### PR TITLE
swaylock-effects: fix build

### LINKED ISSUE #338879: Build failure: swaylock-effects
### Steps To Reproduce

1. build *swaylock-effects*

### Build log

```
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/asg6302fhr0z8b63qc51vl77j2cv9rdw-source
source root is source
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
mesonConfigurePhase flags: --prefix=/nix/store/sxrvzv9fxxcisr1zd4jbirvpqbk0zn9h-swaylock-effects-1.7.0.0 --libdir=/nix/store/sxrvzv9fxxcisr1zd4jbirvpqbk0zn9h-swaylock-effects-1.7.0.0/lib --libexecdir=/nix/store/sxrvzv9fxxcisr1zd4jbirvpqbk0zn9h-swaylock-effects-1.7.0.0/libexec --bindir=/nix/store/sxrvzv9fxxcisr1zd4jbirvpqbk0zn9h-swaylock-effects-1.7.0.0/bin --sbindir=/nix/store/sxrvzv9fxxcisr1zd4jbirvpqbk0zn9h-swaylock-effects-1.7.0.0/sbin --includedir=/nix/store/sxrvzv9fxxcisr1zd4jbirvpqbk0zn9h-swaylock-effects-1.7.0.0/include --mandir=/nix/store/sxrvzv9fxxcisr1zd4jbirvpqbk0zn9h-swaylock-effects-1.7.0.0/share/man --infodir=/nix/store/sxrvzv9fxxcisr1zd4jbirvpqbk0zn9h-swaylock-effects-1.7.0.0/share/info --localedir=/nix/store/sxrvzv9fxxcisr1zd4jbirvpqbk0zn9h-swaylock-effects-1.7.0.0/share/locale -Dauto_features=enabled -Dwrap_mode=nodownload --buildtype=plain -Dpam=enabled -Dgdk-pixbuf=enabled -Dman-pages=enabled
The Meson build system
Version: 1.5.1
Source dir: /build/source
Build dir: /build/source/build
Build type: native build
Project name: swaylock
Project version: 1.7.0.0
C compiler for the host machine: gcc (gcc 13.3.0 "gcc (GCC) 13.3.0")
C linker for the host machine: gcc ld.bfd 2.42
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: YES (/nix/store/fcmc82gp5qc0s8qvcw4c0w46c67zd295-pkg-config-wrapper-0.29.2/bin/pkg-config) [1;34m0.29.2
Run-time dependency wayland-client found: YES 1.23.0
Run-time dependency wayland-protocols found: YES 1.36
Did not find CMake 'cmake'
Found CMake: mNO
Build-time dependency wayland-scanner found: mNO (tried pkgconfig)

meson.build:38:18: mERROR: Dependency "wayland-scanner" not found, tried pkgconfig

A full log can be found at /build/source/build/meson-logs/meson-log.txt
```

### Additional context

Not exactly sure what the problem might be, since on first glance it appears that the proper build inputs should be there.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
✖ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.6, NixOS, 24.11 (Vicuna), 24.11.20240828.71e91c4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.22.3`
 - nixpkgs: `/nix/store/887hpp8a2i99n9jjwcvz6qkhhhqsvzkg-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by poperigby**
## Description of changes

Fixed `swaylock-effects` failing to build because it couldn't find `wayland-scanner`. Also ran `nixfmt-rfc-style` on it.

fixes #338879

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by newAM** [comment]
Result of `nixpkgs-review pr 338876` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>swaylock-effects</li>
  </ul>
</details>

**Review by newAM — APPROVED** [review]

**Review by eclairevoyant — CHANGES_REQUESTED** [review]
Please keep formatting a separate commit from any build/expression changes.

**Comment by poperigby** [comment]
@eclairevoyant sorry, forgot about that. Done.

**Review by newAM — APPROVED** [review]

**Review by eclairevoyant — APPROVED** [review]

**Comment by etu** [comment]
This now seems fixed in #338960 which was merged to master before this one.

**Pull request closed without merging**
