### PR TITLE
self: drop

### PR DESCRIPTION
**Pull request by Mic92**
This is an unsupported programming language from 2017 that crashes on startup and doesn't build on x86_64. Dropping this without an alias since the alias can potentially shadow self as used in overlays and flakes quite often.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
╭─[~/git/nixpkgs]─[main⇡]                                                       
╰─ ╰─ % ./result/bin/Self                                                       
                                                                                
Internal error: signal 11 code 1 addr 0x8 pc 0x81a7e60.                         
                                                                                
VM Version: 2017.1.13, Sat 09 Sep 23 07:05:58 Linux i386                        
                                                                                
Self process 3299725 on turingmachine has crashed.                              
Do you want to:                                                                 
   1) Quit Self (optionally attempting to write a snapshot)                     
   2) Try to print the Self stack                                               
   3) Try to return to the Self prompt                                          
   4) Force a core dump                                                         
   5) Print the interrupted context registers                                   
Your choice:

**Review by Lassulus — APPROVED** [review]

**Comment by Mic92** [comment]
also doesn't have any maintainers.

**Review by Lassulus — APPROVED** [review]
also the name is very confusing

**Review by flokli — APPROVED** [review]

**Comment by mschwaig** [comment]
I am not using it, but I guess there may be some users since both PRs and issues have been created in the last months at https://github.com/russellallen/self/. Maybe none of them are using Nix though. According to https://github.com/russellallen/self/issues/130#issuecomment-557931784 it is 32-bit only right now and would need work to change that.

Could the package just be renamed to`selflanguage` instead without creating an alias to address the shadowing issue?

I agree that it shouldn't be left as is. I'm not sure if removing it or renaming it would be better.

**Comment by zimbatm** [comment]
It's broken right now so it probably means that nobody is using it. If somebody wants it, it's easy enough to dig it back from history and send another PR.

**Comment by AndersonTorres** [comment]
I have tried to build this a long time ago, because the concepts of  this language are wonderful.
But this lang is basically dead now.

**Pull request merged**
