### PR TITLE
Add several python packages

### PR DESCRIPTION
**Pull request by kalbasit**
###### Motivation for this change

Extracting the new packages from the outdated #64962, and replaces #76952.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by kalbasit** [comment]
@GrahamcOfBorg build h3 python2Packages.h3 python2Packages.timezonefinder python2Packages.snowflake-sqlalchemy python2Packages.snowflake-connector-python python2Packages.oscrypto python2Packages.area python3Packages.h3 python3Packages.timezonefinder python3Packages.snowflake-sqlalchemy python3Packages.snowflake-connector-python python3Packages.oscrypto python3Packages.area

**Comment by jonringer** [comment]
please resolve conflicts

**Comment by kalbasit** [comment]
@GrahamcOfBorg build h3
@GrahamcOfBorg build python2Packages.h3 python2Packages.timezonefinder python2Packages.snowflake-sqlalchemy python2Packages.snowflake-connector-python python2Packages.oscrypto python2Packages.area
@GrahamcOfBorg build python3Packages.h3 python3Packages.timezonefinder python3Packages.snowflake-sqlalchemy python3Packages.snowflake-connector-python python3Packages.oscrypto python3Packages.area

**Comment by kalbasit** [comment]
@GrahamcOfBorg build h3
@GrahamcOfBorg build python2Packages.h3 python2Packages.timezonefinder python2Packages.snowflake-sqlalchemy python2Packages.snowflake-connector-python python2Packages.oscrypto python2Packages.area
@GrahamcOfBorg build python3Packages.h3 python3Packages.timezonefinder python3Packages.snowflake-sqlalchemy python3Packages.snowflake-connector-python python3Packages.oscrypto python3Packages.area

**Review by jonringer — APPROVED** [review]
diff LGTM (although I would prefer some more tests)
commits LGTM

```
[27 built, 136 copied (719.3 MiB), 119.6 MiB DL]
https://github.com/NixOS/nixpkgs/pull/76954
18 package were built:
h3 python27Packages.area python27Packages.h3 python27Packages.oscrypto python27Packages.snowflake-connector-python python27Packages.snowflake-sqlalchemy python37Packages.area python37Packages.h3 python37Packages.oscrypto python37Packages.snowflake-connector-python python37Packages.snowflake-sqlalchemy python37Packages.timezonefinder python38Packages.area python38Packages.h3 python38Packages.oscrypto python38Packages.snowflake-connector-python python38Packages.snowflake-sqlalchemy python38Packages.timezonefinder
```

**Pull request merged**
