### PR TITLE
lua-rtoml: init 0.2

### PR DESCRIPTION
**Pull request by lblasc**
## Description of changes

Lua bindings for the Rust toml crate.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
There are already 3 toml parsers in the luarocks packages with a recent one https://github.com/vhyrro/toml-edit.lua that has the same dependency IIRC. Would it be interesting to join forces ?
Otherwise looks good. cc @mrcjkb who dabbles with the lua package set too

**Comment by lblasc** [comment]
Hey @teto , thank for looking into it, toml-edit.lua has only parser, additionally I need a way to dump lua tables back to toml, I also saw [toml](https://github.com/NixOS/nixpkgs/blob/922a4d82c57d0a3b59031818d2cb7fbc3d04ad6e/pkgs/development/lua-modules/generated-packages.nix#L3101) which has all the functionality but it needs to be linked with libstdc++, which I don't like.

**Review by teto — APPROVED** [review]

**Comment by mrcjkb** [comment]
🤔 is the repository private?
I'm getting 404 for https://github.com/scr1pt0r/lua-rtoml.

> toml-edit.lua has only parser, additionally I need a way to dump lua tables back to toml

I believe @vhyrro plans on implementing that for `toml-edit`, too. So it still might be beneficial to join forces.
Of course, that's entirely up to you 😃.

The PR looks good to me, but I'm confused by the fact that I can't find the source repo.

**Comment by lblasc** [comment]
hey @mrcjkb https://github.com/scr1pt0r/lua-rtoml is private or it is deleted, I've fetched the sources from luarocks and created my fork with minor changes, see https://github.com/lblasc/lua-rtoml

I'm happy evaluate/switch to toml-edit when this functionality is added :)

Please be aware that this library is only 28 lines of rust code! I believe is worth including in nixpkgs.

All lua toml libraries have some uniqueness, and depending on the project, they can be more or less fitting:

`lua-rtoml` - simple lua rast binding to toml crate
`lua-toml` - lua implementation of toml encoder/decoder (incomplete)
`toml` - lua bindings to toml++ 
`toml-edit` - parse toml while preserving comments, spaces and relative order of items

**Comment by mrcjkb** [comment]
> I've fetched the sources from luarocks and created my fork with minor changes

I see. In that case, you may want to contact @scr1pt0r to have `lua-rtoml` removed from the luarocks.org root manifest, so you can add your fork. It's not strictly necessary for this PR to be merged, but the package on luarocks.org is be broken without the source repo. So libraries that depend on it will fail to build without Nix.
An alternative option would be to rename your fork (e.g. to `rtoml-lua`) so that you can publish it to luarocks.org if @scr1pt0r doesn't remove his version.

> I'm happy evaluate/switch to toml-edit when this functionality is added
> 
> Please be aware that this library is only 28 lines of rust code! I believe is worth including in nixpkgs.

That's not what "join forces" means 😅. I think we have a misunderstanding.
We're not trying to dissuade anyone from adding your fork to nixpkgs. We were suggesting you contribute the missing functionality to `toml-edit` or vice versa (`toml-edit` is also a lua binding to the `toml` create that also uses `mlua` and is written in Rust).. Again, that's entirely up to you. I'm happy to see this merged as well.

**Review by mrcjkb — APPROVED** [review]

**Comment by lblasc** [comment]
> > I've fetched the sources from luarocks and created my fork with minor changes
> 
> I see. In that case, you may want to contact @scr1pt0r to have `lua-rtoml` removed from the luarocks.org root manifest, so you can add your fork. It's not strictly necessary for this PR to be merged, but the package on luarocks.org is be broken without the source repo. So libraries that depend on it will fail to build without Nix. An alternative option would be to rename your fork (e.g. to `rtoml-lua`) so that you can publish it to luarocks.org if @scr1pt0r doesn't remove his version.

Actually source is preserved on luarocks, that's how I resurrected this project.
```
$ nix-shell -p luarocks cargo
$ luarocks install lua-rtoml --local
```
And it works :)

Let me know @scr1pt0r if you are willing to let me to take over rock packaging.

> 
> > I'm happy evaluate/switch to toml-edit when this functionality is added
> > Please be aware that this library is only 28 lines of rust code! I believe is worth including in nixpkgs.
> 
> That's not what "join forces" means 😅. I think we have a misunderstanding. We're not trying to dissuade anyone from adding your fork to nixpkgs. We were suggesting you contribute the missing functionality to `toml-edit` or vice versa (`toml-edit` is also a lua binding to the `toml` create that also uses `mlua` and is written in Rust).. Again, that's entirely up to you. I'm happy to see this merged as well.

haha I'm being a lazy comrade, sorry about that :sweat_smile:

**Comment by lblasc** [comment]
> > > I've fetched the sources from luarocks and created my fork with minor changes
> > 
> > 
> > I see. In that case, you may want to contact @scr1pt0r to have `lua-rtoml` removed from the luarocks.org root manifest, so you can add your fork. It's not strictly necessary for this PR to be merged, but the package on luarocks.org is be broken without the source repo. So libraries that depend on it will fail to build without Nix. An alternative option would be to rename your fork (e.g. to `rtoml-lua`) so that you can publish it to luarocks.org if @scr1pt0r doesn't remove his version.
> 
> Actually source is preserved on luarocks, that's how I resurrected this project.
> 
> ```
> $ nix-shell -p luarocks cargo
> $ luarocks install lua-rtoml --local
> ```
> 
> And it works :)
> 
> Let me know @scr1pt0r if you are willing to let me to take over rock packaging.
> 
> > > I'm happy evaluate/switch to toml-edit when this functionality is added
> > > Please be aware that this library is only 28 lines of rust code! I believe is worth including in nixpkgs.
> > 
> > 
> > That's not what "join forces" means 😅. I think we have a misunderstanding. We're not trying to dissuade anyone from adding your fork to nixpkgs. We were suggesting you contribute the missing functionality to `toml-edit` or vice versa (`toml-edit` is also a lua binding to the `toml` create that also uses `mlua` and is written in Rust).. Again, that's entirely up to you. I'm happy to see this merged as well.
> 
> haha I'm being a lazy comrade, sorry about that 😅

Serious answer this time :) I've checked the `toml-edit` source code, it not binding to `toml` crate, there is `toml-edit` crate which is more complex project which preserves comments, spaces and relative order of items, which is nice but I actually don't need those features, quite the opposite.

Let me know if you need anything more from me, I hope you are not disappointed by my lack of contribution to `toml-edit`, unfortunately it complicates simple thing I need, which is the basic toml encoding/decoding taken from rust and available as simple lua module.

**Pull request merged**
