### PR TITLE
treewide: add missing lib inputs

### PR DESCRIPTION
**Pull request by sternenseemann**
This fixes hopefully all remaining missing lib inputs, likely introduced
as a regression by our recent treewide switch from stdenv.lib to lib.
These instances are all I could find using nix-instantiate --parse using
the following command:

    find "$NIXPKGS" -name '*.nix' \
      -and ! -path "$NIXPKGS/pkgs/development/interpreters/python/cpython/docs/template.nix" \
      -and ! -path "$NIXPKGS"'/.git/**' \
      -print0 | xargs -0 nix-instantiate --parse >/dev/null

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Those files should be evaluated by ofborg to cath further regression.

**Comment by sternenseemann** [comment]
I investigated why these files wheren't evaluated by ofborg:

* 06c403e846dca7c06924a1cf754cfa10b608616f removed the attribute `bspwm-unstable`, but forget to remove the file.
* `magnetophonDSP` is an attrset below top level which doesn't use `recurseIntoAttrs`. Fixed in eb1aa4900aa.
* The OCaml compilers are really old and don't have their own package set anymore. The files are imported/callPackaged nowhere as far as I can tell and can probably be deleted.
* `chickenPackages_*` also don't use `recurseIntoAttrs`. Fixed in fb7ec6726ee.
* The files in `pkgs/development/interpreters/lua-5` seem to be unused.
* The beets plugins are managed inside the `beets` nix expression, so regressions there only are noticed if `beets` is built with the respective plugins enabled.
* `libelf-freebsd` is conditionally imported only of FreeBSD as `libelf` meaning only an evaluator with `stdenv.isFreeBSD == true` would notice the regression.
* `pkgs/development/libraries/silgraphite/default.nix` doesn't seem to be imported anywhere.

**Comment by SuperSandro2000** [comment]
> * The beets plugins are managed inside the `beets` nix expression, so regressions there only are noticed if `beets` is built with the respective plugins enabled.

Could we somehow redo it to use recurseIntoAttrs or at least eval an beets with all plugins?

**Comment by sternenseemann** [comment]
> Could we somehow redo it to use recurseIntoAttrs or at least eval an beets with all plugins?

I have an idea for it, but it would be a larger refactor and would probably require feedback from the `beets` maintainers. I'm not sure if it would be easier to do it a separate PR.

**Comment by SuperSandro2000** [comment]
> I'm not sure if it would be easier to do it a separate PR.

Sure, not blocking here.

**Comment by sternenseemann** [comment]
> Sure, not blocking here.

Turns out was pretty simple and doesn't really change anything for users.

Ping @lovesegfault @doronbehar @aszlig @pjones on the beets changes.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 114290` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>magnetophonDSP.MBdistortion: log was empty</li>
  </ul>
</details>
<details>
<summary>
13 packages built:
</summary>
<ul>
<li>chickenPackages.chicken (chickenPackages_5.chicken)</li>
<li>chickenPackages.egg2nix (chickenPackages_5.egg2nix)</li>
<li>chickenPackages_4.chicken</li>
<li>chickenPackages_4.egg2nix</li>
<li>magnetophonDSP.CharacterCompressor</li>
<li>magnetophonDSP.CompBus</li>
<li>magnetophonDSP.ConstantDetuneChorus</li>
<li>magnetophonDSP.LazyLimiter</li>
<li>magnetophonDSP.RhythmDelay</li>
<li>magnetophonDSP.VoiceOfFaust</li>
<li>magnetophonDSP.faustCompressors</li>
<li>magnetophonDSP.pluginUtils</li>
<li>magnetophonDSP.shelfMultiBand</li>
</ul>
</details>

**Comment by lovesegfault** [comment]
I'm not sold on the beets changes to be honest. I'd prefer if we didn't add the plugins attrset to the pkgs top-level, and instead kept it in `beets.passthru.plugins`.

I'm not willing to die on this hill though, if others feel strongly.

**Comment by SuperSandro2000** [comment]
> I'd prefer if we didn't add the plugins attrset to the pkgs top-level, and instead kept it in `beets.passthru.plugins`.

We need to eval them and build them or we don't notice any regressions. Right now they are not building.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 114290` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>2 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>beetsExternalPlugins.check: https://termbin.com/a2bf4</li>
<li>magnetophonDSP.MBdistortion: https://termbin.com/1pbq</li>
  </ul>
</details>
<details>
<summary>
16 packages built:
</summary>
<ul>
<li>beetsExternalPlugins.alternatives</li>
<li>beetsExternalPlugins.copyartifacts</li>
<li>beetsExternalPlugins.extrafiles</li>
<li>chickenPackages.chicken (chickenPackages_5.chicken)</li>
<li>chickenPackages.egg2nix (chickenPackages_5.egg2nix)</li>
<li>chickenPackages_4.chicken</li>
<li>chickenPackages_4.egg2nix</li>
<li>magnetophonDSP.CharacterCompressor</li>
<li>magnetophonDSP.CompBus</li>
<li>magnetophonDSP.ConstantDetuneChorus</li>
<li>magnetophonDSP.LazyLimiter</li>
<li>magnetophonDSP.RhythmDelay</li>
<li>magnetophonDSP.VoiceOfFaust</li>
<li>magnetophonDSP.faustCompressors</li>
<li>magnetophonDSP.pluginUtils</li>
<li>magnetophonDSP.shelfMultiBand</li>
</ul>
</details>

**Review by lovesegfault — APPROVED** [review]

**Review by SuperSandro2000 — APPROVED** [review]
not fully sure about the beets changes

**Comment by lovesegfault** [comment]
Merged since I approved on behalf of beets maintainers.

**Pull request merged**
