### PR TITLE
treewide: mostly noop: refer to `src.name` or similar in `sourceRoot` where appropriate

### PR DESCRIPTION
**Pull request by oxij**
###### Description of changes

This replaces all the uses of `sourceRoot = "source";`, `sourceRoot = "source/subdir";`, and similar in package derivations that use the default `unpackPhase` with `sourceRoot = src.name`, `sourceRoot = "${src.name}/subdir";` and similar.

It also fixes `sourceRoot` and `setSourceRoot` description in the docs to match the implementation, and deprecates the old usage in release notes.

The primary motivation for this change is to make #49862 (or its reverse) trivial to implement.

###### Things done

It's a mostly noop change except for the changes to documentation (which cause `nixos-install-tools` to be rebuilt).

### CODE REVIEW

**Comment by oxij** [comment]
Rebased onto master to fix a conflict with `qrcodegen`, it will get rebuilt now as 0164461684445b87208aa73cf3f456e55e8cb832 started to use `preBuild` for doing the same thing (without good reason, AFAICS).

**Comment by oxij** [comment]
ping @AndersonTorres because of 0164461684445b87208aa73cf3f456e55e8cb832

**Comment by AndersonTorres** [comment]
Sometimes this `sourceRoot=source` convention failed.

**Comment by oxij** [comment]
Eh, well, your change will work if you add `finalAttrs` there, but this is a one-shot fix for the whole Nixpkgs, so I'd rather somebody just merge this. Diff of `nix-env` outputs still shows only `nixos-install-tools`, and now also `qrcodegen` and `notcurses` (it depends on `qrcodegen`) changing. So, still, basically a noop change build-wise.

**Review by AndersonTorres — APPROVED** [review]

**Comment by drupol** [comment]
Just my 2 cents on this but...

I just checked the changes and many `rec` are added where `finalAttrs` pattern could be used. Don't you think it would be better to use directly `finalAttrs` instead?

This is something that (_as a very new Nixpkgs committer/reviewer_) I always try to enforce to new contributors... how about doing it here as well?

**Review by Ma27 — APPROVED** [review]

**Comment by oxij** [comment]
> I just checked the changes and many `rec` are added where `finalAttrs` pattern could be used. Don't you think it would be better to use directly `finalAttrs` instead?

I did use `finalAttrs` in the expression that used them already, I was trying to do the minimal change...

**Comment by drupol** [comment]
> I did use `finalAttrs` in the expression that used them already, I was trying to do the minimal change...

I know, but what I'm saying here is a bit different... I'm saying that we should avoid using `rec` when `finalAttrs` can be used.

**Comment by AndersonTorres** [comment]
In the case of a such treewide change, I vote for do no more than what is intended.

The rec-less style can be done in another moment.

**Comment by AndersonTorres** [comment]
The removal of rec can be done in other PRs.

**Comment by oxij** [comment]
OfBorg seems to be stuck? Pending for eval for 20 hours.

**Comment by oxij** [comment]
@drupol I pushed a new commit that replaces all newly introduced `mkDerivation rec`s with fixpoints. `buildRustPackage` and `buildGoModule` do not support this yet, so can't do that there. I consider changing `rec`s that I did not put there to be out of scope of this PR because that's a lot of package-specific work right there. I hope your objection can be withdrawn now?

**Comment by drupol** [comment]
Excellent, thanks !!!!

**Review by drupol — APPROVED** [review]

**Comment by AndersonTorres** [comment]
> OfBorg seems to be stuck? Pending eval for 20 hours.

aarch64-darwin usually spends days bootstrapping.
Whereas x86_64-darwin dies of timeout :)

**Review by AndersonTorres — APPROVED** [review]

**Comment by oxij** [comment]
Yay! All checks pass, still no conflicts. A prime opportunity to merge. :)

**Comment by AndersonTorres** [comment]
Except merge conflicts.

Maybe because I burned it up :(

**Comment by oxij** [comment]
Rebased.

**Comment by oxij** [comment]
:beers:

**Comment by oxij** [comment]
This now has a continuation in  #247977.

**Comment by ShamrockLee** [comment]
Please take a look at #294334 for yet another cleanup regarding such hard-coding `sourceRoot` specification.

**Pull request merged**
