### PR TITLE
pdal: 2.1.0 -> 2.2.0

### PR DESCRIPTION
**Pull request by nh2**
###### Motivation for this change

https://github.com/PDAL/PDAL/releases/tag/2.2.0

Changelog items are benign.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nh2** [comment]
@GrahamcOfBorg build cloudcompare

**Comment by nh2** [comment]
CloudCompare builds fine for me.

**Comment by sikmir** [comment]
https://github.com/PDAL/PDAL/releases/tag/2.2.0:
> The Zstandard compression library is no longer required in order to build PDAL.

**Comment by nh2** [comment]
> The Zstandard compression library is no longer required in order to build PDAL.

@sikmir This makes no difference for us; it is now _optional_ upstream but we still want it to have zstd support.

**Comment by nh2** [comment]
ofborg built CloudCompare successfully, merging.

**Pull request merged**
