### PR TITLE
nixos/haskell: Added option to the haskell mkDerivation to build quickjump index

### PR DESCRIPTION
**Pull request by mgttlinger**
###### Motivation for this change

When visiting local documentation via hoogle, currently for most packages the quickjump index is missing so you only get a sad error when pressing "s" to search in the current documentation.

###### Things done

Tested building my sytem including `pandoc`, `xmonad`, `xmonad-contrib` (and all their deps) from the new tree andchecked that now quickjump works.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cdepillabout** [comment]
@mgttlinger Thanks for this new feature.  This will definitely come in handy.

Can you rebase this on the `haskell-updates` branch instead of `master`?

-------------------------------------------------------------------------

I think this looks good, but I am somewhat worried about turning it on for all packages.  I have a hazy memory that I've seen quickjump indexes turned off because of some problem with `haddock`.  (Although this could totally be untrue.)

Could you try to build all of our non-broken Haskell packages and see if you can find any other that break?  If not, then I'd be okay with merging this as-is.

Alternatively, you could set it to `false` for now.

Maybe @peti is willing to create a build on hydra for this branch and see what (if anything) breaks?

**Comment by mgttlinger** [comment]
Whoops I guess  I messed up that rebase. Sorry for the spam.

**Comment by mgttlinger** [comment]
I'm gonna close and open a new PR instead of fixing this.

**Comment by jonringer** [comment]
it's common when doing a base branch switch that the delay between you pushing and the setting the new base branch causes all the divergent commits to show up. :(

**Comment by mgttlinger** [comment]
@jonringer Ah I see. Nonetheless this continues in #75942

**Pull request closed without merging**
