### PR TITLE
mozwire: 0.4.1 -> 0.5.1

### PR DESCRIPTION
**Pull request by siraben**
###### Motivation for this change

Change hashes.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
@GrahamcOfBorg build mozwire

**Comment by siraben** [comment]
@zowoq

**Comment by alyssais** [comment]
Test should either be disabled, or the test that tries to do networking should be skipped.

**Comment by siraben** [comment]
Ok, had a conversation with the maintainer of MozWire and they'll remove the test that need networking in the next release, then I'll rename the PR and force-push.

**Comment by siraben** [comment]
I've made the change to version 0.5.1 and added a newline after the inputs for consistency.

**Comment by dywedir** [comment]
Thanks!

**Pull request merged**
