### PR TITLE
pythonPackages.pypoppler: init at 0.12.2

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Doesn't build yet, since it cannot find a header 
```
poppler.override:23:26: fatal error: glib/poppler.h: No such file or directory
```

**Comment by FRidh** [comment]
NIX_CFLAGS_COMPILE was needed.
However, now we get
```
poppler.c: In function 'py_poppler_add_constants':
poppler.c:4504:53: error: 'POPPLER_TYPE_ORIENTATION' undeclared (first use in this function)
   pyg_enum_add(module, "Orientation", strip_prefix, POPPLER_TYPE_ORIENTATION);
                                                     ^
poppler.c:4504:53: note: each undeclared identifier is reported only once for each function it appears in
error: command 'gcc' failed with exit status 1
```

**Comment by FRidh** [comment]
patch doesn't apply yet

**Comment by 22459** [comment]
Not too familiar with github yet, so I'm just going to go ahead and attach this.
It adds a patch file for poppler.c that removes the line that adds the removed enum, and adds the patch file to the nix file.
[diff.txt](https://github.com/NixOS/nixpkgs/files/501315/diff.txt)

**Comment by FRidh** [comment]
and my last comment is outdated, the patch does apply.

**Comment by 22459** [comment]
I have a commit here: [https://github.com/NixOS/nixpkgs/compare/master...22459:pypoppler](https://github.com/NixOS/nixpkgs/compare/master...22459:pypoppler) but I don't know how to integrate that with you.

**Comment by FRidh** [comment]
it seems to indeed be working now, @22459

**Pull request merged**
