### PR TITLE
macvim: 8.2.1719 -> 8.2.3455

### PR DESCRIPTION
**Pull request by leungbk**
-------

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lilyball** [comment]
@leungbk What do you mean by "color escape sequences would be displayed literally"? I just tried taking your PR and building it with the `fzf-vim` plugin enabled and the `:FZF` command looks fine to me, in both the GUI and the terminal versions.

**Comment by leungbk** [comment]
@lilyball This is what I mean:

Screen Shot 2022-02-14 at 18 33 39

I see this with a blank `.bashrc` and the following `shell.nix`:

``` nix
{ pkgs ? import /Users/brian/Projects/nixpkgs { } }:
pkgs.mkShell {
  nativeBuildInputs = [
    pkgs.fzf

    (pkgs.macvim.configure {
      packages.myVimPackage = with pkgs.vimPlugins; {
        start = [ fzf-vim ];
      };
    })
  ];
}


```

I notice something similar when executing `fzf` inside a Vim `:terminal`. Maybe some terminal-related config of mine is interfering?

**Comment by lilyball** [comment]
@leungbk I just can't reproduce this issue. I've tried with both macOS Terminal.app and with Kitty in case there was some terminal difference, and I tried using `nix-shell --pure` too in case the environment mattered. Both `vim` and `mvim` worked correctly every time.

**Comment by leungbk** [comment]
> @leungbk I just can't reproduce this issue. I've tried with both macOS Terminal.app and with Kitty in case there was some terminal difference, and I tried using `nix-shell --pure` too in case the environment mattered. Both `vim` and `mvim` worked correctly every time.

Thanks, I wasn't aware that `--pure` actually did anything on macOS, but once I did that, the problem went away. Then I suppose the PR is ready for review.

**Comment by lilyball** [comment]
It's the sandbox that's different on macOS, `--pure` should behave identically on macOS and Linux. You might want to check your local env vars for anything terminal-related, though I'm not sure what affects MacVim's ability to interpret escape codes coming from external commands.

**Comment by lilyball** [comment]
In any case, reading the diff on the patchfile is difficult because of the double-diff, but it looks like you didn't really change much besides adding `-DMACOS_X_DARWIN`?

If a sanity check of the various embedded languages works (I generally just did a "hello world" print in each language) then that's probably good enough.

**Comment by leungbk** [comment]
> it looks like you didn't really change much besides adding `-DMACOS_X_DARWIN`?

That was actually there before. I didn't need to change the diff in any meaningful way.

**Comment by lilyball** [comment]
Is there anything blocking this PR?

**Comment by leungbk** [comment]
No, it should be good to go.

**Pull request merged**
