### PR TITLE
mailman: 3.3.1 -> 3.3.4 and python3Packages.aiosmtpd: 1.2.1 -> 1.4.2

### PR DESCRIPTION
**Pull request by m1cr0man**
###### Motivation for this change

I encountered an issue with the Mailman management interface (Postorious) which [I contacted the Mailman team](https://gitlab.com/mailman/postorius/-/issues/516) about. They informed me that the Mailman core has to be updated to add new endpoints.

Compiled + deployed + tested the fix on nixos-unstable. Also had to update aiosmtpd to resolve unmet dependencies in the Mailman update

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by m1cr0man** [comment]
Added some comments to hyperkitty + postorious indicating [the core should be on the latest version](https://gitlab.com/mailman/postorius/-/issues/516#note_544571309) before updating.

**Comment by SuperSandro2000** [comment]
Can you change the commit message on the last commit so that it begins with mailman? otherwise LGTM

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 118527` at dc328861 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built successfully:</summary>
  <ul>
    <li>mailman</li>
    <li>python38Packages.aiosmtpd</li>
    <li>python38Packages.mailman</li>
    <li>python38Packages.mailman-hyperkitty</li>
    <li>python39Packages.aiosmtpd</li>
    <li>python39Packages.mailman</li>
    <li>python39Packages.mailman-hyperkitty</li>
    <li>sourcehut.listssrht</li>
  </ul>
</details>
<details>
  <summary>8 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/servers/mail/mailman/default.nix:28:5:
```
   |
28 |     (fetchpatch {
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-include-tests.md">python-include-tests</a>

Consider adding a `checkPhase` for tests, or if not feasible, `pythonImportsCheck`.

Near pkgs/development/python-modules/aiosmtpd/default.nix:26:0:
```
   |
26 |     description = "Asyncio based SMTP server";
   | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-uri-literals.md">no-uri-literals</a>

URI literals are deprecated.
Near pkgs/servers/mail/mailman/default.nix:25:13:
```
   |
25 |       url = https://gitlab.com/mailman/mailman/-/commit/4b206e2a5267a0e17f345fd7b2d957122ba57566.patch;
   |             ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-uri-literals.md">no-uri-literals</a>

URI literals are deprecated.
Near pkgs/servers/mail/mailman/default.nix:29:13:
```
   |
29 |       url = https://gitlab.com/mailman/mailman/-/commit/9613154f3c04fa2383fbf017031ef263c291418d.patch;
   |             ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/servers/mail/mailman/default.nix:32:5:
```
   |
32 |     ./log-stderr.patch
   |     ^
```
</li>
    <li>warning: unused-argument

Unused argument: `lazr_delegates`.
Near pkgs/servers/mail/mailman/default.nix:2:54:
```
  |
2 | , flufl_bounce, flufl_i18n, flufl_lock, lazr_config, lazr_delegates, passlib
  |                                                      ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/servers/mail/mailman/default.nix:24:5:
```
   |
24 |     (fetchpatch {
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-include-tests.md">python-include-tests</a>

Consider adding a `checkPhase` for tests, or if not feasible, `pythonImportsCheck`.

Near pkgs/servers/mail/mailman/default.nix:55:0:
```
   |
55 |     description = "Free software for managing electronic mail discussion and newsletter lists";
   | ^
```
</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 118527` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
8 packages built:
</summary>
<ul>
<li>mailman</li>
<li>python38Packages.aiosmtpd</li>
<li>python38Packages.mailman</li>
<li>python38Packages.mailman-hyperkitty</li>
<li>python39Packages.aiosmtpd</li>
<li>python39Packages.mailman</li>
<li>python39Packages.mailman-hyperkitty</li>
<li>sourcehut.listssrht</li>
</ul>
</details>

**Comment by m1cr0man** [comment]
Thanks for doing the nixpkgs-review and merge :) I'll try to do the review part too from now on, but it was quite late last night when I made the PR

**Pull request merged**
