### PR TITLE
geekbench: 6.2.0 -> 6.3.0

### PR DESCRIPTION
**Pull request by asininemonkey**
## Description of changes

https://www.primatelabs.com/release/geekbench6/

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by illustris — CHANGES_REQUESTED** [review]
```
Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/282939

1 package built:
geekbench
```

LGTM, but please squash into one commit.

**Review by illustris — APPROVED** [review]

**Comment by asininemonkey** [comment]
@michalrus Would you mind giving this a review? Happy to help maintain.

**Review by michalrus — APPROVED** [review]
@asininemonkey LGTM, thank you :) And sure, add yourself to maintainers, if you wish 🙇

**Comment by asininemonkey** [comment]
@michalrus @illustris Apologies for the updated review request. Updated my PR to the latest version and added myself as a maintainer.

**Comment by illustris** [comment]
```
error: hash mismatch in fixed-output derivation '/nix/store/w38xjwidbr5y81d6qy9fppby5jvj2l79-Geekbench-6.3.0-Linux.tar.gz.drv':
         specified: sha256-fbf01qa9wx3k9j8AEqv38fAM3F9tZOcnpH/wa/9rawQ=
            got:    sha256-AXJ5mXGc1RWnIkB13KtIdt7vKETEXowunzQZciQDnzs=
error: 1 dependencies of derivation '/nix/store/6wf536109mb9xyxggazq6nr6yzqg656j-geekbench-6.3.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/wp6wn5scil73hcj1cym7cbhnlwqfzc5f-review-shell.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/282939

1 package failed to build:
geekbench
```

**Comment by asininemonkey** [comment]
@illustris Apologies. Hashes got transposed somehow. Corrected and double-checked locally.

**Review by illustris — APPROVED** [review]

**Comment by illustris** [comment]
> Hashes got transposed somehow

Wrong hashes with valid cache in fixed output derivations are always a pain to identify.

**Comment by pbsds** [comment]
Result of `nixpkgs-review pr 282939` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>geekbench (geekbench_6)</li>
  </ul>
</details>

i also built the aarch64-linux cross

**Pull request merged**
