### PR TITLE
rustc: 1.65.0 -> 1.66.0

### PR DESCRIPTION
**Pull request by figsoda**
###### Description of changes

https://blog.rust-lang.org/2022/12/15/Rust-1.66.0.html

built and tested fd on master (x86_64-linux)

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by figsoda** [comment]
@ofborg build fd

**Comment by tjni** [comment]
Thank you for putting this out so quickly.

/cc @winterqt per https://github.com/NixOS/nixpkgs/pull/190093

**Comment by figsoda** [comment]
I don't have a darwin machine so I can't test the stuff mentioned in https://github.com/NixOS/nixpkgs/pull/190093, feel free to directly push to this pr if you have any changes you want to make

**Comment by winterqt** [comment]
Working on this right now -- need to build 11k packages to collect some info. Hopefully this shouldn't take more than a few hours, but worst case scenario we can just merge and deal with it when we can. (The issue doesn't seem to be fully fixed, but I can't figure out why. Will post more info + ask the Rust folks about it ASAP.)

**Comment by winterqt** [comment]
Turns out building 11k packages wasn't needed to figure out the issue.

I've described the strategy for dealing with this in 70d39d1679e38e018a540de0a582f97e6a89cff7, as well as added a note that I *believe* is correct in ebce964b12f5c99d9f30b2bbe2e0f43e3c4e4713. Let me know if anything is unclear.

cc @zowoq

**Comment by tjni** [comment]
I opened https://github.com/vectordotdev/vector/issues/15627 to track fixing vector when compiled using Rust 1.66.

**Comment by figsoda** [comment]
Thanks @tjni! we should be able to just remove the `#![deny(warnings)]` if upstream doesn't fix the issue before this gets into master

**Comment by figsoda** [comment]
zowoq hasn't had any github acitivity for 10 days, perhaps we can just merge this and fix the issues that might pop up later

**Comment by tjni** [comment]
I'm in favor of merging it.

**Review by tjni — APPROVED** [review]

**Comment by winterqt** [comment]
Just to confirm: does my approach to the libiconv situation make sense to you both, are there any issues? This should cause no breakages right now, but it just makes things easier for us to eventually start only adding it when needed by not propagating it alongside `rustc` (only adding it to the inputs of any Rust package using `buildRustPackage`, as we did previously).

**Comment by tjni** [comment]
It makes sense to me at a high level (I'm not as in tune with the details). To move is in that direction, what needs to happen so that:

1. Rust 1.66 is used to bootstrap.
2. Packages bump their `libc` versions.

**Comment by winterqt** [comment]
I think there may be a typo in your message, or is that a question?

Either way, assuming I understand your question(?) correctly:
1. libiconv being a dependency to build rustc doesn't matter too much here, and will go away when 1.66 is used to bootstrap; it doesn't propagate anymore.
2. Once enough packages in the repo bump their `libc` version, we can go through and find which ones fail without it, and manually add those. I'd say we can maybe start doing this around March? (Just pulled a date out of thin air.)

Does that clarify things?

**Comment by figsoda** [comment]
Makes sense to me as well, we just need to keep an eye on the packages that don't use buildRustPackage as they might still depend on an older version of libc

IIUC removing libiconv from buildRustPackage should also work, would just require a lot more work and we might as well wait a little longer for packages to update their dependencies

**Comment by winterqt** [comment]
> IIUC removing libiconv from buildRustPackage should also work, would just require a lot more work and we might as well wait a little longer for packages to update their dependencies

Exactly, that'll be the next step, per my last comment.

Give me one sec to adjust the commit message, please.

**Comment by winterqt** [comment]
Let me know how those messages sound, adjusted some wording and formatting. Then we should be good to go!

**Comment by figsoda** [comment]
messages & changes both lgtm, thanks!

**Comment by tjni** [comment]
Thanks for the context. This LGTM (though might need to be rebased against latest staging, which should include the cargo auditable changes). I created https://github.com/NixOS/nixpkgs/pull/207451 to fix vector pending upstream fix.

**Pull request merged**
