### PR TITLE
pkgs: some speech-related things

### PR DESCRIPTION
**Pull request by oxij**
###### Motivation for this change

An easy to port from SLNOS.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
Overall LGTM.  Please consider adding the top three commits here (all for speech-tools): https://github.com/dtzWill/nixpkgs/commits/speech

* 2.4 -> 2.5
* run tests
* fix w/musl

**Comment by oxij** [comment]
I amended one line in the last commit (`doCheck` is `true` by default). Other than that, LGTM.

@GrahamcOfBorg build speech-tools

**Comment by dtzWill** [comment]
> `doCheck` is `true` by default

Happy to have you amend it, glad you liked it overall :D.

However I'm not sure doCheck is true by default, maybe that's  an SLNOS-ism?
(I rather like it, though! :+1:)

**Comment by oxij** [comment]
> However I'm not sure doCheck is true by default, maybe that's  an SLNOS-ism?
> (I rather like it, though! :+1:)

Ouch. You are right. It's `false` by default in `stdenv.mkDerivation`, but it is `true` by default in Python's `buildPythonPackage` (so it's Python-ism, not SLNOS-ism). I reset the branch back. Thanks.

**Pull request merged**
