### PR TITLE
linux: use lore URL for netfilter fix, remove linux 6.10 (EOL)

### PR DESCRIPTION
**Pull request by Ma27**
See also https://github.com/NixOS/nixpkgs/pull/350500#discussion_r1811016880

I know that we've already reached the point where bisecting got harder, but perhaps having the correct URL available in the history is still helpful.
If not, I'm also fine with dropping the commit from this PR.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by K900** [comment]
net-next shouldn't get rebased generally, but I don't really care where we get the patch from.

**Comment by Ma27** [comment]
Also pushed a fix for #350681.

> net-next shouldn't get rebased generally, but I don't really care where we get the patch from.

I'm not sure if "shouldn't" is good enough if there's an alternative. @alyssais what's your opinion on this?

**Review by fabianhjr — APPROVED** [review]
lgtm

**Comment by fabianhjr** [comment]
All hydra checks have passed, checked that both the base json and hardened json were removed, hydra did build linux_hardened

**Comment by Ma27** [comment]
Will backport tomorrow unless someone's faster.

**Comment by alyssais** [comment]
> I'm not sure if "shouldn't" is good enough if there's an alternative. @alyssais what's your opinion on this?

Not fussed but lore is probably slightly better until it's in mainline as long as the diff is the same, especially since we could then use fetchurl.

**Comment by Ma27** [comment]
Apologies for the delay, just opened #351145 for that.

**Pull request merged**
