### PR TITLE
gnutar: 1.29 -> 1.30

### PR DESCRIPTION
**Pull request by copumpkin**
Cherry-pick of #32816 to 17.09

Not sure if others even want this in 17.09, but I do, so I'm proposing this and if nobody else wants it, we can just close it 😄

### CODE REVIEW

**Review by Ericson2314 — APPROVED** [review]

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

**Comment by edolstra** [comment]
It's not clear to me that 1.30 is purely a bug fix release. I'd rather not have non-bug fix updates on the release branch, especially when they're stdenv changes.

**Comment by copumpkin** [comment]
@edolstra understandable. My sense is that it's mostly bugfix, with the only new feature being a `--warnings` command-line option. My motivation for putting it here is that if we're going to put out a Nix 1.12 pointing at a 17.09 stable on Darwin, I'd like it to include a gnutar that can produce cross-platform deterministic tarballs, and this is the first version to include that fix. It also natively includes a CVE patch that we were applying manually and a couple of other fixes, but indeed it does seem to have one new feature. If you still think it's a bad idea, I won't put up a fight.

**Comment by FRidh** [comment]
Closing because of inactivity.

**Pull request closed without merging**
