### PR TITLE
snort: Fix version (download error)

### LINKED ISSUE #8065: snort-2.9.7.2 cannot be downloaded -> Fails nixos-rebuild
I did:

```
sudo nix-channel --update
sudo nixos-rebuild test
```

and it gave me:

```
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download snort-2.9.7.2.tar.gz from any mirror
builder for ‘/nix/store/sq9jaai089m8p0w1fgpslkkplld37j0i-snort-2.9.7.2.tar.gz.drv’ failed with exit code 1
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download daq-2.0.4.tar.gz from any mirror
builder for ‘/nix/store/rq38fv4p85xlcydhlvnfiqnclxkfx4vn-daq-2.0.4.tar.gz.drv’ failed with exit code 1
```

Whereas the second one was already reported in #7947 and should be fixed since, but unfortunately it still shows up. I'm not sure, though, whether the patch has already appeared in the unstable channel.

The first issue is still the version which is in master, at this moment. `daq` is on `2.0.5` already, which should fix the issue, seems it is not in the channel yet.

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Fixes #8065 for me. (currently building locally... hopefully I can rebuild my system _now_, after beeing unable to build it for ... I guess 4 weeks now).

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
I just succeeded with `nixos-rebuild test`. Switching now.

**Comment by matthiasbeyer** [comment]
This was fixed in https://github.com/NixOS/nixpkgs/commit/bba6880aa67123f18b22fccce366c6864c4b8e7b , but I think the switch to [SF is bad](http://helb.github.io/goodbye-sourceforge/). Please let us find another solution!

**Comment by vcunat** [comment]
Update is an orthogonal improvement to what I pushed :-)

**Comment by vcunat** [comment]
Another "solution" might be to write upstream to provide stable sources or collect it from a mirror of some random distro (but there it might disappear as well).

**Comment by nckx** [comment]
Isn't [this](https://botbot.me/freenode/nixos/msg/39965454/) what tarballs.nixos.org is for?

**Comment by lethalman** [comment]
Fixed via bba6880a

**Pull request closed without merging**
