### PR TITLE
libreoffice-collabora: init at 24.04.5-4

### PR DESCRIPTION
**Pull request by xzfc**
## Description of changes

This PR is the first step in bringing Collabora Online Development Edition (CODE) to Nixpkgs. CODE is a way to run LibreOffice in the browser.

In this PR, a new `libreoffice` variant is added, in addition to the existing `"fresh"` and `"still"` variants. It is built from the upstream LibreOffice git repository but from a dedicated Collabora branch.

The primary usage of `libreoffice-collabora` is to be used as a dependency of [Collabora Online](https://github.com/CollaboraOnline/online) which I plan to add in a separate PR. Unlike the upstream "fresh" and "still" variants, this variant does not need to be wrapped, since it's not intended to be run as a desktop app. But for testing purposes, you could run it as `./result/lib/collaboraoffice/program/soffice`.

URLs: https://www.collaboraoffice.com https://www.libreoffice.org/download/libreoffice-online/
cc: @K900 @7c6f434c

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by xzfc** [comment]
The `Check pkgs/by-name` complains, but I'm adding a variant of an existing non-`by-name` package. I guess, we should ignore this particular check for this change.

**Comment by 7c6f434c** [comment]
I guess the proper fix is supposed to be something like libreoffice-variants at the top-level as a package set with the variants then inherited from there, but this can be done separately…

**Comment by trofi** [comment]
Looks like `help.nix` file is missing:

```
$ nix build --no-link -f. libreoffice-collabora.srcs.help
error:
       … while calling a functor (an attribute set with a '__functor' attribute)
         at pkgs/applications/office/libreoffice/default.nix:204:12:
          203|     translations = fetchurl srcsAttributes.translations;
          204|     help = fetchurl srcsAttributes.help;
             |            ^
          205|   };

       … from call site
         at lib/trivial.nix:957:7:
          956|     { # TODO: Should we add call-time "type" checking like built in?
          957|       __functor = self: f;
             |       ^
          958|       __functionArgs = args;

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: path 'pkgs/applications/office/libreoffice/src-collabora/help.nix' does not exist
```

**Comment by xzfc** [comment]
Thanks for pointing it, @trofi. It is intended not to have these files for libreoffice-collabora, but I've missed that they were still being referred to in `passthru.srcs`.

Fixup PR: #329877.

**Pull request merged**
