### PR TITLE
emacsMacport: name change and description

### PR DESCRIPTION
**Pull request by ljli**
###### Motivation for this change
See commit description

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dhess** [comment]
With `lowprio`, does `nix-env -u` properly upgrade an installed `emacs25Macport`?

**Comment by ljli** [comment]
Good question actually, I can't test it, but based on the [nix source](https://github.com/NixOS/nix/blob/master/src/nix-env/nix-env.cc#L537) I suspect not. The naming scheme isn't really compatible with our version detection (first "-"-separated section with a number at the beginning marks the beginning of the version part). So maybe we should change the naming scheme to emacs-mac-25.1-6.1. If somebody decides that to be preferable I'll change the PR.

**Comment by matthewbauer** [comment]
Nice catch! It was originally lowPrio but I removed it because I wanted it in the binary cache. Name change seems like the best option.

**Comment by ljli** [comment]
Done

**Comment by periklis** [comment]
Seems ok for me.

**Comment by matthewbauer** [comment]
The URL needs to be updated too.

**Comment by ljli** [comment]
Good catch, fixed. Ideally somebody would test this on mac before applying.

**Comment by periklis** [comment]
@ljli i'll test this later this evening and will give you feedback soon.

**Comment by periklis** [comment]
@ljli i am builing it right know, sorry got late yesterday.

**Comment by ljli** [comment]
Thanks, I hope it's fixed now.

**Comment by periklis** [comment]
@ljli Everything builds and works like a charm.

**Review by LnL7 — APPROVED** [review]

**Comment by vcunat** [comment]
What about backporting this to 17.03 as well?  (Before it gets released, ideally.)

**Comment by vcunat** [comment]
Motivation: https://github.com/NixOS/nixpkgs/issues/24242

**Comment by periklis** [comment]
@vcunat this should be a good idea for darwin-users using the stable channels

**Comment by LnL7** [comment]
I generally don't bother with it because the release channels don't build darwin packages.

**Comment by vcunat** [comment]
They don't get binaries, but I've heard that e.g. in Eelco's company they use(d) the stable channel on Darwin nevertheless.  I don't know if there are many people.  Note that the main motivation was for non-Darwin users, as otherwise nix tries to "upgrade" emacs to to this macport version.

**Comment by LnL7** [comment]
It's darwin only so it won't show up in nix-env, right?

**Comment by vcunat** [comment]
It will be considered if you `allowBroken`.  I took the picking on myself :-)

**Comment by vcunat** [comment]
It's just missing other platforms in `meta.platforms`, so it's *only* considered "broken" everywhere else.

**Comment by LnL7** [comment]
Right didn't think about that case, just wanted to cherry pick it myself. Thanks.

**Pull request merged**
