### PR TITLE
matomo_5: Init at 5.0.2

### PR DESCRIPTION
**Pull request by cheriimoya**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by leona-ya** [comment]
I vote against backporting this. AFAIK there’re some breaking changes in this upgrade and as far as I understand [the LTS Announcement](https://matomo.org/blog/2016/01/announcing-long-term-support-in-matomo-the-analytics-platform-for-your-mission-critical-projects) they still publish security updates for 4.x longer than the EOL of NixOS 23.11

**Comment by cheriimoya** [comment]
You are right, probably makes sense to not backport this in that case.

**Comment by dpausp** [comment]
I'd like to keep Matomo 4 around for this year and add Matomo 5 as a new package (matomo_5). 
Only Matomo 4 updates would be backported to 23.11.

**Review by leona-ya — CHANGES_REQUESTED** [review]
I'm sorry that I haven't explicitly reviewed for so long :/

Can you update to matomo 5.0.2 and also add matomo 5 to the nixos test?

**Comment by leona-ya** [comment]
Hi, are you interested in finishing this PR? Here is a patchset you could apply: https://gist.github.com/leona-ya/42be886b8f849ef24117f603610cd6fc. Otherwise I would take this PR over in a few days. :)

**Review by leona-ya — APPROVED** [review]
Wonderful, thanks a lot! (also added the backport label again)

**Review by dpausp — APPROVED** [review]

**Review by l0b0 — APPROVED** [review]

**Review by 0x4A6F — APPROVED** [review]

**Pull request merged**
