### PR TITLE
wayland: fix IME for electron apps

### PR DESCRIPTION
**Pull request by SaltyKitkat**
###### Description of changes

IME(for example, fcitx5) doesn't work in electron apps under wayland.

And it seems that add flag `--enable-wayland-ime` to electron is a workaround.

I've tested `logseq`, and the flag could fix the IME issue. So I wrote #239306.

And maybe it can also work well for other packages. So I wrote this draft pr, and if you are the user of one of these apps, welcome to share your test result here.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 2xsaiko** [comment]
Result of `nixpkgs-review pr 239392` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>github-desktop</li>
    <li>whalebird</li>
  </ul>
</details>
<details>
  <summary>69 packages built:</summary>
  <ul>
    <li>_1password-gui</li>
    <li>_1password-gui-beta</li>
    <li>armcord</li>
    <li>bitwarden</li>
    <li>brave</li>
    <li>chromium</li>
    <li>chromium.sandbox</li>
    <li>discord</li>
    <li>discord-canary</li>
    <li>discord-development</li>
    <li>discord-ptb</li>
    <li>drawio</li>
    <li>drawio-headless</li>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
    <li>fast-cli</li>
    <li>feishu</li>
    <li>google-chrome</li>
    <li>google-chrome-beta</li>
    <li>google-chrome-dev</li>
    <li>heroic</li>
    <li>heroic-unwrapped</li>
    <li>jitsi-meet-electron</li>
    <li>joplin-desktop</li>
    <li>kuro</li>
    <li>lens</li>
    <li>logseq</li>
    <li>mermaid-filter</li>
    <li>micropad</li>
    <li>netflix</li>
    <li>obsidian</li>
    <li>pandoc-drawio-filter</li>
    <li>pandoc-drawio-filter.dist</li>
    <li>playwright-test</li>
    <li>podman-desktop</li>
    <li>puppeteer-cli</li>
    <li>python310Packages.mkdocs-drawio-exporter</li>
    <li>python310Packages.mkdocs-drawio-exporter.dist</li>
    <li>python310Packages.pytest-playwright</li>
    <li>python310Packages.pytest-playwright.dist</li>
    <li>python311Packages.mkdocs-drawio-exporter</li>
    <li>python311Packages.mkdocs-drawio-exporter.dist</li>
    <li>python311Packages.pytest-playwright</li>
    <li>python311Packages.pytest-playwright.dist</li>
    <li>r2modman</li>
    <li>reveal-md</li>
    <li>schildichat-desktop</li>
    <li>schildichat-desktop-wayland</li>
    <li>session-desktop</li>
    <li>sharedown</li>
    <li>signal-desktop</li>
    <li>signal-desktop-beta</li>
    <li>sitespeed-io</li>
    <li>slack</li>
    <li>teams-for-linux</li>
    <li>todoist-electron</li>
    <li>ungoogled-chromium</li>
    <li>ungoogled-chromium.sandbox</li>
    <li>vhs</li>
    <li>vivaldi</li>
    <li>vscode</li>
    <li>vscode-fhs</li>
    <li>vscode-langservers-extracted</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
    <li>vscodium-fhs</li>
    <li>wayback</li>
    <li>webcord</li>
    <li>webcord-vencord</li>
  </ul>
</details>

**Comment by SaltyKitkat** [comment]
It seems that wayland IME protocol support is related with desktop environment, so maybe this may only work on plasma, and we need different workaround on other DEs.

**Comment by Weathercold** [comment]
Tested English, French, Pinyin and Mozc on Plasma Wayland. VSCode and Whalebird now function properly, but Obsidian crashes when using Mozc.

**Comment by Weathercold** [comment]
I would suggest rebasing the two commits into one since they do the same thing

**Comment by SaltyKitkat** [comment]
> It seems that wayland IME protocol support is related with desktop environment, so maybe this may only work on plasma, and we need different workaround on other DEs.

Closed due to this

**Pull request closed without merging**
