### PR TITLE
nixos/tests: fix #146169

### LINKED ISSUE #146169: Cannot build interactive test driver anymore
### Describe the bug
When building an interactive test driver with `driverInteractive` and running the generated binary, the test just runs without an interactivity.

### Steps To Reproduce
1. `nix-build nixos/tests/abc.nix -A driverInteractive`
2. `result/bin/nixos-test-driver`
3. Observe that the test just starts instead of displaying the interactive prompt.

### Expected behavior

I'd expect to be dropped into the interactive prompt.

### Notify maintainers
cc @roberth as someone who's touched `testing-python.nix` a lot.

### PR DESCRIPTION
**Pull request by marijanp**
###### Motivation for this change
#146169

###### Things done
Added a `interactive` (defaults to false) attribute that can be passed to `setupDriverForTest` which then adds a flag --interactive when calling `wrapProgram`

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Synthetica9 — COMMENTED** [review]
Would really like a `--no-interactive` flag (see https://docs.python.org/3/library/argparse.html, search `--no-foo` in the page, can't seem to link the header directly)

**Comment by marijanp** [comment]
@ofborg test pantheon boot.biosCdrom boot.uefiUsb networking.networkd.static latestKernel.login networking.networkd.dhcpSimple networking.networkd.sit env switchTest hibernate predictable-interface-names.predictable gnome networking.networkd.bridge networking.networkd.privacy plasma5 systemd-networkd-ipv6-prefix-delegation lightdm installer.simple installer.btrfsSimple installer.btrfsSubvols sway networking.networkd.link networking.scripted.privacy

**Comment by marijanp** [comment]
@ofborg test nat.firewall-conntrack networking.scripted.sit networking.networkd.virtual networking.scripted.dhcpSimple firewall firefox networking.scripted.macvlan proxy firefox-esr sddm.default boot.uefiCdrom networking.scripted.static networking.scripted.routes installer.lvm networking.networkd.vlan containers-imperative boot.biosUsb xfce networking.networkd.dhcpOneIf installer.simpleUefiSystemdBoot keymap.qwertz gnome-xorg shadow networking.networkd.macvlan networking.networkd.routes

**Comment by cole-h** [comment]
> Would really like a `--no-interactive` flag (see https://docs.python.org/3/library/argparse.html, search `--no-foo` in the page, can't seem to link the header directly)

Agreed. The `--no-interactive` flag should take precedence over the `--interactive` flag.

**Comment by marijanp** [comment]
> > Would really like a `--no-interactive` flag (see https://docs.python.org/3/library/argparse.html, search `--no-foo` in the page, can't seem to link the header directly)
> 
> Agreed. The `--no-interactive` flag should take precedence over the `--interactive` flag.

Added the `--no-interactive` flag, allowing a user to still run the driver non-interactively after building the `driverInteractive` attribute

**Comment by marijanp** [comment]
@ofborg test nat.firewall networking.scripted.link installer.simpleProvided installer.separateBootFat networking.scripted.virtual printing keymap.azerty keymap.dvorak-programmer boot-stage1 installer.swraid keymap.neo nfs4.simple i3wm udisks2 networking.networkd.loopback containers-ip ecryptfs login installer.simpleLabels php.httpd zfs.installer predictable-interface-names.unpredictable predictable-interface-names.unpredictableNetworkd mutableUsers

**Comment by marijanp** [comment]
@ofborg test pantheon boot.biosCdrom boot.uefiUsb networking.networkd.static latestKernel.login networking.networkd.dhcpSimple networking.networkd.sit env switchTest hibernate predictable-interface-names.predictable gnome networking.networkd.bridge networking.networkd.privacy plasma5 systemd-networkd-ipv6-prefix-delegation lightdm installer.simple installer.btrfsSimple installer.btrfsSubvols sway networking.networkd.link networking.scripted.privacy

**Comment by marijanp** [comment]
@ofborg test nat.firewall-conntrack networking.scripted.sit networking.networkd.virtual networking.scripted.dhcpSimple firewall firefox networking.scripted.macvlan proxy firefox-esr sddm.default boot.uefiCdrom networking.scripted.static networking.scripted.routes installer.lvm networking.networkd.vlan containers-imperative boot.biosUsb xfce networking.networkd.dhcpOneIf installer.simpleUefiSystemdBoot keymap.qwertz gnome-xorg shadow networking.networkd.macvlan networking.networkd.routes

**Comment by marijanp** [comment]
@ofborg test nfs3.simple php.fpm fontconfig-default-fonts networking.scripted.bond nano keymap.dvorak installer.luksroot networking.scripted.bridge docker simple chromium networking.scripted.dhcpOneIf networking.networkd.bond php.pcre nat.standalone openssh networking.scripted.vlan ipv6 installer.separateBoot misc predictable-interface-names.predictableNetworkd networking.scripted.loopback keymap.colemak installer.btrfsSubvolDefault

**Pull request merged**
