### PR TITLE
pulumi-bin: 2.22.0 -> 2.23.2

### PR DESCRIPTION
**Pull request by Trundle**
###### Motivation for this change

New upstream release. Plus every `pulumi` invocation says there is a newer version available.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 117060` at 25fa536f run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build (new failures):</summary>
  <ul>
    <li><a href="https://gist.github.com/aa49d8fe3c3fb7e9cb9934df41ac16a5">pulumi-bin</a></li></li>
  </ul>
</details>

**Comment by veehaitch** [comment]
Result of `nixpkgs-review pr 117060` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>pulumi-bin</li>
  </ul>
</details>

**Comment by Trundle** [comment]
I don't get what's going on here. With a clean store, I can built the package just fine. And rerunning `update.sh` produces the same hashes again.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 117060` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>pulumi-bin</li>
</ul>
</details>

**Review by veehaitch — APPROVED** [review]
Just checkout out the branch manually and executed `nix-build -A pulumi-bin`. Builds and runs fine on macOS 11.2.3.

**Comment by veehaitch** [comment]
Result of `nixpkgs-review pr 117060` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pulumi-bin</li>
  </ul>
</details>

**Review by veehaitch — APPROVED** [review]

**Pull request merged**
