### PR TITLE
pipewire: 0.3.49 -> 0.3.51

### PR DESCRIPTION
**Pull request by jansol**
###### Description of changes

https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.50
https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.51

###### Things done

Works On My Machine :tm: 

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.51

**Comment by SuperSandro2000** [comment]
Also this is not yet targeting staging.

**Comment by K900** [comment]
@jansol I can open a new PR for 0.3.51 and staging if you're busy?

**Comment by jansol** [comment]
Sorry, didn't notice the request to retarget to staging. Updated and retargeted.

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by K900** [comment]
...why is ofborg-eval-lib-tests trying to bootstrap a rustc?

**Comment by jansol** [comment]
I cherry-picked the commits on top of last night's staging, I guess there are some changes in there that have been having build problems.

**Pull request merged**
