### PR TITLE
asciidoctor-with-extensions: init at 2.0.16

### LINKED ISSUE #106364: asciidoctor: add bibtex support
**Describe the bug**
include [asciidoctor-bibtex](https://github.com/asciidoctor/asciidoctor-bibtex) in the asciidoctor package

**Notify maintainers**
@gpyh @nicknovitski

### PR DESCRIPTION
**Pull request by doronbehar**
###### Motivation for this change

Fixes #106364 . Closes https://github.com/NixOS/nixpkgs/pull/106971 . Cleans up a bit the asciidoctor package and create an `asciidoctor-with-extensions` with many extensions enabled.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by nicknovitski — COMMENTED** [review]
Hmm, isn't removing any extensions from the original `asciidoctor` package a breaking change? Maybe instead it should have all extensions and there should be an additional `asciidoctor-slim` package without them? :/

**Comment by doronbehar** [comment]
> Hmm, isn't removing any extensions from the original `asciidoctor` package a breaking change?

That's a good question, I'll tell you why I'm sure it won't break anything: Every extension's documentation mentions that in order to use it's features you have to use the `--require asciidoctor-<extension-name>` flag when calling asciidoctor. Examples:

- https://github.com/asciidoctor/asciidoctor-mathematical#usage
- A similar example: https://docs.asciidoctor.org/reveal.js-converter/latest/setup/ruby-setup/#features-unique-to-the-ruby-cli

So I iterated all packages that use asciidoctor and I checked whether they use such a `-r` or `--require` flag when calling `asciidoctor`, both at the packages' upstream source and downstream. Relevant links:

- https://github.com/doronbehar/nixpkgs/blob/847dceccb8ce68eaff5cbcc7376b2c472c41538f/pkgs/applications/misc/styx/default.nix#L41-L43
- https://github.com/GothenburgBitFactory/timewarrior/blob/d5773b456e6641ec8e54de02cc28b5924cd8dce3/doc/CMakeLists.txt#L9
- https://github.com/newsboat/newsboat/blob/191a352f8ab967a0492081504a2f1fedbb307333/Makefile#L243-L274
- https://github.com/weechat/weechat/blob/a4d560e0aa831dbf321232c17bc13576068a302c/doc/CMakeLists.txt#L25
- `wsjtx` doesn't seem to really depend upon asciidoctor at all so it seems..: https://physics.princeton.edu/pulsar/k1jt/wsjtx.html
- https://gitlab.com/esr/reposurgeon/-/blob/57ea24d2e0659faf583cd4086cac6b100370a3f7/Makefile#L90-93
- https://github.com/awesomeWM/awesome/blob/70524e72faf263cfed18600339431de513d76186/CMakeLists.txt#L245
- https://github.com/B-Lang-org/bsc/blob/61dc0ebbbea3a853d061556ae8828dc16e687e40/release/Makefile#L66
- https://github.com/ccache/ccache/blob/543a919a4cbe641bfce0927609d767bc5fc8ea31/doc/CMakeLists.txt#L12
- https://gitlab.com/esr/tapview/-/blob/3db5983a98946cb3fa0e5b277606c8627d2bb443/Makefile#L25
- https://github.com/Warzone2100/warzone2100/blob/cbe2f73dfeb5912f23a1296de38013b9c186b135/doc/CMakeLists.txt#L109
- https://github.com/iovisor/bpftrace/blob/6330cafd748fd0c6b2c0ea257a2755da673a2848/man/adoc/CMakeLists.txt#L11
- `drdb`: Can't find any reference to asciidoctor in it's `src`.
- `btrbk`: No Github link or alike to place where it uses `asciidoctor`, but it's a very basic manual page creation command.
- https://github.com/NuxPackage/nux/blob/9a516bf2e7b567d35d3a50ab04821c854b64dabc/build.rs#L44-L55
- https://github.com/doronbehar/pistol/blob/8db18927daa004453401bb276c7ddbd3ab1a6ec8/Makefile#L27
- https://codeberg.org/rumpelsepp/webcat/src/commit/57a65558f0affac0b2f8f4831c52964eb9ad5386/man/Makefile
- https://github.com/rnpgp/rnp/blob/773fd7f3dc6affa7760fed7fb82421685cc3a03e/cmake/Modules/AdocMan.cmake#L123
- https://github.com/jirutka/esh/blob/bee2d5e7b8df880eb9c6acabb6745c2a9e4cb5e1/Makefile#L73
- https://github.com/lunaryorn/mdcat/blob/42b2a7c9db04e024f083ebcf7a69bcb269a9339b/build.rs#L30-L35
- https://github.com/BurntSushi/ripgrep/blob/0b36942f680bfa9ae88a564f2636aa8286470073/build.rs#L96-L103

Hence I think it's safe to assume it won't break any build as probably all of them use asciidoctor only for manual pages creation.

I'm converting this PR to target `master` since it doesn't seem to require. I wonder why [your previous](https://github.com/NixOS/nixpkgs/pull/106971) triggered so many rebuilds..

**Comment by doronbehar** [comment]
Sorry for all the review requests, I changed the base branch from `staging` to `master`.

**Comment by doronbehar** [comment]
What say you @nicknovitski ? I think this can be cooked in unstable Nixpkgs, and hopefully maintainers will notice if there are build errors with their packages (I doubt there will be any).

**Comment by doronbehar** [comment]
I'm taking the risk.

**Pull request merged**
