### PR TITLE
Add AWS cli session manager plugin v1.1.54.0

### PR DESCRIPTION
**Pull request by nikuda**
###### Motivation for this change

Added AWS cli plugin Session Manager as a package
https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lexun** [comment]
Is this covered by https://github.com/NixOS/nixpkgs/pull/87165?

**Comment by nikuda** [comment]
@lexun Mostly, the difference is this one works on Mac, so some of the things here can be moved to the other PR but other PR is more complete.

**Comment by ldeck** [comment]
What's the status of this?

**Comment by jiegec** [comment]
Superceded by https://github.com/NixOS/nixpkgs/pull/102103

**Pull request closed without merging**
