### PR TITLE
lgogdownloader: fix build

### LINKED ISSUE #75836: lgogdownloader fails to build
**Describe the bug**
lgogdownloader fails to build on unstable. The configure phase breaks with error
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/build/source/JSONCPP_INCLUDE_DIR
   used as include directory in directory /build/source

-- Configuring incomplete, errors occurred!
```

**To Reproduce**
1. Build lgogdownloader on master/unstable

**Additional context**
Caused by the following commit:
```
256a3735ec776680341ecfff0ce891d056532dec is the first bad commit
commit 256a3735ec776680341ecfff0ce891d056532dec
Author: R. RyanTM <ryantm-bot@ryantm.com>
Date:   Wed Nov 27 17:47:51 2019 -0800

    jsoncpp: 1.9.1 -> 1.9.2

 pkgs/development/libraries/jsoncpp/default.nix | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.87, NixOS, 20.03pre204199.3140fa89c51 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(alex): `""`
 - channels(root): `"nixos-20.03pre205624.8636580d6f4, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change
fixes https://github.com/NixOS/nixpkgs/issues/75836
cc: @alexarice
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by teto** [comment]
maybe sthg to report upstream ```
Testing MemberTemplateIs/BehavesSameAsNamedIs: OK
* Detail of EscapeSequenceTest/writeEscapeSequence test failure:
/build/source/src/test_lib_json/main.cpp(3370): expected == result
  Expected: '["\"","\\","\b","\f","\n","\r","\t","\u0278","\ud852\udf62"]
  '
  Actual  : '["\"","\\","\b","\f","\n","\r","\t","ɸ","𤭢"]
  '
101/102 tests passed (1 failure(s))
make[2]: *** [src/test_lib_json/CMakeFiles/jsoncpp_test.dir/build.make:117: src/test_lib_json
```

**Comment by marsam** [comment]
upstream issue https://github.com/open-source-parsers/jsoncpp/pull/1120

**Review by jonringer — APPROVED** [review]
LGTM

```
[3 built, 3 copied (1.0 MiB), 0.2 MiB DL]
https://github.com/NixOS/nixpkgs/pull/75862
1 package were built:
lgogdownloader
```

**Comment by teto** [comment]
seems like a patch is already available for jsoncpp in the issue you mentioned. You can update the jsonccp package here or contact the maintainers.

**Comment by marsam** [comment]
sure! I've added the patch for aarch64

**Comment by teto** [comment]
thanks !

**Pull request merged**
