### PR TITLE
sbcl: 2.3.2 -> 2.3.4

### PR DESCRIPTION
**Pull request by hraban**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nagy** [comment]
sbcl 2.3.4 has just been released.

**Comment by hraban** [comment]
> sbcl 2.3.4 has just been released.

🤷‍♀️ yep. I'll update the pr.

**Comment by hraban** [comment]
@nagy could you review this one when you get the chance, so we don't have to wait for another release cycle? :)

I've also added a comment explaining how we manage versions, and where that decision was made.

**Review by nagy — APPROVED** [review]
Works fine on x86_64-linux. The slight correction I would make is to merge the two version bump commits together but it should be fine this way too.

**Comment by nagy** [comment]
Works on aarch64-linux as well.

**Review by nagy — APPROVED** [review]

**Comment by 7c6f434c** [comment]
> could you review this one when you get the chance, so we don't have to wait for another release cycle? :)

You got me scared that I missed it for a few weeks!

**Pull request merged**
