### PR TITLE
Pulumi 2.10.2 > 2.14.0

### PR DESCRIPTION
**Pull request by mudrii**
###### Motivation for this change
Update pulumi to lates version and update plugins verion too

###### Things done
Update script with new pulumi version and plugins. add new plugins to pulumi Kafka, TLS etc.

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Please update your commit messages to fit the contributing guide:

```
maintainers: add mudrii
pulumi: 2.10.2 -> 2.14.0
```

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 104992` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pulumi-bin</li>
  </ul>
</details>

**Comment by RaghavSood** [comment]
If you would like to receive maintainer notifications, you should also update `meta.maintainers` in `pulumi/default.nix`

**Comment by mudrii** [comment]
I will close this pull request and will create a new one to accomodate changes

**Pull request closed without merging**
