### PR TITLE
qutebrowser: don't crash on :version command

### LINKED ISSUE #118784: qutebrowser crashes on unstable
I've updated nixpkgs to a recent nixos-unstable (`3d1a7716d7f1fccbd7d30ab3b2ed3db831f43bde`) which contains #116724, #118084, #118263. 

After the update, as soon as I invoke `:version` command in qutebrowser or try to open a downloaded file from qutebrowser or just start it as `qutebrowser -V`, it crashes with an error (`QVersionNumber` part is always the same):

```
Traceback (most recent call last):
  File "/nix/store/h08av6vp71nqx8855p9ih9h8dfk6g65r-qutebrowser-2.1.1/bin/.qutebrowser-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/h08av6vp71nqx8855p9ih9h8dfk6g65r-qutebrowser-2.1.1/lib/python3.8/site-packages/qutebrowser/qutebrowser.py", line 218, in main
    return app.run(args)
  File "/nix/store/h08av6vp71nqx8855p9ih9h8dfk6g65r-qutebrowser-2.1.1/lib/python3.8/site-packages/qutebrowser/app.py", line 105, in run
    print(version.version_info())
  File "/nix/store/h08av6vp71nqx8855p9ih9h8dfk6g65r-qutebrowser-2.1.1/lib/python3.8/site-packages/qutebrowser/utils/version.py", line 850, in version_info
    dist = distribution()
  File "/nix/store/h08av6vp71nqx8855p9ih9h8dfk6g65r-qutebrowser-2.1.1/lib/python3.8/site-packages/qutebrowser/utils/version.py", line 165, in distribution
    dist_version = utils.VersionNumber.parse(info[version_key])
  File "/nix/store/h08av6vp71nqx8855p9ih9h8dfk6g65r-qutebrowser-2.1.1/lib/python3.8/site-packages/qutebrowser/utils/utils.py", line 129, in parse
    return cls(*ver.normalized().segments())
  File "/nix/store/h08av6vp71nqx8855p9ih9h8dfk6g65r-qutebrowser-2.1.1/lib/python3.8/site-packages/qutebrowser/utils/utils.py", line 92, in __init__
    self._ver = QVersionNumber(*args)
TypeError: arguments did not match any overloaded call:
  QVersionNumber(): too many arguments
  QVersionNumber(Iterable[int]): argument 1 has unexpected type 'int'
  QVersionNumber(int): too many arguments
  QVersionNumber(int, int): too many arguments
  QVersionNumber(int, int, int): too many arguments
  QVersionNumber(QVersionNumber): argument 1 has unexpected type 'int'

```

/cc @dotlambda  @rnhmjoj

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
fixes https://github.com/NixOS/nixpkgs/issues/118784

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @wedens

### CODE REVIEW

**Comment by wedens** [comment]
For me, [this commit](https://github.com/qutebrowser/qutebrowser/commit/1a383bb6701ad497a9f7868d4b5f60fd99a4e98e) had fixed the problem, but I had to remove some tests changes, as they failed to apply.

But maybe the commit you used also fixes the problem in a different way.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by dotlambda** [comment]
@wedens Would you mind testing whether this also fixes it?

**Review by rnhmjoj — APPROVED** [review]
I haven't tested but the diff looks good.

**Comment by wedens** [comment]
> @wedens Would you mind testing whether this also fixes it?

Yeah, it does.

**Comment by The-Compiler** [comment]
FYI I released v2.2.0 today with that fix in.

**Pull request merged**
