### PR TITLE
mangayomi: init at 0.3.55

### LINKED ISSUE #282266: Package request: mangayomi
**Project description**

Mangayomi is free an open source manga reader and anime streaming cross-plateform app inspired by Tachiyomi and Aniyomi made with Flutter. It allows users to read manga and watch anime from a variety of sources.

**Metadata**

* homepage URL: https://github.com/kodjodevf/mangayomi
* source URL: https://github.com/kodjodevf/mangayomi/releases/download/v0.1.61/Mangayomi-v0.1.61-linux.AppImage
* license: Apache
* platforms: Windows macos Linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by TomaSajt**
## Description of changes

Closes https://github.com/NixOS/nixpkgs/issues/282266

Supersedes https://github.com/NixOS/nixpkgs/pull/283193

I had to do a pretty ugly hack to make dart work from inside a cmake script.
(I did `--packages=../../../../../../.dart_tool/package_config.json` which is not really pretty, but hey, it works!)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by TomaSajt** [comment]
@ofborg build mangayomi

**Comment by pluiedev** [comment]
Result of `nixpkgs-review pr 286512` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>mangayomi</li>
    <li>mangayomi.debug</li>
    <li>mangayomi.pubcache</li>
  </ul>
</details>

**Review by pluiedev — APPROVED** [review]

**Comment by Daru-san** [comment]
Hi. I have been trying to get the build working, see https://github.com/Daru-san/Snowpkgs/pull/14.
The issues preventing it from building all seemed to be outdated dependencies and now it mostly builds, until this point:
```
mangayomi> [        ] [   +9 ms] Failed obtaining PRETTY_NAME for Linux: PathNotFoundException: Cannot open file, path = '/usr/lib/os-release' (OS Error: No such file or directory, errno = 2)
```

Still searching for a solution, but I wanted to know if I could get any help in finding it.

**Comment by TomaSajt** [comment]
After much struggling, I finally figured out the main issue I was running into: patches don't work on path-based pub dependencies, so I had to force it to use the build-tree.

After that, it was mostly the same as the older version.

**Comment by Daru-san** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 286512`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 3 packages built:</summary>
  <ul>
    <li>mangayomi</li>
    <li>mangayomi.debug</li>
    <li>mangayomi.pubcache</li>
  </ul>
</details>

**Comment by LucasMartinsVieira** [comment]
When building the derivation and running the program either as `./result/bin/mangayomi` or `./result/app/mangayomi/mangayomi`, the application launches to a black screen and remains that way.

**Comment by TomaSajt** [comment]
> When building the derivation and running the program either as `./result/bin/mangayomi` or `./result/app/mangayomi/mangayomi`, the application launches to a black screen and remains that way.

Oh, looks like https://github.com/NixOS/nixpkgs/pull/345404 broke this, should be simple to fix

**Comment by TomaSajt** [comment]
I won't update the package to `0.3.65`, because of build errors related to using `webkitgtk_4_0`

Error:
<pre>
[        ] FAILED: plugins/desktop_webview_window/CMakeFiles/desktop_webview_window_plugin.dir/webview_window.cc.o
[  +18 ms] /nix/store/qajfjv5lnfys2ykm0ggkr4lnnkvgs10r-clang-wrapper-18.1.8/bin/clang++ -DAPPLICATION_ID=\"com.kodjodevf.mangayomi\" -DFLUTTER_PLUGIN_IMPL -DNDEBUG -Ddesktop_webview_window_plugin_EXPORTS -I/build/source/linux/flutter/ephemeral -isystem /nix/store/slm7mb2626vbl9qwq9cgp1ix6szcyqvw-gtk+3-3.24.43-dev/include/gtk-3.0 -isystem /nix/store/59knjxjaqd279yp8z8miw2kis2szql9n-at-spi2-core-2.54.0-dev/include/atk-1.0 -isystem /nix/store/1hhi03gg5jdb2fa5gb9ncklziczax741-glib-2.82.1-dev/include/glib-2.0 -isystem /nix/store/ipqijizc7rqsxifxc6ky16hr5l0hpls2-glib-2.82.1/lib/glib-2.0/include -isystem /nix/store/56888ikq130wkwzg8jdm40r3787ysqgd-cairo-1.18.2-dev/include/cairo -isystem /nix/store/l1shggh8syl6kra49whf8mpjhhd73360-freetype-2.13.3-dev/include/freetype2 -isystem /nix/store/wmbg435clgdlqn4rrn8h5f4jhmhbk24f-gdk-pixbuf-2.42.12-dev/include/gdk-pixbuf-2.0 -isystem /nix/store/774vgpw939f69xb47f2wz31j6di094bp-pango-1.54.0-dev/include/pango-1.0 -isystem /nix/store/sv5fvv7pimim1z48yyy4fs0amr93qg4q-harfbuzz-9.0.0-dev/include/harfbuzz -isystem /nix/store/6z58p7klc803g18fclhl230n36k5ilhk-webkitgtk-2.46.3+abi=4.0-dev/include/webkitgtk-4.0 -isystem /nix/store/d3xfinmn9xj5gr6hvkbm1xiam30pr3b4-libsoup-2.74.3-dev/include/libsoup-2.4 -isystem /nix/store/xrjakm88sn8q139d5m5jknf7yhyavb53-libX11-1.8.10-dev/include -isystem /nix/store/dx8n1ab4h1gvzn17kpbyizgjr8hnsmf1-xorgproto-2024.1/include -isystem /nix/store/cir85maag3aj3sddq35y59m0wmcr50wk-zlib-1.3.1-dev/include -O3 -DNDEBUG -fPIC -fvisibility=hidden -Wall -Werror -O3 -pthread -MD -MT plugins/desktop_webview_window/CMakeFiles/desktop_webview_window_plugin.dir/webview_window.cc.o -MF plugins/desktop_webview_window/CMakeFiles/desktop_webview_window_plugin.dir/webview_window.cc.o.d -o plugins/desktop_webview_window/CMakeFiles/desktop_webview_window_plugin.dir/webview_window.cc.o -c /build/source/linux/flutter/ephemeral/.plugin_symlinks/desktop_webview_window/linux/webview_window.cc
[   +2 ms] /build/source/linux/flutter/ephemeral/.plugin_symlinks/desktop_webview_window/linux/webview_window.cc:313:20: error: no matching function for call to 'g_date_time_to_unix'
[        ]   313 |     auto expires = g_date_time_to_unix(soup_cookie_get_expires(cookie));
[        ]       |                    ^~~~~~~~~~~~~~~~~~~
[        ] /nix/store/1hhi03gg5jdb2fa5gb9ncklziczax741-glib-2.82.1-dev/include/glib-2.0/glib/gdatetime.h:272:25: note: candidate function not viable: no known conversion from 'SoupDate *' (aka '_SoupDate *') to 'GDateTime *' (aka '_GDateTime *') for 1st argument
[        ]   272 | gint64                  g_date_time_to_unix                             (GDateTime      *datetime);
[        ]       |                         ^                                                ~~~~~~~~~~~~~~~~~~~~~~~~
[        ] 1 error generated.
</pre>

**Pull request closed without merging**
