### PR TITLE
[staging-next] cargo,clippy,rustc,rustfmt: 1.81.0 -> 1.82.0

### PR DESCRIPTION
**Pull request by alyssais**
It's early enough in the cycle that we should be able to get this in without rebuilds.

- [x] fd.x86_64-linux
- [x] firefox.x86_64-linux
- [x] thunderbird.x86_64-linux
- [x] fd.aarch64-linux
- [x] fd.x86_64-darwin
- [x] fd.aarch64-darwin

Please help test Darwin!

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by zowoq** [comment]
Built fd.aarch64-darwin, building fd.x86_64-darwin.

**Comment by zowoq** [comment]
Built fd.x86_64-darwin.

**Comment by alyssais** [comment]
Can't reproduce the wezterm failure on aarch64-linux, so I can't even verify it wasn't a pre-existing issue.

**Comment by skeuchel** [comment]
For reference: this broke building rustc on riscv64-linux. The problem as discussed in https://github.com/rust-lang/rust/issues/129268 seems to be that the 1.81.0 bootstrap version cannot build the 1.82.0 compiler.

**Comment by workingjubilee** [comment]
We currently don't build our distributed RV64 host toolchain using our prior RV64 host toolchain, but rather we cross-build from the x86_64.

**Comment by alyssais** [comment]
Nixpkgs has a strong cross/non-cross distinction, so doing that would be difficult for us.

Does bootstrapping 1.82.0 from upstream's 1.82.0 binary work? We should be able to do that for RISC-V native builds if this is important to somebody!

**Comment by skeuchel** [comment]
> Nixpkgs has a strong cross/non-cross distinction, so doing that would be difficult for us.
> 
> Does bootstrapping 1.82.0 from upstream's 1.82.0 binary work? We should be able to do that for RISC-V native builds if this is important to somebody!

Yes, that is what I am doing on my machine now. Not important to me to commit it to nixpkgs. I can just wait for 1.83.

**Comment by alyssais** [comment]
Oh, but this is going to be the Rust release that we stick to for 24.11, hmm…

**Comment by alyssais** [comment]
I guess it can be fixed at any time by somebody who has the hardware to be able to test it.

**Pull request merged**
