### PR TITLE
mailcap: update mime types

### PR DESCRIPTION
**Pull request by Izorkin**
###### Description of changes
Update mime types.
Needed to update zlib/brotli compression settings in nginx.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I am not sure if we should do this or not.

**Comment by pennae** [comment]
> I am not sure if we should do this or not.

don't think we should. `application/manifest+json` is an official type but not being included in the package should be raised with upstream instead, and `text/x-component` is a long-obsolete IE specific type for DHTML.

**Comment by Mindavi** [comment]
Could you explain a bit better why this is needed? Is there like some release notes or wiki page explaining this patch, or does debian do something like this?

**Comment by Izorkin** [comment]
Does anyone know what the MIME type is for "*.inc" files? These files are often found in php code.

**Comment by Izorkin** [comment]
Should I remove `text/x-component` and leave the rest?

**Comment by Izorkin** [comment]
> > I am not sure if we should do this or not.
> 
> don't think we should. `application/manifest+json` is an official type but not being included in the package should be raised with upstream instead, and `text/x-component` is a long-obsolete IE specific type for DHTML.

Mailcap hasn't had any updates for over a year now. 
I'm not sure they'll now pay attention PR in upstream.

**Comment by SuperSandro2000** [comment]
Is there a project which adds mime-types faster than mailcap? Maybe we could switch to that because I don't want to put the maintenance burden of this onto us.

**Comment by Izorkin** [comment]
There is such an variant - https://salsa.debian.org/debian/media-types
No mime types available:
```
application/javascript
application/rss+xml
application/x-web-app-manifest+json
text/vnd.rim.location.xloc
```
Also extensions for type `text/xml` are not specified:
```
cat mime.types | grep 'text/xml'
text/xml
text/xml-dtd
text/xml-external-parsed-entity
```

In package `mailcap`:
```
cat mime.types | grep '^text/xml'
text/xml                                        xml xsd rng
text/xml-external-parsed-entity                 ent
```

**Review by c0bw3b — CHANGES_REQUESTED** [review]
`mailcap` reports the "official" MIME types as registered to IANA.
Adding unofficial associations by patching mailcap is not the way to go.

**Comment by Izorkin** [comment]
> `mailcap` reports the "official" MIME types as registered to IANA. Adding unofficial associations by patching mailcap is not the way to go.

Mailcap contains unofficial MIME types - https://pagure.io/mailcap/blob/master/f/mime.types#_2018

**Comment by Izorkin** [comment]
Adding a new `media-types` package - https://github.com/NixOS/nixpkgs/pull/203433

**Pull request closed without merging**
