### PR TITLE
komikku: init at 1.15.0

### PR DESCRIPTION
**Pull request by chuangzhu**
###### Description of changes

Adopts #196550. `pytest-steps` and `pytest-harvest` aren't in this PR because they aren't actually used (`doCheck = false`).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by AndersonTorres — APPROVED** [review]

**Comment by bobby285271** [comment]
I just pushed https://github.com/NixOS/nixpkgs/pull/218143/commits/92ed5a309d0a8a35e61943bb9c61681c96048d53 in #218143 for this package to use webkitgtk6.0 (because support for 5.0 [is gone in](https://github.com/WebKit/WebKit/blob/webkitgtk-2.40.0/Source/cmake/OptionsGTK.cmake#L224-L236) latest webkitgtk builds), can you test whether this still works on gnome branch? (e.g. I saw https://gitlab.com/valos/Komikku/-/merge_requests/195)

**Comment by chuangzhu** [comment]
@bobby285271 idk if there is any plan for the upstream to upgrade to webkitgtk-6.0, but this patch seems to work

```diff
diff --git a/komikku/debug_info.py b/komikku/debug_info.py
index c72e2efd..834dadbc 100644
--- a/komikku/debug_info.py
+++ b/komikku/debug_info.py
@@ -8,7 +8,7 @@ import platform
 
 gi.require_version('Adw', '1')
 gi.require_version('Gtk', '4.0')
-gi.require_version('WebKit2', '5.0')
+gi.require_version('WebKit', '6.0')
 gi.require_version('Soup', '3.0')
 
 from gi.repository import Adw
@@ -17,7 +17,7 @@ from gi.repository import GLib
 from gi.repository import Gsk
 from gi.repository import Gtk
 from gi.repository import Soup
-from gi.repository import WebKit2
+from gi.repository import WebKit as WebKit2
 
 from komikku.models.database import VERSION as DB_VERSION
 from komikku.utils import check_cmdline_tool
diff --git a/komikku/webview.py b/komikku/webview.py
index 281a183f..a4b57144 100644
--- a/komikku/webview.py
+++ b/komikku/webview.py
@@ -12,13 +12,13 @@ import platform
 import requests
 import time
 
-gi.require_version('WebKit2', '5.0')
+gi.require_version('WebKit', '6.0')
 
 from gi.repository import Gio
 from gi.repository import GLib
 from gi.repository import GObject
 from gi.repository import Gtk
-from gi.repository import WebKit2
+from gi.repository import WebKit as WebKit2
 
 from komikku.servers.exceptions import CfBypassError
 from komikku.utils import get_cache_dir
@@ -52,14 +52,13 @@ class Webview(Gtk.ScrolledWindow):
         self.webkit_webview = WebKit2.WebView()
         self.set_child(self.webkit_webview)
 
-        self.web_context = self.webkit_webview.get_context()
-        self.web_context.set_cache_model(WebKit2.CacheModel.DOCUMENT_VIEWER)
-        self.web_context.set_tls_errors_policy(WebKit2.TLSErrorsPolicy.IGNORE)
-        self.web_context.get_cookie_manager().set_persistent_storage(
+        self.network_session = self.webkit_webview.get_network_session()
+        self.network_session.set_tls_errors_policy(WebKit2.TLSErrorsPolicy.IGNORE)
+        self.network_session.get_cookie_manager().set_persistent_storage(
             os.path.join(get_cache_dir(), 'WebKitPersistentStorage.sqlite'),
             WebKit2.CookiePersistentStorage.SQLITE
         )
-        self.web_context.get_cookie_manager().set_accept_policy(WebKit2.CookieAcceptPolicy.ALWAYS)
+        self.network_session.get_cookie_manager().set_accept_policy(WebKit2.CookieAcceptPolicy.ALWAYS)
 
         self.window.stack.add_named(self, 'webview')
 
@@ -239,7 +238,7 @@ def bypass_cf(func):
                 return
 
             logger.debug(f'{server.id}: Page loaded, getting cookies...')
-            cookie_manager = webview.web_context.get_cookie_manager()
+            cookie_manager = webview.network_session.get_cookie_manager()
             cookie_manager.get_cookies(server.base_url, None, on_get_cookies_finish, None)
 
         def on_get_cookies_finish(cookie_manager, result, user_data):
```

**Comment by bobby285271** [comment]
It looks like the author doesn't have time to finish https://gitlab.com/valos/Komikku/-/merge_requests/195, you can consider sending a new MR to upstream, fetchpatch it here and open a PR against the gnome branch.

(Is this diff really enough? It looks like your patch does not overlap https://gitlab.com/valos/Komikku/-/merge_requests/195 at all, e.g. is the repo contains various sub-programs?)

**Comment by chuangzhu** [comment]
> It looks like your patch does not overlap https://gitlab.com/valos/Komikku/-/merge_requests/195 at all

IDK, things may changed within the past two months. `WebKit.WebContext` doesn't even have a `get_website_data_manager()` method now. All I know is the app launches and [`make test`](https://github.com/NixOS/nixpkgs/files/11072029/testwebkitgtk6.txt) doesn't report any new failures compared to [the result of webkit2gtk-5.0's](https://github.com/NixOS/nixpkgs/files/11072030/testwebkitgtk5.txt). This however raises a new question: is webkitgtk-6.0's API stable yet?

**Comment by bobby285271** [comment]
> things may changed within the past two months

Ah yeah I noticed that now :+1:

> is webkitgtk-6.0's API stable yet

https://webkitgtk.org/2023/03/17/webkitgtk2.40.0-released.html says this should be a stable one

**Pull request merged**
