### PR TITLE
Allow custom tags to be set for datadog monitoring

### PR DESCRIPTION
**Pull request by cransom**
Allow nix to configure datadog tags.

### CODE REVIEW

**Comment by lethalman** [comment]
Can you remove the `types.uniq` ? Clutters the type uselessly.

**Comment by lethalman** [comment]
Ok thanks.

**Comment by copumpkin** [comment]
How does a value of `null` differ from an empty list?

**Comment by mbbx6spp** [comment]
@copumpkin the difference is with a default of `null` no `tags: ` line is added to datadog.conf (and we have previously seen issues with datadog.conf with an empty `tags: ` line). HTH.

**Pull request merged**
