### PR TITLE
meson: 1.4.0 -> 1.4.1

### PR DESCRIPTION
**Pull request by alyssais**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by JohnRTitor** [comment]
@ofborg build meson

**Review by AndersonTorres — COMMENTED** [review]
LGTM.
Needs some Darwin and some BSD to test.

**Comment by alyssais** [comment]
> Needs some Darwin and some BSD to test.

cc @rhelmot @NixOS/darwin-maintainers

**Comment by DontEatOreo** [comment]
Sorry @JohnRTitor, I don't have enough storage on my computer to build this...

image

**Comment by stepbrobd** [comment]
Currently building `mpd` on aarch64-darwin, it'll probably take a couple hours

**Comment by reckenrode** [comment]
Because the Darwin stdenv bootstrap requires Meson, if it gets to the point where ofborg times out building LLVM, then it was able to successfully build Meson on Darwin. Looking at the logs, it appears that was the case here.

**Comment by stepbrobd** [comment]
meson 1.4.1 and llvm 16 build just fine on aarch64-darwin

**Review by stepbrobd — APPROVED** [review]

**Comment by K900** [comment]
Fixed on -next.

**Comment by emilazy** [comment]
I think we have sufficient confidence that this is fine on macOS and we don’t need to block further on that.

**Comment by stepbrobd** [comment]
Quick question: why would `nix build .#meson` build after `gh pr checkout 316178` while `nix build "github:nixos/nixpkgs/refs/pull/316178/merge#meson"` fails to build? Aren't they supposed to build the same thing?

**Comment by emilazy** [comment]
The former would correspond to `/head` rather than `/merge`, so the latter was trying to build the whole broken stdenv bootstrap stuff currently on `staging` (because that’s the target of this PR), whereas the branch itself was presumably based on an earlier revision of `master` for easy testing (I didn’t actually check, but that’s how I do it).

**Comment by JohnRTitor** [comment]
Yup, `nix build "github:nixos/nixpkgs/refs/pull/316178/merge#meson"` should be fixed in its next merge with `staging-next`

**Comment by alyssais** [comment]
Backport: https://github.com/NixOS/nixpkgs/commit/9d76da314b9262ae22086f859f4a815e7b33a54d

**Pull request merged**
