### PR TITLE
 r-modules: update from CRAN state at 2015-04-16T11:23:00+0100

### PR DESCRIPTION
**Pull request by michelk**

### CODE REVIEW

**Comment by peti** [comment]
Test builds run at http://hydra.cryp.to/jobset/nixpkgs/r-packages. I'll merge once the builds are through so that we can be certain no major breakage occurs.

**Comment by michelk** [comment]
Thanks for evaluating. On my local machine, and in the test-builds, I noticed that gdal fails:

    make[2]: Entering directory '/tmp/nix-build-gdal-1.11.2.drv-0/gdal-1.11.2/swig/python'
    python setup.py install 
    running install
    error: can't create or remove files in install directory

    The following error occurred while trying to add or remove files in the
    installation directory:

        [Errno 13] Permission denied: '/nix/store/pbi1lgank10fy0xpjckbdpgacqw34dsz-python-        2.7.9/lib/python2.7/site-packages/test-easy-install-16991.write-test'


On my local machine I worked around it with given write access to that very directory, which did the trick; but I don't know how to properly fix that.

BTW. R version 3.2 has just been released.

**Comment by peti** [comment]
IMHO, this is a bug in `gdal` that should be fixed upstream. The build is not supposed to create files in the python hierarchy. My guess is that the `install` target doesn't honor the prefix that was configured for the build. IMHO, the only way to remedy that issue is to patch the source code (and, preferably, to submit that patch to the package authors for inclusion in a new release).

**Comment by cstrahan** [comment]
This looks very much intentional on `gdal`'s part, but I don't know *why*. IIUC, this patch should suffice:

``` patch
diff --git a/swig/python/GNUmakefile.old b/swig/python/GNUmakefile
index b4d5e90..2160b83 100644
--- a/swig/python/GNUmakefile
+++ b/swig/python/GNUmakefile
@@ -67,11 +67,7 @@ egg:
 	
 install:
 
-ifeq ($(PY_HAVE_SETUPTOOLS),1)
-	$(PYTHON) setup.py install 
-else
 	$(PYTHON) setup.py install --prefix=$(DESTDIR)$(prefix)
-endif
 
 	for f in $(SCRIPTS) ; do $(INSTALL) ./scripts/$$f $(DESTDIR)$(INST_BIN) ; done
 
```

I'm running a build right now, and will push up a commit if the issue is resolved.

**Comment by cstrahan** [comment]
Fixed the gdal problem in 1645795c53807a83561479eebf25bb1adce003ce.

**Pull request closed without merging**
