### PR TITLE
xrootd: provide fuse support (xrootdfs) for Darwin and fix the tests

### PR DESCRIPTION
**Pull request by ShamrockLee**
###### Description of changes

Pass `fuse` into `buildInputs` by defaults and use `fuse = osxfuse` on Darwin.

This should bring no change to the Linux package. However, the Linux package also rebuilds due to the change of the `buildInputs` order.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ShamrockLee** [comment]
@veprbl Could you help take a look?

**Review by veprbl — APPROVED** [review]

**Comment by wegank** [comment]
@ofborg eval

**Comment by gador** [comment]
This seems to break `nixpkgs-review`:
```
$ nix-env --option system x86_64-linux -f /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs -qaP --xml --out-path --show-trace --no-allow-import-from-derivation
error:
       … while querying the derivation named 'hepmc3-3.2.5'

       … while evaluating the attribute 'out.outPath'

       at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/lib/customisation.nix:215:13:

          214|             drvPath = assert condition; drv.${outputName}.drvPath;
          215|             outPath = assert condition; drv.${outputName}.outPath;
             |             ^
          216|           };

       … while evaluating the attribute 'buildInputs' of the derivation 'hepmc3-3.2.5'

       at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:286:7:

          285|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          286|       name =
             |       ^
          287|         let

       … while evaluating the attribute 'buildInputs' of the derivation 'root-6.26.10'

       at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:286:7:

          285|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          286|       name =
             |       ^
          287|         let

       … while evaluating the attribute 'buildInputs' of the derivation 'xrootd-5.5.1'

       at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:286:7:

          285|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          286|       name =
             |       ^
          287|         let

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling 'getOutput'

       at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/lib/attrsets.nix:832:23:

          831|   */
          832|   getOutput = output: pkg:
             |                       ^
          833|     if ! pkg ? outputSpecified || ! pkg.outputSpecified

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling anonymous lambda

       at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:233:13:

          232|       (map (drv: drv.__spliced.hostHost or drv) (checkDependencyList "depsHostHost" depsHostHost))
          233|       (map (drv: drv.__spliced.hostTarget or drv) (checkDependencyList "buildInputs" buildInputs'))
             |             ^
          234|     ]

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling anonymous lambda

       at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/lib/lists.nix:117:29:

          116|   */
          117|   imap1 = f: list: genList (n: f (n + 1) (elemAt list n)) (length list);
             |                             ^
          118|

       … while evaluating call site

       at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/lib/lists.nix:117:32:

          116|   */
          117|   imap1 = f: list: genList (n: f (n + 1) (elemAt list n)) (length list);
             |                                ^
          118|

       … while calling anonymous lambda

       at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:200:81:

          199|   checkDependencyList = checkDependencyList' [];
          200|   checkDependencyList' = positions: name: deps: lib.flip lib.imap1 deps (index: dep:
             |                                                                                 ^
          201|     if lib.isDerivation dep || isNull dep || builtins.typeOf dep == "string" || builtins.typeOf dep == "path" then dep

       … while evaluating call site

       at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:201:8:

          200|   checkDependencyList' = positions: name: deps: lib.flip lib.imap1 deps (index: dep:
          201|     if lib.isDerivation dep || isNull dep || builtins.typeOf dep == "string" || builtins.typeOf dep == "path" then dep
             |        ^
          202|     else if lib.isList dep then checkDependencyList' ([index] ++ positions) name dep

       … while calling 'isDerivation'

       at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/lib/attrsets.nix:576:5:

          575|     # Value to check.
          576|     value: value.type or null == "derivation";
             |     ^
          577|

       error: undefined variable 'hostPlatform'

       at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/pkgs/top-level/all-packages.nix:1606:10:

         1605|     fuse =
         1606|       if hostPlatform.isDarwin then osxfuse
             |          ^
         1607|       else if hostPlatform.isLinux then fuse
```

**Comment by wegank** [comment]
> This seems to break `nixpkgs-review` (from an unrelated PR):
> 
> ```
> $ nix-env --option system x86_64-linux -f /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs -qaP --xml --out-path --show-trace --no-allow-import-from-derivation
> error:
>        … while querying the derivation named 'hepmc3-3.2.5'
> 
>        … while evaluating the attribute 'out.outPath'
> 
>        at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/lib/customisation.nix:215:13:
> 
>           214|             drvPath = assert condition; drv.${outputName}.drvPath;
>           215|             outPath = assert condition; drv.${outputName}.outPath;
>              |             ^
>           216|           };
> 
>        … while evaluating the attribute 'buildInputs' of the derivation 'hepmc3-3.2.5'
> 
>        at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:286:7:
> 
>           285|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
>           286|       name =
>              |       ^
>           287|         let
> 
>        … while evaluating the attribute 'buildInputs' of the derivation 'root-6.26.10'
> 
>        at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:286:7:
> 
>           285|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
>           286|       name =
>              |       ^
>           287|         let
> 
>        … while evaluating the attribute 'buildInputs' of the derivation 'xrootd-5.5.1'
> 
>        at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:286:7:
> 
>           285|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
>           286|       name =
>              |       ^
>           287|         let
> 
>        … while evaluating call site
> 
>        at «none»:0: (source not available)
> 
>        … while calling 'getOutput'
> 
>        at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/lib/attrsets.nix:832:23:
> 
>           831|   */
>           832|   getOutput = output: pkg:
>              |                       ^
>           833|     if ! pkg ? outputSpecified || ! pkg.outputSpecified
> 
>        … while evaluating call site
> 
>        at «none»:0: (source not available)
> 
>        … while calling anonymous lambda
> 
>        at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:233:13:
> 
>           232|       (map (drv: drv.__spliced.hostHost or drv) (checkDependencyList "depsHostHost" depsHostHost))
>           233|       (map (drv: drv.__spliced.hostTarget or drv) (checkDependencyList "buildInputs" buildInputs'))
>              |             ^
>           234|     ]
> 
>        … while evaluating call site
> 
>        at «none»:0: (source not available)
> 
>        … while calling anonymous lambda
> 
>        at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/lib/lists.nix:117:29:
> 
>           116|   */
>           117|   imap1 = f: list: genList (n: f (n + 1) (elemAt list n)) (length list);
>              |                             ^
>           118|
> 
>        … while evaluating call site
> 
>        at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/lib/lists.nix:117:32:
> 
>           116|   */
>           117|   imap1 = f: list: genList (n: f (n + 1) (elemAt list n)) (length list);
>              |                                ^
>           118|
> 
>        … while calling anonymous lambda
> 
>        at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:200:81:
> 
>           199|   checkDependencyList = checkDependencyList' [];
>           200|   checkDependencyList' = positions: name: deps: lib.flip lib.imap1 deps (index: dep:
>              |                                                                                 ^
>           201|     if lib.isDerivation dep || isNull dep || builtins.typeOf dep == "string" || builtins.typeOf dep == "path" then dep
> 
>        … while evaluating call site
> 
>        at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:201:8:
> 
>           200|   checkDependencyList' = positions: name: deps: lib.flip lib.imap1 deps (index: dep:
>           201|     if lib.isDerivation dep || isNull dep || builtins.typeOf dep == "string" || builtins.typeOf dep == "path" then dep
>              |        ^
>           202|     else if lib.isList dep then checkDependencyList' ([index] ++ positions) name dep
> 
>        … while calling 'isDerivation'
> 
>        at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/lib/attrsets.nix:576:5:
> 
>           575|     # Value to check.
>           576|     value: value.type or null == "derivation";
>              |     ^
>           577|
> 
>        error: undefined variable 'hostPlatform'
> 
>        at /home/wogan/.cache/nixpkgs-review/pr-214311/nixpkgs/pkgs/top-level/all-packages.nix:1606:10:
> 
>          1605|     fuse =
>          1606|       if hostPlatform.isDarwin then osxfuse
>              |          ^
>          1607|       else if hostPlatform.isLinux then fuse
> ```
> 
> and here:
> 
> ```
> nixpkgs-review pr 206969
> $ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/206969/head:refs/nixpkgs-review/1
> Von https://github.com/NixOS/nixpkgs
>  + 885bf6b3a46...4f424907226 refs/pull/206969/head -> refs/nixpkgs-review/1  (Aktualisierung erzwungen)
> $ git worktree add /home/wogan/.cache/nixpkgs-review/pr-206969/nixpkgs 89fae351e4a69b429182e6ffdd348202dd28522e
> Bereite Arbeitsverzeichnis vor (losgelöster HEAD 89fae351e4a)
> Aktualisiere Dateien: 100% (33563/33563), fertig.
> HEAD ist jetzt bei 89fae351e4a Merge pull request #210875 from oluceps/update-maple
> $ git merge --no-commit --no-ff 4f424907226c783b9203c5cddcd0a5276980dc79
> Bereits aktuell.
> error: undefined variable 'hostPlatform'
> 
>        at /home/wogan/.cache/nixpkgs-review/pr-206969/nixpkgs/pkgs/top-level/all-packages.nix:1606:10:
> 
>          1605|     fuse =
>          1606|       if hostPlatform.isDarwin then osxfuse
>              |          ^
>          1607|       else if hostPlatform.isLinux then fuse
> (use '--show-trace' to show detailed location information)
> nix --experimental-features nix-command --system x86_64-linux eval --json --impure --no-allow-import-from-derivation --expr (import /nix/store/gn0vlbi471779yizjkvlz87xk71haq0h-nixpkgs-review-2.8.0/lib/python3.10/site-packages/nixpkgs_review/nix/evalAttrs.nix { allowAliases = false; attr-json = /tmp/tmpvjqi88bh; }) failed to run, /tmp/tmpvjqi88bh was stored inspection
> https://github.com/NixOS/nixpkgs/pull/206969 failed to build
> ```

Oh, sorry! I've reverted this, and I'll redo the PR afterwards.

**Comment by ShamrockLee** [comment]
@gador Sorry for the trouble.

I guess it would be better to test it on a real Darwing setup (either bare-metal or virtual) instead of relying on OfBorg.

**Comment by ShamrockLee** [comment]
@wegank Sorry for the trouble.

Just curious, how does revert and redo solves the problem? The code seems the same.

**Comment by wegank** [comment]
> @wegank Just curious, how does revert and redo solves the problem? The code seems the same.

I think `hostPlatform` should be replaced by `stdenv.hostPlatform`.

My PR was just a minimal one, with zero rebuilds on Linux. Feel free to add the tests again.

**Comment by ShamrockLee** [comment]
> My PR was just a minimal one, with zero rebuilds on Linux. Feel free to add the tests again.

That's because the position of `fuse` in the `buildInputs` aren't changed.

I try to place them in alphabetical order, which changes its position when moving it up and causes the rebuild.

**Pull request merged**
