### PR TITLE
[release-23.11] Revert mastodon: 4.2.8 -> 4.2.9

### PR DESCRIPTION
**Pull request by erictapen**
This broke setups with externally run Nginx due to [this change](https://github.com/mastodon/mastodon/releases/tag/v4.2.9):

> Mastodon is now performing stricter checks to prevent client IP address spoofing. This means that if one of your reverse proxy is not on Mastodon's local network, you will need to set TRUSTED_PROXY_IP accordingly, listing the IP address of every trusted reverse-proxy.

See also https://github.com/NixOS/nixpkgs/pull/315952#issuecomment-2140840261

I quickly checked that the version bump doesn't contain to the `db` directory in Mastodon source code, so I'd hope that no Migrations were executed on peoples setups.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Izorkin — APPROVED** [review]

**Review by SuperSandro2000 — APPROVED** [review]
Deployed the original commit cheery-picked on top of stable

**Comment by erictapen** [comment]
@SuperSandro2000 Does that mean you successfully downgraded?

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
Wait, I should read the title completely. We probably need to bite in the sour apple here. 

All subsequent CVE will be rated with the rate limit in mind and that you cannot spoof client IPs. Without that a vulnerability on the same endpoint could be explorable by brute force which on the official version wouldn't be easily possible.

Also the next security update will build on top of that and carrying self cooked patches especially in messy ruby is also a bad solution. 

Better to break this now than later.

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 Does that mean you successfully downgraded?

No, GitHub Mobile cut of the first part of the title and I was like: oh, that's the update I did yesterday successful 😅😂

**Comment by erictapen** [comment]
@SuperSandro2000 Ok, thanks for your opinion. I'd say we close this then and just hope that people running into the issue [find this comment](https://github.com/NixOS/nixpkgs/pull/315952#issuecomment-2140840261).

**Comment by SuperSandro2000** [comment]
I mean that solution is not ideal but I think personally that the alternatives bite is more in the long run 😅

**Pull request closed without merging**
