### PR TITLE
python3Packages.blis: 0.7.2 -> 0.7.3

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

Upgrades to BLIS 0.7.0:

https://github.com/explosion/cython-blis/releases/tag/v0.7.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by danieldk** [comment]
@ofborg build python37Packages.spacy python38Packages.spacy

**Comment by jonringer** [comment]
aarch failure i in dependent package

**Comment by jonringer** [comment]
I don't think openblas likes my 128 cores

```
  Setting up data for gemm. 1000 iters,  nO=384 nI=384 batch_size=2000
  Blis gemm...
  Total: 11032014.6484375
  5.18 seconds
  Numpy (lapack) gemm...
  BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
  BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
  /nix/store/xpc8bwik5ksb21if0viwmvz13rns3kld-setuptools-check-hook/nix-support/setup-hook: line 4:  9565 Segmentation fault      (core dumped) /nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/bin/python3.8 nix_run_setup test
cannot build derivation '/nix/store/mvyffba0hc5cdcj11ixq7zc69mcpql66-python3.8-thinc-7.4.3.drv':
```

**Comment by danieldk** [comment]
> aarch failure i in dependent package

It currently does not make sense to build BLIS on anything else than x86_64. I'll update platforms.

**Comment by danieldk** [comment]
> > aarch failure i in dependent package
> 
> It currently does not make sense to build BLIS on anything else than x86_64. I'll update platforms.

Restricted `platforms` in the second commit.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105327` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>python27Packages.blis</li>
    <li>python37Packages.blis</li>
    <li>python37Packages.spacy</li>
    <li>python37Packages.textacy</li>
    <li>python37Packages.thinc</li>
    <li>python38Packages.blis</li>
    <li>python38Packages.spacy</li>
    <li>python38Packages.textacy</li>
    <li>python38Packages.thinc</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105327` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>python27Packages.blis</li>
    <li>python37Packages.blis</li>
    <li>python37Packages.spacy</li>
    <li>python37Packages.textacy</li>
    <li>python37Packages.thinc</li>
    <li>python38Packages.blis</li>
    <li>python38Packages.spacy</li>
    <li>python38Packages.textacy</li>
    <li>python38Packages.thinc</li>
  </ul>
</details>

**Pull request merged**
