### PR TITLE
qtpass: 1.0.6 -> 1.1.0

### PR DESCRIPTION
**Pull request by annejan**

### CODE REVIEW

**Comment by davidak** [comment]
it compiles and runs on NixOS :+1: 
i was not using it so i can't tell if it works as expected.
but i gt this message at first start:
```
NOTE: THIS IS A DEVELOPMENT VERSION!
It is only intended for test purposes and should NOT be
used in a production environment or with production keys!
```
also later: `gpg: Sorry, we are in batchmode - can't get input`
bildschirmfoto 2016-01-27 um 00 18 19

**Comment by hrdinka** [comment]
@davidak  I can't confirm these problems. Have you setup `gpg-agent` correctly? Which `gpg` version are using?

**Comment by annejan** [comment]
This is probably caused by having a non-graphical pin-entry set for GPG.

QtPass doesn't wrap the pinentry (for obvious security reasons).

You can set a proper graphical pinentry in `~/.gnupg/gpg-agent.conf` as noted in: https://github.com/IJHack/qtpass/blob/master/FAQ.md#i-dont-get-a-passphrase--pin-dialog

Related: https://github.com/IJHack/qtpass/issues/151

**Comment by davidak** [comment]
it was my fault. sorry, my comment was not very helpful.

**Comment by annejan** [comment]
@davidak so can we assume it's correct now?
Although I am missing the graphics in your screenshot.
Might need a qt5svg package or something that might be missing.

**Comment by hrdinka** [comment]
The icon files won't be installed that's why they are missing. I haven't yet noticed that there are any. `make install` won't copy them. We could still copy them manually—where does `qtpass` expect the icons to be?

**Comment by annejan** [comment]
Compiled into the executable.
It's tiny svg's.

Might change in the future but for now the qrc is compiled in.

**Comment by hrdinka** [comment]
I have compiled qtpass with qtsvg locally but I still can't see the icons. Is there any build/config switch to force the use of qtsvg?

Your last update won't build because qtsvg is missing from the derivation's build inputs (and as said before just adding it doesn't seem to be enough).

**Comment by hrdinka** [comment]
Here is the build log http://pastebin.com/2EUknaZJ

**Comment by ttuegel** [comment]
You need to add `qtsvg` to `buildInputs`, yes, but you also need to wrap the executable with `wrapQtProgram` in the `postInstall` phase. This will ensure that all the required runtime dependencies are present.

**Comment by hrdinka** [comment]
@ttuegel thanks—that did it.

@annejan do you wan't to add this change yourself or should I open another PR?

**Comment by annejan** [comment]
Since I'm on mobile, it's probably safer when you do the honours.

**Comment by hrdinka** [comment]
@annjan I have cherry picked your changes to preserve ownership.

The new PR is over here https://github.com/NixOS/nixpkgs/pull/12733

**Pull request closed without merging**
