### PR TITLE
ceph: 18.2.0 -> 18.2.1

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
Changelog: https://docs.ceph.com/en/latest/releases/reef/#v18-2-1-reef

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 281474` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>ceph (ceph-dev)</li>
    <li>ceph-client</li>
    <li>ceph-csi</li>
    <li>ceph.dev (ceph-dev.dev)</li>
    <li>ceph.doc (ceph-dev.doc)</li>
    <li>libceph (ceph.lib ,libceph.dev ,libceph.doc ,libceph.lib ,libceph.man)</li>
    <li>ceph.man (ceph-dev.man)</li>
    <li>qemu_full</li>
    <li>qemu_full.debug</li>
    <li>qemu_full.ga</li>
    <li>sambaFull (samba4Full)</li>
    <li>sambaFull.dev (samba4Full.dev)</li>
    <li>sambaFull.man (samba4Full.man)</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
@ofborg build ceph ceph.passthru.tests

**Review by nh2 — APPROVED** [review]
Changelog looks good, ofborg is happy (ran NixOS tests).

What's not working is `aarch64-linux`:

* https://github.com/NixOS/nixpkgs/pull/281474/checks?check_run_id=20962544866
  * https://logs.ofborg.org/?key=nixos/nixpkgs.281474&attempt_id=b319f27e-113e-4d5c-a345-f35b91343f94
* It worked for the 18.2.0 PR: https://github.com/NixOS/nixpkgs/pull/281858/checks?check_run_id=20823371445

The Python library `watchfiles-0.21.0` seems to timeout in a test on this architecture:

```
error: builder for '/nix/store/kgy19r4gl6bcg1jjla9rvwlpgcfw77qj-python3.10-watchfiles-0.21.0.drv' failed with exit code 1;
       last 10 log lines:
       >         path = os.getenv('WATCHFILES_TEST_PERMISSION_DENIED_PATH') or '/'
       >
       > >       RustNotify([path], False, False, 0, True, True)
       > E       Failed: Timeout >10.0s
       >
       > tests/test_rust_notify.py:317: Failed
       > =========================== short test summary info ============================
       > FAILED tests/test_rust_notify.py::test_ignore_permission_denied - Failed: Timeout >10.0s
       > ====== 1 failed, 150 passed, 2 skipped, 1 deselected in 80.39s (0:01:20) =======
       > /nix/store/in5b9lna5p97wak30r8397645akl5092-stdenv-linux/setup: line 1582: pop_var_context: head of shell_variables not a function context
```

It does seem to build on Hydra with Python 3.11: https://hydra.nixos.org/build/247427896

I don't have an `aarch64` builder so I can't easily investigate this.

I'm approving this PR under the assumption that this failure has nothing to do with Ceph.

**Comment by nh2** [comment]
https://github.com/ofborg build ceph ceph.passthru.tests

Just in case that test is flaky and works upon rebuild.

**Comment by nh2** [comment]
@GrahamcOfBorg  build ceph ceph.passthru.tests

Just in case that test is flaky and works upon rebuild.

**Comment by fpletz** [comment]
Strangely, ceph builds for me on `aarch64-linux` but the NixOS tests fail due to missing python modules on some services.

**Comment by nh2** [comment]
> but the NixOS tests fail due to missing python modules on some services.

@fpletz Can you post the output?

**Comment by nh2** [comment]
I force-pushed the PR to rebase on the merged PR #281858 with my Ceph GCC fixes.

**Comment by nh2** [comment]
@GrahamcOfBorg build ceph ceph.passthru.tests

**Comment by srhb** [comment]
Looks good to me. I can try to get at an aarch64-linux if we think there's truly a problem?

**Comment by srhb** [comment]
By the way, I also see (racy) failures of ceph-mgr modules (also in prod, sadly) which seem related to the internal subinterpreter struggle, but worsened by pyo3 updates, but I've yet to see a complete test failure because of it. That may just be nondeterminism in the mgr module ordering though, I suppose.

**Comment by nh2** [comment]
Ofborg now succeeds on `aarch64-linux`: 

https://github.com/NixOS/nixpkgs/pull/281474/checks?check_run_id=21247371804

I upgraded a test cluster from 16.2.7 to 18.2.1 based on this commit, so this is good enough to merge now.



> By the way, I also see (racy) failures of ceph-mgr modules (also in prod, sadly) which seem related to the internal subinterpreter struggle, but worsened by pyo3 updates, but I've yet to see a complete test failure because of it. That may just be nondeterminism in the mgr module ordering though, I suppose.

@srhb Thanks for the info!

I hope Ceph fixes this issue.

Personally I enjoy that I saw the Ceph dashboard for the first time yesterday on my cluster on 18.2.1 :)

**Comment by srhb** [comment]
We should backport this, right?

**Comment by nh2** [comment]
> We should backport this, right?

I think so; I added the tag.

**Pull request merged**
