### PR TITLE
vhs: init at 0.1.1

### PR DESCRIPTION
**Pull request by maaslalani**
###### Description of changes

Init VHS at `v0.1.1`

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by winterqt** [comment]
I know this is marked as a draft -- but I figured I'd mention something: according to the README, VHS depends on ffmpeg and ttyd.

I think it would be good for UX if we wrap the binary with these programs in its PATH, so things will just work when users, for example, launch a shell with `vhs`.

**Comment by winterqt** [comment]
Any clue what's up with the dependencies, btw? We're using Go 1.19, so not sure why `go mod vendor` is saying we aren't...

**Comment by maaslalani** [comment]
@winterqt Thanks!

> I think it would be good for UX if we wrap the binary with these programs in its PATH,

I agree we should definitely package the dependencies with this one.

> Looks like it succeeded on your machine

It actually didn't succeed on my machine, I wasn't able to successfully build it. I was also getting some errors about not having the correct Go version, so I tried using `{ buildGoModule = buildGo118Module }` but that didn't work either.

**Comment by winterqt** [comment]
Hmm.

If you run `go mod vendor` from this tag just like, on your dev machine (not in a Nix build), does it succeed?

Also: where's that hash from, then?

**Comment by winterqt** [comment]
Oh, I misread the logs, disregard my last comment.

Strange. I presume the project builds fine with Go 1.19 outside of Nix?

**Comment by winterqt** [comment]
> vendor/golang.org/x/sys/unix/syscall.go:83:16: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)

It just seems so weird -- why would it be set to 1.16...?

**Comment by maaslalani** [comment]
> > vendor/golang.org/x/sys/unix/syscall.go:83:16: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
> 
> It just seems so weird -- why would it be set to 1.16...?

Could it be due to setting the go.mod to 1.16 here?

https://github.com/charmbracelet/vhs/blob/main/go.mod#L3

**Comment by maaslalani** [comment]
> Oh, I misread the logs, disregard my last comment.
> 
> Strange. I presume the project builds fine with Go 1.19 outside of Nix?

Yes, builds fine without nix using Go 1.19 on my machine.

**Comment by winterqt** [comment]
> Could it be due to setting the go.mod to 1.16 here?

If a dependency requires Go 1.18+, how does it being set to 1.16 even work at all?

**Comment by maaslalani** [comment]
@winterqt Ready for review!

**Comment by maaslalani** [comment]
Problems were fixed by: https://github.com/charmbracelet/vhs/pull/84

**Comment by winterqt** [comment]
@maaslalani Can you please wrap the binary to include the binaries needed at runtime in PATH, as discussed earlier?

**Comment by winterqt** [comment]
Force-pushed to address some formatting nits, as well as fix the commit message to correctly reflect the version:
```diff
diff --git a/pkgs/applications/misc/vhs/default.nix b/pkgs/applications/misc/vhs/default.nix
index 4c0dfb0b6b4..e7b81632740 100644
--- a/pkgs/applications/misc/vhs/default.nix
+++ b/pkgs/applications/misc/vhs/default.nix
@@ -1,12 +1,14 @@
 { lib, buildGoModule, installShellFiles, fetchFromGitHub, ffmpeg, ttyd, makeWrapper }:
+
 buildGoModule rec {
   pname = "vhs";
   version = "0.1.1";
+
   src = fetchFromGitHub {
     owner = "charmbracelet";
     repo = pname;
     rev = "v${version}";
-    sha256 = "sha256-wcOLUA/U+xRwo7slnACCURQO7D0F3pFP2/SHDfEHeTA=";
+    hash = "sha256-wcOLUA/U+xRwo7slnACCURQO7D0F3pFP2/SHDfEHeTA=";
   };
 
   vendorSha256 = "sha256-f8EHDxu+NWAFJx9ujzsiDhNymdEzExmdreP11gV56AI=";
```

**Review by winterqt — APPROVED** [review]

**Comment by maaslalani** [comment]
Thank you so much @winterqt! Very much appreciated!

**Pull request merged**
