### PR TITLE
rofi: 1.4.2 -> 1.5.0

### PR DESCRIPTION
**Pull request by matthiasbeyer**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Does not build on my machine... though I have no time to investigate right now.

Feel free to reuse this patch.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
btw: Building fails because one test fails.

**Comment by andir** [comment]
@GrahamcOfBorg build rofi

**Comment by andir** [comment]
nitpick: The URL is outdated. If you visit the homepage noted in the meta attributes then you will be greeted with a deprecation warning and shortly after that redirected to the GitHub repository.

So far I suspect the reason the (gtk settings) test is failing to be because our sandboxed builders do not have a proper $HOME? I'll try to investigate further soon.

**Comment by teto** [comment]
changelog for the curious https://github.com/DaveDavenport/rofi/blob/next/Changelog

**Comment by Mic92** [comment]
@GrahamcOfBorg build rofi

**Comment by matthiasbeyer** [comment]
@GrahamcOfBorg build rofi

**Comment by andir** [comment]
@GrahamcOfBorg build rofi

**Comment by matthiasbeyer** [comment]
I don't even understand what the error is...

and why does github say "All checks have passed" despite the bot failing?

**Comment by andir** [comment]
The @grahamcofborg builds are not part of the normal github checks. 

The Mac build most likely fails because some Mac specific library isn't being linked.. I doubt the previous versions did build there.

**Comment by Mic92** [comment]
According to the logs on `x86_64` one test fails.

**Comment by andir** [comment]
Yes ,that is the "subprojects/libnkutils/tests/gtk-settings.test" which was introcuded with this bump IIRC.

It probably assumes the ability to write to $HOME which might not be writable during test execution/at all?

**Comment by 7c6f434c** [comment]
Well, `$HOME` can be set to something inside the build directory before running the tests.

**Comment by 7c6f434c** [comment]
Maybe the test requires X? I guess we generally just disable such tests, although in principle `xdummy` could be an option.

**Comment by Mic92** [comment]
Maybe try this?
`preConfigure = "export HOME=$(mktemp -d)"`

**Comment by matthiasbeyer** [comment]
With the change suggested by @Mic92 this fails still:


```
FAIL: subprojects/libnkutils/tests/gtk-settings
===============================================

/nkutils/gtk-settings/4.0/boolean: **
ERROR:subprojects/libnkutils/tests/gtk-settings.c:100:_nk_gtk_settings_tests_func: 'ret' should be TRUE
FAIL
/nkutils/gtk-settings/4.0/uint64: **
ERROR:subprojects/libnkutils/tests/gtk-settings.c:112:_nk_gtk_settings_tests_func: 'ret' should be TRUE
**
ERROR:subprojects/libnkutils/tests/gtk-settings.c:113:_nk_gtk_settings_tests_func: assertion failed (value == data->value.int64): (3530962845198832513 == 300)
FAIL
/nkutils/gtk-settings/4.0/string: **
ERROR:subprojects/libnkutils/tests/gtk-settings.c:121:_nk_gtk_settings_tests_func: 'ret' should be TRUE
FAIL subprojects/libnkutils/tests/gtk-settings.test (exit status: 139)
```

Homepage updated, though.

**Comment by yegortimoshenko** [comment]
Superseded by 7c4886d6859f328acd1646bc4e9432dc64419aeb, c7adb9ddc8e52bde7daed633e7ef0f5cbf36f4cb.

**Pull request closed without merging**
