### PR TITLE
Update tensorflow-haskell dependencies.

### PR DESCRIPTION
**Pull request by mikesperber**
Updating to the current HEAD of the Tensorflow-Haskell bindings allows
us to also update the dependencies, specifically proto-lens, and avoid
having to retain their outdated versions.

###### Motivation for this change

I finally got patches into the Tensorflow Haskell bindings to update the dependencies. This enables removing lots of cruft.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cdepillabout** [comment]
@GrahamcOfBorg build haskellPackages.tensorflow-proto
@GrahamcOfBorg build haskellPackages.tensorflow
@GrahamcOfBorg build haskellPackages.tensorflow-core-ops
@GrahamcOfBorg build haskellPackages.tensorflow-logging
@GrahamcOfBorg build haskellPackages.tensorflow-mnist
@GrahamcOfBorg build haskellPackages.tensorflow-opgen
@GrahamcOfBorg build haskellPackages.tensorflow-ops

**Comment by cdepillabout** [comment]
Thanks for updating this.

Can you mark the following Haskell packages as non-broken in pkgs/development/haskell-modules/configuration-hackage2nix.yaml around line 9900?  (All you need to do is remove these lines from that file)

- tensorflow
- tensorflow-core-ops
- tensorflow-logging
- tensorflow-ops

**Comment by mikesperber** [comment]
@cdepillabout Done.

**Comment by cdepillabout** [comment]
Thanks, looks like these all compile!

**Comment by cdepillabout** [comment]
Oops, it looks like `tensorflow-mnist` is still marked broken in `hackage-packages.nix`, even though it is not in the list of `broken-packages` in `configuration-hackage2nix.yaml`.

I'm not sure why this would be the case.  Maybe you can try running `cabal2nix` on the commandline and seeing if you can figure out why it would be generated with `broken = true`.

If you can't figure it out, we can ask peti.

**Comment by mikesperber** [comment]
@cdepillabout Good catch, thanks!

I suspect that's because the `tensorflow-mnist-input-data` dependency, which is not on Hackage, and hence only defined in `configuration-tensorflow.nix` - cabal2nix doesn't know about it.

I suggest just unbreaking it in `configuration-tensorflow.nix` - you OK with that? Then I could make another patch.

**Comment by cdepillabout** [comment]
> I suggest just unbreaking it in configuration-tensorflow.nix

Yeah, that is probably the easiest thing to do right now.

Although, the better thing would be to actually get it on Hackage.  I guess it doesn't make sense to have packages on Hackage if they have dependencies that are not on Hackage.  Although I don't know why `tensorflow-mnist-input-data` isn't on Hackage in the first place.

**Comment by mikesperber** [comment]
@cdepillabout I've asked:

https://github.com/tensorflow/haskell/issues/260

**Comment by mikesperber** [comment]
@cdepillabout So I've written to LeCun, but the whole process - if it's successful at all - will take a while.

OK, in the meantime, to just unbreak tensorflow-mnist?

**Comment by cdepillabout** [comment]
@mikesperber It would probably be easier just to take out the `tensorflow-mnist` package.  It sounds like the authors are saying it was an example package and never meant to be on Hackage.

**Pull request merged**
