### PR TITLE
make-symlinks-relative: run on all outputs

### PR DESCRIPTION
**Pull request by Artturin**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by OmnipotentEntity** [comment]
Reading the commit, it seems like this makes symlinks in "man" relative in addition to those in "out".

@Artturin is this in response to any particular issue or RFC?  This is a reasonably small change, but it touches a lot of packages.  It would be nice to be able to confirm any particular problem is fixed and confirm whether or not this breaks anything.

**Comment by Artturin** [comment]
> Reading the commit, it seems like this makes symlinks in "man" relative in addition to those in "out".
> 
> @Artturin is this in response to any particular issue or RFC? This is a reasonably small change, but it touches a lot of packages. It would be nice to be able to confirm any particular problem is fixed and confirm whether or not this breaks anything.


If you want to know the reason why this hook is useful then read the msg of https://github.com/NixOS/nixpkgs/commit/cb007e69a140eb990ba9b2856a6ca211da653d27

I don't believe this will break anything because the original hook didn't break anything either

**Comment by Artturin** [comment]
The test passes

**Comment by OmnipotentEntity** [comment]
Sorry for leaving you hanging.  It does look good to me, for what it's worth.

**Pull request merged**
