### PR TITLE
yubikey-touch-detector: add icon

### PR DESCRIPTION
**Pull request by AndrewKvalheim**
###### Description of changes

As explained in maximbaz/yubikey-touch-detector#25, YubiKey touch detector doesn't include an icon but is intended to be paired with one by the user or packager.

Following the example of alpinelinux/aports@1f596c2, this derives an icon from the assets of [Yubico Authenticator](https://github.com/Yubico/yubioath-flutter/tree/yubioath-desktop-5.0.0):

> screenshot

I’m not sure if this is the right way to package this.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`?
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests)
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`.
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
I would just use a basic `fetchurl` and put it inside the main expression (so not in a different file).

**Comment by AndrewKvalheim** [comment]
Thanks, something more like that? Feel free to edit directly if that’s easier.

**Comment by Kranzes** [comment]
Yup, that looks good.

**Review by sumnerevans — APPROVED** [review]

**Comment by sumnerevans** [comment]
Tested locally and it works nicely

**Pull request merged**
