### PR TITLE
mariadb rework (WIP)

### PR DESCRIPTION
**Pull request by vcunat**
###### Motivation for this change

We've had quite some split-related problems with the default mysql provider lately; most recently we're unable to update our vulnerable version #17340.
###### Things done
- [x] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
#### TODO:
- [ ] check other libmysqlclient users for problems similar to Qt, as headers for it are on a separate prefix now.
- [ ] find a less radical solution for (possible) 16.03 vulnerability.

**Comment by vcunat** [comment]
This should've been filed against staging :-/ but I didn't expect this PR to be merged by the green button anyway.

**Comment by copumpkin** [comment]
Why is this a mass rebuild?

**Comment by vcunat** [comment]
Well, it rebuilds all Qt, but that's probably not too much actually.

**Comment by vcunat** [comment]
There might be some problems, but I staged it already.

**Comment by vcunat** [comment]
Now it's in master.

**Pull request closed without merging**
