### PR TITLE
notmuch: build with gmime2 for now

### PR DESCRIPTION
**Pull request by flokli**
see #39124 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by flokli** [comment]
please backport to 18.03 as well.

**Comment by oxij** [comment]
This PR will break notmuch show --decrypt. See

Subject: bug: notmuch show --decrypt leads to SIGSEGV
Date: Tue, 15 Aug 2017 10:37:31 -0700

on notmuch ML.

I would temporary disable tests instead.

**Comment by flokli** [comment]
@oxij can you check if disabling tests as in https://github.com/flokli/notmuch/commit/f7dc4cf8958702d338763364281802e9487f2eaf keeps `notmuch show --decrypt` working?

**Comment by oxij** [comment]
Why not just set `doCheck = false;`?

**Comment by flokli** [comment]
Yes, you could use that as well to test whether `notmuch show --decrypt` works then.

If I understand [`id:87fu9nc59a.fsf@tethera.net`](https://notmuchmail.org/pipermail/notmuch/2017/025768.html) correctly, the SIGSEGV shouldn't happen with the current notmuch release and gmime 2:
> This is fixed by either using gmime 3.0, notmuch 0.25.2, or notmuch master.

I followed the mailthread [`874lsn6c1h.fsf@oxij.org`](https://notmuchmail.org/pipermail/notmuch/2017/025211.html), seems like you already had similar problems some time ago :-)
Back then, adding `gpgme` fixed it. I'm unsure about why it broke now, and not immediatly after f8078db863bf43a1d2dffa845d884e25a996a679 ;-)

**Comment by oxij** [comment]
Let me cite myself from the thread

> It fixes the SIGSEGV, but, as with my patch, without some more code
> around those NULLs `notmuch search --format=sexp --decrypt` simply
> produces empty bodies (`:body ()`) for suspect messages. That breaks
> rendering of those messages in `notmuch.el` (it fails with some
> exception and stops rendering the rest of the thread; which is better
> than rendering no messages in the thread, but still very far from
> ideal). This solution also doesn't print any content when it could (in
> case of an invalid signature).
>
> Compiling with gmime-3.0.1, on the other hand, works perfectly. It just
> shows that the signature is invalid and that's it, the rest of the
> message and the rest of the thread renders perfectly. The problem with
> gmime-3.0.1, as my other message still stuck in moderation shows, is
> that a lot of other tests fail with some silly differences in the
> produced JSONs.

Did you check that encrypted threads render correctly with gmime2? Last time I checked, they did not.

**Comment by flokli** [comment]
Nah, I didn't use `--decrypt` at all so far.
Is gmime2 with notmuch broken upstream as well?

**Comment by oxij** [comment]
> Is gmime2 with notmuch broken upstream as well?

From the conversations on ML I feel like gmime2 is kinda deprecated. It works for most things, but not for the advanced features (and I, for one, use said advanced features, so I'd like to keep them working).

So, if gmime3 update broke some tests I would just add `doCheck = false` to notmuch expression with a note to remove on update.

**Comment by flokli** [comment]
I simply wasn't sure if it's just the tests that broke or your "advanced features" as well. I will have a more detailed look on it in some hours.

**Comment by oxij** [comment]
Ah. Hm. I don't think it's likely that things will really break if some tests fail with small output differences.

We could also just keep the previous version of gmime3 just for notmuch. (Which is the best solution, IMHO.)

**Comment by flokli** [comment]
@oxij looks like something between [`6fa31b..355d39`](https://hydra.nixos.org/build/73074312) fixed notmuch tests - most likely the gpgme version bump in f76c8427063db7e4d67c95eb8b03cf71949e4fd6.

So no reason to try to build with gmime2 anymore.

**Pull request closed without merging**
