### PR TITLE
nixos/i18n: normalise locale codeset names in supportedLocales

### LINKED ISSUE #179486: glibc locales cause nixos-rebuild to fail
### Steps To Reproduce
1. build the system with the config below

### Build log
[the full log](https://gist.github.com/kofoyo/b58d1a03876904ceb485dc633a76f91d)
```
[...]
zu_ZA/ISO-8859-1 \
Error: unsupported locales detected:
en_US.utf8/UTF-8 \
You should choose from the list above the error.
error: builder for '/nix/store/h4vpgld9amjy8b8fr3y5cnlrnakihfja-glibc-locales-2.34-210.drv' failed with exit code 1
```
This is where the error message comes from. But there hasnt been changed anything recently.

### Additional context
nixos-channel UNSTABLE
configuration.nix :
```
[...]
  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.utf8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "de_DE.utf8";
    LC_IDENTIFICATION = "de_DE.utf8";
    LC_MEASUREMENT = "de_DE.utf8";
    LC_MONETARY = "de_DE.utf8";
    LC_NAME = "de_DE.utf8";
    LC_NUMERIC = "de_DE.utf8";
    LC_PAPER = "de_DE.utf8";
    LC_TELEPHONE = "de_DE.utf8";
    LC_TIME = "de_DE.utf8";
  };
```
(This configuration was created by the gui installer and worked fine so far.)
If I change the locales to uppercase- Stings it also fails, but with a different error message:
```
building Nix...
building the system configuration...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_ADDRESS = "de_DE.utf8",
	LC_NAME = "de_DE.utf8",
	LC_MONETARY = "de_DE.utf8",
	LC_PAPER = "de_DE.utf8",
	LC_IDENTIFICATION = "de_DE.utf8",
	LC_TELEPHONE = "de_DE.utf8",
	LC_MEASUREMENT = "de_DE.utf8",
	LC_TIME = "de_DE.utf8",
	LC_NUMERIC = "de_DE.utf8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
bsdtar: Failed to set default localebsdtar: Failed to set default locale

bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
bsdtar: Failed to set default locale
leaving systemd-boot 250.4 in place (250.4 is not newer)
activating the configuration...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_ADDRESS = "de_DE.utf8",
	LC_NAME = "de_DE.utf8",
	LC_MONETARY = "de_DE.utf8",
	LC_PAPER = "de_DE.utf8",
	LC_IDENTIFICATION = "de_DE.utf8",
	LC_TELEPHONE = "de_DE.utf8",
	LC_MEASUREMENT = "de_DE.utf8",
	LC_TIME = "de_DE.utf8",
	LC_NUMERIC = "de_DE.utf8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
setting up /etc...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_ADDRESS = "de_DE.utf8",
	LC_NAME = "de_DE.utf8",
	LC_MONETARY = "de_DE.utf8",
	LC_PAPER = "de_DE.utf8",
	LC_IDENTIFICATION = "de_DE.utf8",
	LC_TELEPHONE = "de_DE.utf8",
	LC_MEASUREMENT = "de_DE.utf8",
	LC_TIME = "de_DE.utf8",
	LC_NUMERIC = "de_DE.utf8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
reloading user units for root...
/nix/store/fc2fggs4sxplgy9aywbqwrgfs0fpc8vb-set-environment: line 18: warning: setlocale: LC_NUMERIC: cannot change locale (de_DE.utf8)
/nix/store/fc2fggs4sxplgy9aywbqwrgfs0fpc8vb-set-environment: line 21: warning: setlocale: LC_TIME: cannot change locale (de_DE.utf8)
reloading user units for dev0...
/nix/store/fc2fggs4sxplgy9aywbqwrgfs0fpc8vb-set-environment: line 18: warning: setlocale: LC_NUMERIC: cannot change locale (de_DE.utf8)
/nix/store/fc2fggs4sxplgy9aywbqwrgfs0fpc8vb-set-environment: line 21: warning: setlocale: LC_TIME: cannot change locale (de_DE.utf8)
setting up tmpfiles
```

### Notify maintainers
@Ma27 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.49, NixOS, 22.11 (Raccoon), 22.11pre388062.f2537a505d4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by gravndal**
###### Description of changes

Should hopefully fix https://github.com/NixOS/nixpkgs/issues/179486#issuecomment-1174977448

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gravndal** [comment]
Probably not a perfect solution as is, due to locales like `eo` that do not have `.UTF-8` in their file names (unless I'm mistaken).

Using `replaceStrings` could be a alternative solution:
```
(builtins.replaceStrings [ "utf8" "utf-8" "UTF8" ] [ "UTF-8" "UTF-8" "UTF-8" ] l) + "/UTF-8")
```

**Review by SuperSandro2000 — APPROVED** [review]
@Leixb @vlinkz @kofoyo can you give this a test and leave some feedback?

I would say this should fix the problem but I currently don't have time to test this on a machine.

**Comment by Leixb** [comment]
Just tested some variations of defaultLocale extraLocaleSettings and it works on my machine

**Comment by vcunat** [comment]
Perhaps do the normalization before enforcing uniqueness?

**Comment by vlinkz** [comment]
I like the idea of normalizing it here, and I think this PR would help a lot of people, however for some non standard or not utf layouts even with this there would still be errors when updating old configurations

**Comment by vlinkz** [comment]
> Test the installer #180935

I have a fix for the installer that I'll pr soon. My main concern now is all the people that installed 22.05 as of now would have their configurations break if they update to unstable or eventually 22.11

**Comment by SuperSandro2000** [comment]
> My main concern now is all the people that installed 22.05 as of now would have their configurations break if they update to unstable or eventually 22.11

We already have a changelog entry for that.

**Comment by gravndal** [comment]
Though this reminds me, the entry in the changelog should probably mention that only utf8 locales will be generated by default. Y/N?

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
