### PR TITLE
looking-glass-client: B4 -> B5.0.1

### PR DESCRIPTION
**Pull request by babbaj**
###### Motivation for this change

https://www.patreon.com/posts/looking-glass-5-60336916
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Madouura** [comment]
Tested myself and with ``nixpkgs-review``.
LGTM

**Review by Madouura — APPROVED** [review]

**Comment by hpfr** [comment]
There's a tag out for B5.0.1 with a segfault fix https://github.com/gnif/LookingGlass/releases/tag/B5.0.1

**Comment by babbaj** [comment]
Thanks for pointing that out, I just updated it

**Comment by symphorien** [comment]
changelog mentions
> removed SDL displayserver

so I don't think this can be backported.

**Comment by Madouura** [comment]
Ahh that's a shame.

**Comment by babbaj** [comment]
How is that a problem?

**Comment by Madouura** [comment]
Not being able to backport it because of the SDL change.
It's nothing serious lol.

**Comment by babbaj** [comment]
But how does the SDL change make this unable to be backported? B4 already didn't use SDL and was only still a buildInput because it provided an x11 or opengl dependency.
https://github.com/gnif/LookingGlass/blob/B4/client/CMakeLists.txt#L35

**Comment by babbaj** [comment]
I just tested the windows host from B4 and B5 isn't compatible with it anyways.

**Comment by Madouura** [comment]
I'm not entirely sure.
@symphorien could you elaborate?

**Comment by symphorien** [comment]
It looks like the new version removes a feature, so it's not full backward compatible. If someone uses this feature in 21.11, it should continue working for the whole lifetime of 21.11.

**Comment by symphorien** [comment]
Also, let me remind you that it's easy to use the new version of looking glass while remaining on 21.11: https://nixos.wiki/wiki/FAQ#How_can_I_install_a_package_from_unstable_while_remaining_on_the_stable_channel.3F

**Pull request merged**
