### PR TITLE
Add node 8

### PR DESCRIPTION
**Pull request by wmertens**
Backport Node 8 from master

### CODE REVIEW

**Comment by copumpkin** [comment]
I don't get what's going on in this PR 😕 looks like a ton of unrelated commits. Needs a rebase perhaps?

**Comment by LnL7** [comment]
I think this is supposed to go to release-17.03

**Comment by wmertens** [comment]
Yes, I closed it and made and merged #28154 instead :)

**Comment by LnL7** [comment]
FYI. you can change the target branch in github.

**Comment by wmertens** [comment]
Wow, TIL. Well-hidden :( https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Pull request closed without merging**
