### PR TITLE
UTM: fix meta.mainProgram field

### PR DESCRIPTION
**Pull request by hraban**
###### Description of changes
Fixes `nix run nixpkgs#utm`

To test:

```
$ nix run github:hraban/nixpkgs/utm-mainprogram#utm
```

Once merged, that will be `nix run nixpkgs#utm`

As far as I know `nix run` is the only actual use for `meta.mainProgram`, but if there's anything else that I overlooked please let me know.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rrbutani** [comment]
oh hmm..

I believe `lib.getExe` and friends also use `mainProgram`; I'd rather have `bin/UTM` exist than have an empty `bin` but creating a symlink does not seem to work (UTM seems to look for files in the wrong places).

Perhaps we can make a wrapper, like `SwiftBar` does?
https://github.com/NixOS/nixpkgs/blob/2448665c1674b625d2c5be762da9f61d3f648943/pkgs/os-specific/darwin/swiftbar/default.nix#L30-L31

**Review by rrbutani — CHANGES_REQUESTED** [review]
Perhaps something like this (GitHub won't let me leave suggestions on the appropriate lines, sorry):

```diff
diff --git a/pkgs/os-specific/darwin/utm/default.nix b/pkgs/os-specific/darwin/utm/default.nix
index 2e21945288e..c88005f09f2 100644
--- a/pkgs/os-specific/darwin/utm/default.nix
+++ b/pkgs/os-specific/darwin/utm/default.nix
@@ -1,5 +1,6 @@
 { lib
 , undmg
+, makeWrapper
 , fetchurl
 , stdenvNoCC
 }:
@@ -13,12 +14,23 @@ stdenvNoCC.mkDerivation rec {
     hash = "sha256-YOmTf50UUvvh4noWnmV6WsoWSua0tpWTgLTg+Cdr3bQ=";
   };
 
-  nativeBuildInputs = [ undmg ];
+  nativeBuildInputs = [ undmg makeWrapper ];
 
   sourceRoot = ".";
   installPhase = ''
+    runHook preInstall
+
     mkdir -p $out/Applications
     cp -r *.app $out/Applications
+
+    mkdir -p $out/bin
+    for bin in $out/Applications/UTM.app/Contents/MacOS/*; do
+      # Symlinking `UTM` doesn't work; seems to look for files in the wrong
+      # place
+      makeWrapper $bin "$out/bin/$(basename $bin)"
+    done
+
+    runHook postInstall
   '';
 
   meta = with lib; {

```

(The wildcard on `MacOS/*` is so that `utmctl` gets picked up; I think it'd be nice to have a passthru test that makes sure that this runs just so we have _some_ basic testing for this package — I can take care of that in a follow up PR though)

**Comment by hraban** [comment]
You sound like you know more about it than I do so if your fix handles `nix run nixpkgs#utm`, and _also_ is more idiomatic and fixes more stuff, then I'm a happy camper :) thank you for your time.

**Review by rrbutani — APPROVED** [review]

**Comment by ulrikstrid** [comment]
Result of `nixpkgs-review pr 224435` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Pull request merged**
