### PR TITLE
GNOME Flashback: unbreak & gnome.gnome-bluetooth_1_0: init at 3.34.5

### PR DESCRIPTION
**Pull request by bobby285271**
###### Description of changes

The build is failing on master

https://gitlab.gnome.org/GNOME/gnome-panel/-/merge_requests/49
https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.gnome.gnome-panel.x86_64-linux

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg build gnome.gnome-panel

**Comment by bobby285271** [comment]
The next build failure for `services.xserver.desktopManager.gnome.flashback.enableMetacity`:

```
error: builder for '/nix/store/52ycbm2zmy5yfd6iay473cir1p8nd9a2-gnome-flashback-3.44.0.drv' failed with exit code 1;
       last 10 log lines:
       > ) were not met:
       >
       > No package 'gnome-bluetooth-1.0' found
       >
       > Consider adjusting the PKG_CONFIG_PATH environment variable if you
       > installed software in a non-standard prefix.
       >
       > Alternatively, you may set the environment variables SYSTEM_INDICATORS_CFLAGS
       > and SYSTEM_INDICATORS_LIBS to avoid the need to call pkg-config.
       > See the pkg-config man page for more details.
       For full logs, run 'nix log /nix/store/52ycbm2zmy5yfd6iay473cir1p8nd9a2-gnome-flashback-3.44.0.drv'.
```

**Comment by jtojnar** [comment]
That will probably be necessary, looking at the source code, it also depends on the removed code quite  a bit.

**Comment by bobby285271** [comment]
截图 2022-03-31 22-59-30



VM starts for me.

**Comment by jtojnar** [comment]
I wonder if we should just return it to top-level as `gnome-bluetooth_1_0`?

**Review by jtojnar — APPROVED** [review]

**Pull request merged**
