### PR TITLE
pythonPackages.rpy2: 3.2.6 -> 3.3.6, fix test etc.

### LINKED ISSUE #81345: pythonPackages.rpy2: Tests fail on release-20.03
**Describe the bug**

4 tests are failing

https://hydra.nixos.org/build/113445432/nixlog/1

Maintainer information:
@joelmo

### LINKED ISSUE #100259: python: rpy2 - warnings.warn('pandas >= 1.0 is not supported.') - ERROR rpy2/tests/ipython/test_ggplot.py - rpy2.rinterface_lib.embedded.RRunti...
**Describe the bug**

```
============================= test session starts ==============================
platform linux -- Python 3.7.9, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /build/rpy2-3.2.6
collected 692 items / 1 error / 691 selected                                   

==================================== ERRORS ====================================
______________ ERROR collecting rpy2/tests/ipython/test_ggplot.py ______________
rpy2/tests/ipython/test_ggplot.py:3: in <module>
    import rpy2.robjects.lib.ggplot2
rpy2/robjects/lib/ggplot2.py:57: in <module>
    lazyeval = importr('lazyeval', on_conflict='warn')
rpy2/robjects/packages.py:477: in importr
    env = _get_namespace(rname)
rpy2/rinterface_lib/conversion.py:40: in _
    cdata = function(*args, **kwargs)
rpy2/rinterface.py:789: in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
E   rpy2.rinterface_lib.embedded.RRuntimeError: Error in loadNamespace(name) : there is no package called ‘lazyeval’
E   Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
------------------------------- Captured stderr --------------------------------
R[write to console]: Error in loadNamespace(name) : there is no package called ‘lazyeval’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart

=============================== warnings summary ===============================
rpy2/robjects/pandas2ri.py:14
  /build/rpy2-3.2.6/rpy2/robjects/pandas2ri.py:14: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
    from pandas.core.index import Index as PandasIndex

rpy2/robjects/pandas2ri.py:34
  /build/rpy2-3.2.6/rpy2/robjects/pandas2ri.py:34: UserWarning: pandas >= 1.0 is not supported.
    warnings.warn('pandas >= 1.0 is not supported.')

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=========================== short test summary info ============================
ERROR rpy2/tests/ipython/test_ggplot.py - rpy2.rinterface_lib.embedded.RRunti...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 2 warnings, 1 error in 5.99s =========================
builder for '/nix/store/sp2533fydvzb3hdz414rkv3j3wvc39ri-python3.7-rpy2-3.2.6.drv' failed with exit code 2
cannot build derivation '/nix/store/p4kjkz23jj4p70wk5cmwq1576y26xkpq-python3-3.7.9-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/p4kjkz23jj4p70wk5cmwq1576y26xkpq-python3-3.7.9-env.drv' failed

```

**To Reproduce**
```
with import <nixpkgs> {};
let
  envPy = python37.withPackages ( ps: with ps; [
    ipython 
    jupyterlab
    rpy2
  ]
  )
  ;
in mkShell {
  buildInputs = [
    (envPy)
    black
  ];
}
```

**Expected behavior**

Install rpy2 with 
which R shows to path 
and import rpy2 gets imported

**Notify maintainers**

@joelmo

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.13, NixOS, 20.09beta992.7badbf18c45 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09beta992.7badbf18c45"`
 - channels(user): `"nixos-20.09beta992.7badbf18c45"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

### PR DESCRIPTION
**Pull request by omasanori**
###### Motivation for this change

This change updates `rpy2` to the latest version and rebases a local patch to that version.

Fixes https://github.com/NixOS/nixpkgs/issues/81345.
Fixes https://github.com/NixOS/nixpkgs/issues/100259.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vale981** [comment]
Could this be reviewed please :)

**Comment by yurrriq** [comment]
This builds for me on NixOS 20.09, and appears to work as expected, based on https://rpy2.github.io/doc/v3.3.x/html/introduction.html#graphics-and-plots

image

**Comment by omasanori** [comment]
@yurrriq Thank you for testing!

ping? @joelmo

**Comment by SuperSandro2000** [comment]
Fails to build for me on linux-x86_64:

```
unpacking sources
unpacking source archive /nix/store/kckxwy4ngbarm8dnls31h6khbhyj1yc0-lazyeval_0.2.2.tar.gz
source root is lazyeval
setting SOURCE_DATE_EPOCH to timestamp 1552672207 of file lazyeval/MD5
patching sources
configuring
building
running tests
installing
Error: package or namespace load failed for 'utils':
 .onLoad failed in loadNamespace() for 'utils', details:
  call: system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE)
  error: cannot popen '/nix/store/nsqal2vl76faah1hs5i8h8glzhlidbp7-which-2.21/bin/which 'uname' 2>/dev/null', probable reason 'Cannot allocate memory'
Error: package or namespace load failed for 'stats':
 .onLoad failed in loadNamespace() for 'utils', details:
  call: system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE)
  error: cannot popen '/nix/store/nsqal2vl76faah1hs5i8h8glzhlidbp7-which-2.21/bin/which 'uname' 2>/dev/null', probable reason 'Cannot allocate memory'
During startup - Warning messages:
1: package 'utils' in options("defaultPackages") was not found
2: package 'stats' in options("defaultPackages") was not found
* installing *source* package 'lazyeval' ...
** package 'lazyeval' successfully unpacked and MD5 sums checked
** using staged installation
Error : .onLoad failed in loadNamespace() for 'utils', details:
  call: system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE)
  error: cannot popen '/nix/store/nsqal2vl76faah1hs5i8h8glzhlidbp7-which-2.21/bin/which 'uname' 2>/dev/null', probable reason 'Cannot allocate memory'
ERROR: installing package DESCRIPTION failed for package 'lazyeval'
* removing '/nix/store/d18q27vnxzxjki13wynzpf9a249ccpyb-r-lazyeval-0.2.2/library/lazyeval'
Warning in q("no", status = status, runLast = FALSE) :
  system call failed: No such file or directory
builder for '/nix/store/p5r2j6hngwj3bpkjc91x5dsn0cxd7vgc-r-lazyeval-0.2.2.drv' failed with exit code 1
cannot build derivation '/nix/store/lf1q5mhi298g0c9khi72fkfsalm7vmrw-python3.7-rpy2-3.3.6.drv': 1 dependencies couldn't be built
error: build of '/nix/store/lf1q5mhi298g0c9khi72fkfsalm7vmrw-python3.7-rpy2-3.3.6.drv' failed
```

**Comment by omasanori** [comment]
Thank you for testing, @SuperSandro2000!
It seems that `rPackages.lazyeval` failed for some reasons. Would you make a new issue for the package, after `nix-build`ing it?

**Review by jonringer — APPROVED** [review]
overall LGTM

```
https://github.com/NixOS/nixpkgs/pull/101327
2 packages built:
python37Packages.rpy2 python38Packages.rpy2
```

**Pull request merged**
