### PR TITLE
python3Packages.flask-appbuilder: 2.3.0 -> 3.1.1

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @costrouc @drewrisinger @SCOTT-HAMILTON I did not test this.
cc @bhipple @costrouc @ingenieroariel Apache-airflow depends on this and should also be updated.

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109986` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>3 packages failed to build and are new build failures:</summary>
  <ul>
<li>apache-airflow: log was empty</li>
<li>(python37Packages.apache-airflow): log was empty</li>
<li>python37Packages.flask-appbuilder: log was empty</li>
  </ul>
</details>
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>python38Packages.flask-appbuilder</li>
<li>python39Packages.flask-appbuilder</li>
</ul>
</details>

```
builder for '/nix/store/3han1yi5k9xlnpggxmikdfksn6bjncdw-python3.7-virtualenv-20.3.1.drv' failed with exit code 1; last 10 log lines:                                                         SKIPPED [1] tests/unit/activation/conftest.py:249: PowerShell(                                                                                                                              version=FileNotFoundError(2, "No such file or directory: 'pwsh'"),                                                                                                                          creator=CPython3Posix(dest=/build/pytest-of-nixbld/pytest-0/activation-tester-env3/e-$ èрт🚒♞中片-j, clear=False, no_vcs_ignore=False, global=False),                                       interpreter=PythonInfo(spec=CPython3.7.9.final.0-64, exe=/nix/store/q5hdqw6bcp3mfzg8l9m2qhra3y892xwm-python3-3.7.9/bin/python3.7, platform=linux, version='3.7.9 (default, Aug 15 2020, 06:36:35) \n[GCC 10.2.0]', encoding_fs_io=utf-8-UTF-8)) is not available due [Errno 2] No such file or directory: 'pwsh': 'pwsh'                                                                SKIPPED [1] tests/integration/test_run_int.py: need --int option to run                                                                                                                     SKIPPED [1] tests/integration/test_zipapp.py: need --int option to run                                                                                                                      SKIPPED [2] tests/integration/test_zipapp.py:95: need --int option to run                                                                                                                   FAILED tests/unit/activation/test_xonsh.py::test_xonsh[with_prompt] - IndexEr...                                                                                                            FAILED tests/unit/activation/test_xonsh.py::test_xonsh[no_prompt] - IndexErro...                                                                                                            ===== 2 failed, 209 passed, 15 skipped, 2 deselected, 1 warning in 21.14s ======                                                                                                          cannot build derivation '/nix/store/8ajgpdxplbdaj3qblshriiblg7nz23y5-python3.7-poetry-core-1.0.0.drv': 1 dependencies couldn't be built                                                     cannot build derivation '/nix/store/ldcc0ic2fkv2i5j8bp4klda5cxnannwy-python3.7-tox-3.20.1.drv': 1 dependencies couldn't be built                                                            cannot build derivation '/nix/store/pwx1idq9nkwdbh22iidi36xwdz27crj0-python3.7-isort-5.6.4.drv': 1 dependencies couldn't be built                                                           cannot build derivation '/nix/store/za52wfn3b108hjv00rpaqyzrgyczydbj-python3.7-openapi-spec-validator-0.2.9.drv': 1 dependencies couldn't be built                                          cannot build derivation '/nix/store/72g8xqs9r8jfsdbm1sg19l3pbgqs58q3-python3.7-pendulum-2.1.2.drv': 1 dependencies couldn't be built                                                        cannot build derivation '/nix/store/hd018pxqyw9ys979hlad5c31p0kfyp7l-python3.7-apispec-4.0.0.drv': 1 dependencies couldn't be built                                                         cannot build derivation '/nix/store/l8jczr2wvd2awhr71vax36zfbcf8mlzx-python3.7-pylint-2.6.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/k1f0rfj9aixlcnhq0zd1dw16aljmp68q-python3.7-flask-appbuilder-3.1.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/k1mmksx0byi3cr9idaa4gv5fi7zs13bm-python3.7-trio-0.17.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ff54i91d8gciimfchcxwqghymmmfhzf7-python3.7-jeepney-0.6.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/0v7najg46c3iaf09zb17rk80gb01aj3q-python3.7-secretstorage-3.3.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/zf6qybx233svx8nhs9szyc2r653p9n52-python3.7-keyring-21.5.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/cpw6sk1wz4npfmb464gv3m4qwwy8mwl1-python3.7-twine-3.2.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ljd7ry1njjiv7hm9hrj11368sxiyljkk-python3.7-python-daemon-2.2.4.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/qicvls2wp3hb98rvwqhsp3a9hriw0wk4-python3.7-apache-airflow-1.10.5.drv': 3 dependencies couldn't be built
cannot build derivation '/nix/store/46jcky42k196f4a1biac48i5nhqf12x6-env.drv': 2 dependencies couldn't be built
```

**Comment by drewrisinger** [comment]
@dotlambda I can't get a clean build b/c of failures with ``python37Packages.virtualenv``

```
builder for '/nix/store/3han1yi5k9xlnpggxmikdfksn6bjncdw-python3.7-virtualenv-20.3.1.drv' failed with exit code 1; last 10 log lines:
  FAILED tests/unit/activation/test_xonsh.py::test_xonsh[with_prompt] - IndexEr...
  FAILED tests/unit/activation/test_xonsh.py::test_xonsh[no_prompt] - IndexErro...
  ===== 2 failed, 209 passed, 15 skipped, 2 deselected, 1 warning in 38.45s ======


Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/109986

2 packages failed to build:
apache-airflow python37Packages.flask-appbuilder

2 packages built:
python38Packages.flask-appbuilder python39Packages.flask-appbuilder
```

**Comment by dotlambda** [comment]
@drewrisinger Just do `git fetch upstream pull/109986/head && git checkout FETCH_HEAD`.

**Comment by SuperSandro2000** [comment]
> @drewrisinger Just do `git fetch upstream pull/109986/head && git checkout FETCH_HEAD`.

We always test with nixpkgs-review against the current master to not miss any regressions since you created the PR. If virtualenv is broken than this needs a fix before that.

**Comment by dotlambda** [comment]
> We always test with nixpkgs-review against the current master to not miss any regressions since you created the PR. If virtualenv is broken on master than this needs a fix before we can build and fully review your PR.

I know. But it's good enough to check whether flask-appbuilder is actually working after the update.
Btw, virtualenv was fixed by reverting https://github.com/NixOS/nixpkgs/pull/109930.

**Comment by SuperSandro2000** [comment]
> But it's good enough to check whether flask-appbuilder is actually working after the update.

No, this is not enough for a good review. If it instantly breaks on master we did not test it properly.

**Comment by dotlambda** [comment]
> No, this is not enough for a good review. If it instantly breaks on master we did not test it properly.

That's not what I'm saying. You can check whether the package works after upgrading, but then you also have to check whether everything still builds after merging.

**Comment by dotlambda** [comment]
@drewrisinger Can you try again?

**Pull request merged**
