### PR TITLE
python3Packages.sopel: add missing packaging dependency and mainProgram

### PR DESCRIPTION
**Pull request by Duckle29**
## Description of changes

The package was missing a dependency.
`<Rutherther>` on IRC helped me test with an override, and I got it working through that.

In addition I'm working on a service for this that I plan to upstream, and was suggested to use lib.getExe, which warned about a missing meta.mainProgram field, so I added this too. 

I have not been able to test this, and if that is a strong requirement, I will definitely try and get a VM running on my desktop to run the tests in.

## Things done

Got the package working and running with
```
(python312Packages.sopel.overridePythonAttrs(o: { dependencies = o.dependencies ++ [ pkgs.python312Packages.packaging ];
```
in my systemPackages

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Frontear** [comment]
Result of `nixpkgs-review pr 342045` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.sopel</li>
    <li>python311Packages.sopel.dist</li>
    <li>python312Packages.sopel</li>
    <li>python312Packages.sopel.dist</li>
  </ul>
</details>

**Review by Frontear — APPROVED** [review]

**Comment by Frontear** [comment]
Additionally also tested `sopel configure` -> `sopel`, and in a python repl with `import sopel`. Everything looks to be working well. Welcome to the community and LGTM on your first PR!

**Comment by Eveeifyeve** [comment]
Result of `nixpkgs-review pr 342045` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.sopel</li>
    <li>python311Packages.sopel.dist</li>
    <li>python312Packages.sopel</li>
    <li>python312Packages.sopel.dist</li>
  </ul>
</details>

**Review by FliegendeWurst — COMMENTED** [review]
LGTM. Please make sure your commit message follows CONTRIBUTING.md

**Review by Eveeifyeve — CHANGES_REQUESTED** [review]
LGTM, but please revoke your messages and change them to follow the guidelines of CONTRIBUTING.md.

**Comment by Duckle29** [comment]
Thanks for the reviews guys! :)

I believe I have squashed and re-worded the commit to be compliant now? 🙂

**Review by Eveeifyeve — APPROVED** [review]
LGTM, as said before.

**Pull request merged**
