### PR TITLE
headless: Don't use deprecated vesa.

### PR DESCRIPTION
**Pull request by Et7f3**
###### Description of changes

This option is deprecated as per https://github.com/NixOS/nixpkgs/pull/76481. So I applied recommendation.

###### Things done
I didn't test since the value was already to false. The recommendation was merged so it seem safe to apply.

### CODE REVIEW

**Review by rapenne-s — APPROVED** [review]
looks good to me

**Review by Janik-Haag — APPROVED** [review]

**Comment by Janik-Haag** [comment]
@Et7f3 thank you for your contribution, and it looks like this is still relevant are you still interested in getting this merged? I just ran the boot test (seemed like the related one for this module), which failed on x86_64-linux for some reason :/

**Comment by Et7f3** [comment]
> @ofborg test boot

Can you test it on another commit like master ? I don't see why this error is linked with my change. I can test locally if it still fail

**Comment by Janik-Haag** [comment]
Yeah the test fails on master with the same error. And the one test importing this module runs successfully (`nixos/tests/amazon-init-shell.nix`) 

I will merge this since it looks good to me, is approved by another person as well.

**Pull request merged**
