### PR TITLE
rnote: 0.7.1 -> 0.8.0

### PR DESCRIPTION
**Pull request by yrd**
## Description of changes

Update to Rnote [0.8.0](https://github.com/flxzt/rnote/releases/tag/v0.8.0).

This currently depends on #247766 for [cairo 1.17](https://github.com/NixOS/nixpkgs/pull/247766/files#diff-c1b6675856a14491b8c610758d37ad4372e04a3f25a6049926c738f21121e5b0).

cc @dotlambda 

## Things done

- Built on platform(s)
  - [x] x86_64-linux **(rebased onto the `gnome` branch)**
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by MarcelCoding** [comment]
rnote 0.9.0 is now already available :)

**Comment by dotlambda** [comment]
0.9.0 will need to wait for the gtk4 update from https://github.com/NixOS/nixpkgs/pull/247766 but here's the update to 0.8.2: https://github.com/NixOS/nixpkgs/pull/263494

**Comment by MarcelCoding** [comment]
Nice

**Comment by Tungsten842** [comment]
This has been done in: https://github.com/NixOS/nixpkgs/pull/263494

**Pull request closed without merging**
