### PR TITLE
tailscale: 1.50.1 -> 1.52.0

### PR DESCRIPTION
**Pull request by LeSuisse**
## Description of changes

https://github.com/tailscale/tailscale/releases/tag/v1.52.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by danderson — APPROVED** [review]

**Comment by mfrw** [comment]
Result of `nixpkgs-review pr 264449` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>tailscale</li>
    <li>trayscale</li>
  </ul>
</details>

**Comment by mfrw** [comment]
Result of `nixpkgs-review pr 264449` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>tailscale</li>
    <li>trayscale</li>
  </ul>
</details>

**Review by mfrw — COMMENTED** [review]
`nixpkgs-review` does not agree that this PR builds :(

**Comment by LeSuisse** [comment]
Oh there is a dependency on Tailscale now.

I'm a bit surprise by your `nixpkgs-review` output @mfrw (I'm guessing timeout limit?), Tailscale seems to build just fine on my end.
It seems that the issue comes from `trayscale`, it seems to be blocked on this:
```
building '/nix/store/8k9cf1xyx6kydb4wyn87b5kbrvxqyif5-trayscale-0.10.4.drv'...
unpacking sources
unpacking source archive /nix/store/xzda5rvbdkjh97mmbgw05jhagi8wayzd-source
source root is source
patching sources
updateAutotoolsGnuConfigScriptsPhase
configuring
building
Building subPackage ./cmd/trayscale
```

However I do not think the issue is caused by Tailscale as it only depends on it at runtime with `gappsWrapperArgs`. Also I have the same issue when building it on `master` cc @K900 as the listed package maintainer.

I do not think this is a blocker for the Tailscale upgrade as the issue does not appear to be new/caused by this change.

**Comment by K900** [comment]
trayscale just takes forever to build, because it's a cgo GTK4 app, and it's building one C file at a time.

@ofborg build trayscale

**Comment by K900** [comment]
Seems to build fine on ofborg.

**Pull request merged**
