### PR TITLE
libva: make `libva-full` the default

### PR DESCRIPTION
**Pull request by oxij**
###### Motivation for this change

Side-effect of me making kodi play torrent streams (will PR when this gets merged and staging gets merged into master).

It seems that all uses of `libva` it in nixpkgs except `mesa` and itself actually
either will gain from using `libva-full` instead of `libva-minimal` by default
or simply won't care.

They way it was recursively defined with overrides before was also very
confusing.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
- [X] Tested compilation of most pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by oxij** [comment]
@vcunat @garbas ping! Just look at the `master`, more and more things get `libva = libva-full` every week.

**Comment by garbas** [comment]
i'm +0 on this. i would let @vcunat decide.

**Review by abbradar — APPROVED** [review]
I can merge this with my `libglvnd` changes as related in the staging batch. Note to myself: check for new packages using `libva` before merging.

**Comment by oxij** [comment]
Thanks! Rebased onto newer staging and cleaned up a bit.

**Comment by oxij** [comment]
Rebased onto current staging. The old branch lives in `pkgs/libva-full-by-default-before-rebase`.

**Comment by abbradar** [comment]
Merged into staging, thanks!

**Pull request closed without merging**
