### PR TITLE
[doc] Add example on how to override compile flags for a package

### LINKED ISSUE #22668: Missing documentation: Override compile flags for a package
## Issue description

I cannot find any documentation how to override compile flags for a single package.

For example, I want to build `pkgs.dmenu` with `-O3` and `-march=native`.
One step further, I'd love to have a helper function I could pass packages to, which automatically overrides certain flags, E.G.:

```nix
let
  dmenu = util.optimizeWithFlags [ "-O3", "-march=native" ] pkgs.dmenu;
  mutt = util.optimizeWithFlags [ "-march=native" ] pkgs.mutt;
in
  [ mutt dmenu ]
```

### PR DESCRIPTION
**Pull request by matthiasbeyer**
And again I was able to feel the pain and uglyness of writing XML! *shiver*

Closes #22668

### CODE REVIEW

**Comment by joachifm** [comment]
To me, the complexity of this overshadows the point; this'd be clearer:
```
foo.overrideAttrs (attrs: {
  NIX_CFLAGS_COMPILE = (attrs.NIX_CFLAGS_COMPILE or []) ++ [ "-fgo-fast"];
})
```
I also think it's redundant to say that it compiles foo with the listed flags: it is self-evident.

**Comment by matthiasbeyer** [comment]
@joachifm Thanks for the suggestion. It is complicated because I couldn't find documentation on how to do this, so I had to hack this together myself. I will test your suggestions and update this PR shortly! :+1:

**Comment by matthiasbeyer** [comment]
Don't merge! I guess I missed a blank before the flag

**Comment by matthiasbeyer** [comment]
Okay. I'm ready to fix things up!

**Comment by joachifm** [comment]
What about moving that utility function to `lib/` instead? While much more convenient than the expanded form, it makes the example less crisp, imo. Consider that readers must 1) process more information in total; 2) spend more effort to parse out the relevant parts of the example. I think it'd be better if the cflags example was more in line with the `separateDebug` example above it. 

(As a side note, I think the cflags example is strictly redundant in the context of a function reference, as it fails to teach the reader anything new about `overrideAttrs`, but I suppose we can find a better home for it later).

**Comment by FRidh** [comment]
@matthiasbeyer I think you could be a bit more explicit about what this env var does. It passes the flag directly to the compiler, and therefore it typically won't be shown during configuration as you found out. I think this is worth mentioning.

**Comment by matthiasbeyer** [comment]
@joachifm you mean I should put this function into nixpkgs/lib?

**Comment by joachifm** [comment]
@matthiasbeyer something like that. A function reference is not a good place for utility functions, imo.

**Comment by joachifm** [comment]
I wonder whether https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/configuration/customizing-packages.xml would be a better place for this?

**Comment by matthiasbeyer** [comment]
@joachifm this way? :smile:

**Comment by matthiasbeyer** [comment]
Will this get merged?

**Pull request closed without merging**
