### PR TITLE
telegram-desktop: add missing glib-networking dependency

### LINKED ISSUE #227930: telegram-desktop: broken webkit integration
### Describe the bug
The webkit integration of telegram-desktop is broken, resulting in bots using https://core.telegram.org/bots/webapps to not work properly.

### Steps To Reproduce
1. Open a chat with the demo bot [@DurgerKingBot](https://t.me/durgerkingbot).
2. Click the "Order Food" button
3. Either telegram-desktop crashes, or the webview fails to render the webpage

### Expected behavior
The webkit integration works as shown in https://core.telegram.org/bots/webapps

### Additional information
Reference: https://github.com/NixOS/nixpkgs/pull/227608

### PR DESCRIPTION
**Pull request by NickCao**
## Description of changes
Fixes https://github.com/NixOS/nixpkgs/issues/227930

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Cryolitia — APPROVED** [review]
LGTM, works for me


2 packages built:
_64gram telegram-desktop

Result of `nixpkgs-review pr 315104` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>_64gram</li>
    <li>telegram-desktop</li>
  </ul>
</details>

**Review by superherointj — APPROVED** [review]

**Comment by Hentioe** [comment]
I still had the "TLS support is not available" issue, which seemed to be due to the missing `GIO_MODULE_DIR` environment variable.

When I started from the terminal and set this environment variable manually, the problem was solved. For example:

```bash
GIO_MODULE_DIR=/nix/store/38linv3kvivyvv4qg58ydv3nhjj1z628-glib-networking-2.80.0/lib/gio/modules telegram-desktop
```

Same as here: https://github.com/NixOS/nixpkgs/issues/72579#issuecomment-549046678

**Comment by NickCao** [comment]
> I still had the "TLS support is not available" issue

Is this on unstable or 24.05?

**Comment by Hentioe** [comment]
> > I still had the "TLS support is not available" issue
> 
> Is this on unstable or 24.05?

unstable + kde

**Comment by NickCao** [comment]
`GIO_MODULE_DIR` is not set anywhere treewide, but `glib-networking` is present in the tdesktop wrapper under `GIO_EXTRA_MODULES`. Could you double check this by running:
```bash
strings $(which telegram-desktop) | grep GIO_EXTRA_MODULES
```

**Comment by Hentioe** [comment]
```bash
strings $(which telegram-desktop) | grep GIO_EXTRA_MODULES                                                                  [1:35:50]
GIO_EXTRA_MODULES
    --prefix 'GIO_EXTRA_MODULES' ':' '/nix/store/6xd7halb89mlp2c44i6pb5hpmhi5d135-dconf-0.40.0-lib/lib/gio/modules' \
    --prefix 'GIO_EXTRA_MODULES' ':' '/nix/store/38linv3kvivyvv4qg58ydv3nhjj1z628-glib-networking-2.80.0/lib/gio/modules' \
    --prefix 'GIO_EXTRA_MODULES' ':' '/nix/store/6xd7halb89mlp2c44i6pb5hpmhi5d135-dconf-0.40.0-lib/lib/gio/modules' \
    --prefix 'GIO_EXTRA_MODULES' ':' '/nix/store/38linv3kvivyvv4qg58ydv3nhjj1z628-glib-networking-2.80.0/lib/gio/modules' \
```

I was wrong, I misunderstood the cause of the error.

I figured it out, if Telegram starts automatically at system boot, the "TLS support is not available" error will appear. It will not appear if it is started from the icon or command line.

This should be a new problem, not related to your fix.

The autostart is added from the Telegram settings: Advanced -> Launch Telegram when system starts

**Comment by NickCao** [comment]
> This should be a new problem, not related to your fix.
> 
> The autostart is added from the Telegram settings: Advanced -> Launch Telegram when system starts

I see, the problem is the generated autostart entry points to the unwrapped binary.

**Comment by Hentioe** [comment]
Sorry for wasting time, after repeated testing and confirmation, there should be no problem, including the generated autostart entry.

It seems to be caused by the old autostart entry. I cleaned it up and everything worked fine.😅

**Pull request merged**
