### PR TITLE
Luarocks nix bump

### PR DESCRIPTION
**Pull request by teto**
###### Motivation for this change
According to https://github.com/NixOS/nixpkgs/pull/68158, it seems like update-luarocks-packages will return different urls depending on the mirror hit.
I've thus proceeded to rebase luarocks-nix on top of the new luarocks-release 3.2.1 https://github.com/NixOS/nixpkgs/pull/68201 and added support for the generation of
mirror://luarocks/<PACKAGE_NAME> when possible.
The updater will also now look into a specific LUAROCKS_CONFIG to prevent outside impurities.
It allows to set some settings to let it perform better.

I've successfully regenerated a pkgs/development/lua-modules/generated-packages.nix with this.
Seems like package installation works with the new mirror://luarocks uris. (except for penlight).
I haven't submitted the pkgs/development/lua-modules/generated-packages.nix changes, I prefer to let it update itself little by little :)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by teto** [comment]
CC @Shados . while running the update script I had a few issues because parallel tends to hide the error. I just see: 
```
parallel: This job failed:
convert_pkg cyrussasl '' '' '' '' vcunat
*** error 1: tee -a "$TMP_FILE".
```
without being able to retrieve the error message. I don't know parallel but I wondered if the situation could be improved ?

**Comment by Shados** [comment]
@teto the way parallel is set up, it should still output the all the stdout/stderr for the called function, but it will do so in the order that the calls are made, so you may need to scrollback a bit to find the output for the failing call.

**Comment by teto** [comment]
cc @doronbehar since you are a lua user :)

**Comment by teto** [comment]
due to moving luarocks-nix to nix-community, luarocks-nix is broken in nixpkgs so I will merge this since in my tests it work. If there is an issue, I will fix it.

**Pull request merged**
