### PR TITLE
nyx: init at 2.0.4

### PR DESCRIPTION
**Pull request by offlinehacker**

### CODE REVIEW

**Review by dotlambda — CHANGES_REQUESTED** [review]
Nyx is an appllication and should not live under `pythonPackages`. You should also use `buildPythonApplication`.

**Comment by offlinehacker** [comment]
@dotlambda should be fixed now, thanks! It was some time ago, i last packaged python app in nixos, i can see a few things has changed on better since then, :)

**Comment by dotlambda** [comment]
> Ran 0 tests in 0.000s

You can try to add something like
```
checkPhase = ''
  ./run_tests.py
'';
```

If you don't get the tests to work, please set `doCheck = false` and add a comment why.

**Comment by offlinehacker** [comment]
I did not manage to get tests working, also i did not spend too much time to try, but i wrote a comment about error that test suite reports and it seems to be super error in code. I explicitly disabled tests with `noCheck = true;`

**Comment by dotlambda** [comment]
@GrahamcOfBorg build nyx

**Pull request merged**
