### PR TITLE
bicep: 0.26.54 -> 0.27.1

### PR DESCRIPTION
**Pull request by superherointj**
bicep: 0.26.54 -> 0.27.1

Release: https://github.com/Azure/bicep/releases/tag/v0.27.1

Update script is broken:
* https://r.ryantm.com/log/bicep/2024-05-18.log

### CODE REVIEW

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 314082` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>bicep</li>
  </ul>
</details>

**Comment by khaneliman** [comment]
Update script worked locally... 

```bash
nix-shell maintainers/scripts/update.nix --argstr package bicep
this derivation will be built:
  /nix/store/2g75kpkmrywf0vyzv6pvyzy42r1mcb1f-packages.json.drv
building '/nix/store/2g75kpkmrywf0vyzv6pvyzy42r1mcb1f-packages.json.drv'...

Going to be running update for following packages:
 - bicep-0.26.54

Press Enter key to continue...

Running update for:
 - bicep-0.26.54: UPDATING ...
 - bicep-0.26.54: DONE.

Packages updated!
```

**Comment by khaneliman** [comment]
> Update script is broken:
> 
>     * https://r.ryantm.com/log/bicep/2024-05-18.log

Yeah... looks like the fetch-deps didn't actually update the file. Creating a PR for it.

**Comment by khaneliman** [comment]
Result of `nixpkgs-review pr 314082` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>bicep</li>
  </ul>
</details>

**Review by khaneliman — APPROVED** [review]

**Pull request merged**
