### PR TITLE
Dlang update

### PR DESCRIPTION
**Pull request by ThomasMader**
###### Motivation for this change

Bump versions for various dlang related packages.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ThomasMader** [comment]
Let's try to get it to build on Darwin too.

@GrahamcOfBorg build ldc dmd dtools dub

**Comment by ThomasMader** [comment]
Don't know why it's not building on Darwin but I tested it on my machine without any problems. So this is ready to be merged.

**Comment by Mic92** [comment]
@GrahamcOfBorg build ldc dmd dtools dub

**Comment by Mic92** [comment]
darwin is limited to trusted user since we do not have a sandbox on macOS.

**Comment by ThomasMader** [comment]
For the Darwin build we once again have the problem with the shared tmp dirs. See https://github.com/NixOS/nixpkgs/issues/41099#issuecomment-392592297 for reference.

Why the Linux build was done again is funny, the previous build package must have been erased from the binary cache or something because my second build run just used a cached build.

Nevertheless this problem already occured and I opened https://github.com/NixOS/nix/issues/2155 but closed it because it seemed to be fixed in nix 2.0.2.
18.03 comes with 2.0.4 now so it's either a regression or the ofBorg build machine has an older nix version or it is something totally different.

Has someone access to that very same build machine to check the nix version?

**Comment by Mic92** [comment]
The build before was executed on a different machine. I would ignore this for the moment.

**Pull request merged**
