### PR TITLE
mkCoqDerivation: do not set DESTDIR

### LINKED ISSUE #178109: CoqHammer integration with external ATPs broken
### Describe the bug

#173112 broke CoqHammer communication with external theorem provers, at least on `aarch64-darwin`. This is a mildly complicated issue to reproduce because of some intermittent but unrelated build failures, anyway,

### Steps To Reproduce
Save the following file as `coqhammer.v` in the root of nixpkgs
```coq
Require Import List.
From Hammer Require Import Hammer.
Import ListNotations.

Goal (forall A (l : list A), rev (rev l) = l).
  hammer.
Qed.
```
Run the following command:
```console
$ nix-shell --pure -E 'with import ./. {}; mkShell { buildInputs = [ coq_8_13 coqPackages_8_13.coqhammer cvc4 ]; }' --run "coqtop -l coqhammer.v"
```

On 5041c1bd4b505e6b55dd93e28afa2f2172eaa90c up to master it gives:

```console
$ nix-shell --pure -E 'with import ./. {}; mkShell { buildInputs = [ coq_8_13 coqPackages_8_13.coqhammer cvc4 ]; }' --run "coqtop -l coqhammer.v"
Welcome to Coq 8.13.2 (January 1980)
Detecting provers...
sh: eprover: command not found
Eprover not found
sh: vampire: command not found
Vampire not found
sh: z3_tptp: command not found
Z3 not found
CVC4 found
Extracting features...
Running provers (8 threads)...
Error: Hammer error: Dependency prediction failed.
Prediction command: predict /tmp/predict74bd43fea /tmp/predict74bd43dep /tmp/predict74bd43seq -n 64 -p knn 2>/dev/null < /tmp/predict74bd43conj > /tmp/coqhammer_outknn647679e3
Error: Hammer error: Dependency prediction failed.
Prediction command: predict /tmp/predict74bd43fea /tmp/predict74bd43dep /tmp/predict74bd43seq -n 256 -p knn 2>/dev/null < /tmp/predict74bd43conj > /tmp/coqhammer_outknn2567679e3
Error: Hammer error: Dependency prediction failed.
Prediction command: predict /tmp/predict74bd43fea /tmp/predict74bd43dep /tmp/predict74bd43seq -n 128 -p nbayes 2>/dev/null < /tmp/predict74bd43conj > /tmp/coqhammer_outnbayes1287679e3
Error: Hammer error: Dependency prediction failed.
Prediction command: predict /tmp/predict74bd43fea /tmp/predict74bd43dep /tmp/predict74bd43seq -n 32 -p nbayes 2>/dev/null < /tmp/predict74bd43conj > /tmp/coqhammer_outnbayes327679e3
Error: Hammer error: Dependency prediction failed.
Prediction command: predict /tmp/predict74bd43fea /tmp/predict74bd43dep /tmp/predict74bd43seq -n 256 -p nbayes 2>/dev/null < /tmp/predict74bd43conj > /tmp/coqhammer_outnbayes2567679e3
Error: Hammer error: Dependency prediction failed.
Prediction command: predict /tmp/predict74bd43fea /tmp/predict74bd43dep /tmp/predict74bd43seq -n 1024 -p nbayes 2>/dev/null < /tmp/predict74bd43conj > /tmp/coqhammer_outnbayes10247679e3
Error: Hammer error: Dependency prediction failed.
Prediction command: predict /tmp/predict74bd43fea /tmp/predict74bd43dep /tmp/predict74bd43seq -n 64 -p nbayes 2>/dev/null < /tmp/predict74bd43conj > /tmp/coqhammer_outnbayes647679e3
File "/Users/siraben/Git/forks/nixpkgs/coqhammer.v", line 6, characters 2-8:
Error:
Hammer failed: ATPs failed to find a proof.
You may try increasing the ATP time limit with 'Set Hammer ATPLimit N' (default: 20s).
```
### Expected behavior
The expected behavior is
```console
$ nix-shell --pure -E 'with import ./. {}; mkShell { buildInputs = [ coq_8_13 coqPackages_8_13.coqhammer cvc4 ]; }' --run "coqtop -l coqhammer.v"
Welcome to Coq 8.13.2 (January 1980)
Detecting provers...
sh: eprover: command not found
Eprover not found
sh: vampire: command not found
Vampire not found
sh: z3_tptp: command not found
Z3 not found
CVC4 found
Extracting features...
Running provers (8 threads)...
CVC4 (knn-64) succeeded
- dependencies: Lists.List.rev_involutive
Reconstructing the proof...
Tactic scongruence succeeded.
Replace the hammer tactic with:
        scongruence use: rev_involutive.
```

Bisection log:

```
# bad: [5041c1bd4b505e6b55dd93e28afa2f2172eaa90c] Merge pull request #178101 from Mic92/ruby-fixup
# good: [6766fb6503ae1ebebc2a9704c162b2aef351f921] Merge pull request #170688 from WolfangAukang/lifeograph-2.0.3
git bisect start '5041c1bd4b505e6b55dd93e28afa2f2172eaa90c' '6766fb6503ae1ebebc2a9704c162b2aef351f921'
# skip: [f0953c2c72d25dca8ce9ff2171d7e0444ba3e21a] Merge staging-next into staging
git bisect skip f0953c2c72d25dca8ce9ff2171d7e0444ba3e21a
# good: [bcbbbea82e5a0618f3a11126fea7210bb9af1031] ocamlPackages.cmdliner_1_0: Update license
git bisect good bcbbbea82e5a0618f3a11126fea7210bb9af1031
# bad: [6c4797f0120f5a0f824a105393446e46eaa7da6d] Merge pull request #147503 from OPNA2608/init/libvgm
git bisect bad 6c4797f0120f5a0f824a105393446e46eaa7da6d
# bad: [1461ead834295d5d49e0d29473ee8dfe8fbc29c9] wxcam: stdenv -> gcc10Stdenv
git bisect bad 1461ead834295d5d49e0d29473ee8dfe8fbc29c9
# bad: [1461ead834295d5d49e0d29473ee8dfe8fbc29c9] wxcam: stdenv -> gcc10Stdenv
git bisect bad 1461ead834295d5d49e0d29473ee8dfe8fbc29c9
# bad: [5ae3a14579efb2c68fc2ff42f90d4c34d06b38f8] Merge pull request #174512 from r-ryantm/auto-update/python3.10-ansible-compat
git bisect bad 5ae3a14579efb2c68fc2ff42f90d4c34d06b38f8
# good: [e021db39115439119aa4fcd6d14773171dda7b64] Merge pull request #174143 from fabaff/manticore-fix
git bisect good e021db39115439119aa4fcd6d14773171dda7b64
# good: [ffdc7226562eda2e058c8f7c969c7f8e59c69298] Merge pull request #171839 from mfeliu/fix/python3Packages.dash-update
git bisect good ffdc7226562eda2e058c8f7c969c7f8e59c69298
# good: [22aa8e5c7a19a9e74af9f223b0e033341629d92d] Merge pull request #174423 from fabaff/bump-angr
git bisect good 22aa8e5c7a19a9e74af9f223b0e033341629d92d
# bad: [27d54ad2e9c43f91c45ea543368a6a4e5af56ded] Merge pull request #174556 from prusnak/clboss
git bisect bad 27d54ad2e9c43f91c45ea543368a6a4e5af56ded
# good: [ea3f23b46756d6a157932f0dfa225fe4551a702e] Merge pull request #174416 from r-ryantm/auto-update/python3.10-mwoauth
git bisect good ea3f23b46756d6a157932f0dfa225fe4551a702e
# good: [d0f6b9d5966975de47510cbfa81e7e64bcaa9430] Merge pull request #174096 from GaetanLepage/pkg/mprocs
git bisect good d0f6b9d5966975de47510cbfa81e7e64bcaa9430
# good: [41a7a6caabeed1bfd596ac7accb88a7d4e1d189a] Merge pull request #174374 from lovesegfault/plex-update
git bisect good 41a7a6caabeed1bfd596ac7accb88a7d4e1d189a
# bad: [f905feccd0acc29ce0010d1f36c78abe0964bb2a] Merge pull request #174563 from SuperSandro2000/go-camo
git bisect bad f905feccd0acc29ce0010d1f36c78abe0964bb2a
# bad: [d113661156581c835df4fe5521ffc64128772f18] coqPackages: etc
git bisect bad d113661156581c835df4fe5521ffc64128772f18
# first bad commit: [d113661156581c835df4fe5521ffc64128772f18] coqPackages: etc
```

### Notify maintainers
@vbgl @CohenCyril @Zimmi48

### PR DESCRIPTION
**Pull request by vbgl**
Fixes #178109

###### Description of changes

There is no reason to mess with `DESTDIR`…

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Can confirm it fixes #178109, thanks!

**Comment by Zimmi48** [comment]
>There is no reason to mess with DESTDIR…

I'm pretty sure that there was a reason. And IIUC this was the conclusion of @CohenCyril's interactions with @gares on the proper way to set up where to install Coq libraries.

This is a question that has been going on for years in nixpkgs with PRs going back and forth, from COQLIB to COQMF_COQLIB to DESTDIR, and back, and I still have no idea what is the proper Coq support for the type of installation method that Nix requires. But clearly, there is a lack of documentation and insufficient communication between all the actors involved.

**Comment by CohenCyril** [comment]
This setting was reached in concordance with @gares indeed.
Has this PR been tested with coqPackages on top of coq master?

**Comment by gares** [comment]
COQMF_COQLIB is, and has always been, private.
We did add, and document in the coq refman, other variables which let on ovrride installation paths in a robust way.

Please check the coq_makefile related section if the coq manual.

**Comment by gares** [comment]
In particular we found out that the use of COQMF_COQLIB is sometimes inconsistente w.r.t. absolute paths and relative ones, which makes things particularly nasty on nix. The new variables COQLIBINSTALL, COQDOCINSTALL and COQPLUGININSTALL should be used instead (the latter from Coq 8.16).

**Pull request merged**
