### PR TITLE
xorg.xf86videoamdgpu: 21.0.0 -> 23.0.0

### PR DESCRIPTION
**Pull request by vcunat**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
Perhaps we should wait for at least one person running their desktop on this?  It's quite inconvenient for me to try currently.

**Comment by MasterMind2k** [comment]
> Perhaps we should wait for at least one person running their desktop on this? It's quite inconvenient for me to try currently.

Is there a quick guide how to do this? I am willing to test it out.

**Comment by vcunat** [comment]
Well, e.g. switch to this commit?

Usable git reference is e.g. `git fetch origin refs/pull/218433/head`
If you're using non-flake: `nixos-rebuild -I nixpkgs=path/to/nixpkgs/repo switch`

**Comment by MasterMind2k** [comment]
It works, cursor is visible.

Notable difference to modesetting driver. With amdgpu xorg driver some apps are scaled as defined in nixos configuration. With xorg driver modesetting some apps do not scale.

Configuration snippet:
```
  services.xserver = {
    enable = true;
    videoDrivers = ["amdgpu"];

    # Enable the KDE Plasma Desktop Environment.
    displayManager.sddm.enable = true;
    desktopManager.plasma5.enable = true;

    # Configure keymap in X11
    layout = "si";
    xkbVariant = "";

    # hidpi
    dpi = 120;
  };
```

The apps running in following FHS don't scale with modesetting driver while under amdpu xorg driver they do:
```
{ pkgs ? import <nixpkgs> {}, command }:

(pkgs.buildFHSUserEnv {
  name = "Qt6-env";
  targetPkgs = pkgs: (with pkgs;
    [
      cacert
      alsa-lib
      libdrm
      libpulseaudio
      udev
      which
      libglvnd.dev
      libxkbcommon.dev
      nss
      libevdev
      nspr
      expat
      fontconfig
      bzip2
      dbus
      zlib
      glib
      pcre2.dev
      libpng.dev
      libcap.dev
      libgcrypt.dev
      zstd.dev
      lz4.dev
      libgpg-error.dev
      brotli.dev
      keyutils.dev
      lzma.dev
      freetype
      libkrb5
      gdb
      pkg-config
      gcc
      bintools
      git
      ccache
      clang-tools_14
      # Dev deps
      libyaml
      ffmpeg
    ]) ++ (with pkgs.xorg;
    [
      setxkbmap
      libX11.dev
      libXau.dev
      libXdmcp.dev
      libXcursor
      libXrandr
      libXext
      libxcb.dev
      xcbutilimage
      xcbutilkeysyms
      xcbutilrenderutil
      xcbutilwm
      libXcomposite
      libXdamage
      libXtst
      libXi
      libXfixes
      libXrender
      libxshmfence
      libxkbfile
      xf86inputevdev
    ]);
  profile = ''
    unset QT_PLUGIN_PATH
    unset QTWEBKIT_PLUGIN_PATH
    unset QML2_IMPORT_PATH
    export QML_DISABLE_DISK_CACHE=1
    export PATH="$HOME/Qt/Tools/QtCreator/bin:$HOME/Qt:$PATH"
  '';
  runScript = command;
}).env
```

This is unrelated with pull request but with modesetting driver.

**Comment by MasterMind2k** [comment]
Just found out. Also apps defined in KDE's autostart configuration are properly scaled with amdgpu XOrg driver.

**Comment by jansol** [comment]
Release announcement is here: https://lists.x.org/archives/dri-devel/2023-February/392659.html

Indeed only a couple of meaningful patches, the rest is just CI/docs fixes

**Comment by vcunat** [comment]
Oh, I thought it would go to xorg-announce@lists.x.org like the rest.  Well anyway, it's just auto-generated commit list.

**Comment by vcunat** [comment]
Hmm, I tend to set DPI in the DE's tools (`xfce4-appearance-settings` in my case) and it seems to apply to all apps immediately (even if related to gnome or kde).  It would be hard to miss for me, as I occasionally switch to a double or back... but I don't use that many apps commonly.

**Pull request merged**
