### PR TITLE
sapling: 0.2.20230124-180750-hf8cd450a -> 0.2.20230228-144002-h9440b05e

### PR DESCRIPTION
**Pull request by strager**
###### Description of changes

https://github.com/facebook/sapling/releases/tag/0.2.20230228-144002-h9440b05e

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by athre0z** [comment]
Result of `nixpkgs-review pr 219667` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>sapling</li>
  </ul>
</details>

**Review by thoughtpolice — APPROVED** [review]

**Comment by Krutonium** [comment]
All of a sudden, today this package no longer builds for me.

**Comment by strager** [comment]
@Krutonium Thanks for reporting the issue! I'll fix it.

**Comment by strager** [comment]
451c63214766d3bb8d078620cff4dc74463c5bc8 is the offending commit:
```
commit 451c63214766d3bb8d078620cff4dc74463c5bc8
Author: Martin Weinelt <hexa@darmstadt.ccc.de>
Date:   Wed Feb 8 21:42:08 2023 +0000

    python310Packages.setuptools: 65.0.3 -> 67.4.0

    https://setuptools.pypa.io/en/stable/history.html#v67-4-0

    Update license to MIT, add changelog URL, drop unnused rec.

    Refresh the setuptools-distutils-C++.patch.

 .../python-modules/setuptools/default.nix          | 11 +++++----
 .../setuptools/setuptools-distutils-C++.patch      | 28 +++++++++++-----------
 2 files changed, 20 insertions(+), 19 deletions(-)
```

This makes sense, because of these messages:
```
/nix/store/j9wa8hdvjin2kb0pmywhfni4kksw2v9v-python3.10-setuptools-67.4.0/lib/python3.10/site-packages/setuptools/_normalization.py:93: SetuptoolsDeprecationWarning: Invalid version: '0.2.20230124-180750-hf8cd450a'.
        !!


        ###################
        # Invalid version #
        ###################
        '0.2.20230124-180750-hf8cd450a' is not valid according to PEP 440.

        Please make sure specify a valid version for your package.
        Also note that future releases of setuptools may halt the build process
        if an invalid version is given.


!!

  warnings.warn(cleandoc(msg), SetuptoolsDeprecationWarning)

[snip]

setuptools.extern.packaging.version.InvalidVersion: Invalid version: '0.2.20230124-180750-hf8cd450a'
```

**Comment by strager** [comment]
I filed an issue upstream to discuss: https://github.com/facebook/sapling/issues/571

**Comment by strager** [comment]
Workaround patch: https://github.com/NixOS/nixpkgs/pull/221788

**Pull request merged**
