### PR TITLE
pantheon.elementary-feedback: 6.1.0 -> 6.1.1

### PR DESCRIPTION
**Pull request by bobby285271**
###### Description of changes

https://github.com/NixOS/nixpkgs/issues/170361

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
### [pantheon.elementary-feedback](https://github.com/elementary/feedback): [6.1.0 → 6.1.1](https://github.com/elementary/feedback/compare/6.1.0...6.1.1)



- [ ] [<code>l10n: Correctly setup the locales (#48)</code>](https://github.com/elementary/feedback/commit/080005153977a86d10099eff6a5b3e68f7b12847)
- [ ] [<code>MainWindow: use extra_data_location functions</code>](https://github.com/elementary/feedback/commit/82008b8f476c23d098fb1d5f6531b5cc33404f96)
- [ ] [<code>Bump actions to OS 7</code>](https://github.com/elementary/feedback/commit/d1f332f4ba138e46e07337dcbf277a72994e9fa6)
- [ ] [<code>MainWindow: Use Gtk.show_uri (#57)</code>](https://github.com/elementary/feedback/commit/ff494f974148200f312130c11771dbb3b0844748)
- [ ] [<code>Update feedback.appdata.xml.in</code>](https://github.com/elementary/feedback/commit/4b6dd75658e54b4b70b074d4df2abf688855e74e)
- [ ] [<code>MainWindow: Create one app row per ID (#63)</code>](https://github.com/elementary/feedback/commit/8960fabdc74a0bc7a97e44f48e306d916ae84378)
- [ ] [<code>Restore compatibility with AppStream < 0.15 (#65)</code>](https://github.com/elementary/feedback/commit/ab5d3ed4a8c94b7a4ec1c46c7314f5771234f38d)
- [ ] [<code>MainWindow: get correct icon name for non-stock icons (#62)</code>](https://github.com/elementary/feedback/commit/2bb6df916a957bc4d1554855dea5cd488d7a73ea)
- [ ] [<code>MainWindow: Get system entries from appstream (#64)</code>](https://github.com/elementary/feedback/commit/bd8a0a27acc436d4cd3dbe1e78868d291bb985c1)
- [ ] [<code>Update feedback.appdata.xml.in</code>](https://github.com/elementary/feedback/commit/9e688cf401f8601e43a1a54dacdfcf9fc1677dc2)
- [ ] [<code>Release 6.1.1 (#59)</code>](https://github.com/elementary/feedback/commit/f1cc92a62f31a248c35616747cb8dfcdea8d04c8) <sub>Tagged: <code>6.1.1</code></sub>

**Comment by bobby285271** [comment]
@ofborg test pantheon

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 175059` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pantheon.elementary-feedback</li>
  </ul>
</details>

**Review by davidak — DISMISSED** [review]
Change looks good

Builds, works

It opens the specific bug reporting site in browser. There are no entries for Panel indicators and  system settings. Is that expected?

I don't know if it should be merged now, so feel free to merge yourself!

**Comment by bobby285271** [comment]
Verified that this will not crash if

```vala
appstream_pool.add_extra_data_location ("/some/invalid/path/", AppStream.FormatStyle.METAINFO);
```

is added.

This is not part of the Pantheon installation (not presented in the module), for switchboard we open https://nixos.org/community.html (`SUPPORT_URL` specified in `/etc/os-release`) instead of this app.

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 175059` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pantheon.elementary-feedback</li>
  </ul>
</details>

**Comment by davidak** [comment]
Now it works, perfect!

Screenshot from 2022-05-28 08-55-32

**Review by davidak — APPROVED** [review]

**Pull request merged**
