### PR TITLE
sile: Drop broken flag on Darwin

### PR DESCRIPTION
**Pull request by alerque**
###### Description of changes

The broken flag was added as a part of a large batch of changes in cd3c25616d603598d32430e30ae676f93959f6bd. No root cause was identified there, and as the upstream maintainer of SILE I don't know what the issue would be. We've since gotten an inquiry about it upstream so I'm trying to figure out what the deal is.

This is an attempt to remove the flag, starting by just dropping it and seeing what CI has to say about the matter.

### CODE REVIEW

**Comment by Mic92** [comment]
```
trap 'rm -f $output' EXIT HUP TERM
echo "<sile>foo</sile>" | ./sile -o $output -
/nix/store/1107b378q1cibxsx1m0i702495vc0qwh-poppler-utils-22.08.0/bin/pdfinfo $output | /nix/store/bxdsvykpcnh23a7f4dh5qgsks17ry4jl-gnugrep-3.7/bin/grep "SILE v0.14.3"
SILE v0.14.3 (Lua 5.3)
/nix/store/g7hazgag5h28hf8knkz2diyipriqnfig-lua-5.3.6/bin/lua: error loading module 'justenoughlibtexpdf' from file './justenoughlibtexpdf.so':
        dlopen(./justenoughlibtexpdf.so, 6): Library not loaded: /nix/store/1aix8bcwgygyyllk8n8bnwak4qsqkpn0-sile-0.14.3/lib/libtexpdf.0.dylib
  Referenced from: /private/tmp/nix-build-sile-0.14.3.drv-0/sile-0.14.3/justenoughlibtexpdf.so
  Reason: image not found
stack traceback:
        [C]: in ?
        [C]: in function 'require'
        ./outputters/libtexpdf.lua:2: in main chunk
        [C]: in function 'require'
        ./core/sile.lua:40: in metamethod '__index'
        ./core/sile.lua:122: in function 'core.sile.init'
        ./sile:90: in main chunk
        [C]: in ?
Syntax Error: Document stream is empty
make: *** [Makefile:1399: selfcheck] Error 1
builder for '/nix/store/j0w7i111a84fgwzl2i8cv80nr21jl517-sile-0.14.3.drv' failed with exit code 2
```

**Comment by alerque** [comment]
Thanks for the output @Mic92, that's quite helpful since I don't have access to anything Darwin to actually test. However without access it's hard to find a fix!

Notably this error is from the `make selfcheck` step that runs after it thinks it has already built everything successfully. So no errors from the build, it just turns out the shared library it built is not usable.

The error is not that it couldn't *find* the `justenoughlibtexpdfo.so` module, but for some reason it can't load. It might be looking for something called `lib/libtexpdf.0.dylib`, but that isn't a build artifact I'm familiar with. Platform specific output from autotools? Maybe. But also broken.

Looking around the web the most similar error I can find (e.g. [this SO question](https://stackoverflow.com/questions/36530699/error-importing-packages-into-torch) are about *torch* in Luajit. Some people used to have similar issues on Mac OSX with that project. Unfortunately their solution seems to be scrubbing Python/Anaconda related stuff from their paths before trying to build. That doesn't sound so promising for us.

**Comment by OPNA2608** [comment]
`libtexpdf`'s install name is the problem. The install name is a path that's embedded into the dylib that tells applications that link against it where to find it. Here is a verbose snippet of the verbose build log:

```
libtool: link: clang -dynamiclib  -o .libs/libtexpdf.0.dylib  .libs/libtexpdf_la-agl.o .libs/libtexpdf_la-bmpimage.o .libs/libtexpdf_la-cff.o .libs/libtexpdf_la-cff_dict.o .libs/libtexpdf_la-cid.o .libs/libtexpdf_la-cidtype0.o .libs/libtexpdf_la-cidtype2.o .libs/libtexpdf_la-cmap.o .libs/libtexpdf_la-cmap_read.o .libs/libtexpdf_la-cmap_write.o .libs/libtexpdf_la-cs_type2.o .libs/libtexpdf_la-dpxcrypt.o .libs/libtexpdf_la-dpxfile.o .libs/libtexpdf_la-dpxutil.o .libs/libtexpdf_la-epdf.o .libs/libtexpdf_la-error.o .libs/libtexpdf_la-fontmap.o .libs/libtexpdf_la-jp2image.o .libs/libtexpdf_la-jpegimage.o .libs/libtexpdf_la-mem.o .libs/libtexpdf_la-mfileio.o .libs/libtexpdf_la-numbers.o .libs/libtexpdf_la-otl_conf.o .libs/libtexpdf_la-otl_opt.o .libs/libtexpdf_la-pdfcolor.o .libs/libtexpdf_la-pdfdev.o .libs/libtexpdf_la-pdfdoc.o .libs/libtexpdf_la-pdfdraw.o .libs/libtexpdf_la-pdfencrypt.o .libs/libtexpdf_la-pdfencoding.o .libs/libtexpdf_la-pdffont.o .libs/libtexpdf_la-pdfnames.o .libs/libtexpdf_la-pdfobj.o .libs/libtexpdf_la-pdfparse.o .libs/libtexpdf_la-pdfresource.o .libs/libtexpdf_la-pdfximage.o .libs/libtexpdf_la-pngimage.o .libs/libtexpdf_la-pst.o .libs/libtexpdf_la-pst_obj.o .libs/libtexpdf_la-sfnt.o .libs/libtexpdf_la-subfont.o .libs/libtexpdf_la-t1_char.o .libs/libtexpdf_la-t1_load.o .libs/libtexpdf_la-truetype.o .libs/libtexpdf_la-tt_aux.o .libs/libtexpdf_la-tt_cmap.o .libs/libtexpdf_la-tt_glyf.o .libs/libtexpdf_la-tt_gsub.o .libs/libtexpdf_la-tt_post.o .libs/libtexpdf_la-tt_table.o .libs/libtexpdf_la-type0.o .libs/libtexpdf_la-type1.o .libs/libtexpdf_la-type1c.o .libs/libtexpdf_la-unicode.o .libs/libtexpdf_la-pkfont.o .libs/libtexpdf_la-tfm.o   -L/nix/store/6hbz6qkc1cxm6h85fb6xw9f299wgza8d-zlib-1.2.12/lib -L/nix/store/p938mndmmkkk48nigcbg9lyi86m1gf7a-libpng-apng-1.6.37/lib -lz /nix/store/p938mndmmkkk48nigcbg9lyi86m1gf7a-libpng-apng-1.6.37/lib/libpng16.dylib  -g -O2   -install_name  /nix/store/v8qsi43j0a0crk8k2h33mszmay3rhm0x-sile-0.14.1/lib/libtexpdf.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module -Wl,-exported_symbols_list,.libs/libtexpdf-symbols.expsym
```

This has `-install_name  /nix/store/v8qsi43j0a0crk8k2h33mszmay3rhm0x-sile-0.14.1/lib/libtexpdf.0.dylib`, so when `justenoughlibtexpdf.so` links against `libtexpdf.0.dylib` it gets told that it should expect the library at this path. Because `checkPhase` runs before `installPhase` however, the dynamic loader tries to look up the library at a path that doesn't exist, so the load errors out.

---

The usual workaround is to move the testing to the `installCheckPhase`, which runs after `installPhase` has put the library in question in its final location.

```nix
doInstallCheck = stdenv.buildPlatform == stdenv.hostPlatform;
installCheckTarget = "check";
```

But there is this hack here that deletes everything in the build directory after installation, so that won't work as-is.

https://github.com/NixOS/nixpkgs/blob/2da64a81275b68fdad38af669afeda43d401e94b/pkgs/tools/typesetting/sile/default.nix#L103-L104

---

Another option would be to patch the reference to the pre-installation path.

```nix
preCheck = ''
  # libtexpdf.0.dylib has its final path as install name, patch it to the pre-installation path for tests
  install_name_tool -change $out/lib/libtexpdf.0.dylib $PWD/libtexpdf/.libs/libtexpdf.0.dylib src/.libs/justenoughlibtexpdf.so
'';
```

With that the test succeeds, but it throws the Makefile in a loop of infinitely forking and copying libraries from src/.libs to the pwd…

**Comment by alerque** [comment]
Thanks for the sleuthing on this @OPNA2608.

Maybe the best course would be to figure out how to fix instead of hack whatever is going on with the `preFixup` bit. Is that because of the call to `mktemp` in `make selfcheck` for the upstream project or is there some other root cause there?

**Comment by alerque** [comment]
Hmm, the `preFixup` seems to be unrelated. The makefile loop is also not easily fixable because as far as Make is concerned it is a valid problem: it does not expect things to be monkey patched. It might be possible to also touch it with an old date to fix the look, but that is getting messier and messier.

What about just skipping the `make selfcheck` on Darwin only? Something like `doCheck = !stdenv.isDarwin`?

This should eventually get sorted out when we start versioning and releasing libtexpdf separately — which is on our todo list but not an immanent thing.

**Comment by alerque** [comment]
@OPNA2608 Is it possible you monkey patched the wrong module (i.e. the original build in `./src/.libs` instead of the final one in `./`)? That might solve the loop issue even without backdating the timestamp.

**Comment by alerque** [comment]
> That's why I tried to modify the library in the location where it gets copied from.

It may not be important, but my idea was the make loop might have been caused by the timestamp update and it thinking it had to copy it over again.

**Comment by OPNA2608** [comment]
I don't think timestamps are even a consideration to the current Makefile, here's a log where i removed the `preCheck` and added abunch of additional `echo "Make #*"`s and `make`s after the main build. As you can see, it always runs the `cp`.

```
Make #4
make  all-recursive

[make stuff]

Making all in src
make[2]: Entering directory '/private/tmp/nix-build-sile-0.14.1.drv-0/sile-0.14.1/src'
cp .libs/justenoughharfbuzz.so .libs/justenoughfontconfig.so  .libs/justenoughlibtexpdf.so .libs/fontmetrics.so .libs/svg.so .libs/justenoughicu.so ..
make[2]: Leaving directory '/private/tmp/nix-build-sile-0.14.1.drv-0/sile-0.14.1/src'

[make stuff]

Make #5
make  all-recursive

[make stuff]

Making all in src
make[2]: Entering directory '/private/tmp/nix-build-sile-0.14.1.drv-0/sile-0.14.1/src'
cp .libs/justenoughharfbuzz.so .libs/justenoughfontconfig.so  .libs/justenoughlibtexpdf.so .libs/fontmetrics.so .libs/svg.so .libs/justenoughicu.so ..
make[2]: Leaving directory '/private/tmp/nix-build-sile-0.14.1.drv-0/sile-0.14.1/src'

[make stuff]

Make #6
make  all-recursive

[make stuff]

Making all in src
make[2]: Entering directory '/private/tmp/nix-build-sile-0.14.1.drv-0/sile-0.14.1/src'
cp .libs/justenoughharfbuzz.so .libs/justenoughfontconfig.so  .libs/justenoughlibtexpdf.so .libs/fontmetrics.so .libs/svg.so .libs/justenoughicu.so ..
make[2]: Leaving directory '/private/tmp/nix-build-sile-0.14.1.drv-0/sile-0.14.1/src'

[make stuff]

running tests
check flags: -j12 -l12 SHELL=/nix/store/db7n4xkfng8y4c3klp6bjppaws3rphq6-bash-5.1-p16/bin/bash VERBOSE=y check
make  all-recursive

[make stuff]

Making all in src
make[2]: Entering directory '/private/tmp/nix-build-sile-0.14.1.drv-0/sile-0.14.1/src'
cp .libs/justenoughharfbuzz.so .libs/justenoughfontconfig.so  .libs/justenoughlibtexpdf.so .libs/fontmetrics.so .libs/svg.so .libs/justenoughicu.so ..
make[2]: Leaving directory '/private/tmp/nix-build-sile-0.14.1.drv-0/sile-0.14.1/src'

[make stuff]

touch .built-subdirs
output=/var/folders/d5/pfw86dn93qddkrsqqskfx10m0000gn/T/selfcheck-XXXXXX.pdf.CpVZjmFD
trap 'rm -f ' EXIT HUP TERM
echo "<sile>foo</sile>" | ./sile -o  -
/nix/store/b22nd1q0d73b9nfybv7k5ahqvq98xz5a-poppler-utils-22.08.0/bin/pdfinfo  | /nix/store/jdvpk1v5a1bbzfjm510b97p0bh7vnc5q-gnugrep-3.7/bin/grep "SILE v0.14.1"
SILE v0.14.1 (Lua 5.3)
/nix/store/5kjz4r98hwhlijr8z1rssr26wh04ywp9-lua-5.3.6/bin/lua: error loading module 'justenoughlibtexpdf' from file './justenoughlibtexpdf.so':
        dlopen(./justenoughlibtexpdf.so, 6): Library not loaded: /nix/store/n50ba504727qq38rck880ggkkzji4y2b-sile-0.14.1/lib/libtexpdf.0.dylib
  Referenced from: /private/tmp/nix-build-sile-0.14.1.drv-0/sile-0.14.1/justenoughlibtexpdf.so
  Reason: image not found
```

https://github.com/sile-typesetter/sile/blob/a88575e416e20cfda46405dec7a8ac2c3b638188/src/Makefile.am#L64-L65

I don't really deal with plain Makefiles and don't know how exactly to write this to affect all libs, but wouldn't this need to look smth like

```make
../justenoughlibtexpdf.@SHARED_LIB_EXT@: .libs/justenoughlibtexpdf.@SHARED_LIB_EXT@
	cp .libs/justenoughlibtexpdf.@SHARED_LIB_EXT@ ../
```

for Make to care about timestamps?

**Comment by OPNA2608** [comment]
> What about just skipping the `make selfcheck` on Darwin only? Something like `doCheck = !stdenv.isDarwin`?
> 
> This should eventually get sorted out when we start versioning and releasing libtexpdf separately — which is on our todo list but not an immanent thing.

To me that seems like an okay workaround for now if you also add a comment explaining that, due to install name and makefile shenanigans, tests cannot be run on Darwin for now.

**Comment by alerque** [comment]
@OPNA2608 How does this iteration sit with you?

**Comment by stephank** [comment]
I think disabling tests is probably best the option here.

I was messing around with this, and we actually can do `installCheckPhase` if we want, simply by replace the `rm -fr` trick with a `mv` instead, and restoring it in `postFixup`. The build directory just needs to not exist during the patchelf setup hook, so that it sees the missing paths and removes them from rpath.

But I ran into more issues. One is that a shebang `#!/.../bin/lua` doesn't work for us, because our `lua` is a shell script wrapper, and Darwin requires that a shebang point to an actual binary. Mysteriously, this only fails inside the `nix-build` / `nix-shell` environment, but otherwise just works? I'm not sure what actually implements shebang logic in Darwin to understand why there is a difference.

The other issue I got is that (even without any manual patching of the install path) `make check` still goes into an infinite loop. Maybe that has to do with some of the automatic patching we do in setup hooks? But I believe those don't touch the build directory.

In any case, neither of these issues is a problem if we disable tests.

It's worth noting that the CMake solution to this (I believe) is to build with install name `@rpath/libsomething.dylib`, then fill rpath with both install and build paths. The build rpath can later be removed, but this keeps things working pre-install. I just don't think that's something autotools supports?

**Comment by alerque** [comment]
> Mysteriously, this only fails inside the `nix-build` / `nix-shell` environment, but otherwise just works?

This probably has to do with the order in which we monkey-patch those paths, also part of the build.

I would say dropping the selfcheck test entirely is reasonable. It is helpful in the upstream project's CI to make sure the build worked end-to-end, but in the context of the Nix build we can't really do and end to end check since the build isn't the end of the matter. Since anything we do to make the self check work will inherently just be a special patch for that operation, we're not really testing the final result anyway hence defeating the purpose.

**Comment by doronbehar** [comment]
> But I ran into more issues. One is that a shebang #!/.../bin/lua doesn't work for us, because our lua is a shell script wrapper, and Darwin requires that a shebang point to an actual binary.

This is an old known issue and it was the original reason for marking sile as broken on Darwin but https://github.com/NixOS/nixpkgs/pull/172749 should have fixed this. @stephank could you test whether https://github.com/NixOS/nixpkgs/pull/172749 actually did something - test whether creating a `lua.withPackages(ps: with ps; [ ])` creates a binary wrapper or not?

**Comment by stephank** [comment]
> This is an old known issue and it was the original reason for marking sile as broken on Darwin but #172749 should have fixed this. @stephank could you test whether #172749 actually did something - test whether creating a `lua.withPackages(ps: with ps; [ ])` creates a binary wrapper or not?

Ah! It looks like that didn't work:

```
$ nix-build -E 'with import ./. { }; lua.withPackages(ps: [ ])'
/nix/store/s1jsckpsqmh8hs108f6xvw8668kdy1qk-lua-5.2.4-env

$ cat /nix/store/s1jsckpsqmh8hs108f6xvw8668kdy1qk-lua-5.2.4-env/bin/lua
#! /nix/store/8q570yrfxa7f2yslrqal1jscx79939dy-bash-5.1-p16/bin/bash -e
export LUA_PATH=${LUA_PATH-';;'}
export LUA_CPATH=${LUA_CPATH-';;'}
exec "/nix/store/h5gas624jl1ibj4265i5v3gc1rzr66yb-lua-5.2.4/bin/lua"  "$@"
```

**Comment by stephank** [comment]
Looks like the fix did work originally, was undone. I made a PR here, but I believe that has to go through staging first: https://github.com/NixOS/nixpkgs/pull/194389

**Comment by doronbehar** [comment]
Let's recheck how sile works on darwin when https://github.com/NixOS/nixpkgs/pull/194389 lands in master, it'll take a while.

**Comment by alerque** [comment]
https://nixpk.gs/pr-tracker.html?pr=194389

**Comment by alerque** [comment]
@doronbehar What's your understanding of where we are at with this broken flag?

**Comment by doronbehar** [comment]
> @doronbehar What's your understanding of where we are at with this broken flag?

Now that `lua.withPackages` produces a `lua` with a binary wrapper, it should be possible to keep check this on a darwin machine. I see that https://github.com/NixOS/nixpkgs/pull/173671 marked `sile` as broken on Darwin lastly, only because hydra failed to build it (can't get build logs from back then at present).

**Comment by alerque** [comment]
@doronbehar I've now tried this build with (d484852) and without (dbf72c9) the hotfix patch and both sets of CI runs are throwing an error. I'm not sure whether to blame the Lua binary wrapper or the monkey patching or what...

**Comment by doronbehar** [comment]
The error:

> `justenoughlibtexpdf' from file './justenoughlibtexpdf.so': dlopen(./justenoughlibtexpdf.so, 0x0006):`

Suggests that the build assumes the dynamic library extension is `.so` and not `.dylib`. Perhaps this line does this:

https://github.com/sile-typesetter/sile/blob/2f9e06d1cd63ae17a3be39c39c74bd5161308701/Makefile.am#L172-L174

**Comment by alerque** [comment]
> ghlibtexpdf' from file './justenoughlibtexpdf.so': dlopen(./justenoughlibtexpd

Hmm, maybe. We have `${SHARED_LIB_EXT}` already in use elsewhere. At the same time that error is on the second build with the patch back in place and might be it is just trying to patch the wrong file. On the first build at least the error is different and generated from Lua. The Lua doesn't include any extension at all and uses its platform knowledge to find modules. The error message shows dynlib extentions were tried.

**Comment by alerque** [comment]
Looking at the current iteration, I don't see any evidence that the `preCheck` patch is actually working. I don't see anything in the build log after the `cp` that moves the generated `justenoughlibtexpdf.so` out of the submodule where it is built into the root build dir where it is used for the self check, and later when it is used that indicates the patch actually happened. It might of course be silent or logged elsewhere, but the error also suggests it did not get patched:

```
  Referenced from: '/private/tmp/nix-build-sile-0.14.7.drv-0/sile-0.14.7/justenoughlibtexpdf.so'
  Reason: tried: '/nix/store/27h2pamq1gzrdmq54r7n21flk9h4fjj8-sile-0.14.7/lib/libtexpdf.0.dylib' (no such file), '/usr/local/lib/libtexpdf.0.dylib' (no such file), '/usr/lib/libtexpdf.0.dylib' (no such file)
  ```

**Comment by wegank** [comment]
> trap 'rm -f $output' EXIT HUP TERM
> echo "<sile>foo</sile>" | ./sile -o $output -
> /nix/store/1107b378q1cibxsx1m0i702495vc0qwh-poppler-utils-22.08.0/bin/pdfinfo $output | /nix/store/bxdsvykpcnh23a7f4dh5qgsks17ry4jl-gnugrep-3.7/bin/grep "SILE v0.14.3"
> SILE v0.14.3 (Lua 5.3)
> /nix/store/g7hazgag5h28hf8knkz2diyipriqnfig-lua-5.3.6/bin/lua: error loading module 'justenoughlibtexpdf' from file './justenoughlibtexpdf.so':
>         dlopen(./justenoughlibtexpdf.so, 6): Library not loaded: /nix/store/1aix8bcwgygyyllk8n8bnwak4qsqkpn0-sile-0.14.3/lib/libtexpdf.0.dylib
>   Referenced from: /private/tmp/nix-build-sile-0.14.3.drv-0/sile-0.14.3/justenoughlibtexpdf.so
>   Reason: image not found

This actually means that `./justenoughlibtexpdf.so` exists, but `/nix/store/1aix8bcwgygyyllk8n8bnwak4qsqkpn0-sile-0.14.3/lib/libtexpdf.0.dylib` doesn't. The latter is simply due to the fact that `installPhase` is after `checkPhase`, so the issue cannot be solved with `preCheck`. Opened #210096 for migrating to `installCheckPhase`.

**Comment by alerque** [comment]
Closing in favor of #210096.

**Pull request closed without merging**
