### PR TITLE
mongosh: 1.10.6 -> 2.0.1

### PR DESCRIPTION
**Pull request by aaronjheng**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by applePrincess** [comment]
Result of `nixpkgs-review pr 256997` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mongosh</li>
  </ul>
</details>

**Review by applePrincess — APPROVED** [review]

**Comment by applePrincess** [comment]
```console
[nix-shell:~/.cache/nixpkgs-review/pr-256997]$ ./results/mongosh/bin/mongosh
Current Mongosh Log ID:	65106ab5415753301b452c27
Connecting to:		mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.0.1
Using MongoDB:		6.0.10
Using Mongosh:		2.0.1

For mongosh info see: https://docs.mongodb.com/mongodb-shell/


To help improve our products, anonymous usage data is collected and sent to MongoDB periodically (https://www.mongodb.com/legal/privacy-policy).
You can opt-out by running the disableTelemetry() command.

------
   The server generated these startup warnings when booting
   2023-09-24T16:58:28.871+00:00: Access control is not enabled for the database. Read and write access to data and configuration is unrestricted
   2023-09-24T16:58:28.871+00:00: vm.max_map_count is too low
------
```
looks good to me

**Review by dotlambda — COMMENTED** [review]
Please use `buildNpmPackage`. See https://github.com/NixOS/nixpkgs/pull/251377#issuecomment-1704468830.

**Comment by wegank** [comment]
The package already uses `buildNpmPackage`, and from my tests the upstream `package-lock.json` causes build failures with `buildPhase` trying to fetch `lerna`.

**Comment by dotlambda** [comment]
> The package already uses `buildNpmPackage`, and from my tests the upstream `package-lock.json` causes build failures with `buildPhase` trying to fetch `lerna`.

Oops that's what I meant. Do we at least have an issue tracking that?

**Pull request merged**
