### PR TITLE
nginx: update to 1.20.0, replace zlib to zlib-ng

### PR DESCRIPTION
**Pull request by Izorkin**
###### Motivation for this change
Replace zlib to new library zlib-ng.
Work tested on home server.

```
ldd ./result/bin/nginx | grep zlib
libz.so.1 => /nix/store/ivp7pbwlgfc8izmnzfbmfysas289qal8-zlib-ng-2.0.2/lib/libz.so.1 (0x0000602cb4d76000)
```
cc @aanderse @Mic92

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I don't think we should use an unofficial patch by default and testing this on a home server is probably not enough.

**Comment by Izorkin** [comment]
> I don't think we should use an unofficial patch by default and testing this on a home server is probably not enough.

This patch is pending review and planned to include it in the next version. It is likely that other people have tried this patch as well. Messages about new bugs would appear on the forum.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 118338` at a03ca279 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built successfully:</summary>
  <ul>
    <li>devpi-client</li>
    <li>devpi-server</li>
    <li>nginx (nginxStable)</li>
    <li>nginxMainline</li>
    <li>nginxShibboleth</li>
    <li>openresty</li>
  </ul>
</details>
<details>
  <summary>5 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/servers/http/nginx/generic.nix:119:5:
```
    |
119 |     ./nix-skip-check-logs-path.patch
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/servers/http/nginx/generic.nix:131:5:
```
    |
131 |     (fetchpatch {
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/servers/http/nginx/generic.nix:113:5:
```
    |
113 |     (substituteAll {
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/servers/http/nginx/generic.nix:127:5:
```
    |
127 |     (fetchpatch {
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/servers/http/nginx/generic.nix:123:5:
```
    |
123 |     (fetchpatch {
    |     ^
```
</li>
  </ul>
</details>

**Comment by ajs124** [comment]
I'd be more comfortable with merging this, once it actually gets committed to nginx and we can fetch it from there or just waiting for the release.

My Russian isn't quite good enough to follow the discussion (извини), how long do you think it will take until this is part of a nginx release @Izorkin?

**Comment by Izorkin** [comment]
> My Russian isn't quite good enough to follow the discussion (извини), how long do you think it will take until this is part of a nginx release @Izorkin?

Hopefully in version 1.19.10. But I can't guarantee it, only hope :)

**Comment by ajs124** [comment]
My vote would be for waiting on upstream then, if that's fine by you.

**Comment by Mic92** [comment]
I also would like to wait.

**Comment by Izorkin** [comment]
Patch added to upstream. Updated PR.

**Comment by ajs124** [comment]
[1.19.10](https://nginx.org/en/CHANGES) was released yesterday, which includes the necessary patch for this.

**Comment by Izorkin** [comment]
@ajs124 I don't know how to apply the patch for nginxStable.

**Comment by ajs124** [comment]
Hm. Do you need this in nginxStable? If not, we could just update nginxMainline and only have the override to zlib-ng there.

**Comment by Izorkin** [comment]
@ajs124 ok, updated PR.

**Review by ajs124 — APPROVED** [review]
This is probably alright. Would be nice to have a test for it, but I'm also fine with not having one.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 118338` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>nginxMainline</li>
</ul>
</details>

**Comment by Izorkin** [comment]
Update nginxMainline and nginxStable to 1.20.0.

cc @Mic92 @ajs124

**Review by ajs124 — APPROVED** [review]
If we're going to merge the stable update before branch-off, it might be worth mentioning in the release notes. Might also not be, idk.

All the tests still seem to pass. I haven't rolled this release (1.20.0) out in our infrastructure yet, but it seems equivalent to 1.19.10 when looking through the commit history here https://hg.nginx.org/nginx, which we have been running, including the zlib change. Although we don't use zlib with nginx in many places.

**Comment by Izorkin** [comment]
Added release notes

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
