### PR TITLE
zig: 0.12.0 -> 0.12.1

### PR DESCRIPTION
**Pull request by jmbaur**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kirillrdy** [comment]
Result of `nixpkgs-review pr 317896` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>cargo-lambda</li>
    <li>cargo-zigbuild</li>
    <li>clipbuzz</li>
    <li>glsl_analyzer</li>
    <li>mepo</li>
    <li>ncdu</li>
    <li>river</li>
    <li>river.man</li>
    <li>rivercarro</li>
    <li>waylock</li>
    <li>zig (zig_0_12)</li>
    <li>zig.doc (zig_0_12.doc)</li>
    <li>zls</li>
  </ul>
</details>

**Comment by paparodeo** [comment]
darwin / clang are broken due to https://github.com/NixOS/nixpkgs/issues/317055 (seems to be an issue with cmake getting libclang in the bin search path and trying to build with unwrapped clang when strictDeps = true)

**Comment by jmbaur** [comment]
> darwin / clang are broken due to https://github.com/NixOS/nixpkgs/issues/317055 (seems to be an issue with cmake getting libclang in the bin search path and trying to build with unwrapped clang when strictDeps = true)

Does this change affect that breakage or otherwise negatively influence it? I would think not if it is also broken on 0.12.0

**Comment by paparodeo** [comment]
> > darwin / clang are broken due to #317055 (seems to be an issue with cmake getting libclang in the bin search path and trying to build with unwrapped clang when strictDeps = true)
> 
> Does this change affect that breakage or otherwise negatively influence it? I would think not if it is also broken on 0.12.0

maybe? https://github.com/NixOS/nixpkgs/pull/317861 uses `strictDeps = !stdenv.cc.isClang;` to work around the issue. unclear if this PR further breaks clang / darwin given the preexisting `strictDeps` issue can masks any further breakages. but ofborg is failing in this PR for darwin and #317055 is likely the cause.

**Comment by paparodeo** [comment]
@jmbaur i think there is a misunderstanding -- i am not a committer nor a reviewer but was just pointing out the likely cause of the build failure in ofborg.

**Comment by jmbaur** [comment]
> @jmbaur i think there is a misunderstanding -- i am not a committer nor a reviewer but was just pointing out the likely cause of the build failure in ofborg.

Ah my apologies!

**Comment by jmbaur** [comment]
@paparodeo changed PR to use same method as the zig 0.13 init PR to fix building with clang.

**Comment by khaneliman** [comment]
Result of `nixpkgs-review pr 317896` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>rivercarro</li>
  </ul>
</details>
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>cargo-lambda</li>
    <li>cargo-zigbuild</li>
    <li>glsl_analyzer</li>
    <li>ncdu</li>
    <li>zig_0_12</li>
    <li>zig_0_12.doc</li>
    <li>zls</li>
  </ul>
</details>

**Review by paparodeo — APPROVED** [review]
<details><summary>built zig with clang on linux and then ran nixpkgs-review</summary>

```diff
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index 2bfb7251126f..c5c3f29c59a8 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -25029,6 +25029,7 @@ with pkgs;
   # requires a newer Apple SDK
   zig_0_12 = darwin.apple_sdk_11_0.callPackage ../development/compilers/zig/0.12 {
     llvmPackages = llvmPackages_17;
+    stdenv = clangStdenv;
   };
   zig = zig_0_12;
 
```
</details>

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>cargo-lambda</li>
    <li>cargo-zigbuild</li>
    <li>clipbuzz</li>
    <li>glsl_analyzer</li>
    <li>mepo</li>
    <li>ncdu</li>
    <li>river</li>
    <li>river.man</li>
    <li>rivercarro</li>
    <li>waylock</li>
    <li>zig_0_12</li>
    <li>zig_0_12.doc</li>
    <li>zls</li>
  </ul>
</details>

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 317896` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>cargo-lambda</li>
    <li>cargo-zigbuild</li>
    <li>clipbuzz</li>
    <li>glsl_analyzer</li>
    <li>mepo</li>
    <li>ncdu</li>
    <li>river</li>
    <li>river.man</li>
    <li>rivercarro</li>
    <li>waylock</li>
    <li>zig_0_12</li>
    <li>zig_0_12.doc</li>
    <li>zls</li>
  </ul>
</details>

**Review by marcusramberg — APPROVED** [review]
lgtm.

**Pull request merged**
