### PR TITLE
mpdecimal: init at 2.5.1

### PR DESCRIPTION
**Pull request by KAction**

### CODE REVIEW

**Comment by KAction** [comment]
@happysalada Can you please review this one?

**Comment by happysalada** [comment]
The darwin build is failing, could you mark this one as linux only ? or fix the darwin build if you prefer.

**Comment by happysalada** [comment]
Thank you !

**Comment by KAction** [comment]
Wait, tests didn't pass yet. I am not sure change I force-pushed actually solves anythings, I don't have mac with nix around, that was guesswork. Or you built locally?

**Comment by happysalada** [comment]
Yes i did.

**Pull request merged**
