### PR TITLE
fcitx5-*: update to 5.1.0

### PR DESCRIPTION
**Pull request by linsui**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Vonfry** [comment]
Changelog: https://groups.google.com/g/fcitx-announce/c/Pq0TVFY10bI

**Review by Vonfry — APPROVED** [review]
```
> nix build --impure --expr 'with (builtins.getFlake "/home/vonfry/repos/nixpkgs").outputs.legacyPackages.x86_64-linux; fcitx5-with-addons.override { addons = [ fcitx5-rime ]; }'
> ./result/bin/fcitx5 -rd
```
It is worked for me. 你好！

`nix build '.#nixosTests.fcitx5'` passed as well.

**Comment by NickCao** [comment]
Let's wait a bit for fcitx-rime to make a release containing the fix for https://github.com/fcitx/fcitx5-rime/issues/63

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 249922` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>21 packages built:</summary>
  <ul>
    <li>fcitx5</li>
    <li>fcitx5-anthy</li>
    <li>fcitx5-chewing</li>
    <li>fcitx5-chinese-addons</li>
    <li>fcitx5-configtool</li>
    <li>fcitx5-gtk</li>
    <li>fcitx5-hangul</li>
    <li>fcitx5-lua</li>
    <li>fcitx5-m17n</li>
    <li>fcitx5-mozc</li>
    <li>fcitx5-rime</li>
    <li>fcitx5-skk</li>
    <li>fcitx5-skk-qt</li>
    <li>fcitx5-table-extra</li>
    <li>fcitx5-table-other</li>
    <li>fcitx5-unikey</li>
    <li>fcitx5-with-addons</li>
    <li>libime</li>
    <li>libsForQt5.fcitx5-qt (plasma5Packages.fcitx5-qt)</li>
    <li>mlterm</li>
    <li>mlterm-wayland</li>
  </ul>
</details>

**Review by ElnuDev — APPROVED** [review]
```
> nix build --impure --expr 'with (builtins.getFlake "/home/elnu/Projects/nixpkgs").outputs.legacyPackages.x86_64-linux; fcitx5-with-addons.override { addons = [ fcitx5-anthy ]; }'
> ./result/bin/fcitx5 -rd
```

LGTM

**Comment by Vonfry** [comment]
fcitx5-rime 5.1.1 is released. Would you like to update it again?

**Comment by linsui** [comment]
There is no 5.1.1 tag in https://github.com/fcitx/fcitx5-rime/tags.

**Comment by Vonfry** [comment]
The upstream forgot to tag the release. However, replacing github repo with `download.fcitx-im.org` may break the update script.

**Comment by linsui** [comment]
The update script only use github to get the version. It works for anthy.

**Review by ElnuDev — APPROVED** [review]

**Pull request merged**
