### PR TITLE
zbar: 0.23.90 -> 0.23.92 (+ enable checkPhase)

### PR DESCRIPTION
**Pull request by delroth**
###### Description of changes

0.23.92 was released a while back but we never bumped to it for some reason. It's only very minor changes over 0.23.90 anyway so I don't think we've missed anything too interesting. Just happened to notice it.

While bumping the package I noticed upstream has unit tests and we're not running them. That's now fixed.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
Fails for me on macos 10.15:

```
make[3]: Entering directory '/private/tmp/nix-build-zbar-0.23.92.drv-0/source'
  CC       test/test_images.o
  CXX      test/test_cpp.o
  CC       test/test_decode-test_decode.o
  CXX      test/test_cpp_img.o
  CC       test/test_proc.o
  CC       test/test_jpeg.o
  CC       test/test_convert.o
test/test_jpeg.c:25:10: fatal error: 'argp.h' file not found
#include <argp.h>
         ^~~~~~~~
test/test_decode.c:24:10: fatal error: 'argp.h' file not found
#include <argp.h>
         ^~~~~~~~
```

ofborg seems to agree.

**Comment by delroth** [comment]
> Fails for me on macos 10.15:

Thanks for notifying me, when I pushed the PR ofborg had days of queue time for Darwin builds so I couldn't really check...

This is likely a fixable problem but I went the easy route and disabled the checkPhase on !Linux since I lack the capability to test on Darwin. Still an improvement over the previous state, if someone cares about Darwin support (I don't) I'll gladly review further patches.

**Comment by risicle** [comment]
The tests will work if in the darwin case you add `argp-standalone` to `nativeCheckInputs` and add a `preCheck` with `export NIX_LDFLAGS="$NIX_LDFLAGS -largp"`.

**Comment by 7c6f434c** [comment]
@risicle maybe push a commit on top of the branch? As you already have the checked code…

**Pull request merged**
