### PR TITLE
Teleconsole

### PR DESCRIPTION
**Pull request by kimburgess**
###### Motivation for this change

Add support for [Teleconsole](https://www.teleconsole.com/).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by tomberek** [comment]
0.4.0 is out now. Perhaps it will build? I remember playing with this a while back for `teleport`.

**Comment by KimBurgess** [comment]
Thanks for the bump! Just checked and can confirm the builds are back up and functional. I'll pop together a new derivation some time over the next few days.

**Comment by KimBurgess** [comment]
Woah. Something went really wrong in that rebase. I'm going to nuke this and resubmit a new PR based on a more modern branch.

**Comment by KimBurgess** [comment]
New PR up at https://github.com/NixOS/nixpkgs/pull/48108.

**Pull request closed without merging**
