### PR TITLE
netbsd: 7.1.2 -> 8.0

### PR DESCRIPTION
**Pull request by dtzWill**
I think everything that worked before still works O:)

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
Eep well it worked on Linux :innocent: .

**Comment by matthewbauer** [comment]
Looks good! A few hashes didn’t change with the version though. That might be because the underlying source didn’t change either though. I can look at darwin failures - there’s also aarch64 ones as well.

**Comment by dtzWill** [comment]
Please check if it's not trouble, but I can say at least a few sure seemed to be the same when I tried to check again, but definitely may have missed one or more.  Thanks re:failures, I'll see what I can turn up as well :).

**Comment by matthewbauer** [comment]
For reference, I was working on a NetBSD cross support branch here:

https://github.com/matthewbauer/nixpkgs/commits/netbsd

I don't think we're quite ready to start merging something like this yet- but might be useful as I changed some unrelated things. Eventually I'd like to get bootstrap tools for netbsd.

**Pull request merged**
