### PR TITLE
Update rust and dependants

### PR DESCRIPTION
**Pull request by globin**
This updates:
- rust
- rustUnstable
- rustRegistry
- cargo
- rustfmt

PR is tested

### CODE REVIEW

**Comment by domenkozar** [comment]
I'd like to cherry-pick this to release-15.09 if it fixes transient builds for cargo on i686

**Comment by globin** [comment]
@wkennington apparently did most of this stuff already just now, I cannot guarantee that this will fix the cargo failures, but possibly it could, will have to see.

**Comment by globin** [comment]
I'll rebase on those changes

**Comment by jagajaga** [comment]
What about racer?

**Comment by globin** [comment]
Yep! racer WIP, will push onto here in a sec.

**Comment by globin** [comment]
@domenkozar https://hydra.glob.in/build/1025/nixlog/2 this seems to fix cargo, didn't try to update dependencies.

**Pull request merged**
