### PR TITLE
openexr: 2.5.8 -> 2.5.10

### LINKED ISSUE #278713: Build failure: pkgsMusl.openexr
### Steps To Reproduce

1. build pkgsMusl.openexr

### Build log

https://termbin.com/a5uw

### Metadata

commit 494bdb470881cb8714b47a0bbb0048157e8fdeda (nixos/staging-next)

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by eclairevoyant**
## Description of changes

Fixes #278713.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by yu-re-ka** [comment]
Why do you think this fixes https://github.com/NixOS/nixpkgs/issues/278713 ?
For me the build of pkgsMusl.openexr still fails: https://termbin.com/e6yw

**Comment by eclairevoyant** [comment]
Must've built the wrong variant, should be fixed now.

**Comment by yu-re-ka** [comment]
Indeed now I can build `pkgsMusl.openexr_2`. Care to adjust the commit message to explain how you arrived at this patch? Ideally we would submit it upstream

**Comment by eclairevoyant** [comment]
* I removed the old patch because it was included in [the 2.5.9 release](https://github.com/AcademySoftwareFoundation/openexr/commit/310ae8600bea9eb58462ac8ed8dce49d0e4ecf6a)
* I added the new patch based on my knowledge of headerfile changes in GCC 13 and reading the error to know what file was affected. It's also substantially similar to the existing patch. I admittedly didn't look at the filename in the error carefully the first time round, hence the build issue you encountered initially.
* I'm not willing to contribute code upstream as they require a CLA

**Review by yu-re-ka — APPROVED** [review]

**Pull request merged**
