### PR TITLE
go-mode: init at 20150817

### PR DESCRIPTION
**Pull request by anderspapitto**

### CODE REVIEW

**Comment by oxij** [comment]
Can you please rebase onto something futher than
6a192b4e986993dbae88fa0cffcd4074e5d563a6 and then add a proper
description there?

**Comment by anderspapitto** [comment]
@oxij rebased onto master and added a description

**Comment by oxij** [comment]
Thank you!

:+1:

**Comment by anderspapitto** [comment]
@oxij would you like to merge this, or are we waiting for something else?

**Comment by oxij** [comment]
I would, but I don't have the right.

/cc @jagajaga @ttuegel

**Pull request merged**
