### PR TITLE
Xapian: Remove 1.0, Upgrade 1.2, and pin bindings to php 5.6

### PR DESCRIPTION
**Pull request by grahamc**
###### Things done:
- [ ] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by joachifm** [comment]
xapianBindings was already broken: https://github.com/NixOS/nixpkgs/issues/13899

**Comment by grahamc** [comment]
Closing for now.

**Comment by joachifm** [comment]
What about simply disabling the PHP bindings?

**Comment by joachifm** [comment]
The only thing I'm able to come up with is that `php_config.h` erronously defines the symbol `HAVE_UNIX_H` to indicate the presence of `<unix.h>`, which the PHP configure script states is required for some stuff on QNX. Best I can tell, `<unix.h>` is not a thing on Linux or BSD.

**Comment by grahamc** [comment]
@joachifm Yeah, so I disabled the PHP bindings and that was fine. Then, in the rebuild other packages were failing to build. I'm thinking I'll keep my php70 PR open and get the changes to all build correctly, and then can separate them into separate PRs if that is ultimately desired. Does that sound OK?

**Comment by joachifm** [comment]
Ah, I didn't see that commit. Sounds reasonable.

**Pull request closed without merging**
