### PR TITLE
source-han-{sans,serif,mono}: {update,refactor,init}

### PR DESCRIPTION
**Pull request by emilazy**
###### Motivation for this change

The Source Han fonts now use shared package infrastructure, and the Super OTC distributions, which unify the various scripts into a single bundle file, improving automatic font selection and reducing overall disk space usage. This also means that the Traditional Chinese—Hong Kong language variant is now included.

The old package names including language are aliased to the Super OTC bundle packages.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by emilazy** [comment]
@GrahamcOfBorg build source-han-sans source-han-serif source-han-mono

**Comment by taku0** [comment]
[The official README](https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf) recommends language specific OTFs for Linux.  Actually, I experienced that some applications (sorry, I forgot which one was) fail to select proper language. I will try this branch.

**Comment by emilazy** [comment]
I don't see any specific recommendation for Linux in that document (but maybe I'm missing it?), just notes that lots of font engines don't handle the Super OTCs well – I think that's probably out of date, since I've had no problems with it in my testing so far, and if anything the results for multilingual content are better. Custom fontconfig does potentially need adjusting to use the generic `Source Han …` aliases without the language code, though. [This upstream issue](https://github.com/googlefonts/noto-cjk/issues/85) for Noto CJK (which is almost identical to Source Han) suggests that Super OTCs would be recommended for Linux if there were any concrete recommendations.

**Comment by taku0** [comment]
I mean “Other” in the flowchart. Anyway, I will try this branch with Firefox, Inkscape, LibreOffice, KDE, and GNOME desktop in a clean virtual machine.

**Review by taku0 — APPROVED** [review]
It works fine, at least for Japanese locale. Size of the files could be a problem, but IMO it is acceptable.

**Comment by emilazy** [comment]
Updated to use `stdenvNoCC` to cut down on extraneous rebuilds.

@GrahamcOfBorg build source-han-sans source-han-serif source-han-mono

**Review by taku0 — APPROVED** [review]
LGTM

**Review by lukateras — APPROVED** [review]

**Review by taku0 — APPROVED** [review]
OK. Only the context of the diffs are changed.
https://github.com/NixOS/nixpkgs/commit/0715ba3589394f4c5870e8dbcbbe39e854698667
https://github.com/NixOS/nixpkgs/commit/6eb45bf38ac122a242be8bce2b9868ac72a6e0cc

**Pull request merged**
