### PR TITLE
Update LLVM, unstable Rust and crate.io registry

### PR DESCRIPTION
**Pull request by abbradar**
Also drops Rust-specific LLVM patch and enables system LLVM for unstable Rust.

Cargo release fails to build with nightly Rust, so I've added `cargoUnstable` pointing at the git snapshot.

### CODE REVIEW

**Comment by globin** [comment]
(llvm is already on staging, see #12200)

**Comment by abbradar** [comment]
I think I'll test building this on an older LLVM later, and if not then rebase on `staging`. Thanks for the heads up!

**Comment by abbradar** [comment]
This works with 3.7.0 but I think let's push this into `staging` to avoid Rust double rebuild (with `3.7.0` on `master` and 3.7.1 when `staging` is merged). I'm going to pick this into `staging` in several days if no issues are found before...

**Comment by wizeman** [comment]
It looks good to me on the Rust / cargo side.

**Pull request closed without merging**
