### PR TITLE
dialect: 2.1.1 -> 2.2.0

### PR DESCRIPTION
**Pull request by foo-dogsquared**
## Description of changes

Basic testing done by using all of the supported providers. All of them are fully working (except I have to use other Lingva Translate instances since the official instance fails for some reason).

- https://github.com/dialect-app/dialect/releases/tag/2.2.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by linsui** [comment]
Do you want to maintain this? I don't use this anymore (I'm using pot instead).

**Comment by foo-dogsquared** [comment]
> Do you want to maintain this? I don't use this anymore (I'm using pot instead).

Sure.

**Comment by aqrln** [comment]
Result of `nixpkgs-review pr 273475` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>dialect</li>
  </ul>
</details>

**Comment by aqrln** [comment]
Builds and runs. Translation fails with the following error for me:
```
ERROR:root:Response has failed: TLS support is not available
```

On the other hand, the version in `master` and `nixos-unstable` doesn't even run at all on either of the two NixOS systems I tried:
```
$ nix run nixpkgs#dialect

(dialect:126985): dconf-WARNING **: 02:48:43.242: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by any .service files

(dialect:126985): dconf-WARNING **: 02:48:43.242: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by any .service files
Traceback (most recent call last):
  File "/nix/store/y9rpsdpqay7w6j3g5bi5sfqk1j4kw6zn-dialect-2.1.1/share/dialect/dialect/main.py", line 54, in do_activate
    self.window = DialectWindow(
                  ^^^^^^^^^^^^^^
  File "/nix/store/y9rpsdpqay7w6j3g5bi5sfqk1j4kw6zn-dialect-2.1.1/share/dialect/dialect/window.py", line 129, in __init__
    self.setup()
  File "/nix/store/y9rpsdpqay7w6j3g5bi5sfqk1j4kw6zn-dialect-2.1.1/share/dialect/dialect/window.py", line 150, in setup
    self.load_translator(True)
  File "/nix/store/y9rpsdpqay7w6j3g5bi5sfqk1j4kw6zn-dialect-2.1.1/share/dialect/dialect/window.py", line 281, in load_translator
    on_loaded(True)  # Assume successful loading.
    ^^^^^^^^^^^^^^^
  File "/nix/store/y9rpsdpqay7w6j3g5bi5sfqk1j4kw6zn-dialect-2.1.1/share/dialect/dialect/window.py", line 251, in on_loaded
    self.dest_lang_selector.set_selected(self.dest_langs[0], notify=False)
                                         ~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Pull request closed without merging**
