### PR TITLE
python39: hardcode path to tzdata

### PR DESCRIPTION
**Pull request by FRidh**
Python 3.9 has a new module `zoneinfo` which requires tzdata. By default
it searches TZPATH for folders containing `zoneinfo`.

This commit makes the dependency on tzdata pure.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

## TODO

- [ ] nuke-refs kills the reference to tzdata. This should not happen

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Locally I get a merge conflict when trying to test this PR.

**Comment by jonringer** [comment]
we may have to do some patching
```
[nix-shell:/home/jon/.cache/nixpkgs-review/pr-103993]$ ./results/python310/bin/python3
Python 3.10.0a4 (default, Jan  4 2021, 17:26:04)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zoneinfo
>>> zoneinfo.ZoneInfo("UTC")
Traceback (most recent call last):
  File "/home/jon/.cache/nixpkgs-review/pr-103993/results/python310/lib/python3.10/zoneinfo/_common.py", line 12, in load_tzdata
    return importlib.resources.open_binary(package_name, resource_name)
  File "/home/jon/.cache/nixpkgs-review/pr-103993/results/python310/lib/python3.10/importlib/resources.py", line 40, in open_binary
    package = _common.get_package(package)
  File "/home/jon/.cache/nixpkgs-review/pr-103993/results/python310/lib/python3.10/importlib/_common.py", line 66, in get_package
    resolved = resolve(package)
  File "/home/jon/.cache/nixpkgs-review/pr-103993/results/python310/lib/python3.10/importlib/_common.py", line 56, in resolve
    else importlib.import_module(cand)
  File "/home/jon/.cache/nixpkgs-review/pr-103993/results/python310/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1049, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1026, in _find_and_load
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1049, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1026, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1003, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tzdata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jon/.cache/nixpkgs-review/pr-103993/results/python310/lib/python3.10/zoneinfo/_common.py", line 24, in load_tzdata
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key UTC'
>>>
```

or this may be an issue with upstream, as this doesn't occur in python3.9

**Comment by FRidh** [comment]
Should pass `-e ${tzdata}` to nuke-refs invocation.

**Comment by FRidh** [comment]
pushed 7617b03403acd7d74f8e4f21ed791543ad14bfe9 to staging

**Pull request closed without merging**
