### PR TITLE
protobuf: 3.15.2 -> 3.15.5

### PR DESCRIPTION
**Pull request by marsam**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I tried building python3Packages.google-cloud-kms because it uses protobuf and it fails with some strange error I couldn't solve 

```
  adding 'google_cloud_kms-2.2.0.dist-info/top_level.txt'
  adding 'google_cloud_kms-2.2.0.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
  Finished executing setuptoolsBuildPhase
  installing
  Executing pipInstallPhase
  /build/google-cloud-kms-2.2.0/dist /build/google-cloud-kms-2.2.0
  Processing ./google_cloud_kms-2.2.0-py2.py3-none-any.whl
  ERROR: Could not find a version that satisfies the requirement libcst>=0.2.5 (from google-cloud-kms)
  ERROR: No matching distribution found for libcst>=0.2.5
builder for '/nix/store/hy4jqw5m3c2jqmavgd2g1y1v17mzfdm4-python3.8-google-cloud-kms-2.2.0.drv' failed with exit code 1
error: build of '/nix/store/hy4jqw5m3c2jqmavgd2g1y1v17mzfdm4-python3.8-google-cloud-kms-2.2.0.drv' failed
```

Probably unrelated to this PR.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 115193` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>gnome3.gnome-terminal</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
gnome3.gnome-terminal:
<details>

warning: EvalError
Cannot evaluate attribute ‘gnome3.gnome-terminal’ in ‘/nix/store/vi05s3qxs8zdh9dx68y2y3a5c4agm86g-nixpkgs’.
</details>
</details>

**Comment by marsam** [comment]
google-cloud-kms fail seems to be unrelated

**Comment by SuperSandro2000** [comment]
> google-cloud-kms fail seems to be unrelated

It is and I fixed it in a separate PR.

**Pull request merged**
