### PR TITLE
libredirect: fix argument forwarding in `open*` functions

### PR DESCRIPTION
**Pull request by demin-dmitriy**
###### Motivation for this change
`libredirect` incorrectly forwards arguments of `open`, `open64` and `openat` functions when `O_TMPFILE` flag is set.

From `man 2 open`:
> The mode argument specifies the file mode bits be applied when a new  file  is  created.   This  argument  must  be supplied when O_CREAT or O_TMPFILE is specified in flags; if  neither  O_CREAT nor O_TMPFILE is specified, then mode is ignored.

This PR solves this issue: https://github.com/NixOS/nixpkgs/issues/73077 .

###### Things done
* Fixed argument forwarding in `open`, `open64`, `openat` functions
* Fixed return type of `access` function

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @Ma27

### CODE REVIEW

**Comment by jtojnar** [comment]
Could you add a testcase for this?

**Review by Ma27 — APPROVED** [review]
Diff seems fine, the issue is fixed in the KDE VM I created to reproduce this. Thanks!

**Comment by demin-dmitriy** [comment]
@jtojnar I'm not sure if I can write a good test that tests that `O_TMPFILE` if working.
The problem is that `O_TMPFILE` is filesystem-dependent.
From `man 2 open`:
> O_TMPFILE requires support by the underlying filesystem; only a subset of Linux filesystems provide that support.  In the initial implementation, support was provided in the ext2, ext3, ext4, UDF, Minix, and shmem filesystems.  Support for other filesystems has subsequently been added as follows: XFS (Linux 3.15); Btrfs (Linux 3.16); F2FS (Linux 3.16); and ubifs (Linux 4.9).

So either there is a guarantee that during test a file within supported filesystem can be created, or test only if we can and silently fail if unsupported filesystem is used. In the later case I wonder if that counts as breaking reproducibility.

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS (failures are broken on master)
diff LGTM

```
[29 built (6 failed), 57 copied (270.3 MiB), 65.2 MiB DL]
error: build of '/nix/store/ibwl6l7pl6prp1c613ldkc2zj9b9g0mr-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/73266
9 package failed to build:
citrix_workspace citrix_workspace_19_3_0 citrix_workspace_19_6_0 citrix_workspace_19_8_0 freeoffice gdbgui python37Packages.flask-socketio python37Packages.python-engineio python37Packages.python-socketio

10 package were build:
libredirect python38Packages.flask-socketio python38Packages.python-engineio python38Packages.python-socketio softmaker-office sublime-merge sublime-merge-dev sublime3 sublime3-dev teamspeak_client
```

didn't do any testing

**Comment by demin-dmitriy** [comment]
@Ma27 Let's merge this? (I don't know if there a reason not to).

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM
commits LGTM

```
[27 built (4 failed), 19 copied (73.3 MiB), 12.4 MiB DL]
error: build of '/nix/store/njfx7kk2smycjy2xfsqpwk2yh3268dd0-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/73266
4 package failed to build:
citrix_workspace citrix_workspace_19_3_0 citrix_workspace_19_6_0 citrix_workspace_19_8_0

15 package were built:
freeoffice gdbgui libredirect python37Packages.flask-socketio python37Packages.python-engineio python37Packages.python-socketio python38Packages.flask-socketio python38Packages.python-engineio python38Packages.python-socketio softmaker-office sublime-merge sublime-merge-dev sublime3 sublime3-dev teamspeak_client
```

**Comment by jonringer** [comment]
@GrahamcOfBorg build libredirect

**Comment by jtojnar** [comment]
I guess we will have to do without test. Thanks.

**Pull request merged**
