### PR TITLE
nodejs_14: is EOL on 2023-04-30, nodejs_16: goes EOL during 23.05 release

### PR DESCRIPTION
**Pull request by ajs124**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by teutat3s — APPROVED** [review]

**Comment by mweinelt** [comment]
I think this warrants some maintainer pings.

**Comment by mweinelt** [comment]
Head's up. Your package is using `nodejs_14`, which we are going to mark vulnerable (because EOL) before the 23.05 branch-off.

- onlykey @kalbasit 
- ldgallery @pacien 
- ntfy-sh @arjan-s 
- botamusique @infinisil 
- airfield @offlinehacker 
- vadmicn.vscode-lldb @superherointj 
- archisteamfarm @legendofmiracles 
- spacegun @kampka 
- matrix-recorder @7c6f434c 
- cz-cli @lovesegfault 
- base16-builder @garbas 
- mjolnir @jojosch 
- psitransfer @hyshka 
- ethercalc @iblech 
- whitebophir @iblech 
- haste-server @mkg20001 
- navidrome @squalus
  - #229953 
- jellyfin @nyanloutre @minijackson @purcell @jojosch 
- mx-puppet-discord @expipiplus1 
- ariang @Stunkymonkey 
- newman @freezeboy 
- elm @turbomack @jonringer

**Comment by turboMaCk** [comment]
thanks for ping. I will take care of node modules.

**Comment by mweinelt** [comment]
We might have to pull nodejs_16 as well, given that it EOLS in 4 months. cc @turboMaCk

**Comment by mweinelt** [comment]
Please migrate away from `nodejs_16` as well, since its lifetime ends during the NixOS 23.05 release.

- n8n @freezeboy @K900 
- bitwarden @amarshall @Kiwi 
- meshcentral @lheckemann 
- plausible @happysalada
- hedgedoc @SuperSandro2000 
- mirakurun @midchildan 
- outline @cab404 @yrd 
- epgstation @midchildan 
- peertube @immae @Izorkin @matthiasbeyer @mohe2015 @stevenroose 
- code-server @offlinehacker @henkery 
- audiobookshelf @jvanbruegge 
- openvscode-server @dguenther @ghuntley @emilytrau 
- discourse @talyz 
- whitebophir @iblech 
- kibana @offlinehacker @basvandijk 
- docker-compose-language-service @natsukium 
- electron-fiddle @andersk 
- github-runner @veehaitch @newAM @kfollesdal @aanderse @zimbatm 
- netlify-cli @roberth 
- wiki-js @Ma27

**Comment by kampka** [comment]
@mweinelt I've stepped away from being a maintainer of nixpkga and I don't feel like picking it up again at the moment. If `spacegun` blocks this issue feel free to remove it.

**Comment by Izorkin** [comment]
Update Peertube - https://github.com/NixOS/nixpkgs/pull/218599

**Comment by K900** [comment]
n8n upstream is on 16, it seems to run OK on 18, but I'm inclined to leave it on 16 for now and upgrade to 18 mid-cycle if necessary - there's _a lot_ of plugins I'm not personally using or testing.

**Comment by expipiplus1** [comment]
I'm no longer able to maintain mx-puppet-discord. Perhaps @GovanifY would care to take over?

**Comment by SuperSandro2000** [comment]
> * hedgedoc @SuperSandro2000

I don't think I have time to look at this, also given that updates to hedgedoc in the past where highly problematic and killed the web editor multiple times due to bugs and oversights in node2nix mixing together prod and dev dependencies.

**Comment by 7c6f434c** [comment]
(I tried to find a matrix-recorder fork updated to the new step in the Node.js treadmill and I have failed)

**Comment by andersk** [comment]
electron-fiddle: #231557

**Comment by Ma27** [comment]
Currently taking a look at wiki.js (because there are apparently no plans for v2 to fix nodejs 18 support and in fact there's a runtime error that can be trivially reproduced with the VM test in nixpkgs). Since I doubt that v3 will come up soonish, I'll try to fix this on my own.

**Comment by GovanifY** [comment]
> I'm no longer able to maintain mx-puppet-discord. Perhaps @GovanifY would care to take over?

Ah sure will take a look whenever I have a moment

**Comment by marsam** [comment]
Since the 23.05 branch-off is happening in the next couple of days, I'm inclined to only mark `nodejs_14` as EOL. 
What do you think?

**Comment by mweinelt** [comment]
We can't support nodejs_16 through NixOS 23.05, so it has to be marked EOL as well, as we cannot really cut support mid-release.

**Comment by RaitoBezarius** [comment]
I am in favor of marking Node.js 14, 16 EOL.

**Comment by marsam** [comment]
yeah, but `nodejs_16` will reach EOL at September 11th, a little over a month before the 23.11 release, so I think it's tolerable to maintain it until then

**Comment by mweinelt** [comment]
We'll support 23.05 until 2023/12/31.

**Pull request merged**
