### PR TITLE
rtv: update from 1.2.2 to 1.4

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Update package.

I also build it and made a quick test by invoking the program and exit from it.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Sorry, something got wrong with the branch name and I had to adjust it.

**Comment by matthiasbeyer** [comment]
Updated. Builds for me, now.

**Comment by geerds** [comment]
I've renamed the commit message to `rtv: 1.2.2 -> 1.4` and pushed it directly into our master. Check out our [new contribution guidelines](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md) :smile:

**Comment by matthiasbeyer** [comment]
:-( This closes the PR as "unmerged".

Anyways: thanks.

**Comment by geerds** [comment]
but [commit author](https://github.com/NixOS/nixpkgs/commit/de76ce46e68c4d0a3d1b52530de6c1ded4b825bd) is still the same ;-)

**Pull request closed without merging**
