### PR TITLE
.github/CODEOWNERS: Add infinisil to NixOS modules

### PR DESCRIPTION
**Pull request by infinisil**
###### Motivation for this change
I'm often involved with NixOS modules and know a lot about them. Would like to help all PR's that change them.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by samueldr** [comment]
*Looks for @Infinisil in the changes*:  0/0 results.

**Comment by 7c6f434c** [comment]
@samueldr What did you look for? 35c069ea02b6a19263cd66c2885f4d8190a7c910 seems to be a relevant non-merge commit, for example.

**Comment by Infinisil** [comment]
Ah yes, some links

These only include ones with the "has: module (update)" label:
- [67 labeled PR's I reviewed](https://github.com/NixOS/nixpkgs/pulls?page=1&q=is%3Apr+sort%3Aupdated-desc+reviewed-by%3AInfinisil+label%3A%228.has%3A+module+%28update%29%22&utf8=%E2%9C%93)
- [16 labeled PR's by me](https://github.com/NixOS/nixpkgs/pulls?utf8=%E2%9C%93&q=is%3Apr+sort%3Aupdated-desc+author%3AInfinisil+label%3A%228.has%3A+module+%28update%29%22+)

My non-trivial NixOS module PR's (manually looked through all my PR's):
- https://github.com/NixOS/nixpkgs/pull/45470
- https://github.com/NixOS/nixpkgs/pull/27826
- https://github.com/NixOS/nixpkgs/pull/32914
- https://github.com/nix-community/NUR/pull/27 (not nixpkgs, but still relevant)
- https://github.com/NixOS/nixpkgs/pull/30518
- https://github.com/NixOS/nixpkgs/pull/25782

I've spent a lot of time diving into the module system internals and know pretty much everything about it too :3.

**Comment by dywedir** [comment]
I think @samueldr meant this:
```diff
+ # NixOS modules
+ /nixos/modules
+ 
```

**Comment by Infinisil** [comment]
Oh haha, whoops, will fix

**Review by timokau — APPROVED** [review]

**Comment by samueldr** [comment]
@7c6f434c just confirming, @dywedir is right, the changes did not initially include infinisil in the `CODEOWNERS` file.

**Review by samueldr — APPROVED** [review]

**Pull request merged**
