### PR TITLE
perlPackage.RPCEPCService: Init at 0.0.11

### PR DESCRIPTION
**Pull request by matthuszagh**
Add the RPCEPCService perl package, and its dependency DataSExpression.

###### Motivation for this change
RPC::EPC::Service is a required dependency of the [edbi](https://github.com/kiwanami/emacs-edbi) Emacs package.

###### Things done
These were autogenerated with `nix-generate-from-cpan`.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by c0bw3b** [comment]
Have you been able to test these locally?
(see the checkboxes of the PR template)

@GrahamcOfBorg build perl528Package.RPCEPCService perl530Package.RPCEPCService perl528Package.DataSExpression perl530Package.DataSExpression

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build perl528Packages.RPCEPCService perl530Packages.RPCEPCService perl528Packages.DataSExpression perl530Packages.DataSExpression

**Comment by matthuszagh** [comment]
I've tested this in a sandboxed environment on NixOS. Checkboxes updated to reflect that.

**Review by c0bw3b — APPROVED** [review]
Result of `nix-review pr 71153` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>4 package were build:</summary>

  - perl528Packages.DataSExpression
  - perl528Packages.RPCEPCService
  - perl530Packages.DataSExpression
  - perl530Packages.RPCEPCService
</details>

**Pull request merged**
