### PR TITLE
[WIP] GNOME: 3.22 -> 3.24

### PR DESCRIPTION
**Pull request by lheckemann**
###### Motivation for this change
Upstream release

I'm PRing it now to show that I'm doing it and avoid any potential duplication of efforts. This definitely isn't ready to be merged (although it does build) and I'm planning to split it out into multiple commits and document some of the odder changes — I made this on a trial-and-error cycle where I probably should have committed on every build so I could construct the history more easily, but I didn't :D help is welcome!

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by 0xABAB** [comment]
I looked at it and it seems pretty boring to me, which is a good thing. 

One way to improve the quality of the release would be to write automated tests that actually use the applications, which is just a suggestion, not something that would have to be part of this. Before this gets committed into an actual future release, I'd like to see independent verification of someone testing whatever Gnome apps they use, to see that it won't break everything.

**Comment by lheckemann** [comment]
Yes, I absolutely agree. In fact, I think most modules should be accompanied by tests, which would avoid issues like #25530 popping up unexpectedly just because nobody's using them.

**Comment by eqyiel** [comment]
Great, thanks!

**Comment by grahamc** [comment]
How is this coming @lheckemann?

**Comment by lheckemann** [comment]
I still haven't got around to testing it, besides checking that it builds. Help welcome!

**Comment by jtojnar** [comment]
I tried the branch and it does not work. Cursor flashes in the middle of the screen for a fraction of the second and then GDM is immediately killed. From journal, it looks like gnome shell requires `librsvg` introspection.

```
Jul 19 13:50:09 kaiser .gnome-shell-wr[1090]: JS ERROR: Error: Requiring Rsvg, version none: Typelib file for namespace 'Rsvg' (any version) not found
                                              @resource:///org/gnome/shell/ui/padOsd.js:8:7
                                              @resource:///org/gnome/shell/ui/windowManager.js:20:7
                                              @resource:///org/gnome/shell/ui/workspace.js:19:7
                                              @resource:///org/gnome/shell/ui/appDisplay.js:26:7
                                              @resource:///org/gnome/shell/ui/dash.js:13:7
                                              @resource:///org/gnome/shell/ui/overviewControls.js:10:7
                                              @resource:///org/gnome/shell/ui/overview.js:20:7
                                              @resource:///org/gnome/shell/ui/legacyTray.js:12:7
                                              @resource:///org/gnome/shell/ui/main.js:23:7
                                              @<main>:1:31
Jul 19 13:50:09 kaiser .gnome-shell-wr[1090]: Execution of main.js threw exception: JS_EvaluateScript() failed
Jul 19 13:50:09 kaiser org.gnome.Shell.desktop[1090]: (EE)
Jul 19 13:50:09 kaiser org.gnome.Shell.desktop[1090]: Fatal server error:
Jul 19 13:50:09 kaiser org.gnome.Shell.desktop[1090]: (EE) failed to read Wayland events: Connection reset by peer
Jul 19 13:50:09 kaiser org.gnome.Shell.desktop[1090]: (EE)
Jul 19 13:50:09 kaiser gnome-session[1085]: gnome-session-binary[1085]: WARNING: App 'org.gnome.Shell.desktop' exited with code 1
Jul 19 13:50:09 kaiser gnome-session-binary[1085]: Unrecoverable failure in required component org.gnome.Shell.desktop
Jul 19 13:50:09 kaiser gnome-session-binary[1085]: WARNING: App 'org.gnome.Shell.desktop' exited with code 1

Jul 19 13:50:10 kaiser systemd-logind[967]: Removed session c3.
-- Subject: Session c3 has been terminated
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: https://www.freedesktop.org/wiki/Software/systemd/multiseat
-- 
-- A session with the ID c3 has been terminated.
Jul 19 13:50:10 kaiser systemd[1]: Stopping User Manager for UID 132...
-- Subject: Unit user@132.service has begun shutting down
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit user@132.service has begun shutting down.
Jul 19 13:50:10 kaiser systemd[1074]: Stopped target Default.
-- Subject: Unit UNIT has finished shutting down
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit UNIT has finished shutting down.
Jul 19 13:50:10 kaiser systemd[1074]: Stopping D-Bus User Message Bus...
-- Subject: Unit UNIT has begun shutting down
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit UNIT has begun shutting down.
Jul 19 13:50:10 kaiser gdm[978]: Child process -1082 was already dead.
Jul 19 13:50:10 kaiser gdm[978]: Child process 1070 was already dead.
Jul 19 13:50:10 kaiser gdm[978]: Unable to kill session worker process
```

**Comment by domenkozar** [comment]
cc @lethalman

**Comment by eqyiel** [comment]
What's the best way to test this?

I've tried the following:

```
$ git remote add lheckemann git@github.com:lheckemann/nixpkgs.git
$ git fetch lheckermann && git checkout lheckemann/gnome-3.24
$ sudo nixos-rebuild build -I nixpkgs=.
```

which fails due to unrelated problems with `rustc`, and

```
$ nix-build -A pkgs.gnome3_24 -I nixpkgs=.
```

with

```
$ cat ~/.nixpkgs/config.nix
{
  allowBroken = true;
  permittedInsecurePackages = [
    "webkitgtk-2.4.11"
  ];
}
```

which fails with:

```
checking for a BSD-compatible install... /nix/store/c6hdfpvm1mamgks4x4h7z0fnihi9rn0i-coreutils-8.27/bin/install -c
checking whether build environment is sane... /nix/store/yhf350xdzv68rz52fpx0kc19y5f552s5-binutils-2.28/bin/ld: cannot find -lcrack
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:665: frob-account-dialog] Error 1
make[5]: Leaving directory '/tmp/nix-build-gnome-control-center-3.24.2.drv-0/gnome-control-center-3.24.2/panels/user-accounts'
make[4]: *** [Makefile:854: all-recursive] Error 1
make[4]: Leaving directory '/tmp/nix-build-gnome-control-center-3.24.2.drv-0/gnome-control-center-3.24.2/panels/user-accounts'
make[3]: *** [Makefile:606: all] Error 2
make[3]: Leaving directory '/tmp/nix-build-gnome-control-center-3.24.2.drv-0/gnome-control-center-3.24.2/panels/user-accounts'
make[2]: *** [Makefile:473: all-recursive] Error 1
make[2]: Leaving directory '/tmp/nix-build-gnome-control-center-3.24.2.drv-0/gnome-control-center-3.24.2/panels'
make[1]: *** [Makefile:537: all-recursive] Error 1
make[1]: Leaving directory '/tmp/nix-build-gnome-control-center-3.24.2.drv-0/gnome-control-center-3.24.2'
make: *** [Makefile:469: all] Error 2
builder for ‘/nix/store/h58ifcl82qxj5qr2m8d3il6c6gpdgr69-gnome-control-center-3.24.2.drv’ failed with exit code 2
error: build of ‘/nix/store/h58ifcl82qxj5qr2m8d3il6c6gpdgr69-gnome-control-center-3.24.2.drv’ failed
```

**Comment by lheckemann** [comment]
Sorry, I've been pretty busy — I don't know why it's not building, I think it worked for me. In any case, I won't have time to look at it again in the next 2 weeks or so so unless someone wants to take this over it'll be on hold for a while.

**Comment by teh** [comment]
I rebased against master and can confirm that this branch still builds.

**Comment by teh** [comment]
For this branch GDM no longer starts with the following messages in `sudo journalctl -f -u display-manager.service  -n 2000`:


```Aug 08 22:15:53 nixos systemd[1]: Stopped X11 Server.
Aug 08 22:15:53 nixos systemd[1]: Starting X11 Server...
Aug 08 22:15:53 nixos systemd[1]: Started X11 Server.
Aug 08 22:15:53 nixos gdm[6708]: GdmDisplay: display lasted 0.505423 seconds
Aug 08 22:15:53 nixos gdm[6708]: Child process -6717 was already dead.
Aug 08 22:15:53 nixos gdm[6708]: Child process 6713 was already dead.
Aug 08 22:15:53 nixos gdm[6708]: Unable to kill session worker process
Aug 08 22:15:54 nixos gdm[6708]: Child process -6734 was already dead.
Aug 08 22:15:54 nixos gdm[6708]: Child process 6730 was already dead.
Aug 08 22:15:54 nixos gdm[6708]: Unable to kill session worker process
Aug 08 22:15:54 nixos gdm[6708]: GdmDisplay: display lasted 0.629898 seconds
```

**Comment by lheckemann** [comment]
Hi all, sorry I've kind of dropped the ball on this one.

I don't think I'll manage to get it properly sorted out, nor would I be any good at maintaining it (which I feel I should do if I'm going to do this upgrade), as I'm not a GNOME user myself and as such won't actually be using the majority of the software this affects.

If someone does want to take over please feel free to take inspiration from this PR and ask me any questions you might have about the changes I made here.

**Comment by teh** [comment]
Thanks @lheckemann! Biggest question I have is that I see a number of packages that just moved without an update (like GDM).  Assuming this was intentional how did you choose the packages you didn't update?

**Comment by lheckemann** [comment]
I ran the `maintainers/scripts/gnome.sh` script with `update-all` and let it do its magic without questioning it much. Perhaps it missed gdm and it needs to be updated and that will fix the crash you're experiencing.

**Comment by jtojnar** [comment]
I rebased the PR and added some more fixes and updates: https://github.com/jtojnar/nixpkgs/tree/gnome3.24

The rsvg issue is not solved yet.

Currently rebuilding stupid webkit.

**Comment by teh** [comment]
@jtojnar nice! I fixed the rsvg issue and some others but now running into segfaults :/

See https://github.com/NixOS/nixpkgs/pull/28053

**Comment by teh** [comment]
Another thing that's  bit annoying is that the `switch` moves my system into a state where GDM doesn't restart, but I can't get to a tty either, leaving reboot as the only option. I'm trying to figure out how other distributions deal with this but no luck so far.

**Comment by jtojnar** [comment]
Yes, I have also come across that one, extremely annoying.

Feel free to cherry pick my changes.

**Comment by teh** [comment]
Fixed the segfault which was self-inflicted. Writing this from 

```
$ gnome-shell --version
GNOME Shell 3.24.2
```

but with a number of issues. E.g. all extensions broke, and a number of configuration options aren't being picked up (static work spaces e.g.)

**Comment by teh** [comment]
I suspect the culprit is this but not sure what causes it:

```
Aug 09 00:30:12 nixos gsettings[1555]: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
```

**Comment by jtojnar** [comment]
That is probably #26113, it is not in `nixpkgs-unstable` yet. My patch also relies on #27320 which also did not reach `unstable` yet.

**Comment by 7c6f434c** [comment]
re: stuck-at-X: did you try `Alt-SysRq-R Alt-F2` (`SysRq` is also known as `PrtSc`/`PrintScreen`). Although systemd may disable `Alt-SysRq` kernel handling by default. Magic `SysRq` is a kernel mechanism to call some low-level commands, like reset keyboard to a mode where TTY switch works, force a storage sync, etc. If it is disabled, it can still be enabled via `sysctl` most of the time (NixPkgs kernel definitely comes with support for Magic `SysRq`, I use it — but I am not running precisely NixOS, so may be it is off-by-default after some update).

(I do not use or plan to use Gnome — just noticed a mention of a generic problem)

**Comment by lheckemann** [comment]
Also re the issue of switching to a tty — were you by any chance trying to switch to tty1? Because IIRC gdm actually runs on tty1.

**Pull request closed without merging**
