### PR TITLE
Preview: deterministic build

### PR DESCRIPTION
**Pull request by alexanderkjeldaas**
This is a set of changes that makes the system_tarball_pc derivation deterministic.

Stdenv bootstrap:
- The stdenvs created during bootstrap are numbered to make it easier to debug/understand
- BUG:  for the bootstrap stdenvs, binutils was after the bootstrap binaries in path.
- Deterministic archives are enabled early during bootstrapping of stdenvs.

Stdenv builder:
- The generic builder depends on libfaketime. _libfaketime needs a home_.  libfaketime is currently distributed through github, that that does not work during bootstrap when SSL is not available.  It should be moved to tarballs.nixos.org.
- Feature: Setting useFakeTime fixes the time during builds.  This can break builds, but is easy to manage compared to patching.  Additional environment variables are available for configuring libfaketime.
- Feature: A fake "date" utility is prepended to the path
- Check:  The build directory (/tmp/nix-build-foo-x.y.z) is not allowed to appear in artifacts ($out) to avoid non-deterministic output.

Gcc:
- Gcc by default now defines **DATE** and **TIME** to be (time_t)0.
- TODO: -frandom-seed is not set.  This is relevant for c++ code.
- PGO is turned off for gcc. _Note:_ there is no consensus on doing this as it reduces compilation performance.

Various changes:
- The xsltproc utility creates random identifiers.  A post-processing stage using perl was added to the nixos manual.  This could be generalized.
- All uses of 'gzip -9' has been replaced with 'gzip -9n'.
- Added options to cpio for default uid/gid, and default mtime for tar.
- File lists are sorted before being added to cpio/tar.

### CODE REVIEW

**Comment by alexanderkjeldaas** [comment]
Since this is discussed on the dev list, @vcunat you are doing a great job on this, but I wonder if we could get a list of the current pain points.

When I did the initial set of changes, I believed i was pretty close to a deterministic system stdenv, so I feel that we should be able to get there if we just get the latest issues fleshed out.  If there was a list of things that still needs to be fixed, I might be able to block out some time to take a crack at it.

Is there a particular set of issues that are currently hard to fix?

**Comment by vcunat** [comment]
I wanted to start with stdenv and I stuck with perl. There the configure phase collects many things, and I still haven't caught all (some needed me to use two different build machines and kernels to detect them). My WIP on determinism is on https://github.com/vcunat/nixpkgs/commits/v/determ, re-based on some staging version.

**Comment by vcunat** [comment]
Maybe it would be worth it to patch the ``uname`` utility available through stdenv in general (and similar other impurity sources).

**Comment by wmertens** [comment]
Perhaps `proot` could be used (Linux only of course) to intercept the
syscalls and provide deterministic `uname`, system time etc. PID would be
tough to do deterministically.

**Comment by alexanderkjeldaas** [comment]
`uname` should be mostly deterministic since the kernel timestamp is deterministic.  The hostname might not be deterministic though.  I think PID could be made deterministic if the build system moves towards using one container per build.  This also makes it possible to make the hostname deterministic by using the UTS namespace.

`proot` sounds like a good idea, but I haven't seen too many path problems in these patches. I don't see any documentation for proot indicating that it provides hostname, system-time and more. We have the libfaketime which is supposed to set the time to a fixed value, which is a similar low-level approach.

**Comment by alexanderkjeldaas** [comment]
@vcunat thanks for the link! I think just having determinism on a single machine is a great first step.  If we can get that for stdenv mainlined, that would be great.

**Comment by vcunat** [comment]
``uname`` shows e.g. the kernel version of the build machine.

**Comment by wmertens** [comment]
yes, but that could be exposed as a dependency. If you need the kernel
version, it becomes an input, otherwise you get e.g. 3.1415 or something
greppable.

**Comment by copumpkin** [comment]
> Maybe it would be worth it to patch the uname utility available through stdenv in general (and similar other impurity sources).

:+1:

**Comment by offlinehacker** [comment]
I tried building system_tarball_pc with this branch and didn't get deterministic results of tarball, any idea how to reproduce this. Do you have some script that checks which store paths are non deterministic for closure?

**Comment by alexanderkjeldaas** [comment]
I think the thread on this issue shows that there are still issues with
getting deterministic builds.  The newer versions of nix makes it possible
to rebuild a single derivation, so it shouldn't be too hard to check for
determinism.  I don' t have the command handy.

**Comment by iElectric** [comment]
http://www.cjmweb.net/vbindiff/

**Comment by lethalman** [comment]
@offlinehacker if I'm not mistaken the tarball is affected by the files in the working dir (e.g. the result symlink itself).

**Comment by offlinehacker** [comment]
Me and @matejc were working on a tool that would rebuild all the packages and check if hashes get changed, will continue when i will have more time.

**Comment by lethalman** [comment]
@offlinehacker you are aware of `nix-build --check` ?

**Comment by copumpkin** [comment]
Any progress on this?

**Comment by vcunat** [comment]
Not on my side (apart from what I've already posted/linked here).

**Comment by copumpkin** [comment]
Can we merge a smaller part of this, @alexanderkjeldaas? It would be a pity for this work to rot. If not, can someone enumerate what's preventing this from being merged?

**Comment by bjornfor** [comment]
What's the status of this PR? (I don't know if/how I can help, but I'm definitely interested in deterministic builds.)

**Comment by vcunat** [comment]
I cherry-picked some of the commits (long ago). Some packages remained non-deterministic when I tested them so it wasn't clear to me whether the extra complexity was worth it.

**Comment by Mathnerd314** [comment]
I rebased the patches: https://github.com/NixOS/nixpkgs/compare/master...Mathnerd314:deterministic-patches?expand=1

Skipped:
* These looked like they were random untested changes:
    * python 2.7.7 updates to deterministic builds. 
    * Make python 2.7 deterministic.
    * Make syslinux deterministic.
    * Disable useFakeTime for smartmontools.
    * Set useFakeTime on a set of derivations.
    * Make smartmontools deterministic.
    * Add useFakeTime for python, groff, kernel.
    * perl-modules: Do not create perllocal.pod, for determinism.
    * Set the linux kernel timestamp properly.
* Not patching elf binaries result in non-deterministic builds.
    * This seemed like it could just be a separate PR
* Change some fixed timestamp to != (time_t)0
    * unclear why these are needed, I did miss [a line](https://github.com/NixOS/nixpkgs/compare/master...Mathnerd314:deterministic-patches?expand=1#diff-d7a2c5af155053e8777a9719c870507fL102) though
* Add a fake date utility together with setup.
    * I think just adding a date thing to buildInputs should work
* Remove dates from kernel 3.10.35
    * Ancient kernel, I don't care about it
* Add atomic-ops package.
    * already packaged
* Use real address for __DATE__ and __TIME__.
    * this went to gcc_wrapper_old; I think current gcc wrapper patches these just fine
* these should be fixed by just using a fake date utility:
    * Make openssl deterministic. 
    * Improve determinism for libgcrypt, libgpg-error, and busybox.
    * Make perl 5.16 binary deterministic.
    * Fix date in version string.

**Comment by domenkozar** [comment]
@Mathnerd314 let's open a PR and merge those?

**Comment by copumpkin** [comment]
@Mathnerd314 @domenkozar did you end up creating that PR?

**Comment by copumpkin** [comment]
> Gcc by default now defines DATE and TIME to be (time_t)0.

I think @edolstra just recently changed this behavior in some builds which might conflict with this.

**Comment by copumpkin** [comment]
https://github.com/NixOS/nixpkgs/commit/81e530a7499e3f06bec13b6ec974d0f1e3a4ab84 is the commit I'm talking about.

**Comment by jagajaga** [comment]
Ping all.

**Comment by siddharthist** [comment]
@Mathnerd314 Are you still planning to open that PR?

**Comment by spacekitteh** [comment]
@grahamc tag as security

**Comment by joachifm** [comment]
Note that https://github.com/NixOS/nixpkgs/pull/2281/commits/3157dbe3ac4de70873529c294e4d5c13cc906a95 is probably no longer required due to https://github.com/tytso/e2fsprogs/commit/a2143b51605931db28ba3d5f18f06a73c265287b

**Comment by joachifm** [comment]
I've experimented with patching `gzip -9 -> gzip -9n`, but it doesn't seem to matter (to `nix-build --check`, anyway). Could this be because we now fix timestamps after unpacking sources? Or are there still reasons for doing it, even with `SOURCE_DATE_EPOCH`?

**Comment by joachifm** [comment]
Hm, I guess `gzip -n` still makes sense if the thing being compressed was created as part of the build.

**Comment by joachifm** [comment]
I've been going through most of these.  A brief summary so far:

I think the following are obsolete
- smartmontools passes `nix-build --check` & the string that is patched out
  in https://github.com/NixOS/nixpkgs/pull/2281/commits/fd1101ab949606f1c2b808432aa15329200321ab
 no longer occurs in the source.
- glibc currently contains a patch that removes datetime from nscd
- the openldap patch is no longer relevant, I think, the build no longer skips
  elf patching & the build passes `--check`
- groff and opensp pass `--check` on my end
- the improvement to the linux stdenv are at least partially covered (strip is called with --deterministic-archives)

The following need more work
- syslinux fails `--check`, but the patch in this PR is insufficient
- as reported previously, the manual is still indeterministic

I've not looked at libgpg-error, busybox, python, perl, or the gcc stuff, nor the general libfaketime support.

**Comment by joachifm** [comment]
Regarding the manual, https://wiki.debian.org/ReproducibleBuilds/ExperimentalToolchain#libxslt indicates that the issue of random ids is fixed/worked on upstream, so perhaps we want to just skip that for now.

**Comment by cleverca22** [comment]
something that help help to stress-test determinism, http://manpages.ubuntu.com/manpages/xenial/man1/disorderfs.1.html

this is a fuse filesystem that randomizes the order of files in a directory, so you cant accidentally rely on the fs doing that most of the time

**Comment by joachifm** [comment]
Some of the perl stuff was lost when perl16 was removed, but otherwise it seems like @vcunat (or whomever) picked up most of the specific package fixes. I *think* we're left with gcc, faketime in stdenv, stdenv numbering, and the fake date command thing, all of which seem like they could be profitably dealt with on their own.

**Comment by vcunat** [comment]
IIRC I had tried hard to pick whatever I could verify/make clearly advantegous. For some issues (like PGO) I didn't succeed in a reasonable amount of time so left them behind.

**Comment by cbarrett** [comment]
FYI this PR is being linked to from https://reproducible-builds.org/who/. I volunteer to ping whoever's necessary to get an update posted (don't have the knowledge for more, unfortunately).

**Comment by Ekleog** [comment]
(triage) My reading of the comments in this thread is that most of the changes either have been merged or are no longer needed. The remaining changes that would require being split out to separate PRs would be:
 * [GCC stuff](https://github.com/NixOS/nixpkgs/pull/2281/files#diff-6a1aa6c7a7b76c90dd9b53dfe53ace94)
 * [Faking the time in stdenv](https://github.com/NixOS/nixpkgs/pull/2281/files#diff-7a1764865f30c6cb4c22c2654ebe9a38)
 * [Numbering the names of stdenv](https://github.com/NixOS/nixpkgs/pull/2281/files#diff-d7222640d82ff920625e9311d05a0137)
 * [Fake date command in stdenv](https://github.com/NixOS/nixpkgs/pull/2281/files#diff-96219afccbe3b5e41550ab810c16b025)

Does that sound correct to those actually involved?

**Comment by rht** [comment]
The fake date command is no longer necessary, where faketime by itself is sufficient, so I suppose the remaining points are 1. numbering the names of stdenv, and 2. using faketime in stdenv.

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by worldofpeace** [comment]
This is not actionable in its current state. Please open issues with references to the changes within this PR if needed.

**Comment by davidak** [comment]
There is a GitHub project for this topic: https://github.com/NixOS/nixpkgs/projects/10

@worldofpeace can you add this and every related issue (even closed) to it?

Then https://reproducible-builds.org/who/ can link to that.

The current status is visible on https://r13y.com/ (at least for nixos-unstable's iso_minimal).

**Comment by vcunat** [comment]
Perhaps it might make more sense to have one ticket for each (important) irreproducible package? (or "unreproducible"? whatever)  At least for those that someone started to investigate and didn't immediately manage to fix it completely.

**Comment by worldofpeace** [comment]
Sure, it makes sense to have issues in the tracker for this purpose. Though I'm not sure if I'll have the time to distill them from this thread. @vcunat that is an important point for those who did take time to investigate that

**Pull request closed without merging**
