### PR TITLE
Plasma closure size

### PR DESCRIPTION
**Pull request by ttuegel**
This is the first step in reducing Plasma's closure size. The main feature is a new technique of wrapping KDE applications. Although the closure is still quite large, this achieves up to a 50% reduction in some cases.

### CODE REVIEW

**Comment by ttuegel** [comment]
The Travis failure is a hash mismatch in an unrelated package.

**Comment by peterhoeg** [comment]
@ttuegel I'm getting thousands of file collisions with this PR. All related to icons:
```
collision between `/nix/store/mv2v338sqzzrkfnxnqj6d7b68qsmamf3-kcalc-16.04.3/share/icons/breeze/actions/16/dialog-tile-clones.svg' and `/nix/store/z84piy2h4n2b4sq00719kr0dcykiglrb-gwenview-16.04.3/share/icons/breeze/actions/16/dialog-tile-clones.svg'
collision between `/nix/store/mv2v338sqzzrkfnxnqj6d7b68qsmamf3-kcalc-16.04.3/share/icons/breeze/actions/16/dialog-transform.svg' and `/nix/store/z84piy2h4n2b4sq00719kr0dcykiglrb-gwenview-16.04.3/share/icons/breeze/actions/16/dialog-transform.svg'
collision between `/nix/store/mv2v338sqzzrkfnxnqj6d7b68qsmamf3-kcalc-16.04.3/share/icons/breeze/actions/16/dialog-xml-editor.svg' and `/nix/store/z84piy2h4n2b4sq00719kr0dcykiglrb-gwenview-16.04.3/share/icons/breeze/actions/16/dialog-xml-editor.svg'
collision between `/nix/store/mv2v338sqzzrkfnxnqj6d7b68qsmamf3-kcalc-16.04.3/share/icons/breeze/actions/16/dirsync.svg' and `/nix/store/z84piy2h4n2b4sq00719kr0dcykiglrb-gwenview-16.04.3/share/icons/breeze/actions/16/dirsync.svg'
collision between `/nix/store/mv2v338sqzzrkfnxnqj6d7b68qsmamf3-kcalc-16.04.3/share/icons/breeze/actions/16/distribute-horizontal-baseline.svg' and `/nix/store/z84piy2h4n2b4sq00719kr0dcykiglrb-gwenview-16.04.3/share/icons/breeze/actions/16/distribute-horizontal-baseline.svg'
collision between `/nix/store/mv2v338sqzzrkfnxnqj6d7b68qsmamf3-kcalc-16.04.3/share/icons/breeze/actions/16/distribute-horizontal-center.svg' and `/nix/store/z84piy2h4n2b4sq00719kr0dcykiglrb-gwenview-16.04.3/share/icons/breeze/actions/16/distribute-horizontal-center.svg'
```

**Comment by FRidh** [comment]
I also just noticed huge amounts of collisions like @peterhoeg

**Comment by ttuegel** [comment]
Those collisions are harmless because those are links to identical files, but I will fix them in an upcoming PR.

**Comment by ttuegel** [comment]
> Those collisions are harmless because those are links to identical files, but I will fix them in an upcoming PR.

The excessive collisions are fixed in the branch I merged at 9a295516367eab1505e758ada2f9b1d080c44533.

**Pull request merged**
