### PR TITLE
nixVersions.nix_2_{10..17}: remove

### PR DESCRIPTION
**Pull request by Ma27**
## Description of changes

Those are not maintained anymore by upstream Nix[1]. In fact, Nix intends to only maintain

> * The latest release
> * The version used in the stable NixOS release, which is announced in the NixOS release notes.

Given that security issues and regressions happen, for instance latest 2.17 unconditionally rejects leading dots in store-paths, a regression fixed in other Nix versions[2].

The only package having a problem is `nix-web` which cannot be upgraded to 2.18 since the JSON representation of `nix derivation show` has changed[3]. Upstream seems to be aware of the problem, hence marking the package as broken until there's a new release.

I didn't touch

* 2.3 since there's still a rather large user-base and it has a special role as the last pre-flakes release.

* 2.19 - 2.22: I'm not really sure what the next stable nix for nixpkgs will be and at least 2.19 seems to work relatively well for me. Anyways, touching those seems way more controversial than touching 2.10-2.17, so I'll skip that for now.

[1] https://nixos.org/manual/nix/stable/release-notes/
[2] https://github.com/NixOS/nix/issues/10497
[3] https://codeberg.org/gorgon/gorgon/commit/7b700904e1230b9ac89ce5a1285ed2418733f96c

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc @RaitoBezarius @Artturin 
cc @liclac for nix-web

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Ma27** [comment]
@Infinisil is it not possible to mark a package in by-name as broken?

**Comment by Ma27** [comment]
> 2.19 - 2.22: I'm not really sure what the next stable nix for nixpkgs will be and at least 2.19 seems to work relatively well for me. Anyways, touching those seems way more controversial than touching 2.10-2.17, so I'll skip that for now.

OTOH given that these are effectively dead, fixes will only land on master, i.e. new releases.
I'm not sure what to do here, opinions?

For now I think I'd prefer to leave the scope of that PR as-is since that change seems to be the most obvious one (to me at least).

**Comment by infinisil** [comment]
> @infinisil is it not possible to mark a package in by-name as broken?

Should be no problem. If you're wondering because of the eval error, that is not specific to `pkgs/by-name`, ofborg also fails

**Comment by Ma27** [comment]
Oh crap how embarrassing, sorry for the noise!

**Review by trofi — APPROVED** [review]

**Comment by liclac** [comment]
Ah, I was hoping to be able to transition nix-web away from relying on the CLI before this happened, but I'll put out a hotfix to update to the Nix 2.19+ format later today.

**Comment by liclac** [comment]
#307044

**Pull request merged**
