### PR TITLE
tests.writers: give all test derivations unique names

### PR DESCRIPTION
**Pull request by sternenseemann**
This makes it easier to debug test failures since the derivation name
will give an indication which writer it belongs to.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
@ofborg build tests.writers

**Comment by sternenseemann** [comment]
@ofborg build tests.writers

**Review by Profpatsch — APPROVED** [review]
Looks like an easy enough improvement to me.

Why use `_` everywhere in the names instead of `-` like everywhere else in nixpkgs?

**Review by Lassulus — APPROVED** [review]

**Comment by sternenseemann** [comment]
> Why use _ everywhere in the names instead of - like everywhere else in nixpkgs?

Could point though, fixed all that in a second commit.

**Comment by sternenseemann** [comment]
@ofborg build tests.writers

**Pull request merged**
