### PR TITLE
bloop: 1.2.5 -> 1.3.2

### PR DESCRIPTION
**Pull request by Tomahna**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mmahut** [comment]
I'm trying to test this, however, even with the server running I get:

```
$ ./blp-client 
Command not found: blp-client
```

Is this expected?

**Comment by Tomahna** [comment]
The correct command binary for the client is ./bloop the blp-client is the unwrapped version. Maybe it should not be in the bin directory. I do not know if there are any best practices around this.

**Comment by karolchmist** [comment]
I tried to update it on my side as well, and I have obtained some different sha values... 

For example, to get the `nailgunCommit`, I got `7dfdad8c` from https://github.com/scalacenter/bloop/releases/download/v1.3.0/install.py

Maybe it has changed since?

The sha256 for `client` should change as well, I get `0bchc59dmdxqg5vpdsnhagw0374jr19xg4l5rydcp5ljvv2dp6d4`. 

For `zshCompletion`, I get `09qq5888vaqlqan2jbs2qajz2c3ff13zj8r0x2pcxsqmvlqr02hp`.

Caveat: I'm not very advanced in Nix, so may I miss something... 

PS. Thank you @Tomahna for adding bloop, very useful!

**Comment by Tomahna** [comment]
Thank you for testing this ! Yes you're perfectly right. As I did not change the sha256, it used the value in my cache so it worked for me, but of course not for you.

It should be fixed.

**Comment by Tomahna** [comment]
I've made a few changes. That should prevent both problems from happening again.

As the client has its own derivation it will not appear in the bin directory of the final derivation (only the wrapper will appear), so it should avoid the confusion.

As both the client and the zsh completion have their own derivation, they will have to be rebuilt on version changes and the cache should not be hit.

Please let me know, if there is a better/simpler way to do this.

**Comment by svalaskevicius** [comment]
```
bloop server                                                                                                                             Sun 23 Jun 2019 15:34:42 BST

Defaulting on nailgun port 8212
There is no server running at port 8212
Starting the bloop server... this may take a few seconds
Bloop server could not be located in /nix/store/blp-server.
Pass in the location with `--server-location` before the `server` command.
```

**Comment by svalaskevicius** [comment]
```
 > bloop about
bloop v1.3.2

Using Scala v2.12.8 and Zinc v1.3.0-M4+22-4704d479
Running on Java v1.8.0_212 (/nix/store/i9kl79ch4id866b3xvi3rwr963a4cz9h-openjdk-8u212-ga-jre/lib/openjdk/jre)                                                                
Maintained by the Scala Center (Martin Duhem, Jorge Vicente Cantero)
```

however:
```
 > bloop
Command not found: wfid76hlhxc91nk3j37a4sivkbvcg942-bloop-client-9327a60a
```

**Comment by Tomahna** [comment]
If you want to launch the server from the cli you have to pass the location manually, I'm not sure how to fix that and I honestly don't intend to try as I do not use it this way. However you can use the systemd service with services.bloop.install = true or just run the command blp-server.

For the second part, right now I don't know what causes it. It's not really a blocker because running the cli without a command is not really the way you want to use bloop anyway but it is definitely annoying.

**Comment by svalaskevicius** [comment]
Agreed. Plus I'm not sure how it worked before the upgrade and as both are nonblockers for usage, I'd prefer the new even if somewhat quirky bloop vs nice old one even if these are new issues :)

**Comment by Tomahna** [comment]
I checked the old version, it behaves the same. I'd need to check on a non-nix machine to see how it is actually supposed to behave.

**Comment by Tomahna** [comment]
@FRidh maybe we can remove the work-in-progress tag ?

**Comment by svalaskevicius** [comment]
btw. I've been using this PR in my manually ported nixpkgs for a while now - not quite sure who could merge it would be great if anyone did before we need to update it again :)

(I've only tested bloop itself, not zsh completions)

**Comment by Tomahna** [comment]
I would like that too.

**Comment by Tomahna** [comment]
So I've made a few changes to get closer to the way bloop is packaged on other distributions.

This fix a few problems:
- ```bloop server``` should work transparently 
- it is possible to add java options the way bloop expects them ```bloop server -J-Xmx2G```

**Comment by svalaskevicius** [comment]
just had a chance to test it (except systemd config, as I use my own setup for systemd user unit) - seems like I'm able to pass options to bloop server w/o any issues now :)

**Comment by svalaskevicius** [comment]
Yay! My local nixpkg can now just point to  the master :) thanks!

**Pull request merged**
