### PR TITLE
matrix-synapse: 1.5.1 -> 1.6.1

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

https://github.com/matrix-org/synapse/releases/tag/v1.6.0
https://github.com/matrix-org/synapse/releases/tag/v1.6.1

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by Ralith — APPROVED** [review]

**Comment by pacien** [comment]
@ofborg test matrix-synapse

**Review by pacien — APPROVED** [review]

**Review by Ekleog — APPROVED** [review]

**Review by fadenb — APPROVED** [review]

**Comment by Ma27** [comment]
Marking as `[WIP]` for now. There's a version 1.6.1 now (https://github.com/matrix-org/synapse/releases/tag/v1.6.1), will do the update later today :)

**Comment by pacien** [comment]
And because 1.6.1 is a security update, it should qualify for a backport to release-19.09.

**Comment by pacien** [comment]
@ofborg test matrix-synapse

**Review by pacien — APPROVED** [review]

**Review by Ekleog — APPROVED** [review]

**Review by fadenb — APPROVED** [review]

**Comment by Ma27** [comment]
Backported as 46c4afa674b8892fa4b9173f60fe730110504aea.

**Pull request merged**
