### PR TITLE
fd: 8.7.0 -> 8.7.1

### PR DESCRIPTION
**Pull request by cafkafk**
## Description of changes
Changelog: https://github.com/sharkdp/fd/releases/tag/v8.7.1

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Gerg-L — COMMENTED** [review]
Result of `nixpkgs-review pr 262467` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>fd</li>
    <li>fishPlugins.fzf-fish</li>
    <li>pop-launcher</li>
    <li>yazi</li>
  </ul>
</details>

**Comment by Gerg-L** [comment]
```
fd> ---- test_exec_invalid_utf8 stdout ----
fd> thread 'test_exec_invalid_utf8' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 84, kind: Uncategorized, message: "Invalid or incomplete multibyte or wide character" }', tests/tests.rs:2415:6
fd> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fd>
fd> ---- test_invalid_utf8 stdout ----
fd> thread 'test_invalid_utf8' panicked at 'called `Result::unwrap()` on an `Err`
value: Os { code: 84, kind: Uncategorized, message: "Invalid or incomplete multibyte or wide character" }', tests/tests.rs:2086:6
fd>
```

**Comment by 0x4A6F** [comment]
Result of `nixpkgs-review pr 262467` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>fd</li>
    <li>fishPlugins.fzf-fish</li>
    <li>pop-launcher</li>
    <li>yazi</li>
  </ul>
</details>

**Review by 0x4A6F — APPROVED** [review]

**Review by figsoda — APPROVED** [review]

**Comment by Gerg-L** [comment]
I for some reason can not get this to build on my system

**Comment by figsoda** [comment]
Looking at your error message, looks like it could have something to do with language settings due to some impurities in the tests. But since ofborg is able to build it, hydra should be able to cache it and you would be able to use the cached version

**Pull request merged**
