### PR TITLE
[20.09] Plasma 5: Revert to Qt 5.12

### PR DESCRIPTION
**Pull request by ttuegel**
###### Motivation for this change

Plasma 5.18 only officially supports Qt 5.12.

I don't know what the procedure is for merging `release-20.09` into `staging-20.09`, but I guess somebody needs to fast-forward the latter branch so I can rebase onto it with the latest changes from `release-20.09`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
> I don't know what the procedure is for merging release-20.09 into staging-20.09, but I guess somebody needs to fast-forward the latter branch so I can rebase onto it with the latest changes from release-20.09.

I merged `--no-ff` release-20.09 into staging-20.09 :+1:

**Comment by est31** [comment]
Qt 5.13 is supported as well, and it would fix some failing builds like akonadi or digikam (#98879) and might help with  #98536 too.

**Comment by est31** [comment]
Check the table here, it lists 5.12 and 5.13: https://community.kde.org/Schedules/Plasma_5#Support_status_by_Release_Series

**Comment by ttuegel** [comment]
Qt 5.13 is not an LTS release and we are outside its support window. The affected packages will be supported by upgrading to Qt 5.15.

**Pull request merged**
