### PR TITLE
dasel: 1.2.0 -> 1.5.0

### PR DESCRIPTION
**Pull request by foo-dogsquared**
###### Motivation for this change
Seems like the software is moving quickly so I updated it to catch up.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by 0x4A6F — APPROVED** [review]
Builds and runs.
Thanks for stepping up as maintainer.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 103219` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>dasel</li>
  </ul>
</details>

**Comment by foo-dogsquared** [comment]
Apologies for the noob questions as this is the first time I've contributed to nixpkgs. 

- How do I resolve the above error? Skimming from the build log, it seems it's an error from building Git.
- Can I update the PR into a newer version while it is still unresolved? Case in point, the package [has been updated](https://github.com/TomWright/dasel/releases/tag/v1.5.0) at the time of this comment.

**Comment by 0x4A6F** [comment]
- Ping a person with access to this arch (x86_64-darwin): @SuperSandro2000 can you further debug this build for x86_64-darwin?
- Yes, you can update the package in this pull request. just squash the commits and update the message and title.
1.4.1 and 1.5.0 builds and runs on my local branch. If this is a problem with dasel on x86_64-darwin open a issue on the upstream project. But I think this is due to build dependency errors in nixpkgs on x86_64-darwin.

**Comment by SuperSandro2000** [comment]
Git failed to build when you created your branch. Rebasing might fix this but I did not follow it lately to know it exactly.

**Comment by foo-dogsquared** [comment]
I updated the PR now to the latest commit of the master branch (at least 35 minutes ago).

**Review by 0x4A6F — APPROVED** [review]

**Comment by foo-dogsquared** [comment]
@SuperSandro2000 can you check if it successfully builds on x86_64-darwin?

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 103219` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>dasel</li>
  </ul>
</details>

**Comment by foo-dogsquared** [comment]
Closing since #103859 already takes care of things.

**Pull request closed without merging**
