### PR TITLE
haskell-updates: Example hackage-packages update

### PR DESCRIPTION
**Pull request by maralorn**
This is a rather unorthodox PR as normally I would just push this to haskell-updates, but I thought it would be nice to briefly discuss this.

I have done:

1. Add `--do-commit` option to the relevant haskell update scripts.
2. Run: `maintainers/scripts/haskell/update-hackage.sh --do-commit && maintainers/scripts/haskell/update-stackage.sh --do-commit && maintainers/scripts/haskell/regenerate-hackage-packages.sh --do-commit`

@NixOS/haskell any suggestions for improvement?

### CODE REVIEW

**Comment by maralorn** [comment]
Oh, wow. I didn‘t mean to merge this. But I screwed up my git.

I suggest you two have a look at it anyways. If there is anything to improve I will do that with a new PR.

**Comment by cdepillabout** [comment]
Thanks for adding the `--do-commit` flag.

I think this all looks really good!

**Comment by maralorn** [comment]
> The message is a bit to wordy (too the point where GitHub contracts it). I'd say best would be `all-cabal-hashes: YYYY-MM-DD -> YYYY-MM-DD` where the first is the old commit date, and the second the new commit date. This is probably more trouble to implement than its worth though, `all-cabal-hashes: Update to <date>` would probably suffice.

Yeah, so. The problem is that the "Update from Hackage .." part is the verbatim upstream commit message. And I had conceptual resistance to parse that message to extract the date …

**Comment by sternenseemann** [comment]
Can't you extract the date in the update script, instead of the message?

**Comment by maralorn** [comment]
I will look into it.

**Pull request merged**
