### PR TITLE
slack: add auto-updater script

### PR DESCRIPTION
**Pull request by samuela**
###### Motivation for this change
Save hooman time by spending computer time. This will enable adding slack to https://github.com/samuela/nixpkgs-upkeep.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by samuela** [comment]
cc maintainer @mmahut

**Comment by mmahut** [comment]
@samuela what is the advantage of this approach versus using @r-ryantm?

**Comment by samuela** [comment]
> @samuela what is the advantage of this approach versus using @r-ryantm?

They're more or less the same, with the main difference being that nixpkgs-upkeep does packages that @r-ryantm is not auto-updating. A few other differences: nixpkgs-upkeep has build logs available for all to see on GitHub Actions, only is based on the auto-update scripts that are already in nixpkgs for convenience, and runs every 12 hours.

It's not really meant to be a competition though. I mainly created this PR so that slack could have all of the update.sh conveniences that other packages like vscode and spotify have.

**Review by doronbehar — APPROVED** [review]

**Comment by doronbehar** [comment]
You should also set `passthru.updateScript`.

**Comment by samuela** [comment]
Ok, added `passthru.updateScript` in 3037318.

**Comment by mmahut** [comment]
@samuela I really appreciate this effort, but I feel like it would be better to work on the @r-ryantm bot as a community tool instead of creating an alternative? I do not personally like including scripts with such a limited usage in `nixpkgs`, the repo as well as the nix store is growing painfully and I feel like we need to work on tech debt and not I feel like this is just creating another one.

**Comment by samuela** [comment]
We could also just merge this update script but not add slack to nixpkgs-upkeep. I'd imagine that @r-ryantm could use an update script like this anyhow. 

OTOH, if you're opposed to update scripts in nixpkgs that may not be favorable. As another option, this script could be added to nixpkgs-upkeep but not nixpkgs and run "out of sight, out of mind".

Wdyt?

**Comment by doronbehar** [comment]
You are both confusing a few things:

1. @r-ryantm is supposed to run `passthru.updateScript`s (since https://github.com/ryantm/nixpkgs-update/pull/205 ), but IIRC it doesn't run it for unfree packages.
2. @mmahut the script added here, does something that @r-ryantm doesn't. [`nixpkgs-update`](https://github.com/ryantm/nixpkgs-update) has a limited number of methods to grab the latest version of a package:
   - [Repology](https://repology.org/)
   - GitHub releases.
   - Pypi releases
3. Repology, which is not the most established way to get the latest versions, is essentially based on what other distro's repos are doing, but it's not really reliable because it's a bit disconnected from true upstream.

Hence, the script added here is justified because in order to programmatically find out "what is the latest slack version available?", one has to scrap their website, and not look it up in in one of the sources mentioned above.

**Review by doronbehar — APPROVED** [review]

**Comment by mmahut** [comment]
@doronbehar I would really appreciate it, that next time, you would wait for the package maintainer himself to merge a change after clearing up all questions about a change.

**Comment by ryantm** [comment]
@mmahut r-ryantm uses passthru.updateScript so this change is likely to help it. It would have likely failed before because of multiple hashes being present.

@doronbehar r-ryantm updates unfree things

**Pull request merged**
