### PR TITLE
treewide: cleanup; move packages to `pkgs/by-name`; format via `nixfmt-rfc-style`

### PR DESCRIPTION
**Pull request by NotAShelf**
## Description of changes

Currently going over https://github.com/NixOS/nixpkgs/issues/43716 to figure out licenses for packages without one, and performing maintenance (as in cleanup and formatting) on packages before I update and add license in a separate PR.

- Formatting refers to formatting a package with `nixfmt-rfc-style`.
- "Cleanup" refers to removing `rec`, `with lib` and other bad patterns.

This'll probably be large as there are *lots* of packages to go over.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by drupol** [comment]
What's the reason for closing this?

**Comment by NotAShelf** [comment]
I was told in Matrix that such a PR would be discouraged not to step on others' toes.

**Comment by NotAShelf** [comment]
I am happy to continue with this PR, but I would like to avoid roadblocks down the road stemming from a lack of consensus. If I can get a few more positive responses to this, I'll re-open and proceed.

**Comment by drupol** [comment]
Can you please ping the maintainer who advised not to do this?

**Comment by NotAShelf** [comment]
That'd be @dali99 I believe.

**Comment by drupol** [comment]
@dali99 Could you please elaborate on this PR ?

The only issue I see here is the PR title, besides that, it looked legit to me.
I often do this kind of things myself, never had any issue with that.

**Comment by dali99** [comment]
For the right context see

See https://matrix.to/#/!kjdutkOsheZdjqYmqp:nixos.org/$PilZWDCiopphZRNWhHWCQ20bulZOY0ynW6nK5tPLElg?via=lossy.network&via=matrix.org&via=nixos.dev

and

https://matrix.to/#/!kjdutkOsheZdjqYmqp:nixos.org/$MACs3PednHwhc7EIDHG4DYWV9OW0hl2yBPcEApH8CzQ?via=lossy.network&via=matrix.org&via=nixos.dev

I believe the "stepping on toes" part comes from https://matrix.to/#/!kjdutkOsheZdjqYmqp:nixos.org/$c64jRjBheEYGyhl1XXNsZ-wUGfaahFwRkK3MsIXXG-o?via=lossy.network&via=matrix.org&via=nixos.dev

The main points are:
* Moving packages as part of a "general cleanup" treewide is not encouraged
* There has been significant historical turmoil around automatic formatting. And we are not at the point where automatic formatting is being done on the whole tree. We should wait for that.
* Even still, doing these things might be okay, but I believe that doing so should be up to the owners/maintainers of these packages. Not as part of a individual persons' desire to "clean up" derivations around the repository.

This PR's main motivation seems to be the by-name/formatting. And thus I think these things should not be encouraged _yet_. Especially not done unilaterally without the real maintainer's involvement.

This contributor is new and the advice was more general than necessarily for only this package

**Comment by NotAShelf** [comment]
You are not wrong that formatting and migrating is my motivation, but its not the *main* motivation. 

I am more interested and adding missing licenses, but I'd rather also not leave the packages in their "legacy" state. Some derivations also urgently need maintenance updates, which I'd rather get out of the way while I am already here.

**Comment by drupol** [comment]
I'm also driven by fixing the issue when I see one, and I have my own personal rule.

If when I edit a Nix file to fix a specific problem AND if I see other issue, I fix them in the same PR, but in different commits.

Basically, every time I edit a Nix file in a PR, it should be totally valid at the end of the PR.

**Comment by eclairevoyant** [comment]
Btw, there is no such thing as ownership in nixpkgs; this is a collaborative project. What being a maintainer entails is that you are making yourself available to fix issues with the package, handle updates, approve PRs, etc. and that you ideally use the package and have some knowledge of whether any change will improve a package or not.

This does _not_ preclude making changes to packages you are not a maintainer for; many of our contributions come from non-maintainers.

@NotAShelf, please feel free to reopen if you're interested in continuing work on this PR.

**Comment by drupol** [comment]
> Btw, there is no such thing as exclusive ownership in nixpkgs; this is a collaborative project. What being a maintainer entails is that you are making yourself available to fix issues with the package, handle updates, approve PRs, etc. and that you ideally use the package and have some knowledge of whether any change will improve a package or cause a problem with it.
> 
> This does _not_ preclude making changes to packages you are not a maintainer for; many of our contributions come from non-maintainers.
> 
> @NotAShelf, please feel free to reopen if you're interested in continuing work on this PR.

Voila quelqu'un d'eclairevoyant! (french pun intended!) 

Please forgive me, it's been a while I wanted to do it...

**Review by drupol — CHANGES_REQUESTED** [review]
Can you please adjust the PR title?

**Comment by NotAShelf** [comment]
Sure, how should I adjust it?

**Comment by drupol** [comment]
Since you're modifying only one derivation, I would do:

```
cue2pops: move to `pkgs/by-name`
```

**Comment by NotAShelf** [comment]
I plan to move other derivations as well, though. So far I have 7 waiting to be pushed.

**Comment by drupol** [comment]
Ooh fair enough. Ignore my comment then.

**Comment by dali99** [comment]
> Btw, there is no such thing as exclusive ownership in nixpkgs; this is a collaborative project. What being a maintainer entails is that you are making yourself available to fix issues with the package, handle updates, approve PRs, etc. and that you ideally use the package and have some knowledge of whether any change will improve a package or cause a problem with it.
> 
> This does _not_ preclude making changes to packages you are not a maintainer for; many of our contributions come from non-maintainers.

It was never about exclusive ownership. I'm arguing for respecting each other's responsibilities and _following the rules, guides, and plans we've agreed on_. These are both crucial parts of a collaborative project. I'm just accepting there's nuance around ignoring the plan for the things you're actively responsible for.

Misconstruing my sentiment to imply anything else is - how should I say this - Totally uncool.

> Basically, every time I edit a Nix file in a PR, it should be totally valid and following the current best practices at the end of the PR.

My own ethos is:
Fix problems, keep the local style, make it easy to accept. _As if they wrote it_.
Be non-controversial

**Comment by eclairevoyant** [comment]
What rule is this PR violating, exactly?

**Comment by emilazy** [comment]
I think formatting files you touch is in the spirit of https://github.com/NixOS/nixpkgs/pull/322537, which will soon make it mandatory precisely to enable this kind of incremental transition; there’s clearly no question of ownership there and no real grounds to hold back on formatting any given leaf package that doesn’t have a ton of existing open PRs.

Moving into `pkgs/by-name` I can understand there being some maintainer discretion on; the story for doing that across the entire tree hasn’t been entirely worked out there, and CI ratchet checks means that there’s no easy way of undoing it in case some of the functionality that cannot be used with `pkgs/by-name` becomes required at a later date. Still, for simple leaf packages it also seems fine to me.

If a maintainer objects then of course their reasons should be taken into consideration, and I do think that those migrations should be in separate commits from any other changes to make reviewing the diffs easier. But, while I grant that there is some nuance here, I personally disagree with @dali99 about the extent to which there is any firm consensus or guideline against doing these clean‐ups, as long as you have another meaningful change to make to the packages anyway. The [documentation for `pkgs/by-name`](https://github.com/NixOS/nixpkgs/blob/fcf65eb2954fc78232b038ceef5d6a5390a734ec/pkgs/by-name/README.md#manual-migration-guidelines) states:

> Manual migrations should only be lightly encouraged if the relevant code is being worked on anyways. For example with a package update or refactoring.

…which, while hardly an urgent endorsement, certainly doesn’t advise *against* it.

**Comment by AndersonTorres** [comment]
ofborg called me to review this, since the package I maintain was touched by it.

Let's go:

1. Mere migration to by-name is OK to me. I would do this myself, however this was discouraged.
2. Migration plus modernization (remove nested with) is OK too.
3. `nixfmt-rfc-style` I am a bit reticent, since it can generate noisy patches.
    Further, many people hate to review PRs with reformatting.

> Some derivations also urgently need maintenance updates, which I'd rather get out of the way while I am already here.

This should be made on a per package basis, not as part of a treewide PR.

**Comment by emilazy** [comment]
If every minor clean‐up has to be split into one PR per package, people just won’t clean things up. I understood the intent of this PR to be to handle the packages listed as lacking licence information in https://github.com/NixOS/nixpkgs/issues/43716; I think doing some tidying up along the way is reasonable. I do think there’s a threshold of change where it makes sense to split things up and get individual review but I’m not sure that would reach it.

That said, I see that the change currently in the PR is just a mechanical update and clean‐up of a package that isn't lacking licence information; for that kind of thing I agree that it should be either separated out into its own PR or done systematically in one go.

**Comment by drupol** [comment]
The more people we involve, the more we will have different opinionated overviews.
I'm here to improve `nixpkgs`, not for those politics and shenanigans, unsubscribing.

**Comment by emilazy** [comment]
I think there is perhaps some confusion here because I believe “treewide:” in the PR is only meant to reflect that it touches multiple packages rather than an intent to touch every single package. But I don’t feel like I’m doing a good job at conveying the nuances of my position here, so I’ll bow out too.

**Comment by dali99** [comment]
@emilazy I feel you. I originally spent hours yesterday trying to convey my feelings as accurate as possible. Culminating in a very large wall of text and one light mental breakdown about the changing culture in nixpkgs over the last six years. I felt quite hurt by @eclairevoyant s comment. But I'm not good at writing accurately, concisely, and politely.

I'm sure we all actually have much more nuanced opinions than what we are managing to express here.

@NotAShelf I'm really sorry your PR was turned into this

**Comment by eclairevoyant** [comment]
> When we don't have consensus

https://github.com/NixOS/rfcs/pull/140 (by-name structure) and https://github.com/NixOS/rfcs/pull/166 (nixfmt-rfc-style) getting merged represents net community consensus. There is nothing to tread lightly here about, as this follows the guidelines/plans/whatever as written in this very repo. `@emilazy` quoted the relevant guideline for the former; for the latter, we already have CI enforcing the formatter on certain paths:

https://github.com/nixos/nixpkgs/blob/d14441cfe1bba01699cd614d6ef82cf6bc6aac22/.github/workflows/check-nix-format.yml#L37-L56

So I'm not sure why you think there is a lack of consensus here.

**Comment by AndersonTorres** [comment]
> If every minor clean‐up has to be split into one PR per package

I am not talking about every minor cleanup. 

I am talking about "maintenance updates".

"Maintenance updates" has a large latitude of meaning.

I am doing a maintenance update on the SDL ecosystem, since the original maintainers retired.
I am not introducing any new package. I am merely reworking the code.
And it is causing mass rebuilds: 

- https://github.com/NixOS/nixpkgs/pull/308379
- https://github.com/NixOS/nixpkgs/pull/324837

I tried to do maintenance updates to mesa expressions, and a single whitespace after a `-D` caused mass rebuilds.

Maintenance updates are not necessarily minor cleanups.

> I think doing some tidying up along the way is reasonable. 

I agree with you here. 
However, there are many people - and among them, many people with commit bit - that don't.
And they can easily embargo a PR.

**Comment by dali99** [comment]
> > When we don't have consensus
> 
> [NixOS/rfcs#140](https://github.com/NixOS/rfcs/pull/140) (by-name structure) and [NixOS/rfcs#166](https://github.com/NixOS/rfcs/pull/166) (nixfmt-rfc-style) getting merged represents net community consensus. There is nothing to tread lightly here about, as this follows the guidelines/plans/whatever as written in this very repo. `@emilazy` quoted the relevant guideline for the former; for the latter, we already have CI enforcing the formatter on certain paths:
> 
> [nixos/nixpkgs@`d14441c`/.github/workflows/check-nix-format.yml#L37-L56](https://github.com/nixos/nixpkgs/blob/d14441cfe1bba01699cd614d6ef82cf6bc6aac22/.github/workflows/check-nix-format.yml#L37-L56)
> 
> So I'm not sure why you think there is a lack of consensus here.

I have to believe you are being intentionally obtuse here and I will therefore disengage, this is the second time you've managed to carefully misunderstand my entire argument. This is entirely a question of how, when and not if, and has always been this. The fact that we've agreed on that this will happen does not mean we've agreed on it happening this way, or that it will happen now. There was discussion around enabling the formatting lint in for example python. But they can do that because the python team is responsible for the python tree.

We obviously disagree as to whether or not this fits the "exception" for by-name migrations. But the main crux of the argument isn't that a package can or can't be moved. It's that _you_ might not the one who should be making that decision. I don't believe this light encouragement trumps giving that agency to our maintainers. You might believe something different.

**Comment by eclairevoyant** [comment]
I'm not misunderstanding anything; you seem to believe that maintainership is a form of ownership of a package and they have the final say on every change that happens on the package and can even block improvements, even if they don't actually cause problems to the packaging. I cannot agree with that, nor have I seen that being put into practice.

Especially when we have ratcheting checks that will eventually force the move and reformatting anyway, discouraging/bikeshedding someone that you refer to as a "new contributor" simply doing the sort of PR that has been done hundreds of times already seems unnecessarily hostile.

**Pull request closed without merging**
