### PR TITLE
dart: 2.0.0 -> 2.2.0

### PR DESCRIPTION
**Pull request by glesica**
###### Motivation for this change
There are newer versions of Dart available.

###### Things done
Added 2.1.0, 2.1.1, 2.2.0, and the latest dev channel release of the 2.3.0 series. I'm not actually sure what the `dart_stable`, `dart_old`, and `dart_dev` values are for, I can't actually figure out how to use them other than the fact that they cause the corresponding versions to show up in a query. However, this means 2.2.0 shows up twice, so maybe we ought to drop `dart_stable`?

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions (Fedora 30)
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by fr3fou** [comment]
Any news?

**Comment by rixed** [comment]
There is no maintainer in the meta, so that must not help. I suggest finding one (maybe yourself?)
Then, is it necessary to keep all the old version definitions?

**Comment by glesica** [comment]
Not really necessary, no. I was just following the pattern that seemed to exist already. You think just keeping the latest would be fine?

**Comment by glesica** [comment]
Speaking of which, I also need to update this to 2.6. I'll do that this weekend.

**Comment by rixed** [comment]
> You think just keeping the latest would be fine?

That's my understanding of the recommended best practices. See https://nixos.org/nixpkgs/manual/#sec-versioning
Also this thread has more info and rationale: https://github.com/NixOS/nixpkgs/issues/36266

So unless there is value to keep various versions (for instance if several versions are popular that are incompatible) then I would say there should be only the latest version in nixpkgs.

**Comment by glesica** [comment]
I'll update it, thanks!

**Comment by GRBurst** [comment]
so this is superseded by #78475

**Comment by glesica** [comment]
Perfect, thanks!

**Pull request closed without merging**
