### PR TITLE
gcc48: remove

### PR DESCRIPTION
**Pull request by tobim**
## Description of changes

`gcc48` is not referenced from within nixpkgs, so I propose to remove it.
https://discourse.nixos.org/t/feedback-wanted-removing-gcc-4-8-from-nixpkgs/33259

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tobim** [comment]
relates #256328.

**Comment by vcunat** [comment]
Not being referenced doesn't seem like very relevant argument to me, as compilers in particular tend to be often used from outside (by `nix-shell` or others).  I personally think these might be old enough to drop, but perhaps someone will bring a good enough use case for them.

**Comment by tobim** [comment]
I will ask on discourse, but I doubt a long waiting period will help much. This PR or a post will be buried quickly. It's more likely that people will start complaining after it's merged, at which point we can still revert.

**Review by infinisil — CHANGES_REQUESTED** [review]
It should be replaced with an error when evaluated at the very least. Even better would be a `lib.warn` first for a release.

**Comment by tobim** [comment]
I was under the impression that releases are specific to NixOS, but not nixpkgs as a whole. Maybe that is a misunderstanding on my side, do we have any documentation or guidelines on this topic?

In any case, `gcc48` seems to be pretty far removed from NixOS.

**Comment by vcunat** [comment]
Usually "NixOS" word is used, but de-facto the whole thing is released, as I see it.  For example, we have `nixpkgs-23.05-darwin` which is certainly far removed from NixOS.  I'm not sure if it's formalized somewhere.

**Comment by vcunat** [comment]
I see "for a release" here more like a time scale in this case.

**Comment by vcunat** [comment]
Release-manager's wiki [is very conservative](https://nixos.github.io/release-wiki/Feature-Freeze-Announcement.html#pre-release-cleanup):
> Attributes that can also be safely removed are packages that were broken for more than 2 years.

**Comment by 7c6f434c** [comment]
To be fair, the old pinned versions are dropped faster, and the question is probably whether `gcc48` should be handled as a _package_ or as a now-less-necessary _version_ of `gcc`

**Review by ghost — CHANGES_REQUESTED** [review]
Deleting things from nixpkgs is not an improvement.

If the deletion is necessary in order to solve some other problem, solving that other problem might be an improvement.  But I see no sign of that being the case here.

**Comment by tobim** [comment]
> Release-manager's wiki [is very conservative](https://nixos.github.io/release-wiki/Feature-Freeze-Announcement.html#pre-release-cleanup):
> 
> > Attributes that can also be safely removed are packages that were broken for more than 2 years.

Thanks for that link!
The other bullet in on that page advises that packages for software releases that are past their EOL date should also be removed. Imho the term EOL is a bit unfortunate in this case, because EOL usually relates to a product, but I don't know how to interpret it for a community driven project such as GCC.
If we take "End Of Maintenance" instead that happened 8 years ago.

> To be fair, the old pinned versions are dropped faster, and the question is probably whether `gcc48` should be handled as a package or as a now-less-necessary version of `gcc`.

It seems like a good idea to distinguish it like that.
As a package we can look at other central packages, the linux kernel is the first that comes to my mind.
About it being necessary the only case that I can think of is bootstrap, but the regular bootstrap tarball has long been moved past that. The minimal bootstrap has it's own expression for gcc4.6, and I'd be surprised if there were plans to consolidate with the regular gcc expression (@emilytrau please correct me on that).

**Comment by emilytrau** [comment]
> The minimal bootstrap has it's own expression for gcc4.6, and I'd be surprised if there were plans to consolidate with the regular gcc expression (@emilytrau please correct me on that).

There are no plans to use the gcc expressions in minimal-bootstrap.

**Comment by RaitoBezarius** [comment]
An important way to look into how much something is used outside nixpkgs is SourceGraph: https://sourcegraph.com/search?q=context%3Aglobal+gcc48+lang%3Anix&patternType=standard&sm=1&groupBy=repo

**Comment by tobim** [comment]
> Deleting things from nixpkgs is not an improvement.

The way I see it every package in the attribute set adds some maintenance cost, and when there is no more use of that package one can consider that an improvement.

**Comment by amjoseph-nixpkgs** [comment]
> The way I see it every package in the attribute set adds some maintenance cost,

This simply isn't true.

This thread has already consumed more of my time than `gcc48` has consumed in its entire existence.

If it isn't broken there is no reason to remove it.

**Comment by Artturin** [comment]
Closing due to a gcc maintainers(@amjoseph-nixpkgs) objection

**Pull request closed without merging**
