### PR TITLE
nixos/fwupd: fix silent failure for uefiCapsuleSettings to ever be added

### PR DESCRIPTION
**Pull request by lilyinstarlight**
## Description of changes

See https://github.com/NixOS/nixpkgs/pull/283568#pullrequestreview-1926274847

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by r-vdp — APPROVED** [review]
Diff LGTM. I'm not able to actually test the change since I'm traveling until Monday.

**Comment by amaxine** [comment]
Thanks! I'm irritatingly not great at reading nix language stuff 😅

**Comment by lilyinstarlight** [comment]
> Thanks! I'm irritatingly not great at reading nix language stuff 😅

(It took me reading through the module a few times to realize why the `uefi_capsule` section disappeared recently, so it's easy to miss and I probably would have missed it too if reviewing ❤️)

**Review by bjornfor — APPROVED** [review]

**Comment by bjornfor** [comment]
> Diff LGTM. I'm not able to actually test the change since I'm traveling until Monday.

@r-vdp: I'm was planning to merge, but do you want to test it first?

**Comment by ChanceHarrison** [comment]
I cherry-picked 18015838550d57f525518568e75ef9e986fd9af7 onto nixos-unstable (9df3e30ce24fd28c7b3e2de0d986769db5d6225d) and rebuilt my system (and rebooted for good measure) to see if I could update my system UEFI with `fwupdmgr` without running into `Secure boot is enabled, but shim isn't installed to EFI/nixos/shimx64.efi`, but that error still occurs which makes me concerned that this change does not have the intended result.

It could also be a me-problem; I would appreciate it if someone could point me toward a more direct way of testing.

**Comment by lovesegfault** [comment]
I've cherry-picked this on top of nixos-unstable for testing: https://github.com/lovesegfault/nixpkgs/tree/nixos-unstable-294544

**Comment by r-vdp** [comment]
> @r-vdp: I'm was planning to merge, but do you want to test it first?

It looks to me that we want this PR in any case, we're definitely applying `//` to the wrong value currently.

Whether this PR is sufficient to fix the issue, is not clear to me and I'm not able to test this for the moment.

So I'm ok with merging this in any case, but I'd also be fine with using this PR to get to the bottom of why the uefi section seems to be missing for some people.

**Comment by lovesegfault** [comment]
Works AOK and fixes the issue

**Comment by ChanceHarrison** [comment]
Please disregard my issue; I thought I was using my local nixpkgs clone when rebuilding my system but I was not. This change does indeed fix the issue I was having. Thanks to everyone involved!

**Pull request merged**
