### PR TITLE
vimPlugins.nvim-treesitter: prefix version with commit-

### PR DESCRIPTION
**Pull request by SuperSandro2000**
This makes diffing two nixos systems less noisy,
as no longer short commits starting with numbers are counted as versions and with letters as pname.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by figsoda** [comment]
> This makes diffing two nixos systems less noisy

Are you using nvd? because I'm not sure that this fixes the issue

```python
import re

# https://gitlab.com/khumba/nvd/-/blob/83020265455d858ffffbbae07c2a53ff17c2388a/src/nvd#L97
regex = re.compile(r"^/nix/store/[a-z0-9]+-(.+?)(-([0-9].*?))?(\.drv)?$")


def print_match(path):
    match = regex.search(path)
    assert match is not None
    print(f"pname: {match.group(1)}")
    print(f"version: {match.group(3)}")


print("before")
print_match("/nix/store/ahzmdp22rw6pb34dan6nhjg66dshbk1y-rust-grammar-fbf9e50")
print("after")
print_match("/nix/store/gikljmhwa5q3h918bqr53qvfj1x2bg3j-rust-grammar-commit-fbf9e50")
```

```
before
pname: rust-grammar-fbf9e50
version: None
after
pname: rust-grammar-commit-fbf9e50
version: None
```

**Comment by SuperSandro2000** [comment]
> Are you using nvd? because I'm not sure that this fixes the issue

Nope, I use ``nix store diff-closures``.

I mainly want to prevent those changes which frequently appear:

```
bash-grammar: 7f9506c → ∅, -483.0 KiB
bash-grammar-b338fa9: ∅ → ε, +483.0 KiB
```

**Comment by figsoda** [comment]
I don't think that works either:
```
rust-grammar-commit: 4bf9e50 → ∅, -770.4 KiB
rust-grammar-commit-fbf9e50: ∅ → ε, +770.4 KiB
```

**Comment by figsoda** [comment]
[This](https://github.com/NixOS/nix/blob/e00abd3f566b16bb107d513925cf33b40cca35f4/src/libstore/names.cc#L27) is the logic that determines the name and version, it basically looks for `-[0-9]`

**Comment by SuperSandro2000** [comment]
I should know that section pretty well, I once wrote a custom patch for it and the RFC around version parsing.

**Review by figsoda — APPROVED** [review]

**Pull request merged**
