### PR TITLE
statsd: restore support for {influx,librato,stackdriver} backends

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

adds backends (follow-up for #31235)

These packages will be placed into an environment using
`backendsToPackages`. This function explicitly maps backends to
`pkgs.nodePackages.${type}` unless it's a builtin (some backends
are directly available in the `statsd` source tree). This ensures that only
valid backends that work on NixOS are used (if not, the build already
breaks at evaluation time).

The log will be redirected to `stdout` to be able to watch the entire
output using `journalctl`.

Configuration parameters for the backends need to be set using
`services.statsd.extraConfig` as each backend has its own options and
all of them shouldn't be validated and checked explicitly and manually.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ma27** [comment]
I think it might be the best option to add a full-blown testcase for `statsd`, then we should be fine :)

**Comment by Ma27** [comment]
@garbas I added a simple testcase and removed the WIP label. If everything is fine for you, we can merge this now :-)

**Comment by Mic92** [comment]
@GrahamcOfBorg test statsd

**Comment by Mic92** [comment]
If your test is no in `nixos/release.nix` it will be never executed by hydra.

**Comment by Ma27** [comment]
ah good to know :-)

**Comment by Mic92** [comment]
@GrahamcOfBorg test statsd

**Comment by Ma27** [comment]
@Mic92 how does the bot call these tests? (it's actually the first test I contribute to nixpkgs and I just used `nix-build ./nixos/tests/statsd.nix` :)

**Comment by Ma27** [comment]
@garbas I just resolved the merge conflict introduced by the autogenerated node2nix expressions, so this should be mergable again :)

**Review by garbas — APPROVED** [review]
tnx!

**Pull request merged**
