### PR TITLE
nixos/filesystems: condition mount-pstore.service on unmounted /sys/fs/pstore (once more)

### PR DESCRIPTION
**Pull request by ghost**
backport of #123902.

### CODE REVIEW

**Comment by hyperfekt** [comment]
@symphorien Here we go.

**Comment by symphorien** [comment]
The manual https://nixos.org/manual/nixpkgs/stable/#submitting-changes-stable-release-branches requests that you cherry-pick with `-x` for traceability.

**Comment by hyperfekt** [comment]
Thanks! The whole merge parent thing had me a bit tripped up.

**Comment by symphorien** [comment]
thanks!

**Pull request merged**
