### PR TITLE
hedgedoc: 1.9.4 -> 1.9.5

### PR DESCRIPTION
**Pull request by drupol**
This PR has been made using the provided update script.

There were some inconsistencies in the script and it had to be updated:
- [x] The file `yarn.lock` was not downloaded
- [x] The hash returned by `nix-prefetch-github hedgedoc hedgedoc --rev "1.9.5" | jq -r .sha256` is not the expected hash format (`sha256-dcqCc4UUI1knRlDfQlXq3cpTRTh+kbgFynbypDzw9y8=` vs `n6I9i0b5Z8HgGmGEM+pYl340P/UDzRYOFElyyS0s6cM=`)
- [x] (optional) Since the new hash format, the sed delimiter had to be updated to avoid collision with `/` in the hash.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by drupol** [comment]
@GrahamcOfBorg build hedgedoc

**Comment by drupol** [comment]
@GrahamcOfBorg build hedgedoc

**Comment by drupol** [comment]
@GrahamcOfBorg build hedgedoc

**Comment by drupol** [comment]
@GrahamcOfBorg build hedgedoc

**Comment by drupol** [comment]
@GrahamcOfBorg build hedgedoc

**Comment by drupol** [comment]
@GrahamcOfBorg build hedgedoc

**Comment by drupol** [comment]
@GrahamcOfBorg build hedgedoc

**Comment by xentec** [comment]
Hi and thank you for this quick PR.
Could this version bump also be backported to NixOS 22.05?

**Comment by Mrmaxmeier** [comment]
I've just ran into a data loss issue with v1.9.5 (https://github.com/hedgedoc/hedgedoc/issues/2809), so let's skip this version bump for the stable channels until the maintainers figure out a fix.

Applying [this patch](https://github.com/hedgedoc/hedgedoc/issues/2809#issuecomment-1303624876) without waiting for a patched release might also be worth it.

**Comment by BBBSnowball** [comment]
This is running HedgeDoc with NodeJS 18 on my system. They changed this wording from ">=16" to "Node 18 is NOT supported."
https://github.com/hedgedoc/hedgedoc/compare/1.9.4...1.9.5#diff-28a940e1f5c7a976526b9437278b5ad3f3b60dad38c138b1dbf4fcdc6683fe77

This seems to be due to ["dependency problems"](https://github.com/hedgedoc/hedgedoc/commit/98e9616af870dc6f2c79725741091c85f166f065) and we don't seem to run into those so that part is probably fine (but I ran into a similar issue as Mrmaxmeier). I haven't noticed any problems due to Node 18, yet.

**Comment by davidmehren** [comment]
Node 18 is not supported, because the frontend cannot be built with it, because we use Webpack 4, which is [not compatible](https://github.com/webpack/webpack/issues/14532) with Node 17+.
Using the prebuilt frontend *should* work with 18, but we don't test that.

**Comment by SuperSandro2000** [comment]
> This is running HedgeDoc with NodeJS 18 on my system.

fixing that right now.

**Comment by SuperSandro2000** [comment]
see #199873

**Pull request merged**
