### PR TITLE
weechat: install all outputs into the final store path

### LINKED ISSUE #59300: No manpage for weechat
## Issue description

There is no manpage for weechat

### Steps to reproduce
`nix run nixpkgs.weechat -c man weechat`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.0, NixOS, 19.09.git.c141839 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(teto): `""`
 - channels(root): `""`
 - nixpkgs: `/home/teto/nixpkgs`
```

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

Resolves #59300

Until now only `$out/bin/weechat` and `$out/bin/weechat-headless` were installed
into the store path that will be used when running i.e. `nix-env -iA weechat`.

Further outputs like icons (`$out/share/icons`), man pages (`$man`) or the HTML
documentation (`$out/share/doc/weechat`) are omitted at the moment. As
this can be fairly confusing I figured that it's better to copy those
files into the environment as well.

As `buildEnv` doesn't appear to support output splitting (you can only
install additional outputs of `paths` using `extraOutputsToInstall`),
it's easier for now to always install the `man` output by
default.

Man page installation can be turned off like this now:

``` nix
weechat.override { installManPages = false; }
```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by teto** [comment]
I've seen this problem with zathura and neovim too, seems like we need buildEnv to support output splitting ? (in another PR maybe).

**Comment by Ma27** [comment]
Hmm indeed, in the long term we should fix this for `buildEnv`. I guess that this patch is mergable as-is, I'll have a look at the build script of `buildEnv` in the next weeks and see how to implement this :)

**Comment by FRidh** [comment]
Perhaps
```
passthru.man = weechat.man;
```

**Comment by Ma27** [comment]
> Not sure if buildEnv would be smart enough to pick this man up as an output though.

If I understood how `buildEnv` works this won't work correctly:

* `extraOutputsToInstall` installs all given outputs into the environment by default (that's what this patch does)
* With `passthru` being set, `man` won't be detected as additional output. Hence users have to install man pages for weechat manually.

I think that for now it's fine to use `extraOutputsToInstall` here. In the long term we probably want to fix `buildEnv` to support extra outputs.

**Comment by Ma27** [comment]
@FRidh anythign else? I don't have the time to fix `buildEnv` accordingly at the moment, so I think that this is the best way to go for now.

**Comment by FRidh** [comment]
Nope

**Comment by Ma27** [comment]
Great! :)

**Pull request merged**
