### PR TITLE
autoconf: 2.69 -> 2.70

### PR DESCRIPTION
**Pull request by alyssais**
###### Motivation for this change

First release in 6 years! I expect this will take a lot of fixing up packages. For now, I think we should just keep 2.69 around and pin it for anything that fails with 2.70. I’ll look into getting a Hydra jobset or something so we can identify all the packages that need that before applying this.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
@vcunat could you make a hydra job for this.

**Comment by vcunat** [comment]
Here it is: https://hydra.nixos.org/jobset/nixpkgs/autoconf-2.70 (just a single platform for now)

**Comment by vcunat** [comment]
News: https://lwn.net/Articles/839395/

:-)
> The macro AC_OBSOLETE is obsolete.

**Comment by alyssais** [comment]
I think this is ready now.  I've addressed every autoconf-related
Hydra failure.  Any objections before I merge?

**Review by jonringer — APPROVED** [review]
I think the attrs should have been called `autoconf_2_{69,70}` as this is more aligned established versioning conventions.

But LGTM otherwise.

it would be a lot of tedious work to change it now

other regressions and be dealt with in staging-next.

**Comment by alyssais** [comment]
> I think the attrs should have been called `autoconf_2_{69,70}` as this is more aligned established versioning conventions.

I agree in general, although in this case other autoconf versions used the scheme without underscores so I thought it was better to stick to that here.

**Comment by jonringer** [comment]
> although in this case other autoconf versions used the scheme without underscores

perhaps autoconf versions pre-dates coming to a consensus about version numbers.

**Review by vcunat — APPROVED** [review]
Hydra OK at a quick look.  In case some regression was missed, most likely it will be simply fixed by switching version for the failing package...

**Comment by flokli** [comment]
This broke the `hidapi` (a dependency of `openssh`) cross-build:
```
these derivations will be built:
  /nix/store/952z8zv4j0m9nl41dwv29csl15zim6vk-hidapi-0.10.1-armv6l-unknown-linux-gnueabihf.drv
building '/nix/store/952z8zv4j0m9nl41dwv29csl15zim6vk-hidapi-0.10.1-armv6l-unknown-linux-gnueabihf.drv'...
unpacking sources
unpacking source archive /nix/store/p8nb0nlfffkl9ks12qqlrvc9zgsfvn91-source
source root is source
patching sources
autoreconfPhase
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
configure.ac:16: error: AC_CONFIG_MACRO_DIR can only be used once
./lib/autoconf/general.m4:1969: AC_CONFIG_MACRO_DIR is expanded from...
configure.ac:16: the top level
autom4te: error: /nix/store/h79jdfbmk9kzb4zyh1vs035z3w62cva6-gnum4-1.4.18/bin/m4 failed with exit status: 1
aclocal: error: /nix/store/c1crh9yn453zm3kyvl3zy6j3nbmxna26-autoconf-2.70/bin/autom4te failed with exit status: 1
autoreconf: error: aclocal failed with exit status: 1
builder for '/nix/store/952z8zv4j0m9nl41dwv29csl15zim6vk-hidapi-0.10.1-armv6l-unknown-linux-gnueabihf.drv' failed with exit code 1
error: build of '/nix/store/952z8zv4j0m9nl41dwv29csl15zim6vk-hidapi-0.10.1-armv6l-unknown-linux-gnueabihf.drv' failed
```

**Comment by flokli** [comment]
Curious, this PR already *did* set `autoreconfHook = autoreconfHook269` in nixpkgs. If I remove it from there, I get the same error log. I wonder how we managed to make this a cross-only regression.

**Comment by flokli** [comment]
@Ericson2314 could this be triggered via 4b2ab665fbeb28b9837e920841ca81c570dfbdd4, by any chance?

**Comment by flokli** [comment]
I consider being able to build a minimal nixos image for aarch64, from a x86_64 workstation somewhat important.

As written, autoconf had no release for some years, we don't need to rush merging this to master, but can block until we don't break cross.

**Comment by jonringer** [comment]
Agreed, probably should have just exposed autoconf270; and switch the default much later.

**Comment by FRidh** [comment]
@flokli do you have a cache with pkgsCross.aarch64-multiplatform builds?

**Comment by FRidh** [comment]
hidapi fix https://github.com/NixOS/nixpkgs/pull/108025

**Comment by alyssais** [comment]
> Agreed, probably should have just exposed autoconf270; and switch the default much later.

I disagree. That’s just how we get stuck on old versions of things for years. There’s no reason to think that waiting a year or whatever would have made any difference to one package failing because nobody thought to test a cross image.

**Comment by alyssais** [comment]
> I consider being able to build a minimal nixos image for aarch64,
> from a x86_64 workstation somewhat important.

I agree -- I was trying to be careful about failures, but assumed that
Hydra would test everything important.  Would it be feasible to have
that as something Hydra would test?

**Comment by FRidh** [comment]
> Would it be feasible to have
that as something Hydra would test?

Yes and its one of those topics that's been open for years. We need to revisit `release.nix` and the Hydra jobs we have, but there's only few people with those permissions to adjust jobs and nothing happens there.

**Comment by FRidh** [comment]
In bf46afde6b22942ea605983f66ee23038986ba07 and 136c0d01d25b030c0d103e989de2d5340904dc51 I changed all the overrides to use buildPackages to fix cross-compilation.

**Pull request merged**
