### PR TITLE
lab: 0.15.3 -> 0.16.0

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

https://github.com/zaquestion/lab/releases/tag/v0.16.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by kalbasit** [comment]
@GrahamcOfBorg build lab

**Comment by marsam** [comment]
:) https://github.com/NixOS/nixpkgs/pull/62301

**Comment by kalbasit** [comment]
closing in favor of existing #62301.

**Comment by dtzWill** [comment]
On Fri, 31 May 2019 10:45:08 -0700, Wael Nasreddine <notifications@github.com> wrote:
> Closed #62309.

Thank you, my apologies for the dup.

**Pull request closed without merging**
