### PR TITLE
gcc{10,11,12,13,14}: reorder .cfi_startproc with label

### PR DESCRIPTION
**Pull request by paparodeo**
fixes llvm-18+ builds which require that an asm label precedes the .cfi_startproc pseudo instruction.

testing: built gcc13, verified patch applies on gcc10,11,12,14

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

@emilazy 
---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
These are underneath `stdenv.hostPlatform.isDarwin && stdenv.hostPlatform.isAarch64 && buildPlatform == hostPlatform && hostPlatform == targetPlatform`, which seems wrong? They should probably be higher up in the file and non‐conditional.

**Comment by paparodeo** [comment]
> These are underneath `stdenv.hostPlatform.isDarwin && stdenv.hostPlatform.isAarch64 && buildPlatform == hostPlatform && hostPlatform == targetPlatform`, which seems wrong? They should probably be higher up in the file and non‐conditional.

they can't. they must be applied after the patch fetched just above because the above patch adds a cfi_startproc just below the cfi_startproc in the virgin file.

**Comment by emilazy** [comment]
I see. Doesn’t this mean that cross‐compilers will be broken? IIRC those are weird with old GCCs and `aarch64-darwin` anyway, but I think there’s at least one combination that works. Does the `.cfi_startproc` stuff apply to `aarch64-linux` at all?

**Comment by emilazy** [comment]
SGTM.

**Comment by paparodeo** [comment]
rebuilding gcc13 will return to `ready to review` once complete.

**Comment by paparodeo** [comment]
> > I see. Doesn’t this mean that cross‐compilers will be broken? IIRC those are weird with old GCCs and `aarch64-darwin` anyway, but I think there’s at least one combination that works. Does the `.cfi_startproc` stuff apply to `aarch64-linux` at all?
> 
> hmm. I can split the patch in two and make the first part unconditional and the second come after the darwin patches. that should take care of aarch64-linux.

so I did this but need to apply the diff for for gcc14 only to revert it later on darwin as the diff we fetch also applies the patch. the logic to unconditionally apply the patch for gcc14 and up and then just revert for the darwin condition seemed simpler than adding a ton of logic on how to apply the patch.

**Review by emilazy — APPROVED** [review]
LGTM – could you add the explanation to the top of `cfi_startproc-reorder-label-14-1.diff` too?

**Pull request merged**
