### PR TITLE
elmPackages.elm-graphql: init at 4.3.1

### PR DESCRIPTION
**Pull request by PedroHLC**
## Description of changes

I'm surprised that this baby was not here until now.

## Things done

```
╰─λ ./result/bin/elm-graphql

No matching optionsParser...

Usage:

elm-graphql <url> [--base <base>] [--output <output>] [--exclude-deprecated] [--header <header>]... [--scalar-codecs <scalar-codecs>] [--skip-elm-format] [--skip-validation] # generate files based on the schema at `url`
elm-graphql --introspection-file <introspection-file> [--base <base>] [--output <output>] [--scalar-codecs <scalar-codecs>] [--skip-elm-format] [--skip-validation]
elm-graphql --schema-file <schema-file> [--base <base>] [--output <output>] [--scalar-codecs <scalar-codecs>] [--skip-elm-format] [--skip-validation]
```

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by PedroHLC** [comment]
Result of `nixpkgs-review pr 263641` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>elmPackages.create-elm-app</li>
    <li>elmPackages.elm-analyse</li>
    <li>elmPackages.elm-coverage</li>
    <li>elmPackages.elm-doc-preview</li>
    <li>elmPackages.elm-graphql</li>
    <li>elmPackages.elm-pages</li>
    <li>elmPackages.elm-review</li>
    <li>elmPackages.elm-spa</li>
    <li>elmPackages.elm-upgrade</li>
    <li>elmPackages.elm-verify-examples</li>
  </ul>
</details>

**Comment by turboMaCk** [comment]
thanks @PedroHLC I wonder if you tried to use it a bit more. I'm asking because we know many of these types of packages has issue on nix in that when installed to nix store they are generating code with wrong permissions. I just wonder if that's the case for graphql or not.

**Comment by PedroHLC** [comment]
> I wonder if you tried

Yeah, I actually used it yesterday, generated 4276 lines of Elm from my new schema.

**Review by turboMaCk — APPROVED** [review]
LGTM

**Review by turboMaCk — CHANGES_REQUESTED** [review]
Actually sorry. There is one more thing I just realized.

If I'm not mistaken the first commit on its own wont work because the 2nmd commit of regenerating node2nix files is required.

This means we need to **squash this PR into single commit** to follow the style-guide of nixpkgs.

**Review by turboMaCk — APPROVED** [review]

**Comment by turboMaCk** [comment]
Thanks a lot @PedroHLC. Great contribution!

**Pull request merged**
