### PR TITLE
compfy: init at 1.7.0; picom-allusive: remove

### PR DESCRIPTION
**Pull request by allusive-dev**
## Description of changes

picom-allusive has been renamed to compfy and therefore must be removed.
compfy was added at `v1.7.0`

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by davisrichard437** [comment]
##### Reviewed points

- [x] package name fits guidelines
- [x] package version fits guidelines
- [ ] package builds on x86_64-linux
- [ ] executables tested on x86_64-linux 
- [ ] all depending packages build

##### Fixes

Check out the [nixpkgs commit conventions](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions) and [those specific to the `pkgs` directory](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions). Your commits need to be re-done in some capacity so that logical units of changes are preserved and so that the names are consistent with `nixpkgs` conventions, e.g.

```
compfy: init at 1.7.0
picom-allusive: remove
```

The `compfy: init at 1.7.0` commit needs to include both the derivation and the reference to it in `all-packages.nix` to preserve the adding of that package within a single commit. The `picom-allusive: remove` commit (in addition to a message explaining why on the third line of the commit) needs to include the removal of the derivation, the removal of its reference in `all-packages.nix`, and an alias as described for [removing packages](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#deprecatingremoving-packages), e.g.

```nix
picom-allusive = throw "picom-allusive was renamed to compfy in November 2023"; # added 2023-11-17
```

It also didn't build on my system via `nixpkgs-review`, here are the logs:

    last 10 log lines:
    > remote: Counting objects: 100% (108/108), done.
    > remote: Compressing objects: 100% (102/102), done.
    > remote: Total 108 (delta 1), reused 69 (delta 0), pack-reused 0
    > Receiving objects: 100% (108/108), 426.11 KiB | 588.00 KiB/s, done.
    > Resolving deltas: 100% (1/1), done.
    > From https://github.com/allusive-dev/compfy
    >  * branch            HEAD       -> FETCH_HEAD
    > fatal: Not a valid object name
    > Unrecognized git object type:
    > Unable to checkout refs/tags/v1.7.0 from https://github.com/allusive-dev/compfy.git.

##### Possible improvements

Why do you pass a lambda to `mkDerivation`? I find it generally much cleaner to do `mkDerivation rec { ... }`. Is this a holdout from the picom override derivation? And is there a reason you don't still use the picom override pattern like the derivation you show in the [release notes](https://github.com/allusive-dev/compfy/releases/tag/1.7.0)?

Is there a reason that `meta.homepage` points to the picom repo and not to your `compfy` repo?

In `meta.platforms` you specify all, which is not true, picom and its forks should only run on linux.

I don't believe you need to specify `meta.mainProgram` when it's the same as the `pname`.

**Comment by allusive-dev** [comment]
@davisrichard437 
Hopefully my changes have fixed it.
I tested and the package does build now,
About your question with using `picom.overrideAttrs` still. I am splitting the program off from being related with Picom and so that being why I made a custom derivation.

**Comment by davisrichard437** [comment]
Note that there should be no reference to the removed package `picom-allusive` in `pkgs/top-level/all-packages.nix`, the alias with the `throw` directive should be in `pkgs/top-level/aliases.nix`. Otherwise, it builds just fine, binaries work, etc.

**Review by IogaMaster — APPROVED** [review]
LGTM

**Review by IogaMaster — CHANGES_REQUESTED** [review]
I think we should use pkgs/by-name as this will the standard in the future.
https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/README.md

**Comment by davisrichard437** [comment]
Looks good to me as well, still builds without issue

**Review by IogaMaster — APPROVED** [review]
Looks great!

**Comment by Philipp-M** [comment]
Any reason why this was closed?

**Pull request closed without merging**
