### PR TITLE
wayfire: 0.7.2 -> 0.7.4

### PR DESCRIPTION
**Pull request by nagy**
###### Description of changes

Changelog: https://github.com/WayfireWM/wayfire/releases/tag/v0.7.4

Relates to #151311 .

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wucke13** [comment]
It looks like `wcm` fails to build. Maybe it's missing `wlroots`?

```
error: builder for '/nix/store/yzcl3naa2iv5h3ws0p8n8vsq7lgkxrcg-wcm-0.7.0.drv' failed with exit code 1;
       last 10 log lines:
       > Run-time dependency wayfire found: NO
       >
       > meson.build:6:0: ERROR: Dependency lookup for wayfire with method 'pkgconfig' failed: Could not generate cargs for wayfire:
       > Package wlroots was not found in the pkg-config search path.
       > Perhaps you should add the directory containing `wlroots.pc'
       > to the PKG_CONFIG_PATH environment variable
       > Package 'wlroots', required by 'wayfire', not found
       >
       >
       > A full log can be found at /build/wcm-0.7.0/build/meson-logs/meson-log.txt
       For full logs, run 'nix log /nix/store/yzcl3naa2iv5h3ws0p8n8vsq7lgkxrcg-wcm-0.7.0.drv'.
error: 1 dependencies of derivation '/nix/store/kr7lymvy7qpcvdxl95gqwna1ld4xdqyd-wcm-0.7.0-wrapped.drv' failed to build
error: 2 dependencies of derivation '/nix/store/f39vh28mgcdngjmjrkifph53q97rx0g8-review-shell.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/203754

2 packages failed to build:
wayfireApplications-unwrapped.wcm wcm

4 packages built:
wayfire wayfirePlugins.wayfire wayfirePlugins.wf-shell wayfireApplications-unwrapped.wlroots

error: build log of '/nix/store/b8xfl0nr61y95z2g05jv6kinlyafw26k-wlroots-0.15.1.drv' is not available
error: build log of '/nix/store/kr7lymvy7qpcvdxl95gqwna1ld4xdqyd-wcm-0.7.0-wrapped.drv' is not available
error: build log of '/nix/store/8ckcnkbddilq5z0hrpnmnpalvywcrl5n-wcm-0.7.0-wrapped' is not available
$ /nix/store/81yi66w1q1spb27vp7blwbgb5myhwgjw-nix-2.11.0/bin/nix-shell /home/wucke13/.cache/nixpkgs-review/pr-203754-1/shell.nix
```

**Comment by nagy** [comment]
Thank you for noticing, but as a fix, I have rather just placed `wlroots` into `propagatedBuildInputs` of `wayfire` itself. This way, packages that depend on it get the correct (potentially overridden) version of it.

Also, since then wayfire 0.7.5 has been released, let me address that as well.

**Comment by nagy** [comment]
The update to 0.7.5 is a bit more involved and deserves its own PR.

**Comment by stephaneyfx** [comment]
May I help with this PR? I got `wayfire` 0.7.5 to build locally. If I should open a separate PR instead, please let me know.

**Pull request closed without merging**
