### PR TITLE
rio: 0.0.18 -> 0.0.19

### PR DESCRIPTION
**Pull request by otavio**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by oluceps** [comment]
Result of `nixpkgs-review pr 256123` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>rio</li>
    <li>rio.terminfo</li>
  </ul>
</details>

**Review by oluceps — APPROVED** [review]

**Comment by Nyabinary** [comment]
Solves #256113

**Comment by colemickens** [comment]
Does the app icon actually work for y'all? I can't tell if there's an expected format that it doesn't fit, or maybe `sirula` can't handle only-svg icons?

**Comment by colemickens** [comment]
It still shows per the screenshot in https://github.com/NixOS/nixpkgs/pull/252814. That's the launcher I use, `sirula`.

**Comment by otavio** [comment]
@colemickens please give this a try.

**Comment by colemickens** [comment]
@otavio I think the `install` command is wrong, it installed it as `.../rio.png/logo.png`

**Comment by otavio** [comment]
@colemickens indeed. Dropped the `-t` option. Seems good now.

**Comment by otavio** [comment]
@colemickens I fixed the file destination and file mode. Now it looks good.

**Review by thiagokokada — APPROVED** [review]

**Comment by colemickens** [comment]
I haven't tested this exact PR since I have my own vendored copy that I update with nix-update, but the app icon does work now. Thanks @otavio !

**Pull request merged**
