### PR TITLE
python38: 3.8.9 -> 3.8.10; python39: 3.9.4 -> 3.9.5; python310: 3.10.0a5 -> 3.10.0b2

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

CPython updates for python-unstable

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
Thank you. Seems like I missed an e-mail. Note this should target staging. Please also build all Python passthru tests.

**Comment by mweinelt** [comment]
Okay, thanks for the pointers. `python310.tests` fails like this.

```
==================================== ERRORS ====================================
__________________ ERROR collecting ast3/tests/test_basics.py __________________
ImportError while importing test module '/build/source/ast3/tests/test_basics.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/nix/store/hwaq99xsvx89y7p25njjq6nq2zm0qh9v-python3-3.10.0a5/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ast3/tests/test_basics.py:5: in <module>
    from typed_ast import _ast3
E   ImportError: /nix/store/pz8kk94jvxdz8y73qzx2pxi94p6f0rbf-python3.10-typed-ast-1.4.3/lib/python3.10/site-packages/typed_ast/_ast3.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyArena_AddPyObject
=========================== short test summary info ============================
ERROR ast3/tests/test_basics.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.16s ===============================
```

We wanted to do a python-unstable run, would it be appropriate to retarget to python-unstable, or should it go to staging?

**Comment by FRidh** [comment]
> We wanted to do a python-unstable run, would it be appropriate to retarget to python-unstable, or should it go to staging?

No need, patch releases seldom cause any trouble.

> Okay, thanks for the pointers. python310.tests fails like this. Looking into that later tonight.

That seem to be an upstream bug.

**Comment by SuperSandro2000** [comment]
@ofborg test python38 python39 python310

**Comment by FRidh** [comment]
3.10.0b3 is available now

**Comment by mweinelt** [comment]
```
Traceback (most recent call last):
  File "/nix/store/20xnnayviwdzxyjr7xyjq24wdpyplvj1-python3.10-pytest-6.2.3/bin/.py.test-wrapped", line 9, in <module>
    sys.exit(console_main())
  File "/nix/store/20xnnayviwdzxyjr7xyjq24wdpyplvj1-python3.10-pytest-6.2.3/lib/python3.10/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/nix/store/20xnnayviwdzxyjr7xyjq24wdpyplvj1-python3.10-pytest-6.2.3/lib/python3.10/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/nix/store/20xnnayviwdzxyjr7xyjq24wdpyplvj1-python3.10-pytest-6.2.3/lib/python3.10/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/nix/store/h6ab8g2lflx023z2lif9wpvc6n3zphaw-python3.10-pluggy-0.13.1/lib/python3.10/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/nix/store/h6ab8g2lflx023z2lif9wpvc6n3zphaw-python3.10-pluggy-0.13.1/lib/python3.10/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/nix/store/h6ab8g2lflx023z2lif9wpvc6n3zphaw-python3.10-pluggy-0.13.1/lib/python3.10/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/nix/store/h6ab8g2lflx023z2lif9wpvc6n3zphaw-python3.10-pluggy-0.13.1/lib/python3.10/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/nix/store/20xnnayviwdzxyjr7xyjq24wdpyplvj1-python3.10-pytest-6.2.3/lib/python3.10/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/nix/store/h6ab8g2lflx023z2lif9wpvc6n3zphaw-python3.10-pluggy-0.13.1/lib/python3.10/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/nix/store/h6ab8g2lflx023z2lif9wpvc6n3zphaw-python3.10-pluggy-0.13.1/lib/python3.10/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/nix/store/20xnnayviwdzxyjr7xyjq24wdpyplvj1-python3.10-pytest-6.2.3/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/nix/store/20xnnayviwdzxyjr7xyjq24wdpyplvj1-python3.10-pytest-6.2.3/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "/nix/store/20xnnayviwdzxyjr7xyjq24wdpyplvj1-python3.10-pytest-6.2.3/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1168, in _preparse
    self.pluginmanager.consider_preparse(args, exclude_only=False)
  File "/nix/store/20xnnayviwdzxyjr7xyjq24wdpyplvj1-python3.10-pytest-6.2.3/lib/python3.10/site-packages/_pytest/config/__init__.py", line 635, in consider_preparse
    self.consider_pluginarg(parg)
  File "/nix/store/20xnnayviwdzxyjr7xyjq24wdpyplvj1-python3.10-pytest-6.2.3/lib/python3.10/site-packages/_pytest/config/__init__.py", line 660, in consider_pluginarg
    self.import_plugin(arg, consider_entry_points=True)
  File "/nix/store/20xnnayviwdzxyjr7xyjq24wdpyplvj1-python3.10-pytest-6.2.3/lib/python3.10/site-packages/_pytest/config/__init__.py", line 713, in import_plugin
    self.register(mod, modname)
  File "/nix/store/20xnnayviwdzxyjr7xyjq24wdpyplvj1-python3.10-pytest-6.2.3/lib/python3.10/site-packages/_pytest/config/__init__.py", line 443, in register
    self.consider_module(plugin)
  File "/nix/store/20xnnayviwdzxyjr7xyjq24wdpyplvj1-python3.10-pytest-6.2.3/lib/python3.10/site-packages/_pytest/config/__init__.py", line 669, in consider_module
    self._import_plugin_specs(getattr(mod, "pytest_plugins", []))
  File "/nix/store/20xnnayviwdzxyjr7xyjq24wdpyplvj1-python3.10-pytest-6.2.3/lib/python3.10/site-packages/_pytest/config/__init__.py", line 676, in _import_plugin_specs
    self.import_plugin(import_spec)
  File "/nix/store/20xnnayviwdzxyjr7xyjq24wdpyplvj1-python3.10-pytest-6.2.3/lib/python3.10/site-packages/_pytest/config/__init__.py", line 703, in import_plugin
    __import__(importspec)
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/nix/store/20xnnayviwdzxyjr7xyjq24wdpyplvj1-python3.10-pytest-6.2.3/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 161, in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
  File "/nix/store/20xnnayviwdzxyjr7xyjq24wdpyplvj1-python3.10-pytest-6.2.3/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 356, in _rewrite_test
    co = compile(tree, fn_, "exec", dont_inherit=True)
TypeError: required field "lineno" missing from alias
checking for finitel declaration... yes
builder for '/nix/store/5zfn4w2n1i8ij2lg5z44zpy38ycjzfqn-python3.10-pytest-6.2.3.drv' failed with exit code 1
error: build of '/nix/store/5zfn4w2n1i8ij2lg5z44zpy38ycjzfqn-python3.10-pytest-6.2.3.drv' on 'ssh://hexa@phoibe.cysec.de' failed: builder for '/nix/store/5zfn4w2n1i8ij2lg5z44zpy38ycjzfqn-python3.10-pytest-6.2.3.drv' failed with exit code 1
```

**Comment by FRidh** [comment]
Just ignore 3.10, its still beta and pytest probably needs to be fixed for it anyway.

**Comment by mweinelt** [comment]
Okay, ignoring `python310.tests`, which is I think what you meant.

**Comment by jonringer** [comment]
@GrahamcOfBorg build python39Packages.requests
@GrahamcOfBorg build python310Packages.requests
@GrahamcOfBorg build python38Packages.requests

**Comment by mweinelt** [comment]
@GrahamcOfBorg build python38.tests python39.tests

**Review by jonringer — APPROVED** [review]

**Comment by VergeDX** [comment]
@mweinelt Python 3.10.0 stable is now released! Time for packaging : )

**Comment by mweinelt** [comment]
> @mweinelt Python 3.10.0 stable is now released! Time for packaging : )

https://github.com/NixOS/nixpkgs/pull/136254

**Pull request merged**
