### PR TITLE
tree-sitter: Update grammars and add markdown-inline

### PR DESCRIPTION
**Pull request by jocelynthode**
###### Description of changes

Update tree-sitters grammars and add the split for markdown and markdown-inline mentioned in https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1166574954

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

@Profpatsch @oxalica

### CODE REVIEW

**Comment by jocelynthode** [comment]
@Profpatsch @oxalica

**Comment by SuperSandro2000** [comment]
Do we need to change the vala parser https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1179553091 ?

**Comment by jocelynthode** [comment]
It seems not all parsers are present in this nix package. We should probably write a script or something to automatically retrieve the list from here: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/parsers.lua and make it match with the lock file here https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lockfile.json so that we always use the correct parsers for a given tree-sitter rev.

I could work on this but I might need support as I'm quite new to the nix environment.

**Comment by SuperSandro2000** [comment]
Sounds like a good idea. The best place to ask questions is probably matrix.

**Pull request merged**
