### PR TITLE
nodePackages: init hsd, hs-airdrop, hs-client

### PR DESCRIPTION
**Pull request by d-xo**
##### Motivation for this change

This adds a few tools related to the [`handshake`](https://handshake.org) decentralized naming system.

The following tools are added:

- [`hsd`](https://github.com/handshake-org/hsd)
- [`hs-client`](https://github.com/handshake-org/hs-client)
- [`hs-airdrop`](https://github.com/handshake-org/hs-airdrop)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by midchildan — CHANGES_REQUESTED** [review]
The code looks good, but the commits should be separated for each new package you introduce to fit [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md). Since regenerating `nodePackages` would take a lot of time, you can just recreate the commits without changing the contents of this PR itself:

```sh
git reset --mixed HEAD~ # undos the commit without changing the working tree
git add pkgs/development/node-packages/default.nix
git add -p pkgs/development/node-packages/node-packages.json # add hsd
git commit -m "nodePackages.hsd: init at 2.2.0"
git add -p pkgs/development/node-packages/node-packages.json # add hs-airdrop
git commit -m "nodePackages.hs-airdrop: init at 0.9.0"
git add -p pkgs/development/node-packages/node-packages.json # add hs-client
git commit -m "nodePackages.hs-client: init at 0.0.9"
git add pkgs/development/node-packages/node-packages.nix
git commit -m "nodePackages: update"
git push -f
```

**Comment by xwvvvvwx** [comment]
Updated commits and rebaed on master. Thanks for the help!!

**Review by midchildan — APPROVED** [review]
LGTM

**Comment by xwvvvvwx** [comment]
rebased on master, would be great to get this merged...

**Review by midchildan — APPROVED** [review]
It sometimes helps to leave a comment here when your PR gets buried:

https://discourse.nixos.org/t/prs-already-reviewed/2617

**Comment by AndersonTorres** [comment]
This is a huge diff! I am a bit afraid of it.

**Comment by midchildan** [comment]
Unfortunately, this is unavoidable due to the way node packaging is done in nixpkgs. The source of the huge diff is `node-packages.nix`, which is generated automatically by this script here: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/node-packages/generate.sh

**Comment by AndersonTorres** [comment]
Well, if nothing can be done...

**Comment by dotlambda** [comment]
@d-xo What's the purpose of having hs-client in nixpkgs. It's only a JS library.

**Pull request merged**
