### PR TITLE
libraw_unstable: remove

### PR DESCRIPTION
**Pull request by wineee**
###### Description of changes
After libraw is upgraded, freeimage no longer needs the unstable version

No other application  depend on libraw_unstable，so I think it should be removed

Related：
https://github.com/NixOS/nixpkgs/pull/213120
https://github.com/NixOS/nixpkgs/pull/151592

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wineee** [comment]
@ofborg build freeimage

**Review by superherointj — APPROVED** [review]
Changes look straight forward to me.

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 213518` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>inkcut</li>
    <li>inkscape-extensions.inkcut</li>
    <li>python310Packages.enamlx</li>
    <li>python310Packages.pythonocc-core</li>
    <li>python311Packages.enamlx</li>
    <li>python311Packages.pythonocc-core</li>
    <li>slade</li>
    <li>sladeUnstable</li>
  </ul>
</details>
<details>
  <summary>35 packages built:</summary>
  <ul>
    <li>arrayfire</li>
    <li>cegui</li>
    <li>colmap</li>
    <li>colmapWithCuda</li>
    <li>deepin.deepin-calculator</li>
    <li>deepin.dtkgui</li>
    <li>deepin.dtkwidget</li>
    <li>deepin.image-editor</li>
    <li>deepin.qt5integration</li>
    <li>elmerfem</li>
    <li>emulationstation</li>
    <li>forge</li>
    <li>freeimage</li>
    <li>gamecube-tools</li>
    <li>horizon-eda</li>
    <li>imv</li>
    <li>megacmd</li>
    <li>megasync</li>
    <li>ogre</li>
    <li>ogre1_10</li>
    <li>ogre1_9</li>
    <li>ogrepaged</li>
    <li>opencascade</li>
    <li>opendungeons</li>
    <li>openxray</li>
    <li>perceptualdiff</li>
    <li>pgf_graphics</li>
    <li>posterazor</li>
    <li>python310Packages.mahotas</li>
    <li>python311Packages.mahotas</li>
    <li>rigsofrods</li>
    <li>rucksack</li>
    <li>smesh</li>
    <li>stuntrally</li>
    <li>trenchbroom</li>
  </ul>
</details>

**Comment by wegank** [comment]
Looks like this could target master?

**Comment by beh-10257** [comment]
sorry but well I want to upgrade my system
image

and i don't really know how to find out what pkg exactly depends on it so I cna delete it or something

**Comment by wegank** [comment]
Wrong thread, #280835 is the culprit. (Also `--show-trace` should help)

**Pull request merged**
