### PR TITLE
[staging]: nss + cacert -> 3.60

### PR DESCRIPTION
**Pull request by ajs124**
###### Motivation for this change
Upstream release: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_3.60_release_notes

It has a bunch of CA changes, so I bumped cacert as well. This can (easily) be split in two PRs if necessary.

Firefox 83 still at least compiles with this, I haven't tested if it runs.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by TredwellGit — APPROVED** [review]
I rebuilt my personal system with this.
Should be labeled security and backported since certificate authority certificates were removed.

**Comment by andir** [comment]
Please test that firefox-esr & thunderbird are still working with this.
Those have been the usual candidates that fail on NSS bumps.

**Comment by ajs124** [comment]
I thought esr uses an older nss for exactly that reason?

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/blob/ec2fa1cee81d06d90b88b8e298d1561125df6949/pkgs/applications/networking/browsers/firefox/common.nix#L110
https://github.com/NixOS/nixpkgs/blob/ec2fa1cee81d06d90b88b8e298d1561125df6949/pkgs/applications/networking/mailreaders/thunderbird/default.nix#L123

**Review by vcunat — APPROVED** [review]
All sounds good.

**Comment by ajs124** [comment]
As Firefox 84 is released now, we might want to merge the nss part of this and the new firefox, assuming it requires that nss, to master and only going through staging with cacert.

**Comment by vcunat** [comment]
Probably not.  84 is said to be paired to 3.59.  Their calendar now gives about a month of space between NSS release and the corresponding FF release: https://wiki.mozilla.org/NSS:Release_Versions

**Pull request merged**
