### PR TITLE
Kernels 2021-08-15

### PR DESCRIPTION
**Pull request by TredwellGit**
###### Things done
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabianhjr** [comment]
Diff LGTM, building 5.13.11

**Review by fabianhjr — APPROVED** [review]
Built and booted into 5.13.11

**Review by Ma27 — APPROVED** [review]

**Comment by Ma27** [comment]
Wait, did we forget an older change? Will take care of this tomorrow unless somebody is faster.

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/pull/133640

**Pull request merged**
