### PR TITLE
john: build with recent gcc

### PR DESCRIPTION
**Pull request by Mic92**
###### Motivation for this change

john the ripper contains a patch for gcc >= 5 and builds fine. I am not sure why this was pinned in the first place.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
aarch64 failure is unrelated, I couldn't find any successful hydra build on aarch64 (looking back to March 2017). So let's exclude aarch64 for now.

**Comment by Mic92** [comment]
@GrahamcOfBorg build john

**Comment by xeji** [comment]
why did it try aarch64 again?

**Comment by Mic92** [comment]
@GrahamcOfBorg build john

**Pull request merged**
