### PR TITLE
home-assistant: add support for python_script component

### PR DESCRIPTION
**Pull request by oneingan**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @dotlambda

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
Is the commit history messed up? looks like your first commit tries to add the package that doesnt exist yet

**Comment by juaningan** [comment]
I make the package and run parse_requirements.py locally both, and then make 2 commits. The result is ok. Then only mess is now, rerunning  parse_requirementes.py add python-vlc. I think somebody forget to run it in another PR.

**Comment by jonringer** [comment]
hmm, very possible

**Comment by juaningan** [comment]
Is there something I can do to merge this?

**Comment by peterhoeg** [comment]
Looks good!

**Pull request merged**
