### PR TITLE
github-runner: 2.307.1 -> 2.308.0

### PR DESCRIPTION
**Pull request by veehaitch**
* Update runner to v2.308.0
* Use Node 20 by default
* Allow building with Node 16 support through `nodeRuntimes` argument
* add `nodeRuntimes` option to NixOS module

It's important to have an easy optin for Node 16 since quite many GitHub actions (explicitly) rely on Node 16. It probably will take some time until most switch to Node 20. Note that it's also not an option to tell those who need Node 16 support to continue to use an older version since GitHub removes support for previous releases quite quickly.

**Tested with `nodeRuntimes = [ "node16" "node20" ]` and a simple Node 20 action**

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by domenkozar** [comment]
aarch64-linux:

```
Failed GitHub.Runner.Common.Tests.Worker.StepHostL0.DetermineNode20RuntimeVersionInAlpineContainerAsync [6 ms]
  Error Message:
   System.NotSupportedException : JavaScript Actions in Alpine containers are only supported on x64 Linux runners. Detected Linux Arm64
  Stack Trace:
     at GitHub.Runner.Worker.Handlers.ContainerStepHost.CheckPlatformForAlpineContainer(IExecutionContext executionContext, String preferredVersion) in /build/src/src/Runner.Worker/Handlers/StepHost.cs:line 273
   at GitHub.Runner.Worker.Handlers.ContainerStepHost.DetermineNodeRuntimeVersion(IExecutionContext executionContext, String preferredVersion)
   at GitHub.Runner.Common.Tests.Worker.StepHostL0.DetermineNode20RuntimeVersionInAlpineContainerAsync() in /build/src/src/Test/L0/Worker/StepHostL0.cs:line 105
--- End of stack trace from previous location ---
```

**Comment by matthiasbeyer** [comment]
Result of `nixpkgs-review pr 249103` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>github-runner</li>
  </ul>
</details>

**Review by newAM — APPROVED** [review]
I think `withNode16` should be set to true so that it works as-expected out of the box, but I can understand wanting to remove the insecure package warning.

**Comment by veehaitch** [comment]
I'm also fine with making it the default. If not, we could at least add a new module option to give it more visibility?

**Comment by veehaitch** [comment]
I decided to go with an option `nodeRuntimes` which accepts a list of Node.js runtime strings supported by upstream. That way, we can just update the list of accepted option values.

**Review by newAM — APPROVED** [review]

**Comment by flurie** [comment]
> Note that the usefulness of withNode16 = false (the default) is severely limited at the moment. [Not even checking out a repository will work](https://github.com/actions/checkout/blob/96f53100ba2a5449eb71d2e6604bbcd94b9449b5/action.yml#L87).

If we're introducing what is, practically speaking, a breaking change, why are we making it the default option? Should we not default to `node16`?

And is there anything else holding this up? The GitHub runner release schedule is fairly aggressive, and I'd rather not let us get to a point where unstable is packaging a runner that will not work.

**Review by zimbatm — APPROVED** [review]
Thanks, looks reasonable given that Node 16 is deprecated.

**Comment by domenkozar** [comment]
@veehaitch is there any reason why we wouldn't support both node runtimes by default? 

I imagine most actions will run with either, so that makes a better default.

**Comment by veehaitch** [comment]
AFAIK, CI won't test the build

**Comment by domenkozar** [comment]
@veehaitch I'm not sure I understand, which CI?

**Comment by veehaitch** [comment]
ofBorg

**Pull request merged**
