### PR TITLE
libow: init at 3.2p1

### PR DESCRIPTION
**Pull request by divi255**
###### Motivation for this change

libow 1-wire file system library (owfs) package

includes libraries and headers only

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by divi255** [comment]
libow 1-wire file system library (owfs) package

includes libraries and headers only

**Comment by volth** [comment]
@GrahamcOfBorg build libow

**Review by matthiasbeyer — CHANGES_REQUESTED** [review]
Please split your changes into two commits:

1. Adding yourself as maintainer
1. Adding the package

**Comment by divi255** [comment]
> Please split your changes into two commits:
> 
> 1. Adding yourself as maintainer
> 2. Adding the package

Done

**Comment by matthiasbeyer** [comment]
Now the commit where you add the package does not confirm to the [CONTRIBUTING](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes) anymore.

Sorry for bothering you with this, but as you seem to be new I try to show you how to do it right so that people do not have to tell you later :smile:

**Comment by divi255** [comment]
> Now the commit where you add the package does not confirm to the [CONTRIBUTING](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes) anymore.
> 
> Sorry for bothering you with this, but as you seem to be new I try to show you how to do it right so that people do not have to tell you later 😄

Done )

**Review by matthiasbeyer — APPROVED** [review]

**Review by tomberek — APPROVED** [review]
builds, links, on non-NixOS, no reverse-dependencies
New maintainer.
Previously approved by @matthiasbeyer 
LGTM

**Review by srhb — CHANGES_REQUESTED** [review]
@divi255 Thank you for your contribution! I'm sorry to hold this up just a tiny bit, but I noticed that at the top of the sourceforge page, there's a note: "Project moved to https://github.com/owfs/owfs/"

SourceForge as a distribution source for this package thus appears to be deprecated. Using the new source would allow us to also utilize the `fetchFromGitHub` helper function to grab the newest release (v3.2p3) that is made available on GitHub as well.

**Comment by divi255** [comment]
Good day,

I see but 3.2p1 is the only production release used by other distributions (the package was actually ported from Arch, while Ubuntu is still on 3.1.x). If you want I can change source to github right now, however I suggest to keep 3.2p1 version until the new one get a positive feedback (at least for x86-64 and ARM). Unfortunately I'm not a software author (but heavy user :) and can't give any warranties about new versions.

So, let's change source to github right now or when versions never than 3.2p1 go in production? What do you prefer?

**Comment by srhb** [comment]
@divi255 Since you're way more of an expert than me on this piece of software, I defer to your opinion. Let's go with the github source using `fetchFromGitHub` but keep the version. :)

**Comment by divi255** [comment]
> @divi255 Since you're way more of an expert than me on this piece of software, I defer to your opinion. Let's go with the github source using `fetchFromGitHub` but keep the version. :)

Changed to use github and fetchFromGitHub . Seems to work fine )

**Comment by divi255** [comment]
@GrahamcOfBorg build libow

**Comment by volth** [comment]
@GrahamcOfBorg build libow

**Review by srhb — APPROVED** [review]

**Comment by srhb** [comment]
Thank you!

**Pull request merged**
