### PR TITLE
pythonPackages.tiledb: init at 0.4.2

### PR DESCRIPTION
**Pull request by Rakesh4G**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @CMCDragonkai

### CODE REVIEW

**Comment by Rakesh4G** [comment]
Hi @CMCDragonkai , I will move this PR to ready for review once tiledb core library is merged to nixpkgs.

**Comment by Rakesh4G** [comment]
Redundant now as higher version already available.
https://github.com/avitex/nixpkgs/pull/3565

**Comment by CMCDragonkai** [comment]
Where is the PR for that?

**Comment by Rakesh4G** [comment]
> Where is the PR for that?

Hi @CMCDragonkai , This is merged under this PR https://github.com/avitex/nixpkgs/pull/3565

**Comment by CMCDragonkai** [comment]
Did that solve the test problems we had with this MR? Or are the tests only problematic on AMD + ZFS systems?

On 28 November 2019 16:22:01 GMT+11:00, Rakesh Gupta <notifications@github.com> wrote:
>> Where is the PR for that?
>
>Hi @CMCDragonkai , This is merged under this PR
>https://github.com/avitex/nixpkgs/pull/3565
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/NixOS/nixpkgs/pull/66900#issuecomment-559346463

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request closed without merging**
