### PR TITLE
osquery: 5.5.1 -> 5.12.2

### LINKED ISSUE #314117: Update request: OSquery 5.5.1 → 5.12.1
- Package name: `osquery`
- Latest released version: `5.12.1`

- Current version on the unstable channel: `5.5.1`
- Current version on the stable/release channel: `5.5.1`

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
/cc @znewman01 @lewo

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by squalus**
## Description of changes
- Update to 5.12.2
- Switch to the upstream supported osquery-toolchain
- Upstream binaries for the toolchain were used. Efforts to reproduce the upstream toolchain from source were unsuccessful. Future work could involve building this from source.
- Efforts to use a newer toolchain provided by nixpkgs were unsuccessful. osquery assumes that osquery-toolchain and its included LLVM 9 compiler and libraries are available. LLVM 9 is no longer present in nixpkgs.
- Remove patches that are no longer necessary
- Use the exact version of openssl provided by upstream. This was necessary due to build errors when using the nixpkgs openssl package.
- Add code that will fail the build if the openssl hashes from the fetcher do not match what upstream expects

Fixes #314117

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by JohnRTitor** [comment]
Result of `nixpkgs-review pr 320566` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>osquery</li>
  </ul>
</details>

**Comment by JohnRTitor** [comment]
Logs.

<details>

```log
┏━ 1 Errors: 
┃ error: builder for '/nix/store/k806ckwsfn533z4948mbbmfmn11566q1-source.drv' failed with exit code 1;
┃        last 25 log lines:
┃        > remote: Total 743 (delta 121), reused 339 (delta 51), pack-reused 0
┃        > Receiving objects: 100% (743/743), 2.36 MiB | 431.00 KiB/s, done.
┃        > Resolving deltas: 100% (121/121), done.
┃        > Cloning into '/nix/store/dvb0lbmry9qf1yhh379gyb5iy2ndg3d5-source/libraries/cmake/source/util-linux/src'...
┃        > remote: Enumerating objects: 3210, done.
┃        > remote: Counting objects: 100% (3210/3210), done.
┃        > remote: Compressing objects: 100% (2703/2703), done.
┃        > remote: Total 3210 (delta 434), reused 1746 (delta 181), pack-reused 0
┃        > Receiving objects: 100% (3210/3210), 12.08 MiB | 1.21 MiB/s, done.
┃        > Resolving deltas: 100% (434/434), done.
┃        > Cloning into '/nix/store/dvb0lbmry9qf1yhh379gyb5iy2ndg3d5-source/libraries/cmake/source/libcryptsetup/src'...
┃        > remote: Enumerating objects: 553, done.
┃        > remote: Counting objects: 100% (553/553), done.
┃        > remote: Compressing objects: 100% (502/502), done.
┃        > remote: Total 553 (delta 112), reused 368 (delta 49), pack-reused 0 (from 0)
┃        > Receiving objects: 100% (553/553), 11.35 MiB | 580.00 KiB/s, done.
┃        > Resolving deltas: 100% (112/112), done.
┃        > Cloning into '/nix/store/dvb0lbmry9qf1yhh379gyb5iy2ndg3d5-source/libraries/cmake/source/librdkafka/src'...
┃        > fatal: could not read Username for 'https://github.com': No such device or address
┃        > fatal: clone of 'https://github.com/edenhill/librdkafka' into submodule path '/nix/store/dvb0lbmry9qf1yhh379gyb5iy2ndg3d5-source/libraries/cmake/source/librdka…
┃        > Failed to clone 'libraries/cmake/source/librdkafka/src'. Retry scheduled
┃        > Cloning into '/nix/store/dvb0lbmry9qf1yhh379gyb5iy2ndg3d5-source/libraries/cmake/source/librdkafka/src'...
┃        > fatal: could not read Username for 'https://github.com': No such device or address
┃        > fatal: clone of 'https://github.com/edenhill/librdkafka' into submodule path '/nix/store/dvb0lbmry9qf1yhh379gyb5iy2ndg3d5-source/libraries/cmake/source/librdka…
┃        > Failed to clone 'libraries/cmake/source/librdkafka/src' a second time, aborting
┃        For full logs, run 'nix log /nix/store/k806ckwsfn533z4948mbbmfmn11566q1-source.drv'.
```

</details>

**Comment by squalus** [comment]
From the failure log:

```
fatal: could not read Username for 'https://github.com': No such device or address
```
Is this something to do with the configuration of the machine running nixpkgs-review?

The build worked here: https://logs.ofborg.org/?key=nixos/nixpkgs.320566&attempt_id=3e25a160-16e6-4b66-8ce6-93a0d37d7b59

**Comment by JohnRTitor** [comment]
yeah, something went wrong in my builder. Looks fine now.

@RossComputerGuy this still uses LLVM 9 toolchain (provided by upstream repo), could you take a look?

**Comment by JohnRTitor** [comment]
Result of `nixpkgs-review pr 320566` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>osquery</li>
  </ul>
</details>

**Review by RossComputerGuy — APPROVED** [review]
Result of `nixpkgs-review` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>osquery</li>
  </ul>
</details>

i approb

**Review by JohnRTitor — APPROVED** [review]
LGTM

**Comment by cig0** [comment]
TYVM :pray:

**Pull request merged**
