### PR TITLE
gtk3: 3.24.17 -> 3.24.18

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change
GTK 3.24.17 has a critical issue which breaks many applications under Wayland. This issue was fixed in 3.24.18.

cc. @jtojnar @worldofpeace for review
cc. @FRidh for inclusion into the current staging merge

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lovesegfault** [comment]
I'm about halfway through building all the changed pkgs.

**Comment by lovesegfault** [comment]
World rebuild was fine, I've been running this for a couple days and it's working normally.

It's ready to go.

**Comment by worldofpeace** [comment]
@lovesegfault Are you sure, ofborg shows a build with a patch failing to apply
```
source root is gtk+-3.24.18
setting SOURCE_DATE_EPOCH to timestamp 1586475563 of file gtk+-3.24.18/build/win32/vs16/gtk3-version-paths.props
patching sources
applying patch /nix/store/aq2pv5ijchrhhk07lhmcscdjw8babgph-3.0-immodules.cache.patch
patching file gtk/deprecated/gtkrc.c
Hunk #1 succeeded at 774 with fuzz 1.
applying patch /nix/store/f0brcnzizhmn58nw3sdzcdaqgmfqfl1k-Xft-setting-fallback-compute-DPI-properly.patch
patching file gdk/x11/gdkxftdefaults.c
applying patch /nix/store/1g3l5z56gvj9z61f72p13n6x43ymz48m-01-build-Fix-path-handling-in-pkgconfig.patch
patching file meson.build
Hunk #1 succeeded at 852 (offset 18 lines).
applying patch /nix/store/3zvj1qhvakcmr4fnivsdczdgqjw51yrb-79732da1ed8cb167440fb047c72cfc0d888a187b.patch
patching file gdk/wayland/gdkwindow-wayland.c
Hunk #1 FAILED at 1635.
1 out of 1 hunk FAILED -- saving rejects to file gdk/wayland/gdkwindow-wayland.c.rej
builder for '/nix/store/lmkm9px8zmlr94m4hqyk9mj1a2jcs1gw-gtk+3-3.24.18.drv' failed with exit code 1
```

**Comment by lovesegfault** [comment]
Oh, I rebased and now it fails; investigating.

**Comment by lovesegfault** [comment]
@worldofpeace Fixed, removed patches that were already incorporated into this release

**Comment by worldofpeace** [comment]
> @worldofpeace Fixed, removed patches that were already incorporated into this release

Perfect, thanks @lovesegfault :sparkles:

**Pull request merged**
