### PR TITLE
pash: remove

### PR DESCRIPTION
**Pull request by mdarocha**
## Description of changes

The project is archived since 2019: https://github.com/pash-project/pash

And PowerShell is now fully cross-platform, removing any need for that package.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
I don't know why I was called. This is not my package.
But this is an easy removal with good arguments.

**Comment by AndersonTorres** [comment]
@mdarocha can you please backport this manually?

**Comment by mdarocha** [comment]
@AndersonTorres is backporting a package removal something that should be done? https://gist.github.com/grahamc/c60578c6e6928043d29a427361634df6#what-to-backport

**Comment by AndersonTorres** [comment]
- I believe removals should be backported. Removing old and unmaintained software is good for a "long term support" release

- pash is archived since 2019; therefore this modification in nixpkgs is at least 4 years and 8 releases too late.

- since it is so old and unmaintained, it can be considereded a security concern, and security concerns are covered by backporting guidelines

- powershell is supported by Nixpkgs since the latest stable, therefore people on stable channel can update their workflows to use powershell instead of pash

**Pull request merged**
