### PR TITLE
more vim plugins

### PR DESCRIPTION
**Pull request by KAction**
staging

### CODE REVIEW

**Comment by KAction** [comment]
Looks like CI did not re-run some tests after I rebased to staging. Anything I can do about it?

**Comment by Mic92** [comment]
CI regularly times out on staging because of mass-rebuilds. Any reason you target staging for vim plugins? Usually we just merge them into master.

**Comment by KAction** [comment]
Didn't known, will rebase on master. Just followed general logic that many rebuilds => staging.

**Comment by Mic92** [comment]
Vim plugins are very cheap to build, so master is preferred since would otherwise cause merging conflicts.

**Comment by KAction** [comment]
@Mic92 Rebased on master

**Pull request merged**
