### PR TITLE
mpv-unwrapped: 0.34.1 -> 0.35.0

### PR DESCRIPTION
**Pull request by SuperSandro2000**
Co-authored-by: adisbladis <adisbladis@gmail.com>

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@ofborg build mpv-unwrapped

**Comment by AndersonTorres** [comment]
Darwin is happy.

**Comment by Atemu** [comment]
Why should this be backported? It's pretty large release with lots of potential for breakage. That shouldn't go to stable, especially not this late in the support cycle.

**Comment by AndersonTorres** [comment]
> Why should this be backported?

Because many people use it.

Indeed you yourself suggested that Meson support should be postponed, because the breakage on Darwin was unnacceptable.

> That shouldn't go to stable, especially not this late in the support cycle.

The legacy(?) waf was building it OK. It looks like a good enough reason to a backport, given that it doesn't introduce breaking changes.

Nonetheless the backport bot failed. I will not pursue it further.

**Comment by Atemu** [comment]
I do not mean the build system change, I mean the feature changes.

MPV has had lots of changes since its last release, some of which are breaking. Stable should not receive breaking changes unless there are very good reasons (i.e. security issues).  
Feature updates on stable, while allowed, are not in any way necessary or required; even for popular packages.

See https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#criteria-for-backporting-changes

**Comment by AndersonTorres** [comment]
> MPV has had lots of changes since its last release, some of which are breaking.

Not so much, I would argue. But, as I have said, I will not pursue it further.

> Feature updates on stable, while allowed, are not in any way necessary or required; even for popular packages.

They aren't prohibited either. The only semblance of a hard prohibition is about breaking changes.

> See https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#criteria-for-backporting-changes

I will wait a Portuguese translation. Thanks.

**Comment by OPNA2608** [comment]
This borked MPV for me: https://github.com/mpv-player/mpv/issues/10859 (this was linked in the original PR https://github.com/NixOS/nixpkgs/pull/200914#issuecomment-1312827576)

```console
$ mpv path/to/file.ogg
 (+) Audio --aid=1 (vorbis 2ch 44100Hz)
[ao/pipewire] Could not connect to context '(null)': Host is down!
'!impl->polling' failed at ../spa/plugins/support/loop.c:872 impl_clear()
fish: Job 1, 'mpv path/to/file.ogg' terminated by signal SIGABRT (Abbruch)
```

I'm not using pipewire on my system, so I assume the new `pipewireSupport ? stdenv.isLinux` is causing this.

**Comment by Ma27** [comment]
> Looks like an absolute win to me.

The thing is, it isn't nixpkgs's sole responsibility to be up-to-date. If things have to be sorted out, nobody is hurt if we wait for a few days. In fact, people seem to have problems with it now.

> I will wait a Portuguese translation. Thanks.

Your way of communicating with other maintainers here and the fact that you openly ignore our contribution guidelines seems fairly problematic to me: first of all, if you don't care, why do you even have commit access? Also, what are regular (or drive-by) contributors supposed to think of that?

**Comment by AndersonTorres** [comment]
> The thing is, it isn't nixpkgs's sole responsibility to be up-to-date.

Until that point, the version bump (without the meson part) was working as expected. Indeed I suggested to not bump meson immediately and open a pull request only for the meson part; only after many unacceptable bugs being found the PR was split.

> If things have to be sorted out, nobody is hurt if we wait for a few days. 

I aggree. I should not have acted so hasty.

> In fact, people seem to have problems with it now.

The bug was found now. Certainly I have a portion of guilt by this, however the bug was somehow unexpected.

> Your way of communicating with other maintainers here

Linking the CONTRIBUTING.md file to me was a clear act of debauchery. I responded accordingly.

> and the fact that you openly ignore our contribution guidelines

Allow me a brief disagreement. 

I have not ignored the guidelines - quite the opposite, I have argued all the time that I was following the guidelines. (Further, linking the backport guidelines to me when I was arguing about the backporting guidelines is raw mockery, remind that.)

I even conceded the part about breaking changes and ceased to pursue the issue further.

Recapitulating, I was specifically arguing about backporting MPV, exposing why I have labeled this "worthy of backport". As I have said before, I have read the backporting criteria section, and I judged that there was no impediments; so I give it a shot.

> if you don't care, why do you even have commit access?

I do care.

> Also, what are regular (or drive-by) contributors supposed to think of that?

I have exposed my points above.

**Comment by AndersonTorres** [comment]
> I'm not using pipewire on my system, so I assume the new `pipewireSupport ? stdenv.isLinux` is causing this.

About this specifically, have you tried to force another output? I will upload a patch to render this option false by default.

**Comment by SuperSandro2000** [comment]
> I'm not using pipewire on my system, so I assume the new `pipewireSupport ? stdenv.isLinux` is causing this.

According to the thread this should be fixed for pipewire 0.3.60 which is in staging-next right now.

**Comment by Atemu** [comment]
@SuperSandro2000 Will that hit master before branch-off?

**Comment by OPNA2608** [comment]
> About this specifically, have you tried to force another output?

Yes, `--ao=pulse`works.

> According to the thread this should be fixed for pipewire 0.3.60 which is in staging-next right now.

After an hour of building stuff with the bump cherry-picked it does fix the failing assertion & SIGABRT, so we can just wait 3 days for the merge.

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 Will that hit master before branch-off?

yes, it should be the last staging run before branch-off IIRC.

**Pull request merged**
