### PR TITLE
python3Packages.dependency-injector: 4.32.2 -> 4.34.0

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 4.34.0

Change log: https://github.com/ets-labs/python-dependency-injector/blob/master/docs/main/changelog.rst#4340

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 129025` at 864f86e5 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/d66ee09de1f86cae103693367f7a7e89">dyndnsc</a></li>
    <li><a href="https://gist.github.com/9e93d5cf46a0e125c48f464683e8f343">python38Packages.dependency-injector</a></li>
    <li><a href="https://gist.github.com/3b4346d117733763375c7f5cf03a0c69">python38Packages.fastapi</a></li>
    <li><a href="https://gist.github.com/8f26c36a442ed0fdfd5ea27371feac12">python38Packages.json-logging</a></li>
    <li><a href="https://gist.github.com/567b0ee0325e26771a6a6395eabe98ad">python38Packages.starlette</a></li>
    <li><a href="https://gist.github.com/41d080040b6092ed260dc584e754783f">python39Packages.dependency-injector</a></li>
    <li><a href="https://gist.github.com/8311e6d5911ccd128848677924ceee4c">python39Packages.fastapi</a></li>
    <li><a href="https://gist.github.com/2b07eacee40b8caf4fb8fbb63762ab28">python39Packages.json-logging</a></li>
    <li><a href="https://gist.github.com/6c09e229f1c2029bcdb5fb35548f3147">python39Packages.starlette</a></li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.graphene</li>
    <li>python39Packages.graphene</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by risicle** [comment]
Yup, this is all failing due to a broken `starlette` right now.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 129025` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>esphome</li>
    <li>platformio</li>
  </ul>
</details>
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>dyndnsc</li>
    <li>python38Packages.dependency-injector</li>
    <li>python38Packages.fastapi</li>
    <li>python38Packages.graphene</li>
    <li>python38Packages.json-logging</li>
    <li>python38Packages.starlette</li>
    <li>python39Packages.dependency-injector</li>
    <li>python39Packages.fastapi</li>
    <li>python39Packages.graphene</li>
    <li>python39Packages.json-logging</li>
    <li>python39Packages.starlette</li>
  </ul>
</details>

**Comment by fabaff** [comment]
`platformio` fails to build because of `aiofiles` update.

**Pull request merged**
