### PR TITLE
r-pbdZMQ: fix Darwin install

### PR DESCRIPTION
**Pull request by mnacamura**
###### Motivation for this change

In pbdZMQ installation on Darwin, src/install.libs.R invokes `which install_name_tool` and `which otool`, and this causes failure.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] ~~Tested execution of all binary files (usually in `./result/bin/`)~~
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
You can probably get around the patch by just adding "which" as a native build input for it. Like in BiocCheck:

https://github.com/mnacamura/nixpkgs/blob/e9e09b1305de64b9c02a4719a2428f9c8ef5df45/pkgs/development/r-modules/default.nix#L239

**Comment by mnacamura** [comment]
Thanks @matthewbauer for your suggestion. That's better!

I could not figure out how to rebase a branch that has already been pull-requested so I opened another PL https://github.com/NixOS/nixpkgs/pull/27374.

**Comment by LnL7** [comment]
FYI. you can force push to your branch and the pr will update.

**Comment by mnacamura** [comment]
@LnL7 Thanks! I'll try it next time.

**Pull request closed without merging**
