### PR TITLE
iosevka: 5.0.2 -> 7.0.4, iosevka-bin: 5.0.5 -> 7.0.4 

### PR DESCRIPTION
**Pull request by figgyc**
###### Motivation for this change
There has been a few new glyphs added to Iosevka since this package was last updated, I noticed as I was trying to compile a custom version and it didn't work with the current package.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

/marvin opt-in
/status needs_reviewer

### CODE REVIEW

**Review by kevincox — APPROVED** [review]

**Review by moni-dz — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
@figgyc please resolve the merge conflict.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126664` at 410b187b run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/31f88c5e54737f591888c418aa859c1b">vscode-extensions.vadimcn.vscode-lldb</a></li>
  </ul>
</details>
<details>
  <summary>3 packages skipped due to time constraints:</summary>
  <ul>
    <li>iosevka</li>
    <li>iosevka-bin</li>
    <li>lumo</li>
  </ul>
</details>
<details>
  <summary>7 packages built successfully:</summary>
  <ul>
    <li>bat-extras.prettybat</li>
    <li>discourse</li>
    <li>nixos-install-tools</li>
    <li>parity-ui</li>
    <li>teleprompter</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>zerobin</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by SuperSandro2000** [comment]
sorry for the new merge conflict. Please hit someone up on matrix when you resolved it that we can merge this asap.

**Comment by figgyc** [comment]
@SuperSandro2000 I've resolved the merge conflict, can you (or someone else) take another look? I did ask on matrix before I went to bed last night but seems like nobody did.

**Pull request merged**
