### PR TITLE
rmfuse: don't use poetry2nix

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
Similar to #174804.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by adisbladis** [comment]
I maintain rmfuse and do not want to do this.

**Comment by dotlambda** [comment]
Using poetry2nix is insecure: https://github.com/NixOS/nixpkgs/pull/175600

**Comment by dotlambda** [comment]
> @dotlambda I am wondering how this concern is addressed in `buildRustPackage` which similarly uses the lock file to pull deps down and is used for almost all Rust packages.

`buildRustPackage` suffers from the same problems.

> Is there some type of CVE scanning done in-loop there that poetry2nix does not yet implement, and if so, do you think we would be able to extend poetry2nix to implement similar functionality?

There is a way to manually scan for vulnerabilities: https://github.com/NixOS/nixpkgs/issues/141368.
I assume somthing similar could be done for poetry using e.g. https://github.com/opeco17/poetry-audit-plugin.

**Comment by trepetti** [comment]
@dotlambda Thanks, that does seem like a promising way forward. [The discussion of a similar issue on the Haskell packaging side of things](https://discourse.nixos.org/t/packages-marked-as-broken-should-come-with-an-explanation/19187) also had some interesting thoughts on lock files and the general question of how best to deal with security and breakage for any lang2nix system.

**Comment by dotlambda** [comment]
I think one of this PR and https://github.com/NixOS/nixpkgs/issues/141368 should be merged.

**Pull request closed without merging**
