### PR TITLE
faust: 2.54.9 -> 2.59.6

### PR DESCRIPTION
**Pull request by magnetophon**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
`nixpkgs-review` revealed no new failures on macos 10.15 & nixos x86_64 before the last push, haven't tried again..

**Comment by magnetophon** [comment]
@risicle Thanks for testing!

**Comment by magnetophon** [comment]
2.59.5 was a pre-release, 2.59.6 is a proper release.

**Comment by olafklingt** [comment]
on nixos x86_64 nixpkgs-review failed in `faustStk` i am not sure how it is related to your patch. But it seems that it duplicates parts of Faust. https://github.com/NixOS/nixpkgs/blob/8fcd9a317391dffeb4475f2f8810fd2b7c217ba4/pkgs/applications/audio/faustStk/default.nix#L4 also provides `faustPhysicalModeling` but with a spelling mistake `faustPhhysicalModeling`.

**Comment by magnetophon** [comment]
@olafklingt Thanks for testing!
faustStk is a duplicate package, I have removed it in another PR: https://github.com/NixOS/nixpkgs/pull/215561/commits/5c559bd0656b96ed651814fc2fc24b054a053cdf

**Review by olafklingt — APPROVED** [review]

**Pull request merged**
