### PR TITLE
nixos/dokuwiki: add caddy webserver support

### PR DESCRIPTION
**Pull request by onny**
###### Motivation for this change

To be able to combine DokuWiki with other modules that are using Caddy. This concept is unfluenced by [this pull request](https://github.com/NixOS/nixpkgs/pull/84446).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
@1000101 I created a new pull request since I messed up the old [PR](https://github.com/NixOS/nixpkgs/pull/122883). If the tests are still failing, I'll have too look what exactly is missing :)

**Comment by 1000101** [comment]
> @1000101 I created a new pull request since I messed up the old [PR](https://github.com/NixOS/nixpkgs/pull/122883). If the tests are still failing, I'll have too look what exactly is missing :)

Sure :), let's see!

**Comment by 1000101** [comment]
@onny have a look at https://github.com/NixOS/nixpkgs/pull/124377/checks?check_run_id=2665805387

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 124377` at d959e8ff run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Pull request closed without merging**
