### PR TITLE
eww: 0.6.0-unstable-2024-04-26 -> 0.6.0-unstable-2024-07-05

### PR DESCRIPTION
**Pull request by eclairevoyant**
## Description of changes

- **eww: nixfmt**
- **eww: set updateScript**
- **eww: 0.6.0-unstable-2024-04-26 -> 0.6.0-unstable-2024-07-05**

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by w-lfchen** [comment]
if https://github.com/elkowar/eww/pull/1144 gets merged, this should be obsolete, right?
i contacted elkowar about this yesterday and am currently waiting for a response.

**Comment by eclairevoyant** [comment]
This is a PR that works now, rather than discussing hypotheticals 🤷

**Review by w-lfchen — APPROVED** [review]
yes, i didn't mean to discredit your work with that comment.
i consider myself fairly new to all of this and simply wanted to ask whether my intuition here is correct, my apologies for sounding rude

**Comment by eclairevoyant** [comment]
Sorry, I phrased my response unclearly, as well. I meant, we don't know if upstream will respond to your PR in the next couple of weeks, so we'd be discussing hypotheticals rather than certainties.

Though yes if your PR builds with 1.80, then this PR's patch will not be necessary.

**Comment by w-lfchen** [comment]
alright, no worries then ^^
i think merging this for now is a good idea and i'll see whether i can work something out with upstream.
if i do, i'll just open another pr targeting `staging-next`, is that correct?
or should i target `master`? i'm not really sure whether it'd make much of a difference

**Comment by eclairevoyant** [comment]
If your PR builds with rust 1.79, or if you submit the PR after the staging merge, then `master` is fine. I was just lazy to test my PR on 1.79 since rust builds are always slow :sweat_smile:

**Comment by w-lfchen** [comment]
@eclairevoyant i was unable to find a different way to contact you, so i apologize for using this pr as a last resort (sorry for the notifications to everyone reading this).
if it's not too much of a burden, could you please review eclairevoyant/aur-packages#17?

**Pull request merged**
