### PR TITLE
lib.updateName: use a different mechanism

### PR DESCRIPTION
**Pull request by vcunat**
_I'm merging in a few days if there are no objections._

I found it slightly confusing that the paths of packages like `bashInteractive` didn't reflect the name seen by nix-env.  I really prefer to keep these names equal.

Now `appendToName` changes also the name-part in $out and drv paths. Name changes will cause a rebuild now, but it's a custom to use it for differently configured variants, i.e. the rebuild would happen anyway.

### CODE REVIEW

**Comment by edolstra** [comment]
I don't think this is a good idea. `overrideDerivation` is an ugly, inefficient hack that we shouldn't rely on in Nixpkgs itself. (It's fine for ad-hoc modifications in ~/.nixpkgs/config.nix.)

The clean solution is to compute the correct name in the Nix expression for the package, e.g.
```
mkDerivation {
  name = "bash-" + optionalString interactive "interactive-" + ...;
}
```

Also, I don't think it's that confusing. The goal is to disambiguate names for `nix-env`, which it does.

**Comment by vcunat** [comment]
From programming point of view, the following pattern seems better to me, and it is used in nixpkgs on quite a few places:
```nix
foo-var2 = appendToName "-var2" (foo.override { /* some feature specs */ });
```

It also has more "functional style" feeling for me. Currently I see no suitable implementation, though, if `overrideDerivation` is better avoided.

**Comment by rasendubi** [comment]
(triage) can be closed?

**Comment by domenkozar** [comment]
We should rather use a fixed point to do such modifications instead of overriding derivation attributes once they've been computed.

**Comment by domenkozar** [comment]
@vcunat any objections closing this?

**Comment by vcunat** [comment]
I don't understand what you mean about "fixed point", but in any case I see no use to keep the PR open.

**Pull request closed without merging**
