### PR TITLE
gnunet{,-gtk}: bump to 0.13.1

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
follow up to: #77828

the gnunet and gnunet-gtk project seem to be developed in tandem, seems to make sense to have them under the  same directory

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
cc @pstn @vrthra

**Comment by pstn** [comment]
Changes look good, weird localization behaviour of gnunet-fs-gtk seems to be gone, too.

Anybody against moving me as maintainer to default.nix and also inherit over to gtk.nix? Doesn't seem to make sense to just maintain one of the two when they even share the version number.

**Comment by jonringer** [comment]
@pstn please take another look

**Comment by pstn** [comment]
I like the changes and learned about `mirror://` in nixpkgs. Good to know. Executables still seem fine, too.

**Pull request merged**
