### PR TITLE
remove many unused inputs; amule, python27Packages.requests: mark broken; Revert "qemu: guard desktop file removal"

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by benley** [comment]
LGTM for python-jq, which is the only thing I've touched in here (I think)

**Review by benley — APPROVED** [review]
LGTM for python-jq, which is the only thing I've touched in here (I think)

**Review by alesya-h — APPROVED** [review]
Looks good to me. Mine was modem-manager-gui.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 114768` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
5 packages marked as broken and skipped:
</summary>
<ul>
<li>linuxPackages-libre.virtualbox</li>
<li>linuxPackages_hardkernel_4_14.virtualbox</li>
<li>linuxPackages_hardkernel_latest.virtualbox</li>
<li>linuxPackages_latest-libre.virtualbox</li>
<li>multibootusb</li>
</ul>
</details>
<details>
<summary>
1 package blacklisted:
</summary>
<ul>
<li>tests.nixos-functions.nixosTest-test</li>
</ul>
</details>
<details>

  <summary>5 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>aqemu: <a href="https://termbin.com/ywp8">plain log</a>  |  <a href="https://htmlpreview.github.io/?https://gist.githubusercontent.com/SuperSandroBot/9b726a4995be9056f6c8f084f95f7360/raw/index.html">pretty log </a></li>
<li>qemu_xen: log was empty</li>
<li>(qemu_xen_4_10): log was empty</li>
<li>qemu_xen-light: log was empty</li>
<li>(qemu_xen_4_10-light): log was empty</li>
  </ul>
</details>
<details>
<summary>
49 packages built:
</summary>
<ul>
<li>alpine-make-vm-image</li>
<li>clipit</li>
<li>cloud-init</li>
<li>cloud-utils</li>
<li>cot (python38Packages.cot)</li>
<li>gammastep</li>
<li>libayatana-appindicator (libayatana-appindicator-gtk3)</li>
<li>libayatana-appindicator-gtk2</li>
<li>libguestfs</li>
<li>linuxPackages.virtualbox (linuxPackages_5_4.virtualbox)</li>
<li>linuxPackages_4_14.virtualbox</li>
<li>linuxPackages_4_19.virtualbox</li>
<li>linuxPackages_4_4.virtualbox</li>
<li>linuxPackages_4_9.virtualbox</li>
<li>linuxPackages_5_10.virtualbox</li>
<li>linuxPackages_5_11.virtualbox (linuxPackages_latest.virtualbox)</li>
<li>linuxPackages_hardened.virtualbox</li>
<li>linuxPackages_latest_hardened.virtualbox</li>
<li>linuxPackages_latest_xen_dom0.virtualbox</li>
<li>linuxPackages_latest_xen_dom0_hardened.virtualbox</li>
<li>linuxPackages_lqx.virtualbox</li>
<li>linuxPackages_testing_bcachefs.virtualbox</li>
<li>linuxPackages_xen_dom0.virtualbox</li>
<li>linuxPackages_xen_dom0_hardened.virtualbox</li>
<li>linuxPackages_zen.virtualbox</li>
<li>modem-manager-gui</li>
<li>open-watcom-bin</li>
<li>out-of-tree</li>
<li>pasystray</li>
<li>python37Packages.cot</li>
<li>python37Packages.guestfs</li>
<li>python37Packages.jq</li>
<li>python38Packages.guestfs</li>
<li>python38Packages.jq</li>
<li>python39Packages.cot</li>
<li>python39Packages.guestfs</li>
<li>python39Packages.jq</li>
<li>qemu</li>
<li>qemu-utils</li>
<li>qemu_full</li>
<li>qemu_kvm</li>
<li>qemu_test</li>
<li>qtemu</li>
<li>solo5</li>
<li>vagrant</li>
<li>virtualbox</li>
<li>virtualboxHardened</li>
<li>virtualboxHeadless</li>
<li>virtualboxWithExtpack</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
aqemu:
<details>


warning: unclear-gpl
`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/virtualization/aqemu/default.nix:22:5:

```
   |
22 |     license = licenses.gpl2;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
clipit:
<details>


warning: unclear-gpl
`gpl3` is a deprecated license, check if project uses `gpl3Plus` or `gpl3Only` and change `meta.license` accordingly.

Near pkgs/applications/misc/clipit/default.nix:31:5:

```
   |
31 |     license     = licenses.gpl3;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
cloud-init:
<details>


warning: unused-argument
Unused argument: `pytest`.
Near pkgs/tools/virtualization/cloud-init/default.nix:11:3:

```
   |
11 | , pytest
   |   ^
```
</details>
cloud-utils:
<details>


warning: unclear-gpl
`gpl3` is a deprecated license, check if project uses `gpl3Plus` or `gpl3Only` and change `meta.license` accordingly.

Near pkgs/tools/misc/cloud-utils/default.nix:53:5:

```
   |
53 |     license = licenses.gpl3;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/tools/misc/cloud-utils/default.nix:51:3:

```
   |
51 |   meta = with lib; {
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
warning: unused-argument
Unused argument: `euca2ools`.
Near pkgs/tools/misc/cloud-utils/default.nix:3:30:

```
  |
3 | , wget, python3, qemu-utils, euca2ools
  |                              ^
```
</details>
cot:
<details>


warning: unused-argument
Unused argument: `argcomplete`.
Near pkgs/development/python-modules/cot/default.nix:2:3:

```
  |
2 | , argcomplete, colorlog, pyvmomi, requests, verboselogs
  |   ^
```
warning: unused-argument
Unused argument: `pytest`.
Near pkgs/development/python-modules/cot/default.nix:4:9:

```
  |
4 | , mock, pytest, pytest-mock, pytestCheckHook, qemu
  |         ^
```
</details>
libguestfs:
<details>


warning: unclear-gpl
`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/development/libraries/libguestfs/default.nix:90:5:

```
   |
90 |     license = with licenses; [ gpl2 lgpl21 ];
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
warning: unclear-gpl
`lgpl21` is a deprecated license, check if project uses `lgpl21Plus` or `lgpl21Only` and change `meta.license` accordingly.

Near pkgs/development/libraries/libguestfs/default.nix:90:5:

```
   |
90 |     license = with licenses; [ gpl2 lgpl21 ];
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
linuxPackages_4_14.virtualbox:
<details>


warning: unclear-gpl
`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/virtualization/virtualbox/default.nix:232:5:

```
    |
232 |     license = licenses.gpl2;
    |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
linuxPackages_4_19.virtualbox:
<details>


warning: unclear-gpl
`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/virtualization/virtualbox/default.nix:232:5:

```
    |
232 |     license = licenses.gpl2;
    |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
linuxPackages_4_4.virtualbox:
<details>


warning: unclear-gpl
`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/virtualization/virtualbox/default.nix:232:5:

```
    |
232 |     license = licenses.gpl2;
    |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
linuxPackages_4_9.virtualbox:
<details>


warning: unclear-gpl
`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/virtualization/virtualbox/default.nix:232:5:

```
    |
232 |     license = licenses.gpl2;
    |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
linuxPackages_5_10.virtualbox:
<details>


warning: unclear-gpl
`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/virtualization/virtualbox/default.nix:232:5:

```
    |
232 |     license = licenses.gpl2;
    |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
linuxPackages_5_11.virtualbox:
<details>


warning: unclear-gpl
`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/virtualization/virtualbox/default.nix:232:5:

```
    |
232 |     license = licenses.gpl2;
    |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
linuxPackages_hardened.virtualbox:
<details>


warning: unclear-gpl
`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/virtualization/virtualbox/default.nix:232:5:

```
    |
232 |     license = licenses.gpl2;
    |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
linuxPackages_latest_hardened.virtualbox:
<details>


warning: unclear-gpl
`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/virtualization/virtualbox/default.nix:232:5:

```
    |
232 |     license = licenses.gpl2;
    |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
linuxPackages_latest_xen_dom0_hardened.virtualbox:
<details>


warning: unclear-gpl
`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/virtualization/virtualbox/default.nix:232:5:

```
    |
232 |     license = licenses.gpl2;
    |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
linuxPackages_latest_xen_dom0.virtualbox:
<details>


warning: unclear-gpl
`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/virtualization/virtualbox/default.nix:232:5:

```
    |
232 |     license = licenses.gpl2;
    |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
linuxPackages_lqx.virtualbox:
<details>


warning: unclear-gpl
`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/virtualization/virtualbox/default.nix:232:5:

```
    |
232 |     license = licenses.gpl2;
    |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
linuxPackages_testing_bcachefs.virtualbox:
<details>


warning: unclear-gpl
`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/virtualization/virtualbox/default.nix:232:5:

```
    |
232 |     license = licenses.gpl2;
    |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
linuxPackages.virtualbox:
<details>


warning: unclear-gpl
`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/virtualization/virtualbox/default.nix:232:5:

```
    |
232 |     license = licenses.gpl2;
    |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
linuxPackages_xen_dom0_hardened.virtualbox:
<details>


warning: unclear-gpl
`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/virtualization/virtualbox/default.nix:232:5:

```
    |
232 |     license = licenses.gpl2;
    |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
linuxPackages_xen_dom0.virtualbox:
<details>


warning: unclear-gpl
`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/virtualization/virtualbox/default.nix:232:5:

```
    |
232 |     license = licenses.gpl2;
    |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
linuxPackages_zen.virtualbox:
<details>


warning: unclear-gpl
`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/virtualization/virtualbox/default.nix:232:5:

```
    |
232 |     license = licenses.gpl2;
    |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
modem-manager-gui:
<details>


warning: unclear-gpl
`gpl3` is a deprecated license, check if project uses `gpl3Plus` or `gpl3Only` and change `meta.license` accordingly.

Near pkgs/applications/networking/modem-manager-gui/default.nix:60:5:

```
   |
60 |     license = licenses.gpl3;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
python37Packages.cot:
<details>


warning: unused-argument
Unused argument: `argcomplete`.
Near pkgs/development/python-modules/cot/default.nix:2:3:

```
  |
2 | , argcomplete, colorlog, pyvmomi, requests, verboselogs
  |   ^
```
warning: unused-argument
Unused argument: `pytest`.
Near pkgs/development/python-modules/cot/default.nix:4:9:

```
  |
4 | , mock, pytest, pytest-mock, pytestCheckHook, qemu
  |         ^
```
</details>
python39Packages.cot:
<details>


warning: unused-argument
Unused argument: `argcomplete`.
Near pkgs/development/python-modules/cot/default.nix:2:3:

```
  |
2 | , argcomplete, colorlog, pyvmomi, requests, verboselogs
  |   ^
```
warning: unused-argument
Unused argument: `pytest`.
Near pkgs/development/python-modules/cot/default.nix:4:9:

```
  |
4 | , mock, pytest, pytest-mock, pytestCheckHook, qemu
  |         ^
```
</details>
qemu_full:
<details>


warning: unnecessary-parallel-building
Meson, CMake and qmake already set `enableParallelBuilding = true` by default so it is not necessary.

Near pkgs/applications/virtualization/qemu/default.nix:80:3:

```
   |
80 |   enableParallelBuilding = true;
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unnecessary-parallel-building.md
</details>
qemu_kvm:
<details>


warning: unnecessary-parallel-building
Meson, CMake and qmake already set `enableParallelBuilding = true` by default so it is not necessary.

Near pkgs/applications/virtualization/qemu/default.nix:80:3:

```
   |
80 |   enableParallelBuilding = true;
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unnecessary-parallel-building.md
</details>
qemu:
<details>


warning: unnecessary-parallel-building
Meson, CMake and qmake already set `enableParallelBuilding = true` by default so it is not necessary.

Near pkgs/applications/virtualization/qemu/default.nix:80:3:

```
   |
80 |   enableParallelBuilding = true;
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unnecessary-parallel-building.md
</details>
qemu_test:
<details>


warning: unnecessary-parallel-building
Meson, CMake and qmake already set `enableParallelBuilding = true` by default so it is not necessary.

Near pkgs/applications/virtualization/qemu/default.nix:80:3:

```
   |
80 |   enableParallelBuilding = true;
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unnecessary-parallel-building.md
</details>
qemu_xen-light:
<details>


warning: unnecessary-parallel-building
Meson, CMake and qmake already set `enableParallelBuilding = true` by default so it is not necessary.

Near pkgs/applications/virtualization/qemu/default.nix:80:3:

```
   |
80 |   enableParallelBuilding = true;
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unnecessary-parallel-building.md
</details>
qemu_xen:
<details>


warning: unnecessary-parallel-building
Meson, CMake and qmake already set `enableParallelBuilding = true` by default so it is not necessary.

Near pkgs/applications/virtualization/qemu/default.nix:80:3:

```
   |
80 |   enableParallelBuilding = true;
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unnecessary-parallel-building.md
</details>
qtemu:
<details>


warning: unclear-gpl
`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/virtualization/qtemu/default.nix:41:5:

```
   |
41 |     license = licenses.gpl2;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
warning: unused-argument
Unused argument: `makeWrapper`.
Near pkgs/applications/virtualization/qtemu/default.nix:1:72:

```
  |
1 | { lib, mkDerivation, fetchFromGitLab, pkg-config, qmake, qtbase, qemu, makeWrapper }:
  |                                                                        ^
```
</details>
tests.nixos-functions.nixosTest-test:
<details>


warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near nixos/lib/testing-python.nix:64:7:

```
   |
64 |       buildCommand =
   |       ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
warning: license-missing
Package is missing a license

Near nixos/lib/testing-python.nix:64:7:

```
   |
64 |       buildCommand =
   |       ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md
</details>
vagrant:
<details>


warning: unused-argument
Unused argument: `fetchpatch`.
Near pkgs/development/tools/vagrant/default.nix:2:62:

```
  |
2 | , libguestfs, qemu, writeText, withLibvirt ? stdenv.isLinux, fetchpatch
  |                                                              ^
```
</details>
virtualboxHeadless:
<details>


warning: stale-substitute
Stale substituteInPlace detected.
substituteStream(): WARNING: pattern 'PSHCLFORMATDATA' doesn't match anything in file 'src/VBox/HostServices/SharedClipboard/VBoxSharedClipboardSvc-x11-stubs.cpp'
See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md
</details>
</details>

**Comment by adisbladis** [comment]
@SuperSandro2000 

This is quite frankly unacceptable. Just blindly marking a package like `python2Packages.requests` as broken needs a _very_ thorough explanation and discussion.
Bundling it up with a bunch of other seemingly unrelated stuff makes it even worse. This PR should never have been merged.
You need to deal with the fallout from this.

I have a few questions:
- Did you consider the implications of what packages you are breaking (you broke `nixops` for one)
- Did you even look into actually _fixing_ the problem instead of just sweeping it under the proverbial rug?

**Pull request merged**
