### PR TITLE
root: add nixpkgs-review to shell.nix

### PR DESCRIPTION
**Pull request by Scrumplex**
## Description of changes

nixpkgs-review is endorsed in CONTRIBUTING.md, as well as in the default PR description template.
It would be very useful to include this utility in our shell.nix.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Scrumplex** [comment]
CC @infinisil for #322512

**Review by infinisil — APPROVED** [review]
Sounds good to me!

**Comment by SuperSandro2000** [comment]
Except that it has quite a few gotchas you need to know before running it:
- if ofborg hasn't computed the changed package lists yet, you need probably need 8 or 16GB free RAM at least
- PRs that have a rebuild count of one are better reviewed by building that one package
- if you haven't fine tuned nix max-jobs/cores settings you can easily produce false positives 
- per default there are no logs attached which makes it pretty hard to work with the report
- also pre-existing failures are not filtered which sometimes makes people think, that they need to fix everything 
- everything targetted towards staging should probably not be run unless you know what you are doing
- python programs are known to be broken in the shell

Don't get me wrong, it is a nice utility but you need to know when and how to use it, to make the most out of it. Blindly running it against every change or PR has little benefit.

**Comment by infinisil** [comment]
@SuperSandro2000 Yeah that's good to keep in mind. I don't think this is blocking for this PR though, so let's just go ahead with the merge :)

**Pull request merged**
