### PR TITLE
tcl/tk: 8.6.4 -> 8.6.6

### PR DESCRIPTION
**Pull request by vrthra**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vrthra** [comment]
The error is *no space left on device*

**Comment by obadz** [comment]
@vcunat, does this need to go into staging? Otherwise I'd just merge.

**Comment by vcunat** [comment]
It doesn't seem a mass rebuild to me.

**Comment by vcunat** [comment]
Oh, I didn't notice our default python depends on it.

**Comment by vcunat** [comment]
It does not; the expression confused me. I should finally start using `nox` for this or something.

**Pull request merged**
