### PR TITLE
blas/lapack: increase flexibility of wrappers

### PR DESCRIPTION
**Pull request by markuskowa**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/83888 was a big step forward to provide a simple interface for switching BLAS/LAPACK implementations. This PR fine-tunes the wrapper to extend the number of implementations that can be used by the wrapper. So far, only OpenBLAS and MKL were valid. After cleaning up `amd-blis`, `amd-libflame`,  `blas-reference`, and `lapack-reference`  these implementations can now also be exposed through the wrapper. While it may not seem necessary for `blas-reference`, `lapack-reference` it allows for a clean interface, where now all implementations can be swapped in exactly the same way.

This PR is also one step in cleaning up the handling of the ILP64/LP64 interfaces that these libraries support. All packages that provide blas/lapack implementations (except  MKL), now support the `blas64` boolean input parameter, which switches the interface at build time. Overrides now work for all above-mentioned implementations according to the following scheme:
```
 myblas = self.blas.override { isILP64=true; blasProvider = self.amd-blis; };
 mylapack = self.lapack.override { isILP64=true; lapackProvider = self.mkl; };
```

We now also build the attributes `blas-ilp64` and `lapack-ilp64` to have these 64 bit interfaces available right away. This will make it easier to build scientific applications that rely on it. Note, that while some applications decide at build time which interface to use, others only support either one and can not switch.

###### Things done
* Added `blas-ilp64` and `lapack-ilp64` to provide the 64 bit interfaces separately.
* Added the `blas64` flag to `amd-blis`, `amd-libflame`,  `blas-reference`, and `lapack-reference` and adapted the nix expressions to honor this flag. Note, that `amd-libflame` accepts only  `blas64 = false` at the moment.
* Fixed the BLAS/LAPACK wrappers to hand down the `isILP64` flag to the underlying implementation via `blas64`.
* Use `cmake` to build  `blas-reference`.
* Adopt blas/lapack-reference and amd-blis as a maintainer.
* Added a sentence to the manual mentioning the `blas/lapack-ilp64` attributes.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by markuskowa** [comment]
@GrahamcOfBorg build blas-reference

**Comment by sheepforce** [comment]
I've tried a few packages locally with these changes, and observed some failures, that probably should not be there?

Building some test packages with amd-blis and amd-libflame
```
nix-build -E "
let
  blasOvl = self: super: {
    blas = super.blas.override { blasProvider = super.amd-blis; };
    lapack = super.lapack.override { lapackProvider = super.amd-libflame; };
  };
  pkgs = import ./default.nix {
    overlays = [ blasOvl ];
  };

in { inherit (pkgs) scalapack cp2k;
      numpy = pkgs.python3.pkgs.numpy;
   }
"
```
  * `scalapack` fails multiple tests (5, 6, 8, 12, 14, 15, 26, 27, and possibly more. Didn't wait for it to finish)

------------
Building test packages with blas-reference and lapack-reference
```
nix-build -E "
let
  blasOvl = self: super: {
    blas = super.blas.override { blasProvider = super.blas-reference; };
    lapack = super.lapack.override { lapackProvider = super.lapack-reference; };
  };
  pkgs = import ./default.nix {
    overlays = [ blasOvl ];
  };

in { inherit (pkgs) scalapack cp2k;
      numpy = pkgs.python3.pkgs.numpy;
   }
"
```
  * `blas` does not evaluate as libcblas is missing:
    ```
     these 2 derivations will be built:
       /nix/store/7pfc2fxmhwfm10lc2ybd01hdm0cmyg2h-blas-3.drv
       /nix/store/hjqi815iw0xq08awxlls5bvif3nv726s-scalapack-2.1.0.drv
     building '/nix/store/7pfc2fxmhwfm10lc2ybd01hdm0cmyg2h-blas-3.drv'...
     unpacking sources
     patching sources
     installing
     /nix/store/g16y5z4kj2cyc0nm0ss8sywy75p4fc3f-blas-3.10.0/lib/libcblas.so.3 does not exist, blas-3.10.0 does not provide libcblas.
     error: builder for '/nix/store/7pfc2fxmhwfm10lc2ybd01hdm0cmyg2h-blas-3.drv' failed with exit code 1;
            last 4 log lines:
            > unpacking sources
            > patching sources
            > installing
            > /nix/store/g16y5z4kj2cyc0nm0ss8sywy75p4fc3f-blas-3.10.0/lib/libcblas.so.3 does not exist, blas-3.10.0 does not provide libcblas.
            For full logs, run 'nix log /nix/store/7pfc2fxmhwfm10lc2ybd01hdm0cmyg2h-blas-3.drv'.
     error: 1 dependencies of derivation '/nix/store/hjqi815iw0xq08awxlls5bvif3nv726s-scalapack-2.1.0.drv' failed to build

    ```
  * `numpy`: fails with an attribute error due to name conflicts: 
    ```
        error: dynamic attribute 'blas' already defined at /home/phillip/Dokumente/Git/nixpkgs/pkgs/development/python-modules/numpy/default.nix:34:7

       at /home/phillip/Dokumente/Git/nixpkgs/pkgs/development/python-modules/numpy/default.nix:23:7:

           22|     text = (lib.generators.toINI {} {
           23|       ${blas.implementation} = {
             |       ^
           24|         include_dirs = "${lib.getDev blas}/include:${lib.getDev lapack}/include";
    ```

**Review by sheepforce — CHANGES_REQUESTED** [review]

**Comment by markuskowa** [comment]
@sheepforce Thanks for taking a look at it.

> I've tried a few packages locally with these changes, and observed some failures, that probably should not be there?

`lib-flame` seems to be  not yet perfectly 100% compatible LAPACK interface, so that only some packages will build.
From what I have seen: I think that a lot of combinations will not build. I.e. not every package with build with every blas/lapack implementation.  I would consider this as normal thing. You have the same thing with MPI. Some packages do build properly when you replace the default MPI implementation.

> blas does not evaluate as `libcblas` is missing

To override, blas with the reference implementation, one needs to use `lapack-reference`, as it contains blas+cblas. I will add a remark to the manual. The source code of `blas-reference` does not contain the cblas code.

> numpy: fails with an attribute error due to name conflicts

Not sure where this comes from?

**Comment by sheepforce** [comment]
> @sheepforce Thanks for taking a look at it.

Thanks for this super nice extension :slightly_smiling_face: 


> `lib-flame` seems to be not yet perfectly 100% compatible LAPACK interface, so that only some packages will build.
> From what I have seen: I think that a lot of combinations will not build.

OK, thats true :) For ScaLAPACK I think that is somehow unfortunate, as it is a quite interesting package. However, there is https://developer.amd.com/amd-aocl/scalapack/ from AMD. Next step making a unified ScaLAPACK interface? :sweat_smile: For now we can live with this, I think.

> 

> > numpy: fails with an attribute error due to name conflicts
> 
> Not sure where this comes from?

I think this comes from [here](https://github.com/NixOS/nixpkgs/blob/ccb806afd7146c448be501c46561632fcc7d6ffb/pkgs/development/python-modules/numpy/default.nix#L23) and [here](https://github.com/NixOS/nixpkgs/blob/ccb806afd7146c448be501c46561632fcc7d6ffb/pkgs/development/python-modules/numpy/default.nix#L34).
`blas.implementation` evaluates simply to `blas` and the key in the dict is not unique anymore.

**Comment by markuskowa** [comment]
> OK, thats true :) For ScaLAPACK I think that is somehow unfortunate, as it is a quite interesting package. However, there is https://developer.amd.com/amd-aocl/scalapack/ from AMD. Next step making a unified ScaLAPACK interface? sweat_smile For now we can live with this, I think.

I think the ScaLAPACK interface should already be very uniform. The amd version is just forked from the reference implementation. This could probably be done by just renaming the attributes, like we do for MPI. I did try to build amd-scalapack, but did not succeed yet.

> I think this comes from [here](https://github.com/NixOS/nixpkgs/blob/ccb806afd7146c448be501c46561632fcc7d6ffb/pkgs/development/python-modules/numpy/default.nix#L23) and [here](https://github.com/NixOS/nixpkgs/blob/ccb806afd7146c448be501c46561632fcc7d6ffb/pkgs/development/python-modules/numpy/default.nix#L34).
blas.implementation evaluates simply to blas and the key in the dict is not unique anymore.

OK, I see now where it comes from. I leave this up someone else to adapt numpy to this particular case.

**Review by sheepforce — APPROVED** [review]

**Comment by markuskowa** [comment]
I would go ahead and merge this if there are no further comments from anyone else.

**Pull request merged**
