### PR TITLE
Don't use deprecated dbusdirs

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
✌️etc/dbus-1/system.d for third party packages.
This is a mix of upstream patches of my own, other people's yet to be merged patches, and using the configure flags projects provided.

There's still a few more I'd like to get but didn't have time for
- hplip
- system-config-printer
- ~wpa_supplicant~
- rtkit
- ~rpm-ostree~

###### Upstream PRs/MRs

- [x] https://github.com/fwupd/fwupd/pull/1356
- [x] https://github.com/blueman-project/blueman/pull/1103
- [ ] https://github.com/mate-desktop/mate-settings-daemon/pull/296
- [ ] https://gitlab.gnome.org/GNOME/network-manager-iodine/merge_requests/2
- [ ] https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/merge_requests/11
- [ ] https://gitlab.gnome.org/GNOME/NetworkManager-openconnect/merge_requests/9
- [x] https://gitlab.freedesktop.org/libfprint/fprintd/merge_requests/16
- [ ] https://gitlab.freedesktop.org/cups-pk-helper/cups-pk-helper/merge_requests/2
- [x] https://github.com/coreos/rpm-ostree/pull/1903
- [x] https://github.com/strongswan/strongswan/pull/150
- [ ] https://github.com/svanderburg/disnix/pull/14
- [ ] https://github.com/openSUSE/snapper/pull/492

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by jtojnar** [comment]
Is there any benefit to patching the projects downstream? Unless the legacy directory support is to be removed in near future, I would say this just clutters the expressions without any added value. For the expressions where we are explicitly passing the legacy path, it looks good.

**Comment by worldofpeace** [comment]
@jtojnar All the patches have been submitted upstream, I'm certain they'll all be accepted.

**Comment by jtojnar** [comment]
Yeah, that is good. But I do not see much benefit in applying them here.

**Comment by worldofpeace** [comment]
> Yeah, that is good. But I do not see much benefit in applying them here.

I'd disagree. The added value is that the dbus sys directory is now correct, and that's what this PR is for. The patches are the means to this. If I wasn't going to do that I wouldn't have opened this PR.

**Comment by NeQuissimus** [comment]
Pretty sure this broke WPA Supplicant:

```
Oct 14 09:22:02 nixus dbus-daemon[1819]: dbus[1819]: Failed to start message bus: Failed to read directory "/nix/store/4n7bwq053a3gfz7w8dyigizvq3iydj0h-wpa_supplicant-2.9/share/dbus-1/system.d": Not a directory
Oct 14 09:22:02 nixus systemd[1769]: systemd-logind.service: Executable /sbin/modprobe missing, skipping: No such file or directory
Oct 14 09:22:03 nixus kernel: iwlwifi 0000:01:00.0: Applying debug destination EXTERNAL_DRAM
Oct 14 09:22:03 nixus kernel: iwlwifi 0000:01:00.0: Applying debug destination EXTERNAL_DRAM
Oct 14 09:22:03 nixus kernel: iwlwifi 0000:01:00.0: FW already configured (0) - re-configuring
Oct 14 09:22:03 nixus kernel: IPv6: ADDRCONF(NETDEV_UP): wlp1s0: link is not ready
Oct 14 09:22:03 nixus dhcpcd[1761]: wlp1s0: waiting for carrier
Oct 14 09:22:03 nixus dhcpcd[1761]: wlp1s0: carrier acquired
Oct 14 09:22:03 nixus dhcpcd[1761]: DUID 00:04:d7:9c:d0:a5:72:1f:c7:40:bd:7d:89:00:f7:a2:77:3c
Oct 14 09:22:03 nixus dhcpcd[1761]: wlp1s0: IAID 88:6f:25:20
Oct 14 09:22:03 nixus dhcpcd[1761]: wlp1s0: adding address fe80::4e34:88ff:fe6f:2520
Oct 14 09:22:03 nixus dhcpcd[1761]: wlp1s0: carrier lost
Oct 14 09:22:03 nixus dhcpcd[1761]: wlp1s0: deleting address fe80::4e34:88ff:fe6f:2520
Oct 14 09:22:33 nixus dhcpcd[1761]: timed out
Oct 14 09:22:33 nixus dhcpcd[1761]: timed out
Oct 14 09:22:33 nixus dhcpcd[1761]: forked to background, child pid 1950
```

**Comment by jtojnar** [comment]
See https://github.com/NixOS/nixpkgs/pull/71113

**Pull request merged**
