### PR TITLE
spotifyd: 0.2.24 -> 0.3.0

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change

https://github.com/Spotifyd/spotifyd/releases/tag/v0.3.0

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bnjmnt4n** [comment]
Seems like removing the changes in #106050 (using an older version of Rust to build) causes the same panics until https://github.com/Spotifyd/spotifyd/issues/719 is resolved.

**Comment by sarcasticadmin** [comment]
@bnjmnt4n that panic is now fixed in https://github.com/NixOS/nixpkgs/pull/114309

**Comment by andir** [comment]
I just saw this and I am a bit stunned. The comment was removed while the issue wasn't fixed. Has either of you (@marsam, @SuperSandro2000) actually tested this on their setup? Checked the upstream issue if it was fixed in this version?

**Comment by marsam** [comment]
@andir I'm so sorry. This was a half-automatized update, I forgot to test it thoroughly. I'll be more careful in the future.

**Pull request merged**
