### PR TITLE
Enable soft real time for gnome shell 

### LINKED ISSUE #71381: Support launching gnome-shell with RT scheduling
#### Background

Capability wrappers are somewhat limited. They require the capability be part of the ambient set for it to survive execv's, ie. when the wrapper executes the source binary (https://github.com/NixOS/nixpkgs/pull/16654). This means any program spawned from a wrapped binary will also inherit the capabilities.

We really don't want programs launched from gnome-shell to inherit cap_sys_nice obviously. In particular bubblewrap fails to work if it possess any extra caps, breaking at least flatpaks and epiphany.

#### Our options
So as far as I can see we have two options:

- Actually copy `.gnome-shell-wrapped` to wrapperDir and set cap_sys_nic=+ep. This should be pretty easy, but also quite ugly (see [this comment](https://github.com/NixOS/nixpkgs/issues/6768#issuecomment-84016619) for context).
- Patch mutter to drop inheritable, we could probably adopt [this unmerged commit](https://gitlab.gnome.org/GNOME/mutter/merge_requests/460/diffs?commit_id=c53c47ae123b03cc66044d2b846342123ecb3a01). This should probably work as the ambient set only propagates if inheritable is set.

cc @jtojnar @worldofpeace

### PR DESCRIPTION
**Pull request by hedning**
###### Motivation for this change

Make gnome-shell wayland run with cap_sys_nice to improve performance.

closes https://github.com/NixOS/nixpkgs/issues/71381

###### Things done

Patched mutter to drop `cap_sys_nice=i` on startup, which prevents the ambient set leaking into processes gnome-shell spawns.

Overrode `gnome-shell-wayland.service` to launch through an added capability wrapper. (This proved a bit fiddly as NixOS provides a rather bad default environment for user services). Thought this was cleaner than mucking about in the gnome-shell derivation.

Running this at the moment, and it seems to work:
image

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by hedning** [comment]
Note we could simplify the drop-inheritable patch, as there's a bunch of stuff we don't really need to support (eg. having a meson option, and ifdefs in the code etc.).

**Comment by worldofpeace** [comment]
@hedning Could it be possible to do similar without security wrappers and systemd?
Or is that not supported well in nixos?

I also believe this is an experimental feature, so I don't think it's on by default.
So perhaps we should respect this and just make it easily configurable for the user.

Could you add an option `services.gnome3.core-shell.realtimeScheduling` (not sure how we feel about camel case there), and optional gsettings override?
```
[org.gnome.mutter]
experimental-features=['rt-scheduler']
```

**Comment by hedning** [comment]
> Could it be possible to do similar without security wrappers and systemd?

You basically need an executable with `cap_sys_nice=ep` or a security wrapper. It's possible to  copy the gnome-shell executable somewhere and setting `cap_sys_nice=ep`, but there's really no precedence or infrastructure to do that (I tested this by hardcoding this in the security wrapper setup, and it does work).

To actually launch sessions with the capability it just seemed cleanest to do it as a service override. That keeps the separation between NixOS and nixpkgs, and the security wrapper code can live together with the override.

> I also believe this is an experimental feature, so I don't think it's on by default.

Right, totally forgot that (I apparently turned it on a long time ago :joy: ). 

> Could you add an option `services.gnome3.core-shell.realtimeScheduling`

Yep, that makes sense :+1: The gsettings override only acts as a default right? It doesn't override anything if the option is set in the users database?

Fedora sets cap_sys_nice by default (https://src.fedoraproject.org/rpms/gnome-shell/blob/f31/f/gnome-shell.spec#_173), so I think that's fine to launch through the wrapper by default (that way it's possible to enable it through dconf-editor etc. too).

**Comment by worldofpeace** [comment]
> You basically need an executable with cap_sys_nice=ep or a security wrapper. It's possible to copy the gnome-shell executable somewhere and setting cap_sys_nice=ep, but there's really no precedence or infrastructure to do that (I tested this by hardcoding this in the security wrapper setup, and it does work).

> To actually launch sessions with the capability it just seemed cleanest to do it as a service override. That keeps the separation between NixOS and nixpkgs, and the security wrapper code can live together with the override.

Umm, by using systemd I meant a service override. But with 
* https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Capabilities

**Comment by jtojnar** [comment]
> The gsettings override only acts as a default right? It doesn't override anything if the option is set in the users database?

Yup. And worst of all, GSettings list do not have merging semantics like Nix modules have, so if we wanted to add another experimental feature, we would need to remember to do it all in single place.

**Comment by hedning** [comment]
> https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Capabilities

Ah, right, that only works for system services unfortunately. I think it would be fairly difficult to integrate it with the display-managers etc. (Also looks like the capabilities are passed through the ambient set, so we'd still need the mutter patch).

**Comment by worldofpeace** [comment]
I'm thinking it might make more sense in nixos to not launch through the wrapper default, but to add the option `services.gnome3.core-shell.realtimeScheduling` to enable this. Thoughts?

**Comment by worldofpeace** [comment]
> I'm thinking it might make more sense in nixos to not launch through the wrapper default, but to add the option `services.gnome3.core-shell.realtimeScheduling` to enable this. Thoughts?

Actually, after thinking about it I don't think there's much point without https://github.com/NixOS/nixpkgs/issues/54150, as we can only influence default values. Which isn't much use, it doesn't enable it. I would only enables **support**. So it's more of an implementation detail, and it's pretty harmless capability anyways.

**Review by worldofpeace — APPROVED** [review]
LGTM, tested and it works.

**Pull request merged**
