### PR TITLE
pythonPackages.pythondaemon: rename to pythonPackages.python-daemon

### PR DESCRIPTION
**Pull request by bhipple**
This commit renames the pythondaemon module to match its module name, github
name, and pypi name, which makes it easier to find and reference. In order to
avoid breaking any external users, I've left an alias with a deprecated warning.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bhipple** [comment]
@GrahamcOfBorg build pythonPackages.python-daemon pythonPackages.pythondaemon

**Comment by bhipple** [comment]
@FRidh what do we think about these kinds of refactorings and using the trace function to leave a deprecated warning?  I think `python-daemon` is a much better name for this, since it matches the module and pypi names.  

```
λ brh nixpkgs →  nix-build . -A pythonPackages.python-daemon
/nix/store/bc4lr49nw788g83zmnbma99iiz6rqv6z-python2.7-python-daemon-2.2.0

λ brh nixpkgs →  nix-build . -A pythonPackages.pythondaemon
trace: DEPRECATED: pythondaemon has been renamed to python-daemon
/nix/store/bc4lr49nw788g83zmnbma99iiz6rqv6z-python2.7-python-daemon-2.2.0
```

**Comment by FRidh** [comment]
Ideally we use the normalized names here in `python-packages.nix`. Doing a renaming can break things so the question is whether it is worth it. The same with using an alias.

This is a very uncommon package, so just do the rename, and drop the alias.

**Comment by bhipple** [comment]
Ok sounds good; I'll just rename it then.  Thanks!

**Comment by bhipple** [comment]
Ping @FRidh?  This should still be good to go, and I think it cleans up a little tech debt at little cost given ti's a relatively rare module.

**Pull request merged**
