### PR TITLE
zed-editor: 0.153.6 -> 0.154.1

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog: https://github.com/zed-industries/zed/releases/tag/v0.154.1

cc @jansol @niklaskorz

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

- Command: `nixpkgs-review pr 344362`
- Systems: `x86_64-linux`,`aarch64-linux`,`x86_64-darwin`,`aarch64-darwin`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:fast_forward: 1 package marked as broken and skipped:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:fast_forward: 1 package marked as broken and skipped:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by jansol** [comment]
Looks like we need `cmake` in `nativeBuildInputs` now.

```
$ nix build github:GaetanLepage/nixpkgs/zed#zed-editor
error: builder for '/nix/store/gdqdkwvy9rjscfr4rib0rpnrx94zafmm-zed-editor-0.154.1.drv' failed with exit code 101;
       last 25 log lines:
       >    Compiling serde_json_lenient v0.2.1
       >    Compiling tree-sitter-json v0.23.0
       >    Compiling wasmtime-c-api-macros v24.0.0
       >    Compiling spin v0.5.2
       >    Compiling rustls v0.20.9
       >    Compiling pem-rfc7468 v0.7.0
       >    Compiling untrusted v0.7.1
       >    Compiling zstd-safe v5.0.2+zstd.1.5.2
       >    Compiling data-encoding v2.6.0
       >    Compiling palette v0.7.6
       >    Compiling by_address v1.2.1
       > error: failed to run custom build command for `wasmtime-c-api-impl v24.0.0`
       >
       > Caused by:
       >   process didn't exit successfully: `/build/source/target/release/build/wasmtime-c-api-impl-df8f3b445655ca4e/build-script-build` (exit status: 101)
       >   --- stdout
       >   cargo:rerun-if-changed=cmake/features.cmake
       >   cargo:rerun-if-changed=cmake/install-headers.cmake
       >   cargo:rerun-if-changed=include
       >
       >   --- stderr
       >   thread 'main' panicked at /build/cargo-vendor-dir/wasmtime-c-api-impl-24.0.0/build.rs:41:33:
       >   failed to spawn `cmake`: Os { code: 2, kind: NotFound, message: "No such file or directory" }
       >   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/gdqdkwvy9rjscfr4rib0rpnrx94zafmm-zed-editor-0.154.1.drv'.
```

**Review by jansol — APPROVED** [review]
builds & runs on x86_64-linux

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 344362`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:fast_forward: 1 package marked as broken and skipped:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:fast_forward: 1 package marked as broken and skipped:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Pull request merged**
