### PR TITLE
google-music-scripts: 4.0.1 -> 4.3.0

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
going through r-ryantm logs

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

```
https://github.com/NixOS/nixpkgs/pull/84081
1 package marked as broken and skipped:
python38Packages.google-music

11 package built:
google-music-scripts python37Packages.audio-metadata python37Packages.google-music python37Packages.google-music-proto python37Packages.google-music-utils python37Packages.httpx python37Packages.tbm-utils python38Packages.audio-metadata python38Packages.google-music-proto python38Packages.google-music-utils python38Packages.tbm-utils
```

### CODE REVIEW

**Review by jbaum98 — APPROVED** [review]
This looks great! Thanks!

**Review by jbaum98 — CHANGES_REQUESTED** [review]
Oh, one thing: can you delete the `loguru.patch` that we don't use anymore in `pkgs/tools/audio/google-music-scripts`?

**Comment by jonringer** [comment]
oh yea, forgot about that while i was fixing all the dependencies

**Comment by jonringer** [comment]
removed

**Pull request merged**
