### PR TITLE
gi-graphene: fix dependency on graphene

### PR DESCRIPTION
**Pull request by bgamari**
## Description of changes

Here we add the necessary dependency of gi-graphene on the graphene package.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bgamari** [comment]
I cannot figure out for the life of me how to test this without updating the entire Hackage snapshot.

**Comment by sternenseemann** [comment]
Can you drop the all-cabal-hashes update? It should be irrelevant, but would break package set regeneration.

**Comment by sternenseemann** [comment]
> I cannot figure out for the life of me how to test this. Specifically, it's quite unclear how to regenerate `pkgs/development/haskell-modules/hackage-packages.nix` without updating the entire Hackage snapshot

Drop the all-cabal-hashes commit and run `./maintainers/scripts/haskell/regenerate-hackage-packages.sh`.

**Comment by bgamari** [comment]
I've dropped the spurious changes. Sadly, however, I am still unable to build `gi-gtk_4_0_7` with this branch:
```
nix-repl> :b legacyPackages.x86_64-linux.haskellPackages.gi-gdk_4_0_7
error: builder for '/nix/store/iaxjyz0arghym4gayyxkx5r52fnpqi63-gi-gdk-4.0.7.drv' failed with exit code 1;
       last 10 log lines:
       > gdk_pixbuf-2.0, cairo-gobject, cairo, graphene-1.0, gio-2.0, gobject-2.0,
       > glib-2.0
       > This problem can usually be solved by installing the system packages that
       > provide these libraries (you may need the "-dev" versions). If the libraries
       > are already installed but in a non-standard location then you can use the
       > flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.If
       > the library files do exist, it may contain errors that are caught by the C
       > compiler at the preprocessing stage. In this case you can re-run configure
       > with the verbosity flag -v3 to see the error messages.
       >
       For full logs, run 'nix log /nix/store/iaxjyz0arghym4gayyxkx5r52fnpqi63-gi-gdk-4.0.7.drv'.
```

**Comment by cdepillabout** [comment]
I sent in part of the fix for `gi-graphene` in https://github.com/NixOS/cabal2nix/pull/609.

**Comment by traleig1** [comment]
I'm out of my league here, but on the off-chance this is of any help - I ran into both "missing dependencies" and "arguments too long" while trying to build a `gi-gtk-4` app on `nixos-unstable`. Poking around in the dark, I managed to get through the build and run the app using `gi-graphene-1.0.5` with some overrides and strictDeps, as mentioned in https://github.com/NixOS/nixpkgs/issues/41340:

```nix
overlay = final: prev: let
  gtkDeps = [
    final.graphene final.gdk-pixbuf final.gtk4
    final.pcre final.pcre2
    final.util-linux.dev final.libselinux final.libsepol
    final.fribidi final.libthai final.libdatrie final.xorg.libXdmcp
  ];
in {
  haskell = prev.haskell // {
    packageOverrides = hfinal: hprev:
      prev.haskell.packageOverrides hfinal hprev // {
        gi-graphene = (hfinal.callHackage "gi-graphene" "1.0.5" {
          graphene-gobject = final.graphene;
        }).overrideAttrs (oldAttrs: { strictDeps = true; });
        gi-gsk = (hfinal.callHackage "gi-gsk" "4.0.7" { }).overrideAttrs (oldAttrs: { strictDeps = true; buildInputs = gtkDeps; });
        gi-gdk = (hfinal.callHackage "gi-gdk" "4.0.7" { }).overrideAttrs (oldAttrs: { strictDeps = true; buildInputs = gtkDeps; });
        gi-gtk = (hfinal.callHackage "gi-gtk" "4.0.8" { }).overrideAttrs (oldAttrs: { strictDeps = true; buildInputs = gtkDeps; });
        "${name}" = hfinal.callCabal2nix name ./. { };
      };
  };
  "${name}" = final.haskell.lib.compose.justStaticExecutables final.haskellPackages.${name};
};
```

Haven't done much but draw some pixels to the screen, so no idea if it'll break somewhere else at runtime, but so far it hasn't complained.

**Comment by sternenseemann** [comment]
This was resolved in cabal2nix.

**Pull request closed without merging**
