### PR TITLE
Fixing nixos-generate-config

### LINKED ISSUE #3560: nixos-generate-config: misplaced double quotes in boot.extraModulePackages
I am trying to install NixOS on MacBook 5,1.  The *hardware-configuration.nix* file generated with `nixos-generate-config` contained this line:
```
boot.extraModulePackages = [ "config.boot.kernelPackages.broadcom-sta" ];
```
`nixos-install` failed with the message
> The option value `boot.extraModulePackages' in `/etc/nixos/hardware-configuration.nix' is not a list of paths.

The error went away after i had removed the double quotes.

### PR DESCRIPTION
**Pull request by jagajaga**
fix https://github.com/NixOS/nixpkgs/issues/3560

(Working nicely for me)

### CODE REVIEW

**Comment by jagajaga** [comment]
cc @edolstra

**Comment by jagajaga** [comment]
If there are no objections, I'm going to merge this in a day.

**Comment by domenkozar** [comment]
:cake:

**Comment by vcunat** [comment]
You seem to take care of lots of issues and PRs :-)

**Comment by jagajaga** [comment]
@vcunat what do you mean? :)

**Comment by vcunat** [comment]
I think you significantly help handling the inflow of issues and pull requests, as confirmed by https://github.com/NixOS/nixpkgs/commits?author=jagajaga

**Comment by jagajaga** [comment]
@vcunat oh, stop it, you http://i.imgur.com/ea1LOX7h.jpg :D

**Comment by vcunat** [comment]
:-)

**Pull request merged**
