### PR TITLE
glibcCross: use a libgcc built separately from gcc

### LINKED ISSUE #213453: `mbuffer`: cross-compiled libgcc_s.so.1 must be built with glibc headers for pthread_cleanup_push() to work
### Describe the bug

On `armv7l-linux` or `aarch64-linux` cross-compiled from `x86_64-linux`, `mbuffer` breaks:

```
$ echo "hello" | mbuffer
hello
libgcc_s.so.1 must be installed for pthread_exit to work
Aborted (core dumped)
```

From `armv7l-linux`:

```
Module linux-vdso.so.1 with build-id 04745a31932e964ec4cd2f2af22bff73c959bc5d
Module libatomic.so.1 without build-id.
Module libdl.so.2 with build-id e21ee3b08115e4ff693e068a5ae47e30a6eed56e
Module ld-linux-armhf.so.3 with build-id 5450bffccfed072763370bd64a69b6ea758babb1
Module libc.so.6 with build-id cc4343a8abc2fde08e30176f06b9f4385f438ef5
Module libpthread.so.0 with build-id 6b805729d47513ad23db66eeac106a69998cb666
Module libm.so.6 with build-id 9350661951669899d3d720161626db749d157003
Module libcrypto.so.3 with build-id f4a6e190dcfd9af5793d9afd5cd89ef82559a3e4
Module mbuffer without build-id.
Stack trace of thread 2019:
#0  0x00000000b6a7b2f8 __pthread_kill_implementation (libc.so.6 + 0x7b2f8)
ELF object binary architecture: ARM
```

### Steps To Reproduce

You can either run this on another architecture using `boot.binfmt.emulatedSystems = [ "armv7l-linux" "aarch64-linux" ]`.

```console
$ nix build nixpkgs#pkgsCross.aarch64-multiplatform.mbuffer
$ echo "hello" | result/bin/mbuffer
```

or

```console
$ nix build nixpkgs#pkgsCross.armv7l-hf-multiplatform.mbuffer
$ echo "hello" | result/bin/mbuffer
```

### Expected behavior

`mbuffer` should not crash:

```
$ echo "hello" | mbuffer
hello
summary:  0.0 kiByte in  0.0sec - average of  0.0 kiB/s
```

### Additional context

This was responsible for `syncoid` failing to replicate datasets to my ARM NAS.

The issue does _not_ occur for natively compiled `aarch64-linux` builds. It appears to be a cross-compilation issue only.

### Notify maintainers

@tokudan @skeuchel 

### Metadata

```console
 - system: `"armv7l-linux"`
 - host os: `Linux 6.1.8, NixOS, 22.11 (Raccoon), 22.11.20230127.cc4bb87`
```

### PR DESCRIPTION
**Pull request by ghost**
### Summary

This PR completely and finally solves the gcc<->glibc circular `buildInputs` problem, for cross compilation.  The same technique can be applied to native builds in the future.

Closes #213453

### Motivation

Prior to this PR, we had the following circular `buildInputs` problem:

1. gcc has glibc in its `buildInputs`
   - a compiled copy of glibc must be present before building gcc; if it isn't, gcc cripples     itself (`inhibit_libc`) and refuses to build libgcc_s.so

2. glibc has libgcc_s.so in its `buildInputs`
   - glibc `dlopen()`s libgcc_s.so in order to implement POSIX          thread cancellation.  For security reasons [`glibc` requires that the path to `libgcc_s.so` is hardwired into `glibc` at compile time](https://github.com/NixOS/nixpkgs/blob/7553d0fe29801938bcb280bb324b579ef9016aea/pkgs/development/libraries/glibc/default.nix#L69-L88), so it's technically not a true dynamic link -- it just pretends to be one.

3. libgcc_s.so is built in the same derivation as gcc
   - libgcc_s.so is built as part of the gcc build          process

We must cut one of these three links in the loop.

### Previous Attempts

Previously https://github.com/NixOS/nixpkgs/pull/238154 had attempted to cut link (1) by building `gcc` without `glibc`, and using the `libgcc_s` which emerges from that build.  Unfortunately this just doesn't work.  GCC's configure script extracts quite a lot of information from the glibc headers (which are a build artifact -- you can't just copy them out of the source tarball) and various `./configure`-driven linking attempts.  If `glibc` isn't around at build time you wind up with a `libgcc_s.so` that is missing various unwinder features (see https://github.com/NixOS/nixpkgs/issues/213453 for the most problematic one).

Musl "cuts" link (2), or rather never creates it in the first place.  ["Cancellation cleanup handling in musl has no relationship to C++ exceptions and unwinding... glibc implements cancellation as an exception"](https://wiki.musl-libc.org/functional-differences-from-glibc.html#Thread-cancellation).  IMHO Musl made the smarter decision here.  It is incredibly rare to find a codebase that uses both POSIX thread cancellation *and* C++ exceptions.  I have never seen a codebase that uses both *and* expects them to be aware of each other, and I would be astonished if one existed.  Glibc paid an immense cost in complexity for something nobody has ever used.

### Changes Made

This PR cuts  link (3): instead of building libgcc_s.so as part of gcc, we build  it separately from gcc.  Now there is a strict acyclic graph of `buildInputs`:

```
 gccWithoutTargetLibc
 |
 +--->glibc-nolibgcc
 |    |
 |    v
 +--->libgcc
 |    |
 |    v
 +--->glibc
 |    |
 |    v
 +--->gcc
```

In other words, there's a simple linear `buildInputs` chain `glibc-nolibgcc` `->` `libgcc` `->` `glibc` `->` `gcc` where all four packages are compiled by (and therefore have as a `(native)BuildInput`) `gccWithoutTargetLibc`.

`gccWithoutTargetLibc` and `glibc-nolibgcc` are strictly bootstrapping artifacts; nothing else has them as a `buildInput` and they shouldn't appear in the closure of any final deployment packages.  `glibc-nolibgcc` lacks `libgcc_s.so`, so it will segfault if you try to use it with POSIX thread cancellation.  Fortunately all we need from it is (a) its headers (`lib.getDev`) and (b) to use it in the `./configure` script for `libgcc`.

When translated over to the native bootstrap, `xgcc` takes the place of `gccWithoutTargetLibc`, and the "first `glibc`" (we build two of them) takes the place of `glibc-nolibgcc`.  At that point our native and cross bootstrap have the same overall architecture, and it becomes possible to merge them (at last!)

### CODE REVIEW

**Comment by amjoseph-nixpkgs** [comment]
@ofborg build tests.cross.mbuffer

**Comment by amjoseph-nixpkgs** [comment]
@ofborg build tests.cross.mbuffer

**Comment by amjoseph-nixpkgs** [comment]
@ofborg eval

**Comment by amjoseph-nixpkgs** [comment]
Figured out how to do this without a rebuild of native `stdenv`; base has been switched to `master`.

**Comment by amjoseph-nixpkgs** [comment]
Built:

- [x] `tests.cross.sanity`

@Majiir, as the reporter of the bug which this fixes, would you mind verifying the fix?  If you can confirm that and approve this PR, I intend to merge it; then you won't need to carry a patch any longer.

**Comment by amjoseph-nixpkgs** [comment]
> Building `pkgsCross.armv7l-hf-multiplatform.glibc` fails ([full build log](https://gist.githubusercontent.com/Majiir/704c3a0df4ed615ed30641cfb1b4b47e/raw/a98cf2795426151a04af0c0c927a887d24f04dc0/gistfile0.txt)):

Thanks for catching this, @Majiir.

- Fix is in 322acc7
- Regression test for `armv7hf` is in ac86ffc (so I don't miss this again)

**Comment by amjoseph-nixpkgs** [comment]
> [36909cf](https://github.com/NixOS/nixpkgs/commit/36909cfb3d0e67e3795ec5bfc512032325317c5b) and [1fea173](https://github.com/NixOS/nixpkgs/commit/1fea17366181b22832378d0a537721dc4c1e4369) fail with `infinite recursion encountered`

I've squashed these two commits into the commit after them.

I originally separated them in order to try to change only one package per commit, but unfortunately that creates non-evaluable commits in the history which -- as you noticed -- is a pain when `git bisect`ing.

**Review by Majiir — APPROVED** [review]
Build successful, and it fixes the `mbuffer` issue. :tada: I tested it on my armv7l hardware (cross-compiled from x86_64) to be sure.

I'm also trying to cross-compile my whole armv7l system on this branch, but currently running into build failures on latest master (unrelated to this PR). I'll update if I get a successful build or run into any problems.

I spent some time reading through your commits. I'm not qualified to give these changes a critical review, but it generally looks good to me.

Thank you for your efforts on this and for looking after the core bits of nixpkgs!

**Comment by amjoseph-nixpkgs** [comment]
> I'm also trying to cross-compile my whole armv7l system on this branch

Let me know how it goes!  If you run into any problems that manifest for cross but not for native let me know; there's a good chance I've seen them before.  I mostly hang out in `#tvl` on hackint.org.

**Comment by lopsided98** [comment]
I get the `arm-isa.h: No such file or directory` error on armv6l and armv5tel; https://github.com/NixOS/nixpkgs/commit/322acc798714c06c64b4ca5bc4865de269a84581 probably needs to be expanded to cover all 32-bit ARM architectures.

**Pull request merged**
