### PR TITLE
Add freefall: hard drive protection on HP/Dell laptops

### PR DESCRIPTION
**Pull request by nckx**
Shipped in the kernel's Documentation directory, yet works perfectly.

Simple NixOS service module included.

Tested on HP. If you have a Dell, drop it and let me know what happens.

### CODE REVIEW

**Comment by lethalman** [comment]
I'm unable to build `linuxPackages.freefall`, not sure if it's a problem of mine:

```
building path(s) `/nix/store/xy4i03aadj9nbax7lnizr78v6kidjg03-freefall-3.14.27'
building /nix/store/xy4i03aadj9nbax7lnizr78v6kidjg03-freefall-3.14.27
unpacking sources
unpacking source archive /nix/store/mgqpnnvmbrzva4pdbadlyai4phrajhg4-linux-3.14.27.tar.xz
source root is linux-3.14.27
patching sources
configuring
no configure script, doing nothing
building
cat: Documentation/laptops/freefall.c: No such file or directory
/nix/store/nrxyygy0wqski1klq0305d3h523k41ps-glibc-2.20/lib/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
builder for `/nix/store/8synixmrk1d2ks1q93s6d97kppf3chyk-freefall-3.14.27.drv' failed with exit code 1
error: build of `/nix/store/8synixmrk1d2ks1q93s6d97kppf3chyk-freefall-3.14.27.drv' failed
```

**Comment by nckx** [comment]
Peh. It turns out that `freefall.c` only exists under that name since July 2014 - before that it was called `hpfall.c`. Travis refused (still does) to load logs on my current browser so I just assumed it was a transient failure.

I'll pop this back out of linuxPackages, into a normal top-level package that simply depends on _one_ supported kernel version `${version}`.

**Comment by nckx** [comment]
Done.

`freefall` is now a normal package that doesn't try to do any per-version kernel source magic.

**Comment by lethalman** [comment]
Can't merge, would you update the PR?

**Comment by nckx** [comment]
Done. Travis is on the blink again.

**Comment by lethalman** [comment]
Built locally, thanks.

**Pull request merged**
