### PR TITLE
[WIP]linux_testing_bcachefs : 5.3.2020.04.04 -> 5.6.2020.06.04

### PR DESCRIPTION
**Pull request by pasqui23**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wmertens** [comment]
@pasqui23 could you update? It's based on 5.7 now

**Comment by wmertens** [comment]
Lgtm - is this still WIP or can I merge?

**Comment by pasqui23** [comment]
The 5.7 version does not compile (the error came right at the end of the compilation) and now I can't even compile the 5.6 version (I get `fatal: reference is not a tree` error on fetching the src)

**Comment by pasqui23** [comment]
So this time I'm waiting for the kernel to finish compiling before publishing the result

**Comment by wmertens** [comment]
The reference is not a tree probably means the ref no longer exists because it was forced pushed

**Comment by pasqui23** [comment]
So it tyrns out that the problems with the

**Pull request closed without merging**
