### PR TITLE
onnxruntime: remove

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
I tried to bump this, https://github.com/jonringer/nixpkgs/commit/18255bd69755c3e2dd1b6af13472c6c55e98a0f9, but gave up.

Poor cmake and git hygiene has made maintaining this difficult, see:
https://github.com/microsoft/onnxruntime/issues/5966
https://github.com/microsoft/onnxruntime/issues/5967

I'm not aware of anyone using this package. I added it because it seemed like it may have been a more crucial ML package a year ago.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by blitz** [comment]
It could be interesting to resurrect this to package https://github.com/royshil/obs-backgroundremoval, which is a pretty epic OBS Studio plugin.

**Comment by blitz** [comment]
> Well, if they make it so that you can import external resources, but it was annoying to have to checkout ~1GB of sources and dependencies for what should be ~4-12MB of source.
> 
> https://github.com/microsoft/onnxruntime/blob/master/.gitmodules

Very true. Your Nix expressions still work to build it though, even the latest version. Will look into reviving this when I get chance. Maybe things have improved.

**Comment by jonringer** [comment]
Also, they version control their testdata, which adds like 70MB, which is like 1/2 the checkout size.

I asked if they could use lfs for testdata in https://github.com/microsoft/onnxruntime/issues/5967.

Also, they really need to be following cmake best practices for dependency management. For example https://github.com/microsoft/onnxruntime/blob/master/cmake/external/eigen.cmake should really be using something like `find_package` to find the eigen dependency; instead of expecting another `eigen_SOURCE_PATH` to just point to it. Which was part of https://github.com/microsoft/onnxruntime/issues/5966

**Comment by puffnfresh** [comment]
@blitz coincidentally I started work on this tonight and got fairly far. `onnxruntime` added `onnxruntime_PREFER_SYSTEM_LIB` which works pretty well for a bunch of libraries. There's still things like `re2` which aren't being picked up but things like protobuf, howard-hinnant-date, flatbuffers and nsync (which I packaged) get picked up and used, instead.

**Comment by blitz** [comment]
> @blitz coincidentally I started work on this tonight and got fairly far. `onnxruntime` added `onnxruntime_PREFER_SYSTEM_LIB` which works pretty well for a bunch of libraries. There's still things like `re2` which aren't being picked up but things like protobuf, howard-hinnant-date, flatbuffers and nsync (which I packaged) get picked up and used, instead.

Awesome! If you open a PR please tag me.

**Comment by puffnfresh** [comment]
image

@blitz works surprisingly well, I'll try to push my WIP tomorrow morning.

**Pull request merged**
