### PR TITLE
octave: darwin fix

### PR DESCRIPTION
**Pull request by veprbl**
###### Motivation for this change

Fix octave on darwin.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [x] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

octave build would fail on mac during a test of openblas ABI. I've tried recompiling openblas with different C compilers. It's build system was not willing to appreciate GCC on darwin system. Using different versions of clang (3.6, 3.9) didn't give any positive results. 32bit ABI seems to be a good and quick workaround.

### CODE REVIEW

**Comment by acowley** [comment]
The `fltk` fix is good. I have a similar fix locally that I was going to PR soon. 

The `openblas` change seems strange to me. I've used `octave` on Darwin for a while now; what change introduced the new breakage?

**Comment by veprbl** [comment]
If you look on the hydra the breakage goes back through all available history. One could git-bisect, but that might require a lot of building. This fixes the build and octave still knows that 2+2=4, so this is enough for my needs.

**Comment by acowley** [comment]
Okay. I use `openblasCompat` when building `octave` as that's the usual 32 bit int solution in `nixpkgs`, but I admit I haven't built it in a few weeks, so perhaps that approach stopped working. I can take a look tomorrow. Thank you for pushing this forward!

**Comment by veprbl** [comment]
Using openblasCompat is effectively what I'm pushing with this PR.

**Comment by acowley** [comment]
Any reason not to conditionally pass `openblasCompat` from `all-packages` then? That keeps the `openblas` dependency easily overridable, and is the approach used for other packages.

**Comment by veprbl** [comment]
Yes, implemented.

**Comment by acowley** [comment]
And sorry for being confused about `octave`'s buildability. I guess I've had that `openblasCompat` tweak in my `config.nix` for a while.

**Comment by veprbl** [comment]
@acowley No problem!

**Comment by acowley** [comment]
What I meant was something more like the [`julia` definition](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L4980). Since this aspect of `octave` seems to only be a problem on `darwin`, we could say `openblas = if stdenv.isDarwin openblasCompat else openblas;` when calling the `octave` function from `all-packages`.

I don't know how important this consistency is, but some effort was taken to rationalize the various numerical computation components by @ttuegel I think.

**Comment by ttuegel** [comment]
> What I meant was something more like the julia definition. Since this aspect of octave seems to only be a problem on darwin, we could say openblas = if stdenv.isDarwin openblasCompat else openblas; when calling the octave function from all-packages.

This is generally the preferred way.

**Comment by veprbl** [comment]
When I was creating this PR I thought that this would be only a temporary solution so that somebody interested in octave on darwin could eventually fix this properly. What you propose does provide a slightly better interface for overrides, but it also sweeps the problem under the rug (top-packages) where it will be less visible. I don't have a specific preference here, so if you are sure, I can update the PR in a little while.

**Comment by acowley** [comment]
I agree with the misgivings about putting logic in `all-packages`, but I think it's the way `openblasCompat` is meant to be used (as an override for a package that depends on `openblas`). Likewise for `julia`, really, where the package calls its parameter `openblas`, but `openblasCompat` is swapped in. If you were to `callPackage` `julia` yourself, you'd have to get it right.

I truly don't have strong feelings on this, and I'm fine taking some maintenance responsibility whichever way we go with this PR in case it becomes a question again in the future. I can't merge in any case, so someone else will have to chime in.

**Pull request merged**
