### PR TITLE
Updates to git-crypt and LXC

### PR DESCRIPTION
**Pull request by ip1981**
https://github.com/AGWA/git-crypt/pull/73

### CODE REVIEW

**Comment by ip1981** [comment]
Also ensures that GnuPG from Nix store is used.

**Comment by dochang** [comment]
I think this patch should be committed into the upstream, like AGWA/git-crypt#73 .

We should not change the upstream behavior.  If the upstream switches to gpg2, we'll follow it.

But there's one fix that we should commit is: adding gpg / gpg2 to the dependency list.  I'll do this once AGWA/git-crypt#73 and AGWA/git-crypt#65 are closed.

**Comment by dochang** [comment]
3f4b9f8 seems not related to git-crypt, please split your PR.

**Comment by ip1981** [comment]
https://github.com/NixOS/nixpkgs/pull/11774
https://github.com/NixOS/nixpkgs/pull/11773

**Pull request closed without merging**
