### PR TITLE
amarok,borg: split doc into separate output

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Motivation for this change

The borgbackup doc is 7.3MB alone (package without docs is 4.5M) and the amarok doc is 45M (package without is 67M).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 117945` at 782f17ed run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>borgbackup</li>
    <li>borgmatic</li>
  </ul>
</details>

**Comment by peterhoeg** [comment]
Why are we doing this? It makes sense to do with libraries so things that depend on them do not need to carry documentation but for end-user applications, I don't really see the point.

**Comment by flokli** [comment]
Please fill the "motivation for this change" field, or provide a more detailed commit message.

**Comment by SuperSandro2000** [comment]
> Why are we doing this?

To get down package size.

The borgbackup doc is 7.3MB alone (package without docs is 4.5M) and the amarok doc is 45M (package without is 67M).

**Comment by mweinelt** [comment]
This seems to relate to the `documentation.doc.enable` option and works for packages in `environment.systemPackages`.

https://github.com/NixOS/nixpkgs/blob/857c9ace86e313270415629040136a8442e0607b/nixos/modules/misc/documentation.nix#L251-L254

**Review by mweinelt — APPROVED** [review]
LGTM.

Failures on aarch64 unrelated, looks like qtwebengine issue.

**Review by dotlambda — COMMENTED** [review]
The commit message should have said "borgbackup".

**Comment by mweinelt** [comment]
Right, can we fixup the directory name as well then?

**Comment by SuperSandro2000** [comment]
> The commit message should have said "borgbackup".

I use directory names to generate most of my commit message prefixes.

**Pull request merged**
