### PR TITLE
coreutils: Skip another test that fails on btrfs

### PR DESCRIPTION
**Pull request by knedlsepp**
###### Description of changes

Make `coreutils` build on machines backed by `btrfs`.
Reported on [discourse](https://discourse.nixos.org/t/coreutils-9-0-wont-build/21212/5).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by vcunat — APPROVED** [review]
OK, probably.  I'm not running into this, but I have `boot.tmpOnTmpfs = true;` everywhere.

**Comment by vcunat** [comment]
I wonder if upstream has ever been contacted about these unreliable tests.

**Comment by dasJ** [comment]
People still use btrfs? :O

**Review by dasJ — APPROVED** [review]

**Comment by knedlsepp** [comment]
> People still use btrfs? :O

I don't know much about file system choices, I only did that to replicate Women's notebook setup (as I bought the same one) https://gist.github.com/domenkozar/c1da433406807255f9aa835d72976470

**Comment by vcunat** [comment]
:-D  "Women's" took me quite a while to understand right.  I don't think it was meant seriously; to me btrfs seems a relatively popular choice.

**Pull request merged**
