### PR TITLE
zeek: 5.2.0 -> 6.0.1

### LINKED ISSUE #258954: Update request: zeek 5.2.2 → 6.0.1
- Package name: zeek
- Latest released version: [6.0.1](https://github.com/zeek/zeek/releases/tag/v6.0.1)

- Current version on the unstable channel: 5.2.2
- Current version on the stable/release channel: 5.2.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@pSub @marsam @tobim

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by tobim**
## Description of changes

https://github.com/zeek/zeek/blob/v6.0.1/NEWS
Does not work with system spicy, so it must use the bundled one now.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Resolves #258954.

### CODE REVIEW

**Comment by cornedor** [comment]
Result of `nixpkgs-review pr 261203` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>python310Packages.zeek (python310Packages.zeek.py)</li>
    <li>python311Packages.zeek (python311Packages.zeek.py)</li>
    <li>zeek</li>
  </ul>
</details>

**Review by marsam — APPROVED** [review]

**Comment by MikaelFangel** [comment]
@tobim After this merge `zkg` and `zeekctl` also becomes available through the PATH, but the `zkg` and `zeekctl` are missing their dependencies. I would very much like to see these packages worked and also maybe if `zkg` works the corresponding standalone package should be dropped. I suspect that the standalone-zkg nixpkg would conflict with this now.

So far I've got `zeekctl` to work by just adding `python3` to the `buildInputs`, but I still have some issues with `zkg`.

zkg error message:
```bash
error: zkg failed to import one or more dependencies:

* GitPython:        https://pypi.org/project/GitPython
* semantic-version: https://pypi.org/project/semantic-version

If you use 'pip', they can be installed like:

     pip3 install GitPython semantic-version

Also check the following exception output for possible alternate explanations:

ModuleNotFoundError: No module named 'git'
```

**Comment by tobim** [comment]
I agree that a dedicated `zkg` package doesn't make much sense, but I'm not sure of its value when Zeek itself is managed via Nix. Fixes are welcome though.

**Comment by marsam** [comment]
Would you mind trying the following?
```diff
--- a/pkgs/applications/networking/ids/zeek/default.nix
+++ b/pkgs/applications/networking/ids/zeek/default.nix
@@ -22,6 +22,7 @@
 
 let
   broker = callPackage ./broker { };
+  python = python3.withPackages (p: [ p.gitpython p.semantic-version ]);
 in
 stdenv.mkDerivation rec {
   pname = "zeek";
@@ -43,7 +44,6 @@ stdenv.mkDerivation rec {
     cmake
     file
     flex
-    python3
   ];
 
   buildInputs = [
@@ -54,13 +54,13 @@ stdenv.mkDerivation rec {
     libpcap
     ncurses
     openssl
+    python
     swig
     zlib
   ] ++ lib.optionals stdenv.isLinux [
     libkqueue
   ] ++ lib.optionals stdenv.isDarwin [
     gettext
-    python3
   ];
```

**Comment by MikaelFangel** [comment]
That indeed did the trick!

**Pull request merged**
