### PR TITLE
linux_testing_bcachefs: 5.13-2021-07-08 -> 5.13.2021-09-22

### PR DESCRIPTION
**Pull request by jnsaff**
###### Motivation for this change
bcachefs needs to be updated as there have been lot of developments.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by davidak** [comment]
why did you revert the bcachefs-tools update? shouldn't it be in sync?

in any case, please squash the commits

**Comment by jnsaff** [comment]
> why did you revert the bcachefs-tools update? shouldn't it be in sync?
Two reasons really.
1. I thought they are expected as separate PR's in general, no?
2. bcachefs-tools build fails and I'd need to investigate how to fix that. 

> in any case, please squash the commits
I will do that.

**Comment by davidak** [comment]
>I thought they are expected as separate PR's in general, no?

since they are related and should be updated together, it's ok to have them in one PR, even one commit

so when someone checks out that commit, it works

>bcachefs-tools build fails and I'd need to investigate how to fix that.

maybe choose another commit if the problem is upstream

**Comment by jnsaff** [comment]
Alright, I fixed the issue with tools build and combined them into one commit.

**Comment by davidak** [comment]
@jnsaff sorry i was not able to test this in time.

**Pull request closed without merging**
