### PR TITLE
ocamlPackages.gen: 1.0 → 1.1

### PR DESCRIPTION
**Pull request by vbgl**
###### Description of changes

Support for OCaml 5.0: https://github.com/c-cube/gen/blob/v1.1/CHANGELOG.md

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by romildo** [comment]
Is it supposed to build with ocaml 5.0?

I am getting the following:

```console
$ nix-build --option sandbox true -K -A ocaml-ng.ocamlPackages_latest.gen 2>&1
this derivation will be built:
  /nix/store/y7zyzyyzp9gfi09s5jpd9r6v3g3zpc6a-ocaml5.0.0-gen-1.1.drv
building '/nix/store/y7zyzyyzp9gfi09s5jpd9r6v3g3zpc6a-ocaml5.0.0-gen-1.1.drv'...
unpacking sources
unpacking source archive /nix/store/3bviq3r9snsxz9mmah6b1pii87kn4i8d-source
source root is source
patching sources
configuring
no configure script, doing nothing
building
running tests
File "/nix/store/vl7fvzpl45s7hqrf00j6r0594m5xjx4w-ocaml5.0.0-ounit2-2.2.6/lib/ocaml/5.0.0/site-lib/ounit2/dune-package", line 24, characters 16-21:
24 |  (requires unix bytes seq stdlib-shims)
                     ^^^^^
Error: Library "bytes" not found.
-> required by library "ounit2.advanced" in
   /nix/store/vl7fvzpl45s7hqrf00j6r0594m5xjx4w-ocaml5.0.0-ounit2-2.2.6/lib/ocaml/5.0.0/site-lib/ounit2/advanced
-> required by executable run_qtest in qtest/dune:9
-> required by _build/default/qtest/run_qtest.exe
-> required by alias qtest/runtest in qtest/dune:13
(cd _build/default/qtest && /nix/store/9qdfdlnzx4kgk5jqpim1xkrmp31bcraw-gnumake-4.4.1/bin/make qtest-gen)
sh: line 1: which: command not found
```

**Comment by vbgl** [comment]
Yes. As you can see in that log, it builds fine. Then tests fail because `ounit2` is not yet compatible with OCaml 5.

**Review by romildo — APPROVED** [review]

**Comment by ulrikstrid** [comment]
Would it make sense to not run tests on OCaml 5 then?

**Review by ulrikstrid — APPROVED** [review]
Then ship it!

**Pull request merged**
