### PR TITLE
vapoursynth: Simplify plugin loading

### PR DESCRIPTION
**Pull request by illdefined**
## Description of changes

These changes further simplify the plugin loading mechanism:

Instead of generating code to load every single plugin through a callback function, the plugin path of the combined plugin environment is exposed as a character array and used as default system plugin directory.

This allows plugin loading to be modified through configuration.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by illdefined** [comment]
Result of `nixpkgs-review pr 332800` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>av1an</li>
    <li>av1an-unwrapped</li>
    <li>python311Packages.vapoursynth</li>
    <li>python311Packages.vapoursynth.dist</li>
    <li>python312Packages.vapoursynth</li>
    <li>python312Packages.vapoursynth.dist</li>
    <li>svp</li>
    <li>vapoursynth</li>
    <li>vapoursynth-editor</li>
    <li>vapoursynth-mvtools</li>
  </ul>
</details>

**Review by snaakey — APPROVED** [review]

**Comment by rnhmjoj** [comment]
cc: @tadeokondrak who came up with the `vapoursynth.withPlugins` interface.

**Comment by illdefined** [comment]
An alternative to this plugin loading approach could be to provide a configuration file with a system plugin directory path, through the `VAPOURSYNTH_CONF_PATH` environment variable.

This could be done through a NixOS module or through wrappers, but both options have disadvantages. The former obviously precludes non‐NixOS use and the latter requires wrapping all binaries linked against libvapoursynth.

I also considered if there might be a good reason for loading all the plugins individually, but as far as I can tell, it should not make a difference.

**Comment by tadeokondrak** [comment]
> cc: @tadeokondrak who came up with the `vapoursynth.withPlugins` interface.

lgtm, the weak symbol was the important part and that stays. Good cleanup here

**Comment by illdefined** [comment]
Any objections to merging this?

I tested the modified mechanism successfully with vspipe, vsedit and mpv, both with and without plugins, on 6 August.

**Comment by rnhmjoj** [comment]
No objection from me, but I haven't tested this yet. I will try it soon.

**Review by rnhmjoj — APPROVED** [review]
Ok, the plugins seems to be working as before.

**Pull request merged**
