### PR TITLE
treewide: unpin go

### PR DESCRIPTION
**Pull request by kirillrdy**
###### Description of changes

these all i could find in all-packages.nix that do build with go 1.20 now

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 235467` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>cloudflared</li>
    <li>kube-router</li>
  </ul>
</details>
<details>
  <summary>20 packages built:</summary>
  <ul>
    <li>browserpass</li>
    <li>dnsproxy</li>
    <li>erigon</li>
    <li>eris-go</li>
    <li>grafana-agent</li>
    <li>ipfs-cluster</li>
    <li>kubo</li>
    <li>kubo.systemd_unit</li>
    <li>kubo.systemd_unit_hardened</li>
    <li>open-policy-agent</li>
    <li>pcp</li>
    <li>prometheus-openldap-exporter</li>
    <li>protonmail-bridge</li>
    <li>python310Packages.ipwhl</li>
    <li>python310Packages.ipwhl.dist</li>
    <li>python311Packages.ipwhl</li>
    <li>python311Packages.ipwhl.dist</li>
    <li>sftpgo</li>
    <li>toxiproxy</li>
    <li>victoriametrics</li>
  </ul>
</details>

**Comment by kirillrdy** [comment]
`kube-router-1.5.4` indeed fails on aarch64-linux but `cloudflared` builds for me, maybe flaky test ?

**Comment by kirillrdy** [comment]
Result of `nixpkgs-review pr 235467` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>21 packages built:</summary>
  <ul>
    <li>browserpass</li>
    <li>cloudflared</li>
    <li>dnsproxy</li>
    <li>erigon</li>
    <li>eris-go</li>
    <li>grafana-agent</li>
    <li>ipfs-cluster</li>
    <li>kubo</li>
    <li>kubo.systemd_unit</li>
    <li>kubo.systemd_unit_hardened</li>
    <li>open-policy-agent</li>
    <li>pcp</li>
    <li>prometheus-openldap-exporter</li>
    <li>protonmail-bridge</li>
    <li>python310Packages.ipwhl</li>
    <li>python310Packages.ipwhl.dist</li>
    <li>python311Packages.ipwhl</li>
    <li>python311Packages.ipwhl.dist</li>
    <li>sftpgo</li>
    <li>toxiproxy</li>
    <li>victoriametrics</li>
  </ul>
</details>


I've dropped `kube-router`

**Comment by mweinelt** [comment]
> `cloudflared` builds for me, maybe flaky test ?

Failed on two different machines yesterday, worked on the first try today. :shrug:

**Pull request merged**
