### PR TITLE
isabelle: Rebuild isabelle_setup.jar

### PR DESCRIPTION
**Pull request by jvanbruegge**
This jar contained a call to /usr/bin/env bash which was causing an
error during the build of the HOL session (which could be ignored) and
caused other errors during the development of https://github.com/NixOS/nixpkgs/pull/157515
 (which could not be ignored). This commit patches the java sources to
 call `bash` directly and rebuild the jar.

###### Motivation for this change

Fix the error during the build from #154272

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jvanbruegge** [comment]
cc @gebner

**Comment by jvanbruegge** [comment]
cc @siraben because you merged isabelle stuff in the past :)

**Comment by jvanbruegge** [comment]
ping @gebner 
It has been almost a month :)

**Comment by gebner** [comment]
Feel free to take over the Isabelle package and merge at your own discretion.  You certainly know more about Isabelle than I do!

**Comment by jvanbruegge** [comment]
I do not have commit access, and not enough packages to get it sadly

**Comment by gebner** [comment]
Oh sorry, I saw that you're a member of the nixos org and blindly assumed that this meant you had commit access.

**Pull request merged**
