### PR TITLE
Semi-automated Emacs package updates

### PR DESCRIPTION
**Pull request by mdorman**

### CODE REVIEW

**Comment by matthewbauer** [comment]
Still getting the following trying to eval:

```
nixpkgs $ nix-instantiate -A emacsPackagesNg.melpaPackages
error: anonymous function at /Users/mbauer/Projects/nixpkgs/pkgs/applications/editors/emacs-modes/melpa-generated.nix:1594:34 called without required argument ‘font-lock-plus’, at /Users/mbauer/Projects/nixpkgs/lib/customisation.nix:74:12
```

Is it possible to fix easily?

**Comment by adisbladis** [comment]
@matthewbauer I have a PR for this https://github.com/NixOS/nixpkgs/pull/31302

**Comment by orivej** [comment]
@adisbladis Thank you for the reminder, I've merged it.

How do we test such updates to many emacs packages? Can we require everything provided by `emacsWithPackages`?

**Review by orivej — APPROVED** [review]

**Comment by mdorman** [comment]
@orivej If someone wanted to put together a hydra job that would trigger when I pushed to a branch, I'd be happy to do that.  It should be fairly light-weight to evaluate all the expressions.

**Comment by orivej** [comment]
Automatic evaluation of emacs packages would be great, but I was thinking about testing the packages with Emacs, e.g. by calling `(require)` for each `(provide)`, or forcing all autoloads.

**Comment by mdorman** [comment]
@orivej That sounds like a nightmare of busywork for anyone trying to keep the package sets current.  It is also a more stringent standard than melpa itself takes.

**Comment by matthewbauer** [comment]
I mean that’s basically what the Emacs compiler is doing right?

**Comment by mdorman** [comment]
@matthewbauer I'm not sure what you mean when you say "the Emacs compiler"?

**Comment by orivej** [comment]
@matthebauer You are right, I forgot about it. But we are missing the ability to build all emacs packages, right? `nix-build -A emacs25PackagesNg` fails with `Package … is marked as broken, refusing to evaluate`, and hydra and nox-review do not recurse into emacs25PackagesNg.

**Comment by orivej** [comment]
@mdorman `emacs -L . --batch -f batch-byte-compile *.el` in `pkgs/build-support/emacs/trivial.nix`.

**Comment by matthewbauer** [comment]
Yeah that's an issue that maybe should be looked at in NixOS/nix.

You can do something like this:

```
nix-build -E 'with import <nixpkgs> {config.allowBroken = true;}; lib.filterAttrs (key: value: (lib.isDerivation value) && !((builtins.hasAttr "broken" value.meta) && value.meta.broken)) emacsPackagesNg'
```

But it's going to be a huge number of packages.

**Comment by mdorman** [comment]
So I tried that `nix-build` expression.  It appears to have done some reasonable amount of testing, in a not-outrageous amount of time, and far fewer packages failed than I expected.  I'll look into incorporating the process into the update workflow.

**Pull request merged**
