### PR TITLE
nixos/pam_mount: fix unmounting and add module config options

### PR DESCRIPTION
**Pull request by NetaliDev**
###### Description of changes

This PR adds new options to the `pam_mount` module and fixes a bug where volumes are not unmounted when logging out.

Additionally, the package `hxtools` is added, which provides the program `ofl` that is required by `pam_mount` to kill programs that still access the mounted volumes after the final logout.

The unmounting problem is caused by `pam_mount` being called multiple times on login, which increases the `pmvarrun` counter (a counter from `pam_mount` which counts the active sessions of a user) by more than 1. However, on logout the counter is only reduced by 1 and the volumes are only unmounted if the counter reached 0 on logout.

Then, for example, if the counter is incremented by 2 on login and decremented by only 1 on logout, the counter will never reach 0 and the volumes will never be unmounted.

This is fixed in the PAM module by using `pam_succeed_if` to call `pam_mount` only when PAM is currently called by `systemd-user`, which happens at every login. This ensures that `pam_mount` is only called once per login and the counter of `pmvarrun` is only incremented by 1.

EDIT: I had misunderstood the `pam_succeed_if` line at first and this fix actually causes `pam_mount` not to be called if the current service is `systemd-user`. It is now only called by `sshd` or similar when logging in (depending on what you use to log in). This can be observed for example by the fact that with enabled debugging of `pam_mount` and an SSH login, debug output still comes from `sshd` after this fix and no longer from `systemd-user`.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by yu-re-ka — APPROVED** [review]
I have no idea about pam and its automatic (un)mounting features, so I don't know how I could test this.
The change looks reasonable and formalities/style are all good.

**Comment by emmanuelrosa** [comment]
- **The new module options:** This looks good. The defaults are set such that users don't have to change anything to maintain the current functionality; Meaning, the change is backwards compatible.
- **The bug fix:** I don't know enough about PAM to have an opinion. But given that PAM is a crucial component, I recommend adding a NixOS test to confirm the behaviour is correct.
- **Adding hxtools:** This concerns me because it's a basket of tools from what appears to be a random website. Due to the critical nature of PAM, I'm not comfortable having it execute programs that are not well reviewed. Where's the documentation which states that `ofl` should be used?

**Comment by yu-re-ka** [comment]
This line was in the module before:

```xml
           <!-- if activated, requires ofl from hxtools to be present -->
```

And i think it only gets added as a dependency when the mount feature is actually enabled, which is not the default? So it might not affect as many users as one might think.

**Review by bbjubjub2494 — APPROVED** [review]
Got it to unmount, the bugfix is lgtm

**Comment by lourkeur** [comment]
> This line was in the module before:
> 
> ```
>            
> ```
> 
> And i think it only gets added as a dependency when the mount feature is actually enabled, which is not the default? So it might not affect as many users as one might think.

`hxtools` did get added to my closure. the `<ofl>` node isn't conditional. I don't think it was invoked though.

`hxtools` also contains a lot of irrelevant programs so it might be good to look into whether `lsof` and `fuser` can be used instead.

**Comment by NetaliDev** [comment]
I have built a wrapper-script around lsof which works as a kind of fake-ofl and it also works nicely. This makes `hxtools` for `pam_mount` obsolete again.

**Pull request merged**
