### PR TITLE
treewide: remove licenses.gpl2

### PR DESCRIPTION
**Pull request by Lurkki14**
## Description of changes

Removed `licenses.gpl2` in favor of `gpl2Only` and `gpl2Plus`, also in some cases the license was incorrectly GPL2.

### Method used

First, I dumped all attributes that had `meta.license = gpl2;`  like so:
```
nix-eval-jobs --meta --force-recurse pkgs/top-level/release.nix 2> /dev/null \
	| jq ' select(.meta.license.shortName=="gpl2") | .attrPath | del(.[-1]) | join(".")' \
    -r --unbuffered 2> /dev/null | tee gpl2attrs
```

I wrote a script to go through them afterwards:

```
while true; do
	attr=$(head -n 1 gpl2attrs)
	if [ -z $attr ]; then
		break
	fi

    echo "Checking sources for $attr"
    NIX_PATH=nixpkgs=. \
        nix-build  --keep-failed --expr "let pkgs = import ./. {}; in  pkgs.srcOnly pkgs.$attr" && rg "any later version" result
    checkPid=$!
    echo "nix-build for $attr done"

    attrFile=$(NIX_PATH=nixpkgs=. nix eval --impure --expr "with import <nixpkgs> {}; pkgs.$attr.meta.position" --raw \
        | sed 's/\:.*$//')

    # Check if file has only one match for 'gpl2'
    matchCount=$(rg -wc "gpl2" $attrFile)
    echo $attr is defined in $attrFile
    if [[ $matchCount == "1" ]]; then
        echo "Press 'o' for gpl2Only, 'p' for gpl2Plus; or just Enter to do nothing (edit manually):"
        read -r choice
        if [ $choice == "o" ]; then
            sed -i 's/gpl2/gpl2Only/g' $attrFile
        fi

        if [ $choice == "p" ]; then
            sed -i 's/gpl2/gpl2Plus/g' $attrFile
        fi
    else
        echo "Found $matchCount matches, edit manually, and Enter when done:"
        read -r vuota
    fi

    sed -i "/$attr/d" gpl2attrs
done
```

This got around 90% of the cases, afterwards I just grepped the repo for "gpl2" and went through them more manually.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by adisbladis** [comment]
I'm a big :-1: on removing `licenses.gpl2'. It has distincly different SPDX id: `GPL-2.0` vs `GPL-2.0-only`.
This field is useful to map data from external packaging tools like `pyproject.toml` to Nix.

**Comment by linsui** [comment]
There is no `GPL-2.0` anymore, it has been deprecated. https://spdx.org/licenses/

**Comment by wegank** [comment]
Would you please split the PR into several smaller ones, probably a dozen, and defer the changes to `lib/licenses.nix`? That way you can have multiple reviewers working in parallel, and changes can be checked and merged more quickly.

**Comment by SuperSandro2000** [comment]
As already said, please split this into smaller PRs as this one is way to big to review and we also pinged already way to many people which is the reason I am going to close this one, not because the change is not wanted or desired. 

Also it is probably a good idea to search if for this there is already a tracking issue and if not we can open one and discuss the process there.

**Pull request closed without merging**
