### PR TITLE
libguestfs: 1.36.3 -> 1.38.0

### PR DESCRIPTION
**Pull request by volth**
minor version bump

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build libguestfs

**Comment by volth** [comment]
@GrahamcOfBorg build libguestfs

**Comment by grahamc** [comment]
Can you theorize why it says there are zero rebuilds?

**Comment by grahamc** [comment]
@GrahamcOfBorg build libguestfs

**Comment by volth** [comment]
> Can you theorize why it says there are zero rebuilds?

where?

**Comment by grahamc** [comment]
https://screenshots.firefox.com/knyg6se4qMIdxueM/github.com

**Comment by volth** [comment]
I have no idea what those zeroes mean, but other PRs have them too

**Comment by volth** [comment]
It it is the number the number of dependents, then zero is ok.
Despite its name, ```libguestfs``` is not a development lib but a set of cli tools (there is a lib and ocaml/perl bindings too but no other package is using it)

**Comment by fpletz** [comment]
@grahamc Maybe because `meta.hydraPlatforms` is empty? :)

**Pull request merged**
