### PR TITLE
idris: fix building on GHC 7.8

### PR DESCRIPTION
**Pull request by abbradar**
Requires https://github.com/NixOS/cabal2nix/pull/165

### CODE REVIEW

**Comment by abbradar** [comment]
@peti , would you prefer to pull this by yourself with the next Hackage regeneration, or can I do this? If latter, am I right to use https://github.com/NixOS/cabal2nix/commit/0e784342dd980c08e238fb8bf412e77cec794cd0 commit (with my patch) instead of HEAD for regeneration?

**Comment by peti** [comment]
Commit c434966 will add the required package. I would pull this patch into the https://github.com/peti/nixpkgs/tree/haskell-updates-ghc7101 branch (which will be merged tomorrow), but unfortunately the patch doesn't apply cleanly because of merge conflicts.

**Comment by peti** [comment]
@abbradar, `cabal2nix` can no longer generate the package set for GHC 7.8.4 right now. To do that, one would have to use https://github.com/NixOS/cabal2nix/commit/44d5592e41e34452e58646070828ba4ee75831a8 with https://github.com/NixOS/cabal2nix/commit/9216d9b97a65b8d934758a0cc84061f2469b360f removed first. Since the new 7.10.1 set will be committed tomorrow, I'd prefer to avoid other updates prior to that to avoid merge conflicts, though. I've already made some changes to Idris in the update branch that look similar to yours.

**Comment by abbradar** [comment]
Right, it would be better to update simultaneously with 7.10.1 change. Thanks for fixing in your update branch, closing this then.

**Pull request closed without merging**
