### PR TITLE
rtags: 2.8-p1 -> 2.10

### PR DESCRIPTION
**Pull request by acowley**
###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by acowley** [comment]
I don't understand the Travis CI failure. It built successfully in two configurations, but a third ends up with an unexpected hash.

**Comment by Mic92** [comment]
the first build only check for evaluation errors. The last two check builds on darwin and linux.

**Comment by Mic92** [comment]
I get the same error as travis:

```
output path ‘/nix/store/5p4zqpdy61bh86l2hmjxsi07caj8zzbf-rtags’ has r:sha256 hash ‘1swcz4p5v6zqzqrxdbxbcvy009k509s4ni8qqg1wyp537qcibwdb’ when ‘0z32yncn3x1pm2l6r349kfwi6mi83vll820kka87agcla64pl1f2’ was expected  
```

I am also on Linux.

**Comment by acowley** [comment]
Thank you @Mic92! Can you think of a reason why the sha256 would be different between darwin and Linux? Doing a `stdenv.isDarwin` check on the hash of the source seems worrying, but I can do so if you think that's the way to go.

**Comment by Mic92** [comment]
Maybe `fetchgit` is not so reproducible as it should be. It could be something fs related, which leads to a deviation in the checksum. However this is the first time I encounter that.

**Comment by Mic92** [comment]
nix-prefetch-git is also consistent on my system:

```bash
nix-prefetch-git --fetch-submodules https://github.com/andersbakken/rtags.git refs/tags/v2.10
{                                 
  "url": "https://github.com/andersbakken/rtags.git",               
  "rev": "3b3ace901f53827daef81d4c13658ec4feb318b4",                
  "date": "2017-05-26T14:04:03-07:00",                              
  "sha256": "1swcz4p5v6zqzqrxdbxbcvy009k509s4ni8qqg1wyp537qcibwdb", 
  "fetchSubmodules": true         
}
```

**Comment by acowley** [comment]
I investigated a bit earlier today with some suggestions from IRC, and the most suspicious diff I could find between Linux and Darwin is a [file](https://github.com/Andersbakken/rct/blob/master/tests/testfile_%C3%84%C3%9F%C3%A9%D7%9E%D7%A9%E6%9C%80%E7%B5%82.txt) with UTF8 characters in its name and contents. When I dumped file listings to a file on each system and opened in emacs, ediff highlighted that file name as a difference. Possibly a red herring, but it's all I came up with.

**Comment by Mic92** [comment]
Probably HFS plus does unicode normalisation, which is not the case for other filesystems commonly found on Linux.

**Comment by Mic92** [comment]
The quick fix would be to just have to checksums at the moment, if this is really the root cause.

**Comment by LnL7** [comment]
Yep, it's the filesystem. I have a machine that doesn't use HFS+ for the store and I get the same hash as linux there.

**Comment by LnL7** [comment]
With https://github.com/NixOS/nixpkgs/pull/26358 and this I get the same hash everywhere.

```diff
-    sha256 = "0z32yncn3x1pm2l6r349kfwi6mi83vll820kka87agcla64pl1f2";                                
+    sha256 = "0rv5hz4cfc1adpxvp4j4227nfc0p0yrjdc6l9i32jj11p69a5401";                                
+                        
+    postFetch = ''      
+      rm $out/src/rct/tests/testfile_*.txt       
+    ''; 
```

**Comment by Mic92** [comment]
HFS+ will hopefully be deprecated soon.

**Pull request merged**
