### PR TITLE
electrum: 4.5.3 -> 4.5.4

### LINKED ISSUE #296216: electrum: unable to use hardware wallet
### Describe the bug
Cannot use hardware wallet with electrum from nixos-unstable channel

### Steps To Reproduce
1. Try to use hardware wallet with electrum (either via creating wallet or loading a wallet)
2. :x: on "Choose Hardware Device" screen, be presented with debug error

### Expected behavior
- A list of connected hardware wallets when at least one is connected

### Screenshots
image

### Additional context
Issue is not present in package from nixos-23.11 channel
hardware wallet used: Ledger Nano X

### Notify maintainers

@joachifm, @np, @prusnak

### Metadata
```console
wroclaw in ~ 
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.7, NixOS, 23.11 (Tapir), 23.11.5060.617579a78725`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - channels(wroclaw): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by chewblacka**
## Description of changes
- Added myself to package maintainers
- Added `safet` 0.1.4 to python packages (https://github.com/dArkjON/python-safet)
- Electrum - added missing hardware dependencies:
	`bitbox02`
	`cbor`
	`pyserial`
	`safet`
- Electrum - pinned `ledger-bitcoin` version to 0.2.1 (0.3.0 in the repos doesn't work)
- Electrum - updated version from 4.5.3 -> 4.5.4 (https://github.com/dArkjON/python-safet)

Closes https://github.com/NixOS/nixpkgs/issues/296216

### To test:
Run electrum. Create a new wallet. Standard wallet. Use a hardware device

Before update you get the following error message:

```
Debug message
  bitbox02: (error getting device infos)
    Missing libraries for bitbox02.
        ImportError()
    Make sure you install it with python3
  jade: (error getting device infos)
    Missing libraries for jade.
        ModuleNotFoundError("No module named 'cbor'")
    Make sure you install it with python3
  ledger: (error getting device infos)
    Library version for 'ledger' is incompatible.
    Installed: 0.3.0, Needed: 0.2.0 <= x < 0.3.0
    Make sure you install it with python3
  safe_t: (error getting device infos)
    Missing libraries for safe_t.
        ModuleNotFoundError("No module named 'safetlib'")
    Make sure you install it with python3
```
After update & fixes, all errors are resolved.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by prusnak — CHANGES_REQUESTED** [review]
Please remove SafeT - it is a dead project and their poor code breaks Trezor integration.

**Comment by chewblacka** [comment]
> Please remove SafeT - it is a dead project and their poor code breaks Trezor integration.

Done.

**Comment by prusnak** [comment]
@GrahamcOfBorg build electrum

**Review by prusnak — APPROVED** [review]

**Comment by felipelalli** [comment]
As long as SafeT is a dependency for Electrum to work with hard wallets, I think it makes sense to add it. When it's no longer a dependency, then we can remove it.

**Pull request merged**
