### PR TITLE
python: pymysql 0.6.6 -> 0.7.11

### PR DESCRIPTION
**Pull request by esoeylemez**

### CODE REVIEW

**Comment by FRidh** [comment]
We are moving Python expressions out of `pkgs/top-level/python-packages.nix` into `pkgs/development/python-modules/<module>/default.nix`. 

Please move the expression there, and call it from `pkgs/top-level/python-packages.nix` using `callPackage ../development/python-modules/<package> { };`.

**Comment by orivej** [comment]
@FRidh Why do we ask people to move packages? Shouldn't we move everything automatically?

**Comment by FRidh** [comment]
@orivej any suggestion on how to do this automatically?

**Comment by orivej** [comment]
> any suggestion on how to do this automatically?

I'll experiment with a few possible approaches this weekend (mainly text manipulation based vs parser based).

**Pull request closed without merging**
