### PR TITLE
azure-cli: 2.26.1 -> 2.28.0

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
Another bump

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
```
https://github.com/NixOS/nixpkgs/pull/137461

9 packages built:
azure-cli python38Packages.azure-mgmt-batchai python38Packages.azure-mgmt-iothubprovisioningservices python38Packages.azure-mgmt-sqlvirtualmachine python38Packages.azure-synapse-managedprivateendpoints python39Packages.azure-mgmt-batchai python39Packages.azure-mgmt-iothubprovisioningservices python39Packages.azure-mgmt-sqlvirtualmachine python39Packages.azure-synapse-managedprivateendpoints
```

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 137461` at 0d33362f run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built successfully:</summary>
  <ul>
    <li>azure-cli</li>
    <li>python38Packages.azure-mgmt-batchai</li>
    <li>python38Packages.azure-mgmt-iothubprovisioningservices</li>
    <li>python38Packages.azure-mgmt-sqlvirtualmachine</li>
    <li>python38Packages.azure-synapse-managedprivateendpoints</li>
    <li>python39Packages.azure-mgmt-batchai</li>
    <li>python39Packages.azure-mgmt-iothubprovisioningservices</li>
    <li>python39Packages.azure-mgmt-sqlvirtualmachine</li>
    <li>python39Packages.azure-synapse-managedprivateendpoints</li>
  </ul>
</details>
<details>
  <summary>9 suggestions:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `isPy3k`.
Near pkgs/development/python-modules/azure-mgmt-batchai/default.nix:9:3:
```
  |
9 | , isPy3k
  |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern 'cryptography>=3.2,<3.4' doesn't match anything in file 'setup.py'
Near pkgs/tools/admin/azure-cli/default.nix:265:0:
```
    |
265 |     description = "Next generation multi-platform command line experience for Azure";
    | ^
```
</li>
    <li>warning: unused-argument

Unused argument: `isPy3k`.
Near pkgs/development/python-modules/azure-mgmt-iothubprovisioningservices/default.nix:5:3:
```
  |
5 | , isPy3k
  |   ^
```
</li>
    <li>warning: unused-argument

Unused argument: `python`.
Near pkgs/development/python-modules/azure-mgmt-iothubprovisioningservices/default.nix:4:3:
```
  |
4 | , python
  |   ^
```
</li>
    <li>warning: unused-argument

Unused argument: `python`.
Near pkgs/development/python-modules/azure-mgmt-batchai/default.nix:8:3:
```
  |
8 | , python
  |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-include-tests.md">python-include-tests</a>

Consider adding a `checkPhase` for tests, or if not feasible, `pythonImportsCheck`.

Near pkgs/development/python-modules/azure-mgmt-batchai/default.nix:35:0:
```
   |
35 |     description = "This is the Microsoft Azure Batch AI Management Client Library";
   | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-python-tests.md">no-python-tests</a>

Test runner could not discover any test cases: ‘Ran 0 tests in 0.000s’
Near pkgs/development/python-modules/azure-synapse-managedprivateendpoints/default.nix:28:0:
```
   |
28 |     description = "Microsoft Azure Synapse Managed Private Endpoints Client Library for Python";
   | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern 'mock~=4.0' doesn't match anything in file 'setup.py'
Near pkgs/tools/admin/azure-cli/default.nix:265:0:
```
    |
265 |     description = "Next generation multi-platform command line experience for Azure";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-include-tests.md">python-include-tests</a>

Consider adding a `checkPhase` for tests, or if not feasible, `pythonImportsCheck`.

Near pkgs/development/python-modules/azure-mgmt-iothubprovisioningservices/default.nix:37:0:
```
   |
37 |     description = "This is the Microsoft Azure IoTHub Provisioning Services Client Library";
   | ^
```
</li>
  </ul>
</details>

**Comment by jonringer** [comment]
cc @SuperSandro2000 I fixed up the non-test related suggestions

**Comment by SuperSandro2000** [comment]
Thank you!

**Pull request merged**
