### PR TITLE
nixos/coolercontrol: Use user-preferred nvidia package

### LINKED ISSUE #315594: CoolerControl v1.2.2: daemon does not detect the nvidia proprietary drivers.
### Describe the bug
CoolerControl does not detect Nvidia GPU when enabled via options

### Steps To Reproduce
1. Nvidia GPU with proprietary drivers (version 555, but might not matter)
2. `programs.coolercontrol.enable = true;`
3. `programs.coolercontrol.nvidiaSupport = true;`
4. `journalctl -u coolercontrold` spits out error about missing `nvidia-smi` and `nvidia-settings`

### Expected behavior
CoolerControl to detect Nvidia GPU

### Screenshots
image

### Additional context
Logging output:

```console
May 22 21:27:04 cortex coolercontrold[143375]: Logging Level: INFO
May 22 21:27:04 cortex coolercontrold[143375]: Initializing...
May 22 21:27:04 cortex coolercontrold[143375]: Configuration file check successful
May 22 21:27:07 cortex coolercontrold[143375]: Communication established with Liqctld.
May 22 21:27:07 cortex coolercontrold[143375]: Initialized Liquidctl Devices: ["Corsair Lighting Node Pro"]
May 22 21:27:07 cortex coolercontrold[143375]: Initialized CPU Devices: ["Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz"]
May 22 21:27:07 cortex coolercontrold[143375]: Error communicating with nvidia-smi. If you have a Nvidia card with proprietary drivers, nvidia-smi and nvidia-settings are required.
```

---

If I manually stop the systemd process and start `sudo coolercontrold` it detects the requested binaries correctly, which makes me think that the coolercontrold binary just doesn't search the correct paths.

### Notify maintainers

@codifryed @OPNA2608

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32, NixOS, 24.11 (Vicuña), 24.11.20240526.e2dd4e1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(vilsol): `""`
 - channels(root): `"nixos-23.11, nixos-unstable, nixpkgs-unstable"`
 - nixpkgs: `/nix/store/62ca8xfz3n92p57sdds15r4s07kyls6i-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by OPNA2608**
## Description of changes

Closes #315594

CC @Vilsol, can you test this?

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Vilsol** [comment]
Looks like that fixes the main issue!
```console
May 29 16:40:03 cortex coolercontrold[449998]: Logging Level: INFO
May 29 16:40:03 cortex coolercontrold[449998]: Initializing...
May 29 16:40:03 cortex coolercontrold[449998]: Configuration file check successful
May 29 16:40:14 cortex coolercontrold[449998]: Communication established with Liqctld.
May 29 16:40:14 cortex coolercontrold[449998]: Initialized Liquidctl Devices: ["Corsair Lighting Node Pro"]
May 29 16:40:14 cortex coolercontrold[449998]: Initialized CPU Devices: ["Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz"]
May 29 16:40:15 cortex coolercontrold[449998]: Xauthority found in file path: /run/user/1000/gdm/Xauthority
May 29 16:40:15 cortex coolercontrold[449998]: Initialized GPU Devices: ["NVIDIA GeForce RTX 2080 Ti"]
May 29 16:40:15 cortex coolercontrold[449998]: Error reading temperature value from: "/sys/class/hwmon/hwmon5"/temp1_input - No data available (os error 61)
May 29 16:40:15 cortex coolercontrold[449998]: Initialized Hwmon Devices: ["nvme0", "nvme1", "acpitz"]
May 29 16:40:15 cortex coolercontrold[449998]: Initialized Custom Sensors: []
May 29 16:40:15 cortex coolercontrold[449998]: Applying all saved device settings
May 29 16:40:15 cortex coolercontrold[449998]: API bound to IPv4 and IPv6 addresses: 127.0.0.1:11987, [::1]:11987
May 29 16:40:15 cortex coolercontrold[449998]: Daemon successfully initialized
```

However that does seem to create other issues, as after that, this gets spammed in the logs. This also happens if I manually run the executable from console, so this might be an issue with the package itself, not the daemon.
```console
May 29 16:40:16 cortex coolercontrold[449998]: Error applying scheduled speed setting: Error output received when trying to set nvidia fan speed settings. Some errors don't affect setting the fan speed. YMMV: ERROR: libGL setup error : libGL.so.1: ca>



                                               ERROR: libEGL setup error : libEGL.so.1: cannot open shared object file: No such file or directory



                                               ERROR: libEGL setup error : libEGL.so.1: cannot open shared object file: No such file or directory
May 29 16:40:18 cortex coolercontrold[449998]: Error applying scheduled speed setting: Error output received when trying to set nvidia fan speed settings. Some errors don't affect setting the fan speed. YMMV: ERROR: libGL setup error : libGL.so.1: ca>



                                               ERROR: libEGL setup error : libEGL.so.1: cannot open shared object file: No such file or directory



                                               ERROR: libEGL setup error : libEGL.so.1: cannot open shared object file: No such file or directory
May 29 16:40:19 cortex coolercontrold[449998]: Error applying scheduled speed setting: Error output received when trying to set nvidia fan speed settings. Some errors don't affect setting the fan speed. YMMV: ERROR: libGL setup error : libGL.so.1: ca>



                                               ERROR: libEGL setup error : libEGL.so.1: cannot open shared object file: No such file or directory



                                               ERROR: libEGL setup error : libEGL.so.1: cannot open shared object file: No such file or directory
May 29 16:40:20 cortex coolercontrold[449998]: Error applying scheduled speed setting: Error output received when trying to set nvidia fan speed settings. Some errors don't affect setting the fan speed. YMMV: ERROR: libGL setup error : libGL.so.1: ca>



                                               ERROR: libEGL setup error : libEGL.so.1: cannot open shared object file: No such file or directory



                                               ERROR: libEGL setup error : libEGL.so.1: cannot open shared object file: No such file or directory
May 29 16:40:21 cortex coolercontrold[449998]: Error applying scheduled speed setting: Error output received when trying to set nvidia fan speed settings. Some errors don't affect setting the fan speed. YMMV: ERROR: libGL setup error : libGL.so.1: ca>



                                               ERROR: libEGL setup error : libEGL.so.1: cannot open shared object file: No such file or directory



                                               ERROR: libEGL setup error : libEGL.so.1: cannot open shared object file: No such file or directory
May 29 16:40:22 cortex coolercontrold[449998]: Error applying scheduled speed setting: Error output received when trying to set nvidia fan speed settings. Some errors don't affect setting the fan speed. YMMV: ERROR: libGL setup error : libGL.so.1: ca>



                                               ERROR: libEGL setup error : libEGL.so.1: cannot open shared object file: No such file or directory



                                               ERROR: libEGL setup error : libEGL.so.1: cannot open shared object file: No such file or directory
May 29 16:40:23 cortex coolercontrold[449998]: Error applying scheduled speed setting: Error output received when trying to set nvidia fan speed settings. Some errors don't affect setting the fan speed. YMMV: ERROR: libGL setup error : libGL.so.1: ca>
```

I would really like to know if there was some other easier way of testing than doing this? Maybe with overlays, but I'm not yet that familiar with them:
```nix
nixpkgs-unstable.url = "github:OPNA2608/nixpkgs/fix/coolercontrold-nvidia-package";
```

**Comment by OPNA2608** [comment]
Does `nvidia-settings` work for you, and are you using some more exotic WM/DE setup? After some quick googling, since this involves running `nvidia-settings`, https://discourse.nixos.org/t/issue-getting-nvidia-settings-to-load-on-startup/44032 might be what you're issue is?

**Comment by Vilsol** [comment]
Indeed I do get the same errors when opening `nvidia-settings`, but the issue you linked doesn't seem to be relevant to that.

However, opening `nvidia-settings` logs it about 10 times and then stops. `coolercontrold` logs it every time it tries to change the fan speed. But I guess that is out of scope for this PR, so...

LGTM

**Review by Vilsol — APPROVED** [review]

**Comment by OPNA2608** [comment]
> the issue you linked doesn't seem to be relevant to that

Snippets I was looking at:

> […] `nvidia-settings` needs to run under an Xorg (or wayland, with severely limited functionality) context to do anything […]

> […] depending on the implementation of WM/DE’s systemd integration, you may also need to ensure that certain environment variables (like DISPLAY for xorg and WAYLAND_DISPLAY for wayland) are set when the service runs. Systemd allows propagating and ensuring env vars through `systemctl set-environment` […]

Not sure if anything there applies to you / could help.

> `coolercontrold` logs it every time it tries to change the fan speed.

[Every fan speed change involves an invocation of `nvidia-settings` it seems](https://gitlab.com/coolercontrol/coolercontrol/-/blob/029cbe9a8a8bb26c0b8d4a9404a871e60a800e67/coolercontrold/src/repositories/gpu_repo.rs#L371-387), to that sounds correct.

---

> I would really like to know if there was some other easier way of testing than doing this? Maybe with overlays, but I'm not yet that familiar with them:
>
> ```nix
> nixpkgs-unstable.url = "github:OPNA2608/nixpkgs/fix/coolercontrold-nvidia-package";
> ```

Beats me btw. For my (non-flake) setup, I `callPackage` all of the packages from the files of the `<unstable>` channel, add them in an overlay and import the module into my config. I don't like to look at it though, so I'm not sure if that's better… :cold_sweat:

**Pull request merged**
