### PR TITLE
python3Packages.google*: follow up to #133298

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by roberth** [comment]
> # Google fallout

What happened?

**Comment by SuperSandro2000** [comment]
> > # Google fallout
> 
> What happened?

Updated the PR name. Just cleaning up some things that broke in #133298.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 134309` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>8 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>python38Packages.pathy: log was empty</li>
<li>python38Packages.spacy: log was empty</li>
<li>python38Packages.spacy-transformers: log was empty</li>
<li>python38Packages.textacy: log was empty</li>
<li>python39Packages.pathy: log was empty</li>
<li>python39Packages.spacy: log was empty</li>
<li>python39Packages.spacy-transformers: log was empty</li>
<li>python39Packages.textacy: log was empty</li>
  </ul>
</details>
<details>
<summary>
45 packages built:
</summary>
<ul>
<li>dvc-with-remotes</li>
<li>home-assistant</li>
<li>python38Packages.gensim</li>
<li>python38Packages.google-cloud-appengine-logging</li>
<li>python38Packages.google-cloud-asset</li>
<li>python38Packages.google-cloud-automl</li>
<li>python38Packages.google-cloud-bigquery</li>
<li>python38Packages.google-cloud-bigquery-logging</li>
<li>python38Packages.google-cloud-bigtable</li>
<li>python38Packages.google-cloud-container</li>
<li>python38Packages.google-cloud-datacatalog</li>
<li>python38Packages.google-cloud-iam-logging</li>
<li>python38Packages.google-cloud-iot</li>
<li>python38Packages.google-cloud-kms</li>
<li>python38Packages.google-cloud-pubsub</li>
<li>python38Packages.google-cloud-resource-manager</li>
<li>python38Packages.google-cloud-secret-manager</li>
<li>python38Packages.google-cloud-securitycenter</li>
<li>python38Packages.google-cloud-spanner</li>
<li>python38Packages.google-cloud-storage</li>
<li>python38Packages.google-cloud-tasks</li>
<li>python38Packages.grpc-google-iam-v1</li>
<li>python38Packages.smart-open</li>
<li>python39Packages.gensim</li>
<li>python39Packages.google-cloud-appengine-logging</li>
<li>python39Packages.google-cloud-asset</li>
<li>python39Packages.google-cloud-automl</li>
<li>python39Packages.google-cloud-bigquery</li>
<li>python39Packages.google-cloud-bigquery-logging</li>
<li>python39Packages.google-cloud-bigtable</li>
<li>python39Packages.google-cloud-container</li>
<li>python39Packages.google-cloud-datacatalog</li>
<li>python39Packages.google-cloud-iam-logging</li>
<li>python39Packages.google-cloud-iot</li>
<li>python39Packages.google-cloud-kms</li>
<li>python39Packages.google-cloud-pubsub</li>
<li>python39Packages.google-cloud-resource-manager</li>
<li>python39Packages.google-cloud-secret-manager</li>
<li>python39Packages.google-cloud-securitycenter</li>
<li>python39Packages.google-cloud-spanner</li>
<li>python39Packages.google-cloud-storage</li>
<li>python39Packages.google-cloud-tasks</li>
<li>python39Packages.grpc-google-iam-v1</li>
<li>python39Packages.smart-open</li>
<li>snakemake</li>
</ul>
</details>

**Comment by Mic92** [comment]
I marked typer as broken here: https://github.com/NixOS/nixpkgs/pull/134330

**Pull request merged**
