### PR TITLE
Reduce hydra errors

### PR DESCRIPTION
**Pull request by shlevy**
With this patchset, hydra can set the `NIXPKGS_NO_THROW_ON_BROKEN_OR_UNFREE` env var to `1` to remove the evaluation errors resulting from nixpkgs unfree/broken/disabled logic.

cc @edolstra for stdenv stuff, @domenkozar for python stuff.

### CODE REVIEW

**Comment by edolstra** [comment]
You can't rely on environment variables anymore. In restricted mode (which Hydra now uses) `getEnv` always returns an empty string.

Also, doesn't this cause those packages to be evaluated and added as Hydra builds, even though they're marked as broken/unsupported? Maybe it's better to catch these failures in release-lib.nix and return `null` for the corresponding job attribute.

**Comment by edolstra** [comment]
Oh, I see it returns `false` from `licenseAllowed` so it triggers an assertion failure. But don't those show up in the jobset output?

**Comment by domenkozar** [comment]
Also see #6561

**Comment by domenkozar** [comment]
Another problem are packages that depend on disabled packaged.

**Comment by shlevy** [comment]
@edolstra https://github.com/NixOS/nix/blob/master/src/libexpr/get-drvs.cc#L209-L212

Without getEnv, is there any way at all to communicate "I'm a hydra build?" Maybe some argument to all-packages.nix that we set in the jobset?

**Comment by shlevy** [comment]
@domenkozar Not a problem with assertions, they will also trigger the assertion and be ignored.

**Comment by shlevy** [comment]
Ah, it seems hydra doesn't use that getDrvs code path. Why not?

**Comment by edolstra** [comment]
Just set config.noThrowOnDisabled in `release-lib.nix`.

**Comment by edolstra** [comment]
Hydra doesn't use it because it assumes that you want to know if a job fails to evaluate.

**Comment by shlevy** [comment]
Is that assumption useful anymore? without something that automatically propagates like assert or throw, we simply can't get the right behavior here.

**Comment by edolstra** [comment]
Sure it is, it would be bad if you define a job and Hydra quietly ignores it because it has an evaluation error.

**Comment by shlevy** [comment]
But an assert is different from a general evaluation error, and that code path only ignores asserts. Can't we treat assertions in packages as preconditions and let hydra assume that a package whose precondition isn't met is just not built?

**Comment by edolstra** [comment]
I don't see how Hydra can assume that an assertion failure is "intended". For instance, if I have a Hydra job with
```
buildInputs = [ libfoo ];
```
and now somebody else changes libfoo so that it causes an assertion failure, I would like to know about it.

I think this can only be addressed in `release-lib.nix`, where we can catch evaluation errors specifically for jobs in the Nixpkgs jobset.

**Comment by shlevy** [comment]
Except tryEval doesn't give us any info about the exception being thrown. And even if we had a way to do that, it would still propagate in the `libfoo` case above, right?

**Comment by edolstra** [comment]
What do you mean with propagate? I wouldn't catch the exception in that case, so it would show up in Hydra.

**Comment by shlevy** [comment]
libbar depends on libfoo. In release-lib.nix, I have logic to ignore all broken builds. libfoo is marked broken. How does hydra distinguish between the situation when evaluating the libfoo job and when evaluating the libbar job?

**Comment by edolstra** [comment]
It can't distinguish between those cases.

**Comment by shlevy** [comment]
So, that's what I mean by propagate. Can you give a realistic example where exception catching in in release-lib.nix won't have this problem? Where one job is allowed to have exceptions and is ignored if so, but others that depend on it aren't and are reported?

**Comment by edolstra** [comment]
In my example I wouldn't be using `release-lib.nix`, so I would still get an exception.

**Comment by shlevy** [comment]
OK now I'm confused :grin: Do you think it's a problem at all that hydra is reporting all these broken builds in the eval errors? As a practical consequence, the eval error tab is completely useless IMO.

**Comment by edolstra** [comment]
Right, which would be fixed by catching errors in `release-lib.nix`. Of course, it might also cause some legitimate problems to be hidden.

**Comment by shlevy** [comment]
So as far as I can tell, that means either a) providing a means to add more structure to exceptions (I think it would be easiest to add a string coercion when a throw propagates up to the top level if it's not already there, and giving a way to access the exception in tryEval), or b) treating some class of errors (assertion failures, throws, or aborts) as ignorable. This PR + setting ignoreAssertionErrors in hydra would be b), let me know if you prefer a and I can see about updating nix's exception machinery.

**Comment by edolstra** [comment]
I don't see how this PR accomplished b). I mean, it turns broken/unfree into an assertion failure, meaning they cannot be distinguished from "real" assertion failures.

a) could be done by adding the exception message to the result attribute set of `tryEval`.

**Comment by shlevy** [comment]
I think it'd be much cleaner to have structured data instead of doing string matching, no? `if (tryEval bar).exception.packageBroken or false then null else bar` or some such

**Comment by shlevy** [comment]
Anyway, doing this would have meant doing b) and setting the semantics that assertions are ignorable across the board, which of course may not be the best thing but of the three options without modifying nix seems the least invasive.

**Comment by shlevy** [comment]
s/invasive/obviously wrong.

**Comment by nbp** [comment]
@shlevy @domenkozar Is this issue still a valid concern?

**Comment by domenkozar** [comment]
Well, sadly, yes.

**Comment by rasendubi** [comment]
(triage) any update?

**Comment by shlevy** [comment]
NixOS/nix#1000 is relevant

**Pull request closed without merging**
