### PR TITLE
vlang: weekly.2023.19 -> weekly.2023.42

### LINKED ISSUE #261460: Update request: vlang weekly.2023.19 → weekly.2023.41
- Package name: vlang
- Latest released version: [weekly.2023.41](https://github.com/vlang/v/releases/tag/weekly.2023.41)

- Current version on the unstable channel: vlang weekly.2023.19
- Current version on the stable/release channel: vlang weekly.2023.19

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@Madouura

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by chewblacka**
## Description of changes
https://github.com/vlang/v/blob/master/CHANGELOG.md
Closes #261460

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Delta456** [comment]
I have made the same changes locally but when I try to build it with `nix-build -A vlang`. I got this:

image

**Comment by chewblacka** [comment]
> I have made the same changes locally but when I try to build it with `nix-build -A vlang`. I got this:

Are you on Linux or Darwin? Also what is the output of:

`nix-shell -p nix-info --run "nix-info -m"`

**Comment by Delta456** [comment]
> > I have made the same changes locally but when I try to build it with `nix-build -A vlang`. I got this:
> 
> Are you on Linux or Darwin? Also what is the output of:
> 
> `nix-shell -p nix-info --run "nix-info -m"`

I am on Linux. This is the output of the command.

image

**Comment by chewblacka** [comment]
> > > I have made the same changes locally but when I try to build it with `nix-build -A vlang`. I got this:
> > 

I don't know what changes you made but it's building `weekly-2023.28` which is not the version I've put in my build. Suggest you try using this build and report any errors if you still get them.

**Comment by Delta456** [comment]
> > > > I have made the same changes locally but when I try to build it with `nix-build -A vlang`. I got this:
> 
> I don't know what changes you made but it's building `weekly-2023.28` which is not the version I've put in my build. Suggest you try using this build and report any errors if you still get them.

Your changes are working. I wonder what was wrong with `weekly-2023.28`.

**Pull request merged**
