### PR TITLE
coqPackages.topology: init

### PR DESCRIPTION
**Pull request by siraben**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 122365` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>coqPackages.topology</li>
  </ul>
</details>

**Comment by cole-h** [comment]
@ofborg eval

**Comment by siraben** [comment]
@GrahamcOfBorg build coqPackages_8_13.topology coqPackages_8_12.topology coqPackages_8_1q.topology coqPackages_8_10.topology coqPackages_8_9.topology coqPackages_8_8.topology coqPackages_8_7.topology coqPackages_8_6.topology coqPackages_8_5.topology

**Comment by siraben** [comment]
@GrahamcOfBorg build coqPackages_8_11.topology

**Comment by siraben** [comment]
@CohenCyril @vbgl could you help me out here? I'm not sure what to do about the following error:

```ShellSession
$ nix build .#coqPackages_8_11.topology
error: builder for '/nix/store/dm6j2119fn5f4dppy1b6wqiwa3akcdz4-coq8.11-topology-8.12.0.drv' failed with exit code 2;
       last 10 log lines:
       > *** Warning: in file WeakTopology.v, library ZornsLemma.FiniteIntersections is required and has not been found in the loadpath!
       > COQC TopologicalSpaces.v
       > File "./TopologicalSpaces.v", line 2, characters 31-48:
       > Error: Cannot find a physical path bound to logical path matching suffix
       > <> and prefix ZornsLemma.
       >
       > make[2]: *** [Makefile.coq:678: TopologicalSpaces.vo] Error 1
       > make[1]: *** [Makefile.coq:327: all] Error 2
       > make[1]: Leaving directory '/private/tmp/nix-build-coq8.11-topology-8.12.0.drv-0/source'
       > make: *** [Makefile:2: all] Error 2
       For full logs, run 'nix log /nix/store/dm6j2119fn5f4dppy1b6wqiwa3akcdz4-coq8.11-topology-8.12.0.drv
```

**Comment by CohenCyril** [comment]
@siraben  Looks like you are missing a dependency in the library `coq-community/zorns-lemma` cf the library's [opam file](https://github.com/coq-community/topology/blob/v8.12.0/coq-topology.opam) or [meta.yml file](https://github.com/coq-community/topology/blob/v8.12.0/meta.yml#L43-L46)

**Comment by siraben** [comment]
@CohenCyril Right, though it appears that the dependency is in the same repository, so should I make a new coqPackage called `zorns-lemma` and use this as the source, or is there something similar done elsewhere in `coqPackages`?

**Comment by CohenCyril** [comment]
> @CohenCyril Right, though it appears that the dependency is in the same repository, so should I make a new coqPackage called `zorns-lemma` and use this as the source, or is there something similar done elsewhere in `coqPackages`?

As of `coq/topology` version `8.12`, zorns lemma is not in the same repo.

**Comment by siraben** [comment]
@GrahamcOfBorg build coqPackages_8_13.topology coqPackages_8_12.topology coqPackages_8_11.topology coqPackages_8_10.topology coqPackages_8_9.topology coqPackages_8_8.topology coqPackages_8_7.topology coqPackages_8_6.topology coqPackages_8_5.topology

**Comment by siraben** [comment]
@GrahamcOfBorg build coqPackages_8_13.topology coqPackages_8_12.topology coqPackages_8_11.topology coqPackages_8_10.topology coqPackages_8_9.topology coqPackages_8_8.topology coqPackages_8_7.topology coqPackages_8_6.topology coqPackages_8_5.topology

**Comment by siraben** [comment]
Removing mathcomp dependency.

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 122365` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>coqPackages.topology</li>
    <li>coqPackages.zorns-lemma</li>
  </ul>
</details>

**Comment by siraben** [comment]
@vbgl @CohenCyril please take another look

**Comment by vbgl** [comment]
The commits are in the wrong order: please rebase and put the addition of zorns-lemma before the addition of topology. Thanks.

**Comment by siraben** [comment]
@vbgl fixed

**Comment by vbgl** [comment]
Thanks. The propagate-build-inputs in topology uses `defaultVersion` which may be wrong when overriding. This is not a big deal and is a general limitation of mkCoqDerivation (we need to know the actual version!). Improving this is left as future work.

**Comment by CohenCyril** [comment]
> Thanks. The propagate-build-inputs in topology uses `defaultVersion` which may be wrong when overriding. This is not a big deal and is a general limitation of mkCoqDerivation (we need to know the actual version!). Improving this is left as future work.

Indeed, this is solved in https://github.com/NixOS/nixpkgs/pull/116690, but I'm waiting for more feedback

**Pull request merged**
