### PR TITLE
vuescan: 9.7.35 -> 9.7.37

### PR DESCRIPTION
**Pull request by evax**
###### Motivation for this change

Update to latest version.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by evax** [comment]
The minor versions are released in place, using the same file name, so this will break on every new minor release. Is there a standard way to deal with this in nixpkgs? Could we cache the binaries somewhere?

**Comment by evax** [comment]
9.7.37 is already out and this wasn't merged. I'll update this PR shortly. I'd appreciate some feedback on the caching point I'm making above.

**Comment by evax** [comment]
@garbas, sorry to bother you, you merged the initial package in, the package in master is broken and uninstallable until this is merged. I would also greatly appreciate any feedback you might have on the caching point I'm bringing up above.

**Comment by garbas** [comment]
@evax The sha's are out of sync again. The url provided is for 9.7.x and they change those files. I would recommend contacting the upstream if they can provide permanent links for their releases.

**Comment by evax** [comment]
Hi @garbas, thanks for your feedback. I contacted the author and he's stating he explicitly forbids packaging of his software. I'm closing this pull request and will open a new one to remove the package.

**Pull request closed without merging**
