### PR TITLE
google-fonts: 2019-07-14 -> unstable-2021-01-19

### LINKED ISSUE #109245: Update google-fonts 2019-07-14 -> 2021-01-??
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: google-fonts

current version: 2019-07-14
desired version: 2021-01-?? (see https://github.com/google/fonts)

###### Notify maintainers

maintainers: @spacekookie (the most recent committer here)

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by tu-maurice**
###### Motivation for this change

Closes #109245

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110027` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>inconsolata</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110027` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>ricty: log was empty</li>
  </ul>
</details>
<details>
<summary>
1 package built:
</summary>
<ul>
<li>inconsolata</li>
</ul>
</details>

```
builder for '/nix/store/1fniq0b82853s80210c5pi8d88khbaka-ricty_generator-4.1.1.sh.drv' failed with exit code 1; last 7 log lines:                                                                                                                                                                                                                                                         trying http://www.yusa.lab.uec.ac.jp/~yusa/ricty/ricty_generator-4.1.1.sh
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                   Dload  Upload   Total   Spent    Left  Speed
									       0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
										     curl: (22) The requested URL returned error: 404 Not Found
											   error: cannot download ricty_generator-4.1.1.sh from any mirror
											   cannot build derivation '/nix/store/q5xr9i09bmaxs4445v1c74vrim8bi8a4-ricty-4.1.1.drv': 1 dependencies couldn't be built
											   cannot build derivation '/nix/store/5x20nra7hlyidbz070i9wbj1vaf7lmy1-env.drv': 1 dependencies couldn't be built
```

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by tu-maurice** [comment]
@SuperSandro2000 Just want to ask if there is any reason left not to merge this?

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110027` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>inconsolata</li>
</ul>
</details>

**Comment by petabyteboy** [comment]
This breaks the `inconsolate` package:

```
[pbb@regolith:~/proj/nixpkgs]$ l old/share/fonts/truetype/inconsolata/
Permissions Size User Date Modified Name
.r--r--r--  108k root  1 Jan  1970  Inconsolata-Bold.ttf
.r--r--r--   95k root  1 Jan  1970  Inconsolata-Regular.ttf

[pbb@regolith:~/proj/nixpkgs]$ l new/share/fonts/truetype/inconsolata/
Permissions Size User Date Modified Name
.r--r--r--  347k root  1 Jan  1970  Inconsolata[wdth,wght].ttf

[pbb@regolith:~/proj/nixpkgs]$
```

**Pull request merged**
