### PR TITLE
treewide: fix build errors on darwin due to incorrect SDK

### PR DESCRIPTION
**Pull request by eliandoran**
## Description of changes

Fixes the error caused by using an older SDK version:

```
error: linking with `/nix/store/f3a8vfppqr4p31cxmngp541rhf5a86ds-clang-wrapper-16.0.6/bin/cc` failed: exit status: 1
  |
  = ... = note: Undefined symbols for architecture x86_64:
            "_kCFURLVolumeAvailableCapacityForImportantUsageKey", referenced from:
                _$LT$sysinfo..apple..disk..Disk$u20$as$u20$sysinfo..traits..DiskExt$GT$::refresh::hb774e156a47bb8ab in libsysinfo-775a0e38904b7704.rlib(sysinfo-775a0e38904b7704.sysinfo.312ef2a27622aac8-cgu.12.rcgu.o)
                sysinfo::apple::disk::get_disks::hcbdbab54ad71b5cd in libsysinfo-775a0e38904b7704.rlib(sysinfo-775a0e38904b7704.sysinfo.312ef2a27622aac8-cgu.12.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

According to the documentation `doc/stdenv/platform-notes.chapter.md`:

```md
- x86_64-darwin uses the 10.12 SDK by default, but some software is not compatible with that version of the SDK. In that case,
  the 11.0 SDK used by aarch64-darwin is available for use on x86_64-darwin. To use it, reference `apple_sdk_11_0` instead of
  `apple_sdk` in your derivation and use `pkgs.darwin.apple_sdk_11_0.callPackage` instead of `pkgs.callPackage`. On Linux, this will
  have the same effect as `pkgs.callPackage`, so you can use `pkgs.darwin.apple_sdk_11_0.callPackage` regardless of platform.
```

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ofalvai** [comment]
Result of `nixpkgs-review pr 312711` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by eliandoran** [comment]
Result of `nixpkgs-review pr 312711` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>git-credential-keepassxc</li>
    <li>jikken</li>
    <li>nym</li>
    <li>veilid</li>
    <li>veilid.dev</li>
    <li>veilid.lib</li>
  </ul>
</details>

**Comment by eliandoran** [comment]
Result of `nixpkgs-review pr 312711` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>git-credential-keepassxc</li>
    <li>jikken</li>
    <li>nym</li>
    <li>veilid</li>
    <li>veilid.dev</li>
    <li>veilid.lib</li>
  </ul>
</details>

**Comment by eliandoran** [comment]
Apparently this approach is not good because it breaks linux_x86_64

**Comment by eliandoran** [comment]
Result of `nixpkgs-review pr 312711` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by eliandoran** [comment]
Result of `nixpkgs-review pr 312711` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>git-credential-keepassxc</li>
    <li>jikken</li>
    <li>nym</li>
    <li>veilid</li>
    <li>veilid.dev</li>
    <li>veilid.lib</li>
  </ul>
</details>

**Review by pbsds — APPROVED** [review]
Not sure why you request a review from me as I don't have a darwin machine to test on.

Diff LGTM, and going by your nixpkgs-review:

* fixes https://hydra.nixos.org/build/259373986
* fixes https://hydra.nixos.org/build/259307754
* fixes https://hydra.nixos.org/build/259274154
* fixes https://hydra.nixos.org/build/259444117

**Pull request merged**
