### PR TITLE
stm32cubemx: 6.11.1 -> 6.12.1

### PR DESCRIPTION
**Pull request by jpteb**
Updating stm32cubemax to the newest version of 6.12.1.
Changelog: [Official PDF Download](https://www.st.com/resource/en/release_note/rn0094-stm32cubemx-release-6111-stmicroelectronics.pdf)

Oh and I encountered weird behavior while updating this package. After changing the version it did not download the new file, but gave me the old version of 6.11.1 under the name 6.12.1. Only after gc'ing the store (I wasn't able to find the correct locations in the store, but this might be a skill issue) it rebuild correctly with the new download. I'm not sure if this was a me problem, or if this is a general problem.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by angaz** [comment]
Tested everything seems to work and the version of JRE is within spec.

Can you please test the New Project workflow? I can't test that because I get a blank screen for some reason. It seems to be an upstream bug. If it works for you, then I'm happy to approve.

**Comment by angaz** [comment]
Tested everything seems to work and the version of JRE is within spec.

@jpteb can you please test the New Project workflow? I can't test that because I get a blank screen for some reason. It seems to be an upstream bug. If it works for you, then I'm happy to approve.

**Comment by jpteb** [comment]
> @jpteb can you please test the New Project workflow? I can't test that because I get a blank screen for some reason. It seems to be an upstream bug. If it works for you, then I'm happy to approve.

The New Project workflow worked for me without problems. I will also resolve the conflict and test it again.

**Comment by jpteb** [comment]
@angaz Still works fine after the rebase 👍🏼

**Review by angaz — APPROVED** [review]

**Comment by angaz** [comment]
Cool. Thanks!

**Review by angaz — APPROVED** [review]

**Pull request merged**
