### PR TITLE
nodePackages.remod-cli: init at 1.0.1

### PR DESCRIPTION
**Pull request by samuela**
###### Motivation for this change
Adds the remod-cli tool to nixpkgs (https://github.com/samuela/remod). remod-cli is a user-friendly CLI for modifying and understanding file and directory permissions.

The changes in this PR are from following the instructions at `doc/languages-frameworks/node.section.md`.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 119589` at c638a195 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package skipped due to time constraints:</summary>
  <ul>
    <li>lumo</li>
  </ul>
</details>
<details>
  <summary>3 packages built successfully:</summary>
  <ul>
    <li>parity-ui</li>
    <li>teleprompter</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
@samuela Could you please repackage using a lockfile? See https://github.com/NixOS/nixpkgs/issues/229475.

**Comment by samuela** [comment]
remod uses yarn, so afaiu it is not a candidate for `buildNpmPackage` based on my reading of https://github.com/NixOS/nixpkgs/issues/229475

**Comment by dotlambda** [comment]
> remod uses yarn, so afaiu it is not a candidate for `buildNpmPackage` based on my reading of #229475

True but you can use `fetchYarnDeps`.

**Pull request merged**
