### PR TITLE
python3Packages.scikit-tda: init at 0.0.4

### PR DESCRIPTION
**Pull request by costrouc**
###### Motivation for this change

Went to scipy and saw an awesome package for Topological Data Analysis and wanted to add it to nixpkgs. Thanks @sauln for the great talk!

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by costrouc** [comment]
Result of `nix-review pr 64689` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>11 package were build:</summary>

  - python27Packages.kmapper
  - python27Packages.persim
  - python27Packages.ripser
  - python27Packages.tadasets
  - python27Packages.umap-learn
  - python37Packages.kmapper
  - python37Packages.persim
  - python37Packages.ripser
  - python37Packages.scikit-tda
  - python37Packages.tadasets
  - python37Packages.umap-learn
</details>

**Comment by sauln** [comment]
❤️❤️This is great! Thank you @costrouc!

**Comment by risicle** [comment]
Interesting - `umap-learn` (both py27 and py37) on macos 10.13 gives me

```
running install tests
....................................................F.......................
======================================================================
FAIL: umap.tests.test_umap.test_umap_transform_on_iris
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/7zlrb2lkq5rv24x4a60vjpli2b9hl712-python3.7-nose-1.3.7/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/private/tmp/nix-build-python3.7-umap-learn-0.3.9.drv-0/source/umap/tests/test_umap.py", line 767, in test_umap_transform_on_iris
    trust),
AssertionError: 0.889159891598916 not greater than or equal to 0.89 : Insufficiently trustworthy transform foriris dataset: 0.889159891598916
```

Which... I'm not sure what to do about 🤷‍♂

**Comment by risicle** [comment]
`persim` requires exactly the same fix as `trackpy` in https://github.com/NixOS/nixpkgs/pull/64692#issuecomment-511147767 for the tests to pass on macos 10.13.

**Comment by risicle** [comment]
Same for `ripser`!

**Comment by risicle** [comment]
If I disable the problematic test in `umap-learn`, and make the mentioned other fixes, everything does indeed build fine on macos 10.13.

**Comment by costrouc** [comment]
Thanks @risicle I appreciate the testing on darwin. I will make the changes tomorrow.

**Comment by costrouc** [comment]
Result of `nix-review pr 64689` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>11 package were build:</summary>

  - python27Packages.kmapper
  - python27Packages.persim
  - python27Packages.ripser
  - python27Packages.tadasets
  - python27Packages.umap-learn
  - python37Packages.kmapper
  - python37Packages.persim
  - python37Packages.ripser
  - python37Packages.scikit-tda
  - python37Packages.tadasets
  - python37Packages.umap-learn
</details>

**Comment by costrouc** [comment]
@GrahamcOfBorg build python3Packages.scikit-tda

**Pull request merged**
