### PR TITLE
whitebophir: 1.9.1 -> 1.14.6

### PR DESCRIPTION
**Pull request by cyclic-pentane**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by iblech** [comment]
Awesome, thank you for your work! Unfortunately most likely I will only be able to review this tomorrow, I'm sorry for the delay.

**Comment by alyaeanyx** [comment]
I've also checked that the service provided by `services.whitebophir.enable = true` does indeed work with the new package

**Review by iblech — APPROVED** [review]
Thank you again for your valuable work in keeping this build in sync with upstream! I just reviewed this (package + service), I would merge this if I had the permissions.

**Review by Artturin — APPROVED** [review]
tested by pr maker and package maintainer. merging

**Pull request merged**
