### PR TITLE
fcitx5*: update fcitx5 and its addons

### PR DESCRIPTION
**Pull request by Vonfry**
###### Motivation for this change
[fcitx/fcitx5-rime#31](https://github.com/fcitx/fcitx5-rime/issues/31)

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 125374` at 24717ed9 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>16 packages built successfully:</summary>
  <ul>
    <li>fcitx5</li>
    <li>fcitx5-chinese-addons</li>
    <li>fcitx5-configtool</li>
    <li>fcitx5-gtk</li>
    <li>fcitx5-lua</li>
    <li>fcitx5-m17n</li>
    <li>fcitx5-mozc</li>
    <li>fcitx5-rime</li>
    <li>fcitx5-table-extra</li>
    <li>fcitx5-table-other</li>
    <li>fcitx5-with-addons</li>
    <li>libime</li>
    <li>libsForQt5.fcitx5-qt (libsForQt515.fcitx5-qt ,plasma5Packages.fcitx5-qt)</li>
    <li>libsForQt512.fcitx5-qt</li>
    <li>libsForQt514.fcitx5-qt</li>
    <li>nixos-install-tools</li>
  </ul>
</details>

**Comment by Artturin** [comment]
Result of `nixpkgs-review pr 125374` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>libsForQt512.fcitx5-qt</li>
  </ul>
</details>
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>fcitx5</li>
    <li>fcitx5-chinese-addons</li>
    <li>fcitx5-configtool</li>
    <li>fcitx5-gtk</li>
    <li>fcitx5-lua</li>
    <li>fcitx5-m17n</li>
    <li>fcitx5-mozc</li>
    <li>fcitx5-rime</li>
    <li>fcitx5-table-extra</li>
    <li>fcitx5-table-other</li>
    <li>fcitx5-with-addons</li>
    <li>libime</li>
    <li>libsForQt5.fcitx5-qt (libsForQt515.fcitx5-qt ,plasma5Packages.fcitx5-qt)</li>
    <li>libsForQt514.fcitx5-qt</li>
  </ul>
</details>

**Comment by Artturin** [comment]
Result of `nixpkgs-review pr 125374` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>libsForQt512.fcitx5-qt</li>
  </ul>
</details>
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>fcitx5</li>
    <li>fcitx5-chinese-addons</li>
    <li>fcitx5-configtool</li>
    <li>fcitx5-gtk</li>
    <li>fcitx5-lua</li>
    <li>fcitx5-m17n</li>
    <li>fcitx5-mozc</li>
    <li>fcitx5-rime</li>
    <li>fcitx5-table-extra</li>
    <li>fcitx5-table-other</li>
    <li>fcitx5-with-addons</li>
    <li>libime</li>
    <li>libsForQt5.fcitx5-qt (libsForQt515.fcitx5-qt ,plasma5Packages.fcitx5-qt)</li>
    <li>libsForQt514.fcitx5-qt</li>
  </ul>
</details>

**Comment by Vonfry** [comment]
Update: take suggestion from @rmcgibbo

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Pull request merged**
