### PR TITLE
fcft: 2.2.6 → 2.3.1

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

* [improved bitmap rendering](https://linuxrocks.online/@dnkl/104785149754346986)
* <https://codeberg.org/dnkl/fcft/releases/tag/2.3.1>
* <https://codeberg.org/dnkl/fcft/releases/tag/2.3.0>
* <https://codeberg.org/dnkl/fcft/releases/tag/2.2.7>

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build foot fuzzel

**Review by kevincox — APPROVED** [review]

**Comment by sternenseemann** [comment]
Adapted the PR to update to the newly-released 2.3.1 version, hope this gets merged eventually…

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build foot fuzzel

**Comment by sternenseemann** [comment]
Closing in favor of #98270.

**Pull request closed without merging**
