### PR TITLE
plasma-applet-volumewin7mixer fix missing dependency

### PR DESCRIPTION
**Pull request by mdevlamynck**
Fixes missing dependency on specific qml elements.

###### Motivation for this change
One day the applet stopped working complaining that it could not find the module QtMultimedia. I'm not sure what changed but this seems to fix it.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by doronbehar — APPROVED** [review]

**Review by doronbehar — APPROVED** [review]

**Comment by aanderse** [comment]
@doronbehar you have tested this ensuring it works?

**Comment by doronbehar** [comment]
No :grimacing: , I just saw the diff and it makes sense.

**Comment by aanderse** [comment]
@doronbehar ok thanks for clarifying.
@mdevlamynck sorry for the delay, I'll try to test this in the next day or two and get back to you.

**Comment by aanderse** [comment]
I just tested `plasma-applet-volumewin7mixer` on `20.03` and it seems to work fine. Can you explain in more details your issue?

**Comment by mdevlamynck** [comment]
I recently switched to 20.03 and I also can't reproduce. So I guess we can close this.

The issue I had was that was that the applet was displaying a qml error instead of its UI. The error was about a dependency not found (QtMultimedia). I don't remember the exact error message though.

**Comment by aanderse** [comment]
Glad to hear you're up and running! Thanks.

**Pull request closed without merging**
