### PR TITLE
Block on aarch64 darwin

### PR DESCRIPTION
**Pull request by grahamc**
###### Description of changes

Add aarch64-darwin to the "unstable" job, making it a blocker for the `nixpkgs-*` channels.

The infra's macOS build capacity is primarily aarch64 anyway, and the x86 support is mostly emulated. Further, we're already building these targets elsewhere. The only real difference here is now we're offering a better experience to users on modern Apple hardware by ensuring build artifacts are available.

Note that we should not drop x86_64-darwin from the release channels any time soon. Not just the fact that you can still buy x86 Apple hardware brand neew, but also lots of CI infrastructure doesn't support aarch64-darwin yet. This means a significant number of Nix installations are x86.

Note this also adds Nix to the list of explicit blockers.

_Also: I haven't evaluated this locally. I'm on a laptop without a power adapter, but can put it through its paces on my desktop when I get home._

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by roberth** [comment]
Sounds good, but how does it relate to the support tiers?

Also I'm surprised that the tiers aren't in the manual.
 - https://github.com/NixOS/nixpkgs/issues/180492

**Comment by roberth** [comment]
Hi @grahamc, this PR looks good to me. I just had a question. Why did you close it?

**Comment by grahamc** [comment]
Just cleaning out several pages of old PRs that hadn’t moved in some time. Feel free to reopen and merge, or whatever! :)

**Comment by roberth** [comment]
Thanks for the quick response @grahamc, and for initiating this change.
The idea of this change came up recently at [nix.camp](https://nix.camp), so it  was good to (re)discover today that this idea has buy-in from someone who's worked on the NixOS build farm.
I'm taking care of this with a rebase over at https://github.com/NixOS/nixpkgs/pull/260429.

**Pull request closed without merging**
