### PR TITLE
emscripten: 1.37.16 -> 1.37.34

### PR DESCRIPTION
**Pull request by ryantm**
Semi-automatic update. These checks were performed:

- built on NixOS
- found 1.37.34 with grep in /nix/store/mdr47v3wdjmzic5c2nvdx5krdwl6bcxf-emscripten-1.37.34

### CODE REVIEW

**Comment by ryantm** [comment]
@GrahamcOfBorg build emscripten

**Comment by dtzWill** [comment]
Is the compiler tested as part of building itself, or should that be done as well? Never poked at the emscripten bits...

**Comment by joachifm** [comment]
cc @qknight @matthiasbeyer

**Comment by matthiasbeyer** [comment]
You meant @matthewbauer

**Review by matthewbauer — APPROVED** [review]

**Comment by joachifm** [comment]
@matthiasbeyer it worked out in the end :)

**Comment by dtzWill** [comment]
While debugging my follow-up PR, I found that this breaks emscriptenPackages?
Not familiar enough to say why, but it worked previously:

@GrahamcOfBorg build emscriptenPackages.zlib

Like I said before, does the resulting compiler still work? Apparently not... (at least not the way we used it) :(.

**Comment by ryantm** [comment]
@joachifm based on @dtzWill's cpmment seems like we should revert.

**Comment by qknight** [comment]
@ryantm @dtzWill i've been playing with this for a while now but it seems that those packages didn't build before either. no clue why yet.

i'll look into this. don't revert for the moment.

**Comment by ryantm** [comment]
@qknight It was already reverted.

**Comment by qknight** [comment]
@ryantm thanks for your effort!

see this: https://github.com/kripken/emscripten-fastcomp/issues/224

> ... you should use the same emscripten version in all 3 repos (emcc should warn if you do not).

well, it didn't warn IIRC

> You must also use the same version of LLVM and clang (unrelated to emscripten - if those repos don't match, LLVM won't be able to use clang properly). The same emscripten version in those repos will take care of that for you. Likewise the same emscripten version will ensure you are on the right LLVM version.

i found that out the hard way. 

in general we should change nixpkgs expressions so that one defines the version number as `1.37.36` and all the 3 expressions download the same version. 

our roadmap should be:

* get emscriptenPackages to comiple with 1.37.36
    * emcc main.c -> produces something working
    * emconfigure seems to fail
* get a meaningful set of tests in the `emscripten` package working
* refactor the 3 expressions to use the same target version (only set once)

@everyone

i've been playing with 1.37.36 and implemented the unit testing:

* source: https://github.com/qknight/nixpkgs/tree/emscripten-1.37.16-to-1.37.36

* result : https://gist.github.com/qknight/fd7027a70830b4080e3b4352476e8009

altough there are lots of errors, this is not looking so bad. i'd love to select some meaningful tests and get these into nixpkgs. we can't do all, this requires at least 4220.752s to complete, which is too long!

# building emscriptenPackage.zlib

still this won't compile with the new toolchain. no clue why, anyone?

```
joachim@lenovo-t530 ~/D/p/n/nixpkgs> nix-env -f default.nix -I nixpkgs=. -iA emscriptenPackages.zlib
installing ‘emscripten-zlib-1.2.11’
these derivations will be built:
  /nix/store/8xlwzkd9lsziq188fyznsdmyqgmg7w5f-emscripten-zlib-1.2.11.drv
building path(s) ‘/nix/store/1az5xq03k6qjms3mdvaiix25fk51whv4-emscripten-zlib-1.2.11-static’, ‘/nix/store/ak7rqj9bdhdf0ll4idr6sb06jzrcb6s3-emscripten-zlib-1.2.11-dev’, ‘/nix/store/qi1k9vbp9jzavx44n96zv2ihz96c16af-emscripten-zlib-1.2.11’
unpacking sources
unpacking source archive /nix/store/rrzja19jbqxbfryp2zchb2ma5h041rxh-zlib-1.2.11.tar.gz
source root is zlib-1.2.11
setting SOURCE_DATE_EPOCH to timestamp 1484501380 of file zlib-1.2.11/zutil.c
patching sources
configuring
INFO:root:generating system asset: is_vanilla.txt... (this will be cached in "/tmp/nix-build-emscripten-zlib-1.2.11.drv-0/.emscripten_cache/is_vanilla.txt" for subsequent builds)
INFO:root: - ok
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.
ERROR:root:Configure step failed with non-zero return code 1! Command line: ['./configure', '--prefix=/nix/store/qi1k9vbp9jzavx44n96zv2ihz96c16af-emscripten-zlib-1.2.11'] at /tmp/nix-build-emscripten-zlib-1.2.11.drv-0/zlib-1.2.11
builder for ‘/nix/store/8xlwzkd9lsziq188fyznsdmyqgmg7w5f-emscripten-zlib-1.2.11.drv’ failed with exit code 1
error: build of ‘/nix/store/8xlwzkd9lsziq188fyznsdmyqgmg7w5f-emscripten-zlib-1.2.11.drv’ failed

```

**Comment by matthewbauer** [comment]
Just a guess but maybe try setting 'hardeningDisable = [ "format" ]'

**Comment by qknight** [comment]
seems the python executable was missing and therefore `emconfigure`'s internals fail. i might have `json_c` and `zlib` working

**Comment by qknight** [comment]
LONG_BIT is no longer a problem, i've added this:

`emconfigure ./configure --prefix=$out --without-python`

to libxml2

**Comment by qknight** [comment]
@matthewbauer maybe you could check https://github.com/kripken/emscripten/issues/6341 for an obvious error i've made.

**Comment by matthewbauer** [comment]
@qknight That was just a guess based on the "Compiler error reporting is too harsh" line. But it sounds like python was the real culprit.

**Comment by matthewbauer** [comment]
@qknight Looks like this might be the culprit:

https://github.com/NixOS/nixpkgs/blob/5f020d5627789ce77b2997e360ece984c261bce7/pkgs/development/libraries/zlib/default.nix#L53

This was introduced in @Ericson2314's cross compiling patches.

**Comment by qknight** [comment]
@matthewbauer you are amazing!

setting: `NIX_CFLAGS_COMPILE="";` leads to a libz shared library!

**Comment by qknight** [comment]
status update:

* [x] the `emscriptenVersion` is a global attribute which is used for `emscripten` and `emscripten-fastcomp`
* [x] added a test to check if `emscripten` is working
* [x] updated to 1.37.28 (because i needed to test something)
* [x] fix emscriptenPackages.libxml2
* [x] fix emscriptenPackages.zlib
* [] fix emscriptenPackages.xmlmirror
* [] updated to 1.37.36

will upload my branch in a few secs...

**Comment by qknight** [comment]
@ryantm  @matthewbauer 

if you want to test my changes:

* source: https://github.com/qknight/nixpkgs/tree/emscripten-1.37.16-to-1.37.36
* command: nix-env -f default.nix -I nixpkgs=. -iA emscriptenPackages

**Comment by qknight** [comment]
so everything from my perspective is now working. someone interested in helping me to write the documentation?

**Comment by qknight** [comment]
\o/  done!

**Comment by qknight** [comment]
@matthewbauer please have a look at https://github.com/NixOS/nixpkgs/pull/37291

**Pull request merged**
