### PR TITLE
pmbootstrap: 1.30.0 -> 1.39.0

### LINKED ISSUE #133612: Pmbootstrap at version 1.30 but already is at 1.35
###### Checklist

New pmbootstrap version is out. Seems that they release only with git tags and don't use the release page anymore https://gitlab.com/postmarketOS/pmbootstrap/-/tags

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: pmbootstrap

current version: 1.30
desired version: 1.35

###### Notify maintainers

maintainers: @payas

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by MostAwesomeDude**
###### Motivation for this change

If merged, this would fix #133612. The chosen version is ahead of 1.37, which is the current minimum required to use `pmbootstrap` at all with upstream tools.

I tested this change by building a PostmarketOS image for an `lg-hammerhead`. The resulting image successfully flashes and boots the phone.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by lostnet — COMMENTED** [review]
Since there are a few more tests added in pmbootstrap between 1.30 and 1.39 I looked into the disabledTests and whether it was actually working. It looks like no tests are running because `checkPhase` has been overwritten by what belongs in `preCheck` in the original init pr. If you fix this, I think one of the new tests fails in the sandbox and needs to be added to `disabledTests`.

**Comment by MostAwesomeDude** [comment]
Not sure on the root cause of `aarch64-darwin` breakage, but the logs suggest that `pmbootstrap` or Alpine have problems with 64-bit ARM architecture detection.

**Comment by lostnet** [comment]
It looks like the darwin-arm64 is a problem in [pm arch mapping](https://gitlab.com/postmarketOS/pmbootstrap/-/blob/master/pmb/parse/arch.py) which seems like a part of pmb itself rather anything wrong with the test suite? I think according to [ZHF](https://github.com/NixOS/nixpkgs/issues/144627) you can do:

` broken = stdenv.isDarwin && stdenv.isAarch64;`

**Comment by jonringer** [comment]
that list of disabled tests... maybe we should just opt-in to some of them....

**Comment by lostnet** [comment]
@jonringer Setting up a $HOME and [configuring git](https://gitlab.com/postmarketOS/pmbootstrap/-/blob/master/.ci/prepare.sh#L25) seems to fix a small number of tests but pmbootstrap is very dependent on the directory it sets up with [pmbootstrap init](https://gitlab.com/postmarketOS/pmbootstrap/-/blob/master/.ci/prepare.sh#L29), so I think we are lucky ~2/3 of tests work without that setup.

Since the `pmbootstrap init` clones two repos and immediately starts pulling its configuration from one of them I think it might be a lot of effort and is probably only one precondition for many of the disabled pmboostrap tests.

**Review by lostnet — CHANGES_REQUESTED** [review]
I think broken is needs to be a meta attribute like in this [example](https://github.com/NixOS/nixpkgs/blob/a0dbe47318bbab7559ffbfa7c4872a517833409f/pkgs/applications/science/molecular-dynamics/viennarna/default.nix#L38)

**Review by lostnet — APPROVED** [review]
It looks good to me as is. Maybe @SuperSandro2000 or @e3bc54b2 would like to review or comment on the matter of disabledTests.

**Comment by e3bc54b2** [comment]
Thanks for tagging, but unfortunately I am no longer using pistmarketOS nor this utility anymore. As such, I'm not the best person to judge this. I'd also request to remove my name from maintainers for the same reason.

Thanks,
Payas

**Comment by SuperSandro2000** [comment]
> I'd also request to remove my name from maintainers for the same reason.

Please create a PR yourself doing that.

**Pull request merged**
