### PR TITLE
master -> staging-next

### PR DESCRIPTION
**Pull request by bhipple**
Proposing to merge master -> staging to fix ~10 Rust packages via https://github.com/NixOS/nixpkgs/pull/80153, and also avoid merge conflicts with the treewide no-op https://github.com/NixOS/nixpkgs/pull/79978

### CODE REVIEW

**Comment by veprbl** [comment]
@bhipple See https://discourse.nixos.org/t/maintainers-needed-for-merging-staging-staging-next-branches/3833/4

**Comment by bhipple** [comment]
Are you sure?  I changed the target branch from `staging` to `staging-next`, but if that's actually how it's supposed to be done, then I think the [RFC wording](https://github.com/NixOS/rfcs/blob/master/rfcs/0026-staging-workflow.md) might be out of date?  

> staging-next is branched from staging and only fixes to stabilize and security fixes shall be delivered to this branch. This branch shall be merged into master when deemed of sufficiently high quality.

This seems to imply that the merge goes `master -> staging -> staging-next -> master`.

**Comment by FRidh** [comment]
I just merged master into staging, there weren't any conflicts.

**Comment by FRidh** [comment]
Updates from master are typically merged via staging-next into staging, however, that is not necessary per se, e.g., if there aren't any updates in staging-next (as was the case now) there is no point.

**Pull request closed without merging**
