### PR TITLE
gns3: Fix python package not being pinned

### PR DESCRIPTION
**Pull request by Alan01252**
Due to https://github.com/NixOS/nixpkgs/issues/44426 the correct psutils
package is not picked up, this commit changes the code so the correct
version is always picked

###### Things done
- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Alan01252** [comment]
Thank you :) I learnt a lot from your commit! :)

**Review by primeos — COMMENTED** [review]
Hey @Alan01252 thanks for your PR :)

I've added an extra commit (will be squashed before merging) that tries to get rid of some redundancy (though not all of it, atm it would also make sense to move `defaultOverrides` into `default.nix` but I'm not sure if this will always be the case). I also took care of some minor style and copy&paste issues.

I've dropped the `aiohttp` pinning as I couldn't reproduce any issues. Does your overlay also override `aiohttp` or are you using a different channel? On the most recent nixos-unstable channel I currently get the expected version:
```
$ nix-build -A python3Packages.aiohttp
/nix/store/xw8zl3qcl8zha6wi7fns5rzmz2p1mqim-python3.7-aiohttp-3.6.2
```

**Comment by Alan01252** [comment]
I'm using stable and just had this as an override which is why I had to pin aiohttp, and copy that config over from the latest unstable to get it to build on my machine.

Trying to upgrade just aiohttp package from unstable and get it working with this code warped my mind a little bit and I wasn't able to figure it out.

**Comment by primeos** [comment]
@Alan01252 ok, I see. I suggest that we drop the `aiohttp` pinning then as this will probably quickly become too difficult to maintain as the stable and unstable branches diverge further (in the worst case we would have to pin every dependency). It would be nice to have but generally I try to avoid all overrides that are not necessary (I'd actually like to avoid the `psutil` and `jsonschema` overrides as well, but in the past I often had bad luck (bugs) when ignoring the version constraints from upstream). But at the same time I agree that this could be useful to have.

As for your use-case: If you use channels you could try something like this in your NixOS configuration (untested but looks fine - [source](https://www.reddit.com/r/NixOS/comments/50njte/install_a_package_from_unstable_while_running/)):
```nix
{ config, pkgs, ... }:
let
  unstable = import <nixos-unstable> {};
in {
  environment.systemPackages = [ unstable.packagehere ];
}
```
Or if you use a local git checkout the following should work:
```nix
{ config, pkgs, ... }:
let
  unstable = import /path/to/nixpkgs {};
in {
  environment.systemPackages = [ unstable.packagehere ]; # Or maybe unstable.pkgs.packagehere
}
```
Maybe also interesting (but most likely without the `allowUnfree = true;` example): https://nixos.wiki/wiki/Cheatsheet#Customizing_Packages

With nix-shell and nix-env this is possible as well (I can also post an example if you want).

Hope this helps.

**Review by primeos — APPROVED** [review]
The current state LGTM, so I'll already merge it, but of course I'm still open to discussing additional changes, if you want to change something else (e.g. regarding the `aiohttp` pining) ;)

Anyway, thanks for the PR :) The current pinning should now work as expected when using overlays.

**Comment by Alan01252** [comment]
No this is great thank you. The problem I was having is I wanted "stable" python but "unstable" aiohttp and that combination I just could not figure out. I should probably just move to unstable python.
I should also mention to get ubridge to work proplerly with gns3 ( using local server ) I had to make sure that all the executables were started in the same directory so I've got this.

`
security.wrappers.gns3 = {
    source  = "${pkgs.myGns3.guiStable.out}/bin/gns3";
    owner   = "nobody";
    group   = "nogroup";
   };

   security.wrappers.gns3server = {
    source  = "${pkgs.myGns3.serverStable.out}/bin/gns3server";
    owner   = "nobody";
    group   = "nogroup";
   };


   security.wrappers.ubridge = {
    source  = "${pkgs.ubridge.out}/bin/ubridge";
    owner   = "nobody";
    group   = "nogroup";
    capabilities = "cap_net_admin,cap_net_raw+ep";
   };

In my configuration to make this work

**Pull request merged**
