### PR TITLE
WIP: pipenv: 10.1.2 -> 11.9.0

### PR DESCRIPTION
**Pull request by Mic92**
Also avoid propagating python libraries to keep nix-shell environments
clean.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
needs a better hack...

```console
$ pipenv --python pypy
Creating a virtualenv for this project…
Using /nix/store/8zq58g972iyir1pb8bxpx1j0rv0lxsh4-pypy-5.10.0/bin/pypy (2.7.13) to create virtualenv…
⠋/nix/store/azw9ys2m2fpfzf730xjcxja890gpyp58-python3-3.6.4/bin/python3.6m: Error while finding module specification for 'pipenv.pew' (ModuleNotFoundError: No module named 'pipenv')
```

**Comment by Mic92** [comment]
Given that I did not find a way to use this package without PYTHONPATH set, should we move this back to pythonPackages?

**Comment by domenkozar** [comment]
I've pushed 7a7463d0a3fe6d39a7fc499a0fd9756a3c671e62 which unbreaks pipenv for me - was previously hitting https://github.com/NixOS/nixpkgs/issues/33713

How can I reproduce the issue with leaking PYTHONPATH?

**Comment by Mic92** [comment]
@domenkozar I mean if your python version is different from the pipenv one (python2/pypy) then the following `default.nix`:

```
cat default.nix
with import <nixpkgs> {};
stdenv.mkDerivation {
  name = "env";
  buildInputs = [
    pipenv
  ];
}
```

will pollute the PYTHONPATH:

```console
$ nix-shell --command 'echo $PYTHONPATH'
/nix/store/4cww1g3ghkiga0sp2g55rf2248ds86rm-pipenv-2018.5.18/lib/python3.6/site-packages:/nix/store/p5b1l7akj6ps1jplkzpama73xxa4q6a6-pew-1.1.2/lib/python3.6/site-packages:/nix/store/rxijic79c3d095c94y4b8c4f13jp3vzz-python3.6-virtualenv-15.2.0/lib/python3.6/site-packages:/nix/store/yxzy33fw61kj9ljk30i5qyjrv3pax0kc-python3-3.6.5/lib/python3.6/site-packages:/nix/store/4m1r0plr5g078z5c5hxskhyxjlsb073y-python3.6-setuptools-39.0.1/lib/python3.6/site-packages:/nix/store/px80xr2bw4racjw6njnvfj7j8m42qisd-python3.6-virtualenv-clone-0.2.5/lib/python3.6/site-packages:/nix/store/w18a3cl9g0rppnrvig820ywn8hg6x87z-python3.6-pip-10.0.1/lib/python3.6/site-packages:/nix/store/rdhrdmjz92ka56gp20b0vzg52lwcmry3-python3.6-urllib3-1.22/lib/python3.6/site-packages:/nix/store/aw31s130gc83qcvnd1gkz3dr6dq3fdfz-python3.6-idna-2.6/lib/python3.6/site-packages:/nix/store/hwbkjlajddk8syip7rp40igfp8r0dsyc-python3.6-asn1crypto-0.24.0/lib/python3.6/site-packages:/nix/store/h8nyb584z3m76cd8dvsc0kj25sls3sji-python3.6-packaging-17.1/lib/python3.6/site-packages:/nix/store/1r4jayn0cns7cqb71sv7nxss9yrgd5gc-python3.6-pyparsing-2.2.0/lib/python3.6/site-packages:/nix/store/jx8923scaljqxz9sikk9vivc478fbg38-python3.6-six-1.11.0/lib/python3.6/site-packages:/nix/store/jx8923scaljqxz9sikk9vivc478fbg38-python3.6-six-1.11.0/lib/python3.6/site-packages:/nix/store/w79xzsxpjc8acgn9fqrbk4a344jr39zj-python3.6-pycparser-2.18/lib/python3.6/site-packages:/nix/store/kxc9czasczfry75hlzmgmw5w9sl73v2b-python3.6-cffi-1.11.5/lib/python3.6/site-packages:/nix/store/vh2ilxlv0xzidk6p39722msibzxjylpv-python3.6-cryptography-2.2.2/lib/python3.6/site-packages:/nix/store/437ls21hfqdkamh8ngfkxfvbsj23qkqm-python3.6-pyasn1-0.4.3/lib/python3.6/site-packages:/nix/store/s7jlb60pgwp308gp85han2p31vz0n792-python3.6-pyOpenSSL-17.5.0/lib/python3.6/site-packages:/nix/store/4rdwjmrbl00v3afqs605f0q1gp0mmhmq-python3.6-certifi-2018.1.18/lib/python3.6/site-packages:/nix/store/1n9g1agsmkqzy3diylkr7q0ijzvkwn6m-python3.6-pysocks-1.6.6/lib/python3.6/site-packages:/nix/store/lmsmkz82m9fgah0lshbc37mfadhxy0yv-python3.6-chardet-3.0.4/lib/python3.6/site-packages:/nix/store/7kid9vh8p0sr98mxbdlkmak3lybixnky-python3.6-requests-2.18.4/lib/python3.6/site-packages:/nix/store/zszbx5cpv0xdwcmr921c5mng3bgc88pa-python3.6-flake8-3.5.0/lib/python3.6/site-packages:/nix/store/4fhy695zd39ca1kabh5scdj9in6lmard-python3.6-pyflakes-1.6.0/lib/python3.6/site-packages:/nix/store/sg597480fd4ad537fnjfc5n4kgbclg56-python3.6-pycodestyle-2.3.1/lib/python3.6/site-packages:/nix/store/11ayq856qgwiwmcnf0451rinyzbs3j7v-python3.6-mccabe-0.6.1/lib/python3.6/site-packages:/nix/store/4cww1g3ghkiga0sp2g55rf2248ds86rm-pipenv-2018.5.18/lib/python3.6/site-packages:/nix/store/p5b1l7akj6ps1jplkzpama73xxa4q6a6-pew-1.1.2/lib/python3.6/site-packages:/nix/store/rxijic79c3d095c94y4b8c4f13jp3vzz-python3.6-virtualenv-15.2.0/lib/python3.6/site-packages:/nix/store/yxzy33fw61kj9ljk30i5qyjrv3pax0kc-python3-3.6.5/lib/python3.6/site-packages:/nix/store/4m1r0plr5g078z5c5hxskhyxjlsb073y-python3.6-setuptools-39.0.1/lib/python3.6/site-packages:/nix/store/px80xr2bw4racjw6njnvfj7j8m42qisd-python3.6-virtualenv-clone-0.2.5/lib/python3.6/site-packages:/nix/store/w18a3cl9g0rppnrvig820ywn8hg6x87z-python3.6-pip-10.0.1/lib/python3.6/site-packages:/nix/store/rdhrdmjz92ka56gp20b0vzg52lwcmry3-python3.6-urllib3-1.22/lib/python3.6/site-packages:/nix/store/aw31s130gc83qcvnd1gkz3dr6dq3fdfz-python3.6-idna-2.6/lib/python3.6/site-packages:/nix/store/hwbkjlajddk8syip7rp40igfp8r0dsyc-python3.6-asn1crypto-0.24.0/lib/python3.6/site-packages:/nix/store/h8nyb584z3m76cd8dvsc0kj25sls3sji-python3.6-packaging-17.1/lib/python3.6/site-packages:/nix/store/1r4jayn0cns7cqb71sv7nxss9yrgd5gc-python3.6-pyparsing-2.2.0/lib/python3.6/site-packages:/nix/store/jx8923scaljqxz9sikk9vivc478fbg38-python3.6-six-1.11.0/lib/python3.6/site-packages:/nix/store/jx8923scaljqxz9sikk9vivc478fbg38-python3.6-six-1.11.0/lib/python3.6/site-packages:/nix/store/w79xzsxpjc8acgn9fqrbk4a344jr39zj-python3.6-pycparser-2.18/lib/python3.6/site-packages:/nix/store/kxc9czasczfry75hlzmgmw5w9sl73v2b-python3.6-cffi-1.11.5/lib/python3.6/site-packages:/nix/store/vh2ilxlv0xzidk6p39722msibzxjylpv-python3.6-cryptography-2.2.2/lib/python3.6/site-packages:/nix/store/437ls21hfqdkamh8ngfkxfvbsj23qkqm-python3.6-pyasn1-0.4.3/lib/python3.6/site-packages:/nix/store/s7jlb60pgwp308gp85han2p31vz0n792-python3.6-pyOpenSSL-17.5.0/lib/python3.6/site-packages:/nix/store/4rdwjmrbl00v3afqs605f0q1gp0mmhmq-python3.6-certifi-2018.1.18/lib/python3.6/site-packages:/nix/store/1n9g1agsmkqzy3diylkr7q0ijzvkwn6m-python3.6-pysocks-1.6.6/lib/python3.6/site-packages:/nix/store/lmsmkz82m9fgah0lshbc37mfadhxy0yv-python3.6-chardet-3.0.4/lib/python3.6/site-packages:/nix/store/7kid9vh8p0sr98mxbdlkmak3lybixnky-python3.6-requests-2.18.4/lib/python3.6/site-packages:/nix/store/zszbx5cpv0xdwcmr921c5mng3bgc88pa-python3.6-flake8-3.5.0/lib/python3.6/site-packages:/nix/store/4fhy695zd39ca1kabh5scdj9in6lmard-python3.6-pyflakes-1.6.0/lib/python3.6/site-packages:/nix/store/sg597480fd4ad537fnjfc5n4kgbclg56-python3.6-pycodestyle-2.3.1/lib/python3.6/site-packages:/nix/store/11ayq856qgwiwmcnf0451rinyzbs3j7v-python3.6-mccabe-0.6.1/lib/python3.6/site-packages:/nix/store/4cww1g3ghkiga0sp2g55rf2248ds86rm-pipenv-2018.5.18/lib/python3.6/site-packages:/nix/store/p5b1l7akj6ps1jplkzpama73xxa4q6a6-pew-1.1.2/lib/python3.6/site-packages:/nix/store/rxijic79c3d095c94y4b8c4f13jp3vzz-python3.6-virtualenv-15.2.0/lib/python3.6/site-packages:/nix/store/yxzy33fw61kj9ljk30i5qyjrv3pax0kc-python3-3.6.5/lib/python3.6/site-packages:/nix/store/4m1r0plr5g078z5c5hxskhyxjlsb073y-python3.6-setuptools-39.0.1/lib/python3.6/site-packages:/nix/store/px80xr2bw4racjw6njnvfj7j8m42qisd-python3.6-virtualenv-clone-0.2.5/lib/python3.6/site-packages:/nix/store/w18a3cl9g0rppnrvig820ywn8hg6x87z-python3.6-pip-10.0.1/lib/python3.6/site-packages:/nix/store/rdhrdmjz92ka56gp20b0vzg52lwcmry3-python3.6-urllib3-1.22/lib/python3.6/site-packages:/nix/store/aw31s130gc83qcvnd1gkz3dr6dq3fdfz-python3.6-idna-2.6/lib/python3.6/site-packages:/nix/store/hwbkjlajddk8syip7rp40igfp8r0dsyc-python3.6-asn1crypto-0.24.0/lib/python3.6/site-packages:/nix/store/h8nyb584z3m76cd8dvsc0kj25sls3sji-python3.6-packaging-17.1/lib/python3.6/site-packages:/nix/store/1r4jayn0cns7cqb71sv7nxss9yrgd5gc-python3.6-pyparsing-2.2.0/lib/python3.6/site-packages:/nix/store/jx8923scaljqxz9sikk9vivc478fbg38-python3.6-six-1.11.0/lib/python3.6/site-packages:/nix/store/jx8923scaljqxz9sikk9vivc478fbg38-python3.6-six-1.11.0/lib/python3.6/site-packages:/nix/store/w79xzsxpjc8acgn9fqrbk4a344jr39zj-python3.6-pycparser-2.18/lib/python3.6/site-packages:/nix/store/kxc9czasczfry75hlzmgmw5w9sl73v2b-python3.6-cffi-1.11.5/lib/python3.6/site-packages:/nix/store/vh2ilxlv0xzidk6p39722msibzxjylpv-python3.6-cryptography-2.2.2/lib/python3.6/site-packages:/nix/store/437ls21hfqdkamh8ngfkxfvbsj23qkqm-python3.6-pyasn1-0.4.3/lib/python3.6/site-packages:/nix/store/s7jlb60pgwp308gp85han2p31vz0n792-python3.6-pyOpenSSL-17.5.0/lib/python3.6/site-packages:/nix/store/4rdwjmrbl00v3afqs605f0q1gp0mmhmq-python3.6-certifi-2018.1.18/lib/python3.6/site-packages:/nix/store/1n9g1agsmkqzy3diylkr7q0ijzvkwn6m-python3.6-pysocks-1.6.6/lib/python3.6/site-packages:/nix/store/lmsmkz82m9fgah0lshbc37mfadhxy0yv-python3.6-chardet-3.0.4/lib/python3.6/site-packages:/nix/store/7kid9vh8p0sr98mxbdlkmak3lybixnky-python3.6-requests-2.18.4/lib/python3.6/site-packages:/nix/store/zszbx5cpv0xdwcmr921c5mng3bgc88pa-python3.6-flake8-3.5.0/lib/python3.6/site-packages:/nix/store/4fhy695zd39ca1kabh5scdj9in6lmard-python3.6-pyflakes-1.6.0/lib/python3.6/site-packages:/nix/store/sg597480fd4ad537fnjfc5n4kgbclg56-python3.6-pycodestyle-2.3.1/lib/python3.6/site-packages:/nix/store/11ayq856qgwiwmcnf0451rinyzbs3j7v-python3.6-mccabe-0.6.1/lib/python3.6/site-packages:/nix/store/4cww1g3ghkiga0sp2g55rf2248ds86rm-pipenv-2018.5.18/lib/python3.6/site-packages:/nix/store/p5b1l7akj6ps1jplkzpama73xxa4q6a6-pew-1.1.2/lib/python3.6/site-packages:/nix/store/rxijic79c3d095c94y4b8c4f13jp3vzz-python3.6-virtualenv-15.2.0/lib/python3.6/site-packages:/nix/store/yxzy33fw61kj9ljk30i5qyjrv3pax0kc-python3-3.6.5/lib/python3.6/site-packages:/nix/store/4m1r0plr5g078z5c5hxskhyxjlsb073y-python3.6-setuptools-39.0.1/lib/python3.6/site-packages:/nix/store/px80xr2bw4racjw6njnvfj7j8m42qisd-python3.6-virtualenv-clone-0.2.5/lib/python3.6/site-packages:/nix/store/w18a3cl9g0rppnrvig820ywn8hg6x87z-python3.6-pip-10.0.1/lib/python3.6/site-packages:/nix/store/rdhrdmjz92ka56gp20b0vzg52lwcmry3-python3.6-urllib3-1.22/lib/python3.6/site-packages:/nix/store/aw31s130gc83qcvnd1gkz3dr6dq3fdfz-python3.6-idna-2.6/lib/python3.6/site-packages:/nix/store/hwbkjlajddk8syip7rp40igfp8r0dsyc-python3.6-asn1crypto-0.24.0/lib/python3.6/site-packages:/nix/store/h8nyb584z3m76cd8dvsc0kj25sls3sji-python3.6-packaging-17.1/lib/python3.6/site-packages:/nix/store/1r4jayn0cns7cqb71sv7nxss9yrgd5gc-python3.6-pyparsing-2.2.0/lib/python3.6/site-packages:/nix/store/jx8923scaljqxz9sikk9vivc478fbg38-python3.6-six-1.11.0/lib/python3.6/site-packages:/nix/store/jx8923scaljqxz9sikk9vivc478fbg38-python3.6-six-1.11.0/lib/python3.6/site-packages:/nix/store/w79xzsxpjc8acgn9fqrbk4a344jr39zj-python3.6-pycparser-2.18/lib/python3.6/site-packages:/nix/store/kxc9czasczfry75hlzmgmw5w9sl73v2b-python3.6-cffi-1.11.5/lib/python3.6/site-packages:/nix/store/vh2ilxlv0xzidk6p39722msibzxjylpv-python3.6-cryptography-2.2.2/lib/python3.6/site-packages:/nix/store/437ls21hfqdkamh8ngfkxfvbsj23qkqm-python3.6-pyasn1-0.4.3/lib/python3.6/site-packages:/nix/store/s7jlb60pgwp308gp85han2p31vz0n792-python3.6-pyOpenSSL-17.5.0/lib/python3.6/site-packages:/nix/store/4rdwjmrbl00v3afqs605f0q1gp0mmhmq-python3.6-certifi-2018.1.18/lib/python3.6/site-packages:/nix/store/1n9g1agsmkqzy3diylkr7q0ijzvkwn6m-python3.6-pysocks-1.6.6/lib/python3.6/site-packages:/nix/store/lmsmkz82m9fgah0lshbc37mfadhxy0yv-python3.6-chardet-3.0.4/lib/python3.6/site-packages:/nix/store/7kid9vh8p0sr98mxbdlkmak3lybixnky-python3.6-requests-2.18.4/lib/python3.6/site-packages:/nix/store/zszbx5cpv0xdwcmr921c5mng3bgc88pa-python3.6-flake8-3.5.0/lib/python3.6/site-packages:/nix/store/4fhy695zd39ca1kabh5scdj9in6lmard-python3.6-pyflakes-1.6.0/lib/python3.6/site-packages:/nix/store/sg597480fd4ad537fnjfc5n4kgbclg56-python3.6-pycodestyle-2.3.1/lib/python3.6/site-packages:/nix/store/11ayq856qgwiwmcnf0451rinyzbs3j7v-python3.6-mccabe-0.6.1/lib/python3.6/site-packages
```

This might be also a problem if it adds conflicting library versions.

**Pull request closed without merging**
