### PR TITLE
default-gcc-version: 12 -> 13 if stdenv.isAarch64

### PR DESCRIPTION
**Pull request by wegank**
## Description of changes

`default-gcc-version` was bumped in #268097 on x86_64-linux, on i686-linux, on armv7l-linux, on powerpc64le-linux, on riscv64-linux...

But not on aarch64-linux??

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by wegank** [comment]
@ofborg build stdenv stdenv.passthru.tests

**Comment by wegank** [comment]
@ofborg build waylandpp waylandpp.passthru.tests

**Comment by wegank** [comment]
```
$ nix-build -A libhwy
...
[66/137] Building CXX object CMakeFiles/shuffle4_test.dir/hwy/tests/shuffle4_test.cc.o
FAILED: CMakeFiles/shuffle4_test.dir/hwy/tests/shuffle4_test.cc.o 
/nix/store/vlyjcld1smalc4sgalddw5j73xgd5kn7-gcc-wrapper-13.2.0/bin/g++ -DHWY_STATIC_DEFINE -I/build/source -isystem /nix/store/4pcmwfklwmsh0sxcgvdlmyg8xcy1zm96-gtest-1.12.1-dev/include -O3 -DNDEBUG -fPIE -fvisibility=hidden -fvisibility-inlines-hidden -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -fmerge-all-constants -Wall -Wextra -Wconversion -Wsign-conversion -Wvla -Wnon-virtual-dtor -fmath-errno -fno-exceptions -DHWY_IS_TEST=1 -MD -MT CMakeFiles/shuffle4_test.dir/hwy/tests/shuffle4_test.cc.o -MF CMakeFiles/shuffle4_test.dir/hwy/tests/shuffle4_test.cc.o.d -o CMakeFiles/shuffle4_test.dir/hwy/tests/shuffle4_test.cc.o -c /build/source/hwy/tests/shuffle4_test.cc
during GIMPLE pass: fre
/build/source/hwy/tests/shuffle4_test.cc: In static member function 'static void hwy::N_SVE::TestPer4LaneBlockShuffle::TestTblLookupPer4LaneBlkShuf(D, size_t, hwy::N_SVE::TFromD<D>*, hwy::N_SVE::TFromD<D>*) [with D = hwy::N_SVE::Simd<long int, 32, 0>]':
/build/source/hwy/tests/shuffle4_test.cc:222:1: internal compiler error: in const_unop, at fold-const.cc:1884
  222 | }  // namespace hwy
      | ^
0x1a0cec7 diagnostic_impl(rich_location*, diagnostic_metadata const*, int, char const*, std::__va_list*, diagnostic_t)
        ???:0
0x1a0dafb internal_error(char const*, ...)
        ???:0
0x708d37 fancy_abort(char const*, int, char const*)
        ???:0
0xb1bea7 const_unop(tree_code, tree_node*, tree_node*)
        ???:0
0x1233aeb gimple_resimplify1(gimple**, gimple_match_op*, tree_node* (*)(tree_node*))
        ???:0
0x126bc97 gimple_simplify(gimple*, gimple_match_op*, gimple**, tree_node* (*)(tree_node*), tree_node* (*)(tree_node*))
        ???:0
0xb5a71b gimple_fold_stmt_to_constant_1(gimple*, tree_node* (*)(tree_node*), tree_node* (*)(tree_node*))
        ???:0
0xfbe15b visit_stmt(gimple*, bool) [clone .isra.0]
        ???:0
0xfbeccf process_bb(rpo_elim&, basic_block_def*, bool, bool, bool, bool, bool, bitmap_head*, bool)
        ???:0
0xfc0a87 do_rpo_vn_1(function*, edge_def*, bitmap_head*, bool, bool, vn_lookup_kind)
        ???:0
0xfc160b (anonymous namespace)::pass_fre::execute(function*)
        ???:0
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
[67/137] Building CXX object CMakeFiles/compare_test.dir/hwy/tests/compare_test.cc.o
FAILED: CMakeFiles/compare_test.dir/hwy/tests/compare_test.cc.o 
```

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by amjoseph-nixpkgs** [comment]
> But not on aarch64-linux??

Correct; I don't have enough `aarch64-linux` builders to test that.  It is a Hydra-built platform, so I don't want to cause unknown amounts of breakage there.

For the non-Hydra platforms (`powerpc64le`, `mips*`, etc), well, those of us who run those platforms sort of expect breakage from version bumps.  Goes with the territory.  FWIW I fixed all the breakage on `powerpc64le` and `mips64el` for the packages I use (a lot on `powerpc64le`, but for `mips64el` just the stuff my routers run).

**Review by ghost — APPROVED** [review]
I am in favor of merging this to `staging` *after* 268097 makes it to `master`.

- https://nixpk.gs/pr-tracker.html?pr=268097

**Comment by amjoseph-nixpkgs** [comment]
After both #268097 and this PR make to `master` we can start pestering @reckenrode to see about doing Darwin as well.

**Comment by amjoseph-nixpkgs** [comment]
> https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110280 (fixed in GCC 13.2.1, 14.0)

Looks like GCC 13.2.1 isn't released yet? https://gcc.gnu.org/gcc-13/

If you know which commit fixed it we could cherry-pick that.

**Comment by amjoseph-nixpkgs** [comment]
Ah, never mind, I see you cherry-picked the fix.

**Comment by yu-re-ka** [comment]
I am seeing a new failure on pkgs.reptyr: https://termbin.com/nqqk

**Review by yu-re-ka — APPROVED** [review]
Besides reptyr, I could not find any issues. Built my laptop with master + this applied

**Pull request merged**
