### PR TITLE
gettext: 0.21.1 -> 0.22.4

### PR DESCRIPTION
**Pull request by wegank**
## Description of changes

https://savannah.gnu.org/news/?group=gettext

On Linux, `gettext` requires a working iconv, which breaks the build of `xgcc` in stage1.5. A workaround is to pass `--disable-nls` to the derivation of `xgcc`, then build `gettext` again in stage3, where a fresh `glibc` has been built.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by wegank** [comment]
@ofborg build gettext gettext.passthru.tests

**Comment by wegank** [comment]
```
msgfmt -o fr.mo ../../../../gcc-13.2.0/libstdc++-v3/po/fr.po
msgfmt: Cannot convert from "ISO-8859-1" to "UTF-8". msgfmt relies on iconv(). This version was built without iconv().
make[4]: *** [Makefile:564: de.mo] Error 1
make[4]: *** Waiting for unfinished jobs....
msgfmt: Cannot convert from "ISO-8859-1" to "UTF-8". msgfmt relies on iconv(). This version was built without iconv().
make[4]: *** [Makefile:564: fr.mo] Error 1
make[4]: Leaving directory '/build/build/x86_64-unknown-linux-gnu/libstdc++-v3/po'
make[3]: *** [Makefile:576: all-recursive] Error 1
make[3]: Leaving directory '/build/build/x86_64-unknown-linux-gnu/libstdc++-v3'
make[2]: *** [Makefile:501: all] Error 2
make[2]: Leaving directory '/build/build/x86_64-unknown-linux-gnu/libstdc++-v3'
make[1]: *** [Makefile:11603: all-target-libstdc++-v3] Error 2
make[1]: Leaving directory '/build/build'
make: *** [Makefile:1042: all] Error 2
error: builder for '/nix/store/73cfjra6khpbazzgvq1a5f7f1qs7aibv-xgcc-13.2.0.drv' failed with exit code 2;
       last 10 log lines:
       > msgfmt: Cannot convert from "ISO-8859-1" to "UTF-8". msgfmt relies on iconv(). This version was built without iconv().
       > make[4]: *** [Makefile:564: fr.mo] Error 1
       > make[4]: Leaving directory '/build/build/x86_64-unknown-linux-gnu/libstdc++-v3/po'
       > make[3]: *** [Makefile:576: all-recursive] Error 1
       > make[3]: Leaving directory '/build/build/x86_64-unknown-linux-gnu/libstdc++-v3'
       > make[2]: *** [Makefile:501: all] Error 2
       > make[2]: Leaving directory '/build/build/x86_64-unknown-linux-gnu/libstdc++-v3'
       > make[1]: *** [Makefile:11603: all-target-libstdc++-v3] Error 2
       > make[1]: Leaving directory '/build/build'
       > make: *** [Makefile:1042: all] Error 2
       For full logs, run 'nix log /nix/store/73cfjra6khpbazzgvq1a5f7f1qs7aibv-xgcc-13.2.0.drv'.
error: 1 dependencies of derivation '/nix/store/x2i8c0mmcnq7fklnxs0gxy1dli08bd6j-bootstrap-stage2-gcc-wrapper-13.2.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hmi74vblw28343xhl8cbc8p078fy8p65-bootstrap-stage2-stdenv-linux.drv' failed to build
```

**Comment by reckenrode** [comment]
It looks like it’s going to require Darwin bootstrap changes to have gettext use CoreServices. I made some progress tonight, but I’ll need to work on it some more tomorrow.

**Comment by reckenrode** [comment]
The following patch allows the Darwin stdenv to eval. I’ll kick off a build overnight, but I wanted to post it for feedback.

The patch breaks the infinite recursion by conditionally linking CoreServices. Early in the bootstrap, CoreServices is not linked. This should be safe because the set of programs is finite. We don’t have to worry about accidentally linking gettext against something that will crash (such as aria2, which motivated the change). At the end of the bootstrap when everything is rebuilt against the final libraries, gettext is linked against CoreServices from a previous stage. That should be safe to do because CoreServices is a system framework.

```patch
diff --git a/pkgs/development/libraries/gettext/default.nix b/pkgs/development/libraries/gettext/default.nix
index 4f81df001cc0..906edc0b446e 100644
--- a/pkgs/development/libraries/gettext/default.nix
+++ b/pkgs/development/libraries/gettext/default.nix
@@ -1,4 +1,4 @@
-{ stdenv, lib, fetchurl, libiconv, xz, bash
+{ stdenv, lib, fetchurl, libiconv, xz, bash, darwin
 }:
 
 # Note: this package is used for bootstrapping fetchurl, and thus
@@ -19,6 +19,7 @@ stdenv.mkDerivation rec {
     # fix reproducibile output, in particular in the grub2 build
     # https://savannah.gnu.org/bugs/index.php?59658
     ./0001-msginit-Do-not-use-POT-Creation-Date.patch
+  ] ++ lib.optionals (darwin.apple_sdk.frameworks.CoreServices == null) [
     # prevent infinite recursion for the darwin stdenv
     ./0002-Revert-Avoid-crash-on-macOS-14.patch
   ];
@@ -62,6 +63,9 @@ stdenv.mkDerivation rec {
   ++ lib.optionals (!stdenv.isLinux && !stdenv.hostPlatform.isCygwin) [
     # HACK, see #10874 (and 14664)
     libiconv
+  ]
+  ++ lib.optionals (stdenv.isDarwin && darwin.apple_sdk.frameworks.CoreServices != null) [
+    darwin.apple_sdk.frameworks.CoreServices
   ];
 
   setupHooks = [
diff --git a/pkgs/stdenv/darwin/default.nix b/pkgs/stdenv/darwin/default.nix
index c94c56daae1c..b4b0cdf3e7a0 100644
--- a/pkgs/stdenv/darwin/default.nix
+++ b/pkgs/stdenv/darwin/default.nix
@@ -452,6 +452,9 @@ in
 
       curl = super.curlMinimal;
 
+      # Don’t link CoreServices during the bootstrap to prevent an infinite recursion.
+      gettext = super.gettext.override { darwin.apple_sdk.frameworks.CoreServices = null; };
+
       # Disable tests because they use dejagnu, which fails to run.
       libffi = super.libffi.override { doCheck = false; };
 
@@ -1082,6 +1085,13 @@ in
         inherit (prevStage) fetchurl;
       };
 
+      # Use CoreServices from the previous stage to avoid an infinite recursion.
+      gettext = super.gettext.override {
+        darwin.apple_sdk.frameworks = {
+          inherit (prevStage.darwin.apple_sdk.frameworks) CoreServices;
+        };
+      };
+
       libyaml = super.libyaml.override {
         inherit (prevStage) fetchFromGitHub;
       };
```

**Comment by reckenrode** [comment]
It took longer than expected, but I can confirm I was able to bootstrap the Darwin stdenv with the above patch on both aarch64- and x86_64-darwin.

```console
$ ./result-aarch64/bin/gettext --version
gettext (GNU gettext-runtime) 0.22.4
Copyright (C) 1995-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Ulrich Drepper.
$ otool -L ./result-aarch64/bin/gettext
./result-aarch64/bin/gettext:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1770.255.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1122.11.0)
	/nix/store/k36qfqm8qplpp7ay8q7kq3yi17jfb4bk-gettext-0.22.4/lib/libintl.8.dylib (compatibility version 13.0.0, current version 13.0.0)
	/nix/store/nz4fff34byj1jjy1hka717rhpi7ma2i9-libiconv-50/lib/libiconv.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
$  otool -L ./result-x86_64/bin/gettext
./result-x86_64/bin/gettext:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1349.8.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 775.19.0)
	/nix/store/c8ajzwdwr3drjjri6cyd2jx9prd5jy0v-gettext-0.22.4/lib/libintl.8.dylib (compatibility version 13.0.0, current version 13.0.0)
	/nix/store/jbbxab2nl7hs56rxlr16a64ik1rcm8sn-libiconv-50/lib/libiconv.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```

**Comment by reckenrode** [comment]
I have a few changes I was planning to submit as cleanup for Darwin but haven’t had an opportunity to do so yet. If you’d like to include them, see below. Otherwise, I can cherry-pick them into a separate PR.

* https://github.com/reckenrode/nixpkgs/commit/7698dfe7bd27cc1caddbd44f8b19933461ddabb3 - fixes building FontForge with gettext 0.22;
* https://github.com/reckenrode/nixpkgs/commit/71b04150a0d71a7b008cb02f8b2c7640cd7676f2 - propagating frameworks from the stdenv breaks `overrideSDK`;
* https://github.com/reckenrode/nixpkgs/commit/ecd4aa5193c9119415ceb63d6375cc2567916e9e - clang 18 compatibility;
* https://github.com/reckenrode/nixpkgs/commit/206842a1e33f0b15e47d41ad73bb34774c287584 - add a separate `dev` output (also needed for Darwin’s bootstrap); and
* https://github.com/reckenrode/nixpkgs/commit/3506856ee316d9967e9f466fe42a74b5d6c50893 - only use `out` on Darwin;

**Comment by reckenrode** [comment]
Thinking about it some more, those last two commits are probably required. IIRC propagating CoreServices means it has to be included in the stdenv’s `allowedRequisites`.

**Comment by emilazy** [comment]
Friendly ping :) Any update on this?

**Comment by reckenrode** [comment]
The last attempt to update gettext stalled out due to the needed Darwin changes. Fortunately, https://github.com/NixOS/nixpkgs/pull/346043 should make them all unnecessary. It’s not necessary to propagate frameworks anymore, so no stdenv changes are needed.

The FontForge and clang 18 changes are needed though.

**Comment by emilazy** [comment]
@wegank Are you okay for this to be undrafted and merged (either into `staging` or into `llvm-19` for https://github.com/NixOS/nixpkgs/pull/354107)?

**Comment by wegank** [comment]
I haven't tested on x86_64-darwin, but feel free to take the commits.

**Comment by emilazy** [comment]
I’ll merge into `llvm-19` to minimize risk, since we’ve been doing a lot of Darwin testing there and this would unblock our progress on the bump. Thank you!

**Pull request merged**
