### PR TITLE
jcef-jetbrains: 675 ->767

### PR DESCRIPTION
**Pull request by mevatron**
## Description of changes

Upgraded jcef for 241.* plugins
Added libGL fixes
Fixed some cross-compiler issues with fsnotifier

I was unable to completely get past the gnome-vfs cross-compiler errors, but went as far as I was able. I removed gnome-vfs changes per @zlepper recommendation.

This work should help assist my nx-console plugin PR #306677, the plugin appears to work using this PR and #309011.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [~] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by niknetniko — APPROVED** [review]
Works for me

**Review by liff — APPROVED** [review]
Works for me too, tested with Rust Rover.

**Comment by zlepper** [comment]
Just took a look at this due to also needing jcef updated for Writerside. Picking at the code changes i don't entirely get why the changes to `pkgs/desktops/gnome-2/platform/gnome-vfs/default.nix` are in here, they seem very unrelated to jcef and is probably what is causing a whole bunch of packages to want to be rebuild. 

From personal experience due to the number of rebuilds that will be triggered this probably need to target the `staging` branch instead. :)

Other than they, I can also verify that at least the jcef parts works as a "review" :)

**Comment by mevatron** [comment]
@zlepper I was trying to test aarch64 builds since it references on of the sha hashes, but I don't have an aarch64 box to test from, so I was fixing cross-compiler errors as I ran into them. Unfortunately, gnome-vfs doesn't seem to support cross-compiling out of the box on our current recipes it seems, but I can certainly revert that line if it will be easier to get these fixes in.

**Comment by zlepper** [comment]
> @zlepper I was trying to test aarch64 builds since it references one of the sha hashes, but I don't have an aarch64 box to test from, so I was fixing cross-compiler errors as I ran into them. Unfortunately, gnome-vfs doesn't seem to support cross-compiling out of the box on our current recipes, but I can certainly revert that line if it will be easier to get these fixes in.

It will at least make it possible to get into the master branch from my knowledge, if it has to go through staging then it will take a while before it gets near master.

I don't have merge permissions or anything and have just tried to get into nix recently, so just giving my advice :D

**Comment by mevatron** [comment]
Oh, yeah no problem! Just trying to get my nx-console changes in and need a few of these PRs in, so if it speeds merging up that sounds better to me 😄

**Review by zlepper — APPROVED** [review]

**Comment by zlepper** [comment]
Result of `nixpkgs-review pr 309447` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>22 packages built:</summary>
  <ul>
    <li>jetbrains.clion</li>
    <li>jetbrains.datagrip</li>
    <li>jetbrains.dataspell</li>
    <li>jetbrains.gateway</li>
    <li>jetbrains.goland</li>
    <li>jetbrains.idea-community (jetbrains.idea-community-src)</li>
    <li>jetbrains.idea-community-bin</li>
    <li>jetbrains.idea-ultimate</li>
    <li>jetbrains.jcef</li>
    <li>jetbrains.jcef.unpacked</li>
    <li>jetbrains.jdk</li>
    <li>jetbrains.jdk.debug</li>
    <li>jetbrains.mps</li>
    <li>jetbrains.phpstorm</li>
    <li>jetbrains.pycharm-community (jetbrains.pycharm-community-src)</li>
    <li>jetbrains.pycharm-community-bin</li>
    <li>jetbrains.pycharm-professional</li>
    <li>jetbrains.rider</li>
    <li>jetbrains.ruby-mine</li>
    <li>jetbrains.rust-rover</li>
    <li>jetbrains.webstorm</li>
    <li>jetbrains.writerside</li>
  </ul>
</details>

**Pull request merged**
