### PR TITLE
syft: 0.75.0 -> 0.76.1

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>###### Description of changes

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by 06kellyjac — APPROVED** [review]

**Comment by 06kellyjac** [comment]
If you could amend the update commit to be single dash `->` thatd be ideal. Thanks

**Review by fabaff — COMMENTED** [review]
```bash
error: hash mismatch in fixed-output derivation '/nix/store/mqlmldla1sjimfv61qiypz1c7yn447di-syft-0.76.0-go-modules.drv':
         specified: sha256-le660nqfrqW1a79tlY4/UKqN06zHkUpAVPQhYPqNJLU=
            got:    sha256-1IbSC4lAYDsX5zZXqBdGBQktHISZ9xUorNeK/iP+Vrg=
```

**Comment by developer-guy** [comment]
> Using `nix-update` would take care of updating the hashes.

what should I do to find the correct hash? My method specifies an empty hash and does a `nix build` to give me the correct hash.

**Comment by developer-guy** [comment]
an alternative approach is using `lib.fakeSha256`

**Comment by bbigras** [comment]
0.76.1 is out btw

**Pull request merged**
