### PR TITLE
python312Packages.editdistpy: add tests

### PR DESCRIPTION
**Pull request by ViZiD**
## Description of changes
https://github.com/mammothb/editdistpy
add tests

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by risicle** [comment]
Is this fancy mechanism just to avoid a circular import in test-dependencies?

**Comment by ViZiD** [comment]
> Is this fancy mechanism just to avoid a circular import in test-dependencies?

Yes, something like that. I looked up how other packages solve this problem, like [uvicorn](https://github.com/NixOS/nixpkgs/blob/b06025f1533a1e07b6db3e75151caa155d1c7eb3/pkgs/development/python-modules/uvicorn/default.nix#L67C3-L67C11) and found the information in the [nix manuals](https://nixos.org/manual/nixpkgs/stable/#var-meta-tests)

**Comment by risicle** [comment]
Ok - an easier way to do it (and perhaps a less confusing way) is to simply have the package `doCheck = false` by default (which should have the effect of removing check-dependencies) and then self-referencing the package in `passthru.tests`, overriding (using `overridePythonAttrs` in this case) `doCheck` to `true`.

In non-python packages you can make it even more elegant by self-referencing using the `finalAttrs.finalPackage` trick, but in a python package you're stuck having to do a fixed-point trick. See `python3.pkgs.packaging` package for an example of this being done.

**Comment by ViZiD** [comment]
> Ok - an easier way to do it (and perhaps a less confusing way) is to simply have the package `doCheck = false` by default (which should have the effect of removing check-dependencies) and then self-referencing the package in `passthru.tests`, overriding (using `overridePythonAttrs` in this case) `doCheck` to `true`.
> 
> In non-python packages you can make it even more elegant by self-referencing using the `finalAttrs.finalPackage` trick, but in a python package you're stuck having to do a fixed-point trick. See `python3.pkgs.packaging` package for an example of this being done.

I tried this option but it doesn't work, the symspellpy package crashes with an error because it depends on editdistpy. 
`passthru.tests = {
    check = editdistpy.overridePythonAttrs (_: { doCheck = true; });
  };`

**Comment by natsukium** [comment]
Try this. It works for me.

```diff
diff --git a/pkgs/development/python-modules/editdistpy/default.nix b/pkgs/development/python-modules/editdistpy/default.nix
index 5c86f3773bff..b8a98b17e320 100644
--- a/pkgs/development/python-modules/editdistpy/default.nix
+++ b/pkgs/development/python-modules/editdistpy/default.nix
@@ -6,6 +6,10 @@
 
 , setuptools
 , cython_3
+, editdistpy
+, numpy
+, pytestCheckHook
+, symspellpy
 }:
 
 buildPythonPackage rec {
@@ -30,6 +34,24 @@ buildPythonPackage rec {
   # for tests need symspellpy package, symspellpy is not in nixpkgs...
   doCheck = false;
 

+  nativeCheckInputs = [
+    pytestCheckHook
+    symspellpy
+    numpy
+  ];
+
+  preCheck = ''
+    rm -r editdistpy
+  '';
+
+  passthru.tests = {
+    pytest = editdistpy.overridePythonAttrs (
+      _: {
+        doCheck = true;
+      }
+    );
+  };
+
   pythonImportsCheck = [
     "editdistpy"
   ];

```

**Comment by ViZiD** [comment]
@natsukium  it work, thanks ❤️

**Review by natsukium — APPROVED** [review]
looks fine to me

**Pull request merged**
