### PR TITLE
add armv7l-linux to mesaPlatforms

### PR DESCRIPTION
**Pull request by ghost**
Could somebody merge this please?

### CODE REVIEW

**Comment by dezgeg** [comment]
Does this actually make mesa work? Last time I checked, either mesa or libdrm failed to compile due to the Intel i915 driver getting enabled somehow.

**Comment by vcunat** [comment]
BTW, I always wondered why we have `lib.platforms.mesaPlatforms` instead of standard `mesa.meta.platforms`, in case some of you know...

**Comment by tohl** [comment]
@dezgeg You are right.  I added a fix for this now.

**Comment by tohl** [comment]
@vcunat I have no idea, but funny enough, mesa.meta.platforms is defined
as

platforms = stdenv.lib.platforms.mesaPlatforms;

**Comment by tohl** [comment]
Hmm, still not correct.

**Comment by tohl** [comment]
ok, this one compiles now:-)

**Comment by tohl** [comment]
@dezgeg @vcunat It works now (tested before rebasing, because by the
time it would compile on arm again, it would need rebasing again).

I have now hydra (which depends on mesa via libdevil indirect
dependency) working on raspberry pi 2, see http://rlszasz6dlv5cxrr.onion
for example.

xwindows also compiled without problems with xfce.  DisplayManager does
not start, see bellow.  However, that is a different issue and I think
that there is nothing preventing mesa on allow armv7l-linux.

gdm does not compile due to issue with downloading jam.  The tarball is
not anymore in the specified location and I noticed, that on
x86_64-linux, nix somehow looks at tarballs.nixos.org instead.  It is
not clear to me, why this does not work on arm the same way.

Could somebody merge this please?

---

Here the display manager module log:

$ systemctl status display-manager -l
● display-manager.service - X11 Server
   Loaded: loaded (/nix/store/vg22pz3g3w67bjyxa0q3g3m4h5b6n5xz-unit-display-manager.service/display-manager.service; bad; vendor preset: enabled)
   Active: failed (Result: start-limit) since Sun 2016-02-14 23:04:53 CET; 47min ago
  Process: 11177 ExecStart=/nix/store/f9cwxjznmsabp089786z8cpj6gl5x0bm-unit-script/bin/display-manager-start (code=exited, status=1/FAILURE)
  Process: 11172 ExecStartPre=/nix/store/lswqvhnaddn8yhs2pbv7j6kvjwhl375y-unit-script/bin/display-manager-pre-start (code=exited, status=0/SUCCESS)
 Main PID: 11177 (code=exited, status=1/FAILURE)

Feb 14 23:04:52 r1 systemd[1]: display-manager.service: Failed with result 'exit-code'.
Feb 14 23:04:53 r1 systemd[1]: display-manager.service: Service hold-off time over, scheduling restart.
Feb 14 23:04:53 r1 systemd[1]: Stopped X11 Server.
Feb 14 23:04:53 r1 systemd[1]: display-manager.service: Start request repeated too quickly.
Feb 14 23:04:53 r1 systemd[1]: Failed to start X11 Server.
Feb 14 23:04:53 r1 systemd[1]: display-manager.service: Unit entered failed state.
Feb 14 23:04:53 r1 systemd[1]: display-manager.service: Failed with result 'start-limit'.

**Pull request merged**
