### PR TITLE
Abiword 3.0.2

### PR DESCRIPTION
**Pull request by armijnhemel**
###### Motivation for this change

new version, also needs a patch to build properly. Tested on Fedora 25. On my machine the main Abiword screen flickers like crazy though.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by edolstra** [comment]
Wouldn't something like `NIX_CFLAGS_COMPILE = "-std=c++11"` also work? If they're using `nullptr`, then we should be compiling in C++11 mode...

**Comment by edolstra** [comment]
Did you mean that the flickering occurs in the old or new version?

**Comment by armijnhemel** [comment]
Flickering is in the new version, making it unusable (did not test with the old version). This, however, might have something to do with DRI or something. There are more packages that seem to work fine on NixOS, but not on Fedora when using Nix.

**Comment by armijnhemel** [comment]
will try using the cflags and report back.

**Comment by armijnhemel** [comment]
NIX_CFLAGS_COMPILE seems to work just fine.

**Comment by armijnhemel** [comment]
Any news?

**Comment by pSub** [comment]
I wanted to update abiword for a long time. However the flickering is a deal breaker for me. It does not occur with the old version. I'm guessing this problem is due to an interplay of abiword and gtk. However I currently don't have the time to really look into this.

By the way, we are not the only distro having this problem: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851052

**Comment by jtojnar** [comment]
The working area has been turning black or flickering for a long time for me. I think I first noticed it on 3.0 back when I was still running Arch. I can definitely see it on NixOS with 3.0.1.

**Comment by jtojnar** [comment]
Fixed in #31194

**Pull request closed without merging**
