### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by hedning** [comment]
#71289 fixes `glib` on darwin if we can't find any better solution.

**Comment by worldofpeace** [comment]
Issue apperars to be
```
Traceback (most recent call last):
  File "/nix/store/j7frdsf219fbdg383fhrifg1gw7p3hgd-meson-0.51.2/bin/meson", line 11, in <module>
    sys.exit(main())
  File "/nix/store/j7frdsf219fbdg383fhrifg1gw7p3hgd-meson-0.51.2/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 224, in main
    return run(sys.argv[1:], launcher)
  File "/nix/store/j7frdsf219fbdg383fhrifg1gw7p3hgd-meson-0.51.2/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 213, in run
    return run_script_command(args[1], args[2:])
  File "/nix/store/j7frdsf219fbdg383fhrifg1gw7p3hgd-meson-0.51.2/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 161, in run_script_command
    return module.run(script_args)
  File "/nix/store/j7frdsf219fbdg383fhrifg1gw7p3hgd-meson-0.51.2/lib/python3.7/site-packages/mesonbuild/scripts/gtkdochelper.py", line 259, in run
    options.mode)
  File "/nix/store/j7frdsf219fbdg383fhrifg1gw7p3hgd-meson-0.51.2/lib/python3.7/site-packages/mesonbuild/scripts/gtkdochelper.py", line 130, in build_gtkdoc
    gtkdoc_run_check(scan_cmd, abs_out)
  File "/nix/store/j7frdsf219fbdg383fhrifg1gw7p3hgd-meson-0.51.2/lib/python3.7/site-packages/mesonbuild/scripts/gtkdochelper.py", line 67, in gtkdoc_run_check
    p, out = Popen_safe(cmd, cwd=cwd, env=env, stderr=subprocess.STDOUT)[0:2]
  File "/nix/store/j7frdsf219fbdg383fhrifg1gw7p3hgd-meson-0.51.2/lib/python3.7/site-packages/mesonbuild/mesonlib.py", line 967, in Popen_safe
    stdout=stdout, stderr=stderr, **kwargs)
  File "/nix/store/lqg58f3cnjrgwdhr70hwcf6b555iqnsf-python3-3.7.5/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/nix/store/lqg58f3cnjrgwdhr70hwcf6b555iqnsf-python3-3.7.5/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'gtkdoc-scan'
```

likely latest gtk-doc broke something for darwin.
Should probably report this, it seems gtk-doc releases lately have regressions.
Looks like they need help anyway so I try to get them in.

I'll look into it.

**Comment by worldofpeace** [comment]
So there's a distinct difference in the shebangs on darwin after the update

###### Before
```
#!/nix/store/gaascisqfmxckzhvs5q1wbx6ycsbk4fi-python3-3.7.4/bin/python3.7
```

##### After
```
#!/nix/store/p2jiplya6d80vnr7kpj3dmfn9d06qysm-python3-3.7.5-env/bin/python3
```

I overlooked that python.withPackages creates a wrapper and scripts are not allowed in shebangs.
That's why the package links into sys.path. Interesting that it's only an issue for darwin though.

I believe if I satiate 
* https://gitlab.gnome.org/GNOME/gtk-doc/blob/GTK_DOC_1_32/meson.build#L42 

in any other way the issue will be fixed :+1: 

(pr incoming once I test on darwin)

**Comment by FRidh** [comment]
@hedning gtk3 keeps timing out causing the majority of newly failing builds

**Comment by hedning** [comment]
> @hedning gtk3 keeps timing out causing the majority of newly failing builds

Bisected it to libsass ugrade: e4b4ff8099685dea7e82ae6ccd3899337a121632. Pretty sure it's this https://github.com/sass/libsass/issues/3006, as the timed out logs doesn't contain `Generating Adwaita with a custom command`, while good builds do. I guess there's two options:
- revert `libsass` upgrade
- temporarily disable custom genaration of themes in `gtk3` (they're shipped in the tarball by default)

**Comment by jonringer** [comment]
@hedning i see your request :)

**Comment by hedning** [comment]
> @hedning i see your request :)

My bad, no idea how that happened :)

**Review by veprbl — DISMISSED** [review]
poppler bump breaks poppler (trivially) and texlive.bin.core (non-trivially)

I had some progress with fixing texlive by applying
https://git.archlinux.org/svntogit/packages.git/plain/texlive-bin/trunk/pdftex-poppler0.76.patch?id=8cb784073cfd2299a6c301ce7bb0d89126a47f4e
But then I'm stuck at a luatex build failure that archlinux doesn't address.

**Comment by FRidh** [comment]
@veprbl perhaps revert poppler bump for now?

**Comment by ttuegel** [comment]
> perhaps revert poppler bump for now?

The poppler bump fixes a security issue, so if you decide to keep this reverted then please open a new issue.

**Pull request merged**
