### PR TITLE
ffmpeg: merge with ffmpeg-full

### LINKED ISSUE #15930: ffmpeg has two different implementations
While patching some functionality into mpv I noticed that there are two completely separate ffmpeg derivations, which both do basically the same thing, but `ffmpeg-full` enables more options.

What’s the reasoning behind splitting them, instead of creating a generic derivation with all options turned of by default and `ffmpeg-full` calling it with most options set to `true`, as most other packages do it? @codyopel

### PR DESCRIPTION
**Pull request by Atemu**
###### Description of changes

Fixes https://github.com/NixOS/nixpkgs/issues/15930

Continuation of https://github.com/NixOS/nixpkgs/pull/204198

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by linsui** [comment]
Please also remove ffmpeg_5 from pkgs/applications/networking/instant-messengers/jami/default.nix and all-packages.nix.

**Comment by trofi** [comment]
> Waiting on @trofi to merge master into staging since master contains a jami change that would conflict.

After manual resolution merges should succeed now: https://github.com/NixOS/nixpkgs/actions/runs/3973535483

**Comment by wegank** [comment]
@ofborg build ffmpeg ffmpeg.passthru.tests handbrake handbrake.passthru.tests

**Review by SuperSandro2000 — APPROVED** [review]
didn't check every line by line again but it looked good in the other PR already

**Review by mweinelt — APPROVED** [review]

**Comment by mweinelt** [comment]
Let's give this a try. And please be around to fix issues during the next staging cycle!

**Comment by Atemu** [comment]
Thanks!

**Comment by vcunat** [comment]
This apparently dropped libavresample and some packages are now missing it, e.g. https://hydra.nixos.org/build/207981481

**Comment by Atemu** [comment]
@vcunat libavresample is deprecated and has already been removed in ffmpeg_5 IIRC.

Should we mark the packages as broken?

**Comment by Atemu** [comment]
tvheadend doesn't actually need it anymore: https://github.com/tvheadend/tvheadend/commit/17a357fee8bccacd931476411200b05f2b06f47c

**Comment by vcunat** [comment]
tvheadend: maybe if we built from master instead of latest release.  A quite complex patch is also needed: https://github.com/tvheadend/tvheadend/commit/014bb9505e1d7eb6e37e10931dd89ab3b1a0dc01#diff-8b66bba512ec526b2701a5764adac0f55f955801a0089943ced3c76fcdf65088

(We still default to `ffmpeg_4`.)

**Comment by Ericson2314** [comment]
Congrats!!

**Comment by rnhmjoj** [comment]
I'm not sure how, but this change broke the reproduction of video4linux2 streams in mpv.
If you have a webcam you simply confirm this by `mpv /dev/video0`. I'd like to get this back because it's very useful.

**Comment by mweinelt** [comment]
V4L2 support is only in the full build right now.

**Comment by SuperSandro2000** [comment]
quoting the comments from this PR:

```
  # Build with headless deps; excludes dependencies that are only necessary for
  # GUI applications. To be used for purposes that don't generally need such
  # components and i.e. only depend on libav
, withHeadlessDeps ? ffmpegVariant == "headless" || withSmallDeps

  # Dependencies a user might customarily expect from a regular ffmpeg build.
  # /All/ packages that depend on ffmpeg and some of its feaures should depend
  # on the small variant. Small means the minimal set of features that satisfies
  # all dependants in Nixpkgs
, withSmallDeps ? ffmpegVariant == "small" || withFullDeps

  # Everything enabled; only guarded behind platform exclusivity or brokeness.
  # If you need to depend on ffmpeg-full because ffmpeg is missing some feature
  # your package needs, you should enable that feature in regular ffmpeg
  # instead.
, withFullDeps ? ffmpegVariant == "full"
```

**Pull request merged**
