### PR TITLE
python311Packages.gradio-client: 0.14.0 -> 0.16.1, python311Packages.gradio: 4.27.0 -> 4.29.0

### LINKED ISSUE #310761: Build failure: Gradio / Gradio Client
### Steps To Reproduce

1. build *Gradio / Gradio Client*

### Build log

```
==================================== ERRORS ====================================
_____________________ ERROR collecting test/test_client.py _____________________
ImportError while importing test module '/build/source/client/python/test/test_client.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/nix/store/k3701zl6gmx3la7y4dnflcvf3xfy88kh-python3-3.11.9/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/test_client.py:19: in <module>
    from gradio.networking import Server
E   ImportError: cannot import name 'Server' from 'gradio.networking' (/nix/store/jn91mahr5i81lgq3kx8mnh9qk0fvjqfs-python3.11-gradio-sans-reverse-dependencies-4.27.0/lib/python3.11/site-packages/gradio/networking.py)
```

### Additional context

https://hydra.nixos.org/build/259083479

### Notify maintainers

@pbsds 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.146.1-microsoft-standard-WSL2, NixOS, 24.05 (Uakari), 24.05.20240509.f1010e0`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.22.0`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

gradio-client is currently broken on `master`.
Note: this patch is not working yet.

fixes #310761

Changelogs:
- https://github.com/gradio-app/gradio/releases/tag/gradio_client%400.16.1
- https://github.com/gradio-app/gradio/releases/tag/gradio%404.29.0

cc @pbsds @drupol 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by drupol** [comment]
@GaetanLepage Is it ready to be merged?

**Comment by GaetanLepage** [comment]
> @GaetanLepage Is it ready to be merged? I see this is broken on some archs, can we fix this?

No it's still broken. I have to go through the logs.

**Comment by drupol** [comment]
OK I'll wait then, I need this in https://github.com/NixOS/nixpkgs/pull/305586

**Comment by pbsds** [comment]
Neat! I have nearly the same diff sitting in a local branch which fixes gradio on py311, but py312 is broken due to two issues in diffusers. The following diff fixes the first issue, but diffusers still fail to build due to test failures. Upstream communicates that the tests should be temporarily disabled now, but i've yet to go hunt down the commits to cherrypick. 

```patch
diff --git a/pkgs/development/python-modules/diffusers/default.nix b/pkgs/development/python-modules/diffusers/default.nix
index 39464efe47fd..8b555462c21b 100644
--- a/pkgs/development/python-modules/diffusers/default.nix
+++ b/pkgs/development/python-modules/diffusers/default.nix
@@ -2,6 +2,7 @@
 , stdenv
 , buildPythonPackage
 , fetchFromGitHub
+, fetchpatch
 , pythonOlder
 , writeText
 , setuptools
@@ -51,6 +52,20 @@ buildPythonPackage rec {
     hash = "sha256-aRnbU3jN40xaCsoMFyRt1XB+hyIYMJP2b/T1yZho90c=";
   };
 
+  patches = [
+    # fix python3.12 build
+    (fetchpatch { # https://github.com/huggingface/diffusers/pull/7455
+      name = "001-remove-distutils.patch";
+      url = "https://github.com/huggingface/diffusers/compare/363699044e365ef977a7646b500402fa585e1b6b...3c67864c5acb30413911730b1ed4a9ad47c0a15c.patch";
+      hash = "sha256-Qyvyp1GyTVXN+A+lA1r2hf887ubTtaUknbKd4r46NZQ=";
+    })
+    (fetchpatch { # https://github.com/huggingface/diffusers/pull/7461
+      name = "002-fix-removed-distutils.patch";
+      url = "https://github.com/huggingface/diffusers/commit/efbbbc38e436a1abb1df41a6eccfd6f9f0333f97.patch";
+      hash = "sha256-scdtpX1RYFFEDHcaMb+gDZSsPafkvnIO/wQlpzrQhLA=";
+    })
+  ];
+
   nativeBuildInputs = [
     setuptools
     wheel
```

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 310295` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>python312Packages.gradio</li>
    <li>python312Packages.gradio-client</li>
    <li>python312Packages.gradio-client.dist</li>
    <li>python312Packages.gradio-pdf</li>
    <li>python312Packages.gradio-pdf.dist</li>
    <li>python312Packages.gradio.dist</li>
  </ul>
</details>
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>python311Packages.gradio</li>
    <li>python311Packages.gradio-client</li>
    <li>python311Packages.gradio-client.dist</li>
    <li>python311Packages.gradio-pdf</li>
    <li>python311Packages.gradio-pdf.dist</li>
    <li>python311Packages.gradio.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 310295` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>python311Packages.gradio</li>
    <li>python311Packages.gradio-client</li>
    <li>python311Packages.gradio-client.dist</li>
    <li>python311Packages.gradio-pdf</li>
    <li>python311Packages.gradio-pdf.dist</li>
    <li>python311Packages.gradio.dist</li>
    <li>python312Packages.gradio</li>
    <li>python312Packages.gradio-client</li>
    <li>python312Packages.gradio-client.dist</li>
    <li>python312Packages.gradio-pdf</li>
    <li>python312Packages.gradio-pdf.dist</li>
    <li>python312Packages.gradio.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 310295` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>python311Packages.gradio</li>
    <li>python311Packages.gradio-client</li>
    <li>python311Packages.gradio-client.dist</li>
    <li>python311Packages.gradio-pdf</li>
    <li>python311Packages.gradio-pdf.dist</li>
    <li>python311Packages.gradio.dist</li>
    <li>python312Packages.gradio</li>
    <li>python312Packages.gradio-client</li>
    <li>python312Packages.gradio-client.dist</li>
    <li>python312Packages.gradio-pdf</li>
    <li>python312Packages.gradio-pdf.dist</li>
    <li>python312Packages.gradio.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 310295` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>python311Packages.gradio</li>
    <li>python311Packages.gradio-client</li>
    <li>python311Packages.gradio-client.dist</li>
    <li>python311Packages.gradio-pdf</li>
    <li>python311Packages.gradio-pdf.dist</li>
    <li>python311Packages.gradio.dist</li>
    <li>python312Packages.gradio</li>
    <li>python312Packages.gradio-client</li>
    <li>python312Packages.gradio-client.dist</li>
    <li>python312Packages.gradio-pdf</li>
    <li>python312Packages.gradio-pdf.dist</li>
    <li>python312Packages.gradio.dist</li>
  </ul>
</details>

**Comment by pbsds** [comment]
the diffusers commit is bogging down ofborg with timeouts. It's not complete anyway, so lets pop it off and merge the bumps

**Comment by GaetanLepage** [comment]
Thanks for your patch @pbsds.
Unfortunately, some tests still fail:
```
=========================== short test summary info ============================
FAILED tests/models/autoencoders/test_models_vae.py::AutoncoderKLTemporalDecoderFastTests::test_from_save_pretrained_dynamo - AssertionError: Traceback (most recent call last):
FAILED tests/models/transformers/test_models_prior.py::PriorTransformerTests::test_from_save_pretrained_dynamo - AssertionError: Traceback (most recent call last):
FAILED tests/models/autoencoders/test_models_vae.py::AsymmetricAutoencoderKLTests::test_from_save_pretrained_dynamo - AssertionError: Traceback (most recent call last):
FAILED tests/models/unets/test_models_unet_1d.py::UNet1DModelTests::test_from_save_pretrained_dynamo - AssertionError: Traceback (most recent call last):
FAILED tests/models/autoencoders/test_models_vae.py::AutoencoderKLTests::test_from_save_pretrained_dynamo - AssertionError: Traceback (most recent call last):
FAILED tests/models/autoencoders/test_models_vq.py::VQModelTests::test_from_save_pretrained_dynamo - AssertionError: Traceback (most recent call last):
FAILED tests/models/autoencoders/test_models_vae.py::ConsistencyDecoderVAETests::test_from_save_pretrained_dynamo - AssertionError: Traceback (most recent call last):
FAILED tests/models/unets/test_models_unet_1d.py::UNetRLModelTests::test_from_save_pretrained_dynamo - AssertionError: Traceback (most recent call last):
FAILED tests/models/unets/test_models_unet_2d.py::UNetLDMModelTests::test_from_save_pretrained_dynamo - AssertionError: Traceback (most recent call last):
FAILED tests/models/autoencoders/test_models_vae.py::AutoencoderTinyTests::test_from_save_pretrained_dynamo - AssertionError: Traceback (most recent call last):
FAILED tests/models/unets/test_models_unet_2d.py::NCSNppModelTests::test_from_save_pretrained_dynamo - AssertionError: Traceback (most recent call last):
FAILED tests/models/unets/test_models_unet_2d.py::Unet2DModelTests::test_from_save_pretrained_dynamo - AssertionError: Traceback (most recent call last):
FAILED tests/models/unets/test_models_unet_2d_condition.py::UNet2DConditionModelTests::test_from_save_pretrained_dynamo - AssertionError: Traceback (most recent call last):
FAILED tests/models/unets/test_models_unet_spatiotemporal.py::UNetSpatioTemporalConditionModelTests::test_from_save_pretrained_dynamo - AssertionError: Traceback (most recent call l>
FAILED tests/models/unets/test_models_unet_motion.py::UNetMotionModelTests::test_from_save_pretrained_dynamo - AssertionError: Traceback (most recent call last):
FAILED tests/models/unets/test_models_unet_3d_condition.py::UNet3DConditionModelTests::test_from_save_pretrained_dynamo - AssertionError: Traceback (most recent call last):
= 16 failed, 1825 passed, 1249 skipped, 1673 xfailed, 1917 warnings in 5137.49s (1:25:37) =
```

**Comment by GaetanLepage** [comment]
Basically, it boils down to: `RuntimeError: Dynamo is not supported on Python 3.12+`.
Should we just disable those tests conditionally on 3.12 ?

**Comment by pbsds** [comment]
They fail in `diffusers` right? The fix is in a commit i've yet to hunt down. The problem lies in pytorch according to the diffusers maintainers.

**Comment by GaetanLepage** [comment]
> They fail in `diffusers` right? The fix is in a commit i've yet to hunt down. The problem lies in pytorch according to the diffusers maintainers.

I skipped the dymano test on python 3.12.
It should now build fine. I am running `nixpkgs-review`.

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 310295` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>python311Packages.diffusers</li>
    <li>python311Packages.diffusers.dist</li>
    <li>python311Packages.gradio</li>
    <li>python311Packages.gradio-client</li>
    <li>python311Packages.gradio-client.dist</li>
    <li>python311Packages.gradio-pdf</li>
    <li>python311Packages.gradio-pdf.dist</li>
    <li>python311Packages.gradio.dist</li>
    <li>python312Packages.diffusers</li>
    <li>python312Packages.diffusers.dist</li>
    <li>python312Packages.gradio</li>
    <li>python312Packages.gradio-client</li>
    <li>python312Packages.gradio-client.dist</li>
    <li>python312Packages.gradio-pdf</li>
    <li>python312Packages.gradio-pdf.dist</li>
    <li>python312Packages.gradio.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 310295` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages failed to build:</summary>
  <ul>
    <li>python311Packages.diffusers</li>
    <li>python311Packages.diffusers.dist</li>
    <li>python311Packages.gradio</li>
    <li>python311Packages.gradio-client</li>
    <li>python311Packages.gradio-client.dist</li>
    <li>python311Packages.gradio-pdf</li>
    <li>python311Packages.gradio-pdf.dist</li>
    <li>python311Packages.gradio.dist</li>
    <li>python312Packages.gradio</li>
    <li>python312Packages.gradio.dist</li>
  </ul>
</details>
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>python312Packages.diffusers</li>
    <li>python312Packages.diffusers.dist</li>
    <li>python312Packages.gradio-client</li>
    <li>python312Packages.gradio-client.dist</li>
    <li>python312Packages.gradio-pdf</li>
    <li>python312Packages.gradio-pdf.dist</li>
  </ul>
</details>

**Pull request merged**
