### PR TITLE
zeroad: Split data from binaries again

### PR DESCRIPTION
**Pull request by chvp**
###### Motivation for this change

The rootdir patch was lost in the update to 0.0.24. Adding it allows hydra to build the game (which takes a few minutes). It can't when the binaries depend on the data since the data is too big for hydra.

ZHF: #122042
CC @NixOS/nixos-release-managers

###### Things done

I started a game using this build.

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mindavi** [comment]
Great. It's nice if hydra can build it for us. Also good to see that you're willing to maintain the package.

Haven't tried this yet, might try later. Overall the idea is good and I like it.

**Comment by chvp** [comment]
> Great. It's nice if hydra can build it for us. Also good to see that you're willing to maintain the package.

I'm playing it weekly with a group of friends, it's the least I could do. :smile:

> Haven't tried this yet, might try later. Overall the idea is good and I like it.

Note that this is not a new idea (although I only realized this after I fixed it). This also how it was made sure that it was built on hydra before 0.0.24. (See https://github.com/NixOS/nixpkgs/blob/7f21b53fc075755d34a16ec7a352389578a3de50/pkgs/games/0ad/rootdir_env.patch and https://github.com/NixOS/nixpkgs/blob/7f21b53fc075755d34a16ec7a352389578a3de50/pkgs/games/0ad/game.nix.)

**Comment by Mindavi** [comment]
Yes indeed. I remember seeing that. Not sure why it was changed, I missed that. I also play this sometimes with friends, but not weekly :).

**Comment by chvp** [comment]
I've been using this patch for three weeks now, without issues.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 119643 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>1 package built:</summary>  <ul>    <li>zeroad</li>  </ul></details>

**Pull request merged**
