### PR TITLE
syncthing service: add syncthing-inotify

### PR DESCRIPTION
**Pull request by jokogr**
###### Motivation for this change

Syncthing is not using any OS primitives to detect changes as soon as they happen unless syncthing-inotify is used.

This PR adds syncthing-inotify to packages and creates a system service if `services.syncthing.enableINotify` is set to `true`.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by rnhmjoj** [comment]
Can the inotify handle multiple instances? If so it could be enabled for every user service.

**Comment by peterhoeg** [comment]
syncthing-inotify can also be run as a user service, so you need something like this:

```
systemd.user.services =  {
  syncthing-inotify = {
    description = "Monitor Syncthing using inotify";
    after = [ "syncthing.service" ];
    requires = [ "syncthing.service" ];
    serviceConfig = {
      ExecStart = "${lib.getBin pkgs.syncthing-inotify}/bin/syncthing-inotify -logflags=0";
      Restart = "on-failure";
      ProtectSystem = "full";
      ProtectHome = "read-only";
    };
  };
};
```

The above is missing the handling of the ```useInotify``` flag.

**Comment by jokogr** [comment]
@rnhmjoj @peterhoeg Thanks for your comments!

I have renamed the option to `useInotify` as @peterhoeg suggested.

I have pushed a new commit which enables syncthing-inotify as a user service, as well. The tricky part there has been the dependency with syncthing: Because the system service had the same name as the user service, I had some issues which I have solved by appending an "@" to the system services (both syncthing and syncthing-inotify).

I can personally verify the system services are properly working.
@rnhmjoj could you please verify syncthing-inotify works as a user service?


Many thanks in advance!

**Comment by peterhoeg** [comment]
@jokogr there are basically 3 modes in which you will run syncthing and syncthing-inotify (and a lot of other software for that matter) under systemd but below I'm using just syncthing as an example (it's faster to type than syncthing-inotify):


1) system wide - single instance

Controlled by lib/systemd/system/syncthing.service where the service file has User=syncthing and Group=syncthing


2) system wide - multiple instances

Controlled by lib/systemd/system/syncthing@.service where the service file has User=%i and Group=%i


3) user mode - single instance

Controlled by lib/systemd/user/syncthing.service where the service file has no mention of User/Group as it will automatically run as the current user.


As you can see, there is no overlap between the files. There is similarly no overlap in the systemd service definitions in nix:

```
systemd = {
  services = {
    syncthing = {
      blablabla
    }
    "syncthing@" = {
      blablabla
    }
  };
  user.services = {
    syncthing = {
      blablabla
    };
  };
};
```

So those are the permutations that you need to cover. Hope that clarifies.

**Comment by jokogr** [comment]
@peterhoeg I see. Could you please check my latest commit then and let me know what you think of?

**Comment by rnhmjoj** [comment]
I quickly tested it in a vm and seems to work: the user services `syncthing.service`, `syncthing-inotify.service` along with the system-wide versions run as `syncthing@multi-user.service` and `syncthing-inotify@multi-user.service` run fine. I also tested that inotify correctly picks up the changes in `Sync`.
However I don't understand the point of the `@.service`: there should be no conflict with the user service, they are completely separated. The symbol is intended to pass arguments to the service (like the user name) when you enable imperatively the service with `systemctl enable service@foo` but this is impossible on NixOs, or is it?. It can be used to run multiple "system-wide" but it's essentially the same thing as enabling the user services, right?

**Comment by rnhmjoj** [comment]
[This](https://gist.github.com/anonymous/e1e8a5b8e5f090a2f37bcb0676f45c47) would be my take.

**Comment by peterhoeg** [comment]
@rnhmjoj :  

```
    environment.systemPackages =
      [ cfg.package ]
++ optional cfg.useInotify pkgs.syncthing-inotify;
```
You don't need to add it to systemPackages. It gets installed via the service.

```
wantedBy = [ "default.target" ];
```

This way syncthing is started by default for all users, which is probably not what you want. Without the wantedBy, the user would be responsible for linking it himself via ```.config/systemd/user/default.target.wants``` which is nicer.

**Comment by rnhmjoj** [comment]
@peterhoeg Thanks about the `default.target.wants`: I didn't realise `wantedBy = default.target` was forcing it on on every users.

**Comment by peterhoeg** [comment]
FYI, this is not my decision, but this is what I would do:

Split this PR into 2:

1. the package definition for syncthing-inotify (so we can get it upstream while we sort out the nixos module issue)
2. the nixos service module.

My personal preference is for @rnhmjoj's nixos module - it's cleaner.

Secondly, upstream syncthing and syncthing-inotify both carry their own systemd service files, so instead of manually defining all the services here, we should instead use those like this:
```
config.systemd.packages = [ cfg.package ];
```
For reference, have a look here: https://github.com/peterhoeg/nixpkgs/blob/iio/nixos/modules/hardware/sensor/iio.nix

This way we only have to override a few parts of the service definitions and can simply piggyback on any work that happens upstream.

**Comment by jokogr** [comment]
@peterhoeg I have created a new PR with just syncthing-inotify.
@rnhmjoj I have pushed in this PR your latest version of syncthing.nix I prefer it, too.

I have both syncthing and syncthing-inotify system services running properly on my system. Since we all agree, I propose to merge this PR, until @peterhoeg comes up with a more advanced one.

**Comment by rnhmjoj** [comment]
Can we merge this?

**Pull request merged**
