### PR TITLE
nixos/udev: enable initrd-udevadm-cleanup-db.service in systemd stage 1

### LINKED ISSUE #178345: systemd initrd doesn't restore backlight levels
With `boot.initrd.systemd.enable = true;`, my screen's brightness is reset to 100% on reboot. `systemd-backlight@leds:tpacpi::kbd_backlight.service` starts up but `systemd-backlight@backlight:amdgpu_bl0.service` doesn't. Not sure how to debug this. I'm on a thinkpad T14s.

**Clarification**: the issue is not that the brightness level is 100% in the initrd, but that it *stays* 100% after booting. In other words `systemd-backlight` *never* starts.

### PR DESCRIPTION
**Pull request by NickCao**
###### Description of changes
Fixes https://github.com/NixOS/nixpkgs/issues/178345

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ncfavier — APPROVED** [review]
Fixes the issue for me, thanks!

**Review by K900 — APPROVED** [review]
LGTM.

**Comment by ElvishJerricco** [comment]
@NickCao have you confirmed this doesn't break LUKS? I believe that's the reason we had to disable that previously; it was causing LUKS devices to disappear between stage 1 and stage 2. In particular, this affects file systems that *aren't* mounted in stage 1, but *are* LUKS devices decrypted in stage 1.

**Comment by NickCao** [comment]
The upstream issue is fixed and shipped, not sure about the luks part, is there a nixos test for that? (I'm a bit occupied these days and cannot test it myself)

**Comment by ElvishJerricco** [comment]
@NickCao Ok, the issue that *I* remember having still persists. I thought that systemd issue was related to it, but I suppose it wasn't if they think that systemd issue is fixed.

Essentially, if you define a LUKS device with `boot.initrd.luks.devices`, but you don't have any stage 1 file systems on it, then enabling this service in stage 1 will cause udev to remove its `SYSTEMD_READY` tag, and it won't get picked up again in stage 2. The result is that the file system being mounted in stage 2 cannot find the device and fails.

**Review by ElvishJerricco — CHANGES_REQUESTED** [review]
So we have to find a way to avoid LUKS devices of that nature being broken before we can enable this.

**Comment by ElvishJerricco** [comment]
@dasJ Do you remember what specific issue you ran up against with this service? IIRC it was different than mine.

**Comment by dasJ** [comment]
LVM devices on cryptsetup utterly broken and udev not finding them iirc

**Comment by NickCao** [comment]
Despite still not knowing how to fix the LUKS issue, I've make a nixos test to reproduce it: https://gist.github.com/NickCao/4fa2f532a3ec71ba9a8ff9e3ef9ef1e4

**Comment by NickCao** [comment]
I've found the fix to the problem: https://git.kernel.org/pub/scm/boot/dracut/dracut.git/tree/modules.d/90dm/11-dm.rules
dracut has been shipping this custom udev rule marking dm devices as `db_persist`, so that they survives the db cleanup.

**Review by K900 — APPROVED** [review]
Still LGTM, but I don't have a setup to actually test this on.

**Comment by NickCao** [comment]
@ElvishJerricco  @dasJ are you two still interested in this?

**Comment by ElvishJerricco** [comment]
Do we have a nixos test that covers this?

**Comment by NickCao** [comment]
> Despite still not knowing how to fix the LUKS issue, I've make a nixos test to reproduce it: https://gist.github.com/NickCao/4fa2f532a3ec71ba9a8ff9e3ef9ef1e4

I could adapt this to a nixos test if wanted.

**Comment by ElvishJerricco** [comment]
That would be good to have, yea.

**Comment by ElvishJerricco** [comment]
@ofborg test systemd-initrd-luks-password

**Comment by NickCao** [comment]
The failure on aarch64 seems unrelated?

**Comment by ElvishJerricco** [comment]
Yea, looks like it's had the same failure on hydra for a while now.

**Review by ElvishJerricco — APPROVED** [review]
LGTM

**Comment by ElvishJerricco** [comment]
@ofborg test installer.luksroot

Just want to run this to make sure that udev rule isn't negatively messing with the regular initrd.

**Pull request merged**
