### PR TITLE
nushell: init at 0.5.0

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change
Add https://github.com/nushell/nushell

supersedes and closes https://github.com/NixOS/nixpkgs/pull/68279

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @evanjs @teto I think you were interested in this package

### CODE REVIEW

**Comment by evanjs** [comment]
Sweet! Figured we’d have to skip most if not all of the tests. 
If only we could set the home directory for the duration of the checkPhase, I think?

**Comment by marsam** [comment]
>If only we could set the home directory for the duration of the checkPhase, I think?
Thanks for the hint. I've added it as `preCheck` phase and the tests pass

**Comment by evanjs** [comment]
> > If only we could set the home directory for the duration of the checkPhase, I think?
> 
> Thanks for the hint. I've added it as `preCheck` phase and the tests pass

Wow. That’s _all_ it took?!?
Duly noted. Thanks!

**Comment by evanjs** [comment]
Tested on `NixOS 19.09` and` macOS 10.13.6`.
Seems to compile and work fine.

Thanks again!

**Comment by evanjs** [comment]
I do wonder if we should allow feature flags to be passed through, though.
If enabled, pass through `--all-features` with necessary dependencies, or something like that? :man_shrugging: 
https://github.com/nushell/nushell#local

**Comment by evanjs** [comment]
Okay, I think I got it working for both systems.
Compiles fine on Linux and Darwin and they both have the `binaryview` command which is an optional feature.
``` diff
diff --git a/pkgs/shells/nushell/default.nix b/pkgs/shells/nushell/default.nix
index 6e075b7ceee..767aa9eecfa 100644
--- a/pkgs/shells/nushell/default.nix
+++ b/pkgs/shells/nushell/default.nix
@@ -3,8 +3,12 @@
 , rustPlatform
 , openssl
 , pkg-config
+, allFeatures ? true
+, xorg
+, python3
 , libiconv
 , Security
+, AppKit
 }:
 
 rustPlatform.buildRustPackage rec {
@@ -23,7 +27,10 @@ rustPlatform.buildRustPackage rec {
   nativeBuildInputs = [ pkg-config ];
 
   buildInputs = stdenv.lib.optionals stdenv.isLinux [ openssl ]
-    ++ stdenv.lib.optionals stdenv.isDarwin [ libiconv Security ];
+    ++ stdenv.lib.optionals stdenv.isDarwin [ libiconv Security ]
+    ++ stdenv.lib.optionals allFeatures [ (if stdenv.isDarwin then AppKit else xorg.libX11) python3 ];
+
+  cargoBuildFlags = stdenv.lib.optional allFeatures "--features all";
 
   preCheck = ''
     export HOME=$TMPDIR
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index ee936c9a1b2..3c6ef4685d7 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -16531,7 +16531,7 @@ in
   musl = callPackage ../os-specific/linux/musl { };
 
   nushell = callPackage ../shells/nushell {
-    inherit (darwin.apple_sdk.frameworks) Security;
+    inherit (darwin.apple_sdk.frameworks) AppKit Security;
   };
 
   nettools = if stdenv.isLinux then callPackage ../os-specific/linux/net-tools { }
```

The only weird item I think is the dep on python3 for all-features.
Can't figure out where it comes from (at least with just (`rip`)`grep` :man_shrugging:

**Comment by marsam** [comment]
@evanjs sorry for the delay, I've applied your patch adding you as co-author :)
>Can't figure out where it comes from (at least with just (rip)grep 

`cargoDeps` is [accesible outside of the derivation](https://github.com/marsam/nixpkgs/blob/a8942c6cbd737c4ce989caab5a5ae2a05b9a5d43/pkgs/build-support/rust/default.nix#L180), so you could do something like:
```shell
$ rg python3 $(nix-build -A nushell.cargoDeps)
````
image
in this case,  the python3 requirement comes from xcb as build dependency

**Comment by teto** [comment]
finally got around to testing it. Cool ! thanks for doing it <3

**Pull request merged**
