### PR TITLE
red: init at 0bfb499

### PR DESCRIPTION
**Pull request by 4z3**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jtojnar — COMMENTED** [review]
`red` attribute name is already taken, hence the failure.

**Comment by doronbehar** [comment]
> Question now is, whether it makes sense to rename the directory and the pname to go-red.

I'd leave that as - it's easy enough to note the difference between both attributes by noting the different path under `<nixpkgs>` in which the drv is defined.

**Comment by Lassulus** [comment]
```
error: build of '/nix/store/5s7ws1ryq62mcdma9x7dxz72pz4hy2m9-red-unstable-2019-04-04-go-modules.drv' on 'ssh://nix@morpheus.r' failed: hash mismatch in fixed-output derivation '/nix/store/hghvy88y8j1i00ldnwcp1k630jii1m5h-red-unstable-2019-04-04-go-modules':
  wanted: sha256:0640x6p5hi7yp001cw13z5a17bi9vgd3gij5fxa1y06d3848cv7l
  got:    sha256:0a107hiaid0fprbm8lzakkqz5xlvrwv43b3avz3cxmix59xy0d7i
builder for '/nix/store/5s7ws1ryq62mcdma9x7dxz72pz4hy2m9-red-unstable-2019-04-04-go-modules.drv' failed with exit code 1; last 10 log lines:
  go: downloading golang.org/x/sys v0.0.0-20190222072716-a9d3bda3a223
  go: downloading golang.org/x/text v0.3.0
  go: downloading github.com/mattn/go-runewidth v0.0.4
  go: downloading github.com/lucasb-eyer/go-colorful v0.0.0-20181028223441-12d3b2882a08
  go: downloading github.com/gdamore/encoding v1.0.0
  go: downloading github.com/rivo/uniseg v0.0.0-20190313204849-f699dde9c340
  installing
  hash mismatch in fixed-output derivation '/nix/store/hghvy88y8j1i00ldnwcp1k630jii1m5h-red-unstable-2019-04-04-go-modules':
    wanted: sha256:0640x6p5hi7yp001cw13z5a17bi9vgd3gij5fxa1y06d3848cv7l
    got:    sha256:0a107hiaid0fprbm8lzakkqz5xlvrwv43b3avz3cxmix59xy0d7i
cannot build derivation '/nix/store/ajl51kpjpfpb9mcdv8b7g69vr4cnc2b9-red-unstable-2019-04-04.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/sial4pfnpwffnc8jkxxlg3x49sw7jpvc-env.drv': 1 dependencies couldn't be built
```

**Comment by 4z3** [comment]
I'm not interested in maintaining this anymore, sorry. :1st_place_medal:

**Pull request closed without merging**
