### PR TITLE
lilv: fix python bindings by using full path to library

### LINKED ISSUE #202652: lilv python bindings not working (shared library not found)
### Describe the bug

The lilv python bindings are not working (the shared library is not found)

### Steps To Reproduce
```console
nix-shell -p lilv python3 --run 'echo "import lilv" | python3'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/gw2xsmi1sqs7dw185rhy5vycq4l2n2j7-lilv-0.24.12/lib/python3.9/site-packages/lilv.py", line 36, in <module>
    c = _LilvLib()
  File "/nix/store/gw2xsmi1sqs7dw185rhy5vycq4l2n2j7-lilv-0.24.12/lib/python3.9/site-packages/lilv.py", line 32, in __init__
    self.lib = CDLL("liblilv-0.so")
  File "/nix/store/0zzvjh5gnz0ny7ckilzyn9hmg5lypszf-python3-3.9.13/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: liblilv-0.so: cannot open shared object file: No such file or directory
```

### Expected behavior

The import statement should work!

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[fps@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.78, NixOS, 22.05 (Quokka), 22.05.4120.16f4e04658c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

### PR DESCRIPTION
**Pull request by fps**
###### Description of changes

Added a `preInstall` hook to change occurences of "liblilv-0.so" to "$out/lib/liblilv-0.so" to fix the included python bindings.

Fixes: https://github.com/NixOS/nixpkgs/issues/202652

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mindavi** [comment]
Looks good, but I recommend also adding a postInstallCheck where the import is checked, to prevent future regressions.

**Review by Mindavi — APPROVED** [review]

**Comment by fps** [comment]
Hi, thanks for the review. I might rather try to get that test upstream..

**Comment by trofi** [comment]
It's a mass rebuild (more than 1000 packages). Can you rebase against `staging`?

**Comment by fps** [comment]
ok, that didn't work. closing the PR and doing a new one. talk to you in a year again..

**Pull request closed without merging**
