### PR TITLE
librewolf-unwrapped: 129.0.1 -> 129.0.1-1

### PR DESCRIPTION
**Pull request by dotlambda**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by matdibu** [comment]
build failed during routine `nixos-rebuild`, on `x86_64-linux`, with commit `ac2df85f4d5c580786c7b4db031c199554152681`

```
applying LibreWolf patch: patches/nvidia-wayland-backported-fixes-0001-Bug-1898476-Wayland-Move-MozContainerSurfaceLock-fro.patch
The next patch would create the file widget/gtk/MozContainerSurfaceLock.cpp,
which already exists!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file widget/gtk/MozContainerSurfaceLock.h,
which already exists!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored
patching file widget/gtk/MozContainerWayland.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file widget/gtk/MozContainerWayland.cpp.rej
patching file widget/gtk/MozContainerWayland.h
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file widget/gtk/MozContainerWayland.h.rej
patching file widget/gtk/moz.build
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
3 out of 3 hunks ignored -- saving rejects to file widget/gtk/moz.build.rej
```

**Comment by drupol** [comment]
I think this is broken on `nixos-unstable`:

```
librewolf-unwrapped> building '/nix/store/phkbrpwii0qb8x86nl765h0csw7f3na2-librewolf-unwrapped-129.0.1-1.drv'
librewolf-unwrapped> Running phase: unpackPhase
librewolf-unwrapped> unpacking source archive /nix/store/yvfbccqmlyz22aygk7pg6s83lpx5nx4n-firefox-129.0.1.source.tar.xz
librewolf-unwrapped> source root is firefox-129.0.1
librewolf-unwrapped> setting SOURCE_DATE_EPOCH to timestamp 1723466949 of file firefox-129.0.1/sourcestamp.txt
librewolf-unwrapped> Running phase: patchPhase
librewolf-unwrapped> applying patch /nix/store/9lx1746yy56pn3dpc35l1xr6l3lykbin-env_var_for_system_dir-ff111.patch
librewolf-unwrapped> patching file toolkit/xre/nsXREDirProvider.cpp
librewolf-unwrapped> Hunk #2 succeeded at 313 (offset 3 lines).
librewolf-unwrapped> applying patch /nix/store/6wsdh6246xbmlv3jr5q7qpl9ay3acq04-no-buildconfig-ffx121.patch
librewolf-unwrapped> patching file docshell/base/nsAboutRedirector.cpp
librewolf-unwrapped> patching file toolkit/content/jar.mn
librewolf-unwrapped> Hunk #1 succeeded at 44 (offset 3 lines).
librewolf-unwrapped> applying patch /nix/store/14gmmaq28hb5892lvwap2yblww7afgpz-cbindgen-0.27.0-compat.patch
librewolf-unwrapped> patching file servo/components/style_traits/values.rs
librewolf-unwrapped> Hunk #1 succeeded at 383 (offset -1 lines).
librewolf-unwrapped> Hunk #2 succeeded at 408 (offset -1 lines).
librewolf-unwrapped> patching file servo/ports/geckolib/cbindgen.toml
librewolf-unwrapped> Hunk #1 succeeded at 355 (offset -2 lines).
librewolf-unwrapped> applying patch /nix/store/idkwbyzx5hv6cjbmq6aplxpkxyji0n4x-mozbz-1898476-1.patch
librewolf-unwrapped> patching file widget/gtk/MozContainerWayland.cpp
librewolf-unwrapped> patching file widget/gtk/MozContainerWayland.h
librewolf-unwrapped> patching file widget/gtk/moz.build
librewolf-unwrapped> patching file widget/gtk/MozContainerSurfaceLock.cpp
librewolf-unwrapped> patching file widget/gtk/MozContainerSurfaceLock.h
librewolf-unwrapped> applying patch /nix/store/n6drjva08mkxwrx0ikz9xkzby4zsfail-mozbz-1898476-2.patch
librewolf-unwrapped> patching file widget/gtk/GtkCompositorWidget.cpp
librewolf-unwrapped> patching file widget/gtk/GtkCompositorWidget.h
librewolf-unwrapped> patching file widget/gtk/nsWindow.cpp
librewolf-unwrapped> patching file widget/gtk/nsWindow.h
librewolf-unwrapped> applying patch /nix/store/7f249yx91fri3wb2nwgy1k8l8ms4sqm9-mozbz-1898476-3.patch
librewolf-unwrapped> patching file gfx/webrender_bindings/RenderCompositorEGL.cpp
librewolf-unwrapped> patching script interpreter paths in mach build
librewolf-unwrapped> mach: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/bin/python3"
librewolf-unwrapped> build/cargo-linker: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/bin/python3"
librewolf-unwrapped> build/vs/generate_yaml.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/bin/python3"
librewolf-unwrapped> build/checksums.py: interpreter directive changed from "#!/usr/bin/python" to "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/bin/python"
librewolf-unwrapped> build/macosx/xcrun: interpreter directive changed from "#!/bin/sh" to "/nix/store/4bj2kxdm1462fzcc2i2s4dn33g2angcc-bash-5.2p32/bin/sh"
librewolf-unwrapped> build/cargo-host-linker: interpreter directive changed from "#!/bin/sh" to "/nix/store/4bj2kxdm1462fzcc2i2s4dn33g2angcc-bash-5.2p32/bin/sh"
librewolf-unwrapped> build/build-clang/build-clang.py: interpreter directive changed from "#!/usr/bin/python3" to "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/bin/python3"
librewolf-unwrapped> build/clang-plugin/import_mozilla_checks.py: interpreter directive changed from "#!/usr/bin/python3" to "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/bin/python3"
librewolf-unwrapped> build/unix/print-non-newline.sh: interpreter directive changed from "#!/bin/sh" to "/nix/store/4bj2kxdm1462fzcc2i2s4dn33g2angcc-bash-5.2p32/bin/sh"
librewolf-unwrapped> build/unix/build-hfsplus/build-hfsplus.sh: interpreter directive changed from "#!/bin/bash" to "/nix/store/4bj2kxdm1462fzcc2i2s4dn33g2angcc-bash-5.2p32/bin/bash"
librewolf-unwrapped> build/unix/build-binutils/build-binutils.sh: interpreter directive changed from "#!/bin/bash" to "/nix/store/4bj2kxdm1462fzcc2i2s4dn33g2angcc-bash-5.2p32/bin/bash"
librewolf-unwrapped> build/unix/build-gcc/build-gcc.sh: interpreter directive changed from "#!/bin/bash" to "/nix/store/4bj2kxdm1462fzcc2i2s4dn33g2angcc-bash-5.2p32/bin/bash"
librewolf-unwrapped> build/pgo/profileserver.py: interpreter directive changed from "#!/usr/bin/python" to "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/bin/python"
librewolf-unwrapped> build/package/mac_osx/unpack-diskimage: interpreter directive changed from "#!/bin/bash" to "/nix/store/4bj2kxdm1462fzcc2i2s4dn33g2angcc-bash-5.2p32/bin/bash"
librewolf-unwrapped> build/package/mac_osx/make-diskimage: interpreter directive changed from "#!/bin/sh" to "/nix/store/4bj2kxdm1462fzcc2i2s4dn33g2angcc-bash-5.2p32/bin/sh"
librewolf-unwrapped> build/qemu-wrap: interpreter directive changed from "#!/bin/bash" to "/nix/store/4bj2kxdm1462fzcc2i2s4dn33g2angcc-bash-5.2p32/bin/bash"
librewolf-unwrapped> build/autoconf/config.guess: interpreter directive changed from "#! /bin/sh" to "/nix/store/4bj2kxdm1462fzcc2i2s4dn33g2angcc-bash-5.2p32/bin/sh"
librewolf-unwrapped> build/autoconf/install-sh: interpreter directive changed from "#!/bin/sh" to "/nix/store/4bj2kxdm1462fzcc2i2s4dn33g2angcc-bash-5.2p32/bin/sh"
librewolf-unwrapped> build/autoconf/config.sub: interpreter directive changed from "#! /bin/sh" to "/nix/store/4bj2kxdm1462fzcc2i2s4dn33g2angcc-bash-5.2p32/bin/sh"
librewolf-unwrapped> applying LibreWolf patch: patches/allow-JXL-in-non-nightly-browser.patch
librewolf-unwrapped> patching file toolkit/moz.configure
librewolf-unwrapped> Hunk #1 succeeded at 905 (offset 202 lines).
librewolf-unwrapped> applying LibreWolf patch: patches/allow-ubo-private-mode.patch
librewolf-unwrapped> patching file toolkit/components/extensions/Extension.sys.mjs
librewolf-unwrapped> Hunk #1 succeeded at 3717 (offset 431 lines).
librewolf-unwrapped> applying LibreWolf patch: patches/bootstrap.patch
librewolf-unwrapped> patching file python/mozversioncontrol/mozversioncontrol/__init__.py
librewolf-unwrapped> Hunk #1 succeeded at 1137 (offset 118 lines).
librewolf-unwrapped> applying LibreWolf patch: patches/context-menu.patch
librewolf-unwrapped> patching file browser/base/content/browser-context.inc
librewolf-unwrapped> applying LibreWolf patch: patches/custom-ubo-assets-bootstrap-location.patch
librewolf-unwrapped> patching file toolkit/components/extensions/parent/ext-storage.js
librewolf-unwrapped> Hunk #1 succeeded at 344 (offset 167 lines).
librewolf-unwrapped> applying LibreWolf patch: patches/dbus_name.patch
librewolf-unwrapped> patching file toolkit/components/remote/nsDBusRemoteClient.cpp
librewolf-unwrapped> Hunk #3 succeeded at 114 (offset -1 lines).
librewolf-unwrapped> Hunk #4 succeeded at 125 (offset -1 lines).
librewolf-unwrapped> patching file toolkit/components/remote/nsDBusRemoteServer.cpp
librewolf-unwrapped> Hunk #1 succeeded at 29 (offset 1 line).
librewolf-unwrapped> Hunk #2 succeeded at 39 (offset 1 line).
librewolf-unwrapped> Hunk #3 succeeded at 130 (offset 1 line).
librewolf-unwrapped> Hunk #4 succeeded at 204 (offset 2 lines).
librewolf-unwrapped> Hunk #5 succeeded at 218 (offset 2 lines).
librewolf-unwrapped> applying LibreWolf patch: patches/devtools-bypass.patch
librewolf-unwrapped> patching file devtools/server/actors/thread.js
librewolf-unwrapped> patching file devtools/server/actors/webconsole/listeners/console-api.js
librewolf-unwrapped> applying LibreWolf patch: patches/disable-data-reporting-at-compile-time.patch
librewolf-unwrapped> patching file browser/moz.configure
librewolf-unwrapped> patching file python/mach/mach/telemetry.py
librewolf-unwrapped> applying LibreWolf patch: patches/flatpak-autoconf.patch
librewolf-unwrapped> patching file extensions/pref/autoconfig/src/nsReadConfig.cpp
librewolf-unwrapped> applying LibreWolf patch: patches/fullpage-translations-customization.patch
librewolf-unwrapped> patching file browser/base/content/main-popupset.inc.xhtml
librewolf-unwrapped> patching file browser/base/content/main-popupset.js
librewolf-unwrapped> patching file browser/components/preferences/main.inc.xhtml
librewolf-unwrapped> patching file browser/components/preferences/main.js
librewolf-unwrapped> patching file browser/components/translations/content/fullPageTranslationsPanel.js
librewolf-unwrapped> patching file browser/locales/en-US/browser/translations.ftl
librewolf-unwrapped> applying LibreWolf patch: patches/fullpage-translations.patch
librewolf-unwrapped> patching file services/settings/Attachments.sys.mjs
librewolf-unwrapped> Hunk #1 succeeded at 146 (offset 2 lines).
librewolf-unwrapped> Hunk #2 succeeded at 206 (offset 2 lines).
librewolf-unwrapped> Hunk #3 succeeded at 267 (offset 11 lines).
librewolf-unwrapped> Hunk #4 succeeded at 438 (offset 11 lines).
librewolf-unwrapped> Hunk #5 succeeded at 447 (offset 11 lines).
librewolf-unwrapped> Hunk #6 succeeded at 500 (offset 11 lines).
librewolf-unwrapped> Hunk #7 succeeded at 516 (offset 11 lines).
librewolf-unwrapped> patching file services/settings/RemoteSettingsClient.sys.mjs
librewolf-unwrapped> Hunk #4 succeeded at 610 (offset 1 line).
librewolf-unwrapped> patching file toolkit/components/translations/actors/TranslationsParent.sys.mjs
librewolf-unwrapped> Hunk #1 succeeded at 1217 (offset 183 lines).
librewolf-unwrapped> Hunk #2 succeeded at 1605 (offset 183 lines).
librewolf-unwrapped> Hunk #3 succeeded at 1685 (offset 209 lines).
librewolf-unwrapped> Hunk #4 succeeded at 1711 (offset 209 lines).
librewolf-unwrapped> Hunk #5 succeeded at 2006 (offset 337 lines).
librewolf-unwrapped> applying LibreWolf patch: patches/hide-passwordmgr.patch
librewolf-unwrapped> patching file browser/base/content/browser-init.js
librewolf-unwrapped> patching file browser/components/preferences/privacy.js
librewolf-unwrapped> Hunk #1 succeeded at 1274 (offset 60 lines).
librewolf-unwrapped> applying LibreWolf patch: patches/librewolf-prefs.patch
librewolf-unwrapped> patching file browser/app/profile/firefox.js
librewolf-unwrapped> applying LibreWolf patch: patches/mozilla_dirs.patch
librewolf-unwrapped> patching file toolkit/xre/nsXREDirProvider.cpp
librewolf-unwrapped> Hunk #1 succeeded at 301 with fuzz 1 (offset 1 line).
librewolf-unwrapped> Hunk #2 succeeded at 383 (offset 12 lines).
librewolf-unwrapped> Hunk #3 succeeded at 415 (offset 4 lines).
librewolf-unwrapped> Hunk #4 succeeded at 1134 (offset 20 lines).
librewolf-unwrapped> Hunk #5 succeeded at 1400 (offset 37 lines).
librewolf-unwrapped> Hunk #6 succeeded at 1410 (offset 37 lines).
librewolf-unwrapped> applying LibreWolf patch: patches/msix.patch
librewolf-unwrapped> patching file browser/installer/windows/msix/AppxManifest.xml.in
librewolf-unwrapped> Hunk #1 succeeded at 30 (offset 1 line).
librewolf-unwrapped> Hunk #2 succeeded at 120 (offset 11 lines).
librewolf-unwrapped> patching file python/mozbuild/mozbuild/mach_commands.py
librewolf-unwrapped> Hunk #1 succeeded at 2620 (offset 109 lines).
librewolf-unwrapped> Hunk #2 succeeded at 2779 (offset 131 lines).
librewolf-unwrapped> patching file python/mozbuild/mozbuild/repackaging/msix.py
librewolf-unwrapped> Hunk #2 succeeded at 354 (offset -1 lines).
librewolf-unwrapped> Hunk #3 succeeded at 480 (offset -29 lines).
librewolf-unwrapped> applying LibreWolf patch: patches/nvidia-wayland-backported-fixes-0001-Bug-1898476-Wayland-Move-MozContainerSurfaceLock-fro.patch
librewolf-unwrapped> The next patch would create the file widget/gtk/MozContainerSurfaceLock.cpp,
librewolf-unwrapped> which already exists!  Assume -R? [n] 
librewolf-unwrapped> Apply anyway? [n] 
librewolf-unwrapped> Skipping patch.
librewolf-unwrapped> 1 out of 1 hunk ignored
librewolf-unwrapped> The next patch would create the file widget/gtk/MozContainerSurfaceLock.h,
librewolf-unwrapped> which already exists!  Assume -R? [n] 
librewolf-unwrapped> Apply anyway? [n] 
librewolf-unwrapped> Skipping patch.
librewolf-unwrapped> 1 out of 1 hunk ignored
librewolf-unwrapped> patching file widget/gtk/MozContainerWayland.cpp
librewolf-unwrapped> Reversed (or previously applied) patch detected!  Assume -R? [n] 
librewolf-unwrapped> Apply anyway? [n] 
librewolf-unwrapped> Skipping patch.
librewolf-unwrapped> 1 out of 1 hunk ignored -- saving rejects to file widget/gtk/MozContainerWayland.cpp.rej
librewolf-unwrapped> patching file widget/gtk/MozContainerWayland.h
librewolf-unwrapped> Reversed (or previously applied) patch detected!  Assume -R? [n] 
librewolf-unwrapped> Apply anyway? [n] 
librewolf-unwrapped> Skipping patch.
librewolf-unwrapped> 2 out of 2 hunks ignored -- saving rejects to file widget/gtk/MozContainerWayland.h.rej
librewolf-unwrapped> patching file widget/gtk/moz.build
librewolf-unwrapped> Reversed (or previously applied) patch detected!  Assume -R? [n] 
librewolf-unwrapped> Apply anyway? [n] 
librewolf-unwrapped> Skipping patch.
librewolf-unwrapped> 3 out of 3 hunks ignored -- saving rejects to file widget/gtk/moz.build.rej
error: builder for '/nix/store/phkbrpwii0qb8x86nl765h0csw7f3na2-librewolf-unwrapped-129.0.1-1.drv' failed with exit code 1;
       last 50 log lines:
       > applying LibreWolf patch: patches/hide-passwordmgr.patch
       > patching file browser/base/content/browser-init.js
       > patching file browser/components/preferences/privacy.js
       > Hunk #1 succeeded at 1274 (offset 60 lines).
       > applying LibreWolf patch: patches/librewolf-prefs.patch
       > patching file browser/app/profile/firefox.js
       > applying LibreWolf patch: patches/mozilla_dirs.patch
       > patching file toolkit/xre/nsXREDirProvider.cpp
       > Hunk #1 succeeded at 301 with fuzz 1 (offset 1 line).
       > Hunk #2 succeeded at 383 (offset 12 lines).
       > Hunk #3 succeeded at 415 (offset 4 lines).
       > Hunk #4 succeeded at 1134 (offset 20 lines).
       > Hunk #5 succeeded at 1400 (offset 37 lines).
       > Hunk #6 succeeded at 1410 (offset 37 lines).
       > applying LibreWolf patch: patches/msix.patch
       > patching file browser/installer/windows/msix/AppxManifest.xml.in
       > Hunk #1 succeeded at 30 (offset 1 line).
       > Hunk #2 succeeded at 120 (offset 11 lines).
       > patching file python/mozbuild/mozbuild/mach_commands.py
       > Hunk #1 succeeded at 2620 (offset 109 lines).
       > Hunk #2 succeeded at 2779 (offset 131 lines).
       > patching file python/mozbuild/mozbuild/repackaging/msix.py
       > Hunk #2 succeeded at 354 (offset -1 lines).
       > Hunk #3 succeeded at 480 (offset -29 lines).
       > applying LibreWolf patch: patches/nvidia-wayland-backported-fixes-0001-Bug-1898476-Wayland-Move-MozContainerSurfaceLock-fro.patch
       > The next patch would create the file widget/gtk/MozContainerSurfaceLock.cpp,
       > which already exists!  Assume -R? [n]
       > Apply anyway? [n]
       > Skipping patch.
       > 1 out of 1 hunk ignored
       > The next patch would create the file widget/gtk/MozContainerSurfaceLock.h,
       > which already exists!  Assume -R? [n]
       > Apply anyway? [n]
       > Skipping patch.
       > 1 out of 1 hunk ignored
       > patching file widget/gtk/MozContainerWayland.cpp
       > Reversed (or previously applied) patch detected!  Assume -R? [n]
       > Apply anyway? [n]
       > Skipping patch.
       > 1 out of 1 hunk ignored -- saving rejects to file widget/gtk/MozContainerWayland.cpp.rej
       > patching file widget/gtk/MozContainerWayland.h
       > Reversed (or previously applied) patch detected!  Assume -R? [n]
       > Apply anyway? [n]
       > Skipping patch.
       > 2 out of 2 hunks ignored -- saving rejects to file widget/gtk/MozContainerWayland.h.rej
       > patching file widget/gtk/moz.build
       > Reversed (or previously applied) patch detected!  Assume -R? [n]
       > Apply anyway? [n]
       > Skipping patch.
       > 3 out of 3 hunks ignored -- saving rejects to file widget/gtk/moz.build.rej
       For full logs, run 'nix log /nix/store/phkbrpwii0qb8x86nl765h0csw7f3na2-librewolf-unwrapped-129.0.1-1.drv'.
error: 1 dependencies of derivation '/nix/store/m5jczdsczn4wkk2slf7x4w1srf0p5fh5-librewolf-129.0.1-1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/0064vy05prxrk56x1v1dy7w9f83j1rqr-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/sdcgxxlwyci9xanr7s78kqb80vbr943r-librewolf-129.0.1-1-fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fam40cscdrrjn9k46giag82h2g67a2ln-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/l6fs3xydsj83p85yc6qjhzxvz1f38kpp-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/33q272lwd1cd9bpv6hbzbnraqgifhig0-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ivr5y63bhs0dii4axy2qpr5ymvapspf0-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/iingnvakaz8q8a699a6rwr0xn0a4n343-nixos-system-x13-24.11.20240821.c374d94.drv' failed to build
```

**Comment by drupol** [comment]
Issue on CI: https://hydra.nixos.org/build/270110612

**Comment by matdibu** [comment]
@drupol yes, but not because of this PR (I also thought that initially, but I deleted my comment)
see https://github.com/NixOS/nixpkgs/pull/336204 and https://github.com/NixOS/nixpkgs/pull/336304

**Comment by drupol** [comment]
Fair enough, thanks for the clarification.

**Pull request merged**
