### PR TITLE
ponyc: 0.21.0 -> 0.21.2

### PR DESCRIPTION
**Pull request by kamilchm**
###### Motivation for this change

https://github.com/ponylang/ponyc/issues/2448

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg build ponyc

**Comment by grahamc** [comment]
@kamilchm are these aarch64 / darwin failures to be expected? LGTM otherwise.

**Comment by kamilchm** [comment]
How can I rerun darwin/aarch64 builds? I can try to fix it.

**Comment by kamilchm** [comment]
I've updated patch for darwin tests and will try to fix arm build.

@GrahamcOfBorg build ponyc

**Comment by orivej** [comment]
`ponyc` was updated in #33471, somehow without changes to tests.

**Pull request closed without merging**
