### PR TITLE
bctoolbox: 5.2.16 -> 5.2.30

### PR DESCRIPTION
**Pull request by felixsinger**
###### Description of changes

The "update" doesn't contain any changes. Just the version number
changed, probably because to stay inline with the other libraries of the
ecosystem.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ThibaultLemaire — CHANGES_REQUESTED** [review]
Following the same procedure as [my comment on your bc-decaf PR](https://github.com/NixOS/nixpkgs/pull/220420#pullrequestreview-1334451748), this version is misaligned. Version 5.2.16 is the one shipped officially with Linphone Desktop 5.0.8.

Chances are 5.2.30 will work as well, but that is not guaranteed. Do you need that specific version for an other package?

If not, I suggest to leave bctoolbox as it is until Linphone Desktop is upgraded.

**Comment by wegank** [comment]
Well, I believe `linphone` is no longer maintained...

**Comment by ThibaultLemaire** [comment]
> Well, I believe `linphone` is no longer maintained...

In that case I might be able to pick it up, depending on my employer, and if you other maintainers are ok with it. (There could be conflict of interest, I work for the company making Linphone)

**Comment by wegank** [comment]
Closed by #252773.

**Pull request closed without merging**
