### PR TITLE
distrobuilder: 2018_04_28 -> 2018_06_29

### PR DESCRIPTION
**Pull request by megheaiulian**
###### Motivation for this change
Upgrade distrobuilder and add add doCheck.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build distrobuilder

**Comment by xeji** [comment]
```
        util_test.go:87: Failed to verify: testfile with detached signature
                Failed to create keyring: gpg: keybox '/build/distrobuilder.713647054/pubring.kbx' created
                gpg: keyserver receive failed: No such file or directory
```

Looks like the test fails in the sandbox because it tries to download a key from a keyserver. No network access in the sandbox. You can try to pre-download the key with `fetchurl` during build or disable the failing test. If this doesn't help, disable tests altogether again.

I recommend to enable sandboxing on your system because it's safer, and it will help you catch these errors.

**Comment by megheaiulian** [comment]
@xeji I've disable tests for now. 
I was testing locally using `nix-build -A distrobuilder --show-trace --option build-use-sandbox true` but I didn't catch any of the problems with tests. Will retry to kee tests on a next  update.

**Comment by megheaiulian** [comment]
@GrahamcOfBorg build distrobuilder

**Comment by xeji** [comment]
@GrahamcOfBorg build distrobuilder

**Pull request merged**
