### PR TITLE
installer: add graphical GNOME iso

### PR DESCRIPTION
**Pull request by lucabrunox**
Adds a new iso for the release with GNOME 3. Renames `graphical` to `graphical-kde`.

Screenshot on virtualbox:

cc @edolstra @domenkozar

### CODE REVIEW

**Comment by bjornfor** [comment]
Sweet!

Observation: You're enabling both ```displayManager.slim``` and ```displayManager.gdm```. Is that intentional?

**Comment by edolstra** [comment]
I don't think we should do this. Building more ISOs puts quite a load on Hydra (especially the graphical ISOs, which are very large) and on the channel update script (since it needs to upload the ISOs to EC2). One graphical ISO is enough IMHO.

**Comment by lethalman** [comment]
@edolstra ok what about including the nix but not in the release?

**Comment by domenkozar** [comment]
How big is the closure?

**Comment by domenkozar** [comment]
Could we enable it only for stable releases?

**Comment by lethalman** [comment]
The result closure of the iso build is 5.0GB. The iso itself is 1.2GB.

From hydra charts, the result closure of the kde iso build is about 4GB, and the iso is 960MB.

**Comment by edolstra** [comment]
Well, what's the goal? AFAIK other distros don't offer a different ISO for each desktop environment they support. The only reason for the installation ISO is to, well, install. After that the user can install any desktop environment they want.

NixOS releases are already 4.4 GB per channel update and I regularly need to throw away old (stable!) releases to prevent the disks from filling up.

**Comment by lethalman** [comment]
It's a showcase. Also doesn't the installer benefit from /nix/store of the iso? That would mean less downloads if installing gnome. Anyway, is it possible to include the nix without building on hydra?

**Comment by Mathnerd314** [comment]
Looking at the ["major Linux distributions"](http://distrowatch.com/dwres.php?resource=major) (minus FreeBSD):
1. Linux Mint has 3 variants: http://www.linuxmint.com/download.php
2. Ubuntu has lots of Flavors: https://wiki.ubuntu.com/UbuntuFlavors
3. Debian has lots of Live Iso's: http://cdimage.debian.org/debian-cd/current-live/amd64/bt-hybrid/
4. Mageia has KDE and GNOME: http://www.mageia.org/en/downloads/
5. Fedora offers ISO's for every desktop: https://spins.fedoraproject.org/
6. OpenSUSE has Live KDE and Live GNOME: http://software.opensuse.org/132/en
7. Arch doesn't provide a graphical installer, but has lots of derivatives that do
8. CentOS has GNOME and KDE: http://mirror.lug.udel.edu/pub/centos/7/isos/x86_64/
9. PCLinuxOS provides KDE, LXDE, and MATE: http://www.pclinuxos.com/get-pclinuxos/
10. Slackware does only KDE: http://www.slackware.com/getslack/torrents.php

So, 8 out of 10 distros **do** offer a different ISO for each desktop environment they support.

**Comment by vcunat** [comment]
I think there's a common concept of *live iso* that people can try out a bit to get some feel about the distro, i.e. installation seems *not* the only purpose for those images. IMHO, the isos don't need to be updated so often, especially the big ones, as the installation is network-bounded anyway, and it's enough to keep just 2-3 latest of each channel (especially when we have the -small variants as well).

**Comment by geerds** [comment]
I would also like to see a Gnome based ISO. Great idea @lethalman

**Comment by domenkozar** [comment]
Let's merge this for 16.03 but not build it on hydra by default.

**Comment by lethalman** [comment]
Now that the unstable release passed, I will work on this and merge it.

**Comment by lethalman** [comment]
To build it: `nix-build -A gnome3.installerIso`. Didn't find a better place under `nixos/` for now.

**Comment by jgeerds** [comment]
:beers:

**Pull request merged**
