### PR TITLE
nodePackages.hyperpotamus: init

### PR DESCRIPTION
**Pull request by onny**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 132813` at faadb46e run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages skipped due to time constraints:</summary>
  <ul>
    <li>iosevka</li>
    <li>lumo</li>
  </ul>
</details>
<details>
  <summary>11 packages built successfully:</summary>
  <ul>
    <li>castnow</li>
    <li>fast-cli</li>
    <li>joplin</li>
    <li>netlify-cli</li>
    <li>postcss-cli</li>
    <li>redoc-cli</li>
    <li>vimPlugins.coc-prettier</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>wasm-text-gen</li>
  </ul>
</details>
<details>
  <summary>19 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/node-packages/node-env.nix:401:7:
```
    |
401 |       name = "${name}-${version}";
    |       ^
```

Near pkgs/development/node-packages/node-packages.nix:109329:5:
```
       |
109329 |     version = "0.12.2";
       |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/node-packages/node-env.nix:401:7:
```
    |
401 |       name = "${name}-${version}";
    |       ^
```

Near pkgs/development/node-packages/node-packages.nix:99502:5:
```
      |
99502 |     version = "6.0.5";
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall`.

Near pkgs/development/node-packages/node-env.nix:417:7:
```
    |
417 |       installPhase = ''
    |       ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/node-packages/node-env.nix:401:7:
```
    |
401 |       name = "${name}-${version}";
    |       ^
```

Near pkgs/development/node-packages/node-packages.nix:83850:5:
```
      |
83850 |     version = "3.0.1";
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/node-packages/node-env.nix:401:7:
```
    |
401 |       name = "${name}-${version}";
    |       ^
```

Near pkgs/development/node-packages/node-packages.nix:91311:5:
```
      |
91311 |     version = "2.1.2";
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/node-packages/node-env.nix:401:7:
```
    |
401 |       name = "${name}-${version}";
    |       ^
```

Near pkgs/development/node-packages/node-packages.nix:71939:5:
```
      |
71939 |     version = "0.6.0";
      |     ^
```
</li>
    <li>warning: unused-argument

Unused argument: `lib`.
Near pkgs/development/node-packages/node-packages.nix:3:54:
```
  |
3 | {nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:
  |                                                      ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/misc/vim-plugins/build-vim-plugin.nix:28:14:
```
   |
28 |       inherit unpackPhase configurePhase buildPhase addonInfo preInstall postInstall;
   |              ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

nodePackages.node-gyp-build is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/development/node-packages/node-env.nix:402:7:
```
    |
402 |       buildInputs = [ tarWrapper python nodejs ]
    |       ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/node-packages/node-env.nix:401:7:
```
    |
401 |       name = "${name}-${version}";
    |       ^
```

Near pkgs/development/node-packages/node-packages.nix:106464:5:
```
       |
106464 |     version = "8.3.1";
       |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/development/node-packages/node-env.nix:451:7:
```
    |
451 |       meta = {
    |       ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

nodePackages.node-pre-gyp is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/development/node-packages/node-env.nix:402:7:
```
    |
402 |       buildInputs = [ tarWrapper python nodejs ]
    |       ^
```
</li>
    <li>warning: unused-argument

Unused argument: `stdenv`.
Near pkgs/development/node-packages/node-packages.nix:3:46:
```
  |
3 | {nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:
  |                                              ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/development/node-packages/node-env.nix:410:14:
```
    |
410 |       inherit dontNpmInstall preRebuild unpackPhase buildPhase;
    |              ^
```
</li>
    <li>warning: unused-argument

Unused argument: `nix-gitignore`.
Near pkgs/development/node-packages/node-packages.nix:3:31:
```
  |
3 | {nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:
  |                               ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/node-packages/node-env.nix:451:7:
```
    |
451 |       meta = {
    |       ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

util-linux is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/development/node-packages/node-env.nix:402:7:
```
    |
402 |       buildInputs = [ tarWrapper python nodejs ]
    |       ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`configurePhase` should probably contain `runHook preConfigure` and `runHook postConfigure`.

Near pkgs/misc/vim-plugins/build-vim-plugin.nix:28:14:
```
   |
28 |       inherit unpackPhase configurePhase buildPhase addonInfo preInstall postInstall;
   |              ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/node-packages/node-env.nix:401:7:
```
    |
401 |       name = "${name}-${version}";
    |       ^
```

Near pkgs/development/node-packages/node-packages.nix:69548:5:
```
      |
69548 |     version = "1.11.1";
      |     ^
```
</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Please rebase. You can also only add the name to the list and wait for the next person to update it.

**Comment by onny** [comment]
Hm, I'm struggling with rebasing, how could I revert the rebase?

**Comment by onny** [comment]
> Please rebase. You can also only add the name to the list and wait for the next person to update it.

Okay I managed it ^^ Rebasing done :)

**Pull request merged**
