### PR TITLE
Keybase to 1.0.33

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Motivation for this change
Updates

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by danielfullmer** [comment]
I'd suggest adding `"kbfsgit/git-remote-keybase"` to `subPackages` in `kbfs/default.nix` to enable the new `git-remote-keybase` functionality described in https://keybase.io/blog/encrypted-git-for-everyone

**Comment by carlsverre** [comment]
`keybase service` still works for me...  The pull reqs that I sent work fine and I have keybase + kbfs + keybase-gui + git-remote-keybase all working well on my NixOS machine.  This is what I have in my NixOS configuration:

```
    kbfs = {
      enable = true;
      mountPoint = "/keybase";
      extraFlags = [
          "-label kbfs"
          "-mount-type normal"
        ];
    };
```
https://github.com/carlsverre/nixos-configuration/blob/master/stained/services.nix#L20

**Comment by carlsverre** [comment]
Make sure you run `systemctl --user daemon-reload` after rebuild - user services aren't properly reloaded.

**Comment by NeQuissimus** [comment]
OK, let's merge this then, I basically have the same as you. I took out the service changes.
Must be something with my config then.

**Comment by NeQuissimus** [comment]
I will try the module again tomorrow and then port to stable

**Comment by carlsverre** [comment]
Sounds good, also this just landed - may want to bring it in while we are updating anyways.
https://github.com/keybase/kbfs/pull/1197

**Comment by NeQuissimus** [comment]
Everything works if I run it by hand but not the module to automatically load keybase and mount kbfs... Might be my locked down system though

**Comment by carlsverre** [comment]
Also would be nice to point maintainers at this url to lookup keybase-gui releases:
```
# lookup latest version here:
# https://s3.amazonaws.com/prerelease.keybase.io/linux_binaries/deb/index.html
```

**Comment by NeQuissimus** [comment]
927284f6e4 and 0053f3b86f

**Comment by carlsverre** [comment]
Thanks!

**Comment by NeQuissimus** [comment]
@carlsverre Just to verify: The actual NixOS kbfs module works for you?

**Comment by carlsverre** [comment]
Yea, it's running on my machine now.

**Comment by NeQuissimus** [comment]
dang, no matter what I do it won't do anything...

**Comment by carlsverre** [comment]
This is what I am running on my machine:
https://github.com/carlsverre/nixpkgs/tree/stained

This is my config:
https://github.com/carlsverre/nixos-configuration

After running `sudo systemctl --user restart kbfs` I see this:
```
~/dev/config $ systemctl --user status kbfs                                                                                                             master
● kbfs.service - Keybase File System
   Loaded: loaded (/nix/store/cb2mm0dckjvi4ybv0jjp2yxfsighxrxq-unit-kbfs.service/kbfs.service; static; vendor preset: enabled)
   Active: active (running) since Thu 2017-10-05 17:50:42 PDT; 29s ago
  Process: 21204 ExecStopPost=/run/wrappers/bin/fusermount -u /keybase (code=exited, status=0/SUCCESS)
  Process: 21207 ExecStartPre=/nix/store/d4yib20lqn7krrqmm0wwbwjxjfa78xqp-coreutils-8.28/bin/mkdir -p /keybase (code=exited, status=0/SUCCESS)
 Main PID: 21209 (kbfsfuse)
   CGroup: /user.slice/user-1000.slice/user@1000.service/kbfs.service
           └─21209 /nix/store/6g8hwyn0k2mzy1h4d8c4jgq88ygxvyq9-kbfs-20171004.70800d-bin/bin/kbfsfuse -label kbfs -mount-type normal /keybase

Oct 05 17:50:44 stained kbfsfuse[21209]: github.com/keybase/kbfs/libkbfs.InitWithLogPrefix.func2
Oct 05 17:50:44 stained kbfsfuse[21209]:         /tmp/nix-build-kbfs-20171004.70800d.drv-0/go/src/github.com/keybase/kbfs/libkbfs/init.go:495
Oct 05 17:50:44 stained kbfsfuse[21209]: runtime.goexit
Oct 05 17:50:44 stained kbfsfuse[21209]:         /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.9/share/go/src/runtime/asm_amd64.s:2337
Oct 05 17:50:44 stained kbfsfuse[21209]: 2017-10-05T17:50:44.617707-07:00 ▶ [INFO kbfs start.go:38] 003 Mounting the filesystem was a success
```

And I confirmed that kbfs is working.  Check on your service configuration and compare it to mine.
https://github.com/carlsverre/nixos-configuration/blob/master/stained/services.nix#L20

**Comment by carlsverre** [comment]
@NeQuissimus I think I found the issue.  I was accidentally running the keybase service manually rather than via systemd which allowed the kbfs service to start fine.  The fix is here: https://github.com/carlsverre/nixpkgs/commit/baf5c6ed3135e1371088d5f4db1805f92dc6dce2

Looks like `keybase service` now fork-exes at start.  The `-d` flag prevents this.

**Comment by NeQuissimus** [comment]
@carlsverre ooh, nice, can you send a PR and I'll try it out tonight.

**Comment by NeQuissimus** [comment]
#30171

**Comment by carlsverre** [comment]
Thanks for sending that.

**Pull request merged**
