### PR TITLE
ollama: only set `updateScript` for `ollama`, not `ollama-{rocm,cuda}`

### PR DESCRIPTION
**Pull request by abysssol**
## Description of changes

Attempt to prevent `passthru.updateScript` from triggering a bot update of `ollama-rocm` and `ollama-cuda`. Since `ollama`, `ollama-rocm`, and `ollama-cuda` are all defined in the same file (only specialized with arguments/overrides), only `ollama` should be explicitly updated.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by adamcstephens — APPROVED** [review]
Should be fine. Could also compare `pname != "ollama"` as the others are renamed.

**Comment by mweinelt** [comment]
Nixpkgs-update supports a skiplist: https://github.com/nix-community/nixpkgs-update/blob/d55f27272f33975d67b13be9fa241cdea297dfb1/src/Skiplist.hs#L47

**Comment by abysssol** [comment]
@mweinelt Thank you for letting me know. So, to be clear, I should create a pull request on that repository to add `ollama-rocm` and `ollama-cuda`, right? And this PR is unnecessary (or maybe ineffective?) and should be closed?

**Comment by mweinelt** [comment]
If the only thing you worry about is r-ryantm, then yes.

**Review by drupol — APPROVED** [review]

**Comment by drupol** [comment]
Diff lgtm, but the alternative solution proposed here might seem a better idea.

**Comment by abysssol** [comment]
> If the only thing you worry about is r-ryantm

Are there any bots other than r-ryantm that might be a problem?

If this PR may help, it seems better to merge this as well as adding `ollama-rocm` and `ollama-cuda` to the skip list. Unless there's some reason not to merge this? Maybe this won't actually make any difference?

**Comment by abysssol** [comment]
https://github.com/nix-community/nixpkgs-update/pull/446 has been merged

**Pull request merged**
