### PR TITLE
[24.05] Backport fix for ceph with dmcrypt

### PR DESCRIPTION
**Pull request by nh2**
## Description of changes

Fixes https://github.com/NixOS/nixpkgs/pull/335684#issuecomment-2322849294 by backporting:

* #334275
* #325059
  * build-only change to make the cherry-pick conflict free
* #335684
  * Includes NixOS VM test for that change
* #338619

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

For review @benaryorg

### CODE REVIEW

**Comment by nh2** [comment]
The **Check cherry-picks** message

```
Warning: Difference between 31e495125b71cd77b90f99e0cb4e19f3b97ed217 and original 0cd631e61f7ec34287faea382a9311419c2ca869 may warrant inspection:
```

is expected as explained in the commit message / shown by that check's details.

**Comment by nh2** [comment]
`vm-test-run-basic-single-node-ceph-cluster-bluestore-dmcrypt` passes here, so this looks generally good to me.

**Comment by benaryorg** [comment]
Okay, Ceph has successfully compiled and works with d05b6e35734e5555bd071d03752c1e4fd267db46.

By the way sorry for the trouble with the maintainer/nixpkgs stuff, I was hesitant to do that precisely because I wasn't in the maintainer list yet. Took me a bit to sift through all the PRs, nixpkgs docs, and whatnot, but #338657 should be good to go (if you intend to get this in here of course, I don't mind not being a maintainer until 24.11 rolls around ^^").

**Comment by nh2** [comment]
> sorry for the trouble with the maintainer/nixpkgs stuff, I was hesitant to do that precisely because I wasn't in the maintainer list yet. Took me a bit to sift through all the PRs, nixpkgs docs, and whatnot, but #338657 should be good to go

No problem at all, glad to have you as co-maintainer! The more NixOS Ceph users, the more reliable life we'll all have!

> (if you intend to get this in here of course, I don't mind not being a maintainer until 24.11 rolls around ^^").

For new maintainers I just merged you to `master`, that will be easiest.

---

Merging the backport.

**Pull request merged**
