### PR TITLE
zig: 0.1.1 -> 0.2.0

### PR DESCRIPTION
**Pull request by andrewrk**
no testing done. sha256 computed with `nix-prefetch-url`.

### CODE REVIEW

**Comment by srhb** [comment]
Are you sure you don't want the llvm version overrides in all-packages.nix instead?

**Comment by srhb** [comment]
That is, `zig = callPackage ../development/compilers/zig { llvm = llvm_6; llvmPackages = llvmPackages_6; };`

**Comment by srhb** [comment]
@GrahamcOfBorg build zig

**Comment by andrewrk** [comment]
What's the difference?

The information I can provide is that zig 0.2.0 works with exactly llvm 6.0.0 and no other version.

I trust your judgement on how to communicate this information to nix.

**Comment by dtzWill** [comment]
Putting it at top-level is tradition, for reasons I'm not sure I can claim to fully understand.  Although it does make it easier to see this needs a special version and handle accordingly when doing things like updating default llvmPackages version :).  Also makes overriding version used more natural, instead of "zig.override { llvmPackages_6 = llvmPackages_5; }" or something :).

**Comment by andrewrk** [comment]
I updated this pull request to the recommended way of version locking.

The build failure above seems to have timed out building GCC. I do not understand why that would be a unique requirement to building this package.

**Comment by dtzWill** [comment]
Thanks for the update!

Building this locally failed due to missing dep on libxml2, consider fixing along the lines of commit here:

https://github.com/dtzWill/nixpkgs/commits/andrewrk-zig-0.2.0

Which at least fixes the build for me.

Unfortunately staging is, well, a staging area and often doesn't have everything prebuilt.  You're right that's unrelated to zig entirely :).

-------

Tried this with  the tetris OpenGL example, and once I entered an appropriate nix-shell (`nix-shell -p epoxy -p glfw -p libpng`) it compiled and runs! :+1:

**Comment by andrewrk** [comment]
Thanks @dtzWill. I updated the PR with your suggestions. What does the `nativeBuildInputs` change do?

**Comment by dtzWill** [comment]
It means it's a compile-time dependency, mostly important (and easiest to see why it matters) in the context of cross-compiling: here we want a cmake the builder can execute, not some cmake zig will link against.

LGTM, thanks!

**Comment by dtzWill** [comment]
Backported to 18.03 in 77c052d908088d6096262c6b3af095db98d2f4a2 \o/.

**Pull request merged**
