### PR TITLE
box64: add option for apple silicon

### PR DESCRIPTION
**Pull request by dxwil**
## Description of changes

Add an option to enable Apple silicon build flag. Perhaps there is a way to auto detect the M1 cpu and set the flag automatically, I couldn't figure out a way, but that would obviously be preferred if anyone knows how to.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by OPNA2608** [comment]
Due to the [wide variety of specific platforms that can be targeted with options](https://github.com/ptitSeb/box64/blob/99f2207fd4c64d00e30d29aeade5929e8f907928/CMakeLists.txt#L8-L23), my idea was to let users override box{86,64} on their end as needed, instead of making an option for every possible target.

> Perhaps there is a way to auto detect the M1 cpu and set the flag automatically

Shouldn't be possible, because that would be impure and give different build results with the same build config, based on the specific ARM platform that is doing the build.

You should look into `<drv>.overrideAttrs` to apply custom build options, and depending on your needs [`nixpkgs.overlays`](https://nixos.org/manual/nixpkgs/stable/#sec-overlays-argument) to apply this Nixpkgs-wide if other derivations need to re-use it. If you just want to install an optimised `box64`:

```nix
environment.systemPackages = with pkgs; [
  # Optimised for my hardware
  (box64.overrideAttrs (oldAttrs: {
    cmakeFlags = oldAttrs.cmakeFlags ++ [
      (lib.cmakeBool "M1" true)
    ];
  }))
];
```

**Comment by dxwil** [comment]
> Due to the [wide variety of specific platforms that can be targeted with options](https://github.com/ptitSeb/box64/blob/99f2207fd4c64d00e30d29aeade5929e8f907928/CMakeLists.txt#L8-L23), my idea was to let users override box{86,64} on their end as needed, instead of making an option for every possible target.
> 
> > Perhaps there is a way to auto detect the M1 cpu and set the flag automatically
> 
> Shouldn't be possible, because that would be impure and give different build results with the same build config, based on the specific ARM platform that is doing the build.
> 
> You should look into `<drv>.overrideAttrs` to apply custom build options, and depending on your needs [`nixpkgs.overlays`](https://nixos.org/manual/nixpkgs/stable/#sec-overlays-argument) to apply this Nixpkgs-wide if other derivations need to re-use it. If you just want to install an optimised `box64`:
> 
> ```nix
> environment.systemPackages = with pkgs; [
>   # Optimised for my hardware
>   (box64.overrideAttrs (oldAttrs: {
>     cmakeFlags = oldAttrs.cmakeFlags ++ [
>       (lib.cmakeBool "M1" true)
>     ];
>   }))
> ];
> ```

Yeah makes sense

**Comment by dxwil** [comment]
Hmm, v0.3.0 doesn't pass a test for me, if I build the same version manually with `cmake .. -D M1=1 -D ARM_DYNAREC=1 -D ARM64=1' it works. But if I build with
```
environment.systemPackages = with pkgs; [
  # Optimised for my hardware
  (unstable.box64.overrideAttrs (oldAttrs: {
    cmakeFlags = oldAttrs.cmakeFlags ++ [
      (lib.cmakeBool "M1" true)
    ];
  }))
];
```
it fails with
```
29/30 Test #29: avx_intrinsics ...................***Failed    0.04 sec
CMake Error at /build/source/runTest.cmake:55 (message):
  Failed: The output of /build/source/build/box64 did not match
  /build/source/tests/ref30.txt



30/30 Test #26: sse4_2 ...........................   Passed    0.58 sec

97% tests passed, 1 tests failed out of 30

Total Test time (real) =   0.67 sec

The following tests FAILED:
         29 - avx_intrinsics (Failed)
Errors while running CTest
make: *** [Makefile:91: test] Error 8
```

But if I build the stable version from nixpkgs, then it works

**Comment by OPNA2608** [comment]
The `avx_intrinsics` test was only added with 0.3.0, so pre-0.3.0 working makes sense. If you just want to get past the failure, you can also override `doCheck = false;` (same indentation level as `cmakeFlags`).

As for the error, I couldn't replicate it on my hardware (RK3399 SOC, not an M1 MacBook). Can you check your page size with `getconf PAGESIZE` or `getconf PAGE_SIZE`? There's an upstream issue about the test failing on 16k pagesize systems, maybe this just affects the build on your system in general. As to why it would then work when you build it "manually" (I assume outside of a Nix build, either with `nix-shell`'d tools or using another distro's build tools), I'm not sure. Maybe it's flaky, or something is patched somewhere if you're not using tools from Nix? Hard to say without more details & access to hardware.

**Pull request closed without merging**
