### PR TITLE
dbeaver: 22.2.2 -> 22.2.4

### PR DESCRIPTION
**Pull request by jojosch**
###### Description of changes

https://github.com/dbeaver/dbeaver/releases/tag/22.2.3
https://github.com/dbeaver/dbeaver/releases/tag/22.2.4

-----------------------------------------

Also removed the jdk override for `dbeaver` and `maven`, since `dbeaver` now uses Version 17 by default:

`1 error: org/eclipse/tycho/p2maven/repository/P2ArtifactRepositoryLayout has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0`

https://github.com/dbeaver/dbeaver/commit/53988da10572b2a6bcb7f0577987ba61bae15ad8
https://github.com/dbeaver/dbeaver/tree/22.2.3#prerequisites

-----------------------------------------

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by asbachb** [comment]
Got an error while building locally:
```
buildPhase completed in 19 minutes 50 seconds
installing
error: hash mismatch in fixed-output derivation '/nix/store/i80k2jvzzjxyvl5aj14r80zz91csjy22-dbeaver-22.2.3-maven-deps.drv':
         specified: sha256-4O8Tc3OhrHOtMpAOkvj75OwsVvw+OrOtnQOqks7nO3o=
            got:    sha256-VJ6NtWJ/6ucsoWz3ek8MtgU5wuyFlynK1tbD+M4jVPc=
error: 1 dependencies of derivation '/nix/store/cz5br2gd27fbbvzn3f6cysgfx9jamwz4-dbeaver-22.2.3.drv' failed to build
``` 

Maybe there's a dependency with a range?!

**Comment by ck3d** [comment]
Result of `nixpkgs-review pr 198222` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>dbeaver</li>
  </ul>
</details>

**Comment by PedroHLC** [comment]
@jojosch 22.2.4 is available.

**Comment by marsam** [comment]
There is a mismatch in mvnSha256
```
error: hash mismatch in fixed-output derivation '/nix/store/6d4zymv2i2wpm8yp5g5z3jvy0cc7lmsq-dbeaver-22.2.4-maven-deps.drv':
         specified: sha256-iLNdHcXC1EqWtWd446F1nqfW1FfVpl8c81+fFj0RCgY=
            got:    sha256-lql9tx6oK+XEpxpudHd2IXzdJI//pqPG6CLLUOBDuIg=
```

**Comment by PedroHLC** [comment]
Result of `nixpkgs-review pr 198222` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>dbeaver</li>
  </ul>
</details>

**Review by symphorien — CHANGES_REQUESTED** [review]
a quick looks suggests some dependencies are not pinned in gradle ([eg](https://github.com/dbeaver/dbeaver/blob/devel/product/localRepository/pom.xml#L52)) so the hash will always change. Seems pointless to merge a hash that we will need to update several times a week.

**Pull request closed without merging**
