### PR TITLE
ceph: 18.2.1 -> 18.2.4

### PR DESCRIPTION
**Pull request by nh2**
## Description of changes

Changelog looks good: https://docs.ceph.com/en/latest/releases/reef/#v18-2-4-reef

Also includes the race fix from this for now (without my requested comment improvement)

* #328847

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by nh2** [comment]
Currently building.

**Comment by nh2** [comment]
VM tests pass on x86_64

**Comment by nh2** [comment]
Independent of this PR:

I also suspect that this test step is wrong, and may always have been wrong:

https://github.com/NixOS/nixpkgs/pull/35299#issuecomment-2274876869

**Comment by lejonet** [comment]
> > I also suspect that this test step is wrong, and may always have been wrong:
> 
> I think there's a few oddnesses from back then, but the pool deletion really should fail unless `mon_allow_pool_deletion` is enabled. Perhaps it would be clearer if there was also a test step that must succeed for:
> 
> ```
> ceph tell mon.* injectargs '--mon-allow-pool-delete=true'
> ceph osd pool delete aio-other-test aio-other-test --yes-i-really-really-mean-it
> ```

It would've made sense to add a successful deletion to the test too, that I agree with. But as I wrote in https://github.com/NixOS/nixpkgs/pull/35299#issuecomment-2275609792, the mustFail steps was added for completeness. They can definitively be removed, or the step that @srhb suggested be added to make it actually complete.

**Review by srhb — APPROVED** [review]
LGTM

**Comment by nh2** [comment]
> I pushed a fix for that. It removes the above `ImportError`.

Bah, somehow my push didn't work, and this got merged without the fix... I'll make a new PR for that.

**Pull request merged**
