### PR TITLE
crystal: 1.7 -> 1.8

### PR DESCRIPTION
**Pull request by GeopJr**
###### Description of changes

[Changelog](https://github.com/crystal-lang/crystal/blob/14bfa992ebd9cfa8946a151065dff7eebf829333/CHANGELOG.md?plain=1#L1-L242)

The key changes package-wise are the use of llvm15 and pcre2. I'm not sure if the approach I took is the best one but considering the size of the nix file, I'm leaning towards it than maintaining multiple copies of it for each version.

**Why LLVM 15?**

Crystal 1.8 is the first version with LLVM 15 support which includes opaque pointers. It has performance improvements including an up to 34% speed-up for release builds. You can read more on this great write-up from HertzDevil: https://crystal-lang.org/2023/03/23/llvm-opaque-pointers/

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wegank** [comment]
```
12 packages failed to build:
ameba amqpcat crystal2nix icr invidious kakoune-cr lucky-cli mint oq scry shards thicket

3 packages built:
crystal crystal.bin crystal.lib
```

**Comment by GeopJr** [comment]
I guess not requiring pcre2 directly can't be helped, thanks for running a review!

**Comment by wegank** [comment]
```
1 package failed to build:
ameba

20 packages built:
amqpcat crystal crystal.bin crystal.lib crystal2nix crystal_1_2 crystal_1_2.bin crystal_1_2.lib crystal_1_7 crystal_1_7.bin crystal_1_7.lib icr invidious kakoune-cr lucky-cli mint oq scry shards thicket
```

**Comment by wegank** [comment]
`ameba` requires [this patch](https://github.com/crystal-ameba/ameba/commit/c7f2cba409787a1928fbb54494b4645ec11005cc.patch). Otherwise, LGTM.

**Comment by GeopJr** [comment]
I'll go ahead and tag @straight-shoota in case I missed anything with the LLVM15 + pcre2 migration.

The build and most crystal 1.7 packages succeeded, however while building packages that use the crystal buildCrystalPackage passthru, pcre1 was required:

https://logs.ofborg.org/?attempt_id=01871269-0766-4496-954b-d6cb41723bc1&key=nixos%2Fnixpkgs.226371

```
/nix/store/f4qnwzv6y0nq8lix33jr5ykkyybs6fxf-binutils-2.40/bin/ld: cannot find -lpcre (this usually means you need to install the development package for libpcre): No such file or directory
collect2: error: ld returned 1 exit status
Error: execution of command failed with exit status 1: gcc "${@}" -o /build/source/.crystal/build-source-lib-teeplate-src-lib-file_tree-macros-directory.cr/macro_run  -rdynamic -L/nix/store/8vj98hwkr7glgkdhf345nqlkr5ldywyi-boehm-gc-8.2.2/lib -L/nix/store/pj02km2syw6xc8rdribscls9lpc5g3vr-pcre2-10.42/lib -L/nix/store/mimlcvy3miz847x4icwvi7w8vdn2i3pc-libevent-2.1.12/lib -L/nix/store/xvld1wgp4bj6cscc7in811cnq8k36hb9-libyaml-0.2.5/lib -L/nix/store/2ldgh1qis9p4zf8bgsdm7897gw8vv36g-zlib-1.2.13/lib -L/nix/store/s44s0yzxw4s7nq108css5lcqck6dg6dz-libxml2-2.10.3/lib -L/nix/store/ijk9j536zs30kha06rr966gplwxd7fbg-openssl-3.0.8/lib -lpcre -lm -lgc -lpthread -levent -lrt -lpthread -ldl
```

I just included pcre1 even on the 1.8 builds to fix it, not sure if it's something upstream should be aware of

**Review by wegank — APPROVED** [review]

**Comment by wegank** [comment]
@GeopJr You may want to

- remove `pcre` from `pkgs/development/compilers/crystal/default.nix`, then,
- add `pcre2` to `buildInputs` in `pkgs/development/compilers/crystal/build-package.nix`.

**Comment by GeopJr** [comment]
pcre is needed for crystal < 1.8, the weird part is that even though lucky-cli (and any other latest crystal package that used the passthru) used crystal 1.8 - which uses pcre2 - it needed pcre1

**Comment by straight-shoota** [comment]
I'm not sure it's a good idea to keep `pcre` as a dependency for Crystal 1.8. It should not be necessary unless a package explicitly chooses to use it over `pcre2`. In that case it should be added as a dependency of that particular package, not the `crystal` package.

Also `pcre2` should not be a dependency for older releases. At the most it's useful for 1.7 because you can already opt-in to preview. But older versions have no use of `pcre2`.

About that failing spec, it's a bit hard to trace what exactly is being built there. I suppose it's a nix package for https://github.com/luckyframework/teeplate ? Do you know where that's defined?

**Comment by wegank** [comment]
Just built `lucky-cli` with `pcre2` without any problem. For crystal <1.8 you could just choose the right `pcre` conditionally.

**Comment by GeopJr** [comment]
Just to keep a log of what I have committed:

- initial: pcre was defined as pcre2 on `crystal_1_8` and `crystal` - It prompt the first review to fail on all packages except crystal
- https://github.com/NixOS/nixpkgs/pull/226371/commits/35f5549e29e0056eb379ad8d24475482bfd87d79: pcre2 was included in crystal but pcre1 was only used in crystal < 1.8 and not 1.8 - same issue as the initial
- https://github.com/NixOS/nixpkgs/pull/226371/commits/70cc7966aa62905e6b8f06b1503fb6fe2261fdfc: pcre2 and pcre1 are included - issues got fixed

> About that failing spec, it's a bit hard to trace what exactly is being built there. I suppose it's a nix package for https://github.com/luckyframework/teeplate ? Do you know where that's defined?

I don't think it has to do with teeplate specifically but rather the passthru https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/crystal/build-package.nix since it happens locally for ameba too (the passthru is used to build crystal apps and it deals with their shards (hence treeplate))

> Just built `lucky-cli` with `pcre2` without any problem.

I assume you built it without `pcre` included, right? Because right now it also builds but `pcre` is also required.

> For crystal <1.8 you could just choose the right `pcre` conditionally.

I think the initial commit was the ideal solution - using pcre2 on crystal >= 1.8 and pcre1 on < 1.8, but building crystal packages didn't work, any guidance or suggestions on how to deal with it are welcome!

**Comment by wegank** [comment]
> I assume you built it without `pcre` included, right? Because right now it also builds but `pcre` is also required.

Yes, without `pcre`.

**Pull request merged**
