### PR TITLE
commitmsgfmt: init at 1.6.0

### PR DESCRIPTION
**Pull request by mmlb**
## Description of changes

Adds new package [commitmsgfmt](https://gitlab.com/mkjeldsen/commitmsgfmt)

## Things done

- [x] Built on platform(s)
  - [x] x86_64-linux
- [x] Tested, as applicable:
  - [x] [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by onemoresuza — CHANGES_REQUESTED** [review]
# Reviewed points

Result of `nixpkgs-review pr 249865` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>commitmsgfmt</li>
  </ul>
</details>

- [ ] package path fits guidelines
- [X] package name fits guidelines
- [X] package version fits guidelines
- [X] package builds on x86_64-linux
- [X] executables tested on x86_64-linux
- [X] `meta.description` is set and fits guidelines
- [X] `meta.license` fits upstream license
- [X] `meta.platforms` is set
- [X] `meta.maintainers` is set
- [X] build time only dependencies are declared in `nativeBuildInputs`
- [X] source is fetched using the appropriate function
- [X] the list of `phases` is not overridden
- [ ] `cargoHash256` is used for traditional Nix `SHA-256` hashes

# Possible improvements

1. package path: 
	- Packages should go on [`pkgs/by-name`](https://github.com/NixOS/nixpkgs/blob/cf9a7cd48adb81814dd5d92747a06b4854e5f908/pkgs/by-name/README.md?plain=1#L1). In this case, it would be `pkgs/by-name/co/commitmsgfmt/package.nix`.
	- By moving the `default.nix` file to the mentioned `package.nix` location,
	  there's no need to alter `pkgs/top-level/all-packages.nix`.
1. `cargoHash`: As it is stated on the [nixpkgs manual](https://nixos.org/manual/nixpkgs/stable/#compiling-rust-applications-with-cargo):
	> `buildRustPackage` requires either the `cargoSha256` or the `cargoHash`
	> attribute which is computed over all crate sources of this package.
	> `cargoHash256` is used for traditional Nix SHA-256 hashes, such as the one
	> in the example above. `cargoHash` should instead be used for SRI hashes.

# Comments

1. `meta.platforms` is set by `rustPlatform.buildRustPackage`, so it is set, even though the attribute `meta.platforms` is not present.

**Comment by mmlb** [comment]
@onemoresuza thanks for the review. Fixed the `cargoHash` -> `cargoSha256` and moved to pkgs/by-name. I had done that already while doing the 1.5.0 -> 1.6.0 update but noticed the README say

> Only packages defined using `pkgs.callPackage`.

in https://github.com/NixOS/nixpkgs/tree/d35a953/pkgs/by-name#limitations so kept in the category hierarchy, glad to be able to put it into by-name instead. I rebuilt with --check and had a successful build :+1:.

**Review by onemoresuza — APPROVED** [review]

**Comment by onemoresuza** [comment]
Reposting the reviewed points after the changes

# Reviewed points

Result of `nixpkgs-review pr 249865` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>commitmsgfmt</li>
  </ul>
</details>

- [X] package path fits guidelines
- [X] package name fits guidelines
- [X] package version fits guidelines
- [X] package builds on x86_64-linux
- [X] executables tested on x86_64-linux
- [X] `meta.description` is set and fits guidelines
- [X] `meta.license` fits upstream license
- [X] `meta.platforms` is set
- [X] `meta.maintainers` is set
- [X] build time only dependencies are declared in `nativeBuildInputs`
- [X] source is fetched using the appropriate function
- [X] the list of `phases` is not overridden
- [X] `cargoHash256` is used for traditional Nix `SHA-256` hashes

**Comment by pbsds** [comment]
Result of `nixpkgs-review pr 249865` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>commitmsgfmt</li>
    <li>commitmsgfmt.passthru.tests.version</li>
  </ul>
</details>

Please don't remove the empty checkboxes from the pull template in the future. Committers may like to be able to mark them checked as they review

**Pull request merged**
