### PR TITLE
php84: init at 8.4.0alpha1

### PR DESCRIPTION
**Pull request by drupol**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by drupol** [comment]
@ofborg build php82 php83 php84

**Comment by drupol** [comment]
@ofborg build php82 php83 php84

**Comment by drupol** [comment]
@ofborg build php82 php83 php84

**Comment by drupol** [comment]
@ofborg build php82 php83 php84

**Comment by drupol** [comment]
@ofborg build php82 php83 php84

**Review by Ma27 — COMMENTED** [review]
Update itself looks good, also the changes for 8.2/8.3

I don't really understand the blackfire fix attempt: it seems to be mixed with reformatting making a review kinda hard.

Btw what are your plans for backport? 8.2/8.3 only I guess?

**Comment by drupol** [comment]
> I don't really understand the blackfire fix attempt: it seems to be mixed with reformatting making a review kinda hard.

I removed the fix, check again now ;)

> Btw what are your plans for backport? 8.2/8.3 only I guess?

I guess yes.

**Comment by Ma27** [comment]
Eh noticed just now, apcu on 8.4[1] apcu fails on tests:

```
=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
APC: apcu_entry (exception) [tests/apc_entry_002.phpt]
=====================================================================
```

[1] I'm still somehow used to typing 7.4 here oO

**Comment by drupol** [comment]
> Eh noticed just now, apcu on 8.4[1] apcu fails on tests:
> 
> ```
> =====================================================================
> FAILED TEST SUMMARY
> ---------------------------------------------------------------------
> APC: apcu_entry (exception) [tests/apc_entry_002.phpt]
> =====================================================================
> ```
> 
> [1] I'm still somehow used to typing 7.4 here oO

I can build `php84` locally without any trouble. What trigger this issue on your side?

**Comment by piotrkwiecinski** [comment]
@drupol I seem to have the same issue:
```
       last 25 log lines:
       > Exts skipped    :     0
       > Exts tested     :    12
       > ---------------------------------------------------------------------
       >
       > Number of tests :    68                56
       > Tests skipped   :    12 ( 17.6%) --------
       > Tests warned    :     0 (  0.0%) (  0.0%)
       > Tests failed    :     1 (  1.5%) (  1.8%)
       > Tests passed    :    55 ( 80.9%) ( 98.2%)
       > ---------------------------------------------------------------------
       > Time taken      : 1.617 seconds
       > =====================================================================
       >
       > =====================================================================
       > FAILED TEST SUMMARY
       > ---------------------------------------------------------------------
       > APC: apcu_entry (exception) [tests/apc_entry_002.phpt]
       > =====================================================================
       >
       > You may have found a problem in PHP.
       > This report can be saved and used to open an issue on the bug tracker at
       > https://github.com/php/php-src/issues
       > This gives us a better understanding of PHP's behavior.
       > Do you want to save this report in a file? [Yn]: Report saved to: /build/source/php_test_results_20240706_0922.txt
```
I run it locally using:

```
nix-shell -p nixpkgs-review --run "nixpkgs-review pr 324831"       
```

On Ubuntu with Nix installed.

**Comment by Ma27** [comment]
> I can build php84 locally without any trouble. What trigger this issue on your side?

`nix-build -A nixosTests.php84`

But I'll try to run it on a few different machines a few times then. Perhaps it's just a flaky test.

**Comment by Ma27** [comment]
The drv path is btw `/nix/store/65jjlpx4aanccnqdl2z7in2sq4l9rxrc-php-apcu-5.1.23.drv`.

Can reproduce this on my laptop (also with limited to one core for building) and two more builders.

**Comment by drupol** [comment]
@Ma27 What's the issue with the test? I can't find what's wrong now.

**Comment by Ma27** [comment]
I haven't tested it with your last commit that apparently fixes apcu :)
Can do so later

**Comment by Ma27** [comment]
Hmm, for some reason I now get

```
=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
APC: Bug #61742 preload_path does not work due to incorrect string length (variant 1) [tests/apc54_014.phpt]
=====================================================================
```

Is that what you meant?

**Comment by drupol** [comment]
What command are you running now ?

**Comment by Ma27** [comment]
Same as before, `nix-build -A nixosTests.php84`.
Problematic drv is `/nix/store/7ffc7sn72bx27nqni94rblyz1ihfvgsr-php-apcu-5.1.23.drv`.

Reproducible on three distinct builders.

**Comment by drupol** [comment]
Tests are depending on the APCU extension. What should we do here?

**Comment by Ma27** [comment]
> What should we do here?

I will go to sleep now ;-) 

But to be serious, this seems like a timing problem inside the test-suite: the one test only started to fail after you disabled the other one.
Hence, it probably makes sense to see what happens if you also skip this test and report the problem upstream.

**Comment by jtojnar** [comment]
I can reproduce, looks like the difference is that tests require ZTS, which fails for some reason:

```ShellSession
$ nix-diff $(nix-instantiate -A php84.extensions.apcu) /nix/store/97wzzn3qm4m0sbs1a8rwf7rwh8f3xpji-php-apcu-5.1.23.drv
- /nix/store/nkisn0jd51kvshvj4y51kdq8lqnd46d1-php-apcu-5.1.23.drv:{out}
+ /nix/store/97wzzn3qm4m0sbs1a8rwf7rwh8f3xpji-php-apcu-5.1.23.drv:{out}
• The input derivation named `php-8.4.0alpha4` differs
  - /nix/store/d7sbh5gx3wsi04jfwd61ilyph0pnm940-php-8.4.0alpha4.drv:{dev}
  + /nix/store/a1fpjby6b62jkmh73v65addfga0lqsjf-php-8.4.0alpha4.drv:{dev}
  • The set of input derivation names do not match:
      + apache-httpd-2.4.62
  • The environments do not match:
      buildInputs=''
      /nix/store/vj24v820wgahp8v8zys2gh4r7929rq57-pcre2-10.44-dev /nix/store/v5iqpidgngl4wrm2j0a198803qg2y247-libxml2-2.13.3-dev /nix/store/76g3ni9yfl7fjkz8m2fa20qsmq8i8vij-apache-httpd-2.4.62 /nix/store/8mj87xvw7fp4q259a8nn45fq6gx9zxb2-libargon2-20190702 /nix/store/3944pvqb1myhck3phdvbzf5znkaz77i9-systemd-256.4-dev /nix/store/9rmilswvkcwbkl2jy0indm9gvn65ijgd-valgrind-3.23.0-dev
  ''
      configureFlags=''
      --disable-all --with-external-pcre=/nix/store/vj24v820wgahp8v8zys2gh4r7929rq57-pcre2-10.44-dev --enable-fpm --with-pear --enable-xml --with-libxml --enable-phar --with-apxs2=/nix/store/j8mbic5wavrh0wh9pckw48wymly45m8i-apache-httpd-2.4.62-dev/bin/apxs --with-password-argon2=/nix/store/8mj87xvw7fp4q259a8nn45fq6gx9zxb2-libargon2-20190702 --with-fpm-systemd --with-valgrind=/nix/store/9rmilswvkcwbkl2jy0indm9gvn65ijgd-valgrind-3.23.0-dev --enable-zts PROG_SENDMAIL=/nix/store/3b2bib0b4794jvkvw5f6g5kw24glg94p-system-sendmail-1.0/bin/sendmail
  ''
```

Looks like the failing test just returns `false` for all values:

<details>
<summary>Test output diff</summary>

```ShellSession
$ cat /tmp/nix-build-php-apcu-5.1.23.drv-0/build/source/tests/apc54_014.diff
001- bool(true)
002- string(3) "123"
003- bool(true)
004- string(3) "123"
005- bool(true)
006- string(3) "123"
007- bool(true)
008- string(3) "123"
009- bool(true)
010- string(3) "123"
011- bool(true)
012- string(3) "123"
013- bool(true)
014- string(3) "123"
015- bool(true)
016- string(3) "123"
017- bool(true)
018- string(3) "123"
019- bool(true)
020- string(3) "123"
021- bool(true)
022- string(3) "123"
023- bool(true)
024- string(3) "123"
025- bool(true)
026- string(3) "123"
027- bool(true)
028- string(3) "123"
029- bool(true)
030- string(3) "123"
031- bool(true)
032- string(3) "123"
033- bool(true)
034- string(3) "123"
035- bool(true)
036- string(3) "123"
037- bool(true)
038- string(3) "123"
039- bool(true)
040- string(3) "123"
041- bool(true)
042- string(3) "123"
043- bool(true)
044- string(3) "123"
045- bool(true)
046- string(3) "123"
047- bool(true)
048- string(3) "123"
049- bool(true)
050- string(3) "123"
051- bool(true)
052- string(3) "123"
053- bool(true)
054- string(3) "123"
055- bool(true)
056- string(3) "123"
057- bool(true)
058- string(3) "123"
059- bool(true)
060- string(3) "123"
001+ bool(false)
002+ bool(false)
003+ bool(false)
004+ bool(false)
005+ bool(false)
006+ bool(false)
007+ bool(false)
008+ bool(false)
009+ bool(false)
010+ bool(false)
011+ bool(false)
012+ bool(false)
013+ bool(false)
014+ bool(false)
015+ bool(false)
016+ bool(false)
017+ bool(false)
018+ bool(false)
019+ bool(false)
020+ bool(false)
021+ bool(false)
022+ bool(false)
023+ bool(false)
024+ bool(false)
025+ bool(false)
026+ bool(false)
027+ bool(false)
028+ bool(false)
029+ bool(false)
030+ bool(false)
     done
```

</details>

But the test is not supposed to run:

https://github.com/krakjoe/apcu/blob/2b0e77929196553cce926f93c5c5cf61f46022d2/tests/apc54_014.phpt#L6

Apparently, `PHP_ZTS` constant now contains `true` instead of `1` so the strict comparison that would skip the test fails.

**Comment by jtojnar** [comment]
IMAP and pspell extensions were dropped from source in favour of PECL, so I switched them to that. pspell builds fine with all PHP versions in Nixpkgs but imap does not build with 8.1 or 8.2 so I kept the vendored ext for them.

**Comment by jtojnar** [comment]
APCU fix was merged, `nixosTests.php84` now pass. I think this is ready.

Will ignore by-name for now since it would require re-architecting of the PHP packaging.

**Comment by piotrkwiecinski** [comment]
Result of `nixpkgs-review pr 324831` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>php84Extensions.openssl-legacy</li>
    <li>php84Extensions.openssl-legacy.dev</li>
  </ul>
</details>
<details>
  <summary>15 packages failed to build:</summary>
  <ul>
    <li>php83Packages.castor</li>
    <li>php84Extensions.couchbase</li>
    <li>php84Extensions.datadog_trace</li>
    <li>php84Extensions.ioncube-loader</li>
    <li>php84Extensions.opentelemetry</li>
    <li>php84Extensions.pcov</li>
    <li>php84Extensions.pdo_oci</li>
    <li>php84Extensions.phalcon</li>
    <li>php84Extensions.redis</li>
    <li>php84Extensions.snuffleupagus</li>
    <li>php84Extensions.spx</li>
    <li>php84Extensions.vld</li>
    <li>php84Extensions.xdebug</li>
    <li>php84Packages.castor</li>
    <li>php84Packages.psalm</li>
  </ul>
</details>
<details>
  <summary>203 packages built:</summary>
  <ul>
    <li>firefly-iii</li>
    <li>php81Extensions.apcu</li>
    <li>php81Extensions.apcu.dev</li>
    <li>php81Extensions.pdo_dblib</li>
    <li>php81Extensions.pdo_dblib.dev</li>
    <li>php81Extensions.pspell</li>
    <li>php81Extensions.snmp</li>
    <li>php81Extensions.snmp.dev</li>
    <li>php82Extensions.apcu</li>
    <li>php82Extensions.apcu.dev</li>
    <li>php82Extensions.pdo_dblib</li>
    <li>php82Extensions.pdo_dblib.dev</li>
    <li>php82Extensions.pspell</li>
    <li>php82Extensions.snmp</li>
    <li>php82Extensions.snmp.dev</li>
    <li>php83</li>
    <li>php83Extensions.apcu</li>
    <li>php83Extensions.apcu.dev</li>
    <li>php83Extensions.imap</li>
    <li>php83Extensions.pdo_dblib</li>
    <li>php83Extensions.pdo_dblib.dev</li>
    <li>php83Extensions.pspell</li>
    <li>php83Extensions.snmp</li>
    <li>php83Extensions.snmp.dev</li>
    <li>php83Packages.composer</li>
    <li>php83Packages.composer-local-repo-plugin</li>
    <li>php83Packages.cyclonedx-php-composer</li>
    <li>php83Packages.deployer</li>
    <li>php83Packages.grumphp</li>
    <li>php83Packages.phan</li>
    <li>php83Packages.phing</li>
    <li>php83Packages.phive</li>
    <li>php83Packages.php-codesniffer</li>
    <li>php83Packages.php-cs-fixer</li>
    <li>php83Packages.php-parallel-lint</li>
    <li>php83Packages.phpinsights</li>
    <li>php83Packages.phpmd</li>
    <li>php83Packages.phpstan</li>
    <li>php83Packages.psalm</li>
    <li>php83Packages.psysh</li>
    <li>php84</li>
    <li>php84Extensions.amqp</li>
    <li>php84Extensions.apcu</li>
    <li>php84Extensions.apcu.dev</li>
    <li>php84Extensions.ast</li>
    <li>php84Extensions.bcmath</li>
    <li>php84Extensions.bcmath.dev</li>
    <li>php84Extensions.bz2</li>
    <li>php84Extensions.bz2.dev</li>
    <li>php84Extensions.calendar</li>
    <li>php84Extensions.calendar.dev</li>
    <li>php84Extensions.ctype</li>
    <li>php84Extensions.ctype.dev</li>
    <li>php84Extensions.curl</li>
    <li>php84Extensions.curl.dev</li>
    <li>php84Extensions.dba</li>
    <li>php84Extensions.dba.dev</li>
    <li>php84Extensions.dom</li>
    <li>php84Extensions.dom.dev</li>
    <li>php84Extensions.ds</li>
    <li>php84Extensions.enchant</li>
    <li>php84Extensions.enchant.dev</li>
    <li>php84Extensions.event</li>
    <li>php84Extensions.exif</li>
    <li>php84Extensions.exif.dev</li>
    <li>php84Extensions.ffi</li>
    <li>php84Extensions.ffi.dev</li>
    <li>php84Extensions.fileinfo</li>
    <li>php84Extensions.fileinfo.dev</li>
    <li>php84Extensions.filter</li>
    <li>php84Extensions.filter.dev</li>
    <li>php84Extensions.ftp</li>
    <li>php84Extensions.ftp.dev</li>
    <li>php84Extensions.gd</li>
    <li>php84Extensions.gd.dev</li>
    <li>php84Extensions.gettext</li>
    <li>php84Extensions.gettext.dev</li>
    <li>php84Extensions.gmp</li>
    <li>php84Extensions.gmp.dev</li>
    <li>php84Extensions.gnupg</li>
    <li>php84Extensions.grpc</li>
    <li>php84Extensions.iconv</li>
    <li>php84Extensions.iconv.dev</li>
    <li>php84Extensions.igbinary</li>
    <li>php84Extensions.igbinary.dev</li>
    <li>php84Extensions.imagick</li>
    <li>php84Extensions.imap</li>
    <li>php84Extensions.inotify</li>
    <li>php84Extensions.intl</li>
    <li>php84Extensions.intl.dev</li>
    <li>php84Extensions.ldap</li>
    <li>php84Extensions.ldap.dev</li>
    <li>php84Extensions.mailparse</li>
    <li>php84Extensions.maxminddb</li>
    <li>php84Extensions.mbstring</li>
    <li>php84Extensions.mbstring.dev</li>
    <li>php84Extensions.memcache</li>
    <li>php84Extensions.memcached</li>
    <li>php84Extensions.meminfo</li>
    <li>php84Extensions.memprof</li>
    <li>php84Extensions.mongodb</li>
    <li>php84Extensions.msgpack</li>
    <li>php84Extensions.mysqli</li>
    <li>php84Extensions.mysqli.dev</li>
    <li>php84Extensions.mysqlnd</li>
    <li>php84Extensions.mysqlnd.dev</li>
    <li>php84Extensions.oci8</li>
    <li>php84Extensions.opcache</li>
    <li>php84Extensions.opcache.dev</li>
    <li>php84Extensions.openssl</li>
    <li>php84Extensions.openssl.dev</li>
    <li>php84Extensions.openswoole</li>
    <li>php84Extensions.pcntl</li>
    <li>php84Extensions.pcntl.dev</li>
    <li>php84Extensions.pdlib</li>
    <li>php84Extensions.pdo</li>
    <li>php84Extensions.pdo.dev</li>
    <li>php84Extensions.pdo_dblib</li>
    <li>php84Extensions.pdo_dblib.dev</li>
    <li>php84Extensions.pdo_mysql</li>
    <li>php84Extensions.pdo_mysql.dev</li>
    <li>php84Extensions.pdo_odbc</li>
    <li>php84Extensions.pdo_odbc.dev</li>
    <li>php84Extensions.pdo_pgsql</li>
    <li>php84Extensions.pdo_pgsql.dev</li>
    <li>php84Extensions.pdo_sqlite</li>
    <li>php84Extensions.pdo_sqlite.dev</li>
    <li>php84Extensions.pdo_sqlsrv</li>
    <li>php84Extensions.pgsql</li>
    <li>php84Extensions.pgsql.dev</li>
    <li>php84Extensions.pinba</li>
    <li>php84Extensions.posix</li>
    <li>php84Extensions.posix.dev</li>
    <li>php84Extensions.protobuf</li>
    <li>php84Extensions.pspell</li>
    <li>php84Extensions.rdkafka</li>
    <li>php84Extensions.readline</li>
    <li>php84Extensions.readline.dev</li>
    <li>php84Extensions.rrd</li>
    <li>php84Extensions.session</li>
    <li>php84Extensions.session.dev</li>
    <li>php84Extensions.shmop</li>
    <li>php84Extensions.shmop.dev</li>
    <li>php84Extensions.simplexml</li>
    <li>php84Extensions.simplexml.dev</li>
    <li>php84Extensions.smbclient</li>
    <li>php84Extensions.snmp</li>
    <li>php84Extensions.snmp.dev</li>
    <li>php84Extensions.soap</li>
    <li>php84Extensions.soap.dev</li>
    <li>php84Extensions.sockets</li>
    <li>php84Extensions.sockets.dev</li>
    <li>php84Extensions.sodium</li>
    <li>php84Extensions.sodium.dev</li>
    <li>php84Extensions.sqlite3</li>
    <li>php84Extensions.sqlite3.dev</li>
    <li>php84Extensions.sqlsrv</li>
    <li>php84Extensions.ssh2</li>
    <li>php84Extensions.swoole</li>
    <li>php84Extensions.sysvmsg</li>
    <li>php84Extensions.sysvmsg.dev</li>
    <li>php84Extensions.sysvsem</li>
    <li>php84Extensions.sysvsem.dev</li>
    <li>php84Extensions.sysvshm</li>
    <li>php84Extensions.sysvshm.dev</li>
    <li>php84Extensions.tidy</li>
    <li>php84Extensions.tidy.dev</li>
    <li>php84Extensions.tokenizer</li>
    <li>php84Extensions.tokenizer.dev</li>
    <li>php84Extensions.uv</li>
    <li>php84Extensions.xml</li>
    <li>php84Extensions.xml.dev</li>
    <li>php84Extensions.xmlreader</li>
    <li>php84Extensions.xmlreader.dev</li>
    <li>php84Extensions.xmlwriter</li>
    <li>php84Extensions.xmlwriter.dev</li>
    <li>php84Extensions.xsl</li>
    <li>php84Extensions.xsl.dev</li>
    <li>php84Extensions.yaml</li>
    <li>php84Extensions.zend_test</li>
    <li>php84Extensions.zend_test.dev</li>
    <li>php84Extensions.zip</li>
    <li>php84Extensions.zip.dev</li>
    <li>php84Extensions.zlib</li>
    <li>php84Extensions.zlib.dev</li>
    <li>php84Extensions.zstd</li>
    <li>php84Packages.box</li>
    <li>php84Packages.composer</li>
    <li>php84Packages.composer-local-repo-plugin</li>
    <li>php84Packages.cyclonedx-php-composer</li>
    <li>php84Packages.deployer</li>
    <li>php84Packages.grumphp</li>
    <li>php84Packages.phan</li>
    <li>php84Packages.phing</li>
    <li>php84Packages.phive</li>
    <li>php84Packages.php-codesniffer</li>
    <li>php84Packages.php-cs-fixer</li>
    <li>php84Packages.php-parallel-lint</li>
    <li>php84Packages.phpinsights</li>
    <li>php84Packages.phpmd</li>
    <li>php84Packages.phpspy</li>
    <li>php84Packages.phpstan</li>
    <li>php84Packages.psysh</li>
  </ul>
</details>

Redis ext has some fixes for 8.4 but it's RC https://pecl.php.net/package-info.php?package=redis&version=6.1.0RC1

Overall it's a good starting point

**Review by piotrkwiecinski — APPROVED** [review]

**Pull request merged**
