### PR TITLE
nodePackages: add more coc-nvim extensions

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change
This is #106621 de-novo

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113945` at 067ed4b6 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages marked as broken and skipped:</summary>
  <ul>
    <li>python39Packages.batchspawner</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.jupyterhub</li>
    <li>python39Packages.jupyterhub-ldapauthenticator</li>
    <li>python39Packages.jupyterhub-systemdspawner</li>
    <li>python39Packages.jupyterhub-tmpauthenticator</li>
    <li>python39Packages.oauthenticator</li>
  </ul>
</details>
<details>
  <summary>19 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/464c90c119fc59fd2d580870d8ad3f3f">parity-ui</a></li></li>
    <li><a href="https://gist.github.com/bcb21e048cf7e1f6d2ad6971b88dd33a">python37Packages.batchspawner</a></li></li>
    <li><a href="https://gist.github.com/16c26336f5fed8303b618d6802d6849f">python37Packages.dockerspawner</a></li></li>
    <li><a href="https://gist.github.com/4f904419bb902410a77ff48748cb40b2">python37Packages.jupyterhub</a></li></li>
    <li><a href="https://gist.github.com/e94bd085fdd749146928062e21e536eb">python37Packages.jupyterhub-ldapauthenticator</a></li></li>
    <li><a href="https://gist.github.com/5cf0c72f6ec0f5d20364d413b8131c9c">python37Packages.jupyterhub-systemdspawner</a></li></li>
    <li><a href="https://gist.github.com/04984aa5145bc8e385c826c970119f34">python37Packages.jupyterhub-tmpauthenticator</a></li></li>
    <li><a href="https://gist.github.com/4532ce8765d26c123103da7928661326">python37Packages.oauthenticator</a></li></li>
    <li><a href="https://gist.github.com/6409ce65d4aa4377d79d430fba798b26">python38Packages.batchspawner</a></li></li>
    <li><a href="https://gist.github.com/64f8148a8cdb430410ca62ad9a0b3c29">python38Packages.dockerspawner</a></li></li>
    <li><a href="https://gist.github.com/d014ac3574c2ace78c7920cfbc941b4c">python38Packages.jupyterhub</a></li></li>
    <li><a href="https://gist.github.com/a5b79a118f68600918812f5e86f72b3d">python38Packages.jupyterhub-ldapauthenticator</a></li></li>
    <li><a href="https://gist.github.com/40e877ac69cf9238b9c03e8bb828a82d">python38Packages.jupyterhub-systemdspawner</a></li></li>
    <li><a href="https://gist.github.com/f602a25fcbb73fa87d209c5d86b4807d">python38Packages.jupyterhub-tmpauthenticator</a></li></li>
    <li><a href="https://gist.github.com/6ce780601532fe90fce6e547c4e53789">python38Packages.oauthenticator</a></li></li>
    <li><a href="https://gist.github.com/6ebda2d99b0a421d1a5183d0680bf393">styx</a></li></li>
    <li><a href="https://gist.github.com/a42b91c3a0088cea69cce6c5c30ad3a6">teleprompter</a></li></li>
    <li><a href="https://gist.github.com/6e957f56b83724e943b74a269f73997a">vscode-extensions.matklad.rust-analyzer</a></li></li>
    <li><a href="https://gist.github.com/ab1758add23508f088c328e24c355d99">vscode-extensions.vadimcn.vscode-lldb</a></li></li>
  </ul>
</details>

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 113945` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>image_optim</li>
    <li>python39Packages.batchspawner</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.jupyterhub</li>
    <li>python39Packages.jupyterhub-ldapauthenticator</li>
    <li>python39Packages.jupyterhub-systemdspawner</li>
    <li>python39Packages.jupyterhub-tmpauthenticator</li>
    <li>python39Packages.oauthenticator</li>
  </ul>
</details>
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>netlify-cli</li>
    <li>python37Packages.batchspawner</li>
    <li>python37Packages.dockerspawner</li>
    <li>python37Packages.jupyterhub</li>
    <li>python37Packages.jupyterhub-ldapauthenticator</li>
    <li>python37Packages.jupyterhub-systemdspawner</li>
    <li>python37Packages.jupyterhub-tmpauthenticator</li>
    <li>python37Packages.oauthenticator</li>
  </ul>
</details>
<details>
  <summary>39 packages built:</summary>
  <ul>
    <li>bitwarden-cli</li>
    <li>castnow</li>
    <li>create-cycle-app</li>
    <li>emojione</li>
    <li>epgstation</li>
    <li>etcher</li>
    <li>gtop</li>
    <li>iosevka</li>
    <li>joplin</li>
    <li>lessc</li>
    <li>lumo</li>
    <li>mastodon-bot</li>
    <li>mirakurun</li>
    <li>parity-ui</li>
    <li>pm2</li>
    <li>pscid</li>
    <li>pulp</li>
    <li>python38Packages.batchspawner</li>
    <li>python38Packages.dockerspawner</li>
    <li>python38Packages.jupyterhub</li>
    <li>python38Packages.jupyterhub-ldapauthenticator</li>
    <li>python38Packages.jupyterhub-systemdspawner</li>
    <li>python38Packages.jupyterhub-tmpauthenticator</li>
    <li>python38Packages.oauthenticator</li>
    <li>redoc-cli</li>
    <li>slack</li>
    <li>sloc</li>
    <li>styx</li>
    <li>teleprompter</li>
    <li>thelounge</li>
    <li>triton</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-prettier</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>wasm-text-gen</li>
  </ul>
</details>

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 113945` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>image_optim</li>
    <li>python39Packages.batchspawner</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.jupyterhub</li>
    <li>python39Packages.jupyterhub-ldapauthenticator</li>
    <li>python39Packages.jupyterhub-systemdspawner</li>
    <li>python39Packages.jupyterhub-tmpauthenticator</li>
    <li>python39Packages.oauthenticator</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>netlify-cli</li>
  </ul>
</details>
<details>
  <summary>46 packages built:</summary>
  <ul>
    <li>bitwarden-cli</li>
    <li>castnow</li>
    <li>create-cycle-app</li>
    <li>emojione</li>
    <li>epgstation</li>
    <li>etcher</li>
    <li>gtop</li>
    <li>iosevka</li>
    <li>joplin</li>
    <li>lessc</li>
    <li>lumo</li>
    <li>mastodon-bot</li>
    <li>mirakurun</li>
    <li>parity-ui</li>
    <li>pm2</li>
    <li>pscid</li>
    <li>pulp</li>
    <li>python37Packages.batchspawner</li>
    <li>python37Packages.dockerspawner</li>
    <li>python37Packages.jupyterhub</li>
    <li>python37Packages.jupyterhub-ldapauthenticator</li>
    <li>python37Packages.jupyterhub-systemdspawner</li>
    <li>python37Packages.jupyterhub-tmpauthenticator</li>
    <li>python37Packages.oauthenticator</li>
    <li>python38Packages.batchspawner</li>
    <li>python38Packages.dockerspawner</li>
    <li>python38Packages.jupyterhub</li>
    <li>python38Packages.jupyterhub-ldapauthenticator</li>
    <li>python38Packages.jupyterhub-systemdspawner</li>
    <li>python38Packages.jupyterhub-tmpauthenticator</li>
    <li>python38Packages.oauthenticator</li>
    <li>redoc-cli</li>
    <li>slack</li>
    <li>sloc</li>
    <li>styx</li>
    <li>teleprompter</li>
    <li>thelounge</li>
    <li>triton</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-prettier</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>wasm-text-gen</li>
  </ul>
</details>

**Comment by lovesegfault** [comment]
`netlify-cli` is broken in master too

**Comment by lovesegfault** [comment]
This is low risk and has a high chance of getting merge conflicts, so I'm going to go ahead and merge it.

**Pull request merged**
