### PR TITLE
php: bumps (security release)

### PR DESCRIPTION
**Pull request by drupol**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by drupol** [comment]
@GrahamcOfBorg build php74
@GrahamcOfBorg build php80
@GrahamcOfBorg build php81
@GrahamcOfBorg test php74
@GrahamcOfBorg test php80
@GrahamcOfBorg test php81

**Review by ajs124 — APPROVED** [review]

**Comment by risicle** [comment]
`qcachegrind` failure on macos is pre-existing. `php81` opcache failure appears just flaky. Failed for me first time then passed second, macos 10.15.

**Comment by drupol** [comment]
> `qcachegrind` failure on macos is pre-existing. `php81` opcache failure appears just flaky. Failed for me first time then passed second, macos 10.15.

Do you think we should report that to the PHP dec team ?

**Comment by etu** [comment]
The `qcachegrind` failures has been around in nix for as long as I can remember, it's also not a project maintained by the php community (as far as I know). Last update of it seemed to be 2014: https://sourceforge.net/projects/qcachegrindwin/ wow.

Maybe we should drop that package? Fails to build and isn't updated. This isn't a software graveyard.

The `opcache` extension however is an upstream extension (had to check this, I thought it was a pecl, but that changed in 5.5.0, shows my age I guess). So for that one it could be worth to investigate and maybe report if we find something of value.

**Comment by ajs124** [comment]
Backport is in #161252

**Comment by drupol** [comment]
Dear @@NixOS/darwin-maintainers, can you help use debugging why we are unable to build PHP on Darwin? See relevant logs here: https://github.com/NixOS/nixpkgs/pull/161038/checks?check_run_id=5264046889

**Pull request merged**
