### PR TITLE
patch-shebangs: respect cross compilation for 18.09

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

This is a version of https://github.com/NixOS/nixpkgs/pull/43833 made more conservative to *only* affect cross builds (well, anything enabling `strictDeps`). I hope that makes it conservative enough to land in 18.09. Sorry I didn't make this earlier, pre-fork.

The idea is that if `strictDeps` isn't defined, `HOST_PATH` is defined exactly the same as `PATH`. This means that `patchShebangs`, `patchShebangs --build`, and `patchShebangs --host` are all defined the same as each other and as `patchShebangs` is today.

I still like @matthewbauer's version for `staging` and 19.03 and beyond. The breakage it creates points us to things worth fixing, just not as part of the 18.09 deadline!

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
Maybe we should merge #43833 first just to make sure the changes work. I don't want to break patch shebangs in 18.09. This can be backported a little bit later.

**Comment by Ericson2314** [comment]
@matthewbauer err you mean merge this into `staging` first? Your can indeed break native builds, but this is only capable of breaking cross builds which somehow relied on the broken behavior.

**Comment by Ericson2314** [comment]
OK I think I see. It's fine if `staging` breaks a little since we want to fix the misbehaving packages anyways, and we still get some sanity checking of does the code do the right thing. :+1:.

**Review by matthewbauer — APPROVED** [review]
Looks good to go now.

**Comment by Ericson2314** [comment]
Alright!

**Comment by Ericson2314** [comment]
Changed the order so that https://github.com/NixOS/nixpkgs/pull/46542 for regular `staging` can share a commit.

**Comment by matthewbauer** [comment]
@Ericson2314 Looking at this now, I think I have found a bug in this. Lots of packages have bash scripts in their outputs but don't directly list bash as an input. Instead they get it from ```initialPath```. But initialPath goes into PATH but not HOST_PATH. We need to find a way to make sure that a runtime Bash gets in HOST_PATH. I think defaultBuildInputs is the easiest way to go.

But for now, this will break in unexpected ways. I am going to revert this in staging-18.09 just to be safe.

**Comment by Ericson2314** [comment]
Ah man, all those little corner cases. Sure complicates everything. Good catch

**Pull request merged**
