### PR TITLE
nginx: fix URLs by taking from a specific commit

### PR DESCRIPTION
**Pull request by Twey**
I'm not sure this is the best way to get these patches, but it's better than `master` (at commit https://github.com/openwrt/packages/commit/e9617f553284b170a8b520d051ac1fc1b83cff30 these patches moved into a `nginx` subdirectory, breaking the build unless the patches are cached).

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Twey** [comment]
(build is untested as it is identical to the latest working build)

**Comment by Artturin** [comment]
Mind checking if a backport to 21.05 is needed?

**Comment by Twey** [comment]
Yes, 21.05 seems to have the same problem.  I don't know what the process for backports is but the patch applies cleanly — if you need me to do something please let me know.

**Comment by Twey** [comment]
Thank you @Artturin!

**Pull request merged**
