### PR TITLE
Separate truely top-level code from per-bootstrapping-stage code

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

I think `top-level` was getting a but unwieldy. With this change:

 - Truely top level stays in pkgs/top-level
 - Per-bootstrapping-stage goes in pkgs/stage

###### Things done

Gonna let Travis test this one

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by copumpkin** [comment]
Renaming files that everyone uses is going to break almost every open PR or branch...

**Comment by Ericson2314** [comment]
Hmm git itself can easily deal with renamed files, but github isn't so clever.

**Comment by FRidh** [comment]
Is there an overview of what the desired structure of the top-level functions and repository layout is?

In my opinion we should just move `python-packages.nix` to `pkgs/development/python-modules/default.nix`.

**Comment by Ericson2314** [comment]
@FRidh this is my own vison, if you will :). If you see how I split `top-level/default.nix` into `top-level/stage.nix` in #15043, this is finishing the job.

**Comment by nbp** [comment]
These are not stages, but collections / indexes of packages.
The stages would be the steps taken by the top-level to aggregate stdenv and others.

I think `pkgs/indexes/node-packages.nix` makes more sense than `pkgs/stages/node-packages.nix`.
Also, if all these indexes / collections are suffixed by `-packages`, maybe we should move this particle to the directory name, if it is not explicit yet, such as `pkgs/indexes/npm.nix`, `pkgs/indexes/pip.nix`, `pkgs/indexes/cabal.nix` ?

What do you think?

**Comment by Ericson2314** [comment]
@nbp I like it! While yes `stage/default.nix` computes a single bootstrapping stage, that involves little more than aggregating the indices. And certainly everything else in there is an index that just happens to be used for computing a single stage—and it's better to label our "nouns" by what they are than how they are used.

I'll change this PR accordingly in a few minites, and also change the documentation in now-called `indices/default.nix` to philosophicly align.

**Comment by Ericson2314** [comment]
Not sure if I'm actually causing some sort of pythonic mass rebuild, or Travis was just having a bad day.

**Comment by mmahut** [comment]
Any update on this pull request?

**Comment by FRidh** [comment]
I think moving the package sets into their own folder is not a bad idea, although it's a pain when going through the history. if we would do this, then may as well create a new commit and PR.

**Pull request closed without merging**
