### PR TITLE
tinycdb: add support for static build

### PR DESCRIPTION
**Pull request by KAction**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by tomberek — APPROVED** [review]

**Comment by KAction** [comment]
@tomberek  Can we merge?

**Comment by tomberek** [comment]
@KAction I don't have merge permissions. But as i'm looking at this again, the normal build still works as expected, but i am not able to get the static build working.

I tried `nix-build -A pkgsStatic.tinycdb`, my expectation was that this would create a static version, but it fails with:
```
 setting SOURCE_DATE_EPOCH to timestamp 1336746967 of file tinycdb-0.78/debian/rules
  patching sources
  updateAutotoolsGnuConfigScriptsPhase
  configuring
  no configure script, doing nothing
  building
  build flags: SHELL=/nix/store/2jysm3dfsgby5sw5jgj43qjrb5v79ms9-bash-4.4-p23/bin/bash prefix=\$\(out\) CC=cc AR=ar RANLIB=ranlib static
  cc -O -D_FILE_OFFSET_BITS=64 -c cdb_init.c
  /nix/store/2jysm3dfsgby5sw5jgj43qjrb5v79ms9-bash-4.4-p23/bin/bash: cc: command not found
```

The build logic may work for a cross compilation to static, i did not test that.

**Comment by KAction** [comment]
@tomberek It looks like I messed up build/target/host distinction. Not sure why it worked for me previously. Anyway, should be fine now.

**Comment by ryantm** [comment]
Confirmed `nix-build -A pkgsStatic.tinycdb` works.

**Comment by ryantm** [comment]
Result of `nixpkgs-review pr 97386` [1](https://github.com/Mic92/nixpkgs-review)

**Comment by ryantm** [comment]
@GrahamcOfBorg eval

**Comment by ryantm** [comment]
It doesn't look like this PR is breaking the evaluation.

**Review by ryantm — APPROVED** [review]

**Pull request merged**
