### PR TITLE
nixVersions.nix_2_14: init at 2.14.1

### PR DESCRIPTION
**Pull request by zowoq**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
Checked nixpkgs-review with 2.14 as stable, two failures:

- `nix-eval-jobs` @adisbladis @Mic92
- `nix-doc` @lf-

**Comment by lf-** [comment]
> 
>     * `nix-doc` @lf-

Thanks for the ping. I may have some time tomorrow to assess the damage

**Comment by Mic92** [comment]
Can we merge this without setting it as a default and than I will fix nix-eval-jobs and issue a new release?

**Comment by zowoq** [comment]
> Can we merge this without setting it as a default

Yes, that's why I did `unstable -> 2.14`. Or do you mean I should drop the unstable commit?

**Comment by lf-** [comment]
nix-doc has been fixed

**Comment by Artturin** [comment]
Will need https://github.com/NixOS/nixpkgs/pull/146515 before a stable bump

**Comment by zowoq** [comment]
@Artturin Are you okay with merging this?

**Comment by Mic92** [comment]
> @Artturin Are you okay with merging this?

This is my interpretation since this is not making it the default.

**Pull request merged**
