### PR TITLE
nixUnstable: pre20201205_a5d85d0 -> pre20210219_548437c

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
update nixUnstable

~~had to pin gcc to gcc9 as additional work was merged since the last update which is not compatible. Pragmatically, we can bump to gcc10 when upstream has CI around gcc10~~

Using the version of nixUnstable which hydra is using. and just picked the patches that I really want to use.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
Last time I checked the current `hydra-unstable` in here didn't build with latest Nix master. Can you please check if bumping Hydra would resolve the issue?

Also, this should be backported IMHO.

**Comment by jonringer** [comment]
updating hydra to latest, then picking what the flake.lock is locked to

**Comment by jonringer** [comment]
```
https://github.com/NixOS/nixpkgs/pull/109309

1 package marked as broken and skipped:
nix-exec

1 package failed to build:
hercules-ci-agent

53 packages built:
bundix cabal2nix cachix common-updater-scripts crate2nix crystal2nix dep2nix disnix disnixos dydisnix fusionInventory go2nix hydra-unstable libnixxml lispPackages.quicklisp-to-nix lispPackages.quicklisp-to-nix-system-info nix nix-binary-cache nix-bundle nix-direnv nix-doc nix-du nix-index nix-pin nix-plugins nix-prefetch nix-prefetch-bzr nix-prefetch-cvs nix-prefetch-docker nix-prefetch-git nix-prefetch-hg nix-prefetch-scripts nix-prefetch-svn nix-review nix-serve nix-update nix-update-source nixFlakes nixos-generators nixos-shell nixui python37Packages.nix-kernel python37Packages.nixpkgs python37Packages.pythonix python38Packages.nix-kernel python38Packages.nixpkgs python38Packages.pythonix python39Packages.nix-kernel python39Packages.nixpkgs python39Packages.pythonix update-nix-fetchgit vgo2nix vulnix
```

**Comment by jonringer** [comment]
@GrahamcOfBorg build hydra-unstable

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109309` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages marked as broken and skipped:
</summary>
<ul>
<li>fusionInventory</li>
<li>nix-exec</li>
<li>nixui</li>
</ul>
</details>
<details>

  <summary>51 packages failed to build and are new build failures:</summary>
  <ul>
<li>bundix: log was empty</li>
<li>cabal2nix: log was empty</li>
<li>cachix: log was empty</li>
<li>crate2nix: log was empty</li>
<li>crystal2nix: log was empty</li>
<li>dep2nix: log was empty</li>
<li>disnix: log was empty</li>
<li>dydisnix: log was empty</li>
<li>go2nix: log was empty</li>
<li>haskellPackages.cachix: log was empty</li>
<li>haskellPackages.hercules-ci-agent: log was empty</li>
<li>haskellPackages.nix-paths: log was empty</li>
<li>haskellPackages.update-nix-fetchgit: log was empty</li>
<li>hercules-ci-agent: log was empty</li>
<li>libnixxml: log was empty</li>
<li>nix: log <a href="https://termbin.com/wn4l">https://termbin.com/wn4l</a></li>
<li>(nixStable): log was empty</li>
<li>nix-bundle: log was empty</li>
<li>nix-direnv: log was empty</li>
<li>nix-doc: log was empty</li>
<li>nix-du: log was empty</li>
<li>nix-index: log was empty</li>
<li>nix-pin: log was empty</li>
<li>nix-plugins: log was empty</li>
<li>nix-prefetch-bzr: log was empty</li>
<li>nix-prefetch-cvs: log was empty</li>
<li>nix-prefetch-docker: log was empty</li>
<li>nix-prefetch-git: log was empty</li>
<li>nix-prefetch-hg: log was empty</li>
<li>nix-prefetch-scripts: log was empty</li>
<li>nix-prefetch-svn: log was empty</li>
<li>nix-serve: log was empty</li>
<li>nix-update: log was empty</li>
<li>nix-update-source: log was empty</li>
<li>nixFlakes: log <a href="https://termbin.com/h2iy">https://termbin.com/h2iy</a></li>
<li>(nixUnstable): log was empty</li>
<li>nixos-generators: log was empty</li>
<li>nixos-shell: log was empty</li>
<li>nixpkgs-review: log was empty</li>
<li>python37Packages.nix-kernel: log was empty</li>
<li>python37Packages.nixpkgs: log was empty</li>
<li>python37Packages.pythonix: log was empty</li>
<li>python38Packages.nix-kernel: log was empty</li>
<li>python38Packages.nixpkgs: log was empty</li>
<li>python38Packages.pythonix: log was empty</li>
<li>python39Packages.nix-kernel: log was empty</li>
<li>python39Packages.nixpkgs: log was empty</li>
<li>python39Packages.pythonix: log was empty</li>
<li>update-nix-fetchgit: log was empty</li>
<li>vgo2nix: log was empty</li>
<li>vulnix: log was empty</li>
  </ul>
</details>

**Comment by jonringer** [comment]
gah, darwin :(

**Comment by SuperSandro2000** [comment]
> gah, darwin :(

It is already broken now and I think some tests are failing. We should fix it eventually.

**Comment by jonringer** [comment]
Yea, but the current darwin build is passing https://hydra.nixos.org/build/135058690 so I don't want to break darwin users. Especially since this should be backported.

Wish darwin wasn't so expensive to get CI for. (Free for linux)

**Comment by jonringer** [comment]
looks like https://github.com/NixOS/nix/commit/86a2ceeb986609488be1c6794a8e416df3b90c7b was merged which would allow me to revert gcc version pinning

**Comment by Ma27** [comment]
if we can't merge this because of darwin yet, we should at least apply the patch from https://github.com/NixOS/nix/pull/4470.

**Comment by jonringer** [comment]
reverted the gcc9 change, because it's no longer relevant, may also fix the darwin build

added the related flake inputs changes which I cared about and attempted to open this PR in the first place

@SuperSandro2000 do you mind doing a darwin review?

**Comment by jonringer** [comment]
```
https://github.com/NixOS/nixpkgs/pull/109309

1 package marked as broken and skipped:
nix-exec

1 package failed to build:
hercules-ci-agent

51 packages built:
bundix cabal2nix cachix common-updater-scripts crate2nix crystal2nix dep2nix fusionInventory go2nix hydra-unstable libnixxml lispPackages.quicklisp-to-nix lispPackages.quicklisp-to-nix-system-info nix nix-binary-cache nix-bundle nix-direnv nix-doc nix-du nix-index nix-pin nix-plugins nix-prefetch nix-prefetch-bzr nix-prefetch-cvs nix-prefetch-docker nix-prefetch-git nix-prefetch-hg nix-prefetch-scripts nix-prefetch-svn nix-review nix-serve nix-update nix-update-source nixFlakes nixos-generators nixos-rebuild nixos-shell nixui python37Packages.nix-kernel python37Packages.nixpkgs python37Packages.pythonix python38Packages.nix-kernel python38Packages.nixpkgs python38Packages.pythonix python39Packages.nix-kernel python39Packages.nixpkgs python39Packages.pythonix update-nix-fetchgit vgo2nix vulnix
```
`hercules-ci-agent` is already broken on master

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109309` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>4 packages failed to build and are new build failures:</summary>
  <ul>
<li>nix-update: log was empty</li>
<li>nixFlakes: log <a href="https://termbin.com/ha8z">https://termbin.com/ha8z</a></li>
<li>(nixUnstable): log was empty</li>
<li>nixpkgs-review: log was empty</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109309` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package marked as broken and skipped:
</summary>
<ul>
<li>nix-exec</li>
</ul>
</details>
<details>
<summary>
2 packages blacklisted:
</summary>
<ul>
<li>tests.nixos-functions.nixos-test</li>
<li>tests.nixos-functions.nixosTest-test</li>
</ul>
</details>
<details>

  <summary>2 packages failed to build and are new build failures:</summary>
  <ul>
<li>haskellPackages.hercules-ci-agent: log <a href="https://termbin.com/tugp">https://termbin.com/tugp</a></li>
<li>hercules-ci-agent: log <a href="https://termbin.com/4jqp">https://termbin.com/4jqp</a></li>
  </ul>
</details>
<details>
<summary>
53 packages built:
</summary>
<ul>
<li>bundix</li>
<li>cabal2nix</li>
<li>cachix</li>
<li>common-updater-scripts</li>
<li>crate2nix</li>
<li>crystal2nix</li>
<li>dep2nix</li>
<li>fusionInventory</li>
<li>go2nix</li>
<li>haskellPackages.cachix</li>
<li>haskellPackages.nix-paths</li>
<li>haskellPackages.update-nix-fetchgit</li>
<li>hydra-unstable</li>
<li>libnixxml</li>
<li>lispPackages.quicklisp-to-nix</li>
<li>lispPackages.quicklisp-to-nix-system-info</li>
<li>nix (nixStable)</li>
<li>nix-bundle</li>
<li>nix-direnv</li>
<li>nix-doc</li>
<li>nix-du</li>
<li>nix-index</li>
<li>nix-pin</li>
<li>nix-plugins</li>
<li>nix-prefetch</li>
<li>nix-prefetch-bzr</li>
<li>nix-prefetch-cvs</li>
<li>nix-prefetch-docker</li>
<li>nix-prefetch-git</li>
<li>nix-prefetch-hg</li>
<li>nix-prefetch-scripts</li>
<li>nix-prefetch-svn</li>
<li>nix-serve</li>
<li>nix-update</li>
<li>nix-update-source</li>
<li>nixFlakes (nixUnstable)</li>
<li>nixos-generators</li>
<li>nixos-rebuild</li>
<li>nixos-shell</li>
<li>nixpkgs-review</li>
<li>nixui</li>
<li>python37Packages.nix-kernel</li>
<li>python37Packages.nixpkgs</li>
<li>python37Packages.pythonix</li>
<li>python38Packages.nix-kernel</li>
<li>python38Packages.nixpkgs</li>
<li>python38Packages.pythonix</li>
<li>python39Packages.nix-kernel</li>
<li>python39Packages.nixpkgs</li>
<li>python39Packages.pythonix</li>
<li>update-nix-fetchgit</li>
<li>vgo2nix</li>
<li>vulnix</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109309` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package marked as broken and skipped:
</summary>
<ul>
<li>nix-exec</li>
</ul>
</details>
<details>
<summary>
2 packages blacklisted:
</summary>
<ul>
<li>tests.nixos-functions.nixos-test</li>
<li>tests.nixos-functions.nixosTest-test</li>
</ul>
</details>
<details>

  <summary>2 packages failed to build and are new build failures:</summary>
  <ul>
<li>haskellPackages.hercules-ci-agent: log <a href="https://termbin.com/veld">https://termbin.com/veld</a></li>
<li>hercules-ci-agent: log <a href="https://termbin.com/j26h">https://termbin.com/j26h</a></li>
  </ul>
</details>
<details>
<summary>
53 packages built:
</summary>
<ul>
<li>bundix</li>
<li>cabal2nix</li>
<li>cachix</li>
<li>common-updater-scripts</li>
<li>crate2nix</li>
<li>crystal2nix</li>
<li>dep2nix</li>
<li>fusionInventory</li>
<li>go2nix</li>
<li>haskellPackages.cachix</li>
<li>haskellPackages.nix-paths</li>
<li>haskellPackages.update-nix-fetchgit</li>
<li>hydra-unstable</li>
<li>libnixxml</li>
<li>lispPackages.quicklisp-to-nix</li>
<li>lispPackages.quicklisp-to-nix-system-info</li>
<li>nix (nixStable)</li>
<li>nix-bundle</li>
<li>nix-direnv</li>
<li>nix-doc</li>
<li>nix-du</li>
<li>nix-index</li>
<li>nix-pin</li>
<li>nix-plugins</li>
<li>nix-prefetch</li>
<li>nix-prefetch-bzr</li>
<li>nix-prefetch-cvs</li>
<li>nix-prefetch-docker</li>
<li>nix-prefetch-git</li>
<li>nix-prefetch-hg</li>
<li>nix-prefetch-scripts</li>
<li>nix-prefetch-svn</li>
<li>nix-serve</li>
<li>nix-update</li>
<li>nix-update-source</li>
<li>nixFlakes (nixUnstable)</li>
<li>nixos-generators</li>
<li>nixos-rebuild</li>
<li>nixos-shell</li>
<li>nixpkgs-review</li>
<li>nixui</li>
<li>python37Packages.nix-kernel</li>
<li>python37Packages.nixpkgs</li>
<li>python37Packages.pythonix</li>
<li>python38Packages.nix-kernel</li>
<li>python38Packages.nixpkgs</li>
<li>python38Packages.pythonix</li>
<li>python39Packages.nix-kernel</li>
<li>python39Packages.nixpkgs</li>
<li>python39Packages.pythonix</li>
<li>update-nix-fetchgit</li>
<li>vgo2nix</li>
<li>vulnix</li>
</ul>
</details>

**Comment by jonringer** [comment]
I think that failure has been a long time flakey issue

can you try to build it again?

**Comment by Ma27** [comment]
Can confirm. I regularly compile Nix on my own since I have a few patches on top and this is one of the tests that fail from time to time.

**Comment by SuperSandro2000** [comment]
> can you try to build it again?

I have build it at least two times with that issue.

**Comment by jonringer** [comment]
> > can you try to build it again?
> 
> I have build it at least two times with that issue.

I had another coworker be able to build it fine. I might just merge and babysit, restarting it.

**Comment by jonringer** [comment]
cc @edolstra @Ma27 do you mind if I pin the nix version for hydra, and the `nixUnstable` package can more closely follow the development branch?

**Comment by Ma27** [comment]
Don't have the capacity to test (tonight at least in my tz), but LGTM :+1:

**Review by Ma27 — APPROVED** [review]
@jonringer LGTM, can be merged from my PoV :+1:

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109309` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package marked as broken and skipped:
</summary>
<ul>
<li>nix-exec</li>
</ul>
</details>
<details>
<summary>
2 packages blacklisted:
</summary>
<ul>
<li>tests.nixos-functions.nixos-test</li>
<li>tests.nixos-functions.nixosTest-test</li>
</ul>
</details>
<details>

  <summary>3 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>haskellPackages.hercules-ci-agent: log was empty</li>
<li>hercules-ci-agent: log was empty</li>
<li>libnixxml: log was empty</li>
  </ul>
</details>
<details>
<summary>
50 packages built:
</summary>
<ul>
<li>bundix</li>
<li>cabal2nix</li>
<li>cachix</li>
<li>common-updater-scripts</li>
<li>crate2nix</li>
<li>crystal2nix</li>
<li>dep2nix</li>
<li>fusionInventory</li>
<li>go2nix</li>
<li>haskellPackages.cachix</li>
<li>haskellPackages.hercules-ci-cnix-store</li>
<li>haskellPackages.nix-paths</li>
<li>haskellPackages.update-nix-fetchgit</li>
<li>hydra-unstable</li>
<li>lispPackages.quicklisp-to-nix</li>
<li>lispPackages.quicklisp-to-nix-system-info</li>
<li>nix (nixStable)</li>
<li>nix-bundle</li>
<li>nix-direnv</li>
<li>nix-doc</li>
<li>nix-du</li>
<li>nix-index</li>
<li>nix-pin</li>
<li>nix-plugins</li>
<li>nix-prefetch</li>
<li>nix-prefetch-bzr</li>
<li>nix-prefetch-cvs</li>
<li>nix-prefetch-docker</li>
<li>nix-prefetch-git</li>
<li>nix-prefetch-hg</li>
<li>nix-prefetch-scripts</li>
<li>nix-prefetch-svn</li>
<li>nix-serve</li>
<li>nix-update</li>
<li>nix-update-source</li>
<li>nixFlakes (nixUnstable)</li>
<li>nixos-generators</li>
<li>nixos-rebuild</li>
<li>nixos-shell</li>
<li>nixpkgs-review</li>
<li>nixui</li>
<li>python38Packages.nix-kernel</li>
<li>python38Packages.nixpkgs</li>
<li>python38Packages.pythonix</li>
<li>python39Packages.nix-kernel</li>
<li>python39Packages.nixpkgs</li>
<li>python39Packages.pythonix</li>
<li>update-nix-fetchgit</li>
<li>vgo2nix</li>
<li>vulnix</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109309` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>5 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>nix-direnv: log was empty</li>
<li>(nixpkgs-review): log was empty</li>
<li>nix-update: log was empty</li>
<li>nixFlakes: <a href="https://termbin.com/v5v3">plain log</a>  |  <a href="https://htmlpreview.github.io/?https://gist.githubusercontent.com/SuperSandroBot/a4c6112e9895fae68fff65e5d3f45219/raw/index.html">pretty log </a></li>
<li>(nixUnstable): log was empty</li>
  </ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>nix-review: log was empty</li>
  </ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
nix-direnv:
<details>


warning: unused-argument
Unused argument: `nix`.
Near pkgs/tools/misc/nix-direnv/default.nix:1:42:

```
  |
1 | { lib, stdenv, fetchFromGitHub, gnugrep, nix, nixFlakes }:
  |                                          ^
```
</details>
nixFlakes:
<details>

warning: EvalError
Cannot evaluate attribute ‘nixFlakes’ in ‘/nix/store/2pii6w5m7138dxg0vwjaxwnv8d8jrx1p-nixpkgs’.
</details>
</details>

**Comment by shlevy** [comment]
nixUnstable is now past this.

**Comment by jonringer** [comment]
closing due to other PR

**Pull request closed without merging**
