### PR TITLE
dune: 1.9.2 -> 1.10.0

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change
Changelog: https://github.com/ocaml/dune/releases/tag/1.10.0

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
cc @Zimmi48 for review

**Comment by vbgl** [comment]
@GrahamcOfBorg build virt-top

**Comment by Zimmi48** [comment]
virt-top does not build because of a broken dependency: camomile

**Review by vbgl — CHANGES_REQUESTED** [review]
This breaks `virt-top`.

**Comment by Zimmi48** [comment]
The error is the following:

```
  Multiple rules generated for _build/default/Camomile/installConfig.ml:
  - file present in source tree
  - Camomile/jbuild:4
  Hint: rm -f Camomile/installConfig.ml
```

Removing this line of the camomile:

```
	configurePhase = "ocaml configure.ml --share $out/share/camomile";
```

will fix the build of camomile but then it is gettext that fails with

```
  Fatal error: exception Not_found
```

**Comment by Zimmi48** [comment]
This seems to be related to this changelog entry:

>Improve the behavior when a strict subset of the targets of a rule is already in the source tree for projects using the dune language < 1.10

FTR camomile is not the only package broken by this change: for instance, sqlexpr is as well.

**Comment by Mic92** [comment]
One way to move this forward is to introduce a `dune = dune_1_10;` and a `dune_1_9` and then use the old dune for packages that require it.

**Comment by Zimmi48** [comment]
FTR these are the packages that are broken by this update:

- ocamlPackages.camomile
- ocamlPackages.sqlexpr
- ocamlPackages.lwt_camlp4

Depends on ocamlPackages.camomile:
- liquidsoap
- ocamlPackages.zed
- ocamlPackages.ocaml_gettext
- ocamlPackages.javalib
- libguestfs
- libguestfs-with-appliance
- ocamlPackages.lambdaTerm
- ocamlPackages.sawja
- virt-top
- python37Packages.guestfs
- python27Packages.guestfs
- ocamlPackages.utop
- vagrant
- ocamlPackages.bap
- ocamlPackages.reason
- libbap
- python27Packages.bap
- python37Packages.bap

Depends on ocamlPackages.sqlexpr:
- ocamlPackages.ppx_sqlexpr

Depends on ocamlPackages.lwt_camlp4:
- ocamlPackages.eliom
- ocamlPackages.ocsigen-start
- ocamlPackages.ocsigen-toolkit

and the following patch is enough to have lwt_camlp4 and its dependencies build:

```diff
diff --git a/pkgs/development/ocaml-modules/lwt/camlp4.nix b/pkgs/development/ocaml-modules/lwt/camlp4.nix
index 53f0435f462..5367ef3f9f2 100644
--- a/pkgs/development/ocaml-modules/lwt/camlp4.nix
+++ b/pkgs/development/ocaml-modules/lwt/camlp4.nix
@@ -15,6 +15,8 @@ buildDunePackage rec {
 
   propagatedBuildInputs = [ camlp4 ];
 
+  preBuild = "rm META.lwt_camlp4";
+
   meta = {
     description = "Camlp4 syntax extension for Lwt (deprecated)";
     license = lib.licenses.lgpl21;
@@ -22,4 +24,3 @@ buildDunePackage rec {
     maintainers = [ lib.maintainers.vbgl ];
   };
 }
```

**Comment by Zimmi48** [comment]
The following patch fixes the build for camomile and all the packages that depend on it (including virt-top):

```diff
diff --git a/pkgs/development/ocaml-modules/camomile/default.nix b/pkgs/development/ocaml-modules/camomile/default.nix
index f21e7643afe..815acf78914 100644
--- a/pkgs/development/ocaml-modules/camomile/default.nix
+++ b/pkgs/development/ocaml-modules/camomile/default.nix
@@ -1,14 +1,14 @@
-{ stdenv, fetchFromGitHub, buildDunePackage, cppo }:
+{ stdenv, fetchurl, fetchFromGitHub, buildDunePackage, cppo }:
 
 buildDunePackage rec {
   pname = "camomile";
-       version = "1.0.1";
+       version = "git-pr-76";
 
        src = fetchFromGitHub {
                owner = "yoriyuki";
                repo = pname;
-               rev = version;
-               sha256 = "1pfxr9kzkpd5bsdqrpxasfxkawwkg4cpx3m1h6203sxi7qv1z3fn";
+               rev = "59e350d7988b90b068d4075512d1ad6002fdea4c";
+               sha256 = "1zlrf2ij70x83rncbsbjw0f4l4sxjylkhhx6ayg2n57zqwhmb999";
        };
 
        buildInputs = [ cppo ];
```

This is basically updating to the version of camomile of yoriyuki/Camomile#76.

**Comment by vbgl** [comment]
At this point you should ask upstream (camomile) to release a new version.

**Comment by Mic92** [comment]
They have not even merged the patch. `fetchpatch` might be also acceptable in the meantime.

**Comment by Zimmi48** [comment]
Sure. I intended to do so as soon as upstream merges the PR.

**Comment by Zimmi48** [comment]
The last issue is with sqlexpr whose compilation fail like this:

```
  Multiple rules generated for _build/default/META.sqlexpr:
  - file present in source tree
  - <internal location>
  Hint: rm -f META.sqlexpr
```

but removing the META file like I did for lwt_camlp4 breaks ppx_sqlexpr:

```
  File "tests/ppx/jbuild", line 12, characters 17-24:
  12 |   (libraries    (sqlexpr oUnit))
                        ^^^^^^^
  Error: Library "sqlexpr" not found.
 ```

**Comment by Zimmi48** [comment]
From talking to @diml on yoriyuki/Camomile@505202b, it would seem that it could be a Dune bug that we have three packages using jbuilder that do not build with the new version of Dune:
- https://github.com/mfp/ocaml-sqlexpr/tree/0.9.0/src
- https://github.com/yoriyuki/Camomile/tree/1.0.1
- https://github.com/ocsigen/lwt_camlp4/tree/45f25a081e01071ab566924b48ba5f7553bb33ac

**Comment by Zimmi48** [comment]
According to @diml, another fix for this is just to use the `jbuilder` binary instead of the `dune` binary for projects that still use `jbuild` files.

**Comment by marsam** [comment]
I've replaced `jbuilder` in camomile, and removed the `META.*` files in `sqlexpr` and `lwt_camlp4`  which seems to be enough

@GrahamcOfBorg build ocamlPackages.camomile ocamlPackages.sqlexpr ocamlPackages.lwt_camlp4 virt-top

**Comment by Zimmi48** [comment]
@marsam Have you tried building `ppx_sqlexpr` after removing the `META` file in `sqlexpr`?

**Comment by marsam** [comment]
yes, it builds https://gist.github.com/7bdbfff09f0b48d38c5c0f0fd5c1174c

@GrahamcOfBorg eval

**Comment by Zimmi48** [comment]
@vbgl Isn't this PR ready to be merged?

**Comment by Mic92** [comment]
Camomile got a fix merged now: https://github.com/yoriyuki/Camomile/pull/76

**Pull request merged**
