### PR TITLE
Nix, Hydra: bump to 2017-03-21

### PR DESCRIPTION
**Pull request by domenkozar**
cc @globin @edolstra 

It compiles, but I haven't tested this yet.

### CODE REVIEW

**Comment by edolstra** [comment]
Here is a better patch (used by hydra.nixos.org):
```
diff --git a/pkgs/tools/package-management/nix/default.nix b/pkgs/tools/package-management/nix/default.nix
index 8a9bfa7..2211709 100644
--- a/pkgs/tools/package-management/nix/default.nix
+++ b/pkgs/tools/package-management/nix/default.nix
@@ -1,4 +1,4 @@
-{ lib, stdenv, fetchurl, fetchFromGitHub, perl, curl, bzip2, sqlite, openssl ? null, xz
+{ lib, stdenv, fetchurl, fetchFromGitHub, perl, curl, bzip2, sqlite, openssl ? null, xz, brotli
 , pkgconfig, boehmgc, perlPackages, libsodium, aws-sdk-cpp
 , autoreconfHook, autoconf-archive, bison, flex, libxml2, libxslt, docbook5, docbook5_xsl
 , storeDir ? "/nix/store"
@@ -21,6 +21,7 @@ let
 
     buildInputs = [ curl openssl sqlite xz ]
       ++ lib.optional (stdenv.isLinux || stdenv.isDarwin) libsodium
+      ++ lib.optional fromGit brotli
       ++ lib.optional (stdenv.isLinux && lib.versionAtLeast version "1.12pre")
           (aws-sdk-cpp.override {
             apis = ["s3"];
@@ -112,12 +113,12 @@ in rec {
 
   nixUnstable = lib.lowPrio (common rec {
     name = "nix-1.12${suffix}";
-    suffix = "pre5073_1cf4801";
+    suffix = "pre5104_558eda0";
     src = fetchFromGitHub {
       owner = "NixOS";
       repo = "nix";
-      rev = "1cf480110879ffc8aee94b4b75999da405b71d7c";
-      sha256 = "1iwpddz0yni7cz2g9asj6nmrwhaai3rhfmkq954hph8nx02c3l02";
+      rev = "558eda01154d47b3c88983576eedb582185b2201";
+      sha256 = "01ixakgjb5985kgm6pcvc9w2pxhz3mbnq0j7hhzpv05x715rmj3x";
     };
     fromGit = true;                                                                                                                                                                                                                                         
   });                                                                                                                                                                                                                                                       ```

**Comment by domenkozar** [comment]
I think naming should follow our convention to include the date of the bump rather than commit, but otherwise I'll add brotli

**Comment by edolstra** [comment]
I don't see a reason to change the naming convention. Also your change would cause the version number to 1.122017...

**Comment by edolstra** [comment]
To add to this: `1.12-pre...` comes before `1.12` in `nix-env` version comparisons, while `1.12.2017` comes after. So this would break `nix-env -u`.

**Comment by domenkozar** [comment]
Could be then `1.12-pre-2017-03-21`, according to https://nixos.org/nixpkgs/manual/#sec-package-naming

**Comment by rht** [comment]
It would have been `1.12pre-unstable-2017-03-21` (the infix would make a more consistent `grep` result).

**Comment by domenkozar** [comment]
I've pushed the brotli dependency addition on reverse `suffix` change, I'd really like to get this merged for 17.03 as well :)

**Comment by bjornfor** [comment]
Looks good to me. Didn't test it. Please remove "hydra-bump" branch from the nixpkgs repo that seems to have been pushed alongside this PR.

**Comment by globin** [comment]
@domenkozar are you going to cherry-pick yourself?

**Comment by domenkozar** [comment]
Done in dfba601e1d

**Comment by globin** [comment]
Thanks :)

**Pull request merged**
