### PR TITLE
carbon-now-cli: use buildNpmPackage

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
See https://github.com/NixOS/nixpkgs/issues/229475

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc @rmcgibbo who originally packaged it in https://github.com/NixOS/nixpkgs/pull/139151

### CODE REVIEW

**Comment by teto** [comment]
Result of `nixpkgs-review pr 249877` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>carbon-now-cli</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
It's weird that it built without this error for me but now I also get the same error:
```
> if [ -d 'dist' ]; then trash dist; fi && tsc && trash dist/coverage && trash dist/test

Error: EACCES: permission denied, mkdir '/.Trash-1000'
```

**Comment by teto** [comment]
this build but looks like it depends on playwright and usually they require a specific version of the driver https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/web/playwright/driver.nix
I had started something to make it easier to override the browser version https://github.com/NixOS/nixpkgs/pull/249738 . 


```
(ins)❌1 ❯ carbon-now  ~/config.cfg
(node:797994) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:797994) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time

  Warning: Preset `latest-preset` doesn’t exist. Using default settings…
✔ Processing /home/teto/config.cfg
✔ Preparing connection
↓ Opening in browser
✖ browserType.launch: Executable doesn't exist at /home/teto/.cache/ms-playwright/chromium-1060/chrome-linux/chrome
  ╔═════════════════════════════════════════════════════════════════════════╗
  ║ Looks like Playwright Test or Playwright was just installed or updated. ║
  ║ Please run the following command to download new browsers:              ║
  ║                                                                         ║
  ║     npx playwright install                                              ║
  ║                                                                         ║
  ║ <3 Playwright Team                                                      ║
  ╚═════════════════════════════════════════════════════════════════════════╝
◼ Copying image to clipboard

  Error: Sending code to https://carbon.now.sh went wrong.

  This is mostly due to:

  · Nonsensical input like `--start 10 --end 2`
  · Carbon being down or taking too long to respond
  · Your internet connection not working or being too slow

  Additional info:

  browserType.launch: Executable doesn't exist at /home/teto/.cache/ms-playwright/chromium-1060/chrome-linux/chrome
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
```

Fixing this might be too hard if you just want to convert to buildNpmPackage so we could merge as is and let the maintainer wrap the correct browser version ?

**Comment by dotlambda** [comment]
I tried passing it playwrights driver.browsers` but then it tries to use Chrome which the former doesn't come with so it still fails.

**Comment by dotlambda** [comment]
I'll merge this because the current `nodePackages.carbon-now-cli` doesn't even build.

**Pull request merged**
