### PR TITLE
sof-firmware: 1.4.2 -> 1.5.1

### PR DESCRIPTION
**Pull request by evenbrenden**
###### Motivation for this change

Update stable version and change source repo from https://www.alsa-project.org/files/pub/misc/sof/ to https://github.com/thesofproject/sof-bin.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by evenbrenden** [comment]
https://www.alsa-project.org/files/pub/misc/sof/ is deprecated and replaced by https://github.com/thesofproject/sof-bin. However, it's "(...) still very much WiP and may churn a little until things settle down", so I'm not sure about this change.

In the `stable-1.4.2` branch, there's a `go.sh` script that handles installation. The same file is not (yet) implemented in the `stable-1.5` branch, but as far as I can tell, the exact same script works with version 1.5. Therefore, I inlined the contents of the 1.4.2 script in the `installPhase` verbatim (except for the part that removes any old version). When the install script in the version 1.5 branch is updated, we could just call that instead. Or use our own - not sure what is preferred.

**Review by lblasc — APPROVED** [review]

**Review by lblasc — APPROVED** [review]

**Review by lblasc — APPROVED** [review]

**Comment by lblasc** [comment]
I've updated to kernel 5.7.1 - now this boring error is gone ( `error: no reply expected, received 0x0` )

**Comment by evenbrenden** [comment]
Upped version to 1.5.1. Using the supplied installation script.

**Comment by lblasc** [comment]
@evenbrenden thx. Can you please squash your changes into single commit ?

**Review by lblasc — APPROVED** [review]

**Comment by lblasc** [comment]
pinging random people.. @Mic92 can you maybe merge this ?

**Pull request merged**
