### PR TITLE
faraday-cli: init at 2.0.2

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Command Line Interface for Faraday

https://github.com/infobyte/faraday-cli

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 138944` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>faraday-cli</li>
    <li>python38Packages.faraday-plugins</li>
    <li>python38Packages.python-status</li>
    <li>python38Packages.simple-rest-client</li>
    <li>python39Packages.faraday-plugins</li>
    <li>python39Packages.python-status</li>
    <li>python39Packages.simple-rest-client</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 138944` at 60218ef0 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built successfully:</summary>
  <ul>
    <li>faraday-cli</li>
    <li>python38Packages.faraday-plugins</li>
    <li>python38Packages.python-status</li>
    <li>python38Packages.simple-rest-client</li>
    <li>python39Packages.faraday-plugins</li>
    <li>python39Packages.python-status</li>
    <li>python39Packages.simple-rest-client</li>
  </ul>
</details>

**Comment by figsoda** [comment]
should this go into python-modules and be converted with `toPythonApplication` instead?
this way it is easier to override its dependencies

**Comment by SuperSandro2000** [comment]
> should this go into python-modules and be converted with `toPythonApplication` instead?
> this way it is easier to override its dependencies

but then we could end up in a situation where two different versions of the same library are in one python env.

**Pull request merged**
