### PR TITLE
Cleanup in emacs-packages

### PR DESCRIPTION
**Pull request by oxij**

### CODE REVIEW

**Comment by jagajaga** [comment]
cc @ttuegel

**Comment by peti** [comment]
This looks nice. Does anybody thing we should wait merging this patch or can it go in?

**Comment by jagajaga** [comment]
I think we can merge it.

**Comment by oxij** [comment]
Yep, but wait a bit. I'll fix the parts noted by @ttuegel.

**Comment by oxij** [comment]
Should be okay now. The `emacs-packages` file header can still be discussed, but I think it's pretty up to date with the current state of affairs.

**Pull request merged**
