### PR TITLE
qtcreator: 3.2.1 -> 3.4.2

### PR DESCRIPTION
**Pull request by akaWolf**
Updated version of Qt Creator.

### CODE REVIEW

**Comment by lihop** [comment]
@jagajaga Doesn't the hash need to be changed as well?
Or am I missing something here?

**Comment by jagajaga** [comment]
@lihop you are definetly right! My fault. Will fix in a moment.

**Comment by vcunat** [comment]
This won't build now, as it seems to require qt5 instead of qt4. It's good to try to build at least before merging, ideally try to use ;-)

Maintainer @bbenoist might know better how to fix this up.

**Comment by vcunat** [comment]
Build fixed now.

**Comment by akaWolf** [comment]
@vcunat didn't see how and where.

**Comment by vcunat** [comment]
That's because I forgot to push it :-)

**Comment by bbenoist** [comment]
@vcunat
Sorry for being late. As of now, I am struggling with quite different tasks :-S

I saw you found that you can specify any Qt derivation to the QtCreator one. It was mostly used because Qt4 required the developerBuild option to be enabled. As Qt5 no longer requires it, you might simplify things and directly rely on the default derivation.

**Comment by vcunat** [comment]
Current default `qt5 = qt54;` doesn't even have such options. Instead, it's a set of separately built modules.

I didn't want to do larger changes on packages I don't use at all, as I can't even test them properly...

**Pull request merged**
