### PR TITLE
nixos boot extra-utils: ensure we use working lvm2

### LINKED ISSUE #96197: NixOS Tests broken in master and staging
**Describe the bug**
Trying to build a nixosTests fails due to stage-1 failing during creation of `extra-utils`

```
builder for '/nix/store/z1cxv06bi8iihhcifik0aqllqdbxhwpi-extra-utils.drv' failed with exit code 1
cannot build derivation '/nix/store/h8zxyl8r36bl4av33l2fbq0wkjs775mi-stage-1-init.sh.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/dbl58yvryaxsd4qzmxc09z4npzl07m7s-initrd-linux-5.4.54.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/qr9hy73gr3wwgk81ll2f063ry57idlk2-nixos-system-bbmaster-20.09.git.4cfd81acfa0M.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/rylgj77220s22979zlasdyrmw6g4syvf-nixos-system-bbworker-20.09.git.4cfd81acfa0M.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/6hss4221vbsch61ka9pzpsw2sfhh3lcg-nixos-system-gitrepo-20.09.git.4cfd81acfa0M.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/5sfqhjd1jsbf117sjn70ik777b03lqhi-nixos-vm.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/kah87whvjpp1zxqgjikwwny0249idlgb-nixos-vm.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/sxlb9fh7fqylpzw96jlkg4kfd2nrwshm-nixos-vm.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/xghh70sibzsnw27amzjrli0mgrx39f9j-nixos-test-driver-buildbot.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/4riphbxaqq2ql1kw0nfv8yhiiv08xjbx-vm-test-run-buildbot.drv': 1 dependencies couldn't be built
```
nix log:
```
Copying libs for executable /nix/store/75p0yg2l7lciimfjm6hdh67rl6lyy99i-extra-utils/lib/ld-linux-x86-64.so.2
/nix/store/ljd94dg6vmw9lx4vkszvl109w9y164sg-find-libs/bin/find-libs: line 19: left: unbound variable
stripping (with command strip and flags -s) in /nix/store/75p0yg2l7lciimfjm6hdh67rl6lyy99i-extra-utils/lib  /nix/store/75p0>
patching /nix/store/75p0yg2l7lciimfjm6hdh67rl6lyy99i-extra-utils/bin/systemd-sysctl...
patching /nix/store/75p0yg2l7lciimfjm6hdh67rl6lyy99i-extra-utils/bin/dmsetup...
patching /nix/store/75p0yg2l7lciimfjm6hdh67rl6lyy99i-extra-utils/bin/systemd-udevd...
patching /nix/store/75p0yg2l7lciimfjm6hdh67rl6lyy99i-extra-utils/bin/v4l_id...
patching /nix/store/75p0yg2l7lciimfjm6hdh67rl6lyy99i-extra-utils/bin/busybox...
patching /nix/store/75p0yg2l7lciimfjm6hdh67rl6lyy99i-extra-utils/bin/udevadm...
patching /nix/store/75p0yg2l7lciimfjm6hdh67rl6lyy99i-extra-utils/bin/ata_id...
patching /nix/store/75p0yg2l7lciimfjm6hdh67rl6lyy99i-extra-utils/bin/mke2fs...
patching /nix/store/75p0yg2l7lciimfjm6hdh67rl6lyy99i-extra-utils/bin/lvm...
patching /nix/store/75p0yg2l7lciimfjm6hdh67rl6lyy99i-extra-utils/bin/e2fsck...
patching /nix/store/75p0yg2l7lciimfjm6hdh67rl6lyy99i-extra-utils/bin/blkid...
patching /nix/store/75p0yg2l7lciimfjm6hdh67rl6lyy99i-extra-utils/bin/cdrom_id...
patching /nix/store/75p0yg2l7lciimfjm6hdh67rl6lyy99i-extra-utils/bin/mdadm...
patching /nix/store/75p0yg2l7lciimfjm6hdh67rl6lyy99i-extra-utils/bin/fido_id...
patching /nix/store/75p0yg2l7lciimfjm6hdh67rl6lyy99i-extra-utils/bin/tune2fs...
patching /nix/store/75p0yg2l7lciimfjm6hdh67rl6lyy99i-extra-utils/bin/kmod...
patching /nix/store/75p0yg2l7lciimfjm6hdh67rl6lyy99i-extra-utils/bin/scsi_id...
patching /nix/store/75p0yg2l7lciimfjm6hdh67rl6lyy99i-extra-utils/bin/mdmon...
testing patched programs...
hello world
245
```
from my own trouble shooting, the erring block of code is this "initrd test block" https://github.com/NixOS/nixpkgs/blob/40d2968ebf3b2b4c547caaa776b6eb875e1e5f83/nixos/modules/system/boot/stage-1.nix#L194

**To Reproduce**
```
git checkout staging # or master
git pull
nix-build -A nixosTests.buildbot
```

**Expected behavior**
able to run tests successfully

**Additional context**
git bisect run nix-build -A nixosTests.buildbot pointed me to:
```
72c8ed038946850d345db13f30e259a368d7c3c5 is the first bad commit
commit 72c8ed038946850d345db13f30e259a368d7c3c5
Author: Florian Klink <flokli@flokli.de>
Date:   Mon Aug 19 02:08:46 2019 +0200

    systemd: build with cryptsetup and cryptsetup-generators

    There's a circular dependency to systemd via cryptsetup and lvm2
    (systemd -> cryptsetup -> lvm2 -> udev=systemd).

    However, cryptsetup only really needs the devmapper component shipped
    with lvm2. So build `pkgs.cryptsetup` with a lvm2 that doesn't come with
    udev.

 nixos/modules/system/boot/systemd.nix      | 2 +-
 pkgs/os-specific/linux/systemd/default.nix | 4 +++-
 pkgs/top-level/all-packages.nix            | 6 +++++-
 3 files changed, 9 insertions(+), 3 deletions(-)
```
but this could be misleading due to how staging git history works

**Notify maintainers**
cc @flokli 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.60, NixOS, 20.09.git.2710fed815aM (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(archlayperson): `"home-manager"`
 - channels(root): `"nixos-20.09pre239318.c59ea8b8a0e"`
 - channels(jon): `"home-manager, nixos-20.09pre239318.c59ea8b8a0e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixosTests
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by vcunat**
This fixes the problem for me, though it's a bit hacky that we basically
re-link cryptsetup to a different lvm2 "version".
The recursion probably isn't needed now, but I think theoretically
it might be useful.

Also show those more results/failures in the build log.

###### Motivation for this change

Fixes https://github.com/NixOS/nixpkgs/issues/96197.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
I am able to run nixos tests again

**Comment by flokli** [comment]
`lvm2` provides `libdevmapper`, which is used to build `cyptsetup` (and systemd uses libcryptsetup for its cryptsetup support).
We finally build a `lvm2` with udev support (which is used in the normal system).
Also, see the commit message in https://github.com/NixOS/nixpkgs/commit/72c8ed038946850d345db13f30e259a368d7c3c5.

For initrd, it probably doesn't matter much which lvm2 we use, as systemd isn't available there.

**Comment by vcunat** [comment]
The problem was that if we use the less featurful one, `dmsetup` won't load due to missing symbol(s).

**Comment by flokli** [comment]
I assume we currently only have one `dmsetup` available, `from lvm2.bin`.

We might be able to just use `dmsetup` from `lvm2.override { udev = null; }`'s `bin` output - and only end up with one `lvm2*.lib` store path.

**Comment by flokli** [comment]
@vcunat something like this:
```
diff --git a/nixos/modules/system/boot/stage-1.nix b/nixos/modules/system/boot/stage-1.nix
index ec5eadf69c3..aab9e3cdec6 100644
--- a/nixos/modules/system/boot/stage-1.nix
+++ b/nixos/modules/system/boot/stage-1.nix
@@ -87,7 +87,9 @@ let
   # copy what we need.  Instead of using statically linked binaries,
   # we just copy what we need from Glibc and use patchelf to make it
   # work.
-  extraUtils = pkgs.runCommandCC "extra-utils"
+  extraUtils = let
+    # Use lvm2 without udev support, which is the same lvm2 we already have in the closure anyways
+    lvm2 = pkgs.lvm2.override { udev = null; }; in pkgs.runCommandCC "extra-utils"
     { nativeBuildInputs = [pkgs.buildPackages.nukeReferences];
       allowedReferences = [ "out" ]; # prevent accidents like glibc being included in the initrd
     }
@@ -111,8 +113,8 @@ let
       copy_bin_and_libs ${pkgs.utillinux}/sbin/blkid
 
       # Copy dmsetup and lvm.
-      copy_bin_and_libs ${getBin pkgs.lvm2}/bin/dmsetup
-      copy_bin_and_libs ${getBin pkgs.lvm2}/bin/lvm
+      copy_bin_and_libs ${getBin lvm2}/bin/dmsetup
+      copy_bin_and_libs ${getBin lvm2}/bin/lvm
 
       # Add RAID mdadm tool.
       copy_bin_and_libs ${pkgs.mdadm}/sbin/mdadm
```

**Comment by vcunat** [comment]
Yes, sounds good from what I know.

**Comment by FRidh** [comment]
I've pushed @flokli 's suggestion as f6286dea8881e446f33a9b2faca8db43ec55aa45. Thanks!

**Comment by jonringer** [comment]
since you pushed to master, we should probably push master to staging-next, staging-next to staging. Currently all other branches are broken

**Comment by FRidh** [comment]
already done :wink:

**Pull request closed without merging**
