### PR TITLE
vscode: Fix vscode-with-extensions with #70486

### PR DESCRIPTION
**Pull request by Artturin**
###### Motivation for this change
#71264 with conflicts solved

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
tested with
```nix
{ lib, pkgs }:

let
  insiders = (pkgs.vscode.override { isInsiders = true;}).overrideAttrs (old: rec {
    sourceExecutableName = "code-insiders";
    src = pkgs.fetchurl {
      name = "VSCode_insiders.tar.gz";
      url = "https://code.visualstudio.com/sha/download?build=insider&os=linux-x64";
      sha256 = "sha256-38UBKJWqvtlzpbTVL1NBGrUzXYlAVF/259mjt/QE5MY=";
    };
  });


  extensions = pkgs.vscode-utils.extensionsFromVscodeMarketplace ([
    {
      name = "js-debug-nightly";
      publisher = "ms-vscode";
      version = "2021.8.417";
      sha256 = "sha256-HaJbAFFiKWugzFiNMILYzPxQtI4gHafJy9N3IV9pCPA=";
    }
  ]);

in {

  code = (pkgs.vscode-with-extensions.override {
    vscode = insiders;
    vscodeExtensions = extensions;
  });

  }
```

`nix-build -E "with import <nixpkgs> {}; callPackage ./default.nix {}"  -I nixpkgs=$HOME/nixgits/nixpkgs1`

**Comment by happysalada** [comment]
Let me have a look today

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 133407` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vscode-with-extensions</li>
  </ul>
</details>

**Comment by happysalada** [comment]
Just saying that appart from building I'm trying to actually switch my system to this to see if the locations of the directories make sense.
Briefly looking at the code everything looks okay, but I don't know if the directory paths themselves are correct or not.

**Comment by happysalada** [comment]
Ok, I do not use nix-darwin to manage my vscode (I actually use home-manager).
I've checked about the Nix Apps folder, and how it was working under nix-darwin.
This looks good to me.

**Comment by happysalada** [comment]
@Artturin Thank you for picking up those old PRs!

**Pull request merged**
