### PR TITLE
linux_xanmod: bump stable and edge to latest version

### PR DESCRIPTION
**Pull request by cpcloud**
###### Description of changes

Bumps stable and edge kernels to their respective latest versions.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fortuneteller2k** [comment]
`stable` should be on 5.15.51, in the website it refers to the LTS variant

**Comment by cpcloud** [comment]
Ah ok then. Fixing.

**Review by Atemu — CHANGES_REQUESTED** [review]
Please follow the commit message guidelines.

**Review by Atemu — CHANGES_REQUESTED** [review]
Please take a look at how past commit messages were layed out.

**Comment by cpcloud** [comment]
@Atemu I'm not sure what you're referring to. The commits for xanmod have different commit message formats. Perhaps you can spell out what you want.

```
❯ git log -15 --oneline --grep xanmod --no-merges
5163a2ccf64 (HEAD -> xanmod, origin/xanmod) pkgs.linuxPackages_xanmod: bump stable to 5.15.51 and edge to 5.18.8
58b3f669315 linuxKernels.kernels.linux_xanmod: don't set `-Werror` by default
83171a1dba1 linuxKernels.kernels.linux_xanmod: apply patch from review
d688ec7d80b linuxKernels.kernels.linux_xanmod: import helpers
ecaaba491d4 linuxKernels.kernels.linux_xanmod: adjust config for 5.18
61b37a0a204 linuxKernel.kernels.linux_xanmod_latest: 5.17.8 -> 5.18.1
3fd61ac55ec linuxKernels.kernels.linux_xanmod: 5.15.40 -> 5.15.43
336ee6b108e xanmod-kernels: make myself a maintainer
fe151054ff8 linux_xanmod_latest: 5.17.4 -> 5.17.8
3133e29fcef linux_xanmod: 5.15.35 -> 5.15.40
573127a0f20 linux_xanmod_latest: 5.17.2 -> 5.17.4
97164719dc1 linux_xanmod: 5.15.34 -> 5.15.35
62f67382393 linux_xanmod: 5.15.33 -> 5.15.34
7e318349811 linux_xanmod: 5.15.32 -> 5.15.33
77e6d15276e linux_xanmod_latest: 5.17.1 -> 5.17.2
```

**Comment by fortuneteller2k** [comment]
> @Atemu I'm not sure what you're referring to. The commits for xanmod have different commit message formats. Perhaps you can spell out what you want.
> 
> ```
> ❯ git log -15 --oneline --grep xanmod --no-merges
> 5163a2ccf64 (HEAD -> xanmod, origin/xanmod) pkgs.linuxPackages_xanmod: bump stable to 5.15.51 and edge to 5.18.8
> 58b3f669315 linuxKernels.kernels.linux_xanmod: don't set `-Werror` by default
> 83171a1dba1 linuxKernels.kernels.linux_xanmod: apply patch from review
> d688ec7d80b linuxKernels.kernels.linux_xanmod: import helpers
> ecaaba491d4 linuxKernels.kernels.linux_xanmod: adjust config for 5.18
> 61b37a0a204 linuxKernel.kernels.linux_xanmod_latest: 5.17.8 -> 5.18.1
> 3fd61ac55ec linuxKernels.kernels.linux_xanmod: 5.15.40 -> 5.15.43
> 336ee6b108e xanmod-kernels: make myself a maintainer
> fe151054ff8 linux_xanmod_latest: 5.17.4 -> 5.17.8
> 3133e29fcef linux_xanmod: 5.15.35 -> 5.15.40
> 573127a0f20 linux_xanmod_latest: 5.17.2 -> 5.17.4
> 97164719dc1 linux_xanmod: 5.15.34 -> 5.15.35
> 62f67382393 linux_xanmod: 5.15.33 -> 5.15.34
> 7e318349811 linux_xanmod: 5.15.32 -> 5.15.33
> 77e6d15276e linux_xanmod_latest: 5.17.1 -> 5.17.2
> ```

Ideally the commits should be:

`linux_xanmod: 5.15.43 -> 5.15.51`
`linux_xanmod_latest: 5.18.1 -> 5.18.8`

**Comment by cpcloud** [comment]
Thank you. Doing it now.

**Comment by fortuneteller2k** [comment]
The `LRNG` option needs to be removed.

**Comment by cpcloud** [comment]
> The `LRNG` option needs to be removed.

Is it not still valid for 5.15.51?

**Comment by fortuneteller2k** [comment]
> > The `LRNG` option needs to be removed.
> 
> 
> 
> Is it not still valid for 5.15.51?

Not anymore.

**Comment by thiagokokada** [comment]
@ofborg build linux_xanmod_latest

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
