### PR TITLE
sigil: use qt5's mkDerivation

### PR DESCRIPTION
**Pull request by lightbulbjim**
###### Motivation for this change

Slightly different implementation because out of the box:

  - `$out/bin/sigil` is a shell script wrapper
  - `$out/lib/sigil/sigil` is the ELF executable

See #65399

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @ramkromberg

### CODE REVIEW

**Comment by worldofpeace** [comment]
Can you apply this patch @lightbulbjim? This expression is kinda atypical.

<details><summary>patch</summary>

```diff
diff --git a/pkgs/applications/editors/sigil/default.nix b/pkgs/applications/editors/sigil/default.nix
index 36e9bc757a4..d977599eca1 100644
--- a/pkgs/applications/editors/sigil/default.nix
+++ b/pkgs/applications/editors/sigil/default.nix
@@ -17,18 +17,18 @@ mkDerivation rec {
 
   pythonPath = with python3Packages; [ lxml ];
 
-  propagatedBuildInputs = with python3Packages; [ lxml ];
-
   nativeBuildInputs = [ cmake pkgconfig makeWrapper ];
 
   buildInputs = [
     boost xercesc qtbase qttools qtwebkit qtxmlpatterns
-    python3 python3Packages.lxml ];
+  ];
+
+  dontWrapQtApps = true;
 
   preFixup = ''
-    wrapQtApp "$out/lib/sigil/sigil"
     wrapProgram "$out/bin/sigil" \
-       --prefix PYTHONPATH : $PYTHONPATH:$(toPythonPath ${python3Packages.lxml})
+       --prefix PYTHONPATH : $PYTHONPATH \
+       ''${qtWrapperArgs[@]}
   '';
 
   enableParallelBuilding = true;
@@ -37,7 +37,7 @@ mkDerivation rec {
     description = "Free, open source, multi-platform ebook (ePub) editor";
     homepage = https://github.com/Sigil-Ebook/Sigil/;
     license = licenses.gpl3;
-    maintainers =[ maintainers.ramkromberg ];
+    maintainers = [ maintainers.ramkromberg ];
     platforms = platforms.linux;
   };
 }

```

</details>

**Comment by worldofpeace** [comment]
Can you also remove @RamKromberg from `maintainers` of this package? They haven't contributed since https://github.com/NixOS/nixpkgs/commit/0efd18746abd338d670ab82fa0d9e5411fd53329 so I'd think it's safe to say it's unmaintained.

**Comment by lightbulbjim** [comment]
> Can you apply this patch @lightbulbjim? This expression is kinda atypical.

It works as long as I retain `python3Packages.lxml` in `buildInputs`.

Would it be more idiomatic to use `mkDerivationWith buildPythonApplication` even though it's not a Python app?

> Can you also remove @RamKromberg from maintainers of this package? They haven't contributed since 0efd187 so I'd think it's safe to say it's unmaintained.

Done.

**Comment by worldofpeace** [comment]
> Would it be more idiomatic to use mkDerivationWith buildPythonApplication even though it's not a Python app?

I don't think so, this would add python's `wrapPython` which does something completely different with wrapping `PYTHONPATH` and we use a shell wrapper here. So I'd think it would complicate things.

**Review by worldofpeace — APPROVED** [review]
Starts for me and I checked that the wrapper had the correct entries.

**Pull request merged**
