### PR TITLE
nixos/ibus: allow using the wayland frontend instead of the ibus one

### LINKED ISSUE #300597: IBus module should not set `GTK_IM_MODULE = "ibus"` under gnome
### Describe the bug
IBus module sets `GTK_IM_MODULE = "ibus"`, which causes ibus still leave committed texts on screen in certain apps like gnome-console and nautilus under gnome.

This environment variable should not be set under gnome any longer as it seems that gnome now handles it properly, and setting this variable will break it. (According to [this](https://bugs.eclipse.org/bugs/show_bug.cgi?id=577230) and [this](https://discourse.ubuntu.com/t/ibus-no-more-gtk-im-module-ibus/17727))

### Steps To Reproduce
1. Launch gnome-console with `GTK_IM_MODULE=ibus kgx` and type some random texts, then press left shift.
2. Committed texts leave on screen

### Expected behavior
Committed texts should not leave on screen

### Screenshots
894C94A188C24669A6BC3772FDAB7AEE

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.0-rc1, NixOS, 24.05 (Uakari), 24.05.20240329.d8fe5e6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/cb1gs888vfqxawvc65q1dk6jzbayh3wz-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by 500InternalError**
## Description of changes
Fixes #300597, similar to #278765

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by 500InternalError** [comment]
can anyone review this pr?

**Comment by 500InternalError** [comment]
@K900 I'm terribly sorry to ping you, but can you review this pr?

**Comment by K900** [comment]
I'm not really familiar with ibus stuff, do we have ibus maintainers?

**Comment by 500InternalError** [comment]
I guess no? If we have a maintainer then this pr should have been assigned to someone I guess?

**Comment by K900** [comment]
ofborg doesn't handle NixOS modules, sadly. Paging @ttuegel @yanateras as maintainers of ibus package.

**Comment by zendo** [comment]
Tested, works as expected.

**Comment by ttuegel** [comment]
Is there any way we could set the variables when we're in an X session, and not when we're in a Wayland session? I'm thinking here of the case where someone is switching back and forth between sessions. It would be too bad if this broke their X session.

**Pull request closed without merging**
