### PR TITLE
rebar3: 3.16.0 -> 3.16.1

### PR DESCRIPTION
**Pull request by dlesl**
###### Motivation for this change

This is a security fix so please merge ASAP :)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 124268` at 81b78eb7 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>lfe_1_2</li>
  </ul>
</details>
<details>
  <summary>5 packages built successfully:</summary>
  <ul>
    <li>elixir_ls</li>
    <li>erlang-ls</li>
    <li>lfe (lfe_1_3)</li>
    <li>rebar3</li>
    <li>relxExe</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/tools/build-managers/rebar3/default.nix:42:5:
```
   |
42 |     installPhase = ''
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/development/tools/build-managers/rebar3/default.nix:38:5:
```
   |
38 |     buildPhase = ''
   |     ^
```
</li>
  </ul>
</details>

**Comment by dlesl** [comment]
@jonringer we will need to get this into 21.05 somehow, or is it not too late to get it in via master?

**Comment by DianaOlympos** [comment]
We will need to backport, but that should not be a problem

**Review by DianaOlympos — APPROVED** [review]
Let's merge this ASAP

**Comment by yurrriq** [comment]
works as expected on machine

**Comment by yurrriq** [comment]
I'm not sure of the exact process but I've opened #124300 to hopefully help things along.

**Pull request merged**
