### PR TITLE
python3Packages.ConfigArgParse: 1.2.3 -> 1.3

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 1.3

Also, tests are now enabled.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 113235` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>37 packages built:</summary>
  <ul>
    <li>acpilight</li>
    <li>bashup-events32</li>
    <li>bashup-events44</li>
    <li>certbot (letsencrypt ,python38Packages.certbot)</li>
    <li>certbot-full</li>
    <li>coursera-dl</li>
    <li>gixy</li>
    <li>keepkey_agent (python38Packages.keepkey_agent)</li>
    <li>ledger_agent (python38Packages.ledger_agent)</li>
    <li>linkchecker</li>
    <li>python37Packages.ConfigArgParse</li>
    <li>python37Packages.certbot</li>
    <li>python37Packages.certbot-dns-cloudflare</li>
    <li>python37Packages.certbot-dns-rfc2136</li>
    <li>python37Packages.certbot-dns-route53</li>
    <li>python37Packages.keepkey_agent</li>
    <li>python37Packages.ledger_agent</li>
    <li>python37Packages.libagent</li>
    <li>python37Packages.trezor_agent</li>
    <li>python37Packages.xml2rfc</li>
    <li>python38Packages.ConfigArgParse</li>
    <li>python38Packages.certbot-dns-cloudflare</li>
    <li>python38Packages.certbot-dns-rfc2136</li>
    <li>python38Packages.certbot-dns-route53</li>
    <li>python38Packages.libagent</li>
    <li>trezor_agent (python38Packages.trezor_agent)</li>
    <li>xml2rfc (python38Packages.xml2rfc)</li>
    <li>python39Packages.ConfigArgParse</li>
    <li>python39Packages.certbot</li>
    <li>python39Packages.certbot-dns-cloudflare</li>
    <li>python39Packages.certbot-dns-rfc2136</li>
    <li>python39Packages.certbot-dns-route53</li>
    <li>resholve</li>
    <li>rofimoji</li>
    <li>snakemake</li>
    <li>styx</li>
    <li>yle-dl</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113235` at 1c1da4bd run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>36 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/ec6382230f65cd57340c39a244066976">acpilight</a></li></li>
    <li><a href="https://gist.github.com/c30999ff153248d20ad3c0136625a015">bashup-events32</a></li></li>
    <li><a href="https://gist.github.com/756e00b6994afdc95cf866ac23c001e1">bashup-events44</a></li></li>
    <li><a href="https://gist.github.com/9fbcf82b97f608f84828792992a3fec0">certbot</a></li> (python38Packages.certbot)</li>
    <li><a href="https://gist.github.com/ee26a1cf9c5de0a176eed0a062544893">coursera-dl</a></li></li>
    <li><a href="https://gist.github.com/37484904f1e66cf929b2835b4b6152c2">gixy</a></li></li>
    <li><a href="https://gist.github.com/ed3d0a29da7f2b5e27463dd3900eb1db">keepkey_agent</a></li> (python38Packages.keepkey_agent)</li>
    <li><a href="https://gist.github.com/f55940712f28f0c7cc695be20d50fe22">ledger_agent</a></li> (python38Packages.ledger_agent)</li>
    <li><a href="https://gist.github.com/fc02d244ddbcbc6a869b0d81db8ca0d1">linkchecker</a></li></li>
    <li><a href="https://gist.github.com/ef4acc6aa027e33600457b2a1ca9a5af">python37Packages.ConfigArgParse</a></li></li>
    <li><a href="https://gist.github.com/f98f84fdcb32cfea6752f01363e410c0">python37Packages.certbot</a></li></li>
    <li><a href="https://gist.github.com/55ca4e6199ccf11f2272961aa32885ac">python37Packages.certbot-dns-cloudflare</a></li></li>
    <li><a href="https://gist.github.com/5319a02c386401eafc959ffac06fbdaf">python37Packages.certbot-dns-rfc2136</a></li></li>
    <li><a href="https://gist.github.com/f1326cc2f9c23231234eefacb5f0c16c">python37Packages.certbot-dns-route53</a></li></li>
    <li><a href="https://gist.github.com/57cab787bd6e74ad9809c0ffc31dd98f">python37Packages.keepkey_agent</a></li></li>
    <li><a href="https://gist.github.com/c834bfdd448ff9bf40afc39fd6d077b0">python37Packages.ledger_agent</a></li></li>
    <li><a href="https://gist.github.com/a7159aa0ae2f10ac9ed8b9e90f673be0">python37Packages.libagent</a></li></li>
    <li><a href="https://gist.github.com/54eb59bb2edde95066b3efa25fe92c6a">python37Packages.trezor_agent</a></li></li>
    <li><a href="https://gist.github.com/b427bad92b973e6fa9ecf04b038844e7">python37Packages.xml2rfc</a></li></li>
    <li><a href="https://gist.github.com/3dab7e4a97a0b767d400c21210f3b6a3">python38Packages.ConfigArgParse</a></li></li>
    <li><a href="https://gist.github.com/6592e1588ae322a3e5892d8e2e0c1141">python38Packages.certbot-dns-cloudflare</a></li></li>
    <li><a href="https://gist.github.com/3b223d6486be33bd5b2a6f6c6adf12eb">python38Packages.certbot-dns-rfc2136</a></li></li>
    <li><a href="https://gist.github.com/59b2539359ce882c3043faaebb07c98d">python38Packages.certbot-dns-route53</a></li></li>
    <li><a href="https://gist.github.com/9885aec243a8e54759867723f2b0a87f">python38Packages.libagent</a></li></li>
    <li><a href="https://gist.github.com/ec9acd10464a12d557f559ab0dc99207">trezor_agent</a></li> (python38Packages.trezor_agent)</li>
    <li><a href="https://gist.github.com/b69ee759f72f680aacfde6cbef5a5b02">xml2rfc</a></li> (python38Packages.xml2rfc)</li>
    <li><a href="https://gist.github.com/3f0bac44112518f4866e9a65b9975689">python39Packages.ConfigArgParse</a></li></li>
    <li><a href="https://gist.github.com/464b50157fcec8dc0a750122625ad46b">python39Packages.certbot</a></li></li>
    <li><a href="https://gist.github.com/66618c680230000a5e544b70a3f21290">python39Packages.certbot-dns-cloudflare</a></li></li>
    <li><a href="https://gist.github.com/79d2280f70ad507045d28b1473223b4a">python39Packages.certbot-dns-rfc2136</a></li></li>
    <li><a href="https://gist.github.com/93039d741b1ab3e3de48eb38861e1d5e">python39Packages.certbot-dns-route53</a></li></li>
    <li><a href="https://gist.github.com/e40334b4a4cbb8a599495b1b2ed13528">resholve</a></li></li>
    <li><a href="https://gist.github.com/89541fb280f28c6e5d1063dbb33715ad">rofimoji</a></li></li>
    <li><a href="https://gist.github.com/96906f61c86c47dae951de569364bf96">snakemake</a></li></li>
    <li><a href="https://gist.github.com/1884a36ee89a73c500ad536f4a6e113e">styx</a></li></li>
    <li><a href="https://gist.github.com/1d2bf9dc5661e53f0e7ca88f7f8df930">yle-dl</a></li></li>
  </ul>
</details>

**Review by mweinelt — CHANGES_REQUESTED** [review]
Mismatch between src and meta.homepage.

**Comment by fabaff** [comment]
> Mismatch between src and meta.homepage.

The old meta.homepage entry was redirecting to the new location. Updated to avoid that.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 113235` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
37 packages built:
</summary>
<ul>
<li>bashup-events32</li>
<li>bashup-events44</li>
<li>certbot (python38Packages.certbot)</li>
<li>coursera-dl</li>
<li>keepkey_agent (python38Packages.keepkey_agent)</li>
<li>ledger_agent (python38Packages.ledger_agent)</li>
<li>linkchecker</li>
<li>python37Packages.ConfigArgParse</li>
<li>python37Packages.certbot</li>
<li>python37Packages.certbot-dns-cloudflare</li>
<li>python37Packages.certbot-dns-rfc2136</li>
<li>python37Packages.certbot-dns-route53</li>
<li>python37Packages.keepkey_agent</li>
<li>python37Packages.ledger_agent</li>
<li>python37Packages.libagent</li>
<li>python37Packages.trezor_agent</li>
<li>python37Packages.xml2rfc</li>
<li>python38Packages.ConfigArgParse</li>
<li>python38Packages.certbot-dns-cloudflare</li>
<li>python38Packages.certbot-dns-rfc2136</li>
<li>python38Packages.certbot-dns-route53</li>
<li>python38Packages.libagent</li>
<li>trezor_agent (python38Packages.trezor_agent)</li>
<li>xml2rfc (python38Packages.xml2rfc)</li>
<li>python39Packages.ConfigArgParse</li>
<li>python39Packages.certbot</li>
<li>python39Packages.certbot-dns-cloudflare</li>
<li>python39Packages.certbot-dns-rfc2136</li>
<li>python39Packages.certbot-dns-route53</li>
<li>python39Packages.keepkey_agent</li>
<li>python39Packages.ledger_agent</li>
<li>python39Packages.libagent</li>
<li>python39Packages.trezor_agent</li>
<li>resholve</li>
<li>snakemake</li>
<li>styx</li>
<li>yle-dl</li>
</ul>
</details>

**Pull request merged**
