### PR TITLE
python3Packages.shapely: fix build on darwin

### LINKED ISSUE #107842: python3Packages.shapely: broken on darwin?
**Describe the bug**
python38Packages.shapely does not build for me on darwin. It looks like the previous release, 1.7.0, did build on hydra (https://hydra.nixos.org/build/133213521). I'm not sure if this is a difference depending on the version of shapely or on the version of macosx.

**To Reproduce**
`$ nix-shell -p python38Package.shapely`

**Failure**
```
$ nix-shell -p python38Package.shapely
[...]
running install tests
ImportError while loading conftest '/private/tmp/nix-build-python3.8-Shapely-1.7.1.drv-0/Shapely-1.7.1/tests/conftest.py'.
tests/__init__.py:4: in <module>
    from shapely.geos import geos_version_string, lgeos, WKTWriter
/nix/store/1l2vf26wvfsaddgm9w8ml8891bv0mv79-python3.8-Shapely-1.7.1/lib/python3.8/site-packages/shapely/geos.py:65: in <module>
    free = CDLL('/nix/store/alccnh6365ppv4690rinp7mswalm7gna-Libsystem-osx-10.12.6/lib/libc.dylib').free
/nix/store/c56kq0k3f3rdgkj3s1z5hw0j4ack9gdg-python3-3.8.6/lib/python3.8/ctypes/__init__.py:373: in __init__
    self._handle = _dlopen(self._name, mode)
E   OSError: dlopen(/nix/store/alccnh6365ppv4690rinp7mswalm7gna-Libsystem-osx-10.12.6/lib/libc.dylib, 6): image not found
builder for '/nix/store/vjidc9nms507pyvb7lnbm7gfhkv41m98-python3.8-Shapely-1.7.1.drv' failed with exit code 4
error: build of '/nix/store/vjidc9nms507pyvb7lnbm7gfhkv41m98-python3.8-Shapely-1.7.1.drv' failed
```

It looks like this store path is specifically being added by a nixpkgs patch, but that the patch refers to a file that doesn't exist.

**Additional context**
The're no libc.dylib here:
```
$ ls /nix/store/alccnh6365ppv4690rinp7mswalm7gna-Libsystem-osx-10.12.6/lib/
bundle1.o		crt1.o			lazydylib1.o		libdbm.tbd		libinfo.tbd		libproc.tbd		librpcsvc.tbd
crt0.o			dylib1.10.5.o		libSystem.B.tbd		libdl.tbd		libm.tbd		libpthread.tbd		libutil.tbd
crt1.10.5.o		dylib1.o		libSystem.tbd		libgcc_s.10.4.tbd	libmx.tbd		libresolv.9.dylib	system
crt1.10.6.o		gcrt1.o			libc.tbd		libgcc_s.10.5.tbd	libpoll.tbd		libresolv.dylib
```

**Notify maintainers**
@knedlsepp @dotlambda

**Metadata**
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 16.7.0, macOS 10.12.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(mcgibbon): `"nixpkgs-21.03pre259239.39fe2fc4dc4"`
 - nixpkgs: `/Users/mcgibbon/.nix-defexpr/channels/nixpkgs`
 ```

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change

Fixes https://github.com/NixOS/nixpkgs/issues/107842
cc @rmcgibbo

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by prusnak — APPROVED** [review]
I confirm I was able to reproduce the bug in #107842 and that the commit in this PR fixes it

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107859` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>21 packages failed to build:</summary>
  <ul>
    <li>python37Packages.aplpy</li>
    <li>python37Packages.cartopy</li>
    <li>python37Packages.geopandas</li>
    <li>python37Packages.imgaug</li>
    <li>python37Packages.labelbox</li>
    <li>python37Packages.mask-rcnn</li>
    <li>python37Packages.osmnx</li>
    <li>python37Packages.pyosmium</li>
    <li>python37Packages.spectral-cube</li>
    <li>python38Packages.aplpy</li>
    <li>python38Packages.cartopy</li>
    <li>python38Packages.geopandas</li>
    <li>python38Packages.imgaug</li>
    <li>python38Packages.labelbox</li>
    <li>python38Packages.mask-rcnn</li>
    <li>python38Packages.osmnx</li>
    <li>python38Packages.pyosmium</li>
    <li>python38Packages.spectral-cube</li>
    <li>python39Packages.basemap</li>
    <li>python39Packages.cartopy</li>
    <li>python39Packages.pyosmium</li>
  </ul>
</details>
<details>
  <summary>31 packages built:</summary>
  <ul>
    <li>apache-airflow (python37Packages.apache-airflow)</li>
    <li>buku</li>
    <li>cura</li>
    <li>curaLulzbot</li>
    <li>flatcam</li>
    <li>mapproxy</li>
    <li>python37Packages.basemap</li>
    <li>python37Packages.descartes</li>
    <li>python37Packages.flask-admin</li>
    <li>python37Packages.geoalchemy2</li>
    <li>python37Packages.owslib</li>
    <li>python37Packages.pyproj</li>
    <li>python37Packages.shapely</li>
    <li>python37Packages.uranium</li>
    <li>python38Packages.basemap</li>
    <li>python38Packages.descartes</li>
    <li>python38Packages.flask-admin</li>
    <li>python38Packages.geoalchemy2</li>
    <li>python38Packages.owslib</li>
    <li>python38Packages.pyproj</li>
    <li>python38Packages.shapely</li>
    <li>python38Packages.uranium</li>
    <li>python39Packages.descartes</li>
    <li>python39Packages.flask-admin</li>
    <li>python39Packages.geoalchemy2</li>
    <li>python39Packages.owslib</li>
    <li>python39Packages.pyproj</li>
    <li>python39Packages.shapely</li>
    <li>python39Packages.uranium</li>
    <li>qgis</li>
    <li>qgis-unwrapped</li>
  </ul>
</details>

```
builder for '/nix/store/1yqj2n5nkp1sdvs7hwazgvjbibk7nk53-python3.7-labelbox-2.4.9.drv' failed with exit code 1; last 10 log lines:
adding 'labelbox-2.4.9.dist-info/top_level.txt'
adding 'labelbox-2.4.9.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Finished executing setuptoolsBuildPhase
installing
Executing pipInstallPhase
/build/labelbox-2.4.9/dist /build/labelbox-2.4.9
Processing ./labelbox-2.4.9-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement backports-datetime-fromisoformat==1.0.0 (from labelbox)
ERROR: No matching distribution found for backports-datetime-fromisoformat==1.0.0 
```

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107859` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>flatcam</li>
    <li>python37Packages.mask-rcnn</li>
    <li>python38Packages.mask-rcnn</li>
  </ul>
</details>
<details>
  <summary>19 packages failed to build:</summary>
  <ul>
    <li>apache-airflow (python37Packages.apache-airflow)</li>
    <li>python37Packages.aplpy</li>
    <li>python37Packages.cartopy</li>
    <li>python37Packages.geopandas</li>
    <li>python37Packages.labelbox</li>
    <li>python37Packages.osmnx</li>
    <li>python37Packages.pyosmium</li>
    <li>python37Packages.spectral-cube</li>
    <li>python38Packages.aplpy</li>
    <li>python38Packages.cartopy</li>
    <li>python38Packages.geopandas</li>
    <li>python38Packages.labelbox</li>
    <li>python38Packages.osmnx</li>
    <li>python38Packages.pyosmium</li>
    <li>python38Packages.spectral-cube</li>
    <li>python39Packages.basemap</li>
    <li>python39Packages.cartopy</li>
    <li>python39Packages.labelbox</li>
    <li>python39Packages.pyosmium</li>
  </ul>
</details>
<details>
  <summary>21 packages built:</summary>
  <ul>
    <li>mapproxy</li>
    <li>python37Packages.basemap</li>
    <li>python37Packages.descartes</li>
    <li>python37Packages.flask-admin</li>
    <li>python37Packages.geoalchemy2</li>
    <li>python37Packages.owslib</li>
    <li>python37Packages.pyproj</li>
    <li>python37Packages.shapely</li>
    <li>python38Packages.basemap</li>
    <li>python38Packages.descartes</li>
    <li>python38Packages.flask-admin</li>
    <li>python38Packages.geoalchemy2</li>
    <li>python38Packages.owslib</li>
    <li>python38Packages.pyproj</li>
    <li>python38Packages.shapely</li>
    <li>python39Packages.descartes</li>
    <li>python39Packages.flask-admin</li>
    <li>python39Packages.geoalchemy2</li>
    <li>python39Packages.owslib</li>
    <li>python39Packages.pyproj</li>
    <li>python39Packages.shapely</li>
  </ul>
</details>

**Comment by rmcgibbo** [comment]
LGTM.

**Pull request merged**
