### PR TITLE
proofgeneral_HEAD: fix

### PR DESCRIPTION
**Pull request by Ptival**
###### Motivation for this change

As far as I can tell, the current derivation in master is broken, because of those changes:
https://github.com/ProofGeneral/PG/commit/1a18e33658645a81225c56b5d4f4a4b89434d301
https://github.com/ProofGeneral/PG/issues/177

It seems we don't need a patch anymore as a result.

### CODE REVIEW

**Comment by Ptival** [comment]
@spacekitteh did you not run into this issue with
https://github.com/NixOS/nixpkgs/pull/25695
?

**Comment by gebner** [comment]
This PR broke the default `proofgeneral` package which still references the `pg.patch` file.  I'm not familiar with proofgeneral versioning, should we make HEAD the default or revert the patch deletion?

**Comment by Ptival** [comment]
@gebner woops, that was a bad oversight on my part!

I think we should probably keep the 4.4 around, in case HEAD ever breaks, it's good to have a more stable fallback no?

At least for now, let's revert the patch deletion. Should I:
- revert this commit, then submit a new commit that does the other fixes w/o removing the patch
or
- just make a new commit to restore the patch
?

**Comment by gebner** [comment]
> just make a new commit to restore the patch

I think that's the way to go here.

**Pull request merged**
