### PR TITLE
jemalloc: 5.0.1 -> 5.1.0

### PR DESCRIPTION
**Pull request by loskutov**
###### Motivation for this change
new jemalloc upstream release

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- - Built several manually: rustc, cargo, clickhouse, mariadb, okular. The automated CI is probably better at this than my laptop.
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build jemalloc

**Comment by xeji** [comment]
Changelog: https://github.com/jemalloc/jemalloc/releases
Let's build a few packages directly depending on this (no, I won't try firefox :smile: )
@GrahamcOfBorg build neovim rsyslog mariadb

**Comment by loskutov** [comment]
Oops, it looks like it should be now broken for AArch32 as `--disable-thp` was removed.

**Comment by xeji** [comment]
neovim is broken on aarch64 without this PR, unrelated issue.

**Comment by xeji** [comment]
> Oops, it looks like it should be now broken for AArch32 as --disable-thp was removed.

True. But we don't officially support aarch32 anyway.

**Comment by loskutov** [comment]
As stated in changelog, jemalloc 5.1 avoids MADV_HUGEPAGE on ARM, so removing this option should be fine

**Comment by xeji** [comment]
just to make sure:
@GrahamcOfBorg build jemalloc

**Comment by xeji** [comment]
Thank you, LGTM.

**Pull request merged**
