### PR TITLE
python3Packages.aiosmb: 0.2.41 -> 0.2.44

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 0.2.44

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 125237` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>22 packages built:</summary>
  <ul>
    <li>python38Packages.aiosmb</li>
    <li>python38Packages.certvalidator</li>
    <li>python38Packages.lsassy</li>
    <li>python38Packages.minikerberos</li>
    <li>python38Packages.msldap</li>
    <li>python38Packages.oscrypto</li>
    <li>python38Packages.pypykatz</li>
    <li>python38Packages.signify</li>
    <li>python38Packages.snowflake-connector-python</li>
    <li>python38Packages.snowflake-sqlalchemy</li>
    <li>python38Packages.winsspi</li>
    <li>python39Packages.aiosmb</li>
    <li>python39Packages.certvalidator</li>
    <li>python39Packages.lsassy</li>
    <li>python39Packages.minikerberos</li>
    <li>python39Packages.msldap</li>
    <li>python39Packages.oscrypto</li>
    <li>python39Packages.pypykatz</li>
    <li>python39Packages.signify</li>
    <li>python39Packages.snowflake-connector-python</li>
    <li>python39Packages.snowflake-sqlalchemy</li>
    <li>python39Packages.winsspi</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 125237` at 59f0b563 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>22 packages built successfully:</summary>
  <ul>
    <li>python38Packages.aiosmb</li>
    <li>python38Packages.certvalidator</li>
    <li>python38Packages.lsassy</li>
    <li>python38Packages.minikerberos</li>
    <li>python38Packages.msldap</li>
    <li>python38Packages.oscrypto</li>
    <li>python38Packages.pypykatz</li>
    <li>python38Packages.signify</li>
    <li>python38Packages.snowflake-connector-python</li>
    <li>python38Packages.snowflake-sqlalchemy</li>
    <li>python38Packages.winsspi</li>
    <li>python39Packages.aiosmb</li>
    <li>python39Packages.certvalidator</li>
    <li>python39Packages.lsassy</li>
    <li>python39Packages.minikerberos</li>
    <li>python39Packages.msldap</li>
    <li>python39Packages.oscrypto</li>
    <li>python39Packages.pypykatz</li>
    <li>python39Packages.signify</li>
    <li>python39Packages.snowflake-connector-python</li>
    <li>python39Packages.snowflake-sqlalchemy</li>
    <li>python39Packages.winsspi</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/oscrypto/default.nix:38:3:
```
   |
38 |   meta = with lib; {
   |   ^
```
</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 125237` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>22 packages built:</summary>
  <ul>
    <li>python38Packages.aiosmb</li>
    <li>python38Packages.certvalidator</li>
    <li>python38Packages.lsassy</li>
    <li>python38Packages.minikerberos</li>
    <li>python38Packages.msldap</li>
    <li>python38Packages.oscrypto</li>
    <li>python38Packages.pypykatz</li>
    <li>python38Packages.signify</li>
    <li>python38Packages.snowflake-connector-python</li>
    <li>python38Packages.snowflake-sqlalchemy</li>
    <li>python38Packages.winsspi</li>
    <li>python39Packages.aiosmb</li>
    <li>python39Packages.certvalidator</li>
    <li>python39Packages.lsassy</li>
    <li>python39Packages.minikerberos</li>
    <li>python39Packages.msldap</li>
    <li>python39Packages.oscrypto</li>
    <li>python39Packages.pypykatz</li>
    <li>python39Packages.signify</li>
    <li>python39Packages.snowflake-connector-python</li>
    <li>python39Packages.snowflake-sqlalchemy</li>
    <li>python39Packages.winsspi</li>
  </ul>
</details>

**Comment by fabaff** [comment]
@ofborg eval

**Pull request merged**
