### PR TITLE
Fix detection of changed template unit specializations in switch-to-configuration.pl

### PR DESCRIPTION
**Pull request by oddlama**
###### Description of changes

Currently, template unit specializations were ignored when determining whether a unit has changed.
This means that any instanciated services of template units (e.g. `microvm@a-specific-instance.service` from base `microvm@.service`) would not restart on switch, if the change was to a specialization of a specific instance instead of a change to the base service:

```nix
{
  systemd.services."microvm@a-specific-instance" = {
    overrideStrategy = "asDropin";
    # Changes in here were not detected.
  };
}
```

This fixes adds unit specialization support to the unit parsing logic.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by oddlama** [comment]
> Could you also add respective test cases to `switchTest` to prevent future regressions?

I've added new test cases which I *believe* should be correct, but they currently fail because there seem to be some new `.slice` units that get generated and restarted as-well. I'm not familiar enough with the details of systemd to know whether that is to be expected (and should be added to the assertions) or whether it isn't.

Ignoring the slice units, there might be an (unrelated ?) bug hiding in `switch-to-configuration.pl` that also causes the new tests to fail. I named all unit instances in the test like `someunit@instance.service`, but the script seems to be hallucinating unit instances named `someunit@multi-user.service` and tries to start them. The affected units are exactly those instances that have `wantedBy = ["multi-user.target"]`. Since those only show up in the list of restarted units *as observed* by `get_active_units()`, I believe this is unrelated to my change. Unfortunately this is too deep into the details of systemd for me to be able to figure this out without guidance, so any pointers are highly appreciated.

<details>
<summary>Failed test output</summary>

```
(finished: must succeed: /nix/store/641lmcaylhy3qydm8682gx0rxg6c44lh-nixos-system-machine-23.05pre-git/specialisation/restart-and-reload-by-activation-script/bin/switch-to-configuration test 2>&1, in 16.32 seconds)
The haystack that will cause the following exception is:
---
stopping the following units: test.service
activating the configuration...
setting up /etc...
setting up tmpfiles
starting the following units: no-restart-service.service, reload-triggers-and-restart-by-as.service, simple-reload-service.service, simple-restart-service.service, simple-service.service, templated-no-restart-service@instance.service, templated-reload-triggers-and-restart-by-as@instance.service, templated-simple-reload-service@instance.service, templated-simple-restart-service@instance.service, templated-simple-service@instance.service
the following new units were started: no-restart-service.service, reload-triggers-and-restart-by-as.service, reload-triggers-and-restart.service, reload-triggers.service, simple-reload-service.service, simple-restart-service.service, simple-service.service, system-templated\x2dno\x2drestart\x2dservice.slice, system-templated\x2dreload\x2dtriggers.slice, system-templated\x2dreload\x2dtriggers\x2dand\x2drestart.slice, system-templated\x2dreload\x2dtriggers\x2dand\x2drestart\x2dby\x2das.slice, system-templated\x2dsimple\x2dreload\x2dservice.slice, system-templated\x2dsimple\x2drestart\x2dservice.slice, system-templated\x2dsimple\x2dservice.slice, templated-no-restart-service@instance.service, templated-reload-triggers-and-restart-by-as@instance.service, templated-reload-triggers-and-restart@multi-user.service, templated-reload-triggers@multi-user.service, templated-simple-reload-service@instance.service, templated-simple-restart-service@instance.service, templated-simple-service@instance.service

---
Test "restart and reload by activation script" failed with error: "Expected string 'the following new units were started: no-restart-service.service, reload-triggers-and-restart-by-as.service, reload-triggers-and-restart.service, reload-triggers.service, simple-reload-service.service, simple-restart-service.service, simple-service.service, templated-no-restart-service@instance.service, templated-reload-triggers-and-restart-by-as@instance.service, templated-reload-triggers-and-restart@instance.service, templated-reload-triggers@instance.service, templated-simple-reload-service@instance.service, templated-simple-restart-service@instance.service, templated-simple-service@instance.service
' was not found"
cleanup
```

</details>

<details>
<summary>Formatted version with line breaks and my annotations</summary>

```ruby
# This list is what I would expect. All templated-* units are new and were restarted correctly.
starting the following units:
no-restart-service.service
reload-triggers-and-restart-by-as.service
simple-reload-service.service
simple-restart-service.service
simple-service.service
templated-no-restart-service@instance.service
templated-reload-triggers-and-restart-by-as@instance.service
templated-simple-reload-service@instance.service
templated-simple-restart-service@instance.service
templated-simple-service@instance.service

the following new units were started:
no-restart-service.service
reload-triggers-and-restart-by-as.service
reload-triggers-and-restart.service
reload-triggers.service
simple-reload-service.service
simple-restart-service.service
simple-service.service
# Are these .slice files fine? And if so, do we want to assert they are there or are they just "systemd implementation details" that we don't care about?
system-templated\x2dno\x2drestart\x2dservice.slice
system-templated\x2dreload\x2dtriggers.slice
system-templated\x2dreload\x2dtriggers\x2dand\x2drestart.slice
system-templated\x2dreload\x2dtriggers\x2dand\x2drestart\x2dby\x2das.slice
system-templated\x2dsimple\x2dreload\x2dservice.slice
system-templated\x2dsimple\x2drestart\x2dservice.slice
system-templated\x2dsimple\x2dservice.slice
templated-no-restart-service@instance.service
templated-reload-triggers-and-restart-by-as@instance.service
# #### HERE ####
# What happened here??
# Although the correct units are in the restart list above, the instance name seems to have been altered (multi-user instead of instance). The corresponding services have `wantedBy=multi-user.service`.
templated-reload-triggers-and-restart@multi-user.service
templated-reload-triggers@multi-user.service
templated-simple-reload-service@instance.service
templated-simple-restart-service@instance.service
templated-simple-service@instance.service
```
</details>

**Comment by oddlama** [comment]
Sorry for the delay, I kind of forgot that this PR was still open. I've now finished the necessary test cases to make sure that this is working as expected.

(The @multi-user issue came from an unfinished test case that was setting wantedBy on the base unit instead of the instance specialization)

**Review by dasJ — APPROVED** [review]
LGTM, tests test everything imo.

Added some docs for completeness.

If there are no objections, I plan to merge this in the coming days.
Also posted this to #nixos-systemd

**Comment by dasJ** [comment]
@ofborg test switchTest

**Pull request merged**
