### PR TITLE
aldente: 1.24.1 -> 1.27.3

### PR DESCRIPTION
**Pull request by stepbrobd**
## Description of changes

aldente: 1.24.1 -> 1.27.3

move package to `pkgs/by-name`

also formatted with nixfmt-rfc-style

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by loky-lp** [comment]
I'm afraid that this pr is obsolete, at the time of writing the latest release is the [`1.27.3`](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/releases/tag/1.27.3).

I would like to contribute to speed up the release, but I'm new to this repository, how can I contribute to this pr?

**Comment by pbsds** [comment]
Perhaps consider opening a new PR, or maybe stepbrod wants to update this one?

The reason i didn't merge back in june is because i'm unable to test this, lacking a darwin machine. If I get a confirmation that the bump not only builds but also runs then i'm happy to merge.

**Comment by stepbrobd** [comment]
Result of `nixpkgs-review pr 296701` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>aldente</li>
  </ul>
</details>

**Comment by loky-lp** [comment]
Hey @pbsds, i have a darwin machine (M2 Pro, macOs 14.5 to be precise).
How can i test this and give feedback back to you?

**Comment by pbsds** [comment]
I assume `nix run github:nixos/nixpkgs/refs/pull/296701/merge#aldente` will do the trick

**Comment by stepbrobd** [comment]
> I assume `nix run github:nixos/nixpkgs/refs/pull/296701/merge#aldente` will do the trick

This probably won’t work because ‘mainProgram’ is not set for Aldente.

I think the best way check this would be checking out this PR, build the package and ‘open -a /result/Applications/Aldente.app’

**Comment by pbsds** [comment]
you're free to trade `nix run` for `nix build` or `nix shell` as neccesary :)

**Comment by loky-lp** [comment]
`nix build --impure` and a manual installation did the trick.
Everything seems to work fine.

Screenshot 2024-08-15 alle 09 53 12

**Pull request merged**
