### PR TITLE
pulumi-bin: 3.5.1 -> 3.6.0

### PR DESCRIPTION
**Pull request by t0yv0**
###### Motivation for this change

Pulumi update: 3.5.1 to 3.6.0

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by t0yv0** [comment]
@austinbutler PTAL

**Comment by austinbutler** [comment]
Result of `nixpkgs-review pr 129445` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pulumi-bin</li>
  </ul>
</details>

**Review by austinbutler — APPROVED** [review]

**Comment by austinbutler** [comment]
@t0yv0 out of curiosity do you use Nix/NixOS at Pulumi/what drives you to be kind enough to update the Pulumi packages here?

**Comment by t0yv0** [comment]
I'm a Pulumi dev on the Platform team and I use nix to manage my Mac OS dev environment, so I use this every day and I share the updates I need.

**Pull request merged**
