### PR TITLE
glibc: improve configure options

### PR DESCRIPTION
**Pull request by ajs124**
###### Description of changes
see https://sourceware.org/bugzilla/show_bug.cgi?id=27872
and https://www.gnu.org/software/libc/manual/html_node/Configuring-and-compiling.html

This should maybe be merged together with some other glibc change(s).

I don't have any CET hardware to test this on, but Arch Linux enables this as well.

###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
Raising the minimum kernel version requirement can break a lot of people's installation, I remember that happening when Arch Linux did the same.

**Comment by NickCao** [comment]
Raising the minimum kernel version requirement can break a lot of people's installation, I remember that happening when Arch Linux did the same.

**Comment by NickCao** [comment]
Raising the minimum kernel version requirement can break a lot of people's installation, I remember that happening when Arch Linux did the same.

**Comment by ajs124** [comment]
Interesting. Do you know what they raised it to and what kind of breakage happened? I think 3.2 is quite conservative.

**Comment by NickCao** [comment]
Relevant bug report: https://bugs.archlinux.org/task/69563, looks like my memory has drifted a bit, more a glibc bug than a packaging issue. But anyway there has to be some people out there using nixpkgs on centos 7 or what and stuck on a 3.x kernel.

**Comment by ajs124** [comment]
So… 3.10, then? Or I can drop the commit and we can stick with 3.2.

**Comment by NickCao** [comment]
> "The higher the version number is, the less compatibility code is added, and the faster the code gets."

Are there benchmark results on this? Code size is generally not an issue, but I'm interested in the performance benefits.

**Comment by mweinelt** [comment]
Can we not make centos 7 the support goal for our unstable distro and the upcoming release? Why can't these users use a channel version that works for them?

**Comment by NickCao** [comment]
Personally I would prefer going all the way up to 4.4 just like Arch Linux does, but that decision should require more thorough considerations. Arch Linux is normally used as an distribution that runs on it's own, while nixpkgs serves more than NixOS itself. For reference, ubuntu, arguably the most widely used distribution for containers, is also on 3.2.0: https://git.launchpad.net/~ubuntu-core-dev/ubuntu/+source/glibc/tree/debian/sysdeps/linux.mk

**Comment by symphorien** [comment]
It's really useful to use nix to install new stuff on shared compute servers running old centos kernels, to the point that we have patches to make glibc accept 2.6.32 kernels: https://github.com/NixOS/nixpkgs/blob/1487fabf6091f169a4d70b5cf4dd3b89072aec1f/pkgs/development/libraries/glibc/common.nix#L88-L116

cc @veprbl

**Comment by Mic92** [comment]
Tested `hello` and `python3` binary on a `11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz` (has CET).

**Pull request merged**
