### PR TITLE
nixos/rngd: Remove module entirely, leave an explanation

### PR DESCRIPTION
**Pull request by nicoonoclaste**
###### Motivation for this change

@shlevy's [request] on #96092:

> Perhaps we should remove rngd altogether, but this is the only hardware that rngd helps for anyway.
> If someone explicitly enables it presumably they want it for their devices?

TL;DR of the relevant discussions:

- rngd was auto-enabled for devices that the kernel handles on its own anyhow.
- The rngd module had no affordances to work with devices that the kernel doesn't automatically recognise as hardware RNGs, o it couldn't do anything useful for any user.
- We disabled it by default, but the module is still hanging around; it's both technical debt and might mislead users.

[request]: https://github.com/NixOS/nixpkgs/pull/96092#issuecomment-678826635

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] No NixOS test(s) for this module exist ~~if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))~~
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] ~~Tested execution of all binary files~~ N/A
- [x] ~~Determined the impact on package closure size~~  N/A
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
- [x] Removed uses of `rngd` in modules `hyperv-guest` and `swap`.
- [x] Ensured that relevant documentation is up to date
- [ ] Rebuilding/checking the manual.

### CODE REVIEW

**Comment by nbraud** [comment]
@worldofpeace 16b6c4b was me editing the manual blind, so feel free to push fixed to this PR branch if I did the DocBook wrong.

**Review by shlevy — APPROVED** [review]

**Comment by worldofpeace** [comment]
I can update the manual no problem :+1:

**Comment by worldofpeace** [comment]
BTW, you can build the whole manual like
```
nix-build nixos/release.nix -A manualHTML.x86_64-linux 
```

**Comment by worldofpeace** [comment]
However that should only be needed for local dev because we have a github action to build that manual https://github.com/NixOS/nixpkgs/blob/master/.github/workflows/manual-nixos.yml

**Comment by worldofpeace** [comment]
Thanks for doing this @nbraud :sparkles:

**Comment by nbraud** [comment]
Thanks for reviewing, @worldofpeace <3

**Pull request merged**
