### PR TITLE
Correct NetworkManager documentation

### PR DESCRIPTION
**Pull request by nmikhailov**
This might be confusing for new users

### CODE REVIEW

**Comment by lethalman** [comment]
I could even agree, but then all the nix code still references `services.networkmanager`.

**Comment by nslqqq** [comment]
@lethalman , maybe I am missing something, but https://github.com/NixOS/nixpkgs/blob/release-14.12/nixos/modules/services/networking/networkmanager.nix states that option is ```networking.networkmanager```. Thanks

**Comment by lethalman** [comment]
Oh, ok :) Merged thanks.

**Comment by nslqqq** [comment]
Maybe it will be good idea to somehow merge it in 14.12, so we will have correct [on-site](http://nixos.org/nixos/manual/) documentation.

**Comment by lethalman** [comment]
Done.

**Pull request merged**
