### PR TITLE
Remove Qt 5.14

### PR DESCRIPTION
**Pull request by ttuegel**
###### Motivation for this change

Qt 5.14 is no longer supported upstream.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This can't be removed yet because it would break a lot of programs on darwin cause we can't use 5.15 there because we need to update the apple sdk.

**Comment by ttuegel** [comment]
> This can't be removed yet because it would break a lot of programs on darwin cause we can't use 5.15 there because we need to update the apple sdk.

This being the case, then we need to move macOS back to a version that still has upstream support (Qt 5.12.9).

@NixOS/qt-kde Are any of the current maintainers using Darwin?

**Comment by FRidh** [comment]
There's an increasing amount of packages for which the new sdk is needed.

I don't use darwin.

**Comment by SuperSandro2000** [comment]
> This being the case, then we need to move macOS back to a version that still has upstream support (Qt 5.12.9).

This could break some packages. Maybe we can wait until the SDK update is in.

**Comment by willcohen** [comment]
@ttuegel looking at this a little further -- how would you feel about bumping darwin's support from 5.12 to 5.14? The justification given earlier in this PR is that 5.12 still had LTS support, while 5.14 was unsupported. At this point, 5.12 is no longer supported either. Given two non-ideal situations, maybe it's still at least better to get darwin by default up to 5.14 so it's running on a circa-2019 EOL library rather than a circa-2019 EOL library.

**Comment by ttuegel** [comment]
That's probably a good idea!

**Comment by willcohen** [comment]
PR at: https://github.com/NixOS/nixpkgs/pull/168524

**Pull request closed without merging**
