### PR TITLE
firefox: 91.0 -> 91.0.1; firefox-esr-91: 91.0esr -> 91.0.1esr; firefox-esr-78: 78.12.0esr -> 78.13.0esr

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change
https://www.mozilla.org/en-US/firefox/91.0.1/releasenotes/
https://www.mozilla.org/security/advisories/mfsa2021-37/

https://www.mozilla.org/en-US/firefox/78.13.0/releasenotes/
https://www.mozilla.org/security/advisories/mfsa2021-34/

Untested

###### Things done

- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
They all build.

**Comment by vcunat** [comment]
The tests as well, and I used `firefox` for a while.  (all x86_64 NixOS only)

**Comment by mweinelt** [comment]
Built 91.0.1, 91.0.1esr, 78.13.0esr on x86_64 and 91.0.1 on aarch64.
NixOS Firefox tests seem stuck on audio again. :shrug:

**Comment by ajs124** [comment]
> nixosTests.firefox-esr -> /nix/store/k03yhxwcjhcx27gc4dkzh9rz3xdyzr9s-vm-test-run-firefox

succeeded for me

**Comment by mweinelt** [comment]
Thunderbird :shrug:

**Comment by yu-re-ka** [comment]
> Thunderbird

Should we revert https://github.com/NixOS/nixpkgs/pull/130116/commits/711d674e1322a8ccdbf985322468da87a141bc9c and re-apply it just before the 21.11 release to make backporting easier in the meanwhile? It's just a cosmetic change to not have `ffversion` in the thunderbird `packages.nix`.

**Comment by mweinelt** [comment]
I don't really mind, I just forgot.

**Pull request merged**
