### PR TITLE
treewide: Purge most parseDrvName

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

I added a `lib.getName` to match `lib.getVersion`, which helped make most of these not necessary.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by c0bw3b — CHANGES_REQUESTED** [review]
~~Not fit for master~~ ha ofBorg led me to believe it was a mass rebuild, my bad

Has there been any testing done?

**Comment by Ericson2314** [comment]
@c0bw3b I "tested" by ensuring basically no hashes were changed. The ones that were changed were intentional name -> pname changes.

**Comment by Ericson2314** [comment]
Ah it could be `getPName` or something though. I didn't think of that / realize there was more than one good name.

**Comment by jonringer** [comment]
true, a "name" of a derivation is usually "${pname}-${version}" so the function `getName` is expected to get the pname-version pair.

**Pull request merged**
