### PR TITLE
kustomize: 3.3.1 -> 3.8.0

### PR DESCRIPTION
**Pull request by jlesquembre**
###### Motivation for this change
Version update

###### Things done
tree removed, since doesn't look necessary
buildDate flag removed. If unset, the default date is 1/1/1970, which is
common practice when building nix packages

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Review by zaninime — APPROVED** [review]
Isn't kustomize now officially part of kubectl as well? Do we need to keep a separate package for it? Otherwise LGTM.

**Comment by jlesquembre** [comment]
yes, kustomize is part of kubectl, but it doesn't get any updates. On latest kubectl, kustomize is still on version 2. As long as nothing changes, it makes sense to me to keep a separate package

**Comment by zaninime** [comment]
@marsam could this be merged too? thanks.

**Pull request merged**
