### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dotlambda** [comment]
> This caused multiple build problems in practice, so for now I pushed 3d979f4.

I don't think there are still many packages that break due to 05232ab. Many fixes from https://github.com/NixOS/nixpkgs/pull/54186 are included in this PR. Which packages do you expect 3d979f4 to fix?

**Comment by dotlambda** [comment]
> Is there some best practice around this?

I think none is needed as using `python.pkgs.pkgconfig` instead of `pkgs.pkgconfig` will lead to a build failure in the future.
The only thing we should be worried about is adding an attribute to `python.pkgs` that already exists in top-level `pkgs`.

**Comment by vcunat** [comment]
> Which packages do you expect 3d979f4 to fix?

All I've seen were contained in your commit.  I wanted to avoid tracking all of them down personally, especially as I can't immediately see which of the two pkgconfigs they need (or if both).

**Comment by vcunat** [comment]
I'm afraid darwin is still in a too bad shape: https://hydra.nixos.org/eval/1503346?filter=darwin&compare=1503325&full=#tabs-now-fail

**Comment by 7c6f434c** [comment]
It looks like singular puts its headers in a weird location now, which also breaks sage. Not sure why.

It is a staging-only problem:
https://hydra.nixos.org/job/nixpkgs/staging-next/sage.x86_64-linux
https://hydra.nixos.org/job/nixpkgs/staging/sage.x86_64-linux
https://hydra.nixos.org/job/nixpkgs/trunks/sage.x86_64-linux

https://hydra.nixos.org/api/scmdiff?rev2=379c3899a59df74a2359b34f80604416a25bae05&uri=https%3A%2F%2Fgithub.com%2FNixOS%2Fnixpkgs.git&type=git&branch=&rev1=ab8e72b7bb24d73a588d9783240a1d0154a50ff7 — singular doesn't seem to be mentioned in the diff…

**Comment by vcunat** [comment]
> Which packages do you expect 3d979f4 to fix?

Some was missed: 6ae1cc2 (found via `ffado` build failure); hopefully there won't be many more.

**Comment by vcunat** [comment]
The sage problem was also from the same group.  @dotlambda: I must say I'm still not really convinced about the advantages of *not* propagating the `pkg-config` command from `python*Packages.pkgconfig`, but I'm keeping that as it is.

**Comment by dotlambda** [comment]
> I must say I'm still not really convinced about the advantages of _not_ propagating the `pkg-config` command from `python*Packages.pkgconfig`, but I'm keeping that as it is.

The advantage is that people only use the Python package when it's really needed. It's also a general scheme people should learn. E.g. pythonPackages.graphviz had the same problem: https://github.com/NixOS/nixpkgs/pull/52523. There, it makes even more sense not to propagate since the package is also used at runtime.

**Comment by FlorianFranzen** [comment]
I would like to ask to include #54486, which fixes Python's ```sysconfig``` module again.

**Comment by vcunat** [comment]
@FlorianFranzen: that's a huge rebuild, unfortunately, and the issue seems to be present in master already, so I'd think we leave that to the next iteration (i.e. the usual staging workflow).

**Comment by FlorianFranzen** [comment]
@vcunat Ok, thanks. I created #55519 to get that going then.

**Pull request merged**
