### PR TITLE
gnuradio: 3.7.7.1 -> 3.7.8

### PR DESCRIPTION
**Pull request by offlinehacker**

### CODE REVIEW

**Comment by offlinehacker** [comment]
Travis OOM

**Comment by bjornfor** [comment]
Are you sure this is the final version? I didn't find any release announcement. (Just worried about upstream changing the tarball right after hydra grabs a snapshot of it and we end up missing some bugfix for a while.)

**Comment by bjornfor** [comment]
nox-review on local machine succeeded.

**Comment by offlinehacker** [comment]
Not sure, we can wait a bit before merging.

V ned., 23. avg. 2015 6:01 pop. je oseba Bjørn Forsman <
notifications@github.com> napisala:

**Pull request merged**
