### PR TITLE
niftyreg: init at 1.3.9; niftyseg: init at 1.0.0

### PR DESCRIPTION
**Pull request by bcdarwin**
###### Motivation for this change

New packages based on work by Linus Heckemann.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [NA] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build NiftyReg NiftySeg

**Comment by Mic92** [comment]
@GrahamcOfBorg build niftyreg niftyseg

**Comment by lheckemann** [comment]
This doesn't seem to support aarch64 (tries to use `emmintrin.h`, SSE2 intrinsics i.e. x86-specific), so `meta.platforms` should probably be set to `["x86_64-linux"]` rather than platforms.linux. Other than that, LGTM!

**Comment by bcdarwin** [comment]
@lheckemann -- fixed for niftyreg (niftyseg seems to have built OK).

**Comment by lheckemann** [comment]
Thanks!

**Pull request merged**
