### PR TITLE
rustup: init at 1.2.0

### PR DESCRIPTION
**Pull request by Mic92**
###### Motivation for this change

use pre-compiled cross compiler + access to nightlies

depends on #24926 

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
I would not include this package in nixpkgs, as we have the mozilla overlay which gives us the very same functionality, but on a nix-level.

I'd opt for rejecting this PR.

**Comment by Mic92** [comment]
Does this overlay provides support cross compiler for targets like x86_64-rumprun-netbsd? I also need components like as used in https://github.com/japaric/xargo

**Comment by matthiasbeyer** [comment]
I honestly don't know, sorry.

**Comment by Mic92** [comment]
Rustup now works with unmodified toolchains on Nixos!

**Comment by Mic92** [comment]
I merge this anyway despite the existence of the overlay, for the following reason:

- the overlay seems to address only native compiler targets
- there are still some performance issues with the self-written toml parser: https://www.mail-archive.com/nix-dev@lists.science.uu.nl/msg36074.html
- rustup is somewhat a defacto standard within the rust community. For people like who works with upstream projects, it is helpful to be able to use the same scripts commands to reproduce a test environment like travis ci.

**Comment by nbp** [comment]
> Does this overlay provides support cross compiler for targets [...]?

Not yet, but we can install extensions for the same target, and installing extension for cross-compiling should be doable by changing a few Nix expressions, as soon as someone is interested in contributing these bits back.

**Comment by retrry** [comment]
How are you using rustup in NixOS setting? Currently I'm trying to use it in nix-shell and I get error, when trying to build my project.

error[E0463]: can't find crate for `std`

**Pull request merged**
