### PR TITLE
nixos/locate: Fix sshfs exclusion

### PR DESCRIPTION
**Pull request by chkno**
###### Motivation for this change
locate should not index sshfs mounts.  These are already intended to be excluded.  Fix the mechanism so they're actually excluded.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by chkno** [comment]
I felt bad not checking the "Tested via one or more NixOS test(s)" box, so I [made](https://github.com/NixOS/nixpkgs/compare/master...chkno:fuse-dot-sshfs-with-test) a [locate test](https://github.com/NixOS/nixpkgs/commit/4dff81b137afe2af46146db9094a1fb52980201f) and [verified this sshfs change](https://github.com/NixOS/nixpkgs/commit/3dd6ba3f9c1c17d68d457a38cc772d8943bc5734).

@SuperSandro2000 , who already reviewed this: Would you prefer that I bring the test into this PR, or create a separate PR for it?

**Comment by SuperSandro2000** [comment]
I think you can just add it to this PR. It fits topic wise.

**Comment by chkno** [comment]
Ok.  Now with tests!

**Comment by symphorien** [comment]
@GrahamcOfBorg test locate

**Comment by symphorien** [comment]
hmmm the test probably needs an entry in nixos/tests/all-tests.nix

**Comment by chkno** [comment]
nixos/tests/all-tests.nix entry added.

**Comment by symphorien** [comment]
@grahamcofborg test locate

**Pull request merged**
