### PR TITLE
prisma: #135934 follow-up corrections

### PR DESCRIPTION
**Pull request by pimeys**
###### Motivation for this change

#135934 was incomplete:

I took the changes @Pamplemousse did, and fixed the last missing pieces to get the prisma binary working. Now it copies the files to the right places, and you should be also able to compile this on darwin.

Added myself as maintainers. I'm working for Prisma and will definitely put some effort for this package to get updates.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Thank you for doing this! (I still feel guilty about merging that non working PR).

Could you add yourself as a maintainer in a separate commit ? (that is usually the process).

And the commit message would look like `prisma: add pimeys as maintainer`.

**Comment by pimeys** [comment]
@happysalada sure thing. Also, what I'm thinking about as a next step is to somehow get the `prisma` package out from the autoupdates, because every time you update `prisma` you must set the `prisma-engines` to the same version.

So this needs more work, but for now it should give you a working `prisma` binary and you can do a `shell.nix`, setting the env vars to the `prisma-engines` install location to get a working dev env.

**Comment by happysalada** [comment]
I see.

taking it out of the node-packages will lead to some code-generation and might be a little controversial. But if it won't work properly without the versions being the same, then that's the only way.

Just so you don't despair, the js part is being worked on intensively at the moment to try to improve the workflow.

**Comment by pimeys** [comment]
Yeah, just running the generator is not that much fun. I went running for one hour and came back to see it still running.

So, if somebody now accidentally updates all packages, the prisma version might be different than engines, leading to a system with undefined behavior. It should not be super broken, but definitely not very nice...

I'm doing soon another PR to 3.1.1 version and fixing the patching system in the engines, but after that I'd like to find a good way to have the prisma and prisma-engines packages in the system, that is easy to update together when a new version gets out, and not having an accidental update of only the js library...

**Comment by pimeys** [comment]
Added myself as a separate commit. When this is merged, I can send the 3.1.1 update as another PR.

I'm thinking, would it be possible to just override the versions in `node-packages/default.nix` to prevent accidental updates?

**Comment by happysalada** [comment]
Thank you!

Probably the way to go is to separate this out of node-packages, recently that is what happened to `mirakurun`. it was a little controversial since it added a yarn.nix generated dependency file that was 17k lines. Essentially if you want to separate this, you have to generate a nix file with node2nix or yarn2nix.

**Comment by happysalada** [comment]
oh, I didn't think about an override of the version. That might be a better alternative actually.
If it works then that is the best way to do this.

**Pull request merged**
