### PR TITLE
starship: 0.10.1 -> 0.12.0

### PR DESCRIPTION
**Pull request by bbigras**
###### Motivation for this change
Fix the [parallel tests on darwin issue](https://github.com/NixOS/nixpkgs/pull/66730#issuecomment-522405995) and other stuff. @lilyball 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

nix path-info -S /nix/store/lax8qmvfkdj634ism8jafw4djvxjsxv6-starship-0.10.1
/nix/store/lax8qmvfkdj634ism8jafw4djvxjsxv6-starship-0.10.1	   35764408

nix path-info -S /nix/store/sb4iaff8xksw7x37b4llbiw0938wvh45-starship-0.11.0
/nix/store/sb4iaff8xksw7x37b4llbiw0938wvh45-starship-0.11.0	   35769720

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM (trivial bump)
executable seems to work
leaf package
```
[4 built, 37 copied (595.2 MiB), 161.4 MiB DL]
https://github.com/NixOS/nixpkgs/pull/66947
1 package were build:
starship
```

**Comment by lilyball** [comment]
Alas, more test failures when building this on macOS 🤦‍♀

**Comment by lilyball** [comment]
Looks like this is already being tracked at https://github.com/starship/starship/issues/199

**Comment by lilyball** [comment]
It seems the test failures boil down to `starship module directory --path=somethingThatDoesntExist` panicking. I'm surprised you were able to build it on NixOS since the check phase fails for me when `HOME=/homeless-shelter` or when building with sandboxing (due to `/etc` not being available).

This is being tracked in https://github.com/starship/starship/issues/199. In the meantime, we could just disable the check phase on the package.

**Comment by jonringer** [comment]
I would first try `HOME=$TMPDIR`, if that doesnt work then, `checkPhase = "cargo test --all --exclude=directory"`. I haven't done too much with rust packages, but there should be a way to selectively disable a subset of tests

**Comment by bbigras** [comment]
> or when building with sandboxing (due to /etc not being available).

That's weird. I'm pretty sure I have sandboxing (it's been enabled by default for a while, right?).

➜ nix run nixpkgs.nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.67, NixOS, 19.03.173310.35841f87afa (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(bbigras): `"home-manager-19.03, unstable-19.09pre188690.8746c77a383"`
 - channels(root): `"nixos-19.03.173310.35841f87afa"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

I'm the one who set `/etc` in that test. It was using `/usr` before and didn't work for me.
I modified the test to list all directories in `/` and I saw:
- /dev
- /etc
- /nix
- /build
- /tmp
- /bin
- /proc

Is there something wrong on my side?

**Comment by bbigras** [comment]
> I would first try HOME=$TMPDIR, if that doesnt work then, checkPhase = "cargo test --all --exclude=directory". I haven't done too much with rust packages, but there should be a way to selectively disable a subset of tests

There's `cargo test -- --skip some_test`

**Comment by lilyball** [comment]
Maybe sandboxing on NixOS allows access to `/etc`? I'm only assuming it disallows it on macOS because the test failed. I'm not sure how to actually test what's available right now.

**Comment by lilyball** [comment]
Looking at https://github.com/NixOS/nix/blob/6924bdf2bf8f50f2e6ec5d490571594450aba13a/src/libstore/sandbox-defaults.sb, the macOS sandbox allows for reading the metadata of `/etc` but does not otherwise allow for reading this directory, which means `starship` will fail as I assume it's looking for `$path/.git`.

**Comment by bbigras** [comment]
The test using `/etc` that I was referring to is `test directory::directory_in_root`. Not `directory::home_directory`.

If you want to list all the directory while in the sandbox you can build starship on the `starship-list-dirs` branch of my fork http://github.com/bbigras/nixpkgs. I added the read_dir() stuff in a new unit test.

**Comment by bbigras** [comment]
If I change `test directory::directory_in_root` to read `/etc2`, create it and run the test with `strace -f` I get:
```
$ rg etc2 strace.txt
6603:[pid  8080] execve("./target/debug/starship", ["./target/debug/starship", "module", "directory", "--path=/etc2"], 0x7f20c0002180 /* 2 vars */ <unfinished ...>
6800:[pid  8080] openat(AT_FDCWD, "/etc2", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
6906:[pid  8080] lstat("/etc2", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
6907:[pid  8080] stat("/etc2/.git", 0x7ffef836f9a0) = -1 ENOENT (No such file or directory)
6908:[pid  8080] stat("/etc2", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
6909:[pid  8080] stat("/etc2/commondir", 0x7ffef836f770) = -1 ENOENT (No such file or directory)
6910:[pid  8080] stat("/etc2/HEAD", 0x7ffef836f770) = -1 ENOENT (No such file or directory)
6922:[pid  8080] write(1, "in \33[1;36m/etc2\33[0m ", 20) = 20
6927:[pid  8079] <... read resumed> "in \33[1;36m/etc2\33[0m ", 32) = 20
```

**Comment by lilyball** [comment]
Listing the contents of `/` isn't helpful, that would only tell you something different if you're building a new FHS userenv (which macOS doesn't even have).

**Comment by bbigras** [comment]
I updated the PR. `directory::home_directory` should be skipped now.

**Comment by lilyball** [comment]
`directory::directory_in_root` still fails on macOS though.

**Comment by bbigras** [comment]
OK I excluded that one too.

**Comment by lilyball** [comment]
This now builds on macOS

```
[2 built, 0.0 MiB DL]
https://github.com/NixOS/nixpkgs/pull/66947
1 package were build:
starship
```

**Review by lilyball — APPROVED** [review]

**Comment by bbigras** [comment]
There's already [another release](https://github.com/starship/starship/releases).
Should I update this PR, open a new one or just wait a couple of days between PRs so I don't waste everyone's time. I don't mind doing a PR for every single releases but I know there's a lot of PRs to be reviewed every day.

**Comment by jonringer** [comment]
I would just bump, rebase, and push. You already went through quite a gauntlet of reviews :)

**Comment by bbigras** [comment]
done

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM
binary seems to work
leaf package

```
[4 built, 0.0 MiB DL]
https://github.com/NixOS/nixpkgs/pull/66947
1 package were build:
starship
```

**Review by lilyball — COMMENTED** [review]
This fails to build on macOS, It needs the `Security` framework now.

```
builder for '/nix/store/nmfi9qzqg6acrkfkcmvfwjcb6kxcggw7-starship-0.12.0-vendor.drv' failed with exit code 1; last 10 log lines:
    Referenced from: /nix/store/2bbgqwpafjv7pzfa0027wkqp9k56s60a-cargo-1.36.0/bin/.cargo-wrapped
    Reason: no suitable image found.  Did find:
  	/System/Library/Frameworks/Security.framework/Versions/A/Security: file system sandbox blocked stat()
  	/System/Library/Frameworks/Security.framework/Versions/A/Security: file system sandbox blocked stat()
  Traceback (most recent call last):
    File "/nix/store/84c6nr9wqk77wlasa0nyxjnp2nj5bxd4-cargo-vendor-normalise/bin/.cargo-vendor-normalise-wrapped", line 42, in <module>
      main()
    File "/nix/store/84c6nr9wqk77wlasa0nyxjnp2nj5bxd4-cargo-vendor-normalise/bin/.cargo-vendor-normalise-wrapped", line 17, in main
      assert list(data.keys()) == ["source"]
  AssertionError
cannot build derivation '/nix/store/vsr8ha88ggagv5f7y34pvl1afsw1vnrl-starship-0.12.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/a654z46clgvl76msiyh009pn41w8g4fm-env.drv': 1 dependencies couldn't be built
[2 built (1 failed), 132 copied (1645.9 MiB), 373.2 MiB DL]
error: build of '/nix/store/a654z46clgvl76msiyh009pn41w8g4fm-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/66947
1 package failed to build:
starship
```

**Comment by lilyball** [comment]
Looking at the derivation, it already includes Security, so I guess the problem is actually that it's referencing the system Security framework rather than the Nix one. I'm not sure what's going on there.

**Comment by lilyball** [comment]
The failure is actually when trying to execute the wrapped `cargo` binary, so maybe something happened upstream.

**Comment by lilyball** [comment]
Ok I've figured out what's going on. This review was done on a different machine, whose `/etc/nix/nix.conf` doesn't match the one on my previous machine (in particular it's missing the `extra-sandbox-paths` that allows access to things like `/System/Library/Frameworks` because darwin impurity requires linking against the system for some of these frameworks). I'm re-running the review on my original machine and I'll figure out how to fix nix.conf on this one later.

**Comment by jonringer** [comment]
darwin sounds fun... :)

**Review by lilyball — APPROVED** [review]
Looks good on darwin.

```
[5 built, 0.0 MiB DL]
https://github.com/NixOS/nixpkgs/pull/66947
1 package were build:
starship
```

The binary executes as well.

**Review by aanderse — APPROVED** [review]
Merging entirely based on the good word of @lilyball and @jonringer. Thanks all!

**Pull request merged**
