### PR TITLE
Default gcc to gcc9

### PR DESCRIPTION
**Pull request by globin**
Successor of #63132, based on it.

This will receive a hydra jobset after the above has been merged.

### CODE REVIEW

**Comment by fpletz** [comment]
Rebased onto current master. Created hydra jobset: https://hydra.nixos.org/jobset/nixpkgs/gcc-9

Already built firefox and its dependencies successfully. This might be an easy bump. \o/

**Comment by FRidh** [comment]
The Hydra builds look good. Is there an intent to merge this in the coming days? Both this branch and staging-next seem ready, so depending on how we merge we will need to do at least one more rebuild of either.

**Comment by fpletz** [comment]
@FRidh Yup, that was our intention. There are still some minor packages that are failing but are difficult to fix. The maintainers have to take care of those.

Since I'm not involved in the current staging processes, when would be the best time to merge in your opinion? We wanted to do another master-merge and eval since we wanted to test if the go aarch64 build fail is finally fixed.

**Comment by FRidh** [comment]
Great! I'm going to merge `staging-next` now/today. I therefore suggest merging this in the current `staging`. Then you have the whole `staging-next` period to further submit fixes before it lands in `master`.

**Comment by FRidh** [comment]
These changes are now in `staging-next` (https://github.com/NixOS/nixpkgs/pull/76705).

**Comment by Ma27** [comment]
Great, thanks!

**Comment by fpletz** [comment]
Awesome! Thanks! :tada:

**Pull request merged**
