### PR TITLE
monophony: 2.3.1 -> 2.4.0

### PR DESCRIPTION
**Pull request by ghost**
## Description of changes
https://gitlab.com/zehkira/monophony/-/compare/v2.3.1...v2.4.0

Result of `nixpkgs-review pr 271970` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>monophony</li>
  </ul>
</details>

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by a-n-n-a-l-e-e** [comment]
> > > Lgtm, but does this now work without libsoup, have you tried?
> > 
> > 
> > i don't understand the question. it still uses libsoup.
> 
> I think after #267733, libsoup might not be a nessicary dependency.

does not work without libsoup.

**Comment by a-n-n-a-l-e-e** [comment]
> Odd. Are you on latest master? As this was merged somewhat recently

that change has nothing to do with anything here.

**Comment by Henry-Hiles** [comment]
> > Odd. Are you on latest master? As this was merged somewhat recently
> 
> that change has nothing to do with anything here.
> 
> branch is synced to [0c6d8c7](https://github.com/NixOS/nixpkgs/commit/0c6d8c783336a59f4c59d4a6daed6ab269c4b361)

Okay, @max-privatevoid said it did here: https://github.com/NixOS/nixpkgs/pull/267733#issuecomment-1823589418

**Comment by a-n-n-a-l-e-e** [comment]
> > > Odd. Are you on latest master? As this was merged somewhat recently
> > 
> > 
> > that change has nothing to do with anything here.
> > branch is synced to [0c6d8c7](https://github.com/NixOS/nixpkgs/commit/0c6d8c783336a59f4c59d4a6daed6ab269c4b361)
> 
> Okay, @max-privatevoid said it did here: [#267733 (comment)](https://github.com/NixOS/nixpkgs/pull/267733#issuecomment-1823589418)

you're welcome to try it yourself.

**Comment by a-n-n-a-l-e-e** [comment]
> Odd. Are you on latest master? As this was merged somewhat recently

the change isn't in master and does not have anything to do with my change. can i get an approval or should i close this PR?

**Comment by Henry-Hiles** [comment]
Sure, ill give an approval

**Review by Henry-Hiles — APPROVED** [review]

**Review by LeSuisse — APPROVED** [review]
Result of `nixpkgs-review pr 271970` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>monophony</li>
  </ul>
</details>

**Pull request merged**
