### PR TITLE
python3Packages.pyairvisual: 5.0.8 -> 5.0.9

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 5.0.9

Change log: https://github.com/bachya/pyairvisual/releases/tag/5.0.9

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 131882` at 6a91cf75 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/fe834eeb70add50bd16c22fc960c16f1">home-assistant</a></li>
    <li><a href="https://gist.github.com/98a3ee1acc6cf59003bfb2b81861b119">python38Packages.pyairvisual</a></li>
    <li><a href="https://gist.github.com/c28ea39204fef3e26511d06f946c96f5">python39Packages.pyairvisual</a></li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by SuperSandro2000** [comment]
I can't test this with home-assistant because python-magic is currently fails with 

```
======================================================================
FAIL: test_descriptions (__main__.MagicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/test/test.py", line 108, in test_descriptions
    self.assert_values(m, {
  File "/build/source/test/test.py", line 53, in assert_values
    self.assertIn(value, expected_value)
AssertionError: 'PDF document, version 1.2, 2 pages' not found in ('PDF document, version 1.2',)

----------------------------------------------------------------------
Ran 16 tests in 0.029s
```

@mweinelt

**Comment by fabaff** [comment]
Starting with a update for `python-magic` in #132000...

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 131882` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.pyairvisual</li>
    <li>python39Packages.pyairvisual</li>
  </ul>
</details>

**Pull request merged**
