### PR TITLE
vesktop: 0.4.1 -> 0.4.2

### PR DESCRIPTION
**Pull request by pluiedev**
## Description of changes
https://github.com/Vencord/Vesktop/compare/v0.4.1...v0.4.2

@Scrumplex @vgskye @getchoo 

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Scrumplex** [comment]
I assume this depends on #263618?

**Comment by Scrumplex** [comment]
Now that #263618 is merged, could you rebase your branch?

**Comment by pluiedev** [comment]
> Now that #263618 is merged, could you rebase your branch?

Done — I wish the web interface rebased instead of merged by default though xD

**Comment by Noodlez1232** [comment]
As a part of the release notes, it mentions that `venmic` works now on arm64, so should the package be re-enabled for aarch64?

**Comment by getchoo** [comment]
this branch should be rebased on master, not merged. otherwise lgtm

**Comment by pluiedev** [comment]
> this branch should be rebased on master, not merged. otherwise lgtm

Yeah well GitHub did a funny

**Comment by ChanceHarrison** [comment]
> this branch should be rebased on master, not merged.

Presumably this PR won't be merged until that happens? Is there something that I or someone can do to help with that @pluiedev?

**Comment by pluiedev** [comment]
> > this branch should be rebased on master, not merged.
> 
> 
> 
> Presumably this PR won't be merged until that happens? Is there something that I or someone can do to help with that @pluiedev?

Rebasing should be very simple, but I've been travelling recently and I don't have a stable enough internet connection to fix the issue — will try to fix tomorrow once I can stop having to deal with broken router configurations 😅

**Comment by pluiedev** [comment]
@Scrumplex has kindly rebased it for me. It should be ready to merge now 😄 

@ChanceHarrison

**Review by Scrumplex — APPROVED** [review]

**Review by getchoo — APPROVED** [review]

**Pull request merged**
