### PR TITLE
mikutter: 3.5.14 -> 3.8.6

### PR DESCRIPTION
**Pull request by midchildan**
###### Motivation for this change
Address #58709

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by midchildan** [comment]
I currently get an error trying to run the result.  I suspect that the reason for this is because the `GIO_EXTRA_MODULES` from `bundlerEnv` is not included. Does anyone know of a way to fix this?

For reference, I will paste the logs below:
```console
$ mikutter
GLib-GObject-CRITICAL **: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed
	from /nix/store/86gvpwylbiqw2g7897qzaihp79094y6z-mikutter-3.8.6/core/plugin/gtk/gtk.rb:70:in `block (2 levels) in <top (required)>'
	from /nix/store/gz1iflxha60p1hc3dy8wkd6c3qr7dm2i-ruby2.5.5-pluggaloid-1.1.1/lib/ruby/gems/2.5.0/gems/pluggaloid-1.1.1/lib/pluggaloid/listener.rb:25:in `call'
	from /nix/store/gz1iflxha60p1hc3dy8wkd6c3qr7dm2i-ruby2.5.5-pluggaloid-1.1.1/lib/ruby/gems/2.5.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:97:in `block (2 levels) in call_all_listeners'
	from /nix/store/gz1iflxha60p1hc3dy8wkd6c3qr7dm2i-ruby2.5.5-pluggaloid-1.1.1/lib/ruby/gems/2.5.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `each'
	from /nix/store/gz1iflxha60p1hc3dy8wkd6c3qr7dm2i-ruby2.5.5-pluggaloid-1.1.1/lib/ruby/gems/2.5.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `block in call_all_listeners'
	from /nix/store/gz1iflxha60p1hc3dy8wkd6c3qr7dm2i-ruby2.5.5-pluggaloid-1.1.1/lib/ruby/gems/2.5.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `catch'
	from /nix/store/gz1iflxha60p1hc3dy8wkd6c3qr7dm2i-ruby2.5.5-pluggaloid-1.1.1/lib/ruby/gems/2.5.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `call_all_listeners'
	from /nix/store/gz1iflxha60p1hc3dy8wkd6c3qr7dm2i-ruby2.5.5-pluggaloid-1.1.1/lib/ruby/gems/2.5.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:49:in `block in call'
	from /nix/store/isaj91k807cq6803ha6398naq96hag3g-ruby2.5.5-delayer-0.0.2/lib/ruby/gems/2.5.0/gems/delayer-0.0.2/lib/delayer/procedure.rb:24:in `run'
	from /nix/store/isaj91k807cq6803ha6398naq96hag3g-ruby2.5.5-delayer-0.0.2/lib/ruby/gems/2.5.0/gems/delayer-0.0.2/lib/delayer/extend.rb:58:in `run_once'
	from /nix/store/isaj91k807cq6803ha6398naq96hag3g-ruby2.5.5-delayer-0.0.2/lib/ruby/gems/2.5.0/gems/delayer-0.0.2/lib/delayer/extend.rb:30:in `run'
	from /nix/store/isaj91k807cq6803ha6398naq96hag3g-ruby2.5.5-delayer-0.0.2/lib/ruby/gems/2.5.0/gems/delayer-0.0.2/lib/delayer.rb:43:in `method_missing'
	from /nix/store/86gvpwylbiqw2g7897qzaihp79094y6z-mikutter-3.8.6/core/plugin/gtk/delayer.rb:10:in `block in boot'
	from /nix/store/86gvpwylbiqw2g7897qzaihp79094y6z-mikutter-3.8.6/core/plugin/gtk/mainloop.rb:10:in `main'
	from /nix/store/86gvpwylbiqw2g7897qzaihp79094y6z-mikutter-3.8.6/core/plugin/gtk/mainloop.rb:10:in `mainloop'
	from /nix/store/86gvpwylbiqw2g7897qzaihp79094y6z-mikutter-3.8.6/mikutter.rb:69:in `boot!'
	from /nix/store/86gvpwylbiqw2g7897qzaihp79094y6z-mikutter-3.8.6/mikutter.rb:105:in `<main>'
```

**Comment by jtojnar** [comment]
Note that we are marking mikutter as broken in https://github.com/NixOS/nixpkgs/pull/57027

**Comment by manveru** [comment]
Can we close this?

**Comment by jtojnar** [comment]
Surpassed by https://github.com/NixOS/nixpkgs/pull/60808

**Pull request closed without merging**
