### PR TITLE
nodePackages.fx: init at 19.0.1

### PR DESCRIPTION
**Pull request by elkowar**
###### Motivation for this change
fx is a command-line utility for json processing and viewing.
It allows you to interactively look at json data, as well as process json data simmilarly to `jq`

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by deviant** [comment]
Was about to package fx myself, then spotted this. cherry-picked; works nicely. +1 on this being added

**Comment by zimbatm** [comment]
looks good to go, it just needs a rebase to fix the merge conflict

**Comment by deviant** [comment]
It also needs updating again; there's been a new release since this PR was made.

**Comment by deviant** [comment]
Since this hasn't been touched in almost two months, I made a new PR that replaces it.

**Pull request closed without merging**
