### PR TITLE
mongodb: fix ssl by upgrading 3.4.22 -> 3.4.24

### PR DESCRIPTION
**Pull request by tricktron**
###### Motivation for this change

The compilation of version 3.4.22 was failing with an ssl error on darwin. Reverting the ssl fix commit and upgrading the version to 3.4.24 fixes the ssl error.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tricktron** [comment]
I reverted the ssl fix commit and updated the version from 3.4.22 -> 3.4.24 which fixes the ssl error. So 3.4.24 compiles now on darwin. Lastly, I also rebased the branch on master to fix merge conflict.

I actually didn't want to create a new pull request. How could I have added my commits to the existing pull request #40082?

**Comment by bachp** [comment]
I think this would make mongodb work again after #80746 was merged.

**Review by bachp — APPROVED** [review]
Tested and working with unifi controller.

**Comment by tricktron** [comment]
> I think this would make mongodb work again after #80746 was merged.

Exactly. Would be nice to have MongoDB working again in Nixpkgs.

**Review by erictapen — CHANGES_REQUESTED** [review]
Thanks!
Including patches in the Nixpkgs tree is the less prefered way. Is there any possibility you could either upstream these patches or `fetchpatch` them from a source like a PR to upstream? If none of this is possible please document in the code where you got the patches from, e.g. wether you composed them yourself or where you found them.

Also could you squash your changes into a single commit? At the moment it would be sufficient to have these changes in one commit in Nixpkgs.

**Comment by bachp** [comment]
@erictapen @tricktron as this is based on the work of @jarjee in #40082 I think it would make sense to create two commits, so each author is credited appropriately.

**Comment by erictapen** [comment]
@bachp For that one can include `Co-Authored-By: jarjee <jarjee@users.noreply.github.com>` in the commit message. This is registered as a commit with two or more authors, e.g. https://github.com/NixOS/nixpkgs/commit/4ea8f051ac2bf8edfdc5e712191fb6e34212a95b.

**Comment by tricktron** [comment]
As @jarjee cherrypicked my fixing commit into his pull request #40082 I am going to close this one.

@erictapen Thanks for your review. Could you address your questions directly at @jarjee in #40082? @Jarjee did most of the work and may be able to answer these questions. I just fixed the last blocking ssl error on darwin for `v3.4`.

**Pull request closed without merging**
