### PR TITLE
Revert #224474, git completion command patching

### PR DESCRIPTION
**Pull request by ShamrockLee**
###### Description of changes

This PR reverts #224474, which patches the command `ls` in Bash scripts used by Git and patches the Bash completion script.

This prevents the command patching from breaking the definition of `__git_complete_revlist_file` where there's a local varible named `ls`, and prevents `__gitcomp_builtin grep` (for `git grep`) to be patched as the `grep` command.

This reverts commits b5d052d438df99d5a80e7c126551656d5ba74f75 and 820dc2a56057bcc396dbddbff6be91e1cec73f6f.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ShamrockLee** [comment]
@ofborg build gitMinimal gitMinimal.passthru.tests

**Comment by andersk** [comment]
The other commit b5d052d438df99d5a80e7c126551656d5ba74f75 from #224474 should be reverted too, because this diff is wrong:

```diff
 _git_grep ()
 {
 	__git_has_doubledash && return
 
 	case "$cur" in
 	--*)
-		__gitcomp_builtin grep
+		__gitcomp_builtin /nix/store/4sd4qx367yqczyrwfvr0p7cd0p5357sf-gnugrep-3.7/bin/grep
 		return
 		;;
 	esac
```

The `grep` argument here was referring to the `git grep` subcommand, not the GNU `grep` binary.

**Comment by ShamrockLee** [comment]
@andersk

Got to implement them again in yet another PR after revert.

Is there a way to test them all?

**Comment by andersk** [comment]
I dunno, I found this one by reading the diff between the source file and the built file.

**Comment by ShamrockLee** [comment]
Thank you for the tip.

**Comment by vcunat** [comment]
`staging` branch more likely, but I can have a look based on rebuild state at the moment when this PR gets ready to merge.   It's really large rebuild; ofBorg says 106k.

**Comment by andersk** [comment]
If we revert both commits (as I think we need to) instead of just the one, Hydra might have most of the builds cached from before?

**Comment by vcunat** [comment]
No, it won't.  That PR was merged three weeks ago.  We normally have multiple mass rebuilds per week.

**Comment by ShamrockLee** [comment]
The data partition on my laptop is corrupted, and I haven't got a useable setup to build and test the execution. The derivation doesn't build on NixOnDroid, but it is more likely a NixOnDroid issue.

Could someone test it for me?

**Comment by ncfavier** [comment]
Can we merge this? I don't think a revert needs much testing since we're just back were we started...

**Comment by ShamrockLee** [comment]
@ofborg build gitMinimal gitMinimal.passthru.tests git git.passthru.tests gitFull gitFull.passthru.tests

**Pull request merged**
