### PR TITLE
Patch Openssh for Roundup #15

### PR DESCRIPTION
**Pull request by grahamc**
###### Motivation for this change

 https://github.com/NixOS/nixpkgs/issues/21457#issuecomment-269619564

cc @vcunat @aneeshusa @LnL7 

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by LnL7 — APPROVED** [review]
looks good to me

**Review by fpletz — APPROVED** [review]

**Comment by grahamc** [comment]
I'm feeling a bit inclined to wait for @vcunat to take a look. What do y'all think?

**Comment by vcunat** [comment]
No need for that, really. If you had a look and are convinced it will work...

**Comment by aneeshusa** [comment]
Just woke up, but the reason I haven't updated openssh yet is I've been waiting for updated GSSAPI patches from upstream (Debian). I ran some quick builds and I couldn't get this to build with GSSAPI enabled, hence why I hadn't made a PR. Can you get this to build with GSSAPI?

If not, we'll need to weigh leaving open CVEs w/ an old version of openssh, or breaking GSSAPI support.

I haven't looked at the systemd stuff yet.

**Comment by vcunat** [comment]
GSSAPI is marked as broken.  It didn't build before update and doesn't build after.

**Comment by aneeshusa** [comment]
I only remember `hpnSupport` being broken, and I remember testing GSSAPI as working when I did #17493; let me double-check...

**Comment by vcunat** [comment]
Yeah, it builds on master and this PR breaks it.

**Comment by aneeshusa** [comment]
I think Debian has updated the GSSAPI patch, looking at the git log for the master branch at https://anonscm.debian.org/cgit/pkg-ssh/openssh.git, if we want to give that a try.

**Comment by aneeshusa** [comment]
Specifically https://anonscm.debian.org/cgit/pkg-ssh/openssh.git/tree/debian/patches/gssapi.patch?id=255b8554a50b5c75fca63f76b1ac837c0d4fb7aa may be an updated version, I believe.

**Comment by vcunat** [comment]
Yes, applies and I'm testing the build already.

**Comment by vcunat** [comment]
@grahamc: second-order PR submitted at https://github.com/grahamc/nixpkgs/pull/5 ;-)

**Comment by aneeshusa** [comment]
Changes around daemonization and testing LGTM as well. Building + testing this locally now.

**Comment by grahamc** [comment]
LMK how it goes @aneeshusa and I'll merge / backport straight away. :)

**Comment by grahamc** [comment]
Also -- I really appreciate all the help on this one.

**Review by aneeshusa — APPROVED** [review]
Built and tested, everything looks good. Thanks for keeping me in the loop!

**Comment by vcunat** [comment]
Nice teamwork :-)

**Pull request merged**
