### PR TITLE
python311Packages.google-auth: 2.17.3 -> 2.18.1

### PR DESCRIPTION
**Pull request by fabaff**
Changelog: https://github.com/googleapis/google-auth-library-python/blob/v2.18.1/CHANGELOG.md

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
This broke build of various `python3Packages.google-cloud-*` &ndash; I think most of the regressions shown in https://hydra.nixos.org/eval/1795238#tabs-now-fail

**Comment by vcunat** [comment]
At a brief glance, version bumps like `2.17.x -> 2.18.y` might better be avoided unless there's some reason for them in this period when "breaking changes" are not allowed.

**Comment by vcunat** [comment]
The impact certainly seems like at least a few hundred broken builds.

**Comment by mweinelt** [comment]
@fabaff @SuperSandro2000 No indication either of you built or tested anything on thiS PR. We are in breaking changes freeze, can we be less reckless until the branch-off, please?

**Comment by fabaff** [comment]
> This broke build of various python3Packages.google-cloud-* 

Sorry,my bad. The changelog didn't mention breaking changes and I let the commit log fool me with `pin urllib3 < 2.0 to avoid breaking changes`.

#232752 or #232850 would both solve the issue at hand.

**Pull request merged**
