### PR TITLE
poedit: 1.5.7 -> 2.2.1

### PR DESCRIPTION
**Pull request by bignaux**
###### Motivation for this change

poedit was not updated since 2013.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bignaux** [comment]
@grahamcofborg build poedit

**Comment by flokli** [comment]
@GrahamcOfBorg build poedit

**Comment by flokli** [comment]
@bignaux built and tested locally. poedit complains loudly and advises against about missing language detection and crowdin integration features.

Is that something we can easily enable, without adding too much runtime dependencies?

**Comment by bignaux** [comment]
Not really, need cdl2 (an old framework https://github.com/CLD2Owners/cld2/ )  and cpptest from microsoft, to get such a poedit "pro" ( https://poedit.net/purchase ) that is not cheap and not testable for me. Really i don't care about this warning, i've used it on gscrabble, that's worked at least better than our 2013 build. Perfect is the enemy of good .

**Comment by flokli** [comment]
Sure, just wanted to ask. Thanks for working on this, merged :-)

**Pull request merged**
