### PR TITLE
llvmPackages_{4,5}: musl compat

### PR DESCRIPTION
**Pull request by dtzWill**
Fix llvm, clang, libcxxClang.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Setting triples is part of one approach for enabling cross-compilation,
but for now only address native compilation and avoid rebuilds.

-----

Prebuilt versions of these are available via cache.allvm.org if that's  useful, details here: https://github.com/NixOS/nixpkgs/pull/34645 ("Quickstart with Binary Cache").

On Nix 2.0 you can probably use a temporary store or something to do this quickly without trusting the ALLVM cache system-wide...

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

An eval issue was introduced in to master, sorry for the false failure.

**Comment by dtzWill** [comment]
0 rebuilds folks, you've got nothing to lose! :smiling_imp:

**Comment by 7c6f434c** [comment]
(looks carefully at the patches to find out the emergent interaction that will create a backdoor after some commit from LLVM repository lands in a 5.x release)

**Comment by 7c6f434c** [comment]
@dtzWill but if you start using such an argument, shouldn't you ask for commit access (or maybe should have asked, some time ago)?

**Comment by dtzWill** [comment]
@7c6f434c yes, and it's been supported and passed along... probably should have pursued it a while back.

Regarding the 5.x changes--do you mean regarding the sharing of the patch? It just seemed to have a bit less clutter, but if that makes things harder to reason about or maintain I'm happy to do something else :).

In my local tree I just copied patches everywhere :grin:.

Anyway, if that's not what you meant please clarify-- even if it's not something that needs addressing now never hurts to learn what others see as style considerations or whatnot :).

**Comment by 7c6f434c** [comment]
It's not a style consideration, I just tried to _imagine_ a situation where not changing anything currently built does not prevent the change from being unsafe in the long run.

**Comment by 7c6f434c** [comment]
Re: access: I think you were asking for it wrong. @domenkozar @rbvermaa which of you is a better repository co-owner to ask?

**Pull request merged**
