### PR TITLE
[staging-next] electron: fix build

### PR DESCRIPTION
**Pull request by alyssais**
## Things done

Just like with Firefox, we need to make sure there's only a single
version of LLVM involved in building Chromium, or we get errors like
this:

	ld.lld: error: Invalid record (Producer: 'LLVM18.1.7' Reader: 'LLVM 17.0.6')

Tested that cross compilation of Electron still works.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by doronbehar — APPROVED** [review]
Diff looks very good. Should be good to go if CI is greener.

**Review by emilylange — COMMENTED** [review]
I think there is a stray `pkgsBuildTarget` in `chromium/default.nix` now:

```diff
diff --git a/pkgs/applications/networking/browsers/chromium/default.nix b/pkgs/applications/networking/browsers/chromium/default.nix
index 317cb7de1011..9ce37e18fa86 100644
--- a/pkgs/applications/networking/browsers/chromium/default.nix
+++ b/pkgs/applications/networking/browsers/chromium/default.nix
@@ -18,7 +18,6 @@
 , cupsSupport ? true
 , pulseSupport ? config.pulseaudio or stdenv.isLinux
 , commandLineArgs ? ""
-, pkgsBuildTarget
 , pkgsBuildBuild
 , pkgs
 }:
```

But besides that, I don't feel confident reviewing this.

The code in question is mostly cross-compilation stuff that Amjoseph did before I joined `chromium.meta.maintainers` and I barely know anything about cross-compilation.

In case it helps other reviewers, the commits that introduced `pkgsBuildTarget` and `llvmPackages_attrName` were part of #229265, specifically c25897c1f327ebba6f73ef7ed6b9b6c93a2f3101 5f3c644b1ad7b73de1888177cea86b44513fb670.

Taking `llvm*` from `rustc` makes sense to me though, for what it's worth.

Thanks :)

**Comment by alyssais** [comment]
> I think there is a stray `pkgsBuildTarget` in `chromium/default.nix` now:

Looks like it's been stray since 5f3c644b1ad7b73de1888177cea86b44513fb670.  I'll remove it.

**Comment by vcunat** [comment]
I confirm `electron` build fixed on x86_64-linux.  Diff looks OK to me, at a glance.

**Comment by vcunat** [comment]
`chromium` build looks broken the same way as before this PR.

**Comment by vcunat** [comment]
FYI, on some versions electron builds are still regressing (since nixpkgs master):
https://hydra.nixos.org/eval/1806937?filter=electron&compare=1806929#tabs-now-fail

**Comment by emilylange** [comment]
`electron_27` and `electron_28` are based on `chromium` `M118` and `M120` respectively.
Those won't build with `clang_18` unless we backport something like https://webrtc-review.googlesource.com/c/src/+/332240 to them.

Can do the backporting, if you want me to.

That should unblock it.

But please be aware that `electron_27` is EOL since 2024-04-16, and `electron_28` since \*checks calendar\* today (2024-06-11).

**Comment by alyssais** [comment]
> FYI, on some versions electron builds are still regressing (since nixpkgs master):
> https://hydra.nixos.org/eval/1806937?filter=electron&compare=1806929#tabs-now-fail

Some patches probably need to be backported to get it to build with LLVM 18,
e.g. https://webrtc.googlesource.com/src/+/267f9bdd53a37d1cbee760d5af07880198e1beef%5E%21/

**Comment by alyssais** [comment]
Ah, so maybe we should just set knownVulnerabilities, and then it'll be irrelevant for Hydra anyway, but people who need old Electron can fix it if they want to?

**Comment by vcunat** [comment]
Yes, I don't think maintenance is really expected on EOL versions.

**Comment by vcunat** [comment]
Quite a few packages depend on these two, so we might e.g. notify their meta.maintainers I guess.

**Pull request merged**
