### PR TITLE
zls: 0.12 -> 0.13

### PR DESCRIPTION
**Pull request by einetuer**
Changelog: https://github.com/zigtools/zls/compare/0.12.0...0.13.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by 0x5a4** [comment]
@figsoda @moni-dz

**Comment by 0x5a4** [comment]
Also, I'd like to become a maintainer of this. But since there already are two of you, I wanted to ask before making the commit?

**Comment by tommasobruno** [comment]
Sorry for the questinon, but I am getting this kind of error
```
error: builder for '/nix/store/wqa96vin6m26qp1msv6nm7rdk3ljhrdk-zig-0.12.0.drv' failed with exit code 2;
       last 10 log lines:
       > 1 error generated.
       > make[2]: *** [CMakeFiles/zigcpp.dir/build.make:76: CMakeFiles/zigcpp.dir/src/zig_llvm.cpp.o] Error 1
       > 1 error generated.
       > make[2]: *** [CMakeFiles/zigcpp.dir/build.make:118: CMakeFiles/zigcpp.dir/src/zig_clang_driver.cpp.o] Error 1
       > 1 error generated.
       > make[2]: *** [CMakeFiles/zigcpp.dir/build.make:104: CMakeFiles/zigcpp.dir/src/zig_clang.cpp.o] Error 1
       > 1 error generated.
       > make[2]: *** [CMakeFiles/zigcpp.dir/build.make:132: CMakeFiles/zigcpp.dir/src/zig_clang_cc1_main.cpp.o] Error 1
       > make[1]: *** [CMakeFiles/Makefile2:91: CMakeFiles/zigcpp.dir/all] Error 2
       > make: *** [Makefile:136: all] Error 2
       For full logs, run 'nix log /nix/store/wqa96vin6m26qp1msv6nm7rdk3ljhrdk-zig-0.12.0.drv'.
error: 1 dependencies of derivation '/nix/store/58hpimfszcz4a3mhs701rrddzbdi6vb8-zig-hook.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8k9a0acvyn4kpmv5shiv7k1ma58didd0-zls-0.12.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/341dx3xfaas5isvyk2v3m3i84lq2pi1m-nix-shell-env.drv' failed to build
```
This is when zig v0.13 and zls v0.12 are used at the same time in a nix shell (using flakes)

**Comment by 0x5a4** [comment]
yeah, zls is very sensitive about mismatching zig versions. 
sadly i cant merge this, we'll just have to wait

**Review by jmbaur — APPROVED** [review]
Works on my machine!

**Comment by HirschBerge** [comment]
Poking remaining approvers. Causes noticeable performance issues on even mid-end hardware because of the mismatch.
Would suggest keeping zig and zls in sync in future.

**Comment by tommasobruno** [comment]
Any update on this? Keep getting warning from zig about zls being 0.12 instead of 0.13.

**Comment by junaid1460** [comment]
any update?

**Comment by jmbaur** [comment]
cc @figsoda

**Comment by 0x5a4** [comment]
Uhm, it seems out of stupidity I've closed this... Will try to reopen :(

**Comment by tommasobruno** [comment]
@figsoda @moni-dz Any update on this?

**Review by jmbaur — APPROVED** [review]
Still works for me (not sure if re-approval is needed after close & re-open)

**Review by markbeep — APPROVED** [review]
Also works on my end (x86_64-linux)

**Review by 0x61nas — APPROVED** [review]
It seems fine to me

> WE NEED TO MERGE THIS

**Pull request merged**
