### PR TITLE
various packages: pin boost179

### PR DESCRIPTION
**Pull request by tobim**
###### Description of changes

https://github.com/NixOS/nixpkgs/pull/244111#issuecomment-1646496575

Pin `boost` to `boost179` for packages currently failing in staging-next.

### CODE REVIEW

**Comment by vcunat** [comment]
As OfBorg noticed, `miopen` won't evaluate
> pkgs/development/libraries/miopen/default.nix:1:1 called with unexpected argument 'boost'

**Comment by vcunat** [comment]
By the way, I generally expected to do these overrides inside the `callPackage` invocations, but perhaps it is better the way you did.

**Comment by vcunat** [comment]
`opendungeons` is still failing to build for me
```
/build/source/source/modes/MenuModeEditorNew.cpp: In member function 'bool MenuModeEditorNew::launchSelectedButtonPressed(const CEGUI::EventArgs&)':
/build/source/source/modes/MenuModeEditorNew.cpp:138:37: error: 'std::string boost::filesystem::extension(const path&)' is deprecated: Use path::extension() instead [-Werror=deprecated-declarations]
  138 |     if (boost::filesystem::extension(level) != ".level") {
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
In file included from include/boost/filesystem.hpp:21,
                 from /build/source/source/modes/MenuModeEditorNew.cpp:36:
include/boost/filesystem/convenience.hpp:29:20: note: declared here
```

**Comment by vcunat** [comment]
I confirm that all the others were failing on Hydra and built for me now.  (all my tests are x86_64 NixOS)

**Comment by vcunat** [comment]
Thanks.  So to clean up the newly-failing list on Hydra, I pushed a commit where I fixed and tested the `miopen*` builds and omitted the `opendungeons` change for now.

**Comment by tobim** [comment]
Integrated as ba2ce6e73bf1e0352d09477854cd30a807b7a296.

**Pull request closed without merging**
