### PR TITLE
[19.03] signal-desktop: 1.26.2 -> 1.27.1 (backport)

### PR DESCRIPTION
**Pull request by primeos**
(cherry picked from commit 042b63dd2cd748f9e2485522df921b7f97349525)
Reason: Avoid an expired (unusable) release in the stable release
(Signal-Desktop releases expire after a few months).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by primeos** [comment]
@GrahamcOfBorg test signal-desktop

**Comment by primeos** [comment]
@ixmatus Regarding your last comment: Feel free to merge this PR if you want and if the test `tests.signal-desktop on x86_64-linux` passes ;)

**Comment by worldofpeace** [comment]
@primeos Perhaps you should add a comment in the expression like?
```
Please backport all updates. signal-desktop has no backwards compatibility and old releases expire.
```

**Comment by primeos** [comment]
@worldofpeace yeah, seems like a good idea to document it in the source-code as well. I'll try to come up with something later today and add some more details.

**Comment by primeos** [comment]
@GrahamcOfBorg test signal-desktop

**Comment by blitz** [comment]
I've just tested this. And it works for normal messaging. :+1:

**Comment by primeos** [comment]
@blitz awesome, thanks! :)

@worldofpeace I've added the comment in 5d1abc68e7b1025e90f993711319aa3058ac70d6.

**Pull request merged**
