### PR TITLE
lsof: 4.91 -> 4.93.2

### PR DESCRIPTION
**Pull request by averelld**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @dezgeg

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS (2 packages broken on master)
diff LGTM
executable seems to work

```
[52 built (5 failed), 1099 copied (6997.6 MiB), 1114.8 MiB DL]
error: build of '/nix/store/1gjpasid24ljx03ryqgbrzgqfdbdihhz-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/67658
3 package are marked as broken and were skipped:
python27Packages.nixpart python37Packages.blivet python37Packages.nixpart

2 package failed to build:
python37Packages.dftfit python37Packages.nixpart0

39 package were build:
adafruit-ampy argus ecryptfs enpass gitAndTools.gitAnnex gitAndTools.git-annex-metadata-gui gitless orca lsh lsof magic-wormhole pantheon.elementary-session-settings paperless python27Packages.bitbucket_api python27Packages.blivet python27Packages.magic-wormhole python27Packages.monty python27Packages.nixpart0 python27Packages.pymatgen python27Packages.python-dotenv python27Packages.python-packer python27Packages.sh python27Packages.sumo python27Packages.txtorcon python37Packages.git-annex-adapter python37Packages.lammps-cython python37Packages.monty python37Packages.pymatgen python37Packages.pymatgen-lammps python37Packages.python-dotenv python37Packages.python-packer python37Packages.sh python37Packages.sumo python37Packages.txtorcon spaceFM tahoe-lafs tgt tor-arm transporter
```
PR for one of the broken packages located here: #67665

**Comment by mmahut** [comment]
@GrahamcOfBorg build lsof

**Comment by mmahut** [comment]
``Darwin``:

``
applying patch /nix/store/z8ldknl7n2511d2qixxgxgga0x8iq52y-no-build-info.patch
patching file usage.c
applying patch /nix/store/9ci7i9agyhbmdkvxcjk5xzjsycjg5cc0-darwin-dfile.patch
patching file dialects/darwin/libproc/dfile.c
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file dialects/darwin/libproc/dfile.c.rej
builder for '/nix/store/a73fs4k8hx0rm9i6nz21z4mryyc9mnr7-lsof-4.93.2.drv' failed with exit code 1
error: build of '/nix/store/a73fs4k8hx0rm9i6nz21z4mryyc9mnr7-lsof-4.93.2.drv' failed
``

**Comment by averelld** [comment]
Redundant patch removed.

**Comment by mmahut** [comment]
@GrahamcOfBorg build lsof

**Pull request merged**
