### PR TITLE
Update nginx to 1.10.0

### PR DESCRIPTION
**Pull request by nckx**
CC maintainers @thoughtpolice @7c6f434c.
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nckx** [comment]
This of course has the weird side-effect of `nginxUnstable` being older that `nginx`.

**Comment by zimbatm** [comment]
Thanks ! `nixpkgsUnstable` should probably be removed if you want to make another PR

**Comment by nckx** [comment]
I'll alias nginxUnstable to 1.10.0, so someone else (or me) can point it to the next development branch when it appears.

**Comment by zimbatm** [comment]
Good idea. Feel free to ping me in the PR.

**Comment by nckx** [comment]
I wasn't going to bother with a PR to be honest (since no-one objected here).

**Pull request merged**
