### PR TITLE
hello: 2.10 -> 2.12

### PR DESCRIPTION
**Pull request by trofi**

### CODE REVIEW

**Comment by trofi** [comment]
`pkgsMusl.hello` regressed on tests:

```
hello> FAIL: tests/multibyte-1
hello> =======================
hello> 1c1
hello> < hello: conversion to a multibyte string failed: Invalid or incomplete multibyte or wide character
hello> ---
hello> > hello 世界
hello> FAIL tests/multibyte-1 (exit status: 1)
```

Switching to draft.

**Comment by trofi** [comment]
Disabled 2 tests on musl, sent report upstream to bug-hello@. I think it's a bug in tests. I hope it will eventually show up in https://lists.gnu.org/archive/html/bug-hello/2022-01/threads.html

**Comment by trofi** [comment]
2.12 release fully fixed musl tests.

**Comment by zowoq** [comment]
This broke `stdenvBootstrapTools.x86_64-darwin.test` which is now blocking nixpkgs-unstable.

I opened a PR to revert this for now: https://github.com/NixOS/nixpkgs/pull/158328

**Comment by trofi** [comment]
Do you have a build log? I tried to click through https://hydra.nixos.org/job/nixpkgs/trunk/stdenvBootstrapTools.x86_64-darwin.test and found no logs. Only "Aborted, unexpected EOF".

**Comment by zowoq** [comment]
Reverted the revert with a workaround for the failing test: https://github.com/NixOS/nixpkgs/pull/158517.

**Pull request merged**
