### PR TITLE
python3Packages.dash*: bump

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
closes #93885

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
python2 failure is from cryptography==3

```
https://github.com/NixOS/nixpkgs/pull/94851
1 package failed to build:
python27Packages.dash

11 packages built:
python27Packages.dash-core-components python27Packages.dash-renderer python27Packages.dash-table python37Packages.dash python37Packages.dash-core-components python37Packages.dash-renderer python37Packages.dash-table python38Packages.dash python38Packages.dash-core-components python38Packages.dash-renderer python38Packages.dash-table
```

**Comment by FRidh** [comment]
You could add the reverse dependencies to `passthru.tests`. That way r-ryantm and ofborg will fail.

**Comment by jonringer** [comment]
I'm not the original maintainer, just trying to get PRs in before branch off

**Comment by jonringer** [comment]
the tests can be done by the maintainer

**Pull request merged**
