### PR TITLE
turso-cli: 0.87.2 -> 0.87.4

### PR DESCRIPTION
**Pull request by tstachl**
## Description of changes

Updated version to v0.87.4

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kashw2** [comment]
Hi, thanks for your contribution!

Could you please squash the merge commit into one and also change the remaining commit  to `turso-cli: 0.87.2 -> 0.87.4`, same with the title of the PR?

Thanks

**Comment by tstachl** [comment]
I was trying to avoid that because my internet is pretty bad and downloading a local copy of `nixpkgs` is going to take forever. But let me see what I can do :) Thanks for the instructions btw.

**Comment by tstachl** [comment]
@kashw2 I know it's not your process but I just want to point out that this is stupid. It has taken me a few hours so far just to contribute an updated version and two updated sha hashes.

**Comment by tstachl** [comment]
And I'm giving up.

**Comment by kashw2** [comment]
Respectfully,  this PR  prior to being abandoned didn't just update a version and sha. It touched multiple files and had a diff of 3000+ lines of code. 

The contribution guidelines that are followed are in place to stop mistakes like this from being made unconsciously and also serve to allow automated tools like our faithful Ofborg to perform the correct tests to attempt to ensure stability in nixpkgs.

I'd encourage you to reattempt this, perhaps investigate using `nix-update` to perform this change from a clean branch off of master or to reset this branch to the head of master and to run `nix-update turso-cli`.

**Pull request closed without merging**
