### PR TITLE
glibc: 2.35-224 -> 2.37-8

### PR DESCRIPTION
**Pull request by Ma27**
###### Description of changes

__Note:__ very early draft, but opening it to track the work and to avoid potentially duplicated efforts.
cc @lovesegfault @vcunat 

Also, can anybody create a Hydra jobset for me, please?

Announcements:
https://sourceware.org/pipermail/libc-alpha/2022-August/141193.html
https://sourceware.org/pipermail/libc-alpha/2023-February/145190.html

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
Jobset: https://hydra.nixos.org/jobset/nixpkgs/pr-188492-glibc-2.36
(but it looks pretty bad for now)

**Comment by Ma27** [comment]
> (but it looks pretty bad for now)

I mean where's the fun if everything would've built fine already :upside_down_face: 

But to be serious: I didn't expect it to fail that early, but the problem appears to be GCC: https://hydra.nixos.org/build/189053872/nixlog/1/tail
I'll take a look soonish. But I mean given that it breaks so much so early, creating a jobset for this change was appropriate %)

**Comment by zhaofengli** [comment]
Also we _might_ want to consider applying the patch to [re-enable `DT_DASH` in the glibc `.so`](https://github.com/archlinux/svntogit-packages/commit/e1d69d80d07494e3c086ee2c5458594d5261d2e4) like what Arch does. If we decide to do so, we should re-evaluate by the time 23.05 comes.

- https://github.com/ValveSoftware/Proton/issues/6051
- https://blog.hiler.eu/win32-the-only-stable-abi

**Comment by Ma27** [comment]
@vcunat so I just fixed a few more failing builds, updated glibc to the latest rev from 2.36 and pulled in latest upstream/staging. Let's see what the next Hydra evaluation says, but it seems quite good IMHO.

Do you think it makes sense to add `aarch64-linux` as second system to see if we're missing something obvious there?

**Comment by vcunat** [comment]
Yes why not, added.  (that also triggered evaluation)

**Comment by vcunat** [comment]
So, glibc 2.36 missed NixOS 21.11, right?  https://github.com/NixOS/nixpkgs/issues/194208#issuecomment-1280122825

**Comment by Ma27** [comment]
Yep, but I didn't have the energy last week to finish this anyways :shrug:

**Comment by Ma27** [comment]
Rebased another time, rustc on arm should be fixed again, let's see how much is actually broken now.

**Comment by Ma27** [comment]
OK, just updated to 2.37 which doesn't seem to have much breakage API-wise. Rebased `upstream/staging` from last evening into this branch and ensured that all fixes that are now on this branch are still valid.
After that I managed to build quite much, i.e. I got to `chromium`, `firefox`, `postgresql`, `kubernetes` (for go stuff) and a simple VM test. I'll need to check if @zhaofengli's comment is still relevant and find a solution for it, await one round of Hydra to check if I have missed something obvious (even though https://hydra.nixos.org/eval/1789260 with 101317 succeeding vs 7082 failing looked quite promising already) and then we could discuss if we want to merge it before the staging freeze (cc @vcunat @RaitoBezarius @mweinelt @trofi )

**Comment by vcunat** [comment]
##### DT_HASH

It looks like upstream glibc won't back this out and distros patch it instead.  Not a situation I'm happy about, but that seems to be practically the only down-side of keeping DT_HASH (as it was before 2.36).  Distros do this in various ways, e.g. https://src.fedoraproject.org/rpms/glibc/c/1cd731cf293a236f70ed6d54ff711d6a1342a3d3?branch=rawhide (from a glibc developer)

Long-term prospects don't seem great to me, as any "patch" causes some maintenance burden and older games surely aren't expected to get updates to fix this on their side.

**Comment by vcunat** [comment]
> Rebased `upstream/staging` from last evening into this branch and ensured that all fixes that are now on this branch are still valid.

Latest `staging` isn't generally a great base for looking at regressions on Hydra, because you're mixing staging's regressions with the PR's regressions.

**Comment by Ma27** [comment]
Considering that many other distros do this too I figured it's OK for us to do the same, I simply re-used the patch from ArchLinux (which is basically the reversed form of the commit that was bisected in the valve/proton thread linked above).

> Long-term prospects don't seem great to me, as any "patch" causes some maintenance burden and older games surely aren't expected to get updates to fix this on their side.

Agreed. For now I think it's OK and we'll see what others do that have the same burden.

> Latest staging isn't generally a great base for looking at regressions on Hydra, because you're mixing staging's regressions (often not yet known at that point) with the PR's regressions.

I got quite far yesterday, though. But yeah, since the window before the freeze is slowly closing, I guess I'll rebase it onto the common base of staging & staging-next and trigger an eval on hno after that.

**Comment by vcunat** [comment]
I restarted all failed, as aarch64-linux machines tend to have extra free time lately.

**Comment by vcunat** [comment]
Sounds good enough for `staging`.  I rechecked that stdenv still builds on the merge result, as stdenv bootstrapping changed noticeably in the meantime.

**Comment by vcunat** [comment]
Thanks.

**Comment by stephank** [comment]
> An obvious problem is swift: https://hydra.nixos.org/build/214392116 (error is reproducible on x86_64-linux). I've never used swift, so no idea about that, but I'd say that swift isn't a sufficiently large subsystem to block on that, IMHO the swift maintainers should figure out a solution during zhf (but I'll give them a heads-up now, cc @stephank @Trundle @dduan @trepetti @dtzWill ).

The error there is a simple JSON parse error, which is caused by the extra warning output. I'm not yet sure where that `direct reference to protected function` output is coming from, though. That's not coming from glibc either, is it?

**Comment by vcunat** [comment]
> TSCUtility/Triple.swift:209: Fatal error: Failed to parse target info (malformed).

FYI, this regression will most likely very soon get to master+unstable (and 23.05).

**Comment by stephank** [comment]
> FYI, this regression will most likely very soon get to master+unstable (and 23.05).

It's unfortunate, but I don't have the bandwidth to investigate this right now. What time I find is spent on the Swift 5.8 upgrade. Hopefully that magically fixes it, but probably not. Maybe we can do a 23.05 backport later when we have a fix, but until then we'll have a broken Swift on Linux unless someone else can take a look. I agree it's not a blocker.

**Comment by stephank** [comment]
#225197 fixes the Linux build. I did not find a direct cause, but found issues with CMake >=3.25 in general, so suspect that's what fixed it. (I created an upstream PR. They use an older version of CMake in CI, so didn't notice.)

**Pull request merged**
