### PR TITLE
shotcut: 20.09.13 -> 20.10.31

### PR DESCRIPTION
**Pull request by woffs**
###### Motivation for this change
see https://github.com/mltframework/shotcut/releases/

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wentasah** [comment]
I run the shotcut binary on NixOS and it works as expected.

**Comment by woffs** [comment]
rebased to master and disabled the upgrade prompt

**Comment by woffs** [comment]
Updated to recent version, rebased to master, and tested build and binary execution under x86_64

**Comment by peti** [comment]
Why is this a draft?

**Comment by woffs** [comment]
> Why is this a draft?

Just forgot to un-draft after updating and testing.

**Pull request merged**
