### PR TITLE
ollama: 0.2.8 -> 0.3.0

### PR DESCRIPTION
**Pull request by redyf**
## Description of changes
Set for pre-release
https://github.com/ollama/ollama/releases/tag/v0.3.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by abysssol — APPROVED** [review]
I updated the hash to release. Also tested ollama by running tinydolphin.

**Comment by noggynoggy** [comment]
This update is a game changer for Ollama. I am patiently waiting for the approval :D I don't like Docker

**Comment by Steinhagen** [comment]
It's already merged in.

**Comment by noggynoggy** [comment]
> It's already merged in.

For some reason nix flake update still results in 2.8 for me, but I just used overriteAttr in the mean time :+1: 

```nix
{ pkgs, pkgs-unstable, lib, ... }: 
let
  p = pkgs-unstable.ollama.overrideAttrs (oldAttrs: rec {
    inherit (oldAttrs) pname;
    version = "3.0.0";
    src = pkgs.fetchFromGitHub {
      owner = "ollama";
      repo = "ollama";
      rev = "v${version}";
      hash = "sha256-69CpRAggx6a1NJq+CA9QliXuUbDgC1ERRuA3y17KVAM=";
      fetchSubmodules = true;
    };   
  });
in {
  environment.systemPackages = [ p ];
  services.ollama = {
    package = p;
    enable = true;
    # ...
    };
  };
}
```

**Comment by redyf** [comment]
> > It's already merged in.
> 
> For some reason nix flake update still results in 2.8 for me, but I just used overriteAttr in the mean time 👍
> 
> ```nix
> { pkgs, pkgs-unstable, lib, ... }: 
> let
>   p = pkgs-unstable.ollama.overrideAttrs (oldAttrs: rec {
>     inherit (oldAttrs) pname;
>     version = "0.3.0";
>     src = pkgs.fetchFromGitHub {
>       owner = "ollama";
>       repo = "ollama";
>       rev = "v${version}";
>       hash = "sha256-69CpRAggx6a1NJq+CA9QliXuUbDgC1ERRuA3y17KVAM=";
>       fetchSubmodules = true;
>     };   
>   });
> in {
>   environment.systemPackages = [ p ];
>   services.ollama = {
>     package = p;
>     enable = true;
>     # ...
>     };
>   };
> }
> ```

It usually takes a few days for the package to be propagated across nixpkgs, so don't worry. Should be available soon :smile:

**Comment by RoyDubnium** [comment]
As redyf said, the nixpkgs-unstable branch is delayed from the other branches. If you want access to the latest version as soon as it is merged, then you can add a separate input for your system flake that follows the master branch. Then you can use that for ollama.
Example:
```
{
  description = "";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixpkgs-unstable";
    nixpkgs-latest.url = "github:nixos/nixpkgs?ref=master";
  };

  outputs = inputs@{ 
  self, 
  nixpkgs,
  nixpkgs-latest,
  ...
  }:
  let
    system = "x86_64-linux";
    pkgs = nixpkgs.legacyPackages.${system};
  in
  {
    nixosConfigurations.nixos = nixpkgs.lib.nixosSystem rec {
      system = "x86_64-linux";
      specialArgs = {
        pkgs-latest = import nixpkgs-latest {
          inherit system;
          config.allowUnfree = true;
        };
      };
      modules = [
        {
          environment.systemPackages = [
            pkgs-latest.ollama # or put this in configuration.nix
          ];
        }
      	./configuration.nix
      ];
    };
  };
}
```
I'm no nix expert, this is just what I used to keep track of multiple forks and versions.

**Pull request merged**
