### PR TITLE
flutter: 3.10.5 -> 3.13.0

### PR DESCRIPTION
**Pull request by algorithmiker**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hacker1024** [comment]
Not quite ready for review; we still need to restore 3.10.5 and fix the patches for 3.7 (or drop it) as there are a couple of packages that have dependency conflicts with 3.13.0

**Review by lukegb — APPROVED** [review]
Happy with the `yubioath-flutter` changes :) Thanks!

**Review by RossComputerGuy — APPROVED** [review]
Works on NixOS M1 Pro machine, good job.

**Comment by karlprieb** [comment]
Hey @gilice for some reason I'm getting hash mismatch for dart 3.1.0 aarch64-darwin when trying to install flutter on aarch64-darwin, maybe dart team reuploaded the source?

**Comment by n8henrie** [comment]
@gilice 

```console
$ nix shell github:nixos/nixpkgs/master#flutter
error: hash mismatch in fixed-output derivation '/nix/store/aqnrbn2jmblh0z4h7zv645hkqw4n1i6n-source.drv':
         specified: sha256-sAWnd09mbcRLP0WjSjjWF7+WQ7LP3tWsq5Kqw8e4APg=
            got:    sha256-EzZOWU/yFQJLjX8ukwhUrWs6Vj4QJ5oVQc5KDC66dTc=
error: 1 dependencies of derivation '/nix/store/xs2azqqkg6b5kfbcqh0r53zhgvq2lsmc-dart-3.1.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/105wsij333z0pwqk4qrarq9rssbvzcps-flutter-3.13.0-unwrapped.drv' failed to build
error: 1 dependencies of derivation '/nix/store/w1ajvvdz9dqms138i9b3f6i8c8plf6zr-flutter-wrapped-sdk-links.drv' failed to build
```

https://github.com/NixOS/nixpkgs/pull/254994

**Pull request merged**
