### PR TITLE
v8: 9.7.106.18 -> 12.5.227.9

### PR DESCRIPTION
**Pull request by LeSuisse**
## Description of changes

3 years worth of upgrade.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by LeSuisse** [comment]
It looks mostly fine but `postgresqlPackages.plv8` fails to build with the latest `v8`. Upgrading `plv8` to the latest version resolves most of the issue except:

```
plv8> Running phase: buildPhase
plv8> build flags: SHELL=/nix/store/306znyj77fv49kwnkpxmb0j2znqpa8bj-bash-5.2p26/bin/bash USE_SYSTEM_V8=1 SHLIB_LINK=-lv8 V8_OUTDIR=/nix/store/va71m87nkgc6znlkm2wp7zr0d9h3indd-v8-12.5.227.9/lib all
plv8> sed -e 's/^#undef PLV8_VERSION/#define PLV8_VERSION "3.2.2"/' plv8_config.h.in > plv8_config.h
plv8> g++ -DJSONB_DIRECT_CONVERSION -Wall -std=c++17 -fno-rtti -O2 -fPIC -Wall -Wno-register -xc++ -I. -I./ -I/nix/store/07s64wxjzk6z1glwxvl3yq81vdn42k40-postgresql-15.7/include/server -I/nix/store/07s64wxjzk6z1glwxvl3yq81vdn42k40-postgresql-15.7/include/internal -I/nix/store/zfi1y943q15js1ysgl4vk6lp2bzrngn2-icu4c-73.2-dev/include -D_GNU_SOURCE -I/nix/store/37979sqc7yw9ps0c4xl9jjkhq0w1hw8b-libxml2-2.12.7-dev/include/libxml2 -I/nix/store/ks2x6si7bkxb6ay1s80ld1s5997qllpa-lz4-1.9.4-dev/include -I/nix/store/9ynakmwsf7nqhlv3phl05yybc5ad754l-zstd-1.5.6-dev/include  -fPIC -c -o plv8.o plv8.cc
plv8> In file included from /nix/store/va71m87nkgc6znlkm2wp7zr0d9h3indd-v8-12.5.227.9/include/v8-array-buffer.h:12,
plv8>                  from /nix/store/va71m87nkgc6znlkm2wp7zr0d9h3indd-v8-12.5.227.9/include/v8.h:24,
plv8>                  from plv8.h:12,
plv8>                  from plv8.cc:8:
plv8> /nix/store/va71m87nkgc6znlkm2wp7zr0d9h3indd-v8-12.5.227.9/include/v8-local-handle.h: In instantiation of 'v8::Local<T>::Local(v8::Local<S>) [with S = v8::Data; T = v8::Value]':
plv8> plv8.h:226:65:   required from here
plv8> /nix/store/va71m87nkgc6znlkm2wp7zr0d9h3indd-v8-12.5.227.9/include/v8-local-handle.h:269:42: error: static assertion failed: type check
plv8>   269 |     static_assert(std::is_base_of<T, S>::value, "type check");
plv8>       |                                          ^~~~~
plv8> /nix/store/va71m87nkgc6znlkm2wp7zr0d9h3indd-v8-12.5.227.9/include/v8-local-handle.h:269:42: note: 'std::integral_constant<bool, false>::value' evaluates to false
plv8> make: *** [Makefile:100: plv8.o] Error 1
```

It looks like the latest version they test and build is 11.5 and I see no activity to upgrade to v8 12. I'm going to take a closer look the easiest way to resolve this for us might be to introduce a `v8_11`.

**Comment by risicle** [comment]
On macos 12 x86_64:

```
Command: python3 /private/tmp/nix-build-v8-12.5.227.9.drv-0/v8/build/mac/find_sdk.py --print_sdk_path --print_bin_path --print_sdk_build 10.12
Returned 1 and printed out:

/nix/store/ms4bhj33jn7sdrnai7zrq0bbhqfk3q92-xcodebuild-0.1.2-pre/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
/nix/store/ms4bhj33jn7sdrnai7zrq0bbhqfk3q92-xcodebuild-0.1.2-pre/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/

stderr:

Traceback (most recent call last):
  File "/private/tmp/nix-build-v8-12.5.227.9.drv-0/v8/build/mac/find_sdk.py", line 112, in <module>
    sys.exit(main())
             ^^^^^^
  File "/private/tmp/nix-build-v8-12.5.227.9.drv-0/v8/build/mac/find_sdk.py", line 102, in main
    raise Exception('Failed to determine ProductBuildVersion' +
Exception: Failed to determine ProductBuildVersionfor SDK at path /nix/store/ms4bhj33jn7sdrnai7zrq0bbhqfk3q92-xcodebuild-0.1.2-pre/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/System/Library/CoreServices/SystemVersion.plist

See //build/toolchain/mac/BUILD.gn:5:1: whence it was imported.
import("//build/config/mac/mac_sdk.gni")
^--------------------------------------
See //build/config/BUILDCONFIG.gn:749:5: which caused the file to be included.
    action("${target_name}") {
    ^-------------------------
```

**Comment by risicle** [comment]
Our `SystemVersion.plist` only has

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>ProductName</key>
        <string>Mac OS X</string>
        <key>ProductVersion</key>
        <string>11.0</string>
</dict>
</plist>
```

defined, no `ProductBuildVersion`

**Comment by risicle** [comment]
ok, we get past that with

```
--- a/pkgs/development/libraries/v8/default.nix
+++ b/pkgs/development/libraries/v8/default.nix
@@ -16,7 +16,9 @@ let
   };
 
   git_url = "https://chromium.googlesource.com";
-
+  xcbuild' = xcbuild.override {
+    productBuildVer = "20A2408";
+  };
   # This data is from the DEPS file in the root of a V8 checkout.
   deps = {
     "base/trace_event/common" = fetchgit {
@@ -154,7 +156,7 @@ stdenv.mkDerivation rec {
     pkg-config
     python3
   ] ++ lib.optionals stdenv.isDarwin [
-    xcbuild
+    xcbuild'
     llvmPackages.llvm
     python3.pkgs.setuptools
   ];
```

stolen from `pkgs/development/libraries/qt-6/default.nix`, god knows what version `20A2408` is, but that gets us to:

```
clang (LLVM option parsing): Unknown command line argument '-split-threshold-for-reg-with-hint=0'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--unroll-threshold-aggressive=0'?
```

**Comment by risicle** [comment]
The `split-threshold-...` error can be avoided with the patch already present at `pkgs/applications/networking/browsers/chromium/patches/chromium-120-llvm-17.patch`

**Comment by LeSuisse** [comment]
Thanks, duplicated the patch for `v8`.

I did not took the time to investigate the plv8 build issue further for now, it is likely I won't be able to do it until at least Tuesday night.

**Comment by risicle** [comment]
This gets us a bit further until we get `error: no member named 'aligned_alloc' in the global namespace`.. which I'm struggling with because I expected the `FORCE_MAC_SDK_MIN` setting to address that.

**Comment by reckenrode** [comment]
> This gets us a bit further until we get `error: no member named 'aligned_alloc' in the global namespace`.. which I'm struggling with because I expected the `FORCE_MAC_SDK_MIN` setting to address that.

`aligned_alloc` requires at least the 10.15 SDK.

**Comment by risicle** [comment]
Indeed, but I was looking for a way to stop it trying to use `aligned_alloc` as has been done in e.g. https://github.com/NixOS/nixpkgs/blob/a5f800ab48f10417fb626a07c67a10cb4fac33f6/pkgs/development/web/nodejs/nodejs.nix#L57

**Comment by reckenrode** [comment]
It depends on whether v8 is just using aligned allocations or whether it’s actually invoking `aligned_alloc`. The error suggests the latter, but I don’t get any hits on `aligned_alloc` when searching the v8 repo on GitHub.

**Comment by LeSuisse** [comment]
`plv8` is going to be annoying:
* it requires some adjustments to take some v8 changes into account. From an initial look that does not seem too big but this is probably not the kind of patch we want to have to maintain...
* it looks like there are some naming conflicts between v8 and Postgres < 16
* upstream is unlikely to upgrade soon, they build/vendor v8 via [`v8-cmake`](https://github.com/bnoordhuis/v8-cmake) which is still using v8 11
* we do not have a nixpkgs maintainer for the `plv8` package anymore :cry: 

The only viable way I see is to provide a `v8_11` based on [the vendored version of Node 20](https://github.com/nodejs/node/tree/v20.14.0/deps/v8) in order to get the recent security fixes. Hopefully it is close enough to what `plv8` expects and does not require too many build adjustments from the current `v8`.

**Comment by LeSuisse** [comment]
Just realized we already have `nodejs.libv8`. I'm checking to see if we can rely on that everywhere instead of maintaining this standalone `v8` derivation.

**Comment by LeSuisse** [comment]
Closing this in favor of #315851.
It looks like we can use `nodejs.libv8` for all the zone where we currently use `v8`.

**Pull request closed without merging**
