### PR TITLE
megasync: 4.9.0.0 -> 4.10.0.0

### PR DESCRIPTION
**Pull request by bbigras**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ludat** [comment]
bump @michojel :eyes:

**Comment by michojel** [comment]
Thank you @bbigras for the contribution. I'm sorry for the delay. I don't use the package anymore and am no longer a paying customer. Would you be willing to take this package over?
Other than that, there is [4.11.0.0](https://github.com/meganz/MEGAsync/releases/tag/v4.11.0.0_Linux) available.
I should be able to try out this or the newer version over the weekend.

**Comment by ludat** [comment]
As mentioned [here](https://discourse.nixos.org/t/help-to-upgrade-a-package-dependencies-failing-to-build/40697) megasync `>4.9.0.0` always crashes for me almost immediately after starting

**Comment by bbigras** [comment]
4.12.2.0 crashes for me on startup too. reported to https://github.com/meganz/MEGAsync/issues/915 (with no debug symbols).

 4.10.0.0 starts, I was able to log in, but it's stuck at fetching the files' list. I didn't see any crashdump.

**Comment by michojel** [comment]
> 4.12.2.0 crashes for me on startup too. reported to [meganz/MEGAsync#915](https://github.com/meganz/MEGAsync/issues/915) (with no debug symbols).
> 
> 4.10.0.0 starts, I was able to log in, but it's stuck at fetching the files' list. I didn't see any crashdump.

Same here. 5.2.0.0 crashes for me as well.
And 4.11.0.0 also gets stuck at fetching the files list.

If one wants to fix #290949, one can do the following:

```diff
diff --git a/pkgs/applications/misc/megasync/default.nix b/pkgs/applications/misc/megasync/default.nix
index 79800a6c46ee..3e25f1d96f59 100644
--- a/pkgs/applications/misc/megasync/default.nix
+++ b/pkgs/applications/misc/megasync/default.nix
@@ -8,7 +8,6 @@
 , doxygen
 , fetchFromGitHub
 , ffmpeg
-, freeimage
 , libmediainfo
 , libraw
 , libsodium
@@ -98,7 +95,7 @@ mkDerivation rec {
     "--with-cryptopp"
     "--with-curl"
     "--with-ffmpeg"
-    "--with-freeimage"
+    "--without-freeimage"
     "--without-readline"
     "--without-termcap"
     "--with-sodium"
@@ -111,10 +108,10 @@ mkDerivation rec {
   '';

   preBuild = ''
-    qmake CONFIG+="release" MEGA.pro
+    qmake CONFIG+="nofreeimage release" MEGA.pro
     pushd MEGASync
       lrelease MEGASync.pro
-      DESKTOP_DESTDIR="$out" qmake PREFIX="$out" -o Makefile MEGASync.pro CONFIG+=release
+      DESKTOP_DESTDIR="$out" qmake PREFIX="$out" -o Makefile MEGASync.pro CONFIG+="nofreeimage release"
     popd
   '';
```

As long as one gets past the "fetching the files list".

**Comment by michojel** [comment]
I've tested all newer versions and the only one working for me is 4.9.1.0 (tested on nixos-23.11, Gnome 45, X11). Here's the PR: #302394
I'd appreciate your review.

**Pull request closed without merging**
