### PR TITLE
go-swag: 1.6.7 -> 1.7.1

### PR DESCRIPTION
**Pull request by takeda**
###### Motivation for this change

The version 1.6.7 is quite outdated.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by takeda** [comment]
@StephenWithPH can this be included so it's updated automatically?

**Comment by adisbladis** [comment]
@GrahamcOfBorg eval

**Comment by StephenWithPH** [comment]
@takeda ... I apologize for the long delay in responding. I'm taking a look at this. You prompted me to investigate the automatic update bot [`r-ryantm`](https://ryantm.github.io/nixpkgs-update/r-ryantm/#r-ryantm). I found this:

```
2021-12-07T01:14:30 [version] 
2021-12-07T01:14:30 [version] generic version rewriter does not support multiple hashes
2021-12-07T01:14:30 [rustCrateVersion] 
2021-12-07T01:14:30 [rustCrateVersion] No cargoSha256 found
2021-12-07T01:14:30 [golangModuleVersion] 
2021-12-07T01:14:31 [golangModuleVersion] Found old vendorSha256 = 1i2n2sz2hc89nf2fqfq3swldz0xwrnms4j9q0lrss5gm3bk49q7f
2021-12-07T01:14:40 [golangModuleVersion] Replaced vendorSha256 with sha256-7uBE5hr1Fa0zBThJoqvNvIPfKNcDO+yEswkxKL4WVsQ=
2021-12-07T01:14:49 [golangModuleVersion] Finished updating vendorSha256
2021-12-07T01:14:49 [updateScript] 
2021-12-07T01:14:49 [updateScript] skipping because derivation has no updateScript
2021-12-07T01:14:49 
2021-12-07T01:14:49 [quotedUrls]
2021-12-07T01:14:49 [quotedUrls] nothing found to replace
2021-12-07T01:14:49 Diff after rewrites:
diff --git a/pkgs/development/tools/go-swag/default.nix b/pkgs/development/tools/go-swag/default.nix
index 0a0eb41d613..9343c81027f 100644
--- a/pkgs/development/tools/go-swag/default.nix
+++ b/pkgs/development/tools/go-swag/default.nix
@@ -2,16 +2,16 @@
 
 buildGoModule rec {
   pname = "go-swag";
-  version = "1.6.7";
+  version = "1.7.6";
 
   src = fetchFromGitHub {
     owner = "swaggo";
     repo = "swag";
     rev = "df209afeed2334a97c83aff34ea7abcad85c31f6";
-    sha256 = "17pmcfkcmgjvs4drs0fyhp2m39gw83s0ck3rdzdkgdhrbhva9ksx";
+    sha256 = "sha256-Xc+kNlwZtjfbb3lMBvRA/KVRxYXeAZ0b0Vu+yqZj9Z4=";
   };
 
-  vendorSha256 = "1i2n2sz2hc89nf2fqfq3swldz0xwrnms4j9q0lrss5gm3bk49q7f";
+  vendorSha256 = "sha256-7uBE5hr1Fa0zBThJoqvNvIPfKNcDO+yEswkxKL4WVsQ=";
 
   subPackages = [ "cmd/swag" ];
 

2021-12-07T01:14:49 Source url did not change. 

```
(https://r.ryantm.com/log/github/go-swag/2021-12-07.log)

Looking at [the bot docs](https://ryantm.github.io/nixpkgs-update/nixpkgs-maintainer-faq/#nixpkgs-maintainer-faq):
```
No updateScript and no version

If the derivation file has no version and no updateScript, it will fail.
```


I speculate that the only change needed to get this autoupdating is:
https://github.com/takeda/nixpkgs/blob/07d0e25b49ca818902bfa57bbef8bb57693979d2/pkgs/development/tools/go-swag/default.nix#L10

I found a PR that supports this theory: https://github.com/NixOS/nixpkgs/pull/132221

**Are you amenable to me opening a new PR that cherry-picks your commit adding the version variable?** This will be a good test of the bot.

**Comment by takeda** [comment]
@StephenWithPH Apologies, I missed your comment. Yeah I don't have a problem with creating a new PR, please let me know when you did, so I can close this one.

**Comment by takeda** [comment]
@StephenWithPH actually, after re-reading the logs I believe the problem is that the bot is expecting `rev = "v1.6.7";` but instead it is getting `rev = "df209afeed2334a97c83aff34ea7abcad85c31f6";` I have feeling you might need one PR with updating `rev` to use a tag instead of a hash, before it will start to work.

**Comment by StephenWithPH** [comment]
superseded by #156811

**Pull request closed without merging**
