### PR TITLE
scx: init at 1.0.5

### PR DESCRIPTION
**Pull request by JohnRTitor**
sched_ext is a Linux kernel feature which enables implementing kernel thread schedulers in BPF and dynamically loading them.
This feature got merged in Linux 6.12, this PR adds rust and C userspace schedulers.
Homepage:- https://github.com/sched-ext/scx

With this following packages are now available:

- scx.rustland
- scx.rlfifo
- scx.layered
- scx.lavd
- scx.bpfland
- scx.csheds

Note:
In order to use/test the packages here, you need a kernel with the sched-ext patchset applied. This feature got officially merged in Linux 6.12 (available as `linuxPackages_testing` as of 28-Oct-2024)

Packaging is inspired from [chaotic-nyx flake](https://github.com/chaotic-cx/nyx/tree/main/pkgs/scx).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by liberodark** [comment]
Hi, 

Good to see this feature on nixos.
One question you can switch system76-scheduler (CFS) to SCX (BPF) ?

Best Regards

**Comment by JohnRTitor** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 351746`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 5 packages built:</summary>
  <ul>
    <li>scx.scx_bpfland</li>
    <li>scx.scx_lavd</li>
    <li>scx.scx_layered</li>
    <li>scx.scx_rlfifo</li>
    <li>scx.scx_rustland</li>
  </ul>
</details>

**Comment by JohnRTitor** [comment]
As far as I understand, System76 adjusts Linux CPU scheduler depending on battery level and workload.

Whereas scx is a userspace CPU scheduler with a different concept than System76-scheduler. They are not compatible with each other (I could be wrong though)

**Comment by liberodark** [comment]
Yes sorry my question is badly formulated.
But I hope we can enable this directly in the configuration.nix it would be very convenient for those who want to use it.

**Comment by JohnRTitor** [comment]
@ofborg build scx.rustland scx.rlfifo scx.layered scx.lavd scx.bpfland scx.csheds

**Pull request merged**
