### PR TITLE
Treewide(ish): remove long-time broken pkgs

### PR DESCRIPTION
**Pull request by Mindavi**
###### Description of changes

Remove packages that have been broken for a while.
I didn't add aliases since most of them have been broken for so long that either nobody is using them or those people never update their systems :laughing:.

Note that this is not everything I found, I just cherry-picked a chunk and worked on that.

### CODE REVIEW

**Review by SuperSandro2000 — COMMENTED** [review]
Not sure about not adding aliases but removing them in general is fine for me.

**Comment by Artturin** [comment]
We should codify "packages that have been broken for longer than 2 releases can be removed without adding aliases"

**Comment by Mindavi** [comment]
I think it's fine for packages that have been broken for so long. Nobody cared about them enough to get them fixed, so I don't think they're gonna care if they're dropped.

I just pinged the people working on ue4 though, apparently they've been looking at this on and off since 2016, but so far there's no fix. So I still propose to drop it and let them submit a new version if they ever get around to it.

**Comment by Mindavi** [comment]
Dropped the ue4 removal and linked to the issue in nixpkgs. Not certain if we _really_ want to keep it though. I'd vote for removing it still, if there's no new activity on the derivation.

**Comment by Mindavi** [comment]
nixpkgs-review says:

10 packages removed:
libdap (†3.20.6) multibootusb (†9.2.0) neopg (†0.0.6) openbr (†0.5) openbr (†0.5) openbr (†0.5) pdftk (†2.02) rapcad (†0.9.8) samsung-UnifiedLinuxDriver (†4.00.39) vogl (†2016-05-13)

**Pull request merged**
