### PR TITLE
nixos/kernel.nix: ensure same kernel is used

### PR DESCRIPTION
**Pull request by eadwu**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wizeman** [comment]
I can't tell if this is doing the right thing because I get confused with the overriding mechanisms.
However, I was having the issue described in #86835, which for me meant NixOS wouldn't boot since I was using ZFS boot and root filesystems.
This PR fixed the issue for me.

**Comment by Ekleog** [comment]
Would it be possible to `git commit --amend` to explain why this is required, and how this solves the listed issue?

**Comment by eadwu** [comment]
Yeah a better fix would probably be fixing the `extend` override, but I'm not sure it works.

**Review by hmenke — APPROVED** [review]
The careless use of `super` is a common antipattern that you also see a lot in user overlays on the internet.  If in an overlay you do
```nix
self: super: {
  foobar = super.stdenv.mkDerviaton { ... };
}
```
this will prevent the user from overriding `stdenv` for that derivation and it's no longer possible to, e.g. build `foobar` with a different C compiler.  Overrides are simpler and don't have this problem. They compose and you can even do things like this
```nix
((nixos-shell.override { nix = nixFlakes; }).override { nix = nixStable; }).override { nix = nixUnstable; }
```
That's exactly what this PR proposes and therefore I approve!

**Comment by lopsided98** [comment]
This significantly changes the semantics of the `boot.kernelPackages` option, causing all the attributes of the `linuxPackages` package set to be ignored except for the `kernel` attribute. If a user specifies a package set with customization other than to `kernel`, those extra customizations are just ignored now.

See https://github.com/NixOS/nixpkgs/pull/111845 for a fix for the original problem with `.extends`.

**Pull request merged**
