### PR TITLE
ghcHEAD: 20200403 -> 20200505

### PR DESCRIPTION
**Pull request by ggreif**
###### Motivation for this change

I couldn't resist when seeing the date...

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ggreif** [comment]
@GrahamcOfBorg build haskell.compiler.ghcHEAD

**Review by turion — APPROVED** [review]
Makes sense to me. When it builds, I can test quickly.

**Comment by turion** [comment]
Superficially tested ghc, runghc, ghci.

**Comment by ggreif** [comment]
Works handsomely on macOS.

**Comment by cdepillabout** [comment]
Looks good.  Thanks @ggreif for always keeping this up to date.

**Pull request merged**
