### PR TITLE
platformsh: 4.11.4 -> 4.17.0

### PR DESCRIPTION
**Pull request by spk**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Sigmanificient** [comment]
Result of `nixpkgs-review pr 299508` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>platformsh</li>
  </ul>
</details>

**Review by shyim — APPROVED** [review]

**Comment by shyim** [comment]
Looks good, do you want to add members of platformsh maybe as maintainers?

**Comment by spk** [comment]
Thanks, yes I think I could help maintaining it, should I add myself in the list in the file @shyim ?

**Comment by shyim** [comment]
yes, sure. should be in a second commit something like `platformsh: added spk as maintainer`

**Review by shyim — APPROVED** [review]

**Review by shyim — APPROVED** [review]

**Review by drupol — CHANGES_REQUESTED** [review]
Hey it's great to see people from platformsh here!

This PR should contain 3 commits, in this specific order:

1. "maintainers: add `spk`"
2. "platformsh: 4.11.4 -> 4.17.0"
3. "platformsh: add `spk` as maintainer"

**Comment by drupol** [comment]
The first commit should be: "maintainers: add `spk`", nothing else is needed (look at the git log history in `nixpkgs` for inspiration`)

**Comment by spk** [comment]
> The first commit should be: "maintainers: add `spk`", nothing else is needed (look at the git log history in `nixpkgs` for inspiration) and it shouldn't be cherry-picked either.

Sorry for that it should be ok now

**Review by drupol — APPROVED** [review]

**Review by shyim — APPROVED** [review]

**Review by shyim — APPROVED** [review]

**Pull request merged**
