### PR TITLE
libglvnd: use meson and fix static build

### LINKED ISSUE #157665: pkgsStatic.libglvnd: fails to build. libtool func__fatal_error command not found
### Describe the bug
1.  `pkgsStatic.libglvnd` fails to build
2.  Partial log:
    ```
    Making all in OpenGL
    make[3]: Entering directory '/build/source/src/OpenGL'
      CC       libopengl_main_la-libopengl.lo
      CCLD     libopengl_main.la
    x86_64-unknown-linux-musl-ar: `u' modifier ignored since `D' is the default (see `U')
      CCLD     libOpenGL.la
    ../../libtool: line 2625: func__fatal_error: command not found
    ```
    where `func__fatal_error` should be a typo of `func_fatal_error`, which will show extra information about the error before exit.
3.  Partial content of the generated `libtool` inside the build directory kept (starting from line 2631):
    ```sh
    # func_config
    # -----------
    # Display the configuration for all the tags in this script.
    func_config ()
    {
        re_begincf='^# ### BEGIN LIBTOOL'
        re_endcf='^# ### END LIBTOOL'

        # Default configuration.
        $SED "1,/$re_begincf CONFIG/d;/$re_endcf CONFIG/,\$d" < "$progpath"

        # Now print the configurations for the tags.
        for tagname in $taglist; do
          $SED -n "/$re_begincf TAG CONFIG: $tagname\$/,/$re_endcf TAG CONFIG: $tagname\$/p" < "$progpath"
        done

        exit $?
    }
    ```

### Steps To Reproduce
1.  On the NixOS/nixpkgs source tree
2.  Switch to commit 78e2ef7e3dab7778d823977129e8f8902020ffe6
3.  Run `nix-build -A pkgsStatic.libglvnd`
4.  See error
5.  Run `nix log .#pkgsStatic.libglvnd` to see the log for flake-based Nix.

### Expected behavior

1.  The typo in the auto-generated `libtool` be fixed, so that error message can appear.
2.  The build succeed.

### Screenshots

Screenshot_20220201_175441

### Additional context

The auto-generated file `libtool`:
[libtool](https://github.com/NixOS/nixpkgs/files/7977466/libtool.txt)

### Notify maintainers

@primeos

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.73, NixOS, 21.05.20211019.8fe3b97 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20211006_53e4794`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by SCOTT-HAMILTON**
###### Description of changes

Should fix https://github.com/NixOS/nixpkgs/issues/157665 but couldn't test (not enough test).

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SCOTT-HAMILTON** [comment]
I can't edit and change the base branch to staging, is it a github bug ?

**Comment by ShamrockLee** [comment]
@SCOTT-HAMILTON I guess you should create a new branch, cherry-pick those ed commits to that branch and make a PR based on it.

**Comment by SCOTT-HAMILTON** [comment]
> @SCOTT-HAMILTON I guess you should create a new branch, cherry-pick those ed commits to that branch and create a PR based on it.

This is what this PR was.

**Comment by ShamrockLee** [comment]
```sh
git rebase --onto=upstream/master libglvnd-static~1 libglvnd-static
``` 
should help then.

Just replace `upstream` with the name of the remote branch pointing to https://github.com/NixOS/nixpkgs.

**Pull request closed without merging**
