### PR TITLE
nmap: 7.91 -> 7.92

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 7.92

Change log: https://nmap.org/changelog.html#7.92

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 136279` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>crowbar</li>
    <li>gnome.gnome-nettool</li>
    <li>ncat (nmap ,nmap-unfree)</li>
    <li>nmap-graphical (nmap_graphical)</li>
    <li>nmapsi4</li>
    <li>python38Packages.netmap</li>
    <li>python38Packages.python-nmap</li>
    <li>python39Packages.netmap</li>
    <li>python39Packages.python-nmap</li>
    <li>rmount</li>
    <li>rustscan</li>
  </ul>
</details>

**Comment by fabaff** [comment]
We shipped [`nmap-unfree`](https://github.com/NixOS/nixpkgs/pull/113381) for a while. The statement that the previous license could be applied (see https://github.com/NixOS/nixpkgs/pull/118158) allowed us to move back.

**Comment by alyssais** [comment]
Yeah, but at the time it didn't apply to this release :)

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 136279` at 7bcc7aad run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built successfully:</summary>
  <ul>
    <li>crowbar</li>
    <li>gnome.gnome-nettool</li>
    <li>nmap</li>
    <li>nmap-graphical</li>
    <li>python38Packages.netmap</li>
    <li>python38Packages.python-nmap</li>
    <li>python39Packages.netmap</li>
    <li>python39Packages.python-nmap</li>
    <li>rmount</li>
    <li>rustscan</li>
  </ul>
</details>

**Review by risicle — APPROVED** [review]
`nixpkgs-review` happy, macos 10.15 & nixos x86_64

**Pull request merged**
