### PR TITLE
blas: fix library id on darwin

### PR DESCRIPTION
**Pull request by veprbl**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by matthewbauer — APPROVED** [review]
Assuming -id should be a full path, this seems fine. I can't get a clear answer on it, but it sounds like full path is safer.

**Comment by veprbl** [comment]
@matthewbauer Here is a refresher:
https://github.com/NixOS/nixpkgs/blob/2142a0a8c9bf402c263f4ec563c4f2b39c769465/pkgs/build-support/setup-hooks/fix-darwin-dylib-names.sh#L1-L11

**Comment by risicle** [comment]
Yeah this successfully builds `scipy` & `numpy` on macos 10.15 for me.

**Comment by smancill** [comment]
@veprbl you missed `libcblas`:

https://github.com/NixOS/nixpkgs/blob/6666bdf0fbedcfe195fce304b04695006c43a9ee/pkgs/build-support/alternatives/blas/default.nix#L118

**Comment by veprbl** [comment]
@smancill Good catch! Thanks

**Pull request merged**
