### PR TITLE
oasis: 0.4.6 -> 0.4.7

### PR DESCRIPTION
**Pull request by maurer**
###### Motivation for this change

Update oasis to allow new-style `setup.ml`
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Kept a copy of oasis_46 around for the moment to service qtest. The opam repository shows this too https://github.com/ocaml/opam-repository/issues/7305 and is keeping 4.6 around for it and similar packages for the moment.

### CODE REVIEW

**Comment by maurer** [comment]
If this lands before #18572 , that PR will need to be updated to use only oasis_46 as well. If this hasn't landed when that does, I'll push another commit to this to deal with it.

**Comment by regnat** [comment]
I think both definitions could be factored.
Otherwise, :+1:

**Comment by vbgl** [comment]
Do we need to keep the version 46? Notice that I have just updated `qtest` in 38c143abe2363aa8770a4879b348f7aeaf3fbca1.

**Comment by maurer** [comment]
@vbgl It's no longer needed for qtest, but I'm still looking whether it can be avoided for #18572

**Comment by maurer** [comment]
https://github.com/janestreet/js-build-tools/blob/master/opam#L19

As of master, js-build-tools (which is now used to build all jane street core libraries) conflicts with 0.4.7. As a result, I suggest we keep 0.4.6 around for the moment.

**Comment by joachifm** [comment]
@maurer is this ready to go, with the janestreet stuff having been merged?

**Comment by maurer** [comment]
@joachifm Just added the compatibility patch to the Janestreet stuff, I expect it should be good to go now.

**Comment by maurer** [comment]
@joachifm I just added the Jane Street compatibility stuff. It should be good now.

**Pull request merged**
