### PR TITLE
joplin-desktop: 2.3.5 -> 2.4.6

### PR DESCRIPTION
**Pull request by seandheath**
###### Motivation for this change
The current version in nixpkgs is too old to sync to the current version of the Joplin desktop client. This brings the client up to the current version (as of 20210915)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg build joplin-desktop

Will be nice to follow [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md) when writing commit messages.

**Comment by seandheath** [comment]
> Will be nice to follow [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md) when writing commit messages.

Updated commit message to be consistent with CONTRIBUTIZNG.md (I think?). Please let me know if I missed anything.

**Comment by bobby285271** [comment]
Result of `nixpkgs-review pr 138041` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>joplin-desktop</li>
  </ul>
</details>

**Review by bobby285271 — APPROVED** [review]
Launches, squash merge.

(The commit message still does not follow the contributing guide, I will change that when doing squash merge).

**Comment by ethancedwards8** [comment]
Also, its better practice to make a separate branch for contributions. ie: joplin-desktop-2.4.6

**Pull request merged**
