### PR TITLE
inav-configurator: 5.1.0 -> 7.1.0

### PR DESCRIPTION
**Pull request by teknolog1k**
## Description of changes
[Changelog](https://github.com/iNavFlight/inav-configurator/releases/tag/7.1.0)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by momeemt — APPROVED** [review]
LGTM, but could you please rebase [462daa3](https://github.com/NixOS/nixpkgs/pull/310412/commits/462daa3f6b802be98b743c0bed4371ee71e7e632) onto [1fe20b1](https://github.com/NixOS/nixpkgs/pull/310412/commits/1fe20b1966cfc1c8d06b55f5a1dd0f42e02964dd)?

**Comment by marcusramberg** [comment]
Looks like [7.1.1](https://github.com/iNavFlight/inav-configurator/releases/tag/7.1.1) was just released.

**Comment by MikaelFangel** [comment]
Fixes: #310330

**Comment by Rose-David** [comment]
Should I update this PR to 7.1.1, or should I let this one get merged first and make another PR for 7.1.1? I've never done this before, so idk.

**Comment by MikaelFangel** [comment]
You should update PR to the new version. When you do it remember to change the PR title and that there is only one commit adding the package (squash the new commit you make when you change the version and hash) preferably using `git --force-with-lease`.

**Comment by Rose-David** [comment]
Just realized that this is kind of a duplicate of #310815, which is more complete and seems to solve a problem I was having when trying to get this working, so I'm going to close this PR.

**Pull request closed without merging**
