### PR TITLE
ripple-data-api: use new importer from ripple historical database, that actually works

### PR DESCRIPTION
**Pull request by offlinehacker**

### CODE REVIEW

**Comment by jagajaga** [comment]
Any reasons to be not merged?

**Comment by zimbatm** [comment]
ping

**Comment by wmertens** [comment]
(triage) @offlinehacker travis originally failed because something was referencing a missing ripple-data.nix but restarting the build just started tarball creation which is not impacted.

The PR LGTM, :+1:, merge when you like.

**Comment by Mic92** [comment]
needs rebase

**Pull request closed without merging**
