### PR TITLE
libvirt: 4.5.0 -> 4.7.0

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

version bump

### CODE REVIEW

**Comment by Izorkin** [comment]
Thanks. libvirt-4.7.0 works for me.

**Comment by volth** [comment]
I have deployed ```4.7.0``` to production a few days ago.
No problems so far, but there are only LXC slaves, so I had no problems with 4.6.0 too :)

**Comment by xeji** [comment]
let's check darwin build
@GrahamcOfBorg build libvirt

**Comment by xeji** [comment]
ran nix-review successfully

**Pull request merged**
