### PR TITLE
blocksat-cli: init at 0.3.2

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

- new package for communication with the [Blockstream Satellite](https://blockstream.com/satellite/)
- enable pyutil and zfec packages for Python 3

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
@GrahamcOfBorg build python3Packages.pyutil python3Packages.zfec python3Packages.blocksat-cli blocksat-cli

**Comment by prusnak** [comment]
@GrahamcOfBorg build python3Packages.pyutil python3Packages.zfec python3Packages.blocksat-cli blocksat-cli

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 130454` at e76b936d run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built successfully:</summary>
  <ul>
    <li>blocksat-cli (python38Packages.blocksat-cli)</li>
    <li>python38Packages.pyutil</li>
    <li>python38Packages.zfec</li>
    <li>python39Packages.blocksat-cli</li>
    <li>python39Packages.pyutil</li>
    <li>python39Packages.zfec</li>
  </ul>
</details>
<details>
  <summary>3 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/pyutil/default.nix:27:3:
```
   |
27 |   meta = with lib; {
   |   ^
```
</li>
    <li>warning: unused-argument

Unused argument: `tox`.
Near pkgs/development/python-modules/blocksat-cli/default.nix:11:3:
```
   |
11 | , tox
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/zfec/default.nix:27:3:
```
   |
27 |   meta = with lib; {
   |   ^
```
</li>
  </ul>
</details>

**Comment by jb55** [comment]
nice, lgtm

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 130454` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>blocksat-cli (python38Packages.blocksat-cli)</li>
    <li>python38Packages.pyutil</li>
    <li>python38Packages.zfec</li>
    <li>python39Packages.blocksat-cli</li>
    <li>python39Packages.pyutil</li>
    <li>python39Packages.zfec</li>
  </ul>
</details>

**Pull request merged**
