### PR TITLE
julius: 1.4.1 -> 1.5.1

### PR DESCRIPTION
**Pull request by Thra11**
###### Motivation for this change
Package version update

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102263` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>julius</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102263` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>julius</li>
  </ul>
</details>

**Comment by Thra11** [comment]
Hmmm. Checking hydra, it looks like it's never built on darwin, so not a new issue, but according to upstream, macOs is supported, so we might as well fix it while we're here. The hydra failure on 1.4.1 is:
```
[  0%] Generating ../res/julius.icns
/nix/store/8i9kyqfxhk2s9dzx32x0sgdk7kyx9wjc-bash-4.4-p23/bin/bash: sips: command not found
make[2]: *** [CMakeFiles/julius.dir/build.make:82: ../res/julius.icns] Error 127
make[1]: *** [CMakeFiles/Makefile2:116: CMakeFiles/julius.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
builder for '/nix/store/7wcyk8awnj2wrc5yvpn6q2zcppyaxlim-julius-1.4.1.drv' failed with exit code 2
```
@SuperSandro2000, do you have the full logs for the failed darwin build? Is it the same issue as before, `sips: command not found`? I assume we need to add whatever packages `sips` is part of to the `nativeBuildInputs` when building on darwin.

**Comment by SuperSandro2000** [comment]
Scrolled up and the lines before compiling are

```
/nix/store/8i9kyqfxhk2s9dzx32x0sgdk7kyx9wjc-bash-4.4-p23/bin/bash: sips: command not found                                                                                                  make[2]: *** [CMakeFiles/julius.dir/build.make:82: ../res/julius.icns] Error 127
```

**Comment by Thra11** [comment]
Thanks! Looks like sips is still the issue then.

I did find this in another package:
https://github.com/NixOS/nixpkgs/blob/58d1f49993ee726537b18a6b96bfe1bdbae70191/pkgs/misc/emulators/higan/default.nix#L34-L40

**Comment by SuperSandro2000** [comment]
Can you mark the package broken on darwin?

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102263` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>julius</li>
  </ul>
</details>

**Pull request merged**
