### PR TITLE
openai-whisper: init at unstable-2022-09-21

### LINKED ISSUE #192386: Whisper by OpenAI (automatic speech recognition)
**Project description**
Whisper is a general-purpose speech recognition model. It is trained on a large dataset of diverse audio and is also a multi-task model that can perform multilingual speech recognition as well as speech translation and language identification.

**Metadata**

* homepage URL: https://openai.com/blog/whisper/
* source URL: https://github.com/openai/whisper
* license: mit
* platforms: all

### PR DESCRIPTION
**Pull request by mweinelt**
###### Description of changes

New-fangled speech recognition model. Naming collision with the biology tool whisper. I'm not yet sure whether I want to maintain this. Up until now it is just a code dump.

Fixes #192386 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
```
❯ ./whisper /tmp/This\ is\ an\ example\ of\ Speex\ \[EJlhYIPRE2o\].webm
100%|███████████████████████████████████████| 139M/139M [00:13<00:00, 11.1MiB/s]
/nix/store/l2vb6bg4gvkqvg02k5h8ca9iwj0fnys5-whisper-unstable-2022-09-21/lib/python3.10/site-packages/whisper/transcribe.py:70: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
Detecting language using up to the first 30 seconds. Use `--language` to specify the language
Detected language: english
[00:00.000 --> 00:06.640]  This is an example of spheaks, an audio compression code x specifically tuned for the reproduction of human speech.
[00:06.640 --> 00:13.360]  This is an example of spheaks, an audio compression code x specifically tuned for the reproduction of human speech.
[00:13.360 --> 00:19.980]  This is an example of spheaks, an audio compression code x specifically tuned for the reproduction of human speech.
[00:19.980 --> 00:27.000]  This is an example of spheaks, an audio compression code x specifically tuned for the reproduction of human speech.
[00:27.000 --> 00:32.060]  This is an example of Speaks, an audio compression codex specifically tuned for the reproduction
[00:32.060 --> 00:33.680]  of human speech.
[00:33.680 --> 00:38.740]  This is an example of Speaks, an audio compression codex specifically tuned for the reproduction
[00:38.740 --> 00:40.300]  of human speech.
[00:40.300 --> 00:45.380]  This is an example of Speaks, an audio compression codex specifically tuned for the reproduction
[00:45.380 --> 00:46.960]  of human speech.
[00:46.960 --> 00:52.060]  This is an example of Speaks, an audio compression codex specifically tuned for the reproduction
[00:52.060 --> 00:53.620]  of human speech.

**Comment by andreasfelix** [comment]
just as a note, whisper can also be used as a Python library

**Comment by mweinelt** [comment]
Okay, thanks. Moving it over into python-modules. That makes total sense.

**Review by dit7ya — COMMENTED** [review]
I am getting this error when running the `openai-whisper` package (the bin in the other result works fine).


```fish
𝝺 ./results/openai-whisper/bin/whisper
Traceback (most recent call last):
  File "/nix/store/c1fkpcpz17mccwk9q586a6y2smlwzsbd-python3.10-whisper-unstable-2022-09-21/bin/.whisper-wrapped", line 6, in <module>
    from whisper.transcribe import cli
  File "/nix/store/lv9cxmbxjmma4advdl6h4ihjppvfymg5-python3.9-whisper-unstable-2022-09-21/lib/python3.9/site-packages/whisper/__init__.py", line 8, in <module>
    import torch
  File "/nix/store/ykam416nsgkwymyrmxy366gr5drlkmyf-python3.9-torch-1.12.1/lib/python3.9/site-packages/torch/__init__.py", line 219, in <module>
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.
```

**Comment by dit7ya** [comment]
Result of `nixpkgs-review pr 192391` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>openai-whisper (python310Packages.openai-whisper)</li>
    <li>python39Packages.openai-whisper</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
Works for me.

```
❯ ./result/bin/whisper
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
Moving 0 files to the new cache system
0it [00:00, ?it/s]
usage: whisper [-h]
               [--model {tiny.en,tiny,base.en,base,small.en,small,medium.en,medium,large}]
               [--device DEVICE] [--output_dir OUTPUT_DIR] [--verbose VERBOSE]
               [--task {transcribe,translate}]
               [--language {af,am,ar,as,az,ba,be,bg,bn,bo,br,bs,ca,cs,cy,da,de,el,en,es,et,eu,fa,fi,fo,fr,gl,gu,ha,haw,hi,hr,ht,hu,hy,id,is,it,iw,ja,jw,ka,kk,km,kn,ko,la,lb,ln,lo,lt,lv,mg,mi,mk,ml,mn,mr,ms,mt,my,ne,nl,nn,no,oc,pa,pl,ps,pt,ro,ru,sa,sd,si,sk,sl,sn,so,sq,sr,su,sv,sw,ta,te,tg,th,tk,tl,tr,tt,uk,ur,uz,vi,yi,yo,zh,afrikaans,albanian,amharic,arabic,armenian,assamese,azerbaijani,bashkir,basque,belarusian,bengali,bosnian,breton,bulgarian,burmese,castilian,catalan,chinese,croatian,czech,danish,dutch,english,estonian,faroese,finnish,flemish,french,galician,georgian,german,greek,gujarati,haitian,haitian creole,hausa,hawaiian,hebrew,hindi,hungarian,icelandic,indonesian,italian,japanese,javanese,kannada,kazakh,khmer,korean,lao,latin,latvian,letzeburgesch,lingala,lithuanian,luxembourgish,macedonian,malagasy,malay,malayalam,maltese,maori,marathi,moldavian,moldovan,mongolian,myanmar,nepali,norwegian,nynorsk,occitan,panjabi,pashto,persian,polish,portuguese,punjabi,pushto,romanian,russian,sanskrit,serbian,shona,sindhi,sinhala,sinhalese,slovak,slovenian,somali,spanish,sundanese,swahili,swedish,tagalog,tajik,tamil,tatar,telugu,thai,tibetan,turkish,turkmen,ukrainian,urdu,uzbek,valencian,vietnamese,welsh,yiddish,yoruba}]
               [--temperature TEMPERATURE] [--best_of BEST_OF] [--beam_size BEAM_SIZE]
               [--patience PATIENCE] [--length_penalty LENGTH_PENALTY]
               [--suppress_tokens SUPPRESS_TOKENS] [--fp16 FP16]
               [--temperature_increment_on_fallback TEMPERATURE_INCREMENT_ON_FALLBACK]
               [--compression_ratio_threshold COMPRESSION_RATIO_THRESHOLD]
               [--logprob_threshold LOGPROB_THRESHOLD]
               [--no_caption_threshold NO_CAPTION_THRESHOLD]
               audio [audio ...]
whisper: error: the following arguments are required: audio

**Comment by khanghugo** [comment]
Works great for me.

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 192391` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>openai-whisper (python310Packages.openai-whisper)</li>
    <li>python39Packages.openai-whisper</li>
  </ul>
</details>

**Comment by davidak** [comment]
I get the same error as @dit7ya in nixpkgs-review:

```
[nix-shell:~/.cache/nixpkgs-review/pr-192391]$ ./results/openai-whisper/bin/whisper 
Traceback (most recent call last):
  File "/nix/store/c1fkpcpz17mccwk9q586a6y2smlwzsbd-python3.10-whisper-unstable-2022-09-21/bin/.whisper-wrapped", line 6, in <module>
    from whisper.transcribe import cli
  File "/nix/store/lv9cxmbxjmma4advdl6h4ihjppvfymg5-python3.9-whisper-unstable-2022-09-21/lib/python3.9/site-packages/whisper/__init__.py", line 8, in <module>
    import torch
  File "/nix/store/ykam416nsgkwymyrmxy366gr5drlkmyf-python3.9-torch-1.12.1/lib/python3.9/site-packages/torch/__init__.py", line 219, in <module>
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.
```

Outside of that shell it works:

```
[davidak@gaming:~]$ ~/.cache/nixpkgs-review/pr-192391/results/openai-whisper/bin/whisper 
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
Moving 0 files to the new cache system
0it [00:00, ?it/s]
usage: whisper [-h] [--model {tiny.en,tiny,base.en,base,small.en,small,medium.en,medium,large}] [--device DEVICE] [--output_dir OUTPUT_DIR] [--verbose VERBOSE]
               [--task {transcribe,translate}]
               [--language {af,am,ar,as,az,ba,be,bg,bn,bo,br,bs,ca,cs,cy,da,de,el,en,es,et,eu,fa,fi,fo,fr,gl,gu,ha,haw,hi,hr,ht,hu,hy,id,is,it,iw,ja,jw,ka,kk,km,kn,ko,la,lb,ln,lo,lt,lv,mg,mi,mk,ml,mn,mr,ms,mt,my,ne,nl,nn,no,oc,pa,pl,ps,pt,ro,ru,sa,sd,si,sk,sl,sn,so,sq,sr,su,sv,sw,ta,te,tg,th,tk,tl,tr,tt,uk,ur,uz,vi,yi,yo,zh,afrikaans,albanian,amharic,arabic,armenian,assamese,azerbaijani,bashkir,basque,belarusian,bengali,bosnian,breton,bulgarian,burmese,castilian,catalan,chinese,croatian,czech,danish,dutch,english,estonian,faroese,finnish,flemish,french,galician,georgian,german,greek,gujarati,haitian,haitian creole,hausa,hawaiian,hebrew,hindi,hungarian,icelandic,indonesian,italian,japanese,javanese,kannada,kazakh,khmer,korean,lao,latin,latvian,letzeburgesch,lingala,lithuanian,luxembourgish,macedonian,malagasy,malay,malayalam,maltese,maori,marathi,moldavian,moldovan,mongolian,myanmar,nepali,norwegian,nynorsk,occitan,panjabi,pashto,persian,polish,portuguese,punjabi,pushto,romanian,russian,sanskrit,serbian,shona,sindhi,sinhala,sinhalese,slovak,slovenian,somali,spanish,sundanese,swahili,swedish,tagalog,tajik,tamil,tatar,telugu,thai,tibetan,turkish,turkmen,ukrainian,urdu,uzbek,valencian,vietnamese,welsh,yiddish,yoruba}]
               [--temperature TEMPERATURE] [--best_of BEST_OF] [--beam_size BEAM_SIZE] [--patience PATIENCE] [--length_penalty LENGTH_PENALTY]
               [--suppress_tokens SUPPRESS_TOKENS] [--fp16 FP16] [--temperature_increment_on_fallback TEMPERATURE_INCREMENT_ON_FALLBACK]
               [--compression_ratio_threshold COMPRESSION_RATIO_THRESHOLD] [--logprob_threshold LOGPROB_THRESHOLD] [--no_caption_threshold NO_CAPTION_THRESHOLD]
               audio [audio ...]
whisper: error: the following arguments are required: audio
```

auto-detecting and recognizing german works great, even with bad spoken sentences and bad audio quality. looks great so far

**Review by davidak — APPROVED** [review]
Change looks good

Binary works. Not tested Library.

**Pull request merged**
