### PR TITLE
skim: fix vim-plugin output

### PR DESCRIPTION
**Pull request by tsaeger**
###### Motivation for this change

skim has both a utility and vim-plugin (skim.vim)
The vim-plugin is split where part of it is installed by skim, the rest is installed by skim.vim.
This is very similar to fzf and fzf.vim.  In fact, skim.vim is a fork of fzf.vim.

Add vimPlugin.skim-vim which depends on vimPlugin.skim.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tsaeger** [comment]
@dywedir  review?

**Comment by jonringer** [comment]
@GrahamcOfBorg eval

**Comment by tsaeger** [comment]
Thinking I might re-rework this.  Keep the "vim" outputs path in "skim".
Keep vimPlugins.skim and just merely add vimPlugins.skim-vim.

**Review by jonringer — COMMENTED** [review]
there should also be an entry in vim-plugin-names

**Comment by jonringer** [comment]
please follow https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/vim.section.md#adding-new-plugins-to-nixpkgs

**Comment by tsaeger** [comment]
@jonringer thanks for the link!  I've fixed the pr to include entry in vim-plugin-names.

**Comment by 8573** [comment]
What more needs to be done for this to be merged?

**Pull request merged**
