### PR TITLE
pythonPackages.cheroot: fixed tests

### LINKED ISSUE #42715: pythonPackages.cheroot is broken due to missing dependencies in unstable
## Issue description
cheroot 6.3.2 depends on backports_functools_lru_cache and pytest-testmon to run its tests.

### Steps to reproduce
Try to build cheroot 6.3.2 from nixpkgs-unstable (updated in https://github.com/NixOS/nixpkgs/commit/095a58c09b1cda941358e5fd4c62682a8c0376bf)

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

- system: `"x86_64-linux"`
 - host os: `Linux 4.14.51, NixOS, 18.03.132768.94d80eb7247 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `""`
 - nixpkgs: `/nix/store/gsqxmqmpbq40d62z0fnbyih00lgzx0ac-nixexprs.tar.xz`

### PR DESCRIPTION
**Pull request by xvapx**
###### Motivation for this change
Fix #42715

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dotlambda** [comment]
@GrahamcOfBorg build python2.pkgs.cheroot python3.pkgs.cheroot

**Comment by dotlambda** [comment]
It seems like `setuptools_scm_git_archive` should be added to `nativeBuildInputs`.

**Comment by xvapx** [comment]
Yep, I'm having the same problem, but it was there before this patch.
I was trying to build and test cheroot before trying to add setuptools_scm_git_archive, which is not packaged in nixpkgs.

**Comment by FRidh** [comment]
We can also just patch away `setuptools_scm*` entirely and insert the version ourselves:
```
substituteInPlace setup.py ---replace "use_scm_version=True" "version=${version}" \
  --replace "'setuptools_scm>=1.15.0'," "" \
  --replace "'setuptools_scm_git_archive>=1.0'," ""
```

**Comment by xvapx** [comment]
@FRidh It works, but cherrypy is missing ```backports_functools_lru_cache``` as a checkInput. 
Adding backports_functools_lru_cache to cherrypy works, but it's still failing two tests, I'm looking at it.
Should the changes to cherrypy be in a different PR?

**Comment by FRidh** [comment]
Same PR, but different commits.

**Comment by xvapx** [comment]
Thanks, done.

**Pull request merged**
