### PR TITLE
pythonPackages.amqplib: pypi->github

### PR DESCRIPTION
**Pull request by volth**
Fixes https://github.com/NixOS/nixpkgs/issues/27732

### CODE REVIEW

**Comment by FRidh** [comment]
Thanks. The package seems to be extremely outdated so I think instead we should just update it. The reason `fetchPypi` fails here is that until not too long ago it was possible to upload files with all kinds of extensions. The sdist of this version e.g. has `.tgz` instead of `.tar.gz`.

**Comment by volth** [comment]
even the latest release (1.0.2) is outdated (2011)

**Comment by FRidh** [comment]
Consider the package is neither used nor maintained I suggest to just drop it.

**Comment by volth** [comment]
```virtmanager``` depends on it.

**Pull request merged**
