### PR TITLE
etc: remove obsolete directories

### LINKED ISSUE #16978: Font looks different + really bad kerning
## Issue description
Somewhere between b5a95b1 and 6af0f57f91f5b87e10186f7d26a345cab565478c there is a commit that changes the default fonts on NixOS. Most text is just _different_ (I'd say, a bit less readable). But some text in the terminal (gnome-terminal) is completely borked (in regards to positioning):

selection_002

Look at how the 's' is drawn on top of the 'M'. And generally the positioning of glyphs is... not right!

### Steps to reproduce
Compare how fonts look in a few apps on nixpkgs b5a95b1 vs 6af0f57f91f5b87e10186f7d26a345cab565478c.

## Technical details

* System: x86_64-linux NixOS at master branch (6af0f57f91f5b87e10186f7d26a345cab565478c). No fonts.* settings in my configuration.nix file (never had that). GNOME3 desktop and gnome-terminal.

### PR DESCRIPTION
**Pull request by rasendubi**
###### Things done
- [x] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This patch adds handling of a directory becoming a symlink in
/etc. Before this patch, the directory wasn't removed and then
symlinking failed, which caused directory not being updated at all.

The idea for the patch goes to @abbradar at
https://github.com/NixOS/nixpkgs/issues/16978#issuecomment-232921903:

> A heuristic idea for this -- a function `isStatic :: Path -> Bool`:
> - if path `/etc/foo` is a file, return True iff it's a symlink to `/etc/static/foo`.
> - if path is a directory, return True iff for all items in it `isStatic` is True.
> 
> On any conflicts, if old path is static, it's safe to replace and/or
> delete stale. Otherwise make a backup and notify the user via a
> journal entry and console output.

The only difference here -- it will not replace user configs.

This also fixes https://github.com/NixOS/nixpkgs/issues/16978.

### CODE REVIEW

**Comment by abbradar** [comment]
Great! cc @edolstra for review.

**Comment by wmertens** [comment]
:+1:

**Comment by rasendubi** [comment]
ping

**Comment by wmertens** [comment]
@edolstra since this is quite close to NixOS core, any objections? If I don't hear anything by Tuesday I will merge.

**Comment by edolstra** [comment]
I get very afraid when I see calls to `rmtree`. Somebody should carefully review this for correctness.

**Comment by rasendubi** [comment]
I've tried to be extra-careful about that, and `rmtree` is only called on the directories if all children are either empty directories or symlinks to the `/etc/static`. Anyway, a review is welcome.

**Comment by wmertens** [comment]
The only way the `rmtree` can run is when `isStatic` returns truthy. `isStatic` checks recursively that the path given is either a symlink to somewhere starting with`/etc/static`, or a directory containing only `.`, `..` and 0 or more static symlinks.

So @rasendubi, the code can return truthy for a symlink pointing to e.g. `/etc/staticKeys`, as well as for empty directories. The former is probably rare, but still, and the latter is ok I guess?

**Comment by wmertens** [comment]
@rasendubi so I mean that I would like it if you verify symlinks for `/etc/static/`

**Comment by rasendubi** [comment]
Oh, seems that I've missed that case. Thanks for pointing it out! I'll fix it later today.

**Comment by rasendubi** [comment]
Done + tested on my system.

**Comment by wmertens** [comment]
@edolstra ok? I'll merge tomorrow.

**Comment by wmertens** [comment]
Thanks @rasendubi!

**Pull request merged**
