### PR TITLE
terraform-providers: update and improve update script

### PR DESCRIPTION
**Pull request by mbrgm**
###### Motivation for this change

Adding terraform-provider-pass and making it work with the `update-all` script required some changes to the way the update mechanism works. In the course of this I also updated all registered providers. See individual commit messages for a detailed description of reasons and measures taken.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by mbrgm** [comment]
cc @zimbatm @stephengroat

**Comment by stephengroat** [comment]
any reason not to seperate the `pass` provider out into a different directory, similar to `ansible`, etc.? i like the idea, but adding in `rev` seems to add a lot of duplication (over 100 lines) to cover a single case that's out of the norm for `terraform-providers` hosted repos, which are standard

**Comment by kalbasit** [comment]
@GrahamcOfBorg build terraform_0_12.full terraform_0_11.full

**Comment by kalbasit** [comment]
@mbrgm the commits are not following the [contributing guidelines](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md). Can you please rebase? Thanks!

**Comment by mbrgm** [comment]
@kalbasit I'm sorry I forgot about the commit messages. Rebased.

**Comment by mbrgm** [comment]
> any reason not to seperate the pass provider out into a different directory, similar to ansible, etc.? i like the idea, but adding in rev seems to add a lot of duplication (over 100 lines) to cover a single case that's out of the norm for terraform-providers hosted repos, which are standard

@stephengroat I'm sorry for not addressing this before... The method of "remove some character here, add a 'v' there" appeared a bit brittle to me in the first place. I agree with you in that terraform-providers quite nicely stick to the conventions and adding `rev` adds duplicate code (which is generated though, so...). On the other hand, by making `update-all` work with those cases as well, we can keep them inside the set of packages, which can be auto-upgraded. Extracting the pass provider to a separate directory would mean there's one additional package to upgrade manually.

I can see pros and cons in both approaches... so maybe additional opinions might help?

**Comment by zimbatm** [comment]
I think it's okay. Perfect is the enemy of good and all that. As long as it's maintainable.

**Pull request merged**
