### PR TITLE
self-deploy: Prevent infinite reboot loop

### PR DESCRIPTION
**Pull request by Gabriella439**
###### Description of changes

This fixes the `self-deploy` service to not `reboot` if the
current system matches the target system.  This is necessary
because the `self-deploy` service will run again on system startup
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by evanrelf — APPROVED** [review]

**Comment by roberth** [comment]
Could you add a test?

You can borrow some tricks from the nixops test, like importing `cd-dvd/channel.nix` to supply nixpkgs sources and `allDrvOutputs` to make sure all dependencies are available in the sandbox.
For git it seems that a local repository should work.

**Comment by RaitoBezarius** [comment]
Is there something I can do to help this PR getting merged?

**Comment by Gabriella439** [comment]
I mainly need help with the test requested by @roberth.  I tried to write a test but the test just hangs

Personally, I think this change is safe to merge without the test.  We already used it extensively at my prior job

**Comment by RaitoBezarius** [comment]
> I mainly need help with the test requested by @roberth. I tried to write a test but the test just hangs
> 
> Personally, I think this change is safe to merge without the test. We already used it extensively at my prior job

If you want, I can try PRing a test to your branch?

**Comment by ncfavier** [comment]
If this fixes an issue then it's fine to merge now and add a test later.

**Comment by ncfavier** [comment]
I can't reproduce the manual build failure, probably just needs rebasing.

**Comment by RaitoBezarius** [comment]
> I can't reproduce the manual build failure, probably just needs rebasing and squashing.

It's probably my fault yesterday with `nixos/redmine: Rework module` merge.

**Comment by ncfavier** [comment]
Nah, it failed 6 months ago (and the [logs](https://github.com/NixOS/nixpkgs/actions/runs/2373376621/jobs/3574995770) have expired since).

**Comment by Gabriella439** [comment]
I might need to open a new PR.  I don't have access to the original repository/branch (since I switched jobs since I created this PR)

**Comment by Gabriella439** [comment]
I reopened this as https://github.com/NixOS/nixpkgs/pull/206096

**Pull request closed without merging**
