### PR TITLE
convert-to-import-cargo-lock: convert to callPackage style and wrap program

### PR DESCRIPTION
**Pull request by philiptaron**
## Motivation for change

Remove two top-level with statements. Make the program include its run-time dependencies by default.
- #208242 

## Description of changes

- [x] Used `callPackage` style
- [x] Wrapped program so it's always able to find `nix` (and associated tools) and `nix-prefetch-git`
- [x] Updated wrapper script

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by winterqt** [comment]
I don't see the point of this, honestly. Is there a benefit to exposing this to any downstream Nixpkgs consumer? It's hacky and not really meant for downstream usage...

**Comment by philiptaron** [comment]
> I don't see the point of this, honestly. Is there a benefit to exposing this to any downstream Nixpkgs consumer? It's hacky and not really meant for downstream usage...

Updated to leave where it is but update to callPackage style and wrap the program.

**Comment by philiptaron** [comment]
@winterqt: gentle ping ... if you request changes because you don't care at all, I'll close this, but I do think it provides a small amount of value by virtue of always being able to find `nix` and `nix-prefetch-git`.

**Comment by winterqt** [comment]
> if you request changes because you don't care at all

I may be reading this wrong, but this comes off a bit rude. (It doesn't sound like you meant it, though.)

There are some objectively good changes here, for sure, but I'm just not sure if it really matters too much given that this is just some throwaway script like everything else in `maintainers/scripts`.

I'll play around with this some time this weekend and see what I think, thank you for seeing this through nonetheless. 🙂

**Comment by philiptaron** [comment]
@winterqt: absolutely no rudeness intended, I just have a damned quality of trying to get small things either through or not through, not stuck in limbo. 🙇🏻‍♂️

**Pull request closed without merging**
