### PR TITLE
[Backport release-23.11] appflowy: 0.3.8. -> 0.5.4

### LINKED ISSUE #303892: Update request: Appflowy 0.3.8 → 0.5.4
- Package name: Appflowy
- Latest released version: 0.5.4

- Current version on the unstable channel: 0.5.4
- Current version on the stable/release channel: 0.3.8

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers** 
@DarkOnion0 

-----

Note for maintainers: Is it possible to update the app version for stable release also? I am sorry if this is not a valid request.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by DarkOnion0**
## Description of changes

Backport the latest change made to appflowy in #302779.

Fix #303892

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by risicle** [comment]
Firstly when we need to backport multiple bumps, the normal thing to do is cherry-pick each intervening bump commit separately.

Secondly, if you backport any old bump to the stable branch, there's no point in having a stable branch.

**Comment by DarkOnion0** [comment]
1. Thanks for the tip, also when I reconsider the whole logic behind cherry-picking change, it's obvious. I'm just not used to backporting changes, even less manually and thus, I just applied my normal commit/rebase/push workflow I'm using when updating packages. I apologize.
2. I'm glade that stable branch exists and feel so every day when my system just updates and boots up straight! Although I'm also grateful to every maintainer that backport updates to stable branch. In other words, If I fully agree with you and think that a stable branch should stay stable, I've checked every condition mentioned in the [doc](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#changes-acceptable-for-releases) and the software I'm backporting didn't have a major update nor breaking changes (I've checked all appflowy release notes before backporting). Therefore, I thought it should be okay, aren't it?

**Comment by risicle** [comment]
There are a lot of problems with the contributing doc around this subject - it would be possible to argue almost any change meets the criteria. The problem is that upstream authors are very bad at knowing what is a "breaking change" and frankly even feature additions have the possibility of introducing new bugs. Ultimately it's probably up to you with this being a "leaf" package though.

**Comment by mobsenpai** [comment]
> 1. Thanks for the tip, also when I reconsider the whole logic behind cherry-picking changes, it's obvious. I'm just not used to backporting changes, even less manually and thus, I just applied my normal commit/rebase/push workflow I'm using when updating packages. I apologize.
> 
>     2. I'm glade that stable branch exists and feel so every day when my system just updates and boots up straight! Although I'm also grateful to every maintainer that backport updates to stable branch. In other words, If I fully agree with you and think that a stable branch should stay stable, I've checked every condition mentioned in the [doc](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#changes-acceptable-for-releases) and the software I'm backporting didn't have a major update nor breaking changes (I've checked all appflowy release notes before backporting). Therefore, I thought it should be okay, aren't it?

Thats correct and also we are not using any unstable branch of the given package here. Like for example awesomewm has a git branch but it shouldn't be in stable branch of any package and the users have to do it some other way around. Also to agree with @DarkOnion0, this is a very old version of appflowy which doesn't even have basic features like (sync, relation) making it unusable at this version. I agree stable branch needs to be stable but important updates and more up-to-date packages are also important. We should take time and update after it is proven to be stable.

**Review by JohnRTitor — APPROVED** [review]
LGTM.

**Comment by AkechiShiro** [comment]
@risicle if there are issue with the contributing doc, there should be improvements made so that they are enhanced, I hope your concern can be voiced upstream, maybe to the documentation team or someone that could take into account your feedback.

I don't think upstream doesn't care about "breaking changes".

**Comment by risicle** [comment]
I think it's quite broadly acknowledged that the wording of that section is extremely vague, but I don't think anyone both:
 - has a better definition 
 - has the energy to open that whole can of worms

**Comment by mobsenpai** [comment]
if there isn't any issue, I suppose it should get merged?

**Comment by JohnRTitor** [comment]
Yeah, I suppose, but I don't have the commiter bit, we'll need one to merge this. Perhaps @wegank or @risicle can take a look.

**Comment by JohnRTitor** [comment]
Result of `nixpkgs-review pr 303905` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>appflowy</li>
  </ul>
</details>

**Comment by wegank** [comment]
I have no idea if there are any breaking changes, so I'll let @risicle decide.

**Comment by AkechiShiro** [comment]
I don't understand how there could be breaking change for any other package than `appflowy` because no package depends on `appflowy` I think and I believe `appflowy` did not change any of their database formats between those versions.

**Comment by risicle** [comment]
Firstly, I'm not in charge here, so it's not really my call to make, and I'm not going to stop this. However, keep in mind that it's not as though you'd be _denying_ people the use of the newer version by not bumping - users can easily mix & match packages from stable & unstable.

Remember, when you make a significant version bump in stable, it's effectively a "surprise" software update for users, who shouldn't have to expect significant bumps when following the stable branch, and as such won't have a chance to e.g. take backups beforehand in case an upgrade goes bad. To what extent can you guarantee that this upgrade won't cause any users data loss?

**Review by JohnRTitor — CHANGES_REQUESTED** [review]
See above.

**Comment by mobsenpai** [comment]
@DarkOnion0 Yeah. Its okay. I am actually using it with the unstable branch with nix profile for now, and as you said the next release is near, and there are a lot of new stuff I am waiting for so, let's wait some time more. Anyways tq for creating this PR, the next second, I reported that the stable was behind, although it didn't get merged but can't look past the hardwork it takes to actually do stuff, while I am just here 'commenting' the stuff I want. 
I am very excited for the new release!!

**Comment by AkechiShiro** [comment]
@risicle you are correct, stable should never upgrade unless a major release has landed and the user explicitly switches his channels to that new release.

**Pull request closed without merging**
