### PR TITLE
amd-blis: init at 2.2

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

Add BLIS optimized for AMD Zen CPUs.

We compile specifically for Zen:

- Zen/Zen2 are not included in the x86_64 or amd64 configurations.
- Including them breaks AMD BLIS in other places, since some functions
  have Zen-specific definitions that fail on other platforms.

Non-Zen CI runners will succeed when they are Haswell or later, since
a Haswell kernel is compiled as a dependency.

Tested: building numpy against AMD BLIS.

This is a resubmission of #92981.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by danieldk** [comment]
@ofborg build amd-blis

**Comment by bhipple** [comment]
I'm on vacation for a while and haven't had time to review this, but perhaps @matthewbauer could take a look.

**Comment by danieldk** [comment]
> I'm on vacation for a while and haven't had time to review this, but perhaps @matthewbauer could take a look.

Enjoy your vacation! :palm_tree:

**Review by bhipple — APPROVED** [review]

**Comment by danieldk** [comment]
Thanks for the review!

**Pull request merged**
