### PR TITLE
plausible: fixup, older npm + disable stripDebug

### LINKED ISSUE #220178: Build failure: plausible
### Steps To Reproduce

1. build a system configuration with plausible as a service (I'm on NixOS 22.11)

### Build log
https://gist.github.com/jonaslanglotz/57e0dd20303ab4c3e6586a4ad96dc4ee

### Additional context
I'm new to Nix, so I can't make the changes myself, but I've analyzed the issue and have found the problem.

The issue is that when the package was made, nodejs included an older npm version (<9) which still had the `npm bin` command. This has been removed in newer nodejs versions however. This causes an error, because `npm bin` is used in the repository of plausible (atleast for the version that is pinned here). It can either be fixed by using an older nodejs package, using a newer version of the plausible repository or not using the deploy script from the repository and instead calling webpack manually using npm exec.

### Notify maintainers

Unfortunately, there are currently no maintainers. @Ma27 was originally a maintainer, but has removed himself.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.97, NixOS, 22.11 (Raccoon), 22.11.git.47c00341629M`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(jonaslanglotz): `"home-manager"`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by kirillrdy**
###### Description of changes

Due to https://github.com/NixOS/nixpkgs/pull/191237
and nodejs upgrade to 18

Fixes https://github.com/NixOS/nixpkgs/issues/220178

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by apfelkuchen6** [comment]
@ofborg  test plausible

**Comment by ilyakooo0** [comment]
Is there something blocking this PR?

**Comment by kirillrdy** [comment]
> Is there something blocking this PR?

nothing that I am aware of

**Comment by SuperSandro2000** [comment]
Test is timing out

**Comment by kirillrdy** [comment]
nixos test fails locally
here are the only useful bits i could find from the logs

```
machine # [   24.324826] plausible-start[894]: Crash dump is being written to: erl_crash.dump...done
machine # [   24.338008] systemd[1]: plausible.service: Main process exited, code=exited, status=1/FAILURE
machine # [   24.338719] systemd[1]: plausible.service: Failed with result 'exit-code'.
```

**Comment by kirillrdy** [comment]
i just checked on nixos-22.05 where plausible still builds and `nix-build -A nixosTests.plausible` fails as well

**Comment by SuperSandro2000** [comment]
Someone should fix that test.


@ofborg build plausible

**Comment by SuperSandro2000** [comment]
For darwin to work, we need to set HOME to a temporary directory

```

npm ERR! code EROFS
npm ERR! syscall mkdir
npm ERR! path /homeless-shelter
npm ERR! errno -30
npm ERR! rofs EROFS: read-only file system, mkdir '/homeless-shelter'
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.
npm ERR! Log files were not written due to an error writing to the directory: /homeless-shelter/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
```

**Comment by kirillrdy** [comment]
actually nixosTest is correct, the plausible service doesn't start for me, going to mark this PR as draft to further investigate this

**Review by ilyakooo0 — APPROVED** [review]

**Comment by kirillrdy** [comment]
I figured out an other issue that was preventing plausible from starting, its related to https://github.com/NixOS/nixpkgs/pull/191237

nixosTest.plausible passes now

**Pull request merged**
