### PR TITLE
stdenv/check-meta: Fix performance regressions introduced in #294347

### PR DESCRIPTION
**Pull request by adisbladis**
## Description of changes

This fixes a few performance related regressions added in https://github.com/NixOS/nixpkgs/pull/294347

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by lolbinarycat — APPROVED** [review]
faster eval is good, and these changes only increase code complexity by a very small amount.

**Comment by adisbladis** [comment]
Merging as approved.

**Comment by a-n-n-a-l-e-e** [comment]
this change doesn't appear to have any effect. the cpu improvement of -%0.46 seems to be just noise. source: look at the performance improvements of the automated r-ryantm version updates that are basically an eval no-op and this is well in the range of those no-op change.

**Comment by adisbladis** [comment]
There are plenty of performance issues that don't show up at all in ofborg because it evaluates the performance report with meta checking disabled.

Also I'm not just concerned about wall time. I'm also concered about GC pressure, unnecessary memory accesses and the like.

**Comment by a-n-n-a-l-e-e** [comment]
i see. i am a little confused as https://github.com/NixOS/nixpkgs/pull/294347#issuecomment-2027940507 asked to look at the performance report and here you're saying the performance report doesn't matter because it doesn't check the meta attributes. so the performance report seems like it isn't applicable at all to changes in `check-meta.nix`. one would need to be generating a report with meta checking enabled. ok, so how would one generate a performance report while checking the meta attributes?

to perform checks locally, i run https://github.com/NixOS/ofborg?tab=readme-ov-file#running-meta-checks-locally though it is non-obvious to me how to generate a report as is done by the CI. Do you know how to generate the report? was that done on this change?

**Comment by a-n-n-a-l-e-e** [comment]
comparison of this change (opt), patch reverted (unopt) and unopt revert (before). median of 5 runs using local meta checks (x64-linux only).

|          name          |    before     |     unopt     |      opt      |
|------------------------|---------------|---------------|---------------|
| cpuTime                | 128.21        | 133.93        | 131.94        |
| envs.bytes             | 6577933176    | 7090432912    | 7089095808    |
| envs.elements          | 345162663     | 374300258     | 374201006     |
| envs.number            | 238539492     | 256001928     | 255967985     |
| gc.heapSize            | 18928824320   | 19985793024   | 19985793024   |
| gc.totalBytes          | 40469879104   | 43413791152   | 43407905792   |
| list.bytes             | 778152264     | 819291024     | 819291024     |
| list.concats           | 17173345      | 17992679      | 17992679      |
| list.elements          | 97269033      | 102411378     | 102411378     |
| nrAvoided              | 275230098     | 295060652     | 295026708     |
| nrFunctionCalls        | 219458953     | 234732209     | 234732209     |
| nrLookups              | 113944117     | 123621375     | 123553424     |
| nrOpUpdateValuesCopied | 602605428     | 639235093     | 639235093     |
| nrOpUpdates            | 28310008      | 31468152      | 31468152      |
| nrPrimOpCalls          | 121898431     | 128384775     | 128384775     |
| nrThunks               | 337764428     | 366305855     | 366172660     |
| sets.bytes             | 13798853440   | 14793914880   | 14793914880   |
| sets.elements          | 809401006     | 865106113     | 865106113     |
| sets.number            | 53027334      | 59513567      | 59513567      |
| sizes.Attr             | 16            | 16            | 16            |
| sizes.Bindings         | 16            | 16            | 16            |
| sizes.Env              | 16            | 16            | 16            |
| sizes.Value            | 24            | 24            | 24            |
| symbols.bytes          | 2322871       | 2323547       | 2323560       |
| symbols.number         | 167259        | 167328        | 167329        |
| values.bytes           | 10519975920   | 11346920592   | 11343725400   |
| values.number          | 438332330     | 472788358     | 472655225     |

**Comment by a-n-n-a-l-e-e** [comment]
getting rid of the `optionalAttrs` and making repository an empty string eliminates the performance hit.

|          name          |   baseline    | unopt % | opt % | no-attrs % |
|------------------------|---------------|---------|-------|------------|
| cpuTime                | 128.21        | 4.46    | 2.91  | -0.64      |
| envs.bytes             | 6577933176.0  | 7.79    | 7.77  | 0.18       |
| envs.elements          | 345162663.0   | 8.44    | 8.41  | 0.16       |
| envs.number            | 238539492.0   | 7.32    | 7.31  | 0.19       |
| gc.heapSize            | 18928824320.0 | 5.58    | 5.58  | 0.09       |
| gc.totalBytes          | 40469879104.0 | 7.27    | 7.26  | 0.21       |
| list.bytes             | 778152264.0   | 5.29    | 5.29  | 0.08       |
| list.concats           | 17173345.0    | 4.77    | 4.77  | 0.0        |
| list.elements          | 97269033.0    | 5.29    | 5.29  | 0.08       |
| nrAvoided              | 275230098.0   | 7.21    | 7.19  | 0.15       |
| nrFunctionCalls        | 219458953.0   | 6.96    | 6.96  | 0.19       |
| nrLookups              | 113944117.0   | 8.49    | 8.43  | 0.37       |
| nrOpUpdateValuesCopied | 602605428.0   | 6.08    | 6.08  | 0.12       |
| nrOpUpdates            | 28310008.0    | 11.16   | 11.16 | 0.53       |
| nrPrimOpCalls          | 121898431.0   | 5.32    | 5.32  | 0.16       |
| nrThunks               | 337764428.0   | 8.45    | 8.41  | 0.28       |
| sets.bytes             | 13798853440.0 | 7.21    | 7.21  | 0.22       |
| sets.elements          | 809401006.0   | 6.88    | 6.88  | 0.19       |
| sets.number            | 53027334.0    | 12.23   | 12.23 | 0.63       |
| sizes.Attr             | 16.0          | 0.0     | 0.0   | 0.0        |
| sizes.Bindings         | 16.0          | 0.0     | 0.0   | 0.0        |
| sizes.Env              | 16.0          | 0.0     | 0.0   | 0.0        |
| sizes.Value            | 24.0          | 0.0     | 0.0   | 0.0        |
| symbols.bytes          | 2322871.0     | 0.03    | 0.03  | 0.0        |
| symbols.number         | 167259.0      | 0.04    | 0.04  | 0.0        |
| values.bytes           | 10519975920.0 | 7.86    | 7.83  | 0.26       |
| values.number          | 438332330.0   | 7.86    | 7.83  | 0.26       |

**Comment by lolbinarycat** [comment]
what about making it default to an empty list instead?  i think that more appropriately expresses the semantic of "no value", and should be easier to process.

**Comment by a-n-n-a-l-e-e** [comment]
> what about making it default to an empty list instead? i think that more appropriately expresses the semantic of "no value", and should be easier to process.

about the same

|          name          |   baseline    | unopt % | opt % | no-attrs % | no-attrs-list % |
|------------------------|---------------|---------|-------|------------|-----------------|
| cpuTime                | 128.21        | 4.46    | 2.91  | -0.64      | -0.48           |
| envs.bytes             | 6577933176.0  | 7.79    | 7.77  | 0.18       | 0.2             |
| envs.elements          | 345162663.0   | 8.44    | 8.41  | 0.16       | 0.18            |
| envs.number            | 238539492.0   | 7.32    | 7.31  | 0.19       | 0.22            |
| gc.heapSize            | 18928824320.0 | 5.58    | 5.58  | 0.09       | 0.09            |
| gc.totalBytes          | 40469879104.0 | 7.27    | 7.26  | 0.21       | 0.22            |
| list.bytes             | 778152264.0   | 5.29    | 5.29  | 0.08       | 0.08            |
| list.concats           | 17173345.0    | 4.77    | 4.77  | 0.0        | 0.0             |
| list.elements          | 97269033.0    | 5.29    | 5.29  | 0.08       | 0.08            |
| nrAvoided              | 275230098.0   | 7.21    | 7.19  | 0.15       | 0.15            |
| nrFunctionCalls        | 219458953.0   | 6.96    | 6.96  | 0.19       | 0.22            |
| nrLookups              | 113944117.0   | 8.49    | 8.43  | 0.37       | 0.37            |
| nrOpUpdateValuesCopied | 602605428.0   | 6.08    | 6.08  | 0.12       | 0.12            |
| nrOpUpdates            | 28310008.0    | 11.16   | 11.16 | 0.53       | 0.53            |
| nrPrimOpCalls          | 121898431.0   | 5.32    | 5.32  | 0.16       | 0.16            |
| nrThunks               | 337764428.0   | 8.45    | 8.41  | 0.28       | 0.3             |
| sets.bytes             | 13798853440.0 | 7.21    | 7.21  | 0.22       | 0.22            |
| sets.elements          | 809401006.0   | 6.88    | 6.88  | 0.19       | 0.19            |
| sets.number            | 53027334.0    | 12.23   | 12.23 | 0.63       | 0.63            |
| sizes.Attr             | 16.0          | 0.0     | 0.0   | 0.0        | 0.0             |
| sizes.Bindings         | 16.0          | 0.0     | 0.0   | 0.0        | 0.0             |
| sizes.Env              | 16.0          | 0.0     | 0.0   | 0.0        | 0.0             |
| sizes.Value            | 24.0          | 0.0     | 0.0   | 0.0        | 0.0             |
| symbols.bytes          | 2322871.0     | 0.03    | 0.03  | 0.0        | 0.0             |
| symbols.number         | 167259.0      | 0.04    | 0.04  | 0.0        | 0.0             |
| values.bytes           | 10519975920.0 | 7.86    | 7.83  | 0.26       | 0.28            |
| values.number          | 438332330.0   | 7.86    | 7.83  | 0.26       | 0.28            |

**Pull request merged**
