### PR TITLE
gnuradio-osmosdr: add hackrf support

### PR DESCRIPTION
**Pull request by sjmackenzie**

### CODE REVIEW

**Comment by bjornfor** [comment]
Pushed to master in https://github.com/NixOS/nixpkgs/commit/8a82935d46850b51aed5e9ceb864c330990771da.

I removed the "pbcopy" file, which I guess was a mistake :-)

**Comment by sjmackenzie** [comment]
yeah shouldn't be left around those pbcopies, nasty stuff. BTW it seems travis fails ...

**Comment by bjornfor** [comment]
I didn't manage to spot the cause for the travis build failure. It built fine locally (nixos with chroot builds enabled).

**Comment by sjmackenzie** [comment]
Yes it took a long time for me to build locally but build it did. Thanks
for the prompt merge.

**Pull request closed without merging**
