### PR TITLE
python3Packages.dulwich: 0.20.14 -> 0.20.15

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 0.20.15

Additionally:

- Update the `homepage` entry to metadata
- Add `changelog` entry to metadata
- Clarify the licensing (see https://www.dulwich.io/ -> Licensing) or `COPYING`:
  ```text
  Dulwich may be used under the conditions of either of two licenses,
  the Apache License (version 2.0 or later) or the GNU General Public License,
  version 2.0 or later.
  ```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107452` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>devpi-client</li>
    <li>python37Packages.check-manifest</li>
    <li>python38Packages.check-manifest</li>
    <li>python39Packages.breezy</li>
    <li>python39Packages.check-manifest</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>breezy (python38Packages.breezy)</li>
    <li>cabal2nix</li>
    <li>dep2nix</li>
    <li>klaus (python38Packages.klaus)</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-update-source</li>
    <li>python37Packages.breezy</li>
    <li>python37Packages.dulwich</li>
    <li>python37Packages.klaus</li>
    <li>python38Packages.dulwich</li>
    <li>python39Packages.dulwich</li>
    <li>python39Packages.klaus</li>
    <li>reno</li>
    <li>vcstool</li>
    <li>xandikos</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107452` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>devpi-client</li>
    <li>python37Packages.check-manifest</li>
    <li>python38Packages.check-manifest</li>
  </ul>
</details>
<details>
  <summary>20 packages built:</summary>
  <ul>
    <li>breezy (python38Packages.breezy)</li>
    <li>cabal2nix</li>
    <li>dep2nix</li>
    <li>errbot</li>
    <li>flatpak-builder</li>
    <li>hydra-unstable</li>
    <li>klaus (python38Packages.klaus)</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-update-source</li>
    <li>python37Packages.breezy</li>
    <li>python37Packages.dulwich</li>
    <li>python37Packages.klaus</li>
    <li>python38Packages.dulwich</li>
    <li>python39Packages.dulwich</li>
    <li>python39Packages.klaus</li>
    <li>rabbitvcs</li>
    <li>reno</li>
    <li>vcstool</li>
    <li>xandikos</li>
  </ul>
</details>

check-manifest

```
ERROR: Could not find a version that satisfies the requirement build>=0.1 (from check-manifest)
```

**Comment by fabaff** [comment]
> ERROR: Could not find a version that satisfies the requirement build>=0.1 (from check-manifest)

Thanks. Updates are included.

**Review by ruuda — APPROVED** [review]
Thanks! The changes to the code look good to me. I haven’t tried to build these packages or dependencies.

**Comment by prusnak** [comment]
@GrahamcOfBorg build python3Packages.build python3Packages.dulwich python3Packages.pep517 python3Packages.proto-plus

**Comment by prusnak** [comment]
Some of the updates causes a massive rebuild. Can you please split the PR into 4 different PRs so we can review/accept them individually?

**Comment by fabaff** [comment]
Break-outs:

- pep517: https://github.com/NixOS/nixpkgs/pull/108255

**Comment by prusnak** [comment]
> Break-outs:
> * pep517: #108255

Can you please remove pep517 from the changeset to see whether the rebuild is smaller now?

**Comment by fabaff** [comment]
> Can you please remove pep517 from the changeset to see whether the rebuild is smaller now?

Removed

**Comment by prusnak** [comment]
@GrahamcOfBorg build python3Packages.dulwich python3Packages.build python3Packages.proto-plus

**Comment by prusnak** [comment]
This PR is blocked until https://github.com/NixOS/nixpkgs/pull/108255 arrives from staging to master

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Comment by fabaff** [comment]
Updated commit messages to match the comment in another PR.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 107452` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
23 packages built:
</summary>
<ul>
<li>breezy (python38Packages.breezy)</li>
<li>cabal2nix</li>
<li>dep2nix</li>
<li>devpi-client</li>
<li>errbot</li>
<li>flatpak-builder</li>
<li>hydra-unstable</li>
<li>klaus (python38Packages.klaus)</li>
<li>nix-prefetch-bzr</li>
<li>nix-prefetch-scripts</li>
<li>nix-update-source</li>
<li>python37Packages.breezy</li>
<li>python37Packages.check-manifest</li>
<li>python37Packages.dulwich</li>
<li>python37Packages.klaus</li>
<li>python38Packages.check-manifest</li>
<li>python38Packages.dulwich</li>
<li>python39Packages.dulwich</li>
<li>python39Packages.klaus</li>
<li>rabbitvcs</li>
<li>reno</li>
<li>vcstool</li>
<li>xandikos</li>
</ul>
</details>

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 107452 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>23 packages built:</summary>  <ul>    <li>breezy (python38Packages.breezy)</li>    <li>cabal2nix</li>    <li>dep2nix</li>    <li>devpi-client</li>    <li>errbot</li>    <li>flatpak-builder</li>    <li>hydra-unstable</li>    <li>klaus (python38Packages.klaus)</li>    <li>nix-prefetch-bzr</li>    <li>nix-prefetch-scripts</li>    <li>nix-update-source</li>    <li>python37Packages.breezy</li>    <li>python37Packages.check-manifest</li>    <li>python37Packages.dulwich</li>    <li>python37Packages.klaus</li>    <li>python38Packages.check-manifest</li>    <li>python38Packages.dulwich</li>    <li>python39Packages.dulwich</li>    <li>python39Packages.klaus</li>    <li>rabbitvcs</li>    <li>reno</li>    <li>vcstool</li>    <li>xandikos</li>  </ul></details>

**Pull request merged**
