### PR TITLE
deno: 1.19.1 -> 1.19.3

### PR DESCRIPTION
**Pull request by kidonng**
###### Description of changes

https://github.com/denoland/deno/releases/tag/v1.19.3

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by milahu — APPROVED** [review]

**Comment by bobby285271** [comment]
Have you tested building this? I think this will probably require #161726 :thinking: 

屏幕截图 2022-03-13 16 19 20

**Comment by bobby285271** [comment]
If there is no respond I plan to revert this in a few hours :eyes:

**Comment by kidonng** [comment]
> Have you tested building this? I think this will probably require #161726 (in staging) (see [denoland/deno#13767](https://github.com/denoland/deno/pull/13767)), shall we revert? 🤔

I was fiddling with something in staging previously, must have the wrong impression this is in master 😅
Deno release notes didn't mention the Rust upgrade either.

Odd that Ofborg shows a neutral check status for failed evaluation, that happened to my another pull request. I think the best to do it to revert this update and wait for the current staging next. Thanks for noticing this!

**Comment by 06kellyjac** [comment]
I think ofborg always shows failures as neutral.

**Comment by bobby285271** [comment]
I think ofborg will only push fail status when [a fixed output derivation's hash was incorrect](https://github.com/NixOS/ofborg/blob/d934ebe9af7adcde114a4cb66cf9458cc1dd8e28/ofborg/src/message/buildresult.rs#L34), example is https://github.com/NixOS/nixpkgs/commit/a17174204ce263c7363083d0c1aaad1481fed397 (I haven't investigate that yet...)

**Comment by SuperSandro2000** [comment]
> I think ofborg always shows failures as neutral.

Yeah, many times complained but nothing changes.

**Pull request merged**
