### PR TITLE
imagemagick6: 6.9.10-68 -> 6.9.10-69, imagemagick7: 7.0.8-68 -> 7.0.9-0

### PR DESCRIPTION
**Pull request by risicle**
###### Motivation for this change
As noted by @pacien in https://github.com/NixOS/nixpkgs/pull/71099#issuecomment-546651300, that security bump resulted in some breakages as a side effect. We should probably fix that.

This was because the reverse dependencies of imagemagick are unfortunately huge and I had little chance of building them all.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by pacien** [comment]
You were quicker than me :)

@ofborg build imagemagick
@ofborg build imagemagick7

Let's also test one of the package the previous update broke:

@ofborg build gscan2pdf

**Comment by flokli** [comment]
@ofborg build imagemagick
@ofborg build imagemagick7
@ofborg build gscan2pdf

**Comment by flokli** [comment]
@risicle gscan2pdf still seems to fail for me:

```
Test Summary Report
-------------------
t/1111_save_pdf.t                           (Wstat: 512 Tests: 9 Failed: 2)
  Failed tests:  5-6
  Non-zero exit status: 2
t/232_analyse_dark.t                        (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
t/357_unpaper_rtl.t                         (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  3
  Non-zero exit status: 1
t/52_process_chain_udt.t                    (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=231, Tests=1083, 371 wallclock secs ( 1.45 usr  0.40 sys + 180.61 cusr 79.91 csys = 262.37 CPU)
Result: FAIL
Failed 4/231 test programs. 5/1083 subtests failed.
```

**Comment by pacien** [comment]
Apparently ImageMagick 6.9.10-69 and 7.0.9-0 do not solve all the regressions introduced before. Maybe should we wait a bit more for the next releases?

**Comment by flokli** [comment]
Hm, I think this PR doesn't worsen the situation, `gscan2pdf` was already broken before, but it hopefully fixes some CVEs in between. WDYT?

This might also need backporting to 19.09.

**Pull request merged**
