### PR TITLE
glibc: fix cross compilation build failure

### PR DESCRIPTION
**Pull request by thefloweringash**
###### Motivation for this change

Fix cross compiled glibc which fails due to warnings. I don't know why these warnings only show up in cross compilation, but it lets us avoid a mass rebuild of glibc.

Tested on an x86_64 builder
- [x] pkgsCross.riscv64.hello
- [x] pkgsCross.aarch64-multiplatform.hello
- [x] pkgsCross.armv7l-hf-multiplatform.hello

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by thefloweringash** [comment]
This change fixes the symptoms, but I'm really sure of the cause. Why is the gcc 8 warning only showing up now? There's also some overlap with the `gdCflags`.

**Review by lopsided98 — APPROVED** [review]
Fixes the build for me.

**Comment by Ma27** [comment]
> This change fixes the symptoms, but I'm really not sure of the cause

I assume that this is due to the fact that we still have glibc 2.27 which was released >2 years ago (current version is 2.30) and it's just not "compatible" with newer compilers (the glibc 2.30 update is currently worked on in #66528).

> Why is the gcc 8 warning only showing up now?

Just a wild guess, but perhaps nobody noticed? (it seems to occur only when cross-compiling and we had gcc7 by default for a long time).

**Review by Ma27 — APPROVED** [review]
As I didn't see that one before, I basically tried the same after getting notified in #77504 and this seems fine. But before merging, I'd prefer to wait for some more reviews :)

**Review by flokli — COMMENTED** [review]
LGTM - however, it might be wiser to apply it for non-cross too - either here (and then target staging), or as a follow-up PR to staging once this PR is merged.

**Comment by Mindavi** [comment]
Wouldn't it be better to apply the patch for the OOB access? It seems like a fix that's easy to apply.

**Comment by flokli** [comment]
@Mindavi indeed - so this should `fetchpatch` `https://sourceware.org/git/gitweb.cgi?p=glibc.git;a=patch;h=9c79cec8cd2a6996a73aa83d79b360ffd4bebde6;hp=969c3355069215f1c1cad800a822d0b303fdc1fa` unconditionally.

**Comment by thefloweringash** [comment]
Updating but patch doesn't apply. Hold on a moment while I sort this out.

**Review by flokli — APPROVED** [review]

**Comment by thefloweringash** [comment]
@flokli sorry I got the backport wrong. Please revert this.

**Comment by flokli** [comment]
Reverted 51014768d2f2cc61fd70d39747f6d070583864ec in cd827f2209b35c4c3bdd5492c3e9a9d351e3e3b3.

**Pull request merged**
