### PR TITLE
binwalk: migrate to fork, 2.4.1

### PR DESCRIPTION
**Pull request by jchv**
## Description of changes

Binwalk has [gone unmaintained for some time](https://github.com/ReFirmLabs/binwalk/issues/671), unfortunately. Thankfully our friends at Gentoo have been [maintaining a fork](https://github.com/OSPG/binwalk). It is currently used by both [Gentoo](https://gitweb.gentoo.org/repo/gentoo.git/tree/app-misc/binwalk/binwalk-2.4.1.ebuild) and [Alpine](https://git.alpinelinux.org/aports/tree/testing/binwalk/APKBUILD).

This PR moves to the fork and updates the derivation accordingly. It also migrates to the PEP517 builder.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by emilazy — APPROVED** [review]
Arch, Void, Exherbo, and MSYS2 all use this fork too. At a glance, the new upstream seems reputable, development looks reasonably active, and they seem to understand what a licence is…

Do you know how this might affect the weird test behaviour in https://github.com/NixOS/nixpkgs/pull/325623?

Result of `nixpkgs-review pr 326295` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>ghidra-extensions.ghidraninja-ghidra-scripts</li>
  </ul>
</details>
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>binwalk (python312Packages.binwalk)</li>
    <li>binwalk.dist (python312Packages.binwalk.dist)</li>
    <li>diffoscope</li>
    <li>diffoscope.dist</li>
    <li>diffoscope.man</li>
    <li>python311Packages.binwalk</li>
    <li>python311Packages.binwalk-full</li>
    <li>python311Packages.binwalk-full.dist</li>
    <li>python311Packages.binwalk.dist</li>
    <li>python312Packages.binwalk-full</li>
    <li>python312Packages.binwalk-full.dist</li>
  </ul>
</details>

**Comment by emilazy** [comment]
Yeah, I guess this fork is fine but the other patch wasn’t, somehow…? Or skipping the checks on 3.12 somehow broke it in the other PR? But hey, it built fine…

cc @philiptaron

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 326295` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>ghidra-extensions.ghidraninja-ghidra-scripts</li>
  </ul>
</details>
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>binwalk (python312Packages.binwalk)</li>
    <li>binwalk.dist (python312Packages.binwalk.dist)</li>
    <li>diffoscope</li>
    <li>diffoscope.dist</li>
    <li>diffoscope.man</li>
    <li>python311Packages.binwalk</li>
    <li>python311Packages.binwalk-full</li>
    <li>python311Packages.binwalk-full.dist</li>
    <li>python311Packages.binwalk.dist</li>
    <li>python312Packages.binwalk-full</li>
    <li>python312Packages.binwalk-full.dist</li>
  </ul>
</details>

**Review by superherointj — APPROVED** [review]

**Comment by emilazy** [comment]
I don’t think the 3.12 switch is on 24.05…?

**Review by philiptaron — COMMENTED** [review]
Thanks. I'll close https://github.com/NixOS/nixpkgs/pull/325623.

**Pull request merged**
