### PR TITLE
gcc: fix cyclic dependency for Darwin cross-build

### PR DESCRIPTION
**Pull request by mroi**
When building a cross-compiler for Linux targets on Darwin hosts, the sanitizer libraries are built as Linux ELF shared objects. These binaries contain superfluous rpaths, causing a cyclic dependency between the out and lib outputs.

Manually pruning rpaths with `patchelf` fixes the issue. This should have no impact on non-cross builds.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by parthy** [comment]
@mroi Are you aware of the discussion in https://github.com/NixOS/nixpkgs/issues/88213?

**Comment by mroi** [comment]
No I was not. Sorry about that. It describes exactly the problem I was seeing: rpaths in the sanitizer libraries caused dependency cycles because they have been moved to a separate output.

With my patch, I get a working cross-compiler. But I am not sure if there is a better way to fix this, like reverting d9feea58aeded06aded50eee7e9d69ebe1086e7e.

**Comment by TravisWhitaker** [comment]
@Ericson2314 @matthewbauer what are your thoughts on this approach versus @Gaelan 's https://github.com/NixOS/nixpkgs/compare/master...Gaelan:gcc-cross ?

**Comment by mroi** [comment]
It has been decided to go with PR #88213. I am closing this one and suggest everyone to follow that PR.

**Pull request closed without merging**
