### PR TITLE
php: 7.4.4 -> 7.4.5, 7.3.16 -> 7.3.17

### PR DESCRIPTION
**Pull request by etu**
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by etu** [comment]
@GrahamcOfBorg build php73 php74
@GrahamcOfBorg nixosTests.php

**Review by Ma27 — COMMENTED** [review]
@etu while it's building and working fine on my machine, darwin and aarch64 seem to break because of this update. Could you take a look, please? :)

**Comment by ajs124** [comment]
What's the status on this? There also seems to be a merge conflict, now.

**Comment by etu** [comment]
@ajs124 For easier testing and being able to merge the different versions independent of each other I've fixed the conflicts and will open separate PR's.

**Pull request closed without merging**
