### PR TITLE
Simplify fetchurl assertion logic.

### PR DESCRIPTION
**Pull request by solson**
The two lines I removed technically assert the exact same thing, since `!a -> b`
is equivalent to `a || b`. So, I replaced the two lines with the more symmetric
form to make it clearer.

### CODE REVIEW

**Comment by vcunat** [comment]
Specifying both `url` and `urls` makes no sense, I believe, so we might as well replace it by and *exclusive* or ``assert (urls == []) != (url == "");``.

**Comment by tsion** [comment]
Yeah, I'll do that. Currently the `url` is ignored is `urls` is nonempty.

**Comment by zimbatm** [comment]
Alright. Basically urls not empty XOR url not empty.

**Comment by jagajaga** [comment]
@zimbatm why do we need several commit's if it's better if there is a clear one? So we ask people to squash commits in such situations.

**Comment by zimbatm** [comment]
@jagajaga ack, doing better next time

**Pull request merged**
