### PR TITLE
Documentation: rewrite Python

### PR DESCRIPTION
**Pull request by FRidh**
In #13320 I proposed documentation changes that I accidentally merged and reverted in #13699.
This is a new PR with the proposed changes.

### CODE REVIEW

**Comment by FRidh** [comment]
Unfortunately I get some errors when building the docs:
```
manual.xml:4: element info: Relax-NG validity error : Did not expect element info there
manual.xml:4: element info: Relax-NG validity error : Element book has extra content: info
```

**Comment by domenkozar** [comment]
That means you have misplaced tag somewhere. Or a tag missing.

**Comment by domenkozar** [comment]
Maybe try https://github.com/NixOS/nixpkgs/issues/4966#issuecomment-62956478

**Comment by FRidh** [comment]
I've added an example on how to use `overridePackages` with Python after #12820. See aee52cfeebcb1ff2f9716eda3af640429414358c

**Comment by edolstra** [comment]
Please don't add more Markdown to the manual, use DocBook instead.

**Comment by domenkozar** [comment]
Added milestone to 16.03 as this is very valuable.

**Comment by domenkozar** [comment]
@FRidh do you need some help with this?

**Comment by FRidh** [comment]
Yes please. It would be great to get this building. I'm packed this month which is why I haven't really looked at it anymore.

**Comment by domenkozar** [comment]
@edolstra both me and Fridh lately contribute most to Python ecosystem and neither of us want to maintain docbook. I see two options to make everyone happy:

- we allow markdown and docbook formats in nixpkgs only
- we split off python documentation separately and provide a link from nixpkgs manual

**Comment by copumpkin** [comment]
@domenkozar @edolstra perhaps our documentation-building process could invoke pandoc and auto-convert markdown to docbook prior to the final doc generation? It seems fairly easy to encode that logic in nix.

**Comment by vcunat** [comment]
@copumpkin: that's what is utilized in a few cases, *including* this PR.

**Comment by copumpkin** [comment]
Oh, my apologies then!

**Comment by domenkozar** [comment]
@FRidh also see https://github.com/NixOS/nixpkgs/pull/14320

**Pull request merged**
