### PR TITLE
vmware-workstation: 17.5.2 -> 17.6.1

### PR DESCRIPTION
**Pull request by vifino**
## Description of changes

https://docs.vmware.com/en/VMware-Workstation-Pro/17.6/rn/vmware-workstation-176-pro-release-notes/index.html

VMware dropped a bunch of tools ISOs from this release. 

Modules are switched to a fork of the mkubecek repo until that is updated.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]
Lgtm

**Comment by vifino** [comment]
Any chance to move this along?

**Comment by js6pak** [comment]
[17.6.1](https://docs.vmware.com/en/VMware-Workstation-Pro/17.6.1/rn/vmware-workstation-1761-pro-release-notes/index.html) has been released a few days ago, so might aswell update to it directly. There's a host-modules fork here https://github.com/mkubecek/vmware-host-modules/pull/288, and I can confirm it works (on 6.11 kernel).

@vifino Do the preinstalled guest tools isos work for you? For me vmware says it can't find them (testing with windows11-x64):
image
If vmware can auto download them anyway, maybe we should just drop the `enableGuestTools` option to reduce complexity?

**Comment by vifino** [comment]
> [17.6.1](https://docs.vmware.com/en/VMware-Workstation-Pro/17.6.1/rn/vmware-workstation-1761-pro-release-notes/index.html) has been released a few days ago, so might aswell update to it directly. There's a host-modules fork here [mkubecek/vmware-host-modules#288](https://github.com/mkubecek/vmware-host-modules/pull/288), and I can confirm it works (on 6.11 kernel).

Will do.

> @vifino Do the preinstalled guest tools isos work for you? For me vmware says it can't find them (testing with windows11-x64): image If vmware can auto download them anyway, maybe we should just drop the `enableGuestTools` option to reduce complexity?

No, the tools ISOs haven't worked for me ever. Does the download work for you? I haven't tested it yet.

**Comment by js6pak** [comment]
>  Does the download work for you?

It does, yes.


On the topic of removing broken things, what about `enableInstaller`? It doesn't even build today, needs quite a lot of code and even the original PR (#169966) mentioned[^1] that it's useless in NixOS (and I don't see how it would work outside NixOS, because the installer would have to write into nix store anyway?)

`enableMacOSGuests` seems to build successfully at least, but something to note is that if we updated the `com.vmware.fusion.zip.tar` to `13.6.1`, it would no longer have the darwin guest tool isos. VMWare docs say[^2] that Workstation now downloads the needed guest tools from https://packages-prod.broadcom.com/tools/frozen/, and darwin isos are there so I think we can assume it's fine to remove the darwin iso code from here aswell?

[^1]: > `vmware-workstation` package includes `enableInstaller` option to output `vmware-installer` binary and databases which won't work anyway due to non-FHS of NixOS
[^2]: https://docs.vmware.com/en/VMware-Tools/12.5.0/com.vmware.vsphere.vmwaretools.doc/GUID-D8892B15-73A5-4FCE-AB7D-56C2C90BD951.html
	image

**Comment by vifino** [comment]
@js6pak Yup, `enableInstaller` can go as well if you ask me, especially as it was [mentioned](https://github.com/NixOS/nixpkgs/pull/315242#issuecomment-2142370887) enabling it broke downloading tools.

**Comment by js6pak** [comment]
@vifino Does this PR work as is for you?

I'm getting the following crash
```
❯ vmware
[AppLoader] Cannot get library dependencies. (4a)
[AppLoader] Fallback to use all shipped libraries.
[AppLoader] Fail to load the library. /nix/store/5d4s33ys70ad8q9smw6brdidblpp0j03-libxcb-1.17.0/lib/libxcb-shm.so.0: undefined symbol: xcb_send_request_with_fds
```

I have honestly no idea how it even picks up that libxcb, but I guess it conflicts with whatever X libraries vmware ships now.

I got it working with this patch
```patch
From 353d89c2432a90dea319c808a05304410d464922 Mon Sep 17 00:00:00 2001
From: js6pak <me@6pak.dev>
Date: Sun, 13 Oct 2024 20:57:07 +0200
Subject: [PATCH] vmware-workstation: use system X11 libraries

---
 .../vmware-workstation/default.nix            | 35 ++++++++++++++-----
 1 file changed, 26 insertions(+), 9 deletions(-)

diff --git a/pkgs/applications/virtualization/vmware-workstation/default.nix b/pkgs/applications/virtualization/vmware-workstation/default.nix
index 5556ecdc91a3..6b6e17d6fa3b 100644
--- a/pkgs/applications/virtualization/vmware-workstation/default.nix
+++ b/pkgs/applications/virtualization/vmware-workstation/default.nix
@@ -12,7 +12,6 @@
 , readline70
 , xz
 , cups
-, glibc
 , libaio
 , vulkan-loader
 , alsa-lib
@@ -20,8 +19,7 @@
 , libxcrypt-legacy
 , libGL
 , numactl
-, libX11
-, libXi
+, xorg
 , kmod
 , python3
 , autoPatchelfHook
@@ -82,7 +80,6 @@ stdenv.mkDerivation rec {
     readline
     xz
     cups
-    glibc
     libaio
     vulkan-loader
     alsa-lib
@@ -90,9 +87,21 @@ stdenv.mkDerivation rec {
     libxcrypt-legacy
     libGL
     numactl
-    libX11
-    libXi
-    kmod
+    xorg.libX11
+    xorg.libXau
+    xorg.libXcomposite
+    xorg.libXcursor
+    xorg.libXdamage
+    xorg.libXdmcp
+    xorg.libXext
+    xorg.libXfixes
+    xorg.libXft
+    xorg.libXinerama
+    xorg.libXi
+    xorg.libXrandr
+    xorg.libXrender
+    xorg.libXScrnSaver
+    xorg.libXtst
   ];
 
   nativeBuildInputs = [ python3 vmware-unpack-env autoPatchelfHook makeWrapper ]
@@ -234,8 +243,8 @@ stdenv.mkDerivation rec {
         --add-needed ${libpulseaudio}/lib/libpulse.so.0 \
         --add-needed ${libGL}/lib/libEGL.so.1 \
         --add-needed ${numactl}/lib/libnuma.so.1 \
-        --add-needed ${libX11}/lib/libX11.so.6 \
-        --add-needed ${libXi}/lib/libXi.so.6 \
+        --add-needed ${xorg.libX11}/lib/libX11.so.6 \
+        --add-needed ${xorg.libXi}/lib/libXi.so.6 \
         --add-needed ${libGL}/lib/libGL.so.1 \
         $out/lib/vmware/bin/$binary
     done
@@ -372,6 +381,14 @@ stdenv.mkDerivation rec {
     rm $out/lib/vmware/bin/vmware-vmx
     ln -s /run/wrappers/bin/vmware-vmx $out/lib/vmware/bin/vmware-vmx
 
+    # Remove shipped X11 libraries
+    for lib in $out/lib/vmware/lib/* $out/lib/vmware-ovftool/lib*.so*; do
+      lib_name="$(basename "$lib")"
+      if [[ "$lib_name" == libX* || "$lib_name" == libxcb* ]]; then
+        rm -rf "$lib"
+      fi
+    done
+
     runHook postInstall
   '';
 
-- 
2.46.0
```

Keep in mind lib directory comes from `/etc/vmware/config`, so you have to update your system every time you want to test a change (can we fix this somehow?)

**Comment by vifino** [comment]
Thanks for making me double-check this, @js6pak. No, indeed, it wasn't starting!

I've applied the patch and I'm honestly a bit astounded that you managed to make VMware use skip the bundled libraries.
I've tried this in the past (with earlier versions, obviously) and didn't manage to get it working.

Getting rid of some more of the shipped libraries also seems worthwhile. I had a commit that removed a bunch of stuff, but unfortunately it is lost in time/force-push crimes.

**Comment by js6pak** [comment]
> Getting rid of some more of the shipped libraries also seems worthwhile

I tried doing that, but it's mostly ancient ABI-incompatible GTK libraries that we would have to write new derivations for, I don't think it's worth the trouble.

**Comment by vifino** [comment]
> I tried doing that, but it's mostly ancient ABI-incompatible GTK libraries that we would have to write new derivations for, I don't think it's worth the trouble.

Hrm, that's unfortunate.

**Review by SuperSandro2000 — APPROVED** [review]
Lgtm

**Review by js6pak — APPROVED** [review]

**Pull request merged**
