### PR TITLE
gopass: 1.8.6 -> unstable-2019-07-31

### PR DESCRIPTION
**Pull request by colemickens**
###### Motivation for this change
Mostly just to get feedback on how to build the new version built with module support.

cc: @worldofpeace 

Here's the **failing** build log: https://gist.github.com/colemickens/e0f7be3c350a583bb9c69b6caa9b73f2

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by worldofpeace** [comment]
This works for me @colemickens 

```diff
diff --git a/pkgs/tools/security/gopass/default.nix b/pkgs/tools/security/gopass/default.nix
index 25b7a6580ad..0765b16c8a3 100644
--- a/pkgs/tools/security/gopass/default.nix
+++ b/pkgs/tools/security/gopass/default.nix
@@ -3,9 +3,6 @@
 , wl-clipboard, xclip
 , makeWrapper }:
 
-let
-  metadata = import ./metadata.nix;
-in
 buildGoModule rec {
   pname = "gopass";
   version = "8c7b4a250052d401722b6cbf9308b23a3d3d5661";
@@ -20,29 +17,25 @@ buildGoModule rec {
   modSha256 = "0ijj5sc2q9fx94slxxzqnx97f833pk48a0jfvq9dk9y9biszf2q4";
 
   nativeBuildInputs = [ makeWrapper ];
-  DESTDIR = placeholder "out";
-  
+
+  makeFlags = [
+    "PREFIX=${placeholder ''out''}"
+  ];
+
   wrapperPath = with stdenv.lib; makeBinPath ([
     git
     gnupg
     xclip
   ] ++ stdenv.lib.optional stdenv.isLinux wl-clipboard);
 
-  postInstall = ''
-    mkdir -p \
-      $bin/share/bash-completion/completions \
-      $bin/share/zsh/site-functions \
-      $bin/share/fish/vendor_completions.d
-    $bin/bin/gopass completion bash > $bin/share/bash-completion/completions/_gopass
-    $bin/bin/gopass completion zsh  > $bin/share/zsh/site-functions/_gopass
-    $bin/bin/gopass completion fish > $bin/share/fish/vendor_completions.d/gopass.fish
-  '';
-
   postFixup = ''
-    wrapProgram $bin/bin/gopass \
+    wrapProgram $out/bin/gopass \
       --prefix PATH : "${wrapperPath}"
   '';
 
+  # Use makefile installPhase for completions
+  installPhase = null;
+
   meta = with stdenv.lib; {
     description     = "The slightly more awesome Standard Unix Password Manager for Teams. Written in Go.";
     homepage        = https://www.gopass.pw/;

**Comment by kalbasit** [comment]
@GrahamcOfBorg build gopass

**Comment by colemickens** [comment]
Thanks @worldofpeace. No need to merge this, IMO, but I did update it so it will be around for then next gopass release.

**Comment by marsam** [comment]
addressed by https://github.com/NixOS/nixpkgs/pull/86503

**Pull request closed without merging**
