### PR TITLE
nixos/wireguard: add reload support

### PR DESCRIPTION
**Pull request by Anillc**
###### Motivation for this change

add reload support for wireguard module.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by aanderse — CHANGES_REQUESTED** [review]
I'm not a `wireguard` user and from glancing over the code it wasn't immediately obvious to me if the usual security implications of `reloadIfChanged` apply here. If the usual security implications associated with `reloadIfChanged` do apply here, which I assume they do, can you please come up with a way to educate users (add a note to the module description somewhere, add release notes mentioning the change, other?) please? If there are no security implications can you please add a comment above `reloadIfChanged` briefly explaining why not?

Thanks!

**Comment by Anillc** [comment]
I'm sorry, there were some problems with my previous logic, now I have fixed them and I have added some description.

**Comment by aanderse** [comment]
I didn't mean anything related to `wireguard` at all. I meant that `reloadIfChanged` prevents software from restarting which can be problematic when you do a NixOS upgrade that includes security patches for `wireguard` (or any of its dependencies) and then forget to manually restart the service.

**Comment by Anillc** [comment]
Oh, sorry. I mistook your meaning. Now I have added a note in the description of `interfaces` to tell users about restarting the services.

**Comment by aanderse** [comment]
@Anillc sorry for the lack of reply. Currently @andir is validating how accurate my comment is... I will get back to you once we have some additional information.

**Comment by aanderse** [comment]
Linking relevant conversation here: https://github.com/NixOS/nixpkgs/pull/151241#discussion_r772444301

**Comment by Anillc** [comment]
> Linking relevant conversation here: [#151241 (comment)](https://github.com/NixOS/nixpkgs/pull/151241#discussion_r772444301)

I just ran into a situation where the binary was changed.

<https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/networking/bird.nix#L69>

The bird has its reload function so there is reloadIfChanged in the service definition. When the binary updated and I deployed them to my machines, I found my birds are not restarted (The location of new birds' bird.ctl had changed but the birds were stil running with old bird.ctl).

**Comment by Anillc** [comment]
I think this pull request is not good. There are many cases I haven't thought of. I'm going to close this pull request.

**Pull request closed without merging**
