### PR TITLE
nextcloud30: 30.0.2 -> 30.0.4

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Things done

Changelog: https://github.com/nextcloud/server/releases/tag/v30.0.4

cc @schneefux @bachp @globin @Ma27

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 364566`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>nextcloud30</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>nextcloud30</li>
  </ul>
</details>

---
### `x86_64-darwin`

---
### `aarch64-darwin`

**Comment by GaetanLepage** [comment]
Are nextcloud bumps usually backported ?

**Review by Ma27 — APPROVED** [review]

**Comment by GaetanLepage** [comment]
> I'd like to test this as well, more coverage in actual environments is always good here. Perhaps this evening.

Thanks a lot :)



> Also, why didn't you update nextcloud28?

Done !



> Also, do note that the package itself is super boring: it's basically PHP code copied into an out-path with meta attached to it (and patches from time to time). So for testing, you want to run the test-suite at the very least.

Sure, all the tests pass except one: `vm-test-run-nextcloud-with-postgresql-and-redis28`, which is also failing on `master`.

**Comment by Ma27** [comment]
Ah right, nextcloud notify push seems to fail there. cc @SuperSandro2000 .

**Comment by SuperSandro2000** [comment]
Where?

**Comment by Ma27** [comment]
> Sure, all the tests pass except one: vm-test-run-nextcloud-with-postgresql-and-redis28, which is also failing on master.

**Comment by GaetanLepage** [comment]
> Ah right, nextcloud notify push seems to fail there. cc @SuperSandro2000 .

Log: https://paste.glepage.com/raw/ape-pigeon-horse

**Comment by SuperSandro2000** [comment]
#365442

**Pull request merged**
