### PR TITLE
qgis: 3.28.3 -> 3.32.2

### PR DESCRIPTION
**Pull request by imincik**
## Description of changes

Update QGIS to the latest release.

List of new features is quite massive because we skipped one major release - 3.30.

List of changes:

* https://changelog.qgis.org/en/qgis/version/3.30/
* https://changelog.qgis.org/en/qgis/version/3.32/

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by imincik** [comment]
@offborg build qgis

**Comment by matthiasbeyer** [comment]
Result of `nixpkgs-review pr 250717` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>qgis</li>
    <li>qgis-ltr</li>
  </ul>
</details>

**Comment by imincik** [comment]
@ofborg build qgis

**Comment by imincik** [comment]
Manually tested:

* running built binary with test project from QGIS source code

screen-imincik-2023-08-23-12:53:21

**Comment by imincik** [comment]
@timlinux , please test if you can. Thank you

**Review by markuskowa — APPROVED** [review]

**Comment by imincik** [comment]
@markuskowa ,

thank you very much for approval.

I was not sure setting variable like this is a good idea. What do you think ?

```
  preBuild = ''
    export QT_QPA_PLATFORM_PLUGIN_PATH=${qtbase.bin}/lib/qt-${qtbase.version}/plugins/platforms
  '';
```

**Comment by markuskowa** [comment]
> I was not sure setting variable like this is a good idea. What do you think ?
> 
> ```
>   preBuild = ''
>     export QT_QPA_PLATFORM_PLUGIN_PATH=${qtbase.bin}/lib/qt-${qtbase.version}/plugins/platforms
>   '';
> ```

I am not sure if it is the best solution, but it seems plausible to me to make it work consistently. Just grepping there are a few other packages that use the same trick.

**Comment by imincik** [comment]
Thank you very much @markuskowa

**Comment by imincik** [comment]
> Shall I merge?

@matthiasbeyer , please wait for more testing from @timlinux.

**Comment by timlinux** [comment]
@imincik Thank you - I have been testing and it all seems good so far. Some thoughts on the build definition:

1. I think building the tests is pretty wasteful of natural resources (electricity etc) since most likely no user will use them and we don't actually run them to verify our build is good (I don't think that is needed).
2. QGIS Server - again I think we should probably disable this and make separate package for it
3. Application shortcuts - in my tweaked version I made symlinks in the post build step to link qgis -> qgis-latest and qgis -> qgis-ltr so that if you install both packages you can launch them without having to figure out their absolute path in the store. Similarly it would be nice to generate discrete .desktop files for each build profile so they can be launched easily from the users WM.
image
4. I tested with SAGA and that seems to work nicely (using the newish SAGA python plugin). Could you clarify what is needed to have a build with GRASS support - and also perhaps consider enabling GRASS by default?

Thanks so much for completing my NixOS experience with this patch!

Tim

**Comment by imincik** [comment]
Thank you very much for testing @timlinux.

> 1. I think building the tests is pretty wasteful of natural resources (electricity etc) since most likely no user will use them and we don't actually run them to verify our build is good (I don't think that is needed).

Yes, if tests are not executed a part of build process, we can try to enable them them or disable them completely using 
```
"-DENABLE_TESTS=False"
```
> 2. QGIS Server - again I think we should probably disable this and make separate package for it

Yes, I agree with this. Would you please create issue for that ?

> 3. Application shortcuts - in my tweaked version I made symlinks in the post build step to link qgis -> qgis-latest and qgis -> qgis-ltr so that if you install both packages you can launch them without having to figure out their absolute path in the store. Similarly it would be nice to generate discrete .desktop files for each build profile so they can be launched easily from the users WM.
>    image

Yes, I think we can do this. Would you please create issue for that ?

> 4. I tested with SAGA and that seems to work nicely (using the newish SAGA python plugin). Could you clarify what is needed to have a build with GRASS support - and also perhaps consider enabling GRASS by default?

GRASS support should be enabled by default using `withGrass` parameter which is `true` by default.

> Thanks so much for completing my NixOS experience with this patch!

You are welcome. And as I already said, you are welcome to be a part of Nix Geospatial team.

**Comment by imincik** [comment]
@matthiasbeyer , please merge now.

**Comment by matthiasbeyer** [comment]
:tada:

**Pull request merged**
