### PR TITLE
staging-next 2024-08-23

### PR DESCRIPTION
**Pull request by vcunat**
##### Helpful links

- workflow docs: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#staging
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/332764
##### Mass breakages
_nothing notable so far_

### CODE REVIEW

**Comment by NickCao** [comment]
Not sure if it's a regression: meson cross compilations are failing with:
```
       > ERROR: Malformed value in machine file variable 'exe_wrapper': Expecting eof got id.
```
And quoting the variable fixes that.

**Comment by fabianhjr** [comment]
There is a broken build due to missing a wayland-scanner dependency: https://github.com/NixOS/nixpkgs/pull/337169

**Comment by vcunat** [comment]
- [ ] `python3Packages.dulwich`
  forwarded upstream: https://github.com/jelmer/dulwich/issues/1359

**Comment by vcunat** [comment]
Uh, the `wayland-scanner` fallout was quite large.

**Comment by flokli** [comment]
Yeah, sorry about that. There were quite some leaf packages missing. Luckily, the changes were very mechanical.

**Comment by vcunat** [comment]
I wasn't able to fix some cases.  IIRC it was those that were using `pkg-config` to detect `wayland-scanner`.

**Pull request merged**
