### PR TITLE
[WIP] openjdk : add version 6

### PR DESCRIPTION
**Pull request by FaustXVI**
###### Motivation for this change

A lot of companies are still using JDK6 and developers have to work with it.
Furthermore, some project are Java 6 retro-compatible (for example the language kotlin) and have to be tested under that specific JDK.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FaustXVI** [comment]
To build this version of jdk, we need the motif library (https://sourceforge.net/projects/motif/) at version 2.1 (not higher) but the only version in nixpkgs is 2.3.6.
I could add it within the openjdk package but I think it would be better in a separate package and so in a separate pull request.
What do you think ?

**Comment by NeQuissimus** [comment]
Note that we dropped JDK 6 in #18975 (#18878 / #18856) due to security concerns. I don't think we should add it back to the distribution.

**Comment by FaustXVI** [comment]
Oh sorry ! I searched for that but didn't find it… Sorry.
Well, I totally agree with you to be honest :/ (and, following that philosophy, think that jdk7 should be dropped too :/ )
I won't fight to have it back then :)
Since I need it to work on kotlin, do you know if using fetchFromGithub to a version where it still was there would work ?
Thanks

**Comment by NeQuissimus** [comment]
Kotlin should work just fine with JDK 8, you may just have to define your target JVM to be 1.6 in your build tool if you target a JRE 6 environment.

**Pull request closed without merging**
