### PR TITLE
joplin-desktop: 1.0.201 -> 1.0.216

### PR DESCRIPTION
**Pull request by CheariX**
###### Motivation for this change

New Release.

- Take care: WYSIWYG Editor is now default. Use *Code-View* Button on top bar.
- First start upgrades Database - impossible to go back.
  - If you simply want to test this version, create a Backup ("File -> Export -> JEX") before you upgrade

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by HugoReeves** [comment]
I'm not able to test the build currently but LGTM. Thanks

**Comment by ajs124** [comment]
>     * impossible to go back.

If you have it synchronized to a server, you can throw away your config and start over, with an older version.

**Review by HugoReeves — APPROVED** [review]

**Comment by CheariX** [comment]
> > ```
> > * impossible to go back.
> > ```
> 
> If you have it synchronized to a server, you can throw away your config and start over, with an older version.

Yes. It might be even easier to use Joplins Backup-and-Restore functions.
This remark is just for people who want to quickly verify this PR and then go back.

**Comment by HugoReeves** [comment]
@CheariX could you please remove `rafaelgg raquelgb` from the maintainers section. Both users have been inactive on GitHub, I pinged raquel in the last two PRs and received no response. By removing them, future PRs will be assigned a different reviewer. Pinging @raquelgb to check if they still aren't responding.

**Comment by HugoReeves** [comment]
Once that's done I'll try to contact someone with merge rights to get this merged.

**Comment by CheariX** [comment]
Thanks. I've just updated the branch.

**Review by HugoReeves — APPROVED** [review]

**Pull request merged**
