### PR TITLE
 nginxModules.echo: 0.62 -> 0.63,  nginxModules.lua: 0.10.22 -> 0.10.26

### PR DESCRIPTION
**Pull request by SuperSandro2000**
## Description of changes

While doing #277449 I've randomly checked those two modules, too if they were out of date and they where.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
No PR message, absolutely no diff in the commit messages, nothing. 

Sandro, I hate to say that, but it makes me very confused about whether the feedback that other committers provided to you is taken into consideration or not.

**Review by RaitoBezarius — CHANGES_REQUESTED** [review]
See past comment.

**Comment by zimbatm** [comment]
@RaitoBezarius What more do you need from the commit messages than the version changes? I see the version bump, the diff seems to clean some unneeded patches. I see similar commits all the time in nixpkgs.

**Comment by RaitoBezarius** [comment]
> @RaitoBezarius What more do you need from the commit messages than the version changes? I see the version bump, the diff seems to clean some unneeded patches. I see similar commits all the time in nixpkgs.

https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions
This is what we write in our conventions: link to release notes. This is missing. Usually, maintainers are expected to share release notes, show they read release notes, took a note of what could go wrong and inform people accordingly. If no release notes are available, diff links are acceptable. Without such links, this review becomes annoying because I have to go look for it myself.

People can do this all the time in nixpkgs, I expect something different from someone to whom we asked multiple times to change their ways regarding this.

Yes, everyone can infer what happened from the cleanup, but the purpose of commit messages is to make everything clear to others, to include maximum amount of information to make things easier for people bisecting, people reviewing, people re-reading.

By not writing this information, you force everyone to re-derive it all the time, and sometimes it is not possible to infer it anymore.

**Comment by zimbatm** [comment]
Ok, thanks for clarifying, I think I get it.

Your expectation of a maintainer is that they don't just bump versions, even if those are minor, but also look at the project's release notes. The idea is that this could catch errors that aren't necessarily caught at build time. If the link to the release notes is not attached to the commit, it puts more burden on the reviewer.

Regarding the PR, isn't the PR title sufficient in this case? It seems like the description would be redundant. I'm not personally convinced that even the big checklist is very useful, so I tend to skip all of this.

**Comment by RaitoBezarius** [comment]
> Ok, thanks for clarifying, I think I get it.
> 
> Your expectation of a maintainer is that they don't just bump versions, even if those are minor, but also look at the project's release notes. The idea is that this could catch errors that aren't necessarily caught at build time. If the link to the release notes is not attached to the commit, it puts more burden on the reviewer.

Well, active contributors to Nixpkgs are people I expect from a heightened level of quality. Newcomers can get it wrong and forget, etc.

I took code ownership of NGINX in a context where its maintainers were mostly absent, I invited Sandro to help me with this as he was also doing a lot of changes to NGINX, he declined. I find it problematic to be an active contributor & consumer of a subsystem of nixpkgs and not being able to step up for maintenanceship and pushing it to others, but it's fine, everyone has their choices and I won't insist.

Though, I am the code owner of NGINX, this is not a trivial program, a very front facing one, I take it seriously and scrutinize a lot of stuff and am comfortable reading the codebase of NGINX, etc.

I would like the person who declined to share the burden of maintenance with me and is very active in Nixpkgs to at least do more effort to respect my time. That's it, and I am sorry to be aggressive, but sometimes I think it's important to laid down how we feel so that everyone can understand my position here. 

If someone can step up and take over the burden for me and maintain the quality level, that'd be awesome!

> Regarding the PR, isn't the PR title sufficient in this case? It seems like the description would be redundant. I'm not personally convinced that even the big checklist is very useful, so I tend to skip all of this.

The PR title is not sufficient because it's not **Git** metadata, it's **GitHub** metadata, most of the time, in Nixpkgs, GitHub is unusable. We use **Git**. So we need all the relevant metadata in **Git**.

The checklist is a complicated one, I think the checkboxes should be edited and automated incrementally in response to events on the PR, I try to tick them, I try to modify them and adapt the template for my need, sometimes it's also too much mental overload for me. But I think it's very important for some class of changes, this one was a good example where the effort could have been made to tick tick at least simple stuff.

**Comment by zimbatm** [comment]
Thanks for unrolling your thoughts. It also makes sense to be able to set your own standards for the packages you maintain.

**Comment by SuperSandro2000** [comment]
> No PR message, absolutely no diff in the commit messages, nothing.
> 
> Sandro, I hate to say that, but it makes me very confused about whether the feedback that other committers provided to you is taken into consideration or not.

I thought I wrote at least some short description, not sure if GitHub ate that after a refresh or I my brain is hallucinating things like ChatGPT. Sorry, about that.

Breaking old habits is not always easy and sometimes things still slip by and I don't recognise that I missed some thing when I take a second look at the changes before opening the PR. I think I just need some more time to get used to it and a friendly reminder when I forget it again is certainly helpful.

I certainly do not want to waste your time or was that ever my intention. 

> [`master`/pkgs/README.md#commit-conventions](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md?rgh-link-date=2024-01-02T16%3A04%3A10Z#commit-conventions)
> This is what we write in our conventions: link to release notes. This is missing. Usually, maintainers are expected to share release notes, show they read release notes, took a note of what could go wrong and inform people accordingly. If no release notes are available, diff links are acceptable. Without such links, this review becomes annoying because I have to go look for it myself.

I would appreciate it, if that section could get expanded to include clear wording that links to release notes, news, docs, diffs, etc must be included. Right now you kinda need to know it, to know it.

---

I've slightly changed the package definition to allow nix-update to auto generated the diff links in the commit trailer. I hope that is enough and a pattern we can agree on to make updates to those packages easier.

**Review by RaitoBezarius — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Can we merge this?

**Comment by zimbatm** [comment]
Looks good. The maintainer approved, I don't see any blockers. I will let you do the honours:)

**Pull request merged**
