### PR TITLE
freeorion 0.4.6 -> 0.4.7

### PR DESCRIPTION
**Pull request by tex**
###### Motivation for this change
Update.

###### Things done

- [ x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bjornfor** [comment]
Don't forget to update the commit message too (add "freeorion:" prefix).

**Comment by tex** [comment]
How? Should I force push to overwrite this commit?

**Comment by bjornfor** [comment]
Yes. Amend the commit and force push.

**Comment by bjornfor** [comment]
? (You can "git commit --amend && git push --force" and the github PR will be updated.)

**Comment by tex** [comment]
I closed this pull request since I saw merge collisions and it turned out somebody already udpated freeorion to the same version as I with this pull request.

**Comment by bjornfor** [comment]
Oh :-)

**Pull request closed without merging**
