### PR TITLE
swift-format: init at 0.50400.0

### PR DESCRIPTION
**Pull request by rgnns**
###### Motivation for this change
`swift-format` is available from the `swift` package which is not currently available for mac machines. This derivation allows to install `swift-format` on mac configurations.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-burns** [comment]
Oh, no need to open a separate PR https://github.com/NixOS/nixpkgs/pull/141455 for the maintainers update. You can do both commits here. Please title them exactly as I showed though.

When making changes to your PR, please amend your commits and force push to this PR branch. (I know that's not very typical, but nixpkgs sees a huge number of changes so we have to keep the history as minimal as possible.)

**Comment by r-burns** [comment]
Hmm, I just realized we already package this as `swiftformat`. However I think it's currently broken on x86_64-linux, maybe you can merge your changes with that package and get it working?

**Comment by rgnns** [comment]
@r-burns this package is different from `swiftformat`. This one is a completely different one and is maintained by apple while the other one is maintained by nicklockwood. One is not a fork of the other one and work very differently. A valid improvement later would be to adapt `swift` package to build for darwin architectures too, that does does include `swift-format` but is only currently available for linux.

**Comment by r-burns** [comment]
Thanks, I didn't realize that at first. I wasn't able to get this to build on x86_64-darwin, does it work for you?

**Comment by r-burns** [comment]
Okay, no worries, an impure derivation is better than nothing if others will find it useful. I still wasn't able to build after removing the incompatible arguments so it looks like I won't be able to review further, but I will say that the changes look good as far as I can tell.

**Comment by n8henrie** [comment]
This should also be superseded by https://github.com/NixOS/nixpkgs/pull/230372

cc @wegank

**Pull request closed without merging**
