### PR TITLE
python3Packages.discordpy: 1.7.0 -> 1.7.1

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 1.7.1

Change log: https://github.com/Rapptz/discord.py/blob/master/docs/whats_new.rst#v171

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 119113` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.discordpy</li>
    <li>python39Packages.discordpy</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 119113` at 1b6d76ad run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.discordpy</li>
    <li>python39Packages.discordpy</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern 'websockets>=6.0,!=7.0,!=8.0,!=8.0.1,<9.0' doesn't match anything in file 'requirements.txt'
Near pkgs/development/python-modules/discordpy/default.nix:47:0:
```
   |
47 |     description = "A python wrapper for the Discord API";
   | ^
```
</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
@fabaff please fix the substituteInPlace

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 119113` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.discordpy</li>
    <li>python39Packages.discordpy</li>
  </ul>
</details>

**Comment by fabaff** [comment]
> @fabaff please fix the substituteInPlace

Updated. `websockets` was removed in 1.4.0.

**Pull request merged**
