### PR TITLE
nodePackages.@nestjs/cli: init at 7.2.0

### PR DESCRIPTION
**Pull request by leungbk**
###### Motivation for this change

Add nestjs/cli, a NPM package

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
Please rework your PR. It now has a merge conflict after merging https://github.com/NixOS/nixpkgs/pull/89184

**Comment by leungbk** [comment]
@prusnak OK, I resolved the merge conflict.

**Review by prusnak — APPROVED** [review]

**Comment by leungbk** [comment]
@prusnak I've resolved the merge conflict again. If there are any obstacles to this getting merged, please let me know.

**Comment by leungbk** [comment]
@prusnak

**Comment by leungbk** [comment]
@prusnak

**Pull request merged**
