### PR TITLE
darwin.stdenv: allow `patchShebangs` during the bootstrap

### PR DESCRIPTION
**Pull request by reckenrode**
###### Description of changes

This fixes pyicu (and any other package that uses `icu-config` instead of the CMake or some other module to get the build flags).

What happened here is the bootstrap disables `patchShebangs` to avoid propagating the bootstrap tools to the final stdenv (due to `sh` and `bash` being on the `PATH` from the bootstrap tools). Because of that, the `#!/bin/sh` line in `icu-config` was not updated, causing it to invoke the system bash on Darwin. While that is undesirable in its own right, when the system bash is invoked as `sh`, `echo -n` will print `-n`, resulting in the breakage see in https://github.com/NixOS/nixpkgs/pull/241951#issuecomment-1627604354.

The fix is to build bash earlier in the bootstrap while making sure it is picked up over the one in the bootstrap tools. That allows `patchShebangs` to be enabled during the bootstrap. Any package with scripts that is included in the final stdenv should now have its scripts’ shebang lines properly patched.

I tested that pyicu builds, and this is the contents of `icu-config` now:

```
$ nix build .#icu^dev
$ head -n 1 ./result-dev/bin/icu-config
#!/nix/store/znf9b5c859lgz348r200pgi0y9855y1l-bash-5.2-p15/bin/sh
```

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by reckenrode** [comment]
Creating this as a draft PR while x86_64-darwin builds. I feel pretty confident that it will, but I don’t want to waste time on Hydra if it doesn’t. Once the stdenv is built, I’ll set the PR to ready.

**Comment by reckenrode** [comment]
Setting this to review. I had to build link bash against the system CoreFoundation to break a dependency cycle on x86_64-darwin.

I was able to successfully build a stdenv on both x86_64-darwin and aarch64-darwin, and I was able to build pyicu on aarch64-darwin. I feel pretty confident pyicu will build on x86_64-darwin, but I don’t want to delay longer than necessary.

**Review by tjni — APPROVED** [review]
LGTM. These cycles are crazy!

**Comment by vcunat** [comment]
The [failure](https://hydra.nixos.org/build/226934217/nixlog/2/tail) in `texlive.bin.core-big` is fixed by this as well?  The failure does happen soon after running icu-config, but the error messages are weird.  Could this be cheap for you to run, as you have stuff in cache?

**Comment by vcunat** [comment]
To be clear, Hydra [showed](https://hydra.nixos.org/build/226733706/nixlog/2/tail) the failure the same on both `*-darwin`, so again it should suffice to verify either for now.

**Comment by vcunat** [comment]
Ah, I now caught up the confirmation for those questions in another thread: https://github.com/NixOS/nixpkgs/pull/242202#issuecomment-1627897887

**Comment by vcunat** [comment]
OK, the `icu` issue seems quite serious, so I'll be optimistic and merge fast.  (without reviewing myself; I'm mostly avoiding darwin)

**Comment by reckenrode** [comment]
@vcunat Both texlive and R build for me with this commit.

**Pull request merged**
