### PR TITLE
ddnet: 15.5.4 -> 15.6.2

### PR DESCRIPTION
**Pull request by ElXreno**
###### Motivation for this change
Upgrades ddnet from 15.5.4 to 15.6.1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ElXreno** [comment]
I apologize for the vscode commit. I forgot to switch to my previous branch.

**Comment by endgame** [comment]
I am getting a build error, could you please double-check the hash?:
```
$ nix run 'github:ElXreno/nixpkgs/package-ddnet-15.6#ddnet'
error: hash mismatch in fixed-output derivation '/nix/store/sx8xxsk9vhrh2xs6qf4vz610avas347h-source.drv':
         specified: sha256-81xW82LPeqb+O56NC0q0ThkiRfzc/X9xT52b9XxWqV0=
            got:    sha256-5nAdmPUAvmFVcdupggNPfct1dVRKy7hJDJ8jQys/VNM=
error: 1 dependencies of derivation '/nix/store/3zs9f26zfc4m8f0gq51jwkil73v3kpa2-ddnet-15.6.drv' failed to build
```

**Comment by ElXreno** [comment]
@endgame It seems that the hash was wrong because I used `nix-prefetch-github` without the `--no-fetch-submodules` parameter. Thanks for the check!

**Review by legendofmiracles — APPROVED** [review]
Builds and runs on my machine.

**Review by SirSeruju — COMMENTED** [review]
Everything works as it should on my machine.

**Review by SirSeruju — APPROVED** [review]

**Review by SirSeruju — APPROVED** [review]

**Review by SirSeruju — APPROVED** [review]

**Review by SirSeruju — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
@SirSeruju you don't need to re-approve if ofborg takes a bit to eval and requests it after you already approved the latest push.

**Pull request merged**
