### PR TITLE
linuxPackages.nvidia_x11: 515.65.01 -> 515.76

### PR DESCRIPTION
**Pull request by ThoFrank**
(cherry picked from commit 60b61935ad6be949e4272429653299e1529b2e18)

###### Description of changes

manual backport of #192185 to 22.05 because automatic cherry pick failed

###### Things done

fixed up cherry pick. It builds. I didn't manage to add a boot entry to properly test it.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ThoFrank** [comment]
nixpkgs review said these packages failed to build:
linuxKernel.packages.hardkernel_4_14.nvidia_x11 linuxKernel.packages.linux_testing_bcachefs.nvidia_x11 linuxPackages_hardkernel_latest.nvidia_x11 linuxPackages_testing_bcachefs.nvidia_x11

**Comment by Schweber** [comment]
@ThoFrank can you please expedite the merge somehow before Linux 5.19 reaches EOL?

I have to use the nvidia driver and am currently stuck on 5.19.

**Comment by ThoFrank** [comment]
@Schweber Well I don't know how to.
Maybe @NickCao or @superherointj could help us here.

**Comment by NickCao** [comment]
So what's the problem needing help? This looks fine apart from the broken indentation.

**Comment by Binary-Eater** [comment]
@ThoFrank as a heads up, backports for version upgrades just to support `linuxPackages_latest` typically do not get accepted from what I have seen.

Example: #120655

I guess since it's a minor version update, might have a better chance with this one.

I think a general thing for developers who need to work with the latest kernel is to make use of the unstable channel to pull the latest Nvidia drivers.

```sh
# nix-channel --add https://nixos.org/channels/nixos-unstable nixos-unstable
```

```nix
let
  unstable = import <nixos-unstable> {
    config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
      "nvidia-x11"
      "nvidia-settings"
    ];
  };
in
{
  ...
  # Specify kernel package used.
  boot.kernelPackages = unstable.linuxPackages_latest; # Latest kernel
}
```

Just a personal tip.

**Comment by Binary-Eater** [comment]
For the sake of completeness of the example I posted, you should do a `nix-channel --update nixos-unstable` when adding a new channel like `nixos-unstable` since `--add` just adds the channel url to a channel list file.

**Comment by Schweber** [comment]
@Binary-Eater Thank you for the instructions. I will have to fall back on them when Linux 5.19 reaches EOL.

Using unstable for the whole system gave me too much trouble so i will apply unstable selectively.

**Comment by Binary-Eater** [comment]
It would be nice to develop a better practice for what NVIDIA driver versions are permitted to be backported for a NixOS release. In this case since its a minor version bump, I think the conversation is simple. There could be cases in the future where we see kernel API/header support only added in a new major version (and if so and that version is provided in a release's channel, I think the backport should still be made even if it's a major version bump, or at least provided in some other derivation similar to beta).

**Comment by TLATER** [comment]
> @ThoFrank as a heads up, backports for version upgrades just to support `linuxPackages_latest` typically do not get accepted from what I have seen.
> 
> Example: #120655

They typically are for the nvidia drivers, see e.g. #176083. At the very least @jonringer will recommend a backport every time this happens (roughly every 2 months IME, we've had a good run this time), and the kernel compatibility patches for older versions are rejected.

A proper policy on the topic would make sense, but maintainer's discretion has served well so far.

**Comment by ThoFrank** [comment]
Thanks for all your feedback! I personally don't need the newest kernel. And 22.11 is right around the corner, so I think rejecting this pr is fine.
I updated the formatting in case anyone wants to merge it though.

**Comment by Schweber** [comment]
@NickCao @superherointj Sorry to bother you again, but is it normal that ofborg has still got 1 pending check after 6 days?

**Comment by NickCao** [comment]
Might be an ofborg bug, but as nvidia-x11 is unfree, it won't be built by ofborg anyway, we can safely ignore that.

**Comment by superherointj** [comment]
I no longer can merge PRs. Still, if you want your PRs to be merged (more quickly), I suggest you to always squash commits. (So you have one less objection from whoever will be reviewing/committing this.)

**Comment by Schweber** [comment]
> I no longer can merge PRs. Still, if you want your PRs to be merged (more quickly), I suggest you to always squash commits. (So you have one less objection from whoever will be reviewing/committing this.)

@ThoFrank could you please do that? Linux 5.19 has now reached EOL...

**Review by jraygauthier — APPROVED** [review]
Just tested this patch on top of latest 20.05 stable with linux kernel v6.
Works perfectly fine with my Lenovo Thinkpad p17 gen2.

**Comment by TLATER** [comment]
@jonringer is mentioned as the maintainer, would be nice to get this over the line sometime.

**Comment by Kiskae** [comment]
As per #202417 the `515.86.01` driver is available on unstable.

**Comment by Binary-Eater** [comment]
This PR should probably be closed now that 22.05 is deprecated.

**Pull request closed without merging**
