### PR TITLE
Add ChromiumOS kernels

### PR DESCRIPTION
**Pull request by zohl**
This set of commits provides ChromiumOS kernels, that have better support for chromebooks hardware than the mainline kernel.
The kernels were tested on chromebook pixel 2015 (samus), so additional efforts may be required in order to make it work on another devices.

The pull request contains:
- kernel 3.14 (full hardware support)
- kernel 3.18 (full hardware support except audio)
- firmware blob for Realtek rt5677 device

To enable sound there are required additional steps that are described in [2].

The kernels are taken from chromiumos project's repository [1], the firmware is taken from Raphael's repository [2].
Many thanks to @abbradar for assistance and sharing knowledge.

[1] https://chromium.googlesource.com/
[2] https://github.com/raphael/linux-samus

### CODE REVIEW

**Comment by vcunat** [comment]
Are there multiple chromebook+nixos users? I wonder whether to build all those chromebook-specific `kernelPackages` on Hydra.

**Comment by puffnfresh** [comment]
I run NixOS on a Acer CB3-111 - this kernel is probably a good idea for me to use!

Thanks :fireworks:

**Comment by abbradar** [comment]
I suppose we can at least disable `3.18` builds on Hydra, as it doesn't support all the hardware. @zohl, what do you think?

**Comment by zohl** [comment]
Sure, `3.14` should support much wider range of devices, so there is no need to build `3.18` automatically.

**Comment by colemickens** [comment]
Do you have any intention of including raphael's patches for 4.1, 4.2, or 4.3?

**Comment by zohl** [comment]
Yes, I can add nix-expressions for those kernels too.

Though I had some issues with Raphael's version: I couldn't get working the sound and the touchscreen stopped working after suspend.
(This was the reason why I switched to the ChromiumOS kernel.)

**Comment by zohl** [comment]
@colemickens, I added a nix-expression for the latest Raphael's kernel (4.4) but haven't opened a pull request yet.

The problem is that I was unable to boot successfully: part of my system resides on external usb drive and initrd cannot access it. I suspect there are missing modules as the drive is recognized in the emergency terminal. The same story for 4.3 kernel which worked well when my system was completely on internal drive.

You can check my repository's branch (https://github.com/zohl/nixpkgs/tree/linux-samus) for the nix-expression and test it yourself. If it works well in your case, I'll open a PR and try to fix my initrd.

**Comment by zohl** [comment]
So, back to the main topic, as we decided the 3.18 kernel won't be build on Hydra. What about the rest one?
How many people here interested in automated builds for 3.14 kernel?

**Comment by abbradar** [comment]
Whom can we ping for a review of kernel-related things? This looks fine to me now, maybe sans the open question of whether to build 3.14 on Hydra.

There are at least three people interested in it enough to express it here, so there are certainly some interest, but I don't know how hard would another kernel version hit Hydra. As a data point, Raspberry Pi kernel is now not built there.

**Comment by vcunat** [comment]
One kernel version for two architectures + `kernelPackages_*` is probably not a significant hit for Hydra.

**Comment by abbradar** [comment]
Well, then it looks good to me, and nobody of cc'ed by @mention-bot expressed interest -- I'll merge this in a few days if it stays the same.

**Comment by zohl** [comment]
Tried to build the latest Raphael's version of kernel, still no success. Though I managed to deal with the missing drive error (just mounted it after initrd did the job), the system is less stable than the one based on ChromiumOS kernel.

Playing with kernel config I get different hardware working, so I'll keep on trying to make it work.
As for now, I think 3.14 kernel is better choice.

**Comment by abbradar** [comment]
OK, let's merge. Thank you for your work and congratulations with your merged first pull request ~_^.

**Comment by colemickens** [comment]
@zohl Can you advise on how you got the kernel to even build? I pulled your definition and updated it to the latest release at the time. I got these build errors in the sound/soc area: https://github.com/raphael/linux-samus/issues/72

**Comment by zohl** [comment]
Sorry, I'm afraid I didn't understand your problem. There is no mention of any sound/soc-related configs under the provided link.
First of all which of two kernels are you trying to build (ChromeOS, Raphael's one)? In the latter case there are indeed errors in sound/soc area, which can be eliminated by "SND_SOC n" config line (see [1]).

[1] https://github.com/NixOS/nixpkgs/pull/12576/files

**Comment by colemickens** [comment]
Yes, I forgot that I had removed that line to get the sound working. It should build but doesn't. Anyway, I'm going to dig into it and use 3.14 in the meantime. Thanks for adding them.

**Pull request merged**
