### PR TITLE
clamav: 1.3.1 -> 1.4.0

### LINKED ISSUE #334852: Build failure: clamav
### Steps To Reproduce

1. build *clamav*

### Build log

```
error: builder for '/nix/store/z8mbbp1n6axb1rw15i20niiskh0jiq6k-clamav-1.3.1.drv' failed with exit code 2;
       last 25 log lines:
       >
       > [DEBUG]: stderr:
       >
       > =========================== short test summary info ============================
       > FAILED clamscan/assorted_test.py::TC::test_pe_cert_trust - AssertionError: as...
       > ======================== 1 failed, 52 passed in 14.48s =========================
       >
       > 3/5 Test #4: clamd ............................   Passed   19.33 sec
       > 4/5 Test #1: libclamav ........................   Passed   23.96 sec
       > 5/5 Test #2: libclamav_rust ...................   Passed   28.29 sec
       >
       > 80% tests passed, 1 tests failed out of 5
       >
       > Total Test time (real) =  28.31 sec
       >
       > The following tests FAILED:
       >        3 - clamscan (Failed)
       > Errors while running CTest
       > make[3]: *** [CMakeFiles/check.dir/build.make:70: CMakeFiles/check] Error 8
       > make[3]: Leaving directory '/build/clamav-1.3.1/build'
       > make[2]: *** [CMakeFiles/Makefile2:1348: CMakeFiles/check.dir/all] Error 2
       > make[2]: Leaving directory '/build/clamav-1.3.1/build'
       > make[1]: *** [CMakeFiles/Makefile2:1355: CMakeFiles/check.dir/rule] Error 2
       > make[1]: Leaving directory '/build/clamav-1.3.1/build'
       > make: *** [Makefile:563: check] Error 2
       For full logs, run 'nix log /nix/store/z8mbbp1n6axb1rw15i20niiskh0jiq6k-clamav-1.3.1.drv'.
```

### Additional context

Happened during last system update.

### Notify maintainers
@robberer @qknight @globin

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.44, NixOS, 24.11 (Vicuna), 24.11.20240811.a58bc8a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.0`
 - nixpkgs: `/nix/store/h60m1fwahjd2mv6gsg77ji3vb4gpj4dk-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by martiege**
The previous version, 1.3.1, has recently stopped building due to some certifications used in the tests are out of date.

Fixes https://github.com/NixOS/nixpkgs/issues/334852

## Description of changes
Update which version is fetched and the corresponding hash.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by martiege** [comment]
Pinging maintainers as well @robberer @qknight @globin

**Comment by eclairevoyant** [comment]
Please update commit message to `clamav: 1.3.1 -> 1.4.0`

**Comment by AndersonTorres** [comment]
Apparently the three are silently retired.

**Review by cafkafk — APPROVED** [review]

**Review by eclairevoyant — APPROVED** [review]
I'll merge if CI is happy

**Comment by cafkafk** [comment]
> I'll merge if CI is happy

I'm not sure those darwin passthroughs are ever gonna finish...

**Pull request merged**
