### PR TITLE
stdenv: remove lib

### PR DESCRIPTION
**Pull request by siraben**
###### Motivation for this change
Completion of #108938

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 125494` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 125494` [1](https://github.com/Mic92/nixpkgs-review)

**Review by teto — APPROVED** [review]

**Comment by Ericson2314** [comment]
Congrats! I hope we can do lots more of this sort of thing :).

**Review by Ericson2314 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Here goes nothing!

**Pull request merged**
