### PR TITLE
treewide: remove redundant rec

### PR DESCRIPTION
**Pull request by volth**
remove redundant `rec`

### CODE REVIEW

**Comment by volth** [comment]
@GrahamcOfBorg eval

**Comment by volth** [comment]
@Mic92 the script is easy to rerun against the latest state of `staging`, so probably no need to solve merge conflicts manually

**Comment by Mic92** [comment]
Do you know, why this triggers some rebuilds?

**Comment by volth** [comment]
> Do you know, why this triggers some rebuilds?

Mostly ruby modules with `gemdir = ./.;` and python modules with `src = ./.;`
ofborg report is here: https://gist.github.com/GrahamcOfBorg/e7efc582e944b04b20eb583bd766ed65

**Comment by volth** [comment]
rebased

**Pull request merged**
