### PR TITLE
libbsd: Apply Darwin specific patch only on Darwin

### PR DESCRIPTION
**Pull request by afh**
###### Description of changes

Remotely elated #220891

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wegank** [comment]
It is in principle less preferable to make a patch conditional. Does the patch break the builds on Linux?

**Comment by afh** [comment]
I see @wegank. Unless other precautions are taken (see https://github.com/NixOS/nixpkgs/pull/220891#pullrequestreview-1336235713) applying the patch can break libbsd on other platforms. Open to bounce around other ideas how to approach this best.

**Comment by wegank** [comment]
cc @trofi

**Comment by trofi** [comment]
Yeah, conditional patches are very hard to maintain: attempt to apply a common patch will have a chance to fail to apply on darwin only.

I would suggest fixing the patch to make things work. The patch is structured in a way that it should be reasonably portable. It should also be useful for experimental *bsd targets, not just darwin.

I did not quite catch how https://github.com/NixOS/nixpkgs/pull/220891 relates to this PR. Does this revert fix something?

**Pull request closed without merging**
