### PR TITLE
Fix evaluation of release-20.03-aarch64 jobset

### PR DESCRIPTION
**Pull request by bennofs**
###### Motivation for this change
The `nixos-20.03-aarch64` jobset on hydra currently [fails to eval](https://hydra.nixos.org/jobset/nixos/release-20.03-aarch64#tabs-errors). This is because the constituents of the tested job are hardcoded to refer to the `x86_64-linux` tests, which aren't available in that jobset.

###### Proposed solution
This PR uses helper functions to only generate `tested` constituents for the available platforms. I also checked which tests are supported on aarch64, and limited everything else to `x86_64-linux`.

Variant for master: https://github.com/bennofs/nixpkgs/tree/fix-nixos-aarch64-eval-master

###### Things done

1. verify that `tested.constituents` did stay the same before and after the change: diff of the output from `nix-instantiate --eval --strict --json -A tested.constituents nixos/release-combined.nix | jq` before and after the change:
```diff
-  "nixos.iso_minimal.aarch64-linux",
-  "nixos.iso_minimal.i686-linux",
   "nixos.iso_minimal.x86_64-linux",
+  "nixos.iso_minimal.i686-linux",
+  "nixos.iso_minimal.aarch64-linux",
```

2. verify that all constituents of the `tested` job can be instantiated for `aarch64`:
 
```
#!/usr/bin/env fish
nix-instantiate --eval --strict --json -A tested.constituents --arg 'limitedSupportedSystems' '[]' --arg 'supportedSystems' '["aarch64-linux"]' nixos/release-combined.nix |
  jq -r '.[]' |
  while read attr;
      echo + instantiate $attr; 
      nix-instantiate -A $attr --arg 'limitedSupportedSystems' '[]' --arg 'supportedSystems' '["aarch64-linux"]' nixos/release-combined.nix;
  end
```

### CODE REVIEW

**Review by samueldr — CHANGES_REQUESTED** [review]
(Recording the change discussed on IRC here)

This change should first be made on `master`, then backported (though the backport will not be a trivial cherry-pick).

**Comment by bennofs** [comment]
There is a version of this PR for master on https://github.com/bennofs/nixpkgs/tree/fix-nixos-aarch64-eval-master. Note however that the situation for master is a little bit different, as we don't have split jobsets for `x86_64-linux` and `aarch64-linux` there. Thus, if this change is applied to master, `aarch64-linux` tests will become part of the `tested` job on `trunk-combined`.

**Comment by bennofs** [comment]
Is it OK to keep this PR for discussion? Or should I create a new one against master?

**Comment by worldofpeace** [comment]
> There is a version of this PR for master on https://github.com/bennofs/nixpkgs/tree/fix-nixos-aarch64-eval-master. Note however that the situation for master is a little bit different, as we don't have split jobsets for `x86_64-linux` and `aarch64-linux` there. Thus, if this change is applied to master, `aarch64-linux` tests will become part of the `tested` job on `trunk-combined`.

I guess that means we'd need two PRs, with this one merged just for 20.03.

**Comment by bennofs** [comment]
@worldofpeace ok, I created a second PR for master.

**Review by worldofpeace — APPROVED** [review]
I believe this is fine, though I'm not sure how I feel about the function names (can't suggest better right now I'm afraid).

**Comment by andir** [comment]
I did some prior work on a related topic. When the hydra eval changed we had to apply the conversion to strings on release-19.09 as well:
https://github.com/NixOS/nixpkgs/blob/release-19.09/nixos/release-combined.nix#L47-L149

I tried to be as close to the "old" style definition as possible to make it more familiar and reduce conflicts if we would be cherry-picking changes.

No real opinion just felt like that might be a good piece of information.

**Review by samueldr — APPROVED** [review]

**Review by worldofpeace — APPROVED** [review]

**Pull request merged**
