### PR TITLE
grafana: 7.0.1 -> 7.0.2

### PR DESCRIPTION
**Pull request by Frostman**
###### Motivation for this change

https://github.com/grafana/grafana/releases/tag/v7.0.2

Important security fix release, details in https://grafana.com/blog/2020/06/03/grafana-6.7.4-and-7.0.2-released-with-important-security-fix/

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/89419)

### CODE REVIEW

**Comment by WilliButz** [comment]
@GrahamcOfBorg test grafana

**Comment by Frostman** [comment]
@WilliButz I've decided to not backport 7.x grafana, but use 6.7.4, let me know if you think 7.x backport is preferred. #89422

**Comment by WilliButz** [comment]
@Frostman thanks for mentioning it, I thought that we had 7.x on stable for some reason :)

**Comment by WilliButz** [comment]
seems like 7.0.3 just got tagged as well

**Pull request merged**
