### PR TITLE
update duckdb to 0.9.0

### PR DESCRIPTION
**Pull request by ghost**
## Description of changes

update duckdb to version [0.9.0](https://github.com/duckdb/duckdb/releases/tag/v0.9.0)

### duckdb
- update cmake flags to use `${src}/.github/config/in_tree_extensions.cmake` to enable the built in extensions.
- exclude additional unittests found to fail on macosx or that make network requests
- add patch needed for python module (probably should be in the python module default.nix but not sure how to add to the patches list when patches inherited from duckdb). 

### duckdb python module
- patch setup.py to disable autoloading and autoinstalling of extensions. this feature seems to have bugs which are exposed by the duckdb-engine module. eg: tries to download and install builtin json extension. filed: https://github.com/duckdb/duckdb/issues/9174
- add httpfs extension to the builtins.

### duckdb-engine python module
- bump version to most recent 0.9.2
- add patch so disabled tests actually get disabled.
- disable motherduck test as it requires network.
- disable test_rowcount as duckdb.default_connection.rowcount is now defined.

### ibis-framework python module
- disabled a csv test as duckdb does not respect sample_size=2 (it samples all 3 lines)
- disabled the udf tests which are now failing for duckdb with: "This function can not be called with an active transaction!"

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by robert-manchester** [comment]
> ### duckdb
> 
>     * use `deepClone = true;` so the build can get the git hash so the version is properly reported. `leaveDotGit = true;` and a patch almost works but the hash returned from `git log -1 --format=%h` is a few characters to short.

i can change this to use `--format=%H` to get the full hash and then with a minor patch `leaveDotGit = true;` will work if `deepClone` is undesirable.

**Comment by robert-manchester** [comment]
had thought ibis-framework built and tested successfully but now appears to be failing in 5 udf tests with `This function can not be called with an active transaction!`.

**Comment by cpcloud** [comment]
It should be fine to disable the ibis tests.

**Comment by cpcloud** [comment]
@robert-manchester Should we close this PR? https://github.com/NixOS/nixpkgs/pull/257452 is I think a bit further along.

**Comment by robert-manchester** [comment]
> @robert-manchester Should we close this PR? #257452 is I think a bit further along.

could merge the two -- #257452 is missing the changes to the duckdb cli python bindings and the duckdb_engine that are in this change. most are minor but the build changed a bit for duckdb and #257452 is not getting any extensions built in except for parquet and jemalloc, despite the cmake flags.

**Comment by robert-manchester** [comment]
`nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"` passes -- not sure why i am not seeing the same failure in the lisp stuff as the other PR
20 packages built:
duckdb mycli mycli.dist python310Packages.duckdb python310Packages.duckdb-engine python310Packages.duckdb-engine.dist python310Packages.duckdb.dist python310Packages.ibis-framework python310Packages.ibis-framework.dist python310Packages.sqlglot python310Packages.sqlglot.dist python311Packages.duckdb python311Packages.duckdb-engine python311Packages.duckdb-engine.dist python311Packages.duckdb.dist python311Packages.ibis-framework python311Packages.ibis-framework.dist python311Packages.sqlglot python311Packages.sqlglot.dist sbclPackages.duckdb

**Comment by robert-manchester** [comment]
these changes will get incorporated into the other PR so closing.

**Pull request closed without merging**
