### PR TITLE
Babeltrace updates and Python modules

### PR DESCRIPTION
**Pull request by hacker1024**
## Description of changes

This PR adds the [Babeltrace 2](https://github.com/efficios/babeltrace) package along with its Python bindings. It is ["completely independent from Babeltrace 1"](https://github.com/efficios/babeltrace/releases/tag/v2.0.0).

It also updates Babeltrace 1 to [1.5.11](https://github.com/efficios/babeltrace/releases/tag/v1.5.11) (which mainly improves compatibility with newer Python and dependency versions) and adds a derivation for its Python bindings as well.

Cross-compilation (targeting aarch64-linux on x86_64-linux) has been tested.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

@bjornfor

### CODE REVIEW

**Comment by hacker1024** [comment]
Hmm, I'm not sure how this would fit into the `by-name` structure as it shares code with the 1.x derivation...

**Comment by infinisil** [comment]
There's some options:
- Don't use `pkgs/by-name` and create something like `pkgs.babeltraceVersions` instead
- Create a babeltrace builder function like `pkgs.babeltraceFor`, then use `pkgs/by-name` for the individual versions, calling that function within
- Use `.override` on one version to define the other, then both can be in `pkgs/by-name`
- Use something like `inherit (callPackages ...) babeltrace babeltrace 2`.

What all of these have in common is that the different versions are somehow linked together. Thete might be other ways of doing it though :)

**Comment by infinisil** [comment]
Ahh yeah sorry, I forgot to mention that the CI check has a false positive! It will be fixed once https://github.com/NixOS/nixpkgs/pull/285089 is used in CI, but for now you can just ignore the failing CI. It looks fine as is!

**Comment by infinisil** [comment]
The PR to fix the `pkgs/by-name` check is now merged and used in CI, so it won't fail anymore the next time you push :)

**Comment by hacker1024** [comment]
@bjornfor I have added the comment from #285390 and wrapped commit messages to 72 lines once more.

**Comment by bjornfor** [comment]
Result of `nixpkgs-review pr 285681` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_19.perf</li>
    <li>linuxKernel.packages.linux_4_19.perf.debug</li>
    <li>linuxKernel.packages.linux_4_19_hardened.perf</li>
    <li>linuxKernel.packages.linux_4_19_hardened.perf.debug</li>
    <li>linuxPackages_4_19_hardened.perf</li>
    <li>linuxPackages_4_19_hardened.perf.debug</li>
  </ul>
</details>
<details>
  <summary>18 packages failed to build:</summary>
  <ul>
    <li>ceph (ceph-dev)</li>
    <li>ceph-client</li>
    <li>ceph-csi</li>
    <li>ceph.dev (ceph-dev.dev)</li>
    <li>ceph.doc (ceph-dev.doc)</li>
    <li>libceph (ceph.lib ,libceph.dev ,libceph.doc ,libceph.lib ,libceph.man)</li>
    <li>ceph.man (ceph-dev.man)</li>
    <li>python312Packages.babeltrace</li>
    <li>python312Packages.babeltrace2</li>
    <li>qemu_full</li>
    <li>qemu_full.debug</li>
    <li>qemu_full.ga</li>
    <li>rocmPackages.mivisionx (rocmPackages.mivisionx-hip ,rocmPackages_5.mivisionx ,rocmPackages_5.mivisionx-hip)</li>
    <li>rocmPackages.mivisionx-cpu (rocmPackages_5.mivisionx-cpu)</li>
    <li>rocmPackages.mivisionx-opencl (rocmPackages_5.mivisionx-opencl)</li>
    <li>sambaFull (samba4Full)</li>
    <li>sambaFull.dev (samba4Full.dev)</li>
    <li>sambaFull.man (samba4Full.man)</li>
  </ul>
</details>
<details>
  <summary>41 packages built:</summary>
  <ul>
    <li>babeltrace</li>
    <li>babeltrace2</li>
    <li>cargo-flamegraph</li>
    <li>linuxPackages_5_10_hardened.perf (linuxKernel.packages.linux_5_10.perf)</li>
    <li>linuxPackages_5_10_hardened.perf.debug (linuxKernel.packages.linux_5_10.perf.debug)</li>
    <li>linuxPackages_5_15_hardened.perf (linuxKernel.packages.linux_5_15.perf)</li>
    <li>linuxPackages_5_15_hardened.perf.debug (linuxKernel.packages.linux_5_15.perf.debug)</li>
    <li>linuxKernel.packages.linux_5_4.perf</li>
    <li>linuxKernel.packages.linux_5_4.perf.debug</li>
    <li>linuxPackages_5_4_hardened.perf (linuxKernel.packages.linux_5_4_hardened.perf)</li>
    <li>linuxPackages_5_4_hardened.perf.debug (linuxKernel.packages.linux_5_4_hardened.perf.debug)</li>
    <li>linuxPackages.perf (linuxKernel.packages.linux_6_1.perf)</li>
    <li>linuxPackages.perf.debug (linuxKernel.packages.linux_6_1.perf.debug)</li>
    <li>linuxPackages_hardened.perf (linuxPackages_6_1_hardened.perf)</li>
    <li>linuxPackages_hardened.perf.debug (linuxPackages_6_1_hardened.perf.debug)</li>
    <li>linuxPackages_6_5_hardened.perf (linuxKernel.packages.linux_6_5.perf)</li>
    <li>linuxPackages_6_5_hardened.perf.debug (linuxKernel.packages.linux_6_5.perf.debug)</li>
    <li>linuxKernel.packages.linux_6_6.perf</li>
    <li>linuxKernel.packages.linux_6_6.perf.debug</li>
    <li>linuxPackages_6_6_hardened.perf (linuxKernel.packages.linux_6_6_hardened.perf)</li>
    <li>linuxPackages_6_6_hardened.perf.debug (linuxKernel.packages.linux_6_6_hardened.perf.debug)</li>
    <li>linuxPackages_latest.perf (linuxKernel.packages.linux_6_7.perf)</li>
    <li>linuxPackages_latest.perf.debug (linuxKernel.packages.linux_6_7.perf.debug)</li>
    <li>linuxPackages_6_7_hardened.perf (linuxKernel.packages.linux_6_7_hardened.perf)</li>
    <li>linuxPackages_6_7_hardened.perf.debug (linuxKernel.packages.linux_6_7_hardened.perf.debug)</li>
    <li>linuxPackages_latest-libre.perf (linuxKernel.packages.linux_latest_libre.perf)</li>
    <li>linuxPackages_latest-libre.perf.debug (linuxKernel.packages.linux_latest_libre.perf.debug)</li>
    <li>linuxPackages-libre.perf (linuxKernel.packages.linux_libre.perf)</li>
    <li>linuxPackages-libre.perf.debug (linuxKernel.packages.linux_libre.perf.debug)</li>
    <li>linuxPackages_lqx.perf (linuxKernel.packages.linux_lqx.perf)</li>
    <li>linuxPackages_lqx.perf.debug (linuxKernel.packages.linux_lqx.perf.debug)</li>
    <li>linuxPackages_xanmod.perf (linuxKernel.packages.linux_xanmod.perf)</li>
    <li>linuxPackages_xanmod.perf.debug (linuxKernel.packages.linux_xanmod.perf.debug)</li>
    <li>linuxPackages_xanmod_latest.perf (linuxKernel.packages.linux_xanmod_latest.perf ,linuxPackages_xanmod_stable.perf)</li>
    <li>linuxPackages_xanmod_latest.perf.debug (linuxKernel.packages.linux_xanmod_latest.perf.debug ,linuxPackages_xanmod_stable.perf.debug)</li>
    <li>linuxPackages_zen.perf (linuxKernel.packages.linux_zen.perf)</li>
    <li>linuxPackages_zen.perf.debug (linuxKernel.packages.linux_zen.perf.debug)</li>
    <li>lttv</li>
    <li>python311Packages.babeltrace</li>
    <li>python311Packages.babeltrace2</li>
    <li>qtcreator</li>
  </ul>
</details>

**Comment by wentasah** [comment]
I fixed build failures with Python 3.12. The needed changes are in [my branch](https://github.com/NixOS/nixpkgs/compare/master...wentasah:nixpkgs:package/python-babeltrace), which is rebased to `nixos-unstable`. @hacker1024 feel free to cherry pick the last three patches and put them here (or let me know and I'll submit a new PR from my branch).

It seems that the failures of `ceph` and `qemu` are not caused by this PR. I may have time to investigate the other failures reported by nixpkgs-review later.

**Comment by wentasah** [comment]
So I created a draft PR from my branch and run `nixpkgs-review` on it. Results are [here](https://github.com/NixOS/nixpkgs/pull/310617#issuecomment-2104810615). Only 3 packages fail, all due to a failure in `python3Packages.torchWithRocm`. However, this seems to be caused by non-reproducibility of the package. `nix build --rebuild .#python3Packages.torchWithRocm` complains about non-reproducibility and I can build the package on another system even with this PR.

**Comment by hacker1024** [comment]
Thanks @wentasah, I'm happy to close this PR in favour of yours if that works for you.

**Pull request closed without merging**
