### PR TITLE
linuxPackages.nvidiaPackages.vulkan_beta: 550.40.79 -> 550.40.80

### PR DESCRIPTION
**Pull request by Kiskae**
- November 21st, 2024 - Windows 553.40, Linux 550.40.80
  - New:
    - [VK_KHR_video_encode_av1](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_video_encode_av1.html)
    - [VK_EXT_vertex_attribute_robustness](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_vertex_attribute_robustness.html)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Kiskae** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 358235 --checkout commit`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 5 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_vulkan_beta_open</li>
  </ul>
</details>
<details>
  <summary>:x: 10 packages failed to build:</summary>
  <ul>
    <li>linuxKernel.packages.linux_6_12.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_6_12.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_6_12.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_6_12.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_6_12.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_vulkan_beta_open</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 80 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_6_11.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_6_11.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_6_11.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_6_11.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_6_11.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_6_11_hardened.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_6_11_hardened.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_6_11_hardened.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_6_11_hardened.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_6_11_hardened.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_6_1_hardened.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_6_1_hardened.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_6_1_hardened.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_6_1_hardened.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_6_1_hardened.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_6_6_hardened.nvidia_x11_vulkan_beta)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_vulkan_beta.bin (linuxKernel.packages.linux_6_6_hardened.nvidia_x11_vulkan_beta.bin)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_vulkan_beta.firmware (linuxKernel.packages.linux_6_6_hardened.nvidia_x11_vulkan_beta.firmware)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_vulkan_beta.lib32 (linuxKernel.packages.linux_6_6_hardened.nvidia_x11_vulkan_beta.lib32)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_vulkan_beta_open (linuxKernel.packages.linux_6_6_hardened.nvidia_x11_vulkan_beta_open)</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_vulkan_beta)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_vulkan_beta.bin (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_vulkan_beta.bin)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_vulkan_beta.firmware (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_vulkan_beta.firmware)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_vulkan_beta.lib32 (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_vulkan_beta.lib32)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_vulkan_beta_open (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_vulkan_beta_open)</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_vulkan_beta_open</li>
  </ul>
</details>

**Comment by Kiskae** [comment]
Linux 6.12 build failures can be fixed with #358047

**Comment by fpletz** [comment]
#358047 doesn't fix build failures but a runtime failure to access the DRM device.

**Comment by Kiskae** [comment]
> #358047 doesn't fix build failures but a runtime failure to access the DRM device.

Ah, I didn't realize the beta driver contained code that would break independently of the other branches.
Looks like https://github.com/NVIDIA/open-gpu-kernel-modules/issues/708 fixes the issue with `latest`/`vulkan_beta`

**Comment by Kiskae** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 358235 --checkout commit`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 27 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_6_12.nvidia_x11</li>
    <li>linuxKernel.packages.linux_6_12.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_6_12.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_6_12.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_6_12.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_6_12.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_6_12.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_6_12.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_6_12.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_vulkan_beta_open</li>
  </ul>
</details>
<details>
  <summary>:x: 12 packages failed to build:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11.lib32</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 136 packages built:</summary>
  <ul>
    <li>gwe</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_6_11.nvidia_x11</li>
    <li>linuxKernel.packages.linux_6_11.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_6_11.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_6_11.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_6_11.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_6_11.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_6_11.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_6_11.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_6_11.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_6_11_hardened.nvidia_x11</li>
    <li>linuxKernel.packages.linux_6_11_hardened.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_6_11_hardened.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_6_11_hardened.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_6_11_hardened.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_6_11_hardened.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_6_11_hardened.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_6_11_hardened.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_6_11_hardened.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_6_1_hardened.nvidia_x11</li>
    <li>linuxKernel.packages.linux_6_1_hardened.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_6_1_hardened.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_6_1_hardened.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_6_1_hardened.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_6_1_hardened.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_6_1_hardened.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_6_1_hardened.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_6_1_hardened.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11 (linuxKernel.packages.linux_6_6_hardened.nvidia_x11)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11.bin (linuxKernel.packages.linux_6_6_hardened.nvidia_x11.bin)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11.firmware (linuxKernel.packages.linux_6_6_hardened.nvidia_x11.firmware)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11.lib32 (linuxKernel.packages.linux_6_6_hardened.nvidia_x11.lib32)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_6_6_hardened.nvidia_x11_vulkan_beta)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_vulkan_beta.bin (linuxKernel.packages.linux_6_6_hardened.nvidia_x11_vulkan_beta.bin)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_vulkan_beta.firmware (linuxKernel.packages.linux_6_6_hardened.nvidia_x11_vulkan_beta.firmware)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_vulkan_beta.lib32 (linuxKernel.packages.linux_6_6_hardened.nvidia_x11_vulkan_beta.lib32)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_vulkan_beta_open (linuxKernel.packages.linux_6_6_hardened.nvidia_x11_vulkan_beta_open)</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_vulkan_beta_open</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11 (linuxKernel.packages.linux_xanmod_stable.nvidia_x11)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11.bin (linuxKernel.packages.linux_xanmod_stable.nvidia_x11.bin)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11.firmware (linuxKernel.packages.linux_xanmod_stable.nvidia_x11.firmware)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11.lib32 (linuxKernel.packages.linux_xanmod_stable.nvidia_x11.lib32)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_vulkan_beta)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_vulkan_beta.bin (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_vulkan_beta.bin)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_vulkan_beta.firmware (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_vulkan_beta.firmware)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_vulkan_beta.lib32 (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_vulkan_beta.lib32)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_vulkan_beta_open (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_vulkan_beta_open)</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11.bin</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11.firmware</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11.lib32</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_vulkan_beta.bin</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_vulkan_beta.firmware</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_vulkan_beta.lib32</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_vulkan_beta_open</li>
    <li>tuxclocker</li>
    <li>tuxclocker-nvidia-plugin</li>
    <li>tuxclocker-plugins-with-unfree</li>
  </ul>
</details>

**Review by fpletz — APPROVED** [review]

**Pull request merged**
