### PR TITLE
ats2: 0.3.0 -> 0.3.7

### PR DESCRIPTION
**Pull request by yrashk**
The patch is no longer needed as ats2 includes contribs in the
upstream Makefile_dist file

###### Motivation for this change

ats2 in nixpkgs is outdated

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by adisbladis** [comment]
Nothing that's wrong with this PR but I would like to see `gcc` wrapped since it's a runtime dependency.

**Comment by Mic92** [comment]
Does everybody wants to use the same version of gcc for this package?

**Comment by adisbladis** [comment]
@Mic92 I don't know if everyone would want to use the same gcc version but as it is now invoking `nix-shell -p ats2` and running `patscc example.dats` results in the error `sh: gcc: command not found` which is obviously not desired.

**Comment by joachifm** [comment]
Merging this as-is, the gcc wrapping thing can be solved later. Thank you.

**Pull request merged**
