### PR TITLE
git: 2.17.1 -> 2.18.0

### PR DESCRIPTION
**Pull request by dtzWill**
New release! :)

Release notes: https://github.com/git/git/blob/master/Documentation/RelNotes/2.18.0.txt

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
  * Before: 215181576
  * After:  218954256
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Not unsuited for merging but I had to disable a number of tests that were failing,
and would appreciate help investigating them further in case they indicate
problems that really should be fixed.

### CODE REVIEW

**Comment by dtzWill** [comment]
cc @layus @matthewbauer @NeQuissimus as being involved in recent updates to this package.

**Review by matthewbauer — APPROVED** [review]

**Review by NeQuissimus — APPROVED** [review]

**Comment by dtzWill** [comment]
Tests newly failing (perhaps didn't exist previously, haven't checked):

#### t9902-completion
 "sourcing the completion script clears cached --options" -- I'm seeing this in the logs which seems likely to be related but I'm not sure:
```
/build/git-2.18.0/t/../contrib/completion/git-completion.bash: line 354: compgen: command not found
```
This is printed even when the failing sub-test is disabled, but may be worth checking anyway.

#### editor with a space

Not sure why these fail, perhaps tests end up using the sandbox shell instead of bash? Might be good to double-check the installed result manually re:ensuring this behavior isn't broken.

**Comment by dtzWill** [comment]
@GrahamcOfBorg build git

(maybe Darwin build will complete tests before timing out on a second try? O:))

**Comment by dtzWill** [comment]
Can a @NixOS/darwin-maintainers confirm this doesn't break the build on Darwin? Borg is timing out on the tests :3.

**Review by LnL7 — APPROVED** [review]
darwin build looks good

**Comment by flokli** [comment]
@dtzWill looks good here as well.

**Comment by xeji** [comment]
@dtzWill this appears to break `fetchgit` in some cases, see https://github.com/NixOS/nixpkgs/pull/41414#issuecomment-399787300

**Comment by dtzWill** [comment]
I'm a bit short on time for nixpkgs things tonight/next few days, so unless someone else steps up I vote reverting the update until we can sort this out.

Very sorry for the breakage, thanks for tracking it to the update and I'm sure we'll sort it out properly soon.

**Comment by xeji** [comment]
Thank you!

**Comment by layus** [comment]
Okay, so the issue comes from upstream (https://github.com/git/git/commit/0b5e2ea7cf3b0fd0f4339b7c8b69cb8c5853c0cd) that changed the output format of `git submodule status` to avoid printing `((null))` when the name is not known.

I modified the regex to make this third part optional: https://github.com/dtzWill/nixpkgs/pull/1

@dtzWill Just merge the PR, and test/resubmit ;-)

**Pull request merged**
