### PR TITLE
vimPlugins.muren-nvim: init at 2023-08-26

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Things done

Add vim plugin [muren.nvim](https://github.com/AckslD/muren.nvim), a plugin to do multiple replacements in neovim.

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 353828`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>vimPlugins.muren-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>vimPlugins.muren-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>vimPlugins.muren-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>vimPlugins.muren-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Review by mrcjkb — APPROVED** [review]

**Comment by teto** [comment]
seems like the plugin doesn't need a setup function. can we add a small check `vimCommandCheck = "MurenToggle";`  ? it helps when debugging too, so that you dont have to look for what to test.

**Comment by GaetanLepage** [comment]
> seems like the plugin doesn't need a setup function. can we add a small check `vimCommandCheck = "MurenToggle";` ? it helps when debugging too, so that you dont have to look for what to test.

It fails with:
```
Check whether the following modules can be imported: MurenToggle
Entering Ex mode.  Type "visual" to go to Normal mode.
:if exists(":MurenToggle") == 2

:  cquit 0
:  else
:  cquit 1
```

**Comment by GaetanLepage** [comment]
> seems like the plugin doesn't need a setup function.

Are you sure ?
Isn't the [config = true](https://github.com/AckslD/muren.nvim?tab=readme-ov-file#installation) automatically calling the `setup` function ?

**Comment by teto** [comment]
arf, it might need a setup after all. IIRC that's what the `config = true,` does in the lazy.vim package manager. We should burn those plugins that refuse to work without a `setup` call. Feel free to merge the devilish package as is.

**Comment by bkp5190** [comment]
I see this has been added to nixpkgs, but it is not available in the nixpkgs-unstable branch yet. What is the timeframe for this to be made available?

**Comment by GaetanLepage** [comment]
> I see this has been added to nixpkgs, but it is not available in the nixpkgs-unstable branch yet. What is the timeframe for this to be made available?

This usually happens every 2-4 days.
You can check the status here:
- https://status.nixos.org/
- https://monitoring.nixos.org/grafana/d/LhIq8iLWk/channel-updates?orgId=1&refresh=10s
- https://nixpkgs-tracker.ocfox.me/?pr=353828

**Comment by bkp5190** [comment]
Awesome! Thank you!

**Pull request merged**
