### PR TITLE
slurm: 23.02.6.1 -> 23.11.0.1

### PR DESCRIPTION
**Pull request by markuskowa**
## Description of changes

Changelog: https://slurm.schedmd.com/news.html

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by markuskowa** [comment]
This update breaks pyslurm and the spank plugins. Needs further investigation before we can merge it.

**Comment by posch** [comment]
schedmd releases a critical update, today. I've updated to slurm-23.11, and had no problems so far, but I'm not using pyslurm or spank. Will you create an update to 23.06.7 instead? Or can we proceed to 23.11.1?

**Review by posch — COMMENTED** [review]
MAXPATHLEN is available when adding
#include <sys/param.h>

What's the difference between MAXPATHLEN and PATH_MAX?

**Comment by markuskowa** [comment]
I actually prefer to update 23.02 first. See https://github.com/NixOS/nixpkgs/pull/274301

**Comment by SomeoneSerge** [comment]
With `23.11.0` we can update the systemd services to `Type = "notify"`

**Comment by markuskowa** [comment]
> What's the difference between MAXPATHLEN and PATH_MAX? 

PATH_MAX is the Posix compatible version.

**Comment by markuskowa** [comment]
> With `23.11.0` we can update the systemd services to `Type = "notify"`

I did try that, but it does seem to work out of the box. I would rather update Slurm first and fix the module later in another. It currently works just fine with forking.

**Comment by markuskowa** [comment]
@GrahamcOfBorg test slurm
@GrahamcOfBorg build slurm-spank-x11 slurm-spank-stunnel

**Comment by markuskowa** [comment]
pyslurm support seems to be on the way: https://github.com/PySlurm/pyslurm/issues/327. Although I do not see pyslurm as a blocker right now.

**Comment by markuskowa** [comment]
@posch @SomeoneSerge Any further comments? Should we just merge it?

**Review by SomeoneSerge — APPROVED** [review]
Yes, I don't see any reason to hold this

**Pull request merged**
