### PR TITLE
[22.11] cachix: 1.1 -> 1.3.1

### PR DESCRIPTION
**Pull request by domenkozar**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by domenkozar** [comment]
Thanks, looking into it.

**Comment by risicle** [comment]
This was a nasty surprise which broke some of my tooling and doesn't appear to have any explanation.

**Comment by domenkozar** [comment]
@risicle could you elaborate on what broke?

**Comment by risicle** [comment]
I've not quite pinned it down fully, but it appears that `watch-exec` mode _may_ be quitting too early to allow pending uploads to finish.

**Comment by domenkozar** [comment]
If you can provide a way to reproduce this, we'll fix it right away.

We're looking into functional tests for watch-exec to catch these bugs early.

Note that we need to bump Cachix also on stable to make sure it catches up with the backend changes.

**Comment by risicle** [comment]
These are the functional tests for https://github.com/risicle/nix-build-task that are failing, though I don't expect you to decipher them because concourse ci is a little obscure in nix circles and the tests do some Funny Stuff to check the cachix integration is working as intended. https://github.com/risicle/nix-build-task/blob/master/ci/build.yml#L655

**Comment by risicle** [comment]
I'm currently testing a variant that sleeps 10s after finishing its work...

**Comment by domenkozar** [comment]
I opened https://github.com/NixOS/nixpkgs/pull/221848 - could you test this one?

**Comment by risicle** [comment]
Building cachix from source made my small ci worker instance OOM and not come back cleanly, so it's possible I may not be able to test on the affected system till monday...

**Comment by risicle** [comment]
Testing on a (slightly dodgy, docker based) temporary concourse installation suggests that has indeed fixed it.

FWIW I'm not sure going back and bumping the nixpkgs stable branch's cachix is going to be enough if you want to make breaking changes to the cachix protocol and not cause your users pain. e.g. I myself have part of a pipeline that needs to depend on an old-ish nix docker image at the bottom of its bootstrapping process - that image has a pre-1.0 version of the cachix cli.

**Pull request merged**
