### PR TITLE
netlify-cli: Upgrade to nodejs_18

### PR DESCRIPTION
**Pull request by roberth**
###### Description of changes

16 will be EOL during NixOS 23.05 support window as mentioned in https://github.com/NixOS/nixpkgs/pull/229910#issuecomment-1538936445

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
     - passes package test
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
We should also probably rewrite its expression with buildNpmPackage

**Comment by roberth** [comment]
Not a big fan of complex FODs, but it seems like a thing people do in Nixpkgs.
I've been reviewing RFC 92 related changes in Nix recently. Eyes on the horizon ;D

**Review by lilyinstarlight — APPROVED** [review]
I manually tested on aarch64-darwin and x86_64-darwin since ofborg still hasn't gotten around to it. It builds fine, but that test is broken on darwin, both from this PR and from master (so it's not a regression)

Thanks for handling this!

**Comment by lilyinstarlight** [comment]
@roberth, could you actually also update the `generate.sh` file to generate with node 18? It looks like that was missed

Thanks again!

**Comment by roberth** [comment]
@lilyinstarlight
 - See https://github.com/NixOS/nixpkgs/pull/235606

**Pull request merged**
