### PR TITLE
displaylink: 1.3.52 -> 4.1.9 and refactor

### PR DESCRIPTION
**Pull request by ghost**
While this commit updates displaylink, it also refactors the package to
use a FHS env. This is because the binary of displaylink breaks when
modifying the RPATH with patchelf. So a little wrapper is created around
it, running the binary in the chroot.

This is the first time I use an FHS env, so please look at this accurately.

###### Motivation for this change

The current version of displaylink doesn't work because patchelf breaks the RPATH.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
@GrahamcOfBorg build displaylink

**Comment by joachifm** [comment]
Ah, it's unfree, ignore the build errors :)

**Review by abbradar — CHANGES_REQUESTED** [review]
This doesn't build for me; probably needs `hardeningDisable = [ "format" ];` because of kernel module errors.

Before you fix my other comments -- are you sure FHS environment is really necessary? Binary corruption can be possibly fixed with just `dontStrip = true;`.

P.S.: I don't have hardware to test this, so I rely on you saying that it works.

**Comment by schuppentier** [comment]
@abbradar Thank you for your review! As you can see, I'm a Nix(OS) newbie so your hints are highly appreciated.
With help of @Lassulus I entirely rebuilt this PR from scratch.

> This doesn't build for me; probably needs hardeningDisable = [ "format" ]; because of kernel module errors.

Um, it works here without `hardeningDisable`. Have you enabled any special hardening options that I can enable as well to see if it still works?

> Before you fix my other comments -- are you sure FHS environment is really necessary? Binary corruption can be possibly fixed with just dontStrip = true;.

Sadly, yes. When creating the PR from scratch, I tried again with `dontStrip`. However, the binary is already stripped so I doubt that strip would do anything. Also, it only works when removing `--set-rpath` from patchelf, so I think that patchelf causes the binary corruption. When using `ldd`, it cannot read the rpath when it's patched.
So yes, the FHS env seems to be required.

> P.S.: I don't have hardware to test this, so I rely on you saying that it works.

It works here, but of course, it's better to have more testers. I'll ask a friend of mine who also runs NixOS to test it, too, but that's all I can do.

> My memory is hazy but I think this service is started automatically by udev rules, so no need for that.

Your memory is correct ;) I removed the `RequiredBy`

> Won't other files, like udev rules, be hidden in package because of that indirection?

Yes, but that should be fixed now with the `symlinkJoin`.

**Comment by abbradar** [comment]
@scarmiglione Very strange, I just now tried to bump DisplayLink's version in our existing package and the binary (`DisplayLinkManager`) works. About hardening: I guess that's because I try to build the package on master which has newer something. I've fixed it with disabling fortify hardening for evdi (DisplayLink's kernel driver).

Can you try building https://github.com/abbradar/nixpkgs/commits/displaylink and verifying if resulting binary fails for you?

**Comment by schuppentier** [comment]
@abbradar It seems to run with your branch, but my two monitors are not detected.

**Comment by abbradar** [comment]
Does daemon run and is `evdi` module loaded?

**Comment by schuppentier** [comment]
Yes, the daemon is running and the evdi module is loaded

**Comment by abbradar** [comment]
Maybe `/tmp/DisplayLinkManager.log` says something?

If we won't be able to solve this in a reasonable amount of time let's use your FHS implementation instead.

**Comment by abbradar** [comment]
@schuppentier I think I fixed that, can you try if it works now?

**Comment by schuppentier** [comment]
@abbradar Yes! This really fixes it! This message is typed on a browser on my DisplayLink monitor, running your branch. Do you want to create a new PR that replaces this one?

**Comment by abbradar** [comment]
Awesome ;) I'll just push to master then after one more evaluation test (I'll close this one when I push). Thank you!

**Comment by schuppentier** [comment]
Thank you very much for your help :) Will this be part of the next NixOS release btw?

**Comment by abbradar** [comment]
Yeah, I still have plenty of time to push that. I'll backport this to 17.09 too.

**Comment by schuppentier** [comment]
Alright, thank you :+1:

**Comment by schuppentier** [comment]
Do you also backport evdi? It's required for DisplayLink and broken on the current kernel.

**Comment by abbradar** [comment]
@schuppentier Yeah, plan to do so. Generally our policy is that it's okay to backport version changes to stable releases if it's needed to fix something.

**Comment by azdle** [comment]
@schuppentier is there anything required to use this other than adding it to `displayDrivers`? I've been trying to get this to work for a few months now and your fix has solved the segfault issue, but am still not getting anything on my external displays.

My config: https://github.com/azdle/my-nixos-config/blob/master/desktop-configuration.nix#L31

**Comment by schuppentier** [comment]
@azdle Try something like `xrandr --listproviders` and `xrandr --setprovideroutputsource 0 1`

**Comment by azdle** [comment]
Dang, that did it. You rock.

I ran:

```
xrandr --setprovideroutputsource 2 0
xrandr --setprovideroutputsource 3 0
```
and both of my external displays then showed up in gnome's "displays" settings pane as turned off. Turned each one and they're both working now.

It's somehow making firefox really laggy (multiple seconds of lag) and the whole UI goes laggy when I close the lid, but this is a whole lot closer than I've gotten before and this is something that should be much more googleable.

Again, thanks, so much.

**Pull request closed without merging**
