### PR TITLE
perldevel: 5.29.6 -> 5.29.9

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

version bump

big number of rebuilds is only ```perldevelPackages.*```

cc @rycee @srhb

### CODE REVIEW

**Comment by volth** [comment]
@GrahamcOfBorg build perldevelPackages.LWP

**Comment by rycee** [comment]
Looks fine to me. I guess the `perldevelPackages` rebuild is light? Otherwise I would suggest pointing the PR to staging.

**Comment by volth** [comment]
Yes, that should be light

**Comment by rycee** [comment]
Cool 🙂 Rebased to master in 39fc981fcac64a203307194ebf2cbdabdacdd97a.

**Pull request closed without merging**
