### PR TITLE
nixos/keycloak: Use LoadCredential to load secrets + module formatting

### PR DESCRIPTION
**Pull request by talyz**
###### Motivation for this change

- ### Use `LoadCredential` to load secrets
  Use systemd's `LoadCredential` mechanism to make the secret files available to the service.

  This gets rid of the privileged part of the `ExecPreStart` script which only served to copy these files and assign the correct
permissions. There's been issues with this approach when used in combination with `DynamicUser`, where sometimes the user isn't created before the `ExecPreStart` script runs, causing the error

  > install: invalid user ‘keycloak’

  This should fix that issue.

  Unfortunately, all of the `ExecPreStart` script had to be moved to `ExecStart`, since credentials aren't provided to `ExecPreStart`. See https://github.com/systemd/systemd/issues/19604.

- ### Reformat the module
  Instead of referencing all library functions through `lib.` and builtins through `builtins.` at every invocation, inherit them into the appropriate scope. This is a follow-up to #154193.

  Also, reformat the module with `nixpkgs-fmt`.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by abbradar — APPROVED** [review]
Looks good! TIL of `nixpkgs-fmt`.

**Comment by abbradar** [comment]
Tested with my development servers, works well. Will merge tomorrow to give some time for other potential reviewers -- unless you want to merge it by yourself :)

**Comment by talyz** [comment]
Great! That plan sounds good to me :)

**Comment by abbradar** [comment]
@talyz can you backport it manually?

**Comment by talyz** [comment]
Sure! Here it is: #155898

**Pull request merged**
