### PR TITLE
python3Packages.tensorflow: 2.11.0 -> 2.11.1

### PR DESCRIPTION
**Pull request by risicle**
###### Description of changes

2.12.0 is out, but that didn't immediately work for me and 2.11.1 appears to address the same CVEs.

https://github.com/tensorflow/tensorflow/releases/tag/v2.11.1

~Seeking volunteer(s) to generate the deps hashes for aarch64-linux and aarch64-darwin, otherwise I'll get ofborg to do it and everyone will hate me for making ofborg build tensorflow...~

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SomeoneSerge** [comment]
> Seeking volunteer(s) to generate the deps hashes for aarch64-linux and aarch64-darwin

On that note, there were some experiments around forcing Bazel to fetch dependencies for all platforms at once in https://github.com/NixOS/nixpkgs/pull/219778/commits/aaf0d0a14fb9acfa5ed02b5dc7536551279646a9. This way there should be just one hash, which can be computed on any platform. I'm still unclear on whether that is actually already working, and I don't know if the same trick could be applied to tensorflow

**Comment by risicle** [comment]
Got the aarch64-darwin hash now

**Comment by mweinelt** [comment]
> Seeking volunteer(s) to generate the deps hashes for aarch64-linux and aarch64-darwin, otherwise I'll get ofborg to do it and everyone will hate me for making ofborg build tensorflow...

aarch64-darwin `sha256-qZvqXi6pvIrZpZdR4BcbOh2C/A4ZHJgXgFINhVJmmcs=`
aarch64-linux `sha256-g6JUZQQalCTSjvAarkI7+gq13cPhFg/O9LPQDGNvrII=`

**Comment by SomeoneSerge** [comment]
Needs a rebase before `nixpkgs-review` can take off

**Comment by risicle** [comment]
Hmm hopefully #224917 doesn't cause us to have to recalculate all the hashes.

**Comment by mweinelt** [comment]
Builds fine on x86_64-linux and works for tts.

**Comment by SomeoneSerge** [comment]
Just for the record: we're currently blocked by the merge conflicts

**Comment by risicle** [comment]
That's because this got bumped past in #225174

**Comment by SomeoneSerge** [comment]
That one only updates the -bin?

**Comment by risicle** [comment]
Damn I shouldn't have combined the two in the same PR. Just confusing. Stand by...

**Comment by dotlambda** [comment]
Don't forget that this hasa to be backported.

**Comment by mweinelt** [comment]
1.10.1 on 22.11 :/

**Comment by risicle** [comment]
#224988

**Pull request merged**
