### PR TITLE
Vulnerability rollup 11 (WIP)

### PR DESCRIPTION
**Pull request by grahamc**
###### Motivation for this change

https://github.com/NixOS/nixpkgs/issues/20814

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
I wonder, why don't you push these to master directly?

**Comment by grahamc** [comment]
Sure --

I usually work on these some in the morning and then some again in the evening. Sometimes I'll have one or more mass rebuild-triggering issues. Darwin is really sensitive to multiple world-rebuilds, because they only have a few machines and can't scale up like linux can.

I also like to do a bit of testing to make sure my changes don't break other packages.

To take care of these issues, I've been making a "rollup" branch which contains all my patches, making sure it looks good, and then merging all at once.

I open the PR because my NixOS testing tools work best with PRs :)

**Comment by grahamc** [comment]
Ok, with the bzip push this is officially a mass rebuild :)

**Comment by grahamc** [comment]
I reverted bzip2 to make it easier to test subsequent patches. Will delete the revert later.

**Comment by grahamc** [comment]
lol, then I added icu for more rebuild. Reverting that too. Will delete later.

**Comment by grahamc** [comment]
Alright, this is getting ready to merge, just waiting on merging a few simpler PRs before this one.

**Pull request merged**
