### PR TITLE
Pre-generate fontconfig caches

### PR DESCRIPTION
**Pull request by abbradar**
Fixes https://github.com/NixOS/nixpkgs/issues/12648. Also should generally improve startup times, I think. Note that when using fonts like `noto-fonts-cjk` the build time would be somewhat long -- that's expected (better than having all applications rebuild this in memory on every start!).

### CODE REVIEW

**Comment by edolstra** [comment]
Wait, since when are we pre-generating fontconfig caches, and why?

**Comment by vcunat** [comment]
@edolstra: this PR would add it. ATM each user has to generate its own cache. And with (some) login managers the caches apparently don't even persist.

**Comment by vcunat** [comment]
@abbradar: how did you determine that 32-bit fontconfig needs its own caches? So far we were sharing them, I believe.

**Comment by abbradar** [comment]
@edolstra as @vcunat said, window managers don't have any font cache by now, so they are regenerating it each time leading to very long boot times for people with e.g. CJK fonts. See #12648. Also, even if this wasn't the case system-wide cache should be better anyway, because now each user has to re-generate it by himself from scratch. The cache should lift most of the burden, apart from profile-installed fonts.

@vcunat I'm not really sure, I've used [this man page](http://linux.die.net/man/1/fc-cache) for reference.

> Note that fc-cache must be executed once per architecture to generate font information customized for that architecture.

**Comment by abbradar** [comment]
Also cache files are different, with `le32d4` architecture suffix on i686 and `le64` on `x86_64` but I'm not sure there isn't some clever cache-sharing code present.

**Comment by vcunat** [comment]
No, you're right. Sharing the cache directories *is* fine but the cache files are separate.

**Comment by abbradar** [comment]
One more thing to notice: I haven't bothered to add the cache to fontconfig 2.10. In fact, why do we still have it there? 2.11 is more that 2 years old and nothing references `fontconfig_210` in nixpkgs.

**Comment by vcunat** [comment]
I believe this PR is a good way how to do it, at least in principle. They're system-wide fonts, so it makes sense to distribute with the caches and thus share the data among users.

I'm slightly hesitant about the order of `<cachedir>` entries. This PR will make the pre-generated the first one which is probably not good. The docs claim *the directory that can be accessed first in the list will be used to store the cache files*, so the directory would be in danger of being written to, e.g. by root if `nix.readOnlyStore = false`.

**Comment by vcunat** [comment]
2.10 is safe to disregard in this PR. It's there because stuff using fontconfig <2.11 can't use `/etc/fonts` for fontconfig >=2.11. (I remember horrible failures like 100% CPU usage indefinitely or boxes instead of characters.)

**Comment by abbradar** [comment]
Ouch, I haven't even thought we have `nix.readOnlyStore`!

Anyway, I've added the patch which I think would solve the issue. This would make this a mass-rebuild but we have #12600 anyway.

**Comment by vcunat** [comment]
The reorder seems fine. I just hope that the formulation from docs doesn't mean that fontconfig will read caches also only from the first accessible directory. If it did, I suppose we would have to patch fontconfig.

**Comment by abbradar** [comment]
I don't really think so, that's why Arch does `fc-cache` on fonts installation, but also asks one to do `fc-cache` as user when adding a new font to the user directory. However, I have nothing to back this except those thoughts...

**Comment by abbradar** [comment]
https://superuser.com/questions/527339/in-xorg-fontconfig-why-two-font-caches-var-cache-and-home-possible-to-get-r somewhat supports this but has no explicit statement...

**Comment by edolstra** [comment]
I don't really understand the need for this. I mean, fontconfig generates cache files on the fly (e.g. in ~/.cache/fontconfig), and presumably only for fonts that are actually used rather than all fonts. If certain applications lack a font cache or rebuild it on every start, than there is something wrong there (maybe they need $HOME or $XDG_CACHE_HOME set?).

How much bigger would this make the system closure?

**Comment by abbradar** [comment]
@edolstra By a small amount: 1.4M even with aforementioned `noto-fonts-cjk` enabled. However, then all users don't have to regenerate this by themselves, saving time and space by reusing. Also, thought of window managers generating their font cache seems inelegant to me -- for example, SLIM doesn't have a home I think, and why would it have one just to store a font cache?

**Comment by vcunat** [comment]
@edolstra: the problem referenced from the title is for the display/login manager which isn't really expected to have reasonable `$HOME`, is it? It seems to me the cache has a negligible size w.r.t. to the corresponding font size.

**Comment by vcunat** [comment]
I verified that `fc-cache` does use multiple cache dirs correctly (`--verbose` helped). Actually, most distros do utilize this &ndash; they have read-only cache for system fonts and per-user cache for per-user fonts. With this PR we would just start doing it the same as others.

**Comment by abbradar** [comment]
To show some idea of how long this cache can be generated with CJK fonts: on my T440p laptop (Haswell Core i7, 512G SSD and 12G ram) this takes 32 seconds with this expression:

```
{ pkgs ? import ./. { } }:
let
  fontDirectories = with pkgs; [
    corefonts # Microsoft free fonts
    cm_unicode
    stix-otf
    dejavu_fonts
    source-code-pro
    noto-fonts
    noto-fonts-cjk
    noto-fonts-emoji
  ];
in pkgs.makeFontsCache { inherit fontDirectories; 
```

which, arguably, is a fairly standard set of fonts, apart from CJK ones. This cost would have to be taken by each user and window manager separately on start, repeatedly if there is no `$HOME` to store the results, without system-wide cache.

**Comment by vcunat** [comment]
I'm not using any CJK, just a few more font packages, and the cache is regenerated relatively quickly when I clean it. (<6 seconds with old 2.4 GHz core i3 notebook, just in-place run of `fc-cache` after removing the cache manually. I also get a larger cache, ~1.3 MB.)

**Comment by abbradar** [comment]
Note that on NixOS (not with an expression above) I also get ~1.3MB, I think this is because of some additional fonts from a desktop environment -- for example, X.org fonts.

**Comment by edolstra** [comment]
Well, AFAIK, other distributions use /var/cache/fontconfig, which NixOS also used to use but for some reason no longer does. That seems a more appropriate location for cached data than the Nix store. (On my machines, that directory was last updated around Oct 2014, so I guess we lost that functionality around that time. Presumably this broke caching for display managers.) 

@abbradar I guess when you say "window manager" you mean "display manager"? Window managers should have a home directory.

**Comment by abbradar** [comment]
@edolstra Yes, sorry for messing up terms.

Hm, I see no reason to use `/var/cache/fontconfig` (which would require start-up scripts for creating the directory and calling `fc-cache` while system fonts cannot actually change on NixOS) when we can actually build the whole thing in Nix store on rebuild. It would be similar anyway -- we should get the same results.

**Comment by vcunat** [comment]
> Well, AFAIK, other distributions use /var/cache/fontconfig

Yes, but that one is only writable by root. (It might be insecure otherwise, I suppose.)

**Comment by vcunat** [comment]
IMHO nix store is not a bad location for *persistent* deterministic cache, which is this case. Using a startup script is another option. (I rather dislike the usual packaging where fonts that *the root user can access* get cached into `/var/cache/fontconfig`.)

**Comment by edolstra** [comment]
Yeah, it could be done in an activation script, but maybe that will slow down the activation script too much (depending on whether fc-cache is incremental). So I guess putting it in the Nix store is preferrable.

**Comment by abbradar** [comment]
Good! Then I'll merge this along with #12600 to staging after waiting a few days for others' opinions just in case. Feel free to do this sooner if you merge something else mass-rebuildy.

**Comment by abbradar** [comment]
@aparten reported problems with this in https://github.com/NixOS/nixpkgs/issues/12648#issuecomment-177250358 -- please don't merge yet.

**Comment by abbradar** [comment]
Merged to staging in https://github.com/NixOS/nixpkgs/commit/53e0f8b1cdf36574bfede6e62e2ac2739c3ef804 (why haven't close-via-commit-message worked?).

**Comment by vcunat** [comment]
@abbradar: that only works for the main branch (master typically, including our repos).

Many months ago I reported to them that they should fix this in PRs filed against different branches. They promptly replied, very politely, thanking me for the idea, but that was all I've ever heard about it. It's unfortunate that this experience seems typical. You probably saw https://github.com/dear-github/dear-github... Even if someone from the community wanted to fix it, they just cannot.

**Comment by vcunat** [comment]
Going this way, it seems to me GitLab will become a superior choice within several years.

**Comment by abbradar** [comment]
The fun part is -- I've heard about the restriction but I've just managed to close https://github.com/NixOS/nixpkgs/pull/12600 with a merge to staging! Maybe this is a parser problem now...

That said, I like how GitLab develops -- we'll see who wins but the competition is always good.

**Comment by vcunat** [comment]
Oh, so they've fixed this issue :-)

**Pull request closed without merging**
