### PR TITLE
ffmpeg: 4.2.3 -> 4.3

### PR DESCRIPTION
**Pull request by zowoq**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
@ofborg build ffmpeg-full

**Comment by zowoq** [comment]
@ofborg eval

**Comment by zowoq** [comment]
@ofborg build handbrake mpv-unwrapped mpv
@ofborg test handbrake

**Review by primeos — APPROVED** [review]
I didn't test anything but the diff LGTM and `prefer-libdav1d-over-libaom.patch` is indeed not required anymore as this is already the new default in FFmpeg 4.3.

**Comment by pwetzel** [comment]
Built this and obs-studio on top of it, tested OK.

**Comment by zowoq** [comment]
I looked at adding `rav1e` but it [seems to need a cargo tool](https://github.com/xiph/rav1e#building-the-c-api) that isn't packaged in nixpkgs yet.

**Comment by primeos** [comment]
@zowoq rav1e support would be cool :) I just drafted #91050 so we can add that support later (shouldn't delay this PR).

**Pull request merged**
