### PR TITLE
protonvpn-gui: 4.6.0 -> 4.7.3

### PR DESCRIPTION
**Pull request by Steinhagen**
Updated protonvpn-gui version with all it's dependencies. Since all dependencies are updated at the same time by the developers, I would recommend to do the same in a single PR to make sure that everything is working as expected.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by SebTM** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 354170`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 11 packages built:</summary>
  <ul>
    <li>proton-vpn-local-agent</li>
    <li>protonvpn-gui</li>
    <li>protonvpn-gui.dist</li>
    <li>python311Packages.proton-vpn-api-core</li>
    <li>python311Packages.proton-vpn-api-core.dist</li>
    <li>python311Packages.proton-vpn-network-manager</li>
    <li>python311Packages.proton-vpn-network-manager.dist</li>
    <li>python312Packages.proton-vpn-api-core</li>
    <li>python312Packages.proton-vpn-api-core.dist</li>
    <li>python312Packages.proton-vpn-network-manager</li>
    <li>python312Packages.proton-vpn-network-manager.dist</li>
  </ul>
</details>

**Review by SebTM — APPROVED** [review]
LGTM 👍🏻 Did a quick test connecting to different countries via wireguard without issues

**Comment by Steinhagen** [comment]
I retried the update again in more detail and it seems that the settings widget is not opening anymore. Until that gets fixed, this update shouldn't get merged.

**Comment by Steinhagen** [comment]
This seems to be an upstream issue, where they aren't checking if the `self.distro_manager` is initialized before using it.
https://github.com/ProtonVPN/proton-vpn-gtk-app/blob/stable/proton/vpn/app/gtk/widgets/headerbar/menu/settings/early_access.py#L301

```
  File "/nix/store/i15jvsh3hvhmn4vjwcyc1hf9yka02vrh-protonvpn-gui-4.7.1/lib/python3.12/site-packages/proton/vpn/app/gtk/widgets/headerbar/menu/settings/early_access.py", line 235, in get_setting
    _, beta_package_installed = self._find_installed_repo_packages()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/i15jvsh3hvhmn4vjwcyc1hf9yka02vrh-protonvpn-gui-4.7.1/lib/python3.12/site-packages/proton/vpn/app/gtk/widgets/headerbar/menu/settings/early_access.py", line 301, in _find_installed_repo_packages
    self.distro_manager.list_installed_packages_command.split()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'list_installed_packages_command'
```

**Comment by Steinhagen** [comment]
The issue was resolved upstream.
Based on my testing, everything is working as expected.

**Comment by SebTM** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 354170`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 11 packages built:</summary>
  <ul>
    <li>proton-vpn-local-agent</li>
    <li>protonvpn-gui</li>
    <li>protonvpn-gui.dist</li>
    <li>python311Packages.proton-vpn-api-core</li>
    <li>python311Packages.proton-vpn-api-core.dist</li>
    <li>python311Packages.proton-vpn-network-manager</li>
    <li>python311Packages.proton-vpn-network-manager.dist</li>
    <li>python312Packages.proton-vpn-api-core</li>
    <li>python312Packages.proton-vpn-api-core.dist</li>
    <li>python312Packages.proton-vpn-network-manager</li>
    <li>python312Packages.proton-vpn-network-manager.dist</li>
  </ul>
</details>

**Review by SebTM — APPROVED** [review]
Retested with a bit more time - all three protocols worked for me as well as the settings

**Pull request merged**
