### PR TITLE
kdeFrameworks: 5.61.0 -> 5.62.0

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

https://kde.org/announcements/kde-frameworks-5.62.0.php

###### Things done

Tested this for the portion I use on my laptop, not sure if we have any
more exhaustive tests/targets?

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @ttuegel

### CODE REVIEW

**Comment by dtzWill** [comment]
cc @nyanloutre too :).

**Comment by ttuegel** [comment]
@GrahamcOfBorg test plasma5

**Comment by worldofpeace** [comment]
@GrahamcOfBorg test plasma5

**Comment by ttuegel** [comment]
Apparently I no longer have the magic touch. I will have to test this locally and report back.

**Review by bkchr — APPROVED** [review]
Works for me!

**Comment by worldofpeace** [comment]
@ttuegel I believe ofborg is still on the fritz in terms of building things.

**Comment by ttuegel** [comment]
> I believe ofborg is still on the fritz in terms of building things.

Ah, I didn't know that. Thanks! I will defer to @bkchr on this one.

@dtzWill Could you please rebase this onto staging?

**Comment by dtzWill** [comment]
Sure thing, done!

**Review by bkchr — APPROVED** [review]

**Comment by ttuegel** [comment]
Thanks!

**Pull request merged**
