### PR TITLE
gettext: 0.21.1 -> 0.22

### PR DESCRIPTION
**Pull request by dasJ**
Changelog: https://savannah.gnu.org/news/?id=10378

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dasJ** [comment]
This breaks xgcc:
```
make[4]: Entering directory '/build/build/x86_64-unknown-linux-gnu/libstdc++-v3/po'
msgfmt -o de.mo ../../../../gcc-12.3.0/libstdc++-v3/po/de.po
msgfmt -o fr.mo ../../../../gcc-12.3.0/libstdc++-v3/po/fr.po
msgfmt: Cannot convert from "ISO-8859-1" to "UTF-8". msgfmt relies on iconv(). This version was built without iconv().
msgfmt: Cannot convert from "ISO-8859-1" to "UTF-8". msgfmt relies on iconv(). This version was built without iconv().
make[4]: *** [Makefile:564: de.mo] Error 1
```

Does anyone have an idea? The build of gettext finds libiconv…

**Comment by reckenrode** [comment]
Building help2man is where the Darwin stdenv fails to build. This affects both the current and my reworked stdenv branch (which has some patches to use libiconvReal instead of Apple’s vendored libiconv).

```
checking for perl... perl
checking for module Locale::gettext... yes
checking for msgfmt... /nix/store/xj4m25kdadng4rawl04nsm8pzar9sx3y-gettext-0.22/bin/msgfmt
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether clang accepts -g... yes
checking for clang option to enable C11 features... none needed
checking for library containing dlsym... none required
checking for library containing bindtextdomain... no
configure: error: bindtextdomain() required
```

**Comment by reckenrode** [comment]
Looking at the configure logs, it tries to link `-lintl`, which should have the symbol.

```console
$ nm -m libintl.8.dylib | rg bindtextdomain
000000000000d1a8 (__TEXT,__text) external _bindtextdomain
0000000000007414 (__TEXT,__text) external _libintl_bindtextdomain
```

This is what I get on gettext 0.21.1.

```console
$ nm libintl.8.dylib | rg bindtextdomain
000000000000d1a8 (__TEXT,__text) external _bindtextdomain
0000000000007414 (__TEXT,__text) external _libintl_bindtextdomain
```

It looks like the symbol was switched to private. Huh.

**Comment by wegank** [comment]
This should have been fixed in 0.22.1 according to the [release note](https://savannah.gnu.org/news/?group=gettext)?

Anyway, a second attempt at #279197.

**Comment by wegank** [comment]
Superseded by #279197.

**Pull request closed without merging**
