### PR TITLE
[24.05] gitlab-runner: 16.11.1 -> 17.1.0

### PR DESCRIPTION
**Pull request by yayayayaka**
## Description of changes
Backport of #321428 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by hacklschorsch** [comment]
This broke our CI server:  We use `preCloneScript` but that has been deprecated in March 2023.

Do you guys even read the release notes before merging major version upgrades into the 'stable' channel?

**Comment by teto** [comment]
It's not even a matter of release notes, I thought that major updates were banned from backporting ! `gitlab-runner: 16.11.1 -> 17.1.0`

**Comment by hacklschorsch** [comment]
I created PR #324042 for the preCloneScript fix.

(IDK if downgrading GitLab to 16.x again in the stable channel is an option - this might break things badly for everyone who has successfully upgraded, no?)

**Comment by hacklschorsch** [comment]
OTOH, it seems that GitLab hasn't been upgraded to a new major version - only GitlabRunner has.  IIRC, that doesn't even have a DB?
So maybe downgrading to 16.x is the best route forward?

**Comment by yayayayaka** [comment]
> It's not even a matter of release notes, I thought that major updates were banned from backporting !

[It is not](https://github.com/NixOS/nixpkgs/blob/c0acb02a188cb7e2406c50e6527b275a513d4d1b/CONTRIBUTING.md?plain=1#L504). As I noted in [#324554](https://github.com/NixOS/nixpkgs/pull/324554#issue-2390823656),

> Since GitLab only supports the last three releases as of their [release and maintenance policy](https://docs.gitlab.com/ee/policy/maintenance.html), #313984 needs to backported to stable, otherwise it would stop receiving security fixes soon.

Same applies to gitlab-runner.

> OTOH, it seems that GitLab hasn't been upgraded to a new major version - only GitlabRunner has.

#324554

**Comment by hacklschorsch** [comment]
Hem.

My #324042 and #324066 have landed in `master`, but I don't love changing our 'stable' nixpkgs all the time.

Simplest workaround I found to fix our setup was changing to this:

```nix
registrationFlags = [ "--pre-get-sources-script=${preCloneScript}" ];
```

**Pull request merged**
