### PR TITLE
sketchybar: 2.7.1 -> 2.11.2

### PR DESCRIPTION
**Pull request by luxus**
###### Description of changes

https://github.com/FelixKratz/SketchyBar/releases

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Quick version update. 
cc @azuwis

### CODE REVIEW

**Comment by azuwis** [comment]
The compile test failed https://github.com/NixOS/nixpkgs/pull/203897/checks?check_run_id=9823832728:

```
clang -std=c99 -Wall -DNDEBUG -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11 src/sketchybar.m bin/alias.o bin/background.o bin/bar_item.o bin/custom_events.o bin/event.o bin/graph.o bin/image.o bin/mouse.o bin/shadow.o bin/text.o bin/message.o bin/bar.o bin/window.o bin/bar_manager.o bin/display.o bin/event_loop.o bin/group.o bin/mach.o bin/popup.o bin/animation.o bin/workspace.om bin/volume.o -o bin/sketchybar -framework Carbon -framework Cocoa -framework CoreAudio -F/System/Library/PrivateFrameworks -framework SkyLight -framework DisplayServices
ld: framework not found DisplayServices
```

Commit https://github.com/FelixKratz/SketchyBar/commit/ca15ea88fdf1b63c4c4c80452a9e6653217c6df5 introduced DisplayServices framework that's not available in nixpkgs.

**Comment by luxus** [comment]
Thanks for the clarification. Is it possible to add `displayServices`, or is it not because it is a private API?

**Comment by azuwis** [comment]
I'm no expert on apple sdk in nixpkgs, but I think private framework is not a problem.

https://github.com/NixOS/nixpkgs/commit/2c82907da4492bd1dd92815ae82fe1efea6043d3 (part of https://github.com/NixOS/nixpkgs/pull/117780) added SkyLight framework to nixpkgs.

**Comment by azuwis** [comment]
Great work @luxus!

Compiling on x64_64-darwin worked, @toonn can you please have a look at the aarch64-darwin one https://logs.nix.ci/?key=nixos/nixpkgs.203897&attempt_id=7325eab3-9d9f-4df0-8af3-67cca85648f7 ?

```
       >   - /System/Library/PrivateFrameworks/DisplayServices.framework/ -> /nix/store/9j4cdbvb1f48wvkka2vhh88m4kajawrz-apple-private-framework-DisplayServices-11.0.0/Library/Frameworks/DisplayServices.framework/
       > Required prefix: /nix/store
       > Check existence of resulting paths: yes
       >
       > The following paths did not match any rewrite rule
       >   /usr/lib/libobjc.A.dylib
       > libc++abi: terminating with uncaught exception of type rewrite_errors: Rewriting failed
       > /nix/store/k9d1rvl6yl2rw5wxb01z9161d7q8q8iw-stdenv-darwin/setup: line 1419: 10366 Abort trap: 6           rewrite-tbd -p /System/Library/PrivateFrameworks/DisplayServices.framework/:$out/Library/Frameworks/DisplayServices.framework/ -r /nix/store "$tbd"
       For full logs, run 'nix log /nix/store/db5rl5s7hzipswaihwdk03rk5j2x40iv-apple-private-framework-DisplayServices-11.0.0.drv'.
error: 1 dependencies of derivation '/nix/store/kfck819n46zi7425gjp251dbprzrws10-sketchybar-2.11.2.drv' failed to build
```

I have no idea about the error message.

**Review by toonn — APPROVED** [review]
LGTM but I don't have an aarch64-darwin machine.

**Comment by azuwis** [comment]
> Compiling on x64_64-darwin worked, @toonn can you please have a look at the aarch64-darwin one https://logs.nix.ci/?key=nixos/nixpkgs.203897&attempt_id=7325eab3-9d9f-4df0-8af3-67cca85648f7 ?
> 
> ```
>        >   - /System/Library/PrivateFrameworks/DisplayServices.framework/ -> /nix/store/9j4cdbvb1f48wvkka2vhh88m4kajawrz-apple-private-framework-DisplayServices-11.0.0/Library/Frameworks/DisplayServices.framework/
>        > Required prefix: /nix/store
>        > Check existence of resulting paths: yes
>        >
>        > The following paths did not match any rewrite rule
>        >   /usr/lib/libobjc.A.dylib
>        > libc++abi: terminating with uncaught exception of type rewrite_errors: Rewriting failed
>        > /nix/store/k9d1rvl6yl2rw5wxb01z9161d7q8q8iw-stdenv-darwin/setup: line 1419: 10366 Abort trap: 6           rewrite-tbd -p /System/Library/PrivateFrameworks/DisplayServices.framework/:$out/Library/Frameworks/DisplayServices.framework/ -r /nix/store "$tbd"
>        For full logs, run 'nix log /nix/store/db5rl5s7hzipswaihwdk03rk5j2x40iv-apple-private-framework-DisplayServices-11.0.0.drv'.
> error: 1 dependencies of derivation '/nix/store/kfck819n46zi7425gjp251dbprzrws10-sketchybar-2.11.2.drv' failed to build
> ```

The error can be fixed by adding libobjc as dependence to DisplayServices see https://github.com/NixOS/nixpkgs/pull/209260

**Comment by luxus** [comment]
closing it in favour of the new PR #209260

**Pull request closed without merging**
