### PR TITLE
perlPackages.FileMimeInfo: Add missing dependency

### PR DESCRIPTION
**Pull request by wentasah**
Since version 0.30 (2020-10-26), FileMimeInfo depends on Encode::Locale
(see https://metacpan.org/changes/distribution/File-MimeInfo). Without
having this dependency in Nix, mimetype command fails, which can
result in xdg-mime not working properly.

Specifically, under generic desktop environments (i3 in my case),
xdg-mime tries to use the mimetype command, which fails. Then xdg-mime
falls back to using the file command, which often does not detect the
mime type correctly.

###### Motivation for this change

Fixes problems with xdg-mime (see above).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by stigtsp** [comment]
@GrahamcOfBorg build perlPackages.FileMimeInfo

**Review by stigtsp — CHANGES_REQUESTED** [review]
Can you target this against the `staging` branch instead? It triggers a rebuild of chromium and other rather large pagkages.

**Comment by stigtsp** [comment]
@SuperSandro2000 Can I ask you opinion if this needs to go in staging or now?

**Comment by wentasah** [comment]
I changed the base branch. If it turns not to be necessary, let me know and I'll change it back.

**Review by stigtsp — APPROVED** [review]
LGTM

**Pull request merged**
