### PR TITLE
weechatScripts.wee-slack: 2.7.0 -> 2.8.0

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://github.com/wee-slack/wee-slack/releases/tag/v2.8.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by oxzi — COMMENTED** [review]
Thanks for your PR.

After trying applying your changes, `wee-slack` could not be loaded any longer. Due to the stack trace, the `six` module is missing which you have removed within the `patches` thingy.

```
18:30 python: loading script "/nix/store/dxzx1vyq4dzq61pdi9b6f5zm9zs0ghqb-wee-slack-2.8.0/share/wee_slack.py"
18:30 python: stdout/stderr (?): Traceback (most recent call last):
18:30 python: stdout/stderr (?):   File "/nix/store/dxzx1vyq4dzq61pdi9b6f5zm9zs0ghqb-wee-slack-2.8.0/share/wee_slack.py", line 36, in <module>
18:30 python: stdout/stderr (?):     from websocket import (  # noqa: E402
18:30 python: stdout/stderr (?):   File "/nix/store/4xxnwqgakzjvnm38443bbyp13krq9wwp-wee-slack-env/lib/python3.8/site-packages/websocket/__init__.py", line 21, in <module>
18:30 python: stdout/stderr (?):     from ._abnf import *
18:30 python: stdout/stderr (?):   File "/nix/store/4xxnwqgakzjvnm38443bbyp13krq9wwp-wee-slack-env/lib/python3.8/site-packages/websocket/_abnf.py", line 29, in <module>
18:30 python: stdout/stderr (?):     import six
18:30 python: stdout/stderr (?): ModuleNotFoundError: No module named 'six'
18:30 =!= python: unable to parse file "/nix/store/dxzx1vyq4dzq61pdi9b6f5zm9zs0ghqb-wee-slack-2.8.0/share/wee_slack.py"
```

**Comment by mweinelt** [comment]
Ah interesting, I couldn't find six anymore within wee-slack, so I removed it. I didn't expect six not to be propagated. I'll add it back.

**Comment by oxzi** [comment]
I have successfully tested loading the script by `nix-shell -p '(weechat.override { configure = {...}: { scripts = [ weechatScripts.wee-slack ]; };})'` instead of deploying it on my server this time :^)

**Review by bdesham — APPROVED** [review]
I don’t have a setup suitable for testing this at the moment, but the changes seem reasonable to me. Thanks!

**Pull request merged**
