### PR TITLE
treewide: pin failing packages to openssl_1_1

### PR DESCRIPTION
**Pull request by anthonyroussel**
###### Description of changes

Pin to openssl_1_1 the following packages on staging-next PR:

* perl534Packages.ZonemasterLDNS
* movine
* kore
* journaldriver
* espanso
* cfdyndns
* cargo-raze
* cargo-dephell
* cargo-bisect-rustc
* break-time
* bip
* archiveopteryx
* hadoop
* mrustc-bootstrap
* nfd
* sslsplit
* tremor-rs
* tensorman
* taizen
* synapse-bt
* spotify-tui
* ndn-tools
* ndn-cxx
* shticker-book-unwritten
* rucredstash
* quill
* netease-music-tui
* paperoni
* mdbook-plantuml
* imag
* hydra-cli
* hash_extender
* habitat
* gmnisrv
* git-series
* finalfrontier
* devserver
* cliscord
* coinlive
* xbps
* eidolon
* wkhtmltopdf-bin
* tunnelto
* chit

Fix the failing build in staging-next PR: https://github.com/NixOS/nixpkgs/pull/188284

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by anthonyroussel** [comment]
@ofborg build espanso

**Comment by ajs124** [comment]
I didn't think I'd missed quite that many packages… sorry. Thanks for taking care of this.

**Comment by anthonyroussel** [comment]
> I didn't think I'd missed quite that many packages… sorry. Thanks for taking care of this.

No problem, don't worry :)

**Comment by anthonyroussel** [comment]
I tried to fix as many packages as possible by pinning openssl to 1.1.

I will stop here with my PR, because there are too many packages.

I propose that we do a review of all this, merge, and see the result on Hydra in a few days.
What do you think?

**Review by qbit — APPROVED** [review]
perl534Packages.ZonemasterLDNS seems fine with this!

**Comment by ajs124** [comment]
Result of `nixpkgs-review pr 190667` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>spark2</li>
    <li>spark_2_4</li>
  </ul>
</details>
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>cargo-raze</li>
    <li>mrustc-bootstrap</li>
    <li>tremor-rs</li>
  </ul>
</details>
<details>
  <summary>53 packages built:</summary>
  <ul>
    <li>archiveopteryx</li>
    <li>bip</li>
    <li>break-time</li>
    <li>cargo-bisect-rustc</li>
    <li>cargo-dephell</li>
    <li>cfdyndns</li>
    <li>chit</li>
    <li>cliscord</li>
    <li>coinlive</li>
    <li>devserver</li>
    <li>eidolon</li>
    <li>espanso</li>
    <li>finalfrontier</li>
    <li>git-series</li>
    <li>gmnisrv</li>
    <li>habitat</li>
    <li>hadoop (hadoop3 ,hadoop_3_3)</li>
    <li>hash_extender</li>
    <li>hydra-cli</li>
    <li>imag</li>
    <li>journaldriver</li>
    <li>kore</li>
    <li>mdbook-plantuml</li>
    <li>movine</li>
    <li>ndn-cxx</li>
    <li>ndn-tools</li>
    <li>netease-music-tui</li>
    <li>nfd</li>
    <li>paperoni</li>
    <li>perl534Packages.ZonemasterCLI</li>
    <li>perl534Packages.ZonemasterEngine</li>
    <li>perl534Packages.ZonemasterLDNS</li>
    <li>zonemaster-cli (perl536Packages.ZonemasterCLI)</li>
    <li>perl536Packages.ZonemasterEngine</li>
    <li>perl536Packages.ZonemasterLDNS</li>
    <li>pig</li>
    <li>python310Packages.dask-yarn</li>
    <li>python310Packages.skein</li>
    <li>python39Packages.dask-yarn</li>
    <li>python39Packages.skein</li>
    <li>quill</li>
    <li>rucredstash</li>
    <li>shticker-book-unwritten</li>
    <li>spark (spark3 ,spark_3_2)</li>
    <li>spark_3_1</li>
    <li>spotify-tui</li>
    <li>sslsplit</li>
    <li>synapse-bt</li>
    <li>taizen</li>
    <li>tensorman</li>
    <li>tunnelto</li>
    <li>wkhtmltopdf-bin</li>
    <li>xbps</li>
  </ul>
</details>

**Comment by ajs124** [comment]
```diff
diff --git a/pkgs/development/compilers/mrustc/bootstrap.nix b/pkgs/development/compilers/mrustc/bootstrap.nix
index 85b328848b1..70249fed66b 100644
--- a/pkgs/development/compilers/mrustc/bootstrap.nix
+++ b/pkgs/development/compilers/mrustc/bootstrap.nix
@@ -71,7 +71,7 @@ stdenv.mkDerivation rec {
     # for rustc
     llvm_7 libffi zlib libxml2
     # for cargo
-    openssl curl
+    openssl (curl.override { inherit openssl; })
   ];
 
   makeFlags = [
```
should fix `mrustc-bootstrap`

**Comment by anthonyroussel** [comment]
@ofborg build cargo-raze mrustc-bootstrap tremor-rs

**Pull request merged**
