### PR TITLE
thunderbird: Add gpg/gpgme dependencies to fix smartcard usage

### LINKED ISSUE #98765: thunderbird@78: enable smartcard gpg support
**Describe the bug**
The "new" thunderbird@78 has native support for gpg now. 

**To Reproduce**
1. install thunderbird@78
2. [configure the gpg key manually](https://wiki.mozilla.org/Thunderbird:OpenPGP:Smartcards#Configure_an_email_account_to_use_an_external_GnuPG_key)
3. the mail encryption doesn't work

**Expected behavior**
It should support gpg smartcards or at least have an option to install [all needed dependencies](https://wiki.mozilla.org/Thunderbird:OpenPGP:Smartcards#Install_GnuPG_and_GPGME) (*gpgme*).

**Notify maintainers**
@eelco
@lovesegfault
@pierron
@vcunat

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.10, NixOS, 21.03pre244045.1179840f9a8 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre244045.1179840f9a8"`
 - channels(thomas): `"nixpkgs-21.03pre243895.72b9660dc18"`
 - nixpkgs: `/home/thomas/.nix-defexpr/channels/nixpkgs`

### PR DESCRIPTION
**Pull request by nh2**
###### Motivation for this change

Fixes #98765.

This enables to configure Thunderbird to use gnupg directly, which is the
official upstream recommendation when using GPG with smartcards, which are not
yet supported by Thunderbird's native GPG support.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
     - [x] `master` @ fe8f5586d5955dca0207d76b1514fba8efb257aa
     - [x] I've tested on NixOS 20.09 but not yet on `master`
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
  - `576 MB` -> `599 MB`
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nh2** [comment]
Tested on `master` as well now, works well for me.

**Comment by taku0** [comment]
Could you also add them to `thunderbird-bin`?

**Comment by nh2** [comment]
> Could you also add them to `thunderbird-bin`?

@taku0 Done, and it works for me as well.

I've also added a small refactoring commit sort the import lists, which should not change the eval.

**Review by lovesegfault — APPROVED** [review]
WFM

**Review by taku0 — APPROVED** [review]
LGTM

**Pull request merged**
