### PR TITLE
edgedb: 5.2.3 -> 5.3.0

### LINKED ISSUE #341122: Update request: edgedb 5.2.3 -> 5.3.0
- Package name: edgedb
- Latest released version: 5.3

- Current version on the unstable channel: 4.1.1
- Current version on the stable/release channel: 5.2.3

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@ahirner @kirillrdy 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by NotAShelf**
## Description of changes

Update edgedb from `5.2.3` to `5.3.0`, use `refs/tags` for tag version.

Closes #341122

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See
  [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests)
    (look inside
    [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or
    [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in
    [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or
    [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are
    [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package)
    to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using
      `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all
      changes have to be committed, also see
      [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in
      `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md)
  (or backporting
  [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md)
  and
  [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md)
  Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or
        breaking
  - [ ] (Module updates) Added a release notes entry if the change is
        significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS
        module
- [x] Fits
      [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by ahirner — CHANGES_REQUESTED** [review]
Looks and works well. Tested on darwin x86.

>  [Contributing.md]: ... a reference to the relevant release notes/changelog

Please add them in the commit body. Example: https://github.com/NixOS/nixpkgs/pull/333155/commits/648806da1f2eb4e70e9d1d88847c0377722643f0

**Comment by NotAShelf** [comment]
> Looks and works well. Tested on darwin x86.
> 
> > [Contributing.md]: ... a reference to the relevant release notes/changelog
> 
> Please add them in the commit body. Example: [648806d](https://github.com/NixOS/nixpkgs/commit/648806da1f2eb4e70e9d1d88847c0377722643f0)



> Looks and works well. Tested on darwin x86.
> 
> > [Contributing.md]: ... a reference to the relevant release notes/changelog
> 
> Please add them in the commit body. Example: [648806d](https://github.com/NixOS/nixpkgs/commit/648806da1f2eb4e70e9d1d88847c0377722643f0)

I don't think this is a necessity...

**Comment by kirillrdy** [comment]
greetings @NotAShelf 

> 
> I don't think this is a necessity...

https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions

specifically 

> (Motivation for change. Link to release notes. Additional information.)

for smaller releases link to a diff is also common

**Comment by NotAShelf** [comment]
This will be the first time I have ever included, or have seen someone include a link to the diff in the commit description...

 I've included a link.

**Comment by kirillrdy** [comment]
@NotAShelf nixpkgs is a huge project, and it's hard for everyone to be across everything, but we try to do our best !

you can try something like this to see how other contributors add metadata to commit message 

```
git log -n 1000 | grep -i -e "diff" -e "changelog" -e "release" 
```

**Review by ahirner — APPROVED** [review]

**Pull request merged**
