### PR TITLE
Zotero: Fix to use patchelf instead of FHS Env.

### PR DESCRIPTION
**Pull request by jpathy**
Don't use buildFHSUserEnv and use patchelf to fix up the binary and libs. This should fix issue #48814.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by timor** [comment]
Thanks for this great patch!

I tested this:
- 19.03: builds
- 18.09: builds and runs (from command line)

I encountered one issue, though:  The desktop item which is copied from the upstream source does not work.  It does not start (the exec entry is trying to be clever), and the icon is also missing (which could be a kde issue on my setup, though)

**Comment by jpathy** [comment]
I don't use a DE, so i didn't know the desktop file was broken. It should be fixed now. Let me know if it works for you. Thanks.

**Comment by timor** [comment]
It works now.

**Review by tomberek — APPROVED** [review]
Builds, runs, no reverse dependencies. Another user confirms proper behavior. This is a step away from FHS and towards native nix packaging.

**Pull request merged**
