### PR TITLE
ghc841:  semi-automated updates

### PR DESCRIPTION
**Pull request by deepfire**
- interned the manual changes to the GHC 8.4 package set (except the `markBroken` things, which are maintained as plaintext)
- dropped stale overrides
- new fixes

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by deepfire** [comment]
cc @peti

**Review by peti — CHANGES_REQUESTED** [review]
There are merge conflicts with current master, I'm afraid.

**Comment by peti** [comment]
@deepfire, I've given you push access to https://github.com/peti/nixpkgs. The `haskell-updates` branch in that repository is updated automatically to have the latest packages from Stackage LTS 10.x and Hackage (for those packages not found in Stackage), and it's continuously built at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates. If you'd like to, then you can push those kind of updates directly to that branch and have them test-built. Also, this approach avoids merge conflicts with changes I do in that branch in the mean time, like it has happened with this PR.

**Comment by deepfire** [comment]
@peti, I see -- thank you!

Fixed the conflicts.

**Review by peti — APPROVED** [review]

**Pull request merged**
