### PR TITLE
nixops: fix

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc @NixOS/nixops-committers

### CODE REVIEW

**Comment by roberth** [comment]
@ofborg build nixops

**Comment by jonringer** [comment]
nixops already has a few dependencies vendored. can we just move these packages into the nixops directory.?

**Comment by dotlambda** [comment]
> nixops already has a few dependencies vendored. can we just move these packages into the nixops directory.?

Why would wie? These are the last packages supporting Python 2 and I'm pretty sure nixops will be removed from Nixpkgs at the same time as python2.

**Comment by dotlambda** [comment]
I guess a downside to not vendoring them is that the following packages are re-enabled by this PR:
> 24 packages added:
> bitbucket-cli (init at 0.5.1) buttersink (init at 0.6.9) collectd (init at 5.12.0) collectd-data (init at 5.12.0) dir2opus (init at 0.12.2) fmbt (init at 0.42) libvmi (init at 0.12.0) mongodb (init at 3.4.24) mongodb-3_4 (init at 3.4.24) mongodb-3_6 (init at 3.6.23) mongodb-4_0 (init at 4.0.27) nixops (init at 1.7) opae (init at 1.0.0) pyditz (init at 0.11) qemu_xen_4_10 (init at 6.1.0) qemu_xen_4_10-light (init at 6.1.0) qemu_xen-light (init at 6.1.0) qemu_xen (init at 6.1.0) qubes-core-vchan-xen (init at 4.1.4) split2flac (init at 122) workrave (init at 1.10.31) xen-slim (init at 4.10.4) xen-light (init at 4.10.4) xen (init at 4.10.4)

**Comment by jonringer** [comment]
> > nixops already has a few dependencies vendored. can we just move these packages into the nixops directory.?
> 
> Why would we? These are the last versions supporting Python 2 and I'm pretty sure nixops will be removed from Nixpkgs at the same time as python2.

I prioritize getting rid of python2 over getting rid of nixops. I really want to see python2 go away.

**Comment by jonringer** [comment]
> > nixops already has a few dependencies vendored. can we just move these packages into the nixops directory.?
> 
> Why would we? These are the last versions supporting Python 2 and I'm pretty sure nixops will be removed from Nixpkgs at the same time as python2.

We've been "close to releasing nixops v2" for 18+ months... I don't think there's a huge desire to get nixops2 out the door, when most of the active contributors just use nixopsUnstable anyway.

**Comment by adisbladis** [comment]
I missed this PR and went ahead with https://github.com/NixOS/nixpkgs/pull/154715 which I think is a better solution anyway since it decouples NixOps from what goes on in `python2.pkgs` and prevents future breakage.

**Comment by adisbladis** [comment]
Additionally I think that #154715 can serve as a template for how to deal with remaining Python2 closures and limit their impact for the rest of nixpkgs.

**Pull request closed without merging**
