### PR TITLE
mudlet version

### PR DESCRIPTION
**Pull request by alicerum**
Mudlet 3.0 has gone delta

### CODE REVIEW

**Comment by lethalman** [comment]
I expect the version to change in this nix expression. Why did you change tarball and not the version?

**Comment by wyvie** [comment]
It's the same pre-3.0 version, just another, more stable in bugless build.
Still waiting for official 3.0 to come. Do you think that might be better to be of version 3.0-delta or anything?

**Comment by iyzsong** [comment]
Yes, I think:
  * set version to `3.0.0-delta`
  * and set url to `https://github.com/Mudlet/Mudlet/archive/Mudlet-3.0.0-delta.tar.gz`

is more clear.

**Comment by wyvie** [comment]
@iyzsong @lethalman fixed!

**Comment by iyzsong** [comment]
Thanks!

**Pull request merged**
