### PR TITLE
haskellPackages.yarn2nix: unbreak build

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

@peti really forced my hand by marking this as unbroken. This override fixes two new compilation errors related to dependencies since 0.8.0:

* regex-tdfa-text has been merged into regex-tdfa, so we just remove the dependency on the former which is broken by now in haskellPackages.
* protolude 0.3 changed the interface for string conversion which breaks one module of yarn2nix. We can fix this by applying my patch for bumping the pinned nixpkgs version in the development version of yarn2nx.
* A lot of bounds can be safely ignored via jailbreak

Currently this doesn't evaluate because hnix doesn't evaluate in `haskell-updates`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
See #114422

**Comment by cdepillabout** [comment]
I merged #114422 in, and rebased this on it.

@GrahamcOfBorg build haskellPackages.yarn2nix

**Comment by cdepillabout** [comment]
Building on Linux, looks good to me!

Thanks again

**Pull request merged**
