### PR TITLE
codeblocks: fix builds

### PR DESCRIPTION
**Pull request by wegank**
###### Motivation for this change

This pull request allows codeblocks to be built on all four platforms.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mindavi** [comment]
I'm afraid this is not enough anymore since the gcc11 bump. Do you want to take another look?

https://hydra.nixos.org/build/174836160/nixlog/1

**Comment by wegank** [comment]
@Mindavi Setting `-std=c++14` suffices. I'm checking if applying [this](https://sourceforge.net/p/codeblocks/code/12303/) patch also works.

**Comment by Mindavi** [comment]
cc @linquize (long shot since they don't seem to be active in nixpkgs anymore).

**Comment by Artturin** [comment]
please submit the patches upstream and fetchpatch them

**Comment by wegank** [comment]
@Artturin The commit now uses patches from an unofficial mirror. The upstream is on SourceForge SVN, and I don't know of any way to fetch patches from it.

**Review by minijackson — APPROVED** [review]
From my small research, it seems in nixpkgs fetchpatch from sourceforge is mainly used for fetching patches that are on the forum or other resources in sourceforge, but I haven't found a fetchpatch that fetches from a Git / SVN commit, so I think it should be fine as-is.

This fixes two [Hydra](https://hydra.nixos.org/build/175336728) [builds](https://hydra.nixos.org/build/175365973), so I'm linking this here: 

ZHF: #172160

---

Result of `nixpkgs-review pr 154076` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>codeblocks</li>
    <li>codeblocksFull</li>
  </ul>
</details>

**Pull request merged**
