### PR TITLE
Update Haskell package set to Stackage Nightly 2021-03-21 (plus other fixes)

### PR DESCRIPTION
**Pull request by peti**
This PR is test-built by Hydra at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates. I'll fix up the remaining errors and merge it on **Friday, 2021-04-02 20:00 UTC+2**. Everyone can participate in that process live on Twitch at https://www.twitch.tv/peti343. In addition to the chat features offered by Twitch, there is also a voice conference at https://discord.gg/YTEa3XR viewers can use to chat with me and with each other.

### CODE REVIEW

**Comment by sorki** [comment]
I went thru
- `arbtt` (released with bumped testsuite deps as 0.11 - https://github.com/nomeata/arbtt/pull/54)
- `darcs` (cryptonite dep bump patch emailed upstream)
- `co-log` https://github.com/kowainik/co-log/pull/218
- `nix-diff` https://github.com/Gabriel439/nix-diff/pull/36

Tomorrow I'll take a look at `github`, `niv` and possibly `diagrams` if no one beats me to it.

**Comment by sternenseemann** [comment]
niv has been fixed on `master` (#117023), we should port the fix to `haskell-updates` or merge `master` into here.

Also wondering whether it might be the lesser evil to downgrade optparse-applicative?

**Comment by sorki** [comment]
Ideally we patch things (especially easy ones) upstream. 

`optparse-applicative` downgrade sounds evil to me, there are packages that handled that before it landed in stackage nightly so I would rather deal with the fallout of the remaining few broken (similar to `base16-bytestring` = 1). Also some like `nix-diff` were not affected by the API changes and needed just a version bump.

**Comment by sternenseemann** [comment]
Wasn't sure if it was in stackage, if the version comes from stackage we should stick to it if we can, agreed!

**Comment by sternenseemann** [comment]
> darcs (cryptonite dep bump patch emailed upstream)

Would you mind making a PR for master with the fixed darcs and a hackage set update? A broken `darcs` on master sounds like something we would like to avoid.

**Comment by sorki** [comment]
> > darcs (cryptonite dep bump patch emailed upstream)
> 
> Would you mind making a PR for master with the fixed darcs and a hackage set update? A broken `darcs` on master sounds like something we would like to avoid.

Not at all. Should be just a jailbreak. I have couple more fixes to PR as well.

Broken darcs is pretty bad since you can't clone darcs repo to fix it.. :smile:

**Comment by sternenseemann** [comment]
> Broken darcs is pretty bad since you can't clone darcs repo to fix it.. smile

I've fixed darcs on master as it feels critical enough to warrant this kind of thing :) Sorry for the ensuing merge conflict, hope it's not too much trouble.

Fix for haskell-updates is #117296, I'm hoping we'll get an upstream issue tracker or patch URL until we merge.

**Comment by maralorn** [comment]
So, do we do a blind merge today because we don‘t have hydra or do we postpone until next week?

**Comment by peti** [comment]
> So, do we do a blind merge today because we don‘t have hydra or do we postpone until next week?

I'd say we postpone. I have an important event tomorrow morning early at 8am and I don't feel like working on this merge without build results and without a binary cache. We have done that before and it typically takes 3-4 hours to complete. That's too late for me tonight. So I'd rather merge the branch next Friday.

**Comment by peti** [comment]
I am tempted to schedule the next merge attempt on *Thursday*, though, so that we could do it on April 1st. That might be an opportunity to have some fun. :grin:

**Comment by sternenseemann** [comment]
> I'd say we postpone. I have an important event tomorrow morning early at 8am and I don't feel like working on this merge without build results and without a binary cache. We have done that before and it typically takes 3-4 hours to complete. That's too late for me tonight. So I'd rather merge the branch next Friday.

That is what I'd have suggested as well :) Bit sad for all the fixes we accumulated, but seems like the next few days are gonna be rebuild plagued anyways.

**Comment by sternenseemann** [comment]
> Friday, 2021-04-02 20:00 UTC+1

Gonna be UTC+2 today, presumably?

**Comment by peti** [comment]
> > Friday, 2021-04-02 20:00 UTC+1
> 
> Gonna be UTC+2 today, presumably?

Yeah, that's true. Good catch!

**Comment by peti** [comment]
We will merge https://github.com/NixOS/nixpkgs/pull/118350 next week.

**Pull request merged**
