### PR TITLE
[21.05] navidrome: 0.42.1 -> 0.43.0

### PR DESCRIPTION
**Pull request by vs49688**
(cherry picked from commit 88305beb434f799d70d1d69dc8f9909c5d67fb06)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
is there any breaking changes?

**Comment by jonringer** [comment]
I guess it doesn't really matter since we have officially released

**Comment by jonringer** [comment]
Please link to a changelog when doing backports (or the original PR) https://github.com/navidrome/navidrome/releases/tag/v0.43.0

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 124384 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>1 package built:</summary>  <ul>    <li>navidrome</li>  </ul></details>

**Comment by vs49688** [comment]
Woah, sorry only just saw these now. There's no breaking changes as far as I can tell. I'm running this on my own box with no problems.

**Pull request merged**
