### PR TITLE
SDL2_mixer: 2.0.4 -> 2.6.3

### PR DESCRIPTION
**Pull request by superherointj**
SDL2_mixer: 2.0.4 -> 2.6.3

Release: https://github.com/libsdl-org/SDL_mixer/releases/tag/release-2.6.3

* Refactor: Re-ordered `configureFlags` to respect phases order.

Downstream breakage:
* lzwolf: pinning SDL2_mixer to 2.0.4 until next upgrade.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin

### CODE REVIEW

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 218646` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.rl-coach</li>
  </ul>
</details>
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>appimage-run-tests</li>
  </ul>
</details>
<details>
  <summary>13 packages failed to build:</summary>
  <ul>
    <li>d1x-rebirth-full</li>
    <li>d2x-rebirth-full</li>
    <li>frogatto</li>
    <li>lzwolf</li>
    <li>manaplus</li>
    <li>pureref</li>
    <li>python311Packages.pyautogui</li>
    <li>python311Packages.pygame</li>
    <li>python311Packages.pygame-gui</li>
    <li>python311Packages.pygetwindow</li>
    <li>python311Packages.pyrect</li>
    <li>python311Packages.pytmx</li>
    <li>worldofgoo</li>
  </ul>
</details>
<details>
  <summary>180 packages built:</summary>
  <ul>
    <li>SDL2_mixer</li>
    <li>Sylk</li>
    <li>_1oom</li>
    <li>_20kly</li>
    <li>abbaye-des-morts</li>
    <li>altair</li>
    <li>anki-bin</li>
    <li>anytype</li>
    <li>appimage-run</li>
    <li>augustus</li>
    <li>beekeeper-studio</li>
    <li>betterdiscord-installer</li>
    <li>blobwars</li>
    <li>blockattack</li>
    <li>bloomrpc</li>
    <li>bootstrap-studio</li>
    <li>brutalmaze</li>
    <li>buttercup-desktop</li>
    <li>caprine-bin</li>
    <li>cataclysm-dda</li>
    <li>cataclysm-dda-git</li>
    <li>cdogs-sdl</li>
    <li>chocolateDoom</li>
    <li>chromium-bsu</li>
    <li>chrysalis</li>
    <li>cider</li>
    <li>commandergenius</li>
    <li>cozy-drive</li>
    <li>craftos-pc</li>
    <li>crawlTiles</li>
    <li>crispyDoom</li>
    <li>crypto-org-wallet</li>
    <li>devdocs-desktop</li>
    <li>dxx-rebirth</li>
    <li>ecwolf</li>
    <li>eduke32</li>
    <li>electron-mail</li>
    <li>electronplayer</li>
    <li>endgame-singularity</li>
    <li>enigma</li>
    <li>eternity</li>
    <li>fheroes2</li>
    <li>firefly-desktop</li>
    <li>flare</li>
    <li>flexoptix-app</li>
    <li>fluent-reader</li>
    <li>framesh</li>
    <li>freeciv</li>
    <li>freeciv_qt</li>
    <li>freeciv_sdl2</li>
    <li>frescobaldi</li>
    <li>fspy</li>
    <li>gemrb</li>
    <li>guile-sdl2</li>
    <li>hedgewars</li>
    <li>infra-arcana</li>
    <li>instead</li>
    <li>instead-launcher</li>
    <li>irccloud</li>
    <li>ivan</li>
    <li>joplin-desktop</li>
    <li>julius</li>
    <li>jumpnbump</li>
    <li>keet</li>
    <li>kodiPackages.steam-launcher</li>
    <li>lbreakouthd</li>
    <li>lbry</li>
    <li>ldtk</li>
    <li>ledger-live-desktop</li>
    <li>lens</li>
    <li>liberal-crime-squad</li>
    <li>lightspark</li>
    <li>lincity_ng</li>
    <li>logseq</li>
    <li>losslesscut-bin</li>
    <li>lpairs2</li>
    <li>lunar-client</li>
    <li>lutris</li>
    <li>mar1d</li>
    <li>marktext</li>
    <li>mathpix-snipping-tool</li>
    <li>mendeley</li>
    <li>methane</li>
    <li>minigalaxy</li>
    <li>mobilecoin-wallet</li>
    <li>molotov</li>
    <li>motrix</li>
    <li>museeks</li>
    <li>mycrypto</li>
    <li>neo4j-desktop</li>
    <li>notable</li>
    <li>notion-app-enhanced</li>
    <li>np2kai</li>
    <li>nsz (python310Packages.nsz)</li>
    <li>nuclear</li>
    <li>nxengine-evo</li>
    <li>ocamlPackages.tsdl-mixer</li>
    <li>octant-desktop</li>
    <li>opendune</li>
    <li>opensupaplex</li>
    <li>osu-lazer-bin</li>
    <li>p3x-onenote</li>
    <li>passky-desktop</li>
    <li>pingus</li>
    <li>playonlinux</li>
    <li>plexamp</li>
    <li>polypane</li>
    <li>prboom-plus</li>
    <li>protontricks</li>
    <li>protonup-qt</li>
    <li>pysolfc</li>
    <li>python310Packages.kivy</li>
    <li>python310Packages.pyautogui</li>
    <li>python310Packages.pygame</li>
    <li>python310Packages.pygame-gui</li>
    <li>python310Packages.pygame_sdl2</li>
    <li>python310Packages.pygetwindow</li>
    <li>python310Packages.pyrect</li>
    <li>python310Packages.pysdl2</li>
    <li>python310Packages.pytmx</li>
    <li>python311Packages.kivy</li>
    <li>python311Packages.nsz</li>
    <li>python311Packages.pygame_sdl2</li>
    <li>python311Packages.pysdl2</li>
    <li>radicle-upstream</li>
    <li>rambox</li>
    <li>raven-reader</li>
    <li>redeclipse</li>
    <li>remnote</li>
    <li>renpy</li>
    <li>rocksndiamonds</li>
    <li>ryujinx</li>
    <li>saleae-logic-2</li>
    <li>sauerbraten</li>
    <li>session-desktop</li>
    <li>sfrotz</li>
    <li>sonixd</li>
    <li>space-cadet-pinball</li>
    <li>srb2</li>
    <li>srb2kart</li>
    <li>ssb-patchwork</li>
    <li>standardnotes</li>
    <li>station</li>
    <li>steam</li>
    <li>steam-rom-manager</li>
    <li>steam-run</li>
    <li>steam-small</li>
    <li>steam-tui</li>
    <li>steamcmd</li>
    <li>steamos-devkit</li>
    <li>taisei</li>
    <li>tauon</li>
    <li>the-legend-of-edgar</li>
    <li>timeular</li>
    <li>toppler</li>
    <li>trackballs</li>
    <li>trezor-suite</li>
    <li>tusk</li>
    <li>uhk-agent</li>
    <li>uhk-udev-rules</li>
    <li>ultrastardx</li>
    <li>unityhub</li>
    <li>vcmi</li>
    <li>vengi-tools</li>
    <li>via</li>
    <li>vial</li>
    <li>video2midi</li>
    <li>vvvvvv</li>
    <li>wargus</li>
    <li>wesnoth</li>
    <li>widelands</li>
    <li>wootility</li>
    <li>wpsoffice</li>
    <li>wpsoffice-cn</li>
    <li>xivlauncher</li>
    <li>youtube-music</li>
    <li>ytmdesktop</li>
    <li>zecwallet-lite</li>
    <li>zettlr</li>
    <li>zulip</li>
  </ul>
</details>

**Comment by superherointj** [comment]
@wegank Eval was good. Everything is green.

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 218646` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>22 packages marked as broken and skipped:</summary>
  <ul>
    <li>augustus</li>
    <li>blockattack</li>
    <li>brutalmaze</li>
    <li>cdogs-sdl</li>
    <li>chromium-bsu</li>
    <li>enigma</li>
    <li>frescobaldi</li>
    <li>julius</li>
    <li>lbreakouthd</li>
    <li>lpairs2</li>
    <li>python310Packages.pyautogui</li>
    <li>python310Packages.pytmx</li>
    <li>python310Packages.rl-coach</li>
    <li>python311Packages.pyautogui</li>
    <li>python311Packages.pygame</li>
    <li>python311Packages.pygame-gui</li>
    <li>python311Packages.pygetwindow</li>
    <li>python311Packages.pyrect</li>
    <li>python311Packages.pytmx</li>
    <li>taisei</li>
    <li>the-legend-of-edgar</li>
    <li>toppler</li>
  </ul>
</details>
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>eduke32</li>
    <li>nsz (python310Packages.nsz)</li>
    <li>python310Packages.kivy</li>
    <li>python310Packages.pygame-gui</li>
    <li>python311Packages.kivy</li>
    <li>python311Packages.nsz</li>
  </ul>
</details>
<details>
  <summary>28 packages built:</summary>
  <ul>
    <li>SDL2_mixer</li>
    <li>SDL2_mixer_2_0</li>
    <li>_20kly</li>
    <li>blobwars</li>
    <li>cataclysm-dda</li>
    <li>cataclysm-dda-git</li>
    <li>crawlTiles</li>
    <li>crispyDoom</li>
    <li>ecwolf</li>
    <li>endgame-singularity</li>
    <li>flare</li>
    <li>guile-sdl2</li>
    <li>jumpnbump</li>
    <li>liberal-crime-squad</li>
    <li>mar1d</li>
    <li>pysolfc</li>
    <li>python310Packages.pygame</li>
    <li>python310Packages.pygame_sdl2</li>
    <li>python310Packages.pygetwindow</li>
    <li>python310Packages.pyrect</li>
    <li>python310Packages.pysdl2</li>
    <li>python311Packages.pygame_sdl2</li>
    <li>python311Packages.pysdl2</li>
    <li>space-cadet-pinball</li>
    <li>steamos-devkit</li>
    <li>vengi-tools</li>
    <li>vvvvvv</li>
    <li>wesnoth (wesnoth-dev)</li>
  </ul>
</details>

**Comment by superherointj** [comment]
Are these packages building in master for Darwin?

**Comment by superherointj** [comment]
@wegank Thanks !

**Pull request merged**
