### PR TITLE
github-runner: 2.284.0 -> 2.285.1

### PR DESCRIPTION
**Pull request by veehaitch**
###### Motivation for this change

Update the GitHub Actions Runner to the [v2.285.0 release](https://github.com/actions/runner/releases/tag/v2.285.0).

Adds support for Node.js 16.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veehaitch** [comment]
Result of `nixpkgs-review pr 148342` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>github-runner</li>
  </ul>
</details>

**Comment by veehaitch** [comment]
Didn't test an action yet which actually requires Node.js 16:

https://github.com/actions/runner/blob/a519f96a410a10c4be6e38e8249d33a9b25f716b/src/Test/TestData/node16action.yml#L18-L19

**Comment by veehaitch** [comment]
The [ofborg build on `aarch64-linux`]((https://logs.nix.ci/?key=nixos/nixpkgs.148342&attempt_id=2f0e64bf-be85-4a66-8f65-2950bb8a62c7)) did not succeed due to a failing test:

```
  [xUnit.net 00:00:03.68]     GitHub.Runner.Common.Tests.Worker.StepHostL0.DetermineNodeRuntimeVersionInAlpineContainerAsync [FAIL]
    X GitHub.Runner.Common.Tests.Worker.StepHostL0.DetermineNodeRuntimeVersionInAlpineContainerAsync [9ms]
EXEC : error Message:  [/build/source/src/dir.proj]
     System.NotSupportedException : JavaScript Actions in Alpine containers are only supported on x64 Linux runners. Detected Linux Arm64
    Stack Trace:
       at GitHub.Runner.Worker.Handlers.ContainerStepHost.DetermineNodeRuntimeVersion(IExecutionContext executionContext, String preferredVersion) in /build/source/src/Runner.Worker/Handlers/StepHost.cs:line 149
     at GitHub.Runner.Common.Tests.Worker.StepHostL0.DetermineNodeRuntimeVersionInAlpineContainerAsync() in /build/source/src/Test/L0/Worker/StepHostL0.cs:line 75
  --- End of stack trace from previous location where exception was thrown ---
```

Ignored the respective test.

**Review by newAM — APPROVED** [review]
Works on aarch64-linux, thanks for updating this!

**Comment by veehaitch** [comment]
Meanwhile, v2.285.1 has been released: https://github.com/actions/runner/releases/tag/v2.285.1

**Review by newAM — APPROVED** [review]
Still works on aarch64-linux

**Pull request merged**
