### PR TITLE
pythonPackages.ncclient: refactor + init pythonPackages.selectors2

### PR DESCRIPTION
**Pull request by costrouc**
###### Motivation for this change

18.09 Zero Hydra Failures #45960

###### Things done

ncclient fails to build due to new dependency. adding selectors2 as dependency of ncclient. Added recently 20 days ago in August. https://github.com/ncclient/ncclient/commit/8ef20f282877097c8f51604679277db49c39f80c

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build python27Packages.ncclient python36Packages.ncclient

**Comment by xeji** [comment]
@GrahamcOfBorg build python36Packages.selectors2 python27Packages.selectors2

**Comment by costrouc** [comment]
Looks like this could be fixed with a `sed` replacement. It is a variable that is set within the python code itself. https://github.com/SethMichaelLarson/selectors2/blob/master/tests/support.py#L16 

I don't think that it is changeable via the command line. Do you think it is appropriate to use a `sed` replacement for a patch on the test?

**Comment by xeji** [comment]
These are timing tests, this is  very machine dependent and non-deterministic and will be pretty useless on Hydra. So I think we should disable them completely. Upstream does that for Travis CI too:  https://github.com/SethMichaelLarson/selectors2/blob/master/tests/support.py#L135

Looks like an easy way for us to do the same without patching is to set a `TRAVIS` environment variable in `checkPhase`:  https://github.com/SethMichaelLarson/selectors2/blob/master/tests/support.py#L21.

**Comment by xeji** [comment]
@GrahamcOfBorg build python36Packages.selectors2 python27Packages.selectors2 python27Packages.ncclient

**Comment by xeji** [comment]
Thank you!

**Comment by xeji** [comment]
backported: 010fc6b7621 and 17e17700e27

**Pull request merged**
