### PR TITLE
open-vm-tools: 10.3.10 -> 11.0.1

### PR DESCRIPTION
**Pull request by CheariX**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @joamaki

### CODE REVIEW

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build open-vm-tools

**Comment by aanderse** [comment]
Didn't someone from the NixOS community try to upstream changes like this at one point? @peterhoeg do you have any recollection on that?

**Comment by worldofpeace** [comment]
Oh, it's has been a while and I forgot to merge this patch.

**Comment by worldofpeace** [comment]
> Didn't someone from the NixOS community try to upstream changes like this at one point?

I also see no reason why such a patch ever could be rejected, if it was.
If I were the maintainer I'd merge it with swiftness :smile:

**Review by worldofpeace — APPROVED** [review]
LGTM, I've taken the liberty to rewrite your commit messages to match our guidelines.
Just waiting on eval now (just cuz).

**Comment by peterhoeg** [comment]
We cannot claim `/etc/os-release` ref https://github.com/vmware/open-vm-tools/pull/35#issuecomment-226100905 for NixOS (well, we can if we do the patching on our side but it will not be accepted by upstream).

Upstream is terribly non-responsive as a proper fix was discussed in 2015 by @wmertens which to this date hasn't been even been acknowledged.

**Comment by aanderse** [comment]
Thanks @peterhoeg! Thanks @CheariX!

**Pull request merged**
