### PR TITLE
Fix cloudflare tunnel ignored attrs

### PR DESCRIPTION
**Pull request by mzabani**
###### Description of changes

This PR:

- Fixes the fact that the `originRequest` attrset was previously ignored.
- Documents that credentialsPath needs to be accessible to the right user, even if it might be obvious to most
- Removes warp-routing as it was apparently unused (and I don't know how to implement it). Please double-check that I'm not missing something here.

Question to reviewers as this is my first contribution to nixpkgs: should this be backported to 23.05? It's a fix, but it can make nixos-rebuild fail if someone was using one of these attrsets, even if they had no effect in practice.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mzabani** [comment]
@bbigras friendly ping for a review. Please let me know if there is someone else I can request a review from in case you're busy, or something else I can do to help get this in.

**Comment by mzabani** [comment]
@bbigras sorry once again for spamming you, but I'd really like to get this merged. Could you review this or perhaps invite someone you trust to do it?

**Comment by mzabani** [comment]
I am closing this. It has acquired merge conflicts and I'm not sure how I could get it reviewed.

**Comment by bbigras** [comment]
Ah sorry about that. It seems I wanted to take a look twice but didn't.

It seems that #277189 addressed the two main issues.

Thanks for your contribution and sorry once again.

**Pull request closed without merging**
