### PR TITLE
systemd: add -Wno-error=format-overflow if isPower

### PR DESCRIPTION
**Pull request by ghost**
## Description of changes

Required in order to get the NixOS installer to build again.

CC: @hlandau

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by hlandau — APPROVED** [review]

**Review by NickCao — COMMENTED** [review]
Also required on riscv, this deserves an upstream fix.

**Comment by flokli** [comment]
I'm happy shipping a arch-specific override, but it should have a comment alongside pointing to the upstream PR, so we know why it's there and when we can drop it.

Is there any way to reproduce this without a riscv or power computer?

**Comment by NickCao** [comment]
> Is there any way to reproduce this without a riscv or power computer?

`nix build .#pkgsCross.riscv64.systemd`

**Comment by RaitoBezarius** [comment]
To be precise, here's relevant logs for RISC-V:
```
systemd-minimal> In file included from ../src/basic/macro.h:446,
systemd-minimal>                  from ../src/basic/alloc-util.h:10,
systemd-minimal>                  from ../src/shared/install.c:12:
systemd-minimal> ../src/shared/install.c: In function ‘install_changes_dump’:
systemd-minimal> ../src/shared/install.c:444:64: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
systemd-minimal>   444 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, unit %s does not exist.",
systemd-minimal>       |                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:214:86: note: in definition of macro ‘log_full_errno_zerook’
systemd-minimal>   214 |                         ? log_internal(_level, _e, PROJECT_FILE, __LINE__, __func__, __VA_ARGS__) \
systemd-minimal>       |                                                                                      ^~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:254:41: note: in expansion of macro ‘log_full_errno’
systemd-minimal>   254 | #define log_error_errno(error, ...)     log_full_errno(LOG_ERR,     error, __VA_ARGS__)
systemd-minimal>       |                                         ^~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:444:31: note: in expansion of macro ‘log_error_errno’
systemd-minimal>   444 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, unit %s does not exist.",
systemd-minimal>       |                               ^~~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:444:75: note: format string is defined here
systemd-minimal>   444 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, unit %s does not exist.",
systemd-minimal>       |                                                                           ^~
systemd-minimal> ../src/shared/install.c:403:55: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
systemd-minimal>   403 |                                                       "Failed to %s unit, file \"%s\" already exists.",
systemd-minimal>       |                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:214:86: note: in definition of macro ‘log_full_errno_zerook’
systemd-minimal>   214 |                         ? log_internal(_level, _e, PROJECT_FILE, __LINE__, __func__, __VA_ARGS__) \
systemd-minimal>       |                                                                                      ^~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:254:41: note: in expansion of macro ‘log_full_errno’
systemd-minimal>   254 | #define log_error_errno(error, ...)     log_full_errno(LOG_ERR,     error, __VA_ARGS__)
systemd-minimal>       |                                         ^~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:402:39: note: in expansion of macro ‘log_error_errno’
systemd-minimal>   402 |                                 err = log_error_errno(changes[i].type,
systemd-minimal>       |                                       ^~~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:403:66: note: format string is defined here
systemd-minimal>   403 |                                                       "Failed to %s unit, file \"%s\" already exists.",
systemd-minimal>       |                                                                  ^~
systemd-minimal> ../src/shared/install.c:399:55: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
systemd-minimal>   399 |                                                       "Failed to %s unit, file \"%s\" already exists and is a symlink to \"%s\".",
systemd-minimal>       |                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:214:86: note: in definition of macro ‘log_full_errno_zerook’
systemd-minimal>   214 |                         ? log_internal(_level, _e, PROJECT_FILE, __LINE__, __func__, __VA_ARGS__) \
systemd-minimal>       |                                                                                      ^~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:254:41: note: in expansion of macro ‘log_full_errno’
systemd-minimal>   254 | #define log_error_errno(error, ...)     log_full_errno(LOG_ERR,     error, __VA_ARGS__)
systemd-minimal>       |                                         ^~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:398:39: note: in expansion of macro ‘log_error_errno’
systemd-minimal>   398 |                                 err = log_error_errno(changes[i].type,
systemd-minimal>       |                                       ^~~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:399:66: note: format string is defined here
systemd-minimal>   399 |                                                       "Failed to %s unit, file \"%s\" already exists and is a symlink to \"%s\".",
systemd-minimal>       |                                                                  ^~
systemd-minimal> ../src/shared/install.c:440:72: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
systemd-minimal>   440 |                                 err = log_error_errno(changes[i].type, "Failed to %s unit, invalid unit reference \"%s\".",
systemd-minimal>       |                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:214:86: note: in definition of macro ‘log_full_errno_zerook’
systemd-minimal>   214 |                         ? log_internal(_level, _e, PROJECT_FILE, __LINE__, __func__, __VA_ARGS__) \
systemd-minimal>       |                                                                                      ^~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:254:41: note: in expansion of macro ‘log_full_errno’
systemd-minimal>   254 | #define log_error_errno(error, ...)     log_full_errno(LOG_ERR,     error, __VA_ARGS__)
systemd-minimal>       |                                         ^~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:440:39: note: in expansion of macro ‘log_error_errno’
systemd-minimal>   440 |                                 err = log_error_errno(changes[i].type, "Failed to %s unit, invalid unit reference \"%s\".",
systemd-minimal>       |                                       ^~~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:440:83: note: format string is defined here
systemd-minimal>   440 |                                 err = log_error_errno(changes[i].type, "Failed to %s unit, invalid unit reference \"%s\".",
systemd-minimal>       |                                                                                   ^~
systemd-minimal> ../src/shared/install.c:437:72: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
systemd-minimal>   437 |                                 err = log_error_errno(changes[i].type, "Failed to %s unit, cannot alias %s as %s.",
systemd-minimal>       |                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:214:86: note: in definition of macro ‘log_full_errno_zerook’
systemd-minimal>   214 |                         ? log_internal(_level, _e, PROJECT_FILE, __LINE__, __func__, __VA_ARGS__) \
systemd-minimal>       |                                                                                      ^~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:254:41: note: in expansion of macro ‘log_full_errno’
systemd-minimal>   254 | #define log_error_errno(error, ...)     log_full_errno(LOG_ERR,     error, __VA_ARGS__)
systemd-minimal>       |                                         ^~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:437:39: note: in expansion of macro ‘log_error_errno’
systemd-minimal>   437 |                                 err = log_error_errno(changes[i].type, "Failed to %s unit, cannot alias %s as %s.",
systemd-minimal>       |                                       ^~~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:437:83: note: format string is defined here
systemd-minimal>   437 |                                 err = log_error_errno(changes[i].type, "Failed to %s unit, cannot alias %s as %s.",
systemd-minimal>       |                                                                                   ^~
systemd-minimal> ../src/shared/install.c:415:64: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
systemd-minimal>   415 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, file %s is under the systemd unit hierarchy already.",
systemd-minimal>       |                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:214:86: note: in definition of macro ‘log_full_errno_zerook’
systemd-minimal>   214 |                         ? log_internal(_level, _e, PROJECT_FILE, __LINE__, __func__, __VA_ARGS__) \
systemd-minimal>       |                                                                                      ^~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:254:41: note: in expansion of macro ‘log_full_errno’
systemd-minimal>   254 | #define log_error_errno(error, ...)     log_full_errno(LOG_ERR,     error, __VA_ARGS__)
systemd-minimal>       |                                         ^~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:415:31: note: in expansion of macro ‘log_error_errno’
systemd-minimal>   415 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, file %s is under the systemd unit hierarchy already.",
systemd-minimal>       |                               ^~~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:415:75: note: format string is defined here
systemd-minimal>   415 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, file %s is under the systemd unit hierarchy already.",
systemd-minimal>       |                                                                           ^~
systemd-minimal> ../src/shared/install.c:432:64: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
systemd-minimal>   432 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, refusing to operate on linked unit file %s.",
systemd-minimal>       |                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:214:86: note: in definition of macro ‘log_full_errno_zerook’
systemd-minimal>   214 |                         ? log_internal(_level, _e, PROJECT_FILE, __LINE__, __func__, __VA_ARGS__) \
systemd-minimal>       |                                                                                      ^~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:254:41: note: in expansion of macro ‘log_full_errno’
systemd-minimal>   254 | #define log_error_errno(error, ...)     log_full_errno(LOG_ERR,     error, __VA_ARGS__)
systemd-minimal>       |                                         ^~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:432:31: note: in expansion of macro ‘log_error_errno’
systemd-minimal>   432 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, refusing to operate on linked unit file %s.",
systemd-minimal>       |                               ^~~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:432:75: note: format string is defined here
systemd-minimal>   432 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, refusing to operate on linked unit file %s.",
systemd-minimal>       |                                                                           ^~
systemd-minimal> ../src/shared/install.c:423:64: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
systemd-minimal>   423 |                         err = log_error_errno(changes[i].type, "Failed to %s %s, destination unit %s is a non-template unit.",
systemd-minimal>       |                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:214:86: note: in definition of macro ‘log_full_errno_zerook’
systemd-minimal>   214 |                         ? log_internal(_level, _e, PROJECT_FILE, __LINE__, __func__, __VA_ARGS__) \
systemd-minimal>       |                                                                                      ^~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:254:41: note: in expansion of macro ‘log_full_errno’
systemd-minimal>   254 | #define log_error_errno(error, ...)     log_full_errno(LOG_ERR,     error, __VA_ARGS__)
systemd-minimal>       |                                         ^~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:423:31: note: in expansion of macro ‘log_error_errno’
systemd-minimal>   423 |                         err = log_error_errno(changes[i].type, "Failed to %s %s, destination unit %s is a non-template unit.",
systemd-minimal>       |                               ^~~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:423:75: note: format string is defined here
systemd-minimal>   423 |                         err = log_error_errno(changes[i].type, "Failed to %s %s, destination unit %s is a non-template unit.",
systemd-minimal>       |                                                                           ^~
systemd-minimal> ../src/shared/install.c:448:64: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
systemd-minimal>   448 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, cannot resolve specifiers in \"%s\".",
systemd-minimal>       |                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:214:86: note: in definition of macro ‘log_full_errno_zerook’
systemd-minimal>   214 |                         ? log_internal(_level, _e, PROJECT_FILE, __LINE__, __func__, __VA_ARGS__) \
systemd-minimal>       |                                                                                      ^~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:254:41: note: in expansion of macro ‘log_full_errno’
systemd-minimal>   254 | #define log_error_errno(error, ...)     log_full_errno(LOG_ERR,     error, __VA_ARGS__)
systemd-minimal>       |                                         ^~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:448:31: note: in expansion of macro ‘log_error_errno’
systemd-minimal>   448 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, cannot resolve specifiers in \"%s\".",
systemd-minimal>       |                               ^~~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:448:75: note: format string is defined here
systemd-minimal>   448 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, cannot resolve specifiers in \"%s\".",
systemd-minimal>       |                                                                           ^~
systemd-minimal> ../src/shared/install.c:419:64: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
systemd-minimal>   419 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, invalid specifier in \"%s\".",
systemd-minimal>       |                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:214:86: note: in definition of macro ‘log_full_errno_zerook’
systemd-minimal>   214 |                         ? log_internal(_level, _e, PROJECT_FILE, __LINE__, __func__, __VA_ARGS__) \
systemd-minimal>       |                                                                                      ^~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:254:41: note: in expansion of macro ‘log_full_errno’
systemd-minimal>   254 | #define log_error_errno(error, ...)     log_full_errno(LOG_ERR,     error, __VA_ARGS__)
systemd-minimal>       |                                         ^~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:419:31: note: in expansion of macro ‘log_error_errno’
systemd-minimal>   419 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, invalid specifier in \"%s\".",
systemd-minimal>       |                               ^~~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:419:75: note: format string is defined here
systemd-minimal>   419 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, invalid specifier in \"%s\".",
systemd-minimal>       |                                                                           ^~
systemd-minimal> ../src/shared/install.c:411:64: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
systemd-minimal>   411 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, unit %s is transient or generated.",
systemd-minimal>       |                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:214:86: note: in definition of macro ‘log_full_errno_zerook’
systemd-minimal>   214 |                         ? log_internal(_level, _e, PROJECT_FILE, __LINE__, __func__, __VA_ARGS__) \
systemd-minimal>       |                                                                                      ^~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:254:41: note: in expansion of macro ‘log_full_errno’
systemd-minimal>   254 | #define log_error_errno(error, ...)     log_full_errno(LOG_ERR,     error, __VA_ARGS__)
systemd-minimal>       |                                         ^~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:411:31: note: in expansion of macro ‘log_error_errno’
systemd-minimal>   411 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, unit %s is transient or generated.",
systemd-minimal>       |                               ^~~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:411:75: note: format string is defined here
systemd-minimal>   411 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, unit %s is transient or generated.",
systemd-minimal>       |                                                                           ^~
systemd-minimal> ../src/shared/install.c:428:47: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
systemd-minimal>   428 |                                               "Failed to %s unit, \"%s\" is not a valid unit name.",
systemd-minimal>       |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:214:86: note: in definition of macro ‘log_full_errno_zerook’
systemd-minimal>   214 |                         ? log_internal(_level, _e, PROJECT_FILE, __LINE__, __func__, __VA_ARGS__) \
systemd-minimal>       |                                                                                      ^~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:254:41: note: in expansion of macro ‘log_full_errno’
systemd-minimal>   254 | #define log_error_errno(error, ...)     log_full_errno(LOG_ERR,     error, __VA_ARGS__)
systemd-minimal>       |                                         ^~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:427:31: note: in expansion of macro ‘log_error_errno’
systemd-minimal>   427 |                         err = log_error_errno(changes[i].type,
systemd-minimal>       |                               ^~~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:428:58: note: format string is defined here
systemd-minimal>   428 |                                               "Failed to %s unit, \"%s\" is not a valid unit name.",
systemd-minimal>       |                                                          ^~
systemd-minimal> ../src/shared/install.c:407:64: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
systemd-minimal>   407 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, unit %s is masked.",
systemd-minimal>       |                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:214:86: note: in definition of macro ‘log_full_errno_zerook’
systemd-minimal>   214 |                         ? log_internal(_level, _e, PROJECT_FILE, __LINE__, __func__, __VA_ARGS__) \
systemd-minimal>       |                                                                                      ^~~~~~~~~~~
systemd-minimal> ../src/basic/log.h:254:41: note: in expansion of macro ‘log_full_errno’
systemd-minimal>   254 | #define log_error_errno(error, ...)     log_full_errno(LOG_ERR,     error, __VA_ARGS__)
systemd-minimal>       |                                         ^~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:407:31: note: in expansion of macro ‘log_error_errno’
systemd-minimal>   407 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, unit %s is masked.",
systemd-minimal>       |                               ^~~~~~~~~~~~~~~
systemd-minimal> ../src/shared/install.c:407:75: note: format string is defined here
systemd-minimal>   407 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, unit %s is masked.",
systemd-minimal>       |                                                                           ^~
systemd-minimal> cc1: some warnings being treated as errors
```

**Comment by flokli** [comment]
It's very odd that these `log_error_errno` macros fail because some of the things to log is null, on one specific architecture.

Is this a sign of a bigger problem? Can anyone try to execute some of the binaries produced (on riscv or power architectures), to make sure they're not just plain broken?

**Comment by NickCao** [comment]
> Is this a sign of a bigger problem? Can anyone try to execute some of the binaries produced (on riscv or power architectures), to make sure they're not just plain broken?

I'm booting the resulting systemd on a riscv board and it works fine. Could be just not hitting that code path.

**Comment by ElvishJerricco** [comment]
> It's very odd that these log_error_errno macros fail because some of the things to log is null, on one specific architecture.

I also find this so odd that I'm not very happy merging this until it's understood *why* this is happening.

**Comment by skeuchel** [comment]
I think this is the corresponding upstream bug report https://github.com/systemd/systemd/issues/30448

**Pull request closed without merging**
