### PR TITLE
libressl: 2.2.4 -> 2.3.1

### PR DESCRIPTION
**Pull request by zimbatm**

### CODE REVIEW

**Comment by nbp** [comment]
cc @thoughtpolice @wkennington @fpletz

**Comment by fpletz** [comment]
:+1:

Please note that libressl dropped some more functionality in the 2.3 series that will cause build failures with some older code that relies on the full openssl API.

**Comment by zimbatm** [comment]
@fpletz I can make another patch that keeps the older version around

**Comment by vcunat** [comment]
That's quite an important information wrt. #10468.

**Comment by globin** [comment]
I actually already mentioned that in #10468, btw citing libressl.org:
 * The latest stable release is 2.2.4
 * The latest snapshot release is 2.3.1

**Comment by vcunat** [comment]
Well, it doesn't seem like 2.3.1 would be a good default libressl version.
>  2.1.x and 2.2.x are the currently-supported stable branches.

**Comment by globin** [comment]
@vcunat :+1:

**Comment by zimbatm** [comment]
just changed the PR to incorporate these feedbacks ^^

**Comment by globin** [comment]
Looks good to me

**Comment by spacekitteh** [comment]
What would you say about a config option to set it? c.f. #12877

**Comment by vcunat** [comment]
I think you can do a nixpkgs-wide override easily enough, via `packageOverrides`. Only it will likely cause a mass rebuild, and maybe even lots of failures (who knows?).

**Comment by fpletz** [comment]
@spacekitteh We're using libressl instead of openssl and have backported build fixes upstream. Most packages will work but some like stunnel still need openssl. We have some overrides for those but can't really get those upstream.

**Comment by spacekitteh** [comment]
@fpletz the fix for openntpd is #20602

**Pull request closed without merging**
