### PR TITLE
p7zip: switch to maintained fork

### PR DESCRIPTION
**Pull request by magnetophon**
This the fork that true-upstream seems to prefer, see:
https://www.7-zip.org/links.html

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by magnetophon** [comment]
@7c6f434c I left you as a maintainer of 7zip, if that's OK.
Also: I couldn't test the osx specific parts.

**Comment by 7c6f434c** [comment]
Fine with me re: maintainer entry

I think https://www.7-zip.org/links.html mentioning the new fork should be put into commit message — there are many places where 7-zip.org only links to old p7zip, and there are many forks; but indeed true-upstream seems to prefer this fork as the new one

@ofborg build p7zip

**Comment by magnetophon** [comment]
@7c6f434c Thanks, done.

**Comment by 7c6f434c** [comment]
Maybe remove cross-commit references? Now they do not match (as Git seems to choose to include changelog into commit hash)

**Comment by magnetophon** [comment]
@7c6f434c 
> Maybe remove cross-commit references? Now they do not match (as Git seems to choose to include changelog into commit hash)

Just to be clear, you mean keep the ``This reverts commit 5e52a39.`` but lose the
```
p7zip is now switched to a maintained fork, see commit:
944f51c71328ce0e6bca32ad5da17738fa8a64c6
```

Correct?

**Comment by 7c6f434c** [comment]
>Just to be clear, you mean keep the ``This reverts commit 5e52a39.`` but lose the
>```
>p7zip is now switched to a maintained fork, see commit:
>944f51c71328ce0e6bca32ad5da17738fa8a64c6
>```
>
>Correct?

Well, only the second part (see commit)

**Review by ghost — APPROVED** [review]
dtrx and woeusb work for me

**Comment by magnetophon** [comment]
@7c6f434c OK, done.

**Comment by Anton-Latukha** [comment]
This probably needs to be Linked to the according #88147 Report

**Comment by magnetophon** [comment]
@Anton-Latukha Thanks, I missed that.

**Comment by 7c6f434c** [comment]
(looked up: ofborg complaint is about a warning instead of `throw` in an unrelated package on `master`)

**Pull request merged**
