### PR TITLE
tuxedo drivers module

### PR DESCRIPTION
**Pull request by xaverdh**
## Description of changes

picking up where https://github.com/NixOS/nixpkgs/pull/293017 left off

## Things done

built on kernels: 6.10, 6.11

running this on my own system with `tuxedo-rs`

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by dasj19** [comment]
Hello, I pointed my nixpkgs to this branch and tried to see if it works. It looks like it does not.
I tried with kernel versions 6.6 6.10 and 6.11.

The kernel modules are loaded:
```
lsmod | grep tuxedo
tuxedo_io              24576  1
tuxedo_keyboard       106496  3 clevo_acpi,tuxedo_io,clevo_wmi
tuxedo_compatibility_check    12288  1 tuxedo_keyboard
led_class_multicolor    16384  1 tuxedo_keyboard
battery                28672  1 tuxedo_keyboard
sparse_keymap          12288  1 tuxedo_keyboard
led_class              20480  7 r8169,snd_hda_codec_generic,videodev,input_leds,iwlmvm,tuxedo_keyboard,led_class_multicolor
```

But I am unable to change keyboard backlight color, tried with hotkey, via gnome-interface and tuxedo-rs.
None of the above works.

How can I debug this? Thanks.

**Comment by dasj19** [comment]
Hello again. It works only after a full shutdown, and powerup again. I tried with restart before but for some reason the changes did not take into effect.

**Review by dasj19 — APPROVED** [review]
Changes look good. I built them and works as expected.

**Comment by SebRut** [comment]
Also working for me on a Pulse14 Gen3.

**Comment by nagymathev** [comment]
Hey, I'm trying this on a Tuxedo Stellaris 16, but getting an odd error message, not sure why `tuxedo-drivers` is missing when I've imported it:

```nix
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'nixos-system-stellaris-24.11.20240923.30439d9'
         whose name attribute is located at /nix/store/p2hby44a0qzrnd1vxcpcgfav6160rmcv-source/pkgs/stdenv/generic/make-derivation.nix:336:7

       … while evaluating attribute 'buildCommand' of derivation 'nixos-system-stellaris-24.11.20240923.30439d9'

         at /nix/store/p2hby44a0qzrnd1vxcpcgfav6160rmcv-source/nixos/modules/system/activation/top-level.nix:53:5:

           52|     passAsFile = [ "extraDependencies" ];
           53|     buildCommand = systemBuilder;
             |     ^
           54|

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'tuxedo-drivers' missing

       at /nix/store/7fq4hb2hdirbk8kb3s905m9hfjw5r218-source/nixos/modules/hardware/tuxedo-drivers.nix:4:20:

            3|   cfg = config.hardware.tuxedo-drivers;
            4|   tuxedo-drivers = config.boot.kernelPackages.tuxedo-drivers;
             |                    ^
            5| in
error: Recipe `switch` failed on line 7 with exit code 1
```
The following is what I've done:
```nix
  disabledModules = [
    "hardware/tuxedo-keyboard.nix"
    "services/hardware/tuxedo-rs.nix"
  ];

  imports = [
    "${inputs.tuxedo}/nixos/modules/hardware/tuxedo-drivers.nix"
    "${inputs.tuxedo}/nixos/modules/services/hardware/tuxedo-rs.nix"
  ];

  hardware.tuxedo-drivers.enable = true;
  hardware.tuxedo-rs.enable = true;
  hardware.tuxedo-rs.tailor-gui.enable = true;


  boot = {
    kernelPackages = pkgs.linuxKernel.packages.linux_latest.extend (final: prev: {
      tuxedo-drivers = inputs.tuxedo.legacyPackages.x86_64-linux.linuxKernel.packages.linux_latest.tuxedo-drivers;
    });
  };
```
`inputs.tuxedo` points to this commit.

Any ideas?

**Comment by nagymathev** [comment]
Thank you @PhDyellow, after doing as you told me it works flawlessly so far. Can approve that it works for a Stellaris 16

**Comment by xaverdh** [comment]
closing in favor of https://github.com/NixOS/nixpkgs/pull/343483
we need less pull requests and more of them merged..

**Pull request closed without merging**
