### PR TITLE
zrepl: 0.4.0 -> 0.5.0

### PR DESCRIPTION
**Pull request by spencerjanssen**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cole-h** [comment]
I wish there was a way to communicate potential issues to end users... This version contains a fix for encrypted dataset handling with placeholders, but it appears that it requires special consideration (https://zrepl.github.io/v0.5.0/configuration/sendrecvoptions.html#job-recv-options-placeholder).

**Comment by spencerjanssen** [comment]
> I wish there was a way to communicate potential issues to end users... This version contains a fix for encrypted dataset handling with placeholders, but it appears that it requires special consideration

Should that be included in the 22.05 release notes?  Similarly I was wondering if we need to mention this from the [release notes on GitHub](https://github.com/zrepl/zrepl/releases/tag/v0.5.0):

> The RPC protocol version was bumped; all zrepl daemons in a setup must be updated and restarted before replication can resume.

**Comment by cole-h** [comment]
I think those would be great additions to the release notes, yes! Please and thank you.

**Comment by spencerjanssen** [comment]
Added to the release notes, I think this PR is ready to go.

**Comment by erictapen** [comment]
@GrahamcOfBorg build zrepl

**Pull request merged**
