### PR TITLE
invidious: unstable-2022-08-13 -> unstable-2022-11-02

### PR DESCRIPTION
**Pull request by GaetanLepage**
###### Description of changes

Update to new version.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

@sbruder 
@infinisil

### CODE REVIEW

**Comment by GaetanLepage** [comment]
I am not 100% sure that simply bumping the version and hash in `versions.json` is enough.
Do not hesitate to mention additional needed steps :)

**Comment by infinisil** [comment]
It isn't indeed, but invidious has an `updateScript`, so it's all automated, check out https://nixos.org/manual/nixpkgs/stable/#var-passthru-updateScript :)

**Comment by GaetanLepage** [comment]
> It isn't indeed, but invidious has an `updateScript`, so it's all automated, check out https://nixos.org/manual/nixpkgs/stable/#var-passthru-updateScript :)

Great ! Thank you for the info :)
Is there anything else to do before merging this then ?

**Review by sbruder — APPROVED** [review]
Sorry for not replying sooner, I didn’t really have the time lately.
This looks good and works from what I tested, thanks!

One thing that is not ideal is that invidious logs many instances of `WARNING: Unsupported BIO ctrl call (73)` and `WARNING: Unsupported BIO ctrl call (76)`, which probably is a bug in crystal fixed by https://github.com/crystal-lang/crystal/pull/12034, so it should get fixed by https://github.com/NixOS/nixpkgs/pull/195606.

**Comment by GaetanLepage** [comment]
No worries @sbruder, thank you for your input.
From what I can see on the crystal PR, it seems that it is not yet ready to be merged...
What do you think, should we update now and update one more time when crystal is updated to 1.6 or should we wait ?

**Comment by GaetanLepage** [comment]
Ok perfect !
@infinisil is it ok for you ?

Do one of you have repo-access to merge this PRor should we call someone else to do so ?

**Pull request merged**
