### PR TITLE
add stripJavaArchivesHook and use treewide

### PR DESCRIPTION
**Pull request by TomaSajt**
## Description of changes

Tracking issue: https://github.com/NixOS/nixpkgs/issues/278518

Supersedes https://github.com/NixOS/nixpkgs/pull/278322
Supersedes https://github.com/NixOS/nixpkgs/pull/286805 (pretty similar to this, but would add a new package)
Supersedes https://github.com/NixOS/nixpkgs/pull/294516

This is my 3rd (or 4th) and hopefully final attempt at making a setup-hook, which can be used to strip all `.jar` files from their timestamps.
This time I didn't have to do a lot of work because it turns out the `strip-nondeterminism` package already handles everything I wanted to do.

This PR has 5 commits:
- Update and rename the hook, replacing `canonicalize-jars-hook` (added as an alias)
- Make existing packages using `canonicalize-jars-hook` use the non-alias name for the hook
- Migrate all previous attempts at java determinism, which didn't use `canonicalize-jars-hook`
(I only did the `ant` ones. `maven` and `gradle` might be in another PR as those are a bit different)
- Migrate a non-`ant` package too
- Update the java section of the nixpkgs docs

```sh
# Shorter builds
nix build .#{bisq-desktop,calcoo,mkgmap,mkgmap-splitter,pattypan,dayon,jameica,trimmomatic,jasmin,freetts,javaCup,hydraAntLogger,swt,jdepend,javacc,jpsxdec,ili2c,fop}
# Longer builds
nix build .#{jogl,abcl,prismlauncher-unwrapped}

# Run the commands again with the `--rebuild` flag to check for determinism
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by rnhmjoj** [comment]
Can you add the hook to cie-middleware-linux and bisq-desktop? Both are using strip-nondeterminism.

**Comment by TomaSajt** [comment]
> Can you add the hook to cie-middleware-linux and bisq-desktop? Both are using strip-nondeterminism.

AFACT cie-middleware-linux doesn't build on master ATM, but I'll try the other one

**Comment by rnhmjoj** [comment]
> AFACT cie-middleware-linux doesn't build on master ATM

Oof, I need to update it.

**Review by drupol — APPROVED** [review]
Nice!!

**Review by drupol — APPROVED** [review]

**Comment by rnhmjoj** [comment]
Documentation? There is a Java section in the Nixpkgs manual...

**Comment by TomaSajt** [comment]
> Documentation? There is a Java section in the Nixpkgs manual...

I was planning on doing a rework of the java packaging docs in another PR, but I guess it wouldn't hurt putting some docs in this PR too. Though I will only add stuff related to this hook.

**Comment by TomaSajt** [comment]
I updated the main java packaging example to be more up-to-date and to use `stripJavaArchivesHook`. You can see that the docs are a bit old so I'll still to a proper docs rewrite in a followup PR.

**Comment by LeSuisse** [comment]
For the records, nixpkgs-review is happy on Linux x86_64

Result of `nixpkgs-review pr 296549` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.kmapper</li>
    <li>python311Packages.kmapper.dist</li>
    <li>python311Packages.scikit-tda</li>
    <li>python311Packages.scikit-tda.dist</li>
    <li>spring</li>
    <li>springLobby</li>
  </ul>
</details>
<details>
  <summary>79 packages built:</summary>
  <ul>
    <li>abcl</li>
    <li>ipscan (angryipscanner)</li>
    <li>asciidoc-full</li>
    <li>asciidoc-full-with-plugins</li>
    <li>asciidoc-full-with-plugins.dist</li>
    <li>asciidoc-full.dist</li>
    <li>bisq-desktop</li>
    <li>calcoo</li>
    <li>checkov</li>
    <li>checkov.dist</li>
    <li>clevis</li>
    <li>clevis.man</li>
    <li>dayon</li>
    <li>disorderfs</li>
    <li>fop</li>
    <li>freetts</li>
    <li>gephi</li>
    <li>gpsbabel-gui</li>
    <li>gpsbabel-gui.doc</li>
    <li>hal-hardware-analyzer</li>
    <li>hydraAntLogger</li>
    <li>igraph</li>
    <li>igraph.dev</li>
    <li>igraph.doc</li>
    <li>ili2c</li>
    <li>jameica</li>
    <li>jasmin</li>
    <li>javaCup</li>
    <li>javacc</li>
    <li>jdepend</li>
    <li>jogl</li>
    <li>jpsxdec</li>
    <li>rep (kakounePlugins.rep)</li>
    <li>libleidenalg</li>
    <li>luksmeta</li>
    <li>mkgmap</li>
    <li>mkgmap-splitter</li>
    <li>pattypan</li>
    <li>prismlauncher</li>
    <li>prismlauncher-qt5</li>
    <li>prismlauncher-qt5-unwrapped</li>
    <li>prismlauncher-unwrapped</li>
    <li>processing</li>
    <li>python311Packages.explorerscript</li>
    <li>python311Packages.explorerscript.dist</li>
    <li>python311Packages.igraph</li>
    <li>python311Packages.igraph.dist</li>
    <li>python311Packages.leidenalg</li>
    <li>python311Packages.leidenalg.dist</li>
    <li>python311Packages.skytemple-dtef</li>
    <li>python311Packages.skytemple-dtef.dist</li>
    <li>python311Packages.skytemple-files</li>
    <li>python311Packages.skytemple-files.dist</li>
    <li>python311Packages.skytemple-ssb-debugger</li>
    <li>python311Packages.skytemple-ssb-debugger.dist</li>
    <li>python311Packages.textnets</li>
    <li>python311Packages.textnets.dist</li>
    <li>python312Packages.explorerscript</li>
    <li>python312Packages.explorerscript.dist</li>
    <li>python312Packages.igraph</li>
    <li>python312Packages.igraph.dist</li>
    <li>python312Packages.leidenalg</li>
    <li>python312Packages.leidenalg.dist</li>
    <li>python312Packages.skytemple-dtef</li>
    <li>python312Packages.skytemple-dtef.dist</li>
    <li>python312Packages.skytemple-files</li>
    <li>python312Packages.skytemple-files.dist</li>
    <li>python312Packages.skytemple-ssb-debugger</li>
    <li>python312Packages.skytemple-ssb-debugger.dist</li>
    <li>skytemple</li>
    <li>skytemple.dist</li>
    <li>stripJavaArchivesHook</li>
    <li>swt</li>
    <li>swt_jdk8</li>
    <li>tang</li>
    <li>tang.man</li>
    <li>trimmomatic</li>
    <li>tuxguitar</li>
    <li>vuze</li>
  </ul>
</details>

**Pull request merged**
