### PR TITLE
atom: 1.48.0 -> 1.54.0;  atom-beta: broken

### PR DESCRIPTION
**Pull request by cab404**
###### Motivation for this change
Atom got updated; no one cared :|

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cab404** [comment]
Result of `nixpkgs-review pr 114277` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>atom</li>
    <li>atom-beta</li>
  </ul>
</details>

**Comment by cab404** [comment]
atom-beta doesn't work, apparently it fails to do so with renamed binaries. Gotta rename beta packet to being just 'atom'.

This will break things for users with both in environment, but I doubt that anyone does that (they share configs after all)

**Comment by cab404** [comment]
Maybe just declare atom-beta as broken and move on?

**Comment by cab404** [comment]
Yup, current atom-beta doesn't launch either. Broken it is.

**Comment by SuperSandro2000** [comment]
> Yup, current atom-beta doesn't launch either. Broken it is.

Can you commit that?

**Comment by cab404** [comment]
Yes.

**Comment by cab404** [comment]
f

> > Yup, current atom-beta doesn't launch either. Broken it is.
> 
> Can you commit that?

done!

**Comment by cole-h** [comment]
@ofborg eval

**Pull request merged**
