### PR TITLE
powerline-go: 1.11.0 -> 1.12.1

### PR DESCRIPTION
**Pull request by xrelkd**
###### Motivation for this change

Update `powerline-go` to the latest version

[https://github.com/justjanne/powerline-go/releases/tag/v1.12.1](https://github.com/justjanne/powerline-go/releases/tag/v1.12.1)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
LGTM

**Review by xeji — COMMENTED** [review]
Did you check for updates in dependencies (`deps.nix`) ? There are usually some. It is recommended to do that even if the updated app builds fine.

There's a semi-automated process for updating `deps.nix` with `go2nix`, see https://nixos.org/nixpkgs/manual/#sec-language-go and https://github.com/kamilchm/go2nix .
(We also have `vgo2nix` for Go apps using Go modules, which doesn't apply here)

**Comment by xrelkd** [comment]
@xeji Thanks for the review!
The dependencies (`deps.nix`) are updated.

**Comment by xeji** [comment]
Thank you!
@GrahamcOfBorg build powerline-go

**Pull request merged**
