### PR TITLE
wl-screenrec: init at unstable-2023-05-31

### LINKED ISSUE #235103: Package request: wl-screenrec
**Project description**

[wl-screenrec](https://github.com/russelltg/wl-screenrec) offers high performance wlroots screen recording, featuring hardware encoding.

**Metadata**

* homepage URL: https://github.com/russelltg/wl-screenrec
* source URL: https://github.com/russelltg/wl-screenrec
* license: gpl2+
* platforms: linux

### PR DESCRIPTION
**Pull request by Kranzes**
###### Description of changes
closes https://github.com/NixOS/nixpkgs/issues/235103#

cc. @colemickens 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by dit7ya — COMMENTED** [review]
Package built fine on x86_64-linux. Although, is this supposed to work with GPUs only?


```

[nix-shell:~/.cache/nixpkgs-review/pr-239462]$ ./results/wl-screenrec/bin/wl-screenrec
Using output eDP-1
0 fps
Cannot load libcuda.so.1
[AVHWDeviceContext @ 0x55f894bb2f80] libva: /run/opengl-driver/lib/dri/nvidia_drv_video.so init failed
[AVHWDeviceContext @ 0x55f894bb2f80] Failed to initialise VAAPI connection: 1 (operation failed).
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `-5`,
 right: `0`', src/avhw.rs:27:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Kranzes** [comment]
I am not sure, I don't use wayland, I was just requested to add this package.

**Comment by colemickens** [comment]
You could try the nvidia vaapi driver, but wl-screenrec seems to expect vaapi which nvidia doesn't provide by default.

**Comment by colemickens** [comment]
There's a new revision available that defaults to mp4.

I will also test this on an Nvidia setup with the nvidia vaapi shim driver... but I won't be able to do that for another 7-12 days.

I have tested the revision from this PR (that still defaults to AVI) and it works fine on my AMD/AMD system.

**Comment by colemickens** [comment]
Thank you @Kranzes !

**Pull request merged**
