### PR TITLE
buildGo{Module,Package}: respect nix hardening flags when setting buildmode

### LINKED ISSUE #211951: discussion about PIE and golang
Currently, pkgsMusl.rclone fails to build:

```
/nix/store/dbgdbpda30rscjlps73glkgz3w8gqszp-binutils-2.39/bin/ld: /build/go-link-354073529/go.o: warning: relocation in read-only section `.gopclntab'
/nix/store/dbgdbpda30rscjlps73glkgz3w8gqszp-binutils-2.39/bin/ld: warning: creating DT_TEXTREL in a PIE
@nix { "action": "setPhase", "phase": "checkPhase" }
running tests
?       github.com/rclone/rclone        [no test files]
@nix { "action": "setPhase", "phase": "installPhase" }
installing
/nix/store/khv74mid5pm7b24ji369psdvdi3bjqgj-stdenv-linux/setup: line 113: 16821 Segmentation fault      (core dumped) $out/bin/rclone genautocomplete $shell rclone.$shell
/nix/store/khv74mid5pm7b24ji369psdvdi3bjqgj-stdenv-linux/setup: line 129: pop_var_context: head of shell_variables not a function context
```

Or rather, it builds, but produces a faulty binary that segfaults later on.

From my research, this happens when the external linker defaults to PIE while golang defaults to non-PIE, which is the case in pkgsMusl (but not in the normal glibc package set, since the pie hardening flag is disabled there).

Our options are adding `hardeningDisable = [ "pie" ];` to buildGoModule or [patching go to set the default buildmode to PIE](https://github.com/NixOS/nixpkgs/commit/73e05c425713aab7e06de8b3fcd6bf74cd2ed0e9)

What do you think?

CC @zowoq @superherointj

### PR DESCRIPTION
**Pull request by zowoq**
###### Description of changes

Closes #211951

cc @NixOS/golang 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
Not particularly happy with this but I think it is the best option at the moment.

**Comment by qbit** [comment]
What's the best way to test this? I thought I could set `NIX_HARDENING_ENABLE` and run `nix-build -A somegoapp` but it doesn't seem to work that way.

**Comment by zowoq** [comment]
```diff
diff --git a/pkgs/development/tools/misc/editorconfig-checker/default.nix b/pkgs/development/tools/misc/editorconfig-checker/default.nix
index 1649031a7e7..8595bbd9c03 100644
--- a/pkgs/development/tools/misc/editorconfig-checker/default.nix
+++ b/pkgs/development/tools/misc/editorconfig-checker/default.nix
@@ -19,6 +19,8 @@ buildGoModule rec {
 
   ldflags = [ "-X main.version=${version}" ];
 
+  hardeningEnable = [ "pie" ];
+
   postInstall = ''
     installManPage docs/editorconfig-checker.1
   '';

```

**Comment by qbit** [comment]
:man_facepalming: ty :D

**Comment by qbit** [comment]
Spot checked a few tools, confirmed they build with pie and are still usable! lgtm!

**Review by qbit — APPROVED** [review]

**Pull request merged**
