### PR TITLE
iniparser: tweak include path for compatibility

### PR DESCRIPTION
**Pull request by aaronjheng**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aaronjheng** [comment]
Result of `nixpkgs-review pr 203388` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>apacheHttpdPackages.mod_tile</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>cava</li>
    <li>iniparser</li>
  </ul>
</details>

**Comment by aaronjheng** [comment]
apacheHttpdPackages.mod_tile has been broken for a while.

**Review by primeos — CHANGES_REQUESTED** [review]
Sorry for the delay, I've been too busy.

Could you describe this change a bit more in the commit message body?
E.g., that it is required for `apacheHttpdPackages.mod_tile` and do you have any references of upstream (or other Linux distributions) recommending/doing this?
Otherwise the Git history won't contain enough information to figure out why we made this change.

I've had a quick look and e.g. Arch Linux doesn't seem to do this:
https://archlinux.org/packages/extra/x86_64/iniparser/
```
usr/include/dictionary.h
usr/include/iniparser.h
```

Maybe we can/should fix the other packages instead?

Also: When trying to build `apacheHttpdPackages.mod_tile` I get a different error:
```
In file included from /nix/store/a4gmisgapdmickxv0ns6br4n42lcz4s1-mapnik-unstable-2022-10-18/include/mapnik/map.hpp:28,
                 from src/gen_tile.cpp:2:
/nix/store/a4gmisgapdmickxv0ns6br4n42lcz4s1-mapnik-unstable-2022-10-18/include/mapnik/color.hpp:33:10: fatal error: boost/operators.hpp: No such file or directory
   33 | #include <boost/operators.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:1183: src/renderd-gen_tile.o] Error 1
```

-> Not sure if we really want this change.

**Comment by aaronjheng** [comment]
> I've had a quick look and e.g. Arch Linux doesn't seem to do this:
https://archlinux.org/packages/extra/x86_64/iniparser/

Fro Debian and Ubuntu, they are
```
/usr/include/iniparser/dictionary.h
/usr/include/iniparser/iniparser.h
```

https://packages.debian.org/bullseye/amd64/libiniparser-dev/filelist

**Comment by aaronjheng** [comment]
> Also: When trying to build apacheHttpdPackages.mod_tile I get a different error:

That's another problem.

**Comment by aaronjheng** [comment]
> Maybe we can/should fix the other packages instead?

It's ok too.

**Pull request closed without merging**
