### PR TITLE
php: bumps (April 2022)

### PR DESCRIPTION
**Pull request by drupol**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by drupol** [comment]
@GrahamcOfBorg build php74 php81

**Comment by drupol** [comment]
@GrahamcOfBorg test php74 php81

**Comment by drupol** [comment]
@GrahamcOfBorg build php74 php80 php81
@GrahamcOfBorg test php74 php80 php81

**Review by jtojnar — COMMENTED** [review]
https://www.php.net/ChangeLog-8.php#8.1.5
https://www.php.net/ChangeLog-7.php#7.4.29

Weirdly, there does not seem to be changelog fro 8.0.18.

**Comment by drupol** [comment]
I think it's being written at the moment. Is it mandatory for merging this PR ?

**Comment by jtojnar** [comment]
I would like to be able to say that at least a quick check of changelog is part of a minimum standard when upgrading. But we currently have no such formal policy so it is up to individual maintainers.

**Review by Ma27 — APPROVED** [review]
LGTM

**Comment by Ma27** [comment]
Changelogs for 8.0 are also out: https://www.php.net/ChangeLog-8.php#8.0.18 

Btw I think it's kind of useful to add those to the commit messages in the future.

**Comment by Ma27** [comment]
@drupol would you mind opening a backport PR for 21.11 as well, please? :)

**Comment by drupol** [comment]
> @drupol would you mind opening a backport PR for 21.11 as well, please? :) 

I will see if I can find the time. However, I wish someone else could do this.

**Comment by Ma27** [comment]
Fine, #168757.

**Comment by drupol** [comment]
Merci :)

**Pull request merged**
