### PR TITLE
dwarf-fortress: 0.40.24 -> 0.42.04

### PR DESCRIPTION
**Pull request by robgssp**

### CODE REVIEW

**Comment by redi-russela** [comment]
Does dfhack work with this version? If not, can you update the value of `dfHackWorksWithCurrentVersion`?

**Comment by a1russell** [comment]
Does dfhack work with this version? It seems like it has an alpha build out at https://github.com/DFHack/dfhack/releases/tag/0.42.04-alpha2, but I haven't tested to see if it builds. Maybe just set `dfHackWorksWithCurrentVersion` to `false` for now?

**Comment by abbradar** [comment]
Ah, you have outran me by several hours -- see https://github.com/NixOS/nixpkgs/pull/12339

**Comment by abbradar** [comment]
Superseded by (merged) #12339

**Pull request closed without merging**
