### PR TITLE
clippy: fix on darwin

### PR DESCRIPTION
**Pull request by winterqt**
###### Description of changes

For whatever reason, on Darwin, `clippy-driver` has always pointed to
RPATH for `rustc_driver`, requiring us to add `${rustc}/lib` to RPATH
during fixup with `install_name_tool`. I wish I knew why (the linker
arguments rustc passes are sane), and I wish I knew why this didn't
occur on Linux. Either way, this is now required for `cargo-clippy` to
run, so let's do the same thing for it until we get a better sense of
what's going on here.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by winterqt** [comment]
Should I mention that the issue was caused by the 1.67.0 bump in the commit message, or...?

**Review by figsoda — APPROVED** [review]
I had to do [something similar](https://github.com/nix-community/fenix/commit/1a5444ef22155d07d7ebf0bc8baa34ca942d414a#diff-7cd072ef277b0d8969ff2dfa6d7cc007a7cb307e2ffc7817d76072a0321367eb) for fenix, not sure why it only happens on darwin for the source build

**Comment by winterqt** [comment]
Drafting this until I refactor some things.

**Review by figsoda — APPROVED** [review]

**Comment by winterqt** [comment]
I want to add a version test to prevent future runtime issues, but I don't have a chance to do that right now. Since this will definitely start blocking more people as they start to update their inputs (I've already seen one person run into this), I'm going to merge this now and do that later.

**Pull request merged**
