### PR TITLE
haskellPackages.stack: get building with ghc882

### LINKED ISSUE #81338: Stack is broken
stack is broken on all platforms

Normally I wouldn't mind. But it was also listed as a required job for darwin + ofBorg CI, and had to disable in https://github.com/NixOS/nixpkgs/pull/81334.

cc @peti

### PR DESCRIPTION
**Pull request by cdepillabout**
###### Motivation for this change

This gets `haskellPackages.stack` building again after the update to ghc882.

Fixes #81338.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cdepillabout** [comment]
@GrahamcOfBorg build stack

**Comment by cdepillabout** [comment]
I've tested that `stack` actually works by using it to build and run [`spago`](https://github.com/purescript/spago).

Everything seems to work.

**Review by jonringer — APPROVED** [review]
diff LGTM
i feel like the stack-ghc882-support.patch should be upstreamed (if not already)

otherwise LGTM
```
[6 built, 319 copied (3158.5 MiB), 217.1 MiB DL]
https://github.com/NixOS/nixpkgs/pull/81373
3 package built:
haskellPackages.pantry haskellPackages.stack stack
```

**Comment by cdepillabout** [comment]
> i feel like the stack-ghc882-support.patch should be upstreamed (if not already)

These patches have not been upstreamed.  Normally I hate carrying around patches in our source tree, but let me give my reasons for not upstreaming this:

1. The currently released version of stack is 2.1.3.1.  However, upstream `master` has already diverged significantly from the code for 2.1.3.1.  It is not clear that upstreaming this patch would even be helpful for the `stack` developers.
1. The actual patch is very simple.  Any of the `stack` developers would be able to figure out these changes easily.  I wouldn't really be saving anyone any time by upstreaming it.

**Pull request merged**
