### PR TITLE
python.pkgs.setuptools: 36.7.1 -> 38.2.3

### PR DESCRIPTION
**Pull request by catern**
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by orivej** [comment]
According to the [changelog](https://github.com/pypa/setuptools/blob/master/CHANGES.rst), this may break some packages: 
> In order to support deterministic builds, Setuptools no longer allows packages to declare install_requires as unordered sequences (sets or dicts).

**Comment by FRidh** [comment]
Job running at https://hydra.nixos.org/eval/1415387

**Comment by FRidh** [comment]
The test runner is also fixed it seems, causing a lot of failures due to missing test dependencies.

**Comment by catern** [comment]
All I particularly want is #701: Fixed duplicate test discovery on Python 3. which is present in 36.7.2. If it's a pain to upgrade all the way to 38.2.3, maybe we could just up to 37.0.0 perhaps

**Comment by FRidh** [comment]
> If it's a pain to upgrade all the way to 38.2.3

No, its not. But as with basically every setuptools upgrade, it requires some work. In this case, its fixing several expressions. Not many, really.

**Comment by orivej** [comment]
This commit is now in staging and it's breaking the tests of some packages (https://hydra.nixos.org/eval/1416829?#tabs-now-fail), for example, `cloud-init`: https://hydra.nixos.org/build/65655898. What is the cause of such failures? Why were they not broken before?

**Comment by FRidh** [comment]
In the `checkPhase` we run `python setup.py test`. Packages can provide an option on how to deal with such situation. At some point `setuptools` introduced `python -m unittest` by default. This was however only working with Python 3. Now, it seems it also functions with Python 2 packages. I don't see it anywhere mentioned in the changelog, but it is a good change.

Therefore, the cause of failing packages is that now they have to have their test dependencies defined or `doCheck` put to false, or else they will fail to build.

**Comment by FRidh** [comment]
Also, regarding merging such change while there are failures. Packages that break require a small fix that maintainers can do. Let me send out a mail to the list to clarify why there is some breakage.

**Comment by orivej** [comment]
OK, thanks, the breakage is small enough to deal with in staging.

**Comment by orivej** [comment]
For the reference, here is what has been broken when this change has reached master:
https://hydra.nixos.org/eval/1417673?filter=.x86_64-linux&compare=1417366
and here is a recent status:
https://hydra.nixos.org/eval/1418287?filter=.x86_64-linux&compare=1417366
(Of course not all breakage is due to the update.)

**Pull request closed without merging**
