### PR TITLE
kakoune: add kakboard plugin

### PR DESCRIPTION
**Pull request by loewenheim**
###### Motivation for this change
I think it's a useful plugin.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
  - [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nrdxp** [comment]
This can be easily reworked to follow the new workflow from #108363

**Comment by loewenheim** [comment]
> This can be easily reworked to follow the new workflow from #108363

How do I add a plugin? Just add the repo and name to `kakoune-plugin-names` and run `update.py`?

**Comment by nrdxp** [comment]
> How do I add a plugin? Just add the repo and name to `kakoune-plugin-names` and run `update.py`?
That's it.

**Comment by loewenheim** [comment]
> > How do I add a plugin? Just add the repo and name to `kakoune-plugin-names` and run `update.py`?
> 
> That's it.

That also updates all existing plugins though, is that intentional?

**Comment by nrdxp** [comment]
> That also updates all existing plugins though, is that intentional?

Actually it is, which is why I [asked](https://github.com/NixOS/nixpkgs/pull/116485#issuecomment-805431684) on #116485.

**Comment by loewenheim** [comment]
I updated my branch to depend on that PR, how should I proceed?

**Comment by SuperSandro2000** [comment]
> I updated my branch to depend on that PR, how should I proceed?

I think you need to rebase it because github does not exclude the merged commits.

**Comment by SEbbaDK** [comment]
This was added and merged in #120264

**Pull request closed without merging**
