### PR TITLE
linuxManualConfig: Sometimes depend on ubootTools

### PR DESCRIPTION
**Pull request by samueldr**
## Description of changes

This change will make it so updating U-Boot will not cause a rebuild of all cached/supported kernels.

While uBootTools is not a big dependency to add to the kernel, the kernel is a big dependent to add to U-Boot overall.

This issue was (understandably) introduced with #262677.

cc @alyssais as the previous author
cc @k900 for uh, being k900 and annoyed (like I was) at the unneeded rebuilds
cc @Artturin who sent the previous changes

## Things done

Used the repl and looked at:

```
nix-repl> map (p: p.name) pkgs.linux_latest.nativeBuildInputs # x86_64
[ "perl-5.38.2" "bc-1.07.1" "net-tools-2.10" "openssl-3.0.13" "rsync-3.2.7" "gmp-with-cxx-6.3.0" "libmpc-1.3.1" "mpfr-4.2.1" "zstd-1.5.6" "python3-minimal-3.11.9" "kmod-31" "bison-3.8.2" "flex-2.6.4" "cpio-2.15" "pahole-1.26" "zlib-1.3.1" "elfutils-0.191" ]

nix-repl> map (p: p.name) pkgsCross.aarch64-multiplatform.linux_latest.nativeBuildInputs
[ "perl-5.38.2" "bc-1.07.1" "net-tools-2.10" "openssl-3.0.13" "rsync-3.2.7" "gmp-with-cxx-6.3.0" "libmpc-1.3.1" "mpfr-4.2.1" "zstd-1.5.6" "python3-minimal-3.11.9" "kmod-31" "bison-3.8.2" "flex-2.6.4" "cpio-2.15" "pahole-1.26" "zlib-1.3.1" "elfutils-0.191" ]

nix-repl> map (p: p.name) pkgsCross.armv7l-hf-multiplatform.linux_latest.nativeBuildInputs
[ "perl-5.38.2" "bc-1.07.1" "net-tools-2.10" "openssl-3.0.13" "rsync-3.2.7" "gmp-with-cxx-6.3.0" "libmpc-1.3.1" "mpfr-4.2.1" "zstd-1.5.6" "python3-minimal-3.11.9" "kmod-31" "uboot-tools-only_defconfig-2024.01" "bison-3.8.2" "flex-2.6.4" "cpio-2.15" "pahole-1.26" "zlib-1.3.1" "elfutils-0.191" ]
```

As expected from the list, only armv7l in those examples use U-Boot.

* * *

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

(There is no mistake, the change was only evaluated.)

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by K900 — APPROVED** [review]
Diff LGTM, we can sneak it into master with the next round of kernel updates

**Review by alyssais — APPROVED** [review]
This seems like a reasonable way to do it.

**Comment by samueldr** [comment]
> Diff LGTM, we can sneak it into master with the next round of kernel updates

Can you manage that? And thanks!

**Comment by K900** [comment]
Sure

**Pull request merged**
