### PR TITLE
sniffnet: 1.1.1 -> 1.1.2

### PR DESCRIPTION
**Pull request by figsoda**
Diff: https://github.com/gyulyvgc/sniffnet/compare/v1.1.1...v1.1.2

Changelog: https://github.com/gyulyvgc/sniffnet/blob/main/CHANGELOG.md

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 221916` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>sniffnet</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
Change looks good to me.

**Comment by teto** [comment]
what did I miss  :'( 
```
➜ nix-build -A sniffnet
this path will be fetched (4.78 MiB download, 15.95 MiB unpacked):
  /nix/store/4bjpb8fm9i58km3gm4zxzi13blghhbjg-sniffnet-1.1.2
copying path '/nix/store/4bjpb8fm9i58km3gm4zxzi13blghhbjg-sniffnet-1.1.2' from 'https://cache.nixos.org'...
/nix/store/4bjpb8fm9i58km3gm4zxzi13blghhbjg-sniffnet-1.1.2
nixpkgs3 on  sniffnet:refs/pull/221916/head 
➜ result/bin/sniffnet 

  /---------------------------------------------------------\
 |     _____           _    __    __                  _      |
 |    / ____|         (_)  / _|  / _|                | |     |
 |   | (___    _ __    _  | |_  | |_   _ __     ___  | |_    |
 |    \___ \  | '_ \  | | |  _| |  _| | '_ \   / _ \ | __|   |
 |    ____) | | | | | | | | |   | |   | | | | |  __/ | |_    |
 |   |_____/  |_| |_| |_| |_|   |_|   |_| |_|  \___|  \__|   |
 |                                                           |
 |                   ___________                             |
 |                  /___________\                            |
 |                 | ___________ |                           |
 |                 | |         | |                           |
 |                 | | v1.1.2  | |                           |
 |                 | |_________| |________________________   |
 |                 \_____________/   by Giuliano Bellini  )  |
 |                 / ''''''''''' \                       /   |
 |                / ::::::::::::: \                  =D-'    |
 |               (_________________)                         |
  \_________________________________________________________/
Error: GraphicsCreationFailed(GraphicsAdapterNotFound)
```

**Comment by figsoda** [comment]
Are you using wayland by any chance? I only tested it on x11

**Comment by teto** [comment]
nope, I am using i3 with the nvidia drivier. I just wanted to try it, if it works for you then I dont mind.

**Comment by figsoda** [comment]
works for me with amd gpu, [here](https://github.com/iced-rs/iced/blob/d7fffaa801423ae989fa7693f5b1cb424194e1ff/README.md#graphicsadapternotfound) is the upstream documentation for the error, not exactly sure what's missing

**Comment by teto** [comment]
I'll wait for a fix then, not motivated enough to debug.

**Comment by figsoda** [comment]
can you test https://github.com/NixOS/nixpkgs/pull/222191?

**Pull request merged**
