### PR TITLE
lua.tests.checkSetupHook: test lua setup hook for http package

### PR DESCRIPTION
**Pull request by teto**
Fixes https://github.com/NixOS/nixpkgs/pull/286822#issuecomment-2029454092

the 'http' package is an interesting one to test because all its lua
files are in a 'http' subfolder, ie., there is no share/lua/5.1/*.lua,
only share/lua/5.1/http/*.lua files unlike most packages. This tests we
can match those subfolders.

Will retarget against staging before merge

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by GaetanLepage — APPROVED** [review]
LGTM

**Comment by flokli** [comment]
LGTM too. Also successfully built `knot-resolver` too.

Let's land this. I'll leave it up to @vcunat  to possibly cherrypick this into `staging-next` in case channels are blocked without this fix.

**Comment by vcunat** [comment]
That iteration of staging-next is in master already, and knot-resolver got a workaround that at least lets you use it without `luajitPackages.http` (as most people don't use it, I think).

**Comment by flokli** [comment]
For posterity: 4cad0502dbb4e9ca487b7b59d8f936d5ad64b7f8 and 11fd36353e62a9815413aef7c7273a49458f84d5.

@vcunat With this now merged, can you open a PR reverting the workaround to staging-next (and link to here)?

**Comment by vcunat** [comment]
I certainly planned that, though maybe a bit later.

**Comment by SuperSandro2000** [comment]
> as most people don't use it, I think

I've also run into this. I think the most common usecase for the http module is the prometheus metrics.

**Comment by vcunat** [comment]
Ah, right.  Perhaps I forgot because mentally I'm in 6.x where it's not needed for prometheus.  I should soon think about (NixOS) strategy for migration to 6.x, too.

**Comment by flokli** [comment]
I opened https://github.com/NixOS/nixpkgs/pull/301747, which re-enables the http module for knot-resolver (targeting staging, as the fix is only on staging too). PTAL.

**Comment by vcunat** [comment]
`lua*.tests.checkSetupHook` got broken very fast again &ndash; it doesn't work on current `staging-next` branch already, and consequently `knot-resolver` also fails again.

**Pull request merged**
