### PR TITLE
emacs: allow X and cli-only builds on Darwin

### PR DESCRIPTION
**Pull request by thefloweringash**
###### Motivation for this change

It's possible to configure Emacs on Darwin to build as CLI-only, with lucid, or with Cocoa. Nixpkgs currently does not allow this configuration, and always forces building with Cocoa.

Based on the assertions, building with GTK2 and GTK3 (without X11?) is supported on macOS, but the `buildInputs` value doesn't seem to match this, and only provides gtk if `withX = true`. As is, trying to build with `withX = true; withGTK2 = true;` or `withX = true; withGTK3 = true;` does not succeed.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by oxij** [comment]
>      ++ lib.optionals withX
>        [ xlibsWrapper libXaw Xaw3d libXpm libpng libjpeg libungif libtiff librsvg libXft
> -        imagemagick gconf m17n_lib libotf ]
> +        imagemagick gconf ]
> +    ++ lib.optionals (stdenv.isLinux && withX) [ m17n_lib libotf ]
>      ++ lib.optional (withX && withGTK2) gtk2
>      ++ lib.optionals (withX && withGTK3) [ gtk3 gsettings-desktop-schemas ]

This looks strange to me. Can you build withX on Darwin?

Also /cc @matthewbauer

**Comment by matthewbauer** [comment]
Yep x11 can work on macOS. I think it isn’t used much but might be useful for things like xwidgets and stuff.

**Comment by thefloweringash** [comment]
After reading your comments, I had another look at the gtk2/gtk3 support in emacs. It seems like if building against gtk, it must be X11 gtk. I've pushed an updated version of the patch to use `gtk2-x11` instead of `gtk2` and `gtk3-x11` instead of `gtk3`, and now all configurations build and run on macOS.

**Comment by thefloweringash** [comment]
What's the cause of the `has: clean-up` label?

**Comment by matthewbauer** [comment]
I think it just calls anything that’s not a new package a clean up.

**Comment by matthewbauer** [comment]
@grahamcofborg build emacs

**Pull request merged**
