### PR TITLE
audacity: 2.1.2 -> 2.1.3

### PR DESCRIPTION
**Pull request by matthiasbeyer**
###### Motivation for this change

2.1.2 fails with "Assertion failed" when recording, so I want to try an update.

Unfortunately **this does not build yet**. Maybe the maintainer @the-kenny can help me here?

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Removing the second patch gets me to

```
configure: error: You requested using the local libraries for FFMPEG but they are not available
builder for ‘/nix/store/bk1k7jksqb9mc764glk89yy50c5yk9gf-audacity-2.1.3.drv’ failed with exit code 1
error: build of ‘/nix/store/bk1k7jksqb9mc764glk89yy50c5yk9gf-audacity-2.1.3.drv’ failed
```

which seems to be one step closer if I interpret that correctly? Not sure.

**Comment by the-kenny** [comment]
One solution would be throwing out the first four lines in `preConfigure` which will cause `audacity` to use the bundled `ffmpeg` etc. I'm not sure if that's a nice solution, but it's a solution.

Right now I'm trying the build where I run `autoreconf` in `preConfigure` like arch does: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/audacity

This seems to make audacity use the system libraries. You need to add `autoconf automake libtool` to `buildInputs` for this to work.

**Comment by the-kenny** [comment]
The `autoreconf -vi` thing seems to work here, I get a `2.1.3` audacity (from this branch) which is linked against the system's `ffmpeg` libs (among others).

**Comment by matthiasbeyer** [comment]
Okay, with these changes applied my build is running now. Although I had to remove the patch as mentioned earlier. Will push my changes for you to review as soon as my build succeeded! Thanks for your suggestions!

**Comment by matthiasbeyer** [comment]
@the-kenny Changes pushed. I mentioned you in 2432ca1! I guess you would like me to squash all changes into one commit - if you want to, I can do that (and keep you in the `Suggested-by` trailer, of course).

**Comment by the-kenny** [comment]
LGTM. Squashing would be nice, thanks in advance!

**Comment by Mic92** [comment]
Thanks!

**Pull request merged**
