### PR TITLE
zabbixctl: init at unstable-2019-07-06

### PR DESCRIPTION
**Pull request by mmahut**
###### Motivation for this change

 init at unstable-2019-07-06

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by aanderse** [comment]
@mmahut It looks like you accidentally included some exiv related work in here.

**Comment by mmahut** [comment]
@aanderse oops, sorry. Rebased.

**Comment by aanderse** [comment]
Time to test out my new [super powers](https://github.com/NixOS/ofborg/pull/376) and see if this build on darwin ...

@GrahamcOfBorg build zabbixctl

**Review by aanderse — APPROVED** [review]
Quick review shows no issues. Perfect formatting. I built and ran locally the previous commit with no noticeable issues. LGTM :+1:

**Pull request merged**
