### PR TITLE
burpsuite: 2023.1.2 -> 2023.2.4

### PR DESCRIPTION
**Pull request by stepech**
###### Description of changes

Changelog: https://portswigger.net/burp/releases

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by marcusramberg — APPROVED** [review]

**Comment by buckley310** [comment]
LGTM. I ran the embedded browser for a bit and browsed a few sites. everything worked as expected.

**Comment by MGlolenstine** [comment]
Closed #219199

**Comment by AkechiShiro** [comment]
@buckley310 did you try on Wayland or X11? Or have you tried on both ?

**Comment by buckley310** [comment]
Gnome/x11 only

**Comment by buckley310** [comment]
Is there an issue on wayland or are you just checking test coverage?

**Comment by AkechiShiro** [comment]
I've encountered some crashes of the browser (on an older stable version) and for the 2023.1.2, I can't seem to get it to run under Wayland, I ran into something very similar to this issue : https://github.com/NixOS/nixpkgs/issues/12472 but the workaround, nor the fix seems to help in any way.

Running `2023.1.2-18945 Burp Suite Community Edition` : 
```
Could not start Burp: java.lang.Error: Cannot load com.sun.java.swing.plaf.gtk.GTKLookAndFeel
```

I must mention however that I'm using Nix on Archlinux (WM : Sway) and not directly under NixOS.

I haven't tried yet `2023.2.4` and also the package from the AUR (Archlinux User Repository) is working fine under Wayland, so I believe, it could be a Nix quirk.

**Comment by buckley310** [comment]
Tested recently on hyprland on nixos and it works properly. So yeah, could be a bug specific to non-nixos environments. OpenGL drivers perhaps?

**Comment by AkechiShiro** [comment]
OpenGL issues might be explaining crashes of the browser but the Java errors seems to happen no matter if I use X11 or Wayland, so it's another issue but it only happens on Non-NixOS OSes, it seems and I didn't figure out a way to fix it nor how I should investigate it further yet.

**Comment by Nebucatnetzer** [comment]
I was able to fix the crashes the following options for a devshell: https://github.com/NixOS/nixpkgs/issues/12472#issuecomment-2137006186

**Pull request merged**
