### PR TITLE
nixos/i18n: override pkgs.glibcLocales

### PR DESCRIPTION
**Pull request by volth**
A possible way to strip 100Mb from the tarball is to set explicitly ```i18n.supportedLocales``` to a reasonably small number of locales.
[It is used in minimal.nix and CD images](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=i18n.supportedLocales&type=)

Surprisingly, sometimes it does not reduce the tarball because [many packages]( https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=glibcLocales&type=) (notably python libraries) refer to non-overriden ```pkgs.glibcLocales``` which supports all locales, so the tarball end up having two glibcLocales - the small and the big:

cc: @FRidh @anvik

### CODE REVIEW

**Comment by FRidh** [comment]
I think it is good to be able to easily modify the supported locales on the system and thereby reduce the `glibcLocales` that is added to the environment. However, I am against overriding the package set because it will cause a rebuild of many packages. In the case of the Python packages don't expect `glibcLocales` to be a run-time requirement. Furthermore, I am not sure whether using an overlay here is such a good idea. Won't it break the users' possibility to use an overlay in `configuration.nix`?

**Comment by edolstra** [comment]
Why do packages use `glibcLocales` as a runtime dependency rather than respecting `$LOCALE_ARCHIVE`? (Using it as a build-time dependency is fine.)

**Comment by volth** [comment]
> I am not sure whether using an overlay here is such a good idea. 

It was @anvik idea which failed for unknown reason (see the extended comment of https://github.com/nixos/nixpkgs/commit/2c54fa04be3fe64f7934a31d3469773b13bd3a5d)

> Won't it break the users' possibility to use an overlay in configuration.nix?

No, they are merged.

**Comment by avnik** [comment]
@edolstra  supplying glibcLocales with packageOverrides not works (at least in past), it why I submit 2c54fa0  -- I had legacy application which depends on debian's patched locales.

https://github.com/NixOS/nixpkgs/pull/22489 PR which I sumbitted.
And example of using (with non-working override in comments as well -- https://github.com/avnik/nixos-configs/blob/master/common/i18n.nix#L58

**Pull request closed without merging**
