### PR TITLE
typst-preview: 0.10.8 -> 0.11.1

### PR DESCRIPTION
**Pull request by drupol**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by drupol** [comment]
Hey @Enter-tainer,

We have issue to package `typst-preview` 0.10.10, do you have clue on what is going on based on the log I posted up there ?

**Comment by drupol** [comment]
Oh wait, I think I got it.

**Comment by Enter-tainer** [comment]
could you update it after i publish 0.11.0? 0.10.10 is on typst 0.11.0-rc1. And incoming typst-preview 0.11.0 will update typst to 0.11.0.

hopefully it will comes hours later(when i leave work)

**Comment by drupol** [comment]
> could you update it after i publish 0.11.0? 0.10.10 is on typst 0.11.0-rc1. And incoming typst-preview 0.11.0 will update typst to 0.11.0.
> 
> hopefully it will comes hours later(when i leave work)

OK I'll wait tomorrow :)

**Comment by Enter-tainer** [comment]
I've finished the update. FYI:
1. the path of html has changed to `/src/index.html`

**Comment by drupol** [comment]
> I've finished the update. FYI:
> 
>     1. the path of html has changed to `/src/index.html`

I don't think we specify the path of HTML in the derivation, so I guess it's OK.

**Comment by Enter-tainer** [comment]
i've also published 0.11.1. because 0.11.1 has a config issue that cause ci failure. so currently the latest version is 0.11.1.

**Comment by Enter-tainer** [comment]
the ci is running! not finished yet.

oh it just finished

**Comment by drupol** [comment]
OK update is ready.

**Pull request merged**
