### PR TITLE
gitlab-runner: 15.2.0 -> 15.2.1

### PR DESCRIPTION
**Pull request by max-wittig**
###### Description of changes

https://gitlab.com/gitlab-org/gitlab-runner/blob/v15.2.1/CHANGELOG.md

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by max-wittig** [comment]
Somehow there was no need to update the hashes. Why is that? /cc @bachp @zimbatm @dlouzan

image

**Comment by zimbatm** [comment]
It's because it pulls the old hash from the cache. Try putting a wrong hash and rebuild, nix will complain and give you the right one. Same for the vendorSha256.

**Comment by max-wittig** [comment]
@zimbatm I don't understand this. There is no `old hash` here I think. Nix does not complain, as the hash is clearly wrong for this gitlab-runner version.

**Review by yayayayaka — COMMENTED** [review]
I think zimbatm meant to replace the hashes with `lib.fakeSha256` temporarily and it would complain about the mismatch between the expected (i.e. `fakeSha256`) and the actual hash (i.e. gitlab-runner 15.2.1 hash). This method is described in the nixpkgs manual [there](https://nixos.org/manual/nixpkgs/stable/#sec-source-hashes).

```
error: hash mismatch in fixed-output derivation '/nix/store/1w07ywabj2cb27xgdifi6rsfnqaiyy1a-source.drv':
         specified: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
            got:    sha256-HaFxMNREHTtnbIuQUXCinhd4lhcnkLkacLczeySsfWQ=
error: 1 dependencies of derivation '/nix/store/g08aq08x3f97mhr6x0kxy9v9wjw0mk9v-gitlab-runner-15.2.1.drv' failed to build
```

```
error: hash mismatch in fixed-output derivation '/nix/store/mfqby0ynccd8m8chb7z4bxl15symy4bw-gitlab-runner-15.2.1-go-modules.drv':
         specified: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
            got:    sha256-weT4Ed/VNTLovxUu2xCdHDqxY7v/5Wi3WsWlNDWYLLc=
error: 1 dependencies of derivation '/nix/store/6zjmz7l99293nq3z9s7mbwlixbvmnrzr-gitlab-runner-15.2.1.drv' failed to build
```

The overall diff would be:
```diff
diff --git a/pkgs/development/tools/continuous-integration/gitlab-runner/default.nix b/pkgs/development/tools/continuous-integration/gitlab-runner/default.nix
index b97e02dba0e..bd1e4c5db29 100644
--- a/pkgs/development/tools/continuous-integration/gitlab-runner/default.nix
+++ b/pkgs/development/tools/continuous-integration/gitlab-runner/default.nix
@@ -14,13 +14,13 @@ buildGoModule rec {
     "-X ${commonPackagePath}.REVISION=v${version}"
   ];
 
-  vendorSha256 = "sha256-0lp4Hd6j7G59clWxLfz8GfQEmpXmhuGzmgX2ws/VJeQ=";
+  vendorSha256 = "sha256-weT4Ed/VNTLovxUu2xCdHDqxY7v/5Wi3WsWlNDWYLLc=";
 
   src = fetchFromGitLab {
     owner = "gitlab-org";
     repo = "gitlab-runner";
     rev = "v${version}";
-    sha256 = "sha256-1OflKz8AV8vSCkNBWGteIbXqbueAYNeAdp9nL3lgD8A=";
+    sha256 = "sha256-HaFxMNREHTtnbIuQUXCinhd4lhcnkLkacLczeySsfWQ=";
   };
 
   patches = [
```

**Comment by max-wittig** [comment]
@yayayayaka I still don't understand why it worked without modifying the hashes. Isn't that like a security issue, if it just accepts the old hashes and the new version?

**Comment by zimbatm** [comment]
It's a common trap that everybody has to fall into at least once. There are two types of derivations in nix: input derivations and fixed-output derivations.

Input derivations are the most common ones where you specify all the inputs. When building, it injects all the inputs in the build sandbox, and that's the only things it will use during the build. The output hash is determined by the hash of all the inputs. If the inputs changes, you get a new hash, and it causes a rebuild.

Output derivations are used to fetch things on the Internet. That's where the user specified the expected hash (like fetchurl, fetchFromGitHub, ...). When building, there is no sandbox, and it can talk to the Internet. The output hash is determined by the hash that the user specified. After the build it will check that the output hash is the same as the specified one. A rebuild only happens if the passed hash changes. So passing a different URL is not causing a rebuild.

Another thing to know is that by default, Nix will query `https://cache.nixos.org/<hash>.narinfo`. If it exists, it will download the build result instead of rebuilding it. So even if you didn't build the package's old version, it might still fetch the old source from there.

**Comment by dlouzan** [comment]
@zimbatm I'm confused as to what would happen then if no rebuild is triggered:

- Will the wrong version be used, so it will be as it was never updated, even if the metadata says so?
- Or will it use the right version but then later will fail when trying to use it because it wouldn't match? 
- Or will everything work even if no proper hash validation was done?
- ...

Thanks for the input!

**Comment by max-wittig** [comment]
@zimbatm But it's ready now, if you wanna review.

**Comment by max-wittig** [comment]
@bachp @yayayayaka

**Comment by zimbatm** [comment]
@dlouzan the wrong version of the source would be used by everybody who is using the cache (including hydra). If somebody builds with a disabled cache their nix would fetch the URL and fail because the hashes are mismatching.

**Pull request merged**
