### PR TITLE
Fix Spidermonkey builds (on ARM)

### PR DESCRIPTION
**Pull request by Jookia**
###### Motivation for this change

This fixes all Spidermonkey builds on ARM. It's a bit controversial in that it uses GCC 4.9 for Spidermonkey 1.7 which stops MethodJIT from breaking. This bug was found in master a few days ago and the tests were disabled, which I suspect means we just have a broken Spidermonkey MethodJIT on ARM. Short of disabling it, this is the only way I could fix it.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dezgeg** [comment]
Yes, this is a weird problem that started to occur since the GCC 5.4 bump. As far as I can tell we get an unalignment trap from a vector instruction where 8-byte alignment is required but the address is only 4-byte aligned:
````
   0x21e4f0 <js::mjit::Compiler::finishThisUp()+5272>:	cmp	r1, r8
   0x21e4f4 <js::mjit::Compiler::finishThisUp()+5276>:	bls	0x21e5fc <js::mjit::Compiler::finishThisUp()+5540>
   0x21e4f8 <js::mjit::Compiler::finishThisUp()+5280>:	cmp	r3, #0
   0x21e4fc <js::mjit::Compiler::finishThisUp()+5284>:	beq	0x21e51c <js::mjit::Compiler::finishThisUp()+5316>
=> 0x21e500 <js::mjit::Compiler::finishThisUp()+5288>:	vst1.8	{d16-d17}, [r3 :64]
   0x21e504 <js::mjit::Compiler::finishThisUp()+5292>:	vstr	d16, [r3, #16]
   0x21e508 <js::mjit::Compiler::finishThisUp()+5296>:	vstr	d16, [r3, #24]
   0x21e50c <js::mjit::Compiler::finishThisUp()+5300>:	vstr	d16, [r3, #32]
   0x21e510 <js::mjit::Compiler::finishThisUp()+5304>:	vstr	d16, [r3, #40]	; 0x28
   0x21e514 <js::mjit::Compiler::finishThisUp()+5308>:	vstr	d16, [r3, #48]	; 0x30
   0x21e518 <js::mjit::Compiler::finishThisUp()+5312>:	vstr	d16, [r3, #56]	; 0x38
   0x21e51c <js::mjit::Compiler::finishThisUp()+5316>:	ldr	lr, [r2]

(gdb) p/x $r3
$5 = 0x3963fc

(gdb)  bt
#0  0x0021e500 in js::mjit::Compiler::finishThisUp (this=<optimized out>) at /tmp/nix-build-spidermonkey-17.0.0.drv-0/mozjs17.0.0/js/src/methodjit/Compiler.cpp:1672
#1  0x0023d99c in js::mjit::Compiler::performCompilation (this=this@entry=0xbeff8e78) at /tmp/nix-build-spidermonkey-17.0.0.drv-0/mozjs17.0.0/js/src/methodjit/Compiler.cpp:545
#2  0x0023db0c in js::mjit::Compiler::compile (this=this@entry=0xbeff8e78) at /tmp/nix-build-spidermonkey-17.0.0.drv-0/mozjs17.0.0/js/src/methodjit/Compiler.cpp:116
#3  0x0023de60 in js::mjit::CanMethodJIT (cx=0x387708, script=0xb520d4a0, pc=0x0, construct=<optimized out>, request=js::mjit::CompileRequest_Interpreter, frame=0xb5e000a8) at /tmp/nix-build-spidermonkey-17.0.0.drv-0/mozjs17.0.0/js/src/methodjit/Compiler.cpp:1020
#4  0x000a213c in js::Interpret (cx=0x387708, entryFrame=0x188, entryFrame@entry=0xb5e00020, interpMode=(unknown: 3204428056), interpMode@entry=js::JSINTERP_NORMAL) at /tmp/nix-build-spidermonkey-17.0.0.drv-0/mozjs17.0.0/js/src/jsinterp.cpp:1465
#5  0x000a2d54 in js::RunScript (cx=cx@entry=0x387708, script=<optimized out>, fp=<optimized out>) at /tmp/nix-build-spidermonkey-17.0.0.drv-0/mozjs17.0.0/js/src/jsinterp.cpp:309
#6  0x000a3fe8 in js::ExecuteKernel (result=0x0, evalInFrame=0x0, type=js::EXECUTE_GLOBAL, thisv=..., scopeChain=..., script=..., cx=0x387708) at /tmp/nix-build-spidermonkey-17.0.0.drv-0/mozjs17.0.0/js/src/jsinterp.cpp:494
#7  js::Execute (cx=cx@entry=0x387708, script=script@entry=..., scopeChainArg=..., rval=rval@entry=0x0) at /tmp/nix-build-spidermonkey-17.0.0.drv-0/mozjs17.0.0/js/src/jsinterp.cpp:532
#8  0x00025138 in JS_ExecuteScript (cx=cx@entry=0x387708, objArg=0xb5209040, objArg@entry=0x0, scriptArg=scriptArg@entry=0xb520d438, rval=0x0) at /tmp/nix-build-spidermonkey-17.0.0.drv-0/mozjs17.0.0/js/src/jsapi.cpp:5633
#9  0x00018f84 in Process (cx=cx@entry=0x387708, obj_=0x0, obj_@entry=0xb5209040, filename=<optimized out>, forceTTY=forceTTY@entry=false) at /tmp/nix-build-spidermonkey-17.0.0.drv-0/mozjs17.0.0/js/src/shell/js.cpp:433
#10 0x0001c208 in ProcessArgs (op=0xbeffdc98, obj_=0xb5209040, cx=0x387708) at /tmp/nix-build-spidermonkey-17.0.0.drv-0/mozjs17.0.0/js/src/shell/js.cpp:4795
#11 Shell (cx=cx@entry=0x387708, op=op@entry=0xbeffdc98, envp=<optimized out>) at /tmp/nix-build-spidermonkey-17.0.0.drv-0/mozjs17.0.0/js/src/shell/js.cpp:4847
#12 0x00013cd8 in main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at /tmp/nix-build-spidermonkey-17.0.0.drv-0/mozjs17.0.0/js/src/shell/js.cpp:5022
````
and the code is:
````
    ic::GetElementIC *jitGetElems = (ic::GetElementIC *)cursor;
    chunk->nGetElems = getElemICs.length();
    cursor += sizeof(ic::GetElementIC) * chunk->nGetElems;
    for (size_t i = 0; i < chunk->nGetElems; i++) {
        ic::GetElementIC &to = jitGetElems[i];
        GetElementICInfo &from = getElemICs[i];

        new (&to) ic::GetElementIC();                          // <--------- this line
        from.copyTo(to, fullCode, stubCode);

        to.typeReg = from.typeReg;
        to.objReg = from.objReg;
        to.idRemat = from.id;
````
It's pretty weird to see vector instructions there, but I guess that's an inlined vector-optimized memset. So either those pointer-casting tricks are operating on not-enough aligned memory or GCC 5.4 is buggy.

One thing that might fix this (maybe by accident) would be to change the FPU flags used by GCC. I'm planning to do this anyway since somebody told me the current FPU flags don't work on Scaleway. So I'll try that first.

**Comment by Jookia** [comment]
Very interesting! Will this also address the other build failures? I had to fix
multiple versions of Spidermonkey to get them to build.

**Comment by dezgeg** [comment]
Quite possible that the other versions could be crashing in the same way, after all they probably won't rewrite their JIT compiler from scratch too often... Now rebuilding the world, so we'll see.

**Comment by Jookia** [comment]
The tests run fine, which are the same tests that detected the crashing

**Comment by dezgeg** [comment]
Changing the FPU flags made the tests work with GCC 5 again. So once I rebuild other parts of my system to check for any breakage, I will pick up the `185` and `31` fixes to go with that.

**Comment by dezgeg** [comment]
Everything has been pushed for some time now: https://github.com/NixOS/nixpkgs/compare/b3adffcd5681...33a1d8080b50 and all the spidermonkeys build. Thanks.

**Pull request closed without merging**
