### PR TITLE
circup: 1.2.1 -> 1.2.3

### LINKED ISSUE #243313: Update request: circup 1.2.1 → 1.2.3
- Package name: circup
- Latest released version: 1.2.3
- Current version on the unstable channel: 1.2.1
- Current version on the stable/release channel: 1.2.1
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@fabaff 

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by Janik-Haag**
###### Description of changes
https://github.com/adafruit/circup/releases/tag/1.2.3

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

close #243313

### CODE REVIEW

**Comment by fabaff** [comment]
Please use `nix-update` or add the link to the changelog manually as stated in [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

**Comment by Janik-Haag** [comment]
I used nix-update, what makes you think I didn't?

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 243314` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>circup</li>
    <li>circup.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
> I used nix-update, what makes you think I didn't?

Because the changelog is not part of the commit message. `nix-update` adds the changelog. Not sure when the feature was added to `nix-update` but it's already present for a while.

**Comment by Janik-Haag** [comment]
I have nix-update 0.18.0 and used `nix-update circup --commit` which didn't add a change log to the commit message.

**Comment by fabaff** [comment]
Hmmm, seems to work on NixOS unstable.

```bash
$ nix-env --query --available --attr-path nix-update
nixos.nix-update  nix-update-0.18.0

$ nix-update circup --build --commit
[...]
} --extra-experimental-features flakes nix-command
$ git -C /home/fab/Documents/repos/nixpkgs commit --verbose --message circup: 1.2.1 -> 1.2.3

Diff: https://github.com/adafruit/circup/compare/refs/tags/1.2.1...1.2.3

Changelog: https://github.com/adafruit/circup/releases/tag/1.2.3 /home/fab/Documents/repos/nixpkgs/pkgs/development/tools/circup/default.nix
[circup-bump 914fefa3c20] circup: 1.2.1 -> 1.2.3
 1 file changed, 2 insertions(+), 2 deletions(-)
```

**Review by fabaff — APPROVED** [review]
Change looks good to me.

**Pull request merged**
