### PR TITLE
c-ares: 1.17.1 -> 1.17.2

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change
https://c-ares.haxx.se/adv_20210810.html

<s>21.05: #133378</s>

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by andir — APPROVED** [review]

**Comment by TredwellGit** [comment]
This might be causing DNS issues on staging.
```
$ nix build -f . --no-link c-ares
warning: unable to download 'http://tarballs.nixos.org/sha256/4803c844ce20ce510ef0eb83f8ea41fa24ecaae9d280c468c582d2bb25b3913d': Couldn't resolve host name (6); retrying in 289 ms
warning: unable to download 'http://tarballs.nixos.org/sha256/4803c844ce20ce510ef0eb83f8ea41fa24ecaae9d280c468c582d2bb25b3913d': Couldn't resolve host name (6); retrying in 587 ms
warning: unable to download 'http://tarballs.nixos.org/sha256/4803c844ce20ce510ef0eb83f8ea41fa24ecaae9d280c468c582d2bb25b3913d': Couldn't resolve host name (6); retrying in 1401 ms
warning: unable to download 'http://tarballs.nixos.org/sha256/4803c844ce20ce510ef0eb83f8ea41fa24ecaae9d280c468c582d2bb25b3913d': Couldn't resolve host name (6); retrying in 2128 ms
warning: unable to download 'https://c-ares.haxx.se/download/c-ares-1.17.2.tar.gz': Couldn't resolve host name (6); retrying in 351 ms
warning: unable to download 'https://c-ares.haxx.se/download/c-ares-1.17.2.tar.gz': Couldn't resolve host name (6); retrying in 620 ms
warning: unable to download 'https://c-ares.haxx.se/download/c-ares-1.17.2.tar.gz': Couldn't resolve host name (6); retrying in 1018 ms
warning: unable to download 'https://c-ares.haxx.se/download/c-ares-1.17.2.tar.gz': Couldn't resolve host name (6); retrying in 2660 ms
builder for '/nix/store/a6vp8nwp14wl6vsvlbw7124pba93n58l-c-ares-1.17.2.tar.gz.drv' failed with exit code 1; last 1 log lines:
  error: unable to download 'https://c-ares.haxx.se/download/c-ares-1.17.2.tar.gz': Couldn't resolve host name (6)
cannot build derivation '/nix/store/8fl5kxahjyc7g6p9r4zhyrprizwznz06-c-ares-1.17.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/maha83w9hdziwrlflpakf9syjcpyngfk-nghttp2-1.43.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/1awgj2jxyqnjpvnl338g1vh0b2r1vgdb-curl-7.76.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ga1s3j5f3fx09splb2ikiwbcvjms2c16-c-ares-1.17.2.tar.gz.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/5kx968rlbn44r509vxj4b29d988n58r7-c-ares-1.17.2.drv': 1 dependencies couldn't be built
[0 built (1 failed)]
error: build of '/nix/store/5kx968rlbn44r509vxj4b29d988n58r7-c-ares-1.17.2.drv' failed
```

**Comment by tomberek** [comment]
I'm getting a good build. But Hydra does look like it has stalled on other jobs and there are lots of cancellations.

**Comment by mweinelt** [comment]
Hydra isn't even building the staging branch until it hits staging-next, so not sure why it would stall at this time.

The build works if I prefetch the tarball, not sure what's wrong here.

**Comment by TredwellGit** [comment]
Seems to build now.

**Comment by vcunat** [comment]
`fetchurlBoot` was broken with current Nix: https://github.com/NixOS/nix/pull/5224

Breakage on Hydra: https://hydra.nixos.org/eval/1702813

**Pull request merged**
