### PR TITLE
nixos/dhcpd: make hard-coded options configurable

### PR DESCRIPTION
**Pull request by arezvov**
###### Motivation for this change

I need to change hard-coded dhcpd options default-lease-time, max-lease-time, ddns-update-style (without using configFile) and I think it can be useful for someone else. Also I ran nixfmt on dhcpd.nix and if it's a bad practice i'll revert these changes.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
nixfmt should be in a separate commit to ease review

**Comment by arezvov** [comment]
I applied your suggestions.

**Comment by bb2020** [comment]
Is specifying those values in `extraConfig` also a solution?

**Comment by wigust** [comment]
@bb2020 
> Is specifying those values in `extraConfig` also a solution?

I didn't check this, but it's not IMHO.  If I understand correctly, you asking about duplicating settings by adding them in `extraConfig`. It will definitely lead to a not looking clear and misleading configuration file. E.g. if I specify same settings as in the default configuration but with different values via `extraConfig`, then some months later another person will take a look on the DHCP configuration file output without looking on Nix configuration, how would he know which values are active without reading a dhcpd.conf manual or testing this?

**Comment by bb2020** [comment]
Yeah. The `conf` file would be a mess.

**Comment by ajs124** [comment]
#224635

**Pull request closed without merging**
