### PR TITLE
binutils 2.41 -> 2.42

### PR DESCRIPTION
**Pull request by silvanshade**
## Description of changes

This PR updates `binutils` to version `2.42`.

I removed two patches:

- `gold-powerpc-for-llvm.patch`: seems to be applied upstream
- `0001-libtool.m4-update-macos-version-detection-block.patch`: doesn't apply; not clear if it's still needed

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

@Ericson2314 @lovesegfault

### CODE REVIEW

**Comment by skeuchel** [comment]
This should target the staging branch because of the mass rebuild.

**Comment by skeuchel** [comment]
The previous PR mentions a couple of needed fixes for 2.42 https://github.com/NixOS/nixpkgs/pull/283732#issuecomment-1920973878.

**Comment by skeuchel** [comment]
Could you rebase the PR by following the instructions in the [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging).

I built a bunch of packages and a couple failed:
- `kexec-tools`: [fix is in upstream](https://git.kernel.org/pub/scm/utils/kernel/kexec/kexec-tools.git/commit/?id=328de8e00e298f00d7ba6b25dc3950147e9642e6) repo and will be included in the next release.
- `python311Packages.curio`: This is a new one. Has already been [reported upstream](https://github.com/dabeaz/curio/issues/368).

**Comment by silvanshade** [comment]
> Could you rebase the PR by following the instructions in the [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging).

Okay, I think I changed it to the way it was described. Let me know if there's still something else that needs to be changed with that.

**Comment by JohnRTitor** [comment]
It's still marked as draft @silvanshade perhaps you want to change that. Draft PRs can not be merged.

**Comment by lovesegfault** [comment]
cc. @trofi

**Comment by trofi** [comment]
Looking at https://github.com/NixOS/nixpkgs/pull/283732#issuecomment-1920973878 `nixpkgs` still needs at least two prerequisites:
- [ ] `valgrind` fix. Version update might do: https://github.com/NixOS/nixpkgs/pull/309109
- [ ] `kexec-tools` upstream [fix](https://github.com/horms/kexec-tools/commit/328de8e00e298f00d7ba6b25dc3950147e9642e6) to pull into `nixpkgs`

**Comment by trofi** [comment]
Proposed `kexec-tools` fix as https://github.com/NixOS/nixpkgs/pull/312313

**Comment by lovesegfault** [comment]
I'm going to wait for both of the prereqs to land in master, then kick off a mass build and see what happens :)

**Comment by JohnRTitor** [comment]
> I'm going to wait for both of the prereqs to land in master, then kick off a mass build and see what happens :)

Those PRs are still in staging-next. But I think we can rebase this PR to the latest staging. 

@silvanshade

**Comment by lovesegfault** [comment]
Rebased, kicking off the build

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 304035` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>clang</li>
    <li>gcc</li>
    <li>gcc.info (gcc.info.info ,gcc.info.man)</li>
    <li>gcc.man (gcc.man.info ,gcc.man.man)</li>
    <li>linux</li>
    <li>linux.dev (linux.dev.dev)</li>
    <li>nix</li>
    <li>nix.debug (nix.debug.debug ,nix.debug.dev ,nix.debug.doc ,nix.debug.man)</li>
    <li>nix.dev (nix.dev.debug ,nix.dev.dev ,nix.dev.doc ,nix.dev.man)</li>
    <li>nix.doc (nix.doc.debug ,nix.doc.dev ,nix.doc.doc ,nix.doc.man)</li>
    <li>nix.man (nix.man.debug ,nix.man.dev ,nix.man.doc ,nix.man.man)</li>
    <li>python3</li>
    <li>python3.debug (python3.debug.debug)</li>
    <li>rustc</li>
    <li>rustc.doc (rustc.doc.doc ,rustc.doc.man)</li>
    <li>rustc.man (rustc.man.doc ,rustc.man.man)</li>
  </ul>
</details>

**Comment by lovesegfault** [comment]
I'm going to try building up to the installer ISO now.

**Comment by lovesegfault** [comment]
Okay, I cherry-picked this branch on top of `nixos-unstable` and did:

```console
$ nix build --keep-going -f nixos/release-combined.nix nixos.iso_gnome.x86_64-linux
```

Here is what I got:
```
/nix/store/h7p838lx3ys6z4ywdklqlgv8fswvrrbl-nixos-gnome-24.11pre56789.gfedcba-x86_64-linux.iso
```

I have uploaded it to https://binutils.cachix.org and pinned it: https://app.cachix.org/api/v1/cache/binutils/serve/h7p838lx3ys6z4ywdklqlgv8fswvrrbl/iso/nixos-gnome-24.11pre56789.gfedcba-x86_64-linux.iso

If someone wants to try booting that into a VM, I'd appreciate it. I'm going to build the AArch64 image now

**Comment by lovesegfault** [comment]
Alright, the aarch64-linux build was successful, I've pushed it to cachix and pinned it: https://app.cachix.org/api/v1/cache/binutils/serve/bhgrm272wfmgdgfjf7i81njb3n6lwwy8/iso/nixos-gnome-24.11pre56789.gfedcba-aarch64-linux.iso

**Comment by lovesegfault** [comment]
Fingers crossed!

**Comment by trofi** [comment]
Thanks all!

**Pull request merged**
