### PR TITLE
k3s: use nixosTests.k3s as source reference for tests + minimal refactor

### PR DESCRIPTION
**Pull request by superherointj**
- k3s: use nixosTests.k3s as source reference for tests

- k3s: minimal refactor
  - refactor passthru and expose k3s dependencies for update script
  - add missing phases hook
  - remove nested with
  - nixos/tests: move comments to test (clean-up)

I ask reviewers to avoid expanding the scope of this PR, because the refactor could go much longer and I don't have the time. Particularly update script, hash, etc.

CC @NixOS/k3s

### CODE REVIEW

**Comment by marcusramberg** [comment]
```
Exception: command `crictl img | grep 'test\.local/pause'` failed (exit code 1)
```
Looks like this pr breaks the passthru tests.

**Comment by superherointj** [comment]
> ```
> Exception: command `crictl img | grep 'test\.local/pause'` failed (exit code 1)
> ```
> 
> Looks like this pr breaks the passthru tests.

Sadly I could not reproduce the problem.

image

Does it reproduce in your host? Could be cache, who knows.

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 326575` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by superherointj** [comment]
@ofborg build k3s.passthru.tests.single-node k3s.passthru.tests.multi-node k3s.passthru.tests.etcd k3s.passthru.tests.auto-deploy

**Comment by marcusramberg** [comment]
Actually I see this failure already on the PR to update maintainers to use the team, so maybe it was introduced by #275180 but that didn't trigger passthrough tests?

**Comment by superherointj** [comment]
> Actually I see this failure already on the PR to update maintainers to use the team, so maybe it was introduced by #275180 but that didn't trigger passthrough tests?

Does it reproduce in your host?

> nix build .#k3s.passthru.tests.single-node .#k3s.passthru.tests.multi-node .#k3s.passthru.tests.etcd .#k3s.passthru.tests.auto-deploy

**Comment by superherointj** [comment]
> Actually I see this failure already on the PR to update maintainers to use the team, so maybe it was introduced by #275180 but that didn't trigger passthrough tests?

There was a problem with that PR regarding tests, it did not add `auto-deploy` to K3s package tests, only to NixOS tests. This PR exactly solves that of having to add the reference to two places.

**Comment by marcusramberg** [comment]
> > nix build .#k3s.passthru.tests.single-node .#k3s.passthru.tests.multi-node .#k3s.passthru.tests.etcd .#k3s.passthru.tests.auto-deploy

Nope, builds fine on my host too :-/

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 326575` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>k3s</li>
    <li>k3s_1_28</li>
    <li>k3s_1_29</li>
  </ul>
</details>

**Comment by wrmilling** [comment]
I do get the error on the `auto-deploy` test. 

Result of `nixpkgs-review pr 326575` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>k3s</li>
    <li>k3s_1_28</li>
    <li>k3s_1_29</li>
  </ul>
</details>

Then running the tests in the nixpkgs-review copy of nixpkgs: 

```
error: builder for '/nix/store/lr2dgfp9ylji1dyjl3d54is21m0g1msh-vm-test-run-k3s-1.30.2+k3s2-auto-deploy.drv' failed with exit code 1;
       last 10 log lines:
       >     driver.run_tests()
       >   File "/nix/store/vmq5v8zjpvb0zlvmqzvmx6c8960mpkhn-nixos-test-driver-1.1/lib/python3.12/site-packages/test_driver/driver.py", line 166, in run_tests
       >     self.test_script()
       >   File "/nix/store/vmq5v8zjpvb0zlvmqzvmx6c8960mpkhn-nixos-test-driver-1.1/lib/python3.12/site-packages/test_driver/driver.py", line 158, in test_script
       >     exec(self.tests, symbols, None)
       >   File "<string>", line 10, in <module>
       >   File "/nix/store/vmq5v8zjpvb0zlvmqzvmx6c8960mpkhn-nixos-test-driver-1.1/lib/python3.12/site-packages/test_driver/machine.py", line 611, in succeed
       >     raise Exception(f"command `{command}` failed (exit code {status})")
       > Exception: command `crictl img | grep 'test\.local/pause'` failed (exit code 1)
       > kill vlan (pid 7)
       For full logs, run 'nix log /nix/store/lr2dgfp9ylji1dyjl3d54is21m0g1msh-vm-test-run-k3s-1.30.2+k3s2-auto-deploy.drv'.
```

**Comment by superherointj** [comment]
> Possibly just an issue in [the test check escapes?](https://github.com/NixOS/nixpkgs/blob/d23ae3502ab7d1c7c33f93673a0be9ebcc48ce27/nixos/tests/k3s/auto-deploy.nix#L112-L113), from further up in the logs:

Can you try tweaking it?

**Comment by wrmilling** [comment]
> Can you try tweaking it?

Yes, though I think the escape warnings were just a red-herring. It is actually looking like a race condition on the success checks, seems to work fine locally if I change it to `machine.wait_until_succeeds`. The first `crictl` check seems to take an extra 3 seconds to succeed. The following works locally: 

```
# check if container images got imported
machine.wait_until_succeeds("crictl img | grep 'test\.local/pause'", 30)
machine.wait_until_succeeds("crictl img | grep 'test\.local/hello'", 30)
```

I just did 30 seconds so that I was not waiting the default 900 for a failure if it didn't work, but logs so it as about a 3 second delay on my machine before the first check succeeds. That said, sometimes it just worked without the wait added, but it was highly inconsistent. Adding just the wait I have not had it fail so far.

**Comment by superherointj** [comment]
> It is actually looking like a race condition on the success checks, seems to work fine locally if I change it to `machine.wait_until_succeeds`.

Thank you very much for the fix.

**Comment by wrmilling** [comment]
Result of `nixpkgs-review pr 326575` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>k3s</li>
    <li>k3s_1_28</li>
    <li>k3s_1_29</li>
  </ul>
</details>

(Above confirmed to be on [e3e0123](https://github.com/NixOS/nixpkgs/pull/326575/commits/e3e012325b3e36b4e6d1df99875cdd16976c208e), tests passed.

**Comment by superherointj** [comment]
> Actually I see this failure already on the PR to update maintainers to use the team, so maybe it was introduced by #275180 but that didn't trigger passthrough tests?

I think, what happened was, the failing pass-through test was not triggered in #275180 because K3s package didn't have a reference for it in that PR. On my host I could not see the failure, as it was a data race and my host was too capable for it to show. 
As this PR fixes the test reference, CI could trigger such failure. Phew! We got it!

Thanks everyone for the colaboration!

**Review by wrmilling — APPROVED** [review]

**Comment by superherointj** [comment]
@ofborg eval

**Review by wrmilling — APPROVED** [review]

**Review by marcusramberg — APPROVED** [review]
Nice 👌🏻

**Pull request merged**
