### PR TITLE
ibus-engines.mozc-ut: package ut dictionary

### PR DESCRIPTION
**Pull request by Programmerino**
## Description of changes

Pretty similar rationale to #189728, but for IBus. It's modeled very closely to the [ibus-mozc-ut-full](https://aur.archlinux.org/packages/ibus-mozc-ut-full) AUR package.

Creates a new package `ibus-engines.mozc-ut` which enables a new UT dictionaries option.

This is my first contribution to nixpkgs, so there's a good chance I'm not following best practices, please let me know if there is anything wrong.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by pineapplehunter** [comment]
Thanks for the work!
I am curious if we can package the dictionaries as different derivations.
If we can, I think it will make this package much cleaner.

**Comment by pineapplehunter** [comment]
@Programmerino Can you implement it in some way like this?
1. Put all the dictionary files in a separate file, Something like `dictionary.nix`. And make every dictionary a derivation with a single dictionary file as an output. (Maybe using something like fetchzip)
2. In default.nix, make a for loop and concat all the files and maybe some post-processing if needed.
3. Replace one of the dictionaries (`dictionary00.txt`?) with the newly created file.

I think this should make this easier to maintain. 
@gebner @ericsagnes Let me know if there's a better way.

**Comment by mikunimaru** [comment]
Version 2.29.5374.102 was released a few days ago; it may be prudent to verify that the build does not encounter errors with this new version as well.

**Comment by stephen-huan** [comment]
I also think it is cleaner to separate the dictionary (which can be viewed as a derivation producing the dictionary file) from the build of ibus. For example, on my NixOS configuration I have a single derivation for [mozcdic-ut](https://github.com/stephen-huan/nixos-config/blob/master/pkgs/tools/inputmethods/mozcdic-ut/default.nix) which is [exposed](https://github.com/stephen-huan/nixos-config/blob/master/pkgs/top-level/default.nix) as
```nix
mozcdic-ut = callPackage ../tools/inputmethods/mozcdic-ut {
  alt-cannadic = true;
  edict = true;
  neologd = true;
  skk-jisyo = true;
  sudachidict = true; # overwrite pkgs.sudachidict
};
```
and then the attribute `ibus-engines.mozc-ut` is created through the [overlay](https://github.com/stephen-huan/nixos-config/blob/master/overlays/ibus-engines.nix)
```nix
final: prev:


let
  self = prev.ibus-engines;
  mozcdic = final.mozcdic-ut;
in
{
  ibus-engines = self // {
    mozc-ut = final.ibus-engines.mozc.overrideAttrs (previousAttrs: {
      preBuild = previousAttrs.preBuild or "" + ''
        # Add the UT dictionary
        cat ${mozcdic}/mozcdic-ut.txt >> data/dictionary_oss/dictionary00.txt
      '';
    });
  };
}
```
separating the dictionary from the build of ibus.

**Comment by stephen-huan** [comment]
re: packaging dictionaries independently it's awkward for a number of reasons. 

The most obvious being https://dumps.wikimedia.org/jawiki/ only keeps data for the last three months while the release cycle is six months, so builds that miss the binary cache (e.g. from overlays) will inevitably break on stable NixOS.

Packaging each dictionary (other than [mozcdic-ut-personal-name](https://github.com/utuhiro78/mozcdic-ut-personal-names/), which does not come with a build script in `src` like the other dictionaries) is possible if a bit tedious. One problem is that all of the dictionaries are coupled to the contents of [src/data/dictionary_oss/id.def](https://github.com/google/mozc/blob/master/src/data/dictionary_oss/id.def) on mozc's master branch through the "mozc id", which is the row index of the first occurance of " 名詞,一般,". See [utuhiro78/merge-ut-dictionaries](https://github.com/utuhiro78/merge-ut-dictionaries/blob/main/src/remove_duplicate_ut_entries.rb)'s `remove_duplicate_ut_entries.rb`.

```ruby
url = "https://raw.githubusercontent.com/google/mozc/master/src/data/dictionary_oss/id.def"
id_mozc = URI.open(url).read.split(" 名詞,一般,")[0]
id_mozc = id_mozc.split("\n")[-1]
```

This value was recently changed from `1847` to `1843` by https://github.com/google/mozc/commit/8121eb870b66f26256995b42f069c9f4a8788953 updating the mozc internal dictionaries, which needs to be propagated to each dictionary (see https://github.com/utuhiro78/mozcdic-ut-personal-names/pull/3). Ideally, this value would be computed from the actual version of mozc packaged with nixpkgs and overwritten in each dictionary. Practically, I'm not sure the value of a reproducibly built dictionary is worth all this maintenance hassle.

Instead, I recommend following the recipe of https://github.com/NixOS/nixpkgs/pull/189728 and simply `fetchurl`'ing a fully built dictionary file from a maintainer-controlled url and appending this to `dictionary00.txt`. The dictionary could be updated, say, every year or so and the build script be maintained in or out of tree (which is essentially what [utuhiro78/merge-ut-dictionaries](https://github.com/utuhiro78/merge-ut-dictionaries) is anyways).

**Comment by stephen-huan** [comment]
This PR is redundant with https://github.com/NixOS/nixpkgs/pull/251706, but it seems that PR is substantially more ambitious than this one.

**Comment by Programmerino** [comment]
Hello, thanks for the advice everyone! Unfortunately I've made some significant changes to my system, and I'm no longer using `ibus` as part of my configuration, so I don't think it's a good idea for me maintain these changes. If someone else would like to take this on/use my changes as a base, that would be great, but for now I'll be closing this.

**Pull request closed without merging**
