### PR TITLE
python310Packages: Normalize attribute names, pnames, dirnames

### PR DESCRIPTION
**Pull request by mweinelt**
###### Description of changes

This PR takes care of most libraries that have uppercase letters in attribute/pname/dirname/

> Attribute names in python-packages.nix as well as pnames should match the library's name on PyPI, but be normalized according to [PEP 0503](https://www.python.org/dev/peps/pep-0503/#normalized-names). This means that characters should be converted to lowercase and . and _ should be replaced by a single - (foo-bar-baz instead of Foo__Bar.baz). If necessary, pname has to be given a different value within fetchPypi.

via https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#contributing-guidelines-contributing-guidelines

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Something weird is going on with the merge base here.

```
$ git log --oneline
c6b6c61f6cf (HEAD -> normalize-python-attrs, mweinelt/normalize-python-attrs) python310Packages.yapsi: Normalize attribute & pname
ed1584bce2e python310Packages.xlsxwriter: Normalize attribute & dirname
07f83b18154 python310Packages.wsme: Normalize attribute, pname, dirname
1ab877c49e4 python310Packages.theano: Normalize attribute, pname, dirname
daf490f1f9b python310Packages.rtree: Normalize attribute and dirname
4b57008582a python310Packages.quandl: Normalize attribute name
32b2d24df44 python310Packages.pyro5: Normalize attribute name
d0f1db1efd4 python310Packages.pyro4: Normalize attribute name
dd0c18a4247 python310Packages.pyvirtualdisplay: Normalize attribute, pname, dirname
5b8f20d115b python310Packages.pystemmer: Normalize attribute & pname
5214e64a288 python310Packages.pyrss2gen: Normalize attribute & pname
9a18b57a3b9 python310Packages.pymvglive: Normalize attribute & pname
0f7b057fa35 python310Packages.pylti: Normalize attribute and pname
574ec98796b python310Packages.pygithub: Normalize attribute, pname, dirname
0deebc3b247 python310Packages.pychromecast: Normalize attribute name
8a20c5e473a python310Packages.pweave: Normalize attribute & pname
d1fb8a3019b python310Packages.pmw: Normalize attribute, pname, dirname
743ad736bb1 python310Packages.nuitka: Normalize attribute & pname
02c76246183 python310Packages.nikola: Normalize attribute, pname, dirname
9e7f9a402b3 python310Packages.mako: Normalize attribute, pname, dirname
0981423ea1a python310Packages.mdp: Normalize attribute and pname
52d58e509a2 python310Packages.logbook: Normalize attribute, pname, dirname
acfd6f7704f python310Packages.kajiki: Normalize attribute name
ee9b576f25a python310Packages.jaydebapi: Normalize attribute, pname, dirname
5b1bb7e42ac python310Packages.jpype1: Normalize attribute, pname, dirname
2489cd9c266 python310Packages.htseq: Normalize attribute, pname, dirname
b03e5a85b23 python310Packages.geoip: Normalize attribute, pname, dirname
985f638488d python310Packages.formencode: Normalize attribute, pname and dirname
80192e201a7 python310Packages.fabric: Normalize attribute name and dirname
6325bb10198 python310Packages.easyprocess: Normalize attribute and pname
225dbad50b6 python310Packages.commonmark: Normalize attribute name
0b0d92d893f python310Packages.colanderalchemy: Normalize attribute and pname
34ff0bd1b5d python310Packages.blinkstick: Normalize attribute name and pname
7a2ddfb354d python310Packages.btrees: Normalize attribute name
eb813a6203f python310Packages.apscheduler: Normalize attribute, pname and location
b3557e8e31e (origin/staging) Merge staging-next into staging
```

**Comment by RonnyPfannschmidt** [comment]
is there any way to provide a deprecated alias to the old names? this looks like external users might see things just gone

**Comment by mweinelt** [comment]
We provide aliases in what is currently an append-only way through `pkgs/top-level/python-aliases.nix`, while at the same time converting all in-tree usage to the new name, to allow using nixpkgs without aliases enabled.

There currently is no way to issue a deprecation waring for aliased packages, but I agree there should be.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by Artturin** [comment]
missed one alias usage https://github.com/NixOS/nixpkgs/pull/221682

**Pull request merged**
