### PR TITLE
lowdown: 0.8.6 -> 0.9.0; nixUnstable:  2.4pre20210922 -> 2.4pre20211001

### PR DESCRIPTION
**Pull request by sternenseemann**
https://github.com/kristapsdz/lowdown/blob/0b85e777f3cdacf4210f0d624a0ceec8df612e05/versions.xml#L1126-L1166

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 139234` at 5a3ca08c run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/975af00094a10c1a9c8f93f652eafac7">hydra-unstable</a></li>
    <li><a href="https://gist.github.com/641804a58daaa6eeb9aaa6535ec57c74">nix-direnv-flakes</a></li>
    <li><a href="https://gist.github.com/9814484068428b72174851862fb544d7">nix-update</a></li>
    <li><a href="https://gist.github.com/6a0d2b4aa3bd2668c4463281fb7a73eb">nixUnstable</a></li>
    <li><a href="https://gist.github.com/d90fd634c8a977d00aed09a2da8ccb34">nixpkgs-review</a></li>
    <li><a href="https://gist.github.com/d15861e7062b485d3043795364fd9d13">rnix-lsp</a></li>
  </ul>
</details>
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>lowdown</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by sternenseemann** [comment]
So a fix to upstream into nixUnstable first…

**Comment by sternenseemann** [comment]
<https://github.com/NixOS/nix/pull/5292>

**Comment by sternenseemann** [comment]
@ofborg build nixUnstable hydra-unstable nix-direnv-flakes nix-update nixpkgs-review rnix-lsp

**Comment by sternenseemann** [comment]
@ofborg build nixStatic

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by Ma27** [comment]
Can we also backport this?

**Comment by sternenseemann** [comment]
> Can we also backport this?

I can make a backport, would move the lowdown update into a versioned attribute just to be safe.

**Comment by sternenseemann** [comment]
Backport at #140522.

**Pull request merged**
