### PR TITLE
python310Packages.huggingface-hub: 0.12.1 -> 0.14.1

### LINKED ISSUE #228897: Update request: python3Packages.huggingface_hub 0.12.1 → 0.14.1
- Package name: python3Packages.huggingface_hub
- Latest released version: 0.14.1

- Current version on the unstable channel: 0.12.1
- Current version on the stable/release channel: 0.11.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@r-ryantm (tagged as last updated package)

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by kira-bruneau**
###### Description of changes

Update to the latest version: https://github.com/huggingface/huggingface_hub/releases/tag/v0.14.1

Closes #228897

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kira-bruneau** [comment]
Result of `nixpkgs-review pr 229334` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>python310Packages.dalle-mini</li>
    <li>python310Packages.dalle-mini.dist</li>
    <li>python310Packages.shap</li>
    <li>python310Packages.shap.dist</li>
    <li>python310Packages.timm</li>
    <li>python310Packages.timm.dist</li>
    <li>python310Packages.vqgan-jax</li>
    <li>python310Packages.vqgan-jax.dist</li>
  </ul>
</details>
<details>
  <summary>34 packages built:</summary>
  <ul>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>openai-whisper (python310Packages.openai-whisper)</li>
    <li>openai-whisper.dist (python310Packages.openai-whisper.dist)</li>
    <li>python310Packages.accelerate</li>
    <li>python310Packages.accelerate.dist</li>
    <li>python310Packages.datasets</li>
    <li>python310Packages.datasets.dist</li>
    <li>python310Packages.evaluate</li>
    <li>python310Packages.evaluate.dist</li>
    <li>python310Packages.huggingface-hub</li>
    <li>python310Packages.huggingface-hub.dist</li>
    <li>python310Packages.peft</li>
    <li>python310Packages.peft.dist</li>
    <li>python310Packages.sentence-transformers</li>
    <li>python310Packages.sentence-transformers.dist</li>
    <li>python310Packages.spacy-transformers</li>
    <li>python310Packages.spacy-transformers.dist</li>
    <li>python310Packages.stanza</li>
    <li>python310Packages.stanza.dist</li>
    <li>python310Packages.tokenizers</li>
    <li>python310Packages.tokenizers.dist</li>
    <li>python310Packages.transformers</li>
    <li>python310Packages.transformers.dist</li>
    <li>python311Packages.datasets</li>
    <li>python311Packages.datasets.dist</li>
    <li>python311Packages.evaluate</li>
    <li>python311Packages.evaluate.dist</li>
    <li>python311Packages.huggingface-hub</li>
    <li>python311Packages.huggingface-hub.dist</li>
    <li>python311Packages.tokenizers</li>
    <li>python311Packages.tokenizers.dist</li>
    <li>python311Packages.transformers</li>
    <li>python311Packages.transformers.dist</li>
  </ul>
</details>

**Comment by kira-bruneau** [comment]
Everything that depends on `huggingface-hub` that failed was already failing:
- dalle-mini: https://hydra.nixos.org/job/nixpkgs/trunk/python310Packages.dalle-mini.x86_64-linux
- shap: https://hydra.nixos.org/job/nixpkgs/trunk/python310Packages.shap.x86_64-linux
- timm: https://hydra.nixos.org/job/nixpkgs/trunk/python310Packages.timm.x86_64-linux
- vqgan-jax: (unfree package, but I verified this locally)
  ```
  ERROR: Could not find a version that satisfies the requirement orbax (from flax) (from versions: none)
  ERROR: No matching distribution found for orbax
  ```

**Comment by wegank** [comment]
I guess you forgot to update the hash?

**Comment by kira-bruneau** [comment]
Omg lol well that's embarrassing 😅 Thanks!! 

Will do another nixpkgs-review

**Comment by kira-bruneau** [comment]
Result of `nixpkgs-review pr 229334` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>python310Packages.dalle-mini</li>
    <li>python310Packages.dalle-mini.dist</li>
    <li>python310Packages.shap</li>
    <li>python310Packages.shap.dist</li>
    <li>python310Packages.timm</li>
    <li>python310Packages.timm.dist</li>
    <li>python310Packages.vqgan-jax</li>
    <li>python310Packages.vqgan-jax.dist</li>
  </ul>
</details>
<details>
  <summary>34 packages built:</summary>
  <ul>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>openai-whisper (python310Packages.openai-whisper)</li>
    <li>openai-whisper.dist (python310Packages.openai-whisper.dist)</li>
    <li>python310Packages.accelerate</li>
    <li>python310Packages.accelerate.dist</li>
    <li>python310Packages.datasets</li>
    <li>python310Packages.datasets.dist</li>
    <li>python310Packages.evaluate</li>
    <li>python310Packages.evaluate.dist</li>
    <li>python310Packages.huggingface-hub</li>
    <li>python310Packages.huggingface-hub.dist</li>
    <li>python310Packages.peft</li>
    <li>python310Packages.peft.dist</li>
    <li>python310Packages.sentence-transformers</li>
    <li>python310Packages.sentence-transformers.dist</li>
    <li>python310Packages.spacy-transformers</li>
    <li>python310Packages.spacy-transformers.dist</li>
    <li>python310Packages.stanza</li>
    <li>python310Packages.stanza.dist</li>
    <li>python310Packages.tokenizers</li>
    <li>python310Packages.tokenizers.dist</li>
    <li>python310Packages.transformers</li>
    <li>python310Packages.transformers.dist</li>
    <li>python311Packages.datasets</li>
    <li>python311Packages.datasets.dist</li>
    <li>python311Packages.evaluate</li>
    <li>python311Packages.evaluate.dist</li>
    <li>python311Packages.huggingface-hub</li>
    <li>python311Packages.huggingface-hub.dist</li>
    <li>python311Packages.tokenizers</li>
    <li>python311Packages.tokenizers.dist</li>
    <li>python311Packages.transformers</li>
    <li>python311Packages.transformers.dist</li>
  </ul>
</details>

**Comment by kira-bruneau** [comment]
```shell
> huggingface-cli env

Copy-and-paste the text below in your GitHub issue.

- huggingface_hub version: 0.14.1
- Platform: Linux-6.2.10-x86_64-with-glibc2.37
- Python version: 3.10.11
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/kira/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers:
- FastAI: N/A
- Tensorflow: N/A
- Torch: N/A
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: N/A
- hf_transfer: N/A
- gradio: N/A
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /home/kira/.cache/huggingface/hub
- HUGGINGFACE_ASSETS_CACHE: /home/kira/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/kira/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by wegank** [comment]
So this PR breaks nothing, nice!

**Pull request merged**
