### PR TITLE
plasma-5: 5.14.5 -> 5.15.2

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

https://www.kde.org/announcements/plasma-5.15.0.php

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
Marking WIP because I'm not confident in the patch changes and don't want to mislead-- leaving commit in case useful but until it's looked through more carefully I don't think it's ready.  Don't want to break folks' sessions in a small way that causes pain later :).

**Comment by nyanloutre** [comment]
Hello, could you bump this to version 5.15.1 ?

https://kde.org/announcements/plasma-5.15.1.php

**Comment by dtzWill** [comment]
> Hello, could you bump this to version 5.15.1 ?

Thanks, updated!

**Comment by dtzWill** [comment]
Now with 5.15.2

**Comment by bkchr** [comment]
As far as I can tell, 5.15.2 is working for me :) Maybe time to merge this?

**Comment by dtzWill** [comment]
Been working for me as well, across updates tracked here.  Going ahead, thanks for testing!

**Comment by vcunat** [comment]
This got to master now and [the plasma test](https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.plasma5.x86_64-linux) fails now.  I suspect it's related to this update.  In logs I newly see:
```
machine# [   38.594152] xsession[860]: /nix/store/mrwhgj95xjainwmp9dld9hzb1i8dm0jj-plasma-workspace-5.15.2-bin/bin/startkde: line 347: xmessage: command not found
```
but that one just disappeared when I added `xorg.xmessage` into test's `systemPackages` and did _not_ fix the test, so these new lines seem closer to the cause
```
machine# [   38.561610] xsession[860]: /nix/store/mrwhgj95xjainwmp9dld9hzb1i8dm0jj-plasma-workspace-5.15.2-bin/bin/startkde: line 342: /nix/store/4p630wybyrzrggmjb5hm6c6nr19wq4g9-plasma-workspace-5.15.2/lib/libexec/kf5/start_kdeinit_wrapper: No such file or directory
machine# [   38.581609] xsession[860]: startkde: Could not start kdeinit5. Check your installation.
```
Any ideas?

**Comment by nyanloutre** [comment]
relevant diff of startkde between 5.14.5 and 5.15.2 :
```
342c344
< LD_BIND_NOW=true /nix/store/4p630wybyrzrggmjb5hm6c6nr19wq4g9-plasma-workspace-5.15.2/lib/libexec/kf5/start_kdeinit_wrapper --kded +kcminit_startup
---
> LD_BIND_NOW=true /nix/store/iy34pfyzm86g7wmw6pqd36zjc8z2h3vm-kinit-5.54.0/lib/libexec/kf5/start_kdeinit_wrapper --kded +kcminit_startup
```

**Comment by nyanloutre** [comment]
Found the problem, this line of patch is no longer applied : https://github.com/dtzWill/nixpkgs/blob/34a67fba04742dcbda122c50adec0d4b1871c38b/pkgs/desktops/plasma-5/plasma-workspace/plasma-workspace.patch#L443

**Comment by vcunat** [comment]
@nyanloutre: are you planning to prepare a PR/patch against nixpkgs master?

**Comment by nyanloutre** [comment]
@vcunat yes but if you already have something ready go ahead (I am currently building the plasma5 test on my machine)

**Comment by vcunat** [comment]
No, on the contrary.  I'm doing too many things already.

**Comment by nyanloutre** [comment]
See #59112 for fix

**Pull request merged**
