### PR TITLE
processing3: fix crash under XFCE, fix build in sandbox

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

Fixes https://github.com/NixOS/nixpkgs/issues/36982

### CODE REVIEW

**Comment by xeji** [comment]
local build on x86_64-linux fails: 

```
BUILD FAILED
/build/source/build/build.xml:303: The following error occurred while executing this line:
/build/source/build/build.xml:795: The following error occurred while executing this line:
/build/source/build/build.xml:422: src '/build/source/java/reference.zip' doesn't exist.

Total time: 18 seconds
builder for '/nix/store/qjkfg731m8893y3mrz53jqkc017rdkka-processing3-3.3.7.drv' failed with exit code 1
error: build of '/nix/store/qjkfg731m8893y3mrz53jqkc017rdkka-processing3-3.3.7.drv' failed
```

**Comment by volth** [comment]
@xeji did you build ```pkgs.processing3``` or ```pkgs.callPackage <nixpkgs/pkgs/applications/graphics/processing3/default.nix> {}``` ?

----

It is possible that the problem is because in ```all-packages.nix``` there is
```
  processing3 = callPackage ../applications/graphics/processing3 {
    jdk = oraclejdk8;
  };
```

and ```processing``` has various issues with nixpkgs's default ```jdk``` (OpenJDK and Zulu)

----

if it is so, it might have sense to ```s/jdk/oraclejdk8/g``` in <nixpkgs/pkgs/applications/graphics/processing3/default.nix> to avoid future confusions

**Comment by xeji** [comment]
I built `pkgs.processing3` and confirmed that this uses `oraclejdk8`. 
The error occurs only when building in a sandbox, so it is probably some kind of impurity.

**Comment by xeji** [comment]
Thanks, local build succeeds now.

**Pull request merged**
