### PR TITLE
newsboat: init at 2.10.1

### PR DESCRIPTION
**Pull request by tasmo**
A fork of Newsbeuter, an RSS/Atom feed reader for the text console.

###### Motivation for this change

Because [Newsbeuter is not actively maintained](https://github.com/akrennmair/newsbeuter/#abandoned-an-actively-maintained-fork-is-available-in-newsboat-repo) anymore.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by teto** [comment]
the program works for me but the manpage doesn t seem to be installed.

**Comment by tasmo** [comment]
@teto Thank you for commenting! I will look into it asap.

**Comment by nicknovitski** [comment]
Great minds think alike 😄 .  Feel free to include me as a maintainer.

Notes from my PR:
+ `src`: use `fetchzip` instead of `fetchurl`, because I ran into problems that I believe were caused by the zip file's hash changing..but if you haven't run into it maybe that was just a mistake on my part.
+ `Makefile`: change `a2x` to `a2x --no-xmllint`, because the linter fails when it can't download the document's DTD in the build environment.  The make target silently swallows that error so the build succeeds but the man pages are nowhere to be found.
+ `config.sh`: change `ncurses5.4` to `ncurses`, because on darwin the former name is hard-coded. 
```
postPatch = ''
    substituteInPlace config.sh \
      --replace "ncurses5.4" "ncurses"
    substituteInPlace ./Makefile \
      --replace "a2x" "${asciidoc}/bin/a2x --no-xmllint"
  '';
```
+ `postInstall`: On all platforms (not just on darwin, like my PR mistakenly had), `cp -r $src/contrib $out`.  There's color themes and scripts in that folder which I want to use, so I want the folder to be in my profile.

**Comment by tasmo** [comment]
@nicknovitski I still cannot get man pages compiled. Do you have any clue?

**Comment by nicknovitski** [comment]
@tasmo If you look at [newsboat's Makefile](https://github.com/newsboat/newsboat/blob/master/Makefile#L221-L239), you can see a bunch of lines ending in `|| true`, mostly to do with building and installing docs.  That swallows any errors on the line.  I'd suggest adding another substitution to replace them with an empty string.  That way the errors will become visible and give you more information.

Also you seem to have accidentally pulled in a bunch of other people's commits; be sure to rebase and get rid of those.

**Comment by dotlambda** [comment]
@tasmo Please close this one.

**Comment by tasmo** [comment]
Thank you @dotlambda and @Mic92!

**Pull request closed without merging**
