### PR TITLE
sqlite: 3.24.0 -> 3.25.3

### PR DESCRIPTION
**Pull request by dtzWill**
* https://sqlite.org/releaselog/3_25_3.html
* https://sqlite.org/releaselog/3_25_2.html
* https://sqlite.org/releaselog/3_25_1.html
* https://sqlite.org/releaselog/3_25_0.html

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
SQLalchemy may need updating/fixing? Not sure.

**Comment by dtzWill** [comment]
pythonPackages.sqlalchemy fails a doctest for some reason, seems to happen with sqlite 3.25+ .  Happens on current version of 1.2.11 as well as 1.2.12 and latest git.  D'oh.

**Comment by dtzWill** [comment]
@GrahamcOfBorg build pythonPackages.sqlalchemy python3Packages.sqlalchemy

**Comment by yegortimoshenko** [comment]
Rebased on top of master and bumped SQLAlchemy. Unfortunately, that didn't fix the failed test:

```
FAIL test/base/test_tutorials.py::DocTest::()::test_core
====== 1 failed, 7902 passed, 914 skipped, 1 deselected in 440.51 seconds ======
builder for '/nix/store/h190m2nwlm7q8h0j9d6z3a0dv9v6sv55-python2.7-SQLAlchemy-1.2.12.drv' failed with exit code 1
error: build of '/nix/store/h190m2nwlm7q8h0j9d6z3a0dv9v6sv55-python2.7-SQLAlchemy-1.2.12.drv' failed
```

**Comment by yegortimoshenko** [comment]
```
**********************************************************************
File "core/tutorial.rst", line 1037, in core/tutorial.rst
Failed example:
    conn.execute(stmt).fetchall()
Expected:
    SELECT addresses.user_id, count(addresses.id) AS num_addresses
    FROM addresses ORDER BY num_addresses
    ()
    [(2, 4)]
Got:
    SELECT addresses.user_id, count(addresses.id) AS num_addresses
    FROM addresses ORDER BY num_addresses
    ()
    [(1, 4)]
2018-10-13 15:23:33,398 INFO sqlalchemy.engine.base.Engine SELECT addresses.user_id, count(addresses.id) AS num_addresses
FROM addresses ORDER BY num_addresses DESC
2018-10-13 15:23:33,398 INFO sqlalchemy.engine.base.Engine ()
**********************************************************************
File "core/tutorial.rst", line 1054, in core/tutorial.rst
Failed example:
    conn.execute(stmt).fetchall()
Expected:
    SELECT addresses.user_id, count(addresses.id) AS num_addresses
    FROM addresses ORDER BY num_addresses DESC
    ()
    [(2, 4)]
Got:
    SELECT addresses.user_id, count(addresses.id) AS num_addresses
    FROM addresses ORDER BY num_addresses DESC
    ()
    [(1, 4)]
```

**Comment by dtzWill** [comment]
@GrahamcOfBorg build pythonPackages.sqlalchemy python3Packages.sqlalchemy

**Comment by dtzWill** [comment]
@GrahamcOfBorg build sqlite-analyzer

**Comment by dtzWill** [comment]
Bah, local build still sees the failure :(.

**Comment by andir** [comment]
We should probably open an issue with sqlalchemy? I think the behaviour might be undefined in this case. The first element of the tuple could be either value. If I am wrong then we still have an sqlite issue…

**Comment by dtzWill** [comment]
Agreed, especially since we've seen this for a few versions now.
If nothing else I bet they can tell us something useful without
much trouble :).

**Comment by andir** [comment]
I created an issue: https://bitbucket.org/zzzeek/sqlalchemy/issues/4370/sqlite-325x-docs-tutorialrst-doctests-fail

**Comment by andir** [comment]
We have a patch upstream that fixes this now: https://bitbucket.org/zzzeek/sqlalchemy/commits/63279a69e2b9277df5e97ace161fa3a1bb4f29cd/raw

I updated the branch to carry the fixes and squashed the SQLAlchemy change into one commit. 

cc @dtzWill

**Comment by andir** [comment]
@GrahamcOfBorg build python3Packages.sqlalchemy pythonPackages.sqlalchemy

**Comment by andir** [comment]
Rebased and fixed the commit message for sqlalchemy to actually conform to our guidelines (and ofborg should now also build it automagically).

**Comment by dtzWill** [comment]
Wow, that's great! LGTM, rebuilding with this now! (but no reason to wait for that)

**Pull request merged**
