### PR TITLE
Fix haskell-lsp and lsp-test references

### PR DESCRIPTION
**Pull request by mgttlinger**
###### Motivation for this change

Tree did not evaluate otherwise due to broken references

###### Things done

Tested that tree evaluates

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mgttlinger** [comment]
@grahamcofborg eval

**Comment by mgttlinger** [comment]
I'm not sure what to do here because the source no longer contains any reference to the old version but ofborg still picks it up from somewhere...

**Comment by cdepillabout** [comment]
Unfortunately it looks like `ghcide` depends on `haskell-lsp ==0.18.*, haskell-lsp-types ==0.18.*`, so updating them here doesn't work.

@mgttlinger Could you make `haskell-lsp_0_18_0_0` and `haskell-lsp_types_0_18_0_0` available?  You can do this by sending a PR adding the required lines to `extra-packages` in `configuration-hackage2nix.yaml` and waiting for hackage-packages.nix to be regenerated.

**Comment by mgttlinger** [comment]
@cdepillabout Can you recommend documentation to read to get an idea of what is going on with this yaml file so that I have more of an idea of what to do next time?

**Comment by cdepillabout** [comment]
@mgttlinger Sorry, I don't actually have a good recommendation for documentation.  I've pieced it together by being active here in nixpkgs.  Although it is something I would like to help write at some point.

----------------------------------------------

If you watch the weekly twitch streams from peti, you can get an idea of everything that goes into keeping haskell packages updated:

https://www.twitch.tv/peti343

**Comment by mgttlinger** [comment]
@cdepillabout Actually would it be a possibility to update ghcide because the current version is fine with 0.19: https://github.com/digital-asset/ghcide/blob/v0.0.5/ghcide.cabal#L44-L45

**Comment by mgttlinger** [comment]
Oh never mind the stack.yaml of ghcide disallows 0.19

**Comment by mgttlinger** [comment]
I gues this is obsolete by now

**Pull request closed without merging**
