### PR TITLE
Add/vim plugin shellcheck

### PR DESCRIPTION
**Pull request by afix-space**
###### Motivation for this change
It would be nice to add  itspriddle/vim-shellcheck.
I'm not sure that's how it goes but if necessary here is my branch.
Thanks
@lovek323 @equirosa 

###### Things done

- [ X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by afix-space** [comment]
Maybe I shouldn't run the update script ?

**Comment by SuperSandro2000** [comment]
> Maybe I shouldn't run the update script ?

You need to run it but you can exclude to commit the updates.

**Comment by equirosa** [comment]
> > Maybe I shouldn't run the update script ?
> 
> You need to run it but you can exclude to commit the updates.

IIRC the manual implicitly states that one should update all plugins and committing before adding a new plugin. So maybe the update should be left as it is?

**Comment by equirosa** [comment]
That said, there *does* seem to be conflicts. @afix-space, were you up to date with master?

**Comment by SuperSandro2000** [comment]
> IIRC the manual implicitly states that one should update all plugins and committing before adding a new plugin. So maybe the update should be left as it is?

The author did that in a separate commit but it if fine for me if that wasn't done because it easily creates conflicts.

**Comment by afix-space** [comment]
Thanks, for now I sync the fork and rebase. but now I've an error when I update --add.  I'll watch it tonight.

**Comment by SuperSandro2000** [comment]
> 700 plugins were checked, 6 plugin(s) could not be downloaded:

I am going to do a PR where I update all plugins and resolve the conflicts if there are any. You can just ignore them for now and only commit the changes required for your addition.

**Comment by afix-space** [comment]
I erased the 2 commits, sync/merge fork and rebase PR branch to master. Everything seems clean.
But when ./update.py --add  "itspriddle/vim-shellcheck", it fails before the 1st commit with error like this :
https://gist.github.com/afix-space/551f0be009e7150bf0b7ff04300931d0
I can't spend more time on it right now (unless you know exactly why ). if it works for you and have some time you are welcome to make a PR, but it really does not matter if not, it can wait a bit.

**Comment by SuperSandro2000** [comment]
> unless you know exactly why

You got rate limited by GitHub 429 because you did to many API requests without a token.

**Pull request merged**
