### PR TITLE
nixos/caddy: add globalConfig option

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/issues/153192

ping @ralfbiedert for testing and review please.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ralfbiedert** [comment]
Sure. What would be the best way to test the PR? I'm pretty new when it comes to Nix.

**Comment by happysalada** [comment]
I personally see no problems with this PR.

**Comment by aanderse** [comment]
> Sure. What would be the best way to test the PR? I'm pretty new when it comes to Nix.

See https://discourse.nixos.org/t/how-to-test-changes-to-a-nixos-module/2650 for some discussion on how.

Personally I like to use [`disabledModules`](https://nixos.org/manual/nixos/stable/index.html#sec-replace-modules) or nixos containers instead, but that is mostly because I run the stable channel.

Let me know if you still need a hand after poking through those links. Thanks!

**Comment by ralfbiedert** [comment]
Pulling your branch and running `nixos-rebuild switch  -I nixpkgs=/root/nixpkgs/` with a `globalConfig` set works for me. I have HTTP/3 again. Thanks!

**Comment by aanderse** [comment]
Thanks everyone!

**Pull request merged**
