### PR TITLE
elm-pages: 2.1.11 -> 2.1.12

### PR DESCRIPTION
**Pull request by ilyakooo0**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jali-clarke** [comment]
seems reasonable at a first glance; diff @ https://github.com/dillonkearns/elm-pages/compare/f7248851e604b2bdf91b65162f0cad5a6c637f55..ef1d0e95752c56be8c8c8a19580feb90ce0e5e7b.  @ilyakooo0 did you test the new codegen command?

**Comment by ilyakooo0** [comment]
@jali-clarke no, I didn't test the codegen command.

Furthermore, I can't get the build command to work either in 2.1.11 or 2.1.12. (so, not a regression, but still very sad)

**Comment by jali-clarke** [comment]
@ilyakooo0 ah rip.  well, since it's broken can we mark it as broken and keep the version bump?  or should that be two separate PRs?  i'm a fledgling nixpkgs maintainer so idk the process

**Comment by ilyakooo0** [comment]
@jali-clarke i would prefer to not block a version bump. The other commands still work and are still useful. 

From what I understand the broken flag is meant to prevent evaluating derivations that are known to fail. 

I would prefer to merge this PR and wait for a fix.

**Review by jali-clarke — APPROVED** [review]
lgtm

**Comment by turboMaCk** [comment]
Maybe the problem is that the tool copies the file from store without changing the permissions? This seems to be common issue with nodejs tools. Workaround is to fix permissions manually.

**Comment by NickCao** [comment]
`pkgs/development/compilers/elm/packages/node-packages.nix` is not supposed to be manually edited, if I read correctly.

**Comment by ilyakooo0** [comment]
@NickCao You are right. I guess we just have to wait for an update of the whole repo then.

**Comment by ilyakooo0** [comment]
For future reference: the following command works fine (the commit elm-pages was introduced) 

```
nix run "github:NixOS/nixpkgs?rev=35fc22e24879ca191403a923ea7f520593621a7d#elmPackages.elm-pages" -- build
```

**Pull request closed without merging**
