### PR TITLE
release-notes: add autoPatchelfHookWithLibgcc, explain libgcc changes

### LINKED ISSUE #225963: autoPatchelfHook needs updated for #209870
i.e. generalized version of https://github.com/oxalica/rust-overlay/pull/122

### PR DESCRIPTION
**Pull request by ghost**
###### Description of changes

This PR contains two commits:

1. Add `autoPatchelfHookWithLibgcc`, which is the "dammit just make it work" copypasta for people who get stung by the libgcc changes.
2. Add (quite a bit of) text to the release notes to try to help out-of-tree Nix packages which are downstream of nixpkgs and encounter breakage due to the libgcc changes.

Closes #225963

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by amjoseph-nixpkgs** [comment]
Note: I will be offline from sometime in the next few hours until after the end of the month.

Please don't hesitate to edit this PR aggressively if necessary.  I'm unlikely to be able to respond to review comments before the release deadline.

**Comment by ncfavier** [comment]
Pushed a fix to the NixOS manual.

By the way, why `or null`?

**Comment by amjoseph-nixpkgs** [comment]
> By the way, why `or null`?

Because `stdenv.cc` might not have a `libgcc` output.  Two cases come to mind:

1. Future: using a non-gcc compiler (clang?)
2. Current: even our gcc does not *always* create a `libgcc` output.  [Here](https://github.com/NixOS/nixpkgs/blob/cc4e1f69ed9c4cce1abc6a9ef0a91b71c4a52004/pkgs/development/compilers/gcc/common/libgcc.nix#L9-L13) are the current conditions which cause its creation, but these may (and almost certainly will) change in the future.

**Comment by amjoseph-nixpkgs** [comment]
> Note: I will be offline from sometime in the next few hours until after the end of the month.
> 
> Please don't hesitate to edit this PR aggressively if necessary. I'm unlikely to be able to respond to review comments before the release deadline.

I'm back and pretty close to conquering my backlog.  Not sure if this is still being considered for the release (would technically be a "backport" at this point), but I can respond to comments now.

**Comment by ncfavier** [comment]
> Because `stdenv.cc` might not have a `libgcc` output.

Shouldn't compilation of things that depend on `libgcc` fail in those cases?

**Comment by amjoseph-nixpkgs** [comment]
There are many situations where `stdenv.cc` doesn't have a `libgcc` output:

- `pkgsStatic`
- cross-compilers to platforms which lack dynamic linkers (`arm-none-eabi`)
- a hypothetical future non-`gcc`-based `stdenv`

> Shouldn't compilation of things that depend on `libgcc` fail in those cases?

Unfortunately no.  This is the big problem with `libgcc`.  The `glibc` developers have decided to `dlopen()` it and *not* build with `-lgcc`, so the dependency is completely invisible to nixpkgs and patchelf.  This is the root cause of all our troubles.

**Pull request closed without merging**
