### PR TITLE
element-{web,desktop}: 1.11.32 -> 1.11.33

### PR DESCRIPTION
**Pull request by Stunkymonkey**
###### Description of changes
https://github.com/vector-im/element-desktop/releases/tag/v1.11.33

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stunkymonkey** [comment]
Result of `nixpkgs-review pr 237070` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
    <li>element-web (element-web-unwrapped)</li>
  </ul>
</details>

**Comment by Stunkymonkey** [comment]
just noticed the update to electron 25: https://github.com/vector-im/element-desktop/pull/997
will add this as well.

**Comment by Stunkymonkey** [comment]
Result of `nixpkgs-review pr 237070` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
    <li>element-web (element-web-unwrapped)</li>
  </ul>
</details>

**Comment by Mic92** [comment]
Result of `nixpkgs-review pr 237070` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
    <li>element-web (element-web-unwrapped)</li>
  </ul>
</details>

**Comment by yu-re-ka** [comment]
I noticed the electron 25 update lead to element crashing on startup when using NIXOS_OZONE_WL=1 with sway on aarch64-linux

**Comment by lilyinstarlight** [comment]
> I noticed the electron 25 update lead to element crashing on startup when using NIXOS_OZONE_WL=1 with sway on aarch64-linux

Is that what happened to element? I noticed it crashing as of today too with sway on x86_64-linux

Do you know if the issue has to do with our electron/element packaging or should I attempt to debug the issue?

**Pull request merged**
