### PR TITLE
tree-sitter-grammars: update

### PR DESCRIPTION
**Pull request by foolnotion**
###### Description of changes

The C++ grammar was broken again (I need it on a day-by-day basis for my work), possibly others (C, CMake). I have not tested ALL of them but only the ones I use. Superficially everything seems ok.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wegank** [comment]
@ofborg build tree-sitter-grammars

**Comment by foolnotion** [comment]
> 

I think the breakage comes from the fact that the grammars and tree-sitter itself get updated independent of each other. So grammar A can work with tree-sitter 1.2.3 but silently break with tree-sitter 1.2.4. This can happen after a routine system update without any warning.

I use a fairly typical neovim config as a home-manager module. The tree-sitter plugins are managed by nix:

```nix
{
  plugin = (nvim-treesitter.withPlugins (_:
    with pkgs; [
      tree-sitter-grammars.tree-sitter-c
      tree-sitter-grammars.tree-sitter-cmake
      tree-sitter-grammars.tree-sitter-cpp
      tree-sitter-grammars.tree-sitter-latex
      tree-sitter-grammars.tree-sitter-lua
      tree-sitter-grammars.tree-sitter-python
    ]));
}
```

**Comment by figsoda** [comment]
@foolnotion please use grammars from `nvim-treesitter` instead, these should be more compatible

```
{
  plugin = (nvim-treesitter.withPlugins (ps:
    with ps; [
      c
      cmake
      cpp
      latex
      lua
      python
    ]));
}
```

**Comment by foolnotion** [comment]
> @foolnotion please use grammars from `nvim-treesitter` instead, these should be more compatible
> 
> ```nix
> {
>   plugin = (nvim-treesitter.withPlugins (ps:
>     with ps; [
>       c
>       cmake
>       cpp
>       latex
>       lua
>       python
>     ]));
> }
> ```

@figsoda, thanks, using the grammars as you suggested resulted in a functional experience. I guess this PR can be close then.

**Comment by figsoda** [comment]
feel free to reopen this if you want to pick this up again

**Pull request closed without merging**
