### PR TITLE
haskellPackages: Add shell completions

### PR DESCRIPTION
**Pull request by roberth**
This adds the remaining parts of #42657 on top of #49477

###### Motivation for this change

Adds shell completion to some Haskell programs, for bash, zsh and fish.

Purescript build was failing before this. It does have optparse applicative completions, so it should work out when it gets fixed.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ericson2314** [comment]
I like your PR's `generate..` name and support for multiple exes better, actually. :)

**Comment by roberth** [comment]
There you go!

Sample deprecation message:

```
$ nix-build -A dhall
trace: addOptparseApplicativeCompletionScripts is deprecated in favor of generateOptparseApplicativeCompletion. Please change dhall-1.15.1 to use the latter or its plural form.
/nix/store/4d8vgi6nv6grch9f1mysn97099qkw8y0-dhall-1.15.1
```

**Comment by roberth** [comment]
When merged, this should be backported IMO, because the 'old' version was only recently added to 18.09.

**Comment by Ericson2314** [comment]
Mine was added so recently I'm not even sure the deprecation is worth it :). I'll merge now.

**Pull request merged**
