### PR TITLE
python3Packages.ondilo: init at 0.2.0

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Python package to access Ondilo ICO APIs

https://github.com/JeromeHXP/ondilo

This is a Home Assistant dependency.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 120258` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python38Packages.ondilo</li>
    <li>python39Packages.ondilo</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Has it tests we can activate in home-assistant?

**Comment by fabaff** [comment]
> Has it tests we can activate in home-assistant?

-> https://github.com/NixOS/nixpkgs/pull/120258/commits/d3e8f283846959899676ff28a500aa10b3c64413

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 120258` at d3e8f283 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built successfully:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python38Packages.ondilo</li>
    <li>python39Packages.ondilo</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `pytestCheckHook`.
Near pkgs/development/python-modules/ondilo/default.nix:5:3:
```
  |
5 | , pytestCheckHook
  |   ^
```
</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 120258` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python38Packages.ondilo</li>
    <li>python39Packages.ondilo</li>
  </ul>
</details>

**Review by mweinelt — APPROVED** [review]

**Pull request merged**
