### PR TITLE
enpass backport #21436 to Release 16.09 

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
###### Motivation for this change
backport #21436
###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
Two things:

1. Backports should be cherry-picked with `-x` 
2. What is the purpose of this update?

Typically these are what we backport:

```
# What to backport:

 - Security patches which aren't major updates
 - If a security patch is a major upgrade, try and find patches to our
   current version which accomplish the same goal. Apply the major
   update to master, and the patches to stable.
 - Bug fixes to applications which, again, aren't major updates.
   Generally be cautious about these.
 - Any updates when the current stable version is utterly broken. A
   key example of this is Spotify, who regularly breaks their old
   versions.
 - Extremely security-sensitive software, in particular Chrome,
   Chromium, Firefox, Thunderbird, and of course the kernel.
```

**Comment by RonnyPfannschmidt** [comment]
oh, i see, i missed that bit and i am sorry, i was a bit over-zealous there
thanks for pointing it out

**Comment by grahamc** [comment]
It is okay :) It looks like a nice update ... I was almost hoping for an excuse for backporting.

**Comment by grahamc** [comment]
@RonnyPfannschmidt do you use the browser extensions? I'm not able to connect them.

**Comment by grahamc** [comment]
I backported this fix (thank you) to get the latest fixes and updates on such sensitive software, and to get this patch as well: https://github.com/NixOS/nixpkgs/pull/21082

**Pull request closed without merging**
