### PR TITLE
vimPlugins.animations-nvim: update overrides

### PR DESCRIPTION
**Pull request by hmajid2301**
## Description of changes

We can see in the docs it depends on the middleclass library [here](https://github.com/anuvyklack/animation.nvim?tab=readme-ov-file#installation)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by gepbird** [comment]
Related issue: https://github.com/NixOS/nixpkgs/issues/312050

This PR doesn't yet solve the issue with animation-nvim. To reproduce it, include `animation-nvim` in your vim plugins, rebuild with this PR, and run `nvim --cmd "lua require 'animations'"`. Output in nvim:
```
Error detected while processing pre-vimrc command line:
E5108: Error executing lua ...ovimPackages/start/animation.nvim/lua/animation/init.lua:1: module 'middl
eclass' not found:
        no field package.preload['middleclass']
        no file '/nix/store/yvnliax3mvk269719424q5hsm9p14agw-luajit-2.1.1693350652-env/share/lua/5.1/mi
ddleclass.lua'
        no file '/nix/store/yvnliax3mvk269719424q5hsm9p14agw-luajit-2.1.1693350652-env/share/lua/5.1/mi
ddleclass/init.lua'
        no file '/nix/store/yvnliax3mvk269719424q5hsm9p14agw-luajit-2.1.1693350652-env/lib/lua/5.1/midd
leclass.so'
stack traceback:
        [C]: in function 'require'
        ...ovimPackages/start/animation.nvim/lua/animation/init.lua:1: in main chunk
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
```

Looks like the original middleclass is owned by kikito (https://github.com/kikito/middleclass) and this is what `luaPackages.middleclass` refers to.
The nvim plugin developer anuvyklack who made windows-nvim forked middleclass (https://github.com/anuvyklack/middleclass) which [adds the ability to use middleclass with nvim](https://github.com/anuvyklack/middleclass?tab=readme-ov-file#notes-about-this-fork)

The [diff](https://github.com/kikito/middleclass/compare/master...anuvyklack:middleclass:master) between the original and the forked middleclass is only middleclass.lua being renamed to lua/middleclass.lua and a new file middleclass.lua containing a reference to lua/middleclass.lua, so very minimal diff. Also both repos were last updated 2 years ago, probably unmaintained. The only dependency on middleclass is animation-nvim and window-nvim.

I propose to replace middleclass with the fork, what do you think?

**Comment by gepbird** [comment]
I added an override in lua packages that replaces middleclass with the fork, but the same error occurred. 

However patching animation-nvim's lua source to include middleclass works. I used `dofile` because that allows sourcing a lua file by full path: https://github.com/gepbird/nixpkgs/commit/59a4a89bf2d1712235b6fd4e4f2693f488ba4228.
But using require would be better, especially for performance, I'm not sure how to do it. Also we need to update windows-nvim similarly, as it directly uses middleclass too.

**Comment by hmajid2301** [comment]
thank you very much for doing all this work on this, yeh I just realised I got the same error using it locally :thinking:. I am also unsure how to do it.

**Comment by gepbird** [comment]
@hmajid2301 To "just make it work" you can use my dofile solution, just cherry-pick (or copy and paste the added code from) [this commit](https://github.com/gepbird/nixpkgs/commit/59a4a89bf2d1712235b6fd4e4f2693f488ba4228) to your update-nvim-animation branch.

As I previously said, this solution works but using `dofile` instead of `require` is bad: calling `require` multiple times on the same file will load it only once, but `dofile` will load it **every time**. This makes startup times worse, especially for window-nvim which I believe loads middleclass 3 times. I will dive deeper into lua in nixpkgs to make it work with `require` soon.

**Comment by gepbird** [comment]
I got a `dofile`-less solution working by building a vim plugin out of the same source as the luaPackage, but since the middleclass.lua file is in the root and not in the lua folder (see https://github.com/kikito/middleclass/blob/master/middleclass.lua), nvim won't load it. To fix this I moved the lua file to a new lua directory.
```nix
  animation-nvim = super.animation-nvim.overrideAttrs (oldAttrs: {
    dependencies = [
      (buildVimPlugin {
        pname = "middleclass-nvim";
        version = "unstable";
        src = luaPackages.middleclass.src;
        buildPhase = ''
          mkdir lua
          mv middleclass.lua lua
        '';
      })
    ];
  });
```

But at this point it would be simpler to just add the middleclass fork as a vim plugin which solves the latter problem without additional patching.

@hmajid2301 if you like this solution, do you want to implement it or should I create a PR?

**Comment by hmajid2301** [comment]
please you go create a PR! Thanks a ton!

**Comment by ozkutuk** [comment]
@gepbird Thanks for taking the time to take a deep look into this. I have reported the `windows.nvim` issue, but I didn't know enough about Lua to figure out the problem myself.

**Pull request closed without merging**
