### PR TITLE
python3Packages.mypy-boto3-cognito-idp: init at 1.28.36

### PR DESCRIPTION
**Pull request by mbalatsko**
## Description of changes
Creating new PR and rebased on current master to draw attention, as people stopped to respond on previous PR, and I really need this to be merged. Original PR: https://github.com/NixOS/nixpkgs/pull/253315

Original description:
This PR proposes a new structure of `mypy-boto3-{service}` python packages build. And demonstrate initialization of a new `mypy-boto3-cognito-idp` python package.

### Problem statement: 
`mypy-boto3-*` python packages sources are built by `mypy_boto3_builder` cli tool. For every AWS Service, there is a separate PyPi package. All these packages have the same release cycle and are released all at once. In total there are 350 packages for all boto3 and aioboto3 services

### Current solution:
 `buildPythonPackage` from PyPi, handles these packages separately. 
**Pros**: classic Python package definition, easy for auto updates
**Cons**: a lot of code duplication in Nix Python package definition. Each package should be upgraded separately.

### Proposed solution:
I believe that it could be much more beneficial to have a parametrized pill, which will be used to build these python packages.
**Pros**: Easy new package introduction and effortless version upgrade.
**Cons**: all packages are defined in one `default.nix`, but still using `buildPythonPackage`.

My intention is to discuss the proposed change in this PR and after we find some common ground and we're satisfied with the change, I'd like to add all 348 missing boto3 typing packages so that we all can benefit from typed Python in our favorite nix 😃 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mbalatsko** [comment]
Result of `nixpkgs-review pr 258216` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>python310Packages.dependency-injector</li>
    <li>python310Packages.mypy-boto3-cognito-idp</li>
    <li>python310Packages.mypy-boto3-s3</li>
    <li>python311Packages.dependency-injector</li>
    <li>python311Packages.mypy-boto3-cognito-idp</li>
    <li>python311Packages.mypy-boto3-s3</li>
    <li>toil</li>
  </ul>
</details>

**Review by anthonyroussel — APPROVED** [review]
Result of `nixpkgs-review pr 258216` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
14 packages built:
</summary>
<ul>
<li>python310Packages.dependency-injector</li>
<li>python310Packages.dependency-injector.dist</li>
<li>python310Packages.mypy-boto3-cognito-idp</li>
<li>python310Packages.mypy-boto3-cognito-idp.dist</li>
<li>python310Packages.mypy-boto3-s3</li>
<li>python310Packages.mypy-boto3-s3.dist</li>
<li>python311Packages.dependency-injector</li>
<li>python311Packages.dependency-injector.dist</li>
<li>python311Packages.mypy-boto3-cognito-idp</li>
<li>python311Packages.mypy-boto3-cognito-idp.dist</li>
<li>python311Packages.mypy-boto3-s3</li>
<li>python311Packages.mypy-boto3-s3.dist</li>
<li>toil</li>
<li>toil.dist</li>
</ul>
</details>

**Comment by anthonyroussel** [comment]
@mbalatsko Hello. Thanks for your work! :)

I am also waiting for this PR to be merged to [upgrade aws-sam-cli to 1.95.0](https://github.com/NixOS/nixpkgs/pull/249774#issuecomment-1717958552) which depends on some boto3-stubs packages.

**Review by fabaff — APPROVED** [review]
Let go with this approach and adjust as needed in the future.

**Pull request merged**
