### PR TITLE
atom: 0.187.0 -> 1.0.0

### PR DESCRIPTION
**Pull request by travisbhartwell**
Updated to latest.  Added buildEnv path dependency on systemd because of libudev dep.
Updated the path in the desktop file so it can be launched from the desktop file.
Removed unnecessary lintian directory, artifact of Debian package.

Tested that it installs and launches on my NixOS machine, running the unstable channel.

### CODE REVIEW

**Comment by travisbhartwell** [comment]
I forgot to cc the maintainer.

cc @offlinehacker

**Comment by travisbhartwell** [comment]
I am unsure of why this failed.  I'm new to reading the output of TravisCI and it's not obvious in all of that output what went wrong.

Before committing, I did my test against version e1af50c which is what nixos-version reported as my local version, as I use the unstable channel.  Atom installed and ran with no problems.  It was after this that I rebased my commit on master and then pushed and did my PR.

After this failed TravisCI build, I added hydra to my local binary and trusted caches and tried to install using my local nixpkgs against master with this commit added.  After an hour or so of building various dependencies, it finished building with no errors and I could run Atom without issue.  I saved the output by running the install like this:

`nix-env -i atom -f ~/Projects/nixpkgs/ 2>&1 | tee ~/update-atom-build.out`

What can I do to help debug and fix this?  I am Nafai on #nixos, and am usually lurking.

**Comment by matthiasbeyer** [comment]
I just tried to update the atom package to 1.0 to try atom out, but I got this when I started atom:

```
$ cat ~/.atom/nohup.out 
[30556:0627/173018:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[30556:0627/173018:FATAL:udev_loader.cc(36)] Check failed: false. 
[30619:0627/173018:ERROR:sandbox_linux.cc(325)] InitializeSandbox() called with multiple threads in process gpu-process
[30619:0627/173018:WARNING:file_descriptor_set_posix.cc(30)] FileDescriptorSet destroyed with unconsumed descriptors: 0/1
```

So I do not submit the patch for the update to version 1.0. I'm not really interested in using it, so this is all I can/want to contribute to this discussion. Hope it helps, though.

**Comment by Havvy** [comment]
The CI build failed because the console output was longer than 10,000 lines. Basically, NixOS hits one of the fundamental limits of using TravisCI with almost every package.

**Comment by travisbhartwell** [comment]
@matthiasbeyer I just did a local upgrade of the package to the recently released 1.0.0 and everything worked fine.  Seeing the `udev` error in your `~/.atom/nohup.out` makes me wonder if you updated the version of the package that is currently in master?  The changes I have made in this PR include adding a dependency on `systemd` so the udev libraries can be located.

**Comment by travisbhartwell** [comment]
Should I do a new PR request, changing this from `atom: 0.187.0 -> 0.210.0` to `atom: 0.187.0 -> 1.0.0` with the newly released version?

**Comment by matthiasbeyer** [comment]
@travisbhartwell I updated the package on my unstable channel branch, as I had to rebuild the world when updating it on master... maybe that's the cause of the error I saw.

**Comment by pSub** [comment]
@travisbhartwell you can also reuse this PR by force pushing to the corresponding branch. An update to 1.0.0 would be really nice.

**Comment by pSub** [comment]
Thanks!

**Pull request merged**
