### PR TITLE
Kombu amqp update backport

### PR DESCRIPTION
**Pull request by risicle**
Backporting these updates because otherwise they fail to build on release-15.09 due to python 2.7.11.

### CODE REVIEW

**Comment by FRidh** [comment]
Thanks

**Comment by risicle** [comment]
Realized that I didn't update the commit messages which refer to the wrong previous versions.

**Comment by FRidh** [comment]
Indeed, I missed that as well. Let's get it right next time ;-)

**Comment by risicle** [comment]
Making github comments on the commits. Next best thing.

**Pull request merged**
