### PR TITLE
Atari800: 2.2.1 -> 3.1.0

### PR DESCRIPTION
**Pull request by AndersonTorres**

### CODE REVIEW

**Comment by pSub** [comment]
Builds fine for me. Thanks.

**Comment by sjmackenzie** [comment]
nostalgia caused me to build this. The build works but the emulator halts saying "Sorry this program needs a real Atari/OS visit the webpage to find out more" The webpage resolves to this: "http://atari800.sourceforge.net Do I need the ROM utilities on this page to proceed: http://atari800.sourceforge.net/download.html

**Comment by pSub** [comment]
I'll try to look into this issue in a few days.

**Comment by AndersonTorres** [comment]
As far as I tested, it needs a bunch of roms,  located on /share/atari800, and I passed them to cmdline. I will test others here, but I found an interesting download link:

http://marc-abramowitz.com/download/atari/OSRoms/

**Pull request merged**
