### PR TITLE
mesos: 0.23.0 -> 0.26.0

### PR DESCRIPTION
**Pull request by kevincox**
Update mesos to 0.26.0 and build with SSL support.

### CODE REVIEW

**Comment by kamilchm** [comment]
LGTM

**Comment by jagajaga** [comment]
What about Travis error?

**Comment by kevincox** [comment]
Hmm, that's weird. It builds on my machine. I'll look into it.

**Comment by kevincox** [comment]
It rebuilt locally so I rebased and pushed again. Hopefully CI is happy this time.

**Comment by jagajaga** [comment]
Hi. Again.
Do you use chroot build?

**Comment by kamilchm** [comment]
Looks like something wrong with Maven setup:
```
Could not create local repository at /homeless-shelter/.m2/repository -> [Help 1]
```

**Comment by kevincox** [comment]
> Do you use chroot build?

I thought that was the default so probably not. 

> Looks like something wrong with Maven setup

Yeah, I saw that but know almost nothing about maven. If I find some time I'll look into it but otherwise help would be very much appreciated.

**Comment by kamilchm** [comment]
I know maven pretty good but didn't run it on travis :(
I'll try to find time to fix it.

**Comment by kevincox** [comment]
Thanks, I suspect it's just an environment variable or config option to control where the repo is. I'll avoid touching it so that I don't step on your toes.

**Comment by kamilchm** [comment]
Yep, maven looks for ``$HOME/.m2`` dir to use it as dependencies cache. I need to know if there are specific guidelines for using maven on travis.

**Comment by kevincox** [comment]
It shouldn't matter that it is on Travis. It's just a Nix problem. Nix sets `$HOME`to be a directory that doesn't exist. So you need to convince maven to keep its cache somewhere else. (probably in `$tmp`)

**Comment by kamilchm** [comment]
I think that this line tries to do it:
```
export MAVEN_OPTS="-Dmaven.repo.local=${mavenRepo}"
```
but it looks like it doesn't work for Travis

**Comment by kamilchm** [comment]
There's rather dirty workaround https://github.com/thomas-fritsch/psdt/commit/0a97e2d96dbbc1a91b9df96a8a9ba6338df187f7
@jagajaga what do you think about it?

**Comment by kamilchm** [comment]
https://github.com/kevincox/nixpkgs/pull/1 should fix it.
@jagajaga is there a better  way to add files before ``buildPhase`` instead of echoing it in ``preConfigure``?

**Comment by kevincox** [comment]
I think echoing to configure should work. Environment variables would be better but if that isn't working...

**Comment by kevincox** [comment]
I'll watch CI and clean it up if it works. I should have some time today.

**Comment by kamilchm** [comment]
Same error.
What's the quickest way to try it on my own branch before pushing it here?

**Comment by kevincox** [comment]
If you turn on Travis on your repo it should use the same config and test any commit you push to github.

**Comment by kamilchm** [comment]
I thought so but it finished after 50 second, so I suppose that it wasn't the same build as one here.
https://travis-ci.org/kamilchm/nixpkgs/builds/106688449

**Comment by kevincox** [comment]
I guess it actually needs to be a PR to determine what changed (so that it doesn't rebuild everything). Try opening a PR against your own repo. (but make sure the target branch doesn't have the chanfes)

**Comment by kevincox** [comment]
So apparently you need a multi-user installation for chroot builds do I'm going to stick with guess and check with CI. It would be nice to use a form of isolation that didn't require root.

**Comment by jagajaga** [comment]
We need to pass Travis, because hydra won't build it too then probably.

**Comment by kevincox** [comment]
Yeah, I got that. It's just a pain to debug like this. I can build mesos a lot quicker on my machine then waiting for CI.

**Comment by kevincox** [comment]
Ok, this has defeated me for today. I couldn't get it to build however I suspect that there is a missing dependency that needs to be updated. I think that it is noticing that it is missing from the premade repo so maven tries to download it, ignoring our repo preference and trying to create it under `$HOME`. I suspect that getting the list of required packages should fix this but I haven't discovered a way to get that info.

**Comment by kamilchm** [comment]
I want to reproduce it on my fork but I don't know how to make travis to run the same code even if I created a PR https://travis-ci.org/kamilchm/nixpkgs/builds/106971815
I can work more on it but I need to reproduce it first and have a feedback loop :/
I can create separate PR here but do I need to do it?

**Comment by kevincox** [comment]
The problem is that Nox is comparing changes between the target branch and the PR. So because you are creating a PR to my branch there is no different so Nox doesn't build anything. Try creating the PR against a branch that doesn't have any of these changes.

**Comment by kamilchm** [comment]
This is my PR https://github.com/kamilchm/nixpkgs/pull/1
It's your commit against current nixpkgs/master

**Comment by kevincox** [comment]
Oh sorry, I read it wrong. You are right. I don't know why then. You could always open a PR against this repo because you know that works. Just put the title something that makes it clear it should be ignored.

**Comment by kamilchm** [comment]
This works for my PR https://github.com/kevincox/nixpkgs/pull/2

**Comment by kevincox** [comment]
Awesome! I meged it in. If tests pass I'll squash the commits and propose it for merging.

**Comment by globin** [comment]
Seems to be some issue with PYTHONPATH when running mesos log ...

**Comment by kamilchm** [comment]
Could you provide command example to reproduce PYTHONPATH issue?

**Comment by globin** [comment]
Ah sorry wasn't log but cat and ps:
```
robin@graffel [12:22:03] [~/dev/nixpkgs] [kevincox-mesos-upgrade *]
-> % ./result/bin/mesos cat
Traceback (most recent call last):
  File "/nix/store/ar6l663f2clvqzh11jvi377jykqf2izx-mesos-0.26.0/bin/.mesos-cat-wrapped", line 12, in <module>
    from mesos import http
ImportError: No module named mesos
robin@graffel [12:22:05] [~/dev/nixpkgs] [kevincox-mesos-upgrade *]
-> % ./result/bin/mesos ps
Traceback (most recent call last):
  File "/nix/store/ar6l663f2clvqzh11jvi377jykqf2izx-mesos-0.26.0/bin/.mesos-ps-wrapped", line 10, in <module>
    from mesos import http
ImportError: No module named mesos

```

**Comment by kevincox** [comment]
Ok, I have rebased the code, it should pass CI and be good to merge!

**Comment by kevincox** [comment]
Oh, I guess we have to fix the python path issue.

**Comment by kamilchm** [comment]
This should help https://github.com/kevincox/nixpkgs/pull/3

**Comment by kevincox** [comment]
After that PR I am seeing the same python path issue.

```py
% ./result/bin/mesos cat
Traceback (most recent call last):
  File "/nix/store/vw4g9ysfj2xzkjddidliginqw3wsk775-mesos-0.26.0/bin/.mesos-cat-wrapped", line 12, in <module>
    from mesos import http
ImportError: No module named mesos
```

**Comment by kamilchm** [comment]
Could you check python files you got installed in ``/nix/store/vw4g9ysfj2xzkjddidliginqw3wsk775-mesos-0.26.0/lib/python2.7/site-packages/mesos``? There should be ``http.py`` after my last change.
Besides that travis behaves strange now and it doesn't seem to be related to ``PYTHONPATH`` change.

**Comment by kamilchm** [comment]
I hope it will be the last one https://github.com/kevincox/nixpkgs/pull/4 ;)

**Comment by kevincox** [comment]
Awesome, the python stuff seems to be fixed. Hopefully travis won't cut out before the build is finished but everything appears to be working now.

**Comment by kevincox** [comment]
It's failing because the log is too long. It appears that we are building some python packages, I wonder why it needs to do that.

**Comment by kamilchm** [comment]
You're right https://github.com/travis-ci/travis-ci/issues/3865
@jagajaga can we do something with this?

**Comment by jagajaga** [comment]
Well, you can test this PR yourself by using `nox`. You need to run `nox-review pr 12572`.

**Comment by kamilchm** [comment]
One more try with ``python setup.py --quiet`` https://github.com/kevincox/nixpkgs/pull/5

**Comment by kevincox** [comment]
Is that something we want to do? Logs can be valuable. I'm also not sure if I can use nox on my system because I don't have a multi-user installation.

**Comment by kevincox** [comment]
I merged the quiet setup but we might want to remove it before shipping.

**Comment by kamilchm** [comment]
``--quiet`` does nothing :(
I don't know what to do to make travis happy :/
It looks like travis isn't the best CI we can use if we need to make changes just because travis can't handle build logs.

**Comment by kevincox** [comment]
So this time it took to long to build. The problem is because it gets merged with the master branch it has to rebuild whatever has changed recently in master. I'm going to start a conversation on the mailing list to address this because there are clearly some downsides to the system.

**Comment by kamilchm** [comment]
I thought about it on circleci instead of travis just to make sure that it'll build. I'll try to find some time for it next week.

**Comment by kevincox** [comment]
I don't think that will really solve problem as I believe the issue stems from how the PR is built. Maybe Circle has higher resource limits but the way PRs get built is currently hugely inefficient. If you aren't subscribed to the mailing list you can see my message with the details online.

http://lists.science.uu.nl/pipermail/nix-dev/2016-February/019494.html

Until I get some responses I will just keep submitting this for CI (once the backlog has been consumed) hoping I win the "What has been merged recently?" lottery.

**Comment by kamilchm** [comment]
I read it now and you're right. Hitting CI resource limits is only a symptom.

**Comment by cstrahan** [comment]
Thanks!

**Pull request merged**
