### PR TITLE
vimPlugins: nvimRequireChecks and nvimSkipModules for new nvimRequireCheckHook

### PR DESCRIPTION
**Pull request by khaneliman**
## Things done
Pulling out the vimPlugins changes from https://github.com/NixOS/nixpkgs/pull/352277 so that plugin additions/changes don't cause merge conflicts constantly during staging cycle. They wont have any effect until the hook changes make it to master.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by GaetanLepage — APPROVED** [review]

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 360800`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 89 packages built:</summary>
  <ul>
    <li>vimPlugins.LazyVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.astrotheme</li>
    <li>vimPlugins.asyncrun-vim</li>
    <li>vimPlugins.auto-session</li>
    <li>vimPlugins.bamboo-nvim</li>
    <li>vimPlugins.barbar-nvim</li>
    <li>vimPlugins.base46</li>
    <li>vimPlugins.bufferline-nvim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.ccc-nvim</li>
    <li>vimPlugins.cmd-parser-nvim</li>
    <li>vimPlugins.cobalt2-nvim</li>
    <li>vimPlugins.context-vim</li>
    <li>vimPlugins.darkearth-nvim</li>
    <li>vimPlugins.dropbar-nvim</li>
    <li>vimPlugins.feline-nvim</li>
    <li>vimPlugins.flash-nvim</li>
    <li>vimPlugins.flutter-tools-nvim</li>
    <li>vimPlugins.go-nvim</li>
    <li>vimPlugins.himalaya-vim</li>
    <li>vimPlugins.hover-nvim</li>
    <li>vimPlugins.indent-blankline-nvim</li>
    <li>vimPlugins.instant-nvim</li>
    <li>vimPlugins.legendary-nvim</li>
    <li>vimPlugins.lightline-bufferline</li>
    <li>vimPlugins.lispdocs-nvim</li>
    <li>vimPlugins.lspsaga-nvim</li>
    <li>vimPlugins.ltex_extra-nvim</li>
    <li>vimPlugins.luasnip-latex-snippets-nvim</li>
    <li>vimPlugins.mason-lspconfig-nvim</li>
    <li>vimPlugins.mason-nvim</li>
    <li>vimPlugins.mason-tool-installer-nvim</li>
    <li>vimPlugins.material-vim</li>
    <li>vimPlugins.mkdnflow-nvim</li>
    <li>vimPlugins.modicator-nvim</li>
    <li>vimPlugins.molten-nvim</li>
    <li>vimPlugins.neorepl-nvim</li>
    <li>vimPlugins.neotest-jest</li>
    <li>vimPlugins.neotest-minitest</li>
    <li>vimPlugins.neotest-playwright</li>
    <li>vimPlugins.neotest-vitest</li>
    <li>vimPlugins.neotest-zig</li>
    <li>vimPlugins.netman-nvim</li>
    <li>vimPlugins.nvchad</li>
    <li>vimPlugins.nvchad-ui</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-fzf-commands</li>
    <li>vimPlugins.nvim-moonwalk</li>
    <li>vimPlugins.nvim-neoclip-lua</li>
    <li>vimPlugins.nvim-snippets</li>
    <li>vimPlugins.nvim-surround</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-unception</li>
    <li>vimPlugins.nvzone-menu</li>
    <li>vimPlugins.omni-vim</li>
    <li>vimPlugins.onedark-nvim</li>
    <li>vimPlugins.openscad-nvim</li>
    <li>vimPlugins.outline-nvim</li>
    <li>vimPlugins.persisted-nvim</li>
    <li>vimPlugins.poimandres-nvim</li>
    <li>vimPlugins.pywal-nvim</li>
    <li>vimPlugins.qmk-nvim</li>
    <li>vimPlugins.rainbow-delimiters-nvim</li>
    <li>vimPlugins.range-highlight-nvim</li>
    <li>vimPlugins.smart-open-nvim</li>
    <li>vimPlugins.smart-splits-nvim</li>
    <li>vimPlugins.snacks-nvim</li>
    <li>vimPlugins.snap</li>
    <li>vimPlugins.spaceman-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.text-case-nvim</li>
    <li>vimPlugins.tmux-complete-vim</li>
    <li>vimPlugins.tokyonight-nvim</li>
    <li>vimPlugins.trouble-nvim</li>
    <li>vimPlugins.tsc-nvim</li>
    <li>vimPlugins.vim-apm</li>
    <li>vimPlugins.vim-flog</li>
    <li>vimPlugins.vim-illuminate</li>
    <li>vimPlugins.vim-matchup</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.vim-ultest</li>
    <li>vimPlugins.virt-column-nvim</li>
    <li>vimPlugins.which-key-nvim</li>
    <li>vimPlugins.wiki-vim</li>
    <li>vimPlugins.yanky-nvim</li>
    <li>vimPlugins.zenbones-nvim</li>
    <li>vimPlugins.zk-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 89 packages built:</summary>
  <ul>
    <li>vimPlugins.LazyVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.astrotheme</li>
    <li>vimPlugins.asyncrun-vim</li>
    <li>vimPlugins.auto-session</li>
    <li>vimPlugins.bamboo-nvim</li>
    <li>vimPlugins.barbar-nvim</li>
    <li>vimPlugins.base46</li>
    <li>vimPlugins.bufferline-nvim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.ccc-nvim</li>
    <li>vimPlugins.cmd-parser-nvim</li>
    <li>vimPlugins.cobalt2-nvim</li>
    <li>vimPlugins.context-vim</li>
    <li>vimPlugins.darkearth-nvim</li>
    <li>vimPlugins.dropbar-nvim</li>
    <li>vimPlugins.feline-nvim</li>
    <li>vimPlugins.flash-nvim</li>
    <li>vimPlugins.flutter-tools-nvim</li>
    <li>vimPlugins.go-nvim</li>
    <li>vimPlugins.himalaya-vim</li>
    <li>vimPlugins.hover-nvim</li>
    <li>vimPlugins.indent-blankline-nvim</li>
    <li>vimPlugins.instant-nvim</li>
    <li>vimPlugins.legendary-nvim</li>
    <li>vimPlugins.lightline-bufferline</li>
    <li>vimPlugins.lispdocs-nvim</li>
    <li>vimPlugins.lspsaga-nvim</li>
    <li>vimPlugins.ltex_extra-nvim</li>
    <li>vimPlugins.luasnip-latex-snippets-nvim</li>
    <li>vimPlugins.mason-lspconfig-nvim</li>
    <li>vimPlugins.mason-nvim</li>
    <li>vimPlugins.mason-tool-installer-nvim</li>
    <li>vimPlugins.material-vim</li>
    <li>vimPlugins.mkdnflow-nvim</li>
    <li>vimPlugins.modicator-nvim</li>
    <li>vimPlugins.molten-nvim</li>
    <li>vimPlugins.neorepl-nvim</li>
    <li>vimPlugins.neotest-jest</li>
    <li>vimPlugins.neotest-minitest</li>
    <li>vimPlugins.neotest-playwright</li>
    <li>vimPlugins.neotest-vitest</li>
    <li>vimPlugins.neotest-zig</li>
    <li>vimPlugins.netman-nvim</li>
    <li>vimPlugins.nvchad</li>
    <li>vimPlugins.nvchad-ui</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-fzf-commands</li>
    <li>vimPlugins.nvim-moonwalk</li>
    <li>vimPlugins.nvim-neoclip-lua</li>
    <li>vimPlugins.nvim-snippets</li>
    <li>vimPlugins.nvim-surround</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-unception</li>
    <li>vimPlugins.nvzone-menu</li>
    <li>vimPlugins.omni-vim</li>
    <li>vimPlugins.onedark-nvim</li>
    <li>vimPlugins.openscad-nvim</li>
    <li>vimPlugins.outline-nvim</li>
    <li>vimPlugins.persisted-nvim</li>
    <li>vimPlugins.poimandres-nvim</li>
    <li>vimPlugins.pywal-nvim</li>
    <li>vimPlugins.qmk-nvim</li>
    <li>vimPlugins.rainbow-delimiters-nvim</li>
    <li>vimPlugins.range-highlight-nvim</li>
    <li>vimPlugins.smart-open-nvim</li>
    <li>vimPlugins.smart-splits-nvim</li>
    <li>vimPlugins.snacks-nvim</li>
    <li>vimPlugins.snap</li>
    <li>vimPlugins.spaceman-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.text-case-nvim</li>
    <li>vimPlugins.tmux-complete-vim</li>
    <li>vimPlugins.tokyonight-nvim</li>
    <li>vimPlugins.trouble-nvim</li>
    <li>vimPlugins.tsc-nvim</li>
    <li>vimPlugins.vim-apm</li>
    <li>vimPlugins.vim-flog</li>
    <li>vimPlugins.vim-illuminate</li>
    <li>vimPlugins.vim-matchup</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.vim-ultest</li>
    <li>vimPlugins.virt-column-nvim</li>
    <li>vimPlugins.which-key-nvim</li>
    <li>vimPlugins.wiki-vim</li>
    <li>vimPlugins.yanky-nvim</li>
    <li>vimPlugins.zenbones-nvim</li>
    <li>vimPlugins.zk-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 89 packages built:</summary>
  <ul>
    <li>vimPlugins.LazyVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.astrotheme</li>
    <li>vimPlugins.asyncrun-vim</li>
    <li>vimPlugins.auto-session</li>
    <li>vimPlugins.bamboo-nvim</li>
    <li>vimPlugins.barbar-nvim</li>
    <li>vimPlugins.base46</li>
    <li>vimPlugins.bufferline-nvim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.ccc-nvim</li>
    <li>vimPlugins.cmd-parser-nvim</li>
    <li>vimPlugins.cobalt2-nvim</li>
    <li>vimPlugins.context-vim</li>
    <li>vimPlugins.darkearth-nvim</li>
    <li>vimPlugins.dropbar-nvim</li>
    <li>vimPlugins.feline-nvim</li>
    <li>vimPlugins.flash-nvim</li>
    <li>vimPlugins.flutter-tools-nvim</li>
    <li>vimPlugins.go-nvim</li>
    <li>vimPlugins.himalaya-vim</li>
    <li>vimPlugins.hover-nvim</li>
    <li>vimPlugins.indent-blankline-nvim</li>
    <li>vimPlugins.instant-nvim</li>
    <li>vimPlugins.legendary-nvim</li>
    <li>vimPlugins.lightline-bufferline</li>
    <li>vimPlugins.lispdocs-nvim</li>
    <li>vimPlugins.lspsaga-nvim</li>
    <li>vimPlugins.ltex_extra-nvim</li>
    <li>vimPlugins.luasnip-latex-snippets-nvim</li>
    <li>vimPlugins.mason-lspconfig-nvim</li>
    <li>vimPlugins.mason-nvim</li>
    <li>vimPlugins.mason-tool-installer-nvim</li>
    <li>vimPlugins.material-vim</li>
    <li>vimPlugins.mkdnflow-nvim</li>
    <li>vimPlugins.modicator-nvim</li>
    <li>vimPlugins.molten-nvim</li>
    <li>vimPlugins.neorepl-nvim</li>
    <li>vimPlugins.neotest-jest</li>
    <li>vimPlugins.neotest-minitest</li>
    <li>vimPlugins.neotest-playwright</li>
    <li>vimPlugins.neotest-vitest</li>
    <li>vimPlugins.neotest-zig</li>
    <li>vimPlugins.netman-nvim</li>
    <li>vimPlugins.nvchad</li>
    <li>vimPlugins.nvchad-ui</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-fzf-commands</li>
    <li>vimPlugins.nvim-moonwalk</li>
    <li>vimPlugins.nvim-neoclip-lua</li>
    <li>vimPlugins.nvim-snippets</li>
    <li>vimPlugins.nvim-surround</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-unception</li>
    <li>vimPlugins.nvzone-menu</li>
    <li>vimPlugins.omni-vim</li>
    <li>vimPlugins.onedark-nvim</li>
    <li>vimPlugins.openscad-nvim</li>
    <li>vimPlugins.outline-nvim</li>
    <li>vimPlugins.persisted-nvim</li>
    <li>vimPlugins.poimandres-nvim</li>
    <li>vimPlugins.pywal-nvim</li>
    <li>vimPlugins.qmk-nvim</li>
    <li>vimPlugins.rainbow-delimiters-nvim</li>
    <li>vimPlugins.range-highlight-nvim</li>
    <li>vimPlugins.smart-open-nvim</li>
    <li>vimPlugins.smart-splits-nvim</li>
    <li>vimPlugins.snacks-nvim</li>
    <li>vimPlugins.snap</li>
    <li>vimPlugins.spaceman-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.text-case-nvim</li>
    <li>vimPlugins.tmux-complete-vim</li>
    <li>vimPlugins.tokyonight-nvim</li>
    <li>vimPlugins.trouble-nvim</li>
    <li>vimPlugins.tsc-nvim</li>
    <li>vimPlugins.vim-apm</li>
    <li>vimPlugins.vim-flog</li>
    <li>vimPlugins.vim-illuminate</li>
    <li>vimPlugins.vim-matchup</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.vim-ultest</li>
    <li>vimPlugins.virt-column-nvim</li>
    <li>vimPlugins.which-key-nvim</li>
    <li>vimPlugins.wiki-vim</li>
    <li>vimPlugins.yanky-nvim</li>
    <li>vimPlugins.zenbones-nvim</li>
    <li>vimPlugins.zk-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 89 packages built:</summary>
  <ul>
    <li>vimPlugins.LazyVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.astrotheme</li>
    <li>vimPlugins.asyncrun-vim</li>
    <li>vimPlugins.auto-session</li>
    <li>vimPlugins.bamboo-nvim</li>
    <li>vimPlugins.barbar-nvim</li>
    <li>vimPlugins.base46</li>
    <li>vimPlugins.bufferline-nvim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.ccc-nvim</li>
    <li>vimPlugins.cmd-parser-nvim</li>
    <li>vimPlugins.cobalt2-nvim</li>
    <li>vimPlugins.context-vim</li>
    <li>vimPlugins.darkearth-nvim</li>
    <li>vimPlugins.dropbar-nvim</li>
    <li>vimPlugins.feline-nvim</li>
    <li>vimPlugins.flash-nvim</li>
    <li>vimPlugins.flutter-tools-nvim</li>
    <li>vimPlugins.go-nvim</li>
    <li>vimPlugins.himalaya-vim</li>
    <li>vimPlugins.hover-nvim</li>
    <li>vimPlugins.indent-blankline-nvim</li>
    <li>vimPlugins.instant-nvim</li>
    <li>vimPlugins.legendary-nvim</li>
    <li>vimPlugins.lightline-bufferline</li>
    <li>vimPlugins.lispdocs-nvim</li>
    <li>vimPlugins.lspsaga-nvim</li>
    <li>vimPlugins.ltex_extra-nvim</li>
    <li>vimPlugins.luasnip-latex-snippets-nvim</li>
    <li>vimPlugins.mason-lspconfig-nvim</li>
    <li>vimPlugins.mason-nvim</li>
    <li>vimPlugins.mason-tool-installer-nvim</li>
    <li>vimPlugins.material-vim</li>
    <li>vimPlugins.mkdnflow-nvim</li>
    <li>vimPlugins.modicator-nvim</li>
    <li>vimPlugins.molten-nvim</li>
    <li>vimPlugins.neorepl-nvim</li>
    <li>vimPlugins.neotest-jest</li>
    <li>vimPlugins.neotest-minitest</li>
    <li>vimPlugins.neotest-playwright</li>
    <li>vimPlugins.neotest-vitest</li>
    <li>vimPlugins.neotest-zig</li>
    <li>vimPlugins.netman-nvim</li>
    <li>vimPlugins.nvchad</li>
    <li>vimPlugins.nvchad-ui</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-fzf-commands</li>
    <li>vimPlugins.nvim-moonwalk</li>
    <li>vimPlugins.nvim-neoclip-lua</li>
    <li>vimPlugins.nvim-snippets</li>
    <li>vimPlugins.nvim-surround</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-unception</li>
    <li>vimPlugins.nvzone-menu</li>
    <li>vimPlugins.omni-vim</li>
    <li>vimPlugins.onedark-nvim</li>
    <li>vimPlugins.openscad-nvim</li>
    <li>vimPlugins.outline-nvim</li>
    <li>vimPlugins.persisted-nvim</li>
    <li>vimPlugins.poimandres-nvim</li>
    <li>vimPlugins.pywal-nvim</li>
    <li>vimPlugins.qmk-nvim</li>
    <li>vimPlugins.rainbow-delimiters-nvim</li>
    <li>vimPlugins.range-highlight-nvim</li>
    <li>vimPlugins.smart-open-nvim</li>
    <li>vimPlugins.smart-splits-nvim</li>
    <li>vimPlugins.snacks-nvim</li>
    <li>vimPlugins.snap</li>
    <li>vimPlugins.spaceman-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.text-case-nvim</li>
    <li>vimPlugins.tmux-complete-vim</li>
    <li>vimPlugins.tokyonight-nvim</li>
    <li>vimPlugins.trouble-nvim</li>
    <li>vimPlugins.tsc-nvim</li>
    <li>vimPlugins.vim-apm</li>
    <li>vimPlugins.vim-flog</li>
    <li>vimPlugins.vim-illuminate</li>
    <li>vimPlugins.vim-matchup</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.vim-ultest</li>
    <li>vimPlugins.virt-column-nvim</li>
    <li>vimPlugins.which-key-nvim</li>
    <li>vimPlugins.wiki-vim</li>
    <li>vimPlugins.yanky-nvim</li>
    <li>vimPlugins.zenbones-nvim</li>
    <li>vimPlugins.zk-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Comment by khaneliman** [comment]
Just updated note on `vim-ultest` to not recommend removing atm. It looks like it might still be recommended testing for vim, but neotest is suggested for neovim.

**Comment by teto** [comment]
It's unusual to start merging unused code. As I feared the number of false positives is concerning. almost 700 lines (and that is without https://github.com/NixOS/nixpkgs/pull/352277#issuecomment-2509823495) that doesn't bring much in terms of robustness.

**Comment by khaneliman** [comment]
> As I feared the number of false positives is concerning. almost 700 lines (and that is without [#352277 (comment)](https://github.com/NixOS/nixpkgs/pull/352277#issuecomment-2509823495)) that doesn't bring much in terms of robustness.

Not sure I understand what the comment means.

**Comment by teto** [comment]
If I understand correctly, this PR does nothing without  https://github.com/NixOS/nixpkgs/pull/352277 ?
 in which case it is dead code and it is not good practice to merge dead code.

>  we dont cause constant conflicts in the github actions for master -> staging-next -> staging cycle due to the single file - multiple source files we have that will be touched constantly with new plugins.

Are you talking about pkgs/applications/editors/vim/plugins/overrides.nix ? in my experience it's pretty straightforward to rebase, the chunks are easily identifiable and it's part of the PR process.

> The linked comment are build failures. 

Sry for the link, I just meant the PR in general, not the specific comment my bad

**Pull request merged**
