### PR TITLE
openra-ura: init at 407

### PR DESCRIPTION
**Pull request by msteen**
###### Motivation for this change
Red Alert - Unplugged

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by fusion809** [comment]
Unfortunately, this does not work on openSUSE Tumbleweed, I get the error:

```bash
exception inside UnhandledException handler: The type initializer for 'System.Console' threw an exception.

[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'System.Console' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.ConsoleDriver' threw an exception. ---> System.Exception: Magic number is wrong: 542
  at System.TermInfoReader.ReadHeader (System.Byte[] buffer, System.Int32& position) [0x0008d] in /build/mono-5.8.0.108/mcs/class/corlib/System/TermInfoReader.cs:134 
  at System.TermInfoReader..ctor (System.String term, System.String filename) [0x0005f] in /build/mono-5.8.0.108/mcs/class/corlib/System/TermInfoReader.cs:97 
  at System.TermInfoDriver..ctor (System.String term) [0x00055] in /build/mono-5.8.0.108/mcs/class/corlib/System/TermInfoDriver.cs:164 
  at System.ConsoleDriver.CreateTermInfoDriver (System.String term) [0x00000] in /build/mono-5.8.0.108/mcs/class/corlib/System/ConsoleDriver.cs:73 
  at System.ConsoleDriver..cctor () [0x0004d] in /build/mono-5.8.0.108/mcs/class/corlib/System/ConsoleDriver.cs:57 
   --- End of inner exception stack trace ---
  at System.Console.SetupStreams (System.Text.Encoding inputEncoding, System.Text.Encoding outputEncoding) [0x00000] in /build/mono-5.8.0.108/mcs/class/corlib/System/Console.cs:136 
  at System.Console..cctor () [0x0008e] in /build/mono-5.8.0.108/mcs/class/corlib/System/Console.cs:130 
   --- End of inner exception stack trace ---
  at OpenRA.ExceptionHandler.HandleFatalError (System.Exception ex) [0x0019c] in <3aae6d275d964adeb94a473301fdd340>:0 
  at OpenRA.Program.<Main>m__0 (System.Object _, System.UnhandledExceptionEventArgs e) [0x00006] in <3aae6d275d964adeb94a473301fdd340>:0 
```

**Comment by msteen** [comment]
@fusion809 Like we discussed before, the problem has to do with mono when run from the console. Setting `TERM=xterm` solves it. I planned to add to the wrapper, but forgot about it. It's now been added to the wrapper. Thank you for reminding me!

**Comment by fusion809** [comment]
It turns out that the `openra` Nix package also gets this error on Arch, and it seems to be due to hard-coded OpenGL paths. I tried installing [nixGL](https://github.com/guibou/nixGL) to fix this. Running `nixGLNvidia openra-ura` crashes on startup with the error:

```bash
Platform is Linux
Engine version is unplugged-cd82382
Using SDL 2 with OpenGL renderer
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  92
  Current serial number in output stream:  93
```

**Comment by rardiol** [comment]
Just tested the sp on nixos, seemed fine. As the out of nixos opengl problem also happens to standard openra, then I think we should merge this and fix the non-ura specific opengl issue separately.

**Pull request closed without merging**
