### PR TITLE
libressl: build libcrypto with noexecstack

### PR DESCRIPTION
**Pull request by ruuda**
For some reason, libcrypto would be built with the executable stack flag set. I found out about this when Nginx failed to load the shared library, because I was running it with `MemoryDenyWriteExecute=true` which does not permit executable stacks.

I am not sure why the stack ends up executable; the other shared libraries which are part of LibreSSL do not have this flag set. You can verify this with `execstack -q`. Non-executable stacks should be the
default, and from checking some other files, that does appear to be the case. The LibreSSL sources do not contain the string "execstack", so I am not sure what causes the default to be overridden.

Adding `-z noexecstack` to the linker flags makes the linker unset the flag. Now my Nginx can load the library, and so far I have not run into other issues.

I would like to understand where the shared stack requirement came from though. Without knowing where it originates from, it is hard to say what the impact of disabling it is. I did find these threads, which suggest that it is safe to use `noexecstack`:

* http://openssl.6102.n7.nabble.com/PATCH-libcrypto-without-executable-stack-td30772.html
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=430583

###### Motivation for this change

Nginx built against LibreSSL cannot use `MemoryDenyWriteExecute=true` at the moment, because `libcrypto.so.45` requires an executable stack. This is a weird requirement, especially for a crypto library.

Still, I would like to understand where the requirement came from before merging this.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`). Also tested Nginx built against this LibreSSL.
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @thoughtpolice @fpletz @globin

### CODE REVIEW

**Comment by ruuda** [comment]
The libcrypto in `pkgs.openssl` does already not require an executable stack:

```
$ execstack -q /nix/store/rngzs8bxnajzpwnkk4896gy9d5s525ic-openssl-1.0.2s/lib/*                             
execstack: cannot open ELF file: invalid file descriptor
- /nix/store/rngzs8bxnajzpwnkk4896gy9d5s525ic-openssl-1.0.2s/lib/libcrypto.so
- /nix/store/rngzs8bxnajzpwnkk4896gy9d5s525ic-openssl-1.0.2s/lib/libcrypto.so.1.0.0
- /nix/store/rngzs8bxnajzpwnkk4896gy9d5s525ic-openssl-1.0.2s/lib/libssl.so
- /nix/store/rngzs8bxnajzpwnkk4896gy9d5s525ic-openssl-1.0.2s/lib/libssl.so.1.0.0
```

The `-` means that no executable stack is required, an `X` would mean that it is.

**Comment by mmahut** [comment]
@GrahamcOfBorg build libressl

**Comment by risicle** [comment]
This doesn't work on darwin:

```
/nix/store/wmb4c95cyqryqs6adv9hw8gdbnbcffgj-clang-wrapper-7.1.0/bin/clang   -arch x86_64 -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_df578.dir/testCCompiler.c.o  -o cmTC_df578
    ld: unknown option: -z
```

**Comment by ruuda** [comment]
Does Darwin have the concept of an executable stack, or should the flag it be omitted entirely there?

**Comment by matthewbauer** [comment]
I don't believe this is necessary on Darwin. There is a MH_ALLOW_STACK_EXECUTION flag but it is only valid on executables (via ```-allow_stack_execute```), not libraries

**Comment by ruuda** [comment]
Thanks for clarifying that, I've removed the flags entirely for Darwin.

**Comment by mmahut** [comment]
@GrahamcOfBorg build libressl

**Review by thoughtpolice — APPROVED** [review]

**Comment by thoughtpolice** [comment]
FWIW, my best guess for the reason this happens is that there is some object file that the linker is bringing in which is, for some reason, NOT marked to include the section `.note.GNU-stack`. This section directive tells the linker this object file does *not* need an executable stack. Provided every object has this section set, it will be removed from the final result, and the ELF header indicating noexecstack will be set. But on the flip side, if no such section exists -- in *any object file* -- the linker assumes the object is old, and therefore turns *on* executable stacks for the final result. It's all-or-nothing. (More details [are available from Ian Lance Taylor](https://www.airs.com/blog/archives/518).) Most importantly, this section is always emitted by modern compilers (except in very rare cases), so the most likely culprit is that a hand-written assembly file, for instance, that forgot to include this section, causing the whole thing to go belly up.

Some initial guesswork inside the source code didn't reveal anything on that note, unfortunately. Probably the best way to verify this theory is to simply run the `buildPhase` of libressl and then scan all object files for `.note.GNU-section`, and report any that don't exist. While I can't *prove* this is the issue, my gut feeling is that this might reveal a lead.

**Comment by ruuda** [comment]
> Some initial guesswork inside the source code didn't reveal anything on that note, unfortunately. Probably the best way to verify this theory is to simply run the buildPhase of libressl and then scan all object files for .note.GNU-section, and report any that don't exist. While I can't prove this is the issue, my gut feeling is that this might reveal a lead.

Thanks for the elaborate reply, that clarifies a lot. Your suspicion is spot on, there are a number of `.S.o` files in the build directory that are missing `.note.GNU-stack`.

<details>
<summary>List of those</summary>

```
# objdump exits with 0 if the section exists and with 1 if it does not.
$ find build/crypto/CMakeFiles/crypto.dir/ -name '*.o' -exec sh -c "if ! objdump -h --section=.note.GNU-stack {} > /dev/null 2>&1; then echo {}; fi" \;
build/crypto/CMakeFiles/crypto.dir/cpuid-elf-x86_64.S.o
build/crypto/CMakeFiles/crypto.dir/whrlpool/wp-elf-x86_64.S.o
build/crypto/CMakeFiles/crypto.dir/sha/sha512-elf-x86_64.S.o
build/crypto/CMakeFiles/crypto.dir/sha/sha256-elf-x86_64.S.o
build/crypto/CMakeFiles/crypto.dir/sha/sha1-elf-x86_64.S.o
build/crypto/CMakeFiles/crypto.dir/rc4/rc4-elf-x86_64.S.o
build/crypto/CMakeFiles/crypto.dir/rc4/rc4-md5-elf-x86_64.S.o
build/crypto/CMakeFiles/crypto.dir/modes/ghash-elf-x86_64.S.o
build/crypto/CMakeFiles/crypto.dir/md5/md5-elf-x86_64.S.o
build/crypto/CMakeFiles/crypto.dir/camellia/cmll-elf-x86_64.S.o
build/crypto/CMakeFiles/crypto.dir/bn/gf2m-elf-x86_64.S.o
build/crypto/CMakeFiles/crypto.dir/bn/mont5-elf-x86_64.S.o
build/crypto/CMakeFiles/crypto.dir/bn/mont-elf-x86_64.S.o
build/crypto/CMakeFiles/crypto.dir/bn/modexp512-elf-x86_64.S.o
build/crypto/CMakeFiles/crypto.dir/aes/aes-elf-x86_64.S.o
build/crypto/CMakeFiles/crypto.dir/aes/bsaes-elf-x86_64.S.o
build/crypto/CMakeFiles/crypto.dir/aes/aesni-sha1-elf-x86_64.S.o
build/crypto/CMakeFiles/crypto.dir/aes/aesni-elf-x86_64.S.o
build/crypto/CMakeFiles/crypto.dir/aes/vpaes-elf-x86_64.S.o
```
</details>

The `.S` files for these are present in the source tarball. It looks like they are generated from [scripts like these (cvs)](https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/lib/libcrypto/aes/asm/), but I don’t know exactly how. I will open an issue at [libressl-portable/portable](https://github.com/libressl-portable/portable) to ask if anything can be done about it upstream.

In the mean time, now that we know where the executable stack flag comes from, I think `-z noexecstack` is safe to apply.

**Review by matthewbauer — APPROVED** [review]
Looks good for now. Ideally we can find the root cause, but for now this change along with the comments are okay.

**Comment by ruuda** [comment]
I’ve added a new commit that uses `CMAKE_C_FLAGS=-DHAVE_GNU_STACK` instead of `NIX_LDFLAGS=-z noexecstack`, and I have confirmed that this also clears the executable stack flag. I don’t know how this affects Darwin. If the extra define is not harmful, I think this is a bit nicer than the conditional LDFLAG, but taking c02b4a1cc8c718d4e6a1ef5fbb547388bb4636df is fine with me too.

**Comment by matthewbauer** [comment]
@GrahamcOfBorg build libressl

**Pull request merged**
