### PR TITLE
zoom-us: 5.9.6.2225 -> 5.10.0.2450

### PR DESCRIPTION
**Pull request by LutzCle**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

This PR updates Zoom to the latest version, and fixes the missing dependencies.

However, Zoom fails to run with the message:
```
No PulseAudio daemon running, or not running as session daemon.
```
Note that I'm testing with PipeWire. Am I missing something?

### CODE REVIEW

**Comment by doronbehar** [comment]
> No PulseAudio daemon running, or not running as session daemon.

I get this error too, and I run pulseaudio and not pipewire, for as far as I know.

**Comment by cole-h** [comment]
@ofborg eval

**Comment by dtzWill** [comment]
Don't suppose upstream has any response? The linked issue doesn't work for me, even after signing in, so I'd guess limits access to reporter.

**Comment by LutzCle** [comment]
@dtzWill Sorry, I assumed the Zoom issue was public. Doesn't look like I can change access permissions, though. If you decide to file your own issue, perhaps you can still reference this one.

To summarize the status: My Zoom issue is still open. Customer support recommended a downgrade to version 5.9.6.2225, and then bumped the issue to "the next level of support". I'm now waiting on a response from the next support level.

**Comment by LutzCle** [comment]
Status update: I received a response from an engineer. Essentially, the message is that NixOS isn't supported.

In the meantime, I looked at the strace output, but nothing catches my eye. I tried updating PipeWire to v0.3.48 in nixos-unstable, same result as with v0.3.42.

Not sure how to proceed.

**Comment by dtzWill** [comment]
Found this, suggesting there may be some ABI issue re:glibc 2.34: https://community.zoom.com/t5/Meetings/Version-5-10-0-crashing-at-startup-on-Fedora-35/td-p/51487 .  We have glibc 2.33 on master and 2.34 on staging, building this with staging to see if that helps, let's see! :)

Actually, while that's still building (gcc 11 too, etc.) I did some testing and found that zoom tried loading libudev but fails and then exits (`strace`, `LD_DEBUG=libs`, and logs, together helped here).  Pushed commit adding the dependency, does that help things for anyone else?
(since it's linux-only in our packaging, I think we don't need to make its use conditional?)

---


FWIW zoom does things like: 

```
1651040 13:42:43 execve("/bin/sh", ["sh", "-c", "pacmd list-sinks |grep 'name:\\|module:'"], 0x7ffc5bd280a0 /* 99 vars */ <unfinished ...>
```

Although I think it uses pulse API more directly as well (surely)? But ensuring pacmd is on PATH might be a good idea, I think it is for systems using pulseaudio .

**Comment by doronbehar** [comment]
> since it's linux-only in our packaging, I think we don't need to make its use conditional?

Wait for https://github.com/NixOS/nixpkgs/pull/166428

**Comment by doronbehar** [comment]
This works for me here with the udev change, thanks a lot @dtzWill !

**Comment by doronbehar** [comment]
@LutzCle could you confirm that it works for you too, not on staging, with glibc 2.33 ?

**Comment by LutzCle** [comment]
@dtzWill Thanks!

@doronbehar I can confirm that zoom launches now with dtzWill's patch and both glibc 2.33 and 2.34 (staging).

However, I couldn't test any calls. Single sign on and starting meetings from the browser don't work with v5.10.0 (tested with Chromium and Firefox). I checked the log file, but all it shows is the hand-off from one zoom process to another:

```sh
...
Zoom is running, send message to it: -wrapped zoommtg://my-employer.zoom.us/sso?token=Y...
Exit zoom as another zoom instance is running!
ATTENTION: default value of option mesa_glthread overridden by environment.
No PulseAudio daemon running, or not running as session daemon.
zoom exited normally, exit code is 0 .
ZoomLauncher exit.
...
```

Can either of you reproduce this?

**Comment by doronbehar** [comment]
> Single sign on

Never used it, so I can't confirm, but there are reports of issues with it even with much older Zoom versions - https://github.com/NixOS/nixpkgs/issues/73532

> Starting meetings from the browser

I too get a crash when opening meetings, from the browser or by entering a meeting ID. I had issues with it in the previous version as well. It worked me for 1 time though, didn't found anything interesting in the `strace`. The log has:

```
ZoomLauncher exit.
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
AVX2 model initialized!
This plugin does not support setting window opacity
This plugin does not support setting window opacity
AVX2 model initialized!
qt.scenegraph.general: Using sg animation driver
qt.scenegraph.general: Animation Driver: using vsync: 16.67 ms
qt.scenegraph.general: texture atlas dimensions: 2048x1024
zoom was exited due to a handled signal: 11 
```

**Comment by LutzCle** [comment]
So I tested a Zoom call, it works again.

The other issue regarding SSO is separate, so from my side we can merge this PR.

**Comment by maxhbr** [comment]
Starting meetings from the browser don't work for me also and **I do not think that this is separate**. The issue is not #73532, but the problem is that passing meeting coordinates via calling `$ zoom-us 'zoommtg://zoom.us/join?action=join&confno=XXXXXXXXX'` is no longer working. This could previously be used to join calls. That mechanism is also used to bring SSO information from the browser to the application.

In `~/.zoom/logs/zoom_stdout_stderr.log` I see the following:
```
[....]
cmd line: zoommtg://zoom.us/join?action=join&confno=XXXXXXXXX
Start subprocess: /nix/store/j4cj3a2dfw53cb3sdyisq1f4x2sjrd5z-zoom-5.10.0.2450/opt/zoom/zoom sucessfully,  process pid: 1369141 
pactl: symbol lookup error: /nix/store/q29bwjibv9gi9n86203s38n0577w09sx-glibc-2.33-117/lib/libpthread.so.0: undefined symbol: __libc_siglongjmp, version GLIBC_PRIVATE
                             Class      App      Lib Possible Culprit Flags
                resip::Connection      648      648 
                      resip::Data       36       36 
                 resip::DnsResult     1080     1080 
                   resip::Headers        1        1 
          resip::MsgHeaderScanner       40       40 
                resip::SipMessage     5208     5208 
         resip::TransportSelector      864      864 
                     resip::Tuple      128      128 
              resip::UdpTransport     1144     1144 
          resip::GenericIPAddress       28       28 

zoom started.
pactl: symbol lookup error: /nix/store/q29bwjibv9gi9n86203s38n0577w09sx-glibc-2.33-117/lib/libpthread.so.0: undefined symbol: __libc_siglongjmp, version GLIBC_PRIVATE
pactl: symbol lookup error: /nix/store/q29bwjibv9gi9n86203s38n0577w09sx-glibc-2.33-117/lib/libpthread.so.0: undefined symbol: __libc_siglongjmp, version GLIBC_PRIVATE
                                           Class             App             Lib  ClassPossible Culprit Flags 
          App             Lib   Possible Culprit Flags 
  resip:: Connection         648        648   
              resip:: Connection         648        648   
              resip:: Data         36         36   
                resip:: Data         36         36   
    resip:: DnsResult       1080       1080   
                resip:: DnsResult       1080       1080   
        resip:: Headers          1          1   
                resip:: Headers  resip::       1MsgHeaderScanner         1      40  
      40   
                resip:: MsgHeaderScanner         40         40   
  resip:: SipMessage       5208       5208   
                resip:: SipMessageresip:: TransportSelector    5208       864    5208       864
  
                resip:: TransportSelector        864        864   
            resip:: Tuple        128        128   
                resip:: Tuple        128        128  resip::
UdpTransport       1144       1144   
                resip:: UdpTransport  resip::    1144GenericIPAddress      1144      28  
      28   
 
       resip::GenericIPAddress       28       28 

zoom started.
zoom started.
Client: Breakpad is using Single Client Mode! client fd = -1
```

In the UI I see no feedback.

**Comment by doronbehar** [comment]
I too think we should not merge this.

**Comment by dtzWill** [comment]
```
pactl: symbol lookup error: /nix/store/q29bwjibv9gi9n86203s38n0577w09sx-glibc-2.33-117/lib/libpthread.so.0: undefined symbol: __libc_siglongjmp, version GLIBC_PRIVATE
```

Is your system `pactl` using glibc 3.34 with a zoom using 3.33 (or other way around)?  Since pactl is from PATH, when launched from our wrapper that sets LD_LIBRARY_PATH maybe that's causing `pactl` to pickup the wrong glibc?

One solution I hinted at earlier is to plumb into our zoom wrapper the needed utilities--normally I'd encourage this in name of making the program self-contained (and not fragile w.r.t. depending on (uncontrolled) system requirements), but we want to make it work nicely for folks not using pulseaudio (esp as things seem to move to pipewire!)?

Anyway if you're seeing the glibc symbol error and both zoom and pactl use the same glibc (for this, just checking each via `nix-store -qR $(readlink -f $(which pactl))|grep glibc` or so should be enough, same for `zoom-us`) that's definitely strange.

I'll see about testing the zoommtg support here, just for another point.

**Comment by LutzCle** [comment]
I can report that the issue regarding meeting coordinates still persists in the latest Zoom version 5.10.3 (2778).

**Comment by dtzWill** [comment]
There's a 5.10.4 now FWIW, don't suppose that helps? :pray:

**Comment by LutzCle** [comment]
Unfortunately not, the issue persists in version 5.10.4.2845.

Flatpack seemed to have a similar issue, which was fixed: https://github.com/flathub/us.zoom.Zoom/commit/66af224bf0041672da2f2b80622d1a56f3b585bd. However, I'm not sure if this is relevant for Nix.

**Comment by tomjnixon** [comment]
I think I found the issue!

It seems like it inspects the executable name (rather than just argv[0]), and so "-wrapped" makes its way into the message sent to the socket that's used for IPC (if you're looking in strace it's something like `/run/user/1001/qtsingleapp-zoomwr-3e9`).

With the wrapper changed to `.zoom` SSO at least works. The latest version seems ok too.

```diff
diff --git a/pkgs/applications/networking/instant-messengers/zoom-us/default.nix b/pkgs/applications/networking/instant-messengers/zoom-us/default.nix
index 0983288f227..805aa799eb3 100644
--- a/pkgs/applications/networking/instant-messengers/zoom-us/default.nix
+++ b/pkgs/applications/networking/instant-messengers/zoom-us/default.nix
@@ -37,11 +37,11 @@
 }:
 
 let
-  version = "5.10.0.2450";
+  version = "5.10.4.2845";
   srcs = {
     x86_64-linux = fetchurl {
       url = "https://zoom.us/client/${version}/zoom_x86_64.pkg.tar.xz";
-      sha256 = "CoK7kqUXnFmlFb81K7722wIAb2OOTg6NQneo1bD6cYw=";
+      sha256 = "9gspydrGaEjzAM0nK1u0XNm07HTupJ2wnPxCFWy+Nts=";
     };
   };
 
@@ -116,7 +116,9 @@ stdenv.mkDerivation rec {
     done
 
     # ZoomLauncher sets LD_LIBRARY_PATH before execing zoom
-    wrapProgram $out/opt/zoom/zoom \
+    # IPC breaks if the executable name does not end in 'zoom'
+    mv $out/opt/zoom/zoom $out/opt/zoom/.zoom
+    makeWrapper $out/opt/zoom/.zoom $out/opt/zoom/zoom \
       --prefix LD_LIBRARY_PATH ":" ${libs}
 
     rm $out/bin/zoom
```

**Comment by LutzCle** [comment]
Wow, it works again! I tested both SSO and zoommtg links, works fine for me.

@tomjnixon Can you push your fix to a branch, so that I can merge your commit into this PR? I guess we should split out the version update into a separate PR.

**Comment by tomjnixon** [comment]
> @tomjnixon Can you push your fix to a branch, so that I can merge your commit into this PR? I guess we should split out the version update into a separate PR.

Sure, they are here:
https://github.com/NixOS/nixpkgs/compare/LutzCle:zoom...tomjnixon:zoom

I also rebased onto master here, and gave it a quick test:

https://github.com/NixOS/nixpkgs/compare/master...tomjnixon:zoom_rebase

This is required because the package has changed a bit since this PR started. If you like you could reset to that, or I could make a new PR. I don't see the need to have separate PRs for two arbitrary version bumps.

**Comment by doronbehar** [comment]
Thanks for the rebase @tomjnixon . To progress this, I opened a PR from your `zoom_rebase` branch, I'm closing this one due to the merge conflicts.

**Pull request closed without merging**
