### PR TITLE
buildMavenPackage: add doCheck support

### PR DESCRIPTION
**Pull request by superherointj**
* buildMavenPackage: add doCheck support
* normalize doCheck: h2, kotlin-interactive-shell, sonarlint-ls, ns-usbloader, openrefine, commafeed, java-language-server, forge-mtg, mariadb-connector-java, s3proxy

### CODE REVIEW

**Comment by AndersonTorres** [comment]
1. I am dealing with these files too: https://github.com/NixOS/nixpkgs/pull/316764
2. cko, the maintainer of Maven, is on the retirements list: https://github.com/NixOS/nixpkgs/issues/290642

**Comment by superherointj** [comment]
> 1. I am dealing with these files too: [Maven: refactor #316764](https://github.com/NixOS/nixpkgs/pull/316764)

What a coincidence of timing. This was on my queue for quite some time.

> What do you think about merge both PRs?

By merge, unify as one?
Wouldn't be simpler to just merge this first. (Because it's simple and straightforward.)
And then I review your PR.

**Comment by AndersonTorres** [comment]
Nice. I will wait your PR, then.

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 316765` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>jd-cli</li>
  </ul>
</details>
<details>
  <summary>27 packages built:</summary>
  <ul>
    <li>apgdiff</li>
    <li>bytecode-viewer</li>
    <li>certificate-ripper</li>
    <li>commafeed</li>
    <li>cryptomator</li>
    <li>digital</li>
    <li>forge-mtg</li>
    <li>gephi</li>
    <li>global-platform-pro</li>
    <li>h2</li>
    <li>h2.doc</li>
    <li>java-language-server</li>
    <li>jugglinglab</li>
    <li>kotlin-interactive-shell</li>
    <li>ktfmt</li>
    <li>lemminx</li>
    <li>mariadb-connector-java</li>
    <li>ns-usbloader</li>
    <li>openrefine</li>
    <li>quark-goldleaf</li>
    <li>runelite</li>
    <li>s3proxy</li>
    <li>scenebuilder</li>
    <li>schemaspy</li>
    <li>slipstream</li>
    <li>sonarlint-ls</li>
    <li>tabula-java</li>
  </ul>
</details>

**Review by starsep — APPROVED** [review]

**Pull request merged**
