### PR TITLE
updated digikam to version 4.10.0

### PR DESCRIPTION
**Pull request by fkz**

### CODE REVIEW

**Comment by geerds** [comment]
CC: @viric @cillianderoiste

**Comment by cillianderoiste** [comment]
Thanks for the PR @fkz, would you mind merging with master again to see if it builds on Travis?

**Comment by cillianderoiste** [comment]
Nevermind, I think there's some other error with the Travis build, I'm testing locally.

**Comment by fkz** [comment]
thanks for merging! I still don't understand these travis problems

**Pull request merged**
