### PR TITLE
aspell: Build with ncurses

### LINKED ISSUE #161203: aspell: Built without curses support
### Describe the bug
The aspell package is built without curses support

### Steps To Reproduce
`aspell -c some_file.txt` doesn’t use bold to mark misspellt logs.

Also, the build logs on hydra say
```
checking for working curses library... not found
```

### Expected behavior
Bold **tpyos**

### Notify maintainers
No maintainers for `aspell`.

I might try to fix that myself (probably just a matter of passing the right library to the build)

### Metadata
```console
~ $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.91, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.335665.0f316e4d72d"`
 - channels(jojo): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by nomeata**
###### Motivation for this change

fix #161203: Enable curses support.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by roberth** [comment]
With dependency autodiscovery and no regression test, this fix is fragile.
Could you write a simple test derivation in `passthru.tests`?

**Comment by nomeata** [comment]
Hmm, I have been trying for a while now, first using `unbuffer -p` and then looking for ANSI codes with `grep`, and then a bit with `expect`, but couldn’t get it it to work nicely with the interactive curses UI of `aspell`.

Maybe a simple
```
ldd ${aspell}/bin/aspell|grep -q curses 
```
would be enough?

**Comment by roberth** [comment]
> Maybe a simple
> 
> ```
> ldd ${aspell}/bin/aspell|grep -q curses 
> ```
> 
> would be enough?

Yeah, at least that covers the mostly likely way it could break.

I didn't expect that this would be hard, but turns out it is.

**Comment by roberth** [comment]
lgtm, but the base branch needs to change to staging.

**Comment by nomeata** [comment]
Base branch changed

**Review by roberth — APPROVED** [review]

**Pull request merged**
