### PR TITLE
haskellPackages.fft: unmark broken

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by sternenseemann — CHANGES_REQUESTED** [review]
Please run `./maintainers/scripts/haskell/regenerate-hackage-packages.sh` to regenerate the package set—your manual edit is not quite correct.

It's probably easier to target haskell-updates with this, 23.05 needs a backport anyways.

**Comment by SuperSandro2000** [comment]
done and rebased onto haskell-updates

**Comment by cdepillabout** [comment]
@ofborg build haskellPackages.fft

**Comment by cdepillabout** [comment]
@SuperSandro2000 It looks like the test suite failed for `fft` on x86_64-linux in ofborg:

https://github.com/NixOS/nixpkgs/pull/233884/checks?check_run_id=14058426877

I wonder if this is an expected error?  (In which case, you could mark the package as `dontCheck` and create an issue upstream about the incorrect error.)

**Comment by SuperSandro2000** [comment]
I can reproduce that when merging this branch into haskell-updates, building directly on this branch works. There is no error so I am not sure what I should tell upstream

```
Float
dft idem 1D              : +++ OK, passed 1000 tests.
dftRC/CR idem  1D        : +++ OK, passed 1000 tests.
dftRC dft 1D             : +++ OK, passed 1000 tests.
dht idem 1D              : +++ OK, passed 1000 tests.
dft idem 2D              : +++ OK, passed 1000 tests.
dft idem 2D/2            : +++ OK, passed 1000 tests.
dft idem 2D/2'           : +++ OK, passed 1000 tests.
dftRC/CR idem  2D        : +++ OK, passed 1000 tests.
dftRC dft 2D             : +++ OK, passed 1000 tests.
dftRC dft 2D/2           : +++ OK, passed 1000 tests.
dht idem 2D              : +++ OK, passed 1000 tests.
dft idem 3D              : +++ OK, passed 1000 tests.
dft idem 3D/2            : +++ OK, passed 1000 tests.
dft idem 3D/2'           : +++ OK, passed 1000 tests.
dft idem 3D/3            : +++ OK, passed 1000 tests.
dft idem 3D/3'           : +++ OK, passed 1000 tests.
dft idem 3D/3''          : +++ OK, passed 1000 tests.
Double
dft idem 1D              : +++ OK, passed 1000 tests.
dftRC/CR idem  1D        : +++ OK, passed 1000 tests.
dftRC dft 1D             : +++ OK, passed 1000 tests.
dht idem 1D              : +++ OK, passed 1000 tests.
dft idem 2D              : +++ OK, passed 1000 tests.
dft idem 2D/2            : +++ OK, passed 1000 tests.
dft idem 2D/2'           : +++ OK, passed 1000 tests.
dftRC/CR idem  2D        : +++ OK, passed 1000 tests.
dftRC dft 2D             : +++ OK, passed 1000 tests.
dftRC dft 2D/2           : +++ OK, passed 1000 tests.
dht idem 2D              : +++ OK, passed 1000 tests.
Test suite test-fft: FAIL
Test suite logged to: dist/test/fft-0.1.8.7-test-fft.log
```

**Comment by cdepillabout** [comment]
@SuperSandro2000 Thanks for reporting this.

I went ahead and marked it unbroken and disabled the test suite in fc8620b7cf4 in https://github.com/NixOS/nixpkgs/pull/236431.

My guess is that the tests have recently started failing because of https://github.com/nick8325/quickcheck/issues/359, but it is just a problem in the `fft` test suite.  However, I wasn't able to find an issue tracker for `fft`, so I could even find anywhere to report it :-|

**Comment by SuperSandro2000** [comment]
Thanks!

**Pull request closed without merging**
