### PR TITLE
amazon-ssm-agent: rename from ssm-agent

### PR DESCRIPTION
**Pull request by anthonyroussel**
## Description of changes

I suggest renaming the `ssm-agent` package and module to `amazon-ssm-agent` in order to:

* be consistent with the [upstream package name](https://github.com/aws/amazon-ssm-agent)
* be consistent with the [other distributions and repology](https://repology.org/project/amazon-ssm-agent/versions)
* make it clear that the package can only be used with the Amazon/AWS cloud.
* and make sure you have a pname corresponding to the package name

What do you think?

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by h7x4** [comment]
Just for context' sake, do you happen to know why it wasn't prefixed with `amazon-` in the first place? Did upstream undergo a name change or something?

**Comment by anthonyroussel** [comment]
@h7x4 Hello, thanks for the review!

> Just for context' sake, do you happen to know why it wasn't prefixed with `amazon-` in the first place?

No, I don't know why it wasn't prefixed with `amazon-` in the first place.

Looks like this has always been the case and the pname was already inconsistent with the package attribute name when it was created: https://github.com/nixos/nixpkgs/commit/4c0aae964c9e8d3f3e9361583a88c9c4561f6895

> Did upstream undergo a name change or something?

No, looks like the package has always been called `amazon-ssm-agent` on the upstream side: 
https://github.com/aws/amazon-ssm-agent/tree/v2.0.633.0

**Comment by anthonyroussel** [comment]
Solved conflicts

**Review by h7x4 — APPROVED** [review]

**Comment by anthonyroussel** [comment]
Solved conflicts on nixos/doc/manual/release-notes/rl-2311.section.md

**Review by marsam — APPROVED** [review]

**Comment by anthonyroussel** [comment]
Hello. Would anyone be available to merge this PR after these 2 approvals, please? :)

**Pull request merged**
