### PR TITLE
vdirsyncer: 0.6.0 → 0.7.0

### PR DESCRIPTION
**Pull request by DamienCassou**
also, add 2 news dependencies of vdirsyncer:

click-log: init at 0.1.1
click-threading: init at 0.1.2

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Uh, nice!

For the next time: Can you please add each package in one commit? So you'd have three commits for an package update like this, two introducing new packages, one doing the update.

Anyways: Great! Will checkout the changelog now! :+1:

**Comment by DamienCassou** [comment]
@matthiasbeyer I've just done it. If you like it, please merge.

**Comment by matthiasbeyer** [comment]
Who? I thought this PR was already merged. Nice!

I cannot merge, but I'm sure someone will merge this as soon as the travis build doesn't fail anymore. Maybe you can investigate?

**Comment by pSub** [comment]
Tests releated to timezones fail.

**Comment by DamienCassou** [comment]
this works locally for me...

**Comment by DamienCassou** [comment]
I don't understand what travis is doing:

```
[...]
The invocation of "nix-build -A vdirsyncer -A python35Packages.click-log -A pypyPackages.click-log -A pypyPackages.click-threading -A python35Packages.click-threading -A khard -A khal -A python34Packages.click-threading -A python27Packages.click-threading -A python27Packages.click-log -A python34Packages.click-log /home/travis/.nox/nixpkgs" failed
```

why does it try to install `khard`? It is not a dependency of vdirsyncer. And khard is the one failing, not vdirsyncer.

**Comment by matthiasbeyer** [comment]
What was the error?

**Comment by DamienCassou** [comment]
I don't know why nix/nox was trying to build khard. But I fixed the khard pull request and this fixed this one as well :-).

**Pull request merged**
