### PR TITLE
imagemagick: 7.1.1-25 -> 7.1.1-26

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
Diff: https://github.com/ImageMagick/ImageMagick/compare/7.1.1-25...7.1.1-26

Changelog: https://github.com/ImageMagick/Website/blob/main/ChangeLog.md

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ehmry** [comment]
Staging?

**Comment by dotlambda** [comment]
> Staging?

Let's rather reduce the number of reverse Darwin dependencies. But I don't care about that platform and the Linux number doesn't warrant staging.

**Comment by dotlambda** [comment]
The high number of dependencies seems to stem from `desktopToDarwinBundle` which is used by `mupdf` -> `python3Packages.pikepdf` -> `python3Packages.cairocffi`.

**Comment by SuperSandro2000** [comment]
Sure.

Can we in addition convert desktopToDarwinBundle to only use imagemagick_light? As it only uses convert, on svg's I don't think we need the bigger one. https://github.com/NixOS/nixpkgs/blob/00f5c02ec97a7f0849c9b54736dd3b5d4e35addf/pkgs/build-support/setup-hooks/desktop-to-darwin-bundle.sh#L109C13-L109C27

**Comment by dotlambda** [comment]
> Or can we use a headless mupdf here

That sounds like a nice solution. I'll work on it.

**Comment by dotlambda** [comment]
@ofborg eval

**Comment by dotlambda** [comment]
@ofborg eval

**Comment by SuperSandro2000** [comment]
nix 2.3 somehow doesn't build

```
    ++ nix-instantiate simple.nix
    warning: you did not specify '--add-root'; the result might be removed by the garbage collector
    + drvPath=/build/nix-test/simple/store/h0sg729hgxwhw676dnhnc92r84zihrsb-simple.drv
    ++ nix-store -q --binding system /build/nix-test/simple/store/h0sg729hgxwhw676dnhnc92r84zihrsb-simple.drv
    + test x86_64-linux = x86_64-linux
    + echo 'derivation is /build/nix-test/simple/store/h0sg729hgxwhw676dnhnc92r84zihrsb-simple.drv'
    derivation is /build/nix-test/simple/store/h0sg729hgxwhw676dnhnc92r84zihrsb-simple.drv
    ++ nix-store -rvv /build/nix-test/simple/store/h0sg729hgxwhw676dnhnc92r84zihrsb-simple.drv
    these derivations will be built:
      /build/nix-test/simple/store/h0sg729hgxwhw676dnhnc92r84zihrsb-simple.drv
    executing builder '/nix/store/g8axh6l9mijm0yls9znbwrnd65yzlvaa-bash-5.2-p21/bin/bash'
    building '/build/nix-test/simple/store/h0sg729hgxwhw676dnhnc92r84zihrsb-simple.drv'...
    PATH=
    warning: you did not specify '--add-root'; the result might be removed by the garbage collector
    + outPath=/build/nix-test/simple/store/hwwdpmsykffwa4ajpgf0hj9zj40sgm2y-simple
    + echo 'output path is /build/nix-test/simple/store/hwwdpmsykffwa4ajpgf0hj9zj40sgm2y-simple'
    output path is /build/nix-test/simple/store/hwwdpmsykffwa4ajpgf0hj9zj40sgm2y-simple
    ++ cat /build/nix-test/simple/store/hwwdpmsykffwa4ajpgf0hj9zj40sgm2y-simple/hello
    + text='Hello World!'
    + test 'Hello World!' '!=' 'Hello World!'
    + nix-store --delete /build/nix-test/simple/store/hwwdpmsykffwa4ajpgf0hj9zj40sgm2y-simple
    finding garbage collector roots...
    deleting '/build/nix-test/simple/store/hwwdpmsykffwa4ajpgf0hj9zj40sgm2y-simple'
    deleting '/build/nix-test/simple/store/trash'
    deleting unused links...
    note: currently hard linking saves -0.00 MiB
    1 store paths deleted, 0.00 MiB freed
    + test -e /build/nix-test/simple/store/hwwdpmsykffwa4ajpgf0hj9zj40sgm2y-simple/hello
    ++ NIX_REMOTE='local?store=/foo&real=/build/nix-test/simple/real-store'
    ++ nix-instantiate --readonly-mode hash-check.nix
    warning: you did not specify '--add-root'; the result might be removed by the garbage collector
    + outPath=/foo/q2ivlzbvpm92vrnbrpjvmj7s7ijd559c-dependencies.drv
    + test /foo/q2ivlzbvpm92vrnbrpjvmj7s7ijd559c-dependencies.drv '!=' /foo/lfy1s6ca46rm5r6w4gg9hc0axiakjcnm-dependencies.drv
    + echo 'hashDerivationModulo appears broken, got /foo/q2ivlzbvpm92vrnbrpjvmj7s7ijd559c-dependencies.drv'
    hashDerivationModulo appears broken, got /foo/q2ivlzbvpm92vrnbrpjvmj7s7ijd559c-dependencies.drv
    + exit 1
```

**Comment by dotlambda** [comment]
@ofborg eval

**Comment by dotlambda** [comment]
Yay, this sounds like a reasonable number of rebuilds on Darwin. Let's merge once ofborg is green.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Wait a second, the build is now failing and the ofborg log is not loading for me :(

**Comment by dotlambda** [comment]
I'll merge anyway, those failures can be fixed in staging-next.

**Pull request merged**
