### PR TITLE
Datadog: update packages

### PR DESCRIPTION
**Pull request by Izorkin**
Update datadog packages:
- datadog agent to 6.11.0;
- datadog process agent to 6.11.0;

cc @kalbasit 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Izorkin** [comment]
@GrahamcOfBorg build datadog-agent datadog-process-agent

**Review by c00w — APPROVED** [review]
Simple update
-builds via grahamc and nix-review

**Comment by Izorkin** [comment]
Check with `nix-shell -p nix-review --run 'nix-review pr 59872'`

```
these paths will be fetched (0.03 MiB download, 0.10 MiB unpacked):
  /nix/store/h2qzhwdbhxszlj8d15xf4ap85rghbk94-nix-review-2.0.0
copying path '/nix/store/h2qzhwdbhxszlj8d15xf4ap85rghbk94-nix-review-2.0.0' from 'https://cache.nixos.org'...
$ git fetch --force https://github.com/NixOS/nixpkgs master:refs/nix-review/0 pull/59872/head:refs/nix-review/1
remote: Enumerating objects: 687, done.
remote: Counting objects: 100% (687/687), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 1448 (delta 684), reused 685 (delta 684), pack-reused 761
Получение объектов: 100% (1448/1448), 547.15 KiB | 1.95 MiB/s, готово.
Определение изменений: 100% (997/997), завершено с 343 локальными объектами.
Из https://github.com/NixOS/nixpkgs
   4a11ce7f261..1011fae581e  master               -> refs/nix-review/0
 + 6af5f4c7804...eb299c01687 refs/pull/59872/head -> refs/nix-review/1  (принудительное обновление)
$ git worktree add /home/lf/.cache/nix-review/pr-59872/nixpkgs 1011fae581e1139ea4c9f3e479d604eb5669c5d9
Preparing worktree (detached HEAD 1011fae581e)
Распаковка файлов: 100% (18925/18925), готово.
HEAD сейчас на 1011fae581e Merge pull request #60142 from peterhoeg/u/rng
$ git merge --no-commit eb299c01687f879e373fd0b98cee5f6b71c6fb8a
Автослияние pkgs/top-level/all-packages.nix
Автоматическое слияние прошло успешно; как и запрашивали, остановлено перед выполнением коммита
$ nix build --no-link --keep-going --max-jobs 24 --option build-use-sandbox true -f /home/lf/.cache/nix-review/pr-59872/build.nix
[3 built, 8 copied (27.2 MiB), 3.2 MiB DL]
https://github.com/NixOS/nixpkgs/pull/59872
2 package were build:
datadog-agent datadog-process-agent

[0.0 MiB DL]
error: build log of '/nix/store/k2jy2xys21f7xqpaq15rcqcgzfxh4yc7-datadog-process-agent-6.11.0.drv' is not available

```

**Comment by c00w** [comment]
@Izorkin  - I think that might be a local error on your machine - It seems like it is building succesfully "2 package were build:" - but something about your machine is causing build logs to be inaccessible? "build log of '/nix/store/k2jy2xys21f7xqpaq15rcqcgzfxh4yc7-datadog-process-agent-6.11.0.drv' is not available"

On my machine this seems to work fine.

**Comment by Lassulus** [comment]
works for me with nix-review

**Pull request merged**
