### PR TITLE
Luarocks update

### PR DESCRIPTION
**Pull request by teto**
###### Motivation for this change

Some lua packages have one rockspec per lua interpreter:
https://github.com/NixOS/nixpkgs/commit/c01fe375ca192395af8ae8c575ff8eaa79ed03d8#commitcomment-32572249

I've bumped luarocks that should help with nix integration (noew distinguishes test_dependencies, build_dependencies) as well as it can install rockspecs for a different lua version than its own interpreter. With the luarocks in nixpkgs, I would have to rerun the generator for every interpreter.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
Would you also look at luarocks-nix for 19.03?  It's in some weird state, failing to apply a patch.  https://hydra.nixos.org/jobset/nixos/release-19.03/jobs-tab?filter=luarocks

**Comment by teto** [comment]
I am on holiday with possibly 0 connectivity the next 2 days so woudl appreciate if someone could cherry-pick them. That should be enough ?

**Comment by vcunat** [comment]
Yes, I guess it's been tested enough by being on master for almost a month.  But I see it broke [some `torchPackages`](https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.torchPackages.torch.x86_64-linux) and now I ported that problem to 19.03 :-/ (I realized after pushing).

**Comment by vcunat** [comment]
I reverted that for now due to causing issues; I suppose I'll sacrifice luarocks-nix on 19.03 and work on other nixpkgs stuff.

**Comment by teto** [comment]
fine with me, might be for the best as the doc about the new infra was not merged yet.
I will try to improve the lua infrastructure week end, with converting the pkgs/applications/science/machine-learning/torch/torch-distro.nix and applying some advice from luarocks creators to split build and install phases. This should solve some problems on darwin.

**Pull request merged**
