### PR TITLE
cdrtools: Update to 3.00

### PR DESCRIPTION
**Pull request by nathanielbaxter**
Update cdrtools and unmark as broken.

Only tested building under linux. Although it should build for darwin, etc. I have no means by which to test this.

Should add a license to the package as well. It contains parts that are licensed under CDDL, GPL2 and LPGL2, what do we do in the case of multiple licenses? Note that this is a package where there has been plenty of disagreement regarding the legality of it's licensing ([package maintainers point of view](http://cdrtools.sourceforge.net/private/linux-dist.html)). Could always just mark as unfree and move on, lol.

### CODE REVIEW

**Comment by lethalman** [comment]
Yes let's mark it unfree, after all it was broken before so people won't have any problem.

**Comment by nathanielbaxter** [comment]
Added the unfree license, and a note regarding why it has it.

**Comment by lethalman** [comment]
What's that libbluray patch change?

**Comment by nathanielbaxter** [comment]
Whoops, Rip Travis. 

Accidentally commited a patch from something else I was working on. Fixed it. Thanks! :)

**Comment by lethalman** [comment]
Built locally thanks.

**Pull request merged**
