### PR TITLE
SABnzbd 2.3.2

### PR DESCRIPTION
**Pull request by bflyblue**
###### Motivation for this change

New stable version of SABnzbd.
Added the sabyenc module which is a new (optional) dependency in SABnzbd 2.0+

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by FRidh — CHANGES_REQUESTED** [review]
Considering sabyenc is a fork specifically for sabnzbd, can you move that expression to the sabnzbd expression. Other than that it looks good.

**Comment by FRidh** [comment]
Note it needs to be tested before merging.

**Comment by bflyblue** [comment]
Thank you, I'll move the sabyenc expression and test locally.

**Comment by bflyblue** [comment]
I've made the requested change. I'm still relatively new to nix, would you mind checking I've done it correctly and help with testing? It at least works for me on my system.

**Comment by bflyblue** [comment]
I've tested this on NixOS over the past few days and it's working correctly for me.

**Comment by c0bw3b** [comment]
Closing this since it has been superseded:
* v2.3.3 in #39374
* sabyenc in #44152

**Pull request closed without merging**
