### PR TITLE
Update ocaml to 4.02.1

### PR DESCRIPTION
**Pull request by samuelrivas**
Moving to ocaml 4.02, but some packages won't compile easily. I plan to fix those things that are failing, but first I wanted to have an idea of the scope of fixing that, so this PR just makes them compile with the previous version.

I am not sure this is the best way to proceed, maybe is better to remove the failing packages from ocamlPackages_4_02_1 (they are broken anyway)?

Also, this contains some slightly unrelated bugs that were pointed out by nox. I am not sure why emacsmode and mysql are passing in hydra...

### CODE REVIEW

**Comment by samuelrivas** [comment]
Mmmm, travis was oomkilled. Can someone rerun?

**Comment by vbgl** [comment]
I’ve merged three of your patches in 55ad2d21508333ec21171ceb9e7a16ac3baa6f32 5342e2a598e58a658296de883331048e2329d08a and d1e6f055fe01e3e13a6ba603dd815da2a4d991c8. Thank you.

About `ocaml-mode`, I can’t reproduce the error you report (on linux).

About your last patch, I am not convinced that it is the right thing to do. By the way, the following packages build properly with OCaml 4.02: bolt, ocaml_optcomp, eliom, ocpBuild, ocpIndent, ocp-index, ulex, ocsigen_deriving, js_of_ocaml, vg, ojquery, acgtk. What issue do you encounter with them?

**Comment by samuelrivas** [comment]
Nice, should I rebase to keep just the ones that are not merged yet in this PR?

About `ocaml-mode` it is weird, since I don't see it failing in hydra either, but fails consistently on my (Ubuntu) box. I'll take another look.

The last patch is just a consequence of the first one. I don't think is a definitely solution, but it helps knowing what is (allegedly) broken. In theory (since you say some of the packages are probably not broken), those packages would fail currently for anyone trying to install `ocamlPackages_4_02_1.bolt`, for example. Making ocaml 4_02_1 default just makes it more evident. Since you've merged the obvious bug fixes I could as well close this and open a PR per package, since they are not that many.

It is strange they build for you, I'll check with the latest master. I did most of the work on this PR over a somewhat old master, so some things might have been fixed already. The errors I got were first camlp4 not being present, then, after adding it, some CamlP4 modules being missing. I didn't investigate further yet.

**Comment by vbgl** [comment]
Indeed, most camlp4-related issues have been fixed in #8296. I’ve just fixed mezzo in 8897299e8f375555d9c9819612fede3d5c86ccc9.

**Comment by samuelrivas** [comment]
Ah, cool. Anything left to move to ocaml 4.02? I can take a look during the weekend too

**Comment by samuelrivas** [comment]
`ocaml-mode` still fails reliably on my box:

```
building path(s) ‘/nix/store/ww5dqgvjf2jd4rdc5wfiz63g408pnryj-ocaml-mode-4.02.1’
unpacking sources
unpacking source archive /nix/store/phnh5azcddmg15kwrjlya0nkjfc6516d-ocaml-4.02.1.tar.xz
source root is ocaml-4.02.1
patching sources
configuring
configure flags: -prefix /nix/store/ww5dqgvjf2jd4rdc5wfiz63g408pnryj-ocaml-mode-4.02.1 -no-tk -no-curses -no-pthread 
[ERROR!]Unknown option "-no-tk".
builder for ‘/nix/store/8vw7ds7q4b9pkv4bicnkg8jfkbhn8djj-ocaml-mode-4.02.1.drv’ failed with exit code 2
```

I am using nixpkgs 9d5508d85c33b8fb22d79dde6176792eac2c2696

Very strange

**Comment by samuelrivas** [comment]
bump, should I close this?

**Comment by vcunat** [comment]
So, what's the status of this PR?

**Comment by vbgl** [comment]
I’ve addressed the issue of `ocaml-mode` in 34c59894a6a08518e82c4810f5447a9e8e138b39.

We may be ready to make version 4.02 of OCaml the default. I think there is at least an issue with `why3`.

**Comment by samuelrivas** [comment]
I guess this could be closed and reopened when ready, I didn't have time to look at it for a while and the changes that were working have been merged by vbgl

**Comment by vcunat** [comment]
OK.

**Pull request closed without merging**
