### PR TITLE
i3-gaps: init at 4.12

### PR DESCRIPTION
**Pull request by fmthoma**
###### Motivation for this change

Add the popular i3-gaps fork of the i3 window manager as package and as services.xserver.windowManager option.
###### Things done
- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

`pkgs/applications/window-managers/i3-gaps/default.nix` tries to re-use as much as possible from vanilla i3 build.

### CODE REVIEW

**Comment by domenkozar** [comment]
Travis error logs legit.

**Comment by fmthoma** [comment]
Indeed. Seems like some file permissions are wrong, maybe missing an executable flag. Interesting enough that it used to compile perfectly on my machine as well as a VM. Also it seems odd since this part of the build is not changed between vanilla i3wm and the fork.
Is there some way to inspect the travis build artifacts in order to locate the problem?

**Comment by fmthoma** [comment]
Do not merge right now!

In the latest commit I took the vanilla i3 config and copied it to i3, changing only the name. The build still fails at the same point.
I suspect that probably `nox` messes up the file permissions, and I would argue that they would be correct during the actual build because (a) without `nox`, the PR worked both on my machine and on a clean VM, and (b) `nox` has the same problem with vanilla i3, a package that a lot of users use without any problem.

I leave the test commit for now as proof that the problem still exists with a config file that already is released. Please contact me so that I can remove it.

**Comment by joachifm** [comment]
@fmthoma if you can build this in a sandbox and use the resulting binaries, I'd be inclined to trust that over travis. It'd be good to figure out what causes the problem here, but that looks to me like a separate issue. What do you think?

**Comment by fmthoma** [comment]
@joachifm I agree. I just ran `nix-shell -p nox --run "nox-review wip --against master"` on my machine and everything went fine. So the problem is probably not nox, but maybe travis? My educated guess is that file permissions are somehow reset during unpacking the sources.

I'm going to remove that last commit again, so if you like you can merge the PR. Or you can use it for debugging travis ;-)

**Comment by obadz** [comment]
Does it make sense to have `i3-gaps` be a fully different package/module rather than add an argument to the existing `i3` package that would flip to a different `src` and module option that would toggle said argument?

**Comment by obadz** [comment]
@fmthoma, pls see if this commit would work for you?

**Comment by fmthoma** [comment]
@obadz Good point. As for the i3 package, I agree that an override option might be worth considering. In particular, it makes the dependency between i3 and i3-gaps obvious for maintainers of the i3 package. On the other hand, a separate package allows to decouple version numbers (e.g. when a new i3 version comes out and i3-gaps lags behind). Besides (but that is a personal preference) I prefer polymorphism over if-then-else, and that is a lot of if-then-else expressions sprinkled over that file ;-)

As for the window-managers entry, I am not sure whether this is really helping. The fork is quite well known as i3-gaps, so from a user perspective, putting `windowManager.default = 'i3-gaps'` would seem like the obvious thing to do, much more obvious than setting a rather arcane `windowManager.i3.use-i3-gaps = true` option.

**Comment by obadz** [comment]
I don't have a strong view. @domenkozar you want to opine?

**Comment by obadz** [comment]
cc @vcunat @garbas @aszlig for a tie-breaking opinion

**Comment by garbas** [comment]
i'm -1 on this PR

i'd prefer if all i3 related package, extensions, patches, forks are in ``pkgs/applications/window-managers/i3`` folder. 

also there is really no need to have another nixos module. you can introduce ``package`` where by default is ``i3`` and anybody can override it. this is quite standard across other modules. i'd say it is more important to keep consistency across nixpkgs rather then please each maintainer.

also it should be possible to have ``windowManager.default = 'i3-gaps'`` while reusing the same module. you would just need to set name of session name from above configured package name.

**Comment by obadz** [comment]
@garbas: what do you think of 7160cca176cfad77a6c46f54e3514d4ca4b15dbf ?

**Comment by garbas** [comment]
@obadz apart from what i commented on i think @fmthoma PR is good. did you already pushed i3-gaps?

**Comment by fmthoma** [comment]
@garbas So you would prefer to have one file for the i3 package including the fork, and one file for the i3 windowManager including the fork, right? I think this is reasonable. I see what I can do tomorrow :-)

**Comment by garbas** [comment]
@fmthoma 

 - two files for i3 package (like you implemented with overrideDerivation)
 - move ``pkgs/applications/window-managers/i3-gaps/default.nix`` to ``pkgs/applications/window-managers/i3/gaps.nix`` to have all i3 stuff in one folder
 - one i3 nixos module that would work with both i3 packages

sorry i'm a bit short on time today to explain all in details, so i tried to put everything in short bullet points. please ask if something does not makes sense.

**Comment by fmthoma** [comment]
@garbas No problem :-) I just pushed the changed PR.

**Comment by obadz** [comment]
@fmthoma, sorry to keep making you jump through hoops, but in `i3-gaps.nix` rather than copy-pasting `i3.nix`, would you mind invoking `callPackage` and only override those fields that are changing?

**Comment by fmthoma** [comment]
@obadz The file is not present any more in the updated PR. Although I used a different approach, parameterizing the entire package.

**Comment by obadz** [comment]
@fmthoma: merged! thank you for your patience.

**Comment by obadz** [comment]
Tested both `i3` and `i3-gaps` in a qemu VM: saw no visible difference but I'm pretty sure the right versions were indeed what was running.

**Comment by fmthoma** [comment]
Thanks you!
Yes, the difference will show only when gaps or transparency are configured in `~/.i3/config`.

**Pull request closed without merging**
