### PR TITLE
mesa: remove darwin-specific derivations

### PR DESCRIPTION
**Pull request by matthewbauer**
The ‘mesa-darwin’ stuff was very out of date (2012). This moves darwin
to use the newer mesa. Stuff seems to build okay. Needs more testing
on other stuff though (libraries work). No drivers build but that is
how it should work on macOS.

/cc @cstrahan @Anton-Latukha

###### Motivation for this change

Trying to eliminate duplication in Nixpkgs.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
I assume the linux rebuild is just about not passing `virgl` twice anymore.

**Comment by vcunat** [comment]
How this works on macos?  The driver is provided by OS but apps are supposed/OK to use source-built mesa's libGL?

**Comment by matthewbauer** [comment]
> How this works on macos? The driver is provided by OS but apps are supposed/OK to use source-built mesa's libGL?

Yeah that looks like it. Mostly stuff like ```libGL``` and stuff are needed to compile a few dependencies.

**Comment by vcunat** [comment]
On Linux we've migrated to build-time linking just with the stub libraries provided by glvnd instead of mesa. (And the stubs are supposed to find the right real libraries during runtime).

**Comment by matthewbauer** [comment]
Ok maybe this won't work then. May need to be reverted if it breaks stuff. My main goal here is just to get rid of the duplication (and also update the mesa version for darwin).

**Pull request merged**
