### PR TITLE
forgejo: actually run go tests

### PR DESCRIPTION
**Pull request by emilylange**
## Description of changes

We cannot rely on `buildGoModule`'s default test selection if `subPackages` is set:

~~~
Running phase: checkPhase
?       code.gitea.io/gitea     [no test files]
?       code.gitea.io/gitea/contrib/environment-to-ini  [no test files]
checkPhase completed in 53 seconds
~~~

So we override it in `preCheck` and skip some tests that fail in our sandbox (e.g. because they require networking).

Note that this does slow down building the package quite a bit because there are a lot of tests to run.

Still worth it IMHO.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pyrox0** [comment]
Result of `nixpkgs-review pr 320085` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>forgejo</li>
    <li>forgejo.data</li>
  </ul>
</details>

**Review by pyrox0 — APPROVED** [review]

**Comment by adamcstephens** [comment]
Hmm, this consistently fails to build for me:

```
2024/06/15 20:56:10 ...les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at /build/go-build3765734460/b001/data/actions_artifacts

[1] Test Check
OK

All done (checks: 1).
--- FAIL: TestAddRecursiveExclude (0.00s)
    --- FAIL: TestAddRecursiveExclude/File_inside_directory (0.00s)
        --- FAIL: TestAddRecursiveExclude/File_inside_directory/No_exclude (0.00s)
            dump_test.go:83:
                        Error Trace:    /build/source/cmd/dump_test.go:83
                        Error:          Not equal:
                                        expected: "deep/nested/folder/example"
                                        actual  : "deep/nested/folder/another-file"

                                        Diff:
                                        --- Expected
                                        +++ Actual
                                        @@ -1 +1 @@
                                        -deep/nested/folder/example
                                        +deep/nested/folder/another-file
                        Test:           TestAddRecursiveExclude/File_inside_directory/No_exclude
            dump_test.go:84:
                        Error Trace:    /build/source/cmd/dump_test.go:84
                        Error:          Not equal:
                                        expected: "deep/nested/folder/another-file"
                                        actual  : "deep/nested/folder/example"

                                        Diff:
                                        --- Expected
                                        +++ Actual
                                        @@ -1 +1 @@
                                        -deep/nested/folder/another-file
                                        +deep/nested/folder/example
                        Test:           TestAddRecursiveExclude/File_inside_directory/No_exclude

Forgejo: Protocol: format length error

Forgejo: Protocol: format length error

Forgejo: Protocol: write error

Forgejo: Protocol: write error

2024/06/15 20:56:11 ...les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at /build/TestMigratePackages255460776/001
2024/06/15 20:56:11 ...les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at /build/TestMigrateActionsArtifacts2597845411/001
2024/06/15 20:56:11 ...les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at /build/TestMigrateActionsArtifacts2597845411/002
2024/06/15 20:56:11 ...d/migrate_storage.go:174:func3() [W] ignored: actions artifact /notfound exists in the database but not in storage
FAIL
FAIL    code.gitea.io/gitea/cmd 1.012s
FAIL
error: builder for '/nix/store/l1cgsk6jmnjk7i8jr2d5ha1hpggdics4-forgejo-7.0.4.drv' failed with exit code 1;
       last 10 log lines:
       >
       > Forgejo: Protocol: write error
       >
       > 2024/06/15 20:56:11 ...les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at /build/TestMigratePackages255460776/001
       > 2024/06/15 20:56:11 ...les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at /build/TestMigrateActionsArtifacts2597845411/001
       > 2024/06/15 20:56:11 ...les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at /build/TestMigrateActionsArtifacts2597845411/002
       > 2024/06/15 20:56:11 ...d/migrate_storage.go:174:func3() [W] ignored: actions artifact /notfound exists in the database but not in storage
       > FAIL
       > FAIL    code.gitea.io/gitea/cmd 1.012s
       > FAIL
       For full logs, run 'nix log /nix/store/l1cgsk6jmnjk7i8jr2d5ha1hpggdics4-forgejo-7.0.4.drv'.
```

**Comment by emilylange** [comment]
Hmm that's odd.

**Comment by emilylange** [comment]
I opened https://codeberg.org/forgejo/forgejo/pulls/4161 (upstream) to fix this.

**Comment by emilylange** [comment]
Opinions on how to proceed?

Given this has been merged and backported upstream, we could wait with this PR here until `7.0.5` is released.
We could also add that patch to nixpkgs temporarily, or add `TestAddRecursiveExclude` to `skippedTests`.

**Comment by adamcstephens** [comment]
I guess I’d lean towards getting this in now by skipping or patching, to reduce combining the two changes into one. I don’t have a strong opinion though so whatever you’d prefer works for me.

**Comment by emilylange** [comment]
Decided to patch it instead of skipping. That way, it's harder to forget when `7.0.5` is released, since the patch will no longer apply and will abort the build.

**Review by bendlas — APPROVED** [review]

**Review by pyrox0 — APPROVED** [review]

**Pull request merged**
