### PR TITLE
python3Packages.flask-migrate: 3.1.0 -> 4.0.2

### PR DESCRIPTION
**Pull request by gador**
Signed-off-by: Florian Brandes <florian.brandes@posteo.de>

###### Description of changes

[Changelog](https://github.com/miguelgrinberg/Flask-Migrate/blob/main/CHANGES.md)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 212984` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>powerdns-admin</li>
    <li>privacyidea</li>
    <li>python310Packages.ihatemoney</li>
    <li>python311Packages.ihatemoney</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>pgadmin4</li>
    <li>python310Packages.flask_migrate</li>
    <li>python311Packages.flask_migrate</li>
  </ul>
</details>

**Comment by NickCao** [comment]
The rabbit hole is really deep, the flask-sqlalchemy update breaks so many things.

**Comment by gador** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 212984` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>4 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>powerdns-admin: log was empty</li>
<li>privacyidea: log was empty</li>
<li>python310Packages.ihatemoney: log was empty</li>
<li>python311Packages.ihatemoney: log was empty</li>
  </ul>
</details>
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>pgadmin4</li>
<li>python310Packages.flask_migrate</li>
<li>python311Packages.flask_migrate</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
python310Packages.ihatemoney:
<details>


warning: unused-argument
Unused argument: `alembic`.
Near pkgs/development/python-modules/ihatemoney/default.nix:6:3:

```
  |
6 | , alembic
  |   ^
```
warning: unused-argument
Unused argument: `sqlalchemy-utils`.
Near pkgs/development/python-modules/ihatemoney/default.nix:32:3:

```
   |
32 | , sqlalchemy-utils
   |   ^
```
warning: unused-argument
Unused argument: `sqlalchemy-i18n`.
Near pkgs/development/python-modules/ihatemoney/default.nix:34:3:

```
   |
34 | , sqlalchemy-i18n
   |   ^
```
</details>
python311Packages.ihatemoney:
<details>


warning: unused-argument
Unused argument: `alembic`.
Near pkgs/development/python-modules/ihatemoney/default.nix:6:3:

```
  |
6 | , alembic
  |   ^
```
warning: unused-argument
Unused argument: `sqlalchemy-utils`.
Near pkgs/development/python-modules/ihatemoney/default.nix:32:3:

```
   |
32 | , sqlalchemy-utils
   |   ^
```
warning: unused-argument
Unused argument: `sqlalchemy-i18n`.
Near pkgs/development/python-modules/ihatemoney/default.nix:34:3:

```
   |
34 | , sqlalchemy-i18n
   |   ^
```
</details>
</details>

**Comment by NickCao** [comment]
@ofborg test pgadmin4 pgadmin4-standalone

**Review by NickCao — APPROVED** [review]
At least this introduces no new regressions

**Pull request merged**
