### PR TITLE
mpv: split dev output

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
Separate man? Why? Usually manpages are small.

**Comment by SuperSandro2000** [comment]
> Separate man? Why? Usually manpages are small.

Why not? Better to split everything feasible in one go.

**Comment by AndersonTorres** [comment]
> Why not? Better to split everything feasible in one go.

There is little gain in splitting manpages. They occupy very little disk space and require almost nothing to be processed and read (gunzip and reformat) by end users.
Doing a quick calculation, `mpv.1.gz` has 220K while `mpv.1` has 696K. Less than an 8-inch dual-sided floppy disk.
On the other hand, `mpv` had 2.6M, and the whole `<hash>-mpv-<version>` has almost 6M, almost evenly divided between `bin/` and `lib/` dirs.

Further, a typical end user expects manpages for the things she installs.
Indeed it is frustrating to `man something` and be replied with `No manual entry for <...>`.
Requiring that a user explicitly installs manpages in order to use them is counterproductive.

**Comment by Ma27** [comment]
The man output gets installed by default, but you can turn it off to save disk space.

**Comment by SuperSandro2000** [comment]
> Further, a typical end user expects manpages for the things she installs.
Indeed it is frustrating to man something and be replied with No manual entry for <...>.
Requiring that a user explicitly installs manpages in order to use them is counterproductive.

That is an error in your configuration because you have manpages turned off 😄

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 135340` at 145b75fe run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/0a7a367b62851ca8382d78c4b425ad07">sublime-music</a></li>
  </ul>
</details>
<details>
  <summary>1 package skipped due to time constraints:</summary>
  <ul>
    <li>plex-mpv-shim</li>
  </ul>
</details>
<details>
  <summary>16 packages built successfully:</summary>
  <ul>
    <li>anki</li>
    <li>ankisyncd</li>
    <li>celluloid</li>
    <li>curseradio</li>
    <li>hydrus</li>
    <li>jellyfin-mpv-shim</li>
    <li>jftui</li>
    <li>minitube</li>
    <li>mnemosyne</li>
    <li>mpc-qt</li>
    <li>mpv-unwrapped</li>
    <li>mpvScripts.mpris</li>
    <li>python38Packages.mpv</li>
    <li>python39Packages.mpv</li>
    <li>qimgv</li>
    <li>somafm-cli</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by nagy** [comment]
Having a separate `man` output allows you also to iterate over every package in nixpkgs that has this output and install them, without having to install the software itself.

This allows you to search all man pages for a cli flag for example and view what software documents this. Similar to how some distributions provide an online man page viewer, but locally. Same thing for `.info` files.

In case you often miss man pages, you can customize `environment.extraOutputsToInstall`:

https://search.nixos.org/options?channel=unstable&show=environment.extraOutputsToInstall&from=0&size=50&sort=relevance&query=extra+outputs

I asked about this exact topic a while back in discourse https://discourse.nixos.org/t/would-output-splitting-prs-be-welcome/11249

**Comment by SuperSandro2000** [comment]
Can we please move the discussion about the man page outputs out of this PR? This seems to be a more fundamental discussion that has nothing really to do with the dev output I originally wanted to change.

**Comment by AndersonTorres** [comment]
> Instead of bikesheeding about a man output we should have probably looked at the dev output change. It caused all packages which use the mpv wrapper to break.

Okay. It's time to open a sprint for them!

**Comment by SuperSandro2000** [comment]
> Okay. It's time to open a sprint for them!

I fixed them already by including all outputs in the wrapper. Not ideal but most packages probably expect the extra things the wrapper does. We could also add extra outputs for the wrapper but I would rather know which packages don't need the wrapper and use the unwrapped version in them.

**Pull request merged**
