### PR TITLE
t1utils: fixes and allow on darwin

### PR DESCRIPTION
**Pull request by sjourdois**
Use github cache (primary URL is 404).
Add autoconf and automake missing deps, and run autoreconf -i (bootstrap.sh).

### CODE REVIEW

**Comment by pSub** [comment]
cc maintainer @bjornfor

**Comment by bjornfor** [comment]
The download URL works fine here.

```
$ wget http://www.lcdf.org/type/t1utils-1.39.tar.gz
--2015-11-06 17:22:50--  http://www.lcdf.org/type/t1utils-1.39.tar.gz
Resolving www.lcdf.org (www.lcdf.org)... 54.86.79.210
Connecting to www.lcdf.org (www.lcdf.org)|54.86.79.210|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 175047 (171K) [application/octet-stream]
Saving to: ‘t1utils-1.39.tar.gz’

t1utils-1.39.tar.gz                                  100%[=======================================================================================================================>] 170,94K   343KB/s   in 0,5s   

2015-11-06 17:22:51 (343 KB/s) - ‘t1utils-1.39.tar.gz’ saved [175047/175047]
```

So -1 on the change to git (which requires pulling in autoconf), but +1 for meta.platforms = all.

**Comment by bjornfor** [comment]
@sjourdois: I set meta.platforms = all in 7df8515bb517a9bc4d87f5b7e5ac5668d17e6982.

**Comment by sjourdois** [comment]
I tried 10 minutes ago, it did not… (I even just checked the 404 in my browser history).
It does now again, that’s strange but nevermind.

Thx for the platforms anyway.

kwisatz

**Comment by bjornfor** [comment]
Weird. Checked in my browser again. Works.

**Pull request closed without merging**
