### PR TITLE
groovebasin package

### PR DESCRIPTION
**Pull request by andrewrk**
This is a package of [Groove Basin](https://github.com/andrewrk/groovebasin) - a music player server with a built in web interface.

The [Nixpkgs Contributors Guide](https://nixos.org/nixpkgs/manual/) does not mention Node.js, so I followed the examples set by tessel and keybase.

package.nix is generated with npm2nix.

### CODE REVIEW

**Comment by andrewrk** [comment]
I used the `postInstall` step to do the build.

**Comment by andrewrk** [comment]
I don't understand this travis CI build error, does anyone else?

**Comment by garbas** [comment]
@andrewrk i kicked travis to rerun. lets see. otherwise the only comment i have is if you can add yourself as a maintainer.

**Comment by garbas** [comment]
weird ... looks like travis has hard to to apply this PR and get conflicts. let me build it locally

**Comment by garbas** [comment]
merged [here](http://git.io/vLEY9)

**Pull request closed without merging**
