### PR TITLE
kramdown-rfc2629: 1.3.37 -> 1.4.1 and move to rubyPackages 

### PR DESCRIPTION
**Pull request by omasanori**
###### Motivation for this change

Updates the package to the latest version. Now the version of `kramdown` required by it matches to the one in `ruby-packages.nix`, so we no longer need to separate it from `ruby-packages.nix`.

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>kramdown-rfc2629 (rubyPackages.kramdown-rfc2629)</li>
    <li>rubyPackages.certified</li>
    <li>rubyPackages.json_pure</li>
    <li>rubyPackages_2_7.certified</li>
    <li>rubyPackages_2_7.json_pure</li>
    <li>rubyPackages_2_7.kramdown-rfc2629</li>
    <li>rubyPackages_3_0.certified</li>
    <li>rubyPackages_3_0.json_pure</li>
    <li>rubyPackages_3_0.kramdown-rfc2629</li>
  </ul>
</details>

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 117283` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
9 packages built:
</summary>
<ul>
<li>rubyPackages.certified (rubyPackages_2_6.certified)</li>
<li>rubyPackages.json_pure (rubyPackages_2_6.json_pure)</li>
<li>rubyPackages.kramdown-rfc2629 (rubyPackages_2_6.kramdown-rfc2629)</li>
<li>rubyPackages_2_7.certified</li>
<li>rubyPackages_2_7.json_pure</li>
<li>rubyPackages_2_7.kramdown-rfc2629</li>
<li>rubyPackages_3_0.certified</li>
<li>rubyPackages_3_0.json_pure</li>
<li>rubyPackages_3_0.kramdown-rfc2629</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
You need to add kramdown-rfc2629 to https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ruby-modules/with-packages/Gemfile

**Comment by omasanori** [comment]
@SuperSandro2000 Thank you for your review. Done.

**Pull request merged**
