### PR TITLE
Rambox Pro 1.3.2 > 1.4.1

### PR DESCRIPTION
**Pull request by kamushadenes**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 104997` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>rambox-pro</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Can you update the electron version this is using and test it?

**Comment by kamushadenes** [comment]
Hello, thank you for reviewing.

I'm extremely new to Nix and NixOS (today is actually my very first day), so I'm having a hard time figuring things out.

Locally, I changed to use electron_7 and the app opens but stays at the loading screen forever.

Can you please point me to the general direction of some documentation on how to package applications in general, specially electron ones, so I can try and fix this?

Thanks!

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 104997` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>rambox-pro</li>
  </ul>
</details>

**Pull request merged**
