### PR TITLE
dhall-json: fix build

### PR DESCRIPTION
**Pull request by marsam**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by cdepillabout — APPROVED** [review]
LGTM

**Review by timokau — APPROVED** [review]
To me as well (though I'd prefer to backport the PR), but I don't feel comfortable merging a haskell PR since I know next to nothing about how those are managed.

**Comment by timokau** [comment]
CC @Infinisil

**Comment by Infinisil** [comment]
Yeah this should go to `haskell-updates`, but the `hackage-packages.nix` change isn't needed there because the file gets regenerated regularly anyways

**Comment by Infinisil** [comment]
I'm pinging @peti for this, but as far as my understanding goes:

I think `haskell-updates` should only be used for updates that influence Haskell package builds, like the `configuration-*` files or `generic-builder.nix`. On that branch hackage2nix will get run with `configuration-hackage2nix.yaml` to regenerate `hackage-packages.nix`, which then gets used [by hydra](https://hydra.nixos.org/jobset/nixpkgs/haskell-updates#tabs-evaluations) to build everything (with potential fixes in `configuration-*.nix` files), whose results then get used to mark packages as broken, which in turn then `configuration-hackage2nix.yaml` again.

And doing this on a separate branch allows Haskell updates to be bunched together so they can be fixed up if necessary and be built by hydra before merging to master

While I guess updates to these files in `master` would also make it to that branch eventually, this might be annoying with merge conflicts, it might take a while for it to apply (if you change `configuration-hackage2nix.nix`), and the changes might make some packages not be cached for some time (since hydra doesn't build haskell changes in master I don't think).

**Comment by peti** [comment]
@Infinisil's explanation in https://github.com/NixOS/nixpkgs/pull/67438#issuecomment-525522019 is exactly right. Manual changes to `hackage-packages.nix` in `master` may cause merge errors on `haskell-updates` that break the automatic scripts and should be avoided. Generally speaking, changes to `configuration-hackage2nix.yaml` almost always need to be merged to `haskell-updates` to achieve the correct effect.

**Pull request merged**
