### PR TITLE
graalvm: 1.0.0-rc3 -> 1.0.0-rc8

### PR DESCRIPTION
**Pull request by NeQuissimus**
I need help, @volth :D 

There is something going on with timestamps (apparently a Python thing where it does not like files with a change time before 1980).
But none of this really helps :D

### CODE REVIEW

**Comment by volth** [comment]
https://github.com/NeQuissimus/nixpkgs/pull/2

**Comment by FRidh** [comment]
Maybe `export SOURCE_DATE_EPOCH=315532800` or `ensureNewerSourcesForZipFilesHook`.

**Comment by NeQuissimus** [comment]
Thank you! Things look good now :)

**Comment by volth** [comment]
> ```native-image``` needed a couple more fixes, included them as well

Yes, I have ```gcc``` in ```environment.systemPackages``` so never hit this issue

**Comment by NeQuissimus** [comment]
The same is true for the builds, I suppose :)

**Pull request merged**
