### PR TITLE
glpaper: unstable-2020-03-30 -> unstable-2020-10-11

### PR DESCRIPTION
**Pull request by Slabity**
###### Motivation for this change
Updates to most recent version.

Previous version would segfault.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112364` at 08e20420 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/626a0cee6b0b1a4cce5a179d223d1156">glpaper</a></li></li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112364` at 08e20420 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/90f53c87f3a2e8e981f22b6d95541986">glpaper</a></li></li>
  </ul>
</details>

**Review by lovesegfault — CHANGES_REQUESTED** [review]
Please change the commit message to read `glpaper: unstable-2020-03-30 -> newVersion` and update the `version` in the package to be `unstable-date-of-the-commit`.

**Comment by Slabity** [comment]
> Please change the commit message to read `glpaper: unstable-2020-03-30 -> newVersion` and update the `version` in the package to be `unstable-date-of-the-commit`.

Done. Changed version and commit to `unstable-2020-10-11`

**Comment by lovesegfault** [comment]
> > Please change the commit message to read `glpaper: unstable-2020-03-30 -> newVersion` and update the `version` in the package to be `unstable-date-of-the-commit`.
> 
> Done. Changed version and commit to `unstable-2020-10-11`

Perfect! Thanks for the PR!

Will merge as soon as ofborg settles.

**Review by lovesegfault — APPROVED** [review]

**Pull request merged**
