### PR TITLE
rtl8812au: 5.2.20.2_28373.20180619 -> 5.2.20.2_28373.20190903

### PR DESCRIPTION
**Pull request by danielfullmer**
###### Motivation for this change
Fixes "linuxPackages_5_2.rtl8812au" build.

ZHF #68361

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by symphorien** [comment]
Maybe update the `version` attribute of the derivation ?

**Comment by danielfullmer** [comment]
@symphorien The version currently set to the one indicated in https://github.com/zebulon2/rtl8812au-driver-5.2.20/blob/master/Realtek_Changelog.txt

This repo just contains a bunch of fixes on top of the realtek source code. Do you have a suggestion for what you'd prefer the `version` to be? I could append the current date, but the version string is already very long-- even more so when you consider the derivation `linuxPackages.rtl8812au` prepends the kernel version as well.

**Comment by symphorien** [comment]
If this is the official version, then I guess you can leave it as is.

**Review by worldofpeace — APPROVED** [review]
LGTM with ^

**Pull request merged**
