### PR TITLE
bump: pythonPackages.simanneal, fastjet, herwig

### PR DESCRIPTION
**Pull request by veprbl**
###### Motivation for this change

Bump some of the packages I maintain.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by veprbl** [comment]
@GrahamcOfBorg build python2Packages.simanneal python3Packages.simanneal fastjet herwig

**Comment by veprbl** [comment]
@GrahamcOfBorg build python2Packages.simanneal python3Packages.simanneal fastjet herwig

**Comment by veprbl** [comment]
@GrahamcOfBorg build python2Packages.simanneal python3Packages.simanneal fastjet herwig

**Comment by veprbl** [comment]
@grahamc, there is something wrong with the bot. Is it down?

**Comment by veprbl** [comment]
@GrahamcOfBorg build python2Packages.simanneal python3Packages.simanneal fastjet herwig

**Comment by Mic92** [comment]
Is this ready for review?

**Comment by veprbl** [comment]
@Mic92 Yes, it is!

**Comment by Mic92** [comment]
Is herwig is compatible with aarch64? If not it is better to disable it there.

**Comment by veprbl** [comment]
@Mic92 I don't think anyone will run it on ARM in the near future.

**Pull request merged**
