### PR TITLE
jefferson: 0.4.2 -> 0.4.5

### PR DESCRIPTION
**Pull request by vlaci**
###### Description of changes

- `python-lzo` is switched to `lzallright`, which is the same commit as in https://github.com/NixOS/nixpkgs/pull/233481

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tnias** [comment]
Result of `nixpkgs-review pr 233487` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>jefferson</li>
    <li>jefferson.dist</li>
    <li>python310Packages.lzallright</li>
    <li>python310Packages.lzallright.dist</li>
    <li>python311Packages.lzallright</li>
    <li>python311Packages.lzallright.dist</li>
  </ul>
</details>

Result of `nixpkgs-review pr 233487` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>jefferson</li>
    <li>jefferson.dist</li>
    <li>python310Packages.lzallright</li>
    <li>python310Packages.lzallright.dist</li>
    <li>python311Packages.lzallright</li>
    <li>python311Packages.lzallright.dist</li>
  </ul>
</details>

I successfully built and ran jefferson it against an example image I had flying around. LGTM :rocket:

**Comment by wegank** [comment]
@ofborg build jefferson jefferson.passthru.tests

**Review by tnias — APPROVED** [review]
Result of `nixpkgs-review pr 233487` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>jefferson</li>
    <li>jefferson.dist</li>
    <li>python310Packages.lzallright</li>
    <li>python310Packages.lzallright.dist</li>
    <li>python311Packages.lzallright</li>
    <li>python311Packages.lzallright.dist</li>
  </ul>
</details>

I successfully built and tested it with a local image. LGTM and think this PR should be merged.

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 233487` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>jefferson</li>
    <li>jefferson.dist</li>
    <li>python310Packages.lzallright</li>
    <li>python310Packages.lzallright.dist</li>
    <li>python311Packages.lzallright</li>
    <li>python311Packages.lzallright.dist</li>
  </ul>
</details>

**Pull request merged**
