### PR TITLE
nixos/gnupg: fix gpg-agent when pinentryFlavor is null

### PR DESCRIPTION
**Pull request by corngood**
Problem reported here: https://github.com/doronbehar/nixpkgs/commit/8ea644997f7d92cac129ddbfab14b33997038dae#r120230629

Introduced by #231108

8ea644997f7d92cac129ddbfab14b33997038dae moved the configuration outside the pinentryFlavor check, causing evaluation to fail when it was set to null.

960a5142aa812a2df307a6fab65b25ad698e13b5 removed the upstream systemd units, causing gpg-agent.service to be conditional on pinentryFlavor.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by doronbehar — APPROVED** [review]
LGTM, though I haven't tested.

**Comment by rnhmjoj** [comment]
@GrahamcOfBorg test gnupg

**Comment by rnhmjoj** [comment]
I'm not sure what is the point of `pinentryFlavor = null`. The option default is already picking an appropriate package depending on the DE. Can we just ake the option non-nullable?

**Comment by doronbehar** [comment]
> I'm not sure what is the point of `pinentryFlavor = null`. The option default is already picking an appropriate package depending on the DE. Can't we just make the option non-nullable?

I set `pinentry-program` in my user's `gnupg.conf` to a script in my `~/.bin/` that I manage non decoratively. Hence I don't want `/etc/gnupg/gnupg.conf` to set it to anything, though I still want to use the systemd services NixOS provides.

**Comment by rnhmjoj** [comment]
> Hence I don't want /etc/gnupg/gnupg.conf to set it to anything, though I still want to use the systemd services NixOS provides.

But it shouldn't be a problem: your local gnupg.conf will overrire the global configuration.

**Comment by corngood** [comment]
I added a commit that fixes the documentation for `pinentryFlavor`.

The old docs said:

> If not null, the path to the pinentry binary will be passed to gpg-agent via commandline and thus overrides the pinentry option in gpg-agent.conf in the user's home directory.

You don't need to set it to null any more for your user config to take precedence.

However, I think it's still reasonable to be able to remove the config entry by passing null.

**Comment by doronbehar** [comment]
> > Hence I don't want /etc/gnupg/gnupg.conf to set it to anything, though I still want to use the systemd services NixOS provides.
> 
> But it shouldn't be a problem: your local gnupg.conf will override the global configuration.

Still, that will create a reference to a `pinentry-program` that I don't necessarily want to have in my configuration.

**Comment by corngood** [comment]
This does point out that there's been a behaviour change.  I think it's a good one (i.e. user config taking precedence), but I should probably put something in the release notes.

**Comment by rnhmjoj** [comment]
> via commandline and thus overrides the pinentry option in gpg-agent.conf in the user's home directory.

Oh, I see.

> You don't need to set it to null any more for your user config to take precedence.
> However, I think it's still reasonable to be able to remove the config entry by passing null.

Personally, I would simplify the implementation by removing `null`. A pinentry program must be set anyway and the option wasn't super clear about this. If you don't care about what the default is, it's fine, if you care because you want to provide your one manually, just do so in your home and it's still fine.

**Review by rnhmjoj — APPROVED** [review]
Ok, let's leave it as is.

**Comment by corngood** [comment]
Updated with release note.

**Review by doronbehar — APPROVED** [review]

**Pull request merged**
