### PR TITLE
openssl: remove run-time dependency of perl due to c_rehash

### PR DESCRIPTION
**Pull request by Artturin**
Changes by @adrian-gierakowski  
Replaces perl based c_rehash script with shell script wrapping `openssl rehash`
with the same functionality.

Fixes: #19965
Supersedes: #156776, #83446 https://github.com/NixOS/nixpkgs/pull/219323
Possibly related to: #157093, #82924

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Izorkin** [comment]
Is it possible to make these changes in `quictls`?

**Comment by thomasjm** [comment]
@Izorkin that appears to have been done already in the second commit.

**Comment by Izorkin** [comment]
> @Izorkin that appears to have been done already in the second commit.

Right, I wasn't paying attention :)

**Review by Izorkin — APPROVED** [review]

**Comment by gdamjan** [comment]
built the 2 commits on top of master (x86_64-linux):

image

nice work

**Comment by adrian-gierakowski** [comment]
> built the 2 commits on top of master (x86_64-linux):
> 
> image
> 
> nice work

@gdamjan what’s this TUI you have there for inspecting deps?

**Comment by gdamjan** [comment]
> @gdamjan what’s this TUI you have there for inspecting deps? 

:)
it's  nix-tree
https://github.com/utdemir/nix-tree

**Comment by Artturin** [comment]
Built openssl and quictls on aarch64-darwin

**Comment by adrian-gierakowski** [comment]
🎉

**Pull request merged**
