### PR TITLE
zabbix: 4.4.8 -> 5.0.2

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
New LTS release of `zabbix` :tada: 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
diff LGTM, but did no testing

**Comment by aanderse** [comment]
Needs db changes yet. Still working on that.

**Comment by aanderse** [comment]
ping @PsyanticY @mmahut this is **finally** ready. I have tested that both `server` and `proxy` correctly launch on new install and clicked around a bit on the `web` interface. Ready for merge, but would like a second set of eyes please.

**Comment by jonringer** [comment]
```
https://github.com/NixOS/nixpkgs/pull/87712
1 package blacklisted:
tests.nixos-functions.nixos-test

7 packages built:
zabbix.agent zabbix.proxy-mysql zabbix.proxy-pgsql zabbix.proxy-sqlite zabbix.server zabbix.server-mysql zabbix.web
```

might be nice to get some nixosTests, be easier to assert they are working as intended

**Comment by aanderse** [comment]
Agreed. Not sure if @mmahut was still working on that or not... at one point they were.

**Pull request merged**
