### PR TITLE
bloop: 1.4.3 -> 1.4.4

### PR DESCRIPTION
**Pull request by JesusMtnez**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by JesusMtnez** [comment]
@Tomahna I saw you are maintaining this pkg. I have tried to upgrade, but I haven't found the proper way to calculate the hashes for `darwin` and `linux`. Is there a special process for it?

Right now, I am replicating the installation process in a shell, but I am not obtaining the expected hash for Linux (I do not have a proper way to tested for MacOS).

```
nix-shell -p coursier
> wget https://github.com/scalacenter/bloop/releases/download/v1.4.4/bloop-coursier.json
> coursier install --install-dir out --install-platform x86_64-pc-linux --default-channels=true --channel bloop-coursier.json --only-prebuilt=true bloop
> sed -i '5,$ d' out/bloop
> nix-hash --type sha256 --flat --base32 out/bloop
```

But the result using the `hash` from that is giving me:
```
hash mismatch in fixed-output derivation '/nix/store/d46jblh435xy9r21vvn27j5xa29vr45b-bloop-coursier-1.4.4':
  wanted: sha256:0hggdqjx95bzc3s90aspcb89i51wz17cbn29jx9ndhm18x0ymja1
  got:    sha256:0hf0priy93zqba78a9nvbgl3mzwlc4jz43gz7cv2cdkj6x0lp0y1
```

**Comment by jonringer** [comment]
there should be 5 hash changes, as it pulls down many different srcs

**Comment by JesusMtnez** [comment]
I think I have finally found the problem. I was doing the hash for `out/bloop` instead of the hole `out` directory.

Using `nix-hash --type sha256 --base32 out/` calculated the proper hash. I do not have an OSX machine to test though.

**Comment by jonringer** [comment]
~~what i meant is that the other shell completions need to be bumped as well, otherwise they will fail~~

seems that the contents of the shell completion scripts didnt actually change

**Review by jonringer — APPROVED** [review]
LGTM
shows usage

```
https://github.com/NixOS/nixpkgs/pull/96953
1 package built:
bloop
```

**Comment by jonringer** [comment]
@GrahamcOfBorg build bloop

**Comment by Tomahna** [comment]
Tested on nixos, LGTM.

**Pull request merged**
