### PR TITLE
racket: on darwin, use libiconv

### LINKED ISSUE #34576: darwin: racket broken since 6.10 introduced back in August
## Issue description

racket does not build on MacOS. I git-bisected, and the commit that introduced the issue is:

`8dc06a23856292fc148d430b1cc88c723aa8b639`
`Sat Aug 26 18:35:40 2017 +0200`
`racket: 6.9 -> 6.10`

The error looks different now from how it looked back then. Back then it passed `configure` and later got a link error. Now it fails already in `configure`.

### Steps to reproduce

```
$ nix-build -A racket '<nixpkgs>'
[ . . . ]
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/private/tmp/nix-build-racket-6.11.drv-1/racket-6.11/src/build':
configure: error: C compiler cannot create executables
See `config.log' for more details
builder for ‘/nix/store/sasd6rvr4zx22xg0zd5wfpydymcxf2l4-racket-6.11.drv’ failed with exit code 77
error: build of ‘/nix/store/sasd6rvr4zx22xg0zd5wfpydymcxf2l4-racket-6.11.drv’ failed```
```

config.log:

```
[ . . . ]
configure:3680: checking whether the C compiler works
configure:3702: gcc    conftest.c  >&5
/nix/store/pk7pbzir6kxwzqb4n5wasqjs9fvl1nx9-gcc-wrapper-7.2.0/bin/as: assembler (clang) not installed
configure:3706: $? = 1
configure:3744: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define USE_SINGLE_FLOATS 1
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
[ . . . ]
```

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 16.7.0, macOS 10.12.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(clacke): `"nixpkgs-18.03pre126020.931a0b8be80"`
 - nixpkgs: `/Users/clacke/.nix-defexpr/channels/nixpkgs`

### PR DESCRIPTION
**Pull request by clacke**
Without libiconv, racket doesn't support UTF-16, and this breaks one
of the tests.

Closes #34576

###### Motivation for this change

Make racket build on Darwin.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [] NixOS
   - [✓] macOS
   - [✓] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [✓] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [✓] Tested execution of all binary files (usually in `./result/bin/`)
- [✓] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

The binaries that require `libX11.6.dylib` in the library path for dynamic loading don't run, but I think that's in scope for another commit.

On Linux side this commit introduces zero change to derivations.

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build racket racket-minima

**Comment by Mic92** [comment]
@GrahamcOfBorg build racket racket-minimal

**Comment by clacke** [comment]
Guess I'll try it in sandbox.

**Comment by clacke** [comment]
Oh. What do I do to fix this? I set `build-use-sandbox = relaxed` and reloaded the nix-daemon service, and now I'm getting:

```
building path(s) ‘/nix/store/cs447fnh7r560wgqrsc6qxdpg648cmm9-racket-6.12’
/nix/store/0igxxngigjgfkgg3cw547n92b8bpg6b1-stdenv-darwin/setup: fork: Operation not permitted
```

https://github.com/NixOS/nix/issues/759 seems to say this is a problem that was fixed two years ago. Has it come back or am I doing something wrong?

It may be relevant that `nix-info -m` claims  `- multi-user?: no` when I'm running with `sandbox = relaxed`? Or is that normal?

**Comment by LnL7** [comment]
Sandboxing requires nix 2.0 and the relaxed mode isn't really supported anymore.

**Comment by clacke** [comment]
Ok! Time to upgrade then.

**Comment by clacke** [comment]
That wasn't a roaring success.

```
configure:3839: ./conftest
dyld: Library not loaded: @rpath/CoreFoundation.framework/Versions/A/CoreFoundation
  Referenced from: /private/tmp/nix-build-racket-6.12.drv-0/racket-6.12/src/build/./conftest
  Reason: no suitable image found.  Did find:
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation: file system sandbox blocked stat()

**Comment by clacke** [comment]
@LnL7 It seems to me that https://github.com/NixOS/nixpkgs/blob/3bae30289c15571d6257472b532b07b43a27b5ff/pkgs/os-specific/darwin/apple-sdk/framework-setup-hook.sh#L38-L42 , activated by https://github.com/NixOS/nixpkgs/blob/3bae30289c15571d6257472b532b07b43a27b5ff/pkgs/os-specific/darwin/apple-sdk/default.nix#L136-L137 , makes sandboxing impossible? Alternatively, sandboxing needs to be opened up to system CF?

Probably https://github.com/NixOS/nixpkgs/blob/3bae30289c15571d6257472b532b07b43a27b5ff/pkgs/os-specific/darwin/apple-sdk/framework-setup-hook.sh#L1-L4 can explain why my first attempt at solving #35452 segfaulted?

**Comment by LnL7** [comment]
Yeah, there are still some problems with sandboxing and frameworks. FYI the darwin builders don't run with sandboxing enabled anymore.

**Comment by Mic92** [comment]
I already noticed it, when `/bin/bash` did not return a failure anymore.

**Comment by clacke** [comment]
Ok. Any suggestions how I can fix this? glib is in the libPath expression, but I noticed that LD_LIBRARY_PATH isn't in the environment when building. And on MacOS maybe we should set DYLD_LIBRARY_PATH instead?

**Comment by LnL7** [comment]
I think that's equivalent. There are also a bunch of other DYLD_* environment variables described in `man dyld` that might help when debugging something like this.

**Comment by sjmackenzie** [comment]
Is this good to go?

**Comment by clacke** [comment]
Re: {DY,}LD_LIBRARY_PATH, I have since learned that Racket has internal variables that ffi looks at, and that these environment variables don't help.

**Comment by sjmackenzie** [comment]
@qknight this is mergable, mind taking a quick review please.

**Comment by Mic92** [comment]
@GrahamcOfBorg build racket racket-minimal

**Pull request merged**
