### PR TITLE
test-driver.py: Share the shared dir between VMs

### PR DESCRIPTION
**Pull request by singron**
This changes the python test driver to match the behavior of the perl
test driver.  I.e. the directory mounted into /tmp/shared should be the
same for all machines.

This probably fixes many tests, but I found this while investigating
failures in nixos/tests/ceph-multi-node.nix.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
@singron confirmed this fixes https://github.com/NixOS/nixpkgs/issues/77378, thanks a lot!

However, `nixosTests.systemd-analyze` now fails. Can you add a fix for it in here, too?

**Comment by flokli** [comment]
Also cc @B4dM4n,  @7c6f434c.

**Comment by flokli** [comment]
In fact, it's the `copy_from_vm` method in `test-driver.py` (which is invoked from that test) that needs to be updated.

**Comment by singron** [comment]
I updated `copy_from_vm`. I think that's the only other method that needs to be updated because it uses `self.shared_dir`.

**Comment by flokli** [comment]
@GrahamcOfBorg build nixosTests.systemd-analyze

**Comment by flokli** [comment]
For some reason github decides this PR is still open, even though it merged it in.

**Pull request closed without merging**
