### PR TITLE
eigenpy: 3.1.1 -> 3.1.2

### PR DESCRIPTION
**Pull request by nim65s**
## Description of changes

ref. https://github.com/stack-of-tasks/eigenpy/releases/tag/v3.1.2

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nim65s** [comment]
Result of `nixpkgs-review pr 266438` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>python310Packages.crocoddyl</li>
    <li>python310Packages.example-robot-data</li>
    <li>python310Packages.hpp-fcl</li>
    <li>python310Packages.pinocchio</li>
    <li>python311Packages.crocoddyl</li>
    <li>python311Packages.example-robot-data</li>
    <li>python311Packages.hpp-fcl</li>
    <li>python311Packages.pinocchio</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python310Packages.eigenpy</li>
    <li>python311Packages.eigenpy</li>
  </ul>
</details>

**Comment by nim65s** [comment]
Result of `nixpkgs-review pr 266438` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python310Packages.crocoddyl</li>
    <li>python311Packages.crocoddyl</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>python310Packages.eigenpy</li>
    <li>python310Packages.example-robot-data</li>
    <li>python310Packages.hpp-fcl</li>
    <li>python310Packages.pinocchio</li>
    <li>python311Packages.eigenpy</li>
    <li>python311Packages.example-robot-data</li>
    <li>python311Packages.hpp-fcl</li>
    <li>python311Packages.pinocchio</li>
  </ul>
</details>

**Comment by nim65s** [comment]
Result of `nixpkgs-review pr 266438` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>python310Packages.crocoddyl</li>
    <li>python310Packages.eigenpy</li>
    <li>python310Packages.example-robot-data</li>
    <li>python310Packages.hpp-fcl</li>
    <li>python310Packages.pinocchio</li>
    <li>python311Packages.crocoddyl</li>
    <li>python311Packages.eigenpy</li>
    <li>python311Packages.example-robot-data</li>
    <li>python311Packages.hpp-fcl</li>
    <li>python311Packages.pinocchio</li>
  </ul>
</details>

**Review by wegank — APPROVED** [review]

**Comment by wegank** [comment]
@ofborg build python311Packages.eigenpy

**Pull request merged**
