### PR TITLE
taskwarrior-tui: 0.10.4 -> 0.13.12

### PR DESCRIPTION
**Pull request by renesat**
###### Motivation for this change

Update package to latest version.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Should it crash like 
```
results/taskwarrior-tui/bin/taskwarrior-tui
                                                                                                                                                                             Backtrace omitted. Run with RUST_BACKTRACE=1 to display it.                                                                                                                   Run with RUST_BACKTRACE=full to include source snippets.
                                                                                                                                                                             The application panicked (crashed).
 called `Result::unwrap()` on an `Err` value: Unable to run `task show`.

 Caused by:
     No such file or directory (os error 2)                                                                                                                                  in src/app.rs, line 211                                                                                                                                                       thread: main
```

when starting without a config on a headless system?

**Comment by renesat** [comment]
> Should it crash like when starting without a config on a headless system?

Maybe the problem is that there is no TaskWarrior in the dependencies. It wasn't available in previous releases, so I decided not to add it.

**Comment by SuperSandro2000** [comment]
If I understand it correctly we should wrap taskwarrior-gui to include taskwarrior.

**Comment by renesat** [comment]
What I mean is that taskwarrior-tui needs a taskwarrior to work.

**Comment by SuperSandro2000** [comment]
You mean a running taskwarrior daemon?

**Comment by renesat** [comment]
> You mean a running taskwarrior daemon?

No. Taskwarrior is only cli app. This is no daemon.

**Comment by bbigras** [comment]
Result of `nixpkgs-review pr 119806` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>taskwarrior-tui</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
> > You mean a running taskwarrior daemon?
> 
> No. Taskwarrior is only cli app. This is no daemon.

Then taskwarrior-tui could be wrapped to include taskwarrior, right?

**Comment by renesat** [comment]
Yes.

**Comment by SuperSandro2000** [comment]
Then we should do that.

**Comment by renesat** [comment]
> Then we should do that.

OK. I add taskwarrior to buildInputs.

**Comment by SuperSandro2000** [comment]
I think we need to do something like https://github.com/NixOS/nixpkgs/blob/caba0b6a233503262879e62de7911b8549dce795/pkgs/applications/audio/clerk/default.nix#L24 otherwise the package will not be in the PATH.

**Comment by renesat** [comment]
> I think we need to do something like
> 
> https://github.com/NixOS/nixpkgs/blob/caba0b6a233503262879e62de7911b8549dce795/pkgs/applications/audio/clerk/default.nix#L24
> otherwise the package will not be in the PATH.

OK. I add taskwarrior to PATH.

**Pull request closed without merging**
