### PR TITLE
bbdb-vcard-export: new package

### PR DESCRIPTION
**Pull request by thomas-morgan**
Emacs extension for exporting BBDB as vCard files.

### CODE REVIEW

**Comment by jagajaga** [comment]
Maybe you will take a look into https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/emacs-packages.nix and add pkg to this?

**Comment by jagajaga** [comment]
Updates?

**Comment by thomas-morgan** [comment]
Thanks for the comment and sorry for the delay.  If I understand correctly `emacs-packages.nix` is for packages in MELPA and `bbdb-vcard-export` is not in MELPA.  But `bbdb-vcard` is, and it can also export vCards (albeit with an incompatible interface).  Should I add that instead?

**Comment by jagajaga** [comment]
I'm not a emacs maintainer..
@gridaphobe can you look at this PR?

**Comment by gridaphobe** [comment]
Sorry @jagajaga @thomas-morgan, I'm out of town for a couple weeks and haven't been on my computer as much as usual.

`emacs-packages.nix` is not strictly for packages that are on MELPA, we just reuse some of MELPA's infrastructure to build `package.el`-compatible packages.

I think the goal is to eventually move the standalone emacs packages (i.e. in `pkgs/applications/editors/emacs-modes`) to `emacs-packages.nix`. Here's how I would restructure your package for inclusion in `emacs-packages.nix`

```
bbdb-vcard-export = melpaBuild rec {
  pname = "bbdb-vcard-export";
  version = <date of commit>;
  src = fetchgit {
    url = "https://github.com/emacsmirror/bbdb-vcard-export.git";
    rev = "1e16ccbc1d070eac861886ef4b5a5643ec24fe74";
    sha256 = "1z6kn54gzx43wjv5vsm4bqd2zn86w5zxy59j2nqrgfi5wfz5pnd1";
  };

  packageRequires = [ bbdb ]; # emacs is added by default

  meta = {
    description = "Export BBDB as vCard files";
    homepage = http://www.emacswiki.org/emacs/bbdb-vcard-export.el;
    license = stdenv.lib.licenses.gpl2Plus;
  };
}
```

**Comment by nbp** [comment]
@gridaphobe How should we proceed next with this pull request?

**Comment by gridaphobe** [comment]
I think some people are still using the emacs-modes packages, so I don't have a problem with merging this as is. We should probably come up with a strategy for consolidating the two package sets though.

**Comment by ttuegel** [comment]
We have `bbdb-vcard` from MELPA. If `bbdb-vcard-export` is also needed, it should be added to `emacsPackagesNg` instead.

**Pull request closed without merging**
