### PR TITLE
tautulli/plexpy: 1.4.25 -> 2.1.26 (renamed)

### PR DESCRIPTION
**Pull request by bachp**
PlexPy was renamed to Tautulli.

This renames the module as well as the application accordingly.
Aliases are kept for backwards compatibility.

###### Motivation for this change

Update to latest version of Tautulli

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by csingley** [comment]
Nice one, thanks.  Looks good!

**Comment by csingley** [comment]
@bachp 
See [ecbe7b0](https://github.com/NixOS/nixpkgs/commit/ecbe7b06dcc3aacf53f940064d357290770987e1)
Please incorporate those changes (using `systemd.tmpfiles.rules` instead of `systemd.services.tautulli.preStart` and `systemd.services.tautulli.serviceConfig.PermissionsStartOnly`), so we can get a solid package committed without any deprecated functionality.

Thanks again for bringing this up to date.

**Comment by bachp** [comment]
@csingley I rebased this on top of @aanderse s commit

**Comment by csingley** [comment]
Looks like a winner!

**Comment by bachp** [comment]
@Infinisil anything else that needs to be changed here?

**Comment by Infinisil** [comment]
Looking good thanks :)

**Pull request merged**
