### PR TITLE
codimd: 1.2.0 -> 1.4.0, repackage with yarn2nix

### PR DESCRIPTION
**Pull request by WilliButz**
(updated)

In this PR `yarn2nix` is used as a replacement for `node2nix` to package codimd, which significantly reduces the complexity of the package definition, thus reducing the overhead of package updates.

CodiMD is now packaged with nodejs-10_x.

To avoid the implication of being the only yarn2nix, I added [moretea/yarn2nix](https://github.com/moretea/yarn2nix) as `yarn2nix-moretea`. The source is simply copied to nixpkgs so that hydra is able to build packages using mkYarnPackage.

- [x] tested on x86_64-linux and aarch64-linux

### CODE REVIEW

**Comment by Ma27** [comment]
Awesome! I didn't have a detailed look at this (yet), but that looks much simpler than our previous hackery :)

**Comment by WilliButz** [comment]
Seems like this does in fact not work with hydra, I'll rework this accordingly :confused:

**Comment by WilliButz** [comment]
Now using the most recent version of yarn2nix with hydra support and also rebased on master.

@GrahamcOfBorg test codimd

**Review by Ma27 — APPROVED** [review]
As the change drastically simplifies the complexity of the `codimd`-package itself, I'm all in favor of it :+1:

However I guess that we should get feedback from some more folks that were involved in NPM packaging in the past regarding the (re)introduction of yarn2ni x:)

**Comment by globin** [comment]
@GrahamcOfBorg test codimd

**Pull request merged**
