### PR TITLE
julia_15: run test suite and mark as broken

### LINKED ISSUE #121101: julia_15: failures in the official test suite
**Describe the bug**
The julia_15 derivation does not pass the official julia test suite, including a number of BLAS errors where numerical results are incorrect.

This bug report is a followup to https://github.com/NixOS/nixpkgs/pull/117881 and in particular https://github.com/NixOS/nixpkgs/pull/117881#issuecomment-828835929.

**To Reproduce**
This bug seems to only manifest on certain hardware configurations. All of the results I'm presenting were run on an AWS c5.2xlarge instance running NixOS 20.09.3301.42809feaa9f (Nightingale).

1. `nix-build -A julia_15` in the nixpkgs repository.
2. ``` result/bin/julia --check-bounds=yes --startup-file=no --depwarn=error `result/bin/julia -e 'println(joinpath(Sys.BINDIR, Base.DATAROOTDIR, "julia/test/runtests.jl"))'` ```
3. Observe test failures.

**Expected behavior**
The test suite to pass.

**Screenshots**
n/a

**Additional context**
We know that the patched official binaries from julia upstream do not have the same test failures, so this appears to be an issue with nixpkgs version of `blas` or that the julia-custom BLAS patches are relevant and that we should be using their vendored blas in the build process. 

As I proposed in https://github.com/NixOS/nixpkgs/pull/117881#issuecomment-828835929, I think we should add the test suite to run in the `julia_15` derivation and then either mark it as broken or find a fix. Of course we can mark as broken and then always find a fix later and update it.

**Notify maintainers**

@raskin @rob @garrison

other interested parties: @ninjin @7c6f434c 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.100, NixOS, 20.09.3301.42809feaa9f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3301.42809feaa9f, nix-ld"`
 - channels(skainswo): `"home-manager-20.09, nixpkgs-unstable-21.05pre282548.4c87cb87a2d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: julia_15
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by samuela**
Fixes https://github.com/NixOS/nixpkgs/issues/121101.

###### Motivation for this change
https://github.com/NixOS/nixpkgs/issues/121101

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 7c6f434c** [comment]
Somewhat against that as someone who uses Julia for non-numeric stuff. On the other hand, if 1.6 works strictly better everywhere and 21.05 branch-off is close, maybe we should simply _drop_ 1.5

**Comment by samuela** [comment]
> Somewhat against that as someone who uses Julia for non-numeric stuff. On the other hand, if 1.6 works strictly better everywhere and 21.05 branch-off is close, maybe we should simply _drop_ 1.5

I hear that, and marking as broken does inconvenience some users. Although I think it is worth noting that julia is primarily designed to be a numerical computing language, the likes of matlab, python/numpy, etc. So a considerable chunk of the user base will be using it for those purposes, myself included. Finding pernicious floating point bugs in your code is a really really bad time. For me personally it could mean having to retract academic papers.

I'm all for killing off 1.5 though as you suggest though. I don't think there will be too much reason to keep it around once 1.6 lands.

**Comment by 7c6f434c** [comment]
>I'm all for killing off 1.5 though as you suggest though. I don't think there will be too much reason to keep it around once 1.6 lands.

… which I think has landed in the branch, if not in the channel

**Comment by samuela** [comment]
Not quite yet, iiuc @ninjin will be making that happen in a forthcoming PR.

**Comment by ninjin** [comment]
On Thu 29 Apr 2021, Samuel Ainsworth wrote:
> 
> Not quite yet, iiuc @ninjin will be making that happen in a forthcoming PR. 

Yes, needs some mild polishing: regular expressions into patches and removal of cusses.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by ninjin** [comment]
On Thu 29 Apr 2021, ninjin wrote:
> 
> On Thu 29 Apr 2021, Samuel Ainsworth wrote:
> > 
> > Not quite yet, iiuc @ninjin will be making that happen in a forthcoming PR. 
> 
> Yes, needs some mild polishing: regular expressions into patches and removal of cusses.

All right, binary packages for v1.0.5 and v1.6.1 are now in a PR [1].

[1]: https://github.com/NixOS/nixpkgs/pull/123188

The 21.05 feature freeze is now five days away [2], so I guess we need a decision here. Personally, barring a working v1.6.x expression that builds from source (which I deem highly unlikely any time soon) I do think it makes sense to keep `julia_15` around. But, with tests disabled as it otherwise will not build and marked as broken so that the user can explicitly enable it if desired. Thoughts?

[2]: https://github.com/NixOS/nixpkgs/issues/121972

**Comment by samuela** [comment]
@ninjin Yeah, I think that all makes sense. IMHO either we should remove julia_15 or mark it as broken.

**Comment by ninjin** [comment]
On Sun 16 May 2021, Samuel Ainsworth wrote:
> 
> @ninjin Yeah, I think that all makes sense. IMHO either we should remove julia_15 or mark it as broken.

Agreed. Could you add a comment above `broken = true;` stating that it fails to pass its test suite? I guess also throw in a rebase while you are at it.

Other than that this is good to merge in my book and should really be so before #121972 hits is three days.

**Comment by samuela** [comment]
> Agreed. Could you add a comment above `broken = true;` stating that it fails to pass its test suite? I guess also throw in a rebase while you are at it. Other than that this is good to merge in my book and should really be so before #121972 hits is three days.

Roger that, done in https://github.com/NixOS/nixpkgs/pull/121114/commits/1e7f3bf0beae3c6fe916cc0a3e74391d79f98789.

**Comment by SuperSandro2000** [comment]
> The 21.05 feature freeze is now five days away [2]

We can always backport stuff.

**Comment by ninjin** [comment]
On Tue 18 May 2021, Samuel Ainsworth wrote:
> 
> > Agreed. Could you add a comment above `broken = true;` stating that it fails to pass its test suite? I guess also throw in a rebase while you are at it. Other than that this is good to merge in my book and should really be so before #121972 hits is three days.
> 
> Roger that, done in https://github.com/NixOS/nixpkgs/pull/121114/commits/1e7f3bf0beae3c6fe916cc0a3e74391d79f98789.

Super! I would squash them into a single commit, but frankly that could be a bit pedantic. Good to merge from my perspective.

**Pull request merged**
