### PR TITLE
haskellPackages: update stackage and hackage

### PR DESCRIPTION
**Pull request by maralorn**
### This Merge

This PR is the regular merge of the `haskell-updates` branch into `master`.

This branch is being continually built and tested by hydra at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates. You may be able to find an up-to-date Hydra build report at [cdepillabout/nix-haskell-updates-status](https://github.com/cdepillabout/nix-haskell-updates-status).

We roughly aim to merge these `haskell-updates` PRs at least once every two weeks. See the @NixOS/haskell [team calendar](https://cloud.maralorn.de/apps/calendar/p/Mw5WLnzsP7fC4Zky) for who is currently in charge of this branch.

### haskellPackages Workflow Summary

Our workflow is currently described in [`pkgs/development/haskell-modules/HACKING.md`](https://github.com/NixOS/nixpkgs/blob/haskell-updates/pkgs/development/haskell-modules/HACKING.md).

The short version is this:
* We regularly update the Stackage and Hackage pins on `haskell-updates` (normally at the beginning of a merge window).
* The community fixes builds of Haskell packages on that branch.
* We aim at at least one merge of `haskell-updates` into `master` every two weeks.
* We only do the merge if the [`mergeable`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/mergeable) job is succeeding on hydra.
* If a [`maintained`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/maintained) package is still broken at the time of merge, we will only merge if the maintainer has been pinged 7 days in advance. (If you care about a Haskell package, become a maintainer!)

---

This is the follow-up to #160733. Come to [#haskell:nixos.org](https://matrix.to/#/#haskell:nixos.org) if you have any questions.

### CODE REVIEW

**Comment by roberth** [comment]
Maybe https://github.com/NixOS/nixpkgs/pull/166571 and  https://github.com/NixOS/nixpkgs/pull/166548 could be merged simultaneously to save a bit on mass-rebuilds.

**Comment by sternenseemann** [comment]
> Maybe #166571 and #166548 could be merged simultaneously to save a bit on mass-rebuilds.

Yeah, I was thinking that, too, maybe we'll even be able to combine this with the upcoming `zlib`-related `stdenv` rebuild, so we'd get 3 changes done in one rebuild.

**Comment by roberth** [comment]
> so we'd get 3 changes done in one rebuild.

Not sure if this is practical without merging into staging-next. Otherwise, you'd have to inhibit builds on master, which seems tricky and requires a timely merge of haskell-updates. Maybe we'd better keep it simple, but it's your call, as you have experience running `haskell-updates`.

**Comment by sternenseemann** [comment]
Well eventually the `zlib` change is going to land in master which is when we'll have to do a set rebuild in `haskell-updates` (unless we want to cause the rebuild on `master`), so we could do it a that point. Another option could of course be merging `staging-next` into `haskell-updates` and then waiting for that to be merged — never tried that before and not sure if it's wise.

**Pull request merged**
