### PR TITLE
Update vim-plugin-names

### PR DESCRIPTION
**Pull request by luochen1990**
###### Motivation for this change

Add more vim plugins

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
do you mind running the `update.py`, it should make a commit with changed to the generated.nix

**Comment by luochen1990** [comment]
I find it not as easy as I think, since there are many errors like
```
downloading 'https://github.com/xxx' HTTP Error 429: too many requests, Retrying in 12 seconds...
```
Seems that my requests are limited by github  :(

I'll try it again latter..

**Comment by luochen1990** [comment]
@jonringer found the doc about `GITHUB_API_TOKEN`, and it's done now :)

**Comment by jonringer** [comment]
looks like someone else ran the script in the mean time, do you mind doing:

```
git reset HEAD^^ # undo 2 commits
git checkout .       # remove old changes
./pkgs/misc/vim-plugins/update.py --add luochen1990/indent-detector.vim
./pkgs/misc/vim-plugins/update.py --add luochen1990/select-and-search
```

That should create a git commit history which is able to be merged

**Comment by luochen1990** [comment]
@jonringer Thanks for your detailed help very much!  I rebased to staging and re-run the update.py script again, and there is no conflict now.

**Comment by jonringer** [comment]
If you want to take a look at #158880, that's what the git history should look like

**Comment by luochen1990** [comment]
@jonringer Thanks, I got it that you want a clean & orthorhombic commit history,   it is done now, would you please have a review again?

**Comment by jonringer** [comment]
you can probably drop the generated commit, looks like someone else merged

 `git rebase -i` is a powerful command which achieves this, I created a small video demonstrating it's use [here](https://www.youtube.com/watch?v=OR8Q-4PLalc). A more indepth text tutorial can be found [here](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase)

**Comment by luochen1990** [comment]
@jonringer Done againt, finally no conflict now.

**Pull request closed without merging**
