### PR TITLE
inboxer: 1.2.1 -> 1.3.2

### PR DESCRIPTION
**Pull request by mgttlinger**
Fixes missing gtk3 dependency and closes #103878 because this updates
directly to the last version.

###### Motivation for this change

Dependency on gtk3 was missing even from previous versions of the package.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mgttlinger** [comment]
Made a stupid mistake... Fix imminent...

**Comment by mgttlinger** [comment]
I went via AppImage to ensure the package will work in future releases as well given that the package itself is archived upstream and will not have any further releases.

**Comment by FRidh** [comment]
> As you know Google is going to take down Inbox service.

> This project is not maintained anymore. Since Inbox is closed this project has to be closed as well. It just cannot operate normally without Inbox.

I think we should remove it instead.

**Comment by mgttlinger** [comment]
> I think we should remove it instead.

What is the benefit of that? The Program itself warns the user that it now uses gmail instead of inbox and the package will not have further maintenance effort, right?

**Comment by SuperSandro2000** [comment]
> This project is not maintained anymore. This project doesn't implement Inbox desktop experience, it just used to use Inbox web version packaged as a desktop app. Since Inbox is closed this project has to be closed as well. It just cannot operate normally without Inbox.

See https://github.com/denysdovhan/inboxer/issues/101

> What is the benefit of that? 

It keeps nixpkgs clean of packages which definitely are not going to work cause they are broken.

> The program itself warns the user that it now uses gmail instead of inbox and the package will not have further maintenance effort, right?

The project was about using Inbox as a desktop program which it can't do anymore. It would only make sense to remove it.

**Comment by SuperSandro2000** [comment]
Superseded by #105613

**Pull request closed without merging**
