### PR TITLE
kcl: 0.10.0 -> 0.10.9

### PR DESCRIPTION
**Pull request by superherointj**
kcl: 0.10.0 -> 0.10.7

Release: https://github.com/kcl-lang/cli/releases/tag/v0.10.7

- unpin go version
- order by phases/alphabetical order
- add `meta.changelog`
- remove nested `with` in meta
- add partial fix for cross-compiling
- mark cross-compiling as broken
- replace `lib.optional` (single item) with `lib.optionals` (multiple items)
- add nix update script
- refactor install shell completion
- nixfmt

Note: Tried to add a version test but had issues, will consider another time.

CC @selfuryon @peefy

## Status

This PR is ready for review/merge.

### CODE REVIEW

**Comment by selfuryon** [comment]
@superherointj As far as I know everything should be formatted by `nixpkgs-fmt` tool

**Comment by superherointj** [comment]
> @superherointj As far as I know everything should be formatted by `nixpkgs-fmt` tool

Contributing says differently (it's `nixfmt`):
https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#syntax

But I know nothing. No matter what I know, I'm wrong. I don't know. I have done what you asked for.

**Comment by superherointj** [comment]
https://github.com/kcl-lang/cli/releases/tag/v0.10.9

**Comment by superherointj** [comment]
@selfuryon Please, point out your reasoning for use of `nixpkgs-fmt` instead of `nixfmt`.

**Comment by superherointj** [comment]
@jljox Please review.

**Review by jljox — APPROVED** [review]
Looks good to me.

**Comment by superherointj** [comment]
Review @Aleksanaa ? (Question)

**Review by ulrikstrid — APPROVED** [review]

**Pull request merged**
