### PR TITLE
renoise: fix the file name and the hash

### PR DESCRIPTION
**Pull request by fps**
But only for the registered 3.0.1 version. Scratching my own itches ;)

### CODE REVIEW

**Comment by fps** [comment]
Tested locally as I'm pretty sure travis can't pull the file for registered users, so the automated test will fail.

**Comment by mrVanDalo** [comment]
Well the hash for registered binaries will never be the same, because when you download a registered version it is signed for you only (your name is in there!). This is why I can't install renoise myself.

**Comment by mrVanDalo** [comment]
I had to do this to fix the sha sum 
```
  nixpkgs.config = {
     packageOverrides = pkgs:
     { renoise = (pkgs.lib.overrideDerivation pkgs.renoise ( attrs: {
         src = pkgs.requireFile {
	   url = "";
	   name = "rns_3_0_1_linux_x86_64.tar.gz";
	   sha256 = "736f0c6f16fefdf26cc8d2dbafe69e0f6db09046acbe4d3fd63d53e04fbf386f";
	 };
       }
      ));
  };
    allowUnfree = true;
  };
```

**Comment by fps** [comment]
True. I'd say: Let's only keep the demo version in the package. For this precise reason.

**Comment by mrVanDalo** [comment]
How about create packages
renoise_3.0.1
renoise_3.0.1_demo
renoise_3.1_beta_4 (i will do this today)

and except for the demo version we make the sha sum a parameter, so we can use the better readable override parameter syntax ?

**Comment by fps** [comment]
Sure, go ahead :) I have moved on to GuixSD since hacking on this package. So feel free :)

**Comment by mrVanDalo** [comment]
@fps please have a look at https://github.com/NixOS/nixpkgs/pull/11363

**Pull request merged**
