### PR TITLE
go: add version 1.7 [WIP]

### PR DESCRIPTION
**Pull request by edef1c**
TODO: figure out if godoc will end up in the right place

Currently stuck on

```
misc/cgo/testcarchive
--- FAIL: TestExtar (1.42s)
    carchive_test.go:478: # libgo4
        /nix/store/6gkzwcp486ay95m4am846kpcj2vj05l3-go-1.7/share/go/pkg/tool/linux_amd64/link: running /nix/store/6gkzwcp486ay95m4am846kpcj2vj05l3-go-1.7/share/go/misc/cgo/testcarchive/testar failed: fork/exec /nix/store/6gkzwcp486ay95m4am846kpcj2vj05l3-go-1.7/share/go/misc/cgo/testcarchive/testar: no such file or directory

    carchive_test.go:479: exit status 2
```

going to work on this more tomorrow, bedtime rn

### CODE REVIEW

**Comment by avnik** [comment]
@nathan7 looks like I fix it in #17805

**Comment by nathan7** [comment]
sorry, I kinda dropped the ball on this one — what'd you change specifically, @avnik?

**Comment by avnik** [comment]
@nathan7 actually I do my own from scratch ;) https://github.com/NixOS/nixpkgs/pull/17805/files#diff-8b69266ad55fc928935ddca9ea548397R52 actually ;)

**Comment by rushmorem** [comment]
@nathan7 I would like to propose closing this in favour of @avnik's https://github.com/NixOS/nixpkgs/pull/17805 since that one already builds fine. Is that OK with you?

**Comment by nathan7** [comment]
@rushmore sure thing.

**Pull request closed without merging**
