### PR TITLE
pypy: 2.6.0 -> 4.0.0

### PR DESCRIPTION
**Pull request by bendlas**

### CODE REVIEW

**Comment by domenkozar** [comment]
Did you try to build it?

**Comment by bendlas** [comment]
Yeah, I built it and then built a version of https://github.com/pixie-lang/pixie with it. No other tests.

**Comment by domenkozar** [comment]
Could you make a PR against `buildPythonPackage+wheels` branch and I'll test it as part of wheels refactoring?

**Comment by bendlas** [comment]
The update currently applies cleanly to `buildPythonPackage+wheels`. You can use the following commands:

```
git fetch https://github.com/bendlas/nixpkgs.git update-pypy
git cherry-pick FETCH_HEAD
```

**Comment by domenkozar** [comment]
Thanks, pushed. I'll ship that as part of https://github.com/NixOS/nixpkgs/pull/11086

**Pull request closed without merging**
