### PR TITLE
sundials: 4.1.0 -> 5.0.0

### PR DESCRIPTION
**Pull request by smaret**
##### Motivation for this change

Update sundials to the latest upstream.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @flokli  @idontgetoutmuch

### CODE REVIEW

**Comment by smaret** [comment]
`nix-review pr` succeeds on both macOS and Linux (Debian).

**Comment by flokli** [comment]
scikits-odes 2.5.0 was released, which should work with sundials 4.1.

There were plans on removing `pkgs/development/libraries/sundials/3.x.nix`, meaning this would bump sundials for scikits-odes, too.
@idontgetoutmuch did you check if scikits-odes builds with sundials 5.x, too?

**Comment by flokli** [comment]
Anyways, this shouldn't block this PR.

**Comment by flokli** [comment]
@GrahamcOfBorg build sundials

**Comment by idontgetoutmuch** [comment]
> scikits-odes 2.5.0 was released, which should work with sundials 4.1.
> 
> There were plans on removing `pkgs/development/libraries/sundials/3.x.nix`, meaning this would bump sundials for scikits-odes, too.
> @idontgetoutmuch did you check if scikits-odes builds with sundials 5.x, too?

Yes it builds but they seem to have released

```
https://computing.llnl.gov/projects/sundials/download/sundials-5.0.0-dev.2.tar.gz
https://computing.llnl.gov/projects/sundials/download/sundials-5.0.0-dev.1.tar.gz
https://computing.llnl.gov/projects/sundials/download/sundials-5.0.0-dev.0.tar.gz
```

I validated `dev.2`. I can submit a PR to `nixpkgs` for `sundials` but should we wait until they release a final version? TBH it's not much work so I'll submit a PR which can be rejected if people want to wait.

**Comment by idontgetoutmuch** [comment]
Oh my bad - let me check the non-dev version.

**Comment by idontgetoutmuch** [comment]
That works but you already knew that ;-)

**Comment by idontgetoutmuch** [comment]
> scikits-odes 2.5.0 was released, which should work with sundials 4.1.
> 
> There were plans on removing `pkgs/development/libraries/sundials/3.x.nix`, meaning this would bump sundials for scikits-odes, too.
> @idontgetoutmuch did you check if scikits-odes builds with sundials 5.x, too?

It does *not* build with sundials 5.0 - the maintainer(s) of scikits-odes will need to do something as the directory structure / naming conventions have changed.

**Pull request merged**
