### PR TITLE
qt5.qtbase: switch to overrideSDK

### PR DESCRIPTION
**Pull request by reckenrode**
## Description of changes

Fixes staging-next build failure on x86_64-darwin: https://hydra.nixos.org/build/239500595. #263535

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wegank** [comment]
@ofborg build qt5.qtbase

**Comment by wegank** [comment]
The fix doesn't really work on my side, probably my env is too impure. I'll see what ofborg comes up with.

**Comment by reckenrode** [comment]
It’s not building for me either, which is odd because it built locally.

**Comment by reckenrode** [comment]
Oh, right. I neglected to cherry-pick the commit that recursively updates the propagated build inputs. 🤪

**Comment by reckenrode** [comment]
`nix build 'github:NixOS/nixpkgs?ref=pull/263878/head#qt5.qtbase' --system x86_64-darwin` succeeds for me now. I also dropped the part that switched to unversioned SDK references because it was causing ofborg-eval to fail.

**Comment by wegank** [comment]
Emmm, `qt5.qttranslations` does not evaluate now.

**Comment by reckenrode** [comment]
> Emmm, `qt5.qttranslations` does not evaluate now.

I’ve looked at this a bit, but I won’t have time to look at it in depth until later today. The `nativeBuildInputs` thing is odd because `overrideSDK` doesn’t touch it.

(I’ll run ofborg’s `outPath.nix` before I push any updates, so this should be the last eval error from this PR.)

**Comment by reckenrode** [comment]
I cleaned up the comments and added a check for null packages. I don’t know how that happens, but doing so fixes evaluation of qt5.qttranslations and allowed the eval check to run and pass locally.

**Comment by reckenrode** [comment]
I fixed the conflict after #264497 was merged.

**Pull request merged**
