### PR TITLE
treewide: make shell.nix files not use top-level `with` statement

### PR DESCRIPTION
**Pull request by philiptaron**
- #208242
## Description of changes

This is a very boring PR.

- [x] Make all `shell.nix` instances that used a with at the top level not do that.

## Things done

- [x] Ran `nix-shell` in the following directories on `x86_64-linux`:
  - [x] `maintainers/scripts/convert-to-import-cargo-lock` (@winterqt)
  - [x] `pkgs/tools/security/metasploit` (@Mic92, @zowoq)
  - [x] `pkgs/development/tools/misc/travis` (@Mic92)
  - [x] `nixos/maintainers/scripts/azure-new` (@colemickens)
  - [x] `nixos/lib/test-driver` (@Mic92)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fricklerhandwerk** [comment]
This will work for `nix-shell` and `nix-build` due to their "autocall" semantics, but will break setups where people import `shell.nix` from some other expression. @philiptaron please find and ask maintainers who use this whether this change is okay.

**Comment by philiptaron** [comment]
I didn't see any imports, leading me to believe that this was used for `nix-shell` usage in the directory only.

I've updated the PR headmatter with my best attempt to find maintainers.

**Comment by fricklerhandwerk** [comment]
Maintainers may import this from their own environments! Those expressions produce derivations, you could have them in your local development environment.

**Comment by philiptaron** [comment]
Understood. The maintainers are on the review.

**Review by JohnRTitor — APPROVED** [review]
Changes looks good, but I'd rather get someone more familiar with these scripts/or a maintainer to review these

**Pull request merged**
