### PR TITLE
python3Packages.pyparsing: 2.4.6 -> 2.4.7

### PR DESCRIPTION
**Pull request by kini**
###### Motivation for this change

Bump to the latest version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by prusnak — CHANGES_REQUESTED** [review]
1. Please change the commit message to `python3Packages.pyparsing`

2. Please target `staging` branch as this causes a massive rebuild.

**Comment by kini** [comment]
> 1. Please change the commit message to `python3Packages.pyparsing`
> 2. Please target `staging` branch as this causes a massive rebuild.

Done. Sorry for the noise @ other maintainers who were pinged while I was switching target branches.

**Comment by SuperSandro2000** [comment]
> > 1. Please change the commit message to `python3Packages.pyparsing`
> > 2. Please target `staging` branch as this causes a massive rebuild.
> 
> Done. Sorry for the noise @ other maintainers who were pinged while I was switching target branches.

Known issue. A fix for this is in the making.

**Review by prusnak — APPROVED** [review]

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by jonringer** [comment]
@GrahamcOfBorg build python3Packages.requests

**Review by jonringer — APPROVED** [review]

**Comment by kini** [comment]
> @GrahamcOfBorg build python3Packages.requests

Did you perhaps mean this to be python3Packages.pyparsing, or am I missing something?

**Comment by prusnak** [comment]
> Did you perhaps mean this to be python3Packages.pyparsing, or am I missing something?

I guess requests has pyparsing as its dependency, so Jonathan wants to check whether it still builds

**Comment by jonringer** [comment]
yea, a successful requests build means that sphnix, pytest, and a few other critical libraries all work. Usually doesn't take too long, but looks like staging just had the gcc10 changes applied, so it has to rebuild from stdenv

**Pull request merged**
