### PR TITLE
knot-dns: 3.2.9 -> 3.3.0

### PR DESCRIPTION
**Pull request by vcunat**
https://gitlab.nic.cz/knot/knot-dns/-/releases/v3.3.0

I'd like for people interested in knot-dns to also glance at
https://github.com/NixOS/nixpkgs/pull/81460

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
@ofBorg build knot-dns.passthru.tests
I'm quite sure that the x86_64-linux error is not genuine; I did try all this locally before creating the PR.

**Comment by vcunat** [comment]
3.2 branch remains supported upstream, roughly for another year, so I think it's best to keep `release-23.05` on 3.2.x

**Comment by mweinelt** [comment]
> I'd like for people interested in knot-dns to also glance at
> https://github.com/NixOS/nixpkgs/pull/81460

Already running it in a production environment. Looks and feels good.

**Review by mweinelt — APPROVED** [review]
Passthru tests for ngtcp2-gnutls and knot-dns are looking fine on aarch64-linux and x86_64-linux.

**Pull request merged**
