### PR TITLE
dask: 2.2.0 -> 2.5.2, distributed: 2.4.0 -> 2.5.2, dask-ml: 0.11.0 -> 1.0.0, dask-jobqueue: 0.4.1 -> 0.7.0

### PR DESCRIPTION
**Pull request by francescocarzaniga**
###### Motivation for this change

Dask and relative packages were quite outdated.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @FRidh @costrouc

### CODE REVIEW

**Comment by teh** [comment]
Thanks for the changes! Would you mind splitting out each update to its own commit? That makes it easier for tooling that uses the commit format, and also to selectively back out if something goes wrong.

**Comment by francescocarzaniga** [comment]
@teh No problem, there are now four commits.

**Comment by teh** [comment]
apologies, one more commit style change suggestion: `distributed: 2.4.0->2.5.2` to `distributed: 2.4.0 -> 2.5.2` (check the git commit log of nixpkgs for other examples). LGTM otherwise, thanks!

**Review by teh — APPROVED** [review]

**Review by costrouc — APPROVED** [review]

**Comment by FRidh** [comment]
@GrahamcOfBorg build python3.pkgs.dask python3.pkgs.distributed python3.pkgs.dask-ml python3.pkgs.dask-jobqueue

**Comment by FRidh** [comment]
> apologies, one more commit style change suggestion: `distributed: 2.4.0->2.5.2` to `distributed: 2.4.0 -> 2.5.2` (check the git commit log of nixpkgs for other examples). LGTM otherwise, thanks!

Even better, prefix with the package set so it is an actual attribute path. That way the bot can pick it up.

**Comment by francescocarzaniga** [comment]
So what do I have to do to get these packages updated? It's been ten days and I see that dask has already been replaced in master.

**Comment by teh** [comment]
@francescocarzaniga I think roughly:

1. resolve conflict 
2. prefix packages e.g. `pythonPackages.dask-ml`
3. ping @FRidh to merge

**Comment by FRidh** [comment]
Nothing happening so closing.

**Pull request closed without merging**
