### PR TITLE
Add the google-cloud-sdk package

### PR DESCRIPTION
**Pull request by stephenmw**

### CODE REVIEW

**Comment by cstrahan** [comment]
This looks pretty good.

I think there are a couple improvements you can make:

Try moving the `builder.sh` stuff into `default.nix`. Something like:

```nix
  buildPhase = "true";

  installPhase = ''
    mkdir -p "$out"
    tar -xzf "$src" -C "$out" google-cloud-sdk

    # create wrappers with correct env
    for program in gcloud bq gsutil git-credential-gcloud.sh; do
      programPath="$out/google-cloud-sdk/bin/$program"
      wrapper="$out/bin/$program"
      makeWrapper "$programPath" "$wrapper" \
          --set CLOUDSDK_PYTHON "$python27/bin/python" \
          --prefix PYTHONPATH : "$(toPythonPath $crcmod)"
    done

    # install man pages
    mv "$out/google-cloud-sdk/help/man" "$out"

    # setup bash completion
    mkdir -p "$out/etc/bash_completion.d/"
    mv "$out/google-cloud-sdk/completion.bash.inc" "$out/etc/bash_completion.d/gcloud.inc"
  '';
```

Also, I think you're missing gcutil here:

    for program in gcloud bq gsutil git-credential-gcloud.sh; do

**Comment by cstrahan** [comment]
Ok, I think something like this would do (though I haven't tested it yet):

```nix
{stdenv, lib, fetchurl, python27, makeWrapper, crcmod ? null}:

# crcmod improves the performance of gsutil

stdenv.mkDerivation rec {
  version = "0.9.58";
  name = "google-cloud-sdk-${version}";

  src = fetchurl {
    url = "https://dl.google.com/dl/cloudsdk/release/packages/google-cloud-sdk-coretools-linux-static-20150429151447.tar.gz";
    sha256 = "0sak1fmm7z7ry1k2r67a13mpgi55rbnx81s0y0xhd86dm5aw4f48";
  };

  buildInputs = [python27 makeWrapper];

  phases = [ "unpackPhase" "buildPhase" "fixupPhase" ];

  installPhase = ''
    mkdir -p "$out"

    # create wrappers with correct env
    for program in gcloud bq gsutil git-credential-gcloud.sh; do
      programPath="$out/google-cloud-sdk/bin/$program"
      wrapper="$out/bin/$program"
      ${if (crcmod != null) then ''
      extraArgs="--prefix PYTHONPATH : ${crcmod}/${python27.sitePackages}"
      '' else ''
      extraArgs=""
      ''};
      makeWrapper "$programPath" "$wrapper" \
          --set CLOUDSDK_PYTHON "${python27}/bin/python" \
          $extraAgs
    done

    # install man pages
    mv "$out/google-cloud-sdk/help/man" "$out"

    # setup bash completion
    mkdir -p "$out/etc/bash_completion.d/"
    mv "$out/google-cloud-sdk/completion.bash.inc" "$out/etc/bash_completion.d/gcloud.inc"
  '';

  meta = with lib; {
    description = "Tools for the google cloud platform";
    longDescription = "The Google Cloud SDK. This package has the programs: gcloud, gsutil, and bq";
    homepage = "https://cloud.google.com/sdk/";
    maintainers = with maintainers; [stephenmw];
    platforms = platforms.all;
  };
}
```

**Comment by stephenmw** [comment]
I just found out that the package contains Go binaries made for linux 64 bit. I will update platforms and push sometime tonight or tomorrow..

**Comment by stephenmw** [comment]
Please recheck my PR. I made it one file and now execute the fixup phase.

**Comment by viric** [comment]
Can this get a proper meta.license? Someone should review the compliance of licenses, as it seems to include even precompiled binaries.

**Comment by stephenmw** [comment]
I will add a license of "free" and remove all precompiled binaries. They are not used anyways.

**Comment by stephenmw** [comment]
Added a license and removed the mac binaries. It is now pure python/shell.

**Pull request merged**
