### PR TITLE
meson: 0.54.2 → 0.55.0

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
https://mesonbuild.com/Release-notes-for-0-55-0.html
https://github.com/mesonbuild/meson/releases/tag/0.55.0
https://github.com/mesonbuild/meson/compare/0.54.2...0.55.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] built systemd as a test
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
@Ericson2314 this looks like it will be breaking cross: https://mesonbuild.com/Release-notes-for-0-55-0.html#config-tool-based-dependencies-no-longer-search-path-for-cross-compiling

**Comment by Ericson2314** [comment]
@jtojnar true. There might be environmental variables for some of them, though.

**Comment by FRidh** [comment]
status?

**Comment by FRidh** [comment]
status?

**Comment by jtojnar** [comment]
I am not sure about the extent of the breakage. Could we make a hydra jobset for this branch running `release-cross.nix`?

**Comment by Ericson2314** [comment]
I would just merge and hope for the best. We can make the cross file unconditionally contain stuff like 
```
qmake = '${stdenv.cc.hostPrefix}qmake'
```
which I think will work.

**Comment by jtojnar** [comment]
Here is the commit in question: https://github.com/mesonbuild/meson/commit/245d659522fd73857bf7f4e83bd572d9cdcd7469

Here is the list of known dependencies: https://github.com/mesonbuild/meson/blob/24227a95531b21a04bf2514a5b8f61ae29d47043/mesonbuild/dependencies/__init__.py#L41-L89

We care about those that use/extend `ConfigToolDependency` class, which is quite a few. Maybe we could find all `*-config` programs on `PATH` and add them to cross file.

**Comment by Ericson2314** [comment]
because config-tools are such a pain, I bet we're having trouble with many of them anyways, so I would deal with it on an as-needed basis.

**Comment by jtojnar** [comment]
Merging then.

**Comment by Ericson2314** [comment]
Just ping me liberally if things do fail! :)

**Pull request merged**
