### PR TITLE
llvmPackages: rectify URLs

### PR DESCRIPTION
**Pull request by ggreif**
###### Motivation for this change

https://github.com/NixOS/nixpkgs/pull/78482#issuecomment-587600430

###### Things done

Updated `http://` schemes to `https://`. Followed some moved pages.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
Changes that cause a mass rebuild need to target branch "staging" instead of "master".

**Comment by ggreif** [comment]
Sure, will relocate the patch!

**Comment by ggreif** [comment]
I had to cherry-pick b2ea246 from `master`. Will wait 'till `staging` has caught up with it and then rebase. This guy is not urgent at all.

**Comment by basvandijk** [comment]
Thanks Gabor!

**Pull request merged**
