### PR TITLE
ocamlPackages.reason-native.qcheck-rely: remove

### PR DESCRIPTION
**Pull request by superherointj**
ocamlPackages.reason-native.qcheck-rely: remove

Build is broken. Unmaintained.

### CODE REVIEW

**Comment by Et7f3** [comment]
It isn't unmaintened. Upstream used version 0.9 of qcheck and version 0.9 it still build. check haven't reached 1.0 so maybe we can add another qcheck version ?

**Comment by superherointj** [comment]
> It isn't unmaintened. 

This package hasn't received an update in 3 years:
https://github.com/reasonml/reason-native/tree/master/src/qcheck-rely

Reason project is dead.

> Upstream used version 0.9 of qcheck and version 0.9 it still build. check haven't reached 1.0 so maybe we can add another qcheck version ?

I'm not sure that is a good idea.

**Review by ulrikstrid — APPROVED** [review]
I agree that removing this is a good idea since all of `reason-native` is probably unmaintained at this point.

I'm just not sure about what is the usual approach here.

**Comment by Et7f3** [comment]
It require a 2 lines patch to build https://github.com/reasonml/reason-native/pull/269/commits/280b3ba7513add0f3d7e47def3f7ddefcec09fea I wouldn't say unmaintened. Would you accept PR if I add me as maintainer ?

**Comment by superherointj** [comment]
> It require a 2 lines patch to build [reasonml/reason-native@280b3ba](https://github.com/reasonml/reason-native/commit/280b3ba7513add0f3d7e47def3f7ddefcec09fea) I wouldn't say unmaintened. Would you accept PR if I add me as maintainer ?

Sure.

**Comment by ulrikstrid** [comment]
@Et7f3 I think we could merge it with adding it back and  your patch as well

**Comment by superherointj** [comment]
> @Et7f3 I think we could merge it with adding it back and your patch as well

Use `fetchpatch` to fetch from commit (not PR) of upstream PR. 
Add URL of upstream PR as comment at top of it.

**Pull request merged**
