### PR TITLE
brave: 1.7.92 -> 1.8.95

### PR DESCRIPTION
**Pull request by CheariX**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dasJ** [comment]
What happened to the PR title? :O

**Comment by CheariX** [comment]
> What happened to the PR title? :O

Sorry. I used `hub pull-request` for the first time. Didn't even notice.

**Comment by rht** [comment]
cc: @JeffLabonte for review.

**Review by JeffLabonte — APPROVED** [review]
LGTM

**Comment by CheariX** [comment]
Can i do anything else to push this?

**Comment by CheariX** [comment]
Is there anything else we can to to help merging it?

**Comment by FelschR** [comment]
Compiled and ran it with `nix-review`. Looks fine to me.

**Review by felschr — APPROVED** [review]

**Pull request merged**
