### PR TITLE
kubecolor: 0.0.21 -> 0.0.25, switch back to upstream, cleanup maintai…

### PR DESCRIPTION
**Pull request by SuperSandro2000**
…ners

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by emilylange** [comment]
@SuperSandro2000: a few things. Would be cool if you could respond :)

1. What was your motivation behind removing @ivankovnatsky from `meta.maintainers`? Did you two talk in private or something?
1. To me, it feels like the fork at https://github.com/kubecolor/kubecolor should still be preferred over https://github.com/hidetatz/kubecolor. Considering the diffs between those and comparing the responsiveness and k8s-wide community involvement of each maintainer. https://github.com/kubecolor/kubecolor/compare/v0.0.20...v0.0.21 vs https://github.com/hidetatz/kubecolor/compare/v0.0.20...v0.0.25, https://github.com/hidetatz/kubecolor/issues/95
1. What made you wanting to switch back to, what you refer to as, "upstream"?
1. Please keep `meta.{homepage,changelog}` in sync.

**Review by ivankovnatsky — COMMENTED** [review]
I don't mind, except for the homepage and changelog update.

**Comment by SuperSandro2000** [comment]
> What was your motivation behind removing ivankovnatsky from meta.maintainers? Did you two talk in private or something?

I sometimes remove not so active looking maintainers to so that a package does not look more active maintained then it really is. In the end I'd rather have one active maintainer on a package instead of 3 inactive.

> To me, it feels like the fork at [kubecolor/kubecolor](https://github.com/kubecolor/kubecolor) should still be preferred over [hidetatz/kubecolor](https://github.com/hidetatz/kubecolor). Considering the diffs between those and comparing the responsiveness and k8s-wide community involvement of each maintainer. [kubecolor/kubecolor@v0.0.20...v0.0.21](https://github.com/kubecolor/kubecolor/compare/v0.0.20...v0.0.21) vs [hidetatz/kubecolor@v0.0.20...v0.0.25](https://github.com/hidetatz/kubecolor/compare/v0.0.20...v0.0.25),

If you take a close look at the diff, then you see that kubecolor/kubecolor has not any significant changes, they mostly changed the import path and also the readme, ci and one code change. Compared to the original which had some more major changes.

**Comment by emilylange** [comment]
> If you take a close look at the diff, then you see that kubecolor/kubecolor has not any significant changes, they mostly changed the import path and also the readme, ci and one code change. Compared to the original which had some more major changes.

I feel like there is a chance you might have confused kubecolor/kubecolor with hidetatz/kubecolor.

I would argue, kubecolor/kubecolor has more "significant" changes.
While

> they mostly changed the import path and also the readme, ci and one code change

applies to hidetatz/kubecolor :eyes:

**Comment by SuperSandro2000** [comment]
> I would argue, kubecolor/kubecolor has more "significant" changes.

I compared them again and the only relevant change is https://github.com/kubecolor/kubecolor/pull/1/commits/f5983eaacc1a30389c0e595bcb4e1b6da1c72445#diff-58f406e38e3da16176434f1366d55aeeb357db33dec0d28a6e96714d80c50e77 and https://github.com/kubecolor/kubecolor/pull/1/commits/f5983eaacc1a30389c0e595bcb4e1b6da1c72445#diff-6fda8dfbacb16a290308a43224a4965a24238e2a09a7048b24b1d15a37c02d87 . Everything else is not really relevant to the nixpkgs packaging.

**Pull request closed without merging**
