### PR TITLE
nixos: set default for boot.tmpOnTmpfs to true

### PR DESCRIPTION
**Pull request by cmfwyp**
###### Motivation for this change

Mounting /tmp as a tmpfs keeps /tmp clean on boot and diminishes disk usage, which in turn can save power and increase lifetime of SSD devices. It is the default behavior on Fedora, Arch Linux, and Ubuntu.
###### Things done
- [x] Tested on NixOS with the nixos-unstable channel.
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This currently uses the tmp.mount systemd unit, which has issues #14777 and #10670. It is perhaps preferable to wait for #14778 to be merged so that these issues are solved.

Since this is an incompatible change, I added an item to the release notes for 16.09.

### CODE REVIEW

**Comment by cmfwyp** [comment]
Resolved the merge conflict.

**Comment by abbradar** [comment]
One concern that I have is that building massive projects like Chromium can eat all the RAM with tmpfs because Nix creates build directories in `/tmp`. My proposed solution is to change that to `/var/tmp`.

**Comment by edolstra** [comment]
Nitpick: Shouldn't this option be named `boot.tmpfsOnTmp` (as it mounts a `tmpfs` on /tmp, not /tmp on a tmpfs).

**Comment by cmfwyp** [comment]
Yes, that would be the correct option name. I can push a commit to rename it to that and alias the old name.

@abbradar Good point. Builds are something that would preferably be done in memory, to make them faster and use the disk less, but systems may not have a swap file and therefore come out of memory pretty fast with some builds, which is a more important concern.

On the other hand, I think this would already be an issue when using Nix on most Linux distributions that mount a tmpfs on /tmp; which can mean either that this is already a problem on these distributions and that the path should be changed to /var/tmp (how likely is changing the default path for Nix to break things?), or that it has not been a problem on these distributions and as a consequence that it should not be a problem for NixOS either.

/tmp is the more semantically-correct place for builds, since they do not need to persist for a long time or even through reboots, but it is not ideal for large files.<sup>1</sup>

1: A good comparison: http://0pointer.de/blog/projects/tmp.html.

**Comment by abbradar** [comment]
@cmfwyp Subjectively that would be a bigger problem on NixOS because it's the main platform for overall Nix development and also for Hydra hosts, which together (anecdotally!) account for almost all "big" builds in the Linux/Nix world.

That said, I also do like `/tmp` more for storing builds precisely because of its FHS semantics (they are not needed to be "persistent"). Also, speed and disk wear concerns for small builds are important too.

I'm not sure how this problem should be solved. For some prior experience, on Arch Linux `/tmp` is used for builds by `yaourt` which is a popular tool for building and installing packages from source. I needed to remount `/tmp` or move build to somewhere enough times for me to remember (but not really frequently) when I had 2 and later 4GB of RAM.

**Comment by romildo** [comment]
In Gentoo Linux I usually mount `/tmp` as a `tmpfs` file system, and it is used for building most of the packages. For particular packages which demand too much space I set a per package environment variable `PORTAGE_TMPDIR` which is used to build that package.

Maybe something in this line can be figured out for NixOS too.

**Comment by cmfwyp** [comment]
The more common name seems to be "tmp on tmpfs" ([[1]](https://en.opensuse.org/openSUSE:Tmp_on_tmpfs) [[2]](https://insights.ubuntu.com/2016/01/20/data-driven-analysis-tmp-on-tmpfs/) [[3]](https://wiki.centos.org/TipsAndTricks/TmpOnTmpfs)  [[4]](https://fedoraproject.org/wiki/Features/tmp-on-tmpfs)), so I suggest keeping that.

Regarding large builds, I see multiple options. Adding a meta-attribute for build expressions that use large files is not an elegant solution. Build servers (Hydra or otherwise) that do builds with large files can set `boot.tmpOnTmpfs` to false. Ideally, there would also be a way with `nix-build` to perform the build in `/var/tmp` instead of `/tmp`, which could be used when developing for builds that use large files.

**Comment by fpletz** [comment]
Deferred to 17.09 because a solution to use another directory on a per build basis would be needed.

**Comment by abbradar** [comment]
Another solution may be to make Nix build in `/var/tmp` instead.

**Comment by ckauhaus** [comment]
Any news on this one? Will this make it into 18.03?

**Comment by samueldr** [comment]
Adopting into 18.09 not for definitive inclusion, but since it previously was part of release milestones.

* * *

I would like to know if the previous concerns are still relevant, and what work is being done to fix them, if any.

**Comment by vcunat** [comment]
It's a rather special use case, but I disabled this on the `t4{a,b}` machines on Hydra.  That certainly lead to some slight slow-down, but reliability increased.  The machines don't have that little RAM (2-3 GiB/thread) and `"big-parallel"` builds didn't go to them, but some problems still happened daily.

**Pull request closed without merging**
