### PR TITLE
pythonPackages.ciso8601: init at 2.1.1

### PR DESCRIPTION
**Pull request by liamdiprose**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] Ubuntu 18.04
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) **not applicable?**
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM
module seems to work

```
[4 built, 4 copied (1.1 MiB), 0.2 MiB DL]
https://github.com/NixOS/nixpkgs/pull/70837
2 package were build:
python27Packages.ciso8601 python37Packages.ciso8601
```

**Comment by jonringer** [comment]
@GrahamcOfBorg build python27Packages.ciso8601 python37Packages.ciso8601

**Comment by jonringer** [comment]
do you mind rebasing this branch on origin/master?

**Comment by jonringer** [comment]
also, please squash all the commits into one.
```
git reset HEAD~3
git commit -a --amend --no-edit
git push force liamdiprose ciso8601-2.1.1
```

**Comment by jonringer** [comment]
changes are also present in #70840

**Comment by liamdiprose** [comment]
Closing in favor of #70840

**Pull request closed without merging**
