### PR TITLE
go_1_14: 1.14.13 -> 1.14.14, go_1_15: 1.15.6 -> 1.15.7

### PR DESCRIPTION
**Pull request by zowoq**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Intentionally targeting `master`.

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
> Intentionally targeting master.

Are you sure we want to target master with this many rebuilds?

**Comment by zowoq** [comment]
> Are you sure you want to target master with this many rebuilds?

Yes, we usually send `go` rebuilds to master as they are quick.

**Review by mdlayher — APPROVED** [review]
LGTM

**Review by rvolosatovs — APPROVED** [review]
1.15.7 works fine on NixOS

**Pull request merged**
