### PR TITLE
cargo-pgrx: refactor

### PR DESCRIPTION
**Pull request by marsam**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by happysalada** [comment]
Hey thanks for the refactor !

Just to let you know, ive talked with the upstream maintainer and he will let me know when things stabilize. At the moment its a bit tricky because every new minor version is breaking but stability is coming.
Im waiting for this to become stable before paclaging postgresml

Are you waiting for something more to mark it as ready for review ?

**Comment by marsam** [comment]
Hi, sorry for the delay.  Yeah, I noticed that. Thank you for pushing it upstream.
But while pgrx get stabilized, I think it will better to expose these versions to avoid duplicated code in the extensions.

>Are you waiting for something more to mark it as ready for review ?

I was planing to work on `buildPgrxExtension` to offer a better interface. I was thinking of something like:
```nix
{ buildPgrxExtension }:

buildPgrxExtension {
  pgrx = "0.11.2";

  pname = "pgvecto-rs";
  version = "0.2.1";
  /* ... */
}
```
But, I'll leave it to another PR.

**Review by diogotcorreia — APPROVED** [review]
This looks awesome, thank you!

I've build both affected extensions and they seem to build fine on x86_64-linux.
`pgvecto-rs` did not rebuild since nothing changed, but `timescaledb_toolkit` seems to have been rebuilt because `cargoHash` of pgrx 0_10_2 changed, not really sure why.

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 296336` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>postgresql13JitPackages.timescaledb_toolkit</li>
    <li>postgresql14JitPackages.timescaledb_toolkit</li>
    <li>postgresqlJitPackages.timescaledb_toolkit (postgresql15JitPackages.timescaledb_toolkit)</li>
    <li>postgresql16JitPackages.timescaledb_toolkit</li>
    <li>postgresql16Packages.timescaledb_toolkit</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>cargo-pgrx_0_10_2</li>
    <li>cargo-pgrx_0_11_2</li>
    <li>cargo-pgrx_0_11_3</li>
    <li>postgresql12JitPackages.timescaledb_toolkit</li>
    <li>postgresql12Packages.timescaledb_toolkit</li>
    <li>postgresql13Packages.timescaledb_toolkit</li>
    <li>postgresql14Packages.timescaledb_toolkit</li>
    <li>postgresqlPackages.timescaledb_toolkit (postgresql15Packages.timescaledb_toolkit)</li>
  </ul>
</details>

**Pull request merged**
