### PR TITLE
sbclPackages: mark some failing packages as broken

### LINKED ISSUE #201094: Fix broken lisp-packages-new or mark them broken
These are the most prominent failing dependencies on the nixos-unstable channel right now and should be addressed before the 22.11 branch-off.

Screenshot 2022-11-14 at 00-12-48 nixos trunk-combined 1785383

https://malob.github.io/nix-review-tools-reports/nixos:trunk-combined/nixos_trunk-combined_1785383.html

### PR DESCRIPTION
**Pull request by Uthar**
fixes #201094 

Added a list of broken packages and re-run `ql-import.lisp`.

Also see https://github.com/NixOS/nixpkgs/pull/200573 https://github.com/NixOS/nixpkgs/pull/195393

### CODE REVIEW

**Comment by Uthar** [comment]
should be good for now

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 201101` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>16 packages marked as broken and skipped:</summary>
  <ul>
    <li>lispPackages_new.sbclPackages.cl-gimei_slash_test</li>
    <li>lispPackages_new.sbclPackages.cl-quil_slash_tools</li>
    <li>lispPackages_new.sbclPackages.cl-quil_slash_tools-tests</li>
    <li>lispPackages_new.sbclPackages.imago_slash_jupyter</li>
    <li>lispPackages_new.sbclPackages.lisp-chat_slash_client</li>
    <li>lispPackages_new.sbclPackages.litterae_slash_tests</li>
    <li>lispPackages_new.sbclPackages.math_slash_docs</li>
    <li>lispPackages_new.sbclPackages.math_slash_ls-gsll</li>
    <li>lispPackages_new.sbclPackages.math_slash_tests</li>
    <li>lispPackages_new.sbclPackages.monomyth_slash_basic-example-master</li>
    <li>lispPackages_new.sbclPackages.monomyth_slash_basic-example-worker</li>
    <li>lispPackages_new.sbclPackages.monomyth_slash_tests</li>
    <li>lispPackages_new.sbclPackages.quilc</li>
    <li>lispPackages_new.sbclPackages.quilc-tests</li>
    <li>lispPackages_new.sbclPackages.torrents_slash_tk</li>
    <li>lispPackages_new.sbclPackages.wayflan-client_slash_examples</li>
  </ul>
</details>
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>lispPackages_new.sbclPackages.cl-cairo2-xlib</li>
    <li>lispPackages_new.sbclPackages.cl-pango</li>
    <li>lispPackages_new.sbclPackages.cl-random</li>
    <li>lispPackages_new.sbclPackages.cl-random-tests</li>
    <li>lispPackages_new.sbclPackages.cl-rsvg2</li>
    <li>lispPackages_new.sbclPackages.cl-rsvg2-pixbuf</li>
    <li>lispPackages_new.sbclPackages.cl-rsvg2-test</li>
    <li>lispPackages_new.sbclPackages.clinch-pango</li>
    <li>lispPackages_new.sbclPackages.math</li>
    <li>lispPackages_new.sbclPackages.pzmq-compat</li>
    <li>lispPackages_new.sbclPackages.pzmq-examples</li>
    <li>lispPackages_new.sbclPackages.pzmq-test</li>
  </ul>
</details>
<details>
  <summary>74 packages built:</summary>
  <ul>
    <li>lispPackages_new.sbclPackages.a-cl-cairo2-loader</li>
    <li>lispPackages_new.sbclPackages.ahungry-fleece</li>
    <li>lispPackages_new.sbclPackages.antik</li>
    <li>lispPackages_new.sbclPackages.cl-ana</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_calculus</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_csv-table</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_error-propogation</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_fitting</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_hdf-cffi</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_hdf-table</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_hdf-typespec</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_hdf-utils</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_histogram</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_linear-algebra</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_lorentz</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_makeres</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_makeres-block</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_makeres-branch</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_makeres-graphviz</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_makeres-macro</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_makeres-progress</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_makeres-table</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_makeres-utils</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_math-functions</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_ntuple-table</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_plotting</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_quantity</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_serialization</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_spline</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_statistical-learning</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_statistics</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_table-utils</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_table-viewing</li>
    <li>lispPackages_new.sbclPackages.cl-base16</li>
    <li>lispPackages_new.sbclPackages.cl-cairo2</li>
    <li>lispPackages_new.sbclPackages.cl-cairo2-demos</li>
    <li>lispPackages_new.sbclPackages.cl-gimei</li>
    <li>lispPackages_new.sbclPackages.cl-libxml2</li>
    <li>lispPackages_new.sbclPackages.cl-libxml2-test</li>
    <li>lispPackages_new.sbclPackages.cl-libyaml</li>
    <li>lispPackages_new.sbclPackages.cl-libyaml-test</li>
    <li>lispPackages_new.sbclPackages.cl-myriam</li>
    <li>lispPackages_new.sbclPackages.cl-readline</li>
    <li>lispPackages_new.sbclPackages.cl-rules</li>
    <li>lispPackages_new.sbclPackages.cl-rules-test</li>
    <li>lispPackages_new.sbclPackages.cl-yaml</li>
    <li>lispPackages_new.sbclPackages.cl-yaml-test</li>
    <li>lispPackages_new.sbclPackages.clinch-cairo</li>
    <li>lispPackages_new.sbclPackages.common-lisp-jupyter</li>
    <li>lispPackages_new.sbclPackages.cytoscape-clj</li>
    <li>lispPackages_new.sbclPackages.dml</li>
    <li>lispPackages_new.sbclPackages.duologue-readline</li>
    <li>lispPackages_new.sbclPackages.gsll</li>
    <li>lispPackages_new.sbclPackages.injection</li>
    <li>lispPackages_new.sbclPackages.injection-test</li>
    <li>lispPackages_new.sbclPackages.kekule-clj</li>
    <li>lispPackages_new.sbclPackages.lisp-chat</li>
    <li>lispPackages_new.sbclPackages.litterae</li>
    <li>lispPackages_new.sbclPackages.monomyth</li>
    <li>lispPackages_new.sbclPackages.openapi-parser</li>
    <li>lispPackages_new.sbclPackages.openapi-parser-tests</li>
    <li>lispPackages_new.sbclPackages.pzmq</li>
    <li>lispPackages_new.sbclPackages.replic</li>
    <li>lispPackages_new.sbclPackages.replic-test</li>
    <li>lispPackages_new.sbclPackages.rpcq</li>
    <li>lispPackages_new.sbclPackages.rpcq-tests</li>
    <li>lispPackages_new.sbclPackages.sanitize</li>
    <li>lispPackages_new.sbclPackages.sanitize-test</li>
    <li>lispPackages_new.sbclPackages.skeleton</li>
    <li>lispPackages_new.sbclPackages.torrents</li>
    <li>lispPackages_new.sbclPackages.torrents-test</li>
    <li>lispPackages_new.sbclPackages.xfactory</li>
    <li>lispPackages_new.sbclPackages.xfactory-test</li>
    <li>lispPackages_new.sbclPackages.xoverlay</li>
  </ul>
</details>

**Comment by Uthar** [comment]
Anything more? This is fun

**Comment by mweinelt** [comment]
No, this looks good! Thanks for the quick turn around.

---

Result of `nixpkgs-review pr 201101` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>19 packages marked as broken and skipped:</summary>
  <ul>
    <li>lispPackages_new.sbclPackages.cl-gimei_slash_test</li>
    <li>lispPackages_new.sbclPackages.cl-quil_slash_tools</li>
    <li>lispPackages_new.sbclPackages.cl-quil_slash_tools-tests</li>
    <li>lispPackages_new.sbclPackages.cl-random</li>
    <li>lispPackages_new.sbclPackages.cl-random-tests</li>
    <li>lispPackages_new.sbclPackages.imago_slash_jupyter</li>
    <li>lispPackages_new.sbclPackages.lisp-chat_slash_client</li>
    <li>lispPackages_new.sbclPackages.litterae_slash_tests</li>
    <li>lispPackages_new.sbclPackages.math</li>
    <li>lispPackages_new.sbclPackages.math_slash_docs</li>
    <li>lispPackages_new.sbclPackages.math_slash_ls-gsll</li>
    <li>lispPackages_new.sbclPackages.math_slash_tests</li>
    <li>lispPackages_new.sbclPackages.monomyth_slash_basic-example-master</li>
    <li>lispPackages_new.sbclPackages.monomyth_slash_basic-example-worker</li>
    <li>lispPackages_new.sbclPackages.monomyth_slash_tests</li>
    <li>lispPackages_new.sbclPackages.quilc</li>
    <li>lispPackages_new.sbclPackages.quilc-tests</li>
    <li>lispPackages_new.sbclPackages.torrents_slash_tk</li>
    <li>lispPackages_new.sbclPackages.wayflan-client_slash_examples</li>
  </ul>
</details>
<details>
  <summary>89 packages built:</summary>
  <ul>
    <li>lispPackages_new.sbclPackages.a-cl-cairo2-loader</li>
    <li>lispPackages_new.sbclPackages.ahungry-fleece</li>
    <li>lispPackages_new.sbclPackages.antik</li>
    <li>lispPackages_new.sbclPackages.cl-ana</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_calculus</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_csv-table</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_error-propogation</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_fitting</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_hdf-cffi</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_hdf-table</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_hdf-typespec</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_hdf-utils</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_histogram</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_linear-algebra</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_lorentz</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_makeres</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_makeres-block</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_makeres-branch</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_makeres-graphviz</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_makeres-macro</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_makeres-progress</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_makeres-table</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_makeres-utils</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_math-functions</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_ntuple-table</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_plotting</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_quantity</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_serialization</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_spline</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_statistical-learning</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_statistics</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_table-utils</li>
    <li>lispPackages_new.sbclPackages.cl-ana_dot_table-viewing</li>
    <li>lispPackages_new.sbclPackages.cl-base16</li>
    <li>lispPackages_new.sbclPackages.cl-cairo2</li>
    <li>lispPackages_new.sbclPackages.cl-cairo2-demos</li>
    <li>lispPackages_new.sbclPackages.cl-cairo2-xlib</li>
    <li>lispPackages_new.sbclPackages.cl-freetype2</li>
    <li>lispPackages_new.sbclPackages.cl-freetype2-tests</li>
    <li>lispPackages_new.sbclPackages.cl-gimei</li>
    <li>lispPackages_new.sbclPackages.cl-gtk2-gdk</li>
    <li>lispPackages_new.sbclPackages.cl-gtk2-glib</li>
    <li>lispPackages_new.sbclPackages.cl-gtk2-pango</li>
    <li>lispPackages_new.sbclPackages.cl-libxml2</li>
    <li>lispPackages_new.sbclPackages.cl-libxml2-test</li>
    <li>lispPackages_new.sbclPackages.cl-libyaml</li>
    <li>lispPackages_new.sbclPackages.cl-libyaml-test</li>
    <li>lispPackages_new.sbclPackages.cl-myriam</li>
    <li>lispPackages_new.sbclPackages.cl-pango</li>
    <li>lispPackages_new.sbclPackages.cl-readline</li>
    <li>lispPackages_new.sbclPackages.cl-rsvg2</li>
    <li>lispPackages_new.sbclPackages.cl-rsvg2-pixbuf</li>
    <li>lispPackages_new.sbclPackages.cl-rsvg2-test</li>
    <li>lispPackages_new.sbclPackages.cl-rules</li>
    <li>lispPackages_new.sbclPackages.cl-rules-test</li>
    <li>lispPackages_new.sbclPackages.cl-yaml</li>
    <li>lispPackages_new.sbclPackages.cl-yaml-test</li>
    <li>lispPackages_new.sbclPackages.clinch-cairo</li>
    <li>lispPackages_new.sbclPackages.clinch-pango</li>
    <li>lispPackages_new.sbclPackages.common-lisp-jupyter</li>
    <li>lispPackages_new.sbclPackages.cytoscape-clj</li>
    <li>lispPackages_new.sbclPackages.dml</li>
    <li>lispPackages_new.sbclPackages.duologue-readline</li>
    <li>lispPackages_new.sbclPackages.gsll</li>
    <li>lispPackages_new.sbclPackages.injection</li>
    <li>lispPackages_new.sbclPackages.injection-test</li>
    <li>lispPackages_new.sbclPackages.kekule-clj</li>
    <li>lispPackages_new.sbclPackages.lisp-chat</li>
    <li>lispPackages_new.sbclPackages.litterae</li>
    <li>lispPackages_new.sbclPackages.monomyth</li>
    <li>lispPackages_new.sbclPackages.openapi-parser</li>
    <li>lispPackages_new.sbclPackages.openapi-parser-tests</li>
    <li>lispPackages_new.sbclPackages.pzmq</li>
    <li>lispPackages_new.sbclPackages.pzmq-compat</li>
    <li>lispPackages_new.sbclPackages.pzmq-examples</li>
    <li>lispPackages_new.sbclPackages.pzmq-test</li>
    <li>lispPackages_new.sbclPackages.replic</li>
    <li>lispPackages_new.sbclPackages.replic-test</li>
    <li>lispPackages_new.sbclPackages.rpcq</li>
    <li>lispPackages_new.sbclPackages.rpcq-tests</li>
    <li>lispPackages_new.sbclPackages.sanitize</li>
    <li>lispPackages_new.sbclPackages.sanitize-test</li>
    <li>lispPackages_new.sbclPackages.skeleton</li>
    <li>lispPackages_new.sbclPackages.text-subsystem-generate-font</li>
    <li>lispPackages_new.sbclPackages.torrents</li>
    <li>lispPackages_new.sbclPackages.torrents-test</li>
    <li>lispPackages_new.sbclPackages.xfactory</li>
    <li>lispPackages_new.sbclPackages.xfactory-test</li>
    <li>lispPackages_new.sbclPackages.xoverlay</li>
  </ul>
</details>

**Comment by Uthar** [comment]
No problem!

**Pull request merged**
