### PR TITLE
vend: Use nix-community fork of vend.

### PR DESCRIPTION
**Pull request by c00w**
Note that pkgs.govendor is currently taken by a package which is
orphaned by upstream. It's mildly confusing to have vend point to
nix-community/govendor, but I felt govendor was a better name for the
nix tool since it's easy to understand what's it's for, compared to vend
which won't really make sense to anyone who doesn't package go.

I manually checked that the same hashes were generated by the new tool.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by c00w** [comment]
cc @Mic92 @zowoq

**Comment by zowoq** [comment]
> It's mildly confusing to have vend point to
nix-community/govendor

IMHO it is more than just mildly confusing.

I am not in favour for the name collision with another Go vendoring tool even if it is abandoned.

**Comment by Mic92** [comment]
> > It's mildly confusing to have vend point to
> > nix-community/govendor
> 
> IMHO it is more than just mildly confusing.
> 
> I am not in favour for the name collision with another Go vendoring tool even if it is abandoned.

Is there maybe a third name not used by anything?

**Comment by zimbatm** [comment]
What's the issue with https://github.com/nomad-software/vend, are they not accepting patches?

Unless the project is a complete rewrite, I would keep the same name. It's not great, live with it :-D

If we have to fork it, I would also make sure that the repo is recorded as a fork of upstream for clarity's sake, and add an explanation to the README to explain why we need a long-term fork.

**Comment by zowoq** [comment]
https://github.com/nomad-software/vend/commit/dc54ecbb589c6c52b1577c32d0502d460c8f7db1 Upstream seems to have implemented their own version of replacements.

**Comment by Mic92** [comment]
> What's the issue with [nomad-software/vend](https://github.com/nomad-software/vend), are they not accepting patches?
> 
> Unless the project is a complete rewrite, I would keep the same name. It's not great, live with it :-D
> 
> If we have to fork it, I would also make sure that the repo is recorded as a fork of upstream for clarity's sake, and add an explanation to the README to explain why we need a long-term fork.

The main motivation is to prevent checksum breaks. Upstream does not care about this too much and automatic updates by r-ryantm might introduce silent breakage. The tool itself is not overly complex that's why I think maintaining it our self is the better way to not break things in `buildGoModule`.

**Comment by zowoq** [comment]
> automatic updates by r-ryantm might introduce silent checksum changes.

There are a couple of different ways to prevent the bot sending PRs.

**Comment by zimbatm** [comment]
In order of importance for me is:
* keep the 1:1 mapping between the repo and package name. It's annoying to go resolve layers of indirections.
* make the fork explicit

I would re-fork upstream into nix-community/vend, rename the repo to nix-community/nixpkgs-vend and update the README with a quick explanation about the fork.

**Comment by zowoq** [comment]
I've checked a few packages and the upstream replacements seems to work.

Upstream has also removed `fatih/color` which was the only dependency. https://github.com/nomad-software/vend/commit/bb65beea4dcfb4b8f825843ef1f58cb0bd298347

Assuming that the upstream version is suitable for us to use I think we could just pin the version and disable the update bot.

Adding a warning should be sufficient to prevent accidental upgrades in the event someone does try to bump it manually.

**Comment by Mic92** [comment]
> I've checked a few packages and the upstream replacements seems to work.
> 
> Upstream has also removed `fatih/color` which was the only dependency. [nomad-software/vend@bb65bee](https://github.com/nomad-software/vend/commit/bb65beea4dcfb4b8f825843ef1f58cb0bd298347)
> 
> Assuming that the upstream version is suitable for us to use I think we could just pin the version and disable the update bot.
> 
> Adding a warning should be sufficient to prevent accidental upgrades in the event someone does try to bump it manually.
> 
> Update:
> 
> Upstream `vend` works for the original six packages and only two of them need hash changes.
> 
> However it breaks `telegraf`.

So the only patch left would be the mod-tidy one? @c00w what is your opinion about having the fork?

**Comment by zowoq** [comment]
Once #95485 is merged `telegraf` won't require `runVend`.

I've opened to #95487 switch to upstream.

**Pull request closed without merging**
