### PR TITLE
kdevelop: 4.7.1 -> 4.7.3

### PR DESCRIPTION
**Pull request by ambrop72**
Tested on channels/nixos-15.09 but not this PR as-is (I have cherry-picked it to master).

The new patches fix some cmake error having something to do with a target name conflict related to gettext.

### CODE REVIEW

**Comment by aneeshusa** [comment]
Could you also please add a commit to update the `meta.homepage` attribute for kdevelop to use HTTPS? (i.e. https://www.kdevelop.org/) Refs #13809.

**Comment by ambrop72** [comment]
@aneeshusa, done.

**Comment by joachifm** [comment]
I tried building this on current nixpkgs-unstable, but it fails during the patch phase:
```
applying patch /nix/store/czasppzmbkvaq5nzg0jsaa28xdmqxbix-svn-1.9.patch
patching file plugins/subversion/kdevsvncpp/client_ls.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
3 out of 3 hunks ignored -- saving rejects to file plugins/subversion/kdevsvncpp/client_ls.cpp.rej
patching file plugins/subversion/kdevsvncpp/dirent.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file plugins/subversion/kdevsvncpp/dirent.cpp.rej
patching file plugins/subversion/kdevsvncpp/dirent.hpp
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file plugins/subversion/kdevsvncpp/dirent.hpp.rej
```

**Comment by ambrop72** [comment]
@joachifm, I removed the problematic patch, please try again. I am trying to build myself on nixpkgs master but it will take time due to dependencies.

**Comment by joachifm** [comment]
Have you tried checking out channels/nixpkgs-unstable? Much closer to master, with binary substitutions available.

**Comment by joachifm** [comment]
This now builds for me on nixpkgs-unstable, but it fails to run (I don't use kde, though, so might be unrelated to this change).

**Comment by ambrop72** [comment]
It builds for me too, but I didn't even try to run it because it needs to be in the proper environment (e.g. not with KDE from stable nixpkgs running alongside on my system). I'll test it with my whole system and report back.

If you use NixOS it should run fine if you install it with nix-env and don't have incompatible KDE software also installed, only you may need to run "kbuildsycoca4".

**Comment by joachifm** [comment]
Actually, the run-time error turned out to be caused by PaX, so probably needs some paxmarkings. Anyway, that's a different issue entirely.

**Comment by ambrop72** [comment]
I confirm this works on top of channels/nixos-unstable, I think it's OK to merge.

**Comment by joachifm** [comment]
Let's do it.

**Comment by joachifm** [comment]
@ambrop72 This caused a build error on hydra: https://hydra.nixos.org/build/33306016/nixlog/1/raw

```
/tmp/nix-build-kdevplatform-1.7.3.drv-0/kdevplatform-1.7.3/plugins/filetemplates/classidentifierpage.cpp:22:25: fatal error: ui_newclass.h: No such file or directory
 #include "ui_newclass.h"
                         ^
compilation terminated.
plugins/filetemplates/CMakeFiles/testfiletemplates.dir/build.make:134: recipe for target 'plugins/filetemplates/CMakeFiles/testfiletemplates.dir/classidentifierpage.cpp.o' failed
make[2]: *** [plugins/filetemplates/CMakeFiles/testfiletemplates.dir/classidentifierpage.cpp.o] Error 1
CMakeFiles/Makefile2:10309: recipe for target 'plugins/filetemplates/CMakeFiles/testfiletemplates.dir/all' failed
make[1]: *** [plugins/filetemplates/CMakeFiles/testfiletemplates.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
builder for ‘/nix/store/igqclxd96635wz9y20czs89jbyzgph7j-kdevplatform-1.7.3.drv’ failed with exit code 2
```

**Comment by ambrop72** [comment]
@joachifm Please try removing enableParallelBuilding=true.

**Comment by joachifm** [comment]
I would rather revert and await a new patch or receive a hotfix

**Comment by ambrop72** [comment]
@joachifm I suspect this is not a regression from 4.7.1 but caused either by chance or due to upgraded environment, posibly CMake. I've asked on #kdevelop@freenode and they haven't seen the issue before, but pointed to CMake as a possible culprit.

Anyway it's not economical for me to do any further testing of this locally. I recommend removing enableParallelBuilding and seeing if that works around the issue.

**Comment by vcunat** [comment]
It's typical that missing *_ui.h is due to parallel make. Those are generated during build.

**Comment by joachifm** [comment]
Alright, completed a sandboxed build of both kdevelop and kdevplatform, with the suggested change. Pushing it now. If this doesn't work, I'll just revert, I have no interest in building this any more, it takes forever.

**Comment by joachifm** [comment]
That fixed it. Thanks for your help

**Pull request merged**
