### PR TITLE
Kernels 2021-03-29

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Motivation for this change
Updates

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ivan** [comment]
5.10.26-hardened1 seems to be working for me (tested in vmware).

**Comment by NeQuissimus** [comment]
@ofborg test kernel-latest kernel-lts latestKernel.login kernel-latest-ath-user-regd latestKernel.hardened

**Comment by ivan** [comment]
For the 5.10 series it might make sense to go straight to 5.10.27 because of fixes made to mm (which I have not tested, but the commits look important). https://github.com/NixOS/nixpkgs/pull/117961#issuecomment-810384521

**Comment by NeQuissimus** [comment]
Backport to 20.09 in fe9aef0135d6496e2b2121c37217a57af78d4e69...371fe559696c8c038755104d0c69d010a1df796e

**Pull request merged**
