### PR TITLE
noto-fonts-emoji: unstable-2020-08-20 → 2020-09-16

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

Unicode 13.1

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by Mathnerd314 — CHANGES_REQUESTED** [review]
They bumped the required version of nototools / notofonttools to 0.2.13:
https://github.com/googlefonts/noto-emoji/commit/c9fde67449a31aedd953e79fbd8bb0abe0e124af

Currently we have 0.2.12, so you should update that too.

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build python3Packages.nototools

**Review by Mathnerd314 — APPROVED** [review]
Alright. I didn't actually test the emoji rendering but it's just a version bump so I doubt anything broke.

**Comment by sternenseemann** [comment]
Builds fine for me, resulting font seems good (did a sanity check with harfbuzz).

**Review by danieldk — APPROVED** [review]
Result of `nixpkgs-review pr 98159` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>noto-fonts-emoji</li>
    <li>python37Packages.nototools</li>
    <li>python38Packages.nototools</li>
    <li>twitter-color-emoji</li>
  </ul>
</details>

**Pull request merged**
