### PR TITLE
mtdutils: 1.5.2 -> 2.1.1

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

http://lists.infradead.org/pipermail/linux-mtd/2019-March/088267.html

And the previous releases, hardcoded version in URL I think caused
this to be missed by auto-updaters for a while now.

1.5.2, FWIW in 2015:

http://lists.infradead.org/pipermail/linux-mtd/2015-August/060723.html

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mmahut** [comment]
I'm getting the following during the build:

```
builder for '/nix/store/xfch0i7lz1dkcn0h6cr4gk85d06x3304-mtd-utils-2.1.0.drv' failed with exit code 2; last 6 log lines:
  unpacking sources
  unpacking source archive /nix/store/g1gzvibpd7n36hcgabwz3ggcj93mn38x-mtd-utils-2.1.0.tar.bz2
  source root is mtd-utils-2.1.0
  setting SOURCE_DATE_EPOCH to timestamp 1552495345 of file mtd-utils-2.1.0/include/stamp-h1
  patching sources
  sed: can't read common.mk: No such file or directory
cannot build derivation '/nix/store/hq8q9dn5v1hgq6n3xqambymjqr9lj4mv-env.drv': 1 dependencies couldn't be built
[2 built (1 failed), 63 copied (307.1 MiB), 69.3 MiB DL]
error: build of '/nix/store/hq8q9dn5v1hgq6n3xqambymjqr9lj4mv-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/62805
1 package failed to build:
mtdutils
```

**Comment by mmahut** [comment]
@GrahamcOfBorg build mtdutils

**Comment by c0bw3b** [comment]
@dtzWill  I'm gently hijacking your branch to complete this pkg refresh, sorry :)

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build mtdutils

**Review by c0bw3b — APPROVED** [review]
Builds and binaries runs fine

Result of `nix-review pr 62805` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>1 package were build:</summary>

  - mtdutils
</details>

**Pull request merged**
