### PR TITLE
openssh: decouple gssapi patch from kerberos

### PR DESCRIPTION
**Pull request by aneeshusa**
###### Things done:
- [ ] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- [x] Built on platform(s): Nix on Arch Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Apparently openssh_with_kerberos is prone to breakage when updating the openssh version; see #13595 and #13140.

cc @benley for the GSSAPI patch and @jxy since I broke openssh_with_kerberos for you :(

The GSSAPI patch is useful but maintained by Debian, not upstream, and
can be slow to update. To avoid breaking openssh_with_kerberos when
the openssh version is bumped but the GSSAPI patch has not been updated,
don't enable the GSSAPI patch implicitly but require it to be explicitly
enabled.

### CODE REVIEW

**Comment by benley** [comment]
There is an updated patch from Debian, if you wouldn't mind importing that to fix the build: https://anonscm.debian.org/cgit/pkg-ssh/openssh.git/commit/debian/patches/gssapi.patch?id=46961f5704f8e86cea3e99253faad55aef4d8f35

**Comment by aneeshusa** [comment]
@benley Is this an appropriate URL for fetchpatch? https://anonscm.debian.org/cgit/pkg-ssh/openssh.git/plain/debian/patches/gssapi.patch?id=46961f5704f8e86cea3e99253faad55aef4d8f35

**Comment by benley** [comment]
I guess so.  Honestly I'd prefer to just put the patch in our git repo like debian does, but various people seem opposed to that.

**Comment by cstrahan** [comment]
> I guess so. Honestly I'd prefer to just put the patch in our git repo like debian does, but various people seem opposed to that.

I tend to agree with that, though I've made the same observation you have with respect to popular sentiment. Patches just seem a little too transient to be depending on their URIs to remain available...

**Comment by joachifm** [comment]
I'm sure it's been discussed before, but what about a separate repo controlled by nixos.org for patches. Seems like a fair compromise?

**Comment by peti** [comment]
nixos.org caches source files automatically so that they can be downloaded even if they disappear from their original location.

**Pull request merged**
