### PR TITLE
nixos/less: set default lessopen preprocessor to null

### LINKED ISSUE #309599: NixOS should set programs.less.lessopen.default = null
## Issue description

When using the default pager `less` in NixOS, it is set to use a preprocessor calling `lesspipe`. `lesspipe` provides the following [enhancements to less](https://github.com/wofr06/lesspipe?tab=readme-ov-file#4-supported-file-formats) thus modifying less' default behavior.  This behavior as a NixOS default seems unexpected.

The NixOS minimal profile already has `programs.less.lessopen = mkDefault null;`: https://github.com/NixOS/nixpkgs/commit/8dfe8e447efefcaf2990532114f4b0259ba2eba3

Im proposing removing any preprocessing in less by default and set `programs.less.lessopen.default = null;`

### Steps to reproduce

```
$ echo $LESSOPEN # shows that less preprocessor is set
|/nix/store/2hh93jad9hlhgy2sqj4rfzsjj7c5pdf5-lesspipe-2.10/bin/lesspipe.sh %s
$ cat << EOF > example.json
{
    "glossary": {
        "title": "example glossary",
		"GlossDiv": {
            "title": "S",
			"GlossList": {
                "GlossEntry": {
                    "ID": "SGML",
					"SortAs": "SGML",
					"GlossTerm": "Standard Generalized Markup Language",
					"Acronym": "SGML",
					"Abbrev": "ISO 8879:1986",
					"GlossDef": {
                        "para": "A meta-markup language, used to create markup languages such as DocBook.",
						"GlossSeeAlso": ["GML", "XML"]
                    },
					"GlossSee": "markup"
                }
            }
        }
    }
}
EOF
$ less example.json | cat
==> (lesspipe 2.10) append : to filename to view the original json file
{
  "glossary": {
    "title": "example glossary",
    "GlossDiv": {
      "title": "S",
      "GlossList": {
        "GlossEntry": {
          "ID": "SGML",
          "SortAs": "SGML",
          "GlossTerm": "Standard Generalized Markup Language",
          "Acronym": "SGML",
          "Abbrev": "ISO 8879:1986",
          "GlossDef": {
            "para": "A meta-markup language, used to create markup languages such as DocBook.",
            "GlossSeeAlso": [
              "GML",
              "XML"
            ]
          },
          "GlossSee": "markup"
        }
      }
    }
  }
}
```
Note the output off less: `==> (lesspipe 2.10) append : to filename to view the original json file`

You can disable the preprocessor by setting the following in your nix Configuration:

```
programs.less.lessopen = lib.mkDefault null;
```

I also had to log out of my existing session (i3) to get my profile to update after a nixos-rebuild switch. After I can confirm `LESSOPEN` is not set in the environment:

```
$ echo $LESSOPEN

$
```

Confirm output with less:

```
$ less example.json | cat
{
    "glossary": {
        "title": "example glossary",
                "GlossDiv": {
            "title": "S",
                        "GlossList": {
                "GlossEntry": {
                    "ID": "SGML",
                                        "SortAs": "SGML",
                                        "GlossTerm": "Standard Generalized Markup Language",
                                        "Acronym": "SGML",
                                        "Abbrev": "ISO 8879:1986",
                                        "GlossDef": {
                        "para": "A meta-markup language, used to create markup languages such as DocBook.",
                                                "GlossSeeAlso": ["GML", "XML"]
                    },
                                        "GlossSee": "markup"
                }
            }
        }
    }
}
```

Output is now the default of less without the preprocessor.

## Technical details

```
$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/vm49ygzdh61j1r39l8ikb29icwljlymn-nix-info
copying path '/nix/store/vm49ygzdh61j1r39l8ikb29icwljlymn-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.26, NixOS, 23.11 (Tapir), 23.11.20240411.51651a5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-22.05.3300.82379884b2e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

### PR DESCRIPTION
**Pull request by sarcasticadmin**
## Description of changes

Fixes: https://github.com/NixOS/nixpkgs/issues/309599

Remove any preprocessing in less by default by setting `programs.less.lessopen.default = null`

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by eclairevoyant — COMMENTED** [review]
not sure what I think of this PR... but in any case this should also remove `defaultText` and set `example`, for consistency

**Review by FliegendeWurst — APPROVED** [review]
The linked issue has 9 :+1: vs. 2 :-1:, so this might be the better default.

**Comment by SuperSandro2000** [comment]
Why didn't this get a changelog entry?

**Comment by sarcasticadmin** [comment]
> Why didn't this get a changelog entry?

https://github.com/NixOS/nixpkgs/pull/367737

**Pull request merged**
