### PR TITLE
go: invoke bash directly on make.bash

### PR DESCRIPTION
**Pull request by tie**
###### Description of changes

This change invokes bash interpreter directly on make.bash script. This allows using overrideAttrs with dontPatch set to true as a workaround for issue #125198.

	pkgs.go.overrideAttrs (prev: { dontPatch = true; })

The package also now keeps the regexp/syntax/make_perl_groups.pl script since it is not used by the current test suite and it is confusing when some files present in upstream src tree are missing.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by zowoq — CHANGES_REQUESTED** [review]
- Needs to go to staging, not master.

- Split the bash and perl changes into separate commits.

- Add a comment in each file above the bash change:
```
# invoke the bash interpreter directly on make.bash script.
# this allows using overrideAttrs with dontPatch set to true.
```

**Comment by zowoq** [comment]
> This change invokes bash interpreter directly on make.bash script.

Rather than doing this it might be easier if we move `patchShebangs` to `buildPhase`?
```diff
diff --git a/pkgs/development/compilers/go/1.18.nix b/pkgs/development/compilers/go/1.18.nix
index 7b208da5988..5390d4f2b5b 100644
--- a/pkgs/development/compilers/go/1.18.nix
+++ b/pkgs/development/compilers/go/1.18.nix
@@ -63,10 +63,6 @@ stdenv.mkDerivation rec {
 
   depsTargetTarget = lib.optional stdenv.targetPlatform.isWindows threadsCross;
 
-  postPatch = ''
-    patchShebangs .
-  '';
-
   patches = [
     (substituteAll {
       src = ./iana-etc-1.17.patch;
@@ -117,6 +113,7 @@ stdenv.mkDerivation rec {
 
   buildPhase = ''
     runHook preBuild
+    patchShebangs .
     export GOCACHE=$TMPDIR/go-cache
     # this is compiled into the binary
     export GOROOT_FINAL=$out/share/go
```

**Comment by zowoq** [comment]
Please open a new PR on staging.

**Comment by tie** [comment]
Oops, sorry, forgot to rebase!

**Pull request closed without merging**
