### PR TITLE
xnbd: init at 0.4.0

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

It requires to mount network volumes on scaleway.com (including /-volume on baremetal servers, when ```xnbd-client``` is to be copied to initrd and [run in](https://github.com/scaleway/initrd/blob/51c564e6ac76c3be70622e6c92c6415732e063ec/Linux/tree-common/functions#L264) ```boot.initrd.preLVMCommands```).

Normal ```nbd``` does not work on scaleway (it shows errors about protocol mismatch).

Here are two commits "xnbd: init at 0.3.0" and "xnbd: 0.3.0 -> 0.4.0" to preserve working 0.3.0 derivation in the git history
The distros officially supported by scaleway.com (Ubuntu, etc) still use 0.3.0, so in case of possible issues with 0.4.0, the latter commit could be undone

### CODE REVIEW

**Comment by fpletz** [comment]
@GrahamcOfBorg build xnbd

**Comment by volth** [comment]
hm, it works for me (x86_64-linux)

**Comment by Mic92** [comment]
me too @GrahamcOfBorg build xnbd

**Comment by joachifm** [comment]
@GrahamcOfBorg build xnbd

**Comment by volth** [comment]
@GrahamcOfBorg build xnbd

**Pull request merged**
