### PR TITLE
nixpkgs: added gimp development version

### PR DESCRIPTION
**Pull request by flosse**

### CODE REVIEW

**Comment by flosse** [comment]
hmm...travis tells me that the sha256 hash is not correct but I can build it on my machine. Why?
`output path ‘/nix/store/j12nnmk68133mmc6z9j4bh9z261i244c-git-export’ should have r:sha256 hash ‘0llff710fbbpxwb4g1yp7pq2v6wqfdriilmsk930gh7cpa6mg33f’, instead has ‘06x919454v44w6vjakih9q014xzbnjh84db5lgrqqzsr9icg10bk’`

**Comment by flosse** [comment]
> All these packages shall not be built by hydra, we have only stable released packages

ok, I didn't know

> `meta.hydraPlatforms = []` should prevent building.

done :)

**Comment by bjornfor** [comment]
IMHO, we shouldn't have development versions of packages in nixpkgs at all (in general), even if not built by Hydra.

Who is this development version for? How often do you plan to update it?

**Comment by flosse** [comment]
> IMHO, we shouldn't have development versions of packages in nixpkgs at all (in general)

So where would be the right place to drop such packages?

> Who is this development version for?

I'd be glad if there were a place where I can find development packages. If s.o. already wrote an expression I don't unnecessarily have to loose time to write my own one.

Can we just keep them in a separate branch?

**Comment by bjornfor** [comment]
> So where would be the right place to drop such packages?

Anywhere but (upstream) nixpkgs? ;-)

> I'd be glad if there were a place where I can find development packages. If s.o. already wrote an
> expression I don't unnecessarily have to loose time to write my own one.

Some thoughts come to mind:

- Did you try using ```overrideDerivation```? I think it works well, very few lines needed to provide your own (exact) version of a package, given that the build system interface is mostly the same. There is usually no need to copy expressions, and you get to update exactly when you want (no need to create pull request, wait for channel updates...).

- What's the ultimate goal for development packages in nixpkgs? IMHO, nixpkgs is about packaging latest (stable) releases of all open source software. This is a big job. Also tracking git HEAD of "the world", in parallel, is just crazy (IMHO). (I know you just proposed to package *one* package, which is not crazy, but it's the principle.)

> Can we just keep them in a separate branch?

Slightly better, but I still think few people will use this and it will have a high chance of getting outdated quickly (people loose interest and don't clean up).

You could also make a fork of nixpkgs which contains only unreleased/development packages.

Or help gimp upstream to make releases that can be used in distros.

**Comment by 7c6f434c** [comment]
>> So where would be the right place to drop such packages?
>Anywhere but (upstream) nixpkgs? ;-)

You insist on making specifically upstream NixPkgs less useful and not
the reasonable only stop to get Nix expressions for free software?

>> I'd be glad if there were a place where I can find development packages. If s.o. already wrote an
>> expression I don't unnecessarily have to loose time to write my own one.
>
>Some thoughts come to mind:
>
>- Did you try using ```overrideDerivation```? I think it works well, very few lines needed to provide your own (exact) version of a package, given that the build system interface is mostly the same. There is usually no need to copy expressions, and you get to update exactly when you want (no need to create pull request, wait for channel updates...).
>
>- What's the ultimate goal for development packages in nixpkgs? IMHO, nixpkgs is about packaging latest (stable) releases of all open source software. This is a big job. Also tracking git HEAD of "the world", in parallel, is just crazy (IMHO). (I know you just proposed to package *one* package, which is not crazy, but it's the principle.)

NixPkgs doesn't look like being able to be about packaging latest stable
versions of all the software. NixPkgs seems to be about packaging the
versions someone cares about...

Because no, there is a ton of packages where latest versions are usually
ignored and rarely there is a special effort to get at least some
updates.

We easily give up and keep very old versions as default ones for 
relatively small reasons. Etc.

And yes, there are often good reasons to have a prerelease as an option
and there is often a prerelease as an option.

>> Can we just keep them in a separate branch?
>
>Slightly better, but I still think few people will use this and it will have a high chance of getting outdated quickly (people loose interest and don't clean up).

Wouldn't be so sure.

What would be the reason to use master, and not just merge master into
it? You get more options this way.

>You could also make a fork of nixpkgs which contains only unreleased/development packages.
>
>Or help gimp upstream to make releases that can be used in distros.

For example, by lowering the barrier to casually trying out 
prereleases...

**Comment by flosse** [comment]
>- Did you try using `overrideDerivation?` I think it works well, very few lines needed to provide your own (exact) version of a package, given that the build system interface is mostly the same.

no, that doesn't work. The stable nix expression uses precompiled files (e.g. `http://download.gimp.org/pub/gimp/v2.8/gimp-2.8.14.tar.bz2`) instead of source code.

> - What's the ultimate goal for development packages in nixpkgs?

I think there is no *ultimate goal*. I'd rather say everyone has its own goal ;-)

**Comment by bjornfor** [comment]
@7c6f434c: I don't "insist on making nixpkgs less useful [...]" (hey, that sounded like a really loaded question!). I just think having git HEAD snapshots in addition to latest stable releases is a bad idea in general. If we disagree then that's OK. I just wanted to share my opinion.

@flosse: Ok. I see. Maybe that can be solved by adding something extra to preConfigure?

Btw, if this is going to be merged, please use a "git describe"-like version number (base-version '-' number-of-commits-since-base-version, e.g. 1.2.3-101), so that the relation to the stable release is obvious. I don't think we want to se this when querying packages:

```
package-1.2.3
package-a53df89
```

Because there is no way of knowing what the 2nd package is, unless you have the git repo.

**Comment by bjornfor** [comment]
@flosse: I compared gimp expressions git.nix and 2.8.nix. So, you need to add a one-liner preConfigure and a couple of extra packages to buildInputs (autoconf etc.). Other than that, the expressions look the same. I don't see why that couldn't be a local expression using overrideDerivation. Then you could update your package at will! No need to wait for PR to be merged, channel to be updated etc.

Allright, enough of my opinions on this matter :-)

**Comment by 7c6f434c** [comment]
>@7c6f434c: I don't "insist on making nixpkgs less useful [...]" (hey, that sounded like a really loaded question!). I just think having git HEAD snapshots in addition to latest stable releases is a bad idea in general. If we disagree then that's OK. I just wanted to share my opinion.

Maybe it was not because of what you wrote, but just because you were
the first one to reply, but your explanation looked like you were 
describing a universal consensus, and I somewhat went overboard with the
opposite side of the everlasting arguments.

Sorry if I wrote something too loaded or too emotional.

>@flosse: Ok. I see. Maybe that can be solved by adding something extra to preConfigure?
>
>Btw, if this is going to be merged, please use a "git describe"-like version number (base-version '-' number-of-commits-since-base-version, e.g. 1.2.3-101), so that the relation to the stable release is obvious. I don't think we want to se this when querying packages:
>
>```
>package-1.2.3
>package-a53df89
>```
>
>Because there is no way of knowing what the 2nd package is, unless you have the git repo.

Yes, this is a good idea, thanks.

I usually try to mark it as a VCS version, and add a date of the
snapshot, but I probably like your idea better.

**Comment by 7c6f434c** [comment]
>@flosse: I compared gimp expressions git.nix and 2.8.nix. So, you need to add a one-liner preConfigure and a couple of extra packages to buildInputs (autoconf etc.). Other than that, the expressions look the same. I don't see why that couldn't be a local expression using overrideDerivation. Then you could update your package at will! No need to wait for PR to be merged, channel to be updated etc.
>
>Allright, enough of my opinions on this matter :-)

The most comfortable workflow is: have a git snapshot in NixPkgs, update
it monthly, do a src-only override of the git-snapshot expression.

Maybe it's unfortunate... I am not sure that there is a universal set of
overrides that allows to build at least 70% of autotools-based 
git-snapshots without further configuration.

**Comment by bjornfor** [comment]
@7c6f434c: Thanks for clearing that up :-)

**Comment by flosse** [comment]
Thanks for your thoughts and time. Overall I think we shouldn't merge dev versions into the master branch but keeping them separate in a dev branch. Nevertheless it seems to be too soon for this, so I'll close this PR. Hopefully the NixOS community will grow in the next few years so that there is enough power to maintain a dev branch :)

**Pull request closed without merging**
