### PR TITLE
arangodb: 3.3.19 -> 3.2.18, 3.3.23.1, 3.4.7, 3.5.0-rc.7

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

- [x] update version
- [x] follow all three branches (```3.2.x```, ```3.3.x``` and ```3.4.x```) currently supported by upstream (all the minor versions [are younger than 1 month](https://github.com/arangodb/arangodb/releases))

It depends on #59148 (it is used in a fork where #59148 is backported from)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc maintainer @flosse

### CODE REVIEW

**Comment by volth** [comment]
@GrahamcOfBorg build arangodb_3_2 arangodb_3_3 arangodb_3_4

**Comment by volth** [comment]
@GrahamcOfBorg build arangodb_3_2

**Comment by volth** [comment]
@GrahamcOfBorg build arangodb_3_3

**Comment by volth** [comment]
@GrahamcOfBorg build arangodb_3_4

**Comment by volth** [comment]
it does not work well, will reopen later

**Comment by volth** [comment]
Well, the problem (not specific to this PR, current ```arrangodb``` derivation is affected as well) is:
the binaries built on ```skylake``` does not start on ```sandybridge```.

Forcing comping for the oldest (anyway arbitarily chosen) of the architectures is undesirable for performance reason

I remember that the words "sandybridge", "haswell", "skylake" were in ```<nixpkgs/lib/systems/...>``` once and it was possible to specify the target architecture more precisely than "x86_64-linux".
Is the feature gone?

**Comment by volth** [comment]
@GrahamcOfBorg build arangodb_3_4
@GrahamcOfBorg build arangodb_3_3
@GrahamcOfBorg build arangodb_3_2

**Comment by volth** [comment]
@GrahamcOfBorg build arangodb_3_4
@GrahamcOfBorg build arangodb_3_3
@GrahamcOfBorg build arangodb_3_2

**Comment by volth** [comment]
@GrahamcOfBorg build arangodb_3_4
@GrahamcOfBorg build arangodb_3_3
@GrahamcOfBorg build arangodb_3_2
@GrahamcOfBorg build arangodb

**Comment by volth** [comment]
@GrahamcOfBorg build arangodb_3_5
@GrahamcOfBorg build arangodb_3_4
@GrahamcOfBorg build arangodb_3_3
@GrahamcOfBorg build arangodb_3_2

**Comment by aanderse** [comment]
@volth what is the status on this?

**Comment by volth** [comment]
> @volth what is the status on this?

it should be ok

**Comment by aanderse** [comment]
@volth What about the 3.5 build error?

**Comment by volth** [comment]
> @volth What about the 3.5 build error?

"timed out after 1800 seconds"

**Comment by aanderse** [comment]
Sorry, the `aarch64-linux` is simply marked as failure and the detailed log is no longer available so I couldn't see.

**Comment by volth** [comment]
> Sorry, the `aarch64-linux` is simply marked as failure and the detailed log is no longer available so I couldn't see.

It seems that 3.5.0 (at least `rc`-versions) are only for x86_64
`aarch64-linux` build fails with "fatal error: x86intrin.h: No such file or directory"
I adjusted `meta.platforms` and squashed commits.

**Comment by aanderse** [comment]
@GrahamcOfBorg build arangodb_3_5

**Comment by aanderse** [comment]
@volth 3.5 failed to build for me on NixOS with your branch.

**Comment by volth** [comment]
> @volth 3.5 failed to build for me on NixOS with your branch.

could you post the error ?
ofborg failed with "timed out after 3600 seconds".
it works for me, but I am with `gcc.arch="skylake"` which could make the difference

**Comment by aanderse** [comment]
Sure thing.

>   CXX(target) /build/source/build/3rdParty/V8/v7.1.302.28/x64.release/obj.target/v8_initializers/gen/torque-generated/builtins-array-from-dsl-gen.o
  CXX(target) /build/source/build/3rdParty/V8/v7.1.302.28/x64.release/obj.target/v8_initializers/gen/torque-generated/builtins-typed-array-from-dsl-gen.o
  CXX(target) /build/source/build/3rdParty/V8/v7.1.302.28/x64.release/obj.target/v8_nosnapshot/gen/libraries.o
  CXX(target) /build/source/build/3rdParty/V8/v7.1.302.28/x64.release/obj.target/v8_nosnapshot/gen/extras-libraries.o
  CXX(target) /build/source/build/3rdParty/V8/v7.1.302.28/x64.release/obj.target/v8_nosnapshot/src/snapshot/embedded-empty.o
  CXX(target) /build/source/build/3rdParty/V8/v7.1.302.28/x64.release/obj.target/v8_nosnapshot/gen/experimental-extras-libraries.o
  CXX(target) /build/source/build/3rdParty/V8/v7.1.302.28/x64.release/obj.target/v8_nosnapshot/src/snapshot/snapshot-empty.o
  AR(target) /build/source/build/3rdParty/V8/v7.1.302.28/x64.release/obj.target/gypfiles/libv8_init.a
  CXX(target) /build/source/build/3rdParty/V8/v7.1.302.28/x64.release/obj.target/v8_initializers/src/builtins/x64/builtins-x64.o
  CXX(target) /build/source/build/3rdParty/V8/v7.1.302.28/x64.release/obj.target/v8_initializers/gen/torque-generated/builtins-data-view-from-dsl-gen.o
  AR(target) /build/source/build/3rdParty/V8/v7.1.302.28/x64.release/obj.target/gypfiles/libv8_nosnapshot.a
  AR(target) /build/source/build/3rdParty/V8/v7.1.302.28/x64.release/obj.target/gypfiles/libv8_initializers.a
[ 38%] No install step for 'v8_build'
[ 38%] Completed 'v8_build'
[ 38%] Built target v8_build
make: *** [Makefile:152: all] Error 2
builder for '/nix/store/yzkqyss3lfhmi061g057xcj0kasbwkmk-arangodb-3.5.0-rc.7.drv' failed with exit code 2
error: build of '/nix/store/yzkqyss3lfhmi061g057xcj0kasbwkmk-arangodb-3.5.0-rc.7.drv' failed

Please let me know anything else I can do to assist.

**Comment by volth** [comment]
try now, it should also fix aarch64

**Comment by aanderse** [comment]
`3.5` builds on my machine now :+1:

**Pull request merged**
