### PR TITLE
pcre: 8.38 -> 8.39

### PR DESCRIPTION
**Pull request by RamKromberg**
###### Motivation for this change

maintenance.
passed internal tests.
patch not necessary anymore.

added devdoc to outputs.

### CODE REVIEW

**Comment by vcunat** [comment]
This will need to go through staging.

**Comment by RamKromberg** [comment]
@vcunat I figured as much :/

**Comment by fpletz** [comment]
Sorry, pushed a commit like this to staging (https://github.com/NixOS/nixpkgs/commit/6244be2d0a07778b51eb4ff41f5ecefc187b54a8) as part of https://github.com/NixOS/nixpkgs/issues/18856.

**Comment by RamKromberg** [comment]
Sorry for what? It got done. Thanks :)

**Pull request closed without merging**
