### PR TITLE
marathon: 1.3.6 -> 1.4.1

### PR DESCRIPTION
**Pull request by pradeepchhetri**
###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by pSub** [comment]
It seems some tests are failing on travis.

**Comment by pradeepchhetri** [comment]
I am having a look at it. Thanks.

**Comment by rycee** [comment]
This seems like a more general error with building the Python bindings for Protobuf 2.6. So no program depending on this version will build OK. For example `nix-build -A pythonPackages.ddar` will result in the same error as shown in travis.

Unfortunately current Mesos doesn't work with newer protobuf versions, apparently it will in an upcoming release (maybe 1.3.0?), see [MESOS-5186](https://issues.apache.org/jira/browse/MESOS-5186) and [MESOS-6138](https://issues.apache.org/jira/browse/MESOS-6138).

**Comment by rycee** [comment]
I tried applying #22061 and then build this. That worked quite well both Mesos and Marathon built successfully.

**Comment by pradeepchhetri** [comment]
So I guess we can merge this once #22061 gets merged into master ?

**Comment by rycee** [comment]
Yeah, I would be in favor of that.

**Comment by kamilchm** [comment]
https://github.com/mesosphere/marathon/releases/tag/v1.4.1

**Comment by grahamc** [comment]
That PR has been merged. @rycee can you take another look?

**Review by grahamc — APPROVED** [review]

**Pull request merged**
