### PR TITLE
rustscan: 1.8.0 -> 1.10.1

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Motivation for this change

Keep things up to date.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NieDzejkob** [comment]
Fails to build on NixOS. This seems to be because one of the tests got split. I am currently testing this change:

```suggestion
-    "--skip=parse_correct_ips_or_hosts"
+    "--skip=parse_correct_host_addresses"
```

**Comment by NieDzejkob** [comment]
With the above changes, the package builds and runs fine on NixOS.

**Comment by SuperSandro2000** [comment]
Changed.

I built it locally and nothing failed. Are the tests more strict on nixOS compared to nix? And why is graham green if the tests fail in nixOS? I am a bit confused right now. Can you maybe clear this up or reference some documentation about this?

**Comment by NieDzejkob** [comment]
Perhaps the sandbox is off by default on foreign distributions? Also, I had the impression that the CI hooked up to GitHub PRs only checks whether the derivations instantiate without errors...

**Comment by SuperSandro2000** [comment]
Sandbox is disabled on Debian and Ubuntu because it sometimes causes really strange errors when building certain packages. Not ideal for package maintenance but I try to keep it in mind and maybe change that in the future.

**Comment by SuperSandro2000** [comment]
@NieDzejkob Could you maybe take another look if it still builds on nixOS? (I should setup some VM...)

**Comment by NieDzejkob** [comment]
On Tue Sep 29, 2020 at 2:16 PM CEST, Sandro wrote:
> @NieDzejkob Could you maybe take another look if it still builds/passes
> tests on nixOS? (I should setup some VM...)

you could also try enabling the sandbox in your configuration file on
your machine. That should catch most issues ;)

I'll take a look at it later.

**Comment by SuperSandro2000** [comment]
> you could also try enabling the sandbox in your configuration file on your machine. That should catch most issues ;)

Then some nodePackages are not building.

**Comment by NieDzejkob** [comment]
`parse_correct_host_addresses` still fails in 1.10.1 when sandboxed due to the network being unavailable. Your latest commit shouldn't be removing that skip flag.

**Comment by SuperSandro2000** [comment]
I finally set up a Vagrant box to properly test with sandbox. :tada:

**Pull request merged**
