### PR TITLE
confd: 0.9.0 -> 0.11.0

### PR DESCRIPTION
**Pull request by ryantm**
Semi-automatic update. These checks were performed:

- built on NixOS
- found 0.11.0 in filename of file in /nix/store/fy2xdlmav7xg0qqb4v8ck8qw0g2krfvv-confd-0.11.0-bin

### CODE REVIEW

**Comment by ryantm** [comment]
@grahamc build confd

**Comment by grahamc** [comment]
@GrahamcOfBorg build confd

**Comment by adisbladis** [comment]
cc @kamilchm

**Comment by Mic92** [comment]
confd.bin does not contain any binary

**Comment by kamilchm** [comment]
Why not 0.15 https://github.com/kelseyhightower/confd/releases/tag/v0.15.0 ?

**Comment by ryantm** [comment]
@Profpatsch mentioned this https://twitter.com/Profpatsch/status/968454786310922240

**Comment by kamilchm** [comment]
How is `0.9 -> 0.11` different from `0.9 -> 0.15`? Both look like minor updates.
Besides of that I was never maintaining `confd`. I have extracted it from big old `goPackages`. It looks like it was added by @offlinehacker in https://github.com/NixOS/nixpkgs/pull/7563.
@offlinehacker can you review confd update?

**Comment by Mic92** [comment]
I can review this, when its ready. But at the moment there is still no binary in the build to review.

**Pull request closed without merging**
