### PR TITLE
wowup-cf: init at 2.12.0

### LINKED ISSUE #309135: Package request: WowUp
**Project description**
Open source addon manager for world of warcraft

**Metadata**

* homepage URL: https://wowup.io/
* source URL:https://github.com/WowUp/WowUp
* license: GPL V3
* platforms: unix, linux, darwin,

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by pbek**
## Description of changes

This will add the WowUp-CF AppImage application as a package. It is an add-on manager for World of Warcraft, including CurseForge support.

https://wowup.io/
https://github.com/WowUp/WowUp.CF

I picked up where #281635 by @Enoz left.

This would fix #309135.

I have it running and used it to download all my add-ons, they work fine in World of Warcraft.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by pbek** [comment]
@trevg22, maybe you want to test this?

**Comment by pbek** [comment]
I had to remove @enoz, since they are not in the nixpkgs maintainers list.

**Comment by trevg22** [comment]
Thank you for adding this, I dont mind testing. I am pretty new to nix, I have cloned your fork and was assuming I could create a nix-shell and use nix-build to test on my end?

**Comment by pbek** [comment]
Splendid! 😊
When you are in the cloned nixpkgs folder with my branch, this should do it:

```bash
nix-build -A wowup-cf
./result/bin/wowup-cf
```

**Comment by trevg22** [comment]
It is working for me on x86_64-linux, let me know if there is something else I can help with.

**Comment by pbek** [comment]
Great, thank you for testing!

I don't know what could speed up getting this PR into nixpkgs... I can't assign you as reviewer... You could just like this PR to signal that you want it too... ️🤷🏻

**Comment by pbek** [comment]
But @trevg22, I wonder... When you visit https://github.com/NixOS/nixpkgs/pull/310189/files, do you see a "Review" button on the right?

image

Do you see "Approve" there? Or is it greyed out?

**Review by trevg22 — APPROVED** [review]

**Comment by pbek** [comment]
So it does work. Good to know! Thank you!

**Comment by pbek** [comment]
Thank you, @wegank!

**Pull request merged**
