### PR TITLE
monero: 0.14.1.0 -> 0.15.0.0

### PR DESCRIPTION
**Pull request by prusnak**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @ehmry @rnhmjoj

### CODE REVIEW

**Comment by prusnak** [comment]
@GrahamcOfBorg build monero

**Comment by rnhmjoj** [comment]
Ok, monero looks all right but the GUI didn't build though. I'd rather update both package at the same time to avoid breaking monero-gui

**Review by rnhmjoj — APPROVED** [review]

**Comment by prusnak** [comment]
> Ok, monero looks all right but the GUI didn't build though.

Yeah, monero team is quite bad at delivering things that do build :D

**Review by ghost — APPROVED** [review]

**Comment by ehmry** [comment]
Merged at 84c44d8cafd909105a78bfcf191a0f6c7858c54d.

**Pull request closed without merging**
