### PR TITLE
tcl, tk: 8.6.11 -> 8.6.13

### PR DESCRIPTION
**Pull request by wegank**
###### Description of changes

Supersedes #163181.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wegank** [comment]
@ofborg eval

**Comment by wegank** [comment]
@ofborg eval

**Comment by wegank** [comment]
@ofborg build tcl tcl.passthru.tests tk tk.passthru.tests

**Comment by vcunat** [comment]
Uh, stdenv rebuild?  🤞🏽

**Comment by wegank** [comment]
I think something went wrong with this update, see issues #232089 and #232148.

@vcunat Could you please revert it in staging-next?

**Comment by wegank** [comment]
Wait, I'm confused, there is an easy solution for the Python one: `--set TK_LIBRARY ${tk}/lib/${tk.libPrefix}`...

**Comment by jchv** [comment]
Just for what it's worth, I don't _think_ that #232089 and #232148 are related. The dtdocbook/instant program in CDE seems to build and link properly, and it only really seems to fail due to some specific locale issue. It's perfectly able to link to Tcl 8.6 and the only reason I wind up overriding `TCLLIB` in #232148 is so I can get CDE to link to 8.5 instead to work around the issue. It's necessary because CDE hardcodes `-ltcl8.6` (but does still support 8.5 in version 2.3.2 as far as I can tell, having looked through the mailing list.)

There may be some overarching problem with this update that lead to #232148, but my personal suspicion is that it's actually a dependency update in Tcl that broke some old deprecated locales (maybe ones that are not ISO/IEC 2022 compliant, or perhaps otherwise just too archaic to keep supporting.) But, that's just my hunch, and I haven't had time to properly root-cause it yet.

Just wanted to make this note here to hopefully prevent any unnecessary confusion.

**Pull request merged**
