### PR TITLE
Support more than 99 nodes in NixOS tests & export toHex and toBase

### PR DESCRIPTION
**Pull request by basvandijk**
###### Motivation for this change

The current `zeroPad` function, which determines the MAC address of each QEMU VM in NixOS tests, returns a MAC address component in decimal notation while it should return it in hexadecimal. This means that you get inconsistent MAC addresses once you have 10 nodes or more. Worse: when you have 100 or more nodes the MAC address will look like `52:54:00:12:01:100` which is invalid.

###### Things done

This PR fixes the `zeroPad` function to return a proper hexadecimal component which means we can now have up to 254 nodes.

The implementation needed the `toHex` and `toBase` functions which have been added to the `lib` and come with unit tests.

Finally the `dhcpSimple` NixOS test from the `networking` test suite has been modified to give out fixed IP addresses (instead of a range) based on the MAC address.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by basvandijk** [comment]
@GrahamcOfBorg test networking

**Comment by basvandijk** [comment]
@GrahamcOfBorg test networking.dhcpSimple

**Comment by basvandijk** [comment]
@GrahamcOfBorg test networking.networkd
@GrahamcOfBorg test networking.scripted

**Comment by basvandijk** [comment]
@GrahamcOfBorg test networking.networkd
@GrahamcOfBorg test networking.scripted

**Comment by basvandijk** [comment]
@GrahamcOfBorg test networking.networkd.dhcpSimple
@GrahamcOfBorg test networking.scripted.dhcpSimple
@GrahamcOfBorg test networking.networkd.dhcpOneIf
@GrahamcOfBorg test networking.scripted.dhcpOneIf

**Comment by edolstra** [comment]
Maybe it's better to assert that there aren't more than 99 nodes? If you have that many nodes you have a big problem, since it's going to be superslow and take a huge amount of memory.

**Comment by arianvp** [comment]
No.  as Bas already noted this starts breaking at _10_ nodes; not _100_ without this fix. Adding an  assertion `< 100` will not be enough.

**Pull request merged**
