### PR TITLE
gnupg: fix build on darwin

### PR DESCRIPTION
**Pull request by lovek323**
Can't use libusb on darwin

### CODE REVIEW

**Comment by lovek323** [comment]
This build has failed trying to download something from hydra. I'm not sure how to re-run the build, but it should pass.

**Comment by lethalman** [comment]
Looks fine to me, why not just push?

**Comment by lovek323** [comment]
I am unaware of the process. It's been a while since I contributed anything, so I thought I should get some review before hand.

**Comment by gridaphobe** [comment]
The re-ordering of the `buildInputs` will cause a mass-rebuild of anything that depends on `gnupg`. It would be better to do

```
   buildInputs
     = [ readline zlib libgpgerror libgcrypt libassuan libksba pth openldap bzip2 ]
    ++ stdenv.lib.optional (!stdenv.isDarwin) libusb 
    ++ [ curl libiconv ];
```
even though it's ugly..

**Comment by wkennington** [comment]
Ehh, it's only a handful of packages 10-20 that are mailreaders and the likes so it's not a big deal.

**Comment by gridaphobe** [comment]
Ah true, I misread the giant list of packages to be fetched as to-be-built, and thought it was a mass-rebuild :)

**Comment by gridaphobe** [comment]
Looks good to me then, any objections to merging?

**Pull request merged**
