### PR TITLE
Tidy up: remove old Kdenlive and mlt-qt4

### PR DESCRIPTION
**Pull request by cillianderoiste**
Kdenlive is now a KDE project and is available as kde5.kdenlive

@viric is this OK with you?

### CODE REVIEW

**Comment by viric** [comment]
Sure, go on, go on!

Thank you for pushing things forward!

On Sun, Sep 13, 2015 at 04:52:35AM -0700, goibhniu wrote:
> Kdenlive is now a KDE project and is available as kde5.kdenlive
> 
> @viric is this OK with you?
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/NixOS/nixpkgs/pull/9837
> 
> -- Commit Summary --
> 
>   * Tidy up: remove old Kdenlive and mlt-qt4
> 
> -- File Changes --
> 
>     M pkgs/applications/kde-apps-15.04/default.nix (2)
>     D pkgs/applications/video/kdenlive/default.nix (38)
>     M pkgs/development/libraries/mlt/default.nix (4)
>     D pkgs/development/libraries/mlt/qt5.nix (39)
>     M pkgs/top-level/all-packages.nix (10)
> 
> -- Patch Links --
> 
> https://github.com/NixOS/nixpkgs/pull/9837.patch
> https://github.com/NixOS/nixpkgs/pull/9837.diff
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/NixOS/nixpkgs/pull/9837

-- 
(Escriu-me xifrat si saps PGP / Write ciphered if you know PGP)
PGP key D4831A8A - https://emailselfdefense.fsf.org/

**Comment by domenkozar** [comment]
+1

**Comment by cillianderoiste** [comment]
FTR, I haven't abandoned this, I tried to update the PR last weekend but ran into trouble. I'll have another shot soon.

**Comment by domenkozar** [comment]
I guess kde update broke this PR, is it still relevant?

**Comment by cillianderoiste** [comment]
I'll have another shot at this soon, but I'll close the PR for now since it's very outdated.

**Comment by viric** [comment]
About kdenlive... I don't know for 'master', but for '15.09' it is very hard to launch kde5.kdenlive without running kde, while it is quite easy with the kde4 app wrapper.

I also have yet to notice any difference between kde5.kdenlive and kde4.kdenlive. :)

**Comment by cillianderoiste** [comment]
I believe that kde5.kdenlive should work without kde, since the recent kde updates, so hopefully that's solved now.

**Pull request closed without merging**
