### PR TITLE
psi-plus: 0.16.575.639 -> 1.2.235

### PR DESCRIPTION
**Pull request by ryantm**
Semi-automatic update. These checks were performed:

- built on NixOS
- found 1.2.235 with grep in /nix/store/9z3lbwjmcvgxpicxnkqsqyn2bmkyqvsw-psi-plus-1.2.235

cc "@orivej"

### CODE REVIEW

**Comment by orivej** [comment]
This looks good, but this is not the most recent version, and psi-plus resources should be updated as well (e.g. https://github.com/psi-plus/psi-plus-snapshots/releases/tag/1.2.247 reminds to use `resources` at https://github.com/psi-plus/resources/commit/29029f6af9c2e3bacb539fdee5d59cc898cd074e).

**Comment by joachifm** [comment]
@ryantm do you intend to address @orivej's comments or should we just integrate this as-is and do the rest later.

**Comment by ryantm** [comment]
@joachifm I don't intend to address the comments, and I'm not sure if it is important they be updated in lock-step.

**Comment by joachifm** [comment]
Let's hope some brave soul running master will let us know :)

**Pull request merged**
