### PR TITLE
rustic: 0.7.0-unstable-2024-08-10 -> 0.8.0

### PR DESCRIPTION
**Pull request by emilylange**
## Description of changes

https://github.com/rustic-rs/rustic/releases/tag/v0.8.0

https://github.com/rustic-rs/rustic/blob/v0.8.0/CHANGELOG.md

diff: https://github.com/rustic-rs/rustic/compare/v0.7.0...v0.8.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NobbZ** [comment]
This fails to build for me, and in my draft I prepared yesterday (but didn't submit as I fell asleep) I had to add the following:

```
  preConfigure = ''
    export HOME=$(pwd)/.home
    mkdir -p $HOME
  '';
```

This is again not a nice solution, though sadly a necessity, as the lockfile refers to itself still as `0.7.0-dev`.

**Comment by emilylange** [comment]
This PR builds for me on `x86_64-linux` as is and I wouldn't have opened this PR if it wouldn't.
Additionally to `x86_64-linux`, ofborg is also able to successfully build this on `aarch64-linux`.

On what architecture are you experiencing the build issues you are describing?
Can you share logs?

Also I don't really understand the issue with the `Cargo.lock` referring to itself, `rustic-rs`, as `0.7.0-dev` while `Cargo.toml` reads `0.8.0`.

For embedding version information, e.g. used by `rustic --version`, the value from `Cargo.toml` is used.

```shell
# result/bin/rustic --version
rustic 0.8.0
```

I might be missing something here as well, so if you find the time, I would highly appreciate it if you can shed some light on what the issue with that is.

And finally, rather than vendoring the whole `Cargo.lock`, I would patch the single line.
But only if this turn out to be an issue.

**Comment by NobbZ** [comment]
I get the following error:

```
rustic> Executing cargoBuildHook
rustic> ++ env CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/lbk30k56awz9vz9qpid93fkjns0xwlhd-gcc-wrapper-13.3.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/lbk30k56awz9vz9qpid93fkjns0xwlhd-gcc-wrapper-13.3.0/bin/c++ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/lbk30k56awz9vz9qpid93fkjns0xwlhd-gcc-wrapper-13.3.0/bin/cc CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/lbk30k56awz9vz9qpid93fkjns0xwlhd-gcc-wrapper-13.3.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/lbk30k56awz9vz9qpid93fkjns0xwlhd-gcc-wrapper-13.3.0/bin/c++ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/lbk30k56awz9vz9qpid93fkjns0xwlhd-gcc-wrapper-13.3.0/bin/cc CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu HOST_CC=/nix/store/lbk30k56awz9vz9qpid93fkjns0xwlhd-gcc-wrapper-13.3.0/bin/cc HOST_CXX=/nix/store/lbk30k56awz9vz9qpid93fkjns0xwlhd-gcc-wrapper-13.3.0/bin/c++ cargo build -j 4 --target x86_64-unknown-linux-gnu --offline --profile release --no-default-features --features=tui,webdav
rustic> warning: `/build/.cargo/config` is deprecated in favor of `config.toml`
rustic> note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
rustic> warning: `/build/.cargo/config` is deprecated in favor of `config.toml`
rustic> note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
rustic> error: failed to acquire package cache lock
rustic> 
rustic> Caused by:
rustic>   failed to open: /proc/homeless-shelter/.cargo/.package-cache
rustic> 
rustic> Caused by:
rustic>   failed to create directory `/proc/homeless-shelter/.cargo`
rustic> 
rustic> Caused by:
rustic>   No such file or directory (os error 2)
```

This is true on `x86_64-linux` as well as `aarch64-linux` (binfmt emulation).

With the given snippet from my previous comment, rust will update the lockfiles self reference in the local cache and happily proceed.

Stale self-references in the lock file have been an annoyance in the past across different packages I had to deal with.

For reference:

```
$ nix --version
nix (Nix) 2.25.0pre20240820_af26fe3
```

**Comment by emilylange** [comment]
> ```
> $ nix --version
> nix (Nix) 2.25.0pre20240820_af26fe3`
> ```

Yeah, no, this is https://github.com/NixOS/nix/pull/11300 already causing regressions.

I am not willing to apply fixes for CppNix pre-release _"[Probably good to test and look around in Nixpkgs for anything that might depend on this](https://github.com/NixOS/nix/pull/11300#issuecomment-2297890362)"_-merged stuff.

This should be fixed at an entirely different level, not on a per-package basis.

Do whatever with this, closing.

**Comment by NobbZ** [comment]
I think it is a pity that you closed the PR, as I can not reopen it. (The following text was written under the impression I could, but realised on sending that I can't, as I'm on mobile I won't rephrase, I hope you excuse my laziness in that regard)

I prefer letting this hit the channel in a state that rises awareness of the regression, hoping it will be fixed quickly.

If this will indeed become the defacto standard with 2.25, we can always fix the drv and all the others.

Be assured, I am not happy how some things are handled in the development of what you call "CppNix", still I consider closing without discussing childish.

Yes I was not aware of this particular regression, so thanks for making me aware.

**Comment by NobbZ** [comment]
And a follow up PR has been created in #337535

**Pull request closed without merging**
