### PR TITLE
Update aws python packages: botocore, boto3, awscli, moto

### PR DESCRIPTION
**Pull request by thefloweringash**
###### Motivation for this change

Package update.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by thefloweringash** [comment]
The nix-review shows a lot of failures for this:

127 package failed to build:
aws-sam-cli buildbot buildbot-full buildbot-ui csvs-to-sqlite elasticsearch-curator nixops_1_6_1 poretools python27Packages.Quandl python27Packages.altair python27Packages.atomman python27Packages.awkward python27Packages.bkcharts python27Packages.bokeh python27Packages.celery python27Packages.csvs-to-sqlite python27Packages.cufflinks python27Packages.djmail python27Packages.drms python27Packages.fastparquet python27Packages.gensim python27Packages.geopandas python27Packages.google_cloud_bigquery python27Packages.google_cloud_monitoring python27Packages.histbook python27Packages.holoviews python27Packages.hvplot python27Packages.imbalanced-learn python27Packages.mapsplotlib python27Packages.moto python27Packages.pandas python27Packages.panel python27Packages.paperspace python27Packages.partd python27Packages.pvlib python27Packages.pyarrow python27Packages.pymatgen python27Packages.pytrends python27Packages.seaborn python27Packages.statsmodels python27Packages.sumo python27Packages.tablib python27Packages.trackpy python27Packages.uproot python27Packages.uproot-methods python27Packages.vega python27Packages.vega_datasets python27Packages.vidstab python37Packages.Quandl python37Packages.acoustics python37Packages.altair python37Packages.aplpy python37Packages.atomman python37Packages.awkward python37Packages.bkcharts python37Packages.blaze python37Packages.bokeh python37Packages.buildbot-plugins.console-view python37Packages.buildbot-plugins.grid-view python37Packages.buildbot-plugins.waterfall-view python37Packages.buildbot-plugins.wsgi-dashboards python37Packages.caffe python37Packages.celery python37Packages.cufflinks python37Packages.dask python37Packages.dask-glm python37Packages.dask-image python37Packages.dask-jobqueue python37Packages.dask-ml python37Packages.dask-mpi python37Packages.dask-xgboost python37Packages.datashader python37Packages.dftfit python37Packages.distributed python37Packages.djmail python37Packages.drms python37Packages.fastparquet python37Packages.geopandas python37Packages.glymur python37Packages.google_cloud_bigquery python37Packages.google_cloud_monitoring python37Packages.histbook python37Packages.holoviews python37Packages.hvplot python37Packages.ibis-framework python37Packages.image-match python37Packages.imbalanced-learn python37Packages.intake python37Packages.lammps-cython python37Packages.moto python37Packages.odo python37Packages.optuna python37Packages.osmnx python37Packages.pandas python37Packages.panel python37Packages.paperspace python37Packages.partd python37Packages.pims python37Packages.pvlib python37Packages.pyarrow python37Packages.pyfftw python37Packages.pymatgen python37Packages.pymatgen-lammps python37Packages.pymc3 python37Packages.pytrends python37Packages.rl-coach python37Packages.scikit-bio python37Packages.scikitimage python37Packages.seaborn python37Packages.slicedimage python37Packages.starfish python37Packages.statsmodels python37Packages.streamz python37Packages.stumpy python37Packages.sumo python37Packages.sunpy python37Packages.tablib python37Packages.trackpy python37Packages.uproot python37Packages.uproot-methods python37Packages.vega python37Packages.vega_datasets python37Packages.vidstab python37Packages.wrf-python python37Packages.xarray python37Packages.xgboost visidata

53 package were build:
aws-google-auth aws_shell awscli awsebcli awslogs credstash iceshelf luigi nixops nixopsUnstable python27Packages.PyLTI python27Packages.aws-adfs python27Packages.aws-sam-translator python27Packages.aws-xray-sdk python27Packages.boto3 python27Packages.botocore python27Packages.cartopy python27Packages.cfn-lint python27Packages.chalice python27Packages.credstash python27Packages.fiona python27Packages.flowlogs_reader python27Packages.fs-s3fs python27Packages.rasterio python27Packages.s3fs python27Packages.s3transfer python27Packages.scrapy python27Packages.serverlessrepo python27Packages.smart_open python27Packages.tiros python27Packages.warrant python37Packages.aws-adfs python37Packages.aws-sam-translator python37Packages.aws-xray-sdk python37Packages.boto3 python37Packages.botocore python37Packages.cartopy python37Packages.cfn-lint python37Packages.chalice python37Packages.fiona python37Packages.flowlogs_reader python37Packages.fs-s3fs python37Packages.gensim python37Packages.pynamodb python37Packages.rasterio python37Packages.s3fs python37Packages.s3transfer python37Packages.scrapy python37Packages.serverlessrepo python37Packages.smart_open python37Packages.tiros python37Packages.warrant s4cmd

**Comment by thefloweringash** [comment]
I think most of the failures in the above are caused by moto failing. I've reported the moto issue upstream as https://github.com/spulec/moto/issues/2371

**Comment by thefloweringash** [comment]
Everything that fails in the nix-review also fails for me in master.

**Comment by FRidh** [comment]
Thanks. Pushed to staging.

**Pull request closed without merging**
