### PR TITLE
[WIP] dateutil: 2.5.3 -> 2.6.0

### PR DESCRIPTION
**Pull request by vrthra**
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vrthra** [comment]
The commit `88144373a738fa3a88712cbd11c486c71e834f70` fails on `cairocffi` eventhough the commit should have been idempotent. Hence, `cairocffi` is broken.

**Comment by vrthra** [comment]
Fixing `cairoffi` seems to show that `capstone` is broken. Can I just mark these as broken and proceed with dateutil?

**Comment by FRidh** [comment]
@vrthra involve the maintainer and try to find a solution together

**Comment by 7c6f434c** [comment]
@vrthra is it OK to close this PR now that another version of the same update is merged?

**Comment by vrthra** [comment]
@7c6f434c Indeed, closing this one.

**Pull request closed without merging**
