### PR TITLE
privacyidea: 3.7.4 -> 3.8

### PR DESCRIPTION
**Pull request by Ma27**
###### Description of changes
ChangeLog: https://github.com/privacyidea/privacyidea/blob/v3.8/Changelog

__Note:__ the deploy originally failed with `(psycopg2.errors.DuplicateTable) relation "customuserattribute_seq" already exists`. I fixed that by running `drop sequence customuserattribute_seq` in postgresql. After looking at the source it shouldn't have existed before, so I suspect that I messed something up, but not sure, would be cool if somebody could double-check.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gbtb** [comment]
Hi. I'm currently trying to configure 2FA stack around privacyidea. I've used your branch to upgrade my test instance from 3.7.4 to 3.8 and can confirm, that the same error about customuserattribute_seq happens to me.

Btw, thank you for maintaining the package, it's really cool to be able to build whole auth solution in NixOS :+1:

**Comment by Ma27** [comment]
Thanks a lot for checking (even though that's not what I wanted to hear :sweat_smile: )!

Will investigate (and possibly file a bug upstream) soonish.
Btw, I worked around this by running `delete sequence customuserattribute_seq` and restarted the service. No guarantees though that this is the correct solution for that, you should make a backup before and check carefully if everything works fine for you.

**Comment by Ma27** [comment]
Opened https://github.com/privacyidea/privacyidea/issues/3447 for that.

Alternatively we could just patch the problematic migration script to skip the addition of the sequence in question (or skip it if it already exists).

For now a draft, don't expect activity from me here soon, will be on vacation starting tomorrow.

**Comment by Ma27** [comment]
DB migration problem is fixed, should be fine now.

**Pull request merged**
