### PR TITLE
[wip] vgc: init at unstable-2023-05-25

### LINKED ISSUE #233716: Package request: VGC
**Project description**

VGC is an upcoming suite of applications for graphic design and 2D animation, in which the lines and shapes you draw are connected to each others both in space and time, allowing for faster editing and inbetweening.

**Metadata**

* homepage URL: https://www.vgc.io
* source URL: https://github.com/vgc/vgc
* license: apache 2.0
* platforms: linux, darwin

### PR DESCRIPTION
**Pull request by AndersonTorres**
###### Description of changes

Trying to close  #233716
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
Next step: fill the third party dirs

**Comment by sOfTheApes** [comment]
Hey, it doesn't build. The log from trying to build it is [here](http://0x0.st/HbDG.txt).

**Comment by AndersonTorres** [comment]
Here is the things that need tpo be installed. However I don't know clearly how it can be done, given that
1. the installer does not work (it just throws a bunch of files to `$out`)
2. I do not know how the files inside `Release` interact with themselves

```
Release
Release/lib
Release/lib/libfmt.so.8.1.1
Release/lib/libfmt.so.8
Release/lib/libfmt.so
Release/lib/libvgccore.so
Release/lib/libvgcstyle.so
Release/lib/libvgcgeometry.so
Release/lib/libvgcvacomplex.so
Release/lib/libvgcgraphics.so
Release/lib/libvgcdom.so
Release/lib/libvgcworkspace.so
Release/lib/libvgcui.so
Release/lib/libvgccanvas.so
Release/lib/libvgctools.so
Release/lib/libvgcapp.so
Release/python
Release/python/vgc
Release/python/vgc/core.cpython-310-x86_64-linux-gnu.so
Release/python/vgc/style.cpython-310-x86_64-linux-gnu.so
Release/python/vgc/geometry.cpython-310-x86_64-linux-gnu.so
Release/python/vgc/graphics.cpython-310-x86_64-linux-gnu.so
Release/python/vgc/dom.cpython-310-x86_64-linux-gnu.so
Release/python/vgc/ui.cpython-310-x86_64-linux-gnu.so
Release/tests
Release/tests/vgc
Release/tests/vgc/core
Release/tests/vgc/geometry
Release/tests/vgc/graphics
Release/bin
Release/bin/vgc.conf
Release/bin/vgcillustration
Release/bin/vgcuitest
Release/resources
Release/resources/ui
Release/resources/ui/stylesheets
Release/resources/ui/stylesheets/default.vgcss
Release/resources/graphics
Release/resources/graphics/fonts
Release/resources/graphics/fonts/SourceSansPro
Release/resources/graphics/fonts/SourceSansPro/LICENSE.md
Release/resources/graphics/fonts/SourceSansPro/TTF
Release/resources/graphics/fonts/SourceSansPro/TTF/SourceSansPro-Regular.ttf
Release/resources/graphics/fonts/Roboto
Release/resources/graphics/fonts/Roboto/LICENSE.txt
Release/resources/graphics/fonts/Roboto/Roboto-Regular.ttf
Release/resources/graphics/fonts/Roboto/Roboto-Italic.ttf
Release/resources/graphics/fonts/Roboto/Roboto-BlackItalic.ttf
Release/resources/graphics/fonts/Roboto/Roboto-ThinItalic.ttf
Release/resources/graphics/fonts/Roboto/Roboto-Light.ttf
Release/resources/graphics/fonts/Roboto/Roboto-BoldItalic.ttf
Release/resources/graphics/fonts/Roboto/Roboto-Medium.ttf
Release/resources/graphics/fonts/Roboto/Roboto-MediumItalic.ttf
Release/resources/graphics/fonts/Roboto/Roboto-Bold.ttf
Release/resources/graphics/fonts/Roboto/Roboto-LightItalic.ttf
Release/resources/graphics/fonts/Roboto/Roboto-Thin.ttf
Release/resources/graphics/fonts/Roboto/Roboto-Black.ttf
Release/resources/graphics/shaders
Release/resources/graphics/shaders/opengl
Release/resources/graphics/shaders/opengl/shader.v.glsl
Release/resources/graphics/shaders/opengl/simple_textured.v.glsl
Release/resources/graphics/shaders/opengl/simple.v.glsl
Release/resources/graphics/shaders/opengl/simple_textured_debug.f.glsl
Release/resources/graphics/shaders/opengl/shader.f.glsl
Release/resources/graphics/shaders/opengl/screen_space_displacement.v.glsl
Release/resources/graphics/shaders/opengl/simple.f.glsl
Release/resources/graphics/shaders/opengl/simple_preview.f.glsl
Release/resources/graphics/shaders/opengl/simple_textured.f.glsl
Release/resources/graphics/shaders/d3d11
Release/resources/graphics/shaders/d3d11/screen_space_displacement.v.hlsl
Release/resources/graphics/shaders/d3d11/simple_textured_debug.f.hlsl
Release/resources/graphics/shaders/d3d11/simple_preview.f.hlsl
Release/resources/graphics/shaders/d3d11/simple.v.hlsl
Release/resources/graphics/shaders/d3d11/simple_textured.v.hlsl
Release/resources/graphics/shaders/d3d11/simple.f.hlsl
Release/resources/graphics/shaders/d3d11/simple_textured.f.hlsl
Release/resources/core
Release/resources/core/version.txt
Release/resources/apps
Release/resources/apps/illustration
Release/resources/apps/illustration/icons
Release/resources/apps/illustration/icons/512.png
Release/resources/apps/uitest
Release/resources/apps/uitest/icons
Release/resources/apps/uitest/icons/512.png
```

**Comment by sOfTheApes** [comment]
Is there any reason why we can't use VGC's normal packadging method of compiling an appimage and then wrap that appimage using appimageTools.wrapTypeX? The only problem I can think of is the fact that such a method would be highly silly.

**Pull request closed without merging**
