### PR TITLE
vmware-workstation: 17.0.0 -> 17.0.2

### LINKED ISSUE #250944: vmware-workstation 17 does not start under (X)Wayland
### Describe the bug
vmware-workstation does not start and complains about missing library dependencies.

### Steps To Reproduce
1. Apply this snippet:
```nix
{ pkgs, ... }:

{
  # Unfortunately, VMware remains the only easy way to interoperate with ESXi and have GPU accelerated graphics.
  virtualisation.vmware.host.enable = true;

  # VMware conflicts with KVM.
  boot.blacklistedKernelModules = [ "kvm" "kvmgt" "kvm_intel" "kvm_amd" ];

  # It doesn't work correctly with transparent hugepages.
  # OR IBT??
  boot.kernelParams = [ "transparent_hugepage=madvise" "ibt=off" ];
}
```
2. Try to launch VMware workstation.
3. BANG - vmware does not launch. Instead, it complains:
```
[AppLoader] Cannot get library dependencies. (4a)
[AppLoader] Fallback to use all shipped libraries.
``` 

No further logs, exits with code 1.

As far as I can tell from the strace logs, the relevant bit is this:
```
openat(AT_FDCWD, "/nix/store/i76xrlb3i3xkq9p05m5367ay4x223rg2-vmware-workstation-17.0.0/lib/vmware/lib", O_RDONLY|O_DIRECTORY) = 4
newfstatat(4, "libvmplayer.so", {st_mode=S_IFDIR|0555, st_size=28, ...}, 0) = 0
newfstatat(4, "libvmware-app-control.so", {st_mode=S_IFDIR|0555, st_size=48, ...}, 0) = 0
newfstatat(4, "libvmware-enter-serial.so", {st_mode=S_IFDIR|0555, st_size=50, ...}, 0) = 0
newfstatat(4, "libvmware-fuseUI.so", {st_mode=S_IFDIR|0555, st_size=38, ...}, 0) = 0
newfstatat(4, "libvmware-gksu.so", {st_mode=S_IFDIR|0555, st_size=64, ...}, 0) = 0
newfstatat(4, "libvmware-modconfig.so", {st_mode=S_IFDIR|0555, st_size=44, ...}, 0) = 0
newfstatat(4, "libvmware-netcfg.so", {st_mode=S_IFDIR|0555, st_size=38, ...}, 0) = 0
newfstatat(4, "libvmware-tray.so", {st_mode=S_IFDIR|0555, st_size=34, ...}, 0) = 0
newfstatat(4, "libvmware-zenity.so", {st_mode=S_IFDIR|0555, st_size=38, ...}, 0) = 0
newfstatat(4, "libvmware.so", {st_mode=S_IFDIR|0555, st_size=24, ...}, 0) = 0
newfstatat(4, "liblicenseTool.so", {st_mode=S_IFDIR|0555, st_size=34, ...}, 0) = 0
newfstatat(4, "libvmblock-fuse.so", 0x7ffeaf549f40, 0) = -1 ENOENT (No such file or directory)
newfstatat(4, "libvmware-modconfig-console.so", {st_mode=S_IFDIR|0555, st_size=60, ...}, 0) = 0
newfstatat(4, "libvmware-setup-helper.so", {st_mode=S_IFDIR|0555, st_size=50, ...}, 0) = 0
newfstatat(4, "libvmware-mount.so", {st_mode=S_IFDIR|0555, st_size=36, ...}, 0) = 0
newfstatat(4, "libvmware-vprobe.so", {st_mode=S_IFDIR|0555, st_size=38, ...}, 0) = 0
newfstatat(4, "libbasichttp.so", {st_mode=S_IFDIR|0555, st_size=30, ...}, 0) = 0
newfstatat(4, "libcds.so", {st_mode=S_IFDIR|0555, st_size=18, ...}, 0) = 0
newfstatat(4, "libgvmomi.so", {st_mode=S_IFDIR|0555, st_size=24, ...}, 0) = 0
newfstatat(4, "libvmwarebase.so", {st_mode=S_IFDIR|0555, st_size=32, ...}, 0) = 0
newfstatat(4, "libvmwareui.so", {st_mode=S_IFDIR|0555, st_size=28, ...}, 0) = 0
newfstatat(4, "libvnetlib.so", {st_mode=S_IFDIR|0555, st_size=26, ...}, 0) = 0
newfstatat(4, "libnfc-types.so", 0x7ffeaf549f40, 0) = -1 ENOENT (No such file or directory)
newfstatat(4, "libssoclient.so", 0x7ffeaf549f40, 0) = -1 ENOENT (No such file or directory)
newfstatat(4, "libvim-types.so", 0x7ffeaf549f40, 0) = -1 ENOENT (No such file or directory)
newfstatat(4, "libvmacore.so", 0x7ffeaf549f40, 0) = -1 ENOENT (No such file or directory)
newfstatat(4, "libvmomi.so", 0x7ffeaf549f40, 0) = -1 ENOENT (No such file or directory)
newfstatat(4, "diskLibWrapper.so", 0x7ffeaf549f40, 0) = -1 ENOENT (No such file or directory)
newfstatat(4, "libsvga3dsw.so", {st_mode=S_IFDIR|0555, st_size=28, ...}, 0) = 0
newfstatat(4, "libcrypto.so.1.1", {st_mode=S_IFDIR|0555, st_size=32, ...}, 0) = 0
newfstatat(4, "libcurl.so.4", {st_mode=S_IFDIR|0555, st_size=24, ...}, 0) = 0
newfstatat(4, "libssl.so.1.1", {st_mode=S_IFDIR|0555, st_size=26, ...}, 0) = 0
access("/nix/store/i76xrlb3i3xkq9p05m5367ay4x223rg2-vmware-workstation-17.0.0/lib/vmware/lib/libvmware.so/libvmware.so", F_OK) = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7facd5c36a10) = 97517
wait4(97517, [{WIFEXITED(s) && WEXITSTATUS(s) == 79}], 0, NULL) = 97517
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=97517, si_uid=1000, si_status=79, si_utime=0, si_stime=0} ---
write(3, "2023-08-23T09:33:23.915Z Er(02) "..., 123) = 123
write(3, "2023-08-23T09:33:23.915Z In(05) "..., 173) = 173
pipe2([5, 6], 0)                        = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7facd5c36a10) = 97518
write(3, "2023-08-23T09:33:23.916Z In(05) "..., 81) = 81
close(6)                                = 0
read(5, "", 1048575)                    = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=97518, si_uid=1000, si_status=2, si_utime=0, si_stime=0} ---
close(5)                                = 0
wait4(97518, [{WIFEXITED(s) && WEXITSTATUS(s) == 2}], 0, NULL) = 97518
write(3, "2023-08-23T09:33:23.916Z Er(02) "..., 74) = 74
write(2, "[AppLoader] Cannot get library d"..., 50[AppLoader] Cannot get library dependencies. (4a)
) = 50
write(3, "2023-08-23T09:33:23.916Z No(04) "..., 81) = 81
write(2, "[AppLoader] Fallback to use all "..., 51[AppLoader] Fallback to use all shipped libraries.
) = 51
```

So it is missing at least:
- `libvmblock-fuse.so`
  - there is a `libvmware-vmblock-fuse.so` in the `$out/lib/vmware/lib` folder.
- `libnfc-types.so`
  - Just plain missing.
- `libssoclient.so`, `libvim-types.so`, `ibvmacore.so` and `libvmomi.so` 
  - They are in the ovftool component - `$out/lib/vmware-ovftool`
- `diskLibWrapper.so`
  - No idea where it comes from.

### Expected behavior
VMware Workstation launches.

### Additional context
I am running Hyprland (Wayland), but with Xwayland configured.

### Notify maintainers

@cawilliamson @deinferno @WolfangAukang (You fixed a missing dependency last)

### Metadata
```console
vifino@snip> nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.7-zen1, NixOS, 23.11 (Tapir), 23.11.20230821.91a22f7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

### PR DESCRIPTION
**Pull request by vifino**
## Description of changes
Just a small bump.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gepbird** [comment]
Result of `nixpkgs-review pr 251536` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

<details><summary>8 packages marked as broken and skipped:</summary><ul>
  <li>linuxKernel.packages.hardkernel_4_14.vmware</li>
  <li>linuxKernel.packages.linux_4_14_hardened.vmware</li>
  <li>linuxKernel.packages.linux_4_19_hardened.vmware</li>
  <li>linuxKernel.packages.linux_5_4_hardened.vmware</li>
  <li>linuxPackages_4_14_hardened.vmware</li>
  <li>linuxPackages_4_19_hardened.vmware</li>
  <li>linuxPackages_5_4_hardened.vmware</li>
  <li>linuxPackages_hardkernel_latest.vmware</li>
</ul></details>
<details><summary>5 packages failed to build:</summary><ul>
  <li>linuxPackages_latest.vmware</li>
  <li>linuxPackages_6_4_hardened.vmware</li>
  <li>linuxPackages_latest-libre.vmware</li>
  <li>linuxPackages_testing_bcachefs.vmware</li>
  <li>linuxPackages_xanmod_latest.vmware</li>
</ul></details>

**Comment by vifino** [comment]
@gepbird That looks suspicious to me - why did it fail?
It works just fine for me.

**Comment by gepbird** [comment]
> @gepbird That looks suspicious to me - why did it fail? It works just fine for me.


After cloning nixpkgs on the master branch, (running nixpkgs-review on some other PRs) then running it on this PR it gives me these errors:
```
error: builder for '/nix/store/iiy3f6j5cfk7bpglxsgk3zirzcqxmg3f-vmware-modules-17.0.2-6.4.12.drv' failed with exit code 2;
       last 10 log lines:
       >   LD [M]  /build/source/vmmon-only/vmmon.ko
       >   BTF [M] /build/source/vmmon-only/vmmon.ko
       > Skipping BTF generation for /build/source/vmmon-only/vmmon.ko due to unavailability of vmlinux
       > make -C $PWD SRCROOT=$PWD/. \
       >   MODULEBUILDDIR= postbuild
       > make[2]: Entering directory '/build/source/vmmon-only'
       > make[2]: 'postbuild' is up to date.
       > make[2]: Leaving directory '/build/source/vmmon-only'
       > cp -f vmmon.ko ./../vmmon.o
       > make[1]: Leaving directory '/build/source/vmmon-only'
       For full logs, run 'nix log /nix/store/iiy3f6j5cfk7bpglxsgk3zirzcqxmg3f-vmware-modules-17.0.2-6.4.12.drv'.
error: builder for '/nix/store/d2qjy1hxqasgn82c3i2ymg6clcsg8q23-vmware-modules-17.0.2-6.4.11.drv' failed with exit code 2;
       last 10 log lines:
       >   LD [M]  /build/source/vmmon-only/vmmon.ko
       >   BTF [M] /build/source/vmmon-only/vmmon.ko
       > Skipping BTF generation for /build/source/vmmon-only/vmmon.ko due to unavailability of vmlinux
       > make -C $PWD SRCROOT=$PWD/. \
       >   MODULEBUILDDIR= postbuild
       > make[2]: Entering directory '/build/source/vmmon-only'
       > make[2]: 'postbuild' is up to date.
       > make[2]: Leaving directory '/build/source/vmmon-only'
       > cp -f vmmon.ko ./../vmmon.o
       > make[1]: Leaving directory '/build/source/vmmon-only'
       For full logs, run 'nix log /nix/store/d2qjy1hxqasgn82c3i2ymg6clcsg8q23-vmware-modules-17.0.2-6.4.11.drv'.
error: builder for '/nix/store/hbj954ziacrrkpzi8n0r1lfag1l9bw14-vmware-modules-17.0.2-6.4.11.drv' failed with exit code 2;
       last 10 log lines:
       >   MODPOST /build/source/vmmon-only/Module.symvers
       >   CC [M]  /build/source/vmmon-only/vmmon.mod.o
       >   LD [M]  /build/source/vmmon-only/vmmon.ko
       > make -C $PWD SRCROOT=$PWD/. \
       >   MODULEBUILDDIR= postbuild
       > make[2]: Entering directory '/build/source/vmmon-only'
       > make[2]: 'postbuild' is up to date.
       > make[2]: Leaving directory '/build/source/vmmon-only'
       > cp -f vmmon.ko ./../vmmon.o
       > make[1]: Leaving directory '/build/source/vmmon-only'
       For full logs, run 'nix log /nix/store/hbj954ziacrrkpzi8n0r1lfag1l9bw14-vmware-modules-17.0.2-6.4.11.drv'.
error: builder for '/nix/store/lhqdppqns3v1wgy7fcpa9bcfsapcscs3-vmware-modules-17.0.2-6.4.12.drv' failed with exit code 2;
       last 10 log lines:
       >   LD [M]  /build/source/vmmon-only/vmmon.ko
       >   BTF [M] /build/source/vmmon-only/vmmon.ko
       > Skipping BTF generation for /build/source/vmmon-only/vmmon.ko due to unavailability of vmlinux
       > make -C $PWD SRCROOT=$PWD/. \
       >   MODULEBUILDDIR= postbuild
       > make[2]: Entering directory '/build/source/vmmon-only'
       > make[2]: 'postbuild' is up to date.
       > make[2]: Leaving directory '/build/source/vmmon-only'
       > cp -f vmmon.ko ./../vmmon.o
       > make[1]: Leaving directory '/build/source/vmmon-only'
       For full logs, run 'nix log /nix/store/lhqdppqns3v1wgy7fcpa9bcfsapcscs3-vmware-modules-17.0.2-6.4.12.drv'.
error: builder for '/nix/store/xsgx65kkvyziq3xh35xgcyx7l7dc5sr1-vmware-modules-17.0.2-6.4.12.drv' failed with exit code 2;
       last 10 log lines:
       >   LD [M]  /build/source/vmmon-only/vmmon.ko
       >   BTF [M] /build/source/vmmon-only/vmmon.ko
       > Skipping BTF generation for /build/source/vmmon-only/vmmon.ko due to unavailability of vmlinux
       > make -C $PWD SRCROOT=$PWD/. \
       >   MODULEBUILDDIR= postbuild
       > make[2]: Entering directory '/build/source/vmmon-only'
       > make[2]: 'postbuild' is up to date.
       > make[2]: Leaving directory '/build/source/vmmon-only'
       > cp -f vmmon.ko ./../vmmon.o
       > make[1]: Leaving directory '/build/source/vmmon-only'
       For full logs, run 'nix log /nix/store/xsgx65kkvyziq3xh35xgcyx7l7dc5sr1-vmware-modules-17.0.2-6.4.12.drv'.
error: 5 dependencies of derivation '/nix/store/ayqids3z8w3piqpn1fcn6ivkaxaj7q04-review-shell.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/251536

8 packages marked as broken and skipped:
linuxKernel.packages.hardkernel_4_14.vmware linuxKernel.packages.linux_4_14_hardened.vmware linuxKernel.packages.linux_4_19_hardened.vmware linuxKernel.packages.linux_5_4_hardened.vmware linuxPackages_4_14_hardened.vmware linuxPackages_4_19_hardened.vmware linuxPackages_5_4_hardened.vmware linuxPackages_hardkernel_latest.vmware

5 packages failed to build:
linuxPackages_latest.vmware linuxPackages_6_4_hardened.vmware linuxPackages_latest-libre.vmware linuxPackages_testing_bcachefs.vmware linuxPackages_xanmod_latest.vmware

14 packages built:
linuxKernel.packages.linux_4_14.vmware linuxKernel.packages.linux_4_19.vmware linuxKernel.packages.linux_5_10.vmware linuxPackages_5_10_hardened.vmware linuxKernel.packages.linux_5_15.vmware linuxPackages_5_15_hardened.vmware linuxKernel.packages.linux_5_4.vmware linuxPackages.vmware linuxPackages_hardened.vmware linuxPackages-libre.vmware linuxPackages_lqx.vmware linuxPackages_xanmod.vmware linuxPackages_zen.vmware vmware-workstation

error: cannot find flake 'flake:None' in the flake registries
error: cannot find flake 'flake:None' in the flake registries
error: cannot find flake 'flake:None' in the flake registries
error: cannot find flake 'flake:None' in the flake registries
error: cannot find flake 'flake:None' in the flake registries
error: cannot find flake 'flake:None' in the flake registries
error: cannot find flake 'flake:None' in the flake registries
error: cannot find flake 'flake:None' in the flake registries
```

I'm not sure what `cannot find flake 'flake:None' in the flake registries` error means, is something wrong on my side?

**Comment by vifino** [comment]
@gepbird The log looks like the vmware modules built fine, so it is not a "traditional" build failure at least.

I haven't seen such an error message and it doesn't seem to be related to this, but I have no idea.

**Comment by WolfangAukang** [comment]
https://github.com/NixOS/nixpkgs/pull/251651 related

**Pull request merged**
