### PR TITLE
python3.pkgs.deprecated: build offline documentation

### PR DESCRIPTION
**Pull request by KAction**

### CODE REVIEW

**Comment by KAction** [comment]
@happysalada Can you please review this?

**Comment by KAction** [comment]
@SuperSandro2000 Can you please review this?

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by happysalada** [comment]
There are quite a lot of builds depending on this.
Did you test building a couple of things that depend on this ?
Just to make sure nothing is broken.
Did you verify the content of the output ? (just to make sure it isn't empty ).

**Comment by KAction** [comment]
Documentation is definitely non-empty:
```
>> nix-build -A python3.pkgs.deprecated.doc
/nix/store/jjv2ip4vgvpk2rq4xpk0x1w2xqqwjbgs-python3.10-deprecated-1.2.13-doc
nixpkgs on &patch/v1/python3.pkgs.deprecated on ☁  dbogatov@interfacefinancial.com(us-east4)
>> tree /nix/store/jjv2ip4vgvpk2rq4xpk0x1w2xqqwjbgs-python3.10-deprecated-1.2.13-doc
/nix/store/jjv2ip4vgvpk2rq4xpk0x1w2xqqwjbgs-python3.10-deprecated-1.2.13-doc
└── share
    └── doc
        └── python3.10-deprecated-1.2.13
            └── html
                ├── _images
                │   └── banner.png
                ├── _static
                │   ├── _sphinx_javascript_frameworks_compat.js
                │   ├── alabaster.css
                │   ├── banner.png
                │   ├── basic.css
                │   ├── custom.css
                │   ├── doctools.js
                │   ├── documentation_options.js
                │   ├── file.png
                │   ├── jquery-3.6.0.js
                │   ├── jquery.js
                │   ├── language_data.js
                │   ├── logo-full.png
                │   ├── minus.png
                │   ├── plus.png
                │   ├── pygments.css
                │   ├── searchtools.js
                │   ├── sphinx_highlight.js
                │   ├── title-page.jpg
                │   ├── underscore-1.13.1.js
                │   └── underscore.js
                ├── api.html
                ├── changelog.html
                ├── contributing.html
                ├── genindex.html
                ├── index.html
                ├── installation.html
                ├── introduction.html
                ├── license.html
                ├── objects.inv
                ├── py-modindex.html
                ├── search.html
                ├── searchindex.js
                ├── sphinx_deco.html
                ├── tutorial.html
                └── white_paper.html

6 directories, 36 files
```

Output definitely contains python code:

```
>> nix-build -A python3.pkgs.deprecated
/nix/store/vipw2sl6pxin7ndcdpki9q1v093lkb0w-python3.10-deprecated-1.2.13
nixpkgs on &patch/v1/python3.pkgs.deprecated on ☁  dbogatov@interfacefinancial.com(us-east4)
>> tree /nix/store/vipw2sl6pxin7ndcdpki9q1v093lkb0w-python3.10-deprecated-1.2.13
/nix/store/vipw2sl6pxin7ndcdpki9q1v093lkb0w-python3.10-deprecated-1.2.13
├── lib
│   └── python3.10
│       └── site-packages
│           ├── Deprecated-1.2.13.dist-info
│           │   ├── INSTALLER
│           │   ├── LICENSE.rst
│           │   ├── METADATA
│           │   ├── RECORD
│           │   ├── REQUESTED
│           │   ├── WHEEL
│           │   ├── direct_url.json
│           │   └── top_level.txt
│           └── deprecated
│               ├── __init__.py
│               ├── __pycache__
│               │   ├── __init__.cpython-310.pyc
│               │   ├── classic.cpython-310.pyc
│               │   └── sphinx.cpython-310.pyc
│               ├── classic.py
│               └── sphinx.py
└── nix-support
    └── propagated-build-inputs

7 directories, 15 files
```

Building `python3.pkgs.redis` and `python3.pkgs.pygithub`....

**Comment by KAction** [comment]
Yep, flit is broken on staging even without my patch:
```
error: builder for '/nix/store/1f3dbhybpyl45riys66s5kh33wcgj58p-python3.10-flit-3.8.0.drv' failed with exit code 1;
       last 10 log lines:
       > ------------------------------ Captured log call -------------------------------
       > WARNING  flit_core.versionno:versionno.py:124 Version number normalised: '0.03' -> '0.3' (see PEP 440)
       > WARNING  flit.validate:validate.py:127 Couldn't get list of valid classifiers to check against
       > =========================== short test summary info ============================
       > FAILED tests/test_install.py::InstallTests::test_install_data_dir - subprocess.CalledProcessError: Command '['/nix/store/02jdxqwwyx9sqqkm5zazfa...
       > FAILED tests/test_install.py::InstallTests::test_install_module_pep621 - subprocess.CalledProcessError: Command '['/nix/store/02jdxqwwyx9sqqkm5zazfa...
       > FAILED tests/test_install.py::InstallTests::test_symlink_data_dir - subprocess.CalledProcessError: Command '['/nix/store/02jdxqwwyx9sqqkm5zazfa...
       > FAILED tests/test_install.py::InstallTests::test_symlink_module_pep621 - subprocess.CalledProcessError: Command '['/nix/store/02jdxqwwyx9sqqkm5zazfa...
       > =========== 4 failed, 198 passed, 2 skipped, 1 deselected in 25.75s ============
       > /nix/store/2vi13sbn0iismhc1l0dzdyh4pn9n134i-stdenv-linux/setup: line 1594: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/1f3dbhybpyl45riys66s5kh33wcgj58p-python3.10-flit-3.8.0.drv'.
error: 1 dependencies of derivation '/nix/store/xl66dxm4n1y90ypizag9321sckpqa2dc-flit-build-hook.drv' failed to build
building '/nix/store/s4ga78mdhk0zhhbr05i1whpj6zy96fi0-python3.10-markdown-3.4.3.drv'...
building '/nix/store/kc5kk9x4v189868c0ik3kl1ll27wn2q9-python3.10-networkx-3.0.drv'...
error: 1 dependencies of derivation '/nix/store/yhfjg0mni6jp5yg6bcq2rkfjv9s9drf1-python3.10-sphinx-hoverxref-1.3.0.drv' failed to build
error (ignored): error: cannot unlink '/tmp/nix-build-cargo-c-0.9.13.drv-1/cargo-c-0.9.13+cargo-0.65.tar.gz/target/x86_64-unknown-linux-gnu/release/deps': Directory not empty
error (ignored): error: cannot unlink '/tmp/nix-build-boost-1.79.0.drv-2/boost_1_79_0/libs/numeric/ublas': Directory not empty
error (ignored): error: cannot unlink '/tmp/nix-build-gfortran-12.2.0.drv-1/gcc-12.2.0/gcc/testsuite': Directory not empty
error (ignored): error: cannot unlink '/tmp/nix-build-nettle-3.8.1.drv-0/nettle-3.8.1': Directory not empty
building '/nix/store/qwjv9m45lxpl566p2y81nhz48yiafajr-python3.10-sphinx-rtd-theme-1.2.0.drv'...
building '/nix/store/ag3j9x4gvdidb3vrc0vzy6gj50vkwsr4-python3.10-sqlparse-0.4.4.drv'...
building '/nix/store/irn6kcnp1bwfz3cslgz61xg7m3s92rkb-python3.10-tzdata-2022.7.drv'...
building '/nix/store/xi8pcjmwr28x01zd4f7hhqlrfxbyjsi0-python3.10-uharfbuzz-0.24.1.drv'...
building '/nix/store/zcfhdrw1c8ir7in4xm2csrh7cjkm545f-python3.10-wcwidth-0.2.6.drv'...
building '/nix/store/26cdsvxhvr5b0hl1531qq0va71x8r3lk-rayon-1.7.0.drv'...
building '/nix/store/cdwjj7ks5p7xzysnqr7fiaxbgqgf23hd-rayon-core-1.11.0.drv'...
building '/nix/store/34m9py2nidp9q97f04xvilr0ahfjy32w-rgb-0.8.36.drv'...
building '/nix/store/rc0ljjynpi508h8v32bb2h4hy81kbihf-scopeguard-1.1.0.drv'...
building '/nix/store/gazcn74kjnxwirch7yqx6r8bw4s5zyyh-source.drv'...
building '/nix/store/gmh98fvpiny9vcvv5rl610c0x224ixg9-source.drv'...
building '/nix/store/kvqcxy96ps3d2iqlacg7j2bzmsdn759q-source.drv'...
building '/nix/store/4whpijcr79y9nm42fvm7j3ksc2b60hpj-soxr-0.1.3.drv'...
error (ignored): error: cannot unlink '/tmp/nix-build-python3.10-uharfbuzz-0.24.1.drv-1/source/harfbuzz/test/shape/data/in-house/fonts': Directory not empty
error: 1 dependencies of derivation '/nix/store/c9lx3qn6hmm7vgllkzphn0bvcy4vwcr5-python3.10-hypothesis-6.68.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qnncpbx480kqr9w1gvln6cxqn8ih138h-python3.10-pynacl-1.5.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/89cgxqhx7a6vvf98xlvdppbhl437a1y5-python3.10-pygithub-1.58.0.drv' failed to build

```

**Comment by KAction** [comment]
And here is full log:

```
https://gist.github.com/KAction/3d0e9a2ce805d72ac1253e272e2ac4c2
```

**Comment by KAction** [comment]
UPD: Can't find any issue that would mention it. Flit on master is okay. Bisecting (will take a lot of cpu time)....

**Comment by KAction** [comment]
Okay, according to git-bisect first bad commit is 3d2bdd0788d7fa05883cafc1f8c2ab29527ef4f1.

Which kinda adds up. @zimbatm What is the plan? Just disable tests on flit?

**Comment by happysalada** [comment]
Ok its reasonable to merge this one then. Would you mind testing other packages as well on that other PR you did related to the docs ?

**Pull request merged**
