### PR TITLE
terraform-providers.sumologic: init at 0.2.1

### LINKED ISSUE #45699: Sumologic terraform provider
## Issue description
There is a new Terraform provider available: https://github.com/SumoLogic/sumologic-terraform-provider. It would be great to see this made available such that we can use it in NixOS as a Terraform plugin.

### PR DESCRIPTION
**Pull request by stephengroat**
###### Motivation for this change

closes #45699

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by srhb** [comment]
@GrahamcOfBorg build terraform-providers.sumologic

**Review by srhb — CHANGES_REQUESTED** [review]
Looks like there are some unresolved dependencies here. These need to be fixed first. :)

**Comment by stephengroat** [comment]
@srhb should be good to go now

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by stephengroat** [comment]
no time to work on getting `vendor` uploaded to the base provider

**Pull request closed without merging**
