### PR TITLE
Add kdeapps

### PR DESCRIPTION
**Pull request by freezeboy**
###### Motivation for this change

Continuing the process to make all applications in `applications/kde/srcs.nix`, I used the same technique as the previous PR:
 * one commit per lib/app
 * export user facing apps in `top-level/all-packages.nix`

A few notes:
 * I had to modify the `accounts-qt` package as the structure of the out was fooling cmake
 * I added signond as it contains the dbus information required for `kaccounts-integration` package, but didn't take care to enable a service for it
 * Dev apps (kdesdk, etc) are only in `kdeApplications` namespace

A few kde apps are still not packaged, three I didn't succeed yet (`cervisia`, `signon-kwallet-extension` and `artikulate`), `kopete` as it is obsolete upstream and all the telepathy stack

Maybe we should push this to staging ?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
@freezeboy your work is valuable, but I'm afraid it may not worth the maintainence effort to put all of these packagegs in our collection. Do you think you can add here only those that you personally would like to use?

**Comment by freezeboy** [comment]
What do you mean in "maintainance effort"? basically all the sources are updates in bulk with the srcs.nix file for kde, I just thought it was sad not to provide packages when it is just a matter of listing the deps of each app.

**Comment by doronbehar** [comment]
Listing the deps and maintaining them is the maintenance. Personally I do tend to think the more is the better, but @ttuegel 's approval might be needed for this. Let's hope he'll find time to review this.

**Comment by doronbehar** [comment]
20.08.2 is out in the meantime..

**Comment by doronbehar** [comment]
@freezeboy there are merge conflicts, and I'd post this PR in the "ready for review" thread.

**Comment by doronbehar** [comment]
It should be a rebase instead of a merge master into your branch. Also the commit messages should be `init at 20.08.2`. You don't have to separate all of them into separate commits IMO.

**Comment by eliasp** [comment]
I have 757661745c55c9b5a667c596b989c1ac16101327 which depends on this PR due to ce16b0a9280, ab4bda4c456 and 8e4c0493ed5

Feel free to pull 757661745c55c9b5a667c596b989c1ac16101327 into your PR, otherwise I'll wait for it to be merged to open a separate PR for it.

**Comment by doronbehar** [comment]
@eliasp  I think that if you have a smaller PR you'd like to open with less new packages, then don't wait for this one - it's too big to get in at anytime soon.

**Comment by eliasp** [comment]
@freezeboy FYI: 3 of your commits from this PR have been cherry-picked, slightly modified and are now merged to master via #107948, which makes those obsolete:
ce16b0a9280 → 73779ab8d4bf97c775d84d9511944c43fd053e1a
ab4bda4c456 → 0bc5689058dde8e219ce81356e7f890245529858
8e4c0493ed5 → eb6bdaa89b6619bc9d18dba2d696f542f2b1fbda

**Comment by freezeboy** [comment]
I rebased and removed the 3 obsolete files

**Comment by SuperSandro2000** [comment]
Closing due to inactivity from author.

**Pull request closed without merging**
