### PR TITLE
istioctl: maintainers: replace `veehaitch` with `superherointj`

### PR DESCRIPTION
**Pull request by veehaitch**
###### Description of changes

I don't have regular access to an Istio instance anymore. Therefore, I cannot really test the builds which probably doesn't make me a great maintainer.

I was hoping @superherointj could take on the job 🙂 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by superherointj** [comment]
I don't use Istio for the moment. I only proposed that patch because I've been checking Go packages with tests disabled that builds fine with tests enabled. (It happens that many many packages have actual tests working and are still disabled.) If I were more familiar with Istio, I could accept your request. But as it is now, I think, would be better if you could hang on for a while. Also it wasn't long since I dropped maintaining all packages (#144319), so I'd prefer to limit myself to packages I'm familiar with. I did buy an Istio book, I expect it to arrive soon, when the need of it becomes clearer for me, I may reconsider myself here. Thanks for considering me.

**Comment by veehaitch** [comment]
Guess we'll keep the status quo then. Thanks for the quick reply!

**Comment by superherointj** [comment]
@bryanasdev000 Are you actively using Istio? If yes, consider yourself to be a maintainer here.

**Comment by bryanasdev000** [comment]
@superherointj It really depends on what kind of work I'm doing at the moment, but it's interesting for me to have this package in nixpkgs.  If you wish, I can take over as maintainer.

**Comment by superherointj** [comment]
Add me as well then.

**Pull request closed without merging**
