### PR TITLE
sonobuoy: 0.56.14 -> 0.57.1

### PR DESCRIPTION
**Pull request by katexochen**
## Description of changes

https://github.com/vmware-tanzu/sonobuoy/compare/v0.56.14...v0.56.17
https://github.com/vmware-tanzu/sonobuoy/compare/v0.56.17...v0.57.1

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by wilsonehusin — APPROVED** [review]

**Comment by katexochen** [comment]
Not sure if we can backport the minor version bump or only the patch? The [changelog](https://github.com/vmware-tanzu/sonobuoy/releases/tag/v0.57.0) isn't really helpful..

**Comment by katexochen** [comment]
Regarding the `rev`, is there a specific reason we need to use the actual commit? Most package will just use `${src.rev}`, `none` or `unkown`. Not sure this is worth writing a custom update script.

**Comment by wilsonehusin** [comment]
> Not sure this is worth writing a custom update script.

yeah i think this might be worth updating upstream to read `vcs.revision` from `BuildInfo` instead of stamping with flags.

**Comment by katexochen** [comment]
> > Not sure this is worth writing a custom update script.
> 
> yeah i think this might be worth updating upstream to read `vcs.revision` from `BuildInfo` instead of stamping with flags.

Not sure I agree with this. From a reproducible builds point of view, version control information just don't belong into binaries.

**Comment by wilsonehusin** [comment]
> version control information just don't belong into binaries.

I don't think I follow the reasoning here, but from end user standpoint it's valuable information to know which commit the binary came from and it's rather common practice to have it in many Go builds.

**Comment by katexochen** [comment]
> > version control information just don't belong into binaries.
> 
> I don't think I follow the reasoning here, but from end user standpoint it's valuable information to know which commit the binary came from and it's rather common practice to have it in many Go builds.

The point I wanted to make is that when your binary is bit-by-bit reproducible, there is not much value in embedding a commit in addition to a version, it rather harms reproduciblility. For example, if you update the README of a project, the commit advances, but the binary stays exactly the same. For the user of the binary, it shouldn't matter whether it was built before or after changes to the README. However, if you embed the commit, the binary will change with every commit, no matter if that commit was meaningful to the binary or not. And that's a problem, for content-addressed nix and alike. But that's rather a general discussion and not really related to sonobuoy... ;)
 
 I've created https://github.com/NixOS/nixpkgs/pull/273307 which adds and update script to automate the rev update.

**Comment by katexochen** [comment]
> Not sure if we can backport the minor version bump or only the patch? The [changelog](https://github.com/vmware-tanzu/sonobuoy/releases/tag/v0.57.0) isn't really helpful..

@wilsonehusin what's your opinion on this one?

**Review by saschagrunert — APPROVED** [review]

**Comment by wilsonehusin** [comment]
> > Not sure if we can backport the minor version bump or only the patch? The [changelog](https://github.com/vmware-tanzu/sonobuoy/releases/tag/v0.57.0) isn't really helpful..
> 
> 
> 
> @wilsonehusin what's your opinion on this one?

I would follow what k8s / k3s backports are like, since internally Sonobuoy is (loosely) coupled with k8s API (via client-go)

**Comment by wilsonehusin** [comment]
P.S. thanks for doing this work — I will check with maintainers upstream on the commit sha thing

(I'm no longer employed by VMware, but let me try to put open some discussion with current maintainers)

**Review by l0b0 — APPROVED** [review]

**Pull request merged**
