### PR TITLE
meson: 1.1.1 -> 1.2.0

### PR DESCRIPTION
**Pull request by NickCao**
Release Note: https://mesonbuild.com/Release-notes-for-1-2-0.html
Diff: https://github.com/mesonbuild/meson/compare/1.1.1...1.2.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
Also built systemdMinimal.

**Comment by AndersonTorres** [comment]
@ofborg build systemdMinimal

**Review by AndersonTorres — APPROVED** [review]

**Comment by NickCao** [comment]
There seems to be some dependency failure on darwin.

**Comment by AndersonTorres** [comment]
> error: Package ‘systemd-minimal-253.6’ in /private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/macstadium-m1-44911104/pkgs/os-specific/linux/systemd/default.nix:752 is not available on the requested hostPlatform:

> hostPlatform.config = "aarch64-apple-darwin"

**Comment by NickCao** [comment]
Let's not block this for too long, build is succeeding on aarch64-darwin and we've already missed two staging-next cycles.

**Comment by AndersonTorres** [comment]
I am particularly bored about this situation...

**Comment by trofi** [comment]
Bisect says ce52bf9cc39c66850a399cb573b50bce809658c5 `meson: 1.1.1 -> 1.2.0` broke `gupnp` in `staging` as:

```
$ nix build --no-link -f. gupnp -L
...
gupnp> meson.build:1:0: ERROR: Unexpected "[provides]" section, did you mean "[provide]"?
```

**Comment by NickCao** [comment]
> Bisect says [ce52bf9](https://github.com/NixOS/nixpkgs/commit/ce52bf9cc39c66850a399cb573b50bce809658c5) `meson: 1.1.1 -> 1.2.0` broke `gupnp` in `staging` as:

quick fix:
```diff
--- a/pkgs/development/libraries/gupnp/default.nix
+++ b/pkgs/development/libraries/gupnp/default.nix
@@ -43,6 +43,10 @@ stdenv.mkDerivation rec {
     })
   ];

+  postPatch = ''
+    rm subprojects/gssdp-1.2.wrap
+  '';
+
   depsBuildBuild = [
     pkg-config
   ];
```

**Comment by uninsane** [comment]
see here for a gupnp fix that's closer to upstream: <https://github.com/NixOS/nixpkgs/pull/246931>

**Pull request merged**
