### PR TITLE
Merge staging-20.03 into release-20.03

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

Metrics job is failing on release-20.03 and staging-20.03, blocking any channel advance.
https://hydra.nixos.org/job/nixpkgs/staging-20.03/unstable#tabs-constituents

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
@mweinelt so there was nothing on staging-20.03 after all.

**Comment by vcunat** [comment]
The metrics job fails without exactly pointing to the source of the problem... but I don't think the job will block any channel.  It's certainly not included in the main channel's tested job: https://hydra.nixos.org/job/nixos/release-20.03/tested#tabs-constituents

**Comment by FRidh** [comment]
Oh right, I thought it was.

**Comment by vcunat** [comment]
It used to be at least in some channels, but it gets often broken (in some periods even that machine running it) and generally there doesn't seem to be that much motivation to keep it working.

**Pull request merged**
