### PR TITLE
physfs: 2.0.3 -> 3.0.1

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

New physfs breaks the API so keep v2 around as well.

Cc: @7c6f434c @viric 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by 7c6f434c — APPROVED** [review]

**Comment by Mic92** [comment]
@GrahamcOfBorg build vapor rebirth love

**Comment by Mic92** [comment]
@GrahamcOfBorg build vapor d2x_rebirth love

**Comment by Mic92** [comment]
The packages, I tried to build with the bot, did not build for me. I have not checked, if that was the case before.

**Comment by peterhoeg** [comment]
d2x-rebirth fails for me before this PR on amd64.

**Comment by peterhoeg** [comment]
@Mic92 - I updated and fixed d(1|2)x-rebirth as part of this.

**Pull request merged**
