### PR TITLE
Remove uses of libOnly

### PR DESCRIPTION
**Pull request by matthewbauer**
We failed to get any sort of consensus on #39515 so I am opening this spinoff PR that focuses on the worst overrides offenders. Basically, a few packages rely on this legacy "libOnly" flag that tells them to only build the "library" part of the package.

## What's wrong with libOnly

libOnly is an attempt to be more precise on what a package builds. The goal is to decrease closure size. Unfortunately, it's usage also means that you have to build each package twice - once for the libraries and another for the actual runtime (even though the runtime will still build the library). Since multiple outputs have been released, this is no longer the correct way to decrease closure size. Outputs like "lib" and "dev" should be used instead and mean you only have to build things once.

## Current offenders
- libpulseaudio
- libjack2
- libheimdal
- libkrb5
- libffado

## Backwards compatibility

This PR retains aliases for each of the libOnly overrides so old references to "libpulseaudio", and "libjack", etc. will continue to work.

### CODE REVIEW

**Comment by matthewbauer** [comment]
@GrahamcOfBorg eval

**Review by Ericson2314 — APPROVED** [review]
Excellent! Hopefully after these no-brainer split-outs we can get back to tackling the original problem.

**Comment by Ericson2314** [comment]
ugh this bootstrapping stuff is no fun. These days I'm not sure why we don't use the corepkg fetchurl more.

**Comment by dezgeg** [comment]
Something similar is being done in https://github.com/NixOS/nixpkgs/pull/38494, might want to coordinate to avoid duplicate work.

**Comment by matthewbauer** [comment]
Closing because #38494 is further along.

**Comment by oxij** [comment]
Oops, I got carried away and forgot that `Only` in `libOnly` means something different from my memory model, hence I should've used different terms.

What I wanted to say is I want derivations to become monoids. So, I think, `libOnly` should be split into `withBinaries` and `withLib` (or similar), because both are useful. (The rest of the previous comment is ok.)

Then, we can continue from the parent issue on the usage of `.override`s in derivation themselves for specifying features they expect from dependencies. Clearly, derivations with use-flags are monoids (`libOnly` is not a use-flag, while `withLib` and `withBinaries` are).

Hence, when nixpkgs finally implements use-flags we could make packages specify expected features of their dependencies and export that information, and then merge all those requests using `bool any` (see discussion in #37252) monoid (or something more interesting, if we want use-_options_ instead of use-_flags_) and build `pkgs` using that.

E.g., you gather all "use-flag requests" from packages in `systemPackages`, build use-flag specification, supply it to `pkgs`, now you have the perfect package set. Merge some "hydra-use-flags" into there, and now you only rebuild things that hydra didn't build.

Note that the gathering part is exactly isomorphic to `options + config` of NixOS modules, while the rest is exactly isomorphic to monoidal services (see the "Service composition" thread from 2014-12-26 on nix-dev ML by @esoeylemez and #35900).

**Pull request closed without merging**
