### PR TITLE
pysam: 0.15.3 -> 0.15.4 (and disabling tests)

### PR DESCRIPTION
**Pull request by unode**
This is a reopen of #80360

### CODE REVIEW

**Comment by unode** [comment]
@ofborg build python37Packages.pysam

**Comment by unode** [comment]
Tests have been disabled due to upstream test data incompatibilities with `samtools 1.10`.
See related issue: https://github.com/NixOS/nixpkgs/issues/79548 for additional discussion as well as https://github.com/pysam-developers/pysam/pull/890 

Tests are to be re-enabled once upstream issues are fixed.

**Review by jonringer — COMMENTED** [review]
I tried my hand at this as well, do you mind incorporating some of my adjustments (mostly the pythonImportsCheck and meta)

```
{ lib
, buildPythonPackage
, fetchFromGitHub
, bzip2
, bcftools
, curl
, cython
, htslib
, lzma
, pytest
, samtools
, zlib
}:

buildPythonPackage rec {
  pname   = "pysam";
  version = "0.15.4";

  # Fetching from GitHub instead of PyPi cause the 0.13 src release on PyPi is
  # missing some files which cause test failures.
  # Tracked at: https://github.com/pysam-developers/pysam/issues/616
  src = fetchFromGitHub {
    owner = "pysam-developers";
    repo = "pysam";
    rev = "v${version}";
    sha256 = "04w6h6mv6lsr74hj9gy4r2laifcbhgl2bjcr4r1l9r73xdd45mdy";
  };

  nativeBuildInputs = [ samtools ];
  buildInputs = [ bzip2 curl cython lzma zlib ];

  checkInputs = [ pytest bcftools htslib ];
  checkPhase = "py.test";

  # tests require samtools<=1.9
  doCheck = false;
  preCheck = ''
    export HOME=$(mktemp -d)
    make -C tests/pysam_data
    make -C tests/cbcf_data
  '';

  pythonImportsCheck = [
    "pysam"
    "pysam.bcftools"
    "pysam.libcutils"
    "pysam.libcvcf"
  ];

  meta = with lib; {
    description = "A python module for reading, manipulating and writing genome data sets";
    homepage = "https://pysam.readthedocs.io/";
    maintainers = with maintainers; [ unode ];
    license = licenses.mit;
    platforms = [ "i686-linux" "x86_64-linux" ];
  };
}
```

**Comment by unode** [comment]
@jonringer Thanks. Included your recipe.

**Comment by Infinisil** [comment]
Also backported to 20.03 in 07f20d062430419839fa195e6db97290fd3fed9d, which is fine since this is strictly a bugfix release: https://github.com/pysam-developers/pysam/releases/tag/v0.15.4

**Pull request merged**
