### PR TITLE
Revert "nixos/sway: add enableRealtime option"

### PR DESCRIPTION
**Pull request by kanashimia**
Reverts NixOS/nixpkgs#259066

### CODE REVIEW

**Review by thiagokokada — CHANGES_REQUESTED** [review]
I am in favor of:
- Removing the `default = true` from `enableRealtime` option
- Dropping the patch because it seems useless for now: https://github.com/NixOS/nixpkgs/pull/259066#issuecomment-1771212354

However I still think we should keep this option. So -1 for the way this PR is right now.

**Comment by kanashimia** [comment]
I see no point in keeping the option at all if it just randomly breaks some apps, better remove it so it doesn't end up in stable nixos some time later.
It seems more reasonable just to suggest setting pam limits in the wiki or something.

People are free to read this option again later if they actually make it work, although in my opinion benefit is questionable.

**Comment by thiagokokada** [comment]
> I see no point in keeping the option at all if it just randomly breaks some apps, better remove it so it doesn't end up in stable nixos some time later.
> It seems more reasonable just to suggest setting pam limits in the wiki or something.
> 
> People are free to read this option again later if they actually make it work, although in my opinion benefit is questionable. 

For a counter point, this is recommended by upstream and definitely improves latency in my system (especially after compiling lots of packages).

We should keep the option and improve later instead of removing it.

**Comment by thiagokokada** [comment]
Maybe just reimplement this option using PAM limits and keep disabled by default since I think people should at least understand the implications of raising the PAM limit level before applying.

**Comment by kanashimia** [comment]
On the other hand [gamescope module](https://github.com/NixOS/nixpkgs/blob/35d87899f7c8f6fad50447301465d51b5dd87753/nixos/modules/programs/gamescope.nix) uses similar nix wrappers infrastructure with it being disabled by default.

**Comment by thiagokokada** [comment]
> > For a counter point, this is recommended by upstream
> 
> Actually is it? Where? 

The PR that implements this talk about maintainers adding this to the package, and from what I see at least Arch is doing this by default.

> > We should keep the option and improve later instead of removing it.
> 
> We could just introduce it again if we actually figure how to "improve" it.
> I'm not against having something like this in the future.

I think we should do this right now instead of postponing this further. Release 1.8 (the one that implements this) is already a few months old.

> > Maybe just reimplement this option using PAM limits and keep disabled by default since I think people should at least understand the implications of raising the PAM limit level before applying.
> 
> Simply raising login limits for all users through the option also sounds questionable, looking at the only another module that sets limits for a group, [seems to be jack](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/audio/jack.nix), requiring a custom group doesn't look that good too.
> Plus need to figure out how would this be overridden by users.
> 
> Well, let's wait for more opinions. 

I would say keep this option and document the short comings. You don't have to worry about overriding if this is implemented as an option, because if it causes conflicts you just disable it.

**Comment by thiagokokada** [comment]
> On the other hand [gamescope module](https://github.com/NixOS/nixpkgs/blob/35d87899f7c8f6fad50447301465d51b5dd87753/nixos/modules/programs/gamescope.nix) uses similar nix wrappers infrastructure with it being disabled by default.

But I am advocating in disabling it by default, because I think the user should be aware of the possible issues.

I just think we should keep the option. We can always improve the implementation.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/265358

**Review by alyssais — APPROVED** [review]
I think this is the way to go for now.  It's become clear that the best way to do this is with PAM, which isn't Sway-specific, so we don't need the `enableRealtime` option.  Reverting this will get a fix out for people who have had JACK or SANE broken by this and don't understand why, and remove the time pressure to fix this properly.

**Review by Artturin — APPROVED** [review]

**Review by eclairevoyant — APPROVED** [review]

**Comment by eclairevoyant** [comment]
I will say, this was probably the most noticeable difference coming to NixOS from Arch, the lack of the `cap_sys_nice` capability on NixOS resulted in a noticeable perf drop in sway.

However, as is it doesn't work very well for us, and I agree with its removal for now until we get a better solution in place.

**Comment by Artturin** [comment]
Added the pam thing to the wiki https://nixos.wiki/wiki/Sway#Inferior_performance_compared_to_other_distributions

**Comment by Artturin** [comment]
Btw the cachyos rules for ananicy has

https://github.com/CachyOS/ananicy-rules/blob/8bfce840ae0db6f99c706c919ac61f3feff79db7/00-default/DEs-and-WMs/sway.rules#L2

https://github.com/CachyOS/ananicy-rules/blob/8bfce840ae0db6f99c706c919ac61f3feff79db7/00-types.types#L16-L18

**Comment by thiagokokada** [comment]
> Btw the cachyos rules for ananicy has
> 
> https://github.com/CachyOS/ananicy-rules/blob/8bfce840ae0db6f99c706c919ac61f3feff79db7/00-default/DEs-and-WMs/sway.rules#L2
> 
> https://github.com/CachyOS/ananicy-rules/blob/8bfce840ae0db6f99c706c919ac61f3feff79db7/00-types.types#L16-L18
> 

From what I understand setting nice is different from giving a process real time priority. While both can help with responsiveness, real time has more guarantees than just lowering nice levels.

**Review by thiagokokada — APPROVED** [review]
Still prefer to eventually get a proper solution, but I understand that having this breaking user setups is bad so we should revert for now.

**Pull request merged**
