### PR TITLE
lz4: 131 -> 1.8.2

### PR DESCRIPTION
**Pull request by bhipple**
Upgrades lz4 from version 131 (released 2015-06-29) to v1.8.2 (released 2018-05-07).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bhipple** [comment]
Hmm 501+ packages to rebuild.  Let me know if I should rebase onto `staging` instead.

**Comment by orivej** [comment]
This is very likely to break some packages (due to the changes in API). I think it should be approached like boost in https://github.com/NixOS/nixpkgs/pull/41258#issuecomment-393216626: wait for the current staging to complete and be merged to master, then merge this PR to staging. (A better workflow is under discussion at https://github.com/NixOS/rfcs/pull/26#issuecomment-392891246.)

**Comment by bhipple** [comment]
Ack, rebased my commit onto staging and changed the target branch.  Letting this sit until we're ready is fine by me.

**Comment by dtzWill** [comment]
This seems to have broken spice-- which is critical because it's on the path to qemu.  I'd link hydra but can't find it for whatever reason.

@GrahamcOfBorg build spice qemu

**Comment by orivej** [comment]
Yes, spice configure fails with:
```
configure:13873: $PKG_CONFIG --exists --print-errors "liblz4 >= 129"
Requested 'liblz4 >= 129' but version of lz4 is 1.8.2
You may find new versions of lz4 at http://www.lz4.org/
```
This is fixed in spice 0.14.0, I'm going to update it.

**Comment by orivej** [comment]
@dtzWill or would you like to reopen #37813?

**Comment by dtzWill** [comment]
FWIW: https://github.com/NixOS/nixpkgs/pull/37813 :)

**Pull request merged**
