### PR TITLE
Fix PHP APC pecl package name

### PR DESCRIPTION
**Pull request by katyo**
Fix for issue #7518

### CODE REVIEW

**Comment by pSub** [comment]
@jagajaga Why have you closed this PR? I guess we should either fix APC as long as we have php5.4 in nixpkgs or remove it.

**Comment by katyo** [comment]
I also agree with @pSub. We should not to have a broken packages. The APC compatible with php54, so I just fixed a pecl package name to make it installable.

**Comment by jagajaga** [comment]
@pSub I've closed because it wasn't built successfully.

**Comment by jagajaga** [comment]
@pSub and in the issue I've told why.

**Comment by pSub** [comment]
@jagajaga I haven't tried, but APC should compile fine with php5.4 (according to the links I have posted in the issue).

**Comment by jagajaga** [comment]
@pSub I've made a fix for a name and tried `nix-env -iA pkgs.phpPackages.apc`. Got https://github.com/NixOS/nixpkgs/issues/7518#issuecomment-95939211
I've done something wrong?

**Comment by pSub** [comment]
`phpPackages` refers (currently) to php version 5.6. I just realized that we don't have `php54Packages` anymore. Not sure what to do, as we do not build packages for 5.4 anymore and APC is obsolete for newer version we can delete it, I guess.
@katyo Do you need APC for php5.4?

**Comment by katyo** [comment]
Okay. I think what it hasn't critical for me now.

**Pull request closed without merging**
