### PR TITLE
rust-cbindgen: 0.6.3 -> 0.6.7

### PR DESCRIPTION
**Pull request by andir**
###### Motivation for this change

Updated rust-cbindgen since we will need a newer version for the upcoming firefox 64 release.

I am currently rebuilding firefox on one of my machines.

This will require backporting for future firefox updates.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

/cc @jtojnar 

---

### CODE REVIEW

**Comment by andir** [comment]
the firefox build failes with

```
stack backtrace:
   0:     0x7ffff764190e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h1298aff7c07c67ca
   1:     0x7ffff7654da2 - std::panicking::default_hook::{{closure}}::hb90d1cb6a98fd361
   2:     0x7ffff765433b - std::panicking::default_hook::h856803d056376eda
   3:     0x7ffff7655abc - std::panicking::rust_panic_with_hook::h480f4a14b65756a6
   4:     0x7ffff7655679 - std::panicking::continue_panic_fmt::h8c2ee3ce2bcded8d
   5:     0x7ffff76555dd - std::panicking::begin_panic_fmt::h0002fa8629b585ad
   6:     0x55555559c48b - build_script_build::build_gecko::bindings::write_binding_file::h8e44a113854fb068
   7:     0x55555559feb8 - build_script_build::build_gecko::bindings::generate_structs::h8d7e998605178f9f
   8:     0x7ffff7684919 - __rust_maybe_catch_panic
   9:     0x55555558fe6b - <F as alloc::boxed::FnBox<A>>::call_box::hb54273f07b0de208
  10:     0x7ffff764602a - std::sys_common::thread::start_thread::hebf8eedc34a4d3b4
  11:     0x7ffff7656845 - std::sys::unix::thread::Thread::new::thread_start::h65266df00b7a2b70
  12:     0x7ffff7bc05a6 - start_thread
  13:     0x7ffff6f1522e - __GI___clone
  14:                0x0 - <unknown>
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', libcore/result.rs:1009:5
stack backtrace:
   0:     0x7ffff764190e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h1298aff7c07c67ca
   1:     0x7ffff7654da2 - std::panicking::default_hook::{{closure}}::hb90d1cb6a98fd361
   2:     0x7ffff765433b - std::panicking::default_hook::h856803d056376eda
   3:     0x7ffff7655abc - std::panicking::rust_panic_with_hook::h480f4a14b65756a6
   4:     0x7ffff7655679 - std::panicking::continue_panic_fmt::h8c2ee3ce2bcded8d
   5:     0x7ffff7655575 - rust_begin_unwind
   6:     0x7ffff76ef53b - core::panicking::panic_fmt::h5ac035283b460341
   7:     0x55555558faea - core::result::unwrap_failed::he9ca5f2aa42bd9c6
   8:     0x5555555a5bf8 - build_script_build::main::hb7f27a533cf48842
   9:     0x555555589142 - std::rt::lang_start::{{closure}}::h5a39051669cce92e
  10:     0x7ffff7655512 - std::panicking::try::do_call::hd978816942bf1315
  11:     0x7ffff7684919 - __rust_maybe_catch_panic
  12:     0x7ffff766ed65 - std::rt::lang_start_internal::h00c3c4a30f67a2d3
  13:     0x5555555a5ff3 - main
  14:     0x7ffff6e44b8d - __libc_start_main
  15:     0x5555555845e9 - _start
                               at ../sysdeps/x86_64/start.S:120
  16:                0x0 - <unknown>
```

Will have a look later today.

**Comment by dywedir** [comment]
> the firefox build failes with
> 
> ```
> stack backtrace:
>    0:     0x7ffff764190e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h1298aff7c07c67ca
>    1:     0x7ffff7654da2 - std::panicking::default_hook::{{closure}}::hb90d1cb6a98fd361
>    2:     0x7ffff765433b - std::panicking::default_hook::h856803d056376eda
>    3:     0x7ffff7655abc - std::panicking::rust_panic_with_hook::h480f4a14b65756a6
>    4:     0x7ffff7655679 - std::panicking::continue_panic_fmt::h8c2ee3ce2bcded8d
>    5:     0x7ffff76555dd - std::panicking::begin_panic_fmt::h0002fa8629b585ad
>    6:     0x55555559c48b - build_script_build::build_gecko::bindings::write_binding_file::h8e44a113854fb068
>    7:     0x55555559feb8 - build_script_build::build_gecko::bindings::generate_structs::h8d7e998605178f9f
>    8:     0x7ffff7684919 - __rust_maybe_catch_panic
>    9:     0x55555558fe6b - <F as alloc::boxed::FnBox<A>>::call_box::hb54273f07b0de208
>   10:     0x7ffff764602a - std::sys_common::thread::start_thread::hebf8eedc34a4d3b4
>   11:     0x7ffff7656845 - std::sys::unix::thread::Thread::new::thread_start::h65266df00b7a2b70
>   12:     0x7ffff7bc05a6 - start_thread
>   13:     0x7ffff6f1522e - __GI___clone
>   14:                0x0 - <unknown>
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', libcore/result.rs:1009:5
> stack backtrace:
>    0:     0x7ffff764190e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h1298aff7c07c67ca
>    1:     0x7ffff7654da2 - std::panicking::default_hook::{{closure}}::hb90d1cb6a98fd361
>    2:     0x7ffff765433b - std::panicking::default_hook::h856803d056376eda
>    3:     0x7ffff7655abc - std::panicking::rust_panic_with_hook::h480f4a14b65756a6
>    4:     0x7ffff7655679 - std::panicking::continue_panic_fmt::h8c2ee3ce2bcded8d
>    5:     0x7ffff7655575 - rust_begin_unwind
>    6:     0x7ffff76ef53b - core::panicking::panic_fmt::h5ac035283b460341
>    7:     0x55555558faea - core::result::unwrap_failed::he9ca5f2aa42bd9c6
>    8:     0x5555555a5bf8 - build_script_build::main::hb7f27a533cf48842
>    9:     0x555555589142 - std::rt::lang_start::{{closure}}::h5a39051669cce92e
>   10:     0x7ffff7655512 - std::panicking::try::do_call::hd978816942bf1315
>   11:     0x7ffff7684919 - __rust_maybe_catch_panic
>   12:     0x7ffff766ed65 - std::rt::lang_start_internal::h00c3c4a30f67a2d3
>   13:     0x5555555a5ff3 - main
>   14:     0x7ffff6e44b8d - __libc_start_main
>   15:     0x5555555845e9 - _start
>                                at ../sysdeps/x86_64/start.S:120
>   16:                0x0 - <unknown>
> ```
> 
> Will have a look later today.

Probably related: https://aur.archlinux.org/cgit/aur.git/tree/0001-Keep-mozilla-release-building-with-newer-cbindgen-ve.patch

**Comment by andir** [comment]
@dywedir thanks for pointing me in the right direction. I picked the commit from the 63.0.3 release (pending) and applied it instead.

Running the rebuilds just now.

**Review by dywedir — APPROVED** [review]
Thank you!

**Comment by andir** [comment]
Rebuild succeeded. Looks good to me :-)

**Pull request merged**
