### PR TITLE
darwin backports

### PR DESCRIPTION
**Pull request by LnL7**
###### Motivation for this change

Various fixed merged to master since the branchoff. Most notably https://github.com/NixOS/nixpkgs/pull/97897 awhich fixes part of the last blocker for darwin-tested.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
ZHF: #97479

**Comment by risicle** [comment]
@ofborg build minio

looks like the only linux rebuild.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 98953 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>2 packages built:</summary>  <ul>    <li>bettercap</li>    <li>minio</li>  </ul></details>

**Comment by binarin** [comment]
Incomplete chromaprint change was picked, making it unbuildable on non-darwin. The one finally merged in https://github.com/NixOS/nixpkgs/pull/98057/files doesn't have this problem.

**Comment by LnL7** [comment]
Whoops, I only ran the builds on darwin since there where no conflicts.

**Pull request merged**
