### PR TITLE
nVidia Updates

### PR DESCRIPTION
**Pull request by fabianhjr**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nrdxp** [comment]
Result of `nixpkgs-review pr 150978` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11</li>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11_legacy470</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_legacy470</li>
  </ul>
</details>
<details>
  <summary>44 packages failed to build:</summary>
  <ul>
    <li>bumblebee</li>
    <li>geekbench</li>
    <li>gl-gsync-demo</li>
    <li>gwe</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_legacy470</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11 (linuxKernel.packages.linux_4_14_hardened.nvidia_x11)</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_4_14_hardened.nvidia_x11_legacy470)</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_legacy470</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11 (linuxKernel.packages.linux_4_19_hardened.nvidia_x11)</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_4_19_hardened.nvidia_x11_legacy470)</li>
    <li>linuxKernel.packages.linux_4_4.nvidia_x11</li>
    <li>linuxKernel.packages.linux_4_4.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_4_9.nvidia_x11_legacy470</li>
    <li>linuxPackages.nvidia_x11 (linuxKernel.packages.linux_5_10.nvidia_x11)</li>
    <li>linuxPackages.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_10.nvidia_x11_legacy470)</li>
    <li>linuxPackages_hardened.nvidia_x11 (linuxPackages_5_10_hardened.nvidia_x11)</li>
    <li>linuxPackages_hardened.nvidia_x11_legacy470 (linuxPackages_5_10_hardened.nvidia_x11_legacy470)</li>
    <li>linuxPackages_latest.nvidia_x11 (linuxKernel.packages.linux_5_15.nvidia_x11)</li>
    <li>linuxPackages_latest.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_15.nvidia_x11_legacy470)</li>
    <li>linuxPackages_5_15_hardened.nvidia_x11 (linuxKernel.packages.linux_5_15_hardened.nvidia_x11)</li>
    <li>linuxPackages_5_15_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_15_hardened.nvidia_x11_legacy470)</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_legacy470</li>
    <li>linuxPackages_5_4_hardened.nvidia_x11 (linuxKernel.packages.linux_5_4_hardened.nvidia_x11)</li>
    <li>linuxPackages_5_4_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_4_hardened.nvidia_x11_legacy470)</li>
    <li>linuxPackages_latest-libre.nvidia_x11 (linuxKernel.packages.linux_latest_libre.nvidia_x11)</li>
    <li>linuxPackages_latest-libre.nvidia_x11_legacy470 (linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy470)</li>
    <li>linuxPackages-libre.nvidia_x11 (linuxKernel.packages.linux_libre.nvidia_x11)</li>
    <li>linuxPackages-libre.nvidia_x11_legacy470 (linuxKernel.packages.linux_libre.nvidia_x11_legacy470)</li>
    <li>linuxPackages_lqx.nvidia_x11 (linuxKernel.packages.linux_lqx.nvidia_x11)</li>
    <li>linuxPackages_lqx.nvidia_x11_legacy470 (linuxKernel.packages.linux_lqx.nvidia_x11_legacy470)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11 (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_legacy470 (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy470)</li>
    <li>linuxPackages_xanmod.nvidia_x11 (linuxKernel.packages.linux_xanmod.nvidia_x11)</li>
    <li>linuxPackages_xanmod.nvidia_x11_legacy470 (linuxKernel.packages.linux_xanmod.nvidia_x11_legacy470)</li>
    <li>linuxPackages_zen.nvidia_x11 (linuxKernel.packages.linux_zen.nvidia_x11)</li>
    <li>linuxPackages_zen.nvidia_x11_legacy470 (linuxKernel.packages.linux_zen.nvidia_x11_legacy470)</li>
    <li>mangohud</li>
    <li>nvfancontrol</li>
    <li>primus</li>
    <li>psensor</li>
    <li>xpraWithNvenc</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_9.nvidia_x11</li>
  </ul>
</details>

**Comment by fabianhjr** [comment]
Hey @nrdxp, do you have some error logs?

I have been using one of the packages that failed to build without issues ( `linuxPackages_latest.nvidia_x11 (linuxKernel.packages.linux_5_15.nvidia_x11)` )

**Comment by nrdxp** [comment]
I seem to get spurious package failures with nixpkgs-review on a somewhat random basis. Just seeing a lot of this:
```
       last 10 log lines:
       > tar: ./nvidia-installer.1.gz: Cannot write: No space left on device
       > ./nvidia-settings.desktop
       > tar: ./nvidia-settings.desktop: Cannot write: No space left on device
       > ./mkprecompiled
       > tar: ./mkprecompiled: Cannot write: No space left on device
       > ./libnvidia-encode.so.470.94
       > tar: ./libnvidia-encode.so.470.94: Cannot write: No space left on device
       > ./libGLESv2_nvidia.so.470.94
       > tar: ./libGLESv2_nvidia.so.470.94: Cannot write: No space left on device
       > tar: Exiting with failure status due to previous errors
```

Looks like I was pretty high in ram usage due to the arc, and I usually run all my builds in a tmpfs so I think I ran out of space during this run. Sorry for false negative.

**Review by baracoder — APPROVED** [review]

**Pull request merged**
