### PR TITLE
nixUnstable: 2.4pre20201205_a5d85d0 -> 2.4pre20210308_1c0e3e4 

### PR DESCRIPTION
**Pull request by shlevy**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cole-h** [comment]
May be some relevant / related conversation in https://github.com/NixOS/nixpkgs/pull/109309.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 114786` at ff6a54d1 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/0a22f85c2fef1436bdf673eb312911eb">hydra-unstable</a></li></li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/cd8a7afdc19f488f586bdbf67436dc37">nix-update</a></li></li>
    <li><a href="https://gist.github.com/567c20af63462f6df737d74a42ec80da">nixFlakes</a></li> (nixUnstable)</li>
    <li><a href="https://gist.github.com/95fb9ba948e532847f9b86457cc93358">nixpkgs-review</a></li></li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/tools/package-management/nix/default.nix:203:16:
```
    |
203 |     patches = [(
    |                ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/tools/package-management/nix/default.nix:66:17:
```
   |
66 |                 ./aws-sdk-cpp-TransferManager-ContentEncoding.patch
   |                 ^
```
</li>
  </ul>
</details>

**Comment by shlevy** [comment]
Converting to draft pending the hydra issues and linked PR

**Comment by shlevy** [comment]
@edolstra Are there near term plans to make hydra build against nix master?

**Comment by jonringer** [comment]
My PR #109309 has been updated. I think this is slightly newer, but I'm also not breaking hydra

**Comment by jonringer** [comment]
for future reference, I just inspect the `flake.lock` in the hydra repo to see what it's using to build

**Comment by shlevy** [comment]
OK, now we bump hydra as well.

**Comment by Ma27** [comment]
@shlevy This appears to be a duplicate to #109309, right?

**Comment by shlevy** [comment]
@Ma27 It bumps nix further and hydra such that it can build against the most recent Nix without patches.

**Comment by Ma27** [comment]
@shlevy can you also backport this?

**Comment by shlevy** [comment]
@Ma27 This is a breaking change to Nix's interfaces... why do we need it backported?

**Comment by Ma27** [comment]
There are regularly bugfixes merged into `nixUnstable`, also this package is already named `unstable` (same applies for Hydra), which is why bumps were backported in the past already.

**Comment by shlevy** [comment]
No objection if someone wants to backport it.

**Comment by Ma27** [comment]
Currently preparing a backport PR.

**Comment by Pacman99** [comment]
I'm not sure if I should create an issue for this. This PR broke nixUnstable on aarch64-linux, because it adds libcpuid as a dependency which only supports x86.

**Comment by Mic92** [comment]
It would be great for important packages to also check ofborg!

**Comment by Mic92** [comment]
https://github.com/NixOS/nixpkgs/pull/116032

**Pull request merged**
