### PR TITLE
[Backport release-21.05] tdesktop: 2.7.5 -> 2.8.0 -> 2.8.1 -> 2.8.3 -> 2.8.4 -> 2.8.11

### PR DESCRIPTION
**Pull request by drupol**
This PR:

- [x] Is a backport of https://github.com/NixOS/nixpkgs/pull/128219
- [x] Does not include the changes from https://github.com/NixOS/nixpkgs/commit/e9e5f5f84dedea81605e493ea6cec41275a9a8fd (As I didn't know if those changes were supposed to be backported, I didn't included it and manually changed `alsa-lib` into `alsaLib` when cherry-picking commits.

For each cherry-picked commits, I had merge conflicts because of the change in the `alsaLib` name (_from `alsaLib` to `alsa-lib`_).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by drupol** [comment]
@primeos Hi, could you review this ?

**Comment by primeos** [comment]
@drupol as I noted in https://github.com/NixOS/nixpkgs/pull/128219#issuecomment-869049653 I still don't see a reason to backport this so we should document this (see also https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#backporting-changes: "4. When the reason to backport is not obvious from the original commit message, use git cherry-pick -xe <original commit> and add a reason.").

Our criteria are pretty lax (https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#criteria-for-backporting-changes) but usually we only backport security updates and patch releases.

And before merging this it also needs to be tested manually ("Tested execution of all binary files (usually in ./result/bin/)").

PS: https://github.com/NixOS/nixpkgs/commit/0d509d366d4fc692a9dc81366445e29da81202e6 was part of https://github.com/NixOS/nixpkgs/pull/128219 and not "directly committed to master without PR". I don't mind but just as a FYI ;)

**Comment by drupol** [comment]
> @drupol as I noted in [#128219 (comment)](https://github.com/NixOS/nixpkgs/pull/128219#issuecomment-869049653) I still don't see a reason to backport this so we should document this (see also https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#backporting-changes: "4. When the reason to backport is not obvious from the original commit message, use git cherry-pick -xe and add a reason.").

The sole reason why I'm backporting this is just to have Telegram 2.8.1 for `release-21.05`. I haven't backported any other changes (https://github.com/NixOS/nixpkgs/commit/e9e5f5f84dedea81605e493ea6cec41275a9a8fd).

> Our criteria are pretty lax (https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#criteria-for-backporting-changes) but usually we only backport security updates and patch releases.

Yep, I saw this yesterday. Apparently, bumping/updating packages is part of the criteria for backport, so, I don't see why this would not be allowed now. Or I misunderstand something?

> PS: [0d509d3](https://github.com/NixOS/nixpkgs/commit/0d509d366d4fc692a9dc81366445e29da81202e6) was part of #128219 and not "directly committed to master without PR". I don't mind but just as a FYI ;)

Oops, you're right, please accept my apologies for that! I will fix the description and remove the irrelevant part.

**Comment by primeos** [comment]
> The sole reason why I'm backporting this is just to have Telegram 2.8.1 for release-21.05.

We normally don't backport for that reason (at least AFAIK; it defies the point of a stable release a bit). I'll leave this up to other Nixpkgs maintainers that are more experienced with that (I usually only backport security fixes and important fixes).

> Apparently, bumping/updating packages is part of the criteria for backport, so, I don't see why this would not be allowed now.

Yes, it's certainly allowed. However, AFAIK we try to avoid bumping/updating packages without a good reason.
@NixOS/backports what do you think of this?

> Oops, you're right, please accept my apologies for that!

No problem, it was just a FYI ;)

**Comment by drupol** [comment]
I just finished the testing on my local computer and it works, compilation worked without any trouble.

Sadly bug https://github.com/NixOS/nixpkgs/issues/126285 is still there.

**Comment by ilya-fedin** [comment]
You can try to add `-DNDEBUG` to CXXFLAGS

**Comment by drupol** [comment]
I don't know if it's necessary, apparently there is a solution in #126285, I haven't tested it.

**Comment by ilya-fedin** [comment]
The solution in #126285 is a hack, setting NDEBUG is a more proper variant

**Comment by ilya-fedin** [comment]
(personally I would say let tdesktop to build bundled libtgvoip with tg_owt is the best variant)

**Comment by ilya-fedin** [comment]
2.8.2 and 2.8.3 only have rebuilt macos binaries

**Comment by SuperSandro2000** [comment]
Telegram is an online service. To use all their features you need to have the latest version of the program. Similar to spotify, discord, etc.

**Comment by ilya-fedin** [comment]
I mean 2.8.2 and 2.8.3 have no code changes, these releases have only updated macos binaries with crash fixes (by rebuilding third-party dependencies)

**Comment by drupol** [comment]
What's the status of this? Can we merge it?

**Comment by SuperSandro2000** [comment]
Does not build
```
ninja: error: 'cmake/external/jemalloc/jemalloc-prefix/src/jemalloc/lib/libjemalloc.a', needed by 'Telegram/codegen/codegen/lang/codegen_lang', missing and no known rule to make it
```

**Comment by drupol** [comment]
> Does not build
> 
> ```
> ninja: error: 'cmake/external/jemalloc/jemalloc-prefix/src/jemalloc/lib/libjemalloc.a', needed by 'Telegram/codegen/codegen/lang/codegen_lang', missing and no known rule to make it
> ```

Where do you see this?

**Comment by yu-re-ka** [comment]
This would fix https://github.com/NixOS/nixpkgs/issues/132159

**Comment by drupol** [comment]
Since https://github.com/NixOS/nixpkgs/pull/131322 (see the comments) I decided to not backport anything anymore and use unstable. I guess this can now be closed.

**Pull request closed without merging**
