### PR TITLE
emacs/agda2-mode: deprecate phases

### PR DESCRIPTION
**Pull request by Stunkymonkey**
###### Motivation for this change
compilation will be tested

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by veprbl — CHANGES_REQUESTED** [review]
```
building '/nix/store/pm1kl14bbfamy7n66bv34mxpq3b5ly63-emacs-agda-mode-2.6.2.drv'...
unpacking sources
variable $src or $srcs should point to the source
```

**Comment by Stunkymonkey** [comment]
could you please tell me how you tested this. I thought i tried it, but maybe I used the compiled version for the cache.

**Comment by veprbl** [comment]
@GrahamcOfBorg emacsPackages.agda2-mode

**Comment by veprbl** [comment]
@GrahamcOfBorg build emacsPackages.agda2-mode

**Pull request merged**
