### PR TITLE
[WIP]: lightdm-web-greeter (3.0.0rc2)

### PR DESCRIPTION
**Pull request by samueldr**
## Motivation for this change

This is PRed for visibility. I have seen a couple of times people ask about lightdm-web-greeter. This is not ready to merge, though it works. This will give a hand to anyone trying to use or contribute lightdm-web-greeter, as they are bound to find this PR.

#### Why 3.0.0rc2 and not stable 2.2.5?

[I did an initial try in the past, for the 2.x branch](https://github.com/samueldr/nixpkgs/tree/feature/lightdm-web-greeter). **It will not work with nixos.** It seems that there is a bug with the way webkitgtk is packaged for NixOS, and local files are not rendered as html, but as plain text. This [seems to also affect gnucash](https://github.com/NixOS/nixpkgs/issues/14105) and the same bug did affect midori's DOM inspector during at least 17.09's lifetime.

#### Why isn't this PR for 3.0.0rc2 finished?

Well, first thing first, the code quality for the module hasn't been reviewed; this is a port from a module I wrote about a year ago, which was basically a copy of the ligthdm-gtk-greeter module. I would also need to take a couple minutes to review the derivations, but I think they're in mostly good standing.

Then, there's the issue of "rc2" It has been tagged 6 months ago, on the 8th of January. I would much prefer if they tagged a stable release. Though, there is some activity in the repo, so they eventually will.

Finally, the main reason I'm not continuing: I'm not sure about the quality of the implementation of that greeter. Maybe it's lightdm's configuration at fault, and not the web greeter, but it seems a bit buggy. The shutdown/reboot buttons do nothing (inside a nixos-rebuild build-vm). There are also some layout issue in the default theme, but that's probably not as much an issue.

I'm more concerned with the current state of their *whither* library, which I had to patch to work around (their quote) "*broke[n] file::// url access in qt 5.11*". I had to basically remove a bit of security from the library for it to work. That's not good. Until that is resolved, I may continue on and off (mostly off) to polish this, but this isn't worthy yet for inclusion.

## Things done

- ✔️ Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - ✔️ NixOS
   - 🆖 macOS
   - ❌ other Linux distributions
- ⬜ Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- ⬜ Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- ⬜ Tested execution of all binary files (usually in `./result/bin/`)
- ⬜ Determined the impact on package closure size (by running `nix path-info -S` before and after)
- ⬜ Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by samueldr** [comment]
FWIW, I was/am testing using this mess:

 * https://gist.github.com/samueldr/5b1532aff933b806664d25686c70ebab

The `build.sh` will only work when cd-ed into the same directory.

**Comment by Litarvan** [comment]
Hey ! I'm really glad someone made it, as a theme maker and NixOS user, I was currently waiting for it.
Is the package currently working ? I mean, using your nixpkgs fork on a reagular NixOS, will I be able to use the greeter correctly ?

**Comment by samueldr** [comment]
Hi, there was a question that *somehow disappeared?*.

> Hey ! I'm really glad someone made it, as a theme maker and NixOS user, I was currently waiting for it.
Is the package currently working ? I mean, using your nixpkgs fork on a reagular NixOS, will I be able to use the greeter correctly ?

It was tested up to lightdm-web-greeter starting. I haven't confirmed login worked, but I'm confident it should. Though this confidence is breached by the fact that the shutdown and reboot actions didn't work.

I wouldn't upstream this as-it-is to nixpkgs because of the previous reasons, things are still in development, but once they deem a release to be stable, it would be eventually updated and merged.

**Comment by eadwu** [comment]
Tried running it with `debug_mode: True` and while `lightdm.can_restart` and `lightdm.can_shutdown` were both true, running `lightdm.restart()` and `lightdm.shutdown()` only reloaded the greeter. Also might be good to include https://github.com/Antergos/web-greeter/commit/255a84573f28a079047ceb3cd29f486f87e8cdc3 for HiDPI and setting `services.xserver.displayManager.lightdm.greeters.gtk.enable = false;`.

**Comment by samueldr** [comment]
Closing

 * The project has been archived (antergos is being discontinued)
 * This was never really intended to be "the" PR to include it, but more of a starting point for whenever they fixed their upstream issues.

Anyone is free to revitalize this PR from whichever fork of a web greeter replaces it.

**Pull request closed without merging**
