### PR TITLE
gfortran: use version 8 by default to match our C and C++ compiler

### PR DESCRIPTION
**Pull request by peti**
We recently updated to gcc 8.x, but our default Fortran compiler is still at
version 7.x. This causes trouble for all packages that mix C++ and Fortran
code, like R does.

### CODE REVIEW

**Review by bhipple — APPROVED** [review]

**Comment by markuskowa** [comment]
@GrahamcOfBorg build openblas
@GrahamcOfBorg build octopus
@GrahamcOfBorg build openmolcas

**Comment by peti** [comment]
@GrahamcOfBorg build openblas octopus openmolcas rPackages.RcppArmadillo

**Comment by markuskowa** [comment]
This causes quite a lot of rebuilds. Should this be based against staging?

**Comment by peti** [comment]
No, going through `staging` seems unnecessary for less than 3000 rebuilds. That is not much.

**Pull request merged**
