### PR TITLE
Adding some new vim plugins

### PR DESCRIPTION
**Pull request by Libadoxon**
Added following (neo)vim plugins:
- [cmp-vimtex](https://github.com/micangl/cmp-vimtex)
- [luasnip-latex-snippets-nvim](https://github.com/evesdropper/luasnip-latex-snippets.nvim)
- [follow-md-links-nvim](https://github.com/jghauser/follow-md-links.nvim)
- [typst-conceal-vim](https://github.com/MrPicklePinosaur/typst-conceal.vim)
- [typst-preview-nvim](https://github.com/chomosuke/typst-preview.nvim)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Hello, thank you for your contribution.
In its current state, your PR doesn't do much. Here is how you should operate.

For each plugin:
1. Add the plugin's `JohnDoe/foo.nvim` handle in the `vim-plugin-names` file (like you have done).
2. Edit `pkgs/editors/vim/plugins/generated.nix` and manually add the relevant snippet for your new plugin.
  1. Warning: the attribute name should be `foo-nvim` but `pname` should remain `foo.nvim`.
  2. Look for the last commit on the plugin's github repo and fill the corresponding date (in `version`) and `rev`.
  3. At first, leave the hash empty and try to build the plugin with: `nix-build -A vimPlugins.foo-nvim`
  4. Get the hash from the failed build and put it in the `hash` field.
3. If the plugin has **mandatory** dependencies, edit the `pkgs/editors/vim/plugins/overrides.nix` file and add the `nvimRequireCheck` attribute.
5. Commit the changes for this individual plugin: `vimPlugins.foo-nvim: init at 202X-YY-ZZ`

Please, feel free to ask if the process is unclear.

**Comment by GaetanLepage** [comment]
> I followed the documentation in [nixpkgs](https://github.com/nixos/nixpkgs/blob/master/doc/languages-frameworks/vim.section.md) which just says to run `nix-shell -p vimPluginsUpdater --run 'vim-plugins-updater add "[owner]/[name]"'` for each new plugin, which I have done. Is the documentation out of date or did I miss something?

Yes, the documentation is incomplete in this regard.
running the script with the `add` subcommand does nothing more than editing the `vim-plugin-names` file. This is not enough to effectively add the package.
Normally, you could subsequently run `vim-plugins-updater` without arguments to update `generated.nix`, but this has the unpleasant side effect of updating all vim plugins.

Thus, I recommend you to follow the process I have described above.
We are working on improving the script to automatize this.

**Comment by Libadoxon** [comment]
ok will do

**Comment by PerchunPak** [comment]
> We are working on improving the script to automatize this.


Just for context: https://github.com/NixOS/nixpkgs/pull/336137

**Comment by GaetanLepage** [comment]
Please, ensure that there is exactly one commit per plugin.
Each commit should modify both `vim-plugin-names` and `generated.nix`.
Also, you don't necessarily need to sort the `generated.nix` file.

**Comment by Libadoxon** [comment]
Done

**Comment by GaetanLepage** [comment]
Thanks !
I have a slight concern regarding `typst-preview`. The plugin will try to fetch binaries using `curl`.
Usually, we tend to patch (i.e. hardcode the `/nix/store` path to the needed binaries) in those cases.

**Comment by Libadoxon** [comment]
Plugin works fine for me on NixOs

**Comment by GaetanLepage** [comment]
> Plugin works fine for me on NixOs

Have you been using any specific config ?
If I understand the logic correctly, either the user has set a path for the dependencies ([here](https://github.com/chomosuke/typst-preview.nvim/blob/06778d1b3d4d29c34f1faf80947b586f403689ba/lua/typst-preview/config.lua#L7-L10)) or they are being looked for in `~/.local/share/nvim/typst-preview/` and eventually downloaded.
I would advise to add the following on `pkgs/applications/editors/vim/plugins/overrides.nix`:
```
typst-preview-nvim = super.typst-preview-nvim.overrideAttrs {
  postPatch = ''
    substituteInPlace lua/typst-preview/config.lua \
     --replace-fail "['tinymist'] = nil," "tinymist = '${lib.getExe tinymist}'," \
     --replace-fail "['websocat'] = nil," "websocat = '${lib.getExe websocat}',"
  '';
  nvimRequireCheck = "typst-preview";
};
```

**Comment by Libadoxon** [comment]
Yeah I set the path in my home-manager config, which works perfectly:
```lua
require 'typst-preview'.setup {
  dependencies_bin = {
    ['tinymist'] = "${lib.getExe pkgs.tinymist}",
    ['websocat'] = "${lib.getExe pkgs.websocat}",
  }
}
```

**Comment by GaetanLepage** [comment]
> Yeah I set the path in my home-manager config, which works perfectly:

Ok makes sense indeed.
Let's patch it so that the plugin works out of the box.

**Comment by Libadoxon** [comment]
will do

**Comment by Libadoxon** [comment]
Done

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 353253`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 6 packages built:</summary>
  <ul>
    <li>vimPlugins.cmp-vimtex</li>
    <li>vimPlugins.follow-md-links-nvim</li>
    <li>vimPlugins.luasnip-latex-snippets-nvim</li>
    <li>vimPlugins.typst-conceal-vim</li>
    <li>vimPlugins.typst-preview-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 6 packages built:</summary>
  <ul>
    <li>vimPlugins.cmp-vimtex</li>
    <li>vimPlugins.follow-md-links-nvim</li>
    <li>vimPlugins.luasnip-latex-snippets-nvim</li>
    <li>vimPlugins.typst-conceal-vim</li>
    <li>vimPlugins.typst-preview-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>vimPluginsUpdater</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 5 packages built:</summary>
  <ul>
    <li>vimPlugins.cmp-vimtex</li>
    <li>vimPlugins.follow-md-links-nvim</li>
    <li>vimPlugins.luasnip-latex-snippets-nvim</li>
    <li>vimPlugins.typst-conceal-vim</li>
    <li>vimPlugins.typst-preview-nvim</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>vimPluginsUpdater</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 5 packages built:</summary>
  <ul>
    <li>vimPlugins.cmp-vimtex</li>
    <li>vimPlugins.follow-md-links-nvim</li>
    <li>vimPlugins.luasnip-latex-snippets-nvim</li>
    <li>vimPlugins.typst-conceal-vim</li>
    <li>vimPlugins.typst-preview-nvim</li>
  </ul>
</details>

**Review by GaetanLepage — APPROVED** [review]
Diff LGTM, thank you for patiently addressing all my comments.

The darwin failures are unrelated.
I will merge once ofborg eval will have completed. This might take a while as currently there are technical issues with the CI.

**Pull request merged**
