### PR TITLE
Lua for sile

### PR DESCRIPTION
**Pull request by teto**
###### Motivation for this change

add missing packages for https://github.com/NixOS/nixpkgs/pull/77738

@doronbehar while regenerating the set, I noticed pulseaudio was generated. Maybe you could move you changes to lua-pulseaudio in pkgs/development/lua-modules/overrides.nix instead.

@shados I've disabled parallel, I have never been able to complete a single update with a value != 1.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
@teto could you point me to where did my Pulseaudio Lua module got generated? I didn't find it in the diff other then in the csv file...

**Comment by teto** [comment]
I haven't committed the generated pulseaudio package (due to this line https://github.com/NixOS/nixpkgs/blame/master/maintainers/scripts/luarocks-packages.csv#L74) but if you run `maintainers/scripts/update-luarocks-packages pkgs/development/lua-modules/generated-packages.nix ` you can see it is generated.

**Comment by teto** [comment]
seems like linenoise needs an override, will update later.

**Comment by doronbehar** [comment]
> ... but if you run maintainers/scripts/update-luarocks-packages pkgs/development/lua-modules/generated-packages.nix you can see it is generated.

I remember, that back when I wanted to add lua_pulseaudio to nixpkgs I considered just adding a line to the csv table and running the script. But, I figured that it would just update so many packages that many people would have to be mentioned and summoned for review in order for that PR to pass while I just want my package to be added. Hence, I added it where it is now - to `top-level/lua-modules.nix`.

Anyway, I don't care, as long as copying the make flags and everything to an override won't brake anything (and it shouldn't) feel free @teto to run the script and add an override in `pkgs/development/lua-modules/overrides.nix`.

**Comment by teto** [comment]
@doronbehar You don't have to submit all generated-packages.nix modifications. With `git add -p`, one can select updates only for his/her package. Anyway right now because pulseaudio is mentioned in the csv file, it generates some code so let's keep as much as possible generated.

If you don't beat me to it, I will prepare sthg next week.

**Comment by doronbehar** [comment]
> If you don't beat me to it, I will prepare sthg next week.

What do you mean by "beat me to it" and "sthg"? I noticed you still didn't merge here the pulseaudio and perhaps other updates to lua's generated package set right?

**Pull request merged**
