### PR TITLE
Update nginx packages

### PR DESCRIPTION
**Pull request by Izorkin**
- nginxMainline: 1.21.4 -> 1.21.5
- nginxQuic: 0ee56d2eac44 -> 32daba3aabb2

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Izorkin** [comment]
cc @ajs124 @dasJ @Mic92

**Comment by ajs124** [comment]
`nginxQuic` fails to build for me like this:
```
checking for struct dirent.d_namlen ... not found
checking for struct dirent.d_type ... found
checking for sysconf(_SC_NPROCESSORS_ONLN) ... found
checking for sysconf(_SC_LEVEL1_DCACHE_LINESIZE) ... found
checking for openat(), fstatat() ... found
checking for getaddrinfo() ... found
configuring additional modules
adding module in /nix/store/2ysp5ichpccf4lv1wp2qcwz0bmm840f1-rtmp
 + ngx_rtmp_module was configured
adding module in /nix/store/6pb7j6kymf3y4xs5blp3g8mwin2j22kk-dav
 + ngx_http_dav_ext_module was configured
adding module in /nix/store/y39g23fn8ikzcd1iy3b1bclqwjk2qmxd-moreheaders
 + ngx_http_headers_more_filter_module was configured
checking for PCRE library ... not found
checking for PCRE library in /usr/local/ ... not found
checking for PCRE library in /usr/include/pcre/ ... not found
checking for PCRE library in /usr/pkg/ ... not found
checking for PCRE library in /opt/local/ ... not found

./configure: error: the HTTP rewrite module requires the PCRE library.
You can either disable the module by using --without-http_rewrite_module
option, or install the PCRE library into the system, or build the PCRE library
statically from the source with nginx by using --with-pcre=<path> option.

builder for '/nix/store/bzhyzialaf9fvdn48xk1n2cf9i5s12gh-nginx-1.21.5-quic.drv' failed with exit code 1
```

**Comment by Izorkin** [comment]
Fixed build, update nginxQuic to rev `10522e8dea41`.

**Comment by Izorkin** [comment]
Drop latest commit - ModSecurity-nginx error build with pcre2.

**Comment by Izorkin** [comment]
cc @ajs124 @dasJ @Mic92

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 152566` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>nginxMainline</li>
    <li>nginxQuic</li>
  </ul>
</details>

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 152566` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>nginxMainline</li>
    <li>nginxQuic</li>
  </ul>
</details>

**Review by Kranzes — APPROVED** [review]
Tested working on my machine

**Pull request merged**
