### PR TITLE
nixpkgs manual: add a section about passthru

### PR DESCRIPTION
**Pull request by abbradar**
Is chapter about `meta` a good place to put this into? `passthru` and `meta` are similar after all, but are not related in any actual way. I don't see any better place to put this to (granted, I'm not very good at structuring documentation).

### CODE REVIEW

**Comment by domenkozar** [comment]
@abbradar the only reason why `passthru` exists is that it doesn't pass those attributes to the builder, so hash doesn't change. See https://github.com/NixOS/nix/pull/312

**Comment by abbradar** [comment]
Ah, I haven't really thought of `meta` as a Nix feature before either. I thought that `meta` analogy would be good for people to understand it (we already have a lot of mentions that `meta` is not passed to the builder in several places), but now I see that this can be confusing because we have special support for `meta`.

I'll think how to rewrite it!

**Comment by domenkozar** [comment]
Yes, I wouldn't compare it to something else but rather explain why it exists and what purpose it serves.

**Comment by abbradar** [comment]
Does this look better?

**Comment by domenkozar** [comment]
Look good.

**Pull request merged**
