### PR TITLE
cargo-llvm-cov: 0.5.33 -> 0.5.35

### PR DESCRIPTION
**Pull request by matthiasbeyer**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gepbird** [comment]
Result of `nixpkgs-review pr 261650` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>cargo-llvm-cov</li>
  </ul>
</details>

**Comment by CobaltCause** [comment]
https://github.com/taiki-e/cargo-llvm-cov/releases/tag/v0.5.35 btw

**Comment by matthiasbeyer** [comment]
Still not working for the same reasons as before.

**Comment by CobaltCause** [comment]
```diff
diff --git a/pkgs/development/tools/rust/cargo-llvm-cov/default.nix b/pkgs/development/tools/rust/cargo-llvm-cov/default.nix
index b384187c8d14..33251230b199 100644
--- a/pkgs/development/tools/rust/cargo-llvm-cov/default.nix
+++ b/pkgs/development/tools/rust/cargo-llvm-cov/default.nix
@@ -21,6 +21,7 @@
 , fetchFromGitHub
 , rustPlatform
 , rustc
+, git
 }:
 
 let
@@ -54,7 +55,8 @@ rustPlatform.buildRustPackage {
     inherit owner;
     repo = pname;
     rev = "v${version}";
-    sha256 = "sha256-ux4vVpejMkHwXxYS+LGoJufb4CiBHU7jjLX8glubnVU=";
+    sha256 = "sha256-059k2z+ZtpWgZjoFZKIHF+OHYnBcUUO/4REWW5XRHkw=";
+    leaveDotGit = true;
   };
 
   # Upstream doesn't include the lockfile so we need to add it back
@@ -69,6 +71,10 @@ rustPlatform.buildRustPackage {
   LLVM_COV = "${llvm}/bin/llvm-cov";
   LLVM_PROFDATA = "${llvm}/bin/llvm-profdata";
 
+  nativeCheckInputs = [
+    git
+  ];
+
   meta = {
     inherit homepage;
     changelog = homepage + "/blob/v${version}/CHANGELOG.md";
```

This helps but doesn't fix it, now I'm seeing errors like

```
---- virtual1 stdout ----
thread 'virtual1' panicked at 'assertion failed: `self.status.success()`:

STDOUT:
------------------------------------------------------------

------------------------------------------------------------

STDERR:
------------------------------------------------------------
error: process didn't exit successfully: `/nix/store/9vxskkmmmqh2r72x63g2rr7vf93da577-cargo-1.72.0/bin/.cargo-wrapped locate-project --message-format plain` (exit status: 101)
--- stderr
error: could not find `Cargo.toml` in `/build/.tmp47f2rX` or any parent directory


------------------------------------------------------------
', tests/test.rs:37:9
```

**Comment by CobaltCause** [comment]
The secret sauce was

```
preCheck = ''
  git restore --staged .
'';
```

because for some reason doing `fetchFromGitHub { leaveDotGit = true; ... }` and then `git status` shows that every file is staged as deleted but then also still in the working tree as untracked. You can see this for yourself by doing e.g.

```
preCheck = ''
  git status
  exit 1
'';
```

and then looking at the logs. Pretty surprising behavior, if you ask me.

<details>
<summary>Click to expand fully working patch</summary>

```diff
diff --git a/pkgs/development/tools/rust/cargo-llvm-cov/default.nix b/pkgs/development/tools/rust/cargo-llvm-cov/default.nix
index b384187c8d14..d9a1d5c10d07 100644
--- a/pkgs/development/tools/rust/cargo-llvm-cov/default.nix
+++ b/pkgs/development/tools/rust/cargo-llvm-cov/default.nix
@@ -21,6 +21,7 @@
 , fetchFromGitHub
 , rustPlatform
 , rustc
+, git
 }:
 
 let
@@ -54,7 +55,8 @@ rustPlatform.buildRustPackage {
     inherit owner;
     repo = pname;
     rev = "v${version}";
-    sha256 = "sha256-ux4vVpejMkHwXxYS+LGoJufb4CiBHU7jjLX8glubnVU=";
+    sha256 = "sha256-059k2z+ZtpWgZjoFZKIHF+OHYnBcUUO/4REWW5XRHkw=";
+    leaveDotGit = true;
   };
 
   # Upstream doesn't include the lockfile so we need to add it back
@@ -69,6 +71,14 @@ rustPlatform.buildRustPackage {
   LLVM_COV = "${llvm}/bin/llvm-cov";
   LLVM_PROFDATA = "${llvm}/bin/llvm-profdata";
 
+  nativeCheckInputs = [
+    git
+  ];
+
+  preCheck = ''
+    git restore --staged .
+  '';
+
   meta = {
     inherit homepage;
     changelog = homepage + "/blob/v${version}/CHANGELOG.md";
```

</details>

Also, <https://github.com/taiki-e/cargo-llvm-cov/releases/tag/v0.5.36> exists now.

**Comment by matthiasbeyer** [comment]
Can you send the patches to me or give me an URL to pull from?

I also am in the process of packaging the update to 0.5.36.

**Comment by CobaltCause** [comment]
> Can you send the patches to me or give me an URL to pull from?

I put it in https://github.com/NixOS/nixpkgs/pull/261650#issuecomment-1786206678, you should be able to just copy it to your clipboard and then do `wl-paste -n | patch -p1` assuming Wayland. The hash change will probably get rejected though so you'll have to fix that. Or you can just apply it manually (like, by editing the file and using the patch as a reference).

**Comment by matthiasbeyer** [comment]
Yeah please provide something I can pull from. That's less hassle for everyone and even preserves credit to you.

If I apply the changes from your above fix, the issue is not fixed (`fatal: not a git repository (or any parent up to mount point /)`).

**Comment by CobaltCause** [comment]
I think that means you forgot to change the hash for `fetchFromGitHub` and you're getting a stale version of the FOD from before `leaveDotGit = true;` was set.

Anyway, I opened https://github.com/NixOS/nixpkgs/pull/264606 since it takes 2 extra seconds to open a PR after doing the work of carrying the patch through all the updates, making commits for this, and pushing them somewhere.

**Comment by CobaltCause** [comment]
Hey, matthiasbeyer, sorry for the hostility in the previous comment. Also, apologies for putting any nixpkgs committers who saw this into the awkward position of trying to figure out whether to go ahead with one of these, and if so, which one.

To get things moving again, do you want to pull the changes/commits from #264606 into this PR and have me close that, or do you want to close this one in favor of that one? Personally, I'm okay with either option, I have no preference.

**Comment by matthiasbeyer** [comment]
Don't worry too much about it. 
I test built, approved and merged the other PR and am closing this.

**Pull request closed without merging**
