### PR TITLE
lapack: include lapacke_utils.h in alternatives/lapack 

### PR DESCRIPTION
**Pull request by expipiplus1**
###### Motivation for this change

Although not present in our (old) version of libsurvive, there's an
upcoming issue
(https://gitlab.freedesktop.org/monado/monado/-/issues/130) which can be
worked around by using mkl as a lapack implementation.

This isn't a fix, but it makes things a little easier for those
overriding to a newer version, and it's the correct thing to do anyway.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by prusnak — APPROVED** [review]

**Comment by expipiplus1** [comment]
I updated the PR title to better reflect the large-impact change here, rather than the motivating change.

**Comment by prusnak** [comment]
I am afraid this might have to go to staging first.

**Comment by expipiplus1** [comment]
@prusnak I opened https://github.com/NixOS/nixpkgs/pull/146205 targeting staging.

**Comment by prusnak** [comment]
Closing this PR in favor of https://github.com/NixOS/nixpkgs/pull/146205

**Pull request closed without merging**
