### PR TITLE
home-manager: 2023-04-02 -> 2023-05-30

### PR DESCRIPTION
**Pull request by AndersonTorres**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
1. Fix the silly error
2. Pick the code from home-manager/default.nix

**Comment by AndersonTorres** [comment]
@rycee as one of HM owners, can you review this, please?

**Comment by piegamesde** [comment]
I did some bisecting and have reason to believe that this change caused #236940. Please take a look.

**Comment by piegamesde** [comment]
Given that during that bisect the newer home-manager versions worked even on the commit prior to this change, I infer that the changes made here were not actually necessary for the version bump. If they had been separated out into a separate commit, it would have saved me a lot of time figuring that out.

**Comment by mweinelt** [comment]
Hiding a change in such a huge refactoring is not appreciated.

**Comment by AndersonTorres** [comment]
How exactly this bug is reproduced?

**Comment by piegamesde** [comment]
Not 100% sure, but the common element is people who don't have a Nix channel for home-manager. I am on Arch Linux, but in the bug reports this apparently also seems to happen with system wide HM installs.

**Comment by bb2020** [comment]
> How exactly this bug is reproduced?

Install with `environment.systemPackages` and don't install anything else related to `home-manager`.
`home-manager switch` or `home-manager generations` will throw an error.

**Comment by bb2020** [comment]
> How exactly this bug is reproduced?

Install with `environment.systemPackages` and don't install anything else related to `home-manager`.
Running `home-manager switch` or `home-manager generations` will throw an error.

> I really liked the old packaging, because it meant that home-manager used its own source code for the modules, meaning they were always in sync (and in sync with Nixpkgs).

I agree. Having seperate channels for `nixos` (or `nixpkgs` on other systems) and `home-manager` is a huge regression.

**Comment by AndersonTorres** [comment]
Fixup: https://github.com/NixOS/nixpkgs/pull/247252

**Comment by bb2020** [comment]
The fix is now working properly on my setup.

**Pull request merged**
