### PR TITLE
libminc: 2.4.03 -> unstable-2020-07-17

### PR DESCRIPTION
**Pull request by bcdarwin**
and update reverse dependencies accordingly

###### Motivation for this change

 - update libminc; most importantly a fix for a scaling bug (https://github.com/BIC-MNI/libminc/pull/109)
 - libminc builds against default hdf5, so drop hdf5_1_8 from tree
 - the location of CMake files has changed, so the builds of its reverse dependencies need to be updated

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bcdarwin** [comment]
@GrahamcOfBorg eval

**Comment by bcdarwin** [comment]
Rebased onto master and resolved breakage from another PR (#91071).

**Review by lheckemann — APPROVED** [review]
Wow, upstream could do with some more releases :D 

That aside, LGTM.

**Comment by lheckemann** [comment]
That is indeed an, uh, interesting failure on ofborg. Let's just kick it.

@ofborg build EBTKS bicgl bicpl conglomerate inormalize minc_tools mni_autoreg n3 oobicpl

**Comment by bcdarwin** [comment]
`libminc` tests are still weirdly failing, so I've disabled parallel building -- perhaps that will help.

**Comment by bcdarwin** [comment]
@lheckemann turns out the tests can't be run in parallel (and `enableParallelBuilding` doesn't control `ctest`); see https://github.com/BIC-MNI/libminc/issues/110.  Anyway, good to go now.

**Pull request merged**
