### PR TITLE
procdump: enable parallel building

### PR DESCRIPTION
**Pull request by trofi**

### CODE REVIEW

**Comment by c0bw3b** [comment]
Please keep (and use) the template when you submit a pull request. It helps reviewers to know what was (or wasn't) tested already and the motivation behind the PR.

This currently takes between 2 and 6 seconds to build on Hydra, so there would be very little gain to build ProcDump in parallel.

The patch you submitted upstream (thanks for that) should be reviewed and approved before we merge this.

**Review by c0bw3b — CHANGES_REQUESTED** [review]
No change requested but waiting for upstream review on the patch

**Review by c0bw3b — COMMENTED** [review]
Ok upstream merged the proposed changes. It builds and runs.

Result of `nixpkgs-review pr 157816` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>procdump</li>
  </ul>
</details>

---

@trofi > could you update this to fetch the patch from upstream commit id `eb746130914f800d72038b529d9035454fcd3dc7` instead of the PR patch diff?

**Comment by trofi** [comment]
Oh, good catch! I totally forgot about it. Changed patch to explicit hash.

**Review by c0bw3b — APPROVED** [review]

**Pull request merged**
