### PR TITLE
vscode-extensions.matklad.rust-analyzer: 0.2.834 -> 0.2.975

### LINKED ISSUE #162010: vscode-extensions.matklad.rust-analyzer 0.2.384 out of date, missing security updates
###### Notes

`rust-analyzer` itself has been steadily updated in nixpkgs but nixpkgs' packaging of its bundled vscode extension, `vscode-extensions.matklad.rust-analyzer` has not been updated in >2 months. 

Additionally, during this time, the extension's dependencies have been updated to remove at least two security vulnerabilities: https://github.com/rust-analyzer/rust-analyzer/pull/11420.

I would like to help keep this extension up to date, but I am unfortunately insufficiently familiar with nixpkgs' `nodePackages` infrastructure (and the extension's packaging's use of it) to prepare an appropriate PR.

Thus:

a) can someone who is familiar with the extension's packaging please update it, perhaps to 0.3.953 or to one of the recent git tags such as https://github.com/rust-analyzer/rust-analyzer/releases/tag/2022-02-22, to match `rust-analyzer`?

b) additionally, if/when you do, could you also add a paragraph of comments (maybe to the nixpkgs manual, if not directly in the code?) on what the steps are to update it so that this is more clear?

Thanks!

courtesy cc: @inicola, who has been improving the extensions' compatibility with NixOS.

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: vscode-extensions.matklad.rust-analyzer

current version: 0.2.384
desired version: 0.4-dev

###### Notify maintainers

maintainers: @jonringer

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by austinbutler**
###### Description of changes

1. Add an update script for `vscode-extensions.matklad.rust-analyzer`, mostly taken from the deleted parts of https://github.com/NixOS/nixpkgs/pull/150775
1. Update `vscode-extensions.matklad.rust-analyzer`
1. Document (hopefully correctly) the Javascript packages in nixpkgs update procedure
    - Somewhat counting on [Cunningham's Law](https://en.wikipedia.org/wiki/Ward_Cunningham#%22Cunningham's_Law%22) here :stuck_out_tongue: 

Fixes https://github.com/NixOS/nixpkgs/issues/162010.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by austinbutler** [comment]
Result of `nixpkgs-review pr 165067` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>hyperspace-cli</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.plugins.giphy</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
  </ul>
</details>
<details>
  <summary>52 packages built:</summary>
  <ul>
    <li>antennas</li>
    <li>antora</li>
    <li>balanceofsatoshis</li>
    <li>bat-extras.prettybat</li>
    <li>bitwarden-cli</li>
    <li>castnow</li>
    <li>code-server</li>
    <li>commitlint</li>
    <li>create-cycle-app</li>
    <li>cryptpad</li>
    <li>deltachat-desktop</li>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>emojione</li>
    <li>epgstation</li>
    <li>fast-cli</li>
    <li>google-clasp</li>
    <li>grafana-image-renderer</li>
    <li>gtop</li>
    <li>image_optim</li>
    <li>iosevka</li>
    <li>joplin</li>
    <li>lumo</li>
    <li>mastodon-bot</li>
    <li>odoo</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pyright</li>
    <li>redoc-cli</li>
    <li>reveal-md</li>
    <li>shepherd</li>
    <li>shout</li>
    <li>thelounge</li>
    <li>uchiwa</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-eslint</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-prettier</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-rust-analyzer</li>
    <li>vimPlugins.coc-snippets</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.coc-yaml</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>wasm-text-gen</li>
    <li>yaml-language-server</li>
    <li>zx</li>
  </ul>
</details>

**Comment by winterqt** [comment]
I wonder why those The Lounge plugins failed to build -- mind providing logs?

**Comment by austinbutler** [comment]
Seems the same failures occur on master. Think it's missing/can't find `node-pre-gyp`. Here's the end of `nix-build -A theLoungePlugins.plugins.closepms` on master:

```
sh: line 1: node-pre-gyp: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! sqlite3@5.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the sqlite3@5.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2022-03-21T17_32_23_163Z-debug.log

error: builder for '/nix/store/qqjz1wjl91na10zql30gij66dn1k82ab-thelounge-plugin-closepms-1.0.2.drv' failed with exit code 1;
       last 10 log lines:
       > npm ERR! errno ENOENT
       > npm ERR! sqlite3@5.0.2 install: `node-pre-gyp install --fallback-to-build`
       > npm ERR! spawn ENOENT
       > npm ERR!
       > npm ERR! Failed at the sqlite3@5.0.2 install script.
       > npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       >
       > npm ERR! A complete log of this run can be found in:
       > npm ERR!     /build/.npm/_logs/2022-03-21T17_32_23_163Z-debug.log
       >
       For full logs, run 'nix log /nix/store/qqjz1wjl91na10zql30gij66dn1k82ab-thelounge-plugin-closepms-1.0.2.drv'.
```

**Comment by winterqt** [comment]
Ah, right. 

#161249 fixes this; I could've sworn that it was merged but I guess not.

**Comment by winterqt** [comment]
@ofborg test thelounge

**Comment by happysalada** [comment]
Thank you!

**Comment by austinbutler** [comment]
Result of `nixpkgs-review pr 165067` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>fast-cli</li>
    <li>hyperspace-cli</li>
    <li>odoo</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>lumo</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.plugins.giphy</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
  </ul>
</details>
<details>
  <summary>43 packages built:</summary>
  <ul>
    <li>antennas</li>
    <li>antora</li>
    <li>balanceofsatoshis</li>
    <li>bat-extras.prettybat</li>
    <li>bitwarden-cli</li>
    <li>castnow</li>
    <li>code-server</li>
    <li>commitlint</li>
    <li>create-cycle-app</li>
    <li>cryptpad</li>
    <li>deltachat-desktop</li>
    <li>epgstation</li>
    <li>google-clasp</li>
    <li>gtop</li>
    <li>image_optim</li>
    <li>iosevka</li>
    <li>joplin</li>
    <li>mastodon-bot</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pyright</li>
    <li>redoc-cli</li>
    <li>reveal-md</li>
    <li>shepherd</li>
    <li>shout</li>
    <li>thelounge</li>
    <li>uchiwa</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-eslint</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-prettier</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-rust-analyzer</li>
    <li>vimPlugins.coc-snippets</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.coc-yaml</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>wasm-text-gen</li>
    <li>yaml-language-server</li>
    <li>zx</li>
  </ul>
</details>

**Pull request merged**
