### PR TITLE
sunshine: resolve tray icon issues

### LINKED ISSUE #361790: Sunshine module - tray icon not loading and apps.json created as read-only.
## Describe the bug

Using NixOS 24.11 and GNOME as the DE. When enabling the Sunshine module with `capSysAdmin = true;` the tray icon does not load. The service does start though. Just the tray icon is not present. The tray icon does load if you omit `capSysAdmin = true;` but this causes the application to fail on Wayland.

Another oddity is that the `apps.json` file gets created in `.config/sunshine` as read-only, so no apps can be added to Sunshine by default. Manually marking the file as read-write works. This issue is irrespective of `capSysAdmin = true;` being set or not.

## Steps To Reproduce

Enable Sunshine in the NixOS config as below and perform a `nixos-rebuild switch`. The `apps.json` file is created as read-only and the tray icon is not present, despite the service running.

```
services.sunshine = {
      enable = true;
      autoStart = true;
      capSysAdmin = true;
      openFirewall = true;
};
```
## Expected behavior

The tray icon is present while the service is running, and the `apps.json` file is created with read-write permissions so it can be edited through the GUI.

## Notify maintainers

@devusb 

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by devusb**
Closes #361790
- use Boost 1.85 per [this upstream comment](https://github.com/LizardByte/Sunshine/issues/3253#issuecomment-2391326918)
- set `environment.PATH` to `null`, which allows `xdg-open` to work for opening tray icon links
- cherry pick test fixes from https://github.com/NixOS/nixpkgs/pull/342813
- move to `by-name`

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by thiagokokada — APPROVED** [review]

**Comment by thiagokokada** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 364438`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>sunshine</li>
  </ul>
</details>

**Comment by paparodeo** [comment]
this breaks in staging / staging-next as boost-185 is removed.

https://github.com/NixOS/nixpkgs/actions/runs/12423664740/job/34687593476

>        error: undefined variable 'boost185'
>        at /nix/store/z8w9nr9lsis5c8ayr1dc81cyg2r2qx2q-source/pkgs/top-level/all-packages.nix:18715:13:
>         18714|   sunshine = callPackage ../by-name/su/sunshine/package.nix {
>         18715|     boost = boost185;
>              |             ^
>         18716|   };

this will need to be moved to boost186 or some other boost version or reverted

**Comment by paparodeo** [comment]
can sunshine just use boost-186?

**Comment by devusb** [comment]
haven’t tried, but it may need this https://github.com/LizardByte/Sunshine/pull/3256

**Comment by devusb** [comment]
if 186 is the new default the reverting won’t help either I don’t think.

**Comment by paparodeo** [comment]
> if 186 is the new default the reverting won’t help either I don’t think.

reverting will fix the CI but sunshine will still be broken.

**Comment by paparodeo** [comment]
the patch doesn't look too complex might be easy enough to fix.

**Comment by devusb** [comment]
yeah fair — we may need to consider switching to an unstable version in the meantime.

**Comment by paparodeo** [comment]
> yeah fair — we may need to consider switching to an unstable version in the meantime.

I ported the patch hand have it building on staging-next. will post PR

**Comment by paparodeo** [comment]
> > yeah fair — we may need to consider switching to an unstable version in the meantime.
> 
> I ported the patch hand have it building on staging-next. will post PR

https://github.com/NixOS/nixpkgs/pull/366696

**Pull request merged**
