### PR TITLE
awscli, boto3, botocore: bump to latest versions

### PR DESCRIPTION
**Pull request by flokli**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
This change is on staging-next, please rebase onto it.

**Comment by flokli** [comment]
Well, a slightly different change, but the same packages. Rebased and retargeted to `staging-next`, squashed and updated the commit messages. PTAL.

**Comment by FRidh** [comment]
@GrahamcOfBorg build python3.pkgs.moto

**Comment by flokli** [comment]
@FRidh is this good to merge?

**Review by jonringer — APPROVED** [review]
I say this is good, any regressions can be dealt with on staging-next

**Comment by flokli** [comment]
:+1:

**Pull request merged**
