### PR TITLE
lscolors: init at 0.7.1

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by heroku-miraheze** [comment]
Check all or will be closed.

**Comment by heroku-miraheze** [comment]
Contributors, close this pull request, this person does not have checked all checkboxes.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 114091` at 4fedda2c run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/c7a45173a4fea6b414b5b981ad8ee0f9">lscolors</a></li></li>
  </ul>
</details>

**Comment by 0x4A6F** [comment]
Result of `nixpkgs-review pr 114091` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>lscolors</li>
  </ul>
</details>

**Review by 0x4A6F — APPROVED** [review]
Thanks for this port. Please change title/commit from ini to init.

**Comment by heroku-miraheze** [comment]
Why you merge it, we need to merge us.

**Comment by heroku-miraheze** [comment]
Reverted.

**Pull request merged**
