### PR TITLE
python312Packages.hikari: fix build

### PR DESCRIPTION
**Pull request by itepastra**
- **python3Packages.hikari: format using nixfmt**
- **python3Packages.hikari: fix build Remove the `asyncio_default_fixture_loop_scope` from pyproject.toml**

ZHF: #352882

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by tomodachi94 — APPROVED** [review]
Lgtm, though I'm hesitant to make this *the* long-term fix.

Further investigation at a later date would be appreciated (though I'm fine with this being merged as-is): Do we know why this occurs?

**Comment by itepastra** [comment]
I think I may be able to make the change smaller, but I have to go sleep and will look at this tomorrow if I have time

**Review by Sigmanificient — APPROVED** [review]

**Comment by tomodachi94** [comment]
This occurs because our pytest-asyncio is outdated. asyncio_default_fixture_loop_scope was [introduced in 0.24](https://github.com/pytest-dev/pytest-asyncio/issues/924), but we are on 0.23.6.

**Comment by itepastra** [comment]
I can try, don't know if it counts as a breaking change for backporting,but for the new unstable we should update for sure

**Comment by tomodachi94** [comment]
Considering the above PR has stalled, I'd say this is okay to merge, provided we revert it once the update is applied.

**Comment by itepastra** [comment]
agreed, should I add a comment that it should be removed after the pr is merged?

**Review by tomodachi94 — APPROVED** [review]
Lgtm, thanks ❤️

**Pull request merged**
