### PR TITLE
platformio: 4.0.3 -> 4.1.0

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by FRidh — CHANGES_REQUESTED** [review]
this needs to be rebased onto staging-next

**Comment by Mic92** [comment]
Fixed

**Comment by boxofrox** [comment]
I rebased this PR onto `nixpkgs-unstable` (62ef779f2a5), and I run into a version conflict error with `importlib-metadata`

```
$ nix-env -f . -iA platformio
installing 'platformio'
these derivations will be built:
  /nix/store/1i2l5fjysj964c79d6cj5ijl7idis267-source.drv
  /nix/store/83zlg5mx6dm80d2hlx6zh1b3gihcdlaj-python3.7-tox-3.14.2.drv
  /nix/store/c7ngf2rim1wl5lszlyr7r14payzhxsdj-source.drv
  /nix/store/2p4wlsqp2gzz1nwkv0rbfrcc5k80081z-platformio-4.1.0.drv
  /nix/store/72gv5mcfxc07cm5ygav14z549486rlha-platformio-usr-target.drv
  /nix/store/g6js0kwc5m6bjw8f7hv8ypqxiwy2zzwg-python3.7-tox-3.14.2.drv
  /nix/store/b6m6z2kd0jl345ll40qwhza8zqikks6x-platformio-4.1.0.drv
  /nix/store/h7jmnxvmbw7agv4xlr0jh489jpw6ah3x-platformio-usr-multi.drv
  /nix/store/la4z7xawcz31d7hpm4pxxhvnjvfi5vcz-platformio-fhs.drv
  /nix/store/dqjnlvlwqsh0wyrp39r003wham4j18ar-platformio-init.drv
  /nix/store/kiscf14aingrhrc6s4lkbpnvyy0va2s9-platformio.drv
... trimmed output
Finished executing setuptoolsBuildPhase
installing
Executing pipInstallPhase
/build/tox-3.14.2/dist /build/tox-3.14.2
Processing ./tox-3.14.2-py2.py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement importlib-metadata<2,>=1.1.0; python_version < "3.8" (from tox==3.14.2) (from versions: none)
ERROR: No matching distribution found for importlib-metadata<2,>=1.1.0; python_version < "3.8" (from tox==3.14.2)
```

I found on pypi \[[1](https://pypi.org/project/importlib-metadata/#history)\], that `importlib-metadata` v1.3 is available, and nixpkgs remains on v0.23.  I'm not sure what changed in `nixpkgs-unstable` to enable the requirement for `importlib-metadata<2,>=1.1.0`

I ran into this same error with PR #75913 after syncing `nixpkgs-unstable` to commit 62ef779f2a5.  @Mic92 Do you run into this error also?

\[1\]: https://pypi.org/project/importlib-metadata/#history

**Comment by boxofrox** [comment]
Found it.  python-tox v3.14.2 upgraded its dependency on `importlib-metadata` to v1.1.0 \[[1](https://github.com/tox-dev/tox/commit/b4c4625ff3d7474c409f0e756b479dcd1c30d4f0)\].

I'm new to nixpkgs development.  Do we update the `python{27,37}Packages.importlib-metadata` from v0.23 to v1.1.0?

\[1\]: https://github.com/tox-dev/tox/commit/b4c4625ff3d7474c409f0e756b479dcd1c30d4f0

**Comment by makefu** [comment]
how does this pr fit to #78056 ?

**Comment by Mic92** [comment]
superseeded by https://github.com/NixOS/nixpkgs/pull/78056

**Pull request closed without merging**
