### PR TITLE
planner: 0.14.6 -> 20170429

### PR DESCRIPTION
**Pull request by amiloradovsky**
###### Motivation for this change

Numerous minor fixes since the release.

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bjornfor** [comment]
Have you suggested to upstream developers to make a release? I find it very wrong when downstreams like Nixpkgs have to use unreleased software. Making a release can be as simple as "git tag && git push" (although many have projects have some more steps). Unless planner is dead upstream, they should make a release!

**Comment by amiloradovsky** [comment]
@bjornfor No, but I was told that "No release planned in the
foreseeable future so it may take a while to reach distributions, but
at least it’s upstreamed now." -- So I doubt I should suggest it.

**Comment by bjornfor** [comment]
@amiloradovsky: I don't understand that quote at all. (If they don't make releases, the releases will _never_ reach distributions. What is upstreamed?)

**Comment by amiloradovsky** [comment]
@bjornfor Sorry, here's some context:

- https://github.com/NixOS/nixpkgs/pull/21012
- https://github.com/GNOME/planner/pulls?q=is%3Apr+is%3Aclosed
- and a recent discussion in the mailing list [looking for an archive link...]

**Comment by bjornfor** [comment]
@amiloradovsky: Ok, I see now. So you first proposed some patches to planner in Nixpkgs, to fix some bugs. It was suggested instead to apply those patches upstream. You proposed the patches upstream and they integrated them.

Now upstream has 5+ years of features and bug fixes since the latest release, but still have no plans of a release? That's crazy. You should definitely suggest they make a release :-)

**Comment by bjornfor** [comment]
> https://mail.gnome.org/archives/planner-dev-list/2017-April/thread.htm

"The requested URL /archives/planner-dev-list/2017-April/thread.htm was not found on this server."

**Comment by amiloradovsky** [comment]
@bjornfor Ah, it must be `html`. I probably accidentally deleted the last character.

**Comment by amiloradovsky** [comment]
The last patch has just been merged, fixed the revision.
Referencing a release would be fine too, contacted about it here:

- https://mail.gnome.org/archives/planner-dev-list/2017-April/msg00019.html

Waiting...

**Comment by amiloradovsky** [comment]
Hash check failed due to a redirect, fixed.

**Pull request merged**
