### PR TITLE
nixos/tests: test athUserRegulatoryDomain builds with default kernel

### PR DESCRIPTION
**Pull request by tomfitzhenry**
###### Motivation for this change

Ensure the default kernel builds when athUserRegulatoryDomain is set.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by veehaitch — APPROVED** [review]
Good thinking, thanks! LGTM

**Comment by veehaitch** [comment]
@ofborg test kernel-latest-ath-user-regd

**Comment by veehaitch** [comment]
The name `kernel-latest-ath-user-regd`, however,  is a little misleading now.

**Comment by tomfitzhenry** [comment]
> The name kernel-latest-ath-user-regd, however, is a little misleading now.

Good spot. Renamed to kernel-ath-user-regd.

**Comment by tomfitzhenry** [comment]
@ofborg test kernel-ath-user-regd

**Comment by veehaitch** [comment]
You missed the `name` attribute :)

https://github.com/NixOS/nixpkgs/blob/b86dba54a318e910b84fb0ddbc074219c20774d1/nixos/tests/kernel-latest-ath-user-regd.nix#L2

**Comment by veehaitch** [comment]
Maybe we should make `kernel-latest-ath-user-regd` an alias of `kernel-ath-user-regd` as some are used to run this test? We should at least point them to the right one, I guess.

**Comment by tomfitzhenry** [comment]
> Maybe we should make kernel-latest-ath-user-regd an alias of kernel-ath-user-regd as some are used to run this test? We should at least point them to the right one, I guess.

What's the usecase for folks running these tests themselves by name? Is this compatibility concern worth the alias?

**Comment by tomfitzhenry** [comment]
> You missed the name attribute :)

Fixed.

**Pull request closed without merging**
