### PR TITLE
linuxPackages.{mba6x_bl,rtl8812au,rtl8821au,.rtl88x2bu,lttng-modules}: update to latest version

### PR DESCRIPTION
**Pull request by NickCao**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 244620` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_10.lttng-modules</li>
    <li>linuxKernel.packages.linux_5_10_hardened.lttng-modules</li>
    <li>linuxKernel.packages.linux_5_4.lttng-modules</li>
    <li>linuxKernel.packages.linux_5_4_hardened.lttng-modules</li>
  </ul>
</details>
<details>
  <summary>29 packages failed to build:</summary>
  <ul>
    <li>linuxKernel.packages.linux_6_1.mba6x_bl</li>
    <li>linuxKernel.packages.linux_6_1.rtl8812au</li>
    <li>linuxKernel.packages.linux_6_1.rtl8821au</li>
    <li>linuxKernel.packages.linux_6_1.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_hardened.mba6x_bl (linuxKernel.packages.linux_6_1_hardened.mba6x_bl)</li>
    <li>linuxKernel.packages.linux_hardened.rtl8812au (linuxKernel.packages.linux_6_1_hardened.rtl8812au)</li>
    <li>linuxKernel.packages.linux_hardened.rtl8821au (linuxKernel.packages.linux_6_1_hardened.rtl8821au)</li>
    <li>linuxKernel.packages.linux_hardened.rtl88x2bu (linuxKernel.packages.linux_6_1_hardened.rtl88x2bu)</li>
    <li>linuxKernel.packages.linux_6_3.mba6x_bl</li>
    <li>linuxKernel.packages.linux_6_3.rtl8812au</li>
    <li>linuxKernel.packages.linux_6_3.rtl8821au</li>
    <li>linuxKernel.packages.linux_6_3.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_6_3_hardened.mba6x_bl</li>
    <li>linuxKernel.packages.linux_6_3_hardened.rtl8812au</li>
    <li>linuxKernel.packages.linux_6_3_hardened.rtl8821au</li>
    <li>linuxKernel.packages.linux_6_3_hardened.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_6_4.mba6x_bl</li>
    <li>linuxKernel.packages.linux_6_4_hardened.mba6x_bl</li>
    <li>linuxKernel.packages.linux_latest_libre.mba6x_bl</li>
    <li>linuxKernel.packages.linux_libre.mba6x_bl</li>
    <li>linuxKernel.packages.linux_libre.rtl8812au</li>
    <li>linuxKernel.packages.linux_libre.rtl8821au</li>
    <li>linuxKernel.packages.linux_libre.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_lqx.lttng-modules</li>
    <li>linuxKernel.packages.linux_lqx.mba6x_bl</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.mba6x_bl</li>
    <li>linuxKernel.packages.linux_xanmod.mba6x_bl</li>
    <li>linuxKernel.packages.linux_xanmod_latest.mba6x_bl (linuxKernel.packages.linux_xanmod_stable.mba6x_bl)</li>
    <li>linuxKernel.packages.linux_zen.mba6x_bl</li>
  </ul>
</details>
<details>
  <summary>82 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_14.lttng-modules</li>
    <li>linuxKernel.packages.linux_4_14.mba6x_bl</li>
    <li>linuxKernel.packages.linux_4_14.rtl8812au</li>
    <li>linuxKernel.packages.linux_4_14.rtl8821au</li>
    <li>linuxKernel.packages.linux_4_14.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_4_14_hardened.lttng-modules</li>
    <li>linuxKernel.packages.linux_4_14_hardened.mba6x_bl</li>
    <li>linuxKernel.packages.linux_4_14_hardened.rtl8812au</li>
    <li>linuxKernel.packages.linux_4_14_hardened.rtl8821au</li>
    <li>linuxKernel.packages.linux_4_14_hardened.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_4_19.lttng-modules</li>
    <li>linuxKernel.packages.linux_4_19.mba6x_bl</li>
    <li>linuxKernel.packages.linux_4_19.rtl8812au</li>
    <li>linuxKernel.packages.linux_4_19.rtl8821au</li>
    <li>linuxKernel.packages.linux_4_19.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_4_19_hardened.lttng-modules</li>
    <li>linuxKernel.packages.linux_4_19_hardened.mba6x_bl</li>
    <li>linuxKernel.packages.linux_4_19_hardened.rtl8812au</li>
    <li>linuxKernel.packages.linux_4_19_hardened.rtl8821au</li>
    <li>linuxKernel.packages.linux_4_19_hardened.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_5_10.mba6x_bl</li>
    <li>linuxKernel.packages.linux_5_10.rtl8812au</li>
    <li>linuxKernel.packages.linux_5_10.rtl8821au</li>
    <li>linuxKernel.packages.linux_5_10.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_5_10_hardened.mba6x_bl</li>
    <li>linuxKernel.packages.linux_5_10_hardened.rtl8812au</li>
    <li>linuxKernel.packages.linux_5_10_hardened.rtl8821au</li>
    <li>linuxKernel.packages.linux_5_10_hardened.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_5_15.lttng-modules</li>
    <li>linuxKernel.packages.linux_5_15.mba6x_bl</li>
    <li>linuxKernel.packages.linux_5_15.rtl8812au</li>
    <li>linuxKernel.packages.linux_5_15.rtl8821au</li>
    <li>linuxKernel.packages.linux_5_15.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_5_15_hardened.lttng-modules</li>
    <li>linuxKernel.packages.linux_5_15_hardened.mba6x_bl</li>
    <li>linuxKernel.packages.linux_5_15_hardened.rtl8812au</li>
    <li>linuxKernel.packages.linux_5_15_hardened.rtl8821au</li>
    <li>linuxKernel.packages.linux_5_15_hardened.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_5_4.mba6x_bl</li>
    <li>linuxKernel.packages.linux_5_4.rtl8812au</li>
    <li>linuxKernel.packages.linux_5_4.rtl8821au</li>
    <li>linuxKernel.packages.linux_5_4.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_5_4_hardened.mba6x_bl</li>
    <li>linuxKernel.packages.linux_5_4_hardened.rtl8812au</li>
    <li>linuxKernel.packages.linux_5_4_hardened.rtl8821au</li>
    <li>linuxKernel.packages.linux_5_4_hardened.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_6_1.lttng-modules</li>
    <li>linuxKernel.packages.linux_hardened.lttng-modules (linuxKernel.packages.linux_6_1_hardened.lttng-modules)</li>
    <li>linuxKernel.packages.linux_6_3.lttng-modules</li>
    <li>linuxKernel.packages.linux_6_3_hardened.lttng-modules</li>
    <li>linuxKernel.packages.linux_6_4.lttng-modules</li>
    <li>linuxKernel.packages.linux_6_4.rtl8812au</li>
    <li>linuxKernel.packages.linux_6_4.rtl8821au</li>
    <li>linuxKernel.packages.linux_6_4.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_6_4_hardened.lttng-modules</li>
    <li>linuxKernel.packages.linux_6_4_hardened.rtl8812au</li>
    <li>linuxKernel.packages.linux_6_4_hardened.rtl8821au</li>
    <li>linuxKernel.packages.linux_6_4_hardened.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_latest_libre.lttng-modules</li>
    <li>linuxKernel.packages.linux_latest_libre.rtl8812au</li>
    <li>linuxKernel.packages.linux_latest_libre.rtl8821au</li>
    <li>linuxKernel.packages.linux_latest_libre.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_libre.lttng-modules</li>
    <li>linuxKernel.packages.linux_lqx.rtl8812au</li>
    <li>linuxKernel.packages.linux_lqx.rtl8821au</li>
    <li>linuxKernel.packages.linux_lqx.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.lttng-modules</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.rtl8812au</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.rtl8821au</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_xanmod.lttng-modules</li>
    <li>linuxKernel.packages.linux_xanmod.rtl8812au</li>
    <li>linuxKernel.packages.linux_xanmod.rtl8821au</li>
    <li>linuxKernel.packages.linux_xanmod.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_xanmod_latest.lttng-modules (linuxKernel.packages.linux_xanmod_stable.lttng-modules)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.rtl8812au (linuxKernel.packages.linux_xanmod_stable.rtl8812au)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.rtl8821au (linuxKernel.packages.linux_xanmod_stable.rtl8821au)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.rtl88x2bu (linuxKernel.packages.linux_xanmod_stable.rtl88x2bu)</li>
    <li>linuxKernel.packages.linux_zen.lttng-modules</li>
    <li>linuxKernel.packages.linux_zen.rtl8812au</li>
    <li>linuxKernel.packages.linux_zen.rtl8821au</li>
    <li>linuxKernel.packages.linux_zen.rtl88x2bu</li>
  </ul>
</details>

**Comment by tjni** [comment]
Result of `nixpkgs-review pr 244620` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>66 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.hardkernel_4_14.lttng-modules</li>
    <li>linuxKernel.packages.hardkernel_4_14.mba6x_bl</li>
    <li>linuxKernel.packages.hardkernel_4_14.rtl8812au</li>
    <li>linuxKernel.packages.hardkernel_4_14.rtl8821au</li>
    <li>linuxKernel.packages.hardkernel_4_14.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_5_10.lttng-modules</li>
    <li>linuxKernel.packages.linux_5_10_hardened.lttng-modules</li>
    <li>linuxKernel.packages.linux_5_4.lttng-modules</li>
    <li>linuxKernel.packages.linux_5_4_hardened.lttng-modules</li>
    <li>linuxKernel.packages.linux_lqx.lttng-modules</li>
    <li>linuxKernel.packages.linux_lqx.mba6x_bl</li>
    <li>linuxKernel.packages.linux_lqx.rtl8812au</li>
    <li>linuxKernel.packages.linux_lqx.rtl8821au</li>
    <li>linuxKernel.packages.linux_lqx.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_xanmod.lttng-modules</li>
    <li>linuxKernel.packages.linux_xanmod.mba6x_bl</li>
    <li>linuxKernel.packages.linux_xanmod.rtl8812au</li>
    <li>linuxKernel.packages.linux_xanmod.rtl8821au</li>
    <li>linuxKernel.packages.linux_xanmod.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_xanmod_latest.lttng-modules</li>
    <li>linuxKernel.packages.linux_xanmod_latest.mba6x_bl</li>
    <li>linuxKernel.packages.linux_xanmod_latest.rtl8812au</li>
    <li>linuxKernel.packages.linux_xanmod_latest.rtl8821au</li>
    <li>linuxKernel.packages.linux_xanmod_latest.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_xanmod_stable.lttng-modules</li>
    <li>linuxKernel.packages.linux_xanmod_stable.mba6x_bl</li>
    <li>linuxKernel.packages.linux_xanmod_stable.rtl8812au</li>
    <li>linuxKernel.packages.linux_xanmod_stable.rtl8821au</li>
    <li>linuxKernel.packages.linux_xanmod_stable.rtl88x2bu</li>
    <li>linuxKernel.packages.linux_zen.lttng-modules</li>
    <li>linuxKernel.packages.linux_zen.mba6x_bl</li>
    <li>linuxKernel.packages.linux_zen.rtl8812au</li>
    <li>linuxKernel.packages.linux_zen.rtl8821au</li>
    <li>linuxKernel.packages.linux_zen.rtl88x2bu</li>
    <li>linuxPackages_5_10_hardened.lttng-modules</li>
    <li>linuxPackages_5_4_hardened.lttng-modules</li>
    <li>linuxPackages_hardkernel_latest.lttng-modules</li>
    <li>linuxPackages_hardkernel_latest.mba6x_bl</li>
    <li>linuxPackages_hardkernel_latest.rtl8812au</li>
    <li>linuxPackages_hardkernel_latest.rtl8821au</li>
    <li>linuxPackages_hardkernel_latest.rtl88x2bu</li>
    <li>linuxPackages_lqx.lttng-modules</li>
    <li>linuxPackages_lqx.mba6x_bl</li>
    <li>linuxPackages_lqx.rtl8812au</li>
    <li>linuxPackages_lqx.rtl8821au</li>
    <li>linuxPackages_lqx.rtl88x2bu</li>
    <li>linuxPackages_xanmod.lttng-modules</li>
    <li>linuxPackages_xanmod.mba6x_bl</li>
    <li>linuxPackages_xanmod.rtl8812au</li>
    <li>linuxPackages_xanmod.rtl8821au</li>
    <li>linuxPackages_xanmod.rtl88x2bu</li>
    <li>linuxPackages_xanmod_latest.lttng-modules</li>
    <li>linuxPackages_xanmod_latest.mba6x_bl</li>
    <li>linuxPackages_xanmod_latest.rtl8812au</li>
    <li>linuxPackages_xanmod_latest.rtl8821au</li>
    <li>linuxPackages_xanmod_latest.rtl88x2bu</li>
    <li>linuxPackages_xanmod_stable.lttng-modules</li>
    <li>linuxPackages_xanmod_stable.mba6x_bl</li>
    <li>linuxPackages_xanmod_stable.rtl8812au</li>
    <li>linuxPackages_xanmod_stable.rtl8821au</li>
    <li>linuxPackages_xanmod_stable.rtl88x2bu</li>
    <li>linuxPackages_zen.lttng-modules</li>
    <li>linuxPackages_zen.mba6x_bl</li>
    <li>linuxPackages_zen.rtl8812au</li>
    <li>linuxPackages_zen.rtl8821au</li>
    <li>linuxPackages_zen.rtl88x2bu</li>
  </ul>
</details>
<details>
  <summary>25 packages failed to build:</summary>
  <ul>
    <li>linuxPackages.mba6x_bl (linuxKernel.packages.linux_6_1.mba6x_bl)</li>
    <li>linuxPackages.rtl8812au (linuxKernel.packages.linux_6_1.rtl8812au)</li>
    <li>linuxPackages.rtl8821au (linuxKernel.packages.linux_6_1.rtl8821au)</li>
    <li>linuxPackages.rtl88x2bu (linuxKernel.packages.linux_6_1.rtl88x2bu)</li>
    <li>linuxPackages_hardened.mba6x_bl (linuxPackages_6_1_hardened.mba6x_bl)</li>
    <li>linuxPackages_hardened.rtl8812au (linuxPackages_6_1_hardened.rtl8812au)</li>
    <li>linuxPackages_hardened.rtl8821au (linuxPackages_6_1_hardened.rtl8821au)</li>
    <li>linuxPackages_hardened.rtl88x2bu (linuxPackages_6_1_hardened.rtl88x2bu)</li>
    <li>linuxKernel.packages.linux_6_3.mba6x_bl</li>
    <li>linuxKernel.packages.linux_6_3.rtl8812au</li>
    <li>linuxKernel.packages.linux_6_3.rtl8821au</li>
    <li>linuxKernel.packages.linux_6_3.rtl88x2bu</li>
    <li>linuxPackages_6_3_hardened.mba6x_bl (linuxKernel.packages.linux_6_3_hardened.mba6x_bl)</li>
    <li>linuxPackages_6_3_hardened.rtl8812au (linuxKernel.packages.linux_6_3_hardened.rtl8812au)</li>
    <li>linuxPackages_6_3_hardened.rtl8821au (linuxKernel.packages.linux_6_3_hardened.rtl8821au)</li>
    <li>linuxPackages_6_3_hardened.rtl88x2bu (linuxKernel.packages.linux_6_3_hardened.rtl88x2bu)</li>
    <li>linuxPackages_latest.mba6x_bl (linuxKernel.packages.linux_6_4.mba6x_bl)</li>
    <li>linuxPackages_6_4_hardened.mba6x_bl (linuxKernel.packages.linux_6_4_hardened.mba6x_bl)</li>
    <li>linuxPackages_latest-libre.mba6x_bl (linuxKernel.packages.linux_latest_libre.mba6x_bl)</li>
    <li>linuxPackages-libre.mba6x_bl (linuxKernel.packages.linux_libre.mba6x_bl)</li>
    <li>linuxPackages-libre.rtl8812au (linuxKernel.packages.linux_libre.rtl8812au)</li>
    <li>linuxPackages-libre.rtl8821au (linuxKernel.packages.linux_libre.rtl8821au)</li>
    <li>linuxPackages-libre.rtl88x2bu (linuxKernel.packages.linux_libre.rtl88x2bu)</li>
    <li>linuxPackages_testing_bcachefs.lttng-modules (linuxKernel.packages.linux_testing_bcachefs.lttng-modules)</li>
    <li>linuxPackages_testing_bcachefs.mba6x_bl (linuxKernel.packages.linux_testing_bcachefs.mba6x_bl)</li>
  </ul>
</details>
<details>
  <summary>66 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_14.lttng-modules</li>
    <li>linuxKernel.packages.linux_4_14.mba6x_bl</li>
    <li>linuxKernel.packages.linux_4_14.rtl8812au</li>
    <li>linuxKernel.packages.linux_4_14.rtl8821au</li>
    <li>linuxKernel.packages.linux_4_14.rtl88x2bu</li>
    <li>linuxPackages_4_14_hardened.lttng-modules (linuxKernel.packages.linux_4_14_hardened.lttng-modules)</li>
    <li>linuxPackages_4_14_hardened.mba6x_bl (linuxKernel.packages.linux_4_14_hardened.mba6x_bl)</li>
    <li>linuxPackages_4_14_hardened.rtl8812au (linuxKernel.packages.linux_4_14_hardened.rtl8812au)</li>
    <li>linuxPackages_4_14_hardened.rtl8821au (linuxKernel.packages.linux_4_14_hardened.rtl8821au)</li>
    <li>linuxPackages_4_14_hardened.rtl88x2bu (linuxKernel.packages.linux_4_14_hardened.rtl88x2bu)</li>
    <li>linuxKernel.packages.linux_4_19.lttng-modules</li>
    <li>linuxKernel.packages.linux_4_19.mba6x_bl</li>
    <li>linuxKernel.packages.linux_4_19.rtl8812au</li>
    <li>linuxKernel.packages.linux_4_19.rtl8821au</li>
    <li>linuxKernel.packages.linux_4_19.rtl88x2bu</li>
    <li>linuxPackages_4_19_hardened.lttng-modules (linuxKernel.packages.linux_4_19_hardened.lttng-modules)</li>
    <li>linuxPackages_4_19_hardened.mba6x_bl (linuxKernel.packages.linux_4_19_hardened.mba6x_bl)</li>
    <li>linuxPackages_4_19_hardened.rtl8812au (linuxKernel.packages.linux_4_19_hardened.rtl8812au)</li>
    <li>linuxPackages_4_19_hardened.rtl8821au (linuxKernel.packages.linux_4_19_hardened.rtl8821au)</li>
    <li>linuxPackages_4_19_hardened.rtl88x2bu (linuxKernel.packages.linux_4_19_hardened.rtl88x2bu)</li>
    <li>linuxKernel.packages.linux_5_10.mba6x_bl</li>
    <li>linuxKernel.packages.linux_5_10.rtl8812au</li>
    <li>linuxKernel.packages.linux_5_10.rtl8821au</li>
    <li>linuxKernel.packages.linux_5_10.rtl88x2bu</li>
    <li>linuxPackages_5_10_hardened.mba6x_bl (linuxKernel.packages.linux_5_10_hardened.mba6x_bl)</li>
    <li>linuxPackages_5_10_hardened.rtl8812au (linuxKernel.packages.linux_5_10_hardened.rtl8812au)</li>
    <li>linuxPackages_5_10_hardened.rtl8821au (linuxKernel.packages.linux_5_10_hardened.rtl8821au)</li>
    <li>linuxPackages_5_10_hardened.rtl88x2bu (linuxKernel.packages.linux_5_10_hardened.rtl88x2bu)</li>
    <li>linuxKernel.packages.linux_5_15.lttng-modules</li>
    <li>linuxKernel.packages.linux_5_15.mba6x_bl</li>
    <li>linuxKernel.packages.linux_5_15.rtl8812au</li>
    <li>linuxKernel.packages.linux_5_15.rtl8821au</li>
    <li>linuxKernel.packages.linux_5_15.rtl88x2bu</li>
    <li>linuxPackages_5_15_hardened.lttng-modules (linuxKernel.packages.linux_5_15_hardened.lttng-modules)</li>
    <li>linuxPackages_5_15_hardened.mba6x_bl (linuxKernel.packages.linux_5_15_hardened.mba6x_bl)</li>
    <li>linuxPackages_5_15_hardened.rtl8812au (linuxKernel.packages.linux_5_15_hardened.rtl8812au)</li>
    <li>linuxPackages_5_15_hardened.rtl8821au (linuxKernel.packages.linux_5_15_hardened.rtl8821au)</li>
    <li>linuxPackages_5_15_hardened.rtl88x2bu (linuxKernel.packages.linux_5_15_hardened.rtl88x2bu)</li>
    <li>linuxKernel.packages.linux_5_4.mba6x_bl</li>
    <li>linuxKernel.packages.linux_5_4.rtl8812au</li>
    <li>linuxKernel.packages.linux_5_4.rtl8821au</li>
    <li>linuxKernel.packages.linux_5_4.rtl88x2bu</li>
    <li>linuxPackages_5_4_hardened.mba6x_bl (linuxKernel.packages.linux_5_4_hardened.mba6x_bl)</li>
    <li>linuxPackages_5_4_hardened.rtl8812au (linuxKernel.packages.linux_5_4_hardened.rtl8812au)</li>
    <li>linuxPackages_5_4_hardened.rtl8821au (linuxKernel.packages.linux_5_4_hardened.rtl8821au)</li>
    <li>linuxPackages_5_4_hardened.rtl88x2bu (linuxKernel.packages.linux_5_4_hardened.rtl88x2bu)</li>
    <li>linuxPackages.lttng-modules (linuxKernel.packages.linux_6_1.lttng-modules)</li>
    <li>linuxPackages_hardened.lttng-modules (linuxPackages_6_1_hardened.lttng-modules)</li>
    <li>linuxKernel.packages.linux_6_3.lttng-modules</li>
    <li>linuxPackages_6_3_hardened.lttng-modules (linuxKernel.packages.linux_6_3_hardened.lttng-modules)</li>
    <li>linuxPackages_latest.lttng-modules (linuxKernel.packages.linux_6_4.lttng-modules)</li>
    <li>linuxPackages_latest.rtl8812au (linuxKernel.packages.linux_6_4.rtl8812au)</li>
    <li>linuxPackages_latest.rtl8821au (linuxKernel.packages.linux_6_4.rtl8821au)</li>
    <li>linuxPackages_latest.rtl88x2bu (linuxKernel.packages.linux_6_4.rtl88x2bu)</li>
    <li>linuxPackages_6_4_hardened.lttng-modules (linuxKernel.packages.linux_6_4_hardened.lttng-modules)</li>
    <li>linuxPackages_6_4_hardened.rtl8812au (linuxKernel.packages.linux_6_4_hardened.rtl8812au)</li>
    <li>linuxPackages_6_4_hardened.rtl8821au (linuxKernel.packages.linux_6_4_hardened.rtl8821au)</li>
    <li>linuxPackages_6_4_hardened.rtl88x2bu (linuxKernel.packages.linux_6_4_hardened.rtl88x2bu)</li>
    <li>linuxPackages_latest-libre.lttng-modules (linuxKernel.packages.linux_latest_libre.lttng-modules)</li>
    <li>linuxPackages_latest-libre.rtl8812au (linuxKernel.packages.linux_latest_libre.rtl8812au)</li>
    <li>linuxPackages_latest-libre.rtl8821au (linuxKernel.packages.linux_latest_libre.rtl8821au)</li>
    <li>linuxPackages_latest-libre.rtl88x2bu (linuxKernel.packages.linux_latest_libre.rtl88x2bu)</li>
    <li>linuxPackages-libre.lttng-modules (linuxKernel.packages.linux_libre.lttng-modules)</li>
    <li>linuxPackages_testing_bcachefs.rtl8812au (linuxKernel.packages.linux_testing_bcachefs.rtl8812au)</li>
    <li>linuxPackages_testing_bcachefs.rtl8821au (linuxKernel.packages.linux_testing_bcachefs.rtl8821au)</li>
    <li>linuxPackages_testing_bcachefs.rtl88x2bu (linuxKernel.packages.linux_testing_bcachefs.rtl88x2bu)</li>
  </ul>
</details>

**Comment by tjni** [comment]
The dates in the versions of the `rtl*` packages need to be updated. I like that these changes will fix some of the breakages related to the kernel updates. Thank you for working on this.

**Review by tjni — APPROVED** [review]

**Comment by raboof** [comment]
I ran into this as well, filed #246182 to track it

**Pull request merged**
