### PR TITLE
vulkan-tools: enable support for Darwin

### PR DESCRIPTION
**Pull request by reckenrode**
###### Description of changes

Enable building of vulkan-tools on Darwin. Note that `sandbox = relaxed` was used for testing the `sandboxProfile`.

Also includes two changes to MoltenVK to allow it to work:

* Fix incorrect ICD definition; and
* Export MoltenVK headers in a `dev` output.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by reckenrode** [comment]
The aarch64-darwin failures are normal for MoltenVK.

**Comment by reckenrode** [comment]
Result of `nixpkgs-review pr 169379` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>corectrl</li>
    <li>goverlay</li>
    <li>lutris</li>
    <li>lutris-free</li>
    <li>lutris-unwrapped</li>
    <li>qmplay2</li>
    <li>vulkan-tools</li>
  </ul>
</details>

**Comment by reckenrode** [comment]
Result of `nixpkgs-review pr 169379` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>lapce</li>
  </ul>
</details>
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>google-amber</li>
    <li>libplacebo</li>
    <li>wgpu-utils</li>
    <li>wine64 (wine64Packages.stableFull)</li>
    <li>wine64Packages.stagingFull</li>
    <li>wine64Packages.unstableFull</li>
  </ul>
</details>
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>ncnn</li>
    <li>realesrgan-ncnn-vulkan</li>
    <li>vulkan-loader</li>
    <li>vulkan-tools</li>
    <li>wine64Packages.base (wine64Packages.stable)</li>
    <li>wine64Packages.staging</li>
    <li>wine64Packages.unstable</li>
  </ul>
</details>

**Comment by reckenrode** [comment]
The wine64Packages.*Full failures are due to a build failure in `libpulseaudio`. Looks like the update to 15.0 doesn’t build on Darwin. I’ll see if I can fix that and open a separate PR if I can.

**Comment by reckenrode** [comment]
Looks like the pulseaudio issue also came up in #169336. I got it building too, but I’m not familiar with PulseAudio to feel confident enough to upstream or submit a PR with those fixes.

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 169379` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages marked as broken and skipped:</summary>
  <ul>
    <li>airshipper</li>
    <li>ajour</li>
    <li>fast-cli</li>
    <li>lapce</li>
    <li>lightly-qt</li>
    <li>puppeteer-cli</li>
    <li>sharedown</li>
    <li>sway-contrib.grimshot</li>
    <li>vimix-gtk-themes</li>
    <li>waybar</li>
    <li>whitesur-gtk-theme</li>
  </ul>
</details>
<details>
  <summary>11 packages failed to build:</summary>
  <ul>
    <li>darwin.moltenvk</li>
    <li>libplacebo</li>
    <li>vulkan-loader</li>
    <li>vulkan-tools</li>
    <li>wgpu-utils</li>
    <li>wine64 (wine64Packages.full ,wine64Packages.stableFull)</li>
    <li>wine64Packages.base (wine64Packages.stable)</li>
    <li>wine64Packages.staging</li>
    <li>wine64Packages.stagingFull</li>
    <li>wine64Packages.unstable</li>
    <li>wine64Packages.unstableFull</li>
  </ul>
</details>

**Comment by reckenrode** [comment]
Is Xcode not installed? Unfortunately, due to the old SDK on x86_64-darwin, MoltenVK requires Xcode to build.

**Review by Ralith — APPROVED** [review]
LGTM aside from whatever MacOS-specific issues are being wrestled with. In particular the ICD manifest substituteInPlace fix is very welcome.

**Comment by siraben** [comment]
Please rebase.

**Comment by reckenrode** [comment]
I rebased against master and retested on Darwin.

**Comment by reckenrode** [comment]
Result of `nixpkgs-review pr 169379` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>ddnet</li>
    <li>google-amber</li>
    <li>libplacebo</li>
    <li>realesrgan-ncnn-vulkan</li>
    <li>wgpu-utils</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>ncnn</li>
    <li>vulkan-loader</li>
    <li>vulkan-tools</li>
  </ul>
</details>

**Comment by reckenrode** [comment]
Result of `nixpkgs-review pr 169379` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>ddnet</li>
    <li>google-amber</li>
    <li>libplacebo</li>
    <li>wgpu-utils</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>ncnn</li>
    <li>realesrgan-ncnn-vulkan</li>
    <li>vulkan-loader</li>
    <li>vulkan-tools</li>
  </ul>
</details>

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 169379` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>ddnet</li>
    <li>google-amber</li>
    <li>libplacebo</li>
    <li>realesrgan-ncnn-vulkan</li>
    <li>wgpu-utils</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>ncnn</li>
    <li>vulkan-loader</li>
    <li>vulkan-tools</li>
  </ul>
</details>

**Comment by vcunat** [comment]
OfBorg was failing the build, and Hydra is failing the same way: https://hydra.nixos.org/job/nixpkgs/trunk/vulkan-tools.x86_64-darwin

**Comment by reckenrode** [comment]
Right. I need to set `hydraPlatforms` on anything that depends on MoltenVK. I’ll open a PR to fix the build failures. Thanks!

**Pull request merged**
