### PR TITLE
openexr 3

### PR DESCRIPTION
**Pull request by yu-re-ka**
## Description of changes

Most distros (Arch, Fedora, Alpine, Void) have removed OpenEXR 2.x by now, and are building everything with OpenEXR 3.x. We should do the same.

I have migrated most high profile applications to OpenEXR 3 and tested that they build.
However, it is a lot of effort to individually test that the applications are also picking up OpenEXR correctly after the change. Some builds might silently build a vendored version or disable EXR support.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by paperdigits** [comment]
Why do we want to remove openexr v2? It is actively maintained and developed software.
"Making sure that things build" is a pretty low bar to pass, and a lot of the applications on this list are quite complicated and interact with openexr in complicated ways.

If a specific package, like darktable, says it is compatible with openexr3, then great, we should move to it, but changing every package that depends on openexr to v3 carte blance without checking the dependencies of each package explicitly seems like a mistake.

**Comment by yu-re-ka** [comment]
I don't have a strong opinion here, but it just seems like a smart move. Less packages to maintain, less breakages to fix (openexr has been broken on musl a dozend times), probably a smaller closure size.

Since none of the other big distros are using it, it is going to slowly rot away and it will fall back to us to fix all these build issues once they arise.

https://github.com/void-linux/void-packages/pull/39852

**Comment by paperdigits** [comment]
The find-n-replace without checking what each application is compatible with seems like a terrible idea, especially since this PR proposes removing v2. If something ends up broken, then we have to reopen a PR to get v2 repackaged? 

Arch, Fedora, Alpine, Void seems like a very odd definition of "all the big distros" as well. We should make a decisions that make sense for NixOS, not follow what others are doing.

**Comment by yu-re-ka** [comment]
Again, I don't have a strong opinion.
I'm going to rework this to not remove openexr 2 but instead upgrade all occurances to openexr 3 where supported (and in some instances where the application is no longer maintained but there is a patch available, I would also apply that).

**Comment by yu-re-ka** [comment]
Changing only a few packages over to openexr 3 selectively is also turning out to be a bad idea.  
For instance, updating openexr dependency of pkgs.openimageio will make the pkgs.blender build fail, unless the pkgs.alembic and pkgs.blender dependencies of openexr are also updated (but then it 'just works' and is detected as offically supported).

So I'm once again questioning if globally changing over to openexr3 is not the best option.

**Pull request closed without merging**
