### PR TITLE
Set literal NIX_PATH in 'other distro' docs

### PR DESCRIPTION
**Pull request by frozenkro**
## Description of changes

Setting NIX_PATH to a hard-coded path for the nixos-install step of the "Installing from another Linux Distribution" docs.  

See NixOS/nix@ec9dd9a
From what I can tell, nix is no longer setting the NIX_PATH env var for non-NixOS Linux distros. 
This doesn't break typical package installs since it's falling back to a default path at runtime, but in this case the docs are attempting to use that env var in a separate context, _specifically_ for non-NixOS distros.

I'm assuming it should be ok to just set it to the profile's default `channels` dir, since that's where the tools installed earlier in the doc would have ended up.  

@NixOS/documentation-team

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by frozenkro** [comment]
Side note - Attempted to ping @NixOS/documentation-team as requested in contributions.md, but it doesn't seem like that group exists?

**Comment by JohnRTitor** [comment]
It does but the teams may not be visible to users who are not in the NixOS organisation yet.

**Comment by fricklerhandwerk** [comment]
> From what I can tell, nix is no longer setting the `NIX_PATH` env var for non-NixOS Linux distros.

I'm not sure what that means. `$NIX_PATH` was never set by default anywhere, but one can use it to override the search path set by `nix-path` in `nix.conf` or the `--nix-path` flag. There was a bug with the override logic that is now fixed in https://github.com/NixOS/nix/pull/11079

But instead of hardcoding it to a legacy value that may eventually get replaced with the XDG-compliant location, why not set `NIX_PATH=channel:nixpkgs-unstable`? (Overall I'd rather politely supersede all of the impure-for-no-good-reason `<nixpkgs>` stuff `nixos-rebuild` does with explicit calls to `lib.evalModules` by the user, but that's a can of worms for a different time.)

**Comment by frozenkro** [comment]
> But instead of hardcoding it to a legacy value that may eventually get replaced with the XDG-compliant location, why not set `NIX_PATH=channel:nixpkgs-unstable`?

Wasn't aware of this format, I'm new to nix.

I'll test it out later and update accordingly, thanks!

**Comment by frozenkro** [comment]
@fricklerhandwerk updated PR. I just removed the variable from the command, as you mentioned it is just an override of the existing config. The command works fine without setting NIX_PATH at all.

Also, this could just be an issue with my system, but setting `NIX_PATH=channel:nixpkgs-unstable` during the install command didn't seem to set the path properly. Docs only seem to include local paths and URLs for this var, if there is something I'm missing I'd be interested to know more.

**Comment by fricklerhandwerk** [comment]
Hm, weird. While Nix documentation is certainly still not complete on all that stuff, what works for sure is `-I nixpkgs=channel:nixpkgs-unstable`. Parsing those formats should the same code path for `NIX_PATH`, but maybe I missed something.

If you have the time, I recommend taking a stroll through the Nix codebase. A meaningful entry point is the `initStore()` procedure, and the `NIX_PATH` stuff happens in the `EvalState`, `EvalSettings` and `Args` classes.

**Pull request merged**
