### PR TITLE
altcoins.aeon: 0.12.8.0 -> 0.12.9.0

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change
Version bump

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by aanderse** [comment]
@GrahamcOfBorg build altcoins.aeon

**Comment by aanderse** [comment]
https://github.com/aeonix/aeon/releases/tag/v0.12.9.0-aeon

This is a point release with no major changes, recommended for all users according to upstream.

@fuwa0529 Did you intend to have a backport to 19.03 as well?

**Comment by fuwa0529** [comment]
@aanderse what needs to be done to backport? This crypto will likely hard fork soon, to a different POW. Backporting will likely not be worth it :D

**Comment by aanderse** [comment]
Alright was just checking. Thanks for the information.

**Pull request merged**
