### PR TITLE
python3Packages.polars: init at 0.13.19

### PR DESCRIPTION
**Pull request by happysalada**
###### Description of changes

init a new package. Polars is a dataframe manipulation library built on top of apache arrow

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
will merge this for now, but happy to take care of feedback.

**Comment by teh** [comment]
This doesn't build for me as of 3f0fa66f7377a8dbfc529342ce77691e4f8c4ae6. Relevant section:

```
error: failed to run custom build command for `libz-sys v1.1.3`
error: failed to run custom build command for `libz-sys v1.1.3`


Caused by:
Caused by:
  process didn't exit successfully: `/build/source/py-polars/target/release/build/libz-sys-ff5c51491e762dd9/build-script-build` (exit status: 101)
  process didn't exit successfully: `/build/source/py-polars/target/release/build/libz-sys-ff5c51491e762dd9/build-script-build` (exit status: 101)
  --- stdout
  --- stdout
  cargo:rerun-if-env-changed=LIBZ_SYS_STATIC
  cargo:rerun-if-env-changed=LIBZ_SYS_STATIC
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=build.rs
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  HOST_CMAKE = None
  CMAKE = None
  CMAKE = None
  running: "cmake" "/build/polars-0.13.19-vendor.tar.gz/libz-sys/src/zlib-ng" "-DBUILD_SHARED_LIBS=OFF" "-DZLIB_COMPAT=ON" "-DWITH_GZFILEOP=ON" "-DCMAKE_INSTALL_PREFIX=/build/source/py-polars/target/x86_64-unknown-linux-gnu/release/build/libz-sys-57cf93ddb5e58e9d/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/nix/store/61zfi5pmhb0d91422f186x26v7b52y5k-gcc-wrapper-11.3.0/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/nix/store/61zfi5pmhb0d91422f186x26v7b52y5k-gcc-wrapper-11.3.0/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/nix/store/61zfi5pmhb0d91422f186x26v7b52y5k-gcc-wrapper-11.3.0/bin/cc" "-DCMAKE_BUILD_TYPE=Release"
  running: "cmake" "/build/polars-0.13.19-vendor.tar.gz/libz-sys/src/zlib-ng" "-DBUILD_SHARED_LIBS=OFF" "-DZLIB_COMPAT=ON" "-DWITH_GZFILEOP=ON" "-DCMAKE_INSTALL_PREFIX=/build/source/py-polars/target/x86_64-unknown-linux-gnu/release/build/libz-sys-57cf93ddb5e58e9d/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/nix/store/61zfi5pmhb0d91422f186x26v7b52y5k-gcc-wrapper-11.3.0/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/nix/store/61zfi5pmhb0d91422f186x26v7b52y5k-gcc-wrapper-11.3.0/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/nix/store/61zfi5pmhb0d91422f186x26v7b52y5k-gcc-wrapper-11.3.0/bin/cc" "-DCMAKE_BUILD_TYPE=Release"


  --- stderr
  --- stderr
  thread 'main' panicked at '
  thread 'main' panicked at '
  failed to execute command: No such file or directory (os error 2)
  failed to execute command: No such file or directory (os error 2)
  is `cmake` not installed?
  is `cmake` not installed?
```

**Comment by happysalada** [comment]
Just tested and indeed the build fails.
There is no way to build libz dynamically, so I'm not sure how to fix this.
I've tried a couple of things, but all failed.
things like `LIBZ_SYS_STATIC=0` , adding cmake to the list of native dependencies will fail for other reasons.
There is an issue in libz-sys to allow to build dynamically, but it looks like the maintainer is uninterested.

**Comment by teh** [comment]
You could try sth like this - my build makes some progress but then complains about using unstable features. 

```diff
diff --git a/pkgs/development/python-modules/polars/default.nix b/pkgs/development/python-modules/polars/default.nix
index 5b1e1a5ecbb..e73e4976d36 100644
--- a/pkgs/development/python-modules/polars/default.nix
+++ b/pkgs/development/python-modules/polars/default.nix
@@ -5,6 +5,7 @@
 , rustPlatform
 , libiconv
 , fetchzip
+, cmake
 }:
 let
   pname = "polars";
@@ -31,9 +32,10 @@ buildPythonPackage {
     name = "${pname}-${version}";
     sha256 = "sha256-KEt8lITY4El2afuh2cxnrDkXGN3MZgfKQU3Pe2jECF0=";
   };
+  dontUseCmakeConfigure = true;
   cargoRoot = "py-polars";
 
-  nativeBuildInputs = with rustPlatform; [ cargoSetupHook maturinBuildHook ];
+  nativeBuildInputs = with rustPlatform; [ cargoSetupHook maturinBuildHook cmake ];
 
   buildInputs = lib.optionals stdenv.isDarwin [ libiconv ];
```

**Comment by happysalada** [comment]
Could you share the logs when you have a moment ?

**Comment by teh** [comment]
```
   Compiling arrow2 v0.10.1 (https://github.com/ritchie46/arrow2?branch=polars#da703ae3)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /build/polars-0.13.19-vendor.tar.gz/arrow2/src/lib.rs:8:39
  |
8 | #![cfg_attr(feature = "simd", feature(portable_simd))]
  |                                       ^^^^^^^^^^^^^


error: aborting due to previous error


For more information about this error, try `rustc --explain E0554`.

error: could not compile `arrow2` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `cargo rustc --message-format json --manifest-path Cargo.toml -j 8 --frozen --target x86_64-unknown-linux-gnu --release --lib -- -C link-arg=-s`
error: builder for '/nix/store/qfnqi5hs3x4xdb6d4f6rpaf63n1w74yn-python3.10-polars-0.13.19.drv' failed with exit code 1;
       last 10 log lines:
       > error: aborting due to previous error
       >
       >
       > For more information about this error, try `rustc --explain E0554`.
       >
       > error: could not compile `arrow2` due to 2 previous errors
       > warning: build failed, waiting for other jobs to finish...
       > 💥 maturin failed
       >   Caused by: Failed to build a native library through cargo
       >   Caused by: Cargo build finished with "exit status: 101": `cargo rustc --message-format json --manifest-path Cargo.toml -j 8 --frozen --target x86_64-unknown-linux-gnu --release --lib -- -C link-arg=-s`
       For full logs, run 'nix log /nix/store/qfnqi5hs3x4xdb6d4f6rpaf63n1w74yn-python3.10-polars-0.13.19.drv'.
```

**Comment by happysalada** [comment]
ok it doesn't look like something that will get solved tomorrow.
We will have to be patient on this and try again periodically.

**Comment by teh** [comment]
IMHO it's worth to either mark the package as broken or remove it from nixpkgs until the build works on stable. I wasted quite a bit of time trying to figure out whether it's me or nixpkgs. We can help save that time for others.

**Comment by happysalada** [comment]
fair enough https://github.com/NixOS/nixpkgs/pull/181878

**Pull request merged**
