### PR TITLE
R: remove qtbase.patch and fix few CRAN packages

### PR DESCRIPTION
**Pull request by lblasc**
###### Motivation for this change

~~Last R package update removed [prophet](https://cran.r-project.org/web/packages/prophet/index.html) which is again available with this update. I've also updated bioc-annotation-packages.nix and bioc-experiment-packages.nix.~~

Remove qtbase.patch which is leftover from last update and fix few CRAN packages.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by peti** [comment]
Test builds are running at https://hydra.nixos.org/jobset/nixpkgs/r-updates ...

**Comment by lblasc** [comment]
@peti can you please do another test build? openssl had broken configure script.

**Comment by lblasc** [comment]
rebased, I also bumped R to 4.0.2. Should be ready for merge.

**Comment by lblasc** [comment]
@peti anything else needed ? thx!

**Comment by moritzschaefer** [comment]
While R 4.0.2 and updated bioconductor already made it into master, the patch for openssl didn't. 
@lblasc, I can't test it on my machine at the moment, but would you be willing to quickly setup a new PR that fixes openssl?

**Comment by SuperSandro2000** [comment]
@peti friendly ping

**Pull request merged**
