### PR TITLE
 lua*Packages TLS updates

### PR DESCRIPTION
**Pull request by vcunat**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via all NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))  `prosody.x86_64-linux`
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] N/A Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after).  A couple kilobytes added.
- [ ] N/A, I think. Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
I tried generating these, but they wouldn't build, even if I overrode them to depend on openssl.  (I don't know what's wrong.)

So far I've done mainly basic testing around `knot-resolver`, but even https with TLS 1.3 seemed to work when I added the `openssl-1.1` branch locally.

### CODE REVIEW

**Comment by teto** [comment]
luasec seems to be on luarocks, wouldn't that makes sense to move it to the automated packages instead ?

**Comment by teto** [comment]
luaossl too for what it's worth xD . If you are willing to go through the process and have any trouble/question let me know.

**Comment by vcunat** [comment]
Feel free to try.

> I tried generating these, but they wouldn't build, even if I overrode them to depend on openssl. (I don't know what's wrong.)

**Comment by teto** [comment]
sorry completely missed this. Ok will try.

**Comment by vcunat** [comment]
The generated expression didn't contain openssl reference (not surprising), so I added it to `buildInputs` via the usual overrides, but they still couldn't find headers from the package.  I was probably doing something wrong, anyway I chose a quicker solution for now.

**Comment by teto** [comment]
if you feel confident enough to merge it, let's do it, I will investiage the issue later.
luarocks makes some assumptions on how paths are searched, so for instance if it finds X/include, it will look for the lib in X/lib and ignore Y/lib (or something along these lines IIRC) which is why sometimes it's necessary to specify manually the folders like
```
    extraConfig = ''
      variables = {
        LIBUUID_INCDIR="${pkgs.lib.getDev pkgs.libuuid}/include";
        LIBUUID_LIBDIR="${pkgs.lib.getLib pkgs.libuuid}/lib";
      }
    '';
```
upstream didn't seem too excited about "fixing" this. so maybe I could do it in our fork.

**Comment by vcunat** [comment]
It would be best to support and prefer `pkg-config` to search for dependencies.

**Comment by teto** [comment]
I can only agree https://github.com/luarocks/luarocks/issues/514

**Pull request merged**
