### PR TITLE
trilium-{desktop,server}: 0.57.5  -> 0.58.5

### PR DESCRIPTION
**Pull request by eliandoran**
###### Description of changes

Change log: https://github.com/zadam/trilium/releases/tag/v0.58.5

cc. @fliegendewurst

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by FliegendeWurst — CHANGES_REQUESTED** [review]
The patch `0001-Use-console-logger-instead-of-rolling-files.patch` doesn't apply cleanly.
Try the [updated patch file](https://github.com/NixOS/nixpkgs/files/10411601/0001-Use-console-logger-instead-of-rolling-files.txt).

**Comment by eliandoran** [comment]
@FliegendeWurst , you're absolutely right. Apparently I only tested the `trilium-desktop`, thanks for looking into it.
I've changed the patch with the one you've provided and the server builds successfully. The server test also passes. The desktop application was unchanged.

**Review by FliegendeWurst — APPROVED** [review]

**Comment by eliandoran** [comment]
@FliegendeWurst , bumped to the freshly released 0.58.5.

**Review by FliegendeWurst — APPROVED** [review]
:heavy_check_mark: sha256 values correct
:heavy_check_mark: trilium-desktop launches and works correctly
:heavy_check_mark: CI passes

**Comment by bobby285271** [comment]
@ofborg build trilium-desktop
@ofborg test trilium-server

**Pull request merged**
