### PR TITLE
go: strip binaries in /share

### PR DESCRIPTION
**Pull request by layus**
I have only tested this with go 1.5.
Reviews welcome for other versions of go.

### CODE REVIEW

**Comment by vcunat** [comment]
What? Binaries in `share/`?
> [...] that can be **shared among different architectures** of the same OS.

**Comment by layus** [comment]
@viric, @nbp, Do you have any idea why go has executables in share ?

**Comment by wkennington** [comment]
That's just the way it packages itself. Every distro has it that way and
it's hard to change.

**Comment by layus** [comment]
@wkennington I do not think it has to be that way. For example archlinux has in /usr/lib/go/ the same tree as we have in /nix/store/2zrmd44q1cy7vzbsb2n04lx15kkkld57-go-1.5.3/share/go/.
Their PKGBUILD exports GOROOT_FINAL=/usr/lib/go and GOROOT_BOOTSTRAP=/usr/lib/go[1] and moves some output dirs around after install. Debian also has most go files in /usr/lib/go/[2], but at the cost of an extensive golang-go.install[3].

I would not say that every distro has it that way. But it seems like the fix requires non-trivial modifications.

[1] https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/go#n32
[2] https://packages.debian.org/fr/sid/amd64/golang-go/filelist
[3] http://http.debian.net/debian/pool/main/g/golang/golang_1.6.1-2.debian.tar.xz

**Comment by layus** [comment]
Closing while we are working on #15339

**Pull request closed without merging**
