### PR TITLE
r-modules: Updated definitions of CRAN and Bioc packages.

### PR DESCRIPTION
**Pull request by TikhonJelvis**
Updated the R package definitions.

This involved two manual code changes:

  1. Removing a few deleted packages from default.nix
  2. Renaming the "assert" package to "r_assert" in generate-r-packages.R because "assert" is a keyword in Nix

I followed the steps in [the R manual section](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/r.section.md), testing the result with `nix-build test-evaluation.nix --dry-run`.

###### Motivation for this change

R package set was last updated >4 months ago (2020-08-19).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
darwin patch

```diff
diff --git a/pkgs/development/r-modules/default.nix b/pkgs/development/r-modules/default.nix
index 387a5d0bb63..7cdb5f72658 100644
--- a/pkgs/development/r-modules/default.nix
+++ b/pkgs/development/r-modules/default.nix
@@ -379,6 +379,7 @@ let
     rmutil = lib.optionals stdenv.isDarwin [ pkgs.libiconv ];
     robustbase = lib.optionals stdenv.isDarwin [ pkgs.libiconv ];
     SparseM = lib.optionals stdenv.isDarwin [ pkgs.libiconv ];
+    hexbin = lib.optionals stdenv.isDarwin [ pkgs.libiconv ];
     svKomodo = [ pkgs.which ];
     nat = [ pkgs.which ];
     nat_templatebrains = [ pkgs.which ];
```

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108268` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>rstudioWrapper: log was empty</li>
  </ul>
</details>
<details>
<summary>
5 packages built:
</summary>
<ul>
<li>python37Packages.rpy2</li>
<li>python38Packages.rpy2</li>
<li>rWrapper</li>
<li>sage</li>
<li>sageWithDoc</li>
</ul>
</details>

**Comment by TikhonJelvis** [comment]
I added @SuperSandro2000's Darwin patch and also fixed a bug with the `data_table` override in `default.nix`. The override had a `postInstall` step

```
postInstall = "mv $out/library/data.table/libs/{data.table,datatable}.so";
```

but after the package bump, `data.table.so` was already called `datatable.so` and the `mv` command would fail, so I removed that line.

I only caught the problem with `data_table` because it caused `nix-shell generate-shell.nix` to fail. Is there some kind of test I should run to check other R packages don't have similar problems?

Also, for context, I'm doing this bump now because I'm trying to fix the R Arrow package (#81761). I got a fix for that running locally, but found that I needed to bump the R packages so that the R Arrow package has the same version as the C++ Arrow library in Nixpkgs. But it also seems good to have more up to date package definitions anyway.

**Comment by SuperSandro2000** [comment]
> Is there some kind of test I should run to check other R packages don't have similar problems?

I don't know anything like this. If ofborg evals everything it is usually fine.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 108268` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python37Packages.rpy2</li>
    <li>python38Packages.rpy2</li>
  </ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108268` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
4 packages built:
</summary>
<ul>
<li>python37Packages.rpy2</li>
<li>python38Packages.rpy2</li>
<li>rWrapper</li>
<li>rstudioWrapper</li>
</ul>
</details>

**Review by peti — COMMENTED** [review]
Test builds are running at https://hydra.nixos.org/jobset/nixpkgs/r-updates ...

**Comment by peti** [comment]
Thank you very much for your efforts, everyone!

**Pull request merged**
