### PR TITLE
Update mt-st to verision 1.4

### PR DESCRIPTION
**Pull request by Arcanum417**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Lassulus** [comment]
commit/pr should say `mt-st: 1.3 -> 2.4`

**Comment by redvers** [comment]
Hi @Arcanum417 - were you able to test it with a tape library?… Just for my reference.

**Comment by Arcanum417** [comment]
Nope, not yet actually. I will probably have to at some point, I was pretty sad trying to figure out tape drives on NixOS. Gave up at the time.

**Comment by abathur** [comment]
I'm _tentatively_ closing this for a few _minor_ reasons:
- I suspect jumpstarting the review process and getting this across the finish line would require a few rounds of changes, and there isn't any signal that they'll happen. (There was one request to update the commit/PR name that hasn't been adopted. Standards in nixpkgs have also continued to evolve since this was opened, and a fresh review will likely require changes to meet them.)
- It doesn't sound like the author has a setup they can use to validate the version update at the moment, and it sounds like it will be non-trivial for them to get to that point. The package description makes me think this is the kind of thing that could bite end users if it doesn't get verified by someone who can use it (and add changelog entries if there are any breaking changes)?
- The upstream advanced to 1.7 back in April. Since the comments so far suggest this takes some time/prep/effort to validate, I think it makes sense to minimize the odds that someone invests effort in validating 1.4 when it would be better spent validating 1.7?

@Arcanum417 I don't mean this to discourage you from pursuing the change if you still need it. I'm more than happy to reopen it and help ask around for hands to get it moving in the right direction. (I'm also happy to help with the same if you decide to open another PR for this in the near future--just give me a mention.)

**Pull request closed without merging**
