### PR TITLE
heimdal: remove absolute path to pwd, replace patchPhase with postPa…

### LINKED ISSUE #347616: Build failure: heimdal
### Steps To Reproduce

1. `nix-build -A heimdal`

### Build log

```
Making all in hdb
make[2]: Entering directory '/private/tmp/nix-build-heimdal-7.8.0-unstable-2024-09-10.drv-2/source/lib/hdb'
../../lib/asn1/asn1_compile --option-file=./hdb.opt ./hdb.asn1 hdb_asn1
for genfile in 'asn1_Event.c asn1_GENERATION.c asn1_HDB_EncTypeList.c asn1_HDB_Ext_Aliases.c asn1_HDB_Ext_Constrained_delegation_acl.c asn1_HDB_Ext_KeyRotation.c asn1_HDB_Ext_KeySet.c asn1_HDB_Ext_Lan_Manager_
OWF.c asn1_HDB_Ext_Password.c asn1_HDB_Ext_PKINIT_acl.c asn1_HDB_Ext_PKINIT_cert.c asn1_HDB_Ext_PKINIT_hash.c asn1_HDB_EntryOrAlias.c asn1_HDB_entry_alias.c asn1_HDB_entry.c asn1_HDB_extension.c asn1_HDB_exten
sions.c asn1_HDB_keyset.c asn1_HDBFlags.c asn1_Key.c asn1_KeyRotation.c asn1_KeyRotationFlags.c asn1_Keys.c asn1_Salt.c'; do \
        clang-format -style='{BasedOnStyle: Mozilla, AlwaysBreakAfterReturnType: TopLevelDefinitions, IndentWidth: 4, SortIncludes: false}' -i ${genfile}; \
done
../../lib/com_err/compile_et hdb_err.et
cd .; perl ../../cf/make-proto.pl -q -P comment -o hdb-protos.h common.c db.c db3.c ext.c hdb-ldap.c hdb.c hdb-sqlite.c hdb-keytab.c hdb-mdb.c hdb-mitdb.c hdb_locl.h keys.c keytab.c dbinfo.c mkey.c ndbm.c prin
t.c || rm -f hdb-protos.h
updating hdb-protos.h
cd .; perl ../../cf/make-proto.pl -q -P comment -p hdb-private.h common.c db.c db3.c ext.c hdb-ldap.c hdb.c hdb-sqlite.c hdb-keytab.c hdb-mdb.c hdb-mitdb.c hdb_locl.h keys.c keytab.c dbinfo.c mkey.c ndbm.c pri
nt.c || rm -f hdb-private.h
updating hdb-private.h
make  all-am
make[3]: Entering directory '/private/tmp/nix-build-heimdal-7.8.0-unstable-2024-09-10.drv-2/source/lib/hdb'
  CC       test_dbinfo.o
  CC       common.lo
  CC       db.lo
db.c:54:5: error: use of undeclared identifier 'DB'
    DB *d = (DB*)db->hdb_db;
    ^
db.c:54:9: error: use of undeclared identifier 'd'
    DB *d = (DB*)db->hdb_db;
        ^
db.c:54:17: error: expected expression
    DB *d = (DB*)db->hdb_db;
                ^
db.c:54:14: error: use of undeclared identifier 'DB'
    DB *d = (DB*)db->hdb_db;
             ^
db.c:56:17: error: use of undeclared identifier 'd'
    heim_assert(d != 0, "Closing already closed HDB");
                ^
db.c:58:7: error: use of undeclared identifier 'd'
    (*d->close)(d);
      ^
db.c:58:17: error: use of undeclared identifier 'd'
    (*d->close)(d);
                ^
db.c:85:5: error: use of undeclared identifier 'DB'
    DB *d = (DB*)db->hdb_db;
    ^
db.c:85:9: error: use of undeclared identifier 'd'
    DB *d = (DB*)db->hdb_db;
        ^
db.c:85:17: error: expected expression
    DB *d = (DB*)db->hdb_db;
                ^
db.c:85:14: error: use of undeclared identifier 'DB'
    DB *d = (DB*)db->hdb_db;
             ^
db.c:90:17: error: use of undeclared identifier 'd'
        ret = (*d->sync)(d, 0);
                ^
db.c:90:26: error: use of undeclared identifier 'd'
        ret = (*d->sync)(d, 0);
                         ^
db.c:119:5: error: use of undeclared identifier 'DB'
    DB *d = (DB*)db->hdb_db;
    ^
db.c:119:9: error: use of undeclared identifier 'd'
    DB *d = (DB*)db->hdb_db;
        ^
db.c:119:17: error: expected expression
    DB *d = (DB*)db->hdb_db;
                ^
db.c:119:14: error: use of undeclared identifier 'DB'
    DB *d = (DB*)db->hdb_db;
             ^
db.c:120:5: error: use of undeclared identifier 'DBT'
    DBT key, value;
    ^
db.c:124:14: error: use of undeclared identifier 'd'
    code = (*d->seq)(d, &key, &value, flag);
             ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[3]: *** [Makefile:1115: db.lo] Error 1
make[3]: Leaving directory '/private/tmp/nix-build-heimdal-7.8.0-unstable-2024-09-10.drv-2/source/lib/hdb'
make[2]: *** [Makefile:932: all] Error 2
make[2]: Leaving directory '/private/tmp/nix-build-heimdal-7.8.0-unstable-2024-09-10.drv-2/source/lib/hdb'
make[1]: *** [Makefile:590: all-recursive] Error 1
make[1]: Leaving directory '/private/tmp/nix-build-heimdal-7.8.0-unstable-2024-09-10.drv-2/source/lib'
make: *** [Makefile:634: all-recursive] Error 1
```

### Additional context

This is happening on Darwin. The failure was triggered by https://github.com/NixOS/nixpkgs/pull/345129 that bumped the version.

### Notify maintainers

@jsierles @SuperSandro2000 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.6.0, macOS 14.6.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/ywvkxmphiy3d110p70qj174ici3zmhwg-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by SuperSandro2000**
…tch to not break patches

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by booxter** [comment]
This PR may be useful, but it does not resolve the linked issue for me. I've injected this PR into my flake env here: 3b3bbae1e15d645a547a44c6d207938a98f51444 but still see the same build error.

**Comment by gshpychka** [comment]
Result of `nixpkgs-review pr 347760` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>heimdal</li>
    <li>heimdal.dev</li>
    <li>heimdal.info</li>
    <li>heimdal.man</li>
    <li>openvas-smb</li>
  </ul>
</details>

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 347760`

---
### `x86_64-linux`
<details>
  <summary>:x: 4 packages failed to build:</summary>
  <ul>
    <li>citrix_workspace (citrix_workspace_24_05_0)</li>
    <li>citrix_workspace_23_09_0</li>
    <li>citrix_workspace_23_11_0</li>
    <li>citrix_workspace_24_02_0</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 5 packages built:</summary>
  <ul>
    <li>heimdal</li>
    <li>heimdal.dev</li>
    <li>heimdal.info</li>
    <li>heimdal.man</li>
    <li>openvas-smb</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 5 packages built:</summary>
  <ul>
    <li>heimdal</li>
    <li>heimdal.dev</li>
    <li>heimdal.info</li>
    <li>heimdal.man</li>
    <li>openvas-smb</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:x: 5 packages failed to build:</summary>
  <ul>
    <li>heimdal</li>
    <li>heimdal.dev</li>
    <li>heimdal.info</li>
    <li>heimdal.man</li>
    <li>openvas-smb</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:x: 5 packages failed to build:</summary>
  <ul>
    <li>heimdal</li>
    <li>heimdal.dev</li>
    <li>heimdal.info</li>
    <li>heimdal.man</li>
    <li>openvas-smb</li>
  </ul>
</details>

**Comment by khaneliman** [comment]
@ofborg build heimdal.passthru.tests

**Comment by h7x4** [comment]
Could you rename the commits to be prefixed with `heimdal` instead? `kerberos` could easily be misinterpreted as the MIT variant

**Comment by SuperSandro2000** [comment]
Builds fine locally and only changing the commit can't drip of ofborg.
I am going ahead and merging this to fix the linux build. We fix the darwin build in the other PR.

**Pull request merged**
