### PR TITLE
libvirt: fix hardcoded modules path

### PR DESCRIPTION
**Pull request by sskver**
## Description of changes

This implements what's in #285929, which is a better implementation then what's currently in #286330.
Replaces `/lib/modules` with `/run/current-system/kernel-modules/lib/modules` if it's built on linux. 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by skver0** [comment]
Maintainer pings: @fpletz @globin @lovesegfault

**Review by lovesegfault — APPROVED** [review]

**Comment by k3d3** [comment]
Is there anything left to do in this PR to get this merged?

**Comment by skver0** [comment]
I've been using it for the past couple of days, works perfectly. :+1:

**Comment by asimpson** [comment]
:+1: this needs to be merged. I've been running this patch locally and haven't noticed any odd side-effects.

**Comment by pshirshov** [comment]
Anyone, please? This is a critical issue.

**Comment by jtojnar** [comment]
Does not this suffer from the same issue initial version of the other PR did – not working on non-NixOS Linux?

**Comment by jtojnar** [comment]
Probably better revert this and merge the other PR.

**Comment by jtojnar** [comment]
This change is incompatible with that – it would indiscriminately patch out the NixOS path from the other PR.

That’s one of the reasons why explicit patches are better than `substitute` functions.

**Pull request merged**
