### PR TITLE
python3Packages.zeroconf: 0.28.8 -> 0.29.0

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 0.29.0

 Change log: https://github.com/jstasiak/python-zeroconf#0290

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@fabaff Can you take a look at the failing test?

**Comment by fabaff** [comment]
> @fabaff Can you take a look at the failing test?

Should be fixed with #117732

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 117733` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>41 packages built:</summary>
  <ul>
    <li>calibre</li>
    <li>catt</li>
    <li>cinnamon.warpinator</li>
    <li>cura</li>
    <li>curaLulzbot</li>
    <li>dpt-rp1-py</li>
    <li>expliot</li>
    <li>gnomecast</li>
    <li>home-assistant</li>
    <li>home-assistant-cli</li>
    <li>mkchromecast</li>
    <li>octoprint</li>
    <li>python38Packages.HAP-python</li>
    <li>python38Packages.PyChromecast</li>
    <li>python38Packages.aioesphomeapi</li>
    <li>python38Packages.aiohomekit</li>
    <li>python38Packages.devolo-home-control-api</li>
    <li>python38Packages.libpurecool</li>
    <li>python38Packages.libsoundtouch</li>
    <li>python38Packages.netdisco</li>
    <li>python38Packages.openwebifpy</li>
    <li>python38Packages.pyatv</li>
    <li>python38Packages.pynetdicom</li>
    <li>python38Packages.python-miio</li>
    <li>python38Packages.pyvizio</li>
    <li>python38Packages.webthing</li>
    <li>python38Packages.zeroconf</li>
    <li>python39Packages.HAP-python</li>
    <li>python39Packages.PyChromecast</li>
    <li>python39Packages.aioesphomeapi</li>
    <li>python39Packages.devolo-home-control-api</li>
    <li>python39Packages.libpurecool</li>
    <li>python39Packages.libsoundtouch</li>
    <li>python39Packages.netdisco</li>
    <li>python39Packages.openwebifpy</li>
    <li>python39Packages.pyatv</li>
    <li>python39Packages.pynetdicom</li>
    <li>python39Packages.python-miio</li>
    <li>python39Packages.pyvizio</li>
    <li>python39Packages.webthing</li>
    <li>python39Packages.zeroconf</li>
  </ul>
</details>

**Comment by fabaff** [comment]
@ofborg eval

**Comment by fabaff** [comment]
@ofborg eval

**Comment by SuperSandro2000** [comment]
@fabaff expliot is failing a test

**Comment by fabaff** [comment]
`pynetdicom` has randomly failing tests.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 117733` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>41 packages built:</summary>
  <ul>
    <li>calibre</li>
    <li>catt</li>
    <li>cinnamon.warpinator</li>
    <li>cura</li>
    <li>curaLulzbot</li>
    <li>dpt-rp1-py</li>
    <li>expliot</li>
    <li>gnomecast</li>
    <li>home-assistant</li>
    <li>home-assistant-cli</li>
    <li>mkchromecast</li>
    <li>octoprint</li>
    <li>python38Packages.HAP-python</li>
    <li>python38Packages.PyChromecast</li>
    <li>python38Packages.aioesphomeapi</li>
    <li>python38Packages.aiohomekit</li>
    <li>python38Packages.devolo-home-control-api</li>
    <li>python38Packages.libpurecool</li>
    <li>python38Packages.libsoundtouch</li>
    <li>python38Packages.netdisco</li>
    <li>python38Packages.openwebifpy</li>
    <li>python38Packages.pyatv</li>
    <li>python38Packages.pynetdicom</li>
    <li>python38Packages.python-miio</li>
    <li>python38Packages.pyvizio</li>
    <li>python38Packages.webthing</li>
    <li>python38Packages.zeroconf</li>
    <li>python39Packages.HAP-python</li>
    <li>python39Packages.PyChromecast</li>
    <li>python39Packages.aioesphomeapi</li>
    <li>python39Packages.devolo-home-control-api</li>
    <li>python39Packages.libpurecool</li>
    <li>python39Packages.libsoundtouch</li>
    <li>python39Packages.netdisco</li>
    <li>python39Packages.openwebifpy</li>
    <li>python39Packages.pyatv</li>
    <li>python39Packages.pynetdicom</li>
    <li>python39Packages.python-miio</li>
    <li>python39Packages.pyvizio</li>
    <li>python39Packages.webthing</li>
    <li>python39Packages.zeroconf</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 117733` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>3 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>dpt-rp1-py: log was empty</li>
<li>expliot: log was empty</li>
<li>python38Packages.pynetdicom: log was empty</li>
  </ul>
</details>
<details>
<summary>
38 packages built:
</summary>
<ul>
<li>calibre</li>
<li>catt</li>
<li>cinnamon.warpinator</li>
<li>cura</li>
<li>curaLulzbot</li>
<li>gnomecast</li>
<li>home-assistant</li>
<li>home-assistant-cli</li>
<li>mkchromecast</li>
<li>octoprint</li>
<li>python38Packages.HAP-python</li>
<li>python38Packages.PyChromecast</li>
<li>python38Packages.aioesphomeapi</li>
<li>python38Packages.aiohomekit</li>
<li>python38Packages.devolo-home-control-api</li>
<li>python38Packages.libpurecool</li>
<li>python38Packages.libsoundtouch</li>
<li>python38Packages.netdisco</li>
<li>python38Packages.openwebifpy</li>
<li>python38Packages.pyatv</li>
<li>python38Packages.python-miio</li>
<li>python38Packages.pyvizio</li>
<li>python38Packages.webthing</li>
<li>python38Packages.zeroconf</li>
<li>python39Packages.HAP-python</li>
<li>python39Packages.PyChromecast</li>
<li>python39Packages.aioesphomeapi</li>
<li>python39Packages.devolo-home-control-api</li>
<li>python39Packages.libpurecool</li>
<li>python39Packages.libsoundtouch</li>
<li>python39Packages.netdisco</li>
<li>python39Packages.openwebifpy</li>
<li>python39Packages.pyatv</li>
<li>python39Packages.pynetdicom</li>
<li>python39Packages.python-miio</li>
<li>python39Packages.pyvizio</li>
<li>python39Packages.webthing</li>
<li>python39Packages.zeroconf</li>
</ul>
</details>

**Comment by mweinelt** [comment]
```
builder for '/nix/store/cig6988fdq59hfb6dn9qla9w0jzpqc9z-python3.8-pynetdicom-1.5.6.drv' failed with exit code 1; last 10 log lines:
  -- Docs: https://docs.pytest.org/en/stable/warnings.html
  =========================== short test summary info ============================
  FAILED pynetdicom/apps/tests/test_qrscp_find.py::TestFindSCP::test_sr_query
  FAILED pynetdicom/apps/tests/test_qrscp_find.py::TestFindSCPCLI::test_sr_query
  FAILED pynetdicom/apps/tests/test_qrscp_get.py::TestGetSCP::test_basic - asse...
  FAILED pynetdicom/apps/tests/test_qrscp_get.py::TestGetSCPCLI::test_basic - a...
  FAILED pynetdicom/apps/tests/test_qrscp_move.py::TestMoveSCP::test_basic - as...
  FAILED pynetdicom/apps/tests/test_qrscp_move.py::TestMoveSCPCLI::test_basic
  = 6 failed, 2617 passed, 45 skipped, 599 deselected, 293 warnings in 1225.26s (0:20:25) =
  builder for '/nix/store/cig6988fdq59hfb6dn9qla9w0jzpqc9z-python3.8-pynetdicom-1.5.6.drv' failed with exit code 1
```

**Comment by mweinelt** [comment]
Squash the two commits disabling pynetdicom tests.

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 117733` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>dpt-rp1-py</li>
    <li>home-assistant</li>
    <li>python38Packages.aiohomekit</li>
  </ul>
</details>
<details>
  <summary>38 packages built:</summary>
  <ul>
    <li>calibre</li>
    <li>catt</li>
    <li>cinnamon.warpinator</li>
    <li>cura</li>
    <li>curaLulzbot</li>
    <li>expliot</li>
    <li>gnomecast</li>
    <li>home-assistant-cli</li>
    <li>mkchromecast</li>
    <li>octoprint</li>
    <li>python38Packages.HAP-python</li>
    <li>python38Packages.PyChromecast</li>
    <li>python38Packages.aioesphomeapi</li>
    <li>python38Packages.devolo-home-control-api</li>
    <li>python38Packages.libpurecool</li>
    <li>python38Packages.libsoundtouch</li>
    <li>python38Packages.netdisco</li>
    <li>python38Packages.openwebifpy</li>
    <li>python38Packages.pyatv</li>
    <li>python38Packages.pynetdicom</li>
    <li>python38Packages.python-miio</li>
    <li>python38Packages.pyvizio</li>
    <li>python38Packages.webthing</li>
    <li>python38Packages.zeroconf</li>
    <li>python39Packages.HAP-python</li>
    <li>python39Packages.PyChromecast</li>
    <li>python39Packages.aioesphomeapi</li>
    <li>python39Packages.devolo-home-control-api</li>
    <li>python39Packages.libpurecool</li>
    <li>python39Packages.libsoundtouch</li>
    <li>python39Packages.netdisco</li>
    <li>python39Packages.openwebifpy</li>
    <li>python39Packages.pyatv</li>
    <li>python39Packages.pynetdicom</li>
    <li>python39Packages.python-miio</li>
    <li>python39Packages.pyvizio</li>
    <li>python39Packages.webthing</li>
    <li>python39Packages.zeroconf</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 117733` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>43 packages built:</summary>
  <ul>
    <li>calibre</li>
    <li>catt</li>
    <li>cinnamon.warpinator</li>
    <li>cura</li>
    <li>curaLulzbot</li>
    <li>dpt-rp1-py</li>
    <li>expliot</li>
    <li>gnomecast</li>
    <li>home-assistant</li>
    <li>home-assistant-cli</li>
    <li>mkchromecast</li>
    <li>octoprint</li>
    <li>python38Packages.HAP-python</li>
    <li>python38Packages.PyChromecast</li>
    <li>python38Packages.aioesphomeapi</li>
    <li>python38Packages.aiohomekit</li>
    <li>python38Packages.devolo-home-control-api</li>
    <li>python38Packages.httpsig</li>
    <li>python38Packages.libpurecool</li>
    <li>python38Packages.libsoundtouch</li>
    <li>python38Packages.netdisco</li>
    <li>python38Packages.openwebifpy</li>
    <li>python38Packages.pyatv</li>
    <li>python38Packages.pynetdicom</li>
    <li>python38Packages.python-miio</li>
    <li>python38Packages.pyvizio</li>
    <li>python38Packages.webthing</li>
    <li>python38Packages.zeroconf</li>
    <li>python39Packages.HAP-python</li>
    <li>python39Packages.PyChromecast</li>
    <li>python39Packages.aioesphomeapi</li>
    <li>python39Packages.devolo-home-control-api</li>
    <li>python39Packages.httpsig</li>
    <li>python39Packages.libpurecool</li>
    <li>python39Packages.libsoundtouch</li>
    <li>python39Packages.netdisco</li>
    <li>python39Packages.openwebifpy</li>
    <li>python39Packages.pyatv</li>
    <li>python39Packages.pynetdicom</li>
    <li>python39Packages.python-miio</li>
    <li>python39Packages.pyvizio</li>
    <li>python39Packages.webthing</li>
    <li>python39Packages.zeroconf</li>
  </ul>
</details>

**Pull request merged**
