### PR TITLE
borgbackup: 1.0.11 -> 1.1.0

### PR DESCRIPTION
**Pull request by indiscipline**
###### Motivation for this change
Upgrade to latest stable version 1.1.0

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by indiscipline** [comment]
Ping @nckx

**Comment by nckx** [comment]
Hi @indiscipline! I see you've built this successfully on NixOS. Interesting: I had to [replace the Sphinx theme with Guzzle](http://lists.gnu.org/archive/html/guix-patches/2017-10/msg00306.html) when packaging this for another distribution. Is the documentation still[?] built and functional?

I'll look around for a *Nix box to test this on.

**Comment by bjornfor** [comment]
There is something weird going on here. The PR has conflict against master and the sha256 it updates to is the same hash as 1.0.11 already has in master.

**Comment by bjornfor** [comment]
But yay! Borg 1.1.0 is finally here!

**Comment by nckx** [comment]
As suspected:

```
Successfully installed borgbackup-1.1.0
/tmp/nix-build-borgbackup-1.1.0.drv-0/borgbackup-1.1.0
make: Entering directory '/tmp/nix-build-borgbackup-1.1.0.drv-0/borgbackup-1.1.0/docs'
sphinx-build -b singlehtml -d _build/doctrees   . _build/singlehtml
Running Sphinx v1.6.3
making output directory...

Exception occurred:
  File "conf.py", line 102, in <module>
    import guzzle_sphinx_theme
ModuleNotFoundError: No module named 'guzzle_sphinx_theme'
```

@indiscipline, could you explain how you managed to build this on NixOS?

> There is something weird going on here.

Indeed. It's also [based on a very old nixpkgs checkout](https://github.com/indiscipline/nixpkgs/commit/86fa63f20c5362946f3a3826b57c047537070a8a). Could you rebase, add the missing `guzzle_sphinx_theme` patch, and force-push?

Thanks!

**Comment by flokli** [comment]
@nckx Just sent in #30334, which can be used here to build docs.

**Comment by indiscipline** [comment]
Sorry, I've managed to screw this up at multiple stages. Thanks @flokli for #30334.

**Comment by flokli** [comment]
@indiscipline You're welcome :-) Somthing failed with the Xcode build (`SSLRead() return error -36`). Can you retry this one?

**Comment by bjornfor** [comment]
The patch only touched version, not sha256.

**Comment by bjornfor** [comment]
Oh, I see there was a follow-up commit that fixed the hash. Please squash these when found at PR time!

**Comment by Mic92** [comment]
Yeah, hit the wrong button.

**Pull request merged**
