### PR TITLE
photon: init at 1.0.7

### PR DESCRIPTION
**Pull request by bignaux**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build photon

**Comment by xeji** [comment]
After installing this with `nix-env`, it seems to look for `user-agents.txt` in the wrong place

```
[~/nixpkgs]$ photon -u http://nixos.org
      ____  __          __            
     / __ \/ /_  ____  / /_____  ____ 
    / /_/ / __ \/ __ \/ __/ __ \/ __ \
   / ____/ / / / /_/ / /_/ /_/ / / / /
  /_/   /_/ /_/\____/\__/\____/_/ /_/ 

Traceback (most recent call last):
  File "/nix/store/rbcakz87lxldn5a8blxvhbp2k7fx93xa-photon-1.0.7/share/photon/photon.py", line 188, in <module>
    with open(os.getcwd() + '/core/user-agents.txt', 'r') as uas:
IOError: [Errno 2] No such file or directory: '/home/me/nixpkgs/core/user-agents.txt'
```

**Comment by bignaux** [comment]
i donno how to solve this. --run "cd $out/share/photon"  is a bad idea since it runs in the nix-store so it can't save file. My previous iteration would work with --user-agent defined at command time.

**Comment by bignaux** [comment]
finally i did a patch to avoid this conception problem around os.getcwd().

**Pull request merged**
