### PR TITLE
arpack: 3.8.0 -> 3.9.1

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
Diff: https://github.com/opencollab/arpack-ng/compare/3.8.0...3.9.1

Changelog: https://github.com/opencollab/arpack-ng/blob/3.9.1/CHANGES

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by markuskowa** [comment]
@GrahamcOfBorg build octopus

**Review by markuskowa — APPROVED** [review]

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 216404` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>octavePackages.fem-fenics</li>
    <li>octavePackages.octproj</li>
    <li>octavePackages.vibes</li>
    <li>octavePackages.vrml</li>
  </ul>
</details>
<details>
  <summary>27 packages failed to build:</summary>
  <ul>
    <li>hal-hardware-analyzer</li>
    <li>igraph</li>
    <li>octavePackages.communications</li>
    <li>octavePackages.geometry</li>
    <li>octavePackages.mapping</li>
    <li>octavePackages.sparsersb</li>
    <li>openems</li>
    <li>python310Packages.explorerscript</li>
    <li>python310Packages.igraph</li>
    <li>python310Packages.kmapper</li>
    <li>python310Packages.leidenalg</li>
    <li>python310Packages.python-csxcad</li>
    <li>python310Packages.python-openems</li>
    <li>python310Packages.scikit-tda</li>
    <li>python310Packages.skytemple-dtef</li>
    <li>python310Packages.skytemple-files</li>
    <li>python310Packages.skytemple-ssb-debugger</li>
    <li>python311Packages.explorerscript</li>
    <li>python311Packages.igraph</li>
    <li>python311Packages.kmapper</li>
    <li>python311Packages.leidenalg</li>
    <li>python311Packages.python-csxcad</li>
    <li>python311Packages.python-openems</li>
    <li>python311Packages.skytemple-dtef</li>
    <li>python311Packages.skytemple-files</li>
    <li>python311Packages.skytemple-ssb-debugger</li>
    <li>skytemple</li>
  </ul>
</details>
<details>
  <summary>67 packages built:</summary>
  <ul>
    <li>arpack</li>
    <li>calculix</li>
    <li>gama</li>
    <li>librsb</li>
    <li>minc_widgets</li>
    <li>octave</li>
    <li>octaveFull</li>
    <li>octavePackages.arduino</li>
    <li>octavePackages.audio</li>
    <li>octavePackages.bim</li>
    <li>octavePackages.bsltl</li>
    <li>octavePackages.cgi</li>
    <li>octavePackages.control</li>
    <li>octavePackages.data-smoothing</li>
    <li>octavePackages.database</li>
    <li>octavePackages.dataframe</li>
    <li>octavePackages.dicom</li>
    <li>octavePackages.divand</li>
    <li>octavePackages.doctest</li>
    <li>octavePackages.econometrics</li>
    <li>octavePackages.financial</li>
    <li>octavePackages.fits</li>
    <li>octavePackages.fpl</li>
    <li>octavePackages.fuzzy-logic-toolkit</li>
    <li>octavePackages.ga</li>
    <li>octavePackages.general</li>
    <li>octavePackages.generate_html</li>
    <li>octavePackages.gsl</li>
    <li>octavePackages.image</li>
    <li>octavePackages.image-acquisition</li>
    <li>octavePackages.instrument-control</li>
    <li>octavePackages.interval</li>
    <li>octavePackages.io</li>
    <li>octavePackages.level-set</li>
    <li>octavePackages.linear-algebra</li>
    <li>octavePackages.lssa</li>
    <li>octavePackages.ltfat</li>
    <li>octavePackages.matgeom</li>
    <li>octavePackages.miscellaneous</li>
    <li>octavePackages.msh</li>
    <li>octavePackages.mvn</li>
    <li>octavePackages.nan</li>
    <li>octavePackages.ncarray</li>
    <li>octavePackages.netcdf</li>
    <li>octavePackages.nurbs</li>
    <li>octavePackages.ocl</li>
    <li>octavePackages.octclip</li>
    <li>octavePackages.optics</li>
    <li>octavePackages.optim</li>
    <li>octavePackages.optiminterp</li>
    <li>octavePackages.parallel</li>
    <li>octavePackages.quaternion</li>
    <li>octavePackages.queueing</li>
    <li>octavePackages.signal</li>
    <li>octavePackages.sockets</li>
    <li>octavePackages.splines</li>
    <li>octavePackages.statistics</li>
    <li>octavePackages.stk</li>
    <li>octavePackages.strings</li>
    <li>octavePackages.struct</li>
    <li>octavePackages.symbolic</li>
    <li>octavePackages.tisean</li>
    <li>octavePackages.tsa</li>
    <li>octavePackages.video</li>
    <li>octavePackages.windows</li>
    <li>octavePackages.zeromq</li>
    <li>octopus</li>
  </ul>
</details>

**Comment by NickCao** [comment]
```
error: builder for '/nix/store/yrh6i790xryskdh72cpks4pyj5nmqsg3-hyp2mat-0.0.18.drv' failed with exit code 1;
       last 10 log lines:
       > checking if g++ supports -c -o file.o... (cached) yes
       > checking whether the g++ linker (ld -m elf_x86_64) supports shared libraries... yes
       > checking dynamic linker characteristics... (cached) GNU/Linux ld.so
       > checking how to hardcode library paths into programs... immediate
       > checking for hpdf.h... yes
       > checking for sqrt in -lm... yes
       > checking for deflate in -lz... yes
       > checking for png_read_info in -lpng... yes
       > checking for HPDF_New in -lhpdf... no
       > configure: error: libhpdf library not foun
```

**Comment by markuskowa** [comment]
> ```
> error: builder for '/nix/store/yrh6i790xryskdh72cpks4pyj5nmqsg3-hyp2mat-0.0.18.drv' failed with exit code 1;
>        last 10 log lines:
>        > checking if g++ supports -c -o file.o... (cached) yes
>        > checking whether the g++ linker (ld -m elf_x86_64) supports shared libraries... yes
>        > checking dynamic linker characteristics... (cached) GNU/Linux ld.so
>        > checking how to hardcode library paths into programs... immediate
>        > checking for hpdf.h... yes
>        > checking for sqrt in -lm... yes
>        > checking for deflate in -lz... yes
>        > checking for png_read_info in -lpng... yes
>        > checking for HPDF_New in -lhpdf... no
>        > configure: error: libhpdf library not foun
> ```

That seems unrelated to the arpack update?

**Comment by dotlambda** [comment]
> configure: error: libhpdf library not foun

The same happens on master.

**Comment by dotlambda** [comment]
igraph fails with

> Error at src/linalg/arpack.c:1091 : ARPACK error - Could not build an Arnoldi factorization.

See https://github.com/igraph/igraph/issues/2311

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 216404` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>16 packages marked as broken and skipped:</summary>
  <ul>
    <li>octavePackages.fem-fenics</li>
    <li>octavePackages.image-acquisition</li>
    <li>octavePackages.level-set</li>
    <li>octavePackages.parallel</li>
    <li>octavePackages.sparsersb</li>
    <li>octavePackages.tisean</li>
    <li>octavePackages.vibes</li>
    <li>octavePackages.vrml</li>
    <li>python310Packages.kmapper</li>
    <li>python310Packages.kmapper.dist</li>
    <li>python310Packages.scikit-tda</li>
    <li>python310Packages.scikit-tda.dist</li>
    <li>python311Packages.kmapper</li>
    <li>python311Packages.kmapper.dist</li>
    <li>python311Packages.scikit-tda</li>
    <li>python311Packages.scikit-tda.dist</li>
  </ul>
</details>
<details>
  <summary>115 packages built:</summary>
  <ul>
    <li>arpack</li>
    <li>calculix</li>
    <li>checkov</li>
    <li>checkov.dist</li>
    <li>gama</li>
    <li>hal-hardware-analyzer</li>
    <li>igraph</li>
    <li>igraph.dev</li>
    <li>igraph.doc</li>
    <li>jupyter-all</li>
    <li>jupyter-all.dist</li>
    <li>librsb</li>
    <li>minc_widgets</li>
    <li>octave</li>
    <li>octaveFull</li>
    <li>octavePackages.arduino</li>
    <li>octavePackages.audio</li>
    <li>octavePackages.bim</li>
    <li>octavePackages.bsltl</li>
    <li>octavePackages.cgi</li>
    <li>octavePackages.communications</li>
    <li>octavePackages.control</li>
    <li>octavePackages.data-smoothing</li>
    <li>octavePackages.database</li>
    <li>octavePackages.dataframe</li>
    <li>octavePackages.dicom</li>
    <li>octavePackages.divand</li>
    <li>octavePackages.doctest</li>
    <li>octavePackages.econometrics</li>
    <li>octavePackages.financial</li>
    <li>octavePackages.fits</li>
    <li>octavePackages.fpl</li>
    <li>octavePackages.fuzzy-logic-toolkit</li>
    <li>octavePackages.ga</li>
    <li>octavePackages.general</li>
    <li>octavePackages.generate_html</li>
    <li>octavePackages.geometry</li>
    <li>octavePackages.gsl</li>
    <li>octavePackages.image</li>
    <li>octavePackages.instrument-control</li>
    <li>octavePackages.interval</li>
    <li>octavePackages.io</li>
    <li>octavePackages.linear-algebra</li>
    <li>octavePackages.lssa</li>
    <li>octavePackages.ltfat</li>
    <li>octavePackages.mapping</li>
    <li>octavePackages.matgeom</li>
    <li>octavePackages.miscellaneous</li>
    <li>octavePackages.msh</li>
    <li>octavePackages.mvn</li>
    <li>octavePackages.nan</li>
    <li>octavePackages.ncarray</li>
    <li>octavePackages.netcdf</li>
    <li>octavePackages.nurbs</li>
    <li>octavePackages.ocl</li>
    <li>octavePackages.octclip</li>
    <li>octavePackages.octproj</li>
    <li>octavePackages.optics</li>
    <li>octavePackages.optim</li>
    <li>octavePackages.optiminterp</li>
    <li>octavePackages.quaternion</li>
    <li>octavePackages.queueing</li>
    <li>octavePackages.signal</li>
    <li>octavePackages.sockets</li>
    <li>octavePackages.splines</li>
    <li>octavePackages.statistics</li>
    <li>octavePackages.stk</li>
    <li>octavePackages.strings</li>
    <li>octavePackages.struct</li>
    <li>octavePackages.symbolic</li>
    <li>octavePackages.tsa</li>
    <li>octavePackages.video</li>
    <li>octavePackages.windows</li>
    <li>octavePackages.zeromq</li>
    <li>octopus</li>
    <li>openems</li>
    <li>python310Packages.explorerscript</li>
    <li>python310Packages.explorerscript.dist</li>
    <li>python310Packages.igraph</li>
    <li>python310Packages.igraph.dist</li>
    <li>python310Packages.leidenalg</li>
    <li>python310Packages.leidenalg.dist</li>
    <li>python310Packages.python-csxcad</li>
    <li>python310Packages.python-csxcad.dist</li>
    <li>python310Packages.python-openems</li>
    <li>python310Packages.python-openems.dist</li>
    <li>python310Packages.skytemple-dtef</li>
    <li>python310Packages.skytemple-dtef.dist</li>
    <li>python310Packages.skytemple-files</li>
    <li>python310Packages.skytemple-files.dist</li>
    <li>python310Packages.skytemple-ssb-debugger</li>
    <li>python310Packages.skytemple-ssb-debugger.dist</li>
    <li>python310Packages.textnets</li>
    <li>python310Packages.textnets.dist</li>
    <li>python311Packages.explorerscript</li>
    <li>python311Packages.explorerscript.dist</li>
    <li>python311Packages.igraph</li>
    <li>python311Packages.igraph.dist</li>
    <li>python311Packages.leidenalg</li>
    <li>python311Packages.leidenalg.dist</li>
    <li>python311Packages.python-csxcad</li>
    <li>python311Packages.python-csxcad.dist</li>
    <li>python311Packages.python-openems</li>
    <li>python311Packages.python-openems.dist</li>
    <li>python311Packages.skytemple-dtef</li>
    <li>python311Packages.skytemple-dtef.dist</li>
    <li>python311Packages.skytemple-files</li>
    <li>python311Packages.skytemple-files.dist</li>
    <li>python311Packages.skytemple-ssb-debugger</li>
    <li>python311Packages.skytemple-ssb-debugger.dist</li>
    <li>python311Packages.textnets</li>
    <li>python311Packages.textnets.dist</li>
    <li>skytemple</li>
    <li>skytemple.dist</li>
    <li>vpv</li>
  </ul>
</details>

**Review by markuskowa — APPROVED** [review]

**Pull request merged**
