### PR TITLE
gnome.gnome-calculator: add itself to wrapper path

### PR DESCRIPTION
**Pull request by cab404**
## Description of changes

Search provider (in libexec) expects gnome-calculator to be in PATH, and this adds just that.

This fixes calculator in gnome search.
image

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by cab404** [comment]
@NixOS/gnome ?

**Comment by jtojnar** [comment]
Yeah, it is weird that the search provider would be in `XDG_DATA_DIRS` but not the program itself on `PATH`. What shell do you use, do you perhaps have some custom init/profile script?

I guess the late binding is not necessary so patch like this might be okay.

**Comment by cab404** [comment]
> I cannot reproduce this problem on current (give or take a day) master:
> 
> image
> 
> So I'm not sure whether this is strictly necessary, or if you're experiencing some other issue?

Yup, I do. Calculator search provider just doesn't work, and spews errors!)

```
Nov 27 01:34:35 eris .gnome-calculat[541128]: search-provider.vala:117: Failed to spawn Calculator: Failed to execute child process “gnome-calculator” (No such file or directory)
```

What exactly adds it to your path? Mine is being launched in pretty much empty environment.

**Comment by cab404** [comment]
> Yeah, it is weird that the search provider would be in `XDG_DATA_DIRS` but not the program itself on `PATH`. What shell do you use, do you perhaps have some custom init/profile script?
> 
> I guess the late binding is not necessary so patch like this might be okay.

I am using home-manager, https://github.com/cab404/home/blob/master/modules/gnome/system.nix, https://github.com/cab404/home/blob/master/modules/gnome/home.nix

**Comment by cab404** [comment]
Weirdly enough, the issue disappeared after updating to 777a7125e8463950d202d6162d26016bcd43f81c

**Comment by amaxine** [comment]
As you've mentioned you're no longer experiencing the problem, and there's no clear cause, I'm going to close this.

**Pull request closed without merging**
