### PR TITLE
ceph: 17.2.5 -> 18.2.0

### PR DESCRIPTION
**Pull request by nh2**
## Description of changes

Changelog: https://docs.ceph.com/en/latest/releases/reef/#v18-2-0-reef

See commit message for details on the build changes made.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [x] [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by spacekitteh** [comment]
This works for me! @krav @johanot @adevress

**Comment by spacekitteh** [comment]
(Or rather, after rebasing it, it works)

**Comment by spacekitteh** [comment]
Can this please be merged? :)

**Comment by nh2** [comment]
If possible, I'd like to get another "seems to be working for my cluster/usage" from another NixOS Ceph user:

CC @adev @ak @johanot @krav and from past PRs @srhb @mweinelt @wkennington

**Comment by srhb** [comment]
I'm sorry, Things:tm: came up this week and I'm unlikely to make it in time since I need our staging cluster on 17 until at least next week. If you can wait, I am still happy to do the testing on it as soon as I can, but otherwise I won't hold this back.

**Comment by rodarima** [comment]
So far seems to be working fine in our cluster too.

**Comment by nh2** [comment]
> So far seems to be working fine in our cluster too.

I'd merge it on this second report, but Github is currently degrated as per status.github.com, so the merge button is not available.

image

**Pull request merged**
