### PR TITLE
nodePackages.pkg: init at 5.3.0

### PR DESCRIPTION
**Pull request by CMCDragonkai**
###### Motivation for this change

The vercel/pkg is used for packaging NodeJS applications into single executable files for Linux, Mac, Windows.

This is similar to https://github.com/NixOS/nixpkgs/pull/115230 but for CLI programs.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
This is currently not working because something is broken in the node package instructions: https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/node.section.md

When running this:

> Run the script: (cd pkgs/development/node-packages && ./generate.sh).

We end up with:

```
http request GET https://registry.npmjs.org/@bitwarden%2Fcli
http 200 https://registry.npmjs.org/@bitwarden%2Fcli
fetching local directory: jslib/common from @bitwarden/cli
Error: ENOENT: no such file or directory, open '/home/cmcdragonkai/Projects/nixpkgs/pkgs/development/node-packages/@bitwarden/cli/jslib/common/package.json'
```

Then the `generate.sh` script breaks and we cannot proceed.

**Comment by CMCDragonkai** [comment]
Is anyone able to fix the node packages instructions so I can proceed to package this?

**Comment by CMCDragonkai** [comment]
I've had to remove `@bitwarden/cli` to make allow the `generate.sh` script to continue. After doing this, it works, and we are able to build and run the `vercel/pkg`.

**Comment by CMCDragonkai** [comment]
It was this commit that caused the change for bitwarden/cli: https://github.com/bitwarden/jslib/commit/1016bbfb9eb28c220de8d2ab86d1f2757328f254 It resulted in a new directory `jslib/common` which didn't exist before.

So I think node2nix is struggling to build bitwarden now.

If there's a way to bring vercel/pkg without attempting to update bitwarden, then this PR could be used, and somebody else has to fix `@bitwarden/cli`.

**Comment by CMCDragonkai** [comment]
I've added back `@bitwarden/cli` manually.

**Comment by CMCDragonkai** [comment]
This is now ready for merge.

**Comment by cole-h** [comment]
@ofborg eval

(Sorry, ofborg's certs recently had an issue, meaning that it was unable to
react to PRs. This has been fixed, but all PRs filed in this period will need
ofborg to be manually kicked off.)

**Comment by CMCDragonkai** [comment]
@cole-h can you help merge this. This PR is ready to be merged!

**Pull request merged**
