### PR TITLE
vscode-extensions.skellock.just: init at 2.0.0

### PR DESCRIPTION
**Pull request by maximsmol**
###### Motivation for this change

Add a VSCode extension for [just](https://github.com/casey/just)

###### Things done

- Built on platform(s)
  - [N/A] x86_64-linux
  - [N/A] aarch64-linux
  - [N/A] x86_64-darwin
  - [N/A] aarch64-darwin
- [N/A] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [N/A] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [N/A] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [N/A] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [N/A] (Package updates) Added a release notes entry if the change is major or breaking
  - [N/A] (Module updates) Added a release notes entry if the change is significant
  - [N/A] (Module addition) Added a release notes entry if adding a new NixOS module
  - [N/A] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
There is a recent change that moved `misc/vscode-extensions` to `applications/editors/vscode/extensions` (#160344), do you mind update your PR to resolve the merge conflict?

**Comment by maximsmol** [comment]
@bobby285271 should be good to go

**Comment by maximsmol** [comment]
is this PR good to go? just making sure I'm not holding this back

**Comment by bobby285271** [comment]
@ofborg build vscode-extensions.skellock.just

**Review by bobby285271 — APPROVED** [review]
Sorry, this got lost in my inbox. I pushed more changes hope you don't mind. Diff LGTM if ofborg is happy.


I tested the syntax highlighting myself but didn't test other things, as you didn't check any of the `Built on platform(s)` items (on the PR description), maybe you will wish to test the package yourself, you can do it by

```
nix-build -I nixpkgs=. -E 'with import <nixpkgs> { config= { allowUnfree = true; }; }; vscode-with-extensions.override { vscodeExtensions = with vscode-extensions; [ skellock.just ]; }'
```

A note that https://github.com/skellock/vscode-just has no development since 2017, maybe you will wish to look for some active forks or replacements.

**Comment by maximsmol** [comment]
great, thanks for the feedback!

just for anyone stumbling upon this in the future:
- I know the extension is unmaintained, it is nevertheless functional as of today
- I looked for active forks, none seem to be maintained either. I might make a fork of my own soon-ish

**Pull request merged**
