### PR TITLE
zxing-cpp: 1.4.0 -> 2.1.0

### PR DESCRIPTION
**Pull request by felixsinger**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by trofi — APPROVED** [review]

**Review by trofi — CHANGES_REQUESTED** [review]
Can you check if you can build `gst-plugins-bad-1.20.3` with it? For me it fails due to unconditional `c++17` use:

```
/nix/store/w7y570ccfadwrbpfrpj2mypl6q02bg79-zxing-cpp-2.0.0/include/ZXing/BarcodeFormat.h:59:44: error: 'string_view' is not a member of 'std'
   59 | BarcodeFormat BarcodeFormatFromString(std::string_view str);
      |                                            ^~~~~~~~~~~
/nix/store/w7y570ccfadwrbpfrpj2mypl6q02bg79-zxing-cpp-2.0.0/include/ZXing/BarcodeFormat.h:59:44: note: 'std::string_view' is only available from C++17 onwards
```

**Comment by Artturin** [comment]
When this branch is applied to current master it no longer fails

**Comment by Artturin** [comment]
Rebased onto staging master merge-base

**Comment by K900** [comment]
This seems to have fallen through the cracks, any objections to merging for the next cycle?

**Comment by AndersonTorres** [comment]
> This seems to have fallen through the cracks, any objections to merging for the next cycle?

Ofborg has four objections :)

**Comment by K900** [comment]
Those are timeouts, not build failures. Pretty normal for a staging change really.

@ofborg build zxing-cpp

**Comment by Artturin** [comment]
```
error: builder for '/nix/store/rm209sfg1bscmqqdid9jd5kdal5aqxxn-python3.10-zxing_cpp-2.1.0.drv' failed with exit code 1;
       last 10 log lines:
       > Using setuptoolsCheckPhase
       > unpacking sources
       > unpacking source archive /nix/store/89f94l1vfk27ydyfsh9r8ar46q45r34z-source
       > source root is source/wrappers/python
       > setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/wrappers/python/zxing.cpp
       > patching sources
       > applying patch /nix/store/pmandvprp9lrlxmklh5xnyddia22isiq-use-nixpkgs-pybind11.patch
       > patching file CMakeLists.txt
       > Hunk #1 FAILED at 20.
       > 1 out of 1 hunk FAILED -- saving rejects to file CMakeLists.txt.rej
       For full logs, run 'nix log /nix/store/rm209sfg1bscmqqdid9jd5kdal5aqxxn-python3.10-zxing_cpp-2.1.0.drv'.
```

`python3Packages.zxing_cpp` should be added to passthru.tests

**Comment by K900** [comment]
@ofborg build python3Packages.zxing_cpp

**Comment by jys1670** [comment]
This should probably include update of python package since it is built from the same `src`. The following `./use-nixpkgs-pybind11.patch` applies fine on x86_64-linux for me, resulting in successful build:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 5b2a415..ac43a98 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -18,13 +18,12 @@ if (NOT hasParent)
     set(BUILD_DEPENDENCIES "AUTO")
     if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/core)
         add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/core ZXing EXCLUDE_FROM_ALL)
-        include(${CMAKE_CURRENT_SOURCE_DIR}/zxing.cmake)
     else()
         message(FATAL_ERROR "Unable to locate zxing source code")
     endif()
 endif()
 
-zxing_add_package(pybind11 pybind11 ${pybind11_git_repo} ${pybind11_git_rev})
+find_package(pybind11 CONFIG)
 
 # build the python module
 pybind11_add_module(zxingcpp zxing.cpp)

```

**Comment by AndersonTorres** [comment]
> This should probably include update of python package since it is built from the same `src`. The following `./use-nixpkgs-pybind11.patch` applies fine on x86_64-linux for me, resulting in successful build:

It did not apply cleanly here.

**Comment by jys1670** [comment]
> > This should probably include update of python package since it is built from the same `src`. The following `./use-nixpkgs-pybind11.patch` applies fine on x86_64-linux for me, resulting in successful build:
> 
> It did not apply cleanly here.

Well, perhaps I messed up somewhere, it seemed to work in derivation with src and patches updated via `overrideAttrs`.
Anyways, thanks for taking care of that one!

**Pull request closed without merging**
