### PR TITLE
[20.09] chromium: Backport various patches from nixos-unstable

### PR DESCRIPTION
**Pull request by primeos**
###### Motivation for this change

Backport additional patches from nixos-unstable to keep the differences to a minimum and get various improvements.
This'll better work...

**I can run the VM test but it would be ideal if someone could test `chromium` (warning: takes very long to build) manually on NixOS 20.09 as the switch to the system libraries (etc.) could introduce regressions.**

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by thiagokokada — COMMENTED** [review]
Code wise LGTM, I am trying to build it now (but I can't guarantee that I will have the patience to build everything).

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 108231` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>chromium</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>chromedriver</li>
    <li>google-chrome-dev</li>
    <li>selendroid</li>
    <li>selenium-server-standalone</li>
  </ul>
</details>

**Comment by primeos** [comment]
The VM test was fine so I'll go ahead and hope for the best :)

> chromium seems to have failed to build thanks to a lack of space, but I have sufficient space in my disk thinking.

Could be due to `/tmp` being too small or running out of inodes.

**Comment by thiagokokada** [comment]
> Could be due to /tmp being too small or running out of inodes.

Makes sense, I use `tmpOnTmpfs = true;`.

**Pull request merged**
