### PR TITLE
shaderc: 2022.4 -> 2023.8

### PR DESCRIPTION
**Pull request by Ralith**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gepbird** [comment]
Result of `nixpkgs-review pr 262415` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>15 packages marked as broken and skipped:</summary>
  <ul>
    <li>adl</li>
    <li>feishin</li>
    <li>obs-studio-plugins.obs-hyperion</li>
    <li>python310Packages.dm-sonnet</li>
    <li>python310Packages.dm-sonnet.dist</li>
    <li>python310Packages.tensorflow-datasets</li>
    <li>python310Packages.tensorflow-datasets.dist</li>
    <li>rocmPackages.llvm.flang</li>
    <li>rocmPackages.llvm.flang.doc</li>
    <li>rocmPackages.llvm.flang.info</li>
    <li>rocmPackages.llvm.flang.man</li>
    <li>rocmPackages_5.llvm.flang</li>
    <li>rocmPackages_5.llvm.flang.doc</li>
    <li>rocmPackages_5.llvm.flang.info</li>
    <li>rocmPackages_5.llvm.flang.man</li>
  </ul>
</details>
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>jellyfin-mpv-shim</li>
    <li>jellyfin-mpv-shim.dist</li>
    <li>warzone2100</li>
  </ul>
</details>
<details>
  <summary>228 packages built:</summary>
  <ul>
    <li>MIDIVisualizer</li>
    <li>ani-cli</li>
    <li>anime-downloader</li>
    <li>anime-downloader.dist</li>
    <li>anki</li>
    <li>anki.dist</li>
    <li>anki.doc</li>
    <li>anki.man</li>
    <li>arcanPackages.all-wrapped</li>
    <li>arcanPackages.arcan</li>
    <li>arcanPackages.arcan-wrapped</li>
    <li>arcanPackages.cat9-wrapped</li>
    <li>arcanPackages.durden-wrapped</li>
    <li>ffmpeg-full (arcanPackages.ffmpeg ,ffmpeg_6-full)</li>
    <li>ffmpeg-full.bin (arcanPackages.ffmpeg.bin ,ffmpeg_6-full.bin)</li>
    <li>ffmpeg-full.data (arcanPackages.ffmpeg.data ,ffmpeg_6-full.data)</li>
    <li>ffmpeg-full.dev (arcanPackages.ffmpeg.dev ,ffmpeg_6-full.dev)</li>
    <li>ffmpeg-full.doc (arcanPackages.ffmpeg.doc ,ffmpeg_6-full.doc)</li>
    <li>ffmpeg-full.lib (arcanPackages.ffmpeg.lib ,ffmpeg_6-full.lib)</li>
    <li>ffmpeg-full.man (arcanPackages.ffmpeg.man ,ffmpeg_6-full.man)</li>
    <li>arcanPackages.pipeworld-wrapped</li>
    <li>arcanPackages.prio-wrapped</li>
    <li>arcanPackages.xarcan</li>
    <li>audiobookshelf</li>
    <li>celluloid</li>
    <li>corrscope</li>
    <li>corrscope.dist</li>
    <li>cplay-ng</li>
    <li>cplay-ng.dist</li>
    <li>curseradio</li>
    <li>curseradio.dist</li>
    <li>deepin.dde-gsettings-schemas</li>
    <li>deepin.deepin-movie-reborn</li>
    <li>deepin.deepin-movie-reborn.dev</li>
    <li>deepin.deepin-music</li>
    <li>deepin.deepin-voice-note</li>
    <li>dmlive</li>
    <li>dra-cla</li>
    <li>eaglemode</li>
    <li>emulationstation</li>
    <li>ff2mpv</li>
    <li>ffcast</li>
    <li>ffmpeg_4-full</li>
    <li>ffmpeg_4-full.bin</li>
    <li>ffmpeg_4-full.data</li>
    <li>ffmpeg_4-full.dev</li>
    <li>ffmpeg_4-full.doc</li>
    <li>ffmpeg_4-full.lib</li>
    <li>ffmpeg_4-full.man</li>
    <li>ffmpeg_5-full</li>
    <li>ffmpeg_5-full.bin</li>
    <li>ffmpeg_5-full.data</li>
    <li>ffmpeg_5-full.dev</li>
    <li>ffmpeg_5-full.doc</li>
    <li>ffmpeg_5-full.lib</li>
    <li>ffmpeg_5-full.man</li>
    <li>gonic</li>
    <li>handbrake</li>
    <li>haruna</li>
    <li>hydrus</li>
    <li>hydrus.doc</li>
    <li>hypnotix</li>
    <li>imagination</li>
    <li>jellyfin</li>
    <li>jellyfin-ffmpeg</li>
    <li>jellyfin-ffmpeg.bin</li>
    <li>jellyfin-ffmpeg.data</li>
    <li>jellyfin-ffmpeg.dev</li>
    <li>jellyfin-ffmpeg.doc</li>
    <li>jellyfin-ffmpeg.lib</li>
    <li>jellyfin-ffmpeg.man</li>
    <li>jellyfin-media-player</li>
    <li>jftui</li>
    <li>kaffeine</li>
    <li>klipperscreen</li>
    <li>kphotoalbum</li>
    <li>libplacebo</li>
    <li>libsForQt5.elisa (plasma5Packages.elisa)</li>
    <li>libsForQt5.elisa.dev (plasma5Packages.elisa.dev)</li>
    <li>libsForQt5.kdenlive (plasma5Packages.kdenlive)</li>
    <li>libsForQt5.phonon-backend-vlc (plasma5Packages.phonon-backend-vlc)</li>
    <li>libsForQt5.plasmatube (plasma5Packages.plasmatube)</li>
    <li>soundkonverter (libsForQt5.soundkonverter)</li>
    <li>libsForQt5.tokodon (plasma5Packages.tokodon)</li>
    <li>libvlc</li>
    <li>linux-wallpaperengine</li>
    <li>liquidsoap</li>
    <li>manim</li>
    <li>manim.dist</li>
    <li>megaglest</li>
    <li>memento</li>
    <li>minitube</li>
    <li>mnemosyne</li>
    <li>mnemosyne.dist</li>
    <li>mpc-qt</li>
    <li>mpv</li>
    <li>mpv-unwrapped</li>
    <li>mpv-unwrapped.dev</li>
    <li>mpv-unwrapped.man</li>
    <li>mpvScripts.inhibit-gnome</li>
    <li>mpvScripts.mpris</li>
    <li>mpvScripts.thumbfast</li>
    <li>mpvpaper</li>
    <li>obs-studio</li>
    <li>obs-studio-plugins.advanced-scene-switcher</li>
    <li>obs-studio-plugins.droidcam-obs</li>
    <li>obs-studio-plugins.input-overlay</li>
    <li>obs-studio-plugins.looking-glass-obs</li>
    <li>obs-studio-plugins.obs-3d-effect</li>
    <li>obs-studio-plugins.obs-backgroundremoval</li>
    <li>obs-studio-plugins.obs-command-source</li>
    <li>obs-studio-plugins.obs-freeze-filter</li>
    <li>obs-studio-plugins.obs-gradient-source</li>
    <li>obs-studio-plugins.obs-gstreamer</li>
    <li>obs-studio-plugins.obs-livesplit-one</li>
    <li>obs-studio-plugins.obs-move-transition</li>
    <li>obs-studio-plugins.obs-multi-rtmp</li>
    <li>obs-studio-plugins.obs-mute-filter</li>
    <li>obs-studio-plugins.obs-nvfbc</li>
    <li>obs-studio-plugins.obs-pipewire-audio-capture</li>
    <li>obs-studio-plugins.obs-rgb-levels-filter</li>
    <li>obs-studio-plugins.obs-scale-to-sound</li>
    <li>obs-studio-plugins.obs-shaderfilter</li>
    <li>obs-studio-plugins.obs-source-clone</li>
    <li>obs-studio-plugins.obs-source-record</li>
    <li>obs-studio-plugins.obs-source-switcher</li>
    <li>obs-studio-plugins.obs-teleport</li>
    <li>obs-studio-plugins.obs-text-pthread</li>
    <li>obs-studio-plugins.obs-transition-table</li>
    <li>obs-studio-plugins.obs-tuna</li>
    <li>obs-studio-plugins.obs-vaapi</li>
    <li>obs-studio-plugins.obs-vertical-canvas</li>
    <li>obs-studio-plugins.obs-vintage-filter</li>
    <li>obs-studio-plugins.obs-vkcapture</li>
    <li>obs-studio-plugins.obs-websocket</li>
    <li>obs-studio-plugins.waveform</li>
    <li>obs-studio-plugins.wlrobs</li>
    <li>peek</li>
    <li>photoqt</li>
    <li>plex-media-player</li>
    <li>plex-mpv-shim</li>
    <li>plex-mpv-shim.dist</li>
    <li>printrun</li>
    <li>printrun.dist</li>
    <li>pympress</li>
    <li>pympress.dist</li>
    <li>python310Packages.aigpy</li>
    <li>python310Packages.aigpy.dist</li>
    <li>python310Packages.auditok</li>
    <li>python310Packages.auditok.dist</li>
    <li>python310Packages.gradio</li>
    <li>python310Packages.gradio-client</li>
    <li>python310Packages.gradio-client.dist</li>
    <li>python310Packages.gradio.dist</li>
    <li>python310Packages.moderngl-window</li>
    <li>python310Packages.moderngl-window.dist</li>
    <li>python310Packages.mpv</li>
    <li>python310Packages.mpv.dist</li>
    <li>python310Packages.pydub</li>
    <li>python310Packages.pydub.dist</li>
    <li>python310Packages.pyglet</li>
    <li>python310Packages.pyglet.dist</li>
    <li>python310Packages.pyrender</li>
    <li>python310Packages.pyrender.dist</li>
    <li>python310Packages.python-vlc</li>
    <li>python310Packages.python-vlc.dist</li>
    <li>python310Packages.pytmx</li>
    <li>python310Packages.pytmx.dist</li>
    <li>python310Packages.shazamio</li>
    <li>python310Packages.shazamio.dist</li>
    <li>python311Packages.aigpy</li>
    <li>python311Packages.aigpy.dist</li>
    <li>python311Packages.auditok</li>
    <li>python311Packages.auditok.dist</li>
    <li>python311Packages.gradio</li>
    <li>python311Packages.gradio-client</li>
    <li>python311Packages.gradio-client.dist</li>
    <li>python311Packages.gradio.dist</li>
    <li>python311Packages.moderngl-window</li>
    <li>python311Packages.moderngl-window.dist</li>
    <li>python311Packages.mpv</li>
    <li>python311Packages.mpv.dist</li>
    <li>python311Packages.pydub</li>
    <li>python311Packages.pydub.dist</li>
    <li>python311Packages.pyglet</li>
    <li>python311Packages.pyglet.dist</li>
    <li>python311Packages.pyrender</li>
    <li>python311Packages.pyrender.dist</li>
    <li>python311Packages.python-vlc</li>
    <li>python311Packages.python-vlc.dist</li>
    <li>python311Packages.pytmx</li>
    <li>python311Packages.pytmx.dist</li>
    <li>python311Packages.shazamio</li>
    <li>python311Packages.shazamio.dist</li>
    <li>qimgv</li>
    <li>radioboat</li>
    <li>reaper</li>
    <li>restream</li>
    <li>rocmPackages.llvm.mlir (rocmPackages_5.llvm.mlir)</li>
    <li>rofi-screenshot</li>
    <li>shaderc</li>
    <li>shaderc.bin</li>
    <li>shaderc.dev</li>
    <li>shaderc.lib</li>
    <li>shaderc.static</li>
    <li>shaq</li>
    <li>shaq.dist</li>
    <li>somafm-cli</li>
    <li>strawberry</li>
    <li>stremio</li>
    <li>sublime-music</li>
    <li>sublime-music.dist</li>
    <li>subtitleedit</li>
    <li>sunshine</li>
    <li>superTuxKart</li>
    <li>supersonic</li>
    <li>supersonic-wayland</li>
    <li>tidal-dl</li>
    <li>tidal-dl.dist</li>
    <li>tomato-c</li>
    <li>tone</li>
    <li>video-trimmer</li>
    <li>vlc</li>
    <li>vokoscreen</li>
    <li>wtwitch</li>
    <li>youtube-tui</li>
    <li>ytfzf</li>
    <li>ytui-music</li>
  </ul>
</details>

**Comment by Ralith** [comment]
Those failures look completely unrelated to me.

**Review by trofi — APPROVED** [review]

**Comment by Tungsten842** [comment]
@Ralith Could you updated this to [v2023.8](https://github.com/google/shaderc/releases/tag/v2023.8)

**Comment by Ralith** [comment]
Done and tested.

**Review by fpletz — APPROVED** [review]

**Pull request merged**
