### PR TITLE
linux: version bumps

### PR DESCRIPTION
**Pull request by kraem**
###### Motivation for this change

Versions bumps.
`5.6.5` -> `5.6.6`
`5.5.18` -> `5.5.19`
`5.4.33` -> `5.4.34`
`4.19.116` -> `4.19.117`

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kraem** [comment]
Ping @emilazy @NeQuissimus :)

**Review by emilazy — APPROVED** [review]
LGTM

**Comment by NeQuissimus** [comment]
@kraem Can you make a PR against `release-20.03` as well, please?

**Comment by kraem** [comment]
Sure! I forgot to answer you yesterday. I had to research how the backports were made to the stable branches (what policies there are etc). I'll fix a PR for `20.03`!

**Pull request merged**
