### PR TITLE
[20.09] python.pkgs.scikit-optimize: 0.6 -> 0.8.1

### PR DESCRIPTION
**Pull request by risicle**
###### Motivation for this change
ZHF: #97479

Backport of  #97990

Fails on macos, but that should be fixed in `master` first.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tricktron** [comment]
Result of `nixpkgs-review pr 99673` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>python37Packages.optuna</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python37Packages.scikit-optimize</li>
    <li>python38Packages.scikit-optimize</li>
  </ul>
</details>

**Comment by risicle** [comment]
@tricktron on darwin, right? if so that will get fixed by #99891

**Comment by tricktron** [comment]
> @tricktron on darwin, right? if so that will get fixed by #99891

@risicle Yes on darwin. Ah great. Sorry I missed that one.

**Review by jonringer — APPROVED** [review]
LGTM

failures are broken on target branch
```
https://github.com/NixOS/nixpkgs/pull/99673
1 package failed to build:
python37Packages.optuna

2 packages built:
python37Packages.scikit-optimize python38Packages.scikit-optimize
```

**Pull request merged**
