### PR TITLE
eyedropper: 0.5.1 -> 0.6.0

### PR DESCRIPTION
**Pull request by foo-dogsquared**
###### Description of changes

https://github.com/FineFindus/eyedropper/releases/tag/v0.6.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by foo-dogsquared** [comment]
Basic testing is done and most of the worked except I cannot export palettes. The following image is the error window when the "Save palettes..." button is clicked.

image

I'm almost sure this is an issue with my portals setup but I could be wrong. (It is the first time I've used the export palettes feature so I didn't noticed.)

**Review by zendo — APPROVED** [review]

**Comment by FineFindus** [comment]
Developer of the app here (thanks for packaging the app), yes, most likely indicates an issue with the `org.freedesktop.portal.FileChooser` portal. The app still uses the [GTK FileChooserNative Dialog](https://docs.gtk.org/gtk4/class.FileChooserNative.html), which uses the portal underneath.

Also, the currently listed description is out of date, it changed to `Pick and format colors` with the 0.6.0 release to be more inline with the GNOME guidelines.

**Comment by foo-dogsquared** [comment]
Thanks for the explanation, @FineFindus. I also updated the package description of the app now.

I also rebased the changes on top of 234cd6bb95c870203bb13fa66ca12c67686f544b.

**Review by zendo — APPROVED** [review]

**Review by Janik-Haag — APPROVED** [review]
LGTM

**Pull request merged**
