### PR TITLE
arjun: init at 2.2.1

### PR DESCRIPTION
**Pull request by octodi**
# Description of changes

Added Arjun a [HTTP Parameter Discovery Suite](https://github.com/s0md3v/Arjun#http-parameter-discovery-suite)

https://github.com/s0md3v/Arjun

Related to https://github.com/NixOS/nixpkgs/issues/81418

And added myself to maintainer-list.nix

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Successor of #258183

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 258344` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>arjun</li>
    <li>arjun.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 258344` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>arjun</li>
    <li>arjun.dist</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
- [x] package path fits guidelines
- [x] package name fits guidelines
- [x] package version fits guidelines
- [x] `meta.description` is set and fits guidelines
- [x] `meta.license` fits upstream license
- [x] `meta.maintainers` is set
- [x] package builds (see hhttps://github.com/NixOS/nixpkgs/pull/258344#issuecomment-1742001448)
- [ ] all depending packages build
- [x] tested on x86_64

```bash
...ew/pr-258344-3]$ ./results/arjun/bin/arjun 
    _
   /_| _ '
  (  |/ /(//) v2.2.1
      _/      

[-] No target(s) specified
```
Looks good to me.

**Comment by fabaff** [comment]
[53bf26f](https://github.com/NixOS/nixpkgs/pull/258344/commits/53bf26fa2347aec5732f4d2fe70ef8a195b6bf76) and [7015c36](https://github.com/NixOS/nixpkgs/pull/258344/commits/7015c36a1005a58de5cf1e51eeb316c86527fff2) should be removed from this PR.

I suggest to create branches for changes `git checkout -b [new-package-name or something else] master`. Easier to keep track and working on `master`.

**Comment by fabaff** [comment]
``bash
git reset --hard HEAD~4
git push -f
```

To keep the commit history clean it could be worth thinking about remove my two commits as well and fix it in the initial commit. So we would end-up with:

```
arjun: init at 2.2.1
maintainers: add octodi

**Comment by octodi** [comment]
I will create separate branch for packages

**Pull request closed without merging**
