### PR TITLE
Update metadata for geos

### PR DESCRIPTION
**Pull request by mwtoews**
The primary change in this PR is to use the updated homepage.

Hopefully this is an improved description for geos too.

### CODE REVIEW

**Comment by AndersonTorres** [comment]
Reword the commit to "geos: update meta.description and meta.homepage"

**Comment by nagy** [comment]
I think this should target the master branch.

**Comment by mwtoews** [comment]
whoa, sorry about the noise! Toggling the branch in the web GUI temporarily added too many labels and reviewers!

**Comment by lukegb** [comment]
It looks like you accidentally mass-pinged a bunch of people, which are now subscribed
and getting notifications for everything in this pull request. Unfortunately, they
cannot be automatically unsubscribed from the issue (removing review request does not
unsubscribe), therefore development cannot continue in this pull request anymore.

Please open a new pull request with your changes, link back to this one and ping the
people actually involved in here over there.

In order to avoid this in the future, there are instructions for how to properly
rebase between branches in our [contribution guidelines](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging).
Setting your pull request to draft prior to rebasing is strongly recommended.
In draft status, you can preview the list of people that are about to be requested
for review, which allows you to sidestep this issue.
This is not a bulletproof method though, as OfBorg still does review requests even on draft PRs.

**Pull request closed without merging**
