### PR TITLE
web-archives: init at 0.5.0; libzim-glib: init at 4.0.0; libisocodes: init at 1.2.5

### PR DESCRIPTION
**Pull request by Aleksanaa**
## Description of changes

image

Steps to test:

1. download an archive from kiwix, I recommend https://download.kiwix.org/zim/stack_exchange/bioinformatics.stackexchange.com_en_all_2024-05.zim as it's pretty small. You can also find a list on the app.
2. Click on "+" at the right of "Recents" and import the archive.
3. Click on the archive. It should show a "not found" (Seems not a bug, just the homepage not archived?). Then click on search button, search for something like "cell".

<details>
<summary>More Screenshot</summary>

image
image

</details>

And yeah it looks kinda good, the dark reader works too.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 323098` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>libzim-glib</li>
    <li>libzim-glib.dev</li>
    <li>web-archives</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>libisocodes</li>
  </ul>
</details>

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 323098` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>libisocodes</li>
    <li>libzim-glib</li>
    <li>libzim-glib.dev</li>
    <li>web-archives</li>
  </ul>
</details>

**Comment by Aleksanaa** [comment]
zimlib is marked as only available on Linux. Seems to be wrong...

**Comment by greg-hellings** [comment]
I was unable to get zimlib to build on Darwin when I first submitted it. If your tests pass, then I'm happy to give this my approval for the zimlib change.

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 323098` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>web-archives</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>libisocodes</li>
    <li>libzim-glib</li>
    <li>libzim-glib.dev</li>
    <li>zimlib</li>
  </ul>
</details>

**Review by greg-hellings — APPROVED** [review]
Approved as to the change to zimlib

**Review by wegank — APPROVED** [review]

**Pull request merged**
