### PR TITLE
binutils: Apply patches from 2.30 branch 

### LINKED ISSUE #40397: binutils: Since Version 2.30 strip is broken
## Issue description

This is a continuation of https://github.com/NixOS/nixpkgs/pull/40228#issuecomment-387775835 ff.
Since Commit 3027bca dmd and the phobos static lib can be build but because the static lib contains missing sections dmd can't be used to compile a simple program.

Because dmd doesn't build on Master at the moment https://github.com/NixOS/nixpkgs/pull/40228 needs to be merged first as it fixes the compilation problems of dmd with glibc 2.27 on master. (nan.h error in port.c)

### Steps to reproduce

After building dmd from master with the changes from https://github.com/NixOS/nixpkgs/pull/40228 to fix the build create file test.d with the following contents:

```
import std.stdio;

void main()
{
	writeln("test");
}
```

Compile test.d with the dmd built from master with: `<pathToResult>/bin/dmd test.d`
The compilation crashes with linker errors.
Inspecting the standard lib phobos with `nm <pathToResult>/lib/libphobos2.a` shows that there are missing group infos in sections. See https://forum.dlang.org/post/uwdxarueshdizahjvvsu@forum.dlang.org for details.
Examining the lib with nm before commit 3027bca shows no such missing sections and the compilation of test.d works correctly.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.38, NixOS, 18.03.132304.45cd6090d9a (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-18.03"`
 - channels(thomad): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

### PR DESCRIPTION
**Pull request by ThomasMader**
###### Motivation for this change

This fixes https://github.com/NixOS/nixpkgs/issues/40397.
Because I already had those other patches I thought it is better to commit them with the two patches which fix the strip issue.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ericson2314** [comment]
Can we fetchpatch?

**Comment by ThomasMader** [comment]
Probably yes but that would also mean that we would need to get all patches in the right order.
I had errors because the original patch couldn't be applied because the patch for the changelog file.
I would not want to add all patches because it's a lot of work and I guess 2.31 will be released soon.

So in my opinion it's better to patch concrete problems for now.

**Comment by Ericson2314** [comment]
Hmm Ok. I gues just add a note with all the code. Should this go to staging?

**Comment by ThomasMader** [comment]
What do you mean with the note?

It should go everywhere where binutils 2.30 is used, why do you ask?

**Comment by Ericson2314** [comment]
@ThomasMader I mean next to the patches in `default.nix`, say they are a) not fetched because they are slightly rebased, and b) should be removed with 2.31.

**Comment by Ericson2314** [comment]
Well, at least people can blame and find this PR. So that just leaves whether this should go to staging right?

**Comment by ThomasMader** [comment]
We can also keep that PR unmerged and get it merged only if there are really other packages with the same problem.
It's possible that it's just happening to dmd or programs build with dmd as I suspect the binary generation of dmd to be a little bit strange.

As of now I suspect that tilix isn't building because of this problem but that can be easily verified.
I would say we keep that PR lingering for now and close it if 2.31 is available or we really see that there are many packages suffering from this problem.
If the problem really exists with tilix it can be easily worked around by putting dontStrip = true into the gtkd package.
AFAIR there are not more libs build by dmd than gtkd.
If someone strips D libs build with dmd manually we would still have a problem though but I could live with that for unstable till 2.31 is released.

**Comment by dtzWill** [comment]
I think these patches address security issues mentioned in https://github.com/NixOS/nixpkgs/issues/41748.

If you don't mind, checking and adding additional patches that address those CVEs would be great.

(we might as well fix them while we're at it!)

If merging to master it'd be good to at least have someone sanity check a few builds and monitor Hydra for the fallout.  Maybe new jobset? cc @shlevy since was involved in last binutils bump.

**Comment by shlevy** [comment]
I can revive the binutils-2.30 jobset if we freshen up that branch... I'd really like to see if we can use fetchpatch, though.

**Comment by dtzWill** [comment]
Ping! :)

**Comment by ThomasMader** [comment]
Sorry I have only infrequent access to internet for now. I might take a look when I go back home.

**Comment by dtzWill** [comment]
> Sorry I have only infrequent access to internet for now. I might take a look when I go back home.

No worries, thanks! Ping'ing the thread itself (as opposed to trying to bring it to attention elsewhere) is mostly about helping ensure this isn't left incomplete only because it was forgotten about, which is all too easy to do :).  And giving a small amount of encouragement that at least someone is interested in this :).

Thanks for putting this together, and do what you can when you can.  Take care!

**Comment by ThomasMader** [comment]
Closing this as there is an open PR for binutils 2.31.1: https://github.com/NixOS/nixpkgs/pull/49324

**Pull request closed without merging**
