### PR TITLE
python3Packages.azure*: bump

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
routine bump

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
```
https://github.com/NixOS/nixpkgs/pull/126405

171 packages built:
appdaemon azure-cli dvc-with-remotes python38Packages.azure-appconfiguration python38Packages.azure-core python38Packages.azure-eventgrid python38Packages.azure-identity python38Packages.azure-keyvault python38Packages.azure-keyvault-administration python38Packages.azure-keyvault-certificates python38Packages.azure-keyvault-keys python38Packages.azure-keyvault-secrets python38Packages.azure-mgmt-advisor python38Packages.azure-mgmt-apimanagement python38Packages.azure-mgmt-appconfiguration python38Packages.azure-mgmt-applicationinsights python38Packages.azure-mgmt-authorization python38Packages.azure-mgmt-batch python38Packages.azure-mgmt-billing python38Packages.azure-mgmt-botservice python38Packages.azure-mgmt-cdn python38Packages.azure-mgmt-cognitiveservices python38Packages.azure-mgmt-commerce python38Packages.azure-mgmt-compute python38Packages.azure-mgmt-consumption python38Packages.azure-mgmt-containerinstance python38Packages.azure-mgmt-containerregistry python38Packages.azure-mgmt-containerservice python38Packages.azure-mgmt-core python38Packages.azure-mgmt-cosmosdb python38Packages.azure-mgmt-databoxedge python38Packages.azure-mgmt-datafactory python38Packages.azure-mgmt-datalake-store python38Packages.azure-mgmt-datamigration python38Packages.azure-mgmt-deploymentmanager python38Packages.azure-mgmt-devtestlabs python38Packages.azure-mgmt-dns python38Packages.azure-mgmt-eventgrid python38Packages.azure-mgmt-eventhub python38Packages.azure-mgmt-hanaonazure python38Packages.azure-mgmt-hdinsight python38Packages.azure-mgmt-iotcentral python38Packages.azure-mgmt-iothub python38Packages.azure-mgmt-keyvault python38Packages.azure-mgmt-kusto python38Packages.azure-mgmt-loganalytics python38Packages.azure-mgmt-logic python38Packages.azure-mgmt-managedservices python38Packages.azure-mgmt-managementgroups python38Packages.azure-mgmt-managementpartner python38Packages.azure-mgmt-maps python38Packages.azure-mgmt-marketplaceordering python38Packages.azure-mgmt-media python38Packages.azure-mgmt-monitor python38Packages.azure-mgmt-netapp python38Packages.azure-mgmt-network python38Packages.azure-mgmt-notificationhubs python38Packages.azure-mgmt-policyinsights python38Packages.azure-mgmt-privatedns python38Packages.azure-mgmt-rdbms python38Packages.azure-mgmt-recoveryservices python38Packages.azure-mgmt-recoveryservicesbackup python38Packages.azure-mgmt-redhatopenshift python38Packages.azure-mgmt-redis python38Packages.azure-mgmt-relay python38Packages.azure-mgmt-reservations python38Packages.azure-mgmt-resource python38Packages.azure-mgmt-search python38Packages.azure-mgmt-security python38Packages.azure-mgmt-servicebus python38Packages.azure-mgmt-servicefabric python38Packages.azure-mgmt-servicefabricmanagedclusters python38Packages.azure-mgmt-sql python38Packages.azure-mgmt-storage python38Packages.azure-mgmt-subscription python38Packages.azure-mgmt-synapse python38Packages.azure-mgmt-web python38Packages.azure-multiapi-storage python38Packages.azure-servicebus python38Packages.azure-storage-blob python38Packages.azure-storage-file-share python38Packages.azure-synapse-accesscontrol python38Packages.azure-synapse-artifacts python38Packages.azure-synapse-spark python38Packages.knack python38Packages.snowflake-connector-python python38Packages.snowflake-sqlalchemy python39Packages.azure-appconfiguration python39Packages.azure-core python39Packages.azure-eventgrid python39Packages.azure-identity python39Packages.azure-keyvault python39Packages.azure-keyvault-administration python39Packages.azure-keyvault-certificates python39Packages.azure-keyvault-keys python39Packages.azure-keyvault-secrets python39Packages.azure-mgmt-advisor python39Packages.azure-mgmt-apimanagement python39Packages.azure-mgmt-appconfiguration python39Packages.azure-mgmt-applicationinsights python39Packages.azure-mgmt-authorization python39Packages.azure-mgmt-batch python39Packages.azure-mgmt-billing python39Packages.azure-mgmt-botservice python39Packages.azure-mgmt-cdn python39Packages.azure-mgmt-cognitiveservices python39Packages.azure-mgmt-commerce python39Packages.azure-mgmt-compute python39Packages.azure-mgmt-consumption python39Packages.azure-mgmt-containerinstance python39Packages.azure-mgmt-containerregistry python39Packages.azure-mgmt-containerservice python39Packages.azure-mgmt-core python39Packages.azure-mgmt-cosmosdb python39Packages.azure-mgmt-databoxedge python39Packages.azure-mgmt-datafactory python39Packages.azure-mgmt-datalake-store python39Packages.azure-mgmt-datamigration python39Packages.azure-mgmt-deploymentmanager python39Packages.azure-mgmt-devtestlabs python39Packages.azure-mgmt-dns python39Packages.azure-mgmt-eventgrid python39Packages.azure-mgmt-eventhub python39Packages.azure-mgmt-hanaonazure python39Packages.azure-mgmt-hdinsight python39Packages.azure-mgmt-iotcentral python39Packages.azure-mgmt-iothub python39Packages.azure-mgmt-keyvault python39Packages.azure-mgmt-kusto python39Packages.azure-mgmt-loganalytics python39Packages.azure-mgmt-logic python39Packages.azure-mgmt-managedservices python39Packages.azure-mgmt-managementgroups python39Packages.azure-mgmt-managementpartner python39Packages.azure-mgmt-maps python39Packages.azure-mgmt-marketplaceordering python39Packages.azure-mgmt-media python39Packages.azure-mgmt-monitor python39Packages.azure-mgmt-netapp python39Packages.azure-mgmt-network python39Packages.azure-mgmt-notificationhubs python39Packages.azure-mgmt-policyinsights python39Packages.azure-mgmt-privatedns python39Packages.azure-mgmt-rdbms python39Packages.azure-mgmt-recoveryservices python39Packages.azure-mgmt-recoveryservicesbackup python39Packages.azure-mgmt-redhatopenshift python39Packages.azure-mgmt-redis python39Packages.azure-mgmt-relay python39Packages.azure-mgmt-reservations python39Packages.azure-mgmt-resource python39Packages.azure-mgmt-search python39Packages.azure-mgmt-security python39Packages.azure-mgmt-servicebus python39Packages.azure-mgmt-servicefabric python39Packages.azure-mgmt-servicefabricmanagedclusters python39Packages.azure-mgmt-sql python39Packages.azure-mgmt-storage python39Packages.azure-mgmt-subscription python39Packages.azure-mgmt-synapse python39Packages.azure-mgmt-web python39Packages.azure-multiapi-storage python39Packages.azure-servicebus python39Packages.azure-storage-blob python39Packages.azure-storage-file-share python39Packages.azure-synapse-accesscontrol python39Packages.azure-synapse-artifacts python39Packages.azure-synapse-spark python39Packages.knack python39Packages.snowflake-connector-python python39Packages.snowflake-sqlalchemy
```

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 126405` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>171 packages built:</summary>
  <ul>
    <li>appdaemon</li>
    <li>azure-cli</li>
    <li>dvc-with-remotes</li>
    <li>python38Packages.azure-appconfiguration</li>
    <li>python38Packages.azure-core</li>
    <li>python38Packages.azure-eventgrid</li>
    <li>python38Packages.azure-identity</li>
    <li>python38Packages.azure-keyvault</li>
    <li>python38Packages.azure-keyvault-administration</li>
    <li>python38Packages.azure-keyvault-certificates</li>
    <li>python38Packages.azure-keyvault-keys</li>
    <li>python38Packages.azure-keyvault-secrets</li>
    <li>python38Packages.azure-mgmt-advisor</li>
    <li>python38Packages.azure-mgmt-apimanagement</li>
    <li>python38Packages.azure-mgmt-appconfiguration</li>
    <li>python38Packages.azure-mgmt-applicationinsights</li>
    <li>python38Packages.azure-mgmt-authorization</li>
    <li>python38Packages.azure-mgmt-batch</li>
    <li>python38Packages.azure-mgmt-billing</li>
    <li>python38Packages.azure-mgmt-botservice</li>
    <li>python38Packages.azure-mgmt-cdn</li>
    <li>python38Packages.azure-mgmt-cognitiveservices</li>
    <li>python38Packages.azure-mgmt-commerce</li>
    <li>python38Packages.azure-mgmt-compute</li>
    <li>python38Packages.azure-mgmt-consumption</li>
    <li>python38Packages.azure-mgmt-containerinstance</li>
    <li>python38Packages.azure-mgmt-containerregistry</li>
    <li>python38Packages.azure-mgmt-containerservice</li>
    <li>python38Packages.azure-mgmt-core</li>
    <li>python38Packages.azure-mgmt-cosmosdb</li>
    <li>python38Packages.azure-mgmt-databoxedge</li>
    <li>python38Packages.azure-mgmt-datafactory</li>
    <li>python38Packages.azure-mgmt-datalake-store</li>
    <li>python38Packages.azure-mgmt-datamigration</li>
    <li>python38Packages.azure-mgmt-deploymentmanager</li>
    <li>python38Packages.azure-mgmt-devtestlabs</li>
    <li>python38Packages.azure-mgmt-dns</li>
    <li>python38Packages.azure-mgmt-eventgrid</li>
    <li>python38Packages.azure-mgmt-eventhub</li>
    <li>python38Packages.azure-mgmt-hanaonazure</li>
    <li>python38Packages.azure-mgmt-hdinsight</li>
    <li>python38Packages.azure-mgmt-iotcentral</li>
    <li>python38Packages.azure-mgmt-iothub</li>
    <li>python38Packages.azure-mgmt-keyvault</li>
    <li>python38Packages.azure-mgmt-kusto</li>
    <li>python38Packages.azure-mgmt-loganalytics</li>
    <li>python38Packages.azure-mgmt-logic</li>
    <li>python38Packages.azure-mgmt-managedservices</li>
    <li>python38Packages.azure-mgmt-managementgroups</li>
    <li>python38Packages.azure-mgmt-managementpartner</li>
    <li>python38Packages.azure-mgmt-maps</li>
    <li>python38Packages.azure-mgmt-marketplaceordering</li>
    <li>python38Packages.azure-mgmt-media</li>
    <li>python38Packages.azure-mgmt-monitor</li>
    <li>python38Packages.azure-mgmt-netapp</li>
    <li>python38Packages.azure-mgmt-network</li>
    <li>python38Packages.azure-mgmt-notificationhubs</li>
    <li>python38Packages.azure-mgmt-policyinsights</li>
    <li>python38Packages.azure-mgmt-privatedns</li>
    <li>python38Packages.azure-mgmt-rdbms</li>
    <li>python38Packages.azure-mgmt-recoveryservices</li>
    <li>python38Packages.azure-mgmt-recoveryservicesbackup</li>
    <li>python38Packages.azure-mgmt-redhatopenshift</li>
    <li>python38Packages.azure-mgmt-redis</li>
    <li>python38Packages.azure-mgmt-relay</li>
    <li>python38Packages.azure-mgmt-reservations</li>
    <li>python38Packages.azure-mgmt-resource</li>
    <li>python38Packages.azure-mgmt-search</li>
    <li>python38Packages.azure-mgmt-security</li>
    <li>python38Packages.azure-mgmt-servicebus</li>
    <li>python38Packages.azure-mgmt-servicefabric</li>
    <li>python38Packages.azure-mgmt-servicefabricmanagedclusters</li>
    <li>python38Packages.azure-mgmt-sql</li>
    <li>python38Packages.azure-mgmt-storage</li>
    <li>python38Packages.azure-mgmt-subscription</li>
    <li>python38Packages.azure-mgmt-synapse</li>
    <li>python38Packages.azure-mgmt-web</li>
    <li>python38Packages.azure-multiapi-storage</li>
    <li>python38Packages.azure-servicebus</li>
    <li>python38Packages.azure-storage-blob</li>
    <li>python38Packages.azure-storage-file-share</li>
    <li>python38Packages.azure-synapse-accesscontrol</li>
    <li>python38Packages.azure-synapse-artifacts</li>
    <li>python38Packages.azure-synapse-spark</li>
    <li>python38Packages.knack</li>
    <li>python38Packages.snowflake-connector-python</li>
    <li>python38Packages.snowflake-sqlalchemy</li>
    <li>python39Packages.azure-appconfiguration</li>
    <li>python39Packages.azure-core</li>
    <li>python39Packages.azure-eventgrid</li>
    <li>python39Packages.azure-identity</li>
    <li>python39Packages.azure-keyvault</li>
    <li>python39Packages.azure-keyvault-administration</li>
    <li>python39Packages.azure-keyvault-certificates</li>
    <li>python39Packages.azure-keyvault-keys</li>
    <li>python39Packages.azure-keyvault-secrets</li>
    <li>python39Packages.azure-mgmt-advisor</li>
    <li>python39Packages.azure-mgmt-apimanagement</li>
    <li>python39Packages.azure-mgmt-appconfiguration</li>
    <li>python39Packages.azure-mgmt-applicationinsights</li>
    <li>python39Packages.azure-mgmt-authorization</li>
    <li>python39Packages.azure-mgmt-batch</li>
    <li>python39Packages.azure-mgmt-billing</li>
    <li>python39Packages.azure-mgmt-botservice</li>
    <li>python39Packages.azure-mgmt-cdn</li>
    <li>python39Packages.azure-mgmt-cognitiveservices</li>
    <li>python39Packages.azure-mgmt-commerce</li>
    <li>python39Packages.azure-mgmt-compute</li>
    <li>python39Packages.azure-mgmt-consumption</li>
    <li>python39Packages.azure-mgmt-containerinstance</li>
    <li>python39Packages.azure-mgmt-containerregistry</li>
    <li>python39Packages.azure-mgmt-containerservice</li>
    <li>python39Packages.azure-mgmt-core</li>
    <li>python39Packages.azure-mgmt-cosmosdb</li>
    <li>python39Packages.azure-mgmt-databoxedge</li>
    <li>python39Packages.azure-mgmt-datafactory</li>
    <li>python39Packages.azure-mgmt-datalake-store</li>
    <li>python39Packages.azure-mgmt-datamigration</li>
    <li>python39Packages.azure-mgmt-deploymentmanager</li>
    <li>python39Packages.azure-mgmt-devtestlabs</li>
    <li>python39Packages.azure-mgmt-dns</li>
    <li>python39Packages.azure-mgmt-eventgrid</li>
    <li>python39Packages.azure-mgmt-eventhub</li>
    <li>python39Packages.azure-mgmt-hanaonazure</li>
    <li>python39Packages.azure-mgmt-hdinsight</li>
    <li>python39Packages.azure-mgmt-iotcentral</li>
    <li>python39Packages.azure-mgmt-iothub</li>
    <li>python39Packages.azure-mgmt-keyvault</li>
    <li>python39Packages.azure-mgmt-kusto</li>
    <li>python39Packages.azure-mgmt-loganalytics</li>
    <li>python39Packages.azure-mgmt-logic</li>
    <li>python39Packages.azure-mgmt-managedservices</li>
    <li>python39Packages.azure-mgmt-managementgroups</li>
    <li>python39Packages.azure-mgmt-managementpartner</li>
    <li>python39Packages.azure-mgmt-maps</li>
    <li>python39Packages.azure-mgmt-marketplaceordering</li>
    <li>python39Packages.azure-mgmt-media</li>
    <li>python39Packages.azure-mgmt-monitor</li>
    <li>python39Packages.azure-mgmt-netapp</li>
    <li>python39Packages.azure-mgmt-network</li>
    <li>python39Packages.azure-mgmt-notificationhubs</li>
    <li>python39Packages.azure-mgmt-policyinsights</li>
    <li>python39Packages.azure-mgmt-privatedns</li>
    <li>python39Packages.azure-mgmt-rdbms</li>
    <li>python39Packages.azure-mgmt-recoveryservices</li>
    <li>python39Packages.azure-mgmt-recoveryservicesbackup</li>
    <li>python39Packages.azure-mgmt-redhatopenshift</li>
    <li>python39Packages.azure-mgmt-redis</li>
    <li>python39Packages.azure-mgmt-relay</li>
    <li>python39Packages.azure-mgmt-reservations</li>
    <li>python39Packages.azure-mgmt-resource</li>
    <li>python39Packages.azure-mgmt-search</li>
    <li>python39Packages.azure-mgmt-security</li>
    <li>python39Packages.azure-mgmt-servicebus</li>
    <li>python39Packages.azure-mgmt-servicefabric</li>
    <li>python39Packages.azure-mgmt-servicefabricmanagedclusters</li>
    <li>python39Packages.azure-mgmt-sql</li>
    <li>python39Packages.azure-mgmt-storage</li>
    <li>python39Packages.azure-mgmt-subscription</li>
    <li>python39Packages.azure-mgmt-synapse</li>
    <li>python39Packages.azure-mgmt-web</li>
    <li>python39Packages.azure-multiapi-storage</li>
    <li>python39Packages.azure-servicebus</li>
    <li>python39Packages.azure-storage-blob</li>
    <li>python39Packages.azure-storage-file-share</li>
    <li>python39Packages.azure-synapse-accesscontrol</li>
    <li>python39Packages.azure-synapse-artifacts</li>
    <li>python39Packages.azure-synapse-spark</li>
    <li>python39Packages.knack</li>
    <li>python39Packages.snowflake-connector-python</li>
    <li>python39Packages.snowflake-sqlalchemy</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
- [x] package built (see https://github.com/NixOS/nixpkgs/pull/126405#issuecomment-858154543)
- [x] all depending packages build
- [x] tested on x86_64

Change looks good to me.

**Comment by alyssais** [comment]
The commit adding PyGithub is after the commit that uses it.  If you don't want to reorder the commits into an order where everything builds, maybe squash so we don't break bisection?

**Comment by jonringer** [comment]
> The commit adding PyGithub is after the commit that uses it. If you don't want to reorder the commits into an order where everything builds, maybe squash so we don't break bisection?

pygithub wasn't used in azure-cli 2.23, so it should be harmless

**Comment by alyssais** [comment]
I'm sorry, I should be in bed.  It's the same commit that introduces it and uses it.  Not sure why I thought they were different ones.

**Review by alyssais — APPROVED** [review]

**Pull request merged**
