### PR TITLE
lemminx: init at 0.27.0

### LINKED ISSUE #100164: Packaging request: Lemminx
**Project description**
Lemminx is an implementation of the Language Server Protocol for XML files.

**Metadata**

* homepage URL: https://github.com/eclipse/lemminx
* source URL: https://github.com/eclipse/lemminx
* license: EPL2
* platforms: GNU/Linux, Darwin

### PR DESCRIPTION
**Pull request by tricktron**
## Description of changes

Adds Lemminx, an implementation of the Language Server Protocol for XML files.

Closes https://github.com/NixOS/nixpkgs/issues/100164 and supersedes https://github.com/NixOS/nixpkgs/pull/132335 and https://github.com/NixOS/nixpkgs/pull/201885.

CC @wegank for review since this uses the newly added buildOffline feature flag of https://github.com/NixOS/nixpkgs/pull/255243#event-10424279507.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wegank** [comment]
Looks like there are more failing tests on Linux?

**Comment by tricktron** [comment]
> Looks like there are more failing tests on Linux?

@wegank I disabled the flaky tests and therefore it should be ready to merge😃.

**Review by wegank — APPROVED** [review]

**Comment by wegank** [comment]
@ofborg build lemminx lemminx.passthru.tests

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 256447` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>lemminx</li>
  </ul>
</details>

**Comment by wegank** [comment]
`DocumentLifecycleParticipantTest` fails deterministically on aarch64-darwin.

**Comment by tricktron** [comment]
> `DocumentLifecycleParticipantTest` fails deterministically on aarch64-darwin.

@wegank Thank you for the finding. I disabled the test.

**Comment by tricktron** [comment]
@ofborg build lemminx lemminx.passthru.tests

**Comment by tricktron** [comment]
@wegank Does it now build on your aarch64-darwin system?

**Review by wegank — APPROVED** [review]

**Pull request merged**
