### PR TITLE
haskellPackages: update stackage and hackage

### PR DESCRIPTION
**Pull request by sternenseemann**
### This Merge

This PR is the regular merge of the `haskell-updates` branch into `master`.

This branch is being continually built and tested by hydra at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates. You may be able to find an up-to-date Hydra build report at [cdepillabout/nix-haskell-updates-status](https://github.com/cdepillabout/nix-haskell-updates-status).

We roughly aim to merge these `haskell-updates` PRs at least once every two weeks. See the @NixOS/haskell [team calendar](https://cloud.maralorn.de/apps/calendar/p/H6migHmKX7xHoTFa) for who is currently in charge of this branch.

### haskellPackages Workflow Summary

Our workflow is currently described in [`pkgs/development/haskell-modules/HACKING.md`](https://github.com/NixOS/nixpkgs/blob/haskell-updates/pkgs/development/haskell-modules/HACKING.md).

The short version is this:
* We regularly update the Stackage and Hackage pins on `haskell-updates` (normally at the beginning of a merge window).
* The community fixes builds of Haskell packages on that branch.
* We aim at at least one merge of `haskell-updates` into `master` every two weeks.
* We only do the merge if the [`mergeable`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/mergeable) job is succeeding on hydra.
* If a [`maintained`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/maintained) package is still broken at the time of merge, we will only merge if the maintainer has been pinged 7 days in advance. (If you care about a Haskell package, become a maintainer!)

More information about Haskell packages in nixpkgs can be found [in the nixpkgs manual](https://nixos.org/manual/nixpkgs/unstable/#haskell).

---

This is the follow-up to #228965. Come to [#haskell:nixos.org](https://matrix.to/#/#haskell:nixos.org) if you have any questions.

### CODE REVIEW

**Comment by vcunat** [comment]
I'm sorry, due to current situation I cancelled the jobset.  I expect it to get back in about two days, with much of work done over one or two days following that.  I hope it's not an issue; otherwise we could try to find some other approach.

**Comment by vcunat** [comment]
BTW, I expect that you're aware that no "breaking changes" are allowed in these couple of weeks.

**Comment by sternenseemann** [comment]
> I'm sorry, due to current situation I cancelled the jobset. I expect it to get back in about two days, with much of work done over one or two days following that. I hope it's not an issue; otherwise we could try to find some other approach.

No problem, there's no real urgency in this iteration and I lack time anyways. I've restarted the aborted jobs now since the queue was pretty empty (<2000 jobs).

**Comment by vcunat** [comment]
Yes, probably.  `staging-next` #231026 will probably merged this weekend, so it will be redone afterwards, but not a problem.

**Comment by vcunat** [comment]
I cancelled the old builds in favor of the new ones.  I _assume_ that's what you'd want, but feel free to override that.

**Comment by sternenseemann** [comment]
When Hydra gets a long a bit more, I'd merge this PR before branch-off (likely later today), as there are no breaking changes present.

This will cause a full rebuild of `haskellPackages` on `staging-next` (which shouldn't break anything though), is that okay with you @vcunat? I'm guessing staging-next is not a very pressing issue at the moment, as it doesn't target branch-off?

**Comment by vcunat** [comment]
Yes, the last iteration for 23.05 is already on master and new one hasn't started yet.

**Pull request merged**
