### PR TITLE
ns-2: init at 2.35

### PR DESCRIPTION
**Pull request by pschuprikov**
###### Motivation for this change

[NS2](https://www.isi.edu/nsnam/ns/) is a previous incarnation of the [NS3](https://www.nsnam.org/) network simulator that is [already in nixpkgs][ns3-nix]. NS3 is a next-to-complete rewrite of NS2, and while it is considered superior, feature parity is yet to achieve. For that reason, NS2 is still actively used in the research community.

I haven't placed NS2 next to NS3 in `development/libraries/...` since NS2 is mainly used through the `ns` executable, as opposed to NS3 that is primarily a set of libraries to link against.

[ns3-nix]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/science/networking/ns3/default.nix
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Is this project still maintained? Last release is 2011 and it needs 3 patches to compile.

**Comment by Mic92** [comment]
cc @teto

**Comment by pschuprikov** [comment]
@Mic92 I believe it is not maintained. I've been using it myself and thought why not to tidy it up and package. If it is not a good fit for *nixpkgs*, I am totally OK with closing the PR :-)

**Comment by pschuprikov** [comment]
@teto Thanks for the suggestion. Being honest I haven't heard of NUR before, but it sounds like a better option indeed. I'm closing the PR then.

**Comment by Mic92** [comment]
@pschuprikov thanks, NUR is a great option for that.

**Pull request closed without merging**
