### PR TITLE
bumblebee: backport critical libkmod.patch

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change

Backport [change](https://github.com/Bumblebee-Project/Bumblebee/pull/762) which replaces modprobe execution with libkmod2 library calls. This is a must for anyone who has an issue where Bumblebee can't disable discrete graphics card. Was already backported into [Debian](http://metadata.ftp-master.debian.org/changelogs/main/b/bumblebee/bumblebee_3.2.1-13_changelog)
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
So this fixes https://github.com/NixOS/nixpkgs/issues/20009?

**Comment by gnidorah** [comment]
@joachifm No it's unrelated, so I created a new issue https://github.com/NixOS/nixpkgs/issues/20047

**Comment by abbradar** [comment]
Seems good to me; I'll test it ASAP and merge if things are okay.

**Comment by gnidorah** [comment]
@abbradar Thanks. I'm on 16.09 and use Bumblebee nix module, so tested my change following this guide: http://anderspapitto.com/posts/2015-11-01-nixos-with-local--checkout.html

**Comment by abbradar** [comment]
Sorry, completely forgotten about this! I've tested it and it works okay for me. Thank you for your contribution!

**Pull request merged**
