### PR TITLE
gitAndTools.git-annex: fix darwin build

### LINKED ISSUE #73435: git-annex: 5 out of 366 tests failed
**Describe the bug**
On Darwin, attempting to install the derivation results in it attempting to build it, and subsequent tests failing.

**To Reproduce**
1. nix-env -iA nixpkgs.gitAndTools.git-annex

**Expected behavior**
I would expect it to fetch the package from cache, and otherwise the build and pass the tests, and install.

**Additional context**
This may well be specific to Darwin. I am unable to test otherwise.

I have attached the log of the build. It became rather long, so it's attached as a single file:
[log.txt](https://github.com/NixOS/nixpkgs/files/3849414/log.txt)

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

Unfortunately this didn't seem to work, presumably specific to Darwin. I'm using the channel nixpkgs-19.09-darwin, but it was also, up until a few weeks ago, a problem on nixpkgs-unstable.

I'm using macOS Catalina (10.15). It seemed to be a problem on Mojave too but I can't confirm that for sure. I hope this is useful. If there is additional information required I am very happy to provide it.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixpkgs.gitAndTools.git-annex
```

### PR DESCRIPTION
**Pull request by veprbl**
###### Motivation for this change

git-annex doesn't build on darwin, I suspect a case of NixOS/nix#1085
Fixes: #73435
Helps with: #40783

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
Should this target "haskell-updates" instead?

**Comment by cdepillabout** [comment]
@veprbl Since it only affects Darwin, it is probably fine to merge into master, but we usually merge Haskell-related changes into `haskell-updates`.

----------------------------------------------------------------------------------------

This looks good to me, and it builds on darwin, so I think it is good to merge in.

**Review by marsam — APPROVED** [review]

**Comment by veprbl** [comment]
Pushed this to the `haskell-updates`.

**Comment by cdepillabout** [comment]
This is commit 18c2874 on https://github.com/NixOS/nixpkgs/pull/75857 for `haskell-updates`, so I am going ahead and closing this.

**Pull request closed without merging**
