### PR TITLE
mavproxy: add lxml dependency

### PR DESCRIPTION
**Pull request by lopsided98**
###### Things done

Updates mavproxy and pymavlink to the latest version. Also, add dependencies to mavproxy to allow all the tools to run.

cc @onny 

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
Still two binaries fail to run:
```
[nix-shell:~/.cache/nixpkgs-review/pr-186868]$ ./results/mavproxy/bin/mp_tile.py 
Traceback (most recent call last):
  File "/nix/store/zs9s8ncp22dpyvnhn858rpvpsch921g3-MAVProxy-1.8.53/bin/.mp_tile.py-wrapped", line 644, in <module>
    mt = MPTile(debug=opts.debug, service=opts.service,
  File "/nix/store/zs9s8ncp22dpyvnhn858rpvpsch921g3-MAVProxy-1.8.53/bin/.mp_tile.py-wrapped", line 208, in __init__
    raise TileException('unknown tile service %s' % service)
__main__.TileException: unknown tile service OviHybrid
```

```
[nix-shell:~/.cache/nixpkgs-review/pr-186868]$ ./results/mavproxy/bin/MAVExplorer.py 
Traceback (most recent call last):
  File "/nix/store/zs9s8ncp22dpyvnhn858rpvpsch921g3-MAVProxy-1.8.53/bin/.MAVExplorer.py-wrapped", line 32, in <module>
    from lxml import objectify
ImportError: cannot import name 'objectify' from 'lxml' (/nix/store/z4rqrzahlz5ljrf4rrw6hljwf7iqclm1-python3.9-lxml-4.9.1/lib/python3.9/site-packages/lxml/__init__.py)
``` 

Hope it's not too complicated! Thank you for fixing this

**Comment by lopsided98** [comment]
The first is just a bug. `OviHybrid` was [removed](https://github.com/ArduPilot/MAVProxy/commit/bc6196d840146d317e04ec15bd725e01b34619ec) a few years ago but the default value for `--service` wasn't updated.

I cannot reproduce the second failure.

**Comment by onny** [comment]
> The first is just a bug. `OviHybrid` was [removed](https://github.com/ArduPilot/MAVProxy/commit/bc6196d840146d317e04ec15bd725e01b34619ec) a few years ago but the default value for `--service` wasn't updated.
> 
> I cannot reproduce the second failure.

Is there a upstream patch for the first bug? Or can we reference the upstream issue?

**Comment by lopsided98** [comment]
There is no upstream issue, probably because few people actually run `mp_tile.py` directly. Normally it is imported as a library, which unfortunately doesn't work either because of the shell script wrapper. This latter issue is not specific to mavproxy, see: https://github.com/NixOS/nixpkgs/issues/72345

IMO neither of these issues should block a routine update. I created a PR to fix the default tile service (https://github.com/ArduPilot/MAVProxy/pull/1100), but I don't we need to backport it, especially given the frequency of mavproxy releases.

**Comment by onny** [comment]
Please rebase on top of master, there seems to be a merge conflict. Thank you for pointing out the usage of this app

**Comment by lopsided98** [comment]
The packages were auto-updated in other PRs and the OpenCV dependency was added, so the only remaining changes are pretty minor: adding a dependency on lxml, which was already implicit, and alphabetizing the dependencies.

**Comment by onny** [comment]
@ofborg build mavproxy

**Pull request merged**
