### PR TITLE
nixos/tests/postfix: migrate test to use tlsTrustedAuthorities

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

This fixes the tests to work after 632104e.

Discovered in https://github.com/NixOS/nixpkgs/pull/94457#issuecomment-667580428.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
CC @asbachb

**Comment by mweinelt** [comment]
This also adds passthru.tests.

**Comment by mweinelt** [comment]
Hey @asbachb, can you please check this?

**Comment by asbachb** [comment]
@mweinelt tbh I don't feel competent enough with nixos testsing to approve the changes.

/cc @peti @nlewo can you help out?

**Review by nlewo — APPROVED** [review]
Sorry for the latency :(
Could you rebase?

**Comment by mweinelt** [comment]
> error: value is a function while a set was expected, at /home/hexa/git/nixos/master/nixos/tests/postfix.nix:14:19

I tried rebasing it, but now fails like so. Seems to have issues accesssing `certs.ca.cert`?

**Comment by mweinelt** [comment]
@nlewo Fixed!

**Comment by nlewo** [comment]
@mweinelt Cool! Thank you.

**Pull request merged**
