### PR TITLE
indent: 2.2.10 -> 2.2.12

### PR DESCRIPTION
**Pull request by mmahut**
###### Motivation for this change

Update to the latest version which fixes issue #61768.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
---

### CODE REVIEW

**Review by tomberek — APPROVED** [review]
Builds, runs, functions on Ubuntu. Reverse dependencies function (lush2 tested)

**Comment by grahamc** [comment]
@grahamcofborg build lush2 
@grahamcofborg build indent

**Review by grahamc — CHANGES_REQUESTED** [review]
Looks like this doesn't build on Darwin for some reason: https://logs.nix.ci/?key=nixos/nixpkgs.61808&attempt_id=f4f37ee3-367c-4f22-b0e7-5b3e09114e24 That is a blocker, as it is in such a large number of closures.

**Comment by grahamc** [comment]
cc @lnl7 do you have insight in to what is going on with this failure?

**Comment by mmahut** [comment]
cc @acowley as he has fixed something similar for indent in the past

**Comment by LnL7** [comment]
Looks like something glibc specific was added, 7790868 should do the trick.

**Comment by LnL7** [comment]
@GrahamcOfBorg build lush2
@GrahamcOfBorg build indent

**Pull request merged**
