### PR TITLE
rocmPackages.rocfft: fix build

### LINKED ISSUE #305641: Build failure: rocmPackages, rocmPackages_5
### Steps To Reproduce

The build for a lot of ROCm components broke with 6083fb0a158607ce76c1cc0849e89eb35d66cfa7, which updated CMake from 3.29.0 to 3.29.1, basically breaking all of ROCm.
This commit was merged via https://github.com/NixOS/nixpkgs/pull/298979 and recently made its way from staging into unstable in the last few days.

1. `nix build nixpkgs/716b484faececc3cd4570cc612ec9e927427d682#rocmPackages.rccl`

### Build log

The builds for a number of ROCm components now fail with error messages like the following:

```
CMake Error in library/CMakeLists.txt:
  Imported target "hip::device" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

### Additional context

This is possible related to how ROCm uses `CMAKE_INSTALL_<dir>` of CMake incorrectly.
See https://github.com/NixOS/nixpkgs/pull/197838#discussion_r1006537286 and https://github.com/ROCm/rocm-cmake/issues/121 which is linked in that comment thread.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by marsam**
## Description of changes

Fixes https://github.com/NixOS/nixpkgs/issues/305641
cc: @mschwaig 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by rjpcasalino** [comment]
this works

**Review by rjpcasalino — APPROVED** [review]

**Comment by rjpcasalino** [comment]
but fyi https://github.com/NixOS/nixpkgs/issues/305641#issuecomment-2067823151

**Comment by mschwaig** [comment]
Thanks for the PR. :+1: 

I would run `nixpkgs-review` on this if it also fixed ROCm 5.7.

Do you happen to know if this fix will break the build again once the CMake version update is actually merged?

If not, I think this might be a reasonable fix, otherwise I don't know.

I think we also have to weigh this against other possible fixes like https://github.com/NixOS/nixpkgs/issues/305641#issuecomment-2070604266.

**Comment by rjpcasalino** [comment]
`nixpkgs-review` on this crashed my machine :crying_cat_face:

**Comment by mschwaig** [comment]
> `nixpkgs-review` on this crashed my machine 😢 but it worked when I used this branch directly but would like `nixpkgs-review` to pass

You need boatloads or RAM to build ROCm, so that might be why.

Slightly over 64 GB, from what I saw, even with `--build-args="--max-jobs 4"` . You might get buy with 64 GB with that flag set to 4 or maybe a little lower and zram for ram compression.

**Comment by nonetrix** [comment]
> > `nixpkgs-review` on this crashed my machine 😢 but it worked when I used this branch directly but would like `nixpkgs-review` to pass
> 
> You need boatloads or RAM to build ROCm, so that might be why.
> 
> Slightly over 64 GB, from what I saw, even with `--build-args="--max-jobs 4"` . You might get buy with 64 GB with that flag set to 4 or maybe a little lower and zram for ram compression.

I have been building it without issue on ollama package with 64GBs of RAM, but I haven't tweaked anything. Just takes half a century, I also only have 16 cores pretty sure more cores being used = more memory needed

**Pull request closed without merging**
