### PR TITLE
vulkan: 1.1 -> 1.2

### PR DESCRIPTION
**Pull request by Ralith**
###### Motivation for this change
Broad ecosystem update for the minor version bump. Definitely want this for the next NixOS release.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pingiun** [comment]
https://github.com/NixOS/nixpkgs/pull/78746
3 package failed to build:
libretro.atari800 libretro.hatari libretro.play

101 package built:
celluloid curseradio deepin.dde-file-manager deepin.deepin-movie-reborn deepin.startdde dolphinEmuMaster glslang kodiPlugins.steam-launcher libplacebo libretro._4do libretro.beetle-gba libretro.beetle-lynx libretro.beetle-ngp libretro.beetle-pce-fast libretro.beetle-pcfx libretro.beetle-psx libretro.beetle-saturn libretro.beetle-snes libretro.beetle-supergrafx libretro.beetle-vb libretro.beetle-wswan libretro.bluemsx libretro.bsnes-mercury libretro.desmume libretro.desmume2015 libretro.dolphin libretro.dosbox libretro.fba libretro.fceumm libretro.flycast libretro.gambatte libretro.genesis-plus-gx libretro.gpsp libretro.handy libretro.higan-sfc libretro.mame libretro.mame2000 libretro.mame2003 libretro.mame2003-plus libretro.mame2010 libretro.mame2015 libretro.mame2016 libretro.mesen libretro.mgba libretro.mupen64plus libretro.nestopia libretro.o2em libretro.parallel-n64 libretro.pcsx_rearmed libretro.picodrive libretro.ppsspp libretro.prboom libretro.prosystem libretro.quicknes libretro.scummvm libretro.snes9x libretro.snes9x2002 libretro.snes9x2005 libretro.snes9x2010 libretro.stella libretro.vba-m libretro.vba-next libretro.vecx libretro.virtualjaguar libretro.yabause linux-steam-integration lutris lutris-free lutris-unwrapped minitube mpc-qt mpv mpv-with-scripts openxr-loader pipelight playonlinux plex-media-player python37Packages.mpv python38Packages.mpv renderdoc retroarch retroarchBare rpcs3 shaderc steam steam-run steam-run-native steamcmd vkquake vulkan-headers vulkan-loader vulkan-tools vulkan-validation-layers wine wine-staging winePackages.base winePackages.staging wineWowPackages.base wineWowPackages.full wineWowPackages.staging winetricks

**Comment by Ralith** [comment]
> 3 package failed to build:
> libretro.atari800

```
libretro/libretro-core.c: In function 'retro_get_system_info':
libretro/libretro-core.c:575:36: error: expected ';' before 'GIT_VERSION'
  575 |    info->library_version  = "3.1.0" GIT_VERSION;
      |                                    ^~~~~~~~~~~~
      |                                    ;
```

Looks like unrelated breakage in libretro itself to me.

**Comment by Ralith** [comment]
Patch release applied. Bump?

**Comment by pingiun** [comment]
lgtm

**Comment by FRidh** [comment]
If you think this should go into 20.03, please open a PR against release-20.03.

**Comment by worldofpeace** [comment]
Same.

**Comment by Ralith** [comment]
Backport opened at https://github.com/NixOS/nixpkgs/pull/79852

**Pull request merged**
