### PR TITLE
cage: upgrade to wlroots 0_15

### PR DESCRIPTION
**Pull request by wineee**
###### Description of changes

wlroots 0.15 compatible tag still not released： https://github.com/cage-kiosk/cage/issues/232

Let's pick up some commit to support  wlroots 0_15 as archlinux did 
https://github.com/archlinux/svntogit-community/blob/packages/cage/trunk/PKGBUILD#L25-L29

This is the last package that depends on wlroot 0.14： https://github.com/NixOS/nixpkgs/issues/151311

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wineee** [comment]
cage.passthru.tests failed

**Comment by wineee** [comment]
@ofborg test cage

**Comment by wineee** [comment]
Discussion of related issues:
https://www.reddit.com/r/swaywm/comments/rrhzl9/sway_17rc1_and_other_wlroots_015_compositors_on/
https://discourse.nixos.org/t/problem-with-sway-in-nixos-rebuild-build-vm-how-to-configure-vm/20263/2

**Comment by m-bdf** [comment]
Have you tried with `virtualisation.qemu.options = [ "-vga qxl" ]` ?

**Comment by wineee** [comment]
> Have you tried with `virtualisation.qemu.options = [ "-vga qxl" ]` ?

I tested it locally (nix-build . -A nixosTests.cage)， cage still doesn't start normally

**Comment by wineee** [comment]
@ofborg test cage

**Comment by wineee** [comment]
The script below works fine，not sure why nixosTests fails


```nix
# nix run -v -L
{
  inputs.nixpkgs.url = "github:wineee/nixpkgs/cage";

  outputs = inputs@{ self, nixpkgs }: let 
    system = "x86_64-linux";
    pkgs = import nixpkgs { inherit system; };
  in {
    nixosConfigurations.vm = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = [
        {
        imports = [ "${nixpkgs}/nixos/modules/virtualisation/qemu-vm.nix" ];
        
        services.cage = {
          enable = true;
          user = "test";
          program = "${pkgs.xterm}/bin/xterm";
        };
        
        users.users.test = {
          isNormalUser = true;
          extraGroups = [ "wheel" ];
          password = "test";
        };
        fonts.fonts = with pkgs; [ dejavu_fonts ];
        virtualisation.qemu.options = [ "-vga none" "-device virtio-vga-gl" "-display gtk,gl=on" ];
        system.stateVersion = "23.05";
      }];
    };
    packages.${system}.default = self.nixosConfigurations.vm.config.system.build.vm;
    apps.${system}.default = {
      type = "app";
      program = "${self.packages.${system}.default}/bin/run-nixos-vm";
    };
  };
}

```

**Comment by wineee** [comment]
close this as cage has new release
https://github.com/NixOS/nixpkgs/pull/245892

**Pull request closed without merging**
