### PR TITLE
python3Packages.hdf5plugin: 4.1.2 -> 4.1.3, fix maintainer

### PR DESCRIPTION
**Pull request by pbsds**
## Description of changes

This PR changes the maintainer from bhipple to me.
I set the wrong maintainer when i introduced hdf5plugin in #211851, as a copy-paste mistake.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tjni** [comment]
Result of `nixpkgs-review pr 247732` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.hdf5plugin</li>
    <li>python310Packages.hdf5plugin.dist</li>
    <li>python311Packages.hdf5plugin</li>
    <li>python311Packages.hdf5plugin.dist</li>
  </ul>
</details>

**Comment by tjni** [comment]
Result of `nixpkgs-review pr 247732` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.hdf5plugin</li>
    <li>python310Packages.hdf5plugin.dist</li>
    <li>python311Packages.hdf5plugin</li>
    <li>python311Packages.hdf5plugin.dist</li>
  </ul>
</details>

**Review by tjni — APPROVED** [review]

**Comment by natsukium** [comment]
@ofborg build python310Packages.hdf5plugin

**Review by D4ndellion — APPROVED** [review]

**Review by natsukium — APPROVED** [review]
The diff looks fine.
How about replacing `checkPhase` with `pytestCheckHook`?

**Comment by pbsds** [comment]
Did some testing. pytestCheckHook tries to test the wrong files, and when directed at `test/` it fails to run the tests. The current check on the other hand does the same as the [upstream ci](https://github.com/silx-kit/hdf5plugin/blob/main/.github/workflows/ci.yml#L109).

**Comment by natsukium** [comment]
Try this next time.
```nix
  pytestFlagsArray = [
    "test/test.py"
  ];
```
Thanks!

**Pull request merged**
