### PR TITLE
luarocks: 3.2.1 -> 3.7.0

### PR DESCRIPTION
**Pull request by averms**
###### Motivation for this change

Update luarocks. The version currently packaged is broken for Lua version 5.4: luarocks/luarocks#1060

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- N/A For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- N/A Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - N/A (I think) (Package updates) Added a release notes entry if the change is major or breaking
  - N/A (Module updates) Added a release notes entry if the change is significant
  - N/A (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
it's a known issue see https://github.com/NixOS/nixpkgs/pull/80528

**Comment by doronbehar** [comment]
@7c6f434c please revert this update :pray: We can't break updates for all Neovim users..

**Comment by 7c6f434c** [comment]
Let's at least add 3.7 as a separate package so that it is more visible that Luarocks is _explicitly_ no the freshest

**Comment by teto** [comment]
I wanted to hack on neovim which required a newer libuv, so I spent a few hours on this issue and related (https://github.com/NixOS/nixpkgs/issues/163134) and found the luarocks bug https://github.com/luarocks/luarocks/issues/1402 (marked as wont fix). I ended up doing things sideways: Could anyone check that https://github.com/NixOS/nixpkgs/pull/166162 works for them ?

**Pull request merged**
