### PR TITLE
llvmPackages_18: 18.1.1 -> 18.1.3

### PR DESCRIPTION
**Pull request by RossComputerGuy**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by wegank** [comment]
@ofborg build llvmPackages_18

**Comment by RossComputerGuy** [comment]
Before we merge, should we change the default LLVM version to 18 in `pkgs/top-level/all-packages.nix`?

**Comment by wegank** [comment]
Probably much later, as LLVM is a [release-critical package](https://nixos.github.io/release-wiki/Release-Critical-Packages.html), and I guess we don't have time to test everything, according to the [24.05 release schedule](https://nixos.github.io/release-wiki/Release-Process.html).

**Comment by RossComputerGuy** [comment]
Yeah, good to know. We can wait until after the release. I definitely don't have time myself to test those kinds of things.

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 302738` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>40 packages built:</summary>
  <ul>
    <li>clang-tools_18</li>
    <li>clang_18 (llvmPackages_18.clang ,llvmPackages_18.libcxxClang)</li>
    <li>include-what-you-use</li>
    <li>lld_18 (llvmPackages_18.lld)</li>
    <li>lld_18.dev (llvmPackages_18.lld.dev)</li>
    <li>lld_18.lib (llvmPackages_18.lld.lib)</li>
    <li>lldb_18 (llvmPackages_18.lldb)</li>
    <li>lldb_18.dev (llvmPackages_18.lldb.dev)</li>
    <li>lldb_18.lib (llvmPackages_18.lldb.lib)</li>
    <li>llvmPackages_18.clang-manpages</li>
    <li>llvmPackages_18.libclang (llvmPackages_18.clang-unwrapped)</li>
    <li>llvmPackages_18.libclang.dev (llvmPackages_18.clang-unwrapped.dev)</li>
    <li>llvmPackages_18.libclang.lib (llvmPackages_18.clang-unwrapped.lib)</li>
    <li>llvmPackages_18.libclang.python (llvmPackages_18.clang-unwrapped.python)</li>
    <li>llvmPackages_18.clangNoCompilerRt</li>
    <li>llvmPackages_18.clangNoCompilerRtWithLibc</li>
    <li>llvmPackages_18.clangNoLibc</li>
    <li>llvmPackages_18.clangNoLibcxx</li>
    <li>llvmPackages_18.clangUseLLVM</li>
    <li>llvmPackages_18.compiler-rt (llvmPackages_18.compiler-rt-libc ,llvmPackages_18.compiler-rt-no-libc)</li>
    <li>llvmPackages_18.compiler-rt.dev (llvmPackages_18.compiler-rt-libc.dev)</li>
    <li>llvmPackages_18.libclc</li>
    <li>llvmPackages_18.libclc.dev</li>
    <li>llvmPackages_18.libcxx</li>
    <li>llvmPackages_18.libcxx.dev</li>
    <li>llvmPackages_18.stdenv (llvmPackages_18.libcxxStdenv)</li>
    <li>llvm_18 (llvmPackages_18.llvm)</li>
    <li>llvm_18.dev (llvmPackages_18.llvm.dev)</li>
    <li>llvm_18.lib (llvmPackages_18.llvm.lib)</li>
    <li>llvm_18.python (llvmPackages_18.llvm.python)</li>
    <li>llvmPackages_18.libstdcxxClang</li>
    <li>llvmPackages_18.libunwind</li>
    <li>llvmPackages_18.libunwind.dev</li>
    <li>llvmPackages_18.lldb-manpages</li>
    <li>llvmPackages_18.llvm-manpages</li>
    <li>llvmPackages_18.mlir</li>
    <li>llvmPackages_18.mlir.dev</li>
    <li>llvmPackages_18.openmp</li>
    <li>llvmPackages_18.openmp.dev</li>
    <li>tests.cc-wrapper.llvmTests.llvmPackages_18.clang (tests.cc-wrapper.llvmTests.llvmPackages_18.libcxx)</li>
  </ul>
</details>

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 302738` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>40 packages built:</summary>
  <ul>
    <li>clang-tools_18</li>
    <li>clang_18 (llvmPackages_18.clang ,llvmPackages_18.libcxxClang)</li>
    <li>include-what-you-use</li>
    <li>lld_18 (llvmPackages_18.lld)</li>
    <li>lld_18.dev (llvmPackages_18.lld.dev)</li>
    <li>lld_18.lib (llvmPackages_18.lld.lib)</li>
    <li>lldb_18 (llvmPackages_18.lldb)</li>
    <li>lldb_18.dev (llvmPackages_18.lldb.dev)</li>
    <li>lldb_18.lib (llvmPackages_18.lldb.lib)</li>
    <li>llvmPackages_18.clang-manpages</li>
    <li>llvmPackages_18.libclang (llvmPackages_18.clang-unwrapped)</li>
    <li>llvmPackages_18.libclang.dev (llvmPackages_18.clang-unwrapped.dev)</li>
    <li>llvmPackages_18.libclang.lib (llvmPackages_18.clang-unwrapped.lib)</li>
    <li>llvmPackages_18.libclang.python (llvmPackages_18.clang-unwrapped.python)</li>
    <li>llvmPackages_18.clangNoCompilerRt</li>
    <li>llvmPackages_18.clangNoCompilerRtWithLibc</li>
    <li>llvmPackages_18.clangNoLibc</li>
    <li>llvmPackages_18.clangNoLibcxx</li>
    <li>llvmPackages_18.clangUseLLVM</li>
    <li>llvmPackages_18.compiler-rt (llvmPackages_18.compiler-rt-libc ,llvmPackages_18.compiler-rt-no-libc)</li>
    <li>llvmPackages_18.compiler-rt.dev (llvmPackages_18.compiler-rt-libc.dev)</li>
    <li>llvmPackages_18.libclc</li>
    <li>llvmPackages_18.libclc.dev</li>
    <li>llvmPackages_18.libcxx</li>
    <li>llvmPackages_18.libcxx.dev</li>
    <li>llvmPackages_18.stdenv (llvmPackages_18.libcxxStdenv)</li>
    <li>llvm_18 (llvmPackages_18.llvm)</li>
    <li>llvm_18.dev (llvmPackages_18.llvm.dev)</li>
    <li>llvm_18.lib (llvmPackages_18.llvm.lib)</li>
    <li>llvm_18.python (llvmPackages_18.llvm.python)</li>
    <li>llvmPackages_18.libstdcxxClang</li>
    <li>llvmPackages_18.libunwind</li>
    <li>llvmPackages_18.libunwind.dev</li>
    <li>llvmPackages_18.lldb-manpages</li>
    <li>llvmPackages_18.llvm-manpages</li>
    <li>llvmPackages_18.mlir</li>
    <li>llvmPackages_18.mlir.dev</li>
    <li>llvmPackages_18.openmp</li>
    <li>llvmPackages_18.openmp.dev</li>
    <li>tests.cc-wrapper.llvmTests.llvmPackages_18.clang (tests.cc-wrapper.llvmTests.llvmPackages_18.libcxx)</li>
  </ul>
</details>

**Pull request merged**
