### PR TITLE
Make a configuration management tool based on Nix to manage User Profiles.

### PR DESCRIPTION
**Pull request by nbp**
This pull request is made to bootstrap a variant of NixOS, which is dedicated at managing the home directory of users.  This new project is called NixUP (Nix User Profile), and the goals are the following:
- [✓] Generate an activation script.
- [✓] Abstract the creation of resource files. (similar to environment.etc)
- [✓] Option to list installed packages. (similar to system.packages)
- [✗] Command line tool to manage profiles generations and updates.  (similar to nixos-rebuild)
- [✗] Command line tool to write / read option definition without using an editor.  (no legacy yet)
- [✗] Mock compatibility modules to use some NixOS modules in NixUP.
- [✗] Include NixUP modules as submodules of NixOS option `users.extraUser.<name?>`

### CODE REVIEW

**Comment by jagajaga** [comment]
Ping? :)

**Comment by nbp** [comment]
I am currently doing some clean-up on NixOS, mostly as a way to try a way to include similar work as this one in NixOS (such as within extraUsers).

So far you can already use this branch, but the commands might be a bit raw as you would have to basically type manually what is done by nixos-rebuild — without the nix update.

I will have to get back to it, and think more on how to make a command line tool which is both similar to `nix-env` and also compatible with the module system.  The idea would be to have something like:

```
$ nixup extend config ssh.authorizedKeys ./id.pub
```

**Comment by copumpkin** [comment]
:+1:

**Comment by copumpkin** [comment]
Does this actually need NixOS? It seems like anything that can run Nix could have its user profiles managed this way.

**Comment by jagajaga** [comment]
@copumpkin good point

**Comment by nbp** [comment]
Closing: This work is taken over by @ts468 in #9250.

**Pull request closed without merging**
