### PR TITLE
nrfconnect: 3.11.1 -> 4.0.1

### PR DESCRIPTION
**Pull request by eyJhb**
###### Description of changes
Updated to latest nrfconnect

###### Things done
Updated and tested

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wegank** [comment]
Looks good, but is it a breaking change?

**Comment by eyJhb** [comment]
Unsure, each time I open up the current version (3.x), it says that most of the tools are only supported by 4.x :)

**Comment by wegank** [comment]
So it looks like it doesn't quite work on version 3.x, I guess.

Does the version upgrade require any manual migration on the user side? If not, this PR should be good for merging.

**Comment by eyJhb** [comment]
Sadly I have no clue @wegank , I would assume that nrfconnect would prompt if anything needs to happen.
I just started using this software, and are not all that into how it should behave etc.

I just know that I can now use the Power Profiler :D But this package hasn't been touched since it was first init, so I would assume that not too many use it (might be a bad assumption).

**Pull request merged**
