### PR TITLE
tensorflow: 0.9.0 -> 0.10.0, support for Darwin

### PR DESCRIPTION
**Pull request by jhhuh**
###### Motivation for this change

Tensorflow package binary file name was hard coded for linux platform. 'isDarwin' conditional is added to support Darwin system. Tensorflow version is moved from 0.9.0 to 0.10.0 since 0.9.0 is not functional in OSX. Required python packages Mock 2.0.0 and funcsigs 1.0.2 are added as well.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [x] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
@jhhuh please check https://github.com/NixOS/nixpkgs/pull/19701

**Comment by FRidh** [comment]
cc @teh

**Comment by teh** [comment]
@jhhuh if you can rebase against my branch that @FRidh already merged this should be fine. I think you can update `platforms   = platforms.linux` to include darwin as well. I can't test darwin so if it breaks I'll refer to you.

**Comment by jhhuh** [comment]
@FRidhThanks for the comments. Yes, I will check your PR. @teh Yes, let me do the rebase.

**Comment by FRidh** [comment]
If this is ready, then @jhhuh , can you squash the commits.

**Comment by jhhuh** [comment]
@FRidh Now they are squashed.

**Pull request merged**
