### PR TITLE
 uasm: 2.56.2 -> 2.57 

### LINKED ISSUE #368633: Build failure: uasm
## Steps To Reproduce

1. build uasm from unstable (`github:nixos/nixpkgs/634fd46801442d760e09493a794c4f15db2d0cbb`).

## Build log

<details>
<summary>Build Log</summary>

```
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/w98ia5fj94bmi7zm17wq63cc3rya2hrh-source
source root is source
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
applying patch /nix/store/96jj8d9f05shwww7nrzx60k4q4077p8s-fix-v2_55-compilation-on-macos.patch
patching file ClangOSX64.mak
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
no configure script, doing nothing
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
build flags: -j3 SHELL=/nix/store/5mh7kaj2fyv8mk4sfq1brwxgc02884wi-bash-5.2p37/bin/bash CC=cc
mkdir GccUnixR
cc -D __UNIX__ -c -IH -D __UNIX__ -DNDEBUG -O2 -funsigned-char -Wwrite-strings   -o GccUnixR/main.o main.c
cc -D __UNIX__ -c -IH -D __UNIX__ -DNDEBUG -O2 -funsigned-char -Wwrite-strings   -o GccUnixR/apiemu.o apiemu.c
cc -D __UNIX__ -c -IH -D __UNIX__ -DNDEBUG -O2 -funsigned-char -Wwrite-strings   -o GccUnixR/orgfixup.o orgfixup.c
cc -D __UNIX__ -c -IH -D __UNIX__ -DNDEBUG -O2 -funsigned-char -Wwrite-strings   -o GccUnixR/assemble.o assemble.c
main.c: In function 'main':
main.c:95:17: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
   95 |         argv[0] = pEnv;
      |                 ^
cc -D __UNIX__ -c -IH -D __UNIX__ -DNDEBUG -O2 -funsigned-char -Wwrite-strings   -o GccUnixR/assume.o assume.c
cc -D __UNIX__ -c -IH -D __UNIX__ -DNDEBUG -O2 -funsigned-char -Wwrite-strings   -o GccUnixR/atofloat.o atofloat.c
assemble.c: In function 'PassOneChecks':
assemble.c:1042:32: warning: comparison between pointer and integer
 1042 |         if ( curr->sym.altname > 1 )
      |                                ^
assemble.c: In function 'OnePass':
assemble.c:1181:17: error: implicit declaration of function 'AddSimdTypes' [-Wimplicit-function-declaration]
 1181 |                 AddSimdTypes();
      |                 ^~~~~~~~~~~~
In file included from assemble.c:18:
assemble.c: In function 'get_module_name':
H/globals.h:51:17: error: implicit declaration of function 'strupr'; did you mean '_strupr'? [-Wimplicit-function-declaration]
   51 | #define _strupr strupr
      |                 ^~~~~~
assemble.c:1280:5: note: in expansion of macro '_strupr'
 1280 |     _strupr( ModuleInfo.name );
      |     ^~~~~~~
assemble.c: In function 'GetExt':
assemble.c:1430:23: warning: return discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 1430 |                 return( EXE_EXT );
      |                       ^
assemble.c:1433:23: warning: return discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 1433 |                 return( BIN_EXT );
      |                       ^
assemble.c:1435:15: warning: return discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 1435 |         return( OBJ_EXT );
      |               ^
assemble.c:1437:15: warning: return discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 1437 |         return( LST_EXT );
      |               ^
assemble.c:1439:15: warning: return discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 1439 |         return( ERR_EXT );
      |               ^
In file included from assemble.c:94:
assemble.c: In function 'AssembleModule':
H/Colors.h:12:15: warning: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'uint_32' {aka 'unsi>
   12 | #define KWHT  "\x1B[37m"
      |               ^~~~~~~~~~
H/Colors.h:20:17: note: in expansion of macro 'KWHT'
   20 | #define FWHT(x) KWHT x RST
      |                 ^~~~
assemble.c:1801:56: note: in expansion of macro 'FWHT'
 1801 |                                                 printf(FWHT("%s: %lu lines, "), GetFNamePart(GetFName(ModuleInfo.srcfile)->
      |                                                        ^~~~
make: *** [gccLinux64.mak:35: GccUnixR/assemble.o] Error 1
make: *** Waiting for unfinished jobs....
```

</details>

## Additional context

From what I can see, probably related to new gcc 14 default.
I set `nixpkgs.hostPlatform.gcc.{arch,tune}` to `"znver4"`, which may be relevant.

The package was being built as a dependency of `7zz`, because I had had `useUasm` enabled because the feature flag didn't work correctly before a recent commit.
I have since disabled it, and `7zz` builds fine, so this is no longer relevant to me, but still a failure that should probably be addressed.

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.5-xanmod1, NixOS, 25.05 (Warbler), 25.05.20241219.d70bd19`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.1
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux, x86_64-v4-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/alfarel/.config/nix/nix.conf:/nix/store/v5pkh7wda19iw13vsc4ma7cr8sbhzxs1-stylix-kde-config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/alfarel/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/alfarel/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/alfarel/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/3vdv3p0nhfzz4k3xv5dfmn6qw653xc2z-lix-2.91.1/share`
 - nixpkgs: `/nix/store/8fwsiv0hd7nw1brkvka0jf1frk3m7qkr-source`

## Notify maintainers

@thiagokokada 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by thiagokokada**
Fix: https://github.com/NixOS/nixpkgs/issues/368633.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by thiagokokada** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368803`

---
### `x86_64-darwin`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>uasm</li>
  </ul>
</details>

**Comment by thiagokokada** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368803`

---
### `aarch64-darwin`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>uasm</li>
  </ul>
</details>

**Comment by lucasewd** [comment]
# [nixpkgs-reviewd](https://github.com/nixosbrasil/nixpkgs-reviewd) workflow started

**Status and logs**: https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12527628319
**Extra args**: ``

**Comment by lucasewd** [comment]
# [nixpkgs-reviewd](https://github.com/nixosbrasil/nixpkgs-reviewd) workflow finished

**Status and logs**: https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12527628319


## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368803`

---
### `x86_64-darwin`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>uasm</li>
  </ul>
</details>

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368803`

---
### `aarch64-darwin`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>uasm</li>
  </ul>
</details>

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368803`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>uasm</li>
  </ul>
</details>

**Comment by lucasewd** [comment]
# [nixpkgs-reviewd](https://github.com/nixosbrasil/nixpkgs-reviewd) workflow started

**Status and logs**: https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12528490091
**Extra args**: ``

**Comment by lucasewd** [comment]
# [nixpkgs-reviewd](https://github.com/nixosbrasil/nixpkgs-reviewd) workflow finished

**Status and logs**: https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12528490091


## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368803`

---
### `x86_64-darwin`
<details>
  <summary>:fast_forward: 1 package marked as broken and skipped:</summary>
  <ul>
    <li>uasm</li>
  </ul>
</details>

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368803`

---
### `aarch64-darwin`
<details>
  <summary>:fast_forward: 1 package marked as broken and skipped:</summary>
  <ul>
    <li>uasm</li>
  </ul>
</details>

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368803`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>uasm</li>
  </ul>
</details>

**Review by lucasew — APPROVED** [review]

**Pull request merged**
