### PR TITLE
vscode-extensions.rust-lang.rust-analyzer: 0.2.1048 -> 0.3.1059

### LINKED ISSUE #173388: Rust-analyzer's inlay hints not appearing in VSCode/VSCodium
### Describe the bug
Rust-analyzer's inlay hints don't appear when opening a rust project in VSCode/VSCodium.

### Steps To Reproduce
1. Use the following home-manager config:
```nix
  home-manager.users.<name> = {
    programs.vscode = {
      enable = true;
      extensions = [ pkgs.vscode-extensions.matklad.rust-analyzer ];
      userSettings = { "rust-analyzer.trace.server" = "verbose"; };
    };
  };
```
2. Open a rust project
3. Observe that no inlay hints are shown
4. Observe an error in the `Rust Analyzer Language Server` output along the lines of
```
[ERROR rust_analyzer::dispatch] unknown request: Request { id: RequestId(I32(33)), method: "rust-analyzer/inlayHints", params: Object({"textDocument": Object({"uri": String("file:///path/to/project/src/main.rs")})}) }
```

### Expected behavior
Inlay hints are visible.

### Additional context
Probably broken since #171464.

In VSCode version 1.66, official support for [inlay hints via LSP](https://code.visualstudio.com/updates/v1_66#_language-server-protocol) was added. In [release 2022-04-18](https://github.com/rust-analyzer/rust-analyzer/releases/2022-04-18), rust-analyzer switched to this instead of its own custom inlay hints.

The error looks like the rust-analyzer vscode plugin is still trying to use these custom inlay hints even though the server binary is already using the native LSP inlay hints and does not understand the custom messages any more.

I thought #172842 (or maybe #173074) might fix the issues, but it didn't.

I tried updating `pkgs/applications/editors/vscode/extensions/rust-analyzer/default.nix` with the latest release tag, as well as running the update script. When I did that, the error (step 4. of reproduction) stopped being printed, but no inlay hints were displayed even though they were active both in the vscode and rust-analyzer config. The LSP trace looked normal, with vscode advertising its inlay hint capability and rust-analyzer registering itself as inlay hint provider.

### Notify maintainers
@austinbutler
@happysalada
@AleksanderGondek

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.7, NixOS, 22.05 (Quokka), 22.05pre378063.1d7db1b9e4c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(joscha): `""`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by Garmelon**
###### Description of changes

This PR updates the rust-analyzer vscode extension to the latest version. It also moves the extension from `vscode-extensions.matklad.rust-analyzer` to `vscode-extensions.rust-lang.rust-analyzer` because the extension's publisher was changed on the vscode marketplace. For backwards compatibility, `vscode-extensions.matklad.rust-analyzer` still points to the extension. I don't know how to deprecate it.

It seems like the vscode extension's update script was ran regularly, but the actual release tag and associated hash was not updated as frequently, so I added a reminder to the update script.

Closes  #173388.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by oxalica** [comment]
The update of `rust-analyzer` part is conflict with #173422

**Comment by Garmelon** [comment]
Oh sorry, I didn't see that. Removed the commit updating rust-analyzer itself.

**Comment by happysalada** [comment]
Thank you!

**Comment by Garmelon** [comment]
My update of the extension's publisher was apparently lost during rebasing, so I opened another tiny PR at #174097

**Pull request merged**
