### PR TITLE
Libvirt security updates

### PR DESCRIPTION
**Pull request by nathanielbaxter**
See #6416 

Edit:
There's a 1.2.9.2 maintenance release that is meant to fix the CVE's listed in the previous PR. Should we push the update to 1.2.12 or use the maintenance release for stable?

### CODE REVIEW

**Comment by bjornfor** [comment]
Looking at the changelog[1] between 1.2.9 and 1.2.12, although it is very long and I couldn't read all, the entries under "new features" are very few. And they don't mention any backwards compatibility issues (in the changelog at least). The other sections in the changelog are "security", "documentation", "improvements", "bug fixes". So, it seems safe enough to go to 1.2.12, IMHO.

But then again, why did they make 1.2.9.2, if 1.2.12 seems so safe? :-)

Btw, for backporting commits, Eelco prefers "cherry-pick -x" (which I completely understand). (I can do that myself, it's just FYI.)

1: http://libvirt.org/news.html

**Comment by nathanielbaxter** [comment]
Ah, yeah cherry-pick -x makes sense. :)

**Comment by bjornfor** [comment]
Oh, you closed it? I thought it was a good idea to keep it open for discussions. (And now I cannot re-open because the branch is gone.)

So... cherry-pick or use the tiny bugfix-release 1.2.9.2? If nobody objects, I think I'll go for the cherry-pick.

**Comment by nathanielbaxter** [comment]
Ah, sorry, figured you'ld decided to use the 1.2.12 release. :)

I don't mind

**Comment by lethalman** [comment]
Fails to build, see travis error. Please enable nix chroot builds: http://nixos.org/nixos/manual/ch-options.html#opt-nix.useChroot

**Comment by nathanielbaxter** [comment]
@lethalman I do use nix chroot builds. This doesn't fail to build locally for me, so I'm confused by the travis error.

**Comment by lethalman** [comment]
Built locally, thanks.

**Pull request merged**
