### PR TITLE
[WIP] home-assistant: 0.85.1 -> 0.86.4

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
https://www.home-assistant.io/blog/2019/01/23/release-86/

I'm still in the process of adding a `lovelaceConfig` option to the NixOS module. I have however no experience with Lovelace and hope one of you guys might have some insight into wether this seems useful and what to think about when adding it.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterhoeg** [comment]
I have a *ton* of HA customizations and am also writing out lovelaceConfig from here as well. That probably should be mostly upstreamed... It's basically just a very large attrSet with some helpers thrown in to automate certain elements.

**Comment by dotlambda** [comment]
Sound nice! I'll push what I have so you can have a look at it. Feel free to discard mine and push your own commit to this branch.

**Comment by peterhoeg** [comment]
I haven't had the time to try it out but it looks safe enough except for one thing. It's possible to edit the lovelace UI directly from the web interface, so instead of symlinking we probably should copy it. Instead of going through a whole nixops deploy cycle when shifting some minor things around, I was previously editing the lovelace config file directly and then consolidating all the changes when done. I don't think that will work when the file is read-only.

**Review by peterhoeg — APPROVED** [review]
LGTM!

**Pull request merged**
