### PR TITLE
Add tests for Sonarr, Radarr, Lidarr and Jackett

### PR DESCRIPTION
**Pull request by etu**
###### Motivation for this change
The first application (Sonarr) is a quite clunky mono-application that can be quite weird sometimes. And then we have Radarr and Lidarr which both are forks of Sonarr but are re-purposed so they can't be used for the same things. So all three are relevant to test.

I haven't seen breakage yet, but I'm always a bit scared when it comes to these three.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by etu** [comment]
@GrahamcOfBorg build nixosTests.sonarr nixosTests.radarr nixosTests.lidarr

**Comment by worldofpeace** [comment]
> I haven't seen breakage yet, but I'm always a bit scared when it comes to these three.

I feel the same way about these. Mind also adding one for `jackett`?

**Comment by Mic92** [comment]
You also need to add them to `nixos/tests/all-tests.nix` in order to reach them via `nixosTests`

**Comment by worldofpeace** [comment]
> I haven't seen breakage yet, but I'm always a bit scared when it comes to these three.

I feel the same way about these. Mind adding one for jackett also?
It should be pretty similar.

**Comment by etu** [comment]
@GrahamcOfBorg build nixosTests.sonarr nixosTests.radarr nixosTests.lidarr nixosTests.jackett

**Pull request merged**
