### PR TITLE
bcachefs-tools: unstable-2023-06-28 -> 1.3.1

### PR DESCRIPTION
**Pull request by ghost**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by amjoseph-nixpkgs** [comment]
@ofborg build bcachefs-tools

**Comment by amjoseph-nixpkgs** [comment]
We should probably consider updating our `linux_testing_bcachefs` at some point soon... I had some [really bad experiences](https://github.com/koverstreet/bcachefs/issues/608) with our patches-on-linux-6.4-based bcachefs.  Using the upstream nightly (6.7 prerelease) fixed them.

**Review by thoughtpolice — APPROVED** [review]
I'm running testing and would like to use this, so +1

**Comment by thoughtpolice** [comment]
> We should probably consider updating our `linux_testing_bcachefs` at some point soon... I had some [really bad experiences](https://github.com/koverstreet/bcachefs/issues/608) with our patches-on-linux-6.4-based bcachefs. Using the upstream nightly (6.7 prerelease) fixed them.

Why even keep `linux_testing_bcachefs` around at this point, now that bcachefs is in 6.7-rc1? That's probably where Kent will still put interim patches before getting pulled during the merge window&mdash;but we don't keep expressions for any other upstream maintainer branches (e.g. like Jens tree for io_uring)... Aside from it being impractical to track too many, maintainer branches are often unstable anyway since developers patch and fix bugs. bcachefs was only special before because it was not upstream *and* there was appetite to have an expression anyway. With the move upstream, I don't think there's any reason to keep it around.

**Comment by vcunat** [comment]
This conflicted with PR #256638.  Perhaps you want to check the result.

**Pull request merged**
