### PR TITLE
Zabbix: Add LTS version 7

### PR DESCRIPTION
**Pull request by gador**
## Description of changes

Add new LTS version of `zabbix`

[Whats new](https://www.zabbix.com/documentation/7.0/en/manual/introduction/whatsnew700)
[Breaking changes](https://www.zabbix.com/documentation/7.0/en/manual/installation/upgrade_notes_700#breaking-changes)

There are no breaking changes to the default installation (AFAIK). Database migration runs automatically. 

Supersedes #317463

Ping @mmahut and @psyanticy

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).
- [x] Tested basic functionality (web Server only) in a VM
- [x] Tested on my server Farm

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by gador** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 332290` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
9 packages built:
</summary>
<ul>
<li>zabbix-agent2-plugin-postgresql</li>
<li>zabbix70.agent</li>
<li>zabbix70.agent2</li>
<li>zabbix70.proxy-mysql</li>
<li>zabbix70.proxy-pgsql</li>
<li>zabbix70.proxy-sqlite</li>
<li>zabbix70.server</li>
<li>zabbix70.server-mysql</li>
<li>zabbix70.web</li>
</ul>
</details>

**Comment by aanderse** [comment]
this looks good

is this tested enough for me to hit merge?

**Comment by gador** [comment]
I've been running the server version for about a week and haven't noticed any regressions. It works well with the agent version 6.4 and 7.0

**Comment by aanderse** [comment]
awesome! let's get this merged once rebased + ci

thanks for your efforts

**Comment by aanderse** [comment]
thanks @gador!

**Pull request merged**
