### PR TITLE
buildGoModule: fix enableParallelBuilding

### PR DESCRIPTION
**Pull request by zowoq**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
@zowoq please target staging.

**Comment by zowoq** [comment]
>  please target staging.

Intentionally targeting master as we usually do for `go`.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 129205` at 214ee12c run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>810 packages skipped due to time constraints:</summary>
  <ul>
    <li>_3mux</li>
    <li>act</li>
    <li>aerc</li>
    <li>age</li>
    <li>agebox</li>
    <li>air</li>
    <li>alertmanager-bot</li>
    <li>alertmanager-irc-relay</li>
    <li>amass</li>
    <li>amfora</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>boringssl</li>
    <li>nginxQuic</li>
  </ul>
</details>

**Review by siraben — APPROVED** [review]
LGTM, but I'll let someone else hit the merge button 😇

**Comment by SuperSandro2000** [comment]
Can we default this to true by any chance?

**Comment by siraben** [comment]
This is already set to true.

**Pull request merged**
