### PR TITLE
gitkraken: 8.3.0 -> 8.3.3

### PR DESCRIPTION
**Pull request by asjur**
###### Motivation for this change
Gitkraken is outdated.

###### Things done
Added necessary libraries and updated checksum to match the new one.

I have not decided to reorder list of dependencies to "group" libraries as this has not been done by previous maintainers and by keeping newly added libraries at the end we know in which order they have been required by the software.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ModdedGamers** [comment]
Result of `nixpkgs-review pr 162753` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gitkraken</li>
  </ul>
</details>

**Comment by ModdedGamers** [comment]
Result of `nixpkgs-review pr 162753` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gitkraken</li>
  </ul>
</details>

**Review by pyrox0 — COMMENTED** [review]
LGTM, though the actual version change is 8.3.0 -> 8.3.2, instead of the 8.2.1 implied by the name of the PR.

**Comment by asjur** [comment]
Correct because another merge request was merged after the creation of my merge request and since I closed my 8.3.0 request because it was already outdated by the time it was merged.

**Comment by bobby285271** [comment]
Please also update the hash for aarch64-darwin

**Comment by asjur** [comment]
Done. Sha for ARM64 Darwin is up to date.

**Comment by rhoriguchi** [comment]
@asjur there's a new version `8.3.3`

<https://support.gitkraken.com/release-notes/current>

**Comment by asjur** [comment]
It is once again up to date.

**Pull request merged**
