### PR TITLE
darwin: wxmac: add needed inputs

### PR DESCRIPTION
**Pull request by datakurre**

### CODE REVIEW

**Comment by vcunat** [comment]
I wonder how it's happened that so many darwin fixes are suddenly done/needed.

**Comment by datakurre** [comment]
@vcunat New (pure) darwin stdenv was made default a couple of weeks ago, and requires changes to many darwin builds. (And the whole Darwin world would have been broken anyways because of some issues with Nix and the latest XCode.) @pikajude has been leading the new stdenv development lately and knows the details.

**Comment by datakurre** [comment]
@vcunat The cool thing is that also hydra is now building darwin binaries (using the new darwin sandbox in Nix >= 1.9 [with a lot of fixes in 1.11]).

**Comment by vcunat** [comment]
Thanks for explanation. Hopefully the improved purity will mean there will be less such breakages with future OS X updates :-)

**Comment by datakurre** [comment]
Fixed in master.

**Pull request closed without merging**
