### PR TITLE
hubstaff: 1.4.5 -> 1.4.6

### PR DESCRIPTION
**Pull request by srghma**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
Thanks @srghma

**Comment by srghma** [comment]
@worldofpeace np

I have a question: is there some bot that monitors nixpkgs and could periodically find and run the `update.sh` scripts, and if script changes some file in repo - make pr (like revision.json in case of hubstaff). Where could I submit such proposal?

**Comment by worldofpeace** [comment]
> @worldofpeace np
> 
> I have a question: is there some bot that monitors nixpkgs and could periodically find and run the `update.sh` scripts, and if script changes some file in repo - make pr (like revision.json in case of hubstaff). Where could I submit such proposal?

This has been sort of discussed in https://github.com/NixOS/nixpkgs/issues/50665#issuecomment-439776956 https://github.com/NixOS/nixpkgs/issues/50665#issuecomment-440135204.
Currently we have [nixpkgs-update](https://github.com/ryantm/nixpkgs-update#introduction) which essentially submits update prs based of data provided by repology. However I'm not sure if it supports how this expression uses `revision.json`.

So currently that might be a feature in nixpkgs-update's roadmap.

**Comment by Ma27** [comment]
Not sure if that's a good idea, but the best shot for now would be to ask here: https://github.com/ryantm/nixpkgs-update/ (this is the software behind @r-ryantm that periodically updates a large set of our packages based on repology)

**Comment by srghma** [comment]
made an issue https://github.com/ryantm/nixpkgs-update/issues/117

**Pull request merged**
