### PR TITLE
nextcloud-client: fix dbus service location

### PR DESCRIPTION
**Pull request by kleifgch**
I see no reason, why this service file would be placed in a location where dbus does not expect it.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kleifgch** [comment]
@Ma27 you seem to have written the original patch.
Maybe you can tell me if I missed something.

**Comment by lucasew** [comment]
Isn't this a no-op? Isn't the build system using the value provided by pkg-config? If this solves the issue, did you try to upstream the patch?

**Comment by lucasew** [comment]
I answered my two questions by simply building the package on master.

The issue is there.

**Comment by lucasew** [comment]
Upstream changed a little this logic. Probably it will be solved in the next bump.

I didn't know one could pass a variable to override a value in pkg-config tho

https://github.com/nextcloud/desktop/blob/ef1d2a34cc0bbc6e5c7631648c89c6665c9e6fc0/shell_integration/libcloudproviders/CMakeLists.txt#L3

**Comment by lucasew** [comment]
Latest version rn is 3.15.2 tho

**Comment by kleifgch** [comment]
Thanks for your comments!
I did not previously think about that change in upstream, but you're right that it is relevant.
That change is 8 months old and has landed well before the 3.14.3 that is currently in nixpkgs.
That has not fixed the problem yet, because the applied path explicitly overrides that again.
I just tried removing the patch entirely and the service indeed gets installed correctly now,
so this is probably the best solution.

**Comment by kleifgch** [comment]
@lucasew Would you mind taking another look?

**Comment by lucasew** [comment]
I'm cherry-picking this to my branch to test

I'm updating the package, I hope it doesn't conflict. If the stuff is in services instead of service then LGTM.

https://github.com/NixOS/nixpkgs/pull/368914

**Comment by lucasew** [comment]
For context:
- This package is emiting the dbus services into `$out/share/dbus-1/service`
- It should emit into `$out/share/dbus-1/services` as you can check in `/run/current-system/sw`

**Comment by lucasew** [comment]
image

Nice

**Review by GaetanLepage — APPROVED** [review]
Diff LGTM ^^

**Review by lucasew — APPROVED** [review]

**Comment by Ma27** [comment]
> @Ma27 you seem to have written the original patch.
> Maybe you can tell me if I missed something.

FTR I don't even remember that I wrote this patch, so I assume it was a mistake on my end.
Thank you for cleaning this up.

**Pull request merged**
