### PR TITLE
apple-source-releases: always use python3Minimal

### PR DESCRIPTION
**Pull request by reckenrode**
## Description of changes

Using python3Minimal avoids infinite recursions in the stdenv bootstrap on x86_64-darwin when building Python with configd support.

Build was tested on my ld64 branch. Primary issue is ensuring evaluation, which can be tested with `nix-instantiate`.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by reckenrode** [comment]
The force push uses `buildPackages.python3Minimal`, which is needed for Darwin cross-compilation.

**Comment by toonn** [comment]
This was previously achieved by passing in python3Minimal from the bootstrap, no? What's the motivation for changing it around? In principle it's nice for the packages in the final package set to all depend on the same Python rather than have some depend on the minimal version.

**Comment by reckenrode** [comment]
> This was previously achieved by passing in python3Minimal from the bootstrap, no? What's the motivation for changing it around? In principle it's nice for the packages in the final package set to all depend on the same Python rather than have some depend on the minimal version.

Meson needs a fairly functional Python, and it simplifies things not having to do a ton of overrides to do enable that. Otherwise, I’d have to be doing overrides of configd, xnu, etc to use python3Minimal.

**Comment by toonn** [comment]
I'm actually fine with overriding it for all the source releases rather than the ones that strictly need it but it would be slightly nicer not to end up with pretty much always needing two copies of Python in the store.

Would it be hard to switch to non-minimal Python after bootstrapping?

**Comment by reckenrode** [comment]
> I'm actually fine with overriding it for all the source releases rather than the ones that strictly need it but it would be slightly nicer not to end up with pretty much always needing two copies of Python in the store.

Wouldn’t it only be pulled into the store as a build-time dependency?

> Would it be hard to switch to non-minimal Python after bootstrapping?

The way the source releases are implemented in `darwin-packages.nix` doesn’t expose a way to override Python for all of the packages. They’re only exposed individually. It may be something to consider for the SDK refactor. There’s going to need to be a way to override the source-release packages in bulk anyway. Maybe the bootstrap could reuse that.

**Review by toonn — APPROVED** [review]
LGTM, tested a couple things still build fine on both Darwins.

Not my favorite solution but it shouldn't be blocked on my account if it'll allow further progress.

**Pull request merged**
