### PR TITLE
btcpayserver: 1.0.6.8 -> 1.0.7.0

### PR DESCRIPTION
**Pull request by nixbitcoin**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

The package builds and passes the nix-bitcoin VM test suite.
You can run the tests with [this self-contained script](https://gist.github.com/nixbitcoin/35e3359e98b72e843d539551286c4909).

@erikarvstedt

### CODE REVIEW

**Review by erikarvstedt — APPROVED** [review]
Things tested:
- `pkgs/applications/blockchains/nbxplorer./update.sh` and
   `pkgs/applications/blockchains/btcpayserver/update.sh` produce the same content as this PR.
- The package builds and the nix-bitcoin VM test succeeds.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 115954` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>btcpayserver</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
btcpayserver:
<details>


warning: unused-argument
Unused argument: `writeScript`.
Near pkgs/applications/blockchains/btcpayserver/default.nix:2:39:

```
  |
2 |   dotnetPackages, dotnetCorePackages, writeScript, bash
  |                                       ^
```
warning: unused-argument
Unused argument: `bash`.
Near pkgs/applications/blockchains/btcpayserver/default.nix:2:52:

```
  |
2 |   dotnetPackages, dotnetCorePackages, writeScript, bash
  |                                                    ^
```
</details>
</details>

**Review by erikarvstedt — CHANGES_REQUESTED** [review]
See https://github.com/NixOS/nixpkgs/pull/115954#issuecomment-797095607

**Comment by nixbitcoin** [comment]
> See [#115954 (comment)](https://github.com/NixOS/nixpkgs/pull/115954#issuecomment-797095607)

Fixed

**Review by erikarvstedt — APPROVED** [review]

**Comment by nixbitcoin** [comment]
@jonringer can we merge?

**Comment by jonringer** [comment]
do you mind squashing the two commits? otherwise LGTM

**Comment by nixbitcoin** [comment]
> do you mind squashing the two commits? otherwise LGTM

Squashed

**Review by erikarvstedt — APPROVED** [review]

**Pull request merged**
