### PR TITLE
yarn: 1.15.2 -> 1.16.0

### PR DESCRIPTION
**Pull request by ghost**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ma27** [comment]
Built and tested locally :+1:
As several packages depend on `yarn`, I'll run a `nix-review` to search for possible regressions, after that this can be merged :)

**Comment by BenBals** [comment]
##### Reviewed points

- [x] package build on Linux nixos-beb 4.19.37 #1-NixOS SMP Sat Apr 27 07:36:41 UTC 2019 x86_64 GNU/Linux
- [x] executables tested on Linux nixos-beb 4.19.37 #1-NixOS SMP Sat Apr 27 07:36:41 UTC 2019 x86_64 GNU/Linux

##### Possible improvements

##### Comments
All test projects I have handy build fine with this.

**Comment by Ma27** [comment]
Ok so in fact the only package that affected by this is `riot-desktop` according to `nix-review`. I thought that would be more, sorry :sweat_smile:

**Comment by Ma27** [comment]
@petabyteboy thanks!

**Pull request merged**
