### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by domenkozar** [comment]
@FRidh would be great to include latest staging with Big Sur support that was merged 14h ago.

**Comment by FRidh** [comment]
> @FRidh would be great to include latest staging with Big Sur support that was merged 14h ago.

I merged #98541 into here, which should not cause any additional Linux rebuilds.

**Comment by domenkozar** [comment]
Thank you 💝

**Comment by FRidh** [comment]
Over half of Darwin is done, merging.

**Comment by tscholak** [comment]
Wonderful, thank you!

**Comment by thefloweringash** [comment]
There's a potential channel blocker from the Darwin merge. I've opened a PR to address it here: https://github.com/NixOS/nixpkgs/pull/104013

**Pull request merged**
