### PR TITLE
eza: 0.18.22 -> 0.18.23

### PR DESCRIPTION
**Pull request by cafkafk**
Signed-off-by: Christina Sørensen <christina@cafkafk.com>

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kirillrdy** [comment]
@cafkafk please consider adding a link to changelog and/or diff to PR and commit message, something like 
3e051ceda2cbab6f4774387f32350eb0b47bd970

**Comment by cafkafk** [comment]
> @cafkafk please consider adding a link to changelog and/or diff to PR and commit message, something like [3e051ce](https://github.com/NixOS/nixpkgs/commit/3e051ceda2cbab6f4774387f32350eb0b47bd970)

https://github.com/eza-community/eza/releases/tag/v0.18.23

**Comment by kirillrdy** [comment]
apologies, as i was not clear enough.

link to Diff and/Or change log should be added to PR description ( so that it's easy to find ), but it also add such link to commit message as per https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions

**Comment by cafkafk** [comment]
> apologies, as i was not clear enough.
> 
> link to Diff and/Or change log should be added to PR description ( so that it's easy to find ), but it also add such link to commit message as per https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions

honestly, I've done this update about every week for nearly a year and usually it just flies right through review, it's a simple update made by `nixpkgs-update`. I know this guideline exists, but doing this would just make a very routine task overly complicated IMO, since you're the first reviewer ever to ask for this.

**Comment by cafkafk** [comment]
ryanbot makes a massive amount of updates every day that get merged without this extra commit information, and no one is bothered one bit, this really is just gunking up our already heavily overloaded review system with unnecessary nitpicking

**Comment by kirillrdy** [comment]
@cafkafk for a project as big as nixpkgs it's hard to maintain consistent quality of contributions, so yes sometimes commits that don't fit guidelines slip through.

I do appreciate your contribution, and don't mean to discourage you from doing so.

Indeed ryan doesn't add diff to commit, even though it should, thanks for pointing this out.

I would also like to point that many people do follow this guideline

`git log |  grep -i changelog`

there is also https://github.com/NixOS/nixpkgs/pull/277450#issuecomment-1874218676

**Comment by cafkafk** [comment]
> I would also like to point that many people do follow this guideline

I'll quote myself from a moment ago in on element

> if you do git log --grep "->" | wc -l and git log --grep "->" | rg -i "changelog" | wc -l you'll find that just 0.59% of version updates has a changelog footer (I know this is a flawed way to measure this, just to a zeroeth approximation)

Also

> I do appreciate your contribution, and don't mean to discourage you from doing so.

I assume as much, and assume this is in good faith, and I'm sure it could be valuable to add this, and I will strongly consider doing so. I also think it would be a good idea to have ryanbot add this automatically, since it already understands the `lib.meta.changelog` field. 

My point is more that this doesn't meerly "slip through" but is a generally *de facto* accepted practice to ignore in most cases, and that if this is something important to you or other people, it would make more sense to actually enforce this globally, e.g. with a ci check.

I feel like having it be this arbitrary makes is just like when it was normal for style nitpicking (which I did plenty of myself back then) was common practice. Tools like nixfmt solve this way better than uneven standars IMO.

**Comment by cafkafk** [comment]
Anyways, the review has been addressed and commit message has been added, this is ready to be merged

**Comment by Scrumplex** [comment]
Result of `nixpkgs-review pr 329861` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>eza</li>
    <li>eza.man</li>
  </ul>
</details>

**Review by Scrumplex — APPROVED** [review]

**Review by kirillrdy — APPROVED** [review]

**Pull request merged**
