### PR TITLE
nixos/xserver: auto-enable preferred display managers for DE's

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
When Gnome 3 is enabled we should use GDM over lightdm,
and similarly for Plasma5 we should be using SDDM.
This doesn't change the default of lightdm, however
if someone were to enable multiple desktops the previous rules
for Gnome and Plasma don't apply, and lightdm is used.

Really a follow for what we wanted in #48080

###### Todo's
This is opened as a draft because I get an infinite recursion and I'm not sure why.

- [ ] Add release note describing change
- [ ] Actually test the thing

In all situations the user defined display-manager should be used.

###### Further motivations
I've actually opened this in the hopes of very soon not using slim as a display-manager
in the installer ISO.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by worldofpeace** [comment]
cc @Infinisil, maybe you could suggest what's up with the infinite recursion?
Trace isn't helpful. 
(or maybe I've overlooked something in a drowsy state).

**Comment by Lassulus** [comment]
I guess the problem is that setting the value of `services.xserver.displayManager.gdm.enable` in line 583 on the condition if `gdm.enable` in line 157. similiar problems arise for lightdm and sddm.
You can see in the diff, that the old value didn't depend on lightdm being set, because this would also lead to an infinite recursion.

**Comment by worldofpeace** [comment]
> Maybe a solution would be an option like ...xserver.displayManager.activated = "lightdm"; because there can only be a single displayManager enabled anyway?

Right, how about we introduce a `xserver.displayManager.default` pretty much the same as `desktopManager.default`. Not sure I didn't do this initially, it would be a lot simpler.
This would also be a chance to improve another thing, you can actually enable multiple display managers, and it will fail with an error like `displayManager.job.execCmd` being defined multiple times.
Definitely not user friendly.

**Comment by Lassulus** [comment]
`xserver.displayManager.default` could be working, if its already working for desktopManager. although we have weird bugs there with xterm being enabled even though if another desktopManager was specified

**Comment by Lassulus** [comment]
this seems to be stale for a long time. if you still care about this you are free to reopen again :)

**Pull request closed without merging**
