### PR TITLE
python312Packages.icalendar: 5.0.13 -> 6.0.0

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
Diff: https://github.com/collective/icalendar/compare/refs/tags/v5.0.13...v6.0.0

Changelog: https://github.com/collective/icalendar/blob/v6.0.0/CHANGES.rst

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by dotlambda** [comment]
This breaks xandikos until https://github.com/jelmer/xandikos/issues/351 is fixed
cc @0x4A6F @schnusch

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 328227` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>syncall</li>
    <li>syncall.dist</li>
  </ul>
</details>
<details>
  <summary>9 packages failed to build:</summary>
  <ul>
    <li>autosuspend</li>
    <li>autosuspend.dist</li>
    <li>home-assistant-custom-components.waste_collection_schedule</li>
    <li>khal</li>
    <li>khal.dist</li>
    <li>python311Packages.icalevents</li>
    <li>python311Packages.icalevents.dist</li>
    <li>python312Packages.icalevents</li>
    <li>python312Packages.icalevents.dist</li>
  </ul>
</details>
<details>
  <summary>40 packages built:</summary>
  <ul>
    <li>calendar-cli</li>
    <li>calendar-cli.dist</li>
    <li>confy</li>
    <li>errands</li>
    <li>gtg</li>
    <li>home-assistant-component-tests.caldav</li>
    <li>ical2orgpy</li>
    <li>ical2orgpy.dist</li>
    <li>mutt-ics</li>
    <li>mutt-ics.dist</li>
    <li>python311Packages.caldav</li>
    <li>python311Packages.caldav.dist</li>
    <li>python311Packages.django-scheduler</li>
    <li>python311Packages.django-scheduler.dist</li>
    <li>python311Packages.icalendar</li>
    <li>python311Packages.icalendar.dist</li>
    <li>python311Packages.recurring-ical-events</li>
    <li>python311Packages.recurring-ical-events.dist</li>
    <li>python311Packages.x-wr-timezone</li>
    <li>python311Packages.x-wr-timezone.dist</li>
    <li>python312Packages.caldav</li>
    <li>python312Packages.caldav.dist</li>
    <li>python312Packages.django-scheduler</li>
    <li>python312Packages.django-scheduler.dist</li>
    <li>python312Packages.icalendar</li>
    <li>python312Packages.icalendar.dist</li>
    <li>python312Packages.recurring-ical-events</li>
    <li>python312Packages.recurring-ical-events.dist</li>
    <li>python312Packages.x-wr-timezone</li>
    <li>python312Packages.x-wr-timezone.dist</li>
    <li>tandoor-recipes</li>
    <li>timeline</li>
    <li>todoman</li>
    <li>todoman.dist</li>
    <li>topydo</li>
    <li>topydo.dist</li>
    <li>xandikos</li>
    <li>xandikos.dist</li>
    <li>yokadi</li>
    <li>yokadi.dist</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
Packages that need fixing

- [ ] autosuspend (@bzizou @anthonyroussel) https://github.com/languitar/autosuspend/issues/570
- [x] icalevents (@JamieMagee) https://github.com/jazzband/icalevents/pull/145
- [ ] khal (@gebner) https://github.com/pimutils/khal/issues/1361
- [x] todoman (@leenaars @antonmosich) https://github.com/pimutils/todoman/pull/563
- [x] xandikos (@0x4A6F) https://github.com/jelmer/xandikos/pull/352

**Comment by JamieMagee** [comment]
Result of `nixpkgs-review pr 328227` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>syncall</li>
    <li>syncall.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>autosuspend</li>
    <li>autosuspend.dist</li>
    <li>khal</li>
    <li>khal.dist</li>
  </ul>
</details>
<details>
  <summary>45 packages built:</summary>
  <ul>
    <li>calendar-cli</li>
    <li>calendar-cli.dist</li>
    <li>confy</li>
    <li>errands</li>
    <li>gtg</li>
    <li>home-assistant-component-tests.caldav</li>
    <li>home-assistant-custom-components.waste_collection_schedule</li>
    <li>ical2orgpy</li>
    <li>ical2orgpy.dist</li>
    <li>mutt-ics</li>
    <li>mutt-ics.dist</li>
    <li>python311Packages.caldav</li>
    <li>python311Packages.caldav.dist</li>
    <li>python311Packages.django-scheduler</li>
    <li>python311Packages.django-scheduler.dist</li>
    <li>python311Packages.icalendar</li>
    <li>python311Packages.icalendar.dist</li>
    <li>python311Packages.icalevents</li>
    <li>python311Packages.icalevents.dist</li>
    <li>python311Packages.recurring-ical-events</li>
    <li>python311Packages.recurring-ical-events.dist</li>
    <li>python311Packages.x-wr-timezone</li>
    <li>python311Packages.x-wr-timezone.dist</li>
    <li>python312Packages.caldav</li>
    <li>python312Packages.caldav.dist</li>
    <li>python312Packages.django-scheduler</li>
    <li>python312Packages.django-scheduler.dist</li>
    <li>python312Packages.icalendar</li>
    <li>python312Packages.icalendar.dist</li>
    <li>python312Packages.icalevents</li>
    <li>python312Packages.icalevents.dist</li>
    <li>python312Packages.recurring-ical-events</li>
    <li>python312Packages.recurring-ical-events.dist</li>
    <li>python312Packages.x-wr-timezone</li>
    <li>python312Packages.x-wr-timezone.dist</li>
    <li>tandoor-recipes</li>
    <li>timeline</li>
    <li>todoman</li>
    <li>todoman.dist</li>
    <li>topydo</li>
    <li>topydo.dist</li>
    <li>xandikos</li>
    <li>xandikos.dist</li>
    <li>yokadi</li>
    <li>yokadi.dist</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 328227` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>syncall</li>
    <li>syncall.dist</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>tandoor-recipes</li>
  </ul>
</details>
<details>
  <summary>48 packages built:</summary>
  <ul>
    <li>autosuspend</li>
    <li>autosuspend.dist</li>
    <li>calendar-cli</li>
    <li>calendar-cli.dist</li>
    <li>confy</li>
    <li>errands</li>
    <li>gtg</li>
    <li>home-assistant-component-tests.caldav</li>
    <li>home-assistant-custom-components.waste_collection_schedule</li>
    <li>ical2orgpy</li>
    <li>ical2orgpy.dist</li>
    <li>khal</li>
    <li>khal.dist</li>
    <li>mutt-ics</li>
    <li>mutt-ics.dist</li>
    <li>python311Packages.caldav</li>
    <li>python311Packages.caldav.dist</li>
    <li>python311Packages.django-scheduler</li>
    <li>python311Packages.django-scheduler.dist</li>
    <li>python311Packages.icalendar</li>
    <li>python311Packages.icalendar.dist</li>
    <li>python311Packages.icalevents</li>
    <li>python311Packages.icalevents.dist</li>
    <li>python311Packages.recurring-ical-events</li>
    <li>python311Packages.recurring-ical-events.dist</li>
    <li>python311Packages.x-wr-timezone</li>
    <li>python311Packages.x-wr-timezone.dist</li>
    <li>python312Packages.caldav</li>
    <li>python312Packages.caldav.dist</li>
    <li>python312Packages.django-scheduler</li>
    <li>python312Packages.django-scheduler.dist</li>
    <li>python312Packages.icalendar</li>
    <li>python312Packages.icalendar.dist</li>
    <li>python312Packages.icalevents</li>
    <li>python312Packages.icalevents.dist</li>
    <li>python312Packages.recurring-ical-events</li>
    <li>python312Packages.recurring-ical-events.dist</li>
    <li>python312Packages.x-wr-timezone</li>
    <li>python312Packages.x-wr-timezone.dist</li>
    <li>timeline</li>
    <li>todoman</li>
    <li>todoman.dist</li>
    <li>topydo</li>
    <li>topydo.dist</li>
    <li>xandikos</li>
    <li>xandikos.dist</li>
    <li>yokadi</li>
    <li>yokadi.dist</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
> 1 package failed to build

That will be fixed by https://github.com/NixOS/nixpkgs/pull/348408.

**Pull request merged**
