### PR TITLE
webcord: lock ozone wayland behind NIXOS_OZONE_WL envvar

### PR DESCRIPTION
**Pull request by eclairevoyant**
## Description of changes

Locks Ozone Wayland behind `NIXOS_OZONE_WL` envvar, as per the behaviour prior to #259899.

There are multiple reasons to do so:

* Ozone Wayland is not production-ready, which is the whole purpose of the envvar in the first place on NixOS. Broken solutions should be opt-in, not opt-out.
* Using Ozone Wayland breaks IMEs; this is a known issue [reported to Chromium in 2021](https://bugs.chromium.org/p/chromium/issues/detail?id=1183262), and as of [yet](https://bugs.chromium.org/p/chromium/issues/detail?id=1237456) [unfixed](https://bugs.chromium.org/p/chromium/issues/detail?id=1315264) - in other words, using Ozone Wayland is not viable for any users who use IMEs to type.
  * There are other hacky solutions such as passing `--gtk-version=4`, but this is only supported in Chromium (**not** Electron), and breaks file dialogs even in Chromium itself.
  * `--enable-wayland-ime` is not viable either, as the associated wl input protocol (`zwp_text_input_v1`) is only supported by some compositors, while others only support v3 and [the flag does nothing](https://bugs.chromium.org/p/chromium/issues/detail?id=1039161). [More background here](https://nimfsoft.art/blog/the-reality-of-wayland-input-methods-in-2022/).
* Ozone Wayland does not work well in many GPU configurations.
* Webcord should not be the only package using a different pattern compared to every other Electron app. See the results of `rg 'ozone-platform-hint=auto'` in the nixpkgs repo below:

<details>

```
pkgs/games/heroic/default.nix
98:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations --enable-wayland-ime}}"

pkgs/games/lunar-client/default.nix
25:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}"

pkgs/games/r2modman/default.nix
89:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}"

pkgs/tools/security/bitwarden/default.nix
140:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}" \

pkgs/by-name/ve/vesktop/package.nix
113:        --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}"

pkgs/applications/misc/1password-gui/linux.nix
139:      #--add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}"

pkgs/applications/misc/whalebird/default.nix
87:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}"

pkgs/applications/misc/kuro/default.nix
60:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}" \

pkgs/applications/misc/passky-desktop/default.nix
40:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}"

pkgs/applications/misc/todoist-electron/default.nix
42:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}"

pkgs/applications/misc/logseq/default.nix
63:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}" \

pkgs/applications/misc/anytype/default.nix
25:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}"

pkgs/applications/graphics/drawio/default.nix
75:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}" \

pkgs/development/tools/redisinsight/default.nix
129:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}" \

pkgs/development/tools/altair-graphql-client/default.nix
22:        --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}"

pkgs/applications/editors/vscode/generic.nix
211:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}"

pkgs/applications/virtualization/podman-desktop/default.nix
92:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}" \

pkgs/applications/audio/youtube-music/default.nix
62:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}" \

pkgs/applications/audio/tidal-hifi/default.nix
108:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}" \

pkgs/applications/office/micropad/default.nix
69:        --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}"

pkgs/applications/networking/cluster/lens/linux.nix
23:        --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}"

pkgs/applications/networking/instant-messengers/slack/default.nix
177:        --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations,WebRTCPipeWireCapturer}}"

pkgs/applications/networking/instant-messengers/feishu/default.nix
171:        --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}" \

pkgs/applications/networking/instant-messengers/qq/default.nix
97:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}"

pkgs/applications/networking/instant-messengers/session-desktop/default.nix
53:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}"

pkgs/applications/networking/instant-messengers/schildichat/schildichat-desktop.nix
100:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}"

pkgs/applications/networking/instant-messengers/element/element-desktop.nix
108:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}"

pkgs/applications/networking/instant-messengers/zulip/default.nix
23:  runScript = "appimage-exec.sh -w ${appimageContents} -- \${NIXOS_OZONE_WL:+\${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}";

pkgs/applications/networking/instant-messengers/teams-for-linux/default.nix
81:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}"

pkgs/applications/networking/instant-messengers/signal-desktop/generic.nix
155:      #--add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}"

pkgs/applications/networking/instant-messengers/webcord/default.nix
65:      --add-flags "--ozone-platform-hint=auto" \

pkgs/applications/networking/instant-messengers/jitsi-meet-electron/default.nix
50:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}"

pkgs/applications/networking/instant-messengers/beeper/default.nix
52:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}} --no-update"

pkgs/applications/networking/browsers/google-chrome/default.nix
149:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}" \

pkgs/applications/networking/browsers/brave/default.nix
182:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}"

pkgs/applications/networking/browsers/vivaldi/default.nix
113:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}" \

pkgs/applications/networking/browsers/chromium/default.nix
196:      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}" \
```

</details>

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by NotAShelf — APPROVED** [review]
makes sense, looks good

**Review by huantianad — APPROVED** [review]
Wondering if maybe @NotAShelf and @FlafyDev should also be added to the main webcord's meta maintainers since they're getting mentioned each time anyway

**Comment by eclairevoyant** [comment]
I'd leave it up to them if they want to be considered as maintainers. Not sure how borgo adds reviewers though

**Review by lilyinstarlight — APPROVED** [review]

**Comment by C0rn3j** [comment]
IME support is tracked here https://github.com/electron/electron/issues/33662

**Comment by eclairevoyant** [comment]
@C0rn3j not really, the patch needs to go to chromium, and there's the -v1 vs -v3 distinction...

**Pull request merged**
