### PR TITLE
grpc: add coments about updating related python packages for compatibility

### PR DESCRIPTION
**Pull request by rorosen**
`grpc` should always be updated together with related python packages to ensure compatibility. Mismatched versions have led to incompatibilities in the past: https://github.com/NixOS/nixpkgs/pull/338875

## Things done

- Extend the comment about related python packages
- Disable auto updates for grpc and related python packages

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by matdibu** [comment]
thank you!

**Review by matdibu — APPROVED** [review]

**Review by nikstur — APPROVED** [review]

**Comment by scraptux** [comment]
I would suggest, actually upgrading all grpc python packages at once.


So the additional packages not mentioned in the comment (including your commit) would be:

- pythonPackages.grpcio-testing
- pythonPackages.grpcio-channelz
- pythonPackages.grpcio-reflection
- pythonPackages.grpcio-health-checking


Its probably also a good idea to add 'noupdate' to these packages so that r-ryantm doesn't update them individually.

**Comment by rorosen** [comment]
> I would suggest, actually upgrading all grpc python packages at once.

Sounds like a wise thing to do. I added the python packages you mentioned to the comment and disabled auto updates for them as well as the main grpc package. Looking at the logs, r-ryantm cannot update it ultimately anyway  (e.g. [here](https://r.ryantm.com/log/grpc/2024-10-05.log)).

**Review by scraptux — APPROVED** [review]
Looks good! Thanks for making the changes!

**Comment by rorosen** [comment]
I decided to add a test that checks whether the related python packages have the same version as grpc. The test will fail with an error message, if any version doesn't match

```
error: builder for '/nix/store/qcwpwsk0arvszv23b9yg72b5kzv7gil8-check-grpc-versions.drv' failed with exit code 1;
       last 2 log lines:
       > Version of package python3.12-grpcio-1.64.1 does not match this grpc version (1.66.1)
       > Please ensure that all related packages have the same version
       For full logs, run 'nix log /nix/store/qcwpwsk0arvszv23b9yg72b5kzv7gil8-check-grpc-versions.drv'.
```

The test will obviously fail currently, but should pass once all packages have the same version and will help to prevent incompatibilities in the future. I don't feel to good to merge a failing test but I think it makes sense in this context. Let me know if you have concerns.

**Comment by scraptux** [comment]
> The test will obviously fail currently, but should pass once all packages have the same version and will help to prevent incompatibilities in the future. I don't feel to good about merging a failing test but I think it makes sense in this context. Let me know if you have concerns.

Great idea! I believe merging now should not be a problem. Since the latest version is 1.66.2 now anyways, I think we should create a PR updating all packages once this one is merged.

**Review by scraptux — APPROVED** [review]

**Review by nikstur — APPROVED** [review]

**Comment by scraptux** [comment]
PR title needs to be adjusted, looks good otherwise!

**Pull request merged**
