### PR TITLE
incus: 6.2.0 -> 6.3.0

### PR DESCRIPTION
**Pull request by bbigras**
## Description of changes

- `skopeo`, `umoci` and `readlink` are needed to use OCI containers.

```
lxc mydocker 20240715032412.339 DEBUG    utils - ../src/lxc/utils.c:run_buffer:560 - Script exec /nix/store/cfwa9a0aiv9h5mlw8k5zj3jv0ak0cir6-lxcfs-6.0.1/share/lxcfs/lxc.mount.hook produced output: /nix/store/cfwa9a0aiv9h5mlw8k5zj3jv0ak0cir6-lxcfs-6.0.1/share/lxcfs/.lxc.mount.hook-wrapped: line 15: readlink: command not found
```

`incus launch docker:nginx mynginx --console --ephemeral`

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by bbigras** [comment]
Note that I'm not able to use oci containers yet.

https://discuss.linuxcontainers.org/t/incus-cant-find-docker-hello-world/21028

**Comment by adamcstephens** [comment]
@ofborg build incus incus.passthru.tests

**Comment by bbigras** [comment]
```sh
❯ incus launch docker:nginx mynginx --ephemeral
Launching mynginx

❯ xh 10.0.100.3
HTTP/1.1 200 OK
Accept-Ranges: bytes
Connection: keep-alive
Content-Length: 615
Content-Type: text/html
Date: Mon, 15 Jul 2024 03:49:06 GMT
Etag: "6655da96-267"
Last-Modified: Tue, 28 May 2024 13:22:30 GMT
Server: nginx/1.27.0

<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
```

**Comment by adamcstephens** [comment]
This file was added, and the logic around edk2 firmware detection changed, breaking our virtual machine support. You can see this by building `incus.passthru.tests.virtual-machine`. Until resolved, I'm marking this as a draft.

 https://github.com/lxc/incus/blob/v6.3.0/internal/server/instance/drivers/edk2/driver_edk2.go

**Comment by bbigras** [comment]
@ofborg build incus incus.passthru.tests

**Comment by adamcstephens** [comment]
x86
/nix/store/kaq863r4lk3jkx8gzssmhniwvk1zh4g6-vm-test-run-container-legacy-init
/nix/store/phhfd2z80y5l6x0w82zqjrgx63fsmfrd-vm-test-run-container-systemd-init
/nix/store/00lawiypacd3bzpicj10hfydvl1b72mg-vm-test-run-incusd-options
/nix/store/i0pic42188mrnfn03k3d955d4j8hgqbb-vm-test-run-lxd-to-incus
/nix/store/hk6rwaxrwx48vy65i0v5v6bbb9ky7v1b-vm-test-run-incus-openvswitch
/nix/store/909jqv74ry0zhlpjhd10j2sr5k79mgdr-vm-test-run-incus-socket-activated
/nix/store/w0ff1hpczbks2053791bm34fkxi7rh8v-vm-test-run-incus-storage
/nix/store/lrpv9qm31pfjfb3az9j4mv541l8g08j8-vm-test-run-incus-ui
/nix/store/6nd620v099d3w5xvk5bij1xzfz9924s3-vm-test-run-incus-virtual-machine

aarch64
/nix/store/mvjzd0r9sb8wndydlmmhl73wm8daahwj-vm-test-run-container-legacy-init
/nix/store/sds83pm4b24ybmnl3ic8gfkwl03bb188-vm-test-run-container-systemd-init
/nix/store/w7gkilsysnrdxnwin69kicpa9s9p8vr0-vm-test-run-incusd-options
/nix/store/41r861fbqr4z6b9r95l48gkaynzll1rs-vm-test-run-lxd-to-incus
/nix/store/rpwabc9jfacqz8fxg9p1rl2fsvmmbixk-vm-test-run-incus-openvswitch
/nix/store/dh935nnxwr3v4q8p76sx5z4hrd681cs1-vm-test-run-incus-socket-activated
/nix/store/azh21vld405hkvvjlika7fg2j2514pa4-vm-test-run-incus-storage
/nix/store/rh8m8pmvwqn5q0v5bl06xnd91997yiiy-vm-test-run-incus-ui

**Review by adamcstephens — APPROVED** [review]

**Review by megheaiulian — APPROVED** [review]

**Comment by bbigras** [comment]
Thanks everyone!

**Pull request merged**
