### PR TITLE
VLC wants a newer version of libdvdnav

### PR DESCRIPTION
**Pull request by pjones**
- Updated libdvdnav/libdvdread to latest versions
- Removed libdvdnav patches since they have been incorporated into the
  latest release
- Added `--enable-dvdnav` configure flag to VLC to ensure that if this
  happens again VLC will fail to build

### CODE REVIEW

**Comment by peti** [comment]
This change breaks `mplayer`: http://hydra.cryp.to/build/635252/nixlog/5/raw

**Comment by pjones** [comment]
I'll upgrade mplayer or patch it.

**Comment by pjones** [comment]
I'm not a mplayer user so I'd like a bit of advice.

The version of mplayer in nixpkgs is 1.1.1, which is a bit old.  The mplayer website recommends using the nightly snapshots, which apparently we used to do.  Are there any downsides to going this route?  If we go to a snapshot and I still have to patch mplayer (for libdvdnav and libdvdread updates), at least it'll be easy to send those patches upstream.

/cc maintainer @edolstra

**Comment by edolstra** [comment]
I can have a look at updating it to the latest SVN snapshot.

**Pull request merged**
