### PR TITLE
pyxel: init at 2.0.7

### LINKED ISSUE #271012: Package request: pyxel
**Project description**

Pyxel is a retro game engine for Python.

**Metadata**

* homepage URL: https://github.com/kitao/pyxel
* source URL: https://github.com/kitao/pyxel
* license: mit
* platforms: unix, linux, darwin

**Priorities**

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by TomaSajt**
## Description of changes

Closes https://github.com/NixOS/nixpkgs/issues/271012
Supersedes https://github.com/NixOS/nixpkgs/pull/275025

This PR adds 1 package: `pyxel`

There is an [earlier pending PR](https://github.com/NixOS/nixpkgs/pull/275025) which also adds this package, which used the prebuilt wheels.
This derivation, however, builds from source, which I think is better inside Nixpkgs.

There are some hacks present, which might need to be fixed in another PR:
- ~`clang` version not overridable in `rustPlatform.bindgenHook`~ (not needed anymore)
  PR: https://github.com/NixOS/nixpkgs/pull/276390)

- ~`maturin` not respecting wheel directory (found a good enough workaround)~ (fixed)

@Sigmanificient, as the author of the original PR, would you like to still help maintain this package?

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by TomaSajt** [comment]
Had to move package from `pkgs/by-name` because derivations here are not allowed to have path literals pointing to outside of the directory.

**Comment by TomaSajt** [comment]
@ofborg build pyxel

**Comment by Sigmanificient** [comment]
Hello, I am open to merging the 2 prs, though we used a quite different approach (you build from github, while I build from Pypi.

What should we do considering this?

**Comment by TomaSajt** [comment]
> Also can you add the supported `platforms` list?
Yeah, sure, though I am still fixing the darwin build at the moment

**Comment by TomaSajt** [comment]
@ofborg build pyxel

**Comment by Sigmanificient** [comment]
> > Also can you add the supported `platforms` list?
> 
> Yeah, sure, though I am still fixing the darwin build at the moment

Well I believe if you do support more platforms than I do and that building from source is a better approach, it would be better to use yours

**Comment by TomaSajt** [comment]
@ofborg build pyxel

**Comment by TomaSajt** [comment]
@ofborg build pyxel

**Comment by TomaSajt** [comment]
@ofborg build pyxel

**Comment by TomaSajt** [comment]
@ofborg build pyxel

**Comment by TomaSajt** [comment]
@ofborg build pyxel

**Comment by TomaSajt** [comment]
@ofborg build pyxel

**Comment by TomaSajt** [comment]
@ofborg build pyxel

**Comment by TomaSajt** [comment]
@ofborg build pyxel

**Comment by TomaSajt** [comment]
@ofborg build pyxel

**Comment by gaykitty** [comment]
Result of `nixpkgs-review pr 276354` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>pyxel</li>
    <li>pyxel.dist</li>
  </ul>
</details>

**Comment by TomaSajt** [comment]
Finally, according to OfBorg, it compiles on darwin.

I just realized I used buildPythonPackage instead of buildPythonApplication

**Comment by TomaSajt** [comment]
And now that all the custom `makeSetupHook` shenanigans have been removed, I could move the files back to `pkgs/by-name`

**Comment by pbsds** [comment]
Result of `nixpkgs-review pr 276354` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>pyxel</li>
    <li>pyxel.dist</li>
  </ul>
</details>

```
pyxel> 📦 Built wheel for abi3 Python ≥ 3.7 to target/wheels/pyxel-2.0.1-cp37-abi3-linux_x86_64.whl
pyxel> mv: missing destination file operand after 'dist/'
pyxel> Try 'mv --help' for more information.
```

**Comment by Sigmanificient** [comment]
Having the working package from binary as a starting point and refactoring it later could be nice. What do you think about this idea?

**Comment by TomaSajt** [comment]
Looks like they have patched the issue I was hacking around
https://github.com/NixOS/nixpkgs/commit/8742c0cd2e872ad371759dbf12b32702253fe355

I think if I remove the hack, it will start building again

**Review by pbsds — APPROVED** [review]
Result of `nixpkgs-review pr 276354` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>pyxel</li>
    <li>pyxel.dist</li>
  </ul>
</details>

**Comment by Sigmanificient** [comment]
Wow that's a old package :O

**Pull request merged**
