### PR TITLE
wineStable: 6.0.2 -> 7.0 / wine{Unstable,Staging}: 7.0-rc6 -> 7.0

### PR DESCRIPTION
**Pull request by SFrijters**
###### Motivation for this change

https://www.winehq.org/announce/7.0

Currently upstream development == staging, but I'm not sure if we want to also put `unstable = stable;` like I did for now, or if we just want to inherit some more attributes.

###### Things done

nixpkgs-review in progress...

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SFrijters** [comment]
Result of `nixpkgs-review pr 155529` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>airwave</li>
  </ul>
</details>
<details>
  <summary>27 packages built:</summary>
  <ul>
    <li>bottles</li>
    <li>grapejuice</li>
    <li>lutris</li>
    <li>lutris-free</li>
    <li>lutris-unwrapped</li>
    <li>pipelight</li>
    <li>playonlinux</li>
    <li>q4wine</li>
    <li>winbox</li>
    <li>wine (winePackages.stableFull ,winePackages.unstableFull)</li>
    <li>wine-staging (winePackages.stagingFull)</li>
    <li>wine64 (wine64Packages.stableFull ,wine64Packages.unstableFull)</li>
    <li>wine64Packages.base (wine64Packages.stable ,wine64Packages.unstable)</li>
    <li>winePackages.fonts (wine64Packages.fonts ,wineWowPackages.fonts)</li>
    <li>wine64Packages.minimal</li>
    <li>wine64Packages.staging</li>
    <li>wine64Packages.stagingFull</li>
    <li>winePackages.base (winePackages.stable ,winePackages.unstable)</li>
    <li>winePackages.minimal</li>
    <li>winePackages.staging</li>
    <li>wineWowPackages.base (wineWowPackages.stable ,wineWowPackages.unstable)</li>
    <li>wineWowPackages.full (wineWowPackages.stableFull ,wineWowPackages.unstableFull)</li>
    <li>wineWowPackages.minimal</li>
    <li>wineWowPackages.staging</li>
    <li>wineWowPackages.stagingFull</li>
    <li>yabridge</li>
    <li>yabridgectl</li>
  </ul>
</details>

**Comment by SFrijters** [comment]
Airwave failure: "Unfortunately, we cannot download file vstsdk368_08_11_2017_build_121.zip automatically.", as usual.

**Comment by fufexan** [comment]
Result of `nixpkgs-review pr 155529` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>lutris</li>
    <li>lutris-free</li>
    <li>lutris-unwrapped</li>
  </ul>
</details>
<details>
  <summary>24 packages built:</summary>
  <ul>
    <li>bottles</li>
    <li>grapejuice</li>
    <li>pipelight</li>
    <li>playonlinux</li>
    <li>q4wine</li>
    <li>winbox</li>
    <li>wine (winePackages.full ,winePackages.stableFull ,winePackages.unstableFull)</li>
    <li>wine-staging (winePackages.stagingFull)</li>
    <li>wine64 (wine64Packages.full ,wine64Packages.stableFull ,wine64Packages.unstableFull)</li>
    <li>wine64Packages.base (wine64Packages.stable ,wine64Packages.unstable)</li>
    <li>winePackages.fonts (wine64Packages.fonts ,wineWowPackages.fonts)</li>
    <li>wine64Packages.minimal</li>
    <li>wine64Packages.staging</li>
    <li>wine64Packages.stagingFull</li>
    <li>winePackages.base (winePackages.stable ,winePackages.unstable)</li>
    <li>winePackages.minimal</li>
    <li>winePackages.staging</li>
    <li>wineWowPackages.base (wineWowPackages.stable ,wineWowPackages.unstable)</li>
    <li>wineWowPackages.full (wineWowPackages.stableFull ,wineWowPackages.unstableFull)</li>
    <li>wineWowPackages.minimal</li>
    <li>wineWowPackages.staging</li>
    <li>wineWowPackages.stagingFull</li>
    <li>yabridge</li>
    <li>yabridgectl</li>
  </ul>
</details>

**Comment by fufexan** [comment]
Ah too late lol

**Comment by SFrijters** [comment]
Do you have any details on the `lutris` failures? I didn't see them in my `nixpkgs-review` run.

**Comment by fufexan** [comment]
Hmm, nothing hints at a cause
```
› nixpkgs-review pr 155529 --post-result
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/155529/head:refs/nixpkgs-review/1
remote: Enumerating objects: 4741, done.
remote: Counting objects: 100% (2071/2071), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 4741 (delta 2066), reused 2066 (delta 2066), pack-reused 2670
Receiving objects: 100% (4741/4741), 7.08 MiB | 1.21 MiB/s, done.
Resolving deltas: 100% (3265/3265), completed with 652 local objects.
From https://github.com/NixOS/nixpkgs
   e098427f750..26b9c9800a1  master     -> refs/nixpkgs-review/0
$ git worktree add /home/mihai/.local/cache/nixpkgs-review/pr-155529-1/nixpkgs 26b9c9800a1c570c43801fec2a9aa0f87d1801b3
Preparing worktree (detached HEAD 26b9c9800a1)
Updating files: 100% (29388/29388), done.
HEAD is now at 26b9c9800a1 Merge pull request #153529 from dmacvicar/patch-1
$ git merge --no-commit --no-ff abe5804eff8efae2fcec83f6b1ba9f5ab108d4b7
Already up to date.
$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/mihai/.local/cache/nixpkgs-review/pr-155529-1/build.nix

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/155529

3 packages marked as broken and skipped:
lutris lutris-free lutris-unwrapped

24 packages built:
bottles grapejuice pipelight playonlinux q4wine winbox wine wine-staging wine64 wine64Packages.base winePackages.fonts wine64Packages.minimal wine64Packages.staging wine64Packages.stagingFull winePackages.base winePackages.minimal winePackages.staging wineWowPackages.base wineWowPackages.full wineWowPackages.minimal wineWowPackages.staging wineWowPackages.stagingFull yabridge yabridgectl

Posting result comment on https://github.com/NixOS/nixpkgs/pull/155529
$ nix-shell /home/mihai/.local/cache/nixpkgs-review/pr-155529-1/shell.nix
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/jaa5l5g36aj1wwlmk9lqhslclmdqms3x-bash-interactive-5.1-p12-dev
copying path '/nix/store/jaa5l5g36aj1wwlmk9lqhslclmdqms3x-bash-interactive-5.1-p12-dev' from 'https://cache.nixos.org'...
```

**Pull request merged**
