### PR TITLE
vimPlugins: cleanup

### PR DESCRIPTION
**Pull request by khaneliman**
## Things done

- Cleanup imports
- `--replace` -> `--replace-fail`
- consolidate non generated plugins
- wip

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by lucasewd** [comment]
# [nixpkgs-reviewd](https://github.com/nixosbrasil/nixpkgs-reviewd) workflow started

- **Extra args**: ``
- **Free space**: true
- **Who asked**: lucasew

**TARGETS**
- **x86_64-linux**: true
- **x86_64-darwin**: true
- **aarch64-darwin**: true

**Status and logs**: https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12449901244

**Comment by lucasewd** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 366898`

---
### `aarch64-darwin`
<details>
  <summary>:fast_forward: 2 packages marked as broken and skipped:</summary>
  <ul>
    <li>vimPlugins.stylish-nvim</li>
    <li>vimPlugins.vim-xkbswitch</li>
  </ul>
</details>
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>vimPlugins.vim-wakatime</li>
    <li>vimacs</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 36 packages built:</summary>
  <ul>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.aider-nvim</li>
    <li>vimPlugins.clang_complete</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.command-t</li>
    <li>vimPlugins.copilot-vim</li>
    <li>vimPlugins.ddc-filter-matcher_head</li>
    <li>vimPlugins.ddc-filter-sorter_rank</li>
    <li>vimPlugins.ddc-source-lsp</li>
    <li>vimPlugins.ddc-ui-native</li>
    <li>vimPlugins.ddc-ui-pum</li>
    <li>vimPlugins.ddc-vim</li>
    <li>vimPlugins.denops-vim</li>
    <li>vimPlugins.diagram-nvim</li>
    <li>vimPlugins.direnv-vim</li>
    <li>vimPlugins.fruzzy</li>
    <li>vimPlugins.image-nvim</li>
    <li>vimPlugins.kulala-nvim</li>
    <li>vimPlugins.minimap-vim</li>
    <li>vimPlugins.nvim-teal-maker</li>
    <li>vimPlugins.phpactor</li>
    <li>vimPlugins.ranger-nvim</li>
    <li>vimPlugins.statix</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.tsc-nvim</li>
    <li>vimPlugins.vim-agda</li>
    <li>vimPlugins.vim-dasht</li>
    <li>vimPlugins.vim-isort</li>
    <li>vimPlugins.vim-pluto</li>
    <li>vimPlugins.vim-stylish-haskell</li>
    <li>vimPlugins.vim-yapf</li>
    <li>vimPlugins.vimacs</li>
    <li>vimPlugins.vimproc-vim</li>
    <li>vimPlugins.vimshell-vim</li>
    <li>vimPlugins.zoxide-vim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Comment by lucasewd** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 366898`

---
### `x86_64-linux`
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>vimPlugins.vim-wakatime</li>
    <li>vimPlugins.vim-xkbswitch</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 38 packages built:</summary>
  <ul>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.aider-nvim</li>
    <li>vimPlugins.clang_complete</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.command-t</li>
    <li>vimPlugins.copilot-vim</li>
    <li>vimPlugins.ddc-filter-matcher_head</li>
    <li>vimPlugins.ddc-filter-sorter_rank</li>
    <li>vimPlugins.ddc-source-lsp</li>
    <li>vimPlugins.ddc-ui-native</li>
    <li>vimPlugins.ddc-ui-pum</li>
    <li>vimPlugins.ddc-vim</li>
    <li>vimPlugins.denops-vim</li>
    <li>vimPlugins.diagram-nvim</li>
    <li>vimPlugins.direnv-vim</li>
    <li>vimPlugins.fruzzy</li>
    <li>vimPlugins.image-nvim</li>
    <li>vimPlugins.kulala-nvim</li>
    <li>vimPlugins.minimap-vim</li>
    <li>vimPlugins.nvim-teal-maker</li>
    <li>vimPlugins.phpactor</li>
    <li>vimPlugins.ranger-nvim</li>
    <li>vimPlugins.statix</li>
    <li>vimPlugins.stylish-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.tsc-nvim</li>
    <li>vimPlugins.vim-agda</li>
    <li>vimPlugins.vim-dasht</li>
    <li>vimPlugins.vim-isort</li>
    <li>vimPlugins.vim-pluto</li>
    <li>vimPlugins.vim-stylish-haskell</li>
    <li>vimPlugins.vim-yapf</li>
    <li>vimPlugins.vimacs</li>
    <li>vimPlugins.vimproc-vim</li>
    <li>vimPlugins.vimshell-vim</li>
    <li>vimPlugins.zoxide-vim</li>
    <li>vimPluginsUpdater</li>
    <li>vimacs</li>
  </ul>
</details>

**Comment by lucasewd** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 366898`

---
### `x86_64-darwin`
<details>
  <summary>:fast_forward: 2 packages marked as broken and skipped:</summary>
  <ul>
    <li>vimPlugins.stylish-nvim</li>
    <li>vimPlugins.vim-xkbswitch</li>
  </ul>
</details>
<details>
  <summary>:x: 3 packages failed to build:</summary>
  <ul>
    <li>vimPlugins.aider-nvim</li>
    <li>vimPlugins.vim-wakatime</li>
    <li>vimacs</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 35 packages built:</summary>
  <ul>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.clang_complete</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.command-t</li>
    <li>vimPlugins.copilot-vim</li>
    <li>vimPlugins.ddc-filter-matcher_head</li>
    <li>vimPlugins.ddc-filter-sorter_rank</li>
    <li>vimPlugins.ddc-source-lsp</li>
    <li>vimPlugins.ddc-ui-native</li>
    <li>vimPlugins.ddc-ui-pum</li>
    <li>vimPlugins.ddc-vim</li>
    <li>vimPlugins.denops-vim</li>
    <li>vimPlugins.diagram-nvim</li>
    <li>vimPlugins.direnv-vim</li>
    <li>vimPlugins.fruzzy</li>
    <li>vimPlugins.image-nvim</li>
    <li>vimPlugins.kulala-nvim</li>
    <li>vimPlugins.minimap-vim</li>
    <li>vimPlugins.nvim-teal-maker</li>
    <li>vimPlugins.phpactor</li>
    <li>vimPlugins.ranger-nvim</li>
    <li>vimPlugins.statix</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.tsc-nvim</li>
    <li>vimPlugins.vim-agda</li>
    <li>vimPlugins.vim-dasht</li>
    <li>vimPlugins.vim-isort</li>
    <li>vimPlugins.vim-pluto</li>
    <li>vimPlugins.vim-stylish-haskell</li>
    <li>vimPlugins.vim-yapf</li>
    <li>vimPlugins.vimacs</li>
    <li>vimPlugins.vimproc-vim</li>
    <li>vimPlugins.vimshell-vim</li>
    <li>vimPlugins.zoxide-vim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Comment by khaneliman** [comment]
@GaetanLepage I have more I want to do but I'll break them up into different PRs to not be too much at a time.

**Review by GaetanLepage — APPROVED** [review]
Well done, thanks

**Pull request merged**
