### PR TITLE
joplin-desktop: 2.10.4 -> 2.10.18

### PR DESCRIPTION
**Pull request by mayjs**
###### Description of changes

Changes:
https://github.com/laurent22/joplin/releases/tag/v2.10.6
https://github.com/laurent22/joplin/releases/tag/v2.10.7
https://github.com/laurent22/joplin/releases/tag/v2.10.8
https://github.com/laurent22/joplin/releases/tag/v2.10.9
https://github.com/laurent22/joplin/releases/tag/v2.10.10
https://github.com/laurent22/joplin/releases/tag/v2.10.11
https://github.com/laurent22/joplin/releases/tag/v2.10.12
https://github.com/laurent22/joplin/releases/tag/v2.10.13
https://github.com/laurent22/joplin/releases/tag/v2.10.14
https://github.com/laurent22/joplin/releases/tag/v2.10.15
https://github.com/laurent22/joplin/releases/tag/v2.10.16
https://github.com/laurent22/joplin/releases/tag/v2.10.17
https://github.com/laurent22/joplin/releases/tag/v2.10.18

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by MaxHearnden** [comment]
I recommend you change the hash for darwin from the 32 bit `sha256-18xx1zvzsqb4lc28scpiz45anmgf4mmsdyc2jyl9nbcbr99448c4` to the 64 bit version `sha256-hCFCUsqLLZuol4L5pmsl7lWrCvnxMo0Eo2Rh/fcPvaM=`

You can use `nix hash to-base64 --type sha256 $32_BIT_HASH` to convert to a 64 bit hash

**Comment by mayjs** [comment]
> I recommend you change the hash for darwin from the 32 bit `sha256-18xx1zvzsqb4lc28scpiz45anmgf4mmsdyc2jyl9nbcbr99448c4` to the 64 bit version `sha256-hCFCUsqLLZuol4L5pmsl7lWrCvnxMo0Eo2Rh/fcPvaM=`
> 
> You can use `nix hash to-base64 --type sha256 $32_BIT_HASH` to convert to a 64 bit hash

Thanks for the tip! I just copied the hash from the output of `nix-prefetch-url` instead of the usual `fakeHash`approach.
The checksum is the correct 64 bit one now.

**Comment by mayjs** [comment]
@mweinelt you reviewed the last `joplin-desktop` PR (#215577) and it seems like @HugoReeves is not available for the review right now. Could you review this PR as well?

**Comment by mweinelt** [comment]
Hey @mayjs, apparently I missed your ping. Can you update to 2.10.17?

**Comment by mayjs** [comment]
> Hey @mayjs, apparently I missed your ping. Can you update to 2.10.17?

Sure, I updated to the most recent version again (2.10.18). Thanks for taking a look at this!

**Comment by mazzzterrr** [comment]
Hello @mayjs, is it possible to update to 2.11.11 since the encryption method is updated and newer and older version are no longer compatible. Notes created in a newer version cannot be decrypted in the older version.

**Comment by mayjs** [comment]
> Hello @mayjs, is it possible to update to 2.11.11 since the encryption method is updated and newer and older version are no longer compatible. Notes created in a newer version cannot be decrypted in the older version.

Yes, updating should be easy, usually a version bump and update of the checksums in the package is enough. Judging by this PR it might take a while for the update to get merged though, so you might need to use an overlay in the meantime.

**Comment by mazzzterrr** [comment]
> > Hello @mayjs, is it possible to update to 2.11.11 since the encryption method is updated and newer and older version are no longer compatible. Notes created in a newer version cannot be decrypted in the older version.
> 
> Yes, updating should be easy, usually a version bump and update of the checksums in the package is enough. Judging by this PR it might take a while for the update to get merged though, so you might need to use an overlay in the meantime.

Ah, i am trying, but still pretty new to NixOS so i made this, and it is downloading and installing, but in the app the version remains 2.10.18
`nixpkgs.overlays = [ 
    (final: prev: {
      joplin-desktop = prev.joplin-desktop.overrideAttrs ( oldAttrs: {
        version = "2.11.11";
        name = "joplin-desktop-2.11.11";
        src = prev.fetchurl {
          url = "https://github.com/laurent22/joplin/releases/download/v2.11.11/Joplin-2.11.11.AppImage";
          sha256 = "afae3ecbe2df32b26751d69b55d6a4e7e2d0079d182ceb8c5dfb65678b370bfc";
          };         
        });
      }
    )
  ];`

**Comment by mayjs** [comment]
> > > Hello @mayjs, is it possible to update to 2.11.11 since the encryption method is updated and newer and older version are no longer compatible. Notes created in a newer version cannot be decrypted in the older version.
> > 
> > 
> > Yes, updating should be easy, usually a version bump and update of the checksums in the package is enough. Judging by this PR it might take a while for the update to get merged though, so you might need to use an overlay in the meantime.
> 
> Ah, i am trying, but still pretty new to NixOS so i made this, and it is downloading and installing, but in the app the version remains 2.10.18
> 
> ```nix
> `nixpkgs.overlays = [ 
>     (final: prev: {
>       joplin-desktop = prev.joplin-desktop.overrideAttrs ( oldAttrs: {
>         version = "2.11.11";
>         name = "joplin-desktop-2.11.11";
>         src = prev.fetchurl {
>           url = "https://github.com/laurent22/joplin/releases/download/v2.11.11/Joplin-2.11.11.AppImage";
>           sha256 = "afae3ecbe2df32b26751d69b55d6a4e7e2d0079d182ceb8c5dfb65678b370bfc";
>           };         
>         });
>       }
>     )
>   ];
> ```

Just noticed that 2.11.11 was already merged in #240317. It should already be part of `nixos-unstable`.

How your overlay may depend on how you "install" joplin on your system. Is it via `nix-env` or declarative? Are you using flakes?
If you need further help, I'd suggest taking this to Matrix or IRC.

**Pull request merged**
