### PR TITLE
openmpi: 4.1.5 -> 4.1.6 and pmix: 3.2.4 -> 5.0.1

### PR DESCRIPTION
**Pull request by markuskowa**
## Description of changes
Updating open-mpi and together pmix here.

Openmpi changes:
* Changelog: https://raw.githubusercontent.com/open-mpi/ompi/v4.1.x/NEWS
* add ucc to inputs, is supported since 4.1.4

Pmix changes:
* https://github.com/openpmix/openpmix/releases

Slurm: 
* Fix build with pmix>3 and remove patch, which is not needed any longer

pyslurm: fix build

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

CC: @Madouura This should bring the MPI eco-system one step closer towards integrating rocm?

### CODE REVIEW

**Comment by markuskowa** [comment]
@GrahamcOfBorg build cp2k elpa

**Comment by Madouura** [comment]
You may want to take a look at pyslurm. Probably here:
https://github.com/NixOS/nixpkgs/blob/75a52265bda7fd25e06e3a67dee3f0354e73243c/pkgs/development/python-modules/pyslurm/default.nix#L25

```console
INFO: running build_ext
INFO: building 'pyslurm.settings' extension
INFO: creating build
INFO: creating build/temp.linux-x86_64-cpython-310
INFO: creating build/temp.linux-x86_64-cpython-310/pyslurm
INFO: gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/nix/store/pgvy92m2rk4sw656nzsrz9lixarkw8z1-libxcrypt-4.4.36/include -fPIC -I/nix/store/zz84rik09vh1fmc4lrvhk7xpkz2c53c2-slurm-23.02.6.>
INFO: creating build/lib.linux-x86_64-cpython-310
INFO: creating build/lib.linux-x86_64-cpython-310/pyslurm
INFO: gcc -shared -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-zlib-1.3/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-bzip2-1.0.8/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-expat-2.5.0/lib -L/nix/sto>
INFO: building 'pyslurm.api' extension
INFO: gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/nix/store/pgvy92m2rk4sw656nzsrz9lixarkw8z1-libxcrypt-4.4.36/include -fPIC -I/nix/store/zz84rik09vh1fmc4lrvhk7xpkz2c53c2-slurm-23.02.6.>
INFO: gcc -shared -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-zlib-1.3/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-bzip2-1.0.8/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-expat-2.5.0/lib -L/nix/sto>
INFO: building 'pyslurm.pyslurm' extension
INFO: gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/nix/store/pgvy92m2rk4sw656nzsrz9lixarkw8z1-libxcrypt-4.4.36/include -fPIC -Ipyslurm -I/nix/store/zz84rik09vh1fmc4lrvhk7xpkz2c53c2-slur>
pyslurm/pyslurm.c: In function ‘__pyx_pymod_exec_pyslurm’:
pyslurm/pyslurm.c:90547:40: error: ‘KILL_JOB_ARRAY’ undeclared (first use in this function); did you mean ‘KILL_JOB_RESV’?
90547 |   __pyx_t_2 = __Pyx_PyInt_From_uint8_t(KILL_JOB_ARRAY); if (unlikely(!__pyx_t_2)) __PYX_ERR(7, 412, __pyx_L1_error)
      |                                        ^~~~~~~~~~~~~~
      |                                        KILL_JOB_RESV
pyslurm/pyslurm.c:90547:40: note: each undeclared identifier is reported only once for each function it appears in
error: command '/nix/store/zlzz2z48s7ry0hkl55xiqp5a73b4mzrg-gcc-wrapper-12.3.0/bin/gcc' failed with exit code 1
/nix/store/bbxdw4rgwwl3gnajri82yidr1nlsfskf-stdenv-linux/setup: line 1596: pop_var_context: head of shell_variables not a function context
```

**Review by Madouura — COMMENTED** [review]
LGTM, waiting on ``nixpkgs-review``.

>CC: @Madouura This should bring the MPI eco-system one step closer towards integrating rocm?

Yes, this will help a lot. Thanks!

**Comment by markuskowa** [comment]
@GrahamcOfBorg build python3Packages.pyslurm

**Comment by Madouura** [comment]
Result of `nixpkgs-review pr 262965` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>125 packages marked as broken and skipped:</summary>
  <ul>
    <li>ezminc</li>
    <li>frigate</li>
    <li>gpt2tc</li>
    <li>libtensorflow</li>
    <li>libtensorflow.python</li>
    <li>octavePackages.sparsersb</li>
    <li>postgresql11JitPackages.postgis</li>
    <li>postgresql11JitPackages.postgis.doc</li>
    <li>postgresql11Packages.postgis</li>
    <li>postgresql11Packages.postgis.doc</li>
    <li>python310Packages.baselines</li>
    <li>python310Packages.baselines.dist</li>
    <li>python310Packages.cleanlab</li>
    <li>python310Packages.cleanlab.dist</li>
    <li>python310Packages.dalle-mini</li>
    <li>python310Packages.dalle-mini.dist</li>
    <li>python310Packages.distrax</li>
    <li>python310Packages.distrax.dist</li>
    <li>python310Packages.dm-sonnet</li>
    <li>python310Packages.dm-sonnet.dist</li>
    <li>python310Packages.edward</li>
    <li>python310Packages.edward.dist</li>
    <li>python310Packages.elegy</li>
    <li>python310Packages.elegy.dist</li>
    <li>python310Packages.fenics</li>
    <li>python310Packages.fenics.dist</li>
    <li>python310Packages.flax</li>
    <li>python310Packages.flax.dist</li>
    <li>python310Packages.gpt-2-simple</li>
    <li>python310Packages.gpt-2-simple.dist</li>
    <li>python310Packages.mhcflurry</li>
    <li>python310Packages.mhcflurry.dist</li>
    <li>python310Packages.n3fit</li>
    <li>python310Packages.n3fit.dist</li>
    <li>python310Packages.pot</li>
    <li>python310Packages.pot.dist</li>
    <li>python310Packages.rlax</li>
    <li>python310Packages.rlax.dist</li>
    <li>python310Packages.scikit-tda</li>
    <li>python310Packages.scikit-tda.dist</li>
    <li>python310Packages.sunpy</li>
    <li>python310Packages.sunpy.dist</li>
    <li>python310Packages.tensorflow</li>
    <li>python310Packages.tensorflow-build</li>
    <li>python310Packages.tensorflow-build.dist</li>
    <li>python310Packages.tensorflow-datasets</li>
    <li>python310Packages.tensorflow-datasets.dist</li>
    <li>python310Packages.tensorflow-probability</li>
    <li>python310Packages.tensorflow-probability.dist</li>
    <li>python310Packages.tensorflow.dist</li>
    <li>python310Packages.tensorflowWithCuda</li>
    <li>python310Packages.tensorflowWithCuda.dist</li>
    <li>python310Packages.tensorflowWithoutCuda</li>
    <li>python310Packages.tensorflowWithoutCuda.dist</li>
    <li>python310Packages.tf2onnx</li>
    <li>python310Packages.tf2onnx.dist</li>
    <li>python310Packages.tflearn</li>
    <li>python310Packages.tflearn.dist</li>
    <li>python310Packages.treex</li>
    <li>python310Packages.treex.dist</li>
    <li>python310Packages.trfl</li>
    <li>python310Packages.trfl.dist</li>
    <li>python310Packages.umap-learn</li>
    <li>python310Packages.umap-learn.dist</li>
    <li>python310Packages.vqgan-jax</li>
    <li>python310Packages.vqgan-jax.dist</li>
    <li>python310Packages.worldengine</li>
    <li>python310Packages.worldengine.dist</li>
    <li>python311Packages.baselines</li>
    <li>python311Packages.baselines.dist</li>
    <li>python311Packages.cleanlab</li>
    <li>python311Packages.cleanlab.dist</li>
    <li>python311Packages.dalle-mini</li>
    <li>python311Packages.dalle-mini.dist</li>
    <li>python311Packages.distrax</li>
    <li>python311Packages.distrax.dist</li>
    <li>python311Packages.edward</li>
    <li>python311Packages.edward.dist</li>
    <li>python311Packages.elegy</li>
    <li>python311Packages.elegy.dist</li>
    <li>python311Packages.fenics</li>
    <li>python311Packages.fenics.dist</li>
    <li>python311Packages.flax</li>
    <li>python311Packages.flax.dist</li>
    <li>python311Packages.gpt-2-simple</li>
    <li>python311Packages.gpt-2-simple.dist</li>
    <li>python311Packages.mhcflurry</li>
    <li>python311Packages.mhcflurry.dist</li>
    <li>python311Packages.n3fit</li>
    <li>python311Packages.n3fit.dist</li>
    <li>python311Packages.pot</li>
    <li>python311Packages.pot.dist</li>
    <li>python311Packages.rlax</li>
    <li>python311Packages.rlax.dist</li>
    <li>python311Packages.scikit-tda</li>
    <li>python311Packages.scikit-tda.dist</li>
    <li>python311Packages.sunpy</li>
    <li>python311Packages.sunpy.dist</li>
    <li>python311Packages.tensorflow</li>
    <li>python311Packages.tensorflow-build</li>
    <li>python311Packages.tensorflow-build.dist</li>
    <li>python311Packages.tensorflow-probability</li>
    <li>python311Packages.tensorflow-probability.dist</li>
    <li>python311Packages.tensorflow.dist</li>
    <li>python311Packages.tensorflowWithCuda</li>
    <li>python311Packages.tensorflowWithCuda.dist</li>
    <li>python311Packages.tensorflowWithoutCuda</li>
    <li>python311Packages.tensorflowWithoutCuda.dist</li>
    <li>python311Packages.tf2onnx</li>
    <li>python311Packages.tf2onnx.dist</li>
    <li>python311Packages.tflearn</li>
    <li>python311Packages.tflearn.dist</li>
    <li>python311Packages.treex</li>
    <li>python311Packages.treex.dist</li>
    <li>python311Packages.trfl</li>
    <li>python311Packages.trfl.dist</li>
    <li>python311Packages.umap-learn</li>
    <li>python311Packages.umap-learn.dist</li>
    <li>python311Packages.vqgan-jax</li>
    <li>python311Packages.vqgan-jax.dist</li>
    <li>python311Packages.worldengine</li>
    <li>python311Packages.worldengine.dist</li>
    <li>t-rex</li>
    <li>worldengine-cli</li>
    <li>worldengine-cli.dist</li>
  </ul>
</details>
<details>
  <summary>135 packages failed to build:</summary>
  <ul>
    <li>apacheHttpdPackages.mod_tile (apacheHttpdPackages_2_4.mod_tile)</li>
    <li>cloudcompare</li>
    <li>dl-poly-classic-mpi</li>
    <li>entwine</li>
    <li>febio</li>
    <li>gdal (python311Packages.gdal)</li>
    <li>getdp</li>
    <li>gmt</li>
    <li>gplates</li>
    <li>grass</li>
    <li>haskellPackages.hgdal</li>
    <li>haskellPackages.hgdal.doc</li>
    <li>mapcache</li>
    <li>mapnik</li>
    <li>mapproxy</li>
    <li>mapproxy.dist</li>
    <li>mapserver</li>
    <li>merkaartor</li>
    <li>mysql-workbench</li>
    <li>nco</li>
    <li>netcdfcxx4</li>
    <li>octavePackages.mapping</li>
    <li>openorienteering-mapper</li>
    <li>p4est</li>
    <li>p4est-dbg</li>
    <li>paraview</li>
    <li>pdal</li>
    <li>perl536Packages.Tirex</li>
    <li>perl536Packages.Tirex.devdoc</li>
    <li>perl538Packages.Tirex</li>
    <li>perl538Packages.Tirex.devdoc</li>
    <li>petsc</li>
    <li>postgresql12JitPackages.postgis</li>
    <li>postgresql12JitPackages.postgis.doc</li>
    <li>postgresql12Packages.postgis</li>
    <li>postgresql12Packages.postgis.doc</li>
    <li>postgresql13JitPackages.postgis</li>
    <li>postgresql13JitPackages.postgis.doc</li>
    <li>postgresql13Packages.postgis</li>
    <li>postgresql13Packages.postgis.doc</li>
    <li>postgresql14JitPackages.postgis</li>
    <li>postgresql14JitPackages.postgis.doc</li>
    <li>postgresql14Packages.postgis</li>
    <li>postgresql14Packages.postgis.doc</li>
    <li>postgresqlJitPackages.postgis (postgresql15JitPackages.postgis)</li>
    <li>postgresqlJitPackages.postgis.doc (postgresql15JitPackages.postgis.doc)</li>
    <li>postgresqlPackages.postgis (postgresql15Packages.postgis)</li>
    <li>postgresqlPackages.postgis.doc (postgresql15Packages.postgis.doc)</li>
    <li>postgresql16JitPackages.postgis</li>
    <li>postgresql16JitPackages.postgis.doc</li>
    <li>postgresql16Packages.postgis</li>
    <li>postgresql16Packages.postgis.doc</li>
    <li>python310Packages.arviz</li>
    <li>python310Packages.arviz.dist</li>
    <li>python310Packages.bambi</li>
    <li>python310Packages.bambi.dist</li>
    <li>python310Packages.bsuite</li>
    <li>python310Packages.bsuite.dist</li>
    <li>python310Packages.cartopy</li>
    <li>python310Packages.cartopy.dist</li>
    <li>python310Packages.django-bootstrap4</li>
    <li>python310Packages.django-bootstrap4.dist</li>
    <li>python310Packages.fiona</li>
    <li>python310Packages.fiona.dist</li>
    <li>python310Packages.folium</li>
    <li>python310Packages.folium.dist</li>
    <li>python310Packages.gdal</li>
    <li>python310Packages.geopandas</li>
    <li>python310Packages.geopandas.dist</li>
    <li>python310Packages.osmnx</li>
    <li>python310Packages.osmnx.dist</li>
    <li>python310Packages.plotnine</li>
    <li>python310Packages.plotnine.dist</li>
    <li>python310Packages.pygmt</li>
    <li>python310Packages.pygmt.dist</li>
    <li>python310Packages.pymc</li>
    <li>python310Packages.pymc.dist</li>
    <li>python310Packages.python-mapnik</li>
    <li>python310Packages.python-mapnik.dist</li>
    <li>python310Packages.qcodes</li>
    <li>python310Packages.qcodes-contrib-drivers</li>
    <li>python310Packages.qcodes-contrib-drivers.dist</li>
    <li>python310Packages.qcodes-loop</li>
    <li>python310Packages.qcodes-loop.dist</li>
    <li>python310Packages.qcodes.dist</li>
    <li>python310Packages.rasterio</li>
    <li>python310Packages.rasterio.dist</li>
    <li>python310Packages.sfepy</li>
    <li>python310Packages.sfepy.dist</li>
    <li>python310Packages.wktutils</li>
    <li>python310Packages.wktutils.dist</li>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.bsuite</li>
    <li>python311Packages.bsuite.dist</li>
    <li>python311Packages.cartopy</li>
    <li>python311Packages.cartopy.dist</li>
    <li>python311Packages.django-bootstrap4</li>
    <li>python311Packages.django-bootstrap4.dist</li>
    <li>python311Packages.fiona</li>
    <li>python311Packages.fiona.dist</li>
    <li>python311Packages.folium</li>
    <li>python311Packages.folium.dist</li>
    <li>python311Packages.geopandas</li>
    <li>python311Packages.geopandas.dist</li>
    <li>python311Packages.hoomd-blue</li>
    <li>python311Packages.osmnx</li>
    <li>python311Packages.osmnx.dist</li>
    <li>python311Packages.plotnine</li>
    <li>python311Packages.plotnine.dist</li>
    <li>python311Packages.pygmt</li>
    <li>python311Packages.pygmt.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python311Packages.python-mapnik</li>
    <li>python311Packages.python-mapnik.dist</li>
    <li>python311Packages.qcodes-loop</li>
    <li>python311Packages.qcodes-loop.dist</li>
    <li>python311Packages.rasterio</li>
    <li>python311Packages.rasterio.dist</li>
    <li>python311Packages.sfepy</li>
    <li>python311Packages.sfepy.dist</li>
    <li>python311Packages.wktutils</li>
    <li>python311Packages.wktutils.dist</li>
    <li>pytrainer</li>
    <li>pytrainer.dist</li>
    <li>qgis</li>
    <li>qgis-ltr</li>
    <li>qmapshack</li>
    <li>saga</li>
    <li>sumo</li>
    <li>udig</li>
    <li>vpv</li>
  </ul>
</details>
<details>
  <summary>160 packages built:</summary>
  <ul>
    <li>EBTKS</li>
    <li>bicgl</li>
    <li>bicpl</li>
    <li>cdo</li>
    <li>conglomerate</li>
    <li>costa</li>
    <li>cp2k</li>
    <li>dbcsr</li>
    <li>eccodes</li>
    <li>elmerfem</li>
    <li>elpa</li>
    <li>elpa.dev</li>
    <li>elpa.doc</li>
    <li>elpa.man</li>
    <li>fftwMpi</li>
    <li>fftwMpi.dev</li>
    <li>fftwMpi.info</li>
    <li>fftwMpi.man</li>
    <li>globalarrays</li>
    <li>gnudatalanguage</li>
    <li>gromacsCudaMpi</li>
    <li>gromacsCudaMpi.dev</li>
    <li>gromacsCudaMpi.man</li>
    <li>gromacsDoubleMpi</li>
    <li>gromacsDoubleMpi.dev</li>
    <li>gromacsDoubleMpi.man</li>
    <li>gromacsMpi</li>
    <li>gromacsMpi.dev</li>
    <li>gromacsMpi.man</li>
    <li>haskellPackages.haskell-mpi</li>
    <li>haskellPackages.haskell-mpi.doc</li>
    <li>hdf5-mpi</li>
    <li>hdf5-mpi.dev</li>
    <li>highfive-mpi</li>
    <li>hp2p</li>
    <li>hpcg</li>
    <li>hpl</li>
    <li>inormalize</li>
    <li>ior</li>
    <li>labplot</li>
    <li>lammps-mpi</li>
    <li>libminc</li>
    <li>librsb</li>
    <li>libvdwxc</li>
    <li>migrate</li>
    <li>minc_tools</li>
    <li>minc_widgets</li>
    <li>mni_autoreg</li>
    <li>mpi (openmpi)</li>
    <li>mpi.man (openmpi.man)</li>
    <li>n3</li>
    <li>ncview</li>
    <li>nest-mpi</li>
    <li>netcdf</li>
    <li>netcdf-mpi</li>
    <li>netcdffortran</li>
    <li>neuron-full (python311Packages.neuronpy)</li>
    <li>neuron-mpi</li>
    <li>nwchem</li>
    <li>octavePackages.ncarray</li>
    <li>octavePackages.netcdf</li>
    <li>octopus</li>
    <li>oobicpl</li>
    <li>ovito</li>
    <li>p4est-sc</li>
    <li>p4est-sc-dbg</li>
    <li>parmetis</li>
    <li>pmix</li>
    <li>precice</li>
    <li>pymol</li>
    <li>pymol.dist</li>
    <li>python310Packages.boltztrap2</li>
    <li>python310Packages.boltztrap2.dist</li>
    <li>python310Packages.dask-mpi</li>
    <li>python310Packages.dask-mpi.dist</li>
    <li>python310Packages.datashader</li>
    <li>python310Packages.datashader.dist</li>
    <li>python310Packages.eccodes</li>
    <li>python310Packages.fipy</li>
    <li>python310Packages.fipy.dist</li>
    <li>python310Packages.gpaw</li>
    <li>python310Packages.gpaw.dist</li>
    <li>python310Packages.h5netcdf</li>
    <li>python310Packages.h5netcdf.dist</li>
    <li>python310Packages.h5py-mpi</li>
    <li>python310Packages.h5py-mpi.dist</li>
    <li>python310Packages.hoomd-blue</li>
    <li>python310Packages.meep</li>
    <li>python310Packages.meshio</li>
    <li>python310Packages.meshio.dist</li>
    <li>python310Packages.mpi4py</li>
    <li>python310Packages.mpi4py.dist</li>
    <li>python310Packages.nest</li>
    <li>python310Packages.netcdf4</li>
    <li>python310Packages.netcdf4.dist</li>
    <li>python310Packages.neuronpy</li>
    <li>python310Packages.pyprecice</li>
    <li>python310Packages.pyprecice.dist</li>
    <li>python310Packages.pyslurm</li>
    <li>python310Packages.pyslurm.dist</li>
    <li>python310Packages.wrf-python</li>
    <li>python310Packages.wrf-python.dist</li>
    <li>python311Packages.boltztrap2</li>
    <li>python311Packages.boltztrap2.dist</li>
    <li>python311Packages.dask-mpi</li>
    <li>python311Packages.dask-mpi.dist</li>
    <li>python311Packages.datashader</li>
    <li>python311Packages.datashader.dist</li>
    <li>python311Packages.eccodes</li>
    <li>python311Packages.fipy</li>
    <li>python311Packages.fipy.dist</li>
    <li>python311Packages.gpaw</li>
    <li>python311Packages.gpaw.dist</li>
    <li>python311Packages.h5netcdf</li>
    <li>python311Packages.h5netcdf.dist</li>
    <li>python311Packages.h5py-mpi</li>
    <li>python311Packages.h5py-mpi.dist</li>
    <li>python311Packages.meep</li>
    <li>python311Packages.meshio</li>
    <li>python311Packages.meshio.dist</li>
    <li>python311Packages.mpi4py</li>
    <li>python311Packages.mpi4py.dist</li>
    <li>python311Packages.nest</li>
    <li>python311Packages.netcdf4</li>
    <li>python311Packages.netcdf4.dist</li>
    <li>python311Packages.pyprecice</li>
    <li>python311Packages.pyprecice.dist</li>
    <li>python311Packages.pyslurm</li>
    <li>python311Packages.pyslurm.dist</li>
    <li>python311Packages.qcodes</li>
    <li>python311Packages.qcodes-contrib-drivers</li>
    <li>python311Packages.qcodes-contrib-drivers.dist</li>
    <li>python311Packages.qcodes.dist</li>
    <li>python311Packages.wrf-python</li>
    <li>python311Packages.wrf-python.dist</li>
    <li>quantum-espresso-mpi</li>
    <li>raxml-mpi</li>
    <li>rocmPackages.rocalution (rocmPackages_5.rocalution)</li>
    <li>rocmPackages.rocprofiler (rocmPackages_5.rocprofiler)</li>
    <li>scalapack</li>
    <li>scalapack.dev</li>
    <li>scotch</li>
    <li>siesta-mpi</li>
    <li>sirius</li>
    <li>slurm</li>
    <li>slurm-spank-stunnel</li>
    <li>slurm-spank-x11</li>
    <li>slurm.dev</li>
    <li>spfft</li>
    <li>spla</li>
    <li>tests.pkg-config.defaultPkgConfigPackages.ompi</li>
    <li>tests.pkg-config.defaultPkgConfigPackages.ompi-c</li>
    <li>tests.pkg-config.defaultPkgConfigPackages.ompi-cxx</li>
    <li>tests.pkg-config.defaultPkgConfigPackages.ompi-f77</li>
    <li>tests.pkg-config.defaultPkgConfigPackages.ompi-f90</li>
    <li>tests.pkg-config.defaultPkgConfigPackages.ompi-fort</li>
    <li>tests.pkg-config.defaultPkgConfigPackages.orte</li>
    <li>trilinos-mpi</li>
    <li>xyce-parallel</li>
    <li>xyce-parallel.doc</li>
  </ul>
</details>

**Review by Madouura — APPROVED** [review]
LGTM.
All of the failures are unrelated to this PR and/or I manually terminated because I have fixes for them in another PR.

**Comment by markuskowa** [comment]
@Madouura thanks for the review!

**Pull request merged**
