### PR TITLE
[23.11] mlflow: 2.7.0 -> 2.12.1

### PR DESCRIPTION
**Pull request by veprbl**
## Description of changes

Backport of #289834

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by LeSuisse — COMMENTED** [review]
The changes looks pretty big for 23.11, it might be preferable to backport the fix directly. https://github.com/mlflow/mlflow/commit/432b8ccf27fd3a76df4ba79bb1bec62118a85625 applies cleanly on top of the 2.7.0.


The commit message should start with `python3Packages.mlflow` to trigger OfBorg.

**Comment by LeSuisse** [comment]
Yeah OK I did not see https://huntr.com/repos/mlflow/mlflow and they do not mention all the security issues in their release notes...

I might take a look to see if we can only backport the sec fixes but it will likely have to wait this week end.

If the bump to 2.10.2 is considered safe enough to be backported the PR should be rewritten to cherry-pack the patches from `master`, see https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#how-to-backport-pull-requests

**Comment by risicle** [comment]
Yeah I don't particularly like it, but there are an awful lot of security issues spread across several releases.

`nixpkgs-review` reveals no new failures, macos 12 x86_64 & nixos x86_64

**Comment by risicle** [comment]
I guess the other option is `knownVulnerabilities`, but offering a second version in parallel for those who don't mind upgrading doesn't work quite so well in the python packageset.

**Comment by veprbl** [comment]
cc @mweinelt @benxiao @bcdarwin

**Comment by LeSuisse** [comment]
So I took a closer look but even identifying the related PR/commits is a PITA. Some valid reports are flagged as duplicate and link to other non public reports :/ 

At this point I do not think attempting to backports the fixes is a viable option.

**Comment by mweinelt** [comment]
We can always deal with regressions later.

**Comment by veprbl** [comment]
I don't think the python package update would bring breakage, but we could instead restrict update to only apply to mlflow-server.

**Comment by LeSuisse** [comment]
Cherry-picked patches to bump to 2.12.1. Too many security patches that are not always mentioned (and it seems the Huntr.com page that was the best places to identify most of them is not available anymore). 2.12.1 release notes mentions:

> Security Patch: Addressed a critical Local File Read/Path Traversal vulnerability within the Model Registry, ensuring robust protection against unauthorized access and securing user data integrity.

**Comment by LeSuisse** [comment]
Thanks for the merge, please ping me if a regression is spotted and will see what we can do. Clearly it is not an easy package to maintain.

**Comment by LeSuisse** [comment]
A bit late but nixpkgs-review is happy on Linux x86_64

Result of `nixpkgs-review pr 289835` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>64 packages built:</summary>
  <ul>
    <li>dbx</li>
    <li>dbx.dist</li>
    <li>mlflow-server</li>
    <li>mlflow-server.dist</li>
    <li>openai-full</li>
    <li>openai-full.dist</li>
    <li>python310Packages.dalle-mini</li>
    <li>python310Packages.dalle-mini.dist</li>
    <li>python310Packages.fastai</li>
    <li>python310Packages.fastai.dist</li>
    <li>python310Packages.k-diffusion</li>
    <li>python310Packages.k-diffusion.dist</li>
    <li>python310Packages.mlflow</li>
    <li>python310Packages.mlflow.dist</li>
    <li>python310Packages.mmcv</li>
    <li>python310Packages.mmcv.dist</li>
    <li>python310Packages.mmengine</li>
    <li>python310Packages.mmengine.dist</li>
    <li>python310Packages.skrl</li>
    <li>python310Packages.skrl.dist</li>
    <li>python310Packages.spacy</li>
    <li>python310Packages.spacy-loggers</li>
    <li>python310Packages.spacy-loggers.dist</li>
    <li>python310Packages.spacy-lookups-data</li>
    <li>python310Packages.spacy-lookups-data.dist</li>
    <li>python310Packages.spacy-transformers</li>
    <li>python310Packages.spacy-transformers.dist</li>
    <li>python310Packages.spacy.dist</li>
    <li>python310Packages.textacy</li>
    <li>python310Packages.textacy.dist</li>
    <li>python310Packages.textnets</li>
    <li>python310Packages.textnets.dist</li>
    <li>python310Packages.wandb</li>
    <li>python310Packages.wandb.dist</li>
    <li>python311Packages.dalle-mini</li>
    <li>python311Packages.dalle-mini.dist</li>
    <li>python311Packages.fastai</li>
    <li>python311Packages.fastai.dist</li>
    <li>python311Packages.k-diffusion</li>
    <li>python311Packages.k-diffusion.dist</li>
    <li>python311Packages.mlflow</li>
    <li>python311Packages.mlflow.dist</li>
    <li>python311Packages.mmcv</li>
    <li>python311Packages.mmcv.dist</li>
    <li>python311Packages.mmengine</li>
    <li>python311Packages.mmengine.dist</li>
    <li>python311Packages.skrl</li>
    <li>python311Packages.skrl.dist</li>
    <li>python311Packages.spacy</li>
    <li>python311Packages.spacy-loggers</li>
    <li>python311Packages.spacy-loggers.dist</li>
    <li>python311Packages.spacy-lookups-data</li>
    <li>python311Packages.spacy-lookups-data.dist</li>
    <li>python311Packages.spacy-transformers</li>
    <li>python311Packages.spacy-transformers.dist</li>
    <li>python311Packages.spacy.dist</li>
    <li>python311Packages.textacy</li>
    <li>python311Packages.textacy.dist</li>
    <li>python311Packages.textnets</li>
    <li>python311Packages.textnets.dist</li>
    <li>python311Packages.wandb</li>
    <li>python311Packages.wandb.dist</li>
    <li>tts</li>
    <li>tts.dist</li>
  </ul>
</details>

**Pull request merged**
