### PR TITLE
[21.11] llvmPackages_14: 14.0.0rc1 -> 14.0.1

### PR DESCRIPTION
**Pull request by ggreif**
This (mostly) catches up with `master` branch and unbreaks `llvm_14` and dependents.

This is the difference vs. `master`:
``` diff
$ git diff nixos/master HEAD -- pkgs/development/compilers/llvm/14
diff --git a/pkgs/development/compilers/llvm/14/lld/default.nix b/pkgs/development/compilers/llvm/14/lld/default.nix
index 1ae6d4ea6fc..fe655c76112 100644
--- a/pkgs/development/compilers/llvm/14/lld/default.nix
+++ b/pkgs/development/compilers/llvm/14/lld/default.nix
@@ -42,7 +42,7 @@ stdenv.mkDerivation rec {
 
   meta = llvm_meta // {
     homepage = "https://lld.llvm.org/";
-    description = "The LLVM linker (unwrapped)";
+    description = "The LLVM linker";
     longDescription = ''
       LLD is a linker from the LLVM project that is a drop-in replacement for
       system linkers and runs much faster than them. It also provides features
diff --git a/pkgs/development/compilers/llvm/14/llvm/default.nix b/pkgs/development/compilers/llvm/14/llvm/default.nix
index ea147337831..05aac728b45 100644
--- a/pkgs/development/compilers/llvm/14/llvm/default.nix
+++ b/pkgs/development/compilers/llvm/14/llvm/default.nix
@@ -200,12 +200,6 @@ in stdenv.mkDerivation (rec {
     ln -s $lib/lib/libLLVM.dylib $lib/lib/libLLVM-${shortVersion}.dylib
     ln -s $lib/lib/libLLVM.dylib $lib/lib/libLLVM-${release_version}.dylib
   ''
-  + optionalString enableSharedLibraries ''
-    mkdir -p $dev/lib
-    mv $lib/lib/*.a $dev/lib
-    sed -i -E "s|$lib/lib/(.*)\.a|$dev/lib/\1\.a|" \
-      "$dev/lib/cmake/llvm/LLVMExports-${if debugVersion then "debug" else "release"}.cmake"
-  ''
   + optionalString (stdenv.buildPlatform != stdenv.hostPlatform) ''
     cp NATIVE/bin/llvm-config $dev/bin/llvm-config-native
   '';
```

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ggreif** [comment]
@GrahamcOfBorg build llvm_14 lld_14 clang_14

**Comment by primeos** [comment]
Please use `git cherry-pick -x <original commit>`, see https://nixos.org/manual/nixpkgs/stable/#submitting-changes-stable-release-branches.

**Comment by ggreif** [comment]
> Please use `git cherry-pick -x <original commit>`, see https://nixos.org/manual/nixpkgs/stable/#submitting-changes-stable-release-branches.

@primeos that is fine, but it is not just one commit, but this list:
```
git cherry-pick -x 1748887ff23 dd8169da3e4 90d9b7c8dc7 f0c2e464685 c9cfbe08995 641c2d3b7b6 790c4f13dd8 5e04d64aed1 7151381aab2 4f3116f7542 2efcc3e297a 6d111cbf615 075c5eb8d39 84dbfa8f970
```
Additionally, some of these contain changes outside of `pkgs/development/compilers/llvm/14`, namely:
- `libomptarget/DeviceRTL/CMakeLists.txt`
- `libomptarget/deviceRTLs/amdgcn/CMakeLists.txt`
- `CMakeLists.txt`
- `libomptarget/plugins/amdgpu/CMakeLists.txt`
- `libomptarget/plugins/ve/CMakeLists.txt`
- `runtime/src/CMakeLists.txt`
- `tools/multiplex/CMakeLists.txt`
- `cmake/OpenMPTesting.cmake`

Can you provide some guidance how to proceed with these? I can imagine that those changed files provide necessary changes for the success of this PR, but it is not clear whether I am allowed to submit it this way.

**Comment by primeos** [comment]
> @primeos that is fine, but it is not just one commit, but this list:

Yes, that's fine ;)

> Can you provide some guidance how to proceed with these?

I usually do one of two things (after examining the commit):
a) I don't cherry-pick the commit (because it's optional, requires other commits with major changes, etc.)
b) I only cherry-pick the relevant changes (i.e., pkgs/development/compilers/llvm/14 in this case; requires a bit of Git fu) and make it clear in the commit message (e.g., by changing `openmp: new fix-find-tools patch` to `llvmPackages_14.openmp: new fix-find-tools patch`)

In this case I didn't cherry-pick any of those commits since NixOS 22.05 is imminent and I only care about Chromium but it's of course fine to backport those commits.

**Comment by ggreif** [comment]
@primeos Okay, PTAL. `pkgs/development/compilers/llvm/update.sh` is probably necessary, I am happy to incorporate your input there.

**Comment by ggreif** [comment]
@primeos Sadly the Darwin builders ofBorg time out after an hour, but both Linux builders have produced results. So I guess this is an improvement.

**Comment by risicle** [comment]
`nixpkgs-review` reveals no new failures on macos 10.15

**Comment by primeos** [comment]
Not really, I just don't have that much time anymore so it takes me a bit sometimes (but feel free to re-ping me after a few days in case I forgot about something).

**Review by primeos — APPROVED** [review]
Diff and commits LGTM (I did a few Git checks to verify it). CI is also fine so it should be good to go :) Thanks for the PR!

**Pull request merged**
