### PR TITLE
erlang: update default to OTP 27

### PR DESCRIPTION
**Pull request by adamcstephens**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by adamcstephens** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368120`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 27 packages built:</summary>
  <ul>
    <li>cl</li>
    <li>couchdb3</li>
    <li>ejabberd</li>
    <li>elixir (elixir_1_17)</li>
    <li>elixir-ls</li>
    <li>elixir_1_18</li>
    <li>elvis-erlang</li>
    <li>erlang</li>
    <li>erlang-ls</li>
    <li>erlang_nox</li>
    <li>erlfmt</li>
    <li>ex_doc</li>
    <li>lexical</li>
    <li>lfe (lfe_2_1)</li>
    <li>livebook</li>
    <li>mercury</li>
    <li>mix2nix</li>
    <li>notmuch-bower</li>
    <li>plausible</li>
    <li>pleroma</li>
    <li>protoc-gen-elixir</li>
    <li>rebar</li>
    <li>rebar3</li>
    <li>sonic-pi</li>
    <li>tsung</li>
    <li>wings</li>
    <li>yaws</li>
  </ul>
</details>

**Comment by lucasewd** [comment]
# [nixpkgs-reviewd](https://github.com/nixosbrasil/nixpkgs-reviewd) workflow started

**Status and logs**: https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12495621270

**Comment by lucasewd** [comment]
# [nixpkgs-reviewd](https://github.com/nixosbrasil/nixpkgs-reviewd) workflow finished

**Status and logs**: https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12495621270


## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368120`

---
### `x86_64-darwin`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>couchdb3</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 20 packages built:</summary>
  <ul>
    <li>elixir (elixir_1_17)</li>
    <li>elixir-ls</li>
    <li>elixir_1_18</li>
    <li>elvis-erlang</li>
    <li>erlang</li>
    <li>erlang-ls</li>
    <li>erlang_nox</li>
    <li>erlfmt</li>
    <li>ex_doc</li>
    <li>lexical</li>
    <li>lfe (lfe_2_1)</li>
    <li>livebook</li>
    <li>mercury</li>
    <li>mix2nix</li>
    <li>plausible</li>
    <li>pleroma</li>
    <li>protoc-gen-elixir</li>
    <li>rebar</li>
    <li>rebar3</li>
    <li>tsung</li>
  </ul>
</details>

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368120`

---
### `aarch64-darwin`
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>couchdb3</li>
    <li>pleroma</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 19 packages built:</summary>
  <ul>
    <li>elixir (elixir_1_17)</li>
    <li>elixir-ls</li>
    <li>elixir_1_18</li>
    <li>elvis-erlang</li>
    <li>erlang</li>
    <li>erlang-ls</li>
    <li>erlang_nox</li>
    <li>erlfmt</li>
    <li>ex_doc</li>
    <li>lexical</li>
    <li>lfe (lfe_2_1)</li>
    <li>livebook</li>
    <li>mercury</li>
    <li>mix2nix</li>
    <li>plausible</li>
    <li>protoc-gen-elixir</li>
    <li>rebar</li>
    <li>rebar3</li>
    <li>tsung</li>
  </ul>
</details>

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368120`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 27 packages built:</summary>
  <ul>
    <li>cl</li>
    <li>couchdb3</li>
    <li>ejabberd</li>
    <li>elixir (elixir_1_17)</li>
    <li>elixir-ls</li>
    <li>elixir_1_18</li>
    <li>elvis-erlang</li>
    <li>erlang</li>
    <li>erlang-ls</li>
    <li>erlang_nox</li>
    <li>erlfmt</li>
    <li>ex_doc</li>
    <li>lexical</li>
    <li>lfe (lfe_2_1)</li>
    <li>livebook</li>
    <li>mercury</li>
    <li>mix2nix</li>
    <li>notmuch-bower</li>
    <li>plausible</li>
    <li>pleroma</li>
    <li>protoc-gen-elixir</li>
    <li>rebar</li>
    <li>rebar3</li>
    <li>sonic-pi</li>
    <li>tsung</li>
    <li>wings</li>
    <li>yaws</li>
  </ul>
</details>

**Comment by adamcstephens** [comment]
Hmm, sorry about that. Looks like ejabberd has been updated since this was merged so that may have fixed OTP 27 support.

I also added version-specific top-level beam package sets which would be better to use if this needs to be pinned. e.g. `beam26Packages` and then the ejabberd package could get erlang from there.

**Comment by adamcstephens** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/371148 to fix ejabberd

**Pull request merged**
