### PR TITLE
syncplay: use Qt6 for macOS

### PR DESCRIPTION
**Pull request by Enzime**
###### Description of changes

Update Syncplay to 1.7.0 and switch to PySide6 and Qt6, also mark macOS as a platform which will start working when #231325 is merged

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wegank** [comment]
@ofborg build syncplay syncplay.passthru.tests

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 231386` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>syncplay</li>
    <li>syncplay-nogui</li>
  </ul>
</details>

**Review by wegank — APPROVED** [review]

**Comment by girlmaya** [comment]
Builds on x86_64-linux but crashes upon hitting the "Store configuration and run Syncplay" button. Was this tested? Is there anything I need to add to my system for it to work? (wrt Qt6 & PySide6)
Thank you

**Comment by wegank** [comment]
@girlmaya The maintainer of the package has clearly tested it on `x86_64-linux` and `aarch64-darwin`. I've also tested it on macOS before merging it. Did version 1.6.9 work for you?

**Comment by Enzime** [comment]
@girlmaya just tested again and it's not working for me either, I've now submitted a PR to fix Linux :+1: 

https://github.com/NixOS/nixpkgs/pull/234094

**Pull request merged**
