### PR TITLE
treewide: rev -> tag, for pkgs I maintain, remove with lib

### PR DESCRIPTION
**Pull request by phanirithvij**
## Things done

Same hashes before and after.

```console
$ nix build -f default.nix distrobox-tui gh-i gitcs gogup gomtree opengist viddy --print-out-paths --no-link
/nix/store/m371rkcdvc4iyzyr6c47l2sfbszj1kn6-distrobox-tui-0.1.0
/nix/store/gp1s6g12ljrk4017h48y8vcv1p7y6rmj-gh-i-0.0.10
/nix/store/mwfyjg9zpjpzq42vc48npf2dx10kdmlz-gitcs-1.2.0
/nix/store/0a2wriygwsq5byskb6nhxmx1xw5pkckz-gogup-0.27.5
/nix/store/c1aps1x1gsa4312nprkl7yz1dbradv0q-gomtree-0.5.4
/nix/store/jdl71k8c5mgw7ljlv7077fdk3yg5d6dz-opengist-1.8.3
/nix/store/z9rcg76xawrdpp0hmi2gpaci5cxn3c29-viddy-1.3.0
```

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by phanirithvij** [comment]
@ofborg build distrobox-tui gh-i gitcs gogup gomtree opengist viddy

**Comment by phanirithvij** [comment]
I didn't know what to name the commit, and did not want 7 commits, but I hope this is clear enough.

**Comment by Atemu** [comment]
First of all: Separate commits for the with refactor and another one for rev -> tag.

Second: I don't think this justifies calling it "treewide" because you're not actually doing anything across the tree, just your packages.

Honestly, I don't really get the point of doing this; just change out rev for tag when you next update your packages. You can stuff a separate refactor commit in there too.

If you want to apply this sooner for some reason (I don't really get the urgency here), please contribute to making an actual tree-wide commit for this that also applies to your packages.

**Comment by phanirithvij** [comment]
I will wait for the treewide.

**Pull request closed without merging**
