### PR TITLE
k3s_1_26: remove package

### PR DESCRIPTION
**Pull request by wrmilling**
## Description of changes

Removal of EOL k3s version 1.26 prior to 24.05 branch off. Leaving upgrade path from 1.27 to 1.30. 

Branch off task from #311692 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by superherointj — APPROVED** [review]

**Comment by superherointj** [comment]
One mistake we did here is to not add a warning for the package that is being removed.

**Comment by wrmilling** [comment]
> One mistake we did here is to not add a warning for the package that is being removed.

Are you thinking a deprecation notice shown during a rebuild or a notice in the release notes for 24.05? 

Main reason I did not do a deprecation notice for rebuilds in this PR being the short time before branch off for 24.05 and given the fact that the release line was already multi-month EOL. 

We could still get a notice into the breaking change documentation for 24.05 that k3s_1_24, k3s_1_25, and k3s_1_26 have been removed for this release.

Would probably be a good idea to start setting the deprecation notices on unstable once the release goes into maintenance mode and then delete after a set period of time once EOL. Our current documentations says we should be deleting the 1_27, 1_28, and 1_29 once 24.05 is released.

**Comment by superherointj** [comment]
Deprecation notice for builds. Without the warning, users will be presented a cryptic error, instead of a coherent deprecation notice.

Docs are too much already. Counter intuitively, the longer the docs, the worse it is. People just won't read it. I think, K3s docs has to be refactored already, and information from Wiki included. We should strive to keep things simple. Unfortunately, thinking is hard and the bias is to make it complicated.

Yes, once release happens we should delete all K3s versions that exist in `nixos-stable` but the latest. And add the aliases warnings (for those versions).

**Comment by superherointj** [comment]
@wrmilling Don't worry about this tiny detail of alias. Let's just follow the usual procedure so that we remember this next time. It is not like this is life changing, it is not, but if we forget here, we forget later too when it may matter. So, see it as an opportunity for learning.

Also, thanks for the help in upkeep. Your presence, as the presence of our other maintainers, are always appreciated. It's important to have you guys here, particularly to stop me merging dumb shit too often. :-)

**Comment by wrmilling** [comment]
> Docs are too much already. Counter intuitively, the longer the docs, the worse it is. People just won't read it. I think, K3s docs has to be refactored already, and information from Wiki included. We should strive to keep things simple. Unfortunately, thinking is hard and the bias is to make it complicated.

Yeah, I am happy to help on the documentation front. Probably an issue or such to track ideas, whose working on what, and progress? 

> Yes, once release happens we should delete all K3s versions that exist in `nixos-stable` but the latest. And add the aliases warnings (for those versions).

This is one point where I disagree on the process given those branches still receive upstream support, but something we can discuss as part of any documentation update work. 

> @wrmilling Keep cool about this tiny detail of alias. Let's just follow the usual procedure so that we remember this next time. It is not like this is life changing, it is not, but if we forget here, we forget later too when it may matter. So, I suggest to see it as an opportunity of learning. [I always forget about it too.]

No sweat from me on this, all good. 

> I will propose the alias PR.
> 
> Also, thanks for the help in upkeep. Your presence, as the presence of our other maintainers, are always appreciated. It's important to have you guys here, particularly to stop me from merging dumb shit too often. :-)

:+1: :100:

**Pull request merged**
