### PR TITLE
harsh: init at 0.8.28

### PR DESCRIPTION
**Pull request by LAURAilway**
## Description of changes
Added the cli based habit tracker harsh (https://github.com/wakatara/harsh)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by LAURAilway** [comment]
@h7x4 Good now?

**Review by AndersonTorres — CHANGES_REQUESTED** [review]
Why not building this from source code instead of precompiled binaries?
Nixpkgs has a good support for Golang.

**Comment by h7x4** [comment]
add-to-maintainer-list commit should be formatted as following:

maintainers: add LAURAilway

There are also some other commits left to rebase

**Comment by LAURAilway** [comment]
> Why not building this from source code instead of precompiled binaries? Nixpkgs has a good support for Golang.

Because I have no idea how to do that and wasn't aware that there was good support for golang.

**Comment by h7x4** [comment]
I think it's already building from source, but it's a bit weird to use `fetchurl` when we have things like `fechFromGitHub`. Maybe you could use [this](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/security/go-dork/default.nix) for reference?

`buildPhase` and `installPhase` is mostly automatically determined by the project files in the source.

**Comment by AndersonTorres** [comment]
> Because I have no idea how to do that and wasn't aware that there was good support for golang.

Look at how mailhog is packaged.

**Comment by LAURAilway** [comment]
Ok, I will take a look at all those things and reopen once in am done rewriting. Thanks :)

**Comment by soupglasses** [comment]
This got reopened in #251704

**Pull request closed without merging**
