### PR TITLE
Remove manual service

### PR DESCRIPTION
**Pull request by edolstra**
###### Motivation for this change

This removes the `nixos-manual` service on TTY-8 since it isn't very useful (you can just run `nixos-help`) and is a security issue if people enable it in regular systems.

While I was at it, I also removed the `rogue` service (which has been disabled in the installer for a while).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
Sounds good to me in principle.  Let's add `mkRemovedOptionModule` I guess?  I certainly assume porting to 20.03; I'm not sure about 19.09.

**Comment by rnhmjoj** [comment]
I think having the manual already open on the installer is useful and *cool*. Also rogue is nice when you have to wait for `nix-install` to finish.

I have a happy memory of the first time I installed NixOS: I was surprised to discover the non-graphical installer was so friendly compared to arch linux.
I'm not really happy to see these going away.

**Comment by rnhmjoj** [comment]
Maybe making the modules internal and only enabling them on the installer could be a solution.

**Review by primeos — APPROVED** [review]
LGTM, I like this approach and IMO we don't loose any functionality (regarding the default configuration) while removing unnecessary complexity.

Adding a nice error message for the removed modules would improve the user experience, but I consider it optional as there should be very few users (but in any case it would probably be nice to have).

**Comment by danbst** [comment]
https://github.com/NixOS/nixpkgs/blob/67c81af775efd0e9afea1d41b92b7eec9be89485/nixos/doc/manual/installation/installing.xml#L26-L29

This one too.

**Comment by worldofpeace** [comment]
https://github.com/NixOS/nixpkgs/pull/83199#issuecomment-602484826

This needs to use `mkRemovedOptionModule`, that's actually in the checklist for reviewing contributions in the nixpkgs manual.

**Comment by vcunat** [comment]
Like this?  #83651

**Pull request merged**
