### PR TITLE
libreoffice: 6.1.4.2 -> 6.1.5.2, 6.2.1.2

### PR DESCRIPTION
**Pull request by 7c6f434c**
###### Motivation for this change

LibreOffice update.

###### Things done

[x] LibreOffice Still: built and executed on `x86_64-linux` (NixOS-like)

##### Status

This is the latest LibreOffice update — will probably backport to 19.03 because starting a stable cycle with obsolete LibreOffice Still is unfortunate.

### CODE REVIEW

**Comment by 7c6f434c** [comment]
At least now `libreoffice-still` actually reaches _building_ instead of stumbling on something around checking the tarballs…

**Comment by dtzWill** [comment]
libreoffice-fresh fails a few tests re:odfvalidator? Not sure what's going on there....

Trying libreoffice-still presently... (build build build :))

**Comment by 7c6f434c** [comment]
@dtzWill Still seems to work for me.

As for Fresh tests: so far I am working on disabling some of them, because 2-pixel rendering problems… (I think even upstream developers sometimes complain about fragileness of some tests). I want _most_ tests to pass, and there are some failures we accept but dislike, but rendering differences are not even disappointing.

But you could have mentioned exact test name so I can kill it too and not wait for my rebuild!

**Comment by 7c6f434c** [comment]
I wonder howmany more tests to kill are left…

**Comment by 7c6f434c** [comment]
Hrm. Just how many new tests fail???

But still, I want a full list first…

**Comment by 7c6f434c** [comment]
ARGGH. Full round-trip import-export-import fails for _many_ entries. Not sure what to do about all that…

**Comment by 7c6f434c** [comment]
Status update: LibreOffice Fresh builds, seems to run.

I have disabled way too many tests — the last for lines disable a few _classes_ of tests.

I have no idea how to investigate better and don't have time right now…

(And not updating LibreOffice before stable release is _also_ a bad idea, sigh).

(Deleting my old comments about «progress» in finding a list of tests to disable)

**Comment by 7c6f434c** [comment]
@lheckemann any preferences regarding handling this LibreOffice update?

**Comment by lheckemann** [comment]
Yeah, I'm all for backporting if the current version is obsolete. We can consider the missing tests a bug and just "deal with it" until fixed (if fixed); it's far from the worst, we have 1536 occurrences of `doCheck = false;` in nixpkgs :/

**Comment by 7c6f434c** [comment]
Let;s test this a bit right now then. Backported as c6e60578b6d.

**Pull request merged**
