### PR TITLE
all-packages.nix: Alias self to res, deprecating self

### PR DESCRIPTION
**Pull request by roberth**
For historical reasons, self in `all-packages.nix` was ill-named. This removes its usages from `all-packages.nix` and provides a deprecation message for those who use a patched Nixpkgs.

Some packages seem to depend on the peculiarities of res, as can be seen by making res into an alias of `pkgs` (normally `self`). The `super` variable doesn't have all attributes that are needed.

Therefore the simple fix is not guaranteed to work and as such,
usages of `res` need to be changed to `pkgs` or `super`, case by case.

###### Motivation for this change

#34881 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
Since we use rec here i think we could just get rid of res.

**Comment by roberth** [comment]
@matthewbauer I don't see a `rec` keyword. Did I miss something?

**Comment by matthewbauer** [comment]
Oh maybe not then! ```with pkgs;``` here does a similar thing. It's used inconsistently though.

**Comment by roberth** [comment]
So we have `with` self, as it's usually named. That's like some class-based object oriented languages.
I don't think we should do that here, but that's a separate issue.

**Comment by roberth** [comment]
@Ericson2314 When switching, some hashes change, so it's not guaranteed to work.
Even though I don't expect things to break, it's still good to separate the concerns.
This pr only fixes the naming. I suppose a follow-up pr/prs can improve the way these packages are structured.

**Review by Ericson2314 — APPROVED** [review]

**Comment by Ericson2314** [comment]
Fair enough. If you want to make the next one removing all the `res` for `self,` and ofborg can spit out the changed hashes, I'll happily triage them.

**Comment by matthewbauer** [comment]
The warning here breaks tarball:

https://hydra.nixos.org/build/85466401/nixlog/1/tail

**Comment by edolstra** [comment]
IMHO, `res` is even vaguer than `self`. It should be `final` or something like that.

**Comment by Ericson2314** [comment]
It's now been removed!

**Pull request merged**
