### PR TITLE
nixos/borgbackup: don't exit with code 1 on warnings

### LINKED ISSUE #177733: borgbackup exits if borg issues any warnings
### Describe the bug

`borg` uses exit code 1 to indicate not errors, but warnings, which are not fatal to the program (see https://borgbackup.readthedocs.io/en/stable/usage/general.html#return-codes).

Since `systemd.services.*.script` is prefixed by `set -e`, this makes the backup script exit after e.g. `borg create`, even though it should continue. 

The default silent behavior of borg also made this failure more mysterious. I needed to set `extraCreateArgs = "--verbose";` to get Borg to log the warning.

### Steps To Reproduce
1. Have a `borgbackup.jobs.foo`
2. The unit will occasionally exit with an error as Borg issues warnings. One warning I encounter frequently is this in `borg create`:
```
/root/.config/borg/security/048c71a26c7d15b4890012f52aa70a0f97f0e8d5c0603a8a006baf497a698116/nonce: file changed while we backed it up
```
  which happens if you try to back-up the home directory of the user that Borg is running as (`/root` when running as `root`).
3. The unit exits early, does not execute prune, `postCreate`, etc. and is marked as failed.

### Expected behavior
The script of borgbackup unit should continue even after receiving exit code of 1 from an individual `borg` command.

### Notify maintainers

@dotlambda 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[root@calor:~]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.43, NixOS, 22.05 (Quokka), 22.05-11e805f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/store/hm5n6bfsl9grg6r2fxynyrxv896wq5x4-1390c1iw8j28msp2k2pbamq6mqjpgw03-nixos-22.05-2022-06-07`
```

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
fixes https://github.com/NixOS/nixpkgs/issues/177733

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [x] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by justinas — APPROVED** [review]
LGTM in general. Not sure how easy it will be to maintain this patch in the long run, as opposed to the [wrapper approach](https://github.com/NixOS/nixpkgs/issues/177733#issuecomment-1200499837).

**Review by pennae — COMMENTED** [review]
wouldn't this silence *all* warnings including eg "repository moved" warnings? that probably wouldn't be the intended effect here. @mweinelt's original patch seems like the better way to go, whether it's applied to all borgs or just the one used by the module.

**Comment by dotlambda** [comment]
The warnings will still be in the logs. This only changes the exit code.

**Comment by dotlambda** [comment]
> @mweinelt's original patch seems like the better way to go, whether it's applied to all borgs or just the one used by the module.

Feel free to open a PR implementing it for the module only.

**Review by bjornfor — CHANGES_REQUESTED** [review]
I agree we shouldn't patch upstream code, but instead deal with this (for those who want) in the NixOS module.

**Comment by symphorien** [comment]
I implemented something similar in https://github.com/NixOS/nixpkgs/pull/310199 but without patching the source.

**Pull request closed without merging**
