### PR TITLE
qt5: 5.10.0 -> 5.10.1

### PR DESCRIPTION
**Pull request by bkchr**
###### Motivation for this change
Yeah, a bug fix release. 

It currently still compiles,  but it looks good.

@ttuegel @adisbladis @peterhoeg 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bkchr** [comment]
Hmm, somehow the kde activity manager wants to mix qt libraries. I will need to investigate what is happening there.

**Comment by bkchr** [comment]
Okay, works now. I had some software in my user environment, sounds like: https://github.com/NixOS/nixpkgs/issues/30551

**Comment by bkchr** [comment]
@adisbladis @peterhoeg did someone of you tried this?

**Comment by peterhoeg** [comment]
I have not, no. And realistically won't these next few days.

**Comment by bkchr** [comment]
ping @adisbladis @ttuegel

**Comment by adisbladis** [comment]
I've been using this for the past few days :) Thanks!

**Pull request merged**
