### PR TITLE
Small nginx tweaks

### PR DESCRIPTION
**Pull request by vincentbernat**
###### Motivation for this change

 - reduce gzip compression in recommended settings (see commit message for details)
 - add 2 additional MIME types to be compressed (SVG and atom feeds)

These two changes are independent but I thought it would be silly to have two PR for such small changes. If one of these changes only is rejected, I'll rebase the PR to remove it.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by Mic92 — APPROVED** [review]
Both changes seems reasonable.

**Comment by Mic92** [comment]
@GrahamcOfBorg test nginx

**Comment by Mic92** [comment]
Feel free to add the urls to the gzip compression value.

**Comment by globin** [comment]
Thanks @vincentbernat

**Pull request merged**
