### PR TITLE
swaynotificationcenter: backport PR 296

### PR DESCRIPTION
**Pull request by aacebedo**
## Description of changes
 
Backport PR 296 from upstream to fix the loading of default config and style files

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aacebedo** [comment]
@PedroHLC  and @berbiche can you check this out?

**Comment by PedroHLC** [comment]
Can you mention here the issue/pr related to what you wanna fix?

**Comment by aacebedo** [comment]
> Can you mention here the issue/pr related to what you wanna fix?
Upsteam fixed this in https://github.com/ErikReider/SwayNotificationCenter/pull/296
After 0.9.0 release. 

I added the necessary to update correctly the default path in the derivation.

**Comment by PedroHLC** [comment]
> I added the necessary to update correctly the default path in the derivation.

So you tested if adding `https://patch-diff.githubusercontent.com/raw/ErikReider/SwayNotificationCenter/pull/296.patch` to the patches would be enough instead of moving us 10 commits into the unstable?

**Comment by aacebedo** [comment]
> > I added the necessary to update correctly the default path in the derivation.
> 
> So you tested if adding `https://patch-diff.githubusercontent.com/raw/ErikReider/SwayNotificationCenter/pull/296.patch` to the patches would be enough instead of moving us 10 commits into the unstable?
> 
> (Not trying to be aggressive, just asking as it sounds like a better solution)

Thanks for the edit of the initial message, I actually found the original one a bit aggressive indeed.

In the end, I tried to apply the PR patch, but it was not working, it would have required to get the other commits and thus defeated the purpose. I ended up backporting the fixes of the PR directly on the 0.9.0. Tell me if it seems correct to you

**Review by PedroHLC — APPROVED** [review]
> Tell me if it seems correct to you

It became super easy to review.

Diff LGTM

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
