### PR TITLE
staging-next 2022-10-28

### PR DESCRIPTION
**Pull request by vcunat**
- workflow docs: https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/195862

### CODE REVIEW

**Comment by vcunat** [comment]
So, let's start linux-only rebuilds now, trying to fix any larger regressions and then on November 1 we can add the critical openssl security fix and merge soon-ish aftewards.

_`*-darwin` builds most likely won't be finished when merging this to master, as openssl rebuilds stdenv for them and they rebuild much slower on Hydra than `*-linux` anyway._

**Comment by kirillrdy** [comment]
fix awsebcli https://github.com/NixOS/nixpkgs/pull/198400

cc @vcunat @mweinelt

**Comment by vcunat** [comment]
- [ ] `google-cloud-cpp` started failing: https://hydra.nixos.org/build/196748001
  /cc maintainer: @cpcloud. Related: #180138

**Comment by sternenseemann** [comment]
git update related fix for buf: https://github.com/NixOS/nixpkgs/pull/199015 (doesn't seem to have a lot (any?) reverse dependencies, so likely low priority).

**Pull request merged**
