### PR TITLE
pythonPackages.autologging: init at 1.2.1

### PR DESCRIPTION
**Pull request by Twey**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ma27** [comment]
The change itself is looking good, but may I ask why you didn't add yourself as maintainer? It's AFAIK not a hard rule, but I think it's preferable to attempt to have as many maintained packages as possible in the `master`.

**Comment by Twey** [comment]
Just because I forgot :)  Fixed.

**Comment by Ma27** [comment]
built locally, but I'd like to confirm that it works on different platforms as well, then it should be safe to merge :)

@GrahamcOfBorg build pythonPackages.autologging python3Packages.autologging

**Review by Ma27 — APPROVED** [review]

**Comment by Ma27** [comment]
thanks!

**Pull request merged**
