### PR TITLE
Iosevka: build from source, custom font sets

### PR DESCRIPTION
**Pull request by ttuegel**
### Motivation

Iosevka has many options to build custom font sets, but it must be built from source.

Based on #27573, but updated to build with Node 8 and support custom font sets.

### Testing

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] ~Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))~
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] ~Tested execution of all binary files (usually in `./result/bin/`)~
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
Note the "Details" link next to the failing "eval-package-list" check :)

**Comment by grahamc** [comment]
It will post a detail link for all but the overarching one. If one fails
though, it doesn’t attempt the remainder (as it is now. I could change
this) and the ones run with a prior version of the checker.

**Comment by orivej** [comment]
Note that this makes Iosevka unavaible on aarch64 Linux and Darwin because now it depends on otfcc which only supports x86/64 Linux.

**Comment by ttuegel** [comment]
> otfcc which only supports x86/64 Linux.

This is a mistake; otfcc should work on any platform.

**Comment by orivej** [comment]
I've enabled building Iosevka on Darwin in https://github.com/NixOS/nixpkgs/compare/6a23fb10...f557844c . Supporting aarch64 involves an additional challenge: [otfcc/premake5.lua](https://github.com/caryll/otfcc/blob/77134110/premake5.lua) has no provisions for this architecture. (I'm not going to take it upon myself.)

**Comment by ttuegel** [comment]
> Supporting aarch64 involves an additional challenge: otfcc/premake5.lua has no provisions for this architecture.

This would probably be simple... except that my aarch64 board is currently out of commission. I will re-add the fetch-only expression for platforms without otfcc.

**Pull request merged**
