### PR TITLE
lxd: 2.0.2 -> 2.12

### PR DESCRIPTION
**Pull request by bkchr**
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
Can you test this with sandboxing enabled? With such a great leap in versions, seems like good potential for new implicit dependencies & whatnot.

**Comment by bkchr** [comment]
Hi, I have done nox-review pr 25685.
I also activated the sandbox and builded the package in a sandbox.

**Comment by joachifm** [comment]
Thank you

**Comment by lzrski** [comment]
Hi! 

I realize PRs are not a place for support requests, but the resources on the subject seem very sparse, so I'll indulge myself into asking here anyway.

Are you aware of any beginner friendly walk-through of running LXC container (using LXD) on NixOS? I'm interested in more recent versions of LXD (> 2.3) with networking features. Basically I want to recreate [this setup](https://gist.github.com/lzrski/6a3fb8879bbdc6e81925daf5bba8e06c) from Ubuntu 16.04 into NixOS 17.03.

I'm very new to both LXC / LXD and NixOS (installed it for a first time this weekend).

Thanks in advance and sorry for spamming your PR ;-)

**Comment by bkchr** [comment]
Nope sorry. Is something not working?

**Comment by lzrski** [comment]
I can't start a container (neither as `root` or normal user).

Here is my `/etc/nixos/configuration.nix`:

```nix
{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];
  networking.hostName = "macbook-pro-nixos";
  networking.networkmanager.enable = true;

  # Open ports in the firewall.
  # networking.firewall.allowedTCPPorts = [ ... ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  # Or disable the firewall altogether.
  # networking.firewall.enable = false;

  virtualisation.lxd.enable = true;

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.extraUsers.tadeusz = {
    isNormalUser = true;
    uid = 1000;
    extraGroups = [ "wheel" "networkmanager" "lxd" ];
    shell = pkgs.zsh;
  };

  # The NixOS release to be compatible with for stateful data such as databases.
  system.stateVersion = "17.03";
}
```

I've left everything that can even remotely affect the LXD.
 
Here is what a shell log:

```sh
 lxc 20170802203206.290 INFO     lxc_seccomp - seccomp.c:parse_config_v2:418 - processing: .kexec_load errno 1.
            lxc 20170802203206.290 INFO     lxc_seccomp - seccomp.c:parse_config_v2:590 - Adding native rule for kexec_load action 327681.
            lxc 20170802203206.290 INFO     lxc_seccomp - seccomp.c:parse_config_v2:593 - Adding compat rule for kexec_load action 327681.
            lxc 20170802203206.290 INFO     lxc_seccomp - seccomp.c:parse_config_v2:418 - processing: .open_by_handle_at errno 1.
            lxc 20170802203206.290 INFO     lxc_seccomp - seccomp.c:parse_config_v2:590 - Adding native rule for open_by_handle_at action 327681.
            lxc 20170802203206.290 INFO     lxc_seccomp - seccomp.c:parse_config_v2:593 - Adding compat rule for open_by_handle_at action 327681.
            lxc 20170802203206.290 INFO     lxc_seccomp - seccomp.c:parse_config_v2:418 - processing: .init_module errno 1.
            lxc 20170802203206.290 INFO     lxc_seccomp - seccomp.c:parse_config_v2:590 - Adding native rule for init_module action 327681.
            lxc 20170802203206.290 INFO     lxc_seccomp - seccomp.c:parse_config_v2:593 - Adding compat rule for init_module action 327681.
            lxc 20170802203206.290 INFO     lxc_seccomp - seccomp.c:parse_config_v2:418 - processing: .finit_module errno 1.
            lxc 20170802203206.290 INFO     lxc_seccomp - seccomp.c:parse_config_v2:590 - Adding native rule for finit_module action 327681.
            lxc 20170802203206.290 INFO     lxc_seccomp - seccomp.c:parse_config_v2:593 - Adding compat rule for finit_module action 327681.
            lxc 20170802203206.290 INFO     lxc_seccomp - seccomp.c:parse_config_v2:418 - processing: .delete_module errno 1.
            lxc 20170802203206.290 INFO     lxc_seccomp - seccomp.c:parse_config_v2:590 - Adding native rule for delete_module action 327681.
            lxc 20170802203206.290 INFO     lxc_seccomp - seccomp.c:parse_config_v2:593 - Adding compat rule for delete_module action 327681.
            lxc 20170802203206.290 INFO     lxc_seccomp - seccomp.c:parse_config_v2:603 - Merging in the compat Seccomp ctx into the main one.
            lxc 20170802203206.290 INFO     lxc_conf - conf.c:run_script_argv:427 - Executing script "/nix/store/pns5q1wwyy2f0glsrpnwrc4304lclw2p-lxd-2.0.2-bin/bin/lxd callhook /var/lib/lxd 7 start" for container "ubuntu-container", config section "lxc".
            lxc 20170802203206.290 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:330 - Going to wait for pid 1779.
            lxc 20170802203206.291 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:349 - Trying to sync with child process.
            lxc 20170802203206.291 INFO     lxc_start - start.c:lxc_check_inherited:235 - Closed inherited fd: 3.
            lxc 20170802203206.291 INFO     lxc_start - start.c:lxc_check_inherited:235 - Closed inherited fd: 8.
            lxc 20170802203206.291 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:387 - Using pipe file descriptor 5 for monitord.
            lxc 20170802203206.299 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:364 - Successfully synced with child process.
            lxc 20170802203206.300 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:333 - Finished waiting on pid 1779.
            lxc 20170802203206.300 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:201 - using monitor socket name "lxc/d78a9d7e97b4b375//var/lib/lxd/containers" (length of socket name 44 must be <= 105)
            lxc 20170802203206.300 DEBUG    lxc_monitor - monitor.c:lxc_monitor_open:225 - opening monitor socket lxc/d78a9d7e97b4b375//var/lib/lxd/containers with len 44
            lxc 20170802203206.339 DEBUG    lxc_start - start.c:setup_signal_fd:273 - Set SIGCHLD handler with file descriptor: 5.
            lxc 20170802203206.339 INFO     lxc_confile - confile.c:config_idmap:1537 - read uid map: type u nsid 0 hostid 1000000 range 100000
            lxc 20170802203206.339 INFO     lxc_confile - confile.c:config_idmap:1537 - read uid map: type g nsid 0 hostid 1000000 range 100000
            lxc 20170802203206.339 DEBUG    console - console.c:lxc_console_peer_default:438 - process does not have a controlling terminal
            lxc 20170802203206.339 INFO     lxc_start - start.c:lxc_init:475 - Container "ubuntu-container" is initialized.
            lxc 20170802203206.339 DEBUG    lxc_start - start.c:__lxc_start:1325 - Not dropping CAP_SYS_BOOT or watching utmp.
            lxc 20170802203206.344 INFO     lxc_conf - conf.c:instantiate_veth:2709 - Retrieved mtu 1500 from vethK1CQKF
            lxc 20170802203206.344 ERROR    lxc_conf - conf.c:instantiate_veth:2728 - failed to attach 'veth722Y17' to the bridge 'lxdbr0': Operation not permitted
            lxc 20170802203206.352 ERROR    lxc_conf - conf.c:lxc_create_network:3021 - failed to create netdev
            lxc 20170802203206.352 ERROR    lxc_start - start.c:lxc_spawn:1099 - Failed to create the network.
            lxc 20170802203206.352 ERROR    lxc_start - start.c:__lxc_start:1354 - Failed to spawn container "ubuntu-container".
            lxc 20170802203206.352 INFO     lxc_conf - conf.c:run_script_argv:427 - Executing script "/nix/store/pns5q1wwyy2f0glsrpnwrc4304lclw2p-lxd-2.0.2-bin/bin/lxd callhook /var/lib/lxd 7 stop" for container "ubuntu-container", config section "lxc".
            lxc 20170802203206.371 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:177 - Command get_cgroup failed to receive response: Connection reset by peer.
            lxc 20170802203206.371 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:177 - Command get_cgroup failed to receive response: Connection reset by peer.
            lxc 20170802203206.372 INFO     lxc_confile - confile.c:config_idmap:1537 - read uid map: type u nsid 0 hostid 1000000 range 100000
            lxc 20170802203206.372 INFO     lxc_confile - confile.c:config_idmap:1537 - read uid map: type g nsid 0 hostid 1000000 range 100000
            lxc 20170802203219.573 INFO     lxc_confile - confile.c:config_idmap:1537 - read uid map: type u nsid 0 hostid 1000000 range 100000
            lxc 20170802203219.573 INFO     lxc_confile - confile.c:config_idmap:1537 - read uid map: type g nsid 0 hostid 1000000 range 100000
            lxc 20170802203219.577 INFO     lxc_confile - confile.c:config_idmap:1537 - read uid map: type u nsid 0 hostid 1000000 range 100000
            lxc 20170802203219.577 INFO     lxc_confile - confile.c:config_idmap:1537 - read uid map: type g nsid 0 hostid 1000000 range 100000


~ ⌚ 22:32:19
$ lxc network list                                                                                                                                                       ~
+--------+----------+---------+-------------+---------+
|  NAME  |   TYPE   | MANAGED | DESCRIPTION | USED BY |
+--------+----------+---------+-------------+---------+
| wlp3s0 | physical | NO      |             | 0       |
+--------+----------+---------+-------------+---------+

~ ⌚ 22:32:31
$ ifconfig                                                                                                                                                               ~
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 757  bytes 71143 (69.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 757  bytes 71143 (69.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vboxnet0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.56.1  netmask 255.255.255.0  broadcast 0.0.0.0
        ether 0a:00:27:00:00:00  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp3s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.43.212  netmask 255.255.255.0  broadcast 192.168.43.255
        inet6 fe80::cd15:744c:de86:ff16  prefixlen 64  scopeid 0x20<link>
        ether f4:5c:89:9f:d0:0d  txqueuelen 1000  (Ethernet)
        RX packets 1576  bytes 1230552 (1.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1323  bytes 152385 (148.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

I'm probably missing something very obvious - as I've mentioned I'm new to both technologies. One thing I've noticed is that there is no `lxdbr0` bridge network.

**Comment by bkchr** [comment]
Have you executed the command `lxd init`? 
See the following [tutorial](https://github.com/tych0/tycho.ws/blob/master/src/blog/2016/04/lxdbr0.md).

**Comment by lzrski** [comment]
Thanks. I'll try it in the evening.

But... is this a proper NixOS way? Seems quite imperative :grimacing:

**Comment by bkchr** [comment]
Not that I'm aware of. But after some experiments, I also gave up lxc and did not used it anymore. So, sorry.

**Comment by lzrski** [comment]
Thanks again for your attention here. I've opened a proper issue for that here: #27967

**Pull request merged**
