### PR TITLE
ocamlPackages.cstruct: 6.1.1 → 6.2.0

### PR DESCRIPTION
**Pull request by vbgl**
###### Description of changes

https://github.com/mirage/ocaml-cstruct/releases/tag/v6.2.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ulrikstrid** [comment]
Result of `nixpkgs-review pr 223540` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>185 packages built:</summary>
  <ul>
    <li>comby</li>
    <li>dune-release</li>
    <li>jackline</li>
    <li>libbap</li>
    <li>ligo</li>
    <li>liquidsoap</li>
    <li>ocamlPackages.arp</li>
    <li>ocamlPackages.asn1-combinators</li>
    <li>ocamlPackages.async_rpc_websocket</li>
    <li>ocamlPackages.awa</li>
    <li>ocamlPackages.awa-lwt</li>
    <li>ocamlPackages.awa-mirage</li>
    <li>ocamlPackages.bap</li>
    <li>ocamlPackages.bls12-381</li>
    <li>ocamlPackages.bls12-381-signature</li>
    <li>ocamlPackages.bonsai</li>
    <li>ocamlPackages.ca-certs</li>
    <li>ocamlPackages.ca-certs-nss</li>
    <li>ocamlPackages.callipyge</li>
    <li>ocamlPackages.carton</li>
    <li>ocamlPackages.carton-git</li>
    <li>ocamlPackages.carton-lwt</li>
    <li>ocamlPackages.chacha</li>
    <li>ocamlPackages.cohttp-async</li>
    <li>ocamlPackages.cohttp-lwt-unix</li>
    <li>ocamlPackages.cohttp-mirage</li>
    <li>ocamlPackages.cohttp_async_websocket</li>
    <li>ocamlPackages.cohttp_static_handler</li>
    <li>ocamlPackages.conduit</li>
    <li>ocamlPackages.conduit-async</li>
    <li>ocamlPackages.conduit-lwt</li>
    <li>ocamlPackages.conduit-lwt-unix</li>
    <li>ocamlPackages.conduit-mirage</li>
    <li>ocamlPackages.cooltt</li>
    <li>ocamlPackages.cow</li>
    <li>ocamlPackages.cstruct</li>
    <li>ocamlPackages.cstruct-async</li>
    <li>ocamlPackages.cstruct-lwt</li>
    <li>ocamlPackages.cstruct-sexp</li>
    <li>ocamlPackages.cstruct-unix</li>
    <li>ocamlPackages.curly</li>
    <li>ocamlPackages.data-encoding</li>
    <li>ocamlPackages.dbf</li>
    <li>ocamlPackages.digestif</li>
    <li>ocamlPackages.dns</li>
    <li>ocamlPackages.dns-certify</li>
    <li>ocamlPackages.dns-cli</li>
    <li>ocamlPackages.dns-client</li>
    <li>ocamlPackages.dns-client-lwt</li>
    <li>ocamlPackages.dns-client-mirage</li>
    <li>ocamlPackages.dns-mirage</li>
    <li>ocamlPackages.dns-resolver</li>
    <li>ocamlPackages.dns-server</li>
    <li>ocamlPackages.dns-stub</li>
    <li>ocamlPackages.dns-tsig</li>
    <li>ocamlPackages.dnssec</li>
    <li>ocamlPackages.eliom</li>
    <li>ocamlPackages.eqaf</li>
    <li>ocamlPackages.erm_xmpp</li>
    <li>ocamlPackages.ethernet</li>
    <li>ocamlPackages.ezjsonm</li>
    <li>ocamlPackages.git</li>
    <li>ocamlPackages.git-mirage</li>
    <li>ocamlPackages.git-paf</li>
    <li>ocamlPackages.git-unix</li>
    <li>ocamlPackages.graphql-cohttp</li>
    <li>ocamlPackages.h2</li>
    <li>ocamlPackages.happy-eyeballs-lwt</li>
    <li>ocamlPackages.happy-eyeballs-mirage</li>
    <li>ocamlPackages.hex</li>
    <li>ocamlPackages.hkdf</li>
    <li>ocamlPackages.http-mirage-client</li>
    <li>ocamlPackages.io-page</li>
    <li>ocamlPackages.ipaddr-cstruct</li>
    <li>ocamlPackages.ipaddr-sexp</li>
    <li>ocamlPackages.irmin</li>
    <li>ocamlPackages.irmin-chunk</li>
    <li>ocamlPackages.irmin-containers</li>
    <li>ocamlPackages.irmin-fs</li>
    <li>ocamlPackages.irmin-git</li>
    <li>ocamlPackages.irmin-graphql</li>
    <li>ocamlPackages.irmin-http</li>
    <li>ocamlPackages.irmin-mirage</li>
    <li>ocamlPackages.irmin-mirage-git</li>
    <li>ocamlPackages.irmin-mirage-graphql</li>
    <li>ocamlPackages.irmin-pack</li>
    <li>ocamlPackages.irmin-test</li>
    <li>ocamlPackages.irmin-tezos</li>
    <li>ocamlPackages.jwto</li>
    <li>ocamlPackages.letsencrypt</li>
    <li>ocamlPackages.letsencrypt-app</li>
    <li>ocamlPackages.letsencrypt-dns</li>
    <li>ocamlPackages.letsencrypt-mirage</li>
    <li>ocamlPackages.lustre-v6</li>
    <li>ocamlPackages.macaddr-cstruct</li>
    <li>ocamlPackages.macaddr-sexp</li>
    <li>ocamlPackages.macaque</li>
    <li>ocamlPackages.magic-trace</li>
    <li>ocamlPackages.mec</li>
    <li>ocamlPackages.mimic</li>
    <li>ocamlPackages.mimic-happy-eyeballs</li>
    <li>ocamlPackages.mirage-block</li>
    <li>ocamlPackages.mirage-block-combinators</li>
    <li>ocamlPackages.mirage-block-ramdisk</li>
    <li>ocamlPackages.mirage-block-unix</li>
    <li>ocamlPackages.mirage-bootvar-xen</li>
    <li>ocamlPackages.mirage-channel</li>
    <li>ocamlPackages.mirage-console</li>
    <li>ocamlPackages.mirage-console-unix</li>
    <li>ocamlPackages.mirage-crypto</li>
    <li>ocamlPackages.mirage-crypto-ec</li>
    <li>ocamlPackages.mirage-crypto-pk</li>
    <li>ocamlPackages.mirage-crypto-rng</li>
    <li>ocamlPackages.mirage-crypto-rng-async</li>
    <li>ocamlPackages.mirage-crypto-rng-lwt</li>
    <li>ocamlPackages.mirage-crypto-rng-mirage</li>
    <li>ocamlPackages.mirage-flow</li>
    <li>ocamlPackages.mirage-flow-combinators</li>
    <li>ocamlPackages.mirage-flow-unix</li>
    <li>ocamlPackages.mirage-fs</li>
    <li>ocamlPackages.mirage-nat</li>
    <li>ocamlPackages.mirage-net</li>
    <li>ocamlPackages.mirage-net-xen</li>
    <li>ocamlPackages.mirage-profile</li>
    <li>ocamlPackages.mirage-protocols</li>
    <li>ocamlPackages.mirage-random</li>
    <li>ocamlPackages.mirage-random-test</li>
    <li>ocamlPackages.mirage-stack</li>
    <li>ocamlPackages.mirage-vnetif</li>
    <li>ocamlPackages.mirage-xen</li>
    <li>ocamlPackages.mrmime</li>
    <li>ocamlPackages.mustache</li>
    <li>ocamlPackages.netchannel</li>
    <li>ocamlPackages.ocsigen-start</li>
    <li>ocamlPackages.ocsigen-toolkit</li>
    <li>ocamlPackages.ocsigen_server</li>
    <li>ocamlPackages.ocsipersist</li>
    <li>ocamlPackages.ocsipersist-pgsql</li>
    <li>ocamlPackages.ocsipersist-sqlite</li>
    <li>ocamlPackages.opium</li>
    <li>ocamlPackages.otr</li>
    <li>ocamlPackages.paf</li>
    <li>ocamlPackages.paf-cohttp</li>
    <li>ocamlPackages.paf-le</li>
    <li>ocamlPackages.pbkdf</li>
    <li>ocamlPackages.pcap-format</li>
    <li>ocamlPackages.pgocaml</li>
    <li>ocamlPackages.pgocaml_ppx</li>
    <li>ocamlPackages.piaf</li>
    <li>ocamlPackages.plotkicadsch</li>
    <li>ocamlPackages.ppx_cstruct</li>
    <li>ocamlPackages.ppx_deriving_yaml</li>
    <li>ocamlPackages.randomconv</li>
    <li>ocamlPackages.resto-cohttp-self-serving-client</li>
    <li>ocamlPackages.resto-cohttp-server</li>
    <li>ocamlPackages.secp256k1-internal</li>
    <li>ocamlPackages.shared-memory-ring</li>
    <li>ocamlPackages.shared-memory-ring-lwt</li>
    <li>ocamlPackages.tar</li>
    <li>ocamlPackages.tar-unix</li>
    <li>ocamlPackages.tcpip</li>
    <li>ocamlPackages.telegraml</li>
    <li>ocamlPackages.tezos-base58</li>
    <li>ocamlPackages.tezos-bls12-381-polynomial</li>
    <li>ocamlPackages.tezos-plompiler</li>
    <li>ocamlPackages.tezos-plonk</li>
    <li>ocamlPackages.tls</li>
    <li>ocamlPackages.tls-async</li>
    <li>ocamlPackages.tls-lwt</li>
    <li>ocamlPackages.tls-mirage</li>
    <li>ocamlPackages.uecc</li>
    <li>ocamlPackages.vchan</li>
    <li>ocamlPackages.wayland</li>
    <li>ocamlPackages.x509</li>
    <li>ocamlPackages.xenstore</li>
    <li>ocamlPackages.xenstore-tool</li>
    <li>ocamlPackages.xenstore_transport</li>
    <li>ocamlPackages.yaml</li>
    <li>ocamlPackages.yaml-sexp</li>
    <li>python310Packages.bap</li>
    <li>python310Packages.bap.dist</li>
    <li>python311Packages.bap</li>
    <li>python311Packages.bap.dist</li>
    <li>soupault</li>
    <li>wayland-proxy-virtwl</li>
  </ul>
</details>

**Review by ulrikstrid — APPROVED** [review]
Looks good, do you want more reviewers to approve @vbgl? Otherwise I'm OK merging this

**Review by sternenseemann — APPROVED** [review]

**Comment by sternenseemann** [comment]
Any reason to drop `strictDeps`? It wasn't doing much since it's unlikely a reference to `pkg-config` persists, but seems odd.

**Comment by vbgl** [comment]
`buildDunePackage` sets `strictDeps` already; I’ve just removed something redundant.

**Pull request merged**
