### PR TITLE
zitadel: 2.40.3 -> 2.42.10, build fixes and cleanup

### PR DESCRIPTION
**Pull request by Sorixelle**
## Description of changes

- Update ZITADEL to 2.42.10
- Modify derivation to use `preBuild` instead of overriding `buildGoModule`'s `buildPhase` - turns out this wasn't necessary
- Patch the console portion to use local protobuf plugins instead of Buf's [remote plugins](https://buf.build/docs/bsr/remote-plugins/usage). This was causing hash changes in the generated protobuf code (thanks to #277136 for calling this issue out!)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Sorixelle** [comment]
Result of `nixpkgs-review pr 277643` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>protoc-gen-js</li>
    <li>zitadel</li>
  </ul>
</details>

**Comment by Sorixelle** [comment]
Putting this one in draft mode while I figure out the darwin failures for `protoc-gen-js`

**Comment by commandodev** [comment]
I've just stumbled across this issue and have added this branch as an overlay. The package now builds fine - thanks for fixing :-)

**Comment by mannp** [comment]
> Putting this one in draft mode while I figure out the darwin failures for `protoc-gen-js`

The current build doesn't build at the moment, so any merge would be a great help :)

Thanks in advance.

**Comment by bddvlpr** [comment]
Result of `nixpkgs-review pr 277643` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>protoc-gen-js</li>
    <li>zitadel</li>
  </ul>
</details>

**Review by bddvlpr — APPROVED** [review]

**Comment by OPNA2608** [comment]
```
error: hash mismatch in fixed-output derivation '/nix/store/p42b90w9sz07d702fg3xy6fn80p3nyi3-zitadel-console-buf-generated.drv':
         specified: sha256-h/5K6PvEFyjzS5p7SfuDIk91TkN1iPc+iXor8T/QSeE=
            got:    sha256-3I+O0D3xYjDaBUsobTwhXjwsLpJbjpRKVaHVlql+igg=
```

**Comment by h3ndrik** [comment]
Does anyone actively use that and have a working config / some place to point to?
The package builds fine for me but I can't get it to run. CockroachDB somehow wouldn't work and I've given up on that since it's not free software anyways. I set up postgres and it seems to connect fine but Zitadel is stuck at the migration.

**Comment by domenkozar** [comment]
It seems like the hash still fails.

**Comment by domenkozar** [comment]
You can use diffoscope to see the difference between the two nix store derivations.

**Pull request merged**
