### PR TITLE
restya-board: 0.6 -> 0.6.6

### PR DESCRIPTION
**Pull request by uvNikita**
###### Motivation for this change
The current version is 1 year old and there was a lot of improvements implemented recently, see https://restya.com/board/changelog.

I'm not sure if we should do anything to invoke database migration in the nixos module. 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by uvNikita** [comment]
CC @ts468 @c0bw3b

**Review by coretemp — APPROVED** [review]

**Comment by uvNikita** [comment]
There is a script in the repository that seems to handle upgrades in some way, not sure if we can reuse it here: https://github.com/RestyaPlatform/board/blob/dev/restyaboard.sh

**Comment by coretemp** [comment]
Such upgrades are to be managed in NixOS modules, not in the packages.

**Review by ryantm — CHANGES_REQUESTED** [review]
The consensus is that a migration strategy should be in place in the NixOS module before this is merged.

**Comment by c0bw3b** [comment]
(to mirror exchanges in #74763)
I'm ok with the service module doing no transformation and let the admin deal with it, as long as it's clearly stated in a release note

**Comment by aanderse** [comment]
Closing in favor of https://github.com/NixOS/nixpkgs/pull/74888.

**Pull request closed without merging**
