### PR TITLE
Revert "lib.getExe: Do not make assumptions about the main program"

### PR DESCRIPTION
**Pull request by gytis-ivaskevicius**
A possible resolution to https://github.com/NixOS/nixpkgs/pull/247115

### CODE REVIEW

**Comment by R-VdP** [comment]
PRs to add `meta.mainProgram` to many packages have already been merged, they will hit the unstable channel soon.

The whole idea of the warning (and maybe at some point error) is to have people add `meta.mainProgram` immediately in the future. So I don't really see the point of this PR.

**Review by roberth — CHANGES_REQUESTED** [review]
Strange error messages tend to be caused by assumptions in generic code. This is one of them. Removing the assumption improved the predictability of the code and the quality of error messages at the temporary cost of some inconvenience.

I sure hope we can look past the inconvenience in order to make a substantial and permanent improvement in robustness.

**Comment by gytis-ivaskevicius** [comment]
> PRs to add meta.mainProgram to many packages have already been merged, they will hit the unstable channel soon.

May I have a link to this PR? I see only a few PRs where this was addedhttps://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+mainProgram+is%3Aclosed

I upgraded nixpkgs to master and got 6 warnings of `lib.getExe` being used, `lib.getExe` in this evaluation was used 7 times. Somehow I got a feeling that this is going to be the same ratio in other projects of mine

> Strange error messages tend to be caused by assumptions in generic code. This is one of them. Removing the assumption improved the predictability of the code and the quality of error messages at the temporary cost of some inconvenience.

As long as this is implemented more or less everywhere. I am more than happy to see this patch

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/248895

**Pull request closed without merging**
