### PR TITLE
Remove upstart layer

### PR DESCRIPTION
**Pull request by globin**
This removes the obsolete layer for backward compat with old `jobs.*` services.

I tried to convert everything keeping the same behaviour by trying to understand the wrapper module which had been in place, please review that.

I removed `services.gvpe.{start,stop}On` options as these used upstart specific syntax.

I removed the fuppes package and service as they were marked as broken or commented in the module-list

### CODE REVIEW

**Comment by domenkozar** [comment]
Amazing work. cc @edolstra 

We better merge this fast before merge conflicts arise

**Comment by copumpkin** [comment]
:+1: :+1: :+1: :+1:

**Comment by domenkozar** [comment]
fixes #11745

**Comment by edolstra** [comment]
:beer:

**Comment by copumpkin** [comment]
Let's press the big green button and fix anything that goes wrong? Besides, Travis says it's good, so clearly we're safe to go :sweat_smile:

**Comment by nbp** [comment]
@globin I faced this issue today, and the release notes where quite unhelpful on how one should transliterate the `jobs` attribute set into the `systemd.services`.  Could we improve the release notes to include examples, and potentially link to external documentation?

For example, I noticed that the `daemonType` option does not exists anymore, but there is not documentation to highlight how I should rewrite my module.

```
The option `systemd.services.ircSession.daemonType' defined in `/nix/store/6s6q20ylbsk519ra33yvifx3f5qh9539-nixos-16.09pre78286.0bf8a1a/nixos/nixpkgs/nixos/modules/rename.nix' does not exist.
```

**Comment by globin** [comment]
Generally I used https://github.com/NixOS/nixpkgs/blob/d89454bb79d2495df903fc91d8c7a74ebdcc9cc3/nixos/modules/system/upstart/upstart.nix as documentation when rewriting the stuff, so that probably is your best bet at the moment.. Although more docs definitely wouldn't hurt and I'll try to write something up if no one beats me but I'm quite busy with other stuff right now.

**Pull request merged**
