### PR TITLE
nix-generate-from-cpan: large refactor

### PR DESCRIPTION
**Pull request by rycee**
This commit includes a substantial refactoring of `nix-generate-from-cpan`. This somewhat simplifies the code through the use of the CPAN::Meta module while adding the following features:
- The program now takes an optional maintainer on the command line that is subsequently added into the generated package.
- An attempt is made to convert the license specified inside the META.json or META.yaml file to a license in `stdenv.lib.licenses`.
- An attempt is made to disambiguate attribute names of packages whose package name is a reserved word in Nix (or known to be bound in the perlPackage expression).

The latter feature really only applies to the `if` package for now but I added a few additional keywords and such for completeness sake. In any case, the current (version 1) `nix-generate-from-cpan` produces the package

``` nix
{
  if = buildPerlPackage {
    name = "if-0.0606";
    src = fetchurl {
      url = mirror://cpan/authors/id/R/RJ/RJBS/if-0.0606.tar.gz;
      sha256 = "63d69282d6c4c9e76370b78d770ca720cea88cfe5ee5b612709240fc6078d50e";
    };
    meta = {
      description = "C<use> a Perl module if a condition holds (also can C<no> a module)";
      license = "perl";
    };
  };
}
```

while this proposed version 2 produces the package

``` nix
{
  if_ = buildPerlPackage rec {
    name = "if-0.0606";
    src = fetchurl {
      url = "mirror://cpan/authors/id/R/RJ/RJBS/${name}.tar.gz";
      sha256 = "63d69282d6c4c9e76370b78d770ca720cea88cfe5ee5b612709240fc6078d50e";
    };
    meta = {
      description = "C<use> a Perl module if a condition holds (also can C<no> a module)";
      license = with stdenv.lib.licenses; [ artistic1 gpl1Plus ];
      maintainers = [ maintainers.rycee ];
    };
  };
}
```

if the the command line option `-m rycee` was given. This more closely reflects the current de-facto style for Perl module packages.

Finally, due to the size of these changes I have also added myself as a co-maintainer of the package.

CC @edolstra as the current maintainer

### CODE REVIEW

**Comment by pSub** [comment]
I have just glanced over the change. One thing I noticed is that in your example `maintainers` is not in scope.

**Comment by rycee** [comment]
@pSub, believe it or not but it really is in scope since maintainers is [inherited from stdenv](https://github.com/NixOS/nixpkgs/blob/499be4736fdcb17ab5f70c9610a7b7df623e9c60/pkgs/top-level/perl-packages.nix#L14).

**Comment by pSub** [comment]
Oh, you are right.

**Comment by rycee** [comment]
Hi, any chance of getting this merged? I've used the updated script for a while now and have had no issues.

**Comment by bjornfor** [comment]
CC @edolstra.

**Comment by spwhitt** [comment]
@rycee Attribute name shouldn't need to be disambiguated if you just put them in quotes. For example:

```
"if" = buildPerlPackage {
...
```

This is the approach taken by haskellPackages, among others: https://raw.githubusercontent.com/NixOS/nixpkgs/master/pkgs/development/haskell-modules/hackage-packages.nix

**Comment by rycee** [comment]
@spwhitt, that's neat. But is it possible to refer to such attributes directly or must it be done through the `self` variable? For example, if we have `"if" = buildPerlPackage { … }` and another package refers to it then I think it'll need `propagatedBuildInputs = [ self."if" ]` or is there some more straight-forward way?

In any case, it wouldn't be difficult to make this happen in the script but is there any particular benefit to it compared to simply appending `_` to the attribute name?

**Comment by rycee** [comment]
@spwhitt, I've implemented something like what you suggested. The script now generates package expressions where the attribute name is quoted. I use the `self."XYZ"` format only for those attribute names that are Nix keywords. So the `if` package is now generated as
```nix
{
  "if" = buildPerlPackage rec {
    name = "if-0.0606";
    src = fetchurl {
      url = "mirror://cpan/authors/id/R/RJ/RJBS/${name}.tar.gz";
      sha256 = "63d69282d6c4c9e76370b78d770ca720cea88cfe5ee5b612709240fc6078d50e";
    };
    meta = {
      description = "C<use> a Perl module if a condition holds (also can C<no> a module)";
      license = with stdenv.lib.licenses; [ artistic1 gpl1Plus ];
      maintainers = [ maintainers.rycee ];
    };
  };
}
```
and the CGI package, which depends on if is now generated as
```nix
{
  "CGI" = buildPerlPackage rec {
    name = "CGI-4.25";
    src = fetchurl {
      url = "mirror://cpan/authors/id/L/LE/LEEJO/${name}.tar.gz";
      sha256 = "efb3e5235ada6a91f97ca2905399a686bedea60f6b525e52f4a147baff4f131a";
    };
    propagatedBuildInputs = [ HTMLParser self."if" ];
    meta = {
      homepage = https://metacpan.org/module/CGI;
      description = "Handle Common Gateway Interface requests and responses";
      license = with stdenv.lib.licenses; [ artistic1 gpl1Plus ];
      maintainers = [ maintainers.rycee ];
    };
  };
}
```

**Comment by rycee** [comment]
Hi everybody, anything further I can do to get this merged?

**Comment by rycee** [comment]
Thanks @zimbatm!

**Pull request merged**
