### PR TITLE
czkawka-full: "init"

### LINKED ISSUE #339308: czkawka - missing ffmpeg dependency (used for comparing videos)
### Describe the bug
The czkawka package is missing ffmpeg as a dependency.
https://github.com/NixOS/nixpkgs/blob/6cc3e274c947096556c57d2b05dad5acda395b74/pkgs/by-name/cz/czkawka/package.nix

If ffmpeg is not found you get this error when trying to compare video files:
```
############### ERRORS(2) ###############
Cannot find proper installation of FFmpeg
Similar Videos don't work currently with snap, if you want help look at - ⁨https://github.com/snapcrafters/ffmpeg/issues/73⁩
```
Ignore the snap part, it throws this error when it can't find ffmpeg, regardless if snap or not.

### Steps To Reproduce
1. Don't have ffmpeg installed on you system.
2. Try comparing videos in czkawka
3. czkawka throws error
4. Install ffmpeg
5. No error. Just works.

### Expected behavior
No error. Just works.

### Additional context
First issue I've reported here, hopefully I'm doing this right. 

### Notify maintainers
@AndersonTorres 
@yanganto 
@0x4A6F 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.46, NixOS, 24.05 (Uakari), 24.05.4169.797f7dc49e0b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by AndersonTorres**
## Description of changes

Closes https://github.com/NixOS/nixpkgs/issues/339308

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by AndersonTorres** [comment]
@edermats32 can you please test it?

**Comment by 0x4A6F** [comment]
Result of `nixpkgs-review pr 339359` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>czkawka</li>
    <li>czkawka-full</li>
  </ul>
</details>

**Comment by edermats32** [comment]
> @edermats32 can you please test it?

Sorry for taking so long to respond, didn't see you tagged me until now.
Anyway, I'm pretty new to Nix and Git in general.
How exactly do I test it?

Do i clone the nixpkgs repo and then run:

`git fetch origin pull/339359/head:pr-339359` 
`git checkout pr-339359`
`nix-build -A czkawka-full`
`nix-shell -p nixpkgs-review --run "nixpkgs-review pr 339359"`

and then test run the binary?

I did some research but didn't find a straight forward answer.
It might be me not being familiar enough with nix or just being blind though.

**Comment by 0x4A6F** [comment]
```
# in checkout of nixpkgs repo:
nix-shell -p nixpkgs-review --run "nixpkgs-review pr 339359"
./results/czkawka-full/bin/czkawka_gui
```

**Pull request merged**
