### PR TITLE
taglib: 0.13.0 -> 0.13.1

### PR DESCRIPTION
**Pull request by trofi**
Changes: https://github.com/taglib/taglib/releases/tag/v1.13.1

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by trofi** [comment]
Needs a `.pc` fix:

```
       > It is very likely that paths are being joined improperly.
       > ex: "${prefix}/@CMAKE_INSTALL_LIBDIR@" should be "@CMAKE_INSTALL_FULL_LIBDIR@"
       > Please see https://github.com/NixOS/nixpkgs/issues/144170 for more details.
```

**Comment by trofi** [comment]
The prefix was added in https://github.com/taglib/taglib/commit/967c0eefedcf7dea71832400791bed7246a41299 assuming relative paths.

**Comment by wineee** [comment]
A workaround is:
https://github.com/NixOS/nixpkgs/blob/66ce081fafa2dca0038006ec7c6482d7a11d13d8/pkgs/development/libraries/zydis/zycore.nix#L22-L23

**Comment by trofi** [comment]
Great suggestion! Stole as it. Ready to review.

**Comment by trofi** [comment]
Filed upstream issue as https://github.com/taglib/taglib/issues/1098

**Comment by trofi** [comment]
Added a link to upstream issue into the comment nearby the workaround.

**Pull request merged**
