### PR TITLE
freetube: 0.18.0 -> 0.19.0

### PR DESCRIPTION
**Pull request by LAURAilway**
## Description of changes
freetube: 0.18.0 -> 0.19.0
https://github.com/FreeTubeApp/FreeTube/releases/tag/v0.19.0-beta

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by natsukium** [comment]
Thanks for your contribution!

Would you please read CONTRIBUTING.md (especially https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions) and rewrite your commit message?
Thanks.

**Comment by LAURAilway** [comment]
> Thanks for your contribution!
> 
> Would you please read CONTRIBUTING.md (especially https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions) and rewrite your commit message? Thanks.

Like this?

**Comment by natsukium** [comment]
That's great.
Could you change the commit message as well?

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 250484` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>freetube</li>
  </ul>
</details>

**Comment by LAURAilway** [comment]
> That's great. Could you change the commit message as well?

Is this what you meant? (Sorry, first commit and very tired)

**Comment by natsukium** [comment]
Don't worry.

I think this page is helpful for you.
https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

The commit message is what is shown [here](https://github.com/NixOS/nixpkgs/pull/250484/commits) as `Updated freetube derivation to version 0.19.0`.
To change it to `freetube: 0.18.0 -> 0.19.0`, please execute `git commit --amend` on your local repository.

**Review by natsukium — APPROVED** [review]
LGTM, thanks!

**Comment by absidue** [comment]
Hi I'm one of the people on the FreeTube team and 3 people (including the author of this pull request) have reported that your FreeTube package is broken, but don't have issues using our official releases: https://github.com/FreeTubeApp/FreeTube/issues/3953.

I don't know much about NixOS and it's packaging, however looking at your FreeTube packaging file, it looks like you are extracting our AppImage that was built with/for Electron 22.3.18 but running it with your own much newer Electron version.

**Comment by absidue** [comment]
The reason I suspect the Electron mismatch is the problem, is that the unofficial AUR package had issues in the past, that were caused by using a different version of Electron to upstream.

**Comment by ryneeverett** [comment]
It would be easy enough to switch from `electron` to `electron_22`, but I can't reproduce the reported bugs on wayland+sway.

**Comment by LAURAilway** [comment]
> The reason I suspect the Electron mismatch is the problem, is that the unofficial AUR package had issues in the past, that were caused by using a different version of Electron to upstream.

Thanks for the suggestion, sould be fixed by #252061

**Comment by natsukium** [comment]
It works on my Weston (WSL) regardless of the version of electron.
Does pinning electron to 22 actually fix the reported bug?

**Comment by LAURAilway** [comment]
> It works on my Weston (WSL) and hyprland regardless of the version of electron. Does pinning electron to 22 actually fix the reported bug?

It does fix it on my end, I don't have anyone else to test it tho

**Pull request merged**
