### PR TITLE
gdal: introduce a gdalMinimal variant with a smaller closure size

### PR DESCRIPTION
**Pull request by thoughtpolice**
## Description of changes

This is intended to reduce the support burden and closure size of using `gdal`; in contexts like PostGIS, it's possible to expose GDAL (and the one quadrillion lines of code it pulls in) through PostgreSQL. This isn't always desireable; an overlay may want to make some features optional. And even ignoring that, `gdal` is currently incredibly bloated and depends on nearly everything under the sun.

`gdal` versus `gdalMinimal` yields a closure size reduction from 1.1GiB to 430MiB:

```
austin@GANON:~/src/nixpkgs$ nix path-info -Srh ./result | tail -1
/nix/store/g6yblqa0gb1n3s5ndm628fndd0acn4dd-gdal-3.7.1                     1.1G
austin@GANON:~/src/nixpkgs$ nix path-info -Srh ./result-2 | tail -1
/nix/store/81i50vd3i5hs8jkkwqyp257y98jjkjqp-gdal-3.7.1                   434.1M
austin@GANON:~/src/nixpkgs$ 
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
I was doing this as well a while back for work but never finalized it. Will definitely use it! :+1: 

The remaining list of dependencies, are they all required or you stopped grouping those? I imagine netcdf not to be a required dependency.

**Comment by FRidh** [comment]
Having a separate output for `bin` removes Python as runtime dependency for when it is used as library.

**Review by FRidh — APPROVED** [review]

**Comment by thoughtpolice** [comment]
> The remaining list of dependencies, are they all required or you stopped grouping those? I imagine netcdf not to be a required dependency.

No, the ones I have now were just the really big easy wins from running `nix why-depends` a lot. :) If we can get even more size reduction, I'll keep trying!

**Comment by thoughtpolice** [comment]
Pulling out netcdf and armadillo brought it down to 270MiB! I think we can call that good for a first cut in terms of size, at least.

```
austin@GANON:~/src/nixpkgs$ nix path-info -Srh ./result-2 | tail -1
/nix/store/b6s4g7ajpky5fb0m03h4xa469yi6n74l-gdal-3.7.1                   273.2M
```

**Comment by FRidh** [comment]
Nice work, thanks.

Now I am really curious though why there is a cycle with `python3`. Getting rid of that one by having it only in `bin` would be a big win as well.

**Comment by thoughtpolice** [comment]
Yeah, I'll open an issue for that so we don't lose track of it; good idea.

**Comment by imincik** [comment]
I like the idea of having configurable GDAL. Thank you very much for this work.

**Pull request merged**
