### PR TITLE
erlang: 24.3.4.13 -> 24.3.4.14 25.3.2.6 -> 25.3.2.7 26.1.1 -> 26.1.2

### PR DESCRIPTION
**Pull request by c4710n**
## Description of changes

This aims to fix the issues on macOS 14 Sonoma, which has been fixed and backported to main versions.

* https://github.com/NixOS/nixpkgs/issues/258100
* https://github.com/NixOS/nixpkgs/issues/257880 (already closed, but issue exist still.)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

## Maintainer pings
cc @ankhers @Br1ght0ne @DianaOlympos @gleber @happysalada @minijackson @yurrriq

### CODE REVIEW

**Comment by happysalada** [comment]
Hey, thanks a lot for the fix !

Could you split it in three commits, one per major version ? Just to have more clarity on the commit names and also to be able to identify and revert quickly if something breaks on only one version.

**Comment by c4710n** [comment]
done.

**Comment by ankhers** [comment]
The change looks alright. But I don't have a Mac to test on.

**Comment by c4710n** [comment]
I tested them with following commands on macOS 14 in a dumb way:
```console
$ nix build .#legacyPackages.aarch64-darwin.erlang_24
$ ./result/bin/erl # run successfully

$ nix build .#legacyPackages.aarch64-darwin.erlang_25
$ ./result/bin/erl # run successfully

$ nix build .#legacyPackages.aarch64-darwin.erlang_26
$ ./result/bin/erl # run successfully
```

I think that would be enough.

**Pull request merged**
