### PR TITLE
buildbot: 0.9.11 -> 0.9.15.post1

### PR DESCRIPTION
**Pull request by lopsided98**
###### Motivation for this change

Updates buildbot to 0.9.15.post1.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
cc maintainers @nand0p @ryansydnor

**Review by FRidh — APPROVED** [review]

**Comment by adisbladis** [comment]
@GrahamcOfBorg build buildbot

**Comment by lopsided98** [comment]
Oops, it looks like one of my overlays disabled the tests, so I didn't see these failures. I'm really busy this week, so I'll look into this over the weekend.

**Comment by lopsided98** [comment]
The problem seems to be that `buildbot` runs tests that require `buildbot-pkg` to be available. `buildbot-pkg` is currently only used by the plugins, and is not a real package (the derivation is defined in a `let` block in `plugins.nix`).

I moved `buildbot-pkg` to its own file and added it as a `buildInput` of buildbot. This fixed the tests, but introduced a new problem, seemingly related to how buildbot_pkg monkey patches `os.listdir`

This is the current error, which I can't find a way to fix:
```
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 556, in <module>
    setup(**setup_args)
  File "/nix/store/a4zb290zkx8avpand4a58ndci8ppczik-python2.7-bootstrapped-pip-9.0.1/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/nix/store/87l8l9w3x8saxqz9sfcfw2i3jiilmxfi-python-2.7.14/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/nix/store/87l8l9w3x8saxqz9sfcfw2i3jiilmxfi-python-2.7.14/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/nix/store/87l8l9w3x8saxqz9sfcfw2i3jiilmxfi-python-2.7.14/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/nix/store/a4zb290zkx8avpand4a58ndci8ppczik-python2.7-bootstrapped-pip-9.0.1/lib/python2.7/site-packages/setuptools/command/test.py", line 226, in run
    self.run_tests()
  File "/nix/store/87l8l9w3x8saxqz9sfcfw2i3jiilmxfi-python-2.7.14/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/nix/store/a4zb290zkx8avpand4a58ndci8ppczik-python2.7-bootstrapped-pip-9.0.1/lib/python2.7/site-packages/setuptools/command/test.py", line 171, in project_on_sys_path
    working_set.__init__()
  File "/nix/store/a4zb290zkx8avpand4a58ndci8ppczik-python2.7-bootstrapped-pip-9.0.1/lib/python2.7/site-packages/pkg_resources/__init__.py", line 650, in __init__
    self.add_entry(entry)
  File "/nix/store/a4zb290zkx8avpand4a58ndci8ppczik-python2.7-bootstrapped-pip-9.0.1/lib/python2.7/site-packages/pkg_resources/__init__.py", line 706, in add_entry
    for dist in find_distributions(entry, True):
  File "/nix/store/a4zb290zkx8avpand4a58ndci8ppczik-python2.7-bootstrapped-pip-9.0.1/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2032, in find_on_path
    entries = safe_listdir(path_item)
  File "/nix/store/a4zb290zkx8avpand4a58ndci8ppczik-python2.7-bootstrapped-pip-9.0.1/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2091, in safe_listdir
    return os.listdir(path)
  File "/nix/store/8gkpajpp6fl78ck3jjdy3znnpswqakm4-python2.7-buildbot-pkg-0.9.15.post1/lib/python2.7/site-packages/buildbot_pkg.py", line 41, in listdir
    l = old_listdir(path)
TypeError: 'NoneType' object is not callable
```

**Comment by FRidh** [comment]
@lopsided98 fixed with 73d985f1b59

**Pull request merged**
