### PR TITLE
deno: 1.0.0 -> 1.0.5

### PR DESCRIPTION
**Pull request by 06kellyjac**
###### Motivation for this change

deno `1.0.5` released

###### Things done

Bumped version, sha, and cargo sha

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by marsam** [comment]
@GrahamcOfBorg build deno

**Comment by 06kellyjac** [comment]
Hmmm there seems to be a range of different tests failing for the different build targets.

I'll do some digging tomorrow

**Comment by 06kellyjac** [comment]
@GrahamcOfBorg build deno

**Comment by 06kellyjac** [comment]
@marsam I'm really not too sure why the tests fail this way.
They're meant to be running an integration test (for the most commonly failing test type) e.g. "deno_test_fail_fast" which correctly compares it's output to "deno_test_fail_fast.out" but the output is from "deno_test" so it fails
I've had cases where I run the exact same nix & the tests build and pass the 2nd time so (IMO) it's highly likely there's something wrong with the deno tests & because of this temperamental nature of the issue it's a nightmare to reproduce.

This is the block of code responsible for the most failures:
https://github.com/denoland/deno/blob/master/cli/tests/integration_tests.rs#L2837-L2906

In one of my PRs I'm adding some logging for `args` and `test_dir` to help with the debugging:
https://github.com/denoland/deno/blob/master/cli/tests/integration_tests.rs#L2854-L2855
But if it's some kind of weird parallel stdout thingie where stdout from one test endup in another it wont help much.
Also it's supprising this kind of collision style issue doesn't show up more regularly in their CI. Maybe the CI is just running less parallel threads???

---

I like the tests running because it's fun & helps check for f-ups etc but should we turn the checks off for now until we get a handle on this?
Would love to hear your thoughts

**Comment by 06kellyjac** [comment]
I've decided to abandon the tests for now. Once there's more logging in the upstream tests I'll give it another crack.

Also added an upgrade script that does most tasks in parallel.
I know it's pretty uncommon but I'll be the one to maintain it, if I stop maintaining this I'll convert it to bash first (similar to `nym/update.sh`)

**Comment by 06kellyjac** [comment]
Also removed python as it's not actually required when we're pre-fetching the `rusty_v8` library

**Comment by marsam** [comment]
Thank you for working on this, and sorry for the delay
>This is the block of code responsible for the most failures

I think you can add a patch deleting the offending tests

**Pull request merged**
