### PR TITLE
xorg: batch of updates, bump luit

### PR DESCRIPTION
**Pull request by dtzWill**
Announcements with details of changes
can be found on the mailing list,
and since IIRC these are all from
this month they all are listed here:

https://lists.x.org/archives/xorg-announce/2019-March/thread.html

-----

Grab luit from mirror because our fetcher's
default behavior doesn't get along with
invisible-island's FTP server apparently (?).

Or perhaps server is problematic, not sure.

Example URL:
ftp://ftp.invisible-island.net/luit/luit-20190106.tgz
* Using curl or wget:
  "Server denied you to change to the given directory"
  (or so)
* Using curl with `--ftp-mode nocwd`: success

curl's manpage suggests this is less-compliant behavior
used for speed, offering a third option that's more
likely to work but not quite as fast.
So it seems like the more compliant behavior is
rejected but the fast behavior is accepted.
Dunno, hopefully it'll be on a content-addressed
server soon enough so it doesn't matter as much :).

Hash used here matches manually-fetched from official URL
as well as from the mirror.

###### Things done

I have not tested this on staging yet,
but on my tree which is generally pretty close :).

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
`libXdmcp` contains security fix, although the issue itself has been known (with patch to fix) for some time.. but I don't think we were doing so.

See: https://lists.x.org/archives/xorg-announce/2019-March/002974.html

**Comment by dtzWill** [comment]
Also noteworthy AMD/ATI driver updates, which look rather exciting:
* https://lists.x.org/archives/xorg-announce/2019-March/002966.html
* https://lists.x.org/archives/xorg-announce/2019-March/002967.html

FWIW the update script dependency magic added  `mesa_noglu` and `libGL` to the ATI driver,
they were already on the AMD one? Dunno :).

**Comment by grahamc** [comment]
cc @lovek323 who is a maintainer on some of these

**Comment by worldofpeace** [comment]
I've noticed that these xorg updates can stall a little longer than in other distros.

I think it would be a welcome improvement if we could streamline them more since this is obviously important.

**Comment by dtzWill** [comment]
Started "just" fixing uses of `mkfontdir` package to use `mkfontscale` package instead,
and one thing led to another.  Some overdue fixups to the generate script, which makes it possible to avoid the problems resulting in reported issues manually fixed previously, such as:
* #56978
* #57664 
(and others, see the bits removed from overrides.nix)

Also, fix various dependencies (mostly font utils) to be nativeBuildInputs since they (only) provide binaries used by the builder.

**Comment by dtzWill** [comment]
(eval failure unrelated, darwin hfsevents which I believe has been fixed now)
@GrahamcOfBorg eval

**Comment by dtzWill** [comment]
Inclined to go ahead with this, it works on my machines and doesn't look like there are any problems with the updates in other distributions "yet" :).

Sound okay?

**Pull request merged**
