### PR TITLE
cacert: add hook that sets SSL_CERT_FILE

### LINKED ISSUE #32981: nix-shell MacOSX git checkout
## Issue description
How can I do a git checkout using nixpkgs (17.09 version) git on MacOSX? 

```
#! /usr/bin/env nix-shell
#! nix-shell -I nixpkgs=./nixpkgs --pure -i sh -p cacert git
SSL_CERT_FILE=????? git clone https://github.com/NixOS/nixpkgs.git 
```
Solve for ?????

returns something like 

```
fatal: unable to access 'https://github.com/NixOS/nixpkgs.git': error setting certificate verify locations:
```

### PR DESCRIPTION
**Pull request by LnL7**
###### Motivation for this change

Fixes #32981

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by coretemp** [comment]
I am not sure how tests work, but a test like the one I had described in my ticket would be nice to have for something as important as git. It shouldn't checkout all of nixpkgs, but a mini test repository like NixOS/testRepo could be used. 

Just an idea.

**Review by peti — APPROVED** [review]
Looks good to me (as far as `r-modules` is concerned).

**Comment by LnL7** [comment]
Still have to run nox-review.

**Review by FRidh — APPROVED** [review]

**Comment by LnL7** [comment]
Don't see any new failures, but there are a lot of changes in staging right now so it might be best to wait a bit.

**Comment by pbogdan** [comment]
@LnL7 FYI apparently `envHooks` don't exist any more - https://github.com/NixOS/nixpkgs/issues/33458#issuecomment-355724805 -- so this may need to be adjusted accordingly.

**Comment by LnL7** [comment]
Oh! I made and tested this before the cross changes where merged, I will take a look.

**Pull request merged**
