### PR TITLE
subversionClient: remove vendored swig 3 files; fix build

### LINKED ISSUE #369143: Build failure: subversionClient on aarch64-darwin
## Steps To Reproduce

1. build `subversionClient`

## Build log

<details>

<summary>Build Log</summary>

```
error: builder for '/nix/store/rp0i3wrcwj8j9f69nyd728mv9a074cg0-subversion-client-1.14.5.drv' failed with exit code 2;
       last 25 log lines:
       >       |                 ~~~~~~~~~~~~~~~~~~~~~~~~                                              ^
       > subversion/bindings/swig/python/svn_client.c:1258:1: note: 'SWIG_Python_AppendOutput' declared here
       >  1258 | SWIG_Python_AppendOutput(PyObject* result, PyObject* obj) {
       >       | ^                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       > subversion/bindings/swig/python/svn_client.c:9168:78: error: too many arguments to function call, expected 2, have 3
       >  9168 |     resultobj = SWIG_Python_AppendOutput(resultobj, SWIG_From_long((*arg1)), 0);
       >       |                 ~~~~~~~~~~~~~~~~~~~~~~~~                                     ^
       > subversion/bindings/swig/python/svn_client.c:1258:1: note: 'SWIG_Python_AppendOutput' declared here
       >  1258 | SWIG_Python_AppendOutput(PyObject* result, PyObject* obj) {
       >       | ^                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       > subversion/bindings/swig/python/svn_client.c:9171:116: error: too many arguments to function call, expected 2, have 3
       >  9171 |     resultobj = SWIG_Python_AppendOutput(resultobj, SWIG_NewPointerObj((void*)(arg1), SWIGTYPE_p_long, new_flags), 0);
       >       |                 ~~~~~~~~~~~~~~~~~~~~~~~~                                                                           ^
       > subversion/bindings/swig/python/svn_client.c:1258:1: note: 'SWIG_Python_AppendOutput' declared here
       >  1258 | SWIG_Python_AppendOutput(PyObject* result, PyObject* obj) {
       >       | ^                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       > subversion/bindings/swig/python/svn_client.c:9315:78: error: too many arguments to function call, expected 2, have 3
       >  9315 |     resultobj = SWIG_Python_AppendOutput(resultobj, SWIG_From_long((*arg1)), 0);
       >       |                 ~~~~~~~~~~~~~~~~~~~~~~~~                                     ^
       > subversion/bindings/swig/python/svn_client.c:1258:1: note: 'SWIG_Python_AppendOutput' declared here
       >  1258 | SWIG_Python_AppendOutput(PyObject* result, PyObject* obj) {
       >       | ^                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       > fatal error: too many errors emitted, stopping now [-ferror-limit=]
       > 5 warnings and 20 errors generated.
       > make: *** [build-outputs.mk:2607: subversion/bindings/swig/python/svn_client.lo] Fehler 1
       For full logs, run 'nix log /nix/store/rp0i3wrcwj8j9f69nyd728mv9a074cg0-subversion-client-1.14.5.drv'.
```

</details>

## Additional context

Build failure on Hydra: https://hydra.nixos.org/build/282891753

## Metadata

```
 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.2.0, macOS 15.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.11`
 - channels(root): `"nixpkgs"`
 - channels(rocko): `"nixpkgs, home-manager"`
 - nixpkgs: `/nix/store/6zgbbqlr7nnfxpzkyj7fsl4fpg89jbw0-source`
```

## Notify maintainers

@lovek323 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by paparodeo**
fixes: https://github.com/NixOS/nixpkgs/issues/369143

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by paparodeo** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369267`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 4 packages marked as broken and skipped:</summary>
  <ul>
    <li>kdePackages.umbrello</li>
    <li>kdePackages.umbrello.debug</li>
    <li>kdePackages.umbrello.dev</li>
    <li>kdePackages.umbrello.devtools</li>
  </ul>
</details>
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>ikiwiki-full</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 57 packages built:</summary>
  <ul>
    <li>apacheHttpdPackages.subversion</li>
    <li>apacheHttpdPackages.subversion.dev</li>
    <li>apacheHttpdPackages.subversion.man</li>
    <li>cabal2nix</li>
    <li>git-doc (git-doc.debug ,git-doc.doc ,gitFull.doc)</li>
    <li>gitFull</li>
    <li>gitFull.debug</li>
    <li>gitSVN</li>
    <li>gitSVN.debug</li>
    <li>gitSVN.doc</li>
    <li>hydra</li>
    <li>hydra.doc</li>
    <li>kdePackages.kdev-php</li>
    <li>kdePackages.kdev-php.debug</li>
    <li>kdePackages.kdev-php.dev</li>
    <li>kdePackages.kdev-php.devtools</li>
    <li>kdePackages.kdev-python</li>
    <li>kdePackages.kdev-python.debug</li>
    <li>kdePackages.kdev-python.dev</li>
    <li>kdePackages.kdev-python.devtools</li>
    <li>kdePackages.kdevelop</li>
    <li>kdePackages.kdevelop.debug</li>
    <li>kdePackages.kdevelop.dev</li>
    <li>kdePackages.kdevelop.devtools</li>
    <li>kdesvn</li>
    <li>luarocks-packages-updater</li>
    <li>luarocks-packages-updater.dist</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-update-source</li>
    <li>nix-update-source.dist</li>
    <li>patroni</li>
    <li>patroni.dist</li>
    <li>perl538Packages.SVNSimple</li>
    <li>perl538Packages.SVNSimple.devdoc</li>
    <li>perl540Packages.SVNSimple</li>
    <li>perl540Packages.SVNSimple.devdoc</li>
    <li>python312Packages.pysvn</li>
    <li>ydiff (python312Packages.ydiff)</li>
    <li>ydiff.dist (python312Packages.ydiff.dist)</li>
    <li>python313Packages.pysvn</li>
    <li>python313Packages.ydiff</li>
    <li>python313Packages.ydiff.dist</li>
    <li>rapidsvn</li>
    <li>subversion</li>
    <li>subversion.dev</li>
    <li>subversion.man</li>
    <li>subversionClient</li>
    <li>subversionClient.dev</li>
    <li>subversionClient.man</li>
    <li>svn-all-fast-export</li>
    <li>svn2git</li>
    <li>svnfs</li>
    <li>thcrap-steam-proton-wrapper</li>
    <li>vcstool</li>
    <li>vcstool.dist</li>
    <li>wp4nix</li>
  </ul>
</details>

failed builds also fail on master: https://hydra.nixos.org/build/283179983

**Review by matteo-pacini — APPROVED** [review]
@paparodeo pysvn seems to be broken now.

(accidentally approved, wanted to post a build result for both Darwin systems)

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369267`

---
### `x86_64-darwin`
<details>
  <summary>:fast_forward: 2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python312Packages.pysvn</li>
    <li>python313Packages.pysvn</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 38 packages built:</summary>
  <ul>
    <li>apacheHttpdPackages.subversion (apacheHttpdPackages_2_4.subversion)</li>
    <li>apacheHttpdPackages.subversion.dev (apacheHttpdPackages_2_4.subversion.dev)</li>
    <li>apacheHttpdPackages.subversion.man (apacheHttpdPackages_2_4.subversion.man)</li>
    <li>cabal2nix</li>
    <li>git-doc (git-doc.doc ,gitFull.doc)</li>
    <li>gitFull</li>
    <li>gitSVN</li>
    <li>gitSVN.doc</li>
    <li>haskellPackages.cabal2nix-unstable</li>
    <li>luarocks-packages-updater</li>
    <li>luarocks-packages-updater.dist</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-update-source</li>
    <li>nix-update-source.dist</li>
    <li>patroni</li>
    <li>patroni.dist</li>
    <li>perl538Packages.SVNSimple</li>
    <li>perl538Packages.SVNSimple.devdoc</li>
    <li>perl540Packages.SVNSimple</li>
    <li>perl540Packages.SVNSimple.devdoc</li>
    <li>ydiff (python312Packages.ydiff)</li>
    <li>ydiff.dist (python312Packages.ydiff.dist)</li>
    <li>python313Packages.ydiff</li>
    <li>python313Packages.ydiff.dist</li>
    <li>rapidsvn</li>
    <li>subversion</li>
    <li>subversion.dev</li>
    <li>subversion.man</li>
    <li>subversionClient</li>
    <li>subversionClient.dev</li>
    <li>subversionClient.man</li>
    <li>svn-all-fast-export</li>
    <li>svn2git</li>
    <li>svnfs</li>
    <li>vcstool</li>
    <li>vcstool.dist</li>
    <li>wp4nix</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:fast_forward: 2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python312Packages.pysvn</li>
    <li>python313Packages.pysvn</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 38 packages built:</summary>
  <ul>
    <li>apacheHttpdPackages.subversion (apacheHttpdPackages_2_4.subversion)</li>
    <li>apacheHttpdPackages.subversion.dev (apacheHttpdPackages_2_4.subversion.dev)</li>
    <li>apacheHttpdPackages.subversion.man (apacheHttpdPackages_2_4.subversion.man)</li>
    <li>cabal2nix</li>
    <li>git-doc (git-doc.doc ,gitFull.doc)</li>
    <li>gitFull</li>
    <li>gitSVN</li>
    <li>gitSVN.doc</li>
    <li>haskellPackages.cabal2nix-unstable</li>
    <li>luarocks-packages-updater</li>
    <li>luarocks-packages-updater.dist</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-update-source</li>
    <li>nix-update-source.dist</li>
    <li>patroni</li>
    <li>patroni.dist</li>
    <li>perl538Packages.SVNSimple</li>
    <li>perl538Packages.SVNSimple.devdoc</li>
    <li>perl540Packages.SVNSimple</li>
    <li>perl540Packages.SVNSimple.devdoc</li>
    <li>ydiff (python312Packages.ydiff)</li>
    <li>ydiff.dist (python312Packages.ydiff.dist)</li>
    <li>python313Packages.ydiff</li>
    <li>python313Packages.ydiff.dist</li>
    <li>rapidsvn</li>
    <li>subversion</li>
    <li>subversion.dev</li>
    <li>subversion.man</li>
    <li>subversionClient</li>
    <li>subversionClient.dev</li>
    <li>subversionClient.man</li>
    <li>svn-all-fast-export</li>
    <li>svn2git</li>
    <li>svnfs</li>
    <li>vcstool</li>
    <li>vcstool.dist</li>
    <li>wp4nix</li>
  </ul>
</details>

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369267`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 4 packages marked as broken and skipped:</summary>
  <ul>
    <li>kdePackages.umbrello</li>
    <li>kdePackages.umbrello.debug</li>
    <li>kdePackages.umbrello.dev</li>
    <li>kdePackages.umbrello.devtools</li>
  </ul>
</details>
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>ikiwiki-full</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 58 packages built:</summary>
  <ul>
    <li>apacheHttpdPackages.subversion (apacheHttpdPackages_2_4.subversion)</li>
    <li>apacheHttpdPackages.subversion.dev (apacheHttpdPackages_2_4.subversion.dev)</li>
    <li>apacheHttpdPackages.subversion.man (apacheHttpdPackages_2_4.subversion.man)</li>
    <li>cabal2nix</li>
    <li>git-doc (git-doc.debug ,git-doc.doc ,gitFull.doc)</li>
    <li>gitFull</li>
    <li>gitFull.debug</li>
    <li>gitSVN</li>
    <li>gitSVN.debug</li>
    <li>gitSVN.doc</li>
    <li>haskellPackages.cabal2nix-unstable</li>
    <li>hydra</li>
    <li>hydra.doc</li>
    <li>kdePackages.kdev-php</li>
    <li>kdePackages.kdev-php.debug</li>
    <li>kdePackages.kdev-php.dev</li>
    <li>kdePackages.kdev-php.devtools</li>
    <li>kdePackages.kdev-python</li>
    <li>kdePackages.kdev-python.debug</li>
    <li>kdePackages.kdev-python.dev</li>
    <li>kdePackages.kdev-python.devtools</li>
    <li>kdePackages.kdevelop</li>
    <li>kdePackages.kdevelop.debug</li>
    <li>kdePackages.kdevelop.dev</li>
    <li>kdePackages.kdevelop.devtools</li>
    <li>kdesvn</li>
    <li>luarocks-packages-updater</li>
    <li>luarocks-packages-updater.dist</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-update-source</li>
    <li>nix-update-source.dist</li>
    <li>patroni</li>
    <li>patroni.dist</li>
    <li>perl538Packages.SVNSimple</li>
    <li>perl538Packages.SVNSimple.devdoc</li>
    <li>perl540Packages.SVNSimple</li>
    <li>perl540Packages.SVNSimple.devdoc</li>
    <li>python312Packages.pysvn</li>
    <li>ydiff (python312Packages.ydiff)</li>
    <li>ydiff.dist (python312Packages.ydiff.dist)</li>
    <li>python313Packages.pysvn</li>
    <li>python313Packages.ydiff</li>
    <li>python313Packages.ydiff.dist</li>
    <li>rapidsvn</li>
    <li>subversion</li>
    <li>subversion.dev</li>
    <li>subversion.man</li>
    <li>subversionClient</li>
    <li>subversionClient.dev</li>
    <li>subversionClient.man</li>
    <li>svn-all-fast-export</li>
    <li>svn2git</li>
    <li>svnfs</li>
    <li>thcrap-steam-proton-wrapper</li>
    <li>vcstool</li>
    <li>vcstool.dist</li>
    <li>wp4nix</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:fast_forward: 4 packages marked as broken and skipped:</summary>
  <ul>
    <li>kdePackages.umbrello</li>
    <li>kdePackages.umbrello.debug</li>
    <li>kdePackages.umbrello.dev</li>
    <li>kdePackages.umbrello.devtools</li>
  </ul>
</details>
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>ikiwiki-full</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 58 packages built:</summary>
  <ul>
    <li>apacheHttpdPackages.subversion (apacheHttpdPackages_2_4.subversion)</li>
    <li>apacheHttpdPackages.subversion.dev (apacheHttpdPackages_2_4.subversion.dev)</li>
    <li>apacheHttpdPackages.subversion.man (apacheHttpdPackages_2_4.subversion.man)</li>
    <li>cabal2nix</li>
    <li>git-doc (git-doc.debug ,git-doc.doc ,gitFull.doc)</li>
    <li>gitFull</li>
    <li>gitFull.debug</li>
    <li>gitSVN</li>
    <li>gitSVN.debug</li>
    <li>gitSVN.doc</li>
    <li>haskellPackages.cabal2nix-unstable</li>
    <li>hydra</li>
    <li>hydra.doc</li>
    <li>kdePackages.kdev-php</li>
    <li>kdePackages.kdev-php.debug</li>
    <li>kdePackages.kdev-php.dev</li>
    <li>kdePackages.kdev-php.devtools</li>
    <li>kdePackages.kdev-python</li>
    <li>kdePackages.kdev-python.debug</li>
    <li>kdePackages.kdev-python.dev</li>
    <li>kdePackages.kdev-python.devtools</li>
    <li>kdePackages.kdevelop</li>
    <li>kdePackages.kdevelop.debug</li>
    <li>kdePackages.kdevelop.dev</li>
    <li>kdePackages.kdevelop.devtools</li>
    <li>kdesvn</li>
    <li>luarocks-packages-updater</li>
    <li>luarocks-packages-updater.dist</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-update-source</li>
    <li>nix-update-source.dist</li>
    <li>patroni</li>
    <li>patroni.dist</li>
    <li>perl538Packages.SVNSimple</li>
    <li>perl538Packages.SVNSimple.devdoc</li>
    <li>perl540Packages.SVNSimple</li>
    <li>perl540Packages.SVNSimple.devdoc</li>
    <li>python312Packages.pysvn</li>
    <li>ydiff (python312Packages.ydiff)</li>
    <li>ydiff.dist (python312Packages.ydiff.dist)</li>
    <li>python313Packages.pysvn</li>
    <li>python313Packages.ydiff</li>
    <li>python313Packages.ydiff.dist</li>
    <li>rapidsvn</li>
    <li>subversion</li>
    <li>subversion.dev</li>
    <li>subversion.man</li>
    <li>subversionClient</li>
    <li>subversionClient.dev</li>
    <li>subversionClient.man</li>
    <li>svn-all-fast-export</li>
    <li>svn2git</li>
    <li>svnfs</li>
    <li>thcrap-steam-proton-wrapper</li>
    <li>vcstool</li>
    <li>vcstool.dist</li>
    <li>wp4nix</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:fast_forward: 2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python312Packages.pysvn</li>
    <li>python313Packages.pysvn</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 38 packages built:</summary>
  <ul>
    <li>apacheHttpdPackages.subversion (apacheHttpdPackages_2_4.subversion)</li>
    <li>apacheHttpdPackages.subversion.dev (apacheHttpdPackages_2_4.subversion.dev)</li>
    <li>apacheHttpdPackages.subversion.man (apacheHttpdPackages_2_4.subversion.man)</li>
    <li>cabal2nix</li>
    <li>git-doc (git-doc.doc ,gitFull.doc)</li>
    <li>gitFull</li>
    <li>gitSVN</li>
    <li>gitSVN.doc</li>
    <li>haskellPackages.cabal2nix-unstable</li>
    <li>luarocks-packages-updater</li>
    <li>luarocks-packages-updater.dist</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-update-source</li>
    <li>nix-update-source.dist</li>
    <li>patroni</li>
    <li>patroni.dist</li>
    <li>perl538Packages.SVNSimple</li>
    <li>perl538Packages.SVNSimple.devdoc</li>
    <li>perl540Packages.SVNSimple</li>
    <li>perl540Packages.SVNSimple.devdoc</li>
    <li>ydiff (python312Packages.ydiff)</li>
    <li>ydiff.dist (python312Packages.ydiff.dist)</li>
    <li>python313Packages.ydiff</li>
    <li>python313Packages.ydiff.dist</li>
    <li>rapidsvn</li>
    <li>subversion</li>
    <li>subversion.dev</li>
    <li>subversion.man</li>
    <li>subversionClient</li>
    <li>subversionClient.dev</li>
    <li>subversionClient.man</li>
    <li>svn-all-fast-export</li>
    <li>svn2git</li>
    <li>svnfs</li>
    <li>vcstool</li>
    <li>vcstool.dist</li>
    <li>wp4nix</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:fast_forward: 2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python312Packages.pysvn</li>
    <li>python313Packages.pysvn</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 38 packages built:</summary>
  <ul>
    <li>apacheHttpdPackages.subversion (apacheHttpdPackages_2_4.subversion)</li>
    <li>apacheHttpdPackages.subversion.dev (apacheHttpdPackages_2_4.subversion.dev)</li>
    <li>apacheHttpdPackages.subversion.man (apacheHttpdPackages_2_4.subversion.man)</li>
    <li>cabal2nix</li>
    <li>git-doc (git-doc.doc ,gitFull.doc)</li>
    <li>gitFull</li>
    <li>gitSVN</li>
    <li>gitSVN.doc</li>
    <li>haskellPackages.cabal2nix-unstable</li>
    <li>luarocks-packages-updater</li>
    <li>luarocks-packages-updater.dist</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-update-source</li>
    <li>nix-update-source.dist</li>
    <li>patroni</li>
    <li>patroni.dist</li>
    <li>perl538Packages.SVNSimple</li>
    <li>perl538Packages.SVNSimple.devdoc</li>
    <li>perl540Packages.SVNSimple</li>
    <li>perl540Packages.SVNSimple.devdoc</li>
    <li>ydiff (python312Packages.ydiff)</li>
    <li>ydiff.dist (python312Packages.ydiff.dist)</li>
    <li>python313Packages.ydiff</li>
    <li>python313Packages.ydiff.dist</li>
    <li>rapidsvn</li>
    <li>subversion</li>
    <li>subversion.dev</li>
    <li>subversion.man</li>
    <li>subversionClient</li>
    <li>subversionClient.dev</li>
    <li>subversionClient.man</li>
    <li>svn-all-fast-export</li>
    <li>svn2git</li>
    <li>svnfs</li>
    <li>vcstool</li>
    <li>vcstool.dist</li>
    <li>wp4nix</li>
  </ul>
</details>

**Review by khaneliman — APPROVED** [review]

**Comment by paparodeo** [comment]
> @paparodeo pysvn seems to be broken now.
> 
> (accidentally approved, wanted to post a build result for both Darwin systems)

it was marked as broken in 2021 e3dbed8e382b5eb13f72151898c1b4995471a6c4

**Comment by paparodeo** [comment]
> > @paparodeo pysvn seems to be broken now.
> > (accidentally approved, wanted to post a build result for both Darwin systems)
> 
> it was marked as broken in 2021 [e3dbed8](https://github.com/NixOS/nixpkgs/commit/e3dbed8e382b5eb13f72151898c1b4995471a6c4)

and still fails with the same error: `line 1: g++: command not found`. it might be fixable if someone cares but out of the scope of this PR.

**Pull request merged**
