### PR TITLE
vimPlugins.typescript-tools-nvim: init at unstable-2023-10-04

### LINKED ISSUE #251855: Package request: typescript-tools.nvim
**Project description**

It seems like the current non-archived project for making nvim experience more like vscode would be great to have it in nixpkgs.

**Metadata**

* homepage URL: https://github.com/pmizio/typescript-tools.nvim
* source URL: https://github.com/pmizio/typescript-tools.nvim
* license: [mit](https://github.com/pmizio/typescript-tools.nvim/blob/master/LICENSE)
* platforms: all

### PR DESCRIPTION
**Pull request by jfvillablanca**
## Description of changes
Resolves #251855

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jfvillablanca** [comment]
> could you add plenary as a dependency in pkgs/applications/editors/vim/plugins/overrides.nix (follow the examples), maybe lspconfig too. Also would be nice if you could run a nixpkgs-review on the result as these updates tend to break rust-based plugins

oh right, thanks!
does the commit message for updating the `overrides.nix` have a specific format?

**Comment by teto** [comment]
`vimPlugins.typescript-tools-nvim: add overrides` for instance

**Comment by jfvillablanca** [comment]
> Also would be nice if you could run a nixpkgs-review on the result as these updates tend to break rust-based plugins

I tried that earlier with the `--post-result` flag but my machine was struggling and I only have a few GBs left from my 256GB hard drive 😢.

**Comment by jfvillablanca** [comment]
> Also would be nice if you could run a nixpkgs-review on the result as these updates tend to break rust-based plugins

If the update breaks some plugins, i could drop the commit

**Pull request merged**
