### PR TITLE
rambox: 1.5.0 -> 2.0.5 and remove deprecated CE

### LINKED ISSUE #161741: rambox-pro: 2.0.1
New release available at https://github.com/ramboxapp/download/releases

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: rambox-pro

current version: 1.5.0
desired version: 2.0.1

###### Notify maintainers

maintainers: @cawilliamson

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by Wabri**
###### Description of changes

Update package rambox from 1.5.0 to 2.0.5 , here you can find the release: https://github.com/ramboxapp/download/releases/tag/v2.0.5

Since rambox community edition is no longer maintained and not work anymore, I remove it. Here the link to the deprecated repository: https://github.com/ramboxapp/community-edition

I think this pr could close #161741 issue!

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
@ofborg build rambox
@ofborg eval rambox

**Comment by vale981** [comment]
see #191886

**Comment by Wabri** [comment]
With the upgraded pr of @vale981 this can be closed I guess ☺️

**Comment by onny** [comment]
THank you @Wabri for trying to fix this!

**Pull request closed without merging**
