### PR TITLE
wasmtime: backport to release-22.05

### PR DESCRIPTION
**Pull request by ereslibre**
###### Description of changes

Backports wasmtime 0.39.1 (mainly https://github.com/NixOS/nixpkgs/pull/187702 and the rest of commits). It also backports the fact that this package is not broken, but a false positive in the way the Hydra infrastructure is set up.

These backports do not contain any breaking change.

More information in the commit d97b6efa79a219b6fcdbb90e7f9f514f9c175579.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by symphorien** [comment]
changelog: https://github.com/bytecodealliance/wasmtime/blob/main/RELEASES.md

does 
> Some methods on the Config structure now return &mut Self instead of Result<&mut Self> since the validation is deferred until Engine::new: profiler, cranelift_flag_enable, cranelift_flag_set, max_wasm_stack, async_stack_size, and strategy. https://github.com/bytecodealliance/wasmtime/pull/4252 https://github.com/bytecodealliance/wasmtime/pull/4262


constitute a breaking change?

**Comment by ereslibre** [comment]
> The manual requires you to use git cherry-pick -x in backports.

Missed that, first time backporting. Done.

> constitute a breaking change?

We briefly discussed this on the chat; given rust is vendored in nixpkgs this should not constitute an issue. Being completely strict it would be a breaking change, but I think it does not apply strictly given rust dependencies are vendored.

**Comment by symphorien** [comment]
@GrahamcOfBorg build wasmtime

**Pull request merged**
