### PR TITLE
mupdf: 1.14.0 -> 1.16.1

### PR DESCRIPTION
**Pull request by teto**
###### Motivation for this change
Wanna try termpdf.py that relies on https://github.com/pymupdf/PyMuPDF which relies on an up to date mupdf

replaces https://github.com/NixOS/nixpkgs/pull/61196

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by teto** [comment]
seems like it will require some more work as a nix-review gives
```
https://github.com/NixOS/nixpkgs/pull/68506
4 package failed to build:
k2pdfopt llpp system-config-printer zathura

5 package were build:
cups-filters jfbpdf jfbview mupdf splix
```

**Comment by teto** [comment]
would you mind looking at the patch for llpp @pSub @enzime ? bumping the package gets me to
```
building '/nix/store/bjld1ajlx4bz9p6b1zpnrhk255z032nr-fix-build-bash.patch.drv'...
building '/nix/store/b80y8dr4s7xivp6h85yqndffqz761dx8-llpp-31.drv'...
unpacking sources
unpacking source archive /nix/store/108fgxx0k26n81pg1hz61z324nrsihaa-llpp
source root is llpp
patching sources
applying patch /nix/store/8fv6cs6sc5p4lkxfvi082a69fvmqxdkr-fix-build-bash.patch
patching file build.bash
Hunk #2 succeeded at 226 (offset 3 lines).
Hunk #3 succeeded at 280 (offset 3 lines).
configuring
building
make: *** No rule to make target 'libs'.  Stop.
make: Entering directory '/build/llpp/build/mupdf'
make: *** No rule to make target 'libs'.  Stop.
make: Leaving directory '/build/llpp/build/mupdf'
make: *** No rule to make target 'libs'.  Stop.
./build.bash: line 44: build/mupdf/build/native/libmupdf.a.past: No such file or directory
no program to fetch remote urls found
```

@bosu @danielfullmer same for k2pdfopt ? it breaks with the mupdf update

**Comment by tobiasBora** [comment]
k2pdfopt is already broken I think: https://github.com/NixOS/nixpkgs/issues/68683

**Comment by teto** [comment]
nix-review can now build all of them
```
$ nix build --no-link --keep-going --max-jobs 4 --option build-use-sandbox true -f /home/teto/.cache/nix-review/rev-2390e3f97f88dabb664e22f0d31b6deff18b4a3c/build.nix
[15 built, 27 copied (137.8 MiB), 23.5 MiB DL]
9 package were build:
cups-filters jfbpdf jfbview k2pdfopt llpp mupdf splix system-config-printer zathura

```
I've just started the binaries, they look fine.

**Review by pSub — APPROVED** [review]

**Comment by danieldk** [comment]
Upstream's release notes are somewhat incomplete, but 1.15 and 1.16 fix some CVEs, so this should be backported to 19.03/19.09:

https://www.cvedetails.com/vulnerability-list/vendor_id-10846/product_id-20840/Artifex-Mupdf.html

**Comment by flokli** [comment]
@danieldk was this backported already?

**Comment by danieldk** [comment]
@flokli doesn't seem so, the last real update was in December 2018:

https://github.com/NixOS/nixpkgs/commits/release-19.09/pkgs/applications/misc/mupdf/default.nix

**Pull request merged**
