### PR TITLE
fastfetch: fix fish completions

### LINKED ISSUE #325317: fastfetch: shell completion does not work
### Describe the bug
shell completion does not work with fastfetch

### Steps To Reproduce
1. install fastfatch
2. open fish
3. enter `fastfetch` and `<tab>`

### Expected behavior
shell completion works

### Screenshots
image

### Notify maintainers
@khaneliman 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.7-zen1, NixOS, 24.11 (骆马), 24.11.20240705.4284c2b`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `not found`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by iynaix**
## Description of changes

Fix fish completions by providing a full path to python3.
Fixes #325317

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by khaneliman** [comment]
Result of `nixpkgs-review pr 325383` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>fastfetch</li>
    <li>fastfetch.man</li>
  </ul>
</details>

**Comment by khaneliman** [comment]
Fish completions already work for me. So, can't really verify the validity of the issue or fix..

**Comment by iynaix** [comment]
It currently only works for me if python3 is globally installed, otherwise I get the following error:

```console
 fastfetch -The program 'python3' is currently not installed. It is provided by
several packages. You can install it by typing one of the following:
  nix-env -iA nixpkgs.python3.out
  nix-env -iA nixpkgs.python39.out
  nix-env -iA nixpkgs.python39Full.out
  nix-env -iA nixpkgs.python3Minimal.out
  nix-env -iA nixpkgs.python312.out
  nix-env -iA nixpkgs.jupyter-all.out
  nix-env -iA nixpkgs.python3Full.out
  nix-env -iA nixpkgs.python313Full.out
  nix-env -iA nixpkgs.python312Full.out
  nix-env -iA nixpkgs.python310Full.out
  nix-env -iA nixpkgs.python313.out
  nix-env -iA nixpkgs.jupyter.out
  nix-env -iA nixpkgs.python310.out
  nix-env -iA nixpkgs.ihaskell.out
  nix-env -iA nixpkgs.graalvmCEPackages.graalpy.out

Or run it once with:
  nix-shell -p python3.out --run 'python3 ...'
  nix-shell -p python39.out --run 'python3 ...'
  nix-shell -p python39Full.out --run 'python3 ...'
  nix-shell -p python3Minimal.out --run 'python3 ...'
  nix-shell -p python312.out --run 'python3 ...'
  nix-shell -p jupyter-all.out --run 'python3 ...'
  nix-shell -p python3Full.out --run 'python3 ...'
  nix-shell -p python313Full.out --run 'python3 ...'
  nix-shell -p python312Full.out --run 'python3 ...'
  nix-shell -p python310Full.out --run 'python3 ...'
  nix-shell -p python313.out --run 'python3 ...'
  nix-shell -p jupyter.out --run 'python3 ...'
  nix-shell -p python310.out --run 'python3 ...'
  nix-shell -p ihaskell.out --run 'python3 ...'
  nix-shell -p graalvmCEPackages.graalpy.out --run 'python3 ...'
/etc/profiles/per-user/iynaix/share/fish/vendor_completions.d/fastfetch.fish (line 57): 
string match -r -a -g "^###> ?(.*)" < (status -f) | string collect | python3 | source
                                                                     ^~~~~~^
```

**Comment by khaneliman** [comment]
> It currently only works for me if python3 is globally installed, otherwise I get the following error:
> 
>  fastfetch -The program 'python3' is currently not installed. It is provided by

Hmm.. not sure what in my config has added python to my global path. But, I do see it referenced in the fish completion https://github.com/fastfetch-cli/fastfetch/blob/4f70c16d636c308e8fbafcfddb5ee30ae0163a6b/completions/fastfetch.fish#L101.

**Review by khaneliman — APPROVED** [review]

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 325383` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>fastfetch</li>
    <li>fastfetch.man</li>
  </ul>
</details>

**Pull request merged**
