### PR TITLE
bump azure packages

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
routine bump of azure packages

created PR to fix pinning: https://github.com/Azure/azure-cli/pull/16074

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Comment by SuperSandro2000** [comment]
I get a lot of 

```
  ERROR: Could not find a version that satisfies the requirement azure-mgmt-core<2.0.0,>=1.2.0 (from azure-mgmt-web==1.0.0) (from versions: none)
  ERROR: No matching distribution found for azure-mgmt-core<2.0.0,>=1.2.0 (from azure-mgmt-web==1.0.0)
```

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105267` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>68 packages marked as broken and skipped:</summary>
  <ul>
    <li>nixops_1_6_1</li>
    <li>python27Packages.azure-applicationinsights</li>
    <li>python27Packages.azure-batch</li>
    <li>python27Packages.azure-cosmosdb-table</li>
    <li>python27Packages.azure-datalake-store</li>
    <li>python27Packages.azure-eventgrid</li>
    <li>python27Packages.azure-graphrbac</li>
    <li>python27Packages.azure-loganalytics</li>
    <li>python27Packages.azure-mgmt-advisor</li>
    <li>python27Packages.azure-mgmt-applicationinsights</li>
    <li>python27Packages.azure-mgmt-authorization</li>
    <li>python27Packages.azure-mgmt-batch</li>
    <li>python27Packages.azure-mgmt-batchai</li>
    <li>python27Packages.azure-mgmt-billing</li>
    <li>python27Packages.azure-mgmt-cdn</li>
    <li>python27Packages.azure-mgmt-cognitiveservices</li>
    <li>python27Packages.azure-mgmt-commerce</li>
    <li>python27Packages.azure-mgmt-common</li>
    <li>python27Packages.azure-mgmt-consumption</li>
    <li>python27Packages.azure-mgmt-containerinstance</li>
    <li>python27Packages.azure-mgmt-containerservice</li>
    <li>python27Packages.azure-mgmt-cosmosdb</li>
    <li>python27Packages.azure-mgmt-datafactory</li>
    <li>python27Packages.azure-mgmt-datalake-analytics</li>
    <li>python27Packages.azure-mgmt-datalake-store</li>
    <li>python27Packages.azure-mgmt-datamigration</li>
    <li>python27Packages.azure-mgmt-devspaces</li>
    <li>python27Packages.azure-mgmt-devtestlabs</li>
    <li>python27Packages.azure-mgmt-dns</li>
    <li>python27Packages.azure-mgmt-eventgrid</li>
    <li>python27Packages.azure-mgmt-hanaonazure</li>
    <li>python27Packages.azure-mgmt-iotcentral</li>
    <li>python27Packages.azure-mgmt-iothub</li>
    <li>python27Packages.azure-mgmt-iothubprovisioningservices</li>
    <li>python27Packages.azure-mgmt-loganalytics</li>
    <li>python27Packages.azure-mgmt-logic</li>
    <li>python27Packages.azure-mgmt-machinelearningcompute</li>
    <li>python27Packages.azure-mgmt-managementgroups</li>
    <li>python27Packages.azure-mgmt-managementpartner</li>
    <li>python27Packages.azure-mgmt-maps</li>
    <li>python27Packages.azure-mgmt-marketplaceordering</li>
    <li>python27Packages.azure-mgmt-media</li>
    <li>python27Packages.azure-mgmt-msi</li>
    <li>python27Packages.azure-mgmt-notificationhubs</li>
    <li>python27Packages.azure-mgmt-policyinsights</li>
    <li>python27Packages.azure-mgmt-powerbiembedded</li>
    <li>python27Packages.azure-mgmt-rdbms</li>
    <li>python27Packages.azure-mgmt-recoveryservices</li>
    <li>python27Packages.azure-mgmt-recoveryservicesbackup</li>
    <li>python27Packages.azure-mgmt-redis</li>
    <li>python27Packages.azure-mgmt-relay</li>
    <li>python27Packages.azure-mgmt-reservations</li>
    <li>python27Packages.azure-mgmt-scheduler</li>
    <li>python27Packages.azure-mgmt-search</li>
    <li>python27Packages.azure-mgmt-servicebus</li>
    <li>python27Packages.azure-mgmt-servicefabric</li>
    <li>python27Packages.azure-mgmt-signalr</li>
    <li>python27Packages.azure-mgmt-sql</li>
    <li>python27Packages.azure-mgmt-subscription</li>
    <li>python27Packages.azure-mgmt-trafficmanager</li>
    <li>python27Packages.azure-mgmt-web</li>
    <li>python27Packages.azure-servicebus</li>
    <li>python27Packages.azure-servicefabric</li>
    <li>python27Packages.azure-servicemanagement-legacy</li>
    <li>python27Packages.azure-storage</li>
    <li>python27Packages.azure-storage-common</li>
    <li>python27Packages.azure-storage-file</li>
    <li>python27Packages.azure-storage-queue</li>
  </ul>
</details>
<details>
  <summary>19 packages failed to build:</summary>
  <ul>
    <li>python37Packages.azure-identity</li>
    <li>python37Packages.azure-mgmt-authorization</li>
    <li>python37Packages.azure-mgmt-containerinstance</li>
    <li>python37Packages.azure-mgmt-containerservice</li>
    <li>python37Packages.azure-mgmt-cosmosdb</li>
    <li>python37Packages.azure-mgmt-redis</li>
    <li>python37Packages.azure-mgmt-servicebus</li>
    <li>python37Packages.azure-mgmt-sql</li>
    <li>python37Packages.azure-mgmt-web</li>
    <li>python37Packages.azure-servicebus</li>
    <li>python38Packages.azure-mgmt-authorization</li>
    <li>python38Packages.azure-mgmt-containerinstance</li>
    <li>python38Packages.azure-mgmt-containerservice</li>
    <li>python38Packages.azure-mgmt-cosmosdb</li>
    <li>python38Packages.azure-mgmt-redis</li>
    <li>python38Packages.azure-mgmt-servicebus</li>
    <li>python38Packages.azure-mgmt-sql</li>
    <li>python38Packages.azure-mgmt-web</li>
    <li>python38Packages.azure-servicebus</li>
  </ul>
</details>
<details>
  <summary>198 packages built:</summary>
  <ul>
    <li>appdaemon</li>
    <li>azure-cli</li>
    <li>dvc-with-remotes</li>
    <li>python27Packages.azure-common</li>
    <li>python37Packages.azure-appconfiguration</li>
    <li>python37Packages.azure-applicationinsights</li>
    <li>python37Packages.azure-batch</li>
    <li>python37Packages.azure-common</li>
    <li>python37Packages.azure-core</li>
    <li>python37Packages.azure-cosmosdb-table</li>
    <li>python37Packages.azure-datalake-store</li>
    <li>python37Packages.azure-eventgrid</li>
    <li>python37Packages.azure-graphrbac</li>
    <li>python37Packages.azure-keyvault</li>
    <li>python37Packages.azure-keyvault-administration</li>
    <li>python37Packages.azure-keyvault-certificates</li>
    <li>python37Packages.azure-keyvault-keys</li>
    <li>python37Packages.azure-keyvault-secrets</li>
    <li>python37Packages.azure-loganalytics</li>
    <li>python37Packages.azure-mgmt-advisor</li>
    <li>python37Packages.azure-mgmt-apimanagement</li>
    <li>python37Packages.azure-mgmt-appconfiguration</li>
    <li>python37Packages.azure-mgmt-applicationinsights</li>
    <li>python37Packages.azure-mgmt-batch</li>
    <li>python37Packages.azure-mgmt-batchai</li>
    <li>python37Packages.azure-mgmt-billing</li>
    <li>python37Packages.azure-mgmt-botservice</li>
    <li>python37Packages.azure-mgmt-cdn</li>
    <li>python37Packages.azure-mgmt-cognitiveservices</li>
    <li>python37Packages.azure-mgmt-commerce</li>
    <li>python37Packages.azure-mgmt-common</li>
    <li>python37Packages.azure-mgmt-compute</li>
    <li>python37Packages.azure-mgmt-consumption</li>
    <li>python37Packages.azure-mgmt-containerregistry</li>
    <li>python37Packages.azure-mgmt-core</li>
    <li>python37Packages.azure-mgmt-datafactory</li>
    <li>python37Packages.azure-mgmt-datalake-analytics</li>
    <li>python37Packages.azure-mgmt-datalake-store</li>
    <li>python37Packages.azure-mgmt-datamigration</li>
    <li>python37Packages.azure-mgmt-deploymentmanager</li>
    <li>python37Packages.azure-mgmt-devspaces</li>
    <li>python37Packages.azure-mgmt-devtestlabs</li>
    <li>python37Packages.azure-mgmt-dns</li>
    <li>python37Packages.azure-mgmt-eventgrid</li>
    <li>python37Packages.azure-mgmt-eventhub</li>
    <li>python37Packages.azure-mgmt-hanaonazure</li>
    <li>python37Packages.azure-mgmt-hdinsight</li>
    <li>python37Packages.azure-mgmt-imagebuilder</li>
    <li>python37Packages.azure-mgmt-iotcentral</li>
    <li>python37Packages.azure-mgmt-iothub</li>
    <li>python37Packages.azure-mgmt-iothubprovisioningservices</li>
    <li>python37Packages.azure-mgmt-keyvault</li>
    <li>python37Packages.azure-mgmt-kusto</li>
    <li>python37Packages.azure-mgmt-loganalytics</li>
    <li>python37Packages.azure-mgmt-logic</li>
    <li>python37Packages.azure-mgmt-machinelearningcompute</li>
    <li>python37Packages.azure-mgmt-managedservices</li>
    <li>python37Packages.azure-mgmt-managementgroups</li>
    <li>python37Packages.azure-mgmt-managementpartner</li>
    <li>python37Packages.azure-mgmt-maps</li>
    <li>python37Packages.azure-mgmt-marketplaceordering</li>
    <li>python37Packages.azure-mgmt-media</li>
    <li>python37Packages.azure-mgmt-monitor</li>
    <li>python37Packages.azure-mgmt-msi</li>
    <li>python37Packages.azure-mgmt-netapp</li>
    <li>python37Packages.azure-mgmt-network</li>
    <li>python37Packages.azure-mgmt-notificationhubs</li>
    <li>python37Packages.azure-mgmt-policyinsights</li>
    <li>python37Packages.azure-mgmt-powerbiembedded</li>
    <li>python37Packages.azure-mgmt-privatedns</li>
    <li>python37Packages.azure-mgmt-rdbms</li>
    <li>python37Packages.azure-mgmt-recoveryservices</li>
    <li>python37Packages.azure-mgmt-recoveryservicesbackup</li>
    <li>python37Packages.azure-mgmt-redhatopenshift</li>
    <li>python37Packages.azure-mgmt-relay</li>
    <li>python37Packages.azure-mgmt-reservations</li>
    <li>python37Packages.azure-mgmt-resource</li>
    <li>python37Packages.azure-mgmt-scheduler</li>
    <li>python37Packages.azure-mgmt-search</li>
    <li>python37Packages.azure-mgmt-security</li>
    <li>python37Packages.azure-mgmt-servicefabric</li>
    <li>python37Packages.azure-mgmt-signalr</li>
    <li>python37Packages.azure-mgmt-sqlvirtualmachine</li>
    <li>python37Packages.azure-mgmt-storage</li>
    <li>python37Packages.azure-mgmt-subscription</li>
    <li>python37Packages.azure-mgmt-synapse</li>
    <li>python37Packages.azure-mgmt-trafficmanager</li>
    <li>python37Packages.azure-multiapi-storage</li>
    <li>python37Packages.azure-servicefabric</li>
    <li>python37Packages.azure-servicemanagement-legacy</li>
    <li>python37Packages.azure-storage</li>
    <li>python37Packages.azure-storage-blob</li>
    <li>python37Packages.azure-storage-common</li>
    <li>python37Packages.azure-storage-file</li>
    <li>python37Packages.azure-storage-file-share</li>
    <li>python37Packages.azure-storage-queue</li>
    <li>python37Packages.azure-synapse-accesscontrol</li>
    <li>python37Packages.azure-synapse-artifacts</li>
    <li>python37Packages.azure-synapse-spark</li>
    <li>python37Packages.snowflake-connector-python</li>
    <li>python37Packages.snowflake-sqlalchemy</li>
    <li>python38Packages.azure-appconfiguration</li>
    <li>python38Packages.azure-applicationinsights</li>
    <li>python38Packages.azure-batch</li>
    <li>python38Packages.azure-common</li>
    <li>python38Packages.azure-core</li>
    <li>python38Packages.azure-cosmosdb-table</li>
    <li>python38Packages.azure-datalake-store</li>
    <li>python38Packages.azure-eventgrid</li>
    <li>python38Packages.azure-graphrbac</li>
    <li>python38Packages.azure-keyvault</li>
    <li>python38Packages.azure-keyvault-administration</li>
    <li>python38Packages.azure-keyvault-certificates</li>
    <li>python38Packages.azure-keyvault-keys</li>
    <li>python38Packages.azure-keyvault-secrets</li>
    <li>python38Packages.azure-loganalytics</li>
    <li>python38Packages.azure-mgmt-advisor</li>
    <li>python38Packages.azure-mgmt-apimanagement</li>
    <li>python38Packages.azure-mgmt-appconfiguration</li>
    <li>python38Packages.azure-mgmt-applicationinsights</li>
    <li>python38Packages.azure-mgmt-batch</li>
    <li>python38Packages.azure-mgmt-batchai</li>
    <li>python38Packages.azure-mgmt-billing</li>
    <li>python38Packages.azure-mgmt-botservice</li>
    <li>python38Packages.azure-mgmt-cdn</li>
    <li>python38Packages.azure-mgmt-cognitiveservices</li>
    <li>python38Packages.azure-mgmt-commerce</li>
    <li>python38Packages.azure-mgmt-common</li>
    <li>python38Packages.azure-mgmt-compute</li>
    <li>python38Packages.azure-mgmt-consumption</li>
    <li>python38Packages.azure-mgmt-containerregistry</li>
    <li>python38Packages.azure-mgmt-core</li>
    <li>python38Packages.azure-mgmt-datafactory</li>
    <li>python38Packages.azure-mgmt-datalake-analytics</li>
    <li>python38Packages.azure-mgmt-datalake-store</li>
    <li>python38Packages.azure-mgmt-datamigration</li>
    <li>python38Packages.azure-mgmt-deploymentmanager</li>
    <li>python38Packages.azure-mgmt-devspaces</li>
    <li>python38Packages.azure-mgmt-devtestlabs</li>
    <li>python38Packages.azure-mgmt-dns</li>
    <li>python38Packages.azure-mgmt-eventgrid</li>
    <li>python38Packages.azure-mgmt-eventhub</li>
    <li>python38Packages.azure-mgmt-hanaonazure</li>
    <li>python38Packages.azure-mgmt-hdinsight</li>
    <li>python38Packages.azure-mgmt-imagebuilder</li>
    <li>python38Packages.azure-mgmt-iotcentral</li>
    <li>python38Packages.azure-mgmt-iothub</li>
    <li>python38Packages.azure-mgmt-iothubprovisioningservices</li>
    <li>python38Packages.azure-mgmt-keyvault</li>
    <li>python38Packages.azure-mgmt-kusto</li>
    <li>python38Packages.azure-mgmt-loganalytics</li>
    <li>python38Packages.azure-mgmt-logic</li>
    <li>python38Packages.azure-mgmt-machinelearningcompute</li>
    <li>python38Packages.azure-mgmt-managedservices</li>
    <li>python38Packages.azure-mgmt-managementgroups</li>
    <li>python38Packages.azure-mgmt-managementpartner</li>
    <li>python38Packages.azure-mgmt-maps</li>
    <li>python38Packages.azure-mgmt-marketplaceordering</li>
    <li>python38Packages.azure-mgmt-media</li>
    <li>python38Packages.azure-mgmt-monitor</li>
    <li>python38Packages.azure-mgmt-msi</li>
    <li>python38Packages.azure-mgmt-netapp</li>
    <li>python38Packages.azure-mgmt-network</li>
    <li>python38Packages.azure-mgmt-notificationhubs</li>
    <li>python38Packages.azure-mgmt-policyinsights</li>
    <li>python38Packages.azure-mgmt-powerbiembedded</li>
    <li>python38Packages.azure-mgmt-privatedns</li>
    <li>python38Packages.azure-mgmt-rdbms</li>
    <li>python38Packages.azure-mgmt-recoveryservices</li>
    <li>python38Packages.azure-mgmt-recoveryservicesbackup</li>
    <li>python38Packages.azure-mgmt-redhatopenshift</li>
    <li>python38Packages.azure-mgmt-relay</li>
    <li>python38Packages.azure-mgmt-reservations</li>
    <li>python38Packages.azure-mgmt-resource</li>
    <li>python38Packages.azure-mgmt-scheduler</li>
    <li>python38Packages.azure-mgmt-search</li>
    <li>python38Packages.azure-mgmt-security</li>
    <li>python38Packages.azure-mgmt-servicefabric</li>
    <li>python38Packages.azure-mgmt-signalr</li>
    <li>python38Packages.azure-mgmt-sqlvirtualmachine</li>
    <li>python38Packages.azure-mgmt-storage</li>
    <li>python38Packages.azure-mgmt-subscription</li>
    <li>python38Packages.azure-mgmt-synapse</li>
    <li>python38Packages.azure-mgmt-trafficmanager</li>
    <li>python38Packages.azure-multiapi-storage</li>
    <li>python38Packages.azure-servicefabric</li>
    <li>python38Packages.azure-servicemanagement-legacy</li>
    <li>python38Packages.azure-storage</li>
    <li>python38Packages.azure-storage-blob</li>
    <li>python38Packages.azure-storage-common</li>
    <li>python38Packages.azure-storage-file</li>
    <li>python38Packages.azure-storage-file-share</li>
    <li>python38Packages.azure-storage-queue</li>
    <li>python38Packages.azure-synapse-accesscontrol</li>
    <li>python38Packages.azure-synapse-artifacts</li>
    <li>python38Packages.azure-synapse-spark</li>
    <li>python38Packages.snowflake-connector-python</li>
    <li>python38Packages.snowflake-sqlalchemy</li>
  </ul>
</details>

**Comment by jonringer** [comment]
it should be 1.2.2...

**Comment by jonringer** [comment]
oh, they added it as a new dependency...

**Comment by jonringer** [comment]
should be good now:
```
https://github.com/NixOS/nixpkgs/pull/105267
221 packages built:
appdaemon azure-cli dvc-with-remotes python27Packages.azure-common python37Packages.azure-appconfiguration python37Packages.azure-applicationinsights python37Packages.azure-batch python37Packages.azure-common python37Packages.azure-core python37Packages.azure-cosmosdb-table python37Packages.azure-datalake-store python37Packages.azure-eventgrid python37Packages.azure-graphrbac python37Packages.azure-identity python37Packages.azure-keyvault python37Packages.azure-keyvault-administration python37Packages.azure-keyvault-certificates python37Packages.azure-keyvault-keys python37Packages.azure-keyvault-secrets python37Packages.azure-loganalytics python37Packages.azure-mgmt-advisor python37Packages.azure-mgmt-apimanagement python37Packages.azure-mgmt-appconfiguration python37Packages.azure-mgmt-applicationinsights python37Packages.azure-mgmt-authorization python37Packages.azure-mgmt-batch python37Packages.azure-mgmt-batchai python37Packages.azure-mgmt-billing python37Packages.azure-mgmt-botservice python37Packages.azure-mgmt-cdn python37Packages.azure-mgmt-cognitiveservices python37Packages.azure-mgmt-commerce python37Packages.azure-mgmt-common python37Packages.azure-mgmt-compute python37Packages.azure-mgmt-consumption python37Packages.azure-mgmt-containerinstance python37Packages.azure-mgmt-containerregistry python37Packages.azure-mgmt-containerservice python37Packages.azure-mgmt-core python37Packages.azure-mgmt-cosmosdb python37Packages.azure-mgmt-datafactory python37Packages.azure-mgmt-datalake-analytics python37Packages.azure-mgmt-datalake-store python37Packages.azure-mgmt-datamigration python37Packages.azure-mgmt-deploymentmanager python37Packages.azure-mgmt-devspaces python37Packages.azure-mgmt-devtestlabs python37Packages.azure-mgmt-dns python37Packages.azure-mgmt-eventgrid python37Packages.azure-mgmt-eventhub python37Packages.azure-mgmt-hanaonazure python37Packages.azure-mgmt-hdinsight python37Packages.azure-mgmt-imagebuilder python37Packages.azure-mgmt-iotcentral python37Packages.azure-mgmt-iothub python37Packages.azure-mgmt-iothubprovisioningservices python37Packages.azure-mgmt-keyvault python37Packages.azure-mgmt-kusto python37Packages.azure-mgmt-loganalytics python37Packages.azure-mgmt-logic python37Packages.azure-mgmt-machinelearningcompute python37Packages.azure-mgmt-managedservices python37Packages.azure-mgmt-managementgroups python37Packages.azure-mgmt-managementpartner python37Packages.azure-mgmt-maps python37Packages.azure-mgmt-marketplaceordering python37Packages.azure-mgmt-media python37Packages.azure-mgmt-monitor python37Packages.azure-mgmt-msi python37Packages.azure-mgmt-netapp python37Packages.azure-mgmt-network python37Packages.azure-mgmt-notificationhubs python37Packages.azure-mgmt-policyinsights python37Packages.azure-mgmt-powerbiembedded python37Packages.azure-mgmt-privatedns python37Packages.azure-mgmt-rdbms python37Packages.azure-mgmt-recoveryservices python37Packages.azure-mgmt-recoveryservicesbackup python37Packages.azure-mgmt-redhatopenshift python37Packages.azure-mgmt-redis python37Packages.azure-mgmt-relay python37Packages.azure-mgmt-reservations python37Packages.azure-mgmt-resource python37Packages.azure-mgmt-scheduler python37Packages.azure-mgmt-search python37Packages.azure-mgmt-security python37Packages.azure-mgmt-servicebus python37Packages.azure-mgmt-servicefabric python37Packages.azure-mgmt-signalr python37Packages.azure-mgmt-sql python37Packages.azure-mgmt-sqlvirtualmachine python37Packages.azure-mgmt-storage python37Packages.azure-mgmt-subscription python37Packages.azure-mgmt-synapse python37Packages.azure-mgmt-trafficmanager python37Packages.azure-mgmt-web python37Packages.azure-multiapi-storage python37Packages.azure-servicebus python37Packages.azure-servicefabric python37Packages.azure-servicemanagement-legacy python37Packages.azure-storage python37Packages.azure-storage-blob python37Packages.azure-storage-common python37Packages.azure-storage-file python37Packages.azure-storage-file-share python37Packages.azure-storage-queue python37Packages.azure-synapse-accesscontrol python37Packages.azure-synapse-artifacts python37Packages.azure-synapse-spark python37Packages.msal python37Packages.msal-extensions python37Packages.snowflake-connector-python python37Packages.snowflake-sqlalchemy python38Packages.azure-appconfiguration python38Packages.azure-applicationinsights python38Packages.azure-batch python38Packages.azure-common python38Packages.azure-core python38Packages.azure-cosmosdb-table python38Packages.azure-datalake-store python38Packages.azure-eventgrid python38Packages.azure-graphrbac python38Packages.azure-keyvault python38Packages.azure-keyvault-administration python38Packages.azure-keyvault-certificates python38Packages.azure-keyvault-keys python38Packages.azure-keyvault-secrets python38Packages.azure-loganalytics python38Packages.azure-mgmt-advisor python38Packages.azure-mgmt-apimanagement python38Packages.azure-mgmt-appconfiguration python38Packages.azure-mgmt-applicationinsights python38Packages.azure-mgmt-authorization python38Packages.azure-mgmt-batch python38Packages.azure-mgmt-batchai python38Packages.azure-mgmt-billing python38Packages.azure-mgmt-botservice python38Packages.azure-mgmt-cdn python38Packages.azure-mgmt-cognitiveservices python38Packages.azure-mgmt-commerce python38Packages.azure-mgmt-common python38Packages.azure-mgmt-compute python38Packages.azure-mgmt-consumption python38Packages.azure-mgmt-containerinstance python38Packages.azure-mgmt-containerregistry python38Packages.azure-mgmt-containerservice python38Packages.azure-mgmt-core python38Packages.azure-mgmt-cosmosdb python38Packages.azure-mgmt-datafactory python38Packages.azure-mgmt-datalake-analytics python38Packages.azure-mgmt-datalake-store python38Packages.azure-mgmt-datamigration python38Packages.azure-mgmt-deploymentmanager python38Packages.azure-mgmt-devspaces python38Packages.azure-mgmt-devtestlabs python38Packages.azure-mgmt-dns python38Packages.azure-mgmt-eventgrid python38Packages.azure-mgmt-eventhub python38Packages.azure-mgmt-hanaonazure python38Packages.azure-mgmt-hdinsight python38Packages.azure-mgmt-imagebuilder python38Packages.azure-mgmt-iotcentral python38Packages.azure-mgmt-iothub python38Packages.azure-mgmt-iothubprovisioningservices python38Packages.azure-mgmt-keyvault python38Packages.azure-mgmt-kusto python38Packages.azure-mgmt-loganalytics python38Packages.azure-mgmt-logic python38Packages.azure-mgmt-machinelearningcompute python38Packages.azure-mgmt-managedservices python38Packages.azure-mgmt-managementgroups python38Packages.azure-mgmt-managementpartner python38Packages.azure-mgmt-maps python38Packages.azure-mgmt-marketplaceordering python38Packages.azure-mgmt-media python38Packages.azure-mgmt-monitor python38Packages.azure-mgmt-msi python38Packages.azure-mgmt-netapp python38Packages.azure-mgmt-network python38Packages.azure-mgmt-notificationhubs python38Packages.azure-mgmt-policyinsights python38Packages.azure-mgmt-powerbiembedded python38Packages.azure-mgmt-privatedns python38Packages.azure-mgmt-rdbms python38Packages.azure-mgmt-recoveryservices python38Packages.azure-mgmt-recoveryservicesbackup python38Packages.azure-mgmt-redhatopenshift python38Packages.azure-mgmt-redis python38Packages.azure-mgmt-relay python38Packages.azure-mgmt-reservations python38Packages.azure-mgmt-resource python38Packages.azure-mgmt-scheduler python38Packages.azure-mgmt-search python38Packages.azure-mgmt-security python38Packages.azure-mgmt-servicebus python38Packages.azure-mgmt-servicefabric python38Packages.azure-mgmt-signalr python38Packages.azure-mgmt-sql python38Packages.azure-mgmt-sqlvirtualmachine python38Packages.azure-mgmt-storage python38Packages.azure-mgmt-subscription python38Packages.azure-mgmt-synapse python38Packages.azure-mgmt-trafficmanager python38Packages.azure-mgmt-web python38Packages.azure-multiapi-storage python38Packages.azure-servicebus python38Packages.azure-servicefabric python38Packages.azure-servicemanagement-legacy python38Packages.azure-storage python38Packages.azure-storage-blob python38Packages.azure-storage-common python38Packages.azure-storage-file python38Packages.azure-storage-file-share python38Packages.azure-storage-queue python38Packages.azure-synapse-accesscontrol python38Packages.azure-synapse-artifacts python38Packages.azure-synapse-spark python38Packages.msal python38Packages.msal-extensions python38Packages.snowflake-connector-python python38Packages.snowflake-sqlalchemy
```

**Comment by jonringer** [comment]
I think this is good now. merging

**Pull request merged**
