### PR TITLE
dockerTools: normalize arch to GOARCH

### LINKED ISSUE #106695: dockerTools.buildLayeredImage uses wrong architecture
**Describe the bug**

It seems `dockerTools.buildLayeredImage` generates images with the wrong architecture set. (#104271 began setting these values, but the values before were also wrong)

**To Reproduce**

```console
$ cat docker.nix
{ pkgs ? import <nixpkgs> { inherit crossSystem; }, crossSystem ? null, ... }:

with pkgs;

dockerTools.buildLayeredImage {
  name = "hello";

  config.Entrypoint = [ "${pkgs.hello}/bin/hello" ];
}

$ nix-build ./docker.nix --arg crossSystem '(import <nixpkgs> {}).lib.systems.examples.armv7l-hf-multiplatform'
/nix/store/4cmqs0czx2yrjbd2k0jnjzymwymb7xaw-hello.tar.gz

$ skopeo inspect docker-archive:result | jq .Architecture
"arm32v7"
```

Compared to the current version of [ubuntu:20.10](https://hub.docker.com/layers/ubuntu/library/ubuntu/20.10/images/sha256-04f21a3c6e991895b46604a23ce210ecedfa08b3571cb6f98bcc2909ac98bcf9?context=explore):

```console
$ skopeo inspect docker://ubuntu@sha256:04f21a3c6e991895b46604a23ce210ecedfa08b3571cb6f98bcc2909ac98bcf9 | jq .Architecture
"arm"
```

If you actually run the image on arm, Docker complains.

```console
# uname -p
armv7l

# docker version
Client: Docker Engine - Community
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 19:04:15 2020
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 19:01:54 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

# docker load < result
3c57fc4dc3df: Loading layer [==================================================>]  29.04MB/29.04MB
068a070f8dd3: Loading layer [==================================================>]  399.4kB/399.4kB
bab8c8268779: Loading layer [==================================================>]  10.24kB/10.24kB
Loaded image: hello:1v53220vs60bahnjf2zjvrw9nyrrsnz9

# docker run --rm -it hello:1v53220vs60bahnjf2zjvrw9nyrrsnz9
WARNING: The requested image's platform (linux/arm32v7) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
Hello, world!
```

**Expected behavior**
Architectures embedded in the image configuration should match those generated by Docker.

**Additional context**

The warning message printed by Docker if the running platform doesn't match the image's platform.

https://github.com/moby/moby/blob/d17cf2192c2cda0fa11040b8801a6407636072b8/daemon/create.go#L92-L94

The operating system, architecture, and variant are determined by `GOOS` and `GOARCH`.

https://github.com/moby/moby/blob/d17cf2192c2cda0fa11040b8801a6407636072b8/vendor/github.com/containerd/containerd/platforms/defaults.go#L31-L38

(If the image's architecture is "arm" and the variant is empty, as it almost always is, it is normalized to "v7", see `normalizeArch`)

**Notify maintainers**

- @roberth
- @adisbladis

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.81, NixOS, 20.09.2205.65c9cc79f1d (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-20.09.2205.65c9cc79f1d, nixos-hardware"`
 - channels(terin): `"home-manager-20.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by terinjokes**
Docker (via containerd) and the the OCI Image Configuration imply and
suggest, respectfully, that the architecture set in images matches those
of GOARCH in the Go Language document.

This changeset updates the implimentation of getArch in dockerTools to
return GOARCH values, to satisfy Docker.

Fixes: #106695

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
   - [x] Tested by loading cross-compiled image on arm64 and verifying execution without warnings
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by roberth** [comment]
Tested and improvement suggested here https://github.com/terinjokes/nixpkgs/pull/1.

@adisbladis could you have a look and confirm if these changes still work for you?

**Comment by roberth** [comment]
@ofborg build nixosTests.docker-tools nixosTests.docker-tools-cross

**Comment by roberth** [comment]
Fair enough, ofborg doesn't have remote builders set up, but tests pass locally, ehm remotely.

**Comment by Ericson2314** [comment]
If GOARCH is taking on a significance beyond `Go`, we might move to the lib to match the GCC arch and darwin arch, CC @matthewbauer

**Comment by roberth** [comment]
> If GOARCH is taking on a significance beyond `Go`, we might move to the lib to match the GCC arch and darwin arch, CC @matthewbauer

It does seems so. Taking it from a package is not a problem here. I'm pretty sure that container stuff is strict in `pkgs.go` ;). We could extract it as a function or add it directly into `cpuTypes`. Having all this info in one place seems nice. With `cpuTypes` we remove the need for an extra function. Which is more like a table really. One big table is probably easier to understand than a join of two.

**Pull request merged**
