### PR TITLE
python3Packages.praw: 6.3.1 -> 6.4.0

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
closes #70743

freezes python2 version so it still builds

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

```
[1 built (4 failed), 106 copied (185.0 MiB), 66.7 MiB DL]
error: build of '/nix/store/mfmsw7nwbanjdpgzrijh06n2hbpyd7gy-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/71276
2 package failed to build:
python38Packages.praw python38Packages.sopel

2 package were build:
python37Packages.praw python37Packages.sopel
```

### CODE REVIEW

**Comment by mmahut** [comment]
@GrahamcOfBorg build python37Packages.praw python38Packages.praw

**Comment by jonringer** [comment]
python38Packages.pytest is broken...

**Comment by jonringer** [comment]
@GrahamcOfBorg build python37Packages.praw python27Packages.praw

**Comment by risicle** [comment]
Builds happily on macos 10.13/py37

**Pull request merged**
