### PR TITLE
freecad: 0.19.2 -> 0.20

### PR DESCRIPTION
**Pull request by panicgh**
###### Description of changes

Upstream update.

It would also be nice to have a backport to 22.05. Reason: bugfixes and new features since 0.19.2.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gebner** [comment]
A dependency seems to be marked as broken according to ofborg:
```
error: Package ‘shiboken2-5.15.2’ in /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/ofborg-evaluator-3/pkgs/development/python-modules/shiboken2/default.nix:33 is marked as broken, refusing to evaluate.
```

**Comment by AndersonTorres** [comment]
Broken in Darwin or in Python 3.10.

**Comment by panicgh** [comment]
> Broken in Darwin or in Python 3.10.

Ah, right. Sorry, I tried it on nixos-22.05 branch instead of master and there it worked of course, because it still uses Python 3.9.

**Comment by AndersonTorres** [comment]
I am a bit afraid because, well, this is the exact error of Ofborg:

https://github.com/NixOS/nixpkgs/blob/2a7556a3adce47489e3422e55606f53b36741d53/pkgs/development/python-modules/shiboken2/default.nix#L37

**Comment by panicgh** [comment]
I got it working in a temporary branch [freecad-wip](https://github.com/NixOS/nixpkgs/compare/master...panicgh:freecad-wip). Basically, I updated pyside2 5.15.2 -> 5.15.5 and removed the pinning to python3Packages.boost169 from freecad.

I'll create a PR for pyside2 to python-updates and when that got through, we update freecad. What do you think?

**Comment by panicgh** [comment]
freecad now expectedly [fails in master](https://hydra.nixos.org/eval/1768435?filter=freecad&compare=1768387&full=#tabs-still-succeed) after the pyside2 update. This PR fixes it.

**Comment by Hentioe** [comment]
FreeCAD 0.20 can create threads for holes, I've been looking forward to it for a long time. Thanks for the quick commit to the new version.

**Pull request merged**
