### PR TITLE
[WIP] thunderbird: pass less non-standard flags

### PR DESCRIPTION
**Pull request by lukateras**
Prerequisite to https://github.com/NixOS/nixpkgs/pull/36449. Not tested yet.

### CODE REVIEW

**Comment by jerith666** [comment]
This would not build for me.  I've pushed two new commits on top of it that get it building and basically working:

https://github.com/jerith666/nixpkgs/tree/thunderbird-config-flags
c56165f4 Merge remote-tracking branch 'channels/nixos-unstable' into thunderbird-config-flags
c68c3015 thunderbird: add libpulseaudio build input, disable tests

Only issue I've noticed is that pushing the "play" button in the preferences dialog to test the new-mail sound doesn't work.  But I'm not sure it did before those changes either.

**Comment by jerith666** [comment]
Oh, also: the test failure looks like this:

```
    make[3]: Entering directory '/build/objdir/comm/mail/test/mozmill'
    rm -rf ../../../../_tests/mozmill/../mozmill-virtualenv && \
    mkdir ../../../../_tests/mozmill/../mozmill-virtualenv && \
    unset MACOSX_DEPLOYMENT_TARGET && \
    /build/objdir/_virtualenv/bin/python ../../../../_tests/mozmill/resources/installmozmill.py ../../../../_tests/mozmill/../mozmill-virtualenv
    Using real prefix '/nix/store/9qjc0d5557h3dkpsvfq98b2k96lnb6pw-python-2.7.15'
    New python executable in /build/objdir/_tests/mozmill-virtualenv/bin/python
    Installing setuptools, pip, wheel...done.
    The directory '/homeless-shelter/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Processing /build/thunderbird-60.0/testing/mozbase/manifestparser
    Processing /build/thunderbird-60.0/testing/mozbase/mozfile
    Processing /build/thunderbird-60.0/testing/mozbase/mozinfo
    Processing /build/thunderbird-60.0/testing/mozbase/mozlog
    Processing /build/thunderbird-60.0/testing/mozbase/mozprofile
    Processing /build/thunderbird-60.0/testing/mozbase/mozcrash
    Processing /build/thunderbird-60.0/testing/mozbase/moznetwork
    Processing /build/thunderbird-60.0/testing/mozbase/mozprocess
    Processing /build/thunderbird-60.0/testing/mozbase/mozdevice
    Processing /build/thunderbird-60.0/testing/mozbase/mozrunner
    Processing /build/thunderbird-60.0/python/mozterm
    Processing ./jsbridge
    Processing ./mozmill
    Collecting six>=1.10.0 (from manifestparser==1.2)
      Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff14a0950>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/six/
      Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff14a0ad0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/six/
      Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff14a0c50>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/six/
      Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff14a0dd0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/six/
      Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff14a0f50>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/six/
      Could not find a version that satisfies the requirement six>=1.10.0 (from manifestparser==1.2) (from versions: )
    No matching distribution found for six>=1.10.0 (from manifestparser==1.2)
    Python: 2.7.15 (default, Apr 29 2018, 23:18:59)
    [GCC 7.3.0]
    Failure to install packages
    make[3]: *** [Makefile:28: mozmill-virtualenv] Error 1
    make[3]: Leaving directory '/build/objdir/comm/mail/test/mozmill'
```

**Comment by jerith666** [comment]
I've updated my fork of this with a merge that resolves the conflicts: 9ee0173307ed7e6a5a1b3aa1ab7b94e27d3aa9a5

**Comment by yegortimoshenko** [comment]
Going to pull that; thanks!

**Comment by yegortimoshenko** [comment]
Closing in favor of #55026.

**Pull request closed without merging**
