### PR TITLE
gradle: 5.0 -> 5.3.1

### PR DESCRIPTION
**Pull request by groodt**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
Do we have to keep 6 different gradle versions in nixpkgks? It should be possible to remove some old versions.

**Comment by groodt** [comment]
@xeji It's a good question and a good point. I've taken a quick look and this is what I've done:

* I've bumped the "bugfix" versions of `gradle_4_10` and `gradle_3_5`
* Instead of introducing `gradle_5_0`, I've bumped `gradle_latest` all the way from 5.0 to 5.3.1
* I've identified which nixpkgs are consuming the named gradle versions. Only `gradle_2_14` and `gradle_4_10` are unused by nixpkgs.
* `gradle_2_5` is consumed by packages called `jd-gui` and `mxisd`. If these are updated, then I feel that it might be appropriate to remove both `gradle_2_5` and `gradle_2_14`.

Thoughts?

**Comment by xeji** [comment]
Sounds good, thanks for looking into it. Let's see if the bumped versions build:
@GrahamcOfBorg build gradle gradle_3_5 gradle_4_10

**Comment by groodt** [comment]
@xeji I think I've fixed the issue with the linux build of `gradle`. Please try Ofborg again when you get a chance.

**Comment by xeji** [comment]
@GrahamcOfBorg build gradle gradle_3_5 gradle_4_10

**Pull request merged**
