### PR TITLE
nixos/zfs: Enable trim by default

### PR DESCRIPTION
**Pull request by Baughn**
###### Motivation for this change

Trimming SSDs once per week should be safe in all cases, barring firmware or ZFS bugs. It's the default everywhere else.

*Not* trimming an SSD will wear it out much faster than necessary.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by Baughn** [comment]
@Mic92

**Comment by Mic92** [comment]
Assuming that more and more people will have SSDs/NVMEs these days this seems like a fair assumption. What do you think @fpletz

**Comment by Mic92** [comment]
We also have `services.fstrim.enable`, which could be enabled by default.

**Comment by Baughn** [comment]
I've been using ZFS trim since it was released, with the only data corruption being on 0.8.0 when combined with encryption. That one was resolved...

Enabling fstrim by default would mean relying on *every* other filesystem to work, however.

**Comment by fpletz** [comment]
I feel a bit uneasy enabling this by default since it incurs a performance impact which is unnecessary for spinning disks. According to the related ZFS PR #8419, it will only do trim if the underlying block device supports discard though. If that works as intended :+1: from me. I wonder why ZoL disabled it by default then.

Regarding `services.fstrim`, how does this interact with ZFS since it has its own trimming feature? And how do other filesystems on spinning disks behave if you do a trim?

**Review by ck3d — APPROVED** [review]

**Comment by Mic92** [comment]
`services.fstrim` is orthogonal to zfs, it's just for the same thing for other filesystems (I think ubuntu also has such a timer-activated service running). Also note that services.zfs.trim.enable is a systemd-timer-based weekly trim that is different from the `autotrim` property that is builtin into zfs.
From the `zfs` manpage:

> Be aware that automatic trimming of recently freed data blocks can put significant stress on the underlying storage devices. This will vary depending of how well the specific device handles these commands. For lower end devices it is often possible to achieve most of the benefits of automatic trimming by running an on-demand (manual) TRIM periodically using the zpool trim command.

**Comment by fpletz** [comment]
Okay, thanks! :+1:

**Comment by Baughn** [comment]
Not to let "lower end devices" fool anyone: The fastest devices on the market are NVMe, and all the ones I've found guidance for say to use periodic trim, not continuous.

**Comment by delroth** [comment]
I *think* this PR might have enabled zfs-trim on all systems regardless of whether they use ZFS. I just received a monitoring alert from all my NixOS machines saying that zpool-trim.service had failed execution :-)

**Pull request merged**
