### PR TITLE
wineUnstable: 6.11 -> 6.12

### PR DESCRIPTION
**Pull request by avnik**
Staging updated as well

###### Motivation for this change

Regular wine update

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SFrijters — APPROVED** [review]
`nixpkgs-review` passes, my Windows software still works (with staging), so LGTM.

**Comment by avnik** [comment]
@SFrijters  TY. I tested only games I play daiiy this time. We need more testers, may be some basic test apps (free, or semi/free)

**Review by SuperSandro2000 — APPROVED** [review]
ping me if you want to merge it

**Comment by SFrijters** [comment]
The programs I use (and test with) are a 3D design tool, a database tool, and a music player, so there is at least some spread to the functionality that is being exercised. But indeed, more testers and a more well-defined suite of tests would be nice.

**Comment by avnik** [comment]
@SuperSandro2000  It was ready already ;)  This round is just hashes update, no magic ;)

**Pull request merged**
