### PR TITLE
calibre: 5.44.0 -> 6.6.1

### PR DESCRIPTION
**Pull request by kilianar**
###### Description of changes

Thanks to the great work by @LunNova `PyQt6` finally arrived in nixpkgs and we can update `calibre` to version 6.

https://github.com/kovidgoyal/calibre/releases/tag/v6.6.1

###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by qbit** [comment]
Result of `nixpkgs-review pr 194912` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>calibre</li>
  </ul>
</details>

**Comment by fabianhjr** [comment]
I am having an issue after this upgrade regarding the `ebook-viewer` binary:

```
ebook-viewer                                                         3864ms  Mon 10 Oct 2022 10:28:58 PM CDT
Failed to import PyQt module: PyQt6.QtWebEngineCore with error: No module named 'PyQt6.QtWebEngineCore'
```

Unsure about possible cause; reverting this commit fixes the issue on my machine.

**Comment by LunNova** [comment]
Probably needs a dependency added for pyqt6-webengine as that's separate now. @nrdxp just packaged it in #194833

**Comment by fabianhjr** [comment]
Ah, thanks for the pointer; will test and open a MR if it works. :3

**Comment by vcunat** [comment]
See https://discourse.nixos.org/t/why-is-qt6-qtwebengine-failing-ulimit-n/19539/10

**Pull request merged**
