### PR TITLE
Wrap the python scripts in lxc

### PR DESCRIPTION
**Pull request by globin**
fixes `lxc-ls` and possibly others

### CODE REVIEW

**Comment by globin** [comment]
Rebased

**Comment by lethalman** [comment]
Doesn't build successfully, see the travis error which is relevant to this PR.

**Comment by globin** [comment]
AFAICS this failure has nothing to do with my changes and I would assume that this was the same before?
When building on my machine I don't have that failure either.

**Comment by lethalman** [comment]
Built locally thanks. cc @

**Pull request merged**
