### PR TITLE
python27Packages.cherrypy: deprecating python 2.7

### PR DESCRIPTION
**Pull request by d-goldin**
###### Motivation for this change

A lot of packages have moved on and don't immedaitely support python
2.7 anymore. While it would be possible to patch things up in multiple
corners, python 2.7 is EOL 2020-01-01 so it doesn't seem to be worth it
anymore.

Supersedes: https://github.com/NixOS/nixpkgs/pull/73922
Related: https://github.com/NixOS/nixpkgs/pull/73920

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

There is no maintainer set for cherrypy, so not sure whom to ping except for the usual suspects
cc @FRidh @jonringer 

From commit log: @dotlambda @johanot @marsam

### CODE REVIEW

**Comment by FRidh** [comment]
have a quick search on the issue tracker. You'll find those that often mention cherrypy.

**Comment by flokli** [comment]
@FRidh I checked nixpkgs for usage of cherrypy with python2:

```
pkgs/applications/networking/flexget/default.nix # uses python3
pkgs/applications/networking/p2p/tribler/default.nix # uses python2
pkgs/applications/version-management/bugseverywhere/default.nix # uses python2, but: "Upstream stopped development of this package. If this package does not build anymore, feel free to remove it"
pkgs/development/python-modules/WSME/default.nix # no specific versioning
pkgs/development/python-modules/cheroot/default.nix # no specific versioning
pkgs/development/python-modules/cherrypy/default.nix # python3 version (to be kept)
pkgs/development/python-modules/cherrypy/17.nix # python2 version (to be removed)
pkgs/development/python-modules/ws4py/default.nix # no specific versioning
pkgs/development/python-modules/zerobin/default.nix # no specific versioning
pkgs/games/mnemosyne/default.nix # no specific versioning
pkgs/servers/sickbeard/default.nix # python2 only, but from 2016
pkgs/tools/admin/salt/pepper/default.nix # no specific versioning
pkgs/tools/filesystems/ceph/default.nix # python3
```

I think we should check what of these packages can be moved to python3 by now, but it doesn't look like a too complex thing to solve.

**Comment by FRidh** [comment]
Yes

**Comment by d-goldin** [comment]
I can have a look at some of those packages too.

**Comment by d-goldin** [comment]
Closing, because of lack of interest.

**Pull request closed without merging**
