### PR TITLE
sharkey: init at 2023.9.1.beta5

### PR DESCRIPTION
**Pull request by aprilthepink**
## Description of changes

Initial binary build for Sharkey.
Building from source is currently too difficult,
as that would require us to utilize pnpm,
which manages packages in a unreproducible way at the moment.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by CutestNekoAqua** [comment]
Parts of this are inspired by #161855 
Sharkey is a fork of Misskey, which provides prebuilds which makes it easier to get a initial binary package, plans are to switch to from-source builds once possible.

**Comment by CutestNekoAqua** [comment]
I outplayed the ofborg:tm:

**Comment by cole-h** [comment]
@ofborg eval

**Comment by CutestNekoAqua** [comment]
this should:tm: be ready to evaluate. Currently working on a module for sharkey, misskey and its derivations; that can be added as a seperate commit or so later.

**Comment by Weathercold** [comment]
What’s the status on this?

**Comment by CutestNekoAqua** [comment]
I plan on still packaging stuff like this, but: there currently is so much forking etc going on with misskey adjacent projects than I am thinking about a way on how to best go on about it.

**Comment by CutestNekoAqua** [comment]
continuing it on #296697

**Pull request closed without merging**
