### PR TITLE
nodePackages.emmet-ls: init at 0.3.0

### PR DESCRIPTION
**Pull request by nalves599**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nalves599** [comment]
Fix #162652

**Comment by jfvillablanca** [comment]
I would like to see this merged.

**Comment by Luflosi** [comment]
The conflicts need to be resolved before this can be merged.

**Comment by nalves599** [comment]
I cannot run `generate.sh` because I'm having this [issue](https://discourse.nixos.org/t/wrong-relative-path-to-package-json/27277)

**Comment by winterqt** [comment]
Please try to package this with `buildNpmPackage`.

**Comment by nalves599** [comment]
The problem seems to be with this (line)[https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/node-packages/node-packages.json#L284] because there was a refactor of vscode-extensions (#221878) which made the path change from '../../applications/editors/vscode/extensions/rust-analyzer/build-deps' to '../../applications/editors/vscode/extensions/rust-lang.rust-analyzer/build-deps'

**Comment by nalves599** [comment]
I opened a new PR to solve the problem (#226651)

**Comment by winterqt** [comment]
> Please try to package this with `buildNpmPackage`.

Please try this, it's much better than working with the node-packages blob.

**Comment by jfvillablanca** [comment]
I have been trying to package this as an overlay
```nix
final: prev:
{
  "emmet-ls" = prev.buildNpmPackage rec {
    pname = "emmet-ls";
    version = "0.3.1";
    src = prev.fetchFromGitHub {
      owner = "aca";
      repo = pname;
      rev = "d644b4e56235fd760e1af8ee2a6dad5f3e449f1f";
      hash = "sha256-EocgRF0pW/iNLiUxDRa9MoAMFLWeuMmYroXz91HiNos=";
    };
    npmDepsHash = "sha256-azK0KGPo1r3jJA87E1QNnj54KMxCmBnh6wcagwSU6Fo=";
    npmPackFlags = [ "--ignore-scripts" ];
    npmFlags = [ "--legacy-peer-deps" ];
    makeCacheWritable = true;
  };
}
```
however, there is some trouble with installing dependencies about having no cache available. Here is the log

```
$ nix log /nix/store/1sd4myp03z8ndgmm6shz8k45r5f9v0pj-emmet-ls-0.3.1.drv
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/wibvz8brkckbdvjc58w461bhyqjggy1q-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
Executing npmConfigHook
Configuring npm
Validating consistency between /build/source/package-lock.json and /nix/store/3da1f91dfq3hpvz7whl09j4kz28qgvvg-emmet-ls-0.3.1-npm-deps/package-lock.json
Making cache writable
Installing dependencies
npm ERR! code ENOTCACHED
npm ERR! request to https://registry.npmjs.org/@types%2fnode failed: cache mode is 'only-if-cached' but no cached response is available.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/cache/_logs/2023-04-30T22_58_30_256Z-debug-0.log

ERROR: npm failed to install dependencies

Here are a few things you can try, depending on the error:
1. Set `makeCacheWritable = true`
  Note that this won't help if npm is complaining about not being able to write to the logs directory -- look above that for the actual error.
2. Set `npmFlags = [ "--legacy-peer-deps" ]`
```

I am unsure if this is an npm issue.

**Comment by ribosomerocker** [comment]
@nalves599 Sorry for bothering you-- any progress?

**Comment by SuperSandro2000** [comment]
We do not want to add more packages to the unmaintainable pile nodePackages is right now. Please explore alternatives like mentioned above. 

The problem above is because emmet-ls is not properly maintaining their lock file.

https://github.com/aca/emmet-ls/pull/68

**Comment by figsoda** [comment]
packaged using `buildNpmPackage` in #252440

**Pull request closed without merging**
