### PR TITLE
utsushi: 3.57.0 -> 3.59.2

### PR DESCRIPTION
**Pull request by wucke13**
###### Motivation for this change

+ adding installChecks
+ building from gitlab source now

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by symphorien** [comment]
Any reason to remove the patches which make this work without imagemagick in the PATH ? See https://github.com/NixOS/nixpkgs/issues/64985#issuecomment-518050879 for motivation.
cc @thedavidmeister for testing.
Nice to see that you enabled the tests.

**Comment by wucke13** [comment]
@symphorien no good ones. I just assumed they were some magic for making the epson distributed thing tarball work without actually looking into them. I'm sorry. I will incorporate them again and test the build, though I prefer my way of wrapping `tesseract`. What do you think in that regard?

**Comment by symphorien** [comment]
Patching is required for imagemagick because otherwise *all* programes using libsane should be wrapped as well, which is not possible. So please revert to using patches.

**Comment by wucke13** [comment]
@symphorien I do not understand about what `libsane` are we talking? Like what breaks due to `libsane` being wrapped?

**Comment by symphorien** [comment]
If you look at the imagemagick patch, you will see that the C code calls convert explicitly. And *any* program on the system can load libsane and thus call this code. Therefore any program can require convert on PATH. The only reasonable solution is to replace `convert` by an absolute path in the C file.

**Comment by wucke13** [comment]
@symphorien Ok, done. This should cover the `get-text-orientation` script too.

**Comment by thedavidmeister** [comment]
@wucke13 ok i'll try testing then

**Comment by thedavidmeister** [comment]
xsane fails to scan:

image

**Comment by thedavidmeister** [comment]
similar for utsushi, the scanner runs but files aren't created

**Comment by wucke13** [comment]
@thedavidmeister please give me detailed information about the setup on which your having trouble scanning. As stated, I was able to scan both with utsushi and and xsane, so your feedback surprises me a little.

I did it like this 
`configuration.nix`:
```
  nixpkgs.config = {
    packageOverrides = super: let self = super.pkgs; in {
      current = (import /* insert absolute path to checkout of my branch, ending with `/nixpkgs` */ {
        config = config.nixpkgs.config;
      });
    };
  };
# ...
  services.udev.packages = with pkgs; [ current.utsushi ];
  hardware.sane = {
      enable = true;
      extraBackends = with pkgs; [ current.utsushi ];
    };
# ...
  environment.systemPackages = with pkgs; [ xsane ];
```
The scanner that I was using is the integrated scanner of an Epson ET-3750.
So, how what exactly did you do what ultimately failed?

**Comment by wucke13** [comment]
ping @thedavidmeister

**Comment by grahamc** [comment]
@GrahamcOfBorg build utsushi

**Comment by grahamc** [comment]
(note it wasn't a bot, but https://github.com/NixOS/nixpkgs/pull/70645 and https://github.com/NixOS/nixpkgs/issues/68361)

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

**Comment by wucke13** [comment]
@grahamc Please backport too, I would like to not wait another 5 1/2 months until I can scan with on a stable system... Also: thank you for taking the time on this matter!

**Comment by grahamc** [comment]
@wucke13 Thank you! Please open another PR backporting ot 19.09, with `git cherry-pick -x 9eb00acbbee63d20a6ac7c124005089a8bebcfba`.

**Comment by thedavidmeister** [comment]
my testing was pretty simple, i set my `nixos` channel to the fork commit and ran `nixos-rebuild`

i have all the packages included as explained above, i was using utsushi when it was first merged

as this is merged i'll swap back to the latest master, rebuild nixos and see what happens :man_shrugging:

**Comment by wucke13** [comment]
@thedavidmeister Okay okay. What of scanner model do you use? Please do a full restart after the rebuild and before the testing. Can you also give information about the scanners ownership and permissions (`lsusb` to get its major and minor device node, `ls -l /dev/bus/usb/<major>/<minor>`  to get permission and ownership) and about your users groups (`groups`)? Last but not least please provide the out of `env SANE_DEBUG_DLL=4 scanimage -L`.

**Pull request merged**
