### PR TITLE
sphinx: 2.2.2 -> 2.3.1

### PR DESCRIPTION
**Pull request by bgamari**
Just a version bump.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
Do you know if there's any breaking changes? a lot of packages used sphinx to generate documentation

**Comment by jonringer** [comment]
also, please target staging branch as this causes >1000 rebuilds

**Comment by bgamari** [comment]
The only two breaking changes are listed [here](http://www.sphinx-doc.org/en/master/changes.html#release-2-3-0-released-dec-15-2019).

**Comment by jonringer** [comment]
any breaking changes are very concerning, as this will usually mean regressions in some packages.

**Comment by bgamari** [comment]
Fair enough; I suppose the right way to address this would be to try building the reverse dependency set of `sphinx`. However, I don't off-hand know how to do this.

**Comment by FRidh** [comment]
I've included it in https://github.com/NixOS/nixpkgs/pull/79375.

**Comment by FRidh** [comment]
this is in master now

**Pull request closed without merging**
