### PR TITLE
ffmpeg_5: 5.1 -> 5.1.1

### PR DESCRIPTION
**Pull request by zowoq**
https://git.ffmpeg.org/gitweb/ffmpeg.git/blob/1bad30dbe34f2d100b43e8f773d3fe0b5eb23523:/Changelog#l4

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
@ofborg build ffmpeg_5-full

**Comment by zowoq** [comment]
`jellyfin-ffmpeg` was the only new failure.

**Review by justinas — APPROVED** [review]
LGTM re: jellyfin-ffmpeg

**Comment by superherointj** [comment]
`ndi` is marked to not build at hydraPlatforms.
`obs-studio-plugins.obs-ndi` depends on it.
Shouldn't `obs-studio-plugins.obs-ndi` inherit this?
I can mark hydraPlatform at `obs-studio-plugins.obs-ndi` too, but I guess, it should inherit a subset of hydraPlatform because it is dependency.

**Comment by zowoq** [comment]
> Shouldn't `obs-studio-plugins.obs-ndi` inherit the hydraPlatform limitation (just as broken does) because it is a dependency?

It does as hydra doesn't try to build it? ofborg and nixpkgs-review don't work quite the same way so they still count it as a rebuild.

> As a workaround: I can mark hydraPlatform at `obs-studio-plugins.obs-ndi` too.

I don't see the point in doing this as it doesn't scale, the underlying issue should be fixed.

**Comment by superherointj** [comment]
I'm sorry! I have edited your message by mistake!

**Comment by superherointj** [comment]
> It does as hydra doesn't try to build it? ofborg and nixpkgs-review don't work quite the same way so they still count it as a rebuild.

Needs dig in.

> I don't see the point in doing this as it doesn't scale, the underlying issue should be fixed.

I can understand you want a definite solution. I want too. But I'm not ready to provide it.

Disabling hydra builds for `obs-ndi` avoids build failures / noise in the meanwhile a final solution is not available.

As I see value in the workaround: #189266

**Comment by superherointj** [comment]
> It does as hydra doesn't try to build it? ofborg and nixpkgs-review don't work quite the same way so they still count it as a rebuild.
> I don't see the point in doing this as it doesn't scale, the underlying issue should be fixed.

Actually, when I used nixpkgs-review to build displaylink PR (https://github.com/NixOS/nixpkgs/pull/189259#issuecomment-1234186414), it did not list any build package.
Seems to be inheritance that is not happening.

Workaround at: https://github.com/NixOS/nixpkgs/pull/189266

**Pull request merged**
