### PR TITLE
postgresql: add debug versions

### LINKED ISSUE #103024: Postgresql dbgsym version
It would be great to be able to obtain a version of postgres including debug symbols.
(For people actually getting segfaults to properly report a backtrace for example. I know it doesn't seem like there are many bugs in postgres, but I'm actually running into on on version 13)

It's a matter of passing the flags `--enable-debug` when building from source.
so It seems that it should be another configure flag to add here https://github.com/NixOS/nixpkgs/blob/nixos-20.09/pkgs/servers/sql/postgresql/default.nix#L51.
However I'm not sure what's the best way to go about it, since each version should have a dbgsym version associated.

perhaps just like version is inherited for every single package, add a `dbgsym` attribute that would be defined in each package and add a new dbgsym version of each package?
So far it seems to be what makes the most sense to me. I'm curious to have your opinion when you have a moment.

@ocharles @thoughtpolice @danbst @globin @marsam 

Let me know if I'm missing anything.

* homepage URL: postgresql.org/

PS: completely unrelated, but it seems there is a typo here
https://github.com/NixOS/nixpkgs/blob/nixos-20.09/pkgs/servers/sql/postgresql/default.nix#L12
postgreql -> postgresql

### PR DESCRIPTION
**Pull request by happysalada**
##### Motivation for this change

Add postgres versions with debug symbols to get backtrace in case of a segfault

Not sure yet what the best approach is. This is my naive first approach.

closes https://github.com/NixOS/nixpkgs/issues/103024

@ocharles @thoughtpolice @danbst @globin @marsam 

Interested in your thoughts

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by symphorien** [comment]
Can you try making enable-debug true all the time and setting `separateDebugInfo` to true ? Then check that the closure size of the non-debug outputs is still the same. More info on separateDebugInfo in the manual https://nixos.org/manual/nixpkgs/stable/#ssec-fixup-phase and the wiki https://nixos.wiki/wiki/Debug_Symbols

**Comment by happysalada** [comment]
@symphorien Thanks for the tip, this way seems to make a lot more sense.

Here is what I did.
- cd in the nixpkgs forked repository
- then run `nix-build ./ -A postgresql_13`
- run `du -hs ./result/` and check the size. (about 20 mb for each version)

I tried not adding `separateDebugInfo = true;` and it didn't seem to make a difference.

I feel there is something about building packages locally that I don't understand.

**Comment by symphorien** [comment]
You put `separateDebugInfo` on the postgresqlWithPackage derivation, not postgresql itself.

To compute the closure size, use `nix path-info -S` as recommented by the PR template instead of du.

**Comment by happysalada** [comment]
Thank you for your patience on this!

Enabling debug info with separate debug the size is `134966120`
without enable debug, the size is `134965104`

grahamcofborg-eval-check-meta seems to fail but on a `text-cp437` package, It seems unrelated. Not sure what to do about it.

**Comment by symphorien** [comment]
I can build the debug info with your pr:
```
$  nix-build . -A postgresql.debug
/nix/store/wxvhkdfl501cy380kfwzdwfid4rrd0vi-postgresql-11.9-debug
```

**Comment by happysalada** [comment]
Maybe I need to enable something else on my end to enable the debug to show?

I'm using nix version `nix (Nix) 3.0pre20200829_f156513`

I can see that the derivation is built with `--enable-debug` and `separateDebugInfo` but when I try to build `.debug` like you did, this is what I get

```
❯ nix-build . -A postgresql.debug
error: --- AttrPathNotFound -------------------------------------------------------------------------------------------------------------------------- nix-build
attribute 'debug' in selection path 'postgresql.debug' not found
```

**Comment by symphorien** [comment]
Huh ? If we have the same checkout, we should get the same evaluation... can you double check?

**Comment by happysalada** [comment]
I've attached more information below. I have checked my branch. I have tried building the normal postgres. It seems I still get the same error.

```
nixpkgs on  postgresql_add_debug
❯ nix-build . -A postgresql.debug
error: --- AttrPathNotFound -------------------------------------------------------------------------------------------------------------------------- nix-build
attribute 'debug' in selection path 'postgresql.debug' not found
nixpkgs on  postgresql_add_debug
❯ nix-build --version
nix-build (Nix) 3.0pre20200829_f156513
nixpkgs on  postgresql_add_debug
❯ nix-build . -A postgresql
/nix/store/cxrv523j6k4hr7ck5a5hagsk44a7n9yk-postgresql-11.9
```

It there is anything else that I might have forgotten, let me know. I can't think of anything though.

Perhaps it's something wrong with my environment only? I'm on macos, not sure if that should make a difference though.

**Comment by happysalada** [comment]
When you have a moment, we probably need another pair of eyes on this. I'm not sure how to move forward
@ocharles @thoughtpolice @danbst @globin @marsam
(no rush if you're busy)

**Comment by happysalada** [comment]
When you have a moment, we probably need another pair of eyes on this. I'm not sure how to move forward
@ocharles @thoughtpolice @danbst @globin @marsam
(no rush if you're busy)

**Comment by happysalada** [comment]
The debug symbols don't work on macOS, however I tested on nixOS and was able to build them.
I don't understand why the debug symbols don't work on macOS, but most probably they won't be used on that platform.
debug symbols would mostly be used to debug a prod issue in my opinion (That is also what I intend to use them for).

As far as I'm concerned this is ready to merge.
@ocharles @thoughtpolice @danbst @globin @marsam

**Comment by happysalada** [comment]
@ocharles @thoughtpolice @danbst @globin @marsam
I'm ating everybody as I don't know who is the best person to ask.
When you have a moment, I think this is ready to merge.
Let me know if anything of course

**Comment by symphorien** [comment]
Maintainers are not responsive but I think this is low risk enough for me to merge it.

@GrahamcOfBorg test postgresql

**Comment by happysalada** [comment]
@symphorien Thank you!
I'll be testing this in staging next week

**Comment by happysalada** [comment]
I'm seeing some debug symbols on my staging instance.

I am currently having a coredump on production sometimes. I will switch my production and try to inspect the coredump. I'll create an issue if there are any unexpected problems.

Thanks again for the help!

**Pull request merged**
