### PR TITLE
Move nix upgrading instruction to nixpkgs manual

### PR DESCRIPTION
**Pull request by ericsagnes**
###### Motivation for this change

Address #13186
ML thread: [How to upgrade when Nix is too old to evaluate nixpkgs](http://thread.gmane.org/gmane.linux.distributions.nixos/20811)

As the wiki is read only and its information is outdated, nixpkgs manual seemed a natural alternative.

Improvements and feedback are welcome.

cc @garbas

### CODE REVIEW

**Comment by bjornfor** [comment]
The problem is that none of the build artifacts linked on that hydra page work. (Hydra doesn't have binaries anymore, as @vcunat said.)

Also, the solution(s) listed in that ML thread aren't long/complicated. Maybe we can just put some instructions directly into the error message from Nix, instead of having users go visit a web page?

**Comment by ericsagnes** [comment]
> Maybe we can just put some instructions directly into the error message from Nix, instead of having users go visit a web page?

Indeed that sounds simpler, closing the PR.

**Comment by bjornfor** [comment]
It seems automatically using a new nix to do nixos-rebuild was added in 2014, if you follow the git log for ```nixos/modules/installer/tools/nixos-rebuild.sh```. There have been some changes along the way, the last was just before the NixOS 16.03 release. Hopefully upgrades from (very) old installations will simply Just Work from now on :-D

**Comment by ericsagnes** [comment]
> It seems automatically using a new nix to do nixos-rebuild was added in 2014, if you follow the git log for nixos/modules/installer/tools/nixos-rebuild.sh. There have been some changes along the way, the last was just before the NixOS 16.03 release. Hopefully upgrades from (very) old installations will simply Just Work from now on :-D

That's neat! So problem solved for NixOS users.

What about non-NixOS Nix users, is there a similar mechanism?

**Comment by bjornfor** [comment]
Yes, looks like problem solved for NixOS 16.03 users and later (as long as the nix fallback binaries aren't pruned from the binary cache).

Don't know about non-NixOS.

**Comment by garbas** [comment]
@ericbmerritt for non nixos users i usually suggest to just remove /nix and install it again

**Comment by vcunat** [comment]
On non-nixos it should also work to find the /nix/store path of a recent nix, e.g. on Hydra, then `nix-store --realize` that path and `nix-env -i` it. Re-running the installation script will likely also work, and I'd personally expect you don't even need to remove `/nix` before that.

**Pull request closed without merging**
