### PR TITLE
nixos/gitea: Don't include not needed database options depending on type

### PR DESCRIPTION
**Pull request by etu**
###### Motivation for this change
This was discovered in https://github.com/NixOS/nixpkgs/pull/60014

If this works as I expect I think we should backport #60014 to stable together with this fix, to get the security fixes over there at stable.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
cc @ajs124 @srhb

### CODE REVIEW

**Comment by etu** [comment]
@GrahamcOfBorg build nixosTests.gitea

**Comment by ajs124** [comment]
:+1: works for me (on 19.03). Thanks for looking into this.

**Comment by etu** [comment]
@ajs124 Thanks for discovering this and bringing it up :-)

**Comment by srhb** [comment]
Hey, sorry I'm late. I still don't understand why this is necessary. As far as I can tell, the path is already (properly) ignored for other databases. How do I reproduce any issue that makes this PR necessary?

**Comment by ajs124** [comment]
I haven't found a really good reproducer yet, but one (potentially big) difference between the test and my deployment is that I don't explicitly set `services.gitea.database.socket`. That shouldn't lead to the error I was seeing, though.

And now it looks like I can't reproduce it anymore on my own setup, great.

I'd still say that it's cleaner this way, but it looks like it might not be necessary, after all.

**Pull request merged**
