### PR TITLE
I2p: fix service

### PR DESCRIPTION
**Pull request by bendlas**
These are the changes I had to make to get i2p running as a proper systemd service.

cc @joelmo

### CODE REVIEW

**Comment by joelmo** [comment]
Thanks. You removed jdk, does it still build, I don't think jre have the compiler? No hardcoded openjre was used :smile_cat:

**Comment by bendlas** [comment]
Fixed. Thanks! It built on my machine because oraclejdk == oraclejre.

**Comment by joelmo** [comment]
I'm unsure if hydra builds unfree software, does jdk refer to oraclejdk? If this is the case its nice to keep openjdk because building may take around 30-60min on my machine.

**Comment by bendlas** [comment]
jdk and jre refer to icedtea, openjdk or oraclejdk in order of availability. They are also the canonical point for packageOverrides, thus packages should respect them, except if they depend hard on a specific vm.

**Comment by bendlas** [comment]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L3837

**Comment by joelmo** [comment]
Thanks this is nice, I would squash the last three commits, from f1b86e8 and up as they all improve the build.

**Comment by bendlas** [comment]
there you go

**Comment by edwtjo** [comment]
Great guys!

**Pull request merged**
