### PR TITLE
rmfuse: Fix fallout from #139480

### PR DESCRIPTION
**Pull request by adisbladis**
###### Description of changes
I used the wrong incantation when testing this PR, resulting in not actually testing it :/

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
I guess we just merge 9af334d8fcd78bc33590f6b8e3b1ce52d6daf83d? I believe it fixes the issue since the basic eval test is not failing on 550162327f99a99e928739ca4d61a741b17653a2 [so far](https://github.com/NixOS/nixpkgs/runs/6151887717?check_suite_focus=true).

**Comment by adisbladis** [comment]
@bobby285271 I tried that at some point but ofborg still fails eval for some unknown reason...

**Comment by adisbladis** [comment]
I really don't like the fact that ofborg is responsible for evals instead of Github Actions which should have far lower latency.
This workflow has far too much latency.

**Comment by zowoq** [comment]
ofborg evals the base branch first

**Comment by adisbladis** [comment]
@zowoq That would explain it.. This is some terrible UX at play here.

**Comment by adisbladis** [comment]
I'm just going to go ahead and merge the revert for now no matter what ofborg thinks.

**Pull request merged**
