### PR TITLE
alacritty: 0.3.2 -> 0.3.3

### PR DESCRIPTION
**Pull request by xrelkd**
###### Motivation for this change

Update `alacritty` to the latest release.
https://github.com/jwilm/alacritty/releases/tag/v0.3.3
https://github.com/jwilm/alacritty/blob/v0.3.3/CHANGELOG.md

**Note**:
CHANGELOG.md: The xclip dependency has been removed

cc @Mic92 to review. Thank you!

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by mmahut — APPROVED** [review]
- [X] reviewed the diff and commit messages
- [X] made sure ofBorg evals
- [X] run nix-review without any failures
- [X] run and tested the binaries

**Comment by xrelkd** [comment]
@marsam Could you review this PR, if possible?
Thank you very much!

**Comment by marsam** [comment]
@GrahamcOfBorg build alacritty

**Comment by marsam** [comment]
built and tested locally on NixOS and Darwin
Thanks!

**Pull request merged**
