### PR TITLE
azure-cli-extensions: update package set

### PR DESCRIPTION
**Pull request by katexochen**
## Description of changes

Update the extensions that can be generated.

~~PR is currently based on https://github.com/NixOS/nixpkgs/pull/306986, so marking this as draft for now.~~

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by katexochen** [comment]
Result of `nixpkgs-review pr 306999` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>68 packages built:</summary>
  <ul>
    <li>azure-cli-extensions.aks-preview</li>
    <li>azure-cli-extensions.aks-preview.dist</li>
    <li>azure-cli-extensions.amg</li>
    <li>azure-cli-extensions.amg.dist</li>
    <li>azure-cli-extensions.appservice-kube</li>
    <li>azure-cli-extensions.appservice-kube.dist</li>
    <li>azure-cli-extensions.astronomer</li>
    <li>azure-cli-extensions.astronomer.dist</li>
    <li>azure-cli-extensions.automation</li>
    <li>azure-cli-extensions.automation.dist</li>
    <li>azure-cli-extensions.compute-diagnostic-rp</li>
    <li>azure-cli-extensions.compute-diagnostic-rp.dist</li>
    <li>azure-cli-extensions.confluent</li>
    <li>azure-cli-extensions.confluent.dist</li>
    <li>azure-cli-extensions.connectedvmware</li>
    <li>azure-cli-extensions.connectedvmware.dist</li>
    <li>azure-cli-extensions.cosmosdb-preview</li>
    <li>azure-cli-extensions.cosmosdb-preview.dist</li>
    <li>azure-cli-extensions.datamigration</li>
    <li>azure-cli-extensions.datamigration.dist</li>
    <li>azure-cli-extensions.dataprotection</li>
    <li>azure-cli-extensions.dataprotection.dist</li>
    <li>azure-cli-extensions.desktopvirtualization</li>
    <li>azure-cli-extensions.desktopvirtualization.dist</li>
    <li>azure-cli-extensions.devcenter</li>
    <li>azure-cli-extensions.devcenter.dist</li>
    <li>azure-cli-extensions.edgezones</li>
    <li>azure-cli-extensions.edgezones.dist</li>
    <li>azure-cli-extensions.firmwareanalysis</li>
    <li>azure-cli-extensions.firmwareanalysis.dist</li>
    <li>azure-cli-extensions.fleet</li>
    <li>azure-cli-extensions.fleet.dist</li>
    <li>azure-cli-extensions.gallery-service-artifact</li>
    <li>azure-cli-extensions.gallery-service-artifact.dist</li>
    <li>azure-cli-extensions.hdinsightonaks</li>
    <li>azure-cli-extensions.hdinsightonaks.dist</li>
    <li>azure-cli-extensions.k8s-extension</li>
    <li>azure-cli-extensions.k8s-extension.dist</li>
    <li>azure-cli-extensions.maintenance</li>
    <li>azure-cli-extensions.maintenance.dist</li>
    <li>azure-cli-extensions.managednetworkfabric</li>
    <li>azure-cli-extensions.managednetworkfabric.dist</li>
    <li>azure-cli-extensions.mdp</li>
    <li>azure-cli-extensions.mdp.dist</li>
    <li>azure-cli-extensions.mobile-network</li>
    <li>azure-cli-extensions.mobile-network.dist</li>
    <li>azure-cli-extensions.nginx</li>
    <li>azure-cli-extensions.nginx.dist</li>
    <li>azure-cli-extensions.scheduled-query</li>
    <li>azure-cli-extensions.scheduled-query.dist</li>
    <li>azure-cli-extensions.self-help</li>
    <li>azure-cli-extensions.self-help.dist</li>
    <li>azure-cli-extensions.spring</li>
    <li>azure-cli-extensions.spring.dist</li>
    <li>azure-cli-extensions.stack-hci-vm</li>
    <li>azure-cli-extensions.stack-hci-vm.dist</li>
    <li>azure-cli-extensions.standbypool</li>
    <li>azure-cli-extensions.standbypool.dist</li>
    <li>azure-cli-extensions.support</li>
    <li>azure-cli-extensions.support.dist</li>
    <li>azure-cli-extensions.trustedsigning</li>
    <li>azure-cli-extensions.trustedsigning.dist</li>
    <li>azure-cli-extensions.virtual-wan</li>
    <li>azure-cli-extensions.virtual-wan.dist</li>
    <li>azure-cli-extensions.vm-repair</li>
    <li>azure-cli-extensions.vm-repair.dist</li>
    <li>azure-cli-extensions.workloads</li>
    <li>azure-cli-extensions.workloads.dist</li>
  </ul>
</details>

**Comment by katexochen** [comment]
Rebase on master.

---

Result of `nixpkgs-review pr 306999` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>68 packages built:</summary>
  <ul>
    <li>azure-cli-extensions.aks-preview</li>
    <li>azure-cli-extensions.aks-preview.dist</li>
    <li>azure-cli-extensions.amg</li>
    <li>azure-cli-extensions.amg.dist</li>
    <li>azure-cli-extensions.appservice-kube</li>
    <li>azure-cli-extensions.appservice-kube.dist</li>
    <li>azure-cli-extensions.astronomer</li>
    <li>azure-cli-extensions.astronomer.dist</li>
    <li>azure-cli-extensions.automation</li>
    <li>azure-cli-extensions.automation.dist</li>
    <li>azure-cli-extensions.compute-diagnostic-rp</li>
    <li>azure-cli-extensions.compute-diagnostic-rp.dist</li>
    <li>azure-cli-extensions.confluent</li>
    <li>azure-cli-extensions.confluent.dist</li>
    <li>azure-cli-extensions.connectedvmware</li>
    <li>azure-cli-extensions.connectedvmware.dist</li>
    <li>azure-cli-extensions.cosmosdb-preview</li>
    <li>azure-cli-extensions.cosmosdb-preview.dist</li>
    <li>azure-cli-extensions.datamigration</li>
    <li>azure-cli-extensions.datamigration.dist</li>
    <li>azure-cli-extensions.dataprotection</li>
    <li>azure-cli-extensions.dataprotection.dist</li>
    <li>azure-cli-extensions.desktopvirtualization</li>
    <li>azure-cli-extensions.desktopvirtualization.dist</li>
    <li>azure-cli-extensions.devcenter</li>
    <li>azure-cli-extensions.devcenter.dist</li>
    <li>azure-cli-extensions.edgezones</li>
    <li>azure-cli-extensions.edgezones.dist</li>
    <li>azure-cli-extensions.firmwareanalysis</li>
    <li>azure-cli-extensions.firmwareanalysis.dist</li>
    <li>azure-cli-extensions.fleet</li>
    <li>azure-cli-extensions.fleet.dist</li>
    <li>azure-cli-extensions.gallery-service-artifact</li>
    <li>azure-cli-extensions.gallery-service-artifact.dist</li>
    <li>azure-cli-extensions.hdinsightonaks</li>
    <li>azure-cli-extensions.hdinsightonaks.dist</li>
    <li>azure-cli-extensions.k8s-extension</li>
    <li>azure-cli-extensions.k8s-extension.dist</li>
    <li>azure-cli-extensions.maintenance</li>
    <li>azure-cli-extensions.maintenance.dist</li>
    <li>azure-cli-extensions.managednetworkfabric</li>
    <li>azure-cli-extensions.managednetworkfabric.dist</li>
    <li>azure-cli-extensions.mdp</li>
    <li>azure-cli-extensions.mdp.dist</li>
    <li>azure-cli-extensions.mobile-network</li>
    <li>azure-cli-extensions.mobile-network.dist</li>
    <li>azure-cli-extensions.nginx</li>
    <li>azure-cli-extensions.nginx.dist</li>
    <li>azure-cli-extensions.scheduled-query</li>
    <li>azure-cli-extensions.scheduled-query.dist</li>
    <li>azure-cli-extensions.self-help</li>
    <li>azure-cli-extensions.self-help.dist</li>
    <li>azure-cli-extensions.spring</li>
    <li>azure-cli-extensions.spring.dist</li>
    <li>azure-cli-extensions.stack-hci-vm</li>
    <li>azure-cli-extensions.stack-hci-vm.dist</li>
    <li>azure-cli-extensions.standbypool</li>
    <li>azure-cli-extensions.standbypool.dist</li>
    <li>azure-cli-extensions.support</li>
    <li>azure-cli-extensions.support.dist</li>
    <li>azure-cli-extensions.trustedsigning</li>
    <li>azure-cli-extensions.trustedsigning.dist</li>
    <li>azure-cli-extensions.virtual-wan</li>
    <li>azure-cli-extensions.virtual-wan.dist</li>
    <li>azure-cli-extensions.vm-repair</li>
    <li>azure-cli-extensions.vm-repair.dist</li>
    <li>azure-cli-extensions.workloads</li>
    <li>azure-cli-extensions.workloads.dist</li>
  </ul>
</details>

**Review by malt3 — APPROVED** [review]
Builds and looks good to me. I also tested a few extensions. They seem to work fine.

**Review by msanft — APPROVED** [review]
Diff LGTM

Ofborg failures seem unrelated

**Comment by katexochen** [comment]
@ofborg eval

**Pull request merged**
