### PR TITLE
stretchly: 0.21.1 -> 1.2.0

### PR DESCRIPTION
**Pull request by 1000101**
###### Motivation for this change
Update stretchly, with additional housekeeping (remove wrapGAppsHook). Newer versions switched to electron 9 (fixes errors seen in https://github.com/NixOS/nixpkgs/pull/93530) and the update script was missing a dependency. 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 1000101** [comment]
@GrahamcOfBorg build stretchly

**Comment by cdepillabout** [comment]
@1000101 I don't actually use stretchly anymore, would you like to take over maintainership for this?

**Comment by 1000101** [comment]
> @1000101 I don't actually use stretchly anymore, would you like to take over maintainership for this?

Sure, I'd be happy to.

But would you be willing to confirm it's working properly? I haven't used this software before and it seems odd, that you have no control panel (under GNOME at least). The app seems to be working properly, but once you set the settings, you can't really get to the menu to change them other than removing the config file from `~/.config/Stretchly/config.json`. It seems fine in KDE.

**Comment by 1000101** [comment]
@GrahamcOfBorg build stretchly

**Comment by 1000101** [comment]
> @1000101 I don't actually use stretchly anymore, would you like to take over maintainership for this?

Ok, I've changed maintainer to myself and added desktop/icon support so it's possible to launch the app outside of Terminal.

**Review by cdepillabout — APPROVED** [review]
This appears to work.  The system tray icon appears to show up correct.

@1000101 Thanks for taking this over!

**Pull request merged**
