### PR TITLE
haskellPackages: update stackage and hackage

### PR DESCRIPTION
**Pull request by maralorn**
### This Merge

This PR is the regular merge of the `haskell-updates` branch into `master`.

This branch is being continually built and tested by hydra at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates. You may be able to find an up-to-date Hydra build report at [cdepillabout/nix-haskell-updates-status](https://github.com/cdepillabout/nix-haskell-updates-status).

We roughly aim to merge these `haskell-updates` PRs at least once every two weeks. See the @NixOS/haskell [team calendar](https://cloud.maralorn.de/apps/calendar/p/H6migHmKX7xHoTFa) for who is currently in charge of this branch.

### haskellPackages Workflow Summary

Our workflow is currently described in [`pkgs/development/haskell-modules/HACKING.md`](https://github.com/NixOS/nixpkgs/blob/haskell-updates/pkgs/development/haskell-modules/HACKING.md).

The short version is this:
* We regularly update the Stackage and Hackage pins on `haskell-updates` (normally at the beginning of a merge window).
* The community fixes builds of Haskell packages on that branch.
* We aim at at least one merge of `haskell-updates` into `master` every two weeks.
* We only do the merge if the [`mergeable`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/mergeable) job is succeeding on hydra.
* If a [`maintained`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/maintained) package is still broken at the time of merge, we will only merge if the maintainer has been pinged 7 days in advance. (If you care about a Haskell package, become a maintainer!)

More information about Haskell packages in nixpkgs can be found [in the nixpkgs manual](https://nixos.org/manual/nixpkgs/unstable/#haskell).

---

This is the follow-up to #318363. Come to [#haskell:nixos.org](https://matrix.to/#/#haskell:nixos.org) if you have any questions.

### CODE REVIEW

**Comment by maralorn** [comment]
### [haskell-updates build report from hydra](https://hydra.nixos.org/jobset/nixpkgs/haskell-updates)
*evaluation [1807381](https://hydra.nixos.org/eval/1807381) of nixpkgs commit [3db0e82](https://github.com/NixOS/nixpkgs/commits/3db0e826fc0b28414153037ecf8860c1be21d4a2) as of 2024-07-02 18:10 UTC*

🔴 **Branch not mergeable**
  * `mergeable` jobset failed.
  * `maintained` jobset failed.

#### Build summary

 | Platform | Failed ❌ | DependencyFailed ❗ | TimedOut ⌛🚫 | Unfinished ⏳ | Success ✅ | 
 | --- | --- | --- | --- | --- | --- | 
 | [aarch64-darwin 🍏](https://hydra.nixos.org/eval/1807381?filter=.aarch64-darwin) | 89 | 126 | 2 | 28 | 6225 | 
 | [aarch64-linux 📱](https://hydra.nixos.org/eval/1807381?filter=.aarch64-linux) | 35 | 100 | 2 |  | 6374 | 
 | [x86_64-darwin 🍎](https://hydra.nixos.org/eval/1807381?filter=.x86_64-darwin) | 78 | 105 | 2 | 4 | 6269 | 
 | [x86_64-linux 🐧](https://hydra.nixos.org/eval/1807381?filter=.x86_64-linux) | 25 | 103 | 3 | 21 | 6404 | 
#### Maintained Linux packages with build failure
- [ ] [[📱❌]](https://hydra.nixos.org/build/263899005) [[🐧❌]](https://hydra.nixos.org/build/263884023) [haskellPackages.aeson-gadt-th](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.aeson-gadt-th) @alexfmpe
- [ ] [[📱❌]](https://hydra.nixos.org/build/263894582) [[🐧❌]](https://hydra.nixos.org/build/263884286) [haskellPackages.cli-git](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.cli-git) @alexfmpe
- [ ] [[📱❌]](https://hydra.nixos.org/build/263877777) [[🐧❌]](https://hydra.nixos.org/build/263897114) [haskellPackages.dependent-sum-aeson-orphans](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.dependent-sum-aeson-orphans) @alexfmpe
- [ ] [[📱❌]](https://hydra.nixos.org/build/264231489) [[🐧❌]](https://hydra.nixos.org/build/264231490) [echidna](https://hydra.nixos.org/eval/1807381?filter=echidna) @arcz @hellwolf
- [ ] [[📱❌]](https://hydra.nixos.org/build/263904106) [[🐧❌]](https://hydra.nixos.org/build/263884429) [haskellPackages.proto3-wire](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.proto3-wire) @alexfmpe
- [ ] [[📱❌]](https://hydra.nixos.org/build/263982114) [[🐧❌]](https://hydra.nixos.org/build/263982224) [haskellPackages.push-notify-apn](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.push-notify-apn) @mpscholten
#### Maintained Linux packages with failed dependency
- [ ] [[📱❗]](https://hydra.nixos.org/build/264229004) [[🐧❗]](https://hydra.nixos.org/build/264229014) [haskellPackages.cabal-gild](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.cabal-gild) @turion
- [ ] [cachix](https://hydra.nixos.org/eval/1807381?filter=cachix) @domenkozar
  - [[📱❗]](https://hydra.nixos.org/build/264688497) [[🐧❗]](https://hydra.nixos.org/build/264688483) [toplevel](https://hydra.nixos.org/eval/1807381?filter=cachix)
  - [[📱❗]](https://hydra.nixos.org/build/264688423) [[🐧❗]](https://hydra.nixos.org/build/264688510) [haskellPackages](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.cachix)
- [ ] [[📱❗]](https://hydra.nixos.org/build/263892704) [[🐧❗]](https://hydra.nixos.org/build/263879764) [haskellPackages.dependent-monoidal-map](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.dependent-monoidal-map) @alexfmpe
- [ ] [emanote](https://hydra.nixos.org/eval/1807381?filter=emanote) @srid
  - [[📱❗]](https://hydra.nixos.org/build/264504475) [[🐧❗]](https://hydra.nixos.org/build/264504485) [toplevel](https://hydra.nixos.org/eval/1807381?filter=emanote)
  - [[📱❗]](https://hydra.nixos.org/build/264504439) [[🐧❗]](https://hydra.nixos.org/build/264504580) [haskellPackages](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.emanote)
- [ ] [[📱❗]](https://hydra.nixos.org/build/263985127) [[🐧❗]](https://hydra.nixos.org/build/263982901) [haskellPackages.ghcjs-dom-hello](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.ghcjs-dom-hello) @alexfmpe
- [ ] [git-annex](https://hydra.nixos.org/eval/1807381?filter=git-annex) @peti @roosemberth
  - [[📱❗]](https://hydra.nixos.org/build/264858487) [[🐧❗]](https://hydra.nixos.org/build/264858407) [toplevel](https://hydra.nixos.org/eval/1807381?filter=git-annex)
  - [[📱❗]](https://hydra.nixos.org/build/264858337) [[🐧❗]](https://hydra.nixos.org/build/264858360) [haskellPackages](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.git-annex)
- [ ] [haskell-ci](https://hydra.nixos.org/eval/1807381?filter=haskell-ci) @sternenseemann
  - [[📱❗]](https://hydra.nixos.org/build/263886654) [[🐧❗]](https://hydra.nixos.org/build/263889567) [toplevel](https://hydra.nixos.org/eval/1807381?filter=haskell-ci)
  - [[📱❗]](https://hydra.nixos.org/build/263897536) [[🐧❗]](https://hydra.nixos.org/build/263899631) [haskellPackages](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.haskell-ci)
- [ ] [haskell-language-server](https://hydra.nixos.org/eval/1807381?filter=haskell-language-server) @maralorn
  - [[📱❗]](https://hydra.nixos.org/build/263881850) [[🐧❗]](https://hydra.nixos.org/build/263901280) [toplevel](https://hydra.nixos.org/eval/1807381?filter=haskell-language-server)
  - [[📱❗]](https://hydra.nixos.org/build/263877922) [[🐧❗]](https://hydra.nixos.org/build/263888314) [haskell.packages.ghc925](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc925.haskell-language-server)
  - [[📱❗]](https://hydra.nixos.org/build/263896604) [[🐧❗]](https://hydra.nixos.org/build/263898330) [haskell.packages.ghc926](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc926.haskell-language-server)
  - [[📱❗]](https://hydra.nixos.org/build/263883479) [[🐧❗]](https://hydra.nixos.org/build/263904290) [haskell.packages.ghc927](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc927.haskell-language-server)
  - [[📱❗]](https://hydra.nixos.org/build/263886998) [[🐧❗]](https://hydra.nixos.org/build/263890414) [haskell.packages.ghc928](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc928.haskell-language-server)
  - [[📱❗]](https://hydra.nixos.org/build/263894986) [[🐧❗]](https://hydra.nixos.org/build/263898307) [haskell.packages.ghc945](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc945.haskell-language-server)
  - [[📱❗]](https://hydra.nixos.org/build/263898699) [[🐧❗]](https://hydra.nixos.org/build/263897028) [haskell.packages.ghc946](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc946.haskell-language-server)
  - [[📱❗]](https://hydra.nixos.org/build/263883532) [[🐧❗]](https://hydra.nixos.org/build/263877707) [haskell.packages.ghc947](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc947.haskell-language-server)
  - [[📱❗]](https://hydra.nixos.org/build/263882096) [[🐧❗]](https://hydra.nixos.org/build/263901714) [haskell.packages.ghc948](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc948.haskell-language-server)
  - [[📱❗]](https://hydra.nixos.org/build/263892444) [[🐧❗]](https://hydra.nixos.org/build/263898845) [haskell.packages.ghc963](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc963.haskell-language-server)
  - [[📱❗]](https://hydra.nixos.org/build/263903947) [[🐧❗]](https://hydra.nixos.org/build/263883363) [haskell.packages.ghc964](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc964.haskell-language-server)
  - [[📱❗]](https://hydra.nixos.org/build/263898984) [[🐧❗]](https://hydra.nixos.org/build/263888858) [haskell.packages.ghc965](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc965.haskell-language-server)
  - [[📱❗]](https://hydra.nixos.org/build/264229008) [[🐧❗]](https://hydra.nixos.org/build/264229013) [haskell.packages.ghc981](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc981.haskell-language-server)
  - [[📱❗]](https://hydra.nixos.org/build/264229015) [[🐧❗]](https://hydra.nixos.org/build/264229011) [haskell.packages.ghc982](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc982.haskell-language-server)
  - [[📱❗]](https://hydra.nixos.org/build/263878148) [[🐧❗]](https://hydra.nixos.org/build/263883043) [haskellPackages](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.haskell-language-server)
- [ ] [[📱❗]](https://hydra.nixos.org/build/264688537) [[🐧❗]](https://hydra.nixos.org/build/264688425) [hci](https://hydra.nixos.org/eval/1807381?filter=hci) @roberth
- [ ] [hercules-ci-agent](https://hydra.nixos.org/eval/1807381?filter=hercules-ci-agent) @roberth
  - [[📱❗]](https://hydra.nixos.org/build/264858451) [[🐧❗]](https://hydra.nixos.org/build/264858373) [toplevel](https://hydra.nixos.org/eval/1807381?filter=hercules-ci-agent)
  - [[📱❗]](https://hydra.nixos.org/build/264688455) [[🐧❗]](https://hydra.nixos.org/build/264688450) [haskellPackages](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.hercules-ci-agent)
- [ ] [[📱❗]](https://hydra.nixos.org/build/264688338) [[🐧❗]](https://hydra.nixos.org/build/264688343) [haskellPackages.hercules-ci-cli](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.hercules-ci-cli) @roberth
- [ ] [hinit](https://hydra.nixos.org/eval/1807381?filter=hinit) @poscat0x04
  - [[📱❗]](https://hydra.nixos.org/build/263901564) [[🐧❗]](https://hydra.nixos.org/build/263886896) [toplevel](https://hydra.nixos.org/eval/1807381?filter=hinit)
  - [[📱❗]](https://hydra.nixos.org/build/263900729) [[🐧❗]](https://hydra.nixos.org/build/263896460) [haskellPackages](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.hinit)
- [ ] [[📱❗]](https://hydra.nixos.org/build/263984879) [[🐧❗]](https://hydra.nixos.org/build/263985137) [haskellPackages.jsaddle-hello](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.jsaddle-hello) @alexfmpe
- [ ] [[📱❗]](https://hydra.nixos.org/build/263881665) [[🐧❗]](https://hydra.nixos.org/build/263900992) [haskellPackages.jsaddle-webkit2gtk](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.jsaddle-webkit2gtk) @alexfmpe
- [ ] [[🐧❗]](https://hydra.nixos.org/build/264858527) [maintained](https://hydra.nixos.org/eval/1807381?filter=maintained) @cdepillabout @expipiplus1 @maralorn @ncfavier @sternenseemann
- [ ] [[📱✅]](https://hydra.nixos.org/build/263899268) [[🐧❗]](https://hydra.nixos.org/build/263880443) [haskellPackages.massiv](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.massiv) @sheepforce
- [ ] [[📱✅]](https://hydra.nixos.org/build/263879544) [[🐧❗]](https://hydra.nixos.org/build/263886869) [haskellPackages.massiv-io](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.massiv-io) @sheepforce
- [ ] [[📱✅]](https://hydra.nixos.org/build/263904322) [[🐧❗]](https://hydra.nixos.org/build/263902609) [haskellPackages.massiv-test](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.massiv-test) @sheepforce
- [ ] [[🐧❗]](https://hydra.nixos.org/build/264688378) [mergeable](https://hydra.nixos.org/eval/1807381?filter=mergeable) @cdepillabout @expipiplus1 @maralorn @ncfavier @sternenseemann
- [ ] [[📱❗]](https://hydra.nixos.org/build/264688427) [[🐧❗]](https://hydra.nixos.org/build/264688415) [haskellPackages.nix-thunk](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.nix-thunk) @alexfmpe
- [ ] [[📱❗]](https://hydra.nixos.org/build/263878285) [[🐧❗]](https://hydra.nixos.org/build/263903133) [haskellPackages.reflex-dom](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.reflex-dom) @alexfmpe @maralorn
- [ ] [taffybar](https://hydra.nixos.org/eval/1807381?filter=taffybar) @rvl
  - [[📱❗]](https://hydra.nixos.org/build/263984204) [[🐧❗]](https://hydra.nixos.org/build/263984526) [toplevel](https://hydra.nixos.org/eval/1807381?filter=taffybar)
  - [[📱❗]](https://hydra.nixos.org/build/263985404) [[🐧❗]](https://hydra.nixos.org/build/263984953) [haskellPackages](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.taffybar)
- [ ] [termonad](https://hydra.nixos.org/eval/1807381?filter=termonad) @cdepillabout
  - [[📱❗]](https://hydra.nixos.org/build/263904570) [[🐧❗]](https://hydra.nixos.org/build/263902215) [toplevel](https://hydra.nixos.org/eval/1807381?filter=termonad)
  - [[📱❗]](https://hydra.nixos.org/build/263878866) [[🐧❗]](https://hydra.nixos.org/build/263896255) [haskellPackages](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.termonad)
- [ ] [weeder](https://hydra.nixos.org/eval/1807381?filter=weeder) @maralorn
  - [[📱✅]](https://hydra.nixos.org/build/263984945) [[🐧✅]](https://hydra.nixos.org/build/263983058) [haskell.packages.ghc8107](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc8107.weeder)
  - [[📱✅]](https://hydra.nixos.org/build/263981798) [[🐧✅]](https://hydra.nixos.org/build/263983309) [haskell.packages.ghc902](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc902.weeder)
  - [[📱✅]](https://hydra.nixos.org/build/263981982) [[🐧✅]](https://hydra.nixos.org/build/263984994) [haskell.packages.ghc925](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc925.weeder)
  - [[📱✅]](https://hydra.nixos.org/build/263983444) [[🐧✅]](https://hydra.nixos.org/build/263984553) [haskell.packages.ghc926](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc926.weeder)
  - [[📱✅]](https://hydra.nixos.org/build/263985319) [[🐧✅]](https://hydra.nixos.org/build/263982204) [haskell.packages.ghc927](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc927.weeder)
  - [[📱✅]](https://hydra.nixos.org/build/263982180) [[🐧✅]](https://hydra.nixos.org/build/263984681) [haskell.packages.ghc928](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc928.weeder)
  - [[📱✅]](https://hydra.nixos.org/build/263884460) [[🐧✅]](https://hydra.nixos.org/build/263878146) [haskell.packages.ghc945](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc945.weeder)
  - [[📱✅]](https://hydra.nixos.org/build/263893847) [[🐧✅]](https://hydra.nixos.org/build/263889683) [haskell.packages.ghc946](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc946.weeder)
  - [[📱✅]](https://hydra.nixos.org/build/263904189) [[🐧✅]](https://hydra.nixos.org/build/263885926) [haskell.packages.ghc947](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc947.weeder)
  - [[📱✅]](https://hydra.nixos.org/build/263897472) [[🐧✅]](https://hydra.nixos.org/build/263888070) [haskell.packages.ghc948](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc948.weeder)
  - [[📱✅]](https://hydra.nixos.org/build/263893507) [[🐧✅]](https://hydra.nixos.org/build/263903043) [haskell.packages.ghc963](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc963.weeder)
  - [[📱✅]](https://hydra.nixos.org/build/263897835) [[🐧✅]](https://hydra.nixos.org/build/263888040) [haskell.packages.ghc964](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc964.weeder)
  - [[📱✅]](https://hydra.nixos.org/build/263894681) [[🐧✅]](https://hydra.nixos.org/build/263896234) [haskell.packages.ghc965](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc965.weeder)
  - [[📱❗]](https://hydra.nixos.org/build/263985177) [[🐧✅]](https://hydra.nixos.org/build/263981750) [haskell.packages.ghc981](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc981.weeder)
  - [[📱✅]](https://hydra.nixos.org/build/263984002) [[🐧✅]](https://hydra.nixos.org/build/263985062) [haskell.packages.ghc982](https://hydra.nixos.org/eval/1807381?filter=haskell.packages.ghc982.weeder)
  - [[📱✅]](https://hydra.nixos.org/build/263902813) [[🐧✅]](https://hydra.nixos.org/build/263897291) [haskellPackages](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.weeder)
- [ ] [xmonad](https://hydra.nixos.org/eval/1807381?filter=xmonad) @NeQuissimus @dschrempf @ivanbrennan @peti @slotThe
  - [[📱✅]](https://hydra.nixos.org/build/263898565) [[🐧✅]](https://hydra.nixos.org/build/263882308) [haskellPackages](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.xmonad)
  - [[📱❗]](https://hydra.nixos.org/build/264858452) [[🐧❗]](https://hydra.nixos.org/build/264858393) [nixosTests](https://hydra.nixos.org/eval/1807381?filter=nixosTests.xmonad)
- [ ] [[📱❗]](https://hydra.nixos.org/build/263879802) [[🐧❗]](https://hydra.nixos.org/build/263892527) [haskellPackages.xmonad-extras](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.xmonad-extras) @slotThe

**Comment by dschrempf** [comment]
> [xmonad](https://hydra.nixos.org/eval/1807381?filter=xmonad) @NeQuissimus @dschrempf @ivanbrennan @peti @slotThe
[[📱✅]](https://hydra.nixos.org/build/263898565) [[🐧✅]](https://hydra.nixos.org/build/263882308) [haskellPackages](https://hydra.nixos.org/eval/1807381?filter=haskellPackages.xmonad)
[[📱❗]](https://hydra.nixos.org/build/264858452) [[🐧❗]](https://hydra.nixos.org/build/264858393) [nixosTests](https://hydra.nixos.org/eval/1807381?filter=nixosTests.xmonad)

According to Hydra, `nixosTests` was cancelled by a user. Is there anything we can help out with?

**Comment by maralorn** [comment]
I have restarted all mentioned jobs.

**Comment by mpscholten** [comment]
@maralorn just [fixed the issue with `push-notify-apn` upstream](https://github.com/digitallyinduced/push-notify-apn/commit/e54d40516f1b8f912a74df75256bb6bacc931943) and released v0.4.0.2 that contains the fix. So the build should succeed after the next hackage sync

**Comment by maralorn** [comment]
Hm, @mpscholten can we then apply the fix as a patch? Or are you okay with the package being broken on master for a few days?

**Comment by mpscholten** [comment]
I'll do a patch quickly

**Comment by spacekitteh** [comment]
Was the patch made?

**Comment by cdepillabout** [comment]
@spacekitteh Looking at the last few commits, it looks like the relevant patch was applied in 7825445.

**Comment by maralorn** [comment]
I hope I have dealt with all (relevant) open pull requests. If not please ping me.

Yet, there is still a bit of breakage to deal with before we merge:

#### Maintained Linux packages with build failure
- [ ] [[🐧❌]](https://hydra.nixos.org/build/265271358) [haskellPackages.cpython](https://hydra.nixos.org/eval/1807525?filter=haskellPackages.cpython) @sheepforce
- [ ] [[📱❌]](https://hydra.nixos.org/build/265271370) [[🐧❌]](https://hydra.nixos.org/build/265282585) [echidna](https://hydra.nixos.org/eval/1807525?filter=echidna) @arcz @hellwolf
- [ ] [[📱❌]](https://hydra.nixos.org/build/265539085) [[🐧❌]](https://hydra.nixos.org/build/265539186) [koka](https://hydra.nixos.org/eval/1807525?filter=koka) @siraben @sternenseemann
#### Maintained Linux packages with failed dependency
- [ ] [[📱❗]](https://hydra.nixos.org/build/265272467) [[🐧❗]](https://hydra.nixos.org/build/265281052) [haskellPackages.cabal-gild](https://hydra.nixos.org/eval/1807525?filter=haskellPackages.cabal-gild) @turion
- [ ] [[📱❗]](https://hydra.nixos.org/build/265542378) [[🐧❗]](https://hydra.nixos.org/build/265542381) [haskellPackages.ghcjs-dom-hello](https://hydra.nixos.org/eval/1807525?filter=haskellPackages.ghcjs-dom-hello) @alexfmpe
- [ ] [haskell-ci](https://hydra.nixos.org/eval/1807525?filter=haskell-ci) @sternenseemann
  - [[📱❗]](https://hydra.nixos.org/build/265267103) [[🐧❗]](https://hydra.nixos.org/build/265268318) [toplevel](https://hydra.nixos.org/eval/1807525?filter=haskell-ci)
  - [[📱❗]](https://hydra.nixos.org/build/265289228) [[🐧❗]](https://hydra.nixos.org/build/265287439) [haskellPackages](https://hydra.nixos.org/eval/1807525?filter=haskellPackages.haskell-ci)
- [ ] [[📱❗]](https://hydra.nixos.org/build/265542368) [[🐧❗]](https://hydra.nixos.org/build/265542386) [haskellPackages.jsaddle-hello](https://hydra.nixos.org/eval/1807525?filter=haskellPackages.jsaddle-hello) @alexfmpe
- [ ] [[📱❗]](https://hydra.nixos.org/build/265542383) [[🐧❗]](https://hydra.nixos.org/build/265542366) [haskellPackages.jsaddle-webkit2gtk](https://hydra.nixos.org/eval/1807525?filter=haskellPackages.jsaddle-webkit2gtk) @alexfmpe
- [ ] [[📱❗]](https://hydra.nixos.org/build/265539127) [[🐧❗]](https://hydra.nixos.org/build/265539114) [haskellPackages.orbits](https://hydra.nixos.org/eval/1807525?filter=haskellPackages.orbits) @expipiplus1
- [ ] [[📱❗]](https://hydra.nixos.org/build/265542377) [[🐧❗]](https://hydra.nixos.org/build/265542353) [haskellPackages.reflex-dom](https://hydra.nixos.org/eval/1807525?filter=haskellPackages.reflex-dom) @alexfmpe @maralorn

**Comment by hellwolf** [comment]
I will look into updating echidna, which has been what I am after, after all. But I was waiting for this update to be merged.

What's the timeline? This package had been broken for quite a while due to hevm breakage. So I am not sure if this should be any sort of blocker.

**Comment by sheepforce** [comment]
> [[🐧❌]](https://hydra.nixos.org/build/265271358) [haskellPackages.cpython](https://hydra.nixos.org/eval/1807525?filter=haskellPackages.cpython) @sheepforce

This suffers from many removed functions in the C-API of python 3.12. Will require an upstream fix. I will try to fix this upstream but it will take some time, as the project is more or less dead. For the moment please mark it as broken while I try to get a new release for Python 3.12.

**Comment by maralorn** [comment]
@sheepforce, I think for many packages in nixpkgs we currently pin python to 3.11. Maybe that is also an option here?

**Comment by sheepforce** [comment]
> @sheepforce, I think for many packages in nixpkgs we currently pin python to 3.11. Maybe that is also an option here?

Sure, that would work for now! :+1: That gives me some time to come up with a fix. Here is the workaround PR: #325499 325499

**Comment by mpscholten** [comment]
@maralorn can we also get https://github.com/NixOS/nixpkgs/pull/325322 in?

**Comment by sheepforce** [comment]
For reference, the CPython upstream fix is here: https://github.com/zsedem/haskell-cpython/pull/22

**Comment by sternenseemann** [comment]
@ofborg eval

**Pull request merged**
