### PR TITLE
papermc: 1.15.2r161 -> 1.16.2r141

### PR DESCRIPTION
**Pull request by TheUserCreated**
Just updated the version, build number, and sha256 sum

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by danieldk — CHANGES_REQUESTED** [review]
Thank you for submitting this update! Could you update the commit message to follow the [contribution guidelines](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md)?

So, in this case:

```
papermc: 1.15.2r161 -> 1.16.1r135
```

**Comment by TheUserCreated** [comment]
> Thank you for submitting this update! Could you update the commit message to follow the [contribution guidelines](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md)?
> 
> So, in this case:
> 
> ```
> papermc: 1.15.2r161 -> 1.16.1r135
> ```

my mistake, didnt think to add the build number. thanks for the heads up

**Comment by TheUserCreated** [comment]
Unfortunately, this has taken so long to be merged that it is several versions out of date... 
I edited to fix that.

**Review by danieldk — APPROVED** [review]
LGTM

Result of `nixpkgs-review pr 95386` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- papermc
</details>

**Pull request merged**
