### PR TITLE
nodejs: 10.23.0 -> 10.23.1, 12.20.0 -> 12.20.1, 14.15.3 -> 14.15.4, 15.5.0 -> 15.5.1 

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change

https://nodejs.org/en/blog/vulnerability/january-2021-security-releases/

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by erictapen** [comment]
@marsam Any suggestions on how to backport this? Should we bump `release-20.09` to the latest versions?

I don't see any fixes by upstream ontop of e.g. `10.22.1` and manually patching the mentioned CVEs might get hairy.

**Comment by ajs124** [comment]
It's probably fine as long as we stay in the same major release. Or do 10.22 and 10.23 have any incompatibilities?

**Comment by erictapen** [comment]
Pinging all other `nodejs` maintainers here. What do you think?

@gilligan @cko @cillianderoiste

**Comment by marsam** [comment]
Sorry for the delay, backported to 20.09 in https://github.com/NixOS/nixpkgs/pull/109336

**Pull request merged**
