### PR TITLE
bcachefs: support unlocking in systemd-based stage1

### PR DESCRIPTION
**Pull request by lheckemann**
## Description of changes

Draft, because there's no test and there are probably plenty of bugs.

What I want to cover in a test:
- Encrypted root
- Encrypted non-root neededForBoot filesystem

I also don't know what the state of unlocking encrypted bcachefs in stage2 is -- my guess is that it doesn't work and should probably use the same code, so that's another reason this is still a draft.

@JulienMalka @gabriel-doriath-dohler @RaitoBezarius 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lheckemann** [comment]
I'm confused at how the test fails. Unlike the non-systemd initramfs encrypted bcachefs root test and all the other tests (even with systemd initramfs), waiting for `local-fs.target` doesn't seem to result in `/boot` being mounted. Adding a `wait_for_unit("boot.mount")` or `wait_for_unit("local-fs-pre.target")` fixes it for some reason.

**Comment by lheckemann** [comment]
@ofborg test installer-systemd-stage-1.bcachefsEncrypted

**Comment by JulienMalka** [comment]
I tried this and I get `bcachefs: error requesting encryption key: ENOKEY`

**Comment by lheckemann** [comment]
@JulienMalka how are you testing, and at what stage do you get that error message?

**Comment by JulienMalka** [comment]
@lheckemann I am sorry, I found out that the unlocking unit was actually not generated on my setup, which was due to the way I was patching nixpkgs. After a second trial, I can confirm this is working on my `x86_64-linux` laptop :)

**Pull request closed without merging**
