### PR TITLE
ELK 5.6.9 & 6.2.4 & fixes for elasticsearch6 and logstash6 not starting up

### PR DESCRIPTION
**Pull request by basvandijk**
###### Motivation for this change

https://www.elastic.co/guide/en/elasticsearch/reference/6.2/release-notes-6.2.2.html

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by basvandijk** [comment]
@nh2 I pushed a fix for #37102 and also a fix for `logstash6` not starting up due to unpatched shebangs. The `nixos/tests/elk.nix` now succeeds.

@globin care to review?

**Comment by spinus** [comment]
If only package version bump, looks pretty ok, right?
Would be nice to have tests to make sure both es5 and es6 setups are working. Also, would be great to hardcode user (like in all other nix services).

**Comment by adisbladis** [comment]
@spinus There are already tests for elk: https://github.com/NixOS/nixpkgs/blob/f8bf6a9c3fcbff4988635287f0be760906995a65/nixos/tests/elk.nix#L96#106.
I'm running them now and will merge if successful.

**Comment by basvandijk** [comment]
@adisbladis thanks for the merge. It would be great if this can be cherry-picked on 18.03 as well: https://github.com/NixOS/nixpkgs/pull/39104

**Pull request merged**
