### PR TITLE
{asymptote,texlive.bin.xindy}: build binaries without docs and other tex files

### PR DESCRIPTION
**Pull request by xworld21**
## Description of changes
Avoid building docs and other tex files that are already shipped by TeX Live for asymptote and xindy.

This is a not-so-elegant optimisation: it ensures that all TeX Live binaries can be built separately from the combined schemes, to facilitate testing, and *marginally* speeding up evaluation (edit: eval improvement is small).

I wasn't taking this idea seriously until tests timed out while building asymptote https://github.com/NixOS/nixpkgs/pull/299583/checks?check_run_id=23519603102
Testing texlive shouldn't require rebuilding asymptote!

## Things done
- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by 7c6f434c** [comment]
This separately commits to updating asymptote more slowly, right?

**Comment by xworld21** [comment]
> This separately commits to updating asymptote more slowly, right?

True. An alternative could be to use texlive-specific overrides in `texlive.bin.asymptote`, to keep that version locked to whatever is distributed by TeX Live, but allow the top level asymptote to stay close to upstream.

**Comment by 7c6f434c** [comment]
Well, the difference is like one minor version most of the time, and asymptote in general is quite mature, so yet another option would be to have a synchronised «asymptote» thing everywhere, and `asymptote_latest` for those who happen to know what specific things they need from the latest version.

**Comment by xworld21** [comment]
> Well, the difference is like one minor version most of the time, and asymptote in general is quite mature, so yet another option would be to have a synchronised «asymptote» thing everywhere, and `asymptote_latest` for those who happen to know what specific things they need from the latest version.

@7c6f434c  I have finally implemented your asymptote suggestion using `finalAttrs`. Does the override approach look good?

Separately, I think having `asymptote` track upstream and `asymptote_texlive` track TeX Live is more appropriate. It's an easy swap.

**Comment by xworld21** [comment]
> Separately, I think having `asymptote` track upstream and `asymptote_texlive` track TeX Live is more appropriate. It's an easy swap.

Better: `asymptote` tracks upstream, and `texlive.bin.asymptote` overrides to the TeX Live version + uses the TeX Live containers for sty and docs. I have made the change, so that we don't break the new `by-name` rules.

To prove that it works, I have also updated the top level `asymptote` to 2.89.

**Review by 7c6f434c — APPROVED** [review]

**Pull request merged**
