### PR TITLE
ell: 0.59 -> 0.61

### PR DESCRIPTION
**Pull request by trofi**
Changes:
- https://git.kernel.org/pub/scm/libs/ell/ell.git/tree/ChangeLog?h=0.60
- https://git.kernel.org/pub/scm/libs/ell/ell.git/tree/ChangeLog?h=0.61

Closes #268838 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by trofi** [comment]
Looks like it exposed `iwd`'s incomplete header inclusion (or similar):

```
error: builder for '/nix/store/31yjgscir510w00a129l5kj10g4dgh4m-iwd-2.8.drv' failed with exit code 2;
       last 10 log lines:
       > src/ip-pool.c:337:34: error: invalid use of undefined type 'const struct ifaddrmsg'
       >   337 |                 rec.ifindex = ifa->ifa_index;
       >       |                                  ^~
       > src/ip-pool.c: In function 'ip_pool_init':
       > src/ip-pool.c:366:39: error: 'RTNLGRP_IPV4_IFADDR' undeclared (first use in this function)
       >   366 |         if (!l_netlink_register(rtnl, RTNLGRP_IPV4_IFADDR,
       >       |                                       ^~~~~~~~~~~~~~~~~~~
       > make[1]: *** [Makefile:2538: src/ip-pool.o] Error 1 shuffle=3868977690
       > make[1]: *** Waiting for unfinished jobs....
       > make: *** [Makefile:1710: all] Error 2 shuffle=3868977690
       For full logs, run 'nix log /nix/store/31yjgscir510w00a129l5kj10g4dgh4m-iwd-2.8.drv'.
```

**Comment by trofi** [comment]
`iwd` was fixed in https://git.kernel.org/pub/scm/network/wireless/iwd.git/commit/?id=653122498aaf660d3bf9263bf95aa6544ef154c6 (included in `2.10` release).

**Comment by trofi** [comment]
Pulled trivial backport. Ready for review.

**Comment by amaxine** [comment]
@ofborg build ofono bluez

**Comment by trofi** [comment]
Added `iwd` update to `2.10` as well.

**Review by amaxine — APPROVED** [review]
Ta, changes look good to me, let's just wait for ofborg.

**Comment by amaxine** [comment]
@ofborg eval

**Comment by amjoseph-nixpkgs** [comment]
> Thanks. I'd rather we bump iwd together with this than pulling a single commit in

[eiwd](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/ei/eiwd/package.nix) vendors ell for this reason

**Pull request merged**
