### PR TITLE
dns-root-data: init at 2017-06-16

### PR DESCRIPTION
**Pull request by fpletz**
As outlined in https://github.com/NixOS/nixpkgs/commit/cb59381eee5e89079cc855e52777dae7dc29263d#commitcomment-22565238, add a package for dnssec roots and use them in a few packages.

I chose to include an update script and commit `root.keys` into nixpkgs rather than using a fixed output derivation because unbound itself depends on the location of `root.keys`.

~Do we need `root.ds`?~

### CODE REVIEW

**Comment by vcunat** [comment]
We should put both keys in there now already, as the rollover will happen soon.  The DS records certainly are [available now](https://data.iana.org/root-anchors/root-anchors.xml), so we could use those instead.  I immediately can't see the new DNSKEY record, but maybe we can find it somewhere.

**Comment by vcunat** [comment]
Or if we at least add it before branching 17.09...

**Comment by vcunat** [comment]
Ah, debian has them: https://anonscm.debian.org/cgit/pkg-dns/dns-root-data.git/tree/root.key

**Comment by vcunat** [comment]
> Do we need `root.ds`?

In theory, either DS or DNSKEY records are enough.  DNSKEYs are used in the end, but resolvers can simply retrieve current DNSKEY set from the public DNS and verify them via the DS records.

**Comment by fpletz** [comment]
:+1: on the new KSK but `unbound-anchor` only puts the current key into `root.keys` because the new one will be published via DNS on July 11, 2017. I didn't want to commit an unreproducible `root.keys`.

**Comment by 0xABAB** [comment]
I'd expect a feature like this to be tied to a module.

**Comment by fpletz** [comment]
@0xABAB There is no default location for the root anchors, so on non-NixOS systems we won't be able to find them. Therefore it should be implemented in nixpkgs itself rather than a NixOS module.

**Comment by vcunat** [comment]
The new DNSKEY is in public DNS now!  *I'm sorry; I've been terribly out of time lately.*

**Comment by fpletz** [comment]
Thanks for the reminder. I'll check if the script now returns both and push to master. ;)

**Comment by vcunat** [comment]
BTW, the `DS` are also obtainable via `unbound-anchor -F -a root.ds`, which fetches them from https://data.iana.org with pinned certificate.

**Comment by fpletz** [comment]
Cool, then I'll add that to the script. The second DNSKEY has also been fetched.

**Comment by vcunat** [comment]
I believe so!  I just changed some details in 338a1952049.

**Comment by fpletz** [comment]
Thanks! :+1:

**Pull request merged**
