### PR TITLE
enchant: 1.6.1 -> 2.2.3

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
@grahamcofborg build subtitleeditor xneur mate.pluma abiword gnome2.gtkhtml gnome3.gtkhtml gnome3.geary

**Comment by FRidh** [comment]
@GrahamcOfBorg eval

**Comment by FRidh** [comment]
@GrahamcOfBorg eval

**Comment by c0bw3b** [comment]
I tested a nix-review of this:

Result of `nix-review pr 60348` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>9 package are marked as broken and were skipped:</summary>

  - gtk-sharp-3_0 (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - mmex (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - monodevelop (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - notify-sharp (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python27Packages.pywebkitgtk (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - uzbl (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - vimprobable2-unwrapped (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - webkitgtk24x-gtk2 (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - webkitgtk24x-gtk3 (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
</details>
<details>
  <summary>53 package failed to build:</summary>

  - buildbot (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - buildbot-full (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - buildbot-ui (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - dotnetPackages.MonoAddins (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - gio-sharp (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - gnome-sharp (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - gnome2.gtkhtml (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - gnome2.gtkhtml4 (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - gnome3.gtkhtml (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - gtk-sharp-2_0 (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - gtk-sharp-beans (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - gtkspell2 (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - gummi (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - gxneur (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - haskellPackages.enchant (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - hyena (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - mono-addins (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - pdfmod (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - pidgin (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - pidgin-carbons (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - pidgin-latex (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - pidgin-mra (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - pidgin-msn-pecan (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - pidgin-opensteamworks (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - pidgin-osd (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - pidgin-otr (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - pidgin-sipe (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - pidgin-skypeweb (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - pidgin-window-merge (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - pidgin-xmpp-receipts (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - pinta (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - poedit (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - purple-discord (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - purple-facebook (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - purple-hangouts (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - purple-lurch (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - purple-matrix (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - purple-plugin-pack (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - purple-vk-plugin (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - purple-xmpp-http-upload (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.buildbot-plugins.console-view (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.buildbot-plugins.grid-view (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.buildbot-plugins.waterfall-view (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.buildbot-plugins.wsgi-dashboards (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - skype4pidgin (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - subtitleeditor (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - supertux-editor (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - telegram-purple (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - telepathy-haze (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - tomboy (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - toxprpl (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - xiphos (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - xneur (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
</details>
<details>
  <summary>47 package were build:</summary>

  - abiword (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - beets (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - bluefish (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - buku (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - conan (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - empathy (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - enchant (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - enchant1 (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - fcitx (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - fcitx-configtool (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - fcitx-engines.anthy (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - fcitx-engines.chewing (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - fcitx-engines.cloudpinyin (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - fcitx-engines.hangul (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - fcitx-engines.libpinyin (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - fcitx-engines.m17n (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - fcitx-engines.mozc (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - fcitx-engines.rime (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - fcitx-engines.skk (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - fcitx-engines.table-extra (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - fcitx-engines.table-other (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - fcitx-engines.unikey (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - libsForQt5.fcitx-qt5 (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - libsForQt511.fcitx-qt5 (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - mate.pluma (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - psi (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.azure-mgmt-common (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.azure-mgmt-compute (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.azure-mgmt-network (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.azure-mgmt-resource (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.azure-mgmt-storage (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.diff_cover (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.msrest (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.msrestazure (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.pamqp (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.pylint (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.pyls-black (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.pyls-isort (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.pyls-mypy (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.pytest-pylint (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.python-language-server (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.rabbitpy (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.soco (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - python37Packages.trio (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - spyder (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - thonny (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
  - topydo (gnome3.empathy ,libsForQt512.fcitx-qt5 ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui)
</details>

---
Patch available for gtkhtml 4.10 at least :
https://gitweb.gentoo.org/repo/gentoo.git/tree/gnome-extra/gtkhtml/files/enchant-2.patch

**Pull request merged**
