### PR TITLE
Expose minimum required Nix version.

### PR DESCRIPTION
**Pull request by ebzzry**

### CODE REVIEW

**Comment by edolstra** [comment]
Hm, what's the motivation? I mean, if the minimum version is not met, you can't even import Nixpkgs...

Also, what is the `all-packages.nix` argument for? Overloading a function to make it return something completely different seems ugly.

**Comment by ebzzry** [comment]
@edolstra First, I'm not even sure if I'm doing it the right way. Please forgive me for that.

Anyway, the motivation is to have apps/libs that use Nixpkgs use that requirement prior to loading it.. In that way, it is ensured that that version is met before going through the rest of the code. An example of such an application is [try-reflex](https://github.com/ebzzry/try-reflex/tree/dev).

**Comment by vcunat** [comment]
That sounds like a case for throw-catch paradigm, but it seems to me we don't have nice tools for that in nix yet.

**Comment by domenkozar** [comment]
Why can'y you just use `<nixpkgs/minver.nix>`? No need to change `default.nix`

**Comment by ebzzry** [comment]
@domenkozar That's a good point.

**Comment by vcunat** [comment]
The other PR certainly seems nicer.

**Pull request closed without merging**
