### PR TITLE
ruby: 2.4.5 -> 2.4.7, 2.5.5 -> 2.5.6, 2.6.3 -> 2.6.4

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change
+ 2.4.7 https://www.ruby-lang.org/en/news/2019/08/28/ruby-2-4-7-released/
+ 2.5.6 https://www.ruby-lang.org/en/news/2019/08/28/ruby-2-5-6-released/
+ 2.6.4 https://www.ruby-lang.org/en/news/2019/08/28/ruby-2-6-4-released/
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by petabyteboy** [comment]
Should probably go to staging

**Review by manveru — APPROVED** [review]
LGTM

**Comment by alyssais** [comment]
< 1000 packages should be fine for master, according to #nixos-dev.

**Comment by petabyteboy** [comment]
I see

**Pull request merged**
