### PR TITLE
aliases: add linux_5_15 aliases

### PR DESCRIPTION
**Pull request by fabianhjr**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabianhjr** [comment]
Continuation of #144079

**Comment by Ma27** [comment]
Aliases are deprecated backwards-compat things, why should we add them for new stuff?

(I mean, I don't like how stuff was moved around here previously, but supporting two APIs doesn't make sense either to me).

**Comment by fabianhjr** [comment]
Oh, I missed the change :o

I had been using `linuxPackages_` for a while a while and went by inertia. Better change my config then.

**Comment by fabianhjr** [comment]
@Ma27, would it help the migration to add a throw to aliases pointing out to the change?

**Comment by xaverdh** [comment]
> Oh, I missed the change :o
> 
> I had been using `linuxPackages_` for a while a while and went by inertia. Better change my config then.

The idea was that if you want a versioned package, then you use `linuxKernel.*` directly.
The unversioned variants were kept, so as to not break most ppls configs (and its more of an interface saying "I want the latest kernel").

**Comment by xaverdh** [comment]
> Aliases are deprecated backwards-compat things, why should we add them for new stuff?
> 
> (I mean, I don't like how stuff was moved around here previously, but supporting two APIs doesn't make sense either to me).

Can you elaborate what you don't like about the change? Just too much churn for little benefit (the original pr did make good use of the new structure, but sadly didn't make it), or do you have something more specific in mind?

**Comment by xaverdh** [comment]
> @Ma27, would it help the migration to add a throw to aliases pointing out to the change?
> 
> `linuxPackages_5_15 = throw "Deprecated; [Reference]"`

Yes, the idea was to do that eventually. Probably not before 21:11 lands though.

**Comment by xaverdh** [comment]
> > @Ma27, would it help the migration to add a throw to aliases pointing out to the change?
> > `linuxPackages_5_15 = throw "Deprecated; [Reference]"`
> 
> Yes, the idea was to do that eventually. Probably not before 21:11 lands though.
And throw is a bit too intrusive, maybe a `warn`.

**Comment by xaverdh** [comment]
with https://github.com/NixOS/nixpkgs/pull/144079 merged, this change should actually be applied, so we don't invalidate the config of ppl coming from the old release channel.

**Review by xaverdh — APPROVED** [review]

**Pull request merged**
