### PR TITLE
freeglut: 2.8.1 -> 3.0.0 (and some cleanup)

### PR DESCRIPTION
**Pull request by bjornfor**
Currently rebuilding world to see if anything breaks.

### CODE REVIEW

**Comment by bjornfor** [comment]
Travis OOM'ed. `nox-review wip` on my local system indicates no regressions.

**Comment by bjornfor** [comment]
Any feedback from darwin users before I merge? Ping @peti and @cstrahan, found in git log.

**Comment by peti** [comment]
I have no qualified opinion on this matter. Sorry I can't be more helpful.

**Comment by lethalman** [comment]
If things built just merge :+1: we can always fix at later time.

**Comment by vcunat** [comment]
Darwin isn't tested AFAIK, but `glut` doesn't seem a critical package anyway.

**Comment by bjornfor** [comment]
I would have merged it already if it wasn't for darwin. I just thought I'd let darwin maintainers have a look first. I'll merge it soon if nobody comments on the darwin change.

**Comment by bjornfor** [comment]
I hate regressions :-)

**Comment by vcunat** [comment]
You can merge to staging instead. That way we get Hydra test building it on darwin and it doesn't get to master immediately (so there's more time to fix potential darwin problems).

**Comment by bjornfor** [comment]
@vcunat: Good point. Done in 38880d19cb1b1378851c0dc3a496597c67654843 (and parents).

**Comment by vcunat** [comment]
There seems to be a problem on darwin, but it maybe just depends on the config of the machine. http://hydra.nixos.org/build/24954029/nixlog/2/raw

**Comment by bjornfor** [comment]
:-( Don't know how to fix that.

**Pull request closed without merging**
