### PR TITLE
emacs: pass 'withX' to dbus

### PR DESCRIPTION
**Pull request by bbigras**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2 packages built:
emacs-nox mozart2

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 128140` at 7a420776 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>emacs-nox (emacs27-nox)</li>
    <li>mozart2</li>
  </ul>
</details>

**Comment by jtojnar** [comment]
Is it for closure size? Could you explain the motivation in the commit message?

**Comment by bbigras** [comment]
> Is it for closure size? Could you explain the motivation in the commit message?

It's to get rid of unneeded x11 libs on my phone with nix-on-droid.

The closure size is just a tiny bit lower:

```
/nix/store/4h4l1c6228z7xs6za85l80z2dw8dy4fx-emacs-27.2   285.9M
/nix/store/zyjh12bvwi9hljk24a0i7chdhkir30bi-emacs-27.2   279.1M (without x11)
```

I updated the commit msg.

**Comment by adisbladis** [comment]
While I don't mind the goal of this PR the implementation feels a bit hacky and ad-hoc.
Also the resulting closure size difference is not that impressive so I'm not sure it's worth the hackiness.

**Comment by bbigras** [comment]
Ok I'll just use an overlay or something.

**Pull request closed without merging**
