### PR TITLE
dynamic-colors: 2013-12-28 -> 0.2.0

### PR DESCRIPTION
**Pull request by peterhoeg**
Hi all,

first contribution from here. I wanted to try things out with an easy packaging task, so here goes:
- new upstream for package
- changes to packaging:
  - no longer depend on tmux and vim
  - do not inject env variable (and thus we do not use wrapProgram) as upstream does not need it
- we do not have to patch the source
- added myself as maintainer (there was previously none)
###### Things done:
- [X] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zimbatm** [comment]
Please rename the commit to "dynamic-colors: 2013-12-28 -> 0.2.0" to follow the CONTRIBUTING.md rules.

Otherwise looks good ! :+1:

**Comment by peterhoeg** [comment]
@zimbatm - done, but not to be pedantic, but neither CONTRIBUTING.md nor PULL_REQUEST_TEMPLATE.md say anything about naming PRs.

**Comment by zimbatm** [comment]
@peterhoeg it does but you have to follow trough CONTRIBUTIN.md -> manual link and then scan the text to find the right info. We should probably bring it closer.

**Comment by zimbatm** [comment]
Thanks ! Fixed the commit naming and pushed as c6a717d2125a43e2b1ce538a5a5c101782d3453b

**Pull request closed without merging**
