### PR TITLE
fractal: 8 -> 9

### PR DESCRIPTION
**Pull request by Aleksanaa**
Changelog: https://gitlab.gnome.org/World/fractal/-/releases/9

This takes very, very long to build. (About 30 min on Ryzen 7 7840HS)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by nekowinston** [comment]
I tried just bumping this yesterday & adding libseccomp, but this broke images for me. Fractal now uses Glycin, which has [`pkgs.glycin.passthru.glycinPathsPatch`](https://github.com/NixOS/nixpkgs/blob/080166c15633801df010977d9d7474b4a6c549d7/pkgs/by-name/gl/glycin-loaders/package.nix#L63-L66), but the only places this patch is applied to in Nixpkgs is in packages pulled from Gnome mirrors, which include a `./vendor/` directory with all rust dependencies.
We'd have to somehow patch the cargoDeps, to fix the glycin `brwap` path, just like the passthru patch does.
I couldn't find a way to apply patches during `rustPlatform.importCargoLock`.

**Comment by nekowinston** [comment]
I don't think the problem of not being able to view images has been adressed. @drupol

**Comment by drupol** [comment]
Oh nose, sorry about that. Let me know if you want me to revert this.

**Comment by nekowinston** [comment]
No worries, I probably should've left a review instead, my bad.
I just pulled the latest master & built it, images aren't showing for me, and there are plenty of logs like:
```
2024-11-04T19:56:59.526924Z  WARN fractal::utils::media::image::queue: Could not load image from file: No image loaders are configured. You might need to install a package like glycin-loaders.
Used config: Config {
    image_loader: {},
    image_editor: {},
}
```
We should probably revert, as it breaks all images, including profile pictures and attachments.

**Comment by symphorien** [comment]
if patching the crate is impossible, it should be possible to wrap fractal with a shell script called `bwrap` and which calls the real bwrap adding --ro-bind /nix /nix

**Comment by Aleksanaa** [comment]
> We should probably revert, as it breaks all images, including profile pictures and attachments.

But the previous fractal package is completely broken?

**Comment by nekowinston** [comment]
I wasn't aware of that, I'm still using Fractal 8 from nixos-unstable at the moment... 🤔

**Comment by Aleksanaa** [comment]
> if patching the crate is impossible, it should be possible to wrap fractal with a shell script called `bwrap` and which calls the real bwrap adding --ro-bind /nix /nix

Not impossible but this looks better. I'm testing it

**Pull request merged**
