### PR TITLE
Added openarena 0.8.8

### PR DESCRIPTION
**Pull request by alicerum**
Haven't found the must be in repo.

### CODE REVIEW

**Comment by wmertens** [comment]
@wyvie @jagajaga This broke master because stdenv.glibc doesn't exist (?!). See e.g. https://travis-ci.org/NixOS/nixpkgs/builds/45582143 (at the bottom)

**Comment by jagajaga** [comment]
@wmertens hm, strange. Travis was fine when PR was opened.

**Comment by wmertens** [comment]
@jagajaga are you sure? https://travis-ci.org/NixOS/nixpkgs/builds/45113418 Says it didn't...

Either way it's super strange that stdenv.glibc doesn't exist.

**Comment by jagajaga** [comment]
@wmertens I'm tottaly sure (I'm not accepting PR if travis fails).

Yeah, that's strange :fearful:

**Comment by wmertens** [comment]
@jagajaga oh sorry, the PR build was https://travis-ci.org/NixOS/nixpkgs/builds/45051966 and passed. So something between those master commits broke it and openarena was the unlucky first to trigger. Checking further.

**Comment by wyvie** [comment]
@wmertens i'm definitely sure travis build was successful on my pr. i was also quite happy about that fact.

**Pull request merged**
