### PR TITLE
kvmfr: fix build failure for B7-rc1

### LINKED ISSUE #304559: Build failure: kvmfr
### Steps To Reproduce

1. build *kvmfr*

### Build log

```console
[user@system:~]$ nixos-rebuild boot
building the system configuration...                                                                                                                                   
error: builder for '/nix/store/yf0bzpdyzg0rrgf3mls6wnsly5k2b84c-kvmfr-B7-rc1.drv' failed with exit code 1;                                                             
       last 8 log lines:                                                                                                                                               
       > Running phase: unpackPhase                                                                                                                                    
       > unpacking source archive /nix/store/gxa54xkyx9482zac5q1nkjwgbjph1cq9-source                                                                                   
       > source root is source/module                                                                                                                                  
       > Running phase: patchPhase                                                                                                                                     
       > applying patch /nix/store/p1zcdm98cswfmbyi8pvf1d0m3vv8iii2-linux-6-4-compat.patch                                                                             
       > patching file kvmfr.c                                                                                                                                         
       > Hunk #1 FAILED at 539.                                                                                                                                        
       > 1 out of 1 hunk FAILED -- saving rejects to file kvmfr.c.rej                                                                                                  
       For full logs, run 'nix log /nix/store/yf0bzpdyzg0rrgf3mls6wnsly5k2b84c-kvmfr-B7-rc1.drv'.                                                                      
error: 1 dependencies of derivation '/nix/store/llvs7yphmcg793qm5rwv8bj6xq1vqcyr-linux-6.8.5-modules.drv' failed to build                                              
error: 1 dependencies of derivation '/nix/store/gzxxihkwmavmhxrv8shznnpxh48klv0r-nixos-system-Yon-24.05.20240412.cfd6b5f.drv' failed to build

[user@system:~]$ nix log /nix/store/yf0bzpdyzg0rrgf3mls6wnsly5k2b84c-kvmfr-B7-rc1.drv
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/gxa54xkyx9482zac5q1nkjwgbjph1cq9-source
source root is source/module
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
applying patch /nix/store/p1zcdm98cswfmbyi8pvf1d0m3vv8iii2-linux-6-4-compat.patch
patching file kvmfr.c
Hunk #1 FAILED at 539.
1 out of 1 hunk FAILED -- saving rejects to file kvmfr.c.rej
```

### Notify maintainers
@j-brn 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.5, NixOS, 24.05 (Uakari), 24.05.20240410.1042fd8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/r1g09wfd968168f6drdl7agfaf3msik4-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by j-brn**
## Description of changes

fixes https://github.com/NixOS/nixpkgs/issues/304559

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by gmemstr — APPROVED** [review]
Result of `nixpkgs-review pr 305018` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>linuxPackages.kvmfr (linuxKernel.packages.linux_6_6.kvmfr)</li>
    <li>linuxPackages_hardened.kvmfr (linuxPackages_6_6_hardened.kvmfr)</li>
    <li>linuxPackages_latest.kvmfr (linuxKernel.packages.linux_6_8.kvmfr)</li>
    <li>linuxPackages_latest-libre.kvmfr (linuxKernel.packages.linux_latest_libre.kvmfr)</li>
    <li>linuxPackages-libre.kvmfr (linuxKernel.packages.linux_libre.kvmfr)</li>
    <li>linuxPackages_lqx.kvmfr (linuxKernel.packages.linux_lqx.kvmfr)</li>
    <li>linuxPackages_xanmod.kvmfr (linuxKernel.packages.linux_xanmod.kvmfr)</li>
    <li>linuxPackages_xanmod_latest.kvmfr (linuxKernel.packages.linux_xanmod_latest.kvmfr ,linuxPackages_xanmod_stable.kvmfr)</li>
    <li>linuxPackages_zen.kvmfr (linuxKernel.packages.linux_zen.kvmfr)</li>
  </ul>
</details>

**Comment by gmemstr** [comment]
@j-brn Wondering if we should re-generate the patchfile rather than removing it outright, given it was for kernel 6.4 compat.

**Comment by j-brn** [comment]
> @j-brn Wondering if we should re-generate the patchfile rather than removing it outright, given it was for kernel 6.4 compat.

No need, the patch seems to be a backport of https://github.com/gnif/LookingGlass/commit/e32b292cc1ba089db6ed28e4d5eb0fc8cc4c2235, which is already included in the source

**Comment by j-brn** [comment]
Is there anything that blocks this from being merged?

**Comment by Svenum** [comment]
I tryed the fix with an overlay and it works for me perfectly. So I dont see any blocking points.

**Comment by bandithedoge** [comment]
Result of `nixpkgs-review pr 305018` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>linuxPackages.kvmfr (linuxKernel.packages.linux_6_6.kvmfr)</li>
    <li>linuxPackages_hardened.kvmfr (linuxPackages_6_6_hardened.kvmfr)</li>
    <li>linuxPackages_latest.kvmfr (linuxKernel.packages.linux_6_8.kvmfr)</li>
    <li>linuxPackages_latest-libre.kvmfr (linuxKernel.packages.linux_latest_libre.kvmfr)</li>
    <li>linuxPackages-libre.kvmfr (linuxKernel.packages.linux_libre.kvmfr)</li>
    <li>linuxPackages_lqx.kvmfr (linuxKernel.packages.linux_lqx.kvmfr)</li>
    <li>linuxPackages_xanmod.kvmfr (linuxKernel.packages.linux_xanmod.kvmfr)</li>
    <li>linuxPackages_xanmod_latest.kvmfr (linuxKernel.packages.linux_xanmod_latest.kvmfr ,linuxPackages_xanmod_stable.kvmfr)</li>
    <li>linuxPackages_zen.kvmfr (linuxKernel.packages.linux_zen.kvmfr)</li>
  </ul>
</details>

**Review by Janik-Haag — APPROVED** [review]

**Pull request merged**
