### PR TITLE
cmocka: 1.0.1 -> 1.1.1

### PR DESCRIPTION
**Pull request by stephengroat**
###### Motivation for this change

package updated

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by c0bw3b** [comment]
Thanks for your contribution. Could you please squash your 2 commits into one `cmocka: 1.0.1 -> 1.1.1` ?

Have you tested building it?

**Comment by stephengroat** [comment]
no problem, squashed.

i've tested on macOS and ubuntu, not on NixOS

**Comment by c0bw3b** [comment]
nox-review completed successfully on nixos-17.09
```
Result in /tmp/nox-review-wb0zx0wn
total 4
lrwxrwxrwx 1 renaud users 56 15 nov.  22:40 result -> /nix/store/zcf2dwlxbrw4h959j90wazzwz0j40978-autofs-5.1.3
lrwxrwxrwx 1 renaud users 56 15 nov.  22:40 result-2 -> /nix/store/w9dkdxw4hjpkj7dkci5s0nyl3jakgn89-cmocka-1.1.1
lrwxrwxrwx 1 renaud users 63 15 nov.  22:40 result-3 -> /nix/store/fpr235lw2bdihsx31adfybz6a79wcqv8-knot-resolver-1.5.0
lrwxrwxrwx 1 renaud users 55 15 nov.  22:40 result-4 -> /nix/store/rgkif6a8rgcdvvr1543bifkwb0nnykfd-sssd-1.16.0
```

**Review by c0bw3b — APPROVED** [review]

**Comment by stephengroat** [comment]
@c0bw3b i updated the formula to use the `majorVersion`, `version` scheme that i found in https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/gupnp-igd/default.nix

**Comment by c0bw3b** [comment]
Ok works for me.

**Pull request merged**
