### PR TITLE
Make myself a maintainer

### PR DESCRIPTION
**Pull request by Atemu**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/79085#issuecomment-581150929

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
nit https://github.com/NixOS/nixpkgs/pull/79455/commits/39519d2e6a2fec427c2a503239b8c427f761b354, can the message not be uppercase `Maintainers` but just lower case?

**Comment by Atemu** [comment]
Sure, is that the general code style for commit messages in nixpkgs?

**Comment by worldofpeace** [comment]
> Sure, is that the general code style for commit messages in nixpkgs?

Usually it's an attribute path or a file path https://github.com/NixOS/nixpkgs/commits/master/maintainers.
In this case the directory is not uppercase, and the attribute in `stdenv.lib` is `maintainers`.

**Comment by FRidh** [comment]
cc @waynr

**Pull request merged**
