### PR TITLE
heatseeker: init at 1.3.0

### PR DESCRIPTION
**Pull request by michaelpj**
Heatseeker is a nice fuzzy-selector for command-line usage.

### CODE REVIEW

**Comment by michaelpj** [comment]
I don't understand why travis failed: I built this totally fine locally.

**Comment by jagajaga** [comment]
cc @wizeman

**Comment by michaelpj** [comment]
Okay, I ran `nox-review pr 10066` locally and that works too, so I think this must be a spurious failure.

**Comment by lethalman** [comment]
Built locally thanks.

**Pull request merged**
