### PR TITLE
modules/sshd: print the offending keys when we detect duplicate sshd config keys.

### PR DESCRIPTION
**Pull request by r-vdp**
###### Description of changes

Follow-up to #231467, print the offending keys when we detect them to make it easier to correct them.

Ping @teto 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Shawn8901** [comment]
for easier visibility, thats how an error may look like:
```shell
       Failed assertions:
       - Duplicate sshd config key; does your capitalization match the option's? Duplicate keys: (KbdInteractiveAuthentication, kbdInteractiveAuthentication), (PasswordAuthentication, passwordAuthentication)
(use '--show-trace' to show detailed location information)

```

**Review by Shawn8901 — APPROVED** [review]

**Review by nyanotech — APPROVED** [review]
lgtm, seems to pass and fail correctly

**Review by siph — APPROVED** [review]
I tested this with `passwordAuthentication` and `permitRootLogin` and it works fine.

```shell
error:
       Failed assertions:
       - Duplicate sshd config key; does your capitalization match the option's? Duplicate keys: (PasswordAuthentication, passwordAuthentication), (PermitRootLogin, permitRootLogin)

```

**Comment by R-VdP** [comment]
@RaitoBezarius it may be good to merge this and backport it to 23.05 before the release, since the current behaviour on the release branch is pretty confusing.

**Comment by teto** [comment]
I've just tested it and it seems to work. Thanks a lot. 
The ideal scenarii would be: 
- that openssh REALLY checks its config
- that we modify the module to standardize the case, sadly the issue was raised too close to the release process so this change will do.

**Pull request merged**
