### PR TITLE
mesa: build with llvm 16

### PR DESCRIPTION
**Pull request by yu-re-ka**
to reduce the number of llvm versions required

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
`libclc` fails on x86_64-linux now, but mesa builds on aarch64-linux.

```
libclc> [2850/2871] Generating spirv-mesa3d-.spv
libclc> FAILED: spirv-mesa3d-.spv /build/source/libclc/build/spirv-mesa3d-.spv 
libclc> cd /build/source/libclc/build && /nix/store/cc9fzrwdgsv4xsxq6yadzc57h06b4xls-SPIRV-LLVM-Translator-unstable-2022-05-04/bin/llvm-spirv --spirv-max-version=1.1 -o spirv-mesa3d-.spv builtins.link.spirv-mesa3d-.bc
libclc> Invalid value (Producer: 'LLVM16.0.6' Reader: 'LLVM 11.1.0')
libclc> [2851/2871] Generating builtins.opt.cypress-r600--.bc
libclc> [2852/2871] Generating builtins.opt.cedar-r600--.bc
libclc> [2853/2871] Generating builtins.opt.barts-r600--.bc
libclc> [2854/2871] Generating builtins.opt.cayman-r600--.bc
libclc> [2855/2871] Generating builtins.opt.nvptx64--nvidiacl.bc
libclc> ninja: build stopped: subcommand failed.

**Comment by Kiskae** [comment]
> SPIRV-LLVM-Translator-unstable-2022-05-04

Looking at the LLVM-Translator releases, the [release based on llvm16](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/releases/tag/v16.0.0) was published 2023-03-22, so perhaps it will work if that component is updated as well.

**Comment by RicArch97** [comment]
Looks like this one https://github.com/NixOS/nixpkgs/pull/263956 could supersede this

**Comment by vcunat** [comment]
right

**Pull request closed without merging**
