### PR TITLE
binutils 2.35.1 -> 2.36.1

### PR DESCRIPTION
**Pull request by rychale**

### CODE REVIEW

**Comment by lovesegfault** [comment]
This needs to be rebased onto `staging`.

**Comment by r-burns** [comment]
Also, past binutils bumps have been pretty breaking right? Should this have a hydra job?

**Comment by lovesegfault** [comment]
> Also, past binutils bumps have been pretty breaking right? Should this have a hydra job?

Yeah, past binutils bumps were an intense uphill battle requiring multiple people to collaborate over weeks to get them in shape. I speak from experience :P 

This needs a hydra job, and I'll be (positively!) surprised if it doesn't need significant work to fix all the breakages.

**Comment by SuperSandro2000** [comment]
/rebase staging

and the commit message should be ``binutils: 2.35.1 -> 2.36.1``.

**Comment by lovesegfault** [comment]
The user doesn't seem super active, I suggest we close this and I can re-open it.

**Comment by SuperSandro2000** [comment]
> The user doesn't seem super active, I suggest we close this and I can re-open it.

Sure, go ahead.

**Comment by TredwellGit** [comment]
118945

**Pull request closed without merging**
