### PR TITLE
js_of_ocaml: 3.4.0 -> 3.5.2

### PR DESCRIPTION
**Pull request by nomeata**
a  drive-by contribution, as I was playing around with this (it has better
support for the `num` library, it seems.)

### CODE REVIEW

**Comment by vbgl** [comment]
@GrahamcOfBorg build why3

**Review by vbgl — CHANGES_REQUESTED** [review]
This breaks `why3`.

**Comment by nomeata** [comment]
Bummer. No new `why3` release yet, and I did not manage to register for their Gitlab. Guess we’ll just wait until they become compatible with the latest `js_of_ocaml`?

**Comment by vbgl** [comment]
There is no release, but the source has been updated. Maybe you should try a fix like that:

~~~
--- a/pkgs/applications/science/logic/why3/default.nix
+++ b/pkgs/applications/science/logic/why3/default.nix
@@ -1,4 +1,4 @@
-{ callPackage, fetchurl, stdenv
+{ callPackage, fetchurl, fetchpatch, stdenv
 , ocamlPackages, coqPackages, rubber, hevea, emacs }:
 
 stdenv.mkDerivation {
@@ -30,7 +30,13 @@ stdenv.mkDerivation {
   enableParallelBuilding = true;
 
   # Remove unnecessary call to which
-  patches = [ ./configure.patch ];
+  patches = [ ./configure.patch
+    # Compatibility with js_of_ocaml 3.5
+    (fetchpatch {
+      url = "https://gitlab.inria.fr/why3/why3/commit/269ab313382fe3e64ef224813937314748bf7cf0.diff";
+      sha256 = "0i92wdnbh8pihvl93ac0ma1m5g95jgqqqj4kw6qqvbbjjqdgvzwa";
+    })
+  ];
 
   configureFlags = [ "--enable-verbose-make" ];
 
~~~

**Comment by nomeata** [comment]
Thanks, trying that. 
@GrahamcOfBorg build why3

**Review by thoughtpolice — APPROVED** [review]

**Comment by vbgl** [comment]
@GrahamcOfBorg build ocamlPackages.js_of_ocaml-ppx_deriving_json

**Comment by vbgl** [comment]
I’ve just pushed a fix for `js_of_ocaml-ppx_deriving-json`.

Eliom and related packages still need to be updated.

**Comment by vbgl** [comment]
I’ve just pushed an update of eliom and ocsigen-toolkit. In order to update ocsigen-start (which needs pgocaml_ppx), could you please rebase? Thanks.

**Comment by vbgl** [comment]
I’ve force-pushed an update to `ocsigen-start`. I hope you don’t mind.

I believe this is now ready.

**Review by vbgl — APPROVED** [review]

**Comment by nomeata** [comment]
Will this get into 20.03 as well or is it too late for that?

**Comment by vbgl** [comment]
Let’s give it a try!

**Comment by nomeata** [comment]
I guess https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#backporting-changes describes the process. Will give it a try!

**Comment by vbgl** [comment]
You’ll have to cherry-pick 4f7484f03895a75d375dbe9da1e2f370e3a9a9ac & c589de98e247e87b7e6e5274c1226d888c3f207b too.

**Comment by nomeata** [comment]
> You’ll have to cherry-pick [4f7484f](https://github.com/NixOS/nixpkgs/commit/4f7484f03895a75d375dbe9da1e2f370e3a9a9ac) & [c589de9](https://github.com/NixOS/nixpkgs/commit/c589de98e247e87b7e6e5274c1226d888c3f207b) too.

Thanks, that was helpful :-)

**Comment by nomeata** [comment]
@vbgl how does https://github.com/NixOS/nixpkgs/pull/81882 look?

**Pull request merged**
