### PR TITLE
replace deprecated usage of PermissionsStartOnly (part 1)

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
First round of code ready for merging from https://github.com/NixOS/nixpkgs/pull/56265

ping @flokli 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by aanderse** [comment]
@GrahamcOfBorg test clickhouse codicmd etcd ipfs
@GrahamcOfBorg test jackett lidarr mxisd mysql-backup
@GrahamcOfBorg test peerflix radarr smokeping sonarr
@GrahamcOfBorg test vault zookeeper couchdb influxdb

**Comment by flokli** [comment]
Going through the draft PR, there was some discussion about [clickhouse](https://github.com/NixOS/nixpkgs/pull/56265#pullrequestreview-212624941) (which had a static data directory anyway) and [mpd](https://github.com/NixOS/nixpkgs/pull/56265#discussion_r267020491) (with some discussion about the`dataDir` option exposed - which is why this directory's creation was moved to `tmpfiles.d` instead of `StateDirectory`.

We didn't receive any feedback on the changes proposed to the following services/modules:

 - liquidsoap
 - mesos
 - stanchion
 - rss2email
 - rabbitmq
 - nullmailer
 - codimd
 - couchdb
 - jackett
 - ipfs
 - etcd
 - influxdb
 - radarr
 - mysql-backup
 - peerflix
 - smokeping
 - mxisd
 - sonarr
 - zookeeper

Given these are pretty mechanical, and this is unstable, I tend to merge it anyway - it's very granular commits, and we can revert them individually in case of any problems.

@Infinisil, what do you think?

**Comment by Infinisil** [comment]
I think we should double-check these services, but in general I'm fine with merging this soon, the chance of this causing breakage shouldn't be high and the change is quite nice. Considering that `systemd-tmpfiles` (I think) recursively changes permissions, this might even fix some problems.

**Comment by flokli** [comment]
@Infinisil I did review the services, and they LGTM.

`systemd-tmpfiles` doesn't change permissions (except if explicitly requested), `StateDirectory=` etc. only do it in some cases:

**Review by flokli — APPROVED** [review]

**Review by infinisil — APPROVED** [review]

**Comment by flokli** [comment]
:rocket:

**Comment by volth** [comment]
It broke `zookeeper` service.
`${cfg.dataDir}/myid` was owned by `root` and after nixos-19.03 -> 19.09 upgrade it is still owned by root, so `zookeeper` service fails to write to root-owned file and `zookeeper` service fails to start after OS upgrade

I wanted to make a PR with fix but would be undoing of https://github.com/NixOS/nixpkgs/commit/55ddb04a8ae3030fc6363874b65845ec7d2a507b

So this "deprecating usage of PermissionsStartOnly" is very questionable

**Comment by aanderse** [comment]
@volth That is unfortunate. Sorry for the inconvenience. Given what you said I believe the fix should be to add an additional entry to `systemd.tmpfiles.rules`: `"Z '${cfg.dataDir}' 0700 zookeeper - - -"`.

If you would be willing to test that would be appreciated.

**Comment by volth** [comment]
> Given what you said I believe the fix should be to add an additional entry to systemd.tmpfiles.rules: "Z '${cfg.dataDir}' 0700 zookeeper - - -".

Yes, it helped.
Could you commit it before 19.09 release?

**Pull request merged**
