### PR TITLE
gdal: just disable python support instead of marking gdal broken wholesa...

### PR DESCRIPTION
**Pull request by risicle**
...le

### CODE REVIEW

**Comment by lethalman** [comment]
Ok thanks.

**Comment by lethalman** [comment]
cc @iElectric

**Comment by peti** [comment]
I'm pretty sure that merging this patch on top of https://github.com/NixOS/nixpkgs/commit/1645795c53807a83561479eebf25bb1adce003ce is not a good idea.

**Comment by lethalman** [comment]
Oh wow they didn't conflict.... reverted.

**Comment by risicle** [comment]
oh excellent someone fixed it properly

**Pull request merged**
