### PR TITLE
archi: bugfix - added missing glib

### LINKED ISSUE #343272: Runtime Error: archi
### Describe the bug
While investigating the failing test in https://github.com/NixOS/nixpkgs/pull/342229
I noticed that Archi crashes while starting up - if built against the current master.

Bisecting nixpkgs showed that dbd9745e11c65cb89fa81b0181b322cd5683f4cb broke the package. (which was introduced in https://github.com/NixOS/nixpkgs/pull/322599 ).

### Steps To Reproduce
Reverting the following commits fixes the package:
- dbd9745e11c65cb89fa81b0181b322cd5683f4cb
- 77f5a747f44917e040a1bd0dfbde5c1a01e17410
- 2163a45ca7d635b42241de7ed49dfccd2492222c

### Error message
```
WARNING: Using incubator modules: jdk.incubator.vector
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
SWT OS.java Error: Failed to load swt-pi3, loading swt-pi4 as fallback.
Archi:
An error has occurred. See the log file
/home/<user>/.archi/.metadata/.log.
```
```
 > ~ cat /home/<user>/.archi/.metadata/.log
!SESSION 2024-09-20 15:07:47.226 -----------------------------------------------
eclipse.buildId=unknown
java.version=21.0.3
java.vendor=N/A
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -cleanConfig -eclipse.keyring @user.home/.archi/secure_storage
Command-line arguments:  -os linux -ws gtk -arch x86_64 -cleanConfig -eclipse.keyring @user.home/.archi/secure_storage

!ENTRY org.eclipse.osgi 4 0 2024-09-20 15:07:49.819
!MESSAGE Application error
!STACK 1
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons:
	no swt-pi4-gtk-4960r6 in java.library.path: /nix/store/kpb4y0h9pw4r7dg91dnq3rqi0j2ddwsr-webkitgtk-2.44.3+abi=4.0/lib:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	no swt-pi4-gtk in java.library.path: /nix/store/kpb4y0h9pw4r7dg91dnq3rqi0j2ddwsr-webkitgtk-2.44.3+abi=4.0/lib:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	no swt-pi4 in java.library.path: /nix/store/kpb4y0h9pw4r7dg91dnq3rqi0j2ddwsr-webkitgtk-2.44.3+abi=4.0/lib:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	Can't load library: /home/<user>/.swt/lib/linux/x86_64/libswt-pi4-gtk-4960r6.so
	Can't load library: /home/<user>/.swt/lib/linux/x86_64/libswt-pi4-gtk.so
	Can't load library: /home/<user>/.swt/lib/linux/x86_64/libswt-pi4.so

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:346)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:255)
	at org.eclipse.swt.internal.gtk.OS.<clinit>(OS.java:97)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:209)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:155)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:169)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:725)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:183)
	at com.archimatetool.editor.Application.start(Application.java:63)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

### PR DESCRIPTION
**Pull request by paumr**
fixes #343272

## Description of changes

This fix is required for the software to start correctly - currently the package is broken!

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by alyssais** [comment]
Commit message says glibc, but the added library is glib.

**Comment by paumr** [comment]
@alyssais doh, thanks for the catch! Fixed.

**Comment by r-vdp** [comment]
@paumr there is a merge conflict.

**Review by r-vdp — APPROVED** [review]

**Comment by r-vdp** [comment]
@paumr ofborg complains about darwin because the nixos test does not work on darwin. Maybe it would be better to include `passthru.tests` only for linux? Then it will be easier to see that the package actually builds correctly on darwin.

You can do that in a follow-up PR, I don't think we need to block this PR on that.

**Comment by paumr** [comment]
@r-vdp thanks for the merge!

The following error is logged by borg:
```
error: a 'x86_64-linux' with features {} is required to build '/nix/store/884s2vvfhsqhi022n58nz97arrv625hp-append-initrd-secrets.drv', but I am a 'x86_64-darwin' with features {benchmark, big-parallel, nixos-test}
```

To me this either seems to be an upstream issue, or a build-node one. Thus, I would not disable it on this package but hope that it will get fixed in general. Sadly I can't help with that since I neither own a mac, nor the necessary rights on borg.

**Comment by r-vdp** [comment]
Yeah, that's because the test doesn't build on darwin. I don't think it's useful to try and run the test on darwin, which is why I would just add it only when we're on linux. There are many other packages in nixpkgs that do this.

**Comment by paumr** [comment]
I see, thanks for the heads-up.
For future reference (and other readers):

@r-vdp proposed a solution similar to the one mentioned here: https://github.com/NixOS/nixpkgs/issues/345825

There were considerations on global solutions ( https://github.com/NixOS/nixpkgs/issues/294725 ), however they currently seem quite stale.

**Pull request merged**
