### PR TITLE
vimPlugins.luasnip: rename to LuaSnip

### PR DESCRIPTION
**Pull request by linsui**
###### Description of changes

The pname is used to generate the path of the plugin. Generally this is not important but lazy.nvim loads the plugins based on the path and it's case-sensitive. I guess the pname and the package path are generated so I add an alias instead of changing the pname only. 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by figsoda — CHANGES_REQUESTED** [review]
I don't like this change. The convention is to normalize packages to be lower case and kebab case

I don't think lazyvim should rely on case sensitivity when cloning from github is not, would overriding `pname` work for your use case?

**Comment by linsui** [comment]
There are many workarounds for this problem. But I thought this is a mistake so I want to fix it upstream.

> The convention is to normalize packages to be lower case and kebab case

I'm not sure. There are some other examples and LuaSnip is the only one failed for me.

> I don't think lazyvim should rely on case sensitivity when cloning from github is not

Goog point. I'll also report this to lazy.nvim.

**Comment by linsui** [comment]
My proposal was [rejected](https://github.com/folke/lazy.nvim/issues/675) so it still makes sense to make the plugin use the correct path by difault. I thought it's better to rename all the package name to lower case and use the origin name as the pname. This should be done in the update script.

**Comment by figsoda** [comment]
does overriding `pname` (in overrides.nix) solve the issue? I think that should be done instead of renaming the attribute in the mean time, before we figure out how to normalize attribute names in the update script.

**Comment by linsui** [comment]
```nix
(luasnip.overrideAttrs (_: { pname = "LuaSnip"; }))
```
This works.

**Comment by linsui** [comment]
> before we figure out how to normalize attribute names in the update script.

Looks like it's easy. We just need to change

```py
    @property
    def normalized_name(self) -> str:
        return self.name.replace(".", "-")
```

to

```py
    @property
    def normalized_name(self) -> str:
        return self.name.replace(".", "-").lower()
```

but we need to add many alias.

**Comment by teto** [comment]
even better set the alias in 
https://github.com/NixOS/nixpkgs/blob/a3fe093364f627e621deb52e71071e59b14763a4/pkgs/applications/editors/vim/plugins/vim-plugin-names#L1

**Pull request closed without merging**
