### PR TITLE
Help fix quodlibet! (Doesn't find icons)

### PR DESCRIPTION
**Pull request by Zer0-**
The Quodlibet music player [hasn't been building](https://nix-cache.s3.amazonaws.com/log/kg39z8vrd5fpqbj0hk1zar1d4qq6z554-quodlibet-4.2.1.drv).
I got [two of the 6 failing tests to pass](https://github.com/NixOS/nixpkgs/files/3164488/asdf.txt)
but the ones for icons still fail, and in fact adding `doCheck = false` and running it shows that the app has no icons.

Does anyone versed in gtk know why this is?

###### Motivation for this change
I like quodlibet and want it to work

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
hicolor-icon-theme does not really contain any icons, users are expected to choose an icon theme and install it globally (though some prefer to include Adwaita to make the icons work even for users without icon theme, see discussion on https://github.com/NixOS/nixpkgs/pull/43150.)

Not really sure why tray icon tests are failing and will not be able to debug anytime soon.

**Comment by lazka** [comment]
Looks like librsvg is missing or the gdk-pixbuf svg loader it contains.

**Comment by Zer0-** [comment]
It also complains that it can't import pyflakes and pycodestyle, however those are added to checkInputs. I wonder why that is.

**Comment by lazka** [comment]
You can pass `--no-quality` to test to skip them.

**Comment by sauyon** [comment]
I suspect we should be wrapping the test with `wrapGAppsHook` before running them.

Also, passing `--no-quality` sounds like a reasonable idea (I assume those are just code quality checks, which shouldn't be relevant for us.

I'm also getting a ton of deprecation warnings, which I hope will go away with 1.13.0.

**Comment by 101100** [comment]
This was done in #77796 and can be closed.

**Comment by Zer0-** [comment]
safe

**Pull request closed without merging**
