### PR TITLE
fmt: 6.2.1 -> 7.0.3

### PR DESCRIPTION
**Pull request by samuelgrf**
###### Motivation for this change
`pcsx2` master depends on `fmt` 7.0.3 and up, it'd be best to update `fmt` before `pcsx2`'s next release, so we aren't stuck on an older version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by samuelgrf** [comment]
Result of `nixpkgs-review pr 101251` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>gerbera</li>
    <li>waybar</li>
  </ul>
</details>
<details>
  <summary>22 packages built:</summary>
  <ul>
    <li>adlplug</li>
    <li>d-seams</li>
    <li>fmt</li>
    <li>kodi</li>
    <li>kodi-gbm</li>
    <li>kodi-wayland</li>
    <li>kodiGBM</li>
    <li>kodiPlain (kodiPlugins.kodi)</li>
    <li>kodiPlainWayland</li>
    <li>kodiPlugins.inputstream-adaptive</li>
    <li>kodiPlugins.joystick</li>
    <li>kodiPlugins.kodi-platform</li>
    <li>kodiPlugins.pvr-hdhomerun</li>
    <li>kodiPlugins.pvr-hts</li>
    <li>kodiPlugins.pvr-iptvsimple</li>
    <li>kodiPlugins.steam-controller</li>
    <li>kodiPlugins.vfs-libarchive</li>
    <li>kodiPlugins.vfs-sftp</li>
    <li>mkvtoolnix</li>
    <li>mkvtoolnix-cli</li>
    <li>mpvScripts.convert</li>
    <li>opnplug</li>
  </ul>
</details>

**Comment by samuelgrf** [comment]
Result of `nixpkgs-review pr 101251` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>23 packages built:</summary>
  <ul>
    <li>adlplug</li>
    <li>d-seams</li>
    <li>fmt</li>
    <li>fmt_6</li>
    <li>kodi (xbmc)</li>
    <li>kodi-gbm</li>
    <li>kodi-wayland</li>
    <li>kodiGBM</li>
    <li>kodiPlain (xbmcPlain)</li>
    <li>kodiPlainWayland</li>
    <li>kodiPlugins.inputstream-adaptive</li>
    <li>kodiPlugins.joystick</li>
    <li>kodiPlugins.kodi-platform</li>
    <li>kodiPlugins.pvr-hdhomerun</li>
    <li>kodiPlugins.pvr-hts</li>
    <li>kodiPlugins.pvr-iptvsimple</li>
    <li>kodiPlugins.steam-controller</li>
    <li>kodiPlugins.vfs-libarchive</li>
    <li>kodiPlugins.vfs-sftp</li>
    <li>mkvtoolnix</li>
    <li>mkvtoolnix-cli</li>
    <li>mpvScripts.convert</li>
    <li>opnplug</li>
  </ul>
</details>

**Comment by samuelgrf** [comment]
@Lassulus can you review this?

**Comment by Lassulus** [comment]
Result of `nixpkgs-review pr 101251` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>23 packages built:</summary>
  <ul>
    <li>adlplug</li>
    <li>d-seams</li>
    <li>fmt (fmt_7)</li>
    <li>fmt_6</li>
    <li>kodi</li>
    <li>kodi-gbm</li>
    <li>kodi-wayland</li>
    <li>kodiGBM</li>
    <li>kodiPlain (kodiPlugins.kodi)</li>
    <li>kodiPlainWayland</li>
    <li>kodiPlugins.inputstream-adaptive</li>
    <li>kodiPlugins.joystick</li>
    <li>kodiPlugins.kodi-platform</li>
    <li>kodiPlugins.pvr-hdhomerun</li>
    <li>kodiPlugins.pvr-hts</li>
    <li>kodiPlugins.pvr-iptvsimple</li>
    <li>kodiPlugins.steam-controller</li>
    <li>kodiPlugins.vfs-libarchive</li>
    <li>kodiPlugins.vfs-sftp</li>
    <li>mkvtoolnix</li>
    <li>mkvtoolnix-cli</li>
    <li>mpvScripts.convert</li>
    <li>opnplug</li>
  </ul>
</details>

**Pull request merged**
