### PR TITLE
gnomeExtensions.gsconnect: fix installed tests

### PR DESCRIPTION
**Pull request by mvnetbiz**
###### Motivation for this change
"try to fix LAN test in gsconnect's installed tests"
https://github.com/NixOS/nixpkgs/projects/30#card-47310308

###### Things done
add glib-networking to GIO_EXTRA_MODULES of minijasmine of gsconnect test.

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mvnetbiz** [comment]
Why should it not use `wrapGApp "$installedTests/libexec/installed-tests/gsconnect/minijasmine"`?

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105272` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gnomeExtensions.gsconnect</li>
  </ul>
</details>

**Comment by jtojnar** [comment]
I believe it was to limit what dependencies were available in the tests to avoid tests succeeding even though they would fail on live system.

**Comment by mvnetbiz** [comment]
Then glib-networking should probably also be in buildInputs even though it gets installed through other means?

**Comment by jtojnar** [comment]
Yeah, we should probably do that. I guess the daemon inherits the `GIO_EXTRA_MODULES` variable from the [D-Bus activation environment](https://dbus.freedesktop.org/doc/dbus-specification.html#bus-messages-update-activation-environment).

**Comment by mvnetbiz** [comment]
Does this make sense, or should I keep it as wrapProgram? This way the installedTests closure is only 6kb bigger.

**Comment by jtojnar** [comment]
Works for me. Also the commit should say `gnomeExtensions.gsconnect` (without the 3) so the ofborg can build it.

**Comment by jtojnar** [comment]
Thanks.

**Pull request merged**
