### PR TITLE
pkgsStatic.cyrus_sasl: fix build

### PR DESCRIPTION
**Pull request by KAction**
# pkgsStatic.cyrus_sasl: fix build

```
pkgsStatic.cyrus_sasl: fix build
```

### pkgsStatic.cyrus_sasl

<details><summary>content of pkgsStatic.cyrus_sasl.bin</summary>

```
/nix/store/h1p7q88fqg9zbzkpn319m8ifxb026dsa-cyrus-sasl-static-x86_64-unknown-linux-musl-2.1.28-bin
├── bin
│   ├── pluginviewer
│   ├── saslauthd
│   ├── sasldblistusers2
│   ├── saslpasswd2
│   └── testsaslauthd
└── sbin -> bin

2 directories, 5 files
```
</details>

<details><summary>content of pkgsStatic.cyrus_sasl.dev</summary>

```
/nix/store/cvwh9jqrlj1fp5dqwpbdi5qs5s37k9wh-cyrus-sasl-static-x86_64-unknown-linux-musl-2.1.28-dev
├── include
│   └── sasl
│       ├── hmac-md5.h
│       ├── md5.h
│       ├── md5global.h
│       ├── prop.h
│       ├── sasl.h
│       ├── saslplug.h
│       └── saslutil.h
├── lib
│   └── pkgconfig
│       └── libsasl2.pc
└── nix-support
    └── propagated-build-inputs

5 directories, 9 files
```
</details>

<details><summary>content of pkgsStatic.cyrus_sasl.devdoc</summary>

```
/nix/store/zsif9aar7hp83q0cd6yf40n01ws1z8gp-cyrus-sasl-static-x86_64-unknown-linux-musl-2.1.28-devdoc
└── share
    └── man
        └── man3
            ├── sasl.3.gz
            ├── sasl_authorize_t.3.gz
            ├── sasl_auxprop.3.gz
            ├── sasl_auxprop_getctx.3.gz
            ├── sasl_auxprop_request.3.gz
            ├── sasl_callbacks.3.gz
            ├── sasl_canon_user_t.3.gz
            ├── sasl_chalprompt_t.3.gz
            ├── sasl_checkapop.3.gz
            ├── sasl_checkpass.3.gz
            ├── sasl_client_init.3.gz
            ├── sasl_client_new.3.gz
            ├── sasl_client_start.3.gz
            ├── sasl_client_step.3.gz
            ├── sasl_decode.3.gz
            ├── sasl_dispose.3.gz
            ├── sasl_done.3.gz
            ├── sasl_encode.3.gz
            ├── sasl_encodev.3.gz
            ├── sasl_errdetail.3.gz
            ├── sasl_errors.3.gz
            ├── sasl_errstring.3.gz
            ├── sasl_getconfpath_t.3.gz
            ├── sasl_getopt_t.3.gz
            ├── sasl_getpath_t.3.gz
            ├── sasl_getprop.3.gz
            ├── sasl_getrealm_t.3.gz
            ├── sasl_getsecret_t.3.gz
            ├── sasl_getsimple_t.3.gz
            ├── sasl_global_listmech.3.gz
            ├── sasl_idle.3.gz
            ├── sasl_listmech.3.gz
            ├── sasl_log_t.3.gz
            ├── sasl_server_init.3.gz
            ├── sasl_server_new.3.gz
            ├── sasl_server_start.3.gz
            ├── sasl_server_step.3.gz
            ├── sasl_server_userdb_checkpass_t.3.gz
            ├── sasl_server_userdb_setpass_t.3.gz
            ├── sasl_setpass.3.gz
            ├── sasl_setprop.3.gz
            ├── sasl_user_exists.3.gz
            └── sasl_verifyfile_t.3.gz

3 directories, 43 files
```
</details>

<details><summary>content of pkgsStatic.cyrus_sasl.man</summary>

```
/nix/store/jh5zrhpa9gbqma2sxqjah2fazwxr1ix9-cyrus-sasl-static-x86_64-unknown-linux-musl-2.1.28-man
└── share
    └── man
        └── man8
            ├── pluginviewer.8.gz
            ├── saslauthd.8.gz
            ├── sasldblistusers2.8.gz
            ├── saslpasswd2.8.gz
            └── testsaslauthd.8.gz

3 directories, 5 files
```
</details>

<details><summary>content of pkgsStatic.cyrus_sasl.out</summary>

```
/nix/store/8bkcif2fhz2iwcxdggi0cwh7hb1hhmsz-cyrus-sasl-static-x86_64-unknown-linux-musl-2.1.28
└── lib
    ├── libsasl2.a
    ├── libsasl2.la
    └── sasl2
        ├── libanonymous.a
        ├── libanonymous.la
        ├── libcrammd5.a
        ├── libcrammd5.la
        ├── libdigestmd5.a
        ├── libdigestmd5.la
        ├── liblogin.a
        ├── liblogin.la
        ├── libotp.a
        ├── libotp.la
        ├── libplain.a
        ├── libplain.la
        ├── libsasldb.a
        ├── libsasldb.la
        ├── libscram.a
        └── libscram.la

2 directories, 18 files
```
</details>

### CODE REVIEW

**Comment by KAction** [comment]
@mweinelt Can you review this please?

**Comment by KAction** [comment]
@GrahamcOfBorg build

**Comment by KAction** [comment]
@happysalada Can you please take a look at this?

**Comment by happysalada** [comment]
Ci seems to fail here, could you run a nixpkgs-review on the PR just to make sure that this builds ?

**Comment by KAction** [comment]
`nixpkgs-review pr 235377` wants to rebuild 17k derivations. I guess, all reverse dependencies. Can we merge on the basis of cyrus_sasl building itself?

**Comment by happysalada** [comment]
I'm trying to run a nixpkgs-review on my server, I'm leaving this over night, I'll update when I have results

**Comment by happysalada** [comment]
The build broke in between and I couldn't get any results. For about 24h it looked good and I only had 35 breakage.
I'm afraid we are going to have to run a review and verify that this doesn't break anything.

**Comment by KAction** [comment]
Isn't it overkill? The only thing my PR changes is dropping this one commit:

https://github.com/cyrusimap/cyrus-sasl/commit/c2bd3afbca57f176d8c650670ce371444bb7fcc0

This commit adds a function already provided by version of openssl we are using. With dynamic linking that is unfortunately silently ignored, with static linking it is duplicate symbol. https://www.openssl.org/docs/man3.0/man3/HMAC.html

**Comment by KAction** [comment]
But if you want, I can drop that commit only if host platform is static. Then it will be same-hash for glibc version.

**Comment by happysalada** [comment]
This makes sense to me, i hope im not making a mistake

**Pull request merged**
