### PR TITLE
mailspring: 1.11.0 -> 1.12.0

### PR DESCRIPTION
**Pull request by Arjun31415**
New release: https://github.com/Foundry376/Mailspring/releases/tag/1.12.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Arjun31415** [comment]
I am facing this issue <https://github.com/Foundry376/Mailspring/issues/2475>. Need someone to review if the inputs needed have to be changed

**Comment by Arjun31415** [comment]
logs - 
```
[353677:1116/130602.969669:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
Error: Could not call remote method 'encryptString'. Check that the method signature is correct. Underlying error: Error: Error while decrypting the ciphertext provided to safeStorage.decryptString. Encryption is not available.Underlying stack: Error: Error while decrypting the ciphertext provided to safeStorage.decryptString. Encryption is not available.
    at /nix/store/mvawqm1x2z8jibw8yk5p2bxy6vds51xk-mailspring-1.12.0/share/mailspring/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:465:71
    at IpcMainImpl.<anonymous> (/nix/store/mvawqm1x2z8jibw8yk5p2bxy6vds51xk-mailspring-1.12.0/share/mailspring/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:323:27)
    at IpcMainImpl.emit (node:events:390:28)
    at IpcMainImpl.emit (node:domain:475:12)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10935)
    at EventEmitter.emit (node:events:390:28)
    at EventEmitter.emit (node:domain:475:12)

    at /nix/store/mvawqm1x2z8jibw8yk5p2bxy6vds51xk-mailspring-1.12.0/share/mailspring/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:468:25
    at IpcMainImpl.<anonymous> (/nix/store/mvawqm1x2z8jibw8yk5p2bxy6vds51xk-mailspring-1.12.0/share/mailspring/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:323:27)
    at IpcMainImpl.emit (node:events:390:28)
    at IpcMainImpl.emit (node:domain:475:12)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10935)
    at EventEmitter.emit (node:events:390:28)
    at EventEmitter.emit (node:domain:475:12) {
  message: "Recovered Error: Could not call remote method 'encryptString'. Check that the method signature is correct. Underlying error: Error: Error while decrypting the ciphertext provided to safeStorage.decryptString. Encryption is not available.Underlying stack: Error: Error while decrypting the ciphertext provided to safeStorage.decryptString. Encryption is not available.\n" +
    '    at /nix/store/mvawqm1x2z8jibw8yk5p2bxy6vds51xk-mailspring-1.12.0/share/mailspring/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:465:71\n' +
    '    at IpcMainImpl.<anonymous> (/nix/store/mvawqm1x2z8jibw8yk5p2bxy6vds51xk-mailspring-1.12.0/share/mailspring/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:323:27)\n' +
    '    at IpcMainImpl.emit (node:events:390:28)\n' +
    '    at IpcMainImpl.emit (node:domain:475:12)\n' +
    '    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10935)\n' +
    '    at EventEmitter.emit (node:events:390:28)\n' +
    '    at EventEmitter.emit (node:domain:475:12)\n'
} { pluginIds: [] }
```

The troubleshooting [guide](https://community.getmailspring.com/t/password-management-error/199/2) claims `libsecret` needs to be installed, which is already present in the `buildInputs`

**Review by NickCao — DISMISSED** [review]

**Comment by Arjun31415** [comment]
Ok it works with `--password-store="gnome-libsecret"`. and libsecret in runtime deps

**Comment by Arjun31415** [comment]
Referring this https://github.com/electron/electron/blob/main/docs/api/safe-storage.md#safestoragegetselectedstoragebackend-linux. The `--password-store` flag needs to be set if the errors pop up again. Could this be included in the desktop file ?. It depends on desktop environment

**Comment by NickCao** [comment]
> Referring this https://github.com/electron/electron/blob/main/docs/api/safe-storage.md#safestoragegetselectedstoragebackend-linux. The `--password-store` flag needs to be set if the errors pop up again. Could this be included in the desktop file ?. It depends on desktop environment

According to the doc it should be able to automatically choose the right one?

**Comment by Arjun31415** [comment]
I'm on hyprland but it does not use `basic_text` for me

**Comment by NickCao** [comment]
Whats the value of your `XDG_CURRENT_DESKTOP` environment variable?

**Comment by Arjun31415** [comment]
> XDG_CURRENT_DESKTOP

```
echo $XDG_CURRENT_DESKTOP
Hyprland
```

**Comment by Arjun31415** [comment]
Oh well I could always use home manager [xdg.desktopEntries](https://nix-community.github.io/home-manager/options.html#opt-xdg.desktopEntries) or just create a wrapper with the flag. 

I think the PR is ready otherwise

**Review by NickCao — APPROVED** [review]

**Comment by Arjun31415** [comment]
I do have `gnome-keyring` and `gnome-keyring-3` but not the libsecret one

**Comment by Arjun31415** [comment]
Maybe I'll bring it up with the mailspring devs instead or chromium

**Comment by Arjun31415** [comment]
I'm using hyprland, then it should resolve to basic, but that is not the
case

**Pull request merged**
