### PR TITLE
xdg-desktop-portal: Use custom variable for finding portals

### PR DESCRIPTION
**Pull request by jtojnar**
## Description of changes

x-d-p only looks for portal definitions in one of two places:
- datadir (which we cannot install anything to, since Nix packages are immutable)
- when `XDG_DESKTOP_PORTAL_DIR` environment variable is set, the path specified therein
  (meant for tests, disables looking for portal configuration anywhere else)

Let’s introduce our own `NIX_XDG_DESKTOP_PORTAL_DIR` environment variable
that will only control the portal definitions lookup.
We will not use it for searching for configuration
because it would require looking in the parent directory
and `XDG_CONFIG_DIRS` variable is sufficient for us.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
Can we call it `NIX_XDG_DESKTOP_PORTAL_DIR` or `NIXPKGS_XDG_DESKTOP_PORTAL_DIR`?  This package isn't NixOS-specific, and neither is the problem this environment variable solves.

**Review by alyssais — APPROVED** [review]
Diff LGTM.

**Review by K900 — APPROVED** [review]
LGTM

**Comment by jtojnar** [comment]
Rebased and updated the commit messages and comments.

:heavy_check_mark: Tested that portals still work in GNOME (with `door-knocker` and `ashpd-demo`).

**Comment by 5aaee9** [comment]
Looks this PR break `xdg-desktop-portal` test? https://hydra.nixos.org/build/250188445

```
14/28 xdg-desktop-portal:portals / test-portals-print                 ERROR            0.77s   killed by signal 6 SIGABRT
20/28 xdg-desktop-portal:portals / limited-portals-savefile           ERROR            1.16s   killed by signal 6 SIGABRT
```

**Comment by jtojnar** [comment]
I am unable to reproduce locally on this branch, master or 52e1f314725b09b354336d17c7b8bd2442b7b8e4 (used for the failing eval). I have tried rerunning the build several times.

**Pull request merged**
