### PR TITLE
k3s_1_28: 1.28.11+k3s2 -> 1.28.12+k3s1

### PR DESCRIPTION
**Pull request by rorosen**
https://github.com/k3s-io/k3s/releases/tag/v1.28.12%2Bk3s1

## Description of changes

1 package updated:
k3s_1_28 (1.28.11+k3s2 → 1.28.12+k3s1)

1 package built:
k3s_1_28

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by superherointj** [comment]
Git commit message title should have been:

> k3s_1_28: 1.28.11+k3s2 -> 1.28.12+k3s1

**Comment by superherointj** [comment]
Following tests are failing for me (x86_64):
- nix run .#k3s_1_28.passthru.tests.containerd-config.driver
- nix run .#k3s_1_28.passthru.tests.kubelet-config.driver

**Comment by rorosen** [comment]
> Following tests are failing for me (x86_64):
> 
>     * nix run .#k3s_1_28.passthru.tests.containerd-config.driver
> 
>     * nix run .#k3s_1_28.passthru.tests.kubelet-config.driver

Whoops, guess I run the tests for the wrong k3s version... However, I tracked down why the tests are failing and I think this has never worked with `v1.28.x`. The pre-`1.29.x` versions of `kubectl` weren't able to handle the JSONstring used in the test (i.e. `{.status.conditions[?(@.type=="Ready")].status}=True`) because they split the JSONpath input on `=` and `==` . While the `v1.28.x` versions just split on every `=` (e.g. [here](https://github.com/k3s-io/kubernetes/blob/v1.28.12-k3s1/staging/src/k8s.io/kubectl/pkg/cmd/wait/wait.go#L212)), the `v1.29.x` and `v1.30.x` versions introduced a `splitJSONPathInput` function that respects `==` (e.g. [here](https://github.com/k3s-io/kubernetes/blob/v1.29.7-k3s1/staging/src/k8s.io/kubectl/pkg/cmd/wait/wait.go#L270) and [here](https://github.com/k3s-io/kubernetes/blob/v1.30.3-k3s1/staging/src/k8s.io/kubectl/pkg/cmd/wait/wait.go#L270)).

I try to find previous runs of ofborg for `v1.28.x` and the JSONpath test, but can't find any. Ofborg seems to only run tests with the newest version? For instance, [these](https://github.com/NixOS/nixpkgs/runs/28130301152) are the logs of the tests that introduced the JSONpath input initially, they were only run for `v1.30.2`.

Do you know how ofborg decides how to run tests? Does just take the `k3s` package and ignores other versions?

Anyway, I think we should rewrite both tests to use `jq` for json processing instead of JSONpath (which is only partially supported by kubectl anyway...).

**Comment by superherointj** [comment]
Thanks for the fix.
The fix commit should precede the package bump or else it is going to error when bisecting. Then, makes sense to rebase to master as usual. Still, LGTM.

**Comment by rorosen** [comment]
Sorry for the delay, I rebased and changed the order of commits now. Let me know if there is anything else

**Comment by superherointj** [comment]
Before back-porting it's necessary to back-port the PRs that adds the tests.

**Review by superherointj — APPROVED** [review]

**Comment by superherointj** [comment]
> > Before back-porting it's necessary to back-port the PRs that adds the tests.
> 
> I'm not sure how much do we want to backport on second thought. Would it make sense to only backport version information and hashes similar to #335107?

Yes, that would be good.

Also, as there is infinite work, I think, we should be strategic on the actions we take, since time of everyone is limited, so it is fine to lag/ignore on back-ports that have failed, unless it blocks back-porting required to remove outdated K3s versions on NixOS releases. Stable users interested in newer features can always pick up from where we left.

**Pull request merged**
