### PR TITLE
nixos/obs-studio: init

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Add the `programs.obs-studio` module.
It lets you add third-party plugins (e.g. `pkgs.obs-studio-plugins.wlrobs`) to make a wrapped OBS package.
This is basically a port of the [equivalent home-manager module](https://github.com/nix-community/home-manager/blob/2d47379ad591bcb14ca95a90b6964b8305f6c913/modules/programs/obs-studio.nix).

cc @eclairevoyant @jb55 @MP2E @materusPL @fpletz 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
I am not sure on how to test such module. I have created a test file but for now, it doesn't do much (enables the module with one extra plugin).
I don't know whether I should launch OBS in the VM and check that it was succesful.

**Comment by h7x4** [comment]
OBS seems to have pretty good logging. It might be possible to create a test that starts OBS from some sort of external program that captures the output, waits for a cue in the log to shut it down and look for a string saying that the plugin has been loaded.

**Comment by GaetanLepage** [comment]
> OBS seems to have pretty good logging. It might be possible to create a test that starts OBS from some sort of external program that captures the output, waits for a cue in the log to shut it down and look for a string saying that the plugin has been loaded.

Indeed, that would be nice. However, I have no clue in how to write that... I guess that I would have to import the x11 stuff in the test derivation.
Would you know any similar example that I could get inspiration from ?

**Comment by eclairevoyant** [comment]
Thanks for the contribution. Looking at the code here, I'm not entirely convinced the module is worthwhile atm - usually I would expect a module to enable everything required for its package to work and possibly expose some config options; I don't see either here.

Maybe wrapOBS should just be publicised/documented?

**Comment by GaetanLepage** [comment]
> Thanks for the contribution. Looking at the code here, I'm not entirely convinced the module is worthwhile atm - usually I would expect a module to enable everything required for its package to work and possibly expose some config options; I don't see either here.
> 
> Maybe wrapOBS should just be publicised/documented?

This is a fair opinion. I could understand if this patch would get refused.
Any opinion @jb55, @fpletz, @MP2E, @materusPL, @SuperSandro2000 ?

**Comment by fpletz** [comment]
> Maybe wrapOBS should just be publicised/documented?

Where would that be? `wrapOBS` is not even available on https://search.nixos.org/packages. And if it were, the parameters wouldn't be discoverable. IMHO `wrapOBS` is not easily discoverable since its name doesn't start with `obs` but that is a separate issue.

Since the standard NixOS way for configuring wrappers is a NixOS module which is also done for other programs, I don't see any reason not to add this module.

The test in its current form is kind of useless, though. I would prefer to remove it and or add something useful like loading a module and starting a stream.

**Comment by GaetanLepage** [comment]
> Where would that be? `wrapOBS` is not even available on https://search.nixos.org/packages. And if it were, the parameters wouldn't be discoverable. IMHO `wrapOBS` is not easily discoverable since its name doesn't start with `obs` but that is a separate issue.
> 
> Since the standard NixOS way for configuring wrappers is a NixOS module which is also done for other programs, I don't see any reason not to add this module.

I agree. This is why I drafted this implementation.



> The test in its current form is kind of useless, though. I would prefer to remove it and or add something useful like loading a module and starting a stream.

Indeed ! Could you link me to some resource on how to implement such a test ? I was not able to find examples in the repo...

**Comment by fpletz** [comment]
> Indeed ! Could you link me to some resource on how to implement such a test ? I was not able to find examples in the repo...

I see the following challenges and possible solutions without having tried it:

 * We need a graphical environment. This is easy and there are lots of examples in the tests, just grep for tests that include `./common/x11.nix`.
 * OBS needs to be configured. You could just put some configs for scenes and profiles in the test users home directory for this. As far as I can see these are inis, so this should be quite easy. Not sure if obs can be called with a specific config file or directory.
 * Starting streaming automatically could be accomplished by starting obs with `--startstreaming`.
 * You need an endpoint to stream to and check if the stream is being received. I'm currently very fond of `mediamtx` which I am hosting for restreaming purposes. There is a NixOS test for mediamtx you can look into. You could also use the `nginx-rtmp-module` as an alternative.

If you need more assistance you can also message me on matrix.

**Comment by eclairevoyant** [comment]
Converting to draft pending tests

**Comment by bbigras** [comment]
Should this be closed now that #312112 is merged?

**Comment by GaetanLepage** [comment]
> Should this be closed now that #312112 is merged?

Indeed ! I am happy that someone was able to get this through.

**Pull request closed without merging**
