### PR TITLE
grisbi: 1.0.4 -> 1.2.1

### PR DESCRIPTION
**Pull request by marzipankaiser**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
cc @layus

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build grisbi

**Review by xeji — CHANGES_REQUESTED** [review]
Please fix build, apparently a missing dependency

**Comment by marzipankaiser** [comment]
> Please fix build, apparently a missing dependency
Apparently grisbi now needs gtk version 3 to compile.

**Comment by xeji** [comment]
@GrahamcOfBorg build grisbi

**Review by xeji — APPROVED** [review]

**Pull request merged**
