### PR TITLE
lib.types: Include the suboptions of both types for either

### PR DESCRIPTION
**Pull request by traxys**
## Description of changes

With this change types that are wrapped in `either` or `oneOf` will still display their suboptions in the documentation. This is import for types of the form `either a (submodule  ....))`.

Here are some options that were previously hidden, and are now visible:
```
services.tor.client.socksListenAddress.<xxx>
services.tor.relay.onionServices.<name>.map.*
services.tor.settings.ControlPort.*
services.tor.settings.DNSPort.*
services.tor.settings.ExtORPort.xxx
services.tor.settings.HTTPTunnelPort.*
services.tor.settings.NATDPort.*
....
```

Note that making `either` and `oneOf` handle suboptions means that they don't work with recursive types anymore. As such the types `eitherRecursive` and `oneOfRecursive` are added, that don't list suboptions, those types should not be used with submodules in order to correctly render their documentation.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by traxys** [comment]
Manual fails to build due to the newly exposed `tor` sub options that don't have documentation, but I'm not sure what documentation I could add to them, as I don't know `tor` options at all.

**Comment by ncfavier** [comment]
Earlier work: https://github.com/NixOS/nixpkgs/pull/208227

I don't have any energy to review this, sorry.

**Comment by traxys** [comment]
In view of that previous PR I'm not really sure this approach is going to cut it :/

**Comment by traxys** [comment]
I don't have the Nix knowledge to push this do a satisfying solution

**Pull request closed without merging**
