### PR TITLE
paperless-ngx: 1.8.0 -> 1.9.1

### PR DESCRIPTION
**Pull request by gador**
###### Description of changes

Update of paperless-ngx.

~~Due to the beta status currently a draft.~~

[Changelog](https://github.com/paperless-ngx/paperless-ngx/releases)

EDIT:

Now includes the following updates:

- qpdf: 10.6.3 -> 11.1.0 [Changelog](https://qpdf.readthedocs.io/en/stable/release-notes.html)
- python3Packages.pikepdf: 5.4.2 -> 6.0.2 [Changelog](https://pikepdf.readthedocs.io/en/latest/releasenotes/index.html)
- ~~pdfarranger: add support for newer pikepdf version~~
- pdfmixtool: 1.0.2 -> 1.1 add override to old qpdf version and track issue upstream

Both are major version updates. `qpdf` now builds with cmake and has some breaking changes in their API. `pikepdf` adapted to the changes in this newer version. 

The new version of `pikepdf` is necessary for the update in `paperless-ngx`  
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gador** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 192260` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages marked as broken and skipped:
</summary>
<ul>
<li>paperless</li>
<li>paperless-ng</li>
</ul>
</details>
<details>
<summary>
15 packages built:
</summary>
<ul>
<li>cups-filters</li>
<li>img2pdf (python310Packages.img2pdf)</li>
<li>manga-cli</li>
<li>ocrmypdf (python310Packages.ocrmypdf)</li>
<li>paperless-ngx</li>
<li>pdfarranger</li>
<li>pdfmixtool</li>
<li>pdfslicer</li>
<li>python310Packages.pikepdf</li>
<li>python39Packages.img2pdf</li>
<li>python39Packages.ocrmypdf</li>
<li>python39Packages.pikepdf</li>
<li>qpdf</li>
<li>splix</li>
<li>system-config-printer</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
cups-filters:
<details>

got build log for '/nix/store/x5p1a85ybfa99b7m65x36ix31vr78bkl-cups-filters-1.28.15' from 'daemon'
When evaluating attribute ‘cups-filters’:
warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/misc/cups/filters.nix:102:3:

```
    |
102 |   meta = {
    |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
warning: unclear-gpl
`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/misc/cups/filters.nix:105:5:

```
    |
105 |     license = lib.licenses.gpl2;
    |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
warning: stale-substitute
Stale substituteInPlace detected.
substituteStream(): WARNING: pattern 'execve' doesn't match anything in file 'filter/gstoraster.c'
Near pkgs/misc/cups/filters.nix:104:

```
    |
104 |     description = "Backends, filters, and other software that was once part of the core CUPS distribution but is no longer maintained by Apple Inc";
    | ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md
</details>
pdfarranger:
<details>

got build log for '/nix/store/qfzyvb70i2rpmyz3pg5ip7qxb94pzpyw-pdfarranger-1.9.0' from 'daemon'
When evaluating attribute ‘pdfarranger’:
warning: stale-substitute
Stale substituteInPlace detected.
substituteStream(): WARNING: pattern 'pikepdf>=1.17.0,<6' doesn't match anything in file 'setup.py'
Near pkgs/applications/misc/pdfarranger/default.nix:67:

```
   |
67 |     description = "Merge or split pdf documents and rotate, crop and rearrange their pages using an interactive and intuitive graphical interface";
   | ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md
</details>
python39Packages.img2pdf:
<details>

got build log for '/nix/store/j6ih1y8cbll256j0k2r1ckha1f3ikjm4-python3.9-img2pdf-0.4.4' from 'daemon'
When evaluating attribute ‘python39Packages.img2pdf’:
warning: unclear-gpl
`lgpl2` is a deprecated license, please check if project uses `lgpl2Plus` or `lgpl2Only` and change `meta.license` accordingly.

Near pkgs/development/python-modules/img2pdf/default.nix:71:5:

```
   |
71 |     license = licenses.lgpl2;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
splix:
<details>

got build log for '/nix/store/3ghdc1kmakw1yd7mj8lpxpfqn53h9b7d-splix-svn-315' from 'daemon'
When evaluating attribute ‘splix’:
warning: unclear-gpl
`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/misc/cups/drivers/splix/default.nix:50:5:

```
   |
50 |     license = licenses.gpl2;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
system-config-printer:
<details>

Package is missing a meta section.
If the package is using runCommand please make sure to inherit or create a meta section.

got build log for '/nix/store/x6gbfw5i705kp2668hl1b5j9n91xa6hx-system-config-printer-1.5.15' from 'daemon'
When evaluating attribute ‘system-config-printer’:
warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/tools/misc/system-config-printer/default.nix:78:3:

```
   |
78 |   meta = {
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
warning: unclear-gpl
`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/tools/misc/system-config-printer/default.nix:81:5:

```
   |
81 |     license = lib.licenses.gpl2;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
warning: unused-argument
Unused argument: `fetchpatch`.
Near pkgs/tools/misc/system-config-printer/default.nix:1:33:

```
  |
1 | { lib, stdenv, fetchFromGitHub, fetchpatch, udev, intltool, pkg-config, glib, xmlto, wrapGAppsHook
  |                                 ^
```
</details>
</details>

**Comment by gador** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 192260` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages marked as broken and skipped:
</summary>
<ul>
<li>paperless</li>
<li>paperless-ng</li>
</ul>
</details>
<details>
<summary>
15 packages built:
</summary>
<ul>
<li>cups-filters</li>
<li>img2pdf (python310Packages.img2pdf)</li>
<li>manga-cli</li>
<li>ocrmypdf (python310Packages.ocrmypdf)</li>
<li>paperless-ngx</li>
<li>pdfarranger</li>
<li>pdfmixtool</li>
<li>pdfslicer</li>
<li>python310Packages.pikepdf</li>
<li>python39Packages.img2pdf</li>
<li>python39Packages.ocrmypdf</li>
<li>python39Packages.pikepdf</li>
<li>qpdf</li>
<li>splix</li>
<li>system-config-printer</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
cups-filters:
<details>

got build log for '/nix/store/x5p1a85ybfa99b7m65x36ix31vr78bkl-cups-filters-1.28.15' from 'daemon'
When evaluating attribute ‘cups-filters’:
warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/misc/cups/filters.nix:102:3:

```
    |
102 |   meta = {
    |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
warning: unclear-gpl
`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/misc/cups/filters.nix:105:5:

```
    |
105 |     license = lib.licenses.gpl2;
    |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
warning: stale-substitute
Stale substituteInPlace detected.
substituteStream(): WARNING: pattern 'execve' doesn't match anything in file 'filter/gstoraster.c'
Near pkgs/misc/cups/filters.nix:104:

```
    |
104 |     description = "Backends, filters, and other software that was once part of the core CUPS distribution but is no longer maintained by Apple Inc";
    | ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md
</details>
python39Packages.img2pdf:
<details>

got build log for '/nix/store/j6ih1y8cbll256j0k2r1ckha1f3ikjm4-python3.9-img2pdf-0.4.4' from 'daemon'
When evaluating attribute ‘python39Packages.img2pdf’:
warning: unclear-gpl
`lgpl2` is a deprecated license, please check if project uses `lgpl2Plus` or `lgpl2Only` and change `meta.license` accordingly.

Near pkgs/development/python-modules/img2pdf/default.nix:71:5:

```
   |
71 |     license = licenses.lgpl2;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
splix:
<details>

got build log for '/nix/store/3ghdc1kmakw1yd7mj8lpxpfqn53h9b7d-splix-svn-315' from 'daemon'
When evaluating attribute ‘splix’:
warning: unclear-gpl
`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/misc/cups/drivers/splix/default.nix:50:5:

```
   |
50 |     license = licenses.gpl2;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
system-config-printer:
<details>

Package is missing a meta section.
If the package is using runCommand please make sure to inherit or create a meta section.

got build log for '/nix/store/x6gbfw5i705kp2668hl1b5j9n91xa6hx-system-config-printer-1.5.15' from 'daemon'
When evaluating attribute ‘system-config-printer’:
warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/tools/misc/system-config-printer/default.nix:78:3:

```
   |
78 |   meta = {
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
warning: unclear-gpl
`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/tools/misc/system-config-printer/default.nix:81:5:

```
   |
81 |     license = lib.licenses.gpl2;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
warning: unused-argument
Unused argument: `fetchpatch`.
Near pkgs/tools/misc/system-config-printer/default.nix:1:33:

```
  |
1 | { lib, stdenv, fetchFromGitHub, fetchpatch, udev, intltool, pkg-config, glib, xmlto, wrapGAppsHook
  |                                 ^
```
</details>
</details>

**Comment by gador** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 192260` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages marked as broken and skipped:
</summary>
<ul>
<li>paperless</li>
<li>paperless-ng</li>
</ul>
</details>
<details>
<summary>
15 packages built:
</summary>
<ul>
<li>cups-filters</li>
<li>img2pdf (python310Packages.img2pdf)</li>
<li>manga-cli</li>
<li>ocrmypdf (python310Packages.ocrmypdf)</li>
<li>paperless-ngx</li>
<li>pdfarranger</li>
<li>pdfmixtool</li>
<li>pdfslicer</li>
<li>python310Packages.pikepdf</li>
<li>python39Packages.img2pdf</li>
<li>python39Packages.ocrmypdf</li>
<li>python39Packages.pikepdf</li>
<li>qpdf</li>
<li>splix</li>
<li>system-config-printer</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
cups-filters:
<details>

got build log for '/nix/store/x5p1a85ybfa99b7m65x36ix31vr78bkl-cups-filters-1.28.15' from 'daemon'
When evaluating attribute ‘cups-filters’:
warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/misc/cups/filters.nix:102:3:

```
    |
102 |   meta = {
    |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
warning: unclear-gpl
`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/misc/cups/filters.nix:105:5:

```
    |
105 |     license = lib.licenses.gpl2;
    |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
warning: stale-substitute
Stale substituteInPlace detected.
substituteStream(): WARNING: pattern 'execve' doesn't match anything in file 'filter/gstoraster.c'
Near pkgs/misc/cups/filters.nix:104:

```
    |
104 |     description = "Backends, filters, and other software that was once part of the core CUPS distribution but is no longer maintained by Apple Inc";
    | ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md
</details>
python39Packages.img2pdf:
<details>

got build log for '/nix/store/j6ih1y8cbll256j0k2r1ckha1f3ikjm4-python3.9-img2pdf-0.4.4' from 'daemon'
When evaluating attribute ‘python39Packages.img2pdf’:
warning: unclear-gpl
`lgpl2` is a deprecated license, please check if project uses `lgpl2Plus` or `lgpl2Only` and change `meta.license` accordingly.

Near pkgs/development/python-modules/img2pdf/default.nix:71:5:

```
   |
71 |     license = licenses.lgpl2;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
splix:
<details>

got build log for '/nix/store/3ghdc1kmakw1yd7mj8lpxpfqn53h9b7d-splix-svn-315' from 'daemon'
When evaluating attribute ‘splix’:
warning: unclear-gpl
`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/misc/cups/drivers/splix/default.nix:50:5:

```
   |
50 |     license = licenses.gpl2;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
system-config-printer:
<details>

Package is missing a meta section.
If the package is using runCommand please make sure to inherit or create a meta section.

got build log for '/nix/store/x6gbfw5i705kp2668hl1b5j9n91xa6hx-system-config-printer-1.5.15' from 'daemon'
When evaluating attribute ‘system-config-printer’:
warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/tools/misc/system-config-printer/default.nix:78:3:

```
   |
78 |   meta = {
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
warning: unclear-gpl
`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/tools/misc/system-config-printer/default.nix:81:5:

```
   |
81 |     license = lib.licenses.gpl2;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
warning: unused-argument
Unused argument: `fetchpatch`.
Near pkgs/tools/misc/system-config-printer/default.nix:1:33:

```
  |
1 | { lib, stdenv, fetchFromGitHub, fetchpatch, udev, intltool, pkg-config, glib, xmlto, wrapGAppsHook
  |                                 ^
```
</details>
</details>

**Comment by symphorien** [comment]
lgtm regarding pdfarranger

**Comment by symphorien** [comment]
please drop the commit about pdfarranger and rebase on master now that #192914 is merged

**Comment by gador** [comment]
I'll Rebase later on master. The commit is still necessary due to the incompatibility with qpf and the applied patch

**Comment by gador** [comment]
Ping at Co-Maintainers: @erikarvstedt @lukegb 
Version 1.9.1 is out and the PR is ready for review

**Review by lukegb — APPROVED** [review]

**Pull request merged**
