### PR TITLE
WIP: Firefox fix

### PR DESCRIPTION
**Pull request by corngood**
###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
Note: if I apply this to recent master (19cb65206f), the firefox test still segfaults for me reliably (x86_64-linux).

**Comment by 7c6f434c** [comment]
@vcunat  do you get `/nix/store/b03dh1icxw2ra6r3m9c46r6ywx2gd61r-firefox-52.0` ?

Because it seems mostly OK to me after cleaning the profile.

How sepcifically do you crash it reliably?

**Comment by vcunat** [comment]
I have your ICU commit on top of current master
```
$ nix-build -Q -A firefox
/nix/store/zhc4plsan742p2by8mm622svb9w59a98-firefox-52.0
```
and the tests show the segfault
```
$ nix-build nixos/release.nix -A tests.firefox.x86_64-linux
[...]
machine# [    9.221513] firefox[950]: segfault at 0 ip 00007f3249b677f6 sp 00007ffe79308528 error 4 in libc-2.25.so[7f3249ae7000+195000]
[...]
```

**Comment by vcunat** [comment]
Aha, but I can only reproduce that in the VM, and the patch does appear to fix the real-machine crash (F12 key).

**Comment by vcunat** [comment]
Making FF use embedded ICU also fixes the F12-key crash (without causing larger rebuilds), but not the VM one.  There's probably some additional problem, perhaps unrelated to ICU.

**Comment by 7c6f434c** [comment]
Can you manually reproduce the crash in a VM? And if the crash is not in the `libxul.so`, it is probably another problem, I agree

**Comment by vcunat** [comment]
I tried about five times to run the VM test so far, and it always crashed.  It takes just a few seconds.  (The only problem is that the test is waiting for the window to appear and doesn't notice the crash, but you can see it in the log.)

**Comment by 7c6f434c** [comment]
And on the other hand, opening the same HTML page in Firefox manually doesn't crash it…

**Comment by vcunat** [comment]
Yes, that's what I had tried.

**Comment by 7c6f434c** [comment]
I think the situation with the test makes too much sense. I volunteer to fix this problem.

With the following patch (basically, give Firefox a real terminal as stdout) the test passes even on `master`:
```
diff --git a/nixos/tests/firefox.nix b/nixos/tests/firefox.nix
index 1bdabe93fe..94b1d646de 100644
--- a/nixos/tests/firefox.nix
+++ b/nixos/tests/firefox.nix
@@ -14,7 +14,7 @@ import ./make-test.nix ({ pkgs, ... }: {
   testScript =
     ''
       $machine->waitForX;
-      $machine->execute("firefox file://${pkgs.valgrind.doc}/share/doc/valgrind/html/index.html &");
+      $machine->execute("xterm -e 'firefox file://${pkgs.valgrind.doc}/share/doc/valgrind/html/index.html' &");
       $machine->waitForWindow(qr/Valgrind/);
       $machine->sleep(40); # wait until Firefox has finished loading the page
       $machine->screenshot("screen");
```

**Comment by 7c6f434c** [comment]
@vcunat I propose to declare the crash you observe a mystery (see my PR)

**Comment by vcunat** [comment]
Let's make Hydra start getting binaries, so that we can bump of that "ancient" nixos-unstable.

Your hash might've differed because the `debugBuild` change adds `patches = [];`.

**Pull request merged**
