### PR TITLE
flatpak: 0.99.3 → 1.0.2

### LINKED ISSUE #43595: Update the flatpak-builder package for YAML support
## Issue description

`flatpak-builder` package cannot build (Flatpak) applications that are assembled using YAML file(s).

### Steps to reproduce

Just pull a Flatpak package from any repository that uses a YAML file as descriptor and try to build it. You should get something like:

```shell
[gorre@uplink flathub]$ flatpak-builder build-dir com.brave.Brave.yaml
Can't parse 'com.brave.Brave.yaml': flatpak-builder was not compiled with YAML support.
```

## Technical details

```shell
[gorre@uplink flathub]$ uname -a
Linux uplink 4.14.55-1-lts #1 SMP Wed Jul 11 18:24:20 CEST 2018 x86_64 GNU/Linux

[gorre@uplink flathub]$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (35.63 MiB download, 137.92 MiB unpacked):
  /nix/store/3vmmdcx64dmfjwzsh5w9hr35sgjhw8xq-diffutils-3.6
  /nix/store/5b7v3h1avvcqhwpjwmjvgh755k2yqr5l-bash-interactive-4.4-p23-info
  /nix/store/615hqc9nn4pxxb8a7l61ylanmhn64gny-paxctl-0.9
  /nix/store/6k0cz3nzypv5i0y4i4kydcwa2asiszml-findutils-4.6.0
  /nix/store/7m4kn21xwm1161ki8l2iy3dxhcijvd4i-bash-interactive-4.4-p23-doc
  /nix/store/bcrwa5b8z54xrl95ipfrq6nqhb0530yi-stdenv-linux
  /nix/store/dr4csnaym4cmijaslnhq36kf69lz46ix-bash-interactive-4.4-p23-man
  /nix/store/hcmwqnqj3xhirg1hdwavhvv2d32mw08g-patchelf-0.9
  /nix/store/iag0b52whk3ya4jg6mniyfgz99b41k89-bash-interactive-4.4-p23
  /nix/store/imfm3gk3qchmyv7684pjpm8irvkdrrkk-gcc-7.3.0
  /nix/store/lq0r48d21ngb7c9nk92b1zpk42bc7p96-nix-info
  /nix/store/s8vd4p3mhkmgyf7py58m8722zcz3gr0x-readline-7.0p5
  /nix/store/svqz53x33gsjh41h357azm8fk755ynma-bash-interactive-4.4-p23-dev
  /nix/store/yz6kinf4ia19r1c14yirl6x4ciwgzk67-gcc-wrapper-7.3.0
copying path '/nix/store/7m4kn21xwm1161ki8l2iy3dxhcijvd4i-bash-interactive-4.4-p23-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/5b7v3h1avvcqhwpjwmjvgh755k2yqr5l-bash-interactive-4.4-p23-info' from 'https://cache.nixos.org'...
copying path '/nix/store/dr4csnaym4cmijaslnhq36kf69lz46ix-bash-interactive-4.4-p23-man' from 'https://cache.nixos.org'...
copying path '/nix/store/3vmmdcx64dmfjwzsh5w9hr35sgjhw8xq-diffutils-3.6' from 'https://cache.nixos.org'...
copying path '/nix/store/6k0cz3nzypv5i0y4i4kydcwa2asiszml-findutils-4.6.0' from 'https://cache.nixos.org'...
copying path '/nix/store/imfm3gk3qchmyv7684pjpm8irvkdrrkk-gcc-7.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/lq0r48d21ngb7c9nk92b1zpk42bc7p96-nix-info' from 'https://cache.nixos.org'...
copying path '/nix/store/yz6kinf4ia19r1c14yirl6x4ciwgzk67-gcc-wrapper-7.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/hcmwqnqj3xhirg1hdwavhvv2d32mw08g-patchelf-0.9' from 'https://cache.nixos.org'...
copying path '/nix/store/615hqc9nn4pxxb8a7l61ylanmhn64gny-paxctl-0.9' from 'https://cache.nixos.org'...
copying path '/nix/store/s8vd4p3mhkmgyf7py58m8722zcz3gr0x-readline-7.0p5' from 'https://cache.nixos.org'...
copying path '/nix/store/bcrwa5b8z54xrl95ipfrq6nqhb0530yi-stdenv-linux' from 'https://cache.nixos.org'...
copying path '/nix/store/iag0b52whk3ya4jg6mniyfgz99b41k89-bash-interactive-4.4-p23' from 'https://cache.nixos.org'...
copying path '/nix/store/svqz53x33gsjh41h357azm8fk755ynma-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.55-1-lts, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(gorre): `"nixpkgs-18.09pre146103.d3ed77f1fb1"`
 - nixpkgs: `/home/gorre/.nix-defexpr/channels/nixpkgs`
```

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
Flatpak update; cherry-picked from https://github.com/NixOS/nixpkgs/pull/45950 with some extra fixes

cc @hedning 

Closes: https://github.com/NixOS/nixpkgs/issues/43595 cc @x80486

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
@GrahamcOfBorg test flatpak xdg-desktop-portal ostree

**Comment by hedning** [comment]
The new pipewire breaks mutter, so it will require a patch or to wait for 3.30.

**Comment by jtojnar** [comment]
I have removed the pipewire dependency from mutter for now, we still do not have working wayland anyway.

**Comment by jtojnar** [comment]
Installed tests for ostree still fail due to https://github.com/ostreedev/ostree/issues/1592 and https://github.com/ostreedev/ostree/issues/1634

**Pull request merged**
