### PR TITLE
ofono: load configuration from outside the nix store

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109109` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>modem-manager-gui</li>
<li>ofono</li>
</ul>
</details>

**Comment by jtojnar** [comment]
Did someone check ofono works without `/etc/ofono/phonesim.conf` existing? Sometimes projects crash if they cannot find their configuration file, even though it is just empty.

Also this issue is typically fixed by the following for autotools projects:

```nix
configureFlags = [ "--sysconfdir=/etc" ];
makeFlags = [ "SYSCONFDIR=${placeholder "out"}/etc" ];
```

**Comment by Mic92** [comment]
This seems to work fine without configuration: `sudo ofonod -n -d`

**Comment by Mic92** [comment]
The proposed workaround does not work: 

```
  libtool: install: /nix/store/87ipxqn2ah5ba282cnip9z4mm3dbczjc-coreutils-8.32/bin/install -c src/ofonod /nix/store/16yqn13rld3d2d76f8kxn4jbzp13dlm5-ofono-1.31/sbin/ofonod
   /nix/store/87ipxqn2ah5ba282cnip9z4mm3dbczjc-coreutils-8.32/bin/mkdir -p '/etc/ofono'
  /nix/store/87ipxqn2ah5ba282cnip9z4mm3dbczjc-coreutils-8.32/bin/mkdir: cannot create directory '/etc/ofono': Permission denied
  make[2]: *** [Makefile:4149: install-dist_confDATA] Error 1
  make[1]: *** [Makefile:4777: install-am] Error 2
  make: *** [Makefile:4770: install] Error 2
```

```diff
diff --git a/pkgs/tools/networking/ofono/default.nix b/pkgs/tools/networking/ofono/default.nix
index 5dafb1e5639..289df6e4b6c 100644
--- a/pkgs/tools/networking/ofono/default.nix
+++ b/pkgs/tools/networking/ofono/default.nix
@@ -42,14 +42,12 @@ stdenv.mkDerivation rec {
 
   configureFlags = [
     "--with-dbusconfdir=${placeholder "out"}/share"
+    "--sysconfdir=/etc"
     "--with-systemdunitdir=${placeholder "out"}/lib/systemd/system"
     "--enable-external-ell"
   ];
 
-  postInstall = ''
-    rm -r $out/etc/ofono
-    ln -s /etc/ofono $out/etc/ofono
-  '';
+  installFlags = [ "SYSCONFDIR=${placeholder "out"}/etc" ];
 
   enableParallelBuilding = true;
   enableParallelChecking = false;
```

**Pull request merged**
