### PR TITLE
Kernels 2021-12-17

### PR DESCRIPTION
**Pull request by TredwellGit**
###### Things done
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/pull/150484

**Review by fabianhjr — APPROVED** [review]
Built and booted into 5.15.8, diff LGTM

```
 ~  cat /proc/version                                                                                   Thu 16 Dec 2021 10:25:15 AM CST
Linux version 5.15.8 (nixbld@localhost) (gcc (GCC) 10.3.0, GNU ld (GNU Binutils) 2.35.2) #1-NixOS SMP Tue Dec 14 09:57:23 UTC 2021
```

**Comment by fabianhjr** [comment]
5.15.9 was just released

**Review by fabianhjr — APPROVED** [review]
Built and booted into 5.15.9

**Comment by fabianhjr** [comment]
I don't know what is going on but 5.15.10 was also just released; this cadence is a bit too high. XD

**Comment by fabianhjr** [comment]
hardened patches have also been released: https://github.com/anthraxx/linux-hardened/releases/tag/5.15.10-hardened1

**Review by Ma27 — APPROVED** [review]

**Pull request merged**
