### PR TITLE
epgstation: 1.7.4 -> 1.7.5

### PR DESCRIPTION
**Pull request by midchildan**
###### Motivation for this change
* bump version
* change existing scripts to make use of `passthru.updateScript`
* change `name` from `node_EPGStation` to `EPGStation`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by wamserma — APPROVED** [review]
LGTM at first glance.

**Comment by midchildan** [comment]
Thanks! JFYI the command for changing statuses is `/status`.

/status needs_merger

**Comment by midchildan** [comment]
Oh.

**Comment by wamserma** [comment]
> Thanks! JFYI the command for changing statuses is `/status`.
> 
> /status needs_merger

I always mix this up. -.-

**Review by timokau — APPROVED** [review]
This looks good to me. @cideM, what is the [status](https://discourse.nixos.org/t/call-for-nodepackages-maintainers/9176/28) on node packages? Should I just merge this or do you want to bundle it somehow?

**Comment by cideM** [comment]
Since there are no conflicts I'd just merge this right now

**Comment by timokau** [comment]
Okay, thanks! Also thank you for the review @wamserma.

**Pull request merged**
