### PR TITLE
errbot: init at 4.2.2

### PR DESCRIPTION
**Pull request by fpletz**
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fpletz** [comment]
This PR depends on #16534 being merged first.

**Comment by groxxda** [comment]
I know that there are multiple places where it's done like here (importing `python3Packages`) but isn't our usual policy to specify version overrides in `all-packages.nix` (`callPackage .. { pythonPackages = python3Packages; }`)?

**Comment by fpletz** [comment]
I thought this is more appropriate because this version of errbot plus the stated dependencies won't work with Python2.

**Comment by groxxda** [comment]
I don't have a strong opinion which way to go, but adding `disabled = pythonPackages.isPy27` or `disabled = !pythonPackages.isPy3k` (depending whether pypy works) would be an option :wink:

But since both ways are currently used in nixpkgs it's most probably fine either way.

**Comment by fpletz** [comment]
@groxxda I thought about it again and modified the code as you suggested. Also added the `disabled` flag. Thanks!

**Pull request merged**
