### PR TITLE
chefdk: 1.3.40 -> 2.3.4

### PR DESCRIPTION
**Pull request by grahamc**
###### Motivation for this change

Update for tomster on IRC, documented the nix-shell call to update the package.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg build chefdk

**Comment by grahamc** [comment]
@GrahamcOfBorg build chefdk

**Comment by tomster** [comment]
FTR tested this on x86_64 using nixos 17.09 and it worked

**Comment by tomster** [comment]
FTR when running actual sessions with this version my output is littered with the following errors/warnings:

```       Ignoring ffi-1.9.18 because its extensions are not built.  Try: gem pristine ffi --version 1.9.18
       Ignoring unf_ext-0.0.7.4 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.4
       Ignoring wdm-0.1.1 because its extensions are not built.  Try: gem pristine wdm --version 0.1.1
``` - perhaps some dependencies need to be updated?

**Comment by grahamc** [comment]
@manveru can you take a look at this?

**Pull request merged**
