### PR TITLE
Staging next

### LINKED ISSUE #112173: Cross-compiling nixos for armv6l failing to build File-ShareDir
**Describe the bug**

I am trying to cross-compile nixos for the raspberry pi. Trying to do so leads to an error while trying to build `/nix/store/7x07kg9jvw7y1zxl2crk7lv4d73hmv0a-perl5.32.0-File-ShareDir-1.116-armv6l-unknown-linux-gnueabihf.drv`.

The error is this:

```
Can't load module IO, dynamic loading not available in this perl.
  (You may need to build a new perl executable which either supports
  dynamic loading or has the IO module statically linked into it.)
 at /nix/store/gjikgqfwbfgdavg5cm2nl2isgqj9xzwf-perl-5.32.0-armv6l-unknown-linux-gnueabihf/lib/perl5/5.32.0/armv6l-linux/IO/Handle.pm line 268.
Compilation failed in require at /nix/store/gjikgqfwbfgdavg5cm2nl2isgqj9xzwf-perl-5.32.0-armv6l-unknown-linux-gnueabihf/lib/perl5/5.32.0/armv6l-linux/IO/Handle.pm line 268.
BEGIN failed--compilation aborted at /nix/store/gjikgqfwbfgdavg5cm2nl2isgqj9xzwf-perl-5.32.0-armv6l-unknown-linux-gnueabihf/lib/perl5/5.32.0/armv6l-linux/IO/Handle.pm line 268.
Compilation failed in require at /nix/store/gjikgqfwbfgdavg5cm2nl2isgqj9xzwf-perl-5.32.0-armv6l-unknown-linux-gnueabihf/lib/perl5/5.32.0/armv6l-linux/IO/Seekable.pm line 100.
BEGIN failed--compilation aborted at /nix/store/gjikgqfwbfgdavg5cm2nl2isgqj9xzwf-perl-5.32.0-armv6l-unknown-linux-gnueabihf/lib/perl5/5.32.0/armv6l-linux/IO/Seekable.pm line 100.
Compilation failed in require at /nix/store/gjikgqfwbfgdavg5cm2nl2isgqj9xzwf-perl-5.32.0-armv6l-unknown-linux-gnueabihf/lib/perl5/5.32.0/armv6l-linux/IO/File.pm line 132.
BEGIN failed--compilation aborted at /nix/store/gjikgqfwbfgdavg5cm2nl2isgqj9xzwf-perl-5.32.0-armv6l-unknown-linux-gnueabihf/lib/perl5/5.32.0/armv6l-linux/IO/File.pm line 132.
Compilation failed in require at inc/latest/private.pm line 10.
BEGIN failed--compilation aborted at inc/latest/private.pm line 10.
Compilation failed in require at inc/latest.pm line 5.
Compilation failed in require at Makefile.PL line 18.
BEGIN failed--compilation aborted at Makefile.PL line 18.
```

I am using the nix expression from this repository: https://github.com/ilyakooo0/rasnixos.

**To Reproduce**
1. `git clone https://github.com/ilyakooo0/rasnixos.git`
2. `cd rasnixos`
3. `nix-build -j auto --argstr system x86_64-linux`

**Expected behavior**
Everything builds without error.

### LINKED ISSUE #112417: stdenv.x86_64-darwin fails on staging-next
The `stdenv.x86_64-darwin` build is failing on staging-next (#112095) and I don't know what could cause this.

The earliest hydra job this failed on is https://hydra.nixos.org/build/136505930.

The log since then always looks like this:
```
output '/nix/store/hd0fxaykxgp3a8bc3ia17n18zsb06fbd-stdenv-darwin' is not allowed to refer to the following paths:
  /nix/store/2q831bygr0ddkjk4bgix42ym9ha1jpmm-bootstrap-stage0-clang
  /nix/store/6jysbyhc43sjvfiyh1bpvi1n3zbz212r-bootstrap-tools
```

Pinging people that touched the darwin stdenv in recent times:
@thefloweringash @holymonson

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
`stdenv.x86_64-darwin` fails with this peculiar log output:

```
output '/nix/store/hd0fxaykxgp3a8bc3ia17n18zsb06fbd-stdenv-darwin' is not allowed to refer to the following paths:
  /nix/store/2q831bygr0ddkjk4bgix42ym9ha1jpmm-bootstrap-stage0-clang
  /nix/store/6jysbyhc43sjvfiyh1bpvi1n3zbz212r-bootstrap-tools
```

What is going on there?

**Comment by mweinelt** [comment]
The manual fails in `qt.section.xml`:

```
languages-frameworks/qt.section.xml:36: parser error : Specification mandates value for attribute id
      nativeBuildInputs = [ wrapQtAppsHook ]; <co xml:id'qt-default-nix-co-2' />
                                                        ^
languages-frameworks/qt.section.xml:36: parser error : attributes construct error
      nativeBuildInputs = [ wrapQtAppsHook ]; <co xml:id'qt-default-nix-co-2' />
                                                        ^
languages-frameworks/qt.section.xml:36: parser error : Couldn't find end of Start Tag co line 36
      nativeBuildInputs = [ wrapQtAppsHook ]; <co xml:id'qt-default-nix-co-2' />
                                                        ^
languages-frameworks/qt.section.xml:49: parser error : Unescaped '<' not allowed in attributes values
        <para>
        ^
languages-frameworks/qt.section.xml:49: parser error : attributes construct error
        <para>
        ^
languages-frameworks/qt.section.xml:49: parser error : Couldn't find end of Start Tag callout line 48
        <para>
        ^
languages-frameworks/qt.section.xml:54: parser error : Opening and ending tag mismatch: calloutlist line 1 and callout
      </callout>
                ^
languages-frameworks/qt.section.xml:55: parser error : Opening and ending tag mismatch: section line 1 and calloutlist
     </calloutlist>
                   ^
languages-frameworks/qt.section.xml:57: parser error : Extra content at the end of the document
  <section xml:id="qt-runtime-dependencies">
  ^
languages-frameworks/index.xml:28: element include: XInclude error : could not load languages-frameworks/qt.section.xml, and no fallback was found
jing doc-support/result/docbook.rng manual-full.xml
/build/doc/manual-full.xml:20671:37: error: element "xi:include" not allowed here; expected the element end-tag or element "bibliography", "glossary", "index", "section", "simplesect" or "toc"
make: *** [Makefile:29: validate] Error 1
builder for '/nix/store/ki0jxvs7mxy0hgycqd51wknvdfzs2xlq-nixpkgs-manual.drv' failed with exit code 2
```

5590e365e4775f138610b1036a75f8886921843e https://github.com/NixOS/nixpkgs/pull/108888 @ttuegel

**Comment by mweinelt** [comment]
Another manual problem in `qt.section.md`:

```
languages-frameworks/qt.section.xml:49: parser error : Unescaped '<' not allowed in attributes values
        <para>
        ^
languages-frameworks/qt.section.xml:49: parser error : attributes construct error
        <para>
        ^
languages-frameworks/qt.section.xml:49: parser error : Couldn't find end of Start Tag callout line 48
        <para>
        ^
languages-frameworks/qt.section.xml:54: parser error : Opening and ending tag mismatch: calloutlist line 26 and callout
      </callout>
                ^
languages-frameworks/qt.section.xml:55: parser error : Opening and ending tag mismatch: section line 26 and calloutlist
     </calloutlist>
                   ^
languages-frameworks/qt.section.xml:57: parser error : Extra content at the end of the document
  <section xml:id="qt-runtime-dependencies">
  ^
languages-frameworks/index.xml:28: element include: XInclude error : could not load languages-frameworks/qt.section.xml, and no fallback was found
jing doc-support/result/docbook.rng manual-full.xml
/build/doc/manual-full.xml:20671:37: error: element "xi:include" not allowed here; expected the element end-tag or element "bibliography", "glossary", "index", "section", "simplesect" or "toc"
make: *** [Makefile:29: validate] Error 1
builder for '/nix/store/23j9w0x0iwzy8fqmaxsshwly86pax9g9-nixpkgs-manual.drv' failed with exit code 2
```

**Comment by mweinelt** [comment]
We're down to 20k packages and primarily waiting on darwin now. The issues with the darwin stdenv and manual have thankfully been fixed, thanks to everyone for your contributions. I hope we can finish this staging next cycle tomorrow.

**Comment by mweinelt** [comment]
The darwin builders seem stuck. There hasn't been any progress for a while now. I've posted to #nixos-infra last night about this, no feedback yet.

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 112095` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>15 packages built:</summary>
  <ul>
    <li>abbaye-des-morts</li>
    <li>abc-verifier</li>
    <li>abcde</li>
    <li>abcl</li>
    <li>abcm2ps</li>
    <li>abcmidi</li>
    <li>abduco</li>
    <li>abella</li>
    <li>abi-compliance-checker</li>
    <li>abi-dumper</li>
    <li>abiword</li>
    <li>abook</li>
    <li>abootimg</li>
    <li>abseil-cpp</li>
    <li>abuse</li>
  </ul>
</details>

**Comment by tomberek** [comment]
How does one help/assist with staging merges?

**Comment by jonringer** [comment]
I usually rebuild my system pointing at it
```
git checkout staging-next
nixos-rebuild -I nixpkgs=$PWD build
```

and a similar thing for my home-manager setup
```
home-manager -I nixpkgs=$PWD switch
```

I also have another nix file which does the majority of the release candidates.

If you do encounter issues, make an issue or PR targeting staging-next.

**Comment by jonringer** [comment]
I'm unable to run any nixos tests
```
patching script interpreter paths in /nix/store/9c26s6vgrgb5cj37dlkzrmciqrb1yqpw-busybox-1.32.1/default.script
/nix/store/9c26s6vgrgb5cj37dlkzrmciqrb1yqpw-busybox-1.32.1/default.script: interpreter directive changed from "#!/bin/sh" to "/nix/store/9c26s6vgrgb5cj37dlkzrmciqrb1yqpw-busybox-1.32.1/bin/sh"
stat: unrecognized option '--printf'
BusyBox v1.32.1 () multi-call binary.
```

**Comment by mweinelt** [comment]
That is odd, given that so much of the tested set looks to be working. https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents

**Comment by jonringer** [comment]
the nixpkgs jobset doesn't run any nixos tests

**Comment by tomberek** [comment]
> I'm unable to run any nixos tests
> 
> ```
> patching script interpreter paths in /nix/store/9c26s6vgrgb5cj37dlkzrmciqrb1yqpw-busybox-1.32.1/default.script
> /nix/store/9c26s6vgrgb5cj37dlkzrmciqrb1yqpw-busybox-1.32.1/default.script: interpreter directive changed from "#!/bin/sh" to "/nix/store/9c26s6vgrgb5cj37dlkzrmciqrb1yqpw-busybox-1.32.1/bin/sh"
> stat: unrecognized option '--printf'
> BusyBox v1.32.1 () multi-call binary.
> ```

Could it be this: https://github.com/NixOS/nixpkgs/blob/staging-next/pkgs/build-support/setup-hooks/patch-shebangs.sh#L97 ?

**Comment by mweinelt** [comment]
Yes, that sounds like the culprit. I'd kindly ask @Mic92 and @thefloweringash to take a look.

**Comment by Mic92** [comment]
I have a look.

**Comment by Mic92** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/113333

**Comment by mweinelt** [comment]
Thanks, applied.

**Comment by mweinelt** [comment]
Git fails its tests on aarch64
https://nix-cache.s3.amazonaws.com/log/x3hkzfhpc0yr7na3sh92skyxa3n9bl43-git-2.30.0.drv

**Comment by baloo** [comment]
I'm not too sure how staging-next merging works, but any chance we could get this one in this window?
https://github.com/NixOS/nixpkgs/pull/112928

That'd be awesome!

**Comment by jtojnar** [comment]
@baloo See https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy. That PR causes too many rebuilds so it would delay this cycle too much.

**Comment by jonringer** [comment]
another way to think of staging-next is getting this set of changes closer to being able to be merged to master. If we included more PRs, it would potentially be diverging from a more stabilized state

**Comment by mohe2015** [comment]
I have no idea but I would assume that PR would be merged into the next `staging` cycle first and would then progress to `staging-next` and then `master` at some point.

**Comment by baloo** [comment]
@jtojnar Alright then.
@mohe2015 That's what I assumed too. I got it mixed up it appears.

**Comment by mweinelt** [comment]
> I have no idea but I would assume that PR would be merged into the next `staging` cycle first and would then progress to `staging-next` and then `master` at some point.

While staging can continuously receive new merges, staging-next has a cycle where it picks up changes from staging to stabilize them so they can be merged into master.

**Comment by mohe2015** [comment]
> @mohe2015 That's what I assumed too. I got it mixed up it appears.
 I also think the name is a bit misleading but unfortunately that's how it is for now.

**Comment by tomberek** [comment]
> And then personally, I usually rebuild my system pointing at it
> 
> ```
> git checkout staging-next
> nixos-rebuild -I nixpkgs=$PWD build
> ```

Rebuilt my system with 79b7a67b55ee7f22a796720643ec8b1b65b2f8ed. No issues noticed. (required a reboot for Nvidia)

**Pull request merged**
