### PR TITLE
[staging] python3Packages.aiohttp: 3.7.4 -> 3.7.4.post0

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by mweinelt — APPROVED** [review]

**Comment by dotlambda** [comment]
Note that this breaks `home-assistant` though.

**Comment by mweinelt** [comment]
Several things on staging seem to break `home-assistant`.

**Comment by mweinelt** [comment]
The last staging-next cycle broke over 10k packages.

https://hydra.nixos.org/jobset/nixpkgs/staging-next/evals

Like werkzeug-1.0.1 which breaks due to the pytest upgrade. So this change is the least of my worries.

**Comment by FRidh** [comment]
@mweinelt I think you're mixing up something. werkzeug builds fine on master (which was the last staging-next cycle). Note on staging-next many jobs have been aborted by me since it was already merged into master.

**Comment by mweinelt** [comment]
@FRidh It is unfortunate that cancelled and failed are summed up to one number then.

**Pull request merged**
