### PR TITLE
packer: 1.9.3 -> 1.9.4

### PR DESCRIPTION
**Pull request by aaronjheng**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by qjoly — CHANGES_REQUESTED** [review]
Since the licence changed between 1.9.3 and 1.9.4, can you update it to BSL?

**Comment by nywilken** [comment]
> Since the licence changed between 1.9.3 and 1.9.4, can you update it to BSL

Hi @QJoly I'm a maintainer over on Packer. Thanks for making Packer available as a NixOS package. The license change takes affect starting with the next minor release, which will be 1.10.0. The 1.9.x releases should all still be under the MPL-2.0 license. 

Do you have an example of documentation or license info indicating a license difference between 1.9.3 and 1.9.4? 

I can assure you the license between the two release should be the same. But if you are seeing information indicating that it is not please let me know so that we can investigate further.

**Comment by QJoly** [comment]
That's clearly my fault, I checked on the Packer GitHub repository (and not in the release).

Thank you for correcting me

**Review by qjoly — APPROVED** [review]
The update of licence isn't required for this version.

Sorry for my error.

**Review by figsoda — APPROVED** [review]

**Pull request merged**
