### PR TITLE
python3Packages.wallbox: init at 0.4.5

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Component tests can't be enabled because `test_form_invalid_auth` and `test_form_cannot_connect` access the network.
cc @mweinelt

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126896` at d96bb54c run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.wallbox</li>
    <li>python39Packages.wallbox</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Old PR for 0.4.4: #125482

**Comment by fabaff** [comment]
https://github.com/NixOS/nixpkgs/pull/125482/commits/35ca5b370a0d0b5d3b6a94696ed5990f23ef7bdb would enable Home Assistant's tests.

**Comment by dotlambda** [comment]
> Component tests can't be enabled because `test_form_invalid_auth` and `test_form_cannot_connect` access the network.

**Comment by mweinelt** [comment]
Addressed in https://github.com/NixOS/nixpkgs/pull/126896/commits/ac0e2f63d0237b653fc0f07a6868acfc8716c8e0.

**Pull request merged**
