### PR TITLE
python3Packages.lttng: init at 2.13.11

### PR DESCRIPTION
**Pull request by hacker1024**
## Description of changes

This package contains Python bindings to `liblttng-ctl` from [LTTng‑tools](https://github.com/lttng/lttng-tools).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

@bjornfor

### CODE REVIEW

**Review by bjornfor — APPROVED** [review]
LGTM.

The two commits can be squashed.

**Comment by bjornfor** [comment]
Maybe you can amend the commit and say in the commit body why this is a separate attribute which rebuilds lttng-tools, instead of adding python support directly to lttng-tools? (I'm guessing it's about closure size?)

**Comment by hacker1024** [comment]
> LGTM.
> 
> The two commits can be squashed.



> Maybe you can amend the commit and say in the commit body why this is a separate attribute which rebuilds lttng-tools, instead of adding python support directly to lttng-tools? (I'm guessing it's about closure size?)

Done and done.

**Comment by hacker1024** [comment]
I have switched to using the `PYTHON` and `PYTHON_CONFIG` environment variables to avoid polluting the `nativeBuildInputs`.

**Comment by bjornfor** [comment]
> Done and done.

Thanks.

> I have switched to using the `PYTHON` and `PYTHON_CONFIG` environment variables to avoid polluting the `nativeBuildInputs`.

Why is putting a build input in nativeBuildInputs "polluting" it? Using those variables seem more complicated to me. Or am I missing something?

Nit: Commit messages should be wrapped at 72 chars to avoid overlong lines.

**Comment by hacker1024** [comment]
> Why is putting a build input in nativeBuildInputs "polluting" it? Using those variables seem more complicated to me. Or am I missing something?

Nix treats `nativeBuildInputs` specially for cross-compilation, but in this case, cross-compilation is accounted for explicitly. Using the variables ensures that the platform setup isn't messed with further. It also allows regular Python to be added in the future if it is ever needed.

**Comment by bjornfor** [comment]
> > Why is putting a build input in nativeBuildInputs "polluting" it? Using those variables seem more complicated to me. Or am I missing something?
> 
> Nix treats `nativeBuildInputs` specially for cross-compilation, but in this case, cross-compilation is accounted for explicitly. Using the variables ensures that the platform setup isn't messed with further. It also allows regular Python to be added in the future if it is ever needed.

Put that in a code comment maybe?

**Comment by hacker1024** [comment]
I have added the comment and wrapped commit messages to 72 lines.

**Review by bjornfor — APPROVED** [review]

**Pull request merged**
