### PR TITLE
wasm: rename unofficial package into proglodyte-wasm

### PR DESCRIPTION
**Pull request by Ekleog**
###### Motivation for this change

The package is a concurrent to the official [wasm interpreter](https://github.com/WebAssembly/spec) (available as `ocamlPackages.wasm`), so I think the name is treacherous :)

If this could get in before 18.09 branch-off it'd likely be best, as it's a breaking change.

cc @proglodyte 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
This will probably need an alias.

**Comment by Ekleog** [comment]
@matthewbauer Up. Does that sound good to you? (we already missed the 18.09 branch-off)

 *  Alias `wasm` to `proglodyte-wasm`
 *  After 19.03 branch-off, remove the `wasm` alias
 *  After 19.09 branch-off, add a `wasm` alias to `ocamlPackages.wasm`

**Comment by matthewbauer** [comment]
Yeah sounds ok.

**Comment by Ekleog** [comment]
@matthewbauer Erhm… the PR wasn't actually adding the alias yet, as I was unsure this was OK with you :'( I've opened https://github.com/NixOS/nixpkgs/pull/48444 to add the alias back, think it'd be great if this could get merged ASAP to avoid in-between hydra bumps. (either that or live with the absence of alias, but that was the original issue :/)

**Pull request merged**
