### PR TITLE
duckdb,python311Packages.duckdb: 0.10.0 -> 0.10.1, add update script

### PR DESCRIPTION
**Pull request by ghost**
## Description of changes

https://github.com/duckdb/duckdb/releases/tag/v0.10.1

add an update script to provide the commit hash and version to the derivations which pass them to the builds via newly added `OVERRIDE_GIT_DESCRIBE`.

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build and are broken on master:</summary>
  <ul>
    <li>python311Packages.ibis-framework</li>
    <li>python311Packages.ibis-framework.dist</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>duckdb</li>
    <li>duckdb.dev</li>
    <li>duckdb.lib</li>
    <li>mycli</li>
    <li>mycli.dist</li>
    <li>python311Packages.duckdb</li>
    <li>python311Packages.duckdb-engine</li>
    <li>python311Packages.duckdb-engine.dist</li>
    <li>python311Packages.duckdb.dist</li>
    <li>python311Packages.sqlglot</li>
    <li>python311Packages.sqlglot.dist</li>
    <li>python312Packages.duckdb</li>
    <li>python312Packages.duckdb.dist</li>
    <li>python312Packages.sqlglot</li>
    <li>python312Packages.sqlglot.dist</li>
    <li>sbclPackages.duckdb</li>
  </ul>
</details>

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by cpcloud — APPROVED** [review]
Seems legit!

**Comment by cpcloud** [comment]
Might want to rebase on `master` given how far behind this PR is!

**Comment by a-n-n-a-l-e-e** [comment]
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python311Packages.ibis-framework</li>
    <li>python311Packages.ibis-framework.dist</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>duckdb</li>
    <li>duckdb.dev</li>
    <li>duckdb.lib</li>
    <li>mycli</li>
    <li>mycli.dist</li>
    <li>python311Packages.duckdb</li>
    <li>python311Packages.duckdb-engine</li>
    <li>python311Packages.duckdb-engine.dist</li>
    <li>python311Packages.duckdb.dist</li>
    <li>python311Packages.sqlglot</li>
    <li>python311Packages.sqlglot.dist</li>
    <li>python312Packages.duckdb</li>
    <li>python312Packages.duckdb.dist</li>
    <li>python312Packages.sqlglot</li>
    <li>python312Packages.sqlglot.dist</li>
    <li>sbclPackages.duckdb</li>
  </ul>
</details>

**Comment by cpcloud** [comment]
Feel free to disable as many ibis-framework tests as needed.

**Comment by a-n-n-a-l-e-e** [comment]
ibis is failing on master even after with a constraint on `sqlglot` and with that constraint removed various tests. it failing shouldn't block this PR given it was a per-existing condition.

error: builder for '/nix/store/iqkl0x98v9276d4d15dwc22h1dz01s9m-python3.11-ibis-framework-8.0.0.drv' failed with exit code 1;
       last 10 log lines:
       > FAILED ibis/backends/pandas/tests/execution/test_operations.py::test_aggregation_group_by[abs-complex] - FutureWarning: SeriesGroupBy.grouper is deprecated and will be removed in a...
       > FAILED ibis/backends/pandas/tests/execution/test_operations.py::test_aggregation_group_by[exp-simple] - FutureWarning: SeriesGroupBy.grouper is deprecated and will be removed in a...
       > FAILED ibis/backends/pandas/tests/execution/test_operations.py::test_order_by[plain_datetimes_naive-<lambda>-<lambda>-False1] - DeprecationWarning: The truth value of an empty array is ambiguous. Returni...
       > FAILED ibis/backends/pandas/tests/execution/test_operations.py::test_aggregation_group_by[log2-none] - FutureWarning: SeriesGroupBy.grouper is deprecated and will be removed in a...
       > FAILED ibis/backends/pandas/tests/execution/test_structs.py::test_struct_field_series_group_by_value - FutureWarning: SeriesGroupBy.grouper is deprecated and will be removed in a...
       > FAILED ibis/backends/pandas/tests/execution/test_operations.py::test_left_binary_op_gb[1c-mod] - FutureWarning: SeriesGroupBy.grouper is deprecated and will be removed in a...
       > FAILED ibis/backends/pandas/tests/execution/test_operations.py::test_left_binary_op_gb[1c-pow] - FutureWarning: SeriesGroupBy.grouper is deprecated and will be removed in a...
       > FAILED ibis/expr/operations/tests/test_generic.py::test_coerced_to_interval_value - KeyError: 's'
       > ===== 247 failed, 8140 passed, 83 skipped, 819 xfailed in 86.65s (0:01:26) =====
       > /nix/store/v099hqvw5z87423p4hz1vfhzaqa07dii-stdenv-linux/setup: line 1578: pop_var_context: head of shell_variables not a function context

**Pull request merged**
