### PR TITLE
matrix-synapse: 1.19.1 -> 1.19.2

### PR DESCRIPTION
**Pull request by ajs124**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by D4ndellion — APPROVED** [review]

**Review by fadenb — APPROVED** [review]
```
Ran 1142 tests in 511.921s

PASSED (skips=5, successes=1137)
```

**Comment by mweinelt** [comment]
```
Ran 1142 tests in 633.275s

PASSED (skips=5, successes=1137)
```

```
/nix/store/njykssngnvk9w4zilwp4n0711k4a9415-vm-test-run-matrix-synapse
``´

LGTM

**Review by mweinelt — APPROVED** [review]

**Review by martinetd — APPROVED** [review]
cherry-picked on 20.03 works-for-me (build tests as quoted previously and actual functionality seems OK)

**Comment by mguentner** [comment]
> cherry-picked on 20.03 works-for-me (build tests as quoted previously and actual functionality seems OK)

Can confirm

**Comment by Ma27** [comment]
@ajs124 thanks a lot for taking care of this! :heart:

**Pull request merged**
