### PR TITLE
imlib2: support webp by default, use full package in image viewers

### PR DESCRIPTION
**Pull request by ncfavier**
https://github.com/NixOS/nixpkgs/pull/186492 made some formats opt-in but didn't actually opt them in anywhere, so e.g. feh just lost webp support for no reason.

I completely agree with @jtojnar in https://github.com/NixOS/nixpkgs/pull/186492/files#r950566813 that an image library should support as many formats as possible by default. I am not sure where the 200 MB they talk about come from though, since even the full package only weighs 1.5 MB (vs 1.2 MB for the minimal one).

### CODE REVIEW

**Comment by risicle** [comment]
Look at the size of the full closure of that package, not just the package alone.

My suggestion would be for `feh` to use `imlib2Full` instead of `imlib2` - it is exactly the sort of package that would want to have the full complement of image formats supported.

**Comment by ncfavier** [comment]
Ah, of course. In that case I suggest a compromise: set webp to `true` as it was (this keeps the closure size at around 50 MB), keep the rest to `false`, and use `imlib2Full` for feh (and others?).

**Comment by risicle** [comment]
I think that makes sense.

**Comment by ncfavier** [comment]
Alright I think I got all the obvious ones

**Comment by risicle** [comment]
LGTM, passthru.tests pass & all updated image viewers build for me, nixos x86_64 & macos 10.15 (for those applicable to each platform).

But this will need to be re-targeted at staging because of the large number of rebuilds (using the technique described in https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging)

**Comment by ncfavier** [comment]
Done

**Review by risicle — APPROVED** [review]

**Pull request merged**
