### PR TITLE
avogadro2: 1.98.1 -> 1.99.0

### PR DESCRIPTION
**Pull request by sheepforce**
## Description of changes

Updates to the latest avogadrolibs and avogadroapp versions:
https://github.com/OpenChemistry/avogadrolibs/releases/tag/1.99.0
https://github.com/OpenChemistry/avogadroapp/releases/tag/1.99.0

This release should include fixes for Avogadro on Wayland.

I've also added `openbabel-unstable` and `python3Packages.openbabel-bindings-unstable`. The last OpenBabel release is nearly 4 years old but OpenBabel has been under steady development since then. Consumers like avogadro startet using new features, most importantly chemical JSON and are not working properly anymore with the latest stable release (e.g. can not export molecules to any helpful file format with old OpenBabel versions).
I'm not sure if this is the best approach, but it's the best I came up with :)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by markuskowa** [comment]
What would be the impact of simply updating openbabel stable to unstable? Would that break other packages?

**Comment by sheepforce** [comment]
Only two: 

  * `python3.pkgs.openbabel-bindings` which is easy to fix. The only complaint is that `unstable-xxx` is not a valid PEP 440 version string. I'm pretending to be a beta version now.
  * `molsketch` which fails with exactly one C++ error, which I assume _could_ be easy to fix:
```
[ 96%] Building CXX object molsketch/CMakeFiles/molsketch.dir/qrc_licenses.cpp.o
In file included from /build/Molsketch-0.8.0/obabeliface/obabeliface.cpp:53:
/build/Molsketch-0.8.0/obabeliface/obabeliface.cpp: In function 'bool Molsketch::hasCoordinates(OpenBabel::OBMol&)':
/nix/store/ncamfpizybnjqby2xyb97cc9v36hvvqx-openbabel-unstable-06-12-23/include/openbabel3/openbabel/obiter.h:417:49: error: 'impl' has not been declared
  417 | #define FOR_ATOMS_OF_MOL(a,m)     for (auto a : impl::MolGetAtoms(m))
```

**Comment by sheepforce** [comment]
I've pushed a version with openbabel simply updated to unstable and fixes for molsketch and the python bindings.

**Comment by sheepforce** [comment]
@GrahamcOfBorg build avogadro2 openbabel python3Packages.openbabel-bindings molsketch

**Pull request merged**
