### PR TITLE
nixos/qt5: add kde platform theme

### LINKED ISSUE #180131: nixos.modules.config.qt5: provide the possibility of using QT_QPA_PLATFORMTHEME="kde"
The reason why I didn't open a PR, is described in [Additional context](#Additional_context).

### Describe the bug
I'm aware of four platforms for Qt's themes right now:
- Using GTK themes through `qtstyleplugins` + `QT_STYLE_OVERRIDE`;
- Using GNOME themes through `qgnomeplatform` + `QT_STYLE_OVERRIDE`;
- Using Qt themes, with the non-KDE solution `qt5ct`, ***which uses [its own color schemes](https://sourceforge.net/p/qt5ct/code/HEAD/tree/trunk/qt5ct/colors)***;
- Using Plasma-targeted Qt themes, with `kde` as `QT_QPA_PLATFORMTHEME`, as done natively in a plasma session, ***using the theme's colorscheme***.

### Steps To Reproduce
1. Check [`qt5.platformTheme`](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/config/qt5.nix) and it does not provide `kde`;
2. No equivalent to [`programs.qt5ct.enable`](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/programs/qt5ct.nix) providing `kde`;
3. Enable `services.xserver.desktopManager.plasma5.enable = true;`, then add some Pasma-target themes like `[breeze-gtk breeze-icons breeze-qt5]`, then adjust envvars `export QT_QPA_PLATFORMTHEME='kde' QT_PLATFORM_PLUGIN='kde' QT_PLATFORMTHEME='kde'`, set the theme in `~/.config/kdeglobals` or with `QT_STYLE_OVERRIDE`, you'll get the right theme with the proper color scheme.

### Expected behavior
`qt5.platformTheme` should provide `kde` (or `plasma`) as an option, it should add only the required packages to the system, and set the proper envvars. (or maybe rename it, since qt6 also uses the same variables and envvars)

### Screenshots
- qbittorrent + breeze + `QT_QPA_PLATFORMTHEME=kde` + dark:
screenshot

- qbittorrent + breeze + `QT_QPA_PLATFORMTHEME=qt5ct` + dark:
screenshot

- qbittorrent + `QT_QPA_PLATFORMTHEME=gtk2` (ignored my theme):
screenshot

- qbittorrent + `QT_QPA_PLATFORMTHEME=gnome` (also ignored my theme):
screenshot

### Additional context
I tried to discover what package that is being added when evaluating `services.xserver.desktopManager.plasma5` provides this platform-theme, but I failed miserably.

### Notify maintainers
- stated as maintainers of plasma-integration: @ttuegel @nyanloutre
- stated as maintainer of qt5ct: @Ralith
- qt5 module contributors: @worldofpeace
- cc @thiagokokada 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
╭─pedrohlc at desktop in /home/pedrohlc
╰─λ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.51, NixOS, 22.11 (Raccoon), 22.11.20220702.660ac43`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by romildo**
###### Description of changes

Add the kde platform theme.

Fixes https://github.com/NixOS/nixpkgs/issues/180131.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thiagokokada** [comment]
CC @PedroHLC.

**Comment by PedroHLC** [comment]
I totally want to test this as last time I tried (7 months ago) `plasma-integration` wasn't enough, but I see that you also added `systemsettings`.

**Comment by romildo** [comment]
> I totally want to test this as last time I tried (7 months ago) `plasma-integration` wasn't enough, but I see that you also added `systemsettings`.

`plasma-integration` should be enough for the kde platform theme to work.

`systemsettings` is needed only to change Qt configuration without the full Plasma installed.

I have tested this on my system, and it worked.

**Review by PedroHLC — APPROVED** [review]
I don't know why it didn't work in the past, but now I'm fully able to reproduce it working!

**Pull request merged**
