### PR TITLE
nixos/systembus-notify: introduce module

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

Introduce a new NixOS module to support `systembus-notify` and make `earlyoom` use that instead of having it depend directly on the package.

Instead of running `systembus-notify` via XDG autostart, introduce a system user unit as it allows us to limit access.

Cc: @matthewbauer

Reference:
https://github.com/rfjakob/systembus-notify/issues/3

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 130003` at 22e68279 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>systembus-notify</li>
  </ul>
</details>

**Comment by peterhoeg** [comment]
Come to think of it, we should probably put a big, fat warning on this as it's basically a local DoS waiting to happen if any local user can essentially spam all other local users.

**Comment by peterhoeg** [comment]
I just tried sending 10000 messages as quickly as possible and that makes plasma hang. So yeah, this isn't great if you don't trust the users.

**Review by matthewbauer — APPROVED** [review]

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 130003` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>systembus-notify</li>
  </ul>
</details>

**Comment by maydayv7** [comment]
Can this also be backported to 21.11 if possible

**Comment by maydayv7** [comment]
I have an issue: The `systembus-notify` service does not start on user login when `services.earlyoom.enableNotifications = true;` using this PR

```shellsession
$ systemctl status --user systembus-notify
○ systembus-notify.service - system bus notification daemon
     Loaded: loaded (/run/current-system/sw/share/systemd/user/systembus-notify.service; linked-runtime; vendor preset: enabled)
     Active: inactive (dead)
```

**Comment by peterhoeg** [comment]
What is the output of `systemctl --user status graphical-session.target` ?

**Comment by maydayv7** [comment]
> What is the output of `systemctl --user status graphical-session.target` ?

```shellsession
● graphical-session.target - Current graphical user session
     Loaded: loaded (/etc/systemd/user/graphical-session.target; static)
    Drop-In: /nix/store/g04qycaf8nnrxx131nxq61ydbsjsg95g-user-units/graphical-session.target.d
             └─overrides.conf
     Active: active since Thu 2022-03-03 10:16:06 IST; 2min 40s ago
       Docs: man:systemd.special(7)
```

**Comment by peterhoeg** [comment]
Anything failed? `systemctl --user --failed` ?

**Comment by maydayv7** [comment]
> Anything failed? `systemctl --user --failed` ?

Nope
```shellsession
$ systemctl --user --failed
  UNIT LOAD ACTIVE SUB DESCRIPTION
-----------------------------------
0 loaded units listed.
```

**Pull request merged**
