### PR TITLE
nocrypto: 0.5.1 -> 0.5.3

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @vbgl 

I suspected that the change of `cstruct` would break things (especially on 4.01), but a `nox-review wip` did not reveal anything.

### CODE REVIEW

**Comment by vbgl** [comment]
Now `ocamlPackages.nocrypto` is broken (no longer evaluates).

`nox-review` does not attempt to build things that do not evaluate.

**Comment by sternenseemann** [comment]
@vbgl this is fine though, because the only package which depends on `nocrypto` currently is `x509` which also only evaluates for ocaml-version 4.02 or higher.

**Comment by vbgl** [comment]
Other packages in `nixpkgs` are fine; but what about the users? Commit 86c45fc has just _removed_ two packages.

**Comment by sternenseemann** [comment]
Yeah, that is right. The ocaml community that uses these libraries seems to be fast-moving currently, many are already using ocaml 4.04, so I don't think this is much of a problem.

But this is a general dilemma of ocamlPackages I'd suppose: Moving on with the development and offering stability. Especially because compiler updates break code, you end up with a “compatibility-matrix”…

**Pull request merged**
