### PR TITLE
emscripten: 1.37.13 -> 1.37.16

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change

Update to emscripten

###### Things done

Please check what applies. Note that these are not hard requirements but merely serve as information for reviewers.

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
Travis errors because it takes too long...

**Comment by NeQuissimus** [comment]
@matthewbauer Can you at least build it yourself? :) I am uncomfortable merging this when your PR says you haven't built it and Travis also fails (despite it meaning nothing for long-running builds)...

**Comment by matthewbauer** [comment]
Sorry forgot to check it. I've only tested on MacOS but it works without problems:

```
nixpkgs $ nix-build -A emscripten
/nix/store/1jbcsd6m6dslaa0srf5snicsjw3m0agj-emscripten-1.37.16
nixpkgs $ ls /nix/store/1jbcsd6m6dslaa0srf5snicsjw3m0agj-emscripten-1.37.16
bin  share
```

**Comment by Infinisil** [comment]
Can confirm that it builds on NixOS, also did a simple compilation with a C hello world.

**Pull request merged**
