### PR TITLE
nixos/i18n: don't build all supportedLocales by default

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by dasJ — APPROVED** [review]

**Comment by gebner** [comment]
This broke any custom `extraLocaleSettings`..

**Comment by gravndal** [comment]
Shouldn't this have been announced here: https://discourse.nixos.org/t/breaking-changes-announcement-for-unstable/17574?

Either way, wouldn't it make more sense to default to something like:
```
    supportedLocales = with config.i18n; lib.unique (
      (lib.mapAttrsToList (n: v: v + "/UTF-8")
        (lib.filterAttrs (n: v: n != "LANGUAGE") extraLocaleSettings)
      ) ++ [ (defaultLocale + "/UTF-8") ]
    );
```

**Comment by SuperSandro2000** [comment]
> Shouldn't this have been announced here: [discourse.nixos.org/t/breaking-changes-announcement-for-unstable/17574](https://discourse.nixos.org/t/breaking-changes-announcement-for-unstable/17574)?

I didn't even know that thread existed.



> Either way, wouldn't it make more sense to default to something like:

Please do a PR with that.



> This broke any custom `extraLocaleSettings` (like `LC_PAPER` or `LC_TIME` etc.).

Presumable only when they are set to something other than your display language?

**Comment by gravndal** [comment]
https://github.com/NixOS/nixpkgs/pull/179194

**Comment by gebner** [comment]
> > This broke any custom `extraLocaleSettings` (like `LC_PAPER` or `LC_TIME` etc.).
> 
> Presumable only when they are set to something other than your display language?

That's their only use, yes.  They default to the display language, so you don't need the override if it's the same.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/issues/179607

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/issues/179486

**Comment by sternenseemann** [comment]
I think unconditionally generating `C.UTF-8/UTF-8` is probably also a good idea.

**Comment by Profpatsch** [comment]
So we should revert this and reevaluate.

**Comment by Profpatsch** [comment]
Like, for example, not generating `C.UTF-8` by default shows that there is a fundamental gap in understanding here.

**Comment by SuperSandro2000** [comment]
> No, that’s not how that works.

If someone is presenting me a working code solution to a problem I think it is very reasonable to ask them to create a PR with that. The other option I would have would be to commit it as my own and then ask the same person to test their own code which is a bit weird.

> You can’t break other people’s systems and then tell them to fix it themselves.

That is wrong. Every change has the potential to break something somewhere in some combination of the infinity of potential system combinations. We can only consider so much when doing a change. That's why I wrote a changelog entry because I knew before that if people relied silently on other locales their setup would break. There is just no other way to not break this. I and two reviewers didn't think about ``extraLocaleSettings`` or ``eo`` and only almost two weeks later we noticed that some things break.

Also my time is not infinite and between real life and other work and projects I might only find time to do this in a few days in which the fix could have been already be commited, merged and be on unstable.

> So we should revert this and reevaluate.

Instead of hastily reverting changes and later reverting the revert, we should first consider if a small addition/change of code fixes those use cases or people need to adopt their config and explicitly mention a locale. 

> Like, for example, not generating `C.UTF-8` by default shows that there is a fundamental gap in understanding here.

First of all, I know how locales work and the special meaning behind c.utf-8.

Then this must have been broken for a good amount of time in the minimal profile which is used in containers similar to ``environment.noXlibs``.

---

Now back to fixing this instead of doing discussions.

First of all a big thanks to @gravndal for the two PRs fixing the situation when more complex settings are used. I'll really appreciate it.

Also regarding to #179486 : This must have been always broken but since we generated all locales by default this was never noticed. So to say we unconvered more bugs with this change that where always there.

Then why I didn't notice this while testing: I had ``C.UTF-8`` set in ``i18n.supportedLocales`` so I couldn't. Happens when your configuration is multiple thousand lines long. Going to fix that in a PR right now.

**Comment by Profpatsch** [comment]
> That is wrong. Every change has the potential to break something somewhere in some combination of the infinity of potential system combinations.

Given that this PR has neither any description, nor a commit description, I would not assume much thought has been put into possible breakage.

**Comment by dasJ** [comment]
It's called "unstable" for a reason…

**Comment by SuperSandro2000** [comment]
I wanted to write that, too. 😂 

Yes, breakages can happen even if we all try our best to avoid them.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/issues/180935

**Comment by SuperSandro2000** [comment]
I don't think that is good way to move this forward. I'd rather add an exception for that language instead of reverting improvements which where much needed and everyone benefits of.

**Comment by Artturin** [comment]
Another issue https://github.com/NixOS/nixpkgs/issues/183960

**Comment by gravndal** [comment]
@Artturin I don't think that's actually caused by this.

From some limited testing, it seems that if your current configured locales don't match the new supported locales reliably triggers those warnings.

A situation likes this can naturally occur if you're removing a locale from your `extraLocaleSettings`, e.g. I can trigger it by removing my `LC_TIME=en_DK.UTF-8` (the only location where I reference this specific locale).

**Pull request merged**
