### PR TITLE
Added YNAB paid wine package.

### PR DESCRIPTION
**Pull request by jraygauthier**
Also seamless integration same as when
using it on the windows platform. Even
dropbox sync is working and some form
of drag and drop for files.

### CODE REVIEW

**Comment by jagajaga** [comment]
That's a windows program (even wrapped with `wine` in your PR).
IMO we must not add such things to `nixpkgs`.

**Comment by jraygauthier** [comment]
Is there a more elaborate reason as to why? From my POV,
this is a pretty nice recipe for getting stuff installed automatically.
I don't mind keeping my recipe private but I thought it would be
nice to share it we the community, this is the reason for this
pull request. If undesirable fine. However, would be nice to
understand why.

**Comment by jagajaga** [comment]
сс @abbradar @lethalman @domenkozar

**Comment by abbradar** [comment]
On one hand I subjectively don't like the idea of adding Wine-emulated packages to the repository, sensing that `wine`, being a reverse-engineered runtime for a closed-source platform with a big bag'o'quirks, "should be avoided". However, `wine` is a runtime nevertheless like e.g. `python` or `java`, albeit reverse-engineered and quirky, and we have a bunch of closed-source packages already. I don't have a final opinion on this and feel that things of this kind should be written as a policy somewhere after a discussion.

Aside of that, there might be licensing issues (I'm not a lawyer!) -- can this be considered `redistribution` or perhaps `modifying`? I feel we should ask the company before packaging.

**Comment by edolstra** [comment]
Hm, I don't think we should do this. It's really going too far if we start including proprietary Windows packages in addition to Linux packages. 

Also, IMHO, the main consideration for accepting non-free packages is whether there is no (realistic) free alternative. For instance, you pretty much need the nvidia-x11 package if you want to do 3D graphics with NVIDIA hardware on Linux. But we already have free budgeting/accounting packages such as gnucash.

**Comment by jraygauthier** [comment]
Ok. Indeed multiple good arguments. Thanks you all for elaborating on this point.

**Comment by abbradar** [comment]
I think that work of this kind can be useful to someone nevertheless and should be published somewhere (although not in official repo). What about a Wiki entry?

**Comment by edolstra** [comment]
We could create a separate repository for packages that don't belong in Nixpkgs.

**Comment by jagajaga** [comment]
@edolstra like arch's `aur`?

**Comment by geerds** [comment]
Maybe something like `nixpkgs-contrib`

**Comment by jraygauthier** [comment]
The separate repository looks like a great idea to me.

**Pull request closed without merging**
