### PR TITLE
nixpkgs manual: Remove obsolete warning

### PR DESCRIPTION
**Pull request by lheckemann**
PR #815 has already been merged.

### CODE REVIEW

**Comment by vcunat** [comment]
https://github.com/NixOS/nix/pull/815 has been merged but the default nix version does **not** contain it yet. See https://github.com/NixOS/nixpkgs/issues/19761#issuecomment-255533511

**Comment by lheckemann** [comment]
Ah right, perhaps the warning should just be reworded then...

**Comment by domenkozar** [comment]
Ping

**Comment by vcunat** [comment]
@domenkozar: any indication the situation has changed?  I sadly still see 1.11.6 as the default, without that PR contained or picked.

**Comment by vcunat** [comment]
Ah, I'm sorry &ndash; you probably meant that the rewording should be done.

**Comment by lheckemann** [comment]
Since 1.11.8 is now the default version and contains the commit in question, I'm guessing this can be merged?

**Comment by vcunat** [comment]
Right, even though the situation isn't ideal, as discussed in #24717.

**Pull request merged**
