### PR TITLE
gitlab: 11.6.3 -> 11.7.3

### PR DESCRIPTION
**Pull request by jslight90**
###### Motivation for this change

New version with bugfixes.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Using in production with a ~15 user team.
---

### CODE REVIEW

**Comment by flokli** [comment]
@GrahamcOfBorg test gitlab

**Comment by andir** [comment]
@jslight90 can you update it to the latest version? There was a release just a while ago:

https://about.gitlab.com/2019/02/05/critical-security-release-gitlab-11-dot-7-dot-4-released/

@flokli how did the testing go?

**Comment by flokli** [comment]
bumped to 11.7.4, and tested locally on my sandbox instance.

**Comment by flokli** [comment]
backported to 18.09 in 12b1462924a6445537075003c0c8705ecbff3556.

**Pull request merged**
