### PR TITLE
home-assistant: 0.110.1 -> 0.111.0

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
Did someone ever try to get the NixOS test running again?

**Comment by Mic92** [comment]
The test requires a human to perform the initial. We would need to either include this data or remove tests that require a login.

**Comment by dotlambda** [comment]
But the documentation still mentions the lagecy api password: https://www.home-assistant.io/docs/authentication/providers/#legacy-api-password

**Comment by Mic92** [comment]
Yes. The API exists, however before the API can be used one has to go through an on boarding page.

**Comment by mweinelt** [comment]
Hmm, we could do that with Selenium, but I'm not sure to what degree the Onboarding Process is a moving target.

**Comment by dotlambda** [comment]
See https://github.com/NixOS/nixpkgs/issues/90149

**Review by mweinelt — APPROVED** [review]
Works for me.

**Comment by Mic92** [comment]
> Hmm, we could do that with Selenium, but I'm not sure to what degree the Onboarding Process is a moving target.

https://www.youtube.com/watch?v=WkODp99eQ4M

**Pull request merged**
