### PR TITLE
galaxy-buds-client: 5.1.0 -> 5.1.1

### PR DESCRIPTION
**Pull request by Icy-Thought**
###### Changelogs
- https://github.com/timschneeb/GalaxyBudsClient/releases/tag/5.1.1

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 365231`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>galaxy-buds-client</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>galaxy-buds-client</li>
  </ul>
</details>

**Comment by khaneliman** [comment]
Seems to fail the same way on master. 

```bash
/build/source/GalaxyBudsClient/GalaxyBudsClient.csproj : error NU1101: Unable to find package Microsoft.NETCore.App.Host.linux-x64. No packages exist with this id in source(s): _nix
```

Looks like the dotnet flag was only set for x64 https://github.com/NixOS/nixpkgs/pull/365231/files#diff-0481f4c907609b2332cf110e6aad41041f189c410538e7f5613bc5fc9e3697a8R30

**Comment by khaneliman** [comment]
```nix
dotnetFlags =
    lib.optionals stdenv.hostPlatform.isx86_64 [ "-p:Runtimeidentifier=linux-x64" ]
    ++ lib.optionals stdenv.hostPlatform.isAarch64 [ "-p:Runtimeidentifier=linux-arm64" ];
```

**Comment by Icy-Thought** [comment]
@khaneliman would you like to add those flags to the current PR or should I just do it and rebase?

**Comment by khaneliman** [comment]
> @khaneliman would you like to add those flags to the current PR or should I just do it and rebase?

Figured you could add it while you're in here.

**Comment by Icy-Thought** [comment]
No worries, I was just thinking of giving credits to the original author of those lines! :)
I am going to add them to my PR right away!

**Comment by khaneliman** [comment]
Says there is a merge conflict, somehow.

**Comment by Icy-Thought** [comment]
Very strange..

**Comment by khaneliman** [comment]
> Very strange.. I can see that deps.nix is the culprit, but I do not understand why that should trigger a merge conflict.

Just rebase on master and take your changes.

**Comment by Icy-Thought** [comment]
Alright this is strange. It appears as if something deleted the deps.nix in master recently for the merge conflict to arise.

**Comment by Icy-Thought** [comment]
DON'T MERGE! Apparently there was a "silent" migration to deps.json instead... Someone notify when there is such change, please...

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 365231`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>galaxy-buds-client</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>galaxy-buds-client</li>
  </ul>
</details>

**Review by khaneliman — APPROVED** [review]
LGTM, thanks for handling that

**Pull request merged**
