### PR TITLE
kitty: 0.18.1 → 0.18.2

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

<https://github.com/kovidgoyal/kitty/releases/tag/v0.18.2>

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
@grahamcofborg build kitty

**Comment by sikmir** [comment]
Result of `nixpkgs-review pr 94240` on darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
<br>- kitty
</details>

```
builder for '/nix/store/cc6c9qb5l1d4frav2cv80cjhv1ir3zrm-kitty-0.18.2.drv' failed with exit code 1; last 10 log lines:
      cache[rtype].remove(name)
  KeyError: '/mp-vkbse8fx'
  Traceback (most recent call last):
    File "/nix/store/rf859gichqk3rvxw7xnlavpc8zalsk62-python3-3.8.3/lib/python3.8/multiprocessing/resource_tracker.py", line 201, in main
      cache[rtype].remove(name)
  KeyError: '/mp-onh27hyr'
  Traceback (most recent call last):
    File "/nix/store/rf859gichqk3rvxw7xnlavpc8zalsk62-python3-3.8.3/lib/python3.8/multiprocessing/resource_tracker.py", line 201, in main
      cache[rtype].remove(name)
  KeyError: '/mp-bkf0meiz'
cannot build derivation '/nix/store/51cgkdi3qv0j1127mwvxwjmxrp2bq82b-env.drv': 1 dependencies couldn't be built
```

**Comment by Mic92** [comment]
> Result of `nixpkgs-review pr 94240` on darwin [1](https://github.com/Mic92/nixpkgs-review)
> 1 package failed to build:
> - kitty
> 
> ```
> builder for '/nix/store/cc6c9qb5l1d4frav2cv80cjhv1ir3zrm-kitty-0.18.2.drv' failed with exit code 1; last 10 log lines:
>       cache[rtype].remove(name)
>   KeyError: '/mp-vkbse8fx'
>   Traceback (most recent call last):
>     File "/nix/store/rf859gichqk3rvxw7xnlavpc8zalsk62-python3-3.8.3/lib/python3.8/multiprocessing/resource_tracker.py", line 201, in main
>       cache[rtype].remove(name)
>   KeyError: '/mp-onh27hyr'
>   Traceback (most recent call last):
>     File "/nix/store/rf859gichqk3rvxw7xnlavpc8zalsk62-python3-3.8.3/lib/python3.8/multiprocessing/resource_tracker.py", line 201, in main
>       cache[rtype].remove(name)
>   KeyError: '/mp-bkf0meiz'
> cannot build derivation '/nix/store/51cgkdi3qv0j1127mwvxwjmxrp2bq82b-env.drv': 1 dependencies couldn't be built
> ```

Can you do a `nix log /nix/store/cc6c9qb5l1d4frav2cv80cjhv1ir3zrm-kitty-0.18.2.drv` ?

**Comment by sternenseemann** [comment]
Oh great, another cryptic error message related to `test_multiprocessing_spawn` (?), I'll see whether I can figure this out.

**Comment by Mic92** [comment]
@GrahamcOfBorg build kitty

**Comment by Mic92** [comment]
We can also get the full log from ofborg...

**Comment by Mic92** [comment]
I would say just `test_multiprocessing_spawn` on macOS for now.

**Comment by sternenseemann** [comment]
@Mic92  Yeah, I'm pretty sure, I know what the issue is, I'll quickly boot up my macOS machine and test the fix.

**Comment by sternenseemann** [comment]
Fixed in e94a383c5718f0730a514ab77b66c2b51cd454f5.

**Comment by sternenseemann** [comment]
Fixed in c8f1df041f5801f79c3441398f20cb4c71bc5e90.

**Comment by Luflosi** [comment]
Your commit was very helpful. I think I found a good way to do this in kitty so we don't need to change the PATH. I'll report back once I've made a PR upstream, then we can apply that as a patch.

**Comment by sternenseemann** [comment]
It's only really a problem in the tests for `nixpkgs`, right? `kitty` is wrapped to include itself in `PATH` anyways normally.

**Comment by Luflosi** [comment]
Well, this problem could also happen in other environments when running the tests with kitty not in the path or in `kitty/launcher`, see https://github.com/kovidgoyal/kitty/issues/2881 for example. For nixpkgs as well it's only a problem when running the tests as far as I know.
I made a PR in https://github.com/kovidgoyal/kitty/pull/2885, which I expect to be reviewed and hopefully merged in a couple hours.

**Comment by Mic92** [comment]
@GrahamcOfBorg build kitty

**Comment by Mic92** [comment]
Result of `nixpkgs-review pr 94240` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- kitty
</details>

**Comment by Luflosi** [comment]
The solution upstream recommends is to build the launcher before running the tests, see https://github.com/kovidgoyal/kitty/pull/2885. I think I'll do this when I update kitty the next time.

**Comment by Mic92** [comment]
There is an installCheckPhase for that.

**Pull request merged**
