### PR TITLE
perlPackages.Mojolicious: 9.35 -> 9.36

### PR DESCRIPTION
**Pull request by marcusramberg**
## Description of changes

Changelog: https://metacpan.org/dist/Mojolicious/changes#L2

## Things done

Added myself to maintainers

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by marcusramberg** [comment]
```
30 packages built:
abcde convos convos.devdoc get_iplayer get_iplayer.man lanraragi perl536Packages.CPANAudit perl536Packages.CPANAudit.devdoc perl536Packages.JSONValidator perl536Packages.JSONValidator.devdoc perl536Packages.LinkEmbedder perl536Packages.LinkEmbedder.devdoc perl536Packages.Minion perl536Packages.Minion.devdoc perl536Packages.MinionBackendRedis perl536Packages.MinionBackendRedis.devdoc perl536Packages.MinionBackendSQLite perl536Packages.MinionBackendSQLite.devdoc perl536Packages.MinionBackendmysql perl536Packages.MinionBackendmysql.devdoc perl536Packages.MojoIOLoopDelay perl536Packages.MojoIOLoopDelay.devdoc perl536Packages.MojoIOLoopForkCall perl536Packages.MojoIOLoopForkCall.devdoc perl536Packages.MojoJWT perl536Packages.MojoJWT.devdoc perl536Packages.MojoPg perl536Packages.MojoPg.devdoc perl536Packages.MojoRedis perl536Packages.MojoRedis.devdoc perl536Packages.MojoSAML perl536Packages.MojoSAML.devdoc perl536Packages.MojoSQLite perl536Packages.MojoSQLite.devdoc perl536Packages.MojoUserAgentCached perl536Packages.MojoUserAgentCached.devdoc perl536Packages.Mojolicious perl536Packages.Mojolicious.devdoc perl536Packages.MojoliciousPluginAssetPack perl536Packages.MojoliciousPluginAssetPack.devdoc perl536Packages.MojoliciousPluginGravatar perl536Packages.MojoliciousPluginGravatar.devdoc perl536Packages.MojoliciousPluginI18N perl536Packages.MojoliciousPluginI18N.devdoc perl536Packages.MojoliciousPluginMail perl536Packages.MojoliciousPluginMail.devdoc perl536Packages.MojoliciousPluginOpenAPI perl536Packages.MojoliciousPluginOpenAPI.devdoc perl536Packages.MojoliciousPluginRenderFile perl536Packages.MojoliciousPluginRenderFile.devdoc perl536Packages.MojoliciousPluginStatus perl536Packages.MojoliciousPluginStatus.devdoc perl536Packages.MojoliciousPluginSyslog perl536Packages.MojoliciousPluginSyslog.devdoc perl536Packages.MojoliciousPluginTemplateToolkit perl536Packages.MojoliciousPluginTemplateToolkit.devdoc perl536Packages.MojoliciousPluginTextExceptions perl536Packages.MojoliciousPluginTextExceptions.devdoc perl536Packages.MojoliciousPluginWebpack perl536Packages.MojoliciousPluginWebpack.devdoc perl536Packages.Mojomysql perl536Packages.Mojomysql.devdoc perl536Packages.MusicBrainz perl536Packages.MusicBrainz.devdoc perl536Packages.OpenAPIClient perl536Packages.OpenAPIClient.devdoc perl536Packages.Yancy perl536Packages.Yancy.devdoc perl538Packages.CPANAudit perl538Packages.CPANAudit.devdoc perl538Packages.JSONValidator perl538Packages.JSONValidator.devdoc perl538Packages.LinkEmbedder perl538Packages.LinkEmbedder.devdoc perl538Packages.Minion perl538Packages.Minion.devdoc perl538Packages.MinionBackendRedis perl538Packages.MinionBackendRedis.devdoc perl538Packages.MinionBackendSQLite perl538Packages.MinionBackendSQLite.devdoc perl538Packages.MinionBackendmysql perl538Packages.MinionBackendmysql.devdoc perl538Packages.MojoIOLoopDelay perl538Packages.MojoIOLoopDelay.devdoc perl538Packages.MojoIOLoopForkCall perl538Packages.MojoIOLoopForkCall.devdoc perl538Packages.MojoJWT perl538Packages.MojoJWT.devdoc perl538Packages.MojoPg perl538Packages.MojoPg.devdoc perl538Packages.MojoRedis perl538Packages.MojoRedis.devdoc perl538Packages.MojoSAML perl538Packages.MojoSAML.devdoc perl538Packages.MojoSQLite perl538Packages.MojoSQLite.devdoc perl538Packages.MojoUserAgentCached perl538Packages.MojoUserAgentCached.devdoc perl538Packages.Mojolicious perl538Packages.Mojolicious.devdoc perl538Packages.MojoliciousPluginAssetPack perl538Packages.MojoliciousPluginAssetPack.devdoc perl538Packages.MojoliciousPluginGravatar perl538Packages.MojoliciousPluginGravatar.devdoc perl538Packages.MojoliciousPluginI18N perl538Packages.MojoliciousPluginI18N.devdoc perl538Packages.MojoliciousPluginMail perl538Packages.MojoliciousPluginMail.devdoc perl538Packages.MojoliciousPluginOpenAPI perl538Packages.MojoliciousPluginOpenAPI.devdoc perl538Packages.MojoliciousPluginRenderFile perl538Packages.MojoliciousPluginRenderFile.devdoc perl538Packages.MojoliciousPluginStatus perl538Packages.MojoliciousPluginStatus.devdoc perl538Packages.MojoliciousPluginSyslog perl538Packages.MojoliciousPluginSyslog.devdoc perl538Packages.MojoliciousPluginTemplateToolkit perl538Packages.MojoliciousPluginTemplateToolkit.devdoc perl538Packages.MojoliciousPluginTextExceptions perl538Packages.MojoliciousPluginTextExceptions.devdoc perl538Packages.MojoliciousPluginWebpack perl538Packages.MojoliciousPluginWebpack.devdoc perl538Packages.Mojomysql perl538Packages.Mojomysql.devdoc perl538Packages.MusicBrainz perl538Packages.MusicBrainz.devdoc perl538Packages.OpenAPIClient perl538Packages.OpenAPIClient.devdoc perl538Packages.Yancy perl538Packages.Yancy.devdoc
```

**Comment by zakame** [comment]
Result of `nixpkgs-review pr 308289` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>130 packages built:</summary>
  <ul>
    <li>abcde</li>
    <li>convos</li>
    <li>convos.devdoc</li>
    <li>get_iplayer</li>
    <li>get_iplayer.man</li>
    <li>lanraragi</li>
    <li>perl536Packages.CPANAudit</li>
    <li>perl536Packages.CPANAudit.devdoc</li>
    <li>perl536Packages.JSONValidator</li>
    <li>perl536Packages.JSONValidator.devdoc</li>
    <li>perl536Packages.LinkEmbedder</li>
    <li>perl536Packages.LinkEmbedder.devdoc</li>
    <li>perl536Packages.Minion</li>
    <li>perl536Packages.Minion.devdoc</li>
    <li>perl536Packages.MinionBackendRedis</li>
    <li>perl536Packages.MinionBackendRedis.devdoc</li>
    <li>perl536Packages.MinionBackendSQLite</li>
    <li>perl536Packages.MinionBackendSQLite.devdoc</li>
    <li>perl536Packages.MinionBackendmysql</li>
    <li>perl536Packages.MinionBackendmysql.devdoc</li>
    <li>perl536Packages.MojoIOLoopDelay</li>
    <li>perl536Packages.MojoIOLoopDelay.devdoc</li>
    <li>perl536Packages.MojoIOLoopForkCall</li>
    <li>perl536Packages.MojoIOLoopForkCall.devdoc</li>
    <li>perl536Packages.MojoJWT</li>
    <li>perl536Packages.MojoJWT.devdoc</li>
    <li>perl536Packages.MojoPg</li>
    <li>perl536Packages.MojoPg.devdoc</li>
    <li>perl536Packages.MojoRedis</li>
    <li>perl536Packages.MojoRedis.devdoc</li>
    <li>perl536Packages.MojoSAML</li>
    <li>perl536Packages.MojoSAML.devdoc</li>
    <li>perl536Packages.MojoSQLite</li>
    <li>perl536Packages.MojoSQLite.devdoc</li>
    <li>perl536Packages.MojoUserAgentCached</li>
    <li>perl536Packages.MojoUserAgentCached.devdoc</li>
    <li>perl536Packages.Mojolicious</li>
    <li>perl536Packages.Mojolicious.devdoc</li>
    <li>perl536Packages.MojoliciousPluginAssetPack</li>
    <li>perl536Packages.MojoliciousPluginAssetPack.devdoc</li>
    <li>perl536Packages.MojoliciousPluginGravatar</li>
    <li>perl536Packages.MojoliciousPluginGravatar.devdoc</li>
    <li>perl536Packages.MojoliciousPluginI18N</li>
    <li>perl536Packages.MojoliciousPluginI18N.devdoc</li>
    <li>perl536Packages.MojoliciousPluginMail</li>
    <li>perl536Packages.MojoliciousPluginMail.devdoc</li>
    <li>perl536Packages.MojoliciousPluginOpenAPI</li>
    <li>perl536Packages.MojoliciousPluginOpenAPI.devdoc</li>
    <li>perl536Packages.MojoliciousPluginRenderFile</li>
    <li>perl536Packages.MojoliciousPluginRenderFile.devdoc</li>
    <li>perl536Packages.MojoliciousPluginStatus</li>
    <li>perl536Packages.MojoliciousPluginStatus.devdoc</li>
    <li>perl536Packages.MojoliciousPluginSyslog</li>
    <li>perl536Packages.MojoliciousPluginSyslog.devdoc</li>
    <li>perl536Packages.MojoliciousPluginTemplateToolkit</li>
    <li>perl536Packages.MojoliciousPluginTemplateToolkit.devdoc</li>
    <li>perl536Packages.MojoliciousPluginTextExceptions</li>
    <li>perl536Packages.MojoliciousPluginTextExceptions.devdoc</li>
    <li>perl536Packages.MojoliciousPluginWebpack</li>
    <li>perl536Packages.MojoliciousPluginWebpack.devdoc</li>
    <li>perl536Packages.Mojomysql</li>
    <li>perl536Packages.Mojomysql.devdoc</li>
    <li>perl536Packages.MusicBrainz</li>
    <li>perl536Packages.MusicBrainz.devdoc</li>
    <li>perl536Packages.OpenAPIClient</li>
    <li>perl536Packages.OpenAPIClient.devdoc</li>
    <li>perl536Packages.Yancy</li>
    <li>perl536Packages.Yancy.devdoc</li>
    <li>perl538Packages.CPANAudit</li>
    <li>perl538Packages.CPANAudit.devdoc</li>
    <li>perl538Packages.JSONValidator</li>
    <li>perl538Packages.JSONValidator.devdoc</li>
    <li>perl538Packages.LinkEmbedder</li>
    <li>perl538Packages.LinkEmbedder.devdoc</li>
    <li>perl538Packages.Minion</li>
    <li>perl538Packages.Minion.devdoc</li>
    <li>perl538Packages.MinionBackendRedis</li>
    <li>perl538Packages.MinionBackendRedis.devdoc</li>
    <li>perl538Packages.MinionBackendSQLite</li>
    <li>perl538Packages.MinionBackendSQLite.devdoc</li>
    <li>perl538Packages.MinionBackendmysql</li>
    <li>perl538Packages.MinionBackendmysql.devdoc</li>
    <li>perl538Packages.MojoIOLoopDelay</li>
    <li>perl538Packages.MojoIOLoopDelay.devdoc</li>
    <li>perl538Packages.MojoIOLoopForkCall</li>
    <li>perl538Packages.MojoIOLoopForkCall.devdoc</li>
    <li>perl538Packages.MojoJWT</li>
    <li>perl538Packages.MojoJWT.devdoc</li>
    <li>perl538Packages.MojoPg</li>
    <li>perl538Packages.MojoPg.devdoc</li>
    <li>perl538Packages.MojoRedis</li>
    <li>perl538Packages.MojoRedis.devdoc</li>
    <li>perl538Packages.MojoSAML</li>
    <li>perl538Packages.MojoSAML.devdoc</li>
    <li>perl538Packages.MojoSQLite</li>
    <li>perl538Packages.MojoSQLite.devdoc</li>
    <li>perl538Packages.MojoUserAgentCached</li>
    <li>perl538Packages.MojoUserAgentCached.devdoc</li>
    <li>perl538Packages.Mojolicious</li>
    <li>perl538Packages.Mojolicious.devdoc</li>
    <li>perl538Packages.MojoliciousPluginAssetPack</li>
    <li>perl538Packages.MojoliciousPluginAssetPack.devdoc</li>
    <li>perl538Packages.MojoliciousPluginGravatar</li>
    <li>perl538Packages.MojoliciousPluginGravatar.devdoc</li>
    <li>perl538Packages.MojoliciousPluginI18N</li>
    <li>perl538Packages.MojoliciousPluginI18N.devdoc</li>
    <li>perl538Packages.MojoliciousPluginMail</li>
    <li>perl538Packages.MojoliciousPluginMail.devdoc</li>
    <li>perl538Packages.MojoliciousPluginOpenAPI</li>
    <li>perl538Packages.MojoliciousPluginOpenAPI.devdoc</li>
    <li>perl538Packages.MojoliciousPluginRenderFile</li>
    <li>perl538Packages.MojoliciousPluginRenderFile.devdoc</li>
    <li>perl538Packages.MojoliciousPluginStatus</li>
    <li>perl538Packages.MojoliciousPluginStatus.devdoc</li>
    <li>perl538Packages.MojoliciousPluginSyslog</li>
    <li>perl538Packages.MojoliciousPluginSyslog.devdoc</li>
    <li>perl538Packages.MojoliciousPluginTemplateToolkit</li>
    <li>perl538Packages.MojoliciousPluginTemplateToolkit.devdoc</li>
    <li>perl538Packages.MojoliciousPluginTextExceptions</li>
    <li>perl538Packages.MojoliciousPluginTextExceptions.devdoc</li>
    <li>perl538Packages.MojoliciousPluginWebpack</li>
    <li>perl538Packages.MojoliciousPluginWebpack.devdoc</li>
    <li>perl538Packages.Mojomysql</li>
    <li>perl538Packages.Mojomysql.devdoc</li>
    <li>perl538Packages.MusicBrainz</li>
    <li>perl538Packages.MusicBrainz.devdoc</li>
    <li>perl538Packages.OpenAPIClient</li>
    <li>perl538Packages.OpenAPIClient.devdoc</li>
    <li>perl538Packages.Yancy</li>
    <li>perl538Packages.Yancy.devdoc</li>
  </ul>
</details>

**Review by zakame — APPROVED** [review]

**Review by stigtsp — CHANGES_REQUESTED** [review]
Nitpick: Please use `perlPackages` as a prefix in the commit message instead of `perl538Packages`, otherwise LGTM

**Review by zakame — CHANGES_REQUESTED** [review]
As @stigtsp said, need to rewrite the commit message for consistency.

**Comment by marcusramberg** [comment]
> Nitpick: Please use `perlPackages` as a prefix in the commit message instead of `perl538Packages`, otherwise LGTM

No problem. I just blindly copied the format of the last changes to `perl-packages.nix` but I agree without version makes more sense. updated the commit now.

**Review by zakame — APPROVED** [review]

**Review by stigtsp — APPROVED** [review]

**Pull request merged**
