### PR TITLE
ansible-lint: 5.0.8 -> 5.1.2

### PR DESCRIPTION
**Pull request by elliot-u410**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 136190` at 284e5525 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/83ee0a069b3bfd28fd15732f98d5648d">ansible-lint</a> (python39Packages.ansible-lint)</li>
    <li><a href="https://gist.github.com/1950389e68dc1fb83bfc34ee3782ec39">python38Packages.ansible-lint</a></li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by noch3** [comment]
Looks like tests also fail on aarch64. I can turn them off on that arch as well.

**Comment by mweinelt** [comment]
Disable the tests that require network access. The other tests are failing with `internal-error: the role 'test-role' was not found in [...]` and I'd rather look for a fix than simply disable those.

**Comment by domenkozar** [comment]
Let's merge this and improve tests later?

**Comment by mweinelt** [comment]
The tests are failing, they need to be checked for breakage on our end. I'll take a look later if the author doesn't.

**Comment by noch3** [comment]
I may have time later this week to look into fixing the tests, but probably best if you don't wait for me.

**Pull request closed without merging**
