### PR TITLE
msieve: 1050 -> 1056

### PR DESCRIPTION
**Pull request by vegamink**
## Description of changes

Add VBITS info to output.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Moraxyc** [comment]
Please change the PR target to `master`

**Comment by Moraxyc** [comment]
Your commit message should match `{packageName}: {oldVersion} -> {newVersion}`

**Comment by Moraxyc** [comment]
Result of `nixpkgs-review pr 311732` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>msieve</li>
  </ul>
</details>

**Review by Moraxyc — APPROVED** [review]

**Comment by Moraxyc** [comment]
> Your commit message should match {packageName}: {oldVersion} -> {newVersion}

well...please rebase your commit and edit the commit msg to match the rule.

**Comment by vegamink** [comment]
If there is an update to this pull request do I create a new pull request or make changes to this one?

See my edits here: https://github.com/NixOS/nixpkgs/pull/318125/commits/e71dd6a296cad2830769057b893c64122a41e6a9

**Comment by pbsds** [comment]
You may force-push the update, or stack bump commits. Generally we prefer the first one

**Review by JohnAZoidberg — APPROVED** [review]
Tested with:

```
./result/bin/msieve 0xA41006DEFD378B7395B4E2EB1EC9BF56A61CD9C3B5A0A73528521EEB2FB817A7
```

**Comment by JohnAZoidberg** [comment]
I helped you rebase and also updated it to the latest revision :)

**Comment by pbsds** [comment]
@JohnAZoidberg 1a12a2d879cf694ee487c8ce76317a50b0203e1a doesn't follow the nixpkgs commit message schema. It is okay to make mistakes, but please be more mindful going forward :)

**Comment by JohnAZoidberg** [comment]
Ah sorry, because j just amended the original commit, I didn't notice the beginning part was wrong

**Pull request merged**
