### PR TITLE
wraith-master: init at 1.2.1

### PR DESCRIPTION
**Pull request by auroraanna**
###### Description of changes

Taking on #131519. Add the wraith-master package with cli and gtk frontend.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by serebit** [comment]
No support for aarch64 or darwin, fyi, only amd64-linux.

**Comment by papojari** [comment]
There is no platform named `amd64-linux`.

**Comment by papojari** [comment]
@serebit if you want to be a maintainer please make an entry in the maintainers file and make a PR to my fork or post it here.

**Comment by serebit** [comment]
I'm okay with you maintaining this package - given that I'm not on Nix, I'm not sure I'd trust myself with proper maintainership.

**Comment by papojari** [comment]
Ok, so I guess I won't add you as a maintainer then.

**Comment by alex-fu27** [comment]
Why is this still a draft? Is it still relevant? In case you want to still get it into nixpkgs, it currently doesnt build:
```
building '/nix/store/gnq9ssrj06sspzk8yaljiwc8hq5dxgqb-wraith-master-1.2.1.drv'...
unpacking sources
unpacking source archive /nix/store/ld05v6mgc2xkaavj7n4xa0rbj1hvh742-source
source root is source
patching sources
updateAutotoolsGnuConfigScriptsPhase
configuring
no configure script, doing nothing
building
build flags: SHELL=/nix/store/q1c2flcykgr4wwg5a6h450hxbk4ch589-bash-5.2-p15/bin/bash
install -Dm 0644 resources/common/99-wraith-master.rules build/PACKAGE/udev/99-wraith-master.rules
mkdir -p build/PACKAGE/man
scdoc < resources/cli/wraith-master.1.scd > build/PACKAGE/man/wraith-master.1
scdoc < resources/gtk/wraith-master-gtk.1.scd > build/PACKAGE/man/wraith-master-gtk.1
gradle --no-daemon --console=plain  linkReleaseExecutableLinuxX64

Welcome to Gradle 8.4!

Here are the highlights of this release:
 - Compiling and testing with Java 21
 - Faster Java compilation on Windows
 - Role focused dependency configurations creation

For more details see https://docs.gradle.org/8.4/release-notes.html

To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.4/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build 
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/build/source/build.gradle.kts' line: 1

* What went wrong:
Plugin [id: 'org.jetbrains.kotlin.multiplatform', version: '1.6.0', apply: false] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.jetbrains.kotlin.multiplatform:org.jetbrains.kotlin.multiplatform.gradle.plugin:1.6.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 18s
make: *** [Makefile:37: all] Error 1
error: builder for '/nix/store/gnq9ssrj06sspzk8yaljiwc8hq5dxgqb-wraith-master-1.2.1.drv' failed with exit code 2;
       last 10 log lines:
       >     Gradle Central Plugin Repository
       >
       > * Try:
       > > Run with --stacktrace option to get the stack trace.
       > > Run with --info or --debug option to get more log output.
       > > Run with --scan to get full insights.
       > > Get more help at https://help.gradle.org.
       >
       > BUILD FAILED in 18s
       > make: *** [Makefile:37: all] Error 1
       For full logs, run 'nix log /nix/store/gnq9ssrj06sspzk8yaljiwc8hq5dxgqb-wraith-master-1.2.1.drv'.
```

**Pull request closed without merging**
