### PR TITLE
Add friedow as a maintainer

### PR DESCRIPTION
**Pull request by friedow**
## Description of changes

Add myself as a maintainer :)

## Things done
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by a-kenji — APPROVED** [review]

**Comment by alyssais** [comment]
Please follow the guidelines in CONTRIBUTING.md for commit message formatting.

**Comment by alyssais** [comment]
Please follow the guidelines in CONTRIBUTING.md for commit message formatting.

**Comment by alyssais** [comment]
aaaa sorry, I was somehow looking at a 30 minute old version of the PR

**Comment by alyssais** [comment]
aaaa sorry, I was somehow looking at a 30 minute old version of the PR

**Comment by friedow** [comment]
You're damn fast with checking out new PRs though :D. I've corrected that right away but it seems you got the old version anyways. Impressive!

**Pull request merged**
