### PR TITLE
coq_8_15: init at 8.15+rc1

### PR DESCRIPTION
**Pull request by vbgl**
###### Motivation for this change

Prepare for next release.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
On macos 10.15:

```
builder for '/nix/store/a3jidc2sz6pw4sqdskjs8dc3a1wl1q11-source.drv' failed with exit code 1; last 10 log lines:
  checkdir error:  cannot create coq-8.15-rc1/test-suite/misc/deps/+?+?
                   Illegal byte sequence
                   unable to process coq-8.15-rc1/test-suite/misc/deps/+?+?/.
  checkdir error:  cannot create coq-8.15-rc1/test-suite/misc/deps/+?+?
                   Illegal byte sequence
                   unable to process coq-8.15-rc1/test-suite/misc/deps/+?+?/+?+?.v.
  checkdir error:  cannot create coq-8.15-rc1/test-suite/misc/deps/+?+?
                   Illegal byte sequence
                   unable to process coq-8.15-rc1/test-suite/misc/deps/+?+?/+?+?.v.
  do not know how to unpack source archive /private/tmp/nix-build-source.drv-0/V8.15+rc1.zip
```

**Comment by vbgl** [comment]
IIRC, this is a bug of `fetchzip`.

**Comment by Zimmi48** [comment]
Indeed, this is a known issue which becomes irrelevant for macOS users because the source is downloaded directly from the official NixOS binary cache (which is why it has been there for many versions without being detected).

**Review by Zimmi48 — APPROVED** [review]
Confirmed with the coq-nix-toolbox CI that everything in `coqPackages_8_15` builds correctly.

**Pull request merged**
