### PR TITLE
beam: tooling upgrade (rebar3, hex2nix, relx, etc)

### PR DESCRIPTION
**Pull request by gleber**
###### Motivation for this change

This change upgrades all Beam tooling to the newest versions and:
- makes the tooling depend on explicit non-automatically generated Hex packages => this makes upgrading hex-packages.nix to no longer break tooling necessary to do the upgrade at cost of minimal duplication;
- since buildRebar3 depends on rebar3 port compiler package (pc), make it into an explicit manually defined package;
- redo rebar3 hermeticity patch to make it smaller and more robust;
- upgrade hex-pm-registry-snapshot;
- adds @gleber to CODEOWNERs for beam-related packages.

Part of #11748 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- [x] Tested using sandboxing (option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

CC @ankhers @ericbmerritt

### CODE REVIEW

**Comment by ankhers** [comment]
@gleber There appears to be a conflict with the code owners file. If you fix that, I can run nox on my mac.

**Comment by gleber** [comment]
@ankhers Rebased onto 90b3d2d, now it merges. Please take a look

**Comment by gleber** [comment]
On Linux with sandboxed builds:

$ git log -n 6 --oneline

c041770 Add gleber to CODEOWNERs of beam-related packages.
52f8bec hex2nix: 0.0.5 -> 0.0.6
b8adacf relx-exe: 3.18.0 -> 3.23.1
c806641 pc: 1.2.0 -> 1.6.0
adbc1ed rebar3: 3.3.2 -> 3.4.3
90b3d2d qtox: drop gtk2 dependency

$ nix-shell -p nox --run "nox-review wip --against 90b3d2d"

==> We're in a git repo, trying to fetch it
Building in /tmp/gleber/nox-review-zvt88czh: hexRegistrySnapshot lfe rebar3 rebar3-open hex2nix relxExe
... [snip] ...
Result in /tmp/gleber/nox-review-zvt88czh
total 0
lrwxrwxrwx 1 gleber gleber 56 Sep 11 23:07 result -> /nix/store/6z1389kpniviix3z9qshkvvh6kx6jq87-hex-registry
lrwxrwxrwx 1 gleber gleber 53 Sep 11 23:07 result-2 -> /nix/store/6br5zdw59cf31jjnx4c55yldfa0p353c-lfe-1.2.1
lrwxrwxrwx 1 gleber gleber 56 Sep 11 23:07 result-3 -> /nix/store/v17rfryiaiw50jxl5v3fqqab8c990ib0-rebar3-3.4.3
lrwxrwxrwx 1 gleber gleber 56 Sep 11 23:07 result-4 -> /nix/store/j4xv8qr5pqmxbws8jx1pxl7d1kyckx83-rebar3-3.4.3
lrwxrwxrwx 1 gleber gleber 57 Sep 11 23:07 result-5 -> /nix/store/rqrc51l49sxigddjnnxnszv97sp21qpq-hex2nix-0.0.6
lrwxrwxrwx 1 gleber gleber 59 Sep 11 23:07 result-6 -> /nix/store/6xcsvpi5w50z0cnrvr0p65q6yq9shgwi-relx-exe-3.23.1

**Comment by gleber** [comment]
Also builds on NixOS

**Comment by ankhers** [comment]
Nox just finished and it builds on MacOS.

**Comment by Mic92** [comment]
Thanks!

**Pull request merged**
