### PR TITLE
python310Packages.httpie: re-enable tests

### PR DESCRIPTION
**Pull request by alexshpilkin**
###### Description of changes

An upstream fix for the test failures discovered in https://github.com/NixOS/nixpkgs/pull/205270 has landed as https://github.com/httpie/httpie/commit/e73c3e6c249b89496b4f81fa20bb449911da79f1, so pick up that patch until the next version is released and revert https://github.com/NixOS/nixpkgs/pull/207035 which disabled the tests.

h/t @dbaynard @mweinelt 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 210996` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python311Packages.httpie</li>
    <li>python311Packages.httpie-ntlm</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>http-prompt</li>
    <li>httpie (python310Packages.httpie)</li>
    <li>python310Packages.httpie-ntlm</li>
  </ul>
</details>

**Comment by alexshpilkin** [comment]
@fabaff Huh. Thanks! I did `nixpkgs-review rev` locally but that didn’t catch it—perhaps because at the point I based this on (https://github.com/NixOS/nixpkgs/commit/a4379d2b0deefedc8dba360897557707ea9ee9a7) a dependency of `httpie` (`multidict`) did not build either? I’ll look into it.

**Comment by alexshpilkin** [comment]
Right, so `python311Packages.ephemeral-port-reserve` doesn’t even build (or more precisely fails tests) on current `nixpkgs-unstable`, it only works only on `master`. And yes, this looks like independent 3.11-induced breakage. The first four failures (in `test_cli.py` and `test_output.py`) I think are due to the [changes to `enum.Enum.__format__`][1]; the one in `test_plugins_cli.py` is a genuine failure I’m not sure about; the final three in `test_sessions.py` are because the cookies in the mock response aren’t ordered the way the test expects (?).

Should I just disable these on ≥ 3.11 and let upstream sort it out? FWIW, the prerequisites on 3.12 seem quite broken for now.

[1]: https://docs.python.org/3/whatsnew/3.11.html#enum

**Comment by NickCao** [comment]
No longer relevant.

**Pull request closed without merging**
