### PR TITLE
 cairo-lang: init at 2.0.0

### PR DESCRIPTION
**Pull request by samoht9277**
###### Description of changes

Custom [cairo-lang](https://cairo-by-example.com/) installer for @LambdaClass.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by figsoda** [comment]
is this different from #236447?

**Comment by samoht9277** [comment]
@figsoda, yes.

First of all, the build version is the actual one, also when checking [#236447](https://github.com/NixOS/nixpkgs/pull/236447), it doesn't seem to compile the actual language. This version compiles from source with the latest version.

We even tried to run [#236447](https://github.com/NixOS/nixpkgs/pull/236447), but it doesn't even work. Should we update that package with the correspondent build instructions, or shall we proceed to continue on this package?

**Comment by figsoda** [comment]
> First of all, the build version is the actual one, also when checking [#236447](https://github.com/NixOS/nixpkgs/pull/236447), it doesn't seem to compile the actual language. This version compiles from source with the latest version.

Could you elaborate on that? What exactly is missing?

> We even tried to run [#236447](https://github.com/NixOS/nixpkgs/pull/236447), but it doesn't even work.

What did you try to do? What command did you run?

> Should we update that package with the correspondent build instructions, or shall we proceed to continue on this package?

If there is something wrong with the existing package, it should be updated. The current PR doesn't actually add package (to `top-level/all-packages.nix`) and has a few other issues. I want to sort out what is the issue with the existing package before more thoroughly reviewing this pull request.

**Comment by figsoda** [comment]
cc @RaitoBezarius as the author of #236447

**Comment by RaitoBezarius** [comment]
I'm not so sure about including RC compilers without any good reason.
1.1.0 is a released version of the compiler and I confirmed I can compile actual Cairo programs with it, you will have to provide more information.

The packaging of this software is not on par with the rest of Rust programs, please take a look to other Rust programs or how I did the packaging, you have to follow the packaging style in nixpkgs.

**Comment by samoht9277** [comment]
> Could you elaborate on that? What exactly is missing?

The .nix file seems like it pulls from GitHub the precompiled (v1.1.0) version. Then, it starts to compile out of nowhere, then it runs some tests, and finishes by giving an error while testing. 

> What did you try to do? What command did you run?

`nix-shell -p cairo-lang` to create a nix-shell instance with all the cairo tools. While runnning the command, this error came up. _running on: macOS 13.4 with M1, nix-shell (Nix) 2.16.1_
```
error: test failed, to rerun pass `-p cairo-lang-runner --lib`

Caused by:
  process didn't exit successfully: `/private/tmp/nix-build-cairo-1.1.0.drv-0/source/target/aarch64-apple-darwin/release/deps/cairo_lang_runner-57610ad6599a3fd9 --test-threads=8 '--skip=golden_test::sourcegen_ast'` (signal: 11, SIGSEGV: invalid memory reference)
error: builder for '/nix/store/9gf3y5wlwpszwxgjr23n20r4mjv42icz-cairo-1.1.0.drv' failed with exit code 101;
       last 10 log lines:
       >
       > test result: ok(B. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
       >
       >      Running unittests src/lib.rs (target/aarch64-apple-darwin/release/deps/cairo_lang_runner-57610ad6599a3fd9)
       >
       > running 8 tests
       > error: test failed, to rerun pass `-p cairo-lang-runner --lib`
       >
       > Caused by:
       >   process didn't exit successfully: `/private/tmp/nix-build-cairo-1.1.0.drv-0/source/target/aarch64-apple-darwin/release/deps/cairo_lang_runner-57610ad6599a3fd9 --test-threads=8 '--skip=golden_test::sourcegen_ast'` (signal: 11, SIGSEGV: invalid memory reference) or maybe there is a form to manually select the version you want? As you may notice, I started using nix not so long ago.
```
---  
### proposed solution
I would like to have the release candidate version of `cairo`. Maybe we can have two versions, and I maintain the RC one. I can rename the package version to `cairo-lang-rc` (and add it to `all-packages.nix`). Or maybe there is a way to specify the version you want (?). As you may notice, i started using nix not so long ago, so the process is a bit confusing to me, please let me know what should I do.

**Comment by RaitoBezarius** [comment]
> > Could you elaborate on that? What exactly is missing?
> 
> The .nix file seems like it pulls from GitHub the precompiled (v1.1.0) version. Then, it starts to compile out of nowhere, then it runs some tests, and finishes by giving an error while testing

It doesn't pull a precompiled version... It compiles from source.

> 
> > What did you try to do? What command did you run?
> 
> `nix-shell -p cairo-lang` to create a nix-shell instance with all the cairo tools. While runnning the command, this error came up. _running on: macOS 13.4 with M1, nix-shell (Nix) 2.16.1_
> 
> ```
> error: test failed, to rerun pass `-p cairo-lang-runner --lib`
> 
> Caused by:
>   process didn't exit successfully: `/private/tmp/nix-build-cairo-1.1.0.drv-0/source/target/aarch64-apple-darwin/release/deps/cairo_lang_runner-57610ad6599a3fd9 --test-threads=8 '--skip=golden_test::sourcegen_ast'` (signal: 11, SIGSEGV: invalid memory reference)
> error: builder for '/nix/store/9gf3y5wlwpszwxgjr23n20r4mjv42icz-cairo-1.1.0.drv' failed with exit code 101;
>        last 10 log lines:
>        >
>        > test result: ok(B. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
>        >
>        >      Running unittests src/lib.rs (target/aarch64-apple-darwin/release/deps/cairo_lang_runner-57610ad6599a3fd9)
>        >
>        > running 8 tests
>        > error: test failed, to rerun pass `-p cairo-lang-runner --lib`
>        >
>        > Caused by:
>        >   process didn't exit successfully: `/private/tmp/nix-build-cairo-1.1.0.drv-0/source/target/aarch64-apple-darwin/release/deps/cairo_lang_runner-57610ad6599a3fd9 --test-threads=8 '--skip=golden_test::sourcegen_ast'` (signal: 11, SIGSEGV: invalid memory reference) or maybe there is a form to manually select the version you want? As you may notice, I started using nix not so long ago.
> ```

Yes macOS has problems with the test suite, figuring out this is open to Darwin maintainers of that package, I don't run Darwin, the easy fix is to disable that particular test for Darwin and the hard fix is to figure out.

> 
> ### proposed solution
> I would like to have the release candidate version of `cairo`. Maybe we can have two versions, and I maintain the RC one. I can rename the package version to `cairo-lang-rc` (and add it to `all-packages.nix`). Or maybe there is a way to specify the version you want (?). As you may notice, i started using nix not so long ago, so the process is a bit confusing to me, please let me know what should I do.

I don't think you need the RC version in nixpkgs, you haven't explained why this is needed at all, you can just have it locally or in your projects, even by overriding the original expression.

**Comment by wegank** [comment]
Closed by #242447.

**Pull request closed without merging**
