### PR TITLE
ckb-next: 0.3.2 -> 0.4.2

### PR DESCRIPTION
**Pull request by kierdavis**
###### Motivation for this change

Requested by a user.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after) - *increase by 0.068%*
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kierdavis** [comment]
Tested that this compiles and boots without error, and successfully detects my Corsair keyboard (Strafe) and mouse (Sabre RGB).

**Comment by kierdavis** [comment]
Note that I hope to push these patches upstream at some point.

**Comment by mmahut** [comment]
@GrahamcOfBorg build ckb-next

**Comment by kierdavis** [comment]
Updated from 0.4.0 to 0.4.1.

**Comment by mmahut** [comment]
@GrahamcOfBorg build ckb-next

**Comment by Ekleog** [comment]
(triage) @kierdavis Looks like there's been another merge conflict since @mmahut ran the ofborg build :/

**Comment by kierdavis** [comment]
Rebased and updated to latest version 0.4.2, please review

**Review by Br1ght0ne — APPROVED** [review]
diff LGTM
executable runs, shows GUI

```
[4 built, 230 copied (889.7 MiB), 193.3 MiB DL]
https://github.com/NixOS/nixpkgs/pull/60262
1 package built:
ckb-next
```

**Comment by Ekleog** [comment]
Looks pretty good, thanks!

**Pull request merged**
