### PR TITLE
[Backport release 23.11] searxng 2023-10-31 -> 2024-03-08; uwsgi 2.0.23 -> 2.0.24

### LINKED ISSUE #301912: nixos-23.11 ships with searxng version that hits bug with current firefox stable
### Describe the bug
The upstream bug https://github.com/searxng/searxng/issues/3227 was fixed a while ago and is also fixed in unstable, however not in stable.
This means that current Firefox versions cannot add a self-hosted searx instance to search engines from the Firefox UI.

### Steps To Reproduce
1. install searx with the current defaults
2. try to add the search to Firefox by right-clicking the address bar and going "add [name of instance"

### Expected behavior
Search engine is added.

### Screenshots
See upstream issue.

### Additional context
At the time this was fixed upstream the affected Firefox version was a beta as far as I can tell.
There have been [several updates to the package](https://github.com/NixOS/nixpkgs/commits/nixos-unstable/pkgs/by-name/se/searxng/package.nix) since, however none of them backported to stable.

My current workaround, pulling the required packages from *nixpkgs-unstable*:

```nix
# FIXME: https://github.com/searxng/searxng/issues/3227
searx.package = nixpkgs-unstable.legacyPackages.${config.nixpkgs.system}.searxng;
# you can drop the following if you add `.override { inherit (pkgs) python3; }` to the line above
# you either have the option to use the verbatim searxng package from unstable (which requires you to match the uwsgi package) or to rebuild the searxng unstable package for the current stable python version (this causes rebuilds, however they're "just" python packages, use your own judgement)
uwsgi.package = lib.mkForce (nixpkgs-unstable.legacyPackages.${config.nixpkgs.system}.uwsgi.override
{
  plugins = lib.unique config.services.uwsgi.plugins;
});
```

With the upcoming NixOS 24.05 release I personally don't mind waiting, so I'm contempt with the above workaround for myself, I just wanted to create an issue for this so others can find it and use the workaround if needed (though it's not exactly super reusable anyway).
IMHO: feel free to Won't Fix this.

### Notify maintainers

- @999eagle
- @SuperSandro2000

### Metadata

```console
% nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.73, NixOS, 23.11 (Tapir), 23.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/9fpv0kjq9a80isa1wkkvrdqsh9dpcn05-source`
```

(nixpkgs being 1487bdea619e4a7a53a4590c475deabb5a9d1bfb)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by JohnRTitor**
## Description of changes
Backport
searxng: 2023-10-31 -> 2024-03-08
uwsgi: 2.0.23 -> 2.0.24

Backport needed due to [upstream bug](https://github.com/searxng/searxng/issues/3227)
Closes #301912 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Do we really need the uwsgi backport?

**Comment by JohnRTitor** [comment]
@benaryorg can answer that, I added it as per the issue description.

**Review by 999eagle — APPROVED** [review]
I haven't tested this but the changes look good. While I don't think backporting the `uwsgi` update is strictly necessary it doesn't hurt either.

**Comment by benaryorg** [comment]
> @benaryorg can answer that, I added it as per the issue description.

I only included it in the workaround because otherwise the dependencies didn't align (i.e. `no python application found`) and an override would've caused package rebuilds.
Using `unstable.pkgs.searxng.override { inherit (pkgs) python3; }` seems to work nicely, so the *uwsgi* bump shouldn't be required, although as mentioned by others it probably wouldn't hurt, it being a [bugfix release with a reasonable changelog](https://uwsgi-docs.readthedocs.io/en/latest/Changelog-2.0.24.html), but that'd be one for the maintainers to decide IMHO.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by rnhmjoj** [comment]
@grahamcOfBorg test searx

**Review by rnhmjoj — APPROVED** [review]

**Pull request merged**
