### PR TITLE
golangci-lint: 1.9.2 -> 1.16.0

### PR DESCRIPTION
**Pull request by anpryl**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by aneeshusa** [comment]
v1.16.0 was [released a week ago](https://github.com/golangci/golangci-lint/releases/tag/v1.16.0) and pulls in almost 2 months of additional fixes (v1.15.0 was released Feb 18). Could you bump this to the latest?

**Comment by aneeshusa** [comment]
It would also be nice to try to use the [new `buildGoModule`](https://kalbas.it/2019/03/17/announcing-the-new-golang-infrastructure-buildgomodule/) support in nixpkgs.

**Comment by anpryl** [comment]
Ok, don't merge this please, I will update PR soon

**Comment by anpryl** [comment]
Updated to latest version using buildGoModule, can be merged now.

**Comment by kalbasit** [comment]
Getting an error building this locally:

```
$ nix build --no-link --keep-going --max-jobs 8 --option build-use-sandbox true -f /yl/.cache/nix-review/pr-58336/build.nix
hash mismatch in fixed-output derivation '/nix/store/xf54c6fwph4dip4mjqljnpj6mhbp0456-source':
  wanted: sha256:0jq434hq56xb7r7pdjykxx8jxr107djzk24dwzhjs9ynqfdv9k4v
  got:    sha256:1yzcfmrxyrxhq3vx13qm7czvhvdnaqay75v8ry1lgpg0bnh9pakx
cannot build derivation '/nix/store/r94y9l6wd5vaycfnng3xyj6si38nm5jj-golangci-lint-1.16.0-go-modules.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/vg5k969mrxy4c83hg8bw5fxjdwbkalaf-golangci-lint-1.16.0.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/yprpzx5z6l9zk1ici9jmshk8wccm2px9-env.drv': 1 dependencies couldn't be built
[0 built (1 failed), 13 copied (6.1 MiB), 1.5 MiB DL]
error: build of '/nix/store/yprpzx5z6l9zk1ici9jmshk8wccm2px9-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/58336
1 package failed to build:
golangci-lint
```

@GrahamcOfBorg build golangci-lint

**Comment by anpryl** [comment]
@GrahamcOfBorg build golangci-lint

**Comment by anpryl** [comment]
> Getting an error building this locally:
> 
> ```
> $ nix build --no-link --keep-going --max-jobs 8 --option build-use-sandbox true -f /yl/.cache/nix-review/pr-58336/build.nix
> hash mismatch in fixed-output derivation '/nix/store/xf54c6fwph4dip4mjqljnpj6mhbp0456-source':
>   wanted: sha256:0jq434hq56xb7r7pdjykxx8jxr107djzk24dwzhjs9ynqfdv9k4v
>   got:    sha256:1yzcfmrxyrxhq3vx13qm7czvhvdnaqay75v8ry1lgpg0bnh9pakx
> cannot build derivation '/nix/store/r94y9l6wd5vaycfnng3xyj6si38nm5jj-golangci-lint-1.16.0-go-modules.drv': 1 dependencies couldn't be built
> cannot build derivation '/nix/store/vg5k969mrxy4c83hg8bw5fxjdwbkalaf-golangci-lint-1.16.0.drv': 2 dependencies couldn't be built
> cannot build derivation '/nix/store/yprpzx5z6l9zk1ici9jmshk8wccm2px9-env.drv': 1 dependencies couldn't be built
> [0 built (1 failed), 13 copied (6.1 MiB), 1.5 MiB DL]
> error: build of '/nix/store/yprpzx5z6l9zk1ici9jmshk8wccm2px9-env.drv' failed
> https://github.com/NixOS/nixpkgs/pull/58336
> 1 package failed to build:
> golangci-lint
> ```
> 
> @GrahamcOfBorg build golangci-lint

Very strange behavior. Locally it was fine. Updated to latest nix.

**Comment by kalbasit** [comment]
Let's try again. @GrahamcOfBorg build golangci-lint

**Comment by kalbasit** [comment]
@GrahamcOfBorg build golangci-lint

**Review by kalbasit — CHANGES_REQUESTED** [review]
please squash 40f4e1f3611bb39d649d5d6c39f87c16681394e7 into ac0add6d7b4115c4605ad922c3f04d8afaecd997.

**Comment by kalbasit** [comment]
I believe I know why the hash did not work before, and now it does. Go 1.12 seems to have added a new empty file with the mods and it's changing the hash :( We should update existing packages that are affected by the 1.12 update.

**Comment by anpryl** [comment]
> please squash [40f4e1f](https://github.com/NixOS/nixpkgs/commit/40f4e1f3611bb39d649d5d6c39f87c16681394e7) into [ac0add6](https://github.com/NixOS/nixpkgs/commit/ac0add6d7b4115c4605ad922c3f04d8afaecd997).

Done

**Comment by kalbasit** [comment]
@GrahamcOfBorg build golangci-lint

**Comment by anpryl** [comment]
@kalbasit ping

**Comment by kalbasit** [comment]
@GrahamcOfBorg build golangci-lint

**Comment by kalbasit** [comment]
I'm not sure why it's failing on Darwin, but it's working on my side.

**Review by kalbasit — APPROVED** [review]

**Pull request merged**
