### PR TITLE
vapoursynth: fix darwin build

### PR DESCRIPTION
**Pull request by viraptor**
###### Description of changes

The build is fixed, and the binary starts up, but I don't really know how to test this further.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rnhmjoj** [comment]
There are a few applications that you can try that use vapoursynth. Try running vapoursynth-editor, maybe.

**Comment by viraptor** [comment]
@rnhmjoj Unfortunately `vapoursynth-editor` has its own issues to solve. I tried the basic script from vapoursynth documentation using `nix-shell -I nixpkgs=. -p vapoursynth -p ffms` and a trivial script, but get:

```
$ vspipe -c y4m foo.vpy - > /tmp/res
Script evaluation failed:
Python exception: No attribute with the name ffms2 exists. Did you mistype a plugin namespace?

Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 2890, in vapoursynth._vpy_evaluate
  File "src/cython/vapoursynth.pyx", line 2891, in vapoursynth._vpy_evaluate
  File "foo.vpy", line 2, in <module>
    video = core.ffms2.Source(source='sample.mkv')
  File "src/cython/vapoursynth.pyx", line 2438, in vapoursynth._CoreProxy.__getattr__
  File "src/cython/vapoursynth.pyx", line 2280, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name ffms2 exists. Did you mistype a plugin namespace?
```

Am I trying something silly?

**Comment by viraptor** [comment]
@rnhmjoj oh, is this good enough?

```
from vapoursynth import core
print("---")
print(core.version())
print("---")
```

```
$ vspipe foo.vpy -
---
VapourSynth Video Processing Library
Copyright (c) 2012-2022 Fredrik Mellbin
Core R59
API R4.0
API R3.6
Options: -

---
Failed to retrieve output node. Invalid index specified?
```

**Comment by rnhmjoj** [comment]
> @rnhmjoj oh, is this good enough?

Well, at least the core library is working.
You can try to see if the plugins machinery works by building something like this:
```
(vapoursynth.withPlugins [ ffms ])
```

If the editor is broken you can also try mpv, I guess it should be working on darwin.
Try this overlay:
```
(self: super: {
  mpv-unwrapped = super.mpv-unwrapped.override {
    vapoursynthSupport = true;
    vapoursynth = with self; vapoursynth.withPlugins
      [ vapoursynth-mvtools ffms ];
  };
})
```
You can then try a filter like [this one](https://gist.github.com/phiresky/4bfcfbbd05b3c2ed8645).

**Comment by viraptor** [comment]
This whole thing became a "I can make it compile, but it's actually broken". So with vapoursynth itself compiling:

```
nix-shell -I nixpkgs=. -p '(vapoursynth.withPlugins [ffms])'
```

results in failures about unavailable patchelf since it wasn't explicitly declared and came with the environment.
Making that explicit and the patchelf blocks disabled on macos, I get:

```
Builder called die: Cannot wrap '/nix/store/3n61iziy913km8jwiv6zw90kajfknycy-vapoursynth-59-with-plugins/bin/.vspipe-wrapped' because it is not an executable file
```

But that requires tracing a few issues. I think I'll give up at this point and let someone continue the fixing in the future.
Happy to help testing.

**Pull request closed without merging**
