### PR TITLE
 pythonPackages.sepaxml: 2.0.0 -> 2.1.0

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
Noticed it was out of date. Also, enabled tests.

More work than I was expecting.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @elohmeier 

```
$ nix build --no-link --keep-going --max-jobs 8 --option build-use-sandbox true -f /home/jon/.cache/nix-review/pr-65750-2/build.nix
https://github.com/NixOS/nixpkgs/pull/65750
6 package were build:
python27Packages.elementpath python27Packages.xmlschema python37Packages.elementpath python37Packages.fints python37Packages.sepaxml python37Packages.xmlschema
```

### CODE REVIEW

**Comment by jonringer** [comment]
Upstreamed fints version bounds here https://github.com/raphaelm/python-fints/pull/88

**Comment by jonringer** [comment]
@GrahamcOfBorg build python3Packages.xmlschema python3Packages.elementpath python3Packages.sepaxml python3Packages.fints

**Comment by elohmeier** [comment]
Looks good to me, thanks @jonringer !

**Comment by risicle** [comment]
On macos 10.13 `xmlschema`'s automatic check to disable "remote tests" fails to detect the lack of network access and `test_remote_schemas_loading` fails.

You can either add this test to the `-k 'not ...'` clause or add to `checkPhase`:

```
substituteInPlace xmlschema/tests/__init__.py --replace "SKIP_REMOTE_TESTS = " "SKIP_REMOTE_TESTS = True #"
```

Not sure which is more likely to prove robust.

**Comment by jonringer** [comment]
Interesting, I wonder if this is from the macos environment being impure, so it's able to touch network and do the network calls. Because the logic seems sound. I'll change it, don't worry :)

**Comment by risicle** [comment]
It's something along those lines, yes.

**Comment by jonringer** [comment]
@risicle can you retry macos, it was able to build for me :)

**Review by risicle — APPROVED** [review]
WFM now.

**Pull request merged**
