### PR TITLE
linux_6_1, linux_6_3, linux_6_4: update stable kernels

### PR DESCRIPTION
**Pull request by RaitoBezarius**
###### Description of changes

    linux_6_4: 6.4 -> 6.4.1
    
    https://lwn.net/Articles/937080/

    linux_6_3: 6.3.10 -> 6.3.11
    
    https://lwn.net/Articles/937081/

    linux_6_1: 6.1.36 -> 6.1.37
    
    https://lwn.net/Articles/937082/

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
(untested yet, I don't have fast Internet alas.)

**Review by Ma27 — APPROVED** [review]

**Comment by K900** [comment]
We usually push kernel updates directly to master despite the rebuild count, FWIW.

**Comment by Ma27** [comment]
Welp I really missed the target branch (and didn't have to build that much, so it wasn't obvious there either) :facepalm: 

Not sure about the current cycle, but if it's not on master at the next update, I'd forward-port.

**Comment by RaitoBezarius** [comment]
Yeah, apologies for that. I can resubmit it on master if needed.

Le lun. 3 juil. 2023 à 14:07, Maximilian Bosch ***@***.***> a
écrit :

**Comment by fabianhjr** [comment]
The resubmit would be great since there is a chance another update would land on the main branch (eg, 6.4.2) and cause a conflict between staging and the main branch.

**Comment by Ma27** [comment]
Done in #241655.

**Pull request merged**
