### PR TITLE
ruby: init at 2.4.4

### PR DESCRIPTION
**Pull request by drzln**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gador** [comment]
The build fails for me for ruby-2.4.4

Log:
```
nix log /nix/store/9m4qr72m3f6wxgks7ysch01af0ad4blh-ruby-2.4.4.drv
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/sy6dr7xxmfrss0l4ylz1xf9wpscrafk0-ruby-2.4.4.tar.gz
source root is ruby-2.4.4
setting SOURCE_DATE_EPOCH to timestamp 1522246441 of file ruby-2.4.4/gems/xmlrpc-0.2.1/xmlrpc.gemspec
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/w7yayg65p8vvi97a2952bpvq7rfwnszp-do-not-regenerate-revision.h.patch
patching file defs/gmake.mk
Hunk #1 FAILED at 325.
1 out of 1 hunk FAILED -- saving rejects to file defs/gmake.mk.rej
```

**Comment by pennae** [comment]
it's probably not a good idea to add an outdated release of a ruby version that has been EOL for years?

**Review by viraptor — CHANGES_REQUESTED** [review]
Ruby 2.4 is already EOL (https://endoflife.software/programming-languages/server-side-scripting/ruby#2-4)
This doesn't look like it should be included at all

**Comment by marsam** [comment]
Ruby 2.4 is already EOL

**Pull request closed without merging**
