### PR TITLE
multimc: add Microsoft account support

### PR DESCRIPTION
**Pull request by leo60228**
###### Motivation for this change
Microsoft/Mojang has been progressively pushing people towards using Microsoft accounts instead of Mojang accounts for logging in. MultiMC's source does not contain the necessary OAuth client ID, so I registered a "MC on NixOS" application:
permissions request

The MultiMC source code contains warnings about making the client ID public. From my reading of Microsoft's documentation, I don't believe that this is an issue, but since I registered the application it'd be my problem (and not the NixOS project or MultiMC's).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by starcraft66** [comment]
I think that the Client ID should not be hardcoded. Ideally, MultiMC's derivation would need an argument allowing one to specify their own client ID and have it compiled into the package. If there were to be an "official" client ID for this package, I'd like to reach out to the NixOS foundation and see if they are interested in managing this sort of thing instead of having a client id owned by an individual. Besides, I also think that this whole client id obfuscation charade is ridiculous at best, we could trivially obtain the official MultiMC client ID and use it in this package and there's nothing stopping us technically.

**Comment by Forkk** [comment]
> I think that the Client ID should not be hardcoded. Ideally, MultiMC's derivation would need an argument allowing one to specify their own client ID and have it compiled into the package. If there were to be an "official" client ID for this package, I'd like to reach out to the NixOS foundation and see if they are interested in managing this sort of thing instead of having a client id owned by an individual.

This is the best approach. Please do this.


> Besides, I also think that this whole client id obfuscation charade is ridiculous at best, we could trivially obtain the official MultiMC client ID and use it in this package and there's nothing stopping us technically. The OAuth client ID is certainly not "confidential" as the author claims it is in their repo (as opposed to an OAuth Client Secret for "confidential" OAuth clients for example), this is simply an intimidatory tactic

According to Microsoft's [identity platform terms of use](https://docs.microsoft.com/en-us/legal/microsoft-identity-platform/terms-of-use), the client ID absolutely is confidential and will be blocked if misused:

> ... Microsoft will also assign your Application an “Application ID”. Your Application ID is confidential, and You are required to keep your Application ID secure. Microsoft may reassign Application IDs in Microsoft's sole discretion.

I understand that this is very difficult to accomplish in desktop software, but we have no choice other than to make a best effort attempt to keep the client ID confidential, so I have to ask you to *please* not make the client ID from official builds of MultiMC publicly available. If someone is going to use it outside the official builds, it ought to at least be non-trivial.

As for Nix's own client ID, if you go the route of having the Nix foundation manage their own, you're free to interpret Microsoft's ToS differently and keep said ID confidential or not based on your own interpretation of it, but I'd ask that you respect our interpretation of it, and not leak our own ID.

On a somewhat unrelated note, I'd also like to clarify that MSA is *not* OAuth. It is a bastardized version of OAuth, so some things that apply to OAuth are not the same in this case. I really wish it were OAuth, or that we could just keep using the old authentication system, but we are subject to the whims of Microsoft, and they have decided to implement this stupid new system, so we must do as they say.

**Comment by leo60228** [comment]
@starcraft66 Done.

**Comment by starcraft66** [comment]
@leo60228 I'm unable to get your changes to work.

I ran `nix-build --argstr msaClientID <some client id> -A multimc https://github.com/leo60228/nixpkgs/archive/refs/heads/mmc-microsoft.tar.gz`, then `./result/bin/multimc` and the button to add a Mojang account is greyed out. Could you double-check? I'm fairly certain my command should build the derivation properly. I also made sure to kill any previously running multimc.

**Comment by leo60228** [comment]
Hmm... I won't be able to test the final binary for a few hours, but I tested the build in `nix-shell` and the code after `patchPhase` was pretty much the same as the original PR, which I did test.

**Comment by leo60228** [comment]
The issue ended up being pretty simple... it's an argument to `multimc`, not Nixpkgs itself. Running `nix-build -E '(import (builtins.fetchTarball https://github.com/leo60228/nixpkgs/archive/refs/heads/mmc-microsoft.tar.gz) {}).multimc.override { msaClientID = "<some client id>"; }'` works.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by starcraft66** [comment]
> The issue ended up being pretty simple... it's an argument to multimc, not Nixpkgs itself.

D'oh! I don't frequently build packages that require argument overrides so I had a brain fart there, thanks for finding the proper command.

**Review by starcraft66 — APPROVED** [review]
Tested. LGTM.

**Comment by alx-alexpark** [comment]
Merge

**Comment by Artturin** [comment]
Drop this
[`2b87405` (#137147)](https://github.com/NixOS/nixpkgs/pull/137147/commits/2b874053a4a9d525c3fc868b5162086bc7c472cb)
and the patch deletion in [`88daaed` (#137147)](https://github.com/NixOS/nixpkgs/pull/137147/commits/88daaed0928f021068749ad60bba0c5cec712d29)

**Comment by Artturin** [comment]
Made a wiki page https://nixos.wiki/wiki/Multimc

**Comment by leo60228** [comment]
@Arturin Done.

**Comment by leo60228** [comment]
Oops, I meant @Artturin.

**Pull request merged**
