### PR TITLE
[WIP] systemd: 247.6 -> 249.4

### PR DESCRIPTION
**Pull request by kwohlfahrt**
###### Motivation for this change

systemd-248 introduces support for TPM-backed LUKS volumes. I want to experiment with this, so tried to bump the systemd version. So far, this fixes some build issues, but many systemd-related tests hang, waiting for the machine to come up (e.g. `systemd-analyze.nix`).

I'm currently debugging this, but thought I'd post the work on building systemd so far, in case anybody happens to be working on this they can use my build fixes.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kwohlfahrt** [comment]
Some tests, like `nixos/tests/systemd.nix` do complete.

**Comment by andir** [comment]
Perhaps you want to look at #131618 instead.

**Comment by kwohlfahrt** [comment]
I thought I'd searched for open PRs before starting this, but must have missed that. Thanks for the pointer!

**Comment by vcunat** [comment]
Well, that PR has been _closed_ for two days.

**Pull request closed without merging**
