### PR TITLE
jellyfin: 10.9.11 -> 10.10.0

### LINKED ISSUE #351607: Update request: Jellyfin 10.9.11 → 10.10.0
- Package name: Jellyfin
- Latest released version: [10.10.0](https://github.com/jellyfin/jellyfin/releases/tag/v10.10.0)

- Current version on the unstable channel: 10.9.11
- Current version on the stable/release channel: 10.9.11

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@nyanloutre @minijackson @purcell @jojosch 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dotlambda**
https://jellyfin.org/posts/jellyfin-release-10.10.0

fixes https://github.com/NixOS/nixpkgs/issues/351607
cc @Titaniumtown @justinas @justinkb

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by justinkb** [comment]
looks good, I came to basically the same changes, except I didn't do your nice sha revision thing. is this gonna be backported to 24.05, for reference?

**Comment by Titaniumtown** [comment]
For me, it's getting stuck at "Installing dependencies", I've been waiting 35 minutes lol
```shell
jellyfin-web> building '/nix/store/ssvd3blgnnf6ylpxvcf6j0ikzk41lyjd-jellyfin-web-10.10.0.drv'
jellyfin-web> Running phase: unpackPhase
jellyfin-web> unpacking source archive /nix/store/08bnd5lxc4x8rh08261ra49krcl31a50-source
jellyfin-web> source root is source
jellyfin-web> Running phase: patchPhase
jellyfin-web> Executing npmConfigHook
jellyfin-web> Configuring npm
jellyfin-web> Validating consistency between /build/source/package-lock.json and /nix/store/8sdn3lpmpwzh4gpixi0g5rinwqy6ls7q-jellyfin-web-10.10.0-npm-deps/package-lock.json
jellyfin-web> Fixing lockfile
Installing dependencies
```

**Comment by dotlambda** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 351966`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 9 packages built:</summary>
  <ul>
    <li>jellyfin</li>
    <li>jellyfin-ffmpeg</li>
    <li>jellyfin-ffmpeg.bin</li>
    <li>jellyfin-ffmpeg.data</li>
    <li>jellyfin-ffmpeg.dev</li>
    <li>jellyfin-ffmpeg.doc</li>
    <li>jellyfin-ffmpeg.lib</li>
    <li>jellyfin-ffmpeg.man</li>
    <li>jellyfin-web</li>
  </ul>
</details>

**Comment by purcell** [comment]
The failure on `x86_64-darwin` is new, right? I don't see any indication that BlurHashSharp doesn't support MacOS now, so it's confusing.

**Comment by dotlambda** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 351966`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 9 packages built:</summary>
  <ul>
    <li>jellyfin</li>
    <li>jellyfin-ffmpeg</li>
    <li>jellyfin-ffmpeg.bin</li>
    <li>jellyfin-ffmpeg.data</li>
    <li>jellyfin-ffmpeg.dev</li>
    <li>jellyfin-ffmpeg.doc</li>
    <li>jellyfin-ffmpeg.lib</li>
    <li>jellyfin-ffmpeg.man</li>
    <li>jellyfin-web</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>jellyfin</li>
    <li>jellyfin-web</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>jellyfin</li>
    <li>jellyfin-web</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>jellyfin</li>
    <li>jellyfin-web</li>
  </ul>
</details>

**Comment by Titaniumtown** [comment]
How are people able to get this to build? I can't get it to build at all :p

**Comment by K900** [comment]
Built and running fine on my aarch64 system.

**Comment by Titaniumtown** [comment]
Yea I think my nix store is messed up :p oh well.

**Comment by Titaniumtown** [comment]
Turns out my local build failure is due to a known kernel issue. Disregard my previous concern :P

**Comment by K900** [comment]
I'm going to merge later today if there are no objections.

**Comment by Myaats** [comment]
Did you ever build jellyfin-ffmpeg? Seems to fail building on hydra and locally when I tried with incompatible types errors.

Log: https://hydra.nixos.org/build/277152708/nixlog/2

**Comment by wrocketdev** [comment]
Can confirm, jellyfin-ffmpeg-7.0.2-5 no building.

```
       > libavcodec/libxeve.c: In function 'get_conf':
       > libavcodec/libxeve.c:199:27: error: incompatible types when assigning to type 'XEVE_RATIONAL' {aka 'struct _XEVE_RATIONAL'} from type 'long int'
       >   199 |         cdsc->param.fps = lrintf(av_q2d(avctx->framerate));
       >       |                           ^~~~~~
       > libavcodec/libxeve.c: In function 'libxeve_encode':
       > libavcodec/libxeve.c:484:40: error: incompatible types when assigning to type 'int' from type 'XEVE_RATIONAL' {aka 'struct _XEVE_RATIONAL'}
       >   484 |                 avpkt->time_base.den = xectx->cdsc.param.fps;
       >       |                                        ^~~~~
       > make: *** [ffbuild/common.mak:82: libavcodec/libxeve.o] Error 1
       > make: *** Waiting for unfinished jobs....
       For full logs, run 'nix log /nix/store/n9vd6qaiyzkyc8jf09ikr07k3vm9wxs2-jellyfin-ffmpeg-7.0.2-5.drv'.
error: 1 dependencies of derivation '/nix/store/s13zkd4ln6pppk3za5hvl7iq47zk77pq-jellyfin-10.10.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8qlyiriaqsblwya37zj2v4wwqccvbl5l-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hqxkyqzi3p8ippfgcwcdb45wzd6896r6-nixos-system-serveur-24.11.20241102.7ffd9ae.drv' failed to build
┏━ 1 Errors: 
 ⋮ 
┃        > CC   libavcodec/libxevd.o
┃        > CC   libavcodec/libxeve.o
┃        > CC   libavcodec/libxvid.o
┃        > libavcodec/libxeve.c: In function 'get_conf':
┃        > libavcodec/libxeve.c:199:27: error: incompatible types when assigning to type 'XEVE_RATIONAL' {aka 'struct _XEVE_RATIONAL'} from type 'long int'
┃        >   199 |         cdsc->param.fps = lrintf(av_q2d(avctx->framerate));
┃        >       |                           ^~~~~~
┃        > libavcodec/libxeve.c: In function 'libxeve_encode':
┃        > libavcodec/libxeve.c:484:40: error: incompatible types when assigning to type 'int' from type 'XEVE_RATIONAL' {aka 'struct _XEVE_RATIONAL'}
┃        >   484 |                 avpkt->time_base.den = xectx->cdsc.param.fps;
┃        >       |                                        ^~~~~
┃        > make: *** [ffbuild/common.mak:82: libavcodec/libxeve.o] Error 1
┃        > make: *** Waiting for unfinished jobs....
┃        For full logs, run 'nix log /nix/store/n9vd6qaiyzkyc8jf09ikr07k3vm9wxs2-jellyfin-ffmpeg-7.0.2-5.drv'.
```

**Comment by K900** [comment]
Seems like it may have been broken by the staging merge?

**Comment by justinas** [comment]
Fixed since? Seems to build (and is cached) at b7b476adbe59a511d906d5fd8c24e8d5a1bb3061 .

**Comment by WesfunOfficial** [comment]
looks like build is failing on my end
screenshot-2024-11-03-22-17-54

**Pull request merged**
