### PR TITLE
Update fcitx5 and its plugins

### PR DESCRIPTION
**Pull request by xrelkd**
###### Description of changes

https://groups.google.com/g/fcitx/c/BlKpFdz-Aes

https://github.com/fcitx/libime/compare/1.0.12...1.0.13
https://github.com/fcitx/fcitx5/compare/5.0.17...5.0.18
https://github.com/fcitx/fcitx5-chewing/compare/5.0.11...5.0.12
https://github.com/fcitx/fcitx5-chinese-addons/compare/5.0.13...5.0.14
https://github.com/fcitx/fcitx5-configtool/compare/5.0.13...5.0.14
https://github.com/fcitx/fcitx5-gtk/compare/5.0.15...5.0.16
https://github.com/fcitx/fcitx5-hangul/compare/5.0.9...5.0.10
https://github.com/fcitx/fcitx5-lua/compare/5.0.8...5.0.9
https://github.com/fcitx/fcitx5-m17n/compare/5.0.9...5.0.10
https://github.com/fcitx/fcitx5-rime/compare/5.0.13...5.0.14
https://github.com/fcitx/fcitx5-qt/compare/5.0.13...5.0.14
https://github.com/fcitx/fcitx5-table-extra/compare/5.0.10...5.0.11
https://github.com/fcitx/fcitx5-table-other/compare/5.0.9...5.0.10
https://github.com/fcitx/fcitx5-unikey/compare/5.0.10...5.0.11

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Closes #180495
Closes #180496
Closes #180497
Closes #180504
Closes #180505
Closes #180506
Closes #180522
Closes #180532
Closes #180542
Closes #180539

### CODE REVIEW

**Comment by Vonfry** [comment]
fcitx5-configtool fail to building on my machine. 
<detaisl> <summary>Here is the log.</summary>
  By not providing "FindKF5Plasma.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "KF5Plasma", but CMake did not find one.

  Could not find a package configuration file provided by "KF5Plasma" with
  any of the following names:

    KF5PlasmaConfig.cmake
    kf5plasma-config.cmake

  Add the installation prefix of "KF5Plasma" to CMAKE_PREFIX_PATH or set
  "KF5Plasma_DIR" to a directory containing one of the above files.  If
  "KF5Plasma" provides a separate development package or SDK, be sure it has
  been installed.

</details>

commit: 5569f0f2ebe6de5b5f60de9ec3c89a9b44aedf66
bulid command: `nix build --impure --expr 'with (builtins.getFlake (toString ./.)).legacyPackages.x86_64-linux; fcitx5-with-addons.override { addons = [ fcitx5-rime rime-data ]; }'`

**Comment by Vonfry** [comment]
After I rebase these commits to the newest master, it can be built successfully. 
I suggest to rebase it and let CI try to build it again.

**Comment by xrelkd** [comment]
@Vonfry Thanks for the review.
I have rebased these commits onto the latest master branch.
Please try it again.
Thank you!

**Review by Vonfry — APPROVED** [review]

**Comment by bobby285271** [comment]
@ofborg build libime

This fails for me with the same error reported in https://github.com/kpu/kenlm/issues/391. We probably want https://github.com/fcitx/libime/commit/2136d94b142267c9a5faf5ebeadff84214954e87, which is included in the next release.

**Comment by Vonfry** [comment]
Well, libime can not be built on my machine as well. It is better to include the new release in this pr.

**Comment by Vonfry** [comment]
I check the diff of configtool from 5.0.13 to 5.0.14. It adds two new dependencies: KF5IconThemes and KF5Plasma.

So they must be added in the buildInputs as well. @xddxdd 

<details><summary>A patch is here. You can use `git am` to apply and rebase.</summary>
From 32b756423cce78f82e0f2450a4daf1333a596a99 Mon Sep 17 00:00:00 2001
From: Vonfry <mail@vonfry.name>
Date: Mon, 11 Jul 2022 21:36:04 +0800
Subject: [PATCH] fcitx5-configtool: add new dependencies

---
 pkgs/tools/inputmethods/fcitx5/fcitx5-configtool.nix | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/pkgs/tools/inputmethods/fcitx5/fcitx5-configtool.nix b/pkgs/tools/inputmethods/fcitx5/fcitx5-configtool.nix
index ead6bc0bbc4..85ec938645f 100644
--- a/pkgs/tools/inputmethods/fcitx5/fcitx5-configtool.nix
+++ b/pkgs/tools/inputmethods/fcitx5/fcitx5-configtool.nix
@@ -14,6 +14,8 @@
 , xkeyboardconfig
 , libxkbfile
 , libXdmcp
+, plasma5Packages
+, plasma-framework
 , kcmSupport ? true
 }:
 
@@ -50,6 +52,8 @@ mkDerivation rec {
   ] ++ lib.optionals kcmSupport [
     kdeclarative
     kwidgetsaddons
+    plasma5Packages.kiconthemes
+    plasma-framework
   ];
 
   meta = with lib; {
-- 
2.36.0
</details>
You can add `Co-authored-by: Vonfry <mail@vonfry.name>`  into the last line of the commit message to mention me.

And you should update *libime* to *1.0.14* as well as discussions belew.

**Comment by xrelkd** [comment]
Hi, @Vonfry, thanks for the review, I just updated the branch again with your patch!

**Comment by Vonfry** [comment]
Please update [libime](https://github.com/fcitx/libime/commit/1adb14eb0617ef0eb0f07ad99684f43ca8a4395c) as well. 
There is a new release after you open the pr which fixes a build issue and this package is used by chinese-addons.

**Review by Vonfry — APPROVED** [review]
Thanks for your contributions!

Some checks:
- fcitx5-rime can input chinese 
- libime can be built with an tagged release.
- fcitx5-chinese-addons can input chinese

Notes:
We should use the tagged version of libime in the future when a new one is created instead of the unstable one.

CC: @bobby285271

**Comment by bobby285271** [comment]
Yeah looks like https://github.com/fcitx/libime/commit/1adb14eb0617ef0eb0f07ad99684f43ca8a4395c 1.0.14 hasn't tagged yet :-\

**Review by bobby285271 — APPROVED** [review]
Thanks!

**Pull request merged**
