### PR TITLE
freetype: makeWrapper doesn't cross compile to windows

### PR DESCRIPTION
**Pull request by Artturin**
Issue #120726

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by seanybaggins** [comment]
Curious if this actually works because of this comment...
https://github.com/NixOS/nixpkgs/issues/120726#issuecomment-1518984250

**Comment by seanybaggins** [comment]
It looks like in this PR they solved the same problem by conditionally removing makeWrapper if the hostPlatfrom was windows.
https://github.com/NixOS/nixpkgs/pull/229465

**Comment by seanybaggins** [comment]
Hey. I wish someone replied to my comments before this got merged. @Mindavi. Has this been tested on windows? I would rather have a package that fails to build for windows vs a package that builds for windows but doesn't function correctly.

**Comment by Mindavi** [comment]
They were addressed, but I didn't test this otherwise. Are you willing to test it?

**Comment by seanybaggins** [comment]
Oh okay I see. My bad. I can test on windows, but it might be a little til I get back on this :(

**Comment by Artturin** [comment]
> Hey. I wish someone replied to my comments before this got merged. @Mindavi. Has this been tested on windows? I would rather have a package that fails to build for windows vs a package that builds for windows but doesn't function correctly.

The only wrapped binary is the freetype-config in the dev output. -config binaries should be avoided because they break cross-compilation, instead pkg-config should be used.

**Comment by seanybaggins** [comment]
So I tried to build this for mingwW64 and I get an error for pkg-config.
```text
gslice.c: In function 'smc_notify_free':
gslice.c:1506:24: error: format '%u' expects argument of type 'unsigned int', but argument 4 has type 'size_t' {aka 'long long unsigned int'} [-Werror=format=]
 1506 |       fprintf (stderr, "GSlice: MemChecker: attempt to release non-allocated block: %p size=%" G_GSIZE_FORMAT "\n", pointer, size);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                               ~~~~
      |                                                                                                                              |
      |                                                                                                                              size_t {aka long long unsigned int}
In file included from gslice.c:22:
glibconfig.h:62:28: note: format string is defined here
   62 | #define G_GSIZE_FORMAT "I64u"
gslice.c:1511:24: error: format '%u' expects argument of type 'unsigned int', but argument 4 has type 'SmcVType' {aka 'long long unsigned int'} [-Werror=format=]
 1511 |       fprintf (stderr, "GSlice: MemChecker: attempt to release block with invalid size: %p size=%" G_GSIZE_FORMAT " invalid-size=%" G_GSIZE_FORMAT "\n", pointer, real_size, size);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                ~~~~~~~~~
      |                                                                                                                                                                   |
      |                                                                                                                                                                   SmcVType {aka long lo>
glibconfig.h:62:28: note: format string is defined here
   62 | #define G_GSIZE_FORMAT "I64u"
gslice.c:1511:24: error: format '%u' expects argument of type 'unsigned int', but argument 5 has type 'size_t' {aka 'long long unsigned int'} [-Werror=format=]
 1511 |       fprintf (stderr, "GSlice: MemChecker: attempt to release block with invalid size: %p size=%" G_GSIZE_FORMAT " invalid-size=%" G_GSIZE_FORMAT "\n", pointer, real_size, size);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                           ~~~~
      |                                                                                                                                                                              |
      |                                                                                                                                                                              size_t {ak>
glibconfig.h:62:28: note: format string is defined here
   62 | #define G_GSIZE_FORMAT "I64u"
gslice.c:1516:24: error: format '%u' expects argument of type 'unsigned int', but argument 4 has type 'size_t' {aka 'long long unsigned int'} [-Werror=format=]
 1516 |       fprintf (stderr, "GSlice: MemChecker: attempt to release non-allocated block: %p size=%" G_GSIZE_FORMAT "\n", pointer, size);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                               ~~~~
      |                                                                                                                              |
      |                                                                                                                              size_t {aka long long unsigned int}

```

**Comment by seanybaggins** [comment]
Okay interesting. If I try to build for pkgs.pkgsCross.mingw32. It works. If I try to build for pkgs.pkgsCross.mingwW64 it does not work.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/245775

**Pull request merged**
