### PR TITLE
archi: 5.2.0 -> 5.3.0

### PR DESCRIPTION
**Pull request by paumr**
## Description of changes

This PR was created based on: https://github.com/NixOS/nixpkgs/pull/302808

Additionally, to the automatically generated update this PR also fixes the download link.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by paumr** [comment]
looks like a test is failing, i'll look into it.

**Comment by pbsds** [comment]
please reorder the url changes to precede the version bump, or squash it

**Comment by paumr** [comment]
- I squashed the commits as requested
- I rebased this PR on the current master branch

**Comment by pbsds** [comment]
darwin builders ran out of space

@ofborg eval

**Comment by pbsds** [comment]
the associated nixos test on x86_64-linux is timing out, any ideas?

**Comment by paumr** [comment]
> the associated nixos test on x86_64-linux is timing out, any ideas?

Yes, tesseract seems to be unable to parse the welcome text, checkout https://github.com/NixOS/nixpkgs/issues/302965 for more information (it seems to be a race condition).

While the OCR check would be nice to have for this package, it's not strictly necessary. I documented the findings of my debugging session in the ticket. If this effects multiple packages (or a broader user base) it can be used as a reference, and we'll probably have to refactor/rebuild the OCR testing mechanics of nixpkgs. 
While I could have "fixed" it unintrusively the fix would have had a negative performance impact on the CI (and frankly a hack) - IMO not worth it, for this package.

**Comment by pbsds** [comment]
Great investigative work! I'm onboard with the workaround but not quite with the erasure of domain knowledge. Please reintroduce the wait_for_text as a comment with an explanation as to why it doesn't work currently.

**Comment by paumr** [comment]
Thanks! Works for me, I reintroduced the change as comment.

**Pull request merged**
