### PR TITLE
buildDotnetModule: fix `projectReferences = [ ... ]`

### PR DESCRIPTION
**Pull request by raphaelr**
###### Description of changes

#229851 broke the projectReferences feature of buildDotnetModule. The new `mkNugetSource` only considers *.nupkg files in the base directory of each dependency, but `nuget init` also considered subdirectories.

When setting `projectReferences` the *.nupkg files of the referenced project will be [placed in the `/share` subdirectory](https://github.com/NixOS/nixpkgs/blob/0d497d938046dce607171838fbad8170c8a514f9/pkgs/build-support/dotnet/build-dotnet-module/hooks/dotnet-install-hook.sh#L33-L36). Therefore `mkNugetSource` must also search for *.nupkg files in subdirectories.

This PR also adds a test for the projectReferecenes feature, since it's otherwise unused in nixpkgs.

cc: @imsofi

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable: (`tests.dotnet`)
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by imsofi** [comment]
Reading the test, are you sure this will verify the behavior of `projectReferences`? As currently it looks like its replacing the dependency with the same file.

One idea could be to rewrite it to a NixOS test with 2 seperate library files that respectively print `"Failed"` for local, and `"Passed"` for the nix packaged one. That we can check against to see if it used its local or the `projectReferences` version?

**Comment by raphaelr** [comment]
> Reading the test, are you sure this will verify the behavior of `projectReferences`? As currently it looks like its replacing the dependency with the same file.

Do you mean this part?
```
<ProjectReference Include="../library/Library.csproj" />
<PackageReference Include="ProjectReferencesTest.Library" Version="*" Condition=" '$(ContinuousIntegrationBuild)'=='true' " />
```

I'm doing it this way because that's the code that's suggested by the [buildDotnetModule documentation](https://nixos.org/manual/nixpkgs/unstable/index.html#packaging-a-dotnet-application), and I want the test to closely track real-word usage.

The `<ProjectReference>` will not be used, because the `application` derivation does not have access to the `library` source code (due to the `src = ./application`).

**Review by mdarocha — APPROVED** [review]
Looks good, I didn't know about the `pkgs/test` directories.

You can also add a test for basic building of a project using `buildDotnetModule`, more tests is always better.

**Review by corngood — APPROVED** [review]

**Review by soupglasses — APPROVED** [review]

**Comment by imsofi** [comment]
Changing the line `projectReferences = [ library ];` does correctly fail the test correctly. My previous comment for change can be disregarded.

**Pull request merged**
