### PR TITLE
FreeOrion 0.4.7.1 -> 0.4.8

### PR DESCRIPTION
**Pull request by tex**
###### Motivation for this change
Update to working version of FreeOrion.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by tex** [comment]
Fixes #38615.

**Comment by jtojnar** [comment]
Why not update to stable 0.4.8?

**Comment by tex** [comment]
Well, newer is better. But truth is that it is because of this:

```
[1] milan@nixos> nix-prefetch-git --url https://github.com/freeorion/freeorion.git --rev "v0.4.8"                    /etc/nixos/nixpkgs
Bad commit hash or bad reference.
```

I have no idea how prefetch is supposed to be used now to fetch anything other that master...
It used to work as I would expect, but it does not anymore.

**Comment by jtojnar** [comment]
Since it only seems to contain 5 unimportant commits, you would need to change the version to `unstable-2018-09-01` to comply with the policy, and it would also make work for automated updaters harder, I would suggest to stay with stable version, it is preferred anyway.

Regarding `nix-prefetch-git`, I prefer TOFU system, where I change the first byte of the hash (0→1 or 1→0) and `nix-build` will tell me the correct hash. Or use `update-source-version` which does everything for me.

**Comment by tex** [comment]
Ok, will update to 0.4.8. BTW where can I get update-source-version?

**Comment by xeji** [comment]
@GrahamcOfBorg build freeorion

**Pull request merged**
