### PR TITLE
ansible: 2.9.25 -> 2.9.26; 2.10.13 -> 2.10.14; 2.11.4 -> 2.11.5

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://github.com/ansible/ansible/blob/v2.11.5/changelogs/CHANGELOG-v2.11.rst#v2-11-5
https://github.com/ansible/ansible/blob/stable-2.10/changelogs/CHANGELOG-v2.10.rst#v2-10-14
https://github.com/ansible/ansible/blob/stable-2.9/changelogs/CHANGELOG-v2.9.rst#v2-9-26

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
diff LGTM

**Comment by jonringer** [comment]
should we backport these? I feel like we should, since we have [major+minor] stable top-level attrs

**Comment by mweinelt** [comment]
SGTM.

**Comment by jonringer** [comment]
if it's significant amount of work, then maybe it's not worth it. 21.11 will be released in 10ish weeks anyway

**Pull request merged**
