### PR TITLE
Nix minimal version: 1.11 -> 2.0

### PR DESCRIPTION
**Pull request by grahamc**
Placeholders are just too convenient.

Extracted from https://github.com/NixOS/nixpkgs/pull/37693

### CODE REVIEW

**Comment by Mic92** [comment]
This should definitely have release notes.

**Comment by grahamc** [comment]
image

**Comment by vcunat** [comment]
Great to have the release note.  I believe we should improve the message in `<nixpkgs/deault.nix>` with similar information as well (or a hyperlink to it).  I'm not sure about the exact formulation yet, though.

**Comment by grahamc** [comment]
Good idea @vcunat:

```
error: evaluation aborted with the following error message: '
This version of Nixpkgs requires Nix >= 2.0, please upgrade:

- If you are running NixOS, `nixos-rebuild' can be used to upgrade your system.

- Alternatively, with Nix > 2.0 `nix upgrade-nix' can be used to imperatively
  upgrade Nix. You may use `nix-env --version' to check which version you have.

- If you installed Nix using the install script (https://nixos.org/nix/install),
  it is safe to upgrade by running it again:

      curl https://nixos.org/nix/install | sh

For more information, please see the NixOS release notes at
https://nixos.org/nixos/manual.
'
```

**Comment by vcunat** [comment]
Right, that should work well.  After the release happens, at least :-)

**Comment by grahamc** [comment]
```error: evaluation aborted with the following error message: '
This version of Nixpkgs requires Nix >= 2.0, please upgrade:

- If you are running NixOS, `nixos-rebuild' can be used to upgrade your system.

- Alternatively, with Nix > 2.0 `nix upgrade-nix' can be used to imperatively
  upgrade Nix. You may use `nix-env --version' to check which version you have.

- If you installed Nix using the install script (https://nixos.org/nix/install),
  it is safe to upgrade by running it again:

      curl https://nixos.org/nix/install | sh

For more information, please see the NixOS release notes at
https://nixos.org/nixos/manual or locally at
/home/grahamc/projects/nixpkgs/doc/manual/release-notes.

If you need further help, see https://nixos.org/nixos/support.html
'
```

how about this?

**Comment by srhb** [comment]
Yay!

But: While nix upgrade-nix *should* be a good answer, I think it's pretty dangerous to advertise its existence as long as https://github.com/NixOS/nix/issues/2175 exists.

**Comment by vcunat** [comment]
Well, in this case, either you have `nix` command and you have nix 2 and should not have a problem yet, or you don't have it and can't run `nix upgrade-nix`.  (Well, yes, you probably might be in some edge case when `nixos-rebuild` uses nix1 but you still have nix2 in your env.)

**Comment by vcunat** [comment]
Yes, I'm glad you did point it out. (to make my meaning clear)

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

DO NOT MERGE even if this passes!

**Review by samueldr — APPROVED** [review]

**Comment by vcunat** [comment]
2.0 has been the default during whole stable 18.03, and it's basically backward compatible with 1.x.  I expect we will document some hints for such upgrade leaps, but it only happens for combinations of versions whose support didn't overlap (several months in-between).

**Comment by ElvishJerricco** [comment]
@vcunat I still think it'd be useful to open a discussion thread on discourse.

**Comment by vcunat** [comment]
Here's a thread now: https://github.com/NixOS/nixpkgs/issues/46387

**Comment by ElvishJerricco** [comment]
@vcunat that's just one consequence of the choice to up the minimal version. If we had a proper discussion thread, that issue would be one of several bullets I'd list.

**Comment by vcunat** [comment]
I would probably add it into the same thread, as it seems closely related, but you can start another cross-linked one if you think you have some other well-separable bullets.

**Pull request merged**
