### PR TITLE
Fix MySQL Include Path

### PR DESCRIPTION
**Pull request by ahiaao**
###### Motivation for this change
Fixes https://hydra.nixos.org/build/106233951

I noticed several other packages had the same error so I corrected them.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @mpickering @juliendehos @orivej @peterhoeg @4z3 @rickynils @globin @fare @thoughtpolice @sheganinans

### CODE REVIEW

**Comment by aanderse** [comment]
cc @Izorkin

**Comment by Izorkin** [comment]
Thanks for fix.
My fix variant grass - https://github.com/NixOS/nixpkgs/pull/72876/files
Other packages in 19.09 did not check.

**Comment by Izorkin** [comment]
In the master branch, these packages correct builded.

**Comment by bennofs** [comment]
merged to the release branch.

**Pull request closed without merging**
