### PR TITLE
lumail: 2.9 -> 3.1

### PR DESCRIPTION
**Pull request by matthiasbeyer**
###### Motivation for this change

Wanna try out lumail

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This fails for me with

```
installing
install flags: install SHELL=/nix/store/sxwh6a4v8xdlvg4jf3vl2jh9l5760hsc-bash-4.4-p12/bin/bash LVER=lua PREFIX=\$\(out\) SYSCONFDIR=\$\(out\)/etc gsettingsschemadir=/nix/store/c697qr96a0cbyli667jy3khhglsdvmj4-lumail-3.1/share/gsettings-schemas/lumail-3.1/glib-2.0/schemas/
rm /etc/lumail2/perl.d/delete-message || true
rm: cannot remove '/etc/lumail2/perl.d/delete-message': No such file or directory
rm /etc/lumail2/perl.d/get-folders    || true
rm: cannot remove '/etc/lumail2/perl.d/get-folders': No such file or directory
rm /etc/lumail2/perl.d/get-messages   || true
rm: cannot remove '/etc/lumail2/perl.d/get-messages': No such file or directory
rm /etc/lumail2/perl.d/save-message   || true
rm: cannot remove '/etc/lumail2/perl.d/save-message': No such file or directory
rm /etc/lumail2/perl.d/set-flags      || true
rm: cannot remove '/etc/lumail2/perl.d/set-flags': No such file or directory
rm /etc/lumail2/perl.d/imap-proxy     || true
rm: cannot remove '/etc/lumail2/perl.d/imap-proxy': No such file or directory
rm /etc/lumail2/perl.d/Lumail.pm      || true
rm: cannot remove '/etc/lumail2/perl.d/Lumail.pm': No such file or directory
rmdir /etc/lumail2/perl.d             || true
rmdir: failed to remove '/etc/lumail2/perl.d': No such file or directory
mkdir -p /usr/share/lumail || true
mkdir: cannot create directory '/usr': Permission denied
install -m755 perl.d/imap-proxy /usr/share/lumail/
install: target '/usr/share/lumail/' is not a directory: No such file or directory
make: *** [Makefile:243: install_imap] Error 1
builder for ‘/nix/store/ipd27jim2a0gcc2rc6yhbg77zsw35xcn-lumail-3.1.drv’ failed with exit code 2
```

I assume that the `makeFlags` do not properly work. Neither `DESTDIR` nor `PREFIX` is overriden, as the log suggests.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Tested and works for me.

Please review the package, I made some serious modifications. @orivej

**Comment by matthiasbeyer** [comment]
Please don't merge. Found a bug.

**Comment by matthiasbeyer** [comment]
I'm currently trying to set the lua path. I fail hard.

**Comment by matthiasbeyer** [comment]
`postInstall` does not get called apparently.

**Comment by matthiasbeyer** [comment]
Found the issue: https://github.com/lumail/lumail/issues/348

I will squash the patches if someone approves.

**Comment by matthiasbeyer** [comment]
#36816 documents how to use lua 5.2

This branch uses 5.1, which is the simplest fix for the issue. If requested, I can change the package to use 5.2 (or 5.3, if requested of course).

**Comment by Mic92** [comment]
@GrahamcOfBorg build lumail

**Comment by matthiasbeyer** [comment]
Nice. I'll do a squash!

**Comment by matthiasbeyer** [comment]
Ready for merging, IMO.

**Pull request merged**
