### PR TITLE
jetbrains: update

### PR DESCRIPTION
**Pull request by raboof**
Used ./update.pl, no other changes.

Tested by building and running a Scala project in idea-community

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by LeUlukai** [comment]
CLion works fine :+1:

**Comment by kolaente** [comment]
Goland flat out crashes with a SIGSEGV on my machine: 

```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f8252561692, pid=12900, tid=12901
#
# JRE version: OpenJDK Runtime Environment (11.0.7) (build 11.0.7+0-adhoc..source)
# Java VM: OpenJDK 64-Bit Server VM (11.0.7+0-adhoc..source, mixed mode, tiered, compressed oops, concurrent mark sweep gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x82a692]  InstanceKlass::initialize_impl(Thread*)+0x492
#
# Core dump will be written. Default location: Core dumps may be processed with "/nix/store/vac1gmzh1xmk3s7w9pbjvirxqsg1npn0-systemd-243.7/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/konrad/www/nixpkgs/core.12900)
#
# An error report file with more information is saved as:
# /home/konrad/java_error_in_GOLAND_12900.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
/nix/store/d2zaxh9z4v1bsv551dqs088dn1ckvb85-goland-2020.2.2/goland-2020.2.2/bin/goland.sh: line 229: 12900 Aborted                 (core dumped) "$JAVA_BIN" -classpath "$CLASSPATH" ${VM_OPTIONS} "-XX:ErrorFile=$HOME/java_error_in_GOLAND_%p.log" "-XX:HeapDumpPath=$HOME/java_error_in_GOLAND.hprof" -Didea.vendor.name=${PRODUCT_VENDOR} -Didea.paths.selector=${PATHS_SELECTOR} "-Djb.vmOptionsFile=$VM_OPTIONS_FILE" ${IDE_PROPERTIES_PROPERTY} -Didea.platform.prefix=GoLand com.intellij.idea.Main "$@"
```

I've been seeing this lately with the current version as well so it might not be related to the update itself but rather some issue in my setup.

**Comment by kolaente** [comment]
On another note, there have also been updates to phpstorm, would you mind updating that as well in this PR or should i open another one?

**Comment by raboof** [comment]
> there have also been updates to phpstorm

AFAICS the update script updates all components - I guess that phpstorm update wasn't available yet when I opened this PR 11 days ago?

> would you mind updating that as well in this PR or should i open another one?

I think the easiest way forward is if you create a new PR (that would then supersede this one).

**Comment by kolaente** [comment]
> AFAICS the update script updates all components - I guess that phpstorm update wasn't available yet when I opened this PR 11 days ago?

I think so, yes.

> I think the easiest way forward is if you create a new PR (that would then supersede this one).

Is up: #97359

**Comment by raboof** [comment]
closing this in favour of #97359 then

**Pull request closed without merging**
