### PR TITLE
cmake: Tighten deps

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

 - OpenSSL is evidentally an optional dep. I guess pkg-config found it
   before because it was a transitive dep?

 - `zstd` and cross-built CMake can get by with a `cmakeMinimal that we
   use during bootstrapping, so let's restrict to that.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
Don't we put overrides for bootstrapping elsewhere?

**Comment by vcunat** [comment]
If it's more complex, I think it's better to keep an option in the expression itself, as it's less likely that a change will clash with those overrides.

**Comment by Ericson2314** [comment]
Yeah the Darwin bootstrapping just used the `isBootstrap` defined here.

**Comment by Ericson2314** [comment]
Ofborg is stalled, but I built the Darwin stdenv by hand.

**Comment by vcunat** [comment]
Ofborg for darwin is a "known problem": https://github.com/NixOS/ofborg/issues/529#issuecomment-690913092

**Pull request merged**
