### PR TITLE
jdupes: 1.21.0 -> 1.27.3

### PR DESCRIPTION
**Pull request by pbsds**
## Description of changes

Diff: https://github.com/jbruchon/jdupes/compare/v1.21.0...v1.27.3

Bye bye patches. As noted in #212217 i made sure to target staging.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pbsds** [comment]
@ofborg build jdupes

**Review by romildo — APPROVED** [review]
LGTM

**Comment by pbsds** [comment]
Skimming the changelogs, it seems this is a breaking change. Hence merge should wait until after the the 23.11 branchoff

**Comment by pbsds** [comment]
> jdupes migrated from GitHub to codeberg (https://www.jdupes.com/2023/10/05/news-github-is-out-codeberg-is-in, [jbruchon/jdupes@2984bd7](https://github.com/jbruchon/jdupes/commit/2984bd77f47123591c971eb872b3d99c27070c93), https://github.com/jbruchon/jdupes/releases/tag/v1.27.0), I think it's better to replace fetchFromGitHub with fetchFromGitea in both packages right away.

Thanks for the heads up :smile:

**Comment by romildo** [comment]
@pbsds I think I will remove myself as maintainer of this package. Maybe you want to include yourself as its maintainer.

**Comment by pbsds** [comment]
I don't feel like assuming maintainership, considering i don't use the software

**Review by romildo — APPROVED** [review]

**Comment by pbsds** [comment]
The darwin builders seem unable to build coreutils, which tells me nothing. I'll watch the [hydra job](https://hydra.nixos.org/job/nixpkgs/trunk/jdupes.x86_64-darwin)

**Pull request merged**
