### PR TITLE
[21.05] nvidia_x11: 470.57.02 → 470.63.01

### PR DESCRIPTION
**Pull request by TLATER**
###### Motivation for this change

Nvidia driver build failure as documented in #132840.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by r-burns — APPROVED** [review]
Result of `nixpkgs-review pr 138132` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxPackages-libre.nvidia_x11</li>
    <li>linuxPackages_hardkernel_4_14.nvidia_x11</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11</li>
    <li>linuxPackages_latest-libre.nvidia_x11</li>
  </ul>
</details>
<details>
  <summary>21 packages built:</summary>
  <ul>
    <li>bumblebee</li>
    <li>geekbench</li>
    <li>linuxPackages.nvidia_x11 (linuxPackages_5_10.nvidia_x11)</li>
    <li>linuxPackages_4_14.nvidia_x11</li>
    <li>linuxPackages_4_19.nvidia_x11</li>
    <li>linuxPackages_4_4.nvidia_x11</li>
    <li>linuxPackages_4_9.nvidia_x11</li>
    <li>linuxPackages_5_13.nvidia_x11</li>
    <li>linuxPackages_5_14.nvidia_x11 (linuxPackages_latest.nvidia_x11)</li>
    <li>linuxPackages_5_4.nvidia_x11</li>
    <li>linuxPackages_hardened.nvidia_x11 (linuxPackages_latest_hardened.nvidia_x11)</li>
    <li>linuxPackages_lqx.nvidia_x11</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11</li>
    <li>linuxPackages_xanmod.nvidia_x11</li>
    <li>linuxPackages_zen.nvidia_x11</li>
    <li>mangohud</li>
    <li>primus</li>
    <li>psensor</li>
    <li>python38Packages.TheanoWithCuda</li>
    <li>python39Packages.TheanoWithCuda</li>
    <li>xpraWithNvenc</li>
  </ul>
</details>

**Comment by rycee** [comment]
I've been running this exact change for a few days without any issues. FWIW, since I only use the driver to turn off the nvidia gpu in my laptop.

I'm using `linuxPackages_latest`. If somebody could confirm that it works with plain `linuxPackages` then I'd be happy to merge.

**Comment by TLATER** [comment]
I'll give it a test run on `linuxPackages` this weekend if nobody else gets around to it, also running `_latest`, of course, otherwise I wouldn't have noticed the breakage :)

**Comment by TLATER** [comment]
I've been running with `linuxPackages` since Friday evening, and not seen any issues, even running some games. I've not tested cuda or a variety of GPUs of course, but I don't think we've been trying to assert function for the whole range of GPUs/features supported by the driver in the past.

**Comment by rycee** [comment]
Thanks! I think that is good enough 👍

**Pull request merged**
