### PR TITLE
[20.03] smartmontools: 7.0 -> 7.1 and devicedb updated to latest

### PR DESCRIPTION
**Pull request by Frostman**
###### Motivation for this change

https://www.smartmontools.org/browser/tags/RELEASE_7_1/smartmontools/NEWS

Currently, we have 1+ year old devicedb.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/81423)

### CODE REVIEW

**Comment by andir** [comment]
@GrahamcOfBorg eval
@GrahamcOfBorg build smartmontools

**Comment by worldofpeace** [comment]
> Currently, we have 1+ year old devicedb. 

It appear they release once a year consistently.
Given that was just 2019-12-30, no too long ago, it hope it's fine.

**Comment by andir** [comment]
Usually these are fine. I remember having updated them on 19.09 (or 19.03?) because my by then current hardware wasn't even remotely being supported. This should generally be a good QoL improvement and not much of a risk.

**Comment by Frostman** [comment]
@worldofpeace I was talking about devicedb, not about the smartmontools. Last time we had an update to it about a year ago from trunk and I took from trunk again in that PR. I've added to my list to monitor changes in it to update probably about every quarter.

**Pull request merged**
