### PR TITLE
nixos/zabbix: overhaul package & module

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
Team effort between @mmahut and myself to cleanup Zabbix in NixOS as the module & packages have become fairly unmaintained.

I've been running this in a reasonably sized environment for about a month now.

###### Things not yet done 
- [x] Write some release notes (@aanderse)
- [ ] ~~Add a NixOS test which tests all of the server, proxy, and agent (@mmahut)~~
- [ ] ~~test `zabbixProxy` module in a real environment (@aanderse)~~

I'm comfortable to go ahead and merge this without a NixOS test in good faith that @mmahut will eventually get the up and running. As for the `zabbixProxy` module it will eventually get tested in my environment before 19.09 so I can fix an issues which may come up before then. At this point mostly waiting for @PsyanticY to give a thumbs up, as they had done some of the same work this PR does (my fault, I really should have searched for any open PRs when I pushed this).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by aanderse** [comment]
@PsyanticY Well I didn't notice https://github.com/NixOS/nixpkgs/pull/63581... Can you please review this and provide feedback?

**Comment by matthewbauer** [comment]
Sorry for missing this! Had not realized there were multiple zabbix prs, but this one certainly looks to handle things well. Feel free to revert the other PR (or base on top of it).

**Comment by aanderse** [comment]
@matthewbauer No problem, it happens. My fault as well. I had started this branch before the other was publish so when I checked it wasn't there... but then when I actually pushed and made a PR I didn't check again. Oops.

This PR has now been based on top of master after the other PR was merged. As mentioned I have been running this for roughly a month now. Mostly compatible with the merged PR, just a few tiny naming differences. Care to merge?

**Comment by PsyanticY** [comment]
@aanderse, as @matthewbauer  said this one handle thing way better then the other pr so please revert the other or base on top of it.

**Comment by aanderse** [comment]
@PsyanticY Thanks for your approval on this. I regret that our work clashed so I'll double check open PRs more than once next time I work on something like this! Already rebased and briefly tested so I'm going ahead and merging this. Thank you for your support and listing yourself as a maintainer. I hope to hear from you again on the topic of zabbix on NixOS :smile:

**Comment by PsyanticY** [comment]
Thanks, no problem, it is all for the grater nix good :p  :)

**Pull request merged**
