### PR TITLE
python3Packages.spacy: 2.0.18 -> 2.1.3

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

Changes:

https://github.com/explosion/spaCy/releases

The most important change since 2.0.x is support for ELMo/BERT-like pretraining, but there are many other changes that improve spaCy across the board.

Since spaCy has quite many dependencies (that seem to be specific to spaCy), I have bundled all the necessary changes together in this PR, namely:

* Add the wasabi wheel
* Add the srsly wheel
* Add the blis wheel
* Update thinc 7.0.4

The last commit updates all the models to version 2.1.0, which also adds medium/small models for Greek and a medium-size model for German.

Tested using the analysis example from the spaCy webpage with the English small model.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by danieldk** [comment]
@GrahamcOfBorg build python3Packages.spacy python3Packages.spacy_models.de_core_news_md python3Packages.spacy_models.de_core_news_sm python3Packages.spacy_models.el_core_news_md python3Packages.spacy_models.el_core_news_sm python3Packages.spacy_models.en_core_web_lg python3Packages.spacy_models.en_core_web_md python3Packages.spacy_models.en_core_web_sm python3Packages.spacy_models.en_vectors_web_lg python3Packages.spacy_models.es_core_news_md python3Packages.spacy_models.es_core_news_sm python3Packages.spacy_models.fr_core_news_md python3Packages.spacy_models.fr_core_news_sm python3Packages.spacy_models.it_core_news_sm python3Packages.spacy_models.nl_core_news_sm python3Packages.spacy_models.pt_core_news_sm python3Packages.spacy_models.xx_ent_wiki_sm

**Comment by danieldk** [comment]
spaCy 2.1.4 has been released in the meanwhile, so I have added a commit to update from 2.1.3 to 2.1.4.

**Comment by danieldk** [comment]
@dotlambda Since you reviewed my previous spaCy PRs, any chance that you could review this? (And/or  trigger the Darwin build to check that it builds fine too?)

**Comment by FRidh** [comment]
@GrahamcOfBorg build python3Packages.spacy python3Packages.spacy_models.de_core_news_md python3Packages.spacy_models.de_core_news_sm python3Packages.spacy_models.el_core_news_md python3Packages.spacy_models.el_core_news_sm python3Packages.spacy_models.en_core_web_lg python3Packages.spacy_models.en_core_web_md python3Packages.spacy_models.en_core_web_sm python3Packages.spacy_models.en_vectors_web_lg python3Packages.spacy_models.es_core_news_md python3Packages.spacy_models.es_core_news_sm python3Packages.spacy_models.fr_core_news_md python3Packages.spacy_models.fr_core_news_sm python3Packages.spacy_models.it_core_news_sm python3Packages.spacy_models.nl_core_news_sm python3Packages.spacy_models.pt_core_news_sm python3Packages.spacy_models.xx_ent_wiki_sm

**Pull request merged**
