### PR TITLE
ruby_2_7: init at 2.7.0

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change
Release notes: https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by alyssais** [comment]
@GrahamcOfBorg build ruby ruby_2_7

**Comment by andersk** [comment]
This broke Vagrant.

```console
$ nix-shell -p vagrant --run 'vagrant version'
/nix/store/x2xagsdlb556kg1jzx0qrbc1wyjf8092-ruby2.6.5-json-2.1.0/lib/ruby/gems/2.6.0/gems/json-2.1.0/lib/json/common.rb:100: warning: already initialized constant JSON::NaN
/nix/store/p4hrycs0zaa9x0gsqylbk577ppnryixr-vagrant-2.2.6/lib/ruby/gems/2.6.0/gems/json-2.1.0/lib/json/common.rb:100: warning: previous definition of NaN was here
/nix/store/x2xagsdlb556kg1jzx0qrbc1wyjf8092-ruby2.6.5-json-2.1.0/lib/ruby/gems/2.6.0/gems/json-2.1.0/lib/json/common.rb:102: warning: already initialized constant JSON::Infinity
/nix/store/p4hrycs0zaa9x0gsqylbk577ppnryixr-vagrant-2.2.6/lib/ruby/gems/2.6.0/gems/json-2.1.0/lib/json/common.rb:102: warning: previous definition of Infinity was here
/nix/store/x2xagsdlb556kg1jzx0qrbc1wyjf8092-ruby2.6.5-json-2.1.0/lib/ruby/gems/2.6.0/gems/json-2.1.0/lib/json/common.rb:104: warning: already initialized constant JSON::MinusInfinity
/nix/store/p4hrycs0zaa9x0gsqylbk577ppnryixr-vagrant-2.2.6/lib/ruby/gems/2.6.0/gems/json-2.1.0/lib/json/common.rb:104: warning: previous definition of MinusInfinity was here
/nix/store/x2xagsdlb556kg1jzx0qrbc1wyjf8092-ruby2.6.5-json-2.1.0/lib/ruby/gems/2.6.0/gems/json-2.1.0/lib/json/common.rb:129: warning: already initialized constant JSON::UnparserError
/nix/store/p4hrycs0zaa9x0gsqylbk577ppnryixr-vagrant-2.2.6/lib/ruby/gems/2.6.0/gems/json-2.1.0/lib/json/common.rb:129: warning: previous definition of UnparserError was here
Traceback (most recent call last):
	11: from /nix/store/5y31ch80fwnvbz2lpc7shn0jgnf2mql1-vagrant-2.2.6/bin/.vagrant-wrapped:18:in `<main>'
	10: from /nix/store/5y31ch80fwnvbz2lpc7shn0jgnf2mql1-vagrant-2.2.6/bin/.vagrant-wrapped:18:in `load'
	 9: from /nix/store/5y31ch80fwnvbz2lpc7shn0jgnf2mql1-vagrant-2.2.6/lib/ruby/gems/2.6.0/gems/vagrant-2.2.6/bin/vagrant:88:in `<top (required)>'
	 8: from /nix/store/7l24siwk9yw0znjpcapq0rvpdghxmwsc-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 7: from /nix/store/7l24siwk9yw0znjpcapq0rvpdghxmwsc-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 6: from /nix/store/5y31ch80fwnvbz2lpc7shn0jgnf2mql1-vagrant-2.2.6/lib/ruby/gems/2.6.0/gems/vagrant-2.2.6/lib/vagrant.rb:278:in `<top (required)>'
	 5: from /nix/store/p4hrycs0zaa9x0gsqylbk577ppnryixr-vagrant-2.2.6/lib/ruby/gems/2.6.0/gems/i18n-1.1.1/lib/i18n.rb:55:in `load_path'
	 4: from /nix/store/p4hrycs0zaa9x0gsqylbk577ppnryixr-vagrant-2.2.6/lib/ruby/gems/2.6.0/gems/i18n-1.1.1/lib/i18n.rb:42:in `config'
	 3: from /nix/store/7l24siwk9yw0znjpcapq0rvpdghxmwsc-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 2: from /nix/store/7l24siwk9yw0znjpcapq0rvpdghxmwsc-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 1: from /nix/store/p4hrycs0zaa9x0gsqylbk577ppnryixr-vagrant-2.2.6/lib/ruby/gems/2.6.0/gems/i18n-1.1.1/lib/i18n/config.rb:5:in `<top (required)>'
/nix/store/p4hrycs0zaa9x0gsqylbk577ppnryixr-vagrant-2.2.6/lib/ruby/gems/2.6.0/gems/i18n-1.1.1/lib/i18n/config.rb:6:in `<module:I18n>': uninitialized constant I18n::Config (NameError)
```

Expected:

```
$ nix-shell -I nixpkgs=channel:nixos-19.09 -p vagrant --run 'vagrant version'
Installed Version: 2.2.6
Latest Version: 2.2.6
 
You're running an up-to-date version of Vagrant!
```

I bisected this regression to commit 298010982b8986f6669e2b762634dac48253d7ba “ruby: rubygems 3.0.6 -> 3.1.2”.

**Comment by alyssais** [comment]
> This broke Vagrant.

Also broke rubyMinimal.  I'm looking into it.

**Comment by andersk** [comment]
The rubyMinimal fix was merged as #76649. Vagrant is still broken, though (#76629).

**Pull request merged**
