### PR TITLE
gn: install gn-mode.el as well

### PR DESCRIPTION
**Pull request by rennsax**
## Description of changes

Just like the cmake package installs cmake-mode.el, make the gn package provide gn-mode.el as well.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by AndersonTorres** [comment]
I believe it is not needed, since [Melpa already includes gn-mode](https://melpa.org/#/gn-mode) and in Nixpkgs we generate Elisp packages from Melpa database.

**Comment by rennsax** [comment]
@AndersonTorres The problem is gn-mode on Melpa is obsolete. To receive the updates from upstream, we'd better just install gn-mode.el from the source code.

**Comment by AndersonTorres** [comment]
It complicates the things a bit, because in Nixpkgs we provide byte-compiled and native-compiled outputs (via our Elisp framework).
Merely throwing the raw Elisp files into the Nix Store is not sufficient.

(Yes, this should be ruled as a bug in Cmake too.)

----------

Further, I think it is a bit inefficient, because we do not need to build the whole `gn` (and cause a mass rebuild) in order to use its Emacs mode.
It is way cleaner to write a `melpaBuild` expression for it.

**Comment by rennsax** [comment]
> because in Nixpkgs we provide byte-compiled and native-compiled outputs (via our Elisp framework)

Oh, I've not heard of this! Could you show an example about how to byte-compile *.el file with Nixpkgs?

**Comment by AndersonTorres** [comment]
I believe you can pick the packages inside `pkgs/applications/editors/emacs/elisp-packages/` as inspiration.

agda2-mode and texpresso look very similar in this regard to gn-mode: elisp files inside a more general bundle.

**Comment by rennsax** [comment]
Now I agree that this Pull Request is not necessary. Closed.

**Pull request closed without merging**
