### PR TITLE
ocamlPackages.poll: init at 0.3.1

### PR DESCRIPTION
**Pull request by Sixstring982**
## Description of changes

This change initializes `ocamlPackages.poll` at `0.3.1`.

`poll` provides cross-platform support for the IO event notifications.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vbgl** [comment]
The `kqueue` input must be propagated.

**Comment by ulrikstrid** [comment]
Another note, I assume this is updating riot in the end. Feel free to create a `ocamlPackages.riot: 0.0.5 -> 0.0.6` and then have three commits in the same PR, kqueue, poll and riot. This makes it faster for you to land the end product and it's a single set of changes anyway.

Thank you for your recent contributions!

**Comment by Sixstring982** [comment]
> Another note, I assume this is updating riot in the end. Feel free to create a `ocamlPackages.riot: 0.0.5 -> 0.0.6` and then have three commits in the same PR, kqueue, poll and riot. This makes it faster for you to land the end product and it's a single set of changes anyway.
> 
> Thank you for your recent contributions!

Sounds good -- I'll probably follow this kind of pattern next time I need to.

I assume this works because we don't squash when merging -- this makes sense!

**Comment by Sixstring982** [comment]
> The `kqueue` input must be propagated.

Sounds good!

For future reference, how can you tell that it needs to be propagated?

**Comment by ulrikstrid** [comment]
> > The `kqueue` input must be propagated.
> 
> Sounds good!
> 
> For future reference, how can you tell that it needs to be propagated?

When you build it you can check in the META file (if I remember the name correctly) to see what packages are "required", those are needed at runtime and should be propagated.

I should really write a blog post about these small tips and tricks that you pick up over time.

**Comment by Sixstring982** [comment]
> > > The `kqueue` input must be propagated.
> > 
> > 
> > Sounds good!
> > For future reference, how can you tell that it needs to be propagated?
> 
> When you build it you can check in the META file (if I remember the name correctly) to see what packages are "required", those are needed at runtime and should be propagated.
> 
> I should really write a blog post about these small tips and tricks that you pick up over time.

Excellent -- good to know! Thanks for the tip!

**Pull request merged**
