### PR TITLE
JetBrains Update

### PR DESCRIPTION
**Pull request by dan-smetana**
## Description of changes

Updates JetBrains IDEs.

## Things done

I ran update_ides.py.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sdht0** [comment]
RustRover has a new update: https://www.jetbrains.com/rust/nextversion/

**Comment by danielslee** [comment]
@sdht0 Updated

**Review by SuperSandro2000 — APPROVED** [review]

**Review by klDen — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Please remove the merge commit from the PR.

**Comment by danielslee** [comment]
@SuperSandro2000 done. I also ran the update script again since 2023.3 is out now.

**Comment by danielslee** [comment]
Looks like we also need to add some libraries for 2023.3.

**Comment by phip1611** [comment]
Thanks for working on this! I hope this gets merged soon. It sucks that Jetbrains prevents us from using old versions:

image

**Comment by nixdrin** [comment]
Seems like there is already 2023.3.1 now if you want to do yet another update. :-)

**Pull request merged**
