### PR TITLE
pythonPackages.docker: 3.7.2 -> 4.0.2

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
Just scraping repology at this point, updating packages.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

$ nix path-info -Sh ./result
/nix/store/k3qp6r21m4663yb6vwsa02dphqbqnv60-python3.6-docker-3.7.2       105.3M

$ nix path-info -Sh ./result
/nix/store/n6qyv9yfbhjnk2zc00rv1akj641lg5qc-python3.6-docker-4.0.1       107.4M

### CODE REVIEW

**Comment by jonringer** [comment]
Noticed it didnt build on python2, so I updated it.

**Comment by jonringer** [comment]
ping @FRidh 
should be able to merge
packages that are broken as a part of `nix-review` are broken on master.

```
[30 built (1 failed), 6 copied (180.8 MiB), 45.5 MiB DL]
error: build of '/nix/store/ymfm7sihyahkv21ff3qjy6nkh40vxz6m-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/63480
2 package are marked as broken and were skipped:
python27Packages.imgaug python37Packages.imgaug

1 package failed to build:
python37Packages.acoustics

141 package were build:
aws-sam-cli buildbot buildbot-full buildbot-ui csvs-to-sqlite docker-compose fdroidserver poretools python27Packages.Quandl python27Packages.altair python27Packages.atomman python27Packages.awkward python27Packages.bkcharts python27Packages.blaze python27Packages.bokeh python27Packages.caffe python27Packages.celery python27Packages.csvs-to-sqlite python27Packages.cufflinks python27Packages.dask python27Packages.dask-glm python27Packages.dask-image python27Packages.dask-jobqueue python27Packages.dask-ml python27Packages.dask-mpi python27Packages.distributed python27Packages.djmail python27Packages.docker python27Packages.drms python27Packages.fastparquet python27Packages.geopandas python27Packages.glymur python27Packages.google_cloud_bigquery python27Packages.google_cloud_monitoring python27Packages.histbook python27Packages.holoviews python27Packages.hvplot python27Packages.image-match python27Packages.imbalanced-learn python27Packages.mapsplotlib python27Packages.moto python27Packages.odo python27Packages.pandas python27Packages.panel python27Packages.partd python27Packages.pims python27Packages.pvlib python27Packages.pyarrow python27Packages.pyfftw python27Packages.pymatgen python27Packages.scikitimage python27Packages.seaborn python27Packages.slicedimage python27Packages.statsmodels python27Packages.streamz python27Packages.sumo python27Packages.tablib python27Packages.trackpy python27Packages.uproot python27Packages.uproot-methods python27Packages.vega python27Packages.vega_datasets python27Packages.vidstab python37Packages.Quandl python37Packages.altair python37Packages.aplpy python37Packages.atomman python37Packages.awkward python37Packages.bkcharts python37Packages.blaze python37Packages.bokeh python37Packages.buildbot-plugins.console-view python37Packages.buildbot-plugins.grid-view python37Packages.buildbot-plugins.waterfall-view python37Packages.buildbot-plugins.wsgi-dashboards python37Packages.caffe python37Packages.celery python37Packages.cufflinks python37Packages.dask python37Packages.dask-glm python37Packages.dask-image python37Packages.dask-jobqueue python37Packages.dask-ml python37Packages.dask-mpi python37Packages.dask-xgboost python37Packages.datashader python37Packages.dftfit python37Packages.distributed python37Packages.djmail python37Packages.docker python37Packages.drms python37Packages.fastparquet python37Packages.geopandas python37Packages.glymur python37Packages.google_cloud_bigquery python37Packages.google_cloud_monitoring python37Packages.histbook python37Packages.holoviews python37Packages.hvplot python37Packages.ibis-framework python37Packages.image-match python37Packages.imbalanced-learn python37Packages.intake python37Packages.jupyter-repo2docker python37Packages.lammps-cython python37Packages.moto python37Packages.odo python37Packages.optuna python37Packages.osmnx python37Packages.pandas python37Packages.panel python37Packages.partd python37Packages.pims python37Packages.pvlib python37Packages.pyarrow python37Packages.pyfftw python37Packages.pymatgen python37Packages.pymatgen-lammps python37Packages.pymc3 python37Packages.rl-coach python37Packages.scikit-bio python37Packages.scikitimage python37Packages.seaborn python37Packages.slicedimage python37Packages.starfish python37Packages.statsmodels python37Packages.streamz python37Packages.stumpy python37Packages.sumo python37Packages.sunpy python37Packages.tablib python37Packages.trackpy python37Packages.uproot python37Packages.uproot-methods python37Packages.vega python37Packages.vega_datasets python37Packages.vidstab python37Packages.wrf-python python37Packages.xarray python37Packages.xgboost visidata
```

**Comment by marsam** [comment]
@GrahamcOfBorg build pythonPackages.docker python3Packages.docker

**Comment by marsam** [comment]
Thanks @jonringer, btw feel free to ping me if any PR gets stuck

**Pull request merged**
