### PR TITLE
 fsharp41: 4.1.7 -> 4.1.34; mono = mono6

### PR DESCRIPTION
**Pull request by jirkadanek**
###### Motivation for this change
Update another consumer of mono4. Together with https://github.com/NixOS/nixpkgs/pull/66255, there should be no uses of mono4 left in the nixpkgs tree.

Depends on https://github.com/NixOS/nixpkgs/pull/66134 for msbuild.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @thoughtpolice @7c6f434c

### CODE REVIEW

**Review by 7c6f434c — APPROVED** [review]
It's a pity that apparently there is no trivial-to-verify way to make sure that `myget.org` references go to the proper builds of the dependencies, but apparently this is hard to avoid.

**Comment by mmahut** [comment]
@GrahamcOfBorg build fsharp41

**Comment by mmahut** [comment]
@GrahamcOfBorg build msbuild

**Comment by mmahut** [comment]
@GrahamcOfBorg build dotnetPackages.Nuget

**Comment by mmahut** [comment]
@GrahamcOfBorg build mono6

**Comment by jdanekrh** [comment]
@GrahamcOfBorg build mono6

**Comment by jdanekrh** [comment]
mono6 on x86_64-darwin timed out for no (to me) obvious reason. wanted to try if maybe I can retrigger it unchanged. apparently not.

**Comment by mmahut** [comment]
@GrahamcOfBorg build mono6

**Comment by jdanekrh** [comment]
It ran a little bit further in https://logs.nix.ci/?attempt_id=c323e29a-bf41-4bed-8533-3226bdda8881&key=nixos%2Fnixpkgs.66299 than in https://logs.nix.ci/?attempt_id=4690cdd7-839d-4e1e-866a-843e19635f03&key=nixos%2Fnixpkgs.66299, but at the end, macos still timeouted.

**Comment by mmahut** [comment]
yeah, @NixOS/darwin-maintainers anyone willing to give this a try please? :)

**Pull request merged**
