### PR TITLE
python311Packages.{onnxconverter-common,skl2onnx}: unpin protobuf

### PR DESCRIPTION
**Pull request by aaronjheng**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
Why this change? Has it been tested? If so, on what platform? Please use the form.

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
Those should be 2 commits and one should be a normal update commit

**Comment by aaronjheng** [comment]
There are errors similar to the following when building these two packages.
```
...
pythonCatchConflictsPhase
/nix/store/q2zpnf017gccs9w9mb0ikdqhkf0k5v82-catch_conflicts.py:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Found duplicated packages in closure for dependency 'protobuf':
  protobuf 3.20.3 (/nix/store/ybla5hcf1m869cph7c31ydfq1mi7himv-python3.10-protobuf-3.20.3/lib/python3.10/site-packages)
  protobuf 4.24.3 (/nix/store/dr704mj25b1m8xxjkz340jik4grs763g-python3.10-protobuf-4.24.3/lib/python3.10/site-packages)
...
```
It turns out that they both depend on onnx which depend on protobuf (not protobuf3).

**Comment by aaronjheng** [comment]
Here's the tricky thing. skl2onnx depends on onnx and onnxconverter-common. And onnxconverter-common also depends on onnx.

**Comment by aaronjheng** [comment]
> If all parts can work with the latest protobuf, then that is fine. But please be clear about this in your pull request. The form exists for a reason.

My bad. All done.

**Comment by aaronjheng** [comment]
Result of `nixpkgs-review pr 256603` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>python310Packages.onnxconverter-common</li>
    <li>python310Packages.onnxconverter-common.dist</li>
    <li>python310Packages.onnxmltools</li>
    <li>python310Packages.onnxmltools.dist</li>
    <li>python310Packages.skl2onnx</li>
    <li>python310Packages.skl2onnx.dist</li>
    <li>python311Packages.onnxconverter-common</li>
    <li>python311Packages.onnxconverter-common.dist</li>
    <li>python311Packages.onnxmltools</li>
    <li>python311Packages.onnxmltools.dist</li>
    <li>python311Packages.skl2onnx</li>
    <li>python311Packages.skl2onnx.dist</li>
  </ul>
</details>

**Pull request closed without merging**
