### PR TITLE
mdds: 0.12.1 -> 1.2.1

### PR DESCRIPTION
**Pull request by romildo**
###### Things done
- [x] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
libreoffice seems to depend on this package. Did you test whether that still build after this update?

**Comment by romildo** [comment]
As the versions of `libreoffice` currently in the repository do not build with `mdds-1.2.1`, I am keeping `mdds-0.12.1` and adding explicitly as a dependency for libreoffice.

But more recent versions of libreoffice needs at least `mdds-1.2.0` and this is the primary reason I want to update mdds: to enable updating libreoffice.

**Comment by FRidh** [comment]
looks good to me then.

**Comment by romildo** [comment]
Not needed anymore because the commits https://github.com/NixOS/nixpkgs/commit/01b3f3d00b970d23d3696f1d14eafeb260e7d46e, https://github.com/NixOS/nixpkgs/commit/6536d6fe9c193ca25e440075ae84ac4efffae5da and https://github.com/NixOS/nixpkgs/commit/bb4884bb3205e36d9ff67be33638728fd6c6fccc do the version bumping.

**Pull request closed without merging**
