### PR TITLE
pythonPackages.sphinx: 1.8.3 -> 2.2.0

### PR DESCRIPTION
**Pull request by wamserma**
###### Motivation for this change

http://www.sphinx-doc.org/en/master/changes.html#release-2-2-0-released-aug-19-2019
depends on https://github.com/NixOS/nixpkgs/pull/71591 https://github.com/NixOS/nixpkgs/pull/71593 https://github.com/NixOS/nixpkgs/pull/71594 https://github.com/NixOS/nixpkgs/pull/71597 https://github.com/NixOS/nixpkgs/pull/71598 https://github.com/NixOS/nixpkgs/pull/71599

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by jonringer** [comment]
Thank you for combining all the commits into a single PR :)

**Comment by jonringer** [comment]
Do you mind rebasing this on top of the staging branch, then changing the base branch to staging. For large rebuilds we do this to avoid having people build against master get hit by large rebuilds

**Comment by wamserma** [comment]
> Do you mind rebasing this on top of the staging branch, then changing the base branch to staging. For large rebuilds we do this to avoid having people build against master get hit by large rebuilds

Ok, picked up the change requests from the individual PRs, rebased onto staging cleaned up the history. Feel free to close the individual PRs.

**Comment by FRidh** [comment]
Thanks.

> Feel free to close the individual PRs. 

Could you do that yourself?

**Comment by wamserma** [comment]
Could some please take the duty of running

```bash
nix-shell -p nix-review --run 'nix-review pr 71601
```

This includes building pretty much the whole Haskell ecosystem due to the extensive usage of Sphinx for documentation.

I expect quite a few builds to break as Sphinx has changed some defaults, e.g. the name of the documentation index page (contents.rst vs. index.rst) and not all packages may have that configured properly in their `conf.py`.

**Comment by FRidh** [comment]
I will push this to a special branch soon where it will build on Hydra. It won't build everything but a lot.

**Comment by wamserma** [comment]
> I will push this to a special branch soon where it will build on Hydra. It won't build everything but a lot.

Thx.

**Comment by wamserma** [comment]
rebased on current staging

**Comment by FRidh** [comment]
ahh, I forgot to include sphinx itself when I cherry-picked the range. Sorry for that.

**Comment by wamserma** [comment]
> ahh, I forgot to include sphinx itself when I cherry-picked the range. Sorry for that.

Yep. But having sphinx in its own update isn't that bad, as it is the sphinx package itself which will trigger the mass rebuilds and probably break building of documentation for some packages.

**Comment by FRidh** [comment]
Triggered a job at https://hydra.nixos.org/jobset/nixpkgs/python-unstable

**Comment by FRidh** [comment]
This has landed in master so closing.

**Pull request closed without merging**
