### PR TITLE
dvdisaster: Apply debian's patches, fix desktop file and icons

### PR DESCRIPTION
**Pull request by jgeerds**
This PR makes it possible to build dvdisaster with Debian's patches and enable it by default. I find these patches very useful because they let you backup DVD-ROMs and encrypted DVDs. Apart from that I updated the meta attributes and add a desktop file.

Any suggestions for a better name? I think `enableSoftening` isn't the best name for it

### CODE REVIEW

**Comment by geerds** [comment]
No suggestions?

**Comment by vcunat** [comment]
I see just a nitpick: ``meta.description`` should [start by a capital](http://nixos.org/nixpkgs/manual/#chap-meta), and I would personally do that for ``longDescription`` as well.

**Comment by geerds** [comment]
@vcunat You're right. Fixed with dd6ddfaf0c31812c344995de8afcd93b4e97f2f4

**Comment by vcunat** [comment]
Good :-)

**Pull request merged**
