### PR TITLE
kpcli: KDBX 4 support

### LINKED ISSUE #330177: kpcli: missing KDBX4 support
### Describe the bug
When i try to open a .kdbx file generated by `keepassxc`, i'm getting:
```
Perl module File::KDBX is required for KDBX4 support.
Without it, KDBX4 files can only be imported.
 - To import a KDBX v4 file, use the import command.
 - For details, see: help import
```

Can you please add this module to the package?

### Steps To Reproduce
1. `kpcli --kdb=filename.kdbx`

### Notify maintainers
@j-keck

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.0, NixOS, 24.11 (Vicuna), 24.11.20240725.5ad6a14`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/xblysc3prg1zqsi59fr36nj6wdiqryzp-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by FliegendeWurst**
Fixes #330177

cc @Schweber

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by stigtsp — CHANGES_REQUESTED** [review]
Hi, can you do discrete commits for the additions of:

- perlPackages.IteratorSimple
- perlPackages.FileKDBX

**Review by stigtsp — DISMISSED** [review]

**Comment by stigtsp** [comment]
LGTM, pending eval

**Comment by stigtsp** [comment]
@ofborg build perlPackages.IteratorSimple perlPackages.FileKDBX

**Comment by stigtsp** [comment]
`z88dk` has its own `IteratorSimple`, it's a bit unexpected that this triggers a rebuild

2 packages updated:
kpcli (4.1 → 4.1.2) z88dk

**Comment by stigtsp** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 348984`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 10 packages built:</summary>
  <ul>
    <li>kpcli</li>
    <li>perl538Packages.FileKDBX</li>
    <li>perl538Packages.FileKDBX.devdoc</li>
    <li>perl538Packages.IteratorSimple</li>
    <li>perl538Packages.IteratorSimple.devdoc</li>
    <li>perl540Packages.FileKDBX</li>
    <li>perl540Packages.FileKDBX.devdoc</li>
    <li>perl540Packages.IteratorSimple</li>
    <li>perl540Packages.IteratorSimple.devdoc</li>
    <li>z88dk</li>
  </ul>
</details>

**Comment by FliegendeWurst** [comment]
> z88dk has its own IteratorSimple, it's a bit unexpected that this triggers a rebuild

I moved that IteratorSimple to the perl package set. It probably rebuilds because the order of packages used in z88dk changed.

**Comment by FliegendeWurst** [comment]
Rebased (due to #348678)

**Review by stigtsp — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
