### PR TITLE
sqlite: Raising max variable number and max expr depth values

### PR DESCRIPTION
**Pull request by sjau**
###### Motivation for this change

I've been having troubles with Flexget and it seems (one of) the problems is that SQLite does have a rather low number of max variables. Having a look at Arch, they have a significantly higher value for maximum variables. Default is 1000 and in arch they have 250 000: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/sqlite#n36

At the same time it also seems a good idea to also raise the max expr depth to the same value as Arch.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by Mic92 — APPROVED** [review]
should go to the staging branch first though.

**Comment by sjau** [comment]
What do you mean by staging branch?

**Review by fpletz — APPROVED** [review]
Other distributions like Debian are doing the same.

**Comment by fpletz** [comment]
@sjau We have a branch called `staging` that is used for mass rebuilds before pushing them to master. Hydra has a jobset for staging. When we merge staging into master all packages are already built. You just need to rebase your commit onto staging and change the target branch of this PR (below the title).

**Comment by sjau** [comment]
And how to do that?

**Comment by Mic92** [comment]
There is an edit button next to the pull request title.

**Comment by sjau** [comment]
No idea why now errors appear....

**Comment by sjau** [comment]
Why did suddenly so many other things come in here? It was just a simple PR with some SQLite compile settings altered....

**Comment by Mic92** [comment]
you changed the base without rebasing locally. This means you attempt, you pushed all commits from master to staging.

**Comment by sjau** [comment]
<--  https://xkcd.com/1597/

**Pull request closed without merging**
