### PR TITLE
ladybird: search for fonts in NixOS-specific paths

### LINKED ISSUE #314604: Ladybird can't find fonts
### Describe the bug

```
1935.554 WebContent(13872): FontDatabase::load_all_fonts_from_uri('file:///usr/share/fonts'): open: No such file or directory (errno=2)
1935.554 WebContent(13872): FontDatabase::load_all_fonts_from_uri('file:///usr/local/share/fonts'): open: No such file or directory (errno=2)
```

### Steps To Reproduce
1. `nix run '.#ladybird'` in nixpkgs git repo

### Expected behavior

Ladybird should not look for fonts in `/usr/share/fonts`

### Notify maintainers

@fgaz

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.7, NixOS, 24.05 (Uakari), 24.05.20240427.58a1abd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.22.0`
 - channels(root): `"nixos"`
 - channels(suhr): `""`
 - nixpkgs: `/nix/store/801l7gvdz7yaibhjsxqx82sc7zkakjbq-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by fgaz**
## Description of changes

Fixes #314604

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by suhr** [comment]
Unfortunately, this does not seem to fix the issue:

```
[nix-shell:~/.cache/nixpkgs-review/pr-315048-1]$ Ladybird
24010.627 WebContent(54903): FontDatabase::load_all_fonts_from_uri('file:///run/current-system/sw/share/X11/fonts'): open: No such file or directory (errno=2)
24010.627 WebContent(54903): FontDatabase::load_all_fonts_from_uri('file:///usr/share/fonts'): open: No such file or directory (errno=2)
24010.627 WebContent(54903): FontDatabase::load_all_fonts_from_uri('file:///usr/local/share/fonts'): open: No such file or directory (errno=2)
24010.652 RequestServer(54904): Loaded 318 of 318 (100%) provided CA Certificates
```

**Comment by fgaz** [comment]
@suhr it's weird that `/run/current-system/sw/share/X11/fonts` doesn't exist on your system. what is the value of `fonts.packages` (run `nixos-option fonts.packages`)?

**Comment by suhr** [comment]
```
  fonts.packages = with pkgs; [
    corefonts
    terminus_font
    dejavu_fonts
    source-code-pro
    source-sans-pro
    source-serif-pro
    lato
    liberastika
    paratype-pt-sans
    paratype-pt-mono
    paratype-pt-serif
    material-icons
    font-awesome
    roboto
    fira-mono
    fira-code
    iosevka-bin
    nur.repos.suhr.iosevka-term
    open-sans
  ];
```

**Comment by suhr** [comment]
See https://github.com/NixOS/nixpkgs/issues/119433. `/run/current-system/sw/share/X11/fonts` exists only when you enable `fonts.fontDir`.

**Comment by fgaz** [comment]
I see. I had it enabled because of flatpak. Then I think we should add a nixos module for ladybird that just enables the fontDir option. How does that sound?

**Comment by suhr** [comment]
Sounds fine to me.

**Review by suhr — APPROVED** [review]

**Review by suhr — APPROVED** [review]

**Comment by fgaz** [comment]
Looks like https://github.com/LadybirdWebBrowser/ladybird/pull/31 will fix this properly, then we can remove the patch that hardcodes the nixos font directory

**Pull request merged**
