### PR TITLE
Combined nodePackages update and init

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Motivation for this change
#107200 #107168 #106665 #94945 #73119 #108178 #100540

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Now doing the update and merging when it is done before we get a thousand new merge conflicts.

**Comment by SuperSandro2000** [comment]
Only took 71m 38s to generate.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108235` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>iosevka: log https://hastebin.com/raw/ofolukarey</li>
  </ul>
</details>
<details>
<summary>
15 packages built:
</summary>
<ul>
<li>antora</li>
<li>bitwarden-cli</li>
<li>castnow</li>
<li>create-cycle-app</li>
<li>epgstation</li>
<li>fast-cli</li>
<li>joplin</li>
<li>mastodon-bot</li>
<li>mirakurun</li>
<li>netlify-cli</li>
<li>shout</li>
<li>vimPlugins.coc-go</li>
<li>vimPlugins.coc-stylelint</li>
<li>vimPlugins.coc-vetur</li>
<li>vscode-extensions.matklad.rust-analyzer</li>
</ul>
</details>

**Comment by FRidh** [comment]
I *think* there is a node-related evaluation error https://github.com/NixOS/nixpkgs/issues/108304.

**Pull request merged**
