### PR TITLE
ocamlPackages.ocsigen_server: fix build; 2.15.0 → 2.16.0

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

Fix current build failure; [lwt 5](https://github.com/ocsigen/ocsigenserver/blob/master/CHANGES#L2).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build ocamlPackages.eliom ocamlPackages.ocsigen-start ocamlPackages.ocsigen-toolkit ocamlPackages.ocsigen_server

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build ocamlPackages.eliom ocamlPackages.ocsigen-start ocamlPackages.ocsigen-toolkit ocamlPackages.ocsigen_server

**Comment by vbgl** [comment]
The current build failure does not seem related to lwt 5: bisection leads to an update of gnumake (0cfe9f3ae25f5c4627664476bececb31e8b0143e).

**Comment by sternenseemann** [comment]
Yeah, sorry I it's not worded clearly:

* The build fix is just the patch added in a3a85f7e8c4a3945dd0d4a300263cdb5bea9edb8 (also applies on 2.15.0)*
* 2.16.0 is supposed to increase compatibility with lwt 5 according to [ocsigen_server's change log](https://github.com/ocsigen/ocsigenserver/blob/master/CHANGES#L2)

**Comment by vbgl** [comment]
@GrahamcOfBorg build ocamlPackages.ocsigen-start

**Comment by vbgl** [comment]
Thanks for the clarification (and for the good PR)!

**Pull request merged**
