### PR TITLE
common-updater: add update script to all-packages

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

- common-updater: add update script to all-packages
- xfce: use updateScript from pkgs

See also https://github.com/NixOS/nixpkgs/pull/84292.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
Why not just use `common-updater-scripts`?

**Comment by romildo** [comment]
> Why not just use `common-updater-scripts`?

`common-updater-script` is lower level. It does not help looking for newer versions at upstream. The new version should be passed as a command line argument.

`update-script.nix` is capable of searching for available versions upstream. Internally it calls `common-updater-script`, though.

It can be used in a derivation like this:

``` nix
  passthru.updateScript = pkgs.updateScript {
    inherit pname version;
    attrPath = "xfce.${pname}";
    versionLister = xfce.archiveLister category pname;
  };
```

``` nix
  passthru.updateScript = pkgs.updateScript {
    inherit pname version;
    attrPath = "xfce.thunar-dropbox-plugin";
    versionLister = xfce.gitLister src.meta.homepage;
  };
```

``` nix
  passthru.updateScript = pkgs.updateScript {
    inherit pname version;
    versionLister = "${pkgs.common-updater-scripts}/bin/list-git-tags ${sr.meta.homepage}";
    odd-unstable = true;
  };
```

**Comment by jtojnar** [comment]
That is very nice. Though maybe a name like `genericUpdateScript` or `genericUpdater` might be better to avoid name clashes.

**Comment by romildo** [comment]
> That is very nice. Though maybe a name like `genericUpdateScript` or `genericUpdater` might be better to avoid name clashes.

Changed the name to `genericUpdater`.

**Review by jtojnar — APPROVED** [review]

**Pull request merged**
