### PR TITLE
ocamlPackage.cohttp: 2.0.0 -> 2.1.3

### PR DESCRIPTION
**Pull request by vbgl**
###### Motivation for this change

cohttp has been broken by #67008 This update fixes it.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mmahut** [comment]
@GrahamcOfBorg build ocamlPackage.cohttp

**Comment by vbgl** [comment]
@GrahamcOfBorg build ocamlPackages.git-unix ocamlPackages.opium

**Comment by mmahut** [comment]
Looks good, thank you @vbgl.

**Comment by vbgl** [comment]
ping @ryantm

**Comment by ryantm** [comment]
@vbgl what's up?

**Comment by vbgl** [comment]
Just in case you wanted to apologize for causing such a mess and tell us what you intend to do to ensure it will not happen again in the future.

**Comment by ryantm** [comment]
Oh, sorry, I didn't see the first sentence of the PR. 

It is interesting that the "rebuild report" for https://github.com/NixOS/nixpkgs/pull/67008 doesn't list ocamlPackage.cohttp. nixpkgs-update is using pretty much the exact same thing that OfBorg uses for determining the number of packages that changed. It also looks like nix-review must not be detecting the dependency.

**Pull request merged**
