### PR TITLE
pythonPackages.pomegranate: 0.8.0 -> 0.8.1

### PR DESCRIPTION
**Pull request by rybern**
Also now using GitHub instead of PiPy, because the PiPy version fails to build. Not sure why they aren't identical.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by disassembler** [comment]
Missing pytest. Lots of errors like this:
```
conftest (unittest.loader._FailedTest) ... ERROR
test (unittest.loader._FailedTest) ... ERROR
testing (unittest.loader._FailedTest) ... ERROR
joblib.test (unittest.loader._FailedTest) ... ERROR
joblib.testing (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: conftest (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: conftest
Traceback (most recent call last):
  File "/nix/store/d0im7d8gvk39xyhwnsqs57rmzvwy8g89-python3-3.6.3/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/build/joblib-0.11/doc/conftest.py", line 2, in <module>
    from joblib.test.common import np, setup_autokill, teardown_autokill
  File "/build/joblib-0.11/joblib/test/__init__.py", line 1, in <module>
    from joblib.test import test_memory
  File "/build/joblib-0.11/joblib/test/test_memory.py", line 32, in <module>
    from joblib.test.common import with_numpy, np
  File "/build/joblib-0.11/joblib/test/common.py", line 12, in <module>
    from joblib.testing import SkipTest, skipif
  File "/build/joblib-0.11/joblib/testing.py", line 12, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

**Comment by rybern** [comment]
@disassembler Good catch, I wasn't testing Python 3. But that appears to be a problem with python3Packages.joblib. In the mean time I could restrict this package to 2.7..

**Comment by Mic92** [comment]
Now it works with both properly (python2/python3).

**Comment by rybern** [comment]
Nice!

**Pull request merged**
