### PR TITLE
yakyak init at 1.5.4-beta-rolling and (patched) electron-packager init at 14.0.6

### PR DESCRIPTION
**Pull request by hlolli**
###### Motivation for this change
new package from https://github.com/NixOS/nixpkgs/issues/55289

###### Things done

the wildcards in this PR are two things, first is this patched wrapper around electron-packager, I'm sure I can reuse it for other electron packages in the future. It just prevents electron-packager from downloading the binaries and tells it to use the ones already provided from nixpkgs (so overriding the electron input would be the way to choose a different electron version).

The second wildcard is the hangupsjs, which had a terrible conflict in coffee-script. Using the version provided in the yakyak npm package causes compilation error, this syntax error is already a ticket here https://github.com/yakyak/hangupsjs/issues/79 and when it's solved, I will bump and remove the hangusjs as a global nodePackage (and use it just as part of the yakyakBuldDeps).

- [ x ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ x ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ x ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ x ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Sir4ur0n** [comment]
Hi, 

What's the next step for this PR please?

Cheers

**Comment by doronbehar** [comment]
For an easy merge of this, I'd suggest not using `node-packages-v10.{json,nix}` directly, but use the approach taken by e.g [remarkjs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/web/remarkjs/default.nix) where a distinct set of packages is used solely for the main package. `node-packages-v10.{json,nix}` are updated frequently and it's easier to maintain these sets separately on a per package basis for these NodeJS / Atom / Electron / Whatever based packages.

I know this is Nixpkgs' approach is inconsistent but it was [mentioned](https://github.com/NixOS/nixpkgs/pull/73087#issuecomment-553575334) before that this approach is better and as you can see, it's easier to maintain..

**Comment by Enteee** [comment]
I would suggest splitting this PR into one pull request per package.

**Comment by mnajib** [comment]
still important to me

**Comment by doronbehar** [comment]
Unsurprisingly, there are merge conflicts. You may find https://discourse.nixos.org/t/call-for-nodepackages-maintainers/9176/ relevant for this.

**Comment by AleXoundOS** [comment]
Still important for me.

**Comment by DamienCassou** [comment]
If this PR is still important to anyone, could this person feel responsible for applying reviewer's suggestions and resolving conflicts?

**Comment by hlolli** [comment]
it seems yakyak is mostly abandoned, I don't have interest in moving this forward, whoever's interested and wants to use the work I did thus far, feel free to open a new pr

**Pull request closed without merging**
