### PR TITLE
nixos-rebuild: do not resolve flake path

### PR DESCRIPTION
**Pull request by thiagokokada**
###### Motivation for this change

The removed lines converted the flake path passed by the command line from `/some/path` to `git+file:///some/path`.

This technically shouldn't cause any issues, however running `nixos-rebuild switch` inside a directory `/nix/store` will cause the switch to fail and leave a partially construct generation (see issue #144811 for details).

By itself this shouldn't be too much of an issue, however thanks to another issue in `systemd-boot-builder.py` this can leave the system in a broken state for those using `boot.loader.systemd-boot` (AFAIK the default), where future `nixos-rebuild switch` will fail (see issue #93694 for details).

The issue can be fixed by running `nix-env -p /nix/var/nix/profiles/system --delete-generations old`, however this makes newbies very confused and it is showing in our support threads in Matrix and Discourse (see https://discourse.nixos.org/t/need-help-on-failure-of-building-my-configuration/16842).

Keep in mind this is a workaround. The actual issue seems to be in nix itself (see: https://github.com/NixOS/nix/issues/5510).

See also #150065 for an alternative fix that caused other issues.

Kudos for @figsoda for figuring out this fix.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thiagokokada** [comment]
Tested a simple `nixos-rebuild switch`, works fine.

**Comment by thiagokokada** [comment]
BTW, this should be backported to `release-21.05` and `release-21.11` since it also affects them. However to avoid the issue from #150065, in case this is merged I will wait sometime before backporting this to the respective branches.

**Comment by thiagokokada** [comment]
CC @edolstra and @cole-h since they're the folks that introduced the lines that are being deleted on this PR.

CC @colemickens @figsoda to help testing.

**Comment by thiagokokada** [comment]
Also CC @TredwellGit to test if this cause issues with ZFS.

**Review by figsoda — APPROVED** [review]
fixes the issue for me
would like it see another review since the other workaround caused issue on zfs

**Comment by thiagokokada** [comment]
> fixes the issue for me would like it see another review since the other workaround caused issue on zfs

CC @TredwellGit.

**Review by TredwellGit — COMMENTED** [review]
This works with the ZFS modules.

**Comment by thiagokokada** [comment]
Going to merge them and leave during some time on `master` branch to see if someone else detects some issues.

**Comment by Enzime** [comment]
Awesome work, I ran into this a couple of times but I was too lazy to debug it, glad to see it was fixed :tada:

**Pull request merged**
