### PR TITLE
libsForQt5.mauikit: init at 1.2.1

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
Maybe use it on my PinePhone one day.

Questions I have:
* Should I fetch the source from https://download.kde.org/stable/maui/ instead?
* Should I include all dependencies listed at https://invent.kde.org/maui/index-fm#dependencies even though it builds and runs fine without?
* Should I put stuff like `kirigami2` in `mauikit`'s `propagatedBuildInputs`?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @NixOS/qt-kde

### CODE REVIEW

**Comment by FRidh** [comment]
> Should I fetch the source from https://download.kde.org/stable/maui/ instead?

I think either is fine.

> Should I include all dependencies listed at https://invent.kde.org/maui/index-fm#dependencies even though it builds and runs fine without?

Maybe some of these are propagated already?

> Should I put stuff like kirigami2 in mauikit's propagatedBuildInputs?

Why? Mauikit apparently does not need it itself, so it should not be an input for itself.

**Comment by dotlambda** [comment]
> Maybe some of these are propagated already?

Seems to be the case, according to `nix why-depends`.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 115242` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>libsForQt512.mauikit: log was empty</li>
  </ul>
</details>
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>index-fm</li>
<li>libsForQt5.mauikit (libsForQt515.mauikit ,plasma5Packages.mauikit)</li>
<li>libsForQt514.mauikit</li>
</ul>
</details>

**Comment by dotlambda** [comment]
> Please mark it broken for Qt512.

Done

**Pull request merged**
