### PR TITLE
gmic: 3.1.6 → 3.2.0

### LINKED ISSUE #212052: gmic build failed
### Steps To Reproduce
1. Open gmic in a nix shell using the unstable channel

### Build log
https://pastebin.com/SwdL7gkE

### Notify maintainers
@ryantm @jtojnar-

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.89, NixOS, 23.05 (Stoat), 23.05pre445203.5ed48194335`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos"`
 - channels(loc): `"home-manager-22.11.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by fabianhjr**
###### Description of changes

Unbreaks on trunk/main branch: https://hydra.nixos.org/eval/1789458?filter=gmic&compare=1789440&full=

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ShivanshuKantPrasad** [comment]
Result of `nixpkgs-review pr 211600` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>gimp-with-plugins</li>
    <li>gimpPlugins.gmic</li>
    <li>gmic-qt</li>
    <li>gmic-qt-krita</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>darktable</li>
    <li>gmic</li>
    <li>photoprism</li>
  </ul>
</details>

**Comment by ShivanshuKantPrasad** [comment]
Build log: https://gist.github.com/ShivanshuKantPrasad/5ca0c5d7b50754ca9d88ba5eb1795777

**Comment by toastal** [comment]
This built fine for me.

**Comment by fabianhjr** [comment]
Included a gmic-qt upgrade but it fails on my end: https://github.com/NixOS/nixpkgs/issues/211721#issuecomment-1398571834

**Comment by fabianhjr** [comment]
gmic is currently broken on trunk/main branch and that is why I tried this version upgrade. (Which did unbreak it)

https://hydra.nixos.org/eval/1789458?filter=gmic&compare=1789440&

**Comment by jtojnar** [comment]
Looks like `gmic` breakage might have been caused by `cimg` bump. Not sure what’s up with `gmic-qt`.

**Review by toastal — APPROVED** [review]
This patch saved my broken build.

**Review by andresilva — COMMENTED** [review]
`gmic` builds fine after this. `gmic-qt` doesn't build though and I couldn't figure out what's happening.

**Comment by toastal** [comment]
I was able to build and run `darktable` as a downsteam dependency ... can't comment on `gmic-qt`

**Comment by NinjaTrappeur** [comment]
This is a rippling effect from https://github.com/NixOS/nixpkgs/pull/211445.

It does fix the darktable build to me.

It does, however, breaks the qmic-qt build:

```
FAILED: CMakeFiles/gmic_qt.dir/src/FilterSyncRunner.cpp.o 
/nix/store/iiq295j1z4q1sxmdbrl2j8ma3l5ns4wr-gcc-wrapper-11.3.0/bin/g++ -DGMIC_HOST=standalone -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_WIDGETS_LIB -D_IS_LINUX_ -D_IS_UNIX_ -Dcimg_appname=\"gmic\" -Dcimg_display=1 -Dcimg_use_abort -Dcimg_use_cpp11=1 -Dcimg_use_curl -Dcimg_use_fftw3 -Dcimg_use_openmp -Dcimg_use_png -Dcimg_use_vt100 -Dcimg_use_zlib -Dgmic_community -Dgmic_gui -Dgmic_is_parallel -I/build/source/build -I/build/source -I/build/source/build/gmic_qt_autogen/include -I/build/source/src -isystem /nix/store/03svkk8l8dfcbabfl9637krwdkhqvyna-qtbase-5.15.8-dev/include/QtCore -isystem /nix/store/03svkk8l8dfcbabfl9637krwdkhqvyna-qtbase-5.15.8-dev/./mkspecs/linux-g++ -isystem /nix/store/03svkk8l8dfcbabfl9637krwdkhqvyna-qtbase-5.15.8-dev/include/QtWidgets -isystem /nix/store/03svkk8l8dfcbabfl9637krwdkhqvyna-qtbase-5.15.8-dev/include/QtGui -isystem /nix/store/03svkk8l8dfcbabfl9637krwdkhqvyna-qtbase-5.15.8-dev/include/QtNetwork -DNDEBUG -Ofast -fopenmp -fPIC -std=gnu++11 -MD -MT CMakeFiles/gmic_qt.dir/src/FilterSyncRunner.cpp.o -MF CMakeFiles/gmic_qt.dir/src/FilterSyncRunner.cpp.o.d -o CMakeFiles/gmic_qt.dir/src/FilterSyncRunner.cpp.o -c /build/source/src/FilterSyncRunner.cpp
/build/source/src/FilterSyncRunner.cpp: In member function 'void GmicQt::FilterSyncRunner::swapImages(gmic_library::gmic_list<float>&)':
/build/source/src/FilterSyncRunner.cpp:77:12: error: 'struct gmic_library::gmic_list<float>' has no member named 'swap'
   77 |   _images->swap(images);
      |            ^~~~
/build/source/src/FilterSyncRunner.cpp: In member function 'void GmicQt::FilterSyncRunner::run()':
/build/source/src/FilterSyncRunner.cpp:160:69: error: invalid user-defined conversion from 'gmic_library::gmic_image<char>' to 'char' [-fpermissive]
  160 |     gmicInstance.set_variable("_persistent", PersistentMemory::image());
      |                                              ~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /build/source/src/FilterSyncRunner.cpp:35:
/nix/store/hdjr32qnmgqmysllvq6v5ds09mhvz5ja-gmic-3.2.0-dev/include/gmic.h:118:5: note: candidate is: 'gmic_library::gmic_image<T>::operator T*() [with T = char]' (near match)
  118 |     operator T*() {
      |     ^~~~~~~~
/nix/store/hdjr32qnmgqmysllvq6v5ds09mhvz5ja-gmic-3.2.0-dev/include/gmic.h:118:5: note:   no known conversion from 'char*' to 'char'
In file included from /build/source/src/FilterSyncRunner.cpp:35:
/nix/store/hdjr32qnmgqmysllvq6v5ds09mhvz5ja-gmic-3.2.0-dev/include/gmic.h:389:63: note:   initializing argument 2 of 'const char* gmic::set_variable(const char*, char, const char*, double, const unsigned int*)'
  389 |   const char *set_variable(const char *const name, const char operation='=', const char *const value=0,
      |                                                    ~~~~~~~~~~~^~~~~~~~~~~~~
/build/source/src/FilterSyncRunner.cpp:165:46: error: 'struct gmic_library::gmic_image<char>' has no member named 'move_to'
  165 |     gmicInstance.get_variable("_persistent").move_to(*_persistentMemoryOuptut);
      |                                              ^~~~~~~
/build/source/src/FilterSyncRunner.cpp:167:20: error: no matching function for call to 'gmic_library::gmic_list<float>::assign()'
  167 |     _images->assign();
      |     ~~~~~~~~~~~~~~~^~
In file included from /build/source/src/FilterSyncRunner.cpp:35:
/nix/store/hdjr32qnmgqmysllvq6v5ds09mhvz5ja-gmic-3.2.0-dev/include/gmic.h:151:19: note: candidate: 'gmic_library::gmic_list<T>& gmic_library::gmic_list<T>::assign(unsigned int) [with T = float]'
  151 |     gmic_list<T>& assign(const unsigned int n);
      |                   ^~~~~~
/nix/store/hdjr32qnmgqmysllvq6v5ds09mhvz5ja-gmic-3.2.0-dev/include/gmic.h:151:19: note:   candidate expects 1 argument, 0 provided
/build/source/src/FilterSyncRunner.cpp:168:24: error: no matching function for call to 'gmic_library::gmic_list<char>::assign()'
  168 |     _imageNames->assign();
      |     ~~~~~~~~~~~~~~~~~~~^~
In file included from /build/source/src/FilterSyncRunner.cpp:35:
/nix/store/hdjr32qnmgqmysllvq6v5ds09mhvz5ja-gmic-3.2.0-dev/include/gmic.h:151:19: note: candidate: 'gmic_library::gmic_list<T>& gmic_library::gmic_list<T>::assign(unsigned int) [with T = char]'
  151 |     gmic_list<T>& assign(const unsigned int n);
      |                   ^~~~~~
/nix/store/hdjr32qnmgqmysllvq6v5ds09mhvz5ja-gmic-3.2.0-dev/include/gmic.h:151:19: note:   candidate expects 1 argument, 0 provided
ninja: build stopped: subcommand failed.
```

The gmic-lib API seems to have changed, this change may not have been reflected to gmic-qt yet.

**Comment by NinjaTrappeur** [comment]
What the hell!? https://github.com/GreycLab/gmic/commits/master

**Comment by NinjaTrappeur** [comment]
Upstream rebased the whole master branch last week and removed the commit messages: https://github.com/GreycLab/gmic/commits/master

This is weird. Provided gmic is a dependency of krita, gimp, darktable & other popular packages, we should probably warn the security team before merging that.

**Review by picnoir — CHANGES_REQUESTED** [review]
Let's not merge that until we hear back from the security team.

**Comment by jtojnar** [comment]
They rarely use commit messages out of laziness (I asked) and this is not
the first time they dropped the history.

**Comment by alyssais** [comment]
FTR, Matrix discussion starts [here](https://logs.nixos.dev/room/!NBBFPbiuttRgTqbrcY:nixos.org/?anchor=$Ec8AMRELMTEhY8JAZOfx0tENWBSMlaEyGjYIM2aNNz8&offset=90). (Hopefully that's a permalink.)

**Comment by jtojnar** [comment]
Asked about the nuking in https://github.com/GreycLab/gmic/issues/396 – no
reply, and commit messages in
https://github.com/GreycLab/gmic/pull/223#issuecomment-634730999

**Comment by NinjaTrappeur** [comment]
:+1: false alarm.

Let's open an issue on the `gmic-qt` tracker about the build failure and let's merge this.

**Comment by NinjaTrappeur** [comment]
https://github.com/c-koi/gmic-qt/issues/171

**Review by picnoir — APPROVED** [review]

**Comment by toastal** [comment]
I appreciate everyone's effort to double check that there wasn't a security issue. Good work.

**Comment by NinjaTrappeur** [comment]
Okay, I'll work with upstream to figure out the gmic-qt issue. Let's merge this to fix darktable in the meantime.

**Comment by mikelygee** [comment]
I'm not sure where this is at. I'm still unable to build gmic-qt on unstable:
```error: builder for '/nix/store/b5iql7a1ydaxnsx3p94i9r3i4n326cp9-gmic-qt-3.2.0.drv' failed with exit code 1;
       last 10 log lines:
       > /build/source/src/HeadlessProcessor.cpp:154:22: error: no matching function for call to 'gmic_library::gmic_list<float>::assign()'
       >   154 |   _gmicImages->assign();
       >       |   ~~~~~~~~~~~~~~~~~~~^~
       > In file included from /build/source/src/HeadlessProcessor.cpp:43:
       > /nix/store/g7iknz0kv5a999pn7dlyqsjqhaswcr5d-gmic-3.2.0-dev/include/gmic.h:151:19: note: candidate: 'gmic_library::gmic_list<T>& gmic_library::gmic_list<T>::assign(unsigned int) [with T = float]'
       >   151 |     gmic_list<T>& assign(const unsigned int n);
       >       |                   ^~~~~~
       > /nix/store/g7iknz0kv5a999pn7dlyqsjqhaswcr5d-gmic-3.2.0-dev/include/gmic.h:151:19: note:   candidate expects 1 argument, 0 provided
       > [62/96] Building CXX object CMakeFiles/gmic_qt.dir/src/KeypointList.cpp.o
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/b5iql7a1ydaxnsx3p94i9r3i4n326cp9-gmic-qt-3.2.0.drv'.
```

Is this the same issue?

**Pull request merged**
