### PR TITLE
pythonPackages.Markups: 3.1.1 -> 3.0.0

### PR DESCRIPTION
**Pull request by eduardosm**
###### Motivation for this change

Tests fail on 3.1.0 and 3.1.1

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by eduardosm** [comment]
Result of `nixpkgs-review pr 121017` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>python38Packages.Markups</li>
    <li>python39Packages.Markups</li>
    <li>retext</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 121017` at b4b45f31 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built successfully:</summary>
  <ul>
    <li>python38Packages.Markups</li>
    <li>python39Packages.Markups</li>
    <li>retext</li>
  </ul>
</details>

**Review by SuperSandro2000 — COMMENTED** [review]
How do the tests fail?

**Comment by eduardosm** [comment]
> How do the tests fail?

Build log: [markups-log.txt](https://github.com/NixOS/nixpkgs/files/6405535/markups-log.txt)

**Comment by SuperSandro2000** [comment]
We can just disable the 3 failing tests for now.

**Comment by eduardosm** [comment]
> We can just disable the 3 failing tests for now.

https://github.com/NixOS/nixpkgs/pull/122038

**Pull request closed without merging**
