### PR TITLE
teleport: 11.2.3 -> 11.3.4

### PR DESCRIPTION
**Pull request by justinas**
###### Description of changes

Updates to a new upstream version.

This also changes how we deal with the frontend assets. Previously, `gravitational/webassets` provided pre-compiled assets. This has been deprecated upstream. Instead, the frontend sources live in the main repo, and we build the assets from this source code (via Yarn/Webpack etc.), as the upstream does.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
build is failing on darwin.

**Comment by justinas** [comment]
```
$ g-build --config webpack.prod.config.js --progress --bail --output-path=../../../webassets/teleport/app
assets by status 2.82 KiB [cached] 3 assets2mginugin
./src/boot.tsx 1.22 KiB [built] [code generated] [1 error]
WARNING in configuration
The value 'hashed' for option 'optimization.moduleIds' is deprecated. Use 'deterministic' instead.
ERROR in ./src/boot.tsx 41:2
Module parse failed: Unexpected token (41:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| ReactDOM.render(
>   <Teleport history={history.original()} ctx={teleportContext} />,
|   document.getElementById('app')
| );
webpack 5.73.0 compiled with 1 error and 1 warning in 576 ms
✨  Done in 4.03s.
buildPhase completed in 51 seconds
installing
cp: cannot stat 'webassets/.': No such file or director
```

That's weird. I'm not sure why the loader wouldn't work on Darwin. I'll try to investigate, but I'll have to spin up a VM. If anyone has a real Darwin machine, and is willing to investigate, that would be great.

**Comment by justinas** [comment]
The loader issue does not occur on:
* NixOS (impure build: clone teleport, `yarn install`, `yarn build-ui-oss`)
* NixOS (derivation)
* Darwin (impure build)

The issue is present:
* Darwin (derivation)

Still not sure where the problem lies. The tree of `node_modules` installed by impure `yarn install --frozen-lockfile` vs the derivation seems identical.

**Comment by justinas** [comment]
Closed accidentally.

**Comment by NickCao** [comment]
pinging the maintainers to see if they can help: @sigma @tomberek @freezeboy

**Comment by justinas** [comment]
I have identified the issue. When building on Darwin, the `$PWD` inside the builder is e.g.: `/private/tmp/nix-build-teleport-webassets-11.3.2.drv-1/source`

In the Teleport webpack config, there is a line that excludes any file whose full path contains `assets` or `node_modules`. Not even a single component of the path (e.g. an exact match), but anything that contains that string.

https://github.com/gravitational/teleport/blob/b1a29ce99a00e1a4d41989d0abdbad5f97fb31c1/web/packages/build/webpack/webpack.base.js#L104

This means that even if a parent (grandparent, etc.) dir is named  "assets", "webassets", "assets-for-build" etc., these files are skipped over in the config.

I'll see if I can get the fix upstream, and if so, will update this PR when the fix is in the v11 branch. Otherwise, we can simply rename the `webassets` derivation, but that can potentially be a ticking timebomb until someone renames it again :sweat_smile: .

**Comment by justinas** [comment]
Updated to 11.3.4 which fixes the webpack issue, ofborg passed, should be good to go.

**Review by NickCao — APPROVED** [review]

**Pull request merged**
