### PR TITLE
KDE Frameworks 5.80 and Applications 20.12.3

### PR DESCRIPTION
**Pull request by ttuegel**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ttuegel** [comment]
Oops, I forgot to pull out my `aacgain` patch. :sweat_smile:

**Comment by samueldr** [comment]
Mixed this in with my work-in-progress plasma mobile branch and things still seem to work just as well as they did before hand. For all that's worth.

**Comment by peterhoeg** [comment]
Couple of things:

1. how about tagging the minimum required Qt version on a frameworks/plasma release level instead of having to tag the individual packages? I doubt a lot of people are building only the parts of KDE frameworks that happen to work with an older version of Qt. 

2. I've gone ahead and made a KDE team with everyone interested. Makes it easier to ping people with what's going on.

**Comment by ttuegel** [comment]
> I've gone ahead and made a KDE team with everyone interested. Makes it easier to ping people with what's going on.

@peterhoeg There was already @NixOS/qt-kde , but I forgot to tag them. We were each missing some people in the other team, so I added everyone from your list onto mine.


> how about tagging the minimum required Qt version on a frameworks/plasma release level instead of having to tag the individual packages?

I think this will break some packages, but it would be worth a try to see how many.

**Comment by peterhoeg** [comment]
> There was already @NixOS/qt-kde 

*Super* strange. I searched for kde in the teams list before creating it and it didn't show. GNOME did though. Very odd.
> 
> I think this will break some packages, but it would be worth a try to see how many.

Cool, I'll add that to the list.

**Comment by ttuegel** [comment]
> how about tagging the minimum required Qt version on a frameworks/plasma release level instead of having to tag the individual packages?

I implemented this, and it doesn't seem to have broken anything as all applications were already using the latest Qt version.

I was (finally) able to work around the breakage in `staging`, so I am testing this now.

**Comment by peterhoeg** [comment]
>   I implemented this, and it doesn't seem to have broken anything as all
>   applications were already using the latest Qt version.

FWIW, I had a look earlier and I would done it the same way that you did it. Can't we drop qtbase as well and simply propagate that the same way?

**Comment by ttuegel** [comment]
> Can't we drop qtbase as well and simply propagate that the same way?

Sorry, I'm not sure what you mean.

**Pull request merged**
