### PR TITLE
libvirt: 3.10.0 -> 4.1.0

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

```libvirt-4.1.0``` released

###### Things done

 * ```gnulib```: 0.1-357-gffe6467 -> 20180226
(https://github.com/NixOS/nixpkgs/pull/35684)
 * ```libvirt```: 3.10.0 -> 4.1.0
 * ```pythonPackages.libvirt```: 3.10.0 -> 4.1.0
 * ```perlPackages.SysVirt```: 1.2.19 -> 4.1.0
was not updated so long time as there was no assert as in ```pythonPackages.libvirt```, I spotted only because 1.2.19 has been removed from CPAN
* ```ocamlPackages.libvirt``` 0.6.1.4.2017-03-28-unstable -> 0.6.1.4.2017-11-08-unstable
to support ```ocaml``` newer than 4.01
 * ```build-on-bsd.patch``` removed
because the files mentioned in the patch do not exist in new ```libvirt```. It might cause build problems on Darwin, let's see what the CI bot will say.
 * paths to the derivations ```libvirtd``` expects to see on ```$PATH``` moved from ```nixos/libvirt``` module to the wrapper in ```libvirt``` derivation (they are more tied to the derivation internals, so the module can work with different ```libvirt``` versions without supporting table of ```libvirt``` versions and their needs)
 * ```virt-top```: 1.0.8 -> 2017-11-18-unstable
1.0.8 is broken after update of ```ocamlPackages.libvirt```; 1.0.8 is the latest tagged version released 5 years ago. After that only git HEAD.

### CODE REVIEW

**Comment by volth** [comment]
I you had ```3.10.0``` and just upgraded, you may see in logs
```
error : virQEMUCapsLoadCache:3972 : internal error: missing microcode version in QEMU capabilities cache
```
It seems to be benign and self-healing error.
The cache entries are rewritten and there will be no error on the next ```libvirt``` start.

**Comment by volth** [comment]
@GrahamcOfBorg build libvirt

**Comment by volth** [comment]
@FRidh @vcunat as 18.03 branch-off is delaying, it might have sense to merge

maybe https://github.com/NixOS/nixpkgs/pull/27678 too, it was scheduled for ```17.09```

**Comment by Mic92** [comment]
@GrahamcOfBorg build libvirt

**Comment by Mic92** [comment]
mhm libvirt on darwin worked before: https://hydra.nixos.org/build/70192320

**Comment by Mic92** [comment]
cc @nckx who provided the darwin fix last time for libvirt.

**Comment by volth** [comment]
We may return to build from the official tarball instead of git sources.
That works only for release versions (will not work for versions like ```X.X.XrcX``` because upstream does not make tarballs for them)

**Comment by nckx** [comment]
Did I? Oh... I'm not running Nix at the moment, so someone else will have to step in. Sorry.

**Comment by Mic92** [comment]
@nckx might have been a blind fix as well: https://github.com/NixOS/nixpkgs/issues/12139

**Comment by Mic92** [comment]
cc @vbgl regarding darwin

**Comment by volth** [comment]
@Mic92 can you run darwin CI again? (I added some logging and changed base from staging to master, to avoid collisions with other issues on staging)

**Comment by Mic92** [comment]
@GrahamcOfBorg build libvirt

**Comment by volth** [comment]
Hm, that "no configure script, doing nothing" seems strange as there is an implicit check for ./configure presence...

**Comment by volth** [comment]
@Mic92 build libvirt

**Comment by Mic92** [comment]
@GrahamcOfBorg build libvirt

**Comment by volth** [comment]
@GrahamcOfBorg build libvirt

**Comment by vcunat** [comment]
@GrahamcOfBorg build libvirt

**Comment by vbgl** [comment]
Just built on Darwin with `buildFromTarball = true;`. That went well.

**Comment by Mic92** [comment]
@vbgl can you make this the default and add this commit to this pull request?

**Comment by volth** [comment]
The last Darwin failure was about missing ```rpcgen```.
It might be more correct to add ```rpcgen``` to the dependencies

**Comment by volth** [comment]
@GrahamcOfBorg build libvirt

**Comment by volth** [comment]
@GrahamcOfBorg build libvirt

**Comment by volth** [comment]
@GrahamcOfBorg build libvirt

**Comment by Mic92** [comment]
Anything else left todo?

**Comment by volth** [comment]
Maybe to tell GrahamcOfBorg to perform a x86_64-darwin build

**Comment by Mic92** [comment]
@GrahamcOfBorg build libvirt

**Comment by volth** [comment]
ok then, let's merge

**Comment by Mic92** [comment]
@volth it might make sense to upgrade your borg membership to upgrade to `trusted-users`, so you also can build `darwin`.

**Pull request merged**
