### PR TITLE
top-level: Remove useless abstractions

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

1. `forcedNativePackages` is not needed if splicing and `buildPackages` is used correctly.

2. `wrapCCCross` is not needed now that `gcc-cross-wrapper` has been removed in lieu of a generalized `cc-wrapper`.

The vim change is good practice, and needed to get the perfect hash diff :).

###### Things done

All tested native and cross hashes are preserved. (!)

### CODE REVIEW

**Comment by edolstra** [comment]
Hm, what's the point of doing a pull request if you merge it yourself a minute later?

**Comment by Ericson2314** [comment]
I prefer doing that to just pushing directly to

1. Give people that watch a retroactive notification

2. Be able to label the change (e.g. cross-compilation) as I did above.

3. History is more uniform as people without privileges have to go through PR.

**Comment by orivej** [comment]
@Ericson2314 Was this comment obsoleted? https://github.com/NixOS/nixpkgs/blob/8d4ef09a6e2e8a160edac5b5eabe0a117ed4a44e/pkgs/top-level/all-packages.nix#L7398-L7403
How is the case of `pkgconfig` in `buildInputs` handled now?

**Comment by Ericson2314** [comment]
@orivej Manually :). I removed enough that the existing cross tests, a long with a bunch of stuff that I am personally building, are not affected by this.

**Comment by orivej** [comment]
All right, could you delete the comment then?

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nixpkgs/commit/64c3a2e98a9521545690664cfdeb714228c6fabc here you go!

**Pull request merged**
