### PR TITLE
openmpi: 4.0.0 -> 4.0.1

### PR DESCRIPTION
**Pull request by markuskowa**
###### Motivation for this change
regular update

Changelog: https://github.com/open-mpi/ompi/blob/v4.0.x/NEWS

###### Things done
* remove upstream patch

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by markuskowa** [comment]
@GrahamcOfBorg build scalapack 
@GrahamcOfBorg build python3Packages.mpi4py
@GrahamcOfBorg build lammps-mpi
@GrahamcOfBorg build dl-poly-classic-mpi
@GrahamcOfBorg build siesta-mpi

**Comment by markuskowa** [comment]
`mpi4py` fails again due to outdated symbols. 
`openmpi` now fails on darwin:
```
server/pmix_server_ops.c:3432:19: error: use of undeclared identifier 'CLOCK_MONOTONIC'
    clock_gettime(CLOCK_MONOTONIC, &tp);
```

**Comment by FRidh** [comment]
status?

**Comment by markuskowa** [comment]
@FRidh I did not have time to work on this lately. The main blocker here is the build failure on darwin (which I can not really debug). I may put this on hold until 4.0.2 is out, which hopefully solves the darwin problem.

**Comment by orivej** [comment]
Darwin should have `CLOCK_MONOTONIC` since d69cc779b520ea74a5b52fa5691f3f8fd7fe9cf3 which updates its Libc package from 1082.50.1 to 1158.50.2 (https://reviews.llvm.org/D27429).

**Comment by orivej** [comment]
@GrahamcOfBorg build python3Packages.mpi4py

**Review by orivej — APPROVED** [review]
I have checked on a mac that with this PR on top of the current nixpkgs `python3.pkgs.mpi4py` builds (and passes its tests).

**Comment by markuskowa** [comment]
Did a rebase (unfortunatley the ofborg darwin builders seem to have a general issue right now).
@orivej thanks for clearing up the darwin question. With that the PR is ready to be merged.

**Pull request merged**
