### PR TITLE
nixos/libinput: Make every option optional

### LINKED ISSUE #75007: services.xserver.libinput: Allow configuration by input type
**Describe the bug**
PR https://github.com/NixOS/nixpkgs/pull/73785 broke my setup, since it enabled natural scrolling on my mouse when I only wanted it on touchpad. This was my config before:

```nix
{
  xserver = {
    # Enable libinput.
    libinput = {
      enable = true;
      naturalScrolling = true;
    };
  };
}
```

Since now natural scrolling is applied to all devices, I needed to change my config. To fix it, I had to add the following section in my `/etc/nixos/configuration.nix` file:

```nix
{
  xserver = {
    # Enable libinput.
    libinput = {
      enable = true;
    };

    # Set extra config to libinput devices
    extraConfig = ''
      Section "InputClass"
        Identifier "touchpad"
        Driver "libinput"
        MatchIsTouchpad "on"
        Option "NaturalScrolling" "true"
      EndSection
    '';
  };
}
```
The solution above is not exactly good, it is verbose, I lose the type checking from Nix, and also I am configuring libinput related things on `services.xserver` instead of `services.xserver.input`.

However, the change in the PR actually makes sense, since it makes more sense to apply the configuration to any libinput device instead of only in touchpads. There should be a better solution, though.

My proposal would be to have something like this:

```nix
{
  libinput = {
    enable = true;
    touchpad = {
      # Enable naturalScrolling in touchpads
      naturalScrolling = true;
    };
    touchpad = {
      # Only for mouse, set accel profile to flat
      accelProfile = "flat";
    };
  };
}
```
This way, we have much more flexibility, since we can either set a specific configuration to some specific type of device. For even more flexibility, we could support global options too, something like this:

```nix
{
  libinput = {
    enable = true;
    # Disable naturalScrolling globally
    naturalScrolling = false;
    touchpad = {
      # But enable it in touchpads
      naturalScrolling = true;
    };
    touchpad = {
      # Only for mouse, set accel profile to flat
      accelProfile = "flat";
    };
  };
}
```

This would allow us to maintain backwards compatibility, however I don't know if having a global option is really possible/a good idea.

**To Reproduce**
1. Using `xserver.libinput`, I can't set some configuration that is only applied in touchpads and not mouses, for example

**Expected behavior**
It would be interesting to have some way to apply libinput configuration to specific device types.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.1, NixOS, 19.09.1484.84586a4514d (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.1484.84586a4514d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module:
- services.xserver.libinput
```

### PR DESCRIPTION
**Pull request by thiagokokada**
###### Motivation for this change

The libinput module nowadays set some options as optional (i.e.: accepts null) and other options as required (i.e.: if not set it will be set with a default).

However, this module, since PR #73785, applies to all input devices. And this is an issue since many of the options here only make sense to touchpad (for example, NaturalScrolling). Worse than that, once any option is in this configuration it cannot be overriden by any of the existing mechanisms to override, like:

- `services.xserver.extraConfig`
- `services.xserver.inputClassSections`

The only one that works is `services.xserver.libinput.additionalOptions`, but this one does not support applying options to many targets. You can set `additionalOptions` with `MatchIsTouchpad "on"`, for example, but now you cannot apply options in other target unless you use one of the options above.

So what this PR does is convert every option to optional, and also setting to `null` any option that is already default in libinput itself. This way, most options will be available to override using
`services.xserver.extraConfig` or `services.xserver.inputClassSections`.

Closes https://github.com/NixOS/nixpkgs/issues/75007.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thiagokokada** [comment]
I don't have a clue how to test this, but since the changes are so minimal I thought that opening a PR as-is shouldn't hurt.

**Comment by thiagokokada** [comment]
Tagging @worldofpeace since its is the author of #73785.

**Comment by thiagokokada** [comment]
Also, I don't think this is the best solution. Something better would be to have separate sections for each type of input class in `libinput`, so we could have something like:

```nix
server.libinput.touchpad = {
  naturallScrolling = true;
};
server.libinput.mouse = {
  accelProfile = "flat";
};
```

If someone things that the above is a good idea, I can give it a try, but like I said above I don't know how I could test a module.

**Comment by thiagokokada** [comment]
Marking @zackelan @pmyjavec @karthikiyengar, since they commented in issue #75007 and maybe can help review/validate this.

**Comment by thiagokokada** [comment]
So I applied the changes (using `sudo nixos-rebuild -I nixpkgs=$NIXPKGS_LOCAL switch`), and made the following changes in my `/etc/nixos/configuration.nix`:

```nix
{
  services = {
    xserver = {
      enable = true;
      libinput.enable = true;
      inputClassSections = [
        ''
          Identifier "mouse"
          MatchIsPointer "on"
          Option "AccelProfile" "flat"
        ''
        ''
          Identifier "touchpad"
          MatchIsTouchpad "on"
          Option "NaturalScrolling" "on"
          Option "Tapping" "on"
          Option "TappingButtonMap" "lmr"
        ''
      ];
    };
  };
}
```

This seems to work, I have natural scrolling enabled in my touchpad but not in my mouse. Just to make sure that all devices are running with `libinput` and not `evdev`, I did a `cat /var/log/X.0.log | grep libinput` and this is the result:

```
[  2846.661] (II) Using input driver 'libinput' for 'Power Button'
[  2846.693] (II) Using input driver 'libinput' for 'Video Bus'
[  2846.715] (II) Using input driver 'libinput' for 'Video Bus'
[  2846.735] (II) Using input driver 'libinput' for 'Power Button'
[  2846.754] (II) Using input driver 'libinput' for 'Sleep Button'
[  2846.775] (II) Using input driver 'libinput' for 'Integrated_Webcam_HD: Integrate'
[  2846.803] (II) Using input driver 'libinput' for 'DLL07BF:01 06CB:7A13 Mouse'
[  2846.834] (II) Using input driver 'libinput' for 'DLL07BF:01 06CB:7A13 Touchpad'
[  2846.871] (II) Using input driver 'libinput' for 'Corsair Raptor HS40'
[  2846.905] (II) Using input driver 'libinput' for 'Logitech MX518 Gaming Mouse'
[  2847.047] (II) Using input driver 'libinput' for 'Logitech MX518 Gaming Mouse Keyboard'
[  2847.076] (II) Using input driver 'libinput' for 'Logitech MX518 Gaming Mouse Consumer Control'
[  2847.101] (II) Using input driver 'libinput' for 'Logitech MX518 Gaming Mouse System Control'
[  2847.123] (II) Using input driver 'libinput' for 'Logitech Gaming Keyboard G610'
[  2847.151] (II) Using input driver 'libinput' for 'Logitech Gaming Keyboard G610 Keyboard'
[  2847.172] (II) Using input driver 'libinput' for 'Logitech Gaming Keyboard G610 Consumer Control'
[  2847.203] (II) Using input driver 'libinput' for 'Intel HID events'
[  2847.217] (II) Using input driver 'libinput' for 'Intel HID 5 button array'
[  2847.230] (II) Using input driver 'libinput' for 'Dell WMI hotkeys'
[  2847.254] (II) Using input driver 'libinput' for 'AT Translated Set 2 keyboard'
[  2847.270] (II) Using input driver 'libinput' for 'PS/2 Synaptics TouchPad'
[  2847.325] (II) Using input driver 'libinput' for 'Logitech MX518 Gaming Mouse Consumer Control'
```

**Comment by kisik21** [comment]
@thiagokokada I have a question! :sparkles: do you know how this could affect Wayland compositors using libinput, e.g. sway? Can you explain how can I maybe test it on my system, what settings could I try to tweak to see if there's a useful difference in behavior there, or maybe bugs?

**Comment by thiagokokada** [comment]
> do you know how this could affect Wayland compositors using libinput, e.g. sway?

@kisik21 Shouldn't affect Wayland, since Wayland doesn't use Xorg.conf AFAIK. SwayWM for example uses its own completely custom configuration file for input devices: https://github.com/swaywm/sway/wiki#input-configuration.

> Can you explain how can I maybe test it on my system, what settings could I try to tweak to see if there's a useful difference in behavior there, or maybe bugs?

Well, the easiest way I found to test modules is something like this:

```nix
{
let
  libinputModuleRefactor = fetchTarball {
    url = "https://github.com/thiagokokada/nixpkgs/archive/a27a2ff9a3605a9ddc740a3c3fa3d51392fde040.tar.gz";
    sha256 = "..."; # get the correct SHA for commit
  };
in {
  imports = [
    "${libinputModuleRefactor}/nixos/modules/services/x11/hardware/libinput.nix"
  ];

  disabledModules = [
    "services/x11/hardware/libinput.nix"
  ];

  xserver.libinput.enable = true;
  # Set some custom X config here so you can test the changes too.
  # This comment may help: https://github.com/NixOS/nixpkgs/pull/107676#issuecomment-752844528
}
```

Maybe there is someway easier to test this (for example, I can try to write some tests if this would make the review easier), but this is what I found the easiest way to test it.

**Comment by thiagokokada** [comment]
For what behavior you're testing to see if this fix it, try this:

```nix
{
  services = {
    xserver = {
      enable = true;
      libinput.enable = true;
      inputClassSections = [
        ''
          Identifier "mouse"
          MatchIsPointer "on"
          Option "AccelProfile" "flat"
        ''
        ''
          Identifier "touchpad"
          MatchIsTouchpad "on"
          Option "NaturalScrolling" "on"
        ''
      ];
    };
  };
}
```

Now this is slightly trick to test since you need a notebook with a touchpad and a external mouse. But what will happen in `master` is that both mouse and touchpad will not have natural scrolling (https://github.com/NixOS/nixpkgs/pull/107676/files#diff-27164ac6e7f2a68c13050fa6e230c23671056d1357c534e79bb1d2969110bddeL103), even if you're explicitly overriding there. Also, mouse will not have the accel profile flat, instead using the default: https://github.com/NixOS/nixpkgs/pull/107676/files#diff-27164ac6e7f2a68c13050fa6e230c23671056d1357c534e79bb1d2969110bddeL28.

Now with my branch, it should work as expected: touchpad will have natural scrolling and mouse will have accel profile flat. More details can be seen in https://github.com/NixOS/nixpkgs/issues/75007.

**Comment by thiagokokada** [comment]
I created another possible solution for #75007: #108909. It is a more elegant solution but involves more changes.

I think both solutions are fine, so I will keep both PRs open and after one is merged I will close the other one.

**Comment by thiagokokada** [comment]
I will close this PR in favor of #108909, because it seems a better solution.

**Pull request closed without merging**
