### PR TITLE
schildichat-{web,desktop}: 1.10.12-sc.1 -> 1.11.4-sc.1

### PR DESCRIPTION
**Pull request by yu-re-ka**
###### Description of changes

**Beware, going to this version and then back to an older one (electron <19) will wipe your session data!**

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yu-re-ka** [comment]
@ofborg build schildichat-desktop

**Review by yayayayaka — APPROVED** [review]
Built and deployed schildichat-desktop on x84_64-linux for manual testing.

Logging in to my matrix server and sending a message works as well as emoji key verification and encrypted message search. LGTM!

**Comment by onny** [comment]
Thank you for this fix! Could you change `meta = {` to `meta = with lib; {` and remove the `lib`-prefixes below? Otherwise looks good to me.
Not sure about 
```
   export VERSION=${version}
    node_modules/.bin/webpack --progress --mode production
    yarn build:res --offline
    yarn build:module_system --offline
    yarn build:bundle --offline
```
But I guess that's okay :)

**Comment by yu-re-ka** [comment]
> Thank you for this fix! Could you change meta = { to meta = with lib; { and remove the lib-prefixes below? Otherwise looks good to me.

Is it looking good now?

**Pull request merged**
