### PR TITLE
quartz-wm: fix building

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change

The quartz-wm was relying on impurities to build correctly. These changes seem to have fixed it.

### CODE REVIEW

**Comment by c0bw3b** [comment]
The source URL is now a permanent redirect to `https://dl.bintray.com/xquartz/legacy-downloads/src/quartz-wm-1.3.1.tar.xz`

**Comment by LnL7** [comment]
@GrahamcOfBorg build quartz-wm

**Review by LnL7 — APPROVED** [review]

**Comment by LnL7** [comment]
Thanks for the ping

**Pull request merged**
