### PR TITLE
discord: 0.0.13 -> 0.0.14

### PR DESCRIPTION
**Pull request by reedrw**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jshcmpbll — APPROVED** [review]
LGTM! Thanks for getting this PR in

**Review by jonringer — APPROVED** [review]
LGTM

I Just came up with the same diff

**Comment by ronthecookie** [comment]
Well, that got merged very quickly. (:

**Comment by jonringer** [comment]
backported in 0120f5e5b58

**Comment by baracoder** [comment]
Until it is in unstable channel:
```
nix-env -iA discord -f https://github.com/reedrw/nixpkgs/archive/refs/heads/update-discord.tar.gz
```

**Comment by SuperSandro2000** [comment]
> nix-env -iA discord -f https://github.com/NixOS/nixpkgs/archive/refs/heads/master.tar.gz

is preferred.

**Comment by zyansheep** [comment]
How can I install the latest version of discord if I have a system flake that tracks unstable? (and it's not in unstable yet).

**Comment by jonringer** [comment]
there's been a channel release since this was merged, you should be able to just update your flake

**Comment by zyansheep** [comment]
I just realized that there was a random profile that was pinning version 0.0.12 and it wasn't finding the system package :facepalm:

**Pull request merged**
