### PR TITLE
mupdf: 1.8 -> 1.9

### PR DESCRIPTION
**Pull request by vrthra**
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Updates mupdf, and libmupdf.so

### CODE REVIEW

**Comment by vrthra** [comment]
There are two main changes I would like feedback on

* The `my_soname_js_none` so file does not get created currently. So I have removed the logic for it.
* The shared library version was `1.3` which did not seem to be synced to the version of `mupdf`. I have set it to the version of `mupdf`.

Finally, `mupdf` no longer provides a shared library. So should we carry `libmupdf.so` at all?

**Comment by joachifm** [comment]
cc maintainer @viric

**Comment by vrthra** [comment]
For Zathura, I found a patch in Aurlinx to fix the changed API. I have kept the patch as it is, since I was unsure the correct way to add a patch from outside the project.

**Comment by joachifm** [comment]
If at all possible, prefer fetching patches instead of committing them to the nixpkgs repository. Typically, you'll see constructs like
```nix
stdenv.mkDerivation rec {
  # ...
  patches = [ (fetchurl { url = "https://example.com/awesome.patch"; sha256 = ""; }) ];
}
```

**Comment by abbradar** [comment]
It's better to use `fetchpatch` -- it normalizes a patch -- removes dates and such, so when a patch is actually autogenerated (for example if you take it from GitHub: https://github.com/NixOS/nixpkgs/pull/16160.patch) it still won't be non-deterministic after the process.

**Comment by vrthra** [comment]
@abbradar @joachifm I have updated the mu-pdf patch for zathura to use `fetchpatch`

**Comment by abbradar** [comment]
LGTM, thanks! I think Travis failure is because something is mounted `noexec` when it shouldn't be (I saw errors like this lately). I'm very pressed for free time now, so if someone beats me to testing and merging this I'll be glad.

**Comment by abbradar** [comment]
@zimbatm Thanks ^_^

**Pull request merged**
