### PR TITLE
[Demo] splice.nix: hybrid implementation of Gentoo-like use-flags

### PR DESCRIPTION
**Pull request by oxij**
See https://github.com/NixOS/nixpkgs/pull/56110#issuecomment-466107720.

### CODE REVIEW

**Comment by grahamc** [comment]
Sounds like an _actual_ RFC might be in order.

**Comment by oxij** [comment]
Sure, but Code > Literature. Let's explore all alternatives first.

**Comment by danbst** [comment]
wow, such clean, much use! No patches were required to make mpv example work.

**Comment by 7c6f434c** [comment]
@oxij Writing literature would hopefully clarify the requirement trade-offs, and without a few decisions on trade-offs the enumeration space for code is even larger. Requirements > Generic Literature.

… But this version is indeed nice.

**Comment by oxij** [comment]
Closed in favor of #56227.

**Comment by oxij** [comment]
@7c6f434c I think RFCs make sense for something non-trivial, massive, or controversial. This and #56227 are neither.

**Pull request closed without merging**
