### PR TITLE
paperless-ngx: Upgrade tesseract; python3Packages.ocrmypdf: Upgrade tesseract

### PR DESCRIPTION
**Pull request by mweinelt**
The documentation of paperless-ngx mentions it supports versions greater than or equal 4.0.

The NixOS test is passing with this change.

###### Description of changes

I have a document that when running it through tesseract consumes > 4GB memory and triggers the OOM killer. I hope updating tesseract will provide fixes for such scenarios.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gador** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 192249` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages marked as broken and skipped:
</summary>
<ul>
<li>paperless</li>
<li>paperless-ng</li>
</ul>
</details>
<details>
<summary>
1 package built:
</summary>
<ul>
<li>paperless-ngx</li>
</ul>
</details>

**Review by gador — APPROVED** [review]
LGTM. I haven't done any memory tests, though

**Comment by mweinelt** [comment]
I tried the OCR with tesseract locally and it constrained itself to ~2.2GB on my desktop machine where it would otherwise have plenty of memory.

**Comment by gador** [comment]
I just check the build log of the docker image. That still uses the `4` version of tesseract. I don't see any issues with using the newer version of tesseract though. Their [Release Notes](https://tesseract-ocr.github.io/tessdoc/ReleaseNotes.html#tesseract-release-notes-nov-30-2021---v500) don't mention any breaking changes, either

**Comment by mweinelt** [comment]
Does not fix out of memory issues with 4GB supplied to the VM, but probably still a worthwhile upgrade.

**Comment by mweinelt** [comment]
Adding the bump for unpaper 7.0.0 into this PR so we can test these changes together.

**Comment by gador** [comment]
There is an old discussion about higher memory consumption and OOM errors [here](https://github.com/paperless-ngx/paperless-ngx/issues/768). It's probably not easy to debug. I haven't noticed it, either.

Does it occur with every document? Or does it correlate with its size and/or amount of text?

**Comment by mweinelt** [comment]
It is not particularly large and otherwise shouldn't be too fancy. I think it was produced by our old Brother 8460N MFC, which we have replaced in the meantime. Not sure if we still have the original document though.

```
❯ pdfinfo 0452_001-1.pdf
Producer:        cairo 1.16.0 (https://cairographics.org)
CreationDate:    Sun Jan 16 20:51:08 2022 CET
Custom Metadata: no
Metadata Stream: no
Tagged:          no
UserProperties:  no
Suspects:        no
Form:            none
JavaScript:      no
Pages:           1
Encrypted:       no
Page size:       595.2 x 841.44 pts (A4)
Page rot:        0
File size:       414993 bytes
Optimized:       no
PDF version:     1.7
```

```
❯ exiftool -a -G1 0452_001-1.pdf
[ExifTool]      ExifTool Version Number         : 12.39
[System]        File Name                       : 0452_001-1.pdf
[System]        Directory                       : .
[System]        File Size                       : 405 KiB
[System]        File Modification Date/Time     : 2022:09:21 14:27:01+02:00
[System]        File Access Date/Time           : 2022:09:21 17:55:44+02:00
[System]        File Inode Change Date/Time     : 2022:09:21 14:27:01+02:00
[System]        File Permissions                : -rw-r--r--
[File]          File Type                       : PDF
[File]          File Type Extension             : pdf
[File]          MIME Type                       : application/pdf
[PDF]           PDF Version                     : 1.7
[PDF]           Linearized                      : No
[PDF]           Page Count                      : 1
[PDF]           Producer                        : cairo 1.16.0 (https://cairographics.org)
[PDF]           Create Date                     : 2022:01:16 20:51:08+01:00
```

**Comment by gador** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 192249` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages marked as broken and skipped:
</summary>
<ul>
<li>paperless</li>
<li>paperless-ng</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>gscan2pdf: <a href="https://termbin.com/iuq1">plain log</a></li>
  </ul>
</details>
<details>
<summary>
5 packages built:
</summary>
<ul>
<li>ocrmypdf (python310Packages.ocrmypdf)</li>
<li>paperless-ngx</li>
<li>pdfsandwich</li>
<li>python39Packages.ocrmypdf</li>
<li>unpaper</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
pdfsandwich:
<details>

got build log for '/nix/store/01y405kq8ms73l191wakpwfcfvw0nr5q-pdfsandwich-0.1.7' from 'daemon'
When evaluating attribute ‘pdfsandwich’:
warning: unclear-gpl
`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/tools/typesetting/pdfsandwich/default.nix:27:5:

```
   |
27 |     license = licenses.gpl2;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
unpaper:
<details>

got build log for '/nix/store/ga8f7shb6xy7pnivr4nzpvlmvwlsl95d-unpaper-7.0.0' from 'daemon'
When evaluating attribute ‘unpaper’:
warning: unclear-gpl
`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/tools/graphics/unpaper/default.nix:54:5:

```
   |
54 |     license = licenses.gpl2;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
</details>

**Comment by mweinelt** [comment]
Test issues reported "upstream" at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1020458.

**Comment by lukegb** [comment]
unpaper should be marked gpl2Only, I think.

**Comment by mweinelt** [comment]
Mostly gpl2Only with bits and pieces in MIT and BSD0.

```
AUTHORS
3:# SPDX-License-Identifier: GPL-2.0-only

README.md
4:SPDX-License-Identifier: GPL-2.0-only

NEWS
3:# SPDX-License-Identifier: GPL-2.0-only

constants.h
3:// SPDX-License-Identifier: GPL-2.0-only

file.c
5:// SPDX-License-Identifier: GPL-2.0-only

imageprocess.c
6:// SPDX-License-Identifier: GPL-2.0-only

doc/conf.py
3:# SPDX-License-Identifier: MIT

doc/basic-concepts.md
4:SPDX-License-Identifier: GPL-2.0-only

doc/file-formats.md
4:SPDX-License-Identifier: GPL-2.0-only

doc/image-processing.md
4:SPDX-License-Identifier: GPL-2.0-only

doc/unpaper.1.rst
3:.. SPDX-License-Identifier: GPL-2.0-only

imageprocess.h
5:// SPDX-License-Identifier: GPL-2.0-only

meson.build
3:# SPDX-License-Identifier: MIT

parse.c
5:// SPDX-License-Identifier: GPL-2.0-only

parse.h
5:// SPDX-License-Identifier: GPL-2.0-only

doc/img/multiple-input-files.png.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/mask-scan.png.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/mask-scan-detail1.png.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/layout-templates.png.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/blurfilter.png.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/blackfilter-detail.png.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/blackfilter.png.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/blurfilter-detail.png.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/border-align.png.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/border-scan.png.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/deskew-detail1.png.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/deskew.png.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/deskew-detail2.png.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/documentation.odg.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/input-pages.png.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/mask-center.png.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/mask-scan-detail2.png.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/multiple-output-files.png.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/noisefilter.png.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/output-pages.png.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/processing-order.png.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/sheetspages.png.license
3:SPDX-License-Identifier: GPL-2.0-only

doc/img/standard-deviation.png.license
3:SPDX-License-Identifier: GPL-2.0-only

tools.c
5:// SPDX-License-Identifier: GPL-2.0-only

tools.h
5:// SPDX-License-Identifier: GPL-2.0-only

version.h.in
3: * SPDX-License-Identifier: 0BSD

unpaper.h
5:// SPDX-License-Identifier: GPL-2.0-only

unpaper.c
5:// SPDX-License-Identifier: GPL-2.0-only

tests/unpaper_tests.py
3:# SPDX-License-Identifier: GPL-2.0-only
4:# SPDX-License-Identifier: MIT

tests/source_images/imgsrc003.png.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/golden_images/goldenE1-01.pbm.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/golden_images/goldenC2.pbm.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/golden_images/goldenB2.ppm.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/golden_images/goldenB1.ppm.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/golden_images/goldenA1.pbm.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/golden_images/goldenB3.ppm.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/golden_images/goldenC1.pbm.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/golden_images/goldenC3.pbm.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/golden_images/goldenD1.ppm.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/golden_images/goldenD2.ppm.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/golden_images/goldenD3.ppm.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/golden_images/goldenE1-02.pbm.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/source_images/imgsrc001.png.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/source_images/imgsrc002.png.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/golden_images/goldenE1-04.pbm.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/golden_images/goldenE1-05.pbm.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/source_images/imgsrc004.png.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/golden_images/goldenE1-06.pbm.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/source_images/imgsrc005.png.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/golden_images/goldenF.pbm.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/source_images/imgsrcE001.png.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/source_images/imgsrcE002.png.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/source_images/imgsrcE003.png.license
3:SPDX-License-Identifier: GPL-2.0-only

tests/golden_images/goldenE1-03.pbm.license
3:SPDX-License-Identifier: GPL-2.0-only

**Comment by gador** [comment]
@mweinelt could you provide an example pdf, so I can test and possibly reproduce?

**Comment by mweinelt** [comment]
Provided privately due to privacy concerns.

**Comment by gador** [comment]
@mweinelt thanks for providing the test file.

A little update:
- Consuming this file with the docker image of paperless 1.8.0 will result in a OOM situation with 8GB limit
- Consuming this file with the docker image of paperless 1.9.0-beta.rc3 will *not* result in OOM. Maximum memory usage is around 5,7 GB
- Doing an OCR with `ocrmypdf` for just this testfile results in a memory usage of about 5,7 GB
- Doing an OCR on another scanned test page (different scanner, also 1 page only) results in only 1GB of memory usage with `ocrmypdf` 

For now I suppose `ocrmypdf` has an issue with this particular PDF. Also an update to the newest version of paperless will reduce the memory footprint.

I'll do some more tests, though

**Comment by cole-h** [comment]
@ofborg eval

**Comment by mweinelt** [comment]
Moving the unpaper changes out of this tree, because they break gscan2pdf and there is no upstream responset yet.

**Pull request merged**
