### PR TITLE
 pgcli: 1.11.0 -> 2.0.0

### PR DESCRIPTION
**Pull request by marsam**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ma27** [comment]
Currently running `nix-review` on your branch to see  if anything else explicitly breaks.

**Review by Ma27 — CHANGES_REQUESTED** [review]
Especially major bumps of Python modules in `nixpkgs` are unfortunately quite error-prone.
I identified the following packages that seem to break with `prompt_toolkit` bumped to 2.x:

* `pkgs.haxor-news`
* `pkgs.pythonPackages.ptpython`
* `pkgs.xonsh` (`pygments` is missing, this **may** be happening because of the removed `pygments` in `prompt_tools`, but in that case it's certainly an issue of `xonsh`)
* `pkgs.python3Packages.jupyterhub` (same as above)

It would be great if you could fix these packages (or provide `pythonPackages.prompt_tools` and `pythonPackages.prompt_tools2` temporarily until all affected packages support v2).

Feel free to ping me if I can help you :)

**Comment by marsam** [comment]
@Ma27 thanks for your review, I didn't know about nix-review. I believe I've fixed the errors
+ xonsh: 0.6.8 -> 0.8.3 : tested on NixOS and Darwin
+ pythonPackages.ptpython: 0.41 -> 2.0.4 : tested on NixOS and Darwin

also ipython5 and ipython6 only work with prompt_toolkit 1.x and don't have plans to upgrade to prompt_toolkit 2. ipython7 (not yet in nixpkgs) works prompt_toolkit 2.

**Comment by Ma27** [comment]
So, I had a second look at your PR. As far as I can tell the main intention is still to bump `pgcli` to 2.0, right? In this case I'd default `prompt_toolkit` to v1 for now and wait until all applications moved (it seems as there's a bit to do when performing the upgrade in a Python application) and update the expression later. Actually doing the upgrade for `prompt_tools` may take some extra-effort. With this idea you'd only have two (re)builds: the build of `prompt_tools` and the rebuild of `pgcli`.

Additionally, I observed that the sandboxed build of `xonsh` is broken on your branch as you enabled the testcases `test_printname` and `test_sourcefile`. They internally reference `/usr/bin/env` and seem to rely on an impure state of a system :)

**Comment by marsam** [comment]
Sound reasonable. I've set the default prompt_toolkit to v1, and tested xonsh, ptpython with sandboxed builds.
I'm keeping https://github.com/NixOS/nixpkgs/pull/49853/commits/ec5ba05f888c0ab9bc12b6942aa84d558aca32c1 and https://github.com/NixOS/nixpkgs/pull/49853/commits/27241fe2c1621009989947e6daed77e32dffdda1 in this PR, but if you want it I can create separate PRs for them

**Review by Ma27 — APPROVED** [review]
I pushed onto your branch to disable remaining impure tests you seem to have missed (they are already disabled on `master`).

I checked the functionality of `xonsh`, `ptpython` and `pgcli` locally, all of them remained functional.
By default `prompt_tools` is still v1 ATM, so no further breakage is expected (confirmed by running `nix-review` locally). When all of the remaining applications are moved, v1 can be dropped entirely.

And thanks a lot for your effort of course :+1:

**Pull request merged**
