### PR TITLE
python3Packages.emoji: 1.4.1 -> 1.4.2

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 1.4.2

Change log: https://github.com/carpedm20/emoji/releases/tag/v.1.4.2

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 132298` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>home-assistant</li>
    <li>octoprint</li>
  </ul>
</details>
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>ntfy</li>
    <li>opsdroid</li>
    <li>python38Packages.emoji</li>
    <li>python38Packages.locationsharinglib</li>
    <li>python39Packages.emoji</li>
    <li>python39Packages.locationsharinglib</li>
    <li>terraform-compliance</li>
  </ul>
</details>

**Comment by davidak** [comment]
There are failed builds. Not sure if caused by this change. Otherwise looks good.

```
builder for '/nix/store/s4yv1yfs1nml4s4mhp7rkbsggpc48bkq-python3.9-OctoPrint-1.5.3.drv' failed with exit code 1; last 10 log lines:
  installing
  Executing pipInstallPhase
  /build/source/dist /build/source
  Processing ./OctoPrint-1.5.3-py2.py3-none-any.whl
  Requirement already satisfied: sarge==0.1.5post0 in /nix/store/x26x8vhr9266dhad00z68bsqbgg7xkjm-python3.9-sarge-0.1.5.post0/lib/python3.9/site-packages (from OctoPrint==1.5.3) (0.1.5.post0)
  Requirement already satisfied: psutil<6,>=5.7 in /nix/store/hnm6x0cw7m3nnsr2m3q0rlwk365ci9b4-python3.9-psutil-5.8.0/lib/python3.9/site-packages (from OctoPrint==1.5.3) (5.8.0)
  Requirement already satisfied: rsa==4.0 in /nix/store/d2vy701jmp1jpija5m2ccrkzinbq0ry2-python3.9-rsa-4.0/lib/python3.9/site-packages (from OctoPrint==1.5.3) (4.0)
  Requirement already satisfied: frozendict<2,>=1.2 in /nix/store/0jc6zwzjjrjimcmsrv5vccppcl6f4x14-python3.9-frozendict-1.2/lib/python3.9/site-packages (from OctoPrint==1.5.3) (1.2)
  ERROR: Could not find a version that satisfies the requirement markupsafe<2.0,>=1.1 (from octoprint) (from versions: none)
  ERROR: No matching distribution found for markupsafe<2.0,>=1.1
builder for '/nix/store/q9zl7i5lj9vwgzlpa8z2vgd3c5fzi8ag-homeassistant-2021.7.4.drv' failed with exit code 1; last 10 log lines:
      Call to deprecated create function Descriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
  DeprecationWarning:
      Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
  DeprecationWarning:
      Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
  DeprecationWarning:
      Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
  DeprecationWarning:
      Call to deprecated create function Descriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
  DEBUG:pyvera:DEBUG logging is ON
cannot build derivation '/nix/store/r1v7iwzmygy491sg6yiab1q6958lrqfn-review-shell.drv': 2 dependencies couldn't be built
error: build of '/nix/store/r1v7iwzmygy491sg6yiab1q6958lrqfn-review-shell.drv' failed
```

**Comment by siraben** [comment]
home-assistant and octoprint are already failing on master
```ShellSession
$ nix run nixpkgs#hydra-check octoprint
Build Status for nixpkgs.octoprint.x86_64-linux on unstable
✖ (Failed) OctoPrint-1.5.3 from 2021-08-01 - https://hydra.nixos.org/build/149346040

Last Builds:
✖ (Failed) OctoPrint-1.5.3 from 2021-07-30 - https://hydra.nixos.org/build/149015171
✖ (Failed) OctoPrint-1.5.3 from 2021-07-23 - https://hydra.nixos.org/build/148447632
✖ (Failed) OctoPrint-1.5.3 from 2021-07-22 - https://hydra.nixos.org/build/148284917
✖ (Failed) OctoPrint-1.5.3 from 2021-07-20 - https://hydra.nixos.org/build/148112617
✖ (Failed) OctoPrint-1.5.3 from 2021-07-15 - https://hydra.nixos.org/build/147792655
✖ (Failed) OctoPrint-1.5.3 from 2021-07-10 - https://hydra.nixos.org/build/147541856
✖ (Failed) OctoPrint-1.5.3 from 2021-07-09 - https://hydra.nixos.org/build/147465665
✖ (Failed) OctoPrint-1.5.3 from 2021-07-06 - https://hydra.nixos.org/build/147237616
✖ (Failed) OctoPrint-1.5.3 from 2021-07-04 - https://hydra.nixos.org/build/146996648
$ nix run nixpkgs#hydra-check home-assistant
Build Status for nixpkgs.home-assistant.x86_64-linux on unstable
✖ (Failed) homeassistant-2021.7.4 from 2021-08-01 - https://hydra.nixos.org/build/149346613

Last Builds:
✖ (Failed) homeassistant-2021.7.4 from 2021-07-31 - https://hydra.nixos.org/build/149337694
✖ (Dependency failed) homeassistant-2021.7.4 from 2021-07-29 - https://hydra.nixos.org/build/149029125
✔ homeassistant-2021.7.4 from 2021-07-28 - https://hydra.nixos.org/build/148768952
✔ homeassistant-2021.7.4 from 2021-07-27 - https://hydra.nixos.org/build/148761696
✔ homeassistant-2021.7.4 from 2021-07-26 - https://hydra.nixos.org/build/148658209
✔ homeassistant-2021.7.4 from 2021-07-25 - https://hydra.nixos.org/build/148628236
✔ homeassistant-2021.7.4 from 2021-07-24 - https://hydra.nixos.org/build/148490446
✔ homeassistant-2021.7.0 from 2021-07-24 - https://hydra.nixos.org/build/148447919
✖ (Cancelled) homeassistant-2021.6.6 from 2021-07-23 - https://hydra.nixos.org/build/148413737
```

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 132298` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>home-assistant</li>
    <li>octoprint</li>
  </ul>
</details>
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>ntfy</li>
    <li>opsdroid</li>
    <li>python38Packages.emoji</li>
    <li>python38Packages.locationsharinglib</li>
    <li>python39Packages.emoji</li>
    <li>python39Packages.locationsharinglib</li>
    <li>terraform-compliance</li>
  </ul>
</details>

**Pull request merged**
