### PR TITLE
ocamlPackages.zarith: 1.12 -> 1.13

### PR DESCRIPTION
**Pull request by marsam**
Diff: https://github.com/ocaml/Zarith/compare/release-1.12...release-1.13

Changelog: https://github.com/ocaml/Zarith/raw/release-1.13/Changes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vbgl** [comment]
@GrahamcOfBorg build ligo

**Comment by ulrikstrid** [comment]
Result of `nixpkgs-review pr 244874` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>coqPackages.ITree</li>
    <li>coqPackages.QuickChick</li>
    <li>coqPackages.category-theory</li>
    <li>coqPackages.compcert</li>
    <li>coqPackages.dpdgraph</li>
    <li>coqPackages.gappalib</li>
    <li>coqPackages.interval</li>
    <li>coqPackages.relation-algebra</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>ligo</li>
  </ul>
</details>
<details>
  <summary>90 packages built:</summary>
  <ul>
    <li>alt-ergo</li>
    <li>anders</li>
    <li>comby</li>
    <li>compcert</li>
    <li>compcert.doc</li>
    <li>compcert.lib</li>
    <li>compcert.man</li>
    <li>coq (coqPackages.coq)</li>
    <li>coqPackages.Cheerios</li>
    <li>coqPackages.CoLoR</li>
    <li>coqPackages.HoTT</li>
    <li>coqPackages.InfSeqExt</li>
    <li>coqPackages.LibHyps</li>
    <li>coqPackages.StructTact</li>
    <li>coqPackages.Verdi</li>
    <li>coqPackages.aac-tactics</li>
    <li>coqPackages.addition-chains</li>
    <li>coqPackages.autosubst</li>
    <li>coqPackages.bignums</li>
    <li>coqPackages.coq-elpi</li>
    <li>coqPackages.coq-ext-lib</li>
    <li>coqPackages.coq-lsp</li>
    <li>coqPackages.coq-record-update</li>
    <li>coqPackages.coqeal</li>
    <li>coqPackages.coqide</li>
    <li>coqPackages.coqprime</li>
    <li>coqPackages.coquelicot</li>
    <li>coqPackages.corn</li>
    <li>coqPackages.deriving</li>
    <li>coqPackages.equations</li>
    <li>coqPackages.extructures</li>
    <li>coqPackages.flocq</li>
    <li>coqPackages.fourcolor</li>
    <li>coqPackages.hierarchy-builder</li>
    <li>coqPackages.itauto</li>
    <li>coqPackages.math-classes</li>
    <li>coqPackages.mathcomp</li>
    <li>coqPackages.mathcomp-algebra</li>
    <li>coqPackages.mathcomp-algebra-tactics</li>
    <li>coqPackages.mathcomp-analysis</li>
    <li>coqPackages.mathcomp-bigenough</li>
    <li>coqPackages.mathcomp-character</li>
    <li>coqPackages.mathcomp-classical</li>
    <li>coqPackages.mathcomp-field</li>
    <li>coqPackages.mathcomp-fingroup</li>
    <li>coqPackages.mathcomp-finmap</li>
    <li>coqPackages.mathcomp-infotheo</li>
    <li>coqPackages.mathcomp-real-closed</li>
    <li>coqPackages.mathcomp-solvable</li>
    <li>coqPackages.ssreflect (coqPackages.mathcomp-ssreflect)</li>
    <li>coqPackages.mathcomp-word</li>
    <li>coqPackages.mathcomp-zify</li>
    <li>coqPackages.metalib</li>
    <li>coqPackages.multinomials</li>
    <li>coqPackages.paco</li>
    <li>coqPackages.paramcoq</li>
    <li>coqPackages.pocklington</li>
    <li>coqPackages.reglang</li>
    <li>coqPackages.semantics</li>
    <li>coqPackages.serapi</li>
    <li>coqPackages.simple-io</li>
    <li>coqPackages.stdpp</li>
    <li>coqPackages.trakt</li>
    <li>coq_8_13</li>
    <li>coq_8_14</li>
    <li>coq_8_15</li>
    <li>coq_8_16</li>
    <li>coq_8_17</li>
    <li>dune-release</li>
    <li>easycrypt</li>
    <li>framac</li>
    <li>fstar</li>
    <li>google-drive-ocamlfuse</li>
    <li>jackline</li>
    <li>jasmin-compiler</li>
    <li>jasmin-compiler.bin</li>
    <li>jasmin-compiler.lib</li>
    <li>libbap</li>
    <li>liquidsoap</li>
    <li>python310Packages.bap</li>
    <li>python310Packages.bap.dist</li>
    <li>python311Packages.bap</li>
    <li>python311Packages.bap.dist</li>
    <li>sail-riscv-rv32</li>
    <li>sail-riscv-rv64</li>
    <li>satallax</li>
    <li>sks</li>
    <li>sks.webSamples</li>
    <li>spark2014</li>
    <li>why3</li>
  </ul>
</details>

**Comment by vbgl** [comment]
Is there any hope to see `ligo` compatible with `zarith` 1.13 in a near future?

**Comment by ulrikstrid** [comment]
I'm not sure, I think the issue is in tezos. But maybe we can override zarith local to LIGO so that we can update zarith globally?

**Comment by vbgl** [comment]
I’ve just rebased on recent `master` and added the simple pinning of `zarith` used in `ligo` to previous version 1.12.

**Review by ulrikstrid — APPROVED** [review]

**Pull request merged**
