### PR TITLE
mailnag: enable to configure plugins

### PR DESCRIPTION
**Pull request by doronbehar**
###### Motivation for this change

Make mailnag more usable for Gnome users - make the gnome online accounts mailnag extension usable via Nix arguments to the derivation. Mailnag's Goa plugin is https://github.com/pulb/mailnag-goa-plugin . This PR also makes it easy enough for future us add [other plugins](https://github.com/pulb/mailnag#desktop-integration) that will be added to the derivation.

###### Things done

See commit message. I'm currently using it and it works great for me + plus the gnome shell extension: https://extensions.gnome.org/extension/886/mailnag/

Screenshot from 2020-07-30 03-00-04

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by barryfm** [comment]
Since changing from the 1.3.0 to the 2.0.0 mailnag release, I have been unable save my mail passwords between log ins.
Each time i run mailnag-config the passwords fields show up as empty.  Before they were filled with the starred echoed strings representing the current password.  Seahorse (which is also linked with libsecret) shows the contents of my key ring with entries for mailnag (Which I assume were placed there by the previous version).  Once I enter the passwords mailnag runs correctly until I log out.  When I log in again and mailnag starts up it shows password errors.  I can reenter them with mailnag-config but ...  [goto line 2]

**Comment by doronbehar** [comment]
> Each time i run mailnag-config the passwords fields show up as empty.

I don't experience this and this related. Let's discuss this at https://discourse.nixos.org/t/issues-with-gnome-keyring-and-libsecret/8370/ :).

**Comment by barryfm** [comment]
Sorry for my previous entry.  I should not have posted here. Things were resolved on the discourse link given above.

**Comment by doronbehar** [comment]
@jonringer I hope it'd be OK to ask you for a review directly, considering you are busy with the release. This one has a large diff due to some refactoring, and I think that's why reviewers haven't gave it a look. Additionally, it's a Python package I edited and added, so it should be also your area of expertise.

**Review by jonringer — APPROVED** [review]
since it's just one plugin, i think this is fine.
If more are added, it might be worthwhile to refactor it so that it's a little easier to bring in plugins (e.g. `plugins = callPackage ./plugins.nix` )

```
https://github.com/NixOS/nixpkgs/pull/94202
1 package built:
mailnag
```

**Comment by doronbehar** [comment]
> since it's just one plugin, i think this is fine.
If more are added, it might be worthwhile to refactor it so that it's a little easier to bring in plugins (e.g. plugins = callPackage ./plugins.nix )

Maybe it'll be best to do take care of this now - The last push makes it possible to override the set of available plugins.

**Comment by jonringer** [comment]
> Maybe it'll be best to do take care of this now - The last push makes it possible to override the set of available plugins.

or maybe do something like: `mailnag.withPlugins(ps: with ps; [ goa ] )` similar to `python.withPackages`

**Comment by doronbehar** [comment]
@jonringer I haven't to implement exactly the `mailnag.withPlugins(ps: with ps; [ goa ] )`, but now it's closer, and there's even an example in `all-packages.nix`.

**Review by jonringer — APPROVED** [review]
I think this is good.
It would be preferable to have it do something like a symlinkJoin all the packages into a new derivation, so you don't have to rebuild mailnag. But that's way more involved, and since it will use the same `mailnag.withPackages` convention, that can be done at a later time.

```
https://github.com/NixOS/nixpkgs/pull/94202
2 packages built:
mailnag mailnagWithPlugins
```

**Comment by doronbehar** [comment]
Thanks :guitar:.

**Pull request merged**
