### PR TITLE
podman: 4.9.3 -> 5.0.0

### PR DESCRIPTION
**Pull request by zaphar**
## Update Podman to v5.0.0

Release notes: https://github.com/containers/podman/releases/tag/v5.0.0

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by zaphar** [comment]
This should work everywhere but I've only been able to test on an M1 macbook.
cc: @marsam

**Comment by DontEatOreo** [comment]
You should rebase your commit to be

`podman: 4.9.3 -> 5.0.0`

Also please split the patch commit to be separate and change the PR title

Check out: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions

**Comment by zaphar** [comment]
@DontEatOreo , done.

**Comment by DontEatOreo** [comment]
The patch should have a different name, something like:

`podman: remove mac helper message`

Also please update the PR title to `podman: 4.9.3 -> 5.0.0`

**Comment by zaphar** [comment]
Done.

**Comment by sdht0** [comment]
https://github.com/containers/podman/releases/tag/v5.0.1 is now out

**Comment by WxNzEMof** [comment]
Hi!

- Podman switched to `passt` for user level networking (#265409). Is it not needed here?

- I needed to patch the paths in `vendor/github.com/containers/common/pkg/config/default.go`. Without that patch, it tried to run executables in `/usr/bin`, ignoring the `PATH` built by the nixpkgs wrapper. Have you run into this?

Reference: https://github.com/NixOS/nixpkgs/pull/301553

**Comment by zaphar** [comment]
@WxNzEMof I didn't run into those issues yet. But I wouldn't be surprised if they were needed. I haven't had the time to come back to this for a bit. If someone else want's to take over I'll not be offended. Otherwise it can wait till I have time again.

**Comment by DontEatOreo** [comment]
Since v5.0.1 is out, could you amend the last commit with the new version and update the PR title?

**Comment by SuperSandro2000** [comment]
Closing in favor of #301553 because it has a more complete approach to all features

**Pull request closed without merging**
