### PR TITLE
darwin.moltenvk: 1.2.7 -> 1.2.8

### PR DESCRIPTION
**Pull request by reckenrode**
## Description of changes

https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.8

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by reckenrode** [comment]
Result of `nixpkgs-review pr 298437` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>anki</li>
    <li>anki.dist</li>
    <li>anki.doc</li>
    <li>anki.man</li>
    <li>mnemosyne</li>
    <li>mnemosyne.dist</li>
    <li>mpc-qt</li>
    <li>vulkan-caps-viewer</li>
  </ul>
</details>
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>dmlive</li>
    <li>gfxstream</li>
    <li>gtk-pipe-viewer</li>
    <li>gtk-pipe-viewer.devdoc</li>
    <li>hydrus</li>
    <li>hydrus.doc</li>
    <li>ncnn</li>
    <li>realesrgan-ncnn-vulkan</li>
    <li>rerun</li>
    <li>rutabaga_gfx</li>
    <li>tomato-c</li>
    <li>wtwitch</li>
  </ul>
</details>
<details>
  <summary>45 packages built:</summary>
  <ul>
    <li>ani-cli</li>
    <li>cplay-ng</li>
    <li>cplay-ng.dist</li>
    <li>curseradio</li>
    <li>curseradio.dist</li>
    <li>ddnet</li>
    <li>dolphin-emu</li>
    <li>dra-cla</li>
    <li>fastfetch</li>
    <li>fastfetch.man</li>
    <li>feishin</li>
    <li>ff2mpv</li>
    <li>ff2mpv-go</li>
    <li>halloy</li>
    <li>invidtui</li>
    <li>klipperscreen</li>
    <li>libplacebo</li>
    <li>libplacebo_5</li>
    <li>mov-cli</li>
    <li>mov-cli.dist</li>
    <li>mpv</li>
    <li>mpv-unwrapped</li>
    <li>mpv-unwrapped.dev</li>
    <li>mpv-unwrapped.doc</li>
    <li>mpv-unwrapped.man</li>
    <li>photoqt</li>
    <li>pipe-viewer</li>
    <li>pipe-viewer.devdoc</li>
    <li>plex-media-player</li>
    <li>python311Packages.mpv</li>
    <li>python311Packages.mpv.dist</li>
    <li>python312Packages.mpv</li>
    <li>python312Packages.mpv.dist</li>
    <li>rbdoom-3-bfg</li>
    <li>somafm-cli</li>
    <li>subtitleedit</li>
    <li>supersonic</li>
    <li>vkquake</li>
    <li>vulkan-loader</li>
    <li>vulkan-loader.dev</li>
    <li>vulkan-tools</li>
    <li>wgpu-utils</li>
    <li>youtube-tui</li>
    <li>ytfzf</li>
    <li>ytui-music</li>
  </ul>
</details>

**Comment by reckenrode** [comment]
The failures aren’t caused by the MoltenVK update, but I’m submitting PRs to fix them (except for rerun, which appears to have been caused by the Rust 1.76 update).

**Comment by reckenrode** [comment]
Result of `nixpkgs-review pr 298437` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>119 packages marked as broken and skipped:</summary>
  <ul>
    <li>airshipper</li>
    <li>ajour</li>
    <li>anilibria-winmaclinux</li>
    <li>anki</li>
    <li>anki.dist</li>
    <li>anki.doc</li>
    <li>anki.man</li>
    <li>arcan</li>
    <li>colloid-kde</li>
    <li>colloid-kde.sddm</li>
    <li>dwl</li>
    <li>dwl.man</li>
    <li>flet-client-flutter</li>
    <li>flet-client-flutter.debug</li>
    <li>flet-client-flutter.pubcache</li>
    <li>flycast</li>
    <li>graphite-kde-theme</li>
    <li>grimblast</li>
    <li>hyprpicker</li>
    <li>jellyfin-mpv-shim</li>
    <li>jellyfin-mpv-shim.dist</li>
    <li>kaffeine</li>
    <li>kodiPackages.inputstream-adaptive</li>
    <li>kodiPackages.inputstream-ffmpegdirect</li>
    <li>kodiPackages.inputstream-rtmp</li>
    <li>kodiPackages.joystick</li>
    <li>kodiPackages.libretro</li>
    <li>kodiPackages.libretro-2048</li>
    <li>kodiPackages.libretro-fuse</li>
    <li>kodiPackages.libretro-genplus</li>
    <li>kodiPackages.libretro-mgba</li>
    <li>kodiPackages.libretro-nestopia</li>
    <li>kodiPackages.libretro-snes9x</li>
    <li>kodiPackages.pvr-hdhomerun</li>
    <li>kodiPackages.pvr-hts</li>
    <li>kodiPackages.pvr-iptvsimple</li>
    <li>kodiPackages.pvr-vdr-vnsi</li>
    <li>kodiPackages.steam-controller</li>
    <li>kodiPackages.vfs-libarchive</li>
    <li>kodiPackages.vfs-rar</li>
    <li>kodiPackages.vfs-sftp</li>
    <li>kodiPackages.visualization-fishbmc</li>
    <li>kodiPackages.visualization-goom</li>
    <li>kodiPackages.visualization-matrix</li>
    <li>kodiPackages.visualization-pictureit</li>
    <li>kodiPackages.visualization-projectm</li>
    <li>kodiPackages.visualization-shadertoy</li>
    <li>kodiPackages.visualization-spectrum</li>
    <li>kodiPackages.visualization-starburst</li>
    <li>kodiPackages.visualization-waveform</li>
    <li>kphotoalbum</li>
    <li>labwc</li>
    <li>labwc.man</li>
    <li>latte-dock</li>
    <li>layan-kde</li>
    <li>libsForQt5.bismuth</li>
    <li>libsForQt5.krohnkite</li>
    <li>libsForQt5.kwin-dynamic-workspaces</li>
    <li>libsForQt5.kwin-tiling</li>
    <li>libsForQt5.kzones</li>
    <li>libsForQt5.parachute</li>
    <li>libsForQt5.tokodon</li>
    <li>lightly-boehs</li>
    <li>lightly-qt</li>
    <li>ludusavi</li>
    <li>mate.mate-wayland-session</li>
    <li>mesa-demos</li>
    <li>mnemosyne</li>
    <li>mnemosyne.dist</li>
    <li>mojave-gtk-theme</li>
    <li>mpc-qt</li>
    <li>nordic</li>
    <li>nordic.sddm</li>
    <li>pcsx2</li>
    <li>plasma5Packages.bismuth</li>
    <li>plasma5Packages.krohnkite</li>
    <li>plasma5Packages.kwin-dynamic-workspaces</li>
    <li>plasma5Packages.kwin-tiling</li>
    <li>plasma5Packages.kzones</li>
    <li>plasma5Packages.parachute</li>
    <li>plasma5Packages.tokodon</li>
    <li>python311Packages.flet</li>
    <li>python311Packages.flet-runtime</li>
    <li>python311Packages.flet-runtime.dist</li>
    <li>python311Packages.flet.dist</li>
    <li>python311Packages.py3status</li>
    <li>python311Packages.py3status.dist</li>
    <li>python311Packages.python-vlc</li>
    <li>python311Packages.python-vlc.dist</li>
    <li>python311Packages.qtile-extras</li>
    <li>python311Packages.qtile-extras.dist</li>
    <li>python312Packages.flet</li>
    <li>python312Packages.flet-runtime</li>
    <li>python312Packages.flet-runtime.dist</li>
    <li>python312Packages.flet.dist</li>
    <li>python312Packages.python-vlc</li>
    <li>python312Packages.python-vlc.dist</li>
    <li>qogir-kde</li>
    <li>rivercarro</li>
    <li>shairport-sync</li>
    <li>snapshot</li>
    <li>sublime-music</li>
    <li>sublime-music.dist</li>
    <li>sway-contrib.grimshot</li>
    <li>sway-contrib.grimshot.man</li>
    <li>utterly-nord-plasma</li>
    <li>vimix-gtk-themes</li>
    <li>vulkan-caps-viewer</li>
    <li>waybox</li>
    <li>wayfire</li>
    <li>wayfirePlugins.firedecor</li>
    <li>wayfirePlugins.wayfire-plugins-extra</li>
    <li>wayfirePlugins.wcm</li>
    <li>wayfirePlugins.wf-shell</li>
    <li>wayfirePlugins.windecor</li>
    <li>whitesur-gtk-theme</li>
    <li>whitesur-kde</li>
    <li>wio</li>
    <li>xarcan</li>
  </ul>
</details>
<details>
  <summary>57 packages failed to build:</summary>
  <ul>
    <li>ani-cli</li>
    <li>cplay-ng</li>
    <li>cplay-ng.dist</li>
    <li>curseradio</li>
    <li>curseradio.dist</li>
    <li>darwin.moltenvk</li>
    <li>darwin.moltenvk.bin</li>
    <li>darwin.moltenvk.dev</li>
    <li>dmlive</li>
    <li>dolphin-emu</li>
    <li>dra-cla</li>
    <li>fastfetch</li>
    <li>fastfetch.man</li>
    <li>feishin</li>
    <li>ff2mpv-go</li>
    <li>gfxstream</li>
    <li>gtk-pipe-viewer</li>
    <li>gtk-pipe-viewer.devdoc</li>
    <li>halloy</li>
    <li>hydrus</li>
    <li>hydrus.doc</li>
    <li>invidtui</li>
    <li>jellyfin-media-player</li>
    <li>klipperscreen</li>
    <li>libplacebo</li>
    <li>libplacebo_5</li>
    <li>mov-cli</li>
    <li>mov-cli.dist</li>
    <li>mpv-unwrapped</li>
    <li>mpv-unwrapped.dev</li>
    <li>mpv-unwrapped.doc</li>
    <li>mpv-unwrapped.man</li>
    <li>ncnn</li>
    <li>photoqt</li>
    <li>pipe-viewer</li>
    <li>pipe-viewer.devdoc</li>
    <li>python311Packages.mpv</li>
    <li>python311Packages.mpv.dist</li>
    <li>python312Packages.mpv</li>
    <li>python312Packages.mpv.dist</li>
    <li>rbdoom-3-bfg</li>
    <li>realesrgan-ncnn-vulkan</li>
    <li>rerun</li>
    <li>rutabaga_gfx</li>
    <li>somafm-cli</li>
    <li>subtitleedit</li>
    <li>supersonic</li>
    <li>tomato-c</li>
    <li>vkquake</li>
    <li>vulkan-loader</li>
    <li>vulkan-loader.dev</li>
    <li>vulkan-tools</li>
    <li>wgpu-utils</li>
    <li>wtwitch</li>
    <li>youtube-tui</li>
    <li>ytfzf</li>
    <li>ytui-music</li>
  </ul>
</details>

**Comment by reckenrode** [comment]
Added the `__structuredAttrs` change, which should have been included in the cleanup PR.

**Comment by reckenrode** [comment]
Switched the branch to staging-next since the Vulkan SDK updates are there and not on master yet.

**Comment by reckenrode** [comment]
supersonic is a new failure. It appears to be SDK-related.

**Comment by reckenrode** [comment]
Retargeting to master now that the SDK update has been merged.

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 298437` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>121 packages marked as broken and skipped:</summary>
  <ul>
    <li>airshipper</li>
    <li>ajour</li>
    <li>anilibria-winmaclinux</li>
    <li>anki</li>
    <li>anki.dist</li>
    <li>anki.doc</li>
    <li>anki.man</li>
    <li>arcan</li>
    <li>colloid-kde</li>
    <li>colloid-kde.sddm</li>
    <li>dwl</li>
    <li>dwl.man</li>
    <li>flet-client-flutter</li>
    <li>flet-client-flutter.debug</li>
    <li>flet-client-flutter.pubcache</li>
    <li>flycast</li>
    <li>graphite-kde-theme</li>
    <li>grimblast</li>
    <li>hyprpicker</li>
    <li>jellyfin-mpv-shim</li>
    <li>jellyfin-mpv-shim.dist</li>
    <li>kaffeine</li>
    <li>kodiPackages.inputstream-adaptive</li>
    <li>kodiPackages.inputstream-ffmpegdirect</li>
    <li>kodiPackages.inputstream-rtmp</li>
    <li>kodiPackages.joystick</li>
    <li>kodiPackages.libretro</li>
    <li>kodiPackages.libretro-2048</li>
    <li>kodiPackages.libretro-fuse</li>
    <li>kodiPackages.libretro-genplus</li>
    <li>kodiPackages.libretro-mgba</li>
    <li>kodiPackages.libretro-nestopia</li>
    <li>kodiPackages.libretro-snes9x</li>
    <li>kodiPackages.pvr-hdhomerun</li>
    <li>kodiPackages.pvr-hts</li>
    <li>kodiPackages.pvr-iptvsimple</li>
    <li>kodiPackages.pvr-vdr-vnsi</li>
    <li>kodiPackages.steam-controller</li>
    <li>kodiPackages.vfs-libarchive</li>
    <li>kodiPackages.vfs-rar</li>
    <li>kodiPackages.vfs-sftp</li>
    <li>kodiPackages.visualization-fishbmc</li>
    <li>kodiPackages.visualization-goom</li>
    <li>kodiPackages.visualization-matrix</li>
    <li>kodiPackages.visualization-pictureit</li>
    <li>kodiPackages.visualization-projectm</li>
    <li>kodiPackages.visualization-shadertoy</li>
    <li>kodiPackages.visualization-spectrum</li>
    <li>kodiPackages.visualization-starburst</li>
    <li>kodiPackages.visualization-waveform</li>
    <li>kphotoalbum</li>
    <li>labwc</li>
    <li>labwc.man</li>
    <li>latte-dock</li>
    <li>layan-kde</li>
    <li>libsForQt5.bismuth</li>
    <li>libsForQt5.krohnkite</li>
    <li>libsForQt5.kwin-dynamic-workspaces</li>
    <li>libsForQt5.kwin-tiling</li>
    <li>libsForQt5.kzones</li>
    <li>libsForQt5.parachute</li>
    <li>libsForQt5.tokodon</li>
    <li>lightly-boehs</li>
    <li>lightly-qt</li>
    <li>ludusavi</li>
    <li>mate.mate-wayland-session</li>
    <li>mesa-demos</li>
    <li>mnemosyne</li>
    <li>mnemosyne.dist</li>
    <li>mojave-gtk-theme</li>
    <li>mpc-qt</li>
    <li>nordic</li>
    <li>nordic.sddm</li>
    <li>plasma5Packages.bismuth</li>
    <li>plasma5Packages.krohnkite</li>
    <li>plasma5Packages.kwin-dynamic-workspaces</li>
    <li>plasma5Packages.kwin-tiling</li>
    <li>plasma5Packages.kzones</li>
    <li>plasma5Packages.parachute</li>
    <li>plasma5Packages.tokodon</li>
    <li>python311Packages.flet</li>
    <li>python311Packages.flet-runtime</li>
    <li>python311Packages.flet-runtime.dist</li>
    <li>python311Packages.flet.dist</li>
    <li>python311Packages.py3status</li>
    <li>python311Packages.py3status.dist</li>
    <li>python311Packages.python-vlc</li>
    <li>python311Packages.python-vlc.dist</li>
    <li>python311Packages.qtile-extras</li>
    <li>python311Packages.qtile-extras.dist</li>
    <li>python312Packages.flet</li>
    <li>python312Packages.flet-runtime</li>
    <li>python312Packages.flet-runtime.dist</li>
    <li>python312Packages.flet.dist</li>
    <li>python312Packages.python-vlc</li>
    <li>python312Packages.python-vlc.dist</li>
    <li>qogir-kde</li>
    <li>rivercarro</li>
    <li>shairport-sync</li>
    <li>snapshot</li>
    <li>sublime-music</li>
    <li>sublime-music.dist</li>
    <li>sway-contrib.grimshot</li>
    <li>sway-contrib.grimshot.man</li>
    <li>utterly-nord-plasma</li>
    <li>vimix-gtk-themes</li>
    <li>vulkan-caps-viewer</li>
    <li>waybox</li>
    <li>wayfire</li>
    <li>wayfirePlugins.firedecor</li>
    <li>wayfirePlugins.focus-request</li>
    <li>wayfirePlugins.wayfire-plugins-extra</li>
    <li>wayfirePlugins.wayfire-shadows</li>
    <li>wayfirePlugins.wcm</li>
    <li>wayfirePlugins.wf-shell</li>
    <li>wayfirePlugins.windecor</li>
    <li>wayfirePlugins.wwp-switcher</li>
    <li>whitesur-gtk-theme</li>
    <li>whitesur-kde</li>
    <li>wio</li>
    <li>xarcan</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>realesrgan-ncnn-vulkan</li>
    <li>rerun</li>
  </ul>
</details>
<details>
  <summary>54 packages built:</summary>
  <ul>
    <li>ani-cli</li>
    <li>cplay-ng</li>
    <li>cplay-ng.dist</li>
    <li>curseradio</li>
    <li>curseradio.dist</li>
    <li>darwin.moltenvk</li>
    <li>darwin.moltenvk.bin</li>
    <li>darwin.moltenvk.dev</li>
    <li>dmlive</li>
    <li>dolphin-emu</li>
    <li>dra-cla</li>
    <li>fastfetch</li>
    <li>fastfetch.man</li>
    <li>feishin</li>
    <li>ff2mpv-go</li>
    <li>gfxstream</li>
    <li>gtk-pipe-viewer</li>
    <li>gtk-pipe-viewer.devdoc</li>
    <li>halloy</li>
    <li>hydrus</li>
    <li>hydrus.doc</li>
    <li>invidtui</li>
    <li>klipperscreen</li>
    <li>libplacebo</li>
    <li>libplacebo_5</li>
    <li>mov-cli</li>
    <li>mov-cli.dist</li>
    <li>mpv-unwrapped</li>
    <li>mpv-unwrapped.dev</li>
    <li>mpv-unwrapped.doc</li>
    <li>mpv-unwrapped.man</li>
    <li>ncnn</li>
    <li>photoqt</li>
    <li>pipe-viewer</li>
    <li>pipe-viewer.devdoc</li>
    <li>python311Packages.mpv</li>
    <li>python311Packages.mpv.dist</li>
    <li>python312Packages.mpv</li>
    <li>python312Packages.mpv.dist</li>
    <li>rbdoom-3-bfg</li>
    <li>rutabaga_gfx</li>
    <li>somafm-cli</li>
    <li>subtitleedit</li>
    <li>supersonic</li>
    <li>tomato-c</li>
    <li>vkquake</li>
    <li>vulkan-loader</li>
    <li>vulkan-loader.dev</li>
    <li>vulkan-tools</li>
    <li>wgpu-utils</li>
    <li>wtwitch</li>
    <li>youtube-tui</li>
    <li>ytfzf</li>
    <li>ytui-music</li>
  </ul>
</details>

**Review by wegank — APPROVED** [review]

**Pull request merged**
