### PR TITLE
neomutt: 20230517 ->  20231103

### PR DESCRIPTION
**Pull request by michaeladler**
## Description of changes

https://github.com/neomutt/neomutt/releases/tag/20231023

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
Meh… I am seeing broken basic features, like opening a big mailbox, which were working very well before.

**Comment by michaeladler** [comment]
Hmm I use virtual mailboxes (notmuch) which works fine (but at the same time they're not "large"). Maybe open a new issue upstream?

**Comment by RaitoBezarius** [comment]
Will do so, but in the meantime, I am not sure we should merge this bump before more testing cc @Ma27

**Review by Ma27 — CHANGES_REQUESTED** [review]
> Meh… I am seeing broken basic features, like opening a big mailbox, which were working very well before.

_insert ah sh*t here we go again meme here_

But seriously, I'm :-1: on merging until this got resolved. To quote the release notes:

> Most of the work won't be visible to the users.

It's of course a nice milestone for them, but as long as it's not as stable as the currently packaged version we have here, I don't see a reason to bump this.

**Comment by afh** [comment]
@michaeladler neomutt version [20231023](https://github.com/neomutt/neomutt/releases/tag/20231023) has been released, would you be okay with updating this PR accordingly?

**Comment by michaeladler** [comment]
@afh Thanks for the heads up. I've updated the PR.

**Comment by flokli** [comment]
@Ma27 can you give this more recent release another try? The changelog mentions quite a bunch of bugfixes for crashes.

**Comment by Ma27** [comment]
I'll surely test it soonish, though it was @RaitoBezarius this time who found the issues first (and I decided to skip testing the previous release).

**Review by Ma27 — APPROVED** [review]
Did some basic checks and it seems to work fine. Using this on my machine from now on :+1: 

Would like to give @RaitoBezarius a chance to test the new release before merging this, though.

**Comment by RaitoBezarius** [comment]
Testing.

**Comment by RaitoBezarius** [comment]
Still observe that one of my mailbox is extremely slow to open with this new release, like from 900ms to 18s to open.

**Comment by afh** [comment]
Thanks for testing @RaitoBezarius, much appreciated! Can you link to an issue that was raised here or upstream? Might be helpful to get more context on the regression you are observing with neomutt and large mailboxes.

**Comment by afh** [comment]
ℹ️ neomutt version [20231103](https://github.com/neomutt/neomutt/releases/tag/20231103) has been released. Might be worthwhile to update this PR.

**Comment by michaeladler** [comment]
I just updated to [20231103](https://github.com/neomutt/neomutt/releases/tag/20231103). I had to switch to clang to compile neomutt because one test case is failing using gcc. The test case is trivial though so I have no clue why it fails with gcc.

**Comment by michaeladler** [comment]
I agree although I'd be curious to know what's your argument against clang - IMO it's the better compiler ;)
Anyway here's the failure:

```
Test test_attr_colors...                        [ FAILED ]
  Case Common setup:
    attr.c:102: Check memcmp(&ac, &ac_copy, sizeof(ac_copy)) == 0... failed
```

and [this](https://github.com/neomutt/neomutt/blob/ca3b28c4c3cbddd46aa0393e54e561531c73e1c9/test/color/attr.c#L102)  is the test case. I don't see why this could possibly fail, but it does when run in the context of `nix build`. If I run the tests with gcc outside of `nix build`, they pass.

**Comment by RaitoBezarius** [comment]
> I agree although I'd be curious to know what's your argument against clang - IMO it's the better compiler ;) Anyway here's the failure:

Well, you have to bring all the closure size of Clang and NixOS is not really a LLVM distribution but more a GCC distribution.

> 
> ```
> Test test_attr_colors...                        [ FAILED ]
>   Case Common setup:
>     attr.c:102: Check memcmp(&ac, &ac_copy, sizeof(ac_copy)) == 0... failed
> ```
> 
> and [this](https://github.com/neomutt/neomutt/blob/ca3b28c4c3cbddd46aa0393e54e561531c73e1c9/test/color/attr.c#L102) is the test case. I don't see why this could possibly fail, but it does when run in the context of `nix build`. If I run the tests with gcc outside of `nix build`, they pass. Maybe some compiler optimization?

Gotcha.

**Comment by RaitoBezarius** [comment]
I don't have a lot to further debug this but indeed this looks like a miscompilation of potentially https://github.com/neomutt/neomutt/blob/main/color/attr.c#L167-L173.

Ideally, someone should take gdb, compile while separating the debug information, break before and verify what's going on. I checked quickly with radare2 to no avail.

**Review by RaitoBezarius — APPROVED** [review]
I can confirm that latest changes does not introduce the performance regression I saw in the past. We can proceed once CI is green.

**Comment by afh** [comment]
Result of `nixpkgs-review pr 262271` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>neomutt</li>
  </ul>
</details>

**Comment by afh** [comment]
Thanks for putting in all the time and work to debug and merging this, @RaitoBezarius, very much appreciated!

**Comment by RaitoBezarius** [comment]
Apologies for holding this update for so long, I was very busy alas those last months. Thank you for waiting.

**Pull request merged**
