### PR TITLE
qgis: 2.8.2 -> 2.10.0

### PR DESCRIPTION
**Pull request by michelk**

### CODE REVIEW

**Comment by vbgl** [comment]
Is version 2.10 released already? or is this a release candidate?

**Comment by michelk** [comment]
This is a [release](https://github.com/qgis/QGIS/releases).

**Comment by vbgl** [comment]
It seems that 2.10 is released as 2.10.1; would you like to update this PR? Thank you.

**Comment by michelk** [comment]
Done.

**Pull request merged**
