### PR TITLE
minigalaxy: 1.2.2 -> 1.3.0

### PR DESCRIPTION
**Pull request by ozkutuk**
## Description of changes

https://github.com/sharkwouter/minigalaxy/blob/1.2.6/CHANGELOG.md

Supersedes https://github.com/NixOS/nixpkgs/pull/282594, adds the missing runtime dependency.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by quantenzitrone** [comment]
Result of `nixpkgs-review pr 294275` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>minigalaxy</li>
    <li>minigalaxy.dist</li>
  </ul>
</details>

**Comment by quantenzitrone** [comment]
I cannot get the app to run properly, starting it just shows me a black box with a title bar and another small black box which is probably supposed to be the login window.

**Comment by ozkutuk** [comment]
> I cannot get the app to run properly, starting it just shows me a black box with a title bar and another small black box which is probably supposed to be the login window.

Interesting, I don't really know what to say apart from "it works for me". I am on KDE Plasma 6.0.3 with Wayland (although it worked on when I was on 5 as well). Have version 1.2.2 been working for you?

**Comment by quantenzitrone** [comment]
version 1.2.2 works and after logging in in version 1.2.2, 1.2.6 works as well, but the login window doesn't work in 1.2.6 and before logging in, the main window is just black (black due to my gtk theming probably).

so tldr only login does not work in 1.2.6

**Comment by ozkutuk** [comment]
Unfortunately, I can't replicate the issue. I have logged out of my account, and in addition removed the following directories just in case:

```
.config/minigalaxy/
.cache/minigalaxy/
.cache/.minigalaxy-wrapped/
.local/share/.minigalaxy-wrapped/
```

Still, when I open up `minigalaxy` for the first time, I am greeted with the login prompt as usual:
image

**Comment by quantenzitrone** [comment]
with v1.2.6:
image

with v.1.2.2:
image

I ran them both with `env -i WAYLAND_DISPLAY=$WAYLAND_DISPLAY DISPLAY=$DISPLAY LOCALE_ARCHIVE=$LOCALE_ARCHIVE` to remove as much impurities as possible. I don't really know what else to do.

**Comment by ozkutuk** [comment]
> I ran them both with `env -i WAYLAND_DISPLAY=$WAYLAND_DISPLAY DISPLAY=$DISPLAY LOCALE_ARCHIVE=$LOCALE_ARCHIVE` (`-i` removes any environment variables, but some are still needed so i re-add them) to remove as much impurities as possible.

Are those two environment variables enough for you? When I try to run as such I get the following error:
```bash
$ env -i WAYLAND_DISPLAY=$WAYLAND_DISPLAY DISPLAY=$DISPLAY LOCALE_ARCHIVE=$LOCALE_ARCHIVE ./result/bin/minigalaxy
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified


(.minigalaxy-wrapped:38780): Gtk-ERROR **: 00:30:46.211: Can't create a GtkStyleContext without a display connection
```

**Comment by quantenzitrone** [comment]
on Xorg i need XAUTHORITY instead of WAYLAND_DISPLAY

**Review by SuperSandro2000 — APPROVED** [review]
I've took the freedom to push the 1.3.0 update onto this PR and cleanup the dependencies a bit.

**Comment by ozkutuk** [comment]
@SuperSandro2000 I was planning to test if minigalaxy is affected by #341219, but I now realize I can't actually get minigalaxy on master branch working on my machine. I am experiencing the same blank login screen issues as reported by @quantenzitrone. A workaround is suggested in the issue tracker of minigalaxy (https://github.com/sharkwouter/minigalaxy/issues/584#issuecomment-1752955169), but it doesn't work for me either. Can you confirm that minigalaxy@master works for you when you remove the files I listed in https://github.com/NixOS/nixpkgs/pull/294275#issuecomment-2067963591?

**Comment by SuperSandro2000** [comment]
I tested minigalaxy on another machine and it just works as expected but I am on wayland.

**Pull request merged**
