### PR TITLE
saber: init at 0.3.15

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
@hacker1024 Should I better not use `mkFlutterApp`?

**Comment by hacker1024** [comment]
`mkFlutterApp` should work with my latest changes in #201027.
The `vendorHash` for `saber` is `sha256-3aa7b1O7rE+WmpUOYMXXwqvGiWIDBrztl9/ZkeB9E4s=`.

**Comment by dotlambda** [comment]
> The `vendorHash` for `saber` is `sha256-3aa7b1O7rE+WmpUOYMXXwqvGiWIDBrztl9/ZkeB9E4s=`.

I get `sha256-U2VROQPIRxF8KVupcnQTqOoJtiaQz+UMXn4O0AD8B+8=`.

**Comment by hacker1024** [comment]
> > The `vendorHash` for `saber` is `sha256-3aa7b1O7rE+WmpUOYMXXwqvGiWIDBrztl9/ZkeB9E4s=`.
> 
> I get `sha256-U2VROQPIRxF8KVupcnQTqOoJtiaQz+UMXn4O0AD8B+8=`. Is this deterministic?

Hmm, I tried again with your latest init commit and got another hash again. Perhaps something to do with my `.packages` modifications broke the reproducibility?

@mkg20001 if you could take a look at this I'd appreciate it as I don't fully understand how this builder works. Ideally it should be updated to let the wrapped `flutter` supply the build dependencies as well, it doesn't need to do any of that itself anymore (other than patching the RUNPATH of the build outputs).

**Comment by mkg20001** [comment]
@hacker1024 A big issue currently is that flutter downloads whatever the latest version there is of the sdk (there are other parts of the SDK that are fetched, like linux-x64 tools), so what I did was basically generate a vendorHash just before merge and then somehow get it to be cached. I only realized afterwards that linux-x64 tools, etc get updated without any lockfile to control it afaik. It should be possible to fetch the extra stuff beforehand and then make flutter use it via symlinks, but that's more complicated.

Also I don't know if any of the flutter upgrades introduced non-determinism again, this could also be the cause of the issue, as flutter and dart like to put timestamps everywhere.

**Comment by hacker1024** [comment]
Ah, I see.

I wonder if it would be practical to build the entire SDK, engine and all, from source? That would have the benefit of removing the need for patchelf or any other hacks of that nature, as well as allowing us to ship pinned version of all the tools.

**Comment by dotlambda** [comment]
> I wonder if it would be practical to build the entire SDK, engine and all, from source? That would have the benefit of removing the need for patchelf or any other hacks of that nature, as well as allowing us to ship pinned versions of all the tools.

We should definitely do that, especially since using the SDK povided by Google implies consent with their TOS: https://github.com/NixOS/nixpkgs/pull/201027#issuecomment-1314669911

**Comment by mkg20001** [comment]
Maybe. I don't know if that can be pulled off or how much effort it would be to keep everything up-to-date, but it seems worth a try.

**Comment by hacker1024** [comment]
> A big issue currently is that flutter downloads whatever the latest version there is of the sdk (there are other parts of the SDK that are fetched, like linux-x64 tools), so what I did was basically generate a vendorHash just before merge and then somehow get it to be cached. I only realized afterwards that linux-x64 tools, etc get updated without any lockfile to control it afaik. It should be possible to fetch the extra stuff beforehand and then make flutter use it via symlinks, but that's more complicated.
> 
> Also I don't know if any of the flutter upgrades introduced non-determinism again, this could also be the cause of the issue, as flutter and dart like to put timestamps everywhere.

It actually [looks like](https://github.com/flutter/flutter/blob/3.3.8/packages/flutter_tools/lib/src/cache.dart#L928) the tools are pinned to the engine version.

This can be seen with `flutter precache -v` also, as the artifact URLs are printed and they clearly contain an engine hash corresponding to the Flutter version.

The non-determinism in the build output is more of an issue, though. I wonder, while the intermediate build files may contain dates and things, what about the final built artifacts? Could it be possible to download the sources and build the app in one derivation, with a known final binary hash?

**Comment by dotlambda** [comment]
> Could it be possible to download the sources and build the app in one derivation, with a known final binary hash?

That is completely against the spirit of Nix, then we could just as well download a binary from upstream and package that. Also, it would be even harder to make deterministic.

**Comment by prehonor** [comment]
attribute 'mkFlutterApp' missing

       at /nix/store/sgrg7di80hh58rbb997gcd45cqgw9ifw-source/nixpkgs-overlays/pkgs/applications/graphics/saber/default.nix:7:1:

            6|
            7| flutter.mkFlutterApp rec {
             | ^
            8|   pname = "saber";
(use '--show-trace' to show detailed location information)

**Comment by mkg20001** [comment]
The flutter architecture has been completely revamped. It is now way easier to use.  Please rebase.

**Pull request closed without merging**
