### PR TITLE
mastobooper: init at 1.0.0

### PR DESCRIPTION
**Pull request by ckiee**
###### Description of changes

https://github.com/ckiee/mastobooper

it makes badoops.

([motivation](https://social.pixie.town/web/statuses/108204406489150712), cc @DeeUnderscore)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 06kellyjac** [comment]
I think this is a bit niche for nixpkgs :upside_down_face: :sweat_smile: 

https://discourse.nixos.org/t/nixpkgss-current-development-workflow-is-not-sustainable/18741

**Comment by ckiee** [comment]
> I think this is a bit niche for nixpkgs :upside_down_face: :sweat_smile:

But.. fun!

**Comment by 06kellyjac** [comment]
Does it just randomly play that `.ogg`? :sweat_smile:

**Comment by Xe** [comment]
-1, this probably belongs as an independent nix flake and is not sufficiently generally usable for everyone that uses nixos

Not trying to shoot you down @ckiee, but when something is put upstream into NixOS, this makes it a potential release-blocking liability for the future. Keep experimenting, but this tool is not really the best thing to submit upstream at this time.

**Comment by ckiee** [comment]
Womp womp wommmmp..

**Pull request closed without merging**
