### PR TITLE
tmux: 3.3a -> 3.4

### PR DESCRIPTION
**Pull request by marsam**
Diff: https://github.com/tmux/tmux/compare/3.3a...3.4

Changelog: https://github.com/tmux/tmux/raw/3.4/CHANGES

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by caarlos0 — APPROVED** [review]

**Comment by afh** [comment]
Result of `nixpkgs-review pr 288507` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>arsenal</li>
    <li>arsenal.dist</li>
    <li>byobu</li>
    <li>fzf-git-sh</li>
    <li>germinal</li>
    <li>hostmux</li>
    <li>overmind</li>
    <li>python311Packages.libtmux</li>
    <li>python311Packages.libtmux.dist</li>
    <li>python312Packages.libtmux</li>
    <li>python312Packages.libtmux.dist</li>
    <li>tmux</li>
    <li>tmux-cssh</li>
    <li>tmux.man</li>
    <li>tmuxp</li>
    <li>tmuxp.dist</li>
    <li>vimPlugins.cmp-tmux</li>
    <li>wemux</li>
  </ul>
</details>

**Review by afh — APPROVED** [review]
According to the [ChangeLog](https://raw.githubusercontent.com/tmux/tmux/3.4/CHANGES) tmux 3.4 _"Add[s] basic support for SIXEL if built with `--enable-sixel`"_

I'd find it convenient if the tmux nixpkgs would by default include support for sixel. Is the following patch something folks find acceptable and also see value in?

```patch
diff --git a/pkgs/tools/misc/tmux/default.nix b/pkgs/tools/misc/tmux/default.nix
index 3cf6172891bd..a126832cd74c 100644
--- a/pkgs/tools/misc/tmux/default.nix
+++ b/pkgs/tools/misc/tmux/default.nix
@@ -10,6 +10,7 @@
 , withSystemd ? lib.meta.availableOn stdenv.hostPlatform systemd, systemd
 , withUtf8proc ? true, utf8proc # gets Unicode updates faster than glibc
 , withUtempter ? stdenv.isLinux && !stdenv.hostPlatform.isMusl, libutempter
+, withSixel ? true
 }:
 
 let
@@ -58,7 +59,8 @@ stdenv.mkDerivation (finalAttrs: {
     "--localstatedir=/var"
   ] ++ lib.optionals withSystemd [ "--enable-systemd" ]
   ++ lib.optionals withUtempter [ "--enable-utempter" ]
-  ++ lib.optionals withUtf8proc [ "--enable-utf8proc" ];
+  ++ lib.optionals withUtf8proc [ "--enable-utf8proc" ]
+  ++ lib.optionals withSixel [ "--enable-sixel" ];
 
   enableParallelBuilding = true;
 
```

**Comment by natsukium** [comment]
I tried sixel support with wezterm and it seems to work fine.

**Comment by afh** [comment]
Thanks for reviewing and merging this PR, @natsukium, very much appreciated! :pray:

**Pull request merged**
