### PR TITLE
tmux: reorder outputs to avoid cycle reference on OSX. fix #17092

### LINKED ISSUE #17092: tmux on build failure darwin
## Issue description

Issue #16224 appears to have introduced a regression in darwin builds, this was detected by the automated build: https://hydra.nixos.org/build/36852692/log

Reverting commit 94627e658beabf2b4c766d31afa273a55879b46a causes a successful build.

### Steps to reproduce

On OS X (currently running OS X 10.11.5), run `nix-env -i tmux`

Output of the failed `nix-env -i tmux` can be found in this gist: https://gist.github.com/sufianrhazi/470f0854f6f23610e197485c50822338

## Technical details

* System: OS X 10.11.5
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre87025.cb53771

### PR DESCRIPTION
**Pull request by j-hao**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [X] OS X
  - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by LnL7** [comment]
Do we even want a separate `bin` output, the regular output only contains bash completion.

**Comment by dezgeg** [comment]
I would go for just `[ "out" "man" ]`, at least looking at the contents on Linux. Don't know if darwin places some extra stuff that would benefit splitting.

**Comment by LnL7** [comment]
@dezgeg nope, just the bash completion

**Comment by j-hao** [comment]
Removed bin

**Pull request merged**
