### PR TITLE
nixos/prometheus: remote_{read,write} support

### PR DESCRIPTION
**Pull request by 0x4A6F**
###### Motivation for this change
- add initial [remote_write](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) and [remote_read](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read) support

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 0x4A6F** [comment]
Updated based on work in #107398.

**Comment by WilliButz** [comment]
@GrahamcOfBorg test prometheus

**Review by WilliButz — APPROVED** [review]
LGTM :+1:

**Comment by flokli** [comment]
@WilliButz @0x4A6F any reservations against backporting this to 20.09? It shouldn't affect existing configs.

**Comment by 0x4A6F** [comment]
No objections from my side.

**Pull request merged**
