### PR TITLE
proj: update from 4.8.0 to 4.9.1

### PR DESCRIPTION
**Pull request by vbgl**

### CODE REVIEW

**Comment by vcunat** [comment]
Would you like to become a maintainer of this package? (Mostly to get e-mails when build status *changes* on hydra.nixos.org, and being listed in the package so people will know whom to contact about it.)

**Comment by vcunat** [comment]
Pushed after testing that merkaartor and qgis still build, but that question still remains...

**Comment by vbgl** [comment]
Thanks. I’ve listed myself as maintainer of the `proj` package in 710b3e6.

**Comment by vcunat** [comment]
Hmm, I wonder why you haven't pushed this PR yourself.

**Comment by vbgl** [comment]
Sometimes I feel more confident when someone else double-checks my commits.

**Comment by vcunat** [comment]
There wasn't really much to check in this case. I didn't even read the news file, which I do for bumps I author.

**Pull request closed without merging**
