### PR TITLE
nc4nix: 0-unstable-2024-03-01 -> 0-unstable-2024-05-24; nextcloudPackages: update

### PR DESCRIPTION
**Pull request by pyrox0**
Updates nc2nix to include a commit that generates SRI hashes instead of sha256 hashes for extensions.

Also updates the nextcloud2{8,9}Packages package sets, in order to have those new hashes. This causes no rebuilds of the derivations besides those that are updated.
Note that out-of-tree usages of `fetchNextcloudApp` will not throw an error with `sha256`, but this is one step towards being able to do that(per #325892)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by onny** [comment]
Result of `nixpkgs-review pr 326442` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>nc4nix</li>
  </ul>
</details>

**Comment by onny** [comment]
This is great, thank you :)

**Comment by dotlambda** [comment]
> This causes no rebuilds of the derivations besides those that are updated.

Quite the opposite. It causes everything to fail to build. How was this not even tested??

**Comment by alois31** [comment]
> > This causes no rebuilds of the derivations besides those that are updated.
> 
> Quite the opposite. It causes everything to fail to build. How was this not even tested??

Testing does not help for FODs when the thing with the specified hash (in this case, the zip file fetched by upstream nc4nix) is already in the store.

**Comment by dotlambda** [comment]
> > > This causes no rebuilds of the derivations besides those that are updated.
> > 
> > 
> > Quite the opposite. It causes everything to fail to build. How was this not even tested??
> 
> Testing does not help for FODs when the thing with the specified hash (in this case, the zip file fetched by upstream nc4nix) is already in the store.

But it's not. The hashes aren't the same.

**Comment by alois31** [comment]
> But it's not. The hashes aren't the same.

Upstream nc4nix uses `fetchurl`, which does not uncompress the file, while nixpkgs uses `fetchzip`, which does. So the hashes are going to be different, but you aren't going to notice that when you already had the zip file in the store because you used upstream nc4nix.

**Comment by dotlambda** [comment]
> > But it's not. The hashes aren't the same.
> 
> Upstream nc4nix uses `fetchurl`, which does not uncompress the file, while nixpkgs uses `fetchzip`, which does. So the hashes are going to be different, but you aren't going to notice that when you already had the zip file in the store because you used upstream nc4nix.

That doesn't excuse @onny merging this without testing.

**Comment by pyrox0** [comment]
I pushed an updated one that mimics fetchzip, please go to that. I apologize for not testing this more thoroughly. 

#326947

**Pull request merged**
