### PR TITLE
 samba: fix broken sssd because of bundled samba dependencies

### PR DESCRIPTION
**Pull request by wucke13**
###### Description of changes

Fix for fix for https://github.com/NixOS/nixpkgs/issues/205859

Backport PR: https://github.com/NixOS/nixpkgs/pull/208790

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wucke13** [comment]
@GrahamcOfBorg build samba

**Comment by illustris** [comment]
merge conflict caused by https://github.com/NixOS/nixpkgs/commit/555ba5840809bb5842e115877f80901162b618d6. Can you please rebase on master?

Also, I think the PR name needs to have `samba: ` as the prefix

**Comment by kangaroo** [comment]
@wucke13 do you have a chance to update this PR, or do you want to give me write access to it?

**Comment by wucke13** [comment]
@kangaroo I rebased :smile:

**Comment by wucke13** [comment]
@GrahamcOfBorg build samba

**Review by illustris — APPROVED** [review]
A full nixpkgs-review is too big for me to build, so I ran a few nixos tests manually. LGTM.

**Comment by wucke13** [comment]
@SuperSandro2000 what do you think, can we merge this soonish? And how about the [backport](https://github.com/NixOS/nixpkgs/pull/208790)?

**Comment by wucke13** [comment]
@Lassulus would you mind checking and eventually merging this and the [backport sister PR](https://github.com/NixOS/nixpkgs/pull/208790)?

**Pull request merged**
