### PR TITLE
Rmilter+rspamd packages and NixOS modules

### PR DESCRIPTION
**Pull request by avnik**

### CODE REVIEW

**Comment by peti** [comment]
LGTM. :+1:

**Comment by avnik** [comment]
@peti and who can do it? ;)

**Comment by peti** [comment]
@avnik, I can merge the patch. I'd just like to wait another day or two to give others a chance to say their opinion.

**Comment by avnik** [comment]
@peti Good, thank you.
I hope no other changes  in `ids.nix` happens these couple of days ;)

**Pull request merged**
