### PR TITLE
 git: 2.16.2 -> 2.17.0

### PR DESCRIPTION
**Pull request by layus**
Fixed the perl lib path issues detected in #38636

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by layus** [comment]
It would also be wiser to get this on staging rather than on master.

**Comment by layus** [comment]
There is such a mess now with the staging merges and reverts interleaved.
This one should be merged to staging, and 2601941 to master.

**Review by LnL7 — APPROVED** [review]

**Comment by LnL7** [comment]
Yeah, staging.

**Comment by dtzWill** [comment]
Thanks for tackling this!

**Pull request merged**
