### PR TITLE
mtools: 4.0.33 -> 4.0.34

### PR DESCRIPTION
**Pull request by etu**
###### Motivation for this change
Fix bug for recursive use, see release announcement: https://lists.gnu.org/archive/html/info-gnu/2021-07/msg00010.html

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 132211` at 7887182e run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>bootiso</li>
    <li>unetbootin</li>
    <li>wimlib</li>
    <li>woeusb</li>
  </ul>
</details>
<details>
  <summary>7 packages built successfully:</summary>
  <ul>
    <li>fwanalyzer</li>
    <li>fwup</li>
    <li>gnome.gnome-boxes</li>
    <li>ipxe</li>
    <li>memtest86-efi</li>
    <li>mtools</li>
    <li>multibootusb</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl3` is a deprecated license, please check if project uses `gpl3Plus` or `gpl3Only` and change `meta.license` accordingly.

Near pkgs/tools/filesystems/mtools/default.nix:23:5:
```
   |
23 |     license = licenses.gpl3;
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/tools/filesystems/mtools/default.nix:19:3:
```
   |
19 |   meta = with lib; {
   |   ^
```
</li>
  </ul>
</details>

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 132211` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>multibootusb</li>
  </ul>
</details>
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>bootiso</li>
    <li>wimlib</li>
    <li>woeusb</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>fwanalyzer</li>
    <li>fwup</li>
    <li>gnome.gnome-boxes</li>
    <li>ipxe</li>
    <li>memtest86-efi</li>
    <li>mtools</li>
    <li>syslinux</li>
    <li>unetbootin</li>
  </ul>
</details>

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 132211` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>multibootusb</li>
  </ul>
</details>
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>bootiso</li>
    <li>wimlib</li>
    <li>woeusb</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>fwanalyzer</li>
    <li>fwup</li>
    <li>gnome.gnome-boxes</li>
    <li>ipxe</li>
    <li>memtest86-efi</li>
    <li>mtools</li>
    <li>syslinux</li>
    <li>unetbootin</li>
  </ul>
</details>

**Comment by Profpatsch** [comment]
> packages failed to build:

I have no idea what this means. Were they not building before this change? Where’s the build logs?

I’m just going to merge for now, the package seems to build just fine.

**Pull request merged**
