### PR TITLE
pythonPackages.pyqt4: 4.12 -> 4.12.3

### PR DESCRIPTION
**Pull request by eduardosm**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by eduardosm** [comment]
Result of `nixpkgs-review pr 123263` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>appleseed</li>
    <li>seexpr</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>flatcam</li>
    <li>python38Packages.pyqt4</li>
    <li>python39Packages.pyqt4</li>
  </ul>
</details>

**Review by jonringer — APPROVED** [review]
LGTM

failures are broken on target branch
```
https://github.com/NixOS/nixpkgs/pull/123263

10 packages marked as broken and skipped:
gnuradio3_7 gnuradio3_7Packages.ais gnuradio3_7Packages.gnuradio gnuradio3_7Packages.gsm gnuradio3_7Packages.limesdr gnuradio3_7Packages.nacl gnuradio3_7Packages.osmosdr gnuradio3_7Packages.rds hplipWithPlugin_3_16_11 hplip_3_16_11

2 packages failed to build:
appleseed seexpr

3 packages built:
flatcam python38Packages.pyqt4 python39Packages.pyqt4
```

**Comment by L-as** [comment]
This updates breaks `python2Packages.pyqt4` for me.
```
$ nix shell --impure --expr "with import (builtins.getFlake \"github:NixOS/nixpkgs/fe93438d3aee77e20ef4560abadcd5e2cdd9ff82\") {}; python2.withPackages (ps: [ ps.pyqt4 ])" -c python2
Python 2.7.18 (default, Apr 19 2020, 21:45:35) 
[GCC 10.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt4.QtCore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named sip
>>> 
$ nix shell --impure --expr "with import (builtins.getFlake \"github:NixOS/nixpkgs/f515d1f93c403dae2947924ceda8556afc4ad788\") {}; python2.withPackages (ps: [ ps.pyqt4 ])" -c python2
Python 2.7.18 (default, Apr 19 2020, 21:45:35) 
[GCC 10.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt4.QtCore
>>> 
```

**Comment by L-as** [comment]
4.12.1 seems to be the last version that works. @eduardosm Is there any reason you need a version later than 4.12.1?

**Comment by eduardosm** [comment]
> 4.12.1 seems to be the last version that works. @eduardosm Is there any reason you need a version later than 4.12.1?

@L-as Not really, feel free to open a downgrade PR. It might be also a good idea to include `pythonImportsCheck`.

Looking at the diff between 4.12.1 and 4.12.2, I think it is caused by
```diff
-    argv = ['"' + sipcfg.sip_bin + '"', '-w']
+    argv = ['"' + sipcfg.sip_bin + '"', '-w', '-n', 'PyQt4.sip']
```
in `configure.py`.

I don't have a machine with nix right now, so I can't run tests.

**Pull request merged**
