### PR TITLE
dockerTools: optionally preserve directory symlinks

### PR DESCRIPTION
**Pull request by ryantrinkle**
In some cases, this seems to save a lot (>40%) of space.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ryantrinkle** [comment]
@lethalman It would be great to get your input on this.  I can't say I fully understand the implications of the -k parameter here, but I did do some testing without it and my image, at least, seemed to work just fine (and was much smaller).  This patch should, however, preserve the existing behavior by default.

**Review by puffnfresh — COMMENTED** [review]
Should we preserve the existing behaviour? What's the purpose?

**Comment by Ericson2314** [comment]
@puffnfresh I believe this does preserve existing behavior?

**Comment by puffnfresh** [comment]
@Ericson2314 yeah, but why?

**Comment by ryantrinkle** [comment]
@puffnfresh I think certain setup scripts might depend on the existing behavior; plus, I don't totally understand the benefit of the existing behavior, but it looks like it was intentional, so I didn't want to mess with it.

It does look like the `-k` may have been added in error, though: [this commit](https://github.com/NixOS/nixpkgs/commit/186ed3bf8f2ef0454991025d0d09c2872580d63d) says `rsync contents with -keep-dirlinks`, but `--keep-dirlinks` is `-K`, not `-k`, at least according to my rsync's docs.

**Comment by ryantrinkle** [comment]
@puffnfresh I think it may be best to just merge this with the backwards compatibility in place.  I don't personally feel that I understand this code well enough to warrant hitting people downstream with substantive changes, even though I do agree that the old behavior is probably wrong.  In the future, if we want to change the default behavior to be this behavior, it will be very easy.

**Review by fpletz — APPROVED** [review]

**Comment by NeQuissimus** [comment]
ping on this, just built an image that had essentially two copies of everything. This solves my mystery :D

**Comment by gleber** [comment]
Any updates on this?

**Comment by gilligan** [comment]
@ryantrinkle While i've been using dockerTools several times i am somehow drawing a mental blank on this one. 

- Could you add a short but meaningful *description* to the PR that explains this change
- Is `keepContentsDirlinks` a good name for this? It says what it does on an implementation level, but maybe this could be described more from a user perspective?
- As mentioned by others it seems unclear if both ways are needed at all. Just adding it as option because nobody quite knows doesn't seem like a good way forward. Maybe there should be a deprecation date for when only one way will be available. I guess there is no precedence for a workflow like this in nixpkgs though ;/
- *Documentation*: Can you please, please, please add something to the documentation about this option? Because otherwise it simply does not exist from a user/newbie perspective

**Comment by BjornMelgaard** [comment]
Any updates?

**Pull request merged**
