### PR TITLE
wasmtime : 0.12.0 -> 0.15.0

### PR DESCRIPTION
**Pull request by nomeata**
and enable tests again, now that upstream fixed stuff.

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build wasmtime

**Comment by nomeata** [comment]
Drawin build failure reported at https://github.com/bytecodealliance/wasmtime/issues/1556

**Comment by Mic92** [comment]
@GrahamcOfBorg build wasmtime

**Comment by nomeata** [comment]
@GrahamcOfBorg build wasmtime

**Comment by nomeata** [comment]
Should we do the versoin bump without enabling tests? They are not enabled on master (so no regression). Or maybe only test on x86 for now?

**Comment by nomeata** [comment]
I disabled the test suite on master for now. One step at a time.

**Pull request merged**
