### PR TITLE
urlwatch: add jq

### PR DESCRIPTION
**Pull request by tyleroconnell**
###### Motivation for this change

Allow use of urlwatch's [built-in jq filter](https://urlwatch.readthedocs.io/en/latest/filters.html) without separate installation or modifying the default package.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tyleroconnell** [comment]
Result of `nixpkgs-review pr 156569` run on x86_64-linux

```
1 package built:
urlwatch
```

**Comment by tyleroconnell** [comment]
Force re-pushed to match commit message to [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md) standards that I followed for the PR name.

**Comment by tyleroconnell** [comment]
@fabaff you're not one of the maintainers listed for this package but I was wondering if you might be willing/able to review this small addition since you're the most active editor of this package of late and seem to have write access in #146186

I'm seeing that [first-time contributors need a maintainer to approve running workflows](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)

**Review by 4z3 — APPROVED** [review]
Seeing all that urlwatch-unrelated stuff in `propagatedBuildInputs` here, I cannot argue against adding `jq`. That said, I'm pondering whether there is not a better way to add libraries for hooks. As far as I'm concerned, I'm simply spawning subprocesses and have stopped worrying about Python a long time ago =) 

https://p.krebsco.de/0525qq1

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 156569` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>urlwatch</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
It looks like that most optional dependencies are shipped already. I'm fine with adding `jq` as for end-users it's not always easy to figure out what's going on if an optional dependency is missing.

**Pull request merged**
