### PR TITLE
cc-wrapper: propagate man and info to propagated-build-inputs

### LINKED ISSUE #43547: binutils and gcc manpages hidden by wrappers
## Issue description

The `gcc` and `bin-utils` wrappers don't expose the underlying derivations' `man` outputs.

### Steps to reproduce

1. `nix run nixpkgs.binutils.man -c man ld`
2. Notice that the manpage is not found

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.16.14, NixOS, 18.03.132646.08d245eb31a (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.12pre5788_e3013543`
 - channels(root): `"nixos-18.03.132646.08d245eb31a, nixpkgs-18.09pre142651.95a8cb3ade1"`
 - channels(ben): `"nixpkgs-18.03pre126020.931a0b8be80"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

### PR DESCRIPTION
**Pull request by oxij**
Should fix #43547.

### CODE REVIEW

**Review by Ericson2314 — APPROVED** [review]

**Comment by Ericson2314** [comment]
Thanks so much!!

**Comment by oxij** [comment]
You're welcome. Please also have a look on other stdenv changes in this batch: #44517 and #44518.

**Comment by dezgeg** [comment]
Does this actually work? I don't think either `environment.systemPackages` or `nix-env -i` will follow propagated build inputs.

I think you should be just able to do:
````
ln -s ${cc.man} $man
````

**Comment by oxij** [comment]
> Does this actually work? I don't think either `environment.systemPackages` or `nix-env -i` will follow propagated build inputs.

I'm not sure as I can't reproduce the original issue.

https://github.com/NixOS/nixpkgs/issues/43547#issuecomment-410093707 says

> `nix-support/propagated-build-inputs`, which is strictly stronger

and I made this assuming that's correct. But if it's not, then I feel like `propagated-user-env-packages` makes more sense there semantically (judging by the name, not by the actual semantics whatever it is).

Thinking some more about this, however, I think that a better way is to simply sidestep all of this and symlink `.man` and `.info` outputs to the originals like so

```nix
ln -s ${bintools.man} $man
```

instead of doing it like now

```nix
printWords ${bintools.man or ""} >> $man/nix-support/propagated-build-inputs
```

(or `propagated-user-env-packages` like it was before). I'm now rebuilding `stdenv` with that change to see what happens (found 1 bug in `stdenv` already).

Btw, if we are discussing this, there's also `nativeTools` option which does similar things in `bintools-wrapper`, that goes to `propagated-user-env-packages` (and I think that's correct, semantically speaking).

**Comment by oxij** [comment]
> Thinking some more about this, however

... which is exactly your suggestion above too. I gotta get a coffee, it seems. :)

**Comment by oxij** [comment]
See #44558.

**Comment by Ericson2314** [comment]
I'm sorry. I might has improperly tested that. (Worse, I have some dejavu as if I made the same mistake before.)

In a post`-strictDeps` world, it would actually make sense to make `propagatedBuildInputs`do that, but there's nothing wrong with the symlink thing so let's just do that.

**Comment by oxij** [comment]
@Ericson2314 Nah, don't mind, breaking things is half the fun after all.

#44558 needs some testing love on Darwin, though.

**Comment by dezgeg** [comment]
> But if it's not, then I feel like `propagated-user-env-packages` makes more sense there semantically 

I agree, I also thought `propagated-user-env-packages` would work. But I guess it's only looked in the main output and not in `man` or the others.

> In a post-strictDeps world, it would actually make sense to make propagatedBuildInputsdo that, but there's nothing wrong with the symlink thing so let's just do that.

Why? propagatedBuildInputs are only intended for building stuff that depends on the package. In multiple-outputs packages they aren't even visible at runtime, because the `propagated-build-inputs` file only exists in the `dev` output. Of course this strictDeps thing will never, ever be going to happen for native compilation so it's a moot point, but anyway...

**Comment by Ericson2314** [comment]
You said it yourself; it isn't used on things people want to install anyways. `propagatedBuildInputs`, rightly used, is basically only for libraries that rely on other libraries. It wouldn't be used by things people install anyways, even if it weren't for multiple outputs.

OTOH, if you manually install a `dev` output, I don't see why you shouldn't get the propagated deps too. Otherwise, the headers are useless.

**Comment by dezgeg** [comment]
Manually installing `.dev` outputs isn't going to work anyway because setup hooks won't be run. It's just not supported (currently).

**Pull request merged**
