### PR TITLE
firefox: 86.0.1 -> 87.0; firefox-esr: 78.8.0esr -> 78.9.0esr

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://www.mozilla.org/en-US/firefox/78.9.0/releasenotes/
https://www.mozilla.org/en-US/security/advisories/mfsa2021-11/

https://www.mozilla.org/en-US/firefox/87.0/releasenotes/
https://www.mozilla.org/en-US/security/advisories/mfsa2021-10/

###### Things done

- [x] Completed `nixos/tests/firefox.nix`
- Tested on
  - [x] x86_64 Linux X11
  - [x] x86_64 Linux Wayland & Pipewire
  - [ ] aarch64 Linux X11
  - [ ] aarch64 Linux Wayland & Pipewire

### CODE REVIEW

**Comment by mweinelt** [comment]
I couldn't get screensharing via pipewire to work, though I can't rule other things in my environment. I'll reboot later to rule out some of those.

**Comment by ajs124** [comment]
x86_64 Linux X11 seems to work for me. Even screen sharing :smile:

**Comment by mweinelt** [comment]
> I couldn't get screensharing via pipewire to work, though I can't rule out other things in my environment. I'll reboot later to rule out some of those.

Works after reboot.

**Comment by mweinelt** [comment]
So aarch64 went untested? :disappointed:

**Comment by vcunat** [comment]
A tested building both packages.

**Comment by lovesegfault** [comment]
I didn't update the list, but I tested on my personal AArch64 system as well.

**Pull request merged**
