### PR TITLE
nixos/tests: add missing tests

### PR DESCRIPTION
**Pull request by B4dM4n**
###### Motivation for this change

Some tests from the `nixos/tests` folder were missing in the `all-tests.nix` file. This meant they couldn't be run from the `nixosTests` attribute set and therefore not be linked to their packages.

###### Things done

Build the following tests on `x86_64-linux`:

Succeeded:

- `nixosTests.brscan5`
- `nixosTests.emacs-daemon`
- `nixosTests.haka`
- `nixosTests.iscsi-multipath-root`
- `nixosTests.isso`
- `nixosTests.jenkins-cli`
- `nixosTests.k3s-single-node`
- `nixosTests.k3s-single-node-docker`
- `nixosTests.molly-brown`
- `nixosTests.pict-rs`
- `nixosTests.resolv`
- `nixosTests.rstudio-server`
- `nixosTests.rsyncd`
- `nixosTests.soapui`

Failed:

- `nixosTests.doh-proxy-rust`: fix in #156224
- `nixosTests.fenics`: dependency does not compile ( [Hydra build](https://hydra.nixos.org/build/165166292) )
- `nixosTests.geth`: fix in #156220
- `nixosTests.mediatomb`: fix in #156232
- `nixosTests.riak`: marked as insecure
- `nixosTests.teeworlds`: fix in #156205
- `nixosTests.wine`: fix in #156200

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by symphorien** [comment]
Maybe it's a good occasion to add them to passthru.tests on the corresponding packages?

**Comment by B4dM4n** [comment]
Yeah, this would be a good time to improve `passthru.tests` usage.

I will push the update soon.

**Comment by B4dM4n** [comment]
Links from all packages to the tests are added.

Interestingly some packages already referred to tests which were not present in `nixosTests`:

https://github.com/NixOS/nixpkgs/blob/8f3c7d0ae3cd8e0590cdde598a3cb4d062d62812/pkgs/applications/networking/sync/rsync/default.nix#L62

https://github.com/NixOS/nixpkgs/blob/8f3c7d0ae3cd8e0590cdde598a3cb4d062d62812/pkgs/servers/gemini/molly-brown/default.nix#L18

https://github.com/NixOS/nixpkgs/blob/8f3c7d0ae3cd8e0590cdde598a3cb4d062d62812/pkgs/games/teeworlds/default.nix#L40

**Comment by symphorien** [comment]
> Interestingly some packages already referred to tests which were not present in nixosTests:

maybe ofborg does not label "passthru.tests does not evaluate" as a failure (because most packages don't have one at all) so people don't notice it

**Review by symphorien — APPROVED** [review]

**Review by fgaz — APPROVED** [review]

**Pull request merged**
