### PR TITLE
appimage-env: remove xorg.libxshmfence

### PR DESCRIPTION
**Pull request by davidak**
###### Description of changes

was needed for apple-music-electron which is now EOL

Came up in https://github.com/NixOS/nixpkgs/issues/193593

If you need it for anything else, feel free to add it again.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by davidak** [comment]
To test this, nixpkgs-review wants to download 18 GB packages... i don't think that is useful and i don't have so much free disk space.

> 72 packages updated:
> altair anki Anytype appimage-run appimage-run-tests beekeeper-studio betterdiscord-installer bloomrpc bootstrap-studio buttercup-desktop caprine chain-desktop-wallet chrysalis cider cozydrive davinci-resolve devdocs-desktop ElectronMail electronplayer firefly-desktop flexoptix-app framesh fspy heroic irccloud joplin-desktop keeweb lbry-desktop ldtk ledger-live-desktop lens losslesscut lunar-client marktext mathpix-snipping-tool mobilecoin-wallet molotov MyCrypto neo4j-desktop notable notion-app-enhanced-v2.0.18 nuclear-v0.6.6 octant-desktop p3x-onenote passky-desktop Patchwork plexamp radicle-upstream rambox rambox-pro raven-reader remnote saleae-logic session-desktop sonixd standardnotes station steam-rom-manager Sylk timeular trezor-suite tusk uhk-agent uhk-udev-rules unityhub via vial wootility ytmdesktop zecwallet-lite zettlr zulip

I hope it's not secretly a needed dependency for any of these.

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 194230` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>appimage-run-tests</li>
  </ul>
</details>

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 194230` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>tusk</li>
  </ul>
</details>

**Comment by davidak** [comment]
I tested one single package (tusk) and it still works.

**Comment by davidak** [comment]
I think this would be good for staging since it is not urgend, but i'm unable to rebase... so here we are. If you know which command i have to run to rebase on staging, let me know...

**Comment by Artturin** [comment]
> I think this would be good for staging since it is not urgend, but i'm unable to rebase... so here we are. If you know which command i have to run to rebase on staging, let me know...

https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging

**Comment by davidak** [comment]
I tried to build one package as test, but it builds the whole channel, so that is too much.

> 13/695/854 built, 836 copied (5374.9/5377.5 MiB)

**Comment by davidak** [comment]
What is needed to get this merged?

**Comment by davidak** [comment]
I used nixpkgs-review with `--checkout commit`, so it builds the branch at the state of commit und not merged the current staging into it. This way it downloaded 435 packages instead of building them.

So this change looks good. It should only cause issues if any other AppImage relies implicitly on the removed dependency.

**Comment by SuperSandro2000** [comment]
Staging should get commits which cause many rebuilds. This only causes only a few, so it should target master.

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 194230` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>tusk</li>
  </ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]

**Review by FliegendeWurst — APPROVED** [review]
I think it's safe to remove, it was only required for certain Electron versions.

**Pull request merged**
