### PR TITLE
scrcpy: 1.22 -> 1.23

### PR DESCRIPTION
**Pull request by msfjarvis**
###### Motivation for this change

Bumps [scrcpy](https://github.com/Genymobile/scrcpy) to the latest [1.23](https://github.com/Genymobile/scrcpy/releases/tag/v1.23) release.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SubhrajyotiSen** [comment]
@msfjarvis I was unable to build this for `x86_64-darwin`

```
nix-build -A scrcpy
these derivations will be built:
  /nix/store/yzampq1bzq7dfj0g0m8bqv5gxwkdrdcz-scrcpy-1.23.drv
building '/nix/store/yzampq1bzq7dfj0g0m8bqv5gxwkdrdcz-scrcpy-1.23.drv'...
unpacking sources
unpacking source archive /nix/store/ad22snlbphpspxcv0p7xwws27wzp10bn-source
source root is source
patching sources
configuring
meson flags: --buildtype=plain         --libdir=/nix/store/h57mckvpzg378k0k3mpy9xyp5m5wcn50-scrcpy-1.23/lib --libexecdir=/nix/store/h57mckvpzg378k0k3mpy9xyp5m5wcn50-scrcpy-1.23/libexec         --bindir=/nix/store/h57mckvpzg378k0k3mpy9xyp5m5wcn50-scrcpy-1.23/bin --sbindir=/nix/store/h57mckvpzg378k0k3mpy9xyp5m5wcn50-scrcpy-1.23/sbin         --includedir=/nix/store/h57mckvpzg378k0k3mpy9xyp5m5wcn50-scrcpy-1.23/include         --mandir=/nix/store/h57mckvpzg378k0k3mpy9xyp5m5wcn50-scrcpy-1.23/share/man --infodir=/nix/store/h57mckvpzg378k0k3mpy9xyp5m5wcn50-scrcpy-1.23/share/info         --localedir=/nix/store/h57mckvpzg378k0k3mpy9xyp5m5wcn50-scrcpy-1.23/share/locale         -Dauto_features=enabled         -Dwrap_mode=nodownload         --prefix=/nix/store/h57mckvpzg378k0k3mpy9xyp5m5wcn50-scrcpy-1.23
The Meson build system
Version: 0.60.3
Source dir: /private/tmp/nix-build-scrcpy-1.23.drv-0/source
Build dir: /private/tmp/nix-build-scrcpy-1.23.drv-0/source/build
Build type: native build
Project name: scrcpy
Project version: 1.23
C compiler for the host machine: clang (clang 11.1.0 "clang version 11.1.0")
C linker for the host machine: clang ld64 530
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /nix/store/k69qr6dr8hm6q1ma8f7fp5g2i9f9ipjc-pkg-config-wrapper-0.29.2/bin/pkg-config (0.29.2)
Run-time dependency libavformat found: YES 58.76.100
Run-time dependency libavcodec found: YES 58.134.100
Run-time dependency libavutil found: YES 56.70.100
Run-time dependency sdl2 found: YES 2.0.14
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency libusb-1.0 found: NO (tried pkgconfig and framework)

app/meson.build:108:8: ERROR: Dependency "libusb-1.0" not found, tried pkgconfig and framework

A full log can be found at /private/tmp/nix-build-scrcpy-1.23.drv-0/source/build/meson-logs/meson-log.txt
builder for '/nix/store/yzampq1bzq7dfj0g0m8bqv5gxwkdrdcz-scrcpy-1.23.drv' failed with exit code 1
error: build of '/nix/store/yzampq1bzq7dfj0g0m8bqv5gxwkdrdcz-scrcpy-1.23.drv' failed
```

The following diff resolved it for me:
```
diff --git a/pkgs/misc/scrcpy/default.nix b/pkgs/misc/scrcpy/default.nix
index 07386e05aee..1a49d2d9e35 100644
--- a/pkgs/misc/scrcpy/default.nix
+++ b/pkgs/misc/scrcpy/default.nix
@@ -7,6 +7,7 @@
 , ffmpeg
 , libusb1
 , SDL2
+, cmake
 }:

 let
@@ -36,7 +37,7 @@ stdenv.mkDerivation rec {
       --replace "SDL_RENDERER_ACCELERATED" "SDL_RENDERER_ACCELERATED || SDL_RENDERER_SOFTWARE"
   '';

-  nativeBuildInputs = [ makeWrapper meson ninja pkg-config ];
+  nativeBuildInputs = [ makeWrapper meson ninja pkg-config cmake libusb1 ];

   buildInputs = [ ffmpeg SDL2 ] ++ lib.optionals stdenv.isLinux [
     libusb1
```

**Comment by msfjarvis** [comment]
> @msfjarvis I was unable to build this for `x86_64-darwin`
> 

Should've expected that 🤦🏼 

Can you try with 11b46b01deb6?

**Review by SubhrajyotiSen — APPROVED** [review]

**Comment by msfjarvis** [comment]
ping @DeltaEvo @lukeadams

**Review by DeltaEvo — APPROVED** [review]

**Review by c0bw3b — APPROVED** [review]
Result of `nixpkgs-review pr 161463` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>scrcpy</li>
  </ul>
</details>

Runs ok

**Pull request merged**
