### PR TITLE
clisp_2_44_1, libsigsegv_25: delete

### PR DESCRIPTION
**Pull request by orivej**
###### Motivation for this change

These files are obsolete and unused. CLISP 2.44.1 fails to build with glibc 2.26.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

/cc @7c6f434c

### CODE REVIEW

**Comment by orivej** [comment]
@vcunat I tried to add him as a reviewer, but GitHub did not let me, I posted the PR and tried again, and finally I've edited the description.

**Comment by vcunat** [comment]
For me the reviewers field is just "loading suggestions" forever and thus is unusable.

**Comment by 7c6f434c** [comment]
Oh well, apparently we have lost SBCL bootstrap anyway.

**Pull request merged**
