### PR TITLE
python3Packages.scipy: 1.6.0 -> 1.6.1

### PR DESCRIPTION
**Pull request by rmcgibbo**
###### Motivation for this change
https://github.com/scipy/scipy/releases/tag/v1.6.1

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Huh. the bot is weird. I'll just open a new PR against staging myself.

**Comment by SuperSandro2000** [comment]
> Huh. the bot is weird. I'll just open a new PR against staging myself.

Nah, it is supposed to work like that. I could have just reopened the PR.

**Pull request closed without merging**
