### PR TITLE
nodejs: cleanup files no longer needed

### PR DESCRIPTION
**Pull request by cko**
###### Things done

- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by fpletz** [comment]
NodeJS 5.x is not maintained upstream anymore and thus should be removed.

**Comment by fpletz** [comment]
Also backported the removal of `nodejs-5_x` from all-packages.nix by @grahamc: 9634155e3c5764b176e09b32bae8e3eec162c1df

**Comment by domenkozar** [comment]
This fails on 16.09: http://hydra.nixos.org/build/43456574/nixlog/1/raw

**Comment by cko** [comment]
This is because node 0.10 (which had reached end of LTS) has been removed from master [1] but is still on the 16.09 branch [2].
[1] https://github.com/NixOS/nixpkgs/commit/162c65fc87d8e0fc450d2f95dda3f7b3b91987a2
[2] https://github.com/NixOS/nixpkgs-channels/tree/nixos-16.09/pkgs/development/web/nodejs

**Pull request merged**
