### PR TITLE
qdiskinfo: add themes

### PR DESCRIPTION
**Pull request by RoyDubnium**
## Description of changes
Adds support for the CrystalDiskInfo themes that QDiskInfo supports.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by s0me1newithhand7s — APPROVED** [review]

**Comment by RoyDubnium** [comment]
Merge conflict resolved

**Comment by pbsds** [comment]
please rebase rather than merge from master

**Comment by RoyDubnium** [comment]
Done

**Comment by pbsds** [comment]
This one took me a bit of time to understand, but the moment i renamed `isTheme` to `isThemed` it suddenly clicked.
The `theme` input is prone to collide with a future package (`theme-sh` already exists), and the logic around `rightCharacter` and `"custom"` is in my opinion a bit too convoluted.
I took the liberty of refactoring the theming logic to use an attribute set, and provide all the packaged themes via the `passthru`. In the process it also became trivial to add tests for each theme.

The usage pattern thus becomes
```nix
qdiskinfo.override { themeBundle = qdiskinfo.themeBundles.aoi; }
```

I ran the tests:
```
/nix/store/dlm4hxy3r8bvzv8s6xfjmzpb71m7fpkl-qdiskinfo-aoi-0.3
/nix/store/d55svzcp5ndjd89pk241lmwvr6jzhhbi-qdiskinfo-kureikei-0.3
/nix/store/x8jfbdldds1awd6csrv06gnpip3i395b-qdiskinfo-kureikeiAsyuihira-0.3
/nix/store/4qh8kb07vf2aa7qvw8lacwqgwamjbi09-qdiskinfo-kureikeiBikini-0.3
/nix/store/7bzb26l6pq1lks59b2lq8c9x5jgiri9c-qdiskinfo-kureikeiHasumikaoru-0.3
/nix/store/jz1hza6jvs4mqgznm57nn43rsmbxs2cf-qdiskinfo-kureikeiHomebuiltComputer-0.3
/nix/store/nkr4m5cv6jlbyzsb9f801q9hz614jk4x-qdiskinfo-kureikeiKohakumuro-0.3
/nix/store/xx4j5zi6rasmjn5dx4r3iyqx3vffbdzz-qdiskinfo-kureikeiKosake-0.3
/nix/store/r5smrgwha8lkilqkd44ypazh37adw6wf-qdiskinfo-kureikeiKunimi-0.3
/nix/store/b00nrsq2l978zzj2hmwd5ka7bcgwmzj7-qdiskinfo-kureikeiMaru-0.3
/nix/store/zp6rjc08spdvv12jv7rb5v3v4mpbvkpw-qdiskinfo-kureikeiMugya-0.3
/nix/store/0gyirm001sh42wayh36823anh7bhqz5s-qdiskinfo-kureikeiNanatunatu-0.3
/nix/store/h2x2awgbl5blcqzbxrkkqjzjx8q4wgw1-qdiskinfo-kureikeiNekopan-0.3
/nix/store/6zfbaqk8wga9bss17nqg3cnbvw6xk5py-qdiskinfo-kureikeiNyamco-0.3
/nix/store/v1l31fwfjmijhgrrws5adp0dk1kck3lv-qdiskinfo-kureikeiPoyoyonchihiro-0.3
/nix/store/v5xr53mdzizg1sj62xmpa9hlv0l564dl-qdiskinfo-kureikeiPresent-0.3
/nix/store/mbm4gsyrwy57spjhyni326jpwjpf2wq1-qdiskinfo-kureikeiRecoding-0.3
/nix/store/hb4iyf6xkfhkj38hcjnmy1wd20nbir6p-qdiskinfo-kureikeiRecodingKimiya-0.3
/nix/store/pwvh5x1j3bxvmpi05qpcanilwimbzwy9-qdiskinfo-kureikeiShitimiNanami-0.3
/nix/store/xzfkd05y2zzr8c9d950lrsx2hhib8qhc-qdiskinfo-kureikeiSummerKimono-0.3
/nix/store/561w7hapqk5gsyxcy24by4mqyw91yc5c-qdiskinfo-kureikeiTakiOuno-0.3
/nix/store/ddshwy5insf6izzkmhqz3qm5jqmy1zi7-qdiskinfo-kureikeiTori-0.3
/nix/store/pa6v5li0h33j697qk671rkr4bv3g1bs2-qdiskinfo-kureikeiUniform-0.3
/nix/store/x7vrsj97ks69xxw09aisqa1lp8xxzkxh-qdiskinfo-kureikeiYoite-0.3
/nix/store/8bh0ghw4xhmw3qvnr3ypwybvcbj21587-qdiskinfo-shizuku-0.3
/nix/store/q6f86dsfacvyyvgiwp1953daq4v6jlc6-qdiskinfo-shizuku5thAnniversary-0.3
/nix/store/w7i0bwvg6yfgmicyc32wv11p7cx2h99d-qdiskinfo-shizuku7thAnniversary-0.3
/nix/store/7f32ax4wyhh1zrwvfhgjfvw4gm0nfsyb-qdiskinfo-shizukuDate-0.3
/nix/store/da0b1gq4v3bvcim5lbzrv1fcl505lhh4-qdiskinfo-shizukuHanabi-0.3
/nix/store/yhhj6c2assabvp1fl9mw99siwqmwwzjx-qdiskinfo-shizukuHaregi-0.3
/nix/store/irq6x7dzwi3cfql7zgcb3698alnnps3n-qdiskinfo-shizukuHeianKomachi-0.3
/nix/store/n1n51pahjll11d1ax1vqb8n6zha1nc47-qdiskinfo-shizukuHotaru-0.3
/nix/store/kphn1lhicv70j1w1hg8f43zk5x8vb1d8-qdiskinfo-shizukuIdol-0.3
/nix/store/p0ms5v493224a8pkvwrwpa9rbibi1c12-qdiskinfo-shizukuKotatsu-0.3
/nix/store/lsqcpj34ikmhj6191hbiffxynyxmg2ac-qdiskinfo-shizukuKotatsuNight-0.3
/nix/store/m7nhyw62bv0wyrkdbs38d9x20qdrhb5w-qdiskinfo-shizukuLiteratureGirl-0.3
/nix/store/i6xcy4f3cbcy2wy6mdl20siwfaljlwg6-qdiskinfo-shizukuLiteratureGirlWithGlasses-0.3
/nix/store/iaw9vnqzvl4gvb4wd1r076kby0982bla-qdiskinfo-shizukuMaidCool-0.3
/nix/store/5lb7bdnn2lnkrrf5a40ka6475iw7477q-qdiskinfo-shizukuMaidCute-0.3
/nix/store/818zrcqf398qsgpclvrkkgg1wrmbxr2i-qdiskinfo-shizukuMeijiMizugi-0.3
/nix/store/2120s03mcjyf3h116698cpp9ki28x8jc-qdiskinfo-shizukuMermaid-0.3
/nix/store/a2mwl33dg2qs6l8b996wyxv5ncz35jyp-qdiskinfo-shizukuMiko-0.3
/nix/store/7dypi1p6qhack3wx395vldp29xx2bppy-qdiskinfo-shizukuOffice-0.3
/nix/store/7ihv344ymdyh1jgixqz4x3dkpld8yi4j-qdiskinfo-shizukuSakura-0.3
/nix/store/y6lrmik4lywvc0hsz1p6wkhfldn3lha8-qdiskinfo-shizukuTaishoRoman-0.3
/nix/store/m2q3fkqn09vk1hlnyikzbfpjv50h45ac-qdiskinfo-shizukuTeaBreak-0.3
/nix/store/7jsx40zvak79j0n4m34lbsh8y7xj42c8-qdiskinfo-shizukuWebRadio-0.3
/nix/store/1wiw7rfxdwr36ds19ii1afp88cn613xn-qdiskinfo-shizukuWinterLamp-0.3
```

I'm leaning towards wanting to inline `sources.nix` into `themes.nix`, but i leave that decision to you.





```patch
diff --git a/pkgs/by-name/qd/qdiskinfo/package.nix b/pkgs/by-name/qd/qdiskinfo/package.nix
index 907d5c087362..343503f24082 100644
--- a/pkgs/by-name/qd/qdiskinfo/package.nix
+++ b/pkgs/by-name/qd/qdiskinfo/package.nix
@@ -6,36 +6,28 @@
   fetchzip,
   cmake,
   qt6,
-  theme ? "",
-  customBgDark ? "",
-  customBgLight ? "",
-  customStatusPath ? "",
-  customSrc ? "",
-  customRightCharacter ? false,
+  qdiskinfo,
+  themeBundle ? null,
 }:

 let
-  isTheme = theme != null && theme != "";
-
-  rightCharacter =
-    (builtins.elem theme [
-      "aoi"
-      "shizukuTeaBreak"
-    ])
-    || customRightCharacter;
-  themeSources = import ./sources.nix { inherit fetchzip; };
-  themes = import ./themes.nix {
-    inherit
-      customBgDark
-      customBgLight
-      customSrc
-      customStatusPath
-      lib
-      themeSources
-      ;
-  };
+  isThemed = themeBundle != null && themeBundle != { };
+  themeBundle' = {
+    rightCharacter = false;
+  } // themeBundle;
 in
-assert !isTheme || lib.attrsets.hasAttrByPath [ theme ] themes;
+
+# check theme bundle
+assert
+  isThemed
+  -> (
+    themeBundle' ? src
+    && themeBundle' ? paths.bgDark
+    && themeBundle' ? paths.bgLight
+    && themeBundle' ? paths.status
+    && themeBundle' ? rightCharacter
+  );
+
 stdenv.mkDerivation (finalAttrs: {
   pname = "qdiskinfo";
   version = "0.3";
@@ -64,33 +56,50 @@ stdenv.mkDerivation (finalAttrs: {
     [
       "-DQT_VERSION_MAJOR=6"
     ]
-    ++ lib.optionals isTheme [ "-DINCLUDE_OPTIONAL_RESOURCES=ON" ]
-    ++ (if rightCharacter then [ "-DCHARACTER_IS_RIGHT=ON" ] else [ "-DCHARACTER_IS_RIGHT=OFF" ]);
+    ++ lib.optionals isThemed [ "-DINCLUDE_OPTIONAL_RESOURCES=ON" ]
+    ++ (
+      if themeBundle'.rightCharacter then
+        [ "-DCHARACTER_IS_RIGHT=ON" ]
+      else
+        [ "-DCHARACTER_IS_RIGHT=OFF" ]
+    );

   postUnpack = ''
     cp -r $sourceRoot $TMPDIR/src
     sourceRoot=$TMPDIR/src
   '';
-  patchPhase = lib.optionalString isTheme ''
-    export SRCPATH=${themes."${theme}".src}/CdiResource/themes/
+  patchPhase = lib.optionalString isThemed ''
+    export SRCPATH=${themeBundle'.src}/CdiResource/themes/
     export DESTPATH=$sourceRoot/dist/theme/
     mkdir -p $DESTPATH
-    if [ -n "${themes."${theme}".paths.bgDark}" ]; then
-      cp $SRCPATH/${themes."${theme}".paths.bgDark} $DESTPATH/bg_dark.png
+    if [ -n "${themeBundle'.paths.bgDark}" ]; then
+      cp $SRCPATH/${themeBundle'.paths.bgDark} $DESTPATH/bg_dark.png
     fi
-    if  [ -n "${themes."${theme}".paths.bgLight}" ]; then
-      cp $SRCPATH/${themes."${theme}".paths.bgLight} $DESTPATH/bg_light.png
+    if  [ -n "${themeBundle'.paths.bgLight}" ]; then
+      cp $SRCPATH/${themeBundle'.paths.bgLight} $DESTPATH/bg_light.png
     fi
-    cp $SRCPATH/${themes."${theme}".paths.status}/SDdiskStatusBad-300.png $DESTPATH/bad.png
-    cp $SRCPATH/${themes."${theme}".paths.status}/SDdiskStatusCaution-300.png $DESTPATH/caution.png
-    cp $SRCPATH/${themes."${theme}".paths.status}/SDdiskStatusGood-300.png $DESTPATH/good.png
-    cp $SRCPATH/${themes."${theme}".paths.status}/SDdiskStatusUnknown-300.png $DESTPATH/unknown.png
+    cp $SRCPATH/${themeBundle'.paths.status}/SDdiskStatusBad-300.png $DESTPATH/bad.png
+    cp $SRCPATH/${themeBundle'.paths.status}/SDdiskStatusCaution-300.png $DESTPATH/caution.png
+    cp $SRCPATH/${themeBundle'.paths.status}/SDdiskStatusGood-300.png $DESTPATH/good.png
+    cp $SRCPATH/${themeBundle'.paths.status}/SDdiskStatusUnknown-300.png $DESTPATH/unknown.png
   '';
   postInstall = ''
     wrapProgram $out/bin/QDiskInfo \
       --suffix PATH : ${smartmontools}/bin
   '';

+  passthru =
+    let
+      themeSources = import ./sources.nix { inherit fetchzip; };
+    in
+    rec {
+      themeBundles = import ./themes.nix { inherit themeSources; };
+      tests = lib.flip lib.mapAttrs themeBundles (
+        themeName: themeBundle:
+        (qdiskinfo.override { inherit themeBundle; }).overrideAttrs { pname = "qdiskinfo-${themeName}"; }
+      );
+    };
+
   meta = {
     description = "CrystalDiskInfo alternative for Linux";
     homepage = "https://github.com/edisionnano/QDiskInfo";
diff --git a/pkgs/by-name/qd/qdiskinfo/themes.nix b/pkgs/by-name/qd/qdiskinfo/themes.nix
index 6cec442206d0..f02f4ce2887b 100644
--- a/pkgs/by-name/qd/qdiskinfo/themes.nix
+++ b/pkgs/by-name/qd/qdiskinfo/themes.nix
@@ -1,11 +1,4 @@
-{
-  customBgDark,
-  customBgLight,
-  customSrc,
-  customStatusPath,
-  lib,
-  themeSources,
-}:
+{ themeSources }:

 {
   aoi = {
@@ -15,14 +8,7 @@
       bgLight = "Aoi/AoiBackground-300.png";
       status = "Aoi";
     };
-  };
-  custom = {
-    src = themeSources."${customSrc}";
-    paths = {
-      bgDark = customBgDark;
-      bgLight = customBgLight;
-      status = customStatusPath;
-    };
+    rightCharacter = true;
   };
   kureikei = {
     src = themeSources.kureikei;
@@ -383,6 +369,7 @@
       bgLight = "ShizukuTeaBreak/ShizukuBackground-300.png";
       status = "Shizuku";
     };
+    rightCharacter = true;
   };
   shizukuWebRadio = {
     src = themeSources.shizuku;
```

**Comment by RoyDubnium** [comment]
Thanks for the help! However, it seems that ofborg does not like the new changes.

**Comment by RoyDubnium** [comment]
Well, the error no longer occurs. Not sure why it was happening in the first place, but it seems to be working now. Package builds with no issues I can find.

**Pull request merged**
