### PR TITLE
suitesparse: 5.3.0 -> 5.4.0

### PR DESCRIPTION
**Pull request by timokau**
###### Motivation for this change

Latest upstream release, maybe/hopefully a fix for #52709.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by timokau** [comment]
@GrahamcOfBorg build suitesparse

Looks like it doesn't do that automatically for some reason.

**Comment by timokau** [comment]
`nix-review` only shows a Julia test failure, but that was not caused by this PR (cc @7c6f434c).

**Comment by timokau** [comment]
Here's the log for julia: http://sprunge.us/5NBIoN

**Comment by timokau** [comment]
I can confirm that master builds fine. Not sure what caused the issue I saw -- either there was some issue that has since been fixed or maybe the tests just ran out of ram (which they need a ridiculous amount of). Sorry for the false alarm.

**Comment by 7c6f434c** [comment]
Ah I see. It might have been Julia 0.6 problem, which is a known and old problem with some trace of hope that someone still using abandoned 06.-only libraries will come up with a master-applicable fix.

**Comment by timokau** [comment]
Why is 0.6 default if there already is a 1.0?

**Comment by 7c6f434c** [comment]
On master, the default Julia version is 1.0.1 now.

**Pull request merged**
