### PR TITLE
zfsUnstable: 2.1.10-unstable-2023-01-24 → 2.1.10-unstable-2023-03-02

### PR DESCRIPTION
**Pull request by toastal**
###### Description of changes

Built and running on Linux 6.1.11 for me
And 6.1.12
And 6.1.13
And 6.1.14
And 6.1.15

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by toastal** [comment]
ping @jcumming @globin @jonringer @wizeman

**Comment by toastal** [comment]
reping @jcumming @globin @jonringer @wizeman

**Comment by RaitoBezarius** [comment]
https://github.com/openzfs/zfs/compare/92e0d9d183ce6752cd52f7277c8321d81df9ffee...9d2e5c14b2f94c91aa389799bd9e80e1098263e7

**Review by RaitoBezarius — APPROVED** [review]
LGTM, do you know if it works with 6.2?

**Comment by toastal** [comment]
@RaitoBezarius I have only tested on 6.1.11, 6.1.12, 6.1.13, 6.1.14, & 6.1.15. [META](https://github.com/openzfs/zfs/blob/zfs-2.1.10-staging/META) still says max is 6.2, but the precedence I have seen so far is that it's one of the last things that gets updated. New tags are usually against the next kernel version though. Seeing the timing, I wouldn't be surprised to see 2.1.10 cut very soon.

**Pull request merged**
