### PR TITLE
New package: lxqt 0.7

### PR DESCRIPTION
**Pull request by ellis**
Adds packages and a service for lxqt 0.7, a desktop manager

### CODE REVIEW

**Comment by 7c6f434c** [comment]
@ellis and is there a clean solution?

**Comment by ellis** [comment]
@7c6f434c I've put some time into fixing Qt, but a good patch will probably take me many more hours.  I'm having trouble finding such free time.  The only practical solution I see right now is sym-linking /etc/xdg to /run/current-system/sw/etc/xdg and having Qt configured for /etc/xdg (as is standard on many other linux platforms)...  Any thoughts?

**Comment by 7c6f434c** [comment]
>@7c6f434c I've put some time into fixing Qt, but a good patch will probably take me many more hours.  I'm having trouble finding such free time.  The only practical solution I see right now is sym-linking /etc/xdg to /run/current-system/sw/etc/xdg and having Qt configured for /etc/xdg (as is standard on many other linux platforms)...  Any thoughts?

Personally, I do think it would be less breaking, but would it break 
chroot builds using Qt5 (if you have any idea about that)?

It doesn't use a single macro definition for that but hardcodes that
in multiple places?

**Comment by ellis** [comment]
@7c6f434c I'm afraid I have no idea about chroot builds or why it might break them... 

> It doesn't use a single macro definition for that but hardcodes that in multiple places?

When calling ./configure on Qt (both 4 and 5), it accepts an option for where the XDG directory is (default is /etc/xdg).  This is then hard-coded into a .h header file, and QSettings uses that (indirectly).

**Comment by 7c6f434c** [comment]
Chroot will not have /etc/xdg

Maybe I will try to look at it: there could be a simple way to patch environment-override into code — or maybe not.

**Comment by domenkozar** [comment]
@ellis would love to support lxqt, do you have any plans to resolve remaining issue(s)?

**Comment by ellis** [comment]
@domenkozar I would love that too, but I'm really not sure what to do with Qt and the system symlinks.  Patching Qt to properly respect the XDG environment variables would be more work than I see myself finding time for.  Do you know anything about how to sym-link /etc/xdg to /run/current-system/sw/etc/xdg in a way that would be accepted?  If so, the patch to Qt 5's build scripts is simple.

**Comment by ellis** [comment]
@domenkozar I'm taking a second look at making a patch for Qt.  Will let you know what I find.

**Comment by domenkozar** [comment]
Cool!

**Comment by ellis** [comment]
@domenkozar I managed to patch Qt5.3 so that it uses all the directories in $XDG_CONFIG_DIRS.  Fortunately, it's a small patch -- unfortunately, it's not pretty, but the original code isn't pretty either...
Anyhow, I'll create a separate pull request for that in the next few days.  I don't have enough space in my root partition to update my system to the latest nixpkgs, so I'll try it out on a virtual machine first.

**Comment by ellis** [comment]
Patch for Qt 5.3 submitted here: https://github.com/NixOS/nixpkgs/pull/7395

**Comment by ellis** [comment]
I'm closing this pull request, because I now have packages for lxqt 0.9 ready.  Will submit a separate pull request once it has run on my system for another week or so.  LXQt will depend on https://github.com/NixOS/nixpkgs/pull/7395 going through first.

**Pull request closed without merging**
