### PR TITLE
vscode-extensions.ms-python.python: add support for darwin platforms

### PR DESCRIPTION
**Pull request by jfchevrette**
###### Motivation for this change

Add darwin platform support for VSCode extension ms-python.python

LTTng is not available on darwin and the extension does not support it on darwin

I tested that my changes did not impact the existing x86_64-linux platform support

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jfchevrette** [comment]
@jraygauthier as you're the current maintainer. Merci :)

**Comment by jfchevrette** [comment]
`nixpkgs-review pr 154793` returned no errors

**Comment by tboerger** [comment]
Getting support for macOS would be great :+1:

**Review by jraygauthier — APPROVED** [review]
Look good to me. Nice improvement. 
Would you agree to add yourself as co-maintainer? 
Since I won't be able to validate OSX supports (linux only here) it might be a good idea.

**Comment by jfchevrette** [comment]
@jraygauthier Thank you for the offer! I've been meaning to start contributing to nixpkgs and I appreciate the opportunity to help maintain this vscode extension.

I added myself to the maintainers. Please let me know if everything looks OK

**Review by jraygauthier — APPROVED** [review]
Excellent, looks even finer now ;)

**Comment by jfchevrette** [comment]
@jraygauthier is there something else to be done before this can be merged?

**Comment by jraygauthier** [comment]
@jfchevrette : Nop, everything is fine, this PR has been approved for 21 days. I do not however have write access to this repo, you will need someone with merge rights. It might possibly help to tells people via <https://discourse.nixos.org/t/prs-ready-for-review/3032> that the PR has already been reviewed and is ready to be merged.

**Comment by jonringer** [comment]
sorry, was busy with life

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 154793 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>1 package built:</summary>  <ul>    <li>vscode-extensions.ms-python.python</li>  </ul></details>

**Comment by jraygauthier** [comment]
Thanks @jonringer.

**Pull request merged**
