### PR TITLE
gildas: 20230801_a -> 20240401_a; fix build on darwin

### LINKED ISSUE #304516: Build failure: gildas
### Steps To Reproduce

1. `NIXPKGS_ALLOW_BROKEN=1 nix-build -I . -A gildas`

### Build log

```
mkdir /private/tmp/nix-build-gildas-20230801_a.drv-0/gildas-src-aug23a/integ/demo
cpp -P -traditional -C -DIEEE="ieee" -DBITS64="bits64" -DMACHINE=arm64 -DDARWIN="darwin"  -ffreestanding -DGFORTRAN="gfortran" -DGFORTRAN_VERSION="1230" -DCFITSIO="yes" -DATM2009="atm2009" -DPNG="yes" -DGAG_USE_GTK -DGAG_USE_OPENMP -DGAG_USE_POSIX -DGAG_USE_PYTHON -DGAG_USE_UNDERSCORE    hlp2tex.f90 > built/arm64-darwin-gfortran-openmp/hlp2tex.f90
gfortran -c  -fimplicit-none  -I./ -I./built/arm64-darwin-gfortran-openmp -I/private/tmp/nix-build-gildas-20230801_a.drv-0/gildas-src-aug23a/integ/arm64-darwin-gfortran-openmp/include  -J./built/arm64-darwin-gfortran-openmp -pipe -fno-backslash -fno-range-check -w   -fno-second-underscore -fPIC -fopenmp -O built/arm64-darwin-gfortran-openmp/hlp2tex.f90 -o built/arm64-darwin-gfortran-openmp/hlp2tex.o
clang-16: error: no input files
```

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.4.0, macOS 14.4.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.21.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by smaret**
## Description of changes

- Fix the build on Darwin (closes #304516 )
- Update the latest upstream
- Remove unneeded patch

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by smaret** [comment]
Result of `nixpkgs-review pr 304813` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gildas</li>
  </ul>
</details>

**Comment by smaret** [comment]
Result of `nixpkgs-review pr 304813` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gildas</li>
  </ul>
</details>

**Comment by smaret** [comment]
Result of `nixpkgs-review pr 304813` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gildas</li>
  </ul>
</details>

**Comment by bzizou** [comment]
Result of `nixpkgs-review pr 304813` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gildas</li>
  </ul>
</details>

**Review by bzizou — APPROVED** [review]
Maybe patches should be submitted upstream?

**Comment by smaret** [comment]
@bzizou I did submit the patches upstream (by email, because they have no public forge). I hope the patches will be included in the next release.

**Pull request merged**
