### PR TITLE
gnomeExtensions: Update for GNOME 44

### PR DESCRIPTION
**Pull request by LostAttractor**
###### Description of changes
Update GNOME Extensions for GNOME 44.
At the same time, the patches of the two extensions are deleted, because those two extensions support Gnome 41 at the highest, and since we only keep the support for three versions forward, so it is now deprecated.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by piegamesde** [comment]
I'm unsure about what to do with the old extensions that have custom patches. I fear that some of them will get an update again eventually, so we'll have to re-add the patches which is annoying.

One solution could be to modify the `patchExtension` function to not fail when the extension is not there anymore, but I'm usually not a fan of silently doing nothing on failure.

**Comment by rhoriguchi** [comment]
Why keep `gnome41Extensions` if it's not part of `gnomeExtensions`? Because how it is now, we still support 4 versions you just need to add them through `gnome41Extensions.*`

**Comment by LostAttractor** [comment]
I have re-run the `update-extensions.py` and force push it.
The existence of patch really makes us irritated, but here we remove the two patch of extensions that are no longer updated. The reason why they are no longer be maintained and updated here is that the functions they provide are already included in GNOME itself, and we have already retained three historical gnome versions. If an extension has not been maintained for a very long time, then it should also no longer be maintained in the future

**Comment by LostAttractor** [comment]
(Re-run the update-extensions.py and force push it again.)

**Pull request merged**
