### PR TITLE
[20.09] gitlab: 13.6.0 -> 13.6.1

### PR DESCRIPTION
**Pull request by ghost**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by drewrisinger** [comment]
Link to original PR b/c missing from above: #104689

**Review by drewrisinger — APPROVED** [review]
* [x] Diff LGTM
* [x] Commits LGTM
* [x] Builds via ``nix-review``:

```
https://github.com/NixOS/nixpkgs/pull/105697
5 packages built:
gitaly gitlab gitlab-ee gitlab-shell gitlab-workhorse
```

**Comment by bgamari** [comment]
Was this tested? Perhaps I'm doing something wrong but Gitaly fails to start complaining about an unsupported git version locally.

**Comment by bgamari** [comment]
However, cherry-picking 6f2e9937af189854b44ea5d4776a37dae4ef1902 into the branch appears to fix this.

**Comment by petabyteboy** [comment]
The issues you are seeing are not actually introduced by these commits. They were introduced with https://github.com/NixOS/nixpkgs/pull/104587, which was merged without proper testing.

https://github.com/NixOS/nixpkgs/pull/104896 is still making its way to nixos-20.09 via staging. That and this should fix it in theory, but I haven't tested it.

**Comment by srhb** [comment]
The git change is in 20.09 now, so presumably this should fix Gitlab in stable now,

**Pull request merged**
