### PR TITLE
libetebase: init at 0.5.6

### LINKED ISSUE #244286: Package request: libetebase, in order to get etesync support for libsForQt5.kdepim-runtime
**Project description**

EteSync is a "secure, end-to-end encrypted, and privacy respecting sync for your contacts, calendars, tasks and notes."

Since GSoC 2020 KDE supports it. `kdepim-runtime` automatically detects `libetebase` if it is installed and builds the appropriate modules.

**Metadata**

* homepage URL: https://www.etesync.com/user-guide/kontact/ ("build from source" link points to a site that is gone)
* build instructions: https://web.archive.org/web/20210226064244/https://thejollyblog.tech/posts/kde/etesync-v2-kontact/
* source URL: https://github.com/etesync/libetebase
* license:  BSD-3-Clause
* platforms: unix, linux, darwin, ...

### PR DESCRIPTION
**Pull request by laalsaas**
## Description of changes

add [Libetebase](https://github.com/etesync/libetebase), see [etebase.com](https://etebase.com)

Closes #244286
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Fixes: #244286

### CODE REVIEW

**Review by raphaelr — COMMENTED** [review]
Let's see if the darwin build can be fixed easily. Otherwise `broken = stdenv.isDarwin`.

**Review by raphaelr — APPROVED** [review]
LGTM now

**Review by pbsds — COMMENTED** [review]
Result of `nixpkgs-review pr 261255` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>libetebase</li>
  </ul>
</details>

Please set `meta.platforms`, and consider applying the following:


```diff
diff --git a/pkgs/by-name/li/libetebase/package.nix b/pkgs/by-name/li/libetebase/package.nix
index 3ff845fb2da2..411e2288e125 100644
--- a/pkgs/by-name/li/libetebase/package.nix
+++ b/pkgs/by-name/li/libetebase/package.nix
@@ -4,7 +4,10 @@
 , openssl
 , lib
 , stdenv
+, testers
+, libetebase
 }:
+
 rustPlatform.buildRustPackage rec {
   pname = "libetebase";
   version = "0.5.6";
@@ -30,11 +33,16 @@ rustPlatform.buildRustPackage rec {
     ln -s $out/lib/libetebase.so $out/lib/libetebase.so.0
   '';

+  passthru.tests.pkg-config = testers.testMetaPkgConfig libetebase;
+
   meta = with lib; {
     description = "A C library for Etebase";
     homepage = "https://www.etebase.com/";
     license = licenses.bsd3;
     broken = stdenv.isDarwin;
     maintainers = with maintainers; [ laalsaas ];
+    pkgConfigModules = [
+      "etebase"
+    ];
   };
 }
```

**Comment by SuperSandro2000** [comment]
@laalsaas ping

**Pull request merged**
