### PR TITLE
cpp_ethereum: mark as broken

### PR DESCRIPTION
**Pull request by Mic92**
Looks like it incompatible with current ethereum.

cc @artuuge

hydra build: https://hydra.nixos.org/build/70333858

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Is our ethereum too new? @gumb0 
https://hydra.nixos.org/build/70333858

**Comment by gumb0** [comment]
Is the question about the build failure of cpp-ethereum? If yes, where's the log or build error?

**Comment by Mic92** [comment]
@gumb0 yes that was about cpp-ethereum, here is the build log: https://hydra.nixos.org/build/70333858/nixlog/1
I personally don't use it, but I noticed it no longer builds, when I was reviewing an upgrade of https://github.com/catchorg/Catch2

**Comment by gumb0** [comment]
Thank you for the report, we should fix this.

**Comment by Mic92** [comment]
@gumb0 makes sense, we upgraded to gcc7 to because of Spectre.

**Pull request closed without merging**
