### PR TITLE
catfs: init at unstable-2020-03-21

### LINKED ISSUE #99315: catfs
**Project description**
caching file-system, written in rust. Designed to work with https://github.com/kahing/goofys

**Metadata**

* homepage URL: https://github.com/kahing/catfs
* source URL: https://github.com/kahing/catfs
* license: Apache2
* platforms: unix, linux, darwin

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
closes: #99315

some concerns about activity of upstream though: https://github.com/kahing/catfs/issues/47 https://github.com/kahing/catfs/pulls

anyway did this as mostly an exercise for packing rust. Don't feel strongly if this gets added

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I am not sure but should this be marked Unix only because fuse is not available on darwin?

**Comment by jonringer** [comment]
darwin users should get a "not supported platform" error due to the fuse dependency

**Comment by jonringer** [comment]
however, I already have it in os-specific/linux, so I may as well be coherent about it

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 99426` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>catfs</li>
  </ul>
</details>

**Review by tomberek — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 99426` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>catfs</li>
  </ul>
</details>

**Pull request merged**
