### PR TITLE
Deprecate deepspeech in favor of stt

### LINKED ISSUE #119496: Please update Mozilla TTS/STT
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: tts

current version: 0.0.9
desired version: 0.0.11

###### Notify maintainers
@Mic92 @mweinelt 

maintainers:

###### Note for maintainers

mozilla fired the team and they founded a new company to continue their work

new releases can be found here

https://github.com/coqui-ai/TTS/releases/tag/v0.0.11
https://github.com/coqui-ai/STT

### PR DESCRIPTION
**Pull request by rvolosatovs**
@davidak 

Did not adhere to https://github.com/NixOS/nixpkgs/pull/116475 entirely, since the package is not just deprecated, but essentially renamed - made only one commit for clarity.

Closes https://github.com/NixOS/nixpkgs/issues/119496

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rvolosatovs** [comment]
@GrahamcOfBorg build stt

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 121809` at 1aa16fdc run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>stt</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/tools/audio/stt/default.nix:21:3:
```
   |
21 |   installPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-uri-literals.md">no-uri-literals</a>

URI literals are deprecated.
Near pkgs/tools/audio/stt/default.nix:28:16:
```
   |
28 |     homepage = https://github.com/coqui-ai/STT;
   |                ^
```
</li>
  </ul>
</details>

**Comment by davidak** [comment]
@rvolosatovs thanks!

Can you use `git mv`, so blame and history still works?

Also follow the 2. suggestion from @r-rmcgibbo https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-uri-literals.md

**Comment by davidak** [comment]
@rvolosatovs can you have a look?

**Comment by rvolosatovs** [comment]
Sorry for taking so long.
Commited a `git mv` in https://github.com/NixOS/nixpkgs/pull/121809/commits/33b0e0d7920378f2d83dfe490eef0dabcea7b5bb - it doesn't look like this can be squashed in one commit, since then git treats this diff as a deletion and a new file addition due to amount of changes.

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 121809` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>stt</li>
  </ul>
</details>

**Comment by davidak** [comment]
```
tts --text "To help with the large amounts of pull requests, we would appreciate your reviews of other pull requests, especially simple package updates. Just leave a comment describing what you have tested in the relevant package/service. Reviewing helps to reduce the average time-to-merge for everyone. Thanks a lot if you do!"

[nix-shell:~]$ stt --model coqui-stt-0.9.3-models.pbmm --scorer coqui-stt-0.9.3-models.scorer --audio '/home/davidak/Downloads/tts-0.0.14.wav' 
TensorFlow: v2.3.0-6-g23ad988fcde
 Coqui STT: v0.10.0-alpha.4-74-g49cdf7a6
2021-05-21 23:11:10.956472: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
rate: rate clipped 1 samples; decrease volume?
to help with the large amounts of pull requests we would appreciate your reviews of other poll requests especially simple package up dates just leave a comment describing what you have tested in the relevant packages service reviewing helps to reduce the average time to merge for every one thanks a lot if you do
```

That's quiet good.

**Review by davidak — APPROVED** [review]
Looks good

Builds, works

**Pull request merged**
