### PR TITLE
python3Packages.notify-py: fix tests

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
Previously tests failed on Linux with

    Cannot spawn a message bus without a machine-id

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

ZHF: #172160

### CODE REVIEW

**Comment by dotlambda** [comment]
@ofborg build python39.pkgs.notify-py python310.pkgs.notify-py

**Comment by austinbutler** [comment]
Result of `nixpkgs-review pr 172622` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>deltachat-cursed</li>
    <li>mpdevil</li>
    <li>python310Packages.notify-py</li>
    <li>python310Packages.toggl-cli</li>
    <li>python39Packages.notify-py</li>
    <li>python39Packages.toggl-cli</li>
  </ul>
</details>

**Comment by austinbutler** [comment]
Result of `nixpkgs-review pr 172622` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>deltachat-cursed</li>
    <li>python39Packages.notify-py</li>
    <li>python39Packages.toggl-cli</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python310Packages.notify-py</li>
    <li>python310Packages.toggl-cli</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
I don't have a way to debug the Darwin failures. @austinbutler Would you mind looking into them?

**Comment by austinbutler** [comment]
Something new since I last ran the tests on my machine is it pops up a window with "run" or "quit" choices that hangs the tests until you choose one by clicking 😞 .

I'll see if I can suggest any improvements there.

```
============================= test session starts ==============================
platform darwin -- Python 3.9.12, pytest-7.1.1, pluggy-1.0.0
rootdir: /private/tmp/nix-build-python3.9-notify-py-0.3.3.drv-0/source
collecting ... ^Mcollected 20 items

tests/test_notification.py .F..................                          [100%]

=================================== FAILURES ===================================
_________________________ test_multiline_notification __________________________

    def test_multiline_notification():
        n = notifypy.Notify(enable_logging=True)
        n.message = """
    Lorem ipsum dolor sit amet, consectetur adipiscing elit,
    sed do eiusmod tempor incididunt ut labore et dolore magna
    aliqua. Ut enim ad minim veniam, quis nostrud exercitation
    ullamco laboris nisi ut aliquip ex ea commodo consequat.
    Duis aute irure dolor in reprehenderit in voluptate velit
    esse cillum dolore eu fugiat nulla pariatur.
    Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    """
>       assert n.send() == True
E       assert False == True
E        +  where False = <bound method Notify.send of <notifypy.notify.Notify object at 0x1070457f0>>()
E        +    where <bound method Notify.send of <notifypy.notify.Notify object at 0x1070457f0>> = <notifypy.notify.Notify object at 0x1070457f0>.send

tests/test_notification.py:26: AssertionError
----------------------------- Captured stderr call -----------------------------
2022-05-11 23:07:15.101 | INFO     | notifypy.notify:__init__:49 - Logging is enabled.
2022-05-11 23:07:15.106 | WARNING  | notifypy.os_notifiers.macos:send_notification:96 - Notification icon is not supported. Read the docs for more information.
/private/tmp/nix-build-python3.9-notify-py-0.3.3.drv-0/source/notifypy/os_notifiers/binaries/Notificator.app/Contents/Resources/Scripts/notificator: line 65: osascript: command not found
=========================== short test summary info ============================
FAILED tests/test_notification.py::test_multiline_notification - assert False...
======================== 1 failed, 19 passed in 38.14s =========================
```

**Comment by austinbutler** [comment]
Result of `nixpkgs-review pr 172622` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python310Packages.toggl-cli</li>
    <li>python39Packages.toggl-cli</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>deltachat-cursed</li>
    <li>python310Packages.notify-py</li>
    <li>python39Packages.notify-py</li>
  </ul>
</details>

**Comment by austinbutler** [comment]
Uh yeah so I changed nothing and now tests pass 🤷 . The toggle-cli failures are also present on master.

**Review by austinbutler — APPROVED** [review]

**Pull request merged**
