### PR TITLE
docker: 1.6.0 -> 1.6.2

### PR DESCRIPTION
**Pull request by dpausp**

### CODE REVIEW

**Comment by geerds** [comment]
@dpausp Why did you close this PR?

**Comment by dpausp** [comment]
oops, I accidentally deleted my branch. Restored and reopened now

**Comment by domenkozar** [comment]
`/nix/store/bnlcsbw7nhd21vw4xssnxwi9y7h2asjj-coreutils-8.23/bin/mkdir: cannot create directory '/nix/store/2jdv58jrmc9ggf83bh09jw848qcj672k-systemd-217/lib/systemd/system': Permission denied`

**Comment by dpausp** [comment]
The build failure is not caused by my change, it's a problem in lxc (same as in #8151). It builds fine on my NixOS machine but fails on other systems like debian in the travis build.  I'll try to provide a fix for lxc next week.

**Comment by offlinehacker** [comment]
We have docker 1.8 already, closing this.

**Pull request closed without merging**
