### PR TITLE
coolercontrol.*: 1.1.1 -> 1.2.2

### PR DESCRIPTION
**Pull request by codifryed**
## Description of changes

Update for CoolerControl 1.1.1 -> 1.2.2

https://gitlab.com/coolercontrol/coolercontrol/-/releases/1.2.0
https://gitlab.com/coolercontrol/coolercontrol/-/releases/1.2.1
https://gitlab.com/coolercontrol/coolercontrol/-/releases/1.2.2

No breaking changes.

A nice-to-have would be to include any package changes to allow the `coolercontrold` systemd daemon access to `sh` and nvidia binaries if present.  
https://gitlab.com/coolercontrol/coolercontrol/-/issues/263  
(help needed)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by OPNA2608** [comment]
Am abit strapped for time right now, but will get to this on the weekend.

**Comment by OPNA2608** [comment]
I have added 2 commits (hope pushing to your branch was okay):

1. Replace `sh` in the `coolercontrold` source with a `runtimeShell`, which saves us the `bash` wrapping in the non-nvidia case.
2. Add an option to enable Nvidia support in the module. Hoping to get it to default on/off based on nvidia driver usage - still tinkering with that.

**Comment by codifryed** [comment]
Thanks @OPNA2608 ! 

I'm build testing for a small patch, the webkit2gtk build is running so I'll wait until that's done and clean that up and push. (That build takes quite some time) And no prob commiting to the branch, appreciate the help. 👍🏼

**Comment by codifryed** [comment]
All good from my side now. No patches in the near future planned.

**Comment by OPNA2608** [comment]
@ofborg build coolercontrol.coolercontrol-ui-data coolercontrol.coolercontrold coolercontrol.coolercontrold.passthru.tests coolercontrol.coolercontrol-liqctld coolercontrol.coolercontrol-gui

**Comment by OPNA2608** [comment]
Builds on ofborg, and works locally. I don't use Nvidia hardware on Linux, so I can only test the option insofar that:

- enabling the option manually causes nvidia driver & tools to be built
- the necessary paths are now in the service's overrides:
  ```
  Environment="PATH=/nix/store/y2vzxvhy6lmzn290r4yray2rdsk76cq1-nvidia-x11-545.29.02-6.6.10-bin/bin:/nix/store/678lpd6jbbrzhqnisynjzjmxblaq8nn3-nvidia-settings-545.29.02/bin:[...]
  ```
- at runtime I get as far as in the issue - a communication error with nvidia-smi, likely because I'm not running Nvidia

LGTM.

**Review by OPNA2608 — APPROVED** [review]

**Pull request merged**
