### PR TITLE
nixos/minecraft-server: add ops (operators) option

### PR DESCRIPTION
**Pull request by plredmond**
This change extends the `minecraft-server` module with a new option `ops`. If specified, `ops` is a list of users who are "operators" of the minecraft server, and able to issue commands to it while playing.

To test, I've deployed this modified nixpkgs to my server using nixops.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] ~Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`~
- [ ] ~Tested execution of all binary files (usually in `./result/bin/`)~
- [ ] ~Determined the impact on package closure size (by running `nix path-info -S` before and after)~
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by plredmond** [comment]
Perhaps @costrouc is an appropriate reviewer, based on maintainership.

**Comment by petabyteboy** [comment]
I think you accidentally pushed a mindustryupdate to the same branch.

**Comment by plredmond** [comment]
I'm not sure how that happened. I've rebased onto `master`.

**Comment by Avaq** [comment]
There is a competing pull request to this feature over here: #92711
It contains a lot of discussion on the matter.

**Pull request closed without merging**
