### PR TITLE
Add the pythonPackages.pysftp derivation

### PR DESCRIPTION
**Pull request by lsix**

### CODE REVIEW

**Comment by garbas** [comment]
this pytftp build on pypy?

**Comment by lancelotsix** [comment]
I actually never tested that use case…

https://pypi.python.org/pypi/pysftp reports it works for python2 and 3, but with the CPython implementation (the one I use).

I’ll change the derivation ASAP to disable it on pypy.

**Comment by lancelotsix** [comment]
Up. Is just this PR too low in the PR list, or is there is an issue I should work on ?

**Comment by lethalman** [comment]
It's ok thanks.

**Pull request merged**
