### PR TITLE
vcv-rack: 1.1.5 -> 1.1.6

### PR DESCRIPTION
**Pull request by Moredread**
###### Motivation for this change

<strike>It looks like upstream is about to release version 1.1.6 soon. I have updated the derivation for the latest master branch commit, trying out if we can drop one of our patches for 1.1.6.

To avoid duplicated effort I post it here already.</strike>

1.1.6 has been released.

I added a few more explanatory comments. Please let me know if they are helpful or they can be improved.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by Moredread** [comment]
cc @nathyong

**Review by Lassulus — APPROVED** [review]
tested with nix-review, works as expected

**Comment by maxkrieger** [comment]
How do you use plugins? It seems like `Fundamental` isn't preinstalled, and this derivation doesn't have the plugin support that #33132 had i.e. https://github.com/NixOS/nixpkgs/pull/33132/files#diff-0a96701bbd982f577aab66458a659b5e

**Comment by Lassulus** [comment]
If I remember correctly, I created an account and chose the plugins interactively.

**Comment by Moredread** [comment]
The way @Lassulus described is the way to go. At the moment there is no method to install plugins via Nix.

**Pull request merged**
