### PR TITLE
home-assistant: 0.63.3 -> 0.65.5

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
https://home-assistant.io/blog/2018/02/26/release-64/
https://home-assistant.io/blog/2018/03/09/release-65/

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

/cc @peterhoeg

### CODE REVIEW

**Comment by dotlambda** [comment]
@GrahamcOfBorg test home-assistant

**Comment by dotlambda** [comment]
@grahamc I think the test should have run fine on x86_64-linux.

**Comment by peterhoeg** [comment]
Haven't tried it but looks good. Please also backport to 18.03.

**Comment by peterhoeg** [comment]
One more thing - HA needs python 3.5 so please disable it for older versions (JIC).

**Pull request merged**
