### PR TITLE
yabai: 3.0.0 -> 3.0.1

### PR DESCRIPTION
**Pull request by cmacrae**
###### Motivation for this change
New release

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by marsam** [comment]
@GrahamcOfBorg build yabai

**Comment by cmacrae** [comment]
@marsam I could be mistaken, but I think the mention needs to be lowercase `@grahamcofborg` :)

**Comment by cmacrae** [comment]
@grahamcofborg build yabai

**Comment by marsam** [comment]
I guess it's failing in ofborg because depends on darwin>=10.13.6

**Comment by cmacrae** [comment]
Thanks for the review & merge @marsam 🙏

**Pull request merged**
