### PR TITLE
[staging]mesa and x11 updates

### PR DESCRIPTION
**Pull request by ikervagyok**
###### Motivation for this change
see https://github.com/NixOS/nixpkgs/pull/56005#

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lheckemann** [comment]
I've added this to the 19.03 milestone provisionally, let's hope we can get it through by Monday! :)

**Comment by ikervagyok** [comment]
@lheckemann rebuilt the wrong commit over night, so i havent tested this on top of staging yet. still, it shouldn't be too much breakage.

**Comment by ikervagyok** [comment]
plasma5 with firefox and wine work, didn't test extensibly though

**Comment by MP2E** [comment]
LGTM! LLVM being bumped to version 7 will also be necessary when we start packaging Mesa 19.0, so ti's good to do it now.

With the AMDGPU driver, I noticed that any program that used Vulkan was crashing for mysterious reasons due to the LLVM version bump, but after looking into it, it turns out this is due to an old file in ~/.cache named radv_builtin_shaders64

If you simply delete this file, or the 32 bit equivalent on 32-bit OSes, everything goes back to working as normal.

**Review by vcunat — APPROVED** [review]
Nitpicks:
- `xf86videos3virge` doesn't build for me, but the error is the same as before update :-)
- `xcalc` seems not to work well (display + control), but it's a new package so no real harm done.

**Pull request merged**
