### PR TITLE
python3Packages.transformers: 4.1.1 -> 4.2.2

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

Changelog:
https://github.com/huggingface/transformers/releases/tag/v4.2.0
https://github.com/huggingface/transformers/releases/tag/v4.2.1

Changes to the derivation:

- Enable on Python 3.9.
- Disable checks and use pythonImportsCheck instead. The list of
  excluded tests was getting silly. The vast majority of tests
  require internet access (to download models). I guess at this
  point we just have to accept that it is not practical to run
  the tests.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109505` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>3 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.transformers: log <a href="https://termbin.com/tfq0">https://termbin.com/tfq0</a></li>
<li>python38Packages.transformers: log was empty</li>
<li>python39Packages.transformers: log was empty</li>
  </ul>
</details>

**Comment by danieldk** [comment]
@SuperSandro2000 thanks! Python 3.7 should be fixed now, 3.8 and 3.9 build fine here.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109505` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>python37Packages.transformers: log <a href="https://termbin.com/a6j4">https://termbin.com/a6j4</a></li>
  </ul>
</details>
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>python38Packages.transformers</li>
<li>python39Packages.transformers</li>
</ul>
</details>

**Comment by danieldk** [comment]
@ofborg build python37Packages.transformers  python38Packages.transformers  python39Packages.transformers

**Comment by danieldk** [comment]
@SuperSandro2000 cannot reproduce locally and ofborg is also happy.

**Pull request merged**
