### PR TITLE
csharpier: 0.27.2 -> 0.28.2

### PR DESCRIPTION
**Pull request by thomaslaich**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by zoriya — APPROVED** [review]
Thanks!

**Comment by zoriya** [comment]
@h7x4 I don't have the permissions to merge this, could you do it please

**Comment by Aleksanaa** [comment]
Please reword to `csharpier: 0.27.2 -> 0.28.2` (if the format is wrong, ofBorg won't run)

@ofborg build csharpier

**Comment by thomaslaich** [comment]
The commit, or the PR name, or both?

Can I force push a new commit?

**Comment by zoriya** [comment]
Yes you can force push

**Review by Aleksanaa — APPROVED** [review]
```
deleting unused links...
note: currently hard linking saves 0.00 MiB
copying path '/nix/store/24nw7f84q1id5nx9nvk03zicmhmqjijn-dotnet-sdk-6.0.421-deps-nuget-deps' from 'https://cache.nixos.org'...
copying path '/nix/store/cxkaif75fk27a1v3zy89km9zm9vm2qnj-lld-16.0.6' from 'https://cache.nixos.org'...
copying path '/nix/store/i3ln31ykmarv088z9wavxg9phwyfpfw2-clang-16.0.6-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/g1mc9nvkxp2gklcjaj4ihq7m7qv60xnn-llvm-16.0.6' from 'https://cache.nixos.org'...
building '/nix/store/5imkcgyj018gp7lvi3jjlkfld333bnx7-csharpier-0.28.2-dependencies-source.drv'...
copying path '/nix/store/im9bq64cbq5wij0lgyj3fx7lm5612m59-dotnet-sdk-6.0.421-source' from 'https://cache.nixos.org'...
copying path '/nix/store/f7jq0ap58w89wnj0aqqxilg11lwjcn5l-llvm-binutils-16.0.6' from 'https://cache.nixos.org'...
error: writing to file: No space left on device
error: some substitutes for the outputs of derivation '/nix/store/9zaz5hv457x7cqhv9yzmn033kwc9mxis-clang-16.0.6.drv' failed (usually happens due to networking issues); try '--fallback' to build derivation from source
error: some substitutes for the outputs of derivation '/nix/store/sbq8flppmwzxs45iqvfy6lgy1pfbg9qb-clang-wrapper-16.0.6.drv' failed (usually happens due to networking issues); try '--fallback' to build derivation from source
running auto-GC to free 53295439872 bytes
waiting for the big garbage collector lock...
building '/nix/store/gq2n19cbz0n5axk5p4rfr0k2dr0yl0s6-csharpier-0.28.2-nuget-source.drv'...
/nix/store/im9bq64cbq5wij0lgyj3fx7lm5612m59-dotnet-sdk-6.0.421-source/share:
licenses: /nix/store/pjajx1j2dwhvsvx8kj21bryv7kqrm5y8-csharpier-0.28.2-dependencies-source/share/licenses
error: 2 dependencies of derivation '/nix/store/w6cv68jc20g93nxwrhkbgrwa33kr3rcx-dotnet-configure-hook.drv' failed to build
error: 1 dependencies of derivation '/nix/store/cg5qkj8i4m9wy02jp47hlismhsnf0lav-csharpier-0.28.2.drv' failed to build
```

Seems darwin builder is too busy 😅 but since you've tested on aarch64-darwin I'll assume it works

**Comment by thomaslaich** [comment]
thanks! 🙏

**Pull request merged**
