### PR TITLE
networkmanager,modemmanager: fix service symlinks for systemd v243

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

Fixes problems such as:

systemd[1]: Failed to put bus name to hashmap: File exists
systemd[1]: dbus-org.freedesktop.nm-dispatcher.service: Two services allocated for the same bus name org.freedesktop.nm_dispatcher, refusing operation.

Problem is that systemd treats symlinks to files outside the service
path differently, causing our old workaround to look like two separate services.

These symlinks are intended to be a means for manually emulating
the behavior of the `Alias=` directive in these services.
Unfortunately even making these symlinks relative isn't enough,
since they don't make it to where it matters--
that only makes the links in /etc/static/systemd/system/*
relative, with systemd still being shown non-relative links
in /etc/systemd/system/*.

To fix this, drop all of this at the package level
and instead simply specify the aliases in the NixOS modules.

Also handle the same for modemmanager,
since the networkmanager NixOS module also handles that.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify potential reviewers

cc @worldofpeace

### CODE REVIEW

**Comment by worldofpeace** [comment]
It's strange that we weren't doing this in the first place.
Would this be an issue for 19.09 @dtzWill?

**Review by worldofpeace — APPROVED** [review]
LGTM, though how we shuffle this around with #68714 and if this change is needed for stable is yet to be decided.

**Comment by dtzWill** [comment]
FWIW, looks like the alias symlinks were added in https://github.com/NixOS/nixpkgs/pull/1734 .

**Comment by worldofpeace** [comment]
merged in 447d625edc3a488deee1c9b2e5890dd974e55ee3, didn't notice it was to master

**Comment by worldofpeace** [comment]
backported to staging-19.09 5c0ad0e3b2321fe8ecab9da8f710888b7de5df76

**Pull request merged**
