### PR TITLE
[23.05] got: 0.88 -> 0.93

### PR DESCRIPTION
**Pull request by afh**
## Description of changes

Manually backporting got 0.93 as backport via github-actions failed (see [comment](https://github.com/NixOS/nixpkgs/pull/256122#issuecomment-1726423654) on original PR #256122)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabianhjr** [comment]
thanks for manually backporting, looks good to me running nixpkgs review to check building.

**Comment by fabianhjr** [comment]
Result of `nixpkgs-review pr 256403` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>got</li>
  </ul>
</details>

**Review by fabianhjr — APPROVED** [review]

**Comment by fabianhjr** [comment]
waiting for ofborg to finish before merging

**Comment by fabianhjr** [comment]
@ofborg eval

**Comment by fabianhjr** [comment]
Seems like there is an ongoing availability issue affecting ofborg. To avoid compounding it won't merge until that is mitigated/remediated.

**Comment by afh** [comment]
Thanks for the inspiration to manually backport got and for already merging this PR, @fabianhjr, very much appreciated!

Do you have a rough idea/guesstimate as to when this change may appear on [`nixpkgs-23.05-darwin`](https://github.com/nixOS/nixpkgs/tree/nixpkgs-23.05-darwin)?

**Comment by fabianhjr** [comment]
Normally takes about a day, you can check progress at https://status.nixos.org/ ;)

**Comment by fabianhjr** [comment]
seems like there is a build issue in the 23.05 channel, might take longer unu

**Comment by afh** [comment]
Waiting on the order of days or weeks if perfectly fine for me :) Thanks!

**Pull request merged**
