### PR TITLE
nixos/systemd: use cfg.package in systemPackages to avoid confusion

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by aanderse — CHANGES_REQUESTED** [review]
A big :+1: from me. Can you please remove this line as well because it is no longer used and adds confusion:

https://github.com/NixOS/nixpkgs/blob/83f8315e0e754674225269655ea6084e8cb5032b/nixos/modules/system/boot/systemd.nix#L11

**Comment by SuperSandro2000** [comment]
Hmmm, I think that won't solve my issue I initially had but the confusion I had that it would fix it. 😂

**Review by aanderse — APPROVED** [review]
What is/was your issue?

**Comment by aanderse** [comment]
Also, sorry, I missed this line:

https://github.com/NixOS/nixpkgs/blob/ef29cdd70a71ab2fe450c2b59e0412415d156c78/nixos/modules/system/boot/systemd.nix#L440

**Comment by SuperSandro2000** [comment]
> What is/was your issue?

I need to downgrade to systemd 249 to get systemctl status to work in WSL and libfido is still compiled against systemd 250 which confused me.

**Comment by flokli** [comment]
`libfido`, while being a dependency of `sytemd`, also needs a systemd to link against to be built.

As you can see in `all-packages.nix`, we pass `systemdMinimal` into it:

```
  libfido2 = callPackage ../development/libraries/libfido2 {
    udev = systemdMinimal;
  };
```

Setting `systemd.package` will only replace the leaf systemd, it's meant to be used to quickly test another variant of systemd running, without having to recompile the world. If you want to build `libfido2` with another systemd, you need to go the override path (and do all these rebuilds).

**Comment by SuperSandro2000** [comment]
I am not using any libfido stuff and so far it just worked ™️

**Pull request merged**
