### PR TITLE
intel-graphics-compiler: 1.0.15136.4 -> 1.0.15610.11 and some of it's direct dependencies

### PR DESCRIPTION
**Pull request by SuperSandro2000**
## Description of changes

This also updates the dependencies to the ones used in the release tab of intel-graphics-compiler and spirv-llvm-translator to a newer version which fixed a compile error.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Ralith** [comment]
Weren't spirv-headers and spirv-tools already updated by https://github.com/NixOS/nixpkgs/pull/281591? We probably shouldn't be updating them separately from the rest of the Vulkan SDK.

**Comment by SuperSandro2000** [comment]
Then those commits should go away with a rebase.

Keeping them in sync wasn't a concern until now and igc is sometimes very picky about the dependencies used, so if things are older than in there release page, I always updated them in the past.

**Comment by SuperSandro2000** [comment]
Yeah, after a rebase those commits disappeared.

**Comment by SuperSandro2000** [comment]
@ofborg build intel-graphics-compiler intel-compute-runtime

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 283531` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>rocmPackages.llvm.libclc</li>
    <li>rocmPackages_5.llvm.libclc</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>intel-compute-runtime</li>
    <li>intel-compute-runtime.drivers</li>
    <li>intel-graphics-compiler</li>
    <li>opencl-clang</li>
  </ul>
</details>

**Pull request merged**
