### PR TITLE
Update systemd and unbreak staging

### PR DESCRIPTION
**Pull request by abbradar**
###### Motivation for this change

Fix current staging problems by updating systemd and fix other packages around.

Fixes https://github.com/NixOS/nixpkgs/issues/36918.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Tested by building a near-empty VM. Upstream systemd bug report related to `CGROUP_NET_PRIO` is coming.

### CODE REVIEW

**Comment by abbradar** [comment]
Changes in systemd; removed https://github.com/NixOS/systemd/commit/0a69f1d44b385c3187b9aa81d264a11a79b551d0 along with https://github.com/NixOS/systemd/commit/74e8210b48905cb1b69e4d97a1cfc530ab423fdb , added a patch on top to fix build with new `libgpg-error`.

https://github.com/abbradar/systemd/tree/nixos-v238 this should be pushed to a new branch in NixOS/systemd.

cc @fpletz

**Comment by abbradar** [comment]
@GrahamcOfBorg build systemd

**Review by fpletz — APPROVED** [review]
Code changes LGTM. I'm giving this a spin on 18.03 now.

**Comment by abbradar** [comment]
Reported upstream: https://github.com/systemd/systemd/issues/8556

**Comment by abbradar** [comment]
`aarch64-linux` issue seems to be unrelated to the update; not sure how to fix it.

**Comment by abbradar** [comment]
@matthewbauer This should unbreak x86 on staging, I'll try to help with aarch64 separately.

**Comment by fpletz** [comment]
Hrm, apparently the old predictable interface naming from pre-17.09 is back: https://hydra.nixos.org/build/71743537/log/tail

**Comment by fpletz** [comment]
Just checked: The systemd update is triggering the predictable interface names change, not the kernel config change. :confused:

**Comment by abbradar** [comment]
Ugh. I found potentially breaking commits; investigating.

**Comment by abbradar** [comment]
@fpletz https://github.com/systemd/systemd/pull/8258/commits/73fc96c8ac0aa95477e53838a22ce94918c9d06f#r176675065 found the offending change (notice that it was done in _logging improvements_ ~_~). It seems from the code the previous naming has been a bug! We can wait for upstream comments I guess.

**Comment by abbradar** [comment]
Also if we don't want to change the behavior this late in the release cycle we can revert this one line specifically in 18.03 -- I've confirmed that it reverts names to the old (post-17.09) ones.

**Pull request merged**
