### PR TITLE
OpenJDK: 13.0.2 -> 14.0.1

### PR DESCRIPTION
**Pull request by jerith666**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
- [x] build on i686
- [x] test some more

cc @edwtjo @shlevy @NeQuissimus @lopsided98 @xfix @petabyteboy

### CODE REVIEW

**Comment by lopsided98** [comment]
i686 is going to be a problem, because OpenJDK only supports bootstrapping with the previous or same major version, and our bootstrap version is 12. We will probably need to create an OpenJDK 13 bootstrap tarball for i686. There are scripts to do this, although I haven't tested them. The biggest problem I see is ensuring that the resulting tarball is trustworthy.

**Comment by jerith666** [comment]
Yeah, we had that exact same problem in the 12 -> 13 PR (#70983), and I've just extended the same approach I took there: keep the expression for 13 around and use it to bootstrap 14.  Perhaps not elegant, but since i686 isn't a primary platform targeted by nixpkgs, it doesn't bother me too much to require a bit of extra building from source in that case.

I'm going to run my eclipse on top of this build for a couple of days at work this week, and if all goes well I'll remove the 'WIP' from the title here and be ready to merge.

**Comment by jerith666** [comment]
Seems to have worked fine so far at work this week.  I'm removing the WIP and I think it's ready to merge.

**Comment by jerith666** [comment]
bumped to 14.0.1, which was released today.

**Comment by NeQuissimus** [comment]
Other than the rebase that is required, LGTM

**Comment by wamserma** [comment]
@jerith666 ping, please rebase the PR to fix the conflict

**Comment by jerith666** [comment]
weird, it rebased cleanly with no conflicts from the command line ...

**Review by NeQuissimus — APPROVED** [review]

**Comment by piegamesde** [comment]
I just successfully built this on Arch Linux.

**Pull request merged**
