### PR TITLE
Azure functions core tools

### PR DESCRIPTION
**Pull request by ilikeavocadoes**
###### Motivation for this change

Add Azure functions core tools to set up local Azure functions development environment using Nix.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Please change the branch to master.

**Comment by ilikeavocadoes** [comment]
Should I also rebase on it?

**Comment by Mic92** [comment]
Yes.

**Comment by zimbatm** [comment]
yes please!

**Comment by ilikeavocadoes** [comment]
Is there still something that needs to be done?

**Comment by zimbatm** [comment]
sorry it needs a rebase again. please ping me when it's done so I can review and merge right after

**Comment by ilikeavocadoes** [comment]
@zimbatm I rebased it on master. Hope it's all right now.

**Review by zimbatm — APPROVED** [review]

**Comment by zimbatm** [comment]
thanks!

**Pull request merged**
