### PR TITLE
build elementary-files with vala 0.48

### LINKED ISSUE #94707: elementary-files fails to build blocking nixos-20.03 (through pantheon nixos vm test)
**Describe the bug**
https://hydra.nixos.org/build/124686072

### PR DESCRIPTION
**Pull request by pstn**
###### Motivation for this change
fixes #94707 

There is probably a more elegant way to do it but this was the one with the least impact I could find.

ping @vcunat 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pstn** [comment]
I don't know why @GrahamcOfBorg fails here. It builds for me locally just fine.

**Comment by vcunat** [comment]
Most likely because of `--arg config { allowAliases = false; }`

**Comment by worldofpeace** [comment]
We actually need to update vala on stable in the 0.46 series which is completely fine for a stable release.
Once I've verified that works I'm going to revert the update on release-20.03 and merge the vala update to staging-20.03.
And then "revert the revert" on that branch as well.

**Comment by worldofpeace** [comment]
fixed in https://github.com/NixOS/nixpkgs/commit/caf8427f6ff5cf76e5a00b22dedd9a8fdd329249.

**Comment by worldofpeace** [comment]
Here's the PR that updates vala and reverts that revert https://github.com/NixOS/nixpkgs/pull/94749

**Pull request closed without merging**
