### PR TITLE
plausible: mark broken following node-16 deprecation

### PR DESCRIPTION
**Pull request by happysalada**
###### Description of changes

marking this package broken since node-16 is going away and the upgrade looks non-trivial (I personally don't use this).
@NixOS/beam just making sure you know.
following #229910 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
I'm going to merge, but happy for feedback later if there is any.

**Comment by softinio** [comment]
@happysalada @DianaOlympos I am using this version successfully before this merge and I had no issues. Was my derivation built before nodejs deprecation to not cause an issue?

I am actually working on an upgrade PR for this so will try to fix if I can so we can reinstate this package.

Can you let me know what you observed to warrant this PR? 

Thanks
 
For ref my PR Draft which was pending me fixing a test:

https://github.com/NixOS/nixpkgs/pull/229201

**Comment by DianaOlympos** [comment]
What is observed is linked. For 23.05 we are dropping node_16

**Comment by softinio** [comment]
@DianaOlympos thanks for heads up I had missed that link.

**Comment by happysalada** [comment]
@softinio it went kind of under the radar, no worries.
Feel free to ping me when you want someone to review your upgrade PR. 
The last I checked with plausible is that they were about to upgrade to 2.0.0, that's why I didn't try too hard to save the 1.x version.

**Pull request merged**
