### PR TITLE
knot-dns: 3.2.4 -> 3.2.5

### PR DESCRIPTION
**Pull request by vcunat**
https://gitlab.nic.cz/knot/knot-dns/-/tags/v3.2.5

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of _some_ binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
builds and runs fine, nixos tests passing.

Result of `nixpkgs-review pr 214167` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>knot-dns</li>
    <li>knot-resolver</li>
    <li>ngtcp2-gnutls</li>
  </ul>
</details>

**Review by NickCao — APPROVED** [review]

**Comment by NickCao** [comment]
knot-resolver is failing tests on darwin.

**Comment by vcunat** [comment]
That's not a change.  `config.ta_update` fails sometimes if the machine is loaded, but on Hydra it seems relatively rare.

**Comment by NickCao** [comment]
@ofborg build knot-resolver

**Comment by NickCao** [comment]
Unrelated to this PR, knot-resolver could use some rework, the inline patch is just unreadable.

**Comment by vcunat** [comment]
The five-line patch?

**Comment by NickCao** [comment]
Ah I thought the lines below were also part of the patch.

**Comment by vcunat** [comment]
This particular patch seems easy to indent, so I could do that:
```nix
{
  postPatch = ''
    patch meson.build <<-EOF
      @@ -50,2 +50,2 @@
      -systemd_work_dir = prefix / get_option('localstatedir') / 'lib' / 'knot-resolver'
      -systemd_cache_dir = prefix / get_option('localstatedir') / 'cache' / 'knot-resolver'
      +systemd_work_dir  = '/var/lib/knot-resolver'
      +systemd_cache_dir = '/var/cache/knot-resolver'
    EOF

    # ExecStart can't be overwritten in overrides.
    # We need that to use wrapped executable and correct config file.
    ...
  '';
```

**Pull request merged**
