### PR TITLE
pocketbase: 0.15.3 -> 0.16.3

### PR DESCRIPTION
**Pull request by thilobillerbeck**
###### Description of changes

Updated pocketbase to [v0.16.3](https://github.com/pocketbase/pocketbase/releases/tag/v0.16.3) and provided a patch to remove the newly introduced update method in [v0.16.0](https://github.com/pocketbase/pocketbase/releases/tag/v0.16.0) to avoid confusion when using pocketbase in conjunction with the nix packaging system.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thilobillerbeck** [comment]
btw. I just tested adding `passthru.updateScript = nix-update-script { };` to make minor updates more convenient. It seems to work well. Should I include it in this PR as well?

**Comment by thilobillerbeck** [comment]
Btw. I just tested adding `passthru.updateScript = nix-update-script { };` to make minor updates more convenient and it seems to work well. Should I include that change in this PR?

**Comment by dit7ya** [comment]
Result of `nixpkgs-review pr 233615` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pocketbase</li>
  </ul>
</details>

**Comment by dit7ya** [comment]
I am not sure about the patch though - maybe better to just ask upstream about it.

**Comment by thilobillerbeck** [comment]
What makes you unsure about the patch? It just removes the update plugin from the example module. To my understanding pocketbase is designed in such a way that this should not result in a problem. This is why the entry file we compile is named example anyway. And removing the update function helps reduce confusion with users thinking this will update the nix package and it will probably fail anyway.

**Comment by thilobillerbeck** [comment]
And could you please be more specific on what you mean by asking upstream about it? The docs mention this kind of usage too https://pocketbase.io/docs/use-as-framework/

**Comment by dit7ya** [comment]
Though the patch looks fine to me - I don't know much golang to be confident about it. I just meant it is easiest to post a question at https://github.com/pocketbase/pocketbase/discussions asking about if this patch is aligned with them.

**Comment by thilobillerbeck** [comment]
> Though the patch looks fine to me - I don't know much golang to be confident about it. I just meant it is easiest to post a question at https://github.com/pocketbase/pocketbase/discussions asking about if this patch is aligned with them.

I just asked them here https://github.com/pocketbase/pocketbase/discussions/2588

**Comment by thilobillerbeck** [comment]
As pointed out in the discussion forum, it seems to be safe to remove `update` for now, but we should be careful when updating in regards of upcoming changes in the patched file. A suggestion that was made and maybe will be handled by the project is a warning when trying to update through nix or docker.

I think it is safe and a good approach to remove the update function for now. We could think about patching some kind of error message function inside there, but I don't know if this is small enough of a change to be applicable to nixpkgs or if this is a bit out of scope. @dit7ya what's your opinion on that?

**Comment by thilobillerbeck** [comment]
image

would be easy to implement, here's how it's done:

```
	// GitHub selfupdate
	// ghupdate.MustRegister(app, app.RootCmd, nil)

	app.RootCmd.AddCommand(&cobra.Command{
		Use: "update",
		Run: func(command *cobra.Command, args []string) {
			fmt.Println("Due to not compiling against FHS pahts, the update command is disabled in the nixpkgs build to avoid confusion.")
		},
	})
```

since this uses mostly standard components and documented ways to implement custom CLI commands, it shouldn't be prone to break.

**Comment by thilobillerbeck** [comment]
I updated the package to v0.16.3 in the meantime, which should have not much of an effect since it's a minor release

**Pull request merged**
