### PR TITLE
Nodejs fix darwin build

### LINKED ISSUE #132533: nodejs 16.6 fails to build on darwin
trying to build nodejs 16.6 on darwin I get the following error

```
In file included from ../deps/v8/src/libplatform/tracing/trace-writer.cc:14:
../deps/v8/src/libplatform/tracing/recorder.h:17:10: fatal error: 'os/signpost.h' file not found
#include <os/signpost.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [tools/v8_gypfiles/v8_libplatform.target.mk:159: /private/tmp/nix-build-nodejs-16.6.0.drv-0/n
rm 2e0eb71b1e97d7e96d4a06b54146ae6d4d2eb9d0.intermediate
make: *** [Makefile:110: node] Error 2
```

This error seems to be fixed by adding `darwin.Libsystem` as a buildinput.

however trying to build after that I get another error

```
In file included from /nix/store/znv06z6pld0ivwddj52rishggwc2m94c-libcxx-7.1.0-dev/include/c++/v1/__hash_table:19:
/nix/store/znv06z6pld0ivwddj52rishggwc2m94c-libcxx-7.1.0-dev/include/c++/v1/cmath:321:9: error: no member named 'isless' in the global namespace
using ::isless;
      ~~^
/nix/store/znv06z6pld0ivwddj52rishggwc2m94c-libcxx-7.1.0-dev/include/c++/v1/cmath:322:9: error: no member named 'islessequal' in the global namespace
using ::islessequal;
      ~~^
/nix/store/znv06z6pld0ivwddj52rishggwc2m94c-libcxx-7.1.0-dev/include/c++/v1/cmath:323:9: error: no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/nix/store/znv06z6pld0ivwddj52rishggwc2m94c-libcxx-7.1.0-dev/include/c++/v1/cmath:324:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/nix/store/znv06z6pld0ivwddj52rishggwc2m94c-libcxx-7.1.0-dev/include/c++/v1/cmath:325:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
13 errors generated.
```

which I think is coming from the warning
`WARNING: C++ compiler (CXX=clang++, 7.1.0) too old, need g++ 8.3.0 or clang++ 8.0.0`

darwin is still on llvm 7. There is an effort at the moment to update it to llvm 11, but it might take some more time.

I don't understand how to fix the c++ compiler version. Should it not be fixed to something higher than 7 rather than relying on the default stdenv one?

@gilligan @cko @marsam 

I'm happy to test whatever ideas you have

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by happysalada**
###### Motivation for this change

coming from issue https://github.com/NixOS/nixpkgs/issues/132533

I'm trying to fix llvm version that will be used to build node, but I'm still getting this warning.
`WARNING: C++ compiler (CXX=clang++, 7.1.0) too old, need g++ 8.3.0 or clang++ 8.0.0`

@ambroisie I'm sure I'm blind, but I really can't see it.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Ok here is what I found out about this.
From this issue https://github.com/dart-lang/sdk/issues/42034
it makes me think that the original signpost problem is just an old macosx sdk.

From this issuehttps://github.com/NixOS/nixpkgs/issues/63046
it makes me think that including libsystem has come conflicting headers with the apple_sdk it seems.
If there is anybody who knows darwin a bit better I would be interested to get some feedback.
I don't know what to try next.
I will leave this open for one more week just in case someone sees is.

**Comment by veprbl** [comment]
Adding libc headers from `Libsystem` can break libc++. You could try working that around with something like https://github.com/NixOS/nixpkgs/commit/d9a35ea925b5abd35342dced845a4964a4e77241#diff-43c44407289c7e60990a9cf2a6b437abebd9b18253bf34a8bd74da250d43d729R176-R181

**Comment by happysalada** [comment]
@veprbl thanks a lot! Very helpful!

After having a look at the apple sdk, there are no files (on the 10.12 version) named signpost.h
(I did `nix build .#darwin.apple_sdk.sdk.dev -L` and then `find` on the resulting directory)

briefly looking on the internet I found this from 2018
https://opensource.apple.com/source/kext_tools/kext_tools-528.230.1/signposts.h.auto.html

Perhaps this file was added to a later version of the sdk.
I think at this point 2 more things can be tried.
- try to patch source to just remove that include (without really knowing the consequences).
- test with a newer version of the sdk (11 is out, so rather than trying to update osx, it might be worth trying to update to the new os).

**Comment by happysalada** [comment]
This has been fixed in another PR.

**Comment by keegancsmith** [comment]
> This has been fixed in another PR.

@happysalada I'm running into this issue when trying to build a custom node version (16.7.0). What is the other PR which fixes this?

**Comment by happysalada** [comment]
That was the PR that fixed it for me https://github.com/NixOS/nixpkgs/pull/133232

**Pull request closed without merging**
