### PR TITLE
qt(creator): fix documentation build

### PR DESCRIPTION
**Pull request by bjornfor**
CC @ttuegel, @akaWolf .

### CODE REVIEW

**Comment by bjornfor** [comment]
CC @bbenoist

**Comment by bjornfor** [comment]
Looks ok for staging branch? I build tested this a few days ago, now it's rebased on top of staging.

**Comment by bjornfor** [comment]
CC @ttuegel, @akaWolf .

**Comment by akaWolf** [comment]
@bjornfor looks ok for me... but I didn't test that yet.

**Comment by ttuegel** [comment]
@bjornfor Could you run this through `nox` locally, to see how many packages this would rebuild? This may not need to go into staging, especially not the Qt 5.3 changes.

**Comment by akaWolf** [comment]
@ttuegel I think, it will rebuild enough packages... but better run nox-review, ofc.

**Comment by bjornfor** [comment]
Looking at the output of nox-review, it wants to build 390 packages, most of it is kde5.

**Comment by ttuegel** [comment]
Considering that NixOS is 16,000+ packages, I don't think that's enough to bother putting this into staging. You can go ahead and rebase this onto master. I don't think GitHub will let you change target branches for pull requests, so you may need to make a new PR.

**Comment by bjornfor** [comment]
I'll just push it to master manually then.

**Comment by bjornfor** [comment]
nox-review on my machine indicated no regressions. Pushed to master (2cf8502397cc6aa0573a012c6606d24d946f166f with parents).

**Pull request closed without merging**
