### PR TITLE
Revert "nixos/systemd: Handle template overrides"

### PR DESCRIPTION
**Pull request by aforemny**
This reverts commit e3b90b6ccc4cf4147fd01df1ed8779b1c85744bd.

That commit broke `nixos-container start` and thus breaks tests which depend on that command, in particular the test containers-ip.nix which prevents channels nixos-unstable and nixos-unstable-small from advancing.

###### Motivation for this change

Unblock nixos-unstable and nixos-unstable-small.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aforemny** [comment]
CC @adrianparvino @flokli @vcunat

**Comment by adrianparvino** [comment]
Thanks for this. I'm also investigating this myself. The `container` module doesn't seem to handle having template overrides well.

**Comment by flokli** [comment]
I merged this in - we can bring it back once we figured out how we don't break the container module. Too bad actually testing channels is somewhere buried deep in hydra, and not easily exposed as an attribut.

**Comment by vcunat** [comment]
The set for `nixos-unstable` is probably too large to run in most of local configurations.

**Comment by vcunat** [comment]
For reference, individual (matching-platform) tests are fairly easy now, I believe:
```bash
nix build -f. nixosTests.containers-ip
```

**Pull request merged**
