### PR TITLE
pdfmod: init at 0.9.1

### PR DESCRIPTION
**Pull request by obadz**
Package pdfmod & depedency (hyena)

### CODE REVIEW

**Comment by vbgl** [comment]
`pdfmod` is successfully built, but I get a run-time error when opening a file. The trace is given below. It may be an upstream bug, or a packaging issue, or a defect of my local environment (x86_64 fedora linux)?

```
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
GLib.GException: Failed to contact configuration server; the most common cause is a missing or misconfigured D-Bus session bus daemon. See http://projects.gnome.org/gconf/ for information. (Details -  1: GetIOR failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "GetIOR" with signature "" on interface "org.gnome.GConf" doesn't exist
)
  at GConf.Client.SetValue (System.String key, GConf.Value val) [0x00000] in <filename unknown>:0 
  at GConf.ClientBase.Set (System.String key, System.Object val) [0x00000] in <filename unknown>:0 
  at PdfMod.Core.Configuration.Set[String] (System.String key, System.String val) [0x00000] in <filename unknown>:0 
  at PdfMod.Core.Configuration.set_LastOpenFolder (System.String value) [0x00000] in <filename unknown>:0 
  at PdfMod.Gui.Client.LoadPath (System.String path, System.String suggestedFilename, System.Action finishedCallback) [0x00000] in <filename unknown>:0 
  at PdfMod.Core.Client.LoadPath (System.String path, System.String suggestedFilename) [0x00000] in <filename unknown>:0 
  at PdfMod.Core.Client.LoadPath (System.String path) [0x00000] in <filename unknown>:0 
  at PdfMod.Gui.Actions+<OnOpen>c__AnonStorey1.<>m__0 () [0x00000] in <filename unknown>:0 
  at PdfMod.Gui.Client+<RunIdle>c__AnonStorey4.<>m__0 () [0x00000] in <filename unknown>:0 
  at GLib.Idle+IdleProxy.Handler () [0x00000] in <filename unknown>:0 
   at GLib.ExceptionManager.RaiseUnhandledException(System.Exception e, Boolean is_terminal)
   at GLib.Idle+IdleProxy.Handler()
   at Gtk.Application.gtk_main()
   at Gtk.Application.Run()
   at PdfMod.Gui.Client..ctor(Boolean loadFiles)
   at PdfMod.PdfMod.Main(System.String[] args)
```

**Comment by obadz** [comment]
@vbgl,

Do you run the `dbus` service? (on nixos would be `service.dbus.enable = true`) 

cc @lethalman

**Comment by vbgl** [comment]
Yes, I have `dbus` and `gconf` daemons running. They have been installed from the fedora repositories and not from nixpkgs, though.

**Comment by obadz** [comment]
@vbgl, I can't reproduce so not sure how to fix..

**Comment by vbgl** [comment]
I don’t know how to fix that neither. If it’s properly working on NixOS, maybe it’s good enough.

**Comment by vcunat** [comment]
It seems to run fine for me. If someone can fix it on other Linuxes, it would be nice, but for now let's take it as it is (well, I did some style changes).

**Pull request closed without merging**
