### PR TITLE
tor-browser: 13.5.7 -> 14.0

### PR DESCRIPTION
**Pull request by felschr**
https://blog.torproject.org/new-release-tor-browser-140/

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by felschr** [comment]
I currently get a segfault when trying to run the browsers.
Since I'm not really experienced in debugging segfaults, I'm sharing my findings so far and hopefully someone can help:

In `journalctl` I see:
```console
Oct 10 11:03:44 home-pc systemd-coredump[68167]: [🡕] Process 64009 (firefox) of user 1000 dumped core.
                                                 
                                                 Module libgcc_s.so.1 without build-id.
                                                 Module libstdc++.so.6 without build-id.
                                                 Stack trace of thread 64009:
                                                 #0  0x00000000001b41c0 n/a (n/a + 0x0)
                                                 ELF object binary architecture: AMD x86-64
Oct 10 11:03:44 home-pc systemd[1]: systemd-coredump@0-68166-0.service: Deactivated successfully.
```

and `coredumpctl debug` gives me the following backtrace:
```console
(gdb) bt
#0  0x00000000001b41c0 in ?? ()
#1  0x00007efd08f7726e in call_init () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/ld-linux-x86-64.so.2
#2  0x00007efd08f7736c in _dl_init () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/ld-linux-x86-64.so.2
#3  0x00007efd08f73586 in _dl_catch_exception () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/ld-linux-x86-64.so.2
#4  0x00007efd08f7dffe in dl_open_worker () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/ld-linux-x86-64.so.2
#5  0x00007efd08f734f1 in _dl_catch_exception () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/ld-linux-x86-64.so.2
#6  0x00007efd08f7e38c in _dl_open () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/ld-linux-x86-64.so.2
#7  0x00007efd08a704dc in dlopen_doit () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libc.so.6
#8  0x00007efd08f734f1 in _dl_catch_exception () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/ld-linux-x86-64.so.2
#9  0x00007efd08f73623 in _dl_catch_error () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/ld-linux-x86-64.so.2
#10 0x00007efd08a6ff57 in _dlerror_run () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libc.so.6
#11 0x00007efd08a705b1 in dlopen@GLIBC_2.2.5 () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libc.so.6
#12 0x0000559a96dca1f2 in ?? ()
#13 0x0000559a96dc90a1 in ?? ()
#14 0x0000559a96dc8c8b in ?? ()
#15 0x00007efd08a0e14e in __libc_start_call_main () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libc.so.6
#16 0x00007efd08a0e209 in __libc_start_main_impl () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libc.so.6
#17 0x0000559a96dc8a0a in _start ()
```

**Comment by felschr** [comment]
@panicgh could you give this a test and see if you also get the same segfault?

Also, the stable release is scheduled for next Tuesday:
https://gitlab.torproject.org/tpo/applications/tor-browser/-/wikis/Release-Schedule

It would be good if we can manage to fix this issue until then.

**Comment by felschr** [comment]
While looking at the `firefox-bin` package I noticed this part:
```nix
  # Firefox uses "relrhack" to manually process relocations from a fixed offset
  patchelfFlags = [ "--no-clobber-old-sections" ];
```

And it turns out that fixes the segfault for us, too! More info about the original fix for `firefox-bin`: #257980

---

There is still a segfault in Tor itself, but I'm working on a fix and will push another update soon.

**Comment by felschr** [comment]
All segfaults should be fixed now. Basic functionality seems to be all good. Also tested Tor bridges and video playback.

**Comment by felschr** [comment]
Mullvad Browser 14.0 hasn't been released yet, so I'll update that in a separate pull request to not delay this any further.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by Yarny0** [comment]
#### Review per https://github.com/NixOS/nixpkgs/tree/2768c7d042a37de65bb1b5b3268fc987e534c49d/pkgs#package-updates

##### Reviewed points

- [x] package name fits guidelines
- [x] package version fits guidelines
- [x] package builds on x86-64
- [x] executables tested on x86-64
- [x] all depending packages build
- [ ] ~~patches have a comment describing either the upstream URL or a reason why the patch wasn't upstreamed~~
- [ ] ~~patches that are remotely available are fetched rather than vendored~~

##### Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

<details>
  <summary>1 package built:</summary>
  <ul>
    <li>tor-browser</li>
  </ul>
</details>

##### Comments

Tested (on a NixOS 24.05 plasma5 desktop with fresh HOME directory) after cherry-picking onto [recent nixos-unstable](https://github.com/NixOS/nixpkgs/tree/2768c7d042a37de65bb1b5b3268fc987e534c49d): Program starts and looks familiar, connects successfully, and https://check.torproject.org claims we are connected to the tor network.

**Pull request merged**
