### PR TITLE
clang: add lib output

### PR DESCRIPTION
**Pull request by LnL7**
###### Motivation for this change

This should make it easier to depend on libclang without shadowing clang/clang++ on darwin.

/cc @copumpkin @Ericson2314 

Still needs testing.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by copumpkin — COMMENTED** [review]
Looks nice in principle! Is make-bootstrap-tools.nix affected?

**Comment by LnL7** [comment]
Probably, but that should be included in my build.

**Comment by Ericson2314** [comment]
@LnL7 err, it would only copy over the outputs manually specified, so I don't think so?

**Comment by LnL7** [comment]
You're right, I though maybe all of the libs where copied https://github.com/NixOS/nixpkgs/blob/79835e8086a49c20854cd78f554d4ecbafbb2815/pkgs/stdenv/darwin/make-bootstrap-tools.nix#L82

**Comment by vcunat** [comment]
I suspect this broke some reverse dependencies, e.g. [lldb](https://hydra.nixos.org/build/67577542) (multiple versions) or [firefox](https://hydra.nixos.org/build/67559493).

**Comment by LnL7** [comment]
Hmm, think I got this mixed up with some other changes and forgot to test properly.

**Comment by vcunat** [comment]
BTW, staging should be merged soon, due to a security update of glibc.

**Comment by LnL7** [comment]
I just made a partial fix for cmake projects, anything else important I should look at except for firefox?

**Comment by vcunat** [comment]
This is some list of packages, most of them newly failed by clang: https://hydra.nixos.org/eval/1426338?filter=aarch64&compare=1426591&full=#tabs-now-fail

**Comment by LnL7** [comment]
Most of the issues should be fixed now, let me know if you find anything else.

**Comment by vcunat** [comment]
- [ ] `ycmd` https://hydra.nixos.org/build/67630571

**Comment by vcunat** [comment]
^^ I'm sorry; I didn't realize that Hydra hasn't evaluated all of your fixes yet.

**Pull request merged**
