### PR TITLE
surge-XT: unstable-2021-12-11 -> 1.0.1

### PR DESCRIPTION
**Pull request by magnetophon**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by magnetophon** [comment]
First stable release is out!
Pinging some random nix audio/synth maintainers:
@OPNA2608 @nico202 @mitchmindtree @michalrus @astro @minijackson

**Comment by equill** [comment]
Verified per [guidelines](https://nixos.org/manual/nixpkgs/stable/#chap-reviewing-contributions):

- [x] package name fits guidelines
- [x] package version fits guidelines
- [x] package build on x86_64-linux
- [x] executables tested on x86_64-linux
- [x] all depending packages build

**Comment by OPNA2608** [comment]
Should prolly bump `juce-lv2` to the latest commit on lv2 branch (https://github.com/lv2-porting-project/JUCE/commit/000e15a1e108101a68aa068b5c621a0d5b58f4d6) as well.

**Comment by magnetophon** [comment]
> Should prolly bump `juce-lv2` to the latest commit on lv2 branch ([lv2-porting-project/JUCE@000e15a](https://github.com/lv2-porting-project/JUCE/commit/000e15a1e108101a68aa068b5c621a0d5b58f4d6)) as well.

Building with that commit gives me the following error when I try to run the LV2:
```
The program 'jalv.gtk' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 54 error_code 3 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

Both Ardour and jalv.gtk do this.

**Comment by magnetophon** [comment]
Updated the PR from 1.0.0 to 1.0.1

**Comment by Artturin** [comment]
these binary names contain spaces, could they be changed?
```
[nix-shell:~/.cache/nixpkgs-review/pr-154044]$ ls ./results/surge-XT/bin/
'Surge XT'  'Surge XT Effects'
```

**Comment by magnetophon** [comment]
@Artturin I asked upstream, and they say they consciously chose this name and that spaces are valid characters in binary names. 
They also said it would probably work if we change the name.
May I ask why you requested this change?

**Review by mitchmindtree — APPROVED** [review]
utACK

**Comment by Artturin** [comment]
> @Artturin I asked upstream, and they say they consciously chose this name and that spaces are valid characters in binary names. They also said it would probably work if we change the name. May I ask why you requested this change?

because its weird
what a weird choice by upstream

**Pull request merged**
