### PR TITLE
github-runner: 2.319.1 -> 2.320.0

### PR DESCRIPTION
**Pull request by kirillrdy**
https://github.com/actions/runner/releases/tag/v2.320.0

one patch failed to apply, replaced with substituteInPlace

happy to drop formatting changes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by veehaitch — APPROVED** [review]

**Comment by kirillrdy** [comment]
> The release notes contain:
> 
> > Add jq, git, unzip and curl to default packages installed [actions/runner#3056](https://github.com/actions/runner/pull/3056)
> 
> Upstream added those packages to their Dockerfile. Shouldn't we also pass in those packages?

after reading comments in https://github.com/actions/runner/pull/3056, I am leaning towards no, but I will let maintainers decide

**Comment by veehaitch** [comment]
I am not strictly against it, but as far as I understand the Dockerfile has nothing to do with the [VM images of the GitHub-hosted runners](https://github.com/actions/runner-images). They include tons of preinstalled software and we obviously don't want to include all that software for the NixOS module. If we add the tools mentioned, the question immediately arises as to why other programs are not important as well. Therefore, I'd rather refer people to [`services.github-runners.<name>.extraPackages`](https://search.nixos.org/options?channel=unstable&show=services.github-runners.%3Cname%3E.extraPackages&from=0&size=100&sort=relevance&type=packages&query=services.github-runners.%3Cname%3E.extraPackages).

**Review by patka-123 — APPROVED** [review]

**Comment by arianvp** [comment]
This needs backporting  as Github Actions will block runners that are out of date

**Comment by arianvp** [comment]
Unfortunately the formatting patches makes the backport not apply cleanly

**Pull request merged**
