### PR TITLE
[staging] Revert "python39: 3.9.6 -> 3.9.7"

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

This reverts commit d003f75d7888cd92993107b5a1d6e3a8d340bf68.

Causes an unnecessary amount of breakages due to a DeprecationWarning
regarding the loop argument in asyncio, that is going to be deprecrated
in Python 3.10.

> 'The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.'

The ecosystem needs more time to catch up here. Broken packages are for
example aiohttp, argh and by extension alot of other packages.

https://github.com/aio-libs/aiohttp/issues/6066
https://github.com/neithere/argh/issues/148

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
We might be able to apply https://github.com/python/cpython/commit/c967bd523caabb05bf5988449487d7c1717f3ac6 instead of reverting.

**Comment by mweinelt** [comment]
Applied the patch. Results are as follows:

- aiohttp down from 610 test failures

```
= 47 failed, 2464 passed, 29 skipped, 1 deselected, 3 xfailed in 240.14s (0:04:00) =
```

**Comment by mweinelt** [comment]
Merging so I can continue with #141037.

**Comment by bergkvist** [comment]
A downside of this revert is that [this patch](https://github.com/python/cpython/pull/28053) is not included (the first release containing it is Python 3.9.7). Which means `pkgs.python39` can't really be used reliably on macOS Big Sur right now.

**Comment by mweinelt** [comment]
@bergkvist PTAL https://github.com/NixOS/nixpkgs/pull/146477

**Pull request merged**
