### PR TITLE
libqmi: 1.28.6 -> 1.28.8

### PR DESCRIPTION
**Pull request by amaxine**
###### Motivation for this change
https://gitlab.freedesktop.org/mobile-broadband/libqmi/-/blob/1.28.8/NEWS
```
Overview of changes in libqmi 1.28.8
----------------------------------------

 * libqmi-glib:
   ** Fix CTL "Set Data Format" output TLV prerequisites.
   ** Fix double free in the qmiwwan based net port manager.
```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
@GrahamcOfBorg build libqmi

**Comment by jtojnar** [comment]
Changes look okay but the build fails on ofborg for some reason.

**Comment by maxeaubrey** [comment]
Looks like it succeeded [here](https://github.com/NixOS/nixpkgs/pull/132805/checks?check_run_id=3260620994) and failed [here](https://github.com/NixOS/nixpkgs/pull/132805/checks?check_run_id=3255703681)? I'm not sure I understand why there is a difference between the two.

**Comment by maxeaubrey** [comment]
The backport failure is good, I forgot we only updated to modemmanager 1.16 after 21.05, no need to do it manually.

**Pull request merged**
