### PR TITLE
vimPlugins.yanky-nvim: init at 2023-11-27, vimPlugins.startup-nvim: init at 2023-11-02

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Add plugins [yanky.nvim](https://github.com/gbprod/yanky.nvim) and [startup.vim](https://github.com/startup-nvim/startup.nvim).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 273636` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>25 packages built:</summary>
  <ul>
    <li>vimPlugins.asynctasks-vim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.conform-nvim</li>
    <li>vimPlugins.flit-nvim</li>
    <li>vimPlugins.image-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.leap-nvim</li>
    <li>vimPlugins.multicursors-nvim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.nvim-code-action-menu</li>
    <li>vimPlugins.nvim-spider</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-parsers.nim</li>
    <li>vimPlugins.nvim-treesitter-parsers.v</li>
    <li>vimPlugins.nvim-treesitter-parsers.wing</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.playground</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.smart-splits-nvim</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.telekasten-nvim</li>
    <li>vimPlugins.vim-graphql</li>
    <li>vimPlugins.vim-snippets</li>
    <li>vimPlugins.yanky-nvim</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 273636` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>70 packages built:</summary>
  <ul>
    <li>vimPlugins.ChatGPT-nvim</li>
    <li>vimPlugins.asynctasks-vim</li>
    <li>vimPlugins.barbecue-nvim</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.conform-nvim</li>
    <li>vimPlugins.copilot-vim</li>
    <li>vimPlugins.debugprint-nvim</li>
    <li>vimPlugins.dracula-nvim</li>
    <li>vimPlugins.fidget-nvim</li>
    <li>vimPlugins.flit-nvim</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.hardtime-nvim</li>
    <li>vimPlugins.harpoon2</li>
    <li>vimPlugins.haskell-tools-nvim</li>
    <li>vimPlugins.image-nvim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.leap-nvim</li>
    <li>vimPlugins.mason-lspconfig-nvim</li>
    <li>vimPlugins.material-nvim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.mkdnflow-nvim</li>
    <li>vimPlugins.multicursors-nvim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neotest-haskell</li>
    <li>vimPlugins.no-neck-pain-nvim</li>
    <li>vimPlugins.nvim-code-action-menu</li>
    <li>vimPlugins.nvim-lilypond-suite</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-navbuddy</li>
    <li>vimPlugins.nvim-navic</li>
    <li>vimPlugins.nvim-spider</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-parsers.gomod</li>
    <li>vimPlugins.nvim-treesitter-parsers.haskell</li>
    <li>vimPlugins.nvim-treesitter-parsers.hoon</li>
    <li>vimPlugins.nvim-treesitter-parsers.nim</li>
    <li>vimPlugins.nvim-treesitter-parsers.slang</li>
    <li>vimPlugins.nvim-treesitter-parsers.sql</li>
    <li>vimPlugins.nvim-treesitter-parsers.v</li>
    <li>vimPlugins.nvim-treesitter-parsers.wing</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.playground</li>
    <li>vimPlugins.rainbow-delimiters-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.rustaceanvim</li>
    <li>vimPlugins.smart-splits-nvim</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.stan-vim</li>
    <li>vimPlugins.startup-nvim</li>
    <li>vimPlugins.tabby-nvim</li>
    <li>vimPlugins.telekasten-nvim</li>
    <li>vimPlugins.toggleterm-nvim</li>
    <li>vimPlugins.typescript-tools-nvim</li>
    <li>vimPlugins.typst-vim</li>
    <li>vimPlugins.unison</li>
    <li>vimPlugins.vim-graphql</li>
    <li>vimPlugins.vim-just</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-markdown-toc</li>
    <li>vimPlugins.vim-snippets</li>
    <li>vimPlugins.vimade</li>
    <li>vimPlugins.yanky-nvim</li>
  </ul>
</details>

**Comment by teto** [comment]
it's not clear to me how startup.nvim differs from dashboard-nvim. The author insists it depends on plenary though, can you add the dependency in overrides.nix please ? 
Since you are this involved in the neovim ecosystem, you must have noticed some neovim plugins are packaged from their rockspecs to handle their dependencies. 
If you like the approach, you might want to contribute rockspecs to the plugins. 
Note: There is a package manager still WIP that handles neovim plugin dependencies https://github.com/nvim-neorocks/rocks.nvim/

**Comment by GaetanLepage** [comment]
> it's not clear to me how startup.nvim differs from dashboard-nvim.

I haven't look in details for the differences. They look very similar indeed.

> The author insists it depends on plenary though, can you add the dependency in overrides.nix please ?

done !

> Since you are this involved in the neovim ecosystem, you must have noticed some neovim plugins are packaged from their rockspecs to handle their dependencies.
If you like the approach, you might want to contribute rockspecs to the plugins.

I didn't know about this ! I will have a look !

**Comment by teto** [comment]
this is an example https://github.com/L3MON4D3/LuaSnip/pull/1050 on how to do. Our lord @mrcjkb is also a nixer.

**Comment by GaetanLepage** [comment]
Thanks for those pointers !
Regarding this PR, do you want me to add anything else ?

**Comment by teto** [comment]
Result of `nixpkgs-review pr 273636` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>70 packages built:</summary>
  <ul>
    <li>vimPlugins.ChatGPT-nvim</li>
    <li>vimPlugins.asynctasks-vim</li>
    <li>vimPlugins.barbecue-nvim</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.conform-nvim</li>
    <li>vimPlugins.copilot-vim</li>
    <li>vimPlugins.debugprint-nvim</li>
    <li>vimPlugins.dracula-nvim</li>
    <li>vimPlugins.fidget-nvim</li>
    <li>vimPlugins.flit-nvim</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.hardtime-nvim</li>
    <li>vimPlugins.harpoon2</li>
    <li>vimPlugins.haskell-tools-nvim</li>
    <li>vimPlugins.image-nvim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.leap-nvim</li>
    <li>vimPlugins.mason-lspconfig-nvim</li>
    <li>vimPlugins.material-nvim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.mkdnflow-nvim</li>
    <li>vimPlugins.multicursors-nvim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neotest-haskell</li>
    <li>vimPlugins.no-neck-pain-nvim</li>
    <li>vimPlugins.nvim-code-action-menu</li>
    <li>vimPlugins.nvim-lilypond-suite</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-navbuddy</li>
    <li>vimPlugins.nvim-navic</li>
    <li>vimPlugins.nvim-spider</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-parsers.gomod</li>
    <li>vimPlugins.nvim-treesitter-parsers.haskell</li>
    <li>vimPlugins.nvim-treesitter-parsers.hoon</li>
    <li>vimPlugins.nvim-treesitter-parsers.nim</li>
    <li>vimPlugins.nvim-treesitter-parsers.slang</li>
    <li>vimPlugins.nvim-treesitter-parsers.sql</li>
    <li>vimPlugins.nvim-treesitter-parsers.v</li>
    <li>vimPlugins.nvim-treesitter-parsers.wing</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.playground</li>
    <li>vimPlugins.rainbow-delimiters-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.rustaceanvim</li>
    <li>vimPlugins.smart-splits-nvim</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.stan-vim</li>
    <li>vimPlugins.startup-nvim</li>
    <li>vimPlugins.tabby-nvim</li>
    <li>vimPlugins.telekasten-nvim</li>
    <li>vimPlugins.toggleterm-nvim</li>
    <li>vimPlugins.typescript-tools-nvim</li>
    <li>vimPlugins.typst-vim</li>
    <li>vimPlugins.unison</li>
    <li>vimPlugins.vim-graphql</li>
    <li>vimPlugins.vim-just</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-markdown-toc</li>
    <li>vimPlugins.vim-snippets</li>
    <li>vimPlugins.vimade</li>
    <li>vimPlugins.yanky-nvim</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Thanks !!!

**Pull request merged**
