### PR TITLE
fetchurl: support sha512

### PR DESCRIPTION
**Pull request by taku0**
Nix 1.11 supports SHA512 hash algorithm.

### CODE REVIEW

**Comment by vcunat** [comment]
Maybe add an assertion into `fetchurl` to check that nix version is high enough? I know the version of the *evaluating* nix doesn't need to be the version of the *drv-realizing* nix (which is the interesting version here IMO), but I'd still show a warning at least.

**Comment by taku0** [comment]
BTW, I got a `unknown hash algorithm ‘sha512’` error when I try SHA512 version of firefox-bin package (https://github.com/taku0/nixpkgs/tree/firefox-bin-44.0-sha512) despite of I have installed Nix 1.11.1.

```
$ nixos-version
15.09.897.aa2d714 (Dingo)

$ nix-env -i -f ~/src/nixpkgs/ nix
(snip)

$ nix-env --version
nix-env (Nix) 1.11.1

$ nix-env --dry-run -j 4 --show-trace -i --keep-going --keep-failed -f ~/src/nixpkgs/ -A pkgs.firefox-bin 2>&1 
(dry run; not doing anything)
replacing old ‘firefox-bin-44.0’
installing ‘firefox-bin-44.0’
error: while evaluating the attribute ‘buildCommand’ of the derivation ‘firefox-bin-44.0’ at ~/src/nixpkgs/pkgs/applications/networking/browsers/firefox/wrapper.nix:55:10:
while evaluating the attribute ‘src’ of the derivation ‘firefox-bin-unwrapped-44.0’ at ~/src/nixpkgs/pkgs/applications/networking/browsers/firefox-bin/default.nix:63:3:
unknown hash algorithm ‘sha512’
```

Old Nix 1.10 is called from somewhere?

**Comment by taku0** [comment]
Added the assertion.

**Comment by dezgeg** [comment]
Probably you need to update the system Nix as well since that's whose `nix-daemon` binary is being used.

**Comment by vcunat** [comment]
I thought so originally, but it confuses me that the error is during *evaluation* and I thought that isn't done by the daemon.

**Comment by dezgeg** [comment]
AFAIK evaluation does require some sort of connection to the daemon so that the .drv files can get written and for copying local paths (like `./foo.patch`) to the store.

**Comment by domenkozar** [comment]
ready?

**Comment by taku0** [comment]
Rebased.

**Comment by grahamc** [comment]
Looks like this was done in https://github.com/NixOS/nixpkgs/commit/3ecbe604ef751f475a247275ccff8c95f835aa3b

**Comment by joachifm** [comment]
@grahamc looks that way

**Comment by domenkozar** [comment]
We should also do an assert for version.

**Comment by domenkozar** [comment]
fixed in 0f9268e52c03383ade24642836be1a4e74070df3

**Pull request closed without merging**
