### PR TITLE
rubyPackages: update

### PR DESCRIPTION
**Pull request by Mic92**
Those packages block regenerating the lock file.
Bundler loops forever

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
Opened https://github.com/nix-community/bundix/issues/77 regarding the editor-config check.

**Comment by SuperSandro2000** [comment]
Can you please fix the line endings for this PR by hand?

**Comment by Mic92** [comment]
I am not in favor of that because the next person to regenerate this file will run into the same error.

**Comment by SuperSandro2000** [comment]
True but if I merge something with broken editor check I get into problems.

**Comment by Mic92** [comment]
editor config checks are harmless and here is the PR to fix this properly: https://github.com/nix-community/bundix/pull/78

**Pull request merged**
