### PR TITLE
rio: 0.1.15 -> 0.1.16

### PR DESCRIPTION
**Pull request by nartsisss**
## Description of changes

- Upgrade package to [0.1.16](https://github.com/raphamorim/rio/releases/tag/v0.1.16) ([changes](https://github.com/raphamorim/rio/compare/v0.1.15...v0.1.16))
- Remove redundant test skip
- Skip doctest for `sys::unix::eventedfd::EventedFd`, which breaks sandboxed build

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mattpolzin** [comment]
Result of `nixpkgs-review pr 344751` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>rio</li>
    <li>rio.terminfo</li>
  </ul>
</details>

**Comment by mattpolzin** [comment]
Result of `nixpkgs-review pr 344751` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>rio</li>
    <li>rio.terminfo</li>
  </ul>
</details>

**Review by mattpolzin — APPROVED** [review]

**Review by oluceps — APPROVED** [review]

**Comment by mattpolzin** [comment]
It does look like the passthru tests could be made to be a bit more robust by making the nixos test only apply when the host platform is Linux so it doesn’t fail in ofborg for Darwin platforms (the Kitty derivation does this, for example), but I’m not sure that should be required in this PR since I was able to verify that the terminal is functional on Darwin and there’s no regression in the passthru behavior from before this PR.

**Review by TornaxO7 — APPROVED** [review]

**Comment by otavio** [comment]
@mattpolzin see https://github.com/NixOS/nixpkgs/pull/345722

**Pull request merged**
