### PR TITLE
xkeyboard-config: 2.27 -> 2.31

### PR DESCRIPTION
**Pull request by bbjubjub2494**
###### Motivation for this change
upstream minor version. New layouts, e. g. French AFNOR Azerty

###### Things done

Functionally tested on one of my workstations w/ gnome3 and x11.extra-layouts.

Targeted staging because there are a lot of transitive referers

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lourkeur** [comment]
nixos/test/keymap.nix passes

**Review by teto — APPROVED** [review]

**Comment by teto** [comment]
would you be interested in adding the manpage while you are at it ? it s a longstanding isusue https://github.com/freedesktop/xkeyboard-config/tree/master/man

**Review by jtojnar — COMMENTED** [review]
Changelog looks innocuous:

https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/xkeyboard-config-2.31/NEWS#L1-8

**Comment by lourkeur** [comment]
> would you be interested in adding the manpage while you are at it ? it s a longstanding isusue https://github.com/freedesktop/xkeyboard-config/tree/master/man

I looked into that and I found that there's nothing wrong with this derivation in itself. there's a share/man in the output and if you have it directly into your environment, it shows in man. The reason it doesn't show it when used normally is that it isn't spliced in system-path, rather setxkbmap contains a [manual symlink to the xkb data](https://github.com/NixOS/nixpkgs/blob/c778945806b44d46ec16bc4302e7e7163e6bab97/pkgs/servers/x11/xorg/overrides.nix#L325). I'll look into it further though.

**Comment by teto** [comment]
fantastic, that fixed it for me.

**Pull request merged**
