### PR TITLE
wkhtmltopdf: fix ssl bug

### PR DESCRIPTION
**Pull request by jb55**
Fixes bug when trying to convert directly from url

### CODE REVIEW

**Comment by jb55** [comment]
Build error is timeout, I've tested it locally and it works.

**Comment by fpletz** [comment]
Is this PR actually disabling openssl support? Is the bug triggered when using HTTPS URLs and how does disabling SSL support fix this?

**Comment by jb55** [comment]
@fpletz it's overriding the `-openssl-linked` argument at the top, so removing it seems to fix things.

**Comment by fpletz** [comment]
Ah, I see. Thanks for the explanation!

**Pull request merged**
