### PR TITLE
libvirt: 7.10.0 -> 8.1.0

### PR DESCRIPTION
**Pull request by lovesegfault**
- libvirt: 7.10.0 -> 8.1.0
- python3Packages.libvirt: 7.10.0 -> 8.1.0
- perlPackages.SysVirt: 7.10.0 -> 8.1.0

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 164140` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>nixops_unstable</li>
    <li>rubyPackages.ruby-libvirt</li>
    <li>rubyPackages_3_0.ruby-libvirt</li>
    <li>rubyPackages_3_1.ruby-libvirt</li>
    <li>virt-manager</li>
  </ul>
</details>
<details>
  <summary>23 packages built:</summary>
  <ul>
    <li>collectd</li>
    <li>diffoscope</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>gnome.gnome-boxes</li>
    <li>libguestfs</li>
    <li>libguestfs-with-appliance</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>minikube</li>
    <li>minishift</li>
    <li>ocamlPackages.ocaml_libvirt</li>
    <li>perl532Packages.SysVirt</li>
    <li>perl534Packages.SysVirt</li>
    <li>python310Packages.guestfs</li>
    <li>python310Packages.libvirt</li>
    <li>python39Packages.guestfs</li>
    <li>python39Packages.libvirt</li>
    <li>vagrant</li>
    <li>virt-manager-qt</li>
    <li>virt-top</li>
    <li>virt-viewer</li>
    <li>virtlyst</li>
  </ul>
</details>

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 164140` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>nixops_unstable</li>
    <li>rubyPackages.ruby-libvirt</li>
    <li>rubyPackages_3_0.ruby-libvirt</li>
    <li>rubyPackages_3_1.ruby-libvirt</li>
  </ul>
</details>
<details>
  <summary>24 packages built:</summary>
  <ul>
    <li>collectd</li>
    <li>diffoscope</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>gnome.gnome-boxes</li>
    <li>libguestfs</li>
    <li>libguestfs-with-appliance</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>minikube</li>
    <li>minishift</li>
    <li>ocamlPackages.ocaml_libvirt</li>
    <li>perl532Packages.SysVirt</li>
    <li>perl534Packages.SysVirt</li>
    <li>python310Packages.guestfs</li>
    <li>python310Packages.libvirt</li>
    <li>python39Packages.guestfs</li>
    <li>python39Packages.libvirt</li>
    <li>vagrant</li>
    <li>virt-manager</li>
    <li>virt-manager-qt</li>
    <li>virt-top</li>
    <li>virt-viewer</li>
    <li>virtlyst</li>
  </ul>
</details>

**Comment by Kranzes** [comment]
Look at my previous updates of libvirt to see how I dealt with nixops.

**Comment by lovesegfault** [comment]
> Look at my previous updates of libvirt to see how I dealt with nixops.

The issue is different here. I have a PR upstream that should solve the problem: https://github.com/nix-community/nixops-libvirtd/pull/30

For now perhaps I can patch the package.

**Comment by Kranzes** [comment]
I've created a PR similar to this on upstream when I updated from 6.X.X to 7.X.X.

**Comment by lovesegfault** [comment]
Pointing the plugin to my patched branch for now

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 164140` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>libvmi</li>
  </ul>
</details>
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>rubyPackages.ruby-libvirt (rubyPackages_2_7.ruby-libvirt)</li>
    <li>rubyPackages_3_0.ruby-libvirt</li>
    <li>rubyPackages_3_1.ruby-libvirt</li>
  </ul>
</details>
<details>
  <summary>24 packages built:</summary>
  <ul>
    <li>collectd</li>
    <li>diffoscope</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>gnome.gnome-boxes</li>
    <li>haskellPackages.libvirt-hs</li>
    <li>libguestfs</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>minikube</li>
    <li>minishift</li>
    <li>nixops_unstable</li>
    <li>perl532Packages.SysVirt</li>
    <li>perl534Packages.SysVirt</li>
    <li>python310Packages.guestfs</li>
    <li>python310Packages.libvirt</li>
    <li>python39Packages.guestfs</li>
    <li>python39Packages.libvirt</li>
    <li>vagrant</li>
    <li>virt-manager</li>
    <li>virt-manager-qt</li>
    <li>virt-top</li>
    <li>virt-viewer</li>
    <li>virtlyst</li>
  </ul>
</details>

**Comment by Kranzes** [comment]
What's the case with `ruby-libvirt` ?

**Comment by Izorkin** [comment]
Error start default network with use hardening mode:
```
virsh net-list --all
 Name      State      Autostart   Persistent
----------------------------------------------
 default   inactive   yes         yes

```
The error occurs because service `disable-kernel-module-loading` service starts before service `libvirtd` service.
Fix variant:
```
diff --git a/nixos/modules/virtualisation/libvirtd.nix b/nixos/modules/virtualisation/libvirtd.nix
index ab87394a30e..97b85751a99 100644
--- a/nixos/modules/virtualisation/libvirtd.nix
+++ b/nixos/modules/virtualisation/libvirtd.nix
@@ -322,6 +322,7 @@ in
       requires = [ "libvirtd-config.service" ];
       after = [ "libvirtd-config.service" ]
         ++ optional vswitch.enable "ovs-vswitchd.service";
+      wantedBy = [ "multi-user.target" ];

       environment.LIBVIRTD_ARGS = escapeShellArgs (
         [
```

Or is there another variant?
cc @lovesegfault @rnhmjoj

**Comment by MartinPotier** [comment]
I'm suspecting the bump to libvirtd 8.1 to have broken vagrant-libvirt (because it might not be targeting this new version yet), I opened https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1471 against the upstream project to gather more information.

Meanwhile, I have to downgrade to be able to continue using `vagrant` against libvirt:

```
  virtualisation = {
    libvirtd = let
      patchedPkgs = import (builtins.fetchTarball {
        url = "https://github.com/NixOS/nixpkgs/archive/02a5f5cf89b0962173e16a4c9d361b84351ac4c4.tar.gz";
        sha256 = "1z8randgl3dby6zdcaiwhpsl89nccj2zhql3gijafx4gvjhv1yim";
      }) {};
    in {
      enable = true;
      package = patchedPkgs.libvirt;
    };
  };
```

**Pull request merged**
