### PR TITLE
gcc12: 12.2.0 -> 12.3.0

### PR DESCRIPTION
**Pull request by trofi**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by trofi** [comment]
Causes at least `ccache` ICE:
```
ccache> /build/source/src/Logging.hpp:33:7: internal compiler error: Segmentation fault
ccache>    33 |       Logging::log(std::string_view(message_));                                \
ccache>       |       ^~~~~~~
```

Tracked by https://gcc.gnu.org/PR109241

**Comment by trofi** [comment]
Applied `ccache` backport. Ready for review.

**Comment by trofi** [comment]
Demoted `bigsearcher` mirror to help `fetch` succeed. Would be even nicer if fetch tried next URL automatically, but this workaround should do for the time being.

**Review by dasJ — APPROVED** [review]

**Comment by trofi** [comment]
Built and booted into my `system` successfully. No issues so far. `ccache` builds fine as well.

**Comment by trofi** [comment]
Built `pkgsCross.{riscv64,aarch64-multiplatform,mingwW64}.re2c` without problems. That should be a reasonable test for a minor version update.

**Comment by amjoseph-nixpkgs** [comment]
Hi, since this merged I find that `gcc` builds using only one core; very slow.

gcc-12.2.0 does not exhibit this problem.

Is anybody else experiencing this?

gcc-12.3.0 refactored the magic backdoor that gcc uses to talk to gnumake's jobserver; I suspect that is the culprit.

**Comment by trofi** [comment]
I think `jobserver` option only matters for `-flto` builds. Otherwise `make` drives the builds directly.

It's likely caused by f3995cee01fad5aeb5b67de8426a7a0321c74ebf where `.NOTPARALLEL: foo` only disables parallelism on `make-4.4+`. Bootstrap binary likely containes `make-4.3` and as a fallback disables parallelism entirely.

**Comment by amjoseph-nixpkgs** [comment]
> It's likely caused by [f3995ce](https://github.com/NixOS/nixpkgs/commit/f3995cee01fad5aeb5b67de8426a7a0321c74ebf) where `.NOTPARALLEL: foo`

Yeah, I think #229898 is the culprit.  But I don't think the problem is limited to when the bootstrap-files are used.  https://github.com/NixOS/nixpkgs/pull/229898#issuecomment-1589102751

**Comment by amjoseph-nixpkgs** [comment]
> But I don't think the problem is limited to when the bootstrap-files are used. [#229898 (comment)](https://github.com/NixOS/nixpkgs/pull/229898#issuecomment-1589102751)

It turns out there are two separate performance regressions that arrived at the same time -- one in nixpkgs (fixed by #237577, thanks!) and one known in GCC:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84402#c58

I'm still investigating the latter one.  It's pretty painful; my machines take ages to compile `gimple-match.cc` now...

**Pull request merged**
