### PR TITLE
openafs: 1.8.7 -> 1.8.8

### PR DESCRIPTION
**Pull request by rissson**
This still needs some testing.

###### Motivation for this change

https://openafs.org/dl/openafs/1.8.8/RELNOTES-1.8.8

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rissson** [comment]
Result of `nixpkgs-review pr 132007` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxPackages-libre.openafs</li>
    <li>linuxPackages_hardened.openafs</li>
    <li>linuxPackages_latest-libre.openafs</li>
    <li>linuxPackages_latest_hardened.openafs</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>linuxPackages_testing_bcachefs.openafs</li>
  </ul>
</details>
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>linuxPackages.openafs</li>
    <li>linuxPackages_4_14.openafs</li>
    <li>linuxPackages_4_19.openafs</li>
    <li>linuxPackages_4_4.openafs</li>
    <li>linuxPackages_4_9.openafs</li>
    <li>linuxPackages_5_12.openafs</li>
    <li>linuxPackages_5_13.openafs</li>
    <li>linuxPackages_5_4.openafs</li>
    <li>linuxPackages_lqx.openafs</li>
    <li>linuxPackages_xanmod.openafs</li>
    <li>linuxPackages_zen.openafs</li>
    <li>openafs</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 132007` at 87f07135 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxPackages_hardkernel_4_14.openafs</li>
    <li>linuxPackages_hardkernel_4_14.openafs_1_8</li>
    <li>linuxPackages_hardkernel_latest.openafs</li>
    <li>linuxPackages_hardkernel_latest.openafs_1_8</li>
    <li>linuxPackages_testing_bcachefs.openafs</li>
    <li>linuxPackages_testing_bcachefs.openafs_1_8</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/8d238c9d88bfb1d2bc25e3f8b805e91e">linuxPackages_hardened.openafs</a> (linuxPackages_hardened.openafs_1_8)</li>
    <li><a href="https://gist.github.com/6d71f680f7893c070cff9e9298737a08">linuxPackages_latest_hardened.openafs</a> (linuxPackages_latest_hardened.openafs_1_8)</li>
  </ul>
</details>
<details>
  <summary>8 packages skipped due to time constraints:</summary>
  <ul>
    <li>linuxPackages-libre.openafs (linuxPackages-libre.openafs_1_8)</li>
    <li>linuxPackages_4_19.openafs (linuxPackages_4_19.openafs_1_8)</li>
    <li>linuxPackages_4_4.openafs (linuxPackages_4_4.openafs_1_8)</li>
    <li>linuxPackages_4_9.openafs (linuxPackages_4_9.openafs_1_8)</li>
    <li>linuxPackages_latest-libre.openafs (linuxPackages_latest-libre.openafs_1_8)</li>
    <li>linuxPackages_lqx.openafs (linuxPackages_lqx.openafs_1_8)</li>
    <li>linuxPackages_xanmod.openafs (linuxPackages_xanmod.openafs_1_8)</li>
    <li>openafs (openafs_1_8)</li>
  </ul>
</details>
<details>
  <summary>6 packages built successfully:</summary>
  <ul>
    <li>linuxPackages.openafs (linuxPackages.openafs_1_8 ,linuxPackages_5_10.openafs ,linuxPackages_5_10.openafs_1_8)</li>
    <li>linuxPackages_4_14.openafs (linuxPackages_4_14.openafs_1_8)</li>
    <li>linuxPackages_5_12.openafs (linuxPackages_5_12.openafs_1_8)</li>
    <li>linuxPackages_5_13.openafs (linuxPackages_5_13.openafs_1_8 ,linuxPackages_latest.openafs ,linuxPackages_latest.openafs_1_8)</li>
    <li>linuxPackages_5_4.openafs (linuxPackages_5_4.openafs_1_8)</li>
    <li>linuxPackages_zen.openafs (linuxPackages_zen.openafs_1_8)</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Review by spacefrogg — APPROVED** [review]
Looking good! Thanks!

**Comment by rissson** [comment]
Tested the client on a 5.10.37 kernel, it works.

**Pull request merged**
