### PR TITLE
mongosh: 1.10.5 -> 1.10.6

### PR DESCRIPTION
**Pull request by aaronjheng**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by marsam** [comment]
What do you think of using [`buildNpmPackage`](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/javascript.section.md#buildnpmpackage-javascript-buildnpmpackage)? since upstream has a package.json https://github.com/mongodb-js/mongosh

**Comment by aaronjheng** [comment]
> What do you think of using [buildNpmPackage](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/javascript.section.md#buildnpmpackage-javascript-buildnpmpackage)

Actually. It is right now. Just with vendored `package-lock.json`.

> since upstream has a package.json https://github.com/mongodb-js/mongosh

[There were some problems when I first tried. See #219450. I've tried it a few times since, but got no luck.

**Comment by dotlambda** [comment]
Why don't we fetch `package-lock.json` from GitHub rather than censoring it?

**Comment by aaronjheng** [comment]
See https://github.com/NixOS/nixpkgs/pull/203918. There were some problems when building with `package-lock.json` from GitHub.

**Comment by dotlambda** [comment]
> See #203918. There were some problems when building with `package-lock.json` from GitHub.

This is my idea: https://github.com/NixOS/nixpkgs/commit/0ed8b005507e15aa0e6a5361ebfe14f31159c271
Please fix the remaining errors and make a PR. It's not okay to vendor 5k lines of code per package.

**Comment by aaronjheng** [comment]
@dotlambda Thanks for the tips! I tried but failed again. I believe there is something wrong with `package-lock.json` from GitHub. And I don't know how to resolve it.

**Comment by aaronjheng** [comment]
> > See #203918. There were some problems when building with `package-lock.json` from GitHub.
> 
> This is my idea: [0ed8b00](https://github.com/NixOS/nixpkgs/commit/0ed8b005507e15aa0e6a5361ebfe14f31159c271) Please fix the remaining errors and make a PR. It's not okay to vendor 5k lines of code per package.

@undefined-moe Sorry to bother. Could you take a look at this?

**Comment by undefined-moe** [comment]
Well in that github repo, the package-lock.json controls the  whole monorepo workspace (many different packages under packages/ folder, not only mongosh), and it has a different layout compared to normal installs. I agree that maintaining a huge lockfile is really stupid but I don't have other solutions.

**Comment by undefined-moe** [comment]
For example, in that repo, there's source code for package @mongosh/autocomplete, so the lock will mark this packages existence, and simply link the source code to node_modules, instead of downloading from npm. So for this kind of packages, there won't be information like hashes. And this will cause an error (as you are not bringing this source code folder into your build process) when mongosh depends on that package.

**Pull request merged**
