### PR TITLE
oxide-rs: init at 0.9.0+20241204.0.0

### PR DESCRIPTION
**Pull request by djacu**
Initializes the oxide-rs package at version 0.9.0+20241204.0.0. It provides the `oxide` and `xtask` binaries.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by djacu** [comment]
@sarcasticadmin this is ready to test out

**Comment by sarcasticadmin** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 366077`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>oxide-rs</li>
  </ul>
</details>

**Comment by sarcasticadmin** [comment]
@djacu since theres been additional work on oxide-rs since you opened this: https://github.com/oxidecomputer/oxide.rs/pull/952 I also took a stab at building this withouth the patch: https://github.com/sarcasticadmin/nixpkgs/tree/rh/djacu-elaborate-oxide-rs-9 It works but what are your thoughts on this variation?

**Comment by djacu** [comment]
@sarcasticadmin I like that we don't need `cargoPatches` any more but I'd prefer using the tagged versions. Thanks for putting in the work though; it definitely shows that we won't need it any more after 0.9.0.

**Review by sarcasticadmin — APPROVED** [review]
Sounds good! 0.9.0+20241204.0.0 and beyond :rocket:

**Comment by thiagokokada** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 366077`

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>oxide-rs</li>
  </ul>
</details>

**Comment by thiagokokada** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 366077`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>oxide-rs</li>
  </ul>
</details>

**Comment by thiagokokada** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 366077`

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>oxide-rs</li>
  </ul>
</details>

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
