### PR TITLE
mesa: 13.0.4 -> 17.0.0

### PR DESCRIPTION
**Pull request by dezgeg**
I guess this is a version bump we'll want to have for 17.03? I don't really know Mesa's versioning scheme.

I have briefly tested this (by running glmark2) with the new etnaviv driver on ARM and the vc4 driver on Aarch64. Obviously it should still be tested with drivers/hardware that people actually use ;)

cc @vcunat

### CODE REVIEW

**Comment by vcunat** [comment]
Upstream calls `*.0` releases as "development" and typically recommends general adoption since `*.1`; that seems to be typically released two weeks afterwards so I'd hope we'll squash it into 17.03 anyway.

**Comment by vcunat** [comment]
As for versioning scheme, they skipped a few numbers and are now switching to `YY.x.z` where `YY` is year and `x` is a release branch counter since the beginning of the year.

**Comment by fpletz** [comment]
cc @globin

**Comment by vcunat** [comment]
I believe we should have mesa-17.0.x in 17.03, due to getting maintenance longer and better supporting newer GPUs (most likely).  I'm fairly certain upstream will release 17.0.1 before we release 17.03.

**Comment by vcunat** [comment]
By that I mean to take this PR through staging to master now.  We can revert in the worst case.

**Comment by dezgeg** [comment]
This is now in master, so closing.

**Pull request closed without merging**
