### PR TITLE
Fix sage dependencies

### PR DESCRIPTION
**Pull request by timokau**
###### Motivation for this change

Two recent commits, ad53cf0a829dee15a6a01568b7af3b63e08717b2 and 0ccf10b955910dd511208720f3bbf49a2ffe9fbb, broke dependencies that are needed for the sage build. Both look like they can be reverted without negative consequences. I think the first one was made by mistake (probably some automation issue, cc @FRidh), while the second one was premature (cc @jonringer).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by FRidh** [comment]
Thank you. I thought I had removed the commit but apparently not.

I need to implement a way to prevent certain packages from being (automatically) updated because this is getting really annoying for everyone involved.

**Comment by jonringer** [comment]
It probably was premature, the update script did this to a fair number of packages, and I was thinking more about the python2 EOL, then maintaining python2 support.

**Comment by jonringer** [comment]
for the update script, one possible solution is to only apply the bumps if the basename of the path is "default.nix", other variations are likely meant to not be bumped

**Comment by jonringer** [comment]
@GrahamcOfBorg build sage

**Comment by timokau** [comment]
Unfortunately there are still some other issues that I'm currently tracking down. The recent python updates had an unusually big fallout.

I think this is good to be merged anyhow, since it at least fixes the sagelib build (although not the testsuite).

**Pull request merged**
