### PR TITLE
wireguard: 20161209 -> 20161218

### PR DESCRIPTION
**Pull request by zx2c4**
Hi,

Upstream here. This is a rather important version bump, so I'm making the pull request.

@grahamc 

Thanks,
Jason

### CODE REVIEW

**Comment by grahamc** [comment]
Hi @zx2c4,

Unfortunately I don't use or understand wireguard, so I'm not inclined to be merging too many changes about it. Thank you for your PR, though, I hope someone with more experience and knowledge will step in.

Thank you,
Graham

**Comment by zx2c4** [comment]
Hi @grahamc,

I'm the author of WireGuard, so I know enough about it to tell you that merging this is a good idea and quite important.

Thanks,
Jason

**Comment by grahamc** [comment]
Sorry, I don't work that way. I appreciate your feedback in to the importance.

**Comment by zx2c4** [comment]
Hi @grahamc,

Oh, alright. I understood you to mean that you didn't know whether or not this was a relavent snapshot bump, so I thought I'd weigh in that _yes indeed it is_, since I'm privy to that knowledge.

I now see that you're actually looking for a NixOS person who knows about this to answer your inquiry. So, I'll alert @ericsagnes, @fpletz, and @joachifm who all have a bit of experience with this package. Hopefully they can confirm for you.

Regards,
Jason

**Comment by fpletz** [comment]
Thanks!

**Pull request merged**
