### PR TITLE
python3Packages.netdisco: 2.8.2 -> 2.8.3

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Related Home Assistant changes (as a reference for us):

- https://github.com/home-assistant/core/pull/50130
- https://github.com/home-assistant/core/pull/50212

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 122012` at 0e19a6cb run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>expliot</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/42471e42a4b917d61e274f36e3bf106b">home-assistant</a></li>
  </ul>
</details>
<details>
  <summary>1 package skipped due to time constraints:</summary>
  <ul>
    <li>calibre</li>
  </ul>
</details>
<details>
  <summary>36 packages built successfully:</summary>
  <ul>
    <li>catt</li>
    <li>cinnamon.warpinator</li>
    <li>cura</li>
    <li>curaLulzbot</li>
    <li>dpt-rp1-py</li>
    <li>gnomecast</li>
    <li>home-assistant-cli</li>
    <li>mkchromecast</li>
    <li>octoprint</li>
    <li>python38Packages.HAP-python</li>
    <li>python38Packages.PyChromecast</li>
    <li>python38Packages.aioesphomeapi</li>
    <li>python38Packages.aiohomekit</li>
    <li>python38Packages.devolo-home-control-api</li>
    <li>python38Packages.libpurecool</li>
    <li>python38Packages.libsoundtouch</li>
    <li>python38Packages.netdisco</li>
    <li>python38Packages.openwebifpy</li>
    <li>python38Packages.pyatv</li>
    <li>python38Packages.python-miio</li>
    <li>python38Packages.pyvizio</li>
    <li>python38Packages.webthing</li>
    <li>python38Packages.zeroconf</li>
    <li>python39Packages.HAP-python</li>
    <li>python39Packages.PyChromecast</li>
    <li>python39Packages.aioesphomeapi</li>
    <li>python39Packages.devolo-home-control-api</li>
    <li>python39Packages.libpurecool</li>
    <li>python39Packages.libsoundtouch</li>
    <li>python39Packages.netdisco</li>
    <li>python39Packages.openwebifpy</li>
    <li>python39Packages.pyatv</li>
    <li>python39Packages.python-miio</li>
    <li>python39Packages.pyvizio</li>
    <li>python39Packages.webthing</li>
    <li>python39Packages.zeroconf</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 122012` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>39 packages built:</summary>
  <ul>
    <li>calibre</li>
    <li>catt</li>
    <li>cinnamon.warpinator</li>
    <li>cura</li>
    <li>curaLulzbot</li>
    <li>dpt-rp1-py</li>
    <li>expliot</li>
    <li>gnomecast</li>
    <li>home-assistant</li>
    <li>home-assistant-cli</li>
    <li>mkchromecast</li>
    <li>octoprint</li>
    <li>python38Packages.HAP-python</li>
    <li>python38Packages.PyChromecast</li>
    <li>python38Packages.aioesphomeapi</li>
    <li>python38Packages.aiohomekit</li>
    <li>python38Packages.devolo-home-control-api</li>
    <li>python38Packages.libpurecool</li>
    <li>python38Packages.libsoundtouch</li>
    <li>python38Packages.netdisco</li>
    <li>python38Packages.openwebifpy</li>
    <li>python38Packages.pyatv</li>
    <li>python38Packages.python-miio</li>
    <li>python38Packages.pyvizio</li>
    <li>python38Packages.webthing</li>
    <li>python38Packages.zeroconf</li>
    <li>python39Packages.HAP-python</li>
    <li>python39Packages.PyChromecast</li>
    <li>python39Packages.aioesphomeapi</li>
    <li>python39Packages.devolo-home-control-api</li>
    <li>python39Packages.libpurecool</li>
    <li>python39Packages.libsoundtouch</li>
    <li>python39Packages.netdisco</li>
    <li>python39Packages.openwebifpy</li>
    <li>python39Packages.pyatv</li>
    <li>python39Packages.python-miio</li>
    <li>python39Packages.pyvizio</li>
    <li>python39Packages.webthing</li>
    <li>python39Packages.zeroconf</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
Change looks good to me.

**Pull request merged**
