### PR TITLE
Yuzu: create multiplayer service module

### PR DESCRIPTION
**Pull request by PaulGrandperrin**
Hi!

I wanted to create a `yuzu-room` for my friends and I, so I created a `yuzu` module, and then I thought why not make it a real thing and upstream it.

There are still some small things that I want to add and polish, but the main code is there.

What do you think?

Some info:
- the name of the service is `yuzu-multiplayer` but maybe it should be `yuzu` or `yuzu-room`, I really don't know
- the name of the module is `yuzu`, but same question as before.
- All settings options can be overridden by values in a secretsFile (sops-nix/agenix), so you can hide the password and token, but also the room_name or port if you wish.
- values in the secretsFile overrides values from the nix options, would you prefer the other way around?
- The option descriptions comes from the `yuzu-room --help` itself
- I stole the sandboxing options from the `factorio` service, I'll probably add a few things
- i put the module in the `game` directory, should I move it elsewhere?
- And finally, I tested this on `x86_64-linux` and mostly on `aarch64-linux`, which is why I also added `aarch64-linux` to the platforms of the `yuzu` package.

@kira64xyz  @IvarWithoutBones @JoshuaFern @sbruder @K900

### CODE REVIEW

**Comment by K900** [comment]
I really don't like how it's being started here. Does it really not have a config file or something?

**Comment by PaulGrandperrin** [comment]
@nyabinary It's in a ready to use state but there's always a few more things that could be polished
I was waiting for some feedback before investing more time

@K900 No there isn't. I tried multiple designs and I found this one to be the simplest and most robust. It's a little bit verbose and uses bash arrays but it means whitespace characters can safely be passed around.

The big thing that dictated this unconventional design is that I wanted to be able to store my password in a secret and that `yuzu-room` cannot read its password from a file. I think many other services in nixpkgs do similar things when confronted with those contraints. On the top of my head `hostapd` do even weirder things to generate its config file at runtime to be able to feed it secret passwords.

Anyway, I'm open to any suggestions.

**Comment by K900** [comment]
At the very least you can use both `Environment` and `EnvironmentFile` to avoid generating the export script.

**Comment by PaulGrandperrin** [comment]
@K900 That's what I started with, but there was a problem with that. Let me a few minutes to remember why

**Comment by PaulGrandperrin** [comment]
Ok, I think I remember the main reason why I dropped `Environment` and `EnvironmentFile`.

It made it extremely inconveniant to inspect/debug the service.

Before this change, when something went wrong with the service, it was very cubbersome to launch the service manually from the command line.
One had to grep the generated system unit, source all `Environment` variables one by one, source the `EnvironmentFile` and then start the `ExecStart` script.
I guess for some configs it's ok when the `Environment*` vars are just here to add some optional configuration, but for this project they are mandatory and numerous.

Dropping `Environment*` and moving the vars in to the script made it easy to grep the `ExecStart` and launch it manually. Everything about how the program is launched is self contained in the script.

I think it's useful but I don't have hard feelings and I can revert this.

**Comment by PaulGrandperrin** [comment]
I choose to make everything overridable so that everything is handled in one and unique way.

I also thought that some people would be happy to hide any information that could leak which room their server were hosting (room name, prefered game, port...). I'm personally happy that these information are hidden from my publically accessible nixos flake.

Could you give me a list of which variables you'd like to see made non-overridable?

**Comment by K900** [comment]
It's not that I _want_ specific values to be non-overridable, it's that I see a lot of weird boilerplate and questionable shell escapes and whatnot and it feels like a lot of complexity for something that could be much simpler.

**Comment by PaulGrandperrin** [comment]
Hum, given the constraints (runtime secrets given as arguments to the program and correctly escaping whitespaces at each step) I tried to make this as simple as possible.

I really get your feeling and it's not after battling a few days with all the corner cases that I ended up with this solution. I started simple and only after I tried everything else, I added some indirection, some script or some weird escaping.

I really don't pretend it's the best solution, but I can attest that I gave a fight against all the non-inherent complexity that I could find.

**Comment by PaulGrandperrin** [comment]
If someone knows a better design for this use-case (maybe from nixpkgs), we can steal from it.
The one from `hostapd` is way more complex so it won't be useful here.

**Comment by AndersonTorres** [comment]
Closing as SLAPPed

**Pull request closed without merging**
