### PR TITLE
purescript bump

### PR DESCRIPTION
**Pull request by sheganinans**

### CODE REVIEW

**Comment by sheganinans** [comment]
Strange error.

**Comment by nckx** [comment]
My fault. `nox-review` is broken here.

**Comment by peti** [comment]
Note that we have the latest version of purescript as `haskell-ng.packages.ghc784.purescript` already.

GHC 7.8.4 cannot compile it, though, because the package depends on the latest version of `transformers`. That is a core library of GHC, so it cannnot be updated. Upstream should probably use `transformers-compat` instead.

**Comment by sheganinans** [comment]
@peti That makes sense that it would be in haskellng.

I guess the main trouble is that nox does not list the packages in haskell-ng, so I keep defaulting to the packages in haskellPackages on occasion. Since haskellPackages is doomed to be deprecated, should we just close the pull?

**Comment by peti** [comment]
Personally, I'd prefer people to switch to the NG package set ASAP, so, yeah, let's close this PR.

**Pull request closed without merging**
