### PR TITLE
vulkan-headers,vulkan-loader: 1.3.283.0 -> 1.3.289

### PR DESCRIPTION
**Pull request by fgaz**
## Description of changes

Prerequisite for packaging vulkan-enabled skia 124, which is itself a prerequisite for updating ladybird, which I maintain

edit: this wasn't actually needed. I have no idea why I thought it was, maybe I confused a different vulkan error

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by AndersonTorres** [comment]
Have you considered migrating them to by-name?

**Comment by fgaz** [comment]
> Have you considered migrating them to by-name?

Won't the automatic migration take care of that? I thought we weren't supposed to migrate manually.

**Comment by JohnRTitor** [comment]
> Won't the automatic migration take care of that? I thought we weren't supposed to migrate manually.

Technically it is allowed to migrate them manually, but only during update PRs or fixing other stuff.

**Comment by AndersonTorres** [comment]
> Won't the automatic migration take care of that? I thought we weren't supposed to migrate manually.

The manual migration is allowed in a PR in which another modification takes place.
Updates and refactors are the best opportunity for this.
(This can be useful, since the recent merge bot can merge updates from Ryanbot inside by-name hierarchy.)

Besides it, the mere migration is not recommended.

**Comment by Ralith** [comment]
Usually we try to keep the whole Vulkan SDK family in sync, e.g. https://github.com/NixOS/nixpkgs/pull/281591

**Comment by fgaz** [comment]
I was just informed about the [vulkan version tagging scheme](https://github.com/KhronosGroup/Vulkan-Headers?tab=readme-ov-file#version-tagging-scheme). This PR updates vulkan to a regular release, not a SDK. Is that fine or should we wait?

**Comment by AndersonTorres** [comment]
Given the mass-rebuild, I would wait.

**Comment by fgaz** [comment]
Makes sense, closing.

**Pull request closed without merging**
