### PR TITLE
treewide: avoid dashes in specialisation names

### PR DESCRIPTION
**Pull request by r-vdp**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by r-vdp** [comment]
@ofborg test switchTest activation-etc-overlay-mutable activation-etc-overlay-mutable caddy initrd-luks-empty-passphrase systemd-initrd-luks-fido2 systemd-initrd-btrfs-raid systemd-initrd-luks-keyfile systemd-initrd-luks-password systemd-initrd-swraid systemd-sysusers-immutable systemd-systusers-mutable taskserver thanos

**Comment by r-vdp** [comment]
@ofborg test systemd-sysusers-mutable

**Comment by r-vdp** [comment]
The swraid test seems to be broken on master as well, I think it hangs while looking for the root device.

**Comment by ElvishJerricco** [comment]
There are users with dashes in their specialisation names. Just making it so our tests don't use dashes doesn't help them. Those users will have older generations that they don't want to GC that will trigger the errors because those live outside of the new assertion.

We need to fix the actual problem and support dashes in specialisation names. This seems like *entirely* the wrong appraoch to me.

**Comment by r-vdp** [comment]
Ok, it's just a lot less clear what's a good way to do that, and I've seen several people in matrix now with broken configs because of this.

**Comment by ElvishJerricco** [comment]
My main point is that simply asserting that no specialisation has a dash in its name doesn't actually fix problems for users. Their old generations will still generate errors during `nixos-rebuild` as the `systemd-boot-builder.py` processes the old generations' specialisations.

@JulienMalka @Mic92 If we can't *fix* this problem, then I think we have to revert boot counting again until we think of something that works.

My *extremely crude* solution is to base64 encode specialisation names in the file name to make it easy to match correctly. This would work correctly but is really ugly because the file names become incomprehensible. I think we need something of similar nature, but preferably less ugly; i.e. just something that removes the dashes in a reversible way.

**Comment by r-vdp** [comment]
We could replace the dashes by `\x2d` like systemd does for paths.

**Comment by ElvishJerricco** [comment]
Yea, the only issue with that is that *technically* it would break on names including `\x2d`, unless we implemented an entire escaper (or find a pre-existing one). That's, of course, a very esoteric use case though.

**Comment by JulienMalka** [comment]
For complete reference, there is also https://github.com/NixOS/nixpkgs/pull/333857 that might be fixing the issue. Unfortunately, I am in holidays and cannot be in the proper conditions to give the necessary attention to the problem and produce a fix that is not going to blow up on us again. If the short term solution is a revert of boot counting, then let's revert. I agree that we should not break the generations of everyone that uses a dash in their specialisations names.

**Comment by ElvishJerricco** [comment]
Ah, I was not aware of the other PR. I'll take a look.

**Comment by emilazy** [comment]
> Yea, the only issue with that is that _technically_ it would break on names including `\x2d`, unless we implemented an entire escaper (or find a pre-existing one). That's, of course, a very esoteric use case though.

If dashes are the only problematic character then it's as simple as `\` → `\x5c` then `-` → `\x2d`.

**Comment by r-vdp** [comment]
> For complete reference, there is also https://github.com/NixOS/nixpkgs/pull/333857 that might be fixing the issue. Unfortunately, I am in holidays and cannot be in the proper conditions to give the necessary attention to the problem and produce a fix that is not going to blow up on us again. If the short term solution is a revert of boot counting, then let's revert. I agree that we should not break the generations of everyone that uses a dash in their specialisations names.

If we merge that one, then we should probably revert the earlier PR that added an assertion to disallow dashes.

**Pull request closed without merging**
