### PR TITLE
nixos/nsd: add multi-master-check and zonefiles-write options

### PR DESCRIPTION
**Pull request by melvyn2**
## Description of changes
Adds the options `services.nsd.zonefilesWrite` and `services.nsd.zones.<name>.multiMasterCheck`. Ideally this module should be updated to follow RFC42/freeform options but this fixes a small usability gap for now.

I left the `zonefilesWrite` default at 3600 seconds, but it might be better to default it to 0, as the module-generated zone files are unwritable and nsd complains in the logs. Unfortunately, it's a global option and can't be disabled only for the nixos-managed zones.

## Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by hrdinka** [comment]
Thank you for this addition. I just randomly came across your PR, please feel free to ping me the next time so this does not sit around so long.

Regarding `zonefiles-write`, from the documentation:

> Write changed secondary zones to their zonefile every N seconds. If the zone (pattern) configuration has "" zonefile, it is not written. Zones that have received zone transfer updates are written to their zonefile. **Default is 0 (disabled) when there is a database, and 3600 (1 hour) when database is ""**. The database also commits zone transfer contents. You can configure it away from the default by putting the config statement for zone-files-write: after the database: statement in the config file.

The database is always set to `database: "${stateDir}/var/nsd.db"` so 0 should be the default.

**Comment by melvyn2** [comment]
NSD 4.8.0 removed the database option: https://github.com/NLnetLabs/nsd/releases/tag/NSD_4_8_0_REL
Not sure why it's still in their documentation, but it doesn't serve any purpose anymore. I hadn't seen the database nixos option originally, but I might as well update this PR to remove it.
I also assumed that ofBorg would ping maintainers, but it seems it didn't pick you up: https://gist.github.com/GrahamcOfBorg/9ed65edb3d030d04f2498cf8238dc64b
Looks like I'll have to double check next time.

**Comment by melvyn2** [comment]
Just realized one of the options I added copied the older ones in using the obsolete `lib.mdDoc`, so I also removed the rest of its usages too. Hope that's not too far out of scope.

**Comment by hrdinka** [comment]
> Hope that's not too far out of scope.

Separated in several commits would have been better, but we will be fine. Thanks for the changes and clean-ups.

> I left the zonefilesWrite default at 3600 seconds, but it might be better to default it to 0, as the module-generated zone files are unwritable and nsd complains in the logs.

Does it complain every 3600 seconds? If so I am for keeping it at 0, so it is like it was before. Else we create additional work/scare for people who have NSD under monitoring. I also don’t like it to log errors in its default configuration while fulfilling its main purpose. The zones are always managed by NixOS unless it is transferring zones from another server, or am I missing something here?

Btw regarding RFC42, yes this has been on the list for some time. I would also like to add new features like composable zone configurations and additional hardening in that go. I just have been hesitant since this will break compatibility and with all of its modes of operation, testing all possible cases will also take a lot of time. Since there is never a good time for such changes I will make some time for it soon.

**Comment by melvyn2** [comment]
> Does it complain every 3600 seconds? If so I am for keeping it at 0, so it is like it was before. Else we create additional work/scare for people who have NSD under monitoring. I also don’t like it to log errors in its default configuration while fulfilling its main purpose. The zones are always managed by NixOS unless it is transferring zones from another server, or am I missing something here?

Yes, this is all correct; I added the option so that I could set it to 0 in my own uses, to silence these errors. I'll update the default to 0 then.

> Btw regarding RFC42, yes this has been on the list for some time. I would also like to add new features like composable zone configurations and additional hardening in that go. I just have been hesitant since this will break compatibility and with all of its modes of operation, testing all possible cases will also take a lot of time. Since there is never a good time for such changes I will make some time for it soon.

That is entirely understandable, and there's no rush to implement it. I just hoped to increase usability a little more in the mean time.

**Comment by hrdinka** [comment]
Thanks a lot for your changes!

**Pull request merged**
