### PR TITLE
ec2: shellcheck fixes

### PR DESCRIPTION
**Pull request by r-vdp**
## Description of changes
Fix errors when enabling shellcheck on systemd service scripts (see #311394)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by pbsds** [comment]
@ofborg test ec2-nixops

**Comment by r-vdp** [comment]
I will try to take a look later today, I think it also worked for me locally when I made this commit (several months ago, things might have changed on master in the meantime).

I used to have some machines on AWS, which is why I ran into this in the first place, but I have since moved to another platform.

**Comment by Mic92** [comment]
> `ec2-nixops` has failed twice on ofborg, but succeeds for me locally. Any ideas?
> 
> https://logs.ofborg.org/?key=nixos/nixpkgs.340489&attempt_id=708d5437-709b-43b5-9e41-f3c56c38bceb
> 
> @ofborg test ec2-nixops

I believe this plugin was also recently removed: https://github.com/NixOS/nixpkgs/pull/343727

**Comment by Mic92** [comment]
Ok. no. this was just the aws plugin.

**Comment by pbsds** [comment]
@ofborg test ec2-nixops

**Comment by r-vdp** [comment]
This test also fails on master for me when building it locally, I couldn't get it to work.

**Review by pbsds — APPROVED** [review]
able to reproduce the issue.

I checked with the shellcheck rationale, diff LGTM!

**Comment by arianvp** [comment]
Urgh this actually broke SSH access for our AWS images.   I wish I was tagged for review on this. I would've tested it.   I am marked as maintainer for `amazon-image` but apparently not for `ec2-data`.

**Comment by arianvp** [comment]
I will try to allocate some time to write / fix a NixOS test that would've made this a channel blocker

**Comment by pbsds** [comment]
Thank you for following this up. Consider adding yourself to CODEOWNERS as well to ensure the ping, since nixos PRs commonly don't ping `meta.maintainers` due to a lack of tooling. It should be possible as of https://github.com/NixOS/nixpkgs/pull/347610.

**Comment by arianvp** [comment]
I'm trying to retro why this ever made it past a channel bump and I don't understand why. `ec2-nixops`  (Which is just a badly named test as it doesn't do anything NixOps specific ; it just tests SSH access) is a channel-blocking test and it failed on this PR so I expect it also failed on Hydra.  That the test was  failing was remarked by multiple people in review and then this was merged anyway. This is not the part I'm interested in though. The part I'm interested in is why our automation didn't catch the issue after merge?

When it got merged I would expect the test to have failed on Hydra and block the channel. Why did this not happen?

**Comment by arianvp** [comment]
Ah because it's not in the `tested` job. I will make a PR to add it. I can also rename the test to be more descriptive

**Pull request merged**
