### PR TITLE
grass: 6.4.0RC6 -> 7.0.1

### PR DESCRIPTION
**Pull request by vbgl**
This is a rewrite from scratch of the `grass` derivation.

This addresses #9160; @mucaho: would you like to test?

Briefly tested on linux-x86_64.

### CODE REVIEW

**Comment by mucaho** [comment]
Thanks again for your effort @vbgl !
Your nix expression compiles fine, however `subversion` and a `gcc` are missing as run-time dependencies on my system.
Unfortunately I wasn't able to call `Grass` geo-algorithms from `QGis`, but that's not a blocking issue.

**Comment by vbgl** [comment]
> however `subversion` and a `gcc` are missing as run-time dependencies on my system.

Does it work if these dependencies are installed by other means (e.g.,
separate invocations of `nix-env -i`)?

> Unfortunately I wasn't able to call `Grass` geo-algorithms from `QGis`, but that's not a blocking issue.

I don’t really know how to test that…

I’ve updated this PR to enable GRASS support into QGIS: some more
libraries are built. But it does not seem to be enough: nothing related
to GRASS show up in the plug-in menu.

Thanks.

**Comment by mucaho** [comment]
> Does it work if these dependencies are installed by other means (e.g., separate invocations of `nix-env -i`)?

Yes, that fixes the issue. I also propose adding a [runtime wrapper](https://nixos.org/wiki/Nix_Runtime_Environment_Wrapper) to `grass`, so that these runtime dependencies get installed and linked to the executable automatically (possibly like vbgl/nixpkgs#1).

----------

> But it does not seem to be enough: nothing related to GRASS shows up in the plug-in menu.

On my machine using your new qgis expression, the grass algorithms show up, but still complain about missing dependencies. You bring up the toolbox by clicking on the menu item `Processing -> Tollbox` and then you have to switch to advanced interface at the bottom of this toolbox. They should show up as `Grass GIS 7 command`s.

--------------

> I’ve updated this PR to enable GRASS support into QGIS

Hmm, could the grass build dependency be made optional and disabled by default? I don't think it should be mandatory to always install grass alongside qgis.

------------------

As a side note, there is a special directory `applications/gis` for gis applications. Would it make sense to move the grass expression there?

**Comment by vcunat** [comment]
Looks good to me.

**Pull request closed without merging**
