### PR TITLE
amd-hybrid-graphics module: remove

### PR DESCRIPTION
**Pull request by lheckemann**
###### Motivation for this change
This was only applicable to very specific hardware, and the only person
with an apparent interest in maintaining it (me) no longer uses the
hardware in question.

cc @wkennington , original author of the module

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
wkennington no longer uses nixos either.

**Comment by Mic92** [comment]
Is the module itself broken?

**Comment by lheckemann** [comment]
>Is the module itself broken?

I don't know.

Last time it was broken, I was the only one to notice and submit #21227 which was eventually merged with only me having tested it (see also my last comment on the PR). Since there's nobody known to be using it and clearly nobody interested in maintaining it, I think it would be better to remove it rather than keep it around, since keeping around would suggest that it actually works.

**Comment by k0001** [comment]
I am using this, and I wouldn't like to see it go away in the next NixOS version. I will check that it is working as expected, and I will re-submit it.

**Comment by Mic92** [comment]
If you can test the functionality, this should be ok.

**Comment by lheckemann** [comment]
Personally I'd *suggest* just keeping it in your own nixos config repo — having it inside nixpkgs upstream made it harder to use for me (and I basically never used it in its upstream form because the fix took so long to merge).

**Comment by Mic92** [comment]
Set yourself as a maintainer for the module in this case. The overall complexity of the module is reasonable and kernel modules usually don't break with APIs.

**Comment by sondr3** [comment]
Hello, I was just asking around on IRC for some help creating a package for  [systemd-vgaswitcheroo-units](https://github.com/0x414A/systemd-vgaswitcheroo-units) for personal use and was directed to this package/pull request from @lheckemann. 

This is something I used for a long time in Arch and I would love to have it in NixOS as well, however I mentioned in IRC that this isn't just for AMD hybrid graphics but for any kind of system with two graphics cards (AFAIK). I personally use it on a MacBook Pro with Nvidia/Intel and used it to disable the Nvidia card. I'd like to add this back and set myself as a maintainer but I think it'd be reasonable to rename the package as it's not just for AMD, would you be opposed to this @Mic92?

**Comment by Mic92** [comment]
@sondr3 no.

**Comment by plredmond** [comment]
I'm using this hardware (MacBookPro11,5). @sondr3 did you rename and add this back to nixpkgs? I don't see it anywhere on master.

I'm making some changes to make this machine draw less power, which I may eventually PR back to nixpkgs: https://github.com/NixOS/nixpkgs/compare/nixos-20.03...plredmond:add/apple_set_os. I've tested the module which was removed in this PR and it works great; it reduces power consumption by about 30%.

**Comment by sondr3** [comment]
@plredmond I ended up just writing a simple unit file in my configuration instead of sending it upstream, mostly because I got a new laptop that didn’t require it.

**Pull request merged**
