### PR TITLE
Revert "Merge nixos-hardware into nixpkgs under `/nixos/hardware`"

### PR DESCRIPTION
**Pull request by grahamc**
Reverts NixOS/nixpkgs#91160

It isn't cool to merge two separate projects with only one possible hour of discussion. Also, I have questions about license compatibility.

### CODE REVIEW

**Comment by yegortimoshenko** [comment]
WRT license compatibility, nixos-hardware is CC0-1.0, which is public domain dedication with a fallback public license with no conditions of license redistribution. It can be safely removed in favor of top-level MIT.

Agree it should be discussed more.

**Review by Mic92 — CHANGES_REQUESTED** [review]
Now that it is in our git history anyway, we can actually take the time to discuss this

**Comment by grahamc** [comment]
Erm, sorry @Mic92 - your update hadn't appeared before I clicked merge. Let's revert the revert? :)

**Comment by grahamc** [comment]
and discuss there?

**Comment by edolstra** [comment]
Maybe we should do a force push to revert to the state of the repo before the nixos-hardware merge.

**Pull request merged**
