### PR TITLE
sile: postpone checks after install

### PR DESCRIPTION
**Pull request by wegank**
###### Description of changes

Supersedes #189582.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by doronbehar — APPROVED** [review]
Looks great to me! Needs upstream's approval though :)

**Review by alerque — APPROVED** [review]

**Review by alerque — APPROVED** [review]
Also looks good to me! This is actually a much more robust end-to-end test that trying to "check" that everything works while still in the build directory anyway—at the cost of a small bit of code duplication that I can pretty easily tweak to keep in sync if ever necessary.

**Comment by wegank** [comment]
@ofborg build sile sile.passthru.tests

**Comment by Artturin** [comment]
check the aarch64-darwin CI failure

**Comment by wegank** [comment]
The failure is only reproducible on my machine if the sandbox is disabled. Let's see if moving the tests to passthru.tests works.

**Comment by Artturin** [comment]
> The failure is only reproducible on my machine if the sandbox is disabled. Let's see if moving the tests to passthru.tests works.

or `doCheck = !(stdenv.isDarwin && stdenv.isAarch64);`

**Comment by wegank** [comment]
Sorry, I ended up disabling the tests on aarch64-darwin, since the error on ofborg is not reproducible on my machine...

**Review by alerque — APPROVED** [review]

**Pull request merged**
