### PR TITLE
asciidoctor: 2.0.16 -> 2.0.17, add multipage to extensions

### PR DESCRIPTION
**Pull request by FlorianFranzen**
###### Motivation for this change

This update `asciidoctor` and `asciidoctor-with-extensions` from 2.0.16 to 2.0.17 as well as adding `asciidoctor-multipages` to `asciidoctor-with-extensions`.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
We need some kind of an extension system for asciidoctor.. I see more and more PRs like this that add extensions since `asciidoctor-with-extensions` was introduced. Could you separate the update commits to a different PR?

**Comment by FlorianFranzen** [comment]
@

**Comment by SuperSandro2000** [comment]
> We need some kind of an extension system for asciidoctor.. I see more and more PRs like this that add extensions since `asciidoctor-with-extensions` was introduced. Could you separate the update commits to a different PR?

extension system is out of scope of this PR. As long as nothing breaks or we have blocking things I see no reason to do the dance with another PR.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 156210` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
20 packages marked as broken and skipped:
</summary>
<ul>
<li>collectd</li>
<li>collectd-data</li>
<li>libvmi</li>
<li>qemu_xen</li>
<li>qemu_xen-light</li>
<li>qemu_xen_4_10</li>
<li>qemu_xen_4_10-light</li>
<li>qubes-core-vchan-xen</li>
<li>xen</li>
<li>xen-light</li>
<li>xen-slim</li>
<li>xenPackages.xen-light</li>
<li>xenPackages.xen-slim</li>
<li>xenPackages.xen-vanilla</li>
<li>xenPackages.xen_4_10-light</li>
<li>xenPackages.xen_4_10-slim</li>
<li>xenPackages.xen_4_10-vanilla</li>
<li>xen_4_10</li>
<li>xen_4_10-light</li>
<li>xen_4_10-slim</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>oni2: log was empty</li>
  </ul>
</details>
<details>
<summary>
52 packages built:
</summary>
<ul>
<li>asciidoctor</li>
<li>asciidoctor-with-extensions</li>
<li>awesome (awesome-4-0)</li>
<li>bat-extras.batgrep</li>
<li>bluespec</li>
<li>bpftrace (linuxKernel.packages.hardkernel_4_14.bpftrace ,linuxKernel.packages.linux_4_14.bpftrace ,linuxKernel.packages.linux_4_14_hardened.bpftrace ,linuxKernel.packages.linux_4_19.bpftrace ,linuxKernel.packages.linux_4_19_hardened.bpftrace ,linuxKernel.packages.linux_4_4.bpftrace ,linuxKernel.packages.linux_4_9.bpftrace ,linuxKernel.packages.linux_5_10.bpftrace ,linuxKernel.packages.linux_5_10_hardened.bpftrace ,linuxKernel.packages.linux_5_15.bpftrace ,linuxKernel.packages.linux_5_15_hardened.bpftrace ,linuxKernel.packages.linux_5_16.bpftrace ,linuxKernel.packages.linux_5_4.bpftrace ,linuxKernel.packages.linux_5_4_hardened.bpftrace ,linuxKernel.packages.linux_hardened.bpftrace ,linuxKernel.packages.linux_latest_libre.bpftrace ,linuxKernel.packages.linux_libre.bpftrace ,linuxKernel.packages.linux_lqx.bpftrace ,linuxKernel.packages.linux_testing_bcachefs.bpftrace ,linuxKernel.packages.linux_xanmod.bpftrace ,linuxKernel.packages.linux_zen.bpftrace ,linuxPackages-libre.bpftrace ,linuxPackages.bpftrace ,linuxPackages_4_14_hardened.bpftrace ,linuxPackages_4_19_hardened.bpftrace ,linuxPackages_5_10_hardened.bpftrace ,linuxPackages_5_15_hardened.bpftrace ,linuxPackages_5_4_hardened.bpftrace ,linuxPackages_hardened.bpftrace ,linuxPackages_hardkernel_latest.bpftrace ,linuxPackages_latest-libre.bpftrace ,linuxPackages_latest.bpftrace ,linuxPackages_lqx.bpftrace ,linuxPackages_testing_bcachefs.bpftrace ,linuxPackages_xanmod.bpftrace ,linuxPackages_zen.bpftrace)</li>
<li>btrbk</li>
<li>ccache</li>
<li>ccacheStdenv</li>
<li>ccacheWrapper</li>
<li>code-server</li>
<li>compactor</li>
<li>credslayer</li>
<li>drbd</li>
<li>elixir_ls</li>
<li>esh</li>
<li>haka</li>
<li>haskellPackages.neuron</li>
<li>hfinger</li>
<li>keepassxc</li>
<li>mdcat</li>
<li>neuron-notes</li>
<li>newsboat</li>
<li>nux</li>
<li>ocf-resource-agents</li>
<li>openvscode-server</li>
<li>ostinato</li>
<li>pistol</li>
<li>plausible</li>
<li>pleroma</li>
<li>python310Packages.pyshark</li>
<li>python39Packages.pyshark</li>
<li>reposurgeon</li>
<li>ripgrep</li>
<li>ripgrep-all</li>
<li>rnp</li>
<li>spacevim</li>
<li>stellar-core</li>
<li>styx</li>
<li>tapview</li>
<li>termshark</li>
<li>timewarrior</li>
<li>vscode-extensions.asciidoctor.asciidoctor-vscode</li>
<li>warzone2100</li>
<li>webcat</li>
<li>weechat</li>
<li>weechat-unwrapped</li>
<li>wifite2</li>
<li>wireshark (wireshark-qt)</li>
<li>wireshark-cli</li>
<li>wsjtx</li>
<li>yosys-bluespec</li>
</ul>
</details>

**Pull request merged**
