### PR TITLE
gnome-session: add wrapGAppsHook

### PR DESCRIPTION
**Pull request by lukateras**
###### Motivation for this change

This is required to start Wayland session without `nix-shell`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by yegortimoshenko** [comment]
Additionally, maybe this should now be removed or changed:
```
    wrapProgram "$out/bin/gnome-session" \
      --prefix PATH : "${glib.dev}/bin" \
      --prefix GI_TYPELIB_PATH : "$GI_TYPELIB_PATH" \
      --suffix XDG_DATA_DIRS : "$out/share:$GSETTINGS_SCHEMAS_PATH" \
      --suffix XDG_DATA_DIRS : "${gnome3.gnome-shell}/share"\
      --suffix XDG_CONFIG_DIRS : "${gnome3.gnome-settings-daemon}/etc/xdg"
```

**Comment by jtojnar** [comment]
Yes, we should not double wrap.

**Comment by yegortimoshenko** [comment]
@GrahamcOfBorg build gnome3.gnome-session

**Comment by jtojnar** [comment]
IIRC, at least some of the variables are not added by the `wrapGAppsHook`. You will need to inspect the generated wrapper and add the missing ones with `gappsWrapperArgs`.

**Comment by hedning** [comment]
This is now fixed in https://github.com/NixOS/nixpkgs/pull/44497/commits/d54bfa8f4114a64747a6165c21599a5cc036e91a. Not sure how I missed this PR, might've helped to figure out that it was `libexec/gnome-session-binary` that needed wrapping earlier.

**Pull request closed without merging**
