### PR TITLE
k2pdfopt: Fix build and clean up

### PR DESCRIPTION
**Pull request by danielfullmer**
###### Motivation for this change

`k2pdfopt` was broken by the upgrade to `tesseract` 4.1.0.

So, `k2pdfopt` is a pain to package. The upstream author included a bunch of directories like `tesseract_mod` which contain `.cpp` and `.h` files that are to be replaced in the source of the `tesseract` used to build `k2pdfopt`.

This commit changes the way we do this by extracting those changes into a few patches we can then apply on top of those dependencies. This should hopefully be more robust to incremental changes in these dependencies--and if there are conflicts it should be easier to resolve. Moreover, packages like `leptonica` and `mupdf` have CVE patches quite often--so it'd be nice if `k2pdfopt` can get those automatically as well.

This has been tested to build. I've also tried out `k2pdfopt` using the `tesseract` OCR engine on one of my example PDFs.

ZHF #68361 (should cherry-pick cleanly onto release-19.09. I've also tested that build as well)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

CC @bosu (and myself)

### CODE REVIEW

**Comment by teto** [comment]
worked for me

**Comment by teto** [comment]
I am unsure on the process to cherry-pick to release-19.09. As you referend the main issue and I added the 19.09 label, I hope the release managers or people qualified can do it.

**Comment by Infinisil** [comment]
I pushed it to 19.09 in c9453e32b0d33a5ec641ef923708a66da3e74001

@teto Check out the release-19.09 branch, `git cherry-pick -x 740d4c2`, test it, then `git push` (maybe make sure you only push this single commit with `git log` beforehand though) :)

**Comment by teto** [comment]
ok thanks

**Pull request merged**
