### PR TITLE
webkitgtk24x: mark as insecure

### PR DESCRIPTION
**Pull request by joachifm**
See https://github.com/NixOS/nixpkgs/issues/18312

### CODE REVIEW

**Review by vcunat — APPROVED** [review]

**Comment by grahamc** [comment]
I wonder if this would be a good use of `meta.knownVulnerabilities`? https://github.com/NixOS/nixpkgs/pull/23130

**Comment by vcunat** [comment]
Oh, I forgot.  Only I suspect here the list would be too long to write out in full.

**Comment by joachifm** [comment]
I don't care so long as it gets disabled ... and soon. One point in favor of broken is that it's slated for removal, so it seems a waste of time to list the vulns.

**Comment by fpletz** [comment]
The last webkitgtk 2.4x. release was on 2016-03-10, see https://webkitgtk.org/news.html.

We're probably vulnerable to most of the issues in the advisories starting with and including WSA-2016-0004: https://webkitgtk.org/security.html

We could just refer to the relevant WSA urls or even just the security page.

I think `knownVulnerabilities` is more fitting than `broken` because lots of people seem have `allowBroken` in their nixpkgs configs as a workaround for a package at some point but never removed it.

**Comment by grahamc** [comment]
Exactly what I'm thinking, @fpletz. I'll come up with an alternative diff.

**Comment by grahamc** [comment]
@joachifm I think all the advisories since the one you updated to are relevant. Can you include those?

**Comment by vcunat** [comment]
If a new advisory comes out in future, we probably won't want to update this.  We might like to mark packages so that it's clear the CVE list may not be exhaustive.

**Comment by grahamc** [comment]
@vcunat I suppose it would be good for the output to indicate the list isn't exhaustive. It is parto f why I called it _known_ vulnerabilities, so it isn't exhaustive. How could we say this clearer?

```
➜  nixpkgs git:(master) nix-build . -A webkitgtk24x                                                           ~/projects/nixpkgs
error: Package ‘webkitgtk-2.4.11’ in ‘/home/grahamc/projects/nixpkgs/pkgs/development/libraries/webkitgtk/2.4.nix:21’ is marked as insecure, refusing to evaluate.


Known issues:

 - WSA-2017-0002
 - WSA-2017-0001
 - WSA-2016-0006
 - WSA-2016-0005
 - WSA-2016-0004
```

**Comment by joachifm** [comment]
Possibly the output for insecure could include some hedging verbiage (it does say "known issues", implying there may be unknown issues, but doesn't hurt to be clear about it).

**Comment by vcunat** [comment]
I didn't pay attention to the actual message; the formulation seems clear enough.

**Pull request merged**
