### PR TITLE
[unison] use ocaml 4.02

### PR DESCRIPTION
**Pull request by mguentner**
###### Motivation for this change

I see referenced issues. Hopefully this is the last PR :sleepy: 
###### Things done
- [x] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by obadz** [comment]
`nix-build -A unison` gets me this error:

```
ocamlopt -I /nix/store/fkpsdcx386rl0wd5z2vqdpfwy3nxzw1j-lablgtk-2.18.3/lib/ocaml/4.01.0/site-lib/lablgtk2 -g -I lwt -I ubase -I system -I fsmonitor -I fsmonitor/linux -I fsmonitor/windows -I system/generic -I lwt/generic -I +lablgtk2 -c /tmp/nix-build-unison-2.48.4.drv-0/src/uigtk2.mli
ocamlopt -I /nix/store/fkpsdcx386rl0wd5z2vqdpfwy3nxzw1j-lablgtk-2.18.3/lib/ocaml/4.01.0/site-lib/lablgtk2: uigtk2.ml ---> uigtk2.cmx
ocamlopt -I /nix/store/fkpsdcx386rl0wd5z2vqdpfwy3nxzw1j-lablgtk-2.18.3/lib/ocaml/4.01.0/site-lib/lablgtk2 -g -I lwt -I ubase -I system -I fsmonitor -I fsmonitor/linux -I fsmonitor/windows -I system/generic -I lwt/generic -I +lablgtk2 -c /tmp/nix-build-unison-2.48.4.drv-0/src/uigtk2.ml
File "/tmp/nix-build-unison-2.48.4.drv-0/src/uigtk2.ml", line 1:
Error: /nix/store/fkpsdcx386rl0wd5z2vqdpfwy3nxzw1j-lablgtk-2.18.3/lib/ocaml/4.01.0/site-lib/lablgtk2/pango.cmi
is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.
make: *** [Makefile.OCaml:435: uigtk2.cmx] Error 2
```

**Comment by mguentner** [comment]
Ah sorry. I only tested it without X11/gui support. Will look into it...

**Comment by regnat** [comment]
I think this is the wrong way to do.

Binaries generated by different versions of the ocaml compiler aren't
compatible, so unison needs to be linked against dependencies built with the
same version of the compiler.

That's why different set of ocaml packages exists, one for each packaged
version of the compiler : `ocamlPackages_3_10_0`, `ocamlPackages_4_00_1`,
`ocamlPackages_4_01_0`, `ocamlPackages_4_02` and so on.

`ocamlPackages` is just an alias for `ocamlPackages_4_01` (btw, it may should be
more than good to set the default to ocaml 4.02).

Unison should be defined in the `mkOcamlPackages` in the
`all-packages.nix` file, so that the exists an
`ocamlPackages_4_01.unison`, `ocamlPackages_4_02.unison`, etc.. ; which
all points to a version compiled against the good compiler[1].

So to get a version of unison compiled agains 4.02, you would just have to
install `ocamlPackages_4_02.unison` instead of `ocamlPackages.unison`.


[1]: And for backward compatibility, I assume it would be good to keep a `unison = ocamlPackages.unison` alias.

**Comment by joachifm** [comment]
I agree with @regnat that this isn't the best way to approach the problem, I think we can close this for now.

**Pull request closed without merging**
