### PR TITLE
KDE: update Plasma and Applications

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This PR updates Plasma to 5.6.4 and Applications to 16.04.1. I've tested the desktop and several applications.

cc @ttuegel

### CODE REVIEW

**Comment by FRidh** [comment]
note that it didn't fix #15450 for me.

**Comment by ttuegel** [comment]
Did you build everything, i.e.
```
$ nix-build -A kde5.plasma
$ nix-build -A kde5.applications
```
or just test the updated desktop?

**Comment by ttuegel** [comment]
BTW, KDE Frameworks 5.22 is due to be released today, so I will probably merge this PR at the same time as I update Frameworks, just to avoid Hydra doing a lot of pointless work.

**Comment by FRidh** [comment]
Ah, nice. No, didn't build everything.

**Comment by ttuegel** [comment]
Did you mean to close this?

Everything builds for me. Also, it looks like upstream is going to drop the ball on this release date, so I will just merge this, if closing it really was accidental. (I do that all the time, the comment/close buttons are in the wrong order.)

**Comment by FRidh** [comment]
@ttuegel yes and no, I had misread your e-mail.

**Pull request merged**
