### PR TITLE
gimpPlugins.resynthesizer: drop 

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
It breaks resynthesiser2 and there is actually no reason to keep the ancient version.

https://github.com/bootchk/resynthesizer/issues/63#issuecomment-491591082

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @jluttine

### CODE REVIEW

**Comment by jluttine** [comment]
https://github.com/NixOS/nixpkgs/issues/61341#issuecomment-491573991

**Comment by jtojnar** [comment]
I would say that is too vague. If such regression exists, it ought to be
reported. I am reluctant to keep ancient unmaintained packages just because
there is a possibility of regression.

Anyone who encounters an issue and cannot wait for it to be fixed can
always fetch the package from older revision of nixpkgs.

**Comment by 7c6f434c** [comment]
I looked at the details — «fit output to border pixels» is something that was removed from the 2.x UI, I assumed it doesn't fit the new and improved algorithm (and for the stated purpose of the plugin it might have been useless anyway)

**Comment by bootchk** [comment]
I am the maintainer of resynthesizer, not the original author, but the author of the maintained code.  I am rather sure that nothing was removed.  "fit output to border" : the engine still takes that parameter (called useBorder) but has a few more values, and the GUI of the control panel still lets you specify values, if obliquely.  There WERE some behavior changes in the engine (it no longer inverts the selection on the source image) but that only affected hard core users of the control panel, and has since been thoroughly explained and users can still do all that they ever could do.  Its been so long since 0.16 that I could be mistaken, if you have a test case that fails, I am interested.

**Comment by 7c6f434c** [comment]
Oh thank you, I just assumed that my preferences are too strange and used the old version. As far as I remember (I was experimenting together with a coworker a few years back — it was ornament completion or something like that, if I remember correctly) the new version definitely worked OK per se, but it was easier to find the settings for an output we would like with 0.16 than with then-current 2.x

**Pull request merged**
