### PR TITLE
staging-next 2022-05-12

### PR DESCRIPTION
**Pull request by vcunat**
- workflow docs: [nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy](https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy)
- constitutents: [hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents](https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents)
- jobset: [hydra.nixos.org/jobset/nixpkgs/staging-next](https://hydra.nixos.org/jobset/nixpkgs/staging-next)
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/171497

The 22.05 release schedule plans merge (of this PR) on May 15th; that's perhaps even realistic.

### CODE REVIEW

**Comment by vcunat** [comment]
- [ ] [gnat regressed](https://hydra.nixos.org/build/176570025), probably after updating maintenance (!) patches in glibc.  Say, is @sternenseemann interested in looking at it?

**Comment by vcunat** [comment]
Over longer term it might be difficult to maintain the bootstrap from such old version (gcc/gnat 6).

**Comment by vcunat** [comment]
Today is the day of the planned merge, but to me it doesn't seem suitable yet.

**Comment by vcunat** [comment]
- [ ] libpcap split caused several build regressions apparently:
  https://github.com/NixOS/nixpkgs/pull/170415#issuecomment-1127875181

**Comment by SuperSandro2000** [comment]
> * [ ]  libpcap split caused several build regressions apparently:
>       [libpcap: move dev things to extra output #170415 (comment)](https://github.com/NixOS/nixpkgs/pull/170415#issuecomment-1127875181)

# 173297

**Comment by vcunat** [comment]
Current regression list:
- https://hydra.nixos.org/eval/1762178?compare=1762151
- https://hydra.nixos.org/eval/1762178?compare=1762176  (as aarch64-darwin is separate from _trunk_ jobset)

I consider that merge-able, except that 20k builds are still queued.

**Pull request merged**
