### PR TITLE
networkmanager-l2tp: 1.2.4 -> 1.2.8

### PR DESCRIPTION
**Pull request by c0bw3b**
###### Motivation for this change
Package update
Closes: #28546

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by c0bw3b** [comment]
@abbradar @obadz as maintainers

@Mic92 @joachifm who were reviewing that previous PR

**Comment by abbradar** [comment]
Looks good for me. I don't have an L2TP server to test with it nowadays. Have you tested it?

**Comment by c0bw3b** [comment]
No same situation I don't have what's needed to test it

**Comment by abbradar** [comment]
Let's wait for some time, maybe someone else can test this...

**Comment by teto** [comment]
l2tp+strongswan has several flaws in nixos. I have a working setup with https://github.com/NixOS/nixpkgs/pull/31019 (which also bumps l2tp btw) but I have some errors in the module I described in the PR.

**Comment by disassembler** [comment]
@nixborg build

**Comment by nixborg** [comment]
@disassembler is not a committer

**Comment by obadz** [comment]
I don't use l2tp but I think setting up a server is just a matter of `services.xl2tpd.enable = true` + editing `/etc/xl2tpd/ppp/chap-secrets`.

**Comment by c0bw3b** [comment]
@teto I did check quickly but I missed that your PR was already upgrading that package, my bad.

It seems #31019 still needs to figure out some points regarding Strongswan service module.
Either I close this and we wait for your PR to reach completion, or we split the nm-l2tp update here and let your PR focus on Strongswan alone. I'm good with both scenarios.

**Comment by teto** [comment]
@c0bw3b the strongswan PR is likely to sit for a long time (I was apparently the first nixos user of an l2tp vpn) so let's keep this PR and I will update mine once this one gets merged.

**Comment by c0bw3b** [comment]
Ok perfect. :)
I will enhance this slightly by shamelessly peeking at your PR so that you won't need to modify it later (hopefully)

**Comment by disassembler** [comment]
@GrahamcOfBorg build networkmanager_l2tp

**Comment by c0bw3b** [comment]
@disassembler I will set `platforms.linux` just like networkmanager itself

**Comment by c0bw3b** [comment]
Just fixed: configure flags eval failed when called with `withGnome = false`

Now it builds properly:
```shell
Build configuration: 
  --with-gnome=no
  --with-libnm-glib=no
  --enable-absolute-paths=no
  --enable-more-warnings=
  --enable-lto=no
  --enable-ld-gc=yes
```

**Comment by garbas** [comment]
@GrahamcOfBorg build networkmanager_l2tp

**Comment by grahamc** [comment]
@garbas unfortunately you can't trigger the bot yet :) I'll fix that soon!

**Comment by garbas** [comment]
@grahamc tnx!

/me is too excited to finally have an evening of hacking after 8 months :)

**Comment by garbas** [comment]
@GrahamcOfBorg build networkmanager_l2tp

**Pull request merged**
