### PR TITLE
git, curl, openssl: Refactor $NIX_SSL_CERT_FILE handling

### PR DESCRIPTION
**Pull request by layus**
###### Motivation for this change

The way NIX_SSL_CERT_FILE (and previously SSL_CERT_FILE) support leaks from openssl to git, passing by curl.

This changes shows that 
1. we can avoid patching git by fixing curl's patch
2. we can avoid patching curl by making it rely on openssl's default CA
3. we can enable the feature proposed in #23723 and dropped with refactor at point 2.

These points correspond to the three commits. The commits should be reviewed separately to make sense.

It is an improvement/rewrite of #24121

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

/cc @shlevy @domenkozar @edolstra @vcunat

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @shlevy

**Comment by domenkozar** [comment]
This should also go to `staging-17.03` if it works.

**Comment by shlevy** [comment]
Nice!

**Comment by layus** [comment]
Thanks @shlevy :-).

Would you mind reviewing this on darwin, when hydra is ready ? Especially check that it does not introduce a regression for #23723. I have no darwin machine at hand.

PS: Is there a way to add regression tests for stuff like #23723 ?

**Comment by shlevy** [comment]
I don't have a darwin box either, sadly. @copumpkin ?

**Pull request merged**
