### PR TITLE
rootpy: init at 0.8.3

### PR DESCRIPTION
**Pull request by veprbl**
###### Motivation for this change

To provide rootpy package.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [x] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
```
ROOT cannot be imported. Is ROOT installed with PyROOT enabled?
builder for ‘/nix/store/5dndrsy22rfhk642jsd2mdmxz9a0p0w8-python3.5-rootpy-0.8.3.drv’ failed with exit code 1
error: build of ‘/nix/store/5dndrsy22rfhk642jsd2mdmxz9a0p0w8-python3.5-rootpy-0.8.3.drv’ failed
The invocation of "nix-build -A python27Packages.rootpy -A python35Packages.rootpy /home/freddy/.nox/nixpkgs" failed
```

**Comment by FRidh** [comment]
please test whether the package works with all interpreter versions

**Comment by veprbl** [comment]
it should not work with python3

**Comment by FRidh** [comment]
then you need to pass `disabled = isPy3k;`

**Comment by veprbl** [comment]
I think, this is good to merge.

**Pull request merged**
