### PR TITLE
python3Packages.z3-solver: rename from z3

### LINKED ISSUE #271918: python3Packages.z3: rename to python3Packages.z3-solver
### Describe the bug

I was using [pyproject.nix](https://github.com/nix-community/pyproject.nix) to package a project, in the `pyproject.toml`:

```toml
[project]
dependencies = ["z3-solver"]
```

Resulted in: `error: attribute 'z3-solver' missing`.

After some digging, I found the official name for z3 is z3-solver on pypi, and it's z3 here on nixpkgs. According to [python contributing guidelines](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#contributing-guidelines-contributing-guidelines), I think it'd be better to follow the naming on pypi:

z3 (Backup ZFS snapshots to S3): <https://pypi.org/project/z3/>

z3-solver (an efficient SMT solver library): <https://pypi.org/project/z3-solver/>

### Notify maintainers

@thoughtpolice @ttuegel

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by stepbrobd**
## Description of changes

closes #271918

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by fabaff — COMMENTED** [review]
Those two modules should be adjusted.

```bash
$ git grep z3-solver
pkgs/development/python-modules/claripy/default.nix:      --replace "z3-solver==4.10.2.0" ""
pkgs/development/python-modules/deal-solver/default.nix:      --replace "\"z3-solver\"," "" \
```

**Comment by stepbrobd** [comment]
Result of `nixpkgs-review pr 271924` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

<details>
<summary>
27 packages built

</summary>

- acl2
- python310Packages.deal
- python310Packages.deal-solver
- python310Packages.deal-solver.dist
- python310Packages.deal.dist
- python310Packages.icontract
- python310Packages.icontract.dist
- python310Packages.pylddwrap
- python310Packages.pylddwrap.dist
- python310Packages.z3-solver
- python311Packages.angr
- python311Packages.angr.dist
- python311Packages.angrcli
- python311Packages.angrcli.dist
- python311Packages.angrop
- python311Packages.angrop.dist
- python311Packages.claripy
- python311Packages.claripy.dist
- python311Packages.deal
- python311Packages.deal-solver
- python311Packages.deal-solver.dist
- python311Packages.deal.dist
- python311Packages.icontract
- python311Packages.icontract.dist
- python311Packages.pylddwrap
- python311Packages.pylddwrap.dist
- python311Packages.z3-solver

</details>

**Comment by natsukium** [comment]
I found more files that need to be switched.

```
pkgs/development/compilers/solc/default.nix
pkgs/development/python-modules/qiskit-terra/default.nix
pkgs/tools/security/amoco/default.nix
```

`z3` is too short and hard to find.
I wish there were a command to find the reverse dependencies.

**Comment by 7c6f434c** [comment]
In principle one could try to do a full Nixpkgs instantiation and a referrers-closure query for the Z3 derivation file…But that sounds both painful and memory-hungry.

**Review by natsukium — APPROVED** [review]
LGTM
If there are any packages we missed, they may show up as ofborg eval errors. In that case, I'll follow up quickly.

**Pull request merged**
