### PR TITLE
R 4.2.0

### PR DESCRIPTION
**Pull request by jbedo**
###### Description of changes

Updates R and rPackages to next minor release. 

There are more broken packages, but nothing major: https://hydra.nixos.org/jobset/nixpkgs/r-updates

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jbedo** [comment]
RStudio is currently failing, though it's unrelated to this (RStudio doesn't like the latest glibc with the non-constexpr MINSIGSTKSZ). Doesn't seem to be a fix upstream yet.

@bcdarwin ocaml-r is also failing:
```
write_internal_stub.c: In function 'ocamlr_write_lisplist_carval':
write_internal_stub.c:50:21: error: invalid use of undefined type 'struct SEXPREC'
   50 |   Sexp_val(lisplist)->u.listsxp.carval = Sexp_val(elmnt);
```
I tried bumping to latest release (0.5.0) to see if this had been resolved, but then it fails to find R headers (R.h). Not sure why, it's using `pkg-config`? Don't know much about ocaml...

**Comment by collares** [comment]
Thanks for the update! Seems like updating the r-Rhdf5lib patch would help unbreak quite a few packages, but I don't know how relevant that is.

**Comment by bcdarwin** [comment]
A lot of the new failures seem to be timeouts (hitting Hydra's 2hr limit!), meaning that we should probably look for a root cause before the next mass rebuild.

**Comment by jbedo** [comment]
> A lot of the new failures seem to be timeouts (hitting Hydra's 2hr limit!), meaning that we should probably look for a root cause before the next mass rebuild.

Some of these are random Hydra failures (e.g., AlleleShift) but looks like most of them are downstream of rJava. Specifically, they're downstream of rJava and have onLoads like this (from CBSr):
```
.onLoad = function(libname, pkgname) {
  rJava::.jpackage(pkgname, lib.loc = libname)
  rJava::.jaddClassPath(system.file("java",package="CBSr"))
}
```
This causes it to hang during the package load test.

**Comment by jbedo** [comment]
> Thanks for the update! Seems like updating the r-Rhdf5lib patch would help unbreak quite a few packages, but I don't know how relevant that is.

Took a look and fixed it in my branch (patch no longer needed). I'll hold off pushing here until we figure out the rJava thing to avoid tying up hydra with stalling builds again.

**Comment by bcdarwin** [comment]
On my system (x64 NixOS), calling `.jinit` (which is called by  `.jpackage`) causes a CPU-bound indefinite hang, similar to https://github.com/s-u/rJava/issues/272 at the line `xr <- .External(RinitJVM, boot.classpath, parameters)`.

**Comment by jbedo** [comment]
Thanks @bcdarwin, found it: JDK was pinned at 8 for R leading to the same stall reported upstream. Unpinning appears to have resolved it; will see how Hydra goes.

**Review by bcdarwin — APPROVED** [review]
Thanks @jbedo -- this looks to be ready to merge.

**Comment by jbedo** [comment]
I agree I think it's there, just want to bump the package set one more time. A lot of the BioC tarballs have vanished...

**Comment by vcunat** [comment]
I canceled your current evaluation, as `staging-next` just merged to `master`, so the binaries would be "obsolete".  You can merge master or rebase.

Just in case, also beware that 22.05 is being stabilized now: https://github.com/NixOS/nixpkgs/issues/165792

**Comment by jbedo** [comment]
Thanks @vcunat.

**Comment by collares** [comment]
the 22.05 branch-off is scheduled to happen tomorrow. The Hydra jobset looks good to the untrained eye (i.e., me).

**Comment by jbedo** [comment]
Agree everything looks good, thanks all!

**Pull request merged**
