### PR TITLE
openmm: use gfortran11 and gcc11Stdenv

### LINKED ISSUE #216577: Build failure: openmm
### Steps To Reproduce

1. `nix build github:nixos/nixpkgs#openmm`
or 
1. `nix build github:nixos/nixpkgs/nixos-unstable#openmm`

### Build log

https://gist.github.com/ryanswrt/757f4b9e6fab558793c86da372437b1a

### Additional context

Still works around  fab09085df1b60d6a0870c8a89ce26d5a4a708c2 - but has been broken for at least 3 days in nixos-unstable

### Notify maintainers

@sheepforce 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[nix-shell -p nix-info --run "nix-info -m"                                                               feat/qscore-workflow * ] 10:59 AM
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.9-zen1, SnowflakeOS, 23.05 (Stoat), 23.05.20230204.0591d6b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(ryanswart): `"nixos, nixpkgs"`
 - nixpkgs: `/home/ryanswart/.nix-defexpr/channels/nixpkgs`
```

### PR DESCRIPTION
**Pull request by sheepforce**
###### Description of changes

Closes #216577

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by markuskowa** [comment]
It fails to build on `aarch64-linux`

**Comment by sheepforce** [comment]
> It fails to build on `aarch64-linux`

I see. I think for aarch64 the stdenv = gcc9Stdenv. I can add this but it becomes more an more granular :grimacing:

**Comment by markuskowa** [comment]
Alternative: restrict the platform to `x86_64-linux`? This package is mostly used x86 anyway?

**Comment by sheepforce** [comment]
@ofborg build openmm

**Comment by sheepforce** [comment]
Works now again on aarch64. I'm also in favour on keeping the architecture support broader.

**Pull request merged**
