### PR TITLE
fishPlugins: init multiple plugins

### PR DESCRIPTION
**Pull request by Scrumplex**
Package some fish plugins I like to use.

- https://github.com/jethrokuan/fzf
- https://github.com/jorgebucaran/humantime.fish
- https://github.com/jethrokuan/z
- https://github.com/oh-my-fish/theme-bobthefish
- https://github.com/Scrumplex/bobthefisher

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by drupol** [comment]
Do you mind adding `bobthefish`  (https://github.com/oh-my-fish/theme-bobthefish) ?

**Comment by Scrumplex** [comment]
> Do you mind adding `bobthefish` (https://github.com/oh-my-fish/theme-bobthefish) ?

Hmm. While I use my personal fork of bobthefish instead, I guess I could package it and maybe also my fork here?

**Comment by drupol** [comment]
Yes, that's a good idea ! We should package them both and let the user decide with which one to go!

Just for my own personal information, what is the reason of the fork?

**Review by drupol — APPROVED** [review]
LGTM!

**Comment by Scrumplex** [comment]
> Just for my own personal information, what is the reason of the fork?

Just refactoring, removal of oh-my-fish stuff and addition of a Catppuccin color scheme.

**Comment by drupol** [comment]
> > Just for my own personal information, what is the reason of the fork?
> 
> Just refactoring, removal of oh-my-fish stuff and addition of a Catppuccin color scheme.

I might adopt it once this pr is merged !

**Review by drupol — APPROVED** [review]
LGTM.

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
please rebase on master

**Comment by Scrumplex** [comment]
> please rebase on master

done!

**Pull request merged**
