### PR TITLE
Update LLVM default 4 -> 5

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

Bit overdue, submitting to get this started and to track testing.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Darwin will certainly want to test this, cc @LnL7 @copumpkin

### CODE REVIEW

**Comment by LnL7** [comment]
Not sure why yet, but this causes some infinite recursion on darwin.

**Comment by dtzWill** [comment]
@LnL7 eep, confirmed and just pushed a fix :).

**Comment by dtzWill** [comment]
(updating to target staging instead)

**Comment by dtzWill** [comment]
Ping :).

**Review by LnL7 — COMMENTED** [review]
Looks like this pulls in a bunch of extra stuff that shouldn't be in the darwin stdenv.

```
output '/nix/store/30md77sa06dyz4xck99fzfj8v9rwc6i2-stdenv-darwin' is not allowed to refer to the following paths:
	/nix/store/4q1c84f1ynfvsd85a932375sg0jc89v8-bootstrap-tools
	/nix/store/54dlyn7qxp4lpjk55a8fr4s8bcslyqvc-coreutils-8.29
	/nix/store/5jp8k3v9yi342wk1d34d9qqc8qycprh4-sqlite-3.21.0
	/nix/store/9b2kv6px747r7q3x33vd0msbsr747bms-gdbm-1.13
	/nix/store/d5wdi9cjqaq8052qdw4xi1vqk90630mc-python-2.7.14
	/nix/store/gy7qv8z26ig3dbg1g9g970ys01hnbvyq-readline-6.3p08
	/nix/store/m212ikxbnvhiycw54110v2bslclam2gs-gmp-6.1.2
	/nix/store/sa86zrsrn1m4ihm0r4159vxr029w8mh9-bzip2-1.0.6.0.1
	/nix/store/xy0jx6gkv4bjs8xyi52vwn0kn8anx3in-ncurses-5.9
```

**Comment by dtzWill** [comment]
Thanks for giving it a go... bummer about the extra references! Hmm.

Oh I just noticed this: https://github.com/NixOS/nixpkgs/commit/72d9016b8ba4934d6fdcb3a76ea7cae1ab5149b8

Could that be related/cause?

**Comment by vcunat** [comment]
I don't expect the version used to bootstrap _from_ would be that important to extend closure.

**Comment by LnL7** [comment]
I'm pretty sure that's unrelated, however I wouldn't be surprised if that also needs some changes in order to work. I'll try to take a look at this soon.

**Comment by dtzWill** [comment]
python is the key:

```
$ nix why-depends /nix/store/j3r092ykx9ywnjd8x4m2zkiz014zb2fp-llvm-5.0.1 /nix/store/6yb5rvr6rvgvx8ylpchwz808djfw07rb-python-2.7.14 --all
/nix/store/j3r092ykx9ywnjd8x4m2zkiz014zb2fp-llvm-5.0.1
╚═══share/opt-viewer/opt-diff.py: …#!/nix/store/6yb5rvr6rvgvx8ylpchwz808djfw07rb-python-2.7.14/bin/python2.7..fr…
    share/opt-viewer/opt-stats.py: …#!/nix/store/6yb5rvr6rvgvx8ylpchwz808djfw07rb-python-2.7.14/bin/python2.7..fr…
    share/opt-viewer/opt-viewer.py: …#!/nix/store/6yb5rvr6rvgvx8ylpchwz808djfw07rb-python-2.7.14/bin/python2.7..fr…
    share/opt-viewer/optrecord.py: …#!/nix/store/6yb5rvr6rvgvx8ylpchwz808djfw07rb-python-2.7.14/bin/python2.7..fr…
    => /nix/store/6yb5rvr6rvgvx8ylpchwz808djfw07rb-python-2.7.14
```

I'll submit a PR fixing this once I finish compiling and testing it :).

**Comment by dtzWill** [comment]
Can someone test if that PR fixes the Darwin bootstrap problem?

Or maybe save our energy and build hours for 6 in a few months? :)

**Comment by LnL7** [comment]
The python output resolves that issue, next is `darwin.ICU` that doesn't build.

```
1 warning generated.
   c++	 ...  japancal.cpp
   c++	 ...  gregoimp.cpp
   c++	 ...  hebrwcal.cpp
   c++	 ...  indiancal.cpp
   c++	 ...  chnsecal.cpp
   c++	 ...  cecal.cpp
   c++	 ...  coptccal.cpp
   c++	 ...  nfsubs.cpp
   c++	 ...  dangical.cpp
   c++	 ...  ethpccal.cpp
   c++	 ...  coleitr.cpp
   c++	 ...  coll.cpp
   c++	 ...  sortkey.cpp
   c++	 ...  bocsu.cpp
   c++	 ...  ucoleitr.cpp
   c++	 ...  ucol.cpp
ucoleitr.cpp:323:28: error: qualified reference to 'UCollationPCE' is a constructor name rather than a type in this context
    return (UCollationPCE::UCollationPCE(elems)).nextProcessed(ixLow, ixHigh, status);
                           ^
ucoleitr.cpp:387:28: error: qualified reference to 'UCollationPCE' is a constructor name rather than a type in this context
    return (UCollationPCE::UCollationPCE(elems)).previousProcessed(ixLow, ixHigh, status);
                           ^
2 errors generated.
*** Failed compilation command follows: ----------------------------------------------------------
c++ -DU_ATTRIBUTE_DEPRECATED= -DU_I18N_IMPLEMENTATION -DSTD_INSPIRED -DMAC_OS_X_VERSION_MIN_REQUIRED=1070 -DU_HAVE_ATOMIC=1 -DU_DISABLE_RENAMING=1 -I. -I../common -DU_SHOW_CPLUSPLUS_API=1 -DU_SHOW_INTERNAL_API=1 -DU_TIMEZONE=timezone -DICU_DATA_DIR="/usr/share/icu/" -g -Os -Wglobal-constructors -fno-exceptions -fvisibility=hidden -fvisibility-inlines-hidden -fno-common -c -dynamic -MMD -MT ucoleitr.d ucoleitr.o ucoleitr.ao -o ucoleitr.o ucoleitr.cpp
```

**Comment by LnL7** [comment]
https://hydra.nixos.org/eval/1430458?compare=1430378#tabs-now-fail

**Comment by dtzWill** [comment]
The (fastjet PR](https://github.com/NixOS/nixpkgs/pull/34534) fixes the new failures!

Although it looks like many were aborted so we're not done yet...

**Comment by copumpkin** [comment]
@dtzWill @LnL7 \o/ nice!

**Comment by vcunat** [comment]
[qt4 build](https://hydra.nixos.org/build/69031325) seems broken on Darwin (noticed accidentally).

**Comment by dtzWill** [comment]
> qt4 build seems broken on Darwin (noticed accidentally).

I believe that's due to the same problem clang-5 had with qt5 (update: [yep here's the qt5 job, compare the two log tails](https://hydra.nixos.org/build/68599039)-- can whatever fixed qt5 be also done for qt4?

**Comment by LnL7** [comment]
I fixed qt59 and qt510, must have skipped over qt4 accidentally.

**Comment by vcunat** [comment]
This is still causing lots of [build regressions on staging](https://hydra.nixos.org/eval/1433563?filter=x86_64-darwin&compare=1433404&full=), most of which is pysqlite killing all haskell.  (When testing, beware of the new stdenv-rebuilding commit on staging.)

**Comment by LnL7** [comment]
Hmm, I don't think that's related to the clang update. This is a build from my test jobset https://hydra.nixos.org/build/68589517

**Comment by LnL7** [comment]
`-Lsh: -Lpkg-config: -Lcommand -Lnot -Lfound` 😄

**Comment by vcunat** [comment]
The same for includes as well.  Perhaps it will be enough to just add `pkgconfig` to `nativeBuildInputs`?

**Comment by LnL7** [comment]
I'm taking a look at it.

**Comment by vcunat** [comment]
Even with a fix, I wonder whether to just merge the hydra-built commit with the fix commit atop, directly to master... as I'd rather finish this iteration before rebuilding the world again.

**Comment by LnL7** [comment]
I guess that's ok, the amount of rebuilds on master won't be super bad.

**Comment by LnL7** [comment]
@vcunat Can you join irc?

**Pull request merged**
