### PR TITLE
ffmpeg: 2.6.3 -> 2.7.1

### PR DESCRIPTION
**Pull request by andrewrk**
cc @codyopel @Fuuzetsu 

I tested with `nix-build -A ffmpeg-full` and `nix-build -A ffmpeg`.

### CODE REVIEW

**Comment by andrewrk** [comment]
The travis build failed due to network issues, not build or test failures.

**Comment by Fuuzetsu** [comment]
I wonder if we should keep `ffmpeg_2` pointing at 2.6. Don't want to break KDE. Does someone want to test if it all still builds with 2.7?

**Comment by andrewrk** [comment]
> I wonder if we should keep ffmpeg_2 pointing at 2.6

I'm not opposed to this since I would only use the latest one, but wouldn't this break the convention where the unspecified version information is the latest?

Also, presumably, only major version number increments are build-breaking. But you're probably taking into account a mistake on behalf of ffmpeg where they allowed a breaking change into a minor release.

**Comment by andrewrk** [comment]
What command would I run to test the kde build?

**Comment by codyopel** [comment]
@Fuuzetsu 
There aren't any breaking API changes in this release so it shouldn't break any packages linking against ffmpeg.  The last API breakage happened in (2.2 -> 2.3).  The only issue should be having to rebuild if any.

@andrewrk 
To test it just find packages that build against ffmpeg and run ```nix-build -A <package name> --pure``` from the top level of the repo.  This is the easiest way without doing a lot of unnecessary builds.

**Comment by andrewrk** [comment]
What does `--pure` do? It's not mentioned in `man nix-build`.

**Comment by codyopel** [comment]
It basically clears PATH and other environment variables to help prevent your local system from potentially propogating something to the build causing it to succeed locally, but would not be reproducible on all systems.  It isn't full proof, but it helps in some cases. https://github.com/NixOS/nix/blob/master/scripts/nix-build.in#L272L273

**Comment by andrewrk** [comment]
Thanks for the explanation. I've built libgroove and chromaprint successfully, and now I'm waiting on a vlc build to finish. I'll add another comment when it's done.

**Comment by vcunat** [comment]
I believe the ``--pure`` parameter only makes difference in ``nix-shell`` (that's a symlink to the same executable which changes behavior based on what it's called like). ``nix-build`` should always be pure.

**Comment by andrewrk** [comment]
vlc built successfully.

**Comment by Fuuzetsu** [comment]
@codyopel the decision is yours, you know more about it than I do

and yes, I'm pretty sure `--pure` does nothing for `nix-build`

**Comment by andrewrk** [comment]
@codyopel any reason not to merge this?

**Comment by codyopel** [comment]
@andrewrk LGTM

**Pull request merged**
