### PR TITLE
pythonPackages.colorlog: 4.7.2 -> 4.8.0

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 117226` at 4e51f855 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python38Packages.optuna</li>
    <li>python39Packages.optuna</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/6b7480c41cfc0feddcaf7eee8271b0a6">apache-airflow</a></li>
    <li><a href="https://gist.github.com/a9088f352db1fcd1b400d45e34250326">rapid-photo-downloader</a></li>
  </ul>
</details>
<details>
  <summary>1 package skipped due to time constraints:</summary>
  <ul>
    <li>tts</li>
  </ul>
</details>
<details>
  <summary>17 packages built successfully:</summary>
  <ul>
    <li>cot (python38Packages.cot)</li>
    <li>errbot</li>
    <li>python38Packages.abodepy</li>
    <li>python38Packages.clldutils</li>
    <li>python38Packages.colorlog</li>
    <li>python38Packages.dask-gateway-server</li>
    <li>python38Packages.phonemizer</li>
    <li>python38Packages.segments</li>
    <li>python38Packages.skybellpy</li>
    <li>python39Packages.abodepy</li>
    <li>python39Packages.clldutils</li>
    <li>python39Packages.colorlog</li>
    <li>python39Packages.cot</li>
    <li>python39Packages.dask-gateway-server</li>
    <li>python39Packages.phonemizer</li>
    <li>python39Packages.segments</li>
    <li>python39Packages.skybellpy</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 117226` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python38Packages.optuna</li>
    <li>python39Packages.optuna</li>
  </ul>
</details>
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>rapid-photo-downloader</li>
    <li>tts</li>
  </ul>
</details>
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>cot (python38Packages.cot)</li>
    <li>errbot</li>
    <li>esphome</li>
    <li>python38Packages.abodepy</li>
    <li>python38Packages.clldutils</li>
    <li>python38Packages.colorlog</li>
    <li>python38Packages.dask-gateway-server</li>
    <li>python38Packages.phonemizer</li>
    <li>python38Packages.segments</li>
    <li>python38Packages.skybellpy</li>
    <li>python39Packages.abodepy</li>
    <li>python39Packages.clldutils</li>
    <li>python39Packages.colorlog</li>
    <li>python39Packages.cot</li>
    <li>python39Packages.dask-gateway-server</li>
    <li>python39Packages.phonemizer</li>
    <li>python39Packages.segments</li>
    <li>python39Packages.skybellpy</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 117226` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages marked as broken and skipped:
</summary>
<ul>
<li>python38Packages.optuna</li>
<li>python39Packages.optuna</li>
</ul>
</details>
<details>

  <summary>2 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>apache-airflow: log was empty</li>
<li>rapid-photo-downloader: log was empty</li>
  </ul>
</details>
<details>

  <summary>19 packages failed to build and are new build failures:</summary>
  <ul>
<li>cot: log was empty</li>
<li>(python38Packages.cot): log was empty</li>
<li>errbot: log was empty</li>
<li>esphome: log was empty</li>
<li>python38Packages.abodepy: log was empty</li>
<li>python38Packages.clldutils: log was empty</li>
<li>python38Packages.colorlog: <a href="https://termbin.com/gg3l">plain log</a>  |  <a href="https://htmlpreview.github.io/?https://gist.githubusercontent.com/SuperSandroBot/6a1e518df13a193da77bdeefca78a158/raw/index.html">pretty log </a></li>
<li>python38Packages.dask-gateway-server: log was empty</li>
<li>python38Packages.phonemizer: log was empty</li>
<li>python38Packages.segments: log was empty</li>
<li>python38Packages.skybellpy: log was empty</li>
<li>python39Packages.abodepy: log was empty</li>
<li>python39Packages.clldutils: log was empty</li>
<li>python39Packages.colorlog: log was empty</li>
<li>python39Packages.cot: log was empty</li>
<li>python39Packages.dask-gateway-server: log was empty</li>
<li>python39Packages.phonemizer: log was empty</li>
<li>python39Packages.segments: log was empty</li>
<li>python39Packages.skybellpy: log was empty</li>
  </ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
esphome:
<details>


warning: unused-argument
Unused argument: `fetchpatch`.
Near pkgs/tools/misc/esphome/default.nix:1:57:

```
  |
1 | { lib, python3, platformio, esptool, git, protobuf3_12, fetchpatch }:
  |                                                         ^
```
</details>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 117226` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages marked as broken and skipped:
</summary>
<ul>
<li>python38Packages.optuna</li>
<li>python39Packages.optuna</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>apache-airflow: log was empty</li>
  </ul>
</details>
<details>
<summary>
19 packages built:
</summary>
<ul>
<li>cot (python38Packages.cot)</li>
<li>errbot</li>
<li>esphome</li>
<li>python38Packages.abodepy</li>
<li>python38Packages.clldutils</li>
<li>python38Packages.colorlog</li>
<li>python38Packages.dask-gateway-server</li>
<li>python38Packages.phonemizer</li>
<li>python38Packages.segments</li>
<li>python38Packages.skybellpy</li>
<li>python39Packages.abodepy</li>
<li>python39Packages.clldutils</li>
<li>python39Packages.colorlog</li>
<li>python39Packages.cot</li>
<li>python39Packages.dask-gateway-server</li>
<li>python39Packages.phonemizer</li>
<li>python39Packages.segments</li>
<li>python39Packages.skybellpy</li>
<li>rapid-photo-downloader</li>
</ul>
</details>

**Pull request merged**
