### PR TITLE
dbeaver: 22.2.2 -> 23.2.2

### PR DESCRIPTION
**Pull request by khaneliman**
## Description of changes

Different maven hash for each run of it? 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
on a linux nixpkgs-review failed quickly
```
d-use-sandbox relaxed -f /home/teto/.cache/nixpkgs-review/pr-262442/build.nix
error: hash mismatch in fixed-output derivation '/nix/store/nnq9z764630xgn2253s538kys7lwcx0x-dbeaver-23.2.2-maven-deps.drv':
         specified: sha256-heWOdk/ovjSOUdlMMb1ZD5Mav2NYH8YjESTEWo9ytXk=
            got:    sha256-ammqolVrVwlgR/DH/IXvad7LbbSkHDzWA8qFPxxU6gg=
```

**Comment by khaneliman** [comment]
> on a linux nixpkgs-review failed quickly
> 
> ```
> d-use-sandbox relaxed -f /home/teto/.cache/nixpkgs-review/pr-262442/build.nix
> error: hash mismatch in fixed-output derivation '/nix/store/nnq9z764630xgn2253s538kys7lwcx0x-dbeaver-23.2.2-maven-deps.drv':
>          specified: sha256-heWOdk/ovjSOUdlMMb1ZD5Mav2NYH8YjESTEWo9ytXk=
>             got:    sha256-ammqolVrVwlgR/DH/IXvad7LbbSkHDzWA8qFPxxU6gg=
> ```

Yeah I have to look into the maven hashes. Each platform is reporting different hashes in ofborg.

**Comment by wegank** [comment]
https://github.com/NixOS/nixpkgs/pull/232348#issuecomment-1679848322

I guess we should simply drop this package and package the binaries instead.

**Comment by khaneliman** [comment]
> [#232348 (comment)](https://github.com/NixOS/nixpkgs/pull/232348#issuecomment-1679848322)
> 
> I guess we should simply drop this package and package the binaries instead.

Yeah... I was looking at what it would take to make the maven dependencies reproducible and it seemed like we need to either create a custom patch for each of the pom.xml and define their versions properly or upstream changes to make it have a proper lock-file.... just from the bit of reading I did anyways, haven't managed a maven project on nix.

**Pull request closed without merging**
