### PR TITLE
rocmPackages_{5,6}.miopen: fix test builds by linking gtest

### PR DESCRIPTION
**Pull request by dwf**
## Description of changes

At HEAD neither rocm 5.x or rocm 6.x versions of `miopen` succeed in building when `buildTests = true`, because gtest isn't included in `buildInputs` or correctly linked. Simply putting it in `buildInputs` isn't sufficient apparently, so this PR includes a patch to `CMakeLists.txt`.

It seems most of the tests for the rocm 5.x version pass, though overall the build fails due to non-passing tests (I am new in the rocm world so it's possible I'm holding it wrong). For rocm 6.x, there is an LLVM undefined symbol error (see #299156) that I think just means the derivation for that version of MIOpen is completely broken right now. I haven't managed to resolve it yet, and will leave #299156 open to track it, renaming as appropriate. 

Even if the tests don't pass I'd argue that having them buildable is strictly better than not. I also split it into two commits in the unlikely case there's desire to backport the 5.x fix to stable.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mschwaig** [comment]
I have never used `substitueAll` so far, so bare with me. The way I read this you are replacing two instances of `gtest_main`with `@gtest@/lib/libgtest.so @gtest@/lib/libgtest_main.so` and then with `${gtest}/lib/libgtest.so ${gtest}/lib/libgtest_main.so`

Have you considered using `substituteInPlace` with the `--replace-fail` argument to go from `gtest_main` to `${gtest}/lib/libgtest.so ${gtest}/lib/libgtest_main.so` in one step?

**Comment by dwf** [comment]
> Have you considered using `substituteInPlace` with the `--replace-fail` argument to go from `gtest_main` to `${gtest}/lib/libgtest.so ${gtest}/lib/libgtest_main.so` in one step?

You're right, in this case that would be more straightforward and maintainable. I've updated both commits, PTAL.

**Comment by dwf** [comment]
Actually, I see at HEAD in MIOpen the line is

```
target_link_libraries(${TEST_NAME} GTest::gtest GTest::gtest_main MIOpen ${Boost_LIBRARIES} hip::host $<BUILD_INTERFACE:roc::rocblas>)
```
the substitution proposed will silently succeed, I think, but yield something broken. Maybe adding a leading space before "gtest_main" and the replacement patterns would guard against this.

**Comment by mschwaig** [comment]
> Actually, I see at HEAD in MIOpen the line is
> 
> ```
> target_link_libraries(${TEST_NAME} GTest::gtest GTest::gtest_main MIOpen ${Boost_LIBRARIES} hip::host $<BUILD_INTERFACE:roc::rocblas>)
> ```
> 
> the substitution proposed will silently succeed, I think, but yield something broken. Maybe adding a leading space before "gtest_main" and the replacement patterns would guard against this.

That sounds like a good change to me.

**Review by mschwaig — CHANGES_REQUESTED** [review]
I would approve this with the following changes:

```diff
diff --git a/pkgs/development/rocm-modules/5/miopen/default.nix b/pkgs/development/rocm-modules/5/miopen/default.nix
index 9575a688706a..1c072ef1a304 100644
--- a/pkgs/development/rocm-modules/5/miopen/default.nix
+++ b/pkgs/development/rocm-modules/5/miopen/default.nix
@@ -192,7 +192,7 @@ in stdenv.mkDerivation (finalAttrs: {
       --replace "include(googletest)" ""
 
     substituteInPlace test/gtest/CMakeLists.txt \
-      --replace-fail "gtest_main" "${gtest}/lib/libgtest.so ${gtest}/lib/libgtest_main.so"
+      --replace-fail " gtest_main " " ${gtest}/lib/libgtest.so ${gtest}/lib/libgtest_main.so "
 
     ln -sf ${gfx900} src/kernels/gfx900.kdb
     ln -sf ${gfx906} src/kernels/gfx906.kdb
diff --git a/pkgs/development/rocm-modules/6/miopen/default.nix b/pkgs/development/rocm-modules/6/miopen/default.nix
index 3b40a14ec427..09bcf1042953 100644
--- a/pkgs/development/rocm-modules/6/miopen/default.nix
+++ b/pkgs/development/rocm-modules/6/miopen/default.nix
@@ -187,7 +187,7 @@ in stdenv.mkDerivation (finalAttrs: {
       --replace "include(googletest)" ""
 
     substituteInPlace test/gtest/CMakeLists.txt \
-      --replace-fail "gtest_main" "${gtest}/lib/libgtest.so ${gtest}/lib/libgtest_main.so"
+      --replace-fail " gtest_main " " ${gtest}/lib/libgtest.so ${gtest}/lib/libgtest_main.so "
 
     ln -sf ${gfx900} src/kernels/gfx900.kdb
     ln -sf ${gfx906} src/kernels/gfx906.kdb
```

If you prefer only adding the leading spaces that would also be fine with me.

**Comment by dwf** [comment]
I applied your patch, PTAL.

**Review by mschwaig — APPROVED** [review]

**Review by ulrikstrid — COMMENTED** [review]
From what I can tell these changes looks good. I'm currently running `nixpkgs-review` and it failed building `libjpeg-turbo` because some patch doesn't apply, but I don't see how that is related to this change.

**Comment by ulrikstrid** [comment]
Result of `nixpkgs-review pr 300079` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>rocmPackages.migraphx</li>
    <li>rocmPackages.mivisionx</li>
    <li>rocmPackages.mivisionx-cpu</li>
    <li>rocmPackages.mivisionx-hip</li>
    <li>rocmPackages_6.migraphx</li>
    <li>rocmPackages_6.mivisionx</li>
    <li>rocmPackages_6.mivisionx-cpu</li>
    <li>rocmPackages_6.mivisionx-hip</li>
  </ul>
</details>
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>rocmPackages_5.mivisionx (rocmPackages_5.mivisionx-hip)</li>
    <li>rocmPackages_5.mivisionx-cpu</li>
    <li>rocmPackages_5.mivisionx-opencl</li>
  </ul>
</details>
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>python311Packages.torchWithRocm</li>
    <li>python311Packages.torchWithRocm.cxxdev</li>
    <li>python311Packages.torchWithRocm.dev</li>
    <li>python311Packages.torchWithRocm.dist</li>
    <li>python311Packages.torchWithRocm.lib</li>
    <li>python312Packages.torchWithRocm</li>
    <li>python312Packages.torchWithRocm.cxxdev</li>
    <li>python312Packages.torchWithRocm.dev</li>
    <li>python312Packages.torchWithRocm.dist</li>
    <li>python312Packages.torchWithRocm.lib</li>
    <li>rocmPackages.miopen (rocmPackages.miopen-hip ,rocmPackages_6.miopen ,rocmPackages_6.miopen-hip)</li>
    <li>rocmPackages_5.migraphx</li>
    <li>rocmPackages_5.miopen (rocmPackages_5.miopen-hip)</li>
    <li>rocmPackages_5.miopen-opencl</li>
  </ul>
</details>

**Comment by mschwaig** [comment]
> From what I can tell these changes looks good. I'm currently running `nixpkgs-review` and it failed building `libjpeg-turbo` because some patch doesn't apply, but I don't see how that is related to this change.

It is not. This if fixed here: https://github.com/NixOS/nixpkgs/pull/300257

**Comment by mschwaig** [comment]
They are not related.

LGTM from my side. I approved this two weeks ago and I don't have commit bit.

**Review by ulrikstrid — APPROVED** [review]
Let's get this merged, everything here looks good!

**Pull request merged**
