### PR TITLE
survex: 1.2.44 -> 1.4.1

### PR DESCRIPTION
**Pull request by c0bw3b**
###### Motivation for this change
One less user of Python 2.x -> #148779

Use source tarball to get man pages out of the box
Depend on `proj` 8.x and `python3`
Need GApps wrapping or it crashes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by MatthewCroughan — CHANGES_REQUESTED** [review]
@goatchurchprime should test that this program works as expected.

Anyone else who wants to test can run `nix build github:c0bw3b/nixpkgs/pkg/survex#survex` and see Survex 1.4.1 in `./result`

```
user: matthew swordfish in ~ took 9s 
❯ nix build github:c0bw3b/nixpkgs/pkg/survex#survex
user: matthew swordfish in ~ 
❯ ls result/bin/
3dtopos  aven  cavern  diffpos  dump3d  extend  sorterr  survexport
```

**Comment by c0bw3b** [comment]
@ofborg eval

**Comment by MatthewCroughan** [comment]
@c0bw3b Why was this merged when no runtime testing has been performed on the packages? Could we not have waited? You have no idea whether this code works now. This treewide Nixpkgs habit of assuming just because Python packages build with Python3 that it works is very bad practice. Can you please revert this change until testing has been performed?

**Review by MatthewCroughan — COMMENTED** [review]
@c0bw3b Turns out @goatchurchprime performed runtime testing of the result and that it works fine, but he did not communicate this on Github. Please ignore my request to revert. I see that Python3 is just a nativeBuildInput, so this should be fine.

**Comment by c0bw3b** [comment]
I had tested it on my end before merging, opening samples from `http://survex.com/software/sample.tar.gz` and navigating in it.

And I verified upstream that Py3 was supported. That was part of the reason to bump this package.
The more relevant commit would be https://github.com/ojwb/survex/commit/b5a6aff283854fca3feb3a45bd5bbdfec03262fd

Remember that Py2 is EoL and unsupported now. Hence the effort to move away from it.

**Comment by MatthewCroughan** [comment]
@c0bw3b > I had tested it on my end before merging, opening samples from http://survex.com/software/sample.tar.gz and navigating in it.

Thanks a lot for that.

**Comment by goatchurchprime** [comment]
A useful addition.  Just confirming this works on my data as well.  No idea how a python dependency got anywhere near this as this software originally predates it by about 10 years.  https://survex.com/cvs.html

**Comment by c0bw3b** [comment]
Python is not a runtime dependency here, it's only needed during the build of the software because the project uses [one Python script](https://github.com/ojwb/survex/blob/master/src/igrf2c.py) to transform IGRF data.

**Pull request merged**
