### PR TITLE
mathjax-node-cli: init at 1.0.1

### PR DESCRIPTION
**Pull request by uninsane**
project homepage: <https://github.com/mathjax/mathjax-node-cli>

this tool is used in tex -> web workflows. for example, the `math2svg` pandoc filter included in nixpkgs' [pandoc-lua-filters] package -- used to transform markdown documents into html pages, for example -- has an implicit runtime dependency on the `tex2svg` binary packaged here.

[pandoc-lua-filters]: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/misc/pandoc-lua-filters/default.nix

demo usage:
```console
$ nix build '.#pandoc' -o pandoc
$ nix build '.#pandoc-lua-filters' -o filters
$ nix build '.#nodePackages.mathjax-node-cli' -o mathjax
$ echo '$$ a^2 + b^2 = c^2 $$' > math.md
$ PATH=$PATH:$(readlink mathjax)/bin  ./pandoc/bin/pandoc -t html5 -o math.html --lua-filter filters/share/pandoc/filters/math2svg.lua --standalone math.md
$ xdg-open math.html  # should see an embedded svg which was produced with mathjax
```

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by DamienCassou** [comment]
Is this PR still relevant? Could you please rebase it and fix the conflicts?

**Comment by uninsane** [comment]
> Is this PR still relevant? Could you please rebase it and fix the conflicts?

@DamienCassou rebased. `mathjax-node-cli` still gets light use by me, at least.

**Comment by DamienCassou** [comment]
Result of `nixpkgs-review pr 205864` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by dotlambda** [comment]
Please ask upstream to add a lock file and use `buildNpmPackage` instead. See #229475.

**Comment by uninsane** [comment]
opened an upstream issue for the lock file here: <https://github.com/mathjax/mathjax-node-cli/issues/19>

**Comment by dotlambda** [comment]
I suggest you open an upstream PR. Then you can immediately use the file from that PR in Nixpkgs.

**Comment by uninsane** [comment]
it’s a good idea but i’m not a node developer. any time i try to do something that should be simple like that i hit some snag that takes an entire evening to figure out, with 50% chance of success.not to be too ranty, just rather leave that part to someone more experienced with node than me.On Oct 22, 2023, at 00:19, Robert Schütz ***@***.***> wrote:﻿
I suggest you open an upstream PR. Then you can immediately use the file from that PR in Nixpkgs.

**Pull request merged**
