### PR TITLE
_1password-gui: 0.8.2-1 -> 0.8.3-1 

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

Changes:
https://discussions.agilebits.com/discussion/115413/

Also add an update script.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mlen** [comment]
Is there any chance to get this backported to 20.03?

**Comment by danieldk** [comment]
> Is there any chance to get this backported to 20.03?

Not sure if it is worth it. 20.09 is branched soon and the release is probably in 1-2 months.

**Comment by mlen** [comment]
True, but it would grant the ability to easily use it to all those who are using the stable branch for few more months

**Comment by danieldk** [comment]
> True, but it would grant the ability to easily use it to all those who are using the stable branch for few more months

I looked into it, but we do not have Electron 9 in 20.03.

**Pull request merged**
