### PR TITLE
fetch-cargo-{tarball,vendor}: make cargoRoot argument explicit

### PR DESCRIPTION
**Pull request by Aleksanaa**
Some people are accustomed to using `__functionArgs` to tell which arguments can be passed into function, and it's good to explicitly tell people the most common arguments available.

#350541

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by TomaSajt — COMMENTED** [review]
I really dislike default parameters combined with `@args`.

Those "defaults" do literally nothing, even if one would expect them to be defaults values always passed, they are not present in `@args`.

---

I know I added a default `cargoRoot` to `buildRustPackage`, but that was because the value was needed to be sent over to the fetchers.
(Note that that PR caused 0 rebuilds, because `@args` didn't contain `cargoRoot` and we only passed `cargoRoot` to FODs, which don't rebuild by default)

---

In my opinion this pattern is much more optimal:
https://github.com/TomaSajt/nixpkgs/blob/975a1c1601ea3977f8b1593cedeb9d19b6eafab5/pkgs/build-support/rust/build-rust-package/default.nix#L28
https://github.com/TomaSajt/nixpkgs/blob/975a1c1601ea3977f8b1593cedeb9d19b6eafab5/pkgs/build-support/rust/build-rust-package/default.nix#L92-L99

since it doesn't need a default value if unset.

**Review by philiptaron — DISMISSED** [review]
Yeah, I buy that thinking. Heaven help us if this changes the semantics. I verified that the defaults are consistent with other places in the tree.

**Comment by TomaSajt** [comment]
also `__functionArgs` is not useful if we have `// args` anyways

**Comment by Aleksanaa** [comment]
> Those "defaults" do literally nothing, even if one would expect them to be defaults values always passed, they are not present in `@args`.

Yes, they do nothing if you reference them from `args`. This is just to make `__functionArgs` people happy. Of course a more correct approach is to just don't write them at all and use doc-comments everywhere, but we haven't.

**Comment by philiptaron** [comment]
> I really dislike default parameters combined with `@args`.

While I truly empathize with that dislike, I got over it by imagining the following rewrite in my head each time:

```nix
{
  name ? if args ? pname && args ? version then "${args.pname}-${args.version}" else "cargo-deps",
  pname ? null,
  version ? null,
  hash ? (throw "fetchCargoVendor requires a `hash` value to be set for ${name}"),
  src ? null,
  srcs ? [ ],
  patches ? [ ],
  sourceRoot ? "",
  cargoRoot ? "",
  nativeBuildInputs ? [ ],
  ...
}@args:
```

turns into:

```nix
args:

let
  name = if args ? pname && args ? version then "${args.pname}-${args.version}" else "cargo-deps";
  pname = args.pname or null;
  version = args.version or null;
  hash = args.hash or throw "fetchCargoVendor requires a `hash` value to be set for ${name}";
  src = args.src or null;
  srcs = args.srcs or [ ];
  patches = args.patches or [ ];
  sourceRoot = args.sourceRoot or "";
  cargoRoot = args.cargoRoot or "";
  nativeBuildInputs = args.nativeBuildInputs or [ ];
in
```

Somehow, having the defaults be "just" name bindings in a `let` block satisfies me in a way that the alternate model (actual values in an attrset) does not.

**Comment by TomaSajt** [comment]
I agree that removing everything from inside the `{ }` can be horrible, and that's why I still listed a few things in `fetchCargoVendor`.
However, everything I listed in the `{ }` was explicitly removed with `removeAttrs`.
I think this pattern is an improvement over listing everything.

Also, I'm using `// args'` instead of `args' //` to force the code to be explicit about what names are special.

**Comment by TomaSajt** [comment]
I might have misunderstood your message, you were actually just talking about a different way of thinking about the ?  default pattern.

**Review by TomaSajt — COMMENTED** [review]
In any case, moving back to the actual changes of the PR, I would accept the `fetchCargoTarball` change, but not the `fetchCargoVendor` change.

I was explicitly being minimal about the listed names. Would not be happy about changing it.

**Comment by Aleksanaa** [comment]
Then as long as nobody requests I don't add it. I think we'd switch to doc-comment later so not a big deal.

**Pull request closed without merging**
