### PR TITLE
puppeteer-cli: init

### PR DESCRIPTION
**Pull request by chessai**
###### Motivation for this change
add puppeteer-cli tool

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by chessai** [comment]
I don't quite understand the error. If anyone can tell what it means, please let me know. Thanks

**Comment by chessai** [comment]
Apparently, mkYarnPackage uses IFD to turn package.json into yarn.nix

and i need to use yarn2nix (the binary) to generate a yarn.nix file and then set yarnNix = ./yarn.nix; to skip the IFD step

**Comment by dotlambda** [comment]
@7c6f434c Can you please explain why this was merged without `meta` and properly formatted commit messages?

**Comment by 7c6f434c** [comment]
Wait, license (specified in the data) doesn't get put into meta.license? missed that.

**Comment by dotlambda** [comment]
Oh, I didn't know `mkYarnPackage` also populates `meta` with data from `package.json`. However, `meta.homepage` and `meta.maintainers` are missing.

**Comment by 7c6f434c** [comment]
I am not strict about homepage even now (and about commit naming if at least some commits are named well enough to be searchable), and I wasn't worrying much about maintainership record two and a half years ago, I admit that.

More constructively and forward-looking: @chessai would you add yourself as a maintainer here?

**Comment by chessai** [comment]
> I am not strict about homepage even now (and about commit naming if at least some commits are named well enough to be searchable), and I wasn't worrying much about maintainership record two and a half years ago, I admit that.
> 
> More constructively and forward-looking: @chessai would you add yourself as a maintainer here? 

yes

**Comment by dotlambda** [comment]
> I am not strict about homepage even now (and about commit naming if at least some commits are named well enough to be searchable)

I think we should care about homepages. An easy-to-click link to use during reviews is worth a lot.
Here, the commits should have been squashed and the first one should have mentioned the version. That's our convention outlined in the contributing guidelines. If you want to merge PRs you should be willing to follow those.

**Comment by dotlambda** [comment]
This adds the missing meta attributes and adds @chessai as maintainer: https://github.com/NixOS/nixpkgs/pull/253749

**Pull request merged**
