### PR TITLE
asusctl: 4.6.2 -> 4.7.0

### LINKED ISSUE #248436: Update request: asusctl 4.6.2 → 4.7.0
- Package name: `asusctl`
- Latest released version: `4.7.0`: https://gitlab.com/asus-linux/asusctl/-/tree/4.7.0

- Current version on the unstable channel: `4.6.2`
- Current version on the stable/release channel: not sure

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

cc: @aacebedo who did the last update
cc: @K900 who I think is also a user and likely reviewer.

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by K900**
## Description of changes

https://gitlab.com/asus-linux/asusctl/-/releases/4.7.0

Fixes #248436.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
Some annoying changes there, please test.

**Comment by aacebedo** [comment]
Tested and working. Only remark, the app is displaying 4.7.0-RC3 instead of 4.7.0

**Review by aacebedo — APPROVED** [review]

**Comment by K900** [comment]
That's just upstream tagging things weird again. Do you have the dot matrix display thingy? Most of the changes in this update seem to be related to that.

**Comment by aacebedo** [comment]
> That's just upstream tagging things weird again. Do you have the dot matrix display thingy? Most of the changes in this update seem to be related to that.

Nope unfortunately.

**Pull request merged**
