### PR TITLE
GNUs on Darwin

### PR DESCRIPTION
**Pull request by matthewbauer**
Enable some GNU packages that support Darwin.

### CODE REVIEW

**Comment by dtzWill** [comment]
\o/

**Comment by matthewbauer** [comment]
@grahamcofborg build mailutils

**Comment by matthewbauer** [comment]
@GrahamcOfBorg build mailutils

**Comment by matthewbauer** [comment]
@GrahamcOfBorg build mailutils

**Comment by matthewbauer** [comment]
@GrahamcOfBorg build mailutils

**Pull request merged**
