### PR TITLE
[19.09] go_1_13: 1.13.1 -> 1.13.7, go_1_12: 1.12.9 -> 1.12.16 (backport)

### PR DESCRIPTION
**Pull request by Frostman**
###### Motivation for this change

Backport latest patch versions for go in 19.09 branch as there are tons of CVE fixed in them. I'm not sure what should be the process, but, IMO it's quite important from security point of view.

@kalbasit probably, you can advise, thank you!

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/79513)

### CODE REVIEW

**Comment by Frostman** [comment]
`nixpkgs-review pr 79513` succeded with 666 packages built

**Comment by kalbasit** [comment]
Please cherry-pick all backported commits with `-x`.

See https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#backporting-changes

**Comment by Frostman** [comment]
Executed `nixpkgs-review pr 79513` one more time just in case - works fine. With that PR go compiler in 19.09 is in sync with current unstable.

**Comment by kalbasit** [comment]
@GrahamcOfBorg build pet jx kubectl prow

**Review by kalbasit — APPROVED** [review]

**Pull request merged**
