### PR TITLE
beam/mixRelease: default stripDebug to false due to frequent runtime errors

### PR DESCRIPTION
**Pull request by erictapen**
This flag appears to cause issues in 3 out of 4 users of mixRelease in Nixpkgs, plus Mobilizon, which isn't merged yet. It might be safer to set it to fals for now, as the runtime error messages produced by it are quite cryptic.

Introduced in https://github.com/NixOS/nixpkgs/pull/191237

Pinging maintainers of affected packages, even though this should be noop to everything inside of nixpkgs.

@NixOS/beam @mvs @NinjaTrappeur @yu-re-ka @Kloenk 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by erictapen** [comment]
@GrahamcOfBorg test plausible pleroma akkoma elixir-ls

**Review by happysalada — APPROVED** [review]
LGTM, leaving it one day open, just in case other people want to have a look at it.

**Comment by NobbZ** [comment]
Result of `nixpkgs-review pr 232107` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>akkoma</li>
    <li>elixir-ls</li>
    <li>plausible</li>
    <li>pleroma</li>
  </ul>
</details>

**Review by NobbZ — APPROVED** [review]
I tried to build using `--system aarch64-linux` in a binfmt emulated environment, I got `qemu` related errors there, and assume that this is not related to your changes but a general problem with erlang in qemu.

I am fine with the changes and the overal reasoning behind it.

**Review by kloenk — APPROVED** [review]
Sounds reasonable

**Review by picnoir — APPROVED** [review]
LGTM on the Pleroma side.

**Comment by erictapen** [comment]
Thanks everyone for the fast reviews!

**Pull request merged**
