### PR TITLE
mastodon: 4.0.2 -> 4.1.0

### PR DESCRIPTION
**Pull request by erictapen**
###### Description of changes

As 4.1.0rc1 is out I thought we could share the effort for testing. This far it looks pretty good, both tests are green.

[Changelog rc1](https://github.com/mastodon/mastodon/releases/tag/v4.1.0rc1)

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by turion** [comment]
> we could share the effort for testing

How do you test? Do you run a separate test instance?

**Comment by erictapen** [comment]
> How do you test? Do you run a separate test instance?

Personally I just run the integration tests, but maybe somebody else does it this way?

**Review by Izorkin — APPROVED** [review]

**Comment by Izorkin** [comment]
> How do you test? Do you run a separate test instance?

Checking on the internal test server with federation disabled.

**Comment by Izorkin** [comment]
v4.1.0rc2 working.

**Comment by erictapen** [comment]
> v4.1.0rc2 working.

Do you have a commit on a public branch I could pull from?

**Comment by Izorkin** [comment]
> Do you have a commit on a public branch I could pull from?

[mastodon_4.1.0rc1_4.1.0rc2.patch](https://github.com/NixOS/nixpkgs/files/10511897/mastodon_4.1.0rc1_4.1.0rc2.patch)

**Comment by erictapen** [comment]
@Izorkin I'm getting an error message, when applying your patch.

```
$ git apply mastodon_4.1.0rc1_4.1.0rc2.patch
error: corrupt patch at line 6
```

Could you just push it to a git remote where I can pull from? E.g. your Nixpkgs fork on GitHub?

**Comment by Izorkin** [comment]
@erictapen i have several custom patches.

> Could you just push it to a git remote where I can pull from? E.g. your Nixpkgs fork on GitHub?

Here - https://github.com/Izorkin/nixpkgs/tree/local-01

In the current patch, you can delete these lines and correct the changes manually:
```diff
diff --git a/pkgs/servers/mastodon/source.nix b/pkgs/servers/mastodon/source.nix
index a0b6e33458e..8a46696f550 100644
--- a/pkgs/servers/mastodon/source.nix
+++ b/pkgs/servers/mastodon/source.nix
@@ -2,10 +2,10 @@
 { fetchgit, applyPatches }: let
   src = fetchgit {
     url = "https://github.com/mastodon/mastodon.git";
-    rev = "v4.1.0rc1";
-    sha256 = "07585l6sddddvkg5glqqczkzwhhwydyyhnw66c6gd4y769hd4628";
+    rev = "v4.1.0rc2";
+    sha256 = "sha256-FHk6HAKHXq9thIW8zrEhtfCp6feqm6jjebwd9ykrz3A=";
   };
 in applyPatches {
   inherit src;
-  patches = [ ./max_status_lenght.patch ./timeout.patch ./23252.patch ];
+  patches = [ ./max_status_lenght.patch ./timeout.patch ];
 }

```

**Review by Izorkin — APPROVED** [review]

**Comment by imsofi** [comment]
Official release is now out.
https://github.com/mastodon/mastodon/releases/tag/v4.1.0

**Review by Izorkin — APPROVED** [review]

**Review by erictapen — COMMENTED** [review]
I see both tests green on this, so I'd say it is ready to go!

**Comment by Izorkin** [comment]
Yes, it works.

**Comment by SuperSandro2000** [comment]
Tested on my instance and works.

**Comment by f2k1de** [comment]
can we backport this to 22.11?

**Comment by SuperSandro2000** [comment]
Really not sure about backporting especially I am unsure which module parts need backports, too.

**Comment by Izorkin** [comment]
> Really not sure about backporting especially I am unsure which module parts need backports, too.

Mastodon 4.1.0 working on NixOS 22.11.

**Pull request merged**
