### PR TITLE
coq: making sure coq master and 9.0 compile

### PR DESCRIPTION
**Pull request by CohenCyril**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by CohenCyril** [comment]
For now this errors with the following message when running `./result/bin/coqtop` :confused: 
```
Welcome to Coq 9.0+alpha
Error:
Findlib error: zarith not found in:
/nix/store/c2hwnp5ryalzz1rwldp7a87lzxaq1329-coq-dev/lib/coq/../coq-core/..
/nix/store/c2hwnp5ryalzz1rwldp7a87lzxaq1329-coq-dev/lib/coq/user-contrib/Ltac2
/nix/store/c2hwnp5ryalzz1rwldp7a87lzxaq1329-coq-dev/lib/coq/user-contrib/Ltac2/Compat
/nix/store/bj6kj93sbg5j0vgv5yrxfcq91fj9pqfi-ocaml4.14.2-findlib-1.9.8/lib/ocaml/4.14.2/site-lib
required by `coq-core.interp'
```

**Comment by vbgl** [comment]
Thanks Cyril for working on this! Regarding the coqtop failure, did you try wrapping the binary (like, e.g., `rtop`): https://github.com/NixOS/nixpkgs/blob/b3438737b45049d9968e8ad510fb1d188d6b13b7/pkgs/development/compilers/reason/rtop.nix#L23-L28

**Comment by vbgl** [comment]
This was wrong advice. Sorry about that.

I guess this PR can be closed, thanks to the nice work by Pierre.

**Comment by CohenCyril** [comment]
Subsumed by https://github.com/NixOS/nixpkgs/pull/364617/

**Pull request closed without merging**
