### PR TITLE
rocksdb: 6.14.6 -> 6.15.4

### PR DESCRIPTION
**Pull request by cpcloud**
###### Motivation for this change

The motivation for this change is to update the rocksdb package.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
```
hash mismatch in fixed-output derivation '/nix/store/i1gr74ry8smxjmni9xka08mna3vnc2qn-source.drv':                                                                                            specified: sha256-MTpIF0Tmd5xGxi3H8dW++60y6qOYONxtlMHLo2MjxR4=                                                                                                                                 got:    sha256-a2zf+OvTN6csnVoEGn1EIgWi1Y27ghvOF9ncxZip1os=
```

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109633` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
5 packages built:
</summary>
<ul>
<li>blockbook</li>
<li>haskellPackages.rocksdb-haskell-jprupp</li>
<li>rocksdb</li>
<li>rocksdb_lite</li>
<li>sortmerna</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109633` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>sortmerna: log <a href="https://termbin.com/728f">https://termbin.com/728f</a></li>
  </ul>
</details>
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>blockbook</li>
<li>haskellPackages.rocksdb-haskell-jprupp</li>
</ul>
</details>

**Comment by cpcloud** [comment]
@SuperSandro2000 The darwin failure kind of looks like a C++ compiler version issue, but I don't have a mac around that I can use to debug.

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 The darwin failure kind of looks like a C++ compiler version issue, but I don't have a mac around that I can use to debug.

Can you mark sortmerna broken on darwin?

**Review by SuperSandro2000 — APPROVED** [review]
otherwise LGTM

**Pull request merged**
