### PR TITLE
gperftools: 2.6.1 -> 2.6.3

### PR DESCRIPTION
**Pull request by ryantm**
Semi-automatic update. These checks were done:

- built on NixOS
- ran `/nix/store/ba54ymdab4y2jcxwbmn71sm698cy1wik-gperftools-2.6.3/bin/pprof --help` got 0 exit code
- ran `/nix/store/ba54ymdab4y2jcxwbmn71sm698cy1wik-gperftools-2.6.3/bin/pprof --help` and found version 2.6.3
- found 2.6.3 with grep in /nix/store/ba54ymdab4y2jcxwbmn71sm698cy1wik-gperftools-2.6.3
- found 2.6.3 in filename of file in /nix/store/ba54ymdab4y2jcxwbmn71sm698cy1wik-gperftools-2.6.3

cc @vcunat @wkennington

### CODE REVIEW

**Comment by Mic92** [comment]
@alk is the deprecated `_dyld_present` on macOS fixed in  an unreleased version of gperftools?

**Comment by Mic92** [comment]
@GrahamcOfBorg build gperftools

**Comment by Mic92** [comment]
The actual compile error is a different though.

**Comment by Mic92** [comment]
```
stack_trace_table.cc:60:14: note: if you supply your own aligned allocation functions, use -Wno-aligned-allocation-unavailable to silence this diagnostic
src/stack_trace_table.cc:117:16: error: aligned deallocation function of type 'void (void *, std::align_val_t) throw()' possibly unavailable on x86_64-apple-macosx10.10.0 [-Waligned-allocation-unavailable]
  void** out = new void*[out_len];
               ^
src/stack_trace_table.cc:117:16: note: if you supply your own aligned allocation functions, use -Wno-aligned-allocation-unavailable to silence this diagnostic
```

**Comment by alk** [comment]
>> @alk is the deprecated _dyld_present on macOS fixed in an unreleased version of gperftools?

No. Those warnings have been there for years.

**Pull request merged**
