### PR TITLE
k3s_1_31: 1.31.1+k3s1 -> 1.31.2+k3s1

### LINKED ISSUE #255783: k3s: data corruption on ordinary system shutdown
### Describe the bug
Containers and k3s is not stopped before the filesystems are unmounted. This results in a complete loss of state and data during a completely ordinary system shutdown.

### Steps To Reproduce
1. Shutdown your system.
2. Watch containerd shutdown after the filesystem has unmounted your disks, resulting in corruption and loss.

### Expected behavior
Shutdown
k3s-killall.sh
umount

### Notify maintainers

cc @euank @Mic92 @yajo

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.52, NixOS, 23.05 (Stoat), 23.05.3427.e5f018cf150e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by superherointj**
* k3s_1_31: 1.31.1+k3s1 -> 1.31.2+k3s1
* k3s_1_30: 1.30.5+k3s1 -> 1.30.6+k3s1

Fixes #255783

CC @NixOS/k3s 

I'm not including 1.29, 1.28 because a fix is necessary and I don't have it ready.

### CODE REVIEW

**Comment by superherointj** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 352182`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>k3s</li>
    <li>k3s_1_28</li>
    <li>k3s_1_29</li>
    <li>k3s_1_30</li>
  </ul>
</details>

**Comment by superherointj** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 352182`

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>k3s</li>
    <li>k3s_1_28</li>
    <li>k3s_1_29</li>
    <li>k3s_1_30</li>
  </ul>
</details>

**Comment by superherointj** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 352182`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>k3s</li>
    <li>k3s_1_30</li>
  </ul>
</details>

**Comment by superherointj** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 352182`

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>k3s</li>
    <li>k3s_1_30</li>
  </ul>
</details>

**Comment by rorosen** [comment]
The packages build fine for me and test pass as well, however, I can only test on x86_64-linux and ofborg says the multi-node test fails on aarch64-linux. I think this is a flaky test because the logs don't make sense to me, is there a way to tell ofborg to run the tests on aarch64 again?

Otherwise LGTM

**Review by rorosen — APPROVED** [review]

**Comment by superherointj** [comment]
`aarch64-linux` errors as:
- k3s-1.31.2+k3s1-multi-node.log
   https://termbin.com/e04z

image

**Comment by rorosen** [comment]
> nix build .#k3s.passthru.tests.multi-node fails in aarch64-linux

I can't reproduce the failing test on aarch64. The multi-node test seems to be very flaky (it succeeded for me only after 2 restarts), but when it failed I got an error like `services have not yet been read at least once, cannot construct envvars`, not `INVALIDARGUMENT` or anything related to flags. The ofborg tests also have succeeded on aarch64, are you sure that the error you get is related to the update?

**Comment by rorosen** [comment]
However, we should address the flaky multi-node test somehow...

**Comment by superherointj** [comment]
I think, the problem might be that the Raspberry Pi 4, doesn't have enough resources to run the tests. So in this case, let's go ahead.

**Review by rorosen — APPROVED** [review]
I created an issue for the flaky test in https://github.com/NixOS/nixpkgs/issues/354211, however, shouldn't block this as it's not related to this update.

**Comment by superherointj** [comment]
I think, this should be merged. There is a problem with tests but it should be handled elsewhere.

CC @marcusramberg

**Review by wrmilling — APPROVED** [review]

**Comment by superherointj** [comment]
@marcusramberg I think you can merge this.

**Pull request merged**
