### PR TITLE
rapid-photo-downloader: fix QT wrapping

### PR DESCRIPTION
**Pull request by lightbulbjim**
###### Motivation for this change

Fixing QT wrapping as per #65399. Wrapping is done manually as this is a Python app. To be honest I'm not sure if this is the right approach, but it works. Suggestions welcome.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @jfrankenau

### CODE REVIEW

**Review by worldofpeace — CHANGES_REQUESTED** [review]
See `qutebrowser` with as an example of how to do this. (the mkDerivationWith part)
And please wrap in `preFixup`.

**Comment by lightbulbjim** [comment]
I'm a bit stuck with how to proceed. Moving the wrapping to `preFixup`/`postFixup` is fine, but I'm not sure what using `mkDerivationWith` buys me.

Also, from my understanding the way forward is to use declarative wrappers, however if I use `wrapQtAppsHook` then I end up setting `dontWrapQtApps = true` and manually calling `wrapProgram` anyway.

Finally, I can't find a way to avoid double-wrapping the binaries (once for Python libs, once for QT). But that just seems to be the way it works at the moment.

Between the wrappers being reworked and the recent QT changes it's sometimes hard to differentiate between "new best practices" and deprecated patterns :-).

**Comment by lightbulbjim** [comment]
Does that look reasonable? I must admit I don't entirely understand which is the desired approach so I'm cargo culting from other derivations a little. It works though.

**Comment by worldofpeace** [comment]
We can avoid the double wrapping safely by doing this instead:

add
```
 "\${qtWrapperArgs[@]}"
```

to `makeWrapperArgs`. That way the wrapper that `buildPythonApplication` creates will have all the arguments from qt's setup hook. 

Also you don't need to include `wrapQtAppsHook` when using `mkDerivationWith` since it'll include it automatically.

**Comment by worldofpeace** [comment]
Additionally, I'm just noticing this. How does this depend on qt?

This looks more like an application that would need `wrapQtAppsHook`.
What error did you see at runtime?

**Comment by lightbulbjim** [comment]
> We can avoid the double wrapping safely by doing this instead:
> 
> add
> 
> ```
>  "\${qtWrapperArgs[@]}"
> ```
> 
> to `makeWrapperArgs`. That way the wrapper that `buildPythonApplication` creates will have all the arguments from qt's setup hook.

Nifty! I was just trying to do this on another similar package but it was failing because I wasn't escaping the sigil. Thanks!

> Also you don't need to include `wrapQtAppsHook` when using `mkDerivationWith` since it'll include it automatically.

Yeah, I just found some docs I hadn't seen before which explained this. Then looking at the source it's starting to make sense. The names were confusing me (eg it wasn't immediately obvious that `mkDerivationWith` is a QT specific thing just from its name).

Anyway, updated and it looks much cleaner now. Thanks for the pointers.

**Review by worldofpeace — APPROVED** [review]
Builds and executes for me. I inspected the wrappers on the binaries and they have the arguments from `wrapQtAppsHook`.

**Pull request merged**
