### PR TITLE
python3Packages.asyncpg: 0.23.0 -> 0.24.0

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 0.24.0

Change log: https://github.com/MagicStack/asyncpg/releases/tag/v0.24.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Is that mautrix bump unrelated?

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 133643` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>theharvester</li>
  </ul>
</details>
<details>
  <summary>38 packages built:</summary>
  <ul>
    <li>dyndnsc</li>
    <li>esphome</li>
    <li>home-assistant</li>
    <li>mautrix-signal</li>
    <li>mautrix-telegram</li>
    <li>platformio</li>
    <li>python38Packages.asyncpg</li>
    <li>python38Packages.databases</li>
    <li>python38Packages.dependency-injector</li>
    <li>python38Packages.envoy-reader</li>
    <li>python38Packages.fastapi</li>
    <li>python38Packages.ha-philipsjs</li>
    <li>python38Packages.ismartgate</li>
    <li>python38Packages.json-logging</li>
    <li>python38Packages.mautrix</li>
    <li>python38Packages.orm</li>
    <li>python38Packages.respx</li>
    <li>python38Packages.slack-sdk</li>
    <li>python38Packages.slowapi</li>
    <li>python38Packages.starlette</li>
    <li>python38Packages.telethon</li>
    <li>python39Packages.asyncpg</li>
    <li>python39Packages.databases</li>
    <li>python39Packages.dependency-injector</li>
    <li>python39Packages.envoy-reader</li>
    <li>python39Packages.fastapi</li>
    <li>python39Packages.ha-philipsjs</li>
    <li>python39Packages.ismartgate</li>
    <li>python39Packages.json-logging</li>
    <li>python39Packages.mautrix</li>
    <li>python39Packages.orm</li>
    <li>python39Packages.respx</li>
    <li>python39Packages.slack-sdk</li>
    <li>python39Packages.slowapi</li>
    <li>python39Packages.starlette</li>
    <li>python39Packages.telethon</li>
    <li>sourcehut.listssrht</li>
    <li>wapiti</li>
  </ul>
</details>

**Comment by fabaff** [comment]
> Is that mautrix bump unrelated?

Unfortunately is that bump needed.

**Review by expipiplus1 — APPROVED** [review]
lgtm as long as signal and telegram still work

**Pull request merged**
