### PR TITLE
perlPackages: batch update

### PR DESCRIPTION
**Pull request by volth**
update perlPackages

### CODE REVIEW

**Comment by volth** [comment]
I might be the time to run the bot again...

**Comment by FRidh** [comment]
Please resolve the conflicts.

**Comment by volth** [comment]
> Please resolve the conflicts.

It might be much easier to undo https://github.com/NixOS/nixpkgs/pull/78769 to solve the merge conflict than to rebase all this 100+ commits chain

**Comment by volth** [comment]
rebased and applied more updates, but not tested yet (still building)

**Comment by volth** [comment]
I think it is ok to merge without waiting, if 1-2 packages would fail, they will be fixed in ZHF rally.
The PR was tested 4 days ago, when it had 118 commits (now 131)

**Comment by Infinisil** [comment]
Merging sounds good, can I go for it or do you have some updates still in the pipeline?

**Comment by volth** [comment]
I don't

**Comment by Infinisil** [comment]
Awesome thanks, let's see how this does in staging :hot_pepper:

**Comment by FRidh** [comment]
A regression https://github.com/NixOS/nixpkgs/pull/79119#issuecomment-582325954

**Pull request merged**
