### PR TITLE
WIP: remove PIL as dependency

### PR DESCRIPTION
**Pull request by FRidh**
Replacing PIL by pillow. More commits to follow.

cc @domenkozar 

See #10938

### CODE REVIEW

**Comment by domenkozar** [comment]
@FRidh did you test those packages build and work?

**Comment by FRidh** [comment]
I tested whether they run, not any further.

**Comment by FRidh** [comment]
Somehow `nox-review` wants to rebuild more than seems necessary to me.
Anyway, it seems (correct me if I'm wrong!) that there are no packages left accidentally still depending on `pil`.

**Comment by domenkozar** [comment]
thank you :beers:

**Pull request merged**
