### PR TITLE
matrix-synapse: 1.36.0 -> 1.37.0

### PR DESCRIPTION
**Pull request by sumnerevans**
###### Motivation for this change

https://github.com/matrix-org/synapse/releases/tag/v1.37.0

###### Things done

I've deployed this on my homeserver and things seem to be fine.

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 128020` at 64a026d6 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>matrix-synapse</li>
    <li>matrix-synapse-plugins.matrix-synapse-mjolnir-antispam</li>
  </ul>
</details>

**Review by Ma27 — APPROVED** [review]

**Comment by sumnerevans** [comment]
Looks like we are going to have a pretty quick point release: https://github.com/matrix-org/synapse/releases/tag/v1.37.1rc1 due to issues arrising from: https://mobile.twitter.com/matrixdotorg/status/1409873992454967304

**Comment by Ma27** [comment]
Heh, good for me that I've disabled registration %) 
Let's not backport then, though and await 1.37.1.

**Comment by sumnerevans** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/128777.

**Pull request merged**
