### PR TITLE
vimPlugins: add package-info-nvim and SchemaStore-nvim

### PR DESCRIPTION
**Pull request by jlesquembre**
###### Motivation for this change
Add https://github.com/b0o/SchemaStore.nvim and https://github.com/vuki656/package-info.nvim

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
I wanted to use [b0o/SchemaStore.nvim](https://github.com/b0o/SchemaStore.nvim) but the README mentions 
```
lspconfig.jsonls.setup {
  settings = {
    json = {
      schemas = require('schemastore').json.schemas(),
      -- see https://github.com/b0o/SchemaStore.nvim/issues/8 for info about
      validate = { enable = true },
    },
  },
}
```
which triggers on startup:
```
Spawning language server with cmd: `vscode-json-language-server` failed. The language server is either not installed, missing from PATH, or not executable.
```
@jlesquembre I wonder how you leverage the plugin, do you have some nix expression to fetch vscode-json-language-server ?

**Comment by jlesquembre** [comment]
@teto I'm using nodePackages.vscode-langservers-extracted, here my nvim config:

https://github.com/jlesquembre/dotfiles/blob/cfc1ecffae23b40acbed952b6b59fcf2e4c7e54e/home-manager/neovim.nix#L172

**Comment by SuperSandro2000** [comment]
That should be patched in the vim plugin via the overrides file.

**Comment by teto** [comment]
ha thanks, I must have had an outdated nix-index, I tried nix-locate bin/vscode-json-language-server but could not find it. Seems to work now. Thanks !

**Pull request merged**
