### PR TITLE
TensorFlow ecosystem: `tensorflow` should never be in `propagatedBuildInputs`

### PR DESCRIPTION
**Pull request by samuela**
###### Motivation for this change
This is a followup to https://github.com/NixOS/nixpkgs/pull/156808 to provide the same benefits to the tensorflow package. The tl;dr is that including `tensorflow` in `propagatedBuildInputs` makes it extremely difficult for users wanting to use `tensorflowWithCuda`, effectively forcing them to use overlays. The solution is simple: never put `tensorflow` in `propagatedBuildInputs` and instead let users pick `tensorflow` or `tensorflowWithCuda` as they see fit.

I updated all of the offending, non-broken packages in nixpkgs. The following packages include `tensorflow` in their `propagatedBuildInputs` but are marked as broken, so they were left unchanged:
* https://cs.github.com/NixOS/nixpkgs/blob/54cbee8d9700668eaa51219f6c852b4019cfd2ba/pkgs/development/python-modules/rl-coach/default.nix?q=repo%3Anixos%2Fnixpkgs+tensorflow+language%3ANix#L34
* https://cs.github.com/NixOS/nixpkgs/blob/54cbee8d9700668eaa51219f6c852b4019cfd2ba/pkgs/development/python-modules/graph_nets/default.nix?q=repo%3Anixos%2Fnixpkgs+tensorflow+language%3ANix#L29 (graph_nets is not itself marked as broken but depends on dm-sonnet which is broken)

Assuming this PR is accepted, I'll update https://nixos.wiki/wiki/Tensorflow with a section noting that this is best practice for future packages depending on `tensorflow`.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
hmmm. I'm assuming that it would be better to do this at the package set level.

something like:
```
import <nixpkgs> { config.withCuda = true; };
```

And then just determine behavior that way cc @fridh

**Comment by samuela** [comment]
@jonringer IIUC the problem with that approach is that it requires users to (re-)build the ecosystem on their own machine since cache.nixos.org does not cache packages marked unfree (everything that CUDA touches in this case). Building `tensorflowWithCuda` takes 80 vCPU-hours on the m6a family of EC2 instances. So overlays and `config.withCuda = true` are hardly usable for many users like myself.

I'm open to any different set of ways of accomplishing this as long as it is easy enough for users. But OTOH if `{ config.withCuda = true; }` is the blessed way to accomplish this, why does `tensorflowWithCuda` exist?

**Comment by veprbl** [comment]
Not sure how changing leaf packages would allow you to speed up the build of `tensorflowWithCuda`.

**Comment by samuela** [comment]
Well my thinking is that `tensorflowWithCuda` could be cached somewhere for multiple users to use. I've been uploading builds of `jaxlibWithCuda` and `tensorflowWithCuda` to my public cachix bucket [ploop](https://app.cachix.org/cache/ploop#pull).

**Review by FRidh — CHANGES_REQUESTED** [review]
We need to be careful now. I understand why you're doing this, but in the end this goes for every package out there. We can't put all of them in `buildInputs` instead because that will break all runtime dependencies.

My understanding from your jaxlib library was that it was different there, but if it's the same here, then those changes should be reverted.

Essentially, what you're asking for is that packages don't retain runtime dependencies in the store paths, but that when you compose them with say `withPackages` you can still get them, but the versions you want. That would be ideal but we're not there.

**Comment by samuela** [comment]
Perhaps I should clarify why I feel these changes are prudent. I don't want to dismantle `propagatedBuildInputs` and runtime dependencies as a concept. They have a very important place in the ecosystem, esp. packaging Python libraries. My criteria for making this change in the tensorflow and JAX worlds is that we currently let users choose between two different possible runtimes at the package level, eg. users are presented with a choice between `tensorflow` and `tensorflowWithCuda`. As long as we give users this choice, I believe that the relevant packages should "just work" as intended. However, this is not currently the case. Eg, if you run `nix-shell -p python3Packages.tensorflowWithCuda python3Packages.mask-rcnn` you will be quite surprised to find that mask-rcnn is running on the CPU, not the GPU! That's exactly what happened in https://github.com/NixOS/nixpkgs/issues/156767.

So I don't mean to suggest that we should get rid of all runtime dependencies. Only that if we give users a choice between two different runtimes, we ought to respect that choice.

On a meta note, my goal here is to make GPU-enabled deep learning "just work" on NixOS; I'm not tied to any one solution. Furthermore, I believe that there should exist exactly one "blessed" way of accomplishing this. Right now it seems users can either use overlays/`config.withCuda` or select `tensorflowWithCuda`. I think we should have a conversation around which of these solutions is going to be the official way moving forward, and then build based on that decision.

**Comment by samuela** [comment]
closing as stale

**Pull request closed without merging**
