### PR TITLE
liblinphone: 4.4.35 -> 4.5.1

### PR DESCRIPTION
**Pull request by jluttine**
###### Motivation for this change

Update liblinphone and its dependencies. The updating of liblinphone and its dependencies must typically be synced so that all the packages are updated at the same time, otherwise it's very likely that some packages will fail to build.

I tested running `linphone` executable from `linphone` package. I didn't test all the small executables in all the dependencies.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jluttine** [comment]
Result of `nixpkgs-review pr 118297` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>bctoolbox</li>
    <li>belcard</li>
    <li>belle-sip</li>
    <li>belr</li>
    <li>bzrtp</li>
    <li>liblinphone</li>
    <li>lime</li>
    <li>linphone</li>
    <li>mediastreamer</li>
    <li>mediastreamer-openh264</li>
    <li>msilbc</li>
    <li>ortp</li>
    <li>trx</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 118297` at 1f8dc495 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>belle-sip</li>
    <li>liblinphone</li>
    <li>lime</li>
    <li>linphone</li>
  </ul>
</details>
<details>
  <summary>9 packages built successfully:</summary>
  <ul>
    <li>bctoolbox</li>
    <li>belcard</li>
    <li>belr</li>
    <li>bzrtp</li>
    <li>mediastreamer</li>
    <li>mediastreamer-openh264</li>
    <li>msilbc</li>
    <li>ortp</li>
    <li>trx</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl3` is a deprecated license, please check if project uses `gpl3Plus` or `gpl3Only` and change `meta.license` accordingly.

Near pkgs/development/libraries/mediastreamer/default.nix:105:5:
```
    |
105 |     license = licenses.gpl3;
    |     ^
```
</li>
    <li>warning: unused-argument

Unused argument: `fetchpatch`.
Near pkgs/development/libraries/mediastreamer/default.nix:7:3:
```
  |
7 | , fetchpatch
  |   ^
```
</li>
  </ul>
</details>

**Comment by risicle** [comment]
(All rebuilds marked as broken on darwin)

**Review by risicle — APPROVED** [review]
`nixpkgs-review` happy for me, linux x86_64

**Pull request merged**
