### PR TITLE
fix fetchFromGithub to work with revs that contain '/'

### PR DESCRIPTION
**Pull request by madjar**

### CODE REVIEW

**Comment by lethalman** [comment]
Not sure I would do this here. Many projects are already working as is, so I think it's better to handle the case project by project.

**Comment by edolstra** [comment]
Also note that `replaceChars` is a very slow function.

**Comment by madjar** [comment]
So, a tweaked fetchzip call in the project expression?

**Comment by edolstra** [comment]
Probably we should just make `name` overridable, e.g.
```
fetchFromGitHub = { owner, repo, rev, sha256, name ? "${repo}-${rev}-src"  }: fetchzip {
  inherit name;
 ...
```
That's similar to `fetchurl` which also sometimes needs an overriden `name`.

**Comment by madjar** [comment]
@edolstra I did just that in #5770

**Pull request closed without merging**
