### PR TITLE
rpcs3: 0.0.4-8032 -> 0.0.5-6980

### PR DESCRIPTION
**Pull request by ilian**
###### Motivation for this change
- Uses the [LLVM fork of rpcs3](https://github.com/RPCS3/llvm) instead of upstream LLVM.
- ~~Enable leaveDotGit to report correct version info (branch name and commit count). Let me know if this causes some problems (see #8567).~~
- Manually write version info to header file

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
cc @abbradar

**Comment by xeji** [comment]
@GrahamcOfBorg  build rpcs3

**Comment by xeji** [comment]
Build fails with hash mismatch.

**Comment by xeji** [comment]
@GrahamcOfBorg build rpcs3

**Comment by nocent** [comment]
Build fails since 2624f9079617df6b1fffda8c10f6a7a35068ecdc with
```
error: key does not contain a section: .url
```
The error does not occur when building on top of its parent commit 37aab4cbb5552bf021b20cf05d64e8ded6f3538a

**Comment by xeji** [comment]
Still doesn't build.

**Comment by nocent** [comment]
@xeji Yes, but it seems to be related to the update of the git package instead of the hash mismatch error when leaving leaveDotGit enabled.
The new git version might be breaking the `nix-prefetch-git` script.

**Comment by nocent** [comment]
The bash script seems to be failing at https://github.com/NixOS/nixpkgs/blob/bbe8321a29a2a091c955ff7be49e4d67de4bdf7e/pkgs/build-support/fetchgit/nix-prefetch-git#L192
The name and dir variable are set to empty strings, causing the script to execute 
`git config --get .url` which fails.

**Comment by xeji** [comment]
Maybe @dtzWill can have a look. I've seen the same error in another PR today (unfortunately don't remember which one).

**Comment by dtzWill** [comment]
I'd love to take a look, but can't tackle this right now.  Reverted the git update for now, hopefully this'll be addressed soon.  Sorry for the trouble! :)

(And thanks @xeji for identifying the issue and pinging me about it!)

**Comment by xeji** [comment]
@GrahamcOfBorg build rpcs3

**Pull request merged**
