### PR TITLE
haskell.packages: move platform specific overrides into own configuration files

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by maralorn** [comment]
Looks sensible at a first glance. I just hope that the extension plumbing code is really operationally equivalent …

**Comment by roberth** [comment]
> Looks sensible at a first glance. I just hope that the extension plumbing code is really operationally equivalent …

This can be tested by running something like `nix-instantiate --expr `(import ./. { system = /*...*/; }).haskellPackages`, before and after the change and checking for any differences in the reported list of drvs.

**Comment by roberth** [comment]
May be best to split the hash-changing changes into a separate PR? That way you can use ofborg results.

**Comment by sternenseemann** [comment]
> May be best to split the hash-changing changes into a separate PR? That way you can use ofborg results.

With the way the darwin  overrides were done I don't think it's entirely possible and it'd be a nasty rebase nevertheless. Not sure how aarch64 fits into the picture for ofborg, I've picked some of the commits onto the haskell-updates branch now.

**Pull request merged**
