### PR TITLE
graalvm-ce: 20.3.0 -> 21.0.0

### PR DESCRIPTION
**Pull request by thiagokokada**
###### Motivation for this change

Needed for PR #111864.

Will probably break `clj-kondo` ~~and `babashka`~~.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 112042` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>clj-kondo</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>babashka</li>
    <li>graalvm11-ce</li>
    <li>graalvm8-ce</li>
  </ul>
</details>

**Comment by thiagokokada** [comment]
CC @borkdude.

**Comment by thiagokokada** [comment]
BTW PR https://github.com/NixOS/nixpkgs/pull/111864 shows that we can build `leiningen` projects from source using a small hack: https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/maven.section.md#double-invocation. Maybe building everything from source is the answer for making it easier to do those GraalVM bumps, but AFAIK we still need to provide stubs for older/newer versions of GraalVM.

**Comment by borkdude** [comment]
I think clj-kondo and babashka work with 21.0.0 and from then on upgrading GraalVM shouldn't be so painful anymore, hopefully. The problem I'm currently still inspecting with 21.0.0 is the slightly larger image size, but I'm planning to upgrade within the next couple of weeks.

**Comment by thiagokokada** [comment]
No problem @borkdude, we can wait.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 112042` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>clj-kondo: log <a href="https://termbin.com/4vrw">https://termbin.com/4vrw</a></li>
  </ul>
</details>
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>babashka</li>
<li>graalvm11-ce</li>
<li>graalvm8-ce</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 112042` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>clj-kondo: log <a href="https://termbin.com/xhw8">https://termbin.com/xhw8</a></li>
  </ul>
</details>
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>babashka</li>
<li>graalvm11-ce</li>
<li>graalvm8-ce</li>
</ul>
</details>

**Comment by taku0** [comment]
`irb` on Linux not working.

```
$ ./graalvm11-ce/bin/irb
<internal:core> core/kernel.rb:234:in `gem_original_require': libtruffleruby.so: cannot open shared object file: No such file or directory (RuntimeError)
        from /nix/store/z9c6fpm77sf5i742x2wxdczaynr16n2f-graalvm11-ce-21.0.0/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /nix/store/z9c6fpm77sf5i742x2wxdczaynr16n2f-graalvm11-ce-21.0.0/languages/ruby/lib/mri/ripper/core.rb:12:in `<top (required)>'
        from <internal:core> core/kernel.rb:234:in `gem_original_require'
        from /nix/store/z9c6fpm77sf5i742x2wxdczaynr16n2f-graalvm11-ce-21.0.0/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /nix/store/z9c6fpm77sf5i742x2wxdczaynr16n2f-graalvm11-ce-21.0.0/languages/ruby/lib/mri/ripper.rb:2:in `<top (required)>'
        from <internal:core> core/kernel.rb:234:in `gem_original_require'
        from /nix/store/z9c6fpm77sf5i742x2wxdczaynr16n2f-graalvm11-ce-21.0.0/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /nix/store/z9c6fpm77sf5i742x2wxdczaynr16n2f-graalvm11-ce-21.0.0/languages/ruby/lib/mri/irb.rb:12:in `<top (required)>'
        from <internal:core> core/kernel.rb:234:in `gem_original_require'
        from /nix/store/z9c6fpm77sf5i742x2wxdczaynr16n2f-graalvm11-ce-21.0.0/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /nix/store/z9c6fpm77sf5i742x2wxdczaynr16n2f-graalvm11-ce-21.0.0/languages/ruby/lib/gems/gems/irb-1.2.6/exe/irb:9:in `<top (required)>'
        from <internal:core> core/kernel.rb:400:in `load'
        from <internal:core> core/kernel.rb:400:in `load'
        from /nix/store/z9c6fpm77sf5i742x2wxdczaynr16n2f-graalvm11-ce-21.0.0/languages/ruby/bin/irb:42:in `<main>'
```

**Comment by taku0** [comment]
`graalvm8-ce` and `graalvm11-ce` work on macOS.

`babashka` is built successfully on macOS, though not tested.

Building `clj-kondo` fails with the following error:

```
Fatal error:com.oracle.svm.core.util.VMError$HostedError: Option name "HotSpotPostOnExceptions" has multiple definitions: org.graalvm.compiler.hotspot.meta.HotSpotExceptionDispatchPlugin$Options.HotSpotPostOnExceptions and org.graalvm.compiler.hotspot.meta.HotSpotNodePlugin$Options.HotSpotPostOnExceptions
        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
        at com.oracle.svm.hosted.option.HostedOptionParser.collectOptions(HostedOptionParser.java:89)
        at com.oracle.svm.hosted.option.HostedOptionParser.<init>(HostedOptionParser.java:62)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:258)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:529)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:561)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1676)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1426)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1387)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1374)
        at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1858)
```

**Comment by borkdude** [comment]
@taku0 I know what the issue is there: the uberjar depends on 20.3.0 specific classes. It will be fixed once clj-kondo itself upgrades to 21.

**Comment by thiagokokada** [comment]
> `irb` on Linux not working.
> 
> ```
> $ ./graalvm11-ce/bin/irb
> <internal:core> core/kernel.rb:234:in `gem_original_require': libtruffleruby.so: cannot open shared object file: No such file or directory (RuntimeError)
>         from /nix/store/z9c6fpm77sf5i742x2wxdczaynr16n2f-graalvm11-ce-21.0.0/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:92:in `require'
>         from /nix/store/z9c6fpm77sf5i742x2wxdczaynr16n2f-graalvm11-ce-21.0.0/languages/ruby/lib/mri/ripper/core.rb:12:in `<top (required)>'
>         from <internal:core> core/kernel.rb:234:in `gem_original_require'
>         from /nix/store/z9c6fpm77sf5i742x2wxdczaynr16n2f-graalvm11-ce-21.0.0/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:92:in `require'
>         from /nix/store/z9c6fpm77sf5i742x2wxdczaynr16n2f-graalvm11-ce-21.0.0/languages/ruby/lib/mri/ripper.rb:2:in `<top (required)>'
>         from <internal:core> core/kernel.rb:234:in `gem_original_require'
>         from /nix/store/z9c6fpm77sf5i742x2wxdczaynr16n2f-graalvm11-ce-21.0.0/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:92:in `require'
>         from /nix/store/z9c6fpm77sf5i742x2wxdczaynr16n2f-graalvm11-ce-21.0.0/languages/ruby/lib/mri/irb.rb:12:in `<top (required)>'
>         from <internal:core> core/kernel.rb:234:in `gem_original_require'
>         from /nix/store/z9c6fpm77sf5i742x2wxdczaynr16n2f-graalvm11-ce-21.0.0/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:92:in `require'
>         from /nix/store/z9c6fpm77sf5i742x2wxdczaynr16n2f-graalvm11-ce-21.0.0/languages/ruby/lib/gems/gems/irb-1.2.6/exe/irb:9:in `<top (required)>'
>         from <internal:core> core/kernel.rb:400:in `load'
>         from <internal:core> core/kernel.rb:400:in `load'
>         from /nix/store/z9c6fpm77sf5i742x2wxdczaynr16n2f-graalvm11-ce-21.0.0/languages/ruby/bin/irb:42:in `<main>'
> ```

Fixed.

**Comment by thiagokokada** [comment]
> `graalvm8-ce` and `graalvm11-ce` work on macOS.
> 
> `babashka` is built successfully on macOS, though not tested.
> 
> Building `clj-kondo` fails with the following error:
> 
> ```
> Fatal error:com.oracle.svm.core.util.VMError$HostedError: Option name "HotSpotPostOnExceptions" has multiple definitions: org.graalvm.compiler.hotspot.meta.HotSpotExceptionDispatchPlugin$Options.HotSpotPostOnExceptions and org.graalvm.compiler.hotspot.meta.HotSpotNodePlugin$Options.HotSpotPostOnExceptions
>         at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
>         at com.oracle.svm.hosted.option.HostedOptionParser.collectOptions(HostedOptionParser.java:89)
>         at com.oracle.svm.hosted.option.HostedOptionParser.<init>(HostedOptionParser.java:62)
>         at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:258)
>         at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:529)
>         at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
>         at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:561)
> Error: Image build request failed with exit status 1
> com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
>         at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1676)
>         at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1426)
>         at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1387)
>         at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1374)
>         at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1858)
> ```

I think I will add a basic babashka test, so we can make sure it works.

**Comment by thiagokokada** [comment]
@GrahamcOfBorg build babashka clj-kondo graalvm8-ce graalvm11-ce

**Comment by borkdude** [comment]
FWIW babashka proper is now upgraded to GraalVM 21.0.0. Clj-kondo will soon follow.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 112042` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>clj-kondo: log <a href="https://termbin.com/sq3c">https://termbin.com/sq3c</a></li>
  </ul>
</details>
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>babashka</li>
<li>graalvm11-ce</li>
<li>graalvm8-ce</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 112042` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>clj-kondo: log <a href="https://termbin.com/u7v4">https://termbin.com/u7v4</a></li>
  </ul>
</details>
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>babashka</li>
<li>graalvm11-ce</li>
<li>graalvm8-ce</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 112042` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>clj-kondo: log <a href="https://termbin.com/gyqr">https://termbin.com/gyqr</a></li>
  </ul>
</details>
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>babashka</li>
<li>graalvm11-ce</li>
<li>graalvm8-ce</li>
</ul>
</details>

**Comment by borkdude** [comment]
Both clj-kondo and babashka are now based on GraalVM 21.0.0 Java 11.

**Comment by thiagokokada** [comment]
@borkdude Yeah, I saw on Twitter. Thanks for the great work!

**Comment by thiagokokada** [comment]
@GrahamcOfBorg build babashka clj-kondo graalvm8-ce graalvm11-ce

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 112042` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
4 packages built:
</summary>
<ul>
<li>babashka</li>
<li>clj-kondo</li>
<li>graalvm11-ce</li>
<li>graalvm8-ce</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

babashka:
<details>


`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/development/interpreters/clojure/babashka.nix:24:3:

```
   |
24 |   buildPhase = ''
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md
`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/interpreters/clojure/babashka.nix:48:3:

```
   |
48 |   installPhase = ''
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md
</details>
clj-kondo:
<details>


`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/development/tools/clj-kondo/default.nix:22:3:

```
   |
22 |   buildPhase = ''
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md
`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/tools/clj-kondo/default.nix:40:3:

```
   |
40 |   installPhase = ''
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md
</details>
graalvm11-ce:
<details>


`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/compilers/graalvm/community-edition.nix:102:9:

```
    |
102 |         installPhase = {
    |         ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md
</details>
graalvm8-ce:
<details>


`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/compilers/graalvm/community-edition.nix:102:9:

```
    |
102 |         installPhase = {
    |         ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 112042` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
4 packages built:
</summary>
<ul>
<li>babashka</li>
<li>clj-kondo</li>
<li>graalvm11-ce</li>
<li>graalvm8-ce</li>
</ul>
</details>

**Comment by thiagokokada** [comment]
@SuperSandro2000 Can we have this PR merged?

**Pull request merged**
