### PR TITLE
Clean calibre packaging

### PR DESCRIPTION
**Pull request by wrvsrx**
## Description of changes

1. This PR remove `removeReferencesTo` since it makes no difference for calibre now, you can check it using `nix path-info -S .#calibre`.
1. This PR avoid wrapping `PYTHONPATH` into program, instead I use `python.withPackages` and let fixupPhase replace `!/usr/bin/env python` to the wrapped python automatically.

   I'll open another PR to build calibre from git source after 7.13 is released. This change ensure `sphinx` won't be regarded as a runtime dependency due to `PYTHONPATH`.

1. This PR add two args (`popplerSupport` and `speechSupport`) for users to override.

   In arch linux repo, `poppler_utils` and `speechd` are optional dependencies, so I add these options. Another reason is that [someone wants the option](https://github.com/NixOS/nixpkgs/pull/289684#issuecomment-1962919157).

1. Format the code using `nixfmt-rfc-style`

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by wrvsrx** [comment]
cc the maintainer: @pSub

**Comment by wrvsrx** [comment]
Byt the way, I was wondering why we wrap calibre with `gappsWrapperArgs` while calibre is a qt app.

**Comment by Aleksanaa** [comment]
Please split formatting to another commit.

> This PR avoid wrapping PYTHONPATH into program, instead I use python.withPackages and let fixupPhase replace !/usr/bin/env python to the wrapped python automatically.

Just to make sure, it doesn't use python from somewhere else right?

**Comment by wrvsrx** [comment]
> Please split formatting to another commit.

Done.

> > This PR avoid wrapping PYTHONPATH into program, instead I use python.withPackages and let fixupPhase replace !/usr/bin/env python to the wrapped python automatically.
> 
> Just to make sure, it doesn't use python from somewhere else right?

As far as I test, all functions of calibre I use works well after this change.

@Aleksanaa

**Comment by MaxwellDupre** [comment]
Your PR will be more likely to be merged if you squash commits.

**Comment by Aleksanaa** [comment]
> Your PR will be more likely to be merged if you squash commits.

No need to, they are changes regarding different aspects.

**Review by Aleksanaa — APPROVED** [review]

**Pull request merged**
