### PR TITLE
libclang-py3: init at 0.3

### PR DESCRIPTION
**Pull request by expipiplus1**

### CODE REVIEW

**Comment by copumpkin** [comment]
How does this work with no `clang` in the `buildInputs`?

**Comment by joachifm** [comment]
@expipiplus1 still working on this?

**Comment by expipiplus1** [comment]
@joachifm I'd quite forgotten about it actually. Feel free to take over if you're using it.

**Comment by joachifm** [comment]
@expipiplus1 actually I was looking for PRs to prune :)

**Comment by expipiplus1** [comment]
If just adding `clang` to `buildInputs` can get this merged then I'd like to do that. Otherwise I'm happy for this to be closed.

**Comment by joachifm** [comment]
@expipiplus1 as long as it works. I too am a little dubious how the binding could work if not built against the thing it's supposed to bind.

**Comment by expipiplus1** [comment]
@joachifm I'm going to close this now. If I have cause to use libclang-py3 again I'll reopen this with some testing.

**Pull request closed without merging**
