### PR TITLE
apko: 0.4.0 -> 0.8.0

### PR DESCRIPTION
**Pull request by developer-guy**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by 06kellyjac — APPROVED** [review]

**Comment by bobby285271** [comment]
apk_unit_test.go is removed so the package does not build (ofborg shows failing failing builds as `neutral` and you probably want to look into it)

```
substitute(): ERROR: file 'pkg/apk/apk_unit_test.go' does not exist
```

https://github.com/NixOS/nixpkgs/blob/317c54005587d35c738766d881d645f4b4b7d540/pkgs/development/tools/apko/default.nix#L44-L48

**Comment by developer-guy** [comment]
Let me quickly fix this, thanks ☝️

**Comment by developer-guy** [comment]
can you please review it again @bobby285271? ☝️

**Comment by bobby285271** [comment]
[Still fails to build on linux](https://github.com/NixOS/nixpkgs/pull/228007/checks?check_run_id=13356391351). Sounds like some tests require network and should be disabled.

**Comment by developer-guy** [comment]
kindly ping @bobby285271

**Comment by bobby285271** [comment]
When you see this the build fails:



We don't run tests in `preInstallCheck` so dropping that line won't work. I don't write go but I imagine you can search `_test.go` in Nixpkgs for examples on how we skip specific tests.

**Comment by bobby285271** [comment]
Let's try :see_no_evil: 

@ofborg build apko

Some nits: I personally prefer putting `preCheck` above `postInstall` since it is executed in that order, and we probably want to restore the `runHook preInstallCheck` line

**Comment by developer-guy** [comment]
thanks for all the great suggestions @bobby285271!

**Comment by bobby285271** [comment]
Reading the diff again and sounds like story here is not that complex - the `TestInitKeyring` test moved from [`pkg/apk/apk_unit_test.go`](https://github.com/chainguard-dev/apko/blob/v0.4.0/pkg/apk/apk_unit_test.go#L70) to [`pkg/apk/impl/implementation_test.go`](https://github.com/chainguard-dev/apko/blob/v0.8.0/pkg/apk/impl/implementation_test.go#L119), that's all :joy:  

But `pkg/apk/impl/implementation_test.go` [is gone in latest main](https://github.com/chainguard-dev/apko/commit/1f58b65f4778ec06145a88070cf2494ff102041d), I decide I will not be nitpick here, on the next bump hopefully we should be able to drop the `preCheck` again, let's see.

Btw doCheck defaults to true in `buildGoModule` so it's probably okay not to explicitly set that.

**Comment by 06kellyjac** [comment]
When there are additional changes after an approval I'd appreciate some time to review...

**Comment by bobby285271** [comment]
Sorry, did you notice any issues? I can response quick in the next few hours

**Comment by 06kellyjac** [comment]
Well `doChecks` is unnecessary as you mentioned after merging :sweat_smile:

A couple other small changes & typically I'm made to squash my update into 1 PR

**Pull request merged**
