### PR TITLE
Seafile 10

### LINKED ISSUE #272025: Seahub doesn't start on NixOS 23.11
### Describe the bug
I upgraded to NixOS 23.11 from 23.05 and I didn't touch seafile configuration files. Now Seahub doesn't start anymore.

### Steps To Reproduce
1. Upgrade to NixOS 23.11
2. seahub fails
3. `sudo systemctl restart seahub.service`
4. `systemctl --failed`

### Expected behavior
Seahub should start normally, the same as NixOS 23.05.

### Log
```console
Starting Seafile Server Web Frontend...
Started Seafile Server Web Frontend.
Traceback (most recent call last):
  File "/nix/store/qqc3d7lkc7xx5mz1jkpsm09n8ajm10j9-python3.11-gunicorn-21.2.0/bin/.gunicorn-wrapped", line 9, in <module>
    sys.exit(run())
             ^^^^^
  File "/nix/store/qqc3d7lkc7xx5mz1jkpsm09n8ajm10j9-python3.11-gunicorn-21.2.0/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/nix/store/qqc3d7lkc7xx5mz1jkpsm09n8ajm10j9-python3.11-gunicorn-21.2.0/lib/python3.11/site-packages/gunicorn/app/base.py", line 236, in run
    super().run()
  File "/nix/store/qqc3d7lkc7xx5mz1jkpsm09n8ajm10j9-python3.11-gunicorn-21.2.0/lib/python3.11/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
    ^^^^^^^^^^^^^
  File "/nix/store/qqc3d7lkc7xx5mz1jkpsm09n8ajm10j9-python3.11-gunicorn-21.2.0/lib/python3.11/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/nix/store/qqc3d7lkc7xx5mz1jkpsm09n8ajm10j9-python3.11-gunicorn-21.2.0/lib/python3.11/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/nix/store/qqc3d7lkc7xx5mz1jkpsm09n8ajm10j9-python3.11-gunicorn-21.2.0/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/nix/store/qqc3d7lkc7xx5mz1jkpsm09n8ajm10j9-python3.11-gunicorn-21.2.0/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qqc3d7lkc7xx5mz1jkpsm09n8ajm10j9-python3.11-gunicorn-21.2.0/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qqc3d7lkc7xx5mz1jkpsm09n8ajm10j9-python3.11-gunicorn-21.2.0/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/7yz0pmbxldv4sdm7gb8vxazyc0af0xh5-seahub-9.0.10/seahub/__init__.py", line 2, in <module>
    from .signals import repo_created, repo_deleted, clean_up_repo_trash, \
  File "/nix/store/7yz0pmbxldv4sdm7gb8vxazyc0af0xh5-seahub-9.0.10/seahub/signals.py", line 5, in <module>
    repo_created = django.dispatch.Signal(providing_args=["org_id", "creator", "repo_id", "repo_name", "library_template"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Signal.__init__() got an unexpected keyword argument 'providing_args'
seahub.service: Main process exited, code=exited, status=1/FAILURE
seahub.service: Failed with result 'exit-code'.
```

### Notify maintainers

@greizgh @schmittlauch

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.61-hardened1, NixOS, 23.11 (Tapir), 23.11.1250.f8a9aa9ca646`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11-small, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by greizgh**
## Description of changes

Update to latest stable seafile version (major update 9 -> 10). This come with a small change of the module to execute migration.

Fixes https://github.com/NixOS/nixpkgs/issues/272025

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mohe2015** [comment]
Doesn't this also fail with the `TypeError: Signal.__init__() got an unexpected keyword argument 'providing_args'` error? I don't know how useful this change is on it's own as long as either that issue is not fixed or it is updated to the (currently unreleased seafile 11)

**Comment by fin444** [comment]
An easy fix for this is to overlay `django` to `django_3`. I would assume overlaying it only in Seafile's dependencies would work, but I'm not sure how it would play with other Django-related dependencies and I haven't tried it.

**Comment by greizgh** [comment]
Thanks for the heads up, this branch has been rebased and tests are now passing again.

**Comment by quinn-dougherty** [comment]
> Doesn't this also fail with the `TypeError: Signal.__init__() got an unexpected keyword argument 'providing_args'` error?

What do we know about this? is it just a django 2 vs 3 thing? I'm getting it on seafile 9 right now, currently building with an overlay to this branch.

**Comment by greizgh** [comment]
> > Doesn't this also fail with the `TypeError: Signal.__init__() got an unexpected keyword argument 'providing_args'` error?
> 
> What do we know about this? it seems like it's [django 3 vs 4 and a dependency called django-allauth](https://stackoverflow.com/questions/70466886/typeerror-init-got-an-unexpected-keyword-argument-providing-args)

Yes, seafile 10 does not support django 4. That should have been fixed with the latest rebase (at least I cannot reproduce from the branch).
Make sure you pull the latest reference (a312393f1432d5b39a7215ef8d847c13c007ede3), you might have cache somewhere.

**Comment by quinn-dougherty** [comment]
> Make sure you pull the latest reference (https://github.com/NixOS/nixpkgs/commit/a312393f1432d5b39a7215ef8d847c13c007ede3), you might have cache somewhere.

The flake was locked just a few minutes before I sent that message. Everything about my infra is flakes, I don't know how something cached would interfere. 

It turned out that maybe my overlay code was bad, so instead I just passed your fork's flake input into the module and used `seafilePackage = inputs.nixpkgs-seafile.legacyPackages.${system}.seafile-server`. (`ls /nix/store | grep -E "sea(file|hub)"` confirms a v10 of the server was built). I have graduated to a new error, presumably because `seahub` is still a v9. 

```
admin@a-guy-for-a-thing ~> systemctl status seaf-server.service
× seaf-server.service - Seafile server
     Loaded: loaded (/etc/systemd/system/seaf-server.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Mon 2023-11-27 12:37:03 PST; 3min 41s ago
   Duration: 3h 27min 15.654s
    Process: 564015 ExecStartPre=/nix/store/yzs2zbhvyjfi3y6khv0l5x9wc4w69lbr-unit-script-seaf-server-pre-start/bin/seaf-server-pre-start (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
        CPU: 28ms

Nov 27 12:37:03 a-guy-for-a-thing systemd[1]: Starting Seafile server...
Nov 27 12:37:03 a-guy-for-a-thing seaf-server-pre-start[564015]: Unsupported upgrade
Nov 27 12:37:03 a-guy-for-a-thing systemd[1]: seaf-server.service: Control process exited, code=exited, status=1/FAILURE
Nov 27 12:37:03 a-guy-for-a-thing systemd[1]: seaf-server.service: Failed with result 'exit-code'.
Nov 27 12:37:03 a-guy-for-a-thing systemd[1]: Failed to start Seafile server.
```

**Comment by Elinvention** [comment]
I attempted to test this pr, but I just got some errors. I added this to my config:
```nix
let                                                                                                                                                                                                                 
  pkgsReview = builtins.fetchTarball {                                                                                                                                                                              
    url = "https://github.com/greizgh/nixpkgs/archive/seafile-10.tar.gz";                                                                                                                                           
  };                                                                                                                                                                                                                
in                                                                                                                                                                                                                  
{
  disabledModules = [ "services/networking/seafile.nix" ];                                                                                                                                                          
                                                                                                                                                                                                                    
  imports = [                                                                                                                                                                                                       
    (import "${pkgsReview}/nixos/modules/services/networking/seafile.nix")                                                                                                                                          
  ];                                                                                                                                                                                                                
                                                                                                                                                                                                                    
  nixpkgs.overlays = [                                                                                                                                                                                              
    (self: super: {                                                                                                                                                                                                 
      inherit (pkgsReview) seafile;                                                                                                                                                                                 
      inherit (pkgsReview) seahub;                                                                                                                                                                                  
    })                                                                                                                                                                                                              
  ];

...
```

And I got this error:
```console
 ~> sudo nixos-rebuild switch --show-trace
building Nix...
building the system configuration...
error:
       … while calling anonymous lambda

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/attrsets.nix:918:24:

          917|     let f = attrPath:
          918|       zipAttrsWith (n: values:
             |                        ^
          919|         let here = attrPath ++ [n]; in

       … while calling 'g'

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/attrsets.nix:701:19:

          700|           g =
          701|             name: value:
             |                   ^
          702|             if isAttrs value && cond value

       … from call site

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/attrsets.nix:704:20:

          703|               then recurse (path ++ [name]) value
          704|               else f (path ++ [name]) value;
             |                    ^
          705|         in mapAttrs g;

       … while calling anonymous lambda

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/modules.nix:242:72:

          241|           # For definitions that have an associated option
          242|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          243|

       … while evaluating the option `system.build.toplevel':

       … while calling anonymous lambda

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/modules.nix:822:28:

          821|         # Process mkMerge and mkIf properties.
          822|         defs' = concatMap (m:
             |                            ^
          823|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating definitions from `/nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/nixos/modules/system/activation/top-level.nix':

       … from call site

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/modules.nix:823:137:

          822|         defs' = concatMap (m:
          823|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          824|         ) defs;

       … while calling 'dischargeProperties'

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/modules.nix:894:25:

          893|   */
          894|   dischargeProperties = def:
             |                         ^
          895|     if def._type or "" == "merge" then

       … from call site

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/nixos/modules/system/activation/top-level.nix:71:12:

           70|   # Replace runtime dependencies
           71|   system = foldr ({ oldDependency, newDependency }: drv:
             |            ^
           72|       pkgs.replaceDependency { inherit oldDependency newDependency drv; }

       … while calling 'foldr'

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/lists.nix:53:20:

           52|   */
           53|   foldr = op: nul: list:
             |                    ^
           54|     let

       … from call site

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/lists.nix:60:8:

           59|         else op (elemAt list n) (fold' (n + 1));
           60|     in fold' 0;
             |        ^
           61|

       … while calling 'fold''

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/lists.nix:56:15:

           55|       len = length list;
           56|       fold' = n:
             |               ^
           57|         if n == len

       … from call site

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/nixos/modules/system/activation/top-level.nix:68:10:

           67|     then throw "\nFailed assertions:\n${concatStringsSep "\n" (map (x: "- ${x}") failedAssertions)}"
           68|     else showWarnings config.warnings baseSystem;
             |          ^
           69|

       … while calling 'showWarnings'

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/trivial.nix:414:28:

          413|
          414|   showWarnings = warnings: res: lib.foldr (w: x: warn w x) res warnings;
             |                            ^
          415|

       … from call site

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/trivial.nix:414:33:

          413|
          414|   showWarnings = warnings: res: lib.foldr (w: x: warn w x) res warnings;
             |                                 ^
          415|

       … while calling 'foldr'

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/lists.nix:53:20:

           52|   */
           53|   foldr = op: nul: list:
             |                    ^
           54|     let

       … from call site

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/lists.nix:60:8:

           59|         else op (elemAt list n) (fold' (n + 1));
           60|     in fold' 0;
             |        ^
           61|

       … while calling 'fold''

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/lists.nix:56:15:

           55|       len = length list;
           56|       fold' = n:
             |               ^
           57|         if n == len

       … while calling 'g'

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/attrsets.nix:701:19:

          700|           g =
          701|             name: value:
             |                   ^
          702|             if isAttrs value && cond value

       … from call site

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/attrsets.nix:704:20:

          703|               then recurse (path ++ [name]) value
          704|               else f (path ++ [name]) value;
             |                    ^
          705|         in mapAttrs g;

       … while calling anonymous lambda

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/modules.nix:242:72:

          241|           # For definitions that have an associated option
          242|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          243|

       … while evaluating the option `warnings':

       … while calling anonymous lambda

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/modules.nix:822:28:

          821|         # Process mkMerge and mkIf properties.
          822|         defs' = concatMap (m:
             |                            ^
          823|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating definitions from `/nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/nixos/modules/system/boot/systemd.nix':

       … from call site

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/modules.nix:823:137:

          822|         defs' = concatMap (m:
          823|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          824|         ) defs;

       … while calling 'dischargeProperties'

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/modules.nix:894:25:

          893|   */
          894|   dischargeProperties = def:
             |                         ^
          895|     if def._type or "" == "merge" then

       … while calling anonymous lambda

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/attrsets.nix:615:10:

          614|     attrs:
          615|     map (name: f name attrs.${name}) (attrNames attrs);
             |          ^
          616|

       … from call site

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/attrsets.nix:615:16:

          614|     attrs:
          615|     map (name: f name attrs.${name}) (attrNames attrs);
             |                ^
          616|

       … while calling anonymous lambda

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/nixos/modules/system/boot/systemd.nix:425:16:

          424|       mapAttrsToList
          425|         (name: service:
             |                ^
          426|           let

       … from call site

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/nixos/modules/system/boot/systemd.nix:432:16:

          431|             concatLists [
          432|               (optional (type == "oneshot" && (restart == "always" || restart == "on-success"))
             |                ^
          433|                 "Service '${name}.service' with 'Type=oneshot' cannot have 'Restart=always' or 'Restart=on-success'"

       … while calling 'optional'

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/lists.nix:359:20:

          358|   */
          359|   optional = cond: elem: if cond then [elem] else [];
             |                    ^
          360|

       … while calling 'g'

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/attrsets.nix:701:19:

          700|           g =
          701|             name: value:
             |                   ^
          702|             if isAttrs value && cond value

       … from call site

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/attrsets.nix:704:20:

          703|               then recurse (path ++ [name]) value
          704|               else f (path ++ [name]) value;
             |                    ^
          705|         in mapAttrs g;

       … while calling anonymous lambda

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/modules.nix:242:72:

          241|           # For definitions that have an associated option
          242|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          243|

       … while evaluating the option `systemd.services.seaf-server.serviceConfig':

       … while calling anonymous lambda

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/modules.nix:822:28:

          821|         # Process mkMerge and mkIf properties.
          822|         defs' = concatMap (m:
             |                            ^
          823|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating definitions from `/nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/nixos/modules/system/boot/systemd.nix':

       … from call site

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/modules.nix:823:137:

          822|         defs' = concatMap (m:
          823|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          824|         ) defs;

       … while calling 'dischargeProperties'

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/modules.nix:894:25:

          893|   */
          894|   dischargeProperties = def:
             |                         ^
          895|     if def._type or "" == "merge" then

       … while calling 'g'

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/attrsets.nix:701:19:

          700|           g =
          701|             name: value:
             |                   ^
          702|             if isAttrs value && cond value

       … from call site

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/attrsets.nix:704:20:

          703|               then recurse (path ++ [name]) value
          704|               else f (path ++ [name]) value;
             |                    ^
          705|         in mapAttrs g;

       … while calling anonymous lambda

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/modules.nix:242:72:

          241|           # For definitions that have an associated option
          242|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          243|

       … while evaluating the option `systemd.services.seaf-server.preStart':

       … while calling anonymous lambda

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/modules.nix:822:28:

          821|         # Process mkMerge and mkIf properties.
          822|         defs' = concatMap (m:
             |                            ^
          823|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating definitions from `/etc/nixos/seafile.nix':

       … from call site

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/modules.nix:823:137:

          822|         defs' = concatMap (m:
          823|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          824|         ) defs;

       … while calling 'dischargeProperties'

         at /nix/store/dpf82iyyzzrbqgxa9ky86kxig8km8xii-nixos-23.11-small/nixos/lib/modules.nix:894:25:

          893|   */
          894|   dischargeProperties = def:
             |                         ^
          895|     if def._type or "" == "merge" then

       error: value is a string with context while a set was expected
```

**Comment by greizgh** [comment]
> I attempted to test this pr, but I just got some errors. I added this to my config:

This is probably related to your overlay definition. Please move this discussion to the forum, let's keep this thread focused on the PR itself.

<details>
<summary>FYI here is the module I use (flake based):</summary>

```nix
              ({
                disabledModules = [ "services/networking/seafile.nix" ];
                imports = [
                  "${seafpkgs}/nixos/modules/services/networking/seafile.nix"
                ];
                config = {
                  nixpkgs.overlays = [
                    (final: prev: {
                      seafile-server = seafpkgs.legacyPackages.${system}.seafile-server;
                      seahub = seafpkgs.legacyPackages.${system}.seahub;
                    })
                  ];
                };
              })
```
</details>

**Comment by Elinvention** [comment]
Thanks, I was able to fix my issue and I am successfully running seafile again with this pr.
It was indeed my overlay definition. I changed it like this:

```nix
  nixpkgs.overlays = [
    (self: super: {
      inherit (import pkgsReview {}) seafile-server seahub;
    })
  ];
```

**Review by MaxwellDupre — APPROVED** [review]
LGTM. I know some dont like to merge a PR with more than one commit.

**Comment by pbsds** [comment]
Last eval is from november

@ofborg eval

**Comment by pbsds** [comment]
Please look at the build issues

**Comment by greizgh** [comment]
I cannot reproduce the eval error locally.

@ofborg eval

**Comment by pbsds** [comment]
aarch64 build failed, but could have been unrelated

@ofborg build seafile-server seafile-server.passthru.tests seahub seahub.passthru.tests

**Pull request merged**
