### PR TITLE
vlc: 3.0.11.1 -> 3.0.12

### PR DESCRIPTION
**Pull request by tu-maurice**
###### Motivation for this change

Security issue https://www.videolan.org/security/sb-vlc3012.html

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110379` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages marked as broken and skipped:
</summary>
<ul>
<li>libsForQt512.elisa</li>
<li>libsForQt514.elisa</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>obs-ndi: log was empty</li>
  </ul>
</details>
<details>
<summary>
18 packages built:
</summary>
<ul>
<li>libsForQt5.elisa (libsForQt515.elisa ,plasma5Packages.elisa)</li>
<li>libsForQt5.phonon-backend-vlc (libsForQt515.phonon-backend-vlc ,plasma5Packages.phonon-backend-vlc)</li>
<li>libsForQt512.phonon-backend-vlc</li>
<li>libsForQt514.phonon-backend-vlc</li>
<li>libvlc</li>
<li>megaglest</li>
<li>minitube</li>
<li>obs-move-transition</li>
<li>obs-studio</li>
<li>obs-v4l2sink</li>
<li>obs-wlrobs</li>
<li>pympress</li>
<li>python37Packages.python-vlc</li>
<li>python38Packages.python-vlc</li>
<li>python39Packages.python-vlc</li>
<li>strawberry</li>
<li>tribler</li>
<li>vlc (vlc_qt5)</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

libvlc:
<details>

Please consider this feature to be alpha.

A substituteInPlace with an unmatched pattern got detected:
```
substituteStream(): WARNING: pattern '/bin/echo' doesn't match anything in file 'configure'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>
vlc:
<details>

Please consider this feature to be alpha.

A substituteInPlace with an unmatched pattern got detected:
```
substituteStream(): WARNING: pattern '/bin/echo' doesn't match anything in file 'configure'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>

**Comment by tu-maurice** [comment]
@SuperSandro2000 I removed the offending substituteInPlace. I presume obs-ndi did not build for you due to it being unfree or maybe because it requires a manual download of sources?

**Comment by SuperSandro2000** [comment]
> I presume obs-ndi did not build for you because a dependency is unfree and/or requires a manual download of sources?

It requires a manual download.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110379` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages marked as broken and skipped:
</summary>
<ul>
<li>libsForQt512.elisa</li>
<li>libsForQt514.elisa</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>obs-ndi: log was empty</li>
  </ul>
</details>
<details>
<summary>
18 packages built:
</summary>
<ul>
<li>libsForQt5.elisa (libsForQt515.elisa ,plasma5Packages.elisa)</li>
<li>libsForQt5.phonon-backend-vlc (libsForQt515.phonon-backend-vlc ,plasma5Packages.phonon-backend-vlc)</li>
<li>libsForQt512.phonon-backend-vlc</li>
<li>libsForQt514.phonon-backend-vlc</li>
<li>libvlc</li>
<li>megaglest</li>
<li>minitube</li>
<li>obs-move-transition</li>
<li>obs-studio</li>
<li>obs-v4l2sink</li>
<li>obs-wlrobs</li>
<li>pympress</li>
<li>python37Packages.python-vlc</li>
<li>python38Packages.python-vlc</li>
<li>python39Packages.python-vlc</li>
<li>strawberry</li>
<li>tribler</li>
<li>vlc (vlc_qt5)</li>
</ul>
</details>

**Comment by tu-maurice** [comment]
@SuperSandro2000 there's a port to stable here: #110386

**Pull request merged**
