### PR TITLE
Backport Eclipse changes to release-15.09

### PR DESCRIPTION
**Pull request by bjornfor**
See commits.

I'm looking for feedback, whether we'd like to make such changes on the stable branch or not. I'm thinking 'yes' (obviously).

CC @rycee, @muradu, @DamienCassou

### CODE REVIEW

**Comment by rycee** [comment]
I definitely think this is a good idea. Since Eclipse and the plugins don't get built by Hydra we are vulnerable to URL breakage. This is not a big problem for Eclipse itself and the core plugins such as JDT but I did have that problem with TestNG, for example and the 5b290be commit in this PR includes a fix that I hope will provide more URL stability.

The Scala plugin is another example where the file is updated in place so the hash may change without warning; in fact I just checked and the Scala hash in master differs from a fresh download :-( I'll make a PR for this new version.

So basically I happily support this PR because it is limited in scope (only affects Eclipse and Eclipse plugins) and will fix some issues that currently exist in stable Nixpkgs due to broken URLs.

**Comment by rycee** [comment]
Added the Scala plugin bump in #12638, I suggest adding that commit to this PR.

**Comment by DamienCassou** [comment]
+1

**Comment by bjornfor** [comment]
Cool. Added scala plugin bump to PR. Merged.

**Pull request merged**
