### PR TITLE
phoc: 0.9.0 -> 0.11.0, wlroots_0_12: drop

### LINKED ISSUE #118838: Remove wlroots_0_12 (tracking issue)
We've temporarily introduced `wlroots_0_12` as part of #116544 to avoid breaking some reverse dependencies. The affected attributes should switch to `wlroots` when possible (usually a new upstream release). There's no hurry but let's use this issue to track the current progress.

`wlroots_0_12`:
- [ ] phoc #151519
- [x] cage (https://github.com/Hjdskes/cage/pull/174): #119615
- [x] hikari (https://hub.darcs.net/raichoo/hikari/patch/43e289a3d2974c2347c65ae2a0882892e687e93f and https://hub.darcs.net/raichoo/hikari/patch/736754fcf88bebcabb5dccb2801cb384dbc7588d): #120985
- [x] waybox (https://github.com/wizbright/waybox/commit/309ccd2faf08079e698104b19eff32b3a255b947): #123013
- [x] wayfire (supported since https://github.com/WayfireWM/wayfire/commit/b377906b8fd7f01d482db88cfb06a81c3ebe66a7): #121110
- [x] wio (~~nothing so far~~, turns out the pending patches on the ML should fix the build with wlroots 0.13): #123014
- [x] cagebreak (https://github.com/project-repo/cagebreak/commit/b989fe50f08d77245b73790f52ea2cc730b94b4e and additional commits): ~~#119963~~ #121652 (~~TODO: Fix VM test~~)

`wlroots_0_13`:
- [x] sway: #128036
- [x] hikari (downstream patches: https://cgit.freebsd.org/ports/diff/x11-wm/hikari/files/patch-wlroots-0.14?id=f2820b6cc2170feef17989c422f2cf46644a5b57): #128122
- [x] wio (https://git.sr.ht/~primeos/wio/commit/9d5093c019f6966b8ee0dba1da3361a761d04bcc, send via git-send-email to @AndersonTorres, https://github.com/primeos/nixpkgs/commit/68acf441853f95cc148c0bef7e7b1da5e7025f8c): #128220

### PR DESCRIPTION
**Pull request by zhaofengli**
###### Motivation for this change

We can finally drop `wlroots_0_12`! On the other hand, we now need to keep `wlroots_0_14` when 0.15 gets merged in #151234 :stuck_out_tongue: Tested with #151404 on a PinePhone Pro.

Closes #118838, and supersedes #143785.

Also removing archseer from the maintainer list per request: https://github.com/NixOS/nixpkgs/pull/143785#issuecomment-955873911

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zhaofengli** [comment]
Marking this as draft until #151234 lands in master. We will then add the `wlroots_0_14` override for `phoc`.

**Comment by primeos** [comment]
@zhaofengli thanks a lot for this PR and your patience! :) Did you already test this with Phosh (just to be sure)? I just tried to give it a quick go but realized that it's a bit more involved than I thought (plus I never used it before so I could only perform limited testing).

**Review by primeos — APPROVED** [review]
Diff LGTM and from my very limited testing of Phoc and Phosh (without a proper Phosh setup) it seems fine.

**Comment by zhaofengli** [comment]
@primeos

> Did you already test this with Phosh (just to be sure)?

Yes, to be sure I just re-tested on my PinePhone Pro and it worked without a problem.

> Edit: Personal note: I was surprised that I didn't get any notification for https://source.puri.sm/Librem5/phoc/-/merge_requests/241 which I was subscribed to. Turns out the project was archived and moved to https://gitlab.gnome.org/World/Phosh/phoc.
> 
> So: https://source.puri.sm/Librem5/phoc/-/merge_requests/241 became https://gitlab.gnome.org/World/Phosh/phoc/-/merge_requests/241 which was replaced by https://gitlab.gnome.org/World/Phosh/phoc/-/merge_requests/280 which was superseded by https://gitlab.gnome.org/World/Phosh/phoc/-/merge_requests/300 which finally got merged.

Wow, thanks for keeping an eye out for this! I hope their migration to wlroots 0.15.0 won't be as bumpy.

**Comment by primeos** [comment]
Awesome, thanks a lot @zhaofengli! And very cool that you use it on your PinePhone Pro :) (And of course that you already have a PinePhone Pro :D)

**Pull request merged**
