### PR TITLE
Fix FreeBSD support

### PR DESCRIPTION
**Pull request by wahjava**
###### Motivation for this change

I'm trying to make `nixpkgs` work on FreeBSD, similar to `nix-darwin`. For that, I attempted to fix FreeBSD stdenv. I'm not super familiar with `stdenv`, or internals of `nixpkgs`, so I would appreciate review.

Following is the output from `FreeBSD 12.1 amd64` trying to build `curl`:

https://pastebin.com/0b7cJeHF

For those interested in trying out `nix` on FreeBSD, there is a FreeBSD port in progress, https://github.com/0mp/freebsd-ports-nix which is how I got it  running.

Thanks in advance.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
Hi. So all what I need to test this, is the nix port you referenced?

**Comment by Mic92** [comment]
@yater do you still a machine for me to test?

**Comment by Ericson2314** [comment]
This is cool! I'd like to get to a pure bootstrap from binary bootstrap tools, but we can start here.

**Comment by Mic92** [comment]
Could somebody help me out how to boot freebsd in qemu with functional network?

I tried:

```
$ wget http://ftp.freebsd.org/pub/FreeBSD/snapshots/VM-IMAGES/13.0-CURRENT/amd64/Latest/FreeBSD-13.0-CURRENT-amd64.qcow2.xz
$ xz -d FreeBSD-13.0-CURRENT-amd64.qcow2.xz
$ qemu-system-x86_64 -m 20G -hda FreeBSD-13.0-CURRENT-amd64.qcow2 -smp $(nproc) -enable-kvm -netdev user,id=mynet0,hostfwd=tcp:127.0.0.1:7722-:22 -cpu host -display curses -net nic,netdev=user.0,model=virtio -netdev user,id=user.0 -device virtio-rng-pci
```

I see an ip address in freebsd. However I cannot reach the VM.

**Comment by melchips** [comment]
> I see an ip address in freebsd configured. However I cannot reach the VM.
> This command is more or less what we use in NixOS to get userspace networking with qemu.

Hello,

Maybe it's not related at all, but I noticed that my windows 10 VM, using virtio for network is not working anymore since my upgrade to 20.03 channel.

As a matter of fact, packets emitted from the host to the VM are correctly received on the VM, but packets from the VM to the host are not received and don't appear with tcpdump on the host.

By switching the virtual network card model to e1000e, networking is working properly again.

**Could-you try setting the model to e1000e**, maybe "virtio" is not working for you also, or there is a problem between the virtio modules on the VM and the host.

If no model is working for you, your network configuration may lack something...

Regards.

**Comment by Mic92** [comment]
I just got it working using the following setup `virtualisation.libvirtd.enable = true;` in `/etc/nixos/configuration.nix` and by using the following qemu configuration:

```
#!/usr/bin/env bash

sudo ip tuntap add dev tap0 mode tap
sudo ip link set tap0 up promisc on
sudo ip link set dev virbr0 up
sudo ip link set dev tap0 master virbr0

sudo chmod 666 /dev/net/tun /dev/kvm
qemu-system-x86_64 \
  -m 20G -hda FreeBSD-13.0-CURRENT-amd64.qcow2 -smp $(nproc) -enable-kvm \
  -cpu host -display curses \
  -device virtio-rng-pci \
  -netdev tap,id=net0,ifname=tap0,script=no,downscript=no \
  -device virtio-net,id=net0,netdev=net0 \
```

The FreeBSD Image I got from https://download.freebsd.org/ftp/snapshots/VM-IMAGES/13.0-CURRENT/amd64/Latest/

**Comment by Mic92** [comment]
Also got the nix port installed now.

**Comment by Mic92** [comment]
I am currently on `FreeBSD freebsd 13.0-CURRENT`.
When I run `nix-build` it fails however:

```
$ truss -o /tmp/trace -f nix-build -A curl
```

[trace.txt](https://github.com/NixOS/nixpkgs/files/4403742/trace.txt)

I will have a deeper look later.

**Comment by wahjava** [comment]
> I am currently on `FreeBSD freebsd 13.0-CURRENT`.
> When I run `nix-build` it fails however:
> 
> ```
> $ truss -o /tmp/trace -f nix-build -A curl
> ```
> 
> [trace.txt](https://github.com/NixOS/nixpkgs/files/4403742/trace.txt)
> 
> I will have a deeper look later.

Seems like following is the culprit:

    46107: setuid(0x3e9)				 = 0 (0x0)
    46107: kill(-1,SIGKILL)				 ERR#1 'Operation not permitted'


Did you try building it in multi-user/daemon mode ? or single-user ?

I guess you are not able to build `stdenv` either ? Also could you share the build output (stdout/stderr, or from `/nix/var/log/`) ?

**Comment by Kleidukos** [comment]
Hi! Are there any news on that front? :)

**Comment by Mic92** [comment]
> > I am currently on `FreeBSD freebsd 13.0-CURRENT`.
> > When I run `nix-build` it fails however:
> > ```
> > $ truss -o /tmp/trace -f nix-build -A curl
> > ```
> > 
> > 
> > [trace.txt](https://github.com/NixOS/nixpkgs/files/4403742/trace.txt)
> > I will have a deeper look later.
> 
> Seems like following is the culprit:
> 
> ```
> 46107: setuid(0x3e9)				 = 0 (0x0)
> 46107: kill(-1,SIGKILL)				 ERR#1 'Operation not permitted'
> ```
> 
> Did you try building it in multi-user/daemon mode ? or single-user ?
> 
> I guess you are not able to build `stdenv` either ? Also could you share the build output (stdout/stderr, or from `/nix/var/log/`) ?

It fails both in single-user mode and with nix-daemon:

```
root@freebsd:~ # nix-daemon
accepted connection from pid <unknown>, user root (trusted)
error: cannot kill processes for uid '1001': Operation not permitted
accepted connection from pid <unknown>, user root (trusted)
error: cannot kill processes for uid '1001': Operation not permitted
```

**Comment by wahjava** [comment]
> > > I am currently on `FreeBSD freebsd 13.0-CURRENT`.
> > > When I run `nix-build` it fails however:
> > > ```
> > > $ truss -o /tmp/trace -f nix-build -A curl
> > > ```
> > > 
> > > 
> > > [trace.txt](https://github.com/NixOS/nixpkgs/files/4403742/trace.txt)
> > > I will have a deeper look later.
> > 
> > 
> > Seems like following is the culprit:
> > ```
> > 46107: setuid(0x3e9)				 = 0 (0x0)
> > 46107: kill(-1,SIGKILL)				 ERR#1 'Operation not permitted'
> > ```
> > 
> > 
> > Did you try building it in multi-user/daemon mode ? or single-user ?
> > I guess you are not able to build `stdenv` either ? Also could you share the build output (stdout/stderr, or from `/nix/var/log/`) ?
> 
> It fails both in single-user mode and with nix-daemon:
> 
> ```
> root@freebsd:~ # nix-daemon
> accepted connection from pid <unknown>, user root (trusted)
> error: cannot kill processes for uid '1001': Operation not permitted
> accepted connection from pid <unknown>, user root (trusted)
> error: cannot kill processes for uid '1001': Operation not permitted
> ```

This is interesting. I'm testing it in `12.1-RELEASE` and had no such issue. I wonder if you have some fancy security setting enabled in `13-CURRENT`. Could you maybe try it with `12.1-RELEASE` ?

**Comment by Mic92** [comment]
> > > > I am currently on `FreeBSD freebsd 13.0-CURRENT`.
> > > > When I run `nix-build` it fails however:
> > > > ```
> > > > $ truss -o /tmp/trace -f nix-build -A curl
> > > > ```
> > > > 
> > > > 
> > > > [trace.txt](https://github.com/NixOS/nixpkgs/files/4403742/trace.txt)
> > > > I will have a deeper look later.
> > > 
> > > 
> > > Seems like following is the culprit:
> > > ```
> > > 46107: setuid(0x3e9)				 = 0 (0x0)
> > > 46107: kill(-1,SIGKILL)				 ERR#1 'Operation not permitted'
> > > ```
> > > 
> > > 
> > > Did you try building it in multi-user/daemon mode ? or single-user ?
> > > I guess you are not able to build `stdenv` either ? Also could you share the build output (stdout/stderr, or from `/nix/var/log/`) ?
> > 
> > 
> > It fails both in single-user mode and with nix-daemon:
> > ```
> > root@freebsd:~ # nix-daemon
> > accepted connection from pid <unknown>, user root (trusted)
> > error: cannot kill processes for uid '1001': Operation not permitted
> > accepted connection from pid <unknown>, user root (trusted)
> > error: cannot kill processes for uid '1001': Operation not permitted
> > ```
> 
> This is interesting. I'm testing it in `12.1-RELEASE` and had no such issue. I wonder if you have some fancy security setting enabled in `13-CURRENT`. Could you maybe try it with `12.1-RELEASE` ?

I am using the official qemu image without any non-standard modifications.

**Comment by Ericson2314** [comment]
@Kleidukos You may also be interested in #82131, which we can use to make a *pure* freebsd stdenv by cross-building the bootstrap tools.

There is plenty to be done for #82131, and no need to set up and qemu or other things to start (let's get things building and then worry about whether they actually run!) so I hope it is relatively easy to contribute to---I certainly could use all the help I can get!

**Comment by Mic92** [comment]
Now that nix is in ports, can someone else have a look at this again?

**Comment by AndersonTorres** [comment]
I would like to help... what it needs to be done?

**Comment by deliciouslytyped** [comment]
By the way, there is a #freebsd-nix channel on freenode.

**Comment by Mic92** [comment]
> I would like to help... what it needs to be done?

Some maintainer should review/test the patch proposed here.

**Comment by alyssais** [comment]
Fix for @Mic92’s Nix issue: https://github.com/NixOS/nix/pull/4530

**Review by alyssais — APPROVED** [review]
Tested `nix-build -A hello && result/bin/hello`; works fine.

Will need to be rebased and have some minor conflicts fixed.

**Comment by alyssais** [comment]
Rebased, fixed up, and pushed. (Couldn’t do that on the PR since the branch disappeared.)

Thanks @wahjava!

**Pull request closed without merging**
