### PR TITLE
dune_2: 2.6.2 -> 2.7.0

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change
https://github.com/ocaml/dune/releases/tag/2.7.0

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by marsam** [comment]
@GrahamcOfBorg build flow fstar ocamlformat beluga satysfi

**Comment by vbgl** [comment]
There is an easy fix to get dune 2 for OCaml 4.07. Just raise the version number there: https://github.com/NixOS/nixpkgs/blob/4e7fdca34c4bb94470590f02615e56cee97c2d75/pkgs/top-level/ocaml-packages.nix#L221

You should nonetheless raise the `minimumOCamlVersion` attribute in `dune-private-libs`.

**Comment by marsam** [comment]
@GrahamcOfBorg build flow fstar ocamlformat beluga satysfi

**Comment by marsam** [comment]
@GrahamcOfBorg build flow fstar ocamlformat beluga satysfi

**Comment by marsam** [comment]
thank you @vbgl for the hint

**Review by anmonteiro — COMMENTED** [review]
Hey @marsam would you mind also including the `dune-glob` and `dune-action-plugin` libraries in this PR?

**Comment by vbgl** [comment]
@GrahamcOfBorg build ocamlPackages.dune-action-plugin

**Pull request merged**
