### PR TITLE
mattermost-desktop 5.5.0 -> 5.6.0

### PR DESCRIPTION
**Pull request by Antiarchitect**
## Description of changes

Update mattermost-desktop to 5.6.0. [Changelog](https://docs.mattermost.com/deploy/desktop-app-changelog.html#release-v5-6).

## Things done
Update mattermost-desktop
Update electron_26 -> electron_27

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by sochotnicky** [comment]
I've done some basic testing and this update works for my case at least. Ran `nix-shell -p nixpkgs-review --command "nixpkgs-review pr https://github.com/NixOS/nixpkgs/pull/275836"`, package got build and works.

**Comment by Antiarchitect** [comment]
@sohotnicky Thanks for the tip. I've updated to 28 at first, but then I read MM-desktop release notes more carefully.

**Review by jokogr — APPROVED** [review]
Sorry for the delay, it's been a while since I last used this. LGTM.

**Comment by Antiarchitect** [comment]
@jokogr Hi! Should this MR be backported to 23.11 by me or you or at all?

**Comment by sochotnicky** [comment]
@Antiarchitect Regarding backport question - I think Mattermost desktop update *might* fit within https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#changes-acceptable-for-releases 

Not sure if electron update changes things.

**Comment by Antiarchitect** [comment]
As Electron fixes some CVEs very often should it be considered as security critical dependency? :)))
Anyway, that's why I'm asking more experienced guys in nixpkgs internal cuisine.

**Comment by sochotnicky** [comment]
> As Electron fixes some CVEs very often should it be considered as security critical dependency? :))) Anyway, that's why I'm asking more experienced guys in nixpkgs internal cuisine.

Actually a very good point WRT security - I just checked https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline and Electron 26 just went EOL a week ago. So one more reason to backport.

**Pull request merged**
