### PR TITLE
python3.pkgs.heisenbridge: Move to python-packages.nix

### PR DESCRIPTION
**Pull request by dasJ**
###### Motivation for this change

No need for a top-level attribute since this does not provide any binaries.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by mweinelt — CHANGES_REQUESTED** [review]
Vetoing this change, because there should be an executable.

https://github.com/hifi/heisenbridge/blob/master/Dockerfile#L12

**Comment by sumnerevans** [comment]
Maybe we should add a wrapper script in `bin` or something along those lines?

**Comment by mweinelt** [comment]
I'm working on a patch to fix this upstream.

**Comment by dasJ** [comment]
I don't see any problem with [sumnerevans](https://git.sr.ht/~sumner/nixos-configuration/tree/master/item/modules/services/matrix/heisenbridge.nix)'s solution.

**Comment by mweinelt** [comment]
```
❯ result/bin/heisenbridge
usage: python3.8 -m heisenbridge [-h] [-v] -c CONFIG [-l LISTEN_ADDRESS] [-p LISTEN_PORT] [-u UID] [-g GID] [-i] [--generate] [--reset] [-o OWNER] [homeserver]
python3.8 -m heisenbridge: error: the following arguments are required: -c/--config
```

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 124889` at a47ada38 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.heisenbridge</li>
    <li>python39Packages.heisenbridge</li>
  </ul>
</details>

**Pull request closed without merging**
