### PR TITLE
kitty: fix build on aarch64-darwin

### PR DESCRIPTION
**Pull request by bobrik**
###### Motivation for this change

Fixing the following issue:

```
kitty/cocoa_window.m:179:37: error: 'NSUserNotificationCenter' is deprecated:
  first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced
  with UserNotifications.frameworks API [-Werror,-Wdeprecated-declarations]
```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS (aarch64)
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
Use lib.optionalString

**Comment by bobrik** [comment]
I copy-pasted this from some other package, so I went ahead and changed all other similar places. Somebody needs to retarget this to staging now, I suppose.

**Comment by Artturin** [comment]
you dont have to do it in this pr

**Comment by SuperSandro2000** [comment]
More important this needs to target staging.

**Comment by Luflosi** [comment]
@bobrik you can target staging yourself by clicking edit to the right of the title and then changing the branch from master to staging. Maybe you also need to rebase your commits.
I don't have a Mac with macOS 11, so I can't test this PR.

**Comment by bobrik** [comment]
I don't think I even successfully rebased a PR to a different branch without pulling a whole lot of unrelated reviewers. The manual process seems to rely on hope a bit too much: https://github.com/NixOS/nixpkgs/pull/115220#issuecomment-791839041.

Is there there a reason why somebody with permissions can't ask ofborg to rebase?

**Comment by 7c6f434c** [comment]
@ofborg rebase staging

**Comment by 7c6f434c** [comment]
!rebase staging

**Comment by 7c6f434c** [comment]
I don't think ofBorg supports rebase… 

I would recommend maybe rebasing the PR on `git merge-base` of `master` and `staging`, this should reduce the risk of mentioning everyone. Also, retarget and immediately close, and check it worked (and maybe push a staging-rebased version) before reopening.

**Comment by bobrik** [comment]
See https://github.com/NixOS/nixpkgs/pull/115226#issuecomment-791960343, it's absolutely possible to rebase. You just need to be on the list to be allowed to do it.

**Comment by 7c6f434c** [comment]
This is very definitely not ofBorg. (And I am not sure if this action got deactivated or just takes forever — I tried and got no reaction…)

**Comment by zowoq** [comment]
The rebase action was removed a while ago as it was broken.

**Comment by bromanko** [comment]
@bobrik why did you close this? Did you find an alternative solution?

**Pull request closed without merging**
