### PR TITLE
matrix-synapse: 1.47.0 -> 1.47.1

### PR DESCRIPTION
**Pull request by eyJhb**
###### Motivation for this change
https://matrix.org/blog/2021/11/18/pre-disclosure-upcoming-security-release-of-synapse-1-47-1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SEbbaDK** [comment]
This is a security fix for a high-severity issue with synapse: https://matrix.org/blog/2021/11/18/pre-disclosure-upcoming-security-release-of-synapse-1-47-1

**Comment by Synthetica9** [comment]
These tests still succeed: 

```
nixos/tests/matrix/mjolnir.nix
nixos/tests/matrix-synapse.nix
nixos/tests/matrix/pantalaimon.nix
nixos/tests/matrix-appservice-irc.nix
```

**Review by fadenb — APPROVED** [review]

**Review by Synthetica9 — APPROVED** [review]

**Review by Ma27 — APPROVED** [review]
Deployed and still working fine for me.

**Comment by eyJhb** [comment]
Thanks for the fast response @Ma27 ! Deployed and working here as well :)

Should have noted that in the initial comment :)

**Comment by Ekleog** [comment]
@Ma27 I just finished building, running nixos tests and pushing the cherry-picked commit for 21.05, so there's no longer any need for you to do it :)

**Comment by Ekleog** [comment]
Also, thank you all for the reaction speed!

**Comment by Ma27** [comment]
Nice, thanks!

**Comment by eyJhb** [comment]
> @Ma27 I just finished building, running nixos tests and pushing the cherry-picked commit for 21.05, so there's no longer any need for you to do it :)

Just going to add this here as well, I see no patch for this is 21.05 branch?
Am I looking somewhere wrong?

Is there any reason not to update 21.05 to 1.47.1, instead of just fetching the patch?

**Pull request merged**
