### PR TITLE
wxGTK31: 3.1.0 -> 3.1.2

### PR DESCRIPTION
**Pull request by ArdaXi**
###### Motivation for this change
In #55475 a crash bug was introduced in Prusa Slicer. After some investigation, this seemed to be a bug in wxWidgets 3.1.0 that was no longer present in 3.1.2. As 3.1.2 has been out for a while, it seemed like a good idea to upgrade the package.

3.1.2 no longer accepts the `compat2[46]` options, which is why I copied the old file over and removed those configure flags. They seemed to be passed downstream however, so I did not remove the arguments entirely.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Moredread** [comment]
If just the compat options are different, maybe filtering them out (and asserting that they aren't set) in the 3.1 derivation would be nicer.

I'm not sure though how you can override a derivation and changing the function signature though.

**Comment by ArdaXi** [comment]
It would be possible, but it would involve complex filtering on the `configureFlags` attribute, which is fragile and creates inter-dependencies between 3.0 and 3.1. Given that the scripts changed meaningfully between versions, I would argue that having entirely separate derivations is the cleanest option here. Additionally, 2.8, 2.9 and 3.0 are all entirely independent files already, it was only 3.1 that differed.

**Comment by Moredread** [comment]
That makes sense :)

**Comment by vcunat** [comment]
From my NixPkgs experience I'd personally prefer to have e.g. `common.nix` and each of the pair could add a couple flags to this base.  So far the expression are almost exactly the same and I suspect future fixes would often need to be applied to both.

**Comment by Evils-Devils** [comment]
@ArdaXi it looks like these changes got in, can this PR be closed?

**Comment by ArdaXi** [comment]
Looks like #63595 is an exact duplicate of this and got merged, so yes, closing.

**Pull request closed without merging**
