### PR TITLE
bazel: 7.0.0 -> 7.0.2

### LINKED ISSUE #20527: Bazel 7: `--sandbox_add_mount_pair` under `/tmp` fails
### Description of the bug:

With Bazel 7, but neither Bazel 6.4.0 nor `--noincompatible_sandbox_hermetic_tmp`, builds with `--sandbox_add_mount_pair` referencing a path under `/tmp` fail since `/tmp` has been remounted before the manually specified mount pair is applied.

### Which category does this issue belong to?

Local Execution

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```shell
touch WORKSPACE

cat > .bazelrc <<'EOF'
build --sandbox_add_mount_pair=/tmp/some/path:/etc
EOF

cat > BUILD <<'EOF'
genrule(
    name = "gen",
    outs = ["data.txt"],
    cmd = "ls /etc > $@",
)
EOF
```

Then:
```
$ mkdir -p /tmp/some/path
$ bazel clean --expunge && bazel shutdown && bazel build //:gen
...
src/main/tools/linux-sandbox-pid1.cc:305: "mount(/tmp/some/path, /etc, nullptr, MS_BIND | MS_REC, nullptr)": No such file or directory
Target //:gen failed to build
...
# bazel clean --expunge && bazel shutdown && bazel build //:gen --noincompatible_sandbox_hermetic_tmp
...
INFO: Build completed successfully, 2 total actions
```

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

7.0.0

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

_No response_

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

_No response_

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

_No response_

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by Strum355**
## Description of changes

Changelog for 7.0.2: https://github.com/bazelbuild/bazel/releases/tag/7.0.2
List of commits between 7.0.0 and 7.0.2: https://github.com/bazelbuild/bazel/compare/7.0.0...7.0.2

Most importantly perhaps, this bump fixes https://github.com/bazelbuild/bazel/issues/20527.

This PR also includes provisions to enable overriding the version. Previously this wasnt trivial to do due to `version` being a locally scoped variable, so while the `src` could be updated, `version` was used in a few attributes via string interpolation that are more awkward to patch than it could be 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by flurie — APPROVED** [review]
I ran `nixpkgs-review` and tested the Bazel binary on a few targets in large Bazel 7 project on x86_64-linux. I did not test the hermetic `/tmp` fix specifically, but I have had some users verify that 7.0.2 fixes the issue for them, so I am satisfied.

I can also run `nixpkgs-review` on aarch64-darwin, but I'm not sure how functional this is on darwin in general? The meta info indicates it is.

**Comment by malt3** [comment]
Do you think it makes sense to add this patch back? https://github.com/sourcegraph/sourcegraph/pull/59359

I also ran into it for multiple Bazel projects.

**Comment by Strum355** [comment]
> Do you think it makes sense to add this patch back? [sourcegraph/sourcegraph#59359](https://github.com/sourcegraph/sourcegraph/pull/59359)
> 
> I also ran into it for multiple Bazel projects.

I would be tempted to put in a separate PR, although theres some unfinished discussion on the topic here: https://github.com/NixOS/nixpkgs/pull/262152

**Comment by Strum355** [comment]
@layus @wegank sorry for the ping, would we be able to merge this?

**Comment by layus** [comment]
Yes, sure :-).
@Strum355 Thanks for the PR
@malt3, @flurie Thanks for testing this toroughly
@malt3 I did investigate the PATH issues quite a lot. Let's move the discussion to https://github.com/NixOS/nixpkgs/issues/289505

**Pull request merged**
