### PR TITLE
Revert "python311Packages.asn1crypto: 1.5.1 -> 1.5.1-unstable-2023.11.03"

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
This reverts commit https://github.com/NixOS/nixpkgs/commit/6460425484debf3215bdf36841816e735904e0dc because it breaks certomancer.
See https://github.com/MatthiasValvekens/certomancer/issues/12.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by vcunat** [comment]
FYI, this revert broke the build of `python312Packages.asn1crypto`, e.g. see https://hydra.nixos.org/build/249591907/nixlog/1/tail

**Comment by mweinelt** [comment]
It was either certomancer or that. I kinda need asn1crypto for home-assistant's 3.12 migration. There are no good choices :shrug:

**Comment by dotlambda** [comment]
> I kinda need asn1crypto for home-assistant's 3.12 migration.

Will Home Assistant drop support for 3.11?

**Comment by mweinelt** [comment]
Yes in 2024.4.0.

**Comment by dotlambda** [comment]
How does upstream deal with the lack of Python 3.12 support in asn1crypto?

**Comment by mweinelt** [comment]
Consuming wheels from PyPi does not necessitate running the upstreams test suite.

**Comment by dotlambda** [comment]
So an easy fix for now would be to disable asn1crypto's tests for Python >= 3.12, at least inside the home-assistant package.

**Comment by vcunat** [comment]
Or different asn1crypto versions based on python version?  Doesn't sound too complicated to me, and I suspect it would provide better results (for 3.12).

**Comment by vcunat** [comment]
I pushed that quickly as 418b5d9e5c31 to get it building (and let Hydra uncover other failures).  Feel free to change the approach, etc.

**Pull request merged**
