### PR TITLE
zoom-us: update && added new field to `meta` attributes

### PR DESCRIPTION
**Pull request by danbst**
###### Motivation for this change
zoom-us upgrade.

Second commit adds `releaseNews` meta-attribute. If it is controversial or unwanted, that commit may be dropped. Personally, I often find it hard to find the release news link in google, so I propose to document found one in nixpkgs.

And made meta.nix doc more secure (!) by making all links to GNU hello https://

And fixed homepage link for GNU hello - previously it was a link to manual, not homepage.
EDIT: reverted this change, there are plenty of references, need to change them all, but this is out of scope for this PR.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by tadfisher** [comment]
I'd prefer `changelog` myself.

**Comment by danbst** [comment]
@tadfisher you mean, rename `releaseNews` -> `changelog`?

**Comment by srhb** [comment]
I'm sorry for bikeshedding this, but could we split the releaseNews idea into a separate PR? I think it deserves more visibility than what it'll get in a specific package PR, and it'll hold up zoom needlessly.

**Comment by tadfisher** [comment]
Agreed, let's drop #5ae83615ff33445475f5f505423dc361fda0eedd and open that as a separate PR.

**Comment by domenkozar** [comment]
Superseeded by https://github.com/NixOS/nixpkgs/pull/42742

**Pull request closed without merging**
