### PR TITLE
pkgsStatic for 18.09

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

A backport of #48803 for those wanting to use this but unable to switch from stable to master. A note is adding saying the interface is provisional. Presumably in 19.03 this will arrive on staging "the normal way" and the dust will have settled again.

Rebased on a recentish common ancestor of `master` and `relase-18.09`. This way any further fixes can be made on top of this (minus the top commit) and then easily merged into both `master` and `release-19.09`. This is a lot easier than cherry-pick; with cherry-pick alone it wouldn't make sense to pre-release new interfaces on stable.

N.B. I skipped b966d3c5835fdbaa153a9eacd08cdbf789ee1b40 because that is a breaking interface change not appropriate for stable.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

CC @vaibhavsagar

### CODE REVIEW

**Comment by matthewbauer** [comment]
This is missing a patch for portable libsystem

**Comment by Ericson2314** [comment]
@matthewbauer that was done after the original PR?

**Comment by Ericson2314** [comment]
Ah I think you mean #51881 or `5d6b7c74adbcd067d46c8bd7866ba553968bad56`, both of which are not merged (not sure whether the last one is in a PR either.) So I think this is ready to go; I can comment what branch to rebase unmerged work on or (with permission) do the force-push myself.

**Comment by matthewbauer** [comment]
0b85745 Should be added. Otherwise darwin stuff is broken.

**Comment by Ericson2314** [comment]
Oh `5d6b7c74adbcd067d46c8bd7866ba553968bad56` was rebased onto master by github but the original commit not deleted. Fix now, with a small tangle of merges (sorry!).

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nixpkgs/commit/af2cebe78fd185d1bbabd071f85f74654602d042 is the cherry-pick. It's on master and `release-18.09` as expected.

**Pull request merged**
