### PR TITLE
llvm_11: 11.0.0rc2 -> 11.0.0rc5

### PR DESCRIPTION
**Pull request by ggreif**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review pr 98594"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ggreif** [comment]
@GrahamcOfBorg build clang_11

**Comment by ggreif** [comment]
@DieGoldeneEnte may I ask you to run `nix-shell -p nix-review --run "nix-review pr 98594` on linux? Not too urgent, because the final is not out yet.

**Comment by DieGoldeneEnte** [comment]
I actually just wanted to take a look at llvm11, since it should be out soon :)
nix-review only failed on faustlive (foo-yc20, purePackages.faust), but it uses llvm9 so we are not the reason (the others depend on faustlive).
So this should be good.

**Review by primeos — APPROVED** [review]
Thanks @ggreif and @DieGoldeneEnte! :)

**Pull request merged**
