### PR TITLE
Backport Rust 1.38 to 19.09

### PR DESCRIPTION
**Pull request by edolstra**
It might be too late for this, but it would be nice to ship NixOS 19.09 with an up-to-date Rust compiler.

### CODE REVIEW

**Review by LnL7 — APPROVED** [review]
We've had to update rust on stable before for firefox IIRC so unless we start keeping multiple versions it probably makes sense to also keep it updated. Some fixes like https://github.com/NixOS/nixpkgs/pull/70313 should also be backported if this goes through.

**Review by wizeman — APPROVED** [review]

**Comment by hedning** [comment]
This, https://github.com/NixOS/nixpkgs/commit/02585db25bc4d5d623ce083b41f727c65709ad3f, is probably needed too, as librsvg `2.44.14` broke with the rust update.

**Review by Mic92 — APPROVED** [review]
I also think we should backport rustc because of firefox: cc @andir

**Comment by Mic92** [comment]
I was able to build thunderbird on x86_64-linux

**Comment by andir** [comment]
As far as I can see Firefox 70 will still be fine with 1.36: https://hg.mozilla.org/mozilla-central/rev/f82b4a26b4e46d2586972b71e25439470e14117a
That being said I am usually lost in the mercurial interface of mozilla and might likely have missed a bump.

**Comment by Mic92** [comment]
This might have broke tor-browser: cc @oxij

**Comment by YorikSar** [comment]
@Mic92 just took a look at Firefox failures (ESR 60 and 68, Tor browser and Icecat) in Hydra and it seems all of them fail with
```
error[E0506]: cannot assign to `self.input.cached_token` because it is borrowed
   --> /build/firefox-68.1.0/third_party/rust/cssparser/src/parser.rs:584:17
    |
559 |     pub fn next_including_whitespace_and_comments(&mut self) -> Result<&Token<'i>, BasicParseError<'i>> {
    |                                                   - let's call the lifetime of this reference `'1`
...
572 |             Some(ref cached_token)
    |                  ---------------- borrow of `self.input.cached_token` occurs here
...
584 |                 self.input.cached_token = Some(CachedToken {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^ assignment to borrowed `self.input.cached_token` occurs here
...
596 |         Ok(token)
    |         --------- returning this value requires that `self.input.cached_token.0` is borrowed for `'1`
```
that was fixed in servo/rust-cssparser@3c98d22 (probably along with other warnings from 1.37 that became errors in 1.38 in servo/rust-cssparser#245)

I didn't dig deeper and don't know if patching `cssparser` separately would fix it.

**Comment by Mic92** [comment]
I reverted the backport for now: 3becc5bb5634b4bc4333ca474a523f47657d334e
Once we fixed this we can have a look again.

**Comment by Mic92** [comment]
This one also needs to be backported: https://github.com/NixOS/nixpkgs/pull/70506

**Pull request merged**
