### PR TITLE
linuxPackages.rtl8192eu: 4.4.1.20200620 -> unstable-2021-01-11

### PR DESCRIPTION
**Pull request by patrykf03**
###### Motivation for this change
fixed the build on recent kernels

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by IvarWithoutBones — APPROVED** [review]
Result of `nixpkgs-review pr 110786` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>linuxPackages-libre.rtl8192eu</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>linuxPackages.rtl8192eu</li>
    <li>linuxPackages_4_14.rtl8192eu</li>
    <li>linuxPackages_4_19.rtl8192eu</li>
    <li>linuxPackages_4_4.rtl8192eu</li>
    <li>linuxPackages_4_9.rtl8192eu</li>
    <li>linuxPackages_5_10.rtl8192eu</li>
    <li>linuxPackages_hardened.rtl8192eu</li>
    <li>linuxPackages_latest-libre.rtl8192eu</li>
    <li>linuxPackages_latest_hardened.rtl8192eu</li>
    <li>linuxPackages_latest_xen_dom0.rtl8192eu</li>
    <li>linuxPackages_latest_xen_dom0_hardened.rtl8192eu</li>
    <li>linuxPackages_lqx.rtl8192eu</li>
    <li>linuxPackages_testing_bcachefs.rtl8192eu</li>
    <li>linuxPackages_xen_dom0.rtl8192eu</li>
    <li>linuxPackages_xen_dom0_hardened.rtl8192eu</li>
    <li>linuxPackages_zen.rtl8192eu</li>
  </ul>
</details>

Error for `linuxPackages-libre.rtl8192eu`:
```
builder for '/nix/store/hg7kjfjgffx9p5wcpc2yg19g31x6va1l-linux-config-5.4.92.drv' failed with exit code 1; last 10 log lines:
  applying patch /nix/store/mnlqwys9dxznjcvq4w3s0435s9ql8qv8-bridge-stp-helper.patch
  patching file net/bridge/br_private.h
  Hunk #1 succeeded at 46 (offset 7 lines).
  applying patch /nix/store/mbz5gln1q4swlzmqs2399br98qjif9kn-request-key-helper.patch
  patching file security/keys/request_key.c
  applying patch /nix/store/2lr5rrl7ipi8yf0vw8bacqxv1xaw7gph-rtl8761b-support.patch
  patching file drivers/bluetooth/btrtl.c
  Hunk #1 FAILED at 130.
  Hunk #2 succeeded at 255 (offset 4 lines).
  1 out of 2 hunks FAILED -- saving rejects to file drivers/bluetooth/btrtl.c.rej
cannot build derivation '/nix/store/rvnjsf94c4lccjjyivq9133xvp61l7vj-linux-5.4.92.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ssv533mzgzdlh1r28jdn8vhy3hnra5ih-rtl8192eu-5.4.92-unstable-2021-01-11.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/6jhfl1x1prwvdka6hp9jyx1ib72a04aq-env.drv': 1 dependencies couldn't be built
```
I don't think that is related to this PR, so LGTM :)

**Comment by troydm** [comment]
@patrykf03 why did you changed the version to '   version = "unstable-2021-01-11";  '  ?  
Correct version would be version = "4.4.1.20210111", please don't break version lineage for this package

**Review by troydm — CHANGES_REQUESTED** [review]
version needs to be consistent with previous format

**Review by troydm — APPROVED** [review]

**Comment by troydm** [comment]
@patrykf03 could you please resolve merge conflict for your changes

**Comment by SuperSamus** [comment]
I guess this can be closed with #177642 being merged.

**Comment by troydm** [comment]
Yup, closing

**Pull request closed without merging**
