### PR TITLE
pulumi: 3.72.2 -> 3.77.1

### PR DESCRIPTION
**Pull request by glennpratt**
## Description of changes

https://repology.org/project/pulumi/versions

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
On macos 10.15:

```
error: hash mismatch in fixed-output derivation '/nix/store/61qwf3cb0ijrjlm0krv62j9892j7f0sw-pulumi-language-go-3.77.1-go-modules.drv':
         specified: sha256-6/umLzw7HMplP/cJknBsWmiwAnc+YM4tIz4Zl2QMTOQ=
            got:    sha256-i4gqh0VHVJ3JfRAl7izhNbjdP8jf7C9ix3qFjaCK458=
error: 1 dependencies of derivation '/nix/store/qc5kafk8kzc6gfbxx12v939r9ldxmidz-pulumi-language-go-3.77.1.drv' failed to build
error: hash mismatch in fixed-output derivation '/nix/store/rdmc4fwl0fa6452bqlaw5rzfp823pr8s-pulumi-language-nodejs-3.77.1-go-modules.drv':
         specified: sha256-3kDWb+1aebV2D+Nm5bkhKrJZMe/lD0ltFQ7p+Bfk644=
            got:    sha256-nncrl6fsf90dWr8kgOJFsA2zbLUqOH72mae+S1ssuE4=
error: 1 dependencies of derivation '/nix/store/8q5fxjfmrcaj35na70rq38qnzpkchvr4-pulumi-language-nodejs-3.77.1.drv' failed to build
error: builder for '/nix/store/8kgddwprf6ijwkapapb382yahw1ci802-python3.11-pulumi-3.77.1.drv' failed with exit code 1;
       last 10 log lines:
       > removing build/bdist.macosx-10.12-x86_64/wheel
       > Finished executing setuptoolsBuildPhase
       > installing
       > Executing pipInstallPhase
       > /private/tmp/nix-build-python3.11-pulumi-3.77.1.drv-0/pulumi/sdk/python/lib/dist /private/tmp/nix-build-python3.11-pulumi-3.77.1.drv-0/pulumi/sdk/python/lib
       > Processing ./pulumi-3.77.1-py3-none-any.whl
       > Requirement already satisfied: protobuf~=4.21 in /nix/store/gkh18xi8rhj309svy7gjz5msi7k2vxff-python3.11-protobuf-4.21.12/lib/python3.11/site-packages (from pulumi==3.77.1) (4.21.12)
       > ERROR: Could not find a version that satisfies the requirement grpcio==1.56.0 (from pulumi) (from versions: none)
       > ERROR: No matching distribution found for grpcio==1.56.0
       > 
       For full logs, run 'nix log /nix/store/8kgddwprf6ijwkapapb382yahw1ci802-python3.11-pulumi-3.77.1.drv'.
error: 1 dependencies of derivation '/nix/store/l9b2qaa7dn9gm4n0dlaw1g723ci5039v-python3.11-pulumi-aws-5.42.0.drv' failed to build
error: builder for '/nix/store/7x4pyg77dsi5qv1xb5ipzmmxjmyy80gv-python3.10-pulumi-3.77.1.drv' failed with exit code 1;
       last 10 log lines:
       > adding 'pulumi/runtime/proto/codegen/mapper_pb2_grpc.py'
       > adding 'pulumi-3.77.1.dist-info/METADATA'
       > adding 'pulumi-3.77.1.dist-info/WHEEL'
       > adding 'pulumi-3.77.1.dist-info/top_level.txt'
       > adding 'pulumi-3.77.1.dist-info/RECORD'
       > removing build/bdist.macosx-10.12-x86_64/wheel
       > Finished executing setuptoolsBuildPhase
       > installing
       > Executing pipInstallPhase
       > /private/tmp/nix-build-python3.10-pulumi-3.77.1.drv-0/pulumi/sdk/python/lib/dist /private/tmp/nix-build-python3.10-pulumi-3.77.1.drv-0/pulumi/sdk/python/lib
       For full logs, run 'nix log /nix/store/7x4pyg77dsi5qv1xb5ipzmmxjmyy80gv-python3.10-pulumi-3.77.1.drv'.
```

**Comment by glennpratt** [comment]
@risicle weird! I'm on macOS 13.5 + aarch64. Seems like you get multiple errors too.

What command did you run? Have you tested against master as well?

**Comment by risicle** [comment]
This is a `nixpkgs-review` run.

**Comment by glennpratt** [comment]
Oh, now I understand that output, sorry for the confusion.

**Comment by Trundle** [comment]
Thank you for your PR and sorry for not looking into this earlier. With #263085, there is now Pulumi 3.89.0

**Pull request closed without merging**
