### PR TITLE
nixos/pam: pam_mkhomedir umask to 0077

### PR DESCRIPTION
**Pull request by nberlee**
###### Motivation for this change
pam_mkhomedir should create homedirs with the same umask as the rest of the system. Currently it creates homedirs with go+rx which makes it readable for other non-privileged users.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by mweinelt — APPROVED** [review]

**Comment by oxij** [comment]
The change LGTM, and I agree it's a good idea to use 0077 by default.
Or maybe even make an option out of it...

The commit message should be split into title+body, though.

**Comment by nberlee** [comment]
> The commit message should be split into title+body, though.

Sorry, first MR here.
Looking at the `CONTRIBUTING.md` I think you mean split by an extra new line. If so, that is now done.

**Comment by nberlee** [comment]
@oxij I splitted the title+body

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by nberlee** [comment]
Maybe the urgency is not clear; this is a security issue:
pam_mkhomedir creates home directories which are world readable (755). This is unexpected because normal (adduser/useradd) behavior is to create home directories with 700.

The umask set here does not relate to the umask of the newly created user when logged in.

Please tell me what to do to get this merged.

**Comment by mweinelt** [comment]
I wonder if this qualifies for a release notes entry.

**Comment by aanderse** [comment]
@mweinelt yes, release notes would be good here.
@nberlee are you able to add a quick entry to the release notes mentioning this change? I promise we'll merge ASAP!

**Comment by Artturin** [comment]
@aanderse i added release notes

**Comment by aanderse** [comment]
Thanks everyone!

**Pull request merged**
