### PR TITLE
wayland: 1.21.0 -> 1.22.0

### PR DESCRIPTION
**Pull request by PedroHLC**
###### Description of changes

This version will be necessary to build the next version of wlroots.

- Final: https://lists.freedesktop.org/archives/wayland-devel/2023-April/042647.html
- RC1 :https://lists.freedesktop.org/archives/wayland-devel/2023-March/042643.html
- Beta: https://lists.freedesktop.org/archives/wayland-devel/2023-March/042637.html
- Alpha: https://lists.freedesktop.org/archives/wayland-devel/2023-February/042629.html

Cc @primeos since you did the last bump.

###### Things done

I've built the single package, and confirmed that the darwin patch still applies.

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
Can someone test [launching firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1826583)?

**Comment by SebTM** [comment]
> Some Arch users say after the bump [Firefox crashes](https://bugzilla.mozilla.org/show_bug.cgi?id=1826583), I wonder if we should backport [related fixes](https://bugzilla.mozilla.org/show_bug.cgi?id=1826583#a303442_580271) for that.

Yes please, see reports in https://github.com/NixOS/nixpkgs/issues/226539 :)

**Comment by bobby285271** [comment]
> Yes please, see reports in https://github.com/NixOS/nixpkgs/issues/226539 :)

Hmmm, the [ff report](https://bugzilla.mozilla.org/show_bug.cgi?id=1826583) theoretically should be specific to wayland 1.21.91+ due to the new warnings logged ([!282](https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/282), [!297](https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/297)) I think :thinking:

**Comment by bobby285271** [comment]
Hmmm, it actually crashes for me™, using `system.replaceRuntimeDependencies`. Probably *something* is needed to trigger the crash, I haven't go deep into it yet.

<details><summary>Screenshot showing <code>MozCrashReason: warning: queue 0x7fe1e9599a90 destroyed while proxies still attached:</code></summary>



</details>

**Comment by Kiskae** [comment]
That is actually a firefox bug that is triggered by stricter protocol checks triggered by the mesa driver.

It came up in #226539 and [will be fixed in firefox 113 (and maybe 112)](https://bugzilla.mozilla.org/show_bug.cgi?id=1826583)

**Comment by mweinelt** [comment]
Fix has been backported and is targeted for 112.0.2. I expect the release on monday or tuesday.

https://hg.mozilla.org/releases/mozilla-release/rev/94ef9c555302

**Comment by Kiskae** [comment]
Given that the firefox update will end up in `master` and be available fairly quickly, perhaps it would be possible to merge this PR since it has to go through the `staging` -> `staging-next` cycle and be included in the 23.05 release

**Comment by mweinelt** [comment]
Firefox 112.0.2 is already on master.

**Comment by Artturin** [comment]
@ofborg build sway

**Pull request merged**
