### PR TITLE
coq: default to version 8.19

### PR DESCRIPTION
**Pull request by vbgl**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Princemachiavelli — APPROVED** [review]
LGTM, I do not see any other breaking packages besides `why3`.

**Comment by wegank** [comment]
Do we want NixOS 24.05 to ship Coq 8.19 by default? (And also, if there's any release blocker for Coq or OCaml)

**Comment by vbgl** [comment]
> Do we want NixOS 24.05 to ship Coq 8.19 by default?

Sounds like a good idea, to me at least.

> And also, if there's any release blocker for Coq or OCaml

I’m not aware of any such release blocker.

**Review by wegank — APPROVED** [review]

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 307816` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>72 packages built:</summary>
  <ul>
    <li>compcert (coqPackages.compcert)</li>
    <li>compcert.doc (coqPackages.compcert.doc)</li>
    <li>compcert.lib (coqPackages.compcert.lib)</li>
    <li>compcert.man (coqPackages.compcert.man)</li>
    <li>coq (coqPackages.coq)</li>
    <li>coqPackages.Cheerios</li>
    <li>coqPackages.CoLoR</li>
    <li>coqPackages.HoTT</li>
    <li>coqPackages.ITree</li>
    <li>coqPackages.InfSeqExt</li>
    <li>coqPackages.LibHyps</li>
    <li>coqPackages.QuickChick</li>
    <li>coqPackages.StructTact</li>
    <li>coqPackages.VST</li>
    <li>coqPackages.aac-tactics</li>
    <li>coqPackages.bignums</li>
    <li>coqPackages.ceres</li>
    <li>coqPackages.coq-elpi</li>
    <li>coqPackages.coq-ext-lib</li>
    <li>coqPackages.coq-lsp</li>
    <li>coqPackages.coq-record-update</li>
    <li>coqPackages.coqide</li>
    <li>coqPackages.coqprime</li>
    <li>coqPackages.coquelicot</li>
    <li>coqPackages.corn</li>
    <li>coqPackages.deriving</li>
    <li>coqPackages.dpdgraph</li>
    <li>coqPackages.equations</li>
    <li>coqPackages.extructures</li>
    <li>coqPackages.flocq</li>
    <li>coqPackages.fourcolor</li>
    <li>coqPackages.gappalib</li>
    <li>coqPackages.hierarchy-builder</li>
    <li>coqPackages.interval</li>
    <li>coqPackages.iris</li>
    <li>coqPackages.iris-named-props</li>
    <li>coqPackages.itauto</li>
    <li>coqPackages.math-classes</li>
    <li>coqPackages.mathcomp</li>
    <li>coqPackages.mathcomp-algebra</li>
    <li>coqPackages.mathcomp-algebra-tactics</li>
    <li>coqPackages.mathcomp-analysis</li>
    <li>coqPackages.mathcomp-bigenough</li>
    <li>coqPackages.mathcomp-character</li>
    <li>coqPackages.mathcomp-classical</li>
    <li>coqPackages.mathcomp-field</li>
    <li>coqPackages.mathcomp-fingroup</li>
    <li>coqPackages.mathcomp-finmap</li>
    <li>coqPackages.mathcomp-infotheo</li>
    <li>coqPackages.mathcomp-real-closed</li>
    <li>coqPackages.mathcomp-solvable</li>
    <li>coqPackages.ssreflect (coqPackages.mathcomp-ssreflect)</li>
    <li>coqPackages.mathcomp-word</li>
    <li>coqPackages.mathcomp-zify</li>
    <li>coqPackages.metacoq</li>
    <li>coqPackages.metacoq-erasure</li>
    <li>coqPackages.metacoq-pcuic</li>
    <li>coqPackages.metacoq-safechecker</li>
    <li>coqPackages.metacoq-template-coq</li>
    <li>coqPackages.multinomials</li>
    <li>coqPackages.paco</li>
    <li>coqPackages.paramcoq</li>
    <li>coqPackages.parsec</li>
    <li>coqPackages.reglang</li>
    <li>coqPackages.serapi</li>
    <li>coqPackages.simple-io</li>
    <li>coqPackages.stdpp</li>
    <li>coqPackages.vcfloat</li>
    <li>coqPackages.vscoq-language-server</li>
    <li>coqPackages.zorns-lemma</li>
    <li>framac</li>
    <li>satallax</li>
  </ul>
</details>

**Pull request merged**
