### PR TITLE
 minikube: 1.2.0 -> 1.6.2

### PR DESCRIPTION
**Pull request by AtkinsChang**
###### Motivation for this change
Upgrade to [`v1.6.2`](https://github.com/kubernetes/minikube/releases/tag/v1.6.2) and fix bugs in previous version:
- fix building errors and use `buildGoModule` for `docker-machine-kvm2`
- fix `minikube` bugs running on `nixos` cause by `exec /bin/bash` command
- separate `docker-machine-hyperkit` from `minikube` like what `docker-machine-kvm2` did

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by mmahut** [comment]
@GrahamcOfBorg build minikube docker-machine-hyperkit

@GrahamcOfBorg test docker

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by brodul** [comment]
Can we push this forward. The nix pkgs `minikube` is getting old.

**Comment by AtkinsChang** [comment]
I just wonder why there was a `LGTM` from maintainer on Aug 15 but duplicated pr #67242 created on Aug 22 was merged and causes conflicting. Is the issue management principle of this repository FIFO?

**Comment by vdemeester** [comment]
> I just wonder why there was a `LGTM` from maintainer on Aug 15 but duplicated pr #67242 created on Aug 22 was merged and causes conflicting. Is the issue management principle of this repository FIFO?

@AtkinsChang sorry about that :sweat: it's open-source, sometimes a newer PR gets merged before an older one and causes conflicts, it happens :sweat_smile: Can you rebase yours :angel:

**Comment by thmzlt** [comment]
I was able to update 1.2.0 -> 1.5.2 by bumping the minikube version in master (and updating the modSha256):

```patch
diff --git a/pkgs/applications/networking/cluster/minikube/default.nix b/pkgs/applications/networking/cluster/minikube/default.nix
index 5637e486ef1..e107cb98212 100644
--- a/pkgs/applications/networking/cluster/minikube/default.nix
+++ b/pkgs/applications/networking/cluster/minikube/default.nix
@@ -13,7 +13,7 @@ let

 in buildGoModule rec {
   pname   = "minikube";
-  version = "1.2.0";
+  version = "1.5.2";

   kubernetesVersion = "1.15.0";

@@ -26,7 +26,7 @@ in buildGoModule rec {
     sha256 = "0l9znrp49877cp1bkwx84c8lv282ga5a946rjbxi8gznkf3kwaw7";
   };

-  modSha256 = "1cp63n0x2lgbqvvymx9byx48r42qw6w224x5x4iiarc2nryfdhn0";
+  modSha256 = "1spyc71jfa05dyf30q30hjk2lx5w7929jsm3p03gbm6ssvmclfrh";

   buildInputs = [ go-bindata makeWrapper gpgme ] ++ stdenv.lib.optional stdenv.hostPlatform.isDarwin vmnet;
   subPackages = [ "cmd/minikube" ] ++ stdenv.lib.optional stdenv.hostPlatform.isDarwin "cmd/drivers/hyperkit";
```

**Comment by AtkinsChang** [comment]
@vdemeester although it works on my machine, it would be great that you can help to double verify the new version

**Comment by vdemeester** [comment]
@AtkinsChang hum, interesting, I've got a different error that the CI : 

```
error: while evaluating 'callPackageWith' at /home/vincent/.cache/nix-review/pr-6657
8/nixpkgs/lib/customisation.nix:117:35, called from /home/vincent/.cache/nix-review$
pr-66578/nixpkgs/pkgs/top-level/all-packages.nix:18394:31:
while evaluating 'makeOverridable' at /home/vincent/.cache/nix-review/pr-66578/nixpk
gs/lib/customisation.nix:67:24, called from /home/vincent/.cache/nix-review/pr-66578
/nixpkgs/lib/customisation.nix:121:8:
anonymous function at /home/vincent/.cache/nix-review/pr-66578/nixpkgs/pkgs/applicat
ions/networking/cluster/docker-machine/xhyve.nix:1:1 called with unexpected argument
 'minikube', at /home/vincent/.cache/nix-review/pr-66578/nixpkgs/lib/customisation.n
ix:69:16
```

**Comment by AtkinsChang** [comment]
@vdemeester it should be good now

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by flokli** [comment]
Can we drop the minikube-beta commit? There has been some new releases already, and it might make sense to just bump to the latest minikube release in a followup PR.

**Comment by AtkinsChang** [comment]
@flokli 
because this pr keep pending since Aug 2019 and I have rebased this three times

virtualbox driver works well but kvm driver is not working because of `libvirt` bug related to `ebtables`
I may submit another pr to fix `libvirt` this weekend

**Comment by flokli** [comment]
@AtkinsChang sorry for the delay! I can't really test the virtualbox backend anymore.

Did you get a chance to fix the libvirt backend? Missed a reference here.

**Comment by AtkinsChang** [comment]
@flokli  libvirt is good with this version of minikube

**Comment by flokli** [comment]
Unfortunately I couldn't find time to test it properly so far. Thanks @AtkinsChang for the PR, and thanks @Mic92 for merging it! :+1:

**Pull request merged**
