### PR TITLE
spark: Fix tarball hash.

### LINKED ISSUE #13703: Spark Hash Failing
The spark hash on master doesn't match the binary at the URL.

```
building path(s) ‘/nix/store/w7a552hvyai19q35i31xlfijsl14l6i5-spark-1.6.0-bin-cdh4.tgz’

trying http://www.eu.apache.org/dist/spark/spark-1.6.0/spark-1.6.0-bin-cdh4.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  240M  100  240M    0     0  1172k      0  0:03:30  0:03:30 --:--:--  917k
unpacking source archive /tmp/nix-build-spark-1.6.0-bin-cdh4.tgz.drv-0/spark-1.6.0-bin-cdh4.tgz
output path ‘/nix/store/w7a552hvyai19q35i31xlfijsl14l6i5-spark-1.6.0-bin-cdh4.tgz’ has r:sha256 hash ‘19ycx1r8g82vkvzmn9wxkssmv2damrg72yfmrgzpc6xyh071g91c’ when ‘0waq8xx4bjj1yvfbadv1gdvz8s4kh5zasicv2n5623ld6lj7zgad’ was expected
cannot build derivation ‘/nix/store/7hq1lnbav3wk85sb217nxk27dzpiq8an-spark-1.6.0.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/7hq1lnbav3wk85sb217nxk27dzpiq8an-spark-1.6.0.drv’ failed
```

cc: @mboes @samuelrivas

### PR DESCRIPTION
**Pull request by mboes**
Maybe tarball changed upstream. Who knows.

Fixes #13703

### CODE REVIEW

**Comment by mboes** [comment]
cc @kevincox

**Comment by joachifm** [comment]
I downloaded spark from https://www.apache.org/dist/spark/spark-1.6.0/ and it computes the same sha256 as the original (that is, 0waq8xx4bjj1yv). Just a data point.

**Comment by kevincox** [comment]
For me Travis and locally were returning a different hash then the original. Also it might be worth verifying SHAs on sparks website in case the tarball has been modified maliciously.

**Comment by joachifm** [comment]
I computed SHA512 and MD5 for the tarball I downloaded manually (which I also verified with gpg); they match what is published on the server. To me, this looks like the mirror is doing something odd. The tarball at the location I linked has not changed, as far as I can tell.

**Comment by kevincox** [comment]
Is it possible to change the url then?  Travis appears to be downloading from http://www.eu.apache.org/dist/spark/spark-1.6.0/spark-1.6.0-bin-cdh4.tgz which has the error.

**Comment by joachifm** [comment]
Hm, that file also computes the old sha256 for me. Perhaps I'm doing something wrong.

**Comment by kevincox** [comment]
Strange, you can see the build log I am talking about here:
https://travis-ci.org/NixOS/nixpkgs/builds/113994001

Also do local builds work for you?

**Comment by joachifm** [comment]
Ah, spark uses fetchzip, that must be the reason for the discrepancy I'm seeing

**Comment by joachifm** [comment]
Are we sure spark 1.6.0 ever built? If I'm reading hydra correctly, spark has been broken since the update.

**Pull request merged**
