### PR TITLE
opencv: 2.4.13 -> 2.4.13.7

### PR DESCRIPTION
**Pull request by omasanori**
###### Motivation for this change

This change updates OpenCV 2 to the latest version in 2.4 series hosted at `opencv/opencv`.
`opencv2`, `p2pvc` and `pfstools` are built without errors but they are not really tested.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102918` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages marked as broken and skipped:</summary>
  <ul>
    <li>mathematica</li>
    <li>mathematica10</li>
    <li>mathematica11</li>
    <li>mathematica9</li>
    <li>opencv2</li>
    <li>p2pvc</li>
    <li>pfstools</li>
  </ul>
</details>

**Comment by alyssais** [comment]
Should this be removed?

https://github.com/NixOS/nixpkgs/blob/f1d3f6b2ca2617d770c7ef1c32dbdfddd186c958/pkgs/development/libraries/opencv/default.nix#L90

**Comment by omasanori** [comment]
@alyssais Ah, yes, if `broken` means `fails to build` then this commit unbreak it. I will revise the PR. Thank you for the suggestion.

**Comment by LEXUGE** [comment]
LGTM

**Pull request merged**
