### PR TITLE
python3Packages.qiskit: 1.0.1 -> 1.1.1

### PR DESCRIPTION
**Pull request by b-m-f**
## Description of changes

Qiskit has seen some major changes, here is the blog post for [1.0](https://docs.quantum.ibm.com/api/qiskit/release-notes/1.0#100).

The previous build strategy had to be updated. Due to a limitation in one of the dependencies, this derivation does not currently build on Python 3.12.

A Github issue for this is open at https://github.com/NixOS/nixpkgs/issues/306328.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Aleksanaa — COMMENTED** [review]
Please reword to `python3Packages.qiskit: 1.0.1 -> 1.1.1`.

**Comment by SimShady** [comment]
I installed qiskit with your file. Build ran successfully but when importing qiskit I got the following:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/nbzg7zipxa3g325ivhjnb5zs2wdkhjs4-python3-3.11.9-env/lib/python3.11/site-packages/qiskit/__init__.py", line 89, in <module>
    from qiskit.circuit import ClassicalRegister
  File "/nix/store/nbzg7zipxa3g325ivhjnb5zs2wdkhjs4-python3-3.11.9-env/lib/python3.11/site-packages/qiskit/circuit/__init__.py", line 1237, in <module>
    from . import library
  File "/nix/store/nbzg7zipxa3g325ivhjnb5zs2wdkhjs4-python3-3.11.9-env/lib/python3.11/site-packages/qiskit/circuit/library/__init__.py", line 494, in <module>
    from .generalized_gates import (
  File "/nix/store/nbzg7zipxa3g325ivhjnb5zs2wdkhjs4-python3-3.11.9-env/lib/python3.11/site-packages/qiskit/circuit/library/generalized_gates/__init__.py", line 22, in <module>
    from .linear_function import LinearFunction
  File "/nix/store/nbzg7zipxa3g325ivhjnb5zs2wdkhjs4-python3-3.11.9-env/lib/python3.11/site-packages/qiskit/circuit/library/generalized_gates/linear_function.py", line 19, in <module>
    from qiskit.synthesis.linear import check_invertible_binary_matrix
  File "/nix/store/nbzg7zipxa3g325ivhjnb5zs2wdkhjs4-python3-3.11.9-env/lib/python3.11/site-packages/qiskit/synthesis/__init__.py", line 126, in <module>
    from .evolution import (
  File "/nix/store/nbzg7zipxa3g325ivhjnb5zs2wdkhjs4-python3-3.11.9-env/lib/python3.11/site-packages/qiskit/synthesis/evolution/__init__.py", line 17, in <module>
    from .product_formula import ProductFormula
  File "/nix/store/nbzg7zipxa3g325ivhjnb5zs2wdkhjs4-python3-3.11.9-env/lib/python3.11/site-packages/qiskit/synthesis/evolution/product_formula.py", line 20, in <module>
    from qiskit.quantum_info import SparsePauliOp, Pauli
  File "/nix/store/nbzg7zipxa3g325ivhjnb5zs2wdkhjs4-python3-3.11.9-env/lib/python3.11/site-packages/qiskit/quantum_info/__init__.py", line 116, in <module>
    from .analysis import hellinger_distance, hellinger_fidelity, Z2Symmetries
  File "/nix/store/nbzg7zipxa3g325ivhjnb5zs2wdkhjs4-python3-3.11.9-env/lib/python3.11/site-packages/qiskit/quantum_info/analysis/__init__.py", line 17, in <module>
    from .z2_symmetries import Z2Symmetries
  File "/nix/store/nbzg7zipxa3g325ivhjnb5zs2wdkhjs4-python3-3.11.9-env/lib/python3.11/site-packages/qiskit/quantum_info/analysis/z2_symmetries.py", line 26, in <module>
    from ..operators import Pauli, SparsePauliOp
  File "/nix/store/nbzg7zipxa3g325ivhjnb5zs2wdkhjs4-python3-3.11.9-env/lib/python3.11/site-packages/qiskit/quantum_info/operators/__init__.py", line 18, in <module>
    from .measures import average_gate_fidelity, diamond_norm, gate_error, process_fidelity
  File "/nix/store/nbzg7zipxa3g325ivhjnb5zs2wdkhjs4-python3-3.11.9-env/lib/python3.11/site-packages/qiskit/quantum_info/operators/measures.py", line 27, in <module>
    from qiskit.quantum_info.states.densitymatrix import DensityMatrix
  File "/nix/store/nbzg7zipxa3g325ivhjnb5zs2wdkhjs4-python3-3.11.9-env/lib/python3.11/site-packages/qiskit/quantum_info/states/__init__.py", line 16, in <module>
    from .statevector import Statevector
  File "/nix/store/nbzg7zipxa3g325ivhjnb5zs2wdkhjs4-python3-3.11.9-env/lib/python3.11/site-packages/qiskit/quantum_info/states/statevector.py", line 28, in <module>
    from qiskit.quantum_info.states.quantum_state import QuantumState
  File "/nix/store/nbzg7zipxa3g325ivhjnb5zs2wdkhjs4-python3-3.11.9-env/lib/python3.11/site-packages/qiskit/quantum_info/states/quantum_state.py", line 27, in <module>
    from qiskit.result.counts import Counts
  File "/nix/store/nbzg7zipxa3g325ivhjnb5zs2wdkhjs4-python3-3.11.9-env/lib/python3.11/site-packages/qiskit/result/__init__.py", line 62, in <module>
    from .result import Result
  File "/nix/store/nbzg7zipxa3g325ivhjnb5zs2wdkhjs4-python3-3.11.9-env/lib/python3.11/site-packages/qiskit/result/result.py", line 19, in <module>
    from qiskit.pulse.schedule import Schedule
  File "/nix/store/nbzg7zipxa3g325ivhjnb5zs2wdkhjs4-python3-3.11.9-env/lib/python3.11/site-packages/qiskit/pulse/__init__.py", line 65, in <module>
    from qiskit.pulse.builder import (
  File "/nix/store/nbzg7zipxa3g325ivhjnb5zs2wdkhjs4-python3-3.11.9-env/lib/python3.11/site-packages/qiskit/pulse/builder.py", line 445, in <module>
    from typing_extensions import Unpack
ModuleNotFoundError: No module named 'typing_extensions'
```

Adding `typing_extensions` to the dependencies fixes the issue

**Comment by b-m-f** [comment]
@SimShady could you push a commit to this PR with the fix?

**Comment by SimShady** [comment]
> @SimShady could you push a commit to this PR with the fix?

Seems like I lack permissions to do that:

```
ERROR: Permission to b-m-f/nixpkgs.git denied to SimShady.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
 Let me know if I am doing something wrong, I am quite new in contributing to open source

**Comment by b-m-f** [comment]
@SimShady seems like the error is on my end, sorry.
Unfortunately I will not be able to get to fixing this until late October

**Pull request closed without merging**
