### PR TITLE
Aaron unstable

### PR DESCRIPTION
**Pull request by danwwagner**

### CODE REVIEW

**Comment by copumpkin** [comment]
Can you elaborate on what's going on here? No description, a bunch of commits that don't merge cleanly, and no obvious unifying theme to the commits.

**Comment by danwwagner** [comment]
Honestly, I have no idea what the hell all that is.  I was just on GitHub today for a school project in a private repository of a classmate, and your repository was not linked to my account.



Dan Wagner
Junior in Computer Engineering
KSURCT Treasurer


________________________________

**Comment by danwwagner** [comment]
Go ahead and delete this: the university club was demoing GitHub and my account was the last one signed in -- Blame Aaron.

**Comment by copumpkin** [comment]
Alright, thanks. See if Aaron wants to submit proper PRs for his work, since we always welcome contributions :smile:

**Pull request closed without merging**
