### PR TITLE
python3Packages.transformers: fix pytorch reference

### PR DESCRIPTION
**Pull request by jonringer**
###### Description of changes

fix nixpkgs-review eval

related: https://github.com/NixOS/nixpkgs/pull/175086

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
```
Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/175438

$ /nix/store/q3zmh3is1hxpvnw0w8bm1wvis6q8aijv-nix-2.6.1/bin/nix-shell /home/jon/.cache/nixpkgs-review/pr-175438/shell.nix
these 3 paths will be fetched (0.45 MiB download, 2.58 MiB unpacked):
  /nix/store/d4dlj29hjpz8skfsvyyrrcrv0sw2l3wz-bash-interactive-5.1-p16-info
  /nix/store/nq5ab1d4yf0njq9kz6dyybni4fd3b3jz-bash-interactive-5.1-p16-doc
  /nix/store/yjgdgysbfm79s3a5xjawcvz2qyfgpiw6-bash-interactive-5.1-p16-dev
copying path '/nix/store/nq5ab1d4yf0njq9kz6dyybni4fd3b3jz-bash-interactive-5.1-p16-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/d4dlj29hjpz8skfsvyyrrcrv0sw2l3wz-bash-interactive-5.1-p16-info' from 'https://cache.nixos.org'...
copying path '/nix/store/yjgdgysbfm79s3a5xjawcvz2qyfgpiw6-bash-interactive-5.1-p16-dev' from 'https://cache.nixos.org'...
gpg-connect-agent: connection to the agent is in restricted mode

[nix-shell:~/.cache/nixpkgs-review/pr-175438]$
```

**Comment by jonringer** [comment]
going to merge once ofborg is green, as this is blocking me reviewing other PRs

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 175438` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.spacy-transformers</li>
    <li>python310Packages.transformers</li>
    <li>python39Packages.spacy-transformers</li>
    <li>python39Packages.transformers</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
Change looks good to me.

**Pull request merged**
