### PR TITLE
.github/workflows/update-terraform-providers.yml: disable

### PR DESCRIPTION
**Pull request by zowoq**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

> https://registry.terraform.io/terms
> You may download providers, modules, policy libraries and/or other Services or Content from this website solely for use with, or in support of, HashiCorp Terraform. You may download or copy the Content (and other items displayed on the Services for download) for personal non-commercial use only, provided that you maintain all copyright and other notices contained in such Content. You shall not store any significant portion of any Content in any form.

@zimbatm I think we need to change the provider packaging/scripts so it doesn't use the registry. I'll look at doing that but until it's done I want to turn off the auto updates. I plan to merge this before the next update run in ~13 hours.

### CODE REVIEW

**Comment by zimbatm** [comment]
We're doing this as a non-profit, and specifically to use with Terraform. It seems to be in line with what they are asking.

**Comment by zowoq** [comment]
Even if we are okay now I don't want to have to keep checking if they've changed their terms again. I think we'll end up having to change how we handle these providers eventually, may as well do it before it becomes an issue.

**Comment by natsukium** [comment]
Isn't the trigger set to `on: push` by default?
This workflow runs for every push since this PR was merged.🙃
https://github.com/NixOS/nixpkgs/actions/workflows/update-terraform-providers.yml

**Comment by zowoq** [comment]
Sorry, fixed in https://github.com/NixOS/nixpkgs/pull/252674

**Pull request merged**
