### PR TITLE
mxu11x0: 1.3.11 -> 1.3.11+git2017-07-13

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Motivation for this change
#28643 

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by globin** [comment]
Please use `+git20XX-XX-XX` instead of `-1`, this otherwise makes it a pre-release per semver.

**Comment by NeQuissimus** [comment]
@globin Like so?

**Comment by Mic92** [comment]
Fails to build for me:

```
/nix/store/48b4c1zjl5b8l2f70q9hav9kyr7gbwga-linux-3.18.0-dev/lib/modules/3.18.0/source/arch/x86/Makefile:114: stack-protector enabled but compiler support broken
In file included from /nix/store/48b4c1zjl5b8l2f70q9hav9kyr7gbwga-linux-3.18.0-dev/lib/modules/3.18.0/source/include/linux/compiler.h:54:0,
                 from /nix/store/48b4c1zjl5b8l2f70q9hav9kyr7gbwga-linux-3.18.0-dev/lib/modules/3.18.0/source/include/linux/linkage.h:4,
                 from /nix/store/48b4c1zjl5b8l2f70q9hav9kyr7gbwga-linux-3.18.0-dev/lib/modules/3.18.0/source/include/linux/kernel.h:6,
                 from /tmp/nix-build-mxu11x0-1.3.11+git2017-07-13-3.18.0.drv-0/mxu11x0-cbbb5ec2045939209117cb5fcd6c7c23bcc109ef-src/driver/mxu11x0.c:20:
/nix/store/48b4c1zjl5b8l2f70q9hav9kyr7gbwga-linux-3.18.0-dev/lib/modules/3.18.0/source/include/linux/compiler-gcc.h:107:30: fatal error: linux/compiler-gcc6.h: No such file or directory
 #include gcc_header(__GNUC__)
compilation terminated.
make[5]: *** [/nix/store/48b4c1zjl5b8l2f70q9hav9kyr7gbwga-linux-3.18.0-dev/lib/modules/3.18.0/source/scripts/Makefile.build:264: /tmp/nix-build-mxu11x0-1.3.11+git2017-07-13-3.18.0.drv-0/mxu11x0-cbbb5ec2045939209117cb5fcd6c7c23bcc109ef-src/driver/mxu11x0.o] Error 1
make[4]: *** [/nix/store/48b4c1zjl5b8l2f70q9hav9kyr7gbwga-linux-3.18.0-dev/lib/modules/3.18.0/source/Makefile:1398: _module_/tmp/nix-build-mxu11x0-1.3.11+git2017-07-13-3.18.0.drv-0/mxu11x0-cbbb5ec2045939209117cb5fcd6c7c23bcc109ef-src/driver] Error 2
make[3]: *** [Makefile:145: sub-make] Error 2
make[2]: *** [Makefile:24: __sub-make] Error 2
make[1]: *** [Makefile:35: module] Error 2
make: *** [Makefile:5: driver_make] Error 2
```

[build.txt](https://github.com/NixOS/nixpkgs/files/1259447/build.txt)

There is no gcc6 header in this file, so we might need newer linux headers.

**Comment by NeQuissimus** [comment]
@Mic92 3.18? How do you manage to get a 3.18 kernel? :D I thought all the old ones had been kicked out...

**Comment by Mic92** [comment]
pkgs/os-specific/linux/kernel/linux-chromiumos-3.18.nix

**Comment by Mic92** [comment]
I used my nix review script to build all changed packages.

**Comment by NeQuissimus** [comment]
Ahhhh... The one kernel I did not try xD

**Comment by Mic92** [comment]
you can also disable builds for older kernel.

**Comment by NeQuissimus** [comment]
That or we use gcc5 for 3.18?

**Comment by Mic92** [comment]
Sounds better.

**Pull request merged**
