### PR TITLE
linux-hardened: Do not block channel

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Motivation for this change
#102974
Do not block channel when the hardened kernels do not apply, we have had multiple issues recently.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by andersk** [comment]
Should we remove nixos.tests.hardened too?

**Comment by NeQuissimus** [comment]
@andersk No, I use the tests when I update things :)
The patches you pushed should also allow us to point the hardened kernel at 5.9, right?

**Comment by andersk** [comment]
Er to be clear, my question is whether we should remove nixos.tests.hardened from  nixos/release-combined.nix, for the same reason you’ve removed nixos.tests.latestKernel.hardened from nixos/release-combined.nix. (I’m not saying delete the tests themselves.)

**Comment by NeQuissimus** [comment]
Oh, I misunderstood! Yes, we should :)

**Review by andersk — APPROVED** [review]

**Pull request merged**
