### PR TITLE
surge-XT: 1.2.3 -> 1.3.1

### PR DESCRIPTION
**Pull request by magnetophon**
The VST3 and the standalone work as expected, but the LV2 instrument doesn't show up in Ardour, not even as a failed load:

image

In the picture are:
- the 1.2.3 instrument and FX for both LV2 and VST3 an
- the 1.3.1 instrument and FX for VST3
- the 1.3.1 FX for LV2
But not the 1.3.1 instrument for LV2.

Any ideas?

Ping @orivej @luzpaz 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by luzpaz** [comment]
cc @baconpaul  
any idea ?

**Comment by baconpaul** [comment]
No. We have generally had bad luck with the lv2 in juce 7 though

**Comment by magnetophon** [comment]
@baconpaul So maybe NixOS should just drop the lv2 for now?

**Comment by baconpaul** [comment]
It works in some hosts

we had dropped the lv2 for 130 for this reason and Linux users were sad so we put it back in our 131 even though it works imperfectly

**Comment by baconpaul** [comment]
Dunno! I never use lv2 but Linux folks say it works and is useful. Maybe Carla? Or jalv? Or reaper perhaps?

**Comment by orivej** [comment]
> Any ideas?

It works for me:

image

image

Does it show up in Carla? Try `carla-single lv2 https://surge-synthesizer.github.io/lv2/surge-xt`

**Review by orivej — APPROVED** [review]

**Comment by baconpaul** [comment]
Is there anything we can do to make that about screen version number better?

Glad it works!

**Comment by orivej** [comment]
(The about screen version is currently `1.3.git-no-branch.git-no-commit`)

**Comment by orivej** [comment]
@magnetophon I'm not sure that this will help, but in order to test lv2 I just install it systemwise, so I don't have different versions of the same plugin in different locations. `nixos-rebuild test` is useful for that.

**Comment by orivej** [comment]
If we fetch the sources with `leaveDotGit = true` and add `gitMinimal` to `nativeBuildInputs`, then the version would be `1.3.fetchgit.4b53827`. If we also override the local branch name with `branchName = "release-xt/${version}";`, then the version becomes `1.3.1.4b53827`

Alternatively we can generate `VERSION_GIT_INFO` for `cmake/versiontools.cmake` like this:
```
  preConfigure = let git-info = ''
    # git info generated by nixpkgs
    release-xt/${version}
    ${src.rev}
  ''; in ''
    echo "${git-info}" >VERSION_GIT_INFO
  '';
```
Then the version becomes `1.3.1.release_xt_1.3.1`.

@baconpaul, which should be preferred?

**Comment by baconpaul** [comment]
In an ideal world 1.3.1.hash is best, or 1.3.1.(something indicating nixos build) would be ideal

**Comment by orivej** [comment]
@magnetophon, could you apply https://github.com/orivej/nixpkgs/commit/27959eccfed073a5b16d1c6167971da2a3df4bee to this PR? The version becomes `1.3.1.4b53827`

**Comment by magnetophon** [comment]
Thanks @baconpaul and @orivej !

**Review by orivej — APPROVED** [review]

**Comment by luzpaz** [comment]
soft bump

**Comment by jansol** [comment]
Did they silently bump the version tag? I'm getting a hash mismatch now on nixos-unstable.

**Comment by tobiasBora** [comment]
@jansol same error here, just reported https://github.com/NixOS/nixpkgs/issues/293558

**Comment by magnetophon** [comment]
I'm a bit confused with all the different comments.
Could someone summarize what the best way forward is?

**Comment by tobiasBora** [comment]
@magnetophon basically remove the `leaveDotGit` and the git dependency, and update the hash. Git is only used to fetch one skin (the external repo listed in the cmake file contains many more skins, but surge pins an old version containing a single skin) that might not be very helpful anyway… or if you  want to preserve the skin, you can also manually install that skin by just fetching it and copying it in the right folder at the end in `$out/share/surge-xt/skins/`.

**Comment by magnetophon** [comment]
@tobiasBora Thanks!  PR here, hope I got it right!
https://github.com/NixOS/nixpkgs/pull/296917

**Pull request merged**
