### PR TITLE
nixos/bcachefs: RFC: implement bcachefs-askpass

### PR DESCRIPTION
**Pull request by chayleaf**
## Description of changes

I don't have physical access to one of my machines most of the time, and getting it is extremely annoying. So I have to do most boot maintenance from initrd using SSH, including switching generations and filesystem unlocking. The LUKS module currently implements cryptsetup-askpass, which uses a ramfs to communicate between the user and the init script. The bcachefs module doesn't do that (it looks like the systemd unit uses systemd-ask-password, but I really really really don't want to switch to systemd initrd right now).

Additionally, this leaves a lot of room for code deduplication between LUKS and bcachefs, and potentially any other encrypted filesystems - all of them could get feature parity with LUKS (which currently implements e.g. Yubikey/GPG) for free. Currently I didn't copy the advanced features, but nothing prevents me from doing that.

Unfortunately I haven't tested this yet, I'm just sending this to receive general feedback.

Also, this patch doesn't touch systemd initrd yet as I'm not familiar with it.

For reference, [here's](https://github.com/NixOS/nixpkgs/blob/ab69fd9bc08e87ab1e96c6c13d45d66762830c17/nixos/modules/system/boot/luksroot.nix) the LUKS code

CC @davidak @Madouura @PedroHLC @RaitoBezarius @YellowOnion @Mic92 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Mic92** [comment]
I don't want to derail the discussion into systemd initrd support discussion, so here just two things I noticed:
1. It's actually so much cleaner for the remote unlocking case compared to the shell hackery we had before. Now I can just copy the networkd configuration from the normal system into the initrd and all I have to do for zfs to unlock is `echo ${pw} | systemd-tty-ask-password-agent`, which will also kill the interactive prompt on the screen that asks for the password (Here is my migration: https://github.com/Mic92/dotfiles/commit/503dba35bbce55aa077cb334b64eb08840cf2f6d#diff-5bc10e0ffc9022d5ae336b07ab2e74988ba86f799852ce65eaa660688be515b4L48)
2. To implement it one can just create a normal systemd service and than later move it to the initrd (this is how zfs does it https://github.com/NixOS/nixpkgs/blob/eee4c95a6e4372d714ce968386d00bbcf466169c/nixos/modules/tasks/filesystems/zfs.nix#L115).

**Comment by chayleaf** [comment]
fair enough, if scripted initrd is in maintenance mode, I'll just close this

**Comment by onny** [comment]
so is bcachefs already supported for remote unlocking? if not is there any open PR or issue for it?

**Comment by Mic92** [comment]
I am not aware of any.

**Pull request closed without merging**
