### PR TITLE
 nixos/libinput: move out of xserver 

### PR DESCRIPTION
**Pull request by SuperSandro2000**
## Description of changes

From the maker of "Make SDDM wayland only possible".

I am slowly working torwards removing xserver from my config. This time libinput is being changed.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

---

cc @alois31

### CODE REVIEW

**Review by Shawn8901 — APPROVED** [review]
picked that to my fork, used that some days, also checked on my notebook, diff wise i just can see renaming, havent changed anything on my end, dont see eval errors or so.
have just tested with plasma6
so i guess lgtm.

**Review by alois31 — APPROVED** [review]
Plasma (both versions), GNOME and XFCE tests still build successfully. My system configuration works too, and the diff looks sane as well.

**Comment by SuperSandro2000** [comment]
I've locally rebased this PR and didn't find any manual build issues or found new occurrences of the old settings path.

**Review by jtojnar — COMMENTED** [review]
This module is mostly xserver stuff. We should probably revert this change and create a new module that does just the udev install.

**Comment by SuperSandro2000** [comment]
Reverting this will be a big mess. We can just move the remaining xorg stuff into lib.mkIf or move it into xserver

**Comment by SuperSandro2000** [comment]
please see #308777

**Comment by jtojnar** [comment]
How would it be more a mess than interleaving bunch of old code? Moving the legacy stuff to xserver specific module would be cleaner. And the option names should probably reflect that the options are X server specific – it would be more explicit than hidden inside description.

Also, I am not even sure if the X11 configs are used on X11 at all. At least on GNOME, I believe the compositor controls libinput so I would not be surprised if the X11 files were ignored even on XServer.

**Comment by SuperSandro2000** [comment]
> Moving the legacy stuff to xserver specific module would be cleaner.

Having the options split between multiple areas is not really cleaner instead of having it all together for libinput.

> Also, I am not even sure if the X11 configs are used on X11 at all. At least on GNOME

Gnome is strange, I remember that it at least worked on Plasma5 a while ago.

**Comment by GetPsyched** [comment]
Shouldn't this change have received approvals from committers before merging? Or rather have discussion/be merged by someone else? I'm not contesting the change itself but rather the lack of much discussion on changing of options in a module for everyone.

**Comment by MrQubo** [comment]
Does this mean it's possible to configure libinput on wayland with this module?

**Comment by SuperSandro2000** [comment]
It should be but please provide feedback if things actually work or not.

**Pull request merged**
