### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
I saw around 50k jobs "Cancelled by user" but I found no indication why (some other work for Hydra, newer staging-next commits, a comment somewhere), so I restarted them.  Over years I've seen multiple instances of this status getting created without manual interaction, so perhaps it was one of those.

**Comment by FRidh** [comment]
I just noticed it as well, but I think it may be @jtojnar who cancelled them because of the fontconfig change that was merged after the evaluation.

**Comment by vcunat** [comment]
Ah, so I assume that new evaluation was there already but noone restarted the jobs shared by the two of them...

**Comment by FRidh** [comment]
Right, I forgot that as well when I created a new eval.

**Comment by jtojnar** [comment]
Sorry, did not notice this PR. Yeah, I cancelled the builds and triggered a new eval (mentioned on `#nixos-dev`) and did not realize that new eval will not restart the cancelled builds.

**Comment by vcunat** [comment]
For reference, there's a handy "restart aborted" button which *won't* restart builds that were attempted and failed.

**Comment by FRidh** [comment]
Darwin-stdenv does not build https://github.com/NixOS/nixpkgs/pull/95910#issuecomment-687601668 because of texinfo change.

**Comment by pbogdan** [comment]
I can't seem to be able to find it on Hydra but FWIW building `stdenv` shows that `cmake-boot` is also broken on Darwin.

I ran a bisect which pointed to https://github.com/NixOS/nixpkgs/pull/93560 but I don't really understand the changes (or know anything about Darwin) to know how to fix it (other than reverting those changes completely).

**Comment by FRidh** [comment]
> I ran a bisect which pointed to #93560 but I don't really understand the changes (or know anything about Darwin) to know how to fix it (other than reverting those changes completely).

If reverting that change makes darwin build again, then that's good enough at this point.

**Comment by pbogdan** [comment]
Yes, I reverted the change locally and `cmake-boot` now succeeds. I'm trying to build a full stdenv but it will take hours on my hardware (currently chewing through the `stage3-stdenv` stuff).

**Comment by pbogdan** [comment]
Can confirm Darwin `stdenv` builds with https://github.com/NixOS/nixpkgs/pull/93560 reverted, haven't built non-bootstrap `cmake` yet.

**Comment by pbogdan** [comment]
> haven't built non-bootstrap `cmake` yet

It builds as well with the revert.

**Comment by FRidh** [comment]
Thanks for testing. Ugly work-around reverting the PR for Darwin https://github.com/NixOS/nixpkgs/pull/97296.

**Comment by pbogdan** [comment]
@FRidh It looks like we may need to apply your to change to cc-wrapper as well at least (there is a fortran wrapper too I think but not sure how important that is), currently `cmake-boot` still won't build.

**Comment by vcunat** [comment]
[Haskell boostrap on aarch64](https://hydra.nixos.org/build/126391821) is broken.  I can't see any relevant change (since master where it works), and I can reproduce the segfault on [the shared box](https://github.com/nix-community/aarch64-build-box).

Still, I don't think we should block merge to master because of this, in our situation.

**Review by vcunat — APPROVED** [review]
After a few thousand [rebuilt darwin packages](https://hydra.nixos.org/eval/1611852?filter=x86_64-darwin&compare=1611836), I believe we're good enough to merge... at least in our dire situation.

**Comment by vcunat** [comment]
The tested job [succeeded on Hydra](https://hydra.nixos.org/build/126594337)  :tada:  Thanks to everyone who's helped; this staging iteration wasn't easy at all.

**Pull request merged**
