### PR TITLE
wpa_supplicant: 2.7 -> 2.8

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

Testing with your wireless card appreciated!

I've been using iwd :3 but will give this a go later--
regardless it'd be good to avoid breaking too many folks' wireless! :)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
cc #60053

**Comment by worldofpeace** [comment]
Runtime testing this currently. Looks good so far (even resolved some issues).

**Comment by hedning** [comment]
Should probably be backported: https://github.com/NixOS/nixpkgs/issues/60117

**Review by primeos — APPROVED** [review]
> Testing with your wireless card appreciated!

Works on my system (Dell XPS 13 with Qualcomm Atheros QCA6174) :)
I've tested it on a WPA2-Personal and WPA2-Enterprise network and `wpa_cli` still works as well.

**Comment by worldofpeace** [comment]
change for 19.03 for the vulnerabilities btw https://github.com/NixOS/nixpkgs/pull/60143

**Review by NeQuissimus — APPROVED** [review]

**Review by worldofpeace — APPROVED** [review]

**Pull request merged**
