### PR TITLE
xbill, motif: fix clang build

### PR DESCRIPTION
**Pull request by paparodeo**
*needs backport release-24.05 tag*
## Description of changes

motif:
ignore benign clang errors implicit-function-declaration and incompatible-function-pointer-types

xbill depends on motif but was also broken with clang is fixed as well:
ignore implicit-function-declaration errors and regenerate autotools files so configure test programs compile with clang

https://hydra.nixos.org/build/260342733
ZHF: https://github.com/NixOS/nixpkgs/issues/309482

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by paparodeo** [comment]
Result of `nixpkgs-review pr 314766` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>cernlib</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>catclock</li>
    <li>motif</li>
    <li>nedit</li>
    <li>snd</li>
    <li>xbill</li>
  </ul>
</details>

---

Result of `nixpkgs-review pr 314766` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>xbill</li>
  </ul>
</details>

**Comment by alyssais** [comment]
Are you sure they're benign? My understanding is that they'll only be benign if all implicitly declared functions return int, and take int for all arguments (or at least an equally sized type).  (There's a reason Clang has made this an error by default.)

The right way to fix this would be to make sure there aren't any implicitly defined functions.  I did that for Linux in #302635, but apparently it still needs some work for macOS.

**Comment by paparodeo** [comment]
> Are you sure they're benign? My understanding is that they'll only be benign if all implicitly declared functions return int, and take int for all arguments (or at least an equally sized type). (There's a reason Clang has made this an error by default.)
> 
> The right way to fix this would be to make sure there aren't any implicitly defined functions. I did that for Linux in #302635, but apparently it still needs some work for macOS.

i did build on linux with clangStdenv for motif and xbill and implicit functions are usually due to missing the string.h and the warning is also present when compiling with gcc so it doesn't seem like it is fixed on linux but has the same issue. so yes, i believe that the behaviour for gcc and clang is now identical, as they are both ignoring the error.

**Comment by paparodeo** [comment]
ah, i see that https://github.com/NixOS/nixpkgs/pull/302635 is still open. then closing this.

**Pull request closed without merging**
