### PR TITLE
rmapi: init at 0.0.11

### PR DESCRIPTION
**Pull request by NickHu**
###### Motivation for this change

Add the [rMAPI](https://github.com/juruen/rmapi) tool.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
Please switch to `vendorSha256`, this should fix also the CI error.

**Comment by doronbehar** [comment]
Oh I see you commented at https://github.com/ryantm/nixpkgs-update/issues/203, I think it'll work out for you if you'd not only rename the variable `modSha256` to `vendorSha256`, but also zero it out before you rerun `nix-build`.

**Comment by doronbehar** [comment]
This works:

```
diff --git i/pkgs/applications/misc/remarkable/rmapi/default.nix w/pkgs/applications/misc/remarkable/rmapi/default.nix
index 66be455a040..0fe0e03060a 100644
--- i/pkgs/applications/misc/remarkable/rmapi/default.nix
+++ w/pkgs/applications/misc/remarkable/rmapi/default.nix
@@ -11,7 +11,7 @@ buildGoModule rec {
     sha256 = "0zks1pcj2s2pqkmw0hhm41vgdhfgj2r6dmvpsagbmf64578ww349";
   };
 
-  modSha256 = "0w2qiafs5gkgv00yz16bx8yis6gnpxbgqliwrhj5k6z8yy9s7b17";
+  vendorSha256 = "077s13pcql5w2m6wzls1q06r7p501kazbwzxgfh6akwza15kb4is";
 
   meta = with stdenv.lib; {
     description = "A Go app that allows access to the ReMarkable Cloud API programmatically";
```

**Comment by doronbehar** [comment]
@Enteee, personally, I like this PR much more then yours - it's just so much cleaner and regular. I think I've sort of understood now what was your motivation behind the IFD thing, it's just that I didn't catch initially that you tried to push Nix support upstream at https://github.com/juruen/rmapi/pull/78 .

Never the less, I'm still a bit puzzled - almost every Go app that we ship doesn't include `default.nix`, `shell.nix` and all of those files, and most people seem happy about it. Even packages which do have these files and naturally are maintained both upstream and downstream by Nixpkgs contributors, are not packaged using IFD hooks such as you want to apply in #74657. Examples: https://github.com/NixOS/nixpkgs/search?q=maintainers.mic92&unscoped_q=maintainers.mic92

I think you'll like the yet unstable feature flakes - https://github.com/NixOS/rfcs/pull/49 . When it'll stabilized, it'll be possible to do cool stuff like you tried in #74657 with less workarounds.

**Comment by NickHu** [comment]
@doronbehar Oh nice it works now. I wonder why it gave me an empty output before (even though the build log appeared to get all the dependencies and actually compile it). Nonetheless I've updated it so i think it ought to be good to go

**Review by doronbehar — APPROVED** [review]
Passes build and appears to be running as should.

**Review by Enteee — APPROVED** [review]
looks good

**Pull request merged**
