### PR TITLE
pythonPackages.cntk: mark as broken with python 3.7

### PR DESCRIPTION
**Pull request by markuskowa**
###### Motivation for this change
The CNTK python module seems to be broken since November 2018 (does not recognize swig).
Mark it as broken.

Needs back port to 19.03 (https://github.com/NixOS/nixpkgs/issues/56826)

CC @costrouc @abbradar 
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dotlambda** [comment]
Since https://github.com/NixOS/nixpkgs/pull/54182, swig needs to be in `nativeBuildInputs`.

**Comment by markuskowa** [comment]
@dotlambda thanks for the tip. It does find `swig` now but fails at later stage with a different error.

**Comment by dotlambda** [comment]
It fails with
> unable to execute 'mpic++': No such file or directory

because openmpi isn't in `nativeBuildInputs`. However, I'm not sure if that one should remain in `buildInputs` too.

**Comment by markuskowa** [comment]
OK, that solves the `mpic++` error but then we get the next error:
```
ImportError: cannot import name 'GenericMeta' from 'typing'
```

openmpi should probably remain in `buildInputs` since it is also a run time dependency.

**Comment by markuskowa** [comment]
I restricted the broken attribute to python 3.7

@GrahamcOfBorg build python27Packages.cntk
@GrahamcOfBorg build python36Packages.cntk

**Comment by dotlambda** [comment]
> I restricted the broken attribute to python 3.7

Perfect!

**Comment by markuskowa** [comment]
Thanks for the fixes!

**Pull request merged**
