### PR TITLE
Dialog updates

### PR DESCRIPTION
**Pull request by AndersonTorres**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cafkafk** [comment]
Result of `nixpkgs-review pr 260111` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>icesl</li>
  </ul>
</details>
<details>
  <summary>38 packages built:</summary>
  <ul>
    <li>certbot (python310Packages.certbot)</li>
    <li>certbot-full</li>
    <li>certbot.dist (python310Packages.certbot.dist)</li>
    <li>debian-goodies</li>
    <li>dialog</li>
    <li>gammu</li>
    <li>kabeljau</li>
    <li>protonvpn-cli</li>
    <li>protonvpn-cli.dist</li>
    <li>protonvpn-cli_2</li>
    <li>protonvpn-cli_2.dist</li>
    <li>python310Packages.certbot-dns-cloudflare</li>
    <li>python310Packages.certbot-dns-cloudflare.dist</li>
    <li>python310Packages.certbot-dns-google</li>
    <li>python310Packages.certbot-dns-google.dist</li>
    <li>python310Packages.certbot-dns-inwx</li>
    <li>python310Packages.certbot-dns-inwx.dist</li>
    <li>python310Packages.certbot-dns-rfc2136</li>
    <li>python310Packages.certbot-dns-rfc2136.dist</li>
    <li>python310Packages.certbot-dns-route53</li>
    <li>python310Packages.certbot-dns-route53.dist</li>
    <li>python310Packages.python-gammu</li>
    <li>python310Packages.python-gammu.dist</li>
    <li>python311Packages.certbot</li>
    <li>python311Packages.certbot-dns-cloudflare</li>
    <li>python311Packages.certbot-dns-cloudflare.dist</li>
    <li>python311Packages.certbot-dns-google</li>
    <li>python311Packages.certbot-dns-google.dist</li>
    <li>python311Packages.certbot-dns-inwx</li>
    <li>python311Packages.certbot-dns-inwx.dist</li>
    <li>python311Packages.certbot-dns-rfc2136</li>
    <li>python311Packages.certbot-dns-rfc2136.dist</li>
    <li>python311Packages.certbot-dns-route53</li>
    <li>python311Packages.certbot-dns-route53.dist</li>
    <li>python311Packages.certbot.dist</li>
    <li>python311Packages.python-gammu</li>
    <li>python311Packages.python-gammu.dist</li>
    <li>wifish</li>
  </ul>
</details>

**Review by cafkafk — COMMENTED** [review]
the failed build log of `icesl` wasn't available for some reason:
`error: build log of '/nix/store/k06f3z22khwynzl9cg10ic9kdr8s2y12-iceSL-2.4.1.drv^*' is not available`

**Review by spacefrogg — APPROVED** [review]
Looking good, thanks!

**Comment by AndersonTorres** [comment]
@ofborg build icesl

**Comment by AndersonTorres** [comment]
Icesl is unfree.
Also it is broken :/

**Pull request merged**
