### PR TITLE
headset-charge-indicator: init at 2021-08-15

### PR DESCRIPTION
**Pull request by zebreus**
###### Motivation for this change

[headset-charge-indicator](https://github.com/centic9/headset-charge-indicator) not yet packaged for nix.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mindavi** [comment]
Can you rebase and split adding yourself as a maintainer to a separate commit? See the CONTRIBUTING guidelines.

**Comment by Zebreus** [comment]
@Mindavi Thanks for the info, should be fine now. As far as I can see it is only implied in the [CONTRIBUTING.md](CONTRIBUTING.md) that adding a maintainer should be a seperate commit, probably there should be some clarification in there.

**Comment by Mindavi** [comment]
Thanks for the feedback, I guess there should be a section on 'Becoming a maintainer' in there or something like that.

**Comment by Mindavi** [comment]
Result of `nixpkgs-review pr 161404` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>headset-charge-indicator</li>
  </ul>
</details>

Runs fine for me, though I don't have a supported headset so cannot test anything else than that it is added in the tray.

**Review by Mindavi — APPROVED** [review]

**Pull request merged**
