### PR TITLE
uwsgi: add router_basicauth plugin

### PR DESCRIPTION
**Pull request by hxtmdev**
## Description of changes

This enables the included basic auth plugin.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by gdamjan** [comment]
I think this is already included in uwsgi by default
```bash
$ uwsgi --routers-list
…
redirect-301
basicauth
basicauth-next
rewrite
…
```

**Comment by hxtmdev** [comment]
Thanks for taking a look!

I can confirm the output, yet `nix flake check gitlab:hxtmdev/dav` works but when you remove [the patch](https://gitlab.com/hxtmdev/dav/-/blob/ce5bc4ceb7d98557b1d0ea9882d45492dfe93e76/flake.nix#L16-L21) it complains about
```
error: Unknown UWSGI plugin router_basicauth, available : cgi, php, python2, python3, rack
```
output is the same for the used 24.05 commit in my example and the error can be replicated with nixos-unstable as well.

**Comment by gdamjan** [comment]
I don't know what `gitlab:hxtmdev/dav` is, but if it has `--plugin router_basicauth` it'll fail, since that is built-in, not an additional plugin.

**Comment by hxtmdev** [comment]
> if it has `--plugin router_basicauth` it'll fail, since that is built-in

That's it! Everything works if I just don't specify it explicitly. Thanks!

**Comment by hxtmdev** [comment]
@gdamjan I'd like to `Thanks-to: Damjan Georgievski <gdamjan@gmail.com>` you in the fix in my repo if unless you prefer to not be mentioned?!

**Comment by gdamjan** [comment]
fine with me

**Pull request closed without merging**
