### PR TITLE
NixOS /etc/hosts improvements

### PR DESCRIPTION
**Pull request by aszlig**
The goal is to improve `networking.hosts` so that we have more control over whether to set the canonical hostname or aliases of it.

This was originally discussed in #27105 starting with [this comment](https://github.com/NixOS/nixpkgs/pull/27105#discussion_r130336033).

### CODE REVIEW

**Comment by volth** [comment]
I use the current implementation for about a month almost since it was proposed

1. There are services with
```nix
  config = mkIf cfg.enable {
    networking.hosts."127.0.0.1" = [ "servicename" ];
   }
```

2. Workstation's /etc/hosts forms from nixops configuration (not exactly nixops, but it is a for of it)
```nix
    networking.hosts =
      let
        tierra = import ../my-overrides/nixslave/my-tierra.nix;
      in
        lib.zipAttrs (
          (lib.mapAttrsToList (machineName: machine: { ${machine.public-ip} = "${machineName}.wan"; }) (lib.filterAttrs (machineName: machine: machine?public-ip) tierra)) ++
          (lib.mapAttrsToList (machineName: machine: { ${machine.ipv6     } = "${machineName}.wan"; }) (lib.filterAttrs (machineName: machine: machine?ipv6     ) tierra)) ++
          (lib.mapAttrsToList (machineName: machine: { ${machine.lan-ip   } = "${machineName}.lan"; }) (lib.filterAttrs (machineName: machine: machine?lan-ip   ) tierra)) ++
          (lib.mapAttrsToList (machineName: machine: { ${machine.dmz-ip   } = "${machineName}.dmz"; }) (lib.filterAttrs (machineName: machine: machine?dmz-ip   ) tierra)) ++
          # prevent java error: "Exception thrown by the agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException:"
          [{ "127.0.0.1" = config.networking.hostName; }]  ++
          [{ "::1"       = config.networking.hostName; }]
        );
```

Which of these entries are ```canonical``` and which ```aliases``` ?

**Comment by edolstra** [comment]
What are the use cases for this?

Worried that we're over-engineering /etc/hosts.

**Comment by aszlig** [comment]
@edolstra: The main point here is to improve on mergability of the options defined in `networking.hosts`, because right now if you want to distinguish between the canonical host name and aliases, you have to use `mkBefore` to force a particular canonical hostname.

So let's say you have the following definition:

```nix
{
  networking.hosts."1.2.3.4" = [ "foo" "bar" ];
}
```

This leads to the canonical hostname `foo` and the alias `bar`. Now let's say you want to set the canonical host name to `xyz` and still keep aliases defined somewhere else, you could do something like this:

```nix
{ lib, ... }: {
  networking.hosts."1.2.3.4" = lib.mkBefore [ "xyz" ];
}
```

Now we have `1.2.3.4 xyz foo bar`, but we'd need to use `mkOrder 400` if we want to have another canonical hostname. If we want to replace the canonical name it gets even worse and we can only `mkForce` the whole definition.

**Comment by aszlig** [comment]
@volth: What exactly are you referring to?

**Comment by mmahut** [comment]
Any update on this pull request?

**Comment by aszlig** [comment]
@mmahut: Hm, I guess I won't pursue this further, hence closing.

**Pull request closed without merging**
