### PR TITLE
treewide: Re-add reverted Nix 2 syntax features

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
Placeholders are just too convenient. See, for example, recently merged https://github.com/NixOS/nixpkgs/pull/37613

### CODE REVIEW

**Comment by joepie91** [comment]
FYI: `placeholder` usage is totally breaking Nix 1.11 on NixOS 17.09 stable when using the unstable channel (which is not uncommon, either totally or for specific packages), specifically breaking on `gvfs`. That issue is currently blocking a rebuild on my systems.

IMO, Nix 2.0-only expressions should not be merged until 18.03 is released.

**Comment by davidak** [comment]
@joepie91 workaround for 17.09:

`  nix.package = pkgs.nixStable2;`

**Comment by matthewbauer** [comment]
I think we should wait on this until NixOS/nix#2016 is resolved

**Comment by jtojnar** [comment]
@GrahamcOfBorg eval

**Comment by samueldr** [comment]
I was asked to re-consider this issue. I am fine with the minimal version being 1.11 for 18.09, but there have been multiple occasions questioning the value of still keeping 1.11 around as the minimal version.

I think the only fully thought-of argument *for* keeping 1.11 around for 18.09 is nix#2016. This may not be important enough to warrant keeping 1.11 compatibility for 18.09.

I have been told [by @dezgeg](https://logs.nix.samueldr.com/nixos-dev/2018-08-26#1513667;) that there already are some parts of nixpkgs that won't build with 1.11.

> &lt;Dezgeg> huh, I thought we don't, given that many things (like building ISO images or nixos tests) require nix 2.0

Ripping the band-aid right now at the edge of the branch-off would, though, make it so that 18.09 has almost no 2.x specific features in, but ensures going forward 19.03 *can* use everything freely. Merging this will also bring out the users affected by such change, making them known values (if any) instead of theoretical figures.

Assuming this doesn't get merged by branch-off, I nominate this PR as being within the first merged to master right after making the release-18.09 branch.

@vcunat, and @edolstra, could you both give your opinion and judgement? I won't personally merge this before the branch-off (unless told to by one of you), but agree and support the decision of any of you two to merge this.

**Comment by vcunat** [comment]
The largest inconvenience I can see is that this disables one-step upgrade from NixOS <= 17.09 to >= 18.09, as the abortion in `./default.nix` will block `nixos-rebuild` from evaluating nix in the first step.

Now, the build-time closure of nix itself probably won't use placeholders yet, so the abortion itself would be the only blocker (as only new nix gets built and then it's used for further evaluation), but I can't see how to easily enforce this, and support periods for <= 17.09 and >= 18.09 do **not** overlap anyway.  Therefore I'd just add a comment to https://github.com/NixOS/nixpkgs/blob/master/default.nix#L9 that they should switch to 18.03 to get nix2 before updating further.

**Comment by michaelpj** [comment]
We already have this in practice - there was an issue recently about someone being unable to upgrade to versions due to incompatibilities in the Nix version.

As for why it's useful on stable, the main reason I can see is that it makes cherry picking patches easier.

**Comment by grahamc** [comment]
image

**Pull request merged**
