### PR TITLE
winePackages.{unstable,staging}: 8.10 -> 8.13

### PR DESCRIPTION
**Pull request by SuperSamus**
###### Description of changes

https://www.winehq.org/announce/8.11
https://www.winehq.org/announce/8.12
https://www.winehq.org/announce/8.13

Closes #242157.

Untested.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by drupol — APPROVED** [review]

**Comment by trofi** [comment]
Does `unstable` hash work for you as is? It somehow fails in one digit for me (`Ja` vs `Js` below):

```
$ nix build --no-link github:NixOS/nixpkgs/master#wineWowPackages.waylandFull
error: hash mismatch in fixed-output derivation '/nix/store/i3hz0rwsqvsawsnlqkhs72jzv5v37nsi-wine-gecko-2.47.4-x86.msi.drv':
         specified: sha256-Ja7MR3BrCRkI9/gUvdsHTGG+uAYzGOnvxaf3iYV3k9Y=
            got:    sha256-Js7MR3BrCRkI9/gUvdsHTGG+uAYzGOnvxaf3iYV3k9Y=
error: 1 dependencies of derivation '/nix/store/hdd72s0b9d3q3v3n0mpkyqihp1w98655-wine-wow-wayland-8.0.drv' failed to build
```

I wonder if it's something on my side or the hash is slightly off.

**Comment by drupol** [comment]
I'm not in front of a computer, I'll test asap.

**Comment by trofi** [comment]
Result of `nixpkgs-review pr 245043` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>16 packages failed to build:</summary>
  <ul>
    <li>pipelight</li>
    <li>winbox</li>
    <li>wine-staging (winePackages.stagingFull)</li>
    <li>wine-wayland (winePackages.waylandFull)</li>
    <li>wine64Packages.staging</li>
    <li>wine64Packages.stagingFull</li>
    <li>winePackages.staging</li>
    <li>winePackages.unstableFull</li>
    <li>wineWow64Packages.staging</li>
    <li>wineWow64Packages.stagingFull</li>
    <li>wineWowPackages.staging</li>
    <li>wineWowPackages.stagingFull</li>
    <li>wineWowPackages.unstableFull</li>
    <li>wineWowPackages.waylandFull</li>
    <li>yabridge</li>
    <li>yabridgectl</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>grapejuice</li>
    <li>grapejuice.dist</li>
    <li>wine64Packages.unstable</li>
    <li>wine64Packages.unstableFull</li>
    <li>winePackages.unstable</li>
    <li>wineWow64Packages.unstable</li>
    <li>wineWow64Packages.unstableFull</li>
    <li>wineWowPackages.unstable</li>
  </ul>
</details>

**Comment by CobaltCause** [comment]
I'm also hitting https://github.com/NixOS/nixpkgs/pull/245043#issuecomment-1649289898. Looks like https://github.com/NixOS/nixpkgs/pull/245351 should fix this.

**Pull request merged**
