### PR TITLE
libversion: 2.7.0 -> 2.8.1; py-libversion: 1.0.0 -> 1.1.2

### PR DESCRIPTION
**Pull request by dtzWill**
- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
@GrahamcOfBorg build python3.pkgs.libversion

**Comment by c0bw3b** [comment]
@dtzWill can you drop the commit for python3Packages.libversion please?
It's been updated in #49971

**Comment by c0bw3b** [comment]
--> #50705

**Comment by dtzWill** [comment]
Thanks, sorry!

**Pull request closed without merging**
