### PR TITLE
dolphin-emu: fix build, use bundled zlib-ng

### LINKED ISSUE #264274: Build failure: dolphin-emu
### Steps To Reproduce

1. build dolphin-emu on nixpkgs-unstable

### Build log

https://gist.github.com/majiru/ee787dd386f73170a050f7f17fd5b451

### Notify maintainers

@MP2E
@ashkitten 
@xfix 
@IvarWithoutBones 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

### PR DESCRIPTION
**Pull request by kirillrdy**
## Description of changes

not sure if best fix

fixes https://github.com/NixOS/nixpkgs/issues/264274

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by majiru** [comment]
Thanks for taking a look at this.

I think something strange here is going on here with how zlib is getting included. The top level CMakeList file in the dolphin code seems to indicate that zlib should be replaced with zlib-ng for all of the project. But I noticed that the generated Makefile's seem to still link against both zlib and zlib-ng. I suspect by changing this we would just cause dolphin to use it's vendored version of zlib-ng. I gave the following a test and it seems to also fix the build issue.  I think using their vendored variant is fine.

```
diff --git a/pkgs/applications/emulators/dolphin-emu/default.nix b/pkgs/applications/emulators/dolphin-emu/default.nix
index 6e3f93701c0b..553503b8f91c 100644
--- a/pkgs/applications/emulators/dolphin-emu/default.nix
+++ b/pkgs/applications/emulators/dolphin-emu/default.nix
@@ -38,7 +38,6 @@
 , vulkan-loader
 , xxHash
 , xz
-, zlib-ng
 
   # Used in passthru
 , common-updater-scripts
@@ -78,6 +77,8 @@ stdenv.mkDerivation rec {
     ./find-minizip-ng.patch
   ];
 
+  strictDeps = true;
+
   nativeBuildInputs = [
     stdenv.cc
     cmake
@@ -118,7 +119,6 @@ stdenv.mkDerivation rec {
     sfml
     xxHash
     xz # LibLZMA
-    zlib-ng
   ] ++ lib.optionals stdenv.isLinux [
     alsa-lib
     bluez
```

**Comment by kirillrdy** [comment]
@majiru thank you for looking into this as well.  I've pushed you changes, also for some reason on darwin versionTest was failing

**Review by majiru — APPROVED** [review]

**Comment by SuperSamus** [comment]
Related to the mess: https://github.com/dolphin-emu/dolphin/pull/12070.

**Comment by Jackaed** [comment]
What is preventing this from being merged?

**Comment by wegank** [comment]
Nothing, I was just away from nixpkgs for being busy; this PR looks good though.

**Comment by kirillrdy** [comment]
@wegank thank you for taking a look at this !

**Pull request merged**
