### PR TITLE
atlauncher: 3.4.35.4 -> 3.4.35.9

### PR DESCRIPTION
**Pull request by mythmon**
## Description of changes

Updated atlauncher to the latest upstream version. The changelog is listed on their website: https://atlauncher.com/downloads

- __3.4.35.5__
  - Fixes
    - Creating pack not resetting modloader when switched back to none
    - Issue with file downloads for non third party enabled files on CurseForge not working
    - Issue adding a second account
  - Misc
    - Remove old FTB pack installing code
- __3.4.35.6__
  - Fixes
    - Issue with checking for updates on 1.20.1 NeoForge instances on Modrinth not working
- __3.4.35.7__
  - Fixes
    - Issue with browser download mods from CurseForge packs with spaces in the filename not being recognised
- __3.4.35.8__
  - Fixes
    - Mods being duplicated when exporting instances
    - Remove duplicate mods from the instance.json mods list
    - Starting servers not working when script is not executable
    - Issue with LaunchServer.bat script not working when launching with a java path with spaces
    - Issue starting newer Forge servers that use the shim.jar in their server scripts
  - Misc
    - Move tracking to use Mixpanel
- __3.4.35.9__
  - Fixes
    - Issue with Modrinth instance version checker causing error when project ID is not defined [#877]
    - Issue with CurseForge export including non available files causing it to be rejected [#875]
    - Remove initial screen view and CurseForge/Modrinth selector dialogs from Analytics
    - Remove instance_launch_started event and fix time played not coming through for Analytics

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mythmon** [comment]
This is a simpler alternative to https://github.com/NixOS/nixpkgs/pull/286380 that just bumps the version. Maybe that will make it easier to get merged.

**Review by GetPsyched — APPROVED** [review]
Welp, hope what you say happens.

EDIT: There is a typo in your commit message.

**Comment by mythmon** [comment]
Sorry I don't see the typo in the commit message. Can you be more specific?

**Comment by GetPsyched** [comment]
> Sorry I don't see the typo in the commit message. Can you be more specific?

The commit message ends in a period

**Comment by mythmon** [comment]
Ah. That was intentional, but only because I misread the style guide. I fixed it now.

**Review by GetPsyched — APPROVED** [review]

**Pull request merged**
