### PR TITLE
Neverwinter Nights: add the game

### PR DESCRIPTION
**Pull request by abbradar**
This adds a native Linux version of Neverwinter Nights, with data files extracted from the GOG distribution and Linux client taken from official BioWare server. The packaging script was greatly inspired by https://aur.archlinux.org/packages/nwn-gog/ , but changed to patch necessary things for NixOS and also to improve several things.

NWN also requires `binkplayer` which was added too. Unfortunately, RAD Game Tools disallowed redistribution or automated download of the player (via e-mail), so a user needs to download it by himself.

The main concern of this (so this is a PR) is that this package may be too specific for Nixpkgs. On one hand, it's a native Linux (albeit proprietary) application with a very non-trivial building script. On the other, it's an old game which may be needed by only a few people, of not only by myself. What policy do we have to decide whether a particular package is suited for Nixpkgs?

P.S.: The build sequence is indeed very non-trivial, with very few documentation from BioWare on how actually to build a native distribution. Also the work done by the author of `nwmovies`, `nwuser` etc is enormous, he does a lot of binary patching of the game in memory, dynamically searching for key places using a disassembler library (!). Both the authors of those binary patches and of the source `nwn-gog` AUR package deserve credits ^_^.

### CODE REVIEW

**Comment by vcunat** [comment]
AFAIK there's some general opposition against packages needing `requireFile`. I would *personally* include such packages, as we mark them `unfree` so they don't even appear to be present by default. (Or we could even invent a new flag meaning that automated installation isn't possible.) IIRC some suggested factoring these into a separate repository, as composition is relatively easy, I haven't noticed anyone creating such.

**Comment by abbradar** [comment]
One notable difference from #10006 is that this derivation uses only resources from Windows packages (extracting them). However, it does use `requireFile`, both for the source Windows package and for `binkplayer` which was disallowed to be downloaded automatically by authors.

cc @edolstra : what's your opinion on this?

**Comment by rasendubi** [comment]
(triage) `requireFile` is used in almost 30 packages now. Can this be rebased and merged?

**Comment by edolstra** [comment]
No, we should not add more `requireFile`-based packages unless there is a really good reason. (E.g. OracleJDK, although I'd personally prefer to get rid of that one too.) This would be a candidate for the `nixpkgs-warez` repo if we ever create it.

**Comment by rasendubi** [comment]
I think this PR can be closed then.

**Comment by abbradar** [comment]
@edolstra Not really warez -- this package works with an official GOG version, how would you get it is on your conscience (I have it bought, for example).

:+1: for closing this.

**Comment by abbradar** [comment]
If someone still has an interest for this, I have created a small repo for native games like this one which need non-free (in both senses of word) data but also non-trivial packaging to be playable: https://github.com/abbradar/nixpkgs-nonfree

**Pull request closed without merging**
