### PR TITLE
julia-mono: 0.022 → 0.027

### PR DESCRIPTION
**Pull request by toastal**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Can you rebase this PR on master to fix the eval error?

**Review by suhr — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
```
hash mismatch in fixed-output derivation '/nix/store/d31klqks3z0dnc4ksnyc7aslkgdz25d9-JuliaMono-0.027':
  wanted: sha256:1ds7blvmf09rvkf7chfirjbnmcfq63av4dzv62kyynwd3km9cszb
  got:    sha256:1aqkgaml36nfb15y3i29cpvqpidgz80xnibpyz2382y7qsz11wvz
cannot build derivation '/nix/store/2pfj1l56v42lz526c6b8bdjq8x1jq9jd-env.drv': 1 dependencies couldn't be built
```

**Comment by toastal** [comment]
```
$ nix-prefetch-url "https://github.com/cormullion/juliamono/releases/download/v0.027/JuliaMono.zip"
[6.0 MiB DL]
path is '/nix/store/31k5x92hcgd9sfm85nfr0prq6hqyfi6s-JuliaMono.zip'
1ds7blvmf09rvkf7chfirjbnmcfq63av4dzv62kyynwd3km9cszb
```

Does this not work?

**Comment by tomberek** [comment]
@toastal there are postfetch actions. Also you'd probably need `--unpack`. In this case:
```
sha256-RtB0CRBbV5vn3zOBh4yX2ZU2Y50w6iwQEjLVK3CKYNM=
```
or
```
sha256:1aqkgaml36nfb15y3i29cpvqpidgz80xnibpyz2382y7qsz11wvz
```
would work.

**Comment by toastal** [comment]
https://github.com/NixOS/nixpkgs/pull/114627 Is the latest. Honestly I'm still really unsure why I can't run `nix-prefetch-url` to test this. The only thing I _understand_ how to do is put in a fake SHA and let the build system tell me what it was supposed to be.

**Comment by SuperSandro2000** [comment]
> #114627 Is the latest. Honestly I'm still really unsure why I can't run `nix-prefetch-url` to test this. The only thing I _understand_ how to do is put in a fake SHA and let the build system tell me what it was supposed to be.

You can use nix-update to update it properly. You can't use nix-prefetch-url because fetchzip unpacks the archive IIRC.

**Pull request closed without merging**
