### PR TITLE
Support Raspberry Pi 4 (8 GB)

### PR DESCRIPTION
**Pull request by SquircleSpace**
This change simply bumps the versions for all fetchFromGitHub derivations which pull from the official raspberrypi GitHub repository.  The firmware and kernel versions currently being used are too old to support the new 8GB model.

###### Motivation for this change
NixOS doesn't boot on the 8GB Raspberry Pi 4.  See https://github.com/NixOS/nixpkgs/issues/63720

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

I was able to build an sd-image using the config files from https://github.com/Robertof/nixos-docker-sd-image-builder as a starting point.  I made no significant changes to the config file that repo offers as a starting point.  I performed the build on the rpi itself while running Ubuntu Server (I was having issues with qemu/docker).  The resulting sd-image file successfully booted when loaded onto an SD card.

I did no other testing at all.

* * *

Closes #90618
Closes #89659

### CODE REVIEW

**Comment by SquircleSpace** [comment]
@samueldr

**Comment by arachnist** [comment]
raspberrypi-tools in your patchset tries to apply the `tools-dont-install-sysv-init-scripts.patch` which doesn't apply anymore - `interface/vmcs_host/linux/vcfiled/CMakeLists.txt` doesn't exist anymore, and it looks like it won't be needed.

**Comment by samueldr** [comment]
The `raspberrypifw` package has been verified as being compatible with an updated eeprom, and usb boot. (The rest of this review is yet to come.)

**Review by samueldr — CHANGES_REQUESTED** [review]
The change is listed in-line, and is as @arachnist said.

Everything else looks alright, though I could not test the following, only built them: `rpiboot-unstable`, `libraspberrypi` and `raspberrypi-tools`.

**Review by samueldr — APPROVED** [review]

**Pull request merged**
