### PR TITLE
nushell: 0.31.0 -> 0.32.0

### PR DESCRIPTION
**Pull request by ajeetdsouza**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ajeetdsouza** [comment]
Is there a simple way to get the value of `cargoSha256`?

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 125325` at a8fcba85 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/5915999d8f937cb52d6c5d3263c3a952">nushell</a></li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by Artturin** [comment]
Result of `nixpkgs-review pr 125325` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>nushell</li>
  </ul>
</details>

**Comment by iAmMrinal0** [comment]
Result of `nixpkgs-review pr 125325` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>nushell</li>
  </ul>
</details>

**Review by fufexan — APPROVED** [review]

**Comment by fufexan** [comment]
Oops, didn't look at your commit message. It should be `nushell: 0.31.0 - > 0.32.0`, as should be your PR name (though that doesn't matter as much).

**Comment by ajeetdsouza** [comment]
Hey @fufexan, I've amended the commit so that the message is correct.

**Review by Artturin — APPROVED** [review]

**Comment by ajeetdsouza** [comment]
Hey @SuperSandro2000 could you take a look at this?

**Comment by ajeetdsouza** [comment]
Thanks!

**Pull request merged**
