### PR TITLE
firefox{-esr,-bin,}: update to 64.0, 60.4.0esr

### PR DESCRIPTION
**Pull request by andir**
###### Motivation for this change

Bump to the latest versions of firefox.

The version 64.0 release notes will appear here: https://www.mozilla.org/en-US/firefox/64.0/releasenotes/
The version 60.4.0esr0 release notes will appear here: https://www.mozilla.org/en-US/firefox/60.4.0/releasenotes/

This should be backported to 18.09. It depends on #51365 being ported first. The backport is trivial since most of the required dependencies have already been updated. The only catch is the change of `version` to `ffversion` that exists in master.
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
Hmm, FF 64 fails to link libxul on my machine (no interesting log unfortunately):
```
collect2: error: ld returned 1 exit status
```

I used the other two for more than dozen minutes each, so I expect they'll be OK and pushed them.

**Comment by andir** [comment]
That is interesting. Are you maybe running out of (disk) space? I am running a FFX64 on a two of my machines.

**Comment by vcunat** [comment]
It's 8 GiB tmpfs &ndash; do you think it likely?  I haven't watched it.  (And the error message could be clearer in any case :-/)

**Comment by andir** [comment]
I am very sure that is likely. I have run in space limitations for the past few versions. Usually remounting the tmpfs there to around ~10GB fixed it.

Here is the log from my successful build this morning - maybe you can spot a difference.

https://gist.githubusercontent.com/andir/801ea00e002c8c4bc97a09cf1593a771/raw/439c90a67860e96ea49d941d616559ef7a8e3cd3/gistfile1.txt

**Comment by andir** [comment]
@vcunat Did increasing the scratch space solve the error for you? I did rebuild both of the packages on another host just fine.

**Comment by vcunat** [comment]
Confirmed.  All in master now.  -bin in 18.09 as well.   I expect to do porting of non-bin this evening, but anyone can be quicker than me ;-)

**Comment by vcunat** [comment]
Would you agree we should sync expression in release-18.09 from master in terms of using the identifier `ffversion` vs. `version`?  I think the difference unnecessarily complicates cherry-picks.

**Comment by andir** [comment]
I totally agree.. I hit that issue more then once already. The changes made
in master look reasonable and there is not reason to not include them.

**Comment by schmittlauch** [comment]
Will 64.0 also land in release-18.09, or is stable bound to use the esr releases only?

**Comment by vcunat** [comment]
We do backport all firefox updates.  I haven't managed to do it yet (neither has anyone else apparently).

**Comment by fpletz** [comment]
I've started with syncing both expressions on a new branch: https://github.com/NixOS/nixpkgs/tree/release-18.09-firefox64

Gave up for now because I ran into this weird error:

```
layout/style/nsCSSPropsGenerated.inc.stub
/tmp/nix-build-firefox-unwrapped-64.0.drv-0/firefox-64.0/obj-x86_64-pc-linux-gnu/_virtualenvs/init/bin/python -m mozbuild.action.file_generate /tmp/nix-build-firefox-unwrapped-64.0.drv-0/firefox-64.0/layout/style/GenerateCSSPropsGenerated.py generate nsCSSPropsGenerated.inc .deps/nsCSSPropsGenerated.inc.pp .deps/nsCSSPropsGenerated.inc.stub ServoCSSPropList.py
layout/style/ServoStyleConsts.h.stub
/tmp/nix-build-firefox-unwrapped-64.0.drv-0/firefox-64.0/obj-x86_64-pc-linux-gnu/_virtualenvs/init/bin/python -m mozbuild.action.file_generate /tmp/nix-build-firefox-unwrapped-64.0.drv-0/firefox-64.0/layout/style/GenerateServoStyleConsts.py generate ServoStyleConsts.h .deps/ServoStyleConsts.h.pp .deps/ServoStyleConsts.h.stub /tmp/nix-build-firefox-unwrapped-64.0.drv-0/firefox-64.0/servo/components/style/cbindgen.toml
make[4]: Leaving directory '/tmp/nix-build-firefox-unwrapped-64.0.drv-0/firefox-64.0/obj-x86_64-pc-linux-gnu/config/makefiles/xpidl'
make[4]: write error: stdout
make[3]: *** [Makefile:15: export] Error 1
make[3]: Leaving directory '/tmp/nix-build-firefox-unwrapped-64.0.drv-0/firefox-64.0/obj-x86_64-pc-linux-gnu/xpcom/xpidl'
make[2]: *** [/tmp/nix-build-firefox-unwrapped-64.0.drv-0/firefox-64.0/config/recurse.mk:101: xpcom/xpidl/export] Error 2
../../config/nsinstall -R -m 644 'nsCSSPropertyID.h' '../../dist/include'
../../config/nsinstall -R -m 644 'ServoCSSPropList.h' '../../dist/include/mozilla'
../../config/nsinstall -R -m 644 'ServoStyleConsts.h' '../../dist/include/mozilla'
make[3]: Leaving directory '/tmp/nix-build-firefox-unwrapped-64.0.drv-0/firefox-64.0/obj-x86_64-pc-linux-gnu/layout/style'
touch ipdl.track
make[3]: Leaving directory '/tmp/nix-build-firefox-unwrapped-64.0.drv-0/firefox-64.0/obj-x86_64-pc-linux-gnu/ipc/ipdl'
make[2]: Leaving directory '/tmp/nix-build-firefox-unwrapped-64.0.drv-0/firefox-64.0/obj-x86_64-pc-linux-gnu'
make[1]: *** [/tmp/nix-build-firefox-unwrapped-64.0.drv-0/firefox-64.0/config/recurse.mk:34: export] Error 2
make[1]: Leaving directory '/tmp/nix-build-firefox-unwrapped-64.0.drv-0/firefox-64.0/obj-x86_64-pc-linux-gnu'
make: *** [/tmp/nix-build-firefox-unwrapped-64.0.drv-0/firefox-64.0/config/rules.mk:431: default] Error 2
builder for '/nix/store/a0axjwjah3hmrvsss47yrayww0v15rmj-firefox-unwrapped-64.0.drv' failed with exit code 2
cannot build derivation '/nix/store/jl7yv32d85km74zhjqnad9nrl83qksvq-firefox-64.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/jl7yv32d85km74zhjqnad9nrl83qksvq-firefox-64.0.drv' failed
```

**Comment by vcunat** [comment]
Yes, I'm getting the same.  No ideas so far.

**Comment by vcunat** [comment]
Oh, that machine was giving me the same error also for the newly merged backport, but another machine managed to succeed.  I don't have that failing machine under control, so I don't really know, but perhaps it's a bad error message for some kind of resource exhaustion.

**Pull request closed without merging**
