### PR TITLE
man-db > man

### PR DESCRIPTION
**Pull request by zimbatm**
###### Things done:
- [ ] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- [ ] Built on platform(s): NixOS / OSX / Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Fixes issue #7269 and #13436

Installing `man_db` instead of `man` solves the escaping issues if PAGER is unset.

I suppose that we are using `man` by default because it's much smaller (228K vs 2.2M), it would be good to get a confirmation on that. The biggest difference is that man-db includes translated versions of the pages, we could strip them out and gain 1M back.

`man` is hosted at  http://primates.ximian.com/~flucifredi/man/ and hasn't seen any development lately. I can't reach the website at the moment.

`man-db` is hosted at http://man-db.nongnu.org/ and used by all the big distros (Arch, Debian, Gentoo, Fedora, ...).

Based on that I would recommend to remove the `man` package and use `man_db`. Then we can remove the PAGER environment variable (which is no set in any other distro I know of).

Still needs discussion and testing.

### CODE REVIEW

**Comment by edolstra** [comment]
I prefer having a pager by default so I'm :-1: on this.

**Comment by zimbatm** [comment]
@edolstra do you mean keep the environment variable because injecting `less` as a dependency of all the packages is increasing the mass rebuilds ?

**Comment by edolstra** [comment]
Yeah, making lots of packages dependent on `less` seems unnecessary when there is a perfectly good runtime configuration mechanism. Also, setting `PAGER` makes things more predictable, since you know what you get (namely `$PAGER`), rather than whatever the built-in default of each program happens to be.

**Comment by vcunat** [comment]
Well, let's split it up: changing the default `man` provider shouldn't be very controversial, I hope. I believe those translations there aren't translations of any pages but of the strings emitted by man itself. We can extract a lightweight bin/man + lib/*, giving ~0.3 MB.

**Comment by zimbatm** [comment]
Alright, I'll remove the PAGER changes and keep less as a dependency just for man to avoid issues with ssh users, and work on trimming man-db down. Would that work for you @edolstra ?

**Comment by edolstra** [comment]
Why do ssh users need `man` to depend on `less`? I've never had a problem with `man` via `ssh`.

**Comment by zimbatm** [comment]
Sorry I meant for non-nixos users. Right now man_db won't run any pager unless compiled with one or if PAGER is provided which is usually not the case in other distros. On the other hand you might argue that man_db is not really useful on other distros as they hopefully provide their own man implementation.

I'm going to abandon this work as man_db needs a lot more love to be functional. More than I initially thought. Some of it has been addressed in #9554 but there is more. Right now it will complain because /etc/man_db.conf doesn't exist but even when it's populated, the default mapping doesn't work on NixOS. I suppose it would also have to be tuned for other platforms if we want to support them.

**Comment by vcunat** [comment]
See https://github.com/NixOS/nixpkgs/pull/15646

**Pull request closed without merging**
