### PR TITLE
nss_latest: 3.76.1 -> 3.78.0; firefox{,-bin}: 99.0.1 -> 100.0 🥳 ; firefox-esr: 91.8.0esr -> 91.9.0esr

### PR DESCRIPTION
**Pull request by mweinelt**
https://firefox-source-docs.mozilla.org/security/nss/releases/nss_3_78.html
https://firefox-source-docs.mozilla.org/security/nss/releases/nss_3_77.html
https://www.mozilla.org/en-US/firefox/91.9.0/releasenotes/
https://www.mozilla.org/en-US/firefox/100.0/releasenotes/

###### Description of changes

Builds are queued, I'm going to sleep and will test in the morning.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
As usual testing on x86_64-linux (sway, pipewire)
- Webcam
- Microphone
- Screensharing (wlroots)
- Audio/Video
- WebGL

- [x] 91.9.0esr
- [x] 100.0

**Comment by vcunat** [comment]
> pkgs/development/libraries/nss/3_54_security_load.patch': No such file or directory

**Comment by mweinelt** [comment]
Estimating rebuild amount by counting changed Hydra jobs (parallel=unset).
    172 x86_64-darwin
   1230 x86_64-linux

**Comment by mweinelt** [comment]
I assume the rebuild amount comes from the patch handling in the 3.77 update. That doesn't change the fact that this should go into master.

**Comment by vcunat** [comment]
You reordered the patches, but that seems easy to fix.

**Comment by vcunat** [comment]
Or at the very least move the comment that got on a wrong place due to that move.

**Comment by mweinelt** [comment]
Wow, yeah, the list is of course ordered. The 3.77 update came from @ajs124 and we both made the same mistake :hand:.

**Comment by mweinelt** [comment]
Estimating rebuild amount by counting changed Hydra jobs (parallel=unset).
- 1 x86_64-darwin
- 13 x86_64-linux

**Comment by mweinelt** [comment]
https://www.mozilla.org/en-US/security/advisories/mfsa2022-16/
https://www.mozilla.org/en-US/security/advisories/mfsa2022-17/

**Comment by mweinelt** [comment]
Updated the commit messages with advisories and fixed CVEs.

**Pull request merged**
