### PR TITLE
treewide: clean up usages of `cp -n`

### PR DESCRIPTION
**Pull request by K900**
###### Description of changes

coreutils 9.2 changed the behavior of `cp -n` to return an exit code if not all files were replaced: 

https://git.savannah.gnu.org/gitweb/?p=coreutils.git;a=blob;f=NEWS;h=3d19c3bad44f7d21446561449abd07f3794ff0c0;hb=HEAD#l171

This removes all the uses of `cp -n` I found at a glance.

Supersedes #236057

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Madouura** [comment]
The reason why we copy `ckProfiler` from `composable_kernel` into it's own output is because hydra will not cache since it will exceed the output limit. This needs to be changed to ensure we cache.
We should probably do something like #230881. CC @kira-bruneau

**Comment by Madouura** [comment]
I should note ckProfiler shouldn't be required, but it should be included.

**Comment by kira-bruneau** [comment]
@Madouura Do you know if `composable_kernel` was hitting the limit before the workaround? I'm pretty convinced the workaround wasn't working in `rocfft` because hydra was considering all outputs for one derivation as part of the limit (I'm not 100% certain though)

I'm pretty sure the separate derivation approach would still work if we replicated how rocfft quarters files by default, but I found it way simpler to just split by `gpuTarget`.

I think we might just be able to revert the workaround here? Which would be be easier maintenance-wise than adding patches to try to split out the built into multiple derivations.

**Comment by kira-bruneau** [comment]
Oh yep, so it looks like it was building before the workaround: https://hydra.nixos.org/build/197920823, but it takes a crazy amount of time.

I think we can just revert the workaround and mark it to build under `big-parallel`.

**Comment by kira-bruneau** [comment]
Pushed the revert here: #236183! I'm pretty certain it will build - build just running nixpkgs-review now 😜

**Comment by Madouura** [comment]
> @Madouura Do you know if `composable_kernel` was hitting the size limit before the workaround? I'm pretty convinced the workaround wasn't working in `rocfft` because hydra was considering all outputs for one derivation as part of the limit (I'm not 100% certain though).
> 
> and I'm pretty sure the separate derivation approach would still work if we replicated how `rocfft` quarters the generated source files by default, but I found it way simpler to just split by GPU target instead.
> 
> I think we might just be able to revert the workaround? Which would be easier maintenance-wise than adding patches to try to split out the build into multiple derivations.

If we don't put `ckProfiler` into it's own output, or just include it in the main output, yes it will hit the output limit.

**Comment by kira-bruneau** [comment]
> If we don't put `ckProfiler` into it's own output, or just include it in the main output, yes it will hit the output limit.

I looked through the hydra history though and none of the failures were because of the size limit. There were some indirect output errors indirectly from rocm-llvm though: https://hydra.nixos.org/build/200097303.

I might just be completely missing some context.

**Comment by Madouura** [comment]
We could just push and fix it later, I could be wrong.
I just remember the total output size being an issue.

**Comment by K900** [comment]
This wouldn't have helped with the output limit anyway, as the first derivation built still has everything.

**Pull request merged**
