### PR TITLE
chromedriver: 91.0.4472.101 -> 92.0.4515.43 and aarch64-darwin support

### PR DESCRIPTION
**Pull request by hlolli**
###### Motivation for this change

I need to develop selenium tests, and the chrome team are already release aarch64-darwin binaries.

###### Things done

1. bumped the version, called nix-prefetch-url to get the sha256 for linux and x86_64-darwin.
2. Added aarch64-darwin

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cole-h** [comment]
@ofborg eval

(Sorry, ofborg's certs recently had an issue, meaning that it was unable to
react to PRs. This has been fixed, but all PRs filed in this period will need
ofborg to be manually kicked off.)

**Review by primeos — CHANGES_REQUESTED** [review]
aarch64-darwin support sounds good to me but there are two additional requirements here:
1) The `chromedriver` version must be compatible with the stable Chrom{e,ium} release: https://chromedriver.chromium.org/downloads/version-selection (I guess we could consider extending the Nix expressions to support the beta channel as well if required).
2) `upstream-info.json` must be generated automatically via `pkgs/applications/networking/browsers/chromium/update.py`

**Comment by kclejeune** [comment]
> aarch64-darwin support sounds good to me but there are two additional requirements here:
> 
>     1. The `chromedriver` version must be compatible with the stable Chrom{e,ium} release: https://chromedriver.chromium.org/downloads/version-selection (I guess we could consider extending the Nix expressions to support the beta channel as well if required).
> 
>     2. `upstream-info.json` must be generated automatically via `pkgs/applications/networking/browsers/chromium/update.py`

Besides resolving the conflicts, is this all that's needed to get this merged?

**Comment by hlolli** [comment]
I totally forgot this was even still open. Hasn't even newer version been pushed long ago? If so, then I'd close it.

**Comment by hlolli** [comment]
I'm forgetting aarch64 support in this too. Feel free to make a new PR based on the ideas here @kclejeune (or PR onto my fork). I fear I'll forget again, since I don't need this right now.

**Comment by primeos** [comment]
> is this all that's needed to get this merged?

Yes, adding M1 support should be good to go as long as everything in `upstream-info.json` is generated automatically by the update script.

**Comment by hlolli** [comment]
@primeos turns out I need this again :) fixed the connflict and added an entry for generating the shasums for aarch64-darwin as is done with the other targers.

**Comment by kclejeune** [comment]
> @primeos turns out I need this again :) fixed the connflict and added an entry for generating the shasums for aarch64-darwin as is done with the other targers.

Thanks for taking care of this! I've been so busy during my last semester of school that I completely forgot.

**Comment by hlolli** [comment]
putting a grain of salt, not sure if it's a result of my setup but it seems it segfaults
this could be entirely my side. Would make sense if someone tests to confirm.

```
  remoteStacktrace: '0   chromedriver                        0x0000000104ed1408 __gxx_personality_v0 + 543364\n' +
    '1   chromedriver                        0x0000000104e67138 __gxx_personality_v0 + 108468\n' +
    '2   chromedriver                        0x0000000104a667d8 chromedriver + 157656\n' +
    '3   chromedriver                        0x0000000104a6137c chromedriver + 136060\n' +
    '4   chromedriver                        0x0000000104a543f4 chromedriver + 82932\n' +
    '5   chromedriver                        0x0000000104a5509c chromedriver + 86172\n' +
    '6   chromedriver                        0x0000000104a54650 chromedriver + 83536\n' +
    '7   chromedriver                        0x0000000104a53d04 chromedriver + 81156\n' +
    '8   chromedriver                        0x0000000104a52f1c chromedriver + 77596\n' +
    '9   chromedriver                        0x0000000104a531d0 chromedriver + 78288\n' +
    '10  chromedriver                        0x0000000104a68038 chromedriver + 163896\n' +
    '11  chromedriver                        0x0000000104abfe34 chromedriver + 523828\n' +
    '12  chromedriver                        0x0000000104abf7d4 chromedriver + 522196\n' +
    '13  chromedriver                        0x0000000104a8b238 chromedriver + 307768\n' +
    '14  chromedriver                        0x0000000104e94c7c __gxx_personality_v0 + 295672\n' +
    '15  chromedriver                        0x0000000104ea8bd8 __gxx_personality_v0 + 377428\n' +
    '16  chromedriver                        0x0000000104ead2b0 __gxx_personality_v0 + 395564\n' +
    '17  chromedriver                        0x0000000104ea99f8 __gxx_personality_v0 + 381044\n' +
    '18  chromedriver                        0x0000000104e8a754 __gxx_personality_v0 + 253392\n' +
    '19  chromedriver                        0x0000000104ec2a38 __gxx_personality_v0 + 483508\n' +
    '20  chromedriver                        0x0000000104ec2bac __gxx_personality_v0 + 483880\n' +
    '21  chromedriver                        0x0000000104ed7fec __gxx_personality_v0 + 570984\n' +
    '22  libsystem_pthread.dylib             0x00000001bc59d4ec _pthread_start + 148\n' +
    '23  libsystem_pthread.dylib             0x00000001bc5982d0 thread_start + 8\n'
    ```

**Comment by primeos** [comment]
Someone else opened another PR that already got merged: https://github.com/NixOS/nixpkgs/pull/152800
Sorry about that and thanks for your work here @hlolli.
Also: Sorry for not responding here. I read the messages and the diff LGTM but due to https://github.com/NixOS/nixpkgs/pull/128979#issuecomment-1003599950 I assumed this isn't ready yet.

**Comment by hlolli** [comment]
@primeos what a timing, but the other PR is essentialy exactly the same, so is suffers the same segfault. It will be fixed one day I'm sure.

**Pull request closed without merging**
