### PR TITLE
haskellPackages.lapack-ffi: remove from broken.yaml

### PR DESCRIPTION
**Pull request by thielema**
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin

### CODE REVIEW

**Comment by sternenseemann** [comment]
Note: Target branch is `master` and the package set was not regenerated.

**Comment by maralorn** [comment]
Ugh. I had noticed the latter but not the former.

**Comment by sternenseemann** [comment]
Not the end of the world, just a heads up :)

**Comment by thielema** [comment]
On Mon, 8 Nov 2021, sterni wrote:

> Note: Target branch is master and the package set was not regenerated.

What is the right branch?

The manual at 
https://nixos.org/manual/nixpkgs/stable/#chap-submitting-changes
says I shall use the NixOS version branch. But this one is missing recent 
fixes. Then the doc says I shall rebase to 'master'. Hm.

**Comment by sternenseemann** [comment]
`haskell-updates` for haskell-related changes (it's a custom stabilization branch). This is not your fault for getting wrong since it's not properly documented at the moment, I was just commenting for @maralorn. Working on fixing all that :)

**Pull request merged**
