### PR TITLE
python311Packages.google-auth: 2.21.0 -> 2.27.0

### LINKED ISSUE #288057: Update request: python3Packages.google-auth 2.21.0 → 2.27.0
- Package name: python3Packages.google-auth
- Latest released version: 2.27.0

- Current version on the unstable channel: 2.21.0
- Current version on the stable/release channel: 2.21.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@natsukium @mweinelt

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
Changelog: https://github.com/googleapis/google-auth-library-python/blob/v2.27.0/CHANGELOG.md

fixes https://github.com/NixOS/nixpkgs/issues/288057
cc @r3n3gad3p3arl 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by terlar — CHANGES_REQUESTED** [review]
Looks good to me, but seems the package was broken already. We need to move click to propagated build inputs.

We would need this change.
```patch
diff --git a/pkgs/development/python-modules/google-auth-oauthlib/default.nix b/pkgs/development/python-modules/google-auth-oauthlib/default.nix
index abc6fef98d09..b774427452aa 100644
--- a/pkgs/development/python-modules/google-auth-oauthlib/default.nix
+++ b/pkgs/development/python-modules/google-auth-oauthlib/default.nix
@@ -28,12 +28,12 @@ buildPythonPackage rec {
   ];
 
   propagatedBuildInputs = [
+    click
     google-auth
     requests-oauthlib
   ];
 
   nativeCheckInputs = [
-    click
     mock
     pytestCheckHook
   ];
```

I tried to create an install check, but it didn't catch this, since the install check will have the check inputs...

**Comment by dotlambda** [comment]
> We need to move click to propagated build inputs.

It should be in `passthru.optional-dependencies.tool`.

**Comment by terlar** [comment]
Even it is optional, it should be added to `propagatedBuildInputs`, right? Haven't seen this convention before, but it makes sense, how does one build the package with the tool?

**Comment by dotlambda** [comment]
> Even it is optional, it should be added to `propagatedBuildInputs`, right? Haven't seen this convention before, but it makes sense, so one can override the optional build dependencies if you just want the lib?

See https://nixos.org/manual/nixpkgs/unstable/#python-optional-dependencies

**Comment by dotlambda** [comment]
> Cool, still should be optionally added to the `propagatedBuildInputs`. Otherwise the tool won't work. Right now it is optionally added to the `nativeCheckInputs`

Feel free to create a top-level attribute for the tool which does so.

**Review by terlar — APPROVED** [review]

**Pull request merged**
