### PR TITLE
Kernels 2021-07-15

### PR DESCRIPTION
**Pull request by TredwellGit**
###### Things done
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TredwellGit** [comment]
@ofborg test kernel-latest latestKernel.login

**Review by ymatsiuk — APPROVED** [review]

**Comment by fabianhjr** [comment]
Diff LGTM, building 5.13.2

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Comment by fabianhjr** [comment]
Compiled and ran 5.13.2 without issues

**Review by fabianhjr — APPROVED** [review]

**Comment by Ma27** [comment]
Can you elaborate why 5.12.17 was left out?

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/pull/128538#issuecomment-871520957
https://github.com/NixOS/nixpkgs/pull/128538#issuecomment-871561090
https://github.com/anthraxx/linux-hardened/releases

**Pull request merged**
