### PR TITLE
Clean sqlalchemy legacy

### LINKED ISSUE #14026: sqlite update broke pythonPackages.sqlalchemy[7-9]
## Basic info

To make sure that we are on the same page:
- Kernel: `Linux 4.4.5 #1-NixOS SMP Wed Mar 9 23:35:58 UTC 2016 x86_64 GNU/Linux`
- System: `16.03.171.0b5026f`
- Nix version: `nix-env (Nix) 1.11.2`
- Nixpkgs version: `master`

d86633386f2f2b786628b3ca14609a710cc6b993 broke legacy `sqlalchemy` packages (only tested with the `pythonPackages`-set).

``` bash
$ git bisect start 1941c806106c64ffe3b37734d23b8e3835b86c8f 36506df7fe1e087fd0af99f8eb6ee71759fffa81
$ git bisect run nix-build -A python27Packages.sqlalchemy7
…
d86633386f2f2b786628b3ca14609a710cc6b993 is the first bad commit
```

Multiple options to solve this:
- revert the commit (an update will eventually have to be done)
- make sure no-one depends on sqlalchemy legacy versions (this would be the best choice, but can require a big amount of work)
- re-introduce an outdated `sqlite` version only used by `sqlalchemy` legacy version (I’ll prepare a PR shortly that follows this path)

cc @edolstra

### PR DESCRIPTION
**Pull request by lsix**
###### Things done:
- [X] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
###### More

This is a first attempt to fix #14026 

`pkgs.buildbot` still explicitly require `sqlalchemy7`:

``` python
    setup_args['install_requires'] += [
        # sqlalchemy-0.8 betas show issues with sqlalchemy-0.7.2, so stick to 0.7.10
        'sqlalchemy >= 0.6, <= 0.7.10',
        # buildbot depends on sqlalchemy internals, and this is the tested
        # version.
        'sqlalchemy-migrate==0.7.2',
```

I did not update `virt-manager` that still require `sqlalchgemy_migrate_0_7`. Further testing is required before bumping the decency.

### CODE REVIEW

**Comment by FRidh** [comment]
looks good. Ready to merge?

**Comment by lancelotsix** [comment]
It is OK for me.

We still have the problem of `buildbot` which will continue to fail building, and I will do the same work for `sqlalchemy8` and `sqlalchemy9` ASAP.

**Comment by copumpkin** [comment]
Is `buildbot` expected to work right now? #8909

**Comment by copumpkin** [comment]
```
/tmp/nix-build-python2.7-SQLAlchemy-0.7.10.drv-0/SQLAlchemy-0.7.10/./lib/sqlalchemy/dialects/access/base.py:163: SAWarning: The access dialect is not yet ported to SQLAlchemy 0.6/0.7
  super(AccessDialect, self).__init__(**params)
....SSS.......S.....................SS.....................................................................................................S......SSS.SSS...............................SS.SS............SSSS.............S.......SSS.SS...............SSS..........S.......SSSSSS.SSSSS......................SSSSSSSS.SSS.SSSSS...............................................................................................................S.............................S..S.....................................................S..................SS...........S..S.S..S..SSS.S.S.S....SS...................................S...SS....SSSS..................SS......S.S....SS.SS....S.SS..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................S..................................................................................................................................................................................................................................................S....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................S.............S..S.................S...................................................................................SSSSSSSS...SSSSSSS...S..SS...SS...............S.............................S...........................................................................................................S..........................................................................................................................................................S...SS...S.S...S....SS.....................................................................................................................................................................................................................................................................S......S...............FE...........................S..........S..................S..SSS................................................................................................................................................................SSSSSS
======================================================================
ERROR: test.sql.test_query.QueryTest.test_column_accessor_sqlite_translated
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/09g5qrf4lbsh2qcqwb06ngg50dhr9ckh-python2.7-nose-1.3.7/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "<string>", line 1, in <lambda>
  File "/tmp/nix-build-python2.7-SQLAlchemy-0.7.10.drv-0/SQLAlchemy-0.7.10/./test/lib/exclusions.py", line 45, in decorate
    return fn(*args, **kw)
  File "/tmp/nix-build-python2.7-SQLAlchemy-0.7.10.drv-0/SQLAlchemy-0.7.10/./test/sql/test_query.py", line 800, in test_column_accessor_sqlite_translated
    eq_(r['query_users.user_id'], 1)
  File "/tmp/nix-build-python2.7-SQLAlchemy-0.7.10.drv-0/SQLAlchemy-0.7.10/./lib/sqlalchemy/engine/base.py", line 2615, in __getitem__
    processor, obj, index = self._parent._key_fallback(key)
  File "/tmp/nix-build-python2.7-SQLAlchemy-0.7.10.drv-0/SQLAlchemy-0.7.10/./lib/sqlalchemy/engine/base.py", line 2834, in _key_fallback
    expression._string_or_unprintable(key))
NoSuchColumnError: "Could not locate column in row for column 'query_users.user_id'"

======================================================================
FAIL: test.sql.test_query.QueryTest.test_column_accessor_sqlite_raw
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/09g5qrf4lbsh2qcqwb06ngg50dhr9ckh-python2.7-nose-1.3.7/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "<string>", line 1, in <lambda>
  File "/tmp/nix-build-python2.7-SQLAlchemy-0.7.10.drv-0/SQLAlchemy-0.7.10/./test/lib/exclusions.py", line 45, in decorate
    return fn(*args, **kw)
  File "/tmp/nix-build-python2.7-SQLAlchemy-0.7.10.drv-0/SQLAlchemy-0.7.10/./test/sql/test_query.py", line 783, in test_column_accessor_sqlite_raw
    assert 'user_id' not in r
AssertionError

----------------------------------------------------------------------
Ran 4069 tests in 138.966s

FAILED (SKIP=145, errors=1, failures=1)
builder for ‘/nix/store/xl0n3hwa2xkakm6swbwx3v1m77l9lwf8-python2.7-SQLAlchemy-0.7.10.drv’ failed with exit code 1
```

**Pull request merged**
