### PR TITLE
pythonPackages.matrix-nio: 0.15.2 -> 0.18.0, update build system and dependencies

### PR DESCRIPTION
**Pull request by mjlbach**
###### Motivation for this change

I added an upstream patch for matrix-nio so that it can A) be used for dendrite (generally) and B) can be used for nixos tests for dendrite (and synapse) since the python matrix SDK is not actively maintained.

I'm happy to split this PR out into multiple PRs, but the changes are all linked together.

###### Things done
1. add python-socks, a new depdency of aiohttp-socks
2. update aiohttp-socks
3. update unpaddedbase64, update build system to poetry
3. update matrix-nio, update build system to poetry 

cc: 
matrix-weechat maintainers @tilpner @emily

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [] macOS
   -  [x] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mjlbach** [comment]
pantalaimon also needs a bump, I can take care of that

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 121942` at c044015b run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/1bc558dab4414676bca5ea233272a0cd">pantalaimon</a></li>
  </ul>
</details>
<details>
  <summary>1 package skipped due to time constraints:</summary>
  <ul>
    <li>electrum</li>
  </ul>
</details>
<details>
  <summary>15 packages built successfully:</summary>
  <ul>
    <li>matrix-commander</li>
    <li>matrix-synapse</li>
    <li>mautrix-signal</li>
    <li>mirage-im</li>
    <li>python38Packages.aiohttp-socks</li>
    <li>python38Packages.matrix-nio</li>
    <li>python38Packages.python-socks</li>
    <li>python38Packages.signedjson</li>
    <li>python38Packages.unpaddedbase64</li>
    <li>python39Packages.aiohttp-socks</li>
    <li>python39Packages.matrix-nio</li>
    <li>python39Packages.python-socks</li>
    <li>python39Packages.signedjson</li>
    <li>python39Packages.unpaddedbase64</li>
    <li>weechatScripts.weechat-matrix</li>
  </ul>
</details>
<details>
  <summary>6 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/unpaddedbase64/default.nix:23:3:
```
   |
23 |   meta = with lib; {
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-include-tests.md">python-include-tests</a>

Consider adding a `checkPhase` for tests, or if not feasible, `pythonImportsCheck`.

Near pkgs/development/python-modules/aiohttp-socks/default.nix:21:0:
```
   |
21 |     description = "SOCKS proxy connector for aiohttp";
   | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-python-tests.md">no-python-tests</a>

Test runner could not discover any test cases: ‘Ran 0 tests in 0.000s’
Near pkgs/development/python-modules/python-socks/default.nix:17:0:
```
   |
17 |     description = "Core proxy client (SOCKS4, SOCKS5, HTTP) functionality for Python";
   | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/aiohttp-socks/default.nix:20:3:
```
   |
20 |   meta = {
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-include-tests.md">python-include-tests</a>

Consider adding a `checkPhase` for tests, or if not feasible, `pythonImportsCheck`.

Near pkgs/development/python-modules/matrix-nio/default.nix:61:0:
```
   |
61 |     description = "A Python Matrix client library, designed according to sans I/O principles";
   | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-include-tests.md">python-include-tests</a>

Consider adding a `checkPhase` for tests, or if not feasible, `pythonImportsCheck`.

Near pkgs/development/python-modules/unpaddedbase64/default.nix:25:0:
```
   |
25 |     description = "Unpadded Base64";
   | ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

**Comment by symphorien** [comment]
I pushed a bump of pantalaimon and enabled tests on matrix-nio.

**Review by symphorien — APPROVED** [review]
I tested pantalaimon.

**Comment by mjlbach** [comment]
I fixed up my commit messages to match the history, I can't merge, so feel free to merge if there are no subsequent/other reviews :)

**Pull request merged**
