### PR TITLE
Linux kernel updates 2023-09-13

### LINKED ISSUE #250166: tpm_crb: probe of MSFT0101:00 failed with error 378
### Describe the bug
I use tpm + luks, but recently when the kernel updating to 6.4.11, the `tpm_crb` can't find `tpm` devices. 
And, if I switch to old kernel like 6.1, it can't work too.

### Steps To Reproduce
1. Use the latest unstable
2.
```nix
  boot = {
    kernelPackages = pkgs.linuxPackages_latest;
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "nvme"
        "usbhid"
        "usb_storage"
        "sd_mod"
        "tpm"
        "tpm_tis"
        "tpm_crb"
      ];
      systemd.enable = true;
    };

    tmp.useTmpfs = true;
  };
```

### Expected behavior
`tpm` work correctly.

### Screenshots
图片
图片

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.11, NixOS, 23.11 (Tapir), 23.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(yufei): `""`
 - nixpkgs: `/nix/store/5mj1vfslaf052b8s9nnbz31fb2l1qwdi-source`
```

### PR DESCRIPTION
**Pull request by RaitoBezarius**
## Description of changes

This fixes #250166 notably…
https://lwn.net/Articles/944355/

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabianhjr** [comment]
Small nitpick regarding the merge request title, normally the date is used to refer to all updates up to a given date.

Previous two examples:

- https://github.com/NixOS/nixpkgs/pull/253991
- https://github.com/NixOS/nixpkgs/pull/252898

**Review by K900 — APPROVED** [review]
Diff LGTM. Double checked to see if all the hashes are updated.

**Comment by K900** [comment]
> Small nitpick regarding the merge request title, normally the date is used to refer to all updates up to a given date.

Does anyone actually read those?

**Comment by Ma27** [comment]
>  linux-rt_5_10: 5.10.186-rt91 -> 5.10.192-rt92 

I'm pretty sure that this one won't build, 5.10.192 is known to not compile (IIRC). Rebased it out of my last two bumps ;-)

**Comment by RaitoBezarius** [comment]
Thanks!

**Comment by fabianhjr** [comment]
Building 6.5.3 :3

**Review by fabianhjr — APPROVED** [review]
Changes LGTM, built and booted 6.5.3

**Comment by fabianhjr** [comment]
Upon double checking, 5.10.192-rt92 is still on this merge request and per Ma27 comment it is borked unu

https://github.com/NixOS/nixpkgs/pull/254977#issuecomment-1718033143

**Comment by fabianhjr** [comment]
Rebased but the only change should have been to drop the 5.10.192-rt92 kernel update as per @Ma27 comment.

Apologies for the ping mweinelt. UnU

**Review by fabianhjr — APPROVED** [review]

**Pull request merged**
