### PR TITLE
q4wine: init at 1.3.13

### PR DESCRIPTION
**Pull request by rkitover**
Qt GUI application for Wine for managing prefixes and applications.

Signed-off-by: Rafael Kitover <rkitover@gmail.com>

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by legendofmiracles — CHANGES_REQUESTED** [review]

**Comment by legendofmiracles** [comment]
Commit & PR title should be `q4wine: init at 1.3.13`

**Comment by legendofmiracles** [comment]
Result of `nixpkgs-review pr 142087` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>q4wine</li>
  </ul>
</details>

**Comment by rkitover** [comment]
@legendofmiracles ping, anything else that needs to be done here? That one CI run has been queued for weeks now.

**Comment by aanderse** [comment]
Sorry for the delay @rkitover ... but thanks for the contribution! :tada:

**Comment by legendofmiracles** [comment]
> @legendofmiracles ping, anything else that needs to be done here? That one CI run has been queued for weeks now.

I can't merge any PRs, but nevertheless thanks for your contribution!

**Pull request merged**
