### PR TITLE
zpool-trim.service: Enable choosing pools

### PR DESCRIPTION
**Pull request by ElvishJerricco**
###### Motivation for this change

Unlike `services.zfs.autoScrub`, you can't choose which pools to affect with `services.zfs.trim`. This was an issue for me when my HDD pool caused any userland `zfs`/`zpool` processes to hang for some reason while it tried to trim the HDD pool (and failed after 5min, probably from systemd killing it, which then allowed the userland processes to continue). When I used this patch to only trim my SSD pool, everything went fine.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @Mic92, is this a good enough reason to go back to `script` from `ExecStart`? I could do it with a one-liner, but it just seemed very messy.

### CODE REVIEW

**Comment by ElvishJerricco** [comment]
Also, is this the sort of thing that's acceptable to backport to 19.09?

**Comment by Mic92** [comment]
Do you still need this option with https://github.com/NixOS/nixpkgs/pull/81610

**Comment by kmcopper** [comment]
This is still useful to prevent the errors from happening in the first place. This can also speed up the loop if you only want specific pools trimmed.

**Comment by Mic92** [comment]
It no longer should break on errors. I also don't see how speed is a concern when this loop runs only once a week.

**Comment by kmcopper** [comment]
It was more about efficiency and lack of polluting logs with error messages to me.

**Pull request closed without merging**
