### PR TITLE
gcc-arm-embedded: use numVersion as version, rename version to release

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

- followup to 009668465ed07712a51d0b00e33e2d9e00d203ad (merged with https://github.com/NixOS/nixpkgs/pull/130005)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
@siriobalmelli What do you think about this change? That way we could use gcc-arm-embedded.version (same as we can use gcc.version).

**Comment by prusnak** [comment]
@GrahamcOfBorg build gcc-arm-embedded-6 gcc-arm-embedded-7 gcc-arm-embedded-8 gcc-arm-embedded-9 gcc-arm-embedded-10

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 130008` at d66917c4 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package skipped due to time constraints:</summary>
  <ul>
    <li>tinygo</li>
  </ul>
</details>
<details>
  <summary>4 packages built successfully:</summary>
  <ul>
    <li>blackmagic</li>
    <li>gcc-arm-embedded (gcc-arm-embedded-10)</li>
    <li>gcc-arm-embedded-9</li>
    <li>opentx</li>
  </ul>
</details>
<details>
  <summary>10 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl3` is a deprecated license, please check if project uses `gpl3Plus` or `gpl3Only` and change `meta.license` accordingly.

Near pkgs/development/compilers/gcc-arm-embedded/9/default.nix:50:5:
```
   |
50 |     license = with licenses; [ bsd2 gpl2 gpl3 lgpl21 lgpl3 mit ];
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`lgpl3` is a deprecated license, please check if project uses `lgpl3Plus` or `lgpl3Only` and change `meta.license` accordingly.

Near pkgs/development/compilers/gcc-arm-embedded/10/default.nix:50:5:
```
   |
50 |     license = with licenses; [ bsd2 gpl2 gpl3 lgpl21 lgpl3 mit ];
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/development/compilers/gcc-arm-embedded/10/default.nix:50:5:
```
   |
50 |     license = with licenses; [ bsd2 gpl2 gpl3 lgpl21 lgpl3 mit ];
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`lgpl3` is a deprecated license, please check if project uses `lgpl3Plus` or `lgpl3Only` and change `meta.license` accordingly.

Near pkgs/development/compilers/gcc-arm-embedded/9/default.nix:50:5:
```
   |
50 |     license = with licenses; [ bsd2 gpl2 gpl3 lgpl21 lgpl3 mit ];
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`lgpl21` is a deprecated license, please check if project uses `lgpl21Plus` or `lgpl21Only` and change `meta.license` accordingly.

Near pkgs/development/compilers/gcc-arm-embedded/9/default.nix:50:5:
```
   |
50 |     license = with licenses; [ bsd2 gpl2 gpl3 lgpl21 lgpl3 mit ];
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/compilers/gcc-arm-embedded/10/default.nix:33:3:
```
   |
33 |   installPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/compilers/gcc-arm-embedded/9/default.nix:33:3:
```
   |
33 |   installPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl3` is a deprecated license, please check if project uses `gpl3Plus` or `gpl3Only` and change `meta.license` accordingly.

Near pkgs/development/compilers/gcc-arm-embedded/10/default.nix:50:5:
```
   |
50 |     license = with licenses; [ bsd2 gpl2 gpl3 lgpl21 lgpl3 mit ];
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/development/compilers/gcc-arm-embedded/9/default.nix:50:5:
```
   |
50 |     license = with licenses; [ bsd2 gpl2 gpl3 lgpl21 lgpl3 mit ];
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`lgpl21` is a deprecated license, please check if project uses `lgpl21Plus` or `lgpl21Only` and change `meta.license` accordingly.

Near pkgs/development/compilers/gcc-arm-embedded/10/default.nix:50:5:
```
   |
50 |     license = with licenses; [ bsd2 gpl2 gpl3 lgpl21 lgpl3 mit ];
   |     ^
```
</li>
  </ul>
</details>

**Comment by siriobalmelli** [comment]
> @siriobalmelli What do you think about this change? That way we could use gcc-arm-embedded.version (same as we can use gcc.version).

This is brilliant, thank you :)

**Pull request merged**
