### PR TITLE
Clamsmtp package and module

### PR DESCRIPTION
**Pull request by Ekleog**
###### Motivation for this change

Add a package and a module for `clamsmtp`.

Note this combo's quite well with https://github.com/NixOS/nixpkgs/pull/33228 (and is actually the reason for my adding the `PrivateTmp` workaround)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ekleog** [comment]
Hmm, doesn't work any better with an additional `PrivateTmp` as per last push -f :/ (also, I can't just add in `PrivateNetwork`, as clamsmtp is indeed supposed to listen on a port on localhost)

**Comment by joachifm** [comment]
Vexing. Is clamsmtp always started after the clamav daemon? That's the only other thing I can think of :( Regrettably, I have little practical experience with namespace joining, only what I've read, so take my comments with a helping of salt.

**Comment by Ekleog** [comment]
Shame on me. Somehow when testing I didn't notice this...

Now it looks like `clamsmtp` works with `clamdscan` and without `PrivateTmp`, meaning https://github.com/NixOS/nixpkgs/pull/33228 is no longer required for this module to work to full capacity.

Thanks! :)

**Comment by joachifm** [comment]
Resolved conflicts & merged at cb506e6e2ed9133b43eb0c54699b8df4c9957cdf. Thank you

**Comment by Ekleog** [comment]
:)

**Pull request closed without merging**
