### PR TITLE
prismlauncher: 6.3 -> 7.0

### PR DESCRIPTION
**Pull request by getchoo**
###### Description of changes

this updates prismlauncher to v7.0. the only real change is that cmark has been added as a dependency and prism now builds with qt6 by default.

i have also added myself as comaintainer at the advice of scrumplex :)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Scrumplex — APPROVED** [review]
Builds and works fine!

**Comment by Scrumplex** [comment]
Please merge #234104 before merging this, so that the PR backport works

**Comment by Minion3665** [comment]
> Please merge #234104 before merging this, so that the auto backport works

are we sure this is backportable? "Version updates which include new functionality" are fine, but this has some breaking changes too so I don't think it fits

> i have also added myself as comaintainer at the advice of scrumplex :)

I also support this, it'll be awesome to have you as a maintainer!

**Comment by Scrumplex** [comment]
> but this has some breaking changes too so I don't think it fits

I don't think there is anything in here that would be "breaking"

**Comment by getchoo** [comment]
i was about to say the same. i don't know of any changes the user would notice using the wrapped packages (as they're virtually the same as before in usage), and unwrapped packages are "new functionality."

though, if this isn't acceptable i could update the pr to only backport the other changes :)

**Review by Scrumplex — APPROVED** [review]

**Review by Scrumplex — APPROVED** [review]

**Review by Minion3665 — APPROVED** [review]

**Pull request merged**
