### PR TITLE
python3Packages.Nikola: disable failing test

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
ZHF: #122042

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @NixOS/nixos-release-managers 

@ofborg build python3.pkgs.Nikola

### CODE REVIEW

**Comment by dotlambda** [comment]
@ofborg build python3.pkgs.Nikola

**Comment by mweinelt** [comment]
Pywemo also has issues with the libxml2 2.9.12 upgrade. #124165

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 124320` at c57d0a54 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.Nikola</li>
    <li>python39Packages.Nikola</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
Let's try whether it actually works on Darwin (see https://github.com/NixOS/nixpkgs/issues/32087):

@ofborg build python3.pkgs.Nikola

**Comment by risicle** [comment]
Should we be running round disabling loads of tests rather than fixing the apparently buggy libxml2 2.9.12?

**Comment by risicle** [comment]
Also testing on darwin - `Nikola` is marked as broken on darwin but if I remove that it fails due to depending on `watchdog`.

**Review by jonringer — COMMENTED** [review]
you'll need to remove `broken = stdenv.isDarwin;` from meta

**Comment by dotlambda** [comment]
> you'll need to remove `broken = stdenv.isDarwin;` from meta

I tried that but removed the commit doing so again. As @risicle mentioned watchdog doesn't build on Darwin so there's no point in trying.

> Should we be running round disabling loads of tests rather than fixing the apparently buggy libxml2 2.9.12?

Is that still an option for 21.05?

**Comment by risicle** [comment]
I don't imagine we can ship 21.05 _with_ the glaring libxml2 bug.

**Comment by jonringer** [comment]
> I don't imagine we can ship 21.05 _with_ the glaring libxml2 bug.

The patch is in both of the staging-next channels, we can also target that base branch

**Pull request closed without merging**
