### PR TITLE
opensmtpd: 6.0.3p1 -> 6.4.0

### PR DESCRIPTION
**Pull request by Ekleog**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ekleog** [comment]
Note to self: OpenSMTPD will likely drop compatibility with OpenSSL for 6.4.0 release, so will need switch to LibreSSL and removal of the `CERT` part of the patch.

**Comment by Ekleog** [comment]
@rickynils @obadz This PR is now ready, as OpenSMTPD 6.4.0 has been merged

@GrahamcOfBorg test opensmtpd

**Comment by Ekleog** [comment]
No security fixes mentioned in the changelog at least :)

**Comment by Ekleog** [comment]
Thank you! :)

**Comment by obadz** [comment]
No, thank you!

**Comment by Izorkin** [comment]
This package error worked with pki certificates

```
pki mail.example.com cert "/etc/ssl/private/mail.example.com.crt"
pki mail.example.com key "/etc/ssl/private/mail.example.com.key"
ca mail.example.com cert "/etc/ssl/certs/ca-bundle.crt"

listen on 0.0.0.0 tls pki mail.example.com ca mail.example.com

action "local" mbox
match from local for local action "local"
```
error -
```
smtpd -d -f /etc/smtpd.conf -v

debug: init ssl-tree
info: loading pki information for mail.example.com
debug: init ca-tree
info: loading CA information for mail.example.com
debug: init ssl-tree
info: loading pki keys for mail.example.com
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
info: OpenSMTPD 6.4.0p1 starting
debug: init ssl-tree
info: loading pki information for mail.example.com
debug: init ca-tree
info: loading CA information for mail.example.com
debug: init ssl-tree
info: loading pki keys for mail.example.com
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
setup_peer: klondike -> control[1635] fd=4
setup_peer: klondike -> pony express[1637] fd=5
setup_done: ca[1634] done
debug: init ssl-tree
setup_proc: klondike done
info: loading pki information for mail.example.com
debug: init ca-tree
info: loading CA information for mail.example.com
debug: init ssl-tree
info: loading pki keys for mail.example.com
debug: using "fs" queue backend
debug: init ssl-tree
info: loading pki information for mail.example.com
debug: init ca-tree
info: loading CA information for mail.example.com
debug: init ssl-tree
info: loading pki keys for mail.example.com
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
setup_peer: pony express -> control[1635] fd=4
setup_peer: pony express -> klondike[1634] fd=5
setup_peer: pony express -> lookup[1636] fd=6
setup_peer: pony express -> queue[1638] fd=7
debug: init ssl-tree
info: loading pki information for mail.example.com
debug: init ca-tree
info: loading CA information for mail.example.com
debug: init ssl-tree
info: loading pki keys for mail.example.com
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
setup_peer: scheduler -> control[1635] fd=4
setup_peer: scheduler -> queue[1638] fd=5
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
setup_peer: control -> klondike[1634] fd=4
setup_peer: control -> lookup[1636] fd=5
setup_peer: control -> pony express[1637] fd=6
setup_peer: control -> queue[1638] fd=7
setup_peer: control -> scheduler[1639] fd=8
setup_done: control[1635] done
setup_proc: control done
debug: init ssl-tree
info: loading pki information for mail.example.com
debug: init ca-tree
info: loading CA information for mail.example.com
debug: init ssl-tree
info: loading pki keys for mail.example.com
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
setup_peer: queue -> control[1635] fd=4
setup_peer: queue -> pony express[1637] fd=5
setup_peer: queue -> lookup[1636] fd=6
setup_peer: queue -> scheduler[1639] fd=7
debug: init ssl-tree
info: loading pki information for mail.example.com
debug: init ca-tree
info: loading CA information for mail.example.com
debug: init ssl-tree
info: loading pki keys for mail.example.com
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
setup_peer: lookup -> control[1635] fd=4
setup_peer: lookup -> pony express[1637] fd=5
setup_peer: lookup -> queue[1638] fd=6
setup_done: lka[1636] done
setup_proc: lookup done
setup_proc: pony express done
setup_done: pony[1637] done
debug: ca_engine_init: using RSA privsep engine
setup_done: queue[1638] done
setup_done: scheduler[1639] done
smtpd: setup done
debug: parent_send_config_ruleset: reloading
debug: parent_send_config: configuring pony process
debug: parent_send_config: configuring ca process
debug: init private ssl-tree
debug: parent -> ca: pipe closed
smtpd: process ca socket closed
debug: smtp: listen on 0.0.0.0 port 25 flags 0x401 pki "mail.example.com" ca "mail.example.com"
debug: pony: rsae_init
setup_proc: scheduler done
debug: bounce warning after 4h
debug: control -> klondike: pipe closed
debug: control agent exiting
debug: scheduler -> control: pipe closed
debug: scheduler agent exiting
setup_proc: queue done
debug: lka -> parent: pipe closed
debug: lookup agent exiting
debug: queue -> parent: pipe closed
debug: queue agent exiting

```
@Ekleog @obadz

**Comment by Ekleog** [comment]
@Izorkin A few questions:
 * Do you have this problem without PKI?
 * Do I guess correctly that the server just exits after this log?
 * Does it have a particular exit status, or is it returning 0? (`echo $?`)
 * Could you add timing information, eg. with `haskellPackages.timestamper`? (disclaimer: never tried it) This “bounce warning after 4h” makes me wonder if it's all happening at startup or some time after
 * Are you sure your network is up before OpenSMTPD starts running and available to it? I seem to remember having seen errors like this (ie. server exiting with no readable error) with 6.0.3p1 when my configuration had a race condition and sometimes OpenSMTPD started before the network (I was listening on a VPN interface), leading to a similar exit-without-error. Maybe some optimization done on OpenSMTPD is triggering a similar race condition in your code, or OpenSMTPD is for some reason unable to open its listening socket?

**Comment by Izorkin** [comment]
I run manually with the configuration in /etc/smtpd.conf. If I delete lines with pki - opensmtp worked.

**Comment by Izorkin** [comment]
Porcess exit with status 1 and message - smtpd: process ca socket closed

**Comment by Ekleog** [comment]
@Izorkin In addition to the timestamping and checks about network availability, can you check your `journalctl` to see if there is a segfault being logged, and if so paste it here?

**Pull request merged**
