### PR TITLE
stash: 0.25.1 -> 0.26.1; add updateScript

### PR DESCRIPTION
**Pull request by DrakeTDL**
## Description of changes

[Changes between releases](https://github.com/stashapp/stash/compare/v0.25.1...v0.26.1)

https://github.com/stashapp/stash/releases/tag/v0.26.0
https://github.com/stashapp/stash/releases/tag/v0.26.1

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by PeterSchlangsen** [comment]
Maybe this is the wrong place to discuss this, I didn't catch the original pull request for the package, but why was it included in nixpkgs? There is an open pull request at https://github.com/NixOS/nixpkgs/pull/288428/ that covered this as well, but also

- actually built the package from source instead of using the prebuilt ones
- provided a module to use the service
- did provide an update script

The only issue blocking the original request was wording (the word "porn"), and this package didn't actually improve on that. I'd rather have the linked version in nixpkgs for the module and actually building from source.

**Comment by h7x4** [comment]
@PeterSchlangsen The PR that introduced the package is #316452. From the thread, it doesn't seem like anyone realized it was a competing PR, and that happens from time to time. There's no reason not to bring the other changes as well though, rebasing on top of the existing package. But this PR is orthogonal to this issue, I think the best place to bring up that discussion would be the PR with the module.

**Comment by Golo300** [comment]
I was the author of the https://github.com/NixOS/nixpkgs/pull/316452 PR. As @h7x4 mentioned I didn't release that it was a a competing PR. That was my bad and I agree that the changes of the original PR should be added. I am just wondering if it is effective to wait for the https://github.com/NixOS/nixpkgs/pull/288428 to be active again since there where no activities of the original author in months and the mention of this PR also doesn't seem to update anything. Maybe open a new PR with the changes mentioned by @PeterSchlangsen would be better. But I have to say that https://github.com/NixOS/nixpkgs/pull/316452 was my first PR here so I am very Inexperienced.

**Comment by DrakeTDL** [comment]
Fair enough. If no progress happens on https://github.com/NixOS/nixpkgs/pull/288428 by next month; I'll open a new PR with the mentioned changes.

**Pull request closed without merging**
