### PR TITLE
remove godot_headers in favour of a dev output on godot

### PR DESCRIPTION
**Pull request by Twey**
###### Motivation for this change
It turns out that `godot_headers` is not guaranteed to be in sync with `godot`.  Rather than suffer two packages that must be in sync, let's copy the actual generated headers from the `godot` build out into a `dev` output, as is conventional.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Twey** [comment]
(thanks to @tilpner for pointing this out)

**Comment by xeji** [comment]
This should probably go into 18.03 as well since we just applied the change introducing `godot_headers` there.

**Comment by Twey** [comment]
Did this make it into 18.03 in the end?

**Review by matthewbauer — CHANGES_REQUESTED** [review]
Looks good to me! Can you resolve the merge conflicts?

**Comment by Twey** [comment]
Rebased!

**Review by xeji — APPROVED** [review]

**Pull request merged**
