### PR TITLE
jetbrains.plugins: add asciidoc plugin

### PR DESCRIPTION
**Pull request by britter**

### CODE REVIEW

**Comment by bjornfor** [comment]
How was this diff made? Some updateScript? (If so, how was it run?) Would it be possible to have one commit "update plugins" and another "add asciidoc plugin"? Mixing the changes makes it harder to review.

**Comment by britter** [comment]
@bjornfor it was created by following https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/jetbrains/readme.md#how-to-add-a-new-plugin-to-nixpkgs. I was also surprised to see updates to the other plugins. But that seems to be the way `updatePlugins.py` works.

**Comment by liff** [comment]
Also included in #285605.

**Comment by britter** [comment]
Closing in favor of #285605

**Pull request closed without merging**
