### PR TITLE
nixos/virtualbox-guest: support VMSVGA graphics adapter

### PR DESCRIPTION
**Pull request by bachp**
This makes VMSVGA the default and recommended graphics adapter for virtualbox.

###### Motivation for this change

Currently with virtualbox 6.1.6 [guest resizing is broken](https://www.virtualbox.org/ticket/19496).

Also Virtualbox complains that `VBoxVGA` is not the recommended graphics adaptere for linux guests, and that `VMSVGA` should be used. In newer versions of Virtualbox (6.1+) `VMSVGA` seems to be the only adapter supporting 3D acceleration (https://github.com/NixOS/nixpkgs/issues/81850).

This PR makes `VMSVGA` work out of the box in NixOS, including Auto resize and 3D acceleration.

###### Things done

I tested the resulting machine with:
-  `VMSVGA` with 3D (OK)
- `VMSVGA` without 3D (OK)
- `VBoxVGA` (OK, [no auto resize](https://www.virtualbox.org/ticket/19496))

`VBoxVGA` is still supported, but I could not test autoresizing as it is currently broken, even before my changes.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by takeda** [comment]
@bachp thanks for this, I run into this issue and was looking for a solution.

One question, I noticed that `VBoxClient --vmsvga` when running as root also resizes the screen, while seems like currently what's started is `VBoxClient --vmsvga-x11` which uses xrandr. Is there a benefit of libxrandr over DRM?

I'm also wondering if virtualbox guest addition should install libnotify when that package is installed with x11, when I added this package the error popup shows up, which would help diagnosing problems like this in the future.

Will this be backported in 20.03?

**Comment by blitz** [comment]
AFAIK the VBoxVGA model is somewhat deprecated / in maintenance mode, so switching to VMSVGA is the right choice.

I've also verified that the screen resizing now works with VMSVGA

**Review by blitz — APPROVED** [review]

**Comment by jtojnar** [comment]
Indeed looks like it is needed. Without it, the appliance built with `nix-build nixos/release.nix -A ova.x86_64-linux` is imported with VBoxVGA as graphics controller; with it it uses VMSVGA correctly so we need that to match the documentation.

**Comment by bachp** [comment]
@jtojnar I updated the PR to make vmsvga the default adapter on the generated OVA.

@takeda I couldn't get `VBoxClient --vmsvga` working, even when running as root.

**Review by jtojnar — APPROVED** [review]

**Comment by takeda** [comment]
@bachp I was able to run it by adding:
```nix
 systemd.services.virtualbox-resize = {
    description = "VirtualBox Guest Screen Resizing";

    wantedBy = [ "multi-user.target" ];
    requires = [ "dev-vboxguest.device" ];
    after = [ "dev-vboxguest.device" ];

    unitConfig.ConditionVirtualization = "oracle";

    serviceConfig.ExecStart = "@${config.boot.kernelPackages.virtualboxGuestAdditions}/bin/VBoxClient -fv --vmsvga";
  };
```
to `configuration.nix`, note that `VBoxClient --vmsvga-x11` should be removed from `VBoxClient-all`.

Looking at other distros they also add it as a service.

**Comment by bachp** [comment]
@takeda I think we should take this up in a separate PR improving on this one. Are you OK with this?

**Comment by takeda** [comment]
@bachp sorry I just noticed your response. Yes, I think it is better to have something working right now than nothing.

**Comment by jtojnar** [comment]
Anything remaining here?

**Pull request merged**
