### PR TITLE
Linux kernel updates 2024-02-01

### PR DESCRIPTION
**Pull request by Ma27**
## Description of changes
<del>A draft until everything got built.</del>

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by K900 — APPROVED** [review]
Diff LGTM

**Comment by alyssais** [comment]
@OfBorg test kernel-generic.linux_6_7 kernel-generic.linux_6_6 kernel-generic.linux_6_1

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 285502` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>linuxKernel.kernels.linux_6_1</li>
    <li>linuxKernel.kernels.linux_6_1.dev</li>
    <li>linuxKernel.kernels.linux_6_6</li>
    <li>linuxKernel.kernels.linux_6_6.dev</li>
    <li>linuxKernel.kernels.linux_6_7</li>
    <li>linuxKernel.kernels.linux_6_7.dev</li>
    <li>linuxKernel.kernels.linux_latest_libre</li>
    <li>linuxKernel.kernels.linux_latest_libre.dev</li>
    <li>linuxKernel.kernels.linux_libre</li>
    <li>linuxKernel.kernels.linux_libre.dev</li>
    <li>linuxKernel.kernels.linux_rt_6_1</li>
    <li>linuxKernel.kernels.linux_rt_6_1.dev</li>
  </ul>
</details>

**Review by fabianhjr — APPROVED** [review]
diff lgtm

**Comment by kirillrdy** [comment]
bisected issue to this  1eb315f20dc568220f5f73c6e850851005daa9a1 
6.6.15 upgrade breaks nvidia-x11

```
error: builder for '/nix/store/zi4id3fmccf6imsvhg32cylh44r0fvj3-nvidia-x11-545.29.06-6.6.15.drv' failed with exit code 2;
       last 10 log lines:
       >   MODPOST /build/NVIDIA-Linux-x86_64-545.29.06/kernel/Module.symvers
       > ERROR: modpost: GPL-incompatible module nvidia.ko uses GPL-only symbol '__rcu_read_unlock'
       > ERROR: modpost: GPL-incompatible module nvidia.ko uses GPL-only symbol '__rcu_read_lock'
       > make[4]: *** [/nix/store/ry1k4zwx3dsf3aqw8rfc7r6rfryspiln-linux-6.6.15-dev/lib/modules/6.6.15/source/scripts/Makefile.modpost:145: /build/NVIDIA-Linux-x86_64-545.29.06/kernel/Module.symvers] Error 1
       > make[3]: *** [/nix/store/ry1k4zwx3dsf3aqw8rfc7r6rfryspiln-linux-6.6.15-dev/lib/modules/6.6.15/source/Makefile:1865: modpost] Error 2
       > make[2]: *** [/nix/store/ry1k4zwx3dsf3aqw8rfc7r6rfryspiln-linux-6.6.15-dev/lib/modules/6.6.15/source/Makefile:234: __sub-make] Error 2
       > make[2]: Leaving directory '/nix/store/ry1k4zwx3dsf3aqw8rfc7r6rfryspiln-linux-6.6.15-dev/lib/modules/6.6.15/build'
       > make[1]: *** [Makefile:234: __sub-make] Error 2
       > make[1]: Leaving directory '/nix/store/ry1k4zwx3dsf3aqw8rfc7r6rfryspiln-linux-6.6.15-dev/lib/modules/6.6.15/source'
       > make: *** [Makefile:82: modules] Error 2
       For full logs, run 'nix log /nix/store/zi4id3fmccf6imsvhg32cylh44r0fvj3-nvidia-x11-545.29.06-6.6.15.drv'.
```

**Comment by Kiskae** [comment]
@kirillrdy will be fixed by #286058, all 3 kernel branches are affected

**Pull request merged**
