### PR TITLE
Refactor icu and init 74.2

### PR DESCRIPTION
**Pull request by afh**
ℹ️ This draft PR is my understanding of how the icu package could be improved in a similar vein as #289690.

### TODO
If this PR is headed in the right direction and people see value in pursuing this approach close the following PRs
- [ ] #289782
- [ ] #289783

## Description of changes

* Add `icu/default.nix` containing the icu version specific packages
* Remove `icu/[0-9]*.nix` 
* Use `hash` instead of `sha256` in `icu/base.nix`
* Includes changes proposed in #289782 **icu73: use buildPackages.icu73 for nativeBuildRoot**
* Update `all-packages.nix` accordingly using `callPackages`

I'm uncertain whether the changes proposed here properly affect `buildPackages.icu[0-9]{2}` or whether more work is needed.
I'd appreciated if someone could chime in on this.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by afh** [comment]
ℹ️ **icu, icu.passthru.tests, icu74, icu74.passthru.tests on x86_64-darwin** failed due to `error:** building of '/nix/store/1imr8dj9jf3f6j5sqg0sl1y45pmksi7m-llvm-16.0.6.drv^dev' from .drv file timed out after 3600 seconds`

**Comment by 7c6f434c** [comment]
I am confused why icu66 hash has changed here (I am fine with any reason, the impact is small, it;s just slightly mysterious…)

**Comment by afh** [comment]
Thanks for pointing this out, @7c6f434c, the hashes have changed as I moved from `sha256` to `hash`, the latter using SRI format (`nix hash to-sri`).

Going over the changes once again I notice that the hashes for `icu67` and `icu66` are the same, Yikes! Please allow me to ~~doubletriple~~quadruple check and correct this. Be right back!🫨

**Comment by 7c6f434c** [comment]
Yeah I meant derivation hash change, the rest seem to be preserved (as SRI and non-SRI forms of sha256 are supposed to be treated as the same actual fixed-output requirement and thus not change the output hash). So I guess it's 66 and the new 74 that need the most attention, if the rest has the same builds as before and nobody has complained, probably they are fine…

**Comment by afh** [comment]
I've corrected the `hash` for `icu66` and checked the other hashes using:

```sh
grep version\ = pkgs/development/libraries/icu/default.nix > versions.txt
for v in $(cut -d'"' -f2 versions.txt); do print "version = \"$v\";"; nix-prefetch-url https://github.com/unicode-org/icu/releases/download/release-${v/./-}/icu4c-${v/./_}-src.tgz | xargs nix hash to-sri --type sha256; print; done 2>/dev/null
```

and then manually comparing output with the SRI 'hash' in `icu/default.nix`.
Is the derivation hash for `icu66` now unchanged, @7c6f434c ?

During my checks I noticed that the URL (http://bugs.icu-project.org/trac/changeset/39484?format=diff) for the `icu58` patch is no longer valid. It seems upstream has replace trac with Jira. Does this need to be addressed too or is the patch cached in Nix using the original `sha256`?

**Comment by 7c6f434c** [comment]
By the way, why a zero-preexisting-package-rebuild single-addition PR is towards staging? You didn't believe you would succeed to maintain the output paths?

(I hoped to get ofBorg checks on Darwin but apparently parts of staging are broken there)

(If you retarget, draft the PR before and re-ready it afterwards, to avoid triggering CODEOWNER notifications for the difference between staging and master)

**Comment by afh** [comment]
Apologies, @7c6f434c, I'm uncertain whether I understand what you are asking for correctly, could rephrase and add more context?

Which branch would you recommend as this PRs merge base?

**Comment by 7c6f434c** [comment]
Sorry, I was assuming too much context here.

This PR does two things: a well done zero-rebuild (now verified to be zero-rebuild) refactoring of old ICU versions; and addition of a package with version 74 which as of this PR has no dependent packages. The total rebuild amount is 1.

For such changes it is usually safe to target `master`. On the other hand, you do not claim having built it on macOS, we do claim ICU to have wide platform support, and on `master` ofBorg would check for anything unexpected while on `staging` it is more complicated. Not a deal-breaker when there are reasons to target `staging`, but a benefit of targeting `master` when it is otherwise fine.

So I ask if there is any reason not to retarget to `master` branch. 

If you do, please follow https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging

**Comment by afh** [comment]
My sincerest apologies everyone, while changing the merge base from staging to master, you all got pinged, when you shouldn't have. Even though I followed the instructions linked to by @7c6f434c I seem to have made a mistake somewhere along the way.
I'll close this PR and create a new one.

**Comment by afh** [comment]
I'll reply to your previous comments here, @7c6f434c, after that—if your onboard with it—let's continue the conversation on the replacement PR #290266.

To answer your initial question "Why staging?" I had assumed that ICU being such an essential package there will be a lot of rebuilds. Is this something I could check upfront locally prior to creating a PR? If yes, how?

Thanks for the context, that's very helpful. Now I understand what you meant with zero-rebuild. Usually I build locally, but with the changes being on staging the rebuild took too long for the patience I had.

With the additional context and especially the verified zero-rebuild: No, I do not see a reason not to retarget to the `master` branch and have done so in #290266.

As you see from my comment above and this PR being close, something went wrong while rebasing the branches. Hopefully this doesn't disrupt too many peoples day… The 🌙 icon seems to sugggest that have not been pinged, but would have should this PR have been re-ready'd (thanks for the tip! :100:).

**Pull request closed without merging**
