### PR TITLE
wordpress: fixed installing of languages

### PR DESCRIPTION
**Pull request by dasj19**
###### Description of changes

I made a tiny change that would take all language files and have them installed in the wp-content/languages/ root folder and not in a subfolder as it was until now.

The main reason for this is that wordpress would not load its main language files contained inside a subfolder.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sinavir** [comment]
Hello, this PR is breaking my wordpress setup. Since the `languages` folder does not exist in the vanilla wordpress package, the `cp` instruction is failing !

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/zwfrf3digisnz0q2r1h5c2mmj6f21gdd-wordpress-6.3.2
source root is wordpress-6.3.2
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
no Makefile or custom buildPhase, doing nothing
@nix { "action": "setPhase", "phase": "installPhase" }
installing
cp: target '/nix/store/bw9k7ksk0x70j183k7b3qbph4wrcsqx1-wordpress-lavoixduntexte.normalesup.eu-6.3.2/share/wordpress/wp-content/languages/': No such file or directory
```

**Comment by sinavir** [comment]
I guess you tested your PR on a alredy modified wordpress package which had the language folder created ending to the issue you faced

**Comment by sinavir** [comment]
This also raises the issue that the `languages` option is not tested by the nixos test

**Comment by wegank** [comment]
If the folder doesn't exist, reverting the PR wouldn't help. Probably just make a PR doing `mkdir -p` before that line?

**Comment by wegank** [comment]
Anyway, reverted in #272724.

**Comment by sinavir** [comment]
Thanks !

**Pull request merged**
