### PR TITLE
python3Packages.clickclick: 1.2.2 -> 20.10.2, update upstream location

### PR DESCRIPTION
**Pull request by tomodachi94**
* Update to 20.10.2
    * Upstream doesn't provide changelogs,
but the diff reveals no substantial changes: https://codeberg.org/hjacobs/python-clickclick/compare/1.2.2...20.10.2

* Upstream moved to https://codeberg.org/hjacobs/python-clickclick
    * Source:
https://github.com/hjacobs/python-clickclick/commit/ed14a63e007dab504607bc9e7aa5d09a780a82c4
    * Part of #346385

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by mibmo — APPROVED** [review]
Haven't used `clickclick` before, but tested via some of the examples on pip and it works without issue. (also, great library!)

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 350156`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 6 packages marked as broken and skipped:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>apache-airflow.dist</li>
    <li>python311Packages.stups-fullstop</li>
    <li>python311Packages.stups-fullstop.dist</li>
    <li>python312Packages.stups-fullstop</li>
    <li>python312Packages.stups-fullstop.dist</li>
  </ul>
</details>
<details>
  <summary>:x: 16 packages failed to build:</summary>
  <ul>
    <li>python311Packages.clickclick</li>
    <li>python311Packages.clickclick.dist</li>
    <li>python311Packages.stups-cli-support</li>
    <li>python311Packages.stups-cli-support.dist</li>
    <li>python311Packages.stups-pierone</li>
    <li>python311Packages.stups-pierone.dist</li>
    <li>python311Packages.stups-zign</li>
    <li>python311Packages.stups-zign.dist</li>
    <li>python312Packages.clickclick</li>
    <li>python312Packages.clickclick.dist</li>
    <li>python312Packages.stups-cli-support</li>
    <li>python312Packages.stups-cli-support.dist</li>
    <li>python312Packages.stups-pierone</li>
    <li>python312Packages.stups-pierone.dist</li>
    <li>python312Packages.stups-zign</li>
    <li>python312Packages.stups-zign.dist</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:fast_forward: 6 packages marked as broken and skipped:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>apache-airflow.dist</li>
    <li>python311Packages.stups-fullstop</li>
    <li>python311Packages.stups-fullstop.dist</li>
    <li>python312Packages.stups-fullstop</li>
    <li>python312Packages.stups-fullstop.dist</li>
  </ul>
</details>
<details>
  <summary>:x: 16 packages failed to build:</summary>
  <ul>
    <li>python311Packages.clickclick</li>
    <li>python311Packages.clickclick.dist</li>
    <li>python311Packages.stups-cli-support</li>
    <li>python311Packages.stups-cli-support.dist</li>
    <li>python311Packages.stups-pierone</li>
    <li>python311Packages.stups-pierone.dist</li>
    <li>python311Packages.stups-zign</li>
    <li>python311Packages.stups-zign.dist</li>
    <li>python312Packages.clickclick</li>
    <li>python312Packages.clickclick.dist</li>
    <li>python312Packages.stups-cli-support</li>
    <li>python312Packages.stups-cli-support.dist</li>
    <li>python312Packages.stups-pierone</li>
    <li>python312Packages.stups-pierone.dist</li>
    <li>python312Packages.stups-zign</li>
    <li>python312Packages.stups-zign.dist</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:fast_forward: 6 packages marked as broken and skipped:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>apache-airflow.dist</li>
    <li>python311Packages.stups-fullstop</li>
    <li>python311Packages.stups-fullstop.dist</li>
    <li>python312Packages.stups-fullstop</li>
    <li>python312Packages.stups-fullstop.dist</li>
  </ul>
</details>
<details>
  <summary>:x: 16 packages failed to build:</summary>
  <ul>
    <li>python311Packages.clickclick</li>
    <li>python311Packages.clickclick.dist</li>
    <li>python311Packages.stups-cli-support</li>
    <li>python311Packages.stups-cli-support.dist</li>
    <li>python311Packages.stups-pierone</li>
    <li>python311Packages.stups-pierone.dist</li>
    <li>python311Packages.stups-zign</li>
    <li>python311Packages.stups-zign.dist</li>
    <li>python312Packages.clickclick</li>
    <li>python312Packages.clickclick.dist</li>
    <li>python312Packages.stups-cli-support</li>
    <li>python312Packages.stups-cli-support.dist</li>
    <li>python312Packages.stups-pierone</li>
    <li>python312Packages.stups-pierone.dist</li>
    <li>python312Packages.stups-zign</li>
    <li>python312Packages.stups-zign.dist</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:fast_forward: 6 packages marked as broken and skipped:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>apache-airflow.dist</li>
    <li>python311Packages.stups-fullstop</li>
    <li>python311Packages.stups-fullstop.dist</li>
    <li>python312Packages.stups-fullstop</li>
    <li>python312Packages.stups-fullstop.dist</li>
  </ul>
</details>
<details>
  <summary>:x: 16 packages failed to build:</summary>
  <ul>
    <li>python311Packages.clickclick</li>
    <li>python311Packages.clickclick.dist</li>
    <li>python311Packages.stups-cli-support</li>
    <li>python311Packages.stups-cli-support.dist</li>
    <li>python311Packages.stups-pierone</li>
    <li>python311Packages.stups-pierone.dist</li>
    <li>python311Packages.stups-zign</li>
    <li>python311Packages.stups-zign.dist</li>
    <li>python312Packages.clickclick</li>
    <li>python312Packages.clickclick.dist</li>
    <li>python312Packages.stups-cli-support</li>
    <li>python312Packages.stups-cli-support.dist</li>
    <li>python312Packages.stups-pierone</li>
    <li>python312Packages.stups-pierone.dist</li>
    <li>python312Packages.stups-zign</li>
    <li>python312Packages.stups-zign.dist</li>
  </ul>
</details>

**Comment by khaneliman** [comment]
@ofborg build

**Comment by khaneliman** [comment]
Did something change that affects this or is just an issue on my end ?

**Comment by mibmo** [comment]
> Did something change that affects this or is just an issue on my end ?

errrrr... I had no such issues, at least. Certainly weird that it says that `clickclick` itself doesn't build.

**Comment by khaneliman** [comment]
Mine is crashing almost instantly on a pip command with a `--quiet flake8` at the end.

**Comment by tomodachi94** [comment]
> ❌ 16 packages failed to build

Do you have a build log that I could reference? This failure is very strange.

**Comment by khaneliman** [comment]
> > ❌ 16 packages failed to build
> 
> Do you have a build log that I could reference? This failure is very strange.

https://gist.github.com/khaneliman/323a3f59b62928a9f68e93456e0f06e1

**Review by mibmo — CHANGES_REQUESTED** [review]
Actually, seems like I made a mistake upon reviewing; it also doesn't compile for me, doing
`nix build github:tomodachi94/nixpkgs/update/python3Packages.clickclick/20.10.2#python3Packages.clickclick`
(I guess I just somehow pulled the old library? I think I mistyped the PR number ... embarrasing :face_exhaling:)

Adding `six` and `flake8` back to `propagatedBuildInputs` does seem to make it build though; can you check @khaneliman?

**Comment by khaneliman** [comment]
> Actually, seems like I made a mistake upon reviewing; it also doesn't compile for me, doing `nix build github:tomodachi94/nixpkgs/update/python3Packages.clickclick/20.10.2#python3Packages.clickclick` (I guess I just somehow pulled the old library? I think I mistyped the PR number ... embarrasing 😮‍💨)
> 
> Adding `six` and `flake8` back to `propagatedBuildInputs` does seem to make it build though; can you check @khaneliman?

Yep, builds when I add them both back.

**Comment by tomodachi94** [comment]
Should be fixed now, I was a bit too eager 🙂

**Review by mibmo — APPROVED** [review]
Yep, lgtm!

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 350156`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 6 packages marked as broken and skipped:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>apache-airflow.dist</li>
    <li>python311Packages.stups-fullstop</li>
    <li>python311Packages.stups-fullstop.dist</li>
    <li>python312Packages.stups-fullstop</li>
    <li>python312Packages.stups-fullstop.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 16 packages built:</summary>
  <ul>
    <li>python311Packages.clickclick</li>
    <li>python311Packages.clickclick.dist</li>
    <li>python311Packages.stups-cli-support</li>
    <li>python311Packages.stups-cli-support.dist</li>
    <li>python311Packages.stups-pierone</li>
    <li>python311Packages.stups-pierone.dist</li>
    <li>python311Packages.stups-zign</li>
    <li>python311Packages.stups-zign.dist</li>
    <li>python312Packages.clickclick</li>
    <li>python312Packages.clickclick.dist</li>
    <li>python312Packages.stups-cli-support</li>
    <li>python312Packages.stups-cli-support.dist</li>
    <li>python312Packages.stups-pierone</li>
    <li>python312Packages.stups-pierone.dist</li>
    <li>python312Packages.stups-zign</li>
    <li>python312Packages.stups-zign.dist</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:fast_forward: 6 packages marked as broken and skipped:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>apache-airflow.dist</li>
    <li>python311Packages.stups-fullstop</li>
    <li>python311Packages.stups-fullstop.dist</li>
    <li>python312Packages.stups-fullstop</li>
    <li>python312Packages.stups-fullstop.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 16 packages built:</summary>
  <ul>
    <li>python311Packages.clickclick</li>
    <li>python311Packages.clickclick.dist</li>
    <li>python311Packages.stups-cli-support</li>
    <li>python311Packages.stups-cli-support.dist</li>
    <li>python311Packages.stups-pierone</li>
    <li>python311Packages.stups-pierone.dist</li>
    <li>python311Packages.stups-zign</li>
    <li>python311Packages.stups-zign.dist</li>
    <li>python312Packages.clickclick</li>
    <li>python312Packages.clickclick.dist</li>
    <li>python312Packages.stups-cli-support</li>
    <li>python312Packages.stups-cli-support.dist</li>
    <li>python312Packages.stups-pierone</li>
    <li>python312Packages.stups-pierone.dist</li>
    <li>python312Packages.stups-zign</li>
    <li>python312Packages.stups-zign.dist</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:fast_forward: 6 packages marked as broken and skipped:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>apache-airflow.dist</li>
    <li>python311Packages.stups-fullstop</li>
    <li>python311Packages.stups-fullstop.dist</li>
    <li>python312Packages.stups-fullstop</li>
    <li>python312Packages.stups-fullstop.dist</li>
  </ul>
</details>
<details>
  <summary>:x: 4 packages failed to build:</summary>
  <ul>
    <li>python311Packages.stups-pierone</li>
    <li>python311Packages.stups-pierone.dist</li>
    <li>python311Packages.stups-zign</li>
    <li>python311Packages.stups-zign.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 12 packages built:</summary>
  <ul>
    <li>python311Packages.clickclick</li>
    <li>python311Packages.clickclick.dist</li>
    <li>python311Packages.stups-cli-support</li>
    <li>python311Packages.stups-cli-support.dist</li>
    <li>python312Packages.clickclick</li>
    <li>python312Packages.clickclick.dist</li>
    <li>python312Packages.stups-cli-support</li>
    <li>python312Packages.stups-cli-support.dist</li>
    <li>python312Packages.stups-pierone</li>
    <li>python312Packages.stups-pierone.dist</li>
    <li>python312Packages.stups-zign</li>
    <li>python312Packages.stups-zign.dist</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:fast_forward: 6 packages marked as broken and skipped:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>apache-airflow.dist</li>
    <li>python311Packages.stups-fullstop</li>
    <li>python311Packages.stups-fullstop.dist</li>
    <li>python312Packages.stups-fullstop</li>
    <li>python312Packages.stups-fullstop.dist</li>
  </ul>
</details>
<details>
  <summary>:x: 4 packages failed to build:</summary>
  <ul>
    <li>python311Packages.stups-pierone</li>
    <li>python311Packages.stups-pierone.dist</li>
    <li>python311Packages.stups-zign</li>
    <li>python311Packages.stups-zign.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 12 packages built:</summary>
  <ul>
    <li>python311Packages.clickclick</li>
    <li>python311Packages.clickclick.dist</li>
    <li>python311Packages.stups-cli-support</li>
    <li>python311Packages.stups-cli-support.dist</li>
    <li>python312Packages.clickclick</li>
    <li>python312Packages.clickclick.dist</li>
    <li>python312Packages.stups-cli-support</li>
    <li>python312Packages.stups-cli-support.dist</li>
    <li>python312Packages.stups-pierone</li>
    <li>python312Packages.stups-pierone.dist</li>
    <li>python312Packages.stups-zign</li>
    <li>python312Packages.stups-zign.dist</li>
  </ul>
</details>

**Review by khaneliman — APPROVED** [review]
Lgtm thanks

**Pull request merged**
