### PR TITLE
bun: 1.0.2 -> 1.0.3

### PR DESCRIPTION
**Pull request by cornedor**
## Description of changes

Updated Bun 1.0.2 to 1.0.3
Changelog https://bun.sh/blog/bun-v1.0.3

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by torresgol10** [comment]
Pls, the current version is old

**Review by natsukium — CHANGES_REQUESTED** [review]
CI shows all hashes except aarch64-darwin are different.

**Comment by natsukium** [comment]
to maintainers, could you please check if updateScript is working correctly?
The same thing happened with the previous bumps.

**Comment by cornedor** [comment]
The script didn't work for me. I had to comment out the live wheeze the version was set to 0. After that it would only update the Darwin version.

I've generated the other hashes using the nix hash command.

**Comment by cornedor** [comment]
I've updated the hashes for now using the output of OfBorg

**Comment by cornedor** [comment]
I've opened a separate PR with a fix for the script: https://github.com/NixOS/nixpkgs/pull/257133

**Comment by SebTM** [comment]
Result of `nixpkgs-review pr 256950` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>bun</li>
  </ul>
</details>

**Review by SebTM — APPROVED** [review]

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 256950` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>bun</li>
  </ul>
</details>

**Comment by natsukium** [comment]
hmm, bun on x86_64-darwin is already broken on master.

**Review by natsukium — APPROVED** [review]
The version bump itself looks good to me.

**Comment by ajs124** [comment]
the two commits should have been squashed. [updated hashes](https://github.com/NixOS/nixpkgs/pull/256950/commits/2ef86dc8488665215739cc0d8990166fe28cfc2d) does not conform to contributing.md.

**Comment by natsukium** [comment]
Sorry, my bad. I missed that the commits were not squashed.

**Pull request merged**
