### PR TITLE
nodejs: Add 16.20.1 to permittedInsecurePackages in release.nix 

### PR DESCRIPTION
**Pull request by YorikSar**
###### Description of changes

nodejs package has been updated in https://github.com/NixOS/nixpkgs/pull/238884 but it wasn't added here, so Hydra doesn't build any packages depending on it.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by YorikSar** [comment]
cc @marsam who updated nodejs.

**Comment by RaitoBezarius** [comment]
Please drop the formatting changes, they are not necessary and would only hinder merging this PR.
Also, please do the same thing as in #238443 i.e. adding a comment in the package definition to prevent further issues.

cc @drupol who did the same PR in #239406.

**Comment by emilylange** [comment]
The mentioned #239406 got merged 3 minutes ago.
Closing.

**Comment by emilylange** [comment]
Whoops, I might have been a bit trigger happy with the close button, sorry.

Feel free to open a new PR for what @RaitoBezarius suggested

> Also, please do the same thing as in #238443 i.e. adding a comment in the package definition to prevent further issues.

(if you want, no pressure)

**Comment by YorikSar** [comment]
@emilylange   no problem, that PR adds that comment as well and doesn’t include formatting. Although I would prefer to format as much code as possible, it’s nothing critical.

**Comment by lilyinstarlight** [comment]
> Although I would prefer to format as much code as possible, it’s nothing critical.

I would love to be able to reformat a lot of the old stuff in nixpkgs, but until we have a blessed formatter, any formatting choices made towards that would be just as arbitrary as the original formatting. This is a pretty central file and it wasn't obvious how much of an improvement the formatting changes were, so it really just makes this more unclear for merge since we don't have much of a policy on formatting and it should have only been a one or two line change

We will be able to enforce formatting changes soon, at least, once RFC101 work is complete. While I'm not directly involved in the RFC, I've been vaguely keeping up with it and there's been a lot of great work on it (so hopefully it won't be much longer, maybe only a couple of months)

**Pull request closed without merging**
