### PR TITLE
stdenv: change texinfo bootstrap handling; texinfo, bash: simplify expressions

### PR DESCRIPTION
**Pull request by oxij**
###### Motivation for this change

- stdenv change: see commit message.
- others: simpler is better.

###### Things done

- [X] Writing this from a system with these patches applied.
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
Looks okay to me. I assume 4.13a doesn't work with common.nix?

One concern I have with the "generic" style is that it's not always clear how to add stuff to them. For instance, what do we do when we want to add a known vulnerability or mark as broken a specific version of texinfo? I think overrideAttrs would probably work as well as adding an optional argument to common.nix but it's not exactly obvious how to do it. I had to do this with Mono recently and still not sure whether it was the right way to go about it:

https://github.com/NixOS/nixpkgs/pull/39344/files

Definitely not a reason not to merge this because it's used elsewhere - just a concern with this style.

**Comment by oxij** [comment]
Yes, the older texinfo is a bit too different to be merged with this expression and I didn't want to make `common.nix` complicated.

I agree that merging for the sake of merging is not useful, but then expressions almost coincide and you frequently have to update all of them at once I think it's worth merging them.

> I think overrideAttrs would probably work as well as adding an optional argument to common.nix but

You can also inspect the version in common.nix. E.g.

```
{
  inherit version;
  name = "name-${version}";
  meta = {
    knownVulnerabilities = lib.versionOlder version whatever ["CVE-whatever" ];
  }
}
```

But I do feel that `overrideAttrs` is preferrable for stuff like that, since its very version-specefic.

**Comment by oxij** [comment]
The build on arch times out.

**Review by Ericson2314 — APPROVED** [review]

**Review by 7c6f434c — APPROVED** [review]

**Comment by cleverca22** [comment]
this results in the main `pkgs.texinfo` derivation depending on a perl that still links against the bootstrap-tools, causing the closure of every system to use an extra ~113mb

**Comment by oxij** [comment]
I can confirm. That's unfortunate. Reverting a809fdc8e1b0c1d49d40815d9bac0de27ddab5f1 fixes it, but it's a mass-rebuild.

**Comment by oxij** [comment]
@cleverca22 Please try #44932, I think it fixes it, but still saves one texinfo rebuild.

**Pull request merged**
