### PR TITLE
update asterisk-stable and asterisk-lts

### PR DESCRIPTION
**Pull request by womfoo**
###### Motivation for this change

* include debian patch to remove warnings that clutter journald logs
* bump to latest upstream versions

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by yorickvP** [comment]
At first look, seems fine. Out of curiosity, why disable the md5 verification in the makefile?

**Comment by womfoo** [comment]
Thanks for reviewing @yorickvP and yeah i forgot to mention about the MD5 verification.

The upstream makefile [now downloads an MD5SUM.TXT ](https://github.com/asterisk/asterisk/blob/12dde3b568ff3e44527b73f61b073f902edfb10f/third-party/pjproject/Makefile#L101) next to the pjsip package url.

I propose removing this step instead of maintaining another hash each time we bump versions.

**Review by DerTim1 — APPROVED** [review]
+1
Built and tested.

**Comment by joachifm** [comment]
Thank you

**Pull request merged**
