### PR TITLE
ghc 9.2 overrides

### PR DESCRIPTION
**Pull request by roberth**
###### Description of changes

Fix some packages in the GHC 9.2 package set.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by maralorn** [comment]
@roberth we generally have the policy not to accumulate patches for haskell packages in nixpkgs. Is there a reason that you didn‘t open an upstream pull request for protolude?

**Comment by roberth** [comment]
@maralorn

> Is there a reason that you didn‘t open an upstream pull request for protolude?

I was hesitant to do so because I didn't understand their "exports" tool. A similar PR has been merged though, so it's probably ok.

Regarding the patch file: for reliability, it's better not to create fixed-output derivations that depend on resources that may vanish, such as unmerged PRs and unmerged commits, so I'm keeping the copied file instead of changing to `fetchpatch`.

**Comment by roberth** [comment]
Are you sure? If you can't remove commits, that would be bad for security in some other situations.

**Comment by maralorn** [comment]
I can just say that I have used this technique for quite a while and never had issues with it. I am certain that commits have stayed accessible this way after they were unreachable from any tag or branch on github. I can‘t find sources on the internet which confirm that github never garbage collects, but all rumors I heard go in that direction.

Apparently those commits can be deleted, but only by contacting github support or deleting the repo.
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

**Comment by maralorn** [comment]
@piegamesde found a source:

https://github.community/t/does-github-ever-purge-commits-or-files-that-were-visible-at-some-time/1944/2

**Comment by roberth** [comment]
Ok, I'll trust github with my patch then.

**Comment by maralorn** [comment]
Thank you!

**Pull request merged**
