### PR TITLE
libvdpau: 1.2 -> 1.3, vdpauinfo: 1.0 -> 1.3

### LINKED ISSUE #74211: update libvdpau to add VP9 decoding support
Recently `libvdpau` 1.3 with support for VP9 decoding has been released:
https://gitlab.freedesktop.org/vdpau/libvdpau/-/releases

This could present a very interesting improvement for video streaming performance in general and might be especially useful for Google Stadia as it relies on quick video decoding to be playable.
Though I don't even know if chromium's `useVaapi` flag currently works with an NVIDIA GPU.

`vdpauinfo` was also updated to support the changes but there hasn't been an official release yet:
https://gitlab.freedesktop.org/vdpau/vdpauinfo/commits/master

The `nvidiaBeta` drivers might be required to test VP9 support:
https://www.phoronix.com/scan.php?page=news_item&px=NVIDIA-440.26-Linux-Driver

### PR DESCRIPTION
**Pull request by felschr**
###### Motivation for this change
libvdpau 1.3 adds support for VP9 decoding.
Fixes #74211

###### Things done
- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
over 5000+ linux rebuilds, please target staging

**Comment by FelschR** [comment]
@jonringer Oh, sorry. I wasn't aware of that policy. I've rebased the changes onto staging.

**Comment by FRidh** [comment]
What reverse dependencies have been tested?

**Comment by FelschR** [comment]
I've only tested the output of vdpauinfo so far. On my machine it lists all codecs that were listed before with the addition of VP9.

**Pull request merged**
