### PR TITLE
firefox-{,bin-}unwrapped: 105.0.3 -> 106.0; firefox-esr-102-unwrapped: 102.3.0esr -> 102.4.0esr

### PR DESCRIPTION
**Pull request by mweinelt**
https://www.mozilla.org/en-US/firefox/106.0/releasenotes/
https://www.mozilla.org/en-US/firefox/102.4.0/releasenotes/

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by PedroHLC** [comment]
Result of `nixpkgs-review pr 196406` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>adoptopenjdk-icedtea-web</li>
    <li>dropbox</li>
    <li>dropbox-cli</li>
    <li>firefox-esr-unwrapped (firefox-esr-102-unwrapped ,firefoxPackages.firefox-esr-102)</li>
    <li>xulrunner (firefox-unwrapped)</li>
    <li>mate.caja-dropbox</li>
    <li>slimerjs</li>
  </ul>
</details>

**Review by PedroHLC — APPROVED** [review]

**Comment by mweinelt** [comment]
102.4.0 also everything as expected.

**Comment by vcunat** [comment]
It looks like the build regressed on aarch64-linux: https://hydra.nixos.org/build/195736993#tabs-buildsteps  (retried a few times, also once "privately" on the community box)

And as we recently promoted the platform, this is now [blocking](https://hydra.nixos.org/build/195744461) the `nixos-unstable` channel.

**Comment by mweinelt** [comment]
```
/build/firefox-106.0/media/ffvpx/libavutil/cpu.c:46:10: fatal error: 'sys/sysctl.h' file not found
#include <sys/sysctl.h>
         ^~~~~~~~~~~~~~
1 error generated.
make[3]: *** [/build/firefox-106.0/config/rules.mk:590: cpu.o] Error 1
make[3]: *** Waiting for unfinished jobs....

**Comment by vcunat** [comment]
OK, I got this.

**Comment by vcunat** [comment]
https://github.com/NixOS/nixpkgs/pull/196569

**Comment by vcunat** [comment]
BTW, release and security notes are up.

**Pull request merged**
