### PR TITLE
update RaspberryPi related packages

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change
This is a wholesale bump of a number of RaspberryPi related packages. I hit
these while working to get my RPi CM4 booting off NVME.

###### Things done
- raspberrypifw: 1.20210303 -> 1.20210727
- linux_rpi{0,1,2,3,4}: 5.10.17 -> 5.10.52
- raspberrypiWirelessFirmware: 2021-01-28 -> 2021-06-28
- raspberrypi-armstubs: 2020-10-08 -> 2021-07-05
- libraspberrypi: unstable-2021-03-17 -> unstable-2021-06-23

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 132481` at 81adfb5f run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built successfully:</summary>
  <ul>
    <li>device-tree_rpi</li>
    <li>libraspberrypi</li>
    <li>raspberrypiWirelessFirmware</li>
    <li>raspberrypifw</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/os-specific/linux/firmware/raspberrypi-wireless/default.nix:30:3:
```
   |
30 |   installPhase = ''
   |   ^
```
</li>
  </ul>
</details>

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 132481` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>linux_rpi0 (linux_rpi1)</li>
    <li>linux_rpi2</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>device-tree_rpi</li>
    <li>libraspberrypi</li>
    <li>linux_rpi3</li>
    <li>linux_rpi4</li>
    <li>raspberrypi-armstubs</li>
    <li>raspberrypi-eeprom</li>
    <li>raspberrypiWirelessFirmware</li>
    <li>raspberrypifw</li>
  </ul>
</details>

**Comment by lovesegfault** [comment]
Got all my pi's booted and working with this patchset

**Comment by SuperSandro2000** [comment]
@ofborg eval
@ofborg build

**Comment by lovesegfault** [comment]
I'm going to merge this, we can revert if need be.

**Comment by mweinelt** [comment]
The wireless firmware update was a no-op, since the last change in that tree was https://github.com/RPi-Distro/firmware-nonfree/commit/f713a6054746bc61ece1c8696dce91a7b7e22dd9

https://github.com/RPi-Distro/firmware-nonfree/tree/master/brcm.

**Pull request merged**
