### PR TITLE
remove some format hardenings

### PR DESCRIPTION
**Pull request by oxij**
###### Motivation for this change

Fixing fallout from #28029 and continuing #39463.
 
###### Things done

- [X] Everything built before rebase.

### CODE REVIEW

**Comment by oxij** [comment]
@GrahamcOfBorg build linuxPackages.perf haskellPackages.ghc802

**Comment by oxij** [comment]
@GrahamcOfBorg build haskell.compiler.ghc802

**Comment by xeji** [comment]
`libgdiplus`: see also #41187

**Comment by peti** [comment]
How about `haskell.packages.ghc842.ghc`? It also seems to have trouble with the new hardening features: https://hydra.nixos.org/build/75026569. Or is that not related?

**Comment by oxij** [comment]
> libgdiplus

Identical change, rebased.

> How about `haskell.packages.ghc842.ghc`?

Likely related, fixed.

**Review by peti — APPROVED** [review]

**Comment by peti** [comment]
`ghc-7.10.3` and `ghc-head` are also broken. :-(

I committed a246b6e6f8a33622d0be001391a9087820030134 and 8d36f159fa3dcdb2b8f4872787a4bf67748fd7db to the `haskell-updates` branch to fix.

**Comment by peti** [comment]
`ghc-7.10.3` and `ghc-head` are also broken. :-(

I committed a246b6e6f8a33622d0be001391a9087820030134 and 8d36f159fa3dcdb2b8f4872787a4bf67748fd7db to the `haskell-updates` branch to fix.

**Comment by peti** [comment]
`ghc-7.10.3` and `ghc-head` are also broken. :-(

I committed a246b6e6f8a33622d0be001391a9087820030134 and 8d36f159fa3dcdb2b8f4872787a4bf67748fd7db to the `haskell-updates` branch to fix.

**Comment by oxij** [comment]
Okay. Do you want me to do anything else with this?

Ofborg clearly shows that this doesn't make things worse, so I would just merge so that master would hopefully start to build again.

**Pull request merged**
