### PR TITLE
fixup-yarn-lock: split out from prefetch-yarn-deps

### PR DESCRIPTION
**Pull request by SuperSandro2000**
## Description of changes

Verified by building all packages

```
NIXPKGS_ALLOW_UNFREE=1 NIXPKGS_ALLOW_NONSOURCE=1 nix build --impure .#akkoma-frontends.admin-fe .#akkoma-frontends.akkoma-fe .#alice-lg .#anki .#authy .#aws-azure-login .#bilibili .#bitwarden .#bruno .#camunda-modeler .#das .#deltachat-desktop .#drawio .#drawio-headless .#electron .#electron_26 .#electron_27 .#electron_28 .#element-desktop .#element-desktop-wayland .#element-web .#element-web-unwrapped .#fixup-yarn-lock .#freetube .#gitlab .#gitlab-ee .#gitmoji-cli .#gotify-server .#grafana-agent .#headset .#heroic .#heroic-unwrapped .#hydrogen-web .#hydrogen-web-unwrapped .#itch .#jitsi-meet-electron .#logseq .#marp-cli .#mastodon .#matrix-appservice-irc .#mattermost-desktop .#mermaid-cli .#micropad .#mnemosyne .#morgen .#muzika .#nix-tour .#open-stage-control .#outline .#pandoc-drawio-filter .#peertube .#pgadmin4 .#pgadmin4-desktopmode .#picosnitch .#pocket-casts .#podman-desktop .#prefetch-yarn-deps .#pritunl-client .#pxder .#python311Packages.dash .#python311Packages.mkdocs-drawio-exporter .#python312Packages.dash .#python312Packages.mkdocs-drawio-exporter .#r2modman .#ratman .#redisinsight .#revolt-desktop .#rmfakecloud .#sapling .#sharedown .#shepherd .#standardnotes .#stretchly .#super-productivity .#tandoor-recipes .#teams-for-linux .#teleport .#teleport_12 .#teleport_13 .#teleport_14 .#terra-station .#thedesk .#threema-desktop .#tilt .#tutanota-desktop .#uhk-agent .#uhk-udev-rules .#uivonim .#vercel-pkg .#vesktop .#vieb .#webcord .#webcord-vencord .#webtorrent_desktop .#youtube-music
```

redisinsight-electron and recipe-scrapers failed because of unrelated reasons.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Stunkymonkey** [comment]
sadly I do not feel competent enough to review this. removing myself.

@lilyinstarlight might be a good fit here?

**Comment by SuperSandro2000** [comment]
I've just run into cache misses for electron again and working around this is a rather annoying.

@lilyinstarlight

**Comment by SuperSandro2000** [comment]
@yu-re-ka what do we do here? I kinda want to stop fiddling around with my overrides every other week to not have to rebuild electron.

**Review by lilyinstarlight — APPROVED** [review]
Ideally common.js and yarn-lockfile.js could come from a common derivation, but I don't have the spoons to properly review this right and having it is strictly still better than not due to the mentioned closure issues

So I'll approve this. If you've ensured no build regressions or recent introductions of fixup-yarn-lock usage since last rebase that would need updating, then feel free to send this

**Comment by lilyinstarlight** [comment]
I added devcontainer which was missing from the treewide change and rebased. I also kicked off builds on build-box.nix-community.org to check for regressions. I'll be merging when ofborg is green

**Comment by SuperSandro2000** [comment]
Thanks that we finally got this merged 🎉

**Pull request merged**
