### PR TITLE
jetbrains.plugins: add AsciiDoc, StringManipulation, AceJump, Mermaid and AWS toolkit

### PR DESCRIPTION
**Pull request by liff**
## Description of changes

Add a bunch of useful(?) plugins:

- [AsciiDoc](https://plugins.jetbrains.com/plugin/7391-asciidoc),
- [String Manipulation](https://plugins.jetbrains.com/plugin/2162-string-manipulation),
- [AceJump](https://plugins.jetbrains.com/plugin/7086-acejump),
- [Mermaid](https://plugins.jetbrains.com/plugin/20146-mermaid) and
- [AWS Toolkit](https://plugins.jetbrains.com/plugin/11349-aws-toolkit--amazon-q-codewhisperer-and-more).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by britter** [comment]
@edwtjo can we get this merged?

**Comment by britter** [comment]
@liff I tried to built this locally in order to verify this change. I have a local checkout of nixpkgs and cherry picked the commits from this PR to that checkout. I configured my IntelliJ package like so:

```
      (jetbrains.plugins.addPlugins jetbrains.idea-community ["string-manipulation" "acejump" "asciidoc" "aws-toolkit--amazon-q-codewhisperer-and-more" "mermaid"])
```

However when building my system I get

```
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/8sgj1a2k7msya7l8vw59qvcl7ixddcc7-source.drv^*'

trying https://plugins.jetbrains.com/files/11349/524976/aws-toolkit-jetbrains-2.19-241.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:-->
curl: (35) Recv failure: Connection reset by peer
error: cannot download source from any mirror
```

It looks like aws toolkit was moved and the URL is returning 301 now:

```
❯ http HEAD https://plugins.jetbrains.com/files/11349/524976/aws-toolkit-jetbrains-2.19-241.zip
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Content-Length: 0
Date: Tue, 07 May 2024 09:23:47 GMT
Location: https://downloads.marketplace.jetbrains.com/files/11349/524976/aws-toolkit-jetbrains-2.19-241.zip
Via: 1.1 f47fcc9b2aa47ced36c40c318e6f006a.cloudfront.net (CloudFront)
X-Amz-Cf-Id: hqAL3h1h-QiyHNSeI-aSZVBiukGhvygbzz0E_SbGypQG2w7EyeGW7Q==
X-Amz-Cf-Pop: DUS51-P2
X-Cache: Miss from cloudfront
```

Any idea how to fix that?

**Comment by liff** [comment]
@britter looks like a new major version of AWS Toolkit was released, which probably changed stuff. I’ve updated the plugins, can you check again?

**Comment by britter** [comment]
@liff sorry, this took forever... I tried again today with the latest changes, replacing the nixpkgs-unstable input in my flake this this PR branch. I got a different error this time, I'm not sure it's related to your changes. It looks like a problem with the environment that builds some parts of the IDE:

```
❯ sudo nixos-rebuild test --flake .
warning: Git tree '/home/bene/github/britter/nix-configuration' is dirty
building the system configuration...
warning: Git tree '/home/bene/github/britter/nix-configuration' is dirty
error: builder for '/nix/store/6iadizj083lq495fiyx1d1frbghlhsxn-idea-community-233.13135.103.tar.gz.drv' failed with exit code 1;
       last 10 log lines:
       >    at org.jetbrains.jpsBootstrap.JpsBootstrapMain.main(JpsBootstrapMain.kt:158)
       >   at org.jetbrains.jpsBootstrap.JpsBootstrapMain.access$main(JpsBootstrapMain.kt:47)
       >     at org.jetbrains.jpsBootstrap.JpsBootstrapMain$Companion.main(JpsBootstrapMain.kt:358)
       >         at org.jetbrains.jpsBootstrap.JpsBootstrapMain.main(JpsBootstrapMain.kt)
       >
       >
       >           ###### ERROR EXIT due to FATAL error: Build finished with errors. See TC artifacts for build log. First error:
       > java:ERROR:error: release version 7 not supported
       >
       > ###### You may try to delete caches at /build/source/build/jps-bootstrap-work and retry
       For full logs, run 'nix log /nix/store/6iadizj083lq495fiyx1d1frbghlhsxn-idea-community-233.13135.103.tar.gz.drv'.
error: 1 dependencies of derivation '/nix/store/4as4wh4dl5b8pilqsmh4qhwdq31ac04i-idea-community-2024.1.3.drv' failed to build
error: 1 dependencies of derivation '/nix/store/77ql85hxinl1kfzjl0a0l8wg4bfx1f7g-idea-community-with-plugins-2024.1.3.drv' failed to build
error: 1 dependencies of derivation '/nix/store/wsml8bhycw0430v9q2jdp8s6hihn7ngq-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/sc283b3a95rqlsih8v5sgsid6fh34cnv-idea-community-with-plugins-2024.1.3-fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/q759aysiqsn5z3n9hbc7dpkw4f2j3c1y-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9j52sll4l6bfs8namxjgkbx0pgymrrk5-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/k43mm0iy6fhs8bz2wq8231yxg360chf1-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/n8in3mdj15cxmncy75i60hl390l9p6zm-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/y5dp8avbd7bgcw0jfc54z34pddnvlvhw-nixos-system-pulse-14-24.05.20240615.752c634.drv' failed to build
```

I'd really love to get this integrated, but at this point I'm not sure how to help :(

**Comment by britter** [comment]
Turns out this is unrelated to the PR. I also get this when updating to the latest nixpkgs-unstable. It looks like building idea-community is currently broken on unstable.

**Comment by britter** [comment]
Okay, found out in NixOS DE Matrix, that this is a known issue and was fixed in https://github.com/NixOS/nixpkgs/pull/320808

@liff would you mind rebasing one last time? 😅 I can then verify this on my end and ask somebody to merge it.

**Comment by liff** [comment]
Rebased.

**Comment by britter** [comment]
I tested this by checking out this PR locally and replacing my nixpkgs-unstable output with it. After starting IntelliJ, I could see all the plugins as being bundled with the IDE. All of them were enabled. So from my PoV this is good!

**Review by GaetanLepage — APPROVED** [review]
Diff LGTM

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 285605` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 285605` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 285605` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 285605` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Pull request merged**
