### PR TITLE
Add new meta-attributes to stdenv to permit URLs for screenshots

### PR DESCRIPTION
**Pull request by StefanSchroeder**
###### Motivation for this change

If a meta-attribute for a Screenshot-URL were added to the package description, the search result could include a screenshot of the application in the result. There is no need to create new screenshots as http://screenshots.debian.net/ provides a public repository of screenshots already that could be reused.

I am aware that adding screenshots to the existing thousands of packages would be a major undertaking, but I think it would be a nice user experience enhancement and - of course - optional, since screenshots only make sense for graphical applications.

When the Screenshot-URL is provided for a package, the search result could fetch the image and show it alongside the package description.

The font packages could show a sample of the font instead.

###### Things done

Two paragraphs were added to the Nixpks-manual, section Stdenv -> Meta-attributes to explain the two new
attributes ScreenshotThumb and ScreenshotLarge.

In the package games/pingus the two attributes were added as an example.

The Nixpkgs-manual was rebuild to check correctness.

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

@garbas 

Discussed in https://github.com/NixOS/nixos-search/issues/211

### CODE REVIEW

**Comment by jtojnar** [comment]
An alternative approach would be relying on the appstream data (https://github.com/NixOS/nixpkgs/issues/15932), cc @matthewbauer.

**Comment by SuperSandro2000** [comment]
Please squash the commits together.

**Comment by StefanSchroeder** [comment]
I can't take it from here. The other (#15932) issue is quite complex, involves many aspects. I cannot even identify all the different parts that are involved.
Only one thing is for sure: information in the stdenv and the associated appstream data (if available) must be synchronized. 
Ideally, one should "rule" over the other to have one authoritative source of truth.

**Comment by garbas** [comment]
@matthewbauer is there any timeline on #15932? That RFC is quite old, but I can see it is still in your radar. We could serve AppStream XML via search if you want.

Would you be ok if @StefanSchroeder continues with this new meta-attributes? I'm assuming that we will be doing some merging of some sort when producing this XML.

**Pull request closed without merging**
