### PR TITLE
dbeaver-bin: fix build on darwin

### LINKED ISSUE #354475: Build failure: dbeaver-bin
### Steps To Reproduce

1. build *dbeaver-bin* on aarch64_darwin

### Build log

```
error: builder for '/nix/store/dnp9lklrqprn1xvj0s5b8rqnf5p8hx4h-dbeaver-bin-24.2.3.drv' failed with exit code 1;                                                                                                      
       last 7 log lines:                                                                                                                                                                                              
       > Running phase: unpackPhase                                                                                                                                                                                   
       > unpacking source archive /nix/store/cf9z13r1vvffw85naaxqkq78jylmn0zc-dbeaver-ce-24.2.3-macos-aarch64.dmg                                                                                                     
       > source root is dbeaver.app                                                                                                                                                                                   
       > setting SOURCE_DATE_EPOCH to timestamp 1730999811 of file dbeaver.app/Contents/Eclipse/plugins/org.jkiss.bundle.jfreechart_1.5.4/README.md                                                                   
       > warning: file dbeaver.app/Contents/Eclipse/plugins/org.jkiss.bundle.jfreechart_1.5.4/README.md may be generated; SOURCE_DATE_EPOCH may be non-deterministic
       > Running phase: patchPhase
       > substitute(): ERROR: file 'dbeaver.ini' does not exist
```

### Additional context

It seems like [this commit](https://github.com/NixOS/nixpkgs/commit/100a0fa0af68b1146bda1c94e7ff0c9ef577488b) broke the build at least for darwin aarch64.

### Notify maintainers

@GuillaumeDesforges

@gepbird 
@mkg20001 
@yzx9  

### Metadata

```
 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.0.0, macOS 15.0.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/y8pbnccb8bc1p8fchx7zkb0874yblrg3-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by mkg20001**
## Things done
Resolves #354475

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mkg20001** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 354490`

---
### `x86_64-linux`

**Comment by mkg20001** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 354490`

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>dbeaver-bin</li>
  </ul>
</details>

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 354490`

---
### `x86_64-linux`

---
### `aarch64-linux`

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>dbeaver-bin</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>dbeaver-bin</li>
  </ul>
</details>

**Review by khaneliman — APPROVED** [review]
LGTM

**Review by gepbird — APPROVED** [review]

**Review by gepbird — APPROVED** [review]

**Pull request merged**
