### PR TITLE
python311Packages.scipy: remove references to dev outputs

### PR DESCRIPTION
**Pull request by SuperSandro2000**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by doronbehar** [comment]
I think changes look good, but I don't understand them fully. In anycase, it should target staging.

**Comment by SuperSandro2000** [comment]
nuke-reference replaces the paths in the file referencing the build time dependencies with fake nix store paths only containing eeeeees.

**Comment by doronbehar** [comment]
What is the difference between that and `remove-references-to`?

**Comment by doronbehar** [comment]
OK I found my answer at: https://discourse.nixos.org/t/whats-the-difference-between-removereferencesto-and-nukereferences/35075 

Also @SuperSandro2000 , could you show please which references were there before and after this change? I'd like to spare my self building this package on the `staging`. Also, I would like to know where those references are retained in `$out`.. Perhaps this is something that can be discussed with upstream, like [this patch](https://github.com/scipy/scipy/commit/dd50ac9d98dbb70625333a23e3a90e493228e3be.patch) that wasn't accepted upstream.

**Comment by SuperSandro2000** [comment]
> What is the difference between that and `remove-references-to`?

nuke-references just removes all, while remove-references-to takes a specific list.



> Perhaps this is something that can be discussed with upstream, like [this patch](https://github.com/scipy/scipy/commit/dd50ac9d98dbb70625333a23e3a90e493228e3be.patch) that wasn't accepted upstream.

I think this is somehow related to the build system, numpy has the same file with similar content.

The pyc file is just the compiled bytecode from python. We compile with -OO but the test run I think with only -O and our hook is not cleaning that up somehow.

```diff
--- result-before/lib/python3.11/site-packages/scipy/__config__.py
+++ result-after/lib/python3.11/site-packages/scipy/__config__.py
[0;36m@@ -55,15 +55,15 @@[0m
                 "version": "13.2.0",
                 "commands": "gfortran",
                 "args": "",
                 "linker args": "",
             },
             "pythran": {
                 "version": "0.15.0",
[31m-                "include directory": r"/nix/store/5ia6f6sfzqg4831sqa548hxqz3x7ryc4-python3.11-pythran-0.15.0/lib/python3.11/site-packages/pythran"[0m
[32m+                "include directory": r"/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-python3.11-pythran-0.15.0/lib/python3.11/site-packages/pythran"[0m
             },
         },
         "Machine Information": {
             "host": {
                 "cpu": "x86_64",
                 "family": "x86_64",
                 "endian": "little",
[0;36m@@ -82,35 +82,35 @@[0m
                 "name": "blas",
                 "found": bool("True".lower().replace('false', '')),
                 "version": "3",
                 "detection method": "pkgconfig",
                 "include directory": r"unknown",
                 "lib directory": r"unknown",
                 "openblas configuration": "unknown",
[31m-                "pc file directory": r"/nix/store/217gkl46213hrszin5mx2ga6aifmp96h-blas-3-dev/lib/pkgconfig",[0m
[32m+                "pc file directory": r"/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-blas-3-dev/lib/pkgconfig",[0m
             },
             "lapack": {
                 "name": "lapack",
                 "found": bool("True".lower().replace('false', '')),
                 "version": "3",
                 "detection method": "pkgconfig",
                 "include directory": r"unknown",
                 "lib directory": r"unknown",
                 "openblas configuration": "unknown",
[31m-                "pc file directory": r"/nix/store/jg131f5mbra6aps97j0if05m9ml2008l-lapack-3-dev/lib/pkgconfig",[0m
[32m+                "pc file directory": r"/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-lapack-3-dev/lib/pkgconfig",[0m
             },
             "pybind11": {
                 "name": "pybind11",
                 "version": "2.11.1",
                 "detection method": "pkgconfig",
[31m-                "include directory": r"/nix/store/qiwimi4yv292pny7fgdqi4mrxr0ylxb0-python3.11-pybind11-2.11.1/include",[0m
[32m+                "include directory": r"/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-python3.11-pybind11-2.11.1/include",[0m
             },
         },
         "Python Information": {
[31m-            "path": r"/nix/store/7wz6hm9i8wljz0hgwz1wqmn2zlbgavrq-python3-3.11.8/bin/python3.11",[0m
[32m+            "path": r"/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-python3-3.11.8/bin/python3.11",[0m
             "version": "3.11",
         },
     }
 )
 
 
 def _check_pyyaml():

```

**Comment by doronbehar** [comment]
Great thanks for the explanation! It's good to have this documented at least here.

**Pull request merged**
