### PR TITLE
weechat-matrix-bridge: 2018-01-10 -> 2018-05-29

### PR DESCRIPTION
**Pull request by adisbladis**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @Ma27

### CODE REVIEW

**Comment by Ma27** [comment]
:+1: looks reasonable, browsed through the upstream changelog and couldn't find compatibility breaks :)

BTW do you use this package?

**Comment by adisbladis** [comment]
@Ma27 I just tried it out for the first time today. :)

**Comment by adisbladis** [comment]
The aarch64 failure is unrelated to this PR.

**Comment by Ma27** [comment]
feel free to ping me if I can help:)

**Pull request merged**
