### PR TITLE
eureka-editor: Init at 1.21

### PR DESCRIPTION
**Pull request by neonfuz**
###### Motivation for this change
Add an editor for DOOM wads. There are several doom engines in nixpkgs, but I haven't seen many (any?) wad editors, and this one is pretty good so I decided to write this package.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by neonfuz** [comment]
Maybe this should be in pkgs/applications/editors instead, or pkgs/applications/misc, thoughts?

**Comment by MP2E** [comment]
Nice! A Doom map editor seems to go well with all the ports we have packaged. I think putting it in pkgs/applications/misc would fit best, since that is also where Doomseeker is, but I don't have any strong opinions about where it ends up

**Comment by neonfuz** [comment]
yeah oops... forgot to update all-packages.nix, this should merge fine now I think

**Comment by joachifm** [comment]
The linux build error looks potentially unrelated, but the macos one seems legit.

**Comment by neonfuz** [comment]
There seems to be a osx/ directory in the root of src that I never dealt with. I currently don't have an osx machine so it's a little hard to test osx builds but I'll see if I can figure it out.

**Comment by joachifm** [comment]
You can also simply limit the platform list for the time being.

**Comment by joachifm** [comment]
Thank you

**Pull request merged**
