### PR TITLE
staging-next 2023-04-18

### LINKED ISSUE #226673: Build failure: mysql80
### Steps To Reproduce
Just add mysql80 to your System

### Build log

```
467a468
> #include_next <stdint.h>
CMake Error at /build/mysql-8.0.32/cmake/do_abi_check.cmake:121 (MESSAGE):
  ABI check found difference between
  /build/mysql-8.0.32/include/mysql/services.h.pp and
  /build/mysql-8.0.32/build/abi_check.out


make[2]: *** [CMakeFiles/abi_check.dir/build.make:70: CMakeFiles/abi_check] Error 1
make[1]: *** [CMakeFiles/Makefile2:2990: CMakeFiles/abi_check.dir/all] Error 2
```

### Additional context
The build also failed in Hydra
https://hydra.nixos.org/build/215738828

### Notify maintainers
@orivej

### PR DESCRIPTION
**Pull request by vcunat**
According to [23.05 schedule](https://github.com/NixOS/nixpkgs/issues/223562), this is the last iteration that can contain breaking changes to [Release Critical Packages](https://nixos.github.io/release-wiki/Release-Critical-Packages.html).

##### Helpful links

- workflow docs: https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/224806
- - - 
##### Mass breakages
(will be edited based on progress)
- [x] `stdenv` doesn't build on x86_64-darwin
  ```
  error: output '/nix/store/4kg5amiq7hqrj29b88q0nmwmpf42vwal-stdenv-darwin' is not allowed to refer to the following paths:
         /nix/store/c7ld8w5d3w9y074fpss6i3gfkrw5g6gz-SDKs
  ```
  (Hydra [shows](https://hydra.nixos.org/log/zkw8dy0jqz2ak0ndh9fz19hzwcfda29b-stdenv-darwin.drv) just an empty log)
  Solved by e7eb209fed6d400bab258baece1c6f6f50e14eea
- [x] `haskellPackages.ghc` on aarch64-darwin (only)
  https://hydra.nixos.org/build/216912533#tabs-buildsteps
  https://github.com/NixOS/nixpkgs/pull/227919
- [x] `postgresql` (all versions probably) on aarch64-darwin (only);
  https://hydra.nixos.org/build/216681345#tabs-buildsteps
  ```
  error: output '/nix/store/pyildgppqp611v4wswhcnxwrdma52s22-postgresql-14.7' is not allowed to refer to the following paths:
           /nix/store/dzxdakiazglahca47jz5vagx80wxl1l1-clang-wrapper-11.1.0
  ```
    https://github.com/NixOS/nixpkgs/pull/227919

### CODE REVIEW

**Comment by vcunat** [comment]
aarch64-darwin is quite a mess: [no postgresql](https://hydra.nixos.org/build/216681345#tabs-buildsteps) (probably cycle among outputs) and [no ghc/haskell](https://hydra.nixos.org/build/216912533#tabs-buildsteps).  On other three platforms these build OK.

_I don't have access to an aarch64-darwin machine.  I don't want to spend time on darwin anyway._

**Comment by wegank** [comment]
I have no idea why https://github.com/NixOS/nixpkgs/pull/226795/commits/e7eb209fed6d400bab258baece1c6f6f50e14eea was x86_64-darwin-only: setting `stripDebugFlags = [ "-S" ];` fixes the build of `postgresql` on aarch64-darwin.

**Comment by vcunat** [comment]
So if people knowing darwin confirm they think it's best that way, I/we can trivially remove the condition.  It will just take some time to get binaries, maybe two days when it's just aarch64-darwin.

**Comment by wegank** [comment]
> It will just take some time to get binaries, maybe two days when it's just aarch64-darwin.

Yeah, it took 9 hours on my machine just for `ghc`.

**Comment by vcunat** [comment]
This reached both `nixos-unstable*` channels now.

**Pull request merged**
