### PR TITLE
postgresql: default to v15 in 23.11

### PR DESCRIPTION
**Pull request by nbdd0121**
## Description of changes

Change the default postgres version from 14 to 15 in release 23.11.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by thoughtpolice — CHANGES_REQUESTED** [review]
This also needs a change in `all-packages.nix` to change the default `postgresql` and `postgresqlPackages` expressions.

EDIT: Specifically, look here &mdash; https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L27276-L27289

Please swap 14 and 15, and make sure the entries are otherwise sorted as they are now.

**Comment by natsukium** [comment]
This PR should go to `staging`.
https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#flow-of-merged-pull-requests

**Comment by kirillrdy** [comment]
@nbdd0121 please rebase and fix merge conflicts

**Comment by nbdd0121** [comment]
Rebased

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by kirillrdy** [comment]
@nbdd0121  looks like conflict again

**Comment by kirillrdy** [comment]
how about making 16 default for 23.11 ?

**Comment by nbdd0121** [comment]
I think psql 16 is too new for 23.11 release. IIUC timescaledb doesn't yet support psql 16. Probably would be better to wait a bit before making it the default.

**Review by thoughtpolice — APPROVED** [review]

**Comment by leona-ya** [comment]
I'm sorry to come up with this now, i haven't seen this PR before it got merged. I think users will probably get confused that `services.postgresql.ensureUsers`/`ensureDatabases` will not "just" work (see #216989 for context). imo we should use postgresql 14 for less confusion (it's okay if you feel different)

**Comment by SuperSandro2000** [comment]
We have 3 PRs to choose from to fix this: #203474 , #252071, #255961

**Pull request merged**
