### PR TITLE
syncthing-inotify: 0.8.3 -> 0.8.4

### PR DESCRIPTION
**Pull request by jokogr**
###### Motivation for this change

Package upgrade

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] OS X
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
Is the darwin failure reported by travis expected?

**Comment by jokogr** [comment]
@joachifm no, but let me come up with a solution, I think I know what it needs :)

**Comment by jokogr** [comment]
@joachifm all set, nowadays the situation with Go apps in Darwin is a bit nasty.

**Comment by joachifm** [comment]
Thank you

**Pull request merged**
