### PR TITLE
qt6.qtwebengine: fix LibraryExecutablesPath

### PR DESCRIPTION
**Pull request by linsui**
###### Description of changes

A followup of https://github.com/NixOS/nixpkgs/pull/174287. Remove old patch. Fix LibraryExecutablesPath.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

@NickCao

### CODE REVIEW

**Comment by NickCao** [comment]
Build failed with:
```
error: cycle detected in build of '/nix/store/hj1y4hinw8hqzzs0dz3jkzw78ljhlwdl-qtwebengine-6.3.0.drv' in the references of output 'dev' from output 'out'
```

**Comment by linsui** [comment]
Looks like I should put libexec into $out.

**Comment by NickCao** [comment]
> Looks like I should put libexec into $out.

That would require changes to the cmake patch and a few other palaces.

**Comment by linsui** [comment]
I guess you mean

```
+        } else if (cmHasLiteralPrefix(e, "libexec") || cmHasLiteralPrefix(e, "./libexec")) {
+          result += std::getenv("dev");
```

I don't know if this is the right way.

**Comment by NickCao** [comment]
That's it, but for the other qt modules, binaries in libexec are mainly for development and should be in the $dev output. Can we instead try moving the single binary of qtwebengine to $out and see if that works?

**Comment by linsui** [comment]
Yes, it's strange. I'll move it to $out in postinstall.

**Comment by linsui** [comment]
I'll test it with Jami later.

In Debian this is packaged as another package https://packages.debian.org/bookworm/amd64/libqt6webenginecore6-bin/filelist and gn is not packaged in -dev. I doubt if gn should be packaged in a qt package.

**Comment by NickCao** [comment]
gn must have been leaked in, not a sure an upstream bug or an artifact of the patch.

**Comment by linsui** [comment]
Should I remove it in this PR? Or you will do a proper fix?

**Comment by NickCao** [comment]
Apparently Arch Linux has that gn in their qt6-qtwebengine too, see https://archlinux.org/packages/extra/x86_64/qt6-webengine/. We should file an upstream issue. Leaving it as is should be safe for us now.

**Comment by linsui** [comment]
Then I'll just leave it as is.

**Review by NickCao — APPROVED** [review]
Tested with jami.

**Comment by linsui** [comment]
Thanks!

**Comment by linsui** [comment]
Tested with jami.

**Comment by nrdxp** [comment]
@linsui, if you don't mind my query, I was just wondering if you were actually able to build qtwebengine all the way to the end with this fix? I assume you were, but then I cannot seem to. Strangely the build is canceled apparently by the receiving of SIGTERM very late in the build (only a few thousand objects to go). It's rather annoying, and even more perplexingly, if I just cd into the failed build and call the build command, it finishes no problem outside of the sandbox.

Just curious if you saw this error at any point:
```
  g++: fatal error: Terminated signal terminated program cc1plus
```
Which happens at this point in the build:
```
  [25430/29280] CXX obj/content/browser/browser/page_handler.o
```

I double checked my nix.conf and I don't have any timeouts configured so I'm really confused how it ended up receiving a signal out of nowhere? I reproduced this 3 times, which took basically all day yesterday :face_exhaling:

**Comment by linsui** [comment]
> I was just wondering if you were actually able to build qtwebengine all the way to the end with this fix?

Yes, it did build for me though it sometimes crashes my system.

I have no idea why it fails for you. Maybe you can just wait for the binary cache.

**Comment by nrdxp** [comment]
Thank linsui, but if my suspicion is correct (`ulimit -n` too low), then the same thing is already happening on hydra, and won't be fixed without an increase. I'm about about to start a build now to confirm.

**Pull request merged**
