### PR TITLE
napi-rs-cli: 2.12.0 -> 2.17.0

### PR DESCRIPTION
**Pull request by martinjlowm**
## Description of changes

Bumps the derivation to the latest version of `@napi-rs/cli`. 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by sikmir** [comment]
Commit message should follow conventions: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions

**Comment by martinjlowm** [comment]
> Commit message should follow conventions: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions

Missed that one. Updated the commit message with motivation and specific version change.

**Comment by sikmir** [comment]
Result of `nixpkgs-review pr 272524` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>matrix-appservice-slack</li>
    <li>matrix-sdk-crypto-nodejs</li>
    <li>matrix-sdk-crypto-nodejs-0_1_0-beta_3</li>
    <li>mjolnir</li>
    <li>napi-rs-cli</li>
  </ul>
</details>

**Comment by sikmir** [comment]
[2.17.0](https://github.com/napi-rs/napi-rs/releases/tag/%40napi-rs%2Fcli%402.17.0) is out.

**Comment by aqrln** [comment]
Result of `nixpkgs-review pr 272524` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>matrix-appservice-slack</li>
  </ul>
</details>
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>matrix-appservice-discord</li>
    <li>matrix-appservice-irc</li>
    <li>matrix-hookshot</li>
    <li>matrix-sdk-crypto-nodejs</li>
    <li>matrix-sdk-crypto-nodejs-0_1_0-beta_3</li>
    <li>mjolnir</li>
    <li>napi-rs-cli</li>
  </ul>
</details>

**Comment by aqrln** [comment]
`matrix-appservice-slack` build failure looks unrelated and is reproducible on `master` as well:

```
error matrix-appservice-slack@2.1.2: The engine "node" is incompatible with this module. Expected version ">=16 <=18". Got "20.10.0"
error Commands cannot run with an incompatible environment.
```

Everything else looks good.

**Review by aqrln — APPROVED** [review]

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 272524` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>matrix-appservice-slack</li>
    <li>matrix-sdk-crypto-nodejs</li>
    <li>matrix-sdk-crypto-nodejs-0_1_0-beta_3</li>
    <li>mjolnir</li>
    <li>napi-rs-cli</li>
  </ul>
</details>

**Pull request merged**
