### PR TITLE
libinput: 1.25.0 -> 1.26.0

### PR DESCRIPTION
**Pull request by trofi**
Changes: https://lists.freedesktop.org/archives/wayland-devel/2024-June/043657.html

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by betalars** [comment]
Can this please get moved forward?

It fixes a quite annoying bug on Framework 16

:sparkles:  Thanks :sparkles:

**Review by Janik-Haag — COMMENTED** [review]
Hey, I tried changing libinput to the bumped version using a overlay earlier, libinput built fine but it caused some other build failures. Do I have to overwrite more then just pkgs.libinput?

**Comment by trofi** [comment]
I personally applied it locally on `nixpkgs` and built the `system` successfully. I would expect `libinput` override to be enough. DO you have an example package breakage? I wonder if I can reproduce it locally.

**Comment by betalars** [comment]
Hm if this MR seems to be a longer process, would it be worthwhile to add the framework quirk as a post build hook?

See Section 6.1 in https://wiki.archlinux.org/title/Framework_Laptop_16

I can do it myself but something tells me I am not the only nixos framework user.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
@Janik-Haag Can you please provide some more details? Otherwise I would leave this up for staging to find unless we have a strong suspicion that there are many regressions.

**Comment by Janik-Haag** [comment]
Sure, I just didn't have time to post the log yesterday. Qtbase is failing when I overlay libinput from this fork https://gist.github.com/Janik-Haag/eadb2bc3acf8cd8b20c0fb613a82c641

This is the overlay I'm using:
```nix
      (final: prev: {
        libinput = (import sources.libinput { }).libinput;
      })
```
sources.libinput gets pulled from https://github.com/trofi/nixpkgs/tree/libinput-update

**Comment by trofi** [comment]
> Sure, I just didn't have time to post the log yesterday. Qtbase is failing when I overlay libinput from this fork https://gist.github.com/Janik-Haag/eadb2bc3acf8cd8b20c0fb613a82c641
> 
> This is the overlay I'm using:
> 
> ```nix
>       (final: prev: {
>         libinput = (import sources.libinput { }).libinput;
>       })
> ```
> 
> sources.libinput gets pulled from https://github.com/trofi/nixpkgs/tree/libinput-update

`import sources.libinput { }` is a `nixpkgs` instantiation, yes? If `source` is a `nixpkgs` instantiation then you are mixing all the packages from two nixpkgs versions. That will cause library collisions in it's worst form: https://trofi.github.io/posts/248-how-do-shared-library-collisions-break.html. Specifically `qt5.qtbase` will use host's dependencies that don't use `libinput` including `glibc` and overlay's dependencies that use `libinput`.

It could work if you did a (untested) `prev callPackage "${sources}/pkgs/development/libraries/libinput/default.nix" { }` in a single file from the overlay source (not the `nixpkgs` instance).

For example both the below this does work for be in `x86_64-linux`:
```
$ nix build --no-link github:NixOS/nixpkgs/pull/317826/head#qt5.qtbase
$ nix build --no-link github:NixOS/nixpkgs/pull/317826/merge#qt5.qtbase
```

**Comment by Janik-Haag** [comment]
> import sources.libinput { } is a nixpkgs instantiation, yes?

Correct. Yeah, you're right, I messed up with the overlay.
I tried doing
```nix
      (final: prev: {
        libinput = pkgs.libinput.overrideAttrs (o: {
          version = "1.26.0";
          src = pkgs.fetchFromGitLab {
            domain = "gitlab.freedesktop.org";
            owner = "libinput";
            repo = "libinput";
            rev = "1.26.0";
            hash = "sha256-mlxw4OUjaAdgRLFfPKMZDMOWosW9yKAkzDccwuLGCwQ=";
          };
        });
      })
```
to make sure, I just have the updated libinput version with the correct dependencies.
But it results in the same build error, not really sure what's causing it.

https://releases.nixos.org/nixpkgs/nixpkgs-24.11pre640317.38d3352a65ac/nixexprs.tar.xz is the channel I'm using.
> For example both the below this does work for be in x86_64-linux:

I'm also on x86_64-linux

Sorry for holding up the update :/

**Comment by trofi** [comment]
I think you want `prev.libinput.overrideAttrs`, not `pkgs.libinput.overrideAttrs`.

**Review by Janik-Haag — APPROVED** [review]

**Comment by Janik-Haag** [comment]
> I think you want prev.libinput.overrideAttrs, not pkgs.libinput.overrideAttrs.

Yeah, you are right. I'm really not too familiar with how overlays work. I wonder what's causing the difference, since both package imports are the same, so the libs shouldn't otherwise change. Anyway the change works, so we can merge this, sorry for holding it up so long.

**Pull request merged**
