### PR TITLE
Hydra updates 3

### PR DESCRIPTION
**Pull request by Mindavi**
cc @ajs124 @lheckemann @lovesegfault

Tried updating to nix 2.7, but that also doesn't work. Seems like we're stuck on 2.6 for now for hydra, hopefully that doesn't cause too much issues.

Probably time to bump hydra once again, but as for the previous PR: let's get this in first and then move forward with further improvements.

The previous PR already made it nix 2.6 anyway, so there's not much to lose here.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lheckemann** [comment]
I'm not so sure about the autoformatting, it makes it harder to compare with the upstream expression (which I'd consider "canonical").

If we're getting rid of multi-versioning (I'm in favour!), we should also remove the multi-versioning from the nixos test for hydra.

Other than that, LGTM :+1:

**Comment by Mindavi** [comment]
Thanks for the review! I will drop the (auto-)formatting commit, no big deal. But I didn't look at the upstream flake to mirror it, are you willing to fix that up?

I'll look into the hydra multi-versioning.

**Comment by lheckemann** [comment]
The indentation on the upstream flake is deeper, so it's not feasible to have it 100% the same; and I just noticed that the formatting is quite different anyway, so disregard and let's keep the nixpkgs-fmt change in, and maybe also apply that upstream.

**Comment by Mindavi** [comment]
Looked into removing multi-versioning from the nixos test, but it doesn't seem to be in the way much and I'm not sure where to start, so I'll leave that up to you :).

Too bad the build of UUID4-Tiny is broken on aarch64 (https://logs.nix.ci/?key=nixos/nixpkgs.172378&attempt_id=1669bcf6-7b5e-4c57-864d-a2e5569ce24d). Not sure if hydra works/builds on aarch64, but it was building ok before: https://hydra.nixos.org/build/168901053.

Will report upstream as well, maybe they want to fix that by using a different package that _does_ build on aarch64.

**Comment by Mindavi** [comment]
I tried a preliminary patch which may or may not work. If it doesn't I'll just drop it and merge this as-is, unless there is anything I should still address here.

**Comment by Mindavi** [comment]
@ofborg build perlPackages.UUID4Tiny

**Comment by lheckemann** [comment]
Ohhh boy that is an... interesting approach :smile: but fine by me.

**Pull request merged**
