### PR TITLE
 thunderbird, thunderbird-bin: 68.1.0 -> 68.1.1 

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

- Bug fixes

https://www.thunderbird.net/en-US/thunderbird/68.1.1/releasenotes/

The release notes mentions “Various security fixes”, but security advisories are not available.
https://www.mozilla.org/en-US/security/known-vulnerabilities/thunderbird/#thunderbird68.1.1

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @Fuuzetsu, @nbp, @edolstra

### CODE REVIEW

**Comment by alexarice** [comment]
Built both of these with nix-review, started `thunderbird` and that seems to work fine, however when I started `thunderbird-bin` it complained that my profile had been setup by a newer version. Shouldn't these both be the same version?

On a side note, can I revert this in any way, I want to use installed thunderbird again

**Comment by taku0** [comment]
Try `--allow-downgrade` option on startup.

**Comment by taku0** [comment]
The Security Advisory is updated. It is a moderate security fix.
https://www.mozilla.org/en-US/security/advisories/mfsa2019-32/

**Comment by vcunat** [comment]
I noticed even before this bump that there's apparently something wrong in the way they compare version of -bin and non-bin.

**Review by vcunat — APPROVED** [review]
Both seem to work fine.

**Pull request merged**
