### PR TITLE
Fix lima vz support by forcing Apple SDK 15 usage

### PR DESCRIPTION
**Pull request by josvazg**
Help wanted: This does not work, but maybe the fix is easy? 

Related to #346006

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
You want `buildInputs` , not `nativeBuildInputs`.

If the SDK version QEMU is built with matters, it should be changed in the QEMU package rather than overridden here.

**Comment by josvazg** [comment]
> You want `buildInputs` , not `nativeBuildInputs`.
> 
> If the SDK version QEMU is built with matters, it should be changed in the QEMU package rather than overridden here.

Thanks for the help and guidance? a few questions:

- Why not `nativeBuildInputs`? I guess `apple-sdk` does not apply to non `darwin` platforms.

- If `qemu` default build is stuck at `apple_sdk` 11 they might have a reason, right? Which means an override will fix this package that needs the newer SDK and to use `vz` rather than only have the option of `qemu` as a VM. On the other hand, if they are stuck with 11 it might mean that `qemu` nix package might not work without further effort on a newer SDK.

This can get into a deep rabbit hole.

**Comment by emilazy** [comment]
> * Why not `nativeBuildInputs`? I guess `apple-sdk` does not apply to non `darwin` platforms.

`nativeBuildInputs` are for tools that run during the build. We want to override SDK for the host platform.

> * If `qemu` default build is stuck at `apple_sdk` 11 they might have a reason, right? Which means an override will fix this package that needs the newer SDK and to use `vz` rather than only have the option of `qemu` as a VM. On the other hand, if they are stuck with 11 it might mean that `qemu` nix package might not work without further effort on a newer SDK.

It’s actually using 12.3, and the reason is just that we had no newer SDKs available until recently. Though I wasn’t aware that QEMU could make use of any features that aren’t available on the 12.3 SDK? But I could be wrong.

**Comment by booxter** [comment]
FYI I bumped lima version and realized I need to also bump SDK to continue running ubuntu images with default templates, so something like this PR is also included in https://github.com/NixOS/nixpkgs/pull/355729

**Comment by josvazg** [comment]
Thanks @booxter !

Closing as a (partial) duplicate of #355729

**Pull request closed without merging**
