### PR TITLE
msi-ec: 0-unstable-2024-09-19 -> 0-unstable-2024-11-04

### PR DESCRIPTION
**Pull request by m1dugh**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin

- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by m1dugh** [comment]
I don't know where to add the release notes for `24.11`, any help ?

**Comment by Tungsten842** [comment]
You can probably remove the patches, as they are now included directly in the code.
https://github.com/BeardOverflow/msi-ec/pull/168/
https://github.com/BeardOverflow/msi-ec/pull/170

**Comment by m1dugh** [comment]
@Tungsten842 should be good

**Comment by m1dugh** [comment]
Result of `nixpkgs-review pr 353627` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_4_hardened.msi-ec</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_4.msi-ec</li>
  </ul>
</details>
<details>
  <summary>15 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_10.msi-ec</li>
    <li>linuxKernel.packages.linux_5_10_hardened.msi-ec</li>
    <li>linuxKernel.packages.linux_5_15.msi-ec</li>
    <li>linuxKernel.packages.linux_5_15_hardened.msi-ec</li>
    <li>linuxKernel.packages.linux_6_1.msi-ec</li>
    <li>linuxKernel.packages.linux_6_11.msi-ec</li>
    <li>linuxKernel.packages.linux_6_1_hardened.msi-ec</li>
    <li>linuxKernel.packages.linux_6_6.msi-ec</li>
    <li>linuxKernel.packages.linux_hardened.msi-ec (linuxKernel.packages.linux_6_6_hardened.msi-ec)</li>
    <li>linuxKernel.packages.linux_latest_libre.msi-ec</li>
    <li>linuxKernel.packages.linux_libre.msi-ec</li>
    <li>linuxKernel.packages.linux_lqx.msi-ec</li>
    <li>linuxKernel.packages.linux_xanmod.msi-ec</li>
    <li>linuxKernel.packages.linux_xanmod_latest.msi-ec (linuxKernel.packages.linux_xanmod_stable.msi-ec)</li>
    <li>linuxKernel.packages.linux_zen.msi-ec</li>
  </ul>
</details>

**Review by Tungsten842 — APPROVED** [review]

**Comment by m1dugh** [comment]
@wegank If you have time to merge this :heart:

**Pull request merged**
