### PR TITLE
apostrophe: fix latex rendering by providing local mathjax

### LINKED ISSUE #338968: Apostrophe doesn't render LaTeX blocks in Preview
### Describe the bug
Apostrophe doesn't render LaTeX in Preview Mode, as expected. Instead of rendering maths equations (like `\frac{p}{q}`) as equations, it escape them while surrounding them with either parenthesis or square brackets.

### Steps To Reproduce
1. Declare `pkgs.apostrophe` in `environment.systemPackages`
2. Open Apostrophe's tutorial
3. Open Preview Mode using CTRL+P
4. Navigate to the `Math` section
5. See the equations made in LaTeX escaped instead of rendered with Pandoc LaTeX

### Expected behavior
It should render the equations and any symbols written between `$` or `$$` with pandoc LaTeX, for example showing `\frac{p}{q}` as a fraction and not `\(\frac\{p\}\{q\}\)`

### Screenshots
In editing:
image

In preview:
image

### Additional context
This behavior is reproducible on both Apostrophe 3.0 and 3.1. (ie. NixOS 24.05 and NixOS 24.11 (unstable)

I also tried installing alongside Apostrophe `pandoc` and `tex-live.scheme-full` and `tex-live.scheme-medium` to no avail.

### Notify maintainers

@aleksana
@sternenseemann

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.44, NixOS, 24.11 (Vicuna), 24.11.20240804.cb9a96f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/4cpakzyvfw1rmm9v5i3387x6jd2h1v86-source
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Aleksanaa**
## Description of changes

image

Closes https://github.com/NixOS/nixpkgs/issues/338968

Also the upstream is a bit messy now. The "converting latex expression to picture in preview" is actually dead code. I'll try to report to upstream, but this seems fine in all sense (also exporting isn't affected).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Aleksanaa** [comment]
You are right, I'll try to inject mathjax. Maybe their pandoc is bundled with mathjax? These gtk developers are less willingly to solve downstream problems other than Flatpak nowadays

**Comment by Aleksanaa** [comment]
Oh... `glib-networking` again?

**Comment by sternenseemann** [comment]
No clue! Could also be cross site origin policy (but for local files?!). `pandoc`'s man page says `--mathjax` without an argument means it loads the mathjax script from cloudflare.

**Comment by sternenseemann** [comment]
FWIW we should probably prevent that if possible since I don't like your text editor loading random stuff from cloudflare

**Comment by sternenseemann** [comment]
`echo '$x_2$' | pandoc --mathjax --standalone` shows that it emits a working cdn reference.

**Comment by Aleksanaa** [comment]
image

Elegant!

```
$$f(x) \xrightarrow{\mathfrak{F}} \hat{f} (\xi)$$
$$\hat{f} (\xi)=\int_{-\infty}^{\infty}f(x)e^{-2\pi ix\xi}dx$$
```

**Review by sternenseemann — APPROVED** [review]

**Pull request merged**
