### PR TITLE
lxterminal: 0.3.2 -> 0.4.0

### PR DESCRIPTION
**Pull request by pbsds**
## Description of changes

This one seems to have been outdated for a long time, and the config i carried over from arch didn't quite work.

Diff: https://github.com/lxde/lxterminal/compare/0.3.2...0.4.0

The homepage has 404'd but on their forum they indicate that the wiki is flaky.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by spacefault — APPROVED** [review]
Result of `nixpkgs-review pr 262392` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>lxterminal</li>
  </ul>
</details>

Everything seems functional, this should be good for approval.

**Comment by pbsds** [comment]
The nixos terminal emulator test also builds

**Review by velovix — APPROVED** [review]
I'm sorry to say that I don't use NixOS or lxterminal anymore, but this looks reasonable to me.

**Review by velovix — APPROVED** [review]
Also if you would mind removing me from the maintainers list, I would appreciate it. I don't think I'm engaged enough anymore to be a good maintainer of this package.

**Review by Mindavi — APPROVED** [review]

**Pull request merged**
