### PR TITLE
syncthingtray: 1.2.3 -> 1.3.0

### LINKED ISSUE #199596: syncthingtray: error loading plasmoid's QML
### Describe the bug
The tray icon appears, but he according window shows:
```
file:///nix/store/s579qmf6md5nl1hyhxnm5agkl75xbgr6-syncthingtray-1.2.3/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/main.qml:13:34: Type FullRepresentation unavailable

file:///nix/store/s579qmf6md5nl1hyhxnm5agkl75xbgr6-syncthingtray-1.2.3/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/FullRepresentation.qml:16:9: Type ToolBar unavailable

file:///nix/store/s579qmf6md5nl1hyhxnm5agkl75xbgr6-syncthingtray-1.2.3/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/ToolBar.qml:7:1: module "martchus.syncthingplasmoid" is not installed
```

### Steps To Reproduce
1. Install syncthingtray (through home.packages in home-manager in my case)
2. Click on the tray icon

### Expected behavior
The proper GUI with shiny buttons and stuff

### Notify maintainers
@doronbehar 

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.6, NixOS, 22.11 (Raccoon), 22.11pre423448.a2a777538d9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos"`
 - channels(maverick): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by doronbehar**
###### Description of changes

https://github.com/Martchus/syncthingtray/compare/v1.2.3...v1.3.0

https://github.com/Martchus/qtforkawesome/compare/v0.0.4...v0.1.0

https://github.com/Martchus/qtutilities/compare/v6.8.0...v6.10.0

###### Things done

~~Maybe fix~~ Related: #199596 .

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
@EvilMav could you check this update?

**Comment by EvilMav** [comment]
Thank you for looking into it! No joy so far unfortunately:
image

PS I'm a NixOS noob, so let me know if there is anything that I might be doing wrong.

**Comment by doronbehar** [comment]
I'm sort of a KDE/plasma noob :). I wonder what upstream would think about this, I think you should try and get their help in debugging this. https://github.com/Martchus/syncthingtray/issues/133 seems like a somewhat related issue..

**Comment by doronbehar** [comment]
I'm merging this anyway, we can continue on with resolving https://github.com/NixOS/nixpkgs/issues/199596 later.

**Pull request merged**
