### PR TITLE
ryujinx: remove package

### LINKED ISSUE #187020: [Packaging Request] ryujinx-ldn
**Project description**
Ryujinx's internet multiplayer build, even supporting interconnectivity with Switch Consoles.

**Metadata**

* homepage URL: https://www.patreon.com/posts/introducing-ldn2-45268370
* source URL: https://github.com/Ryujinx/Ryujinx
* license: MIT
* platforms: linux

### LINKED ISSUE #325857: Build failure: ryujinx hangs intermittently during testing
### Steps To Reproduce

1. build ryujinx

### Build log

This is where the build appeared to hang:

```
  Passed Bic_64bit(31,1,2,9223372036854775807UL,9223372036854775808UL,2,32) [2 ms]
  Passed Bic_64bit(uint.MinValue,31,31,ulong.MinValue,ulong.MinValue,1,uint.MinValue) [2 ms]
  Passed Bic_64bit(31,31,2,9223372036854775808UL,ulong.MaxValue,uint.MinValue,63) [3 ms]
  Passed Bic_64bit(31,1,31,ulong.MaxValue,9223372036854775807UL,uint.MinValue,uint.MinValue) [2 ms]
  Passed Bic_64bit(uint.MinValue,31,2,ulong.MinValue,9223372036854775807UL,3,32) [2 ms]
  Passed Bic_64bit(31,31,31,ulong.MinValue,ulong.MinValue,2,63) [2 ms]
  Passed Bic_64bit(31,31,31,9223372036854775807UL,ulong.MaxValue,3,31) [2 ms]
  Passed Bic_64bit(31,1,31,9223372036854775807UL,9223372036854775808UL,1,uint.MinValue) [2 ms]
  Passed Bic_64bit(uint.MinValue,31,31,9223372036854775808UL,9223372036854775807UL,2,31) [3 ms]
  Passed Bic_64bit(uint.MinValue,31,31,9223372036854775808UL,ulong.MinValue,1,31) [2 ms]
  Passed Bic_64bit(uint.MinValue,1,2,9223372036854775808UL,ulong.MaxValue,2,32) [2 ms]
  Passed Bic_64bit(31,1,31,ulong.MaxValue,ulong.MinValue,3,31) [2 ms]
  Passed Bic_64bit(31,1,31,ulong.MaxValue,9223372036854775808UL,3,63) [2 ms]
  Passed Bic_64bit(uint.MinValue,31,31,ulong.MaxValue,9223372036854775807UL,2,31) [2 ms]
  Passed Bics_32bit(uint.MinValue,31,2,2147483647,uint.MinValue,uint.MinValue,16) [3 ms]
  Passed Bics_32bit(uint.MinValue,1,31,uint.MinValue,uint.MaxValue,2,uint.MinValue) [3 ms]
```

These processes were running under nix-daemon:

```
           │ │ ├─1826276 bash -e /nix/store/v6x3cs394jgqfbi0a42pam708flxaphh-default-builder.sh
           │ │ ├─1869721 dotnet test src/Ryujinx.Tests/Ryujinx.Tests.csproj -maxcpucount:1 -p:ContinuousIntegrationBuild=true -p:Deterministic=true --configuration Release --no-buil>
           │ │ ├─1870378 dotnet exec /nix/store/b6p63lq7xgqpk9afx5rxbdbkk9aghbkr-dotnet-sdk-8.0.301/sdk/8.0.301/vstest.console.dll --settings:/build/source/src/Ryujinx.Tests/.runset>
           │ │ └─1870572 /nix/store/b6p63lq7xgqpk9afx5rxbdbkk9aghbkr-dotnet-sdk-8.0.301/dotnet exec --runtimeconfig /build/source/src/Ryujinx.Tests/bin/Release/net8.0/linux-x64/Ryuj>
```
### Additional context

I killed the latter process at this point, resulting in:

```
The active test run was aborted. Reason: Test host process crashed
```

This has happened multiple times for me.  I estimate something like 5/10.

### Notify maintainers

@06kellyjac @artemist 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.8, NixOS, 24.11 (Vicuna), 24.11.20240708.aaebd24`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(david): `"servers-22.11"`
 - channels(root): `""`
 - nixpkgs: `not found`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #345410: Update request: [BACKPORT] Ryujinx 1298 → 1398
- Package name: Ryujinx
- Latest released version: 1398

- Current version on the unstable channel: 1398
- Current version on the stable/release channel: 1298

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@06kellyjac
@artemist 

-----

Note for maintainers: Please tag this issue in your PR.
backport
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #345758: Ryujinx has been removed.  Need to decide next steps.
## Issue description

The owner of the Ryujinx organization has deleted the org and all data.  According to riperiperi on the discord:
```
Yesterday, gdkchan was contacted by Nintendo and offered an agreement to stop working on the project, remove the organization and all related assets he's in control of. While awaiting confirmation on whether he would take this agreement, the organization has been removed, so I think it's safe to say what the outcome is.
```

This is a hard block to building ryujinx anymore.  Like Yuzu before, something needs to be decided here, though in this case this is *not* a DMCA take down, so existing license applies.  Might make just as much sense to find a valid fork in the not too distant future.

# Maintainers

@06kellyjac
@artemist

### PR DESCRIPTION
**Pull request by Naxdy**
This is not a PR I wanted to make, but sadly Ryujinx has been taken down upstream, and doesn't look like it's coming back. As per their official discord server:

image

The GitHub repo (and the entire org, in fact) is also no longer accessible: https://github.com/Ryujinx/Ryujinx/

Don't see a need to backport this to 24.05, because binary cache. Users customizing their builds (or one or more dependents) will find their build processes failing however, due to upstream being gone.

Since this doesn't appear to have been the result of a DMCA takedown, but rather a voluntary decision, for those who wish to continue building Ryujinx from source, I offer my self-hosted mirror repo here: https://git.naxdy.org/Mirror/Ryujinx - don't rely on this being around forever, though.

Closes https://github.com/NixOS/nixpkgs/issues/345758
Closes https://github.com/NixOS/nixpkgs/issues/325857
Closes https://github.com/NixOS/nixpkgs/issues/345410
Closes https://github.com/NixOS/nixpkgs/issues/187020

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by AndersonTorres — APPROVED** [review]
Life is not fair...

**Comment by niklaskorz** [comment]
Before some trigger-happy person presses the merge button, please have a look at the ongoing discussion in #345758 where the current maintainer of the package explicitly speaks against removal.

**Comment by Frontear** [comment]
As above, please avoid merging until the issue has reached a generally acceptable consensus.

**Comment by Naxdy** [comment]
Closing due to https://github.com/NixOS/nixpkgs/pull/346694 being merged instead. Before reopening / opening a similar removal PR, refer to the discussion in https://github.com/NixOS/nixpkgs/issues/345758

**Pull request closed without merging**
