### PR TITLE
services.xserver: fix defaults of X11

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

follow-up for #30517 (/cc @nbp @bendlas @NeQuissimus)

This ensures that if a WM/DM is enabled, no default needs to be set and re-adds my original change.

Please not that setting `services.xserver.enable = true;` without any further configuration works now
since `xterm` is enabled by default.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by nbp** [comment]
@rycee, @NeQuissimus, @vyp , would that work for your use cases?
Basically this changes select the first activated window / desktop manager as the default one if any is set, and if the default is still "none".

Is there a use case for having a system wide window / desktop manager while not having any enabled by default?

**Comment by bendlas** [comment]
@Ma27 thanks, I'll try it with my next build.

Could you also mention `services.xserver.desktopManager.default` with example values in the assertion, so that people running into this know what to look  for?

**Comment by Ma27** [comment]
yeah, sure. However this will have to wait until wednesday...

**Comment by NeQuissimus** [comment]
I think this makes sense

**Comment by Ma27** [comment]
@bendlas better?

**Comment by bendlas** [comment]
The new assertion message looks better, thanks! My config still evaluates. I'll report back, if it broke anything else for me, but I don't expect it to.

**Comment by bendlas** [comment]
Is this ticket blocked on something?
I'd like to drop these commits from my mergebox and for all I care, they can go in. I did not do any validation on them, though, other than not breaking my system.

**Comment by rycee** [comment]
Looks good to me™ 👍

**Comment by aszlig** [comment]
The problem here is that if for example you don't want to use a desktop manager at all, you'd need to disable the `xterm` desktop manager, which I think is a bit counter-intuitive. So what we essentially had two variants of "special" DM/WMs prior to this merge, where `""` meant "pick first" and `none` meant pick none at all. The latter is an [actual element](https://github.com/NixOS/nixpkgs/blob/f557844c082fd1b590be3eebec2a3a84acf6973c/nixos/modules/services/x11/desktop-managers/none.nix) of the sessions list.

Now `none` **always** means "pick first" for the reason being, that the `none` session is enabled unconditionally. Apart from that `xterm` is enabled by default which in turn leads to `xterm` being picked as a session because it has more priority than `none`. However in order to specify the real `none` session, you need to explicitly disable *all* of the DM/WMs (by default it's just xterm, but it's still counter-intuitive).

This problem shows up in #32020, because the tests now get `xterm` as DM, despite setting the DM to `none`.

So the solution would be either to change the order of the `none` session to have highest priority (which still is counter-intuitive, because `none` is an actual session in the list) or to revert to the old behavior (which I'd prefer) but improving the type and description for the `default` options a bit to make it more clear what's the difference between `none` and "pick first".

**Comment by Ma27** [comment]
hi @aszlig 

sorry for the delay, I definitely owe you a beer at the next NixCon! :-)

IIRC this was originally addressed to improve the UX the `xserver` module as "" for "pick first" isn't that intuitive. I'd propose to revert the behavior, but find a better solution than using an empty string as default value, ok?

Unfortunately my time on this weekend is quite limited, so you'd have to wait until next week until I could submit a patch :-)

**Comment by PierreR** [comment]
FWIW I don't use any `desktop manager` and I can't thank  @pbogdan enough to drive me to the right place and the comment from @aszlig in order to understand why my configuration suddenly broke when switching to `18.03` ...

@Ma27 It would it be nice to settle this before the `18.03` release ;-)

**Comment by Ma27** [comment]
@PierreR thanks for the ping. As the entire change happened some time ago is it ok when I have a look at it tomorrow? %)

**Comment by Ma27** [comment]
ok, short update: unfortunately my time is a bit limited from now on (I can try to fix this on the weekend though), however if anybody else wants to take over, I'm fine with this as well...

**Comment by bendlas** [comment]
FWIW, I'd be fine with just reverting all of this changeset. I stopped complaining last fall, when my config worked again, but I didn't think it was a good idea to artificially restrict allowed system configurations, and I don't think it's a good idea now.

@Ma27 what the point of adding these assertions again? Do you still think it's worth potentially breaking many users over this? Are you going to commit to maintaining this and responding to newly discovered breakage? If you have little time, that's fine (I think that's the case for most NixOS Contributors, myself included), but if you want to make changes in something so critical as the X config, you better make sure that your changes work for everybody. If you can't be bothered with this maintenance responsibility, you can very easily use a forked X module in your own config.

@rycee it seems to me, that you were the original sponsor of these changes. Are you willing to adopt maintainership for them?

**Comment by Ma27** [comment]
> what the point of adding these assertions again? Do you still think it's worth potentially breaking many users over this? Are you going to commit to maintaining this and responding to newly discovered breakage? If you have little time, that's fine (I think that's the case for most NixOS Contributors, myself included), but if you want to make changes in something so critical as the X config, you better make sure that your changes work for everybody.

I think you misunderstood my point. Reverting is fine, the change was obviously a mistake, however I think that @aszlig made an important point by saying "but improving the type and description for the default options a bit to make it more clear what's the difference between none and "pick first"." This is the *only* thing I'd like to change as well before filing a PR.

As I said I can *try* it on the weekend (in case I have sufficient time), however it might be cool to hear if @nbp or @NeQuissimus have anything to add.

**Comment by NeQuissimus** [comment]
As long as we document what is going on and why, I am fine either way, really.

**Comment by PierreR** [comment]
Whatever happens, it would be nice if it does ship with the 18.03 release.

**Comment by rycee** [comment]
@bendlas Hehe, I don't think I can be considered an original sponsor, especially since my initial statement about all this was literally "I'm not fond of this." :smiley:

For my part I don't have any strong opinion except that I insist on it being possible (in a reasonably easy way) to have a NixOS system that does not require a desktop or window manager configuration at the system level since I configure those through Home Manager (boiling down to `~/.xsession`). From my point of view @Ma27 addressed those concerns, which I appreciate. And although the test issues brought up by @aszlig seem concerning I can't tell what the best solution is.

To be honest, I've never explicitly used `services.xserver.desktopManager` and `services.xserver.windowManager` and have only a vague idea of what their `.default` options actually do. So I think it is for the great benefit of everybody that I respectfully decline from taking on maintainership.

**Comment by bendlas** [comment]
@rycee oh, I misremembered. Sorry.

> Whatever happens, it would be nice if it does ship with the 18.03 release.

That was pretty much my point. Additionally, I'd rather it not break any stable users.

Sorry if my response came off as rather strong, let's wait till monday, before deciding.

**Comment by Ma27** [comment]
see #37276, in the end my change was a mistake, sorry about that...

**Pull request merged**
