### PR TITLE
yuzu-{ea,mainline}: {2841,1092} -> {2901,1131}

### PR DESCRIPTION
**Pull request by sbruder**
This also changes the update script for EA to fetch the two latest
releases, filter for tags matching /^EA-[0-9]*/ and pick the latest one.
This is required because recently the auto-updater (tag: continuous) is
the latest release, which would have been picked by the update script.

It also updates the free icons patch, which is needed due to yuzu
changing how they track licenses of files to REUSE. The comment is
updated to reflect the workflow that is needed to create the patch,
because pineapple does not include files beginning with a dot in its
source.

Because new icons were added, the current version of the free icons
patch still has four CC-BY-ND 3.0 icons (cf.
https://github.com/yuzu-emu/yuzu/pull/8104#issuecomment-1214158492).

I’m not sure if we should wait until there is a patch available to replace all unfree icons or if we should merge this and accept the rebuilds it will cause for users.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by IvarWithoutBones** [comment]
> I’m not sure if we should wait until there is a patch available to replace all unfree icons or if we should merge this and accept the rebuilds it will cause for users.


I do think it'd be better to wait in this case, as I believe the author of the PR we're patching in is planning on converting to the icons to free ones. We've updated not too long ago anyways, as far as I know theres no major features added in these updates.

Adding cc-by-nd-30 licensed icons in that patch kind of defeats its point.

**Comment by IvarWithoutBones** [comment]
> The reason why I updated, is that (at least on my system) the current mainline in nixpkgs has unusually low performance, which is not the case with the EA version currently in nixpkgs or the current mainline. But that might very well be just an issue for me and I can just use a different version for the time being

Hmm, it might be worth checking if we can just update mainline to the latest version where the patch applies, if it's any better there.

**Comment by IvarWithoutBones** [comment]
I've also reported files starting with a dot being stripped to pineapple developers, hopefully we can get that fixed.

**Comment by Docteh** [comment]
I went with tweaked gnome-icons, we'll see how temporary it is ;) 
connected connected_notification disconnected

Bit late for this suggestion, but since the icons aren't directly used yet, could replace with something like the no texture texture from half life
image

I think the proper one is `#FF00FF` and `#000000`

**Review by IvarWithoutBones — APPROVED** [review]
Thanks for fixing the nonfree icons in the patch so quickly, and updating the PR swiftly as well :)

Looks good to me :+1: 

Result of `nixpkgs-review pr 186450` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>yuzu-ea</li>
    <li>yuzu-mainline</li>
  </ul>
</details>

**Pull request merged**
