### PR TITLE
tree-sitter: update grammars

### PR DESCRIPTION
**Pull request by jlesquembre**
###### Motivation for this change
Update tree-sitter grammars

Switch to nvim-treesitter/tree-sitter-lua for lua, since current lua grammar is broken for 0.19.5

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by ck3d — APPROVED** [review]

**Comment by teto** [comment]
any darwin user to say why it fails ?

**Comment by jlesquembre** [comment]
I think the darwin build was fixed in #125100
I rebased with latest master, and updated the grammars again, lets see if now works on darwin (I don't have a macos to test locally)

**Comment by jlesquembre** [comment]
darwin build fixed in current master :)

**Comment by teto** [comment]
thanks for the patience

**Comment by jlesquembre** [comment]
@teto sure, no worries, thanks for all your great work in nixpkgs and neovim :)

**Pull request merged**
