### PR TITLE
meson: 0.61.2 -> 0.62.2

### PR DESCRIPTION
**Pull request by Infinidoge**
###### Description of changes

This updates meson to the latest version, which was necessary for my upcoming PR to bump kmscon to the latest version. Several patches were removed due to being upstreamed.

HOWEVER: This definitely needs feedback, because running the nixpkgs review command below appears to fail, with the error message:
```
error: Function called without required argument "lzma" at /home/infinidoge/.cache/nixpkgs-review/rev-d55fcf6acf96287efc540014758f67fddbd4dc69/nixpkgs/pkgs/development/libraries/avro-c/default.nix:1, did you mean "lima", "czmq" or "emma"?
```
(Before that there was a very long list of packages)

I'm unsure what caused this, because the `avro-c/default.nix` mentions nothing about `meson`, but thought it worth noting here.

Due to the issue above, notifying maintainers: @jtojnar @AndersonTorres @brandonedens 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Infinidoge** [comment]
I think I may know the issue,
It might be possible that for some reason, this latest meson update conflicts with the `fortify` hardening, (kmscon and wayland-protocols, which both used meson, threw the same error about FORTIFY_SOURCE)

The issue there being that it seems like it is trying to compile with fortify without including the optimization level.

In both cases of kmscon and wayland-protocols, adding `hardeningDisable = [ "fortify" ];` resolves the issue, but doing that tree-wide for meson-built software seems unwise.

**Comment by NickCao** [comment]
`lzma` is an alias, replacing it with `xz` should fix the evaluation error.

**Comment by jtojnar** [comment]
This would need to go into staging and we already have https://github.com/NixOS/nixpkgs/pull/171069.

**Comment by Mindavi** [comment]
Please test the other PR and comment on any issues you see.

**Comment by Infinidoge** [comment]
Ah, it seems I didn't see that PR, will retarget accordingly.

**Pull request closed without merging**
