### PR TITLE
shattered-pixel-dungeon: 0.8.2d -> 0.9.0b

### PR DESCRIPTION
**Pull request by fgaz**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by roberth** [comment]
@GrahamcOfBorg build shattered-pixel-dungeon.passthru.tests

**Comment by fgaz** [comment]
Uh... looks like the 0.9.0 tag was deleted :-/ :-/ :-/

I'm sure I didn't mistype it because I still have a 0.9.0 build in my cache

**Comment by fgaz** [comment]
Updated to 0.9.0b

**Comment by fgaz** [comment]
Weird null pointer runtime error only on arm:

```
Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "main"
```

I wonder if it happens every time. Let's see

@GrahamcOfBorg build shattered-pixel-dungeon.passthru.tests

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 99885` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>shattered-pixel-dungeon</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Fails on darwin with

```
building

FAILURE: Build failed with an exception.

* What went wrong:
Could not open terminal for stdout: could not get termcap entry

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by fgaz** [comment]
@SuperSandro2000 could you try to rebuild on darwin?

**Comment by SuperSandro2000** [comment]
@fgaz please fix the eval error

```                                                                                                                                                     37|       # https://github.com/gradle/gradle/issues/4426                                                                                                                                    38|       ${optionalString stdenv.isDarwin "export TERM=dumb"}                                                                                                                                |         ^                                                                                                                                                                               39|       gradle --no-daemon desktop:release                                                                                                                                                                                                                                                                                                                                        undefined variable 'optionalString'
```

**Comment by fgaz** [comment]
Sorry, I forgot to eval before pushing. here we go.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 99885` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>shattered-pixel-dungeon</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Please fix it for darwin or mark it broken:

```
building

Welcome to Gradle 5.6.4!

Here are the highlights of this release:
 - Incremental Groovy compilation
 - Groovy compile avoidance
 - Test fixtures for Java projects
 - Manage plugin versions via settings script

For more details see https://docs.gradle.org/5.6.4/release-notes.html

To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.6.4/userguide/gradle_daemon.html.

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/5.6.4/userguide/gradle_daemon.html
Process command line: /nix/store/3z6qbniycq9pvx8wbls08y89y0zf44m8-zulu1.8.0_202-8.36.0.1/bin/java -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /nix/store/3pl1pfdffk5l3406pa7kzylm9m2s5fda-gradle-5.6.4/lib/gradle/lib/gradle-launcher-5.6.4.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 5.6.4
Please read the following process output to find out more:
-----------------------
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by fgaz** [comment]
Broken it is then

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 99885` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>shattered-pixel-dungeon</li>
</ul>
</details>

**Pull request merged**
