### PR TITLE
python: add python.withPackages function

### LINKED ISSUE #15801: Add python.withPackages function
In Haskell there is a `ghc.withPackages` function, that builds a ghc derivation that knows about specific packages. I suggest that we add a similar function to python, which could be used like this:

    with (import <nixpkgs> {}); python3.withPackages (ps: [ps.dbus ps.pygobject3 ...])

This has multiple benefits: first, it is easier than the `buildEnv` version (in my personal opinion. For example, in the buildEnv version, I have to remember that the attribute to override is called `extraLibs` and it also is not as obvious as a simple function IMO). The second advantage is that it's similar to the Haskell packaging, so users that use both Haskell and Python don't have to remember two ways to do the same thing.

### PR DESCRIPTION
**Pull request by bennofs**
I've tested this with all python versions in nixpkgs (except python 2.6, because I haven't found a package that builds with it), it works like this:

```
nix-build -E 'with (import <nixpkgs> {}); python35.withPackages (ps: [ps.dbus])' 
```

Then there is a `result/bin/python3` executable that knows about the `dbus` python package.

A problem with this implementation is that the following code won't work:

```
customPython = python3.override { .... };
wrapped = customPython.withPackages (ps: []) # here, ps will by python3Packages using python3, not customPython, to build packages.
```

Instead, you have to use this:

```
customPython = python3.override { ...; pythonPackages = customPythonPackages; };
customPythonPackages = python3Packages.override { python = customPython; self = customPythonPackages; };
wrapped = customPython.withPackages (ps: [...]);
```

Solving this requires either duplicating the code from `all-packages.nix` for `pythonXXPackages` or moving that code to the interpreters' default.nix file and then have something like:

```
python35Packages = python35.packages
```

in all-packages.nix. Since I'm not very involved in python packaging, I'm not sure what the best way to proceed is here. 

Fixes #15801

### CODE REVIEW

**Comment by domenkozar** [comment]
Needs documentation in nixpkgs manual, otherwise big :+1: for simplification.

**Comment by bjornfor** [comment]
@bennofs: Why is this branch pushed to the official nixpkgs repo? A mistake? (I don't think we should have a lot of wip-branches in the official repo.)

**Comment by bennofs** [comment]
@bjornfor Alright, I was not aware of such a policy. I'll push to a fork then next time.

**Comment by bennofs** [comment]
@domenkozar The documentation for `buildEnv` uses `import {}`, so I copied that for the `withPackages` documentation. Is that an error or is it a nix feature that I'm not aware of?

**Comment by domenkozar** [comment]
@bennofs ah, it's xml parsing error. See source file for truth (missing some CDATA)

**Comment by bennofs** [comment]
@domenkozar fixed those

**Comment by FRidh** [comment]
:+1: for the simplification. 

I see you now pass in the package sets to the interpreter. Is this going to have an impact on overriding attributes in the package set, or overriding the interpreter itself?

**Comment by knedlsepp** [comment]
I'm currently trying to make this work with overlays. But I can't get it to work.

**Comment by FRidh** [comment]
@knedlsepp please open a new issue.

**Comment by knedlsepp** [comment]
You're right, this belongs in a separate issue:
https://github.com/NixOS/nixpkgs/issues/26487

**Pull request merged**
