### PR TITLE
dockerTools: add environment variables inheritance

### PR DESCRIPTION
**Pull request by srghma**
###### Motivation for this change
Fixes https://github.com/NixOS/nixpkgs/issues/37172

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Tested with 
```sh
export NIX_PATH="nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-18.03.tar.gz"
nix-shell
google-chrome-stable $(nix-build -K nixos/tests/docker-tools.nix)/log.html
```

### CODE REVIEW

**Comment by BjornMelgaard** [comment]
@GrahamcOfBorg test docker-tools

**Comment by roberth** [comment]
Thank you for your pull request. I appreciate your effort to make `dockerTools` more docker-like.
I do have these two concerns:
 - This is a breaking change. Some users of `dockerTools` probably depend on the current behavior. This can be resolved either by adding an option to include the parent environment or by splitting the container functions into two 'layers': a low-level interface and one that simulates docker build. Perhaps such a split is similar to OCI image spec / the rest of Docker?
 - `ENV` is not the only docker command that works in an additive way. By moving away from the current low-level model toward a model that resembles the docker UI even more, we create expectations that need to be managed using documentation.

**Comment by roberth** [comment]
@moretea, @LnL7, should `dockerTools` simulate `docker build`, remain low-level or try to be both?

**Comment by LnL7** [comment]
I don't really have a strong opinion on this, but I think this makes sense since the structure resembles a dockerfile very closely.

@roberth While this is indeed a breaking change, I'm not sure if it's a problem in practice.

**Comment by roberth** [comment]
Well it does say `# WARNING: this API is unstable and may be subject to backwards-incompatible changes in the future.` near the top. I'm fine with it when it's mentioned in the [release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-1809.xml). (You can be the first! ;) )

**Comment by BjornMelgaard** [comment]
@roberth awesome, I vote to make this default behavior too

> Perhaps such a split is similar to OCI image spec / the rest of Docker

I'm too ignorant for this. I don't even know how they differ. 

> ENV is not the only docker command that works in an additive way.

good point, maybe I could add support for other config variables ([reference](https://github.com/opencontainers/image-spec/blob/master/config.md#properties)), like Volumes, Labels.
Doing this manually (like I do with env now) is hard, and I'm wondering, isn't there really no tool that could generate the new schema, that inherits some other schema. I have tried to find something in [open collective](https://github.com/opencontainers), but no luck.
I'll try again tomorrow

**Comment by mmahut** [comment]
What is the status of this pull request?

**Comment by srghma** [comment]
@mmahut , the inheritance of envs is working (was), the tests are implemented

I didn't find tool that is specialized for merging two configs and could merge also volumes, labels, etc. (now I think its not that hard to implement it)

but I've lost interest

**Comment by goosetherumfoodle** [comment]
@roberth how can we move this forward? Is it possible to merge just this functionality (or do it in a new PR if this is too out-of-date), without the additional merging of volumes and labels?

**Comment by roberth** [comment]
@goosetherumfoodle It has two conflicting files now so those have to be fixed at least. If it's easy someone can add them, but env only is also ok.

**Comment by srghma** [comment]
@roberth I have fixed conflicts and tests have passed, I think it can be merged

**Comment by srghma** [comment]
Oh, I see https://github.com/NixOS/nixpkgs/pull/87253 was merged and have the same functionality. 

There is no one to blame except me that this pr wasn't merged in due time.

**Pull request closed without merging**
