### PR TITLE
tplay: init at 0.3.1 (wip)

### PR DESCRIPTION
**Pull request by colemickens**
###### Description of changes

Draft:

1. This uses my fork with Cargo.lock added.
2. This doesn't build, `opencv` fails to build via cargo:

```
tplay>   === Detected OpenCV module header dir at: /nix/store/wyc32im5p1vl9qv4h6jhq1fx6g8hbzic-opencv-4.7.0/include/opencv4/opencv2
tplay>   === Found OpenCV version: 4.7.0 in headers located at: /nix/store/wyc32im5p1vl9qv4h6jhq1fx6g8hbzic-opencv-4.7.0/include/opencv4
tplay>   === Generating code in: /build/source/target/x86_64-unknown-linux-gnu/release/build/opencv-5ea55105c2eccf01/out
tplay>   === Placing generated bindings into: /build/source/target/x86_64-unknown-linux-gnu/release/build/opencv-5ea55105c2eccf01/out/opencv
tplay>   === Using OpenCV headers from: /nix/store/wyc32im5p1vl9qv4h6jhq1fx6g8hbzic-opencv-4.7.0/include/opencv4
tplay>   === Clang: clang version 11.1.0
tplay>   === Clang command line args: [
tplay>       "-isystem/nix/store/7jc6w98k05chdcs40pb9skflfkk8c50h-compiler-rt-libc-11.1.0-dev/include",
tplay>       "-isystem/nix/store/s4mlim0d9aigjcx9xgh5j25kra9q91mr-clang-11.1.0-dev/include",
tplay>       "-isystem/nix/store/xc1pa2l2pxychc7yirdm2jqwm7b35x75-glibc-2.37-8-dev/include",
tplay>       "-isystem/nix/store/wyc32im5p1vl9qv4h6jhq1fx6g8hbzic-opencv-4.7.0/include",
tplay>       "-isystem/nix/store/8b6iqs31p8kriw9c98p4v7qdx4fvm9j7-gcc-12.2.0/include/c++/12.2.0",
tplay>       "-isystem/nix/store/8b6iqs31p8kriw9c98p4v7qdx4fvm9j7-gcc-12.2.0/include/c++/12.2.0/x86_64-unknown-linux-gnu",
tplay>       "-isystem/nix/store/jyhyc4w89ra87qlss72hhynacb3xbdn3-clang-wrapper-11.1.0/resource-root/include",
tplay>       "-I/nix/store/wyc32im5p1vl9qv4h6jhq1fx6g8hbzic-opencv-4.7.0/include/opencv4",
tplay>       "-F/nix/store/wyc32im5p1vl9qv4h6jhq1fx6g8hbzic-opencv-4.7.0/include/opencv4",
tplay>       "-I/build/cargo-vendor-dir/opencv-0.80.0/src_cpp",
tplay>       "-F/build/cargo-vendor-dir/opencv-0.80.0/src_cpp",
tplay>       "-DOCVRS_PARSING_HEADERS",
tplay>       "-includeocvrs_ephemeral.hpp",
tplay>       "-std=c++14",
tplay>   ]
tplay>   === Building binding-generator binary:
tplay>   === error: failed to get `libc` as a dependency of package `opencv v0.80.0 (/build/cargo-vendor-dir/opencv-0.80.0)`
tplay>   ===
tplay>   === Caused by:
tplay>   ===   failed to load source for dependency `libc`
tplay>   ===
tplay>   === Caused by:
tplay>   ===   Unable to update registry `crates-io`
tplay>   ===
tplay>   === Caused by:
tplay>   ===   failed to update replaced source registry `crates-io`
tplay>   ===
tplay>   === Caused by:
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/cifxjpbjcbfaciaxjr61b5dh41a5mfnh-tplay-0.3.1.drv'.
```

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by colemickens** [comment]
Apologies, this should be a draft.

My change got merged, so I updated the source back to the main repo.

However, it still does not build.

**Comment by colemickens** [comment]
I'm getting a headache. I feel like *maybe* opencv-rust is being a pain... and I don't see any other derivations in nixpkgs that use `opencv` and `buildRustPackage` so I'm not sure where to get hints from.

**Comment by colemickens** [comment]
Just FYI, I did open this on `opencv-rust`: https://github.com/twistedfall/opencv-rust/issues/458

**Comment by colemickens** [comment]
I tried again. Still failing in clang/rust/opencv:

```
tplay>   cargo:rerun-if-changed=/build/tplay-0.4.5-vendor.tar.gz/opencv/src_cpp/bioinspired.hpp
tplay>   cargo:rerun-if-changed=/build/tplay-0.4.5-vendor.tar.gz/opencv/src_cpp/aruco.hpp
tplay>   cargo:rerun-if-changed=/build/tplay-0.4.5-vendor.tar.gz/opencv/src_cpp/ocvrs_common.hpp
tplay>   cargo:rerun-if-changed=/build/tplay-0.4.5-vendor.tar.gz/opencv/src_cpp/xfeatures2d.hpp
tplay>   cargo:rerun-if-changed=/build/tplay-0.4.5-vendor.tar.gz/opencv/src_cpp/gapi.hpp
tplay>   cargo:rerun-if-changed=/build/tplay-0.4.5-vendor.tar.gz/opencv/src_cpp/manual-core.cpp
tplay>   cargo:rerun-if-changed=/build/tplay-0.4.5-vendor.tar.gz/opencv/src_cpp/photo.hpp
tplay>   cargo:rerun-if-changed=/build/tplay-0.4.5-vendor.tar.gz/opencv/src_cpp/ccalib.hpp
tplay>   cargo:rerun-if-changed=/build/tplay-0.4.5-vendor.tar.gz/opencv/src_cpp/hdf.hpp
tplay>   cargo:rerun-if-changed=/build/tplay-0.4.5-vendor.tar.gz/opencv/src_cpp/sfm.hpp
tplay>   cargo:rerun-if-changed=/build/tplay-0.4.5-vendor.tar.gz/opencv/src_cpp/alphamat.hpp
tplay>   cargo:rerun-if-changed=/build/tplay-0.4.5-vendor.tar.gz/opencv/src_cpp/core.hpp
tplay>   cargo:rerun-if-changed=Cargo.toml
tplay>   --- stderr
tplay>   === Crate version: Some("0.84.5")
tplay>   === Environment configuration:
tplay>   ===   OPENCV_PACKAGE_NAME = None
tplay>   ===   OPENCV_PKGCONFIG_NAME = None
tplay>   ===   OPENCV_CMAKE_NAME = None
tplay>   ===   OPENCV_CMAKE_BIN = None
tplay>   ===   OPENCV_VCPKG_NAME = None
tplay>   ===   OPENCV_LINK_LIBS = None
tplay>   ===   OPENCV_LINK_PATHS = None
tplay>   ===   OPENCV_INCLUDE_PATHS = None
tplay>   ===   OPENCV_DISABLE_PROBES = None
tplay>   ===   OPENCV_MSVC_CRT = None
tplay>   ===   CMAKE_PREFIX_PATH = None
tplay>   ===   OpenCV_DIR = None
tplay>   ===   PKG_CONFIG_PATH = Some("/nix/store/9lhfjj5x77m9s1j15jr9fcn9lpfwi9fl-alsa-lib-1.2.9-dev/lib/pkgconfig:/nix/store/cqszmr2pxzkdsid9iza57yfrwlbmn953-ffmpeg-4.4.4-dev/lib/pkgconfig:/nix/
tplay>   ===   VCPKG_ROOT = None
tplay>   ===   VCPKGRS_DYNAMIC = None
tplay>   ===   VCPKGRS_TRIPLET = None
tplay>   ===   OCVRS_DOCS_GENERATE_DIR = None
tplay>   ===   DOCS_RS = None
tplay>   ===   PATH = Some("/nix/store/5j3w65zsmry6fch4s4k3p64j5clzbxvl-cargo-1.72.0/bin:/nix/store/3x1i28ayi70f0jkg71bwy95q95ghy181-cargo-auditable-0.6.1/bin:/nix/store/g0afhfibkfzfmqy7c880ld9axf
tplay>   === Enabled features:
tplay>   ===   CLANG_RUNTIME
tplay>   ===   IMGPROC
tplay>   ===   VIDEOIO
tplay>   === Detected probe priority based on environment vars: pkg_config: true, cmake: false, vcpkg: false
tplay>   === Probing the OpenCV library in the following order: environment, pkg_config, cmake, vcpkg_cmake, vcpkg
tplay>   === Can't probe using: environment, continuing with other methods because: Some environment variables are missing
tplay>   === Probing OpenCV library using pkg_config
tplay>   === Successfully probed using: pkg_config
tplay>   === OpenCV library configuration: Library {
tplay>       include_paths: [
tplay>           "/nix/store/24x5nk4ydxfnqmfvpl7kr0cyi5man261-opencv-4.7.0/include/opencv4",
tplay>       ],
tplay>       version: Version {
tplay>           major: 4,
tplay>           minor: 7,
tplay>           patch: 0,
tplay>       },
tplay>       cargo_metadata: [
tplay>           "cargo:rustc-link-search=/nix/store/24x5nk4ydxfnqmfvpl7kr0cyi5man261-opencv-4.7.0/lib",
tplay>           "cargo:rustc-link-lib=opencv_gapi",
tplay>           "cargo:rustc-link-lib=opencv_stitching",
tplay>           "cargo:rustc-link-lib=opencv_alphamat",
tplay>           "cargo:rustc-link-lib=opencv_aruco",
tplay>           "cargo:rustc-link-lib=opencv_barcode",
tplay>           "cargo:rustc-link-lib=opencv_bgsegm",
tplay>           "cargo:rustc-link-lib=opencv_bioinspired",
tplay>           "cargo:rustc-link-lib=opencv_ccalib",
tplay>           "cargo:rustc-link-lib=opencv_dnn_objdetect",
tplay>           "cargo:rustc-link-lib=opencv_dnn_superres",
tplay>           "cargo:rustc-link-lib=opencv_dpm",
tplay>           "cargo:rustc-link-lib=opencv_face",
tplay>           "cargo:rustc-link-lib=opencv_fuzzy",
tplay>           "cargo:rustc-link-lib=opencv_hdf",
tplay>           "cargo:rustc-link-lib=opencv_hfs",
tplay>           "cargo:rustc-link-lib=opencv_img_hash",
tplay>           "cargo:rustc-link-lib=opencv_intensity_transform",
tplay>           "cargo:rustc-link-lib=opencv_line_descriptor",
tplay>           "cargo:rustc-link-lib=opencv_mcc",
tplay>           "cargo:rustc-link-lib=opencv_quality",
tplay>           "cargo:rustc-link-lib=opencv_rapid",
tplay>           "cargo:rustc-link-lib=opencv_reg",
tplay>           "cargo:rustc-link-lib=opencv_rgbd",
tplay>           "cargo:rustc-link-lib=opencv_saliency",
tplay>           "cargo:rustc-link-lib=opencv_stereo",
tplay>           "cargo:rustc-link-lib=opencv_structured_light",
tplay>           "cargo:rustc-link-lib=opencv_phase_unwrapping",
tplay>           "cargo:rustc-link-lib=opencv_superres",
tplay>           "cargo:rustc-link-lib=opencv_optflow",
tplay>           "cargo:rustc-link-lib=opencv_surface_matching",
tplay>           "cargo:rustc-link-lib=opencv_tracking",
tplay>           "cargo:rustc-link-lib=opencv_highgui",
tplay>           "cargo:rustc-link-lib=opencv_datasets",
tplay>           "cargo:rustc-link-lib=opencv_text",
tplay>           "cargo:rustc-link-lib=opencv_plot",
tplay>           "cargo:rustc-link-lib=opencv_videostab",
tplay>           "cargo:rustc-link-lib=opencv_videoio",
tplay>           "cargo:rustc-link-lib=opencv_wechat_qrcode",
tplay>           "cargo:rustc-link-lib=opencv_xfeatures2d",
tplay>           "cargo:rustc-link-lib=opencv_shape",
tplay>           "cargo:rustc-link-lib=opencv_ml",
tplay>           "cargo:rustc-link-lib=opencv_ximgproc",
tplay>           "cargo:rustc-link-lib=opencv_video",
tplay>           "cargo:rustc-link-lib=opencv_xobjdetect",
tplay>           "cargo:rustc-link-lib=opencv_objdetect",
tplay>           "cargo:rustc-link-lib=opencv_calib3d",
tplay>           "cargo:rustc-link-lib=opencv_imgcodecs",
tplay>           "cargo:rustc-link-lib=opencv_features2d",
tplay>           "cargo:rustc-link-lib=opencv_dnn",
tplay>           "cargo:rustc-link-lib=opencv_flann",
tplay>           "cargo:rustc-link-lib=opencv_xphoto",
tplay>           "cargo:rustc-link-lib=opencv_photo",
tplay>           "cargo:rustc-link-lib=opencv_imgproc",
tplay>           "cargo:rustc-link-lib=opencv_core",
tplay>       ],
tplay>   }
tplay>   === Detected OpenCV module header dir at: /nix/store/24x5nk4ydxfnqmfvpl7kr0cyi5man261-opencv-4.7.0/include/opencv4/opencv2
tplay>   === Found OpenCV version: 4.7.0 in headers located at: /nix/store/24x5nk4ydxfnqmfvpl7kr0cyi5man261-opencv-4.7.0/include/opencv4
tplay>   === Generating code in: /build/source/target/x86_64-unknown-linux-gnu/release/build/opencv-cfe6452cca9f18e2/out
tplay>   === Placing generated bindings into: /build/source/target/x86_64-unknown-linux-gnu/release/build/opencv-cfe6452cca9f18e2/out/opencv
tplay>   === Using OpenCV headers from: /nix/store/24x5nk4ydxfnqmfvpl7kr0cyi5man261-opencv-4.7.0/include/opencv4
tplay>   === Clang: clang version 13.0.1
tplay>   === Clang command line args: [
tplay>       "-isystem/nix/store/gx7f5fyrzxjcgg0gm098q47yjn5gp5l0-compiler-rt-libc-13.0.1-dev/include",
tplay>       "-isystem/nix/store/9lhfjj5x77m9s1j15jr9fcn9lpfwi9fl-alsa-lib-1.2.9-dev/include",
tplay>       "-isystem/nix/store/cqszmr2pxzkdsid9iza57yfrwlbmn953-ffmpeg-4.4.4-dev/include",
tplay>       "-isystem/nix/store/4lap45ifj50lp980id60fnbvs81yj9lr-glibc-2.37-8-dev/include",
tplay>       "-isystem/nix/store/6399jqz3i3k99hq2xpybz28ry4six7jb-clang-13.0.1-dev/include",
tplay>       "-isystem/nix/store/9mann52mrpais3hma17v3c4rw13qam7g-libcxx-13.0.1-dev/include",
tplay>       "-isystem/nix/store/24x5nk4ydxfnqmfvpl7kr0cyi5man261-opencv-4.7.0/include",
tplay>       "-isystem/nix/store/15c5j27bc6g6ydfkicazwgf61pkxjh9m-openssl-3.0.10-dev/include",
tplay>       "-isystem/nix/store/n8dryz4xf7ln028j37zapgzg4j47p743-gcc-12.3.0/include/c++/12.3.0",
tplay>       "-isystem/nix/store/n8dryz4xf7ln028j37zapgzg4j47p743-gcc-12.3.0/include/c++/12.3.0/x86_64-unknown-linux-gnu",
tplay>       "-isystem/nix/store/b4y1vzkybpx8ggfrdrn47r21dh44kj0j-clang-wrapper-13.0.1/resource-root/include",
tplay>       "-I/nix/store/24x5nk4ydxfnqmfvpl7kr0cyi5man261-opencv-4.7.0/include/opencv4",
tplay>       "-F/nix/store/24x5nk4ydxfnqmfvpl7kr0cyi5man261-opencv-4.7.0/include/opencv4",
tplay>       "-I/build/tplay-0.4.5-vendor.tar.gz/opencv/src_cpp",
tplay>       "-F/build/tplay-0.4.5-vendor.tar.gz/opencv/src_cpp",
tplay>       "-DOCVRS_PARSING_HEADERS",
tplay>       "-includeocvrs_common.hpp",
tplay>       "-std=c++14",
tplay>   ]
tplay>   === Available jobs from the environment created jobserver is: 0 or there is an error reading that value
tplay>   === Creating a new job server with num_jobs: 16
tplay>   === Generating 3 modules
tplay>   === Running: "/build/source/target/release/build/opencv-a0c308cc8cb1d8dc/build-script-build" "/nix/store/24x5nk4ydxfnqmfvpl7kr0cyi5man261-opencv-4.7.0/include/opencv4" "/build/tplay-0.4.5-vendor.tar.gz/opencv/src_cpp" "/build/source/target/x86_64-unknown-linux-gnu/release/build/opencv-cfe6452cca9f18e2/out" "core" ""
tplay>   === Running: "/build/source/target/release/build/opencv-a0c308cc8cb1d8dc/build-script-build" "/nix/store/24x5nk4ydxfnqmfvpl7kr0cyi5man261-opencv-4.7.0/include/opencv4" "/build/tplay-0.4.5-vendor.tar.gz/opencv/src_cpp" "/build/source/target/x86_64-unknown-linux-gnu/release/build/opencv-cfe6452cca9f18e2/out" "imgproc" ""
tplay>   === Running: "/build/source/target/release/build/opencv-a0c308cc8cb1d8dc/build-script-build" "/nix/store/24x5nk4ydxfnqmfvpl7kr0cyi5man261-opencv-4.7.0/include/opencv4" "/build/tplay-0.4.5-vendor.tar.gz/opencv/src_cpp" "/build/source/target/x86_64-unknown-linux-gnu/release/build/opencv-cfe6452cca9f18e2/out" "videoio" ""
tplay>   === WARNING: 1 diagnostic messages
tplay>   ===    /nix/store/n8dryz4xf7ln028j37zapgzg4j47p743-gcc-12.3.0/include/c++/12.3.0/cstdlib:75:15: fatal error: 'stdlib.h' file not found
tplay>   thread 'main' panicked at '=== Errors during header parsing', /build/tplay-0.4.5-vendor.tar.gz/opencv-binding-generator/src/generator.rs:396:17
tplay>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
tplay>   === WARNING: 1 diagnostic messages
tplay>   ===    /nix/store/n8dryz4xf7ln028j37zapgzg4j47p743-gcc-12.3.0/include/c++/12.3.0/cstdlib:75:15: fatal error: 'stdlib.h' file not found
tplay>   thread 'main' panicked at '=== Errors during header parsing', /build/tplay-0.4.5-vendor.tar.gz/opencv-binding-generator/src/generator.rs:396:17
tplay>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
tplay>   === WARNING: 1 diagnostic messages
tplay>   ===    /nix/store/n8dryz4xf7ln028j37zapgzg4j47p743-gcc-12.3.0/include/c++/12.3.0/cstdlib:75:15: fatal error: 'stdlib.h' file not found
tplay>   thread 'main' panicked at '=== Errors during header parsing', /build/tplay-0.4.5-vendor.tar.gz/opencv-binding-generator/src/generator.rs:396:17
tplay>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
tplay>   thread '<unnamed>' panicked at 'Failed to run the bindings generator for module: videoio', /build/tplay-0.4.5-vendor.tar.gz/opencv/build/generator.rs:108:25
tplay>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
tplay>   thread '<unnamed>' panicked at 'Failed to run the bindings generator for module: core', /build/tplay-0.4.5-vendor.tar.gz/opencv/build/generator.rs:108:25
tplay>   thread 'main' panicked at 'Generator process panicked: Any { .. }', /build/tplay-0.4.5-vendor.tar.gz/opencv/build/generator.rs:117:32
```

**Comment by colemickens** [comment]
Oh hey, I pulled this PR to try again and noticed there was another tplay in the tree.

Looks like @Demine0 got it in https://github.com/NixOS/nixpkgs/pull/266300

Nice, thanks. Closing!

**Comment by Demine0** [comment]
> Oh hey, I pulled this PR to try again and noticed there was another tplay in the tree.
> 
> 
> 
> Looks like @Demine0 got it in https://github.com/NixOS/nixpkgs/pull/266300
> 
> 
> 
> Nice, thanks. Closing!

Yep, but, now I cant follow this package, I dont have machine with NixOS now

**Comment by colemickens** [comment]
You should be able to use it on non-nixos systems! Nix is great even not on NixOS. But that's okay too, I'll try my hand at bumping it up to the new 0.5.0 real quick.

**Comment by Demine0** [comment]
> You should be able to use it on non-nixos systems! Nix is great even not on NixOS. But that's okay too, I'll try my hand at bumping it up to the new 0.5.0 real quick.

I have only a MacOS at this moment, maybe I wont go back on linux anymore

**Comment by colemickens** [comment]
Nix works on Macs too ;)

**Comment by Demine0** [comment]
> Nix works on Macs too ;)

But tplay... is doesn't

**Comment by colemickens** [comment]
whomp whomp, okay, well thank you for your service either way. :vulcan_salute: . let us know when you're back :wink:

**Pull request closed without merging**
