### PR TITLE
jazzy: 0.9.0 -> 0.9.5

### PR DESCRIPTION
**Pull request by lilyball**
###### Motivation for this change
Updates the `jazzy` package.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

/cc @peterromfeldhk

I had to update the `update` script. I did not make it match what we settled on with `cocoapods` because asking `bundler` to build and install all the packages was actually problematic (not only is it completely unnecessary but I ran into a problem with it depending on `sqlite`). So instead we just ask `bundler` to generate the lockfile and let `bundix` do its work and it works just fine. Next time `cocoapods` is updated we should probably update its `update` script again to match.

### CODE REVIEW

**Comment by lilyball** [comment]
What does it take to get package updates processed?

**Comment by lilyball** [comment]
I've updated the commit to add myself as a maintainer of the package as well, as @peterromfeldhk does not seem to be particularly responsive.

**Comment by ryantm** [comment]
@GrahamcOfBorg build jazzy

**Comment by peterromfeldhk** [comment]
its not like i can merge it :/ why do i need to respond if there is nothing
i can do?

**Comment by lilyball** [comment]
@peterromfeldhk As the listed maintainer you should at least approve (or reject) the change.

**Comment by ryantm** [comment]
@peterromfeldhk You could use https://github.com/Mic92/nix-review `nix-review pr 56399` to build and test this commit and see if it behaves the way you expect it to.

**Comment by peterromfeldhk** [comment]
hmm ok, i looked at it (it was fine). there was no approve button, but i
can add approve comment if that makes it easier.

**Comment by ryantm** [comment]
Yes, a approval comment from the maintainer is very helpful. Once [RFC 39](https://github.com/NixOS/rfcs/pull/39/files?short_path=68b0938#diff-68b0938e7e9a24cb0cc24ac6a70950b9) is implemented it will be possible for you to submit a approval review of PRs in GitHub.

**Pull request merged**
