### PR TITLE
sage: import sphinx and sympy update patches, update pari 2.13 patch

### PR DESCRIPTION
**Pull request by collares**
###### Motivation for this change

Staging-next was merged a few days ago (#127151), and the SymPy and Sphinx updates broke Sage. I also took the opportunity to use `fetchSageDiff` for the Pari 2.13 update patch, now that it has been merged upstream.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 7c6f434c** [comment]
OfBorg failure seems real:
```
sage -t --long --random-seed=0 /nix/store/74hcv2wdhfr7qy0qv2dyvib6680qnl16-sage-src-9.3/src/sage/misc/trace.py
**********************************************************************
File "/nix/store/74hcv2wdhfr7qy0qv2dyvib6680qnl16-sage-src-9.3/src/sage/misc/trace.py", line 66, in sage.misc.trace.trace
Failed example:
    print(s.before[s.before.find(b'--'):].decode())
Expected:
    --...
    ...ipdb> c
    ...2 * 5...
Got:
    --Call--
    > <CSI-0;32m>/nix/store/0ipf5dj3dhbb00
**********************************************************************
1 item had failures:
   1 of  11 in sage.misc.trace.trace
    [10 tests, 1 failure, 6.00 s]
```

**Comment by collares** [comment]
This `trace.py` error is a very old intermittent bug: https://groups.google.com/g/sage-release/search?q=%22trace.py%22. Presumably this was fixed in https://trac.sagemath.org/ticket/21258 but the bug just got rarer and they weren't sure that disabling garbage collection helped. Let's try this again.

@ofborg build sage

**Comment by 7c6f434c** [comment]
@ofborg build sage

Does it help to put it in front, I wonder…

**Comment by collares** [comment]
Result of `nixpkgs-review pr 128831` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>sage</li>
    <li>sageWithDoc</li>
  </ul>
</details>

**Comment by 7c6f434c** [comment]
There is a drawback in fetchSageDiff that the expression is quite annoying to verify — I know _you_ check carefully which upstream commits we need, but if some new person submits a patch, there is a bit of manual work to check the diff. (Then there is this entire «GitHub commingles commits from forks»)

**Comment by collares** [comment]
Thanks for merging! 

I try to always link to the corresponding trac issue and ensure that `fetchSageDiff` is always called with a commit from that issue (sometimes I forget and timokau keeps me honest :)). But if you pick the wrong base for the diff, then you might be pulling in a whole Sage upgrade as well. I wonder if we could have a basic check to ensure the diff does not include a version string change, at least.

By the way, I don't remember having this problem (rebases mid-ticket messing up the diffs) before. Maybe something changed upstream and patches are no longer being rebased before getting pushed to the `develop` branch?

**Comment by 7c6f434c** [comment]
>By the way, I don't remember having this problem (rebases mid-ticket messing up the diffs) before. Maybe something changed upstream and patches are no longer being rebased before getting pushed to the `develop` branch?

Oh well, I somewhat like having an idea what to do without the assumption «everyone knows the development habits of upstream very very precisely and acts according to this knowledge»… I wonder if making upstream issue reference a mandatory but ignored string parameter is a good idea… probably not.

**Pull request merged**
