### PR TITLE
rustc: 1.43.0 -> 1.44.1

### PR DESCRIPTION
**Pull request by alyssais**
I wasn’t able to build thunderbird and Firefox for unrelated reasons (unless it’s gone away on a more recent staging I’ll open a PR for that shortly), but with those issues addressed I’ve successfully built Firefox and Thunderbird with Rust 1.44, so they shouldn’t block the rust update.

**Could a Darwin user please `nix-build -A fd` for me please?**

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by lblasc — APPROVED** [review]

**Review by LnL7 — COMMENTED** [review]
Too many other things failed on staging so can't test it properly as is.

**Comment by Mic92** [comment]
cannot test any cargo-based build on aarch64 because one git test fail on our community aarch64 builder. rustc builds itself.

**Comment by FRidh** [comment]
Reminder for testing this PR.

**Review by Ma27 — APPROVED** [review]
Tested this while investigating #89481, LGTM :+1:

**Comment by Mic92** [comment]
I will give aarch64 another try.

**Comment by Mic92** [comment]
aarch64 builds now.

**Comment by L-as** [comment]
This should be updated to 1.44.1 IMO. Apparently 1.44.0 had several regressions: https://github.com/rust-lang/rust/blob/stable/RELEASES.md#version-1441-2020-06-18

**Comment by alyssais** [comment]
> This should be updated to 1.44.1 IMO. Apparently 1.44.0 had several
> regressions:
> https://github.com/rust-lang/rust/blob/stable/RELEASES.md#version-1441-2020-06-18

Done.

Thunderbird and Firefox are now broken due to #85189, but I think it's
reasonable to assume that if they built with 1.44.0 they'll build with
1.44.1.

**Pull request merged**
