### PR TITLE
dfhack: 50.13-r1.1 -> 50.13-r3 (+ Darwin eval fix)

### PR DESCRIPTION
**Pull request by numinit**
## Description of changes

Updates dfhack and fixes eval on Darwin to correct #305141.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by fmoda3** [comment]
Here is the error I get on latest nixpkgs unstable (slightly different from what it was when I reported the eval issue)
```
❯ nix build "nixpkgs/nixpkgs-unstable#dwarf-fortress" --impure
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'dwarf-fortress-50.13'
         whose name attribute is located at /nix/store/jlj7imlwrqyld3jgy01v7ljll6dgxvj1-source/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'dfInit' of derivation 'dwarf-fortress-50.13'

         at /nix/store/jlj7imlwrqyld3jgy01v7ljll6dgxvj1-source/pkgs/games/dwarf-fortress/wrapper/default.nix:152:3:

          151|
          152|   dfInit = substituteAll {
             |   ^
          153|     name = "dwarf-fortress-init";

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: Unsupported dfPlatform: osx
```

Here is the error I get on this branch
```
❯ nix build "github:numinit/nixpkgs?ref=dwarf-fortress-darwin#dwarf-fortress" --impure
error: builder for '/nix/store/l9q9qwhlpa9kcba1csn7vrvr81j3l5am-dwarf-fortress-0.47.05.drv' failed with exit code 1;
       last 10 log lines:
       > unpacking source archive /nix/store/b4qyxln23kl3z19p968iiahvz9d1jg1i-df_47_05_osx.tar.bz2
       > source root is .
       > setting SOURCE_DATE_EPOCH to timestamp 1611875074 of file ./df_osx/libs/SDL_ttf.framework/Versions/A/SDL_ttf
       > Running phase: patchPhase
       > Running phase: configurePhase
       > no configure script, doing nothing
       > Running phase: buildPhase
       > no Makefile or custom buildPhase, doing nothing
       > Running phase: installPhase
       > chmod: cannot access '/nix/store/6a0kim3gxcq0k4sqirl8b9yydmzs6d5c-dwarf-fortress-0.47.05/dwarfort.exe': No such file or directory
       For full logs, run 'nix log /nix/store/l9q9qwhlpa9kcba1csn7vrvr81j3l5am-dwarf-fortress-0.47.05.drv'.
error: 1 dependencies of derivation '/nix/store/1j3g8p1x6cd4pmamsl2acs96j4xhrpxj-dwarf-fortress-base-env-0.47.05.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fy9h60ga26acl3wmkks5kmf0skgfsfr3-dwarf-fortress-env-0.47.05.drv' failed to build
error: 1 dependencies of derivation '/nix/store/yyykdw7a06lycs80pjhv86y3xxybszvk-dwarf-fortress-init.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kzins3g9dfdkm73hxakfrjqfnx2i8zld-dwarf-fortress-0.47.05.drv' failed to build
```
System info
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 23.5.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.2`
 - channels(fmoda3): `""`
 - channels(root): `"nixpkgs-21.11pre329302.d14ae62671f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by numinit** [comment]
@fmoda3 Thanks, give it a shot now. If it still doesn't work, I'll have to get my Darwin VM set up again.

**Comment by fmoda3** [comment]
@numinit Ok, this time it built, and I attempted to run it and got this.  Not sure if its a mistake on my end though
```
❯ nix run "github:numinit/nixpkgs?ref=dwarf-fortress-darwin#dwarf-fortress" --impure
/------------------------------------------------------------------------------\
| Hello from the nixpkgs Dwarf Fortress wrapper!                               |
|                                                                              |
| Using the following Dwarf Fortress overlay directory as NIXPKGS_DF_HOME:     |
| /Users/fmoda3/.local/share/df_linux                                          |
|                                                                              |
| If you make any changes in it, don't forget to clean it when updating the    |
| game version! We detect changes if data directories are symbolic links.      |
|                                                                              |
| Even though we do our best on our own, this script may miss some. Submit a   |
| pull request if there are any that become a problem.                         |
|                                                                              |
| We started with the following nixpkgs launch options as NIXPKGS_DF_OPTS:     |
| debug=0,fmod=0                                                               |
|                                                                              |
| If you want to try fmod over SDL_mixer, set NIXPKGS_DF_OPTS=fmod.            |
\------------------------------------------------------------------------------/
/nix/store/8b6b938yk6k0ismh7c41c4nz11wsxrrd-dwarf-fortress-init: line 129: /Users/fmoda3/.local/share/df_linux/dwarfort.exe: No such file or directory
```

**Comment by numinit** [comment]
Ah, looks like an issue with the wrapper being hardcoded to df_linux now.

**Comment by fmoda3** [comment]
Got past that error, and have a new one:
```
❯ nix run "github:numinit/nixpkgs?ref=dwarf-fortress-darwin#dwarf-fortress" --impure
/------------------------------------------------------------------------------\
| Hello from the nixpkgs Dwarf Fortress wrapper!                               |
|                                                                              |
| Using the following Dwarf Fortress overlay directory as NIXPKGS_DF_HOME:     |
| /Users/fmoda3/.local/share/df_osx                                            |
|                                                                              |
| If you make any changes in it, don't forget to clean it when updating the    |
| game version! We detect changes if data directories are symbolic links.      |
|                                                                              |
| Even though we do our best on our own, this script may miss some. Submit a   |
| pull request if there are any that become a problem.                         |
|                                                                              |
| We started with the following nixpkgs launch options as NIXPKGS_DF_OPTS:     |
| debug=0,fmod=0                                                               |
|                                                                              |
| If you want to try fmod over SDL_mixer, set NIXPKGS_DF_OPTS=fmod.            |
\------------------------------------------------------------------------------/
dyld[1281]: Library not loaded: @rpath/SDL.framework/Versions/A/SDL
  Referenced from: <942EED2E-C3DF-8941-0CFC-428242CBF77A> /nix/store/88rbdr0lmbdlhbs0x2xmhb4wrqclafni-dwarf-fortress-0.47.05/dwarfort.exe
  Reason: tried: '/nix/store/wv61m8x44nhjrswj91awyxcr8ha2bh4z-dwarf-fortress-env-0.47.05/libs/SDL.framework/Versions/A/SDL' (no such file), '/Library/Frameworks/SDL.framework/Versions/A/SDL' (no such file), '/System/Library/Frameworks/SDL.framework/Versions/A/SDL' (no such file, not in dyld cache)
zsh: abort      nix run "github:numinit/nixpkgs?ref=dwarf-fortress-darwin#dwarf-fortress"
```

**Comment by numinit** [comment]
I think we were missing a few libraries. Thanks for the check.

**Comment by fmoda3** [comment]
Hmm, still getting the same error:
```console
❯ nix run "github:numinit/nixpkgs?ref=dwarf-fortress-darwin#dwarf-fortress" --impure
/------------------------------------------------------------------------------\
| Hello from the nixpkgs Dwarf Fortress wrapper!                               |
|                                                                              |
| Using the following Dwarf Fortress overlay directory as NIXPKGS_DF_HOME:     |
| /Users/fmoda3/.local/share/df_osx                                            |
|                                                                              |
| If you make any changes in it, don't forget to clean it when updating the    |
| game version! We detect changes if data directories are symbolic links.      |
|                                                                              |
| Even though we do our best on our own, this script may miss some. Submit a   |
| pull request if there are any that become a problem.                         |
|                                                                              |
| We started with the following nixpkgs launch options as NIXPKGS_DF_OPTS:     |
| debug=0,fmod=0                                                               |
|                                                                              |
| If you want to try fmod over SDL_mixer, set NIXPKGS_DF_OPTS=fmod.            |
\------------------------------------------------------------------------------/
dyld[62231]: Library not loaded: @rpath/SDL.framework/Versions/A/SDL
  Referenced from: <942EED2E-C3DF-8941-0CFC-428242CBF77A> /nix/store/78ffzkjdagq1a27zknq7vc32mf9krlyd-dwarf-fortress-0.47.05/dwarfort.exe
  Reason: tried: '/nix/store/s9qagnkilsb7kys3rh1pcb1s3znjw0vj-dwarf-fortress-env-0.47.05/libs/SDL.framework/Versions/A/SDL' (no such file), '/Library/Frameworks/SDL.framework/Versions/A/SDL' (no such file), '/System/Library/Frameworks/SDL.framework/Versions/A/SDL' (no such file, not in dyld cache)
zsh: abort      nix run "github:numinit/nixpkgs?ref=dwarf-fortress-darwin#dwarf-fortress"
```
Tried to do a little digging to see why it might not be there, so first verified the error:
```console
❯ ls -l /nix/store/s9qagnkilsb7kys3rh1pcb1s3znjw0vj-dwarf-fortress-env-0.47.05/libs/SDL.framework/Versions/A/SDL
ls: /nix/store/s9qagnkilsb7kys3rh1pcb1s3znjw0vj-dwarf-fortress-env-0.47.05/libs/SDL.framework/Versions/A/SDL: No such file or directory
```
Indeed the file isn't there.  Had to go up a few levels to this:
```console
❯ ls -l /nix/store/s9qagnkilsb7kys3rh1pcb1s3znjw0vj-dwarf-fortress-env-0.47.05/libs
lrwxr-xr-x  1 root  wheel    80B Dec 31  1969 /nix/store/s9qagnkilsb7kys3rh1pcb1s3znjw0vj-dwarf-fortress-env-0.47.05/libs -> /nix/store/7y83hy9fzqaaaiapbry7kff08nwq2ka3-dwarf-fortress-base-env-0.47.05/libs
```
Following more symlinks
```console
❯ ls -l /nix/store/7y83hy9fzqaaaiapbry7kff08nwq2ka3-dwarf-fortress-base-env-0.47.05/libs
lrwxr-xr-x  1 root  wheel    71B Dec 31  1969 /nix/store/7y83hy9fzqaaaiapbry7kff08nwq2ka3-dwarf-fortress-base-env-0.47.05/libs -> /nix/store/78ffzkjdagq1a27zknq7vc32mf9krlyd-dwarf-fortress-0.47.05/libs
```
```console
❯ ls -l /nix/store/78ffzkjdagq1a27zknq7vc32mf9krlyd-dwarf-fortress-0.47.05/libs
total 0
lrwxr-xr-x  1 root  wheel    87B Dec 31  1969 SDL.framework -> /nix/store/m3ah9qn9bcf8h0zfzky1y9dp5p285zvx-SDL-1.2.15/Library/Frameworks/SDL.framework
lrwxr-xr-x  1 root  wheel    99B Dec 31  1969 SDL_image.framework -> /nix/store/pn23wj7jnjd97bfkryvkppf4cp7dmsxa-SDL_image-1.2.12/Library/Frameworks/SDL_image.framework
lrwxr-xr-x  1 root  wheel    95B Dec 31  1969 SDL_ttf.framework -> /nix/store/pjddcq6zxlnbhsxfalpg7mhrdmqvkyqs-SDL_ttf-2.0.11/Library/Frameworks/SDL_ttf.framework
lrwxr-xr-x  1 root  wheel    76B Dec 31  1969 libfmodex.dylib -> /nix/store/yk7fdmd85sh4c5fclcjgyjmsh1przvb5-fmod-4.44.64/lib/libfmodex.dylib
lrwxr-xr-x  1 root  wheel    79B Dec 31  1969 libgcc_s.1.dylib -> /nix/store/nrg2s6ksq3zy9sm0x28gf7yi7s3hbxfn-gcc-13.2.0-lib/lib/libgcc_s.1.dylib
lrwxr-xr-x  1 root  wheel    76B Dec 31  1969 libncurses.dylib -> /nix/store/j2l19sql3mc73fdmazzv8nw0jvq3hbdq-ncurses-6.4/lib/libncurses.dylib
lrwxr-xr-x  1 root  wheel    80B Dec 31  1969 libstdc++.6.dylib -> /nix/store/nrg2s6ksq3zy9sm0x28gf7yi7s3hbxfn-gcc-13.2.0-lib/lib/libstdc++.6.dylib
```
Aha, found where `SDL.framework` is supposed to be. But...
```console
❯ ls -l /nix/store/m3ah9qn9bcf8h0zfzky1y9dp5p285zvx-SDL-1.2.15/Library/Frameworks/SDL.framework
ls: /nix/store/m3ah9qn9bcf8h0zfzky1y9dp5p285zvx-SDL-1.2.15/Library/Frameworks/SDL.framework: No such file or directory
```
Going up a few levels:
```console
❯ ls -l /nix/store/m3ah9qn9bcf8h0zfzky1y9dp5p285zvx-SDL-1.2.15
total 0
dr-xr-xr-x  7 root  nixbld   224B Dec 31  1969 lib
```
and then
```console
❯ ls -l /nix/store/m3ah9qn9bcf8h0zfzky1y9dp5p285zvx-SDL-1.2.15/lib
total 1016
-r-xr-xr-x  1 root  nixbld   484K Dec 31  1969 libSDL-1.2.0.dylib
lrwxr-xr-x  1 root  nixbld    18B Dec 31  1969 libSDL.dylib -> libSDL-1.2.0.dylib
-r-xr-xr-x  1 root  nixbld   960B Dec 31  1969 libSDL.la
-r--r--r--  1 root  nixbld    12K Dec 31  1969 libSDLmain.a
-r-xr-xr-x  1 root  nixbld   1.2K Dec 31  1969 libSDLmain.la
```
`SDL_image.framework` and `SDL_ttf.framework` have similar issues.  The other 4 dylibs seem fine.

**Comment by numinit** [comment]
Alright, seems we should leave the prebuilts then.

**Comment by fmoda3** [comment]
Success it seems!
```console
❯ nix run "github:numinit/nixpkgs?ref=dwarf-fortress-darwin#dwarf-fortress" --impure
/------------------------------------------------------------------------------\
| Hello from the nixpkgs Dwarf Fortress wrapper!                               |
|                                                                              |
| Using the following Dwarf Fortress overlay directory as NIXPKGS_DF_HOME:     |
| /Users/fmoda3/.local/share/df_osx                                            |
|                                                                              |
| If you make any changes in it, don't forget to clean it when updating the    |
| game version! We detect changes if data directories are symbolic links.      |
|                                                                              |
| Even though we do our best on our own, this script may miss some. Submit a   |
| pull request if there are any that become a problem.                         |
|                                                                              |
| We started with the following nixpkgs launch options as NIXPKGS_DF_OPTS:     |
| debug=0,fmod=0                                                               |
|                                                                              |
| If you want to try fmod over SDL_mixer, set NIXPKGS_DF_OPTS=fmod.            |
\------------------------------------------------------------------------------/
Loading bindings from data/init/interface.txt
Resetting textures
```
image

**Comment by numinit** [comment]
Cool. Glad we were able to fix that (it was easier since it worked before...)

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 317116` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>17 packages built:</summary>
  <ul>
    <li>dwarf-fortress (dwarf-fortress-packages.dwarf-fortress ,dwarf-fortress-packages.dwarf-fortress_50_13)</li>
    <li>dwarf-fortress-packages.dwarf-fortress-full</li>
    <li>dwarf-fortress-packages.dwarf-fortress-original</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_43_05</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_44_05</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_44_09</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_44_10</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_44_11</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_44_12</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_47_01</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_47_02</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_47_04</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_47_05</li>
    <li>dwarf-fortress-packages.dwarf-fortress_50_10</li>
    <li>dwarf-fortress-packages.dwarf-fortress_50_11</li>
    <li>dwarf-fortress-packages.dwarf-fortress_50_12</li>
    <li>dwarf-therapist (dwarf-fortress-packages.dwarf-therapist)</li>
  </ul>
</details>

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 317116` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>17 packages built:</summary>
  <ul>
    <li>dwarf-fortress (dwarf-fortress-packages.dwarf-fortress ,dwarf-fortress-packages.dwarf-fortress_50_13)</li>
    <li>dwarf-fortress-packages.dwarf-fortress-full</li>
    <li>dwarf-fortress-packages.dwarf-fortress-original</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_43_05</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_44_05</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_44_09</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_44_10</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_44_11</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_44_12</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_47_01</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_47_02</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_47_04</li>
    <li>dwarf-fortress-packages.dwarf-fortress_0_47_05</li>
    <li>dwarf-fortress-packages.dwarf-fortress_50_10</li>
    <li>dwarf-fortress-packages.dwarf-fortress_50_11</li>
    <li>dwarf-fortress-packages.dwarf-fortress_50_12</li>
    <li>dwarf-therapist (dwarf-fortress-packages.dwarf-therapist)</li>
  </ul>
</details>

**Review by tomberek — APPROVED** [review]
It's been a year or two... so i forgot the keybindings!

**Pull request merged**
