### PR TITLE
fluidsynth: 1.1.6 -> 1.1.8

### PR DESCRIPTION
**Pull request by magnetophon**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by orivej — CHANGES_REQUESTED** [review]
`preBuild` fails on Darwin because `src/drivers/fluid_coreaudio.c` does not exist.

**Comment by magnetophon** [comment]
@orivej I don't have a darwin machine, so no way to test that.
The offending lines where in the pkg already.
I could just remove them, and see what happens on hydra; or do you have other suggestions?

**Comment by Mic92** [comment]
Are you sure I still see this file: https://github.com/FluidSynth/fluidsynth/blob/v1.1.8/src/drivers/fluid_coreaudio.c

**Comment by orivej** [comment]
@Mic92 Oh, it did not exist in `build/`, the working directory of the `cmake` build phase.

I have fixed the Darwin build.

**Review by orivej — APPROVED** [review]

**Pull request merged**
