### PR TITLE
BiglyBT: init at v2.8.0.0

### PR DESCRIPTION
**Pull request by joaquinito2048**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
FYI @joaquinito2048 a.k.a @joaquinito2051 a.k.a. @heroku-miraheze (see `maintainer-list.nix` for this) a.k.a. @joaquinito2051 (recently banned from  Matrix) got already blocked from GitHub for good reasons.

**Comment by joaquinito2048** [comment]
@Ma27 Please, merge this.

**Comment by joaquinito2048** [comment]
@Ma27 WTF???

**Comment by joaquinito2048** [comment]
I will contribute in another repository.

**Pull request closed without merging**
