### PR TITLE
python3Packages.hassil: 0.1.3 -> 0.1.4

### PR DESCRIPTION
**Pull request by mweinelt**
Changelog: https://github.com/home-assistant/hassil/releases/tag/v0.1.4

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
Does hassil work with any version of antlr?

**Comment by mweinelt** [comment]
We can and probably should regenerate the antlr files, yes.

**Comment by mweinelt** [comment]
```
❯ echo "what is the temperature in the living room" | ./result/bin/hassil en.yaml --areas 'living room'
INFO:hassil:Area names: ['living room']
INFO:hassil:Device/Entity names: []
Reading sentences from stdin...
{'intent': 'HassClimateGetTemperature', 'area': 'living room', 'domain': 'climate'}

**Comment by mweinelt** [comment]
Oddly enough the antlr files don't land in the final package, while they are part of the pypi sdist. The example still works.

```
lib/
lib/python3.10/
lib/python3.10/site-packages/
lib/python3.10/site-packages/hassil/
lib/python3.10/site-packages/hassil/VERSION
lib/python3.10/site-packages/hassil/__init__.py
lib/python3.10/site-packages/hassil/__main__.py
lib/python3.10/site-packages/hassil/__pycache__/
lib/python3.10/site-packages/hassil/__pycache__/__init__.cpython-310.pyc
lib/python3.10/site-packages/hassil/__pycache__/__main__.cpython-310.pyc
lib/python3.10/site-packages/hassil/__pycache__/_resources.cpython-310.pyc
lib/python3.10/site-packages/hassil/__pycache__/expression.cpython-310.pyc
lib/python3.10/site-packages/hassil/__pycache__/expression_listener.cpython-310.pyc
lib/python3.10/site-packages/hassil/__pycache__/intents.cpython-310.pyc
lib/python3.10/site-packages/hassil/__pycache__/parse.cpython-310.pyc
lib/python3.10/site-packages/hassil/__pycache__/recognize.cpython-310.pyc
lib/python3.10/site-packages/hassil/__pycache__/sample.cpython-310.pyc
lib/python3.10/site-packages/hassil/__pycache__/util.cpython-310.pyc
lib/python3.10/site-packages/hassil/_resources.py
lib/python3.10/site-packages/hassil/expression.py
lib/python3.10/site-packages/hassil/expression_listener.py
lib/python3.10/site-packages/hassil/grammar/
lib/python3.10/site-packages/hassil/grammar/HassILGrammarLexer.py
lib/python3.10/site-packages/hassil/grammar/HassILGrammarListener.py
lib/python3.10/site-packages/hassil/grammar/HassILGrammarParser.py
lib/python3.10/site-packages/hassil/grammar/HassILGrammarVisitor.py
lib/python3.10/site-packages/hassil/grammar/__init__.py
lib/python3.10/site-packages/hassil/grammar/__pycache__/
lib/python3.10/site-packages/hassil/grammar/__pycache__/HassILGrammarLexer.cpython-310.pyc
lib/python3.10/site-packages/hassil/grammar/__pycache__/HassILGrammarListener.cpython-310.pyc
lib/python3.10/site-packages/hassil/grammar/__pycache__/HassILGrammarParser.cpython-310.pyc
lib/python3.10/site-packages/hassil/grammar/__pycache__/HassILGrammarVisitor.cpython-310.pyc
lib/python3.10/site-packages/hassil/grammar/__pycache__/__init__.cpython-310.pyc
lib/python3.10/site-packages/hassil/intents.py
lib/python3.10/site-packages/hassil/parse.py
lib/python3.10/site-packages/hassil/py.typed
lib/python3.10/site-packages/hassil/recognize.py
lib/python3.10/site-packages/hassil/sample.py
lib/python3.10/site-packages/hassil/util.py
lib/python3.10/site-packages/hassil-0.1.4.dist-info/
lib/python3.10/site-packages/hassil-0.1.4.dist-info/INSTALLER
lib/python3.10/site-packages/hassil-0.1.4.dist-info/LICENSE.md
lib/python3.10/site-packages/hassil-0.1.4.dist-info/METADATA
lib/python3.10/site-packages/hassil-0.1.4.dist-info/RECORD
lib/python3.10/site-packages/hassil-0.1.4.dist-info/REQUESTED
lib/python3.10/site-packages/hassil-0.1.4.dist-info/WHEEL
lib/python3.10/site-packages/hassil-0.1.4.dist-info/direct_url.json
lib/python3.10/site-packages/hassil-0.1.4.dist-info/entry_points.txt
lib/python3.10/site-packages/hassil-0.1.4.dist-info/top_level.txt

**Comment by Mic92** [comment]
All files in there seems to come from the grammar:

> lib/python3.10/site-packages/hassil/grammar/

However since its mostly readable python, it wouldn't be end of the world to not build it from source.

**Pull request merged**
