### PR TITLE
nixos/lcd: add support for Logitech LCD

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

A number of (old) Logitech devices have LCDs built-in and this adds support for them.

There are a number of dependencies which are all contained inside a single file. As the last releases of those dependencies were all more than 10 years ago *and* the hardware is no longer being produced, I didn't think it was worth it to pollute the the global attribute set.

This all works here but as I don't have all the hardware, it would be great if somebody else could try it out as well.

~~A few minor things to do:~~

- ~~split the package and the module into separate commits~~
- ~~write release note~~

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by peterhoeg** [comment]
We want to merge this first: https://github.com/NixOS/nixpkgs/pull/82944

**Comment by lschuermann** [comment]
When trying to build this, my version of the `config-write` patch had the checksum `0jkrbqvzqrvxr14h5qi17cb4d32caq7vw9kzlz3qwpxdgxjrjvy2`. It appears as if the `patch` function's url is not entirely stable.

**Comment by peterhoeg** [comment]
>  It appears as if the patch function's url is not entirely stable.

Indeed. It's basically pointing at master in a git repository and if somebody changes anything, the checksum will change. This happens quite a lot with patches from Arch. It still beats maintaining it yourself though....

**Comment by peterhoeg** [comment]
This is good to go. Anybody else with some supported equipment?

**Pull request merged**
