### PR TITLE
androidenv: update generated expressions

### PR DESCRIPTION
**Pull request by lucafavatella**
Depends on #82067 .

###### Motivation for this change

Refresh the generated expressions.

This started by reusing bits from #58131 , grew with some smoke testing of emulator and adb, and reusing some bits from #78623 .

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
  - I am afraid I do not have time for understanding and testing this - help welcome.
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
     - As mentioned in commit "bump emulator version to latest stable - as per Linux", "Each OS has a distinct version..." so on macOS it may be not possible to use an emulator: I am not sure whether emulator version is configurable with the current version of the scripts. Help is welcome.
   - [x] other Linux distributions
     - Ubuntu Bionic on Travis CI.
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - I am afraid I do not have time for understanding and testing this - help welcome.
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
  - I am afraid I do not have time for understanding and testing this - help welcome.
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
  - I tested some binaries, not all. Please refer to comments for details.
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
  - I am afraid I do not have time for understanding and testing this - help welcome.
- [ ] Ensured that relevant documentation is up to date
  - I did one update but I am afraid for bringing all of the documentation to tested working examples would take too much time and I am unable to do that. (I am not sure whether the documentation examples are also present somewhere as tests executed on some CI server - that would make the doc simpler to update.)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lucafavatella** [comment]
> Tested execution of all binary files (usually in `./result/bin/`)
> * I tested some binaries, not all. Please refer to comments for details.

Here is the comment (so the comment stays in the record with the commit history in the GitHub PR events sequence as shown in Web UI): I tested binaries `adb` and `run-test-emulator` on Ubuntu Bionic. The relevant excerpts of my usage are the following.
```yaml
  - >
    nix-build
    -Q
    -E '
      with import (builtins.fetchGit {
        url = "https://github.com/lucafavatella/nixpkgs.git";
        ref = "emulator-google_apis_playstore";
        rev = "8ccc3870b0dca42593067c5bd78761f5d6f9da6b";
      }) {
        config.android_sdk.accept_license = true;
      };
      androidenv.emulateApp {
        name = "emulator-Device";
        /*
         * Android API 28 is Android 9.0.
         * See https://developer.android.com/studio/releases/platforms#9.0
         */
        platformVersion = "28";
        /*
         * From https://developer.android.com/studio/releases/emulator#support_for_arm_binaries_on_android_9_and_11_system_images :
         *
         * > ... you can now use the Android 9 x86 system image or any
         * > Android 11 system image to run your app – it is no longer
         * > necessary to download a specific system image to run ARM
         * > binaries.  These Android 9 and Android 11 system images support
         * > ARM by default and provide dramatically improved performance
         * > when compared to those with full ARM emulation.
         * >
         * > Known issues
         * > Some ARMv7 binaries fail to run on Android 11 x86 and x86_64
         * > system images.  Consider building for ARM64 when targeting
         * > Android 11.
         */
        abiVersion = "x86";
        systemImageType = "google_apis_playstore";
      }
    '
    -o emulator
  - test -f emulator/bin/run-test-emulator  # Ref https://github.com/NixOS/nixpkgs/blob/8d178aeed27482df666208a96b04357afc9726ad/pkgs/development/mobile/androidenv/emulate-app.nix#L134
  #
  - >
    nix-build
    -Q
    -E '
      with import <nixpkgs> {
        config.android_sdk.accept_license = true;
      };
      let
        androidComposition = androidenv.composeAndroidPackages {
        };
      in
      androidComposition.platform-tools
    '
    -o platform-tools
  - test -f platform-tools/bin/adb  # Ref https://github.com/NixOS/nixpkgs/blob/8d178aeed27482df666208a96b04357afc9726ad/pkgs/development/mobile/androidenv/compose-android-packages.nix#L254
```
```yaml
  - export PATH="$(pwd)/platform-tools/bin:${PATH?}"
```
```yaml
  - |
    AUDIO="-no-audio"
    EMU_PARAMS="-verbose -no-snapshot -no-window -camera-back none -camera-front none -selinux permissive -qemu -m 2048 -skip-adb-auth"
    # This double "sudo" monstrosity is used to have Travis execute the
    # emulator with its new group permissions and help preserve the rule
    # of least privilege.
    sudo -E sudo -u $USER -E \
      env NIX_ANDROID_EMULATOR_FLAGS="${AUDIO?} ${EMU_PARAMS?}" \
      ./emulator/bin/run-test-emulator
```
```yaml
  - adb devices -l
```

Commit `8ccc3870b0dca42593067c5bd78761f5d6f9da6b` is the merge of this branch (as of f01278dea25) and of PR #82119 (as of 38aa25ae67e).

**Comment by lucafavatella** [comment]
> Tested execution of all binary files (usually in `./result/bin/`)

Even if not strictly an output binary, I tested `generate.sh` - both by running it via `bash ./generate.sh` on a Nix-less macOS setup (for convenience), and on the following Docker image (via Docker Machine / VirtualBox) - comparing the results for determinism:
```
FROM nixos/nix
RUN mkdir /workdir
ADD generate.sh /workdir/
ADD convertpackages.xsl convertsystemimages.xsl convertaddons.xsl /workdir/
CMD ["/workdir/generate.sh"]

docker run --rm --mount type=bind,src=/generated,dst=/workdir/generated -w /workdir <IMAGE-ID-HERE>
```

**Comment by lucafavatella** [comment]
> * As mentioned in commit "bump emulator version to latest stable - as per Linux", "Each OS has a distinct version..." so on macOS it may be not possible to use an emulator: I am not sure whether emulator version is configurable with the current version of the scripts. Help is welcome.

@fmnxl Your insight may be doubly helpful here. I already included your change re dependencies (thanks!); I also noticed that you [had proposed a change](https://github.com/NixOS/nixpkgs/pull/78623/commits/7bf582265385960f5eca33556586a78d2f33c750) that makes emulator `29.3.6` available on both Linux and macOS. Could you please  consider reviewing this (#82118) PR, and prepare a branch with the enhancements you envisage so we get most androidenv-related enhancements merged.

**Comment by lucafavatella** [comment]
@dicearr I read in [one of your recent comments](https://github.com/NixOS/nixpkgs/pull/67661#discussion_r352134211) that you used the files changed in this PR (androidenv). It would be great if you managed to try this out and recommend fixes - preferably in the form of a branch/PR. Thanks!

**Comment by svanderburg** [comment]
Great work so far. I need a bit of time to review this, but so far the androidenv changes look great.

**Comment by svanderburg** [comment]
@lucafavatella To make my life a bit easier when it comes to reviewing. Can you try to run the tests in this repository? https://github.com/svanderburg/nix-androidenvtests

You can find tests in this folder: https://github.com/svanderburg/nix-androidenvtests/tree/master/tests

If you take a look at the root expression in `deployment/default.nix`, then you'll might notice that there is a parameter called `useUpstream` that is set to `false`. If you change this parameter to `true` then it will try to build the testcases with the `androidenv` implementation that is in Nixpkgs, instead of the implementation in the repository.

For example, running the following testcase described in the README.md file with the `useUpstream` parameter:

```bash
nix-build -A emulate_myfirstapp_debug.host_x86_64-linux.build_16.emulate_16.armeabi-v7a --arg useUpstream true
```

will build a script that builds an APK and launches the emulator using the `androidenv` from Nixpkgs.

If these testcases succeed, then there is nothing holding me back from integrating these changes into Nixpkgs.

**Comment by lucafavatella** [comment]
> @lucafavatella To make my life a bit easier when it comes to reviewing. Can you try to run the tests in this repository? https://github.com/svanderburg/nix-androidenvtests

@svanderburg Thanks for coming back to me, that is helpful! I hope to be able to try those out in the following couple of days, then I shall report back.

**Comment by lucafavatella** [comment]
> For example, running the following testcase described in the README.md file with the `useUpstream` parameter:

@svanderburg Could you please consider helping me with https://github.com/svanderburg/nix-androidenvtests/pull/12 - there is one example failing. So far I did not arrive at investigating why.

Once the examples pass with upstream, I shall update those examples for showing they still pass with the changes in this PR #82118 .

**Comment by lucafavatella** [comment]
> Once the examples pass with upstream, I shall update those examples for showing they still pass with the changes in this PR #82118 .

Tests are passing with upstream on CI at https://github.com/svanderburg/nix-androidenvtests/pull/12 - @svanderburg could you please consider merging that, enabling Travis CI in that repo? It would help future updates in this (nixpkgs) repo.

I still need to run the tests in svanderburg/nix-androidenvtests with the changes in this (#82118) PR, though I will not arrive at doing that for now. Help is welcome.

**Comment by dicearr** [comment]
> @dicearr I read in [one of your recent comments](https://github.com/NixOS/nixpkgs/pull/67661#discussion_r352134211) that you used the files changed in this PR (androidenv). It would be great if you managed to try this out and recommend fixes - preferably in the form of a branch/PR. Thanks!

Hi @lucafavatella I have checked your work so far and It looks great. I had to do similar stuff to make the emulator work locally. I don't think I can contribute anyhow to this PR but I will keep an eye on it and make a PR if I come up with anything.

**Comment by ijohanne** [comment]
I've been eagerly awaiting getting the ndkBundle bumped in version (cargo-ndk doesn't work with anything less than 19c, and before this PR goes in - the only one available is 18). I checked out the branch and used `-I nixpkgs=../nixpkgs` to see if this one would remedy everything for me, but I found out that the `pkgs/development/mobile/androidenv/ndk-bundle/make_standalone_toolchain.py_18.patch` doesn't apply when using `androidComposePackages`. I'm not sure why the patch needs to be there (forgive me for missing some history on why regarding that) - but having removed the last three chunks in the diff - it applied cleanly, and I could then use `cargo-ndk` and build packages inside a `nix-shell`. Is it out of scope of this PR to also account for this before it gets merged?

**Comment by lucafavatella** [comment]
> Is it out of scope of this PR to also account for this before it gets merged?

@ijohanne I would prefer to keep it out of scope unless strictly necessary (and I understand it is not).

Once I get back to this PR, I shall check if the tests at https://github.com/svanderburg/nix-androidenvtests/tree/4daacee111d13b69a707618dab6af5c656036d20 still pass and attempt to fix this PR if not. This comes from review earlier in this PR:

> ... Can you try to run the tests in this repository? https://github.com/svanderburg/nix-androidenvtests
>
> ...
>
> If these testcases succeed, then there is nothing holding me back from integrating these changes into Nixpkgs.

**Pull request merged**
