### PR TITLE
x11/xorg: stdenv.lib -> lib in meta generator

### PR DESCRIPTION
**Pull request by Profpatsch**
The library does not depend on stdenv, that stdenv exposes lib is
an artifact of the ancient origins of nixpkgs.

I didn’t run the generator since it takes quite a while, but it should
be automatically done the next time somebody updates a package.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
I think the generator should be run to avoid confusing the next person who runs it.

**Review by siraben — APPROVED** [review]

**Comment by rnhmjoj** [comment]
> The library does not depend on stdenv, that stdenv exposes lib is
an artifact of the ancient origins of nixpkgs.

I've always wondered why it's exposed in two places.
Would it make sense to do this change treewide?

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/issues/108938

**Comment by Profpatsch** [comment]
I ran the generator and added the change in a second commit.

**Review by alyssais — APPROVED** [review]

**Pull request merged**
