### PR TITLE
ledger-live-desktop: 2.50.0 -> 2.50.1

### PR DESCRIPTION
**Pull request by MGenerowicz**
ledger-live-desktop: 2.50.0 -> 2.50.1

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by eliandoran** [comment]
Result of `nixpkgs-review pr 205889` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ledger-live-desktop</li>
  </ul>
</details>

**Review by eliandoran — COMMENTED** [review]
@MGenerowicz , the update seems good, but could you please rebase your branch against `master`? It seems you have a merge commit as well, and I think it would be ideal to only have one commit in this case.

**Comment by MGenerowicz** [comment]
@eliandoran, im not sure what you mean in this case,
if you tell me how i will be happy to do it

**Comment by eliandoran** [comment]
Hi, @MGenerowicz .

I think one of the issues you are having is that you are using your own `master` branch to push changes to the nixpkgs. Usually we have to create a branch based on the upstream `master` branch (the `master` branch from `NixOS/nixpkgs`, not from `MGenerowicz/nixpkgs`).

I'll write to you once I finish work, perhaps it would help to start from scratch if you're OK with that (create a new fork and set up the branches).

**Comment by MGenerowicz** [comment]
Sounds perfect

**Comment by eliandoran** [comment]
I've just learned that you can't have two forks of the same repository on the same GitHub profile, so instead of removing the fork, we'll focus instead on “fixing” it by aligning its master branch with the official one.

## Step 1. Adding the remote to the official nixpkgs

The first step is to add NixOS/nixpkgs as a Git remote, since this will allow us to obtain the latest version of the  “official” master branch. On your local computer, open a terminal in the forked nixpkgs repository.

Then add NixOS/nixpkgs as a new remote called upstream (the name is not really relevant, it can be anything else):

```
git remote add upstream https://github.com/NixOS/nixpkgs.git
```

Then we need to grab all the modifications which were made on the upstream remote:

```
git fetch upstream
```

**Comment by eliandoran** [comment]
### Step 2. Avoiding data loss

First, make sure there is no important information on your master branch, since we are going to remove it.

GitHub helps us here since it's showing that the master branch is 3 commits ahead (commits that you have in the branch, but they are not present in the official repository) and 44 commits behind (commits that are not present in the fork, meaning that the branch is slightly outdated).

image

Clicking on “[3 commits ahead](https://github.com/NixOS/nixpkgs/compare/master...MGenerowicz:nixpkgs:master)” reveals:

image

From the three modifications, only one is relevant (ledger-live-desktop…), the other ones are merges. These merges are caused by the fact that inside the master branch of the fork, a commit was made which is not present in NixOS/nixpkgs. Thus, Git has to “merge” these two branches together.

Since we have a single commit, we can copy its commit hash (ID), which is displayed to the right of the commit.

image

In this case, the full commit hash is `107ff4b2b42871d4932b2a27f2283e53a0ad48aa` (in GitHub, press the button to the left of the commit to obtain the full commit hash).

**Comment by eliandoran** [comment]
### Step 3. Recreating the master branch

The first step is to go to a different branch than the one we are deleting. In this case we can move to the “official” branch:

```
git checkout upstream/master
```

Then we need to delete our main branch:

```
git branch -D master
```

The next step is to recreate the branch based on the latest version of the official one:

```
git checkout -b master upstream/master
```

The changes that we did were made only locally, now we need to push our changes to GitHub as well. If we try to do a normal push GitHub would not allow us because we are trying to replace the branch with something else, so we will do a force push:

```
git push -u origin master --force
```

Now when you go back to GitHub, the master branch should appear clean:

image

**Comment by eliandoran** [comment]
@MGenerowicz , let's follow the steps above. After this you should have a clean `master` branch and then we can proceed to recreating the work you have done with this PR.

**Pull request closed without merging**
