### PR TITLE
mygui: 3.4.0 -> 3.4.1

### PR DESCRIPTION
**Pull request by smancill**
###### Description of changes

Redo of #149833, with the fix to the license requested by the reviewer.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
@ofborg build stuntrally

**Comment by Mic92** [comment]
Looks like this update broke the ogre backend. I tried to address those breakages in this branch: https://github.com/Mic92/nixpkgs/commits/mygui-3.4.1
but I got stuck with new unrelated errors after bumping rigsofrods...

I would suggest we either mark all packages that use the current mygui that are not compatible with ogre 1.12 as broken or fix the issues.

**Comment by Mic92** [comment]
while upgrading I also saw that our openal pc file is incorrect and fixed it here: https://github.com/NixOS/nixpkgs/pull/182924/files

**Comment by smancill** [comment]
I don't have a Linux box to help with the breakage, I was browsing old PRs to see what can be revisited or restored.

**Comment by smancill** [comment]
I didn't notice that I selected this repo instead of my fork with `gh pr create --web`. I am closing this to delete the branch.

**Pull request closed without merging**
