### PR TITLE
nodejs-0_10: remove

### PR DESCRIPTION
**Pull request by cko**
###### Motivation for this change

node.js 0.10 reaches end of LTS in a few days (see https://github.com/nodejs/LTS for details). Therefore I removed it and set 3 dependant packages to broken as they don't build anymore

---

### CODE REVIEW

**Comment by grahamc** [comment]
:+1:

**Comment by groxxda** [comment]
Updating statsd should fix it: https://github.com/etsy/statsd/pull/565 

CC @garbas ?

**Comment by grahamc** [comment]
@andrewrk would you like to fix groovebasin before it is marked as broken?

@vbgl would you like to fix opa before it is marked as broken?

I propose we merge in 24hrs unless we hear back.

**Comment by andrewrk** [comment]
Let's mark groovebasin as broken. I need to do some work upstream to make it work on the new node and that should not block nixpkgs

**Comment by vbgl** [comment]
I’ve just submitted a PR that fixes the build of `opa` with a recent `node_js`. Hope this helps.

**Comment by grahamc** [comment]
Merged in 80dfbfd9493b37a981686cc0041c60d382d46541, thank you!

**Pull request closed without merging**
