### PR TITLE
 graalvm-ce: add graalvm17-ce

### LINKED ISSUE #142345: Request: graalvm17
[GraalVM 21.3](https://www.graalvm.org/release-notes/21_3/) with support for JDK 17 was released on 2021-10-19.

/cc @ericdallo

### PR DESCRIPTION
**Pull request by thiagokokada**
###### Motivation for this change

Fixes #142345.

Also some fixes for issues @SuperSandro2000 commented on PR #142243.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thiagokokada** [comment]
Sorry folks, but again:

CC @ericdallo @hlolli @babariviere @glittershark @bennyandresen

@glittershark Can you test on macOS please?

**Review by glittershark — APPROVED** [review]
haven't tested *every* binary (there's a lot of them!) but it builds fine on darwin and `native-image`, `irb`, and `graalpython` all seem to function correctly

**Comment by glittershark** [comment]
code also lgtm

**Review by ericdallo — APPROVED** [review]
code-wire looks good, but I can only test it manually in the weekend

**Comment by thiagokokada** [comment]
@SuperSandro2000 Can we have this merged? I also fixed the issues you found in PR #142243.

**Review by glittershark — APPROVED** [review]

**Review by lorenzleutgeb — APPROVED** [review]

**Review by timokau — APPROVED** [review]
Thank you!

**Pull request merged**
