### PR TITLE
azure-cli: 2.17.1 -> 2.18.0, bump python3Packages.azure* packages

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
routine bump

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
```
builder for '/nix/store/3hmw5c01afyh87dvq558z1ish554ajzc-python3.8-azure-mgmt-cdn-10.0.0.drv' failed with exit code 1; last 10 log lines:
  adding 'azure_mgmt_cdn-10.0.0.dist-info/RECORD'
  removing build/bdist.macosx-10.6-x86_64/wheel
  Finished executing setuptoolsBuildPhase
  installing
  Executing pipInstallPhase
  /private/tmp/nix-build-python3.8-azure-mgmt-cdn-10.0.0.drv-0/azure-mgmt-cdn-10.0.0/dist /private/tmp/nix-build-python3.8-azure-mgmt-cdn-10.0.0.drv-0/azure-mgmt-cdn-10.0.0
  Processing ./azure_mgmt_cdn-10.0.0-py2.py3-none-any.whl
  Requirement already satisfied: msrest>=0.5.0 in /nix/store/igi6l4g6yiz2mykibhb0wz074w0x98i9-python3.8-msrest-0.6.19/lib/python3.8/site-packages (from azure-mgmt-cdn==10.0.0) (0.6.19)
  ERROR: Could not find a version that satisfies the requirement azure-mgmt-core<2.0.0,>=1.2.0 (from azure-mgmt-cdn)
  ERROR: No matching distribution found for azure-mgmt-core<2.0.0,>=1.2.0
```

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110990` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>2 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.azure-mgmt-cdn: log <a href="https://termbin.com/rra3">https://termbin.com/rra3</a></li>
<li>python38Packages.azure-mgmt-cdn: log <a href="https://termbin.com/ulmli">https://termbin.com/ulmli</a></li>
  </ul>
</details>
<details>
<summary>
5 packages built:
</summary>
<ul>
<li>azure-cli</li>
<li>python37Packages.azure-mgmt-botservice</li>
<li>python37Packages.azure-mgmt-reservations</li>
<li>python38Packages.azure-mgmt-botservice</li>
<li>python38Packages.azure-mgmt-reservations</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

azure-cli:
<details>

Please consider this feature to be alpha.

A substituteInPlace with an unmatched pattern got detected:
```
substituteStream(): WARNING: pattern 'wheel==0.30.0' doesn't match anything in file 'setup.py'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110990` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages marked as broken and skipped:
</summary>
<ul>
<li>python39Packages.azure-mgmt-botservice</li>
<li>python39Packages.azure-mgmt-cdn</li>
<li>python39Packages.azure-mgmt-reservations</li>
</ul>
</details>
<details>

  <summary>2 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.azure-mgmt-cdn: log <a href="https://termbin.com/9i9n">https://termbin.com/9i9n</a></li>
<li>python38Packages.azure-mgmt-cdn: log <a href="https://termbin.com/gddx">https://termbin.com/gddx</a></li>
  </ul>
</details>
<details>
<summary>
5 packages built:
</summary>
<ul>
<li>azure-cli</li>
<li>python37Packages.azure-mgmt-botservice</li>
<li>python37Packages.azure-mgmt-reservations</li>
<li>python38Packages.azure-mgmt-botservice</li>
<li>python38Packages.azure-mgmt-reservations</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

azure-cli:
<details>

Please consider this feature to be alpha.

A substituteInPlace with an unmatched pattern got detected:
```
substituteStream(): WARNING: pattern 'wheel==0.30.0' doesn't match anything in file 'setup.py'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>

**Comment by jonringer** [comment]
```
https://github.com/NixOS/nixpkgs/pull/110990

7 packages built:
azure-cli python37Packages.azure-mgmt-botservice python37Packages.azure-mgmt-cdn python37Packages.azure-mgmt-reservations python38Packages.azure-mgmt-botservice python38Packages.azure-mgmt-cdn python38Packages.azure-mgmt-reservations
```

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110990` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
7 packages built:
</summary>
<ul>
<li>azure-cli</li>
<li>python37Packages.azure-mgmt-botservice</li>
<li>python37Packages.azure-mgmt-cdn</li>
<li>python37Packages.azure-mgmt-reservations</li>
<li>python38Packages.azure-mgmt-botservice</li>
<li>python38Packages.azure-mgmt-cdn</li>
<li>python38Packages.azure-mgmt-reservations</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

azure-cli:
<details>

Please consider this feature to be alpha.

A substituteInPlace with an unmatched pattern got detected:
```
substituteStream(): WARNING: pattern 'wheel==0.30.0' doesn't match anything in file 'setup.py'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110990` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
7 packages built:
</summary>
<ul>
<li>azure-cli</li>
<li>python37Packages.azure-mgmt-botservice</li>
<li>python37Packages.azure-mgmt-cdn</li>
<li>python37Packages.azure-mgmt-reservations</li>
<li>python38Packages.azure-mgmt-botservice</li>
<li>python38Packages.azure-mgmt-cdn</li>
<li>python38Packages.azure-mgmt-reservations</li>
</ul>
</details>

**Pull request merged**
