### PR TITLE
vimPlugins.none-ls-nvim: init at 2023-10-01

### PR DESCRIPTION
**Pull request by ambroisie**
## Description of changes

I haven't removed `null-ls`, but perhaps we should consider that? It has been [archived by the original maintainer](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1621).

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
I wouldn't remove null-ls just yet as I believe it's quite popular. What we could do is display a warning with an advice about possible replaciements. It seems to me there is no clear "winner" yet, between conform,nvim, none-ls etc. Lazyvim has started using conform.nvim I think. Is none-ls a drop in replacement for null-ls ? ie., does the setup need to be changed ?

**Comment by ambroisie** [comment]
@teto `none-ls` _is_ the `null-ls` replacement, as in community maintained fork of the latter. Arguably we could alias `null-ls-nvim = none-ls-nvim`. It's the exact same API, only the name of the repo changed.

The other plug-ins are just that, other plug-ins.

**Comment by siph** [comment]
In addition to that. `LazyVim` has already switched to `none-ls`: https://github.com/LazyVim/LazyVim/pull/1517.

**Comment by teto** [comment]
I remembered another fork of null-ls but I've done a quick search on the ecosystem and the guy joined the none-ls project. I am not a fan of aliasing null-ls to none-ls since they are not the same plugins, one is going to be updated with potential breakage while the other one is stable, users should be able to keep using null-ls if they want to.

**Pull request merged**
