### PR TITLE
fcitx-unikey: init at 0.2.5

### PR DESCRIPTION
**Pull request by myguidingstar-zz**
###### Motivation for this change

Fcitx Input method Engine for Vietnamese language
###### Things done
- [x] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

For code review: This new package is mostly identical to an existing one:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/inputmethods/fcitx-engines/fcitx-hangul/default.nix

### CODE REVIEW

**Comment by fpletz** [comment]
cc @ericsagnes

**Comment by ericsagnes** [comment]
Thank you, it seems to work perfectly! (I know nothing about Vietnamese but I can type some funky letters with it :)

I have no problem to be the maintainer as I already maintain a few fcitx related packages and they tend to be quite stable, but feel free to add yourself to `meta.maintainers` if you feel like it. (Being a maintainer just mean you will receive an email when the build fail on Hydra, and get mentioned in issues related to the package)

Also, in case you can write docbook, could you add unikey to the fcitx engines list in the [input methods documentation](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/i18n/input-method/default.xml#L80)?

**Comment by myguidingstar** [comment]
too bad I forgot to rebase after git pull

**Comment by myguidingstar** [comment]
@ericsagnes I don't understand fcitx enough to maintain. Will absolutely do it when I gain more knowledge.

**Comment by ericsagnes** [comment]
> I don't understand fcitx enough to maintain. Will absolutely do it when I gain more knowledge.

No problems.

And thank you for adding unikey to the manual!

**Pull request closed without merging**
