### PR TITLE
emacsPackagesNg: remove old, overlapping emacs package declarations

### PR DESCRIPTION
**Pull request by mdorman**
Perhaps this is premature---I don't know exactly what the transition plan is for the emacs infrastructure.  But I found myself looking for something mindless to do, so I identified all but 20 entries in emacs-packages.nix that appeared superseded by the expressions in the elpa/melpa/melpaStable lists; the ones I left either seemed to have additional configuration that might render them unsuitable for using autogenerated info---though I suspect they could be change to be overrides---or where it appeared we had a more up-to-date version than was present in the generated files.

There were also some "emacs-modes" entries that appeared similarly out of date, though I did not drive that list to anywhere near completion.

If there are suggestions for ways to improve this, I'm happy to work on pushing it forward, though I would appreciate guidance.

cc @ttuegel

### CODE REVIEW

**Comment by jagajaga** [comment]
cc @oxij

**Comment by bendlas** [comment]
I resolved this with a simple reordering of repositories, such that the generated repositories take precedence:

`hand-rolled` < `melpa` < `elpa` < `melpa-stable` 
instead of
`melpa` < `elpa` < `melpa-stable` < `hand-rolled`

https://github.com/bendlas/nixpkgs/commit/c4f657a469fbd92aab3dd4a5602618a8443faf13

It seems to work out, and FWIW, I think this would make for a good transition.

**Comment by ttuegel** [comment]
> It seems to work out, and FWIW, I think this would make for a good transition.

It should always work because the package sets are [rigged](https://github.com/NixOS/nixpkgs/blob/master/lib/customisation.nix#L176) to have consistent dependencies. I'm not sure it would make a good transition strategy: we need to override the derived expressions from the custom build steps in the hand-rolled expressions, but demoting the hand-rolled expressions simply removes the customized versions.

**Comment by bendlas** [comment]
_Always_ is a strong word in the face of package authors that never seem to get tired of hacking elisp ;)
But yeah, I get that we need to override incompatible packages from (m)elpa, thus my reordering is probably not a wise thing to do in general. To me it was a good step up from directly managing `.emacs.d/elpa`. Despite reordering, the newScope should lead to consistent deps anyway, no?

So, does removing everything hand-rolled, that's also in `elpa` or `melpa-stable` and then only introducing overrides for incompatibility or stuff that we want to pin from `melpa`, sound like a better plan to you?

**Comment by ttuegel** [comment]
> Always is a strong word in the face of package authors that never seem to get tired of hacking elisp ;)

Heh, that's quite right. At least, the dependency set will always be consistent. It should be impossible to have two packages try to pull in different versions of a dependency. That's the most we can guarantee from the Nix side.

> So, does removing everything hand-rolled, that's also in elpa or melpa-stable and then only introducing overrides for incompatibility or stuff that we want to pin from melpa, sound like a better plan to you?

Yes, I think that's the way to go.

**Comment by mdorman** [comment]
@ttuegel I believe what you just said you thought was the way to go is basically what this PR does---not all of it, but a large chunk of it.

I see that it is now conflicting; I can resolve that, and I have at least one additional thing to remove, and I can probably find some more stuff, and I'm happy to do that work---but I would appreciate some active feedback to this PR as to whether you find it acceptable, before I spend more time on it.

**Comment by ttuegel** [comment]
@mdorman Unfortunately, I don't think this is ready in its current form. It doesn't seem that you made package overrides for the packages that have custom build phases, so I think it's unlikely that any of those packages will work. Also, unless you can test the new versions of all these packages, I think it would be better to remove one package per commit so that the package maintainers can quickly revert/evaluate if there is a problem. I realize that this is significantly more work; that's why I haven't done it yet myself. :frowning:

**Comment by mdorman** [comment]
OK.

**Pull request closed without merging**
