### PR TITLE
clickhouse: 23.3.13.6 -> 23.8.4.69

### PR DESCRIPTION
**Pull request by yu-re-ka**
## Description of changes

New LTS version

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
This looks ready, ofborg is passing.
Where you lookong for something else to take this out of draft ?

**Comment by yu-re-ka** [comment]
No, the build is failing. I'm currently looking into it.

**Comment by edef1c** [comment]
@yu-re-ka Is there a reason we're sticking with LTS? The switch to LTS in #123488 didn't seem to come with any real reasoning, and ClickHouse is evolving pretty quickly / worth keeping up to date on.
If anyone has a need for LTS specifically, I'd rather see that as an additional attribute.

**Comment by yu-re-ka** [comment]
In my view the benefit from sticking to an LTS version is that we can provide security updates on a NixOS release channel without breaking applications.
But in the end it's probably going to require multiple attributes pointing to multiple versions, and the security updates thing only really works if we always have the latest LTS version right before our branchoff, which in this case we don't (it doesn't build).

**Pull request closed without merging**
