### PR TITLE
cudatoolkit_11: cudatoolkit_11_6 → cudatoolkit_11_5

### PR DESCRIPTION
**Pull request by fabianhjr**
###### Description of changes

Partial rollback of #165021 per request of @samuela.

/cc @NixOS/cuda-maintainers 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by samuela** [comment]
Result of `nixpkgs-review pr 166359` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>cudnn_8_1_cudatoolkit_11</li>
    <li>python310Packages.cupy</li>
    <li>python39Packages.cupy</li>
  </ul>
</details>
<details>
  <summary>11 packages failed to build:</summary>
  <ul>
    <li>colmapWithCuda</li>
    <li>cudaPackages.cudatoolkit_11</li>
    <li>cudaPackages.cudatoolkit_11_6</li>
    <li>cudnn_8_3_cudatoolkit_11</li>
    <li>forge</li>
    <li>gromacsCudaMpi</li>
    <li>katagoWithCuda</li>
    <li>nccl_cudatoolkit_11</li>
    <li>python310Packages.jaxlibWithCuda</li>
    <li>python39Packages.jaxlibWithCuda</li>
    <li>python39Packages.tensorflowWithCuda</li>
  </ul>
</details>

**Comment by samuela** [comment]
I ran out of disk space that time. trying again...

**Comment by samuela** [comment]
Result of `nixpkgs-review pr 166359` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>cudnn_8_1_cudatoolkit_11</li>
    <li>python310Packages.cupy</li>
    <li>python39Packages.cupy</li>
  </ul>
</details>
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>colmapWithCuda</li>
    <li>cudatoolkit_11 (cudaPackages.cudatoolkit_11)</li>
    <li>cudnn_8_3_cudatoolkit_11</li>
    <li>forge</li>
    <li>gromacsCudaMpi</li>
    <li>katagoWithCuda</li>
    <li>nccl_cudatoolkit_11</li>
    <li>python310Packages.jaxlibWithCuda</li>
    <li>python39Packages.jaxlibWithCuda</li>
    <li>python39Packages.tensorflowWithCuda</li>
  </ul>
</details>

**Comment by samuela** [comment]
The cudnn_8_1_cudatoolkit_11 failure is expected since that violates version constraints between the two. Perhaps we should remove cudnn_8_1_cudatoolkit_11 at some point, but I don't think that's necessary in this PR. 

That's also causing the cupy failure:
```
[nix-shell:~/.cache/nixpkgs-review/pr-166359-2/nixpkgs]$ nix-build -A python3Packages.cupy
error: Package ‘cudatoolkit-11.5-cudnn-8.1.1’ in /home/ubuntu/.cache/nixpkgs-review/pr-166359-2/nixpkgs/pkgs/development/libraries/science/math/cudnn/generic.nix:90 is marked as broken, refusing to evaluate.
```
But that should all get fixed in https://github.com/NixOS/nixpkgs/pull/166276 anyways.

**Comment by samuela** [comment]
There's also this pesky issue that cudnn points to cudnn_7_6_cudatoolkit_10_1 which is very old. We don't need to fix that now though.

**Review by samuela — APPROVED** [review]
changes LGTM. Thanks for resolving so quickly @fabianhjr! Working with CUDA-related packages can be highly error-prone!

**Comment by SomeoneSerge** [comment]
> The cudnn_8_1_cudatoolkit_11 failure is expected
> https://github.com/NixOS/nixpkgs/pull/166359#issuecomment-1082669708

I'd suggest an alternative convention that "default" attributes (e.g. the "default build of cuda-8.1", where "default" refers to pinning just the major version of cudatoolkit, without the minor) shouldn't break. We can override `cudnn_8_1_cudatoolkit_11` to use the non-default `cudatoolkit_11_5` (or `_4`): this would not affect the users of `cudnn_8_3_cudatoolkit_11` (they'd only have to pull in the latest cuda, which we mark as `cudatoolkit_11`), but would unbreak the users of cudnn=8.1

**Comment by samuela** [comment]
@SomeoneSerge Yeah, I think that makes a lot of sense. The only reason I can think of to keep it around is for users with overlays overriding cudatoolkit_11 to be a compatible version. But o/w I agree; let's just get rid of it!

**Pull request merged**
