### PR TITLE
firefox: 55.0.3 -> 56.0.1, firefox-esr: 52.3.0esr -> 52.4.0esr [Critical security fixes]

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

- Critical security fixes 
- Firefox Screenshots
- Address form autofill (en-US only)
- Updated Preferences
- Media opened in a background tab will not play until the tab is selected
- Improved Send Tabs feature of Sync
- Other improvements

https://www.mozilla.org/en-US/security/advisories/mfsa2017-21/
https://www.mozilla.org/en-US/firefox/56.0/releasenotes/

Firefox now uses more Rust code. It generates bindings with Clang, but it fails if `cstddef` or other headers are in non-standard directories. So I added `-cxx-isystem` and `-isystem` to `ServoBindings.toml`.

`pkg-config` script for NSS was provided as a patch, but NSS now have an official one. It still requires some `postInstall` script.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by edolstra** [comment]
Is the icu upgrade necessary for Firefox? Because we may not want to cherry-pick that on the stable branch.

**Comment by taku0** [comment]
Yes, Firefox requires icu-i18n 59.1.
```
DEBUG: configure:17780: checking for icu-i18n >= 59.1
DEBUG: configure: error: Library requirements (icu-i18n >= 59.1) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them.
```

**Comment by taku0** [comment]
Made 58.2 coexists with 59.1. Please tweak `all-packages.nix` when cherry-picking on the stable branch.

**Review by vcunat — APPROVED** [review]

**Comment by vcunat** [comment]
I tried running both firefox versions only for a while, and I could see nothing wrong.  I kept icu version to 58 by default for now, saving ~1400 rebuilds on x86_64-linux: a7159d3cd.

**Comment by grahamc** [comment]
@vcunat can you backport to 17.09 as well?

**Comment by vcunat** [comment]
Yes, I'm just building atop 17.09.  Also 17.03 is still supported for security, I guess?

**Comment by grahamc** [comment]
17.03 is receiving some patches, yeah, so I reckon it can't hurt -- but perhaps harder to backport.

**Comment by vcunat** [comment]
I'll see how hard 17.03 is.  17.09 still tends to be easy, as it's forked only several weeks ago.

**Comment by vcunat** [comment]
Hmm, hard I guess.  It 56.x needs rustc-1.17 and I didn't manage to port that one straightaway, so I picked all but 55.x -> 56.x.  I have no longer enough motivation to continue on that for 17.03, so feel to pick it up!

**Comment by vcunat** [comment]
This broke thunderbird build (it's the latest release).  It now fails with:
```
In file included from /tmp/nix-build-thunderbird-52.4.0.drv-0/objdir/dist/include/ScopedNSSTypes.h:16:0,
                 from /tmp/nix-build-thunderbird-52.4.0.drv-0/thunderbird-52.4.0/mozilla/netwerk/base/BackgroundFileSaver.h:15,
                 from /tmp/nix-build-thunderbird-52.4.0.drv-0/thunderbird-52.4.0/mozilla/netwerk/base/BackgroundFileSaver.cpp:7,
                 from /tmp/nix-build-thunderbird-52.4.0.drv-0/objdir/netwerk/base/Unified_cpp_netwerk_base0.cpp:11:
/tmp/nix-build-thunderbird-52.4.0.drv-0/objdir/dist/system_wrappers/cert.h:3:23: fatal error: cert.h: No such file or directory
 #include_next <cert.h>
                       ^
compilation terminated.
```

**Comment by orivej** [comment]
The update to `nss` also broke the compilation of `xmlsec` (a dependency of `libreoffice`).

**Comment by 7c6f434c** [comment]
Hm, true. d66a3404a62629f91cd25fd696ea92b18328fc95

**Comment by 7c6f434c** [comment]
Hm, `sssd` seems to be broken by `nss` update and simple include path shuffling is not enough…

**Comment by 7c6f434c** [comment]
@vcunat  hopefully, 034c168aa29fa95c323125d970d4018d25ac7eee fixes everything.

**Comment by vcunat** [comment]
I picked it to 17.09 and 17.03 after some testing in there.  /cc @globin.

**Comment by vcunat** [comment]
On i686-linux we're getting
> --with-libclang-path is not available in this configuration

so I omitted those options on i686: e067d26f43c

**Pull request merged**
