### PR TITLE
PHP extensions as packages

### PR DESCRIPTION
**Pull request by etu**
##### Motivation for this change

So this is based on some work I've done a long time ago and based on things that @gustavderdrache use to customize PHP in Nix.

It seems to work quite well on top of #79377 by @Ma27 :)

So the goal here is to build the different native extensions as separate derivations and then use them to compose a PHP package.

##### Example: Our default install of php doesn't have bz2 support.

Then I build a PHP using the following command:
```bash
nix-build --expr 'with import ./. {}; php74.buildEnv { exts = pp: with pp.exts; [ bz2 ]; }'
```

It builds a bit and I get a result symlink back, then when I run `./result/bin/php -m` I can see `bz2` in the list of modules.

I've got most extensions to work with two notable exceptions:
 - readline
 - gettext

But I don't think that's a blocker for merging this. This still would provide new extensions for people needing some of the "native" extensions that we don't have enabled or even flags for without the need of compiling them themselves.

The next step would be to provide a minimal PHP to compose on top of and to use this minimal one to build our default php setup.

I've gone through *all* extensions for php 7.2, 7.3 and 7.4 and made sure that I have either made a comment or a build for each and everyone of the extensions in these three minor versions of php.

Some of the ones are oracle and other weird databases that we may have pecl's for anyways, so those I've left as comments for now. But they should be easy to move if needed.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [N/A] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
@etu interesting stuff! When you get around to it I'm curious to see some stats on this for a fully loaded `php` vs a minimal.

**Comment by etu** [comment]
@GrahamcOfBorg build php72Packages.exts php73Packages.exts php74Packages.exts

**Comment by etu** [comment]
@GrahamcOfBorg build php72Packages.exts php73Packages.exts php74Packages.exts

**Comment by etu** [comment]
@GrahamcOfBorg build php72Packages.exts php73Packages.exts php74Packages.exts

**Comment by etu** [comment]
@GrahamcOfBorg build php72Packages.exts php73Packages.exts php74Packages.exts

**Comment by etu** [comment]
@GrahamcOfBorg build php72Packages.exts php73Packages.exts php74Packages.exts

**Comment by etu** [comment]
@GrahamcOfBorg build php72Packages.exts php73Packages.exts php74Packages.exts

**Comment by etu** [comment]
@GrahamcOfBorg build php72Packages.exts php73Packages.exts php74Packages.exts

**Comment by etu** [comment]
@GrahamcOfBorg build php72Packages.exts php73Packages.exts php74Packages.exts

**Comment by etu** [comment]
@GrahamcOfBorg build php72Packages.exts php73Packages.exts php74Packages.exts

**Comment by etu** [comment]
@GrahamcOfBorg build php72Packages.exts php73Packages.exts php74Packages.exts

**Comment by etu** [comment]
@GrahamcOfBorg build php72Packages.exts php73Packages.exts php74Packages.exts

**Comment by etu** [comment]
@aanderse @Ma27 I think we're getting closer to something that can be useful here and can be a good second step towards a more modular php setup in nixpkgs :slightly_smiling_face:

**Comment by Ma27** [comment]
Bit late to the party, but just took a look and the code and it seems pretty nice, thanks!

**Pull request merged**
