### PR TITLE
Fix builds of my packages w/glibc-2.32

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change

Fix builds of some of my packages after #95089

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gnidorah** [comment]
cc @Ma27

**Comment by Ma27** [comment]
@gnidorah would like to test it, but I can't even fetch the source properly (to reproduce the build failure, I tried building on 9085a724fdd7668f6e59abd9dfc7aef4e1dde3dd first):

```
source> Initialized empty Git repository in /nix/store/w6hzm7z8i5k25vmi77clc70zakxbmdj5-source/Externals/BugTrap/.git/
source> remote: Enumerating objects: 42, done.
source> remote: Counting objects: 100% (42/42), done.
source> remote: Compressing objects: 100% (33/33), done.
source> remote: Total 1099 (delta 15), reused 16 (delta 9), pack-reused 1057
source> Receiving objects: 100% (1099/1099), 7.49 MiB | 8.01 MiB/s, done.
source> Resolving deltas: 100% (543/543), done.
source> From https://github.com/OpenXRay/BugTrap
source>  * [new branch]      master     -> origin/master
source>  * [new tag]         v1.4.2     -> v1.4.2
source>  * [new tag]         v1.4.3     -> v1.4.3
source>  * [new tag]         v1.4.4     -> v1.4.4
source>  * [new tag]         v1.4.5     -> v1.4.5
source>  * [new tag]         v1.4.6     -> v1.4.6
source>  * [new tag]         v1.4.7     -> v1.4.7
source>  * [new tag]         v1.4.8     -> v1.4.8
source> fatal: reference is not a tree: 28c7928927ba05661ecdb2e4ff870dfaed0ac763
source> Unable to checkout 28c7928927ba05661ecdb2e4ff870dfaed0ac763 from https://github.com/OpenXRay/BugTrap.git.
error: --- Error --- nix-daemon
builder for '/nix/store/k6q2c29g3313wj5zszb96kc85c15cgw8-source.drv' failed with exit code 1
error: --- Error ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
error: --- Error --- nix-daemon
1 dependencies of derivation '/nix/store/v72c6sikb3qghz773sna8bxsa7408q9r-OpenXRay-730-july-preview.drv' failed to build
```

**Comment by gnidorah** [comment]
@Ma27 I've reported upstream https://github.com/OpenXRay/xray-16/issues/678
The developer recovered the BugTrap tree, now checkout should be fine. Please check

**Comment by Ma27** [comment]
`openxray` seems fine now, `cdesktopenv` breaks with the following error:

```
cde> /nix/store/hiwz81i1g3fn3p0acjs042a4h5fri6dh-binutils-2.31.1/bin/ld: ./ksh93/lib/libast.a(fmterror.o): in function `fmterror':
cde> /build/cde-2.3.2/programs/dtksh/ksh93/src/lib/libast/string/fmterror.c:102: undefined reference to `sys_nerr'
cde> /nix/store/hiwz81i1g3fn3p0acjs042a4h5fri6dh-binutils-2.31.1/bin/ld: /build/cde-2.3.2/programs/dtksh/ksh93/src/lib/libast/string/fmterror.c:102: undefined reference to `sys_errlist'
cde> collect2: error: ld returned 1 exit status
cde> make[3]: *** [Makefile:793: dtksh] Error 1
cde> make[3]: Leaving directory '/build/cde-2.3.2/programs/dtksh'
cde> make[2]: *** [Makefile:737: all] Error 2
cde> make[2]: Leaving directory '/build/cde-2.3.2/programs'
cde> make[1]: *** [xmakefile:734: all] Error 2
cde> make[1]: Leaving directory '/build/cde-2.3.2'
cde> make: *** [Makefile:61: World] Error 2
error: --- Error --- build-remote
```

**Comment by gnidorah** [comment]
@Ma27 Thanks! I'm still waiting for proper cdesktopenv fix

**Comment by gnidorah** [comment]
@Ma27 cdesktopenv needs fixes, so I've marked it as broken for now. Could you please merge this PR?

**Comment by gnidorah** [comment]
@Ma27 Thank you!

**Pull request merged**
