### PR TITLE
wine{Unstable,Staging}: 8.3 -> 8.5

### PR DESCRIPTION
**Pull request by reckenrode**
###### Description of changes

https://www.winehq.org/announce/8.4
https://www.winehq.org/announce/8.5

This fixes the crash on Darwin described in #224209. A separate PR for 8.0.1 will follow once it is available.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by reckenrode** [comment]
Result of `nixpkgs-review pr 224239` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>wine64Packages.staging</li>
    <li>wine64Packages.stagingFull</li>
    <li>wine64Packages.unstable</li>
    <li>wine64Packages.unstableFull</li>
  </ul>
</details>

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 224239` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by wegank** [comment]
@ofborg build wine64Packages.unstableFull wine64Packages.stagingFull

**Comment by reckenrode** [comment]
`nixpkgs-review` failed on my Linux device (which stopped responding to network requests), so I set up a NixOS VM on my Mac to do the build. It’s using Rosetta for the x86_64-linux stuff, but it’s using QEMU for i686-linux, which is not especially fast building Wine.

**Review by wegank — APPROVED** [review]

**Comment by wegank** [comment]
I've got this on my slowish x86_64 server:

```

4 packages failed to build:
lutris lutris-free lutris-unwrapped lutris-unwrapped.dist

18 packages built:
grapejuice grapejuice.dist pipelight winbox wine-staging wine64Packages.staging wine64Packages.stagingFull wine64Packages.unstable wine64Packages.unstableFull winePackages.staging winePackages.unstable winePackages.unstableFull wineWowPackages.staging wineWowPackages.stagingFull wineWowPackages.unstable wineWowPackages.unstableFull yabridge yabridgectl
```

where the errors seem to be only timeouts.

```
> subprocess.TimeoutExpired: Command '['/nix/store/syz2y6j53y5hpzbs7l0965zwxshi8iyl-python3-3.10.10/bin/python3.10', 'share/lutris/bin/lutris-wrapper', 'title', '0', '1', 'bash', 'bash', '-c', 'echo Hello World; exec 1>&-; while sleep infinity; do true; done']' timed out after 30 seconds
```

**Comment by reckenrode** [comment]
I was able to get everything to build in my VM, but it kernel panicked right after `nixpkgs-review` finished and was preparing the `nix-shell`. Everything did build at least, but it’s not formatted per `report.md`.

    22 packages built:
    grapejuice grapejuice.dist lutris lutris-free lutris-unwrapped lutris-unwrapped.dist pipelight winbox wine-staging wine64Packages.staging wine64Packages.stagingFull wine64Packages.unstable wine64Packages.unstableFull winePackages.staging winePackages.unstable winePackages.unstableFull wineWowPackages.staging wineWowPackages.stagingFull wineWowPackages.unstable wineWowPackages.unstableFull yabridge yabridgectl

**Pull request merged**
