### PR TITLE
s3ql: 3.3.2 -> 3.7.2

### PR DESCRIPTION
**Pull request by jnetod**
At least one test fails if ran under ZFS.

https://github.com/s3ql/s3ql/issues/249

###### Motivation for this change

ZHF: #122042

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by karolchmist** [comment]
Result of `nixpkgs-review pr 123183` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>s3ql</li>
  </ul>
</details>

**Review by karolchmist — APPROVED** [review]

**Comment by jnetod** [comment]
It failed on aarch64. Which filesystem `grahamc-aarch64-community-8` uses on `/tmp`?

**Comment by jonringer** [comment]
`/tmp` is typically a tmpfs. However, grahamc may have configured it differently for builders

**Comment by jonringer** [comment]
either way, The update still seems worth while. Aarch64 can be done in another PR.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 123183 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>1 package built:</summary>  <ul>    <li>s3ql</li>  </ul></details>

**Pull request merged**
