### PR TITLE
directx-shader-compiler: build with gcc11 for i686

### LINKED ISSUE #216294: Build failure: amdvlk
### Steps To Reproduce

Similar to Hydra now, I'm having issues with `amdvlk` with i686

### Build log

https://hydra.nixos.org/build/209322760

### Additional context

This is used for x86_64 to get the drivers to run Steam and other older games. Building from `master` as I have for months while I wait for #177623 + #187303 because I need to turn off the broken build flag. Maybe one day it will get reviewed and merged in and I can go back to unstable.

### Notify maintainers

@Flakebi 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.11, NixOS, 23.05 (Stoat), 23.05.20230213.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(toastal): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by andresilva**
###### Description of changes

Fixes https://github.com/NixOS/nixpkgs/issues/216294.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SFrijters** [comment]
Result of `nixpkgs-review pr 216796` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>driversi686Linux.amdvlk</li>
  </ul>
</details>

**Comment by eboskma** [comment]
Result of `nixpkgs-review pr 216796` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>driversi686Linux.amdvlk</li>
  </ul>
</details>

**Comment by vcunat** [comment]
That's a different package than in the referenced issue, but possibly same problem and workaround.  Still, it's good to check if things work in practice, as mixing compiler versions can cause issues (e.g. with C++ stuff), especially when `/run/opengl-driver/*` gets injected impurely.

**Comment by andresilva** [comment]
Tested by running `vkcube` from `pkgsi686Linux.vulkan-tools`, no issues. I'm not an expert on any of this though.

**Pull request merged**
