### PR TITLE
cudnn_cudatookit_11: add $ORIGIN/ to library RPATHs

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

Starting with version 8, CuDNN consists of multiple libraries.
Libraries (except libcudnn.so) are dlopen()ed on demand.

Since the CuDNN library path itself was not added to the rpath of the
libraries, use of CuDNN often fails with the following error:

Could not load library libcudnn_cnn_train.so.8.
Error: libcudnn_ops_train.so.8: cannot open shared object file: No such file or directory
Please make sure libcudnn_cnn_train.so.8 is in your library path!

This change fixes this by adding $ORIGIN/ to the rpath of all CuDNN
libraries.

Tested using the CuDNN examples provided by NVIDIA.

**Additional change**

With the update to CuDNN 8.1, we do not get the "maximum file size
exceeded" error anymore when patchelf'ing libcudnn_cnn_infer.so. This
change removes the exception for that library.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113105` at 8dad19ae run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>python37Packages.pytorchWithCuda</li>
    <li>python37Packages.tensorflowWithCuda</li>
    <li>python38Packages.pytorchWithCuda</li>
    <li>python38Packages.tensorflowWithCuda</li>
    <li>python39Packages.pytorchWithCuda</li>
    <li>python39Packages.tensorflowWithCuda</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113105` at 8dad19ae run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python39Packages.pytorchWithCuda</li>
    <li>python39Packages.tensorflowWithCuda</li>
  </ul>
</details>
<details>
  <summary>24 packages failed to build:</summary>
  <ul>
    <li>cudnn (cudnn_cudatoolkit_10 ,cudnn_cudatoolkit_10_2)</li>
    <li>cudnn6_cudatoolkit_8</li>
    <li>cudnn_cudatoolkit_10_0</li>
    <li>cudnn_cudatoolkit_10_1</li>
    <li>cudnn_cudatoolkit_11 (cudnn_cudatoolkit_11_2)</li>
    <li>cudnn_cudatoolkit_11_0</li>
    <li>cudnn_cudatoolkit_11_1</li>
    <li>cudnn_cudatoolkit_7</li>
    <li>cudnn_cudatoolkit_7_5</li>
    <li>cudnn_cudatoolkit_8</li>
    <li>cudnn_cudatoolkit_9 (cudnn_cudatoolkit_9_2)</li>
    <li>cudnn_cudatoolkit_9_0</li>
    <li>cudnn_cudatoolkit_9_1</li>
    <li>katagoWithCuda</li>
    <li>python37Packages.TheanoWithCuda</li>
    <li>python37Packages.cupy</li>
    <li>python37Packages.pytorchWithCuda</li>
    <li>python37Packages.tensorflowWithCuda</li>
    <li>python38Packages.TheanoWithCuda</li>
    <li>python38Packages.cupy</li>
    <li>python38Packages.pytorchWithCuda</li>
    <li>python38Packages.tensorflowWithCuda</li>
    <li>python39Packages.TheanoWithCuda</li>
    <li>python39Packages.cupy</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/libraries/science/math/cudnn/generic.nix:25:3:
```
   |
25 |   installPhase = ''
   |   ^
```
</li>
  </ul>
</details>

**Comment by danieldk** [comment]
@r-rmcgibbo seems to be wrong here? The various cuDNN versions build fine here.

**Comment by danieldk** [comment]
Merging, since CuDNN for CUDA 11 is currently broken. Tested that there are no regressions for CuDNN for CUDA 10.

**Pull request merged**
