### PR TITLE
liana: 6.0 -> 8.0

### PR DESCRIPTION
**Pull request by dunxen**
## Description of changes

Release Notes:
  https://github.com/wizardsardine/liana/releases/tag/v7.0
  https://github.com/wizardsardine/liana/releases/tag/v8.0

Changes: https://github.com/wizardsardine/liana/compare/v6.0...v8.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by dunxen** [comment]
`lianad` can get updated in a separate PR @plebhash

**Comment by dunxen** [comment]
Hey @plebhash, would you be able to give a quick test of this and approval if happy? I see that [v8.0rc1](https://github.com/wizardsardine/liana/releases/tag/v8.0rc1) is already out so we're probably going to get v8 soon. :)

**Review by plebhash — APPROVED** [review]
tACK

**Comment by misuzu** [comment]
It's now possible to get rid of the lock file using `useFetchCargoVendor` option. See https://github.com/NixOS/nixpkgs/pull/349360

**Comment by dunxen** [comment]
> It's now possible to get rid of the lock file using `useFetchCargoVendor` option. See #349360

Great! I'll update this PR when I get the chance.

**Comment by dunxen** [comment]
Ah, looks like that's not possible for liana as git dependencies are not supported for the fetcher yet:

```
error: builder for '/nix/store/si0cp83fqvn5bqr6s31rw293k0x133kd-liana-8.0-vendor.tar.gz.drv' failed with exit code 1;
       last 18 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/r2gzm78h1077irfv5yl5xw65daxpqb3f-source
       > source root is source/gui
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > no configure script, doing nothing
       > Running phase: buildPhase
       > source = "git+https://github.com/edouardparis/iced?branch=patch-0.12.3#459c8eb3da2ae21461ee56baea8a1b10d38ff6e0"
       > source = "git+https://github.com/edouardparis/iced?branch=patch-0.12.3#459c8eb3da2ae21461ee56baea8a1b10d38ff6e0"
       > source = "git+https://github.com/edouardparis/iced?branch=patch-0.12.3#459c8eb3da2ae21461ee56baea8a1b10d38ff6e0"
       > source = "git+https://github.com/wizardsardine/liana?branch=8.x#749b111afac5aaa991622318738462d2857af713"
       >
       > ERROR: The Cargo.lock contains git dependencies
       >
       > This is currently not supported in the fixed-output derivation fetcher.
       > Use cargoLock.lockFile / importCargoLock instead.
```

**Comment by misuzu** [comment]
> Ah, looks like that's not possible for liana as git dependencies are not supported for the fetcher yet:

It was designed specifically to handle git dependencies, you just need to rebase your PR.

**Review by misuzu — APPROVED** [review]

**Pull request merged**
