### PR TITLE
python3Packages.jaxlibWithCuda: init at 0.1.75

### PR DESCRIPTION
**Pull request by samuela**
###### Motivation for this change
In the spirit of https://github.com/NixOS/nixpkgs/pull/156808, we'd like end-users to be able to select which "edition" of jaxlib they would like to use. This is akin to the `tensorflow` vs `tensorflowWithCuda` precedent. By adding `jaxlibWithCuda` to python packages, cache.nixos.org should be able to provide builds for users, freeing them from having to run a very time consuming and expensive build for themselves locally.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ndl — APPROVED** [review]
LG although you might consider adding `jaxlibWithoutCuda` that has an explicit `cudaSupport = false` setting, similar to how it's done for TF and PyTorch?

This shouldn't matter for the default configuration but if anyone overrides `jaxlib` to enable CUDA support there - having an explicit alias without CUDA might be useful?

**Comment by samuela** [comment]
Ah, good point... Added `jaxlibWithoutCuda` in https://github.com/NixOS/nixpkgs/pull/157055/commits/d045385f09ab6c4b4748d26fffc9c30b2302f44e.

I'll merge tomorrow unless anyone objects.

**Comment by FRidh** [comment]
>  By adding jaxlibWithCuda to python packages, cache.nixos.org should be able to provide builds for users, freeing them from having to run a very time consuming and expensive build for themselves locally.

Hydra won't build it because of the unfree cudatoolkit.

**Comment by samuela** [comment]
Damn... what do the tensorflow folks do then?

**Comment by FRidh** [comment]
Maybe they use the `-bin` versions of the packages that use pre-built wheels from PyPI.

**Comment by FRidh** [comment]
Also, is it really such a big deal to build it once every what, couple of weeks?

**Comment by samuela** [comment]
Compiling from source is pretty nasty with these ones. iirc building tensorflow from source is over 24 cpu-hours. Last time I had to debug that derivation I had to create an ec2 instance with as many cores as I could find.

**Comment by samuela** [comment]
I went ahead and merged since the changes are relevant with or without hydra, but I would like to keep talking about that side of things to figure out how we can get builds cached somewhere.

**Pull request merged**
