### PR TITLE
tinygo: 0.32.0 -> 0.33.0

### PR DESCRIPTION
**Pull request by aykevl**
## Description of changes

Updated to v0.33.0. See the changelog: https://github.com/tinygo-org/tinygo/blob/v0.33.0/CHANGELOG.md

The GNUmakefile patch became a bit smaller after some upstream changes.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by nagy — APPROVED** [review]
It works on `x86_64-linux` as well, thank you.

**Review by NickCao — APPROVED** [review]

**Comment by dyegoaurelio** [comment]
I was not able to build packages using go 1.23.x using this build, but just downloading the tinygo binary from  https://github.com/tinygo-org/tinygo/releases/tag/v0.33.0 works just fine.

**Comment by aykevl** [comment]
@dyegoaurelio which OS are you running? NixOS, Linux with Nix packags added, or MacOS?

**Comment by dyegoaurelio** [comment]
@aykevl I'm running nixos.

with tinygo from nixpkgs I get this while trying to compile go 1.23 projects

```

[nix-shell:~/tmp/go-test]$ GOOS=js GOARCH=wasm tinygo build -o out.wasm cmd/wasm/main.go
# internal/itoa

```


I created this simple derivation to just grab the binary from github

```
{ stdenv, fetchurl, lib }:

let
  version = "0.33.0";

in

stdenv.mkDerivation {
  name = "tinygo-${version}-bin";
  version = version;

  src = fetchurl {
    url = "https://github.com/tinygo-org/tinygo/releases/download/v${version}/tinygo${version}.linux-amd64.tar.gz";
    sha256 = "sha256:14ds89d7h2id1msrxabzlgh56nk4qbfr4r081j7vgv598pvyyad5";
  };

  unpackPhase = ''
    tar -xzf $src
  '';

  installPhase = ''
    mkdir -p $out/bin
    cp -r tinygo/* $out/
  '';

  meta = with lib; {
    description = "TinyGo version ${version}, a Go compiler for small places, based on the Go programming language but designed for microcontrollers, WebAssembly, and command-line tools.";
    homepage = "https://tinygo.org";
    license = licenses.bsd3;
    platforms = platforms.linux;
    maintainers = with maintainers; [ ];
  };
}


```

it compiles just fine using package.

I think it's related so some of the folders we're removing before compilation in the nix package

**Comment by dyegoaurelio** [comment]
you can test it out here:
[go-test.zip](https://github.com/user-attachments/files/17049519/go-test.zip)

**Comment by aykevl** [comment]
I can reproduce the issue, thanks for reporting!

**Comment by aykevl** [comment]
Unfortunately, I can't reproduce this issue when running tinygo as a flake, and I'm not really familiar with Nix and don't really know how to debug this.

**Comment by nagy** [comment]
Hello @dyegoaurelio , I could reproduce your issue. But the issue is not the removal of directories from the source. The issue was, that earlier the `buildGoModule` defaulted to go version 1.22. This has since been changed to default to 1.23 here:

* #342429 

That PR has not landed in master yet, but once it does, please check again, it should work then with go 1.23. You can consult the nix repl to check the state:

```
$ nix repl --file https://github.com/NixOS/nixpkgs/archive/staging.tar.gz
nix-repl> buildGoModule == buildGo122Module
false
nix-repl> buildGoModule == buildGo123Module
true
```

**Comment by aykevl** [comment]
I also managed to reproduce the issue locally. The core of the issue is indeed that while TinyGo supports Go 1.23, it was compiled using Go 1.22 and therefore didn't support all language features and therefore couldn't compile Go 1.23 code.

I made a PR to make issues like these much clearer: https://github.com/tinygo-org/tinygo/pull/4520

@nagy would it be reasonable to specify a different Go version for TinyGo, e.g. by using `buildGo123Module`? That would make sure TinyGo is always built with the Go version it expects. (A newer version than it supports is fine, but a too-old version means the `tinygo` binary can't compile newer code).

**Comment by nagy** [comment]
I would just leave it as it is in this case. I would expect that the attribute name without any version is always the latest. This will soon be the case for `buildGoModule` on master as well, as it is already the on staging. By pinning it to `buildGo123Module` we might forget about it when go 1.24 comes out.

**Pull request merged**
