### PR TITLE
buildDotnetModule: add passthru.fetch-deps

### PR DESCRIPTION
**Pull request by IvarWithoutBones**
###### Motivation for this change
This adds a script which fetches nuget dependencies for all projects using `buildDotnetModule`, as this was something that you had to do manually before. It should make packaging dotnet applications a lot more user friendly.

For example:
```shell
~/nix/nixpkgs > nix-build -A python-language-server.passthru.fetch-deps
/nix/store/p5yfgpgi2rr63gva01l94f2vxm8lwj2k-fetch-python-language-server-deps
~/nix/nixpkgs > /nix/store/p5yfgpgi2rr63gva01l94f2vxm8lwj2k-fetch-python-language-server-deps
/tmp/python-language-server.KuJ /nix/store
  Determining projects to restore...
  Restored /tmp/python-language-server.KuJ/src/Analysis/Core/Impl/Microsoft.Python.Analysis.Core.csproj (in 1.38 sec).
  Restored /tmp/python-language-server.KuJ/src/Parsing/Impl/Microsoft.Python.Parsing.csproj (in 1.38 sec).
  Restored /tmp/python-language-server.KuJ/src/Analysis/Ast/Impl/Microsoft.Python.Analysis.csproj (in 19 ms).
  Restored /tmp/python-language-server.KuJ/src/Core/Impl/Microsoft.Python.Core.csproj (in 17 ms).
  Restored /tmp/python-language-server.KuJ/src/LanguageServer/Impl/Microsoft.Python.LanguageServer.csproj (in 16.54 sec).
Writing lockfile...
Succesfully wrote lockfile to: /tmp/python-language-server-deps.nix
```
The location the file get's written to is kind of arbitrary, if anyone has a better suggestion please share!

This could potentially be used for auto-updating as well, though I'm not very familair with how that works. I'll have to look into it.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by IvarWithoutBones** [comment]
cc @prusnak

**Comment by prusnak** [comment]
There are 0 rebuilds anyway, so let's merge this in.

**Comment by legendofmiracles** [comment]
This seems to break custom `passthru`'s of derivations. See the failing tests on [this PR](https://github.com/NixOS/nixpkgs/pull/148541). 
https://github.com/NixOS/nixpkgs/runs/4647348126?check_suite_focus=true

**Comment by prusnak** [comment]
> This seems to break custom `passthru`'s of derivations.

@IvarWithoutBones Can you please have a look?

**Pull request merged**
