### PR TITLE
moonraker: unstable-2022-04-23 -> unstable-2022-11-18, nixos/moonraker: fixes

### PR DESCRIPTION
**Pull request by zhaofengli**
###### Description of changes

Moonraker is [moving](https://moonraker.readthedocs.io/en/latest/user_changes/#october-14th-2022) to storing all its files under a unified `data-path`. We set this path to `cfg.stateDir`.

- `database_path` was forced to `${cfg.stateDir}/databases` which is the [same path](https://github.com/Arksine/moonraker/blob/362bc1a3d3ad397416f7fc48b8efe33837428b90/moonraker/components/database.py#L83) Moonraker is using in the new scheme. No migration is needed.
- `config_path` / `configDir` was previously user-configurable. No migration is needed for the default value (`${cfg.stateDir}/config`), otherwise the module warns the user to move all files there before the setting is removed entirely upstream.

Alternatively, to simplify this we can just remove the `configDir` option entirely. I doubt that many people were using a separate `configDir`.

Supersedes #171500.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zhaofengli** [comment]
@ofborg test moonraker

**Comment by cab404** [comment]
looks fine, gotta test it on my setup :3

**Comment by zhaofengli** [comment]
I think we should just remove `configDir` to keep things simple. We could make it an `internal = true;` option and throw an error if it's set with a message suggesting a migration path. Any opinions?

**Comment by cab404** [comment]
> I think we should just remove `configDir` to keep things simple. We could make it an `internal = true;` option and throw an error if it's set with a message suggesting a migration path. Any opinions?

You will need to version gate this change, but I do support the idea.

**Comment by zhaofengli** [comment]
> You will need to version gate this change, but I do support the idea.

If you are talking about the Moonraker version in case the user overlays it, the new `-d` argument doesn't exist on older versions of Moonraker, so they already don't work with the new module. Adding code to support older unstable versions needlessly complicate things.

If you mean stateVersion, there is no good way to keep supporting the option once upstream entirely removes the setting, short of doing symlinks which also complicate things.

**Pull request merged**
