### PR TITLE
nodejs_20: 20.3.1 -> 20.4.0

### PR DESCRIPTION
**Pull request by marsam**
Changelog: https://github.com/nodejs/node/releases/tag/v20.4.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
not sure if this is a direct consequence of this PR, but I'm getting x86_64-darwin failure on building nodejs-20
```
> 20 libLLVM.dylib           0x000000010b01b022 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) + 226
       > 21 libclang-cpp.11.1.dylib 0x000000010468e0c0 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::alloriver::Command const&, clang::driver::Command const*&) const + 433
       > 23 libclang-cpp.11.1.dylib 0x000000010465c38c clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*> >&) const + 140
       > 24 libclang-cpp.11.1.dylib 0x000000010467594c clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*> >&) + 428
       > 25 clang-11                0x00000001000808cb main + 10283
       > 26 dyld                    0x0000000102f9852e start + 462
       > make[1]: *** [tools/v8_gypfiles/v8_base_without_compiler.target.mk:1094: /private/tmp/nix-build-nodejs-20.4.0.drv-0/node-v20.4.0/out/Release/obj.target/v8_base_without_compiler/deps/v8/src/objects/js-objects.o] Error 1
       > rm 11378f45f6f727b4d1ef2a50a5da6aa69a68202f.intermediate 985c41846a56d0066a3464bf60ffed375bec8901.intermediate 222919265df17f467ac2cf668d8486e0182908ab.intermediate 57a81c7004bf740e697481ff919eff0eb2213386.intermediate 1f93354eaa1606beae7636815a5da2d13e1f7a6a.intermediate
       > make: *** [Makefile:134: node] Error 2
```

This is not an emergency for me, just saying.

**Comment by marsam** [comment]
Thanks for the heads-up. It seems be broken by https://github.com/NixOS/nixpkgs/pull/243683, oddly enough it only breaks nodejs-20 for x86_64-darwin

**Comment by happysalada** [comment]
Thank you for your quick response!

**Comment by reckenrode** [comment]
When I get back, I’ll see if I can reproduce as well as check if it builds on my clang 16 branch.

**Comment by reckenrode** [comment]
It built locally for me using clang 11. I checked the log on Hydra, and it is crashing in a different place (the other logs show clang in the stack trace instead of llvm-ar). The error in Hydra suggests the builder might be low on disk space. The local build of nodejs v20.4.0 required ~30 GiB.

```
LLVM ERROR: IO failure on output stream: No space left on device
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: ar -cqs /nix/store/lpj5dy4ji58zxnbn781j0c40xn17kq20-nodejs-20.4.0-libv8/lib/libv8.a @files 
0  libLLVM.dylib            0x000000010b8043d6 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 54
1  libLLVM.dylib            0x000000010b8031b8 llvm::sys::RunSignalHandlers() + 248
2  libLLVM.dylib            0x000000010b804c70 SignalHandler(int) + 352
3  libsystem_platform.dylib 0x00007ff81b469c1d _sigtramp + 29
4  libcorecrypto.dylib      0x00007ff81b1fc8f6 drbg_update + 215
5  libsystem_c.dylib        0x00007ff81b388ca5 abort + 123
6  libLLVM.dylib            0x000000010b73908e llvm::report_fatal_error(llvm::Twine const&, bool) + 446
7  libLLVM.dylib            0x000000010b7390ab llvm::report_fatal_error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) + 27
8  libLLVM.dylib            0x000000010b7e5c73 llvm::raw_fd_ostream::~raw_fd_ostream() + 227
9  libLLVM.dylib            0x000000010cbd2a83 llvm::writeArchive(llvm::StringRef, llvm::ArrayRef<llvm::NewArchiveMember>, bool, llvm::object::Archive::Kind, bool, bool, std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer> >) + 10963
10 llvm-ar                  0x000000010641f984 performWriteOperation(ArchiveOperation, llvm::object::Archive*, std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer> >, std::__1::vector<llvm::NewArchiveMember, std::__1::allocator<llvm::NewArchiveMember> >*) + 3988
11 llvm-ar                  0x000000010641c735 performOperation(ArchiveOperation, llvm::object::Archive*, std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer> >, std::__1::vector<llvm::NewArchiveMember, std::__1::allocator<llvm::NewArchiveMember> >*) + 85
12 llvm-ar                  0x000000010641c3a6 performOperation(ArchiveOperation, std::__1::vector<llvm::NewArchiveMember, std::__1::allocator<llvm::NewArchiveMember> >*) + 1110
13 llvm-ar                  0x000000010641b8d7 main + 4343
14 dyld                     0x00007ff81b10e310 start + 2432
/nix/store/6lqprgm9a071m7kjb8fllcilbn4wgrcf-stdenv-darwin/setup: line 164: 88837 Abort trap: 6           ar -cqs $libv8/lib/libv8.a @files
/nix/store/6lqprgm9a071m7kjb8fllcilbn4wgrcf-stdenv-darwin/setup: line 155: pop_var_context: head of shell_variables not a function context
```

**Pull request merged**
