### PR TITLE
bcachefs-tools: 1.7.0 -> 1.7.0-unstable-2024-05-09

### LINKED ISSUE #313350: cannot mount bcachefs from lvm raid0 device
### Describe the bug

I have an LVM setup, and I've been trying out bcachefs by using it as scratch space (since it's stuff I don't mind losing) on an LVM RAID0 volume with 4 stripes. Since #304761 updated `bcachefs-tools` to 1.7.0 I can't mount this, but switching back to a previous generation with `bcachefs-tools` 1.4.1 or using `bcachefs-tools` 1.3.3 from nixos-23.11 lets me mount it just fine. Using a linear volume instead also works fine.

### Steps To Reproduce
1. Create an LV with `-t raid0 --stripes 2`
2. Create a bcachefs filesystem on the new LV
3. Try to mount the new filesystem

Running `bcachefs mount` with `-v` results in:

```
INFO - bcachefs::commands::cmd_mount: mounting with params: device: /dev/dm-38:/dev/dm-40, target: /mnt, options: 
DEBUG - bcachefs::commands::cmd_mount: parsing mount options: 
INFO - bcachefs::commands::cmd_mount: mounting bcachefs filesystem, /mnt
INFO - bcachefs::commands::cmd_mount: mounting filesystem
ERROR - bcachefs::commands::cmd_mount: Fatal error: Device or resource busy
```

### Expected behavior

Should mount correctly. Output from bcachefs-tools 1.3.3:

```
INFO - bcachefs_rust::cmd_mount: mounting with params: device: /dev/vg/test, target: /mnt, options: 
DEBUG - bcachefs_rust::cmd_mount: parsing mount options: 
INFO - bcachefs_rust::cmd_mount: mounting bcachefs filesystem, /mnt
INFO - bcachefs_rust::cmd_mount: mounting filesystem
INFO - bcachefs_rust::cmd_mount: Successfully mounted
```

### Additional context

I don't know enough about Linux FS implementations, but suspect it might be an instance of https://github.com/koverstreet/bcachefs-tools/issues/260

### Notify maintainers

@davidak @JohnRTitor @Madouura 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.1, NixOS, 24.05 (Uakari), 24.05.20240519.6c0b7a9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0-beta.1-lixpre20240506-b6799ab`
 - channels(jez): `""`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/store/r8nhgnkxacbnf4kv8kdi8b6ks3k9b16i-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by JohnRTitor**
## Description of changes

- Fixes #313350 , which affects LVM users (unencrypted) who can not mount a bcachefs volume.
- Also vendor the updated patch added in #310504, which affects encrypted partition mounting on boot
- Moved to `pkgs/by-name`

## Things done

- [x] Reviewed changelog https://github.com/koverstreet/bcachefs-tools/compare/v1.7.0...3ac510f6a41feb1b695381fa30869d557c00b822
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

CC @jezcope @codebam @reedriley for testing

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by JohnRTitor** [comment]
@ofborg build bcachefs-tools
@ofborg test bcachefs-tools.passthru.tests

**Comment by jezcope** [comment]
@JohnRTitor Seems to work for me:

```
❯ bcachefs version
1.7.0-unstable-2024-05-09
```

and everything is mounted correctly. Thanks! 👍🏻

**Comment by JohnRTitor** [comment]
@ofborg build bcachefs-tools

**Comment by JohnRTitor** [comment]
@ofborg build bcachefs-tools

**Comment by alyssais** [comment]
We can't backport whatever patch fixes the bug?  Generally we prefer not to use non-release versions of packages.

**Comment by JohnRTitor** [comment]
I am not sure which commit specifically fixes that. 

Also commits like these fix a bug that throws error messages at boot involving scanning other non-bcachefs filesystems.
Screenshot_20240525-174351_Chrome


I have reviewed the changelog and the changes are pretty harmless bug fixes, also daily driving this as we speak. 

That's why I decided to move to to a unstable commit without substantial changes.

**Pull request merged**
