### PR TITLE
git: 2.18.0 -> 2.19.0

### PR DESCRIPTION
**Pull request by thefloweringash**
###### Motivation for this change

Package update. PR is based on and aimed at staging due to the large number of packages affected.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
LGTM.

I too saw the t5562 failure, and with your patchshebang this seems to work for me--and when using musl.

I'd like to re-confirm all the test special-cases for musl but I can't do that right away and can submit any changes in a later PR when I get to it.

Thanks!

**Comment by xeji** [comment]
@GrahamcOfBorg build gitAndTools.gitFull

**Comment by xeji** [comment]
let's see if at least "normal" git builds on darwin without a timeout
@GrahamcOfBorg build git

**Comment by xeji** [comment]
Hm, I don't understand what's wrong with aarch64.

**Comment by thefloweringash** [comment]
I've done a few runs of `nix-build . --check -A git` on aarch64 and I haven't been able to reproduce that failure.

**Comment by xeji** [comment]
Good enough, thanks! Let's merge and observe on Hydra.

**Comment by thefloweringash** [comment]
`git.aarch64-linux` passed on hydra as [build 81757777][].
`gitFull.aarch64-linux` is still queued as [build 81746040][].

[build 81757777]: https://hydra.nixos.org/build/81757777
[build 81746040]: https://hydra.nixos.org/build/81746040

**Pull request merged**
