### PR TITLE
binutils: 2.35.1 -> 2.37

### PR DESCRIPTION
**Pull request by TredwellGit**
###### Motivation for this change
https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob_plain;f=binutils/NEWS;hb=refs/tags/binutils-2_36_1
https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob_plain;f=gas/NEWS;;hb=refs/tags/binutils-2_36_1
https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob_plain;f=ld/NEWS;hb=refs/tags/binutils-2_36_1

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TredwellGit** [comment]
@vcunat, please make a Hydra jobset for this.

**Comment by vcunat** [comment]
I see nothing risky in the linked NEWS, but still I don't think there's enough motivation to rush it into 21.05.  Anyway, `x86_64-linux` is idle on Hydra now, so why not have a look: https://hydra.nixos.org/jobset/nixpkgs/binutils-2.36

**Comment by TredwellGit** [comment]
https://hydra.nixos.org/eval/1662081?compare=1661784#tabs-now-fail

**Comment by alyssais** [comment]
This should target staging, right?

**Pull request closed without merging**
