### PR TITLE
radare2: 1.4.0 -> 1.5.0

### PR DESCRIPTION
**Pull request by armijnhemel**
###### Motivation for this change

new version

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
there are two broken symlinks in the radare package:

```
r2-docker -> /build/radare2-1.5.0/sys/r2-docker.sh
r2-indent -> /build/radare2-1.5.0/sys/indent.sh
```

**Comment by armijnhemel** [comment]
Odd. I build on Fedora 25 and then those symlinks aren't even created when building with Nix, so I missed them. It seems a fairly recent addition (pre-1.4.0).

**Comment by Mic92** [comment]
I built it with the pre-release version of nix. This version is also used on hydra.

**Comment by armijnhemel** [comment]
Right.

The radare2 Makefile says:

        ln -fs "${PWD}/sys/indent.sh" "${DESTDIR}${BINDIR}/r2-indent"
        ln -fs "${PWD}/sys/r2-docker.sh" "${DESTDIR}${BINDIR}/r2-docker"

so I guess that is where it goes wrong.

**Comment by Mic92** [comment]
You can make a patch to copy both scripts instead and sent it also to upstream. This should be never the correct way to install those scripts. If the scripts are only required for development, they can be removed as well.

**Pull request closed without merging**
