### PR TITLE
logseq: 0.9.20 -> 0.10.0

### PR DESCRIPTION
**Pull request by shanesveller**
## Description of changes

https://github.com/logseq/logseq/releases/tag/0.10.0

## Things done

This was my first time trying out `nixpkgs-update` - please let me know if there are any mistakes or gotchas I should be aware of, so I can do better going forward.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by shanesveller** [comment]
Result of `nixpkgs-review pr 272126` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>logseq</li>
  </ul>
</details>

**Comment by shanesveller** [comment]
I'm not able to immediately confirm the update is working as intended. I haven't bisected it further, but my NixOS environment broke for running Logseq somewhere between 2023-11-24 and 2023-12-01, and so my NixOS build using the `nixos-23.11` input is not able to successfully run Logseq, whether or not it includes these changes. I get a miscolored window that doesn't render text or properly display UI elements, but seems to have the correct background and react to some keyboard inputs.

I'll take it out of draft in case a reviewer is not affected by my issues.

**Review by NickCao — APPROVED** [review]
It works correctly for me (on sway, both wayland and xwayland).

**Comment by NickCao** [comment]
>  I get a miscolored window that doesn't render text or properly display UI elements, but seems to have the correct background and react to some keyboard inputs.

This could be related to https://github.com/NixOS/nixpkgs/issues/244742

**Comment by shanesveller** [comment]
> This could be related to #244742

That definitely sounds plausible, thanks very much for the pointer! 🍻

**Comment by jontyms** [comment]
>  I get a miscolored window that doesn't render text or properly display UI elements, but seems to have the correct background and react to some keyboard inputs.
> 

I deleted the files in  ```~/.config/Logseq/GPUCache``` and it started working

**Pull request merged**
