### PR TITLE
signal-desktop: 6.5.1 -> 6.6.0, signal-desktop-beta: 6.6.0-beta.1 -> …

### PR DESCRIPTION
**Pull request by equirosa**
…6.7.0-beta.1

###### Description of changes
New updates:
- Signal Desktop: 
  - https://github.com/signalapp/Signal-Desktop/releases/tag/v6.6.0
  - https://github.com/signalapp/Signal-Desktop/releases/tag/v6.7.0
- Signal Desktop Beta:
  - https://github.com/signalapp/Signal-Desktop/releases/tag/v6.7.0-beta.1
  - https://github.com/signalapp/Signal-Desktop/releases/tag/v6.8.0-beta.1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by kilianar — APPROVED** [review]
Result of `nixpkgs-review pr 217292` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>signal-desktop</li>
    <li>signal-desktop-beta</li>
  </ul>
</details>

---

For your interest, version [v6.8.0-beta.1](https://github.com/signalapp/Signal-Desktop/releases/tag/v6.8.0-beta.1) has just been released.

**Comment by equirosa** [comment]
Didn't realize this hadn't been merged in yet :sweat_smile: I'll go ahead and update this PR to the newest versions :grin:

**Comment by kilianar** [comment]
Thank you for updating! It still builds and runs perfectly.

**Comment by Zahrun** [comment]
LGTM

**Comment by kilianar** [comment]
In the meantime, there have been new releases, so you may want to consider bumping up the version once again :)

**Comment by equirosa** [comment]
On it :D

**Comment by kilianar** [comment]
Here we go again, version [v6.9.0](https://github.com/signalapp/Signal-Desktop/releases/tag/v6.9.0) was released today

**Comment by roberth** [comment]
Looks like ofborg doesn't ping anyone for signal-desktop? I don't know if this is rare, or always happens for this package, but probably a good idea to ping manually for signal-desktop updates. Based on `meta` that'd be:

@mic92 @equirosa @urandom, please review

**Comment by SuperSandro2000** [comment]
Probably because the commit messages don't fit the contributing guide.

**Pull request merged**
