### PR TITLE
nikto: 2.2.0 -> 2.5.0

### PR DESCRIPTION
**Pull request by happysalada**
## Description of changes

I'm going to need a bit of help to get this over the finish line.

here is what I did
- took the latest commit from nikto 2.5.0 branch https://github.com/sullo/nikto/tree/nikto-2.5.0/program
- fixed the patch, and removed the line that installs removed documentation.

however I still get this error
```
ERROR: Can't locate Net/SSLeay.pm in @INC (you may need to install the Net::SSLeay module) (@INC entries checked: /nix/store/khyv1jr3g7246bs87dqfy8ba0ica4fbm-perl-5.38.0/lib/perl5/site_perl/5.38.0/darwin-thread-multi-2level /nix/store/khyv1jr3g7246bs87dqfy8ba0ica4fbm-perl-5.38.0/lib/perl5/site_perl/5.38.0 /nix/store/khyv1jr3g7246bs87dqfy8ba0ica4fbm-perl-5.38.0/lib/perl5/5.38.0/darwin-thread-multi-2level /nix/store/khyv1jr3g7246bs87dqfy8ba0ica4fbm-perl-5.38.0/lib/perl5/5.38.0) at (eval 21) line 1.
BEGIN failed--compilation aborted at (eval 21) line 1.
```

I tried moving propagatedBuildInputs (which sounds like correct) to buildinputs to try to match other packages using ssleay.pm, but this didn't fix the problem.

any pointers would be appreciated!

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by happysalada** [comment]
@bjornfor just in case you can help, since I saw you are a maintainer of a package using perl as well (another network analysis tool).

**Comment by AkechiShiro** [comment]
Did a `nixpkgs-review`, it looks all good, how did you trigger the error you're mentioning ? Are you running on NixOS or running Nix under a non NixOS Linux distro?
```
┏━ Dependency Graph with 2 roots:
┃ ✔︎ source 
┃    ┌─ ⏳︎ source
┃ ┌─ ✔︎ nikto-2.5.0 
┃ ✔︎ review-shell 
┣━━━ Builds          
┗━ ∑︎ ⏵︎ 0 │ ✔︎ 3 │ ⏳︎ 1 │ Finished at 03:17:40 after 3s

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/269949

1 package built:
```

I also tested the binary functionality, it did work, thanks for your PR @happysalada 

```
- Nikto v2.5.0
---------------------------------------------------------------------------
+ ERROR: No host (-host) specified
```

**Comment by happysalada** [comment]
@AkechiShiro thank you for your testing! I'm running on darwin, I triggered the problem by just doing a --help.
Good to know that it's running on linux.
I'm going to wait a couple of days to see if anyone has a fix for this, but otherwise I'll merge this.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 269949` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>nikto</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Works for me on x86-64 as well.

```bash
...ew/pr-269949-1]$ ./results/nikto/bin/nikto -h 192.168.1.1
- Nikto v2.5.0
---------------------------------------------------------------------------
+ Target IP:          192.168.1.1
+ Target Hostname:    192.168.1.1
+ Target Port:        80
+ Start Time:         2023-11-26 10:31:50 (GMT1)
---------------------------------------------------------------------------
+ Server: No banner retrieved
[...]
``

**Comment by happysalada** [comment]
I don't have a response from upstream. 
Given that the releases are multiple years appart and that 2.5.0 is still in a branch state, I've called this pre-2.5.0 just to clarify that 2.5.0 isn't merged yet.
2.5.0 contains breaking changes, so I would rather make the upgrade now so we get the break in unstable to have plenty of time to test before next 24.05 nixpkgs release.
open to feedback on this of course.

**Comment by happysalada** [comment]
There was a new commit on the 2.5.0 branch. This makes me think its better to wait some more for a potential reponse of the maintainers or a merge of the branch.

**Comment by happysalada** [comment]
2.5.0 was just released https://github.com/sullo/nikto/releases/tag/2.5.0
I've just tested on darwin and it's working too.
(unless there is strong feedback, I plan to merge this in 24h).

**Pull request merged**
