### PR TITLE
texlive: make updmap actually regenerate (#76826)

### LINKED ISSUE #76826: TeXLive 2019 .enc vs. pdftex.map inconsistency with ebgaramond
**Describe the bug**
The .enc files distributed with the ebgaramond package are inconsistent with those mentioned in `pdftex.map`.

**To Reproduce**
1. pdflatex this:

    \documentclass{article}

    \usepackage{ebgaramond}

    \begin{document}
    foo
    \end{document}

**Expected behavior**
Produces PDF output.

**Screenshots**
Instead produces:

    !pdfTeX error: /Users/sperber/.nix-profile/bin/pdflatex (file ebgm_nxqm35.enc): cannot open encoding file for reading
     ==> Fatal error occurred, no output PDF file produced!

**Additional context**

In today's Nix packages from Git.

The `ebgm_nxqm35.enc` file is mentioned in `pdftex.map`:

    EBGaramond-Bold-osf-ot1 EBGaramond-Bold " AutoEnc_nxqm357krn5asjgj4l52s7fwme ReEncodeFont " <[ebgm_nxqm35.enc <EBGaramond-Bold.pfb

However, `EBGaramond.map` has this:

    EBGaramond-Bold-osf-ot1 EBGaramond-Bold "AutoEnc_fc2mbn3xtktdfxsxdv3khcb5dh ReEncodeFont" <[ebgm_fc2mbn.enc <EBGaramond-Bold.pfb

I'd be happy to help formulate a patch here, but need handholding as to where to start looking how `pdftex.map` is generated.

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.2.0, macOS 10.15.2`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.1`
 - channels(sperber): `"nixpkgs-16.03pre70724.d4bebcb"`
 - nixpkgs: `/Users/sperber/build/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by mikesperber**
The --syncwithtrees flag made updmap not regenerate the map files,
effectively leaving stale map files in place.

###### Motivation for this change

Closes: #76826

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @veprbl

### CODE REVIEW

**Comment by veprbl** [comment]
Does "updmap --sys" include the operation of "updmap --sys −−syncwithtrees"? If not, this may break schemes smaller than scheme-full.

**Comment by mikesperber** [comment]
I'm not sure what that operation is: The effect I observed is that is causes no map file to be written, leaving the one from the distribution in place.

From the documentation, it seems that the effect *should* be that it removes entries in `pdftex.map` in place where the corresponding map file can't be found. But AFAICS, it doesn't remove (or add or change) anything, so the issue is moot: Either I'm misunderstanding what the flag is supposed to do, or there's a bug with `updmap`.

In any case, I don't see any harm leaving entries in the map file for fonts that are not in the package - after all, you can't create references to these entries if the corresponding package isn't there.

PS: Thanks for looking a this!

**Comment by veprbl** [comment]
@GrahamcOfBorg build texlive.combined.scheme-small

**Comment by veprbl** [comment]
@mikesperber It breaks `texlive.combined.scheme-small`.

**Comment by mikesperber** [comment]
Ah, I see now: `--syncwithtrees` only updates the config files, prevents the map files from being generated. Just updated the pull request and checked that `texlive.combined.scheme-small`. (Sorry about the intermediate breakage.)

**Comment by veprbl** [comment]
@GrahamcOfBorg build texlive.combined.scheme-small
@GrahamcOfBorg build texlive.combined.scheme-full

**Review by veprbl — APPROVED** [review]

**Comment by veprbl** [comment]
I guess, the original issue was caused by an inconsistency in the snapshot that we are using.

**Comment by mikesperber** [comment]
Many thanks!

**Pull request merged**
