### PR TITLE
bitwarden-desktop: 2024.9.0 -> 2024.10.2

### PR DESCRIPTION
**Pull request by bobvanderlinden**
Changelog:
https://bitwarden.com/help/releasenotes/#2024-10-2

The build failed because of electron-builder copying the electron binary to the build. This happened before this version as well, but now an `after-pack.js` script is introduced that uses `flipFuses` to alter the binary (see https://github.com/bitwarden/clients/blob/5842200084dca0e8653953afb787fa8e703c9edb/apps/desktop/scripts/after-pack.js#L132C9-L132C18 and https://www.electronjs.org/docs/latest/tutorial/fuses).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by itepastra** [comment]
--------- Report for 'x86_64-linux' ---------
1 package built:
bitwarden-desktop

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 353215`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>bitwarden-desktop</li>
  </ul>
</details>

**Review by amarshall — CHANGES_REQUESTED** [review]
This version of bitwarden may be unfree, see https://github.com/bitwarden/clients/issues/11611. Unfortunately they also made it quite difficult to determine the provenance of an NPM release (see [issue](https://github.com/bitwarden/sdk-internal/issues/12)). The first NPM release with its bundled LICENSE file as GPL is 0.2.0-main.2 (see [src](https://www.npmjs.com/package/@bitwarden/sdk-internal/v/0.2.0-main.2?activeTab=code)), but I think that some earlier ones may also be and they were copying the wrong license file to the NPM build.

Either way, I think it’s prudent to wait till the next release which more unambiguously does not include unfree dependencies.

**Review by dotlambda — COMMENTED** [review]
Package name is `bitwarden-desktop`. Please squash.

**Comment by dotlambda** [comment]
In https://github.com/bitwarden/clients/issues/11611 people talk about sanitizing node_modules. Should we do the same?

**Comment by gepbird** [comment]
Merge conflict caused by https://github.com/NixOS/nixpkgs/pull/339384

https://github.com/bitwarden/clients/releases/tag/desktop-v2024.11.0 got released

**Comment by itepastra** [comment]
Since you've already made a newer pr I think we should close this one

**Comment by bobvanderlinden** [comment]
Thanks for the new PR :+1:

**Pull request closed without merging**
