### PR TITLE
capability: unbreak

### PR DESCRIPTION
**Pull request by cideM**
###### Motivation for this change

The package compiles and works just fine without any additional changes.

I created a tiny Cabal project that uses the library and just prints something and it works perfectly well. I'm also using it in a little Haskell side project and here too, with `NIXPKGS_ALLOW_BROKEN=1` it works.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cideM** [comment]
yikes, sorry forgot about that

**Comment by sternenseemann** [comment]
Cherry picked on top of `haskell-updates`, thank you! <https://github.com/NixOS/nixpkgs/pull/118350/commits/8fa0c918da65a732864daea213fa3bdd77a8fd54>.

**Comment by cideM** [comment]
Wow this was fast, thanks and sorry again about the incorrect base :see_no_evil:

**Pull request closed without merging**
