### PR TITLE
luaformatter: init at 1.3.4

### PR DESCRIPTION
**Pull request by figsoda**
###### Motivation for this change

luaformatter is a code formatter for lua.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
have you tried adding it to the list of generated lua packages ? that way updates could be automated 
https://github.com/Koihik/LuaFormatter/blob/master/luaformatter-scm-1.rockspec

**Comment by figsoda** [comment]
> have you tried adding it to the list of generated lua packages ? that way updates could be automated
> https://github.com/Koihik/LuaFormatter/blob/master/luaformatter-scm-1.rockspec

I haven't. I am not familiar with lua and luarocks, so I never tried it. This only contains c++ code, so for now this should work. If any one can help packaging as a lua package, that would be great!

**Comment by teto** [comment]
there are some issues with cmake and the nixpkgs lua infrastructure so it may actually be better to have it packaged like this for now. I could start the binary just fine.

**Review by teto — APPROVED** [review]

**Comment by figsoda** [comment]
Any chance this gets merged?

**Pull request merged**
