### PR TITLE
jabba: easy access to various JDK versions

### PR DESCRIPTION
**Pull request by raboof**
###### Motivation for this change

As a developer it can sometimes be helpful to test/run code on a variety of different JDK variants and versions. Typically distributions ship only a few
variants/versions, and you'd rely on a tool like jabba or sdkman to install specific different ones. Now those tools are not very 'nix-like'.

This PR introduces a more 'nix-like' way of downloading and installing the binary JDK distributions offered by 'jabba'.

You can install one, for example, with `nix-shell -p "jabba.adopt.\"1.13.0-2\""`.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by taku0** [comment]
It doesn't run GUI applications: https://github.com/taku0/JavaSample/blob/master/JavaSample.java

**Comment by raboof** [comment]
> It doesn't run GUI applications: https://github.com/taku0/JavaSample/blob/master/JavaSample.java

Thanks! I added patchelf invocations to correctly link the X11 libraries - now the example starts, but doesn't work correctly yet (something around finding fonts)

**Comment by taku0** [comment]
It seems that there are more libraries JDK depends on: `pkgs/development/compilers/zulu/default.nix`.  It also set `JAVA_HOME` and `CLASSPATH`.

`adoptopenjdk-bin` (`pkgs/development/compilers/adoptopenjdk-bin/jdk-linux-base.nix`) also set `passthru.jre` and `passthru.home`.  Some packages depend on the variables. It also states a problem of `freetype` on Raspberry Pis (#57733).

**Comment by jerith666** [comment]
I think https://lazamar.co.uk/nix-versions/?channel=nixpkgs-unstable&package=openjdk already achieves something pretty close to what you want here. Obviously we can't go back in time to add versions that were missed, but over time it should get better.  I don't think it makes sense to keep all these versions at the tip of nixpkgs forever.

**Comment by raboof** [comment]
Abandoning this PR, doing this out-of-tree in https://git.sr.ht/~raboof/nix-jabba

**Pull request closed without merging**
