### PR TITLE
nixpkgs: build aarch64-linux

### PR DESCRIPTION
**Pull request by grahamc**
cc @dezgeg @edolstra 

I figure we'll start with nixpkgs and expand to NixOS afterwards.

### CODE REVIEW

**Comment by fpletz** [comment]
We also need a build machine for hydra if we merge this PR or those builds will stay in the queue. Can we get this done simultaneously?

**Comment by grahamc** [comment]
https://hydra.nixos.org/machines https://hydra.nixos.org/machines

**Comment by fpletz** [comment]
Oh, nevermind. Thanks a lot. :+1:

**Comment by c0bw3b** [comment]
The beast won't be idle anymore!

**Comment by domenkozar** [comment]
Looks good to me (code-wise). What's missing? :)

**Comment by edolstra** [comment]
Hm, it's giving eval errors apparently for all aarch64 jobs:
```
in job ‘icecast.aarch64-linux’:
evaluation aborted with the following error message: ‘unsupported system type: aarch64-linux’
...
```
https://hydra.nixos.org/jobset/nixpkgs/trunk/#tabs-errors

This is odd because the patchelf jobset evaluated fine with an aarch64 job: http://hydra.nixos.org/build/49825197

**Comment by domenkozar** [comment]
We also need to update `pkgs/top-level/release-lib.nix`

**Comment by FRidh** [comment]
This has been merged 11 days ago but one of the jobs, Thunderbird, hasn't actually ever been build successfully. It's nice having aarch64 support but I don't think aarch64 builds should block any of the channels. There's too few people having such systems / the possibility to fix issues.

**Comment by grahamc** [comment]
Certainly not my intention. I'm sorry. Can we still build it, but not
depend on it passing?

**Comment by dezgeg** [comment]
Done in 93446a20600cd3b6c19182ea3f653a1ea2b2d305.

**Pull request merged**
