### PR TITLE
fpm: fix vulnerable dependency (for 16.09)

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

Further to #22374, thanks @joachifm

Only tested on unstable.

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
Picked to release at https://github.com/NixOS/nixpkgs/commit/82a6c831f68e98951f1f7ad6dd815d0cec258645

**Comment by peterhoeg** [comment]
@joachifm, thanks, but I edited Gemfile.lock to adjust the bundler version so that there are no complaints from bundler.

**Comment by joachifm** [comment]
So it's not a cherry-pick? I can revert & apply this instead, but please do mention stuff like that in the future :)

**Comment by peterhoeg** [comment]
It was not a cherry-pick, no, that's why I opened a separate PR with a different commit. The difference is a warning by bundler, but no errors as such.

**Comment by joachifm** [comment]
Well, people open new PRs without remembering to do do `cherry-pick -x` quite often, so ...

**Comment by peterhoeg** [comment]
> people open new PRs without remembering to do do cherry-pick -x

That would include me it seems... ;-) Thanks for handling this!

**Comment by joachifm** [comment]
:)

**Pull request closed without merging**
