### PR TITLE
maintainers: add pbsbot

### PR DESCRIPTION
**Pull request by pbsds**
## Description of changes

I want to experiment with a bot that is able to change labels on github.
However I do not want to put a commit bit access key in `/run/secrets`, hence why i am reviving this old bot account @pbsbot i made a long time ago.

How to and whether to differentiate this entry as a bot and not a human is discussable. I've considered adding a team:

```patch
--- a/maintainers/team-list.nix
+++ b/maintainers/team-list.nix
@@ -94,6 +94,14 @@ with lib.maintainers;
     shortName = "Blockchains";
   };
 
+  bot-accounts = {
+    members = [
+      pbsbot
+    ];
+    scope = "Bot accounts that interact with nixpkgs, may be user-run.";
+    shortName = "Bots";
+  };
+
   budgie = {
     members = [
       bobby285271
```

or extending the `lib.maintainers` schema

```patch
--- a/lib/tests/maintainer-module.nix
+++ b/lib/tests/maintainer-module.nix
@@ -22,6 +22,10 @@ in {
       type = types.nullOr types.ints.unsigned;
       default = null;
     };
+    isBot = lib.mkOption {
+      type = types.bool;
+      default = false;
+    };
     keys = lib.mkOption {
       type = types.listOf (types.submodule {
         options.fingerprint = lib.mkOption { type = types.str; };
```

But feel like doing neither for such a silly thing.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
Maybe you could just inline `{ github = …; githubId = …; }` into `team-list.nix` to avoid adding it to the main maintainers list? I don’t know if that’d work with the automation or not.

**Comment by Aleksanaa** [comment]
> I want to experiment with a bot that is able to change labels on github.

Wait, so why do you have to add the bot to maintainer list? Even @r-ryantm isn't there. Your bot is also unable to fulfill the expectations of a general maintainer, like replying to related issues, help find the cause/workaround of bugs, etc

**Comment by pbsds** [comment]
I only want the permissions to modify labels on github. @\pbsbot was initially added to the github maintainers-list team manually, but was within the hour removed again due to some automation.
@\NixOSInfra has essentially the setup i want, but asking how that worked on matrix proved ineffective.

**Comment by Aleksanaa** [comment]
@lassulus could we add a "bots" team or something?

**Comment by Lassulus** [comment]
bots team sgtm, I would like to have the repo of the bot linked next to the maintainers entry if possible?

**Comment by drupol** [comment]
Related: https://github.com/NixOS/nixpkgs/pull/350640

**Comment by pbsds** [comment]
Due to a change in time availability Im going to have to shelve this project

**Comment by pbsds** [comment]
Still, an index over the apps and user accounts with access to nixpkgs should be made IMO. The various bots infinisil recently have made should also be listed

**Pull request closed without merging**
