### PR TITLE
{terminology,ephoto,rage,econnman}: wrap libcurl.so in LD_LIBRARY_PATH

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

EFL applications depend on `libcurl.so`. Although `efl` has `curl` on `propagatedBuildInputs`, and these packages have `efl` on `buildInputs`, when the applications are run they give error messages about `libcurl.so` not being found. For instance:
```
$ terminology 
ERR<18518>:ecore_con lib/ecore_con/ecore_con_url_curl.c:288 _c_init() Could not find libcurl.so.5, libcurl.so.4
```

`libcurl.so` is not listed by `ldd`, though:
```
$ ldd $(readlink -f $(which terminology)) | grep -i curl
$
```

Explicitly adding the directory containing `libcurl.so` to `LD_LIBRARY_PATH` fixes this issue.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vbgl** [comment]
Why is it a problem that curl is not available? It seems that these programs work fine without curl.

**Comment by romildo** [comment]
> Why is it a problem that curl is not available? It seems that these programs work fine without curl.

@vbgl I have asked on the `e-users` mailing list and the [answer](https://sourceforge.net/p/enlightenment/mailman/message/35948751/) is:

>> When running terminology (and also ephoto, rage and econnman) on NixOS,
>> I am getting a missing library dependency message about libcurl.so:
>> 
>>     $ terminology 
>>     ERR<18518>:ecore_con lib/ecore_con/ecore_con_url_curl.c:288 _c_init()
>> Could not find libcurl.so.5, libcurl.so.4
>> 
>> libcurl.so is not listed by ldd, though:
>> 
>>     $ ldd $(readlink -f $(which terminology)) | grep -i curl
>>     $
> 
> because we runtime link it by hand in code (dlopen it)
> 
>> See https://github.com/NixOS/nixpkgs/pull/25412 for more details.
>> 
>> Is libcurl really needed for terminology?
> 
> it's how it does gravatars when you mouse over an email address, and how when
> you click on a url to a video file. image etc. it will download it itself and
> display it... so yes - it's needed for such feature to work. otherwise they
> will fail.

Therefore in order to get full functionality, the dependency is needed.

**Comment by vbgl** [comment]
Thanks for investigating. `terminology` looks an amazing software ؟

**Pull request merged**
