### PR TITLE
lieer: 1.1 -> 1.2

### PR DESCRIPTION
**Pull request by flokli**
###### Motivation for this change
`gmi send` supporting `-t`, thus being compatible with neomutt (https://github.com/gauteh/lieer/pull/154)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
Updated to fetch the sources from PyPI, as they're published now too (https://github.com/gauteh/lieer/pull/138#issuecomment-633183424).

@kirelagin, can you take a look?

**Comment by kirelagin** [comment]
I once tried to add a new Python package, and someone [suggested](https://github.com/NixOS/nixpkgs/pull/59609#issuecomment-486969738) that I use GitLab instead of PyPi. I’m not sure what the policy in nixpkgs currently is, but the argument that the source repository is usually more up-to-date than PyPi sounds justified...

**Review by kirelagin — APPROVED** [review]

**Comment by flokli** [comment]
We prefer to fetch from git when tests are missing from the PyPI releases, but usually, PyPI is the more canonical location.

As lieer doesn't have tests, we don't need to worry about missing tests :see_no_evil: 

https://github.com/gauteh/lieer/pull/138 reads like PyPI should soon be always up to date on releases, but I'll ask back.

**Comment by flokli** [comment]
Let's merge this in fetching from PyPI for now, we can always flip it back to GitHub, if it turns out to be better there ;-)

**Comment by flokli** [comment]
moved back to `fetchFromGitHub` in 2226972c7a76e947c8882558fe51288fb83709b7.

**Pull request merged**
