### PR TITLE
osu-lazer: 2023.305.0 -> 2023.403.1

### PR DESCRIPTION
**Pull request by stepbrobd**
###### Description of changes

`osu-lazer`:
```diff
diff --git a/pkgs/games/osu-lazer/default.nix b/pkgs/games/osu-lazer/default.nix
index 1de04bc06b9..1c6a51c434f 100644
--- a/pkgs/games/osu-lazer/default.nix
+++ b/pkgs/games/osu-lazer/default.nix
@@ -17,13 +17,13 @@

 buildDotnetModule rec {
   pname = "osu-lazer";
-  version = "2023.305.0";
+  version = "2023.326.1";

   src = fetchFromGitHub {
     owner = "ppy";
     repo = "osu";
     rev = version;
-    sha256 = "sha256-gkAHAiTwCYXTSIHrM3WWLBLbC7S9x1cAaEhSYvtNsvQ=";
+    sha256 = "sha256-hPSoKirp4fAuzewCBlqp0UJrVdFD2pMmikXx9VyvD4o=";
   };
```

`osu-lazer-bin`:
```diff
diff --git a/pkgs/games/osu-lazer/bin.nix b/pkgs/games/osu-lazer/bin.nix
index 20d09d83a09..cde0800130a 100644
--- a/pkgs/games/osu-lazer/bin.nix
+++ b/pkgs/games/osu-lazer/bin.nix
@@ -7,21 +7,21 @@

 let
   pname = "osu-lazer-bin";
-  version = "2023.305.0";
+  version = "2023.326.1";
   name = "${pname}-${version}";

   osu-lazer-bin-src = {
     aarch64-darwin = {
       url = "https://github.com/ppy/osu/releases/download/${version}/osu.app.Apple.Silicon.zip";
-      sha256 = "sha256-nL5j0b4vD/tTYPPBLiMxiPWLHnP5hqco0DJ+7EZRSZY=";
+      sha256 = "sha256-cMimN5yyqsVoJP11QxUD+zer360JsAYpxKIxd5UIlus=";
     };
     x86_64-darwin = {
       url = "https://github.com/ppy/osu/releases/download/${version}/osu.app.Intel.zip";
-      sha256 = "sha256-Er48BIzJlSzDaGb6IfhZoV62kj5GJ/rw9ifUw+ZCJkc=";
+      sha256 = "sha256-6UXIaldL4UAHZK8zy1Yxv0Sj9BFFKjVYqBO/iNS5xNE=";
     };
     x86_64-linux = {
       url = "https://github.com/ppy/osu/releases/download/${version}/osu.AppImage";
-      sha256 = "sha256-W3XJ7HtJM5iFI8OOTTu8IBHMerZSCETHMemkoTislK8=";
+      sha256 = "sha256-B30kokQWhJkZTCclOmJQpdsjP9USp2tH+mmJUTZfr08=";
     };
   }.${stdenv.system} or (throw "${pname}-${version}: ${stdenv.system} is unsupported.");
```

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 223324` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>osu-lazer</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>osu-lazer-bin</li>
  </ul>
</details>

**Comment by StepBroBD** [comment]
Thanks!
Any idea why `osu-lazer` is not building?
I was running the update.sh and the script returned no error.

**Comment by StepBroBD** [comment]
Result of `nixpkgs-review pr 223324` run on x86_64-linux (Debian):

2 packages updated:
* osu-lazer (2023.305.0 → 2023.403.0)
* osu-lazer-bin (2023.305.0 → 2023.403.0)

2 packages built:
* osu-lazer
* osu-lazer-bin

**Comment by StepBroBD** [comment]
Result of `nixpkgs-review pr 223324` run on x86_64-linux (Debian):

2 packages updated:
* osu-lazer (2023.305.0 → 2023.403.1)
* osu-lazer-bin (2023.305.0 → 2023.403.1)

2 packages built:
* osu-lazer
* osu-lazer-bin

**Comment by delan** [comment]
Sorry I can’t help this time, I have too much on my plate right now.

**Comment by oxalica** [comment]
`osu-lazer-bin` builds and works fine for me.

`osu-lazer` builds but segfaults once runs.

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 223324` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>osu-lazer</li>
    <li>osu-lazer-bin</li>
  </ul>
</details>

**Review by thiagokokada — APPROVED** [review]

**Comment by thiagokokada** [comment]
> `osu-lazer-bin` builds and works fine for me.
> 
> `osu-lazer` builds but segfaults once runs.

Both are working fine for me. Going to merge.

**Pull request merged**
