### PR TITLE
asciidoctor: 1.5.6.1 -> 1.5.6.2, also add mathematical and coderay

### PR DESCRIPTION
**Pull request by expipiplus1**
`asciidoctor-mathematical` requires a few system dependencies to compile,
and some of these are not linked correctly into the resulting shared
object, so these are handled manually.

`asciidoctor-mathematical` and `coderay` are necessary to compile the
vulkan specification documentation.

### CODE REVIEW

**Comment by zimbatm** [comment]
@GrahamcOfBorg build asciidoctor

**Comment by zimbatm** [comment]
@expipiplus1 can you fix the build for Darwin? no objection on the other changes.

**Comment by expipiplus1** [comment]
No problem, looks like a missing dependency on `patchelf`

**Comment by expipiplus1** [comment]
@GrahamcOfBorg build asciidoctor on Darwin

**Comment by expipiplus1** [comment]
@GrahamcOfBorg build asciidoctor

**Comment by zimbatm** [comment]
@expipiplus1 what happens if patchelf is missing, is asciidoctor still working unless that extension is being used?

Darwin uses Mach-O instead of ELF for executables so you could try `postFixup = lib.optionalString isLinux "..."`

**Comment by expipiplus1** [comment]
@zimbatm as long as one doesn't use the `asciidoctor-mathematical` plugin the it all works correctly. I think patching on Linux for now is fine, it's not any worse on OS X than before in terms of functionality.

**Comment by expipiplus1** [comment]
Done

**Comment by zimbatm** [comment]
@GrahamcOfBorg build asciidoctor

**Comment by expipiplus1** [comment]
Thanks @zimbatm!

**Pull request merged**
