### PR TITLE
Metasploit Update -- 3.3.1 -> 4.12.5 

### PR DESCRIPTION
**Pull request by endian0A**
###### Things done
- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by zimbatm** [comment]
It looks like the install process is trying to fetch from rubygems directly. Try using bundix and the bundlerEnv to pre-fetch those dependencies instead as it's going to break in the sandboxing.

```
fatal: Not a git repository (or any of the parent directories): .git
Fetching source index from https://rubygems.org/
Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Could not fetch specs from https://rubygems.org/
```

**Comment by endian0A** [comment]
I have tried to leverage bundleEnv and bundix several times, but I am _guessing_ that this is because bundix does not support gem grouping.  Patching this is out of the stock Gemfile  for every version of msf does not seem like fun... 

After researching this a little, it seems that bundix is not correctly generating my gemspec.nix file.  A local gem needs to be built from an included .gemspec file that is part of MSF.  Basically, bundix croaks with the following:

```
> bundix -d 

... 

Skipping metasploit-framework: unkown bundler source
/nix/store/95rivqawf6mppyaqk07pz094pplb5a5k-bundix-2.0.5/lib/ruby/gems/2.1.3/gems/bundix-2.0.5/lib/bundix/source.rb:11:in `convert'
/nix/store/95rivqawf6mppyaqk07pz094pplb5a5k-bundix-2.0.5/lib/ruby/gems/2.1.3/gems/bundix-2.0.5/lib/bundix.rb:47:in `convert_spec'
/nix/store/95rivqawf6mppyaqk07pz094pplb5a5k-bundix-2.0.5/lib/ruby/gems/2.1.3/gems/bundix-2.0.5/lib/bundix.rb:37:in `block in convert'
/nix/store/95rivqawf6mppyaqk07pz094pplb5a5k-bundix-2.0.5/lib/ruby/gems/2.1.3/gems/bundix-2.0.5/lib/bundix.rb:36:in `reverse_each'
/nix/store/95rivqawf6mppyaqk07pz094pplb5a5k-bundix-2.0.5/lib/ruby/gems/2.1.3/gems/bundix-2.0.5/lib/bundix.rb:36:in `with_object'
/nix/store/95rivqawf6mppyaqk07pz094pplb5a5k-bundix-2.0.5/lib/ruby/gems/2.1.3/gems/bundix-2.0.5/lib/bundix.rb:36:in `convert'
/nix/store/95rivqawf6mppyaqk07pz094pplb5a5k-bundix-2.0.5/lib/ruby/gems/2.1.3/gems/bundix-2.0.5/bin/bundix:36:in `<top (required)>'
/home/matt/.nix-profile/bin/bundix:14:in `load'
/home/matt/.nix-profile/bin/bundix:14:in `<main>'

```

And obviously only generates this for the msf gem:

```
  metasploit-framework = {
    dependencies = ["actionpack" "activerecord" "activesupport" "bcrypt" "filesize" "jsobfu" "json" "metasm" "metasploit-concern" "metasploit-credential" "metasploit-model" "metasploit-payloads" "metasploit_data_models" "msgpack" "network_interface" "nokogiri" "octokit" "openssl-ccm" "packetfu" "patch_finder" "pcaprub" "pg" "railties" "rb-readline-r7" "recog" "redcarpet" "robots" "rubyzip" "sqlite3" "tzinfo" "tzinfo-data"];
  };

```

**Comment by zimbatm** [comment]
Last time I tired it didn't support the "gemspec" directive so that might be the issue. bundlerEnv also doesn't support gemspec or path dependencies. If only it was published on rubygems.org, then it would be easy...

**Comment by Mic92** [comment]
You can work around that by creating a new Gemfile, where the only gem is the one you want to add.
If this gem is not on rubygems, you can also fetch it from git.

```
source "https://rubygems.org"

gem "yourgem"
```

**Comment by endian0A** [comment]
Thanks for the tip!

However, and if I remember this thread correctly, when building a package you cannot utilize gem fully as a manager when building a new package for NixOS.  The problem is that, at least at the time, gem dependancy resolution was really bad with NixOS.

Yep.  You can install anything that you want in any context, but if you actually build a package, most of the gem managers couldn't support the correct passing of build options.

Hope most of that is fixed by now as there are some very complex Ruby apps that needed to be built under very specific conditions.

I found where the build variables were getting dropped in the build process and coded around it.  Unless you really feel like patching MSF and dealing with core issues, please, give it your best shot and I can assist.



-------- Original message --------

**Comment by spacekitteh** [comment]
@grahamc security

**Comment by joachifm** [comment]
@endian0A are you still working on this?

**Pull request closed without merging**
