### PR TITLE
python3Packages.skytemple-dtef: 1.1.3 -> 1.1.4

### PR DESCRIPTION
**Pull request by sugar700**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126649` at 5510bbdf run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built successfully:</summary>
  <ul>
    <li>python38Packages.skytemple-dtef</li>
    <li>python39Packages.skytemple-dtef</li>
    <li>skytemple</li>
  </ul>
</details>

**Comment by risicle** [comment]
FWIW `skytemple-rust` could probably be fixed for macos by simply adding 

```
  ++ lib.optionals stdenv.isDarwin [ libiconv ]
```

to the `buildInputs`.

**Comment by xfix** [comment]
> FWIW `skytemple-rust` could probably be fixed for macos by simply adding
> 
> ```
>   ++ lib.optionals stdenv.isDarwin [ libiconv ]
> ```
> 
> to the `buildInputs`.

That seems reasonable, agreed, however I don't use macOS myself so I wouldn't be able to test such a change.

**Comment by ethancedwards8** [comment]
Result of `nixpkgs-review pr 126649` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>skytemple</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python38Packages.skytemple-dtef</li>
    <li>python39Packages.skytemple-dtef</li>
  </ul>
</details>

**Comment by ethancedwards8** [comment]
> > FWIW `skytemple-rust` could probably be fixed for macos by simply adding
> > ```
> >   ++ lib.optionals stdenv.isDarwin [ libiconv ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to the `buildInputs`.
> 
> That seems reasonable, agreed, however I don't use macOS myself so I wouldn't be able to test such a change, and it's not directly related to this pull request.

I'd be happy to test.

**Comment by SuperSandro2000** [comment]
> > FWIW `skytemple-rust` could probably be fixed for macos by simply adding
> > ```
> >   ++ lib.optionals stdenv.isDarwin [ libiconv ]
> > ```
> >   
> > to the `buildInputs`.
> 
> That seems reasonable, agreed, however I don't use macOS myself so I wouldn't be able to test such a change, and it's not directly related to this pull request.

risicle can test it and adding it won't hurt.

**Pull request merged**
