### PR TITLE
python311Packages.catppuccin: 1.3.2 -> 2.2.0, catppuccin-gtk: 0.7.1 -> 0.7.2

### PR DESCRIPTION
**Pull request by TomaSajt**
## Description of changes

This PR bumps the version of the `catppuccin` python package and `catppuccin-gtk` too.

Changes: https://github.com/catppuccin/python/compare/v1.3.2...v2.2.0
Changes: https://github.com/catppuccin/python/compare/v0.7.1...v0.7.2
\+ patch: https://github.com/catppuccin/gtk/commit/355e12387f73b27cf4734a6a3eb431554fabb74f

Release notes:
 - https://github.com/catppuccin/python/releases/tag/v2.0.0
 - https://github.com/catppuccin/python/releases/tag/v2.1.0
 - https://github.com/catppuccin/python/releases/tag/v2.2.0
 - https://github.com/catppuccin/gtk/releases/tag/v0.7.2

The tests were reworked, so we no longer need to disable a test.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by fufexan — APPROVED** [review]

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 290391` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>catppuccin-gtk</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.catppuccin</li>
    <li>python311Packages.catppuccin.dist</li>
    <li>python312Packages.catppuccin</li>
    <li>python312Packages.catppuccin.dist</li>
  </ul>
</details>

**Comment by TomaSajt** [comment]
I'll make this a draft until they make `catppuccin-gtk` work with the new version instead of [just using the old version](https://github.com/catppuccin/gtk/commit/c577226e9c2df2aadb4aadf7d59bda2f194c0181)

**Comment by wegank** [comment]
Done in https://github.com/NixOS/nixpkgs/commit/b9368240c954fe14fff94fd1a57af2e1fd7ed4e9?

**Comment by TomaSajt** [comment]
> Done in [b936824](https://github.com/NixOS/nixpkgs/commit/b9368240c954fe14fff94fd1a57af2e1fd7ed4e9)?

They have merged it, yes, however I think the version bump should be reverted, because `catppuccin-gtk` is broken now.

**Comment by TomaSajt** [comment]
I have opened a PR which reverts the changes

**Comment by TomaSajt** [comment]
This PR is ready for review again

**Review by fufexan — APPROVED** [review]

**Review by dixslyf — APPROVED** [review]
LGTM.

Result of `nixpkgs-review pr 290391` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>catppuccin-gtk</li>
    <li>python311Packages.catppuccin</li>
    <li>python311Packages.catppuccin.dist</li>
    <li>python312Packages.catppuccin</li>
    <li>python312Packages.catppuccin.dist</li>
  </ul>
</details>

**Pull request merged**
