### PR TITLE
defaultCrateOverrides: add rdkafka-sys

### PR DESCRIPTION
**Pull request by bbigras**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
What is your motivation behind this? Do you need it for another package?

**Comment by bbigras** [comment]
> What is your motivation behind this? Do you need it for another package?

I don't need it for another package. I thought this file was to help people using crate2nix.

**Comment by SuperSandro2000** [comment]
I asked someone else and we can it if you restore the branch. It should probably be sorted though.

**Comment by bbigras** [comment]
I can't reopen the PR. I probably fucked up the branch by force-pushing to it.

**Pull request closed without merging**
