### PR TITLE
[WIP] iwd: 0.22 -> 1.0

### PR DESCRIPTION
**Pull request by nrdxp**
ell: 0.24 -> 0.26

###### Notify maintainers
cc @dtzWill @mic92

### CODE REVIEW

**Comment by dtzWill** [comment]
Please don't merge quite yet-- they changed details in the dbus interface, so this update breaks iwd usage with NetworkManager.

I put together this fix which does the job for me, but would ideally have something more official and perhaps more complete ;).
https://github.com/dtzWill/nixpkgs/blob/96213b0560d8d8b8284ec2500c1b48af9aa51cf1/pkgs/tools/networking/network-manager/iwd-new-root-path.patch

The #iwd channel on freenode has some chat about this today, but haven't been following too closely (yet).

**Comment by dtzWill** [comment]
Also at some point I had to add this, I believe it's in the 1.0 release:

```
    "--with-systemd-networkdir=${placeholder "out"}/lib/systemd/system/"
```

And we may consider teaching NixOS to prefer a certain value for persistent naming when using iwd (they want it off).

**Comment by dtzWill** [comment]
Oh and if we currently do much for generating config, they changed the keys to be camelcase and often rewording.  It's not suitable for nixpkgs master yet, but my iwd module has a bit more beef in this area, and demonstrates what I mean:

https://github.com/dtzWill/nixpkgs/commit/57b8f5e7a52e8bd7362773a4ad75cb42f3e3b997#diff-90906f69858d618dcfe8c39518f69a6e

**Comment by colemickens** [comment]
Thank you both for doing this work!

**Comment by worldofpeace** [comment]
> Oh and if we currently do much for generating config, they changed the keys to be camelcase and often rewording. It's not suitable for nixpkgs master yet, but my iwd module has a bit more beef in this area, and demonstrates what I mean:
> 
> [dtzWill@57b8f5e#diff-90906f69858d618dcfe8c39518f69a6e](https://github.com/dtzWill/nixpkgs/commit/57b8f5e7a52e8bd7362773a4ad75cb42f3e3b997#diff-90906f69858d618dcfe8c39518f69a6e)

Oooh, we should try to get some of that in nixpkgs. I believe people have been having issues because there's no config installed for iwd, and dhcp woes.

**Comment by nrdxp** [comment]
What exactly is broken. I am using this right now with networkmanager and have not had any issues for the last few days. Also, I set `--with-systemd-networkdir=${placeholder "out"}/lib/systemd/network/` already. Its not that I don't believe you. I'd just like to reproduce so I can fix. Thanks

**Comment by colemickens** [comment]
note, it looks like the upcoming NM release has a fix for IWD 1.0. Not sure if it's relevant here or not, but seemed like a shot: https://github.com/NetworkManager/NetworkManager/commit/186d22a9634e2bf94658ed6f1cf2b332ecb3a32c

**Comment by xaverdh** [comment]
`iwd` was bumped to 1.1 on master with 09f1e0995469dec3377f1f70bc7bcac87f1583e4, so I guess this is obsolete now?

**Comment by doronbehar** [comment]
I thought this was blocked because of incompatibilities with Network Manager's API.. Does it NM's users who use IWD will get disconnected in their next `nixos-rebuild` upgrade? Or did they patch NM as well?

**Comment by xaverdh** [comment]
> I thought this was blocked because of incompatibilities with Network Manager's API.. Does it mean NM's users who use IWD will get disconnected in their next `nixos-rebuild` upgrade? Or did they patch NM as well?

Well I don't think NM was patched. They can still roll back though, so its not too bad I guess.

**Comment by Mic92** [comment]
The Networkmanager patch could be cherry-picked.

**Comment by dtzWill** [comment]
Yes, and the NM patch is also backwards compatible (an improvement on what I originally put together and linked earlier), so safe to pick.  If there's not a tagged release with this yet, of course :).

**Comment by worldofpeace** [comment]
The fix is in https://gitlab.freedesktop.org/NetworkManager/NetworkManager/blob/1.20.6/NEWS#L9 which there's a PR for #73598. It will have to to staging though

**Comment by worldofpeace** [comment]
Going to close as obsolete. Sorry about a committer pushing this, duplicated work is frequent in nixpkgs unfortunately.

**Comment by zimbatm** [comment]
just came here because I got hit by this issue. The NetworkManager upgrade hasn't left the staging branch yet.

**Comment by doronbehar** [comment]
So NetworkManager was patched to staging while iwd was updated in `master`? And now you can't NetworkManager with IWD?

**Comment by zimbatm** [comment]
Correct.
I tried reverting the IWD upgrade. This doesn't work, there were some build failures, I don't remember the details. Presumably some other packages are now depending on the latest IWD.
I tried cherry-picking the NetworkManager upgrade. Now I get this new error instead:
```
Nov 27 15:00:05 no1 NetworkManager[1026]: <warn>  [1574863205.7424] device (wlp5s0): No agents were available for this request.
Nov 27 15:00:05 no1 NetworkManager[1026]: <error> [1574863205.7425] device (wlp5s0): Activation: (wifi) Network.Connect failed: GDBus.Error:net.connman.iwd.Aborted: Operation aborted
Nov 27 15:00:05 no1 NetworkManager[1026]: <warn>  [1574863205.7433] device (wlp5s0): Activation: failed for connection 'Leazero'
```

**Comment by colemickens** [comment]
If you downgrade ell too with IWD and you can get back up and running.
That's what I did.

**Pull request closed without merging**
