### PR TITLE
tuxedo-keyboard: 3.2.5 -> 3.2.7 (also fix build on kernel >= 6.4)

### PR DESCRIPTION
**Pull request by xaverdh**
###### Description of changes

Update to make it build on kernel >= 6.4.
Replaces https://github.com/NixOS/nixpkgs/pull/240276

###### Things done

Running this on my system now via https://github.com/NixOS/nixpkgs/pull/231384

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by xaverdh** [comment]
cc @blitz

**Review by blitz — APPROVED** [review]
Thanks! This is much better than the manual patching!

**Comment by blitz** [comment]
Maybe @RaitoBezarius or @tfc can help this over the finishing line?

**Comment by xaverdh** [comment]
by the way @RaitoBezarius could you take a look at https://github.com/NixOS/nixpkgs/pull/231384 as well? I think a lot of people are running it on their systems already

**Comment by xaverdh** [comment]
> > Maybe @RaitoBezarius or @tfc can help this over the finishing line?
> 
> Enjoy

thanks :)

**Pull request merged**
