### PR TITLE
vimPlugins: Init various coc extension plugins

### PR DESCRIPTION
**Pull request by rvolosatovs**
###### Motivation for this change
To allow better "Nixifying" `coc` setup

According to https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#use-vims-plugin-manager-for-coc-extension `coc` extensions can be installed simply by adding them to RTP. (So things like this just work: https://github.com/rvolosatovs/infrastructure/blob/902a410ba2f73b32a18af3e2ccb9762c74d345aa/nixpkgs/neovim/default.nix#L10-L15)
Caveat: I managed to make it work with `plug` vim plugin backend, `configure.packages.plugins.start` does not seem to work for me again(https://github.com/NixOS/nixpkgs/issues/56338#issuecomment-466972624)
cc @teto 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by teto** [comment]
i suspect some of these plugins may need override, like coc-denite may need denite as a dependency, coc-tabnine requiring tabnine, coc-vimtex requiring vimtex etc. 
For instance, I wonder if you could make coc-python work ?
Also you've mixed in vimoutliner and a.vim and some unrelated update in a single commit. It may be wiser to split this into several PRs so that one reviewer can really test the PR.

**Comment by rvolosatovs** [comment]
Split the PR in several commits for easier review.
All I did initially was follow the default steps of adding vim plugins: https://github.com/NixOS/nixpkgs/blob/5ded60dfc4178045ac6b11c3a49c404c0376449a/pkgs/misc/vim-plugins/default.nix#L13-L15

Some of these will require extra steps indeed, however I think it's nice to at least have the extensions in `nixpkgs` already as a first step. (similarly how it was done for `coc-nvim` itself)

**Comment by malob** [comment]
Just wanted to chime in and say that I'd love to see `coc` extensions added to nixpkgs, in fact it's been on my list to see if I could figure out how to do it myself. 

As @teto notes, some of them will probably require unique overrides, and I think probably all of them that are actually extensions to `coc` (unlike `coc-denite`) will require an override in order to be properly installed. I expect the general overrides for each extension would be of the same form as the override for `coc-nvim` itself:
https://github.com/NixOS/nixpkgs/blob/5ded60dfc4178045ac6b11c3a49c404c0376449a/pkgs/misc/vim-plugins/overrides.nix#L113-L126

One issue that will almost certainly come up is that the overrides will be hard to keep in sync with the generated nix expressions whenever the vim plugins are updated. See PR #64411 by @teto, for an example.

Seems to me that the ideal longterm solution would be to have a separate script that generated the necessary nix expressions for `coc` extensions, but that seems like a lot of work.

**Comment by rvolosatovs** [comment]
@malob It's not necessarily a lot of effort. E.g. for `coc-go` something as simple as https://github.com/NixOS/nixpkgs/pull/64426/commits/1eb975cd684340a692dbd691ef7963c3f8ecf303 should be sufficient.

`coc-nvim` is quite an exception really since there we actually want to version it.

**Comment by malob** [comment]
@rvolosatovs, hmmm you are probably totally right. I accidentally assumed that the process for installing extensions would be similar to the process of installing `coc.nvim` itself.

**Comment by rvolosatovs** [comment]
Does anyone want to contribute to this?
I won't be able to go through the plugins and add overrides any time soon.

**Comment by malob** [comment]
I'd be happy contribute, but I'll need some tips about how to get started.

**Comment by teto** [comment]
ok let's merge this because I know it can be a pain to rebase the vim generated plugins.
I hope there will be some follow up PRs to make the different plugins work out of the box as much as possible.

@malob you can just look at pkgs/misc/vim-plugins/overrides.nix and try to adapt these to the different plugins.

**Comment by earksiinni** [comment]
I have no idea whether this comment will be noticed, but I want to gently and respectfully ask whether merging this PR in an incomplete state was the best course of action.

I don't know how many other people may have run into this problem, but I've spent about two days trying to figure out why there are coc extensions in the Nix repo that have no documentation on how to use them, no explanation of how they are loaded by coc, and ultimately (as I found out the hard way) don't work. This time is on top of the day or two that I spent figuring out why the coc plugin itself is available in Nixpkgs [even though coc's documentation says that I should use Plug](https://github.com/neoclide/coc.nvim). [Nix's relatively unhelpful wiki page on setting up vim](https://nixos.wiki/wiki/Vim) doesn't give a clear explanation of how the vim packages work, either.

I'm a newcomer to Nix and I've quickly become aware that I'm not the only one having a hard time with the documentation. I've been [trying to update the docs myself](https://github.com/NixOS/nix/pull/3159) as well [trying to contribute to vim plugins](https://github.com/NixOS/nixpkgs/pull/71972). I don't mean to sound ungrateful. I'm aware that most of us are doing this for free and that keeping docs up-to-date is a task that most people don't relish, especially when the code is in flux.

But why make things harder on new users by intentionally, knowingly merging broken code? Had I not stumbled on this PR by accident, I would still be scratching my head, wondering why the mainline Nixpkgs repo has these tantalizingly-named `coc-` packages that are essentially unusable. (Or some of them, anyway. FWIW, in the extensions that I tested, the problem is that we need overrides to add some kind of build step, as @teto [observed above](https://github.com/NixOS/nixpkgs/pull/64426#issuecomment-509059900).)

Thank you all for your hard work. I greatly appreciate it, and I hope that we can all make the UX more hospitable, especially for new users.

**Comment by earksiinni** [comment]
@rvolosatovs, I've also stopped going to the docs, in part due to my struggles with coc extensions. I'm currently writing a deep dive about what exactly happens when one installs a Nix package. It has been highly informative. I follow a workflow similar to yours. (Didn't know that `configuration.nix` had a man page, though, thanks for the tip!)

However, I don't think that "the documentation is bad, so check the source code" is a good state of affairs for the community. Merging broken code merely compounds the problem.

I'd like to take a crack at fixing the broken extensions this week.

**Comment by malob** [comment]
@rvolosatovs, no progress unfortunately, I tried a couple of times but didn't get to far before hitting issues.

**Comment by earksiinni** [comment]
@malob @rvolosatovs, I've made some progress and have fixed `vimPlugins.coc-prettier` on my local machine. Will post in https://github.com/NixOS/nixpkgs/issues/64560 to keep the discussion in one place.

**Pull request merged**
