### PR TITLE
python38Packages.internetarchive: 1.9.9 -> 2.0.2

### PR DESCRIPTION
**Pull request by marsam**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by stephank** [comment]
Result of `nixpkgs-review pr 118779` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python38Packages.internetarchive</li>
    <li>python38Packages.tubeup</li>
    <li>python39Packages.internetarchive</li>
    <li>python39Packages.tubeup</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 118779` at bebb2fac run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built successfully:</summary>
  <ul>
    <li>python38Packages.internetarchive</li>
    <li>python38Packages.tubeup</li>
    <li>python39Packages.internetarchive</li>
    <li>python39Packages.tubeup</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`agpl3` is a deprecated license, please check if project uses `agpl3Plus` or `agpl3Only` and change `meta.license` accordingly.

Near pkgs/development/python-modules/internetarchive/default.nix:56:5:
```
   |
56 |     license = licenses.agpl3;
   |     ^
```
</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 118779` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python38Packages.internetarchive</li>
    <li>python38Packages.tubeup</li>
    <li>python39Packages.internetarchive</li>
    <li>python39Packages.tubeup</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
- [x] package built (see https://github.com/NixOS/nixpkgs/pull/118779#issuecomment-815510611)
- [ ] all depending packages build
- [x] tested on x86_64

```bash
...ew/pr-118779/results/python38Packages.internetarchive/lib/python3.8/site-packages]$ python
Python 3.8.8 (default, Feb 19 2021, 11:04:50) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from internetarchive import get_item
>>> item = get_item('nasa')
>>> item.item_metadata['metadata']['title']
'NASA Images'
```

Change looks good to me.

**Pull request merged**
