### PR TITLE
nixos/wireguard: Remove .path systemd unit for privkey

### LINKED ISSUE #123203: wireguard: Stopping service has no effect
After `systemctl stop wireguard-wg0.service` I still get

```
# netstat -anup | grep 51820
udp        0      0 0.0.0.0:51820           0.0.0.0:*                           -                   
udp6       0      0 :::51820                :::*                                -
```

So Wireguard is still running in the kernel, listening on the port.

I had to do `ip link set down dev wg0` to stop it and free the port.

I believe that `systemctl stop` should stop wireguard, and free the port.

---

These are the `journalctl -f` logs of the `stop` operation:

```
# systemctl stop wireguard-wg0.service 
Warning: Stopping wireguard-wg0.service, but it can still be activated by:
  wireguard-wg0.path
```

```
May 16 06:36:47 myhost systemd[1]: Stopping WireGuard Peer - wg0 - mypeerid_here...
May 16 06:36:47 myhost systemd[1]: wireguard-wg0-peer-mypeeriid_here.service: Succeeded.
May 16 06:36:47 myhost systemd[1]: Stopped WireGuard Peer - wg0 - mypeerid_here.
May 16 06:36:47 myhost systemd[1]: Stopping WireGuard Tunnel - wg0...
May 16 06:36:47 myhost avahi-daemon[1249]: Withdrawing workstation service for wg0.
May 16 06:36:48 myhost systemd[1]: wireguard-wg0.service: Succeeded.
May 16 06:36:48 myhost systemd[1]: Stopped WireGuard Tunnel - wg0.
May 16 06:36:48 myhost systemd[1]: Starting WireGuard Tunnel - wg0...
May 16 06:36:48 myhost systemd-udevd[61430]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
May 16 06:36:48 myhost systemd-udevd[61430]: Using default interface naming scheme 'v245'.
May 16 06:36:48 myhost systemd[1]: Finished WireGuard Tunnel - wg0.
May 16 06:36:48 myhost systemd[1]: Starting WireGuard Peer - wg0 - mypeerid_here...
May 16 06:36:48 myhost systemd[1]: Finished WireGuard Peer - wg0 - mypeerid_here.
```

As shown, the tunnel and peer services both immediately restart, thus effectively ignoring the user's request to `stop`.

## Technical details

On NixOS 20.09.

### LINKED ISSUE #123293: wireguard: Changing `listenPort` has no effect
On NixOS 20.09, steps to reproduce the behavior:

1. After setting up wireguard, change `networking.wireguard.interfaces."wg0".listenPort` to another port
2. `nixos-rebuild switch`

`wg` still shows the old port:

```
interface: wg0
  listening port: ...old port here..
```

### PR DESCRIPTION
**Pull request by nh2**
###### TODO

* [x] Based on PR #121331, merge that first.
  * Thus only the top commit needs to be reviewed.

###### Motivation for this change

Fixes #123203.

As per `man systemd.path`:

> When a service unit triggered by a path unit terminates
> (regardless whether it exited successfully or failed),
> monitored paths are checked immediately again,
> **and the service accordingly restarted instantly**.

Thus the existence of the path unit made it impossible to stop the
wireguard service using e.g.

    systemctl stop wireguard-wg0.service

Systemd path units are not intended for program inputs such
as private key files.
This commit simply removes this usage; the private key is still
generated by the `generateKeyServiceUnit`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nh2** [comment]
Also fixes #123293

**Comment by jonringer** [comment]
cc wireguard users @nrdxp @manveru

**Review by nrdxp — APPROVED** [review]
This works as advertised and doesn't seem to cause any harm to my wg connections after a service stop and restart.
LGTM

**Review by jonringer — APPROVED** [review]
two people saying this works is fine by me.

Don't see anything glaringly wrong with changes :)

**Comment by jonringer** [comment]
oh, this should be backported

**Pull request merged**
