### PR TITLE
bazel_5: 5.0.0 -> 5.1.1

### PR DESCRIPTION
**Pull request by betaboon**
###### Description of changes

https://github.com/bazelbuild/bazel/releases/tag/5.1.0
https://github.com/bazelbuild/bazel/releases/tag/5.1.1

cc @NixOS/bazel 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by uri-canva** [comment]
Looks great, thanks!

**Comment by samuela** [comment]
This PR broke jaxlib, jaxlibWithCuda, augmax, flax, dm-haiku, treeo, treex, elegy, optax, and likely many others. See https://github.com/NixOS/nixpkgs/issues/168568 for example. Please run nixpkgs-review before merging in the future.

Please fix these issues, or revert this change.

**Comment by betaboon** [comment]
@samuela sorry for the inconvenience. I'm looking into it

**Comment by betaboon** [comment]
related #168716

**Comment by betaboon** [comment]
@samuela i went through all the build-logs of nixpkgs-upkeep liked to #168568

```
augmax -> jaxlib
flax -> jaxlib
jax -> jaxlib
jaxlib
jaxlibWithCude -> jaxlib
optax -> jaxlib
tensorflow-bin ->  ERROR: No matching distribution found for tensorflow-estimator<2.8,~=2.7.0rc0
tensorflow-bin-cuda -> ERROR: No matching distribution found for tensorflow-estimator<2.8,~=2.7.0rc0
tensorflow-datasets -> jaxlib
wandb -> tests failing
```

the failures due to jaxlib might be resolved by #168716

so I'm unclear if there is anything left to do for me here. please advice ;)


P.S.: jax just released v0.3.6 two days ago which included the bump to bazel 5.1.1

**Comment by samuela** [comment]
Thanks for looking into it @betaboon! Yeah, let's move forward with https://github.com/NixOS/nixpkgs/pull/168716. I think that's the best route.

And the duplicate nixpkgs-upkeep issues are a PITA... I have a fix I'm going to push today!

**Comment by betaboon** [comment]
@samuela thanks. I'll consider this resolved then :)

**Pull request merged**
