### PR TITLE
gleam: add update script

### PR DESCRIPTION
**Pull request by meppu**
## Description of changes

I added an update script and also ran the script and updated gleam from `0.30.2` to `0.30.5`.
*I'm not really good at writing bash but tried my best, waiting for reviews :)*

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by fabaff — COMMENTED** [review]
At first glance it looks like that `nix-update` is already able to update `gleam`.

**Comment by meppu** [comment]
> At first glance it looks like that `nix-update` is already able to update `gleam`.

Ah I see, i didn't know `nix-update` was a thing. Which option would better – sticking with the current script or just use `nix-update-script`?

**Comment by happysalada** [comment]
most definitely, just adding the following line would be easier
```
  passthru.updateScript = nix-update-script { };
```
let me know if this comment is too vague.

**Comment by meppu** [comment]
I replaced current script with `nix-update-script` and manually ran it for updating `gleam`

**Comment by happysalada** [comment]
Thank you !

**Pull request merged**
