### PR TITLE
pcre: Fix postFixup script to resolve libs on darwin

### PR DESCRIPTION
**Pull request by discordianfish**
##### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [x] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
At first I didn't realize the basic version isn't affected by this. Larger rebuilds should only be through qt5.

**Comment by vcunat** [comment]
@discordianfish: I suppose you did test this works well on Darwin (even though you haven't checked the box)?

**Comment by discordianfish** [comment]
@vcunat Yes, I've just tested it and it builds. But now run into another issue so not sure if something was actually build against it yet.

**Comment by vcunat** [comment]
Even if it doesn't, this change will most likely be useful anyway.

**Comment by vcunat** [comment]
I tend to forget the Darwin differences, having no access to any myself...

**Pull request merged**
