### PR TITLE
awk-language-server: init at 0.10.6

### LINKED ISSUE #234354: Package request: awk-language-server
A Language Server for AWK. 

**Metadata**

* homepage URL: https://github.com/Beaglefoot/awk-language-server/blob/master/README.md
* source URL: https://github.com/Beaglefoot/awk-language-server/
* license: mit
* platforms: linux, darwin

### PR DESCRIPTION
**Pull request by MathiasSven**
## Description of changes

Adds the [awk-language-server](https://github.com/Beaglefoot/awk-language-server/). Closes #234354 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by eclairevoyant — DISMISSED** [review]

**Comment by sivizius** [comment]
Obsolete by https://github.com/NixOS/nixpkgs/pull/346009

**Comment by eclairevoyant** [comment]
Calling this obsolete is kinda rude, considering the author of the other PR didn't check for an existing open PR

**Comment by sivizius** [comment]
> …considering the author of the other PR didn't check for an existing open PR

They might actually have. The other PR introduces this package in a newer version than this PR. Either way, this PR is superseded (is this less rude?) by the other PR, thus this PR can be closed, now or after the other PR was merged. Considering this PR is stale, it could actually be closed immediately.

**Comment by MathiasSven** [comment]
The `update.sh` script from `passthrou.updateScript` still works, I just haven't updated. Regardless, I don't remember why I decided to package it this way vs using `node-packages.nix`. If you believe adding it via `node-packages.nix` has more merits, feel free to close.

**Comment by eclairevoyant** [comment]
> Considering this PR is stale, it could actually be closed immediately.

It's not stale, it's on committers for not reviewing the PR.

> I don't remember why I decided to package it this way vs using `node-packages.nix`

Some committers didn't like nodePackages, I don't know the details though, so maybe this PR is preferable (without me having reviewed the code carefully, anyway).

**Review by Aleksanaa — APPROVED** [review]

**Pull request merged**
