### PR TITLE
nixd: 1.2.3 -> 2.0.2

### PR DESCRIPTION
**Pull request by marsam**
Diff: https://github.com/nix-community/nixd/compare/1.2.3...2.0.2

Changelog: https://github.com/nix-community/nixd/releases/tag/2.0.2

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Aleksanaa** [comment]
Maybe ask @inclyc? He told me this is expected to be unstable.

**Review by inclyc — COMMENTED** [review]
Yes, wait for next stable version? (I'd expect it will be published a few days later)

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 305285` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>nixd</li>
  </ul>
</details>

**Comment by bjornfor** [comment]
nixd 2.0.2 is out now: https://discourse.nixos.org/t/nixd-2-0-2-released/43891. Update?

**Comment by CnTeng** [comment]
> nixd 2.0.2 is out now: https://discourse.nixos.org/t/nixd-2-0-2-released/43891. Update?

It is 2.0.2 already.

**Review by drupol — APPROVED** [review]

**Review by drupol — COMMENTED** [review]
Please upgrade to 2.0.2 (or any other latest version) and we'll get this in.

**Comment by GaetanLepage** [comment]
It fails to build with:
```

**Comment by GaetanLepage** [comment]
It fails to build with:

```
[106/107] Linking target nixd/nixd-attrset-eval
[107/107] Linking target nixd/nixd
buildPhase completed in 33 seconds
@nix { "action": "setPhase", "phase": "checkPhase" }
Running phase: checkPhase

ERROR: *:server test name does not match any test
```

**Comment by inclyc** [comment]
Please update test targets to: https://github.com/nix-community/nixd/blob/dc0164e0df37e5d06bda61b6fb2ca16089d5f838/default.nix#L69

(Anyone has commit access?)

**Comment by 573** [comment]
What about the updating test targets ?
The upstream link @inclyc provided tells to use `meson test --print-errorlogs  unit/libnixf/Basic unit/libnixf/Parse unit/libnixt` [here](https://github.com/NixOS/nixpkgs/pull/305285/files#diff-969ba1739d6853b40d4ebbf375e7a7811884d4aa2efdabbc516235118ab84d82R78) rather so we could retest this PR one more time before letting it gotten merged.

**Comment by Lord-Valen** [comment]
nit: Change PR title and body to reflect that this is moving to nixd 2.0.2 to avoid confusion and for future reference.

**Comment by adamcstephens** [comment]
Fixed the tests, updated the title/description, and verified it builds on x86_64-linux, aarch64-linux and aarch64-darwin.

Hope you don't mind @marsam. :)

**Review by inclyc — APPROVED** [review]

**Comment by inclyc** [comment]
Looks good! Thanks @adamcstephens

**Review by inclyc — APPROVED** [review]

**Pull request merged**
