### PR TITLE
kubernetes: 1.4.0 -> 1.4.5

### PR DESCRIPTION
**Pull request by bachp**
###### Motivation for this change

Update to latest patch version.
This includes some security updates.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bachp** [comment]
@fpletz As far as I know stable is still on Kubernetes 1.2.x so if there needs to be a security update it might be to update to the latest 1.2.x version.

**Comment by offlinehacker** [comment]
Hey, have you tested this with kubernetes nixos module? I'm not fine with just merging, i have not noticed until now, will add comment to the package.

**Comment by offlinehacker** [comment]
upon next update please also test with nixos module

**Comment by bachp** [comment]
@offlinehacker Will do. The new module you merged works well witch 1.4.

**Pull request merged**
