### PR TITLE
yuzu-mainline: 1595 -> 1596, yuzu-ea: 3940 -> 3942

### PR DESCRIPTION
**Pull request by hughobrien**
## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
Did mainline really get a new build number, but no new hash? Also, do we really need to update one or two builds ahead?

**Comment by hughobrien** [comment]
> Did mainline really get a new build number, but no new hash? 
That certainly would be non-sensical, I can only sheepishly point at the update script which maybe hit a race condition where one was updated but not the other? It does fetch by tag so possibly a stale read on GitHub's side - but I'm clutching at straws here. I'll run the script again and fix the commit.

> do we really need to update one or two builds ahead?
Could you tell me what you mean by ahead? Ahead of the flatpak releases?

**Comment by K900** [comment]
Ahead of the previous release. Like, we probably don't want to upgrade to every single Yuzu build in Nixpkgs - it's a lot of churn for something that is probably better handled out of tree, in some automated way.

**Comment by hughobrien** [comment]
Agreed, the builds are released faster than I understood.

**Comment by K900** [comment]
Yeah, they often do multiple builds a day. I usually update the Nixpkgs versions when there's major fixes and/or perf improvements.

**Pull request closed without merging**
