### PR TITLE
libwacom-surface: init at 2.4.0

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc @kiana-S

### CODE REVIEW

**Comment by jtojnar** [comment]
Maybe add a link to https://github.com/linux-surface/libwacom/issues/2 for context?

**Comment by dotlambda** [comment]
Do you think it's a better idea to simply include these patches in our `libwacom`. That would reduce the number of rebuilds for people setting `libwacom = libwacom-surface` in an overlay.

**Comment by jtojnar** [comment]
That would require us reviewing those patches and might break on updates.

**Comment by dotlambda** [comment]
> Maybe add a link to [linux-surface/libwacom#2](https://github.com/linux-surface/libwacom/issues/2) for context?

added

> That would require us reviewing those patches and might break on updates.

I haven't actually read through the patches. And I guess Surface users have to build their own kernel anyway so this is fine.

**Comment by dotlambda** [comment]
I should have tested this beforehand but I'm getting infinite recursion when setting
```
nixpkgs.overlay = [
  (self: super: {
    libwacom = super.libwacom-surface;
  })
];
```
Any idea how to fix that?

**Comment by tejing1** [comment]
This should work:
```nix
(self: super: {
  libwacom = self.libwacom-surface.override { inherit (super) libwacom; };
})
```

**Comment by dotlambda** [comment]
> This should work:
> 
> ```nix
> (self: super: {
>   libwacom = self.libwacom-surface.override { inherit (super) libwacom; };
> })
> ```

It sadly doesn't. It still results in infinite recursion.

**Pull request merged**
