### PR TITLE
GNOME: 45 → 46

### LINKED ISSUE #282102: Update request: FreeRDP 2.11.2 → 3.2.0
- Package name: FreeRDP
- Latest released version: 3.2.0

- Current version on the unstable channel: 2.11.2
- Current version on the stable/release channel: 2.11.2

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@peterhoeg
@lheckemann

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #292187: Package request: bustle (rust) to replace pkgs.bustle
Freedesktop has apparently deprecated the Haskell bustle (`pkgs.bustle`) and rewritten it in Rust: <https://gitlab.gnome.org/World/bustle>. It'd be nice to package it and ideally replace `pkgs.bustle` with it since the haskell version has become difficult to keep working. (Is it a drop in replacement?)

### LINKED ISSUE #300620: Package request: gnome-online-accounts-gtk
A GTK Frontend for GNOME Online Accounts to be used on any desktop outside gnome, made by linuxmint

**Metadata**

* homepage URL: https://github.com/linuxmint/gnome-online-accounts-gtk
* source URL:https://github.com/linuxmint/gnome-online-accounts-gtk
* license: GPL-3.0
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #301052: Update request: libadwaita 1.4.4 → 1.5.0
- Package name: libadwaita
- Latest released version: 1.5.0

- Current version on the unstable channel: 1.4.4
- Current version on the stable/release channel: 1.4.4

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@bobby285271
@hedning
@jtojnar
@dasj19
@amaxine
@dotlambda

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by amaxine**
This draft PR starts update work for the upcoming GNOME 46 release.

- Schedule: https://wiki.gnome.org/FortySix
- Project: TBD
- Previous major release: #247766
- Tool for reviewing changes: https://github.com/jtojnar/nonemast
- Release announcement: https://release.gnome.org/46/
- Hydra jobset: https://hydra.nixos.org/jobset/nixpkgs/gnome

### How to help

- test running your system from this branch (warning: you might not be able to roll back to 45 without dropping all configuration)
- test running new versions of software from this branch
- check hydra builds
  1. look at the latest evaluation in the [jobset](https://hydra.nixos.org/jobset/nixpkgs/gnome)
  2. check the _newly/still failing jobs_ tab, look for red crosses ❌ 
  3. open the individual failures' logs
  4. if you see any failures that look like dependency issue or anything that could be caused by this PR, report it in a comment, or open a PR against gnome-46 branch, if you are able to.
- report any and all problems!

### Needs work

- [ ] Test and fix darwin stuff
  - [x] [ofborg-eval-nixpkgs-unstable-jobset](https://gist.github.com/GrahamcOfBorg/4371e895f4088a18c02e16ed9ff8c319) fails (gst-plugins-base)
- [ ] g-c-c g-r-d doesn't support password generation: ` WARNING: Failed to open file: Error opening file /usr/share/dict/linux.words: No such file or directory`
  - consider setting `environment.wordlist.enable = true` as part of g-r-d? not enough by itself, would still need to patch
- [x] keyring unlocking doesn't use native prompts all of a sudden?
  - cannot repro
- [x] figure out if there's been any implementation changes that require something on our side for mounting from g-o-a - mounting dav/google accounts?
  - all good
- [x] snapshot crashes on startup/can't open stream
  - https://gitlab.gnome.org/GNOME/snapshot/-/issues/134 maybe this
- [ ] Try the new `gi-compile-repository`, `gi-decompile-typelib` and `gi-inspect-typelib`
  - Decide which output they should belong to (they are in `-bin` right now)
  - Figure out how the gobject-introspection-wrapped wrapper might be used here (?? tbh idk)
- [x] loupe/glycin crashes when loading images
  - seems to be sandboxing/bubblewrap related - we need to fix the sandbox patch, the bind mounts make no sense in the context of nix
  - amaxine: bind mounting /nix/store seems a bit more risky than /usr, but it's unclear to me how to instead pass in the linker and each dep
- [x] write release notes
  - link to official release announcement (see above), mentioning experimental VRR support and GTK renderer changes as notable
  - we no longer ship adwaita-dark by default in 24.05 as it's not supported - remember to update your configuration accordingly (`gnome-themes-extra`, #277944)
  - new g-r-d features as before first require being explicitly enabled in nix (`services.gnome.gnome-remote-desktop.enable`)
- [x] add jxl support where necessary
  - land #299988 and #269563
- [ ] GNOME-adjacent desktop breakages (@bobby285271)
  - [x] cinnamon.cinnamon-control-center: [FTBFS with GOA 3.49](https://github.com/linuxmint/cinnamon-control-center/issues/326) + [gnome-online-accounts-gtk](https://github.com/linuxmint/gnome-online-accounts-gtk)
  - [x] pantheon.elementary-notifications: [FTBFS with Vala 0.56.16](https://github.com/elementary/notifications/issues/222)
  - [x] nixosTests.pantheon: [Requires systemd managed gnome-session](https://github.com/NixOS/nixpkgs/pull/140429)
  - [x] I try to actually do some testing in the following week.
- [x] glib/g-i circular dependency
- [ ] gcr/gnome-keyring ssh-agent changes https://gitlab.gnome.org/GNOME/gnome-build-meta/-/issues/770
  - currently disabling gcr ssh-agent and enabling gnome-keyring ssh-agent
- [x] glycin-loaders doesn't build (see commit)
- [x] all of gstreamer needs updating to 1.24
- [x] fix gjs test failures
  - ~~bobby285271: On 9b23cf84451e85ed15f4182ea5ce8b1f350da58d this runs fine for me~~ See [#gnome:nixos.org](https://matrix.to/#/!XQQVyIbcAcHFvzmcTl:nixos.org/$Xd_m3-iqu98EexX08MlRTfWdXwSXQAUgL3ZRtGvg_9k?via=nixos.org&via=matrix.org&via=tchncs.de)
  - for now just disabling introspection tests
- [x] fix libshumate test failures
  - pending upstream fixes https://gitlab.gnome.org/GNOME/libshumate/-/issues/71
  - amaxine: I'm describing this as done within the context of upstream's acknowledgement
- [x] fix gst-python test failures
  - pending upstream fixes https://gitlab.gnome.org/GNOME/pygobject/-/merge_requests/304
  - hopefully PR fixing will be reviewed so we can confidently add the patch
- [x] fix gnome-remote-desktop/freerdp building
- [x] actually test evolution/evolution-ews (spamassassin tests don't pass so I've not built it)

### Nice to have
- [x] Package Papers (gtk4 port of evince)
  - https://gitlab.gnome.org/GNOME/Incubator/papers
  - https://github.com/NixOS/nixpkgs/pull/299579
- [ ] Ensure all GNOME Circle additions are in nixpkgs
- [x] Extensions
  - https://github.com/NixOS/nixpkgs/pull/302860

### Related
Closes #282102
Closes #300620
Closes #300634
Closes #301052
Closes #299414
Closes #292187

### CODE REVIEW

**Comment by amaxine** [comment]
Since staging-next got merged with a libheif bump we need, I've rebased the branch on current master and cleaned up repeated bumps while preserving commit messages. I'm currently rebuilding this branch in that state, so no current promises about it even building just yet.

**Comment by bobby285271** [comment]
@ofborg build libical

**Comment by bobby285271** [comment]
With 2209d11fd8b1055e0bfa62e39a1d2cc631230889 + 016a02c7e7f3837e72d494c67251fc27606d089f + 14436ce5624723242d786c7b45debd680582894f, all gnome-maps tests pass for me (my custom branch also contains a revert for pygobject)



**Note that g-i 1.79 no longer installs GLib introspection data**, this causes some build failures like libical and libsecret (see the commits above) because their test overrides `GI_TYPELIB_PATH`. It is unclear how many breakages this will cause yet.

**Comment by amaxine** [comment]
@bobby285271 Thanks for that fixup, I pushed and kicked off rebuilds elsewhere to look at output another day :woman_facepalming: this doesn't waste a night of compute.

**Comment by amaxine** [comment]
`xapian` test failures are resolved in `staging-next` - #295458.

**Comment by amaxine** [comment]
Still not quite there yet, but gnome tests build fine now!

image

Main blockers are resolving gjs/libshumate tests being broken, and freerdp3/gnome-remote-desktop header issues, as listed in the PR description right now.

**Comment by Jo-Blade** [comment]
@amaxine 
Hello, what is the package " Package Papers (gtk4 port of evince)" that you are referring to ? Do you have a link to share, please ?

I couldn't find any gtk4 port on evince on the web and I am very interested. Thank you

**Comment by jtojnar** [comment]
@Jo-Blade https://thisweek.gnome.org/posts/2024/02/twig-136/#gnome-incubating-apps

**Comment by etrigan63** [comment]
Silly question: since GNOME 46 is pure Wayland (supposedly) will its invocation in `configuration.nix` change because it no longer is an xserver?

**Comment by jtojnar** [comment]
No, the `xserver` module does other stuff than just X stuff. And renaming it is out of scope of the bump, see https://github.com/NixOS/nixpkgs/issues/94799 instead.

And IIRC the X removal was delayed due to some accessibility blockers anyway.

**Comment by Jo-Blade** [comment]
> @Jo-Blade https://thisweek.gnome.org/posts/2024/02/twig-136/#gnome-incubating-apps

Thanks you ! I just manage to build papers today, I will do a request in a few hour (just to clean a bit my derivation)

**Comment by amaxine** [comment]
/If/ you have the CPU cycles to spare, running from this branch should now be doable. I'm typing this comment from my laptop running GNOME 46!

image

**Comment by amaxine** [comment]
@bobby285271 Just as a heads up, when current staging-next lands (the one with the xz revert), I'm going to autosquash/squash this PR again, and rebase to resolve the current and incoming conflicts. I'll try waiting until it makes its way to unstable at least to minimise rebuilds for people.

**Comment by amaxine** [comment]
Note: squashing everything ahead of rebasing properly tomorrow. I'm doing this separately so that conflict resolution is simpler when I rebase on unstable.

**Comment by Nanotwerp** [comment]
It appears that `g-r-d` has a few issues:

- Running most subcommands of `grdctl` gives a segfault. For example, running `grdctl rdp` produces the output `Segmentation fault (core dumped)`
- The system-wide `systemd` service for `g-r-d` doesn't start, but the user-specific one works fine.
- Most options under `g-c-s` -> `System` -> `Remote Login` are greyed out, even after authentication. This includes the `Port` option under the `How to Connect` section, along with all the fields under the `Login Details` section. If I open `g-c-s` in a terminal and click the `Remote Login` button, I get these warnings:
```
00:45:41.0608 cc-remote-session-page[33102]: WARNING: Failed to import newly generated certificates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.RemoteDesktop was not provided by any .service files
00:45:41.1120 cc-remote-session-page[33102]: WARNING: Failed to enable RDP server: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.RemoteDesktop was not provided by any .service files
```

I think the 3rd issue I listed is possibly related to the 2nd one.

**Comment by nyabinary** [comment]
Would this unblock #290598 ?

**Comment by amaxine** [comment]
@nyabinary Yes, this brings newer gtk4 and libadwaita.

**Comment by jtojnar** [comment]
Cambalache moved to GTK 4 and looks like the renderer changes might be too new for my hardware :crying_cat_face: 

<details>

```
(cambalache:464090): Gdk-CRITICAL **: 13:30:05.022: Vulkan: ../src/nouveau/vulkan/nvk_physical_device.c:952: WARNING: NVK is not well-tested on GeForce GTX 760, pass NVK_I_WANT_A_BROKEN_VULKAN_DRIVER=1 if you know what you're doing. (VK_ERROR_INCOMPATIBLE_DRIVER)
MESA-INTEL: warning: Haswell Vulkan support is incomplete
MESA-INTEL: warning: ../src/intel/vulkan_hasvk/anv_formats.c:752: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan_hasvk/anv_formats.c:783: FINISHME: support more multi-planar formats with DRM modifiers
```

</details>

And bustle crashes for me after a bit of usage:

<details>

```
nouveau: kernel rejected pushbuf: No such device
nouveau: ch14: krec 0 pushes 1 bufs 15 relocs 0
nouveau: ch14: buf 00000000 00000011 00000004 00000004 00000000 0x7fcc23f80000 0x1fa0000 0x80000
nouveau: ch14: buf 00000001 00000007 00000002 00000002 00000000 (nil) 0x2e0000 0x80000
nouveau: ch14: buf 00000002 00000028 00000002 00000002 00000000 (nil) 0x2550000 0x1000
nouveau: ch14: buf 00000003 00000037 00000004 00000004 00000000 0x7fcc21300000 0x3880000 0x100000
nouveau: ch14: buf 00000004 00000044 00000002 00000002 00000000 (nil) 0x2b0b000 0x12000
nouveau: ch14: buf 00000005 00000048 00000002 00000002 00000000 (nil) 0x2c1d000 0x2000
nouveau: ch14: buf 00000006 00000049 00000002 00000002 00000000 (nil) 0x2b7c000 0x3000
nouveau: ch14: buf 00000007 0000001b 00000002 00000002 00000000 (nil) 0x25a0000 0x400000
nouveau: ch14: buf 00000008 00000066 00000002 00000002 00000000 (nil) 0x29dd000 0x1000
nouveau: ch14: buf 00000009 00000008 00000002 00000002 00000000 (nil) 0x360000 0xe0000
nouveau: ch14: buf 0000000a 0000000b 00000002 00000002 00000000 (nil) 0x1d80000 0x20000
nouveau: ch14: buf 0000000b 0000000a 00000002 00000002 00000002 (nil) 0x1c80000 0x100000
nouveau: ch14: buf 0000000c 00000006 00000004 00000000 00000004 0x7fcc285d9000 0x224000 0x1000
nouveau: ch14: buf 0000000d 0000001d 00000002 00000000 00000002 (nil) 0x49e0000 0x880000
nouveau: ch14: buf 0000000e 00000040 00000004 00000004 00000004 (nil) 0x29de000 0x1000
nouveau: ch14: psh 00000000 000005356c 00000535b4
nouveau: 	0x200203fd
nouveau: 	0x0116035c
nouveau: 	0x0002024f
nouveau: 	0x20040360
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x20010674
nouveau: 	0x0000003c
nouveau: 	0x200203fd
nouveau: 	0x07800000
nouveau: 	0x04180000
nouveau: 	0x200406c0
nouveau: 	0x00000000
nouveau: 	0x00224000
nouveau: 	0x0000697b
nouveau: 	0x1000f010
bustle: ../nouveau/pushbuf.c:730: nouveau_pushbuf_data: Assertion `kref' failed.
fish: Job 1, 'result/bin/bustle' terminated by signal SIGABRT (Abort)
```

</details>

But I did not see any issues in gtk4-demo.

**Comment by Jo-Blade** [comment]
> It looks like no one is working on Papers yet, so I'm trying to take a shot at it, but I have some questions. Looking at the source repo, there's no tags yet for the new version. Should I target the development branch? (`https://gitlab.gnome.org/GNOME/Incubator/papers/-/archive/meson-release/papers-meson-release.tar.gz`, version 46.alpha as of now)

I'm already working on papers : https://github.com/NixOS/nixpkgs/pull/299579

**Comment by jtojnar** [comment]
That is probably running out of memory due to building too many derivations at once. Try building just `webkitgtk`. Or maybe try temporarily remove whatever program depends on `webkigtk` – most of packages should have been migrated from 4.0 ABI to `webkitgtk_4_1` (or 6.0 if they also switched to GTK 4) by now, to avoid the need for third webkit copy.

**Comment by nyabinary** [comment]
Talking about webkit, I wonder if we can get this merged: https://github.com/NixOS/nixpkgs/pull/280554 before this PR lands.

**Comment by msfjarvis** [comment]
👋🏼 After a rather long round of painful rebuilds (darn you webkitgtk \*shakes fist\*) I've managed to get GNOME 46 working on my machine. I had to update the gnomeExtensions package set to restore my setup to _almost_ the same state as GNOME 45, please let me know if/how/when I can contribute this upstream: https://github.com/msfjarvis/nixpkgs/commits/hs/gnome-46/

**Comment by amaxine** [comment]
@msfjarvis thanks! If you could open a separate PR for gnome extensions, that would be greatly appreciated. Those commits don't need to target this branch, they're fine heading straight to master so that they can be merged at around the same time as this PR.

**Comment by amaxine** [comment]
@nyabinary adding the experimental flag can happen any time, but the comment I left on that PR still stands - we should avoid the unnecessary rebuilds currently caused by not gating that flag behind it being set. Please bump this in the PR you linked and not here.

**Comment by fabianhjr** [comment]
gnome-control-center was failing to build due to missing deps added 3 deps in https://github.com/NixOS/nixpkgs/pull/291339/commits/bba1440dae8eb9d4ad97643c376348db437d99cd

**Comment by jtojnar** [comment]
Hmm, builds fine here. Perhaps a downfall from https://github.com/NixOS/nixpkgs/pull/301865

**Comment by fabianhjr** [comment]
I encounter the issue after rebasing with the main branch.

**Comment by amaxine** [comment]
In the context of that PR, I'm inclined to rebase now to hopefully get more effective testing. Thanks for catching that @fabianhjr

**Comment by Aleksanaa** [comment]
Will this be part of the [24.05 release](https://github.com/NixOS/nixpkgs/issues/303285)? Do we currently have plans for the deadline?

**Comment by jtojnar** [comment]
That is the goal. Though we have all been busier this cycle.

One thing people could help with is evaluating the hydra failures. Unfortunately, we currently do not have the [sophisticated tooling of ZHF](https://github.com/NixOS/nixpkgs/issues/230712) (something to look for future cycles) so it would probably have to be done manually:

1. look at the latest finished evaluation in the [jobset](https://hydra.nixos.org/jobset/nixpkgs/gnome) (currently the second last)
2. check the _newly/still failing jobs_ tab, look for red crosses ❌ (you can remove the grey ones by running the following in browser console `document.querySelectorAll('.build-status[title="Dependency failed"]').forEach((st) => st.parentNode.parentNode.remove())`)
3. open the individual failures' logs
4. check if the failure is a dependency issue or anything that could be caused by this PR (error mentions glib, gtk, gnome, gobject-intropection/g-i…)
5. If so, report it in a comment, or open a PR against gnome-46 branch, if you are able to.

For example, in the latest (unfinished evaluation) the only thing that pops up is:

- [ ] ayatana-indicator-messages https://hydra.nixos.org/build/255863382/nixlog/1 something with gi in tests

**Comment by jtojnar** [comment]
@bobby285271 did not realize the GLib typelib already move went through. That means we cannot rely on libgirepository (e.g.  in `pygobject3`) pulling them in and will always need a wrapper:

```ShellSession
$ GI_TYPELIB_PATH= result/bin/powerprofilesctl
Traceback (most recent call last):
  File "/home/jtojnar/Projects/nixpkgs/result/bin/powerprofilesctl", line 8, in <module>
    from gi.repository import Gio, GLib
  File "/nix/store/99klqpc64w7dn5gn50hvxnrhbxcq0byj-python3-3.11.8-env/lib/python3.11/site-packages/gi/importer.py", line 133, in create_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name Gio, introspection typelib not found
```

I also wonder if `propagatedBuildInputs` for `glib` in `g-i` should not be `depsTargetTargetPropagated` or something.

**Comment by mikunimaru** [comment]
Since https://github.com/NixOS/nixpkgs/pull/302860 has been merged into master, is it possible to rebase to the latest master?

**Comment by Aleksanaa** [comment]
So gnome works with extensions targeting higher versions? Why that's merged into master instead of this branch?

**Comment by dawidd6** [comment]
Yes. Extensions can support multiple GNOME releases. See https://github.com/NixOS/nixpkgs/pull/291339#issuecomment-2045420740

**Comment by Pandapip1** [comment]
Any chance this'll be ready in time for 24.05?

**Comment by amaxine** [comment]
Rebased with extensions and libjxl support.

**Comment by SeekerOfAsh** [comment]
Hi, sorry if this isn't the correct place to report this, but I noticed that the experimental settings section in dconf / gsettings wasnt present. Without it I'm unable to set experimental flags for VRR or fractional scaling support.

**Comment by amaxine** [comment]
This was hopefully the last rebase to resolve conflicts.

**Comment by amaxine** [comment]
This will land via #306080. No further changes will be made to this PR going forward. This PR will hopefully close as merged when that's merged, but who knows how GitHub will act :woman_shrugging:

**Comment by jonringer** [comment]
> This PR will hopefully close as merged when that's merged, but who knows how GitHub will act 🤷‍♀️

This will only be true if there's a comment on the PR saying that it will close this PR. Then merging the staging-next PR will close this.

**Comment by vcunat** [comment]
I'd have closed it, but I don't much like PRs to stay red even though they've been merged really.

**Comment by amaxine** [comment]
> This will only be true if there's a comment on the PR saying that it will close this PR.

This is wrong. GitHub recongises proper merges into the main branch of a repo if the commits match, and since staging-next got this PR in via a merge commit that preserved this entire history, GitHub will either close-close this PR as all included commits landed via another PR, or close-merge it as all included commits are in the main branch - this is ambiguous to me and I don't think made clear in any documentation.

**Comment by jonringer** [comment]
> GitHub recongises proper merges into the main branch of a repo if the commits match, and since staging-next got this PR in via a merge commit that preserved this entire history, GitHub will either close-close this PR as all included commits landed via another PR, or close-merge it as all included commits are in the main branch - this is ambiguous to me and I don't think made clear in any documentation.

TIL

**Comment by rhendric** [comment]
Thank you for corralling all of this, @amaxine!

**Comment by vcunat** [comment]
The merge broke `glib` build on aarch64-darwin (and maybe more):
```
Program g-ir-scanner found: NO

meson.build:2553:14: ERROR: Program 'g-ir-scanner' not found or not executable
```

**Comment by linsui** [comment]
Should I target my PR depending on this PR to staging-next?

**Comment by jtojnar** [comment]
Yes, please target `staging-next`.

**Comment by bobby285271** [comment]
> https://github.com/NixOS/nixpkgs/pull/291339#issuecomment-2071299937

More specifically it is the first glib used to bootstrap the first gobject-introspection that fails. Some merge conflicts are wrongly resolved I guess, in [the original fixup](https://github.com/NixOS/nixpkgs/pull/293682/files#diff-412d507a3b7ec91dfaf84056ca7d6c86a06365470827cc926eaaec1832c8c4da) I would expect e.g. also build [man page](https://github.com/GNOME/glib/commit/031e65808d443f16ce3c492dfe72f24725ca1bd1) on darwin, having `(lib.mesonEnable "introspection" withIntrospection)` on darwin etc.

**Comment by vcunat** [comment]
For reference, glib should be fixed by PR #306215

**Comment by PerchunPak** [comment]
Daily driving GNOME 46 for a few weeks already, so far no problems, just enjoying this release

**Comment by jcmolinajr** [comment]
> Daily driving GNOME 46 for a few weeks already, so far no problems, just enjoying this release

Pardon my ignorance. How can I try 46 already?

**Comment by peigongdsd** [comment]
> > Daily driving GNOME 46 for a few weeks already, so far no problems, just enjoying this release
> 
> Pardon my ignorance. How can I try 46 already?

Use staging-next branch of nixpkgs.

**Comment by PaulGrandperrin** [comment]
It's in master and unstable-small but not unstable yet: https://nixpk.gs/pr-tracker.html?pr=291339

**Comment by Lyndeno** [comment]
Polkit authentication, via pkexec or 1password, fails as the password prompt does not show up on Gnome 46

**Comment by Andreas02-dev** [comment]
> > Daily driving GNOME 46 for a few weeks already, so far no problems, just enjoying this release
> 
> Pardon my ignorance. How can I try 46 already? 

Friendly ping to let you know it is now also available in NixOS Unstable.

**Comment by linuxmobile** [comment]
> Friendly ping to let you know it is now also available in NixOS Unstable.

It's Ready.

image

**Comment by BillHuang2001** [comment]
After upgrading to Gnome 46, I am experiencing a ["click-through" bug](https://gitlab.gnome.org/GNOME/mutter/-/issues/3404), which makes many full-screen apps/games unusable. I noticed the issue is marked resolved on GitLab, perhaps there are some missing patches?

**Comment by Aleksanaa** [comment]
For people wanting to report bugs, please open a new issue.

**Pull request merged**
