### PR TITLE
lemmy-{server,ui}: 0.18.5 → 0.19.1

### PR DESCRIPTION
**Pull request by arjan-s**
## Description of changes

https://github.com/LemmyNet/lemmy/releases/tag/0.19.1

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by arjan-s** [comment]
Still draft because I can't get it to build

**Comment by matejc** [comment]
I get this error, while it was running lemmy server tests (build itself for ui and server went ok):
```
test session_middleware::tests::test_session_auth ... FAILED
```
That leads to:
https://github.com/LemmyNet/lemmy/issues/3979

**Comment by arjan-s** [comment]
That's a different issue actually. This is the output from our failure:

```
running 2 tests
test scheduled_tasks::tests::test_nodeinfo ... ignored
test session_middleware::tests::test_session_auth ... FAILED

failures:

---- session_middleware::tests::test_session_auth stdout ----
thread 'session_middleware::tests::test_session_auth' panicked at crates/utils/src/settings/mod.rs:20:20:
Failed to load settings file, see documentation (https://join-lemmy.org/docs/en/administration/configuration.html): LemmyError { message: Unknown("No such file or directory (os error 2)"), inner: No such file or directory (os error 2), context: SpanTrace [] }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    session_middleware::tests::test_session_auth

test result: FAILED. 0 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.00s
```
As far as I understand it, something should be fixed in `nixos/tests/lemmy.nix` or `pkgs/servers/web-apps/lemmy/server.nix` to make sure a settings file is available in the location where the tests expect them, but I'm afraid I don't have the time to dive into it.

**Comment by matejc** [comment]
@arjan-s Well at least it leads to the issue that I linked. If I fix the issue of config file not found, I get this error:

```
running 2 tests
test scheduled_tasks::tests::test_nodeinfo ... ignored
test session_middleware::tests::test_session_auth ... FAILED

failures:

---- session_middleware::tests::test_session_auth stdout ----
thread 'session_middleware::tests::test_session_auth' panicked at crates/db_schema/src/utils.rs:281:56:
Error connecting to postgres://lemmy:password@localhost:5432/lemmy: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
```

The fix for config file not found, add the following to the ./lemmy/server.nix, inside buildRustPackage:
```
  LEMMY_CONFIG_LOCATION = "${src}/config/config.hjson";
```

**Comment by arjan-s** [comment]
@matejc Thanks for picking this up! I've been lacking time and my server running Lemmy is offline.

**Pull request closed without merging**
