### PR TITLE
fzf: use full path of output in the scripts

### PR DESCRIPTION
**Pull request by otavio**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 226847` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>fzf</li>
    <li>fzf.man (fzf.man.man)</li>
  </ul>
</details>

**Comment by zowoq** [comment]
Why? I don't see how this is a problem, `fzf` needs to be in PATH to be used anyway?

**Comment by otavio** [comment]
In my use case, I use it without it being in `PATH`, and this allows it to work. Do you see a problem adding this?

**Comment by zowoq** [comment]
> In my use case, I use it without it being in PATH, and this allows it to work. 

How are you sourcing these scripts but not having `fzf` in PATH?

>  Do you see a problem adding this?

Yes, it's fragile and unnecessary for most (if not almost all) use cases.

**Comment by otavio** [comment]
For some build environments where we use Docker and the user's shell, where the shell profile is used, and `/nix` is available. So all use Docker, and the user shell keeps working.

**Comment by zowoq** [comment]
I don't think we need to have this here, better off in an overlay.

**Pull request closed without merging**
