### PR TITLE
pebble: 2.4.0 -> 2.6.0

### PR DESCRIPTION
**Pull request by afh**
## Description of changes

This is a follow up PR for #322331, which was prematurely merged and reverted in #331718.

Open tasks that beed to be addressed prior merging:
- [x] Fix tests (see #346023, kudos to @m1cr0man)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by afh** [comment]
@m1cr0man any information you could share that would help fixing the tests?
Happy to give this a try with input from you in case you are pressed for time currently 🙂

**Comment by afh** [comment]
Result of `nixpkgs-review pr 331721` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pebble</li>
  </ul>
</details>

**Comment by m1cr0man** [comment]
I haven't looked too deep into it but there is a function called check_issuer in the test suite that tries to read and validate the cert's subject to determine if it is still self signed or not:
https://github.com/NixOS/nixpkgs/blob/c1e944804f918e3b2e876cf490cd9c2402e1b2b4/nixos/tests/acme.nix#L479

We need to find a new mechanism for checking the issuer or otherwise checking if the cert is issued by pebble and this self signed. I would go for the easiest solution you can think of. I was considering testing if the issuer was _not_ minica but that may break in the same way if minica also updates in the future.

**Comment by afh** [comment]
@GrahamcOfBorg test acme

**Comment by emilazy** [comment]
Fixing the PR name to stop @r-ryantm opening new ones.

**Comment by afh** [comment]
@m1cr0man haven't been able to make any progress here and I think the understanding required to address this exceeds my current one. Do you think you could help out here?

**Comment by m1cr0man** [comment]
Yes I'll try my best to do it this week.

**Comment by afh** [comment]
Much appreciated, @m1cr0man, thank you 🙏

**Comment by m1cr0man** [comment]
Finally got time to find a solution. I'll hopefully commit it tomorrow if the test passes for the new + old versions of pebble.

**Comment by afh** [comment]
As the project is nearing another release, any chance that this PR might make it into it, @m1cr0man?

**Comment by m1cr0man** [comment]
Yes, I'm quite hopeful. I apologise for my slowness again. This week is looking good time wise for me.

**Comment by afh** [comment]
Thanks for the update, @m1cr0man, much appreciated 🙂

**Comment by m1cr0man** [comment]
Finally got a PR up :) https://github.com/NixOS/nixpkgs/pull/346023

I found a relatively simple way to do it in the end. I'm somewhat ashamed it took me a month to make a 10 line change but it is what it is.

**Comment by afh** [comment]
Time to rejoice! Thanks so much, @m1cr0man, for coming up with a fix for the tests!

No need to feel ashamed about a small change some time; we all have our obligations that need our attention, even if we'd like to dedicate ourselves to other matters.

What's the best way to move forward with this PR and your fix?
Can they merged separately?
Should your fix be merged first or into this PRs merge branch?

**Comment by flokli** [comment]
@m1cr0man with https://github.com/NixOS/nixpkgs/pull/346023 merged, can you rebase this on top of master?

**Comment by afh** [comment]
Sure thing, @flokli, this PR branch is now rebased on top of master.

**Comment by emilazy** [comment]
@ofborg test acme

**Comment by flokli** [comment]
@m1cr0man can you take a look at the failure for x86_64-linux? I'm sure it's a flake that'd probably not appear the next time we trigger it, but it might make sense to harden against this too.

**Comment by flokli** [comment]
Oh sorry, @afh is the author. 😆

**Comment by m1cr0man** [comment]
> @m1cr0man can you take a look at the failure for x86_64-linux? I'm sure it's a flake that'd probably not appear the next time we trigger it, but it might make sense to harden against this too.

It seems to have failed because Apache did not start before the Http-01 renewal was tested. It doesn't even look like a race. This might be a really recent regression between now and my last pull of master on my test host. I'll check it out tonight. Hopefully it's something simple, because I tested all permutations of my 2 prs plus this one.

**Comment by afh** [comment]
The [nixosTests.acme on aarch64-darwin Details](https://github.com/NixOS/nixpkgs/pull/331721/checks?check_run_id=31027141323) include the following:

```
error: a 'aarch64-linux' with features {} is required to build '/nix/store/74sagphiibdwpy2if8wagijl3phz918s-boot.json.drv', but I am a 'aarch64-darwin' with features {benchmark, big-parallel, nixos-test}
```

**Comment by emilazy** [comment]
It’s a NixOS test, it’s not expected to build on Darwin (without a Linux builder).

**Comment by afh** [comment]
Given that all checks passed, except for the darwin checks, which are expected not to run/pass, what is missing in order to get this reviewed and ideally merged?

**Review by emilazy — APPROVED** [review]
Nothing.

**Comment by emilazy** [comment]
(I’m assuming you tested that this works on 32‐bit now?)

**Comment by afh** [comment]
I did by:

* creating a temporary package `pebble32 = callPackage_i686 ../tools/admin/pebble { };` in `pkgs/top-level/all-packages.nix`
* successfully building that using `nix build .#pebble32`
* then successfully running `./result/bin/pebble --version`
* all of the above on one of the community builders

Does this suffice as testing it works on 32-bit now, @emilazy?

**Comment by emilazy** [comment]
Yeah, the error looks like a compiler one anyway so checking it builds SGTM :)

Thanks for this.

**Pull request merged**
