### PR TITLE
 modules/virtualisation/qemu-vm: always enable serial console

### PR DESCRIPTION
**Pull request by flokli**
###### Motivation for this change

Don't make serial console activation dependent on graphical.
Even in qemu graphical mode, you can switch to the serial console via
Ctrl+Alt+3.

With that being done, you also don't need to specify
`systemd.services."serial-getty@ttyS0".enable = true;` either as described in
https://nixos.wiki/wiki/Cheatsheet#Building_a_service_as_a_VM_.28for_testing.29,
as systemd automatically spawns a getty on consoles passwd via cmdline.

This also means, vms built by `nixos-rebuild build-vm` can simply be run
properly in nographic mode by appending `-nographic` to `result/bin/run-*-vm`,
without the need to explicitly add platform-specific `QEMU_KERNEL_PARAMS.`

/cc @dezgeg 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by flokli** [comment]
@GrahamcOfBorg test ipv6

**Comment by dezgeg** [comment]
Sounds like a good idea. Does this affect the graphical usage though? I have some recollection that for some reason or another, I needed to specify `console=ttyS0,115200n8 console=tty0` and in this specific order for things to work in both cases.

**Comment by flokli** [comment]
Right, order is important, and I missed that :-)

Kernel messages will be sent to all passed consoles, but only the last one will be the one `/dev/console` is pointing to (that will be the one normally used for initrd and systemd output).

So I fear this is also platform-specific, or what is `tty0` pointing to on qemu aarch32/aarch64 'virt' board?

Regarding `/dev/console`: We should probably should just use `/dev/console` in `modules/system/boot/stage-1-init.sh` instead of what we currently do (`tty1` for stage1, and parsing `cmdline` for stage2) /cc @edolstra

**Comment by dezgeg** [comment]
`tty0` should always be the first virtual console regardless of platform... which in the case of QEMU for ARM/AArch64 will point to nothingness, until you plug in a emulated graphics card.

> Kernel messages will be sent to all passed consoles, but only the last one will be the one /dev/console is pointing to (that will be the one normally used for initrd and systemd output).

Right, that was the problem; it's actually impossible to have e.g. the initrd ask for a passphrase and be able to respond to it from either the virtual console or the serial console.

Fortunately, most of the time the user doesn't need to interact with stage-1, just see its output. In fact stage-1 already tries to capture the output so it ends up in journalctl: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/stage-1-init.sh#L89. Maybe that code could be extended so that it shows up on the other consoles as well. (In fact, I don't understand why that isn't happening with the current code, given it's writing to `/dev/kmsg`).

**Comment by flokli** [comment]
I changed the PR. Now consoles on `tty0` and `$qemuSerialDevice` will be enabled, with `tty0` being the preferred one - as long as `cfg.graphics` is `true` (the default). Otherwise, the console order will be reversed.

**Comment by dezgeg** [comment]
This one sounds good to me.

BTW, regarding `/dev/console`, most other initrd implementations don't use it either, due to e.g. this (in Debian initramfs-tools):
````
commit 619f2caded3910e5be4338c7b01d183ed4484eb6
Author: Ben Hutchings <ben@decadent.org.uk>
Date:   Wed Dec 9 18:54:59 2015 +0000

    scripts/functions: Connect panic shell to normal tty device
    
    Currently the panic shell's controlling tty is /dev/console which is
    not fully functional - the shell can't provide job control and more
    can't work out the screen size for paging.
    
    Fix this by reading /proc/consoles to find out the underlying tty
    device and then connecting the shell to it directly with the aid of
    setsid.
    
    Closes: #512679
    Signed-off-by: Ben Hutchings <ben@decadent.org.uk>

diff --git a/scripts/functions b/scripts/functions
index 531d1bd..67ce319 100644
--- a/scripts/functions
+++ b/scripts/functions
@@ -33,6 +33,8 @@ log_end_msg()
 
 panic()
 {
+       local console rest
+
        if command -v chvt >/dev/null 2>&1; then
                chvt 1
        fi
@@ -48,7 +50,20 @@ panic()
 
        run_scripts /scripts/panic
 
-       REASON="$@" PS1='(initramfs) ' /bin/sh -i </dev/console >/dev/console 2>&1
+       # Try to use setsid, which will enable job control in the shell
+       # and paging in more
+       if command -v setsid >/dev/null 2>&1; then
+               read console rest </proc/consoles
+               if [ "${console}" = "tty0" ]; then
+                       # Need to choose a specific VT
+                       console="tty1"
+               fi
+               # We don't have 'setsid -c' so we need to setsid, open
+               # the tty, and finally exec an interactive shell
+               REASON="$@" PS1='(initramfs) ' setsid sh -c "exec sh -i <>/dev/${console} 1>&0 2>&1"
+       else
+               REASON="$@" PS1='(initramfs) ' sh -i </dev/console >/dev/console 2>&1
+       fi
 }
 
 maybe_break()
````

**Comment by flokli** [comment]
This explains it. Thanks!

Additionally, I misread `stage-1-init.sh` - code using `/dev/${console}` lives inside a `fail()` function, and in almost all cases, the `console` variable already mirrors the preferred console when being called - with the exception of a `boot.debug1` or `debug1` passed via cmdline before the `console=` parameters.

**Pull request merged**
