### PR TITLE
python-updates - major updates - 2022-12-29

### PR DESCRIPTION
**Pull request by mweinelt**
Major changes:
- Stop recursing into python39Packages
- Begin recursing into python311Packages
- See via https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks
- Drop python37

Jobset:
- https://hydra.nixos.org/jobset/nixpkgs/python-updates#tabs-evaluations

Reports:
- https://shells.darmstadt.ccc.de/~hexa/549.html

Dropped updates:
- sphinx 6.0; too early; several documentation builds fail, no issues/patches found
  - upgraded to 5.3.0 instead
- elasticsearch 8.x, breaks elasticsearch-dsl, which seems abandoned, but is still widely used

Needs help:
- [ ] Getting the `greenlet` tests running again https://hydra.nixos.org/build/203639056
- [x] Getting the `scikit-build` tests running again https://hydra.nixos.org/build/203635081
- [ ] `clevercsv` fails to build
  - `AttributeError: 'MinimalDistribution' object has no attribute 'set_defaults'`

TODO:
- [x] Collect open PRs
- [x] Bulk updates
- [x] Early fixes
- [x] Start Evaluation https://hydra.nixos.org/jobset/nixpkgs/python-updates

### CODE REVIEW

**Comment by mweinelt** [comment]
@ofborg eval

**Comment by kirillrdy** [comment]
@mweinelt fixup awsebcli, https://github.com/NixOS/nixpkgs/pull/208593

**Comment by lourkeur** [comment]
#208955 should fix a couple leaf packages

**Comment by lourkeur** [comment]
#209052 missed a line for chia

**Comment by trofi** [comment]
Bisect says 7bd043148707030431c72d55d6839b73d210e4ba `python3Packages.sphinx: 5.1.1 -> 5.3.0` broke `python3Packages.breathe` package in `staging` and `staging-next`:

```
$ nix build --no-link -f. -L python3Packages.breathe
...
python3.10-breathe> =================================== FAILURES ===================================
python3.10-breathe> _______________________________ test_render_func _______________________________
python3.10-breathe> app = <SphinxTestApp buildername='html'>
python3.10-breathe>     def test_render_func(app):
python3.10-breathe>         member_def = WrappedMemberDef(
python3.10-breathe>             kind="function",
python3.10-breathe>             definition="void foo",
python3.10-breathe>             type_="void",
python3.10-breathe>             name="foo",
python3.10-breathe>             argsstring="(int)",
python3.10-breathe>             virt="non-virtual",
python3.10-breathe>             param=[
python3.10-breathe>                 WrappedParam(type_=WrappedLinkedText(content_=[WrappedMixedContainer(value="int")]))
python3.10-breathe>             ],
python3.10-breathe>         )
python3.10-breathe> >       signature = find_node(render(app, member_def), "desc_signature")
python3.10-breathe> tests/test_renderer.py:321:
python3.10-breathe> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
python3.10-breathe> tests/test_renderer.py:306: in render
python3.10-breathe>     return renderer.render(member_def)
python3.10-breathe> breathe/renderer/sphinxrenderer.py:2602: in render
python3.10-breathe>     result = method(self, node)
python3.10-breathe> breathe/renderer/sphinxrenderer.py:2489: in dispatch_memberdef
python3.10-breathe>     return self.visit_function(node)
python3.10-breathe> breathe/renderer/sphinxrenderer.py:1981: in visit_function
python3.10-breathe>     nodes = self.handle_declaration(node, declaration)
python3.10-breathe> breathe/renderer/sphinxrenderer.py:667: in handle_declaration
python3.10-breathe>     nodes_ = self.run_directive(obj_type, declaration, content_callback, options)
python3.10-breathe> breathe/renderer/sphinxrenderer.py:619: in run_directive
python3.10-breathe>     nodes = directive.run()
python3.10-breathe> /nix/store/f65njnrbnha44fwhgxz2s5s9a3hrprwz-python3.10-sphinx-5.3.0/lib/python3.10/site-packages/sphinx/domains/cpp.py:7345: in run
python3.10-breathe>     return super().run()
python3.10-breathe> /nix/store/f65njnrbnha44fwhgxz2s5s9a3hrprwz-python3.10-sphinx-5.3.0/lib/python3.10/site-packages/sphinx/directives/__init__.py:263: in run
python3.10-breathe>     nested_parse_with_titles(self.state, self.content, contentnode)
python3.10-breathe> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
python3.10-breathe> state = <test_renderer.MockState object at 0x7ffff482c670>, content = None
python3.10-breathe> node = <desc_content: >
python3.10-breathe>     def nested_parse_with_titles(state: Any, content: StringList, node: Node) -> str:
python3.10-breathe>         """Version of state.nested_parse() that allows titles and does not require
python3.10-breathe>         titles to have the same decoration as the calling document.
python3.10-breathe>
python3.10-breathe>         This is useful when the parsed content comes from a completely different
python3.10-breathe>         context, such as docstrings.
python3.10-breathe>         """
python3.10-breathe>         # hack around title style bookkeeping
python3.10-breathe> >       surrounding_title_styles = state.memo.title_styles
python3.10-breathe> E       AttributeError: 'MockState' object has no attribute 'memo'
python3.10-breathe> /nix/store/f65njnrbnha44fwhgxz2s5s9a3hrprwz-python3.10-sphinx-5.3.0/lib/python3.10/site-packages/sphinx/util/nodes.py:335: AttributeError
...
python3.10-breathe> =========================== short test summary info ============================
python3.10-breathe> FAILED tests/test_renderer.py::test_render_func - AttributeError: 'MockState' object has no attribute 'memo'
python3.10-breathe> FAILED tests/test_renderer.py::test_render_typedef - AttributeError: 'MockState' object has no attribute 'memo'
python3.10-breathe> FAILED tests/test_renderer.py::test_render_c_typedef - AttributeError: 'MockState' object has no attribute 'memo'
python3.10-breathe> FAILED tests/test_renderer.py::test_render_c_function_typedef - AttributeError: 'MockState' object has no attribute 'memo'
python3.10-breathe> FAILED tests/test_renderer.py::test_render_using_alias - AttributeError: 'MockState' object has no attribute 'memo'
python3.10-breathe> FAILED tests/test_renderer.py::test_render_const_func - AttributeError: 'MockState' object has no attribute 'memo'
python3.10-breathe> FAILED tests/test_renderer.py::test_render_lvalue_func - AttributeError: 'MockState' object has no attribute 'memo'
python3.10-breathe> FAILED tests/test_renderer.py::test_render_rvalue_func - AttributeError: 'MockState' object has no attribute 'memo'
python3.10-breathe> FAILED tests/test_renderer.py::test_render_const_lvalue_func - AttributeError: 'MockState' object has no attribute 'memo'
python3.10-breathe> FAILED tests/test_renderer.py::test_render_const_rvalue_func - AttributeError: 'MockState' object has no attribute 'memo'
python3.10-breathe> FAILED tests/test_renderer.py::test_render_variable_initializer - AttributeError: 'MockState' object has no attribute 'memo'
python3.10-breathe> FAILED tests/test_renderer.py::test_render_define_initializer - AttributeError: 'MockState' object has no attribute 'memo'
python3.10-breathe> FAILED tests/test_renderer.py::test_render_define_no_initializer - AttributeError: 'MockState' object has no attribute 'memo'
python3.10-breathe> ================= 13 failed, 8 passed, 1173 warnings in 11.51s =================
```

**Comment by fabianhjr** [comment]
@trofi et al., got a patch from upstream: https://github.com/NixOS/nixpkgs/pull/209570

**Comment by trofi** [comment]
Bisect says a80621064228f8a822b5bf7bea41054b9dee68dd `python3Packages.fonttools: 4.34.4 -> 4.38.0` broke `python3Packages.afdko` in `staging-next` and `staging` as:

```
$ nix build --no-link -f. -L python3Packages.afdko
...
python3.10-afdko> tests/buildcff2vf_test.py .F........                                     [  0%]
...
python3.10-afdko> =================================== FAILURES ===================================
python3.10-afdko> ______________________________ test_sparse_cjk_vf ______________________________
python3.10-afdko>     def test_sparse_cjk_vf():
python3.10-afdko>         # subset fonts to lists in 'SHSansJPVFTest.subset.txt'
python3.10-afdko>         # Check compatibility. Issue is in cid00089.
python3.10-afdko>         # keep PostScript names
python3.10-afdko>         input_dir = get_input_path('CJKSparseVar')
python3.10-afdko>         temp_dir = get_temp_dir_path('CJKSparseVar')
python3.10-afdko>         copytree(input_dir, temp_dir)
python3.10-afdko>         ds_path = os.path.join(temp_dir, 'SHSansJPVFTest.designspace')
python3.10-afdko>         subset_path = os.path.join(temp_dir, 'SHSansJPVFTest.subset.txt')
python3.10-afdko>         runner(CMD + ['-o', 'd', f'_{ds_path}', 'i', f'_{subset_path}', 'c', 'k'])
python3.10-afdko>         actual_path = os.path.join(temp_dir, 'SHSansJPVFTest.otf')
python3.10-afdko>         actual_ttx = generate_ttx_dump(actual_path,
python3.10-afdko>                                        ['CFF2', 'HVAR', 'avar', 'fvar'])
python3.10-afdko>         expected_ttx = get_expected_path('SHSansJPVFTest.ttx')
python3.10-afdko> >       assert differ([expected_ttx, actual_ttx, '-s', '<ttFont sfntVersion'])
python3.10-afdko> E       AssertionError: assert False
python3.10-afdko> E        +  where False = differ(['/build/afdko-3.9.0/tests/buildcff2vf_data/expected_output/SHSansJPVFTest.ttx', '/build/tmp2s2prze7', '-s', '<ttFont sfntVersion'])
python3.10-afdko> tests/buildcff2vf_test.py:63: AssertionError
python3.10-afdko> ----------------------------- Captured stdout call -----------------------------
python3.10-afdko> --- /build/afdko-3.9.0/tests/buildcff2vf_data/expected_output/SHSansJPVFTest.ttx
python3.10-afdko> +++ /build/tmp2s2prze7
python3.10-afdko> @@ -9,3 +9,3 @@
python3.10-afdko>        <FontMatrix value="0.001 0 0 0.001 0 0"/>
python3.10-afdko> -      <FDSelect format="3"/>
python3.10-afdko> +      <FDSelect format="0"/>
...
python3.10-afdko> =========================== short test summary info ============================
python3.10-afdko> FAILED tests/buildcff2vf_test.py::test_sparse_cjk_vf - AssertionError: assert False
python3.10-afdko> = 1 failed, 1215 passed, 4 skipped, 99 deselected, 8 xfailed in 120.59s (0:02:00) =
```

**Comment by cfhammill** [comment]
This PR broke catboost for at least python310, but I suspect all pythons, the build fails because the patches can no longer be applied

**Comment by dotlambda** [comment]
> This PR broke catboost for at least python310, but I suspect all pythons, the build fails because the patches can no longer be applied

Please open an issue in which you ping the maintainer @PlushBeaver.
Maybe @veprbl is also interested in fixing this. See https://github.com/NixOS/nixpkgs/pull/208317.

**Comment by dotlambda** [comment]
> I _think_ this PR broke mailman-web according to [Hydra](https://hydra.nixos.org/build/205412309):

Please review https://github.com/NixOS/nixpkgs/pull/212926 which fixes mailman-web.

**Comment by alyssais** [comment]
The mediapy update (https://github.com/NixOS/nixpkgs/commit/afc23a5a3b42ce7498743edfb7ffc32d74a78023) seems to have broken it:

```
Executing setuptoolsBuildPhase
Traceback (most recent call last):
  File "/build/mediapy-1.1.2/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "/nix/store/abax98471z8fshv4b9p46bkh3lxmpy0z-python3-3.10.9/lib/python3.10/tokenize.py", line 394, in open
    buffer = _builtin_open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'setup.py'
```

**Pull request merged**
