### PR TITLE
rqbit: 6.0.0 -> 7.0.1

### LINKED ISSUE #339231: Update request: rqbit 6.0.0 → 7.0.1
- Package name: rqbit
- Latest released version: 7.0.1

- Current version on the unstable channel: 6.0.0
- Current version on the stable/release channel: 5.6.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@cafkafk 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Daru-san**
Aims to update rqbit to 7.0.

Closes: #339231 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Daru-san** [comment]
Build seems to be working so far until we reach this error:
```
┃ error: builder for '/nix/store/5xiw7b8dba977hm11dpyxk20gcv3p4hb-rqbit-desktop-7.1.0.drv' failed with exit code 1;
┃        last 17 log lines:
┃        > Running phase: unpackPhase
┃        > unpacking source archive /nix/store/b03cxbz1b7ihfjn50x36gvgy5vgqmb40-source
┃        > source root is source/desktop/src-tauri
┃        > Executing cargoSetupPostUnpackHook
┃        > Finished cargoSetupPostUnpackHook
┃        > Running phase: patchPhase
┃        > Executing cargoSetupPostPatchHook
┃        > Validating consistency between /build/source/desktop/src-tauri/Cargo.lock and /build/cargo-vendor-dir/Cargo.lock
┃        > Finished cargoSetupPostPatchHook
┃        > Running phase: updateAutotoolsGnuConfigScriptsPhase
┃        > Running phase: configurePhase
┃        > Running phase: buildPhase
┃        > Executing tauriBuildHook
┃        > cargo-tauri.hook cargoFlags: -j 6 --target x86_64-unknown-linux-gnu --offline --profile release
┃        > cargo-tauri.hook tauriFlags: --bundles deb --target x86_64-unknown-linux-gnu
┃        > error: Permission denied (os error 13) at path "/build/source/targetIQG8d6"
┃        >     Error failed to build app: failed to build app
┃        For full logs, run 'nix log /nix/store/5xiw7b8dba977hm11dpyxk20gcv3p4hb-rqbit-desktop-7.1.0.drv'.
```

**Comment by Daru-san** [comment]
Made good progress but now running into this:
```
┏━ 1 Errors: 
 ⋮ 
┃        >    Compiling urlencoding v2.1.3
┃        >    Compiling librqbit-tracker-comms v2.0.0 (/build/source/crates/tracker_comms)
┃        >    Compiling tempfile v3.12.0
┃        >    Compiling tar v0.4.41
┃        >    Compiling librqbit-upnp-serve v0.1.0 (/build/source/crates/upnp-serve)
┃        >    Compiling tracing-subscriber v0.3.18
┃        > error: failed to run custom build command for `librqbit v7.0.1 (/build/source/crates/librqbit)`
┃        >
┃        > Caused by:
┃        >   process didn't exit successfully: `/build/source/desktop/src-tauri/target/release/build/librqbit-9a6dc49cc61f7e3c/build-script-build` (exit status: 101)
┃        >   --- stdout
┃        >   cargo:rerun-if-changed=webui/src
┃        >
┃        >   --- stderr
┃        >   thread 'main' panicked at /build/source/crates/librqbit/build.rs:52:37:
┃        >   called `Result::unwrap()` on an `Err` value: "npm install" failed
┃        >
┃        >   stderr: sh: line 1: npm: command not found
┃        >
┃        >
┃        >   stdout:
┃        >   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
┃        > warning: build failed, waiting for other jobs to finish...
┃        >     Error failed to build app: failed to build app
```

**Comment by Daru-san** [comment]
I have tried to modify and patch the build command of the dependency for a while now. Sadly I have had no luck in that since the file needs to be changed within the entire source and cannot be overridden before building the tauri front-end. 
So I would assume that there is another way to do this. I just have no idea how as of yet. Still working on it.

**Comment by Daru-san** [comment]
It builds! :smile:

**Comment by ToasterUwU** [comment]
@Daru-san Does the rqbit-desktop application open for you? When I try to run it no window pops up for some reason.

**Review by ToasterUwU — COMMENTED** [review]
Besides that part of it not opening, it looks good to me. Thank you very much for putting in the effort to make this arcance build process work with Nix, i certainly wouldnt have been able to do this

**Comment by ToasterUwU** [comment]
Result of `nixpkgs-review pr 350989` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>rqbit</li>
  </ul>
</details>

**Comment by ToasterUwU** [comment]
No idea why Github thought i reviewed this PR, I haven't done anything like that.. Sorry about that weird back and forth

**Comment by Daru-san** [comment]
@ToasterUwU Sadly I have been facing the same issue. It doesn't show anything for me either. 
It seems to be related to this error in some way:
```
2024-10-25T19:49:17.169382Z  WARN rqbit: Error checking HTTP API at http://127.0.0.1:3030/: error sending request for url (http://127.0.0.1:3030/)
```

**Comment by Daru-san** [comment]
It was fun putting this together though, however complicated it was :laughing: 
The debugging never ends though.

**Comment by ToasterUwU** [comment]
@Daru-san I dont see any errors like that. I just see the "file descriptor" INFO message, nothing else

**Comment by Daru-san** [comment]
@ToasterUwU  Oh, that seems to be a different issue. I originally assumed they were related but it does not seem like it.

**Comment by Daru-san** [comment]
That one had to do with torrents, it cannot seem to be able to start any downloads due to an http error.

**Comment by Daru-san** [comment]
I have no idea about the GUI issue though. It may be something in the build process I missed, just not sure what.

**Comment by ToasterUwU** [comment]
I'm also totally unsure, I can take a closer look at some point, but not sure that will reveal anything to me

**Comment by ToasterUwU** [comment]
I took a closer look and I can't see anything missing or something like that. 

Unless you can figure this out yourself, I think its best to remove the broken Desktop app from this and just go with the webserver thing for now. Its really cool you got the Desktop thing to build as well, but sadly I cant approve a broken piece of software to be merged.

**Comment by Daru-san** [comment]
I'll keep working on the desktop UI, but I do agree there. It would be fine to leave that to be merged in when we can actually get it working.

**Comment by Daru-san** [comment]
Taking the focus away from that, there seems to be some issue with connecting to the web UI and downloading torrents when the server service has been started.
That being unable to connect to `http://localhost:3030/web/` on via a web browser, which also seems to have something to do with torrent downloading somehow. 

The error message in rqbit when trying to run a command
```
Daru@Nix> rqbit download {magnet url or torrent file}

2024-10-30T09:20:56.885212Z  INFO rqbit: inreased open file limit limit=524288
2024-10-30T09:20:56.906837Z  WARN rqbit: Error checking HTTP API at http://127.0.0.1:3030/: error sending request for url (http://127.0.0.1:3030/)
2024-10-30T09:20:56.908726Z ERROR rqbit: error running rqbit: output_folder is required if can't connect to an existing server
```

**Comment by Daru-san** [comment]
It works perfectly fine when you download a file without running the `rqbit service` command though, then the web UI runs as well.
```
Daru@Nix> rqbit download {torrent} -o ~/Downloads-dir
```

**Comment by Daru-san** [comment]
@ToasterUwU Further testing seems to have changed the results.  
The service suddenly works perfectly.
See: [screenshot](https://imgur.com/Eu6NZrN).

I am not sure what about my configuration that was changed, actively hunting down the culprit.

#### What's working?
- `rqbit server` downloads using `rqbit download` while the service is running.
- WebUI at `http://localhost:3030/web/`
- Standalone `rqbit download` specifying a download path without the service running

**Comment by ToasterUwU** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 350989`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>rqbit</li>
  </ul>
</details>

**Review by ToasterUwU — APPROVED** [review]

**Comment by ToasterUwU** [comment]
Can confirm that it works, so this is ready for merging, and than you can try the desktop app again in a separate PR if you are still interested

**Comment by ToasterUwU** [comment]
@cafkafk Wanna try and approve as well?

**Review by cafkafk — APPROVED** [review]
LGTM, ty for fixing this

**Pull request merged**
