### PR TITLE
qsynth: 0.3.9 -> 0.4.4

### PR DESCRIPTION
**Pull request by magnetophon**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by orivej** [comment]
Please use `libsForQt5` (see examples in `all-packages.nix`) and put `cmake`, `pkgconfig` in `nativeBuildInputs`.

**Comment by magnetophon** [comment]
@orivej ``cmake`` and ``pkgconfig`` are moved.
I've looked at a couple of examples for ``libsForQt5``, but I don't see the pattern yet.
Could you explain?

Thanks for all the quick merges!

**Comment by orivej** [comment]
You are welcome! See https://nixos.org/nixpkgs/manual/#ssec-qt-applications:
> Call your application expression using libsForQt5.callPackage instead of callPackage. Import dependencies unqualified, i.e., qtbase not qt5.qtbase. Do not import a package set such as qt5 or libsForQt5.

**Comment by magnetophon** [comment]
@orivej Thanks!
Done.

**Pull request merged**
