### PR TITLE
ant: introduce `ant.home`, change ant home to $out/share

### PR DESCRIPTION
**Pull request by tomodachi94**
Everything in the Ant home is platform-agnostic (JARs),
so it should go to $out/share.

Debian puts the Ant home into /usr/share as well, so this
is not unprecedented:
https://salsa.debian.org/java-team/ant/-/blob/31d9fc0a76ac991509fcfc537ffc3dbf61ebc41d/debian/README.Debian

Fedora does too:
https://src.fedoraproject.org/rpms/ant/blob/20b8a9a5596a5fd2b12c1d6f922f4502450db674/f/ant.spec#_39

And Arch Linux:
https://gitlab.archlinux.org/archlinux/packaging/packages/ant/-/blob/e8e0ddb82105f16cd7d8153091c2c6f527d9b371/PKGBUILD#L59

And Gentoo:
https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-java/ant/ant-1.10.15.ebuild?id=55bcd350a89469eac0af4bfafe464050d01154e0#n381

And probably more, I stopped looking :)

This PR also changes a few packages to use the new `passthru.ant_home` variable so we can stay DRY, in case this was to change again.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by tomodachi94** [comment]
Aside: If there are any rebuilds **until the very last commit**, I did something wrong; `${ant.ant_home}` should evaluate to `${ant}/lib/ant` (until said final commit), as used before in some packages.

**Comment by tomodachi94** [comment]
Requesting a review from @7c6f434c and @evan-goode, since this touches LibreOffice and `processing`, respectively.

**Comment by TomaSajt** [comment]
Not very important, but to me, `ant_home` looks out of place, since not many things use snake_case inside nixpkgs.
(at least I'm not aware of many).
I would go with `antHome`, `ant-home` or just `home` (since it would be `ant.home`).

**Review by Mindavi — APPROVED** [review]

**Review by evan-goode — CHANGES_REQUESTED** [review]
Were [some changes](https://github.com/NixOS/nixpkgs/commit/e7dd65f541d1bf58c0cb35323216c5b9bc3a1d8a) lost in a rebase? `processing` does not build since the `ant.home` at `${ant}/share/ant` does not exist.

**Comment by tomodachi94** [comment]
Investigating. It looks like that was the case.

**Comment by tomodachi94** [comment]
Should be fixed in latest push. Let me know if you find anything else that needs changing.

**Review by evan-goode — APPROVED** [review]
LGTM, thanks.

**Review by evan-goode — APPROVED** [review]

**Pull request merged**
