### PR TITLE
python3Packages.xmlschema: 1.3.1 -> 1.4.1

### PR DESCRIPTION
**Pull request by jonringer**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
```
https://github.com/NixOS/nixpkgs/pull/109073

9 packages built:
python37Packages.fints python37Packages.sepaxml python37Packages.xmlschema python38Packages.fints python38Packages.sepaxml python38Packages.xmlschema python39Packages.fints python39Packages.sepaxml python39Packages.xmlschema
```

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 109073` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>python37Packages.fints</li>
    <li>python37Packages.sepaxml</li>
    <li>python37Packages.xmlschema</li>
    <li>python38Packages.fints</li>
    <li>python38Packages.sepaxml</li>
    <li>python38Packages.xmlschema</li>
    <li>python39Packages.fints</li>
    <li>python39Packages.sepaxml</li>
    <li>python39Packages.xmlschema</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
Changelog (https://github.com/sissaschool/xmlschema/blob/master/CHANGELOG.rst) is only mentioning bugfixes and no breaking changes.

Looks good to me.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109073` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
9 packages built:
</summary>
<ul>
<li>python37Packages.fints</li>
<li>python37Packages.sepaxml</li>
<li>python37Packages.xmlschema</li>
<li>python38Packages.fints</li>
<li>python38Packages.sepaxml</li>
<li>python38Packages.xmlschema</li>
<li>python39Packages.fints</li>
<li>python39Packages.sepaxml</li>
<li>python39Packages.xmlschema</li>
</ul>
</details>

**Pull request merged**
