### PR TITLE
zeal: 0.7.0 -> 0.7.1

### PR DESCRIPTION
**Pull request by NickCao**
Diff: https://github.com/zealdocs/zeal/compare/v0.7.0...v0.7.1

Changelog: https://github.com/zealdocs/zeal/releases/tag/v0.7.1

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by peterhoeg** [comment]
What was the status on darwin before?

**Comment by NickCao** [comment]
> What was the status on darwin before?

Also failing https://hydra.nixos.org/eval/1806867?filter=zeal&compare=1806851&full=#tabs-still-fail

**Comment by sikmir** [comment]
> > What was the status on darwin before?
> 
> Also failing https://hydra.nixos.org/eval/1806867?filter=zeal&compare=1806851&full=#tabs-still-fail

Looks like darwin.apple_sdk_11_0 required.

**Review by AndersonTorres — APPROVED** [review]
Can we migrate this to by-name?

**Comment by NickCao** [comment]
> Can we migrate this to by-name?

Are we supposed to use `qt6Packages.callPackage` with `by-name`?

**Comment by AndersonTorres** [comment]
1. afaicr, qt6.callPackage is being discouraged;
2. by experience, it can be easily removed (just some minor refactorings):

**Comment by peterhoeg** [comment]
0.7.0 on current unstable is broken due to qt 6.7.2, so I'm merging this for now to at least get things working again.

**Comment by mjm** [comment]
Zeal still fails to build against qt 6.7.2 with this update, at least when I apply the patch on top of current unstable.

**Comment by peterhoeg** [comment]
Zeal still fails to build against qt 6.7.2 with this update




Yes it does - it was brainfart on my side (I built and tested the qt5 version, which does work).

**Pull request merged**
