### PR TITLE
envoy: fix sha256 for x86_64-linux/aarch64-linux

### PR DESCRIPTION
**Pull request by Mindavi**
###### Description of changes

Fix sha256 for envoy, so it starts building again.

SInce it's such a big package, it might take a while to build (and I might kill it before it's done). But at least it starts building now rather than reporting a hash mismatch.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

ZHF: https://github.com/NixOS/nixpkgs/issues/172160

### CODE REVIEW

**Comment by 06kellyjac** [comment]
Is this a temporary fix? Is there an issue with the fetchAttrs determinism?

(Im not very familiar with Bazel in or out of nixpkgs)



Either way getting this merged to reduce Hydra failures is good

**Comment by Mindavi** [comment]
Honestly, I've no clue. Also the aarch64 needs to be fixed too.

**Comment by srhb** [comment]
I can confirm that it builds on linux at least (and that, indeed, it takes a while... :joy:)

**Comment by lukegb** [comment]
Grr, this built with the old hashes on ofborg yesterday...

Yeah, in general this mechanism isn't fantastic - hashes are likely to change and it can be difficult to test. Wrapping the entire fetch phase in one fixed output derivation is problematic.

I'll look at the aarch64 hash when I get home today

**Comment by lukegb** [comment]
The aarch64 hash is `sha256:1zd8awgc32ngrgd7cw5y18cwcn37k4vbcp2bbiz4488lfv8axhvl`

**Comment by Mindavi** [comment]
Just ran the build again and now it's:

```
error: hash mismatch in fixed-output derivation '/nix/store/0mvrnnb16xg0wdidb2h9d3x2rk0fly5r-envoy-1.21.1-deps.tar.gz.drv':
         specified: sha256-Bu9inDqBU73E2Pd+phqikakdyOGMtr7l+Yh9uYGyTEw=
            got:    sha256-23Z6SbKnbah/NCrdMrXhrNFFASd/8xRH3fSyIE++heA=
error: 1 dependencies of derivation '/nix/store/iradkgzbgvix37zzsfaairmlgxlc1cxg-envoy-1.21.1.drv' failed to build
```

So don't think this is gonna keep working in any way or form like this.

**Comment by lukegb** [comment]
I usually diffoscope cases like this to try to track it down

**Comment by 06kellyjac** [comment]
can you diffoscope the whole thing or is there something specific you need to do to diffoscope the deps/fetchAttrs stuff? Just curious what the process would be here

**Comment by lukegb** [comment]
You can diffoscope the entire deps tarball, yeah.

In this case, @Mindavi I think you're on a commit that doesn't include this one, because the specified hash in your output is the old fetchAttrs hash before this commit, and the got hash is the one _after_ this commit.

**Pull request merged**
