### PR TITLE
Pytricia: init 

### PR DESCRIPTION
**Pull request by mkgvt**
###### Motivation for this change

Packaged pytricia library for inclusion in nixpkgs.

###### Things done

Created pkgs/development/python-modules/pytricia/default.nix.
Added to pkgs/top-level/python-packages.nix.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by aanderse** [comment]
What's up with the package removal? It isn't mentioned in the things done section.

**Comment by mkgvt** [comment]
On Fri, Mar 22, 2019 at 8:04 PM aanderse <notifications@github.com> wrote:

> What's up with the package removal? It isn't mentioned in the things done
> section.
>

I found the same software packaged by someone else who did a better job.

Mark
-- 
Mark Gardner
--

**Comment by mkgvt** [comment]
On Sat, Mar 23, 2019 at 11:02 AM Mark Gardner <mkg@vt.edu> wrote:

> On Fri, Mar 22, 2019 at 8:04 PM aanderse <notifications@github.com> wrote:
>
>> What's up with the package removal? It isn't mentioned in the things done
>> section.
>>
>
> I found the same software packaged by someone else who did a better job.
>

More information. It appears that I accidentally conflated two actions: the
removal of the rename package and the addition of the pytricia package. (I
am a GitHub novice.) My comment above concerns the removal of the rename
package.

Mark
-- 
Mark Gardner
--

**Comment by mkgvt** [comment]
A new PR fixing the noted problems can be found at #61494.

**Pull request closed without merging**
