### PR TITLE
cfdyndns: 0.0.4 -> 0.2.0

### PR DESCRIPTION
**Pull request by nrdxp**
## Description of changes

Update binary version to 0.2.0. ~~Leaving in draft now as I'm not sure if @colemickens will want to merge this into his repo, or allow me to take over maintainership yet~~ ready for review

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
@nrdxp one question regarding this package.
Currently, the way the secrets are passed is through an environment variable
```
export CLOUDFLARE_APITOKEN="$(cat '/run/agenix/CLOUDFLARE_API_TOKEN')"
```
so passing an actual secret from agenix will fail.
Do you think we could change the mechanism, so that the binary takes a CLOUDFLARE_APITOKEN_FILE as an env var input ?
then we can just use the LoadCredential mechanism to pass it to the binary.

(on a separate note, we can just use dynamicUser and remove the user and group from the service).

if you are open to the change but not too keen on making it, just let me know.

**Comment by happysalada** [comment]
Hey, just wondering if the git dependency cant be removed ? That would save us from committing the lockfile to the repo ?

**Comment by happysalada** [comment]
Also just posting here as a question.
I was thinking that maybe in the future, the module needs to be changed a bit so as to enable several domains. Right now a token is only available per domain. We should potentially have a config where several tokens can be provided (probably each spinning an instance of cfdyndns).

**Comment by nrdxp** [comment]
> Hey, just wondering if the git dependency cant be removed ? That would save us from committing the lockfile to the repo ?

The git deps are only for patching two crates from crates.io which are both required fixes for the time being, unless or until the upstream PRs are merged.

> I was thinking that maybe in the future, the module needs to be changed a bit so as to enable several domains. Right now a token is only available per domain.

You should be able to generate a CF token that has access to multiple DNS zones on your account. It's up to the user to scope their tokens correctly. Or are you talking about using different tokens from disperate CF accounts entirely?

**Comment by happysalada** [comment]
If there is no ways to remove the git dependencies in the short term and PRs for upstream are opened, im happy to merge this. Are you okay with that or do you need more feedback ?

Thank you for the multiple domains tokens, i wasnt aware, im going to try it.

**Comment by nrdxp** [comment]
> Are you okay with that or do you need more feedback ?

That is fine by me. The current version is horribly broken so we need to get this updated ASAP. I'm already using this version on my local system without any issues, so it should be safe.

**Pull request merged**
