### PR TITLE
openfortivpn-webview: init at 1.2.0-electron

### LINKED ISSUE #322615: Package request: openfortivpn-webview
**Project description**

Application to perform the SAML single sign-on and easily retrieve the SVPNCOOKIE needed by openfortivpn.

**Metadata**

* homepage URL: https://github.com/gm-vm/openfortivpn-webview
* source URL: https://github.com/gm-vm/openfortivpn-webview
* license: mit
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by emilioziniades**
## Description of changes

Adds openfortivpn webview.

Closes #322615.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilioziniades** [comment]
Hi @madjar, @marsam and @lilyinstarlight. Sorry for the random review request, I wasn't quite sure who to put on this PR team, and since this is an electron project, I thought it would make sense for the node team to have a look.

Also hi @winterqt! I saw you were the maintainer for openfortivpn, and since this is a related project, I thought a review from you would make sense.

If you know of anyone better to review this, please point me in the right direction.

Thanks

**Comment by feinerer** [comment]
Tested functionality, it works for me on NixOS 24.05 x86_64-linux.

**Comment by winterqt** [comment]
> Also hi @winterqt! I saw you were the maintainer for openfortivpn, and since this is a related project, I thought a review from you would make sense.

I'm not, and have never been. Wrong person? :)

**Comment by emilioziniades** [comment]
Sorry @winterqt, think I added you because you are on the nodejs team. Apologies. @madjar is the openfortivpn maintainer :)

**Pull request closed without merging**
