### PR TITLE
libinput: Fix commands

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change

Running subcommands like `libinput measure` requires python and some python modules. 

I previously added the dependencies in <https://github.com/NixOS/nixpkgs/pull/51304> but <https://github.com/NixOS/nixpkgs/commit/de14f0c6e1247aa48b0d77c4a3390a61e020bebf> accidentally moved them to checkInputs so they are not available at runtime by patchShebangs (especially since tests are disabled).

Additionally, the tools were ported from evdev python module to python-libevdev in libinput 1.14, which was [missed][3] during upgrade.

Finally, other python modules are needed so let's add them as well.

[3]: https://github.com/NixOS/nixpkgs/commit/b291f2a9953d48d6edc5c73776db9ba289ccf213

###### Closure size
```
before:
/nix/store/q1fzqnxjfiklxxw0w43amavbg9171vs0-libinput-1.15.5    	  52.4M
/nix/store/43nkzxizpfaq9ljhjhfwk146p8jf9pa5-libinput-1.15.5-bin	  53.0M
/nix/store/04r1xdb26swsf7rykdmpf5llsh918nsy-libinput-1.15.5-dev	 152.4M

after:
/nix/store/7yxwhlrr7n0i53jd352mg4slrfihqd31-libinput-1.15.5    	  52.4M
/nix/store/lh3q2fvd4jf0j0q1x39by770l3mkaymp-libinput-1.15.5-bin	 220.6M
/nix/store/lk4qiabwznc8hpava8wiwf2xsgbgbdzx-libinput-1.15.5-dev	 220.8M

original before regressions:
/nix/store/55xasqvnqw88cficppnkmvs6y3dqq213-libinput-1.15.5    	  52.4M
/nix/store/qbhb51ad9anvp36pdgkrc4h13r26x203-libinput-1.15.5-bin	 126.5M
/nix/store/cd25ap98596ws5wrjcib3hsv8dk65grm-libinput-1.15.5-dev	 217.2M

after, simplified with pyudev not propagating systemd:
/nix/store/4xzs08bm15p55x2b6wlw99nn9xr2z2ka-libinput-1.15.5    	  52.4M
/nix/store/qhpd9c5q9lymz9pd87bqgfakk2n39234-libinput-1.15.5-bin	 130.1M
/nix/store/fllaxc6hi1rppfvw9nss14rbh949nqw3-libinput-1.15.5-dev	 220.8M
```

Packages typically depend on the `out` output, so their runtime closure should not be affected by the increase in `bin`.

Fixes: https://github.com/NixOS/nixpkgs/issues/48252

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
@matthewbauer `checkInputs` are subset of `buildInputs` so I do not see a point in moving them there regarding cross-compilation (https://github.com/NixOS/nixpkgs/pull/81858).

**Comment by matthewbauer** [comment]
My bad! Yeah the issue was it didn't cross compile and it looked like it was just used for tests (which are disabled in cross). But fixing native should take priority over that.

**Review by worldofpeace — APPROVED** [review]
I tested the following
```
❯ sudo ./result-bin/bin/libinput measure touchpad-tap                                                                                        
Touchpad: /dev/input/event15

Ready for recording data.
Tap the touchpad multiple times with a single finger only.
For useful data we recommend at least 20 taps.
Ctrl+C to exit
Touch sequences detected: 20
^C
Time: 
  Max delta: 96ms
  Min delta: 55ms
  Average delta: 71ms
  Median delta: 69ms
  90th percentile: 91ms
  95th percentile: 96ms
```

No issues.

**Comment by jtojnar** [comment]
Looks like it fails on aarch64:

```

=================================== FAILURES ===================================
________________ TestNameConversion.test_value_to_name_invalid _________________
self = <test_clib.TestNameConversion testMethod=test_value_to_name_invalid>
    def test_value_to_name_invalid(self):
        name = Libevdev.event_to_name(3, 0x37, 1000)
        self.assertIsNone(name)
        name = Libevdev.event_to_name(3, 0x37, -1)
>       self.assertIsNone(name)
E       AssertionError: 'MSC_MAX' is not None
test/test_clib.py:106: AssertionError
```

But no idea what `MSC_MAX` is supposed to be, do not see anything like that in the code:

https://gitlab.freedesktop.org/libevdev/python-libevdev/-/blob/0.9/test/test_clib.py#L102-108

**Comment by jtojnar** [comment]
@GrahamcOfBorg build python3.pkgs.libevdev

**Comment by makefu** [comment]
@worldofpeace wupps, accidentally clicked a button (no way to undo), sorry for the inconvenience and ignore the request :)

**Review by makefu — APPROVED** [review]
lgtm

**Pull request merged**
