### PR TITLE
teamviewer: fixes for 15.09

### PR DESCRIPTION
**Pull request by glaebhoerl**
This fixes some problems I had when trying to install teamviewer on 15.09 (with gracious help from `clever` and others on IRC). Two other problems (that I can remember off the top of my head) remain.

In `teamviewer/default.nix`:

```
    ${if stdenv.system == "x86_64-linux" then ''
      sed -i "s,TV_LD64_PATH=.*,TV_LD64_PATH=$(cat ${ld64})," script/tvw_config
    '' else ''
      sed -i ",TV_LD64_PATH=.*,d" script/tvw_config
    ''}
```

On my system, the first branch is taken. But at first the second branch was being taken due to `callPackage_i686` in `all-packages.nix` (which I fixed). This showed that the `sed` invocation in the second branch doesn't actually work: `sed` reports an error that `,` is not a command (and trying to put an `s` before it didn't help either). I don't know `sed` very well so I'm not sure what the right fix might be.

And once it finally installed and started up, the "Connect" button in the main window was missing, rendering the whole thing useless. I haven't the faintest clue what might be causing that. (I've since installed an Ubuntu VM to run teamviewer in, and there the Connect button shows up fine, so this is probably not (just) a bug in teamviewer-on-linux itself.)

### CODE REVIEW

**Comment by peti** [comment]
Please apply those fixes to *master* instead of release-15.09. Then we can cherry pick the commits from there into the release branch.

**Comment by jagajaga** [comment]
@peti master already has these changes.

**Comment by peti** [comment]
When I diff `master` again a `release-15.09` branch with this PR applied, then I get the following differences:

    $ git diff master -- pkgs/**/teamvi*
    diff --git a/pkgs/applications/networking/remote/teamviewer/default.nix b/pkgs/applications/networking/remote/teamviewer/default.nix
    index 2c70d44..47130ca 100644
    --- a/pkgs/applications/networking/remote/teamviewer/default.nix
    +++ b/pkgs/applications/networking/remote/teamviewer/default.nix
    @@ -5,7 +5,7 @@ let

       ld32 =
         if stdenv.system == "i686-linux" then "${stdenv.cc}/nix-support/dynamic-linker"
    -    else if stdenv.system == "x86_64-linux" then "${stdenv.cc}/nix-support/dynamic-linker-m32"
    +    else if stdenv.system == "x86_64-linux" then "${pkgsi686Linux.stdenv.cc}/nix-support/dynamic-linker"
         else abort "Unsupported architecture";
       ld64 = "${stdenv.cc}/nix-support/dynamic-linker";

    @@ -22,7 +22,7 @@ stdenv.mkDerivation {
         # There is a 64-bit package, but it has no differences apart from Debian dependencies.
         # Generic versioned packages (teamviewer_${version}_i386.tar.xz) are not available for some reason.
         url = "http://download.teamviewer.com/download/teamviewer_${version}_i386.deb";
    -    sha256 = "1430dimcv69plpj0ad0wsn10k15x9fwlk6fiq7yz51qbcr5l9wk6";
    +    sha256 = "0j4al1wns22aaxn78s1c99kxxvkffi8lpdqk780h0nx2g4vcj96n";
       };

       unpackPhase = ''

That doesn't seem right, no?

**Comment by layus** [comment]
@glaebhoerl It seems to me that teamviewer is now fixed, right ?
Is there still something in this pull request that has not been fixed by other changes in nixpkgs, or can we close it ?

**Comment by glaebhoerl** [comment]
Teamviewer installed fine from upstream now so this can probably be closed.

**Pull request closed without merging**
