### PR TITLE
haproxy: PCRE and LUA support via configurable options

### PR DESCRIPTION
**Pull request by fuzzy-id**
###### Motivation for this change

This solves #23806 and is a follow up to #23901 and #24248. PCRE and LUA support are added via configurable options. Both are enabled by default, apart from LUA on Darwin where compilation breaks.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by garbas** [comment]
@fuzzy-id would you be willing to take over the maintenance of this package? In the past I used haproxy a lot, now I'm doing different work.

**Comment by fuzzy-id** [comment]
Could you elaborate on what it means to take over maintenance?

**Comment by LnL7** [comment]
The `meta.maintainers` is used by hydra to email people when a build breaks and serves reference to notify the relevant people when there are questions, issues, updates, etc. for a package.

**Comment by fuzzy-id** [comment]
I would like to post-pone this step a bit as I will be afk for quite some time this summer. But I would be very glad to take over maintenance in autumn.

**Comment by fuzzy-id** [comment]
On the other hand, I will be around until end of may. Is it possible to add me to the list of maintainers and then drop @garbas entirely when I'm back. Would this be an option?

**Comment by garbas** [comment]
@fuzzy-id 👍 sounds great! You can add yourself to the list in this PR (i will create a comment to a line where you need to edit)

**Comment by fuzzy-id** [comment]
Done. So I guess it's time to celebrate. :)

I also made a mistake with the default values of `useLua` and `usePcre` and forgot to use the proper library. This is fixed now in the cleaned up commits. I hope I got everything alright now.

**Review by LnL7 — APPROVED** [review]

**Pull request merged**
