### PR TITLE
vimPlugins.vim-trailing-whitespace: fix add dynamic TerminalOpen for …

### PR DESCRIPTION
**Pull request by superherointj**
vimPlugins.vim-trailing-whitespace: fix add dynamic TerminalOpen for both vim and nvim

Patch: https://github.com/bronson/vim-trailing-whitespace/pull/30

(or else this plugin errors every time a file is opened at neovim)

### CODE REVIEW

**Comment by superherointj** [comment]
ping @MattCairns

**Review by figsoda — APPROVED** [review]
please use the template next time

**Comment by superherointj** [comment]
> please use the template next time

Please clarify which information you missed.

**Comment by figsoda** [comment]
These two are pretty useful IMO, doesn't matter that much for a vim plugin but I see you've been doing that for other packages as well.

> - [ ] Built on platform(s) 
> - [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)

**Comment by superherointj** [comment]
> doesn't matter that much for a vim plugin

Agreed. Just noise.

> but I see you've been doing that for other packages as well.

Yes, I don't like/agree with the boilerplate.
I'm a reviewer too and I don't miss this information as a reviewer.
IMO whoever is reviewing should test and check CI for builds in all platforms on his own.

> * [ ]  Tested basic functionality of all binary files (usually in `./result/bin/`)

I don't think a boolean properly reflect this. Let's say I have marked yes/no, what changes? I'd say, nothing. The reviewer still needs to check it.

I tried to answer without ranting... But couldn't, so bear with me please.

Actual issue is really **time is limited** and **prioritization** will happen. I'd prefer to do what is really important. (The day won't be longer.) I barely can get things up to date and handle inflow of requests (be it reviews, issues, fixes, etc). People are always complaining about everything. It's tricky to say the least. I wake up everyday to a broken system somewhere (which was the case with vim here) and then try to patch it as necessary. And try to get on. nixpkgs is not even my main thing in life and it already consumes a lot of my time.

Anyway, filling up boilerplate doesn't improve on anything and just adds up to the burden. Honestly, I'd rather do less of that.
Just the thought of you strong arming me into complying with this makes me sad.

Nixpkgs is painful. Seriously.

**Pull request merged**
