### PR TITLE
gnash: fix build with pangox-compat

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
So, this is far from ideal but it's the only way to fix the build.
Right know gnash is really the only viable solution to play swf files, so I think it's worth keeping it around.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change (pangox-compat, gnash)
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
We should probably mark pango with `meta.knownVulnerabilities = [ "unmainatained" ];`.

**Comment by jtojnar** [comment]
I do not even see any pango mentions in the source code itself.

**Comment by jtojnar** [comment]
It looks like they added pango in the past for static linking against GTK but forgot to make the check static only. And it should be unnecessary with pkg-config anyway.

**Comment by jtojnar** [comment]
The following patch seems to be sufficient:

```patch
diff --git a/macros/pango.m4 b/macros/pango.m4
index 96f0457e2..6f24eb2a2 100644
--- a/macros/pango.m4
+++ b/macros/pango.m4
@@ -34,7 +34,7 @@ AC_DEFUN([GNASH_PATH_PANGO],
   if test x$windows = xyes; then
     pango_pkg=pangowin32
   else
-    pango_pkg=pangox
+    pango_pkg=pango
   fi
 
   if test x$cross_compiling = xno; then

```

Probably easier than cleaning up the build system of the pango cruft.

**Comment by rnhmjoj** [comment]
> +    pango_pkg=pango

I don't know how I missed that. I even modified that script to print more information...

**Comment by jtojnar** [comment]
```diff
--- a/pkgs/misc/gnash/default.nix
+++ b/pkgs/misc/gnash/default.nix
@@ -100,6 +100,13 @@ stdenv.mkDerivation {
       url = "https://savannah.gnu.org/patch/download.php?file_id=47859";
       sha256 = "0aimayzgi5065gkcfcr8d5lkd9c0471q7dqmln42hjzq847n6d5y";
     })
+
+    # Fix build with modern Pango
+    # https://savannah.gnu.org/bugs/index.php?57759
+    (fetchpatch {
+      url = "https://savannah.gnu.org/file/0001-Do-not-depend-on-pangox.patch?file_id=48366";
+      sha256 = "02x7sl5zwd1ld2n4b6bp16c5gk91qsap0spfbb5iwpglq3galv2l";
+    })
   ];
 
   configureFlags = with stdenv.lib; [
```

**Comment by jtojnar** [comment]
Fixed in 0c5502e4a484e726e3d0fee35275976074923bf2.

**Comment by rnhmjoj** [comment]
Thank you!

**Pull request closed without merging**
