### PR TITLE
yubikey-manager: 5.0.1 -> 5.1.1

### PR DESCRIPTION
**Pull request by afh**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Lassulus** [comment]
Result of `nixpkgs-review pr 228372` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>yubioath-flutter</li>
    <li>yubioath-flutter.debug</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>gen-oath-safe</li>
    <li>yubikey-manager</li>
    <li>yubikey-manager.dist</li>
  </ul>
</details>

**Comment by afh** [comment]
Friendly ping to @benley, @pinpox, @Lassulus to get eyes on this 🙂

**Comment by pinpox** [comment]
I see errors when using nixpkgs-review, even though the resulting binary seems to work fine:
```
shell ❯ nixpkgs-review pr 228372                                                                                                                                                                              impure ❄ nixpkgs-review
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/228372/head:refs/nixpkgs-review/1
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (5/5), done.
remote: Total 7 (delta 5), reused 5 (delta 5), pack-reused 2
Unpacking objects: 100% (7/7), 1.04 KiB | 56.00 KiB/s, done.
From https://github.com/NixOS/nixpkgs
   4dc8a5c2dcb8..70260851695c  master                -> refs/nixpkgs-review/0
   7e07464c250c..293ca686108c  refs/pull/228372/head -> refs/nixpkgs-review/1
$ git worktree add /home/pinpox/.cache/nixpkgs-review/pr-228372/nixpkgs 70260851695cf34b28d9598281ad40e29e5c5f73
Preparing worktree (detached HEAD 70260851695c)
Updating files: 100% (34955/34955), done.
HEAD is now at 70260851695c Merge pull request #230614 from r-ryantm/auto-update/hyprpaper
$ git merge --no-commit --no-ff 293ca686108c85dc0b2e78f661e32593db595088
Automatic merge went well; stopped before committing as requested
$ nix build --extra-experimental-features nix-command no-url-literals --no-link --keep-going --no-allow-import-from-derivation --option build-use-sandbox relaxed -f /home/pinpox/.cache/nixpkgs-review/pr-228372/build.nix
error: builder for '/nix/store/gzmgm87l0vpp7hx124zsk7i4mmra7kzi-yubioath-flutter-helper-6.1.0.drv' failed with exit code 1;
       last 10 log lines:
       > installing
       > Executing pipInstallPhase
       > /build/source/helper/dist /build/source/helper
       > Processing ./authenticator_helper-0.1.0-py3-none-any.whl
       > Requirement already satisfied: zxing-cpp in /nix/store/lj52z8f3cmlll6bl6sgrmwvi7kcn0a3a-python3.10-zxing_cpp-1.4.0/lib/python3.10/site-packages (from authenticator-helper==0.1.0) (1.4.0)
       > Requirement already satisfied: Pillow<10.0.0,>=9.1.1 in /nix/store/wlxwmws43ip275736j306shg3nqzjlyd-python3.10-pillow-9.4.0/lib/python3.10/site-packages (from authenticator-helper==0.1.0) (9.4.0)
       > Requirement already satisfied: mss in /nix/store/s15nvvsrimzaf09il7c6vmjc3gj9qgwr-python3.10-mss-7.0.1/lib/python3.10/site-packages (from authenticator-helper==0.1.0) (7.0.1)
       > ERROR: Could not find a version that satisfies the requirement yubikey-manager==5.0.1 (from authenticator-helper) (from versions: none)
       > ERROR: No matching distribution found for yubikey-manager==5.0.1
       > 
       For full logs, run 'nix log /nix/store/gzmgm87l0vpp7hx124zsk7i4mmra7kzi-yubioath-flutter-helper-6.1.0.drv'.
error: 1 dependencies of derivation '/nix/store/shnypvlwppqnp38r6iv7cav1w37h4wgg-yubioath-flutter-6.1.0-dart-deps-list.json.drv' failed to build
error: 2 dependencies of derivation '/nix/store/njpcfabwa2clcwq2afmak0s6m5jvps4d-yubioath-flutter-6.1.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xzdmgkszgc2a2dff51gjk4dkw40pz4vh-review-shell.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/228372

2 packages failed to build:
yubioath-flutter yubioath-flutter.debug

3 packages built:
gen-oath-safe yubikey-manager yubikey-manager.dist

error: build log of '/nix/store/njpcfabwa2clcwq2afmak0s6m5jvps4d-yubioath-flutter-6.1.0.drv!*' is not available
error: build log of '/nix/store/s3iwzlf3a88qpc4gcx83fbj0wfa0h8v3-yubioath-flutter-6.1.0' is not available
error: build log of '/nix/store/njpcfabwa2clcwq2afmak0s6m5jvps4d-yubioath-flutter-6.1.0.drv!*' is not available
error: build log of '/nix/store/6h42c1l08c1bvykdiqcarnlj9b9kl81w-yubioath-flutter-6.1.0-debug' is not available
$ /nix/store/rn5l7fpw7gb0qrn6kgbcypikimaqqf9g-nix-2.13.3/bin/nix-shell /home/pinpox/.cache/nixpkgs-review/pr-228372/shell.nix
```

**Comment by afh** [comment]
Thanks for checking, @pinpox, I see that the `yubioath-flutter` derivation installs version 6.1.0, yet version [6.2.0](https://github.com/Yubico/yubioath-flutter/releases/tag/6.2.0) has been released and it includes an [update to yubikey-manager 5.1.0 in its dependencies](https://github.com/Yubico/yubioath-flutter/blob/1ab9eb9c7482c58a610a2bb2c3d4d20b11eae735/helper/pyproject.toml#L13).

I'm not sure how to best update `yubioath-flutter` from my macOS machine with nixpkgs, as `yubioath-flutter` seems to require linux.

What is a good path forward from here on?

**Comment by Lassulus** [comment]
hmm, seems like yubioath-flutter only works with yubikey-manager 5.1.0. I guess we merge this here and fix yubioath-flutter in another PR

**Comment by Lassulus** [comment]
yeah that sounds fine, just mention me there and I will test and merge it

**Pull request merged**
