### PR TITLE
bazel: 5.1.1 -> 5.2.0

### PR DESCRIPTION
**Pull request by the-mikedavis**
###### Description of changes

* https://blog.bazel.build/2022/06/08/bazel-5.2.html
* https://github.com/bazelbuild/bazel/releases/tag/5.2.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by the-mikedavis** [comment]
I got at least through jaxlib in the `nixpkgs-review` but it looks like my system doesn't have enough ram to compile tensorflow from scratch 😅

**Review by uri-canva — APPROVED** [review]
Looks great, will wait a bit for the darwin build to go green, then merge.

**Comment by the-mikedavis** [comment]
I can reproduce the failure in `nix-build -A bazel_5.tests` on aarch64-darwin on this branch and in master. It looks like it's the [installCheckPhase](https://github.com/NixOS/nixpkgs/blob/73fbb75a9061d4cee01390b40f16eda2bbae1462/pkgs/development/tools/build-managers/bazel/bazel_3/default.nix#L573-L605) that fails, specifically the `//examples/cpp:hello-success_test` target. Should I disable that test on aarch64-darwin?

**Comment by uri-canva** [comment]
Strange. Well if it's already broken on master then we can look into it separately.

**Pull request merged**
