### PR TITLE
qemu: 6.1.0 -> 6.2.0

### LINKED ISSUE #141596: Virtualized hosts failing to start guest VM after qemu update 6.0.0 -> 6.1.0
### Describe the bug
I am using `singularity-tools.buildImage` to create a portable singularity image. It was working until recently, but now it stops at:
```
iPXE (http://ipxe.org) 00:03.0 CA00 PCI2.10 PnP PMM+1FF8EFF0+1FEEEFF0 CA00



Booting from ROM...
Probing EDD (edd=off to disable)... ok
```
No progress is made form there, even when left overnight. 

### Steps To Reproduce

Run `nix-build singularity_image.nix -o ~/r-singularity-aus-bio.img -v`

where `singularity_image.nix` is:

```nix
{ pkgs
  ? import (builtins.fetchGit {
  name = "nixos-master";
  url = https://github.com/NixOS/nixpkgs/;
  ref = "refs/heads/master"; #using bleeding edge packages
  # rev = "e1fc1a80a071c90ab65fb6eafae5520579163783"; # good
  rev = "988da51d9c49a1d43fe28a5f92394f5dbc16eede"; #bad
})
    { #the attributes to import
    }
}:

let
  name = "r-singularity-aus-bio";
in
with pkgs; singularity-tools.buildImage { 
  name = name;
  }
```
### Expected behavior
The above steps should produce a singularity `sif` file at `~/r-singularity-aus-bio.img`.

`Probing EDD (edd=off to disable)... ok` should be followed by `cloading kernel modules` within a few seconds.

### Additional context
Using git bisect, I found that the problem was introduced in 988da51d, which is an update for `qemu` from 6.0.0 to 6.1.0. The problem seems to be in all commits to master after that point.

### Notify maintainers

qemu: @eelco @qyliss 
singularity-tools: @cfhammill @jbedo 
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.71, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11pre322215.9bf75dd50b7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: singularity-tools
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by alyssais**
~This is a draft because QEMU 6.2.0 isn't out yet — currently this PR is updating to a release candidate.  I'm trying it this way because [last time](https://github.com/NixOS/nixpkgs/pull/135877) the QEMU update was delayed for weeks because of Darwin issues.  I'm hoping that by opening the PR early, we can identify issues like that in advance, and then be ready to go when the final release comes out.~ <ins>QEMU 6.2.0 has now been released!</ins>

QEMU now supports automatically detecting which audio drivers to build, so we don't need to pass --audio-drv-list anymore.

pkgsMusl.qemu* doesn't build at the moment because of dependency issues, but with a lot of hacks I was able to do enough of a build to be confident the changes to patches etc. are correct for Musl.

## TODO

- [x] [Upgrade Meson](https://git.qemu.org/?p=qemu.git;a=commitdiff;h=654d6b0453aa6eb19af0d75b0f087a97a5776da7) (https://github.com/NixOS/nixpkgs/pull/144779)
- [x] Revert the qemu64 change from https://github.com/NixOS/nixpkgs/pull/125948 (if it's merged before this is ready), because QEMU 6.2.0 fixes https://github.com/NixOS/nixpkgs/issues/141596.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
@OfBorg test simple cage cagebreak cloud-init os-prober sway virtualbox

(Apart from "simple", these are all the tests that use custom QEMU options, so probably give us a good spread of functionality.)

**Comment by Synthetica9** [comment]
> I'm hoping that by opening the PR early, we can identify issues like that in advance, and then be ready to go when the final release comes out.

Good, we've done that for sway the last few releases and it worked really well to work out the kinks.

**Comment by alyssais** [comment]
[We should have Meson ≥0.58.2 (with 0.59.2 recommended).](https://git.qemu.org/?p=qemu.git;a=commitdiff;h=654d6b0453aa6eb19af0d75b0f087a97a5776da7)

**Comment by Synthetica9** [comment]
#144779 targets staging while this targets master, shouldn't this also target staging if this is dependent on that?

**Comment by alyssais** [comment]
I think changing the base branch would be premature at this point.  It's entirely possible #144779 will already be in staging-next or even master by the time this is ready to merge.

**Comment by zowoq** [comment]
Can we move forward with this by using `pkgs.meson_0_60`?

**Comment by Synthetica9** [comment]
> Can we move forward with this by using `pkgs.meson_0_60`?

Resolved the merge conflict, rebased on master, and using `meson_0_60`. All NixOS tests I tried still worked, which is a good sign I think. Rebase available at https://github.com/Synthetica9/nixpkgs/commits/qemu-6.2.0

**Comment by alyssais** [comment]
[I don't think `meson_0_60` should have been added](https://github.com/NixOS/nixpkgs/pull/150486#issuecomment-1002093866), and I'd rather wait for https://github.com/NixOS/nixpkgs/pull/144779/ so fixing the mess of Meson versions we now have doesn't become even more complicated.

**Comment by alyssais** [comment]
The Meson issues should be resolved now, so once OfBorg is happy I'll undraft.

**Comment by alyssais** [comment]
Now that (x86_64) Darwin stdenv is unbroken:

@NixOS/darwin-maintainers **call for Darwin testing**, since I know QEMU is an important package, and Darwin caused such a big problem last QEMU upgrade, and OfBorg can't even build staging without timing out.

It looks like aarch64-darwin stdenv still doesn't work, but there's nothing I can do about that, and we can't hold upgrades forever because of platforms that are broken further up the dependency tree.  If you want to test a platform with broken dependencies, you could try to cherry-pick the upgrade onto master (which I hope is working), but you'd also have to cherry-pick the Meson bump, which might be tricky because it ended up being split over multiple PRs.

**Review by veprbl — APPROVED** [review]
Works fine on x86_64-darwin when af89fb27214f9479a4899ec4cf84aace6dd8e497 is applied to saging-next

**Pull request merged**
