### PR TITLE
{SDL1, SDL_compat}: migrate to by-name

### PR DESCRIPTION
**Pull request by AndersonTorres**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by AndersonTorres** [comment]
Related: https://github.com/NixOS/nixpkgs/pull/274836

**Comment by emilazy** [comment]
I’d rather drop `SDL1` in favour of the compatibility library than refactor it.

**Comment by peterhoeg** [comment]
> I’d rather drop SDL1 in favour of the compatibility library than refactor it.

I don't have any real numbers to back this up and my info is at least a year old, but there were problems in the past with `SDL_compat` breaking applications when swapping it in for SDL1. I don't know how big a problem it is and I appreciate that that number will continue to go down but for now, I am very much in favour of retaining both. That being said, we should absolutely try migrating as many as possible to `SDL_compat`.

**Comment by Aleksanaa** [comment]
@ofborg eval

**Comment by AndersonTorres** [comment]
By running it  locally, SDL_compat zero-rebuilds.
Given that this PR is mass-rebuilding, I will try to split it.

**Comment by AndersonTorres** [comment]
Hey? Why giving `name` s for the patches caused mass rebuilds?

**Comment by philiptaron** [comment]
> Hey! Why giving `name` s for the patches caused mass rebuilds?

`nix-diff` will tell you.

**Comment by AndersonTorres** [comment]
Since @pbsds is dealing with the SDL1 "upgrade" (basically, packaging HEAD) at https://github.com/NixOS/nixpkgs/pull/274836, doing this particular cleanup is not worth the hassle.

**Review by philiptaron — APPROVED** [review]

**Pull request merged**
