### PR TITLE
vmware-workstation: 17.5.1 -> 17.5.2

### LINKED ISSUE #310121: Build failure: vmware-workstation
### Steps To Reproduce

1. build *vmware-workstation*

### Build log

```
building Nix...
building the system configuration...
building '/nix/store/vh6yjal2lyp9va5k5p5shv073jzsgay3-VMware-Workstation-Full-17.5.1-23298084.x86_64.bundle.drv'...
building '/nix/store/4slcz39jjfqb73rjqc2kbqqb9i6nppjy-gdbm-1.8.3.drv'...
building '/nix/store/gqwx8nkfw2m5xw92y6k3s4a3a2iqzrzn-vmware-unpack-env-usr-target.drv'...
Running phase: unpackPhase
unpacking source archive /nix/store/hh149gw57kdvafpqjfq3869x4zkkgdr7-gdbm-1.8.3.tar.gz
source root is gdbm-1.8.3
setting SOURCE_DATE_EPOCH to timestamp 1034719556 of file gdbm-1.8.3/gdbm.info
Running phase: patchPhase
Running phase: updateAutotoolsGnuConfigScriptsPhase
Updating Autotools / GNU config script to a newer upstream version: ./config.sub
Updating Autotools / GNU config script to a newer upstream version: ./config.guess
Running phase: configurePhase
fixing libtool script ./ltmain.sh
patching script interpreter paths in ./configure
./configure: interpreter directive changed from "#! /bin/sh" to "/nix/store/h3bhzvz9ipglcybbcvkxvm4vg9lwvqg4-bash-5.2p26/bin/sh"
configure flags: --disable-static --prefix=/nix/store/2gyp500pg8byyrbd9n4j6ijpbgb9ry4z-gdbm-1.8.3 --enable-libgdbm-compat
warning: collision between `/nix/store/nkdgysx90pln2l562l7lsk021hbxjdg8-glibc-2.39-31-bin/bin/ldconfig' and `/nix/store/d130xwm9365hfdzpz7x5kq9is9q6l4rm-ldconfig/bin/ldconfig'
warning: collision between `/nix/store/apab5i73dqa09wx0q27b6fbhd1r18ihl-glibc-2.39-31/lib/locale/locale-archive' and `/nix/store/j2h103h7b0xg7pc5ih3m1df0j3z71c6v-glibc-locales-2.39-31/lib/locale/locale-archive'
checking for gcc... gcc
created 1125 symlinks in user environment
building '/nix/store/jyymlbz15czjll8hac5qddil8afar8rf-vmware-unpack-env-fhs.drv'...
checking for C compiler default output... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
/nix/store/4hfpf6kn1fj2r1dxpn8dz7zqdnm3j12l-vmware-unpack-env-fhs /build
/nix/store/4hfpf6kn1fj2r1dxpn8dz7zqdnm3j12l-vmware-unpack-env-fhs/usr /nix/store/4hfpf6kn1fj2r1dxpn8dz7zqdnm3j12l-vmware-unpack-env-fhs /build
/nix/store/4hfpf6kn1fj2r1dxpn8dz7zqdnm3j12l-vmware-unpack-env-fhs /build
building '/nix/store/pl6gzr7sjfznn331rkp6iqs439nxav3s-vmware-unpack-env-bwrap.drv'...

trying https://download3.vmware.com/software/WKST-1751-LX/VMware-Workstation-Full-17.5.1-23298084.x86_64.bundle
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
checking for gcc option to accept ANSI C... none needed
checking how to run the C preprocessor... gcc -E
checking for a BSD-compatible install... /nix/store/hq8765g3p1i7qbargnqli5mn0jpsdbfl-coreutils-9.5/bin/install -c
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for ld used by GCC... ld
checking if the linker (ld) is GNU ld... yes
checking for ld option to reload object files... -r
checking for BSD-compatible nm... nm
checking whether ln -s works... yes
checking how to recognise dependant libraries... (cached) pass_all
building '/nix/store/5l3rqri02lk0vlsshzxavdsd240zcm30-vmware-unpack-env.drv'...
checking command to parse nm output... ok
checking for egrep... grep -E
  0    15    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) The requested URL returned error: 522
error: cannot download VMware-Workstation-Full-17.5.1-23298084.x86_64.bundle from any mirror
checking for ANSI C header files... yes
error: builder for '/nix/store/vh6yjal2lyp9va5k5p5shv073jzsgay3-VMware-Workstation-Full-17.5.1-23298084.x86_64.bundle.drv' failed with exit code 1
error:
       … while calling the 'head' builtin

         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'

         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: 1 dependencies of derivation '/nix/store/6zl9d3wlrw7s6p63l9agnangra8yfqdm-vmware-workstation-17.5.1.drv' failed to build
```

### Additional context

The package cannot download. 522 error. It is similarly impossible to install a previous version.

### PR DESCRIPTION
**Pull request by deinferno**
## Description of changes

This PR should close #310121

This derivation now uses https://softwareupdate.vmware.com as source, as of changes to distribution stated in [this blog](https://blogs.vmware.com/workstation/2024/05/vmware-workstation-pro-now-available-free-for-personal-use.html) 

Those changes by Broadcom causes derivation to become a little more complex by now needing to download all the components separately.
Many thanks to @kulczwoj for providing overlay that this PR was based on. 

Change in software itself are minor for now.

Also fixes SQLite INSERT INTO syntax.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by vifino — APPROVED** [review]
Hey! This looks good, but for me the tools ISOs still don't work, with or without `enableInstaller`.

Am I missing something?

**Comment by deinferno** [comment]
For some reason tools iso only work if i disable `enableInstaller` on my 23.11 system, otherwise it will do an SSL error when trying to pull them off the internet. More information can probably be found in /tmp/vmware-root or /tmp/vmware-user dirs with logs.

**Comment by etrigan63** [comment]
When will this get merged and then show up in the 24.05 repo? I really need to get vmware-workstation operational to finish up a photo project I am working on.

**Comment by deinferno** [comment]
Things take a while in big repos, meanwhile you can apply [this overlay](https://github.com/NixOS/nixpkgs/issues/310121#issuecomment-2118349018) in [this NixOS option](https://search.nixos.org/options?show=nixpkgs.overlays) for now to get vmware-workstation working.

**Comment by etrigan63** [comment]
> Things take a while in big repos, meanwhile you can apply [this overlay](https://github.com/NixOS/nixpkgs/issues/310121#issuecomment-2118349018) in [this NixOS option](https://search.nixos.org/options?show=nixpkgs.overlays) for now to get vmware-workstation working.

Thanks but until the documentation becomes usable by normal people (ie: people who do not eat, sleep, breathe, sweat, bleed, urinate and deficate Nix), I am not going to mess with overlays, flakes or home-manager. I will wait for the repos to update as this has merged.

**Comment by chuahou** [comment]
Would it be a good idea to backport this to 24.05 as well considering [VMSA-2024-0010](https://support.broadcom.com/web/ecx/support-content-notification/-/external/content/SecurityAdvisories/0/2428) with fixes in 17.5.2?

**Pull request merged**
