### PR TITLE
Upgrade FreeCAD to qt5, maybe fix seg fault

### PR DESCRIPTION
**Pull request by waynr**
See #42790

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterhoeg** [comment]
Instead of passing in qt5, use ```libsForQt5.callPackage``` instead as it sets up the environment for a qt5 build.

**Comment by peterhoeg** [comment]
There is a *lot* more work required to get this compiling on qt5, just FYI.

**Comment by waynr** [comment]
Yeah I was just looking at the upstream bug tracker: https://www.freecadweb.org/tracker/view.php?id=2986

Not sure how much time I can sink into this right now :(

**Comment by luzpaz** [comment]
It's not there just yet but there is a pending upstream 0.18 release. Qt5 will be default for it. When the time comes then we can cross FreeCAD off of https://github.com/NixOS/nixpkgs/issues/33248

**Comment by gebner** [comment]
Fixed in #63348.

**Pull request closed without merging**
