### PR TITLE
cantata: 2.5.0 -> 3.2.0

### PR DESCRIPTION
**Pull request by RamKromberg**
## Description of changes

Original developer archived the repo a few years ago: https://github.com/CDrummond/cantata

Switched to an updated Qt6 fork: https://github.com/nullobsi/cantata

Also enabled libvlc for playback over http.

p.s. Also packaged taglib2.

- Built on platform(s)
  - [x] x86_64-linux

- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by jtbx — APPROVED** [review]

**Comment by peterhoeg** [comment]
we also need taglib2 for the new version of cantata

**Comment by RamKromberg** [comment]
@peterhoeg good call. are taglib1 apis implemented in taglib2 (backwards compatible) or should I create a new taglib2 package?

**Comment by RamKromberg** [comment]
Added taglib2. It's just a slight modification taglib's default.nix only changing the version number & hash and adding utf8cpp buildInput:

```
$ diff -u pkgs/development/libraries/taglib/default.nix pkgs/development/libraries/taglib2/default.nix
--- pkgs/development/libraries/taglib/default.nix       2024-05-08 02:28:50.857004855 +0300
+++ pkgs/development/libraries/taglib2/default.nix      2024-06-07 12:22:03.017977473 +0300
@@ -4,22 +4,23 @@
 , cmake
 , zlib
 , testers
+, utf8cpp
 }:
 
 stdenv.mkDerivation (finalAttrs: {
   pname = "taglib";
-  version = "1.13.1";
+  version = "2.0.1";
 
   src = fetchFromGitHub {
     owner = "taglib";
     repo = "taglib";
     rev = "v${finalAttrs.version}";
-    hash = "sha256-QX0EpHGT36UsgIfRf5iALnwxe0jjLpZvCTbk8vSMFF4=";
+    sha256 = "sha256-zoZir1TtYtEEZBudlGRLYPFIFJl5oad4+l64lytJ+bc=";
   };
 
   nativeBuildInputs = [ cmake ];
 
-  buildInputs = [ zlib ];
+  buildInputs = [ zlib utf8cpp ];
 
   cmakeFlags = [
     "-DBUILD_SHARED_LIBS=ON" 
```

The original taglib wasn't replaced since some APIs were deprecated with the new major version: https://github.com/taglib/taglib/blob/master/CHANGELOG.md

**Comment by RamKromberg** [comment]
The package naming sanitizer is complaining about me adding pkgs/development/libraries/taglib/2.x.nix to pkgs/top-level/all-packages.nix due to the new pkgs/by-name hierarchy despite the [migration guideline](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/README.md#manual-migration-guidelines) saying to "Please hold off migrating your maintained packages to this directory"...

Feedback?

**Pull request closed without merging**
