### PR TITLE
staging-next 2022-09-15

### PR DESCRIPTION
**Pull request by vcunat**
- workflow docs: [nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy](https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy)
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/188284

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
> * [ ]  ATM even -small channel wouldn't build, due to some pythonPackages regressions:
>       [hydra.nixos.org/eval/1780800#tabs-still-fail](https://hydra.nixos.org/eval/1780800#tabs-still-fail)

thats most likely based on https://github.com/NixOS/nixpkgs/commit/13bb0f49f7afe8296452d70e7782ac1d67b064da which is going to be fixed by https://github.com/NixOS/nixpkgs/pull/191333

**Comment by zowoq** [comment]
https://hydra.nixos.org/build/190672294

I can't reproduce the test failure in `boehmgc.x86_64-darwin`, could someone please restart it?

**Comment by vcunat** [comment]
It reproduced the same on Hydra.  It could be due to rosetta emulation.  Right now on Hydra there's only one small builder that's native x86_64-darwin (and I wonder if it even works at this very moment).  Then we have several `hetzner-m1-*` machines building both platforms.

**Comment by vcunat** [comment]
After the `python-updates` merge `opencv` broke.  That seems rather "suspicious", but I could reproduce the issue locally and I found it upstream as well (unsolved, so far): https://github.com/opencv/opencv/issues/22449
Maybe some of the hashes unexpectedly match a sloppy regexp, or issues like that; who knows.

**Comment by mweinelt** [comment]
onnxruntime has broken pkgconfig paths, which break the package.

```
prefix=/nix/store/jn1pym0anzhqnp1mw6m61aqfavjm90k4-onnxruntime-1.12.1
bindir=${prefix}//nix/store/jn1pym0anzhqnp1mw6m61aqfavjm90k4-onnxruntime-1.12.1/bin
mandir=${prefix}//nix/store/jn1pym0anzhqnp1mw6m61aqfavjm90k4-onnxruntime-1.12.1/share/man
docdir=${prefix}//nix/store/jn1pym0anzhqnp1mw6m61aqfavjm90k4-onnxruntime-1.12.1/share/doc/onnxruntime
libdir=${prefix}//nix/store/jn1pym0anzhqnp1mw6m61aqfavjm90k4-onnxruntime-1.12.1/lib
includedir=/nix/store/058z691fx95lr102l7bxrk4mzqjs5chm-onnxruntime-1.12.1-dev//nix/store/058z691fx95lr102l7bxrk4mzqjs5chm-onnxruntime-1.12.1-dev/include/onnxruntime

Name: onnxruntime
Description: ONNX runtime
URL: https://github.com/microsoft/onnxruntime
Version: 1.12.1
Libs: -L${libdir} -lonnxruntime
Cflags: -I${includedir}

**Comment by vcunat** [comment]
Bigger regression(s):
- [ ] [`python3Packages.celery`](https://hydra.nixos.org/build/192192547): /cc maintainer @fabaff
- [ ] [`python3Packages.prance`](https://hydra.nixos.org/build/192190723): /cc maintainer @costrouc
- [ ] [`python3Packages.grpcio-tools`](https://hydra.nixos.org/build/191713583): no maintainers, most likely triggered by protobuf update

**Comment by vcunat** [comment]
Curiously, cmake-based detection of `protobuf` got broken by switching to later version which uses cmake to build itself (in 6aa094d753).  I can't see the root of the issue, though, and minor updates don't help this (PR #193365).

Here's one log but I might've seen multiple: https://hydra.nixos.org/build/191689965/nixlog/4

**Comment by vcunat** [comment]
`pkgsi686Linux.python3Packages.bcrypt` [segfaults](https://hydra.nixos.org/build/192968257) during tests and consequently blocks many tests from running.  I can reproduce that locally, but i686 tests don't seem very important.

**Comment by mweinelt** [comment]
https://github.com/pyca/bcrypt/issues/407

**Pull request merged**
