### PR TITLE
morph: 1.3.0 -> 1.3.1

### PR DESCRIPTION
**Pull request by mmahut**
###### Motivation for this change

#68421 into 19.09

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by mmahut** [comment]
We will wait until @GrahamcOfBorg is up again to make sure this builds on other platforms too.

**Review by ivan — APPROVED** [review]
I built and tested this on NixOS x86_64 and it is working fine (tested: morph deploy).

**Comment by mmahut** [comment]
@GrahamcOfBorg build morph

Borgy sleepy borg, wake up.

**Comment by mmahut** [comment]
Well, it builds in hydra for master.

**Pull request merged**
