### PR TITLE
yarn2nix: successfully build packages with "@" and "/" in their name

### PR DESCRIPTION
**Pull request by nicknovitski**
###### Motivation for this change

My workplace releases "scoped" node packages, whose names can be things like `@scope/foo`.  It's possible to override the name of the package's derivation, but not that of the internal "modules" derivation the function creates, which will get an invalid name like `@scope/foo-modules-0.0.1`.

I coped node2nix's pattern of replacing the characters with `_at_` and `_slash_`.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
~- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))~
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by nicknovitski** [comment]
I assume this is better handled by moretea/yarn2nix@44e16c6e9ea9f5fc28c73ae388342520d95f1529?

**Comment by nicknovitski** [comment]
I adapted that change with what I believe to be a portable regex.

**Comment by xeji** [comment]
cc @manveru @zimbatm

**Comment by nicknovitski** [comment]
Good idea!

**Pull request closed without merging**
