### PR TITLE
networkmanager: 1.26.0 -> 1.30.0

### LINKED ISSUE #115137: networkmanager is outdated
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: networkmanager

current version: 1.26
desired version: 1.30

###### Notify maintainers

maintainers: @Phreedom @domenkozar @worldofpeace @obadz 

###### Note for maintainers

Nothing notable in changelog: https://github.com/NetworkManager/NetworkManager/blob/master/NEWS

Motivation: https://www.xmodulo.com/wireguard-vpn-network-manager-gui.html says wireguard support comes with 1.26.2

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by amaxine**
###### Motivation for this change
Version bump.

I don't have the time/will right now, but it might be worth upstreaming the paths patch as build flags would probably make this a little easier to bump every time.

Notable changes: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/a592617717305943c129d63bc947fdeb00b431b0/NEWS

Fixes #115137.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
> I don't have the time/will right now but might be worth upstreaming the paths patch as build flags would probably make this a little easier to bump every time.

Sounds like a good idea, and I'm also fairly certain they wouldn't have a problem with that.

**Review by worldofpeace — CHANGES_REQUESTED** [review]
All looks fine to me, but there's one thing if you don't mind.
A while back we had to rename `network-manager` -> `networkmanager`, because that is its actual name. It seems we didn't switch `pname` -> `networkmanager` or the path in nixpkgs. If you could do that and change the commit message it would be much appreciated.

**Comment by maxeaubrey** [comment]
Can do, will do it when I'm back near my laptop. Should it still be `networkmanager`, or `NetworkManager` to match VPN plugins and upstream mirror naming?

**Comment by worldofpeace** [comment]
> Can do, will do it when I'm back near my laptop. Should it still be `networkmanager`, or `NetworkManager` to match VPN plugins and upstream mirror naming?

ehh, those should be changed to `NetworkManager` -. `networkmanager` eventually, since I believe our manual states to convert that to lowercase. For now I'd be fine with just correcting what's `networkmanager`.

**Comment by maxeaubrey** [comment]
Cool, I moved the path/changed the pname and reworded the original commit.

**Comment by SuperSandro2000** [comment]
Can't build this right now because git is broken on staging:

```
builder for '/nix/store/yamjspq1y07ck9b3wzwn513j46ixwrjf-git-2.30.1.drv' failed with exit code 2; last 10 log lines:                                                                          Test Summary Report                                                                                                                                                                         -------------------                                                                                                                                                                         t5319-multi-pack-index.sh                        (Wstat: 256 Tests: 66 Failed: 1)                                                                                                             Failed test:  11                                                                                                                                                                            Non-zero exit status: 1                                                                                                                                                                   Files=913, Tests=22275, 75 wallclock secs ( 4.76 usr  1.07 sys + 301.60 cusr 362.52 csys = 669.95 CPU)                                                                                      Result: FAIL                                                                                                                                                                                make[1]: *** [Makefile:53: prove] Error 1                                                                                                                                                   make[1]: Leaving directory '/build/git-2.30.1/t'                                                                                                                                            make: *** [Makefile:2811: test] Error 2
```

image

**Comment by maxeaubrey** [comment]
@SuperSandro2000 I have the same problem on master, and it's also preventing me from fully rebuilding my system to test #115436 (and I assume my `nixpkgs-review` run for that will face the same problem at some point during the night). I've actually ran into it for a while now (at least a month or so), and I usually just waited until I could pull git from the nix cache...

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 I have the same problem with git on master, and it's also preventing me from fully rebuilding my system to test #115436 (and I assume my `nixpkgs-review` run for that will face the same problem at some point during the night). I've actually ran into it for a while now (at least a month or so), and I usually just waited until I could pull git from the nix cache...

I disabled the test in https://github.com/NixOS/nixpkgs/pull/115847

**Comment by SuperSandro2000** [comment]
```
copying path '/nix/store/nrnk4ryzlkr1g0dkvlmz2knk4gz83di5-ModemManager-1.14.10.tar.xz' from 'http://martha:5000'...
copying path '/nix/store/419gcpmbk6g2jvsnwxxhs2wdpns2dc6m-libqrtr-glib-1.0.0' from 'http://martha:5000'...
copying path '/nix/store/rbkmampbxn0xix6khzjx1j5yxy99nnmm-libmbim-1.24.6' from 'http://martha:5000'...
copying path '/nix/store/z6y4c4syszchwyg7mnki08wjxlqa1nzq-ppp-2.4.8' from 'http://amy:5000'...
error: --- SubstituteGone --- nix-daemon
file 'nar/z6y4c4syszchwyg7mnki08wjxlqa1nzq.nar' does not exist in binary cache 'http://amy:5000'
copying path '/nix/store/z6y4c4syszchwyg7mnki08wjxlqa1nzq-ppp-2.4.8' from 'http://clara:5000'...
copying path '/nix/store/ijgfynv8djgibj0q55mi8sirnnv6gsff-libmbim-1.24.6-dev' from 'http://martha:5000'...
copying path '/nix/store/vx8c4lbwnh924s69akb21a0kxsyylfh4-libqmi-1.28.2' from 'http://martha:5000'...
copying path '/nix/store/v7z9g44i2qr7lhzmmmxb5fbqz4zmnv14-libqmi-1.28.2-dev' from 'http://martha:5000'...
unpacking sources
unpacking source archive /nix/store/nrnk4ryzlkr1g0dkvlmz2knk4gz83di5-ModemManager-1.14.10.tar.xz
source root is ModemManager-1.14.10
setting SOURCE_DATE_EPOCH to timestamp 1610803679 of file ModemManager-1.14.10/docs/reference/libmm-glib/libmm-glib.types
patching sources
configuring
fixing libtool script ./ltmain.sh
configure flags: --disable-static --disable-dependency-tracking --prefix=/nix/store/mmxkpgc36y8r6qkhjcv8pfky9n3v0h30-modem-manager-1.14.10 --with-polkit --with-udev-base-dir=/nix/store/mmxkpgc36y8r6qkhjcv8pfky9n3v0h30-modem-manager-1.14.10/lib/udev --with-dbus-sys-dir=/nix/store/mmxkpgc36y8r6qkhjcv8pfky9n3v0h30-modem-manager-1.14.10/share/dbus-1/system.d --with-systemdsystemunitdir=/nix/store/mmxkpgc36y8r6qkhjcv8pfky9n3v0h30-modem-manager-1.14.10/etc/systemd/system --sysconfdir=/etc --localstatedir=/var --with-systemd-suspend-resume --with-systemd-journal
checking for a BSD-compatible install... /nix/store/9fkdn82nzxgkxyax3m9qdh2knj7apaa5-coreutils-8.32/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /nix/store/9fkdn82nzxgkxyax3m9qdh2knj7apaa5-coreutils-8.32/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '100' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking whether make supports nested variables... (cached) yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... none
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /nix/store/ia1dn8zyi07phxkx02c0wwqc7v7c54nl-gnugrep-3.6/bin/grep
checking for egrep... /nix/store/ia1dn8zyi07phxkx02c0wwqc7v7c54nl-gnugrep-3.6/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) none
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /nix/store/ij7k48dhdrda13gcp3lbpi507b2awnmr-gnused-4.8/bin/sed
checking for fgrep... /nix/store/ia1dn8zyi07phxkx02c0wwqc7v7c54nl-gnugrep-3.6/bin/grep -F
checking for ld used by gcc... ld
checking if the linker (ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... nm
checking the name lister (nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse nm output from gcc object... ok
checking for sysroot... no
checking for a working dd... /nix/store/9fkdn82nzxgkxyax3m9qdh2knj7apaa5-coreutils-8.32/bin/dd
checking how to truncate binary pipes... /nix/store/9fkdn82nzxgkxyax3m9qdh2knj7apaa5-coreutils-8.32/bin/dd bs=4096 count=1
./configure: line 8148: /usr/bin/file: No such file or directory
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether C compiler accepts -Werror=unknown-warning-option... no
checking whether C compiler accepts -Wno-suggest-attribute=format... yes
checking whether C compiler accepts -fno-strict-aliasing... yes
checking whether C compiler accepts -Wnested-externs... yes
checking whether C compiler accepts -Wmissing-prototypes... yes
checking whether C compiler accepts -Wstrict-prototypes... yes
checking whether C compiler accepts -Wdeclaration-after-statement... yes
checking whether C compiler accepts -Wimplicit-function-declaration... yes
checking whether C compiler accepts -Wold-style-definition... yes
checking whether C compiler accepts -Wjump-misses-init... yes
checking whether C compiler accepts -Wall... yes
checking whether C compiler accepts -Wextra... yes
checking whether C compiler accepts -Wundef... yes
checking whether C compiler accepts -Wwrite-strings... yes
checking whether C compiler accepts -Wpointer-arith... yes
checking whether C compiler accepts -Wmissing-declarations... yes
checking whether C compiler accepts -Wredundant-decls... yes
checking whether C compiler accepts -Wno-unused-parameter... yes
checking whether C compiler accepts -Wno-missing-field-initializers... yes
checking whether C compiler accepts -Wformat=2... yes
checking whether C compiler accepts -Wcast-align... yes
checking whether C compiler accepts -Wformat-nonliteral... yes
checking whether C compiler accepts -Wformat-security... yes
checking whether C compiler accepts -Wsign-compare... yes
checking whether C compiler accepts -Wstrict-aliasing... yes
checking whether C compiler accepts -Wshadow... yes
checking whether C compiler accepts -Winline... yes
checking whether C compiler accepts -Wpacked... yes
checking whether C compiler accepts -Wmissing-format-attribute... yes
checking whether C compiler accepts -Wmissing-noreturn... yes
checking whether C compiler accepts -Winit-self... yes
checking whether C compiler accepts -Wredundant-decls... (cached) yes
checking whether C compiler accepts -Wmissing-include-dirs... yes
checking whether C compiler accepts -Wunused-but-set-variable... yes
checking whether C compiler accepts -Warray-bounds... yes
checking whether C compiler accepts -Wreturn-type... yes
checking whether C compiler accepts -Wswitch-enum... yes
checking whether C compiler accepts -Wswitch-default... yes
checking whether C compiler accepts -Wduplicated-cond... yes
checking whether C compiler accepts -Wduplicated-branches... yes
checking whether C compiler accepts -Wlogical-op... yes
checking whether C compiler accepts -Wrestrict... yes
checking whether C compiler accepts -Wnull-dereference... yes
checking whether C compiler accepts -Wdouble-promotion... yes
checking whether C compiler accepts -Wno-error=unused-parameter... yes
checking whether C compiler accepts -Wno-error=missing-field-initializers... yes
checking whether C compiler accepts -Werror=unknown-warning-option... (cached) no
checking whether the linker accepts -Wl,--as-needed... yes
checking whether the linker accepts -Wl,--as-needed... yes
checking whether the linker accepts -Wl,-z,relro... yes
checking whether the linker accepts -Wl,-z,relro... yes
checking whether the linker accepts -Wl,-z,now... yes
checking whether the linker accepts -Wl,-z,now... yes
checking whether the linker accepts -Wl,-z,noexecstack... yes
checking whether the linker accepts -Wl,-z,noexecstack... yes
checking whether the linker accepts -Wl,--no-as-needed... yes
checking whether the linker accepts -Wl,--fatal-warnings... yes
checking whether the linker accepts -Wl,-fatal_warnings... no
checking whether the linker accepts -Wl,--no-as-needed... yes
checking whether C compiler accepts -Werror=unknown-warning-option... (cached) no
checking whether C compiler accepts -Wno-suggest-attribute=format... (cached) yes
checking whether C compiler accepts -fno-strict-aliasing... (cached) yes
checking whether C compiler accepts -Wnested-externs... (cached) yes
checking whether C compiler accepts -Wmissing-prototypes... (cached) yes
checking whether C compiler accepts -Wstrict-prototypes... (cached) yes
checking whether C compiler accepts -Wdeclaration-after-statement... (cached) yes
checking whether C compiler accepts -Wimplicit-function-declaration... (cached) yes
checking whether C compiler accepts -Wold-style-definition... (cached) yes
checking whether C compiler accepts -Wjump-misses-init... (cached) yes
checking whether C compiler accepts -Wall... (cached) yes
checking whether C compiler accepts -Wextra... (cached) yes
checking whether C compiler accepts -Wundef... (cached) yes
checking whether C compiler accepts -Wwrite-strings... (cached) yes
checking whether C compiler accepts -Wpointer-arith... (cached) yes
checking whether C compiler accepts -Wmissing-declarations... (cached) yes
checking whether C compiler accepts -Wredundant-decls... (cached) yes
checking whether C compiler accepts -Wno-unused-parameter... (cached) yes
checking whether C compiler accepts -Wno-missing-field-initializers... (cached) yes
checking whether C compiler accepts -Wformat=2... (cached) yes
checking whether C compiler accepts -Wcast-align... (cached) yes
checking whether C compiler accepts -Wformat-nonliteral... (cached) yes
checking whether C compiler accepts -Wformat-security... (cached) yes
checking whether C compiler accepts -Wsign-compare... (cached) yes
checking whether C compiler accepts -Wstrict-aliasing... (cached) yes
checking whether C compiler accepts -Wshadow... (cached) yes
checking whether C compiler accepts -Winline... (cached) yes
checking whether C compiler accepts -Wpacked... (cached) yes
checking whether C compiler accepts -Wmissing-format-attribute... (cached) yes
checking whether C compiler accepts -Wmissing-noreturn... (cached) yes
checking whether C compiler accepts -Winit-self... (cached) yes
checking whether C compiler accepts -Wredundant-decls... (cached) yes
checking whether C compiler accepts -Wmissing-include-dirs... (cached) yes
checking whether C compiler accepts -Wunused-but-set-variable... (cached) yes
checking whether C compiler accepts -Warray-bounds... (cached) yes
checking whether C compiler accepts -Wreturn-type... (cached) yes
checking whether C compiler accepts -Wswitch-enum... (cached) yes
checking whether C compiler accepts -Wswitch-default... (cached) yes
checking whether C compiler accepts -Wduplicated-cond... (cached) yes
checking whether C compiler accepts -Wduplicated-branches... (cached) yes
checking whether C compiler accepts -Wlogical-op... (cached) yes
checking whether C compiler accepts -Wrestrict... (cached) yes
checking whether C compiler accepts -Wnull-dereference... (cached) yes
checking whether C compiler accepts -Wdouble-promotion... (cached) yes
checking whether C compiler accepts -Wno-cast-function-type... yes
checking whether C compiler accepts -Wno-packed... yes
checking whether C compiler accepts -Wno-error=unused-parameter... (cached) yes
checking whether C compiler accepts -Wno-error=missing-field-initializers... (cached) yes
checking whether C compiler accepts -Wno-error=cast-function-type... yes
checking whether C compiler accepts -Wno-error=packed... yes
checking pkg-config is at least version 0.9.0... yes
checking for gtk-doc... no
configure: WARNING:
  You will not be able to create source packages with 'make dist'
  because gtk-doc >= 1.0 is not found.
checking for gtkdoc-check... no
checking for gtkdoc-check... no
checking for gtkdoc-rebase... no
checking for gtkdoc-mkpdf... no
checking whether to build gtk-doc documentation... no
checking for GTKDOC_DEPS... yes
checking whether NLS is requested... yes
checking for msgfmt... /nix/store/4w5immj9jfwzajr1lzwxsa09ydgri8vg-gettext-0.21/bin/msgfmt
checking for gmsgfmt... /nix/store/4w5immj9jfwzajr1lzwxsa09ydgri8vg-gettext-0.21/bin/msgfmt
checking for xgettext... /nix/store/4w5immj9jfwzajr1lzwxsa09ydgri8vg-gettext-0.21/bin/xgettext
checking for msgmerge... /nix/store/4w5immj9jfwzajr1lzwxsa09ydgri8vg-gettext-0.21/bin/msgmerge
checking for ld used by gcc... ld
checking if the linker (ld) is GNU ld... yes
checking for shared library run path origin... done
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for GNU gettext in libc... yes
checking whether to use NLS... yes
checking where the gettext function comes from... libc
checking for MM... yes
checking for LIBMM_GLIB... yes
checking for MMCLI... yes
checking for xsltproc... no
checking whether to build with code coverage support... no
checking for gobject-introspection... yes
checking pkg-config is at least version 0.9.0... yes
checking for vapigen... yes
checking for GUDEV... yes
checking for LIBSYSTEMD... yes
checking for LIBSYSTEMD_LOGIN... no
checking for POLKIT... yes
checking for MBIM... yes
checking for QMI... no
configure: error: Couldn't find libqmi-glib >= 1.26.0. Install it, or otherwise configure using --without-qmi to disable QMI support.
```

**Comment by maxeaubrey** [comment]
@SuperSandro2000 I don't think the `ModemManager` failure is related to any changes. I get the same problem on staging, reverting 53bf5c322d89912ed157ebbd2617ed9190bf801 fixes building.

**Comment by jtojnar** [comment]
Should be fixed by 6eed4a89f6feaa0797418626619562ec287c7ed6.

**Comment by Artturin** [comment]
could someone update modemmanager?

**Review by jtojnar — APPROVED** [review]
Changes look okay.

**Comment by maxeaubrey** [comment]
Rebased to resolve merge conflicts.

**Review by worldofpeace — APPROVED** [review]

**Comment by worldofpeace** [comment]
Thanks @maxeaubrey, hope this will go smoothly through staging :sparkles:

**Pull request merged**
