### PR TITLE
Teleport 6.1.2 -> 6.1.3 + patch

### LINKED ISSUE #120738: [teleport] Use of `os.Executable()` call to detect path to the binary
**Describe the bug**
In order to be able to invoke the `tsh` command from `kubectl` teleport is using [`os.Executable()`](https://github.com/gravitational/teleport/blob/master/tool/tsh/tsh.go#L517) call.
There is a wrapper around `tsh` to bring into PATH `xdg-open`.
That means `tsh` is invoked from `kubectl` without wrapper and the browser page never opens (due to missing `xdg-open`).

**To Reproduce**
1. `tsh kube login <my cluster>`
2. `grep command ~/.kube/config`

**Expected behavior**
The path to the wrapper must be persisted in the `~/.kube/config`

**Screenshots**

**Additional context**
[More context](https://github.com/gravitational/teleport/issues/6575)

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```bash
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.0-rc8, NixOS, 21.05pre284548.1fe6ed37fd9 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210326_dd77f71`
 - channels(ymatsiuk): `""`
 - channels(root): `"nixos-21.05pre284548.1fe6ed37fd9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: teleport
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by ymatsiuk**
###### Motivation for this change
fixes #120738 + version bump to `6.1.2`

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by freezeboy — APPROVED** [review]
LGTM

**Comment by ymatsiuk** [comment]
@lukegb @justinas I missed the #120224 so tagging you here 🙂 
So #118799 is the reason for the wrapper. And introducing the $client as a separate output removes the need for wrapper in $out.
Although the assumption now is the $out is used only on the server side and the $client is used only on the client side.

**Comment by lukegb** [comment]
If we're installing `tsh` into $out as well, we should probably continue to wrap it, or it'll be confusing.

**Review by lukegb — APPROVED** [review]

**Comment by ymatsiuk** [comment]
anything else I can do here before the merge?

**Pull request merged**
