### PR TITLE
python3Packages.duckduckgo-search: 5.3.1 -> 6.1.6

### PR DESCRIPTION
**Pull request by shivaraj-bh**
## Description of changes
https://github.com/deedy5/duckduckgo_search/compare/v5.3.1...v6.1.9

https://github.com/deedy5/pyreqwest_impersonate/compare/v0.4.7...v0.4.9

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by shivaraj-bh** [comment]
https://github.com/NixOS/nixpkgs/pull/320454 is a pre-requisite for this PR to be ready for review

**Review by drupol — APPROVED** [review]

**Comment by shivaraj-bh** [comment]
I accidentally notified a lot of contributors in https://github.com/NixOS/nixpkgs/pull/320454 , created a new PR https://github.com/NixOS/nixpkgs/pull/320480

**Comment by mweinelt** [comment]
> @vcunat Can you add this PR ? #320480

What is that supposed mean?

**Comment by drupol** [comment]
This was a mistake, this is the reason why I deleted the comment. Sorry for the noise.

**Comment by drupol** [comment]
@shivaraj-bh Can you change the target branch to `staging`? Don't mark it as ready for review until everything is done, so that in case of issue while rebasing, people are not mass notified.

On Matrix Hexa told me it was OK to do that too.

**Comment by shivaraj-bh** [comment]
@drupol `pyreqwest-impersonate` is not in `staging`. Anyways, I was thinking that since `duckduckgo-search` will not update multiple packages, we can wait until `orjson` reaches `master` and then we can merge this?

**Comment by drupol** [comment]
True. Let's wait then.

**Comment by deedy5** [comment]
`orjson` is no longer a dependency of `duckduckgo-search`

**Comment by shivaraj-bh** [comment]
> `orjson` is no longer a dependency of `duckduckgo-search`

Oh okay, let me upgrade to the [latest release](https://github.com/deedy5/duckduckgo_search/releases/tag/v6.1.9) then.

**Comment by shivaraj-bh** [comment]
`nixpkgs-review` succeeds on both `x86_64-linux` and `aarch64-darwin`

**Review by drupol — APPROVED** [review]
Diff LGTM

**Comment by drupol** [comment]
@ofborg build python3Packages.duckduckgo-search python3Packages.pyreqwest-impersonate

**Comment by shivaraj-bh** [comment]
There was a merge commit, that was the result of resolving conflicts. I have now squashed them into two commits for each update.

**Review by drupol — APPROVED** [review]

**Review by drawbu — APPROVED** [review]

**Pull request merged**
