### PR TITLE
pulseaudio: 7.1 -> 8.0

### PR DESCRIPTION
**Pull request by kragniz**
This hasn't been tested locally yet.

### CODE REVIEW

**Comment by FRidh** [comment]
[Release Notes](http://www.freedesktop.org/wiki/Software/PulseAudio/Notes/8.0/)

### Changes at a glance

- Automatic routing more likely to change profile
- OS X and NetBSD support improvements
- Systemd journal logging for clients
- New LFE balance programming interface
- Module-dbus-protocol improvements
- More flexible configuration file handling
- pulsecore-8.0.so moved to a private directory
- New script for measuring memory consumption
- Various bug fixes and small improvements

**Comment by edolstra** [comment]
Has this been tested now? (Original message said no.)

**Comment by fpletz** [comment]
This, we tested and fixed this. We had this running for a week or so and didn't have any problems.

**Comment by edolstra** [comment]
Great, thanks!

**Pull request closed without merging**
