### PR TITLE
email: init at d9fd259f

### PR DESCRIPTION
**Pull request by jerith666**
tested on top of e6d42dfe.

### CODE REVIEW

**Comment by jagajaga** [comment]
Please provide a valid naming. See https://nixos.org/nixpkgs/manual/#sec-versioning

**Comment by jerith666** [comment]
Since the eMail project doesn't version itself, I wasn't sure how to handle that in the nix expression.  Should I put the commit hash in the name, like "email-d9fd259f", or make up my own version like "email-1", or ... ?

**Comment by pSub** [comment]
"If package is fetched from git's commit then the version part of the name must be the date of that (fetched) commit. The date must be in "YYYY-MM-DD" format. Also add "git" to the name - e.g., "pkgname-git-2014-09-23"." See https://nixos.org/nixpkgs/manual/#sec-package-naming.

**Comment by jerith666** [comment]
Ah, I missed that part of the documentation -- sorry!  23d1aa85 names it "email-git-2016-01-31".

**Comment by lethalman** [comment]
Travis passed, thanks.

**Pull request merged**
