### PR TITLE
dejagnu: disable tests on aarch64-darwin

### PR DESCRIPTION
**Pull request by vcunat**
https://hydra.nixos.org/log/4ilhqfxwbsdj49ywq9qna93aj1nilc06-dejagnu-1.6.3.drv

###### Things done

- Built on platform(s)
  - [ ] ~x86_64-linux~
  - [ ] ~aarch64-linux~
  - [ ] ~x86_64-darwin~
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
@ofBorg build dejagnu

**Comment by vcunat** [comment]
Of course it would be better to fix this or at least avoid just the broken tests, but I don't even have a machine capable of testing this.

**Comment by winterqt** [comment]
Wait, this is *only* on aarch64-darwin (with the sandbox disabled), and not x86_64? Ugh. (Enabling the sandbox fixes it, as I said earlier, but that doesn't help here...)

I'd say this is probably the best fix for now, if we'd rather not block -next...

**Comment by vcunat** [comment]
Yes, the build seems OK on x86_64-darwin, on Hydra and I think also locally.

**Comment by vcunat** [comment]
OfBorg shows the first dejagnu build passing (unsurprisingly) and so far continuing with stdenv bootstrapping.

**Review by wegank — APPROVED** [review]

**Comment by winterqt** [comment]
Bad news: I can't reproduce [this successful build](https://hydra.nixos.org/build/202535174) on my machine. So it may just be pure luck that it's been working all this time...

**Comment by wegank** [comment]
My guess is that the regression depends on the system version. The [build failure of Zig](https://hydra.nixos.org/job/nixpkgs/staging-next-22.11/zig.aarch64-darwin) started in late December on that branch, and we all know that Zig 0.9.1 does not build on macOS 13.

**Comment by winterqt** [comment]
> My guess is that the regression depends on the system version.

I was also thinking the same, yeah. Let me poke the infra folks real quick to confirm that hypothesis...

**Pull request merged**
