### PR TITLE
add package.el-based emacs package builder

### PR DESCRIPTION
**Pull request by gridaphobe**
I've been using this to manage my emacs packages for a few months now and it works very nicely for me. I use melpa's `package-build.el` to assemble the packages, and then the standard `package-install` to install them.

To install emacs packages you can run

```
nix-env -iA emacsMelpa.<package>
```

or, like I do, use a `buildEnv` to organize them. Packages reference their dependencies, so you only have to install the top-level packages you actually care about.

Then, in my `.emacs` I just initialize `package.el. with

```
(require 'package)
(setq package-archives nil
      package-user-dir "~/.nix-profile/share/emacs/site-lisp/elpa")
(package-initialize)
```

and proceed as usual.

At the moment, the set of packages is pretty small and ad-hoc, basically just the ones I personally use. I'm open to a more automated method of generating/updating the package list.

/cc @jwiegley

### CODE REVIEW

**Comment by jagajaga** [comment]
cc @oxij

**Comment by peti** [comment]
This looks pretty nice!

**Comment by edwtjo** [comment]
Unfortunately because of the sourceforge outage I cannot try these, but it looks good.

**Comment by edwtjo** [comment]
Works great, I think this is good for merging.

**Comment by oxij** [comment]
Nice! However, I think melpa derivation should go into `build-support` and packages into `top-level/emacs-melpa-packages.nix` or something.

Also, I wonder what is the rational reason behind this `self:` thingy?

**Comment by oxij** [comment]
Also, would be nice to have `meta`s for these packages.

**Comment by gridaphobe** [comment]
@oxij as I understand it (the overall builder structure was stolen from @peti's excellent cabal builder), the `self` business does some fancy knot-tying to allow the default attributes and the custom attributes to reference each other. Whether this is required is a good question.. I notice that the new haskellng builder does *not* do this anymore. I'll experiment a bit this weekend (and will add some `meta` info!)

**Pull request merged**
