### PR TITLE
libbsd: update darwin patch

### LINKED ISSUE #27120: libbsd: Darwin patch fails to apply after upgrade to 0.8.4 (probably 0.8.5 too?
## Issue description

Not sure how difficult it'd be to fix this, but thought I'd note it somewhere.

[Hydra build log](http://hydra.nixos.org/build/54892263)

We recently bumped to 0.8.5 but I don't see any reason that would make the patch apply again (although I can't confirm this myself :)).

If it can't be resolved reasonably perhaps the patch should be dropped and "darwin" removed from `meta.platforms`?

EDIT: Looks like libbsd has a separate "port" for OSX: https://github.com/JackieXie168/libbsd which I've filed an issue on (like was done previously, apparently): https://github.com/JackieXie168/libbsd/issues/2

### Steps to reproduce

Try to build libbsd on Darwin; look at Hydra/Travis build failures.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

### LINKED ISSUE #34989: libbsd build fails on darwin
## Issue description

```
patching file include/bsd/string.h
Hunk #1 FAILED at 37.
1 out of 1 hunk FAILED -- saving rejects to file include/bsd/string.h.rej
```

cc @matthewbauer 

### Steps to reproduce

```
imac:~ davidak$ nix-shell -p nox --run "nox-review pr 34975"
=== Reviewing PR 34975 : stubby: init at 0.2.1
==> Fetching base (master)
==> Fetching PR
==> Fetching extra history for merging
==> Merging PR into base
Auto-merging pkgs/top-level/all-packages.nix
Building in /var/folders/fb/knpgn__s7_s20d_x1gsllflr0000gn/T/nox-review-e2eu1ee0: stubby
Invoking nix-build -A stubby /Users/davidak/.nox/nixpkgs
these derivations will be built:
  /nix/store/08npd4qks90iq79z55fg30dqacwhldhb-libbsd-0.8.7.drv
  /nix/store/s9qinr5vz8ri2f2f781cl1xc8s8h4y8s-source.drv
  /nix/store/97vws45sdsmbrym202jwv2lrfqj7ih78-stubby-0.2.1.drv
building path(s) ‘/nix/store/iccpz0n9fiap97wmfcsxv3ak0afyx41a-libbsd-0.8.7’
building path(s) ‘/nix/store/yvnkac1hy68hakmnqmnwy4yx0rhay3xn-source’
unpacking sources
unpacking source archive /nix/store/rzm65zpvn7qyyg2ls67vrmwgibljkq67-libbsd-0.8.7.tar.xz
source root is libbsd-0.8.7
setting SOURCE_DATE_EPOCH to timestamp 1515857404 of file libbsd-0.8.7/ChangeLog
patching sources
applying patch /nix/store/x12pj9za73n0dpnbs0dy9rf5106bvdqf-darwin.patch
patching file configure.ac
patching file include/bsd/libutil.h
patching file include/bsd/stdio.h
patching file include/bsd/string.h
Hunk #1 FAILED at 37.
1 out of 1 hunk FAILED -- saving rejects to file include/bsd/string.h.rej
patching file src/Makefile.am
patching file src/arc4random_bsd.h
patching file src/arc4random_linux.h
patching file src/arc4random_osx.h
patching file src/fgetln.c
patching file src/fpurge.c
patching file src/funopen.c
patching file src/getentropy.c
patching file src/hash/sha512.h
patching file src/hash/sha512c.c
patching file src/nlist.c
patching file src/setproctitle.c
patching file src/strlcat.c
patching file src/strlcpy.c
patching file src/strmode.c
builder for ‘/nix/store/08npd4qks90iq79z55fg30dqacwhldhb-libbsd-0.8.7.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/97vws45sdsmbrym202jwv2lrfqj7ih78-stubby-0.2.1.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/97vws45sdsmbrym202jwv2lrfqj7ih78-stubby-0.2.1.drv’ failed
The invocation of "nix-build -A stubby /Users/davidak/.nox/nixpkgs" failed
```

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 14.5.0, macOS 10.10.5`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.13`
 - channels(davidak): `"nixpkgs-18.03pre127915.eef9d363e1c"`
 - channels(root): `"nixpkgs-18.03pre121255.45a85eaceb"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

### PR DESCRIPTION
**Pull request by matthewbauer**
Fixes #27120
Fixes #34989

### CODE REVIEW

**Comment by dezgeg** [comment]
@grahamcofborg build libbsd

**Comment by dezgeg** [comment]
````
In file included from arc4random.c:31:
../include/bsd/stdlib.h:70:66: error: token is not a valid binary operator in a preprocessor subexpression
#if defined(_GNU_SOURCE) && defined(__GLIBC__) && !__GLIBC_PREREQ(2, 26)
                                                  ~~~~~~~~~~~~~~~^
````
I think that needs to be split into two `#if`s to avoid the parse error if `__GLIBC_PREREQ` is not defined.

**Comment by matthewbauer** [comment]
Sorry about that. Wasn't happening on my machine for some weird reason.

@GrahamcOfBorg build libbsd

**Comment by LnL7** [comment]
@GrahamcOfBorg build samba samba4 smbclient

**Review by LnL7 — APPROVED** [review]

**Pull request merged**
