### PR TITLE
python3Packages.awesomeversion: 21.2.2 -> 21.2.3

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 21.2.3

Change log: https://github.com/ludeeus/awesomeversion/releases/tag/21.2.3

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 114243` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python38Packages.awesomeversion</li>
    <li>python38Packages.pyhaversion</li>
    <li>python39Packages.awesomeversion</li>
    <li>python39Packages.pyhaversion</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Home Assistant build failure will be fixed with https://github.com/home-assistant/core/pull/46989

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 114243` at bc950813 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/b4d6ecfa9becee38d3c92bec49a950e4">home-assistant</a></li></li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/67c5fe2c6d68a40ed8824ac36b249785">python38Packages.awesomeversion</a></li></li>
    <li><a href="https://gist.github.com/d52ac02da20235541184d0f09f9081e1">python38Packages.pyhaversion</a></li></li>
    <li><a href="https://gist.github.com/83225f0783558e5745892f1a1a00fd60">python39Packages.awesomeversion</a></li></li>
    <li><a href="https://gist.github.com/7b0d67f2d4567e33a89e2cd3f523914f">python39Packages.pyhaversion</a></li></li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
@fabaff can you fix home assistant in the pr with a substituteainPlace?

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 114243` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python38Packages.awesomeversion</li>
    <li>python38Packages.pyhaversion</li>
    <li>python39Packages.awesomeversion</li>
    <li>python39Packages.pyhaversion</li>
  </ul>
</details>

**Pull request merged**
