### PR TITLE
Fixes for X server to run in tty1 with various display managers

### PR DESCRIPTION
**Pull request by abbradar**
This fix `services.xserver.tty` for lightdm. Tried to fix KDM but though it now can run in tty1, for some reason it fails to login on it (it's good with tty7). GDM doesn't run for me at all, so I haven't tried to fix it.

Also this removes `-ac` and `-terminate` options for X server by default -- I don't have any idea why they were added, but it would be nice to hear maintainer's comments. @edolstra ?

### CODE REVIEW

**Comment by abbradar** [comment]
I've found answer to my question myself when `redshift` stopped working ^_^.

**Comment by vcunat** [comment]
Occurs to me: are there some real reasons why X ran (on most distributions) on tty7 previously and now it tends to be tty1?

**Comment by abbradar** [comment]
AFAIR this is a change that `logind` guys are trying to enforce, see also https://unix.stackexchange.com/questions/141604/why-x-server-runs-on-tty1-and-not-tty7-on-arch-linux . It also appeals to me more aesthetically (since I use only one X server and it seems more logical for me to have it on tty1). I haven't changed the default behavior though -- I don't think we should force this on users.

**Comment by abbradar** [comment]
Oops, forgot to remove a non-related patch -- now good to go, I think. I've tested it locally for both tty1 and tty7. Any comments?

**Comment by abbradar** [comment]
Well, this has bit-rotted over time and I've switched to the usual `tty7` again myself (because of some problem) -- let's close this.

**Pull request closed without merging**
