### PR TITLE
jabref: 3.8.1 -> 4.3.1

### PR DESCRIPTION
**Pull request by BenBals**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @gebner

### CODE REVIEW

**Comment by gebner** [comment]
Hmm, this does not even build for me:
```
installing
cp: cannot stat 'images/icons/JabRef-icon-mac.svg': No such file or directory
builder for '/nix/store/f11615w4fpiidaj9d651ps11931yvdxl-jabref-4.3.1.drv' failed with exit code 1
error: build of '/nix/store/f11615w4fpiidaj9d651ps11931yvdxl-jabref-4.3.1.drv' failed
```

The reason we haven't updated jabref is due to several issues:
 * jabref 4+ requires javafx
 * for a long time we didn't have a javafx package
 * now we have javafx for openjdk 11+, but jabref 4 doesn't support openjdk 11

Luckily, jabref 5 seems to support java 11 now: https://github.com/JabRef/jabref/releases/tag/v5.0-alpha

If we want to update jabref, then we should directly go to jabref 5 and use openjdk 11 or 12.

**Comment by BenBals** [comment]
I see. Are you on Mac? As stated in the checklist, this built fine for me via `nix-review`. I don't know whether packages installed system wide could have made that work? (I'm quite new to making nix packages.)

**Comment by gebner** [comment]
No, I'm on nixos and I'm running `nix-build -A jabref`.

@GrahamcOfBorg build jabref

**Comment by gebner** [comment]
The build also fails on ofborg.  Did you run `nix-review wip`?  This will only check the *uncommitted* changes:
```
$ nix-review --help
...
    wip         review the uncommited changes in the working tree
```

If you've already committed the changes, then it won't do anything AFAIR.  Personally, I typically run `nix-build -A $attr` manually for the attributes that are changed (or depend on the changes).

**Comment by BenBals** [comment]
Okay, thanks, now I can reproduce.

**Comment by dtzWill** [comment]
v5 beta is available, FWIW: https://github.com/JabRef/jabref/releases/tag/v5.0-beta

Java is bundled now, maybe customized, so seems more of a FHSenv or autopatchelf sort of thing-- not sure.  Anyone poked at this yet?

**Comment by SuperSandro2000** [comment]
jabref is now already on 5.0.1. Closing this PR.

**Pull request closed without merging**
