### PR TITLE
python312Packages.radish-bdd: fix missing yaml dependency

### PR DESCRIPTION
**Pull request by fliiiix**
```
Traceback (most recent call last):
  File "/nix/store/m7wyckhw6ll6q2azfpivb0jqk9q9fm8z-python3.12-radish-bdd-0.17.1/bin/.radish-test-wrapped", line 6, in <module>
    from radish.testing.__main__ import main
  File "/nix/store/m7wyckhw6ll6q2azfpivb0jqk9q9fm8z-python3.12-radish-bdd-0.17.1/lib/python3.12/site-packages/radish/testing/__main__.py", line 15, in <module>
    from radish.testing.matches import test_step_matches_configs
  File "/nix/store/m7wyckhw6ll6q2azfpivb0jqk9q9fm8z-python3.12-radish-bdd-0.17.1/lib/python3.12/site-packages/radish/testing/matches.py", line 12, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

radish-test requires pyyaml at runtime.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mweinelt** [comment]
https://github.com/radish-bdd/radish/blob/v0.17.1/requirements.txt shows even more changes are required.

**Comment by fliiiix** [comment]
> https://github.com/radish-bdd/radish/blob/v0.17.1/requirements.txt shows even more changes are required.

Missing is `ipython` which is only used for an obscure debugging functionality. (so i would opt for not adding it as the size to usefullnes is not worth it)

For `coverage` i don't know since no one was using this extension until now it might be fine to also not include it by default.

**Comment by mweinelt** [comment]
Also does not seem to depend on lark anymore?

**Comment by fliiiix** [comment]
Ahh good point only 1.x which was never released and probably never will contained lark and click i removed it

**Comment by fliiiix** [comment]
I ran the exploratory test with this version:
```
/nix/store/lyv6m9y4bi8cc5sls1k1gvbqh6dxmyvq-python3.12-radish-bdd-0.17.1/bin/radish-test matches -b radish tests/radish-matches.yml
Testing sentences from tests/radish-matches.yml:
>> STEP "Given I have the number 5" SHOULD MATCH have_number    ✔
>> STEP "When I sum them" SHOULD MATCH sum_numbers    ✔
>> STEP "When I sum them" SHOULD NOT MATCH have_number    ✔
>> STEP "When I divide them" SHOULD NOT MATCH ANY    ✔
>> STEP "When I divide them" SHOULD NOT MATCH sum_numbers    ✔
>> STEP "Then I expect the result to be 8" SHOULD MATCH expect_result    ✔

6 sentences (6 passed)
Covered 3 of 3 step implementations
```

and

```
/nix/store/lyv6m9y4bi8cc5sls1k1gvbqh6dxmyvq-python3.12-radish-bdd-0.17.1/bin/radish -b radish features/SumNumbers.feature 

/nix/store/lyv6m9y4bi8cc5sls1k1gvbqh6dxmyvq-python3.12-radish-bdd-0.17.1/lib/python3.12/site-packages/radish/extensions/time_recorder.py:36: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  feature.starttime = datetime.utcnow()
Feature: Test summing numbers  # features/SumNumbers.feature
    In order to test the basic
    features of radish I test
    to sum numbers.
/nix/store/lyv6m9y4bi8cc5sls1k1gvbqh6dxmyvq-python3.12-radish-bdd-0.17.1/lib/python3.12/site-packages/radish/extensions/time_recorder.py:42: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  scenario.starttime = datetime.utcnow()

 ....

1 features (1 passed)
2 scenarios (2 passed)
9 steps (9 passed)
Run 1731171431 finished within a moment
```

I guess i need to fix the DeprecationWarning at some point upstream :see_no_evil:

**Comment by fliiiix** [comment]
Ahh yikes all the good tests never where executed updated that as well

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
