### PR TITLE
nvidia_x11: 2019-11.1

### PR DESCRIPTION
**Pull request by eadwu**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by eadwu** [comment]
Reused old url since for some reason some revisions don't exist as tags in the Github repository.

**Comment by veprbl** [comment]
@GrahamcOfBorg eval

**Comment by veprbl** [comment]
cc @baracoder

**Review by baracoder — APPROVED** [review]

**Comment by veprbl** [comment]
@eadwu I believe the eval error is not spurious. I am not sure where it comes from.

**Comment by eadwu** [comment]
Supposedly it comes from `bumblebee.nix` and specifically from `nvidia_x11.useGLVND ` though I have no idea just changing the versions and hashes results in something unrelated popping up.

**Comment by baracoder** [comment]
How can I reproduce the eval check locally?

**Comment by 7c6f434c** [comment]
>How can I reproduce the eval check locally?

Does nixpkgs/maintainers/scripts/eval-config.sh pass locally?

**Comment by srhb** [comment]
You're no longer applying `generic` in the right place because you rewrote the expression for `stable` -- hence the `null`. If you reuse the existing structure, everything evals just fine.

**Pull request merged**
