### PR TITLE
go_1_21: 1.21rc4 -> 1.21.0

### LINKED ISSUE #250350: Package request: go_1_21
**Project description**

The Go Compiler

**Metadata**

* homepage URL:https://go.dev 
* source URL: https://github.com/golang/go
* license: bsd
* platforms: unix, linux, darwin

### PR DESCRIPTION
**Pull request by zowoq**
Changelog: https://go.dev/doc/devel/release#go1.21

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
I think I'll leave this open as a draft and merge it to master after https://github.com/NixOS/nixpkgs/pull/238100 goes through staging-next.

**Comment by zowoq** [comment]
I want to leave this open for visibility as I don't want someone to open a PR adding go_1_21/buildGo121Module on master.

**Review by mdwn — APPROVED** [review]
I realize this is still in draft, but this LGTM.

**Comment by diamondburned** [comment]
> I think I'll leave this open as a draft and merge it to master after #238100 goes through staging-next.

Why is this required? Isn't #238100 over 2 months old?

**Comment by zowoq** [comment]
> > I think I'll leave this open as a draft and merge it to master after #238100 goes through staging-next.
> 
> Why is this required? Isn't #238100 over 2 months old?

It was only merged a couple of weeks ago.

https://nixpk.gs/pr-tracker.html?pr=238100

**Pull request merged**
