### PR TITLE
anbox: init at 2019-03-07

### PR DESCRIPTION
**Pull request by gebner**
###### Motivation for this change

[Android in a box](https://github.com/anbox/anbox/)

This is an update of @edwtjo's PR #48040.  Now networking works out of the box---I just had to enable NAT, networking works even though `adb shell ip r` doesn't show a default route.

For testing, I'm starting `anbox session-manager` and then `anbox-application-manager`.

cc @edwtjo @Mic92 @jasoncarr0 @peterhoeg 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
Is there a reason to not use `gtest`? Cursory glance suggests it's the same source.

**Comment by gebner** [comment]
@dtzWill Good point.  It requires a fair amount of patching in the cmake code but it's doable.  Upstream includes googletest as a cmake external project, which expects the googletest source code.

**Review by Mic92 — APPROVED** [review]
I tested the previous PR, since there are no significant changes here, I assume it should be fine.

**Comment by Mic92** [comment]
If anbox works like Android the routing tables for the default route should be in other routing tables then `main`. Just use `adb shell ip rule` to list them.

**Comment by zarelit** [comment]
@Mic92  This is the last open PR about introducing Anbox, I didn't follow the whole story, I put it here just for reference https://github.com/NixOS/nixpkgs/pull/48040

**Comment by gebner** [comment]
@Mic92 I would have never found that.  `ip r s t 0` shows indeed that the default route is set up correctly.

**Comment by zarelit** [comment]
:tada:

**Comment by Mic92** [comment]
@gebner Yeah source routing policies is a not-well known corner of the Linux networking stack. It comes right in terms of weird right after tc.

**Pull request merged**
