### PR TITLE
Python on Nix tests

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
what does venv get us when we already have PYTHONPATH to specific packages?

**Comment by FRidh** [comment]
I don't understand what you mean. These tests are to ensure `venv` still functions.

**Comment by jonringer** [comment]
oh, for some reason I thought we were using venv to test packages, not a test to validate venv's functionality

**Review by jonringer — APPROVED** [review]
```
[nix-shell:/home/jon/.cache/nixpkgs-review/pr-85793]$ nix-build ./nixpkgs/ -A python38.tests.nixenv-venv
these derivations will be built:
  /nix/store/zqcgfwj2x21yc3yn5x2cplhd7n746i2h-python3-3.8.2-env.drv
  /nix/store/msicpycvg075am99zl2yksqp1ykk7d15-python3-3.8.2-venv.drv
  /nix/store/2z9bp5hnscznywiplca9bknwpijgpql7-python3-3.8.2-tests-nixenv-venv.drv
building '/nix/store/zqcgfwj2x21yc3yn5x2cplhd7n746i2h-python3-3.8.2-env.drv'...
created 4 symlinks in user environment
building '/nix/store/msicpycvg075am99zl2yksqp1ykk7d15-python3-3.8.2-venv.drv'...
building '/nix/store/2z9bp5hnscznywiplca9bknwpijgpql7-python3-3.8.2-tests-nixenv-venv.drv'...
test_base_prefix (test_python.TestCasePython) ... ok
test_interpreter (test_python.TestCasePython) ... ok
test_prefix (test_python.TestCasePython) ... ok
test_python_version (test_python.TestCasePython) ... ok
test_site_prefix (test_python.TestCasePython) ... ok

----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
/nix/store/vgk3dzw6smq6w722d5iaapmirwdchy1f-python3-3.8.2-tests-nixenv-venv
```

**Pull request merged**
