### PR TITLE
radicle-node: 1.0.0-rc.9 → 1.0.0-rc.10, wrappers and a better package test

### PR DESCRIPTION
**Pull request by lorenzleutgeb**
## Description of changes

 * Add wrapping to control `$PATH` (requested by @gsaslis) and a test that does a little more than just version comparison.
 * Bump version. Release announcement: https://radicle.zulipchat.com/#narrow/stream/409174-announcements/topic/1.2E0.2E0-rc.2E10

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by amesgen — APPROVED** [review]

**Comment by gador** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 313740` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>radicle-node</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
radicle-node:
<details>

got build log for '/nix/store/2nybm8ad5kizljh3929dab57jw0c09ic-radicle-node-1.0.0-rc.9' from 'daemon'
When evaluating attribute ‘radicle-node’:
warning: environment-variables-go-to-env
Environment variable `PKG_CONFIG_ALLOW_CROSS` should be moved to `env` attribute rather than being passed directly to ‘stdenv.mkDerivation’.

Near pkgs/build-support/rust/build-rust-package/default.nix:135:3:

```
    |
135 |   PKG_CONFIG_ALLOW_CROSS =
    |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/environment-variables-go-to-env.md
</details>
</details>

**Comment by lorenzleutgeb** [comment]
@gador
> The following issues got detected with the above build packages. Please fix at least the ones listed with your changed packages:
> radicle-node:
> 
> got build log for '/nix/store/2nybm8ad5kizljh3929dab57jw0c09ic-radicle-node-1.0.0-rc.9' from 'daemon' When evaluating attribute ‘radicle-node’: warning: environment-variables-go-to-env Environment variable `PKG_CONFIG_ALLOW_CROSS` should be moved to `env` attribute rather than being passed directly to ‘stdenv.mkDerivation’.
> 
> Near pkgs/build-support/rust/build-rust-package/default.nix:135:3:
> 
> ```
>     |
> 135 |   PKG_CONFIG_ALLOW_CROSS =
>     |   ^
> ```
> 
> See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/environment-variables-go-to-env.md

Interesting. The variable is not set explicitly in the derivation, so I have to assume that `buildRustPackage` sets it?

**Comment by gador** [comment]
Yes I suppose so. I would just ignore it 🤷

**Comment by lorenzleutgeb** [comment]
@gador could you please approve this PR using GitHub?

**Review by gador — APPROVED** [review]

**Comment by lorenzleutgeb** [comment]
Ping @amesgen and @gabor: Since 1.0.0-rc.10 was released today, I decided to hijack my own PR here...

**Review by gador — APPROVED** [review]
LGTM!

**Review by amesgen — APPROVED** [review]
LGTM

FTR: When I built this locally, I got a test failure:
```
thread 'tests::e2e::test_connection_crossing' panicked at radicle-node/src/tests/e2e.rs:859:9:
assertion `left == right` failed
  left: Outbound
 right: Inbound
```
It went away after re-running though.

**Comment by lorenzleutgeb** [comment]
@amesgen Hmm, looks like @ju1m also got this failure, based on https://github.com/NixOS/nixpkgs/pull/314440/files#diff-0629dcd6451247ef192e1aa0eb390a6d8ce64612b8974870e1b900ef91d1c47dR43-R47 ... let's see what happens on ofborg. Maybe I'll disable that test in this PR...

**Comment by ju1m** [comment]
> @amesgen Hmm, looks like @ju1m also got this failure, based on https://github.com/NixOS/nixpkgs/pull/314440/files#diff-0629dcd6451247ef192e1aa0eb390a6d8ce64612b8974870e1b900ef91d1c47dR43-R47 ... let's see what happens on ofborg. Maybe I'll disable that test in this PR...

@lorenzleutgeb, AFAICS it's a known flaky test:
- https://radicle.zulipchat.com/#narrow/stream/369277-heartwood/topic/Flaky.20tests/near/438352360
- pointing to https://wumpus.liw.fi/log-930f9b0a7e91f83a031120431db48e74c42cb96a/log-2024-05-13T12:35:05Z.802.fail.html#run3-stderr

**Comment by lorenzleutgeb** [comment]
Alright, not waiting for ofborg then. I'll copy from your PR.

**Pull request merged**
