### PR TITLE
doc/contributing: replace outdated 'nix run' syntax for nixpkgs-review

### PR DESCRIPTION
**Pull request by kenranunderscore**
###### Description of changes

When preparing my first PR I stumbled over "strange" `nix run nixpkgs.nixpkgs-review -c ...` examples in the "Pull Request Template" section of the manual. I changed those to the current version that worked for me, but also added an example of how to do it with `nix-shell`, plus some minor fixups.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by rnhmjoj — APPROVED** [review]

**Review by teutat3s — APPROVED** [review]

**Comment by jtojnar** [comment]
Maybe we should just keep the non-flakes variants? Those are guaranteed to work as long a person has `NIX_PATH` and people who do not have `NIX_PATH` will know how to make the command work.

**Comment by teutat3s** [comment]
I don't mind which one the two options comes first, but I'd like to see the flakes option mentioned in the manual, too.

**Comment by kenranunderscore** [comment]
I've checked other parts of the manual and the `nix-shell` versions seem to prevail (for good reason). I've updated the commands accordingly, while still giving one example for the flaky variant.

**Comment by kenranunderscore** [comment]
Is there anything else I could/should do here? I'm wondering if I should rebase this from time to time or just wait?

**Comment by jtojnar** [comment]
Thanks.

**Pull request merged**
