### PR TITLE
Don't overspecify the julia version

### PR DESCRIPTION
**Pull request by garrison**
This is to bring the julia version information into accordance with
section 7.3.2 of the nixpkgs manual:

```
The version in the filename should leave out unnecessary detail.
For instance, if we keep the latest Firefox 2.0.x and 3.5.x
versions in Nixpkgs, they should be named firefox/2.0.nix and
firefox/3.5.nix, respectively (which, at a given point, might
contain versions 2.0.0.20 and 3.5.4).
```

Julia uses semantic versioning (http://semver.org), so the third
digit (the patch level) represents backwards-compatible bug fixes
only.

### CODE REVIEW

**Comment by 7c6f434c** [comment]
>Julia uses semantic versioning (http://semver.org), so the third
>digit (the patch level) represents backwards-compatible bug fixes
>only.

I am not sure if their build system doesn't change between patchlevel
releases. Did you check?

I guess when Julia is 1.0+, I will believe the claim that patchlevel
releases are safe without any further thought, now I am just not sure
(but cannot exclude they are safe).

**Comment by garrison** [comment]
What exactly do you mean by the build system not changing between patchlevel releases?  For instance, there was recently a migration to using libgit2 which introduced a dependency on cmake, but this was only done on master (which will become the 0.4 branch).  In general the release-0.3 branch is for bug fixes only, not new features.

**Comment by 7c6f434c** [comment]
>What exactly do you mean by the build system not changing between patchlevel releases?  For instance, there was recently a migration to using libgit2 which introduced a dependency on cmake, but this was only done on master (which will become the 0.4 branch).  In general the release-0.3 branch is for bug fixes only, not new features.

It is a definite thing that we need to update dependencies. I think, but
maybe it was minor-version release, there were moments where not 
updating some things about dependency handling correctly lead to build
success with more broken features than before the update (I failed to
ensure that all Julia features work in NixPkgs version)

Currently, I don't understand which parts of testsuite can be made to
work, so I cannot just trust tests.

**Comment by garrison** [comment]
> Currently, I don't understand which parts of testsuite can be made to
work, so I cannot just trust tests.

I'm confused.  Are there parts of the julia testsuite that fail under nixpkgs?

**Comment by 7c6f434c** [comment]
>> Currently, I don't understand which parts of testsuite can be made to
>work, so I cannot just trust tests.
>
>I'm confused.  Are there parts of the julia testsuite that fail under nixpkgs?

Yes.

**Comment by garrison** [comment]
>> I'm confused.  Are there parts of the julia testsuite that fail under nixpkgs?

> Yes.

As mentioned in PR #5853 (just merged), I got tests working on 0.3.X but was unable to get them to work on 0.2.1. However, the 0.2-release branch is dead (its latest commit was Aug 8) and will receive no more releases.

**Comment by 7c6f434c** [comment]
>>> I'm confused.  Are there parts of the julia testsuite that fail under nixpkgs?
>
>> Yes.
>
>As mentioned in PR #5853 (just merged), I got tests working on 0.3.X but was unable to get them to work on 0.2.1. However, the 0.2-release branch is dead (its latest commit was Aug 8) and will receive no more releases.

Thanks, I tried and failed (no later than 0.3.1, though)

**Comment by garrison** [comment]
> Thanks, I tried and failed (no later than 0.3.1, though)

0.3.5 is the latest bugfix release for the 0.3 branch, so there should be no reason to use 0.3.1 if all tests pass on 0.3.5.

**Comment by 7c6f434c** [comment]
>> Thanks, I tried and failed (no later than 0.3.1, though)
>
>0.3.5 is the latest bugfix release for the 0.3 branch, so there should be no reason to use 0.3.1 if all tests pass on 0.3.5.

I completely agree. I am glad that current version of Julia and your
efforts together allow us to have non-broken Julia testsuite.

Thanks!

**Comment by garrison** [comment]
> I completely agree. I am glad that current version of Julia and your
efforts together allow us to have non-broken Julia testsuite.

Sorry, I misunderstood the sentiment of what you meant. ;)  I'm happy to help.  And do let me know if you have any remaining thoughts on this current pull request.

**Comment by garrison** [comment]
Thanks!

**Pull request merged**
