### PR TITLE
Coq elpi 1.10.1

### PR DESCRIPTION
**Pull request by gares**
###### Motivation for this change
update coq-elpi

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gares** [comment]
@GrahamcOfBorg build coqPackages_8_13.coq-elpi coqPackages_8_13.hierarchy-builder

**Comment by gares** [comment]
@GrahamcOfBorg build coqPackages_8_13.coq-elpi coqPackages_8_13.hierarchy-builder

**Comment by gares** [comment]
@GrahamcOfBorg build coqPackages_8_13.coq-elpi coqPackages_8_13.hierarchy-builder

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 124350` at ec2e9166 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built successfully:</summary>
  <ul>
    <li>coqPackages.coq-elpi</li>
    <li>coqPackages.hierarchy-builder</li>
    <li>coqPackages.mathcomp-analysis</li>
  </ul>
</details>

**Comment by gares** [comment]
@GrahamcOfBorg build coqPackages_8_13.hierarchy-builder

**Comment by gares** [comment]
@vbgl this seems ready now

**Review by CohenCyril — APPROVED** [review]

**Comment by vbgl** [comment]
It seems that recent versions of elpi can be built with `ppxlib` > 0.15 (and therefore with latest versions of OCaml).

**Comment by gares** [comment]
Upstream I test 4.04, 4.07 and 4.11, so I m not so sure the constraint is coming from ppxlib

**Pull request merged**
