### PR TITLE
nixos/grafana: fix assertions leaking into YAML

### LINKED ISSUE #224623: `services.grafana.provision.datasources` is parsing `assertions` into the generated `yaml` file
### Describe the bug
The `services.grafana.provision.datasources` module seems to be generating wrong `yaml` file.

### Steps To Reproduce

I have this in my `configuration.nix`:
```
config.services.grafana = {
  enable = true;
  provision = {
    enable = true;
    datasources.settings.datasources = [
      {
        name = "prometheus";
        type = "prometheus";
        url = "localhost:${toString config.services.prometheus.port}";
        isDefault = true;
      }
    ];
  };
}
```

And the generated `datasource.yaml` looks like this:
```
 cat /nix/store/f2a3k24cq2hhf6y0apm5la0cz9yrp6fw-grafana-provisioning/datasources/datasource.yaml
apiVersion: 1
datasources:
- access: proxy
  assertions:
  - assertion: true
    message: 'The option definition `basicAuthPassword'' in  no longer has any effect;
      please remove it.

      `services.grafana.provision.datasources.settings.datasources.<name>.basicAuthPassword`
      has been removed
      in Grafana 9. Use `secureJsonData` instead.


      '
  - assertion: true
    message: 'The option definition `password'' in  no longer has any effect; please
      remove it.

      `services.grafana.provision.datasources.settings.datasources.<name>.password`
      has been removed

      in Grafana 9. Use `secureJsonData` instead.


      '
  editable: false
  isDefault: true
  name: prometheus
  secureJsonData: null
  type: prometheus
  uid: null
  url: localhost:9090
deleteDatasources: []
```
I have problem where `grafana` is creating 3 datasources from this, not sure if this is what causing it. (screenshot below)

### Expected behavior
The `datasources.assertions` shouldn't be there.

### Screenshots

Screenshot from 2023-04-04 17-11-06

### Additional context

This is the code where the data is being parsed: https://github.com/NixOS/nixpkgs/blob/53dad94e874c9586e71decf82d972dfb640ef044/nixos/modules/services/monitoring/grafana.nix#L16-L26

### Notify maintainers

@KFearsoff @Ma27 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.21, NixOS, 23.05 (Stoat), 23.05.20230402.7c65685`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by KFearsoff**
This commit deletes the assertions that were added in 4ec456b. Those assertions weren't even working to begin with, and they also cause assertions leak into the generated YAML.

###### Description of changes

Fixes #224623 and #211060

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
IMHO it would be nicer to fix this rather than silently removing it. Especially considering that nobody seems to have gotten a warning.

**Comment by KFearsoff** [comment]
> IMHO it would be nicer to fix this rather than silently removing it. Especially considering that nobody seems to have gotten a warning.

It would be, yeah. But I've spent some time digging into it and haven't really found a way to fix it. Assertions in submodules are kinda weird.

**Comment by budimanjojo** [comment]
Want to add that the leakage of assertion into the yaml file doesn't cause any problem with the behavior of `grafana` itself.

**Comment by Ma27** [comment]
OK, now that I think of it: it was silently removed already because of the `flip removeAttrs` part in the `apply` of `datasources`, so this will have zero impact.

**Comment by Ma27** [comment]
@ofborg test grafana

**Review by Ma27 — APPROVED** [review]

**Pull request merged**
