### PR TITLE
nixos/dokuwiki: Drop deprecated old interface

### PR DESCRIPTION
**Pull request by onny**
###### Motivation for this change
This PR drops the old deprecated interface used before NixOS 21.11. The syntax `services.dokuwiki."hostname.local" was changed to `services.dokuwiki.sites."hostname.local"`. A deprecation notice was added to the NixOS 21.11 release notes.
It would be good to drop the old interface to cleanup the Dokuwiki module with NixOS 22.05.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [x] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Should we not add a note in the release notes ?

**Comment by onny** [comment]
Thanks for the review, added a note to the release notes

**Review by 1000101 — APPROVED** [review]

**Comment by happysalada** [comment]
@NinjaTrappeur you were using this if I remember correcty. This looks good to me to merge.
I'm going to wait a couple more days in case you have time to have a look.

**Comment by NinjaTrappeur** [comment]
Hey,

I'm not using this module anymore. Thanks for the heads up though :)

**Pull request merged**
