### PR TITLE
staging-next 2022-08-25

### PR DESCRIPTION
**Pull request by vcunat**
- workflow docs: [nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy](https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy)
- important job(s): [hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents](https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents)
- jobset: [hydra.nixos.org/jobset/nixpkgs/staging-next](https://hydra.nixos.org/jobset/nixpkgs/staging-next)
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/186941

### CODE REVIEW

**Comment by NickCao** [comment]
systemd cross compilation is broken by the enablement of libbpf, fixed in https://github.com/NixOS/nixpkgs/pull/188291

**Comment by mweinelt** [comment]
- [ ] `python3.pkgs.graphviz` and `python3.pkgs.pygraphviz` both fail in `test_render` @dotlambda 
  https://hydra.nixos.org/build/188590842
- [ ] `python3.pkgs.moto` fails multiple tests

**Comment by mweinelt** [comment]
@ofborg eval

**Comment by SuperSandro2000** [comment]
Fix for python310Packages.moto https://github.com/NixOS/nixpkgs/pull/188962

**Comment by fabianhjr** [comment]
https://github.com/NixOS/nixpkgs/pull/188983

Introduced an stdenv build failure due to changes of openssl version and removal of no warn error flag.

**Comment by SuperSandro2000** [comment]
> #188983
> 
> Introduced an stdenv build failure due to changes of openssl version and removal of no warn error flag.

https://github.com/NixOS/nixpkgs/pull/189126

**Comment by vcunat** [comment]
Now I'm not aware of any unfixed significant regression, so I'm just waiting for Hydra's `*-linux` builders to work again.  Then we'll see.

**Comment by vcunat** [comment]
Fox `x86_64-linux` the [regressions](https://hydra.nixos.org/eval/1779804?filter=x86_64-linux&compare=1779817) seem mainly due to openssl upgrade so far.*  Perhaps it's not significant, but I see *multiple* cases of cargo not dealing with openssl update, e.g. https://hydra.nixos.org/log/ds44h79zyjydl10n50308lgi3ffkdf11-quill-0.2.7.drv

\* Hydra is still processing slowly, as only one Linux builder works, added in an emergency fashion.  Darwin builders also seem significantly worse than usual, including x86 emulation issues.

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by vcunat** [comment]
- [ ] `python3*Packages.pycurl` on `aarch64-darwin` regressed, despite retrying many times.  The trace looks likely related to the openssl upgrades/pins.
  https://hydra.nixos.org/build/188672968#tabs-buildsteps

**Comment by FRidh** [comment]
I just accidentally merged this. Looking at the overview it does not seem to block anything. 

> * [ ]  `python3*Packages.pycurl` on `aarch64-darwin` regressed, despite retrying many times.  The trace looks likely related to the openssl upgrades/pins.
>       https://hydra.nixos.org/build/188672968#tabs-buildsteps
>       I point it out because hundreds of packages depend on it.

We could disable the test file for aarch64-darwin to unblock it.

**Comment by vcunat** [comment]
Merge at this point was most likely OK-ish.

**Comment by vcunat** [comment]
Uh... you merged it the other way.  So that `staging-next` was the first parent and `master` was the second parent.  That's a bit inconvenient for some of my workflows.

**Pull request merged**
