### PR TITLE
ats-pkg init at 3.2.1.8

### PR DESCRIPTION
**Pull request by bbarker**
###### Motivation for this change

Allow more ATS packages to be built in Nix

###### Things done

I actually haven't tested this locally, and suspect I did something stupid (or didn't do something smart) because `nix-env -I nixpkgs=/home/brandon/workspace/nixpkgs -i ats-pkg` fails with `error: selector 'ats-pkg' matches no derivations `.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bbarker** [comment]
@vmchale any ideas? I basically just ran cabal2nix to get all the interesting bits.

**Comment by bbarker** [comment]
Local build now gets fairly far with the following:

```
 nix-env --show-trace -f /home/brandon/workspace/nixpkgs -iA haskellPackages.ats-pkg  
```

The failure point appears to occur near the end of the build, though I don't know much about Haskell builds as yet:

```
[7 of 7] Compiling Language.ATS     ( src/Language/ATS.hs, dist/build/Language/ATS.p_o )
ignoring (possibly broken) abi-depends field for packages
Preprocessing test suite 'language-ats-test' for language-ats-1.5.0.0..
Building test suite 'language-ats-test' for language-ats-1.5.0.0..
[1 of 1] Compiling Main             ( test/Spec.hs, dist/build/language-ats-test/language-a
ts-test-tmp/Main.o )                                                                      
Linking dist/build/language-ats-test/language-ats-test ...
running tests
Running 1 test suites...
Test suite language-ats-test: RUNNING...
language-ats-test: test/data/stdlib/DATS: getPermissions:getFileStatus: does not exist (No 
such file or directory)                                                                   
Test suite language-ats-test: FAIL
Test suite logged to: dist/test/language-ats-1.5.0.0-language-ats-test.log
0 of 1 test suites (0 of 1 test cases) passed.
builder for '/nix/store/s7nqd67aiyww64w50zxxr2lxsa60vwdr-language-ats-1.5.0.0.drv' failed w
ith exit code 1                                                                           
cannot build derivation '/nix/store/dbwmqzgjh43pxnycfwiv8aknd8a3q664-shake-ats-1.9.0.2.drv'
: 1 dependencies couldn't be built                                                        
cannot build derivation '/nix/store/rw23zprmrng2df18akh2p7gfg3yazg5p-ats-pkg-3.1.0.12.drv':
 1 dependencies couldn't be built                                                         
error: build of '/nix/store/rw23zprmrng2df18akh2p7gfg3yazg5p-ats-pkg-3.1.0.12.drv' failed
```

Not sure what I've done to make @GrahamcOfBorg fail earlier. 

@vmchale , any ideas on the particular build error related to not finding the files?
@shlevy @puffnfresh Any suggestions in general for either the local build error or the @GrahamcOfBorg build error (or otherwise)?

**Comment by vmchale** [comment]
I suspect that the build of `language-ats` failed because I uploaded a package that did not include all the required test data. Any version of `language-ats` later than 1.7.0.1 should work I believe.

**Comment by bbarker** [comment]
Interesting that @GrahamcOfBorg passes, I still have this failing locally witht he issue about language-ats mentioned above

**Comment by bbarker** [comment]
@vmchale I just noticed something very peculiar; when I try running the command:

```
 nix-env --show-trace -f /home/brandon/workspace/nixpkgs -iA haskellPackages.ats-pkg  
```

I see the message `installing 'ats-pkg-3.1.0.12'` which is not even remotely the correct version.

**Comment by bbarker** [comment]
I now see the error in my ways - the supposedly erroneous version above was coming from `haskellPackages.ats-pkg`, which appears to be the canonical way of dealing with hackage packages in nix. And it works, so closing this.

**Pull request closed without merging**
