### PR TITLE
bundlerApp: avoid unecessary rebuilds when gemdir changes

### PR DESCRIPTION
**Pull request by zimbatm**
Because the gemdir was referenced on the derivation, it would cause the
whole gemdir to get added to the store, which would in turn force the
derivation to be rebuilt whenever unrelated folder files would change.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by zimbatm** [comment]
I remember this being an issue recently, not sure where exactly. This should be back-ported to 19.09.

**Review by manveru — APPROVED** [review]

**Comment by alyssais** [comment]
> I remember this being an issue recently, not sure where exactly. This
> should be back-ported to 19.09.

https://github.com/NixOS/nixpkgs/pull/63177#issuecomment-529171458

**Comment by alyssais** [comment]
Backported in 1b132a979a9.

**Comment by volth** [comment]
I'd be happy if magic filenames in gemdir would gone, being replaced with explicit `import ./gemdir.nix` or something which would allow replacing and (post-)patching of individual libraries.

**Comment by zimbatm** [comment]
@volth I wouldn't mind removing the magic either. I had the idea initially but am not holding strongly onto it. The idea was to simplify each bundlerApp declaration but it's probably not worth saving 20 characters per derivation.

**Comment by alyssais** [comment]
+1 to removal

**Pull request merged**
