### PR TITLE
 haskell generic-builder: Fix Dependencies

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

The idea is that one can do `cabal configure $NIX_CABAL_FOREIGN_FLAGS` which ensure that Cabal knows about C headers and libs, but not the c compiler itself.

 - nativeGhc          -> depsBuildBuild
 - Setup.hs libraries -> nativeBuildInputs
 - other tools        -> nativeBuildInputs
 - libraries          -> (propagated)NativeBuildInputs

Also, I'm trying to start the process of smoothing over the differences between our builder and shell env.

 - Everyone gets tools
 - Everyone only accesses C through Cabal
 - No one gets extra `-system` or `-L` flags

I'd like to go even farther and 
 1. stop using `ghcWithPackages`
 2. pass `--with-package-db` to `./Setup` / `NIX_CABAL_FOREIGN_FLAGS`
 3. Only use the new db in the builder for the to-be-built package

`ghcWithPackages`, OTOH, should use a `cc-with-packages`, for a completely (cabal-install or stack)-free persistent environments. Granted, I don't know why one would want to not use either of these tools, but if `ghcWithPackages` continues to exist with the plan above, this gives it its own clear-cut and distinct niche.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peti** [comment]
Can you please re-base on top of the current `master` to shrink the diff?

**Comment by ttuegel** [comment]
Why not set the flags through `CABAL_CONFIG`?

**Comment by Ericson2314** [comment]
@ttuegel Oh, I didn't know about that. Perfect!

@peti Will do.

**Comment by Ericson2314** [comment]
OK the later commits I added aren't really appropriate at this time, as I need to dust off my darwin hack first and make it appropriate for `nix-shell`, but I added them just to get the full idea out there for critique.

**Comment by Ericson2314** [comment]
Will revisit after #26799, which is very close.

**Comment by mmahut** [comment]
What is the status of this pull request?

**Comment by domenkozar** [comment]
Closing this as it's out of sync.

**Pull request closed without merging**
