### PR TITLE
[Backport release-23.11] warp-terminal: 0.2024.03.26.08.02.stable_02 -> 0.2024.04.02.08.02.stable_01

### PR DESCRIPTION
**Pull request by 4evy**
## Description of changes

Changelog: https://docs.warp.dev/getting-started/changelog#id-2024.04.04-v0.2024.04.02.08.02

Manually backport and resolved merge conflicts for #302079

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by risicle** [comment]
The commits you've referenced in the cherry-picks didn't end up in either `master` or `staging` - might it have been rebase-merged?

**Comment by DontEatOreo** [comment]
> Source PR seems to have been squash merged but there is a patch from a previous PR that is missing, the expected commits seem to be [4844f7d](https://github.com/NixOS/nixpkgs/commit/4844f7dad30a6b8f7aa39ab709c306e5b5fe0945) [7872e50](https://github.com/NixOS/nixpkgs/commit/7872e50e11b94fc42c14dae8fb22f9ea16a63921)

Hey, uhh how I'm suppose to cherry pick this? Isn't it be `git cherry-pick -x 7872e50e11b94fc42c14dae8fb22f9ea16a63921`?

**Comment by risicle** [comment]
Cherry-pick them one after the other, as separate commits.

**Comment by LeSuisse** [comment]
The automated backport failed in #302079 because #300326 was not backported so something like `git cherry-pick -x 4844f7dad30a6b8f7aa39ab709c306e5b5fe0945 7872e50e11b94fc42c14dae8fb22f9ea16a63921` should do the trick

**Pull request merged**
