### PR TITLE
Bump VSCode version

### PR DESCRIPTION
**Pull request by turion**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by turion** [comment]
Unfortunately this is blocked on https://github.com/VSCodium/vscodium/issues/500

**Comment by srid** [comment]
Should be closed? 1.50 is out.

**Comment by turion** [comment]
@srid Oh good point. I'll pump to 1.50 right away. (Or do you want a separate PR for that?)

**Comment by turion** [comment]
Unfortunately blocked on https://github.com/VSCodium/vscodium/issues/529. The `update.sh` doesn't run through.

**Comment by turion** [comment]
@srid This is now fixed and rebased.

/marvin opt-in
/status needs_reviewer

**Comment by turion** [comment]
@srid can you review or merge?

**Comment by turion** [comment]
Huh. upkeep-bot was faster. I wonder whether there is any point in doing this.

**Comment by turion** [comment]
@eadwu @synthetica are vscode/vscodium versions bumped automatically when the script works fine?

**Review by srid — APPROVED** [review]

**Review by eadwu — APPROVED** [review]
I'm not sure as I never used the update script, nor do I use the stable version.

Verified hashes.

**Comment by samuela** [comment]
> @eadwu @Synthetica are vscode/vscodium versions bumped automatically when the script works fine?

Yup! You can see the trace of all previous runs of the bot here: https://github.com/samuela/nixpkgs-upkeep/actions. It creates PRs whenever the update scripts work. I've found that they only ever really break when vscode has a new release but the vscodium version is not yet released.

**Comment by turion** [comment]
That's great to know. I've documented this now, so people won't waste their time so much in the future.

**Review by danieldk — CHANGES_REQUESTED** [review]
Could you please update the commit message for the version bump to follow the contribution guidelines?

```
vscode, vscodium: 1.50.0 -> 1.50.1 
```

This may seem like nitpicking, but makes it easier to search or process the logs.

**Comment by danieldk** [comment]
Also, the second commit message should be something like:

```
vscode, vscodium: document update scripts 
```

**Comment by turion** [comment]
@danieldk Done :)

**Review by danieldk — APPROVED** [review]
Thanks for updating the commit messages. Looks good to me now.

Result of `nixpkgs-review pr 98088` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>vscode</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
  </ul>
</details>

**Pull request merged**
