### PR TITLE
Backport #14367 and #14389 fixing Sup, sphinx, and xapian to 16.03.

### PR DESCRIPTION
**Pull request by grahamc**
Working on evaluating this. However, if this isn't going to be accepted let me know and I'll cancel it. This isn't a small compile.
###### Things done:
- [ ] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by joachifm** [comment]
Seeing as xapian is unavailable in the release, I'm +1 on merging this

**Comment by grahamc** [comment]
OK I'm ... somewhat ... ? ... of the way through nox-rebuild.

**Comment by grahamc** [comment]
@joachifm most of the packages built okay, some didn't. I can provide a report of the ones which didn't tomorrow. Spot-checking, it looked like most of them were failing before this patch set.

**Comment by cstrahan** [comment]
Assuming no regressions, this gets :+1: from me.

**Comment by grahamc** [comment]
Many regressions. I'll keep working on it, and try and submit smaller PRs which are more likely to get accepted.

**Pull request closed without merging**
