### PR TITLE
nixos/tests/keymap: wait for xdotool to succeed

### PR DESCRIPTION
**Pull request by xeji**
###### Motivation for this change

After merging #39400 we hit another non-deterministic failure:  `xdotool` could fail when a new window was already created but not yet decorated by the window manager (thanks @srhb for catching on to this).

Fix this by waiting for `xdotool` to succeed. Also prevent a never observed but possible race condition elsewhere in the code.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg test keymap.dvorak

**Comment by srhb** [comment]
@xeji Please PR adding yourself to this list: :smile: https://github.com/coreyoconnor/ofborg/blob/d3c21bd8a35e9b0736ec7476a9aefc2e15b15061/config.public.json

**Comment by srhb** [comment]
@GrahamcOfBorg test keymap.dvorak

**Comment by srhb** [comment]
Oh sorry, I see you're already in known users. I didn't see the eval start on the monitor. :-)

**Comment by xeji** [comment]
Looks unrelated. Are the tests supposed to work on aarch64 now? I've never seen one succeed.

**Comment by srhb** [comment]
No, I think that failure is fine.

**Comment by xeji** [comment]
ofborg dashboard says x86_64-linux builder is stalled, this may take a while or time out.

**Comment by srhb** [comment]
I built it locally just fine. How about I merge it to master and we track its progress on Hydra, reopen the ticket and track it for merging to release once we have confidence?

**Pull request merged**
