### PR TITLE
Bring Darwin frameworks and libs into scope in all packages by default

### PR DESCRIPTION
**Pull request by pikajude**
Creates stub packages for Darwin to avoid evaluation failures.

### CODE REVIEW

**Comment by garbas** [comment]
+1 makes things much all-packages.nix much nicer to look at ... any objections to not merge this?

**Comment by rasendubi** [comment]
(triage) would we like to get this rebased and merged?

**Comment by garbas** [comment]
@pikajude ping. could you rebase this on current master?

**Comment by Mic92** [comment]
I think, he won't. maybe somebody else wants to do this?

**Comment by vcunat** [comment]
:+1: for the cleanup/idea, but we'll have beware of name clashes. However, Darwin seems short on maintainers currently and it's likely this won't be among top priorities (but that depends on the particular people).

**Comment by peti** [comment]
@Mic92, I don't have access to a Darwin machine, I'm afraid; I won't be able to help much with this PR.

**Comment by Mic92** [comment]
@peti sorry I thought you did.

**Comment by rasendubi** [comment]
@copumpkin, @vbgl, @acowley, @grahamc, could you help to rebase this?

**Comment by acowley** [comment]
To ground things like name collision concerns a bit, here is [the list of identifiers](https://gist.github.com/acowley/d774720db685d003bb50daae240a022b) that would be brought into scope.

I would like to see some simplification to the mechanism by which darwin-specific dependencies are pulled in:

- the current need to `inherit` from multiple places is a nuisance
- frameworks are quite highly coupled, resulting in there being several ways to write a list of dependencies such that everything needed is included (e.g. you can just depend on `Cocoa` to pull in everything it depends on)

I think I'd be more inclined to have a simple (maybe default scope) way of bringing in a large subset of the system frameworks, `libobjc`, and `xpc` rather than everything included in the above-linked list. Would that kind of approach appeal to anyone else? It might not be possible to agree on a list of essential frameworks (straw man: `Cocoa`, `AVFoundation`, `AGL` and their transitive dependencies), but I'd be up for trying to do so.

**Comment by gilligan** [comment]
@grahamc @LnL7 any thoughts on this? 

@acowley you were worried about too much stuff being brought into scope? Should this be discarded for a different approach or should we solve the conflicts an move ahead somehow ?

**Comment by LnL7** [comment]
I added `darwin.callPackage` when doing some cleanup of the darwin expression, that could ne used to enable this behaviour where desired.

**Comment by acowley** [comment]
@LnL7 would that become the `stdenv.callPackage` on `darwin`? I don’t think (but I could be wrong) moving the `callPackage` call into a conditional would be too popular as a wide-ranging change across nixpkgs. I also still don’t understand how to make `callPackage` customization compositional, so I am reluctant to lean on it.

I’d be happy if we moved `frameworks` directly under `darwin` as a minor concession to usability.

@gilligan I certainly don’t want to be an obstructionist to this effort, so if you have an idea of how something like the `GLUT` framework can avoid conflicts with some other `GLUT` package, I’d be on board.

**Comment by LnL7** [comment]
@acowley No it's opt-in, currently most expressions explicitly pass the darwin dependencies they need. With `darwin.callPackage` those packages will be in the default scope, but it has the caveat that it might shadow toplevel packages.

```nix
{
  libusb1 = callPackage ../development/libraries/libusb1 {
    inherit (darwin) libobjc;
    inherit (darwin.apple_sdk.frameworks) IOKit;
  };

  libusb1 = darwin.callPackage ../development/libraries/libusb1 {};
}
```

**Comment by copumpkin** [comment]
@wizeman @orivej another example

@pikajude I'm still on the fence about this one but could be swayed if you feel strongly about it. I definitely don't like having to pass all the frameworks around explicitly, but am also fearful of some very easy confusion with some of the Apple libraries, including things like `ICU` vs. `icu`

**Comment by mmahut** [comment]
Anyone wants to pick up this work or can we close it due to inactivity?

**Pull request closed without merging**
