### PR TITLE
mathematica: Refactor install process with autoPatchelfHook

### PR DESCRIPTION
**Pull request by armeenm**
###### Motivation for this change
The current fixup procedure uses brittle heuristics for distinguishing executables and shared libraries which often results in unpatched executables (e.g. bundled Java compiled as a PIE).
Replacing the bespoke patching script with `autoPatchelf` greatly simplifies the derivation and makes supporting external links such as CUDALink trivial (will open PR if this is merged).
Some additional deps were added to maximally fulfill `autoPatchelf`. Some deps remain unsatisfied (mostly related to CUDALink and RLink) and will require future work.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Built on NixOS unstable (22.05), with flakes, and both with and without CA derivations.
Tested with Mathematica versions 13.0.0 and 12.3.1.

### CODE REVIEW

**Comment by herberteuler** [comment]
Thanks. It is a pretty considerable change. I will try it out here in the following days, and let us discuss it later.

**Review by herberteuler — APPROVED** [review]

**Comment by herberteuler** [comment]
Sorry for the delay. I was a bit overloaded recently. I am okay with the changes.
However, I have an additional idea to discuss. I tried to add a group of automated tests through `nixosTests` during the verification process. Unfortunately, the attempt failed because an activated Mathematica was needed to execute scripts. Without activation, the execution of commands like `math -script some-script.m` always fails with "No valid password found."
Considering that you will adjust the derivation further, and we will also definitely have other updates in the future, I think it is worthy to curare a test suite of some form here, even if it can only be used by an activated installation. Personally, I have done such things several times, we may need to standardize it, albeit it will not be integrated to NixOS's automated process.
What do you think?

**Comment by veprbl** [comment]
@herberteuler You could add some tests referencing `mathematica` to `mathematica.passthru.tests`, and then at least people who have access to the license can run those.

**Comment by herberteuler** [comment]
> 

That was exactly my attempt. But the tests are run in a qemu virtual host, where we always get a fresh, unregistered version.

**Comment by veprbl** [comment]
Sorry, I missed your point. I suppose the license key could be supplied via some definition in ~/.config/nixpkgs like `config.mathematica.license_key`.

**Comment by herberteuler** [comment]
There is currently no such option yet. But I see a potential solution from your inspiration. Let me try it.

**Comment by herberteuler** [comment]
@veprbl I just got the reply from Wolfram:

> Thank you for contacting Wolfram Technical Support. A virtual machine will have its own machine ID (MathID) which should have its unique activation key to activate Mathematica or other Wolfram products installed on it. If you would like to do a system transfer, please see:
> 
> https://support.wolfram.com/12412

It seems to me that the only way to test would be doing them on the host. I intend to add some test facilities, perhaps independent from the existing testing framework. What do you think?

**Comment by veprbl** [comment]
The DRM is quite hostile. Plus, I assume, it won't be possible to test the GUI via the command line interface. I appreciate your efforts in testing these updates, but if it doesn't lend itself to systematic testing, it may not be worth it.

**Comment by herberteuler** [comment]
As far as I know, it is possible to run tests via the CLI `math --script`. However, I agree with your point on systematic testing, so let's accept this as a pity.

**Pull request merged**
