### PR TITLE
nextcloud25Packages.apps.recognize: init at 3.3.6

### PR DESCRIPTION
**Pull request by dotlambda**
I get
```
Unable to open "/nix/store/ig7li2s4pyvicprhd50wa08nsv880d7z-source-patched/bin/x64.tar.gz" using mode "w+": fopen(/nix/store/ig7li2s4pyvicprhd50wa08nsv880d7z-source-patched/bin/x64.tar.gz): Failed to open stream: Read-only file system`
Downloading of node binary failed
```
originating in https://github.com/nextcloud/recognize/blob/v3.3.6/lib/Migration/InstallDeps.php when adding it to `extraApps`.

Is there a standard way to declaratively change settings in the databse? In particular, I want to set the path to the Node.js binary. See https://github.com/nextcloud/recognize/blob/v3.3.6/lib/Migration/InstallDeps.php#L76.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by urandom2 — APPROVED** [review]

**Comment by benneti** [comment]
@SuperSandro2000 Thanks for your insight! If I might ask why add the packages to the user not the path of the phpfpm service? And I think you meant to write preStart or postStart not script for your workaround did you?
Did you do any recent changes I just tried with the current version on nextcloud 27 and you workaround results in a build error for me.

**Comment by SuperSandro2000** [comment]
> If I might ask why add the packages to the user not the path of the phpfpm service?

Updates sometimes break and having the package available makes it easier to fix up by hand. 

> Also did you do something different on nixos-23.05 where nodejs 14 is not in the cache and marked as insecure?

The app only support nodejs 14, so no.

**Comment by benneti** [comment]
thanks, did you do something to tell `recognize` the correct node path, because for me it still does not work even after recompiling using `npm ci` and I have the feeling it might be due to still trying to use some other node executable (mind though I have no idea about node development...).

**Comment by SuperSandro2000** [comment]
I think I just wrote the static path (``/etc/profiles/per-user/nextcloud/bin/node``) from the user packages into settings

**Comment by benneti** [comment]
Thank you, this is another reason to put it in the user packages.

**Comment by SuperSandro2000** [comment]
We can probably inject that config setting somehow but I didn't dug into that.

**Comment by dotlambda** [comment]
> Is there a standard way to declaratively change settings in the databse? In particular, I want to set the path to the Node.js binary. See https://github.com/nextcloud/recognize/blob/v3.3.6/lib/Migration/InstallDeps.php#L76.

I don't know how. That's what I wanted to express with

> Is there a standard way to declaratively change settings in the databse? In particular, I want to set the path to the Node.js binary. See https://github.com/nextcloud/recognize/blob/v3.3.6/lib/Migration/InstallDeps.php#L76.

**Comment by SuperSandro2000** [comment]
We could just run psql to inject that row in postStart. I don't really have a better idea.

**Comment by Pacman99** [comment]
I tried the workaround above to edit the nextcloud-setup service and I got the following error from npm:
```
51 verbose lifecycle @tensorflow/tfjs-node@4.6.0~install: CWD: /var/lib/nextcloud/store-apps/recognize/node_modules/@tensorflow/tfjs-node
52 silly lifecycle @tensorflow/tfjs-node@4.6.0~install: Args: [ '-c', 'node scripts/install.js' ]
53 info lifecycle @tensorflow/tfjs-node@4.6.0~install: Failed to exec install script
54 silly lifecycle @tensorflow/tfjs-node@4.6.0~install: Returned: code: -2  signal: null
55 info lifecycle @tensorflow/tfjs-node@4.6.0~install: Failed to exec install script
56 verbose stack Error: @tensorflow/tfjs-node@4.6.0 install: `node scripts/install.js`
56 verbose stack spawn sh ENOENT
56 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:19)
56 verbose stack     at onErrorNT (internal/child_process.js:472:16)
56 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
57 verbose pkgid @tensorflow/tfjs-node@4.6.0
58 verbose cwd /var/lib/nextcloud/store-apps/recognize/node_modules
59 verbose Linux 6.1.37
60 verbose argv "/nix/store/l831sxqicw9crp6naj7k538qfimdk1zd-nodejs-14.21.3/bin/node" "/nix/store/l831sxqicw9crp6naj7k538qfimdk1zd-nodejs-14.21.3/bin/npm" "rebuild" "@tensorflow/tfjs-node" "--build-addon-from-source" "--verbose"
```

**Comment by mibmo** [comment]
@SuperSandro2000 has your config changed since then? I'm having the same issue with PATH not updating which just seems ... really weird to me, even when overriding `services.phpfpm.pools.nextcloud.phpEnv.PATH`

**Comment by SuperSandro2000** [comment]
Probably, I am setting the PATH for the user, that cron, systemd services, etc. all contain it.

**Comment by beardhatcode** [comment]
I also try to add Recognise in #333545 , but I took another approach, as the app requires not only the release but also the content of the repo containing the models.

**Comment by mibmo** [comment]
> I also try to add Recognise in #333545 , but I took another approach, as the app requires not only the release but also the content of the repo containing the models.

Closing in favor of this! :)

**Comment by teutat3s** [comment]
Completed in https://github.com/NixOS/nixpkgs/pull/333545

**Pull request closed without merging**
