### PR TITLE
nixos/mysql: fix typing-induced bugs

### PR DESCRIPTION
**Pull request by florianjacob**
###### Motivation for this change
Fixes issues brought up by @schneefux in #58582.

This also tries to prevent `mysql.initialScript` from ending up in /nix/store when given as nix path type, i.e. `initialScript = /etc/nixos/setup-credentials.sql` in contrast to `initialScript = "/etc/nixos/setup-credentials.sql";`, as it might be used for sensitive data like credentials. Uses `toString` for this, as explained here: https://stackoverflow.com/questions/43850371/when-does-a-nix-path-type-make-it-into-the-nix-store-and-when-not

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by florianjacob** [comment]
@schneefux can you give this a test, please? I don't personally use those two features, which is why those errors slipped through. Therefore tried to improve test coverage for those.

This should also fix the issue you would have come up with next, as `initialScript` was wrongly typed by me as multiline as I thought it's something like `extraConfig`, while it is actually a file. Should also stop `initialScript` from turning up in /nix/store, as you brought to my mind that people will likely store credentials in it as there is no other way to create users with passwords declaratively.

**Comment by florianjacob** [comment]
@GrahamcOfBorg test mysql

**Comment by schneefux** [comment]
Yeah, that works. Good job, thank you!

**Review by aanderse — CHANGES_REQUESTED** [review]
https://github.com/NixOS/nixpkgs/blob/14571f5ed02fea504d131b130327f845715a7714/nixos/modules/services/databases/mysql.nix#L366-L375

Can you please provide some documentation explaining how the user can make use of line 373? Seems like a useful feature that most people wouldn't even know exists.

**Comment by flokli** [comment]
Ping :-)

Ran into the current breakage at https://github.com/NixOS/nixpkgs/pull/57550#commitcomment-33603514 too.

**Comment by Infinisil** [comment]
I'll merge this for now

@aanderse This can be done in a follow-up PR. For now fixing this regression is more important.

**Comment by aanderse** [comment]
@Infinisil @flokli Yes, sorry. This sorta fell off my radar and I should have circled back. Thanks.

**Comment by florianjacob** [comment]
> Can you please provide some documentation explaining how the user can make use of line 373? Seems like a useful feature that most people wouldn't even know exists.

@aanderse sorry for my absence, and thanks for your review. While you're right and I think know how that option is intended, I never used it and will therefore refrain from trying to improve it, as this was how I introduced this regression in the first place. :/

**Comment by aanderse** [comment]
@florianjacob no problem, fair enough.

**Pull request merged**
