### PR TITLE
openbb-terminal: init at 3.2.4

### PR DESCRIPTION
**Pull request by techknowlogick**
## Description of changes

Packaging https://github.com/OpenBB-finance/OpenBBTerminal and all of the dependencies of it that haven't been packaged.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Hey, cool that you're working on this. I am getting an error when running it though:

```
This package has been depreciated and greatly upgraded in the Finance Toolkit package. This package can be installed with: pip install financetoolkit -U                                                                                                                                                                       
For more information (including usage and examples) see: https://github.com/JerBouma/FinanceToolkit                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                               
Welcome to OpenBB Terminal v3.2.4                                                                                                                                                                                                                                                                                              
Traceback (most recent call last):                                                                                                                                                                                                                                                                                             
  File "/nix/store/nvdzhsmjlff50w7zkrn5p0qb8aw1lc4r-python3.11-openbb-terminal-3.2.4/bin/.openbb-wrapped", line 9, in <module>                                                                                                                                                                                                 
    sys.exit(main())                                                                                                                                                                                                                                                                                                           
             ^^^^^^                                                                                                                                                                                                                                                                                                            
  File "/nix/store/nvdzhsmjlff50w7zkrn5p0qb8aw1lc4r-python3.11-openbb-terminal-3.2.4/lib/python3.11/site-packages/terminal.py", line 39, in main                                                                                                                                                                               
    session_controller.main(prompt=prompt_login, dev=dev)                                                                                                                                                                                                                                                                      
  File "/nix/store/nvdzhsmjlff50w7zkrn5p0qb8aw1lc4r-python3.11-openbb-terminal-3.2.4/lib/python3.11/site-packages/openbb_terminal/core/session/session_controller.py", line 190, in main                                                                                                                                       
    launch_terminal(queue=queue)                                                                                                                                                                                                                                                                                               
  File "/nix/store/nvdzhsmjlff50w7zkrn5p0qb8aw1lc4r-python3.11-openbb-terminal-3.2.4/lib/python3.11/site-packages/openbb_terminal/core/session/session_controller.py", line 152, in launch_terminal                                                                                                                            
    terminal_controller.parse_args_and_run()                                                                                                                                                                                                                                                                                   
  File "/nix/store/nvdzhsmjlff50w7zkrn5p0qb8aw1lc4r-python3.11-openbb-terminal-3.2.4/lib/python3.11/site-packages/openbb_terminal/terminal_controller.py", line 1248, in parse_args_and_run                                                                                                                                    
    main(                                                                                                                                                                                                                                                                                                                      
  File "/nix/store/nvdzhsmjlff50w7zkrn5p0qb8aw1lc4r-python3.11-openbb-terminal-3.2.4/lib/python3.11/site-packages/openbb_terminal/terminal_controller.py", line 1154, in main                                                                                                                                                  
    terminal()                                                                                                                                                                                                                                                                                                                 
  File "/nix/store/nvdzhsmjlff50w7zkrn5p0qb8aw1lc4r-python3.11-openbb-terminal-3.2.4/lib/python3.11/site-packages/openbb_terminal/terminal_controller.py", line 833, in terminal                                                                                                                                               
    if first_time_user():                                                                                                                                                                                                                                                                                                      
       ^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                                                                       
  File "/nix/store/nvdzhsmjlff50w7zkrn5p0qb8aw1lc4r-python3.11-openbb-terminal-3.2.4/lib/python3.11/site-packages/openbb_terminal/terminal_helper.py", line 440, in first_time_user                                                                                                                                            
    if SETTINGS_ENV_FILE.stat().st_size == 0:                                                                                                                                                                                                                                                                                  
       ^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                                                                
  File "/nix/store/5k91mg4qjylxbfvrv748smfh51ppjq0g-python3-3.11.6/lib/python3.11/pathlib.py", line 1013, in stat                                                                                                                                                                                                              
    return os.stat(self, follow_symlinks=follow_symlinks)                                                                                                                                                                                                                                                                      
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                                      
FileNotFoundError: [Errno 2] No such file or directory: '$HOME/.openbb_terminal/.env' 
```

**Comment by techknowlogick** [comment]
@matthiasbeyer thanks for the testing! Turns out it was only passing for me because I had the config set through other means. After removing the existing config I was able to replicate what you were facing and have included a patch to resolve this on nixos, will send upstream soon.

**Comment by matthiasbeyer** [comment]
Thanks for working on it. If I open some external window, the window is always empty. For example if I go to "stocks" and then search for some stock, another window opens and this is always blank... Not sure whether you can reproduce, but it seems that there's something missing still.

**Comment by techknowlogick** [comment]
@matthiasbeyer hmm... that's interesting. Thanks for the additional testing. My thoughts are: as you're seeing the window, then the pywry dep is probably working, but as it is blank then possible the HTML inside of it is erroring out. And since pywry/wry is kinda like electron, there is probably a webdeveloper console I could capture errors in (or this assumption could be completely wrong, and pywry is missing some gtk lib)
Are you on NixOS, or using nixpkgs on another distro? I suspect what you are facing is something related to the pywry dependency, and so I'd like to try to replicate the environment you're using.

**Comment by matthiasbeyer** [comment]
I am on NixOS 23.05

**Comment by techknowlogick** [comment]
@matthiasbeyer I'm having trouble replicating. I've run through this PR on 23.11 (aarch64) and am building it with `nixpkgs-review`, and I see the window pop-up with search results for stocks. Obviously, this isn't a 1:1 replication, so I still have some things that I can do to track this down.

I'm going to try on 23.05 next, and while I do that, to confirm how are you building this PR, are you using `nix-build`, `nixpkgs-review` or some other way?

Could you also provide a screenshot of what you are seeing?

Thanks again :)

**Comment by techknowlogick** [comment]
@matthiasbeyer I've been struggling to get 23.05 running on my machine (via UTM virtualization. There are apparently some known issues w/ utm around this that I haven't been able to sort out), so I haven't been able to replicate what you are seeing.

Would asking you to rebuild webkit be too much to ask? I can provide a remote builder for you to hopefully make it faster (lmk as I can provide any sized server from equinix metal for ~24hours)

**Comment by matthiasbeyer** [comment]
I am on 23.11 now... but the issue is that this should actually not change the build of this PR, right? Because it is hermetic anyways...

**Comment by techknowlogick** [comment]
closing this PR as `openbb-terminal` is now EOL, and likely won't receive anymore updates.

Thanks @matthiasbeyer for your review of this PR and giving feedback.

**Comment by matthiasbeyer** [comment]
Where do you get this information from? https://github.com/OpenBB-finance/OpenBBTerminal had its last commit not only 9 hours ago...

**Comment by techknowlogick** [comment]
@matthiasbeyer They published the following post: https://openbb.co/blog/sunsetting-openbb-terminal-why-how-and-what-now and in their latest 3.2.5 release https://github.com/OpenBB-finance/OpenBBTerminal/releases/tag/v3.2.5 it is noted as "This will be the final release of the OpenBB Terminal." :(

**Comment by matthiasbeyer** [comment]
Ah, thanks mentioning this. Yes, this is sad. I always wanted to try it, but never got around to it as this package did not land... :cry:

**Comment by happysalada** [comment]
hey, that was some nice work
openbb released a cli
https://docs.openbb.co/cli
it looks similar to the old terminal. However it looks like there are many more dependencies since it uses data from many different sources.
https://github.com/OpenBB-finance/OpenBB/blob/develop/openbb_platform/pyproject.toml
(the cli has the openbb_platform as a main dependency).
This was just to say that openbb isn't necessarily dead.
I'm personally going to try to use this as a raw python package first to test it out, but if you ever end up wanting to package it, ping me and we can split the work.

**Comment by fleimgruber** [comment]
I came to this via https://github.com/NixOS/nixpkgs/issues/228389 and would also be happy to contribute!

**Comment by fleimgruber** [comment]
@happysalada I reported an issue upstream https://github.com/OpenBB-finance/OpenBB/issues/7005 trying their docs.

> I'm personally going to try to use this as a raw python package first to test it out

I tried that just now and got to the same error as in the upstream issue via a local dev env and directly running `uv run --prerelease=allow python openbb_cli/cli.py`.

Did you start on a PR for this already?

**Comment by happysalada** [comment]
No i havent started. Ive been meaning to play with this, but i have access to good data at my work so never got to try this.
Ive got this on my "try when i get fired" list :-)

**Pull request closed without merging**
