### PR TITLE
tree-sitter: 0.19.3 -> 0.19.5

### PR DESCRIPTION
**Pull request by michaeladler**
###### Motivation for this change

package update and some new grammars:

* tree-sitter-tsq (this one is upstream and I personally don't care about)
* tree-sitter-zig (this one I'm interested in)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by michaeladler** [comment]
It looks like the `cargoSha256` is not deterministic. On my machine, I get `/nix/store/z3qyhf3phdgwj96rm824xqdxkw3zshj9-tree-sitter-0.19.5-vendor.tar.gz.drv` but on CI we have `/nix/store/h68df2804rgfcdkcf4f8mp1kxqq4qb3r-tree-sitter-0.19.5-vendor.tar.gz` and thus the build fails, correctly complaining about a sha256 mismatch.

@Profpatsch carnix / cargo2nix to the rescue? Any preferences or do you have something prepared already?

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123874` at cda45656 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/de401955cdfce40299283cd03aec7cd8">rizin</a></li>
    <li><a href="https://gist.github.com/8da7ed4123c5ec584f98cb36b9ea1b5b">tree-sitter</a></li>
  </ul>
</details>
<details>
  <summary>1 package skipped due to time constraints:</summary>
  <ul>
    <li>cutter</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `fetchurl`.
Near pkgs/development/tools/parsing/tree-sitter/default.nix:5:3:
```
  |
5 | , fetchurl
  |   ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Review by ck3d — APPROVED** [review]

**Comment by ck3d** [comment]
It would be great if you could also add following parser: https://github.com/ikatyang/tree-sitter-toml

**Comment by michaeladler** [comment]
@ck3d I have added the toml grammar and rebased onto the latest master branch.

**Review by ck3d — APPROVED** [review]

**Comment by Profpatsch** [comment]
> @Profpatsch carnix / cargo2nix to the rescue? Any preferences or do you have something prepared already? EDIT: carnix does not work with tree-sitter's Cargo.lock and seems abandoned (404). I have updated the cargo hash for now. Not sure why I have a different one locally. There's definitely something funny going on.

It might be a problem with the `buildRustCrate` stuff, but not really in this updates scope to figure that out.

**Comment by Profpatsch** [comment]
Tests are green, LGTM

**Pull request merged**
