### PR TITLE
sbcl: 2.4.0 -> 2.4.1

### PR DESCRIPTION
**Pull request by hraban**
## Description of changes

Also rename to package.nix to make CI pass. Haven't stayed up to date with the developments around this but I guess this works.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by 7c6f434c** [comment]
Ah apparently the check by @infinisil checks for new top-level call and not for new _files_ being called from the top-level, so the directory has to be moved to `pkgs/by-name/sb/sbcl` and all the calls to it retargeted. But hopefully this shouldn't break anything in the process…

**Comment by hraban** [comment]
Hmm it wants `pkgs/by-name/sb/sbcl_2_4_1`, i.e. including the version. That's not ideal.

**Comment by hraban** [comment]
The RFC lists this under "future work":

> What to do with different versions, e.g. wlroots = wlroots_0_14? This goes into version resolution, a different problem to fix

But it's blocking this PR now

**Comment by infinisil** [comment]
Sorry this is a false positive, feel free to ignore!

**Comment by 7c6f434c** [comment]
@ofborg build sbcl.pkgs.iolib sbcl.pkgs.stumpwm

**Comment by infinisil** [comment]
Turns out this shouldn't have been allowed by CI after all, but for different reasons! Check out https://github.com/NixOS/nixpkgs/pull/287083 for more details, we have to move `sbcl` out of `pkgs/by-name` after all :sweat_smile:

**Pull request merged**
