### PR TITLE
phwmon: remove

### PR DESCRIPTION
**Pull request by armeenm**
###### Description of changes
It seems some were still interested in this package as of [2 years ago](https://github.com/NixOS/nixpkgs/pull/74295) but the upstream issue for python3 support [hasn't seen any movement](https://gitlab.com/o9000/phwmon/-/issues/4).
cc @romildo 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by romildo** [comment]
Although it is not essential, I still use `phwmon`. But I do not have a solution to its dependence on python 2. I would keep it in nixpkgs unless it stops working or its removal is essential for other important parts of the system to progress.

**Comment by davidak** [comment]
@romildo maybe you can find an alternative? it's probably a goal to remove all python 2 eventually

**Comment by romildo** [comment]
> @romildo maybe you can find an alternative? it's probably a goal to remove all python 2 eventually

Feel free to remove it. If one day it is ported to python 3, one can repack it.

**Comment by davidak** [comment]
Change looks good.

@armeenm please rebase.

**Comment by armeenm** [comment]
Rebased.

**Review by davidak — APPROVED** [review]

**Pull request merged**
