### PR TITLE
[21.11] qemu: 6.1.0 -> 6.1.1

### PR DESCRIPTION
**Pull request by alyssais**
###### Motivation for this change

Since there's a stable release available, I tihnk it makes more sense to upgrade to it than backport individual patches like in https://github.com/NixOS/nixpkgs/pull/161345 ("[21.11] qemu: add patch for fixing IO errors").  This is going direct to stable because on unstable we went straight from 6.1.0 to 6.2.0.

@lheckemann, would you mind kicking the tires of this and making sure it works well on staging?

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
:thinking: seeing as I didn't enable the tests by default when I added them, could easily port them back to stable and not worry about accidentally breaking the package for anyone...

**Comment by alyssais** [comment]
> thinking seeing as I didn't enable the tests by default when I added them, could easily port them back to stable and not worry about accidentally breaking the package for anyone...

Oh good idea!  I've added the backport label to that PR.

**Comment by lheckemann** [comment]
Yep, seems to work, the IO error bug isn't happening with this.

And @risicle's suggestion sounds sensible too.

**Review by lheckemann — APPROVED** [review]

**Comment by alyssais** [comment]
@risicle I tried backporting your patch, but some of the tests timed out.

**Comment by risicle** [comment]
#162995 it tends to pass for me on the second pass if it fails on the first.

**Pull request merged**
