### PR TITLE
kodi: 18.9 -> 19.0

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
The newest version of `kodi` (`19.x`) has enough changes that I'm guessing we should start testing this sooner rather than later.

This is **heavily** work in progress. I'm hoping other contributors will work with me on this one :heart:

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
A list of things I plan to test and confirm work:
- [x] watching a video
- [x] nfs shares
- [ ] sftp shares
- [ ] `libcec` functionality
- [ ] various `kodiPlugins`
  - [ ] `kodiPlugins.inputstream-adaptive`
  - [ ] `kodiPlugins.joystick`
- [ ] various 3rd party plugins work
  - [ ] subtitles
  - [ ] netflix plugin works
  - [ ] disney plus plugin works
  - [ ] skins
- more to come...

**Comment by aanderse** [comment]
> ... plus many code and platform-specific fixes and improvements that might be less visible to most users, but are still significant, such as the move to a single Linux binary for multiple windowing systems (X11, Wayland, and GBM).

I just read that from the release notes. Looks like I need to fixup done changes I made.

**Comment by cpages** [comment]
Changes look good to me, hope I can help you test some of this in the following days

**Comment by cpages** [comment]
I also tested that vaapi is working, as well as using kore as remote. In fact I saw an issue there (seek is not working), but I guess that's a generic issue. @aanderse have you tried to run it under wayland, btw?

**Comment by aanderse** [comment]
@cpages thanks for the testing and feedback. I have only tested this under `x11`. I was hoping other people could test `wayland` and `gbm` support.

**Comment by aanderse** [comment]
Note to self: take a look at https://github.com/NixOS/nixpkgs/issues/90235 and resolve it with this PR.

**Comment by edwtjo** [comment]
Looks good to me!

**Comment by minijackson** [comment]
Hello and thanks for this!

I can confirm that kodi-wayland works quite well. As for tested plugins, I have tested these:

- vfs.sftp: works perfectly as before
- OSMC skin: automatically disabled because detected as not compatible
- Steam Controller: in the logs it says that it was also automatically disabled, but it is still marked as enabled. The Steam Controller I have with me can control Kodi without any issue with the desktop configuration, but not in the "gamepad" configuration.
- Steam Launcher: needs xdotool and wmcontrol installed, but even then it fails to start Steam (might be because I am on a wayland wm)

**Comment by minijackson** [comment]
Kodi 19.0 was released: https://kodi.tv/article/kodi-190-matrix-release :tada:

**Comment by aanderse** [comment]
Thanks for the ping @minijackson. Anyone interested in some final testing?

I still need to write release notes to mention that `python2` was dropped so there is a high chance all your plugins will break 😆

**Comment by aanderse** [comment]
I dropped the last commit which renamed packages. I decided I have something much better planned for that, which will come in a future PR.

I think this is good to merge now :+1:

**Comment by minijackson** [comment]
If you're talking about the kodi-x11, kodi-wayland, kodi-something variants, if I remember correctly it is possible to put them in a single package, and the provided Kodi startup script will choose the right one

**Comment by aanderse** [comment]
@minijackson yes. I assume someone like @peterhoeg had use for a trimmed down version which only include `gbm`, though.

I'll take care of the package naming changes in a future PR, though... I have a few ideas for some additions to `kodi` which can make my life easier.

**Comment by peterhoeg** [comment]
My kodi appliance (and projector) have been sitting on a shelf, disconnected for quite a while. I'm not going to be able to properly test this out.

**Comment by aanderse** [comment]
> My kodi appliance (and projector) have been sitting on a shelf, disconnected for quite a while.

During a pandemic?! What secret source of entertainment do you have that the rest of us don't!? :wink:

**Comment by aanderse** [comment]
@GrahamcOfBorg build kodi

**Review by cpages — APPROVED** [review]

**Comment by peterhoeg** [comment]
>   During a pandemic?! What secret source of entertainment do you have that
>   the rest of us don't!? 😉

Toddlers and exorcism.

Wait, that's supposed to be toddlers and exercism.io

**Comment by minijackson** [comment]
Hello, sorry I'm late to the party...

It seems I can't compile Kodi for wayland, and I think the problem is due to some word splitting [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/video/kodi/default.nix#L234).

<details>
<summary>Here is the compilation log for <code>kodiPlainWayland</code></summary>

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/7ns8sjplg7sqhig0gngkl4xws1x3m224-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
fixing cmake files...
cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_BUILD_RPATH=ON -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/store/vjmpgip72b5sj4b8w9rjdcpzlxypjh64-kodi-wayland-19.0/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/vjmpgip72b5sj4b8w9rjdcpzlxypjh64-kodi-wayland-19.0/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/vjmpgip72b5sj4b8w9rjdcpzlxypjh64-kodi-wayland-19.0/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/vjmpgip72b5sj4b8w9rjdcpzlxypjh64-kodi-wayland-19.0/share/doc/kodi -DCMAKE_INSTALL_INFODIR=/nix/store/vjmpgip72b5sj4b8w9rjdcpzlxypjh64-kodi-wayland-19.0/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/vjmpgip72b5sj4b8w9rjdcpzlxypjh64-kodi-wayland-19.0/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/vjmpgip72b5sj4b8w9rjdcpzlxypjh64-kodi-wayland-19.0/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/vjmpgip72b5sj4b8w9rjdcpzlxypjh64-kodi-wayland-19.0/include -DCMAKE_INSTALL_SBINDIR=/nix/store/vjmpgip72b5sj4b8w9rjdcpzlxypjh64-kodi-wayland-19.0/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/vjmpgip72b5sj4b8w9rjdcpzlxypjh64-kodi-wayland-19.0/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/vjmpgip72b5sj4b8w9rjdcpzlxypjh64-kodi-wayland-19.0/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_SYSROOT= -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_STRIP=/nix/store/cp1sa3xxvl71cypiinw2c62i5s33chlr-binutils-2.35.1/bin/strip -DCMAKE_RANLIB=/nix/store/cp1sa3xxvl71cypiinw2c62i5s33chlr-binutils-2.35.1/bin/ranlib -DCMAKE_AR=/nix/store/cp1sa3xxvl71cypiinw2c62i5s33chlr-binutils-2.35.1/bin/ar -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/nix/store/vjmpgip72b5sj4b8w9rjdcpzlxypjh64-kodi-wayland-19.0 -DAPP_RENDER_SYSTEM=gl -DCORE_PLATFORM_NAME=wayland x11 -Dlibdvdcss_URL=/nix/store/sawh6jiqqwr1v22g8rjvr2n6cj44cl3r-source -Dlibdvdnav_URL=/nix/store/8ihw7i3l2xrvlzf4dznpwfl8kvvajra8-source -Dlibdvdread_URL=/nix/store/s73vsf3m7faxd7ak1zjn78fl204g6z8m-source -DGIT_VERSION=20210219 -DENABLE_EVENTCLIENTS=ON -DENABLE_INTERNAL_CROSSGUID=OFF -DENABLE_OPTICAL=ON -DLIRC_DEVICE=/run/lirc/lircd -DSWIG_EXECUTABLE=/nix/store/xlkfr9l47kcbbjv74s5ydh2h36r0f3n7-swig-3.0.12/bin/swig -DFLATBUFFERS_FLATC_EXECUTABLE=/nix/store/nnsjyrbk8whanr6c2fpi71bbrs50gnai-flatbuffers-1.12.0/bin/flatc -DPYTHON_EXECUTABLE=/nix/store/yl69v76azrz4daiqksrhb8nnmdiqdjg9-python3-3.8.8/bin/python -DWAYLANDPP_SCANNER=/nix/store/qy31rfaljr6rgwjl3jnlf20pz3jkbrls-waylandpp-0.2.8-bin/bin/wayland-scanner++ 
CMake Error: The source directory "/build/source/build/x11" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```

</details>

No line wrapping is annoying, so here is the CMake flags what I found weird:

```
-DAPP_RENDER_SYSTEM=gl -DCORE_PLATFORM_NAME=wayland x11 -Dlibdvdcss_URL=/nix/store/...
```

**Comment by minijackson** [comment]
Can't wrap my head around why/how the word is splitted, so the only quick fix I found was to set `x11Support` to false for `kodiPlainWayland`. I think the same happens for `kodiGBM`.

That's weird because passing multiple platforms to the `CORE_PLATFORM_NAME` option should be supported if I'm to believe the [Gentoo ebuild file](https://gitweb.gentoo.org/repo/gentoo.git/tree/media-tv/kodi/kodi-19.0.ebuild#n242)...

**Comment by aanderse** [comment]
@minijackson sorry for the hassle... I could swear either I or someone else had tested this, but obviously I screwed something up there :man_shrugging: 

Fix incoming tonight.

**Comment by minijackson** [comment]
No worries, for now it just means I'm stuck with Kodi 19.0RC1, not a life or death situation for me ^^

**Pull request merged**
