### PR TITLE
Revert "Mark ihaskell as broken. Closes #22047."

### LINKED ISSUE #22047: ihaskell fails to build
## Issue description

IHaskell is not GHC 8 compatible, and so it doesn't build on 16.09 onwards. Instead I get this error:

```
Setup: Encountered missing dependencies:
base >=4.6 && <4.9, ghc >=7.6 && <7.11
builder for ‘/nix/store/9bbjk1lknn94y4b7wf9wd9pfgfcfms37-ghc-parser-0.1.8.0.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/ybqc2p7qk1p2i8ka889xh5ksid1xv0kn-ghc-8.0.1-with-packages.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/6mg7sz0sl6ki7r877g3agc3slqwmnlsf-ihaskell-0.8.4.0.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/qjcg07sw2hammhy3jxkarif5i0jszpgk-ipykernel-4.3.1.tar.gz’
cannot build derivation ‘/nix/store/5z2rsbvisv77hqz7rmxlhg1m7kfj7c7y-ihaskell-with-packages.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/5z2rsbvisv77hqz7rmxlhg1m7kfj7c7y-ihaskell-with-packages.drv’ failed
```

### Steps to reproduce

```bash
nix-build '<nixpkgs>' -A ihaskell
```

## Technical details

* System: 16.09.1512.6b28bd0 (Flounder)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: 16.09.1512.6b28bd0

### PR DESCRIPTION
**Pull request by globin**
Reverts NixOS/nixpkgs#22198

cc @teh, broke travis

### CODE REVIEW

**Comment by teh** [comment]
Apologies - not sure how to fix this then, will probably suggest removal.

**Comment by vcunat** [comment]
`throw` should work the way you intended, I believe.

**Comment by vcunat** [comment]
But even that won't work well, as it wouldn't be sensitive to `allowBroken` etc.  I think we should fix `buildEnv` in this respect.

**Comment by vcunat** [comment]
I now have some WIP on this, expecting a PR this weekend.  I hope to also address: #21845, #22102, #7541.

**Pull request merged**
