### PR TITLE
smlnj: 110.84 -> 110.85

### PR DESCRIPTION
**Pull request by vaibhavsagar**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
@grahamcofborg build smlnj

**Comment by ryantm** [comment]
Build was already failing on Darwin on hydra before this patch.

**Comment by vaibhavsagar** [comment]
Good to know I haven't broken anything! Is there anything further you need from me here?

**Comment by ryantm** [comment]
@vaibhavsagar nope, it looks good to me. Thank you; please consider adding yourself as a maintainer.

**Comment by vaibhavsagar** [comment]
Thanks!

**Pull request merged**
