### PR TITLE
bs-platform: remove

### PR DESCRIPTION
**Pull request by superherointj**
Reason development has mostly halted.
BuckleScript became ReScript. Now there is Melange (as a replacement for BuckleScript).
This package currently is [broken](https://termbin.com/yym5). And no one is fixing it.

CC @turbomack @gamb @anmonteiro @ulrikstrid

### CODE REVIEW

**Comment by turboMaCk** [comment]
Good call. I even forgot I added myself to the maintainers. I don't see any problem with removal.

**Comment by ulrikstrid** [comment]
I agree, rescript and melange fill the same space and I think that rescript is a drop-in or has a smooth migration.

**Review by ulrikstrid — APPROVED** [review]

**Comment by superherointj** [comment]
I was going to backport to `release-24.05` because it is also broken there. I get that we shouldn't back-port this kind of thing. But no one is fixing that. And uses build resources for no good reason.

**Comment by AndersonTorres** [comment]
Just for the sake of completeness, it lacked the traditional throw at aliases.nix.

**Comment by superherointj** [comment]
> Just for the sake of completeness, it lacked the traditional throw at aliases.nix.

True, will fix.

**Comment by turboMaCk** [comment]
it's a good point though. we should explicitly throw just to make breaking change slightly more explicit for down stream users.

**Pull request merged**
