### PR TITLE
R: update CRAN package set to snapshot 2018-10-28

### PR DESCRIPTION
**Pull request by thomasjm**
###### Motivation for this change

I wanted to pick up some new R packages that were added since the last snapshot in July. Never done this before, please let me know if I'm missing some test procedure.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peti** [comment]
Have you run the evaluation test that is explained in the documentation?

**Comment by thomasjm** [comment]
Sorry, didn't see that. Ran into some errors, trying to sort it out now...

**Comment by thomasjm** [comment]
Okay, I think things are good now. I had to regenerate the other packages and remove a few things from `default.nix` that don't seem to exist anymore.

**Comment by peti** [comment]
I merged https://github.com/peti/nixpkgs/commit/98c679607fd3430aff83138c8ee287611017d077 into the `r-updates` branch for testing. The builds are running at https://hydra.nixos.org/jobset/nixpkgs/r-updates. Let's see how well the new versions work ...

**Pull request closed without merging**
