### PR TITLE
dockerTools: use closureInfo to load hashes and closure sizes into the Nix DB

### PR DESCRIPTION
**Pull request by dingxiangfei2009**
###### Motivation for this change
Since `closureInfo` is a good extension of `exportReferencesGraph`, we can use it to bootstrap Nix DB with this and possibly eliminates the need to recompute the hashes.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dingxiangfei2009** [comment]
I just realized that `closureInfo` is only available for nix language version at least `5`.

**Comment by nlewo** [comment]
@dingxiangfei2009 I think you could also have a look at https://github.com/NixOS/nixpkgs/pull/39716.

**Comment by nlewo** [comment]
I close this PR in favor of #49414.
Note we can now rely on Nix2.0 because it is the default since 2 releases.

**Comment by nlewo** [comment]
@dingxiangfei2009 If we consider we have to use Nix 2.0, I don't think these PRs will break any builds. But... maybe you have an example? :/

**Comment by dingxiangfei2009** [comment]
That is what I was thinking. I do not have any statistics on other users of this function, but I do not see any builds being re-triggered by this change according to the CI here.

**Pull request closed without merging**
