### PR TITLE
nixos/redmine: Apply initial hardening using the systemd unit

### PR DESCRIPTION
**Pull request by felixsinger**
These options are a good start for sandboxing the service. It's planned
    to set `ProtectSystem` to `strict` instead of `full`, but that requires
    specific directories to be configured as writable. It's also planned to
    filter system calls. However, that requires more testing but it
    shouldn't prevent us from applying these options for now and add others
    later.

    In my tests, Redmine only bound to an IPv4 address and Unix socket,
    which is why I restricted the address families to these both.

    The command `systemd-analyze security redmine.service` reports an
    overall exposure level of 2.9 with this patch.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by felixsinger** [comment]
@GrahamcOfBorg test redmine

**Comment by felixsinger** [comment]
@GrahamcOfBorg test redmine

**Review by megheaiulian — APPROVED** [review]
:+1:

**Comment by aanderse** [comment]
does this break the various email integrations `redmine` has? etc...

**Comment by felixsinger** [comment]
> does this break the various email integrations `redmine` has? etc...

Which integrations are you referring to? These settings shouldn't break anything. I left out the breaking settings for other PRs.

**Comment by aanderse** [comment]
we have a opinions option which can run scripts, etc....

maybe some of them could break? just asking

**Comment by felixsinger** [comment]
Hmm. Well, we will have to see. Could you mention some of the options you have on your mind? Are these available in upstream nixpkgs? I'm happy to have a look.

**Comment by aanderse** [comment]
no, just a general comment, don't worry

**Pull request merged**
