### PR TITLE
Add vit

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This is **WIP**

This PR adds "VIT" the Visual Interactive Taskwarrior (curses interface to taskwarrior). Unfortunately it has a curses perl module as dependency, so I tried to package this as well, but it fails building.

Maybe some perl guy can have a look? I don't know one, so please feel free to notify one! :smile:

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
I just pushed two fixups. The thing is: the vit install still does not find the `Curses` perl package in the configure phase. Don't know why, though. If someone can provide patches, I'll happily merge them (and do fixup, but give credit to the contributor, of course)!

**Comment by matthiasbeyer** [comment]
I guess something like [this](https://github.com/NixOS/nixpkgs/blob/0761f81da71fc6a940c7f51129b6c7717db78e87/pkgs/servers/ldap/389/perl-path.patch) has to be made, but I'm not sure how to do it for the `configure` fail in the vit package.

**Comment by matthiasbeyer** [comment]
Installation works now, but it does not find the `Curses` package when starting. I tested with `propagatedBuildInputs` as well as the pushed version, doesn't work, still.

Maybe someone can have a look? @jagajaga @rycee (Pinged you two because you are in the log for the `perl-packages.nix` file, so I assume you two are perl people! :smile: )

**Comment by rycee** [comment]
Had a quick look at the expression and did manage to get a bit further:

```perl
{ pkgs, fetchgit, stdenv, makeWrapper, taskwarrior, ncurses
, perl, perlPackages }:

let
  version = "1.2";
in
stdenv.mkDerivation {
  name = "vit-${version}";

  src = fetchgit {
    url = "https://git.tasktools.org/scm/ex/vit.git";
    rev = "7d0042ca30e9d09cfbf9743b3bc72096e4a8fe1e";
    sha256 = "92cad7169b3870145dff02256e547ae270996a314b841d3daed392ac6722827f";
  };

  preConfigure = ''
    substituteInPlace Makefile.in \
      --replace sudo ""
    substituteInPlace configure \
      --replace /usr/bin/perl ${perl}/bin/perl
  '';

  postInstall = ''
    wrapProgram $out/bin/vit --prefix PERL5LIB : $PERL5LIB
  '';

  buildInputs = [ taskwarrior ncurses makeWrapper perlPackages.Curses perl ];

  meta = {
    description = "Visual Interactive Taskwarrior";
    maintainers = with pkgs.lib.maintainers; [ matthiasbeyer ];
    platforms = pkgs.lib.platforms.linux;
    license = pkgs.lib.licenses.gpl3;
  };
}
```

With this I can somewhat run vit:
```
rycee@beta:~/devel/nixpkgs$ ./result/bin/vit -help
usage: vit [switches] [task_args]
  -audit     print task commands to vit_audit.log
  -titlebar  sets the xterm titlebar to "vit-1.2 (20150920)"
  task_args  any set of task commandline args that print an "ID" column
rycee@beta (✗ 1):~/devel/nixpkgs$
```
but when I run without any arguments I only get a black screen.

**Comment by matthiasbeyer** [comment]
@rycee Sounds nice. Do you use taskwarrior? If not, I understand the black screen!

**Comment by rycee** [comment]
I don't use taskwarrior so yeah, might be that ;-)

**Comment by matthiasbeyer** [comment]
@rycee Is this okay for you; I put you in the commit message with a "Suggested-by:" tag, if this is okay for you, this PR is ready for merge (test build and test-started).

**Comment by rycee** [comment]
@matthiasbeyer That sounds fine!

**Comment by matthiasbeyer** [comment]
So we are ready for merge here.

**Comment by jagajaga** [comment]
Please rebase and leave only one commit.

**Comment by matthiasbeyer** [comment]
@jagajaga Oh, did not notice there where two commits. Sorry. Squashed.

**Pull request merged**
