### PR TITLE
spdlog: 1.8.5 -> 1.9.2 

### PR DESCRIPTION
**Pull request by Artturin**
###### Motivation for this change
Supersedes #134609
i need 1.9.2 to package ananicy-cpp

###### Things done
built normal and pkgsStatic

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
Result of `nixpkgs-review pr 145006` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>lizardfs</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>nrfutil</li>
    <li>python38Packages.qiskit</li>
    <li>python38Packages.qiskit-aqua</li>
    <li>python39Packages.qiskit</li>
    <li>python39Packages.qiskit-aqua</li>
  </ul>
</details>
<details>
  <summary>39 packages built:</summary>
  <ul>
    <li>bear</li>
    <li>cherrytree</li>
    <li>far2l</li>
    <li>gerbera</li>
    <li>hal-hardware-analyzer</li>
    <li>kodi (kodiPackages.kodi)</li>
    <li>kodi-gbm</li>
    <li>kodi-wayland</li>
    <li>kodiPackages.a4ksubtitles</li>
    <li>kodiPackages.inputstream-adaptive</li>
    <li>kodiPackages.inputstream-ffmpegdirect</li>
    <li>kodiPackages.inputstream-rtmp</li>
    <li>kodiPackages.joystick</li>
    <li>kodiPackages.kodi-platform</li>
    <li>kodiPackages.libretro</li>
    <li>kodiPackages.libretro-genplus</li>
    <li>kodiPackages.libretro-snes9x</li>
    <li>kodiPackages.netflix</li>
    <li>kodiPackages.pvr-hdhomerun</li>
    <li>kodiPackages.pvr-hts</li>
    <li>kodiPackages.pvr-iptvsimple</li>
    <li>kodiPackages.steam-controller</li>
    <li>kodiPackages.vfs-libarchive</li>
    <li>kodiPackages.vfs-sftp</li>
    <li>mtxclient</li>
    <li>nheko</li>
    <li>openroad</li>
    <li>pc-ble-driver</li>
    <li>python38Packages.pc-ble-driver-py</li>
    <li>python38Packages.qiskit-aer</li>
    <li>python38Packages.qiskit-ibmq-provider</li>
    <li>python38Packages.qiskit-ignis</li>
    <li>python39Packages.pc-ble-driver-py</li>
    <li>python39Packages.qiskit-aer</li>
    <li>python39Packages.qiskit-ibmq-provider</li>
    <li>python39Packages.qiskit-ignis</li>
    <li>spdlog (spdlog_1)</li>
    <li>vowpal-wabbit</li>
    <li>waybar</li>
  </ul>
</details>

**Review by tobim — APPROVED** [review]
I'm fine with this approach. Thanks for pushing this forward!

Maybe we should also retry making `fmt_8` the default.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 145006` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package marked as broken and skipped:
</summary>
<ul>
<li>lizardfs</li>
</ul>
</details>
<details>

  <summary>4 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>python38Packages.qiskit: log was empty</li>
<li>python38Packages.qiskit-aqua: log was empty</li>
<li>python39Packages.qiskit: log was empty</li>
<li>python39Packages.qiskit-aqua: log was empty</li>
  </ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>nrfutil: log was empty</li>
  </ul>
</details>
<details>
<summary>
39 packages built:
</summary>
<ul>
<li>bear</li>
<li>cherrytree</li>
<li>far2l</li>
<li>gerbera</li>
<li>hal-hardware-analyzer</li>
<li>kodi (kodiPackages.kodi)</li>
<li>kodi-gbm</li>
<li>kodi-wayland</li>
<li>kodiPackages.a4ksubtitles</li>
<li>kodiPackages.inputstream-adaptive</li>
<li>kodiPackages.inputstream-ffmpegdirect</li>
<li>kodiPackages.inputstream-rtmp</li>
<li>kodiPackages.joystick</li>
<li>kodiPackages.kodi-platform</li>
<li>kodiPackages.libretro</li>
<li>kodiPackages.libretro-genplus</li>
<li>kodiPackages.libretro-snes9x</li>
<li>kodiPackages.netflix</li>
<li>kodiPackages.pvr-hdhomerun</li>
<li>kodiPackages.pvr-hts</li>
<li>kodiPackages.pvr-iptvsimple</li>
<li>kodiPackages.steam-controller</li>
<li>kodiPackages.vfs-libarchive</li>
<li>kodiPackages.vfs-sftp</li>
<li>mtxclient</li>
<li>nheko</li>
<li>openroad</li>
<li>pc-ble-driver</li>
<li>python38Packages.pc-ble-driver-py</li>
<li>python38Packages.qiskit-aer</li>
<li>python38Packages.qiskit-ibmq-provider</li>
<li>python38Packages.qiskit-ignis</li>
<li>python39Packages.pc-ble-driver-py</li>
<li>python39Packages.qiskit-aer</li>
<li>python39Packages.qiskit-ibmq-provider</li>
<li>python39Packages.qiskit-ignis</li>
<li>spdlog (spdlog_1)</li>
<li>vowpal-wabbit</li>
<li>waybar</li>
</ul>
</details>

**Comment by acowley** [comment]
I would have liked to see the patch borrowed from `vcpkg` that I [described](https://github.com/NixOS/nixpkgs/pull/134609#issuecomment-951931148) in the linked issue. It seems like a usability win.

**Comment by Artturin** [comment]
> I would have liked to see the patch borrowed from `vcpkg` that I [described](https://github.com/NixOS/nixpkgs/pull/134609#issuecomment-951931148) in the linked issue. It seems like a usability win.

Is this line in the apkgbuild related? https://git.alpinelinux.org/aports/tree/community/spdlog/APKBUILD#n34

**Comment by acowley** [comment]
Yes, I think it is addressing the same issue.

**Pull request merged**
