### PR TITLE
 pkgs/tools: switch to fetchFromGitHub part 1

### PR DESCRIPTION
**Pull request by Stunkymonkey**
###### Motivation for this change
use fetchFromGitHub

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 138551` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>openssh_hpn</li>
  </ul>
</details>
<details>
  <summary>3 packages blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
    <li>tests.nixos-functions.nixosTest-test</li>
    <li>tests.trivial</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>tracebox</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>bcache-tools</li>
    <li>dir2opus</li>
    <li>jbig2enc</li>
    <li>ocrmypdf</li>
    <li>paperless-ng</li>
    <li>sipsak</li>
    <li>tcptraceroute</li>
    <li>zbackup</li>
  </ul>
</details>

**Review by davidak — CHANGES_REQUESTED** [review]
Change looks good

One package fails to build

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 138551` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>openssh_hpn</li>
  </ul>
</details>
<details>
  <summary>3 packages blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
    <li>tests.nixos-functions.nixosTest-test</li>
    <li>tests.trivial</li>
  </ul>
</details>
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>bcache-tools</li>
    <li>dir2opus</li>
    <li>jbig2enc</li>
    <li>ocrmypdf (python39Packages.ocrmypdf)</li>
    <li>paperless-ng</li>
    <li>python38Packages.ocrmypdf</li>
    <li>sipsak</li>
    <li>tcptraceroute</li>
    <li>zbackup</li>
  </ul>
</details>

**Review by davidak — APPROVED** [review]
Change looks good

Builds, runs

ocrmypdf fails to run, but it does not even build on unstable, so this is an improvement

Thanks for doing this cleanup work!

**Pull request merged**
