### PR TITLE
apple-sdk: propagate the `libutil` library

### PR DESCRIPTION
**Pull request by emilazy**
The SDK provides this without headers and apparently some things try to link to it. This should help increase compatibility with the native toolchain.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by reckenrode** [comment]
This seems fine. A good test would be to build Python with `darwin-libutil.patch` disabled and Neovim with https://github.com/NixOS/nixpkgs/pull/346946 reverted.

**Comment by emilazy** [comment]
MacVim, CPython 3.10, and CPython 3.12 build successfully. Now building the other CPythons and the other packages I’ve touched here. I looked at the source for all of them except MacVim and determined that they expected `<util.h>`, not `<libutil.h>`, as expected for packages supporting Darwin or BSD upstream. I have not tested MacVim as it requires Xcode; cc @lilyball.

There are no packages left referencing `darwin.libutil` except the SDK; maybe it should not really be installing `libutil.h` at all, since apparently nothing wants it on macOS.

**Comment by emilazy** [comment]
I have confirmed that everything touched here builds (except `macvim` as stated previously, but I’m pretty sure it’s not likely to be the one package in the whole tree that actually needs this, especially given that it has since had changes to depend *less* on Nix stuff).

@reckenrode There are now no users of `darwin.libutil` that don’t use `lib.getLib`, because everything uses `<util.h>` on macOS and various BSDs. Are we sure we want to install the `<libutil.h>` header in that package at all? In any case, the only explicit user outside of the SDK is now `libuv`, which has to build with the bootstrap SDK. Let me know if you think I’ve handled it appropriately there or if there’s something nicer we could do.

**Comment by reckenrode** [comment]
`libutil.h` is used by several source releases (e.g., file_cmds, shell_cmds, system_cmds, etc).

**Review by reckenrode — APPROVED** [review]
lgtm

**Comment by emilazy** [comment]
Ah, I didn’t think of the source release scope!

**Pull request merged**
