### PR TITLE
sublime4: 4169 -> 4180, sublime4-dev: 4175 -> 4178

### LINKED ISSUE #342005: Update request: sublime4 4169 → 4180
- Package name: sublime4
- Latest released version: 4180
- Current version on the unstable channel: 4169
- Current version on the stable/release channel: 4169

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@jtojnar
@wmertens
@demin-dmitriy
@zimbatm

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Frontear**
## Description of changes

Closes #342005

Latest versions determined from https://sublimetext.com. Weirdly the dev version is behind the mainline release, but it was the latest version that they had here (https://www.sublimetext.com/dev) at the time of PRing.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by istudyatuni** [comment]
Tried on 75594987c955031e014a9b04bb0997f16bf5b6c5 with
```sh
export NIXPKGS_ALLOW_UNFREE=1
export NIXPKGS_ALLOW_INSECURE=1
nix run github:NixOS/nixpkgs/75594987c955031e014a9b04bb0997f16bf5b6c5#sublime4 --impure
```
got
```
error: unable to execute '/nix/store/8wgpjmwd4sp3a0k4ypkgh248cr6hv4nv-sublimetext4-4180/bin/sublimetext4': No such file or directory
```
I first thought that binary has been renamed
```sh
$ eza -l /nix/store/8wgpjmwd4sp3a0k4ypkgh248cr6hv4nv-sublimetext4-4180/bin
lrwxrwxrwx   - root  1 Jan  1970 subl -> sublime_text
lrwxrwxrwx   - root  1 Jan  1970 sublime -> sublime_text
lrwxrwxrwx   - root  1 Jan  1970 sublime4 -> sublime_text
.r-xr-xr-x 164 root  1 Jan  1970 sublime_text
```
but on current version /bin has the same files. Probably I should specify binary in `nix run`, but I don't know how

**Comment by istudyatuni** [comment]
It works when using `nix shell` instead of `nix run` and calling `subl` inside of it

**Comment by jtojnar** [comment]
> Latest versions determined from [sublimetext.com](https://sublimetext.com). Weirdly the dev version is behind the mainline release, but it was the latest version that they had here ([sublimetext.com/dev](https://www.sublimetext.com/dev)) at the time of PRing.

That is normal. both branches use the same counter and stable is released after dev is confirmed to work.

> but on current version /bin has the same files. Probably I should specify binary in `nix run`, but I don't know how

That’s what `meta.mainProgram` is for.

**Review by jtojnar — CHANGES_REQUESTED** [review]
Opening a text file in Nautilus no longer opens Sublime Text with 4178 on GNOME Shell X server session. The following is logged in the journal:

```
sublime_text.desktop[819681]: Failed to receive exit code from application
```

Downgrading makes it able to open again.

**Edit:** I get the same when running it from terminal, do not even have to specify path – as long as a Sublime Text is running:

```
$ subl
Failed to receive exit code from application
```

**Edit:** Looks like the issue might have been caused by Nautilus trying to launch the globally installed Sublime. If I run `result/bin/subl` it works okay.

**Comment by istudyatuni** [comment]
It seems that this is because the app already opened, but a different version https://github.com/sublimehq/sublime_text/issues/6455

**Review by jtojnar — APPROVED** [review]
After installing it globally, it works. It will be a bit annoying for people who switch without restarting it, since it appears to be an issue both ways (new system-wide plus old running, and vice versa) but not much we can do about that.

**Pull request merged**
