### PR TITLE
masscan: add patch to fix resume functionality

### LINKED ISSUE #559: --resume fails with an unknown config option error
Currently I'm able to reproduce it on Linux and OS X with the latest master ([3ad77be62](https://github.com/robertdavidgraham/masscan/commit/3ad77be62180d846e127787d1f7d62174c3a5970)).

1. Start masscan and interrupt it to save the paused.conf:

```
# timeout -s INT 1 masscan -p12345 --rate 1 192.168.1.0/24 --wait 0
...
saving resume file to: paused.conf
```

2. Resume the paused scan:

```
# masscan --resume paused.conf
CONF: unknown config option: nocapture=servername
```

The created `paused.conf` file looks like that:
    
    # resume information
    resume-index = 1
    seed = 5391402425458307641
    rate = 1
    shard = 1/1
    nocapture = servername

I fixed it myself by adding a dummy condition in `src/main-conf.c` ([line ~2371](https://github.com/robertdavidgraham/masscan/blob/master/src/main-conf.c#L2369-L2373)):

    } else if (EQUALS("nocapture", name)) {
        // FIXME: do nothing
    } else {
        fprintf(stderr, "CONF: unknown config option: %s=%s\n", name, value);
        exit(1); 
    }

I spent some time digging into the project with no success, so I finally decided to post here. I don't feel confident about the fix I made, thus I created this issue and not a pull request. Sorry about that!

### PR DESCRIPTION
**Pull request by rwf93**
###### Description of changes

Updated masscan from v1.3.2 on the releases to 144c527ed55275ee9fbb80bb14fbb5e3fcff3b7e (latest as of 6/3/2023) to fix [--resume from breaking (robertdavidgraham/masscan#559)](https://github.com/robertdavidgraham/masscan/issues/559)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rwf93** [comment]
cant seem to fix check 3 cause im big dumb
oh well
:trollface:

**Comment by rnhmjoj** [comment]
In this case you should backport only the fix [commit](https://github.com/robertdavidgraham/masscan/commit/90791550bbdfac8905917a109ed74024161f14b3.patch) commit using `fetchpatch`. See 9ace1d895c246d5a6fa9a405897d40f64b5167cd for example.

**Comment by rwf93** [comment]
Thank you so much! Will get on it!

**Review by rnhmjoj — APPROVED** [review]
Thank you! I built masscan and `--resumed` is now working again.

**Comment by fabaff** [comment]
This PR contains more commits than needed and all of them do not follow the current requirements for a proper commit message (see [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md)).

**Comment by rnhmjoj** [comment]
@fabaff Right, but I did squash them using Github's interface.

**Comment by rwf93** [comment]
Yeah, my bad. I rarely commit to projects, and so I am quite noobish. This PR was also quite on a whim. Thank you!

**Pull request merged**
