### PR TITLE
filet: 0.1.1 -> 0.1.2

### PR DESCRIPTION
**Pull request by buffet**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build filet

**Review by xeji — CHANGES_REQUESTED** [review]
Please either fix the build on darwin or restrict platforms to `platforms.linux`.

**Comment by buffet** [comment]
> Please either fix the build on darwin or restrict platforms to `platforms.linux`.

"Fixed". I just checked and #56938 is also broken, but has been merged.

**Comment by xeji** [comment]
Thanks.

> ... #56938 is also broken, but has been merged.

Well, we sometimes miss things :smile: 

Let's try again
@GrahamcOfBorg build filet

**Comment by xeji** [comment]
Still tries and fails to build on Darwin, unfortunately.

**Comment by buffet** [comment]
Sorry, that was on me *again*. **NOW** it's set to linux. Tripple checked.

**Comment by xeji** [comment]
@GrahamcOfBorg build filet

**Comment by xeji** [comment]
Thanks, looks good now.

**Comment by buffet** [comment]
Sorry for the inconviniences.

**Review by xeji — APPROVED** [review]

**Pull request merged**
