### PR TITLE
esy: init at 0.6.2 WIP

### PR DESCRIPTION
**Pull request by NickHu**
###### Motivation for this change

A work-in-progress packaging of the [esy](esy.sh) package manager, by building on #65098 and https://github.com/esy/esy/pull/994.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

# Issues to be solved

While the binary seems to work fine, there are some issues. The largest of which is that `esy` doesn't seem able to compile `ocaml` (under NixOS), which I think will be resolved when https://github.com/esy-ocaml/ocaml/commit/1667562d3f6e8ff8d5703b206b43f7a083d6770d hits the npm package registry (I tried *really* hard to just use local version of `esy-ocaml/ocaml`, switching to the latest `4.8.1000+esy` branch, and editing the `package.json` of [what I was trying to compile](https://github.com/esy-ocaml/hello-reason/), but this just made the dependency resolver scream at me - I think it's very broken). As a result, I was unable to get this build of `esy` to build a single package (as it first needs to bootstrap the `ocaml` compiler), suggesting that more work is needed.

`esy` version 0.6.4 is out, but using this version causes complaints about `esy.lock` being corrupt on everything I tried - initially, I thought this was just that the format of `esy.lock` changed in a non-compatible way, but strangely when I tried version 0.6.4 on Arch Linux (by updating the PKGBUILD on the AUR) and it had no such issue. Fortunately, 0.6.2 doesn't seem to invalidate existing `esy.lock` directories. I wasn't able to package 0.6.3 easily because its `package.json` doesn't seem to be on the npm registry.

It might also be necessary to get some binaries (`gnum4`, `coreutils`, etc.) into the `PATH` used by `esy` when it builds too, but adding this to `buildInputs`/`propagateBuildInputs` doesn't seem to work (though strangely when I ran `esy` inside `nix-shell -p gnum4` it was somehow able to find `m4`).

cc @Zimmi48 @kamilchm @anmonteiro

### CODE REVIEW

**Comment by xavierzwirtz** [comment]
I tried [setting this up in an fhs user env](https://github.com/xavierzwirtz/nixpkgs/tree/esy), looks like it got esy-ocaml compiling. Its getting farther along, but failing due to dune's build trying to call out to ocaml. Feels like something is preventing the built esy-ocaml from getting put on the path.

```
info esy 0.6.6 (using package.json)
info building @opam/ocamlbuild@opam:0.14.0@6ac75d03
info building @opam/jbuilder@opam:1.0+beta20.2@053ddcf2
info building @opam/ocamlfind@opam:1.8.1@ff07b0f9
info building @opam/dune@opam:2.1.3@8a848ab8
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @opam/dune@opam:2.1.3
    # esy-build-package: pwd: /home/xavier/.esy/3/b/opam__s__dune-opam__c__2.1.3-50f7540b
    # esy-build-package: running: 'ocaml' 'bootstrap.ml' '-j' '4'
    esy-build-package: unable to resolve command: ocaml

  building @opam/dune@opam:2.1.3
esy: exiting due to errors above
```

**Comment by xavierzwirtz** [comment]
With the latest changes in https://github.com/xavierzwirtz/nixpkgs/tree/esy I am able to compile and run hello-reason and esy with this derivation. I had to remove https://github.com/esy/esy/pull/988 from the derivation, it was causing the path in the esy sandbox to not include any of the paths esy injects.

**Comment by lobre** [comment]
@xavierzwirtz, does it mean this PR gets closer to not being a draft anymore?

**Comment by SuperSandro2000** [comment]
Closing due to inactivity from author.

**Pull request closed without merging**
