### PR TITLE
sqlite-replication: drop

### PR DESCRIPTION
**Pull request by winterqt**
###### Description of changes

Dqlite and LXD haven't required this custom SQLite version since 2020 (it was last updated in 2019), and its GitHub repo no longer exists.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by winterqt** [comment]
Not sure if I should even bother adding a `throw` alias here, given the circumstsnces. @risicle thoughts?

**Comment by risicle** [comment]
I'd do it anyway. Easy enough to do, sticks to policy...

**Comment by thiagokokada** [comment]
> Not sure if I should even bother adding a `throw` alias here, given the circumstsnces. @risicle thoughts?

Would also prefer to adding a `throw` here.

**Comment by mkg20001** [comment]
@ofborg test lxd

**Comment by winterqt** [comment]
@mkg20001 Why force push this just to add a new commit? (If you amended the previous commit -- which was the better choice, IMO -- I'd understand, but you added a new commit to add the throw...)

**Comment by mkg20001** [comment]
@winterqt I rebased to run the test against latest lxd

**Comment by winterqt** [comment]
@mkg20001 OfBorg automatically merges master into the branch when running tests, for future reference.

**Comment by winterqt** [comment]
Additionally, in the future, I (and most likely others) would prefer that you ask before doing something like that -- only 2 days passed since I made the PR. Thanks :)

**Pull request merged**
