### PR TITLE
libtinfo: init at 6.4

### PR DESCRIPTION
**Pull request by doronbehar**
###### Motivation for this change

Continuing the discussion from https://github.com/NixOS/nixpkgs/pull/279844 . I think some users might need this build of ncurses - with the `postFixup` hook turned off, and with `termlib` support turned on. `tests.buildFHSEnv.libtinfo` is cleaner with this change.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
On a 2nd thought, there is no reason why this should be a draft.

**Comment by NorfairKing** [comment]
@doronbehar I have to admit that I don't really know what `libtinfo` really is.
I'm probably not the right reviewer for this, but I'm still interested in learning.
Do you have any links for me?

**Comment by doronbehar** [comment]
`libtinfo` is a library certain build of `ncurses` that is distributed by other many distributions. See for example Debian's:

https://packages.debian.org/search?suite=sid&searchon=names&keywords=libtinfo

I encountered the need for this library in https://github.com/NixOS/nixpkgs/pull/279844 that managed to reproduce an `buildFHSEnv` that couldn't get a Nix replacement for a `libtinfo` package.

I asked for your review because this has been sitting here for a while, and you also touched a bit the Nix arguments of this package.

**Comment by NorfairKing** [comment]
@doronbehar I don't see anything disagreeable, but I don't see where the `package.nix` is used.
I also don't know if the default should be `false`.

I also don't have commit rights :shrug:

**Comment by doronbehar** [comment]
> I don't see where the `package.nix` is used.

See https://github.com/NixOS/nixpkgs/tree/master/pkgs/by-name#name-based-package-directories 

> I also don't know if the default should be `false`.

That's in order not to trigger too many rebuilds for a feature no body really misses.

> I also don't have commit rights 🤷

Yes but still your approval could have gave me confidence to self merge. If you don't feel comfortable, that's OK, I'll find someone else :).

**Comment by NorfairKing** [comment]
> > I don't see where the `package.nix` is used.
> 
> See https://github.com/NixOS/nixpkgs/tree/master/pkgs/by-name#name-based-package-directories

Cool!
That seems new :)

> > I also don't know if the default should be `false`.
> 
> That's in order not to trigger too many rebuilds for a feature no body really misses.

Fair enough.

> > I also don't have commit rights 🤷
> 
> Yes but still your approval could have gave me confidence to self merge. If you don't feel comfortable, that's OK, I'll find someone else :).

Yeah I definitely don't feel comfortable :)

**Comment by doronbehar** [comment]
Closed by mistake...

**Pull request merged**
