### PR TITLE
[Backport release-22.11] kernel updates

### PR DESCRIPTION
**Pull request by vcunat**
###### Description of changes
Picked https://github.com/NixOS/nixpkgs/pull/209050 except for `linux_testing`, as our config can't handle 6.2 even on nixpkgs master yet.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
Built on x86_64-linux (will edit): `linux_6_0`

**Comment by vcunat** [comment]
Hehe
```
nix-repl> linux_testing_hardened
error: linux_testing_hardened has been removed, please use linux_latest_hardened

nix-repl> linux_latest_hardened
error: The attribute `linuxPackages_hardened_latest' was dropped because [...]
```
Well, if hardened 6.0 exists there, perhaps it's not so important to test it?

**Comment by Ma27** [comment]
Thx for taking care of that! Skiing this week, so I haven't found the time, next week I'm happy to do kernel updates again :)

**Comment by SuperSandro2000** [comment]
I am not fully sure how https://utcc.utoronto.ca/~cks/space/blog/linux/KernelBindBugIn6016 relates into this update for us

**Comment by vcunat** [comment]
The article writes it's present in 6.0.16 and 6.0.18.  From that I expect that this 6.0 bump won't change it.

**Comment by vcunat** [comment]
I suspect it's bad for 6.0, as 6.0.19 was already released as EOL, and based on recency of some posts (and a glance into changelog) I don't expect it's fixed in there.

I think I recently saw some test regression on Hydra that mentioned expecting and not getting EADDRINUSE.

**Comment by SuperSandro2000** [comment]
The 6.0 bug was introduced in 6.0.16 and has no fix so far because it is EOL.

**Comment by Ma27** [comment]
Yeah we shod drop 6.0 anyways.

**Comment by vcunat** [comment]
That makes me sad, as connected ethernet immediately wakes up suspend for me on other kernels that I've tried so far.

**Pull request merged**
