### PR TITLE
archivebox: use hash instead of sha256

### PR DESCRIPTION
**Pull request by Lassulus**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
```
error: builder for '/nix/store/jrp96x8mpjphn4wrhidv2d98zy2ln4jq-python3.10-django-extensions-3.2.0.drv' failed with exit code 1;
       last 10 log lines:
       > removing build/bdist.linux-x86_64/wheel
       > Finished executing setuptoolsBuildPhase
       > installing
       > Executing pipInstallPhase
       > /build/source/dist /build/source
       > Processing ./django_extensions-3.2.0-py3-none-any.whl
       > ERROR: Could not find a version that satisfies the requirement Django>=3.2 (from django-extensions) (from versions: none)
       > ERROR: No matching distribution found for Django>=3.2
       >
       > builder for '/nix/store/jrp96x8mpjphn4wrhidv2d98zy2ln4jq-python3.10-django-extensions-3.2.0.drv' failed with exit code 1
       For full logs, run 'nix log /nix/store/jrp96x8mpjphn4wrhidv2d98zy2ln4jq-python3.10-django-extensions-3.2.0.drv'.
error: 1 dependencies of derivation '/nix/store/k5f62hs8fgy2c4sb44a60pxa43d285ar-archivebox-0.6.2.drv' failed to build
```

**Comment by Mindavi** [comment]
Heh, yeah that only works if the original builder also uses `hash`

**Comment by mweinelt** [comment]
Django uses hash since the 3.2.15 upgrade, so this change is warranted.

**Comment by Lassulus** [comment]
> ```
> error: builder for '/nix/store/jrp96x8mpjphn4wrhidv2d98zy2ln4jq-python3.10-django-extensions-3.2.0.drv' failed with exit code 1;
>        last 10 log lines:
>        > removing build/bdist.linux-x86_64/wheel
>        > Finished executing setuptoolsBuildPhase
>        > installing
>        > Executing pipInstallPhase
>        > /build/source/dist /build/source
>        > Processing ./django_extensions-3.2.0-py3-none-any.whl
>        > ERROR: Could not find a version that satisfies the requirement Django>=3.2 (from django-extensions) (from versions: none)
>        > ERROR: No matching distribution found for Django>=3.2
>        >
>        > builder for '/nix/store/jrp96x8mpjphn4wrhidv2d98zy2ln4jq-python3.10-django-extensions-3.2.0.drv' failed with exit code 1
>        For full logs, run 'nix log /nix/store/jrp96x8mpjphn4wrhidv2d98zy2ln4jq-python3.10-django-extensions-3.2.0.drv'.
> error: 1 dependencies of derivation '/nix/store/k5f62hs8fgy2c4sb44a60pxa43d285ar-archivebox-0.6.2.drv' failed to build
> ```
This seems like another issue, but we don't have it on 22.05. So I would merge this first and  backport and maybe investigate later into this new issue

**Pull request merged**
