### PR TITLE
file: disable tests on musl

### PR DESCRIPTION
**Pull request by alyssais**
###### Description of changes

Regressed in https://github.com/NixOS/nixpkgs/pull/191228.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
> Fixes: https://github.com/NixOS/nixpkgs/commit/4c510f32feb018050c85868b176cac91a5363d65 ("file: 5.42 -> 5.43")

Commit message is a bit ambiguous. The link in the code to be upstream issue is sufficient, commit message probably isn't needed, could just drop it via squash merge.

**Comment by alyssais** [comment]
The "Fixes" tag is a useful convention for identifying fixes for regressions — if you notice that a certain commit has broken your build, you can look for later commits that are marked as "Fixes: <that commit>", and find when the problem has already been solved by a more recent revision.  In Linux, for example, Fixes tags are used to identify candidate commits for backporting. It certainly doesn't hurt anybody to include it, so I'd like to leave it.

**Comment by alyssais** [comment]
@OfBorg build pkgsStatic.file pkgsMusl.file

**Comment by zowoq** [comment]
> The "Fixes" tag is a useful convention for identifying fixes for regressions

> It certainly doesn't hurt anybody to include it

Can't say I agree with either of these points but feel free to merge this as is.

**Comment by alyssais** [comment]
Thanks!

**Pull request merged**
