### PR TITLE
kicad: 6.0.11 -> 7.0.0

### PR DESCRIPTION
**Pull request by evils**
###### Description of changes

https://www.kicad.org/blog/2023/02/Version-7.0.0-Released/

this change depends on #215971
(at least on my sway setup, without it KiCad crashes when trying to open the file picker)

it also includes a kicad-unstable update, as this avoids some feature flagging in the package

the `withPCM` option was removed, i'd be surprised if anyone ever touched that, so i didn't bother with a warning

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by evils** [comment]
shot myself in the foot with #216182
KiCad's build fails to recognize a 4 section long version number for wxwidgets
there's a fix on their master branch already, i'll add the patches to this tomorrow

**Comment by evils** [comment]
separate commit for the patches as i expect to revert this at the next stable point release

**Comment by hesiod** [comment]
Result of `nixpkgs-review pr 215985` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>kicad-small</li>
    <li>kicad-unstable-small</li>
    <li>python310Packages.kicad</li>
    <li>python311Packages.kicad</li>
  </ul>
</details>

**Review by hesiod — APPROVED** [review]
Tested built KiCad executables (from the `kicad-small` and `kicad-unstable-small`) by opening a nontrivial project. Eeschema and Pcbnew (including 3D Viewer) seem to work fine.

**Comment by evils** [comment]
last force push was an update to the last commit of the day for `kicad-unstable`

**Comment by julian1** [comment]
Good work!.

For those who don't want to, and cannot upgrade just yet - is there a way to stay at 6.0.11 version?
git revert doesn't appear to recognize the commit.

[code]

$ git remote -v
origin  git@github.com:NixOS/nixpkgs (fetch)
origin  git@github.com:NixOS/nixpkgs (push)

$ git log | head
[...]
Date:   Sat Apr 15 11:30:56 2023 +0800


$ git revert 9a9546ed3cc25f922
fatal: bad revision '9a9546ed3cc25f922'

[/code]

**Comment by julian1** [comment]
Good work!.

For those who prefer to wait, or are required not to upgrade just yet - is there a way to stay at 6.0.11 version?
git revert doesn't appear to recognize the commit.
 
    $ git remote -v
    origin  git@github.com:NixOS/nixpkgs (fetch)
    origin  git@github.com:NixOS/nixpkgs (push)

    $ git log | head
    [...]
    Date:   Sat Apr 15 11:30:56 2023 +0800

    $ git revert 9a9546ed3cc25f922
    fatal: bad revision '9a9546ed3cc25f922'

**Comment by julian1** [comment]
I've wound it back to the commit before this one,


me@:~/devel/nixpkgs02/pkgs/applications/science/electronics/kicad$ git co  c8d22b3c2a8~1 .

me@:~/devel/nixpkgs02/pkgs/applications/science/electronics/kicad$ git s 
M  base.nix
M  default.niX
M  versions.nix


But it looks like the patch for the wxWidgets to handle the new versioning info is needed, so added it back to base.nix,
But then patch just fails.
```
applying patch /nix/store/r9saygx8s3jz504qbb8142wf5i1x78kf-support-wxWidgets-subrelease-field
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- a/cmake/FindwxWidgets.cmake
|+++ b/cmake/FindwxWidgets.cmake
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored
error: builder for '/nix/store/q0fmvc5ssy19f2b3axhimlm5c3cga4hp-kicad-base-6.0.11.drv' failed with exit code 1;
```

**Comment by evils** [comment]
i hadn't considered the desire to use the old release

i recommend using the nixos-22.11 channel if you want KiCad 6

apparently i didn't backport the 6.0.11 update to the nixos-22.11 channel
so that'll get you 6.0.9, but the 6.0.11 update could be backported to that channel

**Comment by julian1** [comment]
Thanks for maintaining Kicad!

I've got 6.0.11 running ok. But had to revert https://github.com/NixOS/nixpkgs/pull/216182/commits/4ec05165a3afb988fc82aadd017fd2539e96e1a4 also, since I couldn't get the Kicad patch https://github.com/NixOS/nixpkgs/pull/215985/commits/6fdb83a15f3014a17d68dcde9a70f2bf0ca5d2c5 to accept wxwidgets 3.2.2.1 to work for v6. 

The ability to run both versions side-by-side would be ideal for my own needs. 
If I fiddle with it some more, I'll try to extract kicad6 as a separate package.

**Pull request merged**
