### PR TITLE
Set aspell's data-dir through ASPELL_CONF in a wrapper

### PR DESCRIPTION
**Pull request by lpenz**
This makes aspell find the dictionaries in the
user directory, and is essentially what the
documentation suggested.

See NixOS/nixpkgs#1000

###### Motivation for this change

NixOS/nixpkgs#1000

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bjornfor** [comment]
This only allows installing dicts with nix-env :-/  I have them in configuration.nix, so that will break for me. Is there no other way to fix this for non-NixOS users?

Has anyone looked into making aspell take a list of dict-dirs?

**Comment by lpenz** [comment]
How about an option to set ASPELL_CONF only if it's not set?
(in no way implying that I would know how to do that...)

**Comment by bjornfor** [comment]
> How about an option to set ASPELL_CONF only if it's not set?

Sounds good to me.

**Comment by lpenz** [comment]
Done!

**Comment by bjornfor** [comment]
If you want to change makeWrapper I think it should be in a separate commit. Perhaps even separate PR, for visibility. It's a mass rebuild so it'd have to go via the staging branch.

I don't think the need for a --default option in makeWrapper has come up before, so the question is whether this is something we generally need. Do you think there will be other users than "aspell"?

Since you're adding a wrapper... how about writing a custom wrapper for aspell which iterates over $NIX_PROFILES and sets $ASPELL_CONF accordingly (like NixOS does)? Benefits: works no matter how aspell was installed and we can get rid of the ASPELL_CONF logic in NixOS.

Hmm, I see $NIX_PROFILES isn't set in my Ubuntu+Nix. Is it set on macOS? One could hardcode the profile paths in the wrapper until the profile scripts on all platforms set $NIX_PROFILES.

**Comment by lpenz** [comment]
Sounds better! I will try that.

**Comment by lpenz** [comment]
I'm not very confident that this Is this what you mean. If it is not, could you direct me to an example?

**Comment by bjornfor** [comment]
Yes, that's what I had in mind :-)

Did you test it?

Please prefix commit message with "aspell:".

**Comment by lpenz** [comment]
Cool!
Commit message updated.
I tested it with nix-env and inside the nixos/nix docker image that os docker hub - although I think they have the same behaviour - i.e. no $NIX_PROFILES

**Review by bjornfor — APPROVED** [review]

**Comment by bennofs** [comment]
Looks good to me.

**Pull request merged**
