### PR TITLE
virtualbox: 6.1.6 -> 6.1.10

### PR DESCRIPTION
**Pull request by nthorne**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nthorne** [comment]
supersedes pull request #88172

**Review by B4dM4n — APPROVED** [review]
Looks good.

Build succeeds including kernel 5.7 and VMs are running fine.

**Comment by nthorne** [comment]
.. is there someone that needs to be pinged, or something else that needs to be done for this one to be merged??

**Comment by gloaming** [comment]
It builds and VMs run, things seem fine. I did experience a crash while stopping one VM but that might be down to not rebooting after installing, or just chance. LGTM

cc @ambrop72 @flokli @aszlig

**Comment by nthorne** [comment]
@gloaming i've been running my work VM for a while now using this derivation, and as far as I've been able to tell, there's no regression (auto scaling is as crappy as in any version beyond 6.1.2, though, but there's no obvious regression compared to previous version at least).

**Comment by flokli** [comment]
@blitz just wanted to check back on https://github.com/NixOS/nixpkgs/pull/85772#issuecomment-617769606… were you able to take a look at the tests?

**Comment by charvp** [comment]
6.1.12 was released yesterday.

**Comment by blitz** [comment]
@flokli No luck with the tests yet. I'll take some time tomorrow to look into that again. That would simplify testing a lot...

**Review by blitz — APPROVED** [review]
I've manually tested:

- Windows 10
- NixOS Plasma LiveCD

Looks great!

**Comment by flokli** [comment]
Alright, merged this in - let's leave 6.1.12 and the tests to (a) separate PR(s).

**Pull request merged**
