### PR TITLE
firefox: increase silent timeout to 14400s (4h)

### LINKED ISSUE #129115: firefox-unwrapped times out on Hydra for aarch64-linux
**Describe the bug**
See https://hydra.nixos.org/job/nixpkgs/trunk/firefox-unwrapped.aarch64-linux and https://hydra.nixos.org/build/146893853

**Expected behavior**
Optimally it would be built by Hydra since it would take ages for most aarch64-linux users to build.

**Notify maintainers**
@edolstra @lovesegfault @mweinelt 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change
Fixes: #129115
Replaces: #129212

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Atemu — APPROVED** [review]

**Review by vcunat — APPROVED** [review]
I've noticed this [long-term](https://hydra.nixos.org/job/nixpkgs/trunk/firefoxPackages.firefox.aarch64-linux/all) problem before.  This PR is cheap, so why not try it, but I'm not sure it will really help. (I can't quickly confirm that the attribute will even get picked up, but that's not what I meant.)

The problem always seems to happen during the step when libxul is being linked; IIRC that part consumes lots of memory, so I suspect the cause might be memory pressure.  I mean, two hours to perform the linking should be orders of magnitude more than necessary unless something is very wrong there.

**Review by Artturin — APPROVED** [review]

**Comment by L-as** [comment]
Maybe this should be merged?  It's still a problem.

**Comment by Artturin** [comment]
@ofborg eval

**Comment by Artturin** [comment]
ofborg meta eval fails with
```
evaluation aborted with the following error message: 'Failed to evaluate firefox-unwrapped-89.0.2: «unknown-meta»: has an invalid meta attrset:
         - key 'maxSilent' is unrecognized; expected one of: 
        ['available', 'badPlatforms', 'branch', 'broken', 'changelog', 'description', 'downloadPage', 'downloadURLRegexp', 'executables', 'homepage', 'hydraPlatforms', 'insecure', 'isBuildPythonPackage', 'isFcitxEngine', 'isGutenprint', 'isIbusEngine', 'knownVulnerabilities', 'license', 'longDescription', 'mainProgram', 'maintainers', 'name', 'outputsToInstall', 'platforms', 'position', 'priority', 'repositories', 'schedulingPriority', 'tag', 'tests', 'timeout', 'unfree', 'unsupported', 'updateWalker', 'version']'
 ```

**Comment by lovesegfault** [comment]
Yeah, I don't know what the setting is actually supposed to be called and don't have bandwidth right now to chase after this.

Someone should take over this PR.

**Comment by Artturin** [comment]
its a thing in hydra
https://github.com/NixOS/hydra/blob/429be3ed44e2ddc517d9eb8fb77245751c39e34d/src/hydra-eval-jobs/hydra-eval-jobs.cc#L172

but it hasn't been added here https://github.com/NixOS/nixpkgs/blob/44caf8f371dfbe062c96e3659c77c325365861ee/pkgs/stdenv/generic/check-meta.nix#L203

**Comment by Artturin** [comment]
#132945

**Comment by Artturin** [comment]
@ofborg eval

**Pull request merged**
