### PR TITLE
nodePackages.orval: init at 6.9.6

### PR DESCRIPTION
**Pull request by hsjobeki**
###### Description of changes

Add [orval](https://github.com/anymaniax/orval) and rebuild node-packages.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by winterqt** [comment]
@ofborg build nodePackages.orval

**Comment by winterqt** [comment]
@tfc Please consider squashing and merging for PRs like this in the future, there's no point in having commits like 8ba9b8bed612b9624d0cc03b532a879aebc2b7ce and f46c9675a40e2d75bfbdee458a73f38f855d8c3d in master. Thanks!

**Comment by hsjobeki** [comment]
# Known problems with nix:

- Orval generates different outputs as it is a little impure. (6.9.x)
   - e.g failed to import @tanstack/react-query 

Just a brief comment to all users, that want to use the (orval) generator within a seperate build step for your node projects. 
Orval in the current version (6.9.x) does search for your package.json and if it does not find anything, because you are in a different build-step in your isolated nix-builds it makes predictions about your project. If you cannot use the generated code you must either manually harmonize the dependencies of orval and your project, or (recommended) include the package.json of the project you want to generate your client for. [example see here](https://orval.dev/reference/configuration/output#packagejson)

[#anymaniax/orval/issues/558](https://github.com/anymaniax/orval/issues/558)

**Comment by dotlambda** [comment]
> @tfc Please consider squashing and merging for PRs like this in the future, there's no point in having commits like [8ba9b8b](https://github.com/NixOS/nixpkgs/commit/8ba9b8bed612b9624d0cc03b532a879aebc2b7ce) and [f46c967](https://github.com/NixOS/nixpkgs/commit/f46c9675a40e2d75bfbdee458a73f38f855d8c3d) in master. Thanks!

Why did nobody acknowledge this? It totally breaks `git blame`.

**Comment by winterqt** [comment]
@dotlambda The only acknowledgement I got was a +1 reaction from the committer who merged it. I assume they've been more careful since :/

**Pull request merged**
