### PR TITLE
treewide: remove unused {lib,}clang from more build closures

### PR DESCRIPTION
**Pull request by sodiboo**
follow-up to #360711, which seemed to miss oddly many of these? there were like 3x as many as that PR would suggest

```sh
rg -C 3 'bindgenHook|clang' $(rg -l 'bindgenHook' $(rg -l 'clang' --sort=path) --sort=path) --sort=path
```

`ripasso-cursive`, `zed-editor` and `mchprs` are simple Rust packages with the exact same change as the previous PR

the above query also gives a couple more packagese: `stratovirt`, `solana-validator`, `materialize`, and `tplay` all have `buildInputs = [ libclang ];`, which also seemed unnecessary.

i didn't test these packages' functionality, but they *build* just fine. all except `materialize` that is, which took long enough that i just gave up. usually, the crates that are dependent on `clang` would be earlier on in the dependency graph. hope someone else can build and verify this package still workse.

the query would suggest `tplay` and `gyroflow` should have the same `clang`-removal surgery. this is not the case, since they depend on `opencv` which [requires `clang` as a binary](https://github.com/twistedfall/opencv-rust/blob/7b97b9f988e93545f528ec7f2945de93d5dbac6c/binding-generator/src/generator.rs#L364).

`parinfer-rust` also looks like it should get the same treatment, but it doesn't like that either. this is the error i get

>  ```
>  ./include/emacs-module.h:23:10: fatal error: 'stdint.h' file not found
>  ./include/emacs-module.h:23:10: fatal error: 'stdint.h' file not found, err: true
>  thread 'main' panicked at /build/parinfer-rust-0.4.3-vendor.tar.gz/emacs_module/build.rs:12:10:
>  called `Result::unwrap()` on an `Err` value: ()
>  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
>  ```

and besides those three, i don't think there are any other packages covered by this?

## Things done

- Built on platform(s)
  - [X] x86_64-linux (6/7)
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by niklaskorz — APPROVED** [review]
Tested successfully zed-editor on aarch64-darwin. Would be curious to know what failure @GaetanLepage is experiencing.

**Comment by sodiboo** [comment]
cc @Aleksanaa cause this PR was modeled after hers. I wanted to do "request review" but I seem to be unable to do that actually, thus this comment with the ping

**Comment by GaetanLepage** [comment]
I am handling the `materialize` case in https://github.com/NixOS/nixpkgs/pull/361500 (along with the `libclang` removal).

**Comment by GaetanLepage** [comment]
> Tested successfully zed-editor on aarch64-darwin. Would be curious to know what failure @GaetanLepage is experiencing.

Maybe the builder just didn't like building 10 rust packages on 8 lonely cores...

**Comment by sodiboo** [comment]
> I am handling the `materialize` case in #361500 (along with the `libclang` removal).

i've dropped the commit for `materialize` from this one, then.

**Comment by GaetanLepage** [comment]
`ripasso-cursive` handled in #361736

**Comment by Aleksanaa** [comment]
zed-editor builds on aarch64-darwin

**Pull request merged**
