### PR TITLE
nixos/postfix: support alternate smtp ports when relaying

### PR DESCRIPTION
**Pull request by srhb**
###### Motivation for this change
Adds an option `services.postfix.relayPort` to support using an alternative smtp port when using a regular relay.

###### Things done
Tested ability to send via relay with and without `relayPort` set.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by srhb** [comment]
I altered this such that `25` is the default value of `relayPort`, and it is always included explicitly unless the `relayHost` is empty string (since `relayhost = :25` is not valid)

**Comment by srhb** [comment]
Ugh, actually, this changes the logic. Set to WIP while I figure out the consequences...

**Comment by srhb** [comment]
This should be ready for merge now. Should I squash? :)

**Comment by qknight** [comment]
@srhb looks good but i can't test it at the moment. did you test it?

**Comment by srhb** [comment]
@qknight Yep, every possible outcome.

**Comment by qknight** [comment]
@srhb currently has conflicts, if you fix them once more we merge it afterwards. thanks!

**Pull request merged**
