### PR TITLE
Automatic DNSSEC signatures & key schedule for nsd

### PR DESCRIPTION
**Pull request by gkleen**
###### Motivation for this change
This PR adds some (disabled by default) options to nsd which, when enabled, set up a systemd service which automatically generates DNSSEC-keys, signs some of the zones with them, and occasionally checks to make sure the zone complies with a key-schedule policy.

For implementing this I also had to patch the package for bind in order to (optionally; disabled by default) include a python script shipped with it, which manages compliance with a key-schedule.

I'd welcome suggestions for improvement or general discussion.
I suggest, however, holding off on merging until I've heard from my DNS provider regarding upstream submission of my DS-records and made sure everything does in fact work.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by pngwjpgh** [comment]
As far as I can determine this PR indeed does generate validly signed zones. So, as far as I'm concerned, everything works as expected.

**Comment by vcunat** [comment]
Looking only at the BIND changes (for now).

> checking python2 version >= 2.7 or python3 version >= 3.2... found

Python 3 instead of 2, please!

Another possibility would be to always build with the tools but separate those into another output.  (Python* by itself would make a large fraction of runtime closure and I can understand not everyone needs the tools.)  I certainly don't have a strong opinion on this choice; I might lean slightly to have seccomp by default, too.  /cc maintainers: @viric, @peti.

**Comment by peti** [comment]
@vcunat, enabling seccomp by default has caused issues in the past: #25645 & #23431.

**Comment by vcunat** [comment]
OK.  (Such information is one of the main reasons to ping "maintainers".)  Debian does have it, so it's probably doable somehow, but better let it be at least until someone actually wants it.

**Comment by pngwjpgh** [comment]
Separating out just the python-based tools would be kind of a pain.

I also can't see a usecase where one would need just the python-based tools (keymgr, e.g. mostly just calls the other, more primitive tools), which, i think, is the main feature splitting them out would provide?

**Comment by vcunat** [comment]
No big deal.  Not having two versions in some cases, e.g. using `dig` or something else from BIND "built without python" and at the same time activating this service you add.

**Comment by pngwjpgh** [comment]
*bump* ?

**Comment by pngwjpgh** [comment]
*bump*, again

**Comment by matthewbauer** [comment]
@GrahamcOfBorg build bind

**Comment by matthewbauer** [comment]
Looks good to me! Waiting for this though:

@GrahamcOfBorg test nsd

**Pull request merged**
