### PR TITLE
shaarli-material: Mark as broken

### PR DESCRIPTION
**Pull request by schneefux**
###### Motivation for this change
shaarli-material is a theme plugin for the shaarli web application.
The version of the theme needs to match shaarli's or else there are server errors, broken scripts and broken styling. shaarli-material is behind by almost a year, so the two versions of shaarli + shaarli-material in the nix store do not work together.
The build process for shaarli-material has changed in 0.10.3 and now depends on npm packages and a gulp script (changelog: https://github.com/kalvn/Shaarli-Material/releases) and I do not know how to update the build recipe for it.
I have not managed to set up a working shaarli + shaarli-material configuration with the prebuilt assets from the GitHub releases page either.

So I'd like to drop the package because it has been unusable for a year, is too difficult to maintain and apparently not used by anyone.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
@GrahamcOfBorg eval

**Comment by FRidh** [comment]
references need to be removed as well

**Comment by schneefux** [comment]
references removed :)

**Comment by gazally** [comment]
Why not just mark it as broken?

**Comment by schneefux** [comment]
I've marked it as broken instead.

@angristan You have updated this package in #66201. Are you using it or have you tested it?

**Comment by angristan** [comment]
Hi! I am not using it anymore.

**Comment by worldofpeace** [comment]
I can look into integrating this tomorrow then :+1:

**Comment by Infinisil** [comment]
What's the status on this?

**Comment by worldofpeace** [comment]
> What's the status on this?

@worldofpeace lost this PR in the giant list.
I still guess its fine to merge, will check.

**Pull request merged**
