### PR TITLE
various packages: use new darwin sdk pattern

### PR DESCRIPTION
**Pull request by NickCao**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by fom-csis** [comment]
```shell
--------- Report for 'aarch64-darwin' ---------
8 packages marked as broken and skipped:
garage garage_0_8 garage_0_8_7 garage_0_9 garage_0_9_4 garage_1_0_1 garage_1_x ostree-rs-ext

1 package failed to build:
cargo-feature

14 packages built:
cargo-fuzz cargo-limit cargo-unfmt eza eza.man openpgp-card-tools python311Packages.cryptg python311Packages.cryptg.dist python312Packages.cryptg python312Packages.cryptg.dist reindeer sequoia-chameleon-gnupg tg-archive tg-archive.dist
```

```shell
   Compiling cargo-feature v0.7.0 (/private/tmp/nix-build-cargo-feature-0.7.0.drv-0/source)
    Finished `release` profile [optimized] target(s) in 23.95s
     Running unittests src/main.rs (target/aarch64-apple-darwin/release/deps/cargo_feature-52b54e20bf76986a)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/success.rs (target/aarch64-apple-darwin/release/deps/success-9ba3da29feae3382)

running 8 tests
test add_target_feature ... FAILED
test list_optional_deps_as_feature ... FAILED
test ui_not_exist ... ok
test list_features ... ok
test hypen_underline ... ok
test remove_feature ... ok
test default_add ... ok
test disable_default_features ... ok

failures:

---- add_target_feature stdout ----
thread 'add_target_feature' panicked at /private/tmp/nix-build-rustc-1.82.0.drv-0/rustc-1.82.0-src/library/core/src/ops/function.rs:250:5:
Unexpected failure.
code-255
stderr=```"Can\'t find package from metadata! please check package `test-lib-dep` is exists in manifest\n"```
command=`cd "tests/test-ws" && "/private/tmp/nix-build-cargo-feature-0.7.0.drv-0/source/target/aarch64-apple-darwin/release/cargo-feature" "feature" "-p" "test-lib-dep" "+test-lib" "--target=cfg(target_arch = \"wasm32\")"`
code=255
stdout=""
stderr="Can\'t find package from metadata! please check package `test-lib-dep` is exists in manifest\n"

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- list_optional_deps_as_feature stdout ----
thread 'list_optional_deps_as_feature' panicked at /private/tmp/nix-build-rustc-1.82.0.drv-0/rustc-1.82.0-src/library/core/src/ops/function.rs:250:5:
Unexpected failure.
code-255
stderr=```"Can\'t find package from metadata! please check package `test_lib_dep` is exists in manifest\n"```
command=`cd "tests/test-ws" && "/private/tmp/nix-build-cargo-feature-0.7.0.drv-0/source/target/aarch64-apple-darwin/release/cargo-feature" "feature" "-p" "test_lib_dep"`
code=255
stdout=""
stderr="Can\'t find package from metadata! please check package `test_lib_dep` is exists in manifest\n"



failures:
    add_target_feature
    list_optional_deps_as_feature

test result: FAILED. 6 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.66s

error: test failed, to rerun pass `--test success`
```

**Comment by x123** [comment]
```shell
--------- Report for 'aarch64-darwin' ---------
8 packages marked as broken and skipped:
garage garage_0_8 garage_0_8_7 garage_0_9 garage_0_9_4 garage_1_0_1 garage_1_x ostree-rs-ext

1 package failed to build:
cargo-feature

14 packages built:
cargo-fuzz cargo-limit cargo-unfmt eza eza.man openpgp-card-tools python311Packages.cryptg python311Packages.cryptg.dist python312Packages.cryptg python312Packages.cryptg.dist reindeer sequoia-chameleon-gnupg tg-archive tg-archive.dist
```

```shell
   Compiling cargo-feature v0.7.0 (/private/tmp/nix-build-cargo-feature-0.7.0.drv-0/source)
    Finished `release` profile [optimized] target(s) in 23.95s
     Running unittests src/main.rs (target/aarch64-apple-darwin/release/deps/cargo_feature-52b54e20bf76986a)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/success.rs (target/aarch64-apple-darwin/release/deps/success-9ba3da29feae3382)

running 8 tests
test add_target_feature ... FAILED
test list_optional_deps_as_feature ... FAILED
test ui_not_exist ... ok
test list_features ... ok
test hypen_underline ... ok
test remove_feature ... ok
test default_add ... ok
test disable_default_features ... ok

failures:

---- add_target_feature stdout ----
thread 'add_target_feature' panicked at /private/tmp/nix-build-rustc-1.82.0.drv-0/rustc-1.82.0-src/library/core/src/ops/function.rs:250:5:
Unexpected failure.
code-255
stderr=```"Can\'t find package from metadata! please check package `test-lib-dep` is exists in manifest\n"```
command=`cd "tests/test-ws" && "/private/tmp/nix-build-cargo-feature-0.7.0.drv-0/source/target/aarch64-apple-darwin/release/cargo-feature" "feature" "-p" "test-lib-dep" "+test-lib" "--target=cfg(target_arch = \"wasm32\")"`
code=255
stdout=""
stderr="Can\'t find package from metadata! please check package `test-lib-dep` is exists in manifest\n"

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- list_optional_deps_as_feature stdout ----
thread 'list_optional_deps_as_feature' panicked at /private/tmp/nix-build-rustc-1.82.0.drv-0/rustc-1.82.0-src/library/core/src/ops/function.rs:250:5:
Unexpected failure.
code-255
stderr=```"Can\'t find package from metadata! please check package `test_lib_dep` is exists in manifest\n"```
command=`cd "tests/test-ws" && "/private/tmp/nix-build-cargo-feature-0.7.0.drv-0/source/target/aarch64-apple-darwin/release/cargo-feature" "feature" "-p" "test_lib_dep"`
code=255
stdout=""
stderr="Can\'t find package from metadata! please check package `test_lib_dep` is exists in manifest\n"



failures:
    add_target_feature
    list_optional_deps_as_feature

test result: FAILED. 6 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.66s

error: test failed, to rerun pass `--test success`
```

**Comment by NickCao** [comment]
`cargo-feature` should have been fixed.

**Comment by x123** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 358263`

---
### `aarch64-darwin`
<details>
  <summary>:fast_forward: 7 packages marked as broken and skipped:</summary>
  <ul>
    <li>garage</li>
    <li>garage_0_8</li>
    <li>garage_0_8_7</li>
    <li>garage_0_9</li>
    <li>garage_0_9_4</li>
    <li>garage_1_0_1</li>
    <li>garage_1_x</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 15 packages built:</summary>
  <ul>
    <li>cargo-feature</li>
    <li>cargo-fuzz</li>
    <li>cargo-limit</li>
    <li>cargo-unfmt</li>
    <li>eza</li>
    <li>eza.man</li>
    <li>openpgp-card-tools</li>
    <li>python311Packages.cryptg</li>
    <li>python311Packages.cryptg.dist</li>
    <li>python312Packages.cryptg</li>
    <li>python312Packages.cryptg.dist</li>
    <li>reindeer</li>
    <li>sequoia-chameleon-gnupg</li>
    <li>tg-archive</li>
    <li>tg-archive.dist</li>
  </ul>
</details>

**Review by x123 — APPROVED** [review]

**Pull request merged**
