### PR TITLE
stdenv: Provide a way for full `set -x` debugging

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

I need `set -x` all the time, and have been resorting to fairly ugly hacks to get it. @domenkozar needs it to. Re-purposing `NIX_DEBUG` as a "log-level"-style debugger seemed like a pretty non-intrusive way to achieve this.

###### Things done

I won't bother rebuilding the world just for this. But I'll be rebasing my https://github.com/NixOS/nixpkgs/pull/26805 on top of it.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

N.B. I often rebase my PRs on top of each other---they either depend or it's easier to chain rebase if the history is already linear-- \-and this one landed on https://github.com/NixOS/nixpkgs/pull/29610. Just look the last 4 commits.

CC @orivej

### CODE REVIEW

**Comment by orivej** [comment]
If you want a less intrusive alternative, you could treat `NIX_DEBUG` as a string of one letter flags, using `NIX_DEBUG=x` and `[[ "${NIX_DEBUG:-}" == *x* ]]` to activate `set -x`. This will not require changing anything beyond `stdenv/generic/setup.sh`.

---

As a sidenote, I wrote a Linux tool that proved very useful to debug and inspect all kinds of build problems called [fptrace](https://github.com/orivej/fptrace). It supervises a build process and writes a shell script for each program launched during the build. You can examine what environment variables were set, what command line arguments were passed, and repeat any build step, possibly altering it beforehand. The command will look like `fptrace -e -rm -s /tmp/fp nix-build -K …`.

You may be aware of this, but @dezgeg wrote the great [nix-debug-shell](https://github.com/dezgeg/nix-debug-shell) that surpassed my need for `set -x` in the stdenv.

**Comment by Ericson2314** [comment]
@orivej I didn't know of either of those. Thanks, they look quite useful! There's still a need to debug the code before any the phases (say with all my changes to `findInputs` in https://github.com/NixOS/nixpkgs/pull/26805), though, and for this I think `set -x` is still useful. The two you mention are definitely better for debugging packages most of the time, however :).

**Comment by Ericson2314** [comment]
We could use a set of flags, but seeing that this is a mass-rebuild no matter what, I don't mind changing all the use-sites: it makes things clearer for the reader.

**Comment by orivej** [comment]
You may also consider a more generic alternative: to evaluate an arbitrary value in `setup.sh`, e.g. `eval "$NIX_DEBUG_STDENV_SETUP"`.

**Comment by domenkozar** [comment]
I really like your improvements @Ericson2314 - just one request: can we update nixpkgs manual stdenv section to reflect such changes? In this case: https://nixos.org/nixpkgs/manual/#ssec-stdenv-attributes

**Comment by Ericson2314** [comment]
@domenkozar Did that, and added wrapper script `set -x` at `NIX_DEBUG >= 7`.

**Review by domenkozar — APPROVED** [review]
I haven't actually built this, but it looks good. Having bash tracing helps many times.

**Review by copumpkin — APPROVED** [review]
I like it

**Comment by Ericson2314** [comment]
[Did a little force-push and force-push dance to get github to pickup that the previous PR this was based off of is now merged. That will make the history easier to read for @edolstra, the only person whose opinion this is blocked on.]

**Comment by Ericson2314** [comment]
@edolstra approved of this on IRC.

**Pull request merged**
