### PR TITLE
nixos/filesystems: mount-pstore.service improvements

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change

The previous implementation was not functioning correctly for configurations other than `CONFIG_PSTORE m` (the NixOS default). This replaces the `modprobe@.service` dependency with a script (for `n`) and waits for the backend to be registered even if the persistent storage is already mounted (for `y`).

See also https://github.com/NixOS/nixpkgs/pull/123902#issuecomment-848270120.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by ajs124 — APPROVED** [review]
Works on my machine.

**Comment by ajs124** [comment]
Anything I can do to move this forward? I have a bunch of machines running the same kernel without `pstore` and while I could fix it in the config for them, this seems like an appropriate fix.

**Comment by hyperfekt** [comment]
Sorry, I'll get on this today. I want to rewrite the service because I noticed systemd-pstore can get started too early with `CONFIG_PSTORE=y`.

**Review by ajs124 — APPROVED** [review]

**Comment by ju1m** [comment]
My system has no `pstore` backend (neither `efi_pstore` because this system, Lenovo X201, does not support EFI, nor `ramoops` because it requires parameters like `mem_address=0x30000000 mem_size=0x100000 'memmap=0x100000$0x30000000'` to work) and thus `mount-pstore.service` now fails with:
```
-- Boot aa39f8583cf04d349906b9060d09f98d --
juil. 26 15:11:59 oignon jdxyhkqa3q589ji0y3y98aq4kppbfi01-mount-pstore.sh[679]: Persistent Storage backend was not registered in time.
juil. 26 15:11:59 oignon systemd[1]: mount-pstore.service: Main process exited, code=exited, status=1/FAILURE
juil. 26 15:11:59 oignon systemd[1]: mount-pstore.service: Failed with result 'exit-code'.
juil. 26 15:11:59 oignon systemd[1]: Failed to start mount-pstore.service.
```
My unknowledgeable guess is that some condition should be added somewhere to disable `mount-pstore.service` in my case,  maybe using the fact that `efiSupport = false`, or maybe something more clever.

I'm using `boot.kernelPackages = pkgs.linuxPackages_hardened`:
```
$ zgrep -i pstore /proc/config.gz 
CONFIG_EFI_VARS_PSTORE=m
# CONFIG_EFI_VARS_PSTORE_DEFAULT_DISABLE is not set
CONFIG_PSTORE=m
CONFIG_PSTORE_DEFLATE_COMPRESS=m
CONFIG_PSTORE_LZO_COMPRESS=m
CONFIG_PSTORE_LZ4_COMPRESS=m
CONFIG_PSTORE_LZ4HC_COMPRESS=m
# CONFIG_PSTORE_842_COMPRESS is not set
# CONFIG_PSTORE_ZSTD_COMPRESS is not set
CONFIG_PSTORE_COMPRESS=y
CONFIG_PSTORE_DEFLATE_COMPRESS_DEFAULT=y
# CONFIG_PSTORE_LZO_COMPRESS_DEFAULT is not set
# CONFIG_PSTORE_LZ4_COMPRESS_DEFAULT is not set
# CONFIG_PSTORE_LZ4HC_COMPRESS_DEFAULT is not set
CONFIG_PSTORE_COMPRESS_DEFAULT="deflate"
# CONFIG_PSTORE_CONSOLE is not set
# CONFIG_PSTORE_PMSG is not set
# CONFIG_PSTORE_FTRACE is not set
CONFIG_PSTORE_RAM=m
```

**Comment by hyperfekt** [comment]
As I understand it there isn't really any way good way to tell whether a persistent store is available (since there are a number of possibilities) until the kernel does or doesn't manage to use it.

You will want to simply add `systemd.services.mount-pstore.enable = false` to your configuration to suppress this.

**Comment by ajs124** [comment]
Turns out, this breaks the unstable-small channel: https://nix-cache.s3.amazonaws.com/log/2wi0635565fzq9pjx410cipmfqggj4qk-vm-test-run-installer-simple.drv

**Comment by hyperfekt** [comment]
I see, these virtual machines come without a pstore backend and the failure to activate all services is treated as an unsuccessful test, which makes sense. The solution is to make the service succeed nominally even if no backend is registered.

**Comment by hyperfekt** [comment]
Should be fixed in #131587, currently running the test locally to confirm.

**Pull request merged**
