### PR TITLE
idris2: Enable --install, bugfixes

### PR DESCRIPTION
**Pull request by wchresta**
This removes the need of the bin/idris2_app folder
and replaces it with proper links to the nix-storage folders
This also allows the user to override IDRIS2_PREFIX which
will allow them to use --install to install libraries.

* Fix: idris2_app/ was exposed in bin/
* Remove native Idris2 wrapper that set LD_LIBRARY_PATH
* Improve new Idris2 wrapper to set Idris2 paths to out folders

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wchresta** [comment]
@GrahamcOfBorg build idris2

**Comment by wchresta** [comment]
Conflicts with #95640 going to revise this once 2.0.1 is merged.

**Comment by wchresta** [comment]
ARGH

**Comment by jonringer** [comment]
I think you pushed the wrong branch :)

**Pull request closed without merging**
