### PR TITLE
bisq-desktop: 1.9.12 -> 1.9.14

### PR DESCRIPTION
**Pull request by emmanuelrosa**
## Description of changes

- Version bump from 1.9.12 to 1.9.14. See the changelog https://github.com/bisq-network/bisq/releases/tag/v1.9.14
- Refactor the package to account for upstream providing a directory of JAR files instead of a single "fat JAR."
  - The Tor binary is now in a different JAR file, and the file name contains what looks like a Git commit; This makes the file name inconsistent.  The `buildPhase` uses `find` to discover the file name.
  - I found additional java flags which upstream uses, so I added them.
  - Since there's no longer a single JAR, I had to add the `-classpath` argument when calling java.
  - I removed an unnecessary wrapper, to make my life easier in the future.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by naturallaw777** [comment]
@emmanuelrosa any help you would need on this? It seems the Bisq app cut off trading if you have 1.9.12. Thanks again for your hard work in keeping Bisq and Sparrow in Nix.

**Comment by emmanuelrosa** [comment]
It was ready to merge, but I may need to rebase it since it's now rather old. I'm waiting to clear the 23.11 release, because there's a lot of activity happening on the master branch.

If you want, you can copy the package and add it to your flake, in the mean time.

**Comment by naturallaw777** [comment]
> It was ready to merge, but I may need to rebase it since it's now rather old. I'm waiting to clear the 23.11 release, because there's a lot of activity happening on the master branch.
> 
> If you want, you can copy the package and add it to your flake, in the mean time.

That would be great! How would I go about putting it into my flake.nix, as I am familiar with putting in a whole flake module system into my nix flake, but I have never put in an individual nix package?

Thank you again for your help!

**Comment by emmanuelrosa** [comment]
You can download https://github.com/NixOS/nixpkgs/blob/5aeffc48db71fac1f3e7f379bea09e3353108c22/pkgs/applications/blockchains/bisq-desktop/default.nix

And then add an entry to flake.nix:

```
  bisq-desktop = callPackage .pkgs/bisq-desktop.nix {
    openjdk11 = pkgs.openjdk11.override { enableJavaFX = true; };
  };
```

**Comment by naturallaw777** [comment]
> You can download https://github.com/NixOS/nixpkgs/blob/5aeffc48db71fac1f3e7f379bea09e3353108c22/pkgs/applications/blockchains/bisq-desktop/default.nix
> 
> And then add an entry to flake.nix:
> 
> ```
>   bisq-desktop = callPackage .pkgs/bisq-desktop.nix {
>     openjdk11 = pkgs.openjdk11.override { enableJavaFX = true; };
>   };
> ```

Thank You! I will give it a try

**Comment by emmanuelrosa** [comment]
Replaced by #270234

**Pull request closed without merging**
