### PR TITLE
packages-config: drop versioned emacsPackages alias

### PR DESCRIPTION
**Pull request by Atemu**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Atemu** [comment]
I verified that the tarball still contains all emacsPackages.

**Comment by sternenseemann** [comment]
@adisbladis What are your plans on the `emacsPackages` alias? IIRC it was added for the benefit of Hydra and is not guaranteed to stick around?

Maybe we should re-create it in `packages-config.nix` to make sure it will stay around and it also works for older NixOS releases and the benefit of nixos-search.

**Review by ncfavier — APPROVED** [review]
Why is `emacsPackages` treated differently from the other `*Packages`? IMO it doesn't hurt to add it to the `inherit (super)` list just in case it's ever made `dontRecurseIntoAttrs`.

**Comment by sternenseemann** [comment]
It used to not exist outside of `aliases.nix` (in favor of `emacs.pkgs`), since there was no need for it, since it was fine that Hydra ignored it. Thus there was the need to create the alias in `packages-config.nix`, since we evaluate nixpkgs with `allowAliases = false` and `nix-env` would also have no way to figure out `emacs.pkgs` is a thing.

**Comment by Atemu** [comment]
@sternenseemann I added a comment to notify future editors

**Review by sternenseemann — APPROVED** [review]

**Comment by sternenseemann** [comment]
Why does the nixos search currently not show any results for plain `emacsPackages` (without the 28)? Do we need this after all?

**Comment by ncfavier** [comment]
Because of https://github.com/NixOS/nix/blob/b3d2a05c59266688aa904d5fb326394cbb7e9e90/src/libexpr/get-drvs.cc#L311-L313

**Comment by Atemu** [comment]
@sternenseemann not sure actually. They might be using an out-of-date eval of nixpkgs?

It's in the tarball which they take the info from.

**Comment by sternenseemann** [comment]
@Atemu, no @ncfavier is right, `nix-env` deduplicates the output by derivation, so it always just returns the first of the attributes it encounters.

**Comment by Atemu** [comment]
Thanks!

**Pull request merged**
