### PR TITLE
haskellPackages: unbreak selected packages

### PR DESCRIPTION
**Pull request by arcz**
###### Description of changes

I fixed some simple breaks of packages that are causing hydra eval errors.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
I get quite a few build failures with this, e.g. bzlib

```
Setup: Encountered missing or private dependencies:
base >=4.3 && <4.16, bytestring >=0.9 && <0.11
```

**Comment by sternenseemann** [comment]
> I get quite a few build failures with this, e.g. bzlib

Likely prior failures, e.g. `bzlib` is already broken on `haskell-updates`.

**Comment by risicle** [comment]
:facepalm: didn't even spot this is aimed at `haskell-updates`

**Review by cdepillabout — COMMENTED** [review]
This looks good!

When I tried compiling these locally, `vinyl-updates` is still correctly marked broken, and `htoml` looks like it has trouble compiling.

I removed the override for `vinyl-updates` in commit b239a47c8d7.  I remarked `htoml` as broken in commit 42d1913978b.  If you had intended to get these working as well, please feel free to revert these commits in a follow-up PR (or just redo the changes).

Thanks again!  These PRs are really great!

**Comment by maralorn** [comment]
Not to rain too much on the parade here. I also think these PRs are great.

But I think traditionally our bar for jailbreaks in configuration-common is a link to an upstream issue or PR regarding those wrong bounds.
(In rare cases this is important because upstream will respond that the bound is there to prevent a bug. More often for lower bounds, but it has happened for upper bounds.)
Honestly, I personally hate that policy, but I think it exists for a reason. So we should decide if we want to stick with it.

**Comment by cdepillabout** [comment]
> But I think traditionally our bar for jailbreaks in configuration-common is a link to an upstream issue or PR regarding those wrong bounds.

I agree with this in general, but right now we have so many things that are broken.  I'd be worried how long it would end up taking to get `haskell-updates` merged in if we had to upstream all of our `dontCheck` and `doJailbreak` changes.  (Although once we get `haskell-updates` basically in a working state this round, I think we should go back to trying to at least report things upstream.)

**Comment by maralorn** [comment]
Okay, I can live with “temporarily suspended”.

**Pull request merged**
