### PR TITLE
gpxsee: 11.6 -> 11.9

### LINKED ISSUE #202293: qt6's lrelease and friends look in the wrong place for binaries
### Describe the bug

Running `lrelease some_file.pro` breaks with qt6 as it's paths to various binaries are wrong while working fine with qt5.

Take the following PR as an example which adds a qt6 build of the gpxsee application: https://github.com/NixOS/nixpkgs/pull/202131

In the pre-patch

In the `preConfigure` we do this in order to get the translation files generated:

``` sh
lrelease gpxsee.pro
```

And while that is fine with qt5, using qt6, it errors out with:

``` sh
configuring                                      
sh: /nix/store/g9ajh1yq2ds1hrinjn07ihm6bvvyg2mz-qtbase-6.4.0/libexec/lrelease-pro: not found
```

This is because `lrelease-pro` is located in `qttools.dev` and not `qtbase.out`

Changing `preConfigure` to this:

``` sh
    ${qttools.dev}/libexec/lrelease-pro gpxsee.pro
```

Then just gives us this:

``` sh
configuring
sh: /nix/store/g9ajh1yq2ds1hrinjn07ihm6bvvyg2mz-qtbase-6.4.0/libexec/lprodump: not found
```

So basically our builder is looking in the wrong place.

Cc: @nickcao @nrdxp

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Description of changes

- qtpbfimageplugin: build with qt6 too
- gpxsee: 11.6 -> 11.9
  
Also a fix for the location of `lrelease` and friends from qttools. Thanks @NickCao !!

Further to https://github.com/NixOS/nixpkgs/pull/201440

Closes #202293

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by peterhoeg** [comment]
Apologies for the botched rebase and subsequent mass ping on the former PR.

**Comment by peterhoeg** [comment]
Should we just mark the qt6 version as broken on darwin?

**Comment by NickCao** [comment]
We are getting qt6 support on darwin: https://github.com/NixOS/nixpkgs/pull/202015

**Comment by sikmir** [comment]
> Should we just mark the qt6 version as broken on darwin?

That's qt5 build.

**Comment by peterhoeg** [comment]
> That's qt5 build.

Ah yes, but that *should* work as there are no changes to that. Do you mind trying to just build the latest version but without any of the other changes (although they really shouldn't make a difference)?

**Comment by sikmir** [comment]
> > That's qt5 build.
> 
> Ah yes, but that _should_ work as there are no changes to that. Do you mind trying to just build the latest version but without any of the other changes (although they really shouldn't make a difference)?

Yes, the same issue on master, looks like qttools is broken on darwin.

**Pull request merged**
