### PR TITLE
Freerdp backport

### PR DESCRIPTION
**Pull request by lheckemann**
###### Motivation for this change
Security fixes
cc @peterhoeg @mweinelt @FRidh (thanks for the involvement)

###### Things done

- [x] Built on NixOS
- [x] Tested `wlfreerdp`
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 87392` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
<br>- freerdp (freerdpUnstable)
<br>- gnome3.gnome-boxes
<br>- krdc (kdeApplications.krdc)
<br>- remmina
<br>- virt-manager-qt
<br>- weston
</details>

**Review by bjornfor — CHANGES_REQUESTED** [review]
That last commit seems to be cherry-picked not from master (github doesn't know which branch).

**Comment by FRidh** [comment]
Yes, that's because I often rebase commits of PR's instead of merge branches to avoid all the noise in the history. IMO backport PR's should not be opened before the original change is in but it seems it has become common practice.

**Comment by peterhoeg** [comment]
> IMO backport PR's should not be opened before the original change is in

:100: to that

Let's get this in asap.

**Comment by FRidh** [comment]
Without fixing up the reference? ok...

**Comment by lheckemann** [comment]
Aah, I did open this PR after the original, but grabbed the commit ID from the PR view :/

**Comment by FRidh** [comment]
Yes, that can't be trusted if the change is rebased instead of merged. Confusing.

**Pull request merged**
