### PR TITLE
alsa : 1.0.29 -> 1.1.0

### PR DESCRIPTION
**Pull request by heydojo**
Bump versions for the following packages within alsa :
- alsa-utils
- alsa-tools
- alsa-plugins
- alsa-lib

Please see http://www.alsa-project.org/main/index.php/Changes_v1.0.29_v1.1.0
for the full changelog this update brings.

### CODE REVIEW

**Comment by heydojo** [comment]
I bumped this locally due to an audio issue. Turns out it is a kernel related problem and not userspace, but it seems a waste to discard these changes. So I have proposed them here to see if there is a use.

**Comment by fps** [comment]
I do not run nixos anymore, but this change looks simple enough :)

**Comment by heydojo** [comment]
Hi @fps! do you want to continue being a named maintainer? I gather you run guix now?
Thanks for the input. :+1:

**Comment by fps** [comment]
@heydojo Sure, I might return to nix at some point in time..

**Comment by mdorman** [comment]
@peti as I read it, this change seems to have some problems: http://hydra.nixos.org/build/32092327

**Pull request merged**
