### PR TITLE
Revert "PHP maintainer team"

### PR DESCRIPTION
**Pull request by etu**
Reverts NixOS/nixpkgs#85575

### CODE REVIEW

**Comment by FRidh** [comment]
Why? Please motivate in commit message.

**Comment by etu** [comment]
I was planning to merge #85026 before #85575 and then had a email asking "why isn't this merged yet" and I thought "yes, I was planning to merge that by now".

So I merged #85575 before #85026 which created huge conflicts in #85026. 

So I reverted #85575, merged #85026, rebased and resolved the conflicts and created/merged #86342 to introduce the maintainer team.

**Comment by asymmetric** [comment]
Can we please refrain from merging our own unreviewed PRs in the future?

**Comment by etu** [comment]
Sure, but it was blocking me from doing actually useful things that I sensed was way more critical to get in. If you feel that a revert commit of metadata is something that later was going to be re-added is bad I'll be more careful in the future.

And there's a decent explanation in the comment above.

**Pull request merged**
