### PR TITLE
qt6.wrapQtAppsHook: also wrap scripts, pretty error, show hints

### PR DESCRIPTION
**Pull request by milahu**
###### Description of changes

**fix: also wrap scripts**

before this patch, wrapQtAppsHook failed to wrap script files
(bash scripts, python scripts, ...)

the checks `isELF $file` and `isMachO $file` dont make sense here

tested with `python3.pkgs.pyqt6_test` from #177530

**pretty error on missing buildInputs**

wrapQtAppsHook requires `buildInputs = [ qt6.qtbase ]`

before

> ```/nix/store/*-hook/nix-support/setup-hook: line 25: qtPluginPrefix: parameter null or not set```

after

> ```wrapQtAppsHook qtHostPathHook: error: qtPluginPrefix is unset. hint: add qt6.qtbase to nativeBuildInputs```

**show hints on missing nativeBuildInputs**

helpful for packaging qt apps

wrapQtAppsHook does not work when qtbase (etc) are only in buildInputs or propagatedBuildInputs

> ```wrapQtAppsHook makeQtWrapper: qtWrapperArgs is empty. hint: add qt6.qtbase to nativeBuildInputs```
> ```wrapQtAppsHook wrapQtApp: qtWrapperArgs is empty. hint: add qt6.qtbase to nativeBuildInputs```

ping @NickCao @nrdxp @kevincox 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
I'm a bit confused, should it be `nativeBuildInputs` or `buildInputs`?

**Comment by milahu** [comment]
`wrapQtAppsHook` only needs `nativeBuildInputs = [ qtbase ]`

**Comment by NickCao** [comment]
Wouldn't `buildInputs` be more appropriate as qtbase is a runtime dependencies?

**Comment by milahu** [comment]
> Wouldn't `buildInputs` be more appropriate as qtbase is a runtime dependencies?

only `nativeBuildInputs` are passed to `qtHostPathHook`

[the manual](https://gsc.io/70266391-48a6-49be-ab5d-acb5d7f17e76-nixpkgs/doc/nixpkgs-manual/html/ssec-setup-hooks.html) says that also `buildInputs` should be passed ...

> `qtWrapperArgs` is set by `wrapQtAppsHook` itself, checking it again sounds unreasonable.

`qtHostPathHook` is called for every item in `nativeBuildInputs`

the first check can be "tricked" by `buildInputs = [ qtbase ]` which will set `qtPluginPrefix`

**Comment by NickCao** [comment]
`qtHostPathHook` is at `hostOffset`, if I understood correctly it's call for dependencies in the same offset as `qtbase` itself, as the wrapper as to reflect runtime dependencies in `buildInputs`, `qtbase` also should be in `buildInputs`, I insist.

**Comment by milahu** [comment]
> only `nativeBuildInputs` are passed to `qtHostPathHook`
> [the manual](https://gsc.io/70266391-48a6-49be-ab5d-acb5d7f17e76-nixpkgs/doc/nixpkgs-manual/html/ssec-setup-hooks.html) says that also `buildInputs` should be passed ...

this is true only for `python3.pkgs.buildPythonPackage`

in `stdenv.mkDerivation`, the `hostOffset` hook also works with `buildInputs = [ qtbase ]`



> I think the correct fix is to move `qtHostPathHook` from `hostOffset` to `targetOffset`

yes, this works for both `mkDerivation` and `buildPythonPackage` : )

**Comment by NickCao** [comment]
`buildPythonPackage` sets `strictDeps` by default, maybe this can explain the difference in behavior.

**Comment by kevincox** [comment]
Result of `nixpkgs-review pr 181465` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>zint</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>cutemaze</li>
    <li>jami-client-qt</li>
    <li>qt6.wrapQtAppsHook (qt6Packages.wrapQtAppsHook)</li>
    <li>tdesktop</li>
  </ul>
</details>

**Comment by natsukagami** [comment]
Ran into two problems with this today :( 

1. The [Nixpkgs Manual](https://nixos.org/manual/nixpkgs/stable/#sec-language-qt) still mentions that scripts are not wrapped.
2. Any options to opt-out of scripts specifically? Automatically wrapping scripts broke them in `plasma-workspace` if they expect scripts to remain scripts (#316784 for plasma 6, I suspect they broke plasma 5 as well)

**Pull request merged**
