### PR TITLE
sage: 8.3 -> 8.4

### PR DESCRIPTION
**Pull request by timokau**
###### Motivation for this change

There ain't no rest for the wicked, sage updates don't grow on trees...

Shortly after the 8.3 update, the first 8.4 beta is already [released](https://groups.google.com/forum/#!topic/sage-release/QQs7aJ5KCNk).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by 7c6f434c** [comment]
I got a GitHub notification that you (@timokau) have pushed 0 commits. Was it a rebase?

**Comment by timokau** [comment]
I actually did push some commits (updating to beta3, merging master, cherry-picking the openblas fix from staging, updating to beta4). I did rebase but only locally with stuff I didn't push yet (no force-push). I don't know what confused github. I usually don't get any notifications at all if a PR gets updated by force-push.

**Comment by 7c6f434c** [comment]
So, a release has happenned?

**Comment by timokau** [comment]
Yes, I just got a bit sick and thus didn't do a final review & merge yet. Do you think the changes should be squashed? Thats how I did it the previous release but preserving the in-between releases might not hurt either when bisecting some issue.

**Comment by 7c6f434c** [comment]
No idea re:squashing, given that most intermediate commits are plain bumps… I guess it is you who would bisect Sage RCs anyway

**Comment by timokau** [comment]
The RCs yes, but the betas usually also remove some patches that were included upstream or something. I think preserving that history might be valuable, but it would also "pollute" commit history a bit.

**Comment by 7c6f434c** [comment]
Given that every commit is a working state, I guess it is not making anything worse compared to the status quo (we will have a lot of merged small branches until the entire model of interaction with the non-committer contributors is different).

So please do not underestimate the importance of your convenience in maintaining Sage.

(Personally, I do value keeping the true history of changes; I also find use of Git usually suboptimal for that goal)

**Comment by timokau** [comment]
>Personally, I do value keeping the true history of changes; I also find use of Git usually suboptimal for that goal

I agree. Thanks for your opinion :)

All but two of the nix specific patches are upstreamed now :tada:

**Comment by timokau** [comment]
Oops should've removed the WIP label first.

**Pull request merged**
