### PR TITLE
home-assistant: 0.84.6 -> 0.85.0

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
https://www.home-assistant.io/blog/2019/01/09/release-85/

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @peterhoeg

### CODE REVIEW

**Comment by peterhoeg** [comment]
Works here!

**Comment by peterhoeg** [comment]
You might want to run ```parse-requirements.py``` - there's a lot of new stuff there.

**Comment by dotlambda** [comment]
> You might want to run parse-requirements.py - there's a lot of new stuff there.

I always run it for new versions. What do you miss?

**Comment by peterhoeg** [comment]
My own added modules. Doh. Sorry about that.

**Comment by elseym** [comment]
this pr removed pytado dependencies. was there anything wrong with that component?

**Comment by dotlambda** [comment]
Someone needs to package python-tado:
```
# homeassistant.components.tado
python-tado==0.2.9
```
(from https://github.com/home-assistant/home-assistant/blob/dev/requirements_all.txt)

**Pull request merged**
