### PR TITLE
PhpStorm: 2022.2.1 -> 2022.2.2

### PR DESCRIPTION
**Pull request by dritter**
Hi!

There is a new release of [PhpStorm](https://www.jetbrains.com/phpstorm/download/) (2022.2.2), hence I updated the package.

This a cleaned up PR from #193215 , which I messed up. Thx for helping me @piegamesde .

### CODE REVIEW

**Comment by dritter** [comment]
@edwtjo Is there anything I can do to get this merged?

**Comment by drupol** [comment]
Hi @dritter,

Do you think it would be possible to provide the update for all the jetbrains products at once?

Thanks!

**Comment by dritter** [comment]
Hi @drupol ,
thanks for your reply. Sure, I can provide an update for all jetbrains products. Is this is preferred way? I thought it should be one commit (or even PR?) per product (even if the products are all from the same vendor, like in this case). I am asking, because I currently write a bot to do this updates..

Btw. closing this PR, as #195409 already updates PhpStorm as well.

**Comment by drupol** [comment]
Cool thx

**Pull request closed without merging**
