### PR TITLE
fwbuilder: init at 6.0.0-rc1

### PR DESCRIPTION
**Pull request by elatov**
###### Motivation for this change
Adding a new package fwbuilder (https://github.com/fwbuilder/fwbuilder)

###### Things done

- Built on platform(s)
  - [ x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by elatov** [comment]
@legendofmiracles thank you so much taking a look into this. I made the suggested changes. Please let me know if anything else needs to be done.

**Comment by legendofmiracles** [comment]
I didn't mean to put the maintainer part at the end of it's file lol.. only the meta section

The maintainer part should be in it's own commit.

**Comment by elatov** [comment]
oh I see. Here is the new pull request to just add the maintainer: #154629. I also updated this pull request to remove the change to the maintainer file.

**Comment by elatov** [comment]
@legendofmiracles let me know if this is missing anything else :) and thanks again for taking a look a this.

**Comment by legendofmiracles** [comment]
I'm unsure how I can test this, but if it works for you I'd merge it. 

One other thing though, can you please squash all commits?

**Comment by elatov** [comment]
The commits should be squashed now. I did test locally and it worked for me. :)

**Comment by legendofmiracles** [comment]
Result of `nixpkgs-review pr 152858` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>fwbuilder</li>
  </ul>
</details>

**Pull request merged**
