### PR TITLE
buildBazelPackage: add "fetchConfigured" for fetching only things required for the build

### PR DESCRIPTION
**Pull request by lukegb**
###### Motivation for this change

"bazel fetch" will, by default, fetch everything that _might_ be used,
including things that will later be discarded due to the way the build
is configured.

Concretely, this means that for some builds of Java packages, this will
avoid failures where the builder tries to retrieve the JDK from /usr/share/java
(or equivalent).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lukegb** [comment]
@ofborg build gvisor python35Packages.dm-sonnet bazel-watcher python35Packages.tensorflow-probability python35Packages.tensorflow python35Packages.tensorflow-build_2

**Comment by lukegb** [comment]
@ofborg build gvisor python37Packages.dm-sonnet bazel-watcher python37Packages.tensorflow-probability python37Packages.tensorflow python37Packages.tensorflow-build_2

**Comment by flokli** [comment]
This sounds really useful. I wonder if it should become the default?

Currently, there's a lot of packages in nixpkgs removing stuff in their `fetchAttrs.preInstall`, and some of this could probably be removed, leading to more binary reproducibility of the `bazel fetch` phase.

**Comment by lukegb** [comment]
I wanted to make it the default, but I decided I didn't want to update the fetch hashes of everything in one go (e.g. Tensorflow's hash changes, and possibly some other things too)

**Comment by flokli** [comment]
I meant, while flipping the default, also getting rid of the now obsolete "cleanup commands" in `fetchAttrs.preInstall`.

Happy to do this as a follow-up, too, but I assume it'd clean up many footguns and do a great deal w.r.t. changing hashes.

**Review by uri-canva — APPROVED** [review]
Sounds very good to me, also agree that the `fetch` should be removed once all the derivations are switched to use `build --nobuild` instead.

**Pull request merged**
