### PR TITLE
krun updates

### PR DESCRIPTION
**Pull request by NickCao**
###### Description of changes
libkrunfw: 3.3.0 -> 3.8.0
libkrun: 1.3.0 -> 1.4.6
krunvm: 0.2.1 -> 0.2.2

cc @jiegec for testing the darwin builds.
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jiegec** [comment]
Result of `nixpkgs-review pr 199104` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>libkrunfw</li>
  </ul>
</details>

**Comment by jiegec** [comment]
Result of `nixpkgs-review pr 199104` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>krunvm</li>
    <li>libkrun</li>
    <li>libkrun-sev</li>
    <li>libkrunfw</li>
  </ul>
</details>

**Comment by jiegec** [comment]
It works on aarch64-darwin.

**Comment by NickCao** [comment]
The build still fails after adding the missing dependencies on aarch64-linux:
```
libkrunfw> /build/cclfeJLb.s: Assembler messages:
libkrunfw> /build/cclfeJLb.s:35: Error: selected processor does not support `aese v13.16b,v4.16b'
libkrunfw> /build/cclfeJLb.s:36: Error: selected processor does not support `aesmc v13.16b,v13.16b'
libkrunfw> /build/cclfeJLb.s:48: Error: selected processor does not support `aese v7.16b,v4.16b'
libkrunfw> /build/cclfeJLb.s:49: Error: selected processor does not support `aesmc v7.16b,v7.16b'
libkrunfw> /build/cclfeJLb.s:52: Error: selected processor does not support `aese v1.16b,v4.16b'
libkrunfw> /build/cclfeJLb.s:53: Error: selected processor does not support `aesmc v1.16b,v1.16b'
libkrunfw> /build/cclfeJLb.s:60: Error: selected processor does not support `aese v11.16b,v4.16b'
libkrunfw> /build/cclfeJLb.s:61: Error: selected processor does not support `aesmc v11.16b,v11.16b'
```
Likely due to us using outdated toolchains for arm.

**Review by marsam — APPROVED** [review]

**Pull request merged**
