### PR TITLE
nv-codec-headers: recreate under by-name

### PR DESCRIPTION
**Pull request by AndersonTorres**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by AndersonTorres** [comment]
I will split handbrake in its own PR: https://github.com/NixOS/nixpkgs/pull/324418

**Comment by Aleksanaa** [comment]
Could you split migration and format in two commits to have a good log?

**Comment by AndersonTorres** [comment]
Formatting? This is a whole new derivation written basically from scratch that does the same as the previous one.

**Comment by Aleksanaa** [comment]
Then I have to say that your commit message is a bit misleading 😅

**Comment by AndersonTorres** [comment]
I will reformulate as soon as possible.

**Comment by AndersonTorres** [comment]
@Aleksanaa done.

**Review by Aleksanaa — APPROVED** [review]

**Comment by flokli** [comment]
It looks like this broke eval:

```
error:
       … while calling the 'head' builtin

         at /nix/store/pps0ryglnbx1p277ghzv4ax1is1lsb3c-nixpkgs-src/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'

         at /nix/store/pps0ryglnbx1p277ghzv4ax1is1lsb3c-nixpkgs-src/lib/modules.nix:821:9:

          820|     in warnDeprecation opt //
          821|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          822|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'nv-codec-headers-12' missing

       at /nix/store/pps0ryglnbx1p277ghzv4ax1is1lsb3c-nixpkgs-src/pkgs/by-name/nv/nv-codec-headers/package.nix:16:12:

           15|     "11" = sources.nv-codec-headers-11;
           16|     "12" = sources.nv-codec-headers-12;
             |            ^
           17|   }.${majorVersion};
┏━ 1 Errors: 
┃ error:
┃        … while calling the 'head' builtin
┃ 
┃          at /nix/store/pps0ryglnbx1p277ghzv4ax1is1lsb3c-nixpkgs-src/lib/att…
┃ 
┃          1574|         || pred here (elemAt values 1) (head values) then
┃          1575|           head values
┃              |           ^
┃          1576|         else
┃ 
┃        … while evaluating the attribute 'value'
┃ 
┃          at /nix/store/pps0ryglnbx1p277ghzv4ax1is1lsb3c-nixpkgs-src/lib/mod…
┃ 
┃           820|     in warnDeprecation opt //
┃           821|       { value = addErrorContext "while evaluating the option…
┃              |         ^
┃           822|         inherit (res.defsFinal') highestPrio;
┃ 
┃        (stack trace truncated; use '--show-trace' to show the full trace)
┃ 
┃        error: attribute 'nv-codec-headers-12' missing
┃ 
┃        at /nix/store/pps0ryglnbx1p277ghzv4ax1is1lsb3c-nixpkgs-src/pkgs/by-n…
┃ 
┃            15|     "11" = sources.nv-codec-headers-11;
┃            16|     "12" = sources.nv-codec-headers-12;
┃              |            ^
┃            17|   }.${majorVersion};
┣━━━                                                            
┗━ ∑ ⚠ Exited with 1 errors reported by nix at 14:43:54 after 5s
```

**Comment by flokli** [comment]
Revert in https://github.com/NixOS/nixpkgs/pull/325242.

**Comment by Aleksanaa** [comment]
I don't quite get it:

```
=> nix build .#nv-codec-headers-12
path '/home/aleksana/works/nixpkgs/pkgs/by-name/nv/nv-codec-headers' does not contain a 'flake.nix', searching up

=> tree ./result/
./result/
├── include
│   └── ffnvcodec
│       ├── dynlink_cuda.h
│       ├── dynlink_cuviddec.h
│       ├── dynlink_loader.h
│       ├── dynlink_nvcuvid.h
│       └── nvEncodeAPI.h
└── lib
    └── pkgconfig
        └── ffnvcodec.pc

5 directories, 6 files
```

Looks normal?

**Comment by Aleksanaa** [comment]
This PR only drops `nv-codec-headers-versions`, but that's not used anywhere within Nixpkgs either.

**Comment by AndersonTorres** [comment]
Oh boi, just when I was updating nvch 12...

**Pull request merged**
