### PR TITLE
flutterPackages.beta: 1.19.0-4.3.pre -> 1.20.0-7.2.pre, flutterPackages.dev: 1.20.0-3.0.pre -> 1.21.0-1.0.pre

### PR DESCRIPTION
**Pull request by kolaente**
###### Motivation for this change

Flutter update

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kolaente** [comment]
Since this PR only updates beta and dev versions, it is probably not urgent. Especially since the stable version was updated recently.

**Comment by worldofpeace** [comment]
@ofborg build flutterPackages.beta flutterPackages.dev

**Comment by worldofpeace** [comment]
I think a more clear message to use for your commit would be:
```
flutterPackages.beta: 1.19.0-4.3.pre -> 1.20.0-7.2.pre, flutterPackages.dev: 1.20.0-3.0.pre -> 1.21.0-1.0.pre
```

What is important is knowing which attribute has changed.

**Comment by kolaente** [comment]
@worldofpeace I see. Should I change it and force-push again?

**Comment by worldofpeace** [comment]
> @worldofpeace I see. Should I change it and force-push again?

Yep.

**Comment by kolaente** [comment]
@worldofpeace Done

**Review by worldofpeace — APPROVED** [review]

**Comment by worldofpeace** [comment]
Thanks @kolaente, merged :sparkles:

**Pull request merged**
