### PR TITLE
treewide: `\xc2\xa0` -> ` `

### PR DESCRIPTION
**Pull request by pbsds**
I have no idea what this escape sequence even is (edit: [found it, its the utf-8 encoding of nbsb](https://www.compart.com/en/unicode/U+00A0)), but it breaks the nix parser with cryptic errors if not used in a comment or string literal. A friend let me know MacOS is prone to input weird spaces, not sure if that is the source.

Candidates were located and created with:

    chr="$(echo -e '\xc2\xa0')"; rg -F "$chr" -l | xe sd -F "$chr" " "

There are some examples left, most being example output from `tree` in various markdown documents, some patches which we can't really touch, and `pkgs/tools/nix/nixos-render-docs/src/tests/test_commonmark.py` which I'm not sure if should be addressed

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by maralorn** [comment]
Super weird. The affected hls docs are most certainly typed by me on a nixos system with the neo keyboard layout. Would be good to know what I screwed up there, but it is (not only) a macos issue.

**Review by Mindavi — APPROVED** [review]
Some are maybe from copying from other webpages. Others I've no clue.

**Comment by pbsds** [comment]
A second friend notes that `alt-space` also do a this on Linux. GNOME swallows that input for me, but other wms may not

**Comment by emilazy** [comment]
I’m not a huge fan of stripping Unicode from comments and documentation where it is semantically correct, though of course some of these seem quite arbitrary and they certainly don‘t belong in commented out code or examples. I don’t feel strongly enough to get in the way here, though.

**Comment by maralorn** [comment]
@emilazy Do you know where this symbol is semantically correct?

**Review by happysalada — APPROVED** [review]

**Review by stigtsp — APPROVED** [review]
Looks good to me

**Comment by pbsds** [comment]
> I’m not a huge fan of stripping Unicode from comments and documentation where it is semantically correct, [...]

AFAU `pkgs/data/fonts/league-spartan/default.nix` and `nixos/modules/services/web-apps/pixelfed.nix` are the only cases? They bowth however already miss the non-breaking space in front of the (em) dash.

**Comment by emilazy** [comment]
At least `nixos/doc/manual/release-notes/rl-2311.section.md` looks intentional and correct to me, though I suppose it could just be an Alt key mishap. Anyway, this doesn’t touch any of my own carefully‐picked codepoints so I have no desire to get in the way 😆

**Review by h7x4 — APPROVED** [review]

**Pull request merged**
