### PR TITLE
solc: 0.8.2 -> 0.8.13

### PR DESCRIPTION
**Pull request by neirenoir**
###### Motivation for this change
solc updated. This time hopefully for real.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by sifmelcara — APPROVED** [review]
Compiles and runs on NixOS machine

**Comment by neirenoir** [comment]
Any updates on this? I would like to be able to use the LSP included in 0.8.11 with Kate. :( @akru @lionello @dbrock

**Comment by sifmelcara** [comment]
Can someone with merge permission help merge this?

**Comment by bobby285271** [comment]
Seems that `solc.passthru.tests` fails ([log](https://logs.nix.ci/?key=nixos/nixpkgs.160957&attempt_id=4cb76c41-7a0c-4de3-a23d-43d75c2d5cc0))?

```
Testing Python scripts...(B
..........................................................
----------------------------------------------------------------------
Ran 58 tests in 0.010s
OK
Testing LSP...(B
./scripts/tests.sh: line 87: ./scripts/../scripts/test_solidity_lsp.py: No such file or directory
builder for '/nix/store/ygmzlfc7kd9dvm28ih60g5fylvrwv7yi-solc-0.8.12.drv' failed with exit code 127
error: build of '/nix/store/ygmzlfc7kd9dvm28ih60g5fylvrwv7yi-solc-0.8.12.drv' failed
```

**Comment by neirenoir** [comment]
> Seems that `solc.passthru.tests` fails ([log](https://logs.nix.ci/?key=nixos/nixpkgs.160957&attempt_id=4cb76c41-7a0c-4de3-a23d-43d75c2d5cc0))?
> 
> ```
> Testing Python scripts...(B
> ..........................................................
> ----------------------------------------------------------------------
> Ran 58 tests in 0.010s
> OK
> Testing LSP...(B
> ./scripts/tests.sh: line 87: ./scripts/../scripts/test_solidity_lsp.py: No such file or directory
> builder for '/nix/store/ygmzlfc7kd9dvm28ih60g5fylvrwv7yi-solc-0.8.12.drv' failed with exit code 127
> error: build of '/nix/store/ygmzlfc7kd9dvm28ih60g5fylvrwv7yi-solc-0.8.12.drv' failed
> ```

Looks like it's an upstream issue. The specified file does not exist (relevant commit: https://github.com/ethereum/solidity/commit/927b24df1f37cdffc794a74081cfb37d01d47c17), but judging by the CircleCI config, it should be pointing to `test/lsp.py`. Could be a good idea to patch it upstream if this is indeed the case.

**Comment by neirenoir** [comment]
solc 0.8.13 has been released, but it takes forever to compile on my system. Could someone check out that it does work well? Also merge it to master while we are at it.

**Comment by sifmelcara** [comment]
> solc 0.8.13 has been released, but it takes forever to compile on my system. Could someone check out that it does work well?

Not the case for me, it only takes 5 minutes on my desktop

**Comment by neirenoir** [comment]
bruhs, bumping this. It's only a matter of merging. @akru @lionello @dbrock

**Review by lionello — APPROVED** [review]

**Pull request merged**
