### PR TITLE
factoryboy: init at 2.6.1

### PR DESCRIPTION
**Pull request by edugomez**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [x] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
0.5.7 seems to be the latest version of fake-factory. Therefore, I suggest you update the package. If that breaks `hypthesis1` (the only dependent), then we need to have a `fake_factory_0_2` instead.

I think you can fix the tests by adding
```
checkPhase = ''
  ${python.interpreter} -m unittest faker.tests
'';
```

Aside from that it looks good.

**Comment by edugomez** [comment]
Thanks, will add a new commit with those changes and your suggested `checkPhase = '' ${python.interpreter} ...`

**Comment by edugomez** [comment]
This seems to be build fine for me, with no complaints when building `hypothesis` with the updated `fake_factory` version as a dependency. Is Travis failing just due to the long build output?

**Comment by FRidh** [comment]
Yes, indeed.

**Pull request merged**
