### PR TITLE
altair: 4.1.0 -> 4.6.2

### LINKED ISSUE #188359: altair: 2.1.0 -> 2.6.2
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 4.1.0
desired version: 4.6.2

###### Notify maintainers

maintainers:
[Jonathan Wilkins](https://github.com/evalexpr) @evalexpr 
###### Note for maintainers

The current version exports are not compatible with the new one which means I can't send them.

Thank you for your efforts :smile: 

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by Anderssorby**
###### Description of changes

Fixes #188359

Changes: https://github.com/altair-graphql/altair/compare/v4.1.0...v4.6.2

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 188365` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>altair</li>
  </ul>
</details>

**Review by superherointj — APPROVED** [review]

**Comment by superherointj** [comment]
Sorry! Version is wrong!

v4.6.2

**Comment by superherointj** [comment]
Please fix commit message. (Should have been 4.6.2)

**Review by superherointj — CHANGES_REQUESTED** [review]
Please fix commit message. Both versions are wrong!

**Comment by Anderssorby** [comment]
@superherointj The commit message is corrected :smile:  This is what can happen when coding while commuting :sweat_smile:

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 188365` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>altair</li>
  </ul>
</details>

**Review by superherointj — APPROVED** [review]

**Pull request merged**
