### PR TITLE
terraform-providers.gitlab: 3.18.0 -> 3.19.0

### PR DESCRIPTION
**Pull request by zowoq**
source has moved to https://gitlab.com/gitlab-org/terraform-provider-gitlab and currently our terraform packaging only supports github

Better to remove it rather than leave this pinned on an outdated and/or broken version ~~and add it back if/when we add support for it.~~

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
> https://github.com/gitlabhq/terraform-provider-gitlab/releases/tag/v3.19.0
> This release hosted on GitHub only exists because it is the only way to publish to the Terraform Provider Registry.

As binaries still need to be hosted on github we probably won't see many providers that don't have their source on github, probably isn't worth the overhead of adding support for non-github source, easier to point people to https://github.com/nix-community/nixpkgs-terraform-providers-bin.

**Review by zimbatm — APPROVED** [review]

**Comment by Mic92** [comment]
I am still using this and would provide a fix in this PR just now.

**Comment by Mic92** [comment]
Could you cherry pick this? https://github.com/NixOS/nixpkgs/commit/f4c035eaccee30d9bec92c12eb68feb3c7dbc2d7
I have tested it on my dotfiles.

**Comment by Mic92** [comment]
Hang, I see some crash in there.

**Comment by Mic92** [comment]
Ok sorted. The crash was not related to the upgrade and also happened with the current version due to a change in gitlab.
https://github.com/NixOS/nixpkgs/commit/f4c035eaccee30d9bec92c12eb68feb3c7dbc2d7 is good to go.

**Comment by zowoq** [comment]
That makes gitlab the most complicated provider we package ... 

We've removed providers that were difficult to package before, really don't want the precedent of having this in nixpkgs, especially we we have a decent alternative available.

**Comment by zimbatm** [comment]
As long as gitlab can be auto-updated I'm fine with keeping it around. That was the point of removing weird packages; to 
help with the automation. nixpkgs has some advantages like the fact that it can support architectures that haven't been published to registry.terraform.io (something I encountered on M1).

**Comment by Mic92** [comment]
It would need to maintain this package either way if its in nixpkgs or outside would not matter to me too much.

**Comment by zowoq** [comment]
> As long as gitlab can be auto-updated I'm fine with keeping it around. That was the point of removing weird packages; to help with the automation.

It won't work with the update script like the other 140 providers do so I don't see any difference between this and when we removed teleport: https://github.com/NixOS/nixpkgs/pull/155959

**Comment by Mic92** [comment]
Now it is also updated by the update script: fbe4c0ef6fb1c32e77a58642ea14920ffec443ef

**Comment by zowoq** [comment]
And now it is even more complicated than it was previously ... as I said I don't want the precedent of having this in nixpkgs.

**Comment by Mic92** [comment]
Ironically I was using this provider to have an alternative for all my repos hosted exclusively on github and now for the same reason (not beeing on github) this provider is now dropped from nixpkgs. Anyway I just vendored the provider expression into the projects I was using it and call it a day.

**Comment by zowoq** [comment]
I've added support for fetchfromgitlab, don't know if it'll be useful other providers or even work with with them but I guess it'll do for now. Bit fragile as we need to override the owner as the registry still points to the github repo.

**Pull request merged**
