### PR TITLE
python3packages.bme680: Mark Linux only as upstream

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/105483#pullrequestreview-541312913

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by prusnak — APPROVED** [review]

**Comment by mweinelt** [comment]
Can you mention your source?

https://github.com/pimoroni/bme680-python/blob/master/packaging/debian/control#L22

**Comment by Mic92** [comment]
> Can you mention your source?
> 
> [https://github.com/pimoroni/bme680-python/blob/master/packaging/debian/control#L22](https://github.com/pimoroni/bme680-python/blob/master/packaging/debian/control?rgh-link-date=2020-12-01T16%3A04%3A34Z#L22)

Debian only packages for Linux and maybe kfreebsd. I am sure macOS will have different I2C interfaces.

**Comment by mweinelt** [comment]
> > Can you mention your source?
> > [https://github.com/pimoroni/bme680-python/blob/master/packaging/debian/control#L22](https://github.com/pimoroni/bme680-python/blob/master/packaging/debian/control?rgh-link-date=2020-12-01T16%3A04%3A34Z#L22)
> 
> Debian only packages for Linux and maybe kfreebsd. I am sure macOS will have different I2C interfaces.

Oh yeah, what I meant was, shouldn't this be `platform.unix` then? Or does that include Darwin as well?

**Comment by Mic92** [comment]
> > > Can you mention your source?
> > > [https://github.com/pimoroni/bme680-python/blob/master/packaging/debian/control#L22](https://github.com/pimoroni/bme680-python/blob/master/packaging/debian/control?rgh-link-date=2020-12-01T17%3A42%3A10Z#L22)
> > 
> > 
> > Debian only packages for Linux and maybe kfreebsd. I am sure macOS will have different I2C interfaces.
> 
> Oh yeah, what I meant was, shouldn't this be `platform.unix` then? Or does that include Darwin as well?

it does.

**Pull request merged**
