### PR TITLE
keyd: init at 2.4.1

### LINKED ISSUE #132474: package request: keyd - "A key remapping daemon for linux"
**Project description**

https://github.com/rvaiya/keyd

> A key remapping daemon for linux.

> Linux lacks a good key remapping solution. In order to achieve satisfactory results a medley of tools need to be employed (e.g xcape, xmodmap) with the end result often being tethered to a specified environment (X11). keyd attempts to solve this problem by providing a flexible system wide daemon which remaps keys using kernel level input primitives (evdev, uinput).

> Features
> keyd has several unique features many of which are traditionally only found in custom keyboard firmware like QMK. Some of the more interesting ones include:

>Layers.
>Key overloading (different behaviour on tap/hold).
Per keyboard configuration.
Instantaneous remapping (no flashing required).
A simple and intuitive config format.
Being display server agnostic (works on wayland and virtual console alike).

**Metadata**

* homepage URL: https://github.com/rvaiya/keyd
* source URL: https://github.com/rvaiya/keyd
* license: MIT
* platforms: linux

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Description of changes

When I initially made the move from Plasma X11 to Plasma Wayland, I needed a mechanism to handle some key remapping. `keyd` was one of the things I tried out (not the one I ended up using), but I just noticed a request to have it packaged while I was looking for something else, so here goes.

Closes #132474

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dit7ya** [comment]
Please take a look at https://github.com/NixOS/nixpkgs/pull/158793 (and https://github.com/NixOS/nixpkgs/pull/158489 before that). I agree that we can merge the package now and the module later, but would be nice to also get the module working.

**Comment by dit7ya** [comment]
Result of `nixpkgs-review pr 181361` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>keyd</li>
  </ul>
</details>

**Comment by foolnotion** [comment]
one small thing: the `keyd-application-mapper` script hardcodes the python path:
```
bash: /home/bogdb/.nix-profile/bin/keyd-application-mapper: /usr/bin/python3: bad interpreter: No such file or directory
```

**Comment by chreekat** [comment]
> `keyd` was one of the things I tried out (not the one I ended up using)

@peterhoeg out of curiousity, what did you end up using instead?

**Comment by peterhoeg** [comment]
I am using evscript which doesn't have a module but the package is in nixpkgs, so I'm using my own module (which I should upstream!!)

I cannot remember and don't have any notes about *why* I decided on evscript but my needs are very basic, so it's entirely possible that it had to do with the fact that the script example from evscript upstream did almost everything I wanted.

Here's my module:

```nix
{ config, lib, pkgs, ... }:

let
  cfg = config.common.services.evscript;

  inherit (lib)
    concatStringsSep
    mkEnableOption mkIf mkOption types;

in
{
  meta.maintainers = with lib.maintainers; [ peterhoeg ];

  options.common.services.evscript = {
    enable = mkEnableOption "evscript";

    script = mkOption {
      description = "Configuration script";
      type = types.str;
      default = ''
        //! [events]
        //! keys = ['LEFTALT', 'ESC', 'LEFTSHIFT', '9', 'RIGHTSHIFT', '0']
        fn main() ~ evdevs, uinput {
          should_esc := false
          should_lshift := false
          should_rshift := false
          loop {
            evts := next_events(evdevs)
            for i {
              evt := evts[i]
              xcape(mut should_esc,    evt, KEY_LEFTALT(),    [KEY_ESC()])
              xcape(mut should_lshift, evt, KEY_LEFTSHIFT(),  [KEY_LEFTSHIFT(), KEY_9()])
              xcape(mut should_rshift, evt, KEY_RIGHTSHIFT(), [KEY_LEFTSHIFT(), KEY_0()])
            }
          }
        }
      '';
    };

    devices = mkOption {
      description = "Devices";
      type = types.listOf types.str;
      default = [ "/dev/input/by-path/platform-i8042-serio-0-event-kbd" ];
    };

    hosts = mkOption {
      description = "Enabled on hosts";
      type = types.listOf types.str;
      default = [ "!dolores" ];
    };
  };

  config = mkIf cfg.enable {
    assertions = [
      {
        assertion = (builtins.length cfg.devices) > 0;
        message = "You must specify a device for evscript to use.";
      }
    ];

    security.wrappers.evscript = {
      setuid = true;
      owner = "root";
      group = "root";
      source = lib.getExe pkgs.evscript;
    };

    systemd.user.services.evscript = {
      description = "evscript";
      wantedBy = [ "default.target" ];
      unitConfig.ConditionHost = mkIf ((builtins.length cfg.hosts) > 0) cfg.hosts;
      serviceConfig = {
        Type = "exec";
        ExecStart = concatStringsSep " " [
          "/run/wrappers/bin/evscript"
          "-f ${pkgs.writeText "evscript.dyon" cfg.script}"
          "-d ${concatStringsSep " " cfg.devices}"
        ];
        Restart = "on-failure";
        RestartSec = "2s";
        Slice = "session.slice";
      };
    };
  };
}
```

**Pull request merged**
