### PR TITLE
fetchMvnDeps: init

### PR DESCRIPTION
**Pull request by tricktron**
## Description of changes

Fetches maven dependencies analogously to the fetchCargoTarball derivation. This is an alternative to the buildOffline feature flag in https://github.com/NixOS/nixpkgs/pull/255243.

@wegank What do you think makes more sense?

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yu-re-ka** [comment]
Is the output 100% reproducible on 

- darwin vs. linux
- x86_64 vs. aarch64
- across multiple runs / time
- with new maven versions?

**Comment by tricktron** [comment]
> Is the output 100% reproducible on
> 
> * darwin vs. linux
> * x86_64 vs. aarch64
> * across multiple runs / time
> * with new maven versions?

Yes, it should be. The build of my test project lemminx gives reproducible hashes on aarch64-darwin, x86_64-darwin and aarch64-linux. I will also use ofborg to test on x86_64-linux using this pr https://github.com/NixOS/nixpkgs/pull/256243.

Is there any other way to test this? The not-reproducible case is of course much easier to test because it only needs to be shown once.

**Comment by wegank** [comment]
What I'm thinking is that since we don't have a setupHook in maven, anyone using `mvnDeps = fetchMvnDeps ...` would have to provide an explicit `buildPhase` applying `maven` on `mvnDeps`. This seems strictly worse than the equivalent in Rust or #255243.

**Comment by tricktron** [comment]
> What I'm thinking is that since we don't have a setupHook in maven, anyone using `mvnDeps = fetchMvnDeps ...` would have to provide an explicit `buildPhase` applying `maven` on `mvnDeps`. This seems strictly worse than the equivalent in Rust or #255243, where the derivation of [the lemminx package](https://github.com/tricktron/nixpkgs/blob/de51d3734670e0682673376aee46db50703213a2/pkgs/development/tools/language-servers/lemminx/default.nix#L23-L30) is much cleaner than in #256243.

I fully agree. I will close this in favor of https://github.com/NixOS/nixpkgs/pull/255243.

**Pull request closed without merging**
