### PR TITLE
pkgs:octaveFull: darwin fixes

### PR DESCRIPTION
**Pull request by graham33**
###### Motivation for this change

These are fixes I needed (along with #131378) to get pkgs.octaveFull to work on Darwin, I can separate into different PRs if required.

The most questionable is the addition of the QT_MAC_WANTS_LAYER environment variable.  The underlying issue appears to be fixed in Qt 5.12.11, but I'm unable to get that to compile right now.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
Thanks for the PR!

**Comment by hexagonal-sun** [comment]
Hi @graham33 .  I was just wondeirng what version of clang you are using to build portaudio?  Specifially, 2b8523fd7e4252455e3596b93a990a7ea6f76ef5 broke the build of portaudio on arm64 darwin.  I've tried to build with both `clang_11` and `clang_12`.  Maybe this is a flag that's only supported on arm64 darwin?

**Comment by graham33** [comment]
Hi @hexagonal-sun , it looks like it's clang 7.1.0, which is a lot older:

```
nix-repl> portaudio.stdenv.cc
«derivation /nix/store/ahd0izfk7fsc79rv3hjcxsry6c46hj4c-clang-wrapper-7.1.0.drv»
```

I don't use Darwin very much myself, so this was a bit of a drive-by change, but from a brief look it seems that aarch64 Darwin uses a much newer version of llvm/clang than x86_64?  https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/darwin/default.nix#L7

Looks like we should at least make this conditional on aarch64 (I can make this change if you agree), but naively it seems odd that the clang version is so old on x86_64, even if it's not the latest and greatest now.

**Comment by hexagonal-sun** [comment]
@graham33 Thanks for taking a look!  I agree that it's strange that the x86_64 version of clang is so much older. I presume that there's already an issue to look at uplifting the compiler version?

In any case, I agree that adding the flag with the condition `stdenv.isDarwin && stdenv.isAarch64` seems like the right thing to do for the moment.  I suppose the 'proper' way to do it would be to check the version of `clang` that's being used as the conditional, but I think the former is fine for now if you agree?

Thanks!

**Comment by graham33** [comment]
@hexagonal-sun see #131550, hopefully that solves it.

**Pull request merged**
