### PR TITLE
zfs: 2.2.1 -> 2.2.2, zfs_2_1: 2.1.13 -> 2.1.14

### PR DESCRIPTION
**Pull request by adamcstephens**
## Description of changes

This includes the adopted fix for the recent data loss issue.

https://github.com/openzfs/zfs/releases/tag/zfs-2.2.2

https://github.com/openzfs/zfs/releases/tag/zfs-2.1.14

- zfsStable/zfsUnstable: 2.2.1 -> 2.2.2
- zfs_2_1: 2.1.13 -> 2.1.14

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by adamcstephens** [comment]
Result of `nixpkgs-review pr 271328` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_6_6.zfs_2_1</li>
    <li>linuxKernel.packages.linux_latest_libre.zfs_2_1</li>
    <li>linuxKernel.packages.linux_lqx.zfs_2_1</li>
    <li>linuxKernel.packages.linux_zen.zfs_2_1</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>diffoscope</li>
    <li>diffoscope.dist</li>
    <li>diffoscope.man</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.zfs (linuxKernel.packages.linux_testing_bcachefs.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.zfs_2_1</li>
  </ul>
</details>
<details>
  <summary>104 packages built:</summary>
  <ul>
    <li>appvm</li>
    <li>booster</li>
    <li>ceph</li>
    <li>ceph-client</li>
    <li>ceph-csi</li>
    <li>ceph.dev</li>
    <li>ceph.doc</li>
    <li>libceph (ceph.lib ,libceph.dev ,libceph.doc ,libceph.lib ,libceph.man)</li>
    <li>ceph.man</li>
    <li>check_zfs</li>
    <li>collectd</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>easysnap</li>
    <li>gnome.gnome-boxes</li>
    <li>guestfs-tools</li>
    <li>libguestfs</li>
    <li>libguestfs-with-appliance</li>
    <li>librenms</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>libvirt-glib.dev</li>
    <li>libvirt-glib.devdoc</li>
    <li>linuxKernel.packages.linux_4_19.zfs (linuxKernel.packages.linux_4_19.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_4_19.zfs_2_1</li>
    <li>linuxKernel.packages.linux_4_19_hardened.zfs (linuxKernel.packages.linux_4_19_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_4_19_hardened.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_10.zfs (linuxKernel.packages.linux_5_10.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_10.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_10_hardened.zfs (linuxKernel.packages.linux_5_10_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_10_hardened.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_15.zfs (linuxKernel.packages.linux_5_15.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_15.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_15_hardened.zfs (linuxKernel.packages.linux_5_15_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_15_hardened.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_4.zfs (linuxKernel.packages.linux_5_4.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_4.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_4_hardened.zfs (linuxKernel.packages.linux_5_4_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_4_hardened.zfs_2_1</li>
    <li>linuxKernel.packages.linux_6_1.zfs (linuxKernel.packages.linux_6_1.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_6_1.zfs_2_1</li>
    <li>linuxKernel.packages.linux_hardened.zfs (linuxKernel.packages.linux_6_1_hardened.zfs ,linuxKernel.packages.linux_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_hardened.zfs_2_1 (linuxKernel.packages.linux_6_1_hardened.zfs_2_1)</li>
    <li>linuxKernel.packages.linux_6_5.zfs (linuxKernel.packages.linux_6_5.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_6_5.zfs_2_1</li>
    <li>linuxKernel.packages.linux_6_5_hardened.zfs (linuxKernel.packages.linux_6_5_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_6_5_hardened.zfs_2_1</li>
    <li>linuxKernel.packages.linux_6_6.zfs (linuxKernel.packages.linux_6_6.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_latest_libre.zfs (linuxKernel.packages.linux_latest_libre.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_libre.zfs (linuxKernel.packages.linux_libre.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_libre.zfs_2_1</li>
    <li>linuxKernel.packages.linux_lqx.zfs (linuxKernel.packages.linux_lqx.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_xanmod.zfs (linuxKernel.packages.linux_xanmod.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_xanmod.zfs_2_1</li>
    <li>linuxKernel.packages.linux_xanmod_latest.zfs (linuxKernel.packages.linux_xanmod_latest.zfsUnstable ,linuxKernel.packages.linux_xanmod_stable.zfs ,linuxKernel.packages.linux_xanmod_stable.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.zfs_2_1 (linuxKernel.packages.linux_xanmod_stable.zfs_2_1)</li>
    <li>linuxKernel.packages.linux_zen.zfs (linuxKernel.packages.linux_zen.zfsUnstable)</li>
    <li>mgmt</li>
    <li>minikube</li>
    <li>minishift</li>
    <li>multipass</li>
    <li>nixops_unstable</li>
    <li>nixops_unstable.dist</li>
    <li>ocamlPackages.ocaml_libvirt</li>
    <li>partition-manager</li>
    <li>perl536Packages.SysVirt</li>
    <li>perl536Packages.SysVirt.devdoc</li>
    <li>perl538Packages.SysVirt</li>
    <li>perl538Packages.SysVirt.devdoc</li>
    <li>python310Packages.guestfs</li>
    <li>python310Packages.guestfs.dist</li>
    <li>python310Packages.libvirt</li>
    <li>python310Packages.libvirt.dist</li>
    <li>python310Packages.py-libzfs</li>
    <li>python310Packages.py-libzfs.dist</li>
    <li>python311Packages.guestfs</li>
    <li>python311Packages.guestfs.dist</li>
    <li>python311Packages.libvirt</li>
    <li>python311Packages.libvirt.dist</li>
    <li>python311Packages.py-libzfs</li>
    <li>python311Packages.py-libzfs.dist</li>
    <li>qemu_full</li>
    <li>qemu_full.debug</li>
    <li>qemu_full.ga</li>
    <li>rubyPackages.ruby-libvirt</li>
    <li>rubyPackages_3_2.ruby-libvirt</li>
    <li>rubyPackages_3_3.ruby-libvirt</li>
    <li>samba4Full</li>
    <li>samba4Full.dev</li>
    <li>samba4Full.man</li>
    <li>sanoid</li>
    <li>vagrant</li>
    <li>virt-manager</li>
    <li>virt-manager-qt</li>
    <li>virt-manager.dist</li>
    <li>virt-top</li>
    <li>virt-viewer</li>
    <li>zfs (zfsUnstable)</li>
    <li>zfs.dev (zfsUnstable.dev)</li>
    <li>zfs_2_1</li>
    <li>zfs_2_1.dev</li>
    <li>zfstools</li>
    <li>zpool-auto-expand-partitions</li>
    <li>zxfer</li>
  </ul>
</details>

**Review by amarshall — APPROVED** [review]
Diff looks good. Successfully ran `nix-build -A zfsStable.passthru.tests -A zfsUnstable.passthru.tests -A zfs_2_1.passthru.tests`

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_6_6.zfs_2_1</li>
    <li>linuxKernel.packages.linux_latest_libre.zfs_2_1</li>
    <li>linuxKernel.packages.linux_lqx.zfs_2_1</li>
    <li>linuxKernel.packages.linux_zen.zfs_2_1</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>linuxKernel.packages.linux_testing_bcachefs.zfs (linuxKernel.packages.linux_testing_bcachefs.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.zfs_2_1</li>
  </ul>
</details>
<details>
  <summary>107 packages built:</summary>
  <ul>
    <li>appvm</li>
    <li>booster</li>
    <li>ceph</li>
    <li>ceph-client</li>
    <li>ceph-csi</li>
    <li>ceph.dev</li>
    <li>ceph.doc</li>
    <li>libceph (ceph.lib ,libceph.dev ,libceph.doc ,libceph.lib ,libceph.man)</li>
    <li>ceph.man</li>
    <li>check_zfs</li>
    <li>collectd</li>
    <li>diffoscope</li>
    <li>diffoscope.dist</li>
    <li>diffoscope.man</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>easysnap</li>
    <li>gnome.gnome-boxes</li>
    <li>guestfs-tools</li>
    <li>libguestfs</li>
    <li>libguestfs-with-appliance</li>
    <li>librenms</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>libvirt-glib.dev</li>
    <li>libvirt-glib.devdoc</li>
    <li>linuxKernel.packages.linux_4_19.zfs (linuxKernel.packages.linux_4_19.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_4_19.zfs_2_1</li>
    <li>linuxKernel.packages.linux_4_19_hardened.zfs (linuxKernel.packages.linux_4_19_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_4_19_hardened.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_10.zfs (linuxKernel.packages.linux_5_10.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_10.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_10_hardened.zfs (linuxKernel.packages.linux_5_10_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_10_hardened.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_15.zfs (linuxKernel.packages.linux_5_15.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_15.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_15_hardened.zfs (linuxKernel.packages.linux_5_15_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_15_hardened.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_4.zfs (linuxKernel.packages.linux_5_4.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_4.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_4_hardened.zfs (linuxKernel.packages.linux_5_4_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_4_hardened.zfs_2_1</li>
    <li>linuxKernel.packages.linux_6_1.zfs (linuxKernel.packages.linux_6_1.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_6_1.zfs_2_1</li>
    <li>linuxKernel.packages.linux_hardened.zfs (linuxKernel.packages.linux_6_1_hardened.zfs ,linuxKernel.packages.linux_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_hardened.zfs_2_1 (linuxKernel.packages.linux_6_1_hardened.zfs_2_1)</li>
    <li>linuxKernel.packages.linux_6_5.zfs (linuxKernel.packages.linux_6_5.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_6_5.zfs_2_1</li>
    <li>linuxKernel.packages.linux_6_5_hardened.zfs (linuxKernel.packages.linux_6_5_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_6_5_hardened.zfs_2_1</li>
    <li>linuxKernel.packages.linux_6_6.zfs (linuxKernel.packages.linux_6_6.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_latest_libre.zfs (linuxKernel.packages.linux_latest_libre.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_libre.zfs (linuxKernel.packages.linux_libre.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_libre.zfs_2_1</li>
    <li>linuxKernel.packages.linux_lqx.zfs (linuxKernel.packages.linux_lqx.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_xanmod.zfs (linuxKernel.packages.linux_xanmod.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_xanmod.zfs_2_1</li>
    <li>linuxKernel.packages.linux_xanmod_latest.zfs (linuxKernel.packages.linux_xanmod_latest.zfsUnstable ,linuxKernel.packages.linux_xanmod_stable.zfs ,linuxKernel.packages.linux_xanmod_stable.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.zfs_2_1 (linuxKernel.packages.linux_xanmod_stable.zfs_2_1)</li>
    <li>linuxKernel.packages.linux_zen.zfs (linuxKernel.packages.linux_zen.zfsUnstable)</li>
    <li>mgmt</li>
    <li>minikube</li>
    <li>minishift</li>
    <li>multipass</li>
    <li>nixops_unstable</li>
    <li>nixops_unstable.dist</li>
    <li>ocamlPackages.ocaml_libvirt</li>
    <li>partition-manager</li>
    <li>perl536Packages.SysVirt</li>
    <li>perl536Packages.SysVirt.devdoc</li>
    <li>perl538Packages.SysVirt</li>
    <li>perl538Packages.SysVirt.devdoc</li>
    <li>python310Packages.guestfs</li>
    <li>python310Packages.guestfs.dist</li>
    <li>python310Packages.libvirt</li>
    <li>python310Packages.libvirt.dist</li>
    <li>python310Packages.py-libzfs</li>
    <li>python310Packages.py-libzfs.dist</li>
    <li>python311Packages.guestfs</li>
    <li>python311Packages.guestfs.dist</li>
    <li>python311Packages.libvirt</li>
    <li>python311Packages.libvirt.dist</li>
    <li>python311Packages.py-libzfs</li>
    <li>python311Packages.py-libzfs.dist</li>
    <li>qemu_full</li>
    <li>qemu_full.debug</li>
    <li>qemu_full.ga</li>
    <li>rubyPackages.ruby-libvirt</li>
    <li>rubyPackages_3_2.ruby-libvirt</li>
    <li>rubyPackages_3_3.ruby-libvirt</li>
    <li>samba4Full</li>
    <li>samba4Full.dev</li>
    <li>samba4Full.man</li>
    <li>sanoid</li>
    <li>vagrant</li>
    <li>virt-manager</li>
    <li>virt-manager-qt</li>
    <li>virt-manager.dist</li>
    <li>virt-top</li>
    <li>virt-viewer</li>
    <li>zfs (zfsUnstable)</li>
    <li>zfs.dev (zfsUnstable.dev)</li>
    <li>zfs_2_1</li>
    <li>zfs_2_1.dev</li>
    <li>zfstools</li>
    <li>zpool-auto-expand-partitions</li>
    <li>zxfer</li>
  </ul>
</details>

**Comment by RaitoBezarius** [comment]
Please, for the future, give enough time for me to review the 2.1.x series changes. 2.1.14 does not contain only the new patch but more commits than this one. Fortunately, they should work, but I do quite comprehensive testing on ZFS changes before merging them. There is no hurry for the 2.1.x series.

**Comment by adamcstephens** [comment]
I did run the zfs test suite on both x86_64 and aarch64, I just failed to report it here. If you have other tests that we can also run, I'd love to know.

Otherwise, I will wait for your input moving forward or we can even decouple the versions for future bumps.

**Comment by RaitoBezarius** [comment]
> I did run the zfs test suite on both x86_64 and aarch64 for 2.1 and 2.2,

Just to be clear, I am talking about https://github.com/openzfs/zfs/tree/master/tests. Not the NixOS tests. But if we were talking about the same thing, awesome!

Alright, here's my checklist in general:

- ZFS test suite (it's not always run by upstream on the staging branches and… not everything has a test in the test suite alas.)
- Scrolling over the delta of commits
- In case of changes of kernel version, verifying the issue tracker for known potential regressions
- In case of changes of kernel version, checking what was changed for compat (sometimes, the patch is badly done, e.g. leak memory)
- When a release has a lot of changes, I roll it out on some of my production deployments, my "test" deployment is usually a 80TB (raw) ZFS cluster of ~90 disks, containing a mix'n'match of raidz1, raidz2, mirrors with small vdevs and big vdevs, some vdev were constructed and extended, some vdev contains already failed disks and replaced disks, it's full of SAS HDD plugged over SAS HBA 6Gbps. Not anyone can afford such a setup, so I recommend to, at least, build a "test" ZFS cluster with file images in some virtual machine or something, this can help test the logical stuff, not the physical+logical stuff. And ensure you accumulate state, failures and what not in there to have a "realistic" setup that our NixOS tests cannot replicate as they always start afresh.

In the case of this particular ZFS 2.1.x change, we are in a context where we had this SEEK_HOLE bug for a while lurking around:

(a) I would verify that the new ZFS 2.1.x has a regression test for this SEEK_HOLE, Gentoo has a reproducer for it AFAIK (it was even transferred over bcachefs and other filesystems as it seems to be quite the pitfall).
(b) I would look at the extra commits that are not fixing the SEEK_HOLE bug, e.g. https://github.com/openzfs/zfs/commit/1ca531971f176ae7b8ca440e836985ae1d7fa0ec to avoid introducing another subtle bug and creating further data bugs. That's why grabbing **only** the patch was a safe way because we know for sure what does it produce and care should be taken whenever ZFS releases a "bug fixing" release in urgency, given what we went through recently.

You will notice that https://github.com/openzfs/zfs/commits/zfs-2.1.14-staging does not contain the 2.1.14 commit, which makes me dubious about whether the ZFS test suite was run for the 2.1.14 release.

**Comment by numinit** [comment]
@RaitoBezarius It seems like it's worth it to add ztest to a NixOS test suite and ask upstream for/contribute more tests, but this will obviously not fix the "we need pools with history to exercise edgecases" and "we basically need dedicated test hardware" problems. 

That being said... possibly crackpot idea that may solve half of this. The idea is to make a NixOS test script that converges a handful of pools onto some state, and have disk images containing exported pools corresponding to that state be the output of the test. Then we duplicate the derivation, and have it depend on the previous test's output.

The obvious trouble here is that we'd need a derivation per iteration, which makes this really difficult, because we are eternally cursed to test a mutable filesystem developed by Sun Microsystems (RIP) using state stored in an immutable store. But it actually seems doable if the store path of one previous iteration is kept around.

I may try something like this when I've got a few free cycles, since I have a machine running a large SSD pool.

**Comment by RaitoBezarius** [comment]
@numinit you can extract ZTS from https://github.com/NixOS/nixpkgs/pull/271703 which introduces it in nixpkgs as I ported ZFS 2.1.x to Linux 6.7.

> That being said... possibly crackpot idea that may solve half of this. The idea is to make a NixOS test script that converges a handful of pools onto some state, and have disk images containing exported pools corresponding to that state be the output of the test. Then we duplicate the derivation, and have it depend on the previous test's output.
> 
> The obvious trouble here is that we'd need a derivation per iteration, which makes this really difficult, because we are eternally cursed to test a mutable filesystem developed by Sun Microsystems (RIP) using state stored in an immutable store. But it actually seems doable if the store path of one previous iteration is kept around.
> 
> I may try something like this when I've got a few free cycles, since I have a machine running a large SSD pool.

Honestly, I would rather invest into a shared hardware pool that everyone just write into while testing their ZFS stuff, you take a disk snapshot before every dangerous operations (or you don't) and you rollback to previous state everytime you fail.

**Pull request merged**
