### PR TITLE
step-ca: 0.15.15 -> 0.16.0

### PR DESCRIPTION
**Pull request by mohe2015**
###### Motivation for this change

Reasoning for backporting: v0.* and no specified support for older versions. Also never saw updates to older versions.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mohe2015** [comment]
Result of `nixpkgs-review pr 131821` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>step-ca</li>
  </ul>
</details>

**Review by dguibert — APPROVED** [review]
Looks good to me.

**Comment by mohe2015** [comment]
@dguibert Sorry but I realized that this package is not reproducible and tried to fix it. This should really not break it as the buildid is just a value in an elf section but feel free to quickly check again.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 131821` at 5f645dd5 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>step-ca</li>
  </ul>
</details>

**Comment by risicle** [comment]
I don't think that's sufficient justification for backporting. Firstly many projects don't hit 1.0 for many _many_ years, and by this logic anyone using a 0.x version of something should expect it to be switched out from under their feet at any moment (I guarantee that you depend on the stability of a 0.x package somewhere in your stack). Furthermore a package not having stated support for a version doesn't mean we can't/shouldn't distribute it. _If_ there is a grave bug or security issue, then we can worry about that when the time comes on a case-by-case basis. FWIW most projects don't have _any_ stated support for any version (possibly not even the latest), which would mean we should be just continually bumping 90% of packages. And then stable would be the same thing as unstable.

**Pull request merged**
