### PR TITLE
tokei: add zlib to checkInputs on Darwin

### PR DESCRIPTION
**Pull request by midchildan**
## Description of changes

Fixes Darwin build failure.

https://hydra.nixos.org/build/241282331/nixlog/1

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
I'm not sure why ofborg is failing .
Also if the checkPhase fails, the lib is probably required for buildInputs as well no ?

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 268563` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by midchildan** [comment]
The ofborg logs say `"No space left on device"`, so it seems to be a problem on ofborg's end.

**Comment by midchildan** [comment]
The error occurrs while compiling the test runner, so it's not a dependency of the application itself. I also confirmed the resulting binary runs without problems.

**Comment by happysalada** [comment]
@ofborg eval tokei

Both sounds good to me, let me try the eval again and merge if it goes through.

**Comment by happysalada** [comment]
ofborg eval tokei

**Comment by happysalada** [comment]
@ofborg eval

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 268563` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>emacsPackages.tokei</li>
    <li>tokei</li>
  </ul>
</details>

**Review by wegank — APPROVED** [review]

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 268563` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>emacsPackages.tokei</li>
    <li>tokei</li>
  </ul>
</details>

**Pull request merged**
