### PR TITLE
builderDefsPackage cleanup

### PR DESCRIPTION
**Pull request by globin**
Removed some inherently broken ancient stuff

cc @domenkozar

### CODE REVIEW

**Comment by domenkozar** [comment]
Awesome! I'll setup a jobset.

**Comment by domenkozar** [comment]
http://hydra.nixos.org/jobset/nixpkgs/pr-12701

**Comment by Mathnerd314** [comment]
It looks like the jobset didn't set up properly:
> error fetching latest change from git repo at `https://github.com/mayflower/builder-def-cleanup.git':
> fatal: could not read Username for 'https://github.com': No such device or address

**Comment by domenkozar** [comment]
it just evaluated 10min ago

**Comment by domenkozar** [comment]
@globin most of packages are built, could you check if everything is OK?

**Comment by globin** [comment]
Failures look unrelated

**Pull request merged**
