### PR TITLE
koka: 2.1.1 -> 2.1.2

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123574` at 34bb81e9 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>koka</li>
    <li>tests.trivial</li>
  </ul>
</details>
<details>
  <summary>6 suggestions:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `hspec`.
Near pkgs/development/compilers/koka/default.nix:3:31:
```
  |
3 | , filepath, haskeline, hpack, hspec, hspec-core, json, lib, mtl
  |                               ^
```
</li>
    <li>warning: unused-argument

Unused argument: `hspec-core`.
Near pkgs/development/compilers/koka/default.nix:3:38:
```
  |
3 | , filepath, haskeline, hpack, hspec, hspec-core, json, lib, mtl
  |                                      ^
```
</li>
    <li>warning: unused-argument

Unused argument: `extra`.
Near pkgs/development/compilers/koka/default.nix:2:63:
```
  |
2 | , alex, array, base, bytestring, cond, containers, directory, extra
  |                                                               ^
```
</li>
    <li>warning: unused-argument

Unused argument: `json`.
Near pkgs/development/compilers/koka/default.nix:3:50:
```
  |
3 | , filepath, haskeline, hpack, hspec, hspec-core, json, lib, mtl
  |                                                  ^
```
</li>
    <li>warning: unused-argument

Unused argument: `filepath`.
Near pkgs/development/compilers/koka/default.nix:3:3:
```
  |
3 | , filepath, haskeline, hpack, hspec, hspec-core, json, lib, mtl
  |   ^
```
</li>
    <li>warning: unused-argument

Unused argument: `regex-compat`.
Near pkgs/development/compilers/koka/default.nix:4:20:
```
  |
4 | , parsec, process, regex-compat, text, time }:
  |                    ^
```
</li>
  </ul>
</details>

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 123574` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>koka</li>
  </ul>
</details>

**Comment by siraben** [comment]
Build log

```
@nix { "action": "setPhase", "phase": "setupCompilerEnvironmentPhase" }
setupCompilerEnvironmentPhase
Build with /nix/store/6sqrxr2dmn1zrya0gyp22hy2s34v5a44-ghc-8.10.4.
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/q4pg36s9mms624g950x4x6idljrw5dy8-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
generated koka.cabal
@nix { "action": "setPhase", "phase": "compileBuildDriverPhase" }
compileBuildDriverPhase
setupCompileFlags: -package-db=//private/tmp/nix-build-koka-2.1.2.drv-0/setup-package.conf.d -j4 -threaded -rtsopts
[1 of 1] Compiling Main             ( Setup.hs, /private/tmp/nix-build-koka-2.1.2.drv-0/Main.o )
Linking Setup ...
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
configureFlags: --verbose --prefix=/nix/store/xa1bkdl3y3l11vcf1fq5q6pyia0nrjmh-koka-2.1.2 --libdir=$prefix/lib/$compiler --libsubdir=$abi/$libname --with-gcc=clang --package-db=//private/tmp/nix-build-koka-2.1.2.drv-0/package.conf.d --ghc-options=-j4 --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-static --disable-executable-dynamic --disable-tests --disable-benchmarks --enable-library-vanilla --disable-library-for-ghci --extra-include-dirs=/nix/store/3flagapcvzdjljhsgvy9icxlagdyiwyw-libc++-7.1.0-dev/include --extra-lib-dirs=/nix/store/d51irgw2cb1md3yn5xx7snikm8m1zz3f-libc++-7.1.0/lib --extra-include-dirs=/nix/store/96zdhjq2hizfi1qj726whdkxvd75zgga-libc++abi-7.1.0-dev/include --extra-lib-dirs=/nix/store/1jc36rzvkk5j6qzifg4vkij2rjmp9akm-libc++abi-7.1.0/lib --extra-include-dirs=/nix/store/02qncmmxclhd4rdycvgd4k6y3rmc7yhn-compiler-rt-7.1.0-dev/include --extra-lib-dirs=/nix/store/7rk64yfwg030pz4h1504vhsq4aizhlzg-compiler-rt-7.1.0/lib --extra-lib-dirs=/nix/store/xbqnc8wzkpdp9iqvz2vljnd9370svz8f-ncurses-6.2/lib --extra-lib-dirs=/nix/store/438xsgimpw6v3x11sn3b98m6iz6s22gf-libffi-3.3/lib --extra-lib-dirs=/nix/store/npgb696f2x7v2cb1br8p5a906gxf9g6b-gmp-6.2.1/lib --extra-include-dirs=/nix/store/fnh8x9c6yv1k4rfc5x01h8rn7x694yyk-libiconv-50/include --extra-lib-dirs=/nix/store/fnh8x9c6yv1k4rfc5x01h8rn7x694yyk-libiconv-50/lib --extra-include-dirs=/nix/store/pm83h713fcfwlgkkx0rxqp3g4l8r82hn-kklib-2.1.2/include --extra-lib-dirs=/nix/store/pm83h713fcfwlgkkx0rxqp3g4l8r82hn-kklib-2.1.2/lib --extra-framework-dirs=/nix/store/3ggxnmp130g205y7sarhmr4kjq7cg50v-swift-corefoundation/Library/Frameworks
Using Parsec parser
Configuring koka-2.1.2...
Dependency array -any: using array-0.5.4.0
Dependency base >=4.13 && <5: using base-4.14.1.0
Dependency bytestring -any: using bytestring-0.10.12.0
Dependency cond -any: using cond-0.4.1.1
Dependency containers -any: using containers-0.6.2.1
Dependency directory -any: using directory-1.3.6.0
Dependency haskeline -any: using haskeline-0.8.0.1
Dependency mtl -any: using mtl-2.2.2
Dependency parsec -any: using parsec-3.1.14.0
Dependency process -any: using process-1.6.9.0
Dependency text -any: using text-1.2.4.1
Dependency time -any: using time-1.9.3
Source component graph: component exe:koka
Configured component graph:
    component koka-2.1.2-JWnBITvFQBQJegSdgFrzny-koka
        include array-0.5.4.0
        include base-4.14.1.0
        include bytestring-0.10.12.0
        include cond-0.4.1.1-FeTgf08fDE47fZ78jhlgNX
        include containers-0.6.2.1
        include directory-1.3.6.0
        include haskeline-0.8.0.1
        include mtl-2.2.2
        include parsec-3.1.14.0
        include process-1.6.9.0
        include text-1.2.4.1
        include time-1.9.3
Linked component graph:
    unit koka-2.1.2-JWnBITvFQBQJegSdgFrzny-koka
        include array-0.5.4.0
        include base-4.14.1.0
        include bytestring-0.10.12.0
        include cond-0.4.1.1-FeTgf08fDE47fZ78jhlgNX
        include containers-0.6.2.1
        include directory-1.3.6.0
        include haskeline-0.8.0.1
        include mtl-2.2.2
        include parsec-3.1.14.0
        include process-1.6.9.0
        include text-1.2.4.1
        include time-1.9.3
Ready component graph:
    definite koka-2.1.2-JWnBITvFQBQJegSdgFrzny-koka
        depends array-0.5.4.0
        depends base-4.14.1.0
        depends bytestring-0.10.12.0
        depends cond-0.4.1.1-FeTgf08fDE47fZ78jhlgNX
        depends containers-0.6.2.1
        depends directory-1.3.6.0
        depends haskeline-0.8.0.1
        depends mtl-2.2.2
        depends parsec-3.1.14.0
        depends process-1.6.9.0
        depends text-1.2.4.1
        depends time-1.9.3
Using Cabal-3.2.1.0 compiled by ghc-8.10
Using compiler: ghc-8.10.4
Using install prefix: /nix/store/xa1bkdl3y3l11vcf1fq5q6pyia0nrjmh-koka-2.1.2
Executables installed in:
/nix/store/xa1bkdl3y3l11vcf1fq5q6pyia0nrjmh-koka-2.1.2/bin
Libraries installed in:
/nix/store/xa1bkdl3y3l11vcf1fq5q6pyia0nrjmh-koka-2.1.2/lib/ghc-8.10.4/x86_64-osx-ghc-8.10.4/koka-2.1.2
Dynamic Libraries installed in:
/nix/store/xa1bkdl3y3l11vcf1fq5q6pyia0nrjmh-koka-2.1.2/lib/ghc-8.10.4/x86_64-osx-ghc-8.10.4
Private executables installed in:
/nix/store/xa1bkdl3y3l11vcf1fq5q6pyia0nrjmh-koka-2.1.2/libexec/x86_64-osx-ghc-8.10.4/koka-2.1.2
Data files installed in:
/nix/store/xa1bkdl3y3l11vcf1fq5q6pyia0nrjmh-koka-2.1.2/share/x86_64-osx-ghc-8.10.4/koka-2.1.2
Documentation installed in:
/nix/store/xa1bkdl3y3l11vcf1fq5q6pyia0nrjmh-koka-2.1.2/share/doc/x86_64-osx-ghc-8.10.4/koka-2.1.2
Configuration files installed in:
/nix/store/xa1bkdl3y3l11vcf1fq5q6pyia0nrjmh-koka-2.1.2/etc
Using alex version 3.2.6 found on system at:
/nix/store/q491m6y2jbykghfhc5p6fwm6029aid2n-alex-3.2.6/bin/alex
Using ar found on system at:
/nix/store/z7x7jnwc9avhrdprnk0iy9kan9s0v0qg-cctools-binutils-darwin-949.0.1/bin/ar
No c2hs found
No cpphs found
No doctest found
Using gcc version 4.2.1 given by user at:
/nix/store/4akw6n9a2f1cxwcwihzf1diblbyzhkkc-clang-wrapper-7.1.0/bin/clang
Using ghc version 8.10.4 found on system at:
/nix/store/6sqrxr2dmn1zrya0gyp22hy2s34v5a44-ghc-8.10.4/bin/ghc
Using ghc-pkg version 8.10.4 found on system at:
/nix/store/6sqrxr2dmn1zrya0gyp22hy2s34v5a44-ghc-8.10.4/bin/ghc-pkg
No ghcjs found
No ghcjs-pkg found
No greencard found
Using haddock version 2.24.0 found on system at:
/nix/store/6sqrxr2dmn1zrya0gyp22hy2s34v5a44-ghc-8.10.4/bin/haddock
No happy found
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.68 found on system at:
/nix/store/6sqrxr2dmn1zrya0gyp22hy2s34v5a44-ghc-8.10.4/bin/hpc
Using hsc2hs version 0.68.7 found on system at:
/nix/store/6sqrxr2dmn1zrya0gyp22hy2s34v5a44-ghc-8.10.4/bin/hsc2hs
No hscolour found
No jhc found
Using ld found on system at:
/nix/store/1ix8gk032y489apbgfvs3lypij1i0jbw-cctools-binutils-darwin-wrapper-949.0.1/bin/ld
No pkg-config found
Using runghc version 8.10.4 found on system at:
/nix/store/6sqrxr2dmn1zrya0gyp22hy2s34v5a44-ghc-8.10.4/bin/runghc
Using strip found on system at:
/nix/store/z7x7jnwc9avhrdprnk0iy9kan9s0v0qg-cctools-binutils-darwin-949.0.1/bin/strip
Using tar found on system at:
/nix/store/ph0fljkdnf80x75kq80y4vlrrrabzdc0-gnutar-1.34/bin/tar
No uhc found
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Preprocessing executable 'koka' for koka-2.1.2..
Building executable 'koka' for koka-2.1.2..
[ 1 of 97] Compiling Common.Id        ( src/Common/Id.hs, dist/build/koka/koka-tmp/Common/Id.o )
[ 2 of 97] Compiling Common.IdMap     ( src/Common/IdMap.hs, dist/build/koka/koka-tmp/Common/IdMap.o )
[ 3 of 97] Compiling Common.IdSet     ( src/Common/IdSet.hs, dist/build/koka/koka-tmp/Common/IdSet.o )
[ 4 of 97] Compiling Common.ResumeKind ( src/Common/ResumeKind.hs, dist/build/koka/koka-tmp/Common/ResumeKind.o )
[ 5 of 97] Compiling Common.Syntax    ( src/Common/Syntax.hs, dist/build/koka/koka-tmp/Common/Syntax.o )
[ 6 of 97] Compiling Lib.Scc          ( src/Lib/Scc.hs, dist/build/koka/koka-tmp/Lib/Scc.o )
[ 7 of 97] Compiling Paths_koka       ( dist/build/koka/autogen/Paths_koka.hs, dist/build/koka/koka-tmp/Paths_koka.o )
[ 8 of 97] Compiling Platform.Config  ( src/Platform/cpp/Platform/Config.hs, dist/build/koka/koka-tmp/Platform/Config.o )
[ 9 of 97] Compiling Platform.GetOptions ( src/Platform/cpp/Platform/GetOptions.hs, dist/build/koka/koka-tmp/Platform/GetOptions.o )
[10 of 97] Compiling Platform.Runtime ( src/Platform/cpp/Platform/Runtime.hs, dist/build/koka/koka-tmp/Platform/Runtime.o )
[11 of 97] Compiling Platform.ReadLine ( src/Platform/cpp/Platform/ReadLine.hs, dist/build/koka/koka-tmp/Platform/ReadLine.o )
[12 of 97] Compiling Platform.Filetime ( src/Platform/cpp/Platform/Filetime.hs, dist/build/koka/koka-tmp/Platform/Filetime.o )
[13 of 97] Compiling Platform.Console ( src/Platform/cpp/Platform/Console.hs, dist/build/koka/koka-tmp/Platform/Console.o )
impure path `/private/tmp/nix-build-koka-2.1.2.drv-0/ghc33357_0/ghc_68.filelist' used in link

[;1m<no location info>: [;1m[31merror:[0m[0m[;1m[0m[0m[;1m
    `ld' failed in phase `Merge objects'. (Exit code: 1)[0m[0m
[0m[0m[0m[14 of 97] Compiling Lib.JSON         ( src/Lib/JSON.hs, dist/build/koka/koka-tmp/Lib/JSON.o )
[15 of 97] Compiling Common.Failure   ( src/Common/Failure.hs, dist/build/koka/koka-tmp/Common/Failure.o )
[16 of 97] Compiling Common.Range     ( src/Common/Range.hs, dist/build/koka/koka-tmp/Common/Range.o )
[17 of 97] Compiling Platform.Var     ( src/Platform/cpp/Platform/Var.hs, dist/build/koka/koka-tmp/Platform/Var.o )
```

**Comment by sternenseemann** [comment]
ofborg suceeds <https://logs.nix.ci/?key=nixos/nixpkgs.123574&attempt_id=d361ab7d-65d1-4e4a-91a1-7f39aeb3b88b>

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 123574` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>koka</li>
  </ul>
</details>

**Pull request closed without merging**
