### PR TITLE
kodi.packages.youtube: 7.0.1 -> 7.0.2.2

### PR DESCRIPTION
**Pull request by pks-t**
## Description of changes

Changelog: https://github.com/anxdpanic/plugin.video.youtube/blob/v7.0.2.2/changelog.txt

Note that the update also requires a change to the source URL, which now
points to the [official GitHub repository of the addon](https://github.com/CastagnaIT/plugin.video.netflix). This is required
because the update version is not availbale via the official addon
repository. The updated source can be cross-checked via the [official addon page](https://kodi.tv/addons/nexus/plugin.video.youtube/).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
oh did they drop this addon from the officially included repo finally?

should we use is `fetchFromGitHub`?

**Comment by pks-t** [comment]
On Fri, Oct 20, 2023 at 02:28:28PM -0700, Aaron Andersen wrote:
> oh did they drop this addon from the officially included repo finally?

I'm not really sure what the background story here is. At the very least
the official repository doesn't have an up-to-date version for the Nexus
branch anymore. I couldn't find a particular reason why that is in their
issue tracker or anywhere else though.

For me though, the official 7.0.1 version doesn't work nowadays anymore,
whereas the 7.0.2.2 version does. So ultimately, I feel like we need to
adapt regardless of the background story if the addon should continue to
be useful.

> should we use is `fetchFromGitHub`?

The reason why I didn't use `fetchFromGitHub` is mostly that I'm instead
using the artifacts attached to the release themselves, and to the best
of my knowledge the helper function has no way to access these. That
being said, the only difference between the official release artifact
and `fetchFromGitHub` is an extraneous README.md file when using the
latter.

Let me know what you think -- I'm happy to convert to `fetchFromGitHub`
if you think it's preferable.

**Comment by aanderse** [comment]
the GitHub fetcher is preferred generally because it is more efficient so if it works the same we should use that
don't forget to remove the update script in passthru

thank you!

**Comment by pks-t** [comment]
On Sat, Oct 21, 2023 at 05:08:02AM -0700, Aaron Andersen wrote:
> the GitHub fetcher is preferred generally because it is more efficient
> so if it works the same we should use that don't forget to remove the
> update script in passthru

Fair enough, thanks for the explanation. I've updated the pull request
accordingly.

**Review by aanderse — APPROVED** [review]
thank you so much for your contribution!

**Pull request merged**
