### PR TITLE
python3: 3.8 -> 3.9

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

Testing how much breaks.

https://hydra.nixos.org/eval/1639525

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
- nixos test driver needs newer astroid https://github.com/PyCQA/astroid/pull/872#issuecomment-753887145

**Comment by mweinelt** [comment]
>     * nixos test driver needs newer astroid [PyCQA/astroid#872 (comment)](https://github.com/PyCQA/astroid/pull/872#issuecomment-753887145)

Is #112908 enough to give this another try?

**Comment by FRidh** [comment]
Yes, I think so.

**Comment by FRidh** [comment]
Force pushed to `python-unstable` so this PR is now invalid.

**Pull request closed without merging**
