### PR TITLE
gradle: 6.8.1 -> 6.8.3

### PR DESCRIPTION
**Pull request by mstrangfeld**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 114088` at 072018e8 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/ce4721a11e8ff6a42604045e8b3449e5">gradle</a></li> (gradle_6)</li>
    <li><a href="https://gist.github.com/c50d9f8ea6219079d79e22584f49dbcb">gscan2pdf</a></li></li>
    <li><a href="https://gist.github.com/987462dd6fd5fe1899bd9f9f58470f2b">impressive</a></li></li>
    <li><a href="https://gist.github.com/2ed18620b4229e65253c56b993ede112">jadx</a></li></li>
    <li><a href="https://gist.github.com/2946eae84db17caf1c23cfaa7f7edad2">ma1sd</a></li></li>
    <li><a href="https://gist.github.com/bb016a2e4e358c08a18ff62dcf55109f">mucommander</a></li></li>
    <li><a href="https://gist.github.com/8d44bead83c2d37944fafbdfdb714409">mxisd</a></li></li>
    <li><a href="https://gist.github.com/c7fdbe36756606cda2e24127315bf0b7">pdftk</a></li></li>
  </ul>
</details>
<details>
  <summary>3 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/fixup-phase.md">fixup-phase</a>

`fixupPhase` should not be overridden, use `postFixup` instead.

Near pkgs/development/tools/build-managers/gradle/default.nix:20:5:
```
   |
20 |     fixupPhase = if (!stdenv.isLinux) then ":" else
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/tools/build-managers/gradle/default.nix:38:5:
```
   |
38 |     meta = {
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/tools/build-managers/gradle/default.nix:9:5:
```
  |
9 |     installPhase = ''
  |     ^
```
</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Maybe we should add some code owners to gradle so that someone is pinged when it is updated.

ping @lorenzleutgeb

**Comment by lorenzleutgeb** [comment]
LGTM

**Comment by mstrangfeld** [comment]
Should we add code owners or maintainers?
Also, I would be willing to have a look at this as I use this derivation on a daily basis.

**Comment by SuperSandro2000** [comment]
> Should we add code owners or maintainers?
> Also, I would be willing to have a look at this as I use this derivation on a daily basis.

If there is no maintainers set then we should add that first.

**Pull request merged**
