### PR TITLE
linux: Add 4.2.0 (backport to release-15.09)

### PR DESCRIPTION
**Pull request by ktosiek**
As there's already 4.2.0-rc5 in 15.09, I think the stable version should be available too.
This patch is a cherry-pick from master.

### CODE REVIEW

**Comment by domenkozar** [comment]
We'll also have to fix `linuxPackages_4_2.lttng-modules` and `linuxPackages_4_2.openafsClient`

**Comment by ktosiek** [comment]
For lttng bumping it to 2.6.3 (from our current "somewhere after 2.6.1") should fix building on 4.2. If it does, should I add this to this PR, and then open another one against master? Or should I start with master?

**Comment by domenkozar** [comment]
you can add it to this PR and one for master

**Comment by domenkozar** [comment]
@ktosiek more kernel module failures http://hydra.nixos.org/eval/1221352

**Comment by domenkozar** [comment]
(probably just need cherry-picking from master)

**Comment by domenkozar** [comment]
Yup d35d9910281e6a3f7fb58043a3e47a250cf70f7b, done.

**Comment by edolstra** [comment]
Maybe you can remove `linux-testing.nix`, since it's obsoleted by this PR?

**Pull request merged**
