### PR TITLE
linkFarmFromDrvs: Add a trivial builder to create a linkFarm from a list of derivations

### PR DESCRIPTION
**Pull request by cdepillabout**
###### Motivation for this change

This PR adds a trivial builder called `linkFarmFromDrvs`.  It is similar to `linkFarm`, but it is a easier to use if you just want directory with a bunch of links to derivations, but you're fine with links just being the name of the derivation.

We use this in a couple places in our nix code-base at work, and we thought it could be helpful to other nix users.

Here's an example of using it:

```console
$ nix-build -E 'with (import ./. {}); linkFarmFromDrvs "example" [ pkgs.hello pkgs.gcc pkgs.xterm ]'
...
/nix/store/hsi98apxc80l8r3lpi13hzc3lk8i8623-example
$ ls -l result/
lrwxrwxrwx 1 root root 61 Jan  1  1970 gcc-wrapper-8.3.0 -> /nix/store/7hzmz83nv8khpwsk858yaac7y3idh0a7-gcc-wrapper-8.3.0
lrwxrwxrwx 1 root root 54 Jan  1  1970 hello-2.10 -> /nix/store/rr3y0c6zyk7kjjl8y19s4lsrhn4aiq1z-hello-2.10
lrwxrwxrwx 1 root root 53 Jan  1  1970 xterm-348 -> /nix/store/y0cz7w39v4sb743mix5qps3kc2ra9b72-xterm-348
```

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by edolstra** [comment]
What is a "link farm"?

**Comment by cdepillabout** [comment]
@edolstra Thanks for taking a look at this.

`linkFarm` is the name of one of the trivial builders currently in nixpkgs:

https://github.com/NixOS/nixpkgs/blob/6b11080f9f88c9cc3d0037fe73720bc434e93542/pkgs/build-support/trivial-builders.nix#L294-L312

I'm using `linkFarm` in the title and description of this PR to describe the output of a derivation created with the `linkFarm` function.  Although I agree that this is not a widely-used term and I'd be happy to change it if it is confusing.

This PR adds an additional helper function called `linkFarmFromDrvs` that wraps `linkFarm` and makes it a little easier to use in the common case.

**Comment by Profpatsch** [comment]
What’s the difference to `symlinkJoin "name" { paths = [ drv1 drv2 … ]; }`?

**Comment by cdepillabout** [comment]
@Profpatsch `linkFarmFromDrvs` (and the similar `linkFarm` function), just create a bunch of symlinks in a directory:

```console
$ nix-build -E 'with import ./. {}; linkFarmFromDrvs "example" [ pkgs.hello pkgs.gcc pkgs.xterm ]'
...
/nix/store/hsi98apxc80l8r3lpi13hzc3lk8i8623-example
$ tree /nix/store/hsi98apxc80l8r3lpi13hzc3lk8i8623-example
/nix/store/hsi98apxc80l8r3lpi13hzc3lk8i8623-example
├── gcc-wrapper-8.3.0 -> /nix/store/7hzmz83nv8khpwsk858yaac7y3idh0a7-gcc-wrapper-8.3.0
├── hello-2.10 -> /nix/store/rr3y0c6zyk7kjjl8y19s4lsrhn4aiq1z-hello-2.10
└── xterm-348 -> /nix/store/y0cz7w39v4sb743mix5qps3kc2ra9b72-xterm-348
```

You can see that the directory `/nix/store/hsi98apxc80l8r3lpi13hzc3lk8i8623-example` just contains a bunch of symlinks to other derivations.

However, `symlinkJoin` actually replicates the directory structure from the original derivations:

```console
$ nix-build -E 'with import <nixpkgs> {}; symlinkJoin { name = "example"; paths = [ pkgs.hello pkgs.stack ]; }'
/nix/store/wh0nkyg2qklrlq74z17fpy6yqfbdxc4m-example
$ tree /nix/store/wh0nkyg2qklrlq74z17fpy6yqfbdxc4m-example
/nix/store/wh0nkyg2qklrlq74z17fpy6yqfbdxc4m-example
├── bin
│   ├── hello -> /nix/store/qy93dp4a3rqyn2mz63fbxjg228hffwyw-hello-2.10/bin/hello
│   └── stack -> /nix/store/6lzdpxshx78281vy056lbk553ijsdr44-stack-2.1.3.1/bin/stack
└── share
    ├── bash-completion
    │   └── completions
    │       └── stack -> /nix/store/6lzdpxshx78281vy056lbk553ijsdr44-stack-2.1.3.1/share/bash-completion/completions/stack
    ├── fish
    │   └── vendor_completions.d
    │       └── stack.fish -> /nix/store/6lzdpxshx78281vy056lbk553ijsdr44-stack-2.1.3.1/share/fish/vendor_completions.d/stack.fish
    ├── info
    │   └── hello.info -> /nix/store/qy93dp4a3rqyn2mz63fbxjg228hffwyw-hello-2.10/share/info/hello.info
...
```

You can see here that `symlinkJoin` tries to replicate the directory structure from the input derivations, while `linkFarmFromDrvs` just creates a link directory with symlinks.

------------------------------------------

We use `linkFarmFromDrvs` a bunch of places in our code base at work.  Normally in CI when we want to test that a bunch of loosely-related derivations (normally tests) are able to be built, but we rarely access the actual output of the derivations.

**Comment by Profpatsch** [comment]
Then +1 to that change, but let’s move these three functions together and have an overview of their differences.

**Comment by cdepillabout** [comment]
@Profpatsch Reorganizing the functions is a good idea.

I just added a new commit that reorders the functions in this file, adds an example output for `symlinkJoin` and `linkFarm`, and adds some documentation that explains the difference between `symlinkJoin` and `linkFarm`.

I think this should be ready for a final review and hopefully a merge-in.

**Review by Profpatsch — COMMENTED** [review]
Fantastic! LGTM

**Pull request merged**
