### PR TITLE
osslsigncode: 2.3 -> 2.5

### PR DESCRIPTION
**Pull request by charles-dyfis-net**
###### Description of changes

Per https://github.com/mtrojnar/osslsigncode/releases/tag/2.5 --

> ###### 2.5 (2022.08.12)
> - fixed the Unix executable install path
> - fixed the hardcoded "pkcs11" engine id
> - fixed building with MinGW
> - fixed testing with the python3 distributed with Ubuntu 18.04
> 
> ###### 2.4 (2022.08.02)
> - migrated the build system from GNU Autoconf to CMake
> - added the "-h" option to set the cryptographic hash function for the "attach -signature" and "add" commands
> - set the default hash function to "sha256"
> - added the "attach-signature" option to compute and compare the leaf certificate hash for the "add" command
> - renamed the "-st" option "-time" (the old name is accepted for compatibility)
> - updated the "-time" option to also set explicit verification time
> - added the "-ignore-timestamp" option to disable timestamp server signature verification
> - removed the "-timestamp-expiration" option
> - fixed several bugs
> - updated the included documentation
> - enabled additional compiler/linker hardening options
> - added CI based on GitHub Actions

Patch incorporated to fix build on darwin submitted upstream as mtrojnar/osslsigncode#246.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
Please open a pull request with the fix in osslsigncode repo and use link to the patch instead of adding patch file to the nixpkgs tree.

**Comment by charles-dyfis-net** [comment]
> Please open a pull request with the fix in the osslsigncode repo and use link to the patch instead of adding patch file to the nixpkgs tree.

Unfortunately, a diff against master and a diff against the 2.5 release aren't quite compatible, so this wouldn't apply.

**Comment by charles-dyfis-net** [comment]
...I suppose I could fork the upstream repo and create my own 2.5-maint branch; would that be better?

**Comment by prusnak** [comment]
I guess let's leave that as it is and hopefully we can drop the patch once 2.6 is released (and contains the fix).

**Comment by charles-dyfis-net** [comment]
@prusnak, I added d742e50b2f36832c88699bb71bb6362f8baf5582 to the PR per your feedback, with the intent to squash it before merge. There's a separate branch in my personal repo pointing to the same commit (https://github.com/charles-dyfis-net/osslsigncode/commit/issue-246-v1), so even if upstream requires changes to the patch before it goes to main, the link will remain valid.

**Pull request merged**
