### PR TITLE
Added JDK dependency to libguestfs

### PR DESCRIPTION
**Pull request by nightkr**
###### Motivation for this change

The current libguestfs package doesn't build, unless you patch it to either include the JDK dependency, or to disable the Java bindings.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Ideally the language bindings should probably be managed by flags, so that they can be enabled/disabled per language, but at least this gets the package buildable.

### CODE REVIEW

**Comment by edolstra** [comment]
Disabling Java bindings seems vastly preferable to adding a dependency on the JDK.

**Comment by teozkr** [comment]
Fair enough. I'll add an option to disable Java bindings later tonight.

**Comment by teozkr** [comment]
@edolstra Does this look better to you?

**Comment by edolstra** [comment]
Thanks!

**Pull request merged**
