### PR TITLE
 nixos/dokuwiki: add caddy webserver support

### PR DESCRIPTION
**Pull request by onny**
###### Motivation for this change

To be able to combine DokuWiki with other modules that are using Caddy. This concept is unfluenced by [this pull request](https://github.com/NixOS/nixpkgs/pull/84446).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
@1000101: It seems all tests have passed now, do you think this is good now?

**Comment by 1000101** [comment]
> @1000101: It seems all tests have passed now, do you think this is good now?

Good job! I'm going to be honest as I don't want this PR to become stale - I'm currently in a rush and I'll have no access to my PC for next few weeks, so if anyone feels like testing/reviewing this, I'd be more than grateful. Otherwise, it'll take me some time to test this properly.

**Comment by happysalada** [comment]
Sorry to be adding more work for you.
Caddy has now support for a virtualHosts attribute in order to not override other configs.
When you have a moment, could you use that attribute ? (it would enable people to use caddy for other things)

**Comment by onny** [comment]
> Sorry to be adding more work for you.
> Caddy has now support for a virtualHosts attribute in order to not override other configs.
> When you have a moment, could you use that attribute ? (it would enable people to use caddy for other things)

Thanks for the info and thank you for this important work! I rebased and updated my PR. It now includes:

- Support for Nginx and Caddy as webserver
- Updated test script
- Updated release notes

**Comment by happysalada** [comment]
The diff looks fine.
Was there some formatting changes included in there ? Perhaps you have an automated formatter ? Or were the formatting changes just the result of the refactoring. That one commit is a little intense.
Just want to confirm.

**Comment by onny** [comment]
> The diff looks fine.
> Was there some formatting changes included in there ? Perhaps you have an automated formatter ? Or were the formatting changes just the result of the refactoring. That one commit is a little intense.
> Just want to confirm.

I used the concept and module template from the Wordpress PR here https://github.com/NixOS/nixpkgs/pull/84446
It already supported multiple web servers, so I adapted it

**Comment by happysalada** [comment]
The diff is harder to review properly, but it looks good.

**Pull request merged**
