### PR TITLE
awesome: 3.5.9 -> 4.0

### PR DESCRIPTION
**Pull request by rasendubi**
###### Motivation for this change
[Awesome wm 4.0 released](https://awesomewm.org/apidoc/documentation/89-NEWS.md.html)

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I'm currently running awesome-4.0 as my window manager. \o/

### CODE REVIEW

**Comment by grahamc** [comment]
1. Is there a really good reason to keep 3.4 around?
2. Is there a really good reason to keep 3.5 around?
3. Is there a really good reason to expose an attribute named `awesome-4-0`?

**Comment by rasendubi** [comment]
awesome-3.4, awesome-3.5 and awesome-4.0 are not compatible, which means people must adapt their configs to the new version. That's why keeping 3.5 is reasonable.

As for 3.4, there still might be users who haven't migrated to 3.5. (Though, I don't know any usage statistics.)

As for naming, I've just followed the pattern—I'm fine with renaming it to `awesome-4_0` if you like that.

**Comment by grahamc** [comment]
Alexey Shmalko <notifications@github.com> writes:

> awesome-3.4, awesome-3.5 and awesome-4.0 are not compatible, which
> means people must adapt their configs to the new version. That's why
> keeping 3.5 is reasonable.

Sounds good.
>
> As for 3.4, there still might be users who haven't migrated to 3.5.
> (Though, I don't know any usage statistics.)

I think we should probably drop 3.4, but am not a user. I suspect it is
old enough to not be receiving patches or updates, and users should be
updating anyway.
>
> As for naming, I've just followed the pattern—I'm fine with renaming
> it to `awesome-4_0` if you like that.

Makes sense, but if the answer was "just in case people want the old
ones", I'd recommend renaming to just "awesome". Since the versions are
very incompatible, we can/should keep one around for at least a bit I
guess.

**Comment by rasendubi** [comment]
I would like to keep both `awesome-4_0` and `awesome` as an alias. This allows people to request a specific version, so they are not affected once awesome-4.1 is released. (Which could come as a surprise to them and break their system.)

> I think we should probably drop 3.4, but am not a user. I suspect it is
old enough to not be receiving patches or updates, and users should be
updating anyway.

Agree.

**Comment by rasendubi** [comment]
ping. have I addressed all the comments?

**Comment by flosse** [comment]
Unfortunately there's now an error: https://github.com/awesomeWM/awesome/issues/1348

**Pull request merged**
