### PR TITLE
rustracer: 2.1.22 -> 2.1.27

### LINKED ISSUE #70948: request: update rustracer 2.1.22 --> 2.1.27
Current version of rustracer 2.1.22 does not build with latest stable rust (see https://github.com/racer-rust/racer/issues/1058). Please update rustracer to the newest version 2.1.27

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

Fixes failing build on master.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Resolves: #70948

### CODE REVIEW

**Comment by danieldk** [comment]
Added a second commit that fixes the default `RUST_SRC_PATH` (which was empty).

**Review by risicle — APPROVED** [review]
`nix-review` happy for me, macos 10.13, non-nixos linux x86_64

**Review by wykurz — APPROVED** [review]
Works for me.

**Comment by danieldk** [comment]
@Mic92 I think you made the latest big changes to this derivation, so I thought it would be good to ping you. Would be nice if we could unbreak this package (IIRC it is also broken on 19.09).

**Comment by Mic92** [comment]
We actually reverted the rustc backport in 19.03 again. But this fix should be also backported in case we try it another time.

**Pull request merged**
