### PR TITLE
skanlite: 2.0.1 -> 2.2.0

### PR DESCRIPTION
**Pull request by freezeboy**
###### Motivation for this change

Software update + fixes build
ZHF: #97479 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
The commit message still says `rpm-ostree`

**Comment by risicle** [comment]
Also.. `skanlite`'s build isn't failing. Did you mean to tag this for ZHF?

**Comment by freezeboy** [comment]
https://hydra.nixos.org/build/127854510

**Comment by risicle** [comment]
Again, merging to `master` isn't going to fix a problem in `release-20.09`. This is a fine PR for a general bump, but backporting it isn't going to help get `release-20.09` building again. Figuring out what fixed `skanlite` in `master` will, though.

**Comment by jonringer** [comment]
@GrahamcOfBorg eval

**Pull request merged**
