### PR TITLE
gql: add Security framework dependency on darwin

### PR DESCRIPTION
**Pull request by tjni**
## Description of changes

This is broken in staging-next (https://github.com/NixOS/nixpkgs/pull/245935). Related to libgit2 being updated from 1.6.4 to 1.7.0.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by figsoda** [comment]
I opened #247408 to add back libgit2 1.6 like we did for 1.5 and 1.3, so packages like this can still link to libgit2, and `Security` should no longer be required

**Comment by tjni** [comment]
Got it, do you know why this is happening? I don't have a good instinct about how transitive dependencies are or are not propagated.

**Comment by figsoda** [comment]
The `libgit2-sys` crate has opted to only work with one minor release of libgit2
https://github.com/rust-lang/git2-rs/blob/f35a3bbe1f4d60f4c2ed9fc3db7f490dbcde498d/libgit2-sys/build.rs#L17

**Comment by tjni** [comment]
Wow, what a footgun. Can you also revert my change in https://github.com/NixOS/nixpkgs/pull/247387?

**Comment by figsoda** [comment]
> Can you also revert my change in #247387?

:+1:,  done in #247408

**Pull request closed without merging**
