### PR TITLE
rtmidi: 4.0.0 -> 5.0.0

### PR DESCRIPTION
**Pull request by OPNA2608**
###### Motivation for this change
After >2 years, finally a new release, and it obsoletes our patches too!
https://github.com/thestk/rtmidi/releases/tag/5.0.0

I have only tested building RtMidi itself, no reverse dependencies yet.

See #146836 for RtAudio version of this PR.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by OPNA2608** [comment]
Result of `nixpkgs-review pr 146864` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>milkytracker</li>
  </ul>
</details>
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>bambootracker</li>
    <li>csound-qt</li>
    <li>giada</li>
    <li>octavePackages.audio</li>
    <li>opl3bankeditor</li>
    <li>opn2bankeditor</li>
    <li>pianobooster</li>
    <li>polyphone</li>
    <li>ptcollab</li>
    <li>rtmidi</li>
    <li>vcv-rack</li>
    <li>zrythm</li>
  </ul>
</details>

---

- [JACK support is currently broken on macOS](https://github.com/thestk/rtmidi/issues/275) in this release, disabled it for now. Fixing it *might* be as simple as replacing `pthread_yield` in [RtMidi.cpp](https://github.com/thestk/rtmidi/blob/84a99422a3faf1ab417fe71c0903a48debb9376a/RtMidi.cpp#L3611) with `pthread_yield_np`, can't test is rn.

- aarch64-darwin is broken since https://github.com/thestk/rtmidi/pull/218. I've left a comment there, hopefully the PR author has the time to resolve it.

- `milkytracker` is [incompatible with this new version](https://github.com/milkytracker/MilkyTracker/issues/262). Should I remove MIDI support from it? Stall this PR until upstream finds a fix? Keep an `rtmidi_4` package around?
  CC milkytracker maintainer @Zoomulator

**Comment by OPNA2608** [comment]
- Patching `pthread_yield` to `pthread_yield_np` on Darwin fixes compilation problem number 1 and looks like it should work on paper, cannot test as I don't have JACK configured on a macOS system.
- Fixed aarch64-darwin error by improving the problematic preprocessor check.

**Comment by OPNA2608** [comment]
Marking for 21.11 backport because the accompanying rtaudio update has already been merged before the branch-off, and after ~2 years of no new releases for either project having one of them stuck on an older version now doesn't make much sense to me.

**Comment by OPNA2608** [comment]
Result of `nixpkgs-review pr 146864` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>bambootracker</li>
    <li>csound-qt</li>
    <li>giada</li>
    <li>milkytracker</li>
    <li>octavePackages.audio</li>
    <li>opl3bankeditor</li>
    <li>opn2bankeditor</li>
    <li>pianobooster</li>
    <li>polyphone</li>
    <li>ptcollab</li>
    <li>rtmidi</li>
    <li>vcv-rack</li>
    <li>zrythm</li>
  </ul>
</details>

Tested MIDI-IN via BambooTracker, works fine.

---

Result of `nixpkgs-review pr 146864` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>giada</li>
    <li>ptcollab</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>bambootracker</li>
    <li>opl3bankeditor</li>
    <li>opn2bankeditor</li>
    <li>rtmidi</li>
  </ul>
</details>

---

CC @tomberek since you merged the related rtaudio bump https://github.com/NixOS/nixpkgs/pull/146836 before the branch-off, could you take a look at this as well please?

**Comment by tomberek** [comment]
Looks like this fell off my radar. Is this still a thing.

**Comment by magnetophon** [comment]
@tomberek Nope: https://github.com/NixOS/nixpkgs/pull/146836

**Comment by OPNA2608** [comment]
Yes it's still a thing, #146836 is a different library.

**Comment by magnetophon** [comment]
Oh, sorry, that was sloppy of me!

**Comment by OPNA2608** [comment]
Resolved merge conflicts. Fetching required patches from upstream PRs now, nixpkgs-review on x86_64-darwin still passes.

**Review by magnetophon — APPROVED** [review]
LGTM, but I'm not sure I've tested sufficiently:
I've built and ran BambooTracker, and was able to get sound out of it, but IDK if the functionality that is added by rtmidi was tested by doing that.

**Comment by OPNA2608** [comment]
My MIDI keyboard is currently stashed away, but I sent a MIDI file to BambooTracker via `aplaymidi` and it was received just fine.

**Comment by magnetophon** [comment]
I was abe to build the new zrythm using this: https://github.com/NixOS/nixpkgs/pull/157299

**Pull request merged**
