### PR TITLE
[Backport release-24.05] hyprland: 0.40.0-unstable-2024-05-05 -> 0.41.1; hyprwayland-scanner: 0.3.4 -> 0.3.10; hyprlandPlugins.hy3: 0.40.0 -> 0.41.0; hyprutils: init at 0.1.2; hyprlandPlugins: init upstream hyprland-plugins at 0.41.1, hy3: 0.41.0 -> 0.41.1

### PR DESCRIPTION
**Pull request by fufexan**
## Description of changes

Manual backport for https://github.com/NixOS/nixpkgs/pull/319131, https://github.com/NixOS/nixpkgs/pull/321069, https://github.com/NixOS/nixpkgs/pull/309255, https://github.com/NixOS/nixpkgs/pull/321575.
Also backported `hyprcursor-1.9`, otherwise Hyprland wouldn't build.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by drupol — APPROVED** [review]

**Review by JohnRTitor — APPROVED** [review]
Passes my eyeball test, but CI seems to report an error, not a hard fail though.

**Comment by wineee** [comment]
CI fail caused by https://github.com/NixOS/nixpkgs/pull/317959 ， it not backport to release-24.05， cause
 meta mismatch
```
meta = {
          homepage = "https://github.com/hyprwm/hyprwayland-scanner";
    -     description = "Hyprland version of wayland-scanner in and for C++";
    +-    description = "A Hyprland version of wayland-scanner in and for C++";
     -    license = licenses.bsd3;
     -    maintainers = with maintainers; [ fufexan ];
    ++    description = "Hyprland version of wayland-scanner in and for C++";
     +    changelog = "[https://github.com/hyprwm/hyprwayland-scanner/releases/tag/${finalAttrs.version}](https://github.com/hyprwm/hyprwayland-scanner/releases/tag/$%7BfinalAttrs.version%7D)";
     +    license = lib.licenses.bsd3;
     +    maintainers = with lib.maintainers; [ fufexan ];
```

**Comment by JohnRTitor** [comment]
Could you do a partial backport of the conflicting commit? (of only the Hyprland package)

Else further backports to 24.05 will fail as well.

**Comment by fufexan** [comment]
Ok, I don't know what CI wants me to do. Is there a commit I'm missing?

**Comment by donovanglover** [comment]
Should be able to fix by removing the meta.description change in https://github.com/NixOS/nixpkgs/pull/320347/commits/8e4fa0d94326041d46a9f39cb9faea2023f268f0#diff-be17458e33be77de31b34f9517f70d41b45b6675673dd0174607d8aacc424c48L167

**Comment by JohnRTitor** [comment]
> @JohnRTitor `hyprutils` have been updated to [0.1.3](https://github.com/hyprwm/hyprutils/releases) a few hours ago

Sure #321069

**Review by donovanglover — APPROVED** [review]
LGTM

**Comment by wineee** [comment]
hy3-0.41.0  failed to build, https://logs.ofborg.org/?key=nixos/nixpkgs.320347&attempt_id=86365f30-bb52-481c-a60e-612ff1d2c80e
```
[ 14%] Building CXX object CMakeFiles/hy3.dir/src/dispatchers.cpp.o
[ 28%] Building CXX object CMakeFiles/hy3.dir/src/main.cpp.o
[ 42%] Building CXX object CMakeFiles/hy3.dir/src/Hy3Layout.cpp.o
[ 71%] Building CXX object CMakeFiles/hy3.dir/src/SelectionHook.cpp.o
[ 71%] Building CXX object CMakeFiles/hy3.dir/src/Hy3Node.cpp.o
[ 85%] Building CXX object CMakeFiles/hy3.dir/src/TabGroup.cpp.o
/build/source/src/TabGroup.cpp:14:10: fatal error: src/helpers/memory/SharedPtr.hpp: No such file or directory
   14 | #include "src/helpers/memory/SharedPtr.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by donovanglover** [comment]
Good catch. Upstream issue: https://github.com/outfoxxed/hy3/issues/120

**Review by JohnRTitor — DISMISSED** [review]
Please include the #321069 backport

And this is blocked until there is a 41.1 release of hy3

**Comment by JohnRTitor** [comment]
I feel like #309255 should be included as well since v0.40 changed the socket address.

**Comment by JohnRTitor** [comment]
I have removed the blockers please cherry-pick #321575.

**Comment by JohnRTitor** [comment]
Result of `nixpkgs-review pr 320347` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>26 packages built:</summary>
  <ul>
    <li>grimblast</li>
    <li>hdrop</li>
    <li>hyprcursor</li>
    <li>hyprcursor.dev</li>
    <li>hyprcursor.lib</li>
    <li>hyprland</li>
    <li>hyprland.dev</li>
    <li>hyprland.man</li>
    <li>hyprlandPlugins.borders-plus-plus</li>
    <li>hyprlandPlugins.csgo-vulkan-fix</li>
    <li>hyprlandPlugins.hy3</li>
    <li>hyprlandPlugins.hyprbars</li>
    <li>hyprlandPlugins.hyprexpo</li>
    <li>hyprlandPlugins.hyprtrails</li>
    <li>hyprlandPlugins.hyprwinwrap</li>
    <li>hyprpaper</li>
    <li>hyprshade</li>
    <li>hyprshade.dist</li>
    <li>hyprshot</li>
    <li>hyprutils</li>
    <li>hyprutils.dev</li>
    <li>hyprwayland-scanner</li>
    <li>nwg-panel</li>
    <li>nwg-panel.dist</li>
    <li>waybar</li>
    <li>xdg-desktop-portal-hyprland</li>
  </ul>
</details>

**Pull request merged**
