### PR TITLE
lilypond-with-fonts: fix lilypond not finding its libraries

### LINKED ISSUE #140152: lilypond-with-fonts cannot find Scheme files
### Describe the bug
The package `lilypond-with-fonts` cannot find its Scheme files.

### Steps To Reproduce
1. `nix-shell -p lilypond-with-fonts --run lilypond`
This prints the error message
```
GNU LilyPond 2.22.1
ERROR: In procedure primitive-load-path:
ERROR: Unable to find file "lily.scm" in load path
```

### Expected behavior
It should print a help message, as with `nix-shell -p lilypond --run lilypond`.

### Additional context
There used to be a similar (now solved) issue with the main `lilypond` package before: https://github.com/NixOS/nixpkgs/issues/10290

### Notify maintainers
@marcweber @yurrriq

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.60, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.11pre318500.51bcdc4cdaa"`
 - channels(omid): `"home-manager, latest"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by omidmnz**
Fixes #140152. The fix is inspired by how lilypond-with-fonts was
packaged in v18.09.

###### Motivation for this change
As described in the issue, the `lilypond-with-fonts` package is broken at the moment.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by yurrriq — CHANGES_REQUESTED** [review]
Thanks for calling this out! I've made some inline comments and suggestions. By the way, we should probably migrate from https://github.com/OpenLilyPondFonts/ to https://github.com/openlilylib/notation-fonts at some point.

**Review by yurrriq — APPROVED** [review]

**Comment by yurrriq** [comment]
Result of `nixpkgs-review pr 140490` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>lilypond-with-fonts</li>
  </ul>
</details>

**Comment by yurrriq** [comment]
Thanks! Do you have any interest in migrating the fonts? I've created https://github.com/NixOS/nixpkgs/issues/141162 for tracking.

**Comment by omidmnz** [comment]
> Thanks! Do you have any interest in migrating the fonts? I've created #141162 for tracking.

Of course! But I don't have much experience with OpenLilyLib. But I'll sure dig into it and add my updates to the issue you mentioned.

**Pull request merged**
