### PR TITLE
python310Packages.aioaladdinconnect: init 0.1.20

### PR DESCRIPTION
**Pull request by fabaff**
###### Description of changes
Library for controlling Genie garage doors connected to Aladdin Connect devices

https://github.com/mkmer/AIOAladdinConnect

This is a Home Assistant dependency.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
```
============================= test session starts ==============================
platform linux -- Python 3.10.5, pytest-7.1.1, pluggy-1.0.0
rootdir: /build/source, configfile: pyproject.toml
plugins: aiohttp-0.3.0, freezegun-0.4.2, mock-3.8.1, rerunfailures-10.2, socket-0.5.1, xdist-2.5.0, forked-1.4.0, requests-mock-1.9.3, respx-0.19.2, anyio-3.5.0
gw0 [18] / gw1 [18] / gw2 [18] / gw3 [18]1m
..F.......F.......                                                       [100%]
=================================== FAILURES ===================================
_____________________ test_setup_get_doors_errors[pyloop] ______________________
[gw2] linux -- Python 3.10.5 /nix/store/hjwdfamsr1i4hgw41ldbj062icdyshvw-python3-3.10.5/bin/python3.10

hass = <homeassistant.core.HomeAssistant object at 0x7fffee3e5690>

    async def test_setup_get_doors_errors(hass: HomeAssistant) -> None:
        """Test component setup Get Doors Errors."""
        config_entry = MockConfigEntry(
            domain=DOMAIN,
            data=YAML_CONFIG,
            unique_id="test-id",
        )
        config_entry.add_to_hass(hass)
        with patch(
            "homeassistant.components.aladdin_connect.cover.AladdinConnectClient.login",
            return_value=True,
        ), patch(
            "homeassistant.components.aladdin_connect.cover.AladdinConnectClient.get_doors",
            return_value=None,
        ):
>           assert await hass.config_entries.async_setup(config_entry.entry_id) is True
E           assert False is True

config_entry = <tests.common.MockConfigEntry object at 0x7fffee4e0820>
hass       = <homeassistant.core.HomeAssistant object at 0x7fffee3e5690>

tests/components/aladdin_connect/test_init.py:30: AssertionError
---------------------------- Captured stderr setup -----------------------------
DEBUG:asyncio:Using selector: EpollSelector
------------------------------ Captured log setup ------------------------------
2022-07-10 10:26:22.597 DEBUG    MainThread asyncio:selector_events.py:54 Using selector: EpollSelector
----------------------------- Captured stderr call -----------------------------
INFO:homeassistant.loader:Loaded aladdin_connect from homeassistant.components.aladdin_connect
INFO:homeassistant.setup:Setting up aladdin_connect
INFO:homeassistant.setup:Setup of domain aladdin_connect took 0.0 seconds
ERROR:homeassistant.config_entries:Error setting up entry Mock Title for aladdin_connect
Traceback (most recent call last):
  File "/build/source/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/build/source/homeassistant/components/aladdin_connect/__init__.py", line 26, in async_setup_entry
    acc = AladdinConnectClient(username, password, async_get_clientsession(hass))
TypeError: AladdinConnectClient.__init__() takes 3 positional arguments but 4 were given
DEBUG:homeassistant.core:Bus:Handling <Event component_loaded[L]: component=aladdin_connect>
------------------------------ Captured log call -------------------------------
2022-07-10 10:26:22.603 INFO     SyncWorker_0 homeassistant.loader:loader.py:440 Loaded aladdin_connect from homeassistant.components.aladdin_connect
2022-07-10 10:26:22.603 INFO     MainThread homeassistant.setup:setup.py:204 Setting up aladdin_connect
2022-07-10 10:26:22.604 INFO     MainThread homeassistant.setup:setup.py:252 Setup of domain aladdin_connect took 0.0 seconds
2022-07-10 10:26:22.610 ERROR    MainThread homeassistant.config_entries:config_entries.py:416 Error setting up entry Mock Title for aladdin_connect
Traceback (most recent call last):
  File "/build/source/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/build/source/homeassistant/components/aladdin_connect/__init__.py", line 26, in async_setup_entry
    acc = AladdinConnectClient(username, password, async_get_clientsession(hass))
TypeError: AladdinConnectClient.__init__() takes 3 positional arguments but 4 were given
2022-07-10 10:26:22.610 DEBUG    MainThread homeassistant.core:core.py:886 Bus:Handling <Event component_loaded[L]: component=aladdin_connect>
--------------------------- Captured stderr teardown ---------------------------
DEBUG:homeassistant.core:Bus:Handling <Event homeassistant_stop[L]>
DEBUG:homeassistant.core:Bus:Handling <Event homeassistant_final_write[L]>
DEBUG:homeassistant.core:Bus:Handling <Event homeassistant_close[L]>
---------------------------- Captured log teardown -----------------------------
2022-07-10 10:26:22.614 DEBUG    MainThread homeassistant.core:core.py:886 Bus:Handling <Event homeassistant_stop[L]>
2022-07-10 10:26:22.614 DEBUG    MainThread homeassistant.core:core.py:886 Bus:Handling <Event homeassistant_final_write[L]>
2022-07-10 10:26:22.614 DEBUG    MainThread homeassistant.core:core.py:886 Bus:Handling <Event homeassistant_close[L]>
____________________ test_setup_component_no_error[pyloop] _____________________
[gw2] linux -- Python 3.10.5 /nix/store/hjwdfamsr1i4hgw41ldbj062icdyshvw-python3-3.10.5/bin/python3.10

hass = <homeassistant.core.HomeAssistant object at 0x7fffeda87850>

    async def test_setup_component_no_error(hass: HomeAssistant) -> None:
        """Test component setup No Error."""
        config_entry = MockConfigEntry(
            domain=DOMAIN,
            data=YAML_CONFIG,
            unique_id="test-id",
        )
        config_entry.add_to_hass(hass)
        with patch(
            "homeassistant.components.aladdin_connect.cover.AladdinConnectClient.login",
            return_value=True,
        ):
    
>           assert await hass.config_entries.async_setup(config_entry.entry_id)
E           assert False

config_entry = <tests.common.MockConfigEntry object at 0x7fffee410820>
hass       = <homeassistant.core.HomeAssistant object at 0x7fffeda87850>

tests/components/aladdin_connect/test_init.py:86: AssertionError
---------------------------- Captured stderr setup -----------------------------
DEBUG:asyncio:Using selector: EpollSelector
------------------------------ Captured log setup ------------------------------
2022-07-10 10:26:22.802 DEBUG    MainThread asyncio:selector_events.py:54 Using selector: EpollSelector
----------------------------- Captured stderr call -----------------------------
INFO:homeassistant.loader:Loaded aladdin_connect from homeassistant.components.aladdin_connect
INFO:homeassistant.setup:Setting up aladdin_connect
INFO:homeassistant.setup:Setup of domain aladdin_connect took 0.0 seconds
ERROR:homeassistant.config_entries:Error setting up entry Mock Title for aladdin_connect
Traceback (most recent call last):
  File "/build/source/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/build/source/homeassistant/components/aladdin_connect/__init__.py", line 26, in async_setup_entry
    acc = AladdinConnectClient(username, password, async_get_clientsession(hass))
TypeError: AladdinConnectClient.__init__() takes 3 positional arguments but 4 were given
DEBUG:homeassistant.core:Bus:Handling <Event component_loaded[L]: component=aladdin_connect>
------------------------------ Captured log call -------------------------------
2022-07-10 10:26:22.808 INFO     SyncWorker_0 homeassistant.loader:loader.py:440 Loaded aladdin_connect from homeassistant.components.aladdin_connect
2022-07-10 10:26:22.808 INFO     MainThread homeassistant.setup:setup.py:204 Setting up aladdin_connect
2022-07-10 10:26:22.808 INFO     MainThread homeassistant.setup:setup.py:252 Setup of domain aladdin_connect took 0.0 seconds
2022-07-10 10:26:22.811 ERROR    MainThread homeassistant.config_entries:config_entries.py:416 Error setting up entry Mock Title for aladdin_connect
Traceback (most recent call last):
  File "/build/source/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/build/source/homeassistant/components/aladdin_connect/__init__.py", line 26, in async_setup_entry
    acc = AladdinConnectClient(username, password, async_get_clientsession(hass))
TypeError: AladdinConnectClient.__init__() takes 3 positional arguments but 4 were given
2022-07-10 10:26:22.812 DEBUG    MainThread homeassistant.core:core.py:886 Bus:Handling <Event component_loaded[L]: component=aladdin_connect>
--------------------------- Captured stderr teardown ---------------------------
DEBUG:homeassistant.core:Bus:Handling <Event homeassistant_stop[L]>
DEBUG:homeassistant.core:Bus:Handling <Event homeassistant_final_write[L]>
DEBUG:homeassistant.core:Bus:Handling <Event homeassistant_close[L]>
---------------------------- Captured log teardown -----------------------------
2022-07-10 10:26:22.814 DEBUG    MainThread homeassistant.core:core.py:886 Bus:Handling <Event homeassistant_stop[L]>
2022-07-10 10:26:22.814 DEBUG    MainThread homeassistant.core:core.py:886 Bus:Handling <Event homeassistant_final_write[L]>
2022-07-10 10:26:22.815 DEBUG    MainThread homeassistant.core:core.py:886 Bus:Handling <Event homeassistant_close[L]>
=========================== short test summary info ============================
FAILED tests/components/aladdin_connect/test_init.py::test_setup_get_doors_errors[pyloop]
FAILED tests/components/aladdin_connect/test_init.py::test_setup_component_no_error[pyloop]
========================= 2 failed, 16 passed in 3.74s =========================

**Comment by mweinelt** [comment]
```
requirements_all.txt
8:AIOAladdinConnect==0.1.21

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 180958` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>home-assistant-component-tests.aladdin_connect</li>
    <li>python310Packages.aioaladdinconnect</li>
    <li>python39Packages.aioaladdinconnect</li>
  </ul>
</details>

**Comment by fabaff** [comment]
> AIOAladdinConnect==0.1.21

Thanks

**Pull request merged**
