### PR TITLE
WIP: cudatoolkit: add version 7.5

### PR DESCRIPTION
**Pull request by bjornfor**
TODO: Fix nsight startup error:

 $ ./result/bin/nsight
 CompilerOracle: exclude java/lang/reflect/Array.newInstance
 java.lang.NoClassDefFoundError: Could not initialize class
 sun.util.calendar.ZoneInfoFile
         at sun.util.calendar.ZoneInfo.getTimeZone(ZoneInfo.java:663)
         at java.util.TimeZone.getTimeZone(TimeZone.java:560)
         at java.util.TimeZone.setDefaultZone(TimeZone.java:657)
         at java.util.TimeZone.getDefaultRef(TimeZone.java:624)
         at java.util.Date.normalize(Date.java:1193)
         at java.util.Date.toString(Date.java:1027)
         at org.eclipse.equinox.launcher.Main.log(Main.java:2423)
         at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
         at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

### CODE REVIEW

**Comment by bjornfor** [comment]
Does anyone know what's up with that error? Too old Java?

**Comment by edolstra** [comment]
Maybe try strace to see if it's looking for zone info in the wrong place?

**Comment by bjornfor** [comment]
Strace snippet:

```
5143  open("/etc/timezone", O_RDONLY)   = -1 ENOENT (No such file or directory)
5143  lstat("/etc/localtime", {st_mode=S_IFLNK|0777, st_size=83, ...}) = 0
5143  readlink("/etc/localtime", "/nix/store/pl3066vi01b5ynjxi9wf51yyg8dnv43b-tzdata-2015f/share/zoneinfo/Europe/Oslo", 4096) = 83
5143  write(10, "!SESSION ", 9)         = 9
5143  close(10)                         = 0
5143  lseek(3, 27832954, SEEK_SET)      = 27832954
5143  read(3, "PK\3\4\n\0\0\0\0\0\275\215\34A\243\335\v\375\273\2\0\0\273\2\0\0,\0\0\0", 30) = 30
5143  lseek(3, 27833028, SEEK_SET)      = 27833028
5143  read(3, "\312\376\272\276\0\0\0003\0!\1\0\25(Ljava/lang/Object;)V\1\0\6<init>\1\0\4Code\1\0\fInnerClasses\1\0\17LineNumberTable\1\0\25Ljava/io/PrintStream;\1\0\nSourceFile\1\0\23java/io/PrintStream\1\0\23java/lang/Throwable\1\0\25java/lang/Throwable$1\1\0'java/lang/Throwable$PrintStreamOrWriter\1\0&java/lang/Throwable$WrappedPrintStream\1\0\4lock\1\0\vprintStream\1\0\7println\7\0\10\7\0\t\7\0\n\7\0\v\7\0\f\1\0\30(Ljava/io/PrintStream;)V\1\0\24()Ljava/lang/Object;\1\0\32(Ljava/lang/Throwable$1;)V\f\0\16\0"..., 699) = 699
5143  lseek(3, 27831673, SEEK_SET)      = 27831673
5143  read(3, "PK\3\4\n\0\0\0\0\0\275\215\34ABs\313z\354\1\0\0\354\1\0\0-\0\0\0", 30) = 30
5143  lseek(3, 27831748, SEEK_SET)      = 27831748
5143  read(3, "\312\376\272\276\0\0\0003\0\31\1\0\3()V\1\0\25(Ljava/lang/Object;)V\1\0\6<init>\1\0\4Code\1\0\fInnerClasses\1\0\17LineNumberTable\1\0\nSourceFile\1\0\20java/lang/Object\1\0\23java/lang/Throwable\1\0\25java/lang/Throwable$1\1\0'java/lang/Throwable$PrintStreamOrWriter\1\0\4lock\1\0\7println\7\0\10\7\0\t\7\0\n\7\0\v\1\0\24()Ljava/lang/Object;\1\0\32(Ljava/lang/Throwable$1;)V\f\0\3\0\1\n\0\16\0\24\n\0\21\0\24\1\0\23PrintStreamOrWriter\1\0\16Throwable.java\4 \0\21\0\16\0\0\0\0\0\4\0\2\0\3\0\1\0\1\0\4\0\0\0\35\0\1\0\1\0\0\0\5*\267\0\25\261\0\0\0\1\0\6\0\0\0\6\0\1\0\0\2\327\4"..., 492) = 492
5143  lseek(3, 59917326, SEEK_SET)      = 59917326
5143  read(3, "PK\3\4\n\0\0\0\0\0\302\215\34A\22\225F\204G#\0\0G#\0\0\37\0\0\0", 30) = 30
5143  lseek(3, 59917387, SEEK_SET)      = 59917387
5143  read(3, "\312\376\272\276\0\0\0003\1$\3\37\377\377\377\3 \0\0\0\3@\0\0\0\10\0\26\10\0>\1\0\3()I\1\0\24()Ljava/lang/String;\1\0\3()V\1\0\3()Z\1\0\4(I)I\1\0\4(I)V\1\0\5(II)I\1\0\25(Ljava/lang/Object;)I\1\0\25(Ljava/lang/Object;)V\1\0\25(Ljava/lang/Object;)Z\1\0'(Ljava/lang/Object;Ljava/lang/Object;)Z\1\0\25(Ljava/lang/String;)V\1\0\v(TK;TV;)TV;\1\0\t(TK;TV;)V\1\0\10<clinit>\1\0\6<init>\1\0\23Capacity exhausted.\1\0\4Code\1\0\rConstantValue\1\0\20DEFAULT_CAPACITY\1\0\5Entry\1\0\nExceptions\1\0\1I\1\0\fInnerClasses\1\0\1J\1\0\17LineNumberT"..., 9031) = 9031
5143  lseek(3, 59545961, SEEK_SET)      = 59545961
5143  read(3, "PK\3\4\n\0\0\0\0\0\302\215\34A4\226E2\1\7\0\0\1\7\0\0&\0\0\0", 30) = 30
5143  lseek(3, 59546029, SEEK_SET)      = 59546029
5143  read(3, "\312\376\272\276\0\0\0003\0T\1\0\3()I\1\0\3()V\1\0\3()Z\1\0\25(Ljava/lang/Object;)I\1\0\25(Ljava/lang/Object;)Z\1\0\6<init>\1\0\4Code\1\0\fInnerClasses\1\0\17LineNumberTable\1\0\tSignature\1\0\nSourceFile\1\0\rStackMapTable\1\0\naccess$000\1\0\5clear\1\0\10contains\1\0\vcontainsKey\1\0\7hasNext\1\0\10hashCode\1\0\20identityHashCode\1\0\10iterator\1\0\20java/lang/System\1\0\25java/util/AbstractSet\1\0\24java/util/Collection\1\0\31java/util/IdentityHashMap\1\0\33java/util/IdentityHashMap$1\1\0%java/util/"..., 1793) = 1793
5143  write(2, "java.lang.NoClassDefFoundError: Could not initialize class sun.util.calendar.ZoneInfoFile", 89) = 89
5143  write(2, "\n", 1)                 = 1
5143  write(2, "\tat sun.util.calendar.ZoneInfo.getTimeZone(ZoneInfo.java:663)", 61) = 61
5143  write(2, "\n", 1)                 = 1
5143  write(2, "\tat java.util.TimeZone.getTimeZone(TimeZone.java:560)", 53) = 53
5143  write(2, "\n", 1)                 = 1
5143  write(2, "\tat java.util.TimeZone.setDefaultZone(TimeZone.java:657)", 56) = 56
```

I don't know how this logic is implemented (what files are required or not), but it seems to find at least one timezone file.

Searching for this error ("java.lang.NoClassDefFoundError: Could not initialize class
sun.util.calendar.ZoneInfoFile") online gives few results :-/

I just found out that cudatoolkit bundles its own java version (I initially thought it didn't), so everything should be in order. Well, unless nixpkgs patchelf'ing messes some things up.

**Comment by bjornfor** [comment]
Here is one possibly relevant issue (for openjdk): https://bugs.openjdk.java.net/browse/JDK-7009152

I don't know which java cudatoolkit uses:

```
$ nix-build -A cudatoolkit75
$ ./result/jre/bin/java -version
java version "1.7.0_07"
Java(TM) SE Runtime Environment (build 1.7.0_07-b10)
Java HotSpot(TM) 64-Bit Server VM (build 23.3-b01, mixed mode)
```

They haven't changed the java version between cuda 7.0 and 7.5:

```
$ nix-build -A cudatoolkit7
$ ./result/jre/bin/java -version
java version "1.7.0_07"
Java(TM) SE Runtime Environment (build 1.7.0_07-b10)
Java HotSpot(TM) 64-Bit Server VM (build 23.3-b01, mixed mode)
```

**Comment by bjornfor** [comment]
There have been two other PRs for updating to 7.5 already, but no more comments about this issue (why 7.0 -> 7.5 breaks the IDE). If people really want 7.5, I guess we can merge this PR and add a warning (comment) that the IDE is broken.

But I don't think we should move the "cudatoolkit" attribute from 7.0 to 7.5 until the IDE works properly.

Thoughts?

CC @edolstra, @anderspapitto, @spwhitt.

**Comment by bjornfor** [comment]
Disclaimer: I'm not using CUDA now, I just played with it for a while. And I hate regressions :-D

**Comment by bjornfor** [comment]
I see 6d97de951df1c4b80c99c31a81d3ed89a329d999 ("cudatoolkit: Add version 7.5.18") has been added to master. @edolstra: Did you test nsight? Maybe I should turn this into an issue instead of a PR now?

**Comment by bjornfor** [comment]
Just tested on master

```
$ ./result/bin/nsight 
CompilerOracle: exclude java/lang/reflect/Array.newInstance
java.lang.NoClassDefFoundError: Could not initialize class sun.util.calendar.ZoneInfoFile
	at sun.util.calendar.ZoneInfo.getTimeZone(ZoneInfo.java:663)
	at java.util.TimeZone.getTimeZone(TimeZone.java:560)
	at java.util.TimeZone.setDefaultZone(TimeZone.java:657)
	at java.util.TimeZone.getDefaultRef(TimeZone.java:624)
	at java.util.Date.normalize(Date.java:1193)
	at java.util.Date.toString(Date.java:1027)
	at org.eclipse.equinox.launcher.Main.log(Main.java:2423)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

**Comment by edolstra** [comment]
Sorry, forgot about this PR. However, I didn't change the default cudatoolkit, but we may want to add a lowPrio to 7.5.

**Pull request closed without merging**
