### PR TITLE
poppler: 0.67.0 → 0.72.0

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
https://gitlab.freedesktop.org/poppler/poppler/blob/poppler-0.72.0/NEWS

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @codyopel @ttuegel

### CODE REVIEW

**Comment by jtojnar** [comment]
cc @layus https://github.com/OpenPrinting/cups-filters/blob/release-1-21-6/NEWS

**Comment by jtojnar** [comment]
cc @vcunat @lovek323 @raskin @jwiegley for the `texlive.bin.core` change.

**Review by layus — APPROVED** [review]
LGTM

**Review by vcunat — APPROVED** [review]
Now all of texlive binaries build OK, and the changes seem reasonable.  I haven't tested anything, though.

**Pull request merged**
