### PR TITLE
utsushi: 3.59.2 -> unstable-2020-11-10

### PR DESCRIPTION
**Pull request by wucke13**
###### Motivation for this change
Update.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by wucke13** [comment]
@GrahamcOfBorg build utsushi

**Comment by Lassulus** [comment]
@GrahamcOfBorg build utsushi

**Comment by wucke13** [comment]
There still is an issue in the package, that needs to be fixed either through a patch in this PR or through a new release - so please don't merge yet.

**Comment by wucke13** [comment]
@GrahamcOfBorg build utsushi

**Comment by wucke13** [comment]
@Lassulus This could finally be ready for merge. Can you remove the Draft status?

**Comment by Lassulus** [comment]
Uh you could do that yourself, but master is not really a released version. We really prefer stable released versions upstream. But if you really want to bump this to an unreleased git rev. Then the correct version number would be "unstable-2020-11-11" (the date of the pinned commit)

**Comment by wucke13** [comment]
We had a [discussion](https://gitlab.com/utsushi/utsushi/-/issues/98#note_445274222) about this already. Epson releases with version numbers, however, they almost never fix things. There is a [community repo](https://gitlab.com/utsushi/utsushi) which incorporates loads of fixes, but said community repo does not have releases at all, _[yet](https://gitlab.com/utsushi/utsushi/-/issues/97)_. I would opt for the community repo, I'm immediately aware of at least two bugs which are fixed by doing so. 

I adjusted the version number accordingly, thank you for that hint @Lassulus  :smile:

**Pull request merged**
