### PR TITLE
prometheus-statsd-exporter: 0.4.0 -> 0.9.0

### PR DESCRIPTION
**Pull request by ivan**
###### Motivation for this change

https://github.com/prometheus/statsd_exporter/releases

Note that the output binary has changed from `statsd_bridge` to `statsd_exporter` and that the command-line arguments have changed.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I sent a counter to it over UDP and it seemed to work.

### CODE REVIEW

**Comment by basvandijk** [comment]
@GrahamcOfBorg build prometheus-statsd-exporter

**Comment by basvandijk** [comment]
I think it also makes sense to remove the [prometheus-statsd-bridge alias](https://github.com/NixOS/nixpkgs/blob/6cc43add3f023abf0d32fe968503683e005c7ff9/pkgs/top-level/aliases.nix#L256) now because the package really has become a different thing.

**Comment by ivan** [comment]
Thanks, removed the alias.

Heads up @jbgi, this upgrade will break your https://github.com/input-output-hk/iohk-ops/pull/558/files#diff-b6b843ae5c2dd45366d561553ddecbd9R75

**Comment by jbgi** [comment]
Thanks @ivan for heads up, will keep in mind when we upgrade to 19.09. (unless there is a plan to backport this?)

**Pull request merged**
