### PR TITLE
or-tools: add darwin support

### PR DESCRIPTION
**Pull request by sdedovic**
###### Description of changes

Add support for `or-tools` on Mac. Build was borked because of `@rpath` issues in the generated dynlib and binaries used for testing (`checkPhase` a la `ctest`). This works on my machine so sharing the changes with all.

Some related discussion:
- [cmake MACOSX_RPATH](https://cmake.org/cmake/help/latest/prop_tgt/MACOSX_RPATH.html)
- #30150
- [LLVM mailing list on RPATH](https://lists.llvm.org/pipermail/llvm-dev/2017-October/118049.html)

This also seems to me the lesser of two evils. `fixdarwindylibnames` exists but presents two problems, making it insufficient.
1. the script runs after the `checkPhase`, so I need to run it as the `postBuildHook` as `ctest` uses linked objects and fails to pass.
2. the script only patches `dylib` files. This project creates a large amount of executables that do not get patched and are used by `ctest`. Again failing the `checkPhase`. 

Open to thoughts, I'm using it now and it functions well enough. 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Atemu — CHANGES_REQUESTED** [review]
Result of `nixpkgs-review pr 201136` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>or-tools</li>
    <li>python310Packages.ortools</li>
    <li>python39Packages.ortools</li>
  </ul>
</details>


```
 96/394 Test #104: python_model_builder_assignment_mb .........................................***Failed    0.17 sec
Traceback (most recent call last):
  File "/tmp/nix-build-or-tools-9.4.drv-0/source/ortools/model_builder/samples/assignment_mb.py", line 17, in <module>
    from ortools.model_builder.python import model_builder
ModuleNotFoundError: No module named 'ortools.model_builder'
```

**Review by wegank — APPROVED** [review]
Build passes on macOS 13.1, both aarch64-darwin and x86_64-darwin (via Rosetta).

**Comment by Atemu** [comment]
@wegank not for me, still getting the same results as above.

**Comment by wegank** [comment]
@ofborg build or-tools or-tools.passthru.tests

**Comment by sdedovic** [comment]
@Atemu @wegank please see my latest commit

The `checkPhase` was an issue because it could `pip install` from PyPi a newer version instead of the local one. I believe this is fixed in or-tools 9.5 or 9.6, so I have backported the patch. This has successfully built on my M1 mac.

**Comment by sdedovic** [comment]
> Result of `nixpkgs-review pr 201136` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
> 3 packages failed to build:
> 
> ```
>  96/394 Test #104: python_model_builder_assignment_mb .........................................***Failed    0.17 sec
> Traceback (most recent call last):
>   File "/tmp/nix-build-or-tools-9.4.drv-0/source/ortools/model_builder/samples/assignment_mb.py", line 17, in <module>
>     from ortools.model_builder.python import model_builder
> ModuleNotFoundError: No module named 'ortools.model_builder'
> ```

Result of `nixpkgs-review pr 201136` run on arm64 darwin:
```
3 packages built:
or-tools python310Packages.ortools python311Packages.ortools
```

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 201136` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>or-tools</li>
    <li>or-tools.python (python310Packages.ortools ,python310Packages.ortools.python)</li>
    <li>python311Packages.ortools (python311Packages.ortools.python)</li>
  </ul>
</details>

**Comment by sdedovic** [comment]
Result of `nixpkgs-review pr 201136` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>or-tools</li>
    <li>or-tools.python (python310Packages.ortools ,python310Packages.ortools.python)</li>
    <li>python311Packages.ortools (python311Packages.ortools.python)</li>
  </ul>
</details>

**Comment by sdedovic** [comment]
Result of `nixpkgs-review pr 201136` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>or-tools</li>
    <li>or-tools.python (python310Packages.ortools ,python310Packages.ortools.python)</li>
    <li>python311Packages.ortools (python311Packages.ortools.python)</li>
  </ul>
</details>

**Pull request merged**
