### PR TITLE
calligra: 2.9.11 -> 3.0.1

### LINKED ISSUE #22966: Updated Calligra for KDE 5
Calligra has been [updated](http://calligra.org) for KDE 5, but retaining the older KDE 4-based package obstructs removal of its dependencies.

Attn. @urkud @Phreedom @ebzzry

### PR DESCRIPTION
**Pull request by zraexy**
###### Motivation for this change

Update Calligra to 3.0.1 which uses KF5

Kexi has been split off and is now its own package.

Due to the fact that Author, Braindump, Flow, and Stage were removed (Flow and Stage are planned to be added back in) I have kept 2.9.11 under the `calligra2` attribute. It can be removed when `kde4` is.

I have not used Calligra much so it would be good to have someone who uses it regularly give this a try before merging.

Resolves #22966

cc @Phreedom @ebzzry 

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
It builds; neither 2.x nor 3.x will start for me unfortunately, though that might be "just" #13715 or something similar.

Nitpick: why did you drop `enableParallelBuilding`?  It must take ages to build without it.

**Comment by zraexy** [comment]
> Nitpick: why did you drop enableParallelBuilding? It must take ages to build without it.

Oops. I forgot to use `mkDerivation` and `lib` instead of `stdenv.mkDerivation` and `stdenv.lib`.
`libsForQt5.callPackage`'s `mkDerivation` has `enableParallelBuilding` set to `true` by default.

**Comment by zraexy** [comment]
Unless there are any other issues I think this is ready to be merged.

**Comment by orivej** [comment]
Thank you!

**Pull request merged**
