### PR TITLE
[20.03] mongodb: update

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

Backport PR for #40082 and #83617.

(@worldofpeace I may be wrong, but did you mention that you'd prefer to only backport mongodb 3.4.24? In that case I'd remove 3.6/4.0 from this PR. I just added all of it for now as it was rather tight coupled due to the package split :))

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
> (@worldofpeace I may be wrong, but did you mention that you'd prefer to only backport mongodb 3.4.24? In that case I'd remove 3.6/4.0 from this PR. I just added all of it for now as it was rather tight coupled due to the package split :))

I did mention to backport the most minimal upgrade because we are already frozen.
And that's just to avoid additional fixes because the audit for `3.4.10 -> 4.0.4` is much bigger than what is actually minimally required which you mentioned would be `3.4.24`.
But I'm open to second opinions on this because I don't know the semantics of the versioning here, or know anything about mongodb (I what would be a good practical application of best practices)

**Comment by worldofpeace** [comment]
@Ma27 I see the default is 3.4.x, but backported newer versions. I don't see a problem with that.

**Review by worldofpeace — APPROVED** [review]
I approve of this being backported.

**Comment by Ma27** [comment]
In the go/nogo meeting it has been decided that this is good to go and Hydra shouldn't build (for now) unfree code.

**Pull request merged**
