### PR TITLE
polkit: 0.113 -> 0.115

### PR DESCRIPTION
**Pull request by symphorien**
###### Motivation for this change

I am affected by a bug fixed in 0.114 (https://bugs.freedesktop.org/show_bug.cgi?id=96977 )

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [x] Tested via one or more NixOS test(s): udisks
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Other considerations

All fedora patches have been merged upstream.
Tests pass and have been enabled on linux.

cc @dtzWill regarding musl support: https://github.com/NixOS/nixpkgs/commit/551f0702c24536e4918c6239de9f32772a6ef165 introduced a musl patch (source
https://bugs.freedesktop.org/show_bug.cgi?id=50145 ) but this patch does not apply anymore, and
this other bug https://bugs.freedesktop.org/show_bug.cgi?id=75187 introduced similar changes.
I tried building polkit on musl:
```
nix-build . -A polkit --arg crossSystem '(import <nixpkgs> {}).lib.systems.examples.musl64'
```
but this fails to build dependencies ( `/nix/store/b0q57pcgkn2z185nrk2dx6lyjys18xqy-bsd-compat-netbsd-7.1.2-x86_64-unknown-linux-musl.drv` ).
So I chose to drop the patch completely. As of now we don't need it since dependencies don't build.

### CODE REVIEW

**Comment by adisbladis** [comment]
The `udisks2` test is relying on polkit, lets run it :)
@GrahamcOfBorg test udisks2

**Comment by adisbladis** [comment]
The build is failing because of unpatched shebangs in tests.

**Comment by symphorien** [comment]
Here is a version which should build with sandboxing.

**Comment by xeji** [comment]
@grahamcofborg build polkit

**Comment by dtzWill** [comment]
@symphorien Thanks for the ping and effort re:musl!

* Pinging is great! Hopefully there's a "musl team" to ping soon, see #43265
* Cross-compilation is often more problematic than native building--so if you're on a x86_64-linux builder you can test musl support by simply prepending "pkgsMusl" to the attribute.  So, `pkgsMusl.polkit` :).  That said you'll still encounter dependency problems while I cleanup the systemd patchery (long been working in my fork for the curious, but that's mostly a staging area for things I'm sending uptsream :))
* If in doubt or no response, dropping the patch is the right thing and no worries (indeed, apologies for the trouble).  But if you know you're dropping things or MIGHT be breaking things, please ping me/us anyway (as you've done) so we aren't surprised later :).  Much appreciated.

I haven't investigated the musl patch situation yet since it appears to have build problems elsewhere that need attention. (And I'm hoping to clean up systemd bits for inclusion soon!)

**Comment by xeji** [comment]
let's try again, maybe the dependencies have been fixed
@GrahamcOfBorg build polkit

**Comment by xeji** [comment]
I'll add 0.115 here shortly

**Comment by xeji** [comment]
@GrahamcOfBorg build polkit

**Comment by xeji** [comment]
x86_64-linux failure is in a dependency and unrelated to this PR (builds fine locally on this branch).

But we have an issue with darwin: Looks like `spidermonkey_17 -> spidermonkey_52` makes `polkit` unsupported on darwin.  @symphorien was it necessary to update this? 

(I find it rather weird that polkit depends on a javascript engine, see #8989 )

**Comment by vcunat** [comment]
The weird part is that they decided to use JS for configuration.

**Comment by jtojnar** [comment]
polkit uses javascript to allow system administrators to override rules, the requirements were bumped in 0.114: https://cgit.freedesktop.org/polkit/commit/?id=81b92d6c36a086fb370b69440b0a05dfbfa23085

**Comment by xeji** [comment]
So what do we do - leave darwin at polkit 0.113 ?

**Comment by jtojnar** [comment]
Is polkit even used on darwin?

**Comment by xeji** [comment]
Not sure but this causes a 19 darwin rebuilds, mostly mate / lxqt-related stuff

**Comment by jtojnar** [comment]
Yeah, except for falkon, none of the darwin rebuilds look like they would work on darwin anyway.

**Comment by xeji** [comment]
Agree. So I'd say let's merge this and fix the fallout later if anyone complains.

**Pull request merged**
