### PR TITLE
weechat-autojoin: init at 0.3.1; weechat-text-item: init at 0.9

### PR DESCRIPTION
**Pull request by bdesham**
#### Motivation for this change

Adds two scripts to be used with the Weechat chat client:

- weechat-autojoin: When quitting Weechat, automatically saves the list of current IRC channels so that they can be joined next time Weechat is launched.
- weechat-text-item: Allows pieces of static text to be included in Weechat’s various status bars.

~~These scripts come from the Weechat scripts site, which doesn’t seem to offer a way to download a specific version of a script—only the latest version. Therefore, I included the two scripts directly within Nixpkgs. They’re 6,703 bytes and 10,764 bytes. If anyone knows of a way to get specific versions from the Weechat site that would obviously be preferable. (The text_item script says that development is hosted at https://github.com/weechatter/weechat-scripts, but the Weechat site has a more recent version of the script than that repo does.)~~ This problem is now fixed; the derivations just use `fetchFromGitHub` like you’d expect.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @lovek323 @the-kenny @lheckemann @Ma27 (the maintainers of Weechat itself)

### CODE REVIEW

**Comment by lheckemann** [comment]
This should probably download the scripts using fetchurl rather than adding them verbatim into nixpkgs.

**Comment by bdesham** [comment]
I thought that downloading specific versions of these scripts was impossible—that you could only download the latest versions—but I was mistaken. I’ll update the PR tonight, hopefully.

**Comment by jtojnar** [comment]
The text_item looks the same from both sources here.

**Comment by bdesham** [comment]
They weren’t the same when I opened this PR :wink: It turns out that all of the scripts on the WeeChat scripts site are stored in https://github.com/weechat/scripts, so I’m going to update these derivations to pull from there.

**Comment by bdesham** [comment]
This has been updated to use `fetchFromGitHub` instead of including the actual scripts in Nixpkgs.

**Comment by jtojnar** [comment]
Could you perhaps factor out the common code to a `common.nix` file?

**Comment by bdesham** [comment]
@jtojnar I created a mk-weechat-script.nix file that contains a function with all of the common code. If this seems like a good approach then I will add some documentation of how the function can be used.

The way I’m injecting `stdenv` and `fetchFromGitHub` into the function feels extremely awkward right now. I’d appreciate any advice on how to make that more natural.

**Comment by jtojnar** [comment]
Why not just use `callPackage` on it?

**Comment by bdesham** [comment]
@jtojnar Thanks for the pointers on IRC. I’ve updated this to be a little simpler.

**Comment by bdesham** [comment]
I’ve rebased this against the latest Nixpkgs master and I updated one of the scripts.

**Comment by bdesham** [comment]
I still think this is a useful change, but I don’t have the energy to shepherd it through the nixpkgs PR process so I’m going to close it.

**Pull request closed without merging**
