### PR TITLE
New Package: Google Cloud SDK

### PR DESCRIPTION
**Pull request by aaronlevin**
This is my first non-Haskell package. Google manages this package strangely: it's not version'd, uses `$HOME` during installation, etc. Hopefully I did the right things (I tried to look at other similar packages for inspiration).

### CODE REVIEW

**Comment by 7c6f434c** [comment]
@aaronlevin Do I understand it right that this currently works only without chroot builds enabled?

**Comment by aaronlevin** [comment]
@7c6f434c It was working for me until I performed an upgrade and then receive a similar error.  So, perhaps we should close this PR without merging.

**Comment by iElectric** [comment]
@aaronlevin cool, let us know if you want to pursue the issue or close PR

**Comment by aaronlevin** [comment]
@iElectric I will close this PR and submit a new one if I have time to figure out the nuances with this package. Thanks!

**Pull request closed without merging**
