### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by LnL7** [comment]
@matthewbauer What's the status of darwin, is it ready for master?

**Comment by matthewbauer** [comment]
I'm able to build lots of stuff locally but we were having issues on the Hydra machines. This is the error that happened on the last eval:

https://hydra.nixos.org/build/86006395

It most likely has to do with differences between macOS 10.12 and 10.14. If someone could reproduce that error & include the config.log that would be really helpful.

**Comment by FRidh** [comment]
Several linking errors (DSO) https://github.com/NixOS/nixpkgs/issues/53001

**Comment by matthewbauer** [comment]
@lnl7 @fridh It looks like there are a lot more failures with the new Darwin stdenv stuff than I expected. I have opened a PR to fix **some of them** here:

https://github.com/NixOS/nixpkgs/pull/53230

But, I wonder if it would be best to take these out of staging-next? I should probably create a Hydra jobset to handle all of them.

**Comment by LnL7** [comment]
In that case I propose we revert it here for now and branch off from there. Both copumpkin and I have a testing jobset for darwin so we can reuse that and with the increased capacity we don't have to worry too much about holding up other builds. (there are currently 2 darwin jobs in the queue 😄 )

**Comment by FRidh** [comment]
@LnL7 @matthewbauer if you want to revert, then please do so before the weekend because I would like to merge this into master.

**Comment by matthewbauer** [comment]
Ok reverted in 8505e710e707b2e425379dc356721194f742d8d0 (and then unreverted in #53230)

**Comment by FRidh** [comment]
@matthewbauer there's something wrong: https://nix-cache.s3.amazonaws.com/log/w7zz8c4lfrnijrziyc0msa959rigd7w9-adv_cmds-osx-10.5.8.drv

**Pull request merged**
