### PR TITLE
fftw: Fix Darwin build

### PR DESCRIPTION
**Pull request by spwhitt**

### CODE REVIEW

**Comment by spwhitt** [comment]
Fixed stdenv.cc.cc.isClang related build failure by switching to stdenv.isDarwin for now.

**Comment by gridaphobe** [comment]
@spwhitt the correct way to use `.isClang` is `(stdenv.cc.cc.isClang or false)`, which catches the attribute-not-found error and returns false instead.

It's a bit clunky, but that's what the `.isGNU` attribute on gcc does as well.

**Comment by copumpkin** [comment]
Can't we just ensure that `.isClang` and `.isGNU` is always defined (at least on the common `cc` values)? The error-handling feels kinda janky.

**Comment by gridaphobe** [comment]
Yes, we should probably do that; `cc-wrapper` would be a good place to do it, as it's central and would also remove a layer of indirection in the checks.

**Comment by copumpkin** [comment]
:+1:

**Comment by spwhitt** [comment]
Thanks for the info @gridaphobe. I've update the pull request accordingly.

The above scheme to make `.isClang` and `.isGNU` more convenient sounds fantastic. :+1:

**Pull request merged**
