### PR TITLE
prl-tools: init Rosetta support

### PR DESCRIPTION
**Pull request by codgician**
## Description of changes

This PR contains a one-liner change to also install `prlbinfmtconfig.sh` from parallels guest tools. `prlstoold` would mount rosetta binaries to `/media/psf/RosettaLinux/` and invoke this script to register `binfmt`. As per my testing, existing patches seem enough to get this script working and get rosetta correctly registered in `binfmt`:

image

~~⚠️ However I am not able to test it end to end due to I am running macOS Sequoia Beta on my only Mac. In my current environment Rosetta doesn't even work on official Ubuntu image provided by Parallels. So **marking this PR as draft** and welcome testers.~~

Tested under help from @volfyd. See details in conversation.

Following snippet were also added to my nix configuration:

```nix
hardware.parallels = {
  enable = true;
  autoMountShares = true;
};

nix.settings = {
  extra-platforms = [ "x86_64-linux" ];
  extra-sandbox-paths =  [
    "/run/binfmt"
    "/media/psf/RosettaLinux"
  ];
};

# prlbinfmtconfig.sh would only register binfmt when systemd-binfmt.service is enabled.
# Following lines are added to ensure the service exists and is enabled when prlstoolsd.service runs
boot.binfmt.registrations.RosettaLinux = {
  interpreter = "/media/psf/RosettaLinux/rosetta";

  # The required flags for binfmt are documented by Apple:
  # https://developer.apple.com/documentation/virtualization/running_intel_binaries_in_linux_vms_with_rosetta
  magicOrExtension = ''\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x3e\x00'';
  mask = ''\xff\xff\xff\xff\xff\xfe\xfe\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff'';
  fixBinary = true;
  matchCredentials = true;
  preserveArgvZero = false;

  # Remove the shell wrapper and call the runtime directly
  wrapInterpreterInShell = false;
};
```

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by volfyd** [comment]
If anyone wants to test this idea, this snippet will let you try out `prlbinfmtconfig` without needing to merge the commits on this PR:

I will update when I have a chance to actually test the functionality.

```
  hardware.parallels.package = config.boot.kernelPackages.prl-tools.overrideAttrs (
    old: {
      installPhase =
        builtins.replaceStrings
        ["install -Dm755 ../../tools/prlfsmountd.sh $out/sbin/prlfsmountd"]
        [
          ''
            install -Dm755 ../../tools/prlfsmountd.sh $out/sbin/prlfsmountd
            install -Dm755 ../../tools/prlbinfmtconfig.sh $out/sbin/prlbinfmtconfig
          ''
        ]
        old.installPhase;
    }
  );
```

**Comment by volfyd** [comment]
```
$ which prlbinfmtconfig
/run/current-system/sw/bin/prlbinfmtconfig

$ systemctl status systemd-binfmt.service
● systemd-binfmt.service - Set Up Additional Binary Formats
     Loaded: loaded (/etc/systemd/system/systemd-binfmt.service; enabled; preset: enabled)
    Drop-In: /nix/store/0s6br8hvlzj1sw20b8kpn275bcnixarv-system-units/systemd-binfmt.service.d
             └─overrides.conf
     Active: active (exited) since Wed 2024-09-04 20:07:33 EDT; 13min ago
       Docs: man:systemd-binfmt.service(8)
             man:binfmt.d(5)
             https://docs.kernel.org/admin-guide/binfmt-misc.html
             https://www.freedesktop.org/wiki/Software/systemd/APIFileSystems
   Main PID: 1029 (code=exited, status=0/SUCCESS)
        CPU: 5ms

Sep 04 20:07:33 nixos systemd[1]: Starting Set Up Additional Binary Formats...
Sep 04 20:07:33 nixos systemd[1]: Finished Set Up Additional Binary Formats.

$ mkdir hello

$ cd hello

$ go mod init example/hello
go: creating new go.mod: module example/hello

$ cat > hello.go
package main

import "fmt"

func main() {
    fmt.Println("Hello, World!")
}

$ env GOOS=linux GOARCH=amd64 go build .

$ file hello
hello: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=4McYDYWEIoCI_B7x3__H/c6RdewIXKVlG0LeT1juO/Ac63xo5ZUCOrafc1E1ol/_dkgvBldgqf_wg3oBjjf, with debug_info, not stripped

$ ./hello
Hello, World!

$
```

This works for me.

**Comment by volfyd** [comment]
I guess instead of the go program I could have done this (which also works):

```
$ nix run nixpkgs#legacyPackages.x86_64-linux.hello
Hello, world!
```

**Comment by volfyd** [comment]
It's dog slow but I was actually able to run
```
NIXPKGS_ALLOW_UNFREE=1 nix run --impure nixpkgs#legacyPackages.x86_64-linux.slack
```
and get to the login screen.

**Comment by codgician** [comment]
Thank you so much @volfyd. Marking this PR as ready for review.

**Review by wegank — APPROVED** [review]

**Pull request merged**
