### PR TITLE
llvmPackages_12: 12.0.0 -> 12.0.1

### PR DESCRIPTION
**Pull request by primeos**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by primeos** [comment]
@ofborg build llvmPackages_12

**Comment by ck3d** [comment]
I am interested in back-porting this PR to NixOS-21.05 to fix the problem described in https://github.com/NixOS/nixpkgs/pull/130495 . Please give feed back if you this back port has a change to land in 21.05.

**Comment by primeos** [comment]
> Please give feed back if you this back port has a change to land in 21.05.

What do you mean? Is the question if we should backport this (/ if I think a backport would have a chance to land)? In that case I'd say that this makes sense to backport if it fixes things and given that `llvmPackages_latest` on NixOS 21.05 still points to LLVM 11 it shouldn't even cause that many rebuilds.

**Comment by ck3d** [comment]
Thanks, you corrected my misspelling correctly and thanks for back porting! I was not aware how easy it is to create a back port.

**Pull request merged**
