### PR TITLE
python3Packages.black: 21.10b0 -> 21.12b0

### PR DESCRIPTION
**Pull request by bryanasdev000**
###### Motivation for this change

Update to the last release.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [X] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by thiagokokada — COMMENTED** [review]
Another scary number of rebuilds, calling the Python folks again (sorry).

@fabaff @jonringer @SuperSandro2000 .

**Comment by fabaff** [comment]
The update to 21.10b0 trigged a little over 140 rebuilds. From my point of view this can go to `master`.

**Review by jonringer — COMMENTED** [review]
normally, this wouldn't be much of an issue, as most python builds are "cheap". However, hydra is currently being crushed by builds right now. Please rebase on staging

```
# finding the common merge base will avoid pinging all CODEOWNERs
common=$(git merge-base origin/master origin/staging)
git rebase --onto=$common HEAD~1 # or however many commits you want to pull
git push .. ... --force
```
then change the base branch in the github PR from `master` -> `staging`

See https://nixos.org/nixpkgs/manual/#submitting-changes-staging-branch for more details on staging branch

**Review by autophagy — APPROVED** [review]

**Comment by thiagokokada** [comment]
@bryanasdev000 Can you retarget to staging?

**Comment by sumnerevans** [comment]
Also, a newer version was released https://github.com/psf/black/releases/tag/21.12b0

**Comment by thiagokokada** [comment]
@bryanasdev000 Please fix the commit (and PR title).

```
python3Packages.black: 21.10b0 -> 21.12b0
```

**Comment by bryanasdev000** [comment]
Sorry for the delay guys, ready to ship now.

**Review by thiagokokada — COMMENTED** [review]
LGTM.

Wait until the checks finishes.

**Pull request merged**
