### PR TITLE
update maintainer infos for myself

### PR DESCRIPTION
**Pull request by GRBurst**
###### Motivation for this change
Update E-Mail and add GitHub Id and Keys to my maintainer infos.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rnhmjoj** [comment]
Github, Github ID looks good. I don't know about the PGP key: you haven't uploaded it to a keyserver/github yet, right?

**Comment by GRBurst** [comment]
@rnhmjoj thanks for the fast response. I re-added the key right now because I added an uid. But I have not signed my commits, yet

**Comment by GRBurst** [comment]
@rnhmjoj Are there further steps necessary besides adding it to my github account? Do I have to upload it to a specific keyserver that nixpkgs uses for verification? Thanks for your help in advance :-)

**Comment by rnhmjoj** [comment]
I don't know of any hard requirement, it's just convenient: if you upload it to github everyone can quickly see the comit are signed, and a keyserver is useful to get your key if anyone want to send an email.

**Pull request merged**
