### PR TITLE
gitlab: 12.4.1 -> 12.4.2

### PR DESCRIPTION
**Pull request by talyz**
###### Motivation for this change
- Update GitLab from 12.4.1 -> 12.4.2
- Stop building GitLab components on macOS, since it, seemingly at random, [fails to fetch the sources on Hydra](https://hydra.nixos.org/build/104616339). This can cause Linux builds to fail too, since the failure gets cached. Since we don't build the rails app for macOS, I don't see any reason why the rest should be built.
- Lower the allowed memory usage when compiling webpack assets to give the i686 build on Hydra a chance of succeeding. Is there any way to test this before merging?

###### Things done

- Tested basic functionality in local VM

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @flokli @fpletz @globin @krav @bgamari

### CODE REVIEW

**Comment by talyz** [comment]
@grahamcofborg test gitlab

**Review by fpletz — APPROVED** [review]
Not tested this yet but the changes look fine. :+1:

**Comment by flokli** [comment]
It's possible to build a 32bit gitlab via `pkgsi686Linux.gitlab` - verified that locally.

**Comment by flokli** [comment]
`pkgsi686Linux.gitaly` still fails btw:

```
# github.com/libgit2/git2go
go/src/github.com/libgit2/git2go/diff.go:441:2: constant 2147483648 overflows DiffOptionsFlag
```

**Comment by flokli** [comment]
Still, this should be fine to be merged.

**Comment by flokli** [comment]
backported to 19.09 in 84c3cf6b270, ce24a926ace, 23af4044501.

**Comment by talyz** [comment]
@flokli Ah, yeah, that seems to be due to [this issue](https://github.com/libgit2/git2go/issues/487) in git2go. Thanks for backporting!

**Pull request merged**
