### PR TITLE
palemoon: 27.2.1-> 27.4.1

### PR DESCRIPTION
**Pull request by MDeltaX**

### CODE REVIEW

**Review by NeQuissimus — APPROVED** [review]

**Comment by fpletz** [comment]
This update seems to fail to build according to Travis. Could you please check?

**Comment by koenigmaximilian** [comment]
`IOError: [Errno 28] No space left on device`

**Comment by fpletz** [comment]
I'm not sure where this error comes from but it still fails for me on NixOS:

```
 8:20.05 ../bin/icupkg: /nix/store/3z0q05f1law5lsjr9dpfmc9dddfyp4kl-gcc-4.9.4-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /nix/store/k81nxq0j14wdl6yp1imdwyy3fi54k1qz-icu4c-58.2/lib/libicutu.so.58)
 8:20.05 make[7]: *** [Makefile:531: out/build/icudt58l/unames.icu] Error 1
 8:20.05 make[6]: *** [Makefile:147: all-recursive] Error 2
 8:20.05 make[5]: *** [Makefile:59: buildicu] Error 2
 8:20.05 make[4]: *** [/tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/config/recurse.mk:74: config/external/icu/target] Error 2
 8:20.05 make[4]: *** Waiting for unfinished jobs....
 8:20.05 phonet.o
 8:20.34 Unified_cpp_dom_events2.o
 8:21.02 replist.o
 8:21.13 In file included from /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/obj-x86_64-unknown-linux-gnu/gfx/2d/Unified_cpp_gfx_2d1.cpp:2:0:
 8:21.13 /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/gfx/2d/Path.cpp: In function 'void mozilla::gfx::FlattenBezier(const mozilla::gfx::BezierControlPoints&, mozilla::gfx::PathSink*, mozilla::gfx::Float)':
 8:21.13 Warning: -Wmaybe-uninitialized in /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/gfx/2d/Path.cpp: 't2' may be used uninitialized in this function
 8:21.13 /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/gfx/2d/Path.cpp:440:55: warning: 't2' may be used uninitialized in this function [-Wmaybe-uninitialized]
 8:21.13    if (count == 0 || ((t1 < 0 || t1 > 1.0) && ((t2 < 0 || t2 > 1.0) || count == 1)) ) {
 8:21.14                                                        ^
 8:21.62 suggestmgr.o
 8:22.28 Unified_cpp_layout_xul2.o
 8:23.44 Unified_cpp_widget_gtk1.o
 8:23.46 In file included from /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/obj-x86_64-unknown-linux-gnu/dom/indexedDB/Unified_cpp_dom_indexedDB1.cpp:11:0:
 8:23.46 /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/dom/indexedDB/Key.cpp: In static member function 'static void mozilla::dom::indexedDB::Key::DecodeString(const unsigned char*&, const unsigned char*, nsString&)':
 8:23.46 Warning: -Wmaybe-uninitialized in /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/dom/indexedDB/Key.cpp: 'out' may be used uninitialized in this function
 8:23.46 /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/dom/indexedDB/Key.cpp:392:10: warning: 'out' may be used uninitialized in this function [-Wmaybe-uninitialized]
 8:23.46      ++out;
 8:23.46           ^
 8:25.00 libdom_indexedDB.a.desc
 8:25.45 libextensions_spellcheck_hunspell_src.a.desc
 8:25.66 In file included from /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/obj-x86_64-unknown-linux-gnu/gfx/2d/Unified_cpp_gfx_2d0.cpp:47:0:
 8:25.66 /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/gfx/2d/DrawTargetCairo.cpp: In function 'cairo_pattern_t* mozilla::gfx::GfxPatternToCairoPattern(const mozilla::gfx::Pattern&, mozilla::gfx::Float)':
 8:25.66 Warning: -Wmaybe-uninitialized in /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/gfx/2d/DrawTargetCairo.cpp: 'pat' may be used uninitialized in this function
 8:25.66 /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/gfx/2d/DrawTargetCairo.cpp:468:20: warning: 'pat' may be used uninitialized in this function [-Wmaybe-uninitialized]
 8:25.66    cairo_pattern_t* pat;
 8:25.66                     ^
 8:28.33 In file included from /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/obj-x86_64-unknown-linux-gnu/layout/xul/Unified_cpp_layout_xul2.cpp:11:0:
 8:28.33 /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsSprocketLayout.cpp: In member function 'void nsSprocketLayout::AlignChildren(nsIFrame*, nsBoxLayoutState&)':
 8:28.33 Warning: -Wmaybe-uninitialized in /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsSprocketLayout.cpp: 'y' may be used uninitialized in this function
 8:28.33 /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsSprocketLayout.cpp:973:22: warning: 'y' may be used uninitialized in this function [-Wmaybe-uninitialized]
 8:28.33        childRect.y = y;
 8:28.33                       ^
 8:28.33 Warning: -Wmaybe-uninitialized in /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsSprocketLayout.cpp: 'x' may be used uninitialized in this function
 8:28.33 /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsSprocketLayout.cpp:993:22: warning: 'x' may be used uninitialized in this function [-Wmaybe-uninitialized]
 8:28.33        childRect.x = x;
 8:28.33                       ^
 8:28.33 Warning: -Wmaybe-uninitialized in /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsSprocketLayout.cpp: 'isLTR' may be used uninitialized in this function
 8:28.33 /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsSprocketLayout.cpp:989:45: warning: 'isLTR' may be used uninitialized in this function [-Wmaybe-uninitialized]
 8:28.33            x = isLTR ? rightAlign : leftAlign;
 8:28.33                                              ^
 8:28.33 Warning: -Wmaybe-uninitialized in /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsSprocketLayout.cpp: 'maxAscent' may be used uninitialized in this function
 8:28.33 /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsSprocketLayout.cpp:967:25: warning: 'maxAscent' may be used uninitialized in this function [-Wmaybe-uninitialized]
 8:28.33            y = maxAscent - child->GetBoxAscent(aState);
 8:28.33                          ^
 8:28.77 In file included from /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/obj-x86_64-unknown-linux-gnu/layout/xul/Unified_cpp_layout_xul2.cpp:38:0:
 8:28.77 /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsTextBoxFrame.cpp: In member function 'void nsTextBoxFrame::DrawText(nsRenderingContext&, const nsRect&, const nsRect&, const nscolor*)':
 8:28.77 Warning: -Wmaybe-uninitialized in /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsTextBoxFrame.cpp: 'underColor' may be used uninitialized in this function
 8:28.77 /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsTextBoxFrame.cpp:491:36: warning: 'underColor' may be used uninitialized in this function [-Wmaybe-uninitialized]
 8:28.77                            vertical);
 8:28.77                                     ^
 8:28.77 Warning: -Wmaybe-uninitialized in /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsTextBoxFrame.cpp: 'overColor' may be used uninitialized in this function
 8:28.77 /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsTextBoxFrame.cpp:500:36: warning: 'overColor' may be used uninitialized in this function [-Wmaybe-uninitialized]
 8:28.77                            vertical);
 8:28.77                                     ^
 8:28.77 Warning: -Wmaybe-uninitialized in /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsTextBoxFrame.cpp: 'strikeColor' may be used uninitialized in this function
 8:28.77 /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsTextBoxFrame.cpp:582:47: warning: 'strikeColor' may be used uninitialized in this function [-Wmaybe-uninitialized]
 8:28.77                          strikeStyle, vertical);
 8:28.77                                                ^
 8:28.77 Warning: -Wmaybe-uninitialized in /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsTextBoxFrame.cpp: 'strikeStyle' may be used uninitialized in this function
 8:28.77 /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsTextBoxFrame.cpp:582:46: warning: 'strikeStyle' may be used uninitialized in this function [-Wmaybe-uninitialized]
 8:28.77                          strikeStyle, vertical);
 8:28.77                                               ^
 8:28.77 Warning: -Wmaybe-uninitialized in /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsTextBoxFrame.cpp: 'underStyle' may be used uninitialized in this function
 8:28.77 /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsTextBoxFrame.cpp:491:35: warning: 'underStyle' may be used uninitialized in this function [-Wmaybe-uninitialized]
 8:28.77                            vertical);
 8:28.77                                    ^
 8:28.77 Warning: -Wmaybe-uninitialized in /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsTextBoxFrame.cpp: 'overStyle' may be used uninitialized in this function
 8:28.77 /tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/layout/xul/nsTextBoxFrame.cpp:500:35: warning: 'overStyle' may be used uninitialized in this function [-Wmaybe-uninitialized]
 8:28.77                            vertical);
 8:28.77                                    ^
 8:29.77 libgfx_2d.a.desc
 8:30.09 libdom_events.a.desc
 8:31.11 liblayout_xul.a.desc
 8:31.31 libwidget_gtk.a.desc
 8:31.33 make[3]: *** [/tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/config/recurse.mk:37: compile] Error 2
 8:31.33 make[2]: *** [/tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/config/rules.mk:541: default] Error 2
 8:31.33 make[1]: *** [/tmp/nix-build-palemoon-27.4.1.drv-0/palemoon-src/client.mk:398: realbuild] Error 2
 8:31.33 make: *** [client.mk:171: build] Error 2
 8:31.35 219 compiler warnings present.
 8:31.37 Notification center failed: Install the python dbus module to get a notification when the build finishes.
builder for ‘/nix/store/mxfg4fn01a8cx09j9nwpm62j448cixa4-palemoon-27.4.1.drv’ failed with exit code 2
error: build of ‘/nix/store/mxfg4fn01a8cx09j9nwpm62j448cixa4-palemoon-27.4.1.drv’ failed
```

**Comment by koenigmaximilian** [comment]
Yeah, it's an error I don't get on master, but https://github.com/NixOS/nixpkgs/pull/28276/commits/b1686bfd67f997b82efec936f1b6e70451aa13aa fixed it when I tested. Also Travis doesn't report this error anymore: https://travis-ci.org/NixOS/nixpkgs/jobs/264772500

**Review by rnhmjoj — CHANGES_REQUESTED** [review]
Ok, it builds on master. Can you squash the commits?

**Comment by koenigmaximilian** [comment]
done

**Comment by Mic92** [comment]
Thanks!

**Pull request merged**
