### PR TITLE
python-PyQt: 5.6 -> 5.8

### PR DESCRIPTION
**Pull request by NickHu**
###### Motivation for this change

Update qutebrowser dependencies for https://github.com/NixOS/nixpkgs/pull/23244

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Please look at https://github.com/NixOS/nixpkgs/pull/23484 first; this commit is on top of that.

### CODE REVIEW

**Comment by peterhoeg** [comment]
Please run ```nox-review wip``` against this (I'm sure @FRidh will otherwise ask you to)...

```wip``` works against your working tree and as you have already committed the change, the way to invoke nox-review is as follows:

```sh
nox-review wip --against HEAD~2
```

The number 2 is because you have to go 2 commits back.

**Comment by FRidh** [comment]
Here's a Hydra build of most of the Python packages.
https://headcounter.org/hydra/eval/352120

This seems to break pyqt4.

**Comment by FRidh** [comment]
or `nox-review pr 23485`

**Comment by NickHu** [comment]
I have no idea why that happens or how I would fix that. Are we sure it's not caused by the wider change here: http://lists.science.uu.nl/pipermail/nix-dev/2017-February/022900.html ?

**Comment by FRidh** [comment]
`pyqt4` depends directly on `sip`.

```
$ nix-build -A pythonPackages.pyqt4
...
b3y3vfl2p1ma-python2.7-sip-4.19.1/include -I/nix/store/l4v7h3zaiffrnqfqzy60f14h0s1mcp7a-python-2.7.13/include/python2.7 -I../../QtCore -I. -I. -o qpycore_chimera.o qpycore_chimera.cpp
qpycore_chimera.cpp: In member function 'void Chimera::set_flag()':
qpycore_chimera.cpp:557:22: error: 'pyqt4ClassTypeDef' was not declared in this scope
         _is_flag = ((pyqt4ClassTypeDef *)_type)->flags & 0x01;
                      ^
qpycore_chimera.cpp:557:41: error: expected primary-expression before ')' token
         _is_flag = ((pyqt4ClassTypeDef *)_type)->flags & 0x01;
                                         ^
qpycore_chimera.cpp:557:42: error: expected ')' before '_type'
         _is_flag = ((pyqt4ClassTypeDef *)_type)->flags & 0x01;
                                          ^
make[2]: *** [Makefile:290: qpycore_chimera.o] Error 1
make[2]: Leaving directory '/tmp/nix-build-python2.7-PyQt-x11-gpl-4.11.3.drv-0/PyQt-x11-gpl-4.11.3/qpy/QtCore'
make[1]: *** [Makefile:7: all] Error 2
make[1]: Leaving directory '/tmp/nix-build-python2.7-PyQt-x11-gpl-4.11.3.drv-0/PyQt-x11-gpl-4.11.3/qpy'
make: *** [Makefile:3: all] Error 2
builder for ‘/nix/store/x5b16hxjl1v4f0ynkkrvqi7vb77hsrc5-python2.7-PyQt-x11-gpl-4.11.3.drv’ failed with exit code 2
error: build of ‘/nix/store/x5b16hxjl1v4f0ynkkrvqi7vb77hsrc5-python2.7-PyQt-x11-gpl-4.11.3.drv’ failed
```

**Comment by abbradar** [comment]
https://github.com/abbradar/nixpkgs/commit/11f4aded29af552bc72340d017849432dd3e0d7d fixes that for me.

**Comment by abbradar** [comment]
BTW PyQt 5.8.1 is available.

**Comment by abbradar** [comment]
I've merged this in https://github.com/NixOS/nixpkgs/commit/e7a432db1e5a0e221e598b7bdd76262056542441 and https://github.com/NixOS/nixpkgs/commit/0a3b7f994e5995f414b1db3e1d7ca2244220b4e1 and tested locally -- seems fine with PyQt4 update. Thanks!

**Pull request closed without merging**
