### PR TITLE
zoom-us: 5.0.399860.0429 -> 5.0.403652.0509

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change
Zoom complained it was out of date

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by kini — APPROVED** [review]
lgtm

**Review by doronbehar — APPROVED** [review]
Builds and works fine when rebased on latest nixos-unstable channel :+1:.

**Comment by obadz** [comment]
Btw does anyone know why the zoom "build" takes so long? nix-top only shows bash running and yet it takes minutes to do something, just not sure what?

**Comment by doronbehar** [comment]
Yea I also noticed that and it seemed peculiar, it happens here for me:

```
automatically fixing dependencies for ELF files
warning: working around a Linux kernel bug by creating a hole of 2097152 bytes in ‘/nix/store/dcj8q73hv242xxzcgiq3hrk8z40m0f17-zoom-us-5.0.403652.0509/share/zoom-us/.ZoomLauncher-wrapped’
searching for dependencies of /nix/store/dcj8q73hv242xxzcgiq3hrk8z40m0f17-zoom-us-5.0.403652.0509/share/zoom-us/.ZoomLauncher-wrapped
```

I think it's autopatchelfHook that's running there at that "almost stale" phase and it's here where stuff happen:

https://github.com/NixOS/nixpkgs/blob/39b92f6e45534658b49e79c78154df6333af8472/pkgs/build-support/setup-hooks/auto-patchelf.sh#L114-L149

Though I have no idea what makes that function slow.

**Pull request merged**
