### PR TITLE
wealthfolio: init at 1.0.18

### LINKED ISSUE #341027: Package request: wealthfolio
**Project description**

[Wealthfolio](https://wealthfolio.app/) is a free, open-source desktop application built with Tauri that provides investment tracking with local data storage. It has recently gained significant popularity.

**Metadata**

* homepage URL: https://wealthfolio.app/
* source URL: https://github.com/afadil/wealthfolio
* license: LGPL-3.0
* platforms: linux, darwin, windows

I attempted to package this application, and while it successfully builds, when I launch it, I only see an empty window displaying the message: "Could not connect: Connection refused." Unfortunately, I lack experience in packaging Tauri applications for nixpkgs, so I'm hoping someone with more expertise can assist.

```nix
{
  lib,
  fetchFromGitHub,
  copyDesktopItems,
  libsoup,
  makeDesktopItem,
  openssl,
  pkg-config,
  pnpm,
  rustPlatform,
  webkitgtk,
}:

rustPlatform.buildRustPackage rec {
  pname = "wealthfolio";
  version = "1.0.10";

  src = fetchFromGitHub {
    owner = "afadil";
    repo = "wealthfolio";
    rev = "v${version}";
    hash = "sha256-QYa9kreNjnZjzoxlKlEArNQ6oIkhU2CbA5XQiEQiRLs=";
  };

  cargoHash = "sha256-TBaFl3mm5g0SU5UyKSeWpu0/A639qmt1bnOu2BP8xYc=";

  sourceRoot = "${src.name}/src-tauri";

  pnpmDeps = pnpm.fetchDeps {
    inherit pname version src;
    hash = "sha256-VqTMcQUdhJP8ByYkDIW+GTB04XPxJrI5T29+LWY/Hh0=";
  };

  postPatch = ''
    substituteInPlace tauri.conf.json \
      --replace-fail '"distDir": "../dist"' '"distDir": "${pnpmDeps}"' \
      --replace-fail '"beforeBuildCommand": "pnpm build",' '"beforeBuildCommand": "",'
  '';

  nativeBuildInputs = [
    copyDesktopItems
    pkg-config
  ];

  buildInputs = [
    libsoup
    openssl
    webkitgtk
  ];

  postInstall = ''
    mv $out/bin/wealthfolio-app $out/bin/wealthfolio
    install -Dm644 icons/128x128.png $out/share/icons/hicolor/128x128/apps/wealthfolio.png
  '';

  desktopItems = [
    (makeDesktopItem {
      name = "wealthfolio";
      exec = "wealthfolio";
      icon = "wealthfolio";
      desktopName = "Wealthfolio";
      comment = meta.description;
      categories = [ "Office" "Finance" ];
      terminal = false;
    })
  ];

  meta = {
   description = "A Beautiful Private and Secure Desktop Investment Tracking Application";
    homepage = "https://wealthfolio.app/";
    license = lib.licenses.lgpl3;
    mainProgram = "wealthfolio";
    maintainers = with lib.maintainers; [ kilianar ];
    platforms = lib.platforms.linux;
  };
}

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by kilianar**
This pull request adds [wealthfolio](https://github.com/afadil/wealthfolio), a tool for tracking investments with local data storage, at version [1.0.18](https://github.com/afadil/wealthfolio/releases/tag/v1.0.18).

**Note**: Version [1.0.19](https://github.com/afadil/wealthfolio/releases/tag/v1.0.19) is also available but requires `tauri2` support. This support will be introduced in nixpkgs once pull request #346277 has been merged.

Resolves #341027.

## Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by alexandru0-dev** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 351459`

---
### `x86_64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>wealthfolio</li>
  </ul>
</details>

----

Build phase with the following error:

       > ERROR: The Cargo.lock file doesn't exist
       >
       > Cargo.lock is needed to make sure that cargoHash/cargoSha256 doesn't change
       > when the registry is updated.

**Comment by kilianar** [comment]
It’s surprising to see an issue with a missing `Cargo.lock` file, as there is one located in `src-tauri/`. Additionally, I ran `nixpkgs-review` on this pull request, and it completed successfully without any errors.

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 351459`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>wealthfolio</li>
  </ul>
</details>

**Comment by alexandru0-dev** [comment]
@kilianar i've checked with another machine and also ofborg has the same issue
https://logs.ofborg.org/?key=nixos/nixpkgs.351459&attempt_id=4e1963ac-f489-4a41-850a-dee4add8ad49

**Comment by kilianar** [comment]
@alexandru0-dev Thanks for checking again! I was finally able to reproduce the issue. I believe I couldn't replicate it initially because the necessary Cargo dependencies were already present in my Nix store from previous packaging attempts. As a result, Nix bypassed reading `Cargo.lock` and used the cached dependencies instead. Once I deleted the relevant files from my Nix store, the error appeared as expected.

**Comment by alexandru0-dev** [comment]
@kilianar you're welcome :)
btw here is the nixpkgs-review ouput

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 351459`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>wealthfolio</li>
  </ul>
</details>

**Review by alexandru0-dev — APPROVED** [review]

**Pull request merged**
