### PR TITLE
sman: init at 0.2.0

### PR DESCRIPTION
**Pull request by jtojnar**
Old utility of mine for selecting manpage section to be opened

https://github.com/jtojnar/sman

### CODE REVIEW

**Review by ryantm — APPROVED** [review]
seems to work when testing binary, all of the sections seem to have the same name for `sman grep`, but maybe that is expected behavior?

**Comment by jtojnar** [comment]
I see two different `grep`s:

Screenshot from 2020-01-06 12-49-33

**Comment by ryantm** [comment]
I ran `sman grep` and got 

image

**Comment by ryantm** [comment]
It looks like I probably just don't have the `grep (3p)` man page installed.

I played around with some other ones and noticed something that seems wrong:
image
It looks like it assumes whatever is after the first period is the section.

**Comment by jtojnar** [comment]
I fixed these issues in [`0.3.0`](https://github.com/jtojnar/sman/releases/tag/v0.3.0) but in the end I have decided to switch to `man --where --all $page | fzf | xargs man` instead.

**Pull request closed without merging**
