### PR TITLE
cc-wrapper: add `trivialautovarinit` hardening flag support

### PR DESCRIPTION
**Pull request by risicle**
## Description of changes

See discussion of this feature (and some caveats):
 - https://github.com/ossf/wg-best-practices-os-developers/issues/245
 - https://serge-sans-paille.github.io/pythran-stories/trivial-auto-var-init-experiments.html

The `=zero` option is less likely to cause runtime errors, but the clang developers refuse to re-add support for it, believing use of it would lead to developers treating auto-zero-initialized variables as a new c/c++ pseudo-standard. See discussion following from https://lists.llvm.org/pipermail/cfe-dev/2020-April/065221.html .

So rather than using `=zero` for gcc and `=pattern` for llvm, I opted to go for `=pattern` on both compilers for consistency's sake.

Added `hardeningDisable` clauses for several packages I noted this causes problems with.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by cole-h** [comment]
@ofborg eval

**Review by RaitoBezarius — APPROVED** [review]
Thank you for the amazing thread, I spent quite a time reading it, it was very interesting.

If we have documentation on hardening flags, my only demand is to document this and make an important note of the caveat that is uninitialized memory initialization, i.e. very slow on certain type of programs, e.g. systemd.

Diff LGTM; untested.

**Comment by risicle** [comment]
It does feel like we're going to have to bite the bullet at some point and document all the hardening flags. Really, it would be nice to be able to just direct people at the compiler/linker documentation for the equivalent options - but that is often rather brief documentation that often doesn't really explain the full security relevance of the options. Guess we could link to sections of https://best.openssf.org/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.html

**Comment by risicle** [comment]
@ofborg eval

Final check before I merge.

**Comment by RaitoBezarius** [comment]
> @ofborg eval
> 
> Final check before I merge.

Lib tests are failing.

**Pull request merged**
