### PR TITLE
mongosh: 1.6.2 -> 1.8.0

### PR DESCRIPTION
**Pull request by aaronjheng**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by undefined-moe** [comment]
image
mongosh is using node-analytics, however if the telemetry server is unreachable, the whole mongosh process crashes.
It might be better to introduce a patch to remove this `throw`.

**Comment by undefined-moe** [comment]
https://github.com/NixOS/nixpkgs/pull/219450/files#diff-4073dfdd14fadf0272addb93753d3a16c70bdca1c71b9c950dd525c8ef85cd5bR1294

node2nix resolves to `analytics-node@5.2.0` , however it's a deprecated version in npmjs. https://www.npmjs.com/package/analytics-node/?activeTab=versions

npm resolves it to 5.1.2, which works properly.

also see https://github.com/NixOS/nixpkgs/pull/217459

**Comment by aaronjheng** [comment]
> node2nix resolves to analytics-node@5.2.0, however it's a deprecated version in npmjs.

Per https://github.com/mongodb-js/mongosh/blob/9cf53bc336c79e505cf034bf5e6f3b3b3796cf25/packages/cli-repl/package-lock.json#L12, It seems reasonable.

**Comment by undefined-moe** [comment]
Yes, 5.2.0 is a valid reason for ^5.1.2, however 5.2.0 is a deprecated version, it should be excluded from version choices.

**Comment by aaronjheng** [comment]
> mongosh is using node-analytics, however if the telemetry server is unreachable, the whole mongosh process crashes.
It might be better to introduce a patch to remove this throw.

It's more like a network problem. Although, I'm not aginst it.

**Comment by undefined-moe** [comment]
see https://www.npmjs.com/package/analytics-node/v/5.2.0 

I don't think a network problem to a telemetry should crash the whole program.
As the deprecation message says, 5.2.0 is a breaking change (error handling) and should bump a major version.
It is not what ^5.1.2 actually wants.

**Comment by aaronjheng** [comment]
> Yes, 5.2.0 is a valid version for ^5.1.2, however 5.2.0 is a deprecated version, it should be excluded from version choices.
Agreed.

**Comment by aaronjheng** [comment]
As far as I know, the only way to handle this case for node2nix is to use lock file([Using NPM lock files](https://github.com/svanderburg/node2nix#using-npm-lock-files)). But I don't think it's a good way.
I think we should leave it as-is right now if we don't have any other choices .

**Comment by aaronjheng** [comment]
Closing in favor of #217459.

**Pull request closed without merging**
