### PR TITLE
r-modules/generic-builder: Add missing iconv library to fix build on darwin

### PR DESCRIPTION
**Pull request by tricktron**
###### Motivation for this change

Executing `nix-shell --packages 'rWrapper.override{packages = [ rPackages.SparseM ];}'` fails with the error:

```
ld: library not found for -liconv
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/nix/store/saj094y98yryxgi7q1ja36hkbq52yvkf-R-3.6.2/lib/R/share/make/shlib.mk:6: SparseM.so] Error 1
ERROR: compilation failed for package 'SparseM'
```

Adding the missing iconv library for darwin fixes the issue.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by peti — CHANGES_REQUESTED** [review]
Please don't add that package in the generic builder. Add it to `SparseM`, which actually needs it.

**Comment by tricktron** [comment]
@peti Thanks for your quick reply. Sorry for the dumb sounding question but how can I add the missing library to the `SparseM` package? It is a cran package and thus automatically generated with the `generate-r-packages.R` script.

**Comment by peti** [comment]
See https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/r-modules/default.nix#L267 for an example.

**Comment by tricktron** [comment]
@peti Thanks for the hint. I reverted the changes in `generic-builder.nix` and added the libconv library to the r-packages that I used and were breaking directly. In addition, I did a refactoring in a second commit (with statement scope & sorting using `sort -t '=' -k 2`).

**Review by peti — CHANGES_REQUESTED** [review]
Please don't make sweeping changes to that file -- especially, if those changes are unrelated to the actual topic of the PR.

**Comment by tricktron** [comment]
@peti Ok, I reverted the refactoring changes.

**Pull request merged**
