### PR TITLE
sbt: Fix check

### LINKED ISSUE #114462: SBT refuses to build if JRE is overwritten
**Describe the bug**
As of this commit https://github.com/NixOS/nixpkgs/commit/af2e9e50465fadd93ad8637a2512b25d0569194b the package no longer allows overriding the JRE without failing to build.

It still worked as of this commit https://github.com/NixOS/nixpkgs/commit/a7a64001a97b409451cbe1cf2c14bdf2d2e9c87d#diff-97a517ee2aa8880018d9cb752cc14df25a184a5ea0430099f9af57000562e5a8

**To Reproduce**

Note that sbt.nix is the content of the default.nix in the above commit.

```
{ pkgs ? import <nixpkgs> {} }:

let 
sbtRaw = pkgs.callPackage ./sbt.nix { jre = pkgs.jre8; };
in
pkgs.mkShell {
  buildInputs = [
    sbtRaw
  ];
}
```

note it also fails when overriding with `pkgs.jdk11` however `pkgs.jdk` which is the current java15 version works.

**Expected behavior**
Successful build of SBT

**Additional context**

Non Debug output

```
these derivations will be built:
  /nix/store/k6jsvkq719kavnmvscnyxlgld90b6m46-sbt-1.4.7.drv
building '/nix/store/k6jsvkq719kavnmvscnyxlgld90b6m46-sbt-1.4.7.drv'...
unpacking sources
unpacking source archive /nix/store/1g5qdvbg7wycy418vxa661jnqijqqg66-sbt-1.4.7.tgz
source root is sbt
setting SOURCE_DATE_EPOCH to timestamp 1612072156 of file sbt/conf/sbtopts
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/gzdrp665llwvbm2w15bmadvlj2j1bdig-sbt-1.4.7
shrinking /nix/store/gzdrp665llwvbm2w15bmadvlj2j1bdig-sbt-1.4.7/share/sbt/bin/sbtn-x86_64-pc-linux
strip is /nix/store/9f8y44vmjnwdjvzlff0gm3f3g6ycyyqy-binutils-2.35.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/gzdrp665llwvbm2w15bmadvlj2j1bdig-sbt-1.4.7/bin
patching script interpreter paths in /nix/store/gzdrp665llwvbm2w15bmadvlj2j1bdig-sbt-1.4.7
/nix/store/gzdrp665llwvbm2w15bmadvlj2j1bdig-sbt-1.4.7/share/sbt/bin/sbt: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/yyy7wr7r9jwjjqkr1yn643g3wzv010zd-bash-4.4-p23/bin/bash"
checking for references to /tmp/nix-build-sbt-1.4.7.drv-0/ in /nix/store/gzdrp665llwvbm2w15bmadvlj2j1bdig-sbt-1.4.7...
automatically fixing dependencies for ELF files
searching for dependencies of /nix/store/gzdrp665llwvbm2w15bmadvlj2j1bdig-sbt-1.4.7/share/sbt/bin/sbtn-x86_64-pc-linux
  libz.so.1 -> found: /nix/store/7bgshg2z70fpcc7adxfag1lgf45yamxh-zlib-1.2.11/lib/libz.so.1
setting RPATH to: /nix/store/7bgshg2z70fpcc7adxfag1lgf45yamxh-zlib-1.2.11/lib
running install tests
builder for '/nix/store/k6jsvkq719kavnmvscnyxlgld90b6m46-sbt-1.4.7.drv' failed with exit code 1
error: build of '/nix/store/k6jsvkq719kavnmvscnyxlgld90b6m46-sbt-1.4.7.drv' failed
```

**Notify maintainers**
@NeQuissimus 

**Metadata**
```
these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/4js3iv1gkidlmaz19k8v5hkzx5xkwgad-nix-info
copying path '/nix/store/4js3iv1gkidlmaz19k8v5hkzx5xkwgad-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.86, NixOS, 20.09.2483.c5c6009fb43 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.9`
 - channels(grafblutwurst): `"home-manager, nixos-20.09.3301.42809feaa9f, nixpkgs-21.05pre272691.04ac9dcd311"`
 - channels(root): `"nixos-20.09.2483.c5c6009fb43"`
 - nixpkgs: `/home/grafblutwurst/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Motivation for this change
Closes #114462

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NeQuissimus** [comment]
@GrafBlutwurst Can you check whether this addresses your issue?

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 114474` at 8cda3fef run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/13851b9576367e1102038650059ccce4">sbt</a></li> (simpleBuildTool)</li>
    <li><a href="https://gist.github.com/0789ef50f5693540ab67294630ad6ad0">sbt-with-scala-native</a></li></li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/tools/build-managers/sbt/default.nix:28:3:
```
   |
28 |   installPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/patch-phase.md">patch-phase</a>

`patchPhase` should not be overridden, use `postPatch` instead.

Near pkgs/development/tools/build-managers/sbt/default.nix:20:3:
```
   |
20 |   patchPhase = ''
   |   ^
```
</li>
  </ul>
</details>

**Comment by GrafBlutwurst** [comment]
It doesn't seem so. At least with the shell.nix definition as defined in the bug report it doesn't build at all anymore, independent of if I override the jre or not.

Is there a way to get a better error message so i can provide more information?

**Comment by NeQuissimus** [comment]
@GrafBlutwurst Does the actual sbt build fail or the OpenJDK one? The errors posted by @r-rmcgibbo above look like JDK15 is broken.

**Comment by GrafBlutwurst** [comment]
```
these derivations will be built:
  /nix/store/d0dcnycw0q2014hlwygwhkwbknc4bl4j-sbt-1.4.7.drv
building '/nix/store/d0dcnycw0q2014hlwygwhkwbknc4bl4j-sbt-1.4.7.drv'...
unpacking sources
unpacking source archive /nix/store/1g5qdvbg7wycy418vxa661jnqijqqg66-sbt-1.4.7.tgz
source root is sbt
setting SOURCE_DATE_EPOCH to timestamp 1612072156 of file sbt/conf/sbtopts
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/mzvkfgsi8kmmlp12mx70jffqha3bx6aj-sbt-1.4.7
shrinking /nix/store/mzvkfgsi8kmmlp12mx70jffqha3bx6aj-sbt-1.4.7/share/sbt/bin/sbtn-x86_64-pc-linux
strip is /nix/store/9f8y44vmjnwdjvzlff0gm3f3g6ycyyqy-binutils-2.35.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/mzvkfgsi8kmmlp12mx70jffqha3bx6aj-sbt-1.4.7/bin
patching script interpreter paths in /nix/store/mzvkfgsi8kmmlp12mx70jffqha3bx6aj-sbt-1.4.7
/nix/store/mzvkfgsi8kmmlp12mx70jffqha3bx6aj-sbt-1.4.7/share/sbt/bin/sbt: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/yyy7wr7r9jwjjqkr1yn643g3wzv010zd-bash-4.4-p23/bin/bash"
checking for references to /tmp/nix-build-sbt-1.4.7.drv-0/ in /nix/store/mzvkfgsi8kmmlp12mx70jffqha3bx6aj-sbt-1.4.7...
automatically fixing dependencies for ELF files
searching for dependencies of /nix/store/mzvkfgsi8kmmlp12mx70jffqha3bx6aj-sbt-1.4.7/share/sbt/bin/sbtn-x86_64-pc-linux
  libz.so.1 -> found: /nix/store/7bgshg2z70fpcc7adxfag1lgf45yamxh-zlib-1.2.11/lib/libz.so.1
setting RPATH to: /nix/store/7bgshg2z70fpcc7adxfag1lgf45yamxh-zlib-1.2.11/lib
running install tests
builder for '/nix/store/d0dcnycw0q2014hlwygwhkwbknc4bl4j-sbt-1.4.7.drv' failed with exit code 1
error: build of '/nix/store/d0dcnycw0q2014hlwygwhkwbknc4bl4j-sbt-1.4.7.drv' failed
```

This is the full output i get. I also checked with `--debug` but couldn't find an obvious error. I also tried overriding java with both 8 and 11 versions but to no avail

**Comment by NeQuissimus** [comment]
OK, I think I have it reproduced. Let me check a few things and see what is going on.

**Comment by NeQuissimus** [comment]
@GrafBlutwurst I can now build with `jre = jdk15`, `jre = jdk8`, `jre = jdk11` and without redefining `jre`

**Comment by SuperSandro2000** [comment]
> @GrafBlutwurst Does the actual sbt build fail or the OpenJDK one? The errors posted by @r-rmcgibbo above look like JDK15 is broken.

openjdk15 is broken for me.

**Comment by NeQuissimus** [comment]
@ofborg eval

**Comment by GrafBlutwurst** [comment]
@NeQuissimus how are you building it? I just stuck the file as of commit https://github.com/NixOS/nixpkgs/commit/0f4d31313d454d2eb58f1c108ceb65fe07cbde3c into a simple shell 

```
{ pkgs ? import <nixpkgs> {} }:

let 
sbt = pkgs.callPackage ./sbt.nix { };
in
pkgs.mkShell {
  buildInputs = [
    sbt
  ];
}
```

but it still refuses to build.

**Comment by NeQuissimus** [comment]
Let's take the test out :) It works for me but only sometimes, seems way too flaky.

**Comment by GrafBlutwurst** [comment]
It works just fine now locally! It builds successfully with overriding the JRE or without.

**Pull request merged**
