### PR TITLE
netbox: 3.6.3 -> 3.6.6

### PR DESCRIPTION
**Pull request by minijackson**
## Description of changes

Release notes:

- https://github.com/netbox-community/netbox/releases/tag/v3.6.4
- https://github.com/netbox-community/netbox/releases/tag/v3.6.5
- https://github.com/netbox-community/netbox/releases/tag/v3.6.6

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
@ofborg test netbox_3_6

**Comment by minijackson** [comment]
@mweinelt oooh, really good catch. It also seems a recent Postgresql upgrade made the tests fail. I'm pretty sure they passed when I submitted the PR. The psycopg issue can be handled here: #263168

**Comment by minijackson** [comment]
I just included the upgrade to NetBox 3.6.6.

Postgresql issue was fixed, so the tests should pass again.

**Comment by RaitoBezarius** [comment]
@minijackson Please, in the future, don't forget to ping me for the merge explicitly, otherwise I will miss this PR.

**Comment by RaitoBezarius** [comment]
@ofborg test netbox_3_6

Tests are not evaluated because netbox_3_5 is EOL and ofborg bail out.

**Comment by minijackson** [comment]
I should've added: I ran all 3 tests locally, they all passed.

**Pull request merged**
