### PR TITLE
nixos/nginx: add systemd-tmpfiles exclusion of temporary directories

### PR DESCRIPTION
**Pull request by mbey-mw**
Directories used by nginx in the tmp path are only created upon startup and must not be deleted while nginx is running.

cc @dasJ @ajs124 @SuperSandro2000

## Description of changes

Added a systemd-tmpfiles rule to prevent deletion directories created in tmp by nginx. The content of the paths is not excluded from cleaning.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ajs124** [comment]
How does that even happen? I've never seen this before.

**Comment by mbey-mw** [comment]
> How does that even happen? I've never seen this before.

Nginx is used as a proxy and sits there not used for more than 10 days. After that period the nginx_client_body directory is deleted and nginx is unable to store client bodies. Strange use case, but this just happened.

**Comment by RaitoBezarius** [comment]
Could you add a NixOS test that fails before that PR and passes with that PR?

**Comment by mbey-mw** [comment]
> Could you add a NixOS test that fails before that PR and passes with that PR?

I will try that in the second half of next week.

**Review by fpletz — APPROVED** [review]
Although I also didn't experience that before, the behavior seems easy to explain looking at our current default systemd-tmpfiles configs.

We have in `/etc/tmpfiles.d/tmp.conf`:
```
# Clear tmp directories separately, to make them easier to override
q /tmp 1777 root root 10d
q /var/tmp 1777 root root 30d
```

Furthermore in `/etc/tmpfiles.d/systemd-tmp.conf` the root tmp directories are explicitly excluded from cleanup with:
```
# Exclude namespace mountpoints created with PrivateTmp=yes
x /tmp/systemd-private-%b-*
X /tmp/systemd-private-%b-*/tmp
x /var/tmp/systemd-private-%b-*
X /var/tmp/systemd-private-%b-*/tmp
```

The PR looks reasonable enough to me.

**Comment by RaitoBezarius** [comment]
@ofborg test nginx-tmpdir

**Comment by RaitoBezarius** [comment]
Awesome, thank you for the test!

**Review by RaitoBezarius — APPROVED** [review]

**Comment by eyJhb** [comment]
> How does that even happen? I've never seen this before.

I know this is long ago, but I've experienced this multiple times on my 3d printer setup w/ Klipper.
So Klipper is managing my 3d printer, w/ a webinterface for uploading 3d prints, which I may not use in 2-3 weeks, and then suddenly when I needed it, I just got weird error messages. But never made this connection (to systemd-tmpfiles).

Thanks for this PR, I really appreciate not having to restart my RPi each time I want to print (every other week or so) :)

**Pull request merged**
