### PR TITLE
Fix installPhase

### PR DESCRIPTION
**Pull request by a0x77ry**
~ doesn't expand correctly with the result of overwriting config.xml every time the program starts, thus not being able to save an changes in options.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by e1mo — CHANGES_REQUESTED** [review]
First of all, thank you for contributing!

From a quick glance, I don't see anything wrong with your changes (tho I have neither tested them nor attempted to reproduce the original problem), however a couple of "meta" changes are required before this PR can be merged.

Please target the `master` branch instead of `nixos-unstable` (you should be able to edit the Pull Request and select master as the base). Further more, please format your commit message and PR name as outlined in the [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md):

> Format the commit messages in the following way:
> ```
> (pkg-name | nixos/<module>): (from -> to | init at version | refactor | etc)
>
> (Motivation for change. Link to release notes. Additional information.)
> ```

In your case this could look something like this: `zap: fix installPhase`. Please note that not only the PR should be named like this, but also the commit itself. You can update it locally using `git commit --amend` and then `git push --force-with-lease`.

**Comment by drupol** [comment]
Dear @a0x77ry ,

Do you plan to continue working on this?

**Comment by a0x77ry** [comment]
@drupol No. I've solved it on my end.

**Comment by drupol** [comment]
Can we close the pr then ?

**Comment by a0x77ry** [comment]
Yes, of course

**Pull request closed without merging**
