### PR TITLE
ninja: 1.8.2 -> 2018-04-10

### PR DESCRIPTION
**Pull request by Twey**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Twey** [comment]
@matthewbauer Ninja's release hasn't been bumped for a long time, and the git version contains many fixes that aren't in any release, including https://github.com/mesonbuild/meson/issues/3992 which was an issue at my workplace.  The official stance (see comments on that issue) seems to be that distributions should just package the git.

I'm happy to just bump `default.nix` to the git version if you'd prefer, I just thought it would be safer to keep the release packaged in case the git one broke something.  I see similar patterns for several other packages, e.g. `arb`/`arb-git` (though I note that `arb-git` is actually older than `arb`, so maybe not a great example…).

**Comment by matthewbauer** [comment]
Yeah I think we would prefer to just bump ninja. Alternatively, you could just add the patch from https://github.com/ninja-build/ninja/pull/1219.patch with a note about it being in the next released version. This would avoid the potential of including other commits that break things.

**Comment by Twey** [comment]
Okay, changed it to bump. I think it's if anything safer to bump wholesale than to try to back-port patches.

**Comment by Mic92** [comment]
That should go to staging branch first. I would like to also get an opinion from @jtojnar

**Comment by jtojnar** [comment]
I did not look into ninja very much (meson has mostly hide it from me) but, if possible, I would prefer `fetchpatch`ing the PR, there might be many changes for the last year and the risk of breakage would be probably greater. We should probably also let ofborg or hydra build at least some of the packages that depend on ninja to be more certain there were no regressions. Otherwise, I also prefer a single package.

**Comment by orivej** [comment]
@jtojnar seems right that it might be better to pick the relevant commit. I have looked at Ninja commit history and noticed that the master branch introduces this issue: https://github.com/ninja-build/ninja/issues/1418

**Comment by Twey** [comment]
There may be other updates in there that are important to people.  Maybe we should revert to the original approach of having two packages?

**Comment by jtojnar** [comment]
Then they can backport the other patches too. We already have too much of multiple package clutter IMO.

**Comment by orivej** [comment]
I'm OK with a new `ninja-unstable` if that helps you participate in its development (at least by testing it), but nevertheless we should include https://patch-diff.githubusercontent.com/raw/ninja-build/ninja/pull/1219.patch in the default ninja.

**Comment by vcunat** [comment]
ninja-1.9.0 has been released: https://github.com/ninja-build/ninja/releases/tag/v1.9.0

**Comment by vcunat** [comment]
Oh, merged as https://github.com/NixOS/nixpkgs/pull/55008

**Comment by Twey** [comment]
Yep, I decided to leave this minefield alone and push ninja for a proper release instead. Thanks @vcunat :)

**Pull request closed without merging**
