### PR TITLE
go: add 1.6 compiler and packages

### PR DESCRIPTION
**Pull request by edef1c**
TODO:
- [x] test on Linux
- [ ] test on OS X

/cc @copumpkin

### CODE REVIEW

**Comment by nathan7** [comment]
Other concerns: should this bootstrap from Go 1.4 (what it does now) or should it use Go 1.5 to bootstrap?

**Comment by nathan7** [comment]
Ran into a test failure on OS X:
```
--- FAIL: TestDwarfAranges (0.83s)
	runtime-lldb_test.go:218: Missing aranges section
FAIL
FAIL	runtime	21.068s
```

**Comment by nathan7** [comment]
The test failure seems to be harmless, and disabling the test gets me a bunch further.
However, there's a lot of `ld: warning: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation, ignoring unexpected dylib file`, and the `misc/cgo/stdio` tests are failing, which might be because that warning shows up in the `go run` output (?)

**Comment by zimbatm** [comment]
1.4 is fine for now for bootstrap. 1.5 would work but then itself bootstrap on 1.4 which isn't ideal IMO.

**Comment by cstrahan** [comment]
Thanks @nathan7!

**Comment by cstrahan** [comment]
(Any additional teaks for OSX can be added later.)

**Pull request merged**
