### PR TITLE
gcc: fix libgccjit cross

### PR DESCRIPTION
**Pull request by ghost**
###### Description of changes

Before this commit, `pkgsCross.*.libgccjit` would fail to build for two reasons:

1. Apparently `--enable-lang=jit` requires `--enable-plugin`, but   the configury is unaware of this requirement.  The failure mode   is difficult to diagnose; the build fails with a compile error   due to `<dlfcn.h>` not being included.

2. libcCross and threadsCross were not being passed to libgccjit in   all-packages.nix.  These are boilerplate parameters that are   repeated several times in all-packages.nix, so at some point we   should probably make them default arguments of   gcc/${version}/default.nix.

This commit fixes the two problems above, respectively, by:

1. Adding an `assert` to check for the unsupported combination and   provide feedback at eval time.

2. Passing the missing parameters.

###### Things done

- Built on platform(s)
  - [x] aarch64-linux (`pkgsCross.aarch64.libgccjit` on x86_64-linux)

### CODE REVIEW

**Comment by amjoseph-nixpkgs** [comment]
@ofborg build pkgsCross.aarch64-multiplatform.libgccjit

**Comment by amjoseph-nixpkgs** [comment]
Hrm, apparently this only works for gcc>=11, so it will have to wait for #209870

**Comment by ameyp** [comment]
@amjoseph-nixpkgs #209870 has been merged, any chance you could pick this back up?

**Comment by amjoseph-nixpkgs** [comment]
@ofborg build pkgsCross.aarch64-multiplatform.libgccjit

**Comment by amjoseph-nixpkgs** [comment]
Latest push should work.

The patch needs to go upstream first, and there's some minor cleanup to do.

@ofborg build pkgsCross.aarch64-multiplatform.libgccjit

**Comment by amjoseph-nixpkgs** [comment]
Fixed merge conflict.

**Pull request closed without merging**
