### PR TITLE
Infinality: update fontconfig-ultimate, add cairo patches

### PR DESCRIPTION
**Pull request by abbradar**
###### Motivation for this change

This updates fontconfig-ultimate patches and moves to new presets. Our old preset file was obsolete for some time, and new presets are hardcoded into freetype with Infinality patches. This update accomodates for that, removing our presets and instead allowing user to choose one of the new ones. If user wishes, he or she can override the preset with environment variables.

This also adds cairo infinality patches.
###### Things done
- [x] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This branch is for review only; I indend to merge [this branch](https://github.com/abbradar/nixpkgs/tree/font-updates) instead, which also includes #16730 and will include #17770 later. It needs combined testing before we can merge.

### CODE REVIEW

**Comment by cmfwyp** [comment]
I have an issue with applying the very large Infinality patches from fontconfig-ultimate to FreeType (not the cairo ones) even when fonts.fontconfig.ultimate.enable is set to false. The three options I think we should have are:

* Unmodified (vanilla) FreeType (currently possible if `useEncumberedCode` is false, though other software than FreeType gets Infinality patches)
* FreeType with subpixel rendering enabled (currently not possible without having all the fontconfig-ultimate patches)
* fontconfig-ultimate, with patches applied to FreeType and other software (currently the default, also implies subpixel rendering)

Unfortunately, fontconfig-ultimate hasn't been actively maintained lately and is likely to have some trouble with the 2.7 release of FreeType, which adds a new bytecode hinting mode. (Which was added in 2.6.4 and enabled by default, but that was reverted in 2.6.5.)

**Comment by abbradar** [comment]
I think we should leave Infinality support enabled by default for the upcoming 16.09 release given that we would most likely have freetype 2.6.5 there for which there are updated patches (see https://github.com/NixOS/nixpkgs/pull/17770#issuecomment-240982060).

We also may want to add extra flags to other software to disable those patches (they are independent of each other, i.e. Cairo patches can be used without patching freetype) or say allow option 2 if wanted. I'm lazy to do that myself but PRs would be gladly accepted.

For the future freetype update if Infinality's author won't pick it up again we may move to option 2 by default.

> I have an issue with applying the very large Infinality patches from fontconfig-ultimate to FreeType (not > the cairo ones) even when fonts.fontconfig.ultimate.enable is set to false. 
I'm not sure I understood you correctly there -- why `fonts.fontconfig.ultimate.enable`would solve the problem with applying patches?

**Comment by cmfwyp** [comment]
The issue was that `useEncumberedCode` was a toggle for Infinality rather than just for subpixel rendering, but that is fixed now that there are separate parameters for both, which essentially makes option 2 possible.

My thought was that ultimately (not for 16.09), the values of the `useInfinality` and `enableInfinality` parameters for the packages that have such patches could be changed by `fonts.fontconfig.ultimate.enable`.

**Comment by abbradar** [comment]
Unfortunately, that cannot be done on NixOS easily because of one of primary properties of Nix: dependencies are strictly specified in all packages, and any change in a dependency causes rebuild of everything downstream. For this suggestion it means that if the user changes those options, it would trigger source rebuild of all GUI-related things (since they all use freetype in the end).

That means that we need to rely on runtime switches instead to control such behaviour, which exist both for subpixel rendering (in XML config files I think) and Infinality (via environment variables).

**Pull request closed without merging**
