### PR TITLE
hplip: Fix plugin url and hash

### PR DESCRIPTION
**Pull request by talyz**
###### Motivation for this change
The latest version of the plugin is not available from openprinting.org, therefore installation of `hplipWithPlugin` broke in #76128. This fixes this by switching to a download URL provided by HP.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
This is probably nicer than #78023, WDYT @Kiwi ?

**Comment by Kiwi** [comment]
It's what I would have done if I had checked that link for this version and not the one that was deleted so I would know it worked. ;P So fine by me. Too late now anyway :smile:

**Comment by jerith666** [comment]
I get the following error trying to build this:

```
hash mismatch in fixed-output derivation '/nix/store/dizy1x4xhxs53wzzr77x9h39nm2pjv92-hplip-3.19.6-plugin.run':
  wanted: sha256:1fn8h1a5znjqjh071ifjdywr0xswc14286gwy6h9vvlh8hzrz347
  got:    sha256:1b5gys04kh41gg7r7rzlpdbc2f4jirl2ik22cd935mm85k7abfwq
```

**Comment by talyz** [comment]
@jerith666 Hm, your system is trying to build the old version with the new hash, for some reason...

**Comment by jerith666** [comment]
Oh, thanks -- you're right!  That's because I'd reverted the commit from #76128.  I'd assumed I'd get a git conflict when the right fix for that came along, but turns out it touched different parts of the file.

**Pull request merged**
