### PR TITLE
 bmake: 20210420 -> 20210621

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 128118` at 82b64195 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/cd2f0b694d6ee38cf5f8eae2e3f8d444">bozohttpd</a></li>
  </ul>
</details>
<details>
  <summary>5 packages built successfully:</summary>
  <ul>
    <li>bmake</li>
    <li>bozohttpd-minimal</li>
    <li>hikari</li>
    <li>kgt</li>
    <li>libfsm</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Review by alyssais — APPROVED** [review]

**Comment by sternenseemann** [comment]
@liclac Any idea about [the bozohttpd failure on aarch64-linux](https://gist.github.com/cd2f0b694d6ee38cf5f8eae2e3f8d444)? Seems like it hasn't failed on Hydra [so far](https://hydra.nixos.org/job/nixpkgs/trunk/bozohttpd.aarch64-linux).

Wonder if this is a flaky test or a bmake-related problem.

**Comment by sternenseemann** [comment]
@ofborg build bozohttpd

**Comment by risicle** [comment]
On macos 10.15:

```
+make: exec(ksh) failed (No such file or directory)
+*** Error code 1 (continuing)
+
+Stop.
+make: stopped in unit-tests
+exit status 1
Failed tests: shell-ksh
*** Error code 1
```

Is this one of those situations where it's being too clever and seeing macos and assuming ksh?

**Comment by risicle** [comment]
Ah.. because I'm building without the sandbox on darwin, it's detecting the existence of `/bin/ksh` and enabling the `shell-ksh` test.

Sure enough adding

```
  substituteInPlace unit-tests/opt-chdir.exp --replace "File name" "Filename"
  '' + lib.optionalString stdenv.isDarwin ''
    substituteInPlace unit-tests/Makefile --replace 'shell-ksh' '#shell-ksh'
  '';
```

to `postPatch` fixes it.

**Review by thoughtpolice — APPROVED** [review]
lgtm

**Pull request merged**
