### PR TITLE
Plex: update, open ports

### PR DESCRIPTION
**Pull request by jerith666**
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I'm not sure if it's standard practice for network services to open up firewall ports on their own like this, or if it instead needs to be made into an option or put in the documentation.

### CODE REVIEW

**Review by LnL7 — APPROVED** [review]

**Comment by grahamc** [comment]
I'm not sure about opening ports, but I would immediately merge the update and syntax fix if you put those in separately.

**Comment by jerith666** [comment]
Okay, I split up the commits.  Just merge bc102ab if you only want the version bump and syntax fixes.  aff4128 is a separate commit for the network ports.

LMK if you need two separate pull requests as well.

**Comment by grahamc** [comment]
I merged in the first two, thank you!

**Comment by globin** [comment]
We sometimes have a boolean option `openFirewall` as in https://github.com/NixOS/nixpkgs/blob/98a9d815e05dd56aba0f9040d96092335cd90444/nixos/modules/services/monitoring/prometheus/alertmanager.nix#L92

**Comment by Mic92** [comment]
Sometimes, Sometimes not. we should decide on one consistent name: currently we have `openFirewall` and  `openDefaultPorts`.

**Comment by jerith666** [comment]
Okay, I like the idea of a boolean option.  I'll see if I can figure out the most popular name, and maybe even try to introduce some consistency there.  But that should be done in another pull req I think; closing this one out.  Thanks!

**Pull request closed without merging**
