### PR TITLE
Lua: moving some package to the luarocks whitelist

### PR DESCRIPTION
**Pull request by teto**
###### Motivation for this change
Should be easier to maintain in the long run.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by teto** [comment]
CC @7c6f434c

**Comment by teto** [comment]
In my tests 6 months ago with similar packages it worked out fine. I am just worried for mac users but luarocks should adapt its buildprocess accordingly.

**Comment by teto** [comment]
regarding the darwin failure, the chmod is done by luarocks so I wonder what's wrong, maybe it gets a wrong shell  `sh: sw_vers: command not found`.
Is the build flaky https://hydra.nixos.org/job/nixpkgs/gcc8/luaPackages.lgi.x86_64-darwin ?

**Comment by 7c6f434c** [comment]
These are stop signs, not crosses — there are two successful builds and two manually cancelled ones

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build luaPackages.basexx

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build luaPackages.basexx luaPackages.mpack neovim

**Comment by 7c6f434c** [comment]
`chmod` problem is still there…

**Comment by teto** [comment]
@GrahamcOfBorg build luaPackages.basexx luaPackages.mpack

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build luaPackages.basexx luaPackages.mpack

**Comment by 7c6f434c** [comment]
Apparently the patching of `sw_vers` doesn't happen

**Comment by 7c6f434c** [comment]
Apparently we let some wrong `chmod` into the build; the `chmod` command comes from `stdenv`'s `unpackPhase` (can be turned off via `dontMakeSourcesWritable`)

**Comment by alyssais** [comment]
Coming from here:

https://github.com/NixOS/nixpkgs/blob/ae8ae1de154b433dcefa3d23aa3905579179b474/pkgs/development/tools/misc/luarocks/setup-hook.sh#L12

`${unzip}` is expanding to nothing, and so `/bin` is added to PATH.

**Comment by 7c6f434c** [comment]
@alyssais Thanks for the explanation.

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build luaPackages.basexx luaPackages.mpack luaPackages.lgi neovim

**Comment by teto** [comment]
@GrahamcOfBorg build luaPackages.basexx luaPackages.mpack luaPackages.lgi neovim

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build luaPackages.basexx luaPackages.mpack luaPackages.lgi neovim

Aarch64 failure seems to be ENOSPC while building LLVM for Mesa for `lgi`

**Comment by teto** [comment]
I asked on nixos-dev for the machine to be fixed so hopefully there should be no space problem anymore. if darwin passes, I may move unzip to nativeBuildInputs. Is it going to be propagated ? in case someone wants to run `luarocks unpack <src.rock>` (is nativePropagatedBuildInputs a thing  ?)

**Comment by 7c6f434c** [comment]
The manual says yuo spell it wrong. `propagatedNativeBuildInputs` as per https://nixos.org/nixpkgs/manual/#ssec-stdenv-dependencies

**Pull request merged**
