### PR TITLE
Waveterm: init at v0.7.6

### PR DESCRIPTION
**Pull request by Marin-Kitagawa**
## Description of changes

This commit adds a new package: Waveterm with version 0.7.6. This also addresses the issue (package request) #280566 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Please change your commit message(s) to match the [commit message conventions of nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions)! Also change the title of your PR to match the conventions.

**Comment by Marin-Kitagawa** [comment]
@matthiasbeyer Done. Please check now

**Comment by Gliczy** [comment]
You are also updating `notesnook`, this should also be reflected in the title of the PR.

CI complains about the formatting not being respected. You can enter the nix-shell provided by nixpkgs and use `nixfmt` to properly format your files. 

Adding yourself as the maintainer of this package won't work since you are not listed in the `maintainer-list.nix` file, you should add yourself to the list (in it's own separate commit).

Also, you should only have commits for the relevant changes being made, in this PR case you should have 3 commits: `waveterm: init at v0.7.6`, `notesnook: 3.0.8 -> 3.0.13` and lastly `maintainers: add Marin-Kitagawa`.

**Comment by Marin-Kitagawa** [comment]
@Gliczy Yeah. But I have opened a separate PR for the Notesnook (#330464).

**Review by cig0 — CHANGES_REQUESTED** [review]
Hi @Marin-Kitagawa! Please remove the Notesnook bit from this PR so we can move forward with Waveterm :)

**Comment by Marin-Kitagawa** [comment]
@cig0 I have created a new PR. This one got messed up in git. Please refer #330910

**Pull request closed without merging**
