### PR TITLE
lean-language-server: init at 3.4.0

### PR DESCRIPTION
**Pull request by DieracDelta**
###### Description of changes

Add `lean-language-server` to the node packages list. Note this is my first time packaging a node package. As described [here](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/javascript.section.md#adding-and-updating-javascript-packages-in-nixpkgs), I simply added to `node-packages.json` and ran the generate script. This is where most of the large diff stems from.

I've tested this on my local system within neovim. Example usage: 

```
nix run github:DieracDelta/vimconfig -- $SOME_LEAN_FILE
```

Works great AFAICT

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by fufexan — APPROVED** [review]

**Comment by siraben** [comment]
Could you fix the merge conflict?

**Comment by DieracDelta** [comment]
Merge conflicts should be resolved

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 185560` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>pgrok</li>
    <li>pgrok.server</li>
  </ul>
</details>
<details>
  <summary>35 packages built:</summary>
  <ul>
    <li>commitlint</li>
    <li>concurrently</li>
    <li>create-cycle-app</li>
    <li>documenso</li>
    <li>emacsPackages.lsp-bridge</li>
    <li>graphite-cli</li>
    <li>joplin</li>
    <li>lighthouse</li>
    <li>lv_img_conv</li>
    <li>mastodon-bot</li>
    <li>node2nix</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pulp</li>
    <li>pyright</li>
    <li>shout</li>
    <li>sloc</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.plugins.giphy</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-go</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-rust-analyzer</li>
    <li>vimPlugins.coc-sh</li>
    <li>vimPlugins.coc-spell-checker</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-sumneko-lua</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vscode-extensions.rust-lang.rust-analyzer</li>
    <li>wasm-text-gen</li>
    <li>wrangler</li>
  </ul>
</details>

**Comment by siraben** [comment]
LGTM 👍

**Pull request merged**
