### PR TITLE
protonup-rs: init 0.6.0

### PR DESCRIPTION
**Pull request by liperium**
## Description of changes

Lib, CLI and GUI(wip) program to automate the installation and update of Proton-GE
[Github Homepage](https://github.com/auyer/Protonup-rs)

I wasn't able to let tests enabled because of this error: `github::tests::test_fetch_data_from_tag` from the **libprotonup** library.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by 3JlOy-PYCCKUi — CHANGES_REQUESTED** [review]

**Comment by liperium** [comment]
Thanks for the comments @3JlOy-PYCCKUi! I will include them for sure. 
Could I do multiple commits, or do I need to make sure it's all one commit again?

Really appreciate the help, this is my first time contributing to such a big repo.

**Comment by liperium** [comment]
I think I managed to do it. Sorry for the nasty pushes, I have never squashed/reset commits before.
It should be PR ready! Waiting on your feedback.

**Review by 3JlOy-PYCCKUi — APPROVED** [review]

**Comment by liperium** [comment]
@ofborg eval

**Comment by liperium** [comment]
https://github.com/NixOS/nixpkgs/pull/300714

**Pull request closed without merging**
