### PR TITLE
zsh-forgit: add completions

### PR DESCRIPTION
**Pull request by wegank**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 241873` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zsh-forgit</li>
  </ul>
</details>

**Comment by deejayem** [comment]
Were you able to get this to work? When I source `share/zsh/zsh-forgit/git-forgit.zsh` I get `_git-forgit: command not found`

**Comment by wegank** [comment]
Yes. Is `$out/share/zsh/site-functions` in `fpath` on your system?

**Comment by deejayem** [comment]
> Yes. Is `$out/share/zsh/site-functions` in `fpath` on your system?

I have `~/.zsh/plugins/zsh-forgit` in `fpath`, but not the path to `site-functions`.

However, that doesn't seem to help:

```
❯ fpath+="~/.zsh/plugins/zsh-forgit/share/zsh/site-functions"
❯ source ~/.zsh/plugins/zsh-forgit/share/zsh/zsh-forgit/git-forgit.zsh
_git-forgit: command not found
```

(but `~/.zsh/plugins/zsh-forgit/share/zsh/site-functions/_git-forgit` was installed okay).

**Comment by wegank** [comment]
@deejayem Does it change anything if you replace `~/.zsh/plugins/zsh-forgit/share/zsh/site-functions` with an absolute path?

**Comment by deejayem** [comment]
> @deejayem Does it change anything if you replace `~/.zsh/plugins/zsh-forgit/share/zsh/site-functions` with an absolute path?

@wegank no, I get the same error.

**Comment by wegank** [comment]
Hmmm, that's strange. Does moving `_git-forgit` to `$out/share/zsh/zsh-forgit/` work for you? If so, I'll change the derivation.

**Comment by deejayem** [comment]
> Hmmm, that's strange. Does moving `_git-forgit` to `$out/share/zsh/zsh-forgit/` work for you? If so, I'll change the derivation.

No, that gives the same error.

**Review by deejayem — APPROVED** [review]
@wegank I guess you should just merge this if it works for you, as it's not breaking any existing functionality. I will figure out why it's not working for me when I have more time.

**Comment by Janik-Haag** [comment]
Result of `nixpkgs-review pr 241873` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zsh-forgit</li>
  </ul>
</details>

**Review by Janik-Haag — APPROVED** [review]
LGTM

**Pull request merged**
