### PR TITLE
picosnitch: 0.14.0 -> 1.0.1

### PR DESCRIPTION
**Pull request by elesiuta**
## Description of changes

https://github.com/elesiuta/picosnitch/releases

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stunkymonkey** [comment]
Result of `nixpkgs-review pr 263034` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>picosnitch</li>
    <li>picosnitch.dist</li>
  </ul>
</details>

**Comment by elesiuta** [comment]
> Result of `nixpkgs-review pr 263034` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 
> 2 packages failed to build:
> ```
> creating build/bdist.linux-x86_64/wheel/dash-2.13.0.data/data/share/jupyter/lab/extensions
> error: can't copy 'dash/labextension/dist/dash-jupyterlab.tgz': doesn't exist or not a regular file
> /nix/store/bbxdw4rgwwl3gnajri82yidr1nlsfskf-stdenv-linux/setup: line 1596: pop_var_context: head of shell_variables not a function context
> ```

I think this was caused by dash merging JupyterDash into the main repo when the version was bumped here https://github.com/NixOS/nixpkgs/commit/9bfc61135fa0807bd96091773c8ad072c5c038da. Pull request https://github.com/NixOS/nixpkgs/pull/244072 which also builds the jupyter extension (along with the version bump) should resolve this since I see picosnitch and dash were successfully built here https://github.com/NixOS/nixpkgs/pull/244072#issuecomment-1639047857.

**Comment by elesiuta** [comment]
Should build now with https://github.com/NixOS/nixpkgs/pull/266221
@ofborg build picosnitch picosnitch.passthru.tests

**Comment by Stunkymonkey** [comment]
Result of `nixpkgs-review pr 263034` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>picosnitch</li>
    <li>picosnitch.dist</li>
  </ul>
</details>

**Review by Stunkymonkey — APPROVED** [review]

**Pull request merged**
