### PR TITLE
Kernels 2021-11-06

### PR DESCRIPTION
**Pull request by TredwellGit**
###### Things done
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/pull/144361

**Comment by sigprof** [comment]
Is there anything which stops backporting these updates (without 5.15.1, which inclusion is apparently blocked) to 21.05?

Note that the default kernel for 21.05 is 5.10.y, and the 5.10.77 version, which is there at the moment, is severely broken at least for the `nouveau` driver users (although other drivers can be affected too, because the offending change is in the drm core code). The broken change is reverted in 5.10.78: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.10.y&id=bbc920fb320f1c241cc34ac85edaa0058922246a

**Comment by Artturin** [comment]
#145358

**Comment by Ma27** [comment]
Sorry, forgot about this. Will take care of the backports tomorrow!

**Comment by sbourdeauducq** [comment]
``amdgpu`` is also affected and makes machines with AMD GPUs completely unusable. Backport of kernel 5.10.78 to 21.05 is definitely needed.

**Pull request merged**
