### PR TITLE
imagemagick: 7.0.11-14 -> 7.1.0-0

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by erictapen** [comment]
Could you rebase on 9a3f4867099bc868b77817c272dce9f39f808376, which is the current `git merge-base` of staging and master? Makes it easier to build.

**Comment by dotlambda** [comment]
> Could you rebase on [9a3f486](https://github.com/NixOS/nixpkgs/commit/9a3f4867099bc868b77817c272dce9f39f808376), which is the current `git merge-base` of staging and master? Makes it easier to build.

Sadly not possible: 7.0.11-14 only exists in staging so far.

**Comment by erictapen** [comment]
Oh sorry, could have guessed that.

**Review by erictapen — APPROVED** [review]
Builds for me, when cherry-picked on top of 31a8c0e5c4d9f63a17054ea30d7b963c48f5790e.

**Comment by vcunat** [comment]
Aren't the imagemagick backports being a bit too fast?  Upstream bugs [happen](https://github.com/ImageMagick/ImageMagick6/issues/159), so I'd at least expect to wait until the updates get into the `nixos-unstable` channel without causing much regression (unless they include a significant security fix).

**Comment by dotlambda** [comment]
> unless they include a significant security fix

There's no easy way to find out whether they do, so we view every update as security critical.

**Pull request merged**
