### PR TITLE
pleroma: 2.6.3 -> 2.7.0

### PR DESCRIPTION
**Pull request by picnoir**
Changelog: https://git.pleroma.social/pleroma/pleroma/-/releases/v2.7.0

WIP: currently stuck on prometheus_phoenix

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by leona-ya** [comment]
I _think_ (haven't tried yet because of dependency foo) that `prometheus_phoenix` fails because https://github.com/deadtrickster/prometheus-phoenix/pull/19/files is not merged. The library is kinda unmaintained and seems incompatible with modern phoenix?

**Comment by leona-ya** [comment]
I worked a bit on this in the last few hours. It seems that `prometheus_phoenix` is still referenced in the `mix.lock`, but not in any other file in the repo. It also just works when removing it. I created a commit https://github.com/leona-ya/nixpkgs/commit/a19d3c42213759ae61133402f18c7c4e82a29f4c that at least passes the NixOS test. Currently I'm unable to try it on my instance tho. I made a few modifications:

* Update git hex dependencies
* Update nixos test script (it didn't work on my machine and the akkoma one seemed better)
* fix the custom patch
* remove `prometheus_phoenix` from mix.nix

Also I'm sorry for the unsolicited push, that was to the wrong repo.

**Comment by picnoir** [comment]
Oops, I completely forgot this update mid-way through :sweat_smile: 

Sweet! I'll test that on my instance today.

> Also I'm sorry for the unsolicited push, that was to the wrong repo.

Don't be! You're fixing stuff! Don't hesitate to push here.

**Comment by picnoir** [comment]
Erf, hitting the execstartpre timeout once again. The migration should live in its own unit. Modifying that.

**Comment by picnoir** [comment]
Deployed this to my personal instance. So far, it seems to be fine.

I'll test that for the day and will clean the commit history and undraft the PR if I can't spot any regressions.

**Comment by picnoir** [comment]
I don't see anything suspicious in the logs after a full day of use. I think it's ready to be reviewed.

@leona-ya I squashed your fix in the update and set you as co-author. Is such an attribution fine with you?

This is ready for review.

**Comment by leona-ya** [comment]
> @leona-ya I squashed your fix in the update and set you as co-author. Is such an attribution fine with you?

That's perfect for me :)

**Review by fpletz — APPROVED** [review]

**Pull request merged**
