### PR TITLE
haskell-language-server: low-tech solution for removing hls plugins

### PR DESCRIPTION
**Pull request by MangoIV**
## Description of changes

*extremely* low tech solution to easily removing unwanted plugins

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by MangoIV** [comment]
cc @maralorn @Profpatsch

**Comment by maralorn** [comment]
Well, hls does not use the `hls-...-plugin` packages anymore.

**Comment by MangoIV** [comment]
```nix
      packages = [
        "hls-floskell-plugin"
      ];
``` @maralorn so the current solution here doesn't work?

**Comment by maralorn** [comment]
Correct. This change is really new. It hit haskell-updates this night and since then hydra hasn’t compiled our ghc.

**Comment by MangoIV** [comment]
so this hasn't been changed in haskell-updates, yet, either? I will look up how that works then :eyes:

**Comment by MangoIV** [comment]
mmh; but the haskell-languag-server.cabal still says something about library `hls-stan-plugin`, I think I'm missing your point, can you say a bit more?

**Comment by maralorn** [comment]
I think they changed the plugins from being separate cabal packages to being one cabal package with multiple components. That is a significant difference for use because now all of hls builds in one nix-derivation instead of dozens. I think this means that a) what you want to achieve is even easier: Simply disable the stan flag and then hls-stan-plugin won’t be build. However now the hls derivation depends directly on stan and we probably want to set that dependency to null.

**Comment by ncfavier** [comment]
> I think they changed the plugins from being separate cabal packages to being one cabal package with multiple components. That is a significant difference for use because now all of hls builds in one nix-derivation instead of dozens. I think this means that a) what you want to achieve is even easier: Simply disable the stan flag and then hls-stan-plugin won’t be build. However now the hls derivation depends directly on stan and we probably want to set that dependency to null.

Alas, it's not that simple: `./Setup configure` will still try to configure all components, including the ones we don't want to build. There is an option to specify *one* component to be configured (and built) (see https://cabal.readthedocs.io/en/stable/setup-commands.html#runhaskell-setup-hs-configure), but we don't want to build just one either.

AFAICT the only way of completely removing a plugin and its dependencies (as is needed right now to fix `ghc92.haskell-language-server` in `haskell-updates` where `ormolu` doesn't build) would be to patch the cabal file and mark the undesired component as `buildable: False` (in addition to disabling the relevant flag and setting the dependency to `null`).

**Comment by maralorn** [comment]
I had a discussion with michaelpj and they will rework the cabal filenfor the next release so that it will again be easier to disable plugins.

**Pull request closed without merging**
