### PR TITLE
papis: 0.7.5 -> 0.8.1

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @teto @dtzWill @nico202

### CODE REVIEW

**Comment by dtzWill** [comment]
Looks good but I think can be improved a bit:

* release notes mention bash/zsh completions-- I admit I haven't read
  the docs but if these are meant to be installed they don't appear to
  be.
* 0.8.1 was tagged a short time ago, probably a bugfix since so quick?

https://github.com/papis/papis/releases/tag/v0.8.1

On Wed, 27 Feb 2019 05:45:25 -0800, Robert Schütz <notifications@github.com> wrote:
> ###### Motivation for this change
> 
> 
> ###### Things done
> 
> 
> 
> - [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
> - Built on platform(s)
>    - [x] NixOS
>    - [ ] macOS
>    - [ ] other Linux distributions
> - [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
> - [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
> - [x] Tested execution of all binary files (usually in `./result/bin/`)
> - [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
> - [ ] Assured whether relevant documentation is up to date
> - [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
> 
> ---
> 
> cc@teto @dtzWill @nico202 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/NixOS/nixpkgs/pull/56463
> 
> -- Commit Summary --
> 
>   * papis: 0.7.5 -> 0.8
> 
> -- File Changes --
> 
>     M pkgs/tools/misc/papis/default.nix (28)
> 
> -- Patch Links --
> 
> https://github.com/NixOS/nixpkgs/pull/56463.patch
> https://github.com/NixOS/nixpkgs/pull/56463.diff
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/NixOS/nixpkgs/pull/56463
Non-text part: text/html

**Comment by dtzWill** [comment]
Looks like you already did the 0.8.1 bump and shell completion for zsh works once I followed the docs :innocent:.

LGTM!

FWIW, for zsh completion add this to your `.zshrc` or so:

```
eval "$(_PAPIS_COMPLETE=source_zsh papis)"
```

Not the nix-iest but does the trick! :)

**Comment by teto** [comment]
didn't see it was released. As for zsh it would be even better with this in postinstall (tested)
` install -D "scripts/shell_completion/click/papis.zsh" $out/share/zsh/site-functions/_papis`

**Comment by dtzWill** [comment]
Can you push this change, or make a PR doing so?

(if not, let us know and I'm sure someone will, perhaps myself... :))

**Comment by teto** [comment]
my suggestion was not good, I still need to source it. Hopefully papis can change the zsh script so that it works out of the box.

**Pull request merged**
