### PR TITLE
terra updates

### PR DESCRIPTION
**Pull request by thoughtpolice**
###### Motivation

Updates to the latest Terra to fix a few bugs, and also includes a patch to automatically search `NIX_CFLAGS_COMPILE` for C compiler options. This means the following Terra program works out of the box (whereas you had to fix it before):

```lua
#! /usr/bin/env nix-shell
--[[
#! nix-shell -i terra -p terra glibc
--]]

C = terralib.includec("stdio.h")

-- The keyword 'terra' introduces a new Terra function.
terra hello(argc : int, argv : &rawstring)
  -- Here we call a C function from Terra
  C.printf("Hello, Terra!\n")
  return 0
end

hello:compile()
hello:printpretty(false)
hello:disas()
hello(0, nil)
```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS

###### Notify maintainers

cc @jb55

### CODE REVIEW

**Comment by thoughtpolice** [comment]
@GrahamcOfBorg build terra

**Review by jb55 — APPROVED** [review]
Thanks for fixing this up. I vaguely remember running into these issues when I packaged this originally. Made terra hard to work with.

Commits looks ok but they could be `fixup`/`squashed` a bit nicer.

`nix-review pr 69072` :heavy_check_mark:

**Comment by thoughtpolice** [comment]
The evaluator seems to explode on this right now but I can't tell why. Have to ask Graham or something I suppose...

**Comment by Mic92** [comment]
@GrahamcOfBorg eval

**Comment by Mic92** [comment]
Looks like this should be backported to 19.09 as well? Without NIX_CFLAGS_COMPILE support this seems to be not so useful.

**Comment by ivan** [comment]
https://github.com/NixOS/nixpkgs/commit/8025787c745694552ad24afa8ab69dfb3c00cabb#diff-7dd944a54541412ed4394ad3f33de9faR37 is causing a grahamcofborg-eval failure in https://github.com/NixOS/nixpkgs/pull/69388

**Comment by Mic92** [comment]
This was fixed in aad639d8f105639a6aafce252c4ae8126ef91130

**Pull request merged**
