### PR TITLE
Merge openssl 1.1 into staging

### PR DESCRIPTION
**Pull request by lheckemann**
###### Motivation for this change
openssl 1.1 has been merged into master since it had its own hydra jobset. That means we need to merge it into staging. I'm making this PR so @GrahamcOfBorg can evaluate it, to check if I haven't made any silly mistakes while fixing merge conflicts (lots of them because of the pname change).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by vcunat** [comment]
Oh, I haven't noticed this work.  I'm afraid I duplicated much of it now when merging master to staging-next.  In my experience it's a bit better to merge like master <-> staging-next <-> staging and not the spiral-staircase master -> staging -> staging-next -> master.  (Well, for most/easy changes it doesn't matter how you do it.)

**Comment by lheckemann** [comment]
Yeah that's my fault for breaking the merge yesterday, thus not being able to push it until I recovered it this morning… Sorry about that!

**Comment by lheckemann** [comment]
So do you want to merge staging-next into staging?

**Comment by vcunat** [comment]
When the work was done twice, we might as well compare whether my merge and yours arrived at the same result :-)  (after merging into some common staging commit)  At least in my case it's well possible I overlooked some things that weren't caught as evaluation errors (I had to fixup two or three of those).

**Comment by edolstra** [comment]
I don't get this PR. If master already has openssl 1.1, then why does openssl 1.1 specifically need to be merged into staging? Shouldn't we just merge master into staging?

**Comment by vcunat** [comment]
git reports conflicts in very many files, so it's not just a trivial step.  (I know of no other motivation.)

**Comment by FRidh** [comment]
If it's in master then master needs to be merged into staging-next and
staging-next into staging.

**Pull request closed without merging**
