### PR TITLE
dart: 3.5.1 -> 3.5.2

### PR DESCRIPTION
**Pull request by alyssais**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by RossComputerGuy** [comment]
Result of `nixpkgs-review pr 338250` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>rstudio</li>
    <li>rstudio-server</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>flutterPackages-source.v3_13</li>
    <li>flutterPackages-source.v3_16</li>
  </ul>
</details>
<details>
  <summary>27 packages built:</summary>
  <ul>
    <li>dart</li>
    <li>dart-sass</li>
    <li>dart-sass.pubcache</li>
    <li>domine</li>
    <li>domine.pubcache</li>
    <li>expidus.calculator</li>
    <li>expidus.calculator.debug</li>
    <li>expidus.calculator.pubcache</li>
    <li>expidus.file-manager</li>
    <li>expidus.file-manager.debug</li>
    <li>expidus.file-manager.pubcache</li>
    <li>flutterPackages-source.beta (flutterPackages-source.v3_23)</li>
    <li>flutterPackages-source.v3_24 (flutterPackages-source.stable)</li>
    <li>flutterPackages-source.v3_19</li>
    <li>flutterPackages-source.v3_22</li>
    <li>gitlab</li>
    <li>gitlab-ee</li>
    <li>jekyll</li>
    <li>jsonnet</li>
    <li>jsonnet.doc</li>
    <li>protoc-gen-dart</li>
    <li>protoc-gen-dart.pubcache</li>
    <li>quarto</li>
    <li>quartoMinimal</li>
    <li>shopware-cli</li>
    <li>vscode-runner</li>
    <li>vscode-runner.pubcache</li>
  </ul>
</details>

**Comment by alyssais** [comment]
discourse builds for me on both aarch64-linux and x86_64-linux. What build failure did you get?

**Comment by RossComputerGuy** [comment]
From what I could tell, it was some sort of ruby error with dynamic libraries. I got errors about some missing symbols.

**Comment by alyssais** [comment]
Does it still happen?

**Comment by RossComputerGuy** [comment]
Maybe, I'm trying right now to figure out what exactly is going on.

**Comment by RossComputerGuy** [comment]
Ok, I got an output:
```
virtual-dom@2.1.1 ✔
Done in 0.77s.
Waiting for Redis and PostgreSQL to be ready..
psql: error: connection to server on socket "/build/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
2024-09-05 17:39:14.955 UTC [1454] LOG:  starting PostgreSQL 16.4 on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 13.3.0, 64-bit
2024-09-05 17:39:14.956 UTC [1454] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2024-09-05 17:39:14.959 UTC [1454] LOG:  listening on Unix socket "/build/.s.PGSQL.5432"
2024-09-05 17:39:14.965 UTC [1460] LOG:  database system was shut down at 2024-09-05 17:39:10 UTC
2024-09-05 17:39:14.970 UTC [1454] LOG:  database system is ready to accept connections
CREATE ROLE
CREATE DATABASE
CREATE EXTENSION
CREATE EXTENSION
rake aborted!
LoadError: /nix/store/cibfjk6inyr3p7s5lsfxdf41k9m3qy6k-discourse-ruby-env-3.2.5/lib/ruby/gems/3.2.0/extensions/aarch64-linux/3.2.0/mini_racer-0.8.0/mini_racer_extension.so: undefined symbol: _ZNK2v88TryCatch13HasTerminatedEv (LoadError)
/nix/store/vhknwrzmyyn1v43lgp6lxw07d99da3h6-ruby3.2-mini_racer-0.8.0/lib/ruby/gems/3.2.0/gems/mini_racer-0.8.0/lib/mini_racer.rb:14:in `load'
/nix/store/vhknwrzmyyn1v43lgp6lxw07d99da3h6-ruby3.2-mini_racer-0.8.0/lib/ruby/gems/3.2.0/gems/mini_racer-0.8.0/lib/mini_racer.rb:14:in `<main>'
/nix/store/zvqhnrlwk496dn3qz01lh20zmf8rmrfi-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/runtime.rb:60:in `require'
/nix/store/zvqhnrlwk496dn3qz01lh20zmf8rmrfi-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/nix/store/zvqhnrlwk496dn3qz01lh20zmf8rmrfi-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/runtime.rb:55:in `each'
/nix/store/zvqhnrlwk496dn3qz01lh20zmf8rmrfi-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/runtime.rb:55:in `block in require'
/nix/store/zvqhnrlwk496dn3qz01lh20zmf8rmrfi-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/runtime.rb:44:in `each'
/nix/store/zvqhnrlwk496dn3qz01lh20zmf8rmrfi-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/runtime.rb:44:in `require'
/nix/store/zvqhnrlwk496dn3qz01lh20zmf8rmrfi-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler.rb:212:in `require'
/build/source/config/application.rb:69:in `<top (required)>'
<internal:/nix/store/wyv90cgqcgqq8nza7pj76pyscvgca57j-ruby-3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/nix/store/wyv90cgqcgqq8nza7pj76pyscvgca57j-ruby-3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/build/source/Rakefile:7:in `<top (required)>'
/nix/store/cibfjk6inyr3p7s5lsfxdf41k9m3qy6k-discourse-ruby-env-3.2.5/lib/ruby/gems/3.2.0/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
/nix/store/zvqhnrlwk496dn3qz01lh20zmf8rmrfi-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/cli/exec.rb:58:in `load'
/nix/store/zvqhnrlwk496dn3qz01lh20zmf8rmrfi-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/cli/exec.rb:58:in `kernel_load'
/nix/store/zvqhnrlwk496dn3qz01lh20zmf8rmrfi-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/cli/exec.rb:23:in `run'
/nix/store/zvqhnrlwk496dn3qz01lh20zmf8rmrfi-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/cli.rb:455:in `exec'
/nix/store/zvqhnrlwk496dn3qz01lh20zmf8rmrfi-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/nix/store/zvqhnrlwk496dn3qz01lh20zmf8rmrfi-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/nix/store/zvqhnrlwk496dn3qz01lh20zmf8rmrfi-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/nix/store/zvqhnrlwk496dn3qz01lh20zmf8rmrfi-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/cli.rb:35:in `dispatch'
/nix/store/zvqhnrlwk496dn3qz01lh20zmf8rmrfi-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/nix/store/zvqhnrlwk496dn3qz01lh20zmf8rmrfi-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/cli.rb:29:in `start'
/nix/store/cibfjk6inyr3p7s5lsfxdf41k9m3qy6k-discourse-ruby-env-3.2.5/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/exe/bundle:28:in `block in <top (required)>'
/nix/store/zvqhnrlwk496dn3qz01lh20zmf8rmrfi-bundler-2.5.16/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/nix/store/cibfjk6inyr3p7s5lsfxdf41k9m3qy6k-discourse-ruby-env-3.2.5/lib/ruby/gems/3.2.0/gems/bundler-2.5.16/exe/bundle:20:in `<top (required)>'
/nix/store/wyv90cgqcgqq8nza7pj76pyscvgca57j-ruby-3.2.4/bin/bundle:25:in `load'
/nix/store/wyv90cgqcgqq8nza7pj76pyscvgca57j-ruby-3.2.4/bin/bundle:25:in `<main>'
(See full trace by running task with --trace)
```

**Comment by alyssais** [comment]
And it doesn't happen if you force a rebuild without this change?

**Comment by alyssais** [comment]
I just don't understand how a dart upgrade could have anything to do with Ruby not finding a C++ symbol from v8.

**Comment by RossComputerGuy** [comment]
> And it doesn't happen if you force a rebuild without this change?

Idk how to force a rebuild but this didn't happen in the previous update afaik.

**Comment by RossComputerGuy** [comment]
> I just don't understand how a dart upgrade could have anything to do with Ruby not finding a C++ symbol from v8.

I'm not sure either but as it worked in the previous update, I assume something is causing this PR to fail on aarch64. If you're able to build on aarch64-linux then that's good at least. Although it might be good to fix it in this PR in case Hydra or other people get this error from cascading rebuilds. I'm doing this on my Ampere Altra Q64-22 system which is the same system I used previously.

Previous update where it worked: https://github.com/NixOS/nixpkgs/pull/334510#issuecomment-2306372935

**Comment by alyssais** [comment]
> Idk how to force a rebuild but this didn't happen in the previous update afaik.

nix build has a --rebuild argument.

**Comment by RossComputerGuy** [comment]
> nix build has a --rebuild argument.

```
error: some outputs of '/nix/store/q7aa0dcamxhvkjwyhi8bx6lwnmygb5vs-discourse-assets-3.2.5.drv' are not valid, so checking is not possible
```

**Comment by RossComputerGuy** [comment]
Looking at Hydra, discourse has been failing since 3 days ago so this PR isn't responsible.

**Review by RossComputerGuy — APPROVED** [review]

**Pull request merged**
