### PR TITLE
ffmpeg-full: add vulkan and glslang features 

### PR DESCRIPTION
**Pull request by ckiee**
###### Motivation for this change

I've already been using this change locally for a while with my `shell.nix` and I'd like to avoid patching nixpkgs.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ronthecookie** [comment]
`nixpkgs-review` triggers the OOM killer so I cannot do that unfortunately.

**Review by primeos — APPROVED** [review]
I'm not a FFmpeg maintainer but the diff LGTM and enabling those features for `ffmpeg-full` sounds like a good idea.

From `configure` (doesn't really help much :D):
```
  --enable-vulkan          enable Vulkan code [no]
  --enable-libglslang      enable GLSL->SPIRV compilation via libglslang [no]
```

I would've hoped there was more upstream documentation on those two features but I assume they simply enable some performance optimizations (GPU acceleration) - not sure if only via additional CLI flags or by default, if supported.

**Comment by ronthecookie** [comment]
> I would've hoped there was more upstream documentation on those two features but I assume they simply enable some performance optimizations (GPU acceleration) - not sure if only via additional CLI flags or by default, if supported.

@primeos They might also do that (I don't know) but my reason is the [scale_vulkan](https://github.com/FFmpeg/FFmpeg/blob/master/libavfilter/vf_scale_vulkan.c) filter and friends.

**Comment by ronthecookie** [comment]
Just cherry-picked my commit and https://github.com/NixOS/nixpkgs/pull/118990/commits/72354f8ec17b76e70faf2f6b1f1e7ae9a3b9e3c5 onto nixos-unstable and that seems to build fine too.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 120482` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>ffmpeg-full</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
@ofborg build ffmpeg-full

**Comment by ronthecookie** [comment]
Where's the ofborg output? I'm not familiar with it.

**Comment by primeos** [comment]
I've restarted the build again (did timeout) and it succeeds now.

> Where's the ofborg output? I'm not familiar with it.

You can click on "Details" and then "View more details on OfBorg":
image

---

image

**Comment by bcc32** [comment]
I'm not sure if this is the right place to report this, but I experienced an ffmpeg-full build error on darwin and the error message seems to point to `libglslang`:

```
❯ nix-env -iA nixpkgs.ffmpeg-full
installing 'ffmpeg-full-4.4'
these derivations will be built:
  /nix/store/pd9ngrphk41y9chssqsg3bxix072bjyv-ffmpeg-full-4.4.drv
building '/nix/store/pd9ngrphk41y9chssqsg3bxix072bjyv-ffmpeg-full-4.4.drv'...
unpacking sources
unpacking source archive /nix/store/6a0ghyfms7nm8db2q1pvgvb38h838psi-ffmpeg-4.4.tar.bz2
source root is ffmpeg-4.4
setting SOURCE_DATE_EPOCH to timestamp 1617917322 of file ffmpeg-4.4/VERSION
patching sources
patching script interpreter paths in .
./tools/clean-diff: interpreter directive changed from "#!/bin/sh" to "/nix/store/0hjiwn27k8av06bj17rykr4d5qfs7l29-bash-4.4-p23/bin/sh"
./tools/libav-merge-next-commit: interpreter directive changed from "#!/bin/sh" to "/nix/store/0hjiwn27k8av06bj17rykr4d5qfs7l29-bash-4.4-p23/bin/sh"
./tools/make_chlayout_test: interpreter directive changed from "#!/usr/bin/env perl" to "/nix/store/nr7jmhzbz8xsjz9r28x4cyf9p08x80yz-perl-5.32.1/bin/perl"
./tools/cl2c: interpreter directive changed from "#!/bin/sh" to "/nix/store/0hjiwn27k8av06bj17rykr4d5qfs7l29-bash-4.4-p23/bin/sh"
./tools/unwrap-diff: interpreter directive changed from "#!/bin/sh" to "/nix/store/0hjiwn27k8av06bj17rykr4d5qfs7l29-bash-4.4-p23/bin/sh"
./tools/gen-rc: interpreter directive changed from "#!/bin/sh" to "/nix/store/0hjiwn27k8av06bj17rykr4d5qfs7l29-bash-4.4-p23/bin/sh"
./tools/plotframes: interpreter directive changed from "#!/usr/bin/env perl" to "/nix/store/nr7jmhzbz8xsjz9r28x4cyf9p08x80yz-perl-5.32.1/bin/perl"
./tools/patcheck: interpreter directive changed from "#!/bin/sh" to "/nix/store/0hjiwn27k8av06bj17rykr4d5qfs7l29-bash-4.4-p23/bin/sh"
./tools/murge: interpreter directive changed from "#!/bin/sh" to "/nix/store/0hjiwn27k8av06bj17rykr4d5qfs7l29-bash-4.4-p23/bin/sh"
./tools/missing_codec_desc: interpreter directive changed from "#!/bin/sh" to "/nix/store/0hjiwn27k8av06bj17rykr4d5qfs7l29-bash-4.4-p23/bin/sh"
./tools/dvd2concat: interpreter directive changed from "#!/usr/bin/env perl" to "/nix/store/nr7jmhzbz8xsjz9r28x4cyf9p08x80yz-perl-5.32.1/bin/perl"
./tools/target_dec_fate.sh: interpreter directive changed from "#!/bin/sh" to "/nix/store/0hjiwn27k8av06bj17rykr4d5qfs7l29-bash-4.4-p23/bin/sh"
./tools/bisect-create: interpreter directive changed from "#!/bin/sh" to "/nix/store/0hjiwn27k8av06bj17rykr4d5qfs7l29-bash-4.4-p23/bin/sh"
./compat/cuda/ptx2c.sh: interpreter directive changed from "#!/bin/sh" to "/nix/store/0hjiwn27k8av06bj17rykr4d5qfs7l29-bash-4.4-p23/bin/sh"
./compat/windows/mslink: interpreter directive changed from "#!/bin/sh" to "/nix/store/0hjiwn27k8av06bj17rykr4d5qfs7l29-bash-4.4-p23/bin/sh"
./compat/windows/makedef: interpreter directive changed from "#!/bin/sh" to "/nix/store/0hjiwn27k8av06bj17rykr4d5qfs7l29-bash-4.4-p23/bin/sh"
./compat/solaris/make_sunver.pl: interpreter directive changed from "#!/usr/bin/env perl" to "/nix/store/nr7jmhzbz8xsjz9r28x4cyf9p08x80yz-perl-5.32.1/bin/perl"
./configure: interpreter directive changed from "#!/bin/sh" to "/nix/store/0hjiwn27k8av06bj17rykr4d5qfs7l29-bash-4.4-p23/bin/sh"
./tests/copycooker.sh: interpreter directive changed from "#!/bin/sh" to "/nix/store/0hjiwn27k8av06bj17rykr4d5qfs7l29-bash-4.4-p23/bin/sh"
./tests/fate.sh: interpreter directive changed from "#! /bin/sh" to "/nix/store/0hjiwn27k8av06bj17rykr4d5qfs7l29-bash-4.4-p23/bin/sh"
./tests/fate/source-check.sh: interpreter directive changed from "#!/bin/sh" to "/nix/store/0hjiwn27k8av06bj17rykr4d5qfs7l29-bash-4.4-p23/bin/sh"
./tests/fate-run.sh: interpreter directive changed from "#! /bin/sh" to "/nix/store/0hjiwn27k8av06bj17rykr4d5qfs7l29-bash-4.4-p23/bin/sh"
./ffbuild/pkgconfig_generate.sh: interpreter directive changed from "#!/bin/sh" to "/nix/store/0hjiwn27k8av06bj17rykr4d5qfs7l29-bash-4.4-p23/bin/sh"
./ffbuild/version.sh: interpreter directive changed from "#!/bin/sh" to "/nix/store/0hjiwn27k8av06bj17rykr4d5qfs7l29-bash-4.4-p23/bin/sh"
./doc/doxy-wrapper.sh: interpreter directive changed from "#!/bin/sh" to "/nix/store/0hjiwn27k8av06bj17rykr4d5qfs7l29-bash-4.4-p23/bin/sh"
configuring
configure flags: --disable-static --prefix=/nix/store/dhrqbjnamwz1xw3p9h463qbmmc76yq40-ffmpeg-full-4.4 --target_os=darwin --arch=x86_64 --enable-gpl --enable-version3 --disable-nonfree --enable-shared --enable-pic --cc=clang --disable-small --enable-runtime-cpudetect --disable-lto --enable-gray --enable-swscale-alpha --enable-hardcoded-tables --enable-safe-bitstream-reader --enable-pthreads --disable-w32threads --disable-os2threads --enable-network --enable-pixelutils --enable-ffmpeg --enable-ffplay --enable-ffprobe --enable-avcodec --enable-avdevice --enable-avfilter --enable-avformat --enable-avresample --enable-avutil --enable-postproc --enable-swresample --enable-swscale --enable-doc --disable-htmlpages --enable-manpages --disable-podpages --disable-txtpages --enable-bzlib --enable-libcelt --enable-libdav1d --disable-libfdk-aac --disable-libflite --enable-fontconfig --enable-libfreetype --enable-frei0r --enable-libfribidi --enable-libgme --enable-gnutls --enable-libgsm --enable-ladspa --enable-libmp3lame --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --disable-libdc1394 --enable-iconv --disable-libjack --disable-libmfx --disable-libmodplug --enable-libmysofa --enable-libopus --enable-librsvg --enable-libsrt --enable-libssh --enable-libtheora --disable-libv4l2 --disable-vaapi --enable-vdpau --enable-libvorbis --enable-libvmaf --enable-libvpx --enable-libwebp --enable-xlib --enable-libxcb --enable-libxcb-shm --enable-libxcb-xfixes --enable-libxcb-shape --enable-lzma --disable-nvenc --enable-openal --enable-libopencore-amrnb --disable-opengl --enable-libopenjpeg --disable-openssl --disable-libpulse --disable-librav1e --enable-libsvtav1 --enable-librtmp --enable-sdl2 --enable-libsoxr --enable-libspeex --disable-libvidstab --enable-libvo-amrwbenc --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-zlib --disable-vulkan --enable-libglslang --disable-debug --enable-optimizations --disable-extra-warnings --disable-stripping
ERROR: libglslang not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
builder for '/nix/store/pd9ngrphk41y9chssqsg3bxix072bjyv-ffmpeg-full-4.4.drv' failed with exit code 1
error: build of '/nix/store/pd9ngrphk41y9chssqsg3bxix072bjyv-ffmpeg-full-4.4.drv' failed
```

I built this with `nixpkgs` at a39809ade012.

**Comment by ronthecookie** [comment]
@bcc32 You should probably create a new issue and fill out the bug report template.

Also, I cannot reproduce with `nix-shell -p ffmpeg-full -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/a39809ade0121f374126b5b499173930672b3736.tar.gz`.

**Comment by primeos** [comment]
`(enableFeature (glslang != null) "libglslang")` should avoid this particular error so I assume that the `libglslang` build might be broken on Darwin (in a way where the build succeeds but the headers won't be properly installed or something like that).

I agree with @ronthecookie that a new issue makes more sense (better visibility (e.g. I cannot handle any Darwin issues due to the lack of access to a Darwin system) and you can still link to this PR).

**Comment by bcc32** [comment]
Yep, that's definitely better.  I have created a new issue, thanks!

**Pull request merged**
