### PR TITLE
libbpf 0.7.0 -> 0.8.0, bpftrace: 0.14.1 -> 0.15.0

### PR DESCRIPTION
**Pull request by martinetd**
###### Description of changes

standard update

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by martinetd** [comment]
hmm, ofborg failed on `bpftrace -e 'kprobe:schedule {     printf("tgid: %d", ((struct task_struct*) curtask)->tgid); exit() }'` but it works fine on x86_64

The error message (`stdin:1:42-64: ERROR: Unknown struct/union: 'struct task_struct'` makes me think BTF isn't configured, is there an easy way to check the config options for a foreign arch kernel? @Mic92 you might know?

If it's just BTF missing on the kernel we'd want to make the test conditional, e.g. `zgrep DEBUG_INFO_BTF=y /proc/config.gz` or something (/sys/kernel/btf/vmlinux presence perhaps?); but I'd like to make sure that's the case first.

**Comment by Mic92** [comment]
On the same machine also the new bpftrace works:

```
 sudo ./result/bin/bpftrace -e 'kprobe:schedule { printf("tgid: %d", ((struct task_struct*) curtask)->tgid); exit() }'
Attaching 1 probe...
tgid: 2653551
```

**Comment by martinetd** [comment]
Thanks for looking! That's what I thought... and that just leaves me with no idea why the test fails.

I'll try to abuse work aarch64 board and run the test vm there to see if I can reproduce, but if it runs I don't know where to look next..

**Comment by martinetd** [comment]
So I'm not really sure but after a couple of hours of installing nix, trying to compile bpftrace, adding swap, rebuilding bpftrace, rebuilding my custom kernel with kvm, running tests I could reproduce on my aarch64 board.

It turns out there really isn't DEBUG_BTF in the vm kernel:
```
$ zcat /proc/config.gz | grep BTF
CONFIG_VIDEO_SONY_BTF_MPX=m
CONFIG_PAHOLE_HAS_SPLIT_BTF=y
$ ls /sys/kernel/btf
ls: cannot access '/sys/kernel/btf': No such file or directory
$ uname -a
Linux machine 5.15.43 #1-NixOS SMP Wed May 25 12:42:07 UTC 2022 aarch64 GNU/Linux
$ ls -l /run/booted-system/kernel 
lrwxrwxrwx 1 root root 63 Jan  1  1970 /run/booted-system/kernel -> /nix/store/4ma75nl5x4jfjc0msdgwnhff5s02v1mn-linux-5.15.43/Image
```

I guess we probably can specify what kernel we want somehow rather than checking for BTF as I had initially suggested? I've never picked my kernel so I'm a bit clueless about this, and already spent too much of $work time on free time stuff so I'll leave the rest for later.

**Comment by martinetd** [comment]
@Mic92 ok so I took that kernel and looked a bit more, it looks like it has `CONFIG_DEBUG_INFO_REDUCED` which disables `CONFIG_DEBUG_INFO_BTF`.

Now we're not enabling THAT, but it's been turned on by default in [ed938a4bfc58](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ed938a4bfc58cd86eddcb4b1c9d582a435ffcf7b) ("arm64: defconfig: Use DEBUG_INFO_REDUCED") in 5.13, so we need to disable it back.

What kernel are you running on?

Either way, I think it's unrelated enough to this update that we can merge the bpftool update: we've both confirmed bpftrace works on aarch64 if kernel config is OK.
And I'll send another PR that disables `DEBUG_INFO_REDUCED` for aarch64...

**Comment by martinetd** [comment]
ping -- what should we do about this?
Since we understand the aarch64 failure (incompatible kernel) and that has its own PR I don't think we need to wait for it.

**Pull request merged**
