### PR TITLE
octoprint.python.pkgs.costestimate: 3.3.0 -> 3.4.0

### PR DESCRIPTION
**Pull request by Stunkymonkey**
###### Motivation for this change
[update](https://github.com/OllisGit/OctoPrint-CostEstimation/releases/tag/3.4.0)

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
How did you test this?

> octoprint.plugins.costestimation

That's not a valid attribute exposed by the octoprint package.

Furthermore octoprint currently pins click 7, because it's development is rather slow, so we get

```
ERROR: Could not find a version that satisfies the requirement click<9.0,>=8.0 (from celery) (from versions: none)
ERROR: No matching distribution found for click<9.0,>=8.0
error: builder for '/nix/store/ly64116lw25h8n30zxdjn1pr4vifghj7-python3.9-celery-5.2.1.drv' failed with exit code 1;
```

So I wonder how you got this to build on aarch64-linux, as you claimed. Can you enlighten me?

**Comment by Stunkymonkey** [comment]
I tested it around 5. of december, when the package `celery` was not broken.

Testing can be done by setting: `services.octoprint.plugins = "plugins: with plugins; [ costestimation ]"`

**Comment by mweinelt** [comment]
The PR currently does not fulfil the requiremenents of `CONTRIBUTING.md`.
- The attribute name is invalid, try `nix-build -A <attribute>`, won't. work. The correct attribute is `octoprint.python.pkgs.costestimate`, which you can easily see when browsing the Git history.

Also celery was bumped to 5.2.0 mid november (see d45b0b0f05cd04f00c4f18b0ae3d44492c2a3992), which is when it started requiring `click>=8.0`. As it is, unless OctoPrint itself does not support `click>=8.0`, we'd need to downgrade celery via `packageOverrides`.

**Comment by Stunkymonkey** [comment]
I remember now. I build it on `release-21.05` and rebased it without checking.

**Comment by Stunkymonkey** [comment]
@mweinelt  octoprint is fixed with #151577.

**Pull request merged**
