### PR TITLE
[18.09] flatpak: 0.99.3 -> 1.0.2 (cherry-picked from master)

### PR DESCRIPTION
**Pull request by alexeymuranov**
###### Motivation for this change

Update Flatpak to the first stable version.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by alexeymuranov** [comment]
Possibly because something is messed up in my user config of flatpak, I cannot currently do `flatpak update` on NixOS 18.09:
```console
$ flatpak update
error: While opening repository /home/alexey/.local/share/flatpak/repo: min-free-space-percent and min-free-space-size are mutually exclusive
```

I hope this is fixed in Flatpak 1.0.2: https://github.com/ostreedev/ostree/pull/1685

**Comment by jtojnar** [comment]
Cannot test it but if it works for you I do not see a reason not to merge.

**Comment by alexeymuranov** [comment]
@jtojnar, is there any online documentation about how I could test this? (I might be able to figure out how to build and install a modified application package, but this is a service.)

**Comment by jtojnar** [comment]
Usually, I just run `nix-build nixos/release.nix -A tests.flatpak.x86_64-linux` and `nix-build nixos/release.nix -A tests.xdg-desktop-portal.x86_64-linux`.

**Comment by xeji** [comment]
Yes, it means the tests passed. You can ignore the "vde_switch" error.

**Pull request merged**
