### PR TITLE
sdcc: 4.2.0 -> 4.4.0

### PR DESCRIPTION
**Pull request by vifino**
## Description of changes

Bump to sdcc 4.4.0 required libfx2 changes, also contained in this PR.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vifino** [comment]
Yikes!

Result of `nixpkgs-review pr 265651` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages failed to build:</summary>
  <ul>
    <li>collectd</li>
    <li>glasgow</li>
    <li>glasgow.dist</li>
    <li>libfx2 (python311Packages.fx2)</li>
    <li>libfx2.dist (python311Packages.fx2.dist)</li>
    <li>libsigrok</li>
    <li>pulseview</li>
    <li>python310Packages.fx2</li>
    <li>python310Packages.fx2.dist</li>
    <li>python310Packages.sigrok</li>
    <li>python311Packages.sigrok</li>
    <li>sigrok-cli</li>
    <li>sigrok-firmware-fx2lafw</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>sdcc</li>
  </ul>
</details>

**Comment by vifino** [comment]
Ok, so there is a bunch blocking this:

- https://github.com/whitequark/libfx2/issues/11 (libfx2, fx2 python package, glasgow)
- sigrok-firmware-fx2lafw
  - Needed fixes to fx2lib (https://github.com/djmuhlestein/fx2lib/pull/36) and to actual source code.
  - I am not sure how likely it is that sigrok-firmware-fx2lafw will get a new release anytime soon.
  - There is still my PR #259629 which contains the fixes.

See also: https://sourceforge.net/p/sdcc/mailman/sdcc-devel/thread/CAGjSPUDLCihL71_fv0Px4Ws_sa4E21Pq6yF0%2B6MSsecUFf-c1g%40mail.gmail.com/#msg37851015

**Comment by vifino** [comment]
Once https://github.com/whitequark/libfx2/pull/13 is merged, I can bump that.
When that happens and the sigrok changes get merged, this can be merged.

**Comment by yorickvP** [comment]
@vifino how's this doing? I'm not sure if libfx2 is compatible now

**Comment by whitequark** [comment]
I'm not entirely sure what to do with libfx2, I would have to dedicate some time to understanding the differences in detail, and this always takes a while to investigate. Happy to discuss it on the Glasgow Interface Explorer channel anytime, though.

**Comment by vifino** [comment]
Hey @yorickvP! It's been a while.

libfx2 got one of two changes - but my [simple fix](https://github.com/whitequark/libfx2/commit/b83200466dbed5fbb6fcf6c6f3bbec37121e97de) for the second issue (sdcc dropping pre-GCC 3.0 preprocessor syntax) was not to upstream standards.

I couldn't work out how to rewrite the makefiles to make it more compatible or less hacky.

**Comment by vifino** [comment]
Thanks to @carlossless, libfx2 got a proper fix.
I've bumped the version here and it'll build now.

However, we still need #259629 to be merged in order to make all dependants build.

**Comment by carlossless** [comment]
Hey @vifino, now that https://github.com/NixOS/nixpkgs/pull/259629 is merged, what do you think about opening up this one for review?

As a side-note, [sdcc 4.4.0 was recently released](https://sdcc.sourceforge.net/index.php#News)

**Comment by vifino** [comment]
Hey @carlossless, thanks for reminding me.
Updated to sdcc 4.4.0.

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>17 packages built:</summary>
  <ul>
    <li>collectd</li>
    <li>glasgow</li>
    <li>glasgow.dist</li>
    <li>libfx2 (python311Packages.fx2)</li>
    <li>libfx2.dist (python311Packages.fx2.dist)</li>
    <li>libsigrok</li>
    <li>pulseview</li>
    <li>python311Packages.sigrok</li>
    <li>python312Packages.fx2</li>
    <li>python312Packages.fx2.dist</li>
    <li>python312Packages.sigrok</li>
    <li>sdcc</li>
    <li>sdcc.doc</li>
    <li>sdcc.man</li>
    <li>sigrok-cli</li>
    <li>sigrok-firmware-fx2lafw</li>
    <li>smuview</li>
  </ul>
</details>

**Review by yorickvP — APPROVED** [review]

**Review by carlossless — APPROVED** [review]
LGTM

**Pull request merged**
