### PR TITLE
Licence fixes

### PR DESCRIPTION
**Pull request by lheckemann**
###### Motivation for this change
Some of the licences are incorrectly assumed to be free.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lheckemann** [comment]
cc @c0bw3b who added nposl originally

**Comment by c0bw3b** [comment]
`bsl10` could be removed entirely since it's replaced by Business Software License 1.1 (https://mariadb.com/bsl10 even redirects to https://mariadb.com/bsl11 ). And yes 'free' status of this license is questionable at least.

OTOH: why remove NPOSL ?

**Comment by lheckemann** [comment]
>OTOH: why remove NPOSL ?

Because nothing uses it.

**Comment by c0bw3b** [comment]
(NPOSL is not unfree)
I added the whole OSL family of licenses. Granted OSL-2.1 and OSL-3 are the most likely to be used but since NPOSL is a current (non-obsolete) license and SPDX id it's virtually free to keep it available for new additions to nixpkgs that might look for it.
But otherwise I agree `licenses.nix` doesn't need to contain every SPDX ids possible.

**Comment by lheckemann** [comment]
Oh I see, I misunderstood

>17) Non-Profit Amendment. The name of this amended version of the Open Software License ("OSL 3.0") is "Non-Profit Open Software License 3.0". The original OSL 3.0 license has been amended as follows:
>
>(a) Licensor represents and declares that it is a not-for-profit organization that derives no revenue whatsoever from the distribution of the Original Work or Derivative Works thereof, or from support or services relating thereto.

as meaning that the *licensee* has to be non-profit. Never mind that bit then :)

**Comment by c0bw3b** [comment]
:) That's why I was asking in the first place: I thought you believed NPOSL to be unfree.

But it is OSI approved and used by non-profit **licensors* but for the *licensee* the terms are similar to normal OSL.

**Review by c0bw3b — APPROVED** [review]

**Comment by c0bw3b** [comment]
@Izorkin this means `maxscale` is unfree from now on (just FYI as maintainer)

**Comment by Izorkin** [comment]
@c0bw3b in the package need to change something?

**Comment by lheckemann** [comment]
Backported to 18.09 c7519bd46859b344d507058f151148b02023fbeb 51076ed20c55995f2a6a0a0061b381245ed3db70

**Pull request merged**
