### PR TITLE
staging-next 2024-05-05

### PR DESCRIPTION
**Pull request by vcunat**
According to the [24.05 schedule](https://github.com/NixOS/nixpkgs/issues/303285), this is the last staging-next iteration that might contain breaking changes (except desktop environments).

##### Helpful links

- workflow docs: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#staging
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/306080
- - - 
##### Mass breakages
_nothing notable so far_

### CODE REVIEW

**Comment by NickCao** [comment]
We might want https://github.com/NixOS/nixpkgs/pull/308884 (and possibly https://github.com/NixOS/nixpkgs/pull/309256) in this iteration.

**Comment by vcunat** [comment]
- [ ] `python3Packages.websocket` regressed tests
  - looks reproducible and cross-platform
  - log e.g. https://hydra.nixos.org/build/258898214/nixlog/1/tail
  - I noticed nothing upstream, at a glance: https://github.com/python-websockets/websockets/issues

**Comment by vcunat** [comment]
- [ ] `python311Packages.psycopg2cffi` regressed tests on `x86_64-darwin` (only), blocking a few hundred builds:
 https://hydra.nixos.org/build/258938046/nixlog/3/tail
 maintainer: @lovesegfault

**Comment by drupol** [comment]
Can we have this? https://github.com/NixOS/nixpkgs/pull/310667

**Comment by vcunat** [comment]
Have in what sense?  It is contained in this PR already.

**Comment by drupol** [comment]
> Have in what sense? It is contained in this PR already.

Sorry I didn't see it in time, please ignore my comment then.

**Comment by drupol** [comment]
Would it be possible to add this too? https://github.com/NixOS/nixpkgs/pull/305586

**Pull request merged**
