### PR TITLE
nanovg and monomer can build on darwins

### PR DESCRIPTION
**Pull request by yuanwang-wf**
I think haskell packages nanovg and monomer were marked with badPlatforms with darwin were due to mesa cannot build on darwin. https://github.com/NixOS/nixpkgs/pull/272166 fix mesa build on darwin. I tested build a monomer app on aarch64-darwin, the app renders correctly afaict 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by maralorn** [comment]
This is an autogenerated file. Please locate the lines corresponding to those packages in the hackage2nix-configuration/main.yaml file next to it and adapt them accordingly. Then run `maintainers/scripts/haskell/regenerate-hackage-packages.sh`.

**Comment by maralorn** [comment]
Both files still seem a bit inconsistent.
Please also follow the contributing guide lines and squash everything into one commit.

**Comment by yuanwang-wf** [comment]
> Both files still seem a bit inconsistent. Please also follow the contributing guide lines and squash everything into one commit.

Sorry about that. there are some  webkitgtk changes. I am not sure about them. I think this is ready for another look. thank you for your time

**Comment by maralorn** [comment]
1. Mark this PR a draft.
2. Rebase your commit onto haskell-updates and force push.
3. Change the base of this pr to haskell-updates
4. Unmark draft.

Then maybe rerun the script and hopefully the webkit changes disappear.

**Comment by maralorn** [comment]
Oh, damn. I should have said cherry-pick your commit on top of haskell-updates, not rebase it.

**Comment by yuanwang-wf** [comment]
should i just open a PR to haskell-update branch ?

**Comment by yuanwang-wf** [comment]
should i just open a PR to haskell-update branch ?

**Comment by maralorn** [comment]
In theory this PR is still salvagable, but you can also just open a new one.

**Pull request closed without merging**
