### PR TITLE
moonlight-qt: Support darwin

### PR DESCRIPTION
**Pull request by azuwis**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 239600` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>moonlight-qt</li>
  </ul>
</details>

**Comment by siraben** [comment]
Builds, but I run into the following issue when I try to run it.

```ShellSession
[nix-shell:~/.../nixpkgs-review/pr-239600-1]$ moonlight 
Redirecting log output to /tmp/Moonlight-1687751691.log
Assertion failed: (NSViewIsCurrentlyBuildingLayerTreeForDisplay() != currentlyBuildingLayerTree), function NSViewSetCurrentlyBuildingLayerTreeForDisplay, file NSView.m, line 12783.
Trace/BPT trap: 5
```

**Comment by azuwis** [comment]
> Builds, but I run into the following issue when I try to run it.
> 
> ```
> [nix-shell:~/.../nixpkgs-review/pr-239600-1]$ moonlight 
> Redirecting log output to /tmp/Moonlight-1687751691.log
> Assertion failed: (NSViewIsCurrentlyBuildingLayerTreeForDisplay() != currentlyBuildingLayerTree), function NSViewSetCurrentlyBuildingLayerTreeForDisplay, file NSView.m, line 12783.
> Trace/BPT trap: 5
> ```

Works for me on MacBook Pro M1, macOS 13.3.1:

```
cd ~/src/nixpkgs
nix build -f . moonlight-qt
./result/bin/moonlight
```

I've previously install and uninstall Moonlight using homebrew, but I don't think it's related.

**Comment by siraben** [comment]
Strange, I'm also on 13.3.1 and M1 Pro. Maybe someone in @NixOS/darwin-maintainers can also test?

**Comment by azuwis** [comment]
Anyone knows why x86_64-darwin failed?

```
       > /nix/store/yq2ik7qk45ykqz2pa2dyf34j6jraghhl-apple-framework-AudioToolbox-11.0.0/Library/Frameworks/AudioToolbox.framework/Headers/AudioUnitProperties.h:55:10: fatal error: 'os/workgroup.h' file not found
       > #include <os/workgroup.h>
       >          ^~~~~~~~~~~~~~~~
       > 6 errors generated.
       > make[2]: *** [Makefile.Release:166: release/channel_layout.o] Error 1
       > make[2]: Leaving directory '/private/tmp/nix-build-moonlight-qt-4.3.1.drv-0/source/soundio'
       > make[1]: *** [Makefile:45: release] Error 2
       > make[1]: Leaving directory '/private/tmp/nix-build-moonlight-qt-4.3.1.drv-0/source/soundio'
       > make: *** [Makefile:157: sub-soundio-make_first] Error 2
       For full logs, run 'nix log /nix/store/9yj55x7b5pq0z5fy3zhg05iirj5b5gf1-moonlight-qt-4.3.1.drv'.
```

**Pull request merged**
