### PR TITLE
imv: 4.3.1 -> 4.4.0

### PR DESCRIPTION
**Pull request by SebTM**
###### Description of changes
Update to latest release

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rnhmjoj** [comment]
Can you update the homepage to https://sr.ht/~exec64/imv/?

**Comment by SebTM** [comment]
> Can you update the homepage to https://sr.ht/~exec64/imv/?

Sure, thanks adjusted ✌🏻

**Comment by NickCao** [comment]
The build is failing on darwin, may you fix it or mark it broken?

**Comment by SebTM** [comment]
@ofborg build imv

**Comment by SebTM** [comment]
> The build is failing on darwin, may you fix it or mark it broken?

`> meson.build:94:2: ERROR: Dependency "wayland-client" not found, tried pkgconfig and framework`

I've had a look but I'm not sure why it would depend on this on darwin, so I marked it broken on darwin and aarch64

**Comment by rnhmjoj** [comment]
The aarch64-linux build is fine, is just darwin that's failing, likely because wayland doesn't support it.
Try with this patch:
```diff
diff --git a/pkgs/applications/graphics/imv/default.nix b/pkgs/applications/graphics/imv/default.nix
index b824b435670..22efd5e3d36 100644
--- a/pkgs/applications/graphics/imv/default.nix
+++ b/pkgs/applications/graphics/imv/default.nix
@@ -11,7 +11,7 @@
 , icu
 , pango
 , inih
-, withWindowSystem ? "all"
+, withWindowSystem ? null
 , xorg
 , libxkbcommon
 , libGLU
@@ -27,6 +27,12 @@
 }:
 
 let
+  # default value of withWindowSystem
+  withWindowSystem' =
+         if withWindowSystem != null then withWindowSystem
+    else if stdenv.isLinux then "all"
+    else "x11";
+
   windowSystems = {
     all = windowSystems.x11 ++ windowSystems.wayland;
     x11 = [ libGLU xorg.libxcb xorg.libX11 ];
@@ -47,7 +53,7 @@ let
 in
 
 # check that given window system is valid
-assert lib.assertOneOf "withWindowSystem" withWindowSystem
+assert lib.assertOneOf "withWindowSystem" withWindowSystem'
   (builtins.attrNames windowSystems);
 # check that every given backend is valid
 assert builtins.all
@@ -67,7 +73,7 @@ stdenv.mkDerivation rec {
   };
 
   mesonFlags = [
-    "-Dwindows=${withWindowSystem}"
+    "-Dwindows=${withWindowSystem'}"
     "-Dtest=enabled"
     "-Dman=enabled"
   ] ++ backendFlags;
@@ -87,7 +93,7 @@ stdenv.mkDerivation rec {
     libxkbcommon
     pango
     inih
-  ] ++ windowSystems."${withWindowSystem}"
+  ] ++ windowSystems."${withWindowSystem'}"
     ++ builtins.map (b: backends."${b}") withBackends;
 
   postInstall = ''
@@ -96,7 +102,7 @@ stdenv.mkDerivation rec {
     install -Dm644 ../files/imv.desktop $out/share/applications/
   '';
 
-  postFixup = lib.optionalString (withWindowSystem == "all") ''
+  postFixup = lib.optionalString (withWindowSystem' == "all") ''
     # The `bin/imv` script assumes imv-wayland or imv-x11 in PATH,
     # so we have to fix those to the binaries we installed into the /nix/store
 
@@ -113,6 +119,5 @@ stdenv.mkDerivation rec {
     license = licenses.mit;
     maintainers = with maintainers; [ rnhmjoj markus1189 ];
     platforms = platforms.all;
-    broken = (stdenv.isDarwin || stdenv.isAarch64);
   };
 }
```

**Comment by SebTM** [comment]
Thanks for helping out with a patch, I've updated the PR - let's see what ofborg says :)✌🏻

**Comment by rnhmjoj** [comment]
It's still broken for another reason: can you add a `meta.badPlatforms = platforms.darwin`?

**Comment by SebTM** [comment]
> It's still broken for another reason: can you add a `meta.badPlatforms = platforms.darwin`?

np, or should I also revert the changes from the patch as well? not sure

**Comment by rnhmjoj** [comment]
> np, or should I also revert the changes from the patch as well? not sure

No, that's fine: it more correct this way. Thank you.

**Review by rnhmjoj — APPROVED** [review]

**Pull request merged**
