### PR TITLE
chromedriver: fix build failure on aarch64-darwin

### LINKED ISSUE #329202: Build failure: chromedriver (aarch64-darwin)
### Steps To Reproduce

```
$ nix build github:nixos/nixpkgs#chromedriver
error: builder for '/nix/store/4cnbf5s6c9mqdxi831rjapfqdvd1dq6h-chromedriver-126.0.6478.182.drv' failed with exit code 1;
       last 10 log lines:
       > calling 'envHostTargetHook' function hook 'bintoolsWrapper_addLDVars' /nix/store/04w1mgkhawycg64s4q3n8mkcvma5ppx0-apple-framework-CoreFoundation-11.0.0
       > calling 'envHostTargetHook' function hook 'gatherLibraries' /nix/store/lybzq28v1ay0zac24hp0pw38s76ijvsj-libobjc-11.0.0
       > calling 'envHostTargetHook' function hook 'bintoolsWrapper_addLDVars' /nix/store/lybzq28v1ay0zac24hp0pw38s76ijvsj-libobjc-11.0.0
       > calling 'envHostTargetHook' function hook 'sdkRootHook' /nix/store/lybzq28v1ay0zac24hp0pw38s76ijvsj-libobjc-11.0.0
       > calling 'envHostTargetHook' function hook 'ccWrapper_addCVars' /nix/store/lybzq28v1ay0zac24hp0pw38s76ijvsj-libobjc-11.0.0
       > calling 'envHostTargetHook' function hook 'bintoolsWrapper_addLDVars' /nix/store/lybzq28v1ay0zac24hp0pw38s76ijvsj-libobjc-11.0.0
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/jrz3iszjad55yzzazxlkq4kkcr2mkbzd-chromedriver-mac-arm64.zip
       > calling 'unpackCmd' function hook '_defaultUnpack' /nix/store/jrz3iszjad55yzzazxlkq4kkcr2mkbzd-chromedriver-mac-arm64.zip
       > do not know how to unpack source archive /nix/store/jrz3iszjad55yzzazxlkq4kkcr2mkbzd-chromedriver-mac-arm64.zip
       For full logs, run 'nix log /nix/store/4cnbf5s6c9mqdxi831rjapfqdvd1dq6h-chromedriver-126.0.6478.182.drv'.
```

### Build log

Above has the important part.

### Additional context

`unzip` is missing from `nativeBuildInputs` after https://github.com/NixOS/nixpkgs/commit/4919b62fde5fbeb9a5bc518d0edb813616f5b12e

Fixing the immediate issue then reveals that `autoPatchelfHook` will try to run on darwin, which also doesn't work.

PR incoming.

### Notify maintainers

From the above commit: @K900 @paveloom 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.5.0, macOS 14.5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.6`
 - channels(n8henrie): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/h5m0sr1l5cwqga83zfdm7qbbrnm1iill-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by n8henrie**
Darwin seems to need `unzip` and chokes on `autoPatchelfHook`.

Fixes https://github.com/NixOS/nixpkgs/issues/329202

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by n8henrie** [comment]
cc @goibhniu @primeos @k900 @paveloom

**Comment by K900** [comment]
Is unzip only necessary on Darwin then?

**Comment by n8henrie** [comment]
Hmm, apparently -- I'll make it conditional.

**Comment by K900** [comment]
Wait, I'm confused. How do we have unzip on Linux, but not Darwin? Does our default unpacking logic handle different file types depending on platform? What the fuck

**Comment by n8henrie** [comment]
I was wondering the same.

**Comment by K900** [comment]
Wait, I'm an idiot. We're doing a source build on Linux now, so this expression isn't even hit. We can probably drop all the conditionals and make it Darwin only then, because it's not like there are binaries for other systems anyway.

**Comment by n8henrie** [comment]
Yes, I thought maybe it had been exposed as a separate `-bin` package, but it looks like it just switches on availability of `pkgs.chromium` for platform.

I'd be happy to pull out the linux stuff from `binary.nix` if you think it should be removed.

**Comment by n8henrie** [comment]
Done. As this modified quite a bit of the file I also formatted (RFC style).

**Review by jonochang — APPROVED** [review]
Result of `nixpkgs-review pr 329204` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>selendroid</li>
    <li>selenium-server-standalone</li>
  </ul>
</details>

**Pull request merged**
