### PR TITLE
glamoroustoolkit: 1.0.11 -> 1.0.42

### PR DESCRIPTION
**Pull request by akgrant43**
Packaging changes:

- Work around an issue with patchelf 0.12 and later by using patchelf 0.11 (see https://github.com/NixOS/patchelf/issues/546)
- Set "dontStrip = true" as patchelf 0.11 corrupts libWinit.so
- Add dependencies for new library libWebView.so

## Description of changes

See https://github.com/feenkcom/gtoolkit-vm/releases/tag/v1.0.42

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by eclairevoyant** [comment]
@ofborg eval

**Comment by qbit** [comment]
Result of `nixpkgs-review pr 339546` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>glamoroustoolkit</li>
  </ul>
</details>

**Comment by qbit** [comment]
Builds fine but fails to run for me:

```
[nix-shell:~/.cache/nixpkgs-review/pr-339546-1]$ env RUST_BACKTRACE=full ./results/glamoroustoolkit/bin/GlamorousToolkit
thread 'main' panicked at vm-client-desktop/src/application.rs:108:9:
cannot find any dialog implementation (kdialog/zenity)
stack backtrace:
   0:     0x55c63e4caf15 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1e1a1972118942ad
   1:     0x55c63e4f217b - core::fmt::write::hc090a2ffd6b28c4a
   2:     0x55c63e4c86df - std::io::Write::write_fmt::h8898bac6ff039a23
   3:     0x55c63e4cacee - std::sys_common::backtrace::print::ha96650907276675e
   4:     0x55c63e4cbfa9 - std::panicking::default_hook::{{closure}}::h215c2a0a8346e0e0
   5:     0x55c63e4cbced - std::panicking::default_hook::h207342be97478370
   6:     0x55c63e4cc443 - std::panicking::rust_panic_with_hook::hac8bdceee1e4fe2c
   7:     0x55c63e4cc324 - std::panicking::begin_panic_handler::{{closure}}::h00d785e82757ce3c
   8:     0x55c63e4cb3d9 - std::sys_common::backtrace::__rust_end_short_backtrace::h1628d957bcd06996
   9:     0x55c63e4cc057 - rust_begin_unwind
  10:     0x55c63e318643 - core::panicking::panic_fmt::hdc63834ffaaefae5
  11:     0x55c63e3234f8 - core::panicking::panic_display::h2c7d89f3c8cc83dd
  12:     0x55c63e30e226 - vm_client::application::pick_image_with_dialog::{{closure}}::panic_cold_display::ha9b89bc18959b9db
  13:     0x55c63e323aee - vm_client::application::Application::new::hfd6933855000e198
  14:     0x55c63e322c05 - vm_client::main::h519a8719885c9268
  15:     0x55c63e328b53 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc9db2cb38e9613b5
  16:     0x55c63e323cc9 - std::rt::lang_start::{{closure}}::h9d13807ca0fd8dcb
  17:     0x55c63e4c1620 - std::rt::lang_start_internal::h3ed4fe7b2f419135
  18:     0x55c63e3233b5 - main
  19:     0x7f75231e114e - __libc_start_call_main
  20:     0x7f75231e1209 - __libc_start_main@@GLIBC_2.34
  21:     0x55c63e318cfe - _start
  22:                0x0 - <unknown>

```

**Comment by qbit** [comment]
Maybe because wayland?

**Comment by akgrant43** [comment]
> Maybe because wayland?

That's a bug.  I only tested with an image present, in which case it works:

```
mkdir gt
cd gt
GlamorousToolkit-GetImage
GlamorousToolkit
```

I'll follow up on the bug.

Thanks!

**Comment by qbit** [comment]
Yep, that worked!

**Comment by akgrant43** [comment]
@qbit the dialog should open correctly now if there are no images present, or more than one image present.
Thanks!

**Comment by winterqt** [comment]
Mass ping, please resubmit.

**Pull request closed without merging**
