### PR TITLE
ocamlPackages.zed: 3.1.0 -> 3.2.0, ocamlPackages.lambdaterm: 3.2.0 -> 3.3.1

### PR DESCRIPTION
**Pull request by ulrikstrid**
###### Description of changes

Broken out from #195344 to make it smaller.
These changes need to go in together

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ulrikstrid** [comment]
To not break legacy versions I'm doing the same thing as with `Re` and keeping a old version of `zed` and `lambda-term`

**Comment by vbgl** [comment]
It seems that `utop` must be updated as well.

**Comment by ulrikstrid** [comment]
I gave the same treatment to `utop` as `zed` and `lambda-term`

**Comment by vbgl** [comment]
This needs `graphql_ppx` and `reason` to use Dune 3. See #196774.

**Comment by ulrikstrid** [comment]
> This needs `graphql_ppx` and `reason` to use Dune 3. See #196774.

Where do we want to make these changes?

**Comment by ulrikstrid** [comment]
Sorry, I guess you fixed both on your PR

**Comment by ulrikstrid** [comment]
Is this ready to go now @vbgl? should I rebase on `master` first?

**Comment by vbgl** [comment]
This breaks `prof_spacetime`. Maybe said library can just be removed… ping maintainer @symphorien.

**Comment by ulrikstrid** [comment]
I guess we could also constraint it to `OCaml < 4.08` but maybe it's better to remove it at that point?

**Pull request merged**
