### PR TITLE
python3Packages.duckdb-engine: 0.6.9 -> 0.7.0

### PR DESCRIPTION
**Pull request by cpcloud**
###### Description of changes

Bump duckdb-engine from 0.6.9 -> 0.7.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cpcloud** [comment]
@SuperSandro2000 Mind reviewing this one?

nixpkgs-review will fail until we I can update `ibis-framework`. This PR and a number of others (e.g., #226254) are required to do that though.

**Review by fabaff — COMMENTED** [review]
According to https://github.com/Mause/duckdb_engine/issues/388 was support for SQLAlchemy > 2.0 added but the constraint was not updated. Would require that it's done in the `postPatch` section.

```bash
[...]
       > Executing pipInstallPhase
       > /build/source/dist /build/source
       > Processing ./duckdb_engine-0.6.9-py3-none-any.whl
       > ERROR: Could not find a version that satisfies the requirement sqlalchemy<2.0.0,>=1.3.19 (from duckdb-engine) (from versions: none)
       > ERROR: No matching distribution found for sqlalchemy<2.0.0,>=1.3.19
```

**Comment by cpcloud** [comment]
@fabaff What command did you run to produce that output?

**Comment by cpcloud** [comment]
Also, sqlalchemy 2.0 wasn't officially supported until 0.7.0, so I don't think it makes sense to do anything in `postPatch`. This PR is bumping the version to 0.7.0.

**Comment by SuperSandro2000** [comment]
@ofborg build python310Packages.duckdb-engine

**Pull request merged**
