### PR TITLE
nixos/gitea-actions-runner: settings option to configure daemon

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by emilylange** [comment]
Looks like the config file can be used for label registration as well.
Meaning, it could and probably should replace the current registration logic.

I'll try to look more into this.
Feel free to ping me if you haven't heard back from me in a week :eyes: 
Thanks!

PS: Do you use actually use Gitea/Forgejo Actions? Because I decided against it, for now, until it's more polished.

**Comment by Mic92** [comment]
> Looks like the config file can be used for label registration as well. Meaning, it could and probably should replace the current registration logic.
> 
> I'll try to look more into this. Feel free to ping me if you haven't heard back from me in a week eyes Thanks!
> 
> PS: Do you use actually use Gitea/Forgejo Actions? Because I decided against it, for now, until it's more polished.

Service reminder. It has been two weeks.

**Comment by emilylange** [comment]
Please refactor `services.gitea-actions-runner.instances.<name>.labels` to use `runner.labels = []` in the new `config.yaml` instead.
Thank you

**Comment by pjjw** [comment]
@emilylange apologies for chatter from the peanut gallery, but found this as i'm on the same path, more or less. runner labels in yaml config can only be used with the unreleased dev version of gitea (1.21), and not the currently released (and currently in nixpkgs-unstable) 1.20, so your request here of moving labels to the config file would break the module entirely at this point. can i suggest revisiting when 1.21 makes it in?

**Comment by Mic92** [comment]
This has been tested for a while now. The label change can be done after the next gitea release.

**Comment by Mic92** [comment]
@ofborg eval

**Pull request merged**
