### PR TITLE
snes9x: init at 1.61

### PR DESCRIPTION
**Pull request by thiagokokada**
###### Description of changes

This is done by modifying the current `snes9x-gtk` derivation, including a new `withGtk` option that when enabled will build the `snes9x-gtk`, but when disabled will build `snes9x` instead. `snes9x` has less dependencies than `snes9x-gtk`, having only X11 as a major dependency and a minor one in ALSA. However, the only audio backend supported is ALSA, so audio is only available on Linux.

Still, this has less dependencies than the GTK version, so it should be useful as a minimal version for cross-compilation cases or when porting to new devices. This also builds in macOS, however as I said before, shouldn't have any sound there.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 169366` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>snes9x</li>
    <li>snes9x-gtk</li>
  </ul>
</details>

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 169366` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>snes9x-gtk</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>snes9x</li>
  </ul>
</details>

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 169366` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>snes9x</li>
    <li>snes9x-gtk</li>
  </ul>
</details>

**Comment by AndersonTorres** [comment]
This is not a new package properly speaking, but a new option on an already-existent expression.

A better description/name for this PR would be `snes9x: enable non-GTK build as option` or something like that.

**Comment by thiagokokada** [comment]
> This is not a new package properly speaking, but a new option on an already-existent expression.
> 
> A better description/name for this PR would be `snes9x: enable non-GTK build as option` or something like that.

But it is exposing a new attribute. In this case I would say the difference is less clear. Wouldn't make much sense to say `snes9x: enable non-GTK build as option` like you said because we didn't had `snes9x` before, nor `snes9x-gtk: ...` because this change is not included in `snes9x-gtk`.

**Comment by xfix** [comment]
For me, `snes9x` feels like a different package to `snes9x-gtk`, not really an option of it. Their functionality is different - for example, `unix` has functionality to save video/audio to disk while `gtk` doesn't. Opinions can vary however, as this is very borderline.

**Comment by thiagokokada** [comment]
> For me, `snes9x` feels like a different package to `snes9x-gtk`, not really an option of it. Their functionality is different - for example, `unix` has functionality to save video/audio to disk while `gtk` doesn't. Opinions can vary however, as this is very borderline.

Yeah. I am more adding this to the current derivation since they use the exactly same source code and share some dependencies. But feature wise, they're completely different.

**Comment by thiagokokada** [comment]
Update the PR and details from the message commit to make it clear this is a modified version of the previous `snes9x-gtk` derivation with a new included option that allow to build both `snes9x` and `snes9x-gtk`.

**Comment by AndersonTorres** [comment]
My rationale is: 

The titles of PRs in nixpkgs are usually like one of these

- `funny: init at X.Y.Z`
- `funny: X.Y.Z -> A.B.C`
- `funny: add M dependency`
- `funny: add option`
- `funny: remove`
- and a whole lot of others

The idea of a `funny: init at X.Y.Z` tells us that this commit is including something that never existed before.

But it does not apply here - `snes9x` already exists in Nixpkgs. (Indeed my reaction was "_what? snes9x was not in nixpkgs already??_")

Okay, we call it `snes9x-gtk` , _however_ this is because of an old, [parallel fork](https://code.google.com/archive/p/snes9x-gtk/) that is now integrated to the main project.

**Review by sugar700 — APPROVED** [review]
Both packages work. That said, I think I would prefer those to be separate packages rather than one file full of `withGtk` checks (even if those projects do share a repository), but opinions may vary, so I would like to defer to someone's else opinion here.

**Pull request merged**
