### PR TITLE
kcharselect: initial packaging

### PR DESCRIPTION
**Pull request by schmittlauch**
###### Motivation for this change

The util `kcharselect` is a very useful helper for inserting special characters.

###### Things done

- packaged kcharselect
- added myself to maintainers list

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
While I can query info for specific characters, having more than one of them in the search bar results in no results for me. Does this work for you?

I do get a lot of (non-fatal) warnings on the terminal, not sure if they're relevant:

```
$ result/bin/kcharselect
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
Icon theme "breeze" not found.
Icon theme "breeze" not found.
Error: standard icon theme "breeze" not found!
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
```

**Review by ttuegel — CHANGES_REQUESTED** [review]
The Nix expression looks good. The commit which adds the package should have the message
```
kcharselect: init at 18.12.0
```

**Comment by schmittlauch** [comment]
@ttuegel done. I also did some minor additional fixes (license, parallel building)

**Comment by Infinisil** [comment]
Can you answer my question @schmittlauch ?

**Comment by schmittlauch** [comment]
@Infinisil Sure, sorry I was busy.
I don't get any of these warnings in my build, so probably the environment you're running it from is relevant. Are you running it from a GTK session (Gnome, LXDE, …)?
I myself am running it from a Plasma session.

**Comment by Infinisil** [comment]
Well, you didn't answer my question :P, I asked:

> While I can query info for specific characters, having more than one of them in the search bar results in no results for me. Does this work for you?

(I'm running from just xmonad)

**Comment by schmittlauch** [comment]
@Infinisil Yes, it works for me. Interestingly, only certain multiple-character strings yield results: Whil *no* doesn't show anything, *non* does.
screenshot of kcharselect, searching for `non`

**Comment by Infinisil** [comment]
Ah thanks. Yeah "non" doesn't return any results for me. There probably is some impurity there somewhere.

**Comment by Mic92** [comment]
@Infinisil you need to install it in your profile like any other qt application unfortunately. Worked then for me.

**Comment by schmittlauch** [comment]
> you need to install it in your profile like any other qt application unfortunately. Worked then for me.

Why is this the case again? Interestingly it also worked for me (from a Plasma session) when just running the build result directly.

**Comment by Mic92** [comment]
@schmittlauch I assume the qt/kde plugins where installed in your profile already. There is a pr that tries to address this impurity: https://github.com/NixOS/nixpkgs/pull/44047

**Comment by schmittlauch** [comment]
backport: #53461

**Pull request merged**
