### PR TITLE
404 | debootstrap:  1.0.64.tar.xz -> 1.0.66.tar.gz

### PR DESCRIPTION
**Pull request by deepfire**
The traditional debootstrap source package URL fix.

### CODE REVIEW

**Comment by deepfire** [comment]
I can't seem to reproduce this build-time SIGSEGV on my machine.

**Comment by vcunat** [comment]
Neither can I. I don't like the build log, but it seems the same before and after update.
```
...
chown: invalid user: 'root:kmem'
makedev mem c 1 1 root kmem 0640: failed
...
```

It would be nice if upstream provided stable URLs. Pushed after changing to general ``mirror://debian``, and picked to 14.12.

**Comment by ragnard** [comment]
There's a comment about using git source instead. Seems to me like there's a lenny script in there:

http://anonscm.debian.org/cgit/d-i/debootstrap.git/tree/scripts/lenny

**Comment by vcunat** [comment]
Maybe that would be a solution. If someone tests the package still works when built from git tags, it wouldn't break due to debian updates.

**Pull request closed without merging**
