### PR TITLE
mindustry, mindustry-server: 123.1 -> 124.1

### PR DESCRIPTION
**Pull request by ghost**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112392` at 18cb1f9b run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/1c1abd0c338eba57aaec1cd9ca7e3d1a">mindustry</a></li></li>
    <li><a href="https://gist.github.com/0467169a8fa26693e348d28b7fabeb8c">mindustry-wayland</a></li></li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/72d84f52d3b7aeabcbbf96d40015c3ea">mindustry-server</a></li></li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/games/mindustry/default.nix:149:3:
```
    |
149 |   buildPhase = with lib; ''
    |   ^
```
</li>
  </ul>
</details>

**Review by fgaz — APPROVED** [review]

**Review by fgaz — CHANGES_REQUESTED** [review]
124.1 is out :D

edit: I usually wait half a day or so before making a nixpkgs pr exactly because this keeps happening at every release

**Comment by petabyteboy** [comment]
> 124.1 is out :D
> 
> edit: I usually wait half a day or so before making a nixpkgs pr exactly because this keeps happening at every release

Good point! I didn't know this was so common.

**Review by fgaz — APPROVED** [review]
Thanks!

**Pull request merged**
