### PR TITLE
bun: 0.8.1 -> 1.0.0

### PR DESCRIPTION
**Pull request by coffeeispower**
## Description

[Bun](https://bun.sh) just got to version v1.0, which means it is ready for production, so this PR just changes the version to 1.0, this probably will change javascript forever...
Captura de ecrã de 2023-09-08 15-36-06

### CODE REVIEW

**Review by xhyrom — APPROVED** [review]

**Comment by beeb** [comment]
You beat me to it! Please update the changelog URL as the latest blog post doesn't use the full semver version but rather `1.0` in the URL.

**Review by beeb — CHANGES_REQUESTED** [review]
You beat me to it! Please update the changelog URL in the meta section as the latest blog post doesn't use the full semver version but rather 1.0 in the URL.

Also if you could follow the PR template and https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md guide (amend your commit message to `bun: 0.8.1 -> 1.0.0`)

Ideally you want to add yourself to the [maintainers list](https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix) too, in a separate commit that should come first.

See my version here https://github.com/NixOS/nixpkgs/commit/093a9fdbd8a2a84134e4ef38a9e8bcd834e7ef34

**Comment by coffee-is-power** [comment]
@beeb can you merge now? you can squash the commits to have the right commit message if you want

**Review by beeb — APPROVED** [review]

**Comment by beeb** [comment]
Tested on x86_64-linux and x86_64-darwin. LGTM

**Comment by cdmistman** [comment]
ope, you beat me 😅 #254068

**Review by cdmistman — APPROVED** [review]
lgtm! we have the same relevant diff :)

**Comment by happysalada** [comment]
feel free to tag me for future bun updates.
Thank you for the PR !

**Comment by Jarred-Sumner** [comment]
❤️

**Pull request merged**
