### PR TITLE
cutegram: 2.7.0 -> 2.7.1

### PR DESCRIPTION
**Pull request by AndersonTorres**
##### Things done:
- [x] Tested via `nix.useChroot`.
- [x] Built on platform(s): linux-x64.
- [x] Tested compilation of all pkgs that depend on this change.
- [x] Tested execution of binary products.
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @profpatsch.

---

_Please note, that points are not mandatory._

Also, adding myself as maintainer

### CODE REVIEW

**Comment by jagajaga** [comment]
> Tested execution of binary products (Failing).

This program doesn't work after update?

**Comment by Profpatsch** [comment]
Fails with

```
main.cpp:3:43: fatal error: asemantools/asemanapplication.h: No such file or directory
 #include "asemantools/asemanapplication.h"
```

**Comment by AndersonTorres** [comment]
Oh my... I have upgraded NixOS, and now it is the message.
I will work on it.

**Comment by AndersonTorres** [comment]
And, finally, it runs without problems! :+1:

**Pull request merged**
