### PR TITLE
fonttosfnt: 1.2.1 -> 1.2.2

### PR DESCRIPTION
**Pull request by ncfavier**
https://lists.x.org/archives/xorg-announce/2021-June/003093.html

The reason I'm updating so quickly (and [*abusively coerced*](https://gitlab.freedesktop.org/xorg/app/fonttosfnt/-/merge_requests/11#note_958133) upstream into releasing) is that I want to replace `fontforge` with `fonttosfnt` in the derivation for `dina-font`, now that all spacing bugs seem to be fixed.

Sorry about the large diff for `tarballs.list`, it seems like the last commit introduced its own formatting (@lourkeur, maybe you need to tell your formatter to ignore generated files?).

@rnhmjoj @TredwellGit 

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Tested on at least one font.

### CODE REVIEW

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/pull/126366 was merged, so I find the large diff weird.

**Comment by ncfavier** [comment]
The update script generates derivations with `callPackage` on the same line as the arguments list. That commit breaks those lines, probably because of some automatic formatting. It probably went unseen because the diff was huge anyway (the change affected the whole file).

**Review by TredwellGit — APPROVED** [review]
I ran generate-expr-from-tarballs.pl and got the same result.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126906` at f4eb839c run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>woeusb</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/02bb6b6a9302d4e34bd15062485539da">grub2_pvgrub_image</a></li>
    <li><a href="https://gist.github.com/13bec72d6867efdd7575200fbec9501e">grub2_xen</a></li>
  </ul>
</details>
<details>
  <summary>10 packages built successfully:</summary>
  <ul>
    <li>cherry</li>
    <li>creep</li>
    <li>efont-unicode</li>
    <li>envypn-font</li>
    <li>grub2 (grub2_full ,grub2_light)</li>
    <li>grub2_efi</li>
    <li>siji</li>
    <li>ucs-fonts</li>
    <li>unifont</li>
    <li>xorg.fonttosfnt</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by ncfavier** [comment]
The two grub failures predate this PR.

I've added the license attribute as suggested, should I also add myself as maintainer? It seems like only one `xorg` package has a maintainer, is there some other way of keeping track of maintainership in this package set?

**Comment by lourkeur** [comment]
> @lourkeur, maybe you need to tell your formatter to ignore generated files?

I absolutely do, I have a pre-commit-hook with `nixpkgs-fmt`, sorry about that.

**Comment by ncfavier** [comment]
No worries!

**Pull request merged**
