### PR TITLE
importCargoLock: introduce alternative parameter `lockFileContents`

### PR DESCRIPTION
**Pull request by dermetfan**
###### Motivation for this change

In restricted mode (and therefore with flakes) `builtins.readFile` may not be the result of `builtins.toFile`,
making it impossible to use a generated `lockFile` (with or without IFD),
and thereby causing evaluation to fail if `system != builtins.currentSystem` on Hydra
so the jobs are not delegated to eligible build machines that support that system.

This is done in a way that avoids rebuilds.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
cc @Mic92 @danieldk this looks pretty harmless.

diff LGTM to me

**Review by danieldk — CHANGES_REQUESTED** [review]
Looks good to me, but it would be nice if a test is added for this.

**Comment by dermetfan** [comment]
Test added :slightly_smiling_face:

**Comment by danieldk** [comment]
@ofborg build tests.importCargoLock

**Review by danieldk — APPROVED** [review]
Looks good to me! I don't want to hold up this PR any further, but could you make a follow-up PR that adds this option to the nixpkgs Rust docs?

**Pull request merged**
