### PR TITLE
update vam, vim2nix, fixes 6183

### PR DESCRIPTION
**Pull request by MarcWeber**

### CODE REVIEW

**Comment by jagajaga** [comment]
Can you update `YouCompleteMe`? That will be great in this PR.

**Comment by garbas** [comment]
manually merged [here](http://git.io/b6x1)
@jagajaga i've also update YouCompleteMe to latest

**Comment by jagajaga** [comment]
You forgot to update the name of youcompleteme.

**Comment by garbas** [comment]
update the name? isnt ``youcompleteme = YouCompleteMe;`` already there?

**Pull request closed without merging**
