### PR TITLE
picom-allusive: install manpage, fix meta

### PR DESCRIPTION
**Pull request by eclairevoyant**
## Description of changes

Install manpage and preserve meta attrs (`mainProgram` and `platforms`).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by allusive-dev** [comment]
Hello, please do not make pull requests for my package. I am able to maintain it, however thank you for showing me the suggested changes. Next time please contact me if you want to suggest changes to the package.
Thanks

**Comment by eclairevoyant** [comment]
Um, what?

**Comment by allusive-dev** [comment]
As I said I want to personally manage my package, if you have a change you want made please suggest it to me and I will make a pull request accordingly.

**Comment by eclairevoyant** [comment]
This is a public repo, not your personal one. As long as all contributions follow guidelines, I don't see what your concern is here.

If you have a _technical_ concern with a PR, raise that instead of doing this.

**Comment by allusive-dev** [comment]
> This is a public repo, not your personal one.

I understand this but I do not appreciate my package being updated or modified by other maintainers considering I am held responsible for any issues or other unwanted outcomes that may arise by someone else's changes.

I hope you can understand.

**Comment by eclairevoyant** [comment]
You are not "held responsible" for someone else's changes, as `git blame` exists. And the only "responsibility" is to fix an issue when it arises.

**Comment by allusive-dev** [comment]
I'm not going to argue about this. Please explain your reasons for making changes to the package and why it is necessary.

**Comment by eclairevoyant** [comment]
See #246386 for why `meta.mainProgram` shoul be preserved. Installing manpage and setting `meta.platforms` should be self-explanatory.

**Review by allusive-dev — APPROVED** [review]
As long as it passes ofBorg-eval.
LGTM

**Review by allusive-dev — APPROVED** [review]
LGTM

**Review by h7x4 — APPROVED** [review]
manpage shows up correctly in nix-shell!

- [X] package name fits guidelines
- [X] package version fits guidelines
- [X] package build on x86_64-linux
- [x] executables tested on x86_64-linux (`picom --help` and `picom-trans --help` works, former shows correct version)
- [X] all depending packages build
- [X] patches have a comment describing either the upstream URL or a reason why the patch wasn't upstreamed
- [X] patches that are remotely available are fetched rather than vendored

Result of `nixpkgs-review pr 261530` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>picom-allusive</li>
  </ul>
</details>

**Pull request merged**
