### PR TITLE
nushell 0.100.0 -> 0.101.0

### PR DESCRIPTION
**Pull request by MisileLab**
https://www.nushell.sh/blog/2024-12-24-nushell_0_101_0.html

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by cptpiepmatz** [comment]
I just updated my highlight plugin to [v1.4.2+0.101.0](https://github.com/cptpiepmatz/nu-plugin-highlight/releases/tag/v1.4.2%2B0.101.0).

**Comment by MisileLab** [comment]
> I just updated my highlight plugin to [v1.4.2+0.101.0](https://github.com/cptpiepmatz/nu-plugin-highlight/releases/tag/v1.4.2%2B0.101.0).

currently I'm running nixpkgs-review, so I'll update it after that.

**Comment by MisileLab** [comment]
> I just updated my highlight plugin to [v1.4.2+0.101.0](https://github.com/cptpiepmatz/nu-plugin-highlight/releases/tag/v1.4.2%2B0.101.0).

currently I'm running nixpkgs-review, so I'll update it after that.

**Comment by cptpiepmatz** [comment]
While you're at it, maybe take a look at the description text of the highlight plugin, I think that's the description for another plugin.

**Comment by MisileLab** [comment]
> While you're at it, maybe take a look at the description text of the highlight plugin, I think that's the description for another plugin.

I didn't write that description, but I'll look at it, thanks.

**Comment by MisileLab** [comment]
--------- Report for 'x86_64-linux' ---------
1 package failed to build:
nushellPlugins.highlight

6 packages built:
nushell nushellPlugins.formats nushellPlugins.gstat nushellPlugins.polars nushellPlugins.query nushellPlugins.units

**Comment by MisileLab** [comment]
error
```
error: couldn't read `./syntaxes/nushell/nushell.sublime-syntax`: No such file or directory (os error 2)
 --> build.rs:7:30
  |
7 | const NUSHELL_SYNTAX: &str = include_str!("./syntaxes/nushell/nushell.sublime-syntax");
  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `nu_plugin_highlight` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish..
```

**Comment by cptpiepmatz** [comment]
> error
> 
> ```
> error: couldn't read `./syntaxes/nushell/nushell.sublime-syntax`: No such file or directory (os error 2)
>  --> build.rs:7:30
>   |
> 7 | const NUSHELL_SYNTAX: &str = include_str!("./syntaxes/nushell/nushell.sublime-syntax");
>   |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   |
>   = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)
> 
> error: could not compile `nu_plugin_highlight` (build script) due to 1 previous error
> warning: build failed, waiting for other jobs to finish..
> ```

It's a git submodule that is missing here, you probably have to update that first.

**Comment by cptpiepmatz** [comment]
You don't have to patch the file in your nix script, my `build.rs` file already does the patch, [see](https://github.com/cptpiepmatz/nu-plugin-highlight/blob/bfde982c7ab4950a0d3f0941b6d3c7f1cb15ab3e/build.rs#L23-L26).

**Comment by MisileLab** [comment]
I'll combine nushellPlugins.highlight commits into one commit when it compiles.

**Comment by MisileLab** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 367658`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 7 packages built:</summary>
  <ul>
    <li>nushell</li>
    <li>nushellPlugins.formats</li>
    <li>nushellPlugins.gstat</li>
    <li>nushellPlugins.highlight</li>
    <li>nushellPlugins.polars</li>
    <li>nushellPlugins.query</li>
    <li>nushellPlugins.units</li>
  </ul>
</details>

**Pull request merged**
