### PR TITLE
firefox: 67.0.4 -> 68.0, firefox-esr: 60.7.2esr -> 68.0esr, rust-cbindgen: 0.8.3 -> 0.8.7 (v2)

### PR DESCRIPTION
**Pull request by andir**
###### Motivation for this change

Newer revision of #64733 since I am not allowed to update the source branch.

- Critical security fixes
- Other improvements
- ESR is now based on version 68.

https://www.mozilla.org/en-US/firefox/68.0/releasenotes/
https://www.mozilla.org/en-US/security/advisories/mfsa2019-21/

Compiling all the versions now.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
I suppose the huge rebuilds can't be separated, right?  (22k is quite a lot)

**Comment by vcunat** [comment]
In any case, I added the nss commit 442fd85d to staging-next, and I hope it will be mergeable very fast.  In case we find some other regression in there, we can e.g. proceed with merging this PR directly to master anyway.

**Comment by andir** [comment]
@vcunat 
Those bumps are a dependency of the newer firefox version. We could in theory split them. Whenever you feel like staging-next doesn't yield any new errors feel free to merge.

**Comment by vcunat** [comment]
Added 60.8.0: that branch should be supported for a couple more months, though perhaps with less visibility (I found no release notes like [for the new ESR](https://www.mozilla.org/en-US/firefox/68.0esr/releasenotes/)).  I browsed with it shortly (built atop staging-next), and it seemed fine just as the other two here.

**Comment by andir** [comment]
I started working on a backport to 19.03 (https://github.com/andir/nixpkgs/commits/19.03/firefox-68.0). Still running all the builds to see if I didn't break things in the process.

**Comment by andir** [comment]
@vcunat the results on `staging-next` look fine. Do you see any reason not to merge this in yet?

**Comment by vcunat** [comment]
Well, the [yaml problem](https://github.com/NixOS/nixpkgs/pull/64293#issuecomment-511543899) should be easy now; I hope the couple thousand of unrestartable abortions will disappear... and that might be [all from the larger regressions](https://github.com/NixOS/nixpkgs/pull/64293#issuecomment-511543899), at a quick glance.

**Comment by vcunat** [comment]
Your backports seemed to work fine for me, so I pushed them to 19.03.

**Comment by vcunat** [comment]
Except that rustc backport won't build on darwin: https://hydra.nixos.org/build/96319842

**Review by vcunat — APPROVED** [review]

**Comment by jabranham** [comment]
Firefox 68 still isn't in nixos-unstable. Is there something we can do to speed this up?

**Comment by vcunat** [comment]
Some NixOS tests were broken (some even for about a week), but apparently they got fixed today.  I expect both channels to update within a couple hours.

**Comment by jabranham** [comment]
It appears they just did, thanks!

**Pull request merged**
