### PR TITLE
geant4 overhaul

### PR DESCRIPTION
**Pull request by veprbl**
###### Motivation for this change

Update geant4 expression to conform to usual practices used in nixpkgs.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
cc @Tmplt

### CODE REVIEW

**Comment by Tmplt** [comment]
I can only approve these changes. Can't comment on g4py though.

I do wonder, though: is there any reason to default dependencies to `null` when the most probably choice is under the same name? `clhep ? null` is understandable since it's not packaged but the remainder (`expat`, `zlib`, `xercesc`, `motif`, `libGLU_combined`, `xlibsWrapper`, `qt5.qtbase`, `xorg.libXpm.dev` and `xorg.libXmu`) are. If the user does not want to built with the default choice then it can just be overridden, just like now where the `null` must be overridden, yes?

**Comment by veprbl** [comment]
@Tmplt You are right. This stuff is just bizarre. I've pushed commit to remove that.

**Comment by veprbl** [comment]
Any chance to have this merged?

**Comment by vcunat** [comment]
Sounds OK to merge, except that when I merge it with master, `g4py` won't build, spitting multiple lines with `ld: cannot find -lboost_python`.

**Comment by veprbl** [comment]
@GrahamcOfBorg build g4py

**Comment by veprbl** [comment]
Let's merge?

**Comment by veprbl** [comment]
Had to rebase after 2c2f1e37d4374ea61caefd9389927ea03df4ce31 . Can we please merge?

**Comment by veprbl** [comment]
I opened #46019 hoping to increase visibility. That had no effect. I don't understand why this particular PR gets so little traction.

**Comment by vcunat** [comment]
I'd expect the main reason is that only very small fraction of nixpkgs users will utilize such a package.

**Pull request closed without merging**
