### PR TITLE
XMonad: enable configured recompile

### PR DESCRIPTION
**Pull request by ivanbrennan**
###### Motivation for this change

The NixOS xmonad module builds an `xmonad` binary that's not capable of recompiling xmonad with a local config (e.g. ~/.config/xmonad/xmonad.hs) if the module's `config` option was set. That capability is useful when trying out changes to your config, but since it increases the closure size, it should be opt-in.

Add a new module option, `enableConfiguredRecompile`, to opt into including the necessary Haskell dependencies in the binary's environment, even if the `config` option was set (they're already included if it was not set, to allow xmonad to recompile using an xmonad config not managed by nixos).

This behavior was previously added unconditionally (#107696), and later removed (#143886) due to its affect on closure size and the reasonable argument that it's not a common enough use-case.

Additionally, the example config will not work with XMonad 0.17.0. Provide an example of how to configure 0.17.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Synthetica9** [comment]
Would it be possible to test this in `nixosTests.xmonad`?

**Comment by Lassulus** [comment]
code looks good, old behavior seems to be still ok. an addition to the test would be nice thought

**Comment by ivanbrennan** [comment]
@Synthetica9 @Lassulus Thanks, I'll take a look at adding tests. I haven't written nixos tests before, so I'm referencing [these docs](https://www.32degrees.com/products/mens-heavyweight-fleece-baselayer-legging?variant=39368690729049).

**Comment by Lassulus** [comment]
I guess you can just extend https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/xmonad.nix to have the new option enabled and create a xmonad.hs in the correct location, recompile it and check if the new version was compiled/applied

**Comment by Synthetica9** [comment]
I hope these `sleeps` aren't too strict on really congested build machines, if this starts failing we could do `machine.wait_until_succeeds`/-`fails`,

**Comment by ivanbrennan** [comment]
> I hope these `sleeps` aren't too strict on really congested build machines, if this starts failing we could do `machine.wait_until_succeeds`/-`fails`,

@Synthetica9 Good point. I'll make a followup PR to clean these `sleep`s up.

**Pull request merged**
