### PR TITLE
nixos/gnome: let nautilus show audio/video properties

### PR DESCRIPTION
**Pull request by bjornfor**
###### Description of changes
Ref https://github.com/NixOS/nixpkgs/issues/53631.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bjornfor** [comment]
Probably not a good idea, see https://github.com/NixOS/nixpkgs/issues/53631#issuecomment-1296276475.

**Comment by bjornfor** [comment]
I don't understand why yet, but this patch seems to cause pulseaudio to fail creating a gstreamer `capsfilter` in nixos 22.11: https://github.com/NixOS/nixpkgs/issues/203919

**Comment by jtojnar** [comment]
That sounds precisely like the kind of issue I was warning about. Most likely there is a mismatch between GStreamer versions. Does it happen if you install everything from the same channel and restart the computer?

**Comment by bjornfor** [comment]
> That sounds precisely like the kind of issue I was warning about. Most likely there is a mismatch between GStreamer versions. Does it happen if you install everything from the same channel and restart the computer?

Yes. I have only one nixpkgs channel and rebooting doesn't fix it.

**Comment by bjornfor** [comment]
Another data point, running `pulseaudio` manually worked:

```
$ echo $GST_PLUGIN_SYSTEM_PATH_1_0 
/nix/store/blqpkrzcqmks5q05my9akm7395afgpmj-gst-libav-1.20.3/lib/gstreamer-1.0:/nix/store/zdfnrn3qd7hq1mjiyhglq2ryi8v49k5g-gst-plugins-bad-1.20.3/lib/gstreamer-1.0:/nix/store/p1m6hc6zwr8p7c1zhy6yhwsxkz9z71iz-gst-plugins-base-1.20.3/lib/gstreamer-1.0:/nix/store/mhxw7hklkdyv915rrp36bk9i35zcxh5j-gst-plugins-good-1.20.3/lib/gstreamer-1.0:/nix/store/5jrzmz73yr9w79wgn6gzxh6kcanazj4z-gst-plugins-ugly-1.20.3/lib/gstreamer-1.0

$ pulseaudio -k; sleep 1 && pulseaudio --daemonize=no
[...no aptX failure...]
```

**Comment by bjornfor** [comment]
Huh, it seems that when using `environment.sessionVariables.GST_PLUGIN_SYSTEM_PATH_1_0 = [...]`, and using the pulseaudio systemd user serivce, the `pulseaudio` wrapper *doesn't prefix `GST_PLUGIN_SYSTEM_PATH_1_0`* with its required deps[1]. (How/what/why?!)

If I start pulseaudio manually as my user, inheriting the same global env vars, then it works -- `GST_PLUGIN_SYSTEM_PATH_1_0` gets prefixed correctly.

[1] Inspected env var from running process: `gdb -q -ex "attach $(pidof pulseaudio)" -ex 'printf "%s\n", getenv("GST_PLUGIN_SYSTEM_PATH_1_0")' -ex "exit" | tr : \\n`

**Comment by bjornfor** [comment]
After too much debugging, I eventually found that on nixos-22.11, pulseaudio.service starts the *unwrapped* binary:

```
$ nix-build -A pulseaudio && grep ExecStart= result/lib/systemd/user/pulseaudio.service 
/nix/store/bvihhgw8bh6cqqlj0d4s8cvmm4mqmzfc-pulseaudio-16.1
ExecStart=/nix/store/bvihhgw8bh6cqqlj0d4s8cvmm4mqmzfc-pulseaudio-16.1/.bin-unwrapped/pulseaudio --daemonize=no --log-target=journal
```

This is a regression compared to nixos-22.05:

```
$ nix-build -A pulseaudio && grep ExecStart= result/lib/systemd/user/pulseaudio.service 
/nix/store/ifbj5iwl3djz3mrfzjfbcw9dvf84fpm6-pulseaudio-15.0
ExecStart=/nix/store/ifbj5iwl3djz3mrfzjfbcw9dvf84fpm6-pulseaudio-15.0/bin/pulseaudio --daemonize=no --log-target=journal
```

**Comment by bjornfor** [comment]
3871f8be8d6de48d5f094fbe90a09e42cc0b289c seems relevant.

**Comment by SuperSandro2000** [comment]
Why not wrap nautilus itself?

**Comment by bjornfor** [comment]
> Why not wrap nautilus itself?

Probably a better idea. Let's close this and continue discussing in https://github.com/NixOS/nixpkgs/issues/53631.

**Comment by bjornfor** [comment]
> I don't understand why yet, but this patch seems to cause pulseaudio to fail creating a gstreamer capsfilter in nixos 22.11: https://github.com/NixOS/nixpkgs/issues/203919
> [...]
> After too much debugging, I eventually found that on nixos-22.11, pulseaudio.service starts the _unwrapped_ binary:
> [...]
> This is a regression compared to nixos-22.05 [which runs the _wrapped_ binary]:

For the archive, the regression I thought was due to this PR was due to pulseaudio, and it was fixed in c26ff1ed9badf9ec4e5c572a755985360f682010.

**Pull request closed without merging**
