### PR TITLE
GNOME updates 2023-07-04

### PR DESCRIPTION
**Pull request by jtojnar**
###### Description of changes

Changelogs and build system diffs look okay.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
> https://gitlab.gnome.org/GNOME/gcab/-/compare/1.5...1.6

Sounds like the update script generates wrong url :laughing: 

> tracker-miners: 3.5.0 → 3.5.2

Do we still wish to patch https://github.com/NixOS/nixpkgs/issues/228639?

**Review by fabianhjr — APPROVED** [review]
changes lgtm, built and booted into NixOS x86-64

**Comment by jtojnar** [comment]
Added some more GNOME dependencies and apps. Checked their changelogs as well and made sure the apps (+GIMP and Inkscape) run.

**Comment by bobby285271** [comment]
Also tested simple trashing, simple deja-dup backup & restore and geary mail receive.

- I never heard of [MS-RL license](https://gitlab.gnome.org/GNOME/msitools/-/commit/afe0fa7de3ab25ac02ab3ee9c2974bcd52c8329c) before, [thanks debian](https://salsa.debian.org/debian/msitools/-/commit/6343c4fc7c6927f80e673759cdde761001de5067) for telling me it is free :sweat_drops: 
- Specifically [checked](https://gitlab.gnome.org/World/deja-dup/-/commit/fe353abaa2dba79369c5510782e500b8e8adace6) duplicity [0.8.23](https://gitlab.com/duplicity/duplicity/-/tags) supports "incremental" as subcommand

I just called ofborg to build stuff and looks like there are some surprising failures :upside_down_face: 

- I can see [`umfpack_dl_solve`](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/v5.13.0/UMFPACK/Include/umfpack_solve.h#L23) in suitesparse 5.13.0 but not sure why darwin fails [on the change](https://gitlab.gnome.org/GNOME/gegl/-/commit/2348b571e4ec4c4549fa34906e3076dca6231d21)
- The flaky `test_headset_hotplug` upower [test failure](https://logs.ofborg.org/?key=nixos/nixpkgs.241586&attempt_id=b75b7646-ac56-4a28-9fde-e71ca1453795) is hopefully fixed in [this commit](https://gitlab.freedesktop.org/upower/upower/-/commit/f8fe036331cd9f59ab87aee839afc3893a7463a9) so we probably need 1.90.2
- Haven't looked at the lib2geom thing yet

**Comment by jtojnar** [comment]
> I can see [`umfpack_dl_solve`](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/v5.13.0/UMFPACK/Include/umfpack_solve.h?rgh-link-date=2023-07-08T15%3A02%3A02Z#L23) in suitesparse 5.13.0 but not sure why darwin fails [on the change](https://gitlab.gnome.org/GNOME/gegl/-/commit/2348b571e4ec4c4549fa34906e3076dca6231d21)

Good catch. I must have missed the change. It looks like the symbol is in a different header:

```ShellSession
$ rg umfpack_dl_solve result-dev
result-dev/include/umfpack_solve.h
```

But the `result-dev/include/umfpack.h` includes `umfpack_solve.h` without any extra conditionals so I would expect it to just work.

`git diff --no-index $(nix-build -A suitesparse.dev) $(nix-build --system aarch64-darwin -A suitesparse.dev)` does not report any changes other than store path.

So it is weird that we get the following on Linux:

```
Header "umfpack.h" has symbol "umfpack_dl_solve" : YES 
Header "suitesparse/umfpack.h" has symbol "umfpack_dl_solve" : NO 
```

While the following on Nix darwin:

```
Header "umfpack.h" has symbol "umfpack_dl_solve" : NO
Header "suitesparse/umfpack.h" has symbol "umfpack_dl_solve" : NO
```

Would be nice to get hands on `/build/gegl-0.4.46/build/meson-logs/meson-log.txt`.

**Comment by jtojnar** [comment]
> * The flaky `test_headset_hotplug` upower [test failure](https://logs.ofborg.org/?key=nixos/nixpkgs.241586&attempt_id=b75b7646-ac56-4a28-9fde-e71ca1453795) is hopefully fixed in [this commit](https://gitlab.freedesktop.org/upower/upower/-/commit/f8fe036331cd9f59ab87aee839afc3893a7463a9) so we probably need 1.90.2

That version requires newer libgudev #241939, dropped upower bump for now.

> * Haven't looked at the lib2geom thing yet

Dropped for now.

**Comment by jtojnar** [comment]
> So it is weird that we get the following on Linux:
> 
> ```
> Header "umfpack.h" has symbol "umfpack_dl_solve" : YES 
> Header "suitesparse/umfpack.h" has symbol "umfpack_dl_solve" : NO 
> ```

I can reproduce this on Linux with `clangStdenv`.

**Comment by jtojnar** [comment]
Looks like it is downfall from us passing `-lm` to `NIX_CFLAGS_COMPILE`:

```
Running compile:
Working directory:  /build/gegl-0.4.46/build/meson-private/tmpruwqel_w
Command line:  clang /build/gegl-0.4.46/build/meson-private/tmpruwqel_w/testfile.c -o /build/gegl-0.4.46/build/meson-private/tmpruwqel_w/output.obj -c -D_FILE_OFFSET_BITS=64 -O0 -Werror=implicit-function-declaration -Werror=unknown-warning-option -Werror=unused-command-line-argument -Werror=ignored-optimization-argument -std=gnu11 

Code:
 
        #include <umfpack.h>
        int main(void) {
            /* If it's not defined as a macro, try to use as a symbol */
            #ifndef umfpack_dl_solve
                umfpack_dl_solve;
            #endif
            return 0;
        }
Compiler stdout:
 
Compiler stderr:
 clang-11: error: -lm: 'linker' input unused [-Werror,-Wunused-command-line-argument]

Header "umfpack.h" has symbol "umfpack_dl_solve" : NO 
```

**Comment by jtojnar** [comment]
I opened an [upstream fix for the GEGL issue](https://gitlab.gnome.org/GNOME/gegl/-/merge_requests/136) and moved the update to https://github.com/NixOS/nixpkgs/pull/242333 until we get a response from upstream.

**Comment by jtojnar** [comment]
Update GNOME Shell as well. Booted into GNOME VM, did not notice any issues. `nixosTests.gnome-xorg` and `nixosTests.gnome` pass.

**Pull request merged**
