### PR TITLE
zenpower: 0.1.5 -> 0.1.10

### PR DESCRIPTION
**Pull request by alexbakker**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by marsam** [comment]
@GrahamcOfBorg build linuxPackages.zenpower

**Comment by AtkinsChang** [comment]
It is `v0.1.10` atm

**Comment by alexbakker** [comment]
Updated to 0.1.10.

**Comment by alyssais** [comment]
@GrahamcOfBorg build linuxPackages.zenpower

**Comment by alyssais** [comment]
Needs to either be fixed or marked as broken or unsupported on aarch64.

**Comment by AtkinsChang** [comment]
this is kernel hwmon mod for AMD processor so should mark this for x86 only

**Comment by alexbakker** [comment]
Apologies for the delay. I've added the suggested platform constraint.

**Comment by alyssais** [comment]
@GrahamcOfBorg build zenpower

**Comment by alyssais** [comment]
@GrahamcOfBorg build linuxPackages.zenpower

**Comment by alyssais** [comment]
Commit message would ideally say “linuxPackages.zenpower: …” but I won’t block on that

**Pull request merged**
