### PR TITLE
apple-cursor: 2.0.0 -> 2.0.1

### PR DESCRIPTION
**Pull request by dxwil**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by colemickens** [comment]
My cursor seems quite broken after taking this upgrade, need to look into it more.

**Comment by dxwil** [comment]
Hmm, weird. Maybe it's an issue with upstream and your setup.

DK
________________________________

**Comment by colemickens** [comment]
It seems like they've renamed the cursor names *again* so I had to change from `macOS-BigSur-white` to just `macOS-white`.

**Comment by colemickens** [comment]
IDK. Seems fine, maybe there could be a symlink for this, but maybe that's not right or overkill. Anyway, seems fine after updating my config appropriately.

**Comment by dxwil** [comment]
> IDK. Seems fine, maybe there could be a symlink for this, but maybe that's not right or overkill. Anyway, seems fine after updating my config appropriately.

Could be but yeah I agree that that's a little overkill

**Comment by dxwil** [comment]
@colemickens Is this able to be merged now?

**Review by colemickens — APPROVED** [review]

**Comment by emilazy** [comment]
This update seems fine to me, but should this really not be marked as `lib.licenses.unfree`? I guess the designs themselves may be utilitarian enough to not be copyrightable, but I’m a bit nervous about redistributing these.

**Comment by dxwil** [comment]
> This update seems fine to me, but should this really not be marked as `lib.licenses.unfree`? I guess the designs themselves may be utilitarian enough to not be copyrightable, but I’m a bit nervous about redistributing these.

I'm no expert in copyright or licensing so I couldn't say, but if you think this should be marked as unfree then I can change that no problem.

**Comment by emilazy** [comment]
It seems ambiguous since I wouldn’t be surprised if the standard arrow shape at least isn’t copyrightable, but since these are deliberately trying to precisely mimic a variety of fairly unique designs that aren’t found anywhere else but Apple platforms I think I’d feel more comfortable with e.g.:

```nix
license = [
  licenses.gpl3Only

  # Potentially a derivative work of copyrighted Apple designs
  licenses.unfree
];
```

Sorry to bring this up on a minor version bump!

**Comment by dxwil** [comment]
> Sorry to bring this up on a minor version bump!

No worries. What about now :)

**Review by emilazy — APPROVED** [review]

**Comment by emilazy** [comment]
LGTM, thanks :)

**Pull request merged**
