### PR TITLE
[staging-next] pipewire: 0.3.67 -> 0.3.68

### PR DESCRIPTION
**Pull request by K900**
Diff: https://gitlab.freedesktop.org/pipewire/pipewire/-/compare/0.3.67...0.3.68
Changelog: https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.68

###### Description of changes

image

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
This is a spooky one, needs additional testing for sure.

**Comment by K900** [comment]
Seems OK here and no one is complaining on #pipewire either so let's get this in so we have another cycle before 23.05.

**Comment by maxeaubrey** [comment]
I'm not sure what's the problem, but I had to revert this on my system - with GNOME 44, I don't get working sound with this version of pipewire, but everything's fine on 0.3.67 (no other changes, I only reverted the commit).

**Comment by K900** [comment]
Anything in `journalctl --user -u pipewire`?

**Comment by maxeaubrey** [comment]
Nothing of interest, it's the same as on `0.3.67` i.e. current system:
```
Apr 08 22:15:28 chirm systemd[3559]: Started PipeWire Multimedia Service.
Apr 08 22:15:28 chirm pipewire[3882]: mod.rt: Can't find org.freedesktop.portal.Desktop. Is xdg-desktop-portal runnin>
Apr 08 22:15:28 chirm pipewire[3882]: mod.rt: found session bus but no portal
Apr 08 22:15:30 chirm pipewire[3882]: [0:00:26.083367350] [3882]  INFO IPAManager ipa_manager.cpp:143 libcamera is no>
Apr 08 22:15:30 chirm pipewire[3882]: [0:00:26.083589706] [3882]  INFO Camera camera_manager.cpp:299 libcamera v0.0.3
Apr 08 22:18:45 chirm pipewire[3882]: mod.x11-bell: X11 I/O error handler called on display :0
Apr 08 22:18:45 chirm pipewire[3882]: mod.x11-bell: X11 display (:0) has encountered a fatal I/O error
Apr 08 22:18:45 chirm systemd[3559]: Stopping PipeWire Multimedia Service...
Apr 08 22:18:45 chirm systemd[3559]: Stopped PipeWire Multimedia Service.
```

**Comment by matthewpi** [comment]
After updating to staging-next@<https://github.com/NixOS/nixpkgs/commit/df6db8c5b0b94b85e578d05b37e5bf3b24555638> I have a similar problem.

(First boot was from a bit of an older commit on `nixos-unstable`, second is `staging-next`)
```
~ 
❯ journalctl --user -u pipewire
-- Boot 37153458cbfc4a4989c03da1f68f5dce --
Apr 08 12:25:33 matthew-desktop systemd[3836]: Started PipeWire Multimedia Service.
Apr 08 12:25:33 matthew-desktop pipewire[4119]: mod.rt: Can't find org.freedesktop.portal.Desktop. Is xdg-desktop-portal running?
Apr 08 12:25:33 matthew-desktop pipewire[4119]: mod.rt: found session bus but no portal
Apr 08 15:11:48 matthew-desktop pipewire[4119]: mod.x11-bell: X11 I/O error handler called on display :0
Apr 08 15:11:48 matthew-desktop pipewire[4119]: mod.x11-bell: X11 display (:0) has encountered a fatal I/O error
Apr 08 15:11:48 matthew-desktop systemd[3836]: Stopping PipeWire Multimedia Service...
Apr 08 15:11:48 matthew-desktop systemd[3836]: Stopped PipeWire Multimedia Service.
-- Boot 722e685613304d56a5297a44000b58b4 --
Apr 08 15:12:43 matthew-desktop systemd[4154]: Started PipeWire Multimedia Service.
Apr 08 15:12:43 matthew-desktop pipewire[4565]: mod.rt: Can't find org.freedesktop.portal.Desktop. Is xdg-desktop-portal running?
Apr 08 15:12:43 matthew-desktop pipewire[4565]: mod.rt: found session bus but no portal
Apr 08 15:14:16 matthew-desktop pipewire[4565]: mod.x11-bell: canberra context open error: Not available
```

Both `pipewire.service` and `pipewire.socket` are still active, but GNOME does not have any sound devices listed, nor any volume sliders available.  (Not sure if it is relevant, but `wireplumber.service` is also running without any errors.

```
~ 
❯ systemctl status pipewire.service --user
● pipewire.service - PipeWire Multimedia Service
     Loaded: loaded (/etc/systemd/user/pipewire.service; linked-runtime; preset: enabled)
    Drop-In: /nix/store/ry1y5axlgf3zw3b5946gq7khq76ka5wm-user-units/pipewire.service.d
             └─overrides.conf
     Active: active (running) since Sat 2023-04-08 15:12:43 MDT; 5min ago
TriggeredBy: ● pipewire.socket
   Main PID: 4565 (pipewire)
      Tasks: 3 (limit: 154422)
     Memory: 5.1M
        CPU: 35ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/pipewire.service
             └─4565 /nix/store/w1144s3zx8saplrl74sapxjkrg2qc65d-pipewire-0.3.68/bin/pipewire

Apr 08 15:12:43 matthew-desktop systemd[4154]: Started PipeWire Multimedia Service.
Apr 08 15:12:43 matthew-desktop pipewire[4565]: mod.rt: Can't find org.freedesktop.portal.Desktop. Is xdg-desktop-portal running?
Apr 08 15:12:43 matthew-desktop pipewire[4565]: mod.rt: found session bus but no portal
Apr 08 15:14:16 matthew-desktop pipewire[4565]: mod.x11-bell: canberra context open error: Not available
Apr 08 15:17:47 matthew-desktop pipewire[4565]: mod.x11-bell: canberra context open error: Not available

~ 
❯ systemctl status pipewire.socket --user 
● pipewire.socket - PipeWire Multimedia System Socket
     Loaded: loaded (/etc/systemd/user/pipewire.socket; enabled; preset: enabled)
    Drop-In: /nix/store/ry1y5axlgf3zw3b5946gq7khq76ka5wm-user-units/pipewire.socket.d
             └─overrides.conf
     Active: active (running) since Sat 2023-04-08 15:12:41 MDT; 5min ago
   Triggers: ● pipewire.service
     Listen: /run/user/1000/pipewire-0 (Stream)
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/pipewire.socket

Apr 08 15:12:41 matthew-desktop systemd[4154]: Listening on PipeWire Multimedia System Socket.
```

**Comment by K900** [comment]
Oh no, I think I see the problem...

**Comment by K900** [comment]
Yes, fixed in https://github.com/NixOS/nixpkgs/pull/225375.

/me makes a mental note to test pipewire-pulse separately

**Comment by maxeaubrey** [comment]
Thanks, appreciated!

**Pull request merged**
