### PR TITLE
darktable: 4.8.1 -> 5.0.0

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Things done

Changelog: https://github.com/darktable-org/darktable/releases/tag/release-5.0.0

cc @flosse @mrVanDalo @paperdigits @freyacodes

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by lucasew** [comment]
> When updating from the stable 4.8 series, please bear in mind that your edits will be preserved during this process, but the new library and configuration will no longer be usable with 4.8.
>
> You are strongly advised to take a backup first.


This may be concerning. What about 5.x be darktable_5 for some time?

**Comment by paperdigits** [comment]
This should not be concerning, this is the case on every major version upgrade. 

Make a backup of your sqlite dbs before upgrade.

**Comment by paperdigits** [comment]
The database schema gets updated each version and is generally backward incompatible. The project does not test backward compatibility.

You can argue with the general approach all you want, but its been like this for a long time. If you'd like to do the dev work and testing needed to change the behavior that'd be great.

**Comment by paperdigits** [comment]
Gotcha, I def read your message incorrectly, sorry.

**Comment by paperdigits** [comment]
@NixOS/nixpkgs-merge-bot merge

**Review by paperdigits — APPROVED** [review]

**Review by lucasew — APPROVED** [review]

**Comment by tomberek** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 367238`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>darktable</li>
    <li>photoprism</li>
  </ul>
</details>

**Review by tomberek — APPROVED** [review]

**Comment by lucasew** [comment]
> The `updateScript` doesn't eval which then breaks the `updateScript` fetcher for the `nixpkgs-update` bot.
> 
> ```
> $ nix-shell maintainers/scripts/update.nix --argstr package darktable
> error:
>        … while calling the 'derivationStrict' builtin
>          at <nix/derivation-internal.nix>:34:12:
>            33|
>            34|   strict = derivationStrict drvAttrs;
>              |            ^
>            35|
> 
>        … while evaluating derivation 'nixpkgs-update-script'
>          whose name attribute is located at /home/zowoq/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:375:7
> 
>        … while evaluating attribute 'shellHook' of derivation 'nixpkgs-update-script'
>          at /home/zowoq/nixpkgs/maintainers/scripts/update.nix:261:3:
>           260|   '';
>           261|   shellHook = ''
>              |   ^
>           262|     unset shellHook # do not contaminate nested shells
> 
>        (stack trace truncated; use '--show-trace' to show the full, detailed trace)
> 
>        error: function 'anonymous lambda' called with unexpected argument 'rev-prefix'
>        at /home/zowoq/nixpkgs/pkgs/by-name/ni/nix-update/nix-update-script.nix:6:1:
>             5|
>             6| {
>              | ^
>             7|   attrPath ? null,
> ```

Ill try to fix it

**Comment by lucasew** [comment]
Fixed, and also there is a new version so the fix is tested.

https://github.com/NixOS/nixpkgs/pull/367780

Em seg., 23 de dez. de 2024 às 23:06, Lucas Eduardo <
***@***.***> escreveu:

**Comment by trofi** [comment]
The updater script still fails to eval. Proposed the fix as:
- https://github.com/NixOS/nixpkgs/pull/367950

I still tries hard to pull in `5.1.0` (just like `nix-update`), but at least it does not deserve the `package.nix` file when it fails.

**Comment by paperdigits** [comment]
A working nix update script can be found here:  https://github.com/NixOS/nixpkgs/pull/368007

**Pull request merged**
