### PR TITLE
platformio: needs xdg-user-dirs

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Description of changes

pio errors out if it's not able to access xdg-user-dirs.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by dotlambda — COMMENTED** [review]
Why the reformatting?

**Comment by peterhoeg** [comment]
> Why the reformatting?

nixpkgs-fmt doing its thing.

**Comment by oxzi** [comment]
Thanks for the PR. Could you please elaborate when pio crashes? I just run it in a pure nix-shell and nothing failed.

**Comment by peterhoeg** [comment]
Ah yes, that would make sense. `esphome` calls out to `pio` but blows up almost immediately on recent `nixos-unstable` because it tries to call `xdg-user-dirs`. I must admit I haven't tried `pio` on its own, so it might be that however `esphome` is exercising it is what is causing the issue and isn't technically a `pio` problem. 
Would you be more comfortable with a comment in there as to why?

**Comment by oxzi** [comment]
Wouldn't it make more sense to add `xdg-user-dirs` to `esphome` or wrap `platformio` to include `xdg-user-dirs`?

Could you also please test it again as #173670 got merged which bumped `platformio`'s major version. Thanks a lot!

**Comment by peterhoeg** [comment]
The reason for changing it here, is that it *seems* to be standard pio functionality that just happens to only be exercised by esphome and not pio under at least my very limited use of pio directly. If anything else using pio was to exercise the same functionality in pio, that would fail too and hence I think it makes sense to fix it in one place (pio) rather than in each consumer.

**Comment by peterhoeg** [comment]
@oxzi - any concerns? If not, I'll merge this.

**Pull request merged**
