### PR TITLE
dataexplorer: 3.6.2 -> 3.7.1

### PR DESCRIPTION
**Pull request by panicgh**
###### Description of changes

* Package update
* The `file.encoding=UTF-8` setting has been moved into the application itself. It is not needed any more to pass it via the `java` command line.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by panicgh** [comment]
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>dataexplorer</li>
  </ul>
</details>

**Review by SuperSandro2000 — COMMENTED** [review]
darwin is failing to build:

```
BUILD FAILED
/private/tmp/nix-build-dataexplorer-3.7.1.drv-0/dataexplorer-3.7.1/build/build.xml:318: The following error occurred while executing this line:
/private/tmp/nix-build-dataexplorer-3.7.1.drv-0/dataexplorer-3.7.1/build/build.xml:382: The following error occurred while executing this line:
/private/tmp/nix-build-dataexplorer-3.7.1.drv-0/dataexplorer-3.7.1/build/build.xml:417: /nix/store/nz8i3w5ffvn1bi04d7ng01q887ajcpmh-dataexplorer-3.7.1/share/private/tmp/nix-build-dataexplorer-3.7.1.drv-0/dataexplorer-3.7.1/build/target/Mac_64/DataExplorer.app/Contents/Resources/runtime/bin does not exist.
Total time: 2 seconds
```

**Comment by ck3d** [comment]
I can confirm the build error. The version 3.6.2 can be built on darwin.

**Comment by panicgh** [comment]
I have seen the comments (thanks!) and can reproduce the issue. Unfortunately, I didn't have the time yet to investigate the issue (but I'll try to do so soon).

**Comment by panicgh** [comment]
Superseded by #203304.

**Pull request closed without merging**
