### PR TITLE
foliate: add glib-networking to enable the catalog functionality

### PR DESCRIPTION
**Pull request by deifactor**
###### Motivation for this change

Necessary for the catalog functionality, since that talks to the network. Tested this using an override in my local config.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ X Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Artturin — CHANGES_REQUESTED** [review]
Add glib-networking to the third line

**Comment by deifactor** [comment]
> Add glib-networking to the third line

Oops, done. Can squash the two changes together if you want to keep things tidy.

**Comment by Artturin** [comment]
Yes use fixup with rebase

**Comment by deifactor** [comment]
Done.

**Pull request merged**
