### PR TITLE
glusterfs glusterfind fixes cherry-pick for 17.09

### PR DESCRIPTION
**Pull request by nh2**
###### Motivation for this change

Cherry-pick of #29071.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

CC @bachp @joachifm

### CODE REVIEW

**Comment by joachifm** [comment]
Thank you. Please use `git cherry-pick -x` to preserve the link to the original commits.

**Comment by nh2** [comment]
@joachifm OK, will fix.

**Comment by nh2** [comment]
@joachifm Done.

**Comment by fpletz** [comment]
Thanks!

**Pull request merged**
