### PR TITLE
ammonite: 2.2.0 -> 2.3.8

### PR DESCRIPTION
**Pull request by JesusMtnez**
###### Motivation for this change

Bump ammonite to latest release `2.3.8`.

Updated using:
```shell 
nix-shell maintainers/scripts/update.nix --argstr package ammonite_2_12
```

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105115` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>ammonite (ammonite_2_13)</li>
    <li>ammonite_2_12</li>
  </ul>
</details>

**Comment by lourkeur** [comment]
Both packages (2.12 and 2.13) build but won't execute. Might be a shell quoting problem?
```result/bin/amm
Error: Could not find or load main class ammonite.Main --no-remote-logging
Caused by: java.lang.ClassNotFoundException: ammonite.Main --no-remote-logging
```

**Comment by NeQuissimus** [comment]
@JesusMtnez Thank you, I fixed the argument issue.
`nix-build -A ammonite.tests` ;)

**Review by NeQuissimus — APPROVED** [review]

**Review by NeQuissimus — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105115` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>ammonite (ammonite_2_13)</li>
    <li>ammonite_2_12</li>
  </ul>
</details>

**Pull request merged**
