### PR TITLE
wpsoffice: don't need wrapGAppsHook nor wrapQtAppsHook & use autoPatchelfIgnoreMissingDeps

### PR DESCRIPTION
**Pull request by wineee**
###### Description of changes

wrapGAppsHook and wrapQtAppsHook should not be necessary for wpsoffice

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SharzyL** [comment]
It seems that the extra dependencies introduced in this PR is caused by the removed `postUnpack` hook. Is the `postUnpack` hook causing any problems? Because if `postUnpack` just works, bothering adding these dependencies might be not necessary.

**Comment by wineee** [comment]
> It seems that the extra dependencies introduced in this PR is caused by the removed `postUnpack` hook. Is the `postUnpack` hook causing any problems? Because if `postUnpack` just works, bothering adding these dependencies might be not necessary.

They are propagated build dependencies  introduced by  wrapGAppsHook and wrapQtAppsHook

Only  `xorg.libXv`  caused by the removed postUnpack, to fix `libpdfbatchcompressionapp.so` we previously removed



[`0293e7f` (#232244)](https://github.com/NixOS/nixpkgs/pull/232244/commits/0293e7f20dee19e0f9a694783f8adf449539d770)

**Comment by SharzyL** [comment]
```
$ nix build nixpkgs/c839521d172f2bf656c3f8a3e66faa786fb07878#wpsoffice --impure -L
wpsoffice> qtPreHook
wpsoffice> Error: wrapQtAppsHook is not used, and dontWrapQtApps is not set.
error: builder for '/nix/store/2chqcmn12r3w8d187lknky6wk0bqca5a-wpsoffice-11.1.0.11698.drv' failed with exit code 1;
       last 2 log lines:
       > qtPreHook
       > Error: wrapQtAppsHook is not used, and dontWrapQtApps is not set.
       For full logs, run 'nix log /nix/store/2chqcmn12r3w8d187lknky6wk0bqca5a-wpsoffice-11.1.0.11698.drv'.
```

It doesn't build currently. If you don't think it is ok now, better to convert to draft pr.

**Comment by wineee** [comment]
forgot to test :( https://github.com/NixOS/nixpkgs/compare/21dee4c7115f1f8d8b7d0dac4ec20ea73eaa2599..0293e7f20dee19e0f9a694783f8adf449539d770

` dontWrapGApps = true;` is still needed because qtbase is one of `buildInputs`

**Comment by SharzyL** [comment]
I tried removing  `libxslt`, `gdk-pixbuf`, `xorg.libXrandr`, `xorg.libXcomposite`, `cups` and `pango` from `buildInputs`, and it build successfully and works well under my basic tests. Are they necessary for some reason?

**Comment by wineee** [comment]
> I tried removing `libxslt`, `gdk-pixbuf`, `xorg.libXrandr`, `xorg.libXcomposite`, `cups` and `pango` from `buildInputs`, and it builds successfully and works well under my basic tests. Are they necessary for some reason?

They are determined to be required by `autoPatchelfHook`，it should be other dependencies (probability is qtbase and gtk3 
) propagate them，so they are still in the build environment while removed from buildInputs

I'm not against removing them but keeping them should be ok

**Comment by SharzyL** [comment]
From my opinionated perspective, the clean way is either listing all dependencies regardless of the propagated ones, or listing the minimal set of dependencies needed. The former approach is hard to verify so I would prefer the later approach. Anyway this is not a strict requirement so if you are satisfied with it, I will approve later.

**Review by SharzyL — APPROVED** [review]

**Review by NickCao — APPROVED** [review]
Tested basic functionality on sway, seem to work fine.

**Pull request merged**
