### PR TITLE
maintainers/scripts/update.nix: exit with nonzero exit code when script fails

### PR DESCRIPTION
**Pull request by winterqt**
###### Description of changes

This allows tools/scripts like @r-ryantm to properly detect when updates fail, avoiding broken/partial PRs like #190648.

Not sure how I can make the commit message shorter than 50 characters, suggestions welcome.

Also, does the brach name read like I'm talking about a package named `signal`? I think it could be unclear in the merge commit message, though I guess it really doesn't matter...

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jtojnar — APPROVED** [review]
Thanks for noticing this. I verified that it works as expected. Though ideally, we would clean the output a bit more:

```
 - dconf-editor-3.38.3: UPDATING ...
 - devhelp-41.2: UPDATING ...
 - eog-42.3: UPDATING ...
 - file-roller-3.42.0: UPDATING ...
 - dconf-editor-3.38.3: ERROR

--- SHOWING ERROR LOG FOR dconf-editor-3.38.3 ----------------------



--- SHOWING ERROR LOG FOR dconf-editor-3.38.3 ----------------------
Traceback (most recent call last):
  File "/nix/store/r45r2pgwm269ljknck0ynrqiw4ikv0w5-update.py", line 55, in run_update_script
    update_process = await check_subprocess('env', f"UPDATE_NIX_ATTR_PATH={package['attrPath']}", *update_script_command, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE, cwd=worktree)
  File "/nix/store/r45r2pgwm269ljknck0ynrqiw4ikv0w5-update.py", line 33, in check_subprocess
    raise error
__main__.CalledProcessError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/r45r2pgwm269ljknck0ynrqiw4ikv0w5-update.py", line 233, in <module>
    main(args.max_workers, args.keep_going, args.commit, args.packages)
  File "/nix/store/r45r2pgwm269ljknck0ynrqiw4ikv0w5-update.py", line 214, in main
    asyncio.run(start_updates(max_workers, keep_going, commit, packages))
  File "/nix/store/c1vb2z3c64i0sd92iz7fv0lb720qcvhb-python3-3.10.6/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/nix/store/c1vb2z3c64i0sd92iz7fv0lb720qcvhb-python3-3.10.6/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/nix/store/r45r2pgwm269ljknck0ynrqiw4ikv0w5-update.py", line 197, in start_updates
    raise e
  File "/nix/store/r45r2pgwm269ljknck0ynrqiw4ikv0w5-update.py", line 190, in start_updates
    await updaters
  File "/nix/store/r45r2pgwm269ljknck0ynrqiw4ikv0w5-update.py", line 155, in updater
    await run_update_script(nixpkgs_root, merge_lock, temp_dir, package, keep_going)
  File "/nix/store/r45r2pgwm269ljknck0ynrqiw4ikv0w5-update.py", line 75, in run_update_script
    raise UpdateFailedException(f"Updating {package['name']} failed with exit code {e.process.returncode}")
__main__.UpdateFailedException: Updating dconf-editor-3.38.3 failed with exit code 1
```

**Comment by jtojnar** [comment]
We can do a rebase merge if you feel the merge commit could be a problem. I usually ignore those.

**Comment by winterqt** [comment]
How's this instead?

**Review by jtojnar — APPROVED** [review]
Looks and works great, thanks.

**Pull request merged**
