### PR TITLE
[release-24.05] Firefox 132, Thunderbird 128.4.0 and more

### PR DESCRIPTION
**Pull request by mweinelt**
Backport #352161

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Scrumplex** [comment]
Betterbird (which was removed in https://github.com/NixOS/nixpkgs/pull/351205) uses Thunderbird 115. I guess we need to remove it or mark it as broken and remove references to thunderbird-115

**Comment by lukegb** [comment]
On x86_64-linux:

`firefox-115`: errors (EOL), good
/nix/store/y1ckj126c6686ndn60w9grms8z2brkv9-firefox-132.0
/nix/store/ig6rmybqls73bxykvai1xb2nd4gd53xl-firefox-bin-132.0
/nix/store/383rsp8cyll8dds41nsmlr4bbf4ml7bl-firefox-133.0b1
/nix/store/2mr7b9sci9p61xsd0a2jbcgd3ci25p5b-firefox-beta-bin-133.0b1
/nix/store/7bkhnkqfc893g0da3569531qvphhq2h0-firefox-128.4.0esr
/nix/store/mc6r1lvnlhgqsxi3jz4qmzarn02y5c8k-thunderbird-128.4.0esr
/nix/store/iry64xhcrb7m94djy0l4qm9jsd7q8121-thunderbird-bin-128.4.0esr

**Comment by mweinelt** [comment]
> Betterbird (which was removed in #351205) uses Thunderbird 115. I guess we need to remove it or mark it as broken and remove references to thunderbird-115

>error: Thunderbird 115 support ended in October 2024

I think the knownVulnerabilities we have here is fine here.

**Review by lukegb — APPROVED** [review]

**Review by Scrumplex — CHANGES_REQUESTED** [review]
~~Merge blocker, as top level doesn't eval because of betterbird~~

**Comment by mweinelt** [comment]
I dropped the Thunderbird 115 removal

**Review by Scrumplex — APPROVED** [review]
Changes LGTM. `betterbird` and `thunderbirdPackages.thunderbird-115` both refuse to evaluate because of `knownVulnerabilities`

**Pull request merged**
