### PR TITLE
mongoc: init at 1.1.10

### PR DESCRIPTION
**Pull request by iand675**
Add mongoc package. Depends on #9401

### CODE REVIEW

**Comment by bjornfor** [comment]
Please squash "oops" commits.

**Comment by iand675** [comment]
OK, wasn't sure if force pushing over existing commits was acceptable or not for this project

**Comment by bjornfor** [comment]
For small PRs, that's preferred. For big, long-running PRs, there may be exceptions. But generally, make clean PRs :-)

**Comment by iand675** [comment]
OK, commits squashed. Build still failing because #9401 isn't merged yet.

**Comment by bjornfor** [comment]
Pushed to master (4bdcf1fa9525d8c63ac506956042b8ecc5d7e1e6) with tiny style cleanup. (Look at the formatting of the first lines.)

**Pull request closed without merging**
