### PR TITLE
git, gitweb: Fix git-instaweb

### LINKED ISSUE #53491: git-instaweb is broken
## Issue description

`git instaweb` start a webserver that is mean to serve `gitweb` for the current repo. In order to do this, it generates an httpd config with

```
server.document-root = "/nix/store/ailxcwnv97mjr2vmfv4jbc487w0qy1vn-git-2.19.2/share/gitweb"
```

But the expression for `git` moves `gitweb` to a separate output.

### Steps to reproduce

Run `git instaweb` in any repo.

### PR DESCRIPTION
**Pull request by kirelagin**
###### Motivation for this change

Git’s build system does two things with the `gitwebdir` variable:

1. Puts gitweb there
2. Embeds this path into `git-instaweb`

Before this change `git-instaweb` wouldn’t work as it was looking for gitweb in git’s `share` directory, but it was moved away into a separate output by the nix expression.

This PR sets the `gitwebdir` variable in the Makefile and points it to the `gitweb` output. As a result, a path to this output is now embedded into `git-instaweb`, which will affect the closure size, but, AFAIU, only if `perlSupport` is enabled, so this is probably not a problem? I also had to move the fixups from the `gitweb` expression to `git` itself to make sure that `gitweb.cgi` that is referenced from `git-instaweb` is functional.

Fixes #53491.

@gnidorah @peti @the-kenny @wmertens

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

* I always interrupted the build of `git` as its tests take too long, but I am relatively confident that it works as its tests were running successfully for quite a while.
* `git instaweb` now works
* I have not tried to build `gitweb` (as `git` never finished building), but I don’t think this change could break something in it.

### CODE REVIEW

**Comment by kirelagin** [comment]
For reference, I partially reverted #38918.

**Comment by gnidorah** [comment]
@kirelagin sorry, i don't use gitweb atm. Feel free to do whatever you find an appropriate.

**Comment by wmertens** [comment]
Since you're going from not working to working, I think you can merge if it works and if closure size is not impacted overly much.

**Comment by aanderse** [comment]
@kirelagin from your perspective what is the status on this?

**Comment by kirelagin** [comment]
I don’t see any reasons not to merge it.

**Comment by aanderse** [comment]
@mwertins can we get a merge please?

**Comment by wmertens** [comment]
Thanks, looking forward to trying it out!

**Pull request merged**
