### PR TITLE
Update jdreaver email, remove as prowlarr maintainer

### PR DESCRIPTION
**Pull request by jdreaver**
Hello! This PR updates my email to my current email (me@davidreaver.com) and removes myself as the maintainer of `prowlarr`. I never actually used `prowlarr` for more than a couple days after adding the package to nixpkgs, and I don't want users to think I actually maintain it.

### CODE REVIEW

**Comment by jdreaver** [comment]
Hey @fadenb @purcell @tie @corngood, sorry to bother you, but would you be able to help me approve this PR? I saw you tagged on a `sonarr` PR (https://github.com/NixOS/nixpkgs/issues/360592). I'm not sure who else to request a review from :sweat_smile:

**Review by fadenb — APPROVED** [review]

**Comment by fadenb** [comment]
Approved it on Github.
I believe there is also some discourse thread for merge-ready PRs that gets regularly attention by folks that have permissions to merge. If there is no speedy reaction here you could try that approach 🙂

**Comment by corngood** [comment]
I think it should really be two commits:

```
maintainers: update jdreaver email
prowlarr: remove jdreaver as maintainer
```

Also since it's just metadata I'm inclined to backport it to 24.11, unless anyone objects.

**Comment by jdreaver** [comment]
Thanks @fadenb and @corngood! Sorry about combining the commits. I've now broken this up into two commits with the commit messages that @corngood suggested.

**Review by corngood — APPROVED** [review]

**Pull request merged**
