### PR TITLE
 dovecot: 2.3.7 > 2.3.7.1

### PR DESCRIPTION
**Pull request by Izorkin**
#### Motivation for this change
Update packages dovecto to 2.3.7.1 and dovecot-pigeonhole to 0.5.7.1

Fixed load plugin sieve.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by mmahut — APPROVED** [review]
- [X] reviewed the diff and commit messages
- [X] made sure ofBorg build succeeded for all applicable platforms
- [X] run nix-review without any failures
- [X] run and tested the binaries

**Comment by dhess** [comment]
Thank you! The previous commit broke my IMAP server and it took me a few days to realize, since the sieve plugin was failing at runtime rather than at start-up.

**Comment by Izorkin** [comment]
Thanks!

**Comment by sjau** [comment]
Thanks. SNM works again.

**Pull request merged**
