### PR TITLE
ddcutil: 1.4.2 -> 2.0.0

### PR DESCRIPTION
**Pull request by rnhmjoj**
## Description of changes

Major update, it would be useful to do some testing

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files
- [x] Tested ddcutil get/set 10 on HDMI monitor 
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rnhmjoj** [comment]
Result of `nixpkgs-review pr 264189` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>deepin.dde-daemon</li>
  </ul>
</details>
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>clight</li>
    <li>clightd</li>
    <li>ddcui</li>
    <li>ddcutil</li>
    <li>enlightenment.enlightenment</li>
    <li>fastfetch</li>
    <li>gnomeExtensions.brightness-control-using-ddcutil</li>
  </ul>
</details>

**Comment by nh2** [comment]
Release:

* https://github.com/rockowitz/ddcutil/releases/tag/v2.0.0

also lists important changes regarding the shared library.

**Comment by rnhmjoj** [comment]
Yes, I had to update ddcui because of it. Maybe deepin.dde-daemon is failing too?

**Comment by rnhmjoj** [comment]
Looks like it.

**Comment by wineee** [comment]
https://github.com/NixOS/nixpkgs/pull/264280 should fix build error in dde-daemon

**Comment by rnhmjoj** [comment]
I tested ddcutil and ddcui on an HDMI monitor: everything is working as usual.

**Pull request merged**
