### PR TITLE
curl: Add GnuTLS as an alternative to openSSL

### PR DESCRIPTION
**Pull request by ikervagyok**
###### Motivation for this change

Added this option, as the game "Dont Starve" running in fhsUserEnv needs libcurl-gnutls.so.4, which we didn't have.
Also i find that having more choice regarding crypto(-libraries) is better.

It can be pulled even though it's marked WIP, but maybe we could/should add other libraries as well (libreSSL/...)
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by edolstra** [comment]
I'm fine with including an option for building with gnutls, but not including variants in `all-packages.nix`. That means more work for our build farm, and confusion for users (since `nix-env -qa` will show a bunch of apparently identical curl packages).

**Comment by globin** [comment]
@ikervagyok regarding your comment on building with libressl, it only needs overriding openssl with it so no other changes are necessary.

Otherwise this looks fine since you've addressed @edolstra's comment, is it good to go from your side?

**Comment by ikervagyok** [comment]
@globin I have nothing, which explicitly needs curlLibreSSL, or any other fork to test such a case. So from my perspective it's good to go. Maybe later other people (or I) add more SSL/TLS implementations.

**Comment by grahamc** [comment]
@ikervagyok is there work to be done on this PR, or is it complete?

**Comment by vcunat** [comment]
Merge-squash-ed and staged, with a minor nitpick changed.

**Comment by joachifm** [comment]
Looks like this was integrated.

**Comment by vcunat** [comment]
Oh, I forgot this. Maybe I even squashed the merge unintentionally.

**Pull request closed without merging**
