### PR TITLE
blender: fix enableNumpy option

### LINKED ISSUE #81218: blender 2.82 with numpy does not find numpy at run-time
**Describe the bug**
blender 2.82 built with enableNumpy set to true builds and installs without errors, but at run-time it fails to find numpy.
There may be other issues with other libraries not being found as I'm having trouble activating a number of plugins and I don't think all use numpy, though at the moment I can only say for certainty numpy doesn't work.

**To Reproduce**

1. Install blender with `blender.override { enableNumpy = true; }`
2. Run blender and go to the Scripting tab.
3. Type `import numpy` in the console.

The following comes up:
```
>>> import numpy
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
```

This worked with 2.81.

**Expected behavior**
numpy should be imported with no errors.

**Metadata**
Result of `nix-shell -p nix-info --run "nix-info -m"`:

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.6, NixOS, 20.09pre214772.55beed9922c (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre214772.55beed9922c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- blender
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by veprbl**
###### Motivation for this change

Fixes: #81218

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
not familiar with how blender calls python. But another option would be to use `python.withPackages(ps: [ ps.numpy]);` as your "python" interpreter. Essentially this will symlinkjoin all the site packages together, so call that "python" would be as if you were calling one with numpy installed

**Comment by veprbl** [comment]
I disregarded `python.withPackages` because I assumed it is not composable, but it actually it is. If it's composable then it looks like the better approach to use it, especially given that blender disregards PYTHONPATH by default.

**Comment by veprbl** [comment]
Actually, that didn't work. The blender links to the python interpreter directly so our wrappers don't have any effect. I will revert back to using the wrapper.

**Comment by jonringer** [comment]
ah, I didn't realize it was linking against it :(

**Comment by veprbl** [comment]
I think, this is ready now

**Review by jonringer — APPROVED** [review]
LGTM
launches fine
(not sure how to actually test the numpy use case)

```
[2 built, 14 copied (153.7 MiB), 47.8 MiB DL]
https://github.com/NixOS/nixpkgs/pull/81313
1 package built:
blender
```

**Comment by jonringer** [comment]
@GrahamcOfBorg build blender

**Comment by gebner** [comment]
`import numpy` works for me

**Comment by amurrayc** [comment]
This doesn't quite work for me.

It looks like addons are loaded before this command executes.  At least this is true for the Archipack Pro addon.

I get:

> Archipack PRO 2.2.6 : error while loading preset
> No module named 'numpy'

Importing numpy from the blender python console works fine.

If I then go into Preferences and toggle the addon it loads correctly (although settings are lost so it's not a very satisfactory workaround).

This was working before (for < 2.82)

**Comment by veprbl** [comment]
@amurrayc I'm not able to reproduce your issue with Archipack (not PRO, I guess?). Could you please open an issue and describe steps to reproduce. Please assume that we have little experience using extensions in Blender (which is true for me, at least).

**Pull request merged**
