### PR TITLE
renderdoc: 0.34pre -> 0.91

### PR DESCRIPTION
**Pull request by jansol**
###### Motivation for this change

Upstream got updated.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jansol** [comment]
Couldn't test `qrenderdoc` since it apparently insists on building against Qt 5.9.0 whereas KDE plasma is using 5.9.1 and it claims those are not compatible. If someone knows how to work around that, any help is very appreciated.

**Comment by jansol** [comment]
Figured out the Qt problem (mismanaged user channel was leaking) and everything's peachy again with #29790

**Comment by c0bw3b** [comment]
This builds fine actually

```shell
Result in /tmp/nox-review-225khxqw
total 0
lrwxrwxrwx 1 demo users 58 22 nov.  00:10 result -> /nix/store/vw8zzbzp7315sl0mg2fpq71rwb238n7c-renderdoc-0.91
```

**Comment by orivej** [comment]
This broke the sandboxed and Hydra builds because the package attempts to download files during the build: https://hydra.nixos.org/build/65599152

**Pull request merged**
