### PR TITLE
fheroes2: set platforms.unix instead of platforms.linux

### LINKED ISSUE #302354: fheroes2 builds fine on Apple Silicon Macs but the platform is not enabled in the formula
See https://github.com/ihhub/fheroes2/issues/2752

I think we should just add "aarch64-darwin" into the platforms list?

```
package.meta.platforms = [
           "aarch64-linux"
           "armv5tel-linux"
           "armv6l-linux"
           "armv7a-linux"
           "armv7l-linux"
           "i686-linux"
           "loongarch64-linux"
           "m68k-linux"
           "microblaze-linux"
           "microblazeel-linux"
           "mips-linux"
           "mips64-linux"
           "mips64el-linux"
           "mipsel-linux"
           "powerpc64-linux"
           "powerpc64le-linux"
           "riscv32-linux"
           "riscv64-linux"
           "s390-linux"
           "s390x-linux"
           "x86_64-linux"
         ]
```

### PR DESCRIPTION
**Pull request by pshirshov**
## Description of changes

enabled platforms.unix as per freeheroes works everywhere not only on Linux

fixes #302354

### CODE REVIEW

**Comment by karolchmist** [comment]
Looks good to me! Not sure why this check fails though...

```This PR is is targeting a channel branch```

**Review by karolchmist — APPROVED** [review]

**Comment by karolchmist** [comment]
Not sure where it comes from... Can you use the PR template (with all the ckecks etc) ? I see it's missing in your first comment, maybe somehow it impacts the checks.

**Comment by wegank** [comment]
Doesn't work on my aarch64-darwin machine:

```
> sh: line 1: iconv: command not found
```

**Comment by pshirshov** [comment]
I may confirm that everything works well with 

```
    (pkgs.fheroes2.overrideAttrs (oldAttrs: rec {
      buildInputs = oldAttrs.buildInputs ++ lib.optionals stdenv.isDarwin [ libiconv ];
      meta.platforms = lib.platforms.unix;
    }))
```

**Comment by wegank** [comment]
@ofborg eval

**Comment by wegank** [comment]
@ofborg build fheroes2

**Review by karolchmist — APPROVED** [review]
LGTM

**Pull request merged**
