### PR TITLE
libvirtd: polkit integration, security fixes

### PR DESCRIPTION
**Pull request by offlinehacker**
###### Motivation for this change

Currently if libvirtd module is enabled anyone can access libvirtd socket (not only read only), since sockets has wide read and write permissions. This is by design, since in most distros polkit is enabled and polkit does auth/authz checks. In nixos (polkit) auth was disabled and it was thought security was enforced by `unix_sock_rw_perms`, but it was not, since sockets were created by systemd with wide open permissions.

Anyway, enabling polkit authorization fixes all that and enables additional rules to be created. A default rule is that anyone with access to `libvirtd` group has access to libvirt, which is the same as in other distros.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by bjornfor — APPROVED** [review]
Nit: 2nd commit should have "nixos/libvirtd" prefix.

**Comment by offlinehacker** [comment]
fixed, thanks

**Comment by offlinehacker** [comment]
@GrahamcOfBorg build libvirtd

**Comment by offlinehacker** [comment]
@GrahamcOfBorg build libvirt

**Review by ajs124 — APPROVED** [review]

**Comment by offlinehacker** [comment]
I will merge this as it presents a security issue, where it is very easy to compromise nixos workstation running libvirtd. I am also using libvirt for some time with this configuration without any issues.

**Comment by conferno** [comment]
Should `services.libvirtd.enable = true` also set `services.polkit.enable = true` ?

**Comment by conferno** [comment]
Or
```js
if config.services.polkit.enable then <new code> else <old code>
```
?

Now
```js
services.libvirtd.enable = true 
services.polkit.enable = false
```
is not verboten, but will it work?

**Comment by offlinehacker** [comment]
Good catch I will create new pull request that explicitly enables polkit.

**Comment by jakobrs** [comment]
Can this be backported?

**Pull request merged**
