### PR TITLE
Add a `toInt` helper.

### PR DESCRIPTION
**Pull request by zagy**
While the function itself is pretty easy, it's not straitforward to find a way to convert string to int with nix.

### CODE REVIEW

**Comment by peti** [comment]
That function would be a lot more useful if it provided meaningful error handling. `toInt ''{ "foo" : "bar" }''`, for example, should probably not succeed.

Also, note that `toInt = builtins.fromJSON` would suffice in its current form; there's no need to bind and forward the `str` argument.

**Comment by nbp** [comment]
I suggest to assert to assert that the result is an Int, as expected.

**Comment by zagy** [comment]
You are absolutely right. Better now?

Or would an assert instead of throw be the better way?

**Comment by vcunat** [comment]
It looks good to me now.

**Comment by vcunat** [comment]
Assertions have the disadvantage of being unable to supply any description.

**Comment by domenkozar** [comment]
Pretty sure PHP has better functions than this :)

**Pull request closed without merging**
