### PR TITLE
nixos/python-test-driver: add an option to disable python linter

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

While it's a good idea to automate the linting of the python code used
for our tests, I think that it can be quite distracting when hacking on
a NixOS test.

I figured that it might be more convenient to add an option as a
shortcut for this to avoid that everyone needs to dig into the test
driver again.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by flokli** [comment]
We should pipe this through a warn somehow if that option is set, so it's really noticeable it should not be PRed as-is.

**Comment by worldofpeace** [comment]
This would make me a bit happier ref https://github.com/NixOS/nixpkgs/issues/72964. I still think linting when the values are in nix strings not as great.

**Comment by Ma27** [comment]
> I still think linting when the values are in nix strings not as great.

Tbh I fully agree! This is more or less the middle-ground-solution. I thought that there are probably good reasons to use some linting, but I think that there's no point to use this when actively working on a test.

As this is IMHO an improvement over the current situation - is there anything that keeps this from merging? :)

**Comment by worldofpeace** [comment]
> > I still think linting when the values are in nix strings not as great.
> 
> Tbh I fully agree! This is more or less the middle-ground-solution. I thought that there are probably good reasons to use some linting, but I think that there's no point to use this when actively working on a test.
> 
> As this is IMHO an improvement over the current situation - is there anything that keeps this from merging? :)


It's a nice middle-ground improvement. Though, it's a bit funny. Our testing function has an argument to disable a linter, it's unexpected. That being said, I'm going to merge it :smile:

**Review by worldofpeace — APPROVED** [review]
Things tested:

Built and read NixOS manual :heavy_check_mark: 
Ran a test with `skipLint` and saw a warning :heavy_check_mark:

**Pull request merged**
