### PR TITLE
rustPlatform.fetchCargoVendor: fetch git submodules

### PR DESCRIPTION
**Pull request by TomaSajt**
Related PR, where this issue was discovered: https://github.com/NixOS/nixpkgs/pull/356385/

Looks like I missed that `fetchgit` has `fetchSubmodules` set to `true` by default, so when I was copying the `importCargoLock` implementation, I did not also fetch the submodules like (it turns out) it did.

`fetchgit` defaults: https://github.com/NixOS/nixpkgs/blob/7b16c1362333191eac7ad5d03ead2eb283f779e3/pkgs/build-support/fetchgit/default.nix#L14-L33
`importCargoLock` calling `fetchgit`: https://github.com/NixOS/nixpkgs/blob/7b16c1362333191eac7ad5d03ead2eb283f779e3/pkgs/build-support/rust/import-cargo-lock.nix#L148-L152

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by JohnRTitor — COMMENTED** [review]
Could you run a nixpkgs-review on this to see if the other packages using this fetcher have their hash changed?

**Comment by TomaSajt** [comment]
Checked all other uses of `fetchCargoVendor`:
```
nix-build --check -A cargo-shuttle -A hieroglyphic.cargoDeps.vendorStaging -A popsicle.cargoDeps.vendorStaging -A python312Packages.json-stream-rs-tokenizer.cargoDeps.vendorStaging
```

and their hash didn't change, so it seems like they don't use submodules

**Comment by TomaSajt** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 356415`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 14 packages built:</summary>
  <ul>
    <li>cargo-shuttle</li>
    <li>cosmic-applets</li>
    <li>hieroglyphic</li>
    <li>mitmproxy2swagger</li>
    <li>mitmproxy2swagger.dist</li>
    <li>popsicle</li>
    <li>python311Packages.json-stream</li>
    <li>python311Packages.json-stream-rs-tokenizer</li>
    <li>python311Packages.json-stream-rs-tokenizer.dist</li>
    <li>python311Packages.json-stream.dist</li>
    <li>python312Packages.json-stream</li>
    <li>python312Packages.json-stream-rs-tokenizer</li>
    <li>python312Packages.json-stream-rs-tokenizer.dist</li>
    <li>python312Packages.json-stream.dist</li>
  </ul>
</details>

**Comment by JohnRTitor** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 356415`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 14 packages built:</summary>
  <ul>
    <li>cargo-shuttle</li>
    <li>cosmic-applets</li>
    <li>hieroglyphic</li>
    <li>mitmproxy2swagger</li>
    <li>mitmproxy2swagger.dist</li>
    <li>popsicle</li>
    <li>python311Packages.json-stream</li>
    <li>python311Packages.json-stream-rs-tokenizer</li>
    <li>python311Packages.json-stream-rs-tokenizer.dist</li>
    <li>python311Packages.json-stream.dist</li>
    <li>python312Packages.json-stream</li>
    <li>python312Packages.json-stream-rs-tokenizer</li>
    <li>python312Packages.json-stream-rs-tokenizer.dist</li>
    <li>python312Packages.json-stream.dist</li>
  </ul>
</details>

**Review by JohnRTitor — APPROVED** [review]

**Comment by JohnRTitor** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 356415`

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 12 packages built:</summary>
  <ul>
    <li>cargo-shuttle</li>
    <li>hieroglyphic</li>
    <li>mitmproxy2swagger</li>
    <li>mitmproxy2swagger.dist</li>
    <li>python311Packages.json-stream</li>
    <li>python311Packages.json-stream-rs-tokenizer</li>
    <li>python311Packages.json-stream-rs-tokenizer.dist</li>
    <li>python311Packages.json-stream.dist</li>
    <li>python312Packages.json-stream</li>
    <li>python312Packages.json-stream-rs-tokenizer</li>
    <li>python312Packages.json-stream-rs-tokenizer.dist</li>
    <li>python312Packages.json-stream.dist</li>
  </ul>
</details>

**Comment by TomaSajt** [comment]
I'll merge this in an hour.

**Comment by JohnRTitor** [comment]
Sure, I was just waiting for eval.

**Pull request merged**
