### PR TITLE
anydesk: 4.0.1 -> 5.1.2

### PR DESCRIPTION
**Pull request by shyim**
##### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @peterhoeg

### CODE REVIEW

**Comment by peterhoeg** [comment]
Thanks for this @shyim. Do you feel like adding yourself as maintainer (and removing me as I don't use this)?

**Comment by shyim** [comment]
@peterhoeg sure :). Changed the maintainers and removed you :)

**Comment by peterhoeg** [comment]
Thank you for taking this on. Lastly - please split the change where you add yourself to the maintainers/maintainer-list.nix file into a separate commit.

**Comment by shyim** [comment]
Its now in two commits :)

**Comment by jonringer** [comment]
if you could switch the order of the commits, otherwise if we checkout bf940bc, anydesk will fail to evaluate :/

**Comment by shyim** [comment]
Changed order @jonringer hopefully everything is now okay :sweat_smile:

**Pull request merged**
