### PR TITLE
lib/types.nix: add intBetween

### PR DESCRIPTION
**Pull request by Profpatsch**
Add a type for integers between a min and max value; also improve the type error message, see commit message.

- [x] tested manually

### CODE REVIEW

**Review by 0xABAB — COMMENTED** [review]
Port ranges have a smaller domain than the integers.

**Comment by volth** [comment]
Maybe also ```types.unsigned``` because ```intBetween 0 2147483647``` would be the most popular usage of ```intBetween```?

**Comment by 0xABAB** [comment]
@volth Yeah, there is a whole range of such functions that would be of interest. E.g. postiveInteger (if Nix supports bignums).

**Review by shlevy — APPROVED** [review]
OK by me

**Comment by Profpatsch** [comment]
Hm, before we merge we should maybe think about that:

> there is a whole range of such functions that would be of interest

If so, a new namespace for these types should probably be created?

**Comment by Profpatsch** [comment]
I’m thinking about maybe having `types.ints.<subtype>` to bundle all of these.

```
ints = rec {
  between = …
  uint16 = between 0 65535
  …
};
```

**Comment by Profpatsch** [comment]
I will refactor and open a new PR.

**Pull request closed without merging**
