### PR TITLE
Fix typo: s/propogate/propagate/

### LINKED ISSUE #16198: spellcheck
These are definitely not intentional:

https://github.com/NixOS/nixpkgs/search?utf8=✓&q=propogatedBuildInputs&type=Code

### PR DESCRIPTION
**Pull request by phanimahesh**
Fixes #16198

### CODE REVIEW

**Comment by FRidh** [comment]
Please use two separate commits and specify the names of the packages. Its quite a bit of extra work for such trivial changes, but it makes it a lot easier if one wants to backport these fixes.

**Comment by phanimahesh** [comment]
Two separate commits, one fixing attributes and the other fixing comments?

**Comment by FRidh** [comment]
I guess I didn't read the entire commit since I didn't see the comments which is why I said 2 commits.
If you change an expression, it needs a commit of its own.

**Comment by phanimahesh** [comment]
@FRidh Does this look good?

**Pull request merged**
