### PR TITLE
pythonPackages: sphinxcontrib-wavedrom: init at 2.0.0, wavedrom: init at 0.1

### PR DESCRIPTION
**Pull request by clacke**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Sphinx update is already in staging. Rebase onto staging.

**Comment by clacke** [comment]
Does not build on staging because `dejagnu` doesn't. Do we file issues against staging, or is this tracked somewhere else?

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by FRidh** [comment]
Nothing happening so closing.

**Comment by Spaqin** [comment]
Any plans on integrating sphinxcontrib-wavedrom 3.0+ to nixpkgs? Especially since wavedrom is already a part of it.

**Pull request closed without merging**
