### PR TITLE
use libsForQt512

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
Since upgrading to `20.09` I have noticed:
- `okteta` crashes on startup
- `k4dirstat` looks terrible
- `dolphinEmuMaster` [looks terrible](https://github.com/NixOS/nixpkgs/issues/101092)

These changes seem to fix the above issues.

This needs a backport to `20.09`.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
1. The dolphin issue seems unrelated to https://github.com/NixOS/nixpkgs/issues/100707.
2. The okteta issue is definitely related to https://github.com/NixOS/nixpkgs/issues/100707 but currently the list of affected packages there doesn't list it because it was generated by ofborg when `kdeFrameworks` didn't use qt515 by default.
3. The `k4dirstat` issue is the same as okteta.

@aanderse Could you please push the okteta and k4dirstat commits to https://github.com/NixOS/nixpkgs/pull/101369 ? An additional check of these packages with `libsForQt5` (515) would be worth it while at it.

There's a Nix script that may be handy to you / me / us if one wishes to verify incompatible qt versions are used together:

https://github.com/NixOS/ofborg/issues/533#issue-717633427

**Comment by doronbehar** [comment]
Both okteta and k4dirstat build and run and look fine on https://github.com/NixOS/nixpkgs/pull/101369 , with qt515.

**Comment by aanderse** [comment]
Thanks for your feedback @doronbehar. I'll remove `okteta` and `k4dirstat` from this PR.

For reference I have built `dolphinEmuMaster` 3 ways on/against `20.09` to see the ui:
```
nix-build -E 'with import <nixpkgs> {}; libsForQt512.callPackage <nixpkgs/pkgs/misc/emulators/dolphin-emu/master.nix> { CoreBluetooth = null; ForceFeedback = null; IOKit = null; OpenGL = null; }'
nix-build -E 'with import <nixpkgs> {}; libsForQt514.callPackage <nixpkgs/pkgs/misc/emulators/dolphin-emu/master.nix> { CoreBluetooth = null; ForceFeedback = null; IOKit = null; OpenGL = null; }'
nix-build -E 'with import <nixpkgs> {}; libsForQt515.callPackage <nixpkgs/pkgs/misc/emulators/dolphin-emu/master.nix> { CoreBluetooth = null; ForceFeedback = null; IOKit = null; OpenGL = null; }'
```

Only building against `libsForQt512` looked correct. When I build `dolphinEmuMaster` on `unstable` the ui also looks bad.

So do you agree I should keep this PR, but only the `dolphinEmuMaster` commit (dropping the other 2) and then backport to `20.09`?

**Comment by doronbehar** [comment]
> Only building against `libsForQt512` looked correct. When I build `dolphinEmuMaster` on `unstable` the ui also looks bad.

I can't reproduce this **on https://github.com/NixOS/nixpkgs/pull/101369** - building with either qt5 there gives an OK looking UI, to my view. Perhaps your environment is polluted, but that doesn't matter with https://github.com/NixOS/nixpkgs/pull/101369.

**Comment by aanderse** [comment]
Thanks for letting me know. Will that PR get back ported to `20.09`? It looks massive...

**Comment by doronbehar** [comment]
Yes we should.

**Comment by aanderse** [comment]
Thanks!

**Pull request closed without merging**
