### PR TITLE
stdenv setup: disallow references to the build directory

### PR DESCRIPTION
**Pull request by joachifm**
Extracted from https://github.com/NixOS/nixpkgs/pull/2281

Unfortunately, I lack the capacity for testing this, hopefully somebody is able and willing to do so in my stead (if this is something we want to do).

### CODE REVIEW

**Comment by joachifm** [comment]
I'm unsure how this interacts with multiple outputs, if at all.

**Comment by abbradar** [comment]
It seems to me it won't work for multiple outputs as it is -- but you may iterate over `$outputs` (if it's not set, assume `outputs="out"`.

**Comment by joachifm** [comment]
It now iterates over all the outputs

**Comment by joachifm** [comment]
I wonder if there's ever a legitimate reason to capture the build toplevel? If not, maybe we could make it only conditional on `NIX_ENFORCE_PURITY`.

**Comment by abbradar** [comment]
Not sure if that counts as "legitimate" but any package containing debug information will have references to its build paths (for binary text to source code lines mappings). We probably want to disable this in `enableDebugInfo`.

**Comment by joachifm** [comment]
Is it feasible to patch those references to a fixed path?

**Comment by abbradar** [comment]
It's a good idea but I'm not sure we can do it. Surely `/src/foo.cpp` is even better than `/tmp/nix-build-foo-1/src/foo.cpp` but this info is contained in a binary format -- not sure we can do something about it... Short of using mount namespaces to achieve constant path (`/build` for example) that is -- this will require changes to Nix but looks interesting.

**Comment by joachifm** [comment]
I like the mount namespace idea, seems like it would solve the problem "for real".

**Comment by edolstra** [comment]
I have trouble parsing the variable name `noErrorBuildTop`. (E.g. what is a "build top", what is an "error build top" and why is that thing negated?) Shouldn't that be something like `allowTmpDirReferences`?

Also, this functionality would be better to handle in Nix itself, which scans the outputs anyway. Now we're doing twice the I/O.

**Comment by joachifm** [comment]
@edolstra I can't speak to the motivation for the variable naming, but doing this in Nix itself makes sense.

**Comment by abbradar** [comment]
It seems I was mistaken -- we _do_ already use a constant build directory when we are in a sandbox!

```
    /* In a sandbox, for determinism, always use the same temporary
       directory. */
    tmpDirInSandbox = useChroot ? canonPath("/tmp", true) + "/nix-build-" + drvName + "-0" : tmpDir;
```

It'll still be nice to detect and prevent unwanted references to build directories -- I agree it'd better done in Nix.

**Comment by joachifm** [comment]
@abbradar ah, so this is basically a solved problem for sandboxed builds?

**Comment by abbradar** [comment]
It seems so (but we still want to control where build references are allowed I think -- so this PR/Nix issue is still relevant).

**Comment by bjornfor** [comment]
I always imagined that build dirs be Nix store paths. Then, for instance, the debug output can reference the build dir and all source lookup from debuginfo will Just Work.

**Comment by vcunat** [comment]
That would be possible, but you typically don't want the binaries depend on source files (i.e. keep them alive).

**Comment by bjornfor** [comment]
Right. I think perhaps Nix could learn about "weak" references.

**Comment by vcunat** [comment]
The general contention about weak references is that they break purity (slightly).  Note that there are ways to use weak references already, via obfuscating them, e.g. https://github.com/NixOS/nixpkgs/pull/15539

**Pull request closed without merging**
