### PR TITLE
linuxPackages.rtl8821ce: unstable-2022-06-01 -> unstable-2023-01-01

### PR DESCRIPTION
**Pull request by superherointj**
linuxPackages.rtl8821ce: unstable-2022-06-01 -> unstable-2023-01-01

### CODE REVIEW

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 214256` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>linuxKernel.packages.linux_testing_bcachefs.rtl8821ce</li>
  </ul>
</details>
<details>
  <summary>17 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_14.rtl8821ce</li>
    <li>linuxKernel.packages.linux_4_14_hardened.rtl8821ce</li>
    <li>linuxKernel.packages.linux_4_19.rtl8821ce</li>
    <li>linuxKernel.packages.linux_4_19_hardened.rtl8821ce</li>
    <li>linuxKernel.packages.linux_5_10.rtl8821ce</li>
    <li>linuxKernel.packages.linux_5_10_hardened.rtl8821ce</li>
    <li>linuxKernel.packages.linux_5_15.rtl8821ce</li>
    <li>linuxKernel.packages.linux_hardened.rtl8821ce (linuxKernel.packages.linux_5_15_hardened.rtl8821ce)</li>
    <li>linuxKernel.packages.linux_5_4.rtl8821ce</li>
    <li>linuxKernel.packages.linux_6_1.rtl8821ce</li>
    <li>linuxKernel.packages.linux_6_1_hardened.rtl8821ce</li>
    <li>linuxKernel.packages.linux_latest_libre.rtl8821ce</li>
    <li>linuxKernel.packages.linux_libre.rtl8821ce</li>
    <li>linuxKernel.packages.linux_lqx.rtl8821ce</li>
    <li>linuxKernel.packages.linux_xanmod.rtl8821ce</li>
    <li>linuxKernel.packages.linux_xanmod_latest.rtl8821ce (linuxKernel.packages.linux_xanmod_stable.rtl8821ce)</li>
    <li>linuxKernel.packages.linux_zen.rtl8821ce</li>
  </ul>
</details>

**Review by NickCao — APPROVED** [review]
You should have kept the PR template.

**Comment by superherointj** [comment]
> You should have kept the PR template.

I disagree. Just noise.
Which information did find missing?
I was doing batch work. Fixing all kernel modules that were broken.

**Comment by superherointj** [comment]
@NickCao Btw, nice work you have done here at Nixpkgs. You are churning PRs faster than I thought was possible. :-)

**Pull request merged**
