### PR TITLE
samba: fix cross-compilation

### PR DESCRIPTION
**Pull request by lopsided98**
###### Description of changes

https://github.com/NixOS/nixpkgs/pull/200545 mistakenly removed `wafHook` and the patch required to make cross-compilation work. In addition, the bundled version of heimdal is now too new to work with `asn1_compile` from the heimdal package in nixpkgs (it isn't out of date, there just hasn't been a release in years and samba uses an unreleased version).

To fix the latter issue, the native build of samba saves `asn1_compile` and `compile_et` from the bundled heimdal into the dev output, allowing them to be available at build time when cross-compiling.

cc @Majiir @ajs124

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
  - [x] armv6l-linux (cross)
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Majiir** [comment]
Cross-compiling works for `aarch64-multiplatform`. Thanks for the fix!

**Comment by ajs124** [comment]
can we maybe only use the non-vendored heimdal on cross?

**Comment by lopsided98** [comment]
What do you mean by non-vendored heimdal? Upstream heimdal packaged in nixpkgs is not compatible with samba. Samba requires its [own fork](https://gitlab.com/samba-team/devel/lorikeet-heimdal).

**Comment by ajs124** [comment]
Ah, yes. That's what I meant. Seems like I misread this PR and also… not sure what I committed in the update.

Since you're removing it as a buildInput this is all good.

**Pull request merged**
