### PR TITLE
teams: 1.4.00.7556 -> 1.4.00.13653

### PR DESCRIPTION
**Pull request by liff**
###### Motivation for this change

A new version of Teams was [released](https://teams.microsoft.com/downloads/).

No idea what changed overall but `libvulkan.so` made its appearance to the set of bundled libraries, whatever that might mean.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Do we want to backport this?

**Comment by liff** [comment]
Seems reasonable to me. What would disqualify this from backporting?

**Comment by drupol** [comment]
Impossible download this version from Microsoft:

```
building '/nix/store/givwpw09kggm4bb1q8rlranpsmq5fjhv-teams_1.4.00.13653_amd64.deb.drv'...
copying path '/nix/store/60ncgyr2anh1r1h7c7i7p1hz3p56sg0w-cairo-1.16.0-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/x805vlv62fwqw2k0sskfg7zayshjhf71-pango-1.48.4-dev' from 'https://cache.nixos.org'...

trying https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.4.00.13653_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   153    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
error: cannot download teams_1.4.00.13653_amd64.deb from any mirror
builder for '/nix/store/givwpw09kggm4bb1q8rlranpsmq5fjhv-teams_1.4.00.13653_amd64.deb.drv' failed with exit code 1
cannot build derivation '/nix/store/jzmpp0p6fzlwy7ygzflvshj8f1mxwzym-teams-1.4.00.13653.drv': 1 dependencies couldn't be built
error: build of '/nix/store/jzmpp0p6fzlwy7ygzflvshj8f1mxwzym-teams-1.4.00.13653.drv' failed
 ```

**Comment by drupol** [comment]
Seems like the issue is from Microsoft (no way!).

**Comment by liff** [comment]
Yeah the RPM works though. Perhaps they’ll fix it eventually.

**Pull request merged**
