### PR TITLE
pythonPackages.escapism: 0.0.1 -> 1.0.0 move to python-modules

### PR DESCRIPTION
**Pull request by costrouc**
###### Things done

pythonPackages.escapism: 0.0.1 -> 1.0.0 move to python-modules

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Thanks!

**Comment by costrouc** [comment]
@Mic92 I just wanted to ask a question. You merged my pull request without checking that it builds? I have submitted ~20 or so PRs to nixpkgs. Did you just trust me that it built under sandbox for me or did you test the PR locally? (Only asking because it makes me nervous that a package upgrade would be accepted without double checking - even if I do trust my PR).

**Comment by FRidh** [comment]
Looking at the amount of rebuilds you can't break much so often its not worth the scrutiny then :-) 
Considering the amount of contributions I do recommend adding yourself to the ofborg list so ofborg will build your PR's
https://github.com/NixOS/ofborg/blob/released/config.known-users.json

**Comment by Mic92** [comment]
@costrouc I use https://github.com/Mic92/nix-review for the majority of pull requests.

**Pull request merged**
