### PR TITLE
jetbrains.writerside: init at 232.10165

### PR DESCRIPTION
**Pull request by jopejoe1**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by liff** [comment]
Result of `nixpkgs-review pr 265628` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>jetbrains.writerside</li>
  </ul>
</details>

**Comment by liff** [comment]
Starts up fine.

**Review by liff — APPROVED** [review]

**Comment by pbsds** [comment]
Result of `nixpkgs-review pr 265628` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>jetbrains.writerside</li>
  </ul>
</details>

Builds and runs fine. I was initially thrown off by all the binaries suffixed `.sh`, but the desktop entry points to the right entrypoint, so it should be fine.

There is a file `${out}/writerside/bin/restart.py` with the shebang `#!/usr/bin/env python3` but rewriting it to the store might make for a worse developer experience in virtual environments. Thoughts @edwtjo?

**Comment by zlepper** [comment]
Due to the merge conflicts here, i have made an alternative PR at https://github.com/NixOS/nixpkgs/pull/304847 as i'm not sure how to continue on this PR. In addition the Jetbrains tools setup seems to have changed quite a bit, so it was easier to just start from scratch.

**Pull request closed without merging**
