### PR TITLE
ffmpeg: enable vulkan in small variant

### LINKED ISSUE #281631: ffmpeg: enable vulkan video by default
### Describe the bug

Ffmpeg 6.1 supports vulkan video, but it is not enabled in the default version of ffmpeg, it is only enabled in ffmpeg-full.
The default version of ffmpeg should support vulkan video so that applications like mpv can use it. Arch enables vulkan by [default](https://gitlab.archlinux.org/archlinux/packaging/packages/ffmpeg/-/blob/main/PKGBUILD?ref_type=heads#L218).

Vulkan video already works with amd GPUs using ffmpeg-full with this command:
```
RADV_PERFTEST=video_decode ffmpeg -init_hw_device "vulkan=vk:0" -hwaccel vulkan -hwaccel_output_format vulkan -i INPUT -f null - -benchmark
```

### Notify maintainers

 @Atemu @arthsmn 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Atemu**
Closure size: 493.6M -> 494.8M

Fixes https://github.com/NixOS/nixpkgs/issues/281631

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Atemu** [comment]
Hm, hold on I'm getting this error for some reason:

```
[AVHWDeviceContext @ 0xdde280] Unable to open the libvulkan library!
Device creation failed: -1313558101.
Failed to set value 'vulkan=vk:0' for option 'init_hw_device': Unknown error occurred
Error parsing global options: Unknown error occurred
```

It works in ffmpeg-full of the same revision.

**Comment by Atemu** [comment]
It does work when you also enable libplacebo? Is that a requirement for VK somehow @Tungsten842?

**Comment by Tungsten842** [comment]
While trying vulkan videgoo
I am not sure if this is caused by the fact that this is based on staging.
```
[AVHWDeviceContext @ 0x1a09280] Unable to open the libvulkan library!
Device creation failed: -1313558101.
Failed to set value 'vulkan=vk:0' for option 'init_hw_device': Unknown error occurred
Error parsing global options: Unknown error occurred
```

> It does work when you also enable libplacebo? Is that a requirement for VK somehow @Tungsten842?



> It does work when you also enable libplacebo? Is that a requirement for VK somehow @Tungsten842?

It doesn't seem so: https://github.com/FFmpeg/FFmpeg/blob/8e23ebe6f971ec4177be73b453960d83c264b7b5/configure#L3108
Does it work on top of master instead of staging?

**Comment by Tungsten842** [comment]
> It does work when you also enable libplacebo? Is that a requirement for VK somehow @Tungsten842?

It doesn't seem so:
https://github.com/FFmpeg/FFmpeg/blob/8e23ebe6f971ec4177be73b453960d83c264b7b5/configure#L3108
Does it work on top of master instead of staging?

**Comment by Atemu** [comment]
This is based on master/nixos-unstable (c3e128f3c0ecc1fb04aef9f72b3dcc2f6cecf370).

**Comment by Atemu** [comment]
It's apparently not getting linked to the vk loader somehow.

**Comment by Atemu** [comment]
Huh, I followed a hunch and removed vulkan-headers from buildInputs because libplacebo didn't add them and that made it work.

**Comment by Atemu** [comment]
Interesting, it is linked and actually works in `ffmpeg_4` but not anything newer.

**Comment by Atemu** [comment]
Opened https://trac.ffmpeg.org/ticket/10809#ticket

**Comment by Tungsten842** [comment]
> Opened https://trac.ffmpeg.org/ticket/10809#ticket

Anyway, can't we just enable libplacebo as well?
[Arch enables it](https://gitlab.archlinux.org/archlinux/packaging/packages/ffmpeg/-/blob/main/PKGBUILD?ref_type=heads#L187).
[Fedora enables it.](https://src.fedoraproject.org/rpms/ffmpeg/blob/rawhide/f/ffmpeg.spec#_632)
[Debian too](https://salsa.debian.org/multimedia-team/ffmpeg/-/blob/debian/master/debian/rules?ref_type=heads#L167).
And it includes a ton of useful filters: https://ffmpeg.org/ffmpeg-filters.html#libplacebo

**Comment by Atemu** [comment]
libplacebo is like +16M closure size.

**Review by arthsmn — APPROVED** [review]

**Review by Tungsten842 — APPROVED** [review]
Tested and working with the standard ffmpeg.

**Comment by travisghansen** [comment]
Would it be possible / appropriate to add this to `headless` as well?

**Comment by Atemu** [comment]
Could you open a separate issue on this and ping all current maintainers?

**Pull request merged**
