### PR TITLE
aliases: helpful 'fetchFromGithub' typo message

### PR DESCRIPTION
**Pull request by alyssais**
People keep asking for help on IRC because they’ve got the name wrong.

### CODE REVIEW

**Comment by Infinisil** [comment]
Not sure if this is the right solution for this. It might be possible for it to automatically throw such an error, I'll take a look at implementing this now.

**Comment by worldofpeace** [comment]
@alyssais I did this ALL THE TIME when I first used NixOS and I had to add a texteditor snippet to just never need to type it :smile:

**Comment by Synthetica9** [comment]
> Not sure if this is the right solution for this. It might be possible for it to automatically throw such an error, I'll take a look at implementing this now.

@Infinisil  You mean in Nix?

**Comment by Infinisil** [comment]
@Synthetica9 In nixpkgs, the `callPackage` function can detect missing arguments and search for similar ones in that case. Seems to work, currently working on similarity search :)

**Comment by Infinisil** [comment]
And implemented! See https://github.com/NixOS/nixpkgs/pull/79877

**Comment by emilazy** [comment]
I think it'd be a good idea to land this as a simple interim solution since #79877 seems mildly controversial, and simply revert it in that PR if people agree it's a reasonable approach.

**Comment by danbst** [comment]
I wish it was not an error, but a valid alias.

Maybe even rethink `fetch*` idiom. For example, put all fetchers into one collection:
```
fetch = {
  url = fetchUrl;
  zip = fetchZip;
  github = fetchFromGitHub;
  ...
};

{ stdenv, fetch, ... }:
stdenv.mkDerivation {
  srcs = [ 
    (fetch.url {
     ...
     })
    (fetch.github {
     ...
     })
  ];
```

**Comment by alyssais** [comment]
> I wish it was not an error, but a valid alias.

Then we’d get PRs from people with code that worked locally but didn’t work on OfBorg, because it (rightfully) doesn’t follow aliases.

**Review by Profpatsch — APPROVED** [review]

**Comment by alyssais** [comment]
@Infinisil go ahead and revert when you get it working the better way :)

**Pull request merged**
