### PR TITLE
oh-my-posh: 18.26.1 -> 19.6.0

### LINKED ISSUE #280961: Build failure: oh-my-posh
### Steps To Reproduce

1. build *oh-my-posh* package as part of a system flake on nixos-unstable branch
2. only broke today, however most recent working commit I have found is: 6660475dea29309327ee3b2e6824ec0011589017 which is obviously confusing

### Build log

[issue with response and log and error message, referred to you by author](https://github.com/JanDeDobbeleer/oh-my-posh/issues/4622)

### Additional context

package author says not their issue, but also says the package is out of date as they are on 19.5.2 and the package is on 18.26.1
My system config is:
https://github.com/BirdeeHub/birdeeSystems
Dont judge im kinda new I havent worked on secrets yet so I just dont have any secrets in it

### Notify maintainers

@lucperkins 
@urandom2

### PR DESCRIPTION
**Pull request by arjan-s**
Diff: https://github.com/jandedobbeleer/oh-my-posh/compare/refs/tags/v18.26.1...v19.6.0

Changelog: https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v19.6.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

fixes https://github.com/NixOS/nixpkgs/issues/280961
closes #279471

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by arjan-s** [comment]
Looks like @r-ryantm is trying to supersede this PR with https://github.com/NixOS/nixpkgs/pull/279471, let's see which gets merged first... :)

**Comment by BirdeeHub** [comment]
side note, wow the maintenance toll of reproducibly downloading things. Is there not a bot to update hashes and then revert if it breaks a test and alert a maintainer?

**Comment by arjan-s** [comment]
Yeah and that bot is @r-ryantm. But the main problem of nixpkgs is not people willing to create PRs like this one, it's the lack of people willing to review and merge them. Sometimes it's really quick, especially if someone with merging permissions has a personal interest in a package, and other times it just stays open for eternity and you almost have to beg to get someone to review and merge it.
There is even a Discord channel for this "begging", but I've posted this PR there a while ago and apparently nobody found it worth their while.

**Comment by lucperkins** [comment]
@arjan-s The "worth their while" comment is unfair and unnecessarily incendiary. I maintain over a dozen packages in Nixpkgs and many things outside of it and things simply get lost in the shuffle sometimes, _especially during the holiday season_. I get an absolute _torrent_ of emails from GitHub and I cannot possibly keep track of them all. I understand your frustration but this is not the way to express it.

**Review by lucperkins — APPROVED** [review]

**Comment by arjan-s** [comment]
Yeah you're right and I'm sorry for my bad choice of words. But I hope you agree that nixpkgs has a severe lack of reviewers and committers, causing even simple package updates to be postponed.

**Comment by lucperkins** [comment]
@arjan-s No worries, apology accepted. I do agree, but it's proven to be an intractable problem thus far. Suggestions to core Nixpkgs folks are always welcome.

**Comment by BirdeeHub** [comment]
Yeah at over 5k PRs it does become kinda... unmanageable to a degree XD

**Review by lucperkins — APPROVED** [review]

**Comment by BirdeeHub** [comment]
eyyy lemme try to unpin and see what happens XD

**Comment by BirdeeHub** [comment]
awwww im on unstable and not master XD

**Comment by dotlambda** [comment]
> How long does it take for stuff to get to unstable?

https://nixpk.gs/pr-tracker.html?pr=273191

**Comment by BirdeeHub** [comment]
Thats cool!! Thank you for the resource!!

**Pull request merged**
