### PR TITLE
Solarus games

### PR DESCRIPTION
**Pull request by ekureina**
###### Motivation for this change

Adding working games for users of Solarus.
Included is Mystery of Solarus and Return of the Hylian: Solarus Edition.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
The assets, which if I am correct are included, are copyrighted by Nintendo:
http://www.solarus-games.org/games/zelda-return-of-the-hylian-se/

> License: GNU GPL v3 (engine) - Copyright Nintendo (assets)

What is their license?

**Comment by Nate-Devv** [comment]
This is the list from zsdx:
https://github.com/christopho/zsdx/blob/dev/license.txt

**Comment by Nate-Devv** [comment]
I'm actually not sure, because no license is listed.

**Comment by FRidh** [comment]
In principle it would mean listing all licenses in the meta.licenses field.

Anyway, I think this cannot be included in Nixpkgs because

> - Some graphics, sounds and names include content that belong to Nintendo.
We don't own this content.

unless it is clear they're authorized to use this, in which case I would imagine there would be a license by Nintendo for it.

**Comment by Nate-Devv** [comment]
Ok, I'm going to wait for a game to have all free assets before I submit it to Nixpkgs. I'll work on the editor package in the meantime.

**Pull request closed without merging**
