### PR TITLE
tdesktop: 1.8.9 -> 1.8.13, range-v3: 0.5.0 -> 0.9.1

### PR DESCRIPTION
**Pull request by primeos**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by abbradar** [comment]
@GrahamcOfBorg build tdesktop

**Comment by abbradar** [comment]
Ah, didn't notice it's built already.

Thanks!

**Comment by d-goldin** [comment]
@abbradar @primeos: I'd be interested in having a more recent tdesktop in 19.09. Would this be possible?

**Comment by primeos** [comment]
@d-goldin sorry, I forgot to reply :o

Usually we mainly backport security updates, but there are sometimes other reasons. I just had a look at the documentation, but the relevant section is pretty short: [Stable release branches](https://nixos.org/nixpkgs/manual/#submitting-changes-stable-release-branches). If there's a good reason we can consider backporting some updates, but usually that would defy the purpose of the stable branch.

If you want a more recent version it might be best to use `tdeskop` from another channel like `nixos-unstable` (unfortunately this will require more storage for the dependencies, but overriding the derivation would result in long compilation times).

**Comment by d-goldin** [comment]
@primeos: Yeah, agreed. I was just thinking because it felt so outdated for a bit. Yeah, I will consider solving it for me locally.

**Pull request merged**
