### PR TITLE
stdenv: symlink propagated docs

### PR DESCRIPTION
**Pull request by oxij**
###### Motivation for this change

This sidesteps the original problem of #43547 as suggested by @Infinisil in https://github.com/NixOS/nixpkgs/issues/43547#issuecomment-405701974 and @dezgeg in https://github.com/NixOS/nixpkgs/pull/44516#issuecomment-410670228.

###### Things done

- [X] stdenv-linux builds.

###### Things not done

- Please try building stdenv on darwin.

### CODE REVIEW

**Review by Ericson2314 — APPROVED** [review]
Awesome!

**Comment by Ericson2314** [comment]
I like the new parameter order, too.

**Comment by oxij** [comment]
It just struck me that this can be simplified even more with the changes I already made here. Dropped all explicit `propagateDoc` uses from everywhere, it works out automagically anyway.

**Comment by oxij** [comment]
Ping. I just successfully built my whole Linux system on top of this change. I also doubt this version will break anything on Darwin as it now selects `propagateDoc` automagically.

I'd merge.

**Comment by Ericson2314** [comment]
Sorry for no merge from me; I'm temporary unable to test on Darwin. Thanks @matthewbauer

**Comment by edolstra** [comment]
IMHO the correct fix is to use `propagated-user-env-packages`.

**Comment by oxij** [comment]
@edolstra can you elaborate why? I feel like it makes no difference semantically speaking but it's simpler.

**Comment by Ericson2314** [comment]
I was to be able to do `nix-shell -p stdemv.cc.man` and have that work too. That preludes propagated user env packages.

**Pull request merged**
