### PR TITLE
nixos/xserver: drop intel from videoDrivers

### PR DESCRIPTION
**Pull request by 7c6f434c**
###### Motivation for this change

#55520 — the old `intel` driver might create problems in multi-GPU multi-output situations (and maybe in some other situations requiring precise use of modern features).

###### Things done

I have not tested it properly as I don't run NixOS mainline. (I did switch to `modesetting` after X.org update in Nixpkgs).

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by volth** [comment]
Wouldn't it affect opencl programs on intel?

**Comment by 7c6f434c** [comment]
Good question. No idea, actually. Is there _any_ GPGPU framework that works on X/Linux without being tied to a bitrotten video driver not fully supporting modern XRandR, I wonder.

**Comment by flokli** [comment]
cc @oxij

**Comment by oxij** [comment]
OpenCL will probably stop working, also intel-gpu-tools and, as a consequence, intel-vaapi-driver will also stop working.

**Comment by 7c6f434c** [comment]
Hm. It looks like Intel VA-API somewhat supports Wayland, I wonder if that means they are also fine with modesetting https://github.com/intel/libva/issues/53. And Beignet claims to work without X11 if desired.

If you have a Nix expression that uses OpenCL on Intel around — I run a Intel+Nvidia i965+nouveau modesetting system, so I can check if that code works.

**Comment by volth** [comment]
> If you have a Nix expression that uses OpenCL on Intel around

```$(nix-build --no-out-link '<nixpkgs>' -A scallion)/bin/scallion -l```

**Comment by vcunat** [comment]
People doing GPGPU will probably know enough to add `videoDriver = "intel";` into their configs.

**Comment by 7c6f434c** [comment]
@volth thanks. It seems to look for OpenCL configuration in a place defined relative to `libGL`. Adding `beignet` to the packages for `opengl-driver` `buildEnv` seems to help.
```
Using default runtime: v4.0.30319
Id:0 Name:Intel(R) HD Graphics IvyBridge M GT2
    PreferredGroupSizeMultiple:16 ComputeUnits:16 ClockFrequency:1000
    MaxConstantBufferSize:134217728 MaxConstantArgs:8 MaxMemAllocSize:1610612736
```

@vcunat by now I mostly collect information for release notes.

**Comment by volth** [comment]
> @volth thanks. It seems to look for OpenCL configuration in a place defined relative to `libGL`. Adding `beignet` to the packages for `opengl-driver` `buildEnv` seems to help.
> 
> ```
> Using default runtime: v4.0.30319
> Id:0 Name:Intel(R) HD Graphics IvyBridge M GT2
>     PreferredGroupSizeMultiple:16 ComputeUnits:16 ClockFrequency:1000
>     MaxConstantBufferSize:134217728 MaxConstantArgs:8 MaxMemAllocSize:1610612736
> ```

Do you mean
```
hardware.opengl.extraPackages = [ pkgs.beignet ];
```
?

It does not work
```
Using default runtime: v4.0.30319                                                                                                                                   
cl_get_gt_device(): error, unknown device: 3e94                                                                                                                     
                                                                                                                                                                    
Unhandled Exception:                                                                                                                                                
System.InvalidOperationException:  ErrorCode:'-1'                                                                                                                   
  at scallion.CLDeviceInfo.CheckError (System.Int32 err) [0x0001a] in <89fbbd43e3ea45959e2cf53514100388>:0                                                          
  at scallion.CLDeviceInfo.GetDeviceIds (System.IntPtr platformId, OpenTK.Compute.CL10.DeviceTypeFlags deviceType) [0x00011] in <89fbbd43e3ea45959e2cf53514100388>:0
  at scallion.CLDeviceInfo+<>c.<GetDeviceIds>b__5_0 (System.IntPtr i) [0x00000] in <89fbbd43e3ea45959e2cf53514100388>:0                                             
  at System.Linq.Enumerable+SelectManySingleSelectorIterator`2[TSource,TResult].ToArray () [0x00028] in <dbc731b3823b48689299547fb566d4a8>:0                        
  at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <dbc731b3823b48689299547fb566d4a8>:0                 
  at scallion.CLDeviceInfo.GetDeviceIds () [0x0002a] in <89fbbd43e3ea45959e2cf53514100388>:0                                                                        
  at scallion.CLRuntime.GetDevices () [0x00001] in <89fbbd43e3ea45959e2cf53514100388>:0                                                                             
  at scallion.Program.ListDevices () [0x00004] in <89fbbd43e3ea45959e2cf53514100388>:0                                                                              
  at scallion.Program.Main (System.String[] args) [0x00263] in <89fbbd43e3ea45959e2cf53514100388>:0                                                                 
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException:  ErrorCode:'-1'                                                                                
  at scallion.CLDeviceInfo.CheckError (System.Int32 err) [0x0001a] in <89fbbd43e3ea45959e2cf53514100388>:0                                                          
  at scallion.CLDeviceInfo.GetDeviceIds (System.IntPtr platformId, OpenTK.Compute.CL10.DeviceTypeFlags deviceType) [0x00011] in <89fbbd43e3ea45959e2cf53514100388>:0
  at scallion.CLDeviceInfo+<>c.<GetDeviceIds>b__5_0 (System.IntPtr i) [0x00000] in <89fbbd43e3ea45959e2cf53514100388>:0                                             
  at System.Linq.Enumerable+SelectManySingleSelectorIterator`2[TSource,TResult].ToArray () [0x00028] in <dbc731b3823b48689299547fb566d4a8>:0                        
  at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <dbc731b3823b48689299547fb566d4a8>:0                 
  at scallion.CLDeviceInfo.GetDeviceIds () [0x0002a] in <89fbbd43e3ea45959e2cf53514100388>:0                                                                        
  at scallion.CLRuntime.GetDevices () [0x00001] in <89fbbd43e3ea45959e2cf53514100388>:0                                                                             
  at scallion.Program.ListDevices () [0x00004] in <89fbbd43e3ea45959e2cf53514100388>:0                                                                              
  at scallion.Program.Main (System.String[] args) [0x00263] in <89fbbd43e3ea45959e2cf53514100388>:0                                                                 
```

**Comment by gloaming** [comment]
> cl_get_gt_device(): error, unknown device: 3e94

@volth Coffee Lake (but not including CL-R) is supported only in their HEAD, see https://github.com/intel/beignet/commit/7e181af2ea4d37f67406f2563c0e13fa1fdbb14b

Should we move nixpkgs ahead of the release version? It's not clear if they will make another, since it's more or less dead.

**Comment by volth** [comment]
It makes sense, ```master``` is not updated for 1 year and it is 249 commits ahead of the latest release.
At least, ```beignet-unstable``` is to be added along with ```beignet```

**Comment by volth** [comment]
https://cgit.freedesktop.org/beignet/ seems a few commits ahead than https://github.com/intel/beignet/commits/master
Should we use it ?

**Comment by gloaming** [comment]
@7c6f434c I'm not sure that there _is_ any relationship between the (Intel) display and OCL drivers - I didn't see any mention of a GPU driver requirement on Intel's website, nor in the READMEs in their github repos.

I tested disabling modesetting and using the fbdev and vesa drivers on my machine, in turn, and `waifu2x-converter-cpp --force-OpenCL` still ran fine with both, even though the vesa driver doesn't actually work for me. This is using `intel-ocl` though, since I'm on CL-R.

@volth could you test the same with `beignet`?

**Comment by volth** [comment]
I am not an expert in driver internals, but it seems that ```interl-ocl``` adds **CPU** into the list of the OpenCL devices while ```beignet``` adds built-in **GPU** (for example ```scallion``` works about 3 times faster than on CPU device, but much slower than on Nvidia).
So I have them both.

On the picture https://github.com/NixOS/nixpkgs/pull/62993:
 * ```Id:0``` - beignet
 * ```Id:1``` - nvidia
 * ```Id:2``` - intel-ocl

**Pull request merged**
