### PR TITLE
nomad_1_5: init

### PR DESCRIPTION
**Pull request by MagicRB**
###### Description of changes

Add new Nomad version, tested to compile and passes upstream tests.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by numkem** [comment]
What’s missing for this to be merged, I was looking at doing the same thing.

**Review by endocrimes — APPROVED** [review]

**Comment by jaen** [comment]
@MagicRB you might want to consider bumping it to 1.5.5 – https://github.com/hashicorp/nomad/releases.

**Comment by Cottand** [comment]
@MagicRB  I was also thinking about doing a PR to get Nomad 1.5. What is there left to do to move this PR forward?

Separately 
- is it not also necessary to change the `nomad` alias to use the new `nomad_1_5` [here](https://github.com/NixOS/nixpkgs/pull/226429/files#diff-b6c79b9e1267515d0d1f6cc0e3f787656084184c901f58fdd7c2b900dfa24540L47)?
- [nomad 1.5.6 is out](https://github.com/hashicorp/nomad/blob/main/CHANGELOG.md)

**Comment by MagicRB** [comment]
Sorry all, I've been very busy, will bump

**Review by cdepillabout — APPROVED** [review]
LGTM

I'm not one of the maintainers, but this seems like a straight-forward addition.  Any objections to merging?

**Comment by ketzacoatl** [comment]
Who needs to approve before we can hit da button and merge?

**Comment by cdepillabout** [comment]
@ketzacoatl Any committer can merge.

In https://github.com/NixOS/nixpkgs/pull/226429#pullrequestreview-1450118084 I was trying to ask @MagicRB if there are any objections from their side to going ahead and merging, but no response yet.  Although I guess I wasn't clear that I was directing that question at @MagicRB!

**Comment by MagicRB** [comment]
Ah, sorry, I've been busy, thanks for the number of pings  :joy:

I'm going to repin to `1.5.6` later today and then we can merge

**Comment by MagicRB** [comment]
@cdepillabout done

**Comment by cdepillabout** [comment]
@MagicRB Thanks for continuing to work on this!

**Pull request merged**
