### PR TITLE
pulumi-bin: 3.1.0 -> 3.3.0

### PR DESCRIPTION
**Pull request by t0yv0**
###### Motivation for this change

Updating Pulumi CLI and providers to latest stable versions.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mausch** [comment]
Hi Anton, welcome to nixpkgs! 🙂 

There's a convention here for commit messages / PR titles... in this case they should say `pulumi-bin: 3.1.0 -> 3.3.0`, can you change it please?

BTW I'm getting hash mismatches on NixOS x86_64 e.g.

```
hash mismatch in fixed-output derivation '/nix/store/lgcklqyad6nwbk43fczkb6syjymdrksv-pulumi-v3.3.0-linux-x64.tar.gz':
  wanted: sha256:0kcq7zwgbp465lx7p80l5xc50xdmydq32djzis0973hxlkgliiq6
  got:    sha256:1n3gyhrnmg9rl0hif83cw6cmfl733rw83ghpy1m5vz42h5qcxb2q
```

Try using [nix-prefetch-url](https://nixos.org/manual/nix/unstable/command-ref/nix-prefetch-url.html) to get the correct hashes.

**Comment by austinbutler** [comment]
One of our two PRs should be closed as a duplicate: https://github.com/NixOS/nixpkgs/pull/123625

**Comment by austinbutler** [comment]
Result of `nixpkgs-review pr 123900` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pulumi-bin</li>
  </ul>
</details>

**Comment by t0yv0** [comment]
Closing as duplicate of #123625 

@mausch my PR and @austinbutler have the same hashes, what happened here. Let me try to rebuild on linux. Hm, nope, rebuilds cleanly..

It is quite concerning. Did you happen to observe a state where the binary at https://get.pulumi.com/releases/sdk/pulumi-v3.3.0-linux-x64.tar.gz got updated in place? We had this issue once before but I believe we followed up and fixed the problem (I work at Pulumi).

**Comment by t0yv0** [comment]
Some additional digging on the checksums:

```
$ nix-hash --to-base16 --type sha256 0kcq7zwgbp465lx7p80l5xc50xdmydq32djzis0973hxlkgliiq6
06c748dfa41d8e93808e5f363170f3b57550582f14a07b3a2d86dcf5f83f984d

$ nix-hash --to-base16 --type sha256 1n3gyhrnmg9rl0hif83cw6cmfl733rw83ghpy1m5vz42h5qcxb2q
58acce708182fc5d6af017be81781ee3505799e16c201721a039bd6a33f46fd8
```

The first one matches official checksums:
https://get.pulumi.com/releases/sdk/pulumi-3.3.0-checksums.txt

**Comment by mausch** [comment]
@t0yv0 Hmm, this is what I get on both my NixOS x86_64 machine and my Ubuntu x86_64 machine:

```
$ nix-prefetch-url https://get.pulumi.com/releases/sdk/pulumi-v3.3.0-linux-x64.tar.gz
[59.9 MiB DL]
path is '/nix/store/lgcklqyad6nwbk43fczkb6syjymdrksv-pulumi-v3.3.0-linux-x64.tar.gz'
1n3gyhrnmg9rl0hif83cw6cmfl733rw83ghpy1m5vz42h5qcxb2q
```

but the declared hash in both PRs is `0kcq7zwgbp465lx7p80l5xc50xdmydq32djzis0973hxlkgliiq6` ...

Plus the build has passed in https://github.com/NixOS/nixpkgs/pull/123625 , so not sure what's going on here... 
Maybe I'm getting a slightly different binary due to some CDN caching, since you mention it has happened before?
Can you or anyone else try that nix-prefetch-url ?

**Comment by t0yv0** [comment]
I've got this from our ops: `this specific release was paused halfway through due to a GHA failure` so I can't totally rule out that you may have observed an incorrect binary. 

You should be getting a correct binary now though. Does this work the same for you?

```
$ curl -L https://get.pulumi.com/releases/sdk/pulumi-v3.3.0-linux-x64.tar.gz --output pulumi-v3.3.0-linux-x64.tar.gz
$ nix-hash --flat --type sha256 pulumi-v3.3.0-linux-x64.tar.gz 
06c748dfa41d8e93808e5f363170f3b57550582f14a07b3a2d86dcf5f83f984d
```

**Comment by mausch** [comment]
I get a different output for that on my 3 local machines: `58acce708182fc5d6af017be81781ee3505799e16c201721a039bd6a33f46fd8` :confused:

**Comment by t0yv0** [comment]
OK that's not good at all. 

Assuming you are not a victim of a MITM attack rewriting binaries.. mind running the curl command with `--verbose`?

**Comment by t0yv0** [comment]
Could also try `curl -L https://get.pulumi.com/releases/sdk/pulumi-v3.3.0-linux-x64.tar.gz?v=1 --output pulumi-v3.3.0-linux-x64.tar.gz` to bypass any URL-based caching, though I'd be really surprised if that gives a different answer?

**Comment by t0yv0** [comment]
What I get with --verbose:

```
curl --verbose -L "https://get.pulumi.com/releases/sdk/pulumi-v3.3.0-linux-x64.tar.gz?a=4" --output pulumi-v3.3.0-linux-x64.tar.gz
< -L "https://get.pulumi.com/releases/sdk/pulumi-v3.3.0-linux-x64.tar.gz?a=4" --output pulumi-v3.3.0-linux-x64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 99.84.219.107:443...
* Connected to get.pulumi.com (99.84.219.107) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [4826 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=pulumi.com
*  start date: Feb  8 00:00:00 2021 GMT
*  expire date: Mar  9 23:59:59 2022 GMT
*  subjectAltName: host "get.pulumi.com" matched cert's "*.pulumi.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x7fba1f013000)
} [5 bytes data]
> GET /releases/sdk/pulumi-v3.3.0-linux-x64.tar.gz?a=4 HTTP/2
> Host: get.pulumi.com
> user-agent: curl/7.74.0
> accept: */*
> 
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
} [5 bytes data]
< HTTP/2 200 
< content-type: application/x-gzip
< content-length: 62778211
< date: Thu, 20 May 2021 20:06:12 GMT
< last-modified: Thu, 20 May 2021 20:01:36 GMT
< etag: "3f38342f45a1560837307df0b96511bf-12"
< content-disposition: attachment; filename=pulumi-v3.3.0-linux-x64.tar.gz
< accept-ranges: bytes
< server: AmazonS3
< x-cache: Hit from cloudfront
< via: 1.1 a4d8112508e8450a57296bb3736a5137.cloudfront.net (CloudFront)
< x-amz-cf-pop: IAD79-C1
< x-amz-cf-id: D3NUhxnpj4TqI4ZfF2fz7_PUcAFkvbAcF94JBoxv0g7ueIj1vX8uIw==
< age: 329235
< 
{ [15991 bytes data]
100 59.8M  100 59.8M    0     0  34.1M      0  0:00:01  0:00:01 --:--:-- 34.1M
* Connection #0 to host get.pulumi.com left intact
```

**Comment by mausch** [comment]
Yeah, seems I'm getting a different binary:

```
< HTTP/1.1 200 OK
< Content-Type: application/x-gzip
< Content-Length: 62778192
< Connection: keep-alive
< Date: Thu, 20 May 2021 19:13:04 GMT
< Last-Modified: Thu, 20 May 2021 13:42:44 GMT
< ETag: "37edd7f9c74e1cdae5e9c093406f9fb5-12"
< Content-Disposition: attachment; filename=pulumi-v3.3.0-linux-x64.tar.gz
< Accept-Ranges: bytes
* Server AmazonS3 is not blacklisted
< Server: AmazonS3
< X-Cache: Hit from cloudfront
< Via: 1.1 0883b90b3f1903ffbd69ae1c8936b7a6.cloudfront.net (CloudFront)
```

I also tried downloading this on some EC2 instance in eu-west-1 and I'm getting the same binary as in my local machines.

SSL looks good BTW.

> to bypass any URL-based caching, though I'd be really surprised if that gives a different answer

Didn't make any difference

**Comment by t0yv0** [comment]
eu-west-1, let me spin one up and try.

**Comment by t0yv0** [comment]
I can reproduce! Working on this with our ops.

**Comment by austinbutler** [comment]
Interesting, yeah I got the same `0kcq7zwgbp465lx7p80l5xc50xdmydq32djzis0973hxlkgliiq6` hash between multiple computers and even on corporate VPN.

**Comment by t0yv0** [comment]
We have invalidated the CloudFront caches and now I can no longer reproduce the issue in the EU region. @mausch could you try one more time please? Thanks.

**Comment by mausch** [comment]
Yep all good now :+1:

**Pull request closed without merging**
