### PR TITLE
 paxctl: Fix darwin and cross without mass-rebuild for 18.09

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

Backport of of #47400.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ericson2314** [comment]
@oxij philosoraptor me: if I do the staging cleanup first, then I cannot forget. :D

**Comment by oxij** [comment]
I tried for a while but I still can't parse. :) Philosoraptor? What?

**Comment by Ericson2314** [comment]
It's an old meme...whose name I didn't know until I looked it up to write that so know worries.

**Comment by oxij** [comment]
I know that meme, but I can't parse what the above sentence means anyway. I would've expected something like

```
If I add a hack to prevent a mass-rebuild into master
<the philosoraptor goes here>
can I conveniently forget to add a cleanup for it into staging?
```

For which I would say: "but of course you should not". :]

**Pull request merged**
