### PR TITLE
khal,stig,deluge_1,libtorrent-rasterbar,linkchecker: Disable failing tests

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Motivation for this change
#101045

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 106309` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>khal</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 106309` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>kodiPlugins.yatp</li>
    <li>libtorrentRasterbar</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>deluge</li>
    <li>khal</li>
    <li>linkchecker</li>
    <li>python37Packages.libtorrentRasterbar</li>
    <li>python38Packages.libtorrentRasterbar</li>
    <li>python39Packages.libtorrentRasterbar</li>
    <li>stig</li>
    <li>styx</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 106309` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>deluge</li>
    <li>kodiPlugins.yatp</li>
    <li>libtorrentRasterbar</li>
    <li>python37Packages.libtorrentRasterbar</li>
    <li>python38Packages.libtorrentRasterbar</li>
    <li>python39Packages.libtorrentRasterbar</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>khal</li>
    <li>linkchecker</li>
    <li>stig</li>
    <li>styx</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 106309` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>khal</li>
  </ul>
</details>

**Review by doronbehar — APPROVED** [review]

**Pull request merged**
