### PR TITLE
buildFlutterApplication: prevent conflicting app directories

### PR DESCRIPTION
**Pull request by RossComputerGuy**
## Description of changes

Place app directories in `$out/app/$name` to prevent `environment.systemPackages` to complain about colliding app directories. This should result in paths like `$out/app/example-1.2.3`.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by 999eagle — CHANGES_REQUESTED** [review]
intiface-central needs `extraWrapProgramArgs` to be changed to `"--chdir $out/app/$name"` for this change to work, haven't tested any of the other packages

**Comment by RossComputerGuy** [comment]
@999eagle Sweet, thanks for catching that one I missed.

**Review by DSeeLP — APPROVED** [review]

**Comment by RossComputerGuy** [comment]
Any last reviews or things I missed before this gets merged?

**Comment by hacker1024** [comment]
It may be nicer to not include the version in the path. That way, if people need to write scripts or make links or anything without evaluating any Nix, those paths will be stable across updates.

I also wonder if there's a more standard path to use than `/app`? Maybe something traditionally in `/usr/local` (`libexec`?) or `/opt`?

**Comment by RossComputerGuy** [comment]
> It may be nicer to not include the version in the path. 

For whatever reason, I was thinking adding the version would let people have multiple versions of a package in their environment lol.

> That way, if people need to write scripts or make links or anything without evaluating any Nix, those paths will be stable across updates.

Wouldn't people just reference `$out/bin/${meta.mainProgram}` (`lib.getExec`)?

> I also wonder if there's a more standard path to use than `/app`? Maybe something traditionally in `/usr/local` (`libexec`?) or `/opt`?

`libexec` probably is better.

**Comment by hacker1024** [comment]
> For whatever reason, I was thinking adding the version would let people have multiple versions of a package in their environment lol.

That makes sense, though if someone for whatever reason wants two slightly different derivations with the same version at once, that will still be a problem.

If you are using two versions at once, you could always change the name of one with `overrideAttrs`. IMO, I'd rather have the consistency of having to do that every time rather than hope that there's no version collision - but I'm not terribly fussed either way.

> Wouldn't people just reference `$out/bin/${meta.mainProgram}` `(lib.getExec)`?

I'd imagine so, yes. I was thinking more about cases where Nix is not involved.

For example, say you build a number of apps for the Web, and host the linkFarm containing them with a web server. The browser would cache some files -  but if those paths change after an update, that cache would be unusable, even though not every file may have changed.

This is of course a very specific scenario, but I imagine it could affect other things of this nature like file indexing or shell caches.

**Comment by RossComputerGuy** [comment]
I'd consider it trivial, if people see the error then they'd check the files and see what's wrong. Let's see what @FlafyDev thinks.

**Comment by FlafyDev** [comment]
> I'd consider it trivial, if people see the error then they'd check the files and see what's wrong. Let's see what @FlafyDev thinks.

Sorry for the late response, I didn't mean to stall this. I don't really mind either way, but `$pname` does feel more intuitive to me. Mostly because nothing else in the $out directory is versioned anyway.

**Review by FlafyDev — APPROVED** [review]

**Review by DSeeLP — APPROVED** [review]

**Comment by RossComputerGuy** [comment]
Yeah, I couldn't find all packages which would be affected.

**Pull request merged**
