### PR TITLE
treewide: add bool type to enable options, or make use of mkEnableOption

### PR DESCRIPTION
**Pull request by xaverdh**
###### Motivation for this change

When trying out the [nixos-manager graphical user interface for nixos](https://github.com/pmiddend/nixos-manager), I noticed that lots of services had enable options without type information, leading to nixos-manager not showing a slider for them.
Fix this by adding missing type information to manually specified enable options or replacing them by mkEnableOption where appropriate (i.e. trivial text with service name and such).

### CODE REVIEW

**Comment by xaverdh** [comment]
Side note: It would have been useful (for testing this) if the `nixos` manual / man pages could be build separately (not as part of a system  rebuild).

**Comment by xaverdh** [comment]
The `rebuild-linux` tag is no longer applicable, I initially overlooked a case where the default value was true (so it could/should not be switched to `mkEnableOption`), after fixing this, the tag stayed though. Is there a way to recompute those tags from github ci?

**Comment by Mic92** [comment]
Thanks!

**Comment by Mic92** [comment]
Might be worth a backport.

**Comment by ajs124** [comment]
For reference: #76184

**Pull request merged**
