### PR TITLE
mesa: enable intel vulkan driver

### PR DESCRIPTION
**Pull request by Ralith**
###### Motivation for this change

This implements the changes in discussed in #17993, which appear to work when tested with vulkaninfo from #19920. Thanks to @lummax and @vcunat for coming up with the actual modifications performed here.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ralith** [comment]
The cube demo that ships with the loader currently segfaults on startup, so this probably isn't finished yet. Either that or it's just my ivy bridge chip. Anyone got skylake to test?

**Comment by Ralith** [comment]
With this and #19936 I'm able to run simple Vulkan programs, so it looks good from here.

**Comment by Myrl** [comment]
Cube demo? I have a Skylake.

**Comment by Myrl** [comment]
I tried cube and tri demo. Failed to load textures and segfault respectively.

**Pull request merged**
