### PR TITLE
Revert "qt5, libsForQt5: 5.12 -> 5.14 on darwin"

### LINKED ISSUE #185615: qt5 applications broken on darwin
### Describe the bug

Upon launch of any qt application it's icon appears in the dock, but no windows are opened. It will hang indefinitely and dock says "Application does not respond".

Bisecting, say, `wireshark` points to a88af94894f31e6cce358e49610a6fcb5b4f6f13 cc @willcohen
```
a88af94894f31e6cce358e49610a6fcb5b4f6f13 is the first bad commit
commit a88af94894f31e6cce358e49610a6fcb5b4f6f13
Author: Will Cohen <willcohen@users.noreply.github.com>
Date:   Wed Apr 13 15:27:00 2022 -0400

    qt5, libsForQt5: 5.12 -> 5.14 on darwin

 pkgs/top-level/all-packages.nix | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)
```

### Steps To Reproduce
1. `nix-build . -A wireshark`
2. `result/Applications/Wireshark.app`

### Expected behavior

Qt applications should work

### Additional context
The issue is not specific to wireshark.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-darwin"`
 - host os: macOS 10.16 and on 10.14
```

### PR DESCRIPTION
**Pull request by veprbl**
Reverts NixOS/nixpkgs#168524

The original change came without any testing on the target platform and caused a regression.

Fixes: #185615

### CODE REVIEW

**Comment by willcohen** [comment]
The benefit of 5.14 over 5.12 was just that it was "less" end-of-life, but I'm highly in favor of reverting if there's any breakages being detected.

**Review by willcohen — APPROVED** [review]

**Comment by veprbl** [comment]
@tanshihaj Does this fix your issue?

**Comment by tanshihaj** [comment]
No, downgrading to 5.12 will not help me since qt support aarch64-darwin starting from 5.15. So maybe better to bump it to 5.15?

**Comment by veprbl** [comment]
@tanshihaj So you are saying that `qt5` was broken on aarch64-darwin all this time? I have not seen any issue filed for that...

**Comment by willcohen** [comment]
That’s been my understanding as well — other broken aarch64 stuff has messed up my home install so I haven’t had a chance to test on my new M2 machine though.

**Comment by veprbl** [comment]
Search reveals there is one issue https://github.com/NixOS/nixpkgs/issues/130240
and this one is relevant https://github.com/NixOS/nixpkgs/issues/147817
as the clang 5 toolchain is likely the main cause for incompatibility

**Comment by tanshihaj** [comment]
@veprbl yes `qt5` was broken on aarch64-darwin all this time, moreover it was explicitly disabled here https://github.com/NixOS/nixpkgs/blame/7908242f926b3df62b46e98a69e88a2a60265125/pkgs/development/libraries/qt-5/modules/qtbase.nix#L377 until I've fixed build for Qt 5.15 here: https://github.com/NixOS/nixpkgs/commit/940b020fe73f1882163060e90300bc46732f19f9

**Pull request closed without merging**
