### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/pull/101199 apparently breaks Ghostscript. Currently working on a fix along with updating Ghostscript and jbig2dec.

**Comment by vcunat** [comment]
`libical` regressed:
```
  The following tests FAILED:
           1 - regression (SEGFAULT)
     36 - recur (SEGFAULT)
          41 - timezones (Failed)
        45 - libical-glib-array (Failed)
       47 - libical-glib-component (Failed)
           56 - libical-glib-timezone (Failed)
```
(reproduced multiple times on two of my machines, too)

**Comment by vcunat** [comment]
Uh, I'm really sorry.  I made a mistake merge.  Reverting it in c778945806b undid the state on master, but now I realize it crippled the git merge mechanism.  As the merge contained a mix of commits from `master..staging-next` and other commits from `staging-next..staging`, it got the `staging-next` branch into a state which I don't immediately know how to recover.

**Comment by FRidh** [comment]
If we disable force push I could push my state of `staging-next`.

**Comment by jtojnar** [comment]
@vcunat The reverted commit 17f5305b6c20df795c365368d2d868266519599e had a8a018ddc0a (master) and 0594e27df32 (supposedly staging) as parents. But weirdly, GitHub shows the latter only as master. How did you merge it into master in the first place?

**Comment by vcunat** [comment]
Well, it's the commit that showed the effect of the crippled git merge, but undoing it wouldn't really help us.  I don't think force-push really helps at this point.  Perhaps if I undid that c778945 merge on master immediately by a force push but I didn't even have permissions to consider it (and at that point I didn't realize how difficult this will be to recover).

**Comment by vcunat** [comment]
I typically don't use the green button.  I merge by command-line.  And I merged the PR commit which was one new commit atop some `staging` version.

**Comment by FRidh** [comment]
Merge master into staging-next, and then into staging, and on staging revert the revert commit.

**Comment by jtojnar** [comment]
Oh, you mean you ran `git merge 0594e27` on master, then reverted the merge, and then merged to staging? We could check that all commits since the merge commit 17f5305 are included in `git diff a8a018d master`.

**Comment by vcunat** [comment]
@FRidh: yes, that's the standard approach which would fix `staging`.  But it can't fix `staging-next`, due to the bad commit mix.

**Comment by vcunat** [comment]
I think I locally reconstructed the state we want at `staging-next`, so I guess I'll just apply that diff as a new `staging-next` commit.  Well, I'll first push into my own branch and let you comment...

**Comment by vcunat** [comment]
Here: a2188f5c2.  I expect I should have a look at it with clear head tomorrow; I don't feel like pushing it today.

_Of course, I'd push this to `staging-next`, then merge `staging-next` to `staging` and there I'd have to revert this diff and c77894580._

**Comment by jansol** [comment]
Alternatively trash this PR, rewind staging-next to the last commit before this mess, merge from master and then cherry-pick the commits from this PR and overwrite the history of staging-next with that. That way we get to keep the proper commit data.

**Comment by vcunat** [comment]
I'm not sure how exactly to do that approach.  Merging from master breaks things here, as the revert done on master didn't undo the effect on subsequent merge-bases.  Practically speaking, _part_ of changes "in this PR" (against master) were merged into master and then reverted,

**Comment by jansol** [comment]
Basically
1. fork master as it is
2. `git cherry-pick` all the commits that should be added from staging-next to that branch, one by one. This also gives them new hashes so there shouldn't be any conflicts with the reverts
3. force push that new branch to staging-next, replacing the broken history with the new one

Assuming of course that force pushing to staging-next is an option and no further mistakes happen while doing it. Either way, best sleep on it first.

**Comment by vcunat** [comment]
I still can't see that as an easy way.  Most of those commits didn't originate on the `staging-next` branch but `staging`.  If we only had two branches participating in this problem, it would've been relatively easy (revert + merge + re-revert), but there are three of them.  With that plan we'd probably want to also rebase part of the `staging` history, but it seems actually quite common to file pull requests against `staging`...  overall I'd prefer to avoid history rewriting on these three branches; it feels less risky that way.

**Comment by vcunat** [comment]
So, let me really take responsibility and fix this.  I reconsidered the approach, redid the whole process anew carefully and arrived at the same tree hash.  I added better description of what I did into the commit message.

**Comment by jonringer** [comment]
@GrahamcOfBorg test installer.simple

**Comment by FRidh** [comment]
libical test failures are due to the tzdata bump in 8904ce243aa885e0295610bd4e1dc7ca293e8919. Basically, the tests need updating. https://github.com/libical/libical/issues/449

**Comment by FRidh** [comment]
I have not been able to disable the failing tests of libical using `--exclude-regex`.

**Comment by FRidh** [comment]
@vcunat this is strange, github reports there are only few commits that are going to be merged with this PR.

**Comment by jansol** [comment]
@FRidh there used to be until [this](https://github.com/NixOS/nixpkgs/pull/101207#issuecomment-716207420)

**Pull request merged**
