### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by vcunat**
https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents

### CODE REVIEW

**Comment by vcunat** [comment]
If I read [the new rules](https://github.com/nixos/rfcs/blob/master/rfcs/0085-nixos-release-stablization.md#restriction-timeline) right, starting from the next week we'll switch to
> Release Critical Packages are Restricted.

**Comment by jonringer** [comment]
> If I read [the new rules](https://github.com/nixos/rfcs/blob/master/rfcs/0085-nixos-release-stablization.md#restriction-timeline) right, starting from the next week we'll switch to

Correct, I was just about to make the same post :)

Restricted packages are listed: https://nixos.github.io/release-wiki/Release-Critical-Packages.html#list-of-release-critical-packages

essentially:
   - binutils
   - gcc
   - glibc
   - systemd
   
The implications are that breaking changes for the packages should not be merged into staging (already too late if it's already on staging, like this PR). Patches and other non-breaking changes are still welcome. Just want to prevent a lot of work for us before a release.

**Comment by mweinelt** [comment]
`python3Packages.sphinx_rtd_theme` relies on `npm` in setup.py. Therefore  72ccdc1ff46f2ab4b21a0d0c37ff0f6f9a681d5b breaks the package. @FRidh @jonringer 

https://nix-cache.s3.amazonaws.com/log/a2bf6ba7z43hy50ydkv3swhli4hssqjf-python3.8-sphinx_rtd_theme-0.5.1.drv

https://github.com/readthedocs/sphinx_rtd_theme/blob/master/setup.py#L11-L26

```
class WebpackBuildCommand(setuptools.command.build_py.build_py):

    """Prefix Python build with Webpack asset build"""

    def run(self):
        if not 'CI' in os.environ and not 'TOX_ENV_NAME' in os.environ:
            subprocess.run(['npm', 'install'], check=True)
            subprocess.run(['node_modules/.bin/webpack', '--config', 'webpack.prod.js'], check=True)
        setuptools.command.build_py.build_py.run(self)
``

**Comment by FRidh** [comment]
@mweinelt fixed with 80e725f3dc9daff0b720b4cb7d7088cdc65e015d

**Comment by FRidh** [comment]
> If I read the new rules right, starting from the next week we'll switch to

Exciting times ahead, let's see what gets shoved into staging!

**Comment by vcunat** [comment]
We'll see.  In some sense it would be best if the staging freezes always came as a surprise to the general nix* community ;-)

**Comment by mweinelt** [comment]
Eval error for `mimemagic` was on master and has already been reverted.

**Comment by jtojnar** [comment]
@vcunat @FRidh what do you think about merging https://github.com/NixOS/nixpkgs/pull/117081 into staging-next/master after this is merged? The changes were reasonably tested and I just rebased it again onto staging-next.

**Comment by vcunat** [comment]
It seems there are still very many regressions in python packages, maybe mostly a consequence of #117452.

**Comment by mweinelt** [comment]
Well, this is as before every release, and was already expected. https://github.com/NixOS/nixpkgs/pull/117452#issuecomment-813016930

**Comment by FRidh** [comment]
> It seems there are still very many regressions in python packages, maybe mostly a consequence of #117452.

I will have a further look later today.

**Comment by jonringer** [comment]
> @vcunat @FRidh what do you think about merging #117081 into staging-next/master after this is merged? The changes were reasonably tested and I just rebased it again onto staging-next.

I'm okay with this, and in the RFC85 I gave exception to desktop managers about merging breaking changes. As long as it improves the user experience, it's good.

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/eval-1663744.html

Too big for a GitHub comment these days.

<sup>Generated by [eval-report](https://github.com/samueldr/nix-review-tools/blob/master/eval-report)</sup>

**Comment by jonringer** [comment]
@vcunat I had a fix for cinnamon-common here: https://github.com/NixOS/nixpkgs/pull/120094/commits/eefc6780531cd0ceea23928a2fe76c2b80c2836a

**Comment by vcunat** [comment]
I was only watching this thread so I didn't notice.  I almost put the change on the same lines too 😄

**Comment by alyssais** [comment]
Eval is broken on staging-next due to a conflict between 24896293e40cecb2f22cc4db0a13c41697745049 (which makes scandir python 2 only) and dbfbfa380e1 (which adds a python 3 package depending on scandir).  CC @cole-h @FRidh

**Comment by cole-h** [comment]
Eval fails because scandir was marked python2-only in 24896293e40 (even though it doesn't appear to be?).

**Comment by vcunat** [comment]
So, we're [getting](https://hydra.nixos.org/eval/1664901?compare=1664893) to a state that's good enough for master?  Or at least close?  It's certainly not like all the regressions got fixed, but...

**Comment by FRidh** [comment]
Will take some time to check the manual still builds after Haskell updates. Python packages can be fixed by their maintainers.

**Pull request merged**
