### PR TITLE
aws-c-common: 0.4.64 -> 0.5.2, unmark musl broken, enable tests 

### PR DESCRIPTION
**Pull request by r-burns**
###### Motivation for this change

Reenable AWS support in pkgsMusl.nix

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-burns** [comment]
Looks like this requires an aws-c-io bump as well, I'll just roll that up here if that's all right

**Comment by r-burns** [comment]
Some of these failures look concerning to me. I especially don't want to break cachix, hercules, or cabal2nix. Thought this would be a simple bump! Going to take a closer look at this.

Result of `nixpkgs-review pr 115157` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>fusionInventory</li>
    <li>nix-exec</li>
    <li>nixui</li>
  </ul>
</details>
<details>
  <summary>16 packages failed to build:</summary>
  <ul>
    <li>cabal2nix</li>
    <li>cachix</li>
    <li>crystal2nix</li>
    <li>haskellPackages.cachix</li>
    <li>haskellPackages.hercules-ci-agent</li>
    <li>haskellPackages.nix-paths</li>
    <li>haskellPackages.update-nix-fetchgit</li>
    <li>hercules-ci-agent</li>
    <li>libnixxml</li>
    <li>nix-du</li>
    <li>nix-serve</li>
    <li>python37Packages.nix-kernel</li>
    <li>python38Packages.nix-kernel</li>
    <li>python39Packages.nix-kernel</li>
    <li>update-nix-fetchgit</li>
    <li>vulnix</li>
  </ul>
</details>
<details>
  <summary>37 packages built:</summary>
  <ul>
    <li>aws-c-cal</li>
    <li>aws-c-common</li>
    <li>aws-c-event-stream</li>
    <li>aws-c-io</li>
    <li>aws-checksums</li>
    <li>aws-sdk-cpp</li>
    <li>bundix</li>
    <li>crate2nix</li>
    <li>dep2nix</li>
    <li>go2nix</li>
    <li>nix (nixStable)</li>
    <li>nix-bundle</li>
    <li>nix-direnv</li>
    <li>nix-doc</li>
    <li>nix-index</li>
    <li>nix-pin</li>
    <li>nix-plugins</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-cvs</li>
    <li>nix-prefetch-docker</li>
    <li>nix-prefetch-git</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-update</li>
    <li>nix-update-source</li>
    <li>nixFlakes (nixUnstable)</li>
    <li>nixos-generators</li>
    <li>nixos-shell</li>
    <li>nixpkgs-review</li>
    <li>python37Packages.nixpkgs</li>
    <li>python37Packages.pythonix</li>
    <li>python38Packages.nixpkgs</li>
    <li>python38Packages.pythonix</li>
    <li>python39Packages.nixpkgs</li>
    <li>python39Packages.pythonix</li>
    <li>vgo2nix</li>
  </ul>
</details>

**Comment by r-burns** [comment]
Ah nevermind. Looks like hydra is lagging pretty far behind so the ghc build failed on my local system. This is probably fine, but I'll keep it a draft until I can verify it doesn't break stuff on darwin.

**Comment by r-burns** [comment]
Ok, this is ready. Looks like hercules-ci-agent has been failing on master since Jan 6? (cc @roberth just as a heads up)

Result of `nixpkgs-review pr 115157` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>fusionInventory</li>
    <li>nix-exec</li>
    <li>nixui</li>
  </ul>
</details>
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>crystal2nix</li>
    <li>haskellPackages.hercules-ci-agent</li>
    <li>haskellPackages.update-nix-fetchgit</li>
    <li>hercules-ci-agent</li>
    <li>libnixxml</li>
    <li>nix-du</li>
    <li>python39Packages.nix-kernel</li>
    <li>update-nix-fetchgit</li>
  </ul>
</details>
<details>
  <summary>45 packages built:</summary>
  <ul>
    <li>aws-c-cal</li>
    <li>aws-c-common</li>
    <li>aws-c-event-stream</li>
    <li>aws-c-io</li>
    <li>aws-checksums</li>
    <li>aws-sdk-cpp</li>
    <li>bundix</li>
    <li>cabal2nix</li>
    <li>cachix</li>
    <li>crate2nix</li>
    <li>dep2nix</li>
    <li>go2nix</li>
    <li>haskellPackages.cachix</li>
    <li>haskellPackages.nix-paths</li>
    <li>nix (nixStable)</li>
    <li>nix-bundle</li>
    <li>nix-direnv</li>
    <li>nix-doc</li>
    <li>nix-index</li>
    <li>nix-pin</li>
    <li>nix-plugins</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-cvs</li>
    <li>nix-prefetch-docker</li>
    <li>nix-prefetch-git</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-serve</li>
    <li>nix-update</li>
    <li>nix-update-source</li>
    <li>nixFlakes (nixUnstable)</li>
    <li>nixos-generators</li>
    <li>nixos-shell</li>
    <li>nixpkgs-review</li>
    <li>python37Packages.nix-kernel</li>
    <li>python37Packages.nixpkgs</li>
    <li>python37Packages.pythonix</li>
    <li>python38Packages.nix-kernel</li>
    <li>python38Packages.nixpkgs</li>
    <li>python38Packages.pythonix</li>
    <li>python39Packages.nixpkgs</li>
    <li>python39Packages.pythonix</li>
    <li>vgo2nix</li>
    <li>vulnix</li>
  </ul>
</details>

**Comment by r-burns** [comment]
Result of `nixpkgs-review pr 115157` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>nix-exec</li>
  </ul>
</details>
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
    <li>tests.nixos-functions.nixosTest-test</li>
  </ul>
</details>
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>haskellPackages.hercules-ci-agent</li>
    <li>hercules-ci-agent</li>
    <li>libnixxml</li>
  </ul>
</details>
<details>
  <summary>58 packages built:</summary>
  <ul>
    <li>aws-c-cal</li>
    <li>aws-c-common</li>
    <li>aws-c-event-stream</li>
    <li>aws-c-io</li>
    <li>aws-checksums</li>
    <li>aws-sdk-cpp</li>
    <li>bundix</li>
    <li>cabal2nix</li>
    <li>cachix</li>
    <li>common-updater-scripts</li>
    <li>crate2nix</li>
    <li>crystal2nix</li>
    <li>dep2nix</li>
    <li>fusionInventory</li>
    <li>go2nix</li>
    <li>haskellPackages.cachix</li>
    <li>haskellPackages.nix-paths</li>
    <li>haskellPackages.update-nix-fetchgit</li>
    <li>hydra-unstable</li>
    <li>lispPackages.quicklisp-to-nix</li>
    <li>lispPackages.quicklisp-to-nix-system-info</li>
    <li>nix (nixStable)</li>
    <li>nix-bundle</li>
    <li>nix-direnv</li>
    <li>nix-doc</li>
    <li>nix-du</li>
    <li>nix-index</li>
    <li>nix-pin</li>
    <li>nix-plugins</li>
    <li>nix-prefetch</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-cvs</li>
    <li>nix-prefetch-docker</li>
    <li>nix-prefetch-git</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-serve</li>
    <li>nix-update</li>
    <li>nix-update-source</li>
    <li>nixFlakes (nixUnstable)</li>
    <li>nixos-generators</li>
    <li>nixos-rebuild</li>
    <li>nixos-shell</li>
    <li>nixpkgs-review</li>
    <li>nixui</li>
    <li>python37Packages.nix-kernel</li>
    <li>python37Packages.nixpkgs</li>
    <li>python37Packages.pythonix</li>
    <li>python38Packages.nix-kernel</li>
    <li>python38Packages.nixpkgs</li>
    <li>python38Packages.pythonix</li>
    <li>python39Packages.nix-kernel</li>
    <li>python39Packages.nixpkgs</li>
    <li>python39Packages.pythonix</li>
    <li>update-nix-fetchgit</li>
    <li>vgo2nix</li>
    <li>vulnix</li>
  </ul>
</details>

**Comment by roberth** [comment]
>  Looks like hercules-ci-agent has been failing on master since Jan 6? (cc @roberth just as a heads up)

Thanks! I'll release 0.8.0 today, which is compatible with the latest cachix library.

**Pull request merged**
