### PR TITLE
tree-wide: autorename gnome packages to use dashes

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
Closes: https://github.com/NixOS/nixpkgs/issues/32804

The only rebuild should be `plasma-nm`, where patch has been modified.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
@GrahamcOfBorg eval

**Comment by jtojnar** [comment]
I checked it once again and did not found any issues except for missing gnome-2 aliases, which I have now added.

**Comment by bjornfor** [comment]
Great stuff! May I suggest to squash the last fixup commit, as to not break git bisect?

**Comment by jtojnar** [comment]
@bjornfor I would leave it for just before the merge. It is useful if I need to re-generate it.

**Pull request merged**
