### PR TITLE
default to including "man" in outputsToInstall

### LINKED ISSUE #24717: Missing man pages for packages with multiple outputs
## Issue description

For packages with multiple outputs the default meta.outputsToInstall is `[ "out" ]` which won't install any documents/man pages required by this. On NixOS this is resolved using the man module as shown in the link below:

  https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/man.nix#L27

On other platforms such as Linux or Darwin, this NixOS option doesn't trigger and the meta.outputsToInstall defaults to `["out"]` which means missing man pages for any package that uses multiple outputs to separate its man pages.

This can be fixed by modifying the meta.outputsToInstall attribute for the specific package, but I feel like this behavior isn't intended and is more of a bug. Patching each package where including manuals makes sense seems like a pain.

### Steps to reproduce

On Darwin/Linux:

    nix-env -i nix
    nix-env --help || man nix-env || echo "Nobody here but us chickens"

## Technical details

* System: darwin x86_64
* Nix version: 1.11.8
* Nixpkgs version: 17.09pre105100.78adf1832f

### PR DESCRIPTION
**Pull request by dtzWill**
Fixes #24717

In particular, `man tmux` works after installing tmux with `nix-env`.

This likely breaks things or is bad for some reason, but should work as a starting point.

TODO:

* [ ] Ensure NixOS `programs.man.enable = false;` works (as well as `= true`).

### CODE REVIEW

**Comment by Ericson2314** [comment]
1. If this indeed is sufficient, this is super important to merge.

2. What about `info` outputs?

**Comment by dezgeg** [comment]
I think if you do this, `programs.man.enable = false;` in a NixOS configuration doesn't stop installing the manpages anymore. 

I don't know of an easier solution right now, though. Maybe `nix-env` itself should call into some `nixpkgs` function to build user environments (which could then look in `config.enableMan` or something to see whether manpages should be installed or not).

@edolstra ?

**Comment by jokogr** [comment]
I do have some installations where I prefer not to have man pages installed to save some storage space, so please do not merge this right away.

**Comment by Ericson2314** [comment]
@dezgeg How about we control this with a config option?

**Comment by dezgeg** [comment]
The problem is that it's use-case dependant of whether the `man` output needs to be installed in a particular `buildEnv` or not, that would be a global solution to a local problem.

**Comment by Ericson2314** [comment]
@dezgeg excellent point. Can we give buildEnv an `additionalOutputsToInstall` parameter, which is a whitelist or predicte on output names?

**Comment by fpletz** [comment]
Does anybody know what broke this? Did multiple outputs break this? Or Nix 2.0?

I'm not using `nix-env` much so I'm not sure. If this didn't work in 17.09 or 17.03, this isn't a release blocker imho.

**Comment by Ericson2314** [comment]
@fpletz I'm not sure it ever worked, but I don't really know.

**Comment by matthewbauer** [comment]
Nix only started looking at outputsToInstall Nix 2.0, IIRC. See https://github.com/NixOS/nix/pull/815

**Comment by Ericson2314** [comment]
Good sleuthing! Can we get a nix-level fix for 18.09??

**Review by matthewbauer — APPROVED** [review]

**Comment by matthewbauer** [comment]
I'd like to get this merged but I can't figure out what the error is coming from...

**Comment by dtzWill** [comment]
> I'd like to get this merged for 19.03 but I can't figure out what the error is coming from...

weechat error seems to due to copying `meta` (including `meta.outputsToInstall`) to the wrapper expression which doesn't have a `man` output.  Not sure how to best solve but seems the problem is 'best' not whether it can be solved at all :).  Maybe wrapper should be propagating the man pages too? Or filter `outputsToInstall` when copying meta? Dunno.

**Comment by dtzWill** [comment]
!!!! :confetti_ball: :+1: :smile_cat:

**Comment by masaeedu** [comment]
Awesome, thank you so much!

**Comment by lilyball** [comment]
We should probably extend this to include `info` by default.

**Comment by matthewbauer** [comment]
> We should probably extend this to include `info` by default.

Perhaps, although at some point it makes sense to just drop outputsToInstall altogether and use nix-env's default behavior of installing everything. https://github.com/NixOS/nixpkgs/pull/44168

**Comment by lilyball** [comment]
The downside to just installing everything is this means downloading more artifacts that I may not want. For example, if a given package vends a binary, a library, and dev headers, and all I care about is the binary (which is why I'm installing it directly), I certainly don't need to download and install the dev headers.

**Pull request merged**
