### PR TITLE
libreoffice: add update script and 7.2.5 -> 7.3.3 take two

### LINKED ISSUE #174063: Libreoffice fails to build on on darwin
### Description
Apparently the DMG download is 404'ing - see below.

Perhaps a different mirror should be  used:
https://download.documentfoundation.org/libreoffice/stable/7.3.3/mac/x86_64/LibreOffice_7.3.3_MacOS_x86-64.dmg.mirrorlist

### Steps To Reproduce
```
▶ nix run nixpkgs#libreoffice
error: builder for '/nix/store/g6z18avdmmv323shzybvjm2ni9dmmhhd-LibreOffice_7.2.5_MacOS_x86_64.dmg.drv' failed with exit code 1;
       last 7 log lines:
       >
       > trying https://download.documentfoundation.org/libreoffice/stable/7.2.5/mac/x86_64/LibreOffice_7.2.5_MacOS_x86_64.dmg
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0   316    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > curl: (22) The requested URL returned error: 404
       > error: cannot download LibreOffice_7.2.5_MacOS_x86_64.dmg from any mirror
       For full logs, run 'nix log /nix/store/g6z18avdmmv323shzybvjm2ni9dmmhhd-LibreOffice_7.2.5_MacOS_x86_64.dmg.drv'.
error: 1 dependencies of derivation '/nix/store/cr1fdxwdx8x2w3112qcp1g1ainsamxax-libreoffice-7.2.5.drv' failed to build

```

### Notify maintainers
@tricktron

### Metadata
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.8.0`
 - channels(me): `""`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

### PR DESCRIPTION
**Pull request by tricktron**
###### Description of changes
Fixes https://github.com/NixOS/nixpkgs/issues/174063.

The `7.2.5` version is already outdated and 404'ing. This pr adds the following:
- Update script with [nixt](https://github.com/nix-community/nixt/) tests to ease the update process: just run `nix-shell maintainers/scripts/update.nix --argstr package libreoffice` to update to the latest stable version from https://download.documentfoundation.org/libreoffice/stable/. Furthermore, this may even enable and trigger simple https://github.com/ryantm/nixpkgs-update package pr to proactively update to the latest stable version.
- Updates from 7.2.5 -> 7.3.3
- Minor general darwin improvements

@NixOS/darwin-maintainers: I tested this on aarch64-darwin. Could someone give this a test ride on x86_64-darwin?

One question remains:
- What is needed so that the darwin platforms and versions also show up on https://search.nixos.org/packages? How do you handle different versions for darwin vs. linux on https://search.nixos.org/packages? Do I have to give my derivation another `pname`?

Edit: Answered here https://github.com/NixOS/nixos-search/issues/485.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
> However, I am not convinced by your argument: We have always written an update-script in bash, therefore this is the only right way to do that and if there is no api, you should not write an update script because parsing html is fragile and not future proof. 

There are also update scripts and updaters written in perl and python and probably sed and awk script.

I am still with @7c6f434c: update script, yes please but not written in nix that determines the version at eval.

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 175160` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.paperwork-backend</li>
    <li>python310Packages.paperwork-shell</li>
    <li>python39Packages.paperwork-backend</li>
    <li>python39Packages.paperwork-shell</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>libreoffice-bin</li>
  </ul>
</details>

**Comment by tricktron** [comment]
@7c6f434c After the discussion in https://discourse.nixos.org/t/updatescript-written-in-nix-considered-bad-practice-vs-bash/19379/18, are you ok with a comment about impurity at the top of update-utils.nix?

**Comment by 7c6f434c** [comment]
Obviously no, as it is still impure evaluation of `updateScript`

**Comment by tricktron** [comment]
@7c6f434c I finally managed to run the side-effect/impurity at runtime as you proposed. Have a look.

**Comment by 7c6f434c** [comment]
@ofborg build libreoffice-bin libreoffice-bin.updateScript

**Comment by 7c6f434c** [comment]
I am not sure it is optimal to separate update.nix and update-utils.nix but whatever, this construction has a clear maintainer…

As long as all the magic is in the runtime, any working update script beats no update script (and I am realistic enough to expect it will be mostly run by its author anyway, however it is written)

**Pull request merged**
