### PR TITLE
bsp-layout: unstable-2021-05-10 -> unstable-2022-06-19

### PR DESCRIPTION
**Pull request by totoroot**
###### Description of changes

Update package to include recent breaking changes to layout switcher
Add section to release notes fo 22.11

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [x] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by devins2518** [comment]
Don't use bspwm anymore but lgtm, could you remove myself and add yourself to the maintainers list.

**Review by devins2518 — APPROVED** [review]

**Review by Mindavi — APPROVED** [review]
Do make sure to remove the one maintainer :)

**Comment by phenax** [comment]
@totoroot, could you add me as a maintainer?

**Comment by totoroot** [comment]
> Don't use bspwm anymore but lgtm, could you remove myself and add yourself to the maintainers list.

@devins2518 I removed you as a maintainer.

**Comment by totoroot** [comment]
> @totoroot, could you add me as a maintainer?

@phenax First you have to add yourself to nixpkgs [maintainer list](https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix) with a separate PR. Feel free to ping me later, and I'll happily add you as a maintainer in the next PR, as I would like to get this merged now.

**Pull request merged**
