### PR TITLE
nixos/nfs: add idmapd.settings option

### LINKED ISSUE #97616: Add options to configure idmapd.conf
## Issue description

If you want root access to an NFS share secured with Kerberos, you need to modify the default idmapd.conf . Currently, I override the idmapd.conf source, because NixOS has no options to modify idmapd.conf :

```
environment.etc."idmapd.conf".source = let
  nfsStateDir = "/var/lib/nfs";
  rpcMountpoint = "${nfsStateDir}/rpc_pipefs";
in lib.mkForce (pkgs.writeText "idmapd.conf" ''
  [General]
  Pipefs-Directory = ${rpcMountpoint}
  ${lib.optionalString (config.networking.domain != null)
    "Domain = ${config.networking.domain}"}

  [Mapping]
  Nobody-User = nobody
  Nobody-Group = nogroup

  [Translation]
  GSS-Methods = static,nsswitch

  [Static]
  root/hostname.domain.com@REALM.COM = root
'');
```

The text is mostly copied from the default NixOS idmapd.conf . The only changes are

```
-  Method = nsswitch
+  GSS-Methods = static,nsswitch
+
+  [Static]
+  root/hostname.domain.com@REALM.COM = root
```

This solution is brittle, and requires manual intervention if the default idmapd.conf ever changes. I'm not sure exactly what the NixOS options should look like, but there should be mechanisms to modify idmapd.conf in NixOS.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.62, NixOS, 20.03.2882.51d115ac89d (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2882.51d115ac89d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by justinlovinger**
###### Motivation for this change

Fixes #97616

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by aanderse — APPROVED** [review]
@Infinisil do you mind reviewing this too?

**Review by infinisil — APPROVED** [review]
Looking good! Maybe the commits could be squashed together though

**Comment by JustinLovinger** [comment]
@Infinisil I kept the separate commits to give @aanderse proper credit, but I can squash them if you'd prefer and @aanderse is fine with it.

**Comment by aanderse** [comment]
Squash away :+1:

**Comment by JustinLovinger** [comment]
Squash done 👍 @Infinisil

**Comment by Infinisil** [comment]
You can add a `Co-authored-by: ...` field in the commit message to give credit to more people, see https://github.blog/2018-01-29-commit-together-with-co-authors/ :)

**Comment by JustinLovinger** [comment]
@Infinisil Done. I wasn't aware of that option before 🙂

**Comment by aanderse** [comment]
I completely lost track of this... we're good to merge, right?

**Pull request merged**
