### PR TITLE
Revert firmware-linux-nonfree to fix broken Ath10k/QCA9377 wlan adapters [18.09]

### LINKED ISSUE #52644: ath10k WLAN broken on 18.09 between Dec 17 and Dec 21
## Issue description

After updating to 18.09.1777.8c6ab3c72f3 and rebooting into that generation, my wlan adapater is gone.
Symptoms:
# journalctl -b | fgrep ath10k
Linux yuna 4.14.89 #1-NixOS SMP Mon Dec 17 08:28:56 UTC 2018 x86_64 GNU/Linux
Dez 21 22:26:50 yuna kernel: ath10k_pci 0000:05:00.0: enabling device (0000 -> 0002)
Dez 21 22:26:50 yuna kernel: ath10k_pci 0000:05:00.0: pci irq msi oper_irq_mode 2 irq_mode 0 reset_mode 0
Dez 21 22:26:50 yuna kernel: ath10k_pci 0000:05:00.0: Direct firmware load for ath10k/pre-cal-pci-0000:05:00.0.bin failed with error -2
Dez 21 22:26:50 yuna kernel: ath10k_pci 0000:05:00.0: Direct firmware load for ath10k/cal-pci-0000:05:00.0.bin failed with error -2
Dez 21 22:26:50 yuna kernel: ath10k_pci 0000:05:00.0: qca9377 hw1.1 target 0x05020001 chip_id 0x003821ff sub 17aa:0901
Dez 21 22:26:50 yuna kernel: ath10k_pci 0000:05:00.0: kconfig debug 0 debugfs 0 tracing 0 dfs 0 testmode 0
Dez 21 22:26:50 yuna kernel: ath10k_pci 0000:05:00.0: firmware ver WLAN.TF.2.1-00021-QCARMSWP-1 api 6 features wowlan,ignore-otp crc32 42e41877
Dez 21 22:26:53 yuna kernel: ath10k_pci 0000:05:00.0: unable to read from the device
Dez 21 22:26:53 yuna kernel: ath10k_pci 0000:05:00.0: could not execute otp for board id check: -110
Dez 21 22:26:53 yuna kernel: ath10k_pci 0000:05:00.0: failed to get board id from otp: -110
Dez 21 22:26:53 yuna kernel: ath10k_pci 0000:05:00.0: could not probe fw (-110)

Booting back into the old generation yields a different output:
Dez 21 22:24:34 yuna kernel: ath10k_pci 0000:05:00.0: pci irq msi oper_irq_mode 2 irq_mode 0 reset_mode 0
Dez 21 22:24:35 yuna kernel: ath10k_pci 0000:05:00.0: Direct firmware load for ath10k/pre-cal-pci-0000:05:00.0.bin failed with error -2
Dez 21 22:24:35 yuna kernel: ath10k_pci 0000:05:00.0: Direct firmware load for ath10k/cal-pci-0000:05:00.0.bin failed with error -2
Dez 21 22:24:35 yuna kernel: ath10k_pci 0000:05:00.0: Direct firmware load for ath10k/QCA9377/hw1.0/firmware-6.bin failed with error -2
Dez 21 22:24:35 yuna kernel: ath10k_pci 0000:05:00.0: qca9377 hw1.1 target 0x05020001 chip_id 0x003821ff sub 17aa:0901
Dez 21 22:24:35 yuna kernel: ath10k_pci 0000:05:00.0: kconfig debug 0 debugfs 0 tracing 0 dfs 0 testmode 0
Dez 21 22:24:35 yuna kernel: ath10k_pci 0000:05:00.0: firmware ver WLAN.TF.1.0-00002-QCATFSWPZ-5 api 5 features ignore-otp crc32 c3e0d04f
Dez 21 22:24:35 yuna kernel: ath10k_pci 0000:05:00.0: board_file api 2 bmi_id N/A crc32 8aedfa4a
Dez 21 22:24:36 yuna kernel: ath10k_pci 0000:05:00.0: htt-ver 3.44 wmi-op 4 htt-op 3 cal otp max-sta 32 raw 0 hwcrypto 1
Dez 21 22:24:36 yuna kernel: ath10k_pci 0000:05:00.0 wlp5s0: renamed from wlan0

Note the different API version.

### Steps to reproduce

Use affected hardware and update to affected 18.09 version.

## Technical details

I'm testing with the update to firmware-linux-nonfree reverted and will report.

### PR DESCRIPTION
**Pull request by tokudan**
###### Motivation for this change

Fixes #52644 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by badi** [comment]
This would reintroduce #52430

**Comment by Mic92** [comment]
Is there a way to only downgrade your firmware, but keep the other updates?

**Comment by osmano807** [comment]
> Is there a way to only downgrade your firmware, but keep the other updates?

For my QCA9377, I just created a new package derivation [like this](https://gist.github.com/osmano807/8b8e9b37043007c68c4cbfb69ee3e562) with the latest firmware-5.bin. Hacky, but works.

**Comment by tokudan** [comment]
> Is there a way to only downgrade your firmware, but keep the other updates?
I can work around this by keeping a local copy of nixpkgs. But I don't know enough about firmware loading on linux to figure out how to fix this.
Currently a stable version of NixOS broke hardware compatibility, so the responsible commits should be reverted.
If that reintroduces an issue (apparently with amdgpu?) then we need to figure out another solution for that one. From what I've read on #52430 that seems to have been caused by a kernel update, which probably should be reverted, so we can get back to a version that has no software in a completely broken status.

Then we can go about actually fixing the issues as the current state basically means that stable is broken.

**Comment by qolii** [comment]
Hm, what is to be done for this issue? I see that `linux-firmware-nonfree` has been updated several times since this was filed, and is now at 2019-04-16. Does that mean this is fixed?

**Comment by samueldr** [comment]
(triage) as 18.09 is not supported (since a small while), I'm closing this PR.

Though, I didn't look to see if there was a better resolution on the now current stable, or unstable. This issue sure was problematic, and this is the main reason this wasn't merged: introduce a regression for some users, or fix a regression for some :/.

If there is anything to do on current stable or unstable, feel free to open a new PR, though I don't know if there is anything to do.

Thanks again for contributing, though, sorry for not having a resolution for this during the lifetime of 18.09.

**Pull request closed without merging**
