### PR TITLE
clightning: init at 0.6rc1

### PR DESCRIPTION
**Pull request by jb55**
c-lightning is a standard compliant implementation of the Lightning
Network protocol. The Lightning Network is a scalability solution for
Bitcoin, enabling secure and instant transfer of funds between any two
parties for any amount.

###### Motivation for this change

c-lightning is a bit more stable now, figured it was a good time to package

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
tools/generate-wire.py needs to be patched with patchShebangs

**Comment by jb55** [comment]
really weird that I don't get this issue when compiling on master, even with sandbox 🤔

**Comment by jb55** [comment]
@Mic92 fixed

**Comment by jb55** [comment]
closing since 0.6 is released now

**Pull request closed without merging**
