### PR TITLE
Staging next 2021-12-03

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
constitutents: https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
jobset: https://hydra.nixos.org/jobset/nixpkgs/staging-next

Previous staging-next:  #147092

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
nix fails on darwin https://hydra.nixos.org/build/160818008/nixlog/1
Should we revert the update or try to update to a more recent unstable ?

**Comment by happysalada** [comment]
I just tested nix on master and it builds fine with darwin. I think it's just a matter of updating nix to a more recent version.

**Comment by vcunat** [comment]
@happysalada: the changes causing the upgrade most likely come from PR #126411

**Comment by veprbl** [comment]
We might have to define _LIBCPP_DISABLE_AVAILABILITY globally to remove those "introduced in macOS XX.YY" errors

**Comment by veprbl** [comment]
- [ ] https://hydra.nixos.org/job/nixpkgs/staging-next/libepoxy.x86_64-darwin

**Comment by veprbl** [comment]
Strangely libepoxy tests pass for me, but only if I don't use sandbox, which should be the case on Hydra. Can anyone reproduce?

**Comment by happysalada** [comment]
Also passes on my machine ? Maybe just a flaky test ? Perhaps we can try to disable the test ? Or retry the build ?

**Comment by veprbl** [comment]
The https://github.com/anholt/libepoxy/blob/1.5.9/test/cgl_epoxy_api.c doesn't look like such an important test. Disabled it the only way I knew (https://github.com/mesonbuild/meson/issues/6999).

**Comment by veprbl** [comment]
- [ ] https://hydra.nixos.org/job/nixpkgs/staging-next/jemalloc.x86_64-darwin https://github.com/jemalloc/jemalloc/issues/2091

**Comment by veprbl** [comment]
- https://hydra.nixos.org/job/nixpkgs/staging-next/libsForQt512.qtbase.x86_64-darwin builds fine
- [ ] https://hydra.nixos.org/job/nixpkgs/staging-next/libsForQt514.qtbase.x86_64-darwin
- [ ] https://hydra.nixos.org/job/nixpkgs/staging-next/libsForQt515.qtbase.x86_64-darwin

**Comment by vcunat** [comment]
I'm afraid I still see quite a lot of regressions (closing a thousand): https://hydra.nixos.org/eval/1731037?compare=1730968

On a quick glance into some sample of new errors, I saw boost relatively often.

**Comment by vcunat** [comment]
@domenkozar: FYI, I see cachix regressing here on `*-darwin`: https://hydra.nixos.org/job/nixpkgs/staging-next/cachix.x86_64-darwin

**Comment by veprbl** [comment]
`cachix` should be fixed now

**Comment by veprbl** [comment]
I'm now convinced that some machines on Hydra have sandboxing enabled. First we had to fix https://hydra.nixos.org/build/161099051 and now https://hydra.nixos.org/build/161746079.

**Comment by veprbl** [comment]
An issue with the build of mono6 https://hydra.nixos.org/build/161743572
```
Unhandled Exception:
System.IO.IOException: Disk full. Path /private/tmp/nix-build-mono-6.12.0.122.drv-0/mono-6.12.0.122/mcs/docs/netdocs.zip
  at System.IO.FileStream.Dispose (System.Boolean disposing) [0x000cb] in <b9a1c3dbecdb471d9e343f3992f640ab>:0 
  at System.IO.FileStream.Finalize () [0x00000] in <b9a1c3dbecdb471d9e343f3992f640ab>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.IOException: Disk full. Path /private/tmp/nix-build-mono-6.12.0.122.drv-0/mono-6.12.0.122/mcs/docs/netdocs.zip
  at System.IO.FileStream.Dispose (System.Boolean disposing) [0x000cb] in <b9a1c3dbecdb471d9e343f3992f640ab>:0 
  at System.IO.FileStream.Finalize () [0x00000] in <b9a1c3dbecdb471d9e343f3992f640ab>:0 
```

**Comment by vcunat** [comment]
It says "disk full", so that's probably a transient error.

**Comment by veprbl** [comment]
- [ ] https://hydra.nixos.org/job/nixpkgs/staging-next/perl534Packages.GD.x86_64-linux https://hydra.nixos.org/job/nixpkgs/staging-next/perl534Packages.GD.x86_64-darwin

**Comment by veprbl** [comment]
Three regressions with
```
error: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if TARGET_OS_MAC
```
- https://hydra.nixos.org/job/nixpkgs/staging-next/cdk-go.x86_64-darwin
- https://hydra.nixos.org/job/nixpkgs/staging-next/gotop.x86_64-darwin
- https://hydra.nixos.org/job/nixpkgs/staging-next/packer.x86_64-darwin

@toonn, you've touched Libsystem in 84454c32332e39bc84bab576e00c62ac88b3dbe3, could that be relevant?

**Comment by toonn** [comment]
@veprbl, not that particular commit. It only adds two definitions. I think the problem is the LLVM bump. LLVM 11 made this an error. It usually means they neglected to include the `TargetConditionals.h` header.

**Comment by veprbl** [comment]
- [ ] https://hydra.nixos.org/job/nixpkgs/staging-next/perl532Packages.DBIxClass.x86_64-linux https://hydra.nixos.org/job/nixpkgs/staging-next/perl532Packages.DBIxClass.x86_64-darwin

**Comment by vcunat** [comment]
OK, let's not "delay" anymore.  It's relatively common that quite a few regressions remain.  The main point is to get rid of the worst ones before hitting master, and getting most of binaries in advance.

**Comment by bobrik** [comment]
Things look pretty bleak on aarch64-darwin:

image

**Comment by veprbl** [comment]
Seems like the cffi tests were re-enabled in 54b5495e4e632aa5797b04509acc93baf8800580, this seems to cause some python regressions

**Comment by bobrik** [comment]
Here's a possible fix: https://github.com/NixOS/nixpkgs/pull/152166

**Comment by vcunat** [comment]
Eww, I forgot to check the platform, focusing on comparison to `trunk` where it's missing.

**Comment by veprbl** [comment]
I thought staging-next jobs for aarch64-darwin were stuck scheduled, so there was no way to see the failure

**Pull request merged**
