### PR TITLE
lightdm: 1.30.0 -> 1.32.0, lightdm-gtk-greeter: 2.0.7 -> 2.0.8

### PR DESCRIPTION
**Pull request by bobby285271**
###### Description of changes

https://github.com/canonical/lightdm/compare/1.30.0...1.32.0
https://github.com/Xubuntu/lightdm-gtk-greeter/compare/lightdm-gtk-greeter-2.0.7...lightdm-gtk-greeter-2.0.8

/cc @ajs124 I cherry-picked https://github.com/NixOS/nixpkgs/pull/174634/commits/197d1ca99297626011883ce9e09d837dddeb9654 from #174634 as there is no qt4 support in lightdm 1.32.0: https://github.com/canonical/lightdm/commit/e847a5d30780d010bfb776378dea51789efc26df

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg test pantheon
@ofborg test lightdm

**Review by ajs124 — APPROVED** [review]
diff LGTM and test still runs, but could probably use more testing

**Review by romildo — APPROVED** [review]
LGTM. Running it now in my notebook.

**Review by SuperSandro2000 — APPROVED** [review]
Please consider adding yourself as maintainer

**Comment by bobby285271** [comment]
> Please consider adding yourself as maintainer

Done.

@ofborg test pantheon
@ofborg test xfce
@ofborg test lightdm
@ofborg build lightdm_qt lightdm-mini-greeter lightdm-tiny-greeter lightdm-enso-os-greeter

**Pull request merged**
