### PR TITLE
vim_configurable: support managing plugins in "vim packages"

### PR DESCRIPTION
**Pull request by nicknovitski**
Commit message:
> Version 8 of vim adds the concept of "vim packages": subdirectories of
any directory listed in vim's "packpath" option, containing one or more
vim plugins. Vim will automatically load plugins placed in a package's
"start" subdirectory, while those placed in an "opt" subdirectory can be
loaded manually.
>
> Correspondingly, vimrcConfig's packPath option accepts a set with
"start" and/or "opt" attributes containing lists of nix packages, which
are then combined into a vim package, which is then added to vim's
packpath.

I just tried to find the simplest thing that would work.  Feedback welcome.
  
###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by nicknovitski** [comment]
I admit that I don't understand the ci error.  The OS X build timed out after successfully building the test derivations?

**Comment by benley** [comment]
That CI error looks like it's probably bogus and can be ignored.

**Comment by nicknovitski** [comment]
Corrected a typo in the documentation comment.

**Comment by nicknovitski** [comment]
Ah, I just remembered `doc/language_frameworks/vim.md`.  To be honest, I never fully understood it.  Will leaving it as-is block this PR?

**Comment by jagajaga** [comment]
👍

**Comment by nicknovitski** [comment]
In vim terms, what I've written creates a single package named 'nix'.  Another possible api would expose the concept of multiple packages with arbitrary names.  I don't know what people would use that for, but it could look like this instead:
```nix
vim_configurable.customize {
  vimrcConfig.packages.nixOrWhateverOtherNameYoudLike = with vimPlugins; {
    start = [ youcompleteme ];
    opt = [ elm-vim ];
  };
```

I didn't like the idea of forcing people to come up with package names when they don't seem to matter; once vim is running, packages seem to be transparent, with all of their plugins made available the same way.

Maybe `package` is a better attribute name than `packPath` though...

**Comment by jagajaga** [comment]
@nicknovitski sorry, I've reread you message 3 times and can't understand what do you want to say.

**Comment by nicknovitski** [comment]
Forgive me, I'll try to explain myself clearly.

Currently my patch adds a `packPath` argument to `vimrcConfig`. Using that argument creates a nix package which contains a single _vim package_ named `nix`.

I asked two questions.

---
First, should the API expose or hide the name of the _vim package_?

Currently it's hidden:
```
vimrcConfig.packPath.start = [ vimplugin1 vimplugin2 ];
```

By exposing it, users would be able to create _multiple vim packages_, but they would _have to name all of them_:
```
vimrcConfig.packPath.vimPackage1.start = [ vimPlugin1 ];
vimrcConfig.packPath.vimPackage2.start = [ vimPlugin2 ];
```

---
Second, should the argument name be `package` or `packages`, instead of `packPath`?

```
vimrcConfig.package.start = myVimPlugins;
# OR
vimrcConfig.packages.vimPackage1.start = myVimPlugins;
```

**Comment by nicknovitski** [comment]
I've change my patch to use the more explicit approach, and to use `packages` instead of `packPath`, like so:

```
vimrcConfig.packages {
  myVimPackage = with vimPlugins; {
    start = [ youcompleteme ];
    opt = [ elm-vim ];
  };
};
```

**Comment by Mic92** [comment]
@nicknovitski Do you see a use case for multiple packages rather then having a single package called `nix` like your first implementation?

**Review by Mic92 — APPROVED** [review]
Works for me. There only two little typos in the code

**Pull request merged**
