### PR TITLE
jetbrains.*: 2019.1.3 -> 2019.2 (mostly); jetbrainsjdk: 11.0.2b164 -> 11.0.3b360.2

### PR DESCRIPTION
**Pull request by jirkadanek**
###### Motivation for this change
New major release of the IDE suite. I [had issue](https://youtrack.jetbrains.com/issue/JBR-1256) with the older jdk, so I upgraded that also, which resolved it.

###### Things done

I've tested idea-ultimate, clion, and rider, I do not use the other IDEs.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jdanekrh** [comment]
So, compiling jetbrains.webstorm fails, others succeed

```
builder for '/nix/store/b1vwv58y4x4f80b616b8yn27jx21nj5x-webstorm-2019.2.drv' failed with exit code 1; last 6 log lines:
  unpacking sources
  unpacking source archive /nix/store/hb4ljqxfps1cgwj4shwrla3w9y7agwg0-WebStorm-2019.2.tar.gz
  source root is WebStorm-192.5728.87
  setting SOURCE_DATE_EPOCH to timestamp 1563790706 of file WebStorm-192.5728.87/product-info.json
  patching sources
  rm: cannot remove 'jre64': No such file or directory
```

**Comment by jdanekrh** [comment]
jetbrains.webstorm now builds and starts as well

**Comment by averelld** [comment]
GoLand was updated to 2019.2 meanwhile too.

**Review by angristan — APPROVED** [review]
Tested with `nix-review`. Everything builds and each IDE starts correctly. :heavy_check_mark:

**Comment by jdanekrh** [comment]
Updates for datagrip and ruby-mine which were meanwhile released are in #65837. As a further improvement for another PR, I am thinking of removing the jbr directory from all jetbrains tools, not just webstorm. It will save ~130 MB for each package where it is now uselessly present.

**Comment by jdanekrh** [comment]
Rider 2019.2 is in https://github.com/NixOS/nixpkgs/pull/66426

**Comment by c0bw3b** [comment]
Obsolete, there is now newer versions in nixpkgs

**Pull request closed without merging**
