### PR TITLE
libtoxcore: 0.2.13 -> 0.2.17

### PR DESCRIPTION
**Pull request by alexbakker**
###### Description of changes

We're lagging behind a bit on toxcore releases. Latest changelog: https://github.com/TokTok/c-toxcore/releases/tag/v0.2.17.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
On nixos x86_64:

```builder for '/nix/store/0qqrw8h5d6rcfnpx0d6kf8ayxhq1pim8-tuntox-0.0.10.drv' failed with exit code 2; last 10 log lines:
  /nix/store/x2zbyl2l4xayv4d5is0b31plfq8xjjym-binutils-2.35.2/bin/ld: /build/source/client.c:438: undefined reference to `tox_friend_send_lossless_packet'
  /nix/store/x2zbyl2l4xayv4d5is0b31plfq8xjjym-binutils-2.35.2/bin/ld: /build/source/client.c:351: undefined reference to `tox_friend_add'
  /nix/store/x2zbyl2l4xayv4d5is0b31plfq8xjjym-binutils-2.35.2/bin/ld: /build/source/client.c:376: undefined reference to `tox_friend_get_connection_status'
  /nix/store/x2zbyl2l4xayv4d5is0b31plfq8xjjym-binutils-2.35.2/bin/ld: /build/source/client.c:399: undefined reference to `tox_friend_delete'
  /nix/store/x2zbyl2l4xayv4d5is0b31plfq8xjjym-binutils-2.35.2/bin/ld: gitversion.o: in function `print_version':
  /build/source/gitversion.c:8: undefined reference to `tox_version_patch'
  /nix/store/x2zbyl2l4xayv4d5is0b31plfq8xjjym-binutils-2.35.2/bin/ld: /build/source/gitversion.c:8: undefined reference to `tox_version_minor'
  /nix/store/x2zbyl2l4xayv4d5is0b31plfq8xjjym-binutils-2.35.2/bin/ld: /build/source/gitversion.c:8: undefined reference to `tox_version_major'
  collect2: error: ld returned 1 exit status
  make: *** [Makefile:35: tuntox] Error 1
```

**Comment by risicle** [comment]
`nixpkgs-review` reveals no new failures on macos 10.15 though

**Comment by alexbakker** [comment]
@risicle I've applied a small patch to tuntox to fix the build. I missed that, thanks.

**Comment by willcohen** [comment]
`tuntox` continues to work with this update!

**Review by willcohen — APPROVED** [review]

**Review by risicle — APPROVED** [review]
WFM now

**Pull request merged**
