### PR TITLE
gnunet: 0.14.0 -> 0.14.1; gnunet-gtk 0.13.1 -> 0.14.0

### LINKED ISSUE #115112: gnunet-gtk fail to build
**Describe the bug**
```
[davidak@gaming:~]$ nix run nixpkgs.gnunet-gtk -c gnunet-gtk
builder for '/nix/store/w1a305jwbbnn2h723w0hwl1xlflhg2w9-gnunet-gtk-0.13.1.drv' failed with exit code 1; last 10 log lines:
  checking gnutls/abstract.h presence... yes
  checking for gnutls/abstract.h... yes
  checking for gnutls_pubkey_import in -lgnutls... yes
  checking for GNUnet core... --with-gnunet not specified
  checking for gnunetutil >= 0.9.0... yes
  checking GNUNET_CFLAGS... -I/nix/store/aawda90f2iv5x0dxp3ag74i37bclwc80-gnunet-0.14.0/include
  checking GNUNET_LIBS... -L/nix/store/aawda90f2iv5x0dxp3ag74i37bclwc80-gnunet-0.14.0/lib -lgnunetutil
  checking for gnunet/gnunet_conversation_service.h... no
  checking for gnunet/gnunet_fs_service.h... no
  configure: error: compiling gnunet-gtk requires GNUnet core headers
[0 built (1 failed), 6 copied (33.3 MiB), 9.2 MiB DL]
error: build of '/nix/store/w1a305jwbbnn2h723w0hwl1xlflhg2w9-gnunet-gtk-0.13.1.drv' failed
```

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**
@pstn and @jonringer edited it last

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.1, NixOS, 21.05pre273435.0aeba64fb26 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"home-manager-20.09, nixos-21.05pre273435.0aeba64fb26, nixos-hardware, nixos-unstable-21.05pre273435.0aeba64fb26"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by fricklerhandwerk**
###### Motivation for this change
Otherwise `gnunet-setup` will not pick up plugins. See:
https://git.gnunet.org/gnunet-gtk.git/tree/README?id=5034ca084258d6653b2986b00167c736a9cd93ed#n19

Fixes https://github.com/NixOS/nixpkgs/issues/115112

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pstn** [comment]
Sorry for ignoring this. I wasn't pinged, somehow. I'll have a look at it this weekend.

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 110606` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>gnunet-gtk</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
ping @fricklerhandwerk

**Comment by fricklerhandwerk** [comment]
Yep, I’m alive and remember, haven’t gotten to it yet, sorry.

**Comment by fricklerhandwerk** [comment]
@SuperSandro2000 @davidak Weird, I cannot reproduce with `nixpkgs-review`. Was already surprized there was a failure at all, because it built and ran locally in sandbox mode.

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 110606` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>gnunet-gtk</li>
  </ul>
</details>

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 110606` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by davidak** [comment]
@fricklerhandwerk the PR didn't change since january, but master did. So that might be the reason why it fails now.

Can you rebase and test again?

**Comment by fricklerhandwerk** [comment]
`gnunet` upstream seems to have added a dependency to `libsodium`, therefore configure check failed - it tried to compile the header.

**Comment by fricklerhandwerk** [comment]
@davidak @SuperSandro2000 All good now?

**Comment by SuperSandro2000** [comment]
```
_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
       > checking for gnutls... --with-gnutls not specified
       > checking gnutls/abstract.h usability... yes
       > checking gnutls/abstract.h presence... yes
       > checking for gnutls/abstract.h... yes
       > checking for gnutls_pubkey_import in -lgnutls... yes
       > checking for GNUnet core... /nix/store/7nccbpwifxivnjvd26p5p1i1rky92zdf-gnunet-0.14.0
       > checking for GNUnet util library in /nix/store/gal466zyk6zxlrv7c3jwmj5p504dj72v-gnunet-gtk-0.13.1... checking for gnunet/gnunet_util_lib.h... no
       > checking for gnunet/gnunet_conversation_service.h... no
       > configure: error: gnunet-gtk requires GNUnet
       For full logs, run 'nix log /nix/store/0xm6h4jb6jv3hwchchrab9hbc0ac1wgc-gnunet-gtk-0.13.1.drv'.
```

**Comment by fricklerhandwerk** [comment]
Oh my, this is so embarrassing. Sorry for wasting your time. What the hell, where did my force-pushed change go? It even disappeared from my development machine, nothing in `git reflog` either, only the updated commit message is correct. Please check again, for me `nixpkgs-review pr 110606` was successful.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110606` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>gnunet</li>
<li>gnunet-gtk</li>
</ul>
</details>

**Review by SuperSandro2000 — COMMENTED** [review]
```
gnunet: Ask if output path include (1.6M) could be split with outputs = [ ... "dev" ];
gnunet: Ask if output path lib (7.5M) could be split with outputs = [ ... "lib" ];
gnunet: Ask if output path share/info (2.1M) could be split with outputs = [ ... "info" ];
```

**Comment by fricklerhandwerk** [comment]
@SuperSandro2000 I'll note to do it first thing next time I touch this. Right now I would like this to get merged, as refactoring will be more work for everyone without much immediate benefit.

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 110606` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>gnunet</li>
    <li>gnunet-gtk</li>
  </ul>
</details>

**Review by davidak — APPROVED** [review]
Thanks for updating and fixing it!

Builds and binaries seem to work (i will create separate issues for minor issues)

**Pull request merged**
