### PR TITLE
jetbrains.jcef: 654 -> 672

### PR DESCRIPTION
**Pull request by niknetniko**
###### Description of changes

Bumps JetBrain's JCEF fork to work properly with the updated IDEs from #245566.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by niknetniko** [comment]
> However, when I try to run idea-ultimate (from result/bin), I can't open markdown files. See attached Stracktrace

Ah, it appears you also need version 2023.2 for this to work, so you also need #245566. I'll put this in draft until that PR is merged and then rebase this.

**Comment by niknetniko** [comment]
> @niknetniko #245566 was merged

I have rebased; it should work now (or at least does for me).

**Review by x418 — APPROVED** [review]
Result of `nixpkgs-review pr 245717` 

```shell
19 packages built:
greenfoot jetbrains.clion jetbrains.datagrip jetbrains.dataspell jetbrains.gateway jetbrains.goland jetbrains.idea-community jetbrains.idea-ultimate jetbrains.jcef jetbrains.jcef.unpacked jetbrains.jdk jetbrains.jdk.debug jetbrains.mps jetbrains.phpstorm jetbrains.pycharm-community jetbrains.pycharm-professional jetbrains.rider jetbrains.ruby-mine jetbrains.webstorm
```

And can confirm that the errors are gone and Markdown preview works again. Thanks @niknetniko

**Review by fabianhjr — APPROVED** [review]
Works

**Comment by GenericNerdyUsername** [comment]
Should this go with a `jetbrains.jdk` update as well? The newer builds need another file from `jetbrains.jcef`, so preventing a double rebuild would be nice

**Review by SebTM — APPROVED** [review]

**Comment by SebTM** [comment]
Works fine for me, +1 for @GenericNerdyUsername if possible but already 2023.2 in the pipeline (#247219)

**Comment by GenericNerdyUsername** [comment]
The changes necessary for `jetbrains.jcef` are [here](https://gitlab.com/genericnerdyusername/jetbrains-updater/-/commit/172acc5b5adba73cbcd38f8d628386fe8e34f4f2) on line 204 to 220, and the changes for `jetbrains.jdk` are [here](https://gitlab.com/genericnerdyusername/jetbrains-updater/-/commit/a2849b11e85c6d7a2bfefe9a47c6d48397ac78ed)

**Comment by niknetniko** [comment]
> The changes necessary for `jetbrains.jcef` are [here](https://gitlab.com/genericnerdyusername/jetbrains-updater/-/commit/172acc5b5adba73cbcd38f8d628386fe8e34f4f2) on line 204 to 220, and the changes for `jetbrains.jdk` are [here](https://gitlab.com/genericnerdyusername/jetbrains-updater/-/commit/a2849b11e85c6d7a2bfefe9a47c6d48397ac78ed)

If you want to make a PR, I will happily close this one in favour of the new one; otherwise I can add those changes here at some point.

**Comment by NickCao** [comment]
Just merged https://github.com/NixOS/nixpkgs/pull/247219 so all ides are now on 2023.2, shall we push this forward? And while you are at it please take a look at https://github.com/NixOS/nixpkgs/pull/243053

**Comment by sequencer** [comment]
This PR is required for new JetBrains IDES:
```
2023-08-17 10:24:29,110 [   7735]   WARN - #c.i.u.j.JBCefApp - JCEF: minimum supported API version is 1.12, current is 1.10 (Use JBR bundled with the IDE)
```

**Pull request merged**
