### PR TITLE
ddnet: 16.5 -> 16.7.2

### PR DESCRIPTION
**Pull request by ncfavier**
Adds a build dependency on Rust.

Also enable the tests and add me as maintainer.

Let's see if it's still broken on darwin. EDIT: if so, I'll try applying [ddnet/ddnet@`97b9349` (#5913)](https://github.com/ddnet/ddnet/pull/5913/commits/97b9349e9b3ecd7263ed3abd6f58fe52c9f9b05d)

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ncfavier** [comment]
cc @atemp

**Comment by atemp** [comment]
very nice, pr works for me

this package really needs an active maintainer!

**Comment by ncfavier** [comment]
Darwin [fails](https://logs.nix.ci/?key=nixos/nixpkgs.212735&attempt_id=076e8992-b227-485c-a80a-5bfa14cf6c3f), let's see if https://github.com/ddnet/ddnet/pull/5913 fixes it.

**Comment by ncfavier** [comment]
Still [fails](https://logs.nix.ci/?key=nixos/nixpkgs.212735&attempt_id=43fea3c0-e6c9-4434-b3ce-64006378b674) with the patch.

**Comment by ncfavier** [comment]
@NixOS/darwin-maintainers (I hope it's okay to ping, AFAICT that's what this team is for)

I need help figuring out what's going on with the x86_64-darwin build of `ddnet`. See https://github.com/ddnet/ddnet/pull/5913 for context.

Why is `pthread_attr_set_qos_class_np` undefined in the ofborg builder? It's supposed to be [available](https://github.com/ddnet/ddnet/pull/5913#issuecomment-1404851577) starting with mac 10.10, and [this log](https://logs.nix.ci/?key=nixos/nixpkgs.212735&attempt_id=c5e1036c-a697-47fb-ac33-2f2821e3ca41) shows that `MAC_OS_X_VERSION_MIN_REQUIRED` is set to 101300. Is that the actual version the builder runs on? How should we check this properly?

**Comment by stephank** [comment]
I had to do the following:

```diff
--- a/src/base/system.cpp
+++ b/src/base/system.cpp
@@ -38,6 +38,9 @@
 #include <netdb.h>
 #include <netinet/in.h>
 #include <pthread.h>
+#if defined(CONF_PLATFORM_MACOS)
+#include <pthread/qos.h>
+#endif
 #include <sys/ioctl.h>
 #include <sys/socket.h>
 
```

But I don't think that should be necessary? Maybe there's something funny going on with our `<pthread.h>`.

**Review by wegank — APPROVED** [review]

**Review by stephank — APPROVED** [review]
`nixpkgs-review pr 212735` doesn't want to build anything, but tested again manually and builds fine on `x86_64-darwin` now.

**Comment by atemp** [comment]
it seems that this update https://github.com/NixOS/nixpkgs/pull/212229 broke this version of DDNet for me, but when manually adding this https://github.com/NixOS/nixpkgs/pull/216391 it works again

the problem seems to be related to this: https://github.com/ddnet/ddnet/issues/6157

**Pull request merged**
