### PR TITLE
dump1090: 4.0 -> 5.0

### PR DESCRIPTION
**Pull request by earldouglas**
###### Motivation for this change

Update dump1090 to the latest version.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 121442` at a64f3631 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>dump1090</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/applications/radio/dump1090/default.nix:30:3:
```
   |
30 |   installPhase = ''
   |   ^
```
</li>
  </ul>
</details>

**Review by danieldk — APPROVED** [review]
LGTM, thanks!

Result of `nixpkgs-review pr 121442` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>dump1090</li>
  </ul>
</details>

**Comment by danieldk** [comment]
Missed something, the commit message

```
Add recommended runHook pre/postInstall
```

Shoul be formatted as follows:

```
dump1090: add recommended runHook pre/postInstall
```

Too late for this time...

**Comment by earldouglas** [comment]
Oops; I mistakenly expected the commits to be squashed, and the comments to be merged.  I'll stick to the format for follow-on commits going forward.

**Pull request merged**
