### PR TITLE
mint: 0.5.0 -> 0.7.1

### PR DESCRIPTION
**Pull request by Br1ght0ne**
###### Motivation for this change
https://github.com/mint-lang/mint/releases/tag/0.7.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @manveru

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/74921)

### CODE REVIEW

**Comment by filalex77** [comment]
@GrahamcOfBorg build mint

**Review by manveru — APPROVED** [review]

**Comment by manveru** [comment]
Seems to have issues on darwin, but I have no way to debug those.

**Comment by manveru** [comment]
Also this will fail once https://github.com/NixOS/nixpkgs/pull/75545 is merged. Please specify the crystal version as  `crystal_0_31` to prevent that.

**Comment by filalex77** [comment]
@manveru No need - seems that Mint maintainers are quickly updating the code to keep up with the latest stable release of Crystal.

As soon as Crystal 0.32 is merged, I can rebase this PR to check if it builds. But for now:
@GrahamcOfBorg build mint

**Comment by manveru** [comment]
I asked the maintainer for a fix, so there's https://github.com/mint-lang/mint/releases/tag/0.7.1 now

**Comment by filalex77** [comment]
Handled by #80391.

**Pull request closed without merging**
