### PR TITLE
google-chrome: fix makeWrapper invocation

### LINKED ISSUE #339729: Build failure: google-chrome
### Steps To Reproduce

1. build (add) google-chrome from nixpkgs/master (the exact commit with problem from this issue #338703)

### Build log

```
error: builder for '/nix/store/9vvzl5mzdws2brrk33scr88vmc45yb7b-google-chrome-128.0.6613.113.drv' failed with exit code 1;
       last 18 log lines:
       > Running phase: unpackPhase
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > no configure script, doing nothing
       > Running phase: buildPhase
       > no Makefile or custom buildPhase, doing nothing
       > Running phase: glibPreInstallPhase
       > Running phase: installPhase
       >
       > Builder called die: makeWrapper doesn't understand the arg --simulate-outdated-no-au=Tue, 31 Dec 2099 23:59:59 GMT
       > Backtrace:
       > 185 makeShellWrapper /nix/store/y2hsygxffx6rswk0l7ycppigqcpdl0lp-make-shell-wrapper-hook/nix-support/setup-hook
       > 37 makeWrapper /nix/store/y2hsygxffx6rswk0l7ycppigqcpdl0lp-make-shell-wrapper-hook/nix-support/setup-hook
       > 1743 runPhase /nix/store/ffr5qkpiyl0bdz15w1b8hmqnclw6938h-stdenv-linux/setup
       > 1749 genericBuild /nix/store/ffr5qkpiyl0bdz15w1b8hmqnclw6938h-stdenv-linux/setup
       > 4 main /nix/store/v6x3cs394jgqfbi0a42pam708flxaphh-default-builder.sh
       >
       For full logs, run 'nix log /nix/store/9vvzl5mzdws2brrk33scr88vmc45yb7b-google-chrome-128.0.6613.113.drv'.
```
```
❯ nix log /nix/store/9vvzl5mzdws2brrk33scr88vmc45yb7b-google-chrome-128.0.6613.113.drv
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/9vvzl5mzdws2brrk33scr88vmc45yb7b-google-chrome-128.0.6613.113.drv^*'
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
no configure script, doing nothing
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
no Makefile or custom buildPhase, doing nothing
Running phase: glibPreInstallPhase
@nix { "action": "setPhase", "phase": "glibPreInstallPhase" }
Running phase: installPhase
@nix { "action": "setPhase", "phase": "installPhase" }

Builder called die: makeWrapper doesn't understand the arg --simulate-outdated-no-au=Tue, 31 Dec 2099 23:59:59 GMT
Backtrace:
185 makeShellWrapper /nix/store/y2hsygxffx6rswk0l7ycppigqcpdl0lp-make-shell-wrapper-hook/nix-support/setup-hook
37 makeWrapper /nix/store/y2hsygxffx6rswk0l7ycppigqcpdl0lp-make-shell-wrapper-hook/nix-support/setup-hook
1743 runPhase /nix/store/ffr5qkpiyl0bdz15w1b8hmqnclw6938h-stdenv-linux/setup
1749 genericBuild /nix/store/ffr5qkpiyl0bdz15w1b8hmqnclw6938h-stdenv-linux/setup
4 main /nix/store/v6x3cs394jgqfbi0a42pam708flxaphh-default-builder.sh
```

### Notify maintainers

@jnsgruk @johnrtitor @fzakaria

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.7, NixOS, 24.11 (Vicuna), 24.11.20240905.4a6b938`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.4`
 - channels(root): `""`
 - nixpkgs: `/nix/store/5s3fwih59zg3sirmx6xz37zdha9m0r60-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by jnsgruk**
## Description of changes

Fixes #339729

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jnsgruk** [comment]
Result of `nixpkgs-review pr 339734` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>google-chrome</li>
    <li>netflix</li>
  </ul>
</details>

**Comment by jnsgruk** [comment]
Merging, as this package is currently broken, and this is just a simplification of what was already agreed.

**Comment by JohnRTitor** [comment]
Weirdly, even though I built the package locally as far as I could remember. Thanks for the quick fix Jon.

**Comment by fzakaria** [comment]
@JohnRTitor i had the same issue when I tried; i had to add weird quoting to fix it but it wasn't sure if the final command line arg is what i wanted.

I think this is simpler in the long run.

**Pull request merged**
