### PR TITLE
nixos.sway: add a package option

### PR DESCRIPTION
**Pull request by nrdxp**
###### Description of changes

This should be a starting point to allow for home-manager configured sway to interact with NixOS. More work may be needed

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by primeos — CHANGES_REQUESTED** [review]
I think we should spend more thoughts on this before we merge a suboptimal solution (it doesn't have to be perfect but it should be good enough).
We used to intentionally omit the `package` option as it was discouraged in the past but IIRC it's considered fine now. However, so far a `package` option wasn't needed. But IIRC someone else also wanted one to bypass the Sway wrapper (which would be a bit difficult with the way this is currently implemented).

I also think this shouldn't be required for home-manager. I once attempted to resolve some issues with them but IIRC all of my suggestions have been ignored.

Anyway, I had a very brief look at https://discourse.nixos.org/t/sway-nixos-home-manager-conflict/20760:
> If I keep it, the nixos package overrides my sway-wm package overrides in home-manager.
I’m running home-manager in standalone mode.

Doesn't home-manager use `$PATH`? If so the directory with the home-manager binaries should simply come before the Nix(OS) binaries - at least that would seem natural to me...

However, that comment also mentions GDM, which could certainly be an issues (but display managers like GDM are basically unsupported anyway (by Sway upstream and us) as they cause lots of unnecessary issues).
Edit: But `share/wayland-sessions/sway.desktop` already LGTM as well:
```
[Desktop Entry]
Name=Sway
Comment=An i3-compatible Wayland compositor
Exec=sway
Type=Application
```

**Comment by nrdxp** [comment]
I think a package option is generally a good thing for most options. Perhaps we could set `internal = true` to leave it undocumented, seems be that way in some other modules, although I don't think there is any particular rule for it.

In any case, I don't actually use sway personally, but perhaps some addition options could be added to modify the wrapper further, like extra options to pass to the override or a flag to disable it outright?

**Comment by oxalica** [comment]
I also wants this.
Currently we cannot correctly reference the path of `swaymsg` which lies inside `sway` package. Using `pkgs.sway` would introduce two sway derivation which is also suboptimal (unless I applies the same special default overrides to it). There are some where relying `PATH` is not feasible or not good idea, like in config files or scripts.

**Comment by edrex** [comment]
A `programs.sway.package` option was added in https://github.com/NixOS/nixpkgs/pull/213482

**Comment by primeos** [comment]
Thanks a lot for your comment @edrex! - I wasn't even aware of that other PR yet.
The other PR should have considered this PR but at least it was quite a good implementation. Let's close this PR then.

Thanks for giving this a try @nrdxp (although it got me a bit confused that you don't actually use Sway :o :D).

**Comment by nrdxp** [comment]
> although it got me a bit confused that you don't actually use Sway

It was a while ago now, but someone, somewhere was having issues integrating home-manager due to the lack of this flag and I was just trying to help out. I also did use sway for a good while, and I still have a config for it, I just switched to [vivarium](https://github.com/inclement/vivarium) a while back.

Anyway, glad its been resolved.

**Pull request closed without merging**
