### PR TITLE
deno: 1.11.3 -> 1.11.4 -> 1.11.5

### PR DESCRIPTION
**Pull request by 06kellyjac**
###### Motivation for this change

**Note:** ~Waiting for 37ac6d6e760d60d3a99eff4637398c407c68cfe8 to hit master~
37ac6d6e760d60d3a99eff4637398c407c68cfe8 has now hit master

Bump deno to ~`1.11.4`~ `1.11.5`

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
Fails for me with the following error:

```
deno>    Compiling swc_ecma_transforms_react v0.25.0
deno> error[E0658]: or-patterns syntax is experimental
deno>     --> /build/deno-1.11.4-vendor.tar.gz/swc_ecma_transforms_optimization/src/simplify/expr/mod.rs:1347:34
deno>      |
deno> 1347 | ...                   Some(Expr::Lit(..) | Expr::Ident(..)) => {}
deno>      |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
deno>      |
deno>      = note: see issue #54883 <https://github.com/rust-lang/rust/issues/54883> for more information
deno>    Compiling swc_ecma_transforms_proposal v0.24.0
deno> error: aborting due to previous error
deno> For more information about this error, try `rustc --explain E0658`.
deno> error: could not compile `swc_ecma_transforms_optimization`
deno> To learn more, run the command again with --verbose.
deno> warning: build failed, waiting for other jobs to finish...
deno> error: build failed
error: build of '/nix/store/gnysslf3nqpcs8gcf0dwzbicclia7srl-deno-1.11.4.drv' on 'ssh-ng://builder-ng' failed: error: builder for '/nix/store/gnysslf3nqpcs8gcf0dwzbicclia7srl-deno-1.11.4.drv' failed with exit code 101
error: builder for '/nix/store/gnysslf3nqpcs8gcf0dwzbicclia7srl-deno-1.11.4.drv' failed with exit code 1
```

**Comment by cole-h** [comment]
@ofborg eval

(Sorry, ofborg's certs recently had an issue, meaning that it was unable to
react to PRs. This has been fixed, but all PRs filed in this period will need
ofborg to be manually kicked off.)

**Comment by 06kellyjac** [comment]
Ok I had some time to finally look into this and it needs rust 1.53.0 but nixpkgs is on [1.52.1](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/rust/1_52.nix)

**Comment by 06kellyjac** [comment]
1.53 is now in master, running a review

**Comment by 06kellyjac** [comment]
Result of `nixpkgs-review pr 128945` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>deno</li>
  </ul>
</details>

**Pull request merged**
