### PR TITLE
[20.03] nextcloud: 18.0.0 -> 18.0.2 [security]

### PR DESCRIPTION
**Pull request by tokudan**
###### Motivation for this change

The Changelog shows several fixes.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tokudan** [comment]
@GrahamcOfBorg test nextcloud

**Review by bachp — APPROVED** [review]
I have 18.0.1 running on nixos-unstable. I don't have a 20.03 instance running tough.

**Comment by tokudan** [comment]
18.0.2 has been released, so I'll update this PR shortly

**Comment by tokudan** [comment]
I'm running nextcloud 18.0.2 on my NixOS-20.03 system, so it works.
@GrahamcOfBorg test nextcloud.basic nextcloud.with-postgresql-and-redis nextcloud.with-mysql-and-memcached

**Comment by tokudan** [comment]
This is now a security issue: https://nextcloud.com/security/advisory/?id=nC-SA-2020-015

**Comment by flokli** [comment]
This is a backport PR of https://github.com/NixOS/nixpkgs/pull/80622 and https://github.com/NixOS/nixpkgs/pull/82508 to 20.03.

**Comment by flokli** [comment]
19.09 updates (on the 16.x track) happen in https://github.com/NixOS/nixpkgs/pull/82697.

**Pull request merged**
