### PR TITLE
Postgrey

### PR DESCRIPTION
**Pull request by gkleen**
###### Motivation for this change
The postgrey module was rather rudimentary

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

`configuration.nix` does not show `socket` nicely, I worked around that by making sure the default and example cover all options available in both submodules – is there a prettier solution?

### CODE REVIEW

**Comment by bendlas** [comment]
The option renames will be painful for any existing users, but I admit that it makes slightly more sense, the way you did it. Hoping that I'm the only existing user, a tentative +1 from me.

**Comment by joachifm** [comment]
You could add entries like those in https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/rename.nix to smoothe things out.

**Comment by pngwjpgh** [comment]
@joachifm @bendlas https://github.com/NixOS/nixpkgs/pull/21586/commits/9383b2cf347c4181bbdd14b5c8bcb929e4cdcb8b is untested.

**Comment by joachifm** [comment]
@bendlas are you okay with this? I have no stake in this module.

**Comment by bendlas** [comment]
LGTM, thanks for the compat options!

**Pull request merged**
