### PR TITLE
python312Packages.ocrmypdf: 16.5.0 -> 16.6.2

### PR DESCRIPTION
**Pull request by dotlambda**
Diff: https://github.com/ocrmypdf/OCRmyPDF/compare/v16.5.0...v16.6.2

Changelog: https://github.com/ocrmypdf/OCRmyPDF/blob/v16.6.2/docs/release_notes.rst

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 352270` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>paperless-ngx</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>ocrmypdf (python312Packages.ocrmypdf)</li>
    <li>ocrmypdf.dist (python312Packages.ocrmypdf.dist)</li>
    <li>python311Packages.ocrmypdf</li>
    <li>python311Packages.ocrmypdf.dist</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Upstream doesn't support that version yet https://github.com/paperless-ngx/paperless-ngx/blob/702ab1b77aa643a508702d180efe3c19aced50ce/Pipfile#L40 but I assume they will probably soonish. Not sure if that breaks things but I could imagine it. Since paperless-ngx has an option to archive the originals, I would think the devs would disable or ignore this behavior.

**Comment by dotlambda** [comment]
Paperless-ngx updated ocrmypdf in https://github.com/paperless-ngx/paperless-ngx/commit/d1f255a22ea53712cb9101277ec57ea1976f9c02. Should we patch it or wait for a release?

**Comment by SuperSandro2000** [comment]
They are usually releasing quite often. Maybe they release in the next week?

**Comment by shamoon** [comment]
Not really, we are building towards a larger release which means likely a bit longer than that, I dont have an exact timeline.

**Comment by dotlambda** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 352270`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 5 packages built:</summary>
  <ul>
    <li>ocrmypdf (python312Packages.ocrmypdf)</li>
    <li>ocrmypdf.dist (python312Packages.ocrmypdf.dist)</li>
    <li>paperless-ngx</li>
    <li>python311Packages.ocrmypdf</li>
    <li>python311Packages.ocrmypdf.dist</li>
  </ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]
seems to work for me

**Comment by SuperSandro2000** [comment]
@ofborg test paperless

**Comment by dotlambda** [comment]
I confirmed that the NixOS test passes locally.

**Pull request merged**
