### PR TITLE
elixir: 1.7.0 -> 1.7.2

### PR DESCRIPTION
**Pull request by LnL7**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by adisbladis** [comment]
The failed `x86_64-linux` build is just a network error.

**Comment by adisbladis** [comment]
@GrahamcOfBorg build elixir

**Comment by Mic92** [comment]
Strange both ofborg and nix-review do show changed packages in this pull request.

**Comment by LnL7** [comment]
@GrahamcOfBorg build beam.packages.erlang.elixir_1_7

**Pull request merged**
