### PR TITLE
komika-fonts: init at 0-unstable-2024-08-12

### PR DESCRIPTION
**Pull request by pancaek**
## Description of changes
Added the komika font family, with extensive styles for comic artists.

The homepage, which is an archive of the Lab project Komika was a part of: http://moorstation.org/typoasis/designers/lab

Font sources: https://www.1001fonts.com and https://www.1001freefonts.com (while the archive in the homepage contains most fonts, it is entirely missing the Komika Text set, and these should be far less prone to going defunct).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by pancaek** [comment]
I'm pretty sure I caught everything now, relatively sure I haven't missed anything else. Happy to squash any extra commits after review.

**Comment by pancaek** [comment]
Sorry about that, not totally sure what happened but I believe I've fixed it.

**Comment by pancaek** [comment]
Sorry about that, should be fixed now

**Review by mrshmllow — APPROVED** [review]

**Comment by pancaek** [comment]
I'm not terribly confident in my choice of license upon further reflection, the fonts are freeware, but this may be different from the nix notion of free. The zip files contain a custom license, so an extra look at that would be appreciated, as to avoid mislabeling it.

**Review by FliegendeWurst — CHANGES_REQUESTED** [review]
The license:
> This font is freeware and can be used as is in any context without permission from
Apostrophic Laboratories, except to produce material that is racist, criminal and/or illegal in nature. It is prohibited to modify any Apostrophic Laboratories font(s) for repackaging and or re-release without an express written authorization by the designer(s) of the font(s) or Apostrophic Laboratories. Under no circumstance shall any Apostrophic Laboratories design or font design be sold or purchased. Email info@apostrophiclab.com if you want more information.

= licenses.unfree

**Comment by pancaek** [comment]
Something went wrong when i squashed commits, looking into it

**Review by FliegendeWurst — APPROVED** [review]

**Review by misuzu — APPROVED** [review]

**Pull request merged**
