### PR TITLE
vimPlugins.neotest-playwright: add telescope dependency

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

As mentioned in [their README](https://github.com/thenbe/neotest-playwright?tab=readme-ov-file#installation), `telescope.nvim` is required.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 319314` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vimPlugins.neotest-playwright</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 319314` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vimPlugins.neotest-playwright</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 319314` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vimPlugins.neotest-playwright</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 319314` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vimPlugins.neotest-playwright</li>
  </ul>
</details>

**Comment by teto** [comment]
I dont see telescope used in their demo, it seems to use the native neovim TUI vim.select ? Ain't that a convenience dependency ?

**Comment by GaetanLepage** [comment]
> I dont see telescope used in their demo, it seems to use the native neovim TUI vim.select ? Ain't that a convenience dependency ?

From the logs of the nixvim test suite, it seems necessary:
https://buildbot.nix-community.org/api/v2/logs/99776/raw_inline

**Review by MattSturgeon — APPROVED** [review]

**Comment by teto** [comment]
I see 

> From the logs of the nixvim test suite, it seems necessary:
> https://buildbot.nix-community.org/api/v2/logs/99776/raw_inline

Would be nice to have a similar test in nixpkgs too. As you mentioned on chat, a requireCheck with neotest as dependency should catch this.

**Review by SuperSandro2000 — APPROVED** [review]

**Review by teto — APPROVED** [review]
we tried to quickly add a test with @GaetanLepage but it seemed non trivial.
Hopefully https://github.com/NixOS/nixpkgs/pull/319325 will fix some stuff. We can revisit later.

Do as you prefer @GaetanLepage ;)

**Comment by GaetanLepage** [comment]
> Do as you prefer @GaetanLepage ;)

Yes, let us merge this as is. We'll see afterwards regarding testing as we might need the lua-paths fix...

**Pull request merged**
