### PR TITLE
python3Packages.xmldiff: 2.5 -> 2.6.1

### PR DESCRIPTION
**Pull request by SFrijters**
###### Description of changes

https://github.com/Shoobx/xmldiff/compare/2.5...2.6

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ocfox** [comment]
Result of `nixpkgs-review pr 224543` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>checkov</li>
    <li>checkov.dist</li>
    <li>pip-audit</li>
    <li>pip-audit.dist</li>
    <li>python310Packages.cyclonedx-python-lib</li>
    <li>python310Packages.cyclonedx-python-lib.dist</li>
    <li>python311Packages.cyclonedx-python-lib</li>
    <li>python311Packages.cyclonedx-python-lib.dist</li>
  </ul>
</details>
<details>
  <summary>32 packages built:</summary>
  <ul>
    <li>atomic-operator</li>
    <li>atomic-operator.dist</li>
    <li>crackmapexec</li>
    <li>crackmapexec.dist</li>
    <li>python310Packages.fontmake</li>
    <li>python310Packages.fontmake.dist</li>
    <li>python310Packages.glyphslib</li>
    <li>python310Packages.glyphslib.dist</li>
    <li>python310Packages.psrpcore</li>
    <li>python310Packages.psrpcore.dist</li>
    <li>python310Packages.py-serializable</li>
    <li>python310Packages.py-serializable.dist</li>
    <li>python310Packages.pypsrp</li>
    <li>python310Packages.pypsrp.dist</li>
    <li>python310Packages.wavedrom</li>
    <li>python310Packages.wavedrom.dist</li>
    <li>python310Packages.xmldiff</li>
    <li>python310Packages.xmldiff.dist</li>
    <li>python311Packages.fontmake</li>
    <li>python311Packages.fontmake.dist</li>
    <li>python311Packages.glyphslib</li>
    <li>python311Packages.glyphslib.dist</li>
    <li>python311Packages.psrpcore</li>
    <li>python311Packages.psrpcore.dist</li>
    <li>python311Packages.py-serializable</li>
    <li>python311Packages.py-serializable.dist</li>
    <li>python311Packages.pypsrp</li>
    <li>python311Packages.pypsrp.dist</li>
    <li>python311Packages.wavedrom</li>
    <li>python311Packages.wavedrom.dist</li>
    <li>python311Packages.xmldiff</li>
    <li>python311Packages.xmldiff.dist</li>
  </ul>
</details>

**Review by ocfox — APPROVED** [review]

**Comment by ocfox** [comment]
Packages failed to build should be fixed:
checkov: #224586
pip-audit: #224590
python3Packages.cyclonedx-python-lib: #224583

**Comment by SFrijters** [comment]
Result of `nixpkgs-review pr 224543` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>pip-audit</li>
    <li>pip-audit.dist</li>
  </ul>
</details>
<details>
  <summary>36 packages built:</summary>
  <ul>
    <li>atomic-operator</li>
    <li>atomic-operator.dist</li>
    <li>crackmapexec</li>
    <li>crackmapexec.dist</li>
    <li>python310Packages.cyclonedx-python-lib</li>
    <li>python310Packages.cyclonedx-python-lib.dist</li>
    <li>python310Packages.fontmake</li>
    <li>python310Packages.fontmake.dist</li>
    <li>python310Packages.glyphslib</li>
    <li>python310Packages.glyphslib.dist</li>
    <li>python310Packages.psrpcore</li>
    <li>python310Packages.psrpcore.dist</li>
    <li>python310Packages.py-serializable</li>
    <li>python310Packages.py-serializable.dist</li>
    <li>python310Packages.pypsrp</li>
    <li>python310Packages.pypsrp.dist</li>
    <li>python310Packages.wavedrom</li>
    <li>python310Packages.wavedrom.dist</li>
    <li>python310Packages.xmldiff</li>
    <li>python310Packages.xmldiff.dist</li>
    <li>python311Packages.cyclonedx-python-lib</li>
    <li>python311Packages.cyclonedx-python-lib.dist</li>
    <li>python311Packages.fontmake</li>
    <li>python311Packages.fontmake.dist</li>
    <li>python311Packages.glyphslib</li>
    <li>python311Packages.glyphslib.dist</li>
    <li>python311Packages.psrpcore</li>
    <li>python311Packages.psrpcore.dist</li>
    <li>python311Packages.py-serializable</li>
    <li>python311Packages.py-serializable.dist</li>
    <li>python311Packages.pypsrp</li>
    <li>python311Packages.pypsrp.dist</li>
    <li>python311Packages.wavedrom</li>
    <li>python311Packages.wavedrom.dist</li>
    <li>python311Packages.xmldiff</li>
    <li>python311Packages.xmldiff.dist</li>
  </ul>
</details>

**Comment by SFrijters** [comment]
@ocfox FYI checkov now passes nixpkgs-review even though your PR for it is not yet merged.

**Comment by SuperSandro2000** [comment]
@ofborg build python310Packages.xmldiff

**Pull request merged**
