### PR TITLE
20.09: pythonPackages: use latest qt version instead of 5.14

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
Did you exclude any commits?

**Comment by FRidh** [comment]
I have tested several applications, definitely not all of them. This at least fixes the ones that were failing for me.

**Comment by doronbehar** [comment]
I too think no commits should be excluded.

**Comment by FRidh** [comment]
> attribute 'kidentitymanagement' missing, at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/packet-spot-eval-3/pkgs/top-level/all-packages.nix:21501:70

**Comment by jonringer** [comment]
@FRidh not all the applications are exposed correctly, since the 20.09 kde merge has to deviate from master

**Comment by jonringer** [comment]
cc @tteggel

**Comment by FRidh** [comment]
Something is of here with ofborg/actions. Everything succeeded, but it hasn't received the signal to pass the "Wait for ofborg" job.

**Comment by doronbehar** [comment]
Noticed that on other PRs. Could be fixed with https://github.com/NixOS/nixpkgs/pull/100269 ?

**Comment by FRidh** [comment]
Thanks. Then this goes in.

**Pull request merged**
