### PR TITLE
go_1_15: set knownVulnerabilities

### PR DESCRIPTION
**Pull request by zowoq**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by wamserma — APPROVED** [review]

**Comment by endocrimes** [comment]
We might want to avoid doing this to avoid it getting backported to stable? (and wait until we can cleanly remove it instead) - otherwise we’ll have a repeat of 1.14’s deprecation.

**Comment by wamserma** [comment]
Looking at release cycles we will always have one version of Go that goes EOL in the middle of the stable lifecycle.
A possible solution would be to have one recommended version in stable and clearly state that the previous version is only kept until its EOL to ease transitioning (e.g. by adding a deprecation warning).
(Commenting from a security perspective, I'm not very familiar with the Go ecosystem.)

**Comment by Mic92** [comment]
We would need some backports of go applications for this approach to work.

**Comment by zowoq** [comment]
I'll let someone else deal with fixing packages and disabling/removing `go_1_15`.

**Pull request closed without merging**
