### PR TITLE
todoman: 3.9.0 -> 4.0.0

### PR DESCRIPTION
**Pull request by anubhavkini**
###### Motivation for this change
Update todoman from 3.9.0 to 4.0.0.
This version introduces a breaking change in the configuration file and format.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 125901` at e946f506 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>todoman</li>
  </ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Comment by DeeUnderscore** [comment]
Could we get this rebased and merged? todoman currently fails to build in unstable due to a dependency (click) getting bumped in nixpkgs, and this version supports the updated dependency.

**Review by davidak — APPROVED** [review]
Changes look good

Builds, starts

```
[nix-shell:~/.cache/nixpkgs-review/pr-125901]$ results/todoman/bin/todo 
Error: No configuration file found.


For details on the configuration format and a sample file, see
https://todoman.rtfd.org/en/latest/configure.html

[nix-shell:~/.cache/nixpkgs-review/pr-125901]$ results/todoman/bin/todo --version
todoman, version 4.0.0

```

**Pull request merged**
