### PR TITLE
immersed-vr: version update to 10.2.1

### PR DESCRIPTION
**Pull request by iggyZiggy**
## Description of changes

version bump up to 10.1.1, updated to new links on web archive and updated hashes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by iggyZiggy** [comment]
Result of `nixpkgs-review pr 299955` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>immersed-vr</li>
  </ul>
</details>

**Review by haruki7049 — APPROVED** [review]
Thank you!! Nice work!!

**Comment by MikiVanousek** [comment]
I get the following error:
```
ps: error while loading shared libraries: libgpg-error.so.0: cannot open shared object file: No such file or directory
```

**Comment by iggyZiggy** [comment]
already reported that one and a solution for that on this issue:
https://github.com/NixOS/nixpkgs/issues/267408#issuecomment-1985518965

**Comment by pcasaretto** [comment]
Result of `nixpkgs-review pr 299955` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>immersed-vr</li>
  </ul>
</details>

**Comment by pcasaretto** [comment]
It builds on aarch64-darwin, but it occurred to me that these probably should be different packages as they follow different versioning schemes. The updated hash still points to 19.4 which is the same as before (made evident by the hash not changing).
I'll submit a PR this week proposing this separation.

**Comment by iggyZiggy** [comment]
sorry for this mess, i've followed some artice and added myself to maintainers which was not required for this update and then i had a rebase adventure by trying to undo that file, anyway, now it should work fine, updated to today's release and i think i've also managed to update the dmg too with hashes as well, @pcasaretto can you check that and confirm?

**Comment by iggyZiggy** [comment]
Result of `nixpkgs-review pr 299955` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>immersed-vr</li>
  </ul>
</details>

**Comment by iggyZiggy** [comment]
seems like the last 2 updates made improvements on GNOME but it broke on Hyprland, for me at least. Now i get the:
`GDBUS.Error:org.freedesktop.portal.Error.InvalidArgument: Unavailable cursor mode 4`
and after connecting to agent, screen doesn't show up. For anyone else having the same problem, last working version is 10.11.1 and can be run with:
`nix-shell -p appimage-run
appimage-run Immersed-x86_64.AppImage`
as a workaround, older working image can be downloaded from wayback machine, 10.11.1 was released on 03/21/2024
and 10.2.0 on 04/10/2024

**Comment by Pandapip1** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/299955

**Pull request closed without merging**
