### PR TITLE
lutris-unwrapped: 0.5.16 -> 0.5.17

### LINKED ISSUE #314414: Update request: lutris-unwrapped 0.5.16 → 0.5.17
- Package name: Lutris
- Latest released version: 0.5.17

- Current version on the unstable channel: 0.5.16
- Current version on the stable/release channel: 0.5.14

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@Madouura 
-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by bandithedoge**
https://github.com/lutris/lutris/releases/tag/v0.5.17

Closes #314414 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by jonas-w — APPROVED** [review]

**Review by jonas-w — APPROVED** [review]
Built on x86_64, and confirmed that it fixed the issue https://github.com/lutris/lutris/issues/5282

**Comment by michaelBelsanti** [comment]
I've been running Lutris from this branch for 2 weeks, no problems. Looks good to merge.

**Comment by jackyliu16** [comment]
> I've been running Lutris from this branch for 2 weeks, no problems. Looks good to merge.

 @michaelBelsanti Can your Epic be installed properly? 
 There seems to be an error on my side, but I don't quite understand what the specific problem is. 

<details>

<summary>OUTPUT of installation</summary>
```
lutris-wrapper: /home/jacky/.local/share/lutris/runtime/winetricks/winetricks
Started initial process 921904 from /home/jacky/.local/share/lutris/runtime/winetricks/winetricks --unattended corefonts
Start monitoring process.
------------------------------------------------------
warning: You are running winetricks-20230212-next, latest upstream is winetricks-20240105!
------------------------------------------------------
------------------------------------------------------
warning: You should update using your distribution's package manager, --self-update, or manually.
------------------------------------------------------
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20230212-next - sha256sum: 2d7770aa1f49f42ad9dafb092110dbf49fa6581738f6b80488cf0d7f59b2de72 with wine-8.0-3001-g39021e609a2 (Staging) and WINEARCH=win64
Executing w_do_call corefonts
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_corefonts 
Executing w_do_call andale
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_andale 
grep: 警告：/ 前有多余的 Executing cabextract -q -d /home/jacky/Games/epic-games-store/dosdevices/c:/windows/temp /home/jacky/.cache/winetricks/corefonts/andale32.exe
------------------------------------------------------
warning: Running /home/jacky/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wineserver -w. This will hang until all wine processes in prefix=/home/jacky/Games/epic-games-store terminate
------------------------------------------------------
Executing /home/jacky/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine C:\windows\syswow64
egedit.exe /S C:\windows\Temp\_register-font.reg
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
wine: failed to open C:\windows\syswow64
egedit.exe: c0000135
------------------------------------------------------
warning: Note: command /home/jacky/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine C:\windows\syswow64
egedit.exe /S C:\windows\Temp\_register-font.reg returned status 53. Aborting.
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 256)
Exit with return code 256
```
</details>

**Review by Cryolitia — APPROVED** [review]
Result of `nixpkgs-review pr 314682` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>lutris</li>
    <li>lutris-free</li>
    <li>lutris-unwrapped</li>
    <li>lutris-unwrapped.dist</li>
  </ul>
</details>

Building result runs fine on my x86_64

**Review by Aleksanaa — APPROVED** [review]

**Comment by michaelBelsanti** [comment]
> @michaelBelsanti Can your Epic be installed properly?

Sorry, missed this in my inbox. I use Heroic for games from Epic. I gave it a try and was able to install it with no problems. I would recommend trying a different default wine version. I used GE-Proton-9-7.

**Pull request merged**
