### PR TITLE
rofi: 1.6.1 -> 1.7.0

### PR DESCRIPTION
**Pull request by bew**
:warning: This is my first contribution here :) :warning: 

###### Motivation for this change

The rofi package was not up to date :smiley: 

This PR adds a new dependancy on `xcb-util-cursor` which is now needed for the build. 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bew** [comment]
I'm not sure about the release note change, is it the right section? do I need to rebuild the xml files or is that done automatically later?

**Comment by Kranzes** [comment]
Are you able to fetch the src with fetchFromGithub instead of fetchurl?
Also run nixpkgs-fmt on the default.nix if you can, Thanks.

**Comment by Kranzes** [comment]
> I'm not sure about the release note change, is it the right section? do I need to rebuild the xml files or is that done automatically later?

I personally updated/added countless of packages on/to nixpkgs and have never modified the release notes so I am not sure how it should be done.

**Comment by bew** [comment]
> Very rarely people update the release notes, it's almost always being done for major changes, luckily this rofi update isn't one, so you can skip that.

In this case, rofi dev didn't really prepared the deprecation / warned users it will be removed AFAIU, so it may look like a breaking change for people still using old themes, not rewritten to the new config language.
So I think it's important to mention it in the release.

**Comment by bew** [comment]
I updated the release notes with the script mentioned in the CONTRIBUTING.md file, and ran nixpkgs-fmt

**Comment by teto** [comment]
never done it myself but seems like you should just run `nixos/doc/manual/md-to-db.sh` so that the diff is empty. LKooking forward to this.

**Comment by teto** [comment]
and you've just done that ^^'' fetchFromGithub allows to fetch a tarball instead of a git clone which is more efficient overall IIRC.

**Comment by Kranzes** [comment]
> and you've just done that ^^'' fetchFromGithub allows to fetch a tarball instead of a git clone which is more efficient overall IIRC.

And it talks directly to the Github API, I'm sure it's mentioned somewhere in the nixpkgs manual.

**Comment by bew** [comment]
Ok, now updated to use `fetchFromGitHub` instead of `fetchurl`

**Comment by Kranzes** [comment]
> Ok, now updated to use `fetchFromGitHub` instead of `fetchurl`

Was fetchSubmodules required there? interesting...

**Comment by bew** [comment]
> Was fetchSubmodules required there? interesting...

Yes, because it has submodules: https://github.com/davatorium/rofi/tree/next/subprojects

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 136505` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>clerk</li>
    <li>i3-layout-manager</li>
    <li>rofi</li>
    <li>rofi-calc</li>
    <li>rofi-emoji</li>
    <li>rofi-file-browser</li>
    <li>rofi-menugen</li>
    <li>rofi-pass</li>
    <li>rofi-systemd</li>
    <li>rofi-unwrapped</li>
    <li>rofi-vpn</li>
    <li>rofimoji</li>
    <li>todofi-sh</li>
  </ul>
</details>

**Comment by bew** [comment]
Do I need to do anything else?

**Comment by Kranzes** [comment]
I ran nixpkgs-review and nixos-install-tools fails to build for some reason...

**Comment by bew** [comment]
I don't think my changes have anything to do with that..

**Comment by Ma27** [comment]
Not sure why it was tested, but `nixos-install-tools` doesn't seem to depend on `rofi`:

```
→ nix-store --query $(nix-instantiate -A nixos-install-tools) --requisites --include-outputs|grep rofi; echo $?
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
1
```

**Pull request merged**
