### PR TITLE
keysmith: 0.1 → 0.2

### PR DESCRIPTION
**Pull request by SCOTT-HAMILTON**
#### Motivation for this change
Keysmith released a new stable tag

###### Things done
Moved from 0.1 to 0.2, this release brings a lot of new good features.

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — CHANGES_REQUESTED** [review]
doesn't work on nixos
```
QQmlApplicationEngine failed to load component
qrc:/main.qml:22 module "Oath" is not installed
qrc:/main.qml:23 module "Oath.Validators" is not installed
qrc:/main.qml:22 module "Oath" is not installed
qrc:/main.qml:23 module "Oath.Validators" is not installed
```

**Comment by SCOTT-HAMILTON** [comment]
I can't reproduce your error, this derivation runs fine for me. 
Looking the sources, main.qml#L22-L23, I don't see what could produce this error : https://github.com/KDE/keysmith/blob/3880f325ce0730694daa6db868fac4c85462fa32/src/contents/ui/main.qml#L22

**Comment by SCOTT-HAMILTON** [comment]
Don't know why but using fetchurl rather than fetchFromGitHub fixed it.
Further examinating this behaviour, if I exrtact the source directly from the github archive, I don't get the issue anymore. 
And obviously, the sources fetched by `fetchFromGitHub` and does manually fetched are identical.
The issue seems to come from fetchFromGitHub.

**Comment by jonringer** [comment]
:(
```
[nix-shell:/home/jon/.cache/nixpkgs-review/pr-91961]$ ./results//keysmith/bin/keysmith
QQmlApplicationEngine failed to load component
qrc:/main.qml:23 module "Oath.Validators" is not installed
qrc:/main.qml:22 module "Oath" is not installed
qrc:/main.qml:23 module "Oath.Validators" is not installed
qrc:/main.qml:22 module "Oath" is not installed
```

**Comment by SCOTT-HAMILTON** [comment]
Seems like I can't open issues upstream : https://github.com/KDE/keysmith

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 91961` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>keysmith</li>
  </ul>
</details>

**Pull request merged**
