### PR TITLE
bazecor: 1.3.11 -> 1.4.0

### PR DESCRIPTION
**Pull request by gcleroux**
## Description of changes

Update bazecor to 1.4.0
https://github.com/Dygmalab/Bazecor/releases/tag/v1.4.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by amesgen — APPROVED** [review]
Thanks, tested this with my Raise :+1:

 - I have confirmed that the udev rules haven't changed since they were last updated
 - The udev rule workaround has been correctly updated :+1:

We *could* also try to patch out the new prompt which offers auto-updates; but given that it is a one time thing (after declining), this doesn't seem too important.

**Comment by gcleroux** [comment]
> We _could_ also try to patch out the new prompt which offers auto-updates; but given that it is a one time thing (after declining), this doesn't seem too important.

Yeah, frankly I didn't give it much thought. I looked at the appimage and we could patch the autoUpdate with this:
```nix
    # Workaround for https://github.com/Dygmalab/Bazecor/issues/370
    postExtract = ''
      substituteInPlace \
        $out/usr/lib/bazecor/resources/app/.webpack/main/index.js \
        --replace-fail \
          'checkUdev=()=>{try{if(c.default.existsSync(f))return c.default.readFileSync(f,"utf-8").trim()===d.trim()}catch(e){u.default.error(e)}return!1}' \
          'checkUdev=()=>{return 1}'

      # Remove the Bazecor autoUpdate message
      substituteInPlace \
        $out/usr/lib/bazecor/resources/app/.webpack/main/index.js \
        --replace-fail \
          'if(void 0===o.get("settings.autoUpdate")){let t;"darwin"!==process.platform?(t={type:"question",buttons:["Decline","Consent"],cancelId:0,defaultId:1,title:"Bazecor auto update tool",message:"Bazecor will update automatically whenever possible",detail:"Do you want to make Bazecor able to auto update automatically?, click consent to authorize automatic downloads of new versions, if you decline this feature, you can enable it again in preferences."},s.dialog.showMessageBox(e,t).then((e=>{1===e.response?o.set("settings.autoUpdate",!0):o.set("settings.autoUpdate",!1)}))):(t={type:"question",buttons:["Consent","Decline"],cancelId:1,defaultId:0,title:"Bazecor auto update tool",message:"Bazecor will update automatically whenever possible",detail:"Do you want to make Bazecor able to auto update automatically?, click consent to authorize automatic downloads of new versions, if you decline this feature, you can enable it again in preferences."},s.dialog.showMessageBox(e,t).then((e=>{0===e.response?o.set("settings.autoUpdate",!0):o.set("settings.autoUpdate",!1)})))}' \
          'o.set("settings.autoUpdate", !1);'
    '';
```
It replaces the popup's code and disables the `autoUpdate` settings in the store instead.

I could commit this change, but I'm not sure if this will become more of an headache than anything down the line since patching the appimage is definitely a little jank.

Up to you really, I'm ok with either options.

**Comment by amesgen** [comment]
I have no strong opinion either, let's keep the PR as is then; the line seems a bit long :sweat_smile:

**Review by rhoriguchi — APPROVED** [review]
Works on `x86_64-linux` with Defy

**Pull request merged**
