### PR TITLE
nixos/usbStorage: init

### PR DESCRIPTION
**Pull request by bb2020**
###### Description of changes
https://bugzilla.kernel.org/show_bug.cgi?id=205107

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bb2020** [comment]
Ping @Ma27

**Review by AndersonTorres — APPROVED** [review]

**Comment by bjornfor** [comment]
Are there any downsides to enabling this option? (I know it's off by default, just wondering.) If there are no downsides, then shouldn't this udev rule be enabled somewhere upstream instead?

**Comment by bb2020** [comment]
There should be no downsides. This is a probable miscommunication between `libata` and `usb-storage` maintainers. Beacuse `libata` enables `manage_start_stop` by default for internal drives.

**Comment by bjornfor** [comment]
> There should be no downsides. This is a probable miscommunication between libata and usb-storage maintainers. Beacuse libata enables manage_start_stop by default for internal drives.

Yes, looking at my own system, all sata drives have it set, whereas USB drives (spinning disks and flash memory) don't have it set:
```
$ grep -rn --include manage_start_stop . /sys/devices/
/sys/devices/pci0000:00/0000:00:1f.2/ata8/host7/target7:0:0/7:0:0:0/scsi_disk/7:0:0:0/manage_start_stop:1:1
/sys/devices/pci0000:00/0000:00:1f.2/ata6/host5/target5:0:0/5:0:0:0/scsi_disk/5:0:0:0/manage_start_stop:1:1
/sys/devices/pci0000:00/0000:00:11.4/ata1/host0/target0:0:0/0:0:0:0/scsi_disk/0:0:0:0/manage_start_stop:1:1
/sys/devices/pci0000:00/0000:00:11.4/ata4/host3/target3:0:0/3:0:0:0/scsi_disk/3:0:0:0/manage_start_stop:1:1
/sys/devices/pci0000:00/0000:00:11.4/ata2/host1/target1:0:0/1:0:0:0/scsi_disk/1:0:0:0/manage_start_stop:1:1
/sys/devices/pci0000:00/0000:00:11.4/ata3/host2/target2:0:0/2:0:0:0/scsi_disk/2:0:0:0/manage_start_stop:1:1
/sys/devices/pci0000:00/0000:00:14.0/usb3/3-6/3-6:1.0/host10/target10:0:0/10:0:0:0/scsi_disk/10:0:0:0/manage_start_stop:1:0
/sys/devices/pci0000:00/0000:00:14.0/usb3/3-5/3-5:1.0/host12/target12:0:0/12:0:0:0/scsi_disk/12:0:0:0/manage_start_stop:1:0
/sys/devices/pci0000:00/0000:00:14.0/usb3/3-3/3-3:1.0/host11/target11:0:0/11:0:0:0/scsi_disk/11:0:0:0/manage_start_stop:1:0
```

**Pull request merged**
