### PR TITLE
heroic: 2.2.6 -> 2.4.0

### PR DESCRIPTION
**Pull request by Birdthatcantfly**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pmiddend** [comment]
I tried building and running this (on NixOS) and after opening the GUI, I see this:

grafik

The log says:

```
(09:19:28) INFO:    [DXVKInstaller]:   Updating vkd3d to: vkd3d-proton-2.6
(09:19:28) INFO:    [DXVKInstaller]:   Updating dxvk to: dxvk-1.10.1
(09:19:28) INFO:    [Backend]:         Downloaded Winetricks
(09:19:29) INFO:    [DXVKInstaller]:   downloaded vkd3d
(09:19:29) INFO:    [DXVKInstaller]:   extracting vkd3d
(09:19:29) ERROR:   [DXVKInstaller]:   Extraction of vkd3d failed with: Error: Command failed: tar -I zstd -xvf /home/philipp/.config/heroic/tools/vkd3d/vkd3d-proton-2.6.tar.zst -C /home/philipp/.config/heroic/tools/vkd3d
zstd: symbol lookup error: /usr/lib/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
tar: Child returned status 127
tar: Error is not recoverable: exiting now

(09:19:30) INFO:    [DXVKInstaller]:   downloaded dxvk
(09:19:30) INFO:    [DXVKInstaller]:   extracting dxvk
(09:19:30) INFO:    [DXVKInstaller]:   extracting dxvk updated!
```

I can click it away, but it happens on every startup of heroic. Seems there are some hard-coded paths to `/usr/lib`?

I then tried logging into my Epic account and got a browser window containing some JSON. Pressing "Reload" brings me to the start page where I'm logged in now.

I tried installing a game from the Epic store (Absolute Drift), which worked fine. Playing didn't work, though: 

```
(09:26:33) ERROR:   [Backend]:         TypeError - Cannot read properties of undefined (reading 'bin')
```

I think Nix-wise, the PR looks fine, and the application _does_ start, so we might as well merge it. But Heroic does seem pretty unstable right now.

**Comment by bryanasdev000** [comment]
This should close https://github.com/NixOS/nixpkgs/pull/179608

**Comment by bryanasdev000** [comment]
@Birdthatcantfly could you upgrade to the latest version?

**Comment by aidalgol** [comment]
[2.4.0](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v2.4.0) is now the latest stable release.

**Comment by Birdthatcantfly** [comment]
@WolfangAukang Can you review  this PR? ĉu vi povas kontrollegi tiu PR?

**Comment by WolfangAukang** [comment]
Hey @Birdthatcantfly, mi bedaŭras la malfrua respondo, mi tute forgesis respondi ĉi tiu PR. Mi respondos en la angla:

Unfortunately, I have sold my gaming device a few months ago and my current computer is not capable of running games at all, so I can only test the software functioning, but not gaming.

Also, there is something to consider on this PR, which is that, as `legendary` and `gogdl` are packed by the offered packages, the program will look at the path of those on the `asar`. As it is not possible to modify much of the AppImage contents AFAIK, I packaged it on NUR but picking the DEB instead (where you have more flexibility to handle the content of the environment it will generate). I can send those changes if you want.

**Comment by WolfangAukang** [comment]
Created #187631, which kind of fits what @pmiddend indicates. From there, anyone can create a wrapper of the package that can suit their needs.

**Comment by WolfangAukang** [comment]
Will close this one as #187960 is doing a major refactoring job on the package, plus it is being updated.

**Comment by Birdthatcantfly** [comment]
@WolfangAukang Thank you for your work!

**Pull request closed without merging**
