### PR TITLE
Exegol update 4.3.1 to 4.3.8

### PR DESCRIPTION
**Pull request by charB66**
## Description of changes

Updating to the latest version - 4.3.8 - from PyPi.

**Note: I had to change the `pname` to `exegol` instead of `Exegol` because the source distribution link change from `https://files.pythonhosted.org/...SNIP.../==>E<==xegol-*.*.*.tar.gz` to `https://files.pythonhosted.org/..SNIP.../==>e<==xegol-*.*.*.tar.gz`**

## Things done

- Built on platform(s)
    - [x]  x86_64-linux
    - [ ]  aarch64-linux
    - [ ]  x86_64-darwin
    - [ ]  aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
    - [ ]  `sandbox = relaxed`
    - [ ]  `sandbox = true`
- [ ]  Tested, as applicable:
    - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
    - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
    - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
    - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ]  Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x]  Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
    - [ ]  (Package updates) Added a release notes entry if the change is major or breaking
    - [ ]  (Module updates) Added a release notes entry if the change is significant
    - [ ]  (Module addition) Added a release notes entry if adding a new NixOS module
- [x]  Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AkechiShiro** [comment]
@charB66 thanks for the PR however, the commits aren't right, there a commit on other packages such as `vale`, I don't know why they are there, you should have only commits on `exegol` :
 
- One for the update version 
- One for the maintainer addition 

> When adding yourself as maintainer in the same pull request, make a separate commit with the message maintainers: add <handle>. Add the commit before those making changes to the package or module.

See for more details on commits conventions https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md?preview=1#commit-conventions 

I suggest you rebase your PR, squash the two maintainers commits and rewords them accordingly.

**Comment by charB66** [comment]
Changes done!
I kept the three original commits as advised by mattpolzin in [my previous (failed and cancelled) PR](https://github.com/NixOS/nixpkgs/pull/323585#issuecomment-2201851996).
I think everything is ok now :).

**Comment by AkechiShiro** [comment]
Nixpkgs build result seems to be successful : 

2 packages built:
exegol exegol.dist

This LGTM

**Review by AkechiShiro — APPROVED** [review]

**Comment by AkechiShiro** [comment]
Hi again @charB66 

Could you add `xorg.xhost` as well in dependencies, this is necessary to share windows from the docker instance in the graphical environment.

**Review by AkechiShiro — CHANGES_REQUESTED** [review]
@charB66  Could you please add `xorg.xhost` for X11 windows sharing, as this does not work under Wayland hosts where `xorg.xhost` is not installed by default at the moment.

**Comment by AkechiShiro** [comment]
@charB66 could you please update to 4.3.7 and address the change requested ?

**Comment by AkechiShiro** [comment]
Result of `nixpkgs-review pr 345103` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>exegol</li>
    <li>exegol.dist</li>
  </ul>
</details>

**Review by AkechiShiro — APPROVED** [review]
LGTM

**Comment by AkechiShiro** [comment]
Hey @charB66 sorry again but could you please upgrade to 4.3.8 ?

**Comment by charB66** [comment]
Hello @AkechiShiro, yes of course.

**Comment by 0b11stan** [comment]
Currently testing this for an assessment.
So far so good, LGTM too

**Comment by AkechiShiro** [comment]
Result of `nixpkgs-review pr 345103` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>exegol</li>
    <li>exegol.dist</li>
  </ul>
</details>

**Review by AkechiShiro — APPROVED** [review]
@charB66 I think a final step would be to add a script to auto update/auto trigger PR using a specific update script I think, I may try and achieve this in a follow up PR, link to the doc here https://nix-community.org/update-bot/

We could also improve reliability by writing a test that spawns a VM, pulls Exegol docker container (the lightest) and `exegol start -l` (with asciinema logging), then just do an "echo Exegol" and check that everything went well.

Could you also leave an approval review @0b11stan as you've done some testing too ?

**Pull request merged**
