### PR TITLE
Keybase updates

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
Wanted to keep these up to date.

https://github.com/keybase/client/releases

cc @rvolosatovs

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
I'm seeing that `keybase-gui` has `gnome2.GConf` as build input.

I'd like to figure out if that is needed, as I'd like to remove that dependency wherever possible.

**Review by kalbasit — APPROVED** [review]

**Comment by kalbasit** [comment]
@worldofpeace I'm checking on my side if that's removable.

**Comment by kalbasit** [comment]
@worldofpeace it worked well without it. It built correctly and the gui behaved just fine.

```
$ nix-shell -p nur.repos.kalbasit.nix-verify --run 'nix-verify -I nixpkgs=`pwd` -A keybase-gui
```

**Comment by worldofpeace** [comment]
Removing this now then.

**Pull request merged**
