### PR TITLE
treewide: with stdenv.lib; in meta -> with lib;

### PR DESCRIPTION
**Pull request by Profpatsch**
Part of: https://github.com/NixOS/nixpkgs/issues/108938

    meta = with stdenv.lib;

is a widely used pattern. We want to slowly remove
the `stdenv.lib` indirection and encourage people
to use `lib` directly. Thus let’s start with the meta
field.

This used a rewriting script to mostly automatically
replace all occurances of this pattern, and add the
`lib` argument to the package header if it doesn’t
exist yet.

The script in its current form is available at
https://cs.tvl.fyi/depot@2f807d7f141068d2d60676a89213eaa5353ca6e0/-/blob/users/Profpatsch/nixpkgs-rewriter/default.nix

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Profpatsch** [comment]
Strategies used to sanity check the changes involve using a script to randomly evaluate packages, so all important packages should still evaluate.

```
nix eval --raw '(let pkgs = import ./. {}; in builtins.toJSON (builtins.attrNames pkgs))' \
   | jq -r '.[]' \
   | shuf \
    | head -n 1000 \
     | xargs -n1 nix-instantiate -A
```

Some leaf packages might have problems if they don’t follow the `callPackage` standard but pass arguments manually. Hopefully ofborg finds them.

**Comment by Profpatsch** [comment]
The output of

```
$ git diff --numstat HEAD^ | sort -n | tail -n30
2	2	pkgs/tools/X11/xvkbd/default.nix
2	2	pkgs/tools/X11/xwallpaper/default.nix
2	2	pkgs/tools/X11/xwinwrap/default.nix
3	3	pkgs/applications/audio/clementine/default.nix
3	3	pkgs/applications/misc/ape/default.nix
3	3	pkgs/applications/misc/plover/default.nix
3	3	pkgs/applications/networking/instant-messengers/salut-a-toi/requirements.nix
3	3	pkgs/applications/science/logic/coq/default.nix
3	3	pkgs/applications/video/kodi/plugins.nix
3	3	pkgs/development/tools/parsing/antlr/4.8.nix
3	3	pkgs/games/openxray/default.nix
3	3	pkgs/games/riko4/default.nix
3	3	pkgs/misc/vim-plugins/overrides.nix
3	3	pkgs/os-specific/linux/guvcview/default.nix
3	3	pkgs/servers/kippo/default.nix
3	3	pkgs/tools/package-management/nix-prefetch-scripts/default.nix
3	3	pkgs/tools/typesetting/tex/texlive/bin.nix
4	4	pkgs/applications/audio/dfasma/default.nix
4	4	pkgs/applications/misc/dockbarx/default.nix
4	4	pkgs/applications/misc/subsurface/default.nix
4	4	pkgs/applications/virtualization/qemu/default.nix
4	4	pkgs/misc/tmux-plugins/default.nix
5	5	pkgs/tools/text/gawk/default.nix
7	7	pkgs/applications/networking/znc/modules.nix
8	8	pkgs/applications/video/vdr/plugins.nix
9	9	pkgs/misc/vscode-extensions/default.nix
10	10	pkgs/applications/editors/jetbrains/default.nix
16	16	pkgs/applications/misc/octoprint/plugins.nix
26	26	pkgs/applications/editors/eclipse/plugins.nix
```

shows that there are only a few files which got more than two lines of changes.

**Comment by AndersonTorres** [comment]
Good to know. Following.

**Comment by SuperSandro2000** [comment]
EditorCheck fails with ``Error: Argument list too long``. I think it is save to ignore it for this PR.

**Comment by deliciouslytyped** [comment]
Couldn't you test it by generating all the drvs and making sure they're invariant?

**Comment by cole-h** [comment]
`pkgs/misc/emulators/cdemu/base.nix` was changed, but `lib` was not introduced in the deps list (leading to the eval error above).

**Comment by alyssais** [comment]
On Sun, Jan 10, 2021 at 01:43:49PM -0800, deliciouslytyped wrote:
> Couldn't you test it by generating all the drvs and making sure they're invariant?

OfBorg does that. ;)

I've been approving all the PRs for this so far provisionally, on the
condition that OfBorg finds them to be rebuild-0.

**Comment by alyssais** [comment]
@Profpatsch I've found a bug:

> -       stdenv.isCygwin # XXX: `test-dup2' segfaults on Cygwin 6.1
> +       stdenvisCygwin # XXX: `test-dup2' segfaults on Cygwin 6.1

My strategy for reviewing this sort of change is focused on identifying bad
changes rather than ensuring exhaustiveness.  To that end, I ran the
following:

    git fetch nixpkgs # your remote may be called "origin"
    git fetch nixpkgs pull/108978/head
    git diff nixpkgs/master...FETCH_HEAD --word-diff=porcelain --word-diff-regex="[a-zA-Z_][a-zA-Z0-9_'-]*" |
        grep -e '^[+-]' |
        grep -ve '^\(+++\|---\)' |
        sort -u

(Thanks @puckipedia for the Nix identifier regex.)

Which will show me every unique word addition and deletion.  This PR
will only be correct when the output of that pipeline is:

    +lib
    -stdenv

(The +lib comes from having to add lib as an argument)

Currently it outputs:

    +lib
    -stdenv
    +stdenvisCygwin
    -stdenv.isCygwin
    +stdenvisFreeBSD
    -stdenv.isFreeBSD
    +stdenvisSunOS
    -stdenv.isSunOS

And thus the problem is identified.

This check is not exhaustive for correctness, but passing this check
is a necessary part of correctness.

**Comment by Profpatsch** [comment]
Ah yes, I made a mistake when correcting some incorrect replacements that were missing a dot. I thought I had caught them all, but apparently not.

**Comment by Profpatsch** [comment]
> OfBorg does that. ;) I've been approving all the PRs for this so far provisionally, on the condition that OfBorg finds them to be rebuild-0.

ofborg chickened out because “doesn’t list changes cleanly”, not sure what we can do about that.

**Comment by Profpatsch** [comment]
Ah, it does seem to stumble into eval errors, it just displays a confusing error message in the check status.

Oh, and now the merge conflicts begin, this is gonna be fun …

**Comment by Profpatsch** [comment]
>  This check is not exhaustive for correctness, but passing this check is a necessary part of correctness.

Ah, it was right, there were some of these erroneous replacements missing in a commented out piece of code, which my editor’s static nix analyzer did not find of course. Fixed.

**Comment by Profpatsch** [comment]
Rebased on master.

**Comment by Profpatsch** [comment]
I did a dudu while rebasing, I think it’s fixed now.

**Comment by Profpatsch** [comment]
Thanks to @cole-h running the ofborg check locally, full evaluation should now work again.

**Comment by Profpatsch** [comment]
Waiting for ofborg eval to be green, then rebasing & merging (otherwise there will be new merge conflicts before ofborg evals)

**Comment by Profpatsch** [comment]
ofborg takes a while to reach this eval in its queue, and then chickens out immediately if there is a merge conflict … we are running the https://github.com/nixos/ofborg#running-meta-checks-locally check on a big machine and will merge once that succeeds.

**Comment by Profpatsch** [comment]
Okay, ran the eval and made sure the check from above

```
    git diff nixpkgs/master...FETCH_HEAD --word-diff=porcelain --word-diff-regex="[a-zA-Z_][a-zA-Z0-9_'-]*" |
        grep -e '^[+-]' |
        grep -ve '^\(+++\|---\)' |
        sort -u
```

proudces

```
+lib
-stdenv
```

**Review by alyssais — APPROVED** [review]
Ran the OfBorg checks locally. All good.

**Comment by sternenseemann** [comment]
I think a pass with a secondary tool over files changed by this addressing left over `stdenv.lib.versionAtLeast` etc. usages could be worthwhile.

**Comment by FRidh** [comment]
This broke eval in `pkgs/os-specific/linux/nvidia-x11/persistenced.nix`

**Comment by cole-h** [comment]
> Please test treewide changes with `hydra-eval-jobs`.

Sounds like a good idea -- but how (what is the incantation)?

**Comment by jonringer** [comment]
There's probably a better way, but:
```
nix-shell -p hydra-unstable --run "hydra-eval-jobs -I nixpkgs=$PWD nixos/release.nix"
```

**Comment by cole-h** [comment]
And how do we know that there's an issue, given that loads of packages fail to evaluate (e.g. unfree and broken)? Is there some pattern that's easily greppable for? Running `hydra-eval-jobs -I . pkgs/top-level/release.nix` gave me more than 1.6 million lines of output, *after* filtering out all the broken and unfree packages.

**Comment by jonringer** [comment]
that's an excellent question :)

**Comment by FRidh** [comment]
> And how do we know that there's an issue, given that loads of packages fail to evaluate (e.g. unfree and broken)? Is there some pattern that's easily greppable for? Running hydra-eval-jobs -I . pkgs/top-level/release.nix gave me more than 1.6 million lines of output, after filtering out all the broken and unfree packages.

An actual eval error will kill the evaluation. Note one should test `pkgs/top-level/release.nix` but also those under `nixos/`. Probably should write a section on this in the Nixpkgs manual.

**Comment by cole-h** [comment]
I see. So as long as `hydra-eval-jobs` exits zero, all is fine, and one should test both `pkgs/top-level/release.nix` and `nixos/release.nix`. Thanks for the help, I'll keep this in mind for the next time. Since I didn't say so earlier: thanks for catching and fixing the issue.

**Comment by sternenseemann** [comment]
> An actual eval error will kill the evaluation. Note one should test pkgs/top-level/release.nix but also those under nixos/. Probably should write a section on this in the Nixpkgs manual.

`hydra-eval-jobs` exits 0 sometimes even when ofborg still finds evaluation errors.

**Comment by Profpatsch** [comment]
This is a best-effort refactor as long as we don’t have well-documented ways of making sure the whole tree still evaluates. We used the ofborg check for that, running it locally.

**Pull request merged**
