### PR TITLE
Darkcoin 0.10.99.99 -> Dash 0.12.0.55

### PR DESCRIPTION
**Pull request by AndersonTorres**
Now, Darkcoin changed his name for Dash.

### CODE REVIEW

**Comment by vcunat** [comment]
Well, we already have that shell called "dash", so nix-env might replace one with the other. Hmm, I forgot: it would perhaps even attempt to "upgrade" from one to the other. We should better change the name, I think.

Any ideas for a better name? Other distros use "dash" for the shell, so we should keep that one for it.

**Comment by AndersonTorres** [comment]
Do you say something about changng the binary names? Or the package name - to something as "altcoins.dashpay"?
As I list the directory, this is the result:

$ ls fakeroot/nixpkgs/outputs/altcoins.dash/bin                                                                                     ~
dash-cli  dashd  dash-qt  dash-tx  test_dash  test_dash-qt

No clashing with "dash" shell.

**Comment by vcunat** [comment]
No, the binaries don't clash. The package names do, e.g.:
```
$ nix-env -qa dash
dash-0.12.0.55
dash-0.5.8
```

I suppose "dashpay" is the best alternative?

**Comment by AndersonTorres** [comment]
"Dashpay" is good for me :+1:

**Comment by vcunat** [comment]
Pushed the rename.

**Pull request closed without merging**
