### PR TITLE
nixosTests: re-enable networking tests

### PR DESCRIPTION
**Pull request by flokli**
5150378c2f10d34a7ba4404c52f6c882284dd254 fixed the long-broken
nixosTests.networking.virtual.

With all tests failures fixed, and #79328 making debugging much easier,
let's re-add it to the tested jobset.
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by andir** [comment]
@ofborg test networking.scripted.link  networking.scripted.privacy  networking.scripted.routes  networking.scripted.virtual  networking.networkd.bond  networking.networkd.bridge  networking.networkd.dhcpOneIf  networking.networkd.dhcpSimple  networking.networkd.link  networking.networkd.loopback  networking.networkd.macvlan  networking.networkd.privacy  networking.networkd.routes  networking.networkd.sit  networking.networkd.static  networking.networkd.virtual  networking.networkd.vlan

**Comment by andir** [comment]
Some of the tests seem to be flaky. See the aarch64 build results.

**Comment by flokli** [comment]
Hm, I tried squinting at the logs to spot the error, the only parts I found were nixos-test driver specific failures:

```
  File "/nix/store/qv7jilbizwv4cz2rbh46hhkyzavwp4bv-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 748 in process_serial_output
Current thread 0x0000fffff7ff5780 (most recent call first):
/nix/store/rsjp3g6hny6b7m3m6kv753lps0pvdqak-stdenv-linux/setup: line 1271:     6 Aborted                 (core dumped) LOGFILE=$out/log.xml tests='exec(os.environ["testScript"])' /nix/store/5gzzr77gg756pgxdk76wyhjshyfkvcl6-nixos-test-driver-vlan-Networking-Networkd/bin/nixos-test-driver
```

```
  File "/nix/store/qv7jilbizwv4cz2rbh46hhkyzavwp4bv-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 748 in process_serial_output
Current thread 0x0000fffff7ff5780 (most recent call first):
/nix/store/rsjp3g6hny6b7m3m6kv753lps0pvdqak-stdenv-linux/setup: line 1271:     6 Aborted                 (core dumped) LOGFILE=$out/log.xml tests='exec(os.environ["testScript"])' /nix/store/5gzzr77gg756pgxdk76wyhjshyfkvcl6-nixos-test-driver-vlan-Networking-Networkd/bin/nixos-test-driver
```

I couldn't spot some "networking-specific flakiness in there - it looks more like a generic test-driver flakyness, maybe only happening under high load?

@tfc, any ideas?

**Comment by flokli** [comment]
I rebased on top of 78f2a830291eb19af6306476b186b585f4d9cd37, assuming this should fix the observed flakyness.

**Comment by flokli** [comment]
@ofborg test networking.scripted.link networking.scripted.privacy networking.scripted.routes networking.scripted.virtual networking.networkd.bond networking.networkd.bridge networking.networkd.dhcpOneIf networking.networkd.dhcpSimple networking.networkd.link networking.networkd.loopback networking.networkd.macvlan networking.networkd.privacy networking.networkd.routes networking.networkd.sit networking.networkd.static networking.networkd.virtual networking.networkd.vlan

**Comment by flokli** [comment]
Hrm, this still fails:

```
Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stderr>'> at interpreter shutdown, possibly due to daemon threads
Thread 0x0000fffff52101e0 (most recent call first):
  File "/nix/store/kb785q5ry1s7s9fcvxyba1c6c52w0zha-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 93 in eprint
  File "/nix/store/kb785q5ry1s7s9fcvxyba1c6c52w0zha-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 748 in process_serial_output
Thread 0x0000fffff5a111e0 (most recent call first):
  File "/nix/store/kb785q5ry1s7s9fcvxyba1c6c52w0zha-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 93 in eprint
  File "/nix/store/kb785q5ry1s7s9fcvxyba1c6c52w0zha-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 748 in process_serial_output
Thread 0x0000fffff62121e0 (most recent call first):
  File "/nix/store/kb785q5ry1s7s9fcvxyba1c6c52w0zha-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 93 in eprint
  File "/nix/store/kb785q5ry1s7s9fcvxyba1c6c52w0zha-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 748 in process_serial_output
Current thread 0x0000fffff7ff5780 (most recent call first):
/nix/store/yaw7vxl73i6ii08yqid69mli216b9p28-stdenv-linux/setup: line 1271:     6 Aborted                 (core dumped) LOGFILE=/dev/null tests='exec(os.environ["testScript"])' /nix/store/xmi7nwsf3fidj6pqhkpfnd8bvjrlbskn-nixos-test-driver-Privacy-Networking-Networkd/bin/nixos-test-driver
builder for '/nix/store/vyz7ylzi3iqwmphlzv9nfchax35dlr8f-vm-test-run-Privacy-Networking-Scripted.drv' failed with exit code 134
```

**Comment by flokli** [comment]
Even when removing all the `queue` stuff, I still got the
> Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stderr>'> at interpreter shutdown, possibly due to daemon threads

So this seems to come from `process_serial_output` being in a separate thread, and the underlying print to stderr.

With all the xml/html log output gone since #87191, I'll give it a try to rework this to make use of Pythons native `logging` framework, which is supposed to be [thread safe](https://docs.python.org/3/library/logging.html#thread-safety).

**Comment by flokli** [comment]
Converting to draft until the discussion following https://github.com/NixOS/nixpkgs/pull/87191#issuecomment-626136749 has been done.

**Review by Ma27 — COMMENTED** [review]
After having read the threads in this PR, #86889 and #87191 I think that it's preferable to have a stable test-driver rather than waiting until we've reached consensus about how `$out` and logging should look like.

IMHO we can still re-add lost features later on. I may be rather unlucky, but I regularly experience frozen VM-tests (that get "fixed" by restarting them) and right now I have a simple VM using grafana and loki (based on the test-driver) that reproducibly breaks when trying to shut it down (with the error demonstrated in #86889 ) and I think that it's more important to get those kind of (known) issues under control.

**Comment by flokli** [comment]
Yeah, I agree. Feel free to take over this PR - I can't currently pursue this.

**Comment by Ma27** [comment]
I'm sorry, I don't want to start another time-consuming task here, I should get a lot of other NixOS-related stuff I'm hacking on done first :sweat_smile: 

If anyone who subscribed to this thread wants to take over, I'd be fairly grateful!

**Comment by Mic92** [comment]
https://github.com/NixOS/nixpkgs/pull/96254

**Comment by flokli** [comment]
With #96254 being merged, I reopened this, dropped the wip refactor now done in #96254, and rebased to latest master.

**Review by Ma27 — APPROVED** [review]

**Comment by andersk** [comment]
`networking.networkd.macvlan` is failing most of the time: #96709

**Comment by andersk** [comment]
Also #96254 was just reverted (in #96703, to fix #96699).

**Pull request merged**
