### PR TITLE
ghc on musl: Crude hack to allow integer-simple

### PR DESCRIPTION
**Pull request by nomeata**
as per discussion on
https://github.com/NixOS/nixpkgs/pull/130441#issuecomment-922275844 this
seems to be enough to make
```
nix-build -A pkgsMusl.haskell.packages.integer-simple.ghc884.hello
```
work again.

This is likely not the right patch (maybe `gmp` should be
`nativeBuildInput`? Or a propagated build input from the boot ghc?), but
this way I we can discuss (and I can pull the patch into my project...)

### CODE REVIEW

**Comment by nomeata** [comment]
@ofborg pkgsMusl.haskell.packages.integer-simple.ghc884.hello pkgsMusl.haskell.packages.integer-simple.ghc8107.hello

**Comment by nomeata** [comment]
@ofborg build pkgsMusl.haskell.packages.integer-simple.ghc884.hello pkgsMusl.haskell.packages.integer-simple.ghc8107.hello

**Comment by cdepillabout** [comment]
cc @nh2 about this as well

**Comment by nh2** [comment]
Answering https://github.com/NixOS/nixpkgs/pull/130441#issuecomment-922443078

> is a fix along the lines of #138429 the wrong direction?

Based on my write-up https://github.com/NixOS/nixpkgs/pull/130441#issuecomment-922452843 just now, this PR is probably not the "proper fix".

It is `pkgsMusl.haskell.compiler.ghc8102BinaryMinimal` that should be fixed (it forgets its GMP path), not the compilers that are compiled with it.

That said, `ghc8102BinaryMinimal` is mainly used to bootstrap other compilers, so injecting the GMP dependencies into the derivations of those compilers looks like a **reasonable workaround**.

It would be very beneficial though to check that `gmp` is no longer referred to at all by the bootstrapped compilers, or leaked into the outputs built with them (as people use `integer-simple` specifically to be sure not to have a `gmp` dependency). Even better to assert it programmatically, but I don't know how to do that; https://github.com/NixOS/nixpkgs/pull/130441#issuecomment-922278984 mentioned `disallowedRequisites` but I don't know yet what that is.

**Comment by nh2** [comment]
I have put out an alternative PR #138524, which switches `ghc8102Binary` -> `ghc8107Binary` as the bootstrap compiler instead.

If it works, that should be cleaner than this workaround.

**Comment by nomeata** [comment]
Thanks for your help! I’ll close this then

**Pull request closed without merging**
