### PR TITLE
nextpnr: add gowin arch

### PR DESCRIPTION
**Pull request by newAM**
###### Motivation for this change

Add support for the gowin FPGA to [nextpnr](https://github.com/YosysHQ/nextpnr).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by newAM** [comment]
Looks like the darwin failures are because of this: https://github.com/NixOS/nixpkgs/issues/137678

**Review by emilazy — APPROVED** [review]
Looks good to me! We might want to start thinking about splitting the package or at least having multiple outputs at some point as the number of huge `nextpnr-*` binaries grows, but I don't think that needs handling here.

Don't worry about the Darwin failures; that issue is breaking a ton of packages right now.

**Comment by risicle** [comment]
Builds happily, nixos x86_64

**Comment by newAM** [comment]
Rebased onto the latest `master` to test that it works after `nexpnr` was updated earlier today: https://github.com/NixOS/nixpkgs/commit/3a784c4963918c462dd2e81e055c2404ec9ea2cf

Still works.

**Review by thoughtpolice — APPROVED** [review]

**Review by thoughtpolice — APPROVED** [review]

**Pull request merged**
