### PR TITLE
extra-container: 0.8 -> 0.10

### PR DESCRIPTION
**Pull request by erikarvstedt**
This adds compatibility with NixOS 22.05 and unstable.

- [x] Tested on x86_64-linux

cc @Lassulus

### CODE REVIEW

**Comment by Lassulus** [comment]
So I guess we want to backport this to 22.05?

**Comment by erikarvstedt** [comment]
Sure, after this has been merged.

**Comment by Lassulus** [comment]
we can add a label to automate this! :)

**Comment by erikarvstedt** [comment]
Ah, great, I thought the bot needed a merge first.

**Comment by Lassulus** [comment]
Result of `nixpkgs-review pr 179198` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>extra-container</li>
  </ul>
</details>

**Pull request merged**
