### PR TITLE
radicle-upstream: 0.1.11 -> 0.2.3

### PR DESCRIPTION
**Pull request by d-xo**
###### Motivation for this change

new version :)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by maralorn** [comment]
I have build and run this locally. I can start the program and it works kinda fine.
I got some weird error messages when trying to setup a project. But those could be either from stale data from running radicle 0.1.* before or because I didn‘t setup the git-rad helper correctly.

**Comment by xwvvvvwx** [comment]
The git rad helper should be set up out of the box.

Which error messages did you see?

**Comment by maralorn** [comment]
When I try to create a project I get:
```
{
  "code": "ProjectCreationFailure",
  "source": {
    "code": "UnknownException",
    "details": {
      "name": "Error",
      "body": {
        "message": "child exited unsuccessfully",
        "variant": "TRANSPORT_ERROR"
      },
      "response": {}
    }
  }
}
```
Then whenever I switch to the Projects tab I get:
```
{
  "code": "UnhandledRejection",
  "details": {
    "name": "Error",
    "errors": [
      {
        "code": "unrecognized_keys",
        "keys": [
          "type"
        ],
        "path": [
          0
        ],
        "message": "Unrecognized key(s) in object: 'type'"
      },
      {
        "code": "invalid_type",
        "expected": "object",
        "received": "null",
        "path": [
          0,
          "stats"
        ],
        "message": "Expected object, received null"
      }
    ]
  }
}
```

**Comment by xwvvvvwx** [comment]
@maralorn I suspect this is an issue with upstream itself rather than the nix package specifically. Do you get the same error when you try executing the appimage downloaded directly from the releases page (https://releases.radicle.xyz/radicle-upstream-0.2.3.AppImage)?

**Comment by xwvvvvwx** [comment]
@maralorn after discussing with the upstream devs on element, it seems as though your issue is unrelated to the nix package and should be fixed by this pr: https://github.com/radicle-dev/radicle-upstream/pull/1854.

Since this seems to be rather an issue with how the app handles loading failed projects, rather than any issue with the nix package I don't think it should block merging of this PR.

**Pull request merged**
