### PR TITLE
[WIP] nvidia-firmware: init at 325.15 - calling all nvidia users

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

The nouveau driver requires firmware blobs from nvidia in order to enable proper acceleration on some cards (mine's a GK107).

This PR adds support for fetching and extracting the firmware which then needs to be included in the configuration. In order to test this out, you need to do the following:

1. Change to the ```modesetting``` driver in configuration.nix:
```nix
{
  services.xserver.videoDrivers = [ "modesetting" ];
}
```

2. Load the firmware files:
``` nix
{
  boot.extraModprobeConfig = "options nouveau config=NvGrUseFw=1";
  hardware.firmware = with pkgs; [ firmwareLinuxNvidia ];
}
```

3. Add ```vdpauinfo``` to the global environment (you can also just use nix-env -i) which we will need later:
``` nix
{
  environment.systemPackages = with pkgs; [ vdpauinfo ];
}
```

4. Generate the new configuration:
```shell
sudo nixos-rebuild boot -I nixpkgs=https://github.com/peterhoeg/nixpkgs/archive/p/nvidia.tar.gz
```

5. Reboot and run ```vdpauinfo``` to trigger the loading and check in the journal that there are no errors:

```shell
vdpauinfo
journalctl -b | grep -i nouveau
```

6. ```vdpauinfo``` should also tell you that you have acceleration:

```shell
vdpauinfo | head -n 30

display: :0   screen: 0
API version: 1
Information string: G3DVL VDPAU Driver Shared Library version 1.0

Video surface:

name   width height types
-------------------------------------------
420    16384 16384  NV12 YV12
422    16384 16384  UYVY YUYV
444    16384 16384  Y8U8V8A8 V8U8Y8A8

Decoder capabilities:

name                        level macbs width height
----------------------------------------------------
MPEG1                           0 65536  4096  4096
MPEG2_SIMPLE                    3 65536  4096  4096
MPEG2_MAIN                      3 65536  4096  4096
H264_BASELINE                  41 65536  4096  4096
H264_MAIN                      41 65536  4096  4096
H264_HIGH                      41 65536  4096  4096
VC1_SIMPLE                      1 65536  4096  4096
VC1_MAIN                        2 65536  4096  4096
VC1_ADVANCED                    4 65536  4096  4096
MPEG4_PART2_SP                  3 65536  4096  4096
MPEG4_PART2_ASP                 5 65536  4096  4096
DIVX4_QMOBILE                  --- not supported ---
DIVX4_MOBILE                   --- not supported ---
DIVX4_HOME_THEATER             --- not supported ---
```

Should this be part of "enableAllFirmware" ?

```meta.hydraPlatforms``` is blanked out as we cannot redistribute the firmware blobs.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dezgeg** [comment]
Is your nouveau module getting loaded in the initrd? If so, you probably need to include the firmwares there as well.

**Comment by edolstra** [comment]
Regarding inclusion in `enableAllFirmware`, could this package conflict with the full nvidia package? (E.g. cause `nvidia.ko` to use firmware from this package, which might be a different version of the upstream package.)

**Comment by peterhoeg** [comment]
@edolstra, I don't think so as the firmware is extracted from the binary driver, so I would imagine that it is loaded as part of the nvidia driver being loaded. But in any case, I'll test that out.

@dezgeg, is there some magic to loading the firmware files into the initrd? I've tried the following but it simply causes the kernel to panic during boot:

``` nix
{
  boot.initrd.prepend = [
    "${pkgs.firmwareLinuxNvidia}/lib/firmware/nouveau/*"
  ];
}
```

Do I need to make a cpio archive or something?

**Comment by dezgeg** [comment]
I guess it's easier to debug by first getting it to work outside of initrd.

**Comment by peterhoeg** [comment]
@dezgeg, sure, but how do I get it to delay loading the module?

**Comment by peterhoeg** [comment]
@dezgeg and @jansol, we're in business now. I can confirm that it works here.

I haven't mapped all the different card types but let's try with these first.

**Comment by jansol** [comment]
SDDM still doesn't stay open. Not sure if it's a problem with the driver or something else. https://gist.github.com/jansol/3c88efb903bec9df3e578b942eb82eff

**Comment by peterhoeg** [comment]
So X is segfaulting. Can you try with the modesetting X driver instead of nouveau (ref item 1)?

**Comment by jansol** [comment]
With that it works and vdpauinfo output matches what's mentioned here!

**Comment by peterhoeg** [comment]
@fpletz, any thoughts/commens on this?

**Review by fpletz — APPROVED** [review]
@peterhoeg Sorry for the late response. Code looks fine to me, but can't test as I don't own nvidia graphics hardware.

**Comment by peterhoeg** [comment]
@fpletz I need to map the remaining models but I obviously cannot test those as I only have on card (and @jansol another). Do you have any preferences regarding how we handle that? Should we simply not map those because we cannot test them or put a massive disclaimer in the documentation? How have you handled firmware for hardware you cannot test in the past?

**Comment by 7c6f434c** [comment]
I would support just adding the full mapping while testing as the things go and documenting what is known.

After all, we don't test Linux kernel updates on everything we can find before pushing to master.

**Comment by 7c6f434c** [comment]
Hm, in addition to GK107 I have a GM108, what would I need to do to test there?

**Comment by peterhoeg** [comment]
@7c6f434c, you need to map the gm108 to the correct chip name and then add a call to ```link_files``` - I used this for mapping the current ones:
https://nouveau.freedesktop.org/wiki/CodeNames/#NV110

I unfortunately do not know which file to map to for the gm108.

**Comment by 7c6f434c** [comment]
Do I understand correctly that you just map the entry outside the parenthesis to the entry inside the parenthesis?

**Comment by peterhoeg** [comment]
Indeed it is, BUT in this case we don't have any of the firmware files for the NV110 family so I don't know if that's a case of them being called something else.

In my case (GK107), it was exactly what I did:
https://github.com/NixOS/nixpkgs/pull/25075/files#diff-8d5aad77f256d1c21742a3bc2f6a3e49R44

We have the following firmware files available:
- nv98
- nva3
- nva5
- nva8
- nvaa
- nvac
- nvaf
- nvc0
- nvc1
- nvc3
- nvc4
- nvc8
- nvce
- nvcf
- nvd7
- nvd9
- nve4
- nve6
- nve7
- nvf0
- nvf1
- nv106
- nv108

But looking at the dates of the release, the Maxwell cards were released after the driver version we're using. I'll see if we can find a newer one.

**Comment by peterhoeg** [comment]
@edolstra ,

> Regarding inclusion in enableAllFirmware, could this package conflict with the full nvidia package? (E.g. cause nvidia.ko to use firmware from this package, which might be a different version of the upstream package.)

The firmware is now located in ```lib/firmware/nouveau``` instead and only those models we specifically link end up in ```lib/firmware/nvidia```.

This way we don't inadvertently use the this firmware.

If ```linux-firmware``` starts carrying firmware for older nvidia cards we should get a collision.

**Comment by 7c6f434c** [comment]
I guess NV110 is just old enough to be different.

**Comment by calvertvl** [comment]
I've got a GTX-285 which uses NVA0, if you can find the firmware for that one.

I also have a 560 Ti SLI system, which is either NVC8 or (more likely) NVCE, but it is down at the moment; if no one else can test that firmware, I should have it up enough for testing by the end of May.

**Comment by peterhoeg** [comment]
I've added support for GTX-285 - can you give it a go please?

**Comment by peterhoeg** [comment]
No, that didn't work. Please wait.

**Comment by Mic92** [comment]
Including `unfree` marked firmware files in all firmware, should be solved by this commit: https://github.com/NixOS/nixpkgs/pull/25636

**Comment by 0xABAB** [comment]
When this works, can its functionality be put in a module? That way the installer could also hook into it and users don't need to care about the details.

**Comment by jansol** [comment]
What's the status of this?

**Comment by peterhoeg** [comment]
I've been using it on my side without problems but it is only tested against a very limited set of hardware. Turning this into a proper module as suggested by @0xABAB is definitely the way to go - I just haven't done that yet.

**Comment by peterhoeg** [comment]
Brief update, I'm working on a proper nixos module for this which should make things much nicer to work with.

**Comment by baracoder** [comment]
(triage) Any progress on this?

**Comment by peterhoeg** [comment]
Well, it works - someone just need to write the module. I personally don't use the nvidia card any longer as it was just too much trouble and the onboard intel gfx are fine for my case.

**Comment by zyradyl** [comment]
Hello,

I was actually working on trying to write this myself before I found this pull request, I'd like to take it the rest of the way to getting merged, but I was wondering where I should look for information on converting it to a module?

Sorry if this is obvious, I'm still new to Nix.

**Comment by peterhoeg** [comment]
Hi,

>   I was actually working on trying to write this myself before I found this
>   pull request, I'd like to take it the rest of the way to getting merged,
>   but I was wondering where I should look for information on converting it
>   to a module?

Basically, the option that are outlined in the first post need to be set via a module. We already have https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/hardware/video/nvidia.nix which is where it should be put.

>   Sorry if this is obvious, I'm still new to Nix.

Nothing to apologize for.
>

**Comment by peterhoeg** [comment]
Might also make sense to get https://github.com/NixOS/nixpkgs/pull/49703 merged first.

**Comment by peterhoeg** [comment]
I'll get this done.

**Comment by peterhoeg** [comment]
@zyradyl did you get any further with updating the nvidia module by chance?

**Comment by afrepues** [comment]
@peterhoeg I have some changes that I use in my machine at: https://github.com/afrepues/nixpkgs/tree/nvidia-firmware

Feel free to incorporate whatever you find useful.

**Comment by otavio** [comment]
What is the status of this PR? @peterhoeg have you finish it so it could be reviewed?

**Comment by peterhoeg** [comment]
> What is the status of this PR? @peterhoeg have you finish it so it could be reviewed?

I gave up on nvidia and bought an AMD GPU which works perfectly. The only thing missing is just to wrap the manual steps in a module.

**Pull request closed without merging**
