### PR TITLE
rstudio: fix build with new hunspell-dicts

### PR DESCRIPTION
**Pull request by averelld**
###### Motivation for this change
rstudio build broken because of new hunspell dicts: https://github.com/NixOS/nixpkgs/pull/66670#issuecomment-528330031
Not exactly elegant, so improvements welcome.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by ivan** [comment]
@GrahamcOfBorg build rstudio rstudioWrapper

**Comment by matthewbauer** [comment]
Sorry about that! I didn't realized it would break this. Looked through for other cases of this, and this appears to be the only one.

**Review by matthewbauer — APPROVED** [review]

**Review by ivan — APPROVED** [review]
Looks fine to me, assuming grahamcofborg says this builds

**Comment by devhell** [comment]
Thanks for looking into getting this merged, much appreciated! :)

**Comment by devhell** [comment]
Hmmm..

@GrahamcOfBorg build rstudio rstudioWrapper

**Comment by devhell** [comment]
Okay, so I'm not sure why ofBorg had issues, but I can build this locally without errors and rstudio runs.

**Comment by ivan** [comment]
I confirm that this PR does build (tested NixOS x86_64).

**Comment by devhell** [comment]
Thanks, can someone please merge this? @matthewbauer maybe? Thank you!

**Comment by lheckemann** [comment]
Backporting to 19.09 as soon as I've built it.

**Comment by lheckemann** [comment]
19.09: ada07de5d0c3699911bbcae7e4a6cffd0e4c5cd1

**Pull request merged**
