### PR TITLE
[Backport release-24.05] auto-cpufreq: 1.9.9 -> 2.3.0

### PR DESCRIPTION
**Pull request by sarcasticadmin**
## Description of changes

https://github.com/NixOS/nixpkgs/pull/315383

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by sokai** [comment]
@apps/ofborg : I wonder if there is any reason to request the review from @Technical27 …

Maybe @wegank can have a look/help out, like in/with [the last update PR](https://github.com/NixOS/nixpkgs/pull/253595) (where also the review was requested to @Technical27 by @apps/afborg)? *#thinking*

Sry for the noise and KR!

**Comment by sarcasticadmin** [comment]
I'm specifically interested in getting fixes for AMD CPUs that landed sometime after `auto-cpufreq 1.9.9`:

- https://github.com/AdnanHodzic/auto-cpufreq/issues/666
- https://github.com/AdnanHodzic/auto-cpufreq/issues/636

**Comment by wegank** [comment]
Just a final check before merging: does the update contain any known breaking changes?

**Comment by wegank** [comment]
> @apps/ofborg : I wonder if there is any reason to request the review from Technical27 …

Looks like the maintainer isn't active, I think you can drop them following the procedure [here](https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md#how-to-lose-maintainer-status). (and possibly add yourself as a maintainer of the package)

**Comment by sarcasticadmin** [comment]
> Just a final check before merging: does the update contain any known breaking changes?

Reviewed the release notes and there doesn't appear to be any breaking changes

**Pull request merged**
