### PR TITLE
wine{Unstable,Staging}: 7.17 -> 7.20

### PR DESCRIPTION
**Pull request by SuperSamus**
###### Description of changes
https://www.winehq.org/announce/7.18
Tested only a little.
EDIT: https://www.winehq.org/announce/7.19
EDIT: https://www.winehq.org/announce/7.20

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SFrijters** [comment]
Version 7.19 also upgrades vkd3d, can you bump that from 1.4 to 1.5 as well? Can cherry-pick https://github.com/NixOS/nixpkgs/pull/196656/commits/1f7466b87ef2952583a9c3438061219a54ce0912 if you want.

**Comment by SFrijters** [comment]
Result of `nixpkgs-review pr 194215` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>29 packages built:</summary>
  <ul>
    <li>exactaudiocopy</li>
    <li>grapejuice</li>
    <li>lutris</li>
    <li>lutris-free</li>
    <li>lutris-unwrapped</li>
    <li>pipelight</li>
    <li>playonlinux</li>
    <li>q4wine</li>
    <li>winbox</li>
    <li>wine (winePackages.full ,winePackages.stableFull)</li>
    <li>wine-staging (winePackages.stagingFull)</li>
    <li>wine-wayland (winePackages.waylandFull)</li>
    <li>wine64 (wine64Packages.full ,wine64Packages.stableFull)</li>
    <li>wine64Packages.staging</li>
    <li>wine64Packages.stagingFull</li>
    <li>wine64Packages.unstable</li>
    <li>wine64Packages.unstableFull</li>
    <li>wine64Packages.waylandFull</li>
    <li>winePackages.staging</li>
    <li>winePackages.unstable</li>
    <li>winePackages.unstableFull</li>
    <li>wineWowPackages.full (wineWowPackages.stableFull)</li>
    <li>wineWowPackages.staging</li>
    <li>wineWowPackages.stagingFull</li>
    <li>wineWowPackages.unstable</li>
    <li>wineWowPackages.unstableFull</li>
    <li>wineWowPackages.waylandFull</li>
    <li>yabridge</li>
    <li>yabridgectl</li>
  </ul>
</details>

**Comment by SFrijters** [comment]
I had another compiler segmentation when trying to do a review of my own PR https://github.com/NixOS/nixpkgs/pull/196656, but yours works fine so I'm a bit confused. But anyway.

**Comment by SuperSamus** [comment]
Is there anything missing for this to be merged?

**Comment by SFrijters** [comment]
LGTM, but I can't do anything to move this forward.
Also, 7.20 was released yesterday, but updating this PR again seems silly.

**Comment by SuperSamus** [comment]
Why would it be silly?

**Comment by reckenrode** [comment]
Result of `nixpkgs-review pr 194215` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>wine64Packages.staging</li>
    <li>wine64Packages.stagingFull</li>
    <li>wine64Packages.unstable</li>
    <li>wine64Packages.unstableFull</li>
  </ul>
</details>

**Comment by SuperSamus** [comment]
Is anything missing for this to be merged?

**Pull request merged**
