### PR TITLE
Tree sitter fetch all grammars

### PR DESCRIPTION
**Pull request by Profpatsch**
The update script would only fetch the few grammars listed in the
tree-sitter repository previously. But the tree-sitter github orga has
a rather large amount of officially supported grammars.

Thus we change the script to query the github APIs for repositories
instead (up to 100 this is supported without paging).

Since the repository list also contains some that are not grammars,
there is a bash script which lists all repos we are aware of and the
ones we want to ignore. It will make sure we don’t forget any
repositories in the future, by comparing to the actual list with jq.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
I am not sure yet but it would be nice to keep the lua grammar ( https://github.com/nvim-treesitter/tree-sitter-lua ): neovim may require it for its 0.5 release.

**Comment by Profpatsch** [comment]
I am unsure how the lua grammar was added, since the update script would definitely not keep it.

We are going to have to add a list of extra grammars to the updater.

**Comment by Profpatsch** [comment]
> neovim may require it for its 0.5 release.

As in, it would want a dependency?
Before we depend on it from within nixpkgs, I’d make sure the build we expose has a at least somewhat stable API that is easy to integrate. Right now the grammars only get a `$out/parser` executable, I don’t know if that is enough.

**Comment by teto** [comment]
It may become a dependency, it has not been decided yet. Even without I would like to keep it. Maybe it can be defined somewhere else to make it clear it's not automatically updated.

**Comment by Profpatsch** [comment]
> Maybe it can be defined somewhere else to make it clear it's not automatically updated.

it should definitely be automatically updated

**Comment by Profpatsch** [comment]
It’s easy to add, let me take a look.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107514` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>tree-sitter</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107514` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>tree-sitter</li>
  </ul>
</details>

**Comment by Profpatsch** [comment]
@teto I refactored a little, now we can add more repositories that are not from the tree-sitter orga.

**Comment by teto** [comment]
The configuration is scattered through several whiltelists/orgs, my approach would have been to put a single list with the different attributes  (organisation, ignore etc) but as long as it works, it's fine. Feel free to merge when ready.

**Review by teto — APPROVED** [review]

**Comment by Profpatsch** [comment]
>  my approach would have been to put a single list with the different attributes (organisation, ignore etc) but as long as it works, it's fine. Feel free to merge when ready.

We want the tree-sitter org grammars to be complete always, this is why they are handled specially, because the update script checks whether we missed a repo.

**Pull request merged**
