### PR TITLE
Rstudio 2023.06.1+524

### PR DESCRIPTION
**Pull request by nviets**
###### Description of changes

Updating RStudio to latest release. WIP. To-do list:

- [ ] Fix yarn failure in panmirror that breaks the build. I am not familiar with node.js so any tips would be appreciated
- [ ] Enable Quarto and use dependency from nixpkgs

@alexvorobiev, @jbedo, @ciil, @cfhammill

nixpkgs-review log to follow...

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin

### CODE REVIEW

**Comment by nviets** [comment]
Result of `nixpkgs-review pr 245269` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>rstudio</li>
    <li>rstudio-server</li>
    <li>rstudioServerWrapper</li>
    <li>rstudioWrapper</li>
  </ul>
</details>

**Comment by nviets** [comment]
###### Failed derivations

- [ ] RStudio-2023.06.1+524.drv (derivation hash: mrjyqsbgw5xgd32rpn9ia0a5j5pm2pnp)
  - https://gist.github.com/nviets/c945390704d7c98d168bbf2ba3ea30e1
- [ ] RStudio-2023.06.1+524.drv (derivation hash: zwiclgbbh4df73c2pprd145khf0g39cv)
  - https://gist.github.com/nviets/77126c6cdfb5d55aea45d2695197415c

**Comment by jbedo** [comment]
Thanks for working on this, I've started working on bumping rstudio too but haven't had time to finish yet. Your patch for node won't work as it doesn't resolve yarn being called during the build process. I started on this but haven't completed it:

https://github.com/jbedo/nixpkgs/commit/0ccf0a2a910f79e608fe77ac254e98cdb2913022#diff-66342e98cded6365b6717795595bb0560b71413063d178eef1f343fdd7547925

@b-rodrigues fyi

**Comment by nviets** [comment]
Thanks @jbedo  - I pulled your patch into this PR, and it's getting a bit further. The build fails in the panmirror stage when yarn attempts to download dependencies. I imagine we need to update the yarndeps.nix and yarn.lock files. Could anyone point me to the documentation on how to do that?

**Comment by nviets** [comment]
Result of `nixpkgs-review pr 245269` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>rstudio</li>
    <li>rstudio-server</li>
    <li>rstudioServerWrapper</li>
    <li>rstudioWrapper</li>
  </ul>
</details>

**Comment by nviets** [comment]
Hi @MrTarantoga - could you share how you updated the yarndeps.nix and yarn.lock file for this build? I'm trying to update RStudio, but I'm not familiar with the node.js build system.

**Comment by nviets** [comment]
###### Failed derivations

- [ ] RStudio-2023.06.1+524.drv (derivation hash: chz8cygvvgf1fpgx0gyb0n2jp9rg8r6k)
  - https://gist.github.com/nviets/f69b541a3b89a7ce2433a2c17f287724
- [ ] RStudio-2023.06.1+524.drv (derivation hash: z7xgw5p2sij69splki3hv9mmk6xv33p3)
  - https://gist.github.com/nviets/06737e426713a8ddf6ff5d81d2e83ae0

**Comment by b-rodrigues** [comment]
Hi, I was able to get the latest release of RStudio to build thanks to @jbedo ’s help, but visual mode wouldn’t work. Here are my steps:

- get the latest yarn.lock file from the quarto-dev repo: https://github.com/quarto-dev/quarto/tree/release/rstudio-cherry-blossom This is because panmirror has been moved to the quarto-dev repo since the latest "cherry-blossom" release of RStudio.
- get the latest `package.json` as well
- generate the yarndeps.nix file using yarn2nix `yarn2nix > yarndeps.nix`

RStudio should now build successfully, start and operate normally, but for Visual Mode. I don’t really know what’s missing. Maybe this could help: https://github.com/rstudio/rstudio/wiki

**Comment by b-rodrigues** [comment]
So @nviets does it also build for you? What about visual editing mode for markdown, does it work?

**Comment by nviets** [comment]
Not building yet, and I'm trying to clean up the patches now. I'll work on visual editing mode as soon as I get it building.

**Comment by nviets** [comment]
It's almost building, but I'm still working through the quarto stuff. I'll share a log in a few minutes.

**Comment by nviets** [comment]
Result of `nixpkgs-review pr 245269` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>rstudio</li>
    <li>rstudio-server</li>
    <li>rstudioServerWrapper</li>
    <li>rstudioWrapper</li>
  </ul>
</details>

**Comment by nviets** [comment]
###### Failed derivations

- [ ] RStudio-2023.06.1+524.drv (derivation hash: wb1gpjsr9k934s0xnl1wna3vcpkik1v4)
  - https://gist.github.com/nviets/d70572d4322ebea6cd7a58ffccabd024
- [ ] RStudio-2023.06.1+524.drv (derivation hash: 4jkq58hq0pr6hrlm11wbdna6mr6q955c)
  - https://gist.github.com/nviets/9e901965afa251eae3df199720776237

**Comment by nviets** [comment]
RStudio is building now, and I'm starting to test the functionality of visual editing and quarto.

**Comment by nviets** [comment]
rstudio
Here's where I'm stuck. I tried enabling quarto in the build, and it looks like RStudio wants a particular version. Opening a markdown error triggers another version complaint about the specific rmarkdown package version. Neither seems reasonable because both quarto-cli and rmarkdown in nixpkgs are recent versions.

**Comment by nviets** [comment]
Here's a lead... https://github.com/rstudio/rstudio/issues/12169

**Comment by nviets** [comment]
Hi @jgutman, we maintain a version of RStudio in nixpkgs and are trying to update to the latest version with quarto enabled in the build. Similar to the SUSE thread mentioned above, nix provides its own quarto and builds without network access. I tried patching the quarto path, but RStudio is still complaining as in the screenshot. Could you offer any tips on what I've missed? Pandoc has been working fine up to now, but I was hoping to update to quarto here. Thank you!

**Comment by nviets** [comment]
I wonder if we need to patch [external-quarto-path](https://github.com/rstudio/rstudio/blob/main/src/cpp/session/session-options.json#L728):
- https://github.com/rstudio/rstudio/blob/main/src/cpp/session/include/session/SessionOptions.gen.hpp#L376
- https://github.com/rstudio/rstudio/blob/main/src/cpp/conf/rsession-dev.conf#L40
- https://github.com/rstudio/rstudio/blob/main/src/cpp/conf/rdesktop-dev.conf#L45

**Comment by nviets** [comment]
Not sure why RStudio isn't happy with the quarto an pandoc paths. The patch appears to be working correctly inside of SessionConstants.hpp:

```
#ifdef QUARTO_ENABLED
# define kDefaultPandocPath        "/nix/store/z7304ayw334d6cfr8aljfsdhrmx88k73-pandoc-2.19.2/bin/pandoc"
#else
# define kDefaultPandocPath        "bin/pandoc"
#endif

#define kDefaultQuartoPath         "/nix/store/mam9h964gjjwl8pq81lwa99mmh5z9wcd-quarto-1.2.475/bin/quarto"
#define kDefaultRsclangPath        "bin/rsclang"
```

**Comment by nviets** [comment]
Finally a little progress. The Quarto CLI error at the bottom of the RStudio window is finally resolved thanks to giving the full path to pandoc in RSTUDIO_DEPENDENCIES_PANDOC_DIR. RMarkdown continues to fail on the same error. I suspect its another path issue or I'm missing a spot to patch.

**Comment by maupind** [comment]
@nviets Hey I've been attempting to update RStudio off and on for the past month and a half before coming across this thread. I running into similar issues that the beginning of this thread seems to have solved. I am curious if there is anything I can do to help?

**Comment by nviets** [comment]
Hi @maupind and @b-rodrigues, thanks for engaging. I've been traveling for the last week and am just now freeing up to have another look. I'd love to coordinate efforts, and I'll have join the matrix room.

**Comment by ciil** [comment]
Sadly, I'm currently really resource constrained and don't think I can adequately continue maintaining this package. It's totally okay to remove me from maintainers (I really should've done that a while ago) and for yourself and the others in this PR to take over!

**Comment by nviets** [comment]
Closing as this has been superseded by https://github.com/NixOS/nixpkgs/pull/252047

**Pull request closed without merging**
