### PR TITLE
qutebrowser: 3.0.0 -> 3.0.2

### PR DESCRIPTION
**Pull request by arjan-s**
Changelog: https://www.qutebrowser.org/doc/changelog.html
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
> Diff: https://github.com/qutebrowser/qutebrowser/compare/None...v3.0.2

doesn't sound right

**Comment by arjan-s** [comment]
Hmm, weird, that must have been put there by nix-update. Anyway, thanks, it's fixed now.

**Comment by VuiMuich** [comment]
Can confirm build on `x86_64-linux`.

(As this fixes some nasty qt bug for me, I'll keep running the `result/bin` until this is merged, as I am to lazy to patch this in my flake :stuck_out_tongue:)

**Comment by nrdxp** [comment]
Working on building this on top of master atm. Looks like qt was just updated to the 6.6 release and the caches haven't been populated so I have to build all of webengine. I'll leave it all night, but assuming there are no issues I'll go ahead and merge when it's done.

**Comment by arjan-s** [comment]
Result of `nixpkgs-review pr 262277` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by arjan-s** [comment]
Rebased to master, still builds fine for me without rebuilding anything.

**Comment by nrdxp** [comment]
> Rebased to master, still builds fine for me without rebuilding anything.

My build failed with OOM. I should have probably built it on my system with 64G, but in any case I'll go ahead and merge since you were successful. Thanks

**Pull request merged**
