### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by worldofpeace** [comment]
Woah, staging looks pretty small this time :smile:

**Comment by FRidh** [comment]
Yes, I thought the same! Gives us some time again to fix issues causes by the last merges :)

**Comment by FRidh** [comment]
Seems like `gtk3+` fails on Darwin 
```
Running custom install script '/nix/store/yr38li31bnlj14v38cwgl5s6fdgl3khh-meson-0.51.2/bin/meson --internal gettext install --subdir=po-properties --localedir=share/locale --pkgname=gtk30-properties'
Running custom install script '/nix/store/yr38li31bnlj14v38cwgl5s6fdgl3khh-meson-0.51.2/bin/meson --internal gtkdoc --sourcedir=/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12 --builddir=/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/build --subdir=docs/reference/gdk --headerdirs=/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/gdk/.@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/build/gdk/. --mainfile=gdk-docs.sgml --modulename=gdk3 --moduleversion= --mode=none --scanargs=--ignore-decorators=_GDK_EXTERN|G_GNUC_WARN_UNUSED_RESULT@@--ignore-headers=gdkintl.h gdkmarshalers.h gdkkeysyms.h gdkinternals.h gdkprivate.h gdk-private.h gdkapplaunchcontextprivate.h gdkcursorprivate.h gdkdevicemanagerprivate.h gdkdeviceprivate.h gdkdisplaymanagerprivate.h gdkdisplayprivate.h gdkdndprivate.h gdkframeclockprivate.h gdkglcontextprivate.h gdkkeysprivate.h gdkscreenprivate.h gdkseatdefaultprivate.h gdkseatprivate.h gdkvisualprivate.h keyname-table.h win32 x11 quartz broadway wayland --gobjects-types-file=/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/gdk3.types --fixxrefargs=--html-dir=/nix/store/69srancy8cslxmgmkfrgd65abqq30bl3-gtk+3-3.24.12/share/gtk-doc/html@@--extra-dir=/nix/store/r6x7pazw31b8y6zi05c3f8pg75n2adjh-glib-2.62.1/share/gtk-doc/html/glib@@--extra-dir=/nix/store/r6x7pazw31b8y6zi05c3f8pg75n2adjh-glib-2.62.1/share/gtk-doc/html/gobject@@--extra-dir=/nix/store/r6x7pazw31b8y6zi05c3f8pg75n2adjh-glib-2.62.1/share/gtk-doc/html/gio@@--extra-dir=/nix/store/bkclwsnlkzyrs89pgrlnn1fs2iwsrnmy-cairo-1.16.0/share/gtk-doc/html/cairo --html-assets=/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/rotated-text.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/X_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/arrow.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/based_arrow_down.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/based_arrow_up.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/boat.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/bogosity.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/bottom_left_corner.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/bottom_right_corner.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/bottom_side.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/bottom_tee.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/box_spiral.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/center_ptr.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/circle.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/clock.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/coffee_mug.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/cross.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/cross_reverse.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/crosshair.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/diamond_cross.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/dot.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/dotbox.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/double_arrow.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/draft_large.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/draft_small.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/draped_box.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/exchange.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/fleur.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/gobbler.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/gumby.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/hand1.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/hand2.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/heart.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/icon.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/iron_cross.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/left_ptr.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/left_side.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/left_tee.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/leftbutton.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/ll_angle.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/lr_angle.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/man.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/middlebutton.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/mouse.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/pencil.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/pirate.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/plus.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/question_arrow.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/right_ptr.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/right_side.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/right_tee.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/rightbutton.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/rtl_logo.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/sailboat.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/sb_down_arrow.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/sb_h_double_arrow.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/sb_left_arrow.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/sb_right_arrow.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/sb_up_arrow.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/sb_v_double_arrow.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/shuttle.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/sizing.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/spider.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/spraycan.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/star.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/target.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/tcross.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/top_left_arrow.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/top_left_corner.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/top_right_corner.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/top_side.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/top_tee.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/trek.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/ul_angle.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/umbrella.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/ur_angle.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/watch.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/xterm.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/alias_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/all_scroll_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/cell_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/col_resize_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/copy_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/crosshair_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/default_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/e_resize_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/ew_resize_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/grabbing_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/grab_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/hand_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/context_menu_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/help_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/move_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/ne_resize_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/nesw_resize_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/no_drop_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/not_allowed_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/n_resize_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/ns_resize_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/nw_resize_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/nwse_resize_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/pointer_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/progress_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/row_resize_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/se_resize_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/s_resize_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/sw_resize_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/text_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/vertical_text_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/wait_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/w_resize_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/X_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/zoom_in_cursor.png@@/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/docs/reference/gdk/images/zoom_out_cursor.png --content-files= --cc=/nix/store/1vnw05l6bz30whmiang9i3156c064y7d-clang-wrapper-7.1.0/bin/cc --ld=/nix/store/1vnw05l6bz30whmiang9i3156c064y7d-clang-wrapper-7.1.0/bin/cc --cflags=-I/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/build/. -I/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/. -I/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/build/gdk/x11 -I/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/gdk/x11 -I/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/build/gdk/. -I/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/gdk/. -I/nix/store/dl9nkrawjjhl7spbq6yjblrfp5vjw14x-glib-2.62.1-dev/include -I/nix/store/dl9nkrawjjhl7spbq6yjblrfp5vjw14x-glib-2.62.1-dev/include/glib-2.0 -I/nix/store/r6x7pazw31b8y6zi05c3f8pg75n2adjh-glib-2.62.1/lib/glib-2.0/include -I/nix/store/3iwcrs0bj7ca5hxw73vv8yqnzqcqrgng-gdk-pixbuf-2.40.0-dev/include/gdk-pixbuf-2.0 -I/nix/store/167kf7vjdzw4ljfzs0ljlnb1kmk7w04h-cairo-1.16.0-dev/include/cairo -I/nix/store/px68c54jxi8jlb8q6zvcvwvrlmrsw6ap-freetype-2.10.1-dev/include/freetype2 -I/nix/store/px68c54jxi8jlb8q6zvcvwvrlmrsw6ap-freetype-2.10.1-dev/include -I/nix/store/kr4xmhv6gib3vash1q2rxpq1rb056phn-pango-1.43.0-dev/include/pango-1.0 -I/nix/store/sgbrly7mlsrx25fnyjxws93dwvb2cs85-fribidi-1.0.7/include/fribidi -I/nix/store/inwb4688lzjn1mf6fwf1j27vmbx7gfgn-epoxy-1.5.3-dev/include -I/nix/store/dl9nkrawjjhl7spbq6yjblrfp5vjw14x-glib-2.62.1-dev/include/gio-unix-2.0 -DG_LOG_USE_STRUCTURED=1 -DGLIB_MIN_REQUIRED_VERSION=GLIB_VERSION_2_56 -DGLIB_MAX_ALLOWED_VERSION=GLIB_VERSION_2_58 \'-DGTK_VERSION="3.24.12"\' -D_GNU_SOURCE --ldflags=-L/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/build/gdk -Wl,-rpath,/private/tmp/nix-build-gtk+3-3.24.12.drv-0/gtk+-3.24.12/build/gdk -L/nix/store/bkclwsnlkzyrs89pgrlnn1fs2iwsrnmy-cairo-1.16.0/lib -Wl,-rpath,/nix/store/bkclwsnlkzyrs89pgrlnn1fs2iwsrnmy-cairo-1.16.0/lib -L/nix/store/sgbrly7mlsrx25fnyjxws93dwvb2cs85-fribidi-1.0.7/lib -Wl,-rpath,/nix/store/sgbrly7mlsrx25fnyjxws93dwvb2cs85-fribidi-1.0.7/lib -L/nix/store/r6x7pazw31b8y6zi05c3f8pg75n2adjh-glib-2.62.1/lib -Wl,-rpath,/nix/store/r6x7pazw31b8y6zi05c3f8pg75n2adjh-glib-2.62.1/lib -L/nix/store/4db3lfh1k1nbd2hi1g4xjjklzhd7pkn8-epoxy-1.5.3/lib -Wl,-rpath,/nix/store/4db3lfh1k1nbd2hi1g4xjjklzhd7pkn8-epoxy-1.5.3/lib -lgdk-3 -lm -L/nix/store/r6x7pazw31b8y6zi05c3f8pg75n2adjh-glib-2.62.1/lib -L/nix/store/wimkq8am2yz29np01dagmrllxmdjdn7l-gdk-pixbuf-2.40.0/lib -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -L/nix/store/bkclwsnlkzyrs89pgrlnn1fs2iwsrnmy-cairo-1.16.0/lib -lcairo -L/nix/store/x775228b19pch2wl89whbi3b7gydl8xb-pango-1.43.0/lib -lpango-1.0 -L/nix/store/sgbrly7mlsrx25fnyjxws93dwvb2cs85-fribidi-1.0.7/lib -lfribidi -lcairo-gobject -L/nix/store/4db3lfh1k1nbd2hi1g4xjjklzhd7pkn8-epoxy-1.5.3/lib -lepoxy -lgio-2.0 -lpangocairo-1.0 -framework CoreGraphics AppKit Cocoa Carbon'
FAILED: meson-install
/nix/store/yr38li31bnlj14v38cwgl5s6fdgl3khh-meson-0.51.2/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
builder for '/nix/store/wivlprhjgdqcv4r5igkb4xvja7fv8hsx-gtk+3-3.24.12.drv' failed with exit code 1
error: build of '/nix/store/wivlprhjgdqcv4r5igkb4xvja7fv8hsx-gtk+3-3.24.12.drv' failed
```

**Comment by worldofpeace** [comment]
It appears they don't build with gtk-doc in homebrew https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/gtk+3.rb, though blame on github isn't working so I can't be sure when it was introduced. Not sure I can fix it so I'll probably pr just having it for linux.

**Pull request merged**
