### PR TITLE
[20.09] chez-modules: Fix path to csv-site.

### PR DESCRIPTION
**Pull request by meithecatte**
###### Motivation for this change

backport of #97927 and #98128
ZHF: #97479

cc @NixOS/nixos-release-managers

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
  - `nixpkgs-review` seems to want to merge my branch with master before building the diffs. The changes were tested before backporting, though
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by cole-h — APPROVED** [review]
Diff LGTM.

```
[1 built, 6 copied (38.3 MiB), 10.0 MiB DL]
https://github.com/NixOS/nixpkgs/pull/98577
6 packages built:
chez chez-matchable chez-mit chez-scmutils chez-srfi idris2
```

**Review by r-burns — APPROVED** [review]
Built chez-* and idris2 on darwin

**Review by cole-h — CHANGES_REQUESTED** [review]
Something I missed in my review last night:

Please cherry-pick these commits from the master branch (for reference, see https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#backporting-changes; start from step 4). Once that is done, my approval stands.

**Comment by NieDzejkob** [comment]
@cole-h Sorry, I have missed the `-x` flag before. PTAL.

**Review by cole-h — APPROVED** [review]
Much better, thanks. Should be good to go!

**Review by thoughtpolice — APPROVED** [review]

**Comment by thoughtpolice** [comment]
Sorry for the wait, thanks!

**Pull request merged**
