### PR TITLE
beekeeper-studio: 3.3.8 -> 3.4.3, cross platform

### PR DESCRIPTION
**Pull request by milogert**
###### Description of changes

Bumped version from 3.3.8 to 3.4.3 and also made it cross platform. I don't have access to an M1 Mac, so I can't test out the darwin-aarch64 changes that are commented out. If nobody can/wants to test them I'll just remove the comments.

Changelog list since last version:

- https://github.com/beekeeper-studio/beekeeper-studio/releases/tag/v3.4.3
- https://github.com/beekeeper-studio/beekeeper-studio/releases/tag/v3.4.2
- https://github.com/beekeeper-studio/beekeeper-studio/releases/tag/v3.4.1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Alexnortung** [comment]
Built on `x86-64` works as expected.

**Comment by siriobalmelli** [comment]
Result of `nixpkgs-review pr 177655` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>beekeeper-studio</li>
  </ul>
</details>

**Comment by onny** [comment]
Result of `nixpkgs-review pr 177655` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>beekeeper-studio</li>
  </ul>
</details>

**Comment by onny** [comment]
Nice work, thank you! Is it possible to get rid of the duplicate binary in `/bin`?
```
[nix-shell:~/.cache/nixpkgs-review/pr-177655]$ ls ./results/beekeeper-studio/bin/ -la
total 8
dr-xr-xr-x 1 root root 76 Jan  1  1970 .
dr-xr-xr-x 1 root root 16 Jan  1  1970 ..
lrwxrwxrwx 2 root root 93 Jan  1  1970 beekeeper-studio -> /nix/store/s0j6288hy6dp1zfprzdrjw9nbwhahhyq-beekeeper-studio-3.4.3/bin/beekeeper-studio-3.4.3
lrwxrwxrwx 2 root root 93 Jan  1  1970 beekeeper-studio-3.4.3 -> /nix/store/1c3mm3pmf7a3223nrkmf273kl1zppvc0-beekeeper-studio-3.4.3/bin/beekeeper-studio-3.4.3
```
Maybe you can ping someone with darin-aarch64 to test this :)

**Comment by wegank** [comment]
`beekeeper-studio` is at 4.1.13 on master, please open a new PR to resolve merge conflicts.

**Comment by wegank** [comment]
`beekeeper-studio` is at 4.1.13 on master, please open a new PR to resolve merge conflicts.

**Pull request closed without merging**
