### PR TITLE
vimPlugins: generated.nix as an overlay

### PR DESCRIPTION
**Pull request by teto**
let update.py generates generated.nix as an overlay.
This should help maintaining vim-plugins outside of nixpkgs.

I have several additionnal vim plugins in my nixpkgs checkout that often cause problems when rebasing. Thus I want to maintain these vim plugins in an overlay.
I use `	~/nixpkgs/pkgs/misc/vim-plugins/update.py -i config/nixpkgs/overlays/vim-plugins/vim-plugin-names -o config/nixpkgs/overlays/vim-plugins/generated.nix`

with config/nixpkgs/overlays/vim-plugins.nix
```
self: super:
rec {

  inherit (super.vimUtils.override {inherit (super) vim;}) buildVimPluginFrom2Nix;

  generated = super.callPackage ./vim-plugins/generated.nix { 
    inherit buildVimPluginFrom2Nix;
  };
  vimPlugins = super.vimPlugins.extend( generated );
}
```

for some reason aliases stop working.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

**Comment by grahamc** [comment]
Would you mind rebasing this branch on to master? That will clear the `ofborg-internal-error` error, now that I fixed the bug I was seeing while evaluating this PR.

**Comment by teto** [comment]
finally, I've carried this in my fork and it has made every rebase slightly more painful so looking forward to seeing this merged :)

**Comment by teto** [comment]
cc @Mic92 too

**Review by jonringer — APPROVED** [review]
Agree with in principle.

Please address conflicts

**Comment by Mic92** [comment]
Can you document the overlay approach in the vim manual?

**Comment by teto** [comment]
I've added some logging feature ( `update.py --debug INFO`) 'cos update.py sometimes fail and it's not straightforward to know what plugin triggered the failure.

**Comment by teto** [comment]
Going ahead to avoid countless rebasing. I will update the manual once nix stops crashing.

**Comment by Mic92** [comment]
> I think the following overlay should work
> 
> ```
> final: prev: {
>           vimPlugins = prev.vimPlugins.extend (
>             final2: prev2: {
>               octo-nvim = prev.buildVimPluginFrom2Nix {
>                 pname = "octo-nvim";
>                 version = "2021-05-06";
>                 src = prev.fetchFromGitHub {
>                   owner = "pwntester";
>                   repo = "octo.nvim";
>                   rev = "d92a7352516f06a457cbf8812b173abc319f7882";
>                   sha256 = "1xvj3p32nzcn8rv2hscmj8sn8bfm1s2r5j1cwwnkl4zbqdbd4k5f";
>                 };
>                 meta.homepage = "https://github.com/pwntester/octo.nvim/";
>               };
>             }
> 
>           );
>         };
> ```
> 
> but as soon as I uncomment it nix crashes:
> `/run/current-system/sw/bin/nixos-rebuild: line 474: 2329477 Segmentation fault (core dumped) nix "${flakeFlags[@]}" build "$flake#$flakeAttr.config.system.build.toplevel" "${extraBuildFlags[@]}" "${lockFlags[@]}"`.
> So I would be tempted to merge now and I will add the doc once those crashes go away ?

Maybe a stackoverflow (because of infinite recursion)?

**Comment by teto** [comment]
@Mic92 it works now, I've opened https://github.com/NixOS/nixpkgs/pull/126633

**Pull request merged**
