### PR TITLE
Add zoom-us package: nonfree zoom.us client

### PR DESCRIPTION
**Pull request by k0001**
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [x] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @steveeJ

**Comment by grahamc** [comment]
Running locally, I get:

```
➜  nixpkgs git:(6eb7a49) ✗ ./result/bin/zoom-us                                                               ~/projects/nixpkgs
pmap: argument missing
[CZPClientLogMgr::LogClientEnvironment] [MacAddr: 78:31:C1:BC:8A:DC][client: Linux][OS: NixOS 16.03.759.b10f61b (Emu)][Hardware: CPU Core:8 Frenquency:3.60638 G Memory size:15961MB CPU Brand:Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz][Req ID: ]
Linux Client Version is 2.0.49177.0430
Graphics Card Info:: 01:00.0 VGA compatible controller: NVIDIA Corporation GK107M [GeForce GT 750M Mac Edition] (rev a1)
pmap: argument missing
pmap: argument missing
pmap: argument missing
```

and then those last lines repeat forever.

**Comment by k0001** [comment]
I get the "pmap: argument missing" message too, but that doesn't prevent
the program from running. I am able to join calls, microphone works and
webcam too. Isn't it working for you?

**Comment by grahamc** [comment]
Well I was going to test it but then found my facetimehd camera isn't working :) https://github.com/NixOS/nixpkgs/pull/15708 I need to register an account to try it. I have a meeting scheduled with Zoom tomorrow though, so I'm particularly interested in testing it now.

**Comment by grahamc** [comment]
It worked a treat. +1 the merge, backporting would be nice too, but I hear we tend to not backport new stuff to stable.

**Comment by steveeJ** [comment]
Thanks for this @k0001, would you mind rebasing this so it's easier to test?

**Comment by grahamc** [comment]
@steveeJ just to try and help move this along, I rebased it here: https://github.com/NixOS/nixpkgs/compare/master...grahamc:zoom-us-rebase (note I'm not the author of this PR)

**Comment by k0001** [comment]
@steveeJ I updated my `nixpkgs` and I am now a bit stuck here with a completely unrelated error, so I won't be touching this right away. If @grahamc wants to send a new pull-request with his rebase, that is fine by me, otherwise I'll continue working on this on the next couple of days.

**Comment by k0001** [comment]
Ah, nevermind, I just solved the problem I was having. I'll update this shortly.

**Comment by k0001** [comment]
@steveeJ this has been rebased now.

**Comment by grahamc** [comment]
So unfortunately it has bit-rotted, the upstream has changed. This diff makes it build:

```diff
diff --git a/pkgs/applications/networking/instant-messengers/zoom-us/default.nix b/pkgs/applications/networking/instant-messengers/zoom-us/default.nix
index 7b30399..7f4a27c 100644
--- a/pkgs/applications/networking/instant-messengers/zoom-us/default.nix
+++ b/pkgs/applications/networking/instant-messengers/zoom-us/default.nix
@@ -27,10 +27,10 @@ stdenv.mkDerivation rec {
       platforms = stdenv.lib.platforms.linux;
     };
 
-    version = "2.0.49177.0430";
+    version = "2.0.52458.0531";
     src = fetchurl {
       url = "https://zoom.us/client/latest/zoom_${version}_x86_64.tar.xz";
-      sha256 = "107qjvhfxaii5pz4x1j6452822c5hwmladgilwd9icl8nk9a2c9p";
+      sha256 = "16d64pn9j27v3fnh4c9i32vpkr10q1yr26w14964n0af1mv5jf7a";
     };
 
     phases = [ "unpackPhase" "installPhase" ];
```

**Comment by k0001** [comment]
Rebased this against `master` and updated the package version.

**Comment by domenkozar** [comment]
@steveeJ does this work?

**Comment by steveeJ** [comment]
@domenkozar The GUI will open and I can connect to a meeting. It picked up sound but the video window was black, even though the LED next to my camera was active. It's definitely a good start and I will test it in a real meeting soon. I think we should merge it.

**Comment by k0001** [comment]
@steveeJ @domenkozar I've been using this for a month or so, both video and audio are working for me.

**Comment by domenkozar** [comment]
Cool, merging then. Thanks!

**Pull request merged**
