### PR TITLE
bibtex-tidy: init at 1.8.5

### PR DESCRIPTION
**Pull request by bertof**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Added package definition in node packages and linked to top-level.
Built and tested manually on NixOS x86_64-linux and aarch64-linux.

### CODE REVIEW

**Comment by msm-code** [comment]
Result of `nixpkgs-review pr 213590` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>bibtex-tidy</li>
  </ul>
</details>

**Review by msm-code — APPROVED** [review]
Builds successfully. I've tested using commands from the project README:

image

and it seems to work

**Comment by NickCao** [comment]
I'm a bit confused, `pkgs/applications/office/bibtex-tidy/default.nix` seems to be used nowhere?

**Comment by bertof** [comment]
Indeed you are right. I first tried with a complete derivation and later found out how all the `nodePackages` derivations are organized. I forgot to remove the old file. Let me fix that.

**Comment by NickCao** [comment]
Also `pkgs/development/node-packages/node-packages.nix` is automatically generated, see `pkgs/development/node-packages/README.md` for instructions.

**Comment by NickCao** [comment]
Still does not look correct, you should add the desired package to `pkgs/development/node-packages/node-packages.json`, then run `pkgs/development/node-packages/generate.sh` to update `pkgs/development/node-packages/node-packages.nix`

**Comment by bertof** [comment]
Sorry, the node2nix took ages to complete and I first updated the commit to remove the first wrong attempt and forgot to set it as draft.

I didn't know about the auto-generation file. Looking for the documentation on Google I could only find old examples for development environments. I updated the PR with the corrected changes.

From what I understood from the docs, I should also include the updated `node-packages.nix`. Correct?

**Comment by NickCao** [comment]
Yes.

**Comment by bertof** [comment]
Ok, thanks for the help. Now it should be correct. The updater script introduced lots of changes tho. Shouldn't the `node-packages.nix` file be already updated? I used an updated master branch for the PR.

**Comment by NickCao** [comment]
It's seldomly updated on purpose, but as a side effect of PRs like this one.

**Review by NickCao — APPROVED** [review]
Result of `nixpkgs-review pr 213590` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>breitbandmessung</li>
    <li>teleprompter</li>
    <li>whalebird</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>flexoptix-app</li>
  </ul>
</details>
<details>
  <summary>71 packages built:</summary>
  <ul>
    <li>antennas</li>
    <li>balanceofsatoshis</li>
    <li>bibtex-tidy</li>
    <li>bitwarden-cli</li>
    <li>castnow</li>
    <li>code-server</li>
    <li>commitlint</li>
    <li>concurrently</li>
    <li>create-cycle-app</li>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>emanote</li>
    <li>epgstation</li>
    <li>fast-cli</li>
    <li>gnomeExtensions.pop-shell</li>
    <li>google-clasp</li>
    <li>grafana-image-renderer</li>
    <li>gtop</li>
    <li>haskellPackages.aeson-typescript</li>
    <li>haskellPackages.emanote</li>
    <li>haskellPackages.servant-typescript</li>
    <li>haskellPackages.tailwind</li>
    <li>imgbrd-grabber</li>
    <li>joplin</li>
    <li>lighthouse</li>
    <li>morgen</li>
    <li>node2nix</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pulp</li>
    <li>pyright</li>
    <li>quarto</li>
    <li>redoc-cli</li>
    <li>reveal-md</li>
    <li>shepherd</li>
    <li>shout</li>
    <li>slack</li>
    <li>teams</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.plugins.giphy</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
    <li>thelounge</li>
    <li>typescript</li>
    <li>uppy-companion</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.coc-clangd</li>
    <li>vimPlugins.coc-diagnostic</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-html</li>
    <li>vimPlugins.coc-java</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-nginx</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-toml</li>
    <li>vimPlugins.coc-tsserver</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vscode</li>
    <li>vscode-extensions.matklad.rust-analyzer (vscode-extensions.rust-lang.rust-analyzer)</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-fhs</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
    <li>vscodium-fhs</li>
    <li>wasm-text-gen</li>
    <li>weylus</li>
    <li>wrangler</li>
    <li>ycmd</li>
    <li>zx</li>
  </ul>
</details>

**Comment by winterqt** [comment]
Ideally, this should have been (attempted to be) packaged with `buildNpmPackage` before being added to the set, as this project uses npm.

Can you try to do so? Docs are [here](https://nixos.org/manual/nixpkgs/unstable/#javascript-buildNpmPackage).

**Comment by NickCao** [comment]
It was originally done with `buildNpmPackage`, only later added to the set.

**Comment by winterqt** [comment]
Why?

**Comment by NickCao** [comment]
Maybe no particular reason? See https://github.com/NixOS/nixpkgs/pull/213590#issuecomment-1411542491

**Comment by winterqt** [comment]
Yeah, it looks like there was no reason. Sorry, thought this was in a different PR.

@NickCao Sorry for the adhoc-ness of this all, but for the future, `buildNpmPackage` is very much preferred when possible. I assume the docs misled the author into thinking that nodePackages should be used, since that comment doesn't say anything about a reason. 😰

**Comment by bertof** [comment]
@winterqt Hi, I've seen 3 solution being used for NPM based projects:
- `buildNpmPackage` which is mentioned first in the docs and is being used 40+ times (currently) in this repo
- `node2nix` which seems to be used for 15 packages
- the generated file that NickCao suggested, which is used by 406 packages

The stable manual does not mention a preferred solution, as far as I can tell.
The unstable manual seem to suggest [the solution i used is the preferred one](https://nixos.org/manual/nixpkgs/unstable/#id-1.5.8.22.6.10).

What exactly is the preferred solution? This app in particular has no dependencies and is easy to package either way, but the documentation on best practices is kind of lacking.

**Pull request merged**
