### PR TITLE
jetbrains: 2022.3.2 -> 2022.3.3

### PR DESCRIPTION
**Pull request by x418**
###### Description of changes

Bug-fix-update: https://blog.jetbrains.com/idea/2023/03/intellij-idea-2022-3-3-2/

Followed the [Submitting Changes](https://nixos.org/manual/nixpkgs/stable/#chap-submitting-changes) guidelines. Versions were updated using `update.py`

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by qbit** [comment]
Result of `nixpkgs-review pr 220285` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>jetbrains.idea-community</li>
    <li>jetbrains.idea-ultimate</li>
  </ul>
</details>

**Comment by qbit** [comment]
Getting different hashes now:

```
error: hash mismatch in fixed-output derivation '/nix/store/aj0aqc0sf9cbs9x70057hv142j872g40-ideaIC-2022.3.3.tar.gz.drv':
         specified: sha256-5agl0Miwmij9zkW0PC0smb8CJF8oyYxN8fxanZJGO9k=
            got:    sha256-aZSS+1qd51AlD9qtyl/JISEU7kRaUIdbWbvJnwGHwuQ=
error: 1 dependencies of derivation '/nix/store/50zv4z56gs0gww9skpl32b9qzwa8v6fb-idea-community-2022.3.3.drv' failed to build
error: hash mismatch in fixed-output derivation '/nix/store/5w62q1fzhrryri0ja52jb0aah28hins4-ideaIU-2022.3.3.tar.gz.drv':
         specified: sha256-ARAmJ6SsF2ScyDrIMDZvhP4xR831bz3gSiK0m/rc/z8=
            got:    sha256-wwK9hLSKVu8bDwM+jpOg2lWQ+ASC6uFy22Ew2gNTFKY=
error: 1 dependencies of derivation '/nix/store/ay5ry54373nlhhb205n8sv6s1872b6jy-idea-ultimate-2022.3.3.drv' failed to build
error: 2 dependencies of derivation '/nix/store/7q1h3lc3hs5qsz68a6kj3cdh4wxjz9wp-review-shell.drv' failed to build
```

**Comment by qbit** [comment]
Result of `nixpkgs-review pr 220285` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>jetbrains.clion</li>
    <li>jetbrains.goland</li>
    <li>jetbrains.idea-community</li>
    <li>jetbrains.idea-ultimate</li>
    <li>jetbrains.pycharm-community</li>
    <li>jetbrains.pycharm-professional</li>
    <li>jetbrains.ruby-mine</li>
    <li>jetbrains.webstorm</li>
  </ul>
</details>

**Review by qbit — APPROVED** [review]

**Comment by qbit** [comment]
idea-ultimate and goland working as expected for me!

**Review by stepech — APPROVED** [review]

**Comment by stepech** [comment]
Is there someone who can review this? :sweat_smile:

**Pull request merged**
