### PR TITLE
buildDotnetModule: point fetch-deps at module's deps file by default

### PR DESCRIPTION
**Pull request by Atemu**
Previously, you had to provide the path to the deps.nix of the package inside your Nixpkgs checkout as an argument manually. Now it just does that by default when no argument is passed.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by corngood — APPROVED** [review]

**Comment by corngood** [comment]
I was working on something similar here: https://github.com/corngood/nixpkgs/commit/0a1b9030a1c6acd3d3e970bde173820080e9c145

Some of it may be useful, as it has doc updates, deals with github-runner, removes the args from the various update scripts and adds a script for updating all packages.

The only TODO I had was that there's at least one package that doesn't directly reference a file in `nugetDeps`.  I think you covered that in your implementation.

**Comment by Atemu** [comment]
That looks great too but I'm not motivated enough to follow through on that. I just wanted the update process to be a little more convenient ;)

**Comment by DavHau** [comment]
This broke the initialization workflow where `nugetDeps = null`. It will now always raise the error that nugetDeps is not defined introducing a chicken egg problem.

Maybe just revert for now?

**Comment by Atemu** [comment]
Could you post the exact error? If `nugetDeps = null;`, `lib.isPath` should return false and a tmpdir should be used.

**Pull request merged**
