### PR TITLE
remove maintainers dockerfile

### LINKED ISSUE #14863: Is the Dockerfile still necessary?
I'm talking about https://github.com/NixOS/nixpkgs/blob/master/maintainers/docker/Dockerfile. It doesn't look like anyone's touched it in a while (it's using Nix 1.7) so my guess is that it's mostly bitrotted and won't work. Should we just delete it?

### PR DESCRIPTION
**Pull request by langston-barrett**
###### Motivation for this change

I'm not 100% on if this is necessary, but a few of the maintainers seem to think it'd be good, so I figured I'd help out!

fixes #14863
###### Things done
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by domenkozar** [comment]
This is what is used to build https://hub.docker.com/r/nixos/nixpkgs/, we should rethink if we need it or not.

**Comment by siddharthist** [comment]
@domenkozar Feel free to close this if you don't need it!

**Comment by bennofs** [comment]
@NixOS/nixpkgs-committers does anyone use this docker file or can it be removed?

**Comment by pSub** [comment]
I haven't used it so far and don't intend to do so.

**Comment by grahamc** [comment]
Let's document that it is used to update the docker registry ( in the
dockerfile ?) and close both issues because the answer is yes: we do use
it.

**Comment by LnL7** [comment]
I created an alternative for this image that builds from scratch (instead of busybox) in case people are interrested. https://github.com/LnL7/nix-docker

**Comment by garbas** [comment]
@LnL7 any particular reason you're not using ``dockerTools.buildImage``?

**Comment by LnL7** [comment]
I had issues with `readline` when using the docker tools.
This image also does not have any global paths apart from `/bin/sh` and `/usr/bin/env`, just like nixos.

**Comment by joachifm** [comment]
Closing, as it seems the file *is* indeed used.

**Pull request closed without merging**
