### PR TITLE
ocamlPackages.opam-file-format: 2.0.0 -> 2.1.2

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

Fixed Version of #102671

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build opaline ocamlPackages.opam-format ocamlPackages.opam-repository dune-release

**Review by vbgl — COMMENTED** [review]
Are the “use dune 2” commit in the right order? (I mean are intermediate state not broken?) If you don’t care about the intermediate states, please just squash all commits into one.

**Comment by sternenseemann** [comment]
I've rebased the commits to prevent the broken state you pointed out and also switched to `substituteInPlace` which is cleaner here, I agree.

**Comment by vbgl** [comment]
I guess this will be much easier to review after #106150 has been merged.

**Comment by vbgl** [comment]
Merged two commits from this PR into master: 04cbb60e6298a8def8a695ca085f7b182d651d55 & 69e614e77f6a7412f882424c6c5d376357e163ef.

**Comment by vbgl** [comment]
The `opam-file-format` is used in `opaline` which is still used (directly or indirectly) in thousands of packages. So this needs careful testing…

**Comment by sternenseemann** [comment]
Might be worth to wait for the next release which should come shortly: <https://github.com/ocaml/opam-file-format/pull/36#issuecomment-747703848>

Upstream is now going a different direction with the fix than my fix in this package: <https://github.com/ocaml/opam-file-format/pull/37>

**Comment by vbgl** [comment]
Sounds good. Thanks.

**Comment by sternenseemann** [comment]
Okay unfortunately 2.1.2 did not fix the issue, I'll see what I can find out.

**Comment by sternenseemann** [comment]
Updated to 2.1.2 and applied the relevant change from <https://github.com/ocaml/opam-file-format/pull/41> as a patch. `opaline` builds again without any spurious messing around in the `Makefile`.

**Comment by sternenseemann** [comment]
@ofborg build opaline

**Comment by sternenseemann** [comment]
@ofborg eval

**Comment by sternenseemann** [comment]
Result of `nixpkgs-review pr 106107` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>dune-release</li>
    <li>ocamlPackages.genspio</li>
    <li>ocamlPackages.irmin-http</li>
    <li>ocamlPackages.irmin-unix</li>
    <li>ocamlPackages.nonstd</li>
    <li>ocamlPackages.sosa</li>
  </ul>
</details>
<details>
  <summary>549 packages built:</summary>
  <ul>
    <li>acgtk</li>
    <li>alt-ergo</li>
    <li>beluga</li>
    <li>compcert</li>
    <li>coq (coqPackages.coq ,coq_8_11)</li>
    <li>coqPackages.Cheerios</li>
    <li>coqPackages.CoLoR</li>
    <li>coqPackages.InfSeqExt</li>
    <li>coqPackages.QuickChick</li>
    <li>coqPackages.StructTact</li>
    <li>coqPackages.VST</li>
    <li>coqPackages.Verdi</li>
    <li>coqPackages.bignums</li>
    <li>coqPackages.contribs.zorns-lemma</li>
    <li>coqPackages.coq-bits</li>
    <li>coqPackages.coq-elpi</li>
    <li>coqPackages.coq-ext-lib</li>
    <li>coqPackages.coqeal</li>
    <li>coqPackages.coqhammer</li>
    <li>coqPackages.coqprime</li>
    <li>coqPackages.coquelicot</li>
    <li>coqPackages.dpdgraph</li>
    <li>coqPackages.equations</li>
    <li>coqPackages.flocq</li>
    <li>coqPackages.gappalib</li>
    <li>coqPackages.hierarchy-builder</li>
    <li>coqPackages.interval</li>
    <li>coqPackages.iris</li>
    <li>coqPackages.math-classes</li>
    <li>coqPackages.mathcomp</li>
    <li>coqPackages.mathcomp-algebra</li>
    <li>coqPackages.mathcomp-analysis</li>
    <li>coqPackages.mathcomp-bigenough</li>
    <li>coqPackages.mathcomp-character</li>
    <li>coqPackages.mathcomp-field</li>
    <li>coqPackages.mathcomp-fingroup</li>
    <li>coqPackages.mathcomp-finmap</li>
    <li>coqPackages.mathcomp-real-closed</li>
    <li>coqPackages.mathcomp-solvable</li>
    <li>coqPackages.ssreflect (coqPackages.mathcomp-ssreflect)</li>
    <li>coqPackages.metalib</li>
    <li>coqPackages.multinomials</li>
    <li>coqPackages.paco</li>
    <li>coqPackages.paramcoq</li>
    <li>coqPackages.simple-io</li>
    <li>coqPackages.stdpp</li>
    <li>coqPackages.tlc</li>
    <li>coq_8_10</li>
    <li>coq_8_12</li>
    <li>coq_8_13</li>
    <li>dot-merlin-reader</li>
    <li>dune (jbuilder)</li>
    <li>eff</li>
    <li>flow</li>
    <li>framac</li>
    <li>fstar</li>
    <li>google-drive-ocamlfuse</li>
    <li>jackline</li>
    <li>libbap</li>
    <li>libguestfs</li>
    <li>libguestfs-with-appliance</li>
    <li>liquidsoap</li>
    <li>obelisk</li>
    <li>ocaml-crunch</li>
    <li>ocaml-top</li>
    <li>ocamlPackages.accessor</li>
    <li>ocamlPackages.accessor_async</li>
    <li>ocamlPackages.accessor_base</li>
    <li>ocamlPackages.accessor_core</li>
    <li>ocamlPackages.afl-persistent</li>
    <li>ocamlPackages.alcotest</li>
    <li>ocamlPackages.alcotest-lwt</li>
    <li>ocamlPackages.angstrom</li>
    <li>ocamlPackages.angstrom-async</li>
    <li>ocamlPackages.angstrom-lwt-unix</li>
    <li>ocamlPackages.angstrom-unix</li>
    <li>ocamlPackages.arp</li>
    <li>ocamlPackages.asn1-combinators</li>
    <li>ocamlPackages.astring</li>
    <li>ocamlPackages.async</li>
    <li>ocamlPackages.async_extra</li>
    <li>ocamlPackages.async_find</li>
    <li>ocamlPackages.async_inotify</li>
    <li>ocamlPackages.async_interactive</li>
    <li>ocamlPackages.async_js</li>
    <li>ocamlPackages.async_kernel</li>
    <li>ocamlPackages.async_rpc_kernel</li>
    <li>ocamlPackages.async_sendfile</li>
    <li>ocamlPackages.async_shell</li>
    <li>ocamlPackages.async_smtp</li>
    <li>ocamlPackages.async_ssl</li>
    <li>ocamlPackages.async_unix</li>
    <li>ocamlPackages.atd</li>
    <li>ocamlPackages.atdgen</li>
    <li>ocamlPackages.base</li>
    <li>ocamlPackages.base64</li>
    <li>ocamlPackages.base_bigstring</li>
    <li>ocamlPackages.base_quickcheck</li>
    <li>ocamlPackages.batteries</li>
    <li>ocamlPackages.bigarray-compat</li>
    <li>ocamlPackages.bigarray-overlap</li>
    <li>ocamlPackages.bignum</li>
    <li>ocamlPackages.bigstring</li>
    <li>ocamlPackages.bigstringaf</li>
    <li>ocamlPackages.bin_prot</li>
    <li>ocamlPackages.biniou</li>
    <li>ocamlPackages.biocaml</li>
    <li>ocamlPackages.bisect_ppx</li>
    <li>ocamlPackages.bistro</li>
    <li>ocamlPackages.bitstring</li>
    <li>ocamlPackages.bonsai</li>
    <li>ocamlPackages.bos</li>
    <li>ocamlPackages.ca-certs</li>
    <li>ocamlPackages.cairo2</li>
    <li>ocamlPackages.camlimages</li>
    <li>ocamlPackages.camomile</li>
    <li>ocamlPackages.cfstream</li>
    <li>ocamlPackages.charInfo_width</li>
    <li>ocamlPackages.checkseum</li>
    <li>ocamlPackages.cinaps</li>
    <li>ocamlPackages.cmdliner</li>
    <li>ocamlPackages.cohttp</li>
    <li>ocamlPackages.cohttp-async</li>
    <li>ocamlPackages.cohttp-lwt</li>
    <li>ocamlPackages.cohttp-lwt-unix</li>
    <li>ocamlPackages.conduit</li>
    <li>ocamlPackages.conduit-async</li>
    <li>ocamlPackages.conduit-lwt</li>
    <li>ocamlPackages.conduit-lwt-unix</li>
    <li>ocamlPackages.containers</li>
    <li>ocamlPackages.containers-data</li>
    <li>ocamlPackages.core</li>
    <li>ocamlPackages.core_bench</li>
    <li>ocamlPackages.core_extended</li>
    <li>ocamlPackages.core_kernel</li>
    <li>ocamlPackages.cow</li>
    <li>ocamlPackages.cpu</li>
    <li>ocamlPackages.cpuid</li>
    <li>ocamlPackages.crowbar</li>
    <li>ocamlPackages.crunch</li>
    <li>ocamlPackages.cryptokit</li>
    <li>ocamlPackages.csexp</li>
    <li>ocamlPackages.cstruct</li>
    <li>ocamlPackages.cstruct-lwt</li>
    <li>ocamlPackages.cstruct-sexp</li>
    <li>ocamlPackages.cstruct-unix</li>
    <li>ocamlPackages.csv-lwt</li>
    <li>ocamlPackages.csvfields</li>
    <li>ocamlPackages.ctypes</li>
    <li>ocamlPackages.curly</li>
    <li>ocamlPackages.decompress</li>
    <li>ocamlPackages.delimited_parsing</li>
    <li>ocamlPackages.diet</li>
    <li>ocamlPackages.digestif</li>
    <li>ocamlPackages.dispatch</li>
    <li>ocamlPackages.dns</li>
    <li>ocamlPackages.dns-certify</li>
    <li>ocamlPackages.dns-cli</li>
    <li>ocamlPackages.dns-client</li>
    <li>ocamlPackages.dns-mirage</li>
    <li>ocamlPackages.dns-resolver</li>
    <li>ocamlPackages.dns-server</li>
    <li>ocamlPackages.dns-stub</li>
    <li>ocamlPackages.dns-tsig</li>
    <li>ocamlPackages.domain-name</li>
    <li>ocamlPackages.dtoa</li>
    <li>ocamlPackages.duff</li>
    <li>ocamlPackages.dune-configurator</li>
    <li>ocamlPackages.duration</li>
    <li>ocamlPackages.earley</li>
    <li>ocamlPackages.ecaml</li>
    <li>ocamlPackages.eigen</li>
    <li>ocamlPackages.eliom</li>
    <li>ocamlPackages.elpi</li>
    <li>ocamlPackages.email_message</li>
    <li>ocamlPackages.encore</li>
    <li>ocamlPackages.eqaf</li>
    <li>ocamlPackages.ethernet</li>
    <li>ocamlPackages.expect_test_helpers_async</li>
    <li>ocamlPackages.expect_test_helpers_core</li>
    <li>ocamlPackages.ezjsonm</li>
    <li>ocamlPackages.ezxmlm</li>
    <li>ocamlPackages.facile</li>
    <li>ocamlPackages.faraday</li>
    <li>ocamlPackages.farfadet</li>
    <li>ocamlPackages.fdkaac</li>
    <li>ocamlPackages.fiat-p256</li>
    <li>ocamlPackages.fieldslib</li>
    <li>ocamlPackages.fileutils</li>
    <li>ocamlPackages.fmt</li>
    <li>ocamlPackages.fpath</li>
    <li>ocamlPackages.functoria</li>
    <li>ocamlPackages.functoria-runtime</li>
    <li>ocamlPackages.gapi_ocaml</li>
    <li>ocamlPackages.gen</li>
    <li>ocamlPackages.gettext-stub</li>
    <li>ocamlPackages.gg</li>
    <li>ocamlPackages.git</li>
    <li>ocamlPackages.git-http</li>
    <li>ocamlPackages.git-unix</li>
    <li>ocamlPackages.gmap</li>
    <li>ocamlPackages.gnuplot</li>
    <li>ocamlPackages.graphics</li>
    <li>ocamlPackages.graphql</li>
    <li>ocamlPackages.graphql-cohttp</li>
    <li>ocamlPackages.graphql-lwt</li>
    <li>ocamlPackages.graphql_parser</li>
    <li>ocamlPackages.graphql_ppx</li>
    <li>ocamlPackages.gsl</li>
    <li>ocamlPackages.hacl_x25519</li>
    <li>ocamlPackages.hex</li>
    <li>ocamlPackages.hidapi</li>
    <li>ocamlPackages.higher_kinded</li>
    <li>ocamlPackages.hkdf</li>
    <li>ocamlPackages.hmap</li>
    <li>ocamlPackages.httpaf</li>
    <li>ocamlPackages.imagelib</li>
    <li>ocamlPackages.imagelib-unix</li>
    <li>ocamlPackages.incr_dom</li>
    <li>ocamlPackages.incr_map</li>
    <li>ocamlPackages.incr_select</li>
    <li>ocamlPackages.incremental</li>
    <li>ocamlPackages.index</li>
    <li>ocamlPackages.inotify</li>
    <li>ocamlPackages.integers</li>
    <li>ocamlPackages.io-page</li>
    <li>ocamlPackages.io-page-unix</li>
    <li>ocamlPackages.ipaddr</li>
    <li>ocamlPackages.ipaddr-cstruct</li>
    <li>ocamlPackages.ipaddr-sexp</li>
    <li>ocamlPackages.iri</li>
    <li>ocamlPackages.irmin</li>
    <li>ocamlPackages.irmin-chunk</li>
    <li>ocamlPackages.irmin-fs</li>
    <li>ocamlPackages.irmin-git</li>
    <li>ocamlPackages.irmin-graphql</li>
    <li>ocamlPackages.irmin-mem</li>
    <li>ocamlPackages.irmin-pack</li>
    <li>ocamlPackages.irmin-test</li>
    <li>ocamlPackages.irmin-watcher</li>
    <li>ocamlPackages.iter</li>
    <li>ocamlPackages.jingoo</li>
    <li>ocamlPackages.js_of_ocaml</li>
    <li>ocamlPackages.js_of_ocaml-compiler</li>
    <li>ocamlPackages.js_of_ocaml-lwt</li>
    <li>ocamlPackages.js_of_ocaml-ppx</li>
    <li>ocamlPackages.js_of_ocaml-ppx_deriving_json</li>
    <li>ocamlPackages.js_of_ocaml-tyxml</li>
    <li>ocamlPackages.jsonm</li>
    <li>ocamlPackages.jst-config</li>
    <li>ocamlPackages.jwto</li>
    <li>ocamlPackages.kafka</li>
    <li>ocamlPackages.ke</li>
    <li>ocamlPackages.lablgtk3</li>
    <li>ocamlPackages.lablgtk3-gtkspell3</li>
    <li>ocamlPackages.lablgtk3-sourceview3</li>
    <li>ocamlPackages.lacaml</li>
    <li>ocamlPackages.lambdaTerm</li>
    <li>ocamlPackages.lambdasoup</li>
    <li>ocamlPackages.linenoise</li>
    <li>ocamlPackages.llvm</li>
    <li>ocamlPackages.logs</li>
    <li>ocamlPackages.lru</li>
    <li>ocamlPackages.lua-ml</li>
    <li>ocamlPackages.lwt</li>
    <li>ocamlPackages.lwt-dllist</li>
    <li>ocamlPackages.lwt_log</li>
    <li>ocamlPackages.lwt_ppx</li>
    <li>ocamlPackages.lwt_react</li>
    <li>ocamlPackages.lwt_ssl</li>
    <li>ocamlPackages.macaddr</li>
    <li>ocamlPackages.macaddr-cstruct</li>
    <li>ocamlPackages.macaddr-sexp</li>
    <li>ocamlPackages.markup</li>
    <li>ocamlPackages.mdx</li>
    <li>ocamlPackages.merlin</li>
    <li>ocamlPackages.merlin-extend</li>
    <li>ocamlPackages.metrics</li>
    <li>ocamlPackages.metrics-influx</li>
    <li>ocamlPackages.metrics-lwt</li>
    <li>ocamlPackages.metrics-mirage</li>
    <li>ocamlPackages.metrics-unix</li>
    <li>ocamlPackages.mew</li>
    <li>ocamlPackages.mew_vi</li>
    <li>ocamlPackages.minisat</li>
    <li>ocamlPackages.mirage</li>
    <li>ocamlPackages.mirage-block</li>
    <li>ocamlPackages.mirage-block-combinators</li>
    <li>ocamlPackages.mirage-block-ramdisk</li>
    <li>ocamlPackages.mirage-block-unix</li>
    <li>ocamlPackages.mirage-bootvar-unix</li>
    <li>ocamlPackages.mirage-channel</li>
    <li>ocamlPackages.mirage-clock</li>
    <li>ocamlPackages.mirage-clock-unix</li>
    <li>ocamlPackages.mirage-console</li>
    <li>ocamlPackages.mirage-console-unix</li>
    <li>ocamlPackages.mirage-crypto</li>
    <li>ocamlPackages.mirage-crypto-pk</li>
    <li>ocamlPackages.mirage-crypto-rng</li>
    <li>ocamlPackages.mirage-crypto-rng-async</li>
    <li>ocamlPackages.mirage-crypto-rng-mirage</li>
    <li>ocamlPackages.mirage-device</li>
    <li>ocamlPackages.mirage-flow</li>
    <li>ocamlPackages.mirage-flow-combinators</li>
    <li>ocamlPackages.mirage-flow-unix</li>
    <li>ocamlPackages.mirage-fs</li>
    <li>ocamlPackages.mirage-kv</li>
    <li>ocamlPackages.mirage-logs</li>
    <li>ocamlPackages.mirage-nat</li>
    <li>ocamlPackages.mirage-net</li>
    <li>ocamlPackages.mirage-profile</li>
    <li>ocamlPackages.mirage-protocols</li>
    <li>ocamlPackages.mirage-random</li>
    <li>ocamlPackages.mirage-random-test</li>
    <li>ocamlPackages.mirage-runtime</li>
    <li>ocamlPackages.mirage-stack</li>
    <li>ocamlPackages.mirage-time</li>
    <li>ocamlPackages.mirage-time-unix</li>
    <li>ocamlPackages.mirage-types</li>
    <li>ocamlPackages.mirage-types-lwt</li>
    <li>ocamlPackages.mirage-unix</li>
    <li>ocamlPackages.mirage-vnetif</li>
    <li>ocamlPackages.mmap</li>
    <li>ocamlPackages.mtime</li>
    <li>ocamlPackages.mustache</li>
    <li>ocamlPackages.nocrypto</li>
    <li>ocamlPackages.notty</li>
    <li>ocamlPackages.npy</li>
    <li>ocamlPackages.ocaml-lsp</li>
    <li>ocamlPackages.ocaml-migrate-parsetree</li>
    <li>ocamlPackages.ocaml-migrate-parsetree-2-1</li>
    <li>ocamlPackages.ocaml-monadic</li>
    <li>ocamlPackages.ocaml-protoc</li>
    <li>ocamlPackages.ocaml-r</li>
    <li>ocamlPackages.ocaml-sat-solvers</li>
    <li>ocamlPackages.ocaml-version</li>
    <li>ocamlPackages.ocaml_expat</li>
    <li>ocamlPackages.ocaml_gettext</li>
    <li>ocamlPackages.ocaml_oasis</li>
    <li>ocamlPackages.ocaml_sqlite3</li>
    <li>ocamlPackages.ocamlfuse</li>
    <li>ocamlPackages.ocamlmod</li>
    <li>ocamlPackages.ocb-stubblr</li>
    <li>ocamlPackages.ocp-build</li>
    <li>ocamlPackages.ocp-indent</li>
    <li>ocamlPackages.ocp-index</li>
    <li>ocamlPackages.ocp-ocamlres</li>
    <li>ocamlPackages.ocplib-json-typed</li>
    <li>ocamlPackages.ocplib-json-typed-browser</li>
    <li>ocamlPackages.ocplib-json-typed-bson</li>
    <li>ocamlPackages.ocsigen-start</li>
    <li>ocamlPackages.ocsigen-toolkit</li>
    <li>ocamlPackages.ocsigen_server</li>
    <li>ocamlPackages.octavius</li>
    <li>ocamlPackages.odoc</li>
    <li>ocamlPackages.opam-core</li>
    <li>ocamlPackages.opam-file-format</li>
    <li>ocamlPackages.opam-format</li>
    <li>ocamlPackages.opam-repository</li>
    <li>ocamlPackages.opam-state</li>
    <li>ocamlPackages.opium</li>
    <li>ocamlPackages.opium_kernel</li>
    <li>ocamlPackages.opti</li>
    <li>ocamlPackages.optint</li>
    <li>ocamlPackages.otfm</li>
    <li>ocamlPackages.otr</li>
    <li>ocamlPackages.ounit</li>
    <li>ocamlPackages.ounit2</li>
    <li>ocamlPackages.owee</li>
    <li>ocamlPackages.owl</li>
    <li>ocamlPackages.parany</li>
    <li>ocamlPackages.parmap</li>
    <li>ocamlPackages.parse-argv</li>
    <li>ocamlPackages.parsexp</li>
    <li>ocamlPackages.patience_diff</li>
    <li>ocamlPackages.pcap-format</li>
    <li>ocamlPackages.pgocaml</li>
    <li>ocamlPackages.pgocaml_ppx</li>
    <li>ocamlPackages.pgsolver</li>
    <li>ocamlPackages.phylogenetics</li>
    <li>ocamlPackages.piqi</li>
    <li>ocamlPackages.piqi-ocaml</li>
    <li>ocamlPackages.posix-base</li>
    <li>ocamlPackages.posix-socket</li>
    <li>ocamlPackages.posix-types</li>
    <li>ocamlPackages.posixat</li>
    <li>ocamlPackages.ppx_accessor</li>
    <li>ocamlPackages.ppx_assert</li>
    <li>ocamlPackages.ppx_base</li>
    <li>ocamlPackages.ppx_bench</li>
    <li>ocamlPackages.ppx_bin_prot</li>
    <li>ocamlPackages.ppx_bitstring</li>
    <li>ocamlPackages.ppx_blob</li>
    <li>ocamlPackages.ppx_cold</li>
    <li>ocamlPackages.ppx_compare</li>
    <li>ocamlPackages.ppx_cstruct</li>
    <li>ocamlPackages.ppx_custom_printf</li>
    <li>ocamlPackages.ppx_derivers</li>
    <li>ocamlPackages.ppx_deriving</li>
    <li>ocamlPackages.ppx_deriving_protobuf</li>
    <li>ocamlPackages.ppx_deriving_rpc</li>
    <li>ocamlPackages.ppx_deriving_yojson</li>
    <li>ocamlPackages.ppx_enumerate</li>
    <li>ocamlPackages.ppx_expect</li>
    <li>ocamlPackages.ppx_fields_conv</li>
    <li>ocamlPackages.ppx_fixed_literal</li>
    <li>ocamlPackages.ppx_gen_rec</li>
    <li>ocamlPackages.ppx_hash</li>
    <li>ocamlPackages.ppx_here</li>
    <li>ocamlPackages.ppx_import</li>
    <li>ocamlPackages.ppx_inline_test</li>
    <li>ocamlPackages.ppx_irmin</li>
    <li>ocamlPackages.ppx_jane</li>
    <li>ocamlPackages.ppx_js_style</li>
    <li>ocamlPackages.ppx_let</li>
    <li>ocamlPackages.ppx_module_timer</li>
    <li>ocamlPackages.ppx_optcomp</li>
    <li>ocamlPackages.ppx_optional</li>
    <li>ocamlPackages.ppx_pattern_bind</li>
    <li>ocamlPackages.ppx_pipebang</li>
    <li>ocamlPackages.ppx_sexp_conv</li>
    <li>ocamlPackages.ppx_sexp_message</li>
    <li>ocamlPackages.ppx_sexp_value</li>
    <li>ocamlPackages.ppx_stable</li>
    <li>ocamlPackages.ppx_string</li>
    <li>ocamlPackages.ppx_tools</li>
    <li>ocamlPackages.ppx_tools_versioned</li>
    <li>ocamlPackages.ppx_typerep_conv</li>
    <li>ocamlPackages.ppx_variants_conv</li>
    <li>ocamlPackages.ppx_yojson_conv_lib</li>
    <li>ocamlPackages.ppxfind</li>
    <li>ocamlPackages.ppxlib</li>
    <li>ocamlPackages.printbox</li>
    <li>ocamlPackages.prof_spacetime</li>
    <li>ocamlPackages.protocol_version_header</li>
    <li>ocamlPackages.psq</li>
    <li>ocamlPackages.ptime</li>
    <li>ocamlPackages.ptmap</li>
    <li>ocamlPackages.ptset</li>
    <li>ocamlPackages.qcheck</li>
    <li>ocamlPackages.qcheck-alcotest</li>
    <li>ocamlPackages.qcheck-ounit</li>
    <li>ocamlPackages.qtest</li>
    <li>ocamlPackages.randomconv</li>
    <li>ocamlPackages.re</li>
    <li>ocamlPackages.re2</li>
    <li>ocamlPackages.re2_stable</li>
    <li>ocamlPackages.react</li>
    <li>ocamlPackages.reactivedata</li>
    <li>ocamlPackages.reason</li>
    <li>ocamlPackages.resource-pooling</li>
    <li>ocamlPackages.resource_cache</li>
    <li>ocamlPackages.result</li>
    <li>ocamlPackages.rope</li>
    <li>ocamlPackages.rpclib</li>
    <li>ocamlPackages.rpclib-lwt</li>
    <li>ocamlPackages.rresult</li>
    <li>ocamlPackages.safepass</li>
    <li>ocamlPackages.secp256k1</li>
    <li>ocamlPackages.sedlex</li>
    <li>ocamlPackages.sedlex_2</li>
    <li>ocamlPackages.sexp</li>
    <li>ocamlPackages.sexp_diff_kernel</li>
    <li>ocamlPackages.sexp_macro</li>
    <li>ocamlPackages.sexp_pretty</li>
    <li>ocamlPackages.sexp_select</li>
    <li>ocamlPackages.sexplib</li>
    <li>ocamlPackages.shell</li>
    <li>ocamlPackages.shexp</li>
    <li>ocamlPackages.spacetime_lib</li>
    <li>ocamlPackages.spawn</li>
    <li>ocamlPackages.spelll</li>
    <li>ocamlPackages.splay_tree</li>
    <li>ocamlPackages.splittable_random</li>
    <li>ocamlPackages.srt</li>
    <li>ocamlPackages.ssl</li>
    <li>ocamlPackages.stdint</li>
    <li>ocamlPackages.stdio</li>
    <li>ocamlPackages.stdlib-shims</li>
    <li>ocamlPackages.stringext</li>
    <li>ocamlPackages.syslog-message</li>
    <li>ocamlPackages.tcpip</li>
    <li>ocamlPackages.tcslib</li>
    <li>ocamlPackages.textutils</li>
    <li>ocamlPackages.time_now</li>
    <li>ocamlPackages.timezone</li>
    <li>ocamlPackages.tls</li>
    <li>ocamlPackages.toml</li>
    <li>ocamlPackages.topkg</li>
    <li>ocamlPackages.topological_sort</li>
    <li>ocamlPackages.torch</li>
    <li>ocamlPackages.tsdl</li>
    <li>ocamlPackages.tsort</li>
    <li>ocamlPackages.tuntap</li>
    <li>ocamlPackages.typerep</li>
    <li>ocamlPackages.tyxml</li>
    <li>ocamlPackages.uchar</li>
    <li>ocamlPackages.uri</li>
    <li>ocamlPackages.uri-sexp</li>
    <li>ocamlPackages.utop</li>
    <li>ocamlPackages.uucd</li>
    <li>ocamlPackages.uucp</li>
    <li>ocamlPackages.uuidm</li>
    <li>ocamlPackages.uunf</li>
    <li>ocamlPackages.uuseg</li>
    <li>ocamlPackages.uutf</li>
    <li>ocamlPackages.variantslib</li>
    <li>ocamlPackages.vcaml</li>
    <li>ocamlPackages.vg</li>
    <li>ocamlPackages.virtual_dom</li>
    <li>ocamlPackages.visitors</li>
    <li>ocamlPackages.webbrowser</li>
    <li>ocamlPackages.webmachine</li>
    <li>ocamlPackages.wtf8</li>
    <li>ocamlPackages.x509</li>
    <li>ocamlPackages.xmlm</li>
    <li>ocamlPackages.xtmpl</li>
    <li>ocamlPackages.yaml</li>
    <li>ocamlPackages.yojson</li>
    <li>ocamlPackages.zed</li>
    <li>ocamlPackages.zmq</li>
    <li>ocamlPackages.zmq-lwt</li>
    <li>ocamlPackages.zstandard</li>
    <li>ocamlformat (ocamlformat_0_15_0)</li>
    <li>ocamlformat_0_11_0</li>
    <li>ocamlformat_0_12</li>
    <li>ocamlformat_0_13_0</li>
    <li>ocamlformat_0_14_0</li>
    <li>ocamlformat_0_14_1</li>
    <li>ocamlformat_0_14_2</li>
    <li>ocamlformat_0_14_3</li>
    <li>ocsigen-i18n</li>
    <li>opa</li>
    <li>opaline</li>
    <li>orpie</li>
    <li>ott</li>
    <li>patdiff</li>
    <li>python37Packages.bap</li>
    <li>python37Packages.guestfs</li>
    <li>python38Packages.bap</li>
    <li>python38Packages.guestfs</li>
    <li>python39Packages.bap</li>
    <li>python39Packages.guestfs</li>
    <li>satallax</li>
    <li>satysfi</li>
    <li>stog</li>
    <li>vagrant</li>
    <li>virt-top</li>
    <li>why3</li>
  </ul>
</details>

**Pull request merged**
