### PR TITLE
gpsd: 3.23 -> 3.23.1

### PR DESCRIPTION
**Pull request by hjones2199**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg eval

**Review by bjornfor — APPROVED** [review]

**Review by rasendubi — APPROVED** [review]

**Comment by timokau** [comment]
This broke `libsForQt5.marble`:

```
[ 69%] Building CXX object src/plugins/render/satellites/CMakeFiles/SatellitesPlugin.dir/SatellitesConfigAbstractItem.cpp.o
[ 69%] Building CXX object src/plugins/positionprovider/gpsd/CMakeFiles/GpsdPositionProviderPlugin.dir/GpsdPositionProviderPlugin.cpp.o
[ 69%] Building CXX object src/plugins/render/aprs/CMakeFiles/AprsPlugin.dir/GeoAprsCoordinates.cpp.o
[ 69%] Building CXX object src/plugins/render/satellites/CMakeFiles/SatellitesPlugin.dir/SatellitesConfigNodeItem.cpp.o
/build/marble-21.08.1/src/plugins/positionprovider/gpsd/GpsdPositionProviderPlugin.cpp: In member function 'void Marble::GpsdPositionProviderPlugin::update(gps_data_t)':
/build/marble-21.08.1/src/plugins/positionprovider/gpsd/GpsdPositionProviderPlugin.cpp:83:29: error: 'STATUS_NO_FIX' was not declared in this scope; did you mean 'STATUS_PPS_FIX'?
   83 |     if ( data.fix.status == STATUS_NO_FIX || std::isnan( data.fix.longitude ) || std::isnan( data.fix.latitude ) )
      |                             ^~~~~~~~~~~~~
      |                             STATUS_PPS_FIX
make[2]: *** [src/plugins/positionprovider/gpsd/CMakeFiles/GpsdPositionProviderPlugin.dir/build.make:104: src/plugins/positionprovider/gpsd/CMakeFiles/GpsdPositionProviderPlugin.dir/GpsdPositionProviderPlugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:5623: src/plugins/positionprovider/gpsd/CMakeFiles/GpsdPositionProviderPlugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Maybe we should roll this back for now and report the issue upstream. What do you think @hjones2199? CC @ttuegel (for kde applications).

**Comment by CrystalGamma** [comment]
There is already an MR upstream: https://invent.kde.org/education/marble/-/merge_requests/57

**Comment by hjones2199** [comment]
From looking at the gpsd changelog (https://gitlab.com/gpsd/gpsd/-/blob/master/NEWS), and looking at the output of nixpkgs-review (still running, I will post results here), the issue is that gpsd renamed a few macros. Once i have the full nixpkgs-review output it shouldnt be difficult to regex replace the macros in the failing packages patch phase. We're going to need to do that anyways for any dependent packages that arent maintained upstream.

That said, i'm not opposed to a rollback for a while to give maintained projects some time to fix it on their end.

**Comment by hjones2199** [comment]
Result of `nixpkgs-review pr 139794` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages marked as broken and skipped:</summary>
  <ul>
    <li>kexi</li>
    <li>libsForQt512.kreport</li>
    <li>libsForQt512.marble</li>
    <li>libsForQt514.kreport</li>
    <li>libsForQt514.marble</li>
  </ul>
</details>
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>calligra</li>
    <li>digikam</li>
    <li>foxtrotgps</li>
    <li>libsForQt5.kreport (libsForQt515.kreport ,plasma5Packages.kreport)</li>
    <li>libsForQt5.marble (libsForQt515.marble ,plasma5Packages.marble)</li>
    <li>timedoctor</li>
    <li>zombietrackergps</li>
  </ul>
</details>
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>alfred</li>
    <li>direwolf</li>
    <li>gpredict</li>
    <li>gpsd</li>
    <li>indi-full</li>
    <li>kstars</li>
    <li>merkaartor</li>
    <li>phd2</li>
    <li>qlandkartegt</li>
    <li>viking</li>
  </ul>
</details>

**Comment by timokau** [comment]
Thanks for digging into this :) The discussion is continued in #140523.

**Pull request merged**
