### PR TITLE
Generalize some GHCJS stuff for other cross compilers

### PR DESCRIPTION
**Pull request by Ericson2314**
Granted we don't have any others yet :). I also removed an unused file. This shouldn't change any hashes, just a refactor (I'll have follow up PRs that do change things). This is the first batch of changes from https://github.com/NixOS/nixpkgs/pull/13074 .

cc @peti @cstrahan

### CODE REVIEW

**Comment by cstrahan** [comment]
@Ericson2314 This looks great! Is there any reason not to passthru `bootPkgs` in `pkgs/development/compilers/ghc/nokinds.nix`?

**Comment by Ericson2314** [comment]
Nope! I just forgot to do that one.

**Comment by cstrahan** [comment]
Ok, cool. Patch that up and I'll merge this.

**Comment by cstrahan** [comment]
Thanks!

**Pull request merged**
