### PR TITLE
[20.03] backport nvidia driver updates

### PR DESCRIPTION
**Pull request by txt-file**
###### Motivation for this change

Backport some of the bumps from #91445 to 20.03
Closes: #91054

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tokudan** [comment]
@GrahamcOfBorg build linuxPackages.nvidia_x11_legacy340
Not sure if there are more attributes to build and I couldn't find a test

**Comment by tokudan** [comment]
@GrahamcOfBorg build linuxPackages.nvidia_x11_legacy390 linuxPackages.nvidia_x11_legacy440
I hope these are the correct attributes...

**Comment by tokudan** [comment]
Ah right, ofBorg won't build them because it's marked as unfree...

**Review by veprbl — COMMENTED** [review]
```
8 packages marked as broken and skipped:
linuxPackages_hardkernel_4_14.nvidia_x11 linuxPackages_hardkernel_4_14.nvidia_x11_beta linuxPackages_hardkernel_4_14.nvidia_x11_legacy340 linuxPackages_hardkernel_4_14.nvidia_x11_legacy390 linuxPackages_hardkernel_latest.nvidia_x11 linuxPackages_hardkernel_latest.nvidia_x11_beta linuxPackages_hardkernel_latest.nvidia_x11_legacy340 linuxPackages_hardkernel_latest.nvidia_x11_legacy390

13 packages failed to build:
bumblebee linuxPackages_5_6.nvidia_x11_legacy340 linuxPackages_5_7.nvidia_x11_legacy340 linuxPackages_latest-libre.nvidia_x11 linuxPackages_latest-libre.nvidia_x11_legacy340 linuxPackages_latest-libre.nvidia_x11_legacy390 linuxPackages_latest_hardened.nvidia_x11_legacy340 linuxPackages_latest_xen_dom0.nvidia_x11_legacy340 linuxPackages_testing_hardened.nvidia_x11 linuxPackages_testing_hardened.nvidia_x11_legacy340 linuxPackages_testing_hardened.nvidia_x11_legacy390 primus python37Packages.tensorflowWithCuda

44 packages built:
haskellPackages.cuda linuxPackages-libre.nvidia_x11 linuxPackages-libre.nvidia_x11_legacy340 linuxPackages-libre.nvidia_x11_legacy390 linuxPackages.nvidia_x11 linuxPackages.nvidia_x11_legacy340 linuxPackages.nvidia_x11_legacy390 linuxPackages_4_14.nvidia_x11 linuxPackages_4_14.nvidia_x11_legacy340 linuxPackages_4_14.nvidia_x11_legacy390 linuxPackages_4_19.nvidia_x11 linuxPackages_4_19.nvidia_x11_legacy340 linuxPackages_4_19.nvidia_x11_legacy390 linuxPackages_4_4.nvidia_x11 linuxPackages_4_4.nvidia_x11_legacy340 linuxPackages_4_4.nvidia_x11_legacy390 linuxPackages_4_9.nvidia_x11 linuxPackages_4_9.nvidia_x11_legacy340 linuxPackages_4_9.nvidia_x11_legacy390 linuxPackages_5_6.nvidia_x11 linuxPackages_5_6.nvidia_x11_legacy390 linuxPackages_5_7.nvidia_x11 linuxPackages_5_7.nvidia_x11_legacy390 linuxPackages_hardened.nvidia_x11 linuxPackages_hardened.nvidia_x11_legacy340 linuxPackages_hardened.nvidia_x11_legacy390 linuxPackages_latest_hardened.nvidia_x11 linuxPackages_latest_hardened.nvidia_x11_legacy390 linuxPackages_latest_xen_dom0.nvidia_x11 linuxPackages_latest_xen_dom0.nvidia_x11_legacy390 linuxPackages_testing_bcachefs.nvidia_x11 linuxPackages_testing_bcachefs.nvidia_x11_legacy340 linuxPackages_testing_bcachefs.nvidia_x11_legacy390 linuxPackages_xen_dom0.nvidia_x11 linuxPackages_xen_dom0.nvidia_x11_legacy340 linuxPackages_xen_dom0.nvidia_x11_legacy390 nvtop psensor python27Packages.TheanoWithCuda python27Packages.cupy  python37Packages.TheanoWithCuda python37Packages.cupy python38Packages.TheanoWithCuda python38Packages.cupy
```

**Pull request merged**
