### PR TITLE
fclones: 0.18.1 -> 0.19.0

### PR DESCRIPTION
**Pull request by cyounkins**
###### Description of changes

Updates fclones to 0.19.0:
Fix handling of non-unicode and control chars in paths
https://github.com/pkolaczk/fclones/releases

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cyounkins** [comment]
The build may fail on aarch64-linux with the rust compiler claiming it cannot compile a doctest. Since the same doctest compiles on other architectures, I believe this is something wrong with the rust compiler on aarch64-linux and nothing to do with fclones.

@msfjarvis for visibility (are you getting automatic notifications as a maintainer?)

**Comment by msfjarvis** [comment]
> The build may fail on aarch64-linux with the rust compiler claiming it cannot compile a doctest. Since the same doctest compiles on other architectures, I believe this is something wrong with the rust compiler on aarch64-linux and nothing to do with fclones.

I have access to an aarch64 machine, I'll investigate it.

> 
> @msfjarvis for visibility (are you getting automatic notifications as a maintainer?)

I get notified when ofborg requests my review which it doesn't seem to have done for this PR.

**Review by msfjarvis — APPROVED** [review]

**Comment by Artturin** [comment]
@ofborg build fclones

**Comment by Artturin** [comment]
> > The build may fail on aarch64-linux with the rust compiler claiming it cannot compile a doctest. Since the same doctest compiles on other architectures, I believe this is something wrong with the rust compiler on aarch64-linux and nothing to do with fclones.
> 
> I have access to an aarch64 machine, I'll investigate it.
> 
> > @msfjarvis for visibility (are you getting automatic notifications as a maintainer?)
> 
> I get notified when ofborg requests my review which it doesn't seem to have done for this PR.

you didn't get pinged because your githubId is wrong in `maintainers-list.nix` 
`githubId = 3348378;`

Correct one is 13348378 https://caius.github.io/github_id/#msfjarvis

**Pull request merged**
