### PR TITLE
dmd: build process compatibility with 2.101 and 2.102

### PR DESCRIPTION
**Pull request by dukc**
###### Description of changes

Upstreaming the changes from [OldDDerivations](https://github.com/dukc/olddderivations) necessary to be compatible with newer DMD versions, 2.101.x and 2.102.x.

~~I didn't actually upgrade the version, because @ThomasMader IIRC wants the LDC and DMD compilers to use the same frontend version. This will make such an upgrade less work in the future, though.~~

EDIT: it seems there currently is an [LDC update in reviews](218905). If it gets in first, I could update the hashes.

EDIT2: Said version bump was merged so including a verion bump to 2.101.2 here too.

The needed changes are relatively big because the DRuntime and DMD repositories were merged between versions 2.100 and 2.101.

###### Things done

Test-built it with `nix-build -E 'with import ./default.nix {}; dmd'` at project root directory and compiled and ran a "hello world" with the result. I have tested at OldDDerivations that 2.101 and 2.102 also do build with these changes compined with needed updates of the hashes.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dukc** [comment]
Since the LDC version bump got in, I also updated the hashes of DMD to 2.101.2 here.

**Comment by ljmf00** [comment]
Ping @lionello

**Comment by CyberShadow** [comment]
I've just tried to update dmd after noticing that it is now five versions behind, then found this.

It seems that the maintainer is disinterested or MIA. @dukc @ljmf00 How can we move forward here, would changing the maintainer make sense?

**Comment by lionello** [comment]
I'm looking into this, but I admit that I've been out of the Dlang crowd for a while.

**Comment by CyberShadow** [comment]
@lionello How can we or others help? Is there something that currently only you can do, but maybe could delegate to others? E.g. merge rights or testing?

**Comment by CyberShadow** [comment]
Ah, OK, then maybe it would make sense to change the configuration so that more people are added as reviewers and can approve?

**Comment by CyberShadow** [comment]
BTW, here are my changes for 2.101 through 2.103 (but I did not preserve backwards-compatibility with previous versions):

```diff
From ce7ebbfb4376525955347e6cc722ef3d5b43a8f4 Mon Sep 17 00:00:00 2001
From: Vladimir Panteleev <git@cy.md>
Date: Mon, 18 Sep 2023 12:59:27 +0000
Subject: [PATCH 1/3] dmd: 2.100.2 -> 2.101.0

Drop Druntime repository (it was merged into the dmd repository).
---
 pkgs/development/compilers/dmd/default.nix |  7 ++-
 pkgs/development/compilers/dmd/generic.nix | 59 ++++++++--------------
 2 files changed, 24 insertions(+), 42 deletions(-)

diff --git a/pkgs/development/compilers/dmd/default.nix b/pkgs/development/compilers/dmd/default.nix
index 35cb0759c5e1..09fddf3c6419 100644
--- a/pkgs/development/compilers/dmd/default.nix
+++ b/pkgs/development/compilers/dmd/default.nix
@@ -1,6 +1,5 @@
 import ./generic.nix {
-  version = "2.100.2";
-  dmdSha256 = "sha256-o4+G3ARXIGObYHtHooYZKr+Al6kHpiwpMIog3i4BlDM=";
-  druntimeSha256 = "sha256-qXvY1ECN4mPwOGgOE1FWwvxoRvlSww3tGLWgBdhzAKo=";
-  phobosSha256 = "sha256-kTHRaAKG7cAGb4IE/NGHWaZ8t7ZceKj03l6E8wLzJzs=";
+  version = "2.101.0";
+  dmdSha256 = "sha256-fMl2xrixTy9asZ5yty7dTaVLgTXEdeR94ZDXrLSE2qQ=";
+  phobosSha256 = "sha256-mqiVkm45itiG595LPcdGtoHnZ3adZNT+0hcbITAGaKo=";
 }
diff --git a/pkgs/development/compilers/dmd/generic.nix b/pkgs/development/compilers/dmd/generic.nix
index 3f8871df4f96..bdbe169f4ddb 100644
--- a/pkgs/development/compilers/dmd/generic.nix
+++ b/pkgs/development/compilers/dmd/generic.nix
@@ -1,6 +1,5 @@
 { version
 , dmdSha256
-, druntimeSha256
 , phobosSha256
 }:
 
@@ -58,13 +57,6 @@ stdenv.mkDerivation rec {
       sha256 = dmdSha256;
       name = "dmd";
     })
-    (fetchFromGitHub {
-      owner = "dlang";
-      repo = "druntime";
-      rev = "v${version}";
-      sha256 = druntimeSha256;
-      name = "druntime";
-    })
     (fetchFromGitHub {
       owner = "dlang";
       repo = "phobos";
@@ -88,41 +80,33 @@ stdenv.mkDerivation rec {
       extraPrefix = "dmd/";
       sha256 = "sha256-N21mAPfaTo+zGCip4njejasraV5IsWVqlGR5eOdFZZE=";
     })
-  ] ++ lib.optionals (lib.versionOlder version "2.092.2") [
-    # Fixes C++ tests that compiled on older C++ but not on the current one
-    (fetchpatch {
-      url = "https://github.com/dlang/druntime/commit/438990def7e377ca1f87b6d28246673bb38022ab.patch";
-      stripLen = 1;
-      extraPrefix = "druntime/";
-      sha256 = "sha256-/pPKK7ZK9E/mBrxm2MZyBNhYExE8p9jz8JqBdZSE6uY=";
-    })
   ];
 
   postPatch = ''
-    patchShebangs dmd/test/{runnable,fail_compilation,compilable,tools}{,/extra-files}/*.sh
-
-    rm dmd/test/runnable/gdb1.d
-    rm dmd/test/runnable/gdb10311.d
-    rm dmd/test/runnable/gdb14225.d
-    rm dmd/test/runnable/gdb14276.d
-    rm dmd/test/runnable/gdb14313.d
-    rm dmd/test/runnable/gdb14330.d
-    rm dmd/test/runnable/gdb15729.sh
-    rm dmd/test/runnable/gdb4149.d
-    rm dmd/test/runnable/gdb4181.d
+    patchShebangs dmd/compiler/test/{runnable,fail_compilation,compilable,tools}{,/extra-files}/*.sh
+
+    rm dmd/compiler/test/runnable/gdb1.d
+    rm dmd/compiler/test/runnable/gdb10311.d
+    rm dmd/compiler/test/runnable/gdb14225.d
+    rm dmd/compiler/test/runnable/gdb14276.d
+    rm dmd/compiler/test/runnable/gdb14313.d
+    rm dmd/compiler/test/runnable/gdb14330.d
+    rm dmd/compiler/test/runnable/gdb15729.sh
+    rm dmd/compiler/test/runnable/gdb4149.d
+    rm dmd/compiler/test/runnable/gdb4181.d
 
     # Disable tests that rely on objdump whitespace until fixed upstream:
     #   https://issues.dlang.org/show_bug.cgi?id=23317
-    rm dmd/test/runnable/cdvecfill.sh
-    rm dmd/test/compilable/cdcmp.d
+    rm dmd/compiler/test/runnable/cdvecfill.sh
+    rm dmd/compiler/test/compilable/cdcmp.d
 
     # Grep'd string changed with gdb 12
     #   https://issues.dlang.org/show_bug.cgi?id=23198
-    substituteInPlace druntime/test/exceptions/Makefile \
+    substituteInPlace dmd/druntime/test/exceptions/Makefile \
       --replace 'in D main (' 'in _Dmain ('
 
     # We're using gnused on all platforms
-    substituteInPlace druntime/test/coverage/Makefile \
+    substituteInPlace dmd/druntime/test/coverage/Makefile \
       --replace 'freebsd osx' 'none'
   ''
 
@@ -130,11 +114,11 @@ stdenv.mkDerivation rec {
     # This one has tested against a hardcoded year, then against a current year on
     # and off again. It just isn't worth it to patch all the historical versions
     # of it, so just remove it until the most recent change.
-    rm dmd/test/compilable/ddocYear.d
+    rm dmd/compiler/test/compilable/ddocYear.d
   '' + lib.optionalString (lib.versionAtLeast version "2.089.0" && lib.versionOlder version "2.092.2") ''
-    rm dmd/test/dshell/test6952.d
+    rm dmd/compiler/test/dshell/test6952.d
   '' + lib.optionalString (lib.versionAtLeast version "2.092.2") ''
-    substituteInPlace dmd/test/dshell/test6952.d --replace "/usr/bin/env bash" "${bash}/bin/bash"
+    substituteInPlace dmd/compiler/test/dshell/test6952.d --replace "/usr/bin/env bash" "${bash}/bin/bash"
   ''
 
   + lib.optionalString stdenv.isLinux ''
@@ -180,7 +164,6 @@ stdenv.mkDerivation rec {
     fi
 
     make -C dmd -f posix.mak $buildFlags -j$buildJobs HOST_DMD=${HOST_DMD}
-    make -C druntime -f posix.mak $buildFlags -j$buildJobs DMD=${pathToDmd}
     echo ${tzdata}/share/zoneinfo/ > TZDatabaseDirFile
     echo ${lib.getLib curl}/lib/libcurl${stdenv.hostPlatform.extensions.sharedLibrary} > LibcurlPathFile
     make -C phobos -f posix.mak $buildFlags -j$buildJobs DMD=${pathToDmd} DFLAGS="-version=TZDatabaseDir -version=LibcurlPath -J$PWD"
@@ -205,10 +188,10 @@ stdenv.mkDerivation rec {
     fi
 
     NIX_ENFORCE_PURITY= \
-      make -C dmd/test $checkFlags CC=$CXX SHELL=$SHELL -j$checkJobs N=$checkJobs
+      make -C dmd/compiler/test $checkFlags CC=$CXX SHELL=$SHELL -j$checkJobs N=$checkJobs
 
     NIX_ENFORCE_PURITY= \
-      make -C druntime -f posix.mak unittest $checkFlags -j$checkJobs
+      make -C dmd/druntime -f posix.mak unittest $checkFlags -j$checkJobs
 
     NIX_ENFORCE_PURITY= \
       make -C phobos -f posix.mak unittest $checkFlags -j$checkJobs DFLAGS="-version=TZDatabaseDir -version=LibcurlPath -J$PWD"
@@ -224,7 +207,7 @@ stdenv.mkDerivation rec {
     installManPage dmd/docs/man/man*/*
 
     mkdir -p $out/include/dmd
-    cp -r {druntime/import/*,phobos/{std,etc}} $out/include/dmd/
+    cp -r {dmd/druntime/import/*,phobos/{std,etc}} $out/include/dmd/
 
     mkdir $out/lib
     cp phobos/generated/${osname}/release/${bits}/libphobos2.* $out/lib/
-- 
2.42.0

```

```diff
From 15776205437279b080ac1cb0f0e7a85a29353764 Mon Sep 17 00:00:00 2001
From: Vladimir Panteleev <git@cy.md>
Date: Mon, 18 Sep 2023 13:16:37 +0000
Subject: [PATCH 2/3] dmd: 2.101.0 -> 2.102.0

---
 pkgs/development/compilers/dmd/default.nix | 6 +++---
 pkgs/development/compilers/dmd/generic.nix | 2 +-
 2 files changed, 4 insertions(+), 4 deletions(-)

diff --git a/pkgs/development/compilers/dmd/default.nix b/pkgs/development/compilers/dmd/default.nix
index 09fddf3c6419..af6c573a4ab6 100644
--- a/pkgs/development/compilers/dmd/default.nix
+++ b/pkgs/development/compilers/dmd/default.nix
@@ -1,5 +1,5 @@
 import ./generic.nix {
-  version = "2.101.0";
-  dmdSha256 = "sha256-fMl2xrixTy9asZ5yty7dTaVLgTXEdeR94ZDXrLSE2qQ=";
-  phobosSha256 = "sha256-mqiVkm45itiG595LPcdGtoHnZ3adZNT+0hcbITAGaKo=";
+  version = "2.102.0";
+  dmdSha256 = "sha256-WZ7q0cxvfY4EHrNO9OM46cuXCoguGKmrfL2tMzA6huE=";
+  phobosSha256 = "sha256-SEAruz1Byga/Q/wX2wv1pdMNv3RkobQ+EznXV1s4Ie4=";
 }
diff --git a/pkgs/development/compilers/dmd/generic.nix b/pkgs/development/compilers/dmd/generic.nix
index bdbe169f4ddb..51fe0cb9ab86 100644
--- a/pkgs/development/compilers/dmd/generic.nix
+++ b/pkgs/development/compilers/dmd/generic.nix
@@ -103,7 +103,7 @@ stdenv.mkDerivation rec {
     # Grep'd string changed with gdb 12
     #   https://issues.dlang.org/show_bug.cgi?id=23198
     substituteInPlace dmd/druntime/test/exceptions/Makefile \
-      --replace 'in D main (' 'in _Dmain ('
+      --replace 'D main (' '_Dmain ('
 
     # We're using gnused on all platforms
     substituteInPlace dmd/druntime/test/coverage/Makefile \
-- 
2.42.0

```

```diff
From 9bd4d6cd437f3be8eb2f208317811fba85c441b3 Mon Sep 17 00:00:00 2001
From: Vladimir Panteleev <git@cy.md>
Date: Mon, 18 Sep 2023 13:28:17 +0000
Subject: [PATCH 3/3] dmd: 2.102.0 -> 2.103.0

---
 pkgs/development/compilers/dmd/default.nix | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/pkgs/development/compilers/dmd/default.nix b/pkgs/development/compilers/dmd/default.nix
index af6c573a4ab6..bea69740d29e 100644
--- a/pkgs/development/compilers/dmd/default.nix
+++ b/pkgs/development/compilers/dmd/default.nix
@@ -1,5 +1,5 @@
 import ./generic.nix {
-  version = "2.102.0";
-  dmdSha256 = "sha256-WZ7q0cxvfY4EHrNO9OM46cuXCoguGKmrfL2tMzA6huE=";
-  phobosSha256 = "sha256-SEAruz1Byga/Q/wX2wv1pdMNv3RkobQ+EznXV1s4Ie4=";
+  version = "2.103.0";
+  dmdSha256 = "sha256-3iQN4Ktlp8UFT19TaoOi1op/vFMQALjc4Z5ReLpnYt8=";
+  phobosSha256 = "sha256-+Gg57JmW03840xRzESRVv5I3FA1VT4JMDHMScooZBZw=";
 }
-- 
2.42.0

```

**Comment by dukc** [comment]
> Ah, OK, then maybe it would make sense to change the configuration so that more people are added as reviewers and can approve?

The thing is, I'm a maintainer too so I should just have pinged someone with merge rights and there would probably have been no problem since other maintainers didn't veto.

I'm surprised the tests are still passing. I recently ported 2.102.2 from OldDDerivations to [dlang-nix](https://github.com/PetarKirov/dlang-nix/) (that I'm intending to succeed OldDDerivations) and it did require some adaptations before it built.

**Comment by dukc** [comment]
!256163 has superseded this. Well, not quite, since it doesn't keep backwards compatibility unlike my work.

I'm not going to fix it right now though. Since I've been concentrating on porting OldDDerivations to Dlang-Nix, I haven't been able to keep it in sync with NixPkgs and will have to resynchronise them anyway once our two projects have been fully merged. Once I can do that, we will have backwards compatibility to 2.084 again, unless people protest.

**Pull request closed without merging**
