### PR TITLE
Add bibutils 5.6 package

### PR DESCRIPTION
**Pull request by garrison**

### CODE REVIEW

**Comment by garrison** [comment]
Here's the link for bibutils: http://sourceforge.net/p/bibutils/home/Bibutils/

It seems to be actively maintained, with its most recent release made a year ago.  It is packaged for Debian and perhaps other GNU/Linux distributions as well.

**Comment by fpletz** [comment]
Please reword the commit message according to our [contributing guidelines](https://hydra.nixos.org/build/31168087/download/1/nixpkgs/manual.html#chap-submitting-changes).

**Comment by garrison** [comment]
Done

**Comment by globin** [comment]
Thanks!

**Pull request merged**
