### PR TITLE
nodejs: Drop 4_x release

### PR DESCRIPTION
**Pull request by adisbladis**
###### Motivation for this change
nodejs-4_x is scheduled end-of-life on 2018-04-30
It should not go in the 18.03 release

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by globin** [comment]
:+1: 

ping @vcunat, @fpletz

**Comment by vcunat** [comment]
Sounds OK to me.  /cc maintainers: @cillianderoiste, @havvy, @gilligan, @cko.

**Comment by adisbladis** [comment]
If no one has any opposition I plan to merge this in a day.

CC @cillianderoiste @gilligan @cko

**Comment by gilligan** [comment]
Sounds good to me! Lets drop it!

**Pull request merged**
