### PR TITLE
tiledb: 2.8.3 -> 2.18.0

### PR DESCRIPTION
**Pull request by imincik**
## Description of changes

Update TileDB to the latest version.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by imincik** [comment]
PR is tested with GDAL and PDAL packages and it works !

**Comment by imincik** [comment]
Tests fail on following:

```
Test project /home/imincik/Projects/nix/nixpkgs/code/source/build/tiledb/test
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: tiledb_unit

1: Test command: /home/imincik/Projects/nix/nixpkgs/code/source/build/tiledb/test/tiledb_unit "--durations=yes"
1: Working Directory: /home/imincik/Projects/nix/nixpkgs/code/source/test
1: Test timeout computed to be: 10000000
test 2
    Start 2: test_ci_asserts

2: Test command: /home/imincik/Projects/nix/nixpkgs/code/source/build/tiledb/test/ci/test_assert
2: Working Directory: /home/imincik/Projects/nix/nixpkgs/code/source/build/tiledb/test/ci
2: Test timeout computed to be: 10000000
1: Errors occurred during startup!
1:   Found an unclosed tag while registering test case 'Dimension: Test
1:   map_to_uint64, float32' at /home/imincik/Projects/nix/nixpkgs/code/source/
1:   test/src/unit-dimension.cc:274
1/2 Test #1: tiledb_unit ......................***Failed    0.01 sec
Errors occurred during startup!
  Found an unclosed tag while registering test case 'Dimension: Test
  map_to_uint64, float32' at /home/imincik/Projects/nix/nixpkgs/code/source/
  test/src/unit-dimension.cc:274

2: Assert did not exit!
2: Randomness seeded to: 1241610924
2: retval is 0 (0x0) from /home/imincik/Projects/nix/nixpkgs/code/source/build/tiledb/test/ci/try_assert
2: ===============================================================================
2: All tests passed (1 assertion in 1 test case)
2:
2/2 Test #2: test_ci_asserts ..................   Passed    0.01 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =   0.01 sec

The following tests FAILED:
	  1 - tiledb_unit (Failed)
Errors while running CTest
make[7]: *** [test/CMakeFiles/check.dir/build.make:70: test/CMakeFiles/check] Error 8
make[7]: Leaving directory '/home/imincik/Projects/nix/nixpkgs/code/source/build/tiledb'
make[6]: *** [CMakeFiles/Makefile2:13681: test/CMakeFiles/check.dir/all] Error 2
make[6]: Leaving directory '/home/imincik/Projects/nix/nixpkgs/code/source/build/tiledb'
make[5]: *** [CMakeFiles/Makefile2:13688: test/CMakeFiles/check.dir/rule] Error 2
make[5]: Leaving directory '/home/imincik/Projects/nix/nixpkgs/code/source/build/tiledb'
make[4]: *** [Makefile:4261: check] Error 2
make[4]: Leaving directory '/home/imincik/Projects/nix/nixpkgs/code/source/build/tiledb'

make[3]: *** [CMakeFiles/check.dir/build.make:70: CMakeFiles/check] Error 2
make[3]: Leaving directory '/home/imincik/Projects/nix/nixpkgs/code/source/build'
make[2]: *** [CMakeFiles/Makefile2:220: CMakeFiles/check.dir/all] Error 2
make[2]: Leaving directory '/home/imincik/Projects/nix/nixpkgs/code/source/build'
make[1]: *** [CMakeFiles/Makefile2:227: CMakeFiles/check.dir/rule] Error 2
make[1]: Leaving directory '/home/imincik/Projects/nix/nixpkgs/code/source/build'
make: *** [Makefile:189: check] Error 2
```

**Comment by imincik** [comment]
@ofborg build tiledb

**Comment by FRidh** [comment]
We should not just disable the tests. Is the issue reported/known upstream? Is it possible to disable only the failing test(s)?

**Comment by imincik** [comment]
> We should not just disable the tests. Is the issue reported/known upstream? Is it possible to disable only the failing test(s)?

Thanks, 
I am not a maintainer of this package and I am doing this PR only because it is needed as a dependency of two packages which I maintain.

I really don't want to disable tests, but I can't get single one test to work. I very much need a help there  !

**Comment by FRidh** [comment]
I understand, thanks! I also like to see the gdal update in (testing it locally now together with this for a work project).

**Comment by imincik** [comment]
Good news, I am able to run the unit tests using the commands taken from upstream CI - https://github.com/TileDB-Inc/TileDB/blob/f7390c4a86bb82ddfffbaedc2a52228db96784ad/.github/workflows/unit-test-runs.yml#L68C1-L69C58

**Comment by imincik** [comment]
Tests are now enabled, please review.

**Review by FRidh — APPROVED** [review]

**Review by l0b0 — APPROVED** [review]

**Pull request merged**
