### PR TITLE
[19.03] ham: init at (unstable-)2019-01-22

### PR DESCRIPTION
**Pull request by herrwiese**
###### Motivation for this change

This recently got into master. I'm using it on a daily basis and hence would love to also have it in stable...

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by herrwiese** [comment]
cc @worldofpeace

**Comment by worldofpeace** [comment]
I put `[19.03]` in the pr title because it makes it easy to see what's a backport when you can't add the label.

**Comment by herrwiese** [comment]
I noted that for future cases, thanks. ;)  And: Wow, that was quick.

**Comment by worldofpeace** [comment]
> I noted that for future cases, thanks. ;) And: Wow, that was quick.

Thanks, this happens to be a good time for me :smile:

**Review by worldofpeace — APPROVED** [review]
Backport was performed correctly.

Just awaiting the ofborg checks.

**Comment by worldofpeace** [comment]
Thanks @herrwiese :sparkles:

**Pull request merged**
