### PR TITLE
python3Packages.rapidfuzz: 2.0.8 -> 2.0.11

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
https://github.com/maxbachmann/RapidFuzz/releases/tag/v2.0.9
https://github.com/maxbachmann/RapidFuzz/releases/tag/v2.0.10

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc @yuuyins

### CODE REVIEW

**Review by risicle — APPROVED** [review]
`nixpkgs-review` happy, macos 10.15 & nixos x86_64. New native libraries build for `pkgsMusl` and `pkgsCross.aarch64-multiplatform`.

**Comment by risicle** [comment]
Except on aarch64-darwin the build of `taskflow` appears to be trying to use x86 intrinsics:

```
In file included from In file included from /nix/store/nwfcj1p4l74krm4n6szrb0c534p4ai2s-clang-wrapper-11.1.0/resource-root/include/immintrin.h/tmp/nix-build-taskflow-3.3.0.drv-0/source/taskflow/core/../utility/os.hpp::15126:
:
/nix/store/1r3mrri4afdhshaibaamb3rafvy4ngv9-libcxx-11.1.0-dev/include/c++/v1/math.h/nix/store/nwfcj1p4l74krm4n6szrb0c534p4ai2s-clang-wrapper-11.1.0/resource-root/include/mmintrin.h::64933::125:/nix/store/1r3mrri4afdhshaibaamb3rafvy4ngv9-libcxx->
'__builtin_isless' declared here
    return isless(__lcpp_x, __lcpp_y);
           ^    __builtin_ia32_emms();
In file included from /nix/store/nwfcj1p4l74krm4n6szrb0c534p4ai2s-clang-wrapper-11.1.0/resource-root/include/immintrin.h    ^:
15:
/nix/store/nwfcj1p4l74krm4n6szrb0c534p4ai2s-clang-wrapper-11.1.0/resource-root/include/mmintrin.h:33:5: fatal error: use of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?
/nix/store/1r3mrri4afdhshaibaamb3rafvy4ngv9-libcxx-11.1.0-dev/include/c++/v1/math.h:649:In file included from 12:: /tmp/nix-build-taskflow-3.3.0.drv-0/source/examples/subflow.cpp :note: '__builtin_isless' declared here
```

**Comment by risicle** [comment]
Suggest commenting out this section of `os.h` as they appear to have done in upstream master: https://github.com/taskflow/taskflow/commit/75454ae5a40abf1e095a2164cc555684d284bc20#diff-7122f106ea7deeb4027fac3a83db4a8eb748a11687574b1dc4a904faee168149

Also I just looked at the number of bundled dependencies `taskflow` has and it made me sad.

**Comment by risicle** [comment]
```
  postPatch = ''
    sed -i '/^#if __has_include (<immintrin\.h>)/,/^#endif/d' taskflow/utility/os.hpp
  '';
```

Achieves this successfully for me

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by dotlambda** [comment]
> Also I just looked at the number of bundled dependencies `taskflow` has and it made me sad.

It actually builds without them :)

**Comment by SuperSandro2000** [comment]
Might as well also update to https://github.com/maxbachmann/RapidFuzz/releases/tag/v2.0.11 to make packaging easier.

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 170017` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>jarowinkler-cpp</li>
    <li>puddletag</li>
    <li>python310Packages.levenshtein</li>
    <li>python310Packages.rapidfuzz</li>
    <li>python39Packages.levenshtein</li>
    <li>python39Packages.rapidfuzz</li>
    <li>rapidfuzz-cpp</li>
    <li>spotdl</li>
    <li>taskflow</li>
  </ul>
</details>

**Pull request merged**
