### PR TITLE
[haskell-updates] haskellPackages.haskell-language-server: 0.2.0.0 -> 0.2.2.0

### PR DESCRIPTION
**Pull request by maralorn**
This bumps the version of hls. And disables one of the tests.

In my opinion, this can and should be merged with the failing test for now, as the newer version contains a lot of compatibility fixes.

I have contacted upstream about the failing test. But for now, I don‘t know how to fix it.

@GuillaumeDesforges maybe you have an idea?

```
Test suite wrapper-test: RUNNING...
haskell-language-server-wrapper
  --project-ghc-version
    stack with ghc 8.10.1: FAIL
      Exception: dist-newstyle: getDirectoryContents:openDirStream: does not exist (No such file or directory)
    stack with ghc 8.8.3:  FAIL
      Exception: dist-newstyle: getDirectoryContents:openDirStream: does not exist (No such file or directory)
    cabal with global ghc: FAIL
      Exception: dist-newstyle: getDirectoryContents:openDirStream: does not exist (No such file or directory)

3 out of 3 tests failed (0.07s)
Test suite wrapper-test: FAIL
Test suite logged to:
dist/test/haskell-language-server-0.2.2.0-wrapper-test.log
```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by maralorn** [comment]
@GrahamcOfBorg build haskellPackages.haskell-language-server

**Review by cdepillabout — APPROVED** [review]
This seems reasonable to me.

**Comment by GuillaumeDesforges** [comment]
Yup, had some issues about that already, let me get to it

**Comment by maralorn** [comment]
@GuillaumeDesforges Nice! Thanks!

**Comment by GuillaumeDesforges** [comment]
@maralorn did you submit an upstream issue?

**Comment by maralorn** [comment]
@Guillaumedesforges, I am sorry, no. I had a chat with lukelau in the hls freenode room. The issue seems to be simple and generic. The test needs the binary in the PATH and they wrote a hack accessing dist-newstyle to discover the binaries. They consider it a bug. They encouraged me to fix it because they were were. Busy, but I am also on holidays so I forgot about. You can pick between making a simple PR to hls, opening an issue or waiting for me or then to fix it. Although the latter might be risky without an issue...

**Comment by GuillaumeDesforges** [comment]
I'll make an issue, I can't take this atm. It can wait anyway

**Comment by GuillaumeDesforges** [comment]
Apparently fixed: https://github.com/haskell/haskell-language-server/issues/251#issuecomment-665709683

Let's update upstream issue on the next version bump of our nixpkgs hls derivation

**Pull request merged**
