### PR TITLE
mesa: 12.0.3 -> 13.0.1

### PR DESCRIPTION
**Pull request by rnhmjoj**
Updating PR #20139 for mesa 13.0.1 release
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (none)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
---

@NeQuissimus 
@vcunat

### CODE REVIEW

**Comment by vcunat** [comment]
You did try running 13.0.0 and/or 13.0.1, right? What driver was it?

**Comment by vcunat** [comment]
BTW, retarget this for the staging branch, please. (It's a bit strange that I can change almost anything in the PR but only the submitter can do that.)

**Comment by rnhmjoj** [comment]
Yes, I have been using it on my system for a while. I have an Intel GPU: no issue with it so far.

**Comment by vcunat** [comment]
I'm just trying an "ati" driver (R600): desktop and X log seem fine but glxgears stopped working.

**Comment by vcunat** [comment]
It's well possible this problem isn't related to the mesa update. There was an older system in there (16.09beta395 3faa03f).

**Comment by vcunat** [comment]
Ah, it works. It was a combination of my typo in a command and some nixos stuff that could be improved. Nothing directly related.

**Pull request merged**
