### PR TITLE
nixos/iwd: pull in upstream .link unit file

### PR DESCRIPTION
**Pull request by xaverdh**
###### Motivation for this change

This is meant to fix the race condition between `iwd` and `udev` trying to
rename the interface.

Once `systemd.packages` [learns](https://github.com/NixOS/nixpkgs/issues/105689) to deal with `.link` unit files it probably won't be needed anymore.

###### Things done

Currently testing this on my system.
 
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by archseer — APPROVED** [review]

**Comment by xaverdh** [comment]
cc @mic92 @dtzWill (as maintainers)

**Comment by flokli** [comment]
Sorry for the terrible delay of this.

instead of referring to the file, we should probably "set the same contents by hand" via `systemd.network.links`, for visibility and overridability (and to match how we do this by zerotier). I doubt it'll change upstream that often.

See https://github.com/NixOS/nixpkgs/pull/82310 / https://github.com/NixOS/nixpkgs/pull/82941 for some background.

Can something like this be added to the 21.03 release notes file?

> The `iwd` module now installs the upstream-provided `80-iwd.link` file, which sets the `NamePolicy=` for all wlan devices to "keep kernel", to avoid race conditions between `iwd` and `networkd`. If you don't want this, set `systemd.network.links."80-iwd" = lib.mkForce {}`.

**Comment by xaverdh** [comment]
> Sorry for the terrible delay of this.

no problem!
> instead of referring to the file, we should probably "set the same contents by hand" via `systemd.network.links`, for visibility and overridability (and to match how we do this by zerotier). I doubt it'll change upstream that often.
> 
> See #82310 / #82941 for some background.
> 
> Can something like this be added to the 21.03 release notes file?
> 
> > The `iwd` module now installs the upstream-provided `80-iwd.link` file, which sets the `NamePolicy=` for all wlan devices to "keep kernel", to avoid race conditions between `iwd` and `networkd`. If you don't want this, set `systemd.network.links."80-iwd" = lib.mkForce {}`.

done.

**Comment by Mic92** [comment]
Thanks!

**Pull request merged**
