### PR TITLE
Fix CUPS socket path to be default /var/run/cups/cups.sock

### LINKED ISSUE #34963: CUPS on NixOS [Chrome stopped to print]
## Issue description

Chrome stopped to print someday on nixos-unstable

1. Both Chrome and Firefox look for `/run/cups.sock` socket but our CUPS module only creates `/run/cups/cups.sock`
2. We only listen at `127.0.0.1` by default, but both Chrome and Firefox probe `::1` first. Firefox then fallbacks to `127.0.0.1` but Chrome by some reason doesn't and so it never prints.

### Steps to reproduce

Printing doesn't work in Chrome out of box.
After adding
`services.printing.listenAddresses = [ "::1:631" "127.0.0.1:631" ]`
to config it starts to work again.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.16, NixOS, 18.03.git.6acfa35 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre127867.6acfa356ddc"`
 - nixpkgs: `/home/gnidorah/tmp/nixpkgs`

### PR DESCRIPTION
**Pull request by abbradar**
###### Motivation for this change

Hopefully fixes https://github.com/NixOS/nixpkgs/issues/34963, closes https://github.com/NixOS/nixpkgs/pull/35190.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Tested with `tests.printing.x86_64-linux`. `lpstat -H` points to `/var/run/cups/cups.sock` now.`

@gnidorah Can you remember any other applications with broken printing besides Chromium? It'll help to generate less heat from my machine :D

### CODE REVIEW

**Comment by gnidorah** [comment]
@abbradar Wow, awesome work, thanks! No, don't remember. Firefox worked via network port, Libreoffice and GTK programs worked too.

**Review by fpletz — APPROVED** [review]
Push to staging please as this is a mass rebuild. :)

**Comment by abbradar** [comment]
Yeah, I want to do so but am wary of changing branch in PR as this will ping a lot of people as code owners :D

**Comment by abbradar** [comment]
I want to backport it to 17.09, is it okay to cherry-pick mass rebuild changes to `release-17.09`?

**Comment by fpletz** [comment]
@abbradar Yes, it is! As I've just picked another big rebuild to 17.09 and haven triggered an evaluation on Hydra yet, wanna do it right now? :)

**Comment by abbradar** [comment]
Yep, will do. Thanks!

**Comment by abbradar** [comment]
Argh, I pushed it to master by mistake. Will revert and push to staging instead. Lesson learnt, better ping random people than push mass rebuilds to master ~_~

**Comment by fpletz** [comment]
No worries. That happens to all of us. Thanks!

**Comment by abbradar** [comment]
17.09 actually doesn't require this PR -- it's a regression, `git blame` shows e5715d94645a4.

**Pull request merged**
