### PR TITLE
perl-LWP: enable tests + a few version bumps

### PR DESCRIPTION
**Pull request by rycee**
This PR adds a patch that will enable the LWP test suite to run. It also includes a few version bumps of some LWP dependencies. I added these since the LWP change will cause fair number of packages to rebuild and it might be good to get these in at the same time.

### CODE REVIEW

**Comment by rah-mblox** [comment]
Note, the URI version bump is necessary to upgrade the Catalyst packages to a more recent version. Something I would like to do.

**Comment by rycee** [comment]
Note, the URI version bump is necessary to upgrade the Catalyst packages to a more recent version.

**Comment by vcunat** [comment]
Looks good, staged.

**Comment by edolstra** [comment]
IMHO such Perl package updates can go straight to master.

**Comment by vcunat** [comment]
I wasn't sure about the impact and someone else marked it mass-rebuild, so I didn't take chances with Hydra being overloaded now again.

**Comment by rycee** [comment]
Looking at the Travis-CI job it seemed it wanted to build some 2000 packages. I did dig into that a little and it seems that it is the cacert package that is the cause of most of the builds since cacert has a dependency on LWP.  I don't know if 2000 would be considered a mass-rebuild or not, though.

In any case, thanks for the merge.

**Comment by edolstra** [comment]
Yeah, looks like a bunch of packages have been made dependent on cacert (e.g. in cd52c044568bdf1108428698048a9af92dc0b625), which is a bad idea.

**Pull request closed without merging**
