### PR TITLE
influxdb,lexicon: fix builds

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
fix `lexicon` and `influxdb` builds, which were failing on a different review

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
```
https://github.com/NixOS/nixpkgs/pull/91180
6 packages failed to build:
ape pantalaimon python37Packages.nvchecker python37Packages.sunpy python38Packages.nvchecker python38Packages.sunpy

22 packages built:
lexicon python27Packages.influxdb python27Packages.requests-file python27Packages.tldextract python37Packages.aioresponses python37Packages.graphite_api python37Packages.influxdb python37Packages.influxgraph python37Packages.requests-file python37Packages.structlog python37Packages.tldextract python37Packages.zeep python38Packages.aioresponses python38Packages.graphite_api python38Packages.influxdb python38Packages.influxgraph python38Packages.requests-file python38Packages.structlog python38Packages.tldextract python38Packages.zeep qutebrowser sewer
```
a few of the packages are fixed by https://github.com/NixOS/nixpkgs/pull/89694 , going to merge that PR first

**Comment by gloaming** [comment]
LGTM

```
https://github.com/NixOS/nixpkgs/pull/91180
6 package failed to build:
ape python37Packages.nvchecker python37Packages.sunpy python38Packages.nvchecker python38Packages.sunpy qutebrowser

21 package were built:
lexicon python27Packages.influxdb python27Packages.requests-file python27Packages.tldextract python37Packages.aioftp python37Packages.graphite_api python37Packages.influxdb python37Packages.influxgraph python37Packages.parfive python37Packages.requests-file python37Packages.structlog python37Packages.tldextract python38Packages.aioftp python38Packages.graphite_api python38Packages.influxdb python38Packages.influxgraph python38Packages.parfive python38Packages.requests-file python38Packages.structlog python38Packages.tldextract sewer
```
```
[nix-shell:~/.cache/nix-review/pr-91180]$ nix run nixpkgs.influxdb
[2 copied (168.6 MiB), 32.7 MiB DL]
[craig@samwise:~/.cache/nix-review/pr-91180]$ influxd &
[...]
[craig@samwise:~/.cache/nix-review/pr-91180]$ python3
Python 3.8.3 (default, May 13 2020, 19:59:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import influxdb
>>> c = influxdb.client.InfluxDBClient()
>>> c.ping()
[httpd] ::1 - root [20/Jun/2020:21:37:50 +0100] "GET /ping HTTP/1.1" 204 0 "-" "python-requests/2.23.0" e8837e13-b335-11ea-8002-e0d55ee7fa14 43
'1.8.0'
```
```
[nix-shell:~/.cache/nix-review/pr-91180-1]$ lexicon --help
usage: lexicon [-h] [--version] [--delegated DELEGATED] [--config-dir CONFIG_DIR]
```

**Comment by jonringer** [comment]
doing a few more package cleanups then I'll merge

**Comment by jonringer** [comment]
@GrahamcOfBorg eval

**Comment by jonringer** [comment]
```
https://github.com/NixOS/nixpkgs/pull/91180
5 packages failed to build:
ape python37Packages.nvchecker python37Packages.sunpy python38Packages.nvchecker python38Packages.sunpy

39 packages built:
lexicon python27Packages.requests-file python27Packages.tldextract python37Packages.aioftp python37Packages.aplpy python37Packages.asdf python37Packages.extension-helpers python37Packages.graphite_api python37Packages.influxgraph python37Packages.parfive python37Packages.pyregion python37Packages.pytest-astropy python37Packages.pytest-astropy-header python37Packages.pytest-filter-subpackage python37Packages.radio_beam python37Packages.reproject python37Packages.requests-file python37Packages.spectral-cube python37Packages.structlog python37Packages.tldextract python38Packages.aioftp python38Packages.aplpy python38Packages.asdf python38Packages.extension-helpers python38Packages.graphite_api python38Packages.influxgraph python38Packages.parfive python38Packages.pyregion python38Packages.pytest-astropy python38Packages.pytest-astropy-header python38Packages.pytest-filter-subpackage python38Packages.radio_beam python38Packages.reproject python38Packages.requests-file python38Packages.spectral-cube python38Packages.structlog python38Packages.tldextract qutebrowser sewer
```

**Comment by jonringer** [comment]
seeing as almost all of these files were failures previously, I say this is some progress. Other failures can be addressed in other PRs

**Pull request merged**
