### PR TITLE
claws-mail: Fix fancy plugin

### LINKED ISSUE #10421: plugin "fancy" in Claws Mail is not working
I have `enablePluginFancy` enabled in my config:
```nix
    packageOverrides = pkgs: {
     clawsMail = pkgs.clawsMail.override { enablePluginFancy = true; };
    };
```
after loading "Fancy" plugin and opening html email, it show page source instead of rendering html.

P.S.: I don't have this issue in arch linux.

/cc @khumba

### PR DESCRIPTION
**Pull request by fpletz**
This fixes the fancy plugin displaying HTML mails as text as suggested by @wedens.

This fixes #10421.

### CODE REVIEW

**Comment by lethalman** [comment]
Note that setting `XDG_DATA_DIRS` there will replace it at build time, which is not good.

I suggest something like:
```
preFixup = ''
  gappsWrapperArgs+=(--prefix XDG_DATA_DIRS : "${shared_mime_info}/share")
'';
```

**Comment by lethalman** [comment]
Also that ` GIO_EXTRA_MODULES` wrapping is already done. Just put `glib_networking` in `buildInputs`, but that's another issue.

**Comment by fpletz** [comment]
@lethalman Thanks for the hints!

I've updated the commit with your suggestion and removed the extra `GIO_EXTRA_MODULES` wrapping. I've also checked the resulting wrapper script that everything is in there and tested the application itself. Everything's fine as far as I can see.

**Comment by vcunat** [comment]
In time it would be nice to create a hook in `shared_mime_info` to extend `gappsWrapperArgs` automatically when in build inputs. (It might cause a larger rebuild, though.)

**Pull request merged**
