### PR TITLE
loc: init at 0.3.0

### PR DESCRIPTION
**Pull request by matthiasbeyer**
###### Motivation for this change

My first rust package, please tell me how to do this properly! :smile: 
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Heavy WIP.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Updated to MIT license, see for more information: https://github.com/cgag/loc/issues/6

**Comment by gebner** [comment]
BTW, `loc` is already at version 0.3.3 now.

**Comment by matthiasbeyer** [comment]
Quick question: I was asking for review here, not for merge... because this is the first rust package I submitted and I'm rather sure it won't build, because I have close to zero knowledge of the rust packaging infrastructure in nixpkgs...

**Comment by gebner** [comment]
It's fine.  There is a typo though in the github owner, it should be `cgag` instead of `caga`.  I'll push a fix in a few minutes.

**Pull request merged**
