### PR TITLE
vimPlugins.vim-hcl: init at 2020-09-07

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
Unfortunately it hasn't been updated in a while, but it mostly adds syntax support for [hcl](https://www.nomadproject.io/docs/job-specification/hcl2) and should be mostly compatible with hcl2

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by iblech** [comment]
Thank you for your work! :-)

It's a little bit unfortunate that the upstream repos don't work with tags for the releases. That way it's not only slightly more effort for us to keep nixpkgs up to date, but also from a security perspective it's less clear that these are the actual blessed releases (instead of someone's pull request or not even that -- as I understand it, anyone can add arbitrary commits to GitHub repos (but cannot change what the "master" or "main" tag refers to)).

If you have the resources, filing upstream issues for this lack of tags might be worthwhile.

**Comment by jonringer** [comment]
> it's a little bit unfortunate that the upstream repos don't work with tags for the releases.

most vim plugins are rolling releases

**Comment by SuperSandro2000** [comment]
> It's a little bit unfortunate that the upstream repos don't work with tags for the releases.

That is a generally problem in the vim ecosystem and nothing nixpkgs can solve alone.

> If you have the resources, filing upstream issues for this lack of tags might be worthwhile.

That would be about 687 vim plugins to create for. Plug does not even have support for git tags.

> That way it's not only slightly more effort for us to keep nixpkgs up to date, but also from a security perspective it's less clear that these are the actual blessed releases

That is a general problem with GitHub. It might be worth it to look into ways to prevent those fetches completely in nixpkgs.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110390` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
9 packages built:
</summary>
<ul>
<li>spacevim</li>
<li>vimPlugins.Coqtail</li>
<li>vimPlugins.chadtree</li>
<li>vimPlugins.far-vim</li>
<li>vimPlugins.lualine-nvim</li>
<li>vimPlugins.nvim-treesitter</li>
<li>vimPlugins.playground</li>
<li>vimPlugins.vim-hcl</li>
<li>vimPlugins.vim-snipmate</li>
</ul>
</details>

**Pull request merged**
