### PR TITLE
harfbuzz: 5.3.1 -> 6.0.0

### LINKED ISSUE #180054: Harfbuzz's CMake config uses the wrong path
### Describe the bug
Trying to use harfbuzz in a CMake project, CMake fails with the following:

```
CMake Error in CMakeLists.txt:
  Imported target "harfbuzz::harfbuzz" includes non-existent path

    "/nix/store/7ahz2g1i3m2pfk96fjl6j37ldcwlxpbg-harfbuzz-3.3.2-dev//nix/store/7ahz2g1i3m2pfk96fjl6j37ldcwlxpbg-harfbuzz-3.3.2-dev/include/harfbuzz"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

That path comes from /nix/store/7ahz2g1i3m2pfk96fjl6j37ldcwlxpbg-harfbuzz-3.3.2-dev/lib/cmake/harfbuzz/harfbuzz-config.cmake, probably on line 25 which says `set(_harfbuzz_includedir "${prefix}//nix/store/7ahz2g1i3m2pfk96fjl6j37ldcwlxpbg-harfbuzz-3.3.2-dev/include")`.

### Steps To Reproduce
1. Make a CMake project that tries to link an executable to harfbuzz:
    ```
    find_package(harfbuzz REQUIRED)
    add_executable(program main.c)
    target_link_libraries(program harfbuzz::harfbuzz)
    ```
3. Try to configure project (`cmake .`)
4. See error above

### Expected behavior
The project configures successfully.

### Notify maintainers

@edolstra 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.49, NixOS, 22.11 (Raccoon), 22.11.20220627.020c740`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

### PR DESCRIPTION
**Pull request by dblsaiko**
###### Description of changes

Update HarfBuzz to version 6.0.0.

Closes #180054.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
`passthru.tests` build successfully on aarch64-linux apart from already-broken `mapnik`

**Comment by 2xsaiko** [comment]
Tests also build successfully on x86_64-linux and aarch64-darwin (including mapnik).

**Comment by alerque** [comment]
Is there anything in particular holding up this PR? We use Nix for a lot of things upstream at the SILE project and our [next release milestone](https://github.com/sile-typesetter/sile/milestone/44) supporting variable fonts is a bit held up because we can't run CI tests remotely or rebuild our website examples easily without Nix support for HarfBuzz 6!

Also as a point of reference as an avid Arch Linux user I can report that the entire distro switched to 6.x pretty painlessly. There is no known breakage moving up from older releases.

**Review by alerque — APPROVED** [review]

**Comment by risicle** [comment]
This will need to be re-targeted at `staging` using the technique described in https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging

**Review by risicle — APPROVED** [review]

**Comment by alerque** [comment]
[PR Tracker](https://nixpk.gs/pr-tracker.html?pr=207041)

**Pull request merged**
