### PR TITLE
vimPlugins: update

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change
Some of the plugins were out of date

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
do you mind rebasing on top of master? a lot of these should have been udpated
```
git pull -r origin master
git push <fork> <branch> --force
```

**Comment by lovesegfault** [comment]
@jonringer Done :)

**Comment by jonringer** [comment]
there we go, that looks better :)

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM
commits LGTM

```
https://github.com/NixOS/nixpkgs/pull/72942
4 package were build:
vimPlugins.papercolor-theme vimPlugins.plantuml-syntax vimPlugins.vim-ruby vimPlugins.vim-startify
```

**Pull request merged**
