### PR TITLE
nyxt: 2.2.3 -> 2.2.4; workaround webkit sandbox crash

### LINKED ISSUE #158005: nyxt-2.2.3: ERROR **: 00:27:46.959: Unable to configure xdg-desktop-portal access in the WebKit sandbox: GApplication is required.
### Describe the bug
When I open (C-l) a url, nyxt hangs and this message is printed in the console:

```console
** (nyxt:401949): ERROR **: 00:27:46.959: Unable to configure xdg-desktop-portal access in the WebKit sandbox: GApplication is required.
<WARN> [00:27:46] Warning: Error on GTK thread: The value
                       :INVALID-CODE-OBJECT-AT-PC
                     is not of type
                       FUNCTION
```

If I disable sandbox through `export WEBKIT_FORCE_SANDBOX=0`, no error occurs.

### Steps To Reproduce
1. open nyxt
2. open a url, e.g. https://bing.com

### Notify maintainers
@nlewo

### Metadata

```console
$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.93, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0pre20211217_6e6e998`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Description of changes

Fixes #158005.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
Was able to load a website, but did not test much more than that.

**Review by SuperSandro2000 — APPROVED** [review]
diffwise LGTM, didn't test

**Comment by kenranunderscore** [comment]
I'm running into the following error(s) on every action, even after removing `~/.cache/nyxt` and `~/.config/nyxt` using `nix run github:sternenseemann/nixpkgs/nyxt-2.2.4#nyxt`:

```
Error sending IPC message: Socket operation on non-socket
```

I could load the tabs I'd opened the time before, but couldn't, for instance, `C-l`.

Update: after removing every piece of state I could find I could start the 2.2.4 I now get the following when trying `C-l` to load a page, pretty much immediately after startup:

```
<INFO> [19:00:29] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.2.4
Could not determine the accessibility bus address
Error sending IPC message: Bad file descriptor
<WARN> [19:00:32] Warning: Web process terminated for buffer  (opening ) because it crashed
<WARN> [19:00:32] Warning: Error in signal thread: There is no applicable method for the generic function
  #&lt;STANDARD-GENERIC-FUNCTION HISTORY-TREE:OWNERS (1)&gt;
when called with arguments
  (NIL).
See also:
  The ANSI Standard, Section 7.6.6
<WARN> [19:00:32] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: 
<WARN> [19:00:32] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: 
<WARN> [19:00:32] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: 
<WARN> [19:00:32] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: 
WARNING:
   Error on separate prompter thread: The value
                                        NIL
                                      is not of type
                                        STRING
                                      when binding STRING
<WARN> [19:00:32] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: 
```

Could anyone else check if they're having the same problem? I've checked back and 2.2.3 doesn't behave this way for me.

**Comment by jian-lin** [comment]
I cherry-picked this pr onto my system, which is on f2537a505d45c31fe5d9c27ea9829b6f4c4e6ac5 and tested to load several web pages. Works well.

**Comment by kenranunderscore** [comment]
I was able to reproduce my issue on a second system, but at this point it feels like it's a general issue with 2.2.4 on my hardware/system/pin. Since I'm using a local build anyway I'd say go ahead and merge this. Pretty sure it will help lots of people who want to try out Nyxt and can't even start it from nix, as it was for me a while ago.

**Pull request merged**
