### PR TITLE
libhandy: 0.0.13 -> 1.0.1

### PR DESCRIPTION
**Pull request by wamserma**
###### Motivation for this change

Project became a proper GNOME project, version updated and URL changed.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review pr 102678"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
We already have this in staging, this on its own without many changes would cause major breakage

**Comment by omasanori** [comment]
Result of `nixpkgs-review pr 102678` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>31 packages failed to build:</summary>
  <ul>
    <li>adapta-gtk-theme</li>
    <li>calls</li>
    <li>chrome-gnome-shell</li>
    <li>contrast</li>
    <li>deja-dup</li>
    <li>epiphany (gnome3.epiphany)</li>
    <li>fractal</li>
    <li>gnome-passwordsafe</li>
    <li>gnome-podcasts</li>
    <li>gnome3.bijiben (gnome3.gnome-notes)</li>
    <li>gnome3.geary</li>
    <li>gnome3.gnome-calendar</li>
    <li>gnome3.gnome-clocks</li>
    <li>gnome3.gnome-control-center (gnome3.gnome_control_center)</li>
    <li>gnome3.gnome-session (gnome3.gnome_session)</li>
    <li>gnome3.gnome-shell (gnome3.gnome_shell)</li>
    <li>gnome3.gnome-terminal (gnome3.gnome_terminal)</li>
    <li>gnome3.gnome-tweaks (gnome3.gnome-tweak-tool)</li>
    <li>gnome3.pomodoro</li>
    <li>gnome3.seahorse</li>
    <li>gnomeExtensions.gsconnect</li>
    <li>gnomeExtensions.night-theme-switcher</li>
    <li>newsflash</li>
    <li>pantheon.appcenter</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-gsettings-schemas</li>
    <li>pantheon.elementary-onboarding</li>
    <li>pantheon.elementary-session-settings</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-with-indicators</li>
    <li>shortwave</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>gnome3.gnome-contacts</li>
    <li>libhandy</li>
  </ul>
</details>

**Comment by worldofpeace** [comment]
Yeah, and all of those breakages have already been fixed in staging. We had some issues with staging so it's taken longer than usual

**Comment by wamserma** [comment]
@worldofpeace Ah, I had missed [the PR](https://github.com/NixOS/nixpkgs/pull/98316) was to staging (just saw that the Gnome 3.38 was merged and somehow assumed it was to master where this update was missing). Good to know I don't have to fix all the breakage on my own.

w.r.t. to the above PR, this bumps the version to current (one minor release) and fixes the checkPhase - shall I retarget this to staging or wait until it has landed in master? If so, should `librsvg` go to the propagatedBuildInputs?

**Comment by wamserma** [comment]
> shall I retarget this to staging 

Done here: https://github.com/NixOS/nixpkgs/pull/102752

**Pull request closed without merging**
