### PR TITLE
[20.09] imagemagick: 6.9.11-60 -> 6.9.12-3

### PR DESCRIPTION
**Pull request by erictapen**
###### Motivation for this change

Essentially backport of #116330 

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
Did you not use `git cherry-pick -x` because the file was renamed?

**Comment by erictapen** [comment]
@dotlambda Yep, and because the version bump has a different origin. Tried to reflect that in the commit message, that it is not a cherry-pick, while still referencing the corresponding commit.

**Comment by dotlambda** [comment]
Proposal: make one commit renaming `default.nix` to `6.x.nix`. Then cherry-pick 7ac6fbfe5ae083da2020b8438ffc4e71c044ae15, 3210e91, and c528ddd. That will ease future backports.

**Comment by erictapen** [comment]
@dotlambda Makes sense to me! done.

**Review by dotlambda — APPROVED** [review]

**Pull request merged**
