### PR TITLE
prometheus-postgres-exporter: init at 0.5.1

### PR DESCRIPTION
**Pull request by fpletz**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @WilliButz

### CODE REVIEW

**Comment by Ma27** [comment]
@GrahamcOfBorg test prometheus-exporters.postgres

**Review by Ma27 — APPROVED** [review]
Neat! The diff appears to be fine, I ran the test locally and deployed the exporter to one of my machines with a postgresql service as this looks pretty interesting :) 

I'd wait for an approval of @WilliButz and ofBorg to finish, but from perspective this is good to go :+1:

**Comment by fpletz** [comment]
Added a missing description in the NixOS module and improved the test by stopping and starting PostgreSQL.

@GrahamcOfBorg test prometheus-exporters.postgres

**Comment by fpletz** [comment]
@GrahamcOfBorg test prometheus-exporters.postgres

**Review by WilliButz — APPROVED** [review]

**Pull request merged**
