### PR TITLE
[backport-21.11] evolution-data-server: 3.42.1 -> 3.42.3

### PR DESCRIPTION
**Pull request by symphorien**
###### Motivation for this change

backport of #154185

tested by rebuilding my system against it

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
```
error: attribute 'bijiben' missing

       at /???/.cache/nixpkgs-review/pr-156318-1/build.nix:20:9:

           19|         gnome-photos
           20|         gnome."bijiben"
             |         ^
           21|         gnome."file-roller"

```

**Comment by symphorien** [comment]
Hum, it looks like a bug in nixpkgs-review, given that build.nix is generated by it.

**Comment by jonringer** [comment]
> ```
> error: attribute 'bijiben' missing
> 
>        at /???/.cache/nixpkgs-review/pr-156318-1/build.nix:20:9:
> 
>            19|         gnome-photos
>            20|         gnome."bijiben"
>              |         ^
>            21|         gnome."file-roller"
> ```

addressed in https://github.com/Mic92/nixpkgs-review/pull/254

**Comment by symphorien** [comment]
master of nixpkgs-review seems ok so I'll self merge in the coming days is nobody complains.

<details>
<pre>
$  fnix run github:mic92/nixpkgs-review pr https://github.com/NixOS/nixpkgs/pull/156318#issuecomment-1027221739
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs release-21.11:refs/nixpkgs-review/0 pull/156318/head:refs/nixpkgs-review/1
Depuis https://github.com/NixOS/nixpkgs
 + 4b13f83bf08...1056d54a73a release-21.11         -> refs/nixpkgs-review/0  (mise à jour forcée)
 + 6d18192b31f...1294215caf6 refs/pull/156318/head -> refs/nixpkgs-review/1  (mise à jour forcée)
Compression automatique du dépôt en tâche de fond pour optimiser les performances.
Voir "git help gc" pour toute information sur le nettoyage manuel.
warning: Le dernier lancement de gc a rapporté l'erreur suivante. Veuillez corriger
la cause et supprimer .git/gc.log
Le nettoyage automatique n'aura pas lieu jusqu'à ce que le fichier soit supprimé.

fatal: bad object worktrees/nixpkgs1/HEAD
fatal: failed to run repack

$ git worktree add /home/symphorien/.cache/nixpkgs-review/pr-156318-2/nixpkgs 1056d54a73a7bb261e03f24358029c5caffd7867
Préparation de l'arbre de travail (HEAD détachée 1056d54a73a)
Mise à jour des fichiers: 100% (28992/28992), fait.
HEAD est maintenant à 1056d54a73a amazon-ec2-utils: 1.2 -> 2.0
$ git merge --no-commit --no-ff 1294215caf6a0f2a33f93ff824da206e750d393f
La fusion automatique a réussi ; stoppée avant la validation comme demandé
$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/symphorien/.cache/nixpkgs-review/pr-156318-2/build.nix

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/156318

12 packages marked as broken and skipped:
gnome.bijiben gnome.evolution_data_server gnome.folks gnome.gnome-documents gnome.gnome-photos gnome.gnome-tweak-tool gnome.gnome_control_center gnome.gnome_session gnome.gnome_shell gnome.gnome_terminal gnome.tracker-miners xmonad_log_applet

56 packages built:
adapta-gtk-theme almanah bubblemail calls chatty chrome-gnome-shell dropbox-cli elementary-planner empathy evolution evolution-data-server evolution-ews evolutionWithPlugins folks gnome-photos gnome.file-roller gnome.geary gnome.gnome-applets gnome.gnome-books gnome.gnome-boxes gnome.gnome-calendar gnome.gnome-contacts gnome.gnome-control-center gnome.gnome-flashback gnome.gnome-maps gnome.gnome-notes gnome.gnome-panel gnome.gnome-session gnome.gnome-shell gnome.gnome-terminal gnome.gnome-todo gnome.gnome-tweaks gnome.gnome-user-share gnome.nautilus gnome.nautilus-python gnomeExtensions.easyScreenCast gnomeExtensions.gsconnect gnomeExtensions.night-theme-switcher kgx pantheon.elementary-calendar pantheon.elementary-greeter pantheon.elementary-mail pantheon.elementary-session-settings pantheon.elementary-tasks pantheon.extra-elementary-contracts pantheon.file-roller pantheon.switchboard-plug-onlineaccounts pantheon.switchboard-with-plugs pantheon.wingpanel-applications-menu pantheon.wingpanel-indicator-datetime pantheon.wingpanel-with-indicators phosh synology-drive tracker-miners vimix-gtk-themes whitesur-gtk-theme

$ /nix/store/n8x6ig1yf8ffpa07mwvxg6b7ilrrvfy1-nix-2.4/bin/nix-shell /home/symphorien/.cache/nixpkgs-review/pr-156318-2/shell.nix
error: Package ‘dropbox’ in /home/symphorien/.cache/nixpkgs-review/pr-156318-2/nixpkgs/pkgs/applications/networking/dropbox/default.nix:80 has an unfree license (‘unfree’), refusing to evaluate.

       a) To temporarily allow unfree packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNFREE=1

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnfree = true; }
       in configuration.nix to override this.

       Alternatively you can configure a predicate to allow specific packages:
         { nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
             "dropbox"
           ];
         }

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnfree = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
$ git worktree prune
</pre>
<details>

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 156318 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>12 packages marked as broken and skipped:</summary>  <ul>    <li>gnome.bijiben</li>    <li>gnome.evolution_data_server</li>    <li>gnome.folks</li>    <li>gnome.gnome-documents</li>    <li>gnome.gnome-photos</li>    <li>gnome.gnome-tweak-tool</li>    <li>gnome.gnome_control_center</li>    <li>gnome.gnome_session</li>    <li>gnome.gnome_shell</li>    <li>gnome.gnome_terminal</li>    <li>gnome.tracker-miners</li>    <li>xmonad_log_applet</li>  </ul></details><details>  <summary>56 packages built:</summary>  <ul>    <li>adapta-gtk-theme</li>    <li>almanah</li>    <li>bubblemail</li>    <li>calls</li>    <li>chatty</li>    <li>chrome-gnome-shell</li>    <li>dropbox-cli</li>    <li>elementary-planner</li>    <li>empathy (gnome.empathy)</li>    <li>evolution</li>    <li>evolution-data-server (gnome.evolution-data-server)</li>    <li>evolution-ews</li>    <li>evolutionWithPlugins</li>    <li>folks</li>    <li>gnome-photos</li>    <li>gnome.file-roller</li>    <li>gnome.geary</li>    <li>gnome.gnome-applets</li>    <li>gnome.gnome-books</li>    <li>gnome.gnome-boxes</li>    <li>gnome.gnome-calendar</li>    <li>gnome.gnome-contacts</li>    <li>gnome.gnome-control-center</li>    <li>gnome.gnome-flashback</li>    <li>gnome.gnome-maps</li>    <li>gnome.gnome-notes</li>    <li>gnome.gnome-panel</li>    <li>gnome.gnome-session</li>    <li>gnome.gnome-shell</li>    <li>gnome.gnome-terminal</li>    <li>gnome.gnome-todo</li>    <li>gnome.gnome-tweaks</li>    <li>gnome.gnome-user-share</li>    <li>gnome.nautilus</li>    <li>gnome.nautilus-python</li>    <li>gnomeExtensions.easyScreenCast</li>    <li>gnomeExtensions.gsconnect</li>    <li>gnomeExtensions.night-theme-switcher</li>    <li>kgx</li>    <li>pantheon.elementary-calendar</li>    <li>pantheon.elementary-greeter</li>    <li>pantheon.elementary-mail</li>    <li>pantheon.elementary-session-settings</li>    <li>pantheon.elementary-tasks</li>    <li>pantheon.extra-elementary-contracts</li>    <li>pantheon.file-roller</li>    <li>pantheon.switchboard-plug-onlineaccounts</li>    <li>pantheon.switchboard-with-plugs</li>    <li>pantheon.wingpanel-applications-menu</li>    <li>pantheon.wingpanel-indicator-datetime</li>    <li>pantheon.wingpanel-with-indicators</li>    <li>phosh</li>    <li>synology-drive</li>    <li>tracker-miners</li>    <li>vimix-gtk-themes</li>    <li>whitesur-gtk-theme</li>  </ul></details>

**Pull request merged**
