### PR TITLE
nixos.display-manager: set DesktopNames from a new attribute

### LINKED ISSUE #82571: xfce, mate: preferences not shown in menu
**Describe the bug**

The default applications menu of Xfce and Mate desktop environments use to present preferences items and a control center (or similar) item for system configuration. Those items stopped appearing in the menu.

**Screenshots**

Screenshots taken for Xfce and Mate running in a local virtual machine:

Screenshot at 2020-03-14 08-17-02

Screenshot at 2020-03-14 08-13-12

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.7, NixOS, 20.09pre215947.82b54d49066 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre215947.82b54d49066"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: xfce, mate
```

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

Currently some xsession desktop files are generated automatically in NixOS for some desktop environments. In those desktop files the session name is being used also as the value for the `DesktopNames` key, which does not always work.

This PR adds a new attribute `services.xserver.desktopManager.session.desktopNames` and uses it for the value of the `DesktopNames` key in the xsession desktop file.

Fixes #82571.

See also https://github.com/NixOS/nixpkgs/pull/83589.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
@GrahamcOfBorg test xfce

**Comment by worldofpeace** [comment]
This change is safe for backport right?

**Review by jtojnar — APPROVED** [review]

**Comment by jtojnar** [comment]
Yup, should be safe.

**Comment by worldofpeace** [comment]
Verified on this branch that I could see the settings https://github.com/NixOS/nixpkgs/issues/82571 in xfce

**Comment by worldofpeace** [comment]
backports to 20.03 9108778523891fe0c4f5de5fba2d6abff1811c03 83b7dde86131228705e671f70fc49130479c6a0b.

Might need to have some actual tests eventually for this stuff.

**Pull request merged**
