### PR TITLE
picoscope: fix sources

### PR DESCRIPTION
**Pull request by Mic92**
###### Motivation for this change

got a 404 when testing: https://github.com/NixOS/nixpkgs/pull/149731

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by taku0** [comment]
It might be an upstream bug but if `LC_ALL` is `ja_JP.UTF-8`, it crashes with the following message when overriding a file:

```
(badabib:906224): Gdk-ERROR **: 16:00:36.487: The program 'badabib' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadImplementation (server does not implement operation)'.
  (Details: serial 140683 error_code 17 request_code 20 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

Steps to reproduce:

1. `LC_ALL=ja_JP.UTF-8 badabib`
2. Add an entry and `Save` a new file `New File.bib`.
   - BibTeX Key: aaa
   - Author: aaa
   - Title: aaa
3. Add another entry and hit `Save`.
   - BibTeX Key: bbb
   - Author bbb
   - Title: bbb

**Review by c0bw3b — CHANGES_REQUESTED** [review]
Already failing with 404s

Result of `nixpkgs-review pr 152437` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>picoscope</li>
  </ul>
</details>

**Comment by Mic92** [comment]
Fixed them again. Also long-term this may require a better approach (mirroring?)

**Comment by Mic92** [comment]
@GrahamcOfBorg build picoscope

**Comment by expipiplus1** [comment]
> Fixed them again. Also long-term this may require a better approach (mirroring?)

Could always email and ask for better long term hosting? The team there was pretty friendly last time I contacted them

**Pull request merged**
