### PR TITLE
staging-next 2024-12-04

### LINKED ISSUE #366088: Update request: mesa 24.2.6 → 24.3.1
## Package Information

- Package name: mesa
- Latest released version: 24.3.1
- Current version on the unstable channel: 24.2.6
- Current version on the stable/release channel: 24.2.6

## Checklist

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@K900 @primeos @vcunat 
---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by vcunat**
We ended up containing `staging` up to 2024-12-10.

##### Helpful links

- workflow docs: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#staging
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/360437
- next staging-next: https://github.com/NixOS/nixpkgs/pull/371501 
##### Important breakages
_nothing notable so far_

### CODE REVIEW

**Comment by sternenseemann** [comment]
cvs broke which is a fetcher dependency and of e.g. `nix-prefetch-scripts`:

```
gcc -DHAVE_CONFIG_H -I. -I. -I..   -Ino/include  -g -O2 -c sighandle.c
sighandle.c:44:7: error: conflicting types for 'calloc'; have 'char *(unsigned int,  unsigned int)'
   44 | char *calloc(unsigned nelem, unsigned size);
      |       ^~~~~~
In file included from system.h:39,
                 from sighandle.c:34:
/nix/store/glq602m203vqdp8kh79f8vzhsk1ny9vy-glibc-2.40-36-dev/include/stdlib.h:675:14: note: previous declaration of 'calloc' with type 'void *(long unsigned int,  long unsigned int)'
  675 | extern void *calloc (size_t __nmemb, size_t __size)
      |              ^~~~~~
sighandle.c:45:7: error: conflicting types for 'malloc'; have 'char *(unsigned int)'
   45 | char *malloc(unsigned size);
      |       ^~~~~~
/nix/store/glq602m203vqdp8kh79f8vzhsk1ny9vy-glibc-2.40-36-dev/include/stdlib.h:672:14: note: previous declaration of 'malloc' with type 'void *(long unsigned int)'
  672 | extern void *malloc (size_t __size) __THROW __attribute_malloc__
      |              ^~~~~~
```

**Comment by vcunat** [comment]
We've lost most of finished binaries due to a buildEnv fix (#363710), e.g. rebuilding darwin stdenvs, so let's pull more of `staging`, too.

**Comment by vcunat** [comment]
GHActions exploded from [the mass reformat](https://github.com/NixOS/nixpkgs/pull/364000).

**Comment by sternenseemann** [comment]
Proposed fix for cvs: #364035.

**Comment by doronbehar** [comment]
Observed a small failure on `python312Packages.freud` (that doesn't happen on `master`) when trying to build a certain Python environment from `staging-next`. The fix was clear and trivial so I pushed it straight to `staging-next`. I hope it's OK.

**Comment by spiage** [comment]
Hi, Vladimir!

I have the following issues
```
error: builder for '/nix/store/7yi36vvdbigl7qzqgi4fg5ijp68sjcwk-python3.12-ansible-core-2.17.6.drv' failed with exit code 1;
       last 25 log lines:
       > Running phase: patchPhase
       > substituteStream() in derivation python3.12-ansible-core-2.17.6: WARNING: '--replace' is deprecated, use --replace-{fail,warn,quiet}. (file 'lib/ansible/executor/task_executor.py')
       > patching script interpreter paths in packaging/cli-doc/build.py
       > packaging/cli-doc/build.py: interpreter directive changed from "#!/usr/bin/env python" to "/nix/store/c9m6yd8fg1flz2j5r4bif1ib5j20a0cy-python3-3.12.8/bin/python"
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > no configure script, doing nothing
       > Running phase: buildPhase
       > Executing pypaBuildPhase
       > Creating a wheel...
       > pypa build flags: --no-isolation --outdir dist/ --wheel
       > * Getting build dependencies for wheel...
       > running egg_info
       > writing lib/ansible_core.egg-info/PKG-INFO
       > writing dependency_links to lib/ansible_core.egg-info/dependency_links.txt
       > writing entry points to lib/ansible_core.egg-info/entry_points.txt
       > writing requirements to lib/ansible_core.egg-info/requires.txt
       > writing top-level names to lib/ansible_core.egg-info/top_level.txt
       > reading manifest file 'lib/ansible_core.egg-info/SOURCES.txt'
       > reading manifest template 'MANIFEST.in'
       > adding license file 'COPYING'
       > writing manifest file 'lib/ansible_core.egg-info/SOURCES.txt'
       >
       > ERROR Missing dependencies:
       >        setuptools<=75.3.0,>=66.1.0
       For full logs, run 'nix log /nix/store/7yi36vvdbigl7qzqgi4fg5ijp68sjcwk-python3.12-ansible-core-2.17.6.drv'.
```

```
note: keeping build directory '/tmp/nix-build-ORBit2-2.14.19.drv-2/build'
error: builder for '/nix/store/ka9w94xg5f3zbk43n4gy287bh4hppr39-ORBit2-2.14.19.drv' failed with exit code 1;
       last 25 log lines:
       > checking for utime.h... yes
       > checking sys/utime.h usability... no
       > checking sys/utime.h presence... no
       > checking for sys/utime.h... no
       > checking linux/socket.h usability... yes
       > checking linux/socket.h presence... yes
       > checking for linux/socket.h... yes
       > checking sys/sockio.h usability... no
       > checking sys/sockio.h presence... no
       > checking for sys/sockio.h... no
       > checking for an ANSI C-conforming const... yes
       > checking for inline... inline
       > checking for size_t... yes
       > checking for vprintf... yes
       > checking for _doprnt... no
       > checking for socket... yes
       > checking for gethostbyname... yes
       > checking for sigaction... yes
       > checking for syslog... yes
       > checking whether byte ordering is bigendian... no
       > configure: error:
       > Linking is badly borked on your system. Please ensure your library path is correct
       > Check config.log for details - check near the end of the log above 'failed program was'
       > Alternatively ensure that your /etc/ld.so.conf (and/or LD_LIBRARY_PATH) includes the
       > prefix you're compiling on: '/nix/store/sbv3wwpa1nnzrcg87q6khqxc17y0nzsc-ORBit2-2.14.19'
       For full logs, run 'nix log /nix/store/ka9w94xg5f3zbk43n4gy287bh4hppr39-ORBit2-2.14.19.drv'.
error: 1 dependencies of derivation '/nix/store/097yb2s04a33n7n4pwrldykfy2c6k525-gconf-3.2.6.drv' failed to build
error: 1 dependencies of derivation '/nix/store/5fgsg1rjzi7rxpxbk88c6x00k39whnid-yandex-browser-stable-24.12.1.712-1.drv' failed to build
```

```
error: builder for '/nix/store/8y7805npjq8h21khs1qhjkm3wd2y5hzp-reiser4progs-2.0.5.drv' failed with exit code 2;
       last 25 log lines:
       >   146 |                           "(%llu). Use -f to force over.",
       >   147 |                           result, block_count);
       >       |                                   ~~~~~~~~~~~
       >       |                                   |
       >       |                                   uint64_t {aka long unsigned int}
       > volume.c: At top level:
       > volume.c:174:31: error: initialization of 'int (*)(uint64_t *, uint64_t,  uint32_t,  int,  int)' {aka 'int (*)(long unsigned int *, long unsigned int,  unsigned int,  int,  int)'} from incompatible pointer type 'int (*)(uint64_t *, uint32_t,  uint64_t,  int,  int)' {aka 'int (*)(long unsigned int *, unsigned int,  long unsigned int,  int,  int)'} []
       >   174 |         .advise_stripe_size = advise_stripe_size_simple,
       >       |                               ^~~~~~~~~~~~~~~~~~~~~~~~~
       > volume.c:174:31: note: (near initialization for 'simple_vol_plug.advise_stripe_size')
       > volume.c:177:34: error: initialization of 'uint64_t (*)(uint64_t,  int)' {aka 'long unsigned int (*)(long unsigned int,  int)'} from incompatible pointer type 'uint64_t (*)(uint64_t)' {aka 'long unsigned int (*)(long unsigned int)'} []
       >   177 |         .default_data_capacity = default_data_capacity_simple
       >       |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
       > volume.c:177:34: note: (near initialization for 'simple_vol_plug.default_data_capacity')
       > volume.c:186:31: error: initialization of 'int (*)(uint64_t *, uint64_t,  uint32_t,  int,  int)' {aka 'int (*)(long unsigned int *, long unsigned int,  unsigned int,  int,  int)'} from incompatible pointer type 'int (*)(uint64_t *, uint32_t,  uint64_t,  int,  int)' {aka 'int (*)(long unsigned int *, unsigned int,  long unsigned int,  int,  int)'} []
       >   186 |         .advise_stripe_size = advise_stripe_size_asym,
       >       |                               ^~~~~~~~~~~~~~~~~~~~~~~
       > volume.c:186:31: note: (near initialization for 'asym_vol_plug.advise_stripe_size')
       > make[3]: *** [Makefile:419: libvolume_static_la-volume.lo] Error 1
       > make[3]: Leaving directory '/build/reiser4progs-2.0.5/plugin/vol'
       > make[2]: *** [Makefile:613: all-recursive] Error 1
       > make[2]: Leaving directory '/build/reiser4progs-2.0.5/plugin'
       > make[1]: *** [Makefile:463: all-recursive] Error 1
       > make[1]: Leaving directory '/build/reiser4progs-2.0.5'
       > make: *** [Makefile:372: all] Error 2
       For full logs, run 'nix log /nix/store/8y7805npjq8h21khs1qhjkm3wd2y5hzp-reiser4progs-2.0.5.drv'.
```

```
error: 1 dependencies of derivation '/nix/store/5pyrc6y1ri4f92sf067qbkckdyipa64n-partitionmanager-23.08.5.drv' failed to build
error: builder for '/nix/store/8f4qj079jqpsp420hmf0slqlhdb58xnb-freeipmi-1.6.14.drv' failed with exit code 2;
       last 25 log lines:
       > libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../config -I../common/debugutil -I../common/miscutil -I../common/portability -I../libfreeipmi/include -I../libfreeipmi/include -I../libfreeipmi -DIPMI_IPCKEY=\"/nix/store/0lnd5a6imppj11arqipq6vpkkk90ish4-freeipmi-1.6.14/var/lib/freeipmi/ipckey\" -DIPMI_DEBUG_IPCKEY=\"../libfreeipmi/driver/ipmi-semaphores.h\" -D_REENTRANT -g -O2 -c sel/ipmi-sel-string-linux-kernel.c  -fPIC -DPIC -o sel/.libs/libfreeipmi_la-ipmi-sel-string-linux-kernel.o
       > /nix/store/5mh7kaj2fyv8mk4sfq1brwxgc02884wi-bash-5.2p37/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../config  -I../common/debugutil -I../common/miscutil -I../common/portability -I../libfreeipmi/include -I../libfreeipmi/include -I../libfreeipmi -DIPMI_IPCKEY=\"/nix/store/0lnd5a6imppj11arqipq6vpkkk90ish4-freeipmi-1.6.14/var/lib/freeipmi/ipckey\" -DIPMI_DEBUG_IPCKEY=\"../libfreeipmi/driver/ipmi-semaphores.h\" -D_REENTRANT   -g -O2 -c -o sel/libfreeipmi_la-ipmi-sel-string-quanta-s99q.lo `test -f 'sel/ipmi-sel-string-quanta-s99q.c' || echo './'`sel/ipmi-sel-string-quanta-s99q.c
       > libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../config -I../common/debugutil -I../common/miscutil -I../common/portability -I../libfreeipmi/include -I../libfreeipmi/include -I../libfreeipmi -DIPMI_IPCKEY=\"/nix/store/0lnd5a6imppj11arqipq6vpkkk90ish4-freeipmi-1.6.14/var/lib/freeipmi/ipckey\" -DIPMI_DEBUG_IPCKEY=\"../libfreeipmi/driver/ipmi-semaphores.h\" -D_REENTRANT -g -O2 -c sel/ipmi-sel-string-quanta-s99q.c  -fPIC -DPIC -o sel/.libs/libfreeipmi_la-ipmi-sel-string-quanta-s99q.o
       > /nix/store/5mh7kaj2fyv8mk4sfq1brwxgc02884wi-bash-5.2p37/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../config  -I../common/debugutil -I../common/miscutil -I../common/portability -I../libfreeipmi/include -I../libfreeipmi/include -I../libfreeipmi -DIPMI_IPCKEY=\"/nix/store/0lnd5a6imppj11arqipq6vpkkk90ish4-freeipmi-1.6.14/var/lib/freeipmi/ipckey\" -DIPMI_DEBUG_IPCKEY=\"../libfreeipmi/driver/ipmi-semaphores.h\" -D_REENTRANT   -g -O2 -c -o sel/libfreeipmi_la-ipmi-sel-string-sun-x4140.lo `test -f 'sel/ipmi-sel-string-sun-x4140.c' || echo './'`sel/ipmi-sel-string-sun-x4140.c
       > libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../config -I../common/debugutil -I../common/miscutil -I../common/portability -I../libfreeipmi/include -I../libfreeipmi/include -I../libfreeipmi -DIPMI_IPCKEY=\"/nix/store/0lnd5a6imppj11arqipq6vpkkk90ish4-freeipmi-1.6.14/var/lib/freeipmi/ipckey\" -DIPMI_DEBUG_IPCKEY=\"../libfreeipmi/driver/ipmi-semaphores.h\" -D_REENTRANT -g -O2 -c sel/ipmi-sel-string-sun-x4140.c  -fPIC -DPIC -o sel/.libs/libfreeipmi_la-ipmi-sel-string-sun-x4140.o
       > /nix/store/5mh7kaj2fyv8mk4sfq1brwxgc02884wi-bash-5.2p37/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../config  -I../common/debugutil -I../common/miscutil -I../common/portability -I../libfreeipmi/include -I../libfreeipmi/include -I../libfreeipmi -DIPMI_IPCKEY=\"/nix/store/0lnd5a6imppj11arqipq6vpkkk90ish4-freeipmi-1.6.14/var/lib/freeipmi/ipckey\" -DIPMI_DEBUG_IPCKEY=\"../libfreeipmi/driver/ipmi-semaphores.h\" -D_REENTRANT   -g -O2 -c -o sel/libfreeipmi_la-ipmi-sel-string-supermicro-common.lo `test -f 'sel/ipmi-sel-string-supermicro-common.c' || echo './'`sel/ipmi-sel-string-supermicro-common.c
       > libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../config -I../common/debugutil -I../common/miscutil -I../common/portability -I../libfreeipmi/include -I../libfreeipmi/include -I../libfreeipmi -DIPMI_IPCKEY=\"/nix/store/0lnd5a6imppj11arqipq6vpkkk90ish4-freeipmi-1.6.14/var/lib/freeipmi/ipckey\" -DIPMI_DEBUG_IPCKEY=\"../libfreeipmi/driver/ipmi-semaphores.h\" -D_REENTRANT -g -O2 -c sel/ipmi-sel-string-supermicro-common.c  -fPIC -DPIC -o sel/.libs/libfreeipmi_la-ipmi-sel-string-supermicro-common.o
       > /nix/store/5mh7kaj2fyv8mk4sfq1brwxgc02884wi-bash-5.2p37/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../config  -I../common/debugutil -I../common/miscutil -I../common/portability -I../libfreeipmi/include -I../libfreeipmi/include -I../libfreeipmi -DIPMI_IPCKEY=\"/nix/store/0lnd5a6imppj11arqipq6vpkkk90ish4-freeipmi-1.6.14/var/lib/freeipmi/ipckey\" -DIPMI_DEBUG_IPCKEY=\"../libfreeipmi/driver/ipmi-semaphores.h\" -D_REENTRANT   -g -O2 -c -o sel/libfreeipmi_la-ipmi-sel-string-supermicro-overheat-common.lo `test -f 'sel/ipmi-sel-string-supermicro-overheat-common.c' || echo './'`sel/ipmi-sel-string-supermicro-overheat-common.c
       > libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../config -I../common/debugutil -I../common/miscutil -I../common/portability -I../libfreeipmi/include -I../libfreeipmi/include -I../libfreeipmi -DIPMI_IPCKEY=\"/nix/store/0lnd5a6imppj11arqipq6vpkkk90ish4-freeipmi-1.6.14/var/lib/freeipmi/ipckey\" -DIPMI_DEBUG_IPCKEY=\"../libfreeipmi/driver/ipmi-semaphores.h\" -D_REENTRANT -g -O2 -c sel/ipmi-sel-string-supermicro-overheat-common.c  -fPIC -DPIC -o sel/.libs/libfreeipmi_la-ipmi-sel-string-supermicro-overheat-common.o
       > /nix/store/5mh7kaj2fyv8mk4sfq1brwxgc02884wi-bash-5.2p37/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../config  -I../common/debugutil -I../common/miscutil -I../common/portability -I../libfreeipmi/include -I../libfreeipmi/include -I../libfreeipmi -DIPMI_IPCKEY=\"/nix/store/0lnd5a6imppj11arqipq6vpkkk90ish4-freeipmi-1.6.14/var/lib/freeipmi/ipckey\" -DIPMI_DEBUG_IPCKEY=\"../libfreeipmi/driver/ipmi-semaphores.h\" -D_REENTRANT   -g -O2 -c -o sel/libfreeipmi_la-ipmi-sel-string-supermicro-magnum-technologies-x8dtl.lo `test -f 'sel/ipmi-sel-string-supermicro-magnum-technologies-x8dtl.c' || echo './'`sel/ipmi-sel-string-supermicro-magnum-technologies-x8dtl.c
       > libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../config -I../common/debugutil -I../common/miscutil -I../common/portability -I../libfreeipmi/include -I../libfreeipmi/include -I../libfreeipmi -DIPMI_IPCKEY=\"/nix/store/0lnd5a6imppj11arqipq6vpkkk90ish4-freeipmi-1.6.14/var/lib/freeipmi/ipckey\" -DIPMI_DEBUG_IPCKEY=\"../libfreeipmi/driver/ipmi-semaphores.h\" -D_REENTRANT -g -O2 -c sel/ipmi-sel-string-supermicro-magnum-technologies-x8dtl.c  -fPIC -DPIC -o sel/.libs/libfreeipmi_la-ipmi-sel-string-supermicro-magnum-technologies-x8dtl.o
       > /nix/store/5mh7kaj2fyv8mk4sfq1brwxgc02884wi-bash-5.2p37/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../config  -I../common/debugutil -I../common/miscutil -I../common/portability -I../libfreeipmi/include -I../libfreeipmi/include -I../libfreeipmi -DIPMI_IPCKEY=\"/nix/store/0lnd5a6imppj11arqipq6vpkkk90ish4-freeipmi-1.6.14/var/lib/freeipmi/ipckey\" -DIPMI_DEBUG_IPCKEY=\"../libfreeipmi/driver/ipmi-semaphores.h\" -D_REENTRANT   -g -O2 -c -o sel/libfreeipmi_la-ipmi-sel-string-supermicro-peppercon-common.lo `test -f 'sel/ipmi-sel-string-supermicro-peppercon-common.c' || echo './'`sel/ipmi-sel-string-supermicro-peppercon-common.c
       > libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../config -I../common/debugutil -I../common/miscutil -I../common/portability -I../libfreeipmi/include -I../libfreeipmi/include -I../libfreeipmi -DIPMI_IPCKEY=\"/nix/store/0lnd5a6imppj11arqipq6vpkkk90ish4-freeipmi-1.6.14/var/lib/freeipmi/ipckey\" -DIPMI_DEBUG_IPCKEY=\"../libfreeipmi/driver/ipmi-semaphores.h\" -D_REENTRANT -g -O2 -c sel/ipmi-sel-string-supermicro-peppercon-common.c  -fPIC -DPIC -o sel/.libs/libfreeipmi_la-ipmi-sel-string-supermicro-peppercon-common.o
       > /nix/store/5mh7kaj2fyv8mk4sfq1brwxgc02884wi-bash-5.2p37/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../config  -I../common/debugutil -I../common/miscutil -I../common/portability -I../libfreeipmi/include -I../libfreeipmi/include -I../libfreeipmi -DIPMI_IPCKEY=\"/nix/store/0lnd5a6imppj11arqipq6vpkkk90ish4-freeipmi-1.6.14/var/lib/freeipmi/ipckey\" -DIPMI_DEBUG_IPCKEY=\"../libfreeipmi/driver/ipmi-semaphores.h\" -D_REENTRANT   -g -O2 -c -o sel/libfreeipmi_la-ipmi-sel-string-supermicro-x10dimm-common.lo `test -f 'sel/ipmi-sel-string-supermicro-x10dimm-common.c' || echo './'`sel/ipmi-sel-string-supermicro-x10dimm-common.c
       > libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../config -I../common/debugutil -I../common/miscutil -I../common/portability -I../libfreeipmi/include -I../libfreeipmi/include -I../libfreeipmi -DIPMI_IPCKEY=\"/nix/store/0lnd5a6imppj11arqipq6vpkkk90ish4-freeipmi-1.6.14/var/lib/freeipmi/ipckey\" -DIPMI_DEBUG_IPCKEY=\"../libfreeipmi/driver/ipmi-semaphores.h\" -D_REENTRANT -g -O2 -c sel/ipmi-sel-string-supermicro-x10dimm-common.c  -fPIC -DPIC -o sel/.libs/libfreeipmi_la-ipmi-sel-string-supermicro-x10dimm-common.o
       > sel/ipmi-sel-string-supermicro-x10dimm-common.c: In function 'sel_string_output_supermicro_x10dimm_event_data2_event_data3':
       > sel/ipmi-sel-string-supermicro-x10dimm-common.c:87:14: error: implicit declaration of function 'sel_string_output_supermicro_dimm_event_data2_event_data3'; did you mean 'sel_string_output_supermicro_x10dimm_event_data2_event_data3'? []
       >    87 |   if ((ret = sel_string_output_supermicro_dimm_event_data2_event_data3 (ctx,
       >       |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       >       |              sel_string_output_supermicro_x10dimm_event_data2_event_data3
       > make[2]: *** [Makefile:2700: sel/libfreeipmi_la-ipmi-sel-string-supermicro-x10dimm-common.lo] Error 1
       > make[2]: Leaving directory '/build/freeipmi-1.6.14/libfreeipmi'
       > make[1]: *** [Makefile:3005: all-recursive] Error 1
       > make[1]: Leaving directory '/build/freeipmi-1.6.14/libfreeipmi'
       > make: *** [Makefile:602: all-recursive] Error 1
       For full logs, run 'nix log /nix/store/8f4qj079jqpsp420hmf0slqlhdb58xnb-freeipmi-1.6.14.drv'.
error: 1 dependencies of derivation '/nix/store/9adizdyjl3n66cj99xvb3gnfafafx5ji-hardcode-paths.patch.drv' failed to build
error: 2 dependencies of derivation '/nix/store/mzpx01ys8dhcf18vsvy78bg80vjmz86g-nut-2.8.2.drv' failed to build
```

```
error: builder for '/nix/store/gr3548r1724wgc972k14bhyv0gwd9yi2-wesnoth-1.18.2.drv' failed with exit code 2;
       last 25 log lines:
       >   933 |         const std::vector<std::string>& paths = filesystem::get_binary_paths("images");
       >       |                                         ^~~~~
       > /build/source/src/picture.cpp:933:77: note: the temporary was destroyed at the end of the full expression 'filesystem::get_binary_paths(std::__cxx11::basic_string<char>(((const char*)"images"), std::allocator<char>()))'
       >   933 |         const std::vector<std::string>& paths = filesystem::get_binary_paths("images");
       >       |                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
       > [ 97%] Building CXX object src/CMakeFiles/wesnoth-client.dir/widgets/textbox.cpp.o
       > [ 97%] Building CXX object src/CMakeFiles/wesnoth-client.dir/widgets/widget.cpp.o
       > [ 97%] Building CXX object src/CMakeFiles/wesnoth-client.dir/wml_exception.cpp.o
       > [ 98%] Building CXX object src/CMakeFiles/wesnoth-client.dir/desktop/dbus_features.cpp.o
       > [ 98%] Building CXX object src/CMakeFiles/wesnoth-client.dir/sdl/exception.cpp.o
       > [ 98%] Building CXX object src/CMakeFiles/wesnoth-client.dir/sdl/rect.cpp.o
       > [ 98%] Building CXX object src/CMakeFiles/wesnoth-client.dir/sdl/surface.cpp.o
       > [ 98%] Building CXX object src/CMakeFiles/wesnoth-client.dir/sdl/utils.cpp.o
       > [ 98%] Building CXX object src/CMakeFiles/wesnoth-client.dir/sdl/window.cpp.o
       > [ 99%] Building CXX object src/CMakeFiles/wesnoth-client.dir/xBRZ/xbrz.cpp.o
       > /build/source/src/theme.cpp: In constructor 'theme::menu::menu(std::size_t, std::size_t, const config&)':
       > /build/source/src/theme.cpp:523:21: warning: possibly dangling reference to a temporary []
       >   523 |         const auto& cmd = hotkey::get_hotkey_command(items_[0]["id"]);
       >       |                     ^~~
       > /build/source/src/theme.cpp:523:53: note: the temporary was destroyed at the end of the full expression 'hotkey::get_hotkey_command(config_attribute_value::operator std::string() const())'
       >   523 |         const auto& cmd = hotkey::get_hotkey_command(items_[0]["id"]);
       >       |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
       > [ 99%] Linking CXX static library libwesnoth-client.a
       > [ 99%] Built target wesnoth-client
       > make: *** [Makefile:156: all] Error 2
       For full logs, run 'nix log /nix/store/gr3548r1724wgc972k14bhyv0gwd9yi2-wesnoth-1.18.2.drv'.
```

```
note: keeping build directory '/tmp/nix-build-syslinux-unstable-2019-02-07.drv-2/build'
error: builder for '/nix/store/wxw7sqwsskv6kg7b6j20zai8fhzkmxh9-syslinux-unstable-2019-02-07.drv' failed with exit code 2;
       last 25 log lines:
       > /build/source/com32/chain/chain.c:172:35: warning: cast from pointer to integer of different size []
       >   172 |                                   (addr_t) data[i].data, data[i].size))
       >       |                                   ^
       > /build/source/com32/chain/chain.c:246:53: warning: cast from pointer to integer of different size []
       >   246 |         if (syslinux_add_movelist(&mlist, endimage, (addr_t) swapstub,
       >       |                                                     ^
       > /build/source/com32/chain/chain.c: In function 'main':
       > /build/source/com32/chain/chain.c:517:44: error: passing argument 3 of 'loadfile' from incompatible pointer type []
       >   517 |         if (loadfile(opt.file, &fdat.data, &fdat.size)) {
       >       |                                            ^~~~~~~~~~
       >       |                                            |
       >       |                                            addr_t * {aka unsigned int *}
       > In file included from /build/source/com32/chain/chain.c:32:
       > /build/source/com32/include/syslinux/loadfile.h:11:37: note: expected 'size_t *' {aka 'long unsigned int *'} but argument is of type 'addr_t *' {aka 'unsigned int *'}
       >    11 | int loadfile(const char *, void **, size_t *);
       >       |                                     ^~~~~~~~
       > make[4]: *** [/build/source/com32/chain/Makefile:28: chain.o] Error 1
       > make[4]: Leaving directory '/build/source/efi64/com32/chain'
       > make[3]: *** [/build/source/com32/Makefile:8: chain] Error 2
       > make[3]: Leaving directory '/build/source/efi64/com32'
       > make[2]: *** [/build/source/Makefile:288: com32] Error 2
       > make[2]: Leaving directory '/build/source/efi64'
       > make[1]: *** [/build/source/Makefile:272: efi64] Error 2
       > make[1]: Leaving directory '/build/source'
       > make: *** [Makefile:102: bios] Error 2
       For full logs, run 'nix log /nix/store/wxw7sqwsskv6kg7b6j20zai8fhzkmxh9-syslinux-unstable-2019-02-07.drv'.
```

**Comment by spiage** [comment]
Do we need to open the issues for this build errors?

**Comment by vcunat** [comment]
Ideally pull requests :-D

**Pull request merged**
