### PR TITLE
Rename incorrectly named vim Dracula plugin

### PR DESCRIPTION
**Pull request by nasadorian**
The Dracula plugin for vim seems to be named `vim` due to the automation script and the structure of the repo `dracula/vim`. Updating the name of the package to not have a name collision with `vim` itself, and use the appropriate name for the plugin. https://github.com/dracula/vim/

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by prusnak — APPROVED** [review]

**Review by prusnak — CHANGES_REQUESTED** [review]
Use the following commit message:

`vimPlugins.dracula: use the correct name for the package`

**Comment by nasadorian** [comment]
@prusnak amended the commit message.

**Review by prusnak — APPROVED** [review]

**Comment by jonringer** [comment]
I'm afraid this will be overwritten next time someone updates the package set... We would need to fix the name of the repo itself

**Comment by nasadorian** [comment]
@jonringer Another option would be to special-case the script to avoid using the key `vim` and defaulting to `owner-repo`. So in this case `dracula-vim` would be the resulting key.

**Comment by jonringer** [comment]
I think this could lead to some odd behavior, I would like to hear from some others that use vim

cc @timokau  @colemickens @Mic92 @teto

**Comment by teto** [comment]
we could change vim-plugin-names format to be able to specify the nix attribute name. This is how I addressed it for the lua ecosystem (see https://github.com/NixOS/nixpkgs/blob/master/maintainers/scripts/luarocks-packages.csv , haskell has a similar .yaml configuration).
It may sound overkill but I believe we will eventually get there to specify a maintainer or pin a version when the need arises (some plugins are more complex than others, aka coc.nvim/unicode.vim etc).

At some point, we might want to standardize such a configuration file across the different "language packages to nix derivation" ecosystems.

**Comment by jonringer** [comment]
I think having a mechanism to do some of the renaming makes sense

**Comment by timokau** [comment]
That was already implemented by @gjabell a while ago in 8eb8fa153e3ac796566fbd2077360c63918c74d3. You can just specify `dracula/vim as dracula-vim` in `vim-plugin-names`.

**Comment by jonringer** [comment]
> That was already implemented by @gjabell a while ago in [8eb8fa1](https://github.com/NixOS/nixpkgs/commit/8eb8fa153e3ac796566fbd2077360c63918c74d3). You can just specify `dracula/vim as dracula-vim` in `vim-plugin-names`.

good point, I totally forgot about that indirection

**Comment by nasadorian** [comment]
@timokau @jonringer Does that mean I should just edit https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vim-plugins/vim-plugin-names and submit a new PR? Do I have to run the update script myself or does the build do that?

**Comment by jonringer** [comment]
you can see there's a similar example:
```
gruvbox-community/gruvbox as gruvbox-community
```
I would just edit it to say:
```
dracula/vim as dracula-vim
```
and then re-run the update.py

**Pull request closed without merging**
