### PR TITLE
jsonnet: Fix build failures on Darwin

### PR DESCRIPTION
**Pull request by benley**
## Description of changes

Jekyll fails to build on Darwin due to downstream failures in nokogiri.  I suspect nobody actually uses the docs output from this package, so we can just skip building docs on Darwin for now.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 286572` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>jsonnet</li>
  </ul>
</details>

**Comment by siraben** [comment]
Can you post the failure logs when you try to build docs on darwin?

**Comment by benley** [comment]
> Can you post the failure logs when you try to build docs on darwin?

It's visible on hydra, e.g. https://hydra.nixos.org/build/247529793

The actual failure is in Jekyll, which fails while building nokogiri: https://cache.nixos.org/log/i3413x8ilxh853crcibnbxcy8bdb8z8z-ruby3.1-nokogiri-1.13.9.drv

```
Running phase: unpackPhase
Running phase: patchPhase
Running phase: configurePhase
no configure script, doing nothing
Running phase: installPhase
buildFlags: --use-system-libraries --with-zlib-lib=/nix/store/xpq6sdqx4g4fzbwv38nkpfggs2z8784x-zlib-1.3/lib --with-zlib-include=/nix/store/v9r5skd46b87y64nyhf7l3r4s1nw45h2-zlib-1.3-dev/include --with-xml2-lib=/nix/store/6l8z385b8hbdlg5arr380av0i93n2l25-libxml2-2.12.3-unstable-2023-12-14/lib --with-xml2-include=/nix/store/wjnvyczdic0nkzzp3sz0k1vryd7zqm8p-libxml2-2.12.3-unstable-2023-12-14-dev/include/libxml2 --with-xslt-lib=/nix/store/x94049x2k17anfl8maiikcxhmv3qwv4m-libxslt-1.1.39/lib --with-xslt-include=/nix/store/9zddx6s4w01hll2rc1yxi77h67hh4m08-libxslt-1.1.39-dev/include --with-exslt-lib=/nix/store/x94049x2k17anfl8maiikcxhmv3qwv4m-libxslt-1.1.39/lib --with-exslt-include=/nix/store/9zddx6s4w01hll2rc1yxi77h67hh4m08-libxslt-1.1.39-dev/include --with-iconv-dir=/nix/store/h8x57jsgrfbvfkbdybfr9hi5w292fm0x-libiconv-50 --with-opt-include=/nix/store/h8x57jsgrfbvfkbdybfr9hi5w292fm0x-libiconv-50/include
WARNING:  You build with buildroot.
  Build root: /
  Bin dir: /nix/store/jlk7lx9pchf2h1wgph36m1m1pnbqhh53-ruby3.1-nokogiri-1.13.9/lib/ruby/gems/3.1.0/bin
  Gem home: /nix/store/jlk7lx9pchf2h1wgph36m1m1pnbqhh53-ruby3.1-nokogiri-1.13.9/lib/ruby/gems/3.1.0
  Plugins dir: /nix/store/jlk7lx9pchf2h1wgph36m1m1pnbqhh53-ruby3.1-nokogiri-1.13.9/lib/ruby/gems/3.1.0/plugins
Building native extensions with: '--use-system-libraries --with-zlib-lib=/nix/store/xpq6sdqx4g4fzbwv38nkpfggs2z8784x-zlib-1.3/lib --with-zlib-include=/nix/store/v9r5skd46b87y64nyhf7l3r4s1nw45h2-zlib-1.3-dev/include --with-xml2-lib=/nix/store/6l8z385b8hbdlg5arr380av0i93n2l25-libxml2-2.12.3-unstable-2023-12-14/lib --with-xml2-include=/nix/store/wjnvyczdic0nkzzp3sz0k1vryd7zqm8p-libxml2-2.12.3-unstable-2023-12-14-dev/include/libxml2 --with-xslt-lib=/nix/store/x94049x2k17anfl8maiikcxhmv3qwv4m-libxslt-1.1.39/lib --with-xslt-include=/nix/store/9zddx6s4w01hll2rc1yxi77h67hh4m08-libxslt-1.1.39-dev/include --with-exslt-lib=/nix/store/x94049x2k17anfl8maiikcxhmv3qwv4m-libxslt-1.1.39/lib --with-exslt-include=/nix/store/9zddx6s4w01hll2rc1yxi77h67hh4m08-libxslt-1.1.39-dev/include --with-iconv-dir=/nix/store/h8x57jsgrfbvfkbdybfr9hi5w292fm0x-libiconv-50 --with-opt-include=/nix/store/h8x57jsgrfbvfkbdybfr9hi5w292fm0x-libiconv-50/include'
This could take a while...
ERROR:  Error installing /nix/store/65bx0g9xjvvkcwfw7dp1b0bz50g315ms-nokogiri-1.13.9.gem:
        ERROR: Failed to build gem native extension.

    current directory: /nix/store/jlk7lx9pchf2h1wgph36m1m1pnbqhh53-ruby3.1-nokogiri-1.13.9/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9/ext/nokogiri
/nix/store/rn192i32ac5h9jfgcdxanl8b6z8a0vbz-ruby-3.1.4/bin/ruby extconf.rb --use-system-libraries --with-zlib-lib\=/nix/store/xpq6sdqx4g4fzbwv38nkpfggs2z8784x-zlib-1.3/lib --with-zlib-include\=/nix/store/v9r5skd46b87y64nyhf7l3r4s1nw45h2-zlib-1.3-dev/include --with-xml2-lib\=/nix/store/6l8z385b8hbdlg5arr380av0i93n2l25-libxml2-2.12.3-unstable-2023-12-14/lib --with-xml2-include\=/nix/store/wjnvyczdic0nkzzp3sz0k1vryd7zqm8p-libxml2-2.12.3-unstable-2023-12-14-dev/include/libxml2 --with-xslt-lib\=/nix/store/x94049x2k17anfl8maiikcxhmv3qwv4m-libxslt-1.1.39/lib --with-xslt-include\=/nix/store/9zddx6s4w01hll2rc1yxi77h67hh4m08-libxslt-1.1.39-dev/include --with-exslt-lib\=/nix/store/x94049x2k17anfl8maiikcxhmv3qwv4m-libxslt-1.1.39/lib --with-exslt-include\=/nix/store/9zddx6s4w01hll2rc1yxi77h67hh4m08-libxslt-1.1.39-dev/include --with-iconv-dir\=/nix/store/h8x57jsgrfbvfkbdybfr9hi5w292fm0x-libiconv-50 --with-opt-include\=/nix/store/h8x57jsgrfbvfkbdybfr9hi5w292fm0x-libiconv-50/include
checking for whether -std=c99 is accepted as CFLAGS... yes
checking for whether -Wno-declaration-after-statement is accepted as CFLAGS... yes
checking for whether -g is accepted as CFLAGS... yes
checking for whether -Winline is accepted as CFLAGS... yes
checking for whether -Wmissing-noreturn is accepted as CFLAGS... yes
checking for whether -Wno-error=unused-command-line-argument-hard-error-in-future is accepted as CFLAGS... no
Building nokogiri using system libraries.
checking for gzdopen() in -lz... yes
checking for xmlParseDoc() in -lxml2... yes
checking for xsltParseStylesheetDoc() in -lxslt... yes
checking for exsltFuncRegister() in -lexslt... yes
Using mini_portile version 2.8.0
---------- IMPORTANT NOTICE ----------
Building Nokogiri with a packaged version of libgumbo-1.0.0-nokogiri.
Configuration options: --enable-shared --disable-static
[]
Copying gumbo-parser files into tmp/x86_64-apple-darwin22/ports/libgumbo/1.0.0-nokogiri/gumbo-parser...
Running 'compile' for libgumbo 1.0.0-nokogiri... OK
Activating libgumbo 1.0.0-nokogiri (from ports/x86_64-darwin22/libgumbo/1.0.0-nokogiri)...
checking for whether -I/nix/store/jlk7lx9pchf2h1wgph36m1m1pnbqhh53-ruby3.1-nokogiri-1.13.9/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9/ext/nokogiri/ports/x86_64-darwin22/libgumbo/1.0.0-nokogiri/include is accepted as CPPFLAGS... yes
checking for gumbo_parse_with_options() in gumbo.h... yes
checking for xmlHasFeature()... yes
checking for xmlFirstElementChild()... yes
checking for xmlRelaxNGSetParserStructuredErrors()... yes
checking for xmlRelaxNGSetValidStructuredErrors()... yes
checking for xmlSchemaSetValidStructuredErrors()... yes
checking for xmlSchemaSetParserStructuredErrors()... yes
checking for rb_gc_location()... yes
checking for rb_category_warning()... yes
checking for vasprintf()... yes
checking for whether -DNOKOGIRI_OTHER_LIBRARY_VERSIONS="\"libgumbo:1.0.0-nokogiri\"" is accepted as CPPFLAGS... yes
creating Makefile

current directory: /nix/store/jlk7lx9pchf2h1wgph36m1m1pnbqhh53-ruby3.1-nokogiri-1.13.9/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9/ext/nokogiri
make DESTDIR\= sitearchdir\=./.gem.20240125-5258-dxffsr sitelibdir\=./.gem.20240125-5258-dxffsr clean

current directory: /nix/store/jlk7lx9pchf2h1wgph36m1m1pnbqhh53-ruby3.1-nokogiri-1.13.9/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9/ext/nokogiri
make DESTDIR\= sitearchdir\=./.gem.20240125-5258-dxffsr sitelibdir\=./.gem.20240125-5258-dxffsr
compiling gumbo.c
gumbo.c:284:57: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]
      rb_iv_set(syntax_error, "@line", INT2NUM(position.line));
                                       ~~~~~~~ ~~~~~~~~~^~~~
gumbo.c:289:59: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]
      rb_iv_set(syntax_error, "@column", INT2NUM(position.column));
                                         ~~~~~~~ ~~~~~~~~~^~~~~~
gumbo.c:504:30: warning: implicit conversion loses integer precision: 'VALUE' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]
                             rb_utf8_str_new_static("encoding", 8));
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 warnings generated.
compiling html4_document.c
html4_document.c:49:52: error: incompatible function pointer types passing 'void (void *, xmlErrorPtr)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
  xmlSetStructuredErrorFunc((void *)rb_error_list, Nokogiri_error_array_pusher);
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/wjnvyczdic0nkzzp3sz0k1vryd7zqm8p-libxml2-2.12.3-unstable-2023-12-14-dev/include/libxml2/libxml/xmlerror.h:898:29: note: passing argument to parameter 'handler' here
                                 xmlStructuredErrorFunc handler);
                                                        ^
html4_document.c:109:52: error: incompatible function pointer types passing 'void (void *, xmlErrorPtr)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
  xmlSetStructuredErrorFunc((void *)rb_error_list, Nokogiri_error_array_pusher);
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/wjnvyczdic0nkzzp3sz0k1vryd7zqm8p-libxml2-2.12.3-unstable-2023-12-14-dev/include/libxml2/libxml/xmlerror.h:898:29: note: passing argument to parameter 'handler' here
                                 xmlStructuredErrorFunc handler);
                                                        ^
html4_document.c:149:18: warning: implicit conversion loses integer precision: 'long' to 'int' [-Wshorten-64-to-32]
  return INT2NUM((long)doc->type);
         ~~~~~~~ ^~~~~~~~~~~~~~~
1 warning and 2 errors generated.
make: *** [Makefile:247: html4_document.o] Error 1

make failed, exit code 2

Gem files will remain installed in /nix/store/jlk7lx9pchf2h1wgph36m1m1pnbqhh53-ruby3.1-nokogiri-1.13.9/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9 for inspection.
Results logged to /nix/store/jlk7lx9pchf2h1wgph36m1m1pnbqhh53-ruby3.1-nokogiri-1.13.9/lib/ruby/gems/3.1.0/extensions/x86_64-darwin-22/3.1.0/nokogiri-1.13.9/gem_make.out
```

**Comment by szlend** [comment]
In nixpkgs these errors have been typically worked around with:

```
env = lib.optionalAttrs stdenv.cc.isClang {
    NIX_CFLAGS_COMPILE = "-Wno-error=incompatible-function-pointer-types";
};
```

Though I'm not sure how to apply this to `nokogiri` specifically, since that derivation is generated from a gemset.

**Comment by szlend** [comment]
We could probably set `nokogiri` cflags using `gemConfig` like so: 

https://github.com/NixOS/nixpkgs/blob/8f7fe95a8d428e908d1e8fd6263bd2df1b6cd07c/pkgs/applications/networking/misc/zammad/default.nix#L76-L94

**Comment by szlend** [comment]
Alternatively we can update jekyll (#291645) or silence clang errors (#291645).

**Comment by wegank** [comment]
Done in #291659.

**Pull request closed without merging**
