### PR TITLE
consul: 0.5.2 -> 0.6.4 (using go 1.6)

### PR DESCRIPTION
**Pull request by nshalman**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [x] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Upgrades:
consul: 0.5.2 -> 0.6.4 (using go 1.6)
consul-ui: 0.5.2 -> 0.6.4 (using go 1.6)
consul-alerts: 2015-08-09 -> 0.3.3 (using go 1.6)
consul-template: 0.9.0 -> 0.14.0 (using go 1.6)
vault: 0.2.0 -> 0.5.2 (using go 1.6)

### CODE REVIEW

**Comment by nshalman** [comment]
Clearly a bunch of stuff depends on consul. Ball is in my court.

**Comment by nshalman** [comment]
Not sure how to get Travis to rerun the test or how to get the mention bot to look at this, but I'll ping @cstrahan and @kamilchm for now.

**Comment by nshalman** [comment]
I also wonder if it's time to change the default go compiler in `pkgs/top-level/all-packages.nix`:
```diff
-goPackages = go15Packages;
+goPackages = go16Packages
```

Doing so would let me remove some ugly hunks of this commit...

Thoughts?

**Comment by nshalman** [comment]
Travis build failure appears to be network related. I ran `nox-review wip --against master` successfully on my machine.

**Comment by joachifm** [comment]
Thank you

**Pull request merged**
