### PR TITLE
modules/sshd: check for duplicate config keys

### PR DESCRIPTION
**Pull request by nyanotech**
###### Description of changes

In #193757, sshd's settings were switched to freeform config generation. This is fine and dandy, unless you're a dunce like me and just copy-pasted your old config lines down into a `settings` block, without noticing that the first character of the option name is supposed to be uppercased now.

sshd setting names are not case sensitive, and it takes the first value it sees for a given key, therefore, in this case, since the lowercased keys end up on the bottom of the list, they get overridden by the default values. This is a completely legal thing to do in a config, therefore it doesn't get caught by the config validation, unlike if one were to use invalid keys.

This commit adds an assertion that looks for duplicate keys (case-insensitive) in the config attrset in order to hopefully eliminate this footgun.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nyanotech** [comment]
I'm not familiar with nix lang; there's probably a cleaner/better way to write this.

On a similar note, should we move the `extraConfig` contents to the top of the file? It would prevent values from being overridden by defaults if we add more defined settings later.

**Comment by teto** [comment]
Thanks for the PR @nyanotech . This is a real concern. I believe an even better solution would be to standardize the case in the module system so it could detect setting duplication itself ? But it looks like a difficult change also release is closing in so your fix could at least provide some safeguard for the release.

A few things:
- the current error message could be improved to explain why it's a problem to have duplicated settings (aka ssh will ignore the subsequent ones
- it will complain even when the values are equal. This is less of an issue and we could keep the warning even there.
```
  PasswordAuthentication = true;
  passwordAuthentication = true;
```
triggers too
```
       … while calling the 'head' builtin

         at /nix/store/5hkp141clbdi6fg36wpb0y85rljlcypn-source/lib/attrsets.nix:780:11:

          779|         || pred here (elemAt values 1) (head values) then
          780|           head values
             |           ^
          781|         else

       … while evaluating the attribute 'value'

         at /nix/store/5hkp141clbdi6fg36wpb0y85rljlcypn-source/lib/modules.nix:759:9:

          758|     in warnDeprecation opt //
          759|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          760|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error:
       Failed assertions:
       - Duplicate sshd config key; does your capitalization match the option's?
       ```

**Comment by teto** [comment]
I tried to check key by key instead so that it can give an error message with the duplicated keyname but the following snippet failed  even with a proper config:
```
    assertions = let
      compareKey = lowerCaseSettingName:
        lib.lists.count (y: lib.strings.toLower y == lowerCaseSettingName) (attrNames cfg.settings);
      in[{ assertion = if cfg.settings.X11Forwarding then cfgc.setXAuthLocation else true;
                    message = "cannot enable X11 forwarding without setting xauth location";}
        ]
      ++ (forEach (attrNames cfg.settings) (x: {
                    assertion = compareKey (lib.strings.toLower x) > 1;
                    message =  "Duplicate sshd config key ${x}; does your capitalization match the option's?";
                  }))
```
but another pair of eyeballs might be able to see it more clearly

**Comment by teto** [comment]
I think we could generate better error messages but I have not the resources to address those before release so I propose we merge this since it's strictly better than the current state, future improvements can be backported. Any objection @nyanotech ?

**Comment by nyanotech** [comment]
sgtm

**Comment by happysalada** [comment]
Just want to say thank you for this!

**Pull request merged**
