### PR TITLE
pnpm: 9.14.4 -> 9.15.0

### PR DESCRIPTION
**Pull request by Scrumplex**
https://github.com/pnpm/pnpm/releases/tag/v9.15.0

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Scrumplex** [comment]
I tried rebuilding `{vesktop,vencord}.pnpmDeps` and was able to reproduce them successfully.

**Comment by gepbird** [comment]
Thanks, I'll run nixpkgs-review on it very soon

**Comment by gepbird** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 362450`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 1 package marked as broken and skipped:</summary>
  <ul>
    <li>gitbutler</li>
  </ul>
</details>
<details>
  <summary>:x: 19 packages failed to build:</summary>
  <ul>
    <li>modrinth-app</li>
    <li>modrinth-app-unwrapped</li>
    <li>tabby-agent</li>
    <li>taler-challenger</li>
    <li>taler-merchant</li>
    <li>taler-sync</li>
    <li>taler-wallet-core</li>
    <li>teleport (teleport_16)</li>
    <li>teleport.client (teleport_16.client)</li>
    <li>vencord</li>
    <li>vencord-web-extension</li>
    <li>vesktop</li>
    <li>vikunja</li>
    <li>wealthfolio</li>
    <li>webcord-vencord</li>
    <li>wrangler</li>
    <li>youtube-music</li>
    <li>zammad</li>
    <li>zenn-cli</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 47 packages built:</summary>
  <ul>
    <li>astro-language-server</li>
    <li>authelia</li>
    <li>autoprefixer</li>
    <li>cdxgen</li>
    <li>clash-verge-rev</li>
    <li>daed</li>
    <li>deltachat-desktop</li>
    <li>en-croissant</li>
    <li>equibop</li>
    <li>equicord</li>
    <li>follow</li>
    <li>gitify</li>
    <li>goofcord</li>
    <li>gui-for-clash</li>
    <li>gui-for-singbox</li>
    <li>heroic</li>
    <li>heroic-unwrapped</li>
    <li>homebox</li>
    <li>homer</li>
    <li>legcord</li>
    <li>lemmy-ui</li>
    <li>metacubexd</li>
    <li>misskey</li>
    <li>moonfire-nvr</li>
    <li>n8n</li>
    <li>overlayed</li>
    <li>parca</li>
    <li>pgrok</li>
    <li>pgrok.server</li>
    <li>piped</li>
    <li>pnpm (pnpm_9)</li>
    <li>podman-desktop</li>
    <li>porn-vault</li>
    <li>postcss-cli</li>
    <li>pot</li>
    <li>python311Packages.django-filingcabinet</li>
    <li>python311Packages.django-filingcabinet.dist</li>
    <li>python312Packages.django-filingcabinet</li>
    <li>python312Packages.django-filingcabinet.dist</li>
    <li>renovate</li>
    <li>rsshub</li>
    <li>shadcn</li>
    <li>siyuan</li>
    <li>sketchybar-app-font</li>
    <li>stylelint-lsp</li>
    <li>surrealist</li>
    <li>syncyomi</li>
  </ul>
</details>

No build log available for any of the failures, I'll try running it again

**Review by gepbird — APPROVED** [review]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 362450`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 1 package marked as broken and skipped:</summary>
  <ul>
    <li>gitbutler</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 66 packages built:</summary>
  <ul>
    <li>astro-language-server</li>
    <li>authelia</li>
    <li>autoprefixer</li>
    <li>cdxgen</li>
    <li>clash-verge-rev</li>
    <li>daed</li>
    <li>deltachat-desktop</li>
    <li>en-croissant</li>
    <li>equibop</li>
    <li>equicord</li>
    <li>follow</li>
    <li>gitify</li>
    <li>goofcord</li>
    <li>gui-for-clash</li>
    <li>gui-for-singbox</li>
    <li>heroic</li>
    <li>heroic-unwrapped</li>
    <li>homebox</li>
    <li>homer</li>
    <li>legcord</li>
    <li>lemmy-ui</li>
    <li>metacubexd</li>
    <li>misskey</li>
    <li>modrinth-app</li>
    <li>modrinth-app-unwrapped</li>
    <li>moonfire-nvr</li>
    <li>n8n</li>
    <li>overlayed</li>
    <li>parca</li>
    <li>pgrok</li>
    <li>pgrok.server</li>
    <li>piped</li>
    <li>pnpm (pnpm_9)</li>
    <li>podman-desktop</li>
    <li>porn-vault</li>
    <li>postcss-cli</li>
    <li>pot</li>
    <li>python311Packages.django-filingcabinet</li>
    <li>python311Packages.django-filingcabinet.dist</li>
    <li>python312Packages.django-filingcabinet</li>
    <li>python312Packages.django-filingcabinet.dist</li>
    <li>renovate</li>
    <li>rsshub</li>
    <li>shadcn</li>
    <li>siyuan</li>
    <li>sketchybar-app-font</li>
    <li>stylelint-lsp</li>
    <li>surrealist</li>
    <li>syncyomi</li>
    <li>tabby-agent</li>
    <li>taler-challenger</li>
    <li>taler-merchant</li>
    <li>taler-sync</li>
    <li>taler-wallet-core</li>
    <li>teleport (teleport_16)</li>
    <li>teleport.client (teleport_16.client)</li>
    <li>vencord</li>
    <li>vencord-web-extension</li>
    <li>vesktop</li>
    <li>vikunja</li>
    <li>wealthfolio</li>
    <li>webcord-vencord</li>
    <li>wrangler</li>
    <li>youtube-music</li>
    <li>zammad</li>
    <li>zenn-cli</li>
  </ul>
</details>

**Pull request merged**
