### PR TITLE
gohufont: 2.0 -> 2.1

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
#35003 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested in X.org and linux framebuffer
- [x] Tested compilation of all pkgs that depend on this change (none)
- [x] Tested execution of all binary files (none)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

notes: the 2x scaled fonts can't be properly converted to pcf and entirely to psf. It appears to be a problem with the font itself as two different tools are giving the same result.

### CODE REVIEW

**Comment by rnhmjoj** [comment]
Uhm, this is bad. ofBorg, my computer and a different one produced 3 different hashes.

**Comment by rnhmjoj** [comment]
Ok, it was gzip fault but it's fixed now.

**Comment by xeji** [comment]
let's try again
@GrahamcOfBorg build gohufont

**Comment by xeji** [comment]
hash mismatch on all platforms, which I can reproduce locally for x86_64-linux.

**Review by xeji — CHANGES_REQUESTED** [review]
fix hash mismatch

**Comment by rnhmjoj** [comment]
Argh, it must be still nondeterministic: on my machine I can build it with this hash.
I don't know what else to do.

**Comment by xeji** [comment]
Maybe there's a way to build entirely from github?

**Comment by rnhmjoj** [comment]
Not yet, until the issue regarding the font size is fixed.
Anyway I bet it's gzip again. I'll try to not compress the pcf fonts.

**Comment by rnhmjoj** [comment]
@GrahamcOfBorg build gohufont

**Comment by rnhmjoj** [comment]
@GrahamcOfBorg build gohufont

**Comment by rnhmjoj** [comment]
I removed the gzipping parte and it seems reproducible now.
I don't understand why: there are many fixed-output derivations using gzip, so it's supposedly deterministic... unless there is a bug triggered by these particular files.
Debian [reported](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=647522) this issue in the past but it has been fixed, maybe it's a new incarnation of it.

**Comment by rnhmjoj** [comment]
ping

**Comment by rnhmjoj** [comment]
Thank you.

**Comment by rnhmjoj** [comment]
@7c6f434c can you close #35003?

**Pull request merged**
