### PR TITLE
goocanvas2: switch to python3

### PR DESCRIPTION
**Pull request by armeenm**
###### Description of changes
Builds just fine with python3.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mindavi** [comment]
Does it also build _without_ python? A flag `--disable-python` is given.

**Comment by armeenm** [comment]
Unfortunately it complains that there isn't any Python without it.

**Comment by jtojnar** [comment]
Looks like that is indeed the case: https://gitlab.gnome.org/GNOME/goocanvas/-/blob/2.0.4/configure.ac#L89

**Comment by Mindavi** [comment]
Result of `nixpkgs-review pr 169638` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>ocrfeeder</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>etherape</li>
    <li>glom</li>
    <li>gnome-inform7</li>
    <li>goocanvas2</li>
    <li>goocanvasmm2</li>
    <li>gpredict</li>
    <li>gscan2pdf</li>
    <li>pdf-quench</li>
    <li>perl532Packages.GooCanvas2</li>
    <li>perl532Packages.GooCanvas2CairoTypes</li>
    <li>perl534Packages.GooCanvas2</li>
    <li>perl534Packages.GooCanvas2CairoTypes</li>
    <li>python310Packages.goocalendar</li>
    <li>python39Packages.goocalendar</li>
    <li>shutter</li>
    <li>tryton</li>
  </ul>
</details>

**Pull request merged**
