### PR TITLE
Mariadb darwin

### PR DESCRIPTION
**Pull request by pmahoney**
I have successfully compiled mariadb and ncurses on darwin with these patches in place.
I have also tested compilation on linux.

Mariadb - remove TokuDB, change some compiler flags
Ncurses - build shared lib on darwin, support `.dylib` shared lib suffix

The ncurses postInstall script is getting a bit messy. Not sure how to really improve it though.

@wkennington @shlevy @thoughtpolice

### CODE REVIEW

**Comment by wkennington** [comment]
The ncurses changes need to be rebased to staging since we won't be adding this directly to master. I'm not a huge fan of bashisms but this change probably works. The only other downside is that it depends on the naming scheme containing a w and no other library suffix characters.

**Comment by pmahoney** [comment]
Can you explain the distinction between master and staging?  (Just ignorance on my part)

**Comment by wkennington** [comment]
Staging is for changes which require a mass rebuild, so anything core like
ncurses need to go through there first so users of master don't have to
rebuild everrything.

**Comment by wkennington** [comment]
This should be fixed in staging now.

**Comment by pmahoney** [comment]
@wkennington Sounds good. Just FYI, the ncurses patch above misses a few things. Was working on an improved version (with no bash-isms), but sounds like you don't need it?

**Comment by wkennington** [comment]
I don't think so

**Pull request closed without merging**
