### PR TITLE
ponyc: 0.44.0 -> 0.49.0, pony-corral: 0.5.4 -> 0.5.7

### PR DESCRIPTION
**Pull request by Trundle**
###### Motivation for this change

Several upstream releases

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by redvers — CHANGES_REQUESTED** [review]
The version bump from 0.44.0 to 0.49.0 looks perfect.

Can you add to this PR an update to corral as it needs to be updated in-sync with ponyc.

Thanks

**Review by redvers — APPROVED** [review]
This PR looks good to me and I commend it.

**Comment by redvers** [comment]
Additionally - the current version (0.44.0) no longer compiles so ponyc is in a state of brokenness until this PR is merged.

**Comment by redvers** [comment]
Fixes #168313

**Comment by cole-h** [comment]
Looks like it failed on `x86_64-darwin` (a supported platform), so let's try again.

@ofborg build ponyc pony-corral

**Comment by tpwrules** [comment]
Seems to work okay for me on `x86_64-linux`. I can compile a Hello World example and run the `corral` program's help.

**Comment by tpwrules** [comment]
Seems to work okay for me on `x86_64-linux`. I can compile a Hello World example and run the `corral` program's help.

**Comment by redvers** [comment]
Result of `nixpkgs-review pr 162934` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>pony-corral</li>
    <li>ponyc</li>
  </ul>
</details>

**Comment by redvers** [comment]
@cole-h As the build kept timing out on hydra darwin, I ran a nixpkgs-review on my OSX machine to validate for you.

Thanks.

**Comment by redvers** [comment]
```console
[nix-shell:~/.cache/nixpkgs-review/pr-162934-2]$ ponyc --version
0.49.0 [release]
Compiled with: LLVM 13.0.1 -- Clang-9.0.1-x86_64
Defaults: pic=true

[nix-shell:~/.cache/nixpkgs-review/pr-162934-2]$ corral version
version: 0.5.7
```

**Comment by cole-h** [comment]
Unfortunate that it times out on ofborg, but glad that it builds locally. I don't know if there's anything we can do to fix that timeout on darwin at this point in time.

**Comment by redvers** [comment]
@cole-h - is there anything else I can do to help facilitate its merging?

**Comment by cole-h** [comment]
Yes, exactly what you just did: ping me!

**Pull request merged**
