### PR TITLE
Python: add sitecustomize.py, listen to NIX_PYTHONPATH

### PR DESCRIPTION
**Pull request by FRidh**
##### Motivation for this change

Split from https://github.com/NixOS/nixpkgs/pull/25985.

Add a `sitecustomize.py` file that listens to `NIX_PYTHONPATH` and unsets it afterwards. This gives the same feature as both `PYTHONHOME` and `PYTHONPATH`, however, without preventing the user from using those environment variables, and without leaking the variable.

This variable is now used in `python.buildEnv`, thereby solving issues with a leaking `PYTHONHOME` which could break nested Python programs/environments.

In the future we may choose to use this as well in `buildPythonPackage`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by risicle** [comment]
This is a really neat idea - I've been doing something similar in a much hackier way to get virtualenvs to work with less hassle - simply using `sitecustomize.py` to re-sort all of the paths beginning with `/nix/` to the "end" of `sys.path`.

Moving towards preferring `PYTHONPATH` provided packages over nix-provided ones... is there a worry this will threaten the "integrity" (for want of a better word) of nix-provided python applications?

**Comment by FRidh** [comment]
I don't follow you. This does not use `PYTHONPATH`. We may eventual use this also in other wrappers but I don't see any negative changes there.

**Review by abbradar — APPROVED** [review]
> Additionally, this commit introduces `NIX_PYTHON_SCRIPT_NAME` which
can be used for setting `sys.argv[0]`.

Not in the commit, a rebasing mistake?

I needed to read on the previous discussions since I have completely forgotten what's the problem we are trying to solve :D

It's better than using `PYTHONHOME`. I like the idea of unsetting the variable; if we apply it to `NIX_PYTHON_SCRIPT_NAME` won't this solve its leakiness? I don't see any other problems with it, maybe I missed anything in https://github.com/NixOS/nixpkgs/pull/25985?

We still don't solve crazy cases like (5) from https://github.com/NixOS/nixpkgs/pull/25985#issuecomment-303728027 but that's a clear improvement.

**Comment by abbradar** [comment]
And if we move to using them in `buildPythonPackage` both we finally can get rid of [this abomination](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/python/wrap-python.nix)!. The world would definitely become a better place. So I'm all for going all in, again unless I miss anything.

**Comment by FRidh** [comment]
5) should simply not be done.

I've updated the commit message. Yes, we could use `NIX_PYTHON_SCRIPT_NAME` but I won't to test a bit more with `exec -a`, whether it really really does not work.

**Comment by risicle** [comment]
@FRidh my point is just that users may have custom entries in their runtime environment's `PYTHONPATH` and if these now get prioritized in front of `NIX_PYTHONPATH` entries, `$ some-python-based-cli-tool` may have one of its dependencies instead resolved to the runtime environment's and break.

**Comment by FRidh** [comment]
Ah, now I understand. No, this won't change.

**Pull request merged**
