### PR TITLE
nodePackages: add bs-platform

### PR DESCRIPTION
**Pull request by Huddo121**
###### Motivation for this change
`bs-platform` contains some CLI tools for getting started writing ReasonML. I've made this change by blindly following the instructions [here](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/node.section.md). I've been able to test the executables by running `nix-build -A nodePackages.bs-platform` and then trying them out in the `result` symlink, but I haven't been able to run something like `nix-shell -I mynixpkgsdir -p nodePackages.bs-platform`, shouldn't that work?

###### Things done
- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @ No owners listed in CODEOWNERS 🤷‍♂

### CODE REVIEW

**Comment by Huddo121** [comment]
Well, running nix-shell with a file like the following seems to work so maybe I am being a bit of a numpty with my `nix-shell` command from above.

```
let
  pkgs = import (/Users/mhudson/Development/nixpkgs) {};
in
with pkgs;
mkShell {
  buildInputs = [ nodejs yarn nodePackages.bs-platform ];
}
```

**Comment by marsam** [comment]
just curious, does this work? IIRC bucklescript uses `postInstall` script to build their executables, which requires ninja and a specific ocaml version.

**Comment by Huddo121** [comment]
@marsam Argh, good spot, you're right, I just tried this out on my NixOS machine and it crapped out. I must have already had Ninja laying around when I first tried to nixify this. I've settled on using the JS ecosystem tools from within a nix-shell for now, I'll close this PR, as it seems like it might be tricky to deal with their `scripts/install.js` script and there's an alternative approach.

**Comment by turboMaCk** [comment]
related https://github.com/NixOS/nixpkgs/pull/73570

**Pull request closed without merging**
