### PR TITLE
clang: Properly wrap clangd to make it usable

### PR DESCRIPTION
**Pull request by thufschmitt**
###### Description of changes

Wrap the `clangd` executable that's exported by the various `clang` derivations to take into account the Nix-specific flags. This is required to make it usable as it won't see the correct headers otherwise.

A properly wrapped `clangd` is already made available by the `clang-tools` derivation, but this is quite confusing because most people will just see that `clangStdenv` ships a broken `clangd` and will have no clue that another nixpkgs package has the right wrapper to make it work (see
https://discourse.nixos.org/t/get-clangd-to-find-standard-headers-in-nix-shell/11268/8 or
https://discourse.nixos.org/t/clangd-issues-on-nixos-missing-headers/11115/8 as examples of that confusion).
Since the wrapper is very lightweight, there doesn't seem to be a good reason for not having it directly in the `clang` derivation.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yorickvP** [comment]
infinite recursion during eval

**Comment by tobim** [comment]
Alternative idea: Don't provide `clangd` with `clang`.

**Comment by jicksaw** [comment]
> Alternative idea: Don't provide `clangd` with `clang`.

The `clangd` in `clang-tools` uses wrapped `clang`, which doesn't work if your target doesn't use the wrapped headers (in my case, freestanding embedded). I'd be fine with removing `clangd` from `clang`, but I guess we'd need a `clang-tools-unwrapped`.

**Comment by gabyx** [comment]
Is there any progress on this. Would be very usefull.

**Comment by thufschmitt** [comment]
I think the `clang` derivation no longer ships with `clangd` (which is probably a better solution as `clangd` isn't useful for just building things), making this PR obsolete altogether.

**Comment by gabyx** [comment]
@thufschmitt : Thanks.

**Comment by acidghost** [comment]
@thufschmitt I don't think that's the case (channel `nixos-24.05`):
```
❯ which-else clangd
/nix/store/2fq118rjz93ldsxc0diyfyi1kpm2mwz3-clang-tools-17.0.6/bin/clangd
/nix/store/imfj9dq985b8vl4l6arl90ylbww6iplb-clang-17.0.6/bin/clangd
```

In my shell I resort to
```nix
let
  nixpkgs = fetchTarball "https://github.com/NixOS/nixpkgs/tarball/nixos-24.05";
  pkgs = import nixpkgs { config = {}; overlays = []; };
in

pkgs.mkShellNoCC {
  packages = with pkgs; [
    go
    gopls
    golangci-lint
    delve
    # XXX: clang-tools has to come before clang to set precedence in PATH for clangd
    clang-tools
    clang
    llvm
    lldb
  ];
}
```

**Pull request closed without merging**
