### PR TITLE
qt5: add at-spi2-core to qtbase

### PR DESCRIPTION
**Pull request by Artturin**
###### Motivation for this change
Closes #39499

###### Things done

i added `at-spi2-core` to qtbase.nix `buildInputs`

After
```Checking for atspi...
Trying source 0 (type pkgConfig) of library atspi ...
+ pkg-config --exists --silence-errors atspi-2
+ pkg-config --modversion atspi-2
> 2.40.1
+ pkg-config --libs-only-L atspi-2
> -L/nix/store/dcb3cyba5wl6qimv6vwdpbi0kg0g1nlb-glib-2.68.2/lib -L/nix/store/s6aszyzvfph06i9dcic7x6yci5qjjn10-at-spi2-core-2.40.1/lib -L/nix/store/3ywkzq38n9kfjpb84ac2qz5kfhmzjrhv-dbus-1.12.20-lib/lib
+ pkg-config --libs-only-l atspi-2
> -latspi -ldbus-1 -lglib-2.0
+ pkg-config --cflags atspi-2
> -I/nix/store/d9zs9xg86lhqjqni0v8h2ibdrjb57fn4-glib-2.68.2-dev/include/glib-2.0 -I/nix/store/dcb3cyba5wl6qimv6vwdpbi0kg0g1nlb-glib-2.68.2/lib/glib-2.0/include -I/nix/store/qab61iyr99kcny3p9jgivh581cjgm2la-at-spi2-core-2.40.1-dev/include/at-spi-2.0 -I/nix/store/gmvb8249szs44gryl92716wycrw895dy-dbus-1.12.20-dev/include/dbus-1.0 -I/nix/store/3ywkzq38n9kfjpb84ac2qz5kfhmzjrhv-dbus-1.12.20-lib/lib/dbus-1.0/include
 => source accepted.
```

vs Before

```
Checking for atspi... 
Trying source 0 (type pkgConfig) of library atspi ...
+ pkg-config --exists --silence-errors atspi-2
pkg-config did not find package.
  => source produced no result.
test config.qtbase_gui.libraries.atspi FAILED
```

from https://hydra.nixos.org/build/144353470/nixlog/1

at-spi2-atk gets inherited from somewhere else since its visible in the hydra log

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
Does it need to be propagated or do normal build inputs suffice?

**Comment by Artturin** [comment]
> Does it need to be propagated or do normal build inputs suffice?

probably not? since the spi things are running as separate programs or something
im also making a `accessibility` module

**Comment by Artturin** [comment]
@jtojnar for most packages its in buildInputs https://github.com/NixOS/nixpkgs/search?q=at-spi2-core

**Comment by Artturin** [comment]
@jtojnar fedora has this in buildRequires https://src.fedoraproject.org/rpms/qt5-qtbase/blob/rawhide/f/qt5-qtbase.spec#_163
and -core provides that https://src.fedoraproject.org/rpms/at-spi2-core/blob/rawhide/f/at-spi2-core.spec#_85

our configureFlags already have -accessibility so there is no need to add that

**Comment by Artturin** [comment]
also tested and found out that `enableParallelBuilding = true;` speeds up the build by alot
```
[artturin@nixos:~/nixpkgs]$ time nix build .#libsForQt5.qtbase --cores 100

warning: Git tree '/home/artturin/nixpkgs' is dirty
[1/0/1 built, 0.0 MiB DL] building qtbase-5.15.2 (buildPhase): g++ -c -pipe -O2 -fPIC -std=c++1z -fvisibility=hidden -fvisibility

real    5m33.720s
user    0m0.722s
sys     0m0.462s
```

before
```
[artturin@nixos:~/nixpkgs]$ time nix build .#libsForQt5.qtbase --cores 100
warning: Git tree '/home/artturin/nixpkgs' is dirty
[1/0/1 built] building qtbase-5.15.2 (buildPhase): g++ -c -include .pch/Qt5Widgets -pipe -O2 -std=c++1z -fvisibility=hidden -fvis

real    25m33.321s
user    0m0.476s
sys     0m0.396s
```

**Comment by Artturin** [comment]
merging and making a separate pr for enabling parallelbuilding

**Pull request merged**
