### PR TITLE
slack: dark mode css can be passed as argument

### PR DESCRIPTION
**Pull request by anpryl**
###### Motivation for this change

Slack package has a dark mode, but current CSS for dark mode is broken for "All threads".
I add an optional argument to derivation for CSS url.
Default CSS url is an old one, so it is backward compatible.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by JohnAZoidberg** [comment]
> Slack package has a dark mode, but current CSS for dark mode is broken for "All threads".
> I add an optional argument to derivation for CSS url.
> Default CSS url is an old one, so it is backward compatible.

What do you mean it's broken? Does the default url not work anymore? If it doesn't work, we don't need to be backwards compatible.

**Comment by anpryl** [comment]
> > Slack package has a dark mode, but current CSS for dark mode is broken for "All threads".
> > I add an optional argument to derivation for CSS url.
> > Default CSS url is an old one, so it is backward compatible.
> 
> What do you mean it's broken? Does the default url not work anymore? If it doesn't work, we don't need to be backwards compatible.

Here is an issue https://github.com/laCour/slack-night-mode/issues/218.
Personally I switched to fork. 
But I don't think that all package users wants to switch to random fork.

**Comment by etu** [comment]
> What do you mean it's broken? Does the default url not work anymore? If it doesn't work, we don't need to be backwards compatible.

Upstream (of the dark mode) will probably fix the issues that currently exists after upstream (slack server side rendered html) broke the dark mode. But this would give more flexibility for the user of the derivation to "fix it" faster. I use dark mode myself at work and it's currently quite unusable on some pages.

And I think that this is a quite nice workaround to be able to patch it easily as a user of NixOS.

**Review by etu — APPROVED** [review]

**Comment by etu** [comment]
@anpryl Hey, could you rebase this on master? That would be great to solve the conflicts. Ping me when you done it so we can merge this PR :)

**Comment by anpryl** [comment]
@etu rebased on master

**Pull request merged**
