### PR TITLE
gnunet-svn: mark as broken

### PR DESCRIPTION
**Pull request by pstn**
###### Motivation for this change
Gnunet switched develpoment from svn to git and removed the svn repositories. A replacement -svn package has already been added.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
> Gnunet switched develpoment from svn to git and removed the svn repositories.

Then there's no point in marking `gnunet-svn` as broken on master, let's remove it right away.

**Comment by pstn** [comment]
@xeji If you say so. Removed it.

**Comment by xeji** [comment]
Thanks. Our svn revision was from 2013 anyway :smile:

**Comment by pstn** [comment]
Yeah, I'll bump the git version a little bit more often. Maybe next year? ^_~

**Pull request merged**
