### PR TITLE
notmuch-bower: 0.9 -> 0.10

### PR DESCRIPTION
**Pull request by erictapen**
###### Things done

Also added my PGP key to maintainers-list.nix.

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by erictapen** [comment]
@GrahamcOfBorg build notmuch-bower

**Comment by worldofpeace** [comment]
Does this applications have to be configured before it can be executed succesfully?
https://github.com/wangp/bower#configuration

**Comment by erictapen** [comment]
@worldofpeace To be honest I just use bower for viewing some special mails, that are broken in `alot`. But no, I'm able to execute and use it without any config file.

**Comment by worldofpeace** [comment]
Nvm, that was a misunderstanding.

This is good :+1:

**Pull request merged**
