### PR TITLE
nixos/testing: remove unused function runInMachine

### PR DESCRIPTION
**Pull request by mkenigs**
###### Motivation for this change
Not sure if I'm missing something obvious, but I couldn't find anywhere `runInMachine` is used.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by roberth** [comment]
It has a test, but no documentation and no designated maintainer. It seems a bit out of place for this to be in the test infrastructure.

For all I know this could be dead code that was held on to because it was exposed through the use of `rec`. A good reason to prefer `let` over `rec`!

Perhaps you could replace the two functions by something like the following, to give it a last chance.

```nix
runInMachine = abort ''The runInMachine function was removed because it is
  not an essential part of the NixOS testing infrastructure. It had no usage in
  NixOS or Nixpkgs and it had no designated maintainer. You are free to reintroduce
  it by documenting it in the manual and adding yourself as maintainer. It was
  removed in https://github.com/NixOS/nixpkgs/pull/137013
'';
```

**Comment by mkenigs** [comment]
Thanks! Replaced it with an abort

**Review by roberth — APPROVED** [review]

**Review by tfc — APPROVED** [review]

**Comment by mkenigs** [comment]
Anything else I need to do? Or just waiting on @andir?

**Comment by roberth** [comment]
9 days and two approvals should be enough. I don't think another approval reduces the uncertainty enough to warrant delaying / forgetting this.

**Pull request merged**
