### PR TITLE
idrisPackages: add packages

### PR DESCRIPTION
**Pull request by brainrake**
###### Motivation for this change

There were very few Idris packages. I packaged a bunch of them from https://github.com/xgrommx/idris-ecosystem 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
cc @siddharthist

**Comment by Mic92** [comment]
Did you automatically generate this package list?

**Comment by Mic92** [comment]
```
@GrahamcOfBorg build idrisPackages.array idrisPackages.bi idrisPackages.bifunctors idrisPackages.bytes idrisPackages.canvas idrisPackages.categories idrisPackages.coda idrisPackages.config idrisPackages.comonad idrisPackages.composition idrisPackages.console idrisPackages.containers idrisPackages.cube idrisPackages.curses idrisPackages.data idrisPackages.derive idrisPackages.descncrunch idrisPackages.dict idrisPackages.dom idrisPackages.electron idrisPackages.eternal idrisPackages.farrp idrisPackages.free idrisPackages.fsm idrisPackages.glfw idrisPackages.graphviz idrisPackages.hamt idrisPackages.html idrisPackages.heyting-algebra idrisPackages.hezarfen idrisPackages.hrtime idrisPackages.http idrisPackages.http4idris idrisPackages.iaia idrisPackages.idrishighlighter idrisPackages.idrisscript idrisPackages.ipkgparser idrisPackages.jheiling-extras idrisPackages.jheiling-js idrisPackages.js idrisPackages.lens idrisPackages.lightyear idrisPackages.logic idrisPackages.mapping idrisPackages.mhd idrisPackages.pacman idrisPackages.patricia idrisPackages.permutations idrisPackages.pfds idrisPackages.pipes idrisPackages.posix idrisPackages.protobuf idrisPackages.rationals idrisPackages.recursion_schemes idrisPackages.refined idrisPackages.sdl idrisPackages.sdl2 idrisPackages.semidirect idrisPackages.setoids idrisPackages.smproc idrisPackages.snippets idrisPackages.software_foundations idrisPackages.specdris idrisPackages.tap idrisPackages.test idrisPackages.tlhydra idrisPackages.tomladris idrisPackages.tp idrisPackages.tparsec idrisPackages.transducers idrisPackages.trees idrisPackages.union_type idrisPackages.vecspace idrisPackages.webgl idrisPackages.wl-pprint idrisPackages.wyvern idrisPackages.xhr idrisPackages.yaml idrisPackages.yampa
```

**Comment by Mic92** [comment]
cube and vecspace have invalid checksums:

```
  /nix/store/w6rcrjsmrf3sgxyqr8zga81vpjxz1kdx-source.drv
  /nix/store/412andibjji60659yqn1ng0zryfkrxa9-cube-2017-07-05.drv
  /nix/store/kjyppbik1cx9d5ni2w82m9kaymxvqha4-source.drv
  /nix/store/g8r70wyyy79d99b8hg4i55dn093ygg75-vecspace-2018-01-12.drv
building '/nix/store/kjyppbik1cx9d5ni2w82m9kaymxvqha4-source.drv'...
building '/nix/store/w6rcrjsmrf3sgxyqr8zga81vpjxz1kdx-source.drv'...
trying https://github.com/clayrat/idris-vecspace/archive/6830fa13232f25e9874b3f857b79508b5f82cb99.tar.gz
trying https://github.com/aatxe/cube.idr/archive/f8bfa35a68a09b4685e8152901609de8ee115d73.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   164    0   164    0     0    373      0 --:--:-- --:--:-- --:--:--   373
100   156    0   156    0     0    340      0 --:--:-- --:--:-- --:--:--   340
100  2094  100  2094    0     0   2331      0 --:--:-- --:--:-- --:--:--  6820
unpacking source archive /build/6830fa13232f25e9874b3f857b79508b5f82cb99.tar.gz
100 12264  100 12264    0     0  12264      0  0:00:01  0:00:01 --:--:-- 25496
unpacking source archive /build/f8bfa35a68a09b4685e8152901609de8ee115d73.tar.gz
fixed-output derivation produced path '/nix/store/haf59jyrgzfdrl5a9m5k63ijna11njfi-source' with sha256 hash '1dwz69cmzblyh7lnyqq2gp0a042z7h02sh5q5wf4xb500vizwkq2' instead of the expected hash '1yanvzijnkzscf5f2fx4zh4kkc6i0pmasdyg49smqp32da219lqc'
cannot build derivation '/nix/store/g8r70wyyy79d99b8hg4i55dn093ygg75-vecspace-2018-01-12.drv': 1 dependencies couldn't be built
fixed-output derivation produced path '/nix/store/cadfjvrj2mmq99a2fppyfq59wq287389-source' with sha256 hash '0p0k3hqhscck6xjz6n58blhr4qxmdjw7x044l41b9mdr8m77wv46' instead of the expected hash '11k45j0b4qabj6zhwjvynyj56nmssf7d4fnkv66bd2w1pxnshzxg'
cannot build derivation '/nix/store/412andibjji60659yqn1ng0zryfkrxa9-cube-2017-07-05.drv': 1 dependencies couldn't be built
error: build of '/nix/store/412andibjji60659yqn1ng0zryfkrxa9-cube-2017-07-05.drv', '/nix/store/g8r70wyyy79d99b8hg4i55dn093ygg75-vecspace-2018-01-12.drv' failed
```

**Comment by brainrape** [comment]
I made the list manually, checking each package as I went. Thanks for the heads up, fixed `cube` and `vecspace`.
I'll get someone to look into the darwin fails for a future PR.

**Comment by brainrape** [comment]
```
@GrahamcOfBorg build idrisPackages.array idrisPackages.bi idrisPackages.bifunctors idrisPackages.bytes idrisPackages.canvas idrisPackages.categories idrisPackages.coda idrisPackages.config idrisPackages.comonad idrisPackages.composition idrisPackages.console idrisPackages.containers idrisPackages.cube idrisPackages.curses idrisPackages.data idrisPackages.derive idrisPackages.descncrunch idrisPackages.dict idrisPackages.dom idrisPackages.electron idrisPackages.eternal idrisPackages.farrp idrisPackages.free idrisPackages.fsm idrisPackages.glfw idrisPackages.graphviz idrisPackages.hamt idrisPackages.html idrisPackages.heyting-algebra idrisPackages.hezarfen idrisPackages.hrtime idrisPackages.http idrisPackages.http4idris idrisPackages.iaia idrisPackages.idrishighlighter idrisPackages.idrisscript idrisPackages.ipkgparser idrisPackages.jheiling-extras idrisPackages.jheiling-js idrisPackages.js idrisPackages.lens idrisPackages.lightyear idrisPackages.logic idrisPackages.mapping idrisPackages.mhd idrisPackages.pacman idrisPackages.patricia idrisPackages.permutations idrisPackages.pfds idrisPackages.pipes idrisPackages.posix idrisPackages.protobuf idrisPackages.rationals idrisPackages.recursion_schemes idrisPackages.refined idrisPackages.sdl idrisPackages.sdl2 idrisPackages.semidirect idrisPackages.setoids idrisPackages.smproc idrisPackages.snippets idrisPackages.software_foundations idrisPackages.specdris idrisPackages.tap idrisPackages.test idrisPackages.tlhydra idrisPackages.tomladris idrisPackages.tp idrisPackages.tparsec idrisPackages.transducers idrisPackages.trees idrisPackages.union_type idrisPackages.vecspace idrisPackages.webgl idrisPackages.wl-pprint idrisPackages.wyvern idrisPackages.xhr idrisPackages.yaml idrisPackages.yampa
```

**Comment by brainrape** [comment]
Fixed the licenses of skipped packages as well.

**Comment by Mic92** [comment]
```
@GrahamcOfBorg build idrisPackages.array idrisPackages.bi idrisPackages.bifunctors idrisPackages.bytes idrisPackages.canvas idrisPackages.categories idrisPackages.coda idrisPackages.config idrisPackages.comonad idrisPackages.composition idrisPackages.console idrisPackages.containers idrisPackages.cube idrisPackages.curses idrisPackages.data idrisPackages.derive idrisPackages.descncrunch idrisPackages.dict idrisPackages.dom idrisPackages.electron idrisPackages.eternal idrisPackages.farrp idrisPackages.free idrisPackages.fsm idrisPackages.glfw idrisPackages.graphviz idrisPackages.hamt idrisPackages.html idrisPackages.heyting-algebra idrisPackages.hezarfen idrisPackages.hrtime idrisPackages.http idrisPackages.http4idris idrisPackages.iaia idrisPackages.idrishighlighter idrisPackages.idrisscript idrisPackages.ipkgparser idrisPackages.jheiling-extras idrisPackages.jheiling-js idrisPackages.js idrisPackages.lens idrisPackages.lightyear idrisPackages.logic idrisPackages.mapping idrisPackages.mhd idrisPackages.pacman idrisPackages.patricia idrisPackages.permutations idrisPackages.pfds idrisPackages.pipes idrisPackages.posix idrisPackages.protobuf idrisPackages.rationals idrisPackages.recursion_schemes idrisPackages.refined idrisPackages.sdl idrisPackages.sdl2 idrisPackages.semidirect idrisPackages.setoids idrisPackages.smproc idrisPackages.snippets idrisPackages.software_foundations idrisPackages.specdris idrisPackages.tap idrisPackages.test idrisPackages.tlhydra idrisPackages.tomladris idrisPackages.tp idrisPackages.tparsec idrisPackages.transducers idrisPackages.trees idrisPackages.union_type idrisPackages.vecspace idrisPackages.webgl idrisPackages.wl-pprint idrisPackages.wyvern idrisPackages.xhr idrisPackages.yaml idrisPackages.yampa
```

**Comment by brainrape** [comment]
I guess I need to upgrade my hivemind uplink for Graham to listen :)
Fixed `mapping` too, sorry about that.

**Comment by Mic92** [comment]
something like this is needed for ofborg: https://github.com/NixOS/ofborg/pull/138

**Comment by Mic92** [comment]
@GrahamcOfBorg build idrisPackages.protobuf

**Comment by Mic92** [comment]
Protobuf also actually worked for me.

**Comment by Mic92** [comment]
Idris itself cannot be build on macOS at the moment. So its packages are probably less of a problem.

**Comment by brainrape** [comment]
Ok, that's bad news about Idris on macOS, will need to fix that as well:)
So this PR should be good to go then.
Thanks for all the help!

**Pull request merged**
