### PR TITLE
Improve dafny packaging

### PR DESCRIPTION
**Pull request by layus**
- dafny: add basic test for auto-updates
- dafny: move to pkgs/by-name

### CODE REVIEW

**Comment by PetarKirov** [comment]
@layus can you please rebase your PR?

**Comment by layus** [comment]
@PetarKirov Thanks for reviewing this one. I have updated it and would appreciate if you could review it again and eventually merge it.

**Review by corngood — APPROVED** [review]

**Comment by corngood** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 300009`

---
### `x86_64-linux`

**Comment by corngood** [comment]
This PR is missing the boilerplate in the top comment, but I ran the tests locally and they passed.

**Pull request merged**
