### PR TITLE
emacs-mac: 26.1 -> 26.2

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by veprbl — APPROVED** [review]

**Comment by adisbladis** [comment]
@GrahamcOfBorg build emacsMacport

**Comment by adisbladis** [comment]
LGTM! (assuming it's tested)

**Review by adisbladis — APPROVED** [review]

**Comment by Infinisil** [comment]
```
curl: (7) Failed to connect to ftp.math.s.chiba-u.ac.jp port 21: Operation timed out
error: cannot download emacs-26.2-mac-7.6.tar.gz from any mirror
builder for '/nix/store/fa229zspj22y9p7gspxgsyz99gg7bj03-emacs-26.2-mac-7.6.tar.gz.drv' failed with exit code 1
cannot build derivation '/nix/store/vp2kafs7agm9j6r30k6vj8vqzsj5fkbf-emacs-mac-26.2-7.6.drv': 1 dependencies couldn't be built
error: build of '/nix/store/vp2kafs7agm9j6r30k6vj8vqzsj5fkbf-emacs-mac-26.2-7.6.drv' failed
```

**Comment by adisbladis** [comment]
Is this the same emacs macport? https://bitbucket.org/mituharu/emacs-mac/
If it is we might want to switch to bitbucket as our upstream, should be more stable.

**Comment by matthewbauer** [comment]
> This seems to be the same emacs macport: https://bitbucket.org/mituharu/emacs-mac/
> We might want to switch to bitbucket as our upstream, should be more stable.

The Bitbucket has some differences from the tar ball release. I get this error when trying ```https://bitbucket.org/mituharu/emacs-mac/get/emacs-26.2-mac-7.6.tar.gz```:

```
setting SOURCE_DATE_EPOCH to timestamp 1555222666 of file emacs-26.2/test/src/xml-tests.el
patching sources
applying patch /nix/store/5c40xq6xbh7sii2rfxabhliqdslsdcfz-clean-env.patch
patching file src/Makefile.in
Hunk #1 succeeded at 542 (offset 7 lines).
/nix/store/zxlhxc5bfzl8h2x9jvg9wjpwikanngv6-stdenv-darwin/setup: line 105: patch-mac: No such file or directory
builder for '/nix/store/c7ff5ml24snl0y8h2s5qsdy0mbdnyg4w-emacs-mac-26.2-7.6.drv' failed with exit code 1
```

**Comment by adisbladis** [comment]
@matthewbauer Ok, then lets assume the failure is temporary and retry the build in a few hours.

**Comment by adisbladis** [comment]
@GrahamcOfBorg build emacsMacport

**Pull request merged**
