### PR TITLE
awscli: 1.19.97 -> 1.20.25

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Motivation for this change
Updates

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This breaks nixops
```
ERROR: Package 'botocore' requires a different Python: 2.7.18 not in '>= 3.6'
```

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 134862` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
10 packages marked as broken and skipped:
</summary>
<ul>
<li>awsebcli</li>
<li>mlflow-server</li>
<li>python38Packages.pathy</li>
<li>python38Packages.spacy</li>
<li>python38Packages.spacy-transformers</li>
<li>python38Packages.textacy</li>
<li>python39Packages.pathy</li>
<li>python39Packages.spacy</li>
<li>python39Packages.spacy-transformers</li>
<li>python39Packages.textacy</li>
</ul>
</details>
<details>

  <summary>3 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>checkov: log was empty</li>
<li>python38Packages.gradient: log was empty</li>
<li>python39Packages.gradient: log was empty</li>
  </ul>
</details>
<details>

  <summary>8 packages failed to build and are new build failures:</summary>
  <ul>
<li>awscli2: log was empty</li>
<li>buildbot: log was empty</li>
<li>(python39Packages.buildbot): log was empty</li>
<li>buildbot-full: log was empty</li>
<li>(python39Packages.buildbot-full): log was empty</li>
<li>buildbot-ui: log was empty</li>
<li>(python39Packages.buildbot-ui): log was empty</li>
<li>nixops: log was empty</li>
  </ul>
</details>
<details>
<summary>
139 packages built:
</summary>
<ul>
<li>aws-adfs (python39Packages.aws-adfs)</li>
<li>aws-google-auth</li>
<li>aws-mfa</li>
<li>aws-sam-cli</li>
<li>awscli</li>
<li>awslogs</li>
<li>barman</li>
<li>bash-my-aws</li>
<li>certbot-full</li>
<li>cloud-custodian</li>
<li>credstash (python39Packages.credstash)</li>
<li>deja-dup</li>
<li>duplicity</li>
<li>duply</li>
<li>dvc-with-remotes</li>
<li>elasticsearch-curator</li>
<li>git-remote-codecommit</li>
<li>home-assistant</li>
<li>iceshelf</li>
<li>lexicon</li>
<li>luigi</li>
<li>mapproxy</li>
<li>nimbo</li>
<li>python38Packages.aiobotocore</li>
<li>python38Packages.aws-adfs</li>
<li>python38Packages.aws-sam-translator</li>
<li>python38Packages.aws-xray-sdk</li>
<li>python38Packages.boto3</li>
<li>python38Packages.botocore</li>
<li>python38Packages.buildbot</li>
<li>python38Packages.buildbot-full</li>
<li>python38Packages.buildbot-ui</li>
<li>python38Packages.cartopy</li>
<li>python38Packages.celery</li>
<li>python38Packages.certbot-dns-route53</li>
<li>python38Packages.cfn-lint</li>
<li>python38Packages.chalice</li>
<li>python38Packages.credstash</li>
<li>python38Packages.dependency-injector</li>
<li>python38Packages.django-anymail</li>
<li>python38Packages.django-raster</li>
<li>python38Packages.djmail</li>
<li>python38Packages.ec2instanceconnectcli</li>
<li>python38Packages.fiona</li>
<li>python38Packages.flower</li>
<li>python38Packages.flowlogs_reader</li>
<li>python38Packages.fs-s3fs</li>
<li>python38Packages.gensim</li>
<li>python38Packages.geopandas</li>
<li>python38Packages.hass-nabucasa</li>
<li>python38Packages.mapbox</li>
<li>python38Packages.moto</li>
<li>python38Packages.mypy-boto3-builder</li>
<li>python38Packages.mypy-boto3-s3</li>
<li>python38Packages.osmnx</li>
<li>python38Packages.pyathena</li>
<li>python38Packages.pycognito</li>
<li>python38Packages.pyhiveapi</li>
<li>python38Packages.pynamodb</li>
<li>python38Packages.rasterio</li>
<li>python38Packages.s3fs</li>
<li>python38Packages.s3transfer</li>
<li>python38Packages.sapi-python-client</li>
<li>python38Packages.scrapy</li>
<li>python38Packages.scrapy-deltafetch</li>
<li>python38Packages.scrapy-fake-useragent</li>
<li>python38Packages.scrapy-splash</li>
<li>python38Packages.serverlessrepo</li>
<li>python38Packages.slack-sdk</li>
<li>python38Packages.slicedimage</li>
<li>python38Packages.smart-open</li>
<li>python38Packages.snowflake-connector-python</li>
<li>python38Packages.snowflake-sqlalchemy</li>
<li>python38Packages.tensorboardx</li>
<li>python38Packages.warrant</li>
<li>python39Packages.aiobotocore</li>
<li>python39Packages.aws-sam-translator</li>
<li>python39Packages.aws-xray-sdk</li>
<li>python39Packages.boto3</li>
<li>python39Packages.botocore</li>
<li>python39Packages.cartopy</li>
<li>python39Packages.celery</li>
<li>python39Packages.certbot-dns-route53</li>
<li>python39Packages.cfn-lint</li>
<li>python39Packages.chalice</li>
<li>python39Packages.dependency-injector</li>
<li>python39Packages.django-anymail</li>
<li>python39Packages.django-raster</li>
<li>python39Packages.djmail</li>
<li>python39Packages.ec2instanceconnectcli</li>
<li>python39Packages.fiona</li>
<li>python39Packages.flower</li>
<li>python39Packages.flowlogs_reader</li>
<li>python39Packages.fs-s3fs</li>
<li>python39Packages.gensim</li>
<li>python39Packages.geopandas</li>
<li>python39Packages.hass-nabucasa</li>
<li>python39Packages.mapbox</li>
<li>python39Packages.moto</li>
<li>python39Packages.mypy-boto3-builder</li>
<li>python39Packages.mypy-boto3-s3</li>
<li>python39Packages.osmnx</li>
<li>python39Packages.pyathena</li>
<li>python39Packages.pycognito</li>
<li>python39Packages.pyhiveapi</li>
<li>python39Packages.pynamodb</li>
<li>python39Packages.rasterio</li>
<li>python39Packages.s3fs</li>
<li>python39Packages.s3transfer</li>
<li>python39Packages.sapi-python-client</li>
<li>python39Packages.scrapy</li>
<li>python39Packages.scrapy-deltafetch</li>
<li>python39Packages.scrapy-fake-useragent</li>
<li>python39Packages.scrapy-splash</li>
<li>python39Packages.serverlessrepo</li>
<li>python39Packages.slack-sdk</li>
<li>python39Packages.slicedimage</li>
<li>python39Packages.smart-open</li>
<li>python39Packages.snowflake-connector-python</li>
<li>python39Packages.snowflake-sqlalchemy</li>
<li>python39Packages.tensorboardx</li>
<li>python39Packages.warrant</li>
<li>s3bro</li>
<li>s4cmd</li>
<li>snakemake</li>
<li>sourcehut.buildsrht</li>
<li>sourcehut.coresrht</li>
<li>sourcehut.dispatchsrht</li>
<li>sourcehut.gitsrht</li>
<li>sourcehut.hgsrht</li>
<li>sourcehut.hubsrht</li>
<li>sourcehut.listssrht</li>
<li>sourcehut.mansrht</li>
<li>sourcehut.metasrht</li>
<li>sourcehut.pastesrht</li>
<li>sourcehut.todosrht</li>
<li>ssm-session-manager-plugin</li>
<li>streamlit</li>
<li>tts</li>
</ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 134862` at d1699efa run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/62814d25e120cb2b45dae277caf2d0f8">awscli2</a></li>
    <li><a href="https://gist.github.com/da42abbd961b43eb10459298a5a6c4a2">checkov</a></li>
    <li><a href="https://gist.github.com/ae68be0a16a463f092e22540dd92adcc">mlflow-server</a></li>
    <li><a href="https://gist.github.com/ce8427a68f45b45ffab00d5e31e48ee6">nixops</a></li>
    <li><a href="https://gist.github.com/d5d5adebb93cce9fb5461301c63bc91e">python38Packages.gradient</a></li>
    <li><a href="https://gist.github.com/3b6118e87a48f69f643f45cd61db428e">python38Packages.pathy</a></li>
    <li><a href="https://gist.github.com/1e7fa8dcbf4cb5ad5b6435a810c409fe">python38Packages.spacy</a></li>
    <li><a href="https://gist.github.com/035154d6c900e902cccbb315ce2d31da">python38Packages.textacy</a></li>
    <li><a href="https://gist.github.com/59956e4f6edc78bf265d2bbce474db64">python39Packages.gradient</a></li>
    <li><a href="https://gist.github.com/49e77fad820dcebb4f3f9ef3656f64a3">python39Packages.pathy</a></li>
    <li><a href="https://gist.github.com/263d0789e15011c4d60e15c5c67f1b84">python39Packages.spacy</a></li>
    <li><a href="https://gist.github.com/fa3e6ff7a8ce6ef19b51ee5b315170a8">python39Packages.textacy</a></li>
  </ul>
</details>
<details>
  <summary>11 packages skipped due to time constraints:</summary>
  <ul>
    <li>awsebcli</li>
    <li>home-assistant</li>
    <li>lexicon</li>
    <li>python38Packages.slack-sdk</li>
    <li>python38Packages.spacy-transformers</li>
    <li>python39Packages.dependency-injector</li>
    <li>python39Packages.mypy-boto3-builder</li>
    <li>python39Packages.mypy-boto3-s3</li>
    <li>python39Packages.spacy-transformers</li>
    <li>python39Packages.tensorboardx</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>136 packages built successfully:</summary>
  <ul>
    <li>aws-adfs (python39Packages.aws-adfs)</li>
    <li>aws-google-auth</li>
    <li>aws-mfa</li>
    <li>aws-sam-cli</li>
    <li>awscli</li>
    <li>awslogs</li>
    <li>barman</li>
    <li>bash-my-aws</li>
    <li>buildbot (python39Packages.buildbot)</li>
    <li>buildbot-full (python39Packages.buildbot-full)</li>
    <li>buildbot-ui (python39Packages.buildbot-ui)</li>
    <li>certbot-full</li>
    <li>cloud-custodian</li>
    <li>credstash (python39Packages.credstash)</li>
    <li>deja-dup</li>
    <li>duplicity</li>
    <li>duply</li>
    <li>dvc-with-remotes</li>
    <li>elasticsearch-curator</li>
    <li>git-remote-codecommit</li>
    <li>iceshelf</li>
    <li>luigi</li>
    <li>mapproxy</li>
    <li>nimbo</li>
    <li>python38Packages.aiobotocore</li>
    <li>python38Packages.aws-adfs</li>
    <li>python38Packages.aws-sam-translator</li>
    <li>python38Packages.aws-xray-sdk</li>
    <li>python38Packages.boto3</li>
    <li>python38Packages.botocore</li>
    <li>python38Packages.buildbot</li>
    <li>python38Packages.buildbot-full</li>
    <li>python38Packages.buildbot-ui</li>
    <li>python38Packages.cartopy</li>
    <li>python38Packages.celery</li>
    <li>python38Packages.certbot-dns-route53</li>
    <li>python38Packages.cfn-lint</li>
    <li>python38Packages.chalice</li>
    <li>python38Packages.credstash</li>
    <li>python38Packages.dependency-injector</li>
    <li>python38Packages.django-anymail</li>
    <li>python38Packages.django-raster</li>
    <li>python38Packages.djmail</li>
    <li>python38Packages.ec2instanceconnectcli</li>
    <li>python38Packages.fiona</li>
    <li>python38Packages.flower</li>
    <li>python38Packages.flowlogs_reader</li>
    <li>python38Packages.fs-s3fs</li>
    <li>python38Packages.gensim</li>
    <li>python38Packages.geopandas</li>
    <li>python38Packages.hass-nabucasa</li>
    <li>python38Packages.mapbox</li>
    <li>python38Packages.moto</li>
    <li>python38Packages.mypy-boto3-builder</li>
    <li>python38Packages.mypy-boto3-s3</li>
    <li>python38Packages.osmnx</li>
    <li>python38Packages.pyathena</li>
    <li>python38Packages.pycognito</li>
    <li>python38Packages.pyhiveapi</li>
    <li>python38Packages.pynamodb</li>
    <li>python38Packages.rasterio</li>
    <li>python38Packages.s3fs</li>
    <li>python38Packages.s3transfer</li>
    <li>python38Packages.sagemaker</li>
    <li>python38Packages.sapi-python-client</li>
    <li>python38Packages.scrapy</li>
    <li>python38Packages.scrapy-deltafetch</li>
    <li>python38Packages.scrapy-fake-useragent</li>
    <li>python38Packages.scrapy-splash</li>
    <li>python38Packages.serverlessrepo</li>
    <li>python38Packages.slicedimage</li>
    <li>python38Packages.smart-open</li>
    <li>python38Packages.snowflake-connector-python</li>
    <li>python38Packages.snowflake-sqlalchemy</li>
    <li>python38Packages.tensorboardx</li>
    <li>python38Packages.warrant</li>
    <li>python39Packages.aiobotocore</li>
    <li>python39Packages.aws-sam-translator</li>
    <li>python39Packages.aws-xray-sdk</li>
    <li>python39Packages.boto3</li>
    <li>python39Packages.botocore</li>
    <li>python39Packages.cartopy</li>
    <li>python39Packages.celery</li>
    <li>python39Packages.certbot-dns-route53</li>
    <li>python39Packages.cfn-lint</li>
    <li>python39Packages.chalice</li>
    <li>python39Packages.django-anymail</li>
    <li>python39Packages.django-raster</li>
    <li>python39Packages.djmail</li>
    <li>python39Packages.ec2instanceconnectcli</li>
    <li>python39Packages.fiona</li>
    <li>python39Packages.flower</li>
    <li>python39Packages.flowlogs_reader</li>
    <li>python39Packages.fs-s3fs</li>
    <li>python39Packages.gensim</li>
    <li>python39Packages.geopandas</li>
    <li>python39Packages.hass-nabucasa</li>
    <li>python39Packages.mapbox</li>
    <li>python39Packages.moto</li>
    <li>python39Packages.osmnx</li>
    <li>python39Packages.pyathena</li>
    <li>python39Packages.pycognito</li>
    <li>python39Packages.pyhiveapi</li>
    <li>python39Packages.pynamodb</li>
    <li>python39Packages.rasterio</li>
    <li>python39Packages.s3fs</li>
    <li>python39Packages.s3transfer</li>
    <li>python39Packages.sagemaker</li>
    <li>python39Packages.sapi-python-client</li>
    <li>python39Packages.scrapy</li>
    <li>python39Packages.scrapy-deltafetch</li>
    <li>python39Packages.scrapy-fake-useragent</li>
    <li>python39Packages.scrapy-splash</li>
    <li>python39Packages.serverlessrepo</li>
    <li>python39Packages.slack-sdk</li>
    <li>python39Packages.slicedimage</li>
    <li>python39Packages.smart-open</li>
    <li>python39Packages.snowflake-connector-python</li>
    <li>python39Packages.snowflake-sqlalchemy</li>
    <li>python39Packages.warrant</li>
    <li>s3bro</li>
    <li>s4cmd</li>
    <li>snakemake</li>
    <li>sourcehut.buildsrht</li>
    <li>sourcehut.coresrht</li>
    <li>sourcehut.dispatchsrht</li>
    <li>sourcehut.gitsrht</li>
    <li>sourcehut.hgsrht</li>
    <li>sourcehut.hubsrht</li>
    <li>sourcehut.listssrht</li>
    <li>sourcehut.mansrht</li>
    <li>sourcehut.metasrht</li>
    <li>sourcehut.pastesrht</li>
    <li>sourcehut.todosrht</li>
    <li>ssm-session-manager-plugin</li>
    <li>streamlit</li>
  </ul>
</details>
<details>
  <summary>4 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/botocore/default.nix:43:3:
```
   |
43 |   meta = with lib; {
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/s3transfer/default.nix:47:3:
```
   |
47 |   meta = with lib; {
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/boto3/default.nix:40:3:
```
   |
40 |   meta = {
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-include-tests.md">python-include-tests</a>

Consider adding a `checkPhase` for tests, or if not feasible, `pythonImportsCheck`.

Near pkgs/development/python-modules/s3transfer/default.nix:50:0:
```
   |
50 |     description = "A library for managing Amazon S3 transfers";
   | ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Review by Ma27 — APPROVED** [review]
awscli-related changes LGTM, also tested against my AWS account.

@NeQuissimus `nixopsUnstable` is python3, but nixops 1.7 is still python2. I guess it's OK to add a different `botocore` to `python2-packages.nix`. I think this should be done before merging into master.

**Comment by NeQuissimus** [comment]
Ah, this makes sense now. I froze all the dependencies `nixops` has, so they are compatible with Python 2.

**Comment by NeQuissimus** [comment]
NixOps on master is currently broken. Otherwise this should be good now.

```
~/dev/nixpkgs master λ nix-build -A nixops                                                                                       1 ↵
error: brotlicffi-1.0.9.2 not supported for interpreter python2.7
(use '--show-trace' to show detailed location information)
```

**Pull request merged**
