### PR TITLE
Pantheon updates 2021-11-24

### PR DESCRIPTION
**Pull request by bobby285271**
###### Motivation for this change

Part of Pantheon 6.0.4 updates (previous one at #147216).

- If you live on stable channel, please check our [planned backport workflow for 6.0.4 and 6.1](https://github.com/NixOS/nixpkgs/pull/146574).
- For upcoming Pantheon 7, check [OS 7 project board](https://github.com/orgs/elementary/projects/94) and [Danielle's tweet](https://twitter.com/DanielFore/status/1462885304419774468) for more details.

###### Things to do

- [x] https://github.com/elementary/gala/issues/1312
- [x] https://github.com/elementary/applications-menu/pull/513

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
#### pantheon.wingpanel-applications-menu: 2.9.1 -> 2.10.0
- [Release on GitHub](https://github.com/elementary/applications-menu/releases/tag/2.10.0)
- [Compare changes on GitHub](https://github.com/elementary/applications-menu/compare/2.9.1...2.10.0)

###### Comment

Needs test switchboard plugin search.

###### To inspect upstream changes
- [ ] [`Avoid using a MainLoop in Switchboard Plugin (#513)`](https://github.com/elementary/applications-menu/commit/5f3a20cd1868f17cca94b33731470e2cd13c2a03)
- [x] [`Update applications-menu.appdata.xml.in`](https://github.com/elementary/applications-menu/commit/8ece767a1fe75c95628d45211bc424b23bf58574)
- [x] [`Add Files bookmarks to search (#514)`](https://github.com/elementary/applications-menu/commit/71accf07fda91c2c84f213f1e6f630e8b95b7145)
- [x] [`Update applications-menu.appdata.xml.in`](https://github.com/elementary/applications-menu/commit/15b19fef64a0457a91ad8df1622fbf42ff132997)
- [x] [`Bookmarks Plugin: Get default file browser name (#517)`](https://github.com/elementary/applications-menu/commit/32c977866baa93dea6e2e84598d3ef375c5e617e)
- [x] [`Release 2.10.0 (#515)`](https://github.com/elementary/applications-menu/commit/61bc824b5f4477e580a52e8035d0b8142e3df10f)

---

#### pantheon.gala: 6.2.1 -> 6.3.0
- [Release on GitHub](https://github.com/elementary/gala/releases/tag/6.3.0)
- [Compare changes on GitHub](https://github.com/elementary/gala/compare/6.2.1...6.3.0)

###### Comment

Needs upstream fix or mutter downgrade (3.36)

###### To inspect upstream changes
- [x] [`Add systemd units (#1256)`](https://github.com/elementary/gala/commit/d425959aa2b9b9ac7ef622f601f3de1ca8ee768a)
- [ ] [`autostarts: set hidden under systemd (#1255)`](https://github.com/elementary/gala/commit/bd362ec0c89bd72c5afca3f8313ee70d7ee25357)
- [x] [`Fix gala-x11.service timeout`](https://github.com/elementary/gala/commit/cc8692ab2766d3fde42ebf8eaadeab3f5b3c45f7)
- [ ] [`multitasking: Don't use smooth scroll events to handle mouse wheel (#1266)`](https://github.com/elementary/gala/commit/d2dcfdefdf97c1b49654179a7acd01ebfe017308)
- [x] [`Update gala.appdata.xml.in`](https://github.com/elementary/gala/commit/0c89e7c8e151665fb7e380457f0155e3757a92fd)
- [x] [`multitasking: Enable bump animation for mouse scroll (#1270)`](https://github.com/elementary/gala/commit/a682b59ae623092e7a1a81461b9c8edc91152563)
- [ ] [`Bring "Catts" in-tree (#1234)`](https://github.com/elementary/gala/commit/52cbc3cc7b1e566d718fcfd527fb99176a1d829f)
- [x] [`Update gala.appdata.xml.in`](https://github.com/elementary/gala/commit/df1afe1d53fd4f1f624c5bd5b3db9d0cab868eda)
- [ ] [`multitasking: Show nudge animation only on the primary display (#1275)`](https://github.com/elementary/gala/commit/2fbe184042cf3c0ed1964a24d122b1a9931473ec)
- [ ] [`open WindowSwitcher on current monitor`](https://github.com/elementary/gala/commit/4eeaca579b308db9b77332f8f2446c038d209fd7)
- [ ] [`WindowManager: handle empty action keys (#1290)`](https://github.com/elementary/gala/commit/72869e0e34e2a62d6c90c99ce822c0dd2685773c)
- [ ] [`Handle signal to close Gala gracefully on Mutter 3.41`](https://github.com/elementary/gala/commit/9d6f980d19d9f59a359fe7c6eac867c10d67491e)
- [ ] [`IconGroupContainer: add null check to get_next_sibling`](https://github.com/elementary/gala/commit/e5523a2afb138b257ee3ba293c351a9deed6be9e)
- [ ] [`MultitaskingView: don't set custom easing mode`](https://github.com/elementary/gala/commit/65da8f77678fb77cdf2e8e4c7df4625dec0aca5f)
- [ ] [`WindowManager: dim parents of modals (#1285)`](https://github.com/elementary/gala/commit/de1b897bab3e4aa96a79e409c1e09ebbff9c8915)
- [ ] [`Tooltip: null check text_actor before removing (#1293)`](https://github.com/elementary/gala/commit/ebfa8ea45d6da7ad76a23c47a1f3f6aaba014b5b)
- [x] [`Remove DockThemeManager (#1294)`](https://github.com/elementary/gala/commit/336332f4e703ce6362693056c4c176407119726d)
- [ ] [`WindowManager: explicitly dim and undim (#1298)`](https://github.com/elementary/gala/commit/e1bd8bc3063d91da2d0b46682d1549cb6d2fdc72)
- [ ] [`WindowManager: dialogs fall down (#1297)`](https://github.com/elementary/gala/commit/1e3a7c171aa49622d0b743007ebcf4d2518dfa93)
- [ ] [`Tooltip: get text color from style context (#1295)`](https://github.com/elementary/gala/commit/869aa70cfeb1db0396e7e5813b170ec7f80aec02)
- [x] [`build: add systemduserunitdir option`](https://github.com/elementary/gala/commit/78a5f881ba329ea28ade0c3c91fe18521135877a)
- [ ] [`WindowClone: Include spread in bounding box`](https://github.com/elementary/gala/commit/c544da13648f7e3b594270cd72152303117260b7)
- [x] [`Update gala.appdata.xml.in`](https://github.com/elementary/gala/commit/5db27711dcd647d868777c640149747c65b05715)
- [ ] [`Update src/Widgets/WindowClone.vala`](https://github.com/elementary/gala/commit/9d416f6b266983a15fb553f0ede7735bd2412d9d)
- [ ] [`WindowManager: don't type check when undim (#1304)`](https://github.com/elementary/gala/commit/6b65615de458b51d5fb8863e01dff5595827316b)
- [ ] [`Fix various typos (#1310)`](https://github.com/elementary/gala/commit/faac78782c32f056e01c664c8b83ee41b4d97e00)
- [x] [`Release 6.3.0 (#1276)`](https://github.com/elementary/gala/commit/7fb2bef718dc29591f419a66a2027cc14626ad4c)

---

#### pantheon.elementary-code: 6.0.1 -> 6.1.0
- [Release on GitHub](https://github.com/elementary/code/releases/tag/6.1.0)
- [Compare changes on GitHub](https://github.com/elementary/code/compare/6.0.1...6.1.0)

###### Comment

Maybe needs look into the force use portals change.

###### To inspect upstream changes
- [x] [`Add aarch64 architecture support to flatpak builds (#1106)`](https://github.com/elementary/code/commit/61776d6ddebc6e488f35545fe94a3340cdee46d5)
- [x] [`Document: Object style, fix parameter typo (#1110)`](https://github.com/elementary/code/commit/53b5ed64d6129d184eaf816a16d893d41738e1db)
- [x] [`Document: fix non-construct file set`](https://github.com/elementary/code/commit/aaea296de992abf7d1931e21a2beefdfedbb8d39)
- [x] [`Change setting to Visible whitespace. (#1109)`](https://github.com/elementary/code/commit/efde221803390276dbe1ce4981b6552c8f04d027)
- [x] [`Distinguish projects with same folder name (#1112)`](https://github.com/elementary/code/commit/1404628b830acc17d477e8b1be3592fb0341187a)
- [x] [`Updated the libvala dependency version in Readme (#1115)`](https://github.com/elementary/code/commit/f9e34b5d33adb6a040aec230f45c38809f7a0348)
- [x] [`Removing toggling of terminal button visibility (#806)`](https://github.com/elementary/code/commit/cd8435ac7792e337e20b1d9fac31c4715f782b02)
- [ ] [`Make search results easier to see by scrolling a little bit more (#1121)`](https://github.com/elementary/code/commit/6778f502e81638382cdb28c4d76e30386aa76e33)
- [ ] [`Fix terminal hotkeys not captured and affect the document (#1122)`](https://github.com/elementary/code/commit/fcbd15a357b0148e417223f040a4db6876bc288b)
- [x] [`FileView.vala: Fix indentation and namespace (#1120)`](https://github.com/elementary/code/commit/a4e0c2dc28dc3e73d5ff8900fa8d49ffd7d6a696)
- [ ] [`Application: force use portals (#1119)`](https://github.com/elementary/code/commit/46364d1588426c6f0340f93d06e04b53e8e2ec44)
- [ ] [`GlobalSearchDialog: set active_window as transient parent (#1128)`](https://github.com/elementary/code/commit/632b0c827dfaf2a14e89038486976f0e58365d97)
- [x] [`Fix various typos (#1133)`](https://github.com/elementary/code/commit/16d771627b6e04407a6779cc4cc70258e85192c9)
- [x] [`Update io.elementary.code.appdata.xml.in`](https://github.com/elementary/code/commit/440e0409f9b991466aa97f3d156af064fb1c1e78)
- [ ] [`Document: set filechooser dialog as transient for main window (#1135)`](https://github.com/elementary/code/commit/a4083ab5aa1f49d74e7fee786ad6f53bf5f2f524)
- [x] [`Release 6.1.0 (#1131)`](https://github.com/elementary/code/commit/4a111ecbdc3060b36ef6ffb23510a0f0b52129be)

**Comment by bobby285271** [comment]
@ofborg test pantheon

**Comment by bobby285271** [comment]
Result of `nixpkgs-review pr 147256` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>25 packages built:</summary>
  <ul>
    <li>monitor</li>
    <li>pantheon.elementary-code</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-gsettings-schemas</li>
    <li>pantheon.elementary-session-settings</li>
    <li>pantheon.gala</li>
    <li>pantheon.switchboard-plug-a11y</li>
    <li>pantheon.switchboard-plug-mouse-touchpad</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-plug-power</li>
    <li>pantheon.switchboard-plug-security-privacy</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-a11y</li>
    <li>pantheon.wingpanel-indicator-bluetooth</li>
    <li>pantheon.wingpanel-indicator-datetime</li>
    <li>pantheon.wingpanel-indicator-keyboard</li>
    <li>pantheon.wingpanel-indicator-network</li>
    <li>pantheon.wingpanel-indicator-nightlight</li>
    <li>pantheon.wingpanel-indicator-notifications</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-indicator-session</li>
    <li>pantheon.wingpanel-indicator-sound</li>
    <li>pantheon.wingpanel-with-indicators</li>
  </ul>
</details>

**Comment by bobby285271** [comment]
Result of `nixpkgs-review pr 147256` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>25 packages built:</summary>
  <ul>
    <li>monitor</li>
    <li>pantheon.elementary-code</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-gsettings-schemas</li>
    <li>pantheon.elementary-session-settings</li>
    <li>pantheon.gala</li>
    <li>pantheon.switchboard-plug-a11y</li>
    <li>pantheon.switchboard-plug-mouse-touchpad</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-plug-power</li>
    <li>pantheon.switchboard-plug-security-privacy</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-a11y</li>
    <li>pantheon.wingpanel-indicator-bluetooth</li>
    <li>pantheon.wingpanel-indicator-datetime</li>
    <li>pantheon.wingpanel-indicator-keyboard</li>
    <li>pantheon.wingpanel-indicator-network</li>
    <li>pantheon.wingpanel-indicator-nightlight</li>
    <li>pantheon.wingpanel-indicator-notifications</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-indicator-session</li>
    <li>pantheon.wingpanel-indicator-sound</li>
    <li>pantheon.wingpanel-with-indicators</li>
  </ul>
</details>

**Review by davidak — COMMENTED** [review]
Quick review looks good. Thank you!

**Pull request merged**
