### PR TITLE
Initial cross-compilation support for RISC-V

### PR DESCRIPTION
**Pull request by shlevy**
Tested up to building `nixUnstable` which ran a repl successfully under `qemu-riscv`.

Part of #35089

### CODE REVIEW

**Comment by shlevy** [comment]
cc @bgamari as well.

**Comment by shlevy** [comment]
nixUnstable now building.

**Comment by shlevy** [comment]
@GrahamcOfBorg @grahamc This isn't a change from where things were before, right?

**Comment by shlevy** [comment]
@GrahamcOfBorg eval

**Comment by shlevy** [comment]
@grahamc Is there an easy way to see the list of packages ofborg thinks will rebuild?

**Comment by bgamari** [comment]
Excellent, I have been very interested in adding RISC-V support to GHC at some point. This will be quite useful.

**Comment by Ericson2314** [comment]
Wooo! This is a fun thing to come back to.

**Comment by shlevy** [comment]
@Ericson2314 Does it look OK?

**Comment by shlevy** [comment]
@Ericson2314 FYI https://github.com/shlevy/nixos-riscv-bootstrap

**Comment by Ericson2314** [comment]
@shlevy Indeed it does! I might try to remove the need for a `musl-multiplatform` as part of my #34274 crusade, but that's a separate goal and not at all a problem with this PR :).

**Pull request merged**
