### PR TITLE
linux: disable DEBUG_INFO_BTF by default

### PR DESCRIPTION
**Pull request by Atemu**
###### Motivation for this change

linux: disable DEBUG_INFO_BTF by default

It made the ZFS module balloon in size and probably shouldn't be enabled on
production kernels to begin with.

Fixes https://github.com/NixOS/nixpkgs/issues/140851

Merge this so that it ends up in the same eval as https://github.com/NixOS/nixpkgs/pull/141112 to avoid unnecessary rebuilds.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
Afaik NixOS would be the only one not to enable BTF.

**Comment by Artturin** [comment]
fedora config available here https://src.fedoraproject.org/rpms/kernel//blob/rawhide/f/kernel-x86_64-fedora.config

**Comment by Atemu** [comment]
You can try it yourself, it's not an option we can set.

**Comment by nagisa** [comment]
One other consequence of `DEBUG_INFO_BPF` is that it is impossible to build a kernel on systems with full 16G of `/tmp` available now. I vote for landing this.

**Comment by roblabla** [comment]
NixOS would then be the only platform to not support BTF, which would make using and packaging bpf-based tools really annoying, as it'd require the users to do their own kernel builds instead of relying on the kernel in the nix binary cache. On the other hand, if you're doing a local build of the kernel, you can trivially turn the option off in your own configuration.nix.

**Comment by nagisa** [comment]
> trivially turn the option off in your own configuration.nix

While the process of turning the option off is fairly straightforward, figuring out what to turn off when starting with "zfs module is too large to fit into my `/boot`" or "why is building kernel requiring so much memory/disk space" is not. If there's a good way to inform the user they might want to turn this specific option off, then I'm comfortable with leaving this in for the prebuilt builds.

> if you're doing a local build of the kernel

Local builds don't necessarily happen _because_ of changes to the derivation. Testing changes to `nixpkgs` or using channels for which hydra hasn't cached the build for whatever reason are both also perfectly valid use-cases.

**Comment by Atemu** [comment]
> One other consequence of `DEBUG_INFO_BTF` is that it is impossible to build a kernel on systems with full 16G of `/tmp` available now. I vote for landing this.

The builddir of kernel I just built does indeed take ~19GiB apparent and ~10GiB lz4'd which is quite a lot.

You can just put that in /var/tmp instead though, or, since you're compiling your own kernel anyways, set btf=no.

**Pull request closed without merging**
