### PR TITLE
Additional travis checks

### PR DESCRIPTION
**Pull request by joachifm**
Mostly to get the ball rolling, I'm sure it can be improved.

cc @domenkozar 

Fair warning: I will squash & merge this if nobody complains.

### CODE REVIEW

**Comment by joachifm** [comment]
cc @domenkozar

**Comment by jagajaga** [comment]
Won't that significantly affect check time?

**Comment by joachifm** [comment]
I enabled travis on my nixpkgs fork, didn't seem to greatly increase check time, but ofc. that's with binary substitions available for everything.

**Comment by joachifm** [comment]
But it could be that building the manual exercises all the code paths we care about for a travis check.

**Comment by joachifm** [comment]
For reference, this is an example of this in practice: https://travis-ci.org/joachifm/nixpkgs/builds/126907357

**Comment by jagajaga** [comment]
:+1:

**Comment by dezgeg** [comment]
I have a feeling this unnecessarily builds the manual for both i686 and x86_64, one arch should be enough. Other than that, :+1:.

**Comment by joachifm** [comment]
@dezgeg you're right, I will fix that.

**Comment by domenkozar** [comment]
We should really rebuild it if manual changed. Using similar logic as nox already uses to figure out what packages to build.

**Comment by jagajaga** [comment]
@domenkozar what about this https://github.com/NixOS/nixpkgs/issues/10490?

**Comment by joachifm** [comment]
@domenkozar do you consider that a blocker? I'm not currently too keen on adding that logic for what I consider to be a fairly cheap build, but I can see why you'd want it.

**Comment by domenkozar** [comment]
Not sure about this. I'm +1 in general, but then it takes 9min just to "setup" the build and do the checks now. Also it's using 2k out of 10k log lines. This will catch some errors with manual builds, but it will also make more builds fail due to resource limits (build time run, log file limit).

Just another reason why travis-ci is not our best bet on the long run.

**Comment by joachifm** [comment]
On my fork, the whole thing takes 6 minutes, the log output from building the nixos manual is 12 lines. Building the system generates a *lot* of output, though. I'll see about adding some conditionals, but that won't be a priority for me, so might never happen.

@domenkozar Is it possible to do caching for our travis builds?

**Comment by jagajaga** [comment]
@joachifm https://docs.travis-ci.com/user/caching/
Or you can create a docker image with everything we need and use it there.

**Comment by joachifm** [comment]
@jagajaga ah, thanks, I seemed to recall that caching support had been made available to free users. Looks like that would be quite a big benefit for us, but then I wonder why it's not already enabled. Do you know?

**Comment by jagajaga** [comment]
Maybe that's a new feature...

**Comment by joachifm** [comment]
Hm, so the nixpkgs manual can be a real problem, because it may trigger a build of a full Haskell environment (due to pandoc I guess)

**Comment by joachifm** [comment]
What about not building the manuals & just do `nix-build nixos/release.nix -A options`? Or maybe `manpages.x86_64-linux`.

**Comment by zimbatm** [comment]
How far are we to have hydra build the PRs ?

**Comment by joachifm** [comment]
@zimbatm not too far, I hope: https://github.com/NixOS/hydra/pull/280

**Comment by zimbatm** [comment]
I think we should merge this and see how it goes. We can always refine or revert.

**Comment by joachifm** [comment]
Okay, I've reduced this to only build the NixOS options, which at least will catch a few additional silly errors. I'll merge it soon, barring objections.

**Comment by joachifm** [comment]
For example, it would have caught an error in https://github.com/NixOS/nixpkgs/pull/15283, which travis currently says is okay.

**Comment by zimbatm** [comment]
:+1:

**Pull request merged**
