### PR TITLE
kernel-config: Enable framebuffer console for BIOS systems & /proc/config.gz for ARM

### LINKED ISSUE #8139: Boot messages no longer shown during boot
I rebuilt off master sometime earlier today and rebooted. I was greeted by nice new GRUB background (nice) but also no boot messages after that. It just showed me the GRUB background for a while then a black screen for a while then lightdm finally came up.

How do I restore the boot messages? It's hard to tell if something is hanging or restarting or whatever without them.

### PR DESCRIPTION
**Pull request by dezgeg**
The first commit is needed to fix #8139 as some EFI fixes to GRUB (commit 159fed47bcfab67d36d4959fb3ac952a7ad9128c) now apparently cause the kernel  to boot in graphical/framebuffer mode instead of text mode. The second one fixes `/proc/config.gz` not existing on ARM even though it should.

I tested the FB_VESA thing on i686 Virtualbox only, no other x86 NixOS systems around.

cc @wkennington for #8139, and kernel maintainers @thoughtpolice @shlevy

### CODE REVIEW

**Comment by shlevy** [comment]
I'm confused, the `FRAMEBUFFER_CONSOLE` change doesn't seem related to this bug at all (we don't even use grub on EFI). I'm not hugely attached to keeping fbcon modular, but in general we try for as modular a kernel as possible and it's not clear how this improves things.

Similarly, can't we just load the vesa module on non-efi?

:+1: on the IKCONFIG

**Comment by wkennington** [comment]
LGTM, not having the framebuffer built in was largely confusing for efi users and the vesa default seems sane.

**Comment by wmertens** [comment]
LGTM2

**Comment by obadz** [comment]
I have a hidpi screen and now the grub screen takes ~ 5 seconds to display and the same amount of time to refresh everytime I hit a key.  Is there some way for me to force a lower res?

https://github.com/obadz/nixpkgs/issues/1

**Pull request merged**
