### PR TITLE
way-cooler: Remove

### PR DESCRIPTION
**Pull request by matthiasbeyer**
###### Motivation for this change

As of 2020-01-09, way-cooler is officially dead:

    http://way-cooler.org/blog/2020/01/09/way-cooler-post-mortem.html

hence, remove the package and the module.

---

Pinging maintainers from the packages touched in this PR:

@gnidorah @miltador @primeos

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
We should, of course, discuss whether this is what we want. But as we removed 'rtv' just a few days ago because it is no longer maintained, I'd guess that this is the way (not so cool) forward.

**Comment by Valodim** [comment]
The maintainer doesn't seem confident that anyone will step up to take over the project in that postmortem. The module looks extensive though - I wonder how many people's break if we remove it? Is there a way to display deprecation warnings for a grace period, and give it some time to see if someone steps up to maintain the project? It *does* have 2.5k github stars.

**Comment by matthiasbeyer** [comment]
From what I experienced during the removal (I do not say deprecation process here, please notice that!) of `rtv`, we do not have a process. I'd love to have one to follow, but we do not.

**Comment by gnidorah** [comment]
@Valodim 
I'm for to remove it completely, since we now have a retirement letter from developer. It was an immature product, no one used it seriously. I already dropped `orbment` and `velox` wayland compositors for the same reason.
Also `wlc` library on which this product is based is deprecated for years now.
If someone will revive it and make it at least not worser quality than Sway, then I will re-add it.

**Review by ghost — APPROVED** [review]
Finally! Thank you! :)

**Comment by Valodim** [comment]
Sounds reasonable. Go for it :+1:

**Comment by adisbladis** [comment]
@matthiasbeyer Can you please add a change log entry?

**Comment by matthiasbeyer** [comment]
Sure, where?

**Comment by adisbladis** [comment]
@matthiasbeyer https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2003.xml

**Comment by matthiasbeyer** [comment]
Ah. No, I refuse to work with that XML garbage. Someone else can add it, I will cherry-pick the commit onto this PR.

**Comment by grahamc** [comment]
Closing until somebody does that.

**Pull request closed without merging**
