### PR TITLE
gnomeExtensions.open-bar: init at unstable-2024-06-17

### PR DESCRIPTION
**Pull request by heywoodlh**
## Description of changes

Adds openbar GNOME extension

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by heywoodlh** [comment]
@jtojnar when I attempted to use it, I ran into this issue: https://github.com/neuromorph/openbar/issues/38

Once I have it in a functional state, I'll be happy to rework this to update the current package and would appreciate feedback on how to actually implement that (the nixpkgs GNOME extension documentation was really not clear to me -- which is why I'm probably doing it incorrectly).

**Comment by heywoodlh** [comment]
@jtojnar I can confirm my latest commit fixes the issue I linked above.

Please let me know how I should organize this correctly and I will do what is needed. :thumbsup:

**Comment by heywoodlh** [comment]
This technically still has one other issue that I think should be addressed before this is considered ready, that I outlined in this comment: https://github.com/neuromorph/openbar/issues/38#issuecomment-2187664398

The issue is that the files this extension generates are all created with `444` permissions, which causes the extension to not turn back on if you turn it off and try to turn it back on.

I also need to add my commit to add myself as a maintainer.

**Comment by balintbarna** [comment]
I tested using the latest commit on the nixfix branch of open bar and it works correctly so far. I think the branch is on the active development path though and has quite a few bugs. Once it is merged in though, the auto packaging should be sufficient.

**Comment by heywoodlh** [comment]
Latest main branch of open-bar works properly for me!

@jtojnar it seems like the best thing would be for me to back out this PR and revert back to nixpkgs' automatic updating of GNOME extensions. Or maybe I can repurpose this PR to update all the extensions to the latest version?

What would you suggest would be the best path forward for getting the latest working version of openbar added to nixpkgs?

**Comment by jtojnar** [comment]
If the release comes soon, you can update all extensions.

Probably better to open a new PR for that.

**Comment by balintbarna** [comment]
If the custom packaging doesn’t add any extra value maybe it’s better to remove it, then it’s less stuff to maintain, right?

**Pull request closed without merging**
