### PR TITLE
Remove Java 7 and Java 9, bootstrap JDK 10 via JDK 10 

### PR DESCRIPTION
**Pull request by thoughtpolice**
###### Motivation for this change

This bootstraps the JDK 10 builds using a pre-existing JDK 10 binary bootstrap tarball, created using `pkgs/development/compilers/make-bootstrap.nix`. The bootstrapping images for i686 and x86_64 are both compiled to a fixed point: I compiled the original images with JDK 9, producing a minimal JDK 10 bootstrap image, and used it to build a minimal JDK 10 _again_, and packaged that as the final image. So this is JDK10 compiled by JDK10.

With this in place, we can remove the constraint on Java9 as the JDK 10 bootstrap method, and proceed to eliminate it.

I also took the liberty to take this time to remove some ancient packages that were still relying on JDK 7, and eliminate that too. Technically I believe Red Hat is still supporting it (it was EOL'd years ago otherwise by Oracle), but honestly I see little reason to keep building it; less packages for Hydra are always better.

To do this however, I had to eliminate some older packages nobody is maintaining anymore it seems: ECJ (the Eclipse Java Compiler), GNU classpath, and an ancient version of `processing` 2.0. I hope this is OK; I have no need for these packages and nobody seems to have touched them in years, really, other than tree-wide changes. So I think they should go, too.

With this, Nixpkgs only offers JDK 8 and JDK 10, which is a much easier support window (especially for my upcoming plans, such as the Shenandoah previews).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
- [ ] Binary tarballs must be moved to `tarballs.nixos.org` and off Dropbox and my personal server; @shlevy will handle this.

---

### CODE REVIEW

**Comment by shlevy** [comment]
@thoughtpolice Any idea about the build failure here?

**Review by shlevy — APPROVED** [review]
Overall LGTM. Will upload tarballs when this is otherwise completely ready, would like to understand the build failure and give some time for people to object to the removals first.

**Comment by thoughtpolice** [comment]
Apparently the doc building failed or something? But I have no clue how!

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ffff7469872, pid=18114, tid=140736692631296
#
# JRE version: OpenJDK Runtime Environment (8.0_40) (build 1.8.0_40-27)
# Java VM: OpenJDK 64-Bit Server VM (25.40-b25 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x7c872]  _int_free+0x5c2
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /build/jdk8u-jdk8u172-b02/make/hs_err_pid18114.log
Compiled method (c1)   16742 2487       3       com.sun.tools.javadoc.DocImpl::comment (104 bytes)
 total in heap  [0x00007fffe1578490,0x00007fffe1579f28] = 6808
 relocation     [0x00007fffe15785b8,0x00007fffe15786f8] = 320
 main code      [0x00007fffe1578700,0x00007fffe15795c0] = 3776
 stub code      [0x00007fffe15795c0,0x00007fffe15796d8] = 280
 metadata       [0x00007fffe15796d8,0x00007fffe1579748] = 112
 scopes data    [0x00007fffe1579748,0x00007fffe1579c08] = 1216
 scopes pcs     [0x00007fffe1579c08,0x00007fffe1579e88] = 640
 dependencies   [0x00007fffe1579e88,0x00007fffe1579ea0] = 24
 nul chk table  [0x00007fffe1579ea0,0x00007fffe1579f28] = 136
Compiled method (c1)   16742 2487       3       com.sun.tools.javadoc.DocImpl::comment (104 bytes)
 total in heap  [0x00007fffe1578490,0x00007fffe1579f28] = 6808
 relocation     [0x00007fffe15785b8,0x00007fffe15786f8] = 320
 main code      [0x00007fffe1578700,0x00007fffe15795c0] = 3776
 stub code      [0x00007fffe15795c0,0x00007fffe15796d8] = 280
 metadata       [0x00007fffe15796d8,0x00007fffe1579748] = 112
 scopes data    [0x00007fffe1579748,0x00007fffe1579c08] = 1216
 scopes pcs     [0x00007fffe1579c08,0x00007fffe1579e88] = 640
 dependencies   [0x00007fffe1579e88,0x00007fffe1579ea0] = 24
 nul chk table  [0x00007fffe1579ea0,0x00007fffe1579f28] = 136
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

The only thing I can think of is if b2b98b87d1ef1a114eccd675ad85d188aef45acc somehow has changed something, but I can't really imagine how, since otherwise I don't think any JDK 8 rebuild would have happened at all!

Maybe it had an OOM?

**Comment by shlevy** [comment]
@GrahamcOfBorg build openjdk8

**Comment by shlevy** [comment]
@thoughtpolice OK, looks good to me. Any more changes pending besides the URL update?

**Comment by vcunat** [comment]
I suppose at least the removals are suitable for 18.03 before we announce it &ndash; but you surely know the java stuff better than me...

**Comment by jerith666** [comment]
I agree, probably best to backport these removals to 18.03 as well.

**Comment by thoughtpolice** [comment]
Yes, I think we should backport this; I can do that. @shlevy I think this is otherwise ready to go if you're willing to upload the tarballs; I can adjust the URLs and merge.

**Comment by NeQuissimus** [comment]
:+1: Java 9, the one nobody ever used xD

**Comment by shlevy** [comment]
@thoughtpolice `http://tarballs.nixos.org/openjdk/2018-03-31/{8,10}/{x86_64,i686}-linux.tar.xz` now exist. You probably want to use the `name` attribute to `fetchurl` to avoid changing all the downstream hashes.

**Comment by thoughtpolice** [comment]
I rebased this into `master` directly but it didn't close this. :/ Thanks @shlevy for the help, and everyone else!

I'll be porting these to 18.03 soon.

**Comment by vcunat** [comment]
@thoughtpolice: you haven't got to look at this for 18.03, right?  (I don't know the Java ecosystem.)

**Comment by thoughtpolice** [comment]
Sorry I missed this @vcunat -- yes, I *thought* I had pushed these changes a while back, but had not it seems! I'll look into fixing this...

**Pull request closed without merging**
