### PR TITLE
Android Studio improvements

### PR DESCRIPTION
**Pull request by primeos**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by LnL7** [comment]
I think this broke evaluation https://gist.github.com/GrahamcOfBorg/6b399b49b5528b9befa525051bd2c2f9

**Comment by primeos** [comment]
@LnL7 Looking at the last line:
```
attribute 'gconf' missing, at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-2-shlevy.ewr1.nix.ci/pkgs/applications/networking/instant-messengers/gitter/default.nix:16:6
```
I think this was actually due to https://github.com/NixOS/nixpkgs/commit/e090fb29672530c14bb14b153fabdca2280835b0, but thank you very much for the notification anyway :smile:.

From the fist lines it definitely looks like this PR is responsible:
```
trace: android-studio-preview and androidStudioPackages.preview are old aliases
and will be dropped at some point, please use androidStudioPackages.beta
instead (corresponds to the correct channel name).
```
But that's actually supposed to be there (when building android-studio-preview or androidStudioPackages.preview), I'm not sure if that was a good idea though, let's hope this doesn't cause any problems with Hydra... (if it does or if we don't want this, we can revert https://github.com/NixOS/nixpkgs/pull/44310/commits/88bfbf6c7d2308b59f1ca69169c8c9853815ae6b)

**Comment by vcunat** [comment]
There were apparently two problems at that point.  ATM reverting your commit fixed the tarball job for me, so I pushed that.  Maybe this is doable by fixing the tarball job instead, but at least for now...

**Comment by primeos** [comment]
@vcunat Thank you very much for reverting it and sorry for any inconvenience caused (was hoping it would be fine...).

**Pull request merged**
