### PR TITLE
bruno: add giflib build dependency

### PR DESCRIPTION
**Pull request by martinjlowm**
## Description of changes

Bruno depends on react-pdf which in turn requires node-canvas. As per its documentation, node-canvas, requires giflib during compilation, see https://github.com/Automattic/node-canvas/tree/master?tab=readme-ov-file#compiling.

Without it, building bruno fails at the canvas installation step with:

```
bruno> npm ERR! In file included from ../src/CanvasPattern.cc:6:
bruno> npm ERR! ../src/Image.h:18:10: fatal error: 'gif_lib.h' file not found
bruno> npm ERR! #include <gif_lib.h>
bruno> npm ERR!          ^~~~~~~~~~~
bruno> npm ERR! 1 error generated.
```

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mattpolzin** [comment]
Odd, I've been thus far able to build Bruno on Darwin machines. The docs indicate `giflib` and others are optional, but perhaps they are required the way Bruno is using them. I'm tempted to say "why not" even if `giflib` is optional, but I'd still ideally like to reproduce the failure you are getting.

**Comment by martinjlowm** [comment]
> Odd, I've been thus far able to build Bruno on Darwin machines. The docs indicate `giflib` and others are optional, but perhaps they are required the way Bruno is using them. I'm tempted to say "why not" even if `giflib` is optional, but I'd still ideally like to reproduce the failure you are getting.

That's fair. I didn't look into the optionality part - I simply assumed it was required because of the node-gyp error.

**Comment by mattpolzin** [comment]
> Yeah... I have giflib installed via Homebrew (which I'm in the process of migrating away from), so it finds that in /usr/lib.

Oh, so that's why it builds ok for me on my machine. This is starting to make sense finally; config determines you do have `giflib`, build fails to find headers for it.

Does it build if you use `sandbox = true` then?

**Comment by mattpolzin** [comment]
I guess I wouldn't expect sandboxing to help here since the helper JS is explicitly looking at system paths... unfortunate way of doing what they are doing. 

I don't really like the idea of adding more optional dependencies each time their JS code finds a new system install on someone's computer, especially since depending on how the results of that JS helper are used, we may add the dependency to the Nix derivation only to have it not used unless you happen to have the same library on your machine outside of NixOS.

I wonder if it's worth patching the JS in the canvas project somehow to avoid this mess.

**Comment by mattpolzin** [comment]
FWIW, I believe I've confirmed that Bruno makes no use of Canvas being built with optional `giflib` support, so we are really talking about a bug (from the perspective of Nix) with how the Canvas NodeJS library determines whether that library should be used or not. The Canvas tool forces any downstream project to build their distributions in isolated environments or else risk their own developer machine polluting the native compilation of the canvas library.

**Comment by martinjlowm** [comment]
> FWIW, I believe I've confirmed that Bruno makes no use of Canvas being built with optional `giflib` support, so we are really talking about a bug (from the perspective of Nix) with how the Canvas NodeJS library determines whether that library should be used or not. The Canvas tool forces any downstream project to build their distributions in isolated environments or else risk their own developer machine polluting the native compilation of the canvas library.

I totally agree. Good conversation nonetheless for future reference. I'll go ahead and close this one.

**Pull request closed without merging**
