### PR TITLE
rust: fix building in debug mode

### PR DESCRIPTION
**Pull request by arcnmx**
###### Motivation for this change

#56540 broke a few things regarding rust builds and did not have the intended effect:

- bdd3c3fdcb11416d2e2ef459c2e28caa2235f0f3 intended to support debug builds, but passes an invalid `--debug` flag to `cargo build`
- 60761e65ba38280ce19e1d7e3c4ffd883212a96c intended to make sense of cargo target directories, but breaks cargo.
  1. it deletes `$CARGO_TARGET_DIR/debug`, and symlinking/moving `$CARGO_TARGET_DIR/x86_64-unknown-linux-gnu/debug` to it, assuming they're redundant?
  2. this is an incorrect change, as cargo seems to produce and use both directories for different purposes? Each directory has its own lock file, which cargo attempts to use. When both lock files are symlinked to be the same thing, cargo will deadlock itself.
  3. this prevents `cargo test` from working, the only reason it happens to work now is because this step mangles the release directory, while the default `checkPhase` builds tests in debug mode. Changing `buildType` to `debug` or using `cargo test --release` instead will expose the deadlock.
  4. buildRustPackage provides `releaseDir` for this, anything that hard-codes target/release are messy hm...
      - messageformat=json stuff could maybe be used to find binary paths for packaging purposes instead? This is a a rather annoying and [long-standing](https://github.com/rust-lang/cargo/issues/3670) [limitation](https://github.com/rust-lang/cargo/issues/1924) of cargo.

cc @illegalprime @Ericson2314

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
  - will try this soon, it might take a while..?
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Could also mention `$releaseDir` in `doc/languages-frameworks/rust.section.md`?

**Comment by arcnmx** [comment]
> Could you also mention $releaseDir in doc/languages-frameworks/rust.section.md?

Seems appropriate yeah.

> Maybe we should also mention this in the NixOS changelog for out-of-tree rust packages because people need to upgrade.

Hmm... If you want backward-compatibility we could set `CARGO_TARGET_DIR` so cargo doesn't build in `$sourceRoot/target` by default and then just `ln -s $releaseDir target/$buildType` for derivations that rely on that path?

**Comment by FRidh** [comment]
Status?

**Comment by arcnmx** [comment]
Oh, was looking for feedback on whether `CARGO_TARGET_DIR` was a better idea.

To itemize the concerns I'd like feedback on more specifically before proceeding:
- [ ] `CARGO_TARGET_DIR` is currently unset (and thus roughly defaults to `$sourceRoot/target`). Is setting it acceptable? This seems less likely to break existing derivations than moving `$releaseDir`.
- [ ] Re: Documenting/using `$releaseDir` as the way to find build outputs rather than hardcoding `target/release` - any sense in bikeshedding this into a less vague name while we're at it? There's nothing cargo/rusty about it and the build may not even be release mode!
- [ ] symlink `$releaseDir` to `$sourceRoot/target/release` to preserve compatibility with existing derivations seems like a good idea y/n?
- [ ] Should `CARGO_TARGET_DIR` and `$releaseDir` be relative to cwd (presumed to be `$sourceRoot`) or an absolute path? I'm not too familiar with stdenv conventions regarding this.

**Comment by Mic92** [comment]
`CARGO_TARGET_DIR` sounds better then relying on `releaseDir` which is nixpkgs specific.

**Comment by arcnmx** [comment]
> CARGO_TARGET_DIR sounds better then relying on releaseDir which is nixpkgs specific

So the thing is we'll presumably need something nixpkgs specific anyway, since the point of `$releaseDir` is to point to where to get outputs; `$CARGO_TARGET_DIR` on the other hand only points to the root under which there's still `$CARGO_TARGET_DIR/${hostPlatform.config}/$buildType` (also hostPlatform.config is subtly incorrect on many platforms) so... some variations:

1. Set up CARGO_TARGET_DIR to be absolute and provide releaseDir as relative to it: `$CARGO_TARGET_DIR/$releaseDir`.
2. Set up CARGO_TARGET_DIR to be absolute but provide releaseDir as relative to pwd/$sourceRoot, so unless you've chdir'd you can just refer to `$releaseDir`
3. Set up both as absolute paths.

(I'm not going to suggest relative `CARGO_TARGET_DIR` because cargo is inconsistent and setting it to anything disables its usual heuristics regarding where to put the path; `"target"` is not the same as it being unset, and things just get messy if derivations chdir...)

I'm still pretty indecisive about the details but just pushed the following:
- CARGO_TARGET_DIR is set via .cargo/config because it seems like a more noncommittal way to go right now, though I don't really have any problem setting it to an absolute path and exposing it to derivations.
- releaseDir is relative to pwd (expected to roughly be sourceRoot)
- `target/release` is symlinked to `$releaseDir`, though all uses of it should be removed from nixpkgs so this is just for backwards compatibility
- set up the cargo and cc-rs env vars for the whole derivation, if we're going to cause rust rebuilds may as well fix the cross compiling environment up a bit.

**Comment by arcnmx** [comment]
Enough has changed in the rust build helpers that this is mostly irrelevant now, closing.

**Pull request closed without merging**
