### PR TITLE
nixd: 1.0.0 -> 1.1.0

### PR DESCRIPTION
**Pull request by Ruixi-rebirth**
###### Description of changes
Diff: https://github.com/nix-community/nixd/compare/1.0.0...1.1.0

Change log: https://github.com/nix-community/nixd/releases/tag/1.1.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Janik-Haag — COMMENTED** [review]
The build fails you probably want to add flex to the inputs.
```
these 2 derivations will be built:
  /nix/store/g39w1lzc1yvmpypvb7k6hqldf6ng1771-source.drv
  /nix/store/wwxf5j6b2n6y7bfbi7dhk3jvagp99pbr-nixd-1.1.0.drv
these 13 paths will be fetched (17.93 MiB download, 186.25 MiB unpacked):
  /nix/store/9dl9q57qi7283rhsxdli56gy002ndw3r-boehm-gc-8.2.2-dev
  /nix/store/bxs5f5brj00hl087zlrgm85i7xxwk69z-boost-1.82.0
  /nix/store/mvxdb33wl69ml2144ksdffzs6aj90gr7-boost-1.82.0-dev
  /nix/store/lm353qz6cvlmlasxpayv04hg0awgh7r3-gtest-1.12.1
  /nix/store/jndg9hp6qvhn5k60jmcxj8mc8dms7in5-gtest-1.12.1-dev
  /nix/store/rgifjnclgzwmv7ykhmdzs7xa6fhlp1as-libbacktrace-unstable-2022-12-16
  /nix/store/ip1y6d8y8b7agfj04yjf8vxs36vxqaa4-lowdown-1.0.2-lib
  /nix/store/4asjr2i4xzc9gncad3w7xdrs34bmg26v-meson-1.1.0
  /nix/store/ld6l8nrsgzz2yc4igdl1j1p9jzz0qcar-nix-2.16.1
  /nix/store/39j3rckh5l1kjgs74xgpqqchsf2dqq3r-nix-2.16.1-dev
  /nix/store/zm00xmq71h1nv3l4flv3kg1yg64q9jdk-nix-2.16.1-man
  /nix/store/7igsav54ghpg4h2vllw2h695mgpx7b6k-nixpkgs-fmt-1.3.0
  /nix/store/b05268ssww9q2kb8z08i7jcqfwhrfnjw-python3.10-lit-15.0.6
copying path '/nix/store/rgifjnclgzwmv7ykhmdzs7xa6fhlp1as-libbacktrace-unstable-2022-12-16' from 'https://cache.nixos.org'...
copying path '/nix/store/zm00xmq71h1nv3l4flv3kg1yg64q9jdk-nix-2.16.1-man' from 'https://cache.nixos.org'...
copying path '/nix/store/4asjr2i4xzc9gncad3w7xdrs34bmg26v-meson-1.1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/7igsav54ghpg4h2vllw2h695mgpx7b6k-nixpkgs-fmt-1.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/b05268ssww9q2kb8z08i7jcqfwhrfnjw-python3.10-lit-15.0.6' from 'https://cache.nixos.org'...
copying path '/nix/store/9dl9q57qi7283rhsxdli56gy002ndw3r-boehm-gc-8.2.2-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/bxs5f5brj00hl087zlrgm85i7xxwk69z-boost-1.82.0' from 'https://cache.nixos.org'...
copying path '/nix/store/lm353qz6cvlmlasxpayv04hg0awgh7r3-gtest-1.12.1' from 'https://cache.nixos.org'...
copying path '/nix/store/ip1y6d8y8b7agfj04yjf8vxs36vxqaa4-lowdown-1.0.2-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/jndg9hp6qvhn5k60jmcxj8mc8dms7in5-gtest-1.12.1-dev' from 'https://cache.nixos.org'...
building '/nix/store/g39w1lzc1yvmpypvb7k6hqldf6ng1771-source.drv'...
copying path '/nix/store/ld6l8nrsgzz2yc4igdl1j1p9jzz0qcar-nix-2.16.1' from 'https://cache.nixos.org'...
copying path '/nix/store/39j3rckh5l1kjgs74xgpqqchsf2dqq3r-nix-2.16.1-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/mvxdb33wl69ml2144ksdffzs6aj90gr7-boost-1.82.0-dev' from 'https://cache.nixos.org'...

trying https://github.com/nix-community/nixd/archive/1.1.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1513k    0 1513k    0     0  2941k      0 --:--:-- --:--:-- --:--:-- 15.1M
unpacking source archive /build/1.1.0.tar.gz
building '/nix/store/wwxf5j6b2n6y7bfbi7dhk3jvagp99pbr-nixd-1.1.0.drv'...
unpacking sources
unpacking source archive /nix/store/xn024694fg0ib0qxd7z7hw4rqas2n1rs-source
source root is source
patching sources
configuring
meson flags: --buildtype=release         --libdir=/nix/store/va23c1w46pg1k9zw9nw2vkqkw13nq0zd-nixd-1.1.0/lib --libexecdir=/nix/store/va23c1w46pg1k9zw9nw2vkqkw13nq0zd-nixd-1.1.0/libexec         --bindir=/nix/store/va23c1w46pg1k9zw9nw2vkqkw13nq0zd-nixd-1.1.0/bin --sbindir=/nix/store/va23c1w46pg1k9zw9nw2vkqkw13nq0zd-nixd-1.1.0/sbin         --includedir=/nix/store/va23c1w46pg1k9zw9nw2vkqkw13nq0zd-nixd-1.1.0/include         --mandir=/nix/store/va23c1w46pg1k9zw9nw2vkqkw13nq0zd-nixd-1.1.0/share/man --infodir=/nix/store/va23c1w46pg1k9zw9nw2vkqkw13nq0zd-nixd-1.1.0/share/info         --localedir=/nix/store/va23c1w46pg1k9zw9nw2vkqkw13nq0zd-nixd-1.1.0/share/locale         -Dauto_features=enabled         -Dwrap_mode=nodownload         --prefix=/nix/store/va23c1w46pg1k9zw9nw2vkqkw13nq0zd-nixd-1.1.0  
The Meson build system
Version: 1.1.0
Source dir: /build/source
Build dir: /build/source/build
Build type: native build
Project name: nixd
Project version: 1.1.0
C compiler for the host machine: gcc (gcc 12.3.0 "gcc (GCC) 12.3.0")
C linker for the host machine: gcc ld.bfd 2.40
C++ compiler for the host machine: g++ (gcc 12.3.0 "g++ (GCC) 12.3.0")
C++ linker for the host machine: g++ ld.bfd 2.40
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program git found: NO
Configuring nixd-config.h using configuration
Found pkg-config: /nix/store/hshdgh469175gqra1jaw1vgl0i9icjdh-pkg-config-wrapper-0.29.2/bin/pkg-config (0.29.2)
Run-time dependency GTest found: YES 1.12.1
Run-time dependency gtest_main found: YES 1.12.1
Did not find CMake 'cmake'
Found CMake: NO
llvm-config found: YES (/nix/store/8q70b24rsnx6k2618w7azxb5f8dbqn6f-llvm-16.0.1-dev/bin/llvm-config) 16.0.1
Run-time dependency LLVM found: YES 16.0.1
Run-time dependency Boost found: YES 1.82.0 (/nix/store/mvxdb33wl69ml2144ksdffzs6aj90gr7-boost-1.82.0-dev)
Library backtrace found: YES
Library nixfetchers found: YES
Run-time dependency nix-expr found: YES 2.16.1
Run-time dependency nix-cmd found: YES 2.16.1
Run-time dependency nix-store found: YES 2.16.1
Run-time dependency nix-main found: YES 2.16.1
Program flex found: NO

lib/nixd/meson.build:3:7: ERROR: Program 'flex' not found or not executable
```

**Review by Janik-Haag — APPROVED** [review]
builds fine now

**Review by inclyc — APPROVED** [review]
Yes, these dependencies were introduced in https://github.com/nix-community/nixd/pull/131

**Comment by qbit** [comment]
Result of `nixpkgs-review pr 238779` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>nixd</li>
  </ul>
</details>

**Review by qbit — APPROVED** [review]

**Comment by qbit** [comment]
Probably the commits should be squashed.

**Comment by Janik-Haag** [comment]
Yes they should be squashed

**Comment by Ruixi-rebirth** [comment]
already squashed

**Review by inclyc — APPROVED** [review]

**Pull request merged**
