### PR TITLE
linuxKernel.kernels.linux_zen: 6.10.1-zen1 -> 6.10.3-zen1 ; linuxKernel.kernels.linux_lqx: 6.9.11-lqx1 -> 6.10.3-lqx1

### PR DESCRIPTION
**Pull request by JerrySM64**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by JerrySM64** [comment]
CC @thiagokokada for review. Since I did this on my Mac, I don't know if the hash is correct. Please let me know if it isn't.

**Comment by thiagokokada** [comment]
> CC @thiagokokada for review. Since I did this on my Mac, I don't know if the hash is correct. Please let me know if it isn't.

The hash seems to be incorrect, see Hydra logs:

```
error: hash mismatch in fixed-output derivation '/nix/store/8m0f1hn28an498kn7xpsv1ijbl5qkk0x-source.drv':
         specified: sha256-maEkQsBwm8WNb/rPpjNnUn1IdbsyML/YtPMoa0JA5ok=
            got:    sha256-Uh19IJq5mTR7gihcd9QMWyS/XOSyvdo9WfxWLikrOUM=
```

**Comment by Faustrox** [comment]
Linux 6.10.4 zen and lqx released https://github.com/zen-kernel/zen-kernel/releases

**Comment by JerrySM64** [comment]
I know. Just have no PC other than my Apple Silicon Mac on hand. My PC is packed up and ready for moving. That's why I hoped that the hash will be good. When everything's done, I'll update the commits to the latest versions available.

**Comment by JerrySM64** [comment]
Since @JohnRTitor already updated it to 6.10.5 there's no point in keeping this still open. Closing.

Again, sorry for being away from that for that long now. I'm trying my best to get everything sorted as quickly as possible.

**Pull request closed without merging**
