### PR TITLE
nix-info: build locally

### PR DESCRIPTION
**Pull request by LnL7**
###### Motivation for this change

/cc @grahamc

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
Hmm... why?

**Comment by LnL7** [comment]
Copying a file locally is faster then copying everything back and forth with build-remote.

**Comment by grahamc** [comment]
Ah makes sense. This won't make any impact on users fetching it from the cache though, right?

**Comment by LnL7** [comment]
No, that would be `allowSubstitutes = false;`.

**Comment by grahamc** [comment]
👍

**Review by vcunat — APPROVED** [review]

**Pull request merged**
