### PR TITLE
onefetch: init at 2.1.0

### PR DESCRIPTION
**Pull request by Br1ght0ne**
###### Motivation for this change

Close #72254

@Kloenk - feel free to add yourself as a maintainer, if you'd like.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @mmahut @jonringer

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/74191)

### CODE REVIEW

**Comment by filalex77** [comment]
@GrahamcOfBorg build onefetch

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM
executable shows usage

```
[4 built, 0.0 MiB DL]
https://github.com/NixOS/nixpkgs/pull/74191
1 package were built:
onefetch
```

**Comment by jonringer** [comment]
@GrahamcOfBorg build onefetch

**Comment by filalex77** [comment]
@jonringer Build on darwin should be fixed now.

@GrahamcOfBorg build onefetch

**Comment by jonringer** [comment]
@GrahamcOfBorg build onefetch

**Comment by filalex77** [comment]
@jonringer I think I added all the needed frameworks and libraries for Darwin now. Could you please run the build again? Sorry to ping you so much; the [PR adding me to trusted users for ofBorg](https://github.com/NixOS/ofborg/pull/422) is not merged yet.

**Comment by jonringer** [comment]
@GrahamcOfBorg build onefetch

**Comment by filalex77** [comment]
@jonringer I think it's fine now - the PR can be merged. Thanks a lot for your help!

**Comment by jonringer** [comment]
previous review still stand, LGTM

**Pull request merged**
