### PR TITLE
ghcjs: Add ghc-8.0 stage2 packages, update shims.

### PR DESCRIPTION
**Pull request by TravisWhitaker**
Adds stage2 packages to ghcjsHEAD.

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by TravisWhitaker** [comment]
I would propose that the `haskell.compiler.ghcjsHEAD` derivation also provide all of these stage 2 packages. Otherwise the resulting compiler isn't that useful; it can't be used with stack or cabal. At the very least it should provide `Cabal` and `ghcjs-base` (but those two will pull in all of stage 2).

Essentially, I'd like to have something like:

```
haskell.compiler.ghcjsHEAD = haskell.packages.ghcjsHEAD.ghcWithPackages (p: [p.Cabal p.ghcjs-base])
```

I'm not sure of the best way to achieve this, though. I'd imagine something in `pkgs/top-level/haskell-packages.nix` would have to be changed?

**Comment by TravisWhitaker** [comment]
@peti @pikajude @Ericson2314 mention-bot didn't kick in, but selected you as reviewers last time.

**Comment by domenkozar** [comment]
@shlevy @copumpkin

**Comment by shlevy** [comment]
I'm confused, why are these different from the normal haskell packages set? Why can't the user just install them from there?

**Comment by Ericson2314** [comment]
You shouldn't need ghcjs-compiled Cabal? Unlike upstream ghcjs, we use normal ghc-compile Cabal. Otherwise seems fine to me.

@shlevy ghcjs has a bunch of patches it applies to these packages, so they don't quite match upstream.

**Comment by shlevy** [comment]
Ah, I see, :+1: then

**Comment by TravisWhitaker** [comment]
@Ericson2314 ghcjs-boot provides its own Cabal (and booting "normally" with ghcjs-boot will provide it).

Any thoughts on having `haskell.compiler.ghcjs` provide the stage 2 packages? I'm not sure of the most idiomatic way of achieving this.

**Comment by Ericson2314** [comment]
Wait what? The whole point of nixifying stage two is to avoid using ghcjs-compiled stage 2—at least that was the point when @cstrahan and I did this.

**Comment by TravisWhitaker** [comment]
@Profpatsch refactored this(thanks for that!). I'll send a new PR.

**Pull request closed without merging**
