### PR TITLE
openbbterminal: init at 2.1.0

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This is a WIP effort to package OpenBBTerminal (and its numerous dependencies).

Some patches in here merely update python libs that are outdated for OpenBBTerminal. I even took some patches from some other PR (cannot remember which one, sorry).

The expression for OpenBBTerminal is quite massive, as there are a lot of packages that are not in nixpkgs yet.
I would like to keep them this way until everything works (which it does not yet, because I am running into some issues I hope someone can have a look at) and split up the dependencies into individual packages later on.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Right now, the issue is that `jupyterlab-code-formatter` does not build. I don't understand why...

**Comment by jiegec** [comment]
Got error running `nixpkgs-fmt`:

```
error: undefined variable 'GitPython'

       at /home/jiegec/.cache/nixpkgs-review/pr-209882/nixpkgs/pkgs/applications/finance/openbbterminal/default.nix:1041:5:

         1040|     FundamentalAnalysis
         1041|     GitPython
             |     ^
         1042|     jinja2
(use '--show-trace' to show detailed location information)
```

**Comment by matthiasbeyer** [comment]
@jonringer @FRidh friendly ping

**Comment by jiegec** [comment]
Please resolve conflicts

**Comment by matthiasbeyer** [comment]
Closing as I don't care enough and this has been open for way too long.

**Pull request closed without merging**
