### PR TITLE
[WIP] python3Packages.setuptools: 47.3.1 -> 49.1.0

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
they just did a new release

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
@GrahamcOfBorg build requests

**Comment by jonringer** [comment]
@GrahamcOfBorg build python3Packages.requests

**Comment by FRidh** [comment]
There are some pretty big changes, especially https://github.com/pypa/setuptools/blob/master/CHANGES.rst#v4800, so this needs more extensive testing.

**Comment by jonringer** [comment]
@FRidh yea, that's fair. I wish python packaging wasn't a constantly shifting hot mess.

**Comment by jonringer** [comment]
Also, they seemed to have disabled the disutils adoptions in 49.1 https://github.com/pypa/setuptools/blob/master/CHANGES.rst#v4910

**Comment by FRidh** [comment]
Well, there is no need to update everything all the time either. I mean, as long as things work and you have the features you need, why bother?

**Comment by jonringer** [comment]
there may be sprinklings of small fixes which don't manifest on changelogs?

**Comment by jonringer** [comment]
either way, I think this can wait, seeing at the current staging version is only a week old

**Comment by jonringer** [comment]
going to close this and wait for setuptools to figure-out what they are doing. https://github.com/pypa/setuptools/blob/v49.2.0/CHANGES.rst

**Pull request closed without merging**
