### PR TITLE
knock: update repo from github to codeberg

### PR DESCRIPTION
**Pull request by nat-418**
Project has moved development from GitHub to Codeberg.

### CODE REVIEW

**Review by aikooo7 — APPROVED** [review]
Lgtm.

**Comment by aikooo7** [comment]
Perhaps this should be put as a ready to merge?

**Comment by nat-418** [comment]
> Perhaps this should be put as a ready to merge?

Done

**Comment by aikooo7** [comment]
> > Perhaps this should be put as a ready to merge?
> 
> Done

Thanks, now you just need to await :)

**Review by marcusramberg — APPROVED** [review]
lgtm

**Review by Aleksanaa — APPROVED** [review]

**Pull request merged**
