### PR TITLE
fmt: 9.1.0 -> 10.0.0

### PR DESCRIPTION
**Pull request by marsam**
###### Description of changes

https://github.com/fmtlib/fmt/releases/tag/10.0.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tobim** [comment]
spdlog has patches upstream: https://github.com/gabime/spdlog/pull/2694 https://github.com/gabime/spdlog/pull/2736

**Review by alyssais — APPROVED** [review]

**Review by babariviere — APPROVED** [review]

**Comment by tobim** [comment]
Result of `nixpkgs-review pr 233330` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>41 packages marked as broken and skipped:</summary>
  <ul>
    <li>lizardfs</li>
    <li>luxcorerender</li>
    <li>mysql-workbench</li>
    <li>python310Packages.qiskit</li>
    <li>python310Packages.qiskit-aer</li>
    <li>python310Packages.qiskit-aer.dist</li>
    <li>python310Packages.qiskit-finance</li>
    <li>python310Packages.qiskit-finance.dist</li>
    <li>python310Packages.qiskit-ibmq-provider</li>
    <li>python310Packages.qiskit-ibmq-provider.dist</li>
    <li>python310Packages.qiskit-ignis</li>
    <li>python310Packages.qiskit-ignis.dist</li>
    <li>python310Packages.qiskit-nature</li>
    <li>python310Packages.qiskit-nature.dist</li>
    <li>python310Packages.qiskit-optimization</li>
    <li>python310Packages.qiskit-optimization.dist</li>
    <li>python310Packages.qiskit.dist</li>
    <li>python310Packages.rlax</li>
    <li>python310Packages.rlax.dist</li>
    <li>python310Packages.tiledb</li>
    <li>python310Packages.tiledb.dist</li>
    <li>python310Packages.worldengine</li>
    <li>python310Packages.worldengine.dist</li>
    <li>python311Packages.qiskit-aer</li>
    <li>python311Packages.qiskit-aer.dist</li>
    <li>python311Packages.qiskit-finance</li>
    <li>python311Packages.qiskit-finance.dist</li>
    <li>python311Packages.qiskit-ibmq-provider</li>
    <li>python311Packages.qiskit-ibmq-provider.dist</li>
    <li>python311Packages.qiskit-ignis</li>
    <li>python311Packages.qiskit-ignis.dist</li>
    <li>python311Packages.qiskit-nature</li>
    <li>python311Packages.qiskit-nature.dist</li>
    <li>python311Packages.qiskit-optimization</li>
    <li>python311Packages.qiskit-optimization.dist</li>
    <li>python311Packages.tiledb</li>
    <li>python311Packages.tiledb.dist</li>
    <li>python311Packages.worldengine</li>
    <li>python311Packages.worldengine.dist</li>
    <li>worldengine-cli</li>
    <li>worldengine-cli.dist</li>
  </ul>
</details>
<details>
  <summary>169 packages failed to build:</summary>
  <ul>
    <li>ananicy-cpp</li>
    <li>apacheHttpdPackages.mod_tile (apacheHttpdPackages_2_4.mod_tile)</li>
    <li>cherrytree</li>
    <li>cloudcompare</li>
    <li>coeurl</li>
    <li>devilutionx</li>
    <li>easyrpg-player</li>
    <li>entwine</li>
    <li>gdal (python310Packages.gdal)</li>
    <li>gerbera</li>
    <li>gmt</li>
    <li>gnss-sdr</li>
    <li>gnuradio</li>
    <li>gnuradioMinimal (gnuradio3_9Minimal)</li>
    <li>gnuradioPackages.gnuradio</li>
    <li>gnuradioPackages.osmosdr</li>
    <li>gnuradioPackages.osmosdr.dev</li>
    <li>gplates</li>
    <li>gqrx</li>
    <li>gqrx-gr-audio</li>
    <li>gqrx-portaudio</li>
    <li>grass</li>
    <li>haskellPackages.hgdal</li>
    <li>haskellPackages.hgdal.doc</li>
    <li>irods</li>
    <li>irods-icommands</li>
    <li>jami</li>
    <li>kodi (kodiPackages.kodi)</li>
    <li>kodi-gbm</li>
    <li>kodi-wayland</li>
    <li>kodiPackages.a4ksubtitles</li>
    <li>kodiPackages.archive_tool</li>
    <li>kodiPackages.iagl</li>
    <li>kodiPackages.inputstream-adaptive</li>
    <li>kodiPackages.inputstream-ffmpegdirect</li>
    <li>kodiPackages.inputstream-rtmp</li>
    <li>kodiPackages.invidious</li>
    <li>kodiPackages.joystick</li>
    <li>kodiPackages.kodi-platform</li>
    <li>kodiPackages.libretro</li>
    <li>kodiPackages.libretro-genplus</li>
    <li>kodiPackages.libretro-mgba</li>
    <li>kodiPackages.libretro-snes9x</li>
    <li>kodiPackages.netflix</li>
    <li>kodiPackages.pvr-hdhomerun</li>
    <li>kodiPackages.pvr-hts</li>
    <li>kodiPackages.pvr-iptvsimple</li>
    <li>kodiPackages.steam-controller</li>
    <li>kodiPackages.vfs-libarchive</li>
    <li>kodiPackages.vfs-sftp</li>
    <li>kodiPackages.visualization-fishbmc</li>
    <li>kodiPackages.visualization-goom</li>
    <li>kodiPackages.visualization-matrix</li>
    <li>kodiPackages.visualization-pictureit</li>
    <li>kodiPackages.visualization-projectm</li>
    <li>kodiPackages.visualization-shadertoy</li>
    <li>kodiPackages.visualization-spectrum</li>
    <li>kodiPackages.visualization-starburst</li>
    <li>kodiPackages.visualization-waveform</li>
    <li>libLAS</li>
    <li>lokinet</li>
    <li>mapcache</li>
    <li>mapnik</li>
    <li>mapproxy</li>
    <li>mapproxy.dist</li>
    <li>mapserver</li>
    <li>merkaartor</li>
    <li>mtxclient</li>
    <li>nheko</li>
    <li>octavePackages.mapping</li>
    <li>openorienteering-mapper</li>
    <li>openroad</li>
    <li>osl</li>
    <li>osm2pgsql</li>
    <li>paraview</li>
    <li>pcsx2</li>
    <li>pdal</li>
    <li>perl534Packages.Tirex</li>
    <li>perl534Packages.Tirex.devdoc</li>
    <li>perl536Packages.Tirex</li>
    <li>perl536Packages.Tirex.devdoc</li>
    <li>postgresql11JitPackages.postgis</li>
    <li>postgresql11JitPackages.postgis.doc</li>
    <li>postgresql11Packages.postgis</li>
    <li>postgresql11Packages.postgis.doc</li>
    <li>postgresql12JitPackages.postgis</li>
    <li>postgresql12JitPackages.postgis.doc</li>
    <li>postgresql12Packages.postgis</li>
    <li>postgresql12Packages.postgis.doc</li>
    <li>postgresql13JitPackages.postgis</li>
    <li>postgresql13JitPackages.postgis.doc</li>
    <li>postgresql13Packages.postgis</li>
    <li>postgresql13Packages.postgis.doc</li>
    <li>postgresqlJitPackages.postgis (postgresql14JitPackages.postgis)</li>
    <li>postgresqlJitPackages.postgis.doc (postgresql14JitPackages.postgis.doc)</li>
    <li>postgresqlPackages.postgis (postgresql14Packages.postgis)</li>
    <li>postgresqlPackages.postgis.doc (postgresql14Packages.postgis.doc)</li>
    <li>postgresql15JitPackages.postgis</li>
    <li>postgresql15JitPackages.postgis.doc</li>
    <li>postgresql15Packages.postgis</li>
    <li>postgresql15Packages.postgis.doc</li>
    <li>python310Packages.bsuite</li>
    <li>python310Packages.bsuite.dist</li>
    <li>python310Packages.cartopy</li>
    <li>python310Packages.cartopy.dist</li>
    <li>python310Packages.django-bootstrap4</li>
    <li>python310Packages.django-bootstrap4.dist</li>
    <li>python310Packages.fiona</li>
    <li>python310Packages.fiona.dist</li>
    <li>python310Packages.folium</li>
    <li>python310Packages.folium.dist</li>
    <li>python310Packages.geopandas</li>
    <li>python310Packages.geopandas.dist</li>
    <li>python310Packages.osmnx</li>
    <li>python310Packages.osmnx.dist</li>
    <li>python310Packages.plotnine</li>
    <li>python310Packages.plotnine.dist</li>
    <li>python310Packages.pygmt</li>
    <li>python310Packages.pygmt.dist</li>
    <li>python310Packages.python-mapnik</li>
    <li>python310Packages.python-mapnik.dist</li>
    <li>python310Packages.rasterio</li>
    <li>python310Packages.rasterio.dist</li>
    <li>python310Packages.wktutils</li>
    <li>python310Packages.wktutils.dist</li>
    <li>python311Packages.bsuite</li>
    <li>python311Packages.bsuite.dist</li>
    <li>python311Packages.cartopy</li>
    <li>python311Packages.cartopy.dist</li>
    <li>python311Packages.django-bootstrap4</li>
    <li>python311Packages.django-bootstrap4.dist</li>
    <li>python311Packages.fiona</li>
    <li>python311Packages.fiona.dist</li>
    <li>python311Packages.folium</li>
    <li>python311Packages.folium.dist</li>
    <li>python311Packages.gdal</li>
    <li>python311Packages.geopandas</li>
    <li>python311Packages.geopandas.dist</li>
    <li>python311Packages.osmnx</li>
    <li>python311Packages.osmnx.dist</li>
    <li>python311Packages.pc-ble-driver-py</li>
    <li>python311Packages.pc-ble-driver-py.dist</li>
    <li>python311Packages.plotnine</li>
    <li>python311Packages.plotnine.dist</li>
    <li>python311Packages.pygmt</li>
    <li>python311Packages.pygmt.dist</li>
    <li>python311Packages.python-mapnik</li>
    <li>python311Packages.python-mapnik.dist</li>
    <li>python311Packages.rasterio</li>
    <li>python311Packages.rasterio.dist</li>
    <li>python311Packages.wktutils</li>
    <li>python311Packages.wktutils.dist</li>
    <li>pytrainer</li>
    <li>pytrainer.dist</li>
    <li>qgis</li>
    <li>qgis-ltr</li>
    <li>qmapshack</li>
    <li>saga</li>
    <li>sumo</li>
    <li>t-rex</li>
    <li>therion</li>
    <li>tiledb</li>
    <li>udig</li>
    <li>vpv</li>
    <li>wasmedge</li>
    <li>waybar</li>
    <li>yuzu-early-access</li>
    <li>yuzu-mainline</li>
    <li>zeroadPackages.zeroad-unwrapped</li>
  </ul>
</details>
<details>
  <summary>97 packages built:</summary>
  <ul>
    <li>adlplug</li>
    <li>aitrack</li>
    <li>bear</li>
    <li>bencode</li>
    <li>blender</li>
    <li>blender-hip</li>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
    <li>cryfs</li>
    <li>d-seams</li>
    <li>embree</li>
    <li>embree2</li>
    <li>ericw-tools</li>
    <li>ericw-tools.doc</li>
    <li>ericw-tools.man</li>
    <li>far2l</li>
    <li>fcitx5</li>
    <li>fcitx5-anthy</li>
    <li>fcitx5-chewing</li>
    <li>fcitx5-chinese-addons</li>
    <li>fcitx5-configtool</li>
    <li>fcitx5-gtk</li>
    <li>fcitx5-hangul</li>
    <li>fcitx5-lua</li>
    <li>fcitx5-m17n</li>
    <li>fcitx5-mozc</li>
    <li>fcitx5-rime</li>
    <li>fcitx5-skk</li>
    <li>fcitx5-skk-qt</li>
    <li>fcitx5-table-extra</li>
    <li>fcitx5-table-other</li>
    <li>fcitx5-unikey</li>
    <li>fcitx5-with-addons</li>
    <li>fmt (fmt_10)</li>
    <li>fmt.dev (fmt_10.dev)</li>
    <li>giada</li>
    <li>hal-hardware-analyzer</li>
    <li>heroic</li>
    <li>hipblas</li>
    <li>hipsolver</li>
    <li>iptsd</li>
    <li>kemai</li>
    <li>kmsxx</li>
    <li>libime</li>
    <li>libsForQt5.fcitx5-qt (plasma5Packages.fcitx5-qt)</li>
    <li>libsForQt5.plasma-vault (plasma5Packages.plasma-vault)</li>
    <li>litecoin</li>
    <li>litecoind</li>
    <li>magma-hip</li>
    <li>mangohud</li>
    <li>mangohud.doc</li>
    <li>mangohud.man</li>
    <li>micromamba</li>
    <li>mkvtoolnix</li>
    <li>mkvtoolnix-cli</li>
    <li>mlterm</li>
    <li>mlterm-wayland</li>
    <li>mpd</li>
    <li>mpd-small</li>
    <li>mpd-small.doc</li>
    <li>mpd.doc</li>
    <li>mpd.man</li>
    <li>mpvScripts.convert</li>
    <li>nrfutil</li>
    <li>nrfutil.dist</li>
    <li>olive-editor</li>
    <li>openimageio</li>
    <li>openimageio.bin</li>
    <li>openimageio.dev</li>
    <li>openimageio.doc</li>
    <li>opnplug</li>
    <li>pc-ble-driver</li>
    <li>poac</li>
    <li>pynitrokey</li>
    <li>pynitrokey.dist</li>
    <li>python310Packages.kmsxx (python311Packages.kmsxx)</li>
    <li>python310Packages.pc-ble-driver-py</li>
    <li>python310Packages.pc-ble-driver-py.dist</li>
    <li>python310Packages.torchWithRocm</li>
    <li>python310Packages.torchWithRocm.dev</li>
    <li>python310Packages.torchWithRocm.dist</li>
    <li>python310Packages.torchWithRocm.lib</li>
    <li>python310Packages.vowpalwabbit</li>
    <li>python310Packages.vowpalwabbit.dist</li>
    <li>python311Packages.vowpalwabbit</li>
    <li>python311Packages.vowpalwabbit.dist</li>
    <li>rocsolver</li>
    <li>spdlog</li>
    <li>spdlog.dev</li>
    <li>spdlog.doc</li>
    <li>torrenttools</li>
    <li>trenchbroom</li>
    <li>ueberzugpp</li>
    <li>vowpal-wabbit</li>
    <li>wdt</li>
    <li>wsysmon</li>
    <li>ytfzf</li>
  </ul>
</details>

**Comment by Janik-Haag** [comment]
This is laying around for around a month now with no further complains and two approvals so I will merge this.

**Comment by vcunat** [comment]
So, as the nixpkgs-review above suggested, this broke lots of packages, apparently most of this diff:
https://hydra.nixos.org/eval/1797060#tabs-now-fail

**Comment by Janik-Haag** [comment]
Uff I'm sorry 😔
I somehow didn't realize that.
I guess I should revert this then?

**Comment by marsam** [comment]
I think we can solve the breakages pinning spdlog to fmt 9 https://github.com/NixOS/nixpkgs/pull/240270

**Comment by chvp** [comment]
I've got another PR to fix a build failure here: https://github.com/NixOS/nixpkgs/pull/240338

**Comment by doronbehar** [comment]
Fix for coeurl (nheko dependency is in https://github.com/NixOS/nixpkgs/pull/240698 ).

**Comment by aacebedo** [comment]
iptsd package is not building too with an error mentioning this.

**Comment by marsam** [comment]
Sorry about that, iptsd should be fixed by https://github.com/NixOS/nixpkgs/pull/241229

**Pull request merged**
