### PR TITLE
crow-translate: 2.8.1 → 2.8.4

### PR DESCRIPTION
**Pull request by sikmir**
###### Motivation for this change
[Changelog](https://github.com/crow-translate/crow-translate/releases)

###### Things done
- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 125137` at d691ecca run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>crow-translate</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/applications/misc/crow-translate/default.nix:65:5:
```
   |
65 |     (substituteAll {
   |     ^
```
</li>
  </ul>
</details>

**Comment by Mic92** [comment]
Looks like it is still missing icons. I guess this is working for you? https://dl.thalheim.io/UJ9i6H4IrSEG_ef3lBuuQQ/2021-06-01_07-20.png

**Comment by sikmir** [comment]
> Looks like it is still missing icons. I guess this is working for you? https://dl.thalheim.io/UJ9i6H4IrSEG_ef3lBuuQQ/2021-06-01_07-20.png

Yes, icons are still missing, related issue https://github.com/crow-translate/crow-translate/issues/198.

**Comment by Shatur** [comment]
@sikmir, the issue with your `qt5ct` configuration that overrides icon theme. You should specify icons in `qt5ct` explicitly if you using it.

**Comment by sikmir** [comment]
> @sikmir, the issue with your `qt5ct` configuration that overrides icon theme. You should specify icons in `qt5ct` explicitly if you using it.

But why there is no fallback to bundled icons when QT_QPA_PLATFORMTHEME is empty?

**Comment by Shatur** [comment]
> But why there is no fallback to bundled icons when QT_QPA_PLATFORMTHEME is empty?

This is how Qt theming works.

**Pull request merged**
