### PR TITLE
swipl: 8.1.4 -> 8.1.13

### PR DESCRIPTION
**Pull request by yrashk**
8.1.4 can no longer download SWI-Prolog packages (pack_list,
pack_install, etc), rendering it much less useful.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @meditans

### CODE REVIEW

**Comment by zimbatm** [comment]
nix-review:
```
3 package failed to build:
ape apeClex pakcs
```

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS (ape broken on master)
diff LGTM
executables seem to work

```
[2 built (3 failed), 23 copied (175.6 MiB), 17.3 MiB DL]
error: build of '/nix/store/ks9j08siamrhmgdvdmwvdhkhwssxn9wk-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/68675
3 package failed to build:
ape apeClex pakcs

1 package were build:
swiProlog
```

EDIT: this does cause a regession in pakcs though

**Comment by yrashk** [comment]
@jonringer I updated pakcs to 2.1.2 -- this seem to have helped.

**Comment by yrashk** [comment]
Superseded by #70720

**Pull request closed without merging**
