### PR TITLE
libttng-ust: create compatibility symlink for powershell

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

powershell expects a .so.0 library file. 

Cc: @alyssais

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
Presumably the library number was bumped for a reason i.e. backwards
incompatibility?  Is upstream working on this?

**Comment by peterhoeg** [comment]
> Presumably the library number was bumped for a reason i.e. backwards
> incompatibility?

One would think so, but powershell at least works fine with this hack in place.

**Comment by alyssais** [comment]
Can this be fixed in powershell instead?

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by p3psi-boo** [comment]
> 
> 
> Can this be fixed in powershell instead?

Yes

```diff
diff --git a/pkgs/shells/powershell/default.nix b/pkgs/shells/powershell/default.nix
index 5c082641e9f24..15ca1b2d910cb 100644
--- a/pkgs/shells/powershell/default.nix
+++ b/pkgs/shells/powershell/default.nix
@@ -15,7 +15,7 @@ let archString = if stdenv.isAarch64 then "arm64"
                      else if stdenv.isLinux then "LD_LIBRARY_PATH"
                      else throw "unsupported platform";
                      libraries = [ libunwind libuuid icu curl openssl_1_1 ] ++
-                       (if stdenv.isLinux then [ pam lttng-ust ] else [ darwin.Libsystem ]);
+                       (if stdenv.isLinux then [ pam ] else [ darwin.Libsystem ]);
 in
 stdenv.mkDerivation rec {
   pname = "powershell";
@@ -34,6 +34,9 @@ stdenv.mkDerivation rec {
   let
     ext = stdenv.hostPlatform.extensions.sharedLibrary;
   in ''
+    mkdir -p $out/lib
+    ln -s ${lttng-ust}/lib/liblttng-ust.so.1 $out/lib/liblttng-ust.so.0
+
     pslibs=$out/share/powershell
     mkdir -p $pslibs
 
@@ -69,7 +72,7 @@ stdenv.mkDerivation rec {
   meta = with lib; {
     description = "Powerful cross-platform (Windows, Linux, and macOS) shell and scripting language based on .NET";
     homepage = "https://github.com/PowerShell/PowerShell";
-    maintainers = with maintainers; [ yrashk srgom ];
+    maintainers = with maintainers; [ yrashk srgom p3psi ];
     platforms = [ "x86_64-darwin" "x86_64-linux" "aarch64-linux"];
     license = with licenses; [ mit ];
   };
```

https://github.com/p3psi-boo/nixpkgs/commit/549311a6d19ea2e0a0572169f7637d93673467eb

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/138299#event-5376620766

**Pull request closed without merging**
