### PR TITLE
mate updates and downgrades

### LINKED ISSUE #53758: mozo (menu editor) does not work in MATE
## Issue description

```
Traceback (most recent call last):
  File "/nix/store/rz5acy470hvp9pp8wyl0hgmyqrmrfzra-mozo-1.20.1/bin/.mozo-wrapped", line 23, in <module>
    from Mozo.MainWindow import MainWindow
  File "/nix/store/rz5acy470hvp9pp8wyl0hgmyqrmrfzra-mozo-1.20.1/lib/python2.7/site-packages/Mozo/MainWindow.py", line 19, in <module>
    import matemenu
ImportError: No module named matemenu
```

### Steps to reproduce

Install `mozo` and try to run it.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.13, NixOS, 19.03.git.acd2756 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(shane): `""`
 - channels(root): `"nixos-19.03pre165037.eebd1a92637"`
 - nixpkgs: `/pkgs/nixpkgs`

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
Sometime last july r-ryantm sent prs to update mate to its unstable release.
Unfortunately those got merged and it went under the radar.
I noticed this in https://github.com/NixOS/nixpkgs/pull/50695

To prevent this from happening again the `mate` attribute has been blacklisted for [nixpkgs-update](https://github.com/ryantm/nixpkgs-update/commit/102a469d94b5b4efcfa7768b191ebcf2322c94f8).

This should undo that and also update other applications to their latest stable release.

Fixes #53758 #53836

cc @romildo @lheckemann 
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
cc @johannesloetzsch

**Comment by worldofpeace** [comment]
So I've cleaned some things up and got `mozo` to function.

Also tested execution of pretty much everything in a vm with mate enabled.

**Comment by worldofpeace** [comment]
@Mic92 since this has left stable in a pretty poor shape, do you think we should backport this?

**Comment by lheckemann** [comment]
Yes, I'm in favour of backporting.

**Comment by Mic92** [comment]
@worldofpeace ok from my side.

**Comment by worldofpeace** [comment]
> EDIT: Does user config remain compatible if you run 1.21? If it does some sort of schema upgrades that make a downgrade impossible that would be a pain…

This was a thought that I was also having.
I'm not sure where I can look to see if this would be a problem, but the best I could do is simulate this upgrade from within a vm and see if we have problems.

**Comment by worldofpeace** [comment]
Though to begin a backport pr this needs to be merged first :smile:

Just need approval for f9b8f2cf4fecfa8f6a99e6365d435c8c81f783fb...e26d22c091f187d9551d658bc9398e0de02cec7f

**Comment by RedL0tus** [comment]
Any updates on this? I'm currently using MATE and it seems MATE 1.21 isn't fully compatible with themes like arc or materia, downgrading to 1.20 would be great!

**Comment by worldofpeace** [comment]
> Any updates on this? I'm currently using MATE and it seems MATE 1.21 isn't fully compatible with themes like arc or materia, downgrading to 1.20 would be great!

I just need a review for those range of commits, @jtojnar mind giving them a look?

**Comment by jtojnar** [comment]
That looks fine to me.

**Comment by worldofpeace** [comment]
> That looks fine to me.

Great, as I've already tested this in a vm and determined I looked good, I'm going for it :smile:

**Comment by worldofpeace** [comment]
I'm going to assemble the backport now.

**Comment by RedL0tus** [comment]
Thanks a lot!

**Pull request merged**
