### PR TITLE
texlive: add schemes "with docs"

### PR DESCRIPTION
**Pull request by xworld21**
## Description of changes
Build additional variants of each texlive scheme with the documentation included.

This is the final test that we can actually include all the documents, without clashes, and it adds the doc containers to the binary cache (implicitly verifying that those fixed hashes are correct too).

## Things done
- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by apfelkuchen6 — COMMENTED** [review]
We definitely need something like this to resolve binary cache problem for the doc-containers, but I'm not really a huge fan of this approach of adding more pre-combined environments.

I'd prefer including the docs by default and making the interface for removing them less clunky (maybe something like `texlive.combined.scheme-medium.override { withDocs = false; }`, similar to most other derivations in nixpkgs). But this should probably wait until combining becomes essentially free with the format containers.

**Comment by xworld21** [comment]
> I'd prefer including the docs by default and making the interface for removing them less clunky

That seems excessive: the docs of scheme-full are huge and some packages have texlive as build time dependency, so we'd have to add overrides everywhere.

In the meanwhile, an alternative could be to ship `scheme-full-with-docs` only... ? I can't think of another way to get the binary cache at the moment. (I suppose we agree that we don't care about the source containers.)

**Comment by xworld21** [comment]
Progress re building formats in a separate container and on `texlive.withPackages` is going faster than expected – better pause this PR until we can add docs at no cost.

**Comment by xworld21** [comment]
At last, the texdoc containers are in the binary cache and the formats do not need recompiling, so this PR is now 100% irrelevant.

**Pull request closed without merging**
