### PR TITLE
cudnn_cudatoolkit_11_0: 8.1.0 -> 8.1.1

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

Changelog:

https://docs.nvidia.com/deeplearning/cudnn/release-notes/rel_8.html#rel-811

Also change the builder to accept the `hash` argument for SRI hashes.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Comment by SuperSandro2000** [comment]
You are sure the lib directory should be 2.8 GB?

```
tree -l results/cudnn_cudatoolkit_11/lib
dr-xr-xr-x root root 6.6 GB Thu Jan  1 01:00:01 1970  lib
├── .r-xr-xr-x root root 181 KB Thu Jan  1 01:00:01 1970  libcudnn.so
├── .r-xr-xr-x root root 181 KB Thu Jan  1 01:00:01 1970  libcudnn.so.8
├── .r-xr-xr-x root root 181 KB Thu Jan  1 01:00:01 1970  libcudnn.so.8.1.1
├── .r-xr-xr-x root root 122 MB Thu Jan  1 01:00:01 1970  libcudnn_adv_infer.so
├── .r-xr-xr-x root root 122 MB Thu Jan  1 01:00:01 1970  libcudnn_adv_infer.so.8
├── .r-xr-xr-x root root 122 MB Thu Jan  1 01:00:01 1970  libcudnn_adv_infer.so.8.1.1
├── .r-xr-xr-x root root  79 MB Thu Jan  1 01:00:01 1970  libcudnn_adv_train.so
├── .r-xr-xr-x root root  79 MB Thu Jan  1 01:00:01 1970  libcudnn_adv_train.so.8
├── .r-xr-xr-x root root  79 MB Thu Jan  1 01:00:01 1970  libcudnn_adv_train.so.8.1.1
├── .r-xr-xr-x root root 699 MB Thu Jan  1 01:00:01 1970  libcudnn_cnn_infer.so
├── .r-xr-xr-x root root 699 MB Thu Jan  1 01:00:01 1970  libcudnn_cnn_infer.so.8
├── .r-xr-xr-x root root 699 MB Thu Jan  1 01:00:01 1970  libcudnn_cnn_infer.so.8.1.1
├── .r-xr-xr-x root root  95 MB Thu Jan  1 01:00:01 1970  libcudnn_cnn_train.so
├── .r-xr-xr-x root root  95 MB Thu Jan  1 01:00:01 1970  libcudnn_cnn_train.so.8
├── .r-xr-xr-x root root  95 MB Thu Jan  1 01:00:01 1970  libcudnn_cnn_train.so.8.1.1
├── .r-xr-xr-x root root 271 MB Thu Jan  1 01:00:01 1970  libcudnn_ops_infer.so
├── .r-xr-xr-x root root 271 MB Thu Jan  1 01:00:01 1970  libcudnn_ops_infer.so.8
├── .r-xr-xr-x root root 271 MB Thu Jan  1 01:00:01 1970  libcudnn_ops_infer.so.8.1.1
├── .r-xr-xr-x root root  44 MB Thu Jan  1 01:00:01 1970  libcudnn_ops_train.so
├── .r-xr-xr-x root root  44 MB Thu Jan  1 01:00:01 1970  libcudnn_ops_train.so.8
├── .r-xr-xr-x root root  44 MB Thu Jan  1 01:00:01 1970  libcudnn_ops_train.so.8.1.1
├── .r--r--r-- root root 1.4 GB Thu Jan  1 01:00:01 1970  libcudnn_static.a
└── .r--r--r-- root root 1.4 GB Thu Jan  1 01:00:01 1970  libcudnn_static_v8.a
```

**Comment by danieldk** [comment]
> You are sure the lib directory should be 2.8 GB?

They seem to be including CuDNN now, which is great! But something seems to have gone wrong there with symbolic links. I wil have a look tonight. In the meanwhile, I'll put this into draft to avoid that it gets merged.

**Comment by SuperSandro2000** [comment]
> But something seems to have gone wrong there with symbolic links.

I think ``lsd --tree`` counts the symlinks together which means the 6.6GB is definitely wrong but the 2.3GB is counted with du which is correct.

**Comment by danieldk** [comment]
> > But something seems to have gone wrong there with symbolic links.
> 
> I think `lsd --tree` counts the symlinks together which means the 6.6GB is definitely wrong but the 2.3GB is counted with du which is correct.

Then it is kinda expected. CUDA is very big and now they added CuDNN as well (interestingly not in the release notes). I could, however, look if we can remove the static CuDNN library, but I'll have to do some test builds.

**Comment by danieldk** [comment]
Reopening this PR, since everything looks fine. People who do not want the large static library can use the existing `removeStatic` option.

**Pull request merged**
