### PR TITLE
keybase-gui: update to 6.2.4

### PR DESCRIPTION
**Pull request by stuzenz**
## Description of changes

Manila update of the 6.2.2 version of keybase-gui to 6.2.4 to fix the issues with the keybase upstream pkg of broken certificates. 

Reference to upstream change log: https://github.com/keybase/client/releases

## Things done

- Updated version, version-suffix and associated hash
- Tested locally as an overlay

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by eyeinsky** [comment]
Hi, I had a PR updating `keybase-gui` here: https://github.com/NixOS/nixpkgs/pull/278346, did the hash value from there fail?

The actual fix for certificates happened with update to the (plain) `keybase` package here: https://github.com/NixOS/nixpkgs/pull/278033

**Comment by stuzenz** [comment]
> Hi, I had a PR updating `keybase-gui` here: #278346, did the hash value from there fail?
> 
> The actual fix for certificates happened with update to the (plain) `keybase` package here: #278033

From what I can read from your link, it is building 2 packages `kbfs` and `keybase` - the pull request I have done is for the client `keybase-gui` which has the issues noted for the certificates. As you might be aware, it has been an issue for all the clients from Android, MacOS, Windows ... and Linux. Now fixed upstream, but not reflected to the same version in our NixOS pkgs repo.

**Comment by eyeinsky** [comment]
The links above update both `keybase`/`kbfs` https://github.com/NixOS/nixpkgs/pull/278033 and `keybase-gui` https://github.com/NixOS/nixpkgs/pull/278346. It was only the former that fixed the certificate issue, `keybase-gui` I just updated because it wasn't up to date.

If in current master you do `nix-build . -A keybase-gui`, do you get an error still?

**Comment by stuzenz** [comment]
Hi Markus, you were right - I accidentally traced back from nixos.org and was looking at 23.11 branch - not master. I will close this request.

Thanks! 

I will take a bit more care next time - it was my first time trying to contribute back to nix pkgs.

**Comment by stuzenz** [comment]
Markus (@eyeinsky ) had already upgraded the version for the package. I was accidentally referencing 23.11 not master when checking things for updates. 

This pull request was completely superfluous. Thanks!

**Pull request closed without merging**
