### PR TITLE
darktable: 4.6.1 -> 4.8.0

### PR DESCRIPTION
**Pull request by paperdigits**
## Description of changes
Update darktable to the latest.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by paperdigits** [comment]
@ofBorg build darktable

**Review by freyacodes — COMMENTED** [review]
Ever since I started running this version, my config directory seems to be corrupted in such a way that darktable does not render images (except some thumbnails). This persisted with a downgrade to 4.6.1 (and a restore of library.db). This is both the case with and without OpenCL. This renders darktable unusable. 

I am unable to reproduce the issue with a fresh darktable config dir. Darktable seems to work fine under default configuration.

I am wondering if anyone else is experiencing such an issue? I will try to put together a proper bug report for the upstream once I have the time.

**Comment by paperdigits** [comment]
I upgraded yesterday and did some light editing, and it seemed fine to me, with OpenCL and the nvidia proprietary driver.

**Comment by paperdigits** [comment]
@freyacodes there have been a lot of changes in the last two version to openCL and thumbnail generation. 

If you suspect something with library.db, you can try and do a few things with sqlite like vacuum. 

You can also blow away the cached thumbnails and let the regenerate, same for the openCL kernels. 

Finally you can diff you nonworking darktablerc vs a fresh one and see what's changed between the two.

**Review by hraban — APPROVED** [review]

**Review by RossComputerGuy — APPROVED** [review]
Result of `nixpkgs-review` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>darktable</li>
    <li>photoprism</li>
  </ul>
</details>

**Pull request merged**
