### PR TITLE
electrum: 4.0.9 -> 4.1.1

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

- Electrum version update - https://github.com/spesmilo/electrum/blob/master/RELEASE-NOTES

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
@GrahamcOfBorg build electrum

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 118363` at 6a5279f7 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package skipped due to time constraints:</summary>
  <ul>
    <li>electrum</li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.aiorpcx</li>
    <li>python39Packages.aiorpcx</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/aiorpcx/default.nix:20:3:
```
   |
20 |   meta = {
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-include-tests.md">python-include-tests</a>

Consider adding a `checkPhase` for tests, or if not feasible, `pythonImportsCheck`.

Near pkgs/development/python-modules/aiorpcx/default.nix:21:0:
```
   |
21 |     description = "Transport, protocol and framing-independent async RPC client and server implementation";
   | ^
```
</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
@prusnak can you take a look at the bot suggestions? It would be great if we could apply them.

**Comment by emmanuelrosa** [comment]
I confirm that this works on NixOS.

Thank you, @prusnak

**Pull request merged**
