### PR TITLE
perlPackages.Mail-Sendmail: init at 0.80

### PR DESCRIPTION
**Pull request by limeytexan**
###### Motivation for this change
Add Mail::Sendmail module from CPAN.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build perlPackages.Mail-Sendmail

**Comment by Mic92** [comment]
@GrahamcOfBorg build perlPackages.MailSendmail

**Comment by Mic92** [comment]
The error is related to Socket: http://cpansearch.perl.org/src/PEVANS/Socket-2.027/t/getaddrinfo.t
a dependency of this module. Looks like it only fails in nix build sandbox. Also I am surprised why it needs DNS to resolve `127.0.0.1`. The lazy patch would be to just remove `t/getaddrinfo.t` and call it a day.

**Comment by Mic92** [comment]
I fixed perlPackages.Socket here: fd0a32e510dbd3a15de22b0c3f82e11ad2fab28e

**Comment by Mic92** [comment]
@GrahamcOfBorg build perlPackages.MailSendmail

**Comment by limeytexan** [comment]
Many thanks!

**Comment by limeytexan** [comment]
Hi,

I am a new to nixpkgs and curious about how PRs are scheduled for
processing. The first batch of PRs that I submitted went very quickly, but
I've got two PRs that now seem to be stuck - do you have any advice on how
to un-stick them?

   - https://github.com/NixOS/nixpkgs/pull/36379 - a very similar patch to
   perlPackages.Socket to the one that you did, simply removes another test
   that fails in a sandbox because of network reasons
   - https://github.com/NixOS/nixpkgs/pull/36117 - my perlPackages.POE
   patch that replaces my previous PR
   <https://github.com/NixOS/nixpkgs/pull/35218> which tried to add support
   for multiple modules at once

Many thanks!
--
- Michael

**Pull request merged**
