### PR TITLE
[21.11] python39: 3.9.6  -> 3.9.11; python310: 3.10.0 -> 3.10.3

### PR DESCRIPTION
**Pull request by mweinelt**
Backport of https://github.com/NixOS/nixpkgs/pull/164473.

I'm not sure when we move python interpreters in and out of the `sources` attrset, so we might need to correct some of these changes for 21.11.

### CODE REVIEW

**Comment by mweinelt** [comment]
```
==================================== ERRORS ====================================
__________________ ERROR collecting ast3/tests/test_basics.py __________________
ImportError while importing test module '/build/source/ast3/tests/test_basics.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/nix/store/n35ldca6pxnil9khwlpnvr31k2n6p2dg-python3-3.9.11/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ast3/tests/test_basics.py:5: in <module>
    from typed_ast import _ast3
E   ImportError: /nix/store/ajmw2ql63hc9bdzmbx8930xg1jsiaqhf-python3.9-typed-ast-1.4.3/lib/python3.9/site-packages/typed_ast/_ast3.cpython-39-x86_64-linux-gnu.so: undefined symbol: _PyUnicode_DecodeUnicodeEscape
=========================== short test summary info ============================
ERROR ast3/tests/test_basics.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.22s ===============================
```

**Comment by mweinelt** [comment]
Pandas is failing a single test

```pytb
=================================== FAILURES ===================================
___ test_bad_quote_char[python-kwargs2-"quotechar" must be string, not int] ____

all_parsers = <pandas.tests.io.parser.conftest.PythonParser object at 0x7ffdd7d98250>
kwargs = {'quotechar': 2}, msg = '"quotechar" must be string, not int'

    @pytest.mark.parametrize(
        "kwargs,msg",
        [
            ({"quotechar": "foo"}, '"quotechar" must be a(n)? 1-character string'),
            (
                {"quotechar": None, "quoting": csv.QUOTE_MINIMAL},
                "quotechar must be set if quoting enabled",
            ),
            ({"quotechar": 2}, '"quotechar" must be string, not int'),
        ],
    )
    def test_bad_quote_char(all_parsers, kwargs, msg):
        data = "1,2,3"
        parser = all_parsers
    
        with pytest.raises(TypeError, match=msg):
>           parser.read_csv(StringIO(data), **kwargs)

tests/io/parser/test_quoting.py:33: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pandas.tests.io.parser.conftest.PythonParser object at 0x7ffdd7d98250>
args = (<_io.StringIO object at 0x7ffd5e91cdc0>,)
kwargs = {'engine': 'python', 'low_memory': True, 'quotechar': 2}

    def read_csv(self, *args, **kwargs):
        kwargs = self.update_kwargs(kwargs)
>       return read_csv(*args, **kwargs)

tests/io/parser/conftest.py:26: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = (<_io.StringIO object at 0x7ffd5e91cdc0>,)
kwargs = {'engine': 'python', 'low_memory': True, 'quotechar': 2}
arguments = " except for the argument 'filepath_or_buffer'"

    @wraps(func)
    def wrapper(*args, **kwargs):
        arguments = _format_argument_list(allow_args)
        if len(args) > num_allow_args:
            warnings.warn(
                msg.format(arguments=arguments),
                FutureWarning,
                stacklevel=stacklevel,
            )
>       return func(*args, **kwargs)

util/_decorators.py:311: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

filepath_or_buffer = <_io.StringIO object at 0x7ffd5e91cdc0>, sep = <no_default>
delimiter = None, header = 'infer', names = <no_default>, index_col = None
usecols = None, squeeze = False, prefix = <no_default>, mangle_dupe_cols = True
dtype = None, engine = 'python', converters = None, true_values = None
false_values = None, skipinitialspace = False, skiprows = None, skipfooter = 0
nrows = None, na_values = None, keep_default_na = True, na_filter = True
verbose = False, skip_blank_lines = True, parse_dates = False
infer_datetime_format = False, keep_date_col = False, date_parser = None
dayfirst = False, cache_dates = True, iterator = False, chunksize = None
compression = 'infer', thousands = None, decimal = '.', lineterminator = None
quotechar = 2, quoting = 0, doublequote = True, escapechar = None
comment = None, encoding = None, encoding_errors = 'strict', dialect = None
error_bad_lines = None, warn_bad_lines = None, on_bad_lines = None
delim_whitespace = False, low_memory = True, memory_map = False
float_precision = None, storage_options = None

    @deprecate_nonkeyword_arguments(
        version=None, allowed_args=["filepath_or_buffer"], stacklevel=3
    )
    @Appender(
        _doc_read_csv_and_table.format(
            func_name="read_csv",
            summary="Read a comma-separated values (csv) file into DataFrame.",
            _default_sep="','",
            storage_options=generic._shared_docs["storage_options"],
        )
    )
    def read_csv(
        filepath_or_buffer: FilePathOrBuffer,
        sep=lib.no_default,
        delimiter=None,
        # Column and Index Locations and Names
        header="infer",
        names=lib.no_default,
        index_col=None,
        usecols=None,
        squeeze=False,
        prefix=lib.no_default,
        mangle_dupe_cols=True,
        # General Parsing Configuration
        dtype: DtypeArg | None = None,
        engine=None,
        converters=None,
        true_values=None,
        false_values=None,
        skipinitialspace=False,
        skiprows=None,
        skipfooter=0,
        nrows=None,
        # NA and Missing Data Handling
        na_values=None,
        keep_default_na=True,
        na_filter=True,
        verbose=False,
        skip_blank_lines=True,
        # Datetime Handling
        parse_dates=False,
        infer_datetime_format=False,
        keep_date_col=False,
        date_parser=None,
        dayfirst=False,
        cache_dates=True,
        # Iteration
        iterator=False,
        chunksize=None,
        # Quoting, Compression, and File Format
        compression="infer",
        thousands=None,
        decimal: str = ".",
        lineterminator=None,
        quotechar='"',
        quoting=csv.QUOTE_MINIMAL,
        doublequote=True,
        escapechar=None,
        comment=None,
        encoding=None,
        encoding_errors: str | None = "strict",
        dialect=None,
        # Error Handling
        error_bad_lines=None,
        warn_bad_lines=None,
        # TODO (2.0): set on_bad_lines to "error".
        # See _refine_defaults_read comment for why we do this.
        on_bad_lines=None,
        # Internal
        delim_whitespace=False,
        low_memory=_c_parser_defaults["low_memory"],
        memory_map=False,
        float_precision=None,
        storage_options: StorageOptions = None,
    ):
        # locals() should never be modified
        kwds = locals().copy()
        del kwds["filepath_or_buffer"]
        del kwds["sep"]
    
        kwds_defaults = _refine_defaults_read(
            dialect,
            delimiter,
            delim_whitespace,
            engine,
            sep,
            error_bad_lines,
            warn_bad_lines,
            on_bad_lines,
            names,
            prefix,
            defaults={"delimiter": ","},
        )
        kwds.update(kwds_defaults)
    
>       return _read(filepath_or_buffer, kwds)

io/parsers/readers.py:586: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

filepath_or_buffer = <_io.StringIO object at 0x7ffd5e91cdc0>
kwds = {'cache_dates': True, 'chunksize': None, 'comment': None, 'compression': 'infer', ...}

    def _read(filepath_or_buffer: FilePathOrBuffer, kwds):
        """Generic reader of line files."""
        if kwds.get("date_parser", None) is not None:
            if isinstance(kwds["parse_dates"], bool):
                kwds["parse_dates"] = True
    
        # Extract some of the arguments (pass chunksize on).
        iterator = kwds.get("iterator", False)
        chunksize = validate_integer("chunksize", kwds.get("chunksize", None), 1)
        nrows = kwds.get("nrows", None)
    
        # Check for duplicates in names.
        _validate_names(kwds.get("names", None))
    
        # Create the parser.
>       parser = TextFileReader(filepath_or_buffer, **kwds)

io/parsers/readers.py:482: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pandas.io.parsers.readers.TextFileReader object at 0x7ffd5e991370>
f = <_io.StringIO object at 0x7ffd5e91cdc0>, engine = 'python'
kwds = {'cache_dates': True, 'chunksize': None, 'comment': None, 'compression': 'infer', ...}
engine_specified = True, dialect = None
options = {'cache_dates': True, 'comment': None, 'compression': 'infer', 'converters': None, ...}

    def __init__(self, f, engine=None, **kwds):
    
        self.f = f
    
        if engine is not None:
            engine_specified = True
        else:
            engine = "python"
            engine_specified = False
        self.engine = engine
        self._engine_specified = kwds.get("engine_specified", engine_specified)
    
        _validate_skipfooter(kwds)
    
        dialect = _extract_dialect(kwds)
        if dialect is not None:
            kwds = _merge_with_dialect_properties(dialect, kwds)
    
        if kwds.get("header", "infer") == "infer":
            kwds["header"] = 0 if kwds.get("names") is None else None
    
        self.orig_options = kwds
    
        # miscellanea
        self._currow = 0
    
        options = self._get_options_with_defaults(engine)
        options["storage_options"] = kwds.get("storage_options", None)
    
        self.chunksize = options.pop("chunksize", None)
        self.nrows = options.pop("nrows", None)
        self.squeeze = options.pop("squeeze", False)
    
        self._check_file_or_buffer(f, engine)
        self.options, self.engine = self._clean_options(options, engine)
    
        if "has_index_names" in kwds:
            self.options["has_index_names"] = kwds["has_index_names"]
    
>       self._engine = self._make_engine(self.engine)

io/parsers/readers.py:811: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pandas.io.parsers.readers.TextFileReader object at 0x7ffd5e991370>
engine = 'python'

    def _make_engine(self, engine="c"):
        mapping: dict[str, type[ParserBase]] = {
            "c": CParserWrapper,
            "python": PythonParser,
            "python-fwf": FixedWidthFieldParser,
        }
        if engine not in mapping:
            raise ValueError(
                f"Unknown engine: {engine} (valid options are {mapping.keys()})"
            )
        # error: Too many arguments for "ParserBase"
>       return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]

io/parsers/readers.py:1040: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pandas.io.parsers.python_parser.PythonParser object at 0x7ffd5e991160>
f = <_io.StringIO object at 0x7ffd5e91cdc0>
kwds = {'comment': None, 'compression': 'infer', 'converters': {}, 'decimal': '.', ...}

    def __init__(self, f: FilePathOrBuffer | list, **kwds):
        """
        Workhorse function for processing nested list into DataFrame
        """
        ParserBase.__init__(self, kwds)
    
        self.data: Iterator[str] | None = None
        self.buf: list = []
        self.pos = 0
        self.line_pos = 0
    
        self.skiprows = kwds["skiprows"]
    
        if callable(self.skiprows):
            self.skipfunc = self.skiprows
        else:
            self.skipfunc = lambda x: x in self.skiprows
    
        self.skipfooter = _validate_skipfooter_arg(kwds["skipfooter"])
        self.delimiter = kwds["delimiter"]
    
        self.quotechar = kwds["quotechar"]
        if isinstance(self.quotechar, str):
            self.quotechar = str(self.quotechar)
    
        self.escapechar = kwds["escapechar"]
        self.doublequote = kwds["doublequote"]
        self.skipinitialspace = kwds["skipinitialspace"]
        self.lineterminator = kwds["lineterminator"]
        self.quoting = kwds["quoting"]
        self.skip_blank_lines = kwds["skip_blank_lines"]
    
        self.names_passed = kwds["names"] or None
    
        self.has_index_names = False
        if "has_index_names" in kwds:
            self.has_index_names = kwds["has_index_names"]
    
        self.verbose = kwds["verbose"]
        self.converters = kwds["converters"]
    
        self.dtype = copy(kwds["dtype"])
        self.thousands = kwds["thousands"]
        self.decimal = kwds["decimal"]
    
        self.comment = kwds["comment"]
    
        # Set self.data to something that can read lines.
        if isinstance(f, list):
            # read_excel: f is a list
            self.data = cast(Iterator[str], f)
        else:
            self._open_handles(f, kwds)
            assert self.handles is not None
            assert hasattr(self.handles.handle, "readline")
            try:
>               self._make_reader(self.handles.handle)

io/parsers/python_parser.py:100: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pandas.io.parsers.python_parser.PythonParser object at 0x7ffd5e991160>
f = <_io.StringIO object at 0x7ffd5e91cdc0>

    def _make_reader(self, f):
        sep = self.delimiter
    
        if sep is None or len(sep) == 1:
            if self.lineterminator:
                raise ValueError(
                    "Custom line terminators not supported in python parser (yet)"
                )
    
            class MyDialect(csv.Dialect):
                delimiter = self.delimiter
                quotechar = self.quotechar
                escapechar = self.escapechar
                doublequote = self.doublequote
                skipinitialspace = self.skipinitialspace
                quoting = self.quoting
                lineterminator = "\n"
    
            dia = MyDialect
    
            if sep is not None:
                dia.delimiter = sep
            else:
                # attempt to sniff the delimiter from the first valid line,
                # i.e. no comment line and not in skiprows
                line = f.readline()
                lines = self._check_comments([[line]])[0]
                while self.skipfunc(self.pos) or not lines:
                    self.pos += 1
                    line = f.readline()
                    lines = self._check_comments([[line]])[0]
    
                # since `line` was a string, lines will be a list containing
                # only a single string
                line = lines[0]
    
                self.pos += 1
                self.line_pos += 1
                sniffed = csv.Sniffer().sniff(line)
                dia.delimiter = sniffed.delimiter
    
                # Note: encoding is irrelevant here
                line_rdr = csv.reader(StringIO(line), dialect=dia)
                self.buf.extend(list(line_rdr))
    
            # Note: encoding is irrelevant here
>           reader = csv.reader(f, dialect=dia, strict=True)
E           TypeError: "quotechar" must be string or None, not int

io/parsers/python_parser.py:224: TypeError

During handling of the above exception, another exception occurred:

all_parsers = <pandas.tests.io.parser.conftest.PythonParser object at 0x7ffdd7d98250>
kwargs = {'quotechar': 2}, msg = '"quotechar" must be string, not int'

    @pytest.mark.parametrize(
        "kwargs,msg",
        [
            ({"quotechar": "foo"}, '"quotechar" must be a(n)? 1-character string'),
            (
                {"quotechar": None, "quoting": csv.QUOTE_MINIMAL},
                "quotechar must be set if quoting enabled",
            ),
            ({"quotechar": 2}, '"quotechar" must be string, not int'),
        ],
    )
    def test_bad_quote_char(all_parsers, kwargs, msg):
        data = "1,2,3"
        parser = all_parsers
    
        with pytest.raises(TypeError, match=msg):
>           parser.read_csv(StringIO(data), **kwargs)
E           AssertionError: Regex pattern '"quotechar" must be string, not int' does not match '"quotechar" must be string or None, not int'.

tests/io/parser/test_quoting.py:33: AssertionError

**Comment by FRidh** [comment]
With which python3 version does pandas fail? Looks like https://github.com/pandas-dev/pandas/issues/44420

**Review by FRidh — APPROVED** [review]
Looks good to me. llvm timed out, which is not unexpected. Unless there is any other known failure I'd say we merge it.

**Comment by mweinelt** [comment]
requests-cache fails on import

```python
Executing pythonImportsCheckPhase
Check whether the following modules can be imported: requests_cache
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "/nix/store/n35ldca6pxnil9khwlpnvr31k2n6p2dg-python3-3.9.11/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/nix/store/gqaxbhgb74lwxdxid9imwijvngac2g29-python3.9-requests-cache-0.8.1/lib/python3.9/site-packages/requests_cache/__init__.py", line 43, in <module>
    from .backends import *
  File "/nix/store/gqaxbhgb74lwxdxid9imwijvngac2g29-python3.9-requests-cache-0.8.1/lib/python3.9/site-packages/requests_cache/backends/__init__.py", line 8, in <module>
    from .base import BaseCache, BaseStorage
  File "/nix/store/gqaxbhgb74lwxdxid9imwijvngac2g29-python3.9-requests-cache-0.8.1/lib/python3.9/site-packages/requests_cache/backends/base.py", line 18, in <module>
    from ..serializers import init_serializer
  File "/nix/store/gqaxbhgb74lwxdxid9imwijvngac2g29-python3.9-requests-cache-0.8.1/lib/python3.9/site-packages/requests_cache/serializers/__init__.py", line 6, in <module>
    from .preconf import (
  File "/nix/store/gqaxbhgb74lwxdxid9imwijvngac2g29-python3.9-requests-cache-0.8.1/lib/python3.9/site-packages/requests_cache/serializers/preconf.py", line 26, in <module>
    base_stage = CattrStage()  #: Base stage for all serializer pipelines
  File "/nix/store/gqaxbhgb74lwxdxid9imwijvngac2g29-python3.9-requests-cache-0.8.1/lib/python3.9/site-packages/requests_cache/serializers/cattrs.py", line 32, in __init__
    self.converter = init_converter(factory)
  File "/nix/store/gqaxbhgb74lwxdxid9imwijvngac2g29-python3.9-requests-cache-0.8.1/lib/python3.9/site-packages/requests_cache/serializers/cattrs.py", line 67, in init_converter
    converter.register_structure_hook(
  File "/nix/store/vrv8sin3381s23p086ywl8n8jfyiz4q2-python3.9-cattrs-1.8.0/lib/python3.9/site-packages/cattr/converters.py", line 263, in register_structure_hook
    self._structure_func.register_cls_list([(cl, func)])
  File "/nix/store/vrv8sin3381s23p086ywl8n8jfyiz4q2-python3.9-cattrs-1.8.0/lib/python3.9/site-packages/cattr/dispatch.py", line 57, in register_cls_list
    self._single_dispatch.register(cls, handler)
  File "/nix/store/n35ldca6pxnil9khwlpnvr31k2n6p2dg-python3-3.9.11/lib/python3.9/functools.py", line 855, in register
    raise TypeError(
TypeError: Invalid first argument to `register()`. ForwardRef('CachedResponse') is not a class.
```

**Pull request merged**
