### PR TITLE
androidenv: enhance script for the generated expressions

### PR DESCRIPTION
**Pull request by lucafavatella**
###### Motivation for this change

Make the generation of androidenv generated expressions more reproducible.

This started by extracting the non-controversial bits from PR #58131 , that almost got approval in Apr 2019 but was not merged for [the presence of bits requiring further refinement](https://github.com/NixOS/nixpkgs/pull/58131#issuecomment-487743116).

(I was considering to propose an unrelated androidenv PR and I read in the PR template re helping reviewing PRs, so I am triaging androidenv-related PRs and trying to bring them forward.)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
  - **Not applicable**.
- Built on platform(s) - **Not applicable in itself**, tested via #82118 so please refer to that.
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests)) - **Not applicable**
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"` - **Not applicable**
- [ ] Tested execution of all binary files (usually in `./result/bin/`) - **Not applicable**
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after) - **Not applicable**
- [x] Ensured that relevant documentation is up to date
  - [x] doc/languages-frameworks/android.section.md#updating-the-generated-expressions
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lucafavatella** [comment]
@tadfisher @svanderburg @numinit These are `generate.sh`-related changes extracted from PR #58131 so - strictly speaking - not meant to have functional changes (that I segregated in PR #82118 - still draft while I check doc) : could you please (re-)review these (#82067) changes so we move things forward re androidenv PRs?

**Comment by lucafavatella** [comment]
As evident in PR #82118, in order to smoke test successfully the expressions generated by the script amended in this PR (that are *not* in this PR, but in #82118 ) I had to *manually* delete a few of the generated entries. I suggest not to wait for the process to be fully implemented as automated before we merge PRs otherwise PRs may stay hanging (then requiring new rebase and review ...).

**Comment by svanderburg** [comment]
These can go in. The smoke tests succeed and changes make sense.

@lucafavatella I will make some updates to my tests. I noticed that the documentation is slightly outdated here and there.

**Comment by svanderburg** [comment]
About the generation: it seems that we are facing all kinds of new problems compared to several months. I did some investigation and the sad conclusion is that you need some kind of imperative program to properly process it.

Some packages, for example, have the same name and version identifiers, but different zip files. For example some entries are split between operaing systems. The XSL stylesheets make the assumption that there is only one entry per package/version. That used to work in 99% of all cases, but now it seems that the amount of packages that deviate from this has grown.

It seems that Google also has weird ways to configure package repository metadata.

I think manual tweaking for now is unavoidable, until we have adjusted the XSL stylesheets to become more robust. Or when we have come up with a more robust conversion strategy,

So I agree, let's just integrate this. As long as the test pass I'm fine with it.

**Review by svanderburg — APPROVED** [review]

**Comment by svanderburg** [comment]
I'll also add to my personal TODO list to investigate the conversion process so that we actually can get the conversion done without tweaking, but I need to find the time for that :)

**Pull request merged**
