### PR TITLE
Fix stylish haskell by using HsYAML 0.2.1.0

### LINKED ISSUE #79130: Package `stylish-haskell` is marked as broken, refusing to evaluate
**Describe the bug**
Trying to install `stylish-haskell` fails.

https://github.com/NixOS/nixpkgs/blob/bf4169178ec8c9d8c9947ae4ee7f018093a6e77f/pkgs/development/haskell-modules/configuration-hackage2nix.yaml#L1022

**To Reproduce**
1. `$ nix-env -i stylish-haskell`
1. watch it fail

**Expected behavior**
It should install `stylish-haskell`

**Screenshots**
image

**Additional context**
`stylish-haskell` has a dependency on `>=0.2.0 && <0.3`, but it looks like `HsYAML` is set to `0.1.2.0` in [`configuration-hackage2nix.yaml`](https://github.com/NixOS/nixpkgs/blob/bf4169178ec8c9d8c9947ae4ee7f018093a6e77f/pkgs/development/haskell-modules/configuration-hackage2nix.yaml#L1022)

**Metadata**
```
λ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (1.46 MiB download, 7.88 MiB unpacked):
  /nix/store/3lvcb4hxzax99zvb33ryk4whcv7zpjq2-bash-interactive-4.4-p23-info
  /nix/store/czg8zzd1qib1yafggnf5jsd14cmcfsdv-bash-interactive-4.4-p23-doc
  /nix/store/gr67mfj18zmyb0w7510ihi1qbivnjbaa-bash-interactive-4.4-p23-man
  /nix/store/kk512ydg1i1r0h5m9fizdrl9qxlrazrf-bash-interactive-4.4-p23-dev
  /nix/store/l5zsd7mphr5gp8p5y46ba6ahwlna1gnb-DarwinTools-1
  /nix/store/lq6lcv42lf7cp35lgxmxgs6qikqhvgg9-nix-info
  /nix/store/x3vwmx1y5l9ssy07i67395g1xzba1cyk-readline-7.0p5
  /nix/store/y27b4rnmiwzvpznb2hbqmvdzzk4a5472-bash-interactive-4.4-p23
copying path '/nix/store/czg8zzd1qib1yafggnf5jsd14cmcfsdv-bash-interactive-4.4-p23-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/l5zsd7mphr5gp8p5y46ba6ahwlna1gnb-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/3lvcb4hxzax99zvb33ryk4whcv7zpjq2-bash-interactive-4.4-p23-info' from 'https://cache.nixos.org'...
copying path '/nix/store/gr67mfj18zmyb0w7510ihi1qbivnjbaa-bash-interactive-4.4-p23-man' from 'https://cache.nixos.org'...
copying path '/nix/store/lq6lcv42lf7cp35lgxmxgs6qikqhvgg9-nix-info' from 'https://cache.nixos.org'...
copying path '/nix/store/x3vwmx1y5l9ssy07i67395g1xzba1cyk-readline-7.0p5' from 'https://cache.nixos.org'...
copying path '/nix/store/y27b4rnmiwzvpznb2hbqmvdzzk4a5472-bash-interactive-4.4-p23' from 'https://cache.nixos.org'...
copying path '/nix/store/kk512ydg1i1r0h5m9fizdrl9qxlrazrf-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.3.0, macOS 10.15.3`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.1`
 - channels(rpearce): `"home-manager, nixpkgs-20.03pre211437.e3a9318b6fd"`
 - nixpkgs: `/Users/rpearce/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - stylish-haskell
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by clkamp**
Fixes #79130 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cdepillabout** [comment]
Looks good, thanks for fixing this up!

**Comment by rpearce** [comment]
Thank you for this

**Comment by turboMaCk** [comment]
Oh great that this is fixed and merged, thanks!

**Comment by rpearce** [comment]
Looks like this was merged 13 days ago...is it out in the world yet? I'm not picking it up in the unstable channel, but I'm also not the most experienced nixer

**Comment by turboMaCk** [comment]
I've added it to my custom overlay https://github.com/turboMaCk/Dotfiles/blob/master/nixos/overlays/haskell.nix

**Comment by rpearce** [comment]
Gotcha! I did the same late last night, and it's all :+1:. Thank you

https://github.com/rpearce/.config/blob/a2bb839dea4ad7d49d8e1d5091ffe996e677178e/nix/nixpkgs/config.nix#L12-L21

**Pull request merged**
