### PR TITLE
vimPlugins: turn filetype and syntax before sourcing the plugins

### LINKED ISSUE #65894: vim-terraform plugin breaks neovim's manifest generation.
**Describe the bug**
When I try to build Neovim with the `vim-terraform` plugin, neovim is started with a minimal configuration to generate the manifest of the remote plugins [here](https://github.com/NixOS/nixpkgs/blob/1c709e0e6c037961cea0b3206d1f850e2e1ad636/pkgs/applications/editors/neovim/wrapper.nix#L94-L118). Vim terraform recently [received a change](https://github.com/hashivim/vim-terraform/commit/657cf09ff3a53388cee2cfabdbe44512f9f60e4d) that's breaking because the event was not found.

**To Reproduce**
1. `nix-build -I nixpkgs=. -E 'with import <nixpkgs> {}; neovim.override { configure = { vam.pluginDictionaries = [ "vim-terraform" ]; }; }' --show-trace`

**Expected behavior**
NeoVim with the terraform plugin built

**Additional context**
<details>
<summary>error log</summary>

```
 λ  nix-build -I nixpkgs=. -E 'with import <nixpkgs> {}; neovim.override { configure = { vam.pluginDictionaries = [ "vim-terraform" ]; }; }' --show-trace
these derivations will be built:
  /nix/store/ychncgzlm68fvwvfrnw19fliy5p040dz-vimrc.drv
  /nix/store/hw2q66r2ngc21af2i5619pnfnw5jdmnp-neovim-0.3.7.drv
building '/nix/store/ychncgzlm68fvwvfrnw19fliy5p040dz-vimrc.drv'...
building '/nix/store/hw2q66r2ngc21af2i5619pnfnw5jdmnp-neovim-0.3.7.drv'...
Generating remote plugin manifest
Error detected while processing /nix/store/dkns06xxx69b9fzsxsk3505wpl7rky5l-vimplugin-vim-terraform-2019-06-20/share/vim-plugins/vim-terraform/ftdetect/terraform.vim:
line    2:
E216: No such group or event: filetypedetect BufRead,BufNewFile *.tf
remote/host: generated rplugin manifest: /nix/store/fnspsjif1dm824va81hbl3v3iy65krna-neovim-0.3.7/rplugin.vim
Generating rplugin.vim failed!
builder for '/nix/store/hw2q66r2ngc21af2i5619pnfnw5jdmnp-neovim-0.3.7.drv' failed with exit code 1
error: build of '/nix/store/hw2q66r2ngc21af2i5619pnfnw5jdmnp-neovim-0.3.7.drv' failed

```
</details>

<details>

<summary>Reversal patch confirming the cause</summary>

```diff
diff --git a/pkgs/misc/vim-plugins/overrides.nix b/pkgs/misc/vim-plugins/overrides.nix
index 5ee03077d71..500c1944c6b 100644
--- a/pkgs/misc/vim-plugins/overrides.nix
+++ b/pkgs/misc/vim-plugins/overrides.nix
@@ -42,6 +42,10 @@ self: super: {
     src = skim.vim;
   };
 
+  vim-terraform = super.vim-terraform.overrideAttrs(oa: {
+    patches = (oa.patches or []) ++ lib.singleton ./vim-terraform-remove-invalid-event.patch;
+  });
+
   LanguageClient-neovim = let
     version = "0.1.146";
     LanguageClient-neovim-src = fetchurl {
diff --git a/pkgs/misc/vim-plugins/vim-terraform-remove-invalid-event.patch b/pkgs/misc/vim-plugins/vim-terraform-remove-invalid-event.patch
new file mode 100644
index 00000000000..e45bb0ed554
--- /dev/null
+++ b/pkgs/misc/vim-plugins/vim-terraform-remove-invalid-event.patch
@@ -0,0 +1,18 @@
+commit 04621b386dbee77921c989156194f280445d45ce
+Author: Wael M. Nasreddine <wael.nasreddine@gmail.com>
+Date:   Sat Aug 3 19:32:13 2019 -0700
+
+    Revert "Remove Vim's default filetype detection for .tf files"
+    
+    This reverts commit 657cf09ff3a53388cee2cfabdbe44512f9f60e4d.
+
+diff --git a/ftdetect/terraform.vim b/ftdetect/terraform.vim
+index 5919422..467351e 100644
+--- a/ftdetect/terraform.vim
++++ b/ftdetect/terraform.vim
+@@ -1,5 +1,3 @@
+-" By default, Vim associates .tf files with TinyFugue - tell it not to.
+-autocmd! filetypedetect BufRead,BufNewFile *.tf
+ autocmd BufRead,BufNewFile *.tf set filetype=terraform
+ autocmd BufRead,BufNewFile *.tfvars set filetype=terraform
+ autocmd BufRead,BufNewFile *.tfstate set filetype=json
```

</details>

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.11, NixOS, 19.09pre-git (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `""`
 - channels(kalbasit): `"home-manager-18.09, nixpkgs-18.09.932.09195057114"`
 - channels(yl): `""`
 - nixpkgs: `/run/current-system/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
```

### PR DESCRIPTION
**Pull request by kalbasit**
###### Motivation for this change

Vim Terraform expects the `filetypedetect` group to exist. However, since we were enabling the filetype and the syntax *after* loading the plugins, it was exiting with an error preventing us from generating the remote plugins manifest with the plugin enabled. See #65894 for context.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @timokau @gloaming @manveru @rvolosatovs

closes #65894

### CODE REVIEW

**Comment by kalbasit** [comment]
Tested with *neovim on NixOS* only. Reviewer: Please test with Vim as well as Darwin!

```
nix-build -I nixpkgs=. -E 'with import <nixpkgs> {}; neovim.override { configure = { vam.pluginDictionaries = [ "vim-terraform" ]; }; }' --show-trace
```

**Comment by timokau** [comment]
Not sure this is a good idea. The [issue](https://github.com/neovim/neovim/pull/6596) linked by @gloaming mentions that they
- are not sure if `filetype on` can be completely undone
- each `filetype on` adds ~100ms overhead

**Comment by kalbasit** [comment]
> Not sure this is a good idea. The [issue](https://github.com/neovim/neovim/pull/6596) linked by @gloaming mentions that they
> 
>     * are not sure if `filetype on` can be completely undone
> 
>     * each `filetype on` adds ~100ms overhead

We already had it in the vimRC. I merely moved it to the top.

**Comment by kalbasit** [comment]
> EDIT: I see what you mean, sorry for missing your point. Another way to solve this is to enable this patch only for the manifest generation. It might still break the result vim. I'll give it a shot.

@timokau It seems to work for me if I enabled at the top only for generating the manifest. What do you think of this approach?

**Comment by timokau** [comment]
I don't think you missed my point; On the contrary, I missed that we already set `filetype on`. Not sure why we do that, not really our place to change the defaults. But since we already do...

But then there's still justinmk's point in https://github.com/neovim/neovim/pull/6596#issuecomment-297459887 that this may interfere with plugin managers. So your new solution is probably better. Not sure why plugin managers do the `filetype off`/`filetype on` dance in the first place though.

**Comment by timokau** [comment]
Instead of `earlyFiletype`, maybe we want a more general `beforePlugins` escape hatch? Then we could just say `beforePlugins = "filetype ident on"`. Paying the 100ms twice only for the manifest generation shouldn't matter.

**Comment by kalbasit** [comment]
@timokau sure that sounds like a good idea. I've added `beforePlugins` and `afterPlugins` as it makes sense to have both. Obviously, the manifest generation only needs the `beforePlugins`.

PTAL

**Comment by timokau** [comment]
Isn't `afterPlugins` == `customRC`? I wonder what other plugin managers do. If they also don't set `filetype on`, how is it plugins like vim-terraform don't fail for them?

> PTAL

I don't know that acronym.

**Comment by kalbasit** [comment]
> Isn't `afterPlugins` == `customRC`?

That's right. I removed it then.

> I wonder what other plugin managers do. If they also don't set `filetype on`, how is it plugins like vim-terraform don't fail for them?
> 

I'm not sure actually, that's a good question. We could take this discussion on a separate issue and look deeper into plugins. Maybe @junegunn could chime in here as well.

> > PTAL
> 
> I don't know that acronym.

Please Take Another Look :)

**Comment by timokau** [comment]
> > I wonder what other plugin managers do. If they also don't set `filetype on`, how is it plugins like vim-terraform don't fail for them?
> 
> I'm not sure actually, that's a good question. We could take this discussion on a separate issue and look deeper into plugins. Maybe junegunn could chime in here as well.

Right, I'm fine with merging this for now if it fixes the immediate build failure :+1:. Anything else can be done as a followup.

> Please Take Another Look :)

Good to go :)

**Review by timokau — APPROVED** [review]

**Pull request merged**
