### PR TITLE
xorg.libAppleWM: 1.4.1 -> 1.4.1-unstable-2021-01-04

### PR DESCRIPTION
**Pull request by paparodeo**
https://gitlab.freedesktop.org/xorg/lib/libapplewm/-/compare/libAppleWM-1.4.1...d8926ba5805ac8feed0b0cf8ebf54d8ab7af2314

fixes darwin build

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Aleksanaa** [comment]
review tomorrow

**Comment by emilazy** [comment]
Sadly doesn’t seem to fix the build:

```
/nix/store/isgsi0yl9z8g2r9iaixh1ziszf47apm4-bash-5.2p37/bin/bash ../libtool --silent --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I..    -I/nix/store/q7bngy6aghr8z9hsx0mj2bnkmri1nknw-xorgproto-2024.1/include -I/nix/store/0f342khrmnp62q99ak3s0ghrym5d3w00-libX11-1.8.10-dev/include -I/nix/store/p2fycb7yz6zh0pqc0bkrss2s7b06wfas-libXext-1.3.6-dev/include  -Wall -Wpointer-arith -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wnested-externs -fno-strict-aliasing -Wbad-function-cast -Wformat=2  -F/System/Library/Frameworks/ApplicationServices.framework/Frameworks -I../include -I../include/X11 -I../include/X11/extensions -g -O2 -c -o applewm.lo applewm.c
applewm.c:43:10: fatal error: 'HIServices/Processes.h' file not found
#include <HIServices/Processes.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~
applewm.c:43:10: note: did not find header 'Processes.h' in framework 'HIServices' (loaded from '/System/Library/Frameworks/ApplicationServices.framework/Frameworks')
1 error generated.
```

Unclear to me whether it’s loading it from the SDK and that’s still not enough, or whether `-F` is actually not being interpreted relative to the `SDKROOT` for some reason. Will try to investigate.

**Comment by paparodeo** [comment]
> Sadly doesn’t seem to fix the build:
> 
> ```
> /nix/store/isgsi0yl9z8g2r9iaixh1ziszf47apm4-bash-5.2p37/bin/bash ../libtool --silent --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I..    -I/nix/store/q7bngy6aghr8z9hsx0mj2bnkmri1nknw-xorgproto-2024.1/include -I/nix/store/0f342khrmnp62q99ak3s0ghrym5d3w00-libX11-1.8.10-dev/include -I/nix/store/p2fycb7yz6zh0pqc0bkrss2s7b06wfas-libXext-1.3.6-dev/include  -Wall -Wpointer-arith -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wnested-externs -fno-strict-aliasing -Wbad-function-cast -Wformat=2  -F/System/Library/Frameworks/ApplicationServices.framework/Frameworks -I../include -I../include/X11 -I../include/X11/extensions -g -O2 -c -o applewm.lo applewm.c
> applewm.c:43:10: fatal error: 'HIServices/Processes.h' file not found
> #include <HIServices/Processes.h>
>          ^~~~~~~~~~~~~~~~~~~~~~~~
> applewm.c:43:10: note: did not find header 'Processes.h' in framework 'HIServices' (loaded from '/System/Library/Frameworks/ApplicationServices.framework/Frameworks')
> 1 error generated.
> ```
> 
> Unclear to me whether it’s loading it from the SDK and that’s still not enough, or whether `-F` is actually not being interpreted relative to the `SDKROOT` for some reason. Will try to investigate.

`-F` doesn't seem to be relative to `$SDKROOT`.  using your branch that bumps to sdk-11 for x86 it works just fine when prepending `$SDKROOT` to the path specified in `-F`.

**Comment by paparodeo** [comment]
<details><summary>log of error when adding `-v` to compile flag</summary>

```
clang version 16.0.6
Target: x86_64-apple-darwin
Thread model: posix
InstalledDir: /nix/store/mww4g24fr7dasr4db0qjhi3l5kh25wzn-clang-16.0.6/bin
 (in-process)
 "/nix/store/mww4g24fr7dasr4db0qjhi3l5kh25wzn-clang-16.0.6/bin/clang-16" -cc1 -triple x86_64-apple-macosx11.3.0 -Wundef-prefix=TARGET_OS_ -Werror=undef-prefix -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name applewm.c -mrelocation-model pic -pic-level 2 -mframe-pointer=all -relaxed-aliasing -ffp-contract=on -fno-rounding-math -funwind-tables=2 -target-sdk-version=11.3 -fcompatibility-qualified-id-block-type-checking -fvisibility-inlines-hidden-static-local-var -target-cpu penryn -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debug-info-kind=standalone -dwarf-version=4 -debugger-tuning=lldb -target-linker-version 951.9 -v -fcoverage-compilation-dir=/Users/anna/tmp/xorg/libAppleWM-1.4.1/src -resource-dir /nix/store/9d4xm06iy9lf0xc8g1fmpsmcj6sarmw8-clang-wrapper-16.0.6/resource-root -dependency-file .deps/applewm.Tpo -MT applewm.lo -sys-header-deps -MP -idirafter /nix/store/sj7d5nmfgchx43r1rccg0my49maazcr2-libSystem-B/include -isystem /nix/store/mi5qlpysa4m739p7q2cq3nxbibxh4vgn-libcxx-16.0.6-dev/include -isystem /nix/store/hn854dgwhphsfv0zyavnmijmh2d5vk2v-compiler-rt-libc-16.0.6-dev/include -isystem /nix/store/2a269kwrklbcdlfil8mkgi3f9c9b67jr-xorgproto-2024.1/include -isystem /nix/store/pkijmdb5jnla9j7sszjr4wv574grmahb-libX11-1.8.10-dev/include -isystem /nix/store/2a269kwrklbcdlfil8mkgi3f9c9b67jr-xorgproto-2024.1/include -isystem /nix/store/8m3kphp4065051gpywaaivqg1i0mcwv6-libxcb-1.17.0-dev/include -isystem /nix/store/gs0c5fwx0d5vxwyrrdr2zb415j8ni0w4-libXext-1.3.6-dev/include -isystem /nix/store/1hrpf5zj0gs8684lxlvx4w9v542fkcg0-libXau-1.0.11-dev/include -isystem /nix/store/adzg5y6cyvxbx9wnnlf887l2qyqdbw7w-libiconv-107-dev/include -isystem /nix/store/jnsh7dlrzm8hajpic8374v97kjmrdavw-libresolv-83-dev/include -isystem /nix/store/ik99d6pm73vr8pjc058ch059cwh3bqrq-libsbuf-14.1.0-dev/include -isystem /nix/store/j6q1z4sr909lc33y9kdh5d0b31dgyrn6-cups-headers-2.4.11/include -isysroot /nix/store/22flqwpyxjdkfqkbmagi069w2h7vmxnv-apple-sdk-11.3/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -U _FORTIFY_SOURCE -D HAVE_CONFIG_H -I . -I .. -I /nix/store/2a269kwrklbcdlfil8mkgi3f9c9b67jr-xorgproto-2024.1/include -I /nix/store/pkijmdb5jnla9j7sszjr4wv574grmahb-libX11-1.8.10-dev/include -I /nix/store/gs0c5fwx0d5vxwyrrdr2zb415j8ni0w4-libXext-1.3.6-dev/include -F/System/Library/Frameworks/ApplicationServices.framework/Frameworks -I ../include -I ../include/X11 -I ../include/X11/extensions -D PIC -U _FORTIFY_SOURCE -D _FORTIFY_SOURCE=2 -internal-isystem /nix/store/22flqwpyxjdkfqkbmagi069w2h7vmxnv-apple-sdk-11.3/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/local/include -internal-isystem /nix/store/9d4xm06iy9lf0xc8g1fmpsmcj6sarmw8-clang-wrapper-16.0.6/resource-root/include -internal-externc-isystem /nix/store/22flqwpyxjdkfqkbmagi069w2h7vmxnv-apple-sdk-11.3/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -source-date-epoch 1302130966 -O2 -Wformat -Wformat-security -Werror=format-security -Wall -Wpointer-arith -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wnested-externs -Wbad-function-cast -Wformat=2 -fdebug-compilation-dir=/Users/anna/tmp/xorg/libAppleWM-1.4.1/src -ferror-limit 19 -fzero-call-used-regs=used-gpr -fwrapv -stack-protector 2 -stack-protector-buffer-size 4 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fmax-type-align=16 -vectorize-loops -vectorize-slp -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o .libs/applewm.o -x c applewm.c
clang -cc1 version 16.0.6 based upon LLVM 16.0.6 default target x86_64-apple-darwin20.6.0
ignoring nonexistent directory "/nix/store/22flqwpyxjdkfqkbmagi069w2h7vmxnv-apple-sdk-11.3/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/nix/store/22flqwpyxjdkfqkbmagi069w2h7vmxnv-apple-sdk-11.3/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/Library/Frameworks"
ignoring duplicate directory "/nix/store/2a269kwrklbcdlfil8mkgi3f9c9b67jr-xorgproto-2024.1/include"
  as it is a non-system directory that duplicates a system directory
ignoring duplicate directory "/nix/store/pkijmdb5jnla9j7sszjr4wv574grmahb-libX11-1.8.10-dev/include"
  as it is a non-system directory that duplicates a system directory
ignoring duplicate directory "/nix/store/2a269kwrklbcdlfil8mkgi3f9c9b67jr-xorgproto-2024.1/include"
ignoring duplicate directory "/nix/store/gs0c5fwx0d5vxwyrrdr2zb415j8ni0w4-libXext-1.3.6-dev/include"
  as it is a non-system directory that duplicates a system directory
#include "..." search starts here:
#include <...> search starts here:
 .
 ..
 /System/Library/Frameworks/ApplicationServices.framework/Frameworks (framework directory)
 ../include
 ../include/X11
 ../include/X11/extensions
 /nix/store/mi5qlpysa4m739p7q2cq3nxbibxh4vgn-libcxx-16.0.6-dev/include
 /nix/store/hn854dgwhphsfv0zyavnmijmh2d5vk2v-compiler-rt-libc-16.0.6-dev/include
 /nix/store/2a269kwrklbcdlfil8mkgi3f9c9b67jr-xorgproto-2024.1/include
 /nix/store/pkijmdb5jnla9j7sszjr4wv574grmahb-libX11-1.8.10-dev/include
 /nix/store/8m3kphp4065051gpywaaivqg1i0mcwv6-libxcb-1.17.0-dev/include
 /nix/store/gs0c5fwx0d5vxwyrrdr2zb415j8ni0w4-libXext-1.3.6-dev/include
 /nix/store/1hrpf5zj0gs8684lxlvx4w9v542fkcg0-libXau-1.0.11-dev/include
 /nix/store/adzg5y6cyvxbx9wnnlf887l2qyqdbw7w-libiconv-107-dev/include
 /nix/store/jnsh7dlrzm8hajpic8374v97kjmrdavw-libresolv-83-dev/include
 /nix/store/ik99d6pm73vr8pjc058ch059cwh3bqrq-libsbuf-14.1.0-dev/include
 /nix/store/j6q1z4sr909lc33y9kdh5d0b31dgyrn6-cups-headers-2.4.11/include
 /nix/store/9d4xm06iy9lf0xc8g1fmpsmcj6sarmw8-clang-wrapper-16.0.6/resource-root/include
 /nix/store/22flqwpyxjdkfqkbmagi069w2h7vmxnv-apple-sdk-11.3/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
 /nix/store/22flqwpyxjdkfqkbmagi069w2h7vmxnv-apple-sdk-11.3/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
 /nix/store/sj7d5nmfgchx43r1rccg0my49maazcr2-libSystem-B/include
End of search list.
applewm.c:43:10: fatal error: 'HIServices/Processes.h' file not found
#include <HIServices/Processes.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~
applewm.c:43:10: note: did not find header 'Processes.h' in framework 'HIServices' (loaded from '/System/Library/Frameworks/ApplicationServices.framework/Frameworks')
```
</details>

**Comment by emilazy** [comment]
I see. What a pain. This wouldn’t even build on modern macOS at all. This commit fixes it: https://gitlab.freedesktop.org/xorg/lib/libapplewm/-/commit/be972ebc3a97292e7d2b2350eff55ae12df99a42. It’s from three years ago. We’re on a version from 2011. Let’s bump to Git HEAD.

**Comment by emilazy** [comment]
I just checked and XQuartz ships the Git version of this, so it’s definitely the way to go.

**Comment by emilazy** [comment]
Looks like the `mirror://` line in `pkgs/servers/x11/xorg/tarballs.list` needs changing to an archive link like the `https://gitlab.freedesktop.org/xorg/driver/xf86-video-nouveau/-/archive/3ee7cbca8f9144a3bb5be7f71ce70558f548d268/xf86-video-nouveau-3ee7cbca8f9144a3bb5be7f71ce70558f548d268.tar.bz2` that’s already present, and then I guess `generate-expr-from-tarballs.pl` does the rest?

**Comment by paparodeo** [comment]
> Looks like the `mirror://` line in `pkgs/servers/x11/xorg/tarballs.list` needs changing to an archive link like the `https://gitlab.freedesktop.org/xorg/driver/xf86-video-nouveau/-/archive/3ee7cbca8f9144a3bb5be7f71ce70558f548d268/xf86-video-nouveau-3ee7cbca8f9144a3bb5be7f71ce70558f548d268.tar.bz2` that’s already present, and then I guess `generate-expr-from-tarballs.pl` does the rest?

hmm, i updated it in `override.nix` let me look.

**Comment by emilazy** [comment]
It only overwrites entries that have a prefix it updates, which is why it works for Nouveau already.

**Comment by paparodeo** [comment]
> It only overwrites entries that have a prefix it updates, which is why it works for Nouveau already.

I see. but then Nouveau (and perhaps libAppleWM) will need to be manually updated once a new tag is cut?

**Comment by emilazy** [comment]
Yeah, though considering there’s been no commits in almost four years and no release for 13 I suspect that’s not a pressing issue. XQuartz is effectively the only consumer of this library and ships the Git HEAD, so there’s presumably essentially no incentive to perform an actual release. Hopefully Xorg packages will become normal before they tag another release in 2038 or something.

**Comment by paparodeo** [comment]
used tarballs.list. tho I mildly prefer the pure override version given it seems unlikely this will ever get updated.

**Review by emilazy — APPROVED** [review]
LGTM and builds on `x86_64-darwin`, thanks.

I’m pretty confident that something like https://github.com/NixOS/nixpkgs/pull/262669 will enable this to be a normal package with a normal update script by the time that there’s any reason to update this. (It’s on my 25.05 to‐do list now.)

**Pull request merged**
