### PR TITLE
stdenv: generalise showPlatforms

### PR DESCRIPTION
**Pull request by wegank**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This is still wrong.

```
$ NIXPKGS_ALLOW_BROKEN=1 nix-instantiate . -A pkgsStatic.systemd
error: Package ‘systemd-252.5’ in /git/nixpkgs/pkgs/os-specific/linux/systemd/default.nix:724 is only supported on `aarch64-linux armv5tel-linux armv6l-linux armv7a-linux armv7l-linux i686-linux m68k-linux microblaze-linux microblazeel-linux mipsel-linux mips64el-linux powerpc64-linux powerpc64le-linux riscv32-linux riscv64-linux s390-linux s390x-linux x86_64-linux` but not on requested ‘x86_64-linux’, refusing to evaluate.
```
:-1:

(The `NIXPKGS_ALLOW_BROKEN=1` is only because the simplest counterexample, `systemd`, declares itself to be `meta.broken` on the platforms it doesn't support -- which is sort of going overboard).

Note the bolded portions:

error: Package ‘systemd-252.5’ in /git/nixpkgs/pkgs/os-specific/linux/systemd/default.nix:724 **is only supported on** `aarch64-linux armv5tel-linux armv6l-linux armv7a-linux armv7l-linux i686-linux m68k-linux microblaze-linux microblazeel-linux mipsel-linux mips64el-linux powerpc64-linux powerpc64le-linux riscv32-linux riscv64-linux s390-linux s390x-linux `**`x86_64-linux`** but not on requested **`x86_64-linux`**, refusing to evaluate.

The error message is telling the user that this package is only supported on `x86_64-linux`, so it's unsupported on `x86_64-linux`.

### You cannot just `lib.filter lib.systems.all` and expect the result to explain the problem to the user

**Comment by wegank** [comment]
I'm not the one introducing the output of the platforms in the error message. The pull requests I made are to fix obvious problems, like breaking nixpkgs-review. There are certainly edge cases that I didn't detect, and I clearly mentioned one of them in the first PR.

@amjoseph-nixpkgs Maybe you'll want to fix this for cross-builds, but if not, I'd suggest completely revert the commits beginning from @SuperSandro2000's.

**Comment by amjoseph-nixpkgs** [comment]
Proper fix: https://github.com/NixOS/nixpkgs/pull/222852

**Comment by SuperSandro2000** [comment]
> @amjoseph-nixpkgs Maybe you'll want to fix this for static and cross builds, but if not, I'd suggest completely revert the commits beginning from @SuperSandro2000's.

I tested this with the gcc arches added to a machine when gcc.arch/march are set and there it yielded useful results. 😅

**Pull request merged**
