### PR TITLE
Update gnome3.20 packages august

### PR DESCRIPTION
**Pull request by DamienCassou**
###### Things done
- [x] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I tried most of the binaries. Some required tracker to be running (which I don't).

### CODE REVIEW

**Comment by lethalman** [comment]
Great, feel free to merge for these changes, no need for my review. :+1:

**Comment by obadz** [comment]
There seems to be a build issue with `gnome-calculator` http://hydra.nixos.org/build/38881454/nixlog/1#line-153

**Comment by obadz** [comment]
Looks like it's due to 532f88c (glib upgrade) and not this PR

**Pull request merged**
