### PR TITLE
matplotlib: 3.4.3 -> 3.5.0

### PR DESCRIPTION
**Pull request by K900**
###### Motivation for this change
New upstream release. Lots of frustration. See commit messages. nixpkgs-review still running, will update.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
nixpkgs-review update: it's going to rebuild 2k packages and I'm not doing that.

**Comment by pennae** [comment]
> nixpkgs-review update: it's going to rebuild 2k packages and I'm not doing that.

in that case this is probably better for staging than master

**Comment by K900** [comment]
True. Rebased on top of staging, also dropped the fonttools update cause the version in staging is good enough for now and I don't want to figure out why more tests break on the newest one.

**Comment by K900** [comment]
Re-tested, builds on top of staging with the change from https://github.com/NixOS/nixpkgs/issues/147547.

**Comment by veprbl** [comment]
@GrahamcOfBorg build python38Packages.matplotlib python39Packages.matplotlib

**Comment by K900** [comment]
...why was ofborg trying to build LLVM here?

**Comment by veprbl** [comment]
@K900 The "staging", unlike "staging-next", is not built by Hydra, so there is not a cache to rely on.

**Comment by jonringer** [comment]
this is already in staging, was added in https://github.com/NixOS/nixpkgs/pull/147426

**Comment by veprbl** [comment]
@jonringer 
I don't think this is equivalent to https://github.com/NixOS/nixpkgs/pull/147426/commits/ebb34bc2e6e4851ce5343b79a8774e34e4944d86

**Comment by jonringer** [comment]
@veprbl those were addressed in https://github.com/NixOS/nixpkgs/pull/147426/commits/d20fc633dbac10fed609325f1748ec2df9c05108 and  https://github.com/NixOS/nixpkgs/pull/147426/commits/de93eeee943ed09ab95eeb6e243b03cbf5ef6a2d

**Comment by veprbl** [comment]
Fixed in 69221cf2d2eacc8b6aee36ad002411700deaf461

**Comment by K900** [comment]
I'd stick to the MPLSETUPCFG approach, because it won't break things like poetry2nix that may want to build an older version.

**Comment by veprbl** [comment]
I'm not familiar with poetry2nix. Is there a way to reproduce such possible bug?

**Comment by K900** [comment]
Create a new poetry project with `poetry init`, add a dependency on an older MPL version with `poetry add matplotlib==3.4.3`, then try building it with `pkgs.poetry2nix.mkPoetryApplication`.

**Comment by veprbl** [comment]
I couldn't get it to work. But it would seem like poetry2nix upstream already supports your case: https://github.com/nix-community/poetry2nix/blob/2ab5f606d30b042228241f400314067aa9a609af/overrides.nix#L784

I do appreciate the compatibility concern myself when it comes to reasonable overrides. The upstream claims to have a reason for not writing to setup.cfg anymore:
https://github.com/matplotlib/matplotlib/commit/93b5c0fb08b5426623fa3927a515eaec0aac0c36

**Comment by K900** [comment]
Looks like it does, yes. I guess it's not a problem then. Thanks!

**Pull request closed without merging**
