### PR TITLE
rebar3: 3.14.2 -> 3.14.4

### PR DESCRIPTION
**Pull request by dlesl**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 118596` at 63bfd8f8 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>lfe_1_2</li>
  </ul>
</details>
<details>
  <summary>3 packages built successfully:</summary>
  <ul>
    <li>lfe (lfe_1_3)</li>
    <li>rebar3</li>
    <li>relxExe</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/development/tools/build-managers/rebar3/default.nix:111:3:
```
    |
111 |   buildPhase = ''
    |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/tools/build-managers/rebar3/default.nix:115:3:
```
    |
115 |   installPhase = ''
    |   ^
```
</li>
  </ul>
</details>

**Review by happysalada — APPROVED** [review]
Here is the [release changelog](https://github.com/erlang/rebar3/releases) for information
Nothing major.

Also those comments about adding pre and post hooks can be safely ignored in my opinion. I don't see anybody wanting to build a customized version of a build tool. I would be happy to be proved wrong though.

**Comment by happysalada** [comment]
Oh, just noticed, it looks like hex_core disappeared.
I personally don't know what that is used for. What that on purpose @dlesl ?
Maybe just a note on why that is.

**Comment by dlesl** [comment]
Thanks for the review! Regarding hex_core it looks like it was removed as a dependency some time ago and is now vendored with rebar3 ( https://github.com/erlang/rebar3/commit/209c02ec57c2cc3207ee0174c3af3675b8dc8f79#diff-54d206794bbd7299616a51ef468c2aa8a076534de1d98d1786b1ea5abe7776f0 )

**Comment by happysalada** [comment]
@dlesl Great! Thanks!

**Comment by dlesl** [comment]
@happysalada Maybe not the right place to ask but would you mind taking a look at #118595 too? The bot didn't assign reviewers and I'm not sure how else to attract any 😄

**Comment by happysalada** [comment]
@SuperSandro2000 sorry to bother you with this. I think this PR is ok to merge. Do you think we could merge it?

**Pull request merged**
