### PR TITLE
xgboost: 1.7.3 -> 1.7.4

### PR DESCRIPTION
**Pull request by nviets**
###### Description of changes

Updated xgboost to latest version

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin

### CODE REVIEW

**Comment by bcdarwin** [comment]
@ofborg build xgboost

**Comment by bcdarwin** [comment]
`aarch64-darwin` build fails.

**Comment by nviets** [comment]
Weird, I have an aarch64-darwin and it built just fine for me. Look like OfBorg's build is failing in the test phase. Is there anything special about the aarch64-darwin build environment that I should be aware of? In the detailed log, I see:

```
...
[  FAILED  ] ThreadGroup.TimerThread
[  FAILED  ] ThreadGroup.TimerThreadSimple
 2 FAILED TESTS
```

**Comment by trivialfis** [comment]
The failing test is from dmlc core (a dependency) instead of xgboost, and xgboost doesn't use that part of code (thread pool). It can be safely skipped.

Let me take a look tomorrow if the test must pasa, I vaguely remember that test uses sleep to wait for thread, which can be inaccurate.

**Comment by nviets** [comment]
Thanks, we can just disable that test if needed. I'm just surprised the Borg build fails when it passed on my macbook.

**Comment by nviets** [comment]
Result of `nixpkgs-review pr 216795` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.optuna</li>
    <li>xgboostWithCuda</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>haskellPackages.xgboost-haskell</li>
    <li>python310Packages.xgboost</li>
    <li>python311Packages.xgboost</li>
    <li>xgboost</li>
  </ul>
</details>

**Comment by Mindavi** [comment]
@ofborg eval

**Comment by Mindavi** [comment]
Yes, I recommend disabling flaky tests as they just inhibit hydra/ofborg to give useful results.

But I do recommend leaving working tests enabled. It makes updating a package easier since it can give some peace of mind that the basic functionality still works, reducing the chance of broken updates.

**Comment by nviets** [comment]
@ofborg eval

**Comment by nviets** [comment]
Done, @Mindavi - ready for merge.

**Comment by nviets** [comment]
@Mindavi - is disabledTests incorrect here? It look like the errant tests are still running. What should I be using?

**Comment by nviets** [comment]
@ofborg build xgboost

**Comment by nviets** [comment]
@ofborg eval

**Comment by Mindavi** [comment]
Please change the commit message to the desired format again :)

**Comment by nviets** [comment]
@Mindavi - is this message correct? Could you point me to the format you're expecting? Thank you!

**Comment by nviets** [comment]
Another threading failure popped up on ofborg. I'll have a look tonight. This series of tests isn't consistent there.

**Comment by Mindavi** [comment]
Consider talking to upstream or maybe disabling the tests fully for aarch64-darwin.

**Comment by nviets** [comment]
@Mindavi - good to merge finally, I think. Thanks for the tips.

**Comment by Mindavi** [comment]
Sorry for the churn and thanks for pushing through!

**Pull request merged**
