### PR TITLE
tor: 0.4.4.5 -> 0.4.4.6

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

* Version update
* Add me to maintainers

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Added the security label. Fixes TROVE-2020-005. (https://trac.torproject.org/projects/tor/wiki/TROVE)

```
  o Major bugfixes (security, backport from 0.4.5.1-alpha):
    - When completing a channel, relays now check more thoroughly to
      make sure that it matches any pending circuits before attaching
      those circuits. Previously, address correctness and Ed25519
      identities were not checked in this case, but only when extending
      circuits on an existing channel. Fixes bug 40080; bugfix on
      0.2.7.2-alpha. Resolves TROVE-2020-005.
```

Daemon starts up, bootstraps the connection as soon as I try to use the proxy socket, LGTM.

**Comment by mweinelt** [comment]
I think it is prudent to also update 20.09 to the 0.4.4 series, as 0.4.3 will be EOL before 20.09 goes out of support.

**Review by mweinelt — APPROVED** [review]
Thanks for stepping up. LGTM.

**Comment by mweinelt** [comment]
Oh and maybe we could reference https://trac.torproject.org/projects/tor/wiki/org/teams/NetworkTeam/CoreTorReleases#Listofreleases somewhere in the the package.

**Comment by prusnak** [comment]
Port to stable in https://github.com/NixOS/nixpkgs/pull/104365

**Pull request merged**
