### PR TITLE
Fix TZDIR paths in FHS environments

### PR DESCRIPTION
**Pull request by abbradar**
###### Motivation for this change

Move Steam fix to a more general place and clean up.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

@the-kenny @yegortimoshenko You seem to have games which may be affected by those changes -- can you test that they still work?

### CODE REVIEW

**Comment by yegortimoshenko** [comment]
The potentially affected games are various Unity-based Mono games: Stardew Valley and Press X to Not Die. I'll test the change and I'll be right back. Probably still doesn't work if `time.timeZone` is not set (see #31393).

**Comment by abbradar** [comment]
Yeah, that shouldn't be fixed (I don't think we can handle #31393 in any way actually).

**Comment by abbradar** [comment]
@yegortimoshenko Any luck with testing?

**Comment by abbradar** [comment]
Tested with some Mono games; seems to work.

**Pull request merged**
