### PR TITLE
wxhexeditor: 0.22 -> 0.24

### PR DESCRIPTION
**Pull request by symphorien**
###### Motivation for this change
ZHF: https://github.com/NixOS/nixpkgs/issues/36453

upgrading from wxGTK 2.8 to 3.1 fixes the build

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by nlewo** [comment]
@GrahamcOfBorg build wxhexeditor

**Comment by nlewo** [comment]
Could you either fix the build for aarch64-linux or set the meta.platform to x86 only?

**Comment by symphorien** [comment]
I have no aarch64 box, but I found this thread in wxHexEditor issue tracker:
https://github.com/EUA/wxHexEditor/issues/90 and the associated patch.
This is exactly the error in the build log, so I have just pushed a commit with the patch, and I would like ofborg to try again building with this patch. I hope this does not count as abusing ofborg :°
If this does not work, I will stop the experiment, remove the commit and restrict platforms to x86 as you suggested.

**Comment by fpletz** [comment]
@GrahamcOfBorg build wxhexeditor

**Pull request merged**
