### PR TITLE
buildMozillaMach: prune patches, support rust-cbindgen 0.27, backport fix for explicity sync on nvidia gpus

### LINKED ISSUE #335791: Firefox crashes on wayland with NVIDIA due egl-wayland update and related sync issue
### Describe the bug

Firefox crashes on wayland when using an NVIDIA card through egl-wayland. This issue has been partially addressed upstream and on other distributions, some patches are available. Refer to:

- https://gitlab.freedesktop.org/mesa/mesa/-/issues/11541
- https://gitlab.archlinux.org/archlinux/packaging/packages/firefox/-/issues/7

### Steps To Reproduce
1. Launch firefox on wayland with egl-wayland (NVIDIA)
2. Toggle fullscreen -> crash

### Notify maintainers

@edolstra @lovesegfault @mweinelt 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by mweinelt**
See individual commits.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by matdibu** [comment]
I can `nixos-rebuild` my systems on nixpkgs commit `6c28973683417f384313814cb4e308906d593929`, but not on `fb3bf1dec8573d3dd17fab205ecb88fddadc53c0`

**Comment by matdibu** [comment]
would this have been caught by `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"` ?

**Comment by matdibu** [comment]
as mentioned by @drupol, the issue can be observed on CI https://hydra.nixos.org/build/270110612

**Comment by diniamo** [comment]
@mweinelt may I ask why the explicit sync patches aren't applied to the esr (115) version?

**Comment by mweinelt** [comment]
They don't apply and we're about to yank this version sooner rather than later, so I didn't fancy spending time on that.

**Comment by diniamo** [comment]
Unfortunate, thanks. I still don't understand why they aren't backporting a deal-breaking fix to the long term support version.

**Comment by mweinelt** [comment]
Decision by one of their release managers.

**Comment by diniamo** [comment]
I realized that there is a 128 esr release, so that's nice.
> They don't apply and we're about to yank this version sooner rather than later, so I didn't fancy spending time on that.
That also means that this statement is false, the patches will have to be kept for the esr version.

**Comment by mweinelt** [comment]
We're yanking 115 because we have 128.

**Comment by diniamo** [comment]
Oh, that makes sense.

**Pull request merged**
