### PR TITLE
haskellPackages.lambdabot-social-plugins,lambdabot: unbreak, add myself as maintainer

### PR DESCRIPTION
**Pull request by ncfavier**
Both build fine.

I've added myself as a maintainer for `lambdabot` only, is this enough to get notified whenever `lambdabot` is transitively broken, or should I also add all the `lambdabot-*` dependencies?

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [X] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by maralorn** [comment]
That’s exactly right. Thx!

**Comment by ncfavier** [comment]
@ofborg build lambdabot
Not sure why I need to do this

**Comment by maralorn** [comment]
Because of the `,` in the commit description.

**Comment by ncfavier** [comment]
I thought ofborg understood that, see https://github.com/NixOS/ofborg#automatic-building

You merged 105 commits because this wasn't rebased against `haskell-updates`, was that intended?

**Comment by maralorn** [comment]
Those commits come from master and we regularly merge master into haskell-updates anyway. I admit this was a bit unclean. But I was lazy and if you look at https://github.com/NixOS/nixpkgs/pull/136589 it looks clean again, so I think we are fine.

**Comment by ncfavier** [comment]
Ok, thanks!

**Pull request merged**
