### PR TITLE
rust-cbindgen: upgrade cargo fetcher and cargoSha256

### PR DESCRIPTION
**Pull request by bhipple**
Infra upgrade as part of #79975; no functional change expected.

### CODE REVIEW

**Comment by bhipple** [comment]
@grahamcofborg build rust-cbindgen

**Review by jonringer — CHANGES_REQUESTED** [review]
this seems to cause some regressions

```
[1 built (2 failed)]
error: build of '/nix/store/7ib1j5s2sp9z4jcyd818n7vxm1sjzk1q-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/80243
5 package failed to build:
adoptopenjdk-icedtea-web firefox-esr-68-unwrapped xulrunner mozplugger slimerjs

2 package built:
rust-cbindgen thunderbird
```

**Comment by bhipple** [comment]
Good catch, I will take a look and see what's up.  Right now my script is just running `nix-build -A $attr` prior to sending the PR; I think I'll bump it to do a full `nix-review wip` first and only open a PR if everything looks good!

**Comment by jonringer** [comment]
I think this is the first package that I've seen which it had reverse dependencies. I think the script is fine

**Comment by bhipple** [comment]
@jonringer I have rebased onto the latest origin/master and verified that all of these build:

```
λ brh nixpkgs →  nix build -L -f . adoptopenjdk-icedtea-web firefox-esr-68-unwrapped xulrunner mozplugger slimerjs thunderbird
λ brh nixpkgs →  ll result*
lrwxrwxrwx 1 bhipple users 74 Mar 15 18:20 result -> /nix/store/hvl1hg5r7mjphqllnyhgbqvb4yjawadr-adoptopenjdk-icedtea-web-1.8.3
lrwxrwxrwx 1 bhipple users 75 Mar 15 18:20 result-1 -> /nix/store/z0fn853hxf358zb41lsrqdqlfjg0kyk3-firefox-esr-unwrapped-68.6.0esr
lrwxrwxrwx 1 bhipple users 66 Mar 15 18:20 result-2 -> /nix/store/2pkpkzn75xqyqgsg0sxdcwr03f1laysa-firefox-unwrapped-74.0
lrwxrwxrwx 1 bhipple users 60 Mar 15 18:20 result-3 -> /nix/store/ga6n65nk4a7sw0lwj9dnqq3m22q7li9m-mozplugger-2.1.6
lrwxrwxrwx 1 bhipple users 58 Mar 15 18:20 result-4 -> /nix/store/lrnjp2ll3m8c1pjx2xh8qzpd608i22py-slimerjs-1.0.0
lrwxrwxrwx 1 bhipple users 62 Mar 15 18:20 result-5 -> /nix/store/s3kd4vair2b49phb8wr8kp4p2zs7wql6-thunderbird-68.6.0
```
This builds both firefox and the extended support version of firefox, so it takes a very long time and uses a huge amount of RAM. My suspicion is that the original `nixpkgs-review` just died for something like OOM killer on g++, or perhaps the rebase has fixed it.  At any rate, I think this is now good for merging.

**Pull request merged**
