### PR TITLE
yarGen: don't depend on scandir

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/119998#issuecomment-825289566

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
@cole-h Please check whether https://github.com/Neo23x0/yarGen/pull/33 actually works.

**Comment by cole-h** [comment]
LGTM, but could you also apply the following patch? I missed this in my original PR: yarGen was intended to be run with just `python yarGen.py` (e.g. in a writable directory) with a `dbs` directory accessible -- this doesn't work when installed to the Nix store.

```patch
From 70c4f0bb893c985a0d19b73ea9c734c516ae5495 Mon Sep 17 00:00:00 2001
From: Cole Helbling <cole.e.helbling@outlook.com>
Date: Thu, 22 Apr 2021 23:21:44 -0700
Subject: [PATCH] yarGen: get dbs dir from cwd

---
 pkgs/tools/security/yarGen/default.nix          |  2 ++
 pkgs/tools/security/yarGen/use-cwd-for-dbs.diff | 13 +++++++++++++
 2 files changed, 15 insertions(+)
 create mode 100644 pkgs/tools/security/yarGen/use-cwd-for-dbs.diff

diff --git a/pkgs/tools/security/yarGen/default.nix b/pkgs/tools/security/yarGen/default.nix
index 1cbf736bd26..644b17f29de 100644
--- a/pkgs/tools/security/yarGen/default.nix
+++ b/pkgs/tools/security/yarGen/default.nix
@@ -16,6 +16,8 @@ python3.pkgs.buildPythonApplication rec {
   };
 
   patches = [
+    # don't try to read dbs from $out/bin
+    ./use-cwd-for-dbs.diff
     # https://github.com/Neo23x0/yarGen/pull/33
     (fetchpatch {
       name = "use-built-in-scandir.patch";
diff --git a/pkgs/tools/security/yarGen/use-cwd-for-dbs.diff b/pkgs/tools/security/yarGen/use-cwd-for-dbs.diff
new file mode 100644
index 00000000000..22c5644d258
--- /dev/null
+++ b/pkgs/tools/security/yarGen/use-cwd-for-dbs.diff
@@ -0,0 +1,13 @@
+diff --git a/yarGen.py b/yarGen.py
+index a76dc2d..bfb9077 100644
+--- a/yarGen.py
++++ b/yarGen.py
+@@ -84,7 +84,7 @@ KNOWN_IMPHASHES = {'a04dd9f5ee88d7774203e0a0cfa1b941': 'PsExec',
+ 
+ 
+ def get_abs_path(filename):
+-    return os.path.join(os.path.dirname(os.path.abspath(__file__)), filename)
++    return os.path.join(os.getcwd(), filename)
+ 
+ 
+ def get_files(dir, notRecursive):
-- 
2.30.1

```

**Comment by dotlambda** [comment]
@cole-h I suggest you file that patch upstream first. Apart from that, feel free to push to my branch.

**Review by cole-h — APPROVED** [review]
LGTM.

(I'll do my patching separately)

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 120303 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>1 package built:</summary>  <ul>    <li>yarGen</li>  </ul></details>

**Pull request merged**
