### PR TITLE
influxdb2: 2.0.2 -> 2.0.6 [ZHF]

### PR DESCRIPTION
**Pull request by avdv**
###### Motivation for this change

The build of influxdb2 was failing while building libflux because of some Rust changes:

```
commit 6f73a8570ca0cb6d567e8eaebc59293f12bb7483
Author: Arthur Gautier <baloo@superbaloo.net>
Date:   Thu Mar 25 18:03:40 2021 +0000

    rust: 1.50.0 -> 1.51.0
```

```
error: panic message is not a string literal
  --> src/core/ast/flatbuffers/tests.rs:89:28
   |
89 |             assert!(false, e);
   |                            ^
   |
note: the lint level is defined here
  --> src/core/lib.rs:1:38
   |
1  | #![cfg_attr(feature = "strict", deny(warnings, missing_docs))]
   |                                      ^^^^^^^^
= note: `#[deny(non_fmt_panic)]` implied by `#[deny(warnings)]`
= note: this is no longer accepted in Rust 2021
help: add a "{}" format string to Display the message
   |
89 |             assert!(false, "{}", e);
   |                            ^^^^^
```

Upstream fixed this in libflux with commit https://github.com/influxdata/flux/commit/3a89cfc6980d31cf5d9b5a998c2d7a1f2eb1920b

ZHF: #122042

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by avdv** [comment]
ping @NixOS/nixos-release-managers

**Comment by timstott** [comment]
Result of `nixpkgs-review pr 122973` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>influxdb2</li>
  </ul>
</details>

**Review by timstott — APPROVED** [review]

**Comment by stephank** [comment]
Additional changes to fix the Darwin build: https://github.com/stephank/nixpkgs/commit/49a79d66c864fa10ac671532b463c07e059c1460

**Comment by avdv** [comment]
@stephank Thank you! I have integrated your patch into this PR.

**Comment by jonringer** [comment]
please resolve conflicts

**Comment by avdv** [comment]
@jonringer done

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 122973 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>1 package built:</summary>  <ul>    <li>influxdb2</li>  </ul></details>

**Pull request merged**
