### PR TITLE
fish: fix hidden dependency on ul(1) on Linux

### PR DESCRIPTION
**Pull request by edef1c**
This is used in __fish_print_help, which is used for displaying all the
online documentation in fish.

### CODE REVIEW

**Comment by zimbatm** [comment]
What is the __fish_print_help command supposed to do ? I'm getting some sort of noop:

```
$ nix-shell -p fish -p utillinuxCurses --pure --run fish
> __fish_print_help
>
```

**Comment by tsion** [comment]
@zimbatm It's used internally to print help messages for fish builtins. Compare `__fish_print_help echo` and `echo -h`.

**Comment by zimbatm** [comment]
Ok I can reproduce the issue now. Can you just use `substituteInPlace` instead of `sed` ? After a bit of testing this could be merged quite quickly.

**Comment by nathan7** [comment]
@zimbatm How's this?

**Comment by zimbatm** [comment]
@nathan7 almost, it looks like utillinuxCurses has been renamed to utillinux

**Comment by zimbatm** [comment]
It looks like __fish_print_users depends on /usr/bin/getent if you want to fix that as well

**Comment by zimbatm** [comment]
```
$ cd /nix/store/5shwcd178vdmsbl1xgrvwj57m2myja6g-fish-2.2.0/share && grep -r /bin/ . | grep -v /nix/store
./fish/completions/netcat.fish:complete -r -c nc -s c -d "Same as -e, but use /bin/sh"
./fish/completions/duply.fish:complete --command duply --no-files --condition '__fish_is_first_token' --arguments '(/bin/ls /etc/duply ^/dev/null) (/bin/ls ~/.duply ^/dev/null)' --description 'Profile'
./fish/completions/xrdb.fish:complete -c xrdb -o cpp -r           -d 'preprocessor to use [/usr/bin/mcpp]'
./fish/functions/__fish_complete_users.fish:	if test -x /usr/bin/getent
./fish/functions/__fish_print_users.fish:	if test -x /usr/bin/getent
./fish/functions/__fish_print_users.fish:	else if test -x /usr/bin/dscl # OS X support
./fish/functions/__fish_complete_groups.fish:	if test -x /usr/bin/getent
./fish/functions/help.fish:	# OS X /usr/bin/open swallows fragments (anchors), so use osascript
./fish/functions/__fish_config_interactive.fish:				/usr/bin/command-not-found $argv[1]
./fish/functions/__fish_config_interactive.fish:		else if test -f /run/current-system/sw/bin/command-not-found
./fish/functions/__fish_config_interactive.fish:				/run/current-system/sw/bin/command-not-found $argv
./fish/functions/__fish_print_hostnames.fish:	if test -x /usr/bin/getent
```

**Comment by nathan7** [comment]
@zimbatm Done, and done!

**Comment by zimbatm** [comment]
perfect, thanks

**Pull request merged**
