### PR TITLE
simp_le: Bump to b9d95e862536d1242e1ca6d7dac5691f32f11373

### PR DESCRIPTION
**Pull request by Baughn**
I also created https://github.com/kuba/simp_le/issues/78 to do this in simp_le. I'll send another PR if that resolves.
###### Things done:
- [x] Tested via nixos-rebuild switch
- [X] Built on platform(s): Linux.
- [X] Tested execution of binary products.
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
- [x] Tested compilation of all pkgs that depend on this change.

>  I don't think there are any... but how do I find out?

### CODE REVIEW

**Comment by fpletz** [comment]
:+1: We should definitely support changing SANs for existing certs.

One thing I don't like about this is that a new private key will be generated, but I guess there is no way around that with simp_le. I wonder how much time the simp_le devs will need to release a new version so this hack wouldn't be necessary.

cc @abbradar

**Comment by abbradar** [comment]
Looks good to me at glance, but I haven't tested. This sounds better than doing this manually if used together with (included in the patch already) backing certs up before trying.

**Comment by Baughn** [comment]
They actually added a flag for that already, but I missed it. Or else it isn't in a released version, yes. I'll take a poke at that this weekend, I guess.

**Comment by fpletz** [comment]
Note that simp_le doesn't seem to have released versions according to the github repo and https://github.com/kuba/simp_le/blob/master/setup.py#L9. We should try bumping simp_le to the latest commit on the master branch, add the flag and test if this works.

**Comment by pietroalbini** [comment]
There is no new flag, it's the default behavior now :)

**Comment by Baughn** [comment]
Finally got around to bumping the version. Yep, this works, with no need for fragile shell code.

**Comment by joachifm** [comment]
Maybe also update the version to match the date of the commit?

**Comment by Baughn** [comment]
Whoops.

**Comment by joachifm** [comment]
Would you please change the commit subject to `simp_le: 2016-01-09 -> 2016-02-06`. Let me know and I'll press the green button, unless somebody beats me to it.

**Comment by Baughn** [comment]
@joachifm Did that. It isn't actually release-tagged, though.

**Pull request merged**
