### PR TITLE
autogen: try fixing on darwin

### PR DESCRIPTION
**Pull request by vcunat**
and cause no rebuild elsewhere.
In commit 2988780 I forgot that patchelf makes no sense there.

### CODE REVIEW

**Comment by vcunat** [comment]
@GrahamcOfBorg build autogen
IIRC references to `/build/` shouldn't be a problem on Darwin, but better get some overall verification anyway.

**Comment by FRidh** [comment]
> autogen on x86_64-darwin — Success

**Comment by tomberek** [comment]
Possible lingering issue with RPATH on ARMv7l:
```
checking for references to /tmp/nix-build-autogen-5.18.16.drv-0/ in /nix/store/vkxyf46py2kspqmsl4ivm2wlkcrh1x5f-autogen-5.18.16-bin...
RPATH of binary /nix/store/vkxyf46py2kspqmsl4ivm2wlkcrh1x5f-autogen-5.18.16-bin/bin/autogen contains a forbidden reference to /tmp/nix-build-autogen-5.18.16.drv-0/
builder for '/nix/store/28fqbf4c4k6h3v29s56rxg9lqabzyvcz-autogen-5.18.16.drv' failed with exit code 1
```

**Comment by tomberek** [comment]
This seems to help:
```diff
diff --git a/pkgs/development/tools/misc/autogen/default.nix b/pkgs/development/tools/misc/autogen/default.nix
index 3e634bedfd1..66a56669e4b 100644
--- a/pkgs/development/tools/misc/autogen/default.nix
+++ b/pkgs/development/tools/misc/autogen/default.nix
@@ -65,7 +65,7 @@ stdenv.mkDerivation rec {
   '' + stdenv.lib.optionalString (!stdenv.hostPlatform.isDarwin) ''
     # remove /build/** from RPATHs
     for f in "$bin"/bin/*; do
-      local nrp="$(patchelf --print-rpath "$f" | sed -E 's@(:|^)/build/[^:]*:@\1@g')"
+      local nrp="$(patchelf --print-rpath "$f" | sed -E 's@(:|^)/build/[^:]*:@\1@g' | sed -E 's@(:|^)/tmp/nix-build[^:]*:@\1@g')"
       patchelf --set-rpath "$nrp" "$f"
     done
   '';
```
Sandbox on my ARMv7l is set to false, so the build path is `/tmp/nix-build-*`

**Comment by vcunat** [comment]
It would be best to "compute" the path that's being used, but it gets more complicated, as the path might contain sed-special characters.

**Comment by tomberek** [comment]
Perhaps be explicit?
```
${stdenv.lib.makeLIbraryPath [ guile boehm glibc]}:$lib/lib
```

**Pull request merged**
