### PR TITLE
nvidia_x11: 2020.09 - 2020.10

### PR DESCRIPTION
**Pull request by eadwu**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by starcraft66** [comment]
Will this be merged into nixos-20.09?

**Comment by vcunat** [comment]
I personally don't see motivation to pick such major-branch updates into 20.09 at this point.

**Comment by arcnmx** [comment]
This being the only driver version that [supports the new GPUs](https://www.nvidia.com/download/driverResults.aspx/165689/en-us) released last month seems like pretty good motivation ><

**Comment by vcunat** [comment]
450 branch is long-lived.  IIRC they do backport new GPU support into such branches.

**Pull request merged**
