### PR TITLE
GNOME updates 2024-12-07

### PR DESCRIPTION
**Pull request by bobby285271**
- In case you review upstream changelogs from the [GitHub mirror](https://github.com/GNOME/), the GitLab -> GitHub sync is down (?) after the [migration](https://discourse.gnome.org/t/scheduled-maintenance-gitlab-gitlab-pages-04th-of-december-2024-at-2-pm-utc/25271) so the Mutter 47.3 tag is only available on gitlab.g.o
- I keep seeing downstream fixes for https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/7836 I think it will be an annoying task for us when we need to do GTK 4.18 bump

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

@jtojnar

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg test gnome
@ofborg build mutter loupe localsearch gtranslator gnome-user-docs gnome-user-share gnome-shell-extensions gnome-shell gnome-settings-daemon gnome-remote-desktop gnome-music gnome-online-accounts gnome-initial-setup gnome-control-center glycin-loaders

**Comment by philiptaron** [comment]
Need any system testers, Bobby (@bobby285271)?

**Review by jtojnar — COMMENTED** [review]
- Upstream diffs look okay.
- Tested it for a bit in a VM.
- Opened https://gitlab.gnome.org/Infrastructure/Infrastructure/-/issues/1825 for the mirror being out of date

**Review by jtojnar — APPROVED** [review]
LGTM, thanks.

**Comment by bjornfor** [comment]
Shouldn't this be backported to release-24.11? (I know https://github.com/NixOS/nixpkgs/issues/361163 isn't fixed by this update, but I have hopes it will be part of a 47.x update soon.)

**Comment by bjornfor** [comment]
@jtojnar: I made a PR with manual cherry-picks here: https://github.com/NixOS/nixpkgs/pull/365374

**Pull request merged**
