### PR TITLE
python3Packages.pyls-mypy: remove

### PR DESCRIPTION
**Pull request by JamieMagee**
###### Description of changes

Remove `pyls-mypy`

[`pyls-mypy`](https://github.com/tomv564/pyls-mypy) depends on the deprecated [`palantir/python-language-server`](https://github.com/palantir/python-language-server). nixpkgs doesn't package the `palantir` version, instead we package [`microsoft/python-language-server`](https://github.com/microsoft/python-language-server). I don't know if they are interchangable, but regardless, `pyls-mypy`, `palantir/python-language-server`, and `microsoft/python-language-server` are all deprecated.

The replacement for `palantir/python-language-server` and `microsoft/python-language-server` is [`python-lsp-server`](https://github.com/python-lsp/python-lsp-server) which is [already in nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/python-lsp-server/default.nix). The replacement for `pyls-mypy` is [`pylsp-mypy`](https://github.com/python-lsp/pylsp-mypy) and [is also already available in nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/pylsp-mypy/default.nix)

Related to #209585

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by GGG-KILLER** [comment]
I don't know what the usual procedure for obsoleting packages in favor of others is, but instead of outright removing the attribute, wouldn't it be better to add an error message telling people who use `pyls-mypy` to use `pylsp-mypy` instead?

**Comment by JamieMagee** [comment]
I added an alias with a note.

**Comment by ajs124** [comment]
needs a rebase, but otherwise LGTM.

if you want to, you can add the nice and detailed explanation you wrote in the description (thanks for doing that btw) of this PR to the commit message.
that way, if someone finds the removal in the git history, they don't need to go to github to figure out the reasoning.

**Comment by JamieMagee** [comment]
Rebased and added the explanation from the PR to the commit message

**Comment by JamieMagee** [comment]
Result of `nixpkgs-review pr 209582` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by ajs124** [comment]
needs another rebase. presumably after the merge of #209585

**Comment by ajs124** [comment]
no merge commits please. I'll merge this after CI passes, if there aren't any objections.

**Pull request merged**
