### PR TITLE
Add command to switch to root to the installation guide

### PR DESCRIPTION
**Pull request by kvark**
###### Motivation for this change

Installation guide assumed you are root but didn't explain how to get there. And it's not obvious.
I think it's a real issue with the guide right now, could be a blocker for some people.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kvark** [comment]
I'm sorry, I don't know what the manual CI check is complaining about.

**Comment by figsoda** [comment]
It's complaining that xml and markdown docs are out of sync, running `nixos/doc/manual/md-to-db.sh` should fix the issue

**Review by Atemu — APPROVED** [review]
CI fail is on master (dunno how that got in), this LGTM!

**Review by figsoda — APPROVED** [review]

**Comment by r-burns** [comment]
Changes LGTM and CI is happy now. Let's get this merged

**Pull request merged**
