### PR TITLE
Add Zettlr

### PR DESCRIPTION
**Pull request by beardhatcode**
###### Motivation for this change
I wanted to use my favourite markdown editor.

###### Questions

Use some fonts are missing when exporting to PDF at the moment.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"` (new package, no packages depend)
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by beardhatcode** [comment]
It seems there is already a zettlr in the misc folder.

https://github.com/NixOS/nixpkgs/blob/e4c978dbddfedcc7af03d3ddfdfc0890dceaf8e0/pkgs/applications/misc/zettlr/default.nix

**Comment by beardhatcode** [comment]
@tfmoraes, could you take a peek at this PR?
Do you think we could add the pandoc and latex stuff to your zettlr.nix ? 

I don't know if it is easy to also substitute the electron in the appimage with the nix electron. Do you ave any insights on that?

**Comment by tfmoraes** [comment]
Hi @beardhatcode. I've created a branch to try to package Zettlr directly from source code using yarn2nix. See it here https://github.com/tfmoraes/nixpkgs/tree/zettlr-1.7.5_yarn . It's launching Zettlr but the GUI doesn't seem correct.

**Comment by beardhatcode** [comment]
i took a look at it. The reason I used the deb rather than the repo was because the deb is the result of `yarn run release:linux`. This step creates a asar file which basically contains all the JavaScript except electron (and pandoc), so that is convenient.

I took a look at your code, and it might be because you are using `electron` instead of `electron_9`. I can't try it myself atm.

**Pull request closed without merging**
