### PR TITLE
thunderbird, thunderbird-bin: 78.2.2 -> 78.3.0 [High security fix]

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

- High security fix
- Other changes, including features relating to OpenPGP

https://www.thunderbird.net/en-US/thunderbird/78.3.0/releasenotes/
https://www.mozilla.org/en-US/security/advisories/mfsa2020-44/

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by charvp** [comment]
According to [this blog post](https://blog.thunderbird.net/2020/09/openpgp-in-thunderbird-78/) this is the version that users still on Thunderbird 68 should update to. OpenPGP support is enabled by default and Thunderbird 68 will no longer receive security fixes after September 2020. If I read https://github.com/NixOS/nixpkgs/pull/93227 correctly the 68 package should be dropped now?

**Comment by vcunat** [comment]
I'd prefer to leave some delay between switching defaults and dropping 68.

**Comment by vcunat** [comment]
78.3.0 has been withdrawn for now, apparently.

**Comment by taku0** [comment]
Now it is released.
https://www.thunderbird.net/en-US/thunderbird/releases/

**Comment by vcunat** [comment]
There's 78.3.1 now, so I suppose we skip to that directly.

**Review by vcunat — APPROVED** [review]
Both seem to work fine for me.

**Comment by vcunat** [comment]
I'll be now trying them out when backported to 20.0x.

**Comment by vcunat** [comment]
Default branch switched in 2be22836b1b.

**Pull request merged**
