### PR TITLE
jackaudio: 1.9.10 -> 1.9.11-RC1

### PR DESCRIPTION
**Pull request by magnetophon**
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by cillianderoiste** [comment]
We discussed this on IRC. There hasn't been a jack2 release in 3 years, and this version is considered stable except that they need to fix Windows and OsX builds before cutting a final release: http://jack-audio.10948.n7.nabble.com/Jack-Devel-JACK2-1-9-11-RC1-is-now-tagged-td19490.html

If that doesn't happen, and this version is adopted by mainstream audio distros i.e. it becomes a de-facto release, then I'd be happy to include it in nixpkgs, but personally, I would like to wait a bit for things to settle down.

**Comment by magnetophon** [comment]
@cillianderoiste The current maintainer is also the creator of KXstudio, and has [confirmed](https://github.com/jackaudio/jack2/issues/220#issuecomment-309080847) it's safe:
jack-git has been part of KXstudio for several months.

**Comment by cillianderoiste** [comment]
@magnetophon Ah, if KXStudio has been using it for months, then I think it's fine. Can you delete the jack-gcc5.patch file too please? Do you think we need to keep jack2Unstable at all? I see it's only used in libsoundio, so I guess that can use 1.9.11-RC1 instead?

**Comment by magnetophon** [comment]
@cillianderoiste OK, done.

**Comment by cillianderoiste** [comment]
Excellent, thanks @magnetophon!

**Comment by magnetophon** [comment]
@cillianderoiste The pleasure is all mine. For way too long I had a jack override to unstable, so I had to compile *a lot* of stuff on each upgrade.
Soon, no more!

**Pull request merged**
