### PR TITLE
openapi-generator-cli{-unstable}: move to `-bin`

### PR DESCRIPTION
**Pull request by Profpatsch**
These two packages are not built from source, which is customarily
done by suffixing them with `-bin`, until we can provide a from-source
build.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
There is no convention that adds ``-bin`` to packages that are not build from source. This is only done if there are two package with the same name and one is build from source.

**Comment by Profpatsch** [comment]
> Also this should be tracked through meta ideally to avoid many unnecessary renames and throws for people.

how would that work?

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126363` at e36ed8cc run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>openapi-generator-cli-bin</li>
    <li>openapi-generator-cli-unstable-bin</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
> > Also this should be tracked through meta ideally to avoid many unnecessary renames and throws for people.
> 
> how would that work?

We would need to add a new attribute (maybe ``meta.binary = true``?) which would work similar meta.allowAliases or unfree licenses in blocking the installation of binary distributed packages.

**Pull request closed without merging**
