### PR TITLE
Newer haskell cmdlib version 0.3.6 is no longer marked as broken.

### PR DESCRIPTION
**Pull request by kquick**

### CODE REVIEW

**Comment by kquick** [comment]
@peti: here's the better fix for the new cmdlib version.

**Comment by peti** [comment]
When I format several packages into a paragraph like this, then these overrides are usually related to each other. In this particular case, ` darcs-fastconvert` etc. have been disabled because they depend on the broken `cmdlib` library. When that override for `cmdlib` is removed, then the overrides for the other packages should be removed as well.

By the way, I trust you've tested that `cmdlib` actually compiles?

**Comment by kquick** [comment]
cmdlib does compile.

darcs-fastconvert does not compile: the hashed-storage dependency fails to compile.  I'm not sure of the intent of the "dontDistribute" marker (disable hydra builds?); should that be converted to markBroken, or do you no longer wish to use the latter?

The ivory packages do not compile: haskell-ivory has duplicate instance declarations. This is also marked dontDistribute.

The laborantin-hs package does not compile.  This is also marked dontDistribute.

Unless you would prefer that I update any of the above to be markBroken instead of dontDistribute, I don't think there's anything else that should be included in this patch.

**Comment by peti** [comment]
Thank you very much for your efforts! I have the patch in my `haskell-updates` branch, and I'll merge to `master` soon.

**Pull request closed without merging**
