### PR TITLE
elfutils: 0.174 -> 0.175, clean a bit, fix and enable tests and hardening

### PR DESCRIPTION
**Pull request by dtzWill**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by c0bw3b** [comment]
I'm seeing this PR after I merged #50797 so the version bump is done in staging already.

Regarding build checks: there is still one failing on aarch64 -> `FAIL: run-backtrace-native.sh`

The rest LGTM (removing bzip2, keeping format hardening, support for PaX flags)

**Comment by c0bw3b** [comment]
The patch to support PaX flags should be fetched from:
https://bugs.gentoo.org/attachment.cgi?id=74902&action=diff&collapsed=&headers=1&format=raw

**Comment by dtzWill** [comment]
I think "yes" but just checking--do we still want to include support for PaX flags here?

**Comment by dtzWill** [comment]
I think that fixes the aarch64 test situation? :)

**Comment by Ekleog** [comment]
@dtzWill Any reason for not merging?

**Comment by doronbehar** [comment]
Please close this, `elfutils`' current version in master is 0.176.

**Pull request closed without merging**
