### PR TITLE
radare2: cross-build

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg build radare2

**Comment by timokau** [comment]
This broke the radare2-cutter build:

```
In file included from /nix/store/5wbr8krll8l03kcb6ibhfyshz5mbr2hy-radare2-2018-10-07/include/libr/r_core.h:8:0,
                 from Cutter.h:4,
                 from MainWindow.h:6,
                 from CutterApplication.h:8,
                 from Main.cpp:2:
/nix/store/5wbr8krll8l03kcb6ibhfyshz5mbr2hy-radare2-2018-10-07/include/libr/r_magic.h:20:10: fatal error: magic.h: No such file or directory
 #include <magic.h>
          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:2041: Main.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from /nix/store/5wbr8krll8l03kcb6ibhfyshz5mbr2hy-radare2-2018-10-07/include/libr/r_core.h:8:0,
                 from ./Cutter.h:4,
                 from utils/Configuration.h:6,
                 from Cutter.cpp:8:
/nix/store/5wbr8krll8l03kcb6ibhfyshz5mbr2hy-radare2-2018-10-07/include/libr/r_magic.h:20:10: fatal error: magic.h: No such file or directory
 #include <magic.h>
          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:2050: Cutter.o] Error 1
In file included from /nix/store/5wbr8krll8l03kcb6ibhfyshz5mbr2hy-radare2-2018-10-07/include/libr/r_core.h:8:0,
                 from ./Cutter.h:4,
                 from ./utils/Configuration.h:6,
                 from utils/RichTextPainter.cpp:4:
/nix/store/5wbr8krll8l03kcb6ibhfyshz5mbr2hy-radare2-2018-10-07/include/libr/r_magic.h:20:10: fatal error: magic.h: No such file or directory
 #include <magic.h>
          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:2072: RichTextPainter.o] Error 1
In file included from /nix/store/5wbr8krll8l03kcb6ibhfyshz5mbr2hy-radare2-2018-10-07/include/libr/r_core.h:8:0,
                 from ./Cutter.h:4,
                 from ./widgets/GraphView.h:16,
                 from widgets/DisassemblerGraphView.h:11,
                 from widgets/DisassemblerGraphView.cpp:1:
/nix/store/5wbr8krll8l03kcb6ibhfyshz5mbr2hy-radare2-2018-10-07/include/libr/r_magic.h:20:10: fatal error: magic.h: No such file or directory
 #include <magic.h>
          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:2064: DisassemblerGraphView.o] Error 1
builder for '/nix/store/vhj3yv30qzyn7kag6sw62zpw1sfkamcs-radare2-cutter-1.7.2.drv' failed with exit code 2
error: build of '/nix/store/vhj3yv30qzyn7kag6sw62zpw1sfkamcs-radare2-cutter-1.7.2.drv' failed
```

**Comment by timokau** [comment]
Adding `file`, `libzip` and `xxHash` to cutters `buildInputs` fixes the build. Not sure if it should be `propagatedBuildInputs` of r2 instead.

**Comment by timokau** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/53667. I have no idea why it is necessary to explicitly propagate these libraries though. Doesn't that usually work automatically?

**Comment by Mic92** [comment]
That would happen automatically if radare2's pkgconfig file would define a dependency on the libraries, i.e. add include paths.

**Pull request merged**
