### PR TITLE
Add support for building on Mac OS X 10.10 (Yosemite)

### PR DESCRIPTION
**Pull request by jwiegley**
These changes are unfortunately rather numerous, but they are nearly all of the remaining fixes necessary to enable building on both 10.9 and 10.10 (I have tested building several hundred packages on both platforms).  Please review as much as you are able to, as it's possible that unintentional and unnecessary changes may have made it past my review.

Pinging @peti @shlevy @edolstra @joelteon @gridaphobe @copumpkin.

### CODE REVIEW

**Comment by jwiegley** [comment]
Note: My apologies that this a single monstrous commit, but I was not familiar enough with the incorporated changes to know which could be grouped together, and in what sequence.

**Comment by jwiegley** [comment]
A few minor Yosemite issues I know of which are not addressed in this commit (we have workarounds on our local branch that are not yet suitable for submission):

 - There are changes needed to at least 4 Haskell packages, but those changes need to go through `cabal2nix`.
 - `wget` fails its tests on Yosemite.
 - `bup` fails to build (demanding `gcc`), which causes `git-annex` to fail to build.

**Comment by gridaphobe** [comment]
@jwiegley I think we can drop the patches to `firefox`, `thunderbird`, and `gcc`, as none of them should be building on darwin in the first place.

**Comment by jwiegley** [comment]
@gridaphobe Feel free to match whatever changes you see fit and push them to this branch.

**Comment by gridaphobe** [comment]
Can someone with experience in python-on-nix comment on the changes to `python-packages.nix`, `python-packages.json`, and `python-packages-generated.nix`? It all seems a bit redundant, so I'm not sure if we actually need to patch all three files.

**Comment by shlevy** [comment]
@edolstra FYI, this re-separates clang and gcc wrappers

**Comment by shlevy** [comment]
Actually, I think we should hold off on this until we can integrate those together. It will probably mean a linux stdenv change, but that's OK ultimately.

**Comment by shlevy** [comment]
@jwiegley thoughts?

**Comment by codyopel** [comment]
This really needs to be split into multiple commits/pull requests(clang,llvm,qt5,etc...).  Some of these changes do not appear to be Darwin specific, but are lumped in.  In some cases I can't tell if files are being added or bumped to a new version in a seperate file (clang,qt5,etc...).

**Comment by shlevy** [comment]
Yeah, there is too much to look at here. I know it's hard work (and certainly not something @jwiegley should be expected to do on his own), but we really should chunk this up more.

**Comment by gridaphobe** [comment]
The extra julia, perl, and qt versions can probably be removed, but clang/llvm/libc++ are specifically required for darwin support.

**Comment by jwiegley** [comment]
@codyopel Would you be willing to pull out the things you find that are not Darwin specific, and submit them as separate PRs?  If we're going to break this apart, it needs more hands on it.

**Comment by jwiegley** [comment]
@shlevy I have no thoughts, since I haven't been following the development of the clang and gcc wrappers.

**Comment by jwiegley** [comment]
I'm going to close this pull request until we can come back with a separate one that addresses the GCC and clang wrapper support.  After that, those of us working on the Darwin support will think about how we can bring the changes over in smaller chunks.

**Pull request closed without merging**
