### PR TITLE
vimPlugins: update

### PR DESCRIPTION
**Pull request by timokau**
###### Motivation for this change

Regular update.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by teto** [comment]
Care to bump LanguageClient-neovim or should I prepare another PR ? That release can use neovim floating windows which is neat https://github.com/teto/nixpkgs/commit/95e403272f488417c396f29758115136a961758b

**Comment by timokau** [comment]
Sounds neat! Since that shouldn't generate merge conflicts, eval is nearly done here and its a bit annoying to cherry-pick from a different fork I'd say its easiest you create another PR. Ping me and we should get it merged in no time.

As an aside: How do you notice theses PRs so quickly? This is the second time you've reacted within a couple of minutes.

**Comment by teto** [comment]
I work for the government :p it could have been the IRC bot but it was just a coincidence, was looking for something else.
When I propose a vimPlugins PR, I'll ping you no worry :D

**Comment by timokau** [comment]
> I work for the government

That explains it of course :D

**Pull request merged**
