### PR TITLE
python311Packages.lexilang: init at 1.0.1, python311Packages.libretranslate: 1.5.2 -> 1.5.5

### PR DESCRIPTION
**Pull request by fabaff**
## Description of changes
Fix build (https://hydra.nixos.org/build/246735645)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 282824` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>libretranslate (python311Packages.libretranslate)</li>
    <li>libretranslate.dist (python311Packages.libretranslate.dist)</li>
    <li>python311Packages.lexilang</li>
    <li>python311Packages.lexilang.dist</li>
    <li>python312Packages.lexilang</li>
    <li>python312Packages.lexilang.dist</li>
  </ul>
</details>

**Comment by misuzu** [comment]
Translation works, but language detection is broken, logs:
```
Running on http://0.0.0.0:5000
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 2
WARNING:waitress.queue:Task queue depth is 2
WARNING:waitress.queue:Task queue depth is 1
Compiling database...
[Errno 2] No such file or directory: '/nix/store/wwknzccd07xfxjv03c59xfv5x8z45sqi-python3.11-lexilang-1.0.1/lib/python3.11/site-packages/dictionaries/afrikaans.txt'
```

**Comment by Izorkin** [comment]
Package added in upstream, Update this PR?

**Comment by fabaff** [comment]
> Translation works, but language detection is broken, logs:

Seems to work for me. But no expert on `libretranslate` here.

```bash
$ ./result/bin/libretranslate --host 0.0.0.0
Updating language models
Found 86 models
Downloading Albanian → English (1.9) ...
Downloading Arabic → English (1.0) ...
[....]
```

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 282824` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>libretranslate (python311Packages.libretranslate)</li>
    <li>libretranslate.dist (python311Packages.libretranslate.dist)</li>
    <li>python311Packages.lexilang</li>
    <li>python311Packages.lexilang.dist</li>
    <li>python312Packages.lexilang</li>
    <li>python312Packages.lexilang.dist</li>
  </ul>
</details>

**Comment by misuzu** [comment]
> Seems to work for me. But no expert on `libretranslate` here.

Request:
```
% curl 'http://0.0.0.0:5000/detect' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'q=guten%20morgen'

[{"confidence":0.0,"language":"en"}]
```

Logs:
```
Running on http://0.0.0.0:5000
Compiling database...
[Errno 2] No such file or directory: '/nix/store/r1k8wqws2bcdw5s8bkh46b6f6x3fyamq-python3.11-lexilang-1.0.1/lib/python3.11/site-packages/dictionaries/afrikaans.txt'
```

**Comment by Izorkin** [comment]
Draft patch:
```diff
diff --git a/pkgs/development/python-modules/lexilang/default.nix b/pkgs/development/python-modules/lexilang/default.nix
index 5bd64ae8b760..953b2d733d1f 100644
--- a/pkgs/development/python-modules/lexilang/default.nix
+++ b/pkgs/development/python-modules/lexilang/default.nix
@@ -34,6 +38,11 @@ buildPythonPackage rec {
     "lexilang"
   ];

+  postCheckPhase = ''
+    cp -r $src/dictionaries/ $out/lib/python3.11/site-packages/
+    ls -lah $TMP/source/lexilang/data/
+  '';
+
   meta = with lib; {
     description = "Dictionary-based language detector for short texts";
     homepage = "https://github.com/LibreTranslate/LexiLang";
```
Error:
```
Compiling database...
Serializing...
[Errno 2] No such file or directory: '/nix/store/2nn9gdlh5ia57kihqdjprhvr4f11zql8-python3.11-lexilang-1.0.1/lib/python3.11/site-packages/lexilang/data/words.pickle'
2024-02-21 09:25:42 WARNING: Language en package default expects mwt, which has been added
WARNING:stanza:Language en package default expects mwt, which has been added
```

Also need to add `words.pickle` file.

**Comment by Izorkin** [comment]
Any ideas on how to fix it?
```
WARNING: Language en package default expects mwt, which has been added
```

**Comment by Izorkin** [comment]
is there progress?

**Comment by wegank** [comment]
Done in #281850 and #295068.

**Pull request closed without merging**
