### PR TITLE
vimPlugins.vim-easyclip: init at 2019-02-18

### PR DESCRIPTION
**Pull request by Aptrug**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 101998` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vimPlugins.vim-clap</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Can you please fix the merge conflict and only commit the new plugin instead of all the updates?

**Comment by jonringer** [comment]
> Can you please fix the merge conflict and only commit the new plugin instead of all the updates?

I believe the script does this automatically, however, it can be dropped before creating the PR

**Comment by Aptrug** [comment]
The thing is, I cannot merge conflicts since I deleted nixpkgs repository fork after I discovered that I can just install missing Vim plugins with home-manager using something like this:

```
  neovim = {
    plugins = let customPlugins = {
      vim-easyclip = pkgs.vimUtils.buildVimPlugin {
        pname = "vim-easyclip";
        version = "2019-02-18";
        src = pkgs.fetchFromGitHub {
          owner = "svermeulen";
          repo = "vim-easyclip";
          rev = "f1a3b95463402b30dd1e22dae7d0b6ea858db2df";
          sha256 = "1y308y4czdzj9ppb0pnc8mkdd393wpwpncvki88aphicjzvw4498";
        };
        meta.homepage = "https://github.com/svermeulen/vim-easyclip/";
      };
    }; in
      with pkgs.vimPlugins // customPlugins; [
        vim-easyclip
      ];
  };
```

So I'm closing this. Sorry for the noise.

**Pull request closed without merging**
