### PR TITLE
tortoisehg: 3.7.1 -> 3.7.3, refactor

### PR DESCRIPTION
**Pull request by danbst**
###### Things done
- [ ] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This updates TortoiseHg to 3.7.3 and adds alternative fix for #13523 and #13507. If upstream fixes [bug with setup.py](https://bitbucket.org/tortoisehg/thg/issues/4483/problems-with-setuppy-on-posix-systems), we can then remove the custom install phase entirely.

Ping @dckc @FRidh @joachifm as potentially interested persons.

### CODE REVIEW

**Comment by danbst** [comment]
Also, an open question - how to ensure that `TortoiseHg` matches it's `mercurial` version, to prevent failures like #14481. Current thoughts:
- add a comment to `mercurial` package: "when updating, update tortoisehg too"
- assert `tortoisehg` version equals mercurial version. This is really the case for `tortoisehg`
- show warning when versions do not match
- package `mercurial` of specific version for tortoisehg. This conflicts with policy of nixpkgs, but IMHO we should have several versions of mercurial available. For example, `mercurial` versions 3.5+ up to 3.7 had partially broken support for largefiles on windows (client side)

**Comment by FRidh** [comment]
1. Indeed, such comment is always good to add. Or instead when updating mercurial cc the maintainer of tortoisehg
2. assertion is a good idea
3. not needed when assertion is added 
4. if someone needs an older version, then that older version can be kept. You will have to maintain it then though

**Comment by danbst** [comment]
@FRidh, I'm not an active commiter to nixpkgs, so I don't know which path to choose. Can you suggest the right way to choose?
2. my understanding is that assertion will prevent overriding of package with alternative mercurial (they are sometimes compatible).

**Comment by joachifm** [comment]
@danbst go with options 1 and 2.

I'd say worry about using an alternative mercurial when that need arises.

**Comment by danbst** [comment]
Also, this fix or in #13523 should go to `nixos-16.03` channel, because it has mercurial 3.7.3 and tortoisehg 3.6, a broken setup for tortoisehg. Didn't test though...

**Comment by joachifm** [comment]
I think it makes sense to squash these, when you're ready to merge.

**Comment by danbst** [comment]
@joachifm ready

**Comment by joachifm** [comment]
Ah, sorry, I didn't realize this also bumped mercurial. Would you mind splitting into one commit per bump?

**Comment by danbst** [comment]
@joachifm ready

**Comment by joachifm** [comment]
Thank you

**Comment by joachifm** [comment]
Pushed to release at b991fc6e88d422e27b53ba84b31a702ca2ae9c8c
I've tested that it at least runs & is able to create a repository.

**Pull request merged**
