### PR TITLE
woomer: init at 0.1.0

### LINKED ISSUE #346377: Package request: woomer
**Project description**

Zoomer application for wayland (linux) inspired by [tsoding's boomer](https://github.com/tsoding/boomer).

It lets you zoom into the screen to show things.

**Metadata**

* source URL: https://github.com/coffeeispower/woomer
* license: MIT
* platforms: linux

Thankfully there's a flake for it already. I just don't quite know how to add it to nixpkgs.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by getchoo**
[Woomer](https://github.com/coffeeispower/woomer) is a zoomer application for Wayland inspired by tsoding's boomer

Closes #346377
CC @wildwestrom to test as I haven't had the time to just yet

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by wildwestrom** [comment]
Result of `nixpkgs-review pr 346394` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>woomer</li>
  </ul>
</details>

**Comment by bloxx12** [comment]
Tested on Hyprland using `nixpkgs-review pr 346394`, works flawlessly.

**Comment by Scrumplex** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 346394`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>woomer</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>woomer</li>
  </ul>
</details>

**Comment by Scrumplex** [comment]
build failure on aarch64: https://gist.github.com/Scrumplex/9ceccf624b8f743fdc9ef85888da6eda

**Comment by getchoo** [comment]
Looks like this is https://github.com/raylib-rs/raylib-rs/issues/74. Not much we can do here until raylib makes a release with the possible fix

**Comment by Scrumplex** [comment]
> Looks like this is [raylib-rs/raylib-rs#74](https://github.com/raylib-rs/raylib-rs/issues/74). Not much we can do here until raylib makes a release with the possible fix

In that case, we should mark this as broken on aarch64 (Linux)

**Review by Aleksanaa — APPROVED** [review]

**Review by Scrumplex — APPROVED** [review]

**Pull request merged**
