### PR TITLE
vlc: live555 library for streaming

### PR DESCRIPTION
**Pull request by nullie**
I've tested this on my system.

I've added live555 library to make vlc support rtsp streams.

### CODE REVIEW

**Comment by nullie** [comment]
Travis check failed due to OOM

**Comment by jagajaga** [comment]
Please fix commit's name (`live555: added package`) to follow our guide in `CONTIBUTING.md`.

**Comment by jagajaga** [comment]
`live555: init ad YYYY-MM-DD`

**Comment by nullie** [comment]
Sorry, inaccurate rebase

**Comment by vcunat** [comment]
The source is 404 already. Don't they provide a stable URL?

**Comment by vcunat** [comment]
Hmm, the best I can see is this github mirror https://github.com/hackeron/live555.

**Comment by nullie** [comment]
Appently some people use http://download.videolan.org/pub/videolan/testing/contrib/live555/

**Comment by vcunat** [comment]
Argh, I forgot these commits on my branch and pushed them together with others by accident.

**Comment by vcunat** [comment]
It's static libs... but I suppose that's fine when we only have a single package using it.

**Comment by nullie** [comment]
Thanks

**Pull request closed without merging**
