### PR TITLE
haskellPackages.mkDerivation: add option to only propagate known pkgConfigModules

### PR DESCRIPTION
**Pull request by sternenseemann**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by maralorn — APPROVED** [review]
Excellent!

Seems to work fine. Have been playing around to fixing more packages ontop of this PR.

This will definitely nudge me into adding pkgConfigModules all over nixpkgs.

**Comment by maralorn** [comment]
I tried fixing more packages in https://github.com/maralorn/nixpkgs/commit/eb3b743cc695a5bf0bb7536c59708ac67204fa57, sadly I am stuck with building `webkit2gtk3-javascriptcore` because of `libthai`. Either I am not adding the pkgConfigModules annotation to the correct libthai package or libthai is not recognized as a dependency all along or something else is going wrong. Either way I don’t get it. Probably just a mistake by me.

**Comment by sternenseemann** [comment]
@maralorn You also need to make sure the packages which we need to propagate from have the annotation, i.e. `pango` in this case (after that, new errors crop up).  I have collected some of your and some new annotations into #247907. That gets rid of the libthai/pango error, but a new one crops up after that (which is likely also fixable).

**Comment by sternenseemann** [comment]
> This will definitely nudge me into adding pkgConfigModules all over nixpkgs.

It would be great if we could default to true for this!

**Pull request merged**
