### PR TITLE
parity: new release 1.10.0

### PR DESCRIPTION
**Pull request by akru**
###### Motivation for this change

Upgrades according to new releases of Parity:

- https://github.com/paritytech/parity/releases/tag/v1.9.5
- https://github.com/paritytech/parity/releases/tag/v1.10.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build parity parity-beta

**Comment by akru** [comment]
I'm not sure where is it failed? @Mic92, what do you think?

**Comment by akru** [comment]
@GrahamcOfBorg build parity parity-beta

**Comment by Mic92** [comment]
@GrahamcOfBorg build parity parity-beta

**Comment by Mic92** [comment]
@akru you can get borg access here: https://github.com/NixOS/ofborg/pull/138

**Comment by akru** [comment]
@GrahamcOfBorg build parity parity-beta

**Pull request merged**
