### PR TITLE
rofi-emoji: init at 2.1.2

### PR DESCRIPTION
**Pull request by cole-h**
This plugin is intended to be supplied to the `rofi` wrapper through an
override:

    pkgs.rofi.override { plugins = [ rofi-emoji ]; }

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Takes inspiration from and relies on https://github.com/NixOS/nixpkgs/pull/83136.

This comes with a script that uses binaries like `notify-send`, `wl-copy`, `xclip`, `xsel`:
https://github.com/Mange/rofi-emoji/blob/61d6a795ef3703c4c5babd7dc861041c4f7d7e50/clipboard-adapter.sh.

~~Should I patch these to be absolute store paths with `substituteAll` (and thus relying on X11 binaries on Wayland and vice-versa), or is it fine as-is? Or is there another solution I haven't though of? I currently don't have any problems, but I'm on Arch and have these binaries in my PATH already.~~

I'm still curious whether or not it's "fine" to rely on the xclip/wl-clipboard binaries unconditionally. Maybe I should add `waylandSupport ? true` and `x11Support ? true` and make them optional (but requiring at least one of those to be set)?

---

To test, run the following:

```
nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/tarball/f0fe89357ea79c8a9fb35876a26f70ce7455cfee -p 'rofi.override { plugins = [ rofi-emoji ]; }' --run 'rofi -show emoji -modi emoji'
```

If you see a rofi window pop up with emoji, it works! Now see if you can select an emoji (with enter) and paste it somewhere. ~~If you can, I likely don't need to substitute the binaries in `clipboard-adapter.sh`; otherwise, I probably will have to.~~

EDIT: Updated the above easy-test command to point to new commits.

### CODE REVIEW

**Review by Ma27 — CHANGES_REQUESTED** [review]
I'd vote for patching all dependencies into the script (e.g. by using `wrapProgram --prefix PATH`). Also, when testing on NixOS, a so-called emoji file can't be found. Maybe a path to it should be fixed as well.

**Comment by cole-h** [comment]
It appears that the reason that file can't be found is that `$out/share` is not a part of `XDG_DATA_DIRS` (`$out/share/all_emojis.txt` is what it wants to find).

I could make a patch that forces the path to be `$out/share/all_emojis.txt` (would also need to be done for the clipboard script), sidestepping the traversal through `XDG_DATA_DIRS` and the need to find a way to wrap it. It feels kinda icky; the alternative is to modify the rofi wrapper itself to prefix the `XDG_DATA_DIRS` with every plugin's `$out/share` path.

Which do you think is more preferable? I lean towards modifying the wrapper, but I'll defer to you (or anybody else who has an opinion on this).

**Comment by cole-h** [comment]
I opted to modify the wrapper. It appears to work for me. (Removed all local `all_emojis.txt` files to hopefully test that this is the case.) I'm no Nix wizard, so maybe my modifications could be improved? Happy to entertain ideas.

**Review by Ma27 — APPROVED** [review]

**Comment by rikhuijzer** [comment]
I'll leave it here since it isn't clearly documented. To install `rofi-emoji` globally on NixOS, use
```
environment.systemPackages = with pkgs; [
  (rofi.override { plugins = [ rofi-emoji ]; })
  [...]
];
```
And to link the emoji picker to, say, `mod+u` in i3wm use
```
bindsym $mod+u exec "rofi -modi emoji -show emoji"
```
With that, pressing `mod+u` will open the emoji picker and pressing `return` on one of the emoji will past it in the active window.

**Pull request merged**
