### PR TITLE
[staging-next] libffi: disable new static trampolines feature

### PR DESCRIPTION
**Pull request by r-burns**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/131928

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-burns** [comment]
Built tracker, pandoc, and cachix

**Review by vcunat — APPROVED** [review]
This sounds like the right approach.  The only complication is that fixes on libffi side cause yet another stdenv rebuild...

**Comment by r-burns** [comment]
Yeah true. Would you prefer this be controlled by a `withStaticTramp ? true` feature? Then we'd only have to disable it for problematic packages such as ghc and gobject-introspection/glib, avoiding the stdenv rebuild. The downside would be some closure bloat when both flavors of libffi are used by dependencies.

**Comment by SuperSandro2000** [comment]
> Yeah true. Would you prefer this be controlled by a `withStaticTramp ? true` feature? Then we'd only have to disable it for problematic packages such as ghc and gobject-introspection/glib, avoiding the stdenv rebuild. The downside would be some closure bloat when both flavors of libffi are used by dependencies.

Do we know if only those packages need it or do we need to hunt them down the next 2 weeks? I'd rather rebuild stdenv than doing a bug hunt.

**Comment by vcunat** [comment]
It would be possible to only only keep the old one during bootstrapping (where it apparently didn't cause any problems) or some other approaches, but I didn't want to complicate this.

**Pull request merged**
