### PR TITLE
dwarfs: 0.6.1 -> 0.6.2

### PR DESCRIPTION
**Pull request by keksbg**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tpwrules** [comment]
This does not build on `aarch64-linux`, looks like due to a regression in folly.

**Comment by keksbg** [comment]
That feels a bit like a hack, although I guess until it gets fixed upstream this is our best bet. I'll wait for others to weigh in on this, though

**Comment by winterqt** [comment]
As long as an upstream issue is filed about this and that's linked in the comment, I think we should be fine.

**Comment by keksbg** [comment]
I'll implement the hack until upstream fixes it and it gets merged into nixpkgs.

**Comment by tpwrules** [comment]
This might be partially our fault: https://github.com/NixOS/nixpkgs/blob/ab8e65a6de403ef1bcd08c04fe27a043820f2eec/pkgs/development/libraries/cxxopts/default.nix#L21

I don't know why that setting doesn't happen or if there's a better way for Folly to check the architecture. There is a comment that CMAKE_LIBRARY_ARCHITECTURE might not be set so clearly they've seen this before but as a consequence defaulting to x86_64 seems weird. I'm not clued into CMake much.

**Comment by keksbg** [comment]
Okay, yeah, I don't understand why they'd default to x86 if the architecture isn't set, that's just weird. https://github.com/facebook/folly/blob/main/CMakeLists.txt#L79-L91

**Comment by MonAaraj** [comment]
Pardon, but I'm not quite sure what the issue here is that's blocking the merge. Is it just aarch64-linux not building? If so, the architecture could be changed to just x86 for now if it's too difficult to make it work for aarch64. Later, a merge request to add support for aarch64-linux could be created, or maybe even right after this one.

**Review by tpwrules — APPROVED** [review]
To be clear, I've just now confirmed that it builds, passes tests, and works on `x86_64-linux` and `aarch64-linux`. But I don't have permission to merge it myself.

FWIW there are lots of PRs and not many people with such permission. I don't consider calling attention to my PRs (e.g. posting on Discourse) unless it's been at least a week or so with no interaction.

**Comment by MonAaraj** [comment]
I don't think it hurts, especially since when I'm calling attention to PRs in their threads, it's because I'm willing to help if things are stunted. Though, it could be annoying to people, in that case, I apologize if it is.

**Comment by tpwrules** [comment]
> I don't think it hurts, especially since when I'm calling attention to PRs in their threads, it's because I'm willing to help if things are stunted. Though, it could be annoying to people, in that case, I apologize if it is.

My comment was in reference to the posting of this PR in the "ready for review" Discourse thread, not your comment in this GitHub thread.

**Pull request merged**
