### PR TITLE
nixos/bind: Support defining the zone file using nix expressions

### PR DESCRIPTION
**Pull request by martiert**
This removes the need to manually write a zone file for bind, and it can instead be defined in nix expressions.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
There are some prior art at https://github.com/kirelagin/dns.nix, which may worth checking.

**Comment by martiert** [comment]
That is a pretty nice library. It would at least make sense to move the creation of the zone file into its own lib, so it can be reused by non-bind daemons.

Or does it make more sense to not put this functionality into nixpkgs itself, and rather have people use that library?

**Comment by NickCao** [comment]
The best path forward would be integrating it into nixpkgs, IMO. Anyway, there are a lot of DNS servers packaged in nixpkgs, having a generic interface not tied to bind benefits them all.

**Comment by martiert** [comment]
Makes sense. I think the easiest and best path would be to integrate the library as a whole then, as it supports a lot more of the DNS entries. I can see if kirelagin wants to upstream it, or has anything against someone else (me) doing that work.

And then we can ignore this PR

**Pull request closed without merging**
