### PR TITLE
perseus-cli: init at 0.3.0

### PR DESCRIPTION
**Pull request by max-niederman**
###### Motivation for this change

[Perseus](https://github.com/arctic-hen7/perseus)

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by legendofmiracles** [comment]
Result of `nixpkgs-review pr 152595` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>perseus-cli</li>
  </ul>
</details>

**Comment by legendofmiracles** [comment]
Depends on wasm-pack at runtime, I've written this diff to fix it: http://0x0.st/oszj.txt

**Comment by max-niederman** [comment]
Nice catch. I only tested actual building in a dev shell with `wasm-pack` already installed, so I didn't notice. I'll update this PR as soon as I'm at my computer.

**Comment by legendofmiracles** [comment]
Can you share the dev shell you used to get a working wasm rust compiler? I'm not very experienced with all the rust tooling, and honestly find it a bit confusing

**Comment by max-niederman** [comment]
AFAIK, there's no way to customize Nixpkgs' Rust toolchain (`pkgs.rustc`, `pkgs.cargo`, etc.), so you have to use third-party overlays like [fenix](https://github.com/nix-community/fenix) or [oxalica/rust-overlay](https://github.com/oxalica/rust-overlay). Alternatively, you can install `rustup` and let _it_ manage your rust toolchain, but it's not very "Nix-y."

I have a `flake.nix` like this:
```nix
{
  inputs = {
    flake-utils.url = "github:numtide/flake-utils";

    nixpkgs.url = "nixpkgs/nixos-unstable";
    fenix = {
      url = "github:nix-community/fenix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, flake-utils, fenix }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        rust = with fenix.packages.${system}; rec {
          wasm = targets.wasm32-unknown-unknown.latest;
          native = latest;
          dev.toolchain = combine [ wasm.toolchain native.toolchain rust-analyzer ];
        };
      in
      {
        devShell = pkgs.mkShell {
          nativeBuildInputs = with pkgs; [
            # Rust
            rust.dev.toolchain
            wasm-pack
          ];
        };
      }
    );
}
```

**Comment by max-niederman** [comment]
Should now work without `wasm-pack` installed seperately. Unfortunately, it does still rely on an ambient `rustc` which supports `wasm32-unknown-unknown`, but I'm not sure much can be done to fix that.

**Review by legendofmiracles — APPROVED** [review]
LGTM and works for me https://i.imgur.com/ehYbOIf.png

**Comment by legendofmiracles** [comment]
@ofborg build perseus-cli

**Comment by legendofmiracles** [comment]
> LGTM and works for me [i.imgur.com/ehYbOIf.png](https://i.imgur.com/ehYbOIf.png)

Just noticed that you didn't apply the patch yet, works with my patch*

**Comment by max-niederman** [comment]
> > LGTM and works for me [i.imgur.com/ehYbOIf.png](https://i.imgur.com/ehYbOIf.png)
> 
> Just noticed that you didn't apply the patch yet, works with my patch*

Yep, I forgot to stage before amending the commit. _Now_ it's fixed.

**Pull request merged**
