### PR TITLE
shotwell: 0.31.3 -> 0.30.14

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change
There have been no new releases in the 0.31.x series for quite a while, and the
last tag of 0.31.3 is currently broken.

This moves us to 0.30.14, since the 0.30.x series is still seeing regular tags
and builds fine.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by superherointj — APPROVED** [review]

**Comment by xunam** [comment]
I'd like to report the same issue as @regnat: I just upgraded NixOS from 21.05 to 21.11 and it appears that Shotwell cannot start anymore because it has been downgraded. I understand the reasons above and the upstream developers are partially at fault, but the resulting situation is problematic. I do have information that I would rather not loose in Shotwell's database, so what is the proper way to proceed now ?

**Comment by equill** [comment]
I have the same issue as @regnat and @xunam - I'm comfortable enough with SQL to mess with that db, but I still need to figure out _what_ changes to make in order to downgrade it. I'd *really* rather not have to re-import and re-tag everything.

The docs (https://wiki.gnome.org/Apps/Shotwell/Architecture/Database) talk about the thinking behind the db design, but give no details. I'll be happy to work with other people to figure this out.

**Comment by lovesegfault** [comment]
I genuinely do not see a way forward other than figuring out how to build 0.31.3 and then making it available under a `shotwell_0_31` attr.

Having looked at shotwell's repo today though, the project seems all but abandoned with essentially no commits in the past year. My recommendation is that users migrate to an alternative tool, like digikam or darktable.

I've been a heavy shotwell user for years, so trust that my recommendation does not come lightly, I'm still working on importing all my pictures into darktable and it's a major PITA.

**Comment by equill** [comment]
That's not an answer I wanted to hear, but it's at least fast, informative and straight to the point.
Thanks; I'll look at the alternatives.

**Comment by equill** [comment]
@lovesegfault FWIW I'm working on automating the migration to Darktable, via https://github.com/equill/Shotwell_migration - my Shotwell DB is far too big to feasibly migrate by hand, and it's about time I learned to drive Lua anyway. It's at an early stage, but feel free to use/fork/adapt it if it looks useful.

**Pull request merged**
