### PR TITLE
rails: init at 6.0.1

### PR DESCRIPTION
**Pull request by waiting-for-dev**
###### Motivation for this change

Adds Ruby on Rails framework. It already exists a `rails` attribute in `rubyPackages` but it is completely outdated. I'm a little puzzled, but I think that the recommended current way of packaging gems is through `bundix`, as this PR does.

References #45980

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by doronbehar** [comment]
Why not update instead? and cc the maintainer?

**Comment by waiting-for-dev** [comment]
Hmmm... honestly I'm a bit confused. Why are there two different ways of packaging ruby packages in the first place? There are ruby applications much less used that rails, for example [taskjuggler](https://github.com/NixOS/nixpkgs/blob/62cb4f72282b228a9072452448b0574170bebc06/pkgs/applications/misc/taskjuggler/default.nix), which are packaged at the top namespace. On the other side, rails is under `rubyPackages_x_x` namespace. On top of that, reading at the docs it seems that [bundix is the current recommended way](https://nixos.org/nixpkgs/manual/#sec-language-ruby). Maybe we should add this package through bundix and depreciate the one in `rubyPackages_x_x`...

**Comment by doronbehar** [comment]
TBH I have less knowledge then you. But, as in other packages sets, such as `pythonPackages`, I think a package you create using `bundix` is added to the `rubyPackages_x_x` set by adding it to a `ruby-packages.nix` file - I think it's this one:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/ruby-packages.nix

**Comment by marsam** [comment]
>In the first place, why are there two different ways of packaging ruby packages?

@waiting-for-dev the ruby section document explain the differences https://github.com/NixOS/nixpkgs/blob/e16df73d3040526fdf5f6a34adae79dedb0387ba/doc/languages-frameworks/ruby.section.md. In this case you need to update the default gemset, in order to update rails.

For rails development, I recommend to use `bundlerEnv` with `nix-shell`

**Comment by waiting-for-dev** [comment]
Thanks for pointing me out that documentation @marsam . TBH I hadn't seen it before.

> In the nixpkgs tree, Ruby packages can be found throughout, depending on what they do, and are called from the main package set. Ruby gems, however are separate sets, and there's one default set for each interpreter (currently MRI only).

I'm still confused... I guess that for Ruby package we understand any Ruby program which hasn't been packed as a gem by its developers... Anyway, I'm not sure it's a consistent differentiation right now. For example, `rubocop` is a gem, and it appears twice in nixpkgs collection: one in [ruby-packages](https://github.com/NixOS/nixpkgs/blob/01e0ef28df82055d53c554452790c9896ec4c649/pkgs/top-level/ruby-packages.nix#L2156) and another one as a [regular package](https://github.com/NixOS/nixpkgs/blob/076860e0340a5e4a909b9a710e186508b14d1c90/pkgs/development/tools/rubocop/default.nix).

**Comment by waiting-for-dev** [comment]
I'm trying to update rails through `./maintainers/scripts/update-ruby-packages` script, while at the same time I'm learning how this process works. Unless I'm missing something I think it works in a very unsustainable way.

According to my understanding, all gems that will be available through `ruby.withPackages` are taken from a [`pkgs/development/ruby-modules/with-packages/Gemfile`](https://github.com/NixOS/nixpkgs/blob/e16df73d3040526fdf5f6a34adae79dedb0387ba/pkgs/development/ruby-modules/with-packages/Gemfile). This basically means that each available gem must be compatible with any other gem listed there, even if you're not going to install it ever.

In this case, trying to update rails doesn't go beyond 4.2 version, only because another listed gem called [cocoapods](https://rubygems.org/gems/cocoapods) depends on activesupport >= 4 < 5, while rails 6 (last version) requires activesupport 6.

I think it's extremely problematic to depend on all gem maintainers keeping its dependencies updated in order to provide updated ruby packages for nix. WDYT?

**Comment by doronbehar** [comment]
Yea well, this is one of those issues with Nixpkgs in general that need attention you might want to get attention for in [NixOS/rfcs](https://github.com/NixOS/rfcs). I don't have a strong opinion here as I'm not familiar with the Rails/Ruby ecosystem in Nixpkgs... Sorry.

**Comment by marsam** [comment]
>Ruby package we understand any Ruby program which hasn't been packed as a gem by its developers

IIUC `bundlerApp` is meant to be used in applications (provides an executable), and rarely is `require`d, `chef` is a good example.
> For example, rubocop is a gem, and it appears twice in nixpkgs 

keep in mind that ` ruby.withPackages` was just recently introduced [last september](https://github.com/NixOS/nixpkgs/pull/61114), and the regular `rubocop` has been there way before.
IMHO we should remove the regular `rubocop`, with the [recent extensions split](https://github.com/rubocop-hq/rubocop/blob/cc7e221b0e4723a75b59c4bd725a5555a13068dd/manual/extensions.md) it became less useful to keep as a single executable.

>I think it's extremely problematic to depend on all gem maintainers keeping its dependencies updated in order to provide updated ruby packages for nix. WDYT?

Agree, this is a general issue when maintaining packagesets in nixpkgs, in {python,haskell}-packages we have to keep only one version of each package.
I use `bundlerEnv` to work with rails at work, and tbh I'm not sure if would be useful to add rails as regular expression to nixpkgs.

cc: @manveru would you mind shedding some light on this

**Comment by waiting-for-dev** [comment]
> I use bundlerEnv to work with rails at work, and tbh I'm not sure if would be useful to add rails as regular expression to nixpkgs.

The only but not minor benefit would be to be able to execute `rails new` when you start a fresh new project. Once the project is created, you don't need it anymore. Right now you have to workaround this creating a `Gemfile` with only rails, then `bundix` + `nix-shell` + `rails new` and `bundix` + `nix-shell` again for the new `Gemfile`, which is a bit of a PAIN :)

**Comment by waiting-for-dev** [comment]
Still important to me

**Comment by floehopper** [comment]
> > I use bundlerEnv to work with rails at work, and tbh I'm not sure if would be useful to add rails as regular expression to nixpkgs.
> 
> The only but not minor benefit would be to be able to execute `rails new` when you start a fresh new project. Once the project is created, you don't need it anymore. Right now you have to workaround this creating a `Gemfile` with only rails, then `bundix` + `nix-shell` + `rails new` and `bundix` + `nix-shell` again for the new `Gemfile`, which is a bit of a PAIN :)

@waiting-for-dev: Have you found a way round the above? I'm still using the workaround you mention above.

**Comment by onny** [comment]
Please rebase

**Pull request closed without merging**
