### PR TITLE
[Backport release-24.05] slskd: 0.21.3 -> 0.21.4

### PR DESCRIPTION
**Pull request by melvyn2**
Manual backport of https://github.com/NixOS/nixpkgs/pull/344958, needed as https://github.com/NixOS/nixpkgs/commit/2641d97cbf96e0b4caf1733edc47cf1298de0960 isn't present in `release-24.05`.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by melvyn2** [comment]
An expected failure since merge conflicts had to be resolved.

**Comment by fpletz** [comment]
The test suite seems to fail on x86_64-linux on ofborg.

**Comment by melvyn2** [comment]
I'm not sure how exactly to troubleshoot this: the exact same derivation (`/nix/store/dgfwg97aqgabsncyk8fi00k0px1j0gnh-slskd-0.21.4.drv`) builds completely normally with all tests passing on my machine.

**Comment by melvyn2** [comment]
@ofborg eval

**Comment by melvyn2** [comment]
@ofborg build slskd

**Comment by getchoo** [comment]
> I'm not sure how exactly to troubleshoot this: the exact same derivation (/nix/store/dgfwg97aqgabsncyk8fi00k0px1j0gnh-slskd-0.21.4.drv) builds completely normally with all tests passing on my machine.

Most likely a flakey test. Seems to be good enough for Ofborg now though and it hasn't been replicated in Hydra yet, so this may be good to merge? But I'd recommend disabling the test(s?) responsible here and in master at some point regardless

**Review by getchoo — APPROVED** [review]

**Pull request merged**
