### PR TITLE
zabbix:1.8 -> 4.0 | remove old packages

### PR DESCRIPTION
**Pull request by PsyanticY**
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by PsyanticY** [comment]
#40015

**Comment by PsyanticY** [comment]
@matthewbauer can you please have a look

**Comment by risicle** [comment]
`nox-review` builds for me, non-nixos linux x86_64

**Comment by AmineChikhaoui** [comment]
@GrahamcOfBorg build zabbix

**Comment by matthewbauer** [comment]
@GrahamcOfBorg build zabbix

**Comment by PsyanticY** [comment]
@matthewbauer  thanks

**Comment by aanderse** [comment]
@PsyanticY @matthewbauer This breaks `zabbix` for anyone who was running it on NixOS as it entirely removes `postgresql` support.

**Comment by PsyanticY** [comment]
@aanderse your right about the possibility that dropping `postgresql` can break  for people using it but there was no one using it since the module itself was broke ( notice the extra `zabbix_server` in the execstart in the systemd unit : `serviceConfig.ExecStart = "@${pkgs.zabbix.server}/sbin/zabbix_server zabbix_server --config ${configFile}";`) . for the 2.2 and previous version there end of support is august 31 (check [this](https://www.zabbix.com/life_cycle_and_release_policy)) . I did remove them since many people tried to upgrade zabbix but they got annoyed and dropped it since they needed to manage many packages, Also as a rule of thumb i think in nixpkgs we tend to only keep the latest version on any packages. For your PR i think it is way better then this one since it introduces many more functionalities and options

**Comment by aanderse** [comment]
That isn't broke. That is a systemd feature.

**Comment by aanderse** [comment]
Sorry I think I was confused and thought you dropped 3.0 which is supported, but didn't drop 3.4 which is not supported.

**Comment by aanderse** [comment]
@PsyanticY To follow up why this service was **not** broken I'll quote https://www.freedesktop.org/software/systemd/man/systemd.service.html:

> If the executable path is prefixed with "@", the second specified token will be passed as "argv[0]" to the executed process (instead of the actual filename), followed by the further arguments specified.

**Comment by PsyanticY** [comment]
@aanderse thanks for clearing that out i didn't knew about that.

**Pull request merged**
