### PR TITLE
dhcpcd: fix more permissions errors

### PR DESCRIPTION
**Pull request by rnhmjoj**
Fixes for a couple more issues reported in https://github.com/NixOS/nixpkgs/pull/336988.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- Tested via
  - [x] `dhcpcd.tests`
  - [x] `nixosTests.simple`
  - [ ] `nixosTests.networking.scripted`
  - [ ] `nixosTests.networking.networkd`
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by corngood** [comment]
Do we need to worry about ACLs being available on the filesystem?  I only see one existing call to `setfacl` in nixos/.

**Comment by rnhmjoj** [comment]
> Do we need to worry about ACLs being available on the filesystem? I only see one existing call to setfacl in nixos/.

I think that every fs under the sun has them in 2024. That said, if we wanted to be really careful, I could use `chgrp`+`chmod` for the files in /etc and the ACLs only on `/run/resolvconf`. This is guaranteed to be on tmpfs, which does support them.

**Comment by corngood** [comment]
> That said, if we wanted to be really careful, I could use chgrp+chmod for the files in /etc and the ACLs only on /run/resolvconf. This is guaranteed to be on tmpfs, which does support them.

I think if it can be done robustly with basic permissions, there's an argument for using them: ease of inspection with `ls`, compatibility with tar, etc.

Using it on `/run/` seems fine.

**Comment by rnhmjoj** [comment]
Done.

**Review by corngood — APPROVED** [review]

**Pull request merged**
