### PR TITLE
librepcb: 20181031 -> 0.1.0

### PR DESCRIPTION
**Pull request by Luz**
###### Motivation for this change
Update version to the first stable release.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by c0bw3b** [comment]
Homepage should be `https://librepcb.org/` now.

Note: nix won't see this as a newer version so users will need to uninstall `librepcb-20181031` then install `librepcb-0.1.0`

```shell
nix-repl> lib.versionOlder "20181031" "0.1.0"
false
```

**Comment by Mic92** [comment]
Still I see no alternative to not using this version as version number.

**Comment by c0bw3b** [comment]
Yes, it was more for information if someone finds this PR later.
But it should keep `version = "0.1.0"` since it is indeed its upstream version number.

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build librepcb

**Pull request merged**
