### PR TITLE
alsaLib: correct license field

### PR DESCRIPTION
**Pull request by ghost**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Could you please update the commit message acc. the [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes) details?

```text
alsa-lib: correct license field
```

**Review by fabaff — APPROVED** [review]
Reference: https://github.com/alsa-project/alsa-lib/blob/master/src/rawmidi/rawmidi.c#L13-L15

Looks good to me.



```

**Comment by SuperSandro2000** [comment]
But there license file seems to be ``lgpl2.1Only`` https://github.com/alsa-project/alsa-lib/blob/master/COPYING

I am confused.

**Comment by fabaff** [comment]
> But there license file seems to be lgpl21Only https://github.com/alsa-project/alsa-lib/blob/master/COPYING

`COPYING` contains the original content of the license (LGPLv2.1). Paragraph 13 of the license describes the usage of  "any later version". Upstream is clarifying it in their file headers that later versions of the LGPLv2.1 are supported. Thus from my point of view LGPLv2.1+ is correct.

Is in sync with other distributions:

- Fedora: https://src.fedoraproject.org/rpms/alsa-lib/blob/master/f/alsa-lib.spec#_13
- Debian: https://metadata.ftp-master.debian.org/changelogs//main/a/alsa-lib/alsa-lib_1.2.4-1.1_copyright

**Comment by petabyteboy** [comment]
> Could you please update the commit message acc. the [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes) details?
> 
> ```
> alsa-lib: correct license field
> ```

I _think_ my formatting is correct. At least it's the same as all of the previous edits of that file:

screenshot2

**Pull request merged**
