### PR TITLE
nixos/fwupd: migrate to uefi_capsule.conf

### PR DESCRIPTION
**Pull request by KenMacD**
###### Description of changes

In version 1.5.5 of fwupd the uefi plugin was renamed to
uefi-capsule. As part of those changes the configuration file was
renamed and changed.

This modules configuration mismatch was generally hidden because
when udisks2 is enabled fwupd will use that instead. Without
udisks2 the following warning is seen:

    WARNING: UEFI ESP partition not detected or configured

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lovesegfault** [comment]
I recently made a change that enabled udisks2 when fwupd is also enabled, since upstream seemed to assume that.

I prefer what you suggest here, since it means one less service needs to be running for fwupd to work, but do you know which approach is more correct?

**Comment by KenMacD** [comment]
@lovesegfault sorry, I don't know which one is more correct. I just ran in to the issue and [found the solution on the fwupd wiki](https://github.com/fwupd/fwupd/wiki/PluginFlag:esp-not-found).

Like you, I'd prefer fewer dependencies. It appears `udisks2` was default-disabled as it might not be wanted on non-desktop machines. It seems `fwupd` might still be commonly wanted on those machines.

As for if adding `fwupd` you default-include `udisks2`, :shrug:.

**Comment by lovesegfault** [comment]
@KenMacD Can you push a revert of `fb5bceb3ff3` to this branch?

Then I'll just land this change, and we can avoid udisks2 altogether.

**Comment by KenMacD** [comment]
@lovesegfault Rebase and revert added. Thanks!

**Pull request merged**
