### PR TITLE
Workaround Skype segfault

### PR DESCRIPTION
**Pull request by abbradar**
###### Things done:
- [x] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
###### More

This is one possible solution to the problem. I'm not sure if I've done everything correctly to force Hydra to build `qt4-clang` only on i686.

Fixes issue #14234

cc @rycee @domenkozar

### CODE REVIEW

**Comment by abbradar** [comment]
We had a `staging` merge just now -- I'll open this against `master` then ~_^.

**Comment by domenkozar** [comment]
Why is 64bit not supported?

**Comment by abbradar** [comment]
@domenkozar We just don't need it -- only Skype needs 32-bit Clang-built Qt4, and I don't see any reasons to build it on x86_64.

**Comment by domenkozar** [comment]
@abbradar we should then not disable skype on 64bit linux, but rather always pass 32bit clang-built qt4

**Comment by abbradar** [comment]
Hm, I haven't disabled it -- the idea was to make Hydra build `qt4-clang` for i686 (for Skype), but not on x86_64. My solution was to add `qt4-clang` to `all-packages` (so Hydra would see it), but force it to build only on `i686-linux` in `release.nix`. I'm not sure I've done it the right way, though.

**Comment by abbradar** [comment]
Ah, I should also point out that Skype is called through `callPackage_i686`, so it would get 32-bit version of this package automatically... or wait, it would not.

**Pull request closed without merging**
