### PR TITLE
libxmlb: 0.1.7 -> 0.1.8

### PR DESCRIPTION
**Pull request by dtzWill**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
https://github.com/hughsie/libxmlb/commit/cee3c7d00df94bdd6bc2fe9681f72103825664ac

**Comment by jtojnar** [comment]
Should we add [installed tests](https://github.com/NixOS/nixpkgs/issues/34987)?

**Comment by worldofpeace** [comment]
> Should we add [installed tests](https://github.com/NixOS/nixpkgs/issues/34987)?

I can do this, but looking at https://github.com/hughsie/libxmlb/commit/365f598e413abe4f39503d879e4e0953ddc9bc5b I'd need another [patch](https://github.com/NixOS/nixpkgs/blob/c94f6f22d89668bb0c64db0e77d26f69e27eb395/pkgs/tools/misc/colord/installed-tests-path.patch).
Should I opt for pr'ing an option upstream?

**Comment by jtojnar** [comment]
If we could get upstream to accept that, it would be very nice.

**Comment by worldofpeace** [comment]
> If we could get upstream to accept that, it would be very nice.

Right, and it's not like others haven't had something like that https://github.com/NixOS/nixpkgs/blob/20aeed3ba8088160947983f8476eac7a8b53b672/pkgs/development/libraries/xdg-desktop-portal/default.nix#L34

**Comment by dtzWill** [comment]
Ping-- is this waiting on something (changes/decision/info)?

**Comment by jtojnar** [comment]
Adding libxmlb to https://github.com/NixOS/nixpkgs/issues/34987 can be acceptable alternative if no one has the capacity to do it at the moment.

**Comment by jtojnar** [comment]
This has been merged now https://github.com/NixOS/nixpkgs/pull/60602

**Comment by apeyroux** [comment]
maybe close the pr ?

**Comment by dtzWill** [comment]
Thanks!

**Pull request closed without merging**
