### PR TITLE
awesome: 4.2 -> 4.3, don't clutter PATH, touchup lua paths

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

Should be compatible but even so may want to review
release notes to take advantage of the new goodness:

https://github.com/awesomeWM/awesome/releases/tag/v4.3

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by rasendubi — APPROVED** [review]
This looks awesome!

**Comment by rasendubi** [comment]
Running awesome-4.3 right now. Works like a charm.

**Comment by psychon** [comment]
Uhm, asciidoc was replaced with asciidoctor (due to asciidoc being deprecated), thus asciidoc can be removed from the build inputs.

**Comment by dtzWill** [comment]
> Uhm, asciidoc was replaced with asciidoctor (due to asciidoc being deprecated), thus asciidoc can be removed from the build inputs.

Whoops, sorry! Will submit a PR fixing this shortly :).

**Pull request merged**
