### PR TITLE
lunarvim: fix alias neovim is still in node-packages.nix

### PR DESCRIPTION
**Pull request by MisileLab**
fix `Alias neovim is still in node-packages.nix` that related from https://github.com/NixOS/nixpkgs/pull/317333

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by MisileLab** [comment]
I think failure is not derived from this change.

**Comment by MisileLab** [comment]
@ProminentRetail @lebensterben can you review this pr? (I can't request review)

**Review by midischwarz12 — APPROVED** [review]
LGTM

**Review by lebensterben — APPROVED** [review]
Tested and works

**Comment by simon-bueler** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 357119`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>lunarvim</li>
  </ul>
</details>

**Comment by olafkfreund** [comment]
Any progress on this at all?

**Comment by midirhee12** [comment]
@olafkfreund It was merged. So we just need hydra to build it into unstable. You can follow the progress of hydra [here](https://status.nixos.org/). This happens realistically every few days or so. Maybe a week or two max. The last successful build of unstable was a few days ago, but it was 4 days old. So we'll need to wait for hydra to catch up now and build this or a more recent commit.

**Comment by olafkfreund** [comment]
Any updates on this? Still a problem .. and thanks for the update last time @midirhee12. Yeah and guys thanks for work as well.

**Comment by simon-bueler** [comment]
Had the issue and since this week I retried and the fix is in unstable now.

**Comment by olafkfreund** [comment]
Still getting: 

```
error: Alias neovim is still in node-packages.nix
┏━ 1 Errors: 
 ⋮ 
┃              |     ^
┃            14|     then lib.removeAttrs alias ["recurseForDerivations"]
┃ 
┃        … from call site
┃          at /nix/store/nr5nl3zwzl02x3rnikjbry3s5xy7bm1d-source/pkgs/development/node-packages/aliases.nix:34:1…
┃            33|         (removeRecurseForDerivations
┃            34|           (checkInPkgs n alias)))
┃              |            ^
┃            35|       aliases;
┃ 
┃        … while calling 'checkInPkgs'
┃          at /nix/store/nr5nl3zwzl02x3rnikjbry3s5xy7bm1d-source/pkgs/development/node-packages/aliases.nix:25:2…
┃            24|   # Make sure that we are not shadowing something from node-packages.nix.
┃            25|   checkInPkgs = n: alias:
┃              |                    ^
┃            26|     if builtins.hasAttr n super
┃ 
┃        … while calling the 'throw' builtin
┃          at /nix/store/nr5nl3zwzl02x3rnikjbry3s5xy7bm1d-source/pkgs/development/node-packages/aliases.nix:27:1…
┃            26|     if builtins.hasAttr n super
┃            27|     then throw "Alias ${n} is still in node-packages.nix"
┃              |          ^
┃            28|     else alias;
┃ 
┃        error: Alias neovim is still in node-packages.ni
```x

**Comment by lebensterben** [comment]
this should be fixed in unstable channel now.

**Comment by olafkfreund** [comment]
Now I have the same problem in 24.11 stable as well:
`1 Errors: 
┃ error:
┃        … while calling the 'head' builtin
┃          at /nix/store/5wvrlpfrwlmg24ywkybvidyzcvki6bwx-source/lib/attrsets.nix:1574:11:
┃          1573|         || pred here (elemAt values 1) (head values) then
┃          1574|           head values
┃              |           ^
┃          1575|         else
┃ 
┃        … while evaluating the attribute 'value'
┃          at /nix/store/5wvrlpfrwlmg24ywkybvidyzcvki6bwx-source/lib/modules.nix:816:9:
┃           815|     in warnDeprecation opt //
┃           816|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
┃              |         ^
┃           817|         inherit (res.defsFinal') highestPrio;
┃ 
┃        … while evaluating the option `system.build.toplevel':
┃ 
┃        … while evaluating definitions from `/nix/store/5wvrlpfrwlmg24ywkybvidyzcvki6bwx-source/nixos/modules/system/activation/top-level.nix':
┃ 
┃        … while evaluating the option `warnings':
┃ 
┃        … while evaluating definitions from `/nix/store/5wvrlpfrwlmg24ywkybvidyzcvki6bwx-source/nixos/modules/system/boot/systemd.nix':
┃ 
┃        … while evaluating the option `systemd.services.home-manager-olafkfreund.serviceConfig':
┃ 
┃        … while evaluating definitions from `/nix/store/5wvrlpfrwlmg24ywkybvidyzcvki6bwx-source/flake.nix':
┃ 
┃        … while evaluating the option `home-manager.users.olafkfreund.home.file."/home/olafkfreund/.config/fontconfig/conf.d/10-hm-fonts.conf".source':
┃ 
┃        … while evaluating definitions from `/nix/store/d5slvaasbp0j45yix38rn61y13zfzmi2-source/modules/files.nix':
┃ 
┃        … while evaluating the option `home-manager.users.olafkfreund.home.file."/home/olafkfreund/.config/fontconfig/conf.d/10-hm-fonts.conf".text':
┃ 
┃        … while evaluating definitions from `/nix/store/d5slvaasbp0j45yix38rn61y13zfzmi2-source/modules/misc/xdg.nix':
┃ 
┃        … while evaluating the option `home-manager.users.olafkfreund.xdg.configFile."fontconfig/conf.d/10-hm-fonts.conf".text':
┃ 
┃        … while evaluating definitions from `/nix/store/d5slvaasbp0j45yix38rn61y13zfzmi2-source/modules/misc/fontconfig.nix':
┃ 
┃        (stack trace truncated; use '--show-trace' to show the full, detailed trace)
┃ 
┃        error: Alias neovim is still in node-packages.nix
┣━━━                                                             
┗━ ∑ ⚠ Exited with 1 errors reported by nix at 09:23:01 after 24s
Error: 
   0: Command exited with status Exited(1)`

**Comment by lebensterben** [comment]
should be caused by https://github.com/NixOS/nixpkgs/pull/317333#issuecomment-2513319567

**Comment by akgrant43** [comment]
I hit the issue in 24.11, like @olafkfreund.  Given the severity, shouldn't this be submitted for backporting to 24.11?
I guess I can create the PR if appropriate (I haven't done created a PR for a backport before).

**Comment by MisileLab** [comment]
> I hit the issue in 24.11, like @olafkfreund. Given the severity, shouldn't this be submitted for backporting to 24.11? I guess I can create the PR if appropriate (I haven't done created a PR for a backport before).

see https://github.com/NixOS/nixpkgs/pull/363809

**Comment by akgrant43** [comment]
> > I hit the issue in 24.11, like @olafkfreund. Given the severity, shouldn't this be submitted for backporting to 24.11? I guess I can create the PR if appropriate (I haven't done created a PR for a backport before).
> 
> see #363809

Thanks!

**Comment by echometerain** [comment]
I'm still encountering this issue on 24.11:
```
error:
       … while calling the 'head' builtin
         at /nix/store/va0p2i72cm2ljwm084a0g6ji41s5qnyz-source/lib/attrsets.nix:1574:11:
         1573|         || pred here (elemAt values 1) (head values) then
         1574|           head values
             |           ^
         1575|         else

       … while evaluating the attribute 'value'
         at /nix/store/va0p2i72cm2ljwm084a0g6ji41s5qnyz-source/lib/modules.nix:816:9:
          815|     in warnDeprecation opt //
          816|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          817|         inherit (res.defsFinal') highestPrio;

       … while evaluating the option `system.build.toplevel':

       … while evaluating definitions from `/nix/store/va0p2i72cm2ljwm084a0g6ji41s5qnyz-source/nixos/modules/system/activation/top-level.nix':

       … while evaluating the option `system.systemBuilderArgs':

       … while evaluating definitions from `/nix/store/va0p2i72cm2ljwm084a0g6ji41s5qnyz-source/nixos/modules/system/activation/activatable-system.nix':

       … while evaluating the option `system.activationScripts.etc.text':

       … while evaluating definitions from `/nix/store/va0p2i72cm2ljwm084a0g6ji41s5qnyz-source/nixos/modules/system/etc/etc-activation.nix':

       … while evaluating definitions from `/nix/store/va0p2i72cm2ljwm084a0g6ji41s5qnyz-source/nixos/modules/system/etc/etc.nix':

       … while evaluating the option `environment.etc.dbus-1.source':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: Alias neovim is still in node-packages.nix
```

**Comment by lebensterben** [comment]
the back port is merged 1 day ago. it should take a few days to land.

**Comment by olafkfreund** [comment]
The problem is still the same in unstable as well .. Nothing has changed at all.

**Comment by akgrant43** [comment]
> The problem is still the same in unstable as well .. Nothing has changed at all.

I've been using it from unstable without any issue for the last couple of days.

**Pull request merged**
