### PR TITLE
terragrunt: 0.23.2 -> 0.23.14

### PR DESCRIPTION
**Pull request by 06kellyjac**
Moved to use go modules build

---

This is my first real PR to nixpkgs, I welcome any and all criticism.
I removed the rm vendor line because it doesn't look relevant for go mod builds(?)

Let me know if there are extra steps I need to take

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ryantm** [comment]
Thanks for your first PR welcome.

Looks like you can delete the deps.nix file too.

**Review by ryantm — CHANGES_REQUESTED** [review]
Remove deps.nix file

**Comment by 06kellyjac** [comment]
Ah of course, I'll get on that

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 87089 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>1 package built:</summary>  - terragrunt</details>

**Pull request merged**
