### PR TITLE
python.pkgs.tensorflow: wheel version

### PR DESCRIPTION
**Pull request by jyp**
###### Motivation for this change
Tensorflow is broken in master.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by FRidh — CHANGES_REQUESTED** [review]

**Comment by jyp** [comment]
@FRidh Thanks for the review!

I think I've applied all your comments in the current version.

**Comment by jyp** [comment]
Indeed. In master no fixup is done on darwin; i've updated the commit as
you suggest.

**Comment by dotlambda** [comment]
I'm getting
```
$ nix-build -A python2.pkgs.tensorflow
these derivations will be built:
  /nix/store/clmfhq0nl767d1h61drjgm1qxzbgsq1b-python2.7-tensorflow-1.7.1.drv
building '/nix/store/clmfhq0nl767d1h61drjgm1qxzbgsq1b-python2.7-tensorflow-1.7.1.drv'...
unpacking sources
patching sources
configuring
building
installing
/build/dist /build
Processing ./tensorflow-1.7.1-cp27-none-linux_x86_64.whl
Requirement already satisfied: protobuf>=3.4.0 in /nix/store/rlrjqlpsqvlrhjpk5v9zzhsvdpmmi0dp-python2.7-protobuf-3.5.1.1/lib/python2.7/site-packages (from tensorflow==1.7.1) (3.5.1)
Collecting astor>=0.6.0 (from tensorflow==1.7.1)
  Could not find a version that satisfies the requirement astor>=0.6.0 (from tensorflow==1.7.1) (from versions: )
No matching distribution found for astor>=0.6.0 (from tensorflow==1.7.1)
builder for '/nix/store/clmfhq0nl767d1h61drjgm1qxzbgsq1b-python2.7-tensorflow-1.7.1.drv' failed with exit code 1
```

**Comment by jyp** [comment]
@dotlambda If you're targetting py 3.6 it'll work, but not with eager graph execution. Would you care submitting a bug report?
I'd fix the issue right away, but I see also that the package `gast` is needed too, and it is currently not in nixpkgs.

**Pull request merged**
