### PR TITLE
enchant: Add nuspell support

### PR DESCRIPTION
**Pull request by spacekitteh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 133205` at 0542f4e3 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/043d717e0b21acb2f71e63d87bcb8331">python38Packages.sopel</a></li>
    <li><a href="https://gist.github.com/2e7be1e9407b92c8cc639133934e441d">python39Packages.sopel</a></li>
  </ul>
</details>
<details>
  <summary>255 packages skipped due to time constraints:</summary>
  <ul>
    <li>abiword</li>
    <li>adapta-gtk-theme</li>
    <li>alfis</li>
    <li>almanah</li>
    <li>apostrophe</li>
    <li>arc-theme</li>
    <li>areca</li>
    <li>arx-libertatis</li>
    <li>asciidoc-full</li>
    <li>asciidoc-full-with-plugins</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>74 packages built successfully:</summary>
  <ul>
    <li>bluefish</li>
    <li>bottles</li>
    <li>cherrytree</li>
    <li>denemo</li>
    <li>enchant (enchant2)</li>
    <li>evince (gnome.evince)</li>
    <li>fcitx</li>
    <li>fcitx-configtool</li>
    <li>fcitx-engines.anthy</li>
    <li>fcitx-engines.chewing</li>
    <li>fcitx-engines.cloudpinyin</li>
    <li>fcitx-engines.hangul</li>
    <li>fcitx-engines.libpinyin</li>
    <li>fcitx-engines.m17n</li>
    <li>fcitx-engines.mozc</li>
    <li>fcitx-engines.rime</li>
    <li>fcitx-engines.skk</li>
    <li>fcitx-engines.table-extra</li>
    <li>fcitx-engines.table-other</li>
    <li>fcitx-engines.unikey</li>
    <li>fcitx5</li>
    <li>fcitx5-chinese-addons</li>
    <li>fcitx5-configtool</li>
    <li>fcitx5-gtk</li>
    <li>fcitx5-lua</li>
    <li>fcitx5-m17n</li>
    <li>fcitx5-mozc</li>
    <li>fcitx5-rime</li>
    <li>fcitx5-table-extra</li>
    <li>fcitx5-table-other</li>
    <li>fcitx5-with-addons</li>
    <li>gImageReader</li>
    <li>gajim</li>
    <li>gnome-latex</li>
    <li>gnome.gedit</li>
    <li>gspell (gnome.gspell)</li>
    <li>gtkspell3</li>
    <li>gtkspellmm</li>
    <li>gtranslator</li>
    <li>gummi</li>
    <li>hexchat</li>
    <li>libime</li>
    <li>libsForQt5.fcitx-qt5 (libsForQt515.fcitx-qt5 ,plasma5Packages.fcitx-qt5)</li>
    <li>libsForQt5.fcitx5-qt (libsForQt515.fcitx5-qt ,plasma5Packages.fcitx5-qt)</li>
    <li>libsForQt512.fcitx-qt5</li>
    <li>libsForQt512.fcitx5-qt</li>
    <li>libsForQt514.fcitx-qt5</li>
    <li>libsForQt514.fcitx5-qt</li>
    <li>mlterm</li>
    <li>modem-manager-gui</li>
    <li>mwic</li>
    <li>ocrfeeder</li>
    <li>octavePackages.miscellaneous</li>
    <li>octavePackages.vrml</li>
    <li>pan</li>
    <li>paperwork</li>
    <li>pond</li>
    <li>pyspread</li>
    <li>python38Packages.paperwork-backend</li>
    <li>python38Packages.paperwork-shell</li>
    <li>python38Packages.pyenchant</li>
    <li>python38Packages.pygtkspellcheck</li>
    <li>python38Packages.skytemple-ssb-debugger</li>
    <li>python38Packages.sphinxcontrib-spelling</li>
    <li>python39Packages.paperwork-backend</li>
    <li>python39Packages.paperwork-shell</li>
    <li>python39Packages.pyenchant</li>
    <li>python39Packages.pygtkspellcheck</li>
    <li>python39Packages.skytemple-ssb-debugger</li>
    <li>python39Packages.sphinxcontrib-spelling</li>
    <li>retext</li>
    <li>tryton</li>
    <li>xed-editor</li>
    <li>xfce.mousepad</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by jtojnar** [comment]
- Do we want to keep hunspell now when nuspell is supposed to support its files?
- Did you check that this does not cause linking issues for stuff linking to enchant like aspell/hspell did?

**Comment by spacekitteh** [comment]
>     * Did you check that this does not cause linking issues for stuff linking to enchant like aspell/hspell did?

Not exactly, I was relying on CI checks; and I checked the enchant Autoconfigure script to see how it treated aspell, hspell, hunspell and nuspell. Nuspell was treated the same as hunspell in it, so I put it in the same place as hunspell.

**Comment by spacekitteh** [comment]
@jtojnar I'm not really sure how I'd test all the binaries which depend on enchant. What should I do to move this forward?

**Comment by jtojnar** [comment]
Tried building this and comparing it with https://github.com/NixOS/nixpkgs/commit/4f338f0eee21d5ea6317220f3337cbc8634dec71 and looks like the dependencies in the libtool file are now pruned by something:

```
--- a/nix/store/8hy1i741rd3q82k7656aapis8dh2a355-enchant-2.2.3/lib/libenchant-2.la
+++ b/nix/store/vc5lb4v5ffh4jgz9x0i3qgpkm5f4ry84-enchant-2.3.0/lib/libenchant-2.la
@@ -1,5 +1,5 @@
 # libenchant-2.la - a libtool library file
-# Generated by libtool (GNU libtool) 2.4.6 Debian-2.4.6-0.1
+# Generated by libtool (GNU libtool) 2.4.6 Debian-2.4.6-14
 #
 # Please DO NOT delete this file!
 # It is necessary for linking the library.
@@ -8,7 +8,7 @@
 dlname='libenchant-2.so.2'
 
 # Names of this library.
-library_names='libenchant-2.so.2.2.3 libenchant-2.so.2 libenchant-2.so'
+library_names='libenchant-2.so.2.3.0 libenchant-2.so.2 libenchant-2.so'
 
 # The name of the static archive.
 old_library=''
@@ -17,15 +17,15 @@ old_library=''
 inherited_linker_flags=' -pthread'
 
 # Libraries that this one depends upon.
-dependency_libs=' -L/nix/store/dqlc8y4phlg1hmdbwkhqfwhnxcac88d1-glib-2.56.0/lib /nix/store/dqlc8y4phlg1hmdbwkhqfwhnxcac88d1-glib-2.56.0/lib/libgmodule-2.0.la -ldl -L/nix/store/6jw57q1ky5v27vppf769q4f7r3gcaz0k-pcre-8.41/lib /nix/store/dqlc8y4phlg1hmdbwkhqfwhnxcac88d1-glib-2.56.0/lib/libglib-2.0.la /nix/store/6jw57q1ky5v27vppf769q4f7r3gcaz0k-pcre-8.41/lib/libpcre.la -lpthread -lhspell -laspell -lz'
+dependency_libs='' #pruned
 
 # Names of additional weak libraries provided by this library
 weak_library_names=''
 
 # Version information for libenchant-2.
-current=4
-age=2
-revision=3
+current=5
+age=3
+revision=0
 
 # Is this an already installed library?
 installed=yes
@@ -38,4 +38,4 @@ dlopen=''
 dlpreopen=''
 
 # Directory that this library needs to be installed in:
-libdir='/nix/store/8hy1i741rd3q82k7656aapis8dh2a355-enchant-2.2.3/lib'
+libdir='/nix/store/vc5lb4v5ffh4jgz9x0i3qgpkm5f4ry84-enchant-2.3.0/lib'
```

**Comment by jtojnar** [comment]
Thanks.

**Comment by spacekitteh** [comment]
> Tried building this and comparing it with [4f338f0](https://github.com/NixOS/nixpkgs/commit/4f338f0eee21d5ea6317220f3337cbc8634dec71) and looks like the dependencies in the libtool file are now pruned by something:

I know nothing about libtool; what does this imply?

**Comment by jtojnar** [comment]
The consequence is that we should no longer need to propagate `aspell` and `hspell`. It would be interesting to find what prunes the libtool files though. Nixpkgs setup hook, libtool itself or enchant’s build system.

**Comment by spacekitteh** [comment]
Looks like this does it: https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/default.nix#L60

**Pull request merged**
