### PR TITLE
tint2: fix build with gcc14

### PR DESCRIPTION
**Pull request by SFrijters**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by lucasew** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369100`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 80 packages marked as broken and skipped:</summary>
  <ul>
    <li>private-gpt</li>
    <li>private-gpt.dist</li>
    <li>python312Packages.grep-ast</li>
    <li>python312Packages.grep-ast.dist</li>
    <li>python312Packages.llama-index</li>
    <li>python312Packages.llama-index-agent-openai</li>
    <li>python312Packages.llama-index-agent-openai.dist</li>
    <li>python312Packages.llama-index-cli</li>
    <li>python312Packages.llama-index-cli.dist</li>
    <li>python312Packages.llama-index-core</li>
    <li>python312Packages.llama-index-core.dist</li>
    <li>python312Packages.llama-index-embeddings-gemini</li>
    <li>python312Packages.llama-index-embeddings-gemini.dist</li>
    <li>python312Packages.llama-index-embeddings-google</li>
    <li>python312Packages.llama-index-embeddings-google.dist</li>
    <li>python312Packages.llama-index-embeddings-huggingface</li>
    <li>python312Packages.llama-index-embeddings-huggingface.dist</li>
    <li>python312Packages.llama-index-embeddings-ollama</li>
    <li>python312Packages.llama-index-embeddings-ollama.dist</li>
    <li>python312Packages.llama-index-embeddings-openai</li>
    <li>python312Packages.llama-index-embeddings-openai.dist</li>
    <li>python312Packages.llama-index-graph-stores-nebula</li>
    <li>python312Packages.llama-index-graph-stores-nebula.dist</li>
    <li>python312Packages.llama-index-graph-stores-neo4j</li>
    <li>python312Packages.llama-index-graph-stores-neo4j.dist</li>
    <li>python312Packages.llama-index-graph-stores-neptune</li>
    <li>python312Packages.llama-index-graph-stores-neptune.dist</li>
    <li>python312Packages.llama-index-indices-managed-llama-cloud</li>
    <li>python312Packages.llama-index-indices-managed-llama-cloud.dist</li>
    <li>python312Packages.llama-index-legacy</li>
    <li>python312Packages.llama-index-legacy.dist</li>
    <li>python312Packages.llama-index-llms-ollama</li>
    <li>python312Packages.llama-index-llms-ollama.dist</li>
    <li>python312Packages.llama-index-llms-openai</li>
    <li>python312Packages.llama-index-llms-openai-like</li>
    <li>python312Packages.llama-index-llms-openai-like.dist</li>
    <li>python312Packages.llama-index-llms-openai.dist</li>
    <li>python312Packages.llama-index-multi-modal-llms-openai</li>
    <li>python312Packages.llama-index-multi-modal-llms-openai.dist</li>
    <li>python312Packages.llama-index-program-openai</li>
    <li>python312Packages.llama-index-program-openai.dist</li>
    <li>python312Packages.llama-index-question-gen-openai</li>
    <li>python312Packages.llama-index-question-gen-openai.dist</li>
    <li>python312Packages.llama-index-readers-database</li>
    <li>python312Packages.llama-index-readers-database.dist</li>
    <li>python312Packages.llama-index-readers-file</li>
    <li>python312Packages.llama-index-readers-file.dist</li>
    <li>python312Packages.llama-index-readers-json</li>
    <li>python312Packages.llama-index-readers-json.dist</li>
    <li>python312Packages.llama-index-readers-llama-parse</li>
    <li>python312Packages.llama-index-readers-llama-parse.dist</li>
    <li>python312Packages.llama-index-readers-s3</li>
    <li>python312Packages.llama-index-readers-s3.dist</li>
    <li>python312Packages.llama-index-readers-twitter</li>
    <li>python312Packages.llama-index-readers-twitter.dist</li>
    <li>python312Packages.llama-index-readers-txtai</li>
    <li>python312Packages.llama-index-readers-txtai.dist</li>
    <li>python312Packages.llama-index-readers-weather</li>
    <li>python312Packages.llama-index-readers-weather.dist</li>
    <li>python312Packages.llama-index-vector-stores-chroma</li>
    <li>python312Packages.llama-index-vector-stores-chroma.dist</li>
    <li>python312Packages.llama-index-vector-stores-google</li>
    <li>python312Packages.llama-index-vector-stores-google.dist</li>
    <li>python312Packages.llama-index-vector-stores-postgres</li>
    <li>python312Packages.llama-index-vector-stores-postgres.dist</li>
    <li>python312Packages.llama-index-vector-stores-qdrant</li>
    <li>python312Packages.llama-index-vector-stores-qdrant.dist</li>
    <li>python312Packages.llama-index.dist</li>
    <li>python312Packages.llama-parse</li>
    <li>python312Packages.llama-parse.dist</li>
    <li>python312Packages.private-gpt</li>
    <li>python312Packages.private-gpt.dist</li>
    <li>python312Packages.tree-sitter-languages</li>
    <li>python312Packages.tree-sitter-languages.dist</li>
    <li>python313Packages.grep-ast</li>
    <li>python313Packages.grep-ast.dist</li>
    <li>python313Packages.tree-sitter-languages</li>
    <li>python313Packages.tree-sitter-languages.dist</li>
    <li>zeekscript</li>
    <li>zeekscript.dist</li>
  </ul>
</details>
<details>
  <summary>:fast_forward: 1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>:x: 38 packages failed to build:</summary>
  <ul>
    <li>flacon</li>
    <li>gdome2</li>
    <li>glibcInfo</li>
    <li>goldendict-ng</li>
    <li>harlequin</li>
    <li>harlequin.dist</li>
    <li>kakasi</li>
    <li>libeb</li>
    <li>memray</li>
    <li>memray.dist</li>
    <li>python313Packages.brian2</li>
    <li>python313Packages.brian2.dist</li>
    <li>python313Packages.lsp-tree-sitter</li>
    <li>python313Packages.lsp-tree-sitter.dist</li>
    <li>python313Packages.manifestoo</li>
    <li>python313Packages.manifestoo.dist</li>
    <li>python313Packages.pytest-textual-snapshot</li>
    <li>python313Packages.pytest-textual-snapshot.dist</li>
    <li>python313Packages.textual</li>
    <li>python313Packages.textual-dev</li>
    <li>python313Packages.textual-dev.dist</li>
    <li>python313Packages.textual-fastdatatable</li>
    <li>python313Packages.textual-fastdatatable.dist</li>
    <li>python313Packages.textual-slider</li>
    <li>python313Packages.textual-slider.dist</li>
    <li>python313Packages.textual-textarea</li>
    <li>python313Packages.textual-textarea.dist</li>
    <li>python313Packages.textual-universal-directorytree</li>
    <li>python313Packages.textual-universal-directorytree.dist</li>
    <li>python313Packages.textual.dist</li>
    <li>quodlibet-full</li>
    <li>quodlibet-full.dist</li>
    <li>quodlibet-full.doc</li>
    <li>quodlibet-xine-full</li>
    <li>quodlibet-xine-full.dist</li>
    <li>quodlibet-xine-full.doc</li>
    <li>rofi-file-browser</li>
    <li>workrave</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 157 packages built:</summary>
  <ul>
    <li>browsr</li>
    <li>browsr.dist</li>
    <li>clerk</li>
    <li>codecov-cli</li>
    <li>codecov-cli.dist</li>
    <li>dooit</li>
    <li>dooit-extras</li>
    <li>dooit-extras.dist</li>
    <li>dooit.dist</li>
    <li>exercism</li>
    <li>flet-client-flutter</li>
    <li>flet-client-flutter.debug</li>
    <li>flet-client-flutter.pubcache</li>
    <li>freeorion</li>
    <li>frogmouth</li>
    <li>frogmouth.dist</li>
    <li>gollama</li>
    <li>home-assistant-component-tests.ollama</li>
    <li>home-assistant-custom-lovelace-modules.universal-remote-card</li>
    <li>i3-layout-manager</li>
    <li>isponsorblocktv</li>
    <li>isponsorblocktv.dist</li>
    <li>jcli</li>
    <li>knot-dns</li>
    <li>knot-dns.bin</li>
    <li>knot-dns.dev</li>
    <li>knot-resolver</li>
    <li>knot-resolver.dev</li>
    <li>monkeysAudio</li>
    <li>mutmut</li>
    <li>mutmut.dist</li>
    <li>n8n</li>
    <li>namespace-cli</li>
    <li>ngtcp2-gnutls</li>
    <li>ngtcp2-gnutls.dev</li>
    <li>oterm</li>
    <li>oterm.dist</li>
    <li>pinentry-rofi</li>
    <li>plasma-hud</li>
    <li>plemoljp</li>
    <li>plemoljp-nf</li>
    <li>prometheus-knot-exporter</li>
    <li>prometheus-knot-exporter.dist</li>
    <li>python312Packages.brian2</li>
    <li>python312Packages.brian2.dist</li>
    <li>python312Packages.flet</li>
    <li>python312Packages.flet-core</li>
    <li>python312Packages.flet-core.dist</li>
    <li>python312Packages.flet-runtime</li>
    <li>python312Packages.flet-runtime.dist</li>
    <li>python312Packages.flet.dist</li>
    <li>python312Packages.langchain-ollama</li>
    <li>python312Packages.langchain-ollama.dist</li>
    <li>python312Packages.libknot</li>
    <li>python312Packages.libknot.dist</li>
    <li>python312Packages.lsp-tree-sitter</li>
    <li>python312Packages.lsp-tree-sitter.dist</li>
    <li>python312Packages.manifestoo</li>
    <li>python312Packages.manifestoo.dist</li>
    <li>python312Packages.ollama</li>
    <li>python312Packages.ollama.dist</li>
    <li>python312Packages.pytest-textual-snapshot</li>
    <li>python312Packages.pytest-textual-snapshot.dist</li>
    <li>python312Packages.textual</li>
    <li>python312Packages.textual-dev</li>
    <li>python312Packages.textual-dev.dist</li>
    <li>python312Packages.textual-fastdatatable</li>
    <li>python312Packages.textual-fastdatatable.dist</li>
    <li>python312Packages.textual-slider</li>
    <li>python312Packages.textual-slider.dist</li>
    <li>python312Packages.textual-textarea</li>
    <li>python312Packages.textual-textarea.dist</li>
    <li>python312Packages.textual-universal-directorytree</li>
    <li>python312Packages.textual-universal-directorytree.dist</li>
    <li>python312Packages.textual.dist</li>
    <li>python312Packages.tree-sitter</li>
    <li>python312Packages.tree-sitter-html</li>
    <li>python312Packages.tree-sitter-html.dist</li>
    <li>python312Packages.tree-sitter-json</li>
    <li>python312Packages.tree-sitter-json.dist</li>
    <li>python312Packages.tree-sitter-python</li>
    <li>python312Packages.tree-sitter-python.dist</li>
    <li>python312Packages.tree-sitter-rust</li>
    <li>python312Packages.tree-sitter-rust.dist</li>
    <li>python312Packages.tree-sitter.dist</li>
    <li>python313Packages.flet</li>
    <li>python313Packages.flet-core</li>
    <li>python313Packages.flet-core.dist</li>
    <li>python313Packages.flet-runtime</li>
    <li>python313Packages.flet-runtime.dist</li>
    <li>python313Packages.flet.dist</li>
    <li>python313Packages.libknot</li>
    <li>python313Packages.libknot.dist</li>
    <li>python313Packages.ollama</li>
    <li>python313Packages.ollama.dist</li>
    <li>python313Packages.tree-sitter</li>
    <li>python313Packages.tree-sitter-html</li>
    <li>python313Packages.tree-sitter-html.dist</li>
    <li>python313Packages.tree-sitter-json</li>
    <li>python313Packages.tree-sitter-json.dist</li>
    <li>python313Packages.tree-sitter-python</li>
    <li>python313Packages.tree-sitter-python.dist</li>
    <li>python313Packages.tree-sitter-rust</li>
    <li>python313Packages.tree-sitter-rust.dist</li>
    <li>python313Packages.tree-sitter.dist</li>
    <li>ra-multiplex</li>
    <li>rich-cli</li>
    <li>rich-cli.dist</li>
    <li>rofi</li>
    <li>rofi-blezz</li>
    <li>rofi-calc</li>
    <li>rofi-emoji</li>
    <li>rofi-emoji-wayland</li>
    <li>rofi-games</li>
    <li>rofi-menugen</li>
    <li>rofi-pass</li>
    <li>rofi-pass-wayland</li>
    <li>rofi-pulse-select</li>
    <li>rofi-screenshot</li>
    <li>rofi-systemd</li>
    <li>rofi-top</li>
    <li>rofi-unwrapped</li>
    <li>rofi-vpn</li>
    <li>rofi-wayland</li>
    <li>rofi-wayland-unwrapped</li>
    <li>rofimoji</li>
    <li>rofimoji.dist</li>
    <li>rpcs3</li>
    <li>rust-analyzer</li>
    <li>rust-analyzer-unwrapped</li>
    <li>ryzenadj</li>
    <li>slimserver</li>
    <li>smassh</li>
    <li>smassh.dist</li>
    <li>streamcontroller</li>
    <li>subxt</li>
    <li>super-slicer (super-slicer-latest)</li>
    <li>super-slicer-beta</li>
    <li>super-slicer-beta.debug</li>
    <li>super-slicer.debug (super-slicer-latest.debug)</li>
    <li>tftui</li>
    <li>tftui.dist</li>
    <li>tint2</li>
    <li>todofi-sh</li>
    <li>toolong</li>
    <li>toolong.dist</li>
    <li>tpnote</li>
    <li>upiano</li>
    <li>upiano.dist</li>
    <li>url-parser</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPluginsUpdater</li>
    <li>vscode-extensions.rust-lang.rust-analyzer</li>
    <li>wl-mirror</li>
    <li>wsrepl</li>
    <li>wsrepl.dist</li>
    <li>ycmd</li>
  </ul>
</details>

**Comment by SFrijters** [comment]
Why does the `nixpkgs-review` report so much? `tint2` is a leaf package?

**Comment by lucasew** [comment]
> Why does the `nixpkgs-review` report so much? `tint2` is a leaf package?

Maybe those packages were updated recently so they cache missed

**Comment by SFrijters** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369100`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>tint2</li>
  </ul>
</details>

**Review by fpletz — APPROVED** [review]

**Pull request merged**
