### PR TITLE
setxkbmap: 1.3.1 -> 1.3.2

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

https://lists.x.org/archives/xorg-announce/2019-July/003007.html

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by bjornfor** [comment]
Needs rebase.

**Comment by dtzWill** [comment]
Done, thanks!

**Review by bjornfor — APPROVED** [review]

**Comment by bjornfor** [comment]
You've have specified staging as target branch, even though this rebuilds less than 100 packages. Is that correct?

**Comment by dtzWill** [comment]
> You've have specified staging as target branch, even though this rebuilds less than 100 packages. Is that correct?

Good call, switched to master! Thanks!

**Pull request merged**
