### PR TITLE
gst_all_1.gst-plugins-bad: build gtksink plugin

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
Corebird requires gtksink gstreamer plugin to play videos.[¹] The plugin, however, is only built when GTK is available.

This patch adds gtk3 as a dependency to gstreamer-plugins-bad package, enabling the build of gtksink.

[¹]: https://github.com/baedert/corebird/issues/431

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Tested by running Corebird and playing a video
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by 0xABAB — APPROVED** [review]

**Comment by FRidh** [comment]
@jtojnar which attribute corresponds to this expression? Its not `gst-plugins-bad`.

**Comment by jtojnar** [comment]
@FRidh yes, it is `gst-plugins-bad`, I updated the commit message.

**Comment by FRidh** [comment]
So its 
```
$ nix-build -A gst_all_1.gst-plugins-bad
```
and not
```
$ nix-build -A gst-plugins-bad
```

**Comment by FRidh** [comment]
Adding `gtk` adds 60 MB to the closure. How common is this plugin you need?

**Comment by jtojnar** [comment]
You are right, it is for GStreamer 1.

At least Corebird requires the gtk sink, not sure about other packages. Should it be made optional like FAAC support?

**Comment by FRidh** [comment]
> Should it be made optional like FAAC support?

I think that would be better, yes. Say we have `corebird`, then it could override the expression using a version that has this plugin.

**Comment by jtojnar** [comment]
@FRidh Updated to make GTK optional.

**Pull request merged**
