### PR TITLE
buildMaven: Update buildMaven to pure Nix

### PR DESCRIPTION
**Pull request by fzakaria**
###### Motivation for this change

Change the code that builds the maven repository to one using pure nix rather than a bash script.

```bash
❯nix-build --no-out-link example.nix -I nixpkgs=/home/fmzakari/code/github.com/NixOS/nixpkgs
/nix/store/5zg4jxj7897lcasd7zpvjrk8drnmiaf5-maven-repository

❯ tree /nix/store/5zg4jxj7897lcasd7zpvjrk8drnmiaf5-maven-repository | head

/nix/store/5zg4jxj7897lcasd7zpvjrk8drnmiaf5-maven-repository
├── antlr
│   └── antlr
│       └── 2.7.2
│           ├── antlr-2.7.2.jar -> /nix/store/d027c8f2cnmj5yrynpbq2s6wmc9cb559-antlr-2.7.2.jar
│           └── antlr-2.7.2.pom -> /nix/store/mv42fc5gizl8h5g5vpywz1nfiynmzgp2-antlr-2.7.2.pom
├── aopalliance
│   └── aopalliance
│       └── 1.0
│           ├── aopalliance-1.0.jar -> /nix/store/yy66cplfasm9m5r61hi09vbk4mkk47rl-aopalliance-1.0.jar
```

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

(Tagging recent committers to the file)
CC Maintainers: @charles-dyfis-net

### CODE REVIEW

**Comment by fzakaria** [comment]
I ran _nixfmt_ on the source as well, so that's the cause of the additional non-logical changes.

**Comment by doronbehar** [comment]
Wow it looks like a lot of effort has been put into this.

**Comment by fzakaria** [comment]
Yea it's been a while since I posted it. ☺️

I really like the link farm usage when I was using it since you can skip downloading artifacts if you change your pom file.

**Comment by addict3d** [comment]
This looks really great!

I have a project that could use it, but currently, I cannot give a timeline for when I might test that out.

**Comment by shlevy** [comment]
Sorry for the delay, this looks good!

**Pull request merged**
