### PR TITLE
Revert "pkgs/top-level/config.nix: nixfmt, declare options"

### PR DESCRIPTION
**Pull request by eclairevoyant**
Reverts NixOS/nixpkgs#330753 due to master breakage; will need a new PR and testing in the future.

CC @philiptaron

### CODE REVIEW

**Comment by philiptaron** [comment]
The failing test is here: https://github.com/NixOS/nixpkgs/pull/330753#issuecomment-2269456839

**Comment by philiptaron** [comment]
I think it's fine to merge a revert even if the CI fails. @eclairevoyant, did you generate this commit with `git revert` or manually?

**Comment by philiptaron** [comment]
I validated using `nixpkgs-review` and `nixpkgs-manual` and the test case provided.

**Comment by philiptaron** [comment]
@spiage is master fine for you now?

**Comment by spiage** [comment]
Yes =)
```
Version 15449 -> 15450:
  nixos-system-a7: 24.11.20240805.6be7a53 → 24.11.20240805.fb7d848
  source: +14.1 KiB
```

**Comment by alyssais** [comment]
Please include reasons for reverts in commit messages.

**Pull request merged**
