### PR TITLE
tree-sitter: 0.23.0 -> 0.24.3

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Things done

- **tree-sitter: 0.23.0 -> 0.24.3**
- **tree-sitter: update grammars**

Changelog: https://github.com/tree-sitter/tree-sitter/blob/v0.24.3/CHANGELOG.md

cc @Profpatsch

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by fabianhjr — CHANGES_REQUESTED** [review]
Hi @GaetanLepage, thanks for contributing.

Due to the number of rebuilds this needs to target the staging branch.

Reference: https://github.com/NixOS/nixpkgs/blob/nixos-24.05/CONTRIBUTING.md#staging

**Comment by GaetanLepage** [comment]
> Due to the number of rebuilds this needs to target the staging branch.

You are definitely right. It is my first time updating tree-sitter and I did not realize that the number of rebuilds was so huge.

**Comment by khaneliman** [comment]
@GaetanLepage I was looking into a tree-sitter grammar thing and noticed this PR. You still interested in pursuing this or waiting until after release?

**Comment by GaetanLepage** [comment]
> @GaetanLepage I was looking into a tree-sitter grammar thing and noticed this PR. You still interested in pursuing this or waiting until after release?

Sorry, I took a bit of time to respond.
I have just rebased on `staging` and updated to the last version as of now (0.24.3).

**Comment by fabianhjr** [comment]
diff lgtm, haven't build anything

**Review by fabianhjr — COMMENTED** [review]
diff lgtm, haven't build anything

**Review by fabianhjr — APPROVED** [review]

**Comment by ribru17** [comment]
I believe this PR needs to update the wing grammar repo (to winglang/tree-sitter-wing), see #347612 (which I made before seeing this😅)

**Comment by GaetanLepage** [comment]
> I believe this PR needs to update the wing grammar repo (to winglang/tree-sitter-wing), see #347612 (which I made before seeing this😅)

This is already the case: https://github.com/NixOS/nixpkgs/pull/346198/files#diff-41844ea2eb04470a1c22a613c7cbfaefc8a2ae172defc394bb0f1f6be6e3660eL426

**Comment by ribru17** [comment]
Yeah sorry I shouldve mentioned that part is already updated, but I did it incompletely when I updated it as the json file must be updated as well. Maybe something else too? Afk right now but I can check soon

**Comment by GaetanLepage** [comment]
> Looks like they might be talking about https://github.com/NixOS/nixpkgs/pull/347612/files?diff=unified&w=0#diff-8075e8bc2f4964196151b271eae73d5f962146260cd712470560fdbfb32a9fc8L2-L7 and https://github.com/NixOS/nixpkgs/pull/347612/files?diff=unified&w=0#diff-380eb11bc1b25db921eca3698da3fc59c42bb7aff9d7b01ba8b04340c1f034aeL76 ?

According to me, those changes have been made in the meantime and are already effective in my tree.

**Comment by ribru17** [comment]
According to github search? This checks the default branch only; unless I am very mistaken I don't think staging has these changes. Not when I checked out staging locally (and my rebase tip was more recent than this branch's). Otherwise no diff would even be shown in github on my pr

**Comment by khaneliman** [comment]
> According to github search? This checks the default branch only; unless I am very mistaken I don't think staging has these changes. Not when I checked out staging locally (and my rebase tip was more recent than this branch's). Otherwise no diff would even be shown in github on my pr

Just browsing the file tree from different branches you can see them in staging. Staging gets master merged in frequently. 

https://github.com/NixOS/nixpkgs/blob/a445289eb9bae7534650b23a5796c6aa3565e678/pkgs/development/tools/parsing/tree-sitter/grammars/tree-sitter-wing.json#L2 
https://github.com/NixOS/nixpkgs/blob/a445289eb9bae7534650b23a5796c6aa3565e678/pkgs/development/tools/parsing/tree-sitter/update.nix#L424-L427

**Comment by ribru17** [comment]
Weird, I was mistaken then. Thanks for clarifying and sorry for dragging this out :)

**Comment by fabianhjr** [comment]
> I don't think staging has these changes

The main branch gets merged into staging-next and staging-next into staging every 6 hours or so by an automatic merge. If it didn't it very likely has those changes now.

**Pull request merged**
