### PR TITLE
coder: add update script

### PR DESCRIPTION
**Pull request by kylecarbs**
## Description of changes

Adds an `updateScript` to automatically update `coder` as new releases become available.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by superherointj** [comment]
I suggest you to not update the package. Just add the update script. And then, let the bot run the update script to update the package. So you can be sure it will work all right.

**Comment by kylecarbs** [comment]
Sure. Will change!

**Comment by kylecarbs** [comment]
@superherointj fixed!

**Comment by superherointj** [comment]
I'd recommend testing to run script locally in the update script directory and also at top-level of nixpkgs.
Depending on how the script is triggered, it may be meaningful. IIRC, the bot uses top-level. And maintainers often trigger locally.

**Comment by kylecarbs** [comment]
@superherointj fixed to `cd` first.

**Comment by superherointj** [comment]
Because GitHub imposes a limit on API requests, it's good practice to add GITHUB_TOKEN to API requests. See:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/cluster/fluxcd/update.sh#L10

**Comment by kylecarbs** [comment]
@superherointj fixed!

**Review by superherointj — APPROVED** [review]
LGTM.

Waiting CI/eval to merge.

Watch for logs at: https://r.ryantm.com/log/coder/

Eventually [in days] the bot will open a PR attempting to upgrade the package.
Then you review/approve it, and forward me for review/merge.

Welcome to Nixpkgs.

**Comment by kylecarbs** [comment]
@superherointj seems like the build failed: https://r.ryantm.com/log/coder/2024-04-14.log

I'm unsure what to do in this situation; it looks like something infrastructure-related. I'd appreciate any help!

**Comment by kylecarbs** [comment]
@superherointj fix here: https://github.com/NixOS/nixpkgs/pull/304314

**Pull request merged**
