### PR TITLE
Update arduino package from 1.0.6 to 1.6.5-r3

### PR DESCRIPTION
**Pull request by joshuafcole**

### CODE REVIEW

**Comment by joshuafcole** [comment]
There were some nontrivial changes to the build process, and all due credit to clever in the #nixos irc for helping me debug them.

**Comment by bjornfor** [comment]
I'm getting build failure:

```
$ nix-build -A arduino
...
untar-unzip-download:
      [get] Getting: http://downloads.arduino.cc/reference-1.6.0.zip
      [get] To: /tmp/nix-build-arduino-1.6.5-r3.drv-0/Arduino-1.6.5-r3-src/build/shared/reference-1.6.0.zip
      [get] Error getting http://downloads.arduino.cc/reference-1.6.0.zip to /tmp/nix-build-arduino-1.6.5-r3.drv-0/Arduino-1.6.5-r3-src/build/shared/reference-1.6.0.zip

untar-unzip-checksum:
     [echo] Testing checksum of "shared/reference-1.6.0.zip"
 [checksum] Could not find file /tmp/nix-build-arduino-1.6.5-r3.drv-0/Arduino-1.6.5-r3-src/build/shared/reference-1.6.0.zip to generate checksum for.

BUILD FAILED
/tmp/nix-build-arduino-1.6.5-r3.drv-0/Arduino-1.6.5-r3-src/build/build.xml:83: The following error occurred while executing this line:
/tmp/nix-build-arduino-1.6.5-r3.drv-0/Arduino-1.6.5-r3-src/build/build.xml:637: The following error occurred while executing this line:
/tmp/nix-build-arduino-1.6.5-r3.drv-0/Arduino-1.6.5-r3-src/build/build.xml:149: The following error occurred while executing this line:
/tmp/nix-build-arduino-1.6.5-r3.drv-0/Arduino-1.6.5-r3-src/build/build.xml:726: Could not find file /tmp/nix-build-arduino-1.6.5-r3.drv-0/Arduino-1.6.5-r3-src/build/shared/reference-1.6.0.zip to generate checksum for.
```

It's the same issue as in https://github.com/NixOS/nixpkgs/pull/6694.

**Comment by joshuafcole** [comment]
Ah shoot, I hadn't found that PR when looking for anyone else having tried. Do you have any recommendations on how to fix it? I can think of some fairly complicated solutions like MitMing ant to deliver a local file, but ideally there's some better solution than that.

**Comment by bjornfor** [comment]
Not really. Just the generic "pre-download the file with nix and find a way to give the file to the package build system so that it doesn't try to fetch the file itself"...

**Comment by joshuafcole** [comment]
As I try to fix this, how can I reproduce your error? The Travis build was successful.

**Comment by bjornfor** [comment]
Enable chroot builds in nix.

**Comment by brodul** [comment]
@joshuafcole I also updated Arduino to 1.6.5 (no rc).
Also managed to get the Digispark board working. 
But my build is also fetching resources while in build phase. So I will work on that.

**Comment by d4g** [comment]
@brodul I am also interested in getting digispark working. How did you manage to get it working? Did you patch the additional libs after you downloaded them with the arduino gui? Or did you manage to automate this process with a nix package?

**Comment by brodul** [comment]
@d4g I patched them manually. Added myself to `dialout` group.

```
patchelf --set-interpreter /nix/store/mibabdfiaznqaxqiy4bqhj3m9gaj45km-glibc-2.21/lib/ld-linux.so.2 --set-rpath /nix/store/jkycidwj1m3ai9pr3xj078924rq0avmz-gcc-4.9.3/lib/ launcher
patchelf --set-interpreter /nix/store/483br9kb3f5igsgmb6aqsjhl2ipj2bxr-glibc-2.21/lib/ld-linux-x86-64.so.2 --set-rpath /nix/store/rfw2anwm0h7fz4gqjx3r9gr2dgkfdy0p-libusb-compat-0.1.5/lib  micronucleus
```
You also need to add some `udev` rules:
https://github.com/micronucleus/micronucleus/wiki/Ubuntu-Linux

**Comment by domenkozar** [comment]
@joshuafcole care to update the PR with fixes from @brodul ?

**Comment by domenkozar** [comment]
Would be nice to get this into 16.03, which will branch off this weekend :)

**Comment by joshuafcole** [comment]
Apologies for the slow response. I've been a bit swamped with work lately so haven't had time for my arduino and nix hobbies lately. I'm still interested in getting a newer arduino into nixpkgs, but, like @brodul, I solved the problems manually and have been using that. I unfortunately don't have the know-how in arduino's build process to avoid the package fetching step, and hosting it elsewhere and trying to circumvent it feels both fragile and shady. I took a quick look at @brodul's patch and don't see how that resolves @bjornfor's concern either (though if it does, fantastic!) If that's the case, I think he should be the one to get the credit for merging it into the mainline. If there's anything else I can do to help, please let me know.

**Comment by brodul** [comment]
@joshuafcole your observations are correct. It does not. Our branches are similar, but yours is cleaner. I will try to fix the issue, but I can't tell when, but definitely for the next stable release.

**Comment by joachifm** [comment]
Closing in favour of https://github.com/NixOS/nixpkgs/pull/17060

**Pull request closed without merging**
