### PR TITLE
python3Packages.import-expression: 1.1.4 -> 1.1.5

### PR DESCRIPTION
**Pull request by StarrFox**
## Description of changes

updates version to 1.1.5, the main change this version is that tests are included in the pypi source dists so we don't need to pull from github anymore

the patch is also no longer needed as it was merged in this version

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by itslychee** [comment]
Thanks for the PR, if you wouldn't mind, could you update the `nativeBuildInputs` and `propagatedBuildInputs` field names to `build-system` and `dependencies` respectively, the Python wrapper was recently updated to have clearer naming on where deps go.

https://nixos.org/manual/nixpkgs/unstable/#buildpythonpackage-function
https://github.com/NixOS/nixpkgs/pull/271597

**Review by itslychee — APPROVED** [review]

**Comment by StarrFox** [comment]
> Thanks for the PR, if you wouldn't mind, could you update the `nativeBuildInputs` and `propagatedBuildInputs` field names to `build-system` and `dependencies` respectively, the Python wrapper was recently updated to have clearer naming on where deps go.
> 
> https://nixos.org/manual/nixpkgs/unstable/#buildpythonpackage-function #271597

done

**Comment by itslychee** [comment]
Thank you, if you could rewrite the commit message to be like `python3Packages.import-expression: update legacy attributes` to follow the commit conventions that'd be wonderful!

**Comment by itslychee** [comment]
silly bot

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 314735` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python312Packages.import-expression</li>
    <li>python312Packages.import-expression.dist</li>
    <li>python312Packages.jishaku</li>
    <li>python312Packages.jishaku.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.import-expression</li>
    <li>python311Packages.import-expression.dist</li>
    <li>python311Packages.jishaku</li>
    <li>python311Packages.jishaku.dist</li>
  </ul>
</details>

**Comment by tomberek** [comment]
Might want something like:
```
diff --git a/pkgs/development/python-modules/import-expression/default.nix b/pkgs/development/python-modules/import-expression/default.nix
index 3407aa277152..34f49401996d 100644
--- a/pkgs/development/python-modules/import-expression/default.nix
+++ b/pkgs/development/python-modules/import-expression/default.nix
@@ -6,6 +6,7 @@
   pytestCheckHook,
   astunparse,
   setuptools,
+  pythonAtLeast,
 }:
 buildPythonPackage rec {
   pname = "import-expression";
@@ -36,6 +37,7 @@ buildPythonPackage rec {
       psfl
     ];
     mainProgram = "import-expression";
+    broken = pythonAtLeast "3.12";
     maintainers = with lib.maintainers; [ lychee ];
   };
 }
```

or fix the issue

**Comment by tomberek** [comment]
merging, as this doesn't make the breakage worse, but still recommend addressing python312

**Comment by StarrFox** [comment]
> Might want something like:
> 
> ```
> diff --git a/pkgs/development/python-modules/import-expression/default.nix b/pkgs/development/python-modules/import-expression/default.nix
> index 3407aa277152..34f49401996d 100644
> --- a/pkgs/development/python-modules/import-expression/default.nix
> +++ b/pkgs/development/python-modules/import-expression/default.nix
> @@ -6,6 +6,7 @@
>    pytestCheckHook,
>    astunparse,
>    setuptools,
> +  pythonAtLeast,
>  }:
>  buildPythonPackage rec {
>    pname = "import-expression";
> @@ -36,6 +37,7 @@ buildPythonPackage rec {
>        psfl
>      ];
>      mainProgram = "import-expression";
> +    broken = pythonAtLeast "3.12";
>      maintainers = with lib.maintainers; [ lychee ];
>    };
>  }
> ```
> 
> or fix the issue

https://github.com/ioistired/import-expression/commit/e1b5c76912898dc6d34af7057283d0c9dcc226c0

new version of package which fixes the 3.12 issue out now

**Comment by itslychee** [comment]
Not really sure why they bumped the major version as there doesn't seem to be anything breaking, but regardless I think it's okay to bump the package's major version, unsure of what the policy is around that.

**Pull request merged**
