### PR TITLE
nixos/fontconfig: Fix compatibility with unstable apps

### PR DESCRIPTION
**Pull request by jtojnar**
Fontconfig 2.14 from unstable reverted back to using /etc/fonts/fonts.conf
for its configuration. Unfortunately, on NixOS 20.03, this still points
to configuration for Fontconfig 2.10, with cache version 3.

When an app linked against Fontconfig 2.14 reads the config and does not
find a compatible cache, it writes a new cache entries to ~/.cache/fontconfig.
Unfortunately, the fontconfig 2.14 uses the same cache version as 2.12 in 20.03 (7)
so when the apps from 20.03 later read the cache, they cannot make much sense
of it and are unable to find any fonts.

I added a new fonts.fontconfig.disableVersionedFontConfiguration option, which,
when enabled, makes /etc/fonts/fonts.conf point to the configuration file
for the latest fontconfig, instead of the ancient 2.10 version.
This is necessary to prevent packages from Nixpkgs unstable breaking apps
from 20.03.

Enabling this should not cause any issues as there are no programs
using the legacy fontconfig version since NixOS 15.03.

Unfortunately, if a person already ran an app from unstable
before applying this patch, they will need to delete ~/.cache/fontconfig manually.

Closes: #97418
cc @worldofpeace @samueldr

### CODE REVIEW

**Comment by jtojnar** [comment]
I confirmed in 20.03 VM with this patch, that running piper from unstable no longer creates the cache in user's profile. (And running it with `FONTCONFIG_FILE=/etc/fonts/2.10/fonts.conf` still does.)

**Review by Ma27 — APPROVED** [review]
Initially stumbled upon this yesterday. Can confirm that this patch fixes the issue.

**Review by worldofpeace — COMMENTED** [review]
Post commit I am approving :+1:  thanks.

**Comment by xuguojun168** [comment]
I have met the same problem when I run pywebio with deepin-linux.
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
Option 'sandbox' is unknown. Ignoring.
It is too big bug.

**Pull request merged**
