### PR TITLE
nixos/containers: fix imperative containers

### LINKED ISSUE #67174: nixos/tests/containers-imperative.nix broken
**Describe the bug**
Imperative container test broken
https://hydra.nixos.org/build/98994622

**To Reproduce**
`nix-build nixos/tests/containers-imperative.nix`

**Additional context**
Bisect reveals #66846 as the cause

cc @uvNikita

### PR DESCRIPTION
**Pull request by uvNikita**
###### Motivation for this change
Fixes #67174.

Unfortunately, we have to duplicate `INSTANCE = "%i"` in both places due to how `//` is merging values: `{ env.a = 1; env.b = 2; } // { env.a = 3; }` returns `{ env.a = 3; }`. Let me know if there is a better way.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @mmahut @srhb

### CODE REVIEW

**Comment by srhb** [comment]
You could either use `recursiveUpdate` instead of `//` on the top merge, or simply `environment = unit.environment // ...` locally, if you want.

**Comment by uvNikita** [comment]
@srhb Didn't know about `recursiveUpdate`, thanks for the tip!

**Comment by srhb** [comment]
Welcome!

Looks like the test succeeds now, but I think something is broken related to container shutdown. Compare these logs from this PR and current unstable respectively.

I've included everything from the last `nixos-container destroy foo`: https://gist.github.com/srhb/5355fd5b2970bf86596f6373530ba951

**Comment by uvNikita** [comment]
Good catch! I think this is the root cause:

> machine# [   47.117609] container foo[8800]: cat: /run/containers/foo.pid: No such file or directory

It seems like we, unfortunately, can't declare /run/containers as a runtime directory of the service because we are using it after it exited.

Tests should be fixed now.

**Comment by srhb** [comment]
Great! Looks good, thanks!

**Pull request merged**
