### PR TITLE
staging-next 2024-05-15 - last for 24.05

### PR DESCRIPTION
**Pull request by vcunat**
This is the last staging-next iteration that will reach 24.05.  (But there will be `staging*-24.05` afterwards, as usual.)

There should be no breaking changes in this one (desktops have an exception but probably unused now).

##### Helpful links

- workflow docs: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#staging
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/309297
- - - 
##### Mass breakages
_nothing notable so far_

### CODE REVIEW

**Comment by vcunat** [comment]
Let me mention the 24.05 schedule: #303285

**Comment by ivan** [comment]
The libjpeg-turbo 3.0.3 upgrade breaks rawtherapee, which breaks photoprism. 

```
[100%] Linking CXX executable rawtherapee
/nix/store/c3vg6xnafaz7pqv9g6di3az8qsl9cq41-binutils-2.41/bin/ld: ../rtengine/librtengine.a(jdatasrc.cc.o): in function `my_jpeg_std_error':
jdatasrc.cc:(.text+0x545): undefined reference to `jpeg_std_message_table'
collect2: error: ld returned 1 exit status
make[2]: *** [rtgui/CMakeFiles/rth.dir/build.make:2692: rtgui/rawtherapee] Error 1
make[1]: *** [CMakeFiles/Makefile2:191: rtgui/CMakeFiles/rth.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

https://github.com/libjpeg-turbo/libjpeg-turbo/issues/763

https://github.com/Beep6581/RawTherapee/issues/7074

**Comment by vcunat** [comment]
- [ ] at this point I'd address that at rawtherapee side

**Comment by vcunat** [comment]
Linux regressions seem merge-able to me.  Just one thing really caught my eye (not a blocker):
- [ ] `wine*staging` gets blocked by a failure in some perl package
  https://hydra.nixos.org/build/260294662
  
Darwin is still missing quite a lot of binaries, but I hope it will all be fine to merge later today.

**Comment by vcunat** [comment]
Current comparison: https://hydra.nixos.org/eval/1806436?compare=1806431#tabs-now-fail

**Pull request merged**
