### PR TITLE
quassel: 0.12.5 -> 0.13.0

### PR DESCRIPTION
**Pull request by Lucus16**
###### Motivation for this change

0.13.0 came out a few weeks ago. @Phreedom @ttuegel does this look ok?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Lucus16** [comment]
I don't mind. I've temporarily given you access to my fork.

**Comment by worldofpeace** [comment]
@Lucus16 I think if you've checked `Allow edits from maintainers` I'll be able to push since I'm a maintainer.

**Comment by Lucus16** [comment]
Ah, I didn't know that, cool.

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build quassel quasselClient quasselDaemon

And now I'm just checking if it builds. I've already tested execution of `quassel` locally and it looked good.

Results for the build will be here https://github.com/NixOS/nixpkgs/pull/53049/checks

**Comment by Lucus16** [comment]
I'm running `quasselDaemon` on my server and it runs fine.

**Comment by Lucus16** [comment]
Tried `quasselClient`, that works fine too.

**Comment by worldofpeace** [comment]
@Lucus16 great, I merge this in that case.

**Comment by worldofpeace** [comment]
@Lucus16 Thanks :sparkles:

**Pull request merged**
