### PR TITLE
nodePackages: Add official tailwindcss plugins

### PR DESCRIPTION
**Pull request by srid**
###### Motivation for this change

Extend https://github.com/NixOS/nixpkgs/pull/149839 -- which adds tailwindcss cli -- by adding the four [official tailwind plugins](https://tailwindcss.com/docs/plugins#official-plugins).

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by srid** [comment]
I've tested this on macOS, using the following packages:

```nix
                  pkgs.nodePackages.tailwindcss
                  pkgs.nodePackages.postcss
                  pkgs.nodePackages."@tailwindcss/typography"
                  pkgs.nodePackages."@tailwindcss/aspect-ratio"
                  pkgs.nodePackages."@tailwindcss/forms"
                  pkgs.nodePackages."@tailwindcss/line-clamp"
```

The CLI runs with all the 4 plugins enabled in `tailwind.config.js`:

```js
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/line-clamp'),
    require('@tailwindcss/aspect-ratio')
  ]
```

With this PR, it would normally fail trying to find any of these plugins.

Finally, with this change, I can get tailwindcss running without writing a `package.json` or depending on npm.

**Comment by srid** [comment]
Can you review @Mic92? This PR builds on top of #149839 which was merged by you.

**Comment by austinbutler** [comment]
Maybe I am using it wrong, but it doesn't seem to be working for me.

`default.nix`:
```nix
with import <nixpkgs> { };

let
  tailwindWithPlugins = (import
    (builtins.fetchTarball {
      url =
        "https://github.com/NixOS/nixpkgs/archive/f73c4b132ef883af92a34208050e527d4e95c6ba.tar.gz";
      sha256 = "11dywadg62rj3w9ap87yxrxrdn23994900sdmnwlpcnwc6p5x9gl";
    })
    { }).nodePackages;
in
pkgs.mkShell rec {
  buildInputs = [
    tailwindWithPlugins.postcss
    tailwindWithPlugins.tailwindcss
    tailwindWithPlugins."@tailwindcss/typography"
  ];
}
```

`tailwind --help`:
```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'postcss'
Require stack:
- /nix/store/ggmj53c299b20n4sblgxq7bh2hjfdpqm-tailwindcss-3.0.11/lib/node_modules/tailwindcss/lib/lib/generateRules.js
- /nix/store/ggmj53c299b20n4sblgxq7bh2hjfdpqm-tailwindcss-3.0.11/lib/node_modules/tailwindcss/lib/lib/expandTailwindAtRules.js
- /nix/store/ggmj53c299b20n4sblgxq7bh2hjfdpqm-tailwindcss-3.0.11/lib/node_modules/tailwindcss/lib/processTailwindFeatures.js
- /nix/store/ggmj53c299b20n4sblgxq7bh2hjfdpqm-tailwindcss-3.0.11/lib/node_modules/tailwindcss/lib/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/nix/store/ggmj53c299b20n4sblgxq7bh2hjfdpqm-tailwindcss-3.0.11/lib/node_modules/tailwindcss/lib/lib/generateRules.js:6:39)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/ggmj53c299b20n4sblgxq7bh2hjfdpqm-tailwindcss-3.0.11/lib/node_modules/tailwindcss/lib/lib/generateRules.js',
    '/nix/store/ggmj53c299b20n4sblgxq7bh2hjfdpqm-tailwindcss-3.0.11/lib/node_modules/tailwindcss/lib/lib/expandTailwindAtRules.js',
    '/nix/store/ggmj53c299b20n4sblgxq7bh2hjfdpqm-tailwindcss-3.0.11/lib/node_modules/tailwindcss/lib/processTailwindFeatures.js',
    '/nix/store/ggmj53c299b20n4sblgxq7bh2hjfdpqm-tailwindcss-3.0.11/lib/node_modules/tailwindcss/lib/cli.js'
  ]
}
```

Using the same `default.nix` but with rev 46821ea01c8f54d2a20f5a503809abfc605269d7 (current NixOS unstable):

`tailwind --help`:
```
tailwindcss v3.0.8
...
```

This is on NixOS. Maybe the `tailwindcss` update broke something?

**Comment by austinbutler** [comment]
To test I checked out latest master branch, ran the Node generate script, then ran `./result/bin/tailwindcss --help`. I end up with `tailwindcss` 3.0.14 and indeed it fails with the same error from above. So it seems `nodePackages.tailwindcss` is set to break with the next update of Node packages.

**Comment by srid** [comment]
I'm closing because obviously it is not working, but someone feel free pick it up. I had to fix that postcss issue by fixing NODE_PATH:

https://github.com/srid/tailwind-nix/blob/e27e11a66ae26533b265eb826eec357fbf481c92/flake.nix#L20-L29

**Comment by srid** [comment]
> I had to fix that postcss issue by fixing NODE_PATH

Which is just a workaround. I'm sure a proper fix would be something else.

**Comment by lobre** [comment]
Just to understand, is the above PR https://github.com/NixOS/nixpkgs/pull/155433 sufficient to allow the packaging of the official tailwind plugins? Or were there any other blockers?

**Comment by srid** [comment]
I am yet to test it, but going by this diff in that PR, I'd say it *probably should* resolve it.

image

**Comment by austinbutler** [comment]
@lobre I wanted to at least get `tailwindcss` itself working properly, and I am unsure whether plugins are considered appropriate or not for inclusion to nixpkgs. I'd certainly like them to be there, makes it easier to use, just unsure as a matter of what's best for nixpkgs.

**Comment by rycee** [comment]
I just opened #159564 that adds plugin support. Please have a look.

**Pull request closed without merging**
