### PR TITLE
edgedb: 4.1.1 -> 5.1.0

### PR DESCRIPTION
**Pull request by 0x50F1A**
## Description of changes

- Update source from `4.1.1` to `5.1.0`
- Re-vendor `Cargo.lock`
- Fix ELF patch
- Format with nixfmt

Diff: https://github.com/edgedb/edgedb-cli/compare/v4.1.1...v5.1.0

Changelog: https://docs.edgedb.com/changelog/5_x

## Things done

```sh
nix shell .#edgedb
edgedb -V
edgedb project init
# ...
edgedb
select "foo";
# {'foo'}
\quit
edgedb instance destroy -I nixpkgs --force
edgedb branch
rm -rf dbschema
rm edgedb.toml
```

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kirillrdy** [comment]
while release notes don't include words such as "breaking changes"

there is 


> The CLI will first check to see if your schema will migrate cleanly to EdgeDB 5.0. If the upgrade check finds any problems, it will report them back to you.

currently all branches are in 

> Restrict all breaking changes with the exception of desktop environments

I would recommend to wait until 24.05 is released

**Comment by ahirner** [comment]
> Format with nixfmt

Thx!
Builds and works for `x86_64-darwin`.

> currently all branches are in

I observed that `5.1.0` does provide hints in a sane way, e.g. before changing `dbschema/migration` formats:

image

Anyway, I support to not backport and add a release note for 24.05.

This would still go to unstable, or is there another staging mechanism @kirillrdy ? Pardon if that should be obvious from `Contributing.md`.

**Comment by kirillrdy** [comment]
as per https://github.com/NixOS/nixpkgs/issues/303285

> 2024-05-01 	all branches 	Restrict all breaking changes with the exception of desktop environments

you can set PR to draft and wait until `Branch-off` then it can be merged into master and will be part of 24.11 release

this all, assuming 5.x is considered "breaking changes" release, that I don't have a strong opinion about

**Review by ahirner — APPROVED** [review]
Breaking changes (FWIW) got unrestricted as of 2014-05-15.

**Comment by kirillrdy** [comment]
> Breaking changes (FWIW) got unrestricted as of 2014-05-15.

Only for staging branch

**Pull request merged**
