### PR TITLE
cosmic-packages: move to new cargo fetcher

### PR DESCRIPTION
**Pull request by JohnRTitor**
Manually did it by hand. Though we should probably consider creating a script to get rid of other excess Cargo.locks.

Originally intended as part of https://github.com/NixOS/nixpkgs/pull/356385 but split to make reviews easier

CC: https://github.com/NixOS/nixpkgs/issues/327063

Closes https://github.com/NixOS/nixpkgs/pull/356821

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by a-kenji** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 356539`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 20 packages built:</summary>
  <ul>
    <li>cosmic-applibrary</li>
    <li>cosmic-bg</li>
    <li>cosmic-comp</li>
    <li>cosmic-comp.debug</li>
    <li>cosmic-design-demo</li>
    <li>cosmic-edit</li>
    <li>cosmic-files</li>
    <li>cosmic-greeter</li>
    <li>cosmic-launcher</li>
    <li>cosmic-notifications</li>
    <li>cosmic-osd</li>
    <li>cosmic-panel</li>
    <li>cosmic-randr</li>
    <li>cosmic-session</li>
    <li>cosmic-settings</li>
    <li>cosmic-settings-daemon</li>
    <li>cosmic-store</li>
    <li>cosmic-term</li>
    <li>cosmic-workspaces-epoch</li>
    <li>cosmic-workspaces-epoch.debug</li>
  </ul>
</details>

**Review by a-kenji — APPROVED** [review]
Thank you for splitting this in to reviewable chunks.

I have not tried *every* functionality of the packages in here, but ran every output against master to see if they match up.

For programs like `cosmic-edit` I tried them out manually.

**Review by nyabinary — APPROVED** [review]

**Comment by JohnRTitor** [comment]
@ofborg build cosmic-applibrary cosmic-bg cosmic-comp cosmic-design-demo cosmic-edit cosmic-files cosmic-greeter cosmic-launcher cosmic-notifications cosmic-osd cosmic-panel cosmic-randr cosmic-session cosmic-settings cosmic-settings-daemon cosmic-store cosmic-term cosmic-workspaces-epoch

**Comment by JohnRTitor** [comment]
> Originally git repos were fetched sequentially outside of the multiprocessing part.

Perhaps it should respect `enableParallelBuilding`?

**Comment by TomaSajt** [comment]
@ofborg build cosmic-applibrary.cargoDeps cosmic-bg.cargoDeps cosmic-comp.cargoDeps cosmic-design-demo.cargoDeps cosmic-edit.cargoDeps cosmic-files.cargoDeps cosmic-greeter.cargoDeps cosmic-launcher.cargoDeps cosmic-notifications.cargoDeps cosmic-osd.cargoDeps cosmic-panel.cargoDeps cosmic-randr.cargoDeps cosmic-session.cargoDeps cosmic-settings.cargoDeps cosmic-settings-daemon.cargoDeps cosmic-store.cargoDeps cosmic-term.cargoDeps cosmic-workspaces-epoch.cargoDeps

**Comment by TomaSajt** [comment]
@ofborg build cosmic-applibrary.cargoDeps cosmic-bg.cargoDeps cosmic-comp.cargoDeps cosmic-design-demo.cargoDeps cosmic-edit.cargoDeps cosmic-files.cargoDeps cosmic-greeter.cargoDeps cosmic-launcher.cargoDeps cosmic-notifications.cargoDeps cosmic-osd.cargoDeps cosmic-panel.cargoDeps cosmic-randr.cargoDeps cosmic-session.cargoDeps cosmic-settings.cargoDeps cosmic-settings-daemon.cargoDeps cosmic-store.cargoDeps cosmic-term.cargoDeps cosmic-workspaces-epoch.cargoDeps

**Comment by TomaSajt** [comment]
@ofborg build cosmic-applibrary cosmic-bg cosmic-comp cosmic-design-demo cosmic-edit cosmic-files cosmic-greeter cosmic-launcher cosmic-notifications cosmic-osd cosmic-panel cosmic-randr cosmic-session cosmic-settings cosmic-settings-daemon cosmic-store cosmic-term cosmic-workspaces-epoch

**Comment by TomaSajt** [comment]
Okay, seems like decreasing the concurrency limit works for OfBorg. I didn't encounter issues locally, even when trying to build all cargoDeps at the same time. Opened a separate PR and cherry picked its commit into this PR.

**Comment by TomaSajt** [comment]
I also saw that https://github.com/NixOS/nixpkgs/pull/356743/ added some retry logic, maybe that could also be incorporated later.

**Comment by ahoneybun** [comment]
@JohnRTitor does this change stop us from using nix-update to update our packaging?

**Comment by JohnRTitor** [comment]
@ofborg build cosmic-applibrary cosmic-bg cosmic-comp cosmic-design-demo cosmic-edit cosmic-files cosmic-greeter cosmic-launcher cosmic-notifications cosmic-osd cosmic-panel cosmic-randr cosmic-session cosmic-settings cosmic-settings-daemon cosmic-store cosmic-term cosmic-workspaces-epoch

**Comment by JohnRTitor** [comment]
It won't "stop" you, nix update just isn't compatible with it since it's a new fetcher. See https://github.com/Mic92/nix-update/issues/298, PRs welcome there

**Comment by SuperSandro2000** [comment]
That tastes good :P

image

**Pull request merged**
