### PR TITLE
Remove empty go vendor deps

### PR DESCRIPTION
**Pull request by roberth**
###### Motivation for this change

A little discovery I've made when introducing the `emptyDirectory` package #126680: these vendor directories are empty.

cc @NixOS/golang in case this is new information that's useful somehow.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Should we blacklist that hash and throw an error if it is used?

**Comment by roberth** [comment]
An empty vendor derivation doesn't seem to be a real problem. By turning it into an error, we are creating a potential problem.
Perhaps the vendor directory fetcher could suggest setting `null` here instead of setting a hash.
Or perhaps this corner case should be noted somewhere in a comment.

Whether we merge or close this pr is rather inconsequential. If this little discovery doesn't lead to any relevant insights for the go maintainers, that's also ok and they can ignore this.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126682` at 4acb93c1 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built successfully:</summary>
  <ul>
    <li>bombadillo</li>
    <li>gjo</li>
    <li>kubectl-example</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl3` is a deprecated license, please check if project uses `gpl3Plus` or `gpl3Only` and change `meta.license` accordingly.

Near pkgs/applications/networking/browsers/bombadillo/default.nix:26:5:
```
   |
26 |     license = licenses.gpl3;
   |     ^
```
</li>
  </ul>
</details>

**Comment by Mic92** [comment]
> Should we blacklist that hash and throw an error if it is used?

I would make it a lint check instead in nixpkgs-hammering instead.

**Comment by SuperSandro2000** [comment]
https://github.com/jtojnar/nixpkgs-hammering/issues/116

**Comment by zowoq** [comment]
> Perhaps the vendor directory fetcher could suggest setting `null` here instead of setting a hash.

Opened a PR for this https://github.com/NixOS/nixpkgs/pull/212024.

**Comment by siraben** [comment]
@Artturin might be interesting to add to https://github.com/nix-community/nixpkgs-lint

**Pull request merged**
