### PR TITLE
noteshrink: init at 0.1.1

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
Just saw this interesting little tool

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change (new package)
- [x] Tested execution of all binary files
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by rnhmjoj** [comment]
@grahamcOfBorg build noteshrink

**Comment by rnhmjoj** [comment]
@nlewo is it too late to cherry pick it into 18.03?

**Comment by nlewo** [comment]
@rnhmjoj I've cherry picked it.

**Comment by rnhmjoj** [comment]
Thank you!

**Pull request merged**
