### PR TITLE
flutter: 3.13.8 -> 3.16.4

### PR DESCRIPTION
**Pull request by hatch01**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

I tried to update flutter package. However, I don't know how to update the hash of other platforms.

### CODE REVIEW

**Comment by FlafyDev** [comment]
Can you try this for hashes.nix?

```nix
{
  "54a7145303f0dd9d0f93424a2e124eb4abef5091" = {
    skyNotice = "sha256-1rkOkTJwwfFRh1r3DjylUN4mV93UGKyfbu/r5Tsdi4g=";
    flutterNotice = "sha256-pZjblLYpD/vhC17PkRBXtqlDNRxyf92p5fKJHWhwCiA=";
    android-arm = {
      "artifacts.zip" = "sha256-mpMtAyKMotZz1PDXMuFkLBU7nXZZUEE+ZvJC/0HT19I=";
    };
    android-arm-profile = {
      "artifacts.zip" = "sha256-CrMWldUmYk1vd4wzYhnphtAdrah4JrSdPSl53iUoJ0M=";
      "linux-x64.zip" = "sha256-etVFjBI2Ip/Z9fSXsgIHEHZZ8ufL/l74NEOHnqy4BS4=";
      "darwin-x64.zip" = "sha256-a/Iujytz2whX8wzZo2HANEcDEF3J5/zMy0rVFHHXQ3g=";
    };
    android-arm-release = {
      "artifacts.zip" = "sha256-4+iTBR+O353sSwXU+hHbfY9sj1stjObviEHkhRyBTzg=";
      "linux-x64.zip" = "sha256-2JbLrWZQOm+sNVmum+tbL4AUdJ4ASnKrEM1v/WtcEqA=";
      "darwin-x64.zip" = "sha256-OVrVU7yNAxVzh6RNWJGKEqw52k1evDY6Ju+8Se2WecE=";
    };
    android-arm64 = {
      "artifacts.zip" = "sha256-XnY0a+rmj1VCBOTxieRghVScAgUsXEjXqBepOEdy88s=";
    };
    android-arm64-profile = {
      "artifacts.zip" = "sha256-R+tnoRAkDxo33EeT5JrdgWwXpIVSBtywn8q2MGiSTlc=";
      "linux-x64.zip" = "sha256-FiWcnYDyEgTYT+I46M4dN7mURTb6UZP74yfVZyUfa2I=";
      "darwin-x64.zip" = "sha256-lHNs3NFE3nRJg1ZhkTNcP+WZauVNCInfs06CK3jeG4c=";
    };
    android-arm64-release = {
      "artifacts.zip" = "sha256-KgK3Wk38bZy9RxutaVuk6HwznrxS4GBjqo/g9Y6RI5E=";
      "linux-x64.zip" = "sha256-BvI6p1SHf3ablWXefiu1Cfm3rWbghnDuBgPny5G8DWg=";
      "darwin-x64.zip" = "sha256-51oNX2FGj06yKgW3piwtvjvl0gdyboeOaoiR/1wAY/M=";
    };
    android-x64 = {
      "artifacts.zip" = "sha256-6mdJ29C67rL5y6OpHvmdPcVZzQRHzLN/0D4eld50D68=";
    };
    android-x64-profile = {
      "artifacts.zip" = "sha256-aPmXIPWj81Jj+Wbw8mxYyBFaqoTaGk0HliigPOhyEEU=";
      "linux-x64.zip" = "sha256-gJAvF4KincOHUu408GgZIkJHtPF7KaEDczIpCp+GYow=";
      "darwin-x64.zip" = "sha256-i4XyehtqnNJYLtgwJx7Df1ZEeF4zxp0EltIQHvnv/WA=";
    };
    android-x64-release = {
      "artifacts.zip" = "sha256-zWOAREw+rj6L9I+wZxRWzKr1cwivvVequUurkjTbeUc=";
      "linux-x64.zip" = "sha256-l+xrwGVNiZAC53Tn8aIfiMZNKOMXGhIAQaelRCCodI8=";
      "darwin-x64.zip" = "sha256-O25gxbI5+1s7bM10vnBiBb8bqppbcr5myFP2WBG9494=";
    };
    android-x86 = {
      "artifacts.zip" = "sha256-SfCn92Al4O8BKbPdWp2FbaAaadOub9IrIkjDXlfEkes=";
    };
    android-x86-jit-release = {
      "artifacts.zip" = "sha256-nwE1zCqO4LhEt1b3dAYBStDs6iVyDCwWWPIZ9FPetzU=";
    };
    darwin-arm64 = {
      "artifacts.zip" = "sha256-kdgsj89zA17OernmXyomI2wfTSUJxb+lubr4AHXrYik=";
      "font-subset.zip" = "sha256-NEN4x96RyRvJnQMuQjmQddIm+3aWzuIwmmg1jRmwmOA=";
    };
    darwin-arm64-profile = {
      "artifacts.zip" = "sha256-Rqp5b3StavBF+pwn8MPgZgUNOYtizxp0y+jP2hlPETw=";
    };
    darwin-arm64-release = {
      "artifacts.zip" = "sha256-QsnGpVlSWvP1HB66+iv1CcyuFSnTDfOIRVahwVpSReU=";
    };
    darwin-x64 = {
      "FlutterEmbedder.framework.zip" = "sha256-I+HWKU3Y3ifB6lsIewKEG8MFHMTuK2fq+JofVFBnv00=";
      "FlutterMacOS.framework.zip" = "sha256-s/593FHymgsJyjyGQiwNMC8nybdFCPg5XjV26unSMco=";
      "artifacts.zip" = "sha256-1TjPYPGPw9AJ/mvB7dO7kfvfNgGyOe5DX8WDPC9JWS0=";
      "font-subset.zip" = "sha256-BL7xU+pyQMW/EB05X5A3Dkrz+46v8PPUauGoO+KeyBc=";
      "gen_snapshot.zip" = "sha256-HSRasNmoQLnhNdvtKKNeJn4x3EAvltLb0M+IzoDsWnw=";
    };
    darwin-x64-profile = {
      "FlutterMacOS.framework.zip" = "sha256-kw4esoj9mubPEGE4OokP7a7QEMFzUPAmutxORJWZndM=";
      "artifacts.zip" = "sha256-iUX2Psy8n199O/jVHEhhzuZ7RcQBTbdMKMGn5Dtc3SI=";
      "gen_snapshot.zip" = "sha256-aj2jDnFCFcwoiAND/K1Vjec7QiUb4Bs48HYvfeHm6pE=";
    };
    darwin-x64-release = {
      "FlutterMacOS.dSYM.zip" = "sha256-7OlJ3wiciY1JBpoCCQ+pKOivhIlL+M0D4Zx9p/bXUbk=";
      "FlutterMacOS.framework.zip" = "sha256-uafJ7X//jUyLwWBD9PFyc8q7ECMH1OaQGzMk4KkvcX0=";
      "artifacts.zip" = "sha256-hSqcnf68Hv1H8AEk8x0X7m8bSWw8GNbb6We8mgw4M18=";
      "gen_snapshot.zip" = "sha256-y2zl/Z6hWgqQ3D4uk2CHqtrw/wjix1un+fAf53gzzA8=";
    };
    "flutter_patched_sdk.zip" = "sha256-SjGccH51cUF8EEmzSQRxHrgHhB27QniptNOoSB4kaLQ=";
    "flutter_patched_sdk_product.zip" = "sha256-BBqeN34ZATXH9A56eg4xN38TfpXdUeTfh0bYkY/Pyp0=";
    ios = {
      "artifacts.zip" = "sha256-jLc6AlV8ZGWNgZ8Ss4NS2jp5HUH2RJLS1qpJNyqWWXM=";
    };
    ios-profile = {
      "artifacts.zip" = "sha256-ENeZF3H0X+3YZMvPRFgl+CiiSiFyvgaQvBSCZphMUVY=";
    };
    ios-release = {
      "Flutter.dSYM.zip" = "sha256-2Jkuo+sdTCVSspi2HVHoRG0qZ5KWumKD8WFWDiDGMNA=";
      "artifacts.zip" = "sha256-8z+TrpqWeyzZqV3fHGmzA1dVJHq8D/ORcWZ2v+C6g8g=";
    };
    linux-arm64 = {
      "artifacts.zip" = "sha256-PFs4h/jufdPedgO8szoD2uTUUvYecKJaM1Lx2UcAJIw=";
      "font-subset.zip" = "sha256-h8jd3aGp/mdn/u2A21fqIovyNK5oGGKmVh4QCb6+xIw=";
    };
    linux-arm64-debug = {
      "linux-arm64-flutter-gtk.zip" = "sha256-T8VunH262m0pyDeoEaJ1gpwqcqQurmhygO6+A9polgw=";
    };
    linux-arm64-profile = {
      "linux-arm64-flutter-gtk.zip" = "sha256-jhs9XzM9trhLJ/wa/ySmQoxYiTfYpMUenI4dtwn83zE=";
    };
    linux-arm64-release = {
      "linux-arm64-flutter-gtk.zip" = "sha256-KOMuSJ4LJSgMFA8HoBuzx2T+I4Xi0F0uqKGnC8SK60s=";
    };
    linux-x64 = {
      "artifacts.zip" = "sha256-UtwMVBNvXZYY/v7i61FBhRSd6BlXj0mL9aMm+wcs9Sw=";
      "font-subset.zip" = "sha256-8HXNeaOtt7Ia/Y4sr82Z6YSDKRvznAGyherT21fu8aU=";
    };
    linux-x64-debug = {
      "linux-x64-flutter-gtk.zip" = "sha256-HKkRWnVhGZ1EFlhRrxxCCAH6P79iU9uIhehZLplJBEE=";
    };
    linux-x64-profile = {
      "linux-x64-flutter-gtk.zip" = "sha256-ujTwiLlLGlT9OEhabYR8euFV4ZRm+TWfmuDSKLP6Kwg=";
    };
    linux-x64-release = {
      "linux-x64-flutter-gtk.zip" = "sha256-7AhY2nZLK5WPoVvNZk4WHjHs7zE27/HsUD33l4UNmuY=";
    };
  };
}
```

I had to nix build with `--keep-going` and manually replace the hashes.
I turned on `supportsDarwin` and `supportsIOS`. And I changed some of the flutter nix code to allow me to download more darwin and arm exclusive stuff without actually owning such devices.

This needs to change and I hope it does when https://github.com/NixOS/nixpkgs/pull/262789 is merged(I think I can easily make an update script for its new method).
The problem is that the creator of the PR doesn't seem to be working on the PR anymore. I tried reaching them on Matrix but no response. I think I'll try to clone the PR and fix the few issues with it myself. (Probably after this PR is merged)

Additionally, this should be the hashes for flutter and dart

```nix
{
  inherit wrapFlutter;
  stable = mkFlutter {
    version = "3.16.4";
    engineVersion = "54a7145303f0dd9d0f93424a2e124eb4abef5091";
    dartVersion = "3.2.3";
    dartHash = {
      x86_64-linux = "sha256-mPR7HS8GdJD37FmBPYoFPUo+jHlSVz2epzYu1dX4WmA=";
      aarch64-linux = "sha256-2Qa+VVbV5vdcuKn75+2Xkk9vQ0ycBVv+mRjSnMJTB8o=";
      x86_64-darwin = "sha256-KU1/2wLOIIsb6K4wFy4/4sxTc0oYVSgZWa4Mi01cr/Y=";
      aarch64-darwin = "sha256-Y2lBBAATz46PI+bJ3LUSOLQA7LVITNAd/Ti+jz048cw=";
    };
    flutterHash = rec {
      x86_64-linux = "sha256-L+PEk2VR6jDEOJpcKrjAwxKnqfu/o1fZJZAiT27L7s0=";
      aarch64-linux = x86_64-linux;
      x86_64-darwin = "sha256-aeuJ8vEG2kgWY1uOgd4OemJou6IlyT6Dsb82vlbgBSM=";
      aarch64-darwin = "sha256-9VvIEC8KMOdTNkcON8SNiipUISmemCyxpkyCp+FqVNM=";
    };
    patches = flutter3Patches;
  };
}
```

**Review by FlafyDev — CHANGES_REQUESTED** [review]
see comment

**Comment by hatch01** [comment]
Thank you very much for your help.
I will add these modifications quickly.
And yeah it would be super cool to have an update script to update easily.

**Comment by FlafyDev** [comment]
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>expidus.file-manager</li>
    <li>firmware-updater</li>
    <li>fluffychat</li>
    <li>intiface-central</li>
    <li>localsend</li>
    <li>yubioath-flutter</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>flutter</li>
    <li>flutter-unwrapped (flutterPackages.stable)</li>
    <li>flutter-unwrapped.cache (flutterPackages.stable.cache)</li>
    <li>hover</li>
  </ul>
</details>

Flutter works for me. But I guess these applications need an update or something.. I'll try to find fixes

**Comment by hatch01** [comment]
> Result of `nixpkgs-review pr 275522` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 6 packages failed to build:
> 4 packages built:
> 
> Flutter works for me. But I guess these applications need an update or something.. I'll try to find fixes

Don't really know how, but maybe we can pin them to the old flutter version to wait for their update, which could take a while?

**Comment by FlafyDev** [comment]
> > Result of `nixpkgs-review pr 275522` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> > 6 packages failed to build:
> > 4 packages built:
> > 
> > Flutter works for me. But I guess these applications need an update or something.. I'll try to find fixes
> 
> Don't really know how, but maybe we can pin them to the old flutter version to wait for their update, which could take a while?

Yeah I agree. I managed to successfully build firmware updater after changing hashes and fluffychat after updating it. But we probably shouldn't do that just to update flutter.

If the corresponding maintainers want they can update to the new flutter version(which not necessary every package supports yet)


I guess it will look like this?

default.nix

```nix
...
in
{
  inherit wrapFlutter;
  v3_16_4 = mkFlutter { ... };
  v3_13_8 = mkFlutter { ... };
}
```

all-packages.nix

```nix
  flutterPackages =
    recurseIntoAttrs (callPackage ../development/compilers/flutter { });
  flutter-unwrapped = flutterPackages.v3_16_4;
  flutter = flutterPackages.wrapFlutter flutter-unwrapped;
  flutter-3_13_8 = flutterPackages.wrapFlutter flutterPackages.v3_13_8;
```

not sure what to do about changes in the patches between versions, though.

**Comment by drupol** [comment]
I'm locking and closing this pull request, because through the rebase you inadvertently requested many maintainers for review, which subscribed them to update notifications, resulting in unnecessary spam inside everyone's inbox. While we can remove their review requests, we sadly cannot unsubscribe anyone.

Please create a new pull request and for the next time remember to set your PR to draft status before rebasing. In draft status, you can preview the list of maintainers that are about to be requested for review, which allows you to sidestep this issue.

**Pull request closed without merging**
