### PR TITLE
docker-compose: 1.29.2 -> 2.6.0

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
`v2` is packaged as `docker-compose_2`, might be able to drop the `v1` derivation and rename the top-level attr?
https://github.com/NixOS/nixpkgs/blob/cbd66894e60294c14b20b34b4a00950cb224a897/pkgs/applications/virtualization/docker/compose.nix#L4-L5
https://github.com/NixOS/nixpkgs/blob/cbd66894e60294c14b20b34b4a00950cb224a897/pkgs/applications/virtualization/docker/default.nix#L139

**Comment by SuperSandro2000** [comment]
> `v2` is packaged as `docker-compose_2`, might be able to drop the `v1` derivation and rename the top-level attr?

I am not super sure about that. docker-compose 1 and 2 are totally different and 2 does not support everything 1 did.

**Comment by bachp** [comment]
> I am not super sure about that. docker-compose 1 and 2 are totally different and 2 does not support everything 1 did.

- Version 1 is a python script using docker in the background. It's invoked via `docker-compose`.
- Version 2 is implemented as a docker plugin. It is invoked as a docker sub command `docker compose`.

On arch linux they v1 with v2 but also added a [symlink](https://github.com/archlinux/svntogit-community/blob/packages/docker-compose/trunk/PKGBUILD#L40) so that typing `docker-compse` keeps working.
Not sure if this applies on nixos to.

So far I didn't find any incompatibilities between the two.

**Comment by SuperSandro2000** [comment]
See https://docs.docker.com/compose/cli-command-compatibility/

**Comment by zowoq** [comment]
PR to change `docker-compose` to `v2` but keeping `docker-compose_1`: https://github.com/NixOS/nixpkgs/pull/176217

**Comment by SuperSandro2000** [comment]
Closing in favor of the linked PR

**Pull request closed without merging**
