### PR TITLE
nginx service improvements

### PR DESCRIPTION
**Pull request by ghost**
To address https://github.com/NixOS/nixpkgs/issues/5832

### CODE REVIEW

**Comment by lethalman** [comment]
Can we lower to 1sec? 10 sec is really too much in my opinion.

**Comment by arno01** [comment]
@lethalman it's not good as it will throw `start request repeated too quickly for nginx.service`

see as below, just tried:

```
[root@www:~/nixpkgs]# journalctl -b  |grep -v 'rejected connection' |tail -500 |egrep "emerg|nginx.service"
Jan 19 16:51:15 www nginx[22347]: nginx: [emerg] unknown directive "blablabla" in /nix/store/hash-nginx.conf:24
Jan 19 16:51:15 www systemd[1]: nginx.service: main process exited, code=exited, status=1/FAILURE
Jan 19 16:51:15 www systemd[1]: Unit nginx.service entered failed state.
Jan 19 16:51:15 www systemd[1]: nginx.service failed.
Jan 19 16:51:16 www systemd[1]: nginx.service holdoff time over, scheduling restart.
Jan 19 16:51:16 www nginx[22366]: nginx: [emerg] unknown directive "blablabla" in /nix/store/hash-nginx.conf:24
Jan 19 16:51:16 www systemd[1]: nginx.service: main process exited, code=exited, status=1/FAILURE
Jan 19 16:51:16 www systemd[1]: Unit nginx.service entered failed state.
Jan 19 16:51:16 www systemd[1]: nginx.service failed.
Jan 19 16:51:17 www systemd[1]: nginx.service holdoff time over, scheduling restart.
Jan 19 16:51:17 www nginx[22376]: nginx: [emerg] unknown directive "blablabla" in /nix/store/hash-nginx.conf:24
Jan 19 16:51:17 www systemd[1]: nginx.service: main process exited, code=exited, status=1/FAILURE
Jan 19 16:51:17 www systemd[1]: Unit nginx.service entered failed state.
Jan 19 16:51:17 www systemd[1]: nginx.service failed.
Jan 19 16:51:19 www systemd[1]: nginx.service holdoff time over, scheduling restart.
Jan 19 16:51:19 www nginx[22384]: nginx: [emerg] unknown directive "blablabla" in /nix/store/hash-nginx.conf:24
Jan 19 16:51:19 www systemd[1]: nginx.service: main process exited, code=exited, status=1/FAILURE
Jan 19 16:51:19 www systemd[1]: Unit nginx.service entered failed state.
Jan 19 16:51:19 www systemd[1]: nginx.service failed.
Jan 19 16:51:20 www systemd[1]: nginx.service holdoff time over, scheduling restart.
Jan 19 16:51:20 www nginx[22392]: nginx: [emerg] unknown directive "blablabla" in /nix/store/hash-nginx.conf:24
Jan 19 16:51:20 www systemd[1]: nginx.service: main process exited, code=exited, status=1/FAILURE
Jan 19 16:51:20 www systemd[1]: Unit nginx.service entered failed state.
Jan 19 16:51:20 www systemd[1]: nginx.service failed.
Jan 19 16:51:21 www systemd[1]: nginx.service holdoff time over, scheduling restart.
Jan 19 16:51:21 www systemd[1]: start request repeated too quickly for nginx.service
Jan 19 16:51:21 www systemd[1]: Unit nginx.service entered failed state.
Jan 19 16:51:21 www systemd[1]: nginx.service failed.
```

5 times tried to restart and gave up with ` start request repeated too quickly for nginx.service `

**Comment by arno01** [comment]
Might be a good idea to add `Use StartLimitBurst= to configure how many starts per interval are allowed`
not sure what's the default value of it.

or keep it to at least `5s` ..  
actually the same should be done in the dovecot commit https://github.com/NixOS/nixpkgs/pull/5845  where you changed it to `1s`

**Comment by lethalman** [comment]
@arno01 we can think of it. It's certainly an improvement over the previous `Restart=no` default. It's so dependent on the target the system, that after all you can change those values. It's not that we can decide a good value for every system, as this is mainly an hack for a more graceful failure by default.

I have no strong opinion on this, except that 10s is too much.

**Comment by arno01** [comment]
This delay `5s` doesn't generate any friction, but only ensures that the service is started.
If it was anyway started from the first time, then it wasn't delayed at all as it is `RestartSec` parameter `on-failure` only.
So when something is wrong, it will give it `5s` or `10s` before retrying.. and this `something is wrong` might really need `5s` as we know the `dhcpd` problem now https://github.com/NixOS/nixpkgs/issues/5832#issuecomment-70471743 ...

with `1s` it will try just 4-5 times which is not enough

**Comment by arno01** [comment]
@lethalman okay then, `5s` should be enough

**Comment by lethalman** [comment]
Merging this, I think it's a good to have default.

**Pull request merged**
