### PR TITLE
gtk-vnc: 0.6.0 -> 0.7.0

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

Vulnerability Roundup, aka "Weekly playtime with @grahamc"

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
> "Weekly playtime with @grahamc"

😂 

/cc https://github.com/NixOS/nixpkgs/issues/22826

**Comment by 7c6f434c** [comment]
I think this PR needs a second part of «motivation»: motivation for not committing this directly to `master`?

**Review by 7c6f434c — APPROVED** [review]

**Comment by grahamc** [comment]
I'm guessing new-commit-bit nerves :)

**Comment by peterhoeg** [comment]
Actually it was more a case of "I don't use this package, so I cannot really tell if this broke anything".

**Pull request merged**
