### PR TITLE
Add section on fetching sources

### PR DESCRIPTION
**Pull request by edwtjo**
So this is another one of these opinion pieces

### CODE REVIEW

**Comment by devhell** [comment]
Might be worth mentioning all the other fetchers and how to use them? Maybe in the wiki and then link to there from your section?

**Comment by bjornfor** [comment]
Thinking out loud: I never understood the need for those fetchFrom* functions. IMHO, it is easier to use plain fetchzip, because then you can pass a single URL argument, instead of having to decompose the URL into owner, repo, rev. (I would have renamed fetchzip to fetcharchive though, since it also handles tarballs.)

**Comment by edwtjo** [comment]
@bjornfor the rationale for their existence is that they do provide a generalizable interface for a service, given the intention of fetching a specific revision of a package. If we would encode this external interface directly into each package and it would change that would be more work than just correcting the helper.

@devhell the intention was actually not to demonstrate the usage of fetchgit or fetchFromGitHub, they just happened to be convenient to use for the example, we don't have any helpers for monotone servers which exposes revisions over ftp in nixpkgs. Anyway I agree that the fetchers should be documented but let's start with this.

**Comment by lethalman** [comment]
@edwtjo just merge in my opinion, this is not written in the stone and people can change it at later time.

**Comment by edwtjo** [comment]
@lethalman Agreed. In general I think it is better to have a policy than not having one, even if I happen to disagree with it. It would be nice though if we had a more formalized way of reaching consensus regarding matters of policy.

Anyway to give some more background to this PR; It was prompted by [this SO question](http://stackoverflow.com/questions/29075927/how-to-modify-a-nixos-package-configuration). I think that it is good design not having proxied corporate users nixpkgoverride core(meaning very basic and almost always pulled in when switching) derivation src attributes, as it hinders adoption. The main felon here being `fetchgit + git://` combos.

**Pull request closed without merging**
