### PR TITLE
flameshot: 0.10.1 -> unstable-2021-10-17

### LINKED ISSUE #1975: Autostart doesn't work on NixOS
**Flameshot version**
Tested on both master and v0.11.1

**Describe the bug**

Autostart doesn't work.

On NixOS, if the directory `~/.config/autostart` doesn't exist, Flameshot will try to write the desktop file to somewhere in `/nix/store`. However, `/nix/store` is read-only, so that fails.

**To Reproduce**

Install Flameshot on NixOS. Launch it with `strace flameshot 2>&1 | grep open` so that we can observe where it tries to write files. When flipping `Launch at startup` in configuations, strace will print some like this:

```
openat(AT_FDCWD, "/nix/store/nkgiwqxc5i6fhkzm4lj8p11gjpclm5cj-plasma-workspace-5.21.5/etc/xdg/autostart/Flameshot.desktop", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = -1 EROFS (Read-only file system)
```

**Expected behavior**

The desktop file should be written to `~/.config/autostart`, creating the directory if necessary.

**System Information**

NixOS 21.05

### LINKED ISSUE #141873: flameshot: autostart doesn't work & bad desktop file
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: flameshot

current version: 0.10.1
desired version: master (7977cbb), see below for explanation

###### Notify maintainers

maintainers: @scode

###### Note for maintainers

Please tag this issue in your PR.

---

Currently, there're two issues that affacts flameshot in NixOS:

1. Autostart doesn't work when the directory `~/.config/autostart` doesn't exist (https://github.com/flameshot-org/flameshot/issues/1975)
2. Desktop file points to `/usr/bin/flameshot` instead of just `flameshot`

I've landed a [PR](https://github.com/flameshot-org/flameshot/pull/1979) that fixes issue 1. To fix issue 2, flameshot needs to be built with cmake flag `-DUSE_LAUNCHER_ABSOLUTE_PATH:BOOL=OFF`. This flag is also newly added (not present in v0.10.1).

We could upgrade right now, or wait for another minor release.

### PR DESCRIPTION
**Pull request by yizhepku**
###### Motivation for this change

This update fixes two problems:

1. autostart sometimes doesn't work in NixOS (fixed [upstream](https://github.com/flameshot-org/flameshot/issues/1975))
2. desktop file points to /usr/bin/flameshot instead of just flameshot
   (fixed by adding an extra cmake option)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by YizhePKU** [comment]
Fixes #141873.

**Review by newAM — APPROVED** [review]
##### Reviewed points

- [x] package name fits guidelines
- [x] package version fits guidelines
- [x] package build on aarch64-linux
- [x] package build on x86_64-linux
- [x] executables tested on x86_64-linux
- [x] all depending packages build

##### Comments

I double checked that this addresses the issues raised in #141873.  Thank you for fixing this!

**Comment by rycee** [comment]
Have you asked upstream if they can make a new release?

**Comment by YizhePKU** [comment]
> Have you asked upstream if they can make a new release? Alternatively, would it be possible to backport the patch to the released version?

I doubt they'll make a new release just for this, since it seems to only affact NixOS users. I could ask though.

Backporting the patch is hard, as the cmake option used in the second fix is newly added (not in v0.10.1).

**Comment by rycee** [comment]
Wouldn't the path be possible to fix by just doing a `substituteInPlace` on the generated desktop file? My main concern is that changing the package version to 2021-10-17 will effectively freeze the installed version for people who still use imperative package installs, i.e., `nix-env -u` will not do any upgrade of flameshot if this package in the future goes back to a release version such as 0.11 or whatever.

**Comment by YizhePKU** [comment]
> Wouldn't the path be possible to fix by just doing a substituteInPlace on the generated desktop file

Yes, that's doable.

> My main concern is that changing the package version to 2021-10-17 will effectively freeze the installed version for people who still use imperative package installs, i.e., nix-env -u will not do any upgrade of flameshot if this package in the future goes back to a release version such as 0.11 or whatever.

In that case could we just mark the version something like "0.10.2pre1"? 

I made this PR partly because @NewAM show me some upgrade-to-unstable PRs that were merged. They did not seem to be troubled by it.

* [tinycc: 0.9.27 -> unstable-2021-10-09 #141201](https://github.com/NixOS/nixpkgs/pull/141201)
* [pamixer: 1.4 -> unstable-2021-03-29 #139961](https://github.com/NixOS/nixpkgs/pull/139961)

**Comment by oxalica** [comment]
I'd prefer to patch them instead of updating to git version, just because updating stable to git doesn't worth it.

We should apply this patch and `substituteInPlace` the desktop file.
https://github.com/flameshot-org/flameshot/commit/7977cbb52c2d785abd0d85d9df5991e8f7cae441.patch

**Pull request closed without merging**
