### PR TITLE
sqlpage : 0.15.1 -> 0.20.0

### PR DESCRIPTION
**Pull request by guiguid**
## Description of changes
Update SQLPage to [0.20.0 release](https://github.com/lovasoa/SQLpage/releases)
with apexcharts@3.47.0 and @tabler/icons@2.47.0

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [X] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by starsep — APPROVED** [review]

**Comment by luftmensch-luftmensch** [comment]
https://github.com/lovasoa/SQLpage/releases/tag/v0.20.5

**Comment by guiguid** [comment]
Hi, sure ! 
waiting the merge of my 0.20.0 in order to propose 0.20.5

https://github.com/guiguid/nixpkgs/commit/1790fd80fa082e8892772be472b0e9218ccf7ef9

**Comment by luftmensch-luftmensch** [comment]
> Hi, sure ! waiting the merge of my 0.20.0 in order to propose 0.20.5
> 
> [guiguid@1790fd8](https://github.com/guiguid/nixpkgs/commit/1790fd80fa082e8892772be472b0e9218ccf7ef9)

Why not just do one?

**Comment by guiguid** [comment]
I don't want going for 2 others months for review.
Reviewers are very busy, and sqlpage updates are faster than review ;-) .
Please vote this PR if you like Sqlpage.

When waiting for merge, you can do : 
```nix
git clone --depth 2 https://github.com/guiguid/nixpkgs.git ./mynixpkgs
git checkout sqlpage-latest
export NIXPKGS=/home/yourname/path/to/mynixpkgs
nix-build -I nixpkgs=$NIXPKGS -A sqlpage
# to run
/nix/store/aaabbbbbddddd4444rrreeee-sqlpage-0.20.5/bin/sqlpage
# or
./result/bin/sqlpage
```

**Comment by pbsds** [comment]
aarch64-linux failure expected https://hydra.nixos.org/build/260634016

**Pull request merged**
