### PR TITLE
php84: 8.4.0RC4 -> 8.4.1

### PR DESCRIPTION
**Pull request by pan93412**
- **php84: 8.4.0RC4 -> 8.4.1**
- **php-packages: remove the merged soap patch** (https://github.com/php/php-src/pull/16733)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by drupol — APPROVED** [review]
Diff LGTM - But I would wait for the official announcement before merging this, so we make sure that upstream hasn't rebuilt the official source archive.

**Comment by pan93412** [comment]
> Diff LGTM - But I would wait for the official announcement before merging this, so we make sure that upstream hasn't rebuilt the official source archive.

<https://www.php.net/index.php#2024-11-21-4>. It has been announced today. Note that I still prefer to wait the test passed before merging this.

**Comment by drupol** [comment]
Oh boy... sorry about this :)

Waiting for tests to be done goes without saying !

I'll merge this as soon as this is green.

**Comment by drupol** [comment]
@ofborg build php84

**Comment by drupol** [comment]
@ofborg build php84

**Comment by piotrkwiecinski** [comment]
This should also be backported to 24.11

**Comment by drupol** [comment]
Looks like there's a build issue:

```
PASS Bug #80763 (msgfmt_format() does not accept DateTime references) [tests/bug80763.phpt] 
gcc: warning:  -DZEND_COMPILE_DL_EXT=1: linker input file unused because linking not done
gcc: error:  -DZEND_COMPILE_DL_EXT=1: linker input file not found: No such file or directory
make: *** [Makefile:206: apc.lo] Error 1
checking pkg-config is at least version 0.9.0... yes
error: builder for '/nix/store/dh7rkk42hyjb48c41yimyyr6cy0y8x1x-php-apcu-5.1.23.drv' failed with exit code 2;
       last 10 log lines:
       > configure: creating ./config.status
       > config.status: creating config.h
       > Running phase: buildPhase
       > build flags: SHELL=/nix/store/0irlcqx2n3qm6b1pc9rsd2i8qpvcccaj-bash-5.2p37/bin/bash EXTENSION_DIR=\$\(out\)/lib/php/extensions phpincludedir=\$\(dev\)/include
       > /nix/store/0irlcqx2n3qm6b1pc9rsd2i8qpvcccaj-bash-5.2p37/bin/bash /build/source/libtool --tag=CC --mode=compile gcc -I. -I/build/source -I/nix/store/lkcbqnwg5sh196yjiry3h6nwnvbwyqgf-php-8.4.1-dev/include/php -I/nix/store/lkcbqnwg5sh196yjiry3h6nwnvbwyqgf-php-8.4.1-dev/include/php/main -I/nix/store/lkcbqnwg5sh196yjiry3h6nwnvbwyqgf-php-8.4.1-dev/include/php/TSRM -I/nix/store/lkcbqnwg5sh196yjiry3h6nwnvbwyqgf-php-8.4.1-dev/include/php/Zend -I/nix/store/lkcbqnwg5sh196yjiry3h6nwnvbwyqgf-php-8.4.1-dev/include/php/ext -I/nix/store/lkcbqnwg5sh196yjiry3h6nwnvbwyqgf-php-8.4.1-dev/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   \ -DZEND_COMPILE_DL_EXT=1 -c /build/source/apc.c -o apc.lo  -MMD -MF apc.dep -MT apc.lo
       > mkdir .libs
       >  gcc -I. -I/build/source -I/nix/store/lkcbqnwg5sh196yjiry3h6nwnvbwyqgf-php-8.4.1-dev/include/php -I/nix/store/lkcbqnwg5sh196yjiry3h6nwnvbwyqgf-php-8.4.1-dev/include/php/main -I/nix/store/lkcbqnwg5sh196yjiry3h6nwnvbwyqgf-php-8.4.1-dev/include/php/TSRM -I/nix/store/lkcbqnwg5sh196yjiry3h6nwnvbwyqgf-php-8.4.1-dev/include/php/Zend -I/nix/store/lkcbqnwg5sh196yjiry3h6nwnvbwyqgf-php-8.4.1-dev/include/php/ext -I/nix/store/lkcbqnwg5sh196yjiry3h6nwnvbwyqgf-php-8.4.1-dev/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE " -DZEND_COMPILE_DL_EXT=1" -c /build/source/apc.c -MMD -MF apc.dep -MT apc.lo  -fPIC -DPIC -o .libs/apc.o
       > gcc: warning:  -DZEND_COMPILE_DL_EXT=1: linker input file unused because linking not done
       > gcc: error:  -DZEND_COMPILE_DL_EXT=1: linker input file not found: No such file or directory
       > make: *** [Makefile:206: apc.lo] Error 1
       For full logs, run 'nix-store -l /nix/store/dh7rkk42hyjb48c41yimyyr6cy0y8x1x-php-apcu-5.1.23.drv'.
```

**Comment by piotrkwiecinski** [comment]
There is new tag for https://github.com/krakjoe/apcu/releases/tag/v5.1.24 maybe we need to bump it too

**Comment by piotrkwiecinski** [comment]
I'll PR it

**Comment by Ma27** [comment]
@piotrkwiecinski  Eh, I already prepared it while reviewing this PR.
Would push the update here and merge then.

**Review by Ma27 — APPROVED** [review]
With the commit I just pushed, all tests in nixos/tests/php pass for me with 8.4.

**Review by piotrkwiecinski — APPROVED** [review]

**Comment by Ma27** [comment]
@drupol I just pushed it into this PR, I didn't see a reason to split it off :)

**Comment by drupol** [comment]
Oh ! I haven't see it :) all good then !

**Review by drupol — APPROVED** [review]

**Pull request merged**
