### PR TITLE
zstd: 1.4.9 -> 1.5.0

### PR DESCRIPTION
**Pull request by IvarWithoutBones**
###### Motivation for this change
Required for a recent version of a package i maintain.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 124870` at 1a982862 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>296 packages marked as broken and skipped:</summary>
  <ul>
    <li>adobe-reader</li>
    <li>adoptopenjdk-hotspot-bin-13</li>
    <li>adoptopenjdk-hotspot-bin-14</li>
    <li>adoptopenjdk-jre-hotspot-bin-13</li>
    <li>adoptopenjdk-jre-hotspot-bin-14</li>
    <li>adoptopenjdk-jre-openj9-bin-13</li>
    <li>adoptopenjdk-jre-openj9-bin-14</li>
    <li>adoptopenjdk-openj9-bin-13</li>
    <li>adoptopenjdk-openj9-bin-14</li>
    <li>airtame</li>
    <li>attract-mode</li>
    <li>autotrace</li>
    <li>blastem</li>
    <li>capture</li>
    <li>cassandra_2_1</li>
    <li>cassandra_2_2</li>
    <li>clang-sierraHack</li>
    <li>clang-sierraHack-stdenv</li>
    <li>clickshare-csc1</li>
    <li>curaByDagoma</li>
    <li>cura_stable</li>
    <li>darwin.CF</li>
    <li>dcraw</li>
    <li>displaycal</li>
    <li>dr14_tmeter</li>
    <li>dvd-slideshow</li>
    <li>eagle7</li>
    <li>electron_3</li>
    <li>electron_4</li>
    <li>electron_5</li>
    <li>epsxe</li>
    <li>erlang_basho_R16B02</li>
    <li>eterm</li>
    <li>evilvte</li>
    <li>ffmpeg_2</li>
    <li>ffmpeg_2_8</li>
    <li>ffmpeg_3</li>
    <li>ffmpeg_3_4</li>
    <li>git-dit</li>
    <li>gitin</li>
    <li>globalplatform</li>
    <li>gnash</li>
    <li>gnuradio3_7</li>
    <li>gnuradio3_7Packages.ais</li>
    <li>gnuradio3_7Packages.gnuradio</li>
    <li>gnuradio3_7Packages.gsm</li>
    <li>gnuradio3_7Packages.limesdr</li>
    <li>gnuradio3_7Packages.nacl</li>
    <li>gnuradio3_7Packages.osmosdr</li>
    <li>gnuradio3_7Packages.rds</li>
    <li>go_1_14</li>
    <li>gogoclient</li>
    <li>googleearth-pro</li>
    <li>gppcscconnectionplugin</li>
    <li>gpshell</li>
    <li>grass</li>
    <li>green-pdfviewer</li>
    <li>gtmess</li>
    <li>gvisor</li>
    <li>hadoop</li>
    <li>hadoop_2_7</li>
    <li>hadoop_2_8</li>
    <li>hadoop_2_9</li>
    <li>hplipWithPlugin_3_16_11</li>
    <li>hplipWithPlugin_3_18_5</li>
    <li>hplip_3_16_11</li>
    <li>hplip_3_18_5</li>
    <li>hydrus</li>
    <li>impressive</li>
    <li>intecture-cli</li>
    <li>invoice2data</li>
    <li>jboss</li>
    <li>jfbpdf</li>
    <li>jfbview</li>
    <li>julia</li>
    <li>julia-lts</li>
    <li>julia_10</li>
    <li>k2pdfopt</li>
    <li>keyfinder</li>
    <li>libav</li>
    <li>libav_0_8</li>
    <li>libav_11</li>
    <li>libav_12</li>
    <li>libgit2_0_27</li>
    <li>libgroove</li>
    <li>libnats-c</li>
    <li>libvirt_5_9_0</li>
    <li>linuxPackages_hardkernel_4_14.acpi_call</li>
    <li>linuxPackages_hardkernel_4_14.akvcam</li>
    <li>linuxPackages_hardkernel_4_14.amdgpu-pro</li>
    <li>linuxPackages_hardkernel_4_14.anbox</li>
    <li>linuxPackages_hardkernel_4_14.asus-wmi-sensors</li>
    <li>linuxPackages_hardkernel_4_14.batman_adv</li>
    <li>linuxPackages_hardkernel_4_14.bbswitch</li>
    <li>linuxPackages_hardkernel_4_14.bcc</li>
    <li>linuxPackages_hardkernel_4_14.bpftrace</li>
    <li>linuxPackages_hardkernel_4_14.broadcom_sta</li>
    <li>linuxPackages_hardkernel_4_14.can-isotp</li>
    <li>linuxPackages_hardkernel_4_14.chipsec</li>
    <li>linuxPackages_hardkernel_4_14.cryptodev</li>
    <li>linuxPackages_hardkernel_4_14.ddcci-driver</li>
    <li>linuxPackages_hardkernel_4_14.digimend</li>
    <li>linuxPackages_hardkernel_4_14.dpdk</li>
    <li>linuxPackages_hardkernel_4_14.ena</li>
    <li>linuxPackages_hardkernel_4_14.evdi</li>
    <li>linuxPackages_hardkernel_4_14.exfat-nofuse</li>
    <li>linuxPackages_hardkernel_4_14.facetimehd</li>
    <li>linuxPackages_hardkernel_4_14.fwts-efi-runtime</li>
    <li>linuxPackages_hardkernel_4_14.gcadapter-oc-kmod</li>
    <li>linuxPackages_hardkernel_4_14.hid-nintendo</li>
    <li>linuxPackages_hardkernel_4_14.isgx</li>
    <li>linuxPackages_hardkernel_4_14.it87</li>
    <li>linuxPackages_hardkernel_4_14.ixgbevf</li>
    <li>linuxPackages_hardkernel_4_14.jool</li>
    <li>linuxPackages_hardkernel_4_14.lttng-modules</li>
    <li>linuxPackages_hardkernel_4_14.mba6x_bl</li>
    <li>linuxPackages_hardkernel_4_14.mbp2018-bridge-drv</li>
    <li>linuxPackages_hardkernel_4_14.mwprocapture</li>
    <li>linuxPackages_hardkernel_4_14.mxu11x0</li>
    <li>linuxPackages_hardkernel_4_14.ndiswrapper</li>
    <li>linuxPackages_hardkernel_4_14.netatop</li>
    <li>linuxPackages_hardkernel_4_14.nvidia_x11</li>
    <li>linuxPackages_hardkernel_4_14.nvidia_x11_beta</li>
    <li>linuxPackages_hardkernel_4_14.nvidia_x11_legacy340</li>
    <li>linuxPackages_hardkernel_4_14.nvidia_x11_legacy390</li>
    <li>linuxPackages_hardkernel_4_14.nvidia_x11_vulkan_beta</li>
    <li>linuxPackages_hardkernel_4_14.nvidiabl</li>
    <li>linuxPackages_hardkernel_4_14.openafs</li>
    <li>linuxPackages_hardkernel_4_14.openafs_1_8</li>
    <li>linuxPackages_hardkernel_4_14.openafs_1_9</li>
    <li>linuxPackages_hardkernel_4_14.openrazer</li>
    <li>linuxPackages_hardkernel_4_14.phc-intel</li>
    <li>linuxPackages_hardkernel_4_14.prl-tools</li>
    <li>linuxPackages_hardkernel_4_14.r8125</li>
    <li>linuxPackages_hardkernel_4_14.r8168</li>
    <li>linuxPackages_hardkernel_4_14.rtl8192eu</li>
    <li>linuxPackages_hardkernel_4_14.rtl8723bs</li>
    <li>linuxPackages_hardkernel_4_14.rtl8812au</li>
    <li>linuxPackages_hardkernel_4_14.rtl8814au</li>
    <li>linuxPackages_hardkernel_4_14.rtl8821au</li>
    <li>linuxPackages_hardkernel_4_14.rtl8821ce</li>
    <li>linuxPackages_hardkernel_4_14.rtl8821cu</li>
    <li>linuxPackages_hardkernel_4_14.rtl88x2bu</li>
    <li>linuxPackages_hardkernel_4_14.rtl88xxau-aircrack</li>
    <li>linuxPackages_hardkernel_4_14.rtlwifi_new</li>
    <li>linuxPackages_hardkernel_4_14.rtw88</li>
    <li>linuxPackages_hardkernel_4_14.sch_cake</li>
    <li>linuxPackages_hardkernel_4_14.sysdig</li>
    <li>linuxPackages_hardkernel_4_14.system76</li>
    <li>linuxPackages_hardkernel_4_14.system76-acpi</li>
    <li>linuxPackages_hardkernel_4_14.system76-io</li>
    <li>linuxPackages_hardkernel_4_14.systemtap</li>
    <li>linuxPackages_hardkernel_4_14.tbs</li>
    <li>linuxPackages_hardkernel_4_14.tp_smapi</li>
    <li>linuxPackages_hardkernel_4_14.tuxedo-keyboard</li>
    <li>linuxPackages_hardkernel_4_14.v4l2loopback</li>
    <li>linuxPackages_hardkernel_4_14.v86d</li>
    <li>linuxPackages_hardkernel_4_14.vendor-reset</li>
    <li>linuxPackages_hardkernel_4_14.vhba</li>
    <li>linuxPackages_hardkernel_4_14.virtualbox</li>
    <li>linuxPackages_hardkernel_4_14.virtualboxGuestAdditions</li>
    <li>linuxPackages_hardkernel_4_14.wireguard</li>
    <li>linuxPackages_hardkernel_4_14.xpadneo</li>
    <li>linuxPackages_hardkernel_4_14.zenpower</li>
    <li>linuxPackages_hardkernel_4_14.zfs</li>
    <li>linuxPackages_hardkernel_4_14.zfsStable</li>
    <li>linuxPackages_hardkernel_4_14.zfsUnstable</li>
    <li>linuxPackages_hardkernel_latest.acpi_call</li>
    <li>linuxPackages_hardkernel_latest.akvcam</li>
    <li>linuxPackages_hardkernel_latest.amdgpu-pro</li>
    <li>linuxPackages_hardkernel_latest.anbox</li>
    <li>linuxPackages_hardkernel_latest.asus-wmi-sensors</li>
    <li>linuxPackages_hardkernel_latest.batman_adv</li>
    <li>linuxPackages_hardkernel_latest.bbswitch</li>
    <li>linuxPackages_hardkernel_latest.bcc</li>
    <li>linuxPackages_hardkernel_latest.bpftrace</li>
    <li>linuxPackages_hardkernel_latest.broadcom_sta</li>
    <li>linuxPackages_hardkernel_latest.can-isotp</li>
    <li>linuxPackages_hardkernel_latest.chipsec</li>
    <li>linuxPackages_hardkernel_latest.cryptodev</li>
    <li>linuxPackages_hardkernel_latest.ddcci-driver</li>
    <li>linuxPackages_hardkernel_latest.digimend</li>
    <li>linuxPackages_hardkernel_latest.dpdk</li>
    <li>linuxPackages_hardkernel_latest.ena</li>
    <li>linuxPackages_hardkernel_latest.evdi</li>
    <li>linuxPackages_hardkernel_latest.exfat-nofuse</li>
    <li>linuxPackages_hardkernel_latest.facetimehd</li>
    <li>linuxPackages_hardkernel_latest.fwts-efi-runtime</li>
    <li>linuxPackages_hardkernel_latest.gcadapter-oc-kmod</li>
    <li>linuxPackages_hardkernel_latest.hid-nintendo</li>
    <li>linuxPackages_hardkernel_latest.isgx</li>
    <li>linuxPackages_hardkernel_latest.it87</li>
    <li>linuxPackages_hardkernel_latest.ixgbevf</li>
    <li>linuxPackages_hardkernel_latest.jool</li>
    <li>linuxPackages_hardkernel_latest.lttng-modules</li>
    <li>linuxPackages_hardkernel_latest.mba6x_bl</li>
    <li>linuxPackages_hardkernel_latest.mbp2018-bridge-drv</li>
    <li>linuxPackages_hardkernel_latest.mwprocapture</li>
    <li>linuxPackages_hardkernel_latest.mxu11x0</li>
    <li>linuxPackages_hardkernel_latest.ndiswrapper</li>
    <li>linuxPackages_hardkernel_latest.netatop</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_beta</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_legacy340</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_legacy390</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_vulkan_beta</li>
    <li>linuxPackages_hardkernel_latest.nvidiabl</li>
    <li>linuxPackages_hardkernel_latest.openafs</li>
    <li>linuxPackages_hardkernel_latest.openafs_1_8</li>
    <li>linuxPackages_hardkernel_latest.openafs_1_9</li>
    <li>linuxPackages_hardkernel_latest.openrazer</li>
    <li>linuxPackages_hardkernel_latest.phc-intel</li>
    <li>linuxPackages_hardkernel_latest.prl-tools</li>
    <li>linuxPackages_hardkernel_latest.r8125</li>
    <li>linuxPackages_hardkernel_latest.r8168</li>
    <li>linuxPackages_hardkernel_latest.rtl8192eu</li>
    <li>linuxPackages_hardkernel_latest.rtl8723bs</li>
    <li>linuxPackages_hardkernel_latest.rtl8812au</li>
    <li>linuxPackages_hardkernel_latest.rtl8814au</li>
    <li>linuxPackages_hardkernel_latest.rtl8821au</li>
    <li>linuxPackages_hardkernel_latest.rtl8821ce</li>
    <li>linuxPackages_hardkernel_latest.rtl8821cu</li>
    <li>linuxPackages_hardkernel_latest.rtl88x2bu</li>
    <li>linuxPackages_hardkernel_latest.rtl88xxau-aircrack</li>
    <li>linuxPackages_hardkernel_latest.rtlwifi_new</li>
    <li>linuxPackages_hardkernel_latest.rtw88</li>
    <li>linuxPackages_hardkernel_latest.sch_cake</li>
    <li>linuxPackages_hardkernel_latest.sysdig</li>
    <li>linuxPackages_hardkernel_latest.system76</li>
    <li>linuxPackages_hardkernel_latest.system76-acpi</li>
    <li>linuxPackages_hardkernel_latest.system76-io</li>
    <li>linuxPackages_hardkernel_latest.systemtap</li>
    <li>linuxPackages_hardkernel_latest.tbs</li>
    <li>linuxPackages_hardkernel_latest.tp_smapi</li>
    <li>linuxPackages_hardkernel_latest.tuxedo-keyboard</li>
    <li>linuxPackages_hardkernel_latest.v4l2loopback</li>
    <li>linuxPackages_hardkernel_latest.v86d</li>
    <li>linuxPackages_hardkernel_latest.vendor-reset</li>
    <li>linuxPackages_hardkernel_latest.vhba</li>
    <li>linuxPackages_hardkernel_latest.virtualbox</li>
    <li>linuxPackages_hardkernel_latest.virtualboxGuestAdditions</li>
    <li>linuxPackages_hardkernel_latest.wireguard</li>
    <li>linuxPackages_hardkernel_latest.xpadneo</li>
    <li>linuxPackages_hardkernel_latest.zenpower</li>
    <li>linuxPackages_hardkernel_latest.zfs</li>
    <li>linuxPackages_hardkernel_latest.zfsStable</li>
    <li>linuxPackages_hardkernel_latest.zfsUnstable</li>
    <li>loxodo</li>
    <li>metamorphose2</li>
    <li>mfcl8690cdwcupswrapper</li>
    <li>mrxvt</li>
    <li>mupdf_1_17</li>
    <li>natron</li>
    <li>nomad_0_12</li>
    <li>obinskit</li>
    <li>ocropus</li>
    <li>odpdown</li>
    <li>openrw</li>
    <li>openssh_gssapi</li>
    <li>openssh_hpn</li>
    <li>opentsdb</li>
    <li>oven-media-engine</li>
    <li>ovftool</li>
    <li>pbis-open</li>
    <li>pcsxr</li>
    <li>pdfdiff</li>
    <li>pdfread</li>
    <li>pgadmin</li>
    <li>pig</li>
    <li>plover.stable</li>
    <li>rainbowstream</li>
    <li>riak</li>
    <li>ring-daemon</li>
    <li>scallion</li>
    <li>scribus</li>
    <li>scyther</li>
    <li>shellinabox</li>
    <li>spark</li>
    <li>staruml</li>
    <li>stepmania</li>
    <li>swftools</li>
    <li>swift</li>
    <li>termplay</li>
    <li>torchat</li>
    <li>tvheadend</li>
    <li>twinkle</li>
    <li>unicap</li>
    <li>vdrPlugins.markad</li>
    <li>vdrPlugins.vaapidevice</li>
    <li>vdrPlugins.xineliboutput</li>
    <li>vp</li>
    <li>winpdb</li>
    <li>xpdf</li>
    <li>xsw</li>
    <li>yaxg</li>
    <li>zgv</li>
  </ul>
</details>
<details>
  <summary>23287 packages skipped due to time constraints:</summary>
  <ul>
    <li>AusweisApp2</li>
    <li>CHOWTapeModel</li>
    <li>DisnixWebService</li>
    <li>EBTKS</li>
    <li>EmptyEpsilon</li>
    <li>Fabric (python38Packages.Fabric)</li>
    <li>LAStools</li>
    <li>LASzip</li>
    <li>LASzip2</li>
    <li>Literate</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>26 packages built successfully:</summary>
  <ul>
    <li>brotli</li>
    <li>cmake</li>
    <li>curl</li>
    <li>eigen</li>
    <li>graphite2</li>
    <li>ilmbase</li>
    <li>json_c</li>
    <li>lcms2</li>
    <li>libarchive</li>
    <li>libcbor</li>
    <li>libdevil-nox</li>
    <li>libipt</li>
    <li>libjpeg (libjpeg_turbo)</li>
    <li>libmicrohttpd (libmicrohttpd_0_9_71)</li>
    <li>libmng</li>
    <li>libmysqlclient (libmysqlclient_3_1 ,mariadb-connector-c ,mariadb-connector-c_3_1)</li>
    <li>libstemmer</li>
    <li>libtiff</li>
    <li>libwebp</li>
    <li>openexr</li>
    <li>poppler_data</li>
    <li>soxr</li>
    <li>vulkan-headers</li>
    <li>woff2</li>
    <li>zeromq (zeromq4)</li>
    <li>zstd</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
@IvarWithoutBones if you do not allow maintainer pushes the rebase action does not work.

/rebase staging

**Comment by IvarWithoutBones** [comment]
Huh, that's odd. I'm pretty sure i do allow edits by maintainers, at least that's what the website says on the side of the PR. I've disabled and than reenabled it, hopefully it'll work now?

**Comment by lovesegfault** [comment]
@IvarWithoutBones please rebase manually. Alternatively, I'm happy to reopen this PR based on staging.

**Comment by IvarWithoutBones** [comment]
> @IvarWithoutBones please rebase manually. Alternatively, I'm happy to reopen this PR based on staging.

Done :+1: 

I wonder why the automatic rebase fails, I can't think of any reason why it would fail like it does.

**Review by jonringer — APPROVED** [review]
LGTM

```
https://github.com/NixOS/nixpkgs/pull/124870

2 packages built:
arrow-cpp zfsUnstable
```

**Comment by rb2k** [comment]
1.5.0 broke the compilation on darwin. Fix here: https://github.com/NixOS/nixpkgs/pull/131289

**Pull request merged**
