### PR TITLE
Update Qt Creator to version 4.6.2

### PR DESCRIPTION
**Pull request by tarigo**
In order to compile and and use it in NixOS 18.09.

###### Motivation for this change
Cannot compile outdated version 4.5.0 with default version of Qt on NixOS 18.09.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
Need to change the commit message to the format "qtcreator: 4.5.0 -> 4.6.2"

@GrahamcOfBorg build qtcreator

**Comment by tarigo** [comment]
Strange that build fails with timeout.

**Comment by Infinisil** [comment]
That's just @GrahamcOfBorg's timeout because it took too long to build. It works just fine when I build and run it locally. Only thing left to do is fix the commit message :)

I assume you tested the updated version a little better than me?

**Comment by tarigo** [comment]
Yes, I use it for my pet project development. :)
I screwed up my repo a bit changing commit message,  so I re-forked it again, new PR is #43655.
I'm closing this one.

**Pull request closed without merging**
