### PR TITLE
google-chrome: add -beta and -unstable variants

### PR DESCRIPTION
**Pull request by benley**
It is a little weird that chromium has chromium, chromiumBeta, chromiumDev but this one is google-chrome, google-chrome-beta, google-chrome-dev.  Not really sure what the best solution is, or perhaps leaving it alone is fine.

### CODE REVIEW

**Comment by globin** [comment]
I actually still don't get why we have google chrome as we have flags to enable things which normally are chrome specific for chromium e.g. widevine for netflix support?

**Comment by benley** [comment]
Historically there have been some features in chrome that aren't available
for chromium, but I don't know what the relevant differences are anymore.
I've been using chrome out of habit, but I figure it is nice to have both
available if it's reasonable to do it.

**Comment by globin** [comment]
Yes that still applies to other distros who don't give you the possibility to enable widevine in chromium, where you definitely need chrome for that use case. But essentially our chromium can be configured to work just like chrome so we are kind of packaging the same software twice. (We copy over binary extensions from chrome and patch chromium to enable them)

**Comment by benley** [comment]
okay ... I'm still just refining what's already present, not adding chrome anew.

**Comment by globin** [comment]
I am aware of that, but I don't see any reason to add more to that if nobody needs and uses it.

**Comment by benley** [comment]
I use it.  Do we have any actual metrics on how many users packages have?

**Comment by msteen** [comment]
If every [difference between Google Chrome and Chromium][0] that depends on the distro is made the same, then I too see no reason to keep Google Chrome. The only remaining differences will be the logo and some reporting. I do use both Google Chrome (Widevine, Flash) and Chromium at the moment, because I prefer to have flash disabled for most sites. If I want to keep this distinction, I could just create an additional Chromium package with those extensions enabled and setting --user-data-dir to something different.

[0]: https://chromium.googlesource.com/chromium/src/+/master/docs/chromium_browser_vs_google_chrome.md

**Comment by jgillich** [comment]
Widevine refers to the EME/HTML5 DRM stuff? I'm using Chrome because I didn't know I could get them for Chromium. One reason to still use Chrome is branding, but it could as well be Chromium with the branding parts swapped out (no idea how hard that would be).

**Comment by benley** [comment]
widevine works in chromium in nixpkgs now, yes.

It's obviously not my decision whether or not to keep chrome.  I'll leave it up to the people with commit access to either veto this PR or merge it.

**Comment by FRidh** [comment]
If there are users who would prefer to use the Chrome-branded version, then why not just keep it in if the maintenance burden is low. Chromium takes a lot of time to build, so in case of larger changes Chromium on NIx will likely lag in functionality on Chrome.

I at least would like to keep Chrome in, and also have access to the variants that are proposed in this PR.

**Pull request merged**
