### PR TITLE
station: fix missing icon

### PR DESCRIPTION
**Pull request by epiteff**
###### Motivation for this change
Fixes the icon not displaying.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by epiteff** [comment]
The maintainer @lattfein does not exist anymore. Could anyone review this PR?

**Comment by epiteff** [comment]
@jonringer Could you review this PR?

**Comment by jonringer** [comment]
I could, but I don't use a DE so I don't really see icons. @worldofpeace can you take a look? I know you like things looking polished.

**Review by worldofpeace — APPROVED** [review]
LGTM.

**Comment by worldofpeace** [comment]
@jonringer yes :smile: polish always.

**Pull request merged**
