### PR TITLE
roundcubePlugins.carddav: v3.0.3 -> v4.3.0

### LINKED ISSUE #145775: Roundcube fails to start with `carddav` plugin enabled due to PHP Fatal error
### Describe the bug
Roundcube with the `carddav` plugin enabled fails to start due to an error caused by [PHP deprecating the left-associative ternary operator](https://www.php.net/manual/en/migration74.deprecated.php). This seems to be caused by #142148.

```
Nov 13 06:12:48 server systemd[1]: Starting roundcube-setup.service...
Nov 13 06:12:48 server roundcube-setup-start[3861]:  2019092900
Nov 13 06:12:48 server roundcube[3862]: PHP Fatal error:  Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /nix/store/2aifms5v5gwv4i15girjs0zk9n8bx6y8-roundcube-plugin-carddav-3.0.3/plugins/carddav/carddav.php on line 352
Nov 13 06:12:48 server systemd[1]: roundcube-setup.service: Main process exited, code=exited, status=255/EXCEPTION
Nov 13 06:12:48 server systemd[1]: roundcube-setup.service: Failed with result 'exit-code'.
Nov 13 06:12:48 server systemd[1]: Failed to start roundcube-setup.service.
```

### Steps To Reproduce
Enable the `roundcube` module with `services.roundcube.package = pkgs.roundcube.withPlugins (plugins: [ plugins.carddav ]);` and `services.roundcube.plugins = [ "carddav" ];`.

### Expected behavior
Roundcube with the `carddav` plugin enabled should start.

### Additional context
#125778 and #125796 are somewhat related to this issue.

### Notify maintainers
@Ma27 @Vskilet 

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.78, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.11pre329879.c5ed8beb478"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- roundcube
```

### PR DESCRIPTION
**Pull request by rembo10**
###### Motivation for this change
Version bump for the roundcube carddav plugin. The new repo is the ["official" roundcube/carddav plugin repo](https://plugins.roundcube.net/#/packages/roundcube/carddav). Tested on nixos-21.11, closes #145775

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Lassulus** [comment]
Hmm, nix-review and ofborg don't see any chsnges, not sure why

**Comment by rembo10** [comment]
Maybe because it's like a subpackage or something? Is there something i need to do on my end?

**Comment by Lassulus** [comment]
probably nothing you can do. How do you use this package?

**Comment by rembo10** [comment]
```
services.roundcube = {
  package = pkgs.roundcube.withPlugins (plugins: [
    plugins.carddav
  ]);
 plugins = [
   "carddav"
 ];
};
```

**Comment by Lassulus** [comment]
hmm, I guess because its not in a globally defined package set, ofborg and nix-review skip the automatic build.

**Comment by rembo10** [comment]
@Lassulus thanks for merging

**Pull request merged**
