### PR TITLE
sudo and sssd: Enable sssd support in sudo and building of sudo library in sssd

### PR DESCRIPTION
**Pull request by lejonet**
###### Motivation for this change
Sudo has support to poll SSSD for its sudoers rules, but it has to be compiled into sudo and it requires a sudo plugin, libsss_sudo.so, from SSSD to function.

Added optional arguments to sudo and sssd to enable this functionality and have tested it, via packageOverrides, on a baremetal nixos machine. Both sssd and sudo was built with nix.useSandbox = true and I tried the functionality it brings and it works, I have sudoers rules in an openldap directory which I could apply after appending sudoers: files sss to nsswitch.conf.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lejonet** [comment]
Replaces #30025 as I had forgotten to make a feature branch for it, thus polluting the PR with other work.

**Comment by bjornfor** [comment]
Is that last commit a fixup of the first commit?

**Comment by lejonet** [comment]
Yes, it is

**Comment by bjornfor** [comment]
Then please squash them. (Easier to review etc.)

**Comment by lejonet** [comment]
Will do

**Comment by lejonet** [comment]
Now they are rebased, man my git "muscles" are out of shape :P

**Review by bjornfor — APPROVED** [review]

**Review by bjornfor — APPROVED** [review]

**Comment by bjornfor** [comment]
Applied to master (eafcfaf62c103604cf6bde9d38b54b9426d0244e and parent). Thanks!

**Pull request closed without merging**
