### PR TITLE
makeDesktopItem: add desktop file validation

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
This uses desktop-file-validate in desktop-file-utils.
It can be turned off if wanted.

Errant entries according to the specification will now fail the build, and enforce properly created desktop files.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by worldofpeace** [comment]
It's possible current expressions using `makeDesktopItem` will fail to build because of this change.

**Comment by teto** [comment]
I don't have a beefy enough machine but I don't think it would break too much stuff.

**Review by teto — APPROVED** [review]

**Comment by bignaux** [comment]
We could modify the makeDesktopItem() using desktop-file-edit , ie :
desktop-file-edit \
--set-key Exec --set-value $binary \
--set-key Comment --set-value "${meta.description}" \
--set-key Categories --set-value Network default.desktop 
that way, according to documentation, you won't need to rerun validation.
and a most-wanted , and desktop-file-validate doesn't provides that, is to check if Exec value is valid.
( as in #75819 or #45347).

 you can also enforce mode with --mode , avoid some desktop files like firefox ,0ad or xterm one to be executable ...

**Comment by worldofpeace** [comment]
@bignaux Sounds good, will try this.

**Comment by tilpner** [comment]
@bignaux I don't use .desktop files, so I'm unfamiliar with the ways used to generate them, but I'll try to review a PR to appimageTools if you send one. :)

**Comment by bignaux** [comment]
Using this issue as a TODO, i notice we need a unified method to make the icon directories, lot use 
such thing, an integrated helper would be welcome  :
https://github.com/NixOS/nixpkgs/blob/de0af4a171280f085c6181b7477cefb46cc1ae83/pkgs/applications/networking/p2p/soulseekqt/default.nix#L56-L59

**Comment by worldofpeace** [comment]
Merged because I don't think I'll have the time to improve this more.

**Comment by ajs124** [comment]
This also broke the build of `joplin-desktop`. I barely know anything about desktop files, so I'm unsure how to fix this.

**Comment by orivej** [comment]
Fixed in 7df81361.

**Comment by timokau** [comment]
This broke calibre: https://github.com/NixOS/nixpkgs/pull/84095

**Comment by piegamesde** [comment]
Was `nixpkgs-review` ever run on this PR?

**Pull request merged**
