### PR TITLE
heroic: 1.10.3 -> 2.0.2

### PR DESCRIPTION
**Pull request by siddhantk232**
###### Motivation for this change

The new version of heroic-games-launcher has some cool new features that I wanted to try and it worked just by bumping up the `version` of heroic/default.nix.

Please let me know of any further changes required to get this PR merged.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by WolfangAukang** [comment]
Thank you @siddhantk232! I see there is a hotfix (2.0.1). Can you adapt your PR to this new version? I have tested the code and everything is working fine.

**Comment by siddhantk232** [comment]
Thank you @WolfangAukang! I have updated this PR to use the 2.0.1 hotfix version. I have also added gtk3 as the FileChooserDialog wasn't working without it.

**Comment by WolfangAukang** [comment]
Thank you, just one thing: Can you group all of your changes into a single commit? With that we are good to go with the approval

**Comment by siddhantk232** [comment]
Thanks, @WolfangAukang! I have grouped changed into a single commit :smile:

**Comment by JohnAZoidberg** [comment]
> I have updated this PR to use the 2.0.1 hotfix version.

I updated the PR title for you

> I have also added gtk3 as the FileChooserDialog wasn't working without it.

Great, thanks!

**Comment by JohnAZoidberg** [comment]
> The new version of heroic-games-launcher has some cool new features that I wanted to try and it worked just by bumping up the version of heroic/default.nix.

Great! You tried to play some games and everything seems fine?

It's a major version updates from 1.x.y to 2.x.y so I wouldn't be surprised if something broke.

**Comment by SuperSamus** [comment]
[Heroic 2.0.2 is released.](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v2.0.2)
It fixed an accidental breakage from 2.0.1, so it'd be better to update straight to 2.0.2.

**Comment by siddhantk232** [comment]
> Great! You tried to play some games and everything seems fine?

I only played one game and it launched fine. I later added that game as a non-steam game in my Steam library to launch with steam play (proton), so I can't confirm if it has any gameplay issues.

**Comment by siddhantk232** [comment]
> [Heroic 2.0.2 is released.](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v2.0.2) It fixed an accidental breakage from 2.0.1, so it'd be better to update straight to 2.0.2.

Thanks for letting me know! I have updated this PR to use the 2.0.2 version

**Review by WolfangAukang — APPROVED** [review]
Tested it and works fine. Thank you!

**Review by bachp — APPROVED** [review]
No issues found while testing

**Pull request merged**
