### PR TITLE
services.nsd.zones.<name>.data: Do not interpret '$' sign.

### PR DESCRIPTION
**Pull request by nbp**
This patch make sure that dollar sign are not interpreted, and kept as-is, which is necessary if people are migrating their zone files from Ubuntu, and followed the following how to:

https://www.digitalocean.com/community/tutorials/how-to-use-nsd-an-authoritative-only-dns-server-on-ubuntu-14-04

No having this will change the file content by interpreting the `$ORIGIN` and `$TTL` shell variables which are empty when running the `zoneFiles` derivation.  This patch replaces this derivation by a copy of the `writeTextDir` of each zone.

cc @aszlig

### CODE REVIEW

**Comment by aszlig** [comment]
:+1: although I haven't tested it in production.
Cc: @hrdinka, who wrote initial version.

**Comment by hrdinka** [comment]
:+1: This really is how it should have been from the start on.

I have tested it and I am already using it in production without any flaws.
This patch however will break all `nsd` configurations out there—should we add some kind of notification/warning when building the new configuration?

**Comment by nbp** [comment]
> This patch however will break all nsd configurations out there—should we add some kind of notification/warning when building the new configuration?

I added some documentation for it.  Nix is not made to do some string processing, ideally we should request nsd to verify that the zone file is correct.  Would there be a way to do so?

**Comment by hrdinka** [comment]
@nbp I have included your patch in this pull request:
https://github.com/NixOS/nixpkgs/pull/10991

With this new patch NSD will check its config/zone files before starting. This pull request can be closed in favor of the new one.

**Comment by nbp** [comment]
[duplicate] These patches are now included in #10991.

**Pull request closed without merging**
