### PR TITLE
python311Packages.pybind11: 2.11.1 -> 2.12.0

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
Diff: https://github.com/pybind/pybind11/compare/v2.11.1...v2.12.0

Changelog: https://github.com/pybind/pybind11/blob/v2.12.0/docs/changelog.rst

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by dotlambda** [comment]
@ofborg eval

**Comment by doronbehar** [comment]
Hmm I see a failing test in scipy in CI:

```
=================================== FAILURES ===================================
___ test_milp_timeout_16545[options0-Time limit reached. (HiGHS Status 13:] ____
[gw34] linux -- Python 3.11.8 /nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/bin/python3.11
options = {'time_limit': 0.1}, msg = 'Time limit reached. (HiGHS Status 13:'
    @pytest.mark.skipif(np.intp(0).itemsize < 8,
                        reason="Unhandled 32-bit GCC FP bug")
    @pytest.mark.slow
    @pytest.mark.parametrize(["options", "msg"], [({"time_limit": 0.1}, _msg_time),
                                                  ({"node_limit": 1}, _msg_iter)])
    def test_milp_timeout_16545(options, msg):
        # Ensure solution is not thrown away if MILP solver times out
        # -- see gh-16545
        rng = np.random.default_rng(5123833489170494244)
        A = rng.integers(0, 5, size=(100, 100))
        b_lb = np.full(100, fill_value=-np.inf)
        b_ub = np.full(100, fill_value=25)
        constraints = LinearConstraint(A, b_lb, b_ub)
        variable_lb = np.zeros(100)
        variable_ub = np.ones(100)
        variable_bounds = Bounds(variable_lb, variable_ub)
        integrality = np.ones(100)
        c_vector = -np.ones(100)
        res = milp(
            c_vector,
            integrality=integrality,
            bounds=variable_bounds,
            constraints=constraints,
            options=options,
        )
    
        assert res.message.startswith(msg)
>       assert res["x"] is not None
E       assert None is not None
lib/python3.11/site-packages/scipy/optimize/tests/test_milp.py:323: AssertionError
=============================== warnings summary ===============================
lib/python3.11/site-packages/scipy/conftest.py:9: 64 warnings
  /nix/store/m067dwmf2yslbz013vhyfn1c8yj4z1gq-python3.11-scipy-1.12.0/lib/python3.11/site-packages/scipy/conftest.py:9: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
    import numpy.array_api
lib/python3.11/site-packages/scipy/stats/tests/test_qmc.py::TestUtils::test_geometric_discrepancy_mst_with_zero_distances
  /nix/store/m067dwmf2yslbz013vhyfn1c8yj4z1gq-python3.11-scipy-1.12.0/lib/python3.11/site-packages/scipy/stats/tests/test_qmc.py:232: UserWarning: Sample contains duplicate points.
    assert_allclose(qmc.geometric_discrepancy(sample, method='mst'), 0.5)
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED lib/python3.11/site-packages/scipy/optimize/tests/test_milp.py::test_milp_timeout_16545[options0-Time limit reached. (HiGHS Status 13:] - assert None is not None
= 1 failed, 58921 passed, 2699 skipped, 237 xfailed, 16 xpassed, 65 warnings in 541.07s (0:09:01) =
```

I wonder if that is related to the pybind update. Maybe this should be reported upstream? Or perhaps it is a sort of timeout failure that will not exist on Hydra?

**Comment by doronbehar** [comment]
@ofborg eval

**Comment by doronbehar** [comment]
Hmm I saw earlier deeper errors in ofborg from dependencies of pybind. I tested a better but similar version of this change upon the master branch, and it seems to be fine. 

I also don't understand the cython_3 error in ansible-pylibssh that ofborg reports upon.. I sort of fixed it but it won't pick up my change. I think this can be cooked in `staging`, the ofborg error is not fatal of course because it's not the `master` branch. cc @mweinelt .

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by mweinelt** [comment]
Eval fix in 243c22a6cedf1e26f73585c3e67bd22ff9ff901b

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by doronbehar** [comment]
OK thanks for the links - I think what caused the issue was that `staging` without this PR didn't eval so ofborg couldn't compute the different attributes. I rebased and removed my `ansible-pylibssh` commit, to clean the PR. Will merge after eval finishes, I don't expect it to build, as I said earlier.

**Comment by vcunat** [comment]
FYI the build of scipy now regressed on x86_64-darwin (but not the other three platforms):
   https://hydra.nixos.org/build/256212026#tabs-buildsteps
   https://hydra.nixos.org/build/256034246#tabs-buildsteps
   /cc the staging-next PR #303527

**Comment by doronbehar** [comment]
Thanks for the link! https://github.com/scipy/scipy/issues/20300 is the upstream issue. Here's a fix: https://github.com/NixOS/nixpkgs/pull/304226

**Comment by Tom-Hubrecht** [comment]
So, this upgrade broke sagemath tests, I opened #306300

**Pull request merged**
