### PR TITLE
electron_3: refactor

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

This PR refactors electron_3 - essentially it allows us to remove the need for the separate `electron/3.x.nix`.

After the https://github.com/NixOS/nixpkgs/pull/86228 is merged, there will be only one dependency of `electron_3` called `obinskit`, which is modified in this PR to match the new packaging from `electron/default.nix`.

IOW, the https://github.com/NixOS/nixpkgs/pull/86228 needs to be merged first.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
@GrahamcOfBorg build electron_3 obinskit

**Review by Shou — APPROVED** [review]
Tested that obinskit works on NixOS x86_64. LGTM.

**Comment by prusnak** [comment]
@GrahamcOfBorg build electron_3 obinskit

**Comment by mmahut** [comment]
@GrahamcOfBorg build electron_3 obinskit

**Comment by prusnak** [comment]
@GrahamcOfBorg build electron_3 obinskit

**Comment by mmahut** [comment]
@GrahamcOfBorg build electron_3

**Comment by mmahut** [comment]
@GrahamcOfBorg build electron_3

**Comment by mmahut** [comment]
@GrahamcOfBorg build electron_3

**Comment by prusnak** [comment]
The `aarch64` failure is present on master too: https://hydra.nixos.org/build/120910216 so it is not a regression.

**Pull request merged**
