### PR TITLE
ganttproject-bin: 2.8.10 -> 3.1.31

### PR DESCRIPTION
**Pull request by mrVanDalo**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mrVanDalo** [comment]
https://www.ganttproject.biz/download/gp30#zip : 
> GanttProject requires Java Runtime version 11+ with JavaFX modules.
I couldn't find a jre11 so I used openjdk11 as dependency.

**Comment by applePrincess** [comment]
It seems as if depending on `jre` is still fine since `jre` is pointing to openjdk17.

**Comment by mrVanDalo** [comment]
But it needs jre11 not jre17

**Comment by applePrincess** [comment]
Hmmm... I'm not sure now. I need to contact upstream what 'Java Runtime version 11+'  meant. 
I interpret it as JRE 11 or any major version later. so jre17 would be sufficient.

**Comment by applePrincess** [comment]
Okay,
Quote from [Release page on github](https://github.com/bardsoftware/ganttproject/releases/tag/ganttproject-3.2.3200)
>GanttProject requires Java Runtime version 11+ with JavaFX modules. It has been developed and tested with BellSoft Liberica Java 11 which is the recommended Java Runtime. However, it appears to run fine with Java 17 as well, and most likely will run with any other version of Java Runtime which is greater than 11 and includes JavaFX modules.

Which means it will probably work on jre17, however it could also mean that any other version than 11 is tested. So use jre11 is kind required otherwise it may introduce unstability.

**Comment by luzpaz** [comment]
v3.3.3300 has been released (https://github.com/bardsoftware/ganttproject/releases/tag/ganttproject-3.3.3300)

> Recommended Java Runtime

> GanttProject requires Java Runtime version 17+ with JavaFX modules. It has been developed and tested with BellSoft Liberica Java 17 which is the recommended Java Runtime.

> We recommend using [BellSoft Liberica Java Runtime](https://bell-sw.com/pages/downloads/#/java-17-lts). Choose Full JRE option for your platform on their download page.

> [Azul Zulu](https://www.azul.com/downloads/?version=java-17-lts&package=jre-fx#zulu) is another Java Runtime that includes JavaFX. There is also a very convenient tool called [SDKMAN!](https://sdkman.io/) for downloading and managing Java runtimes. It is Linux-native, but it also works fine on macOS and Windows with GitHub Shell.
Compatibility

> GanttProject 3.3 is compatible with the files produced by the previous versions of GanttProject 3+. Previous versions can read files produced by GanttProject 3.3, except that the calculated columns will be treated as regular ones.

**Comment by wegank** [comment]
Superseded by #282989.

**Pull request closed without merging**
