### PR TITLE
katex: init at 0.10.2

### PR DESCRIPTION
**Pull request by mt-caret**
###### Motivation for this change

Add katex, a program that accepts a subset of TeX math and converts it to HTML.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by alexarice** [comment]
nodePackages_10_x version works fine though there is no attribute for the nodePackages_8_x package (I'm assuming there should be one as a load of node v8 files have changed). I don't really know enough about js to review properly and I don't know how hard this would be to merge at this point

**Comment by veprbl** [comment]
@mt-caret Do you still need katex to be included in nixpkgs?

**Comment by prusnak** [comment]
Please rework your PR. It now has a merge conflict after PR https://github.com/NixOS/nixpkgs/pull/89184 has been merged

**Comment by mt-caret** [comment]
@veprbl @prusnak Apologies for the late response. I'm no longer super interested in including this in nixpkgs, so I'm closing this PR.

**Pull request closed without merging**
