### PR TITLE
[20.03] ansible: 2.9.11 -> 2.9.12; 2.8.13 -> 2.8.14

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

New upstream releases with security fixes.

Backports of #95193.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
generally, commits are done to master, then backported. So that the reference commit exists even when the repo gets mirrored https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#backporting-changes

**Comment by mweinelt** [comment]
Ah yeah, should've waited until they had hit master. I'll repick them if it becomes necessary.

**Comment by mweinelt** [comment]
Repicked.

**Comment by jonringer** [comment]
forgot to come back around to this, LGTM

**Pull request merged**
