### PR TITLE
python: Pygments: 2.5.2 -> 2.6.1

### PR DESCRIPTION
**Pull request by W95Psp**
###### Motivation for this change
Update to latest Pygments

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
not entirely sure this causes so many rebuilds, but since it's over 500, do you mind targeting the `staging` branch

```
git rebase --onto=staging HEAD~1
git push .. ... --force
```

then change the base branch in the github PR from `master` -> `staging`

**Comment by FRidh** [comment]
Its a dependency of sphinx which is a core package.

**Comment by jonringer** [comment]
that makes sense, thanks!

**Comment by W95Psp** [comment]
Well... So I've messed up quite much with my repo... I'll make an other pull-request, I'm closing this one

**Pull request closed without merging**
