### PR TITLE
python311Packages.pyqtgraph: don't propagate pyqt5

### PR DESCRIPTION
**Pull request by doronbehar**
## Description of changes

Numerous improvements to the pyqtgraph expression. The main commit (not propagating pyqt5), requires running a `nixpkgs-review` on this - which if successful will give us strong confidence that this PR doesn't break anything.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by bjornfor — APPROVED** [review]
LGTM.

Found a typo in a commit message: pythno312 -> python312

**Comment by doronbehar** [comment]
> LGTM.
> 
> Found a typo in a commit message: pythno312 -> python312

Thanks! Will merge when CI is green.

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 323171` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.stytra</li>
    <li>python311Packages.stytra.dist</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python312Packages.orange-widget-base</li>
    <li>python312Packages.orange-widget-base.dist</li>
  </ul>
</details>
<details>
  <summary>36 packages built:</summary>
  <ul>
    <li>gnss-sdr</li>
    <li>gnuradio</li>
    <li>gnuradio3_9</li>
    <li>gnuradioMinimal (gnuradio3_9Minimal)</li>
    <li>gnuradio3_9Packages.grnet</li>
    <li>gnuradio3_9Packages.osmosdr</li>
    <li>gnuradio3_9Packages.osmosdr.dev</li>
    <li>gnuradioPackages.osmosdr</li>
    <li>gnuradioPackages.osmosdr.dev</li>
    <li>gqrx</li>
    <li>gqrx-gr-audio</li>
    <li>gqrx-portaudio</li>
    <li>hifiscan</li>
    <li>hifiscan.dist</li>
    <li>inkcut</li>
    <li>inkcut.dist</li>
    <li>inkscape-extensions.inkcut</li>
    <li>linien-gui</li>
    <li>linien-gui.dist</li>
    <li>opcua-client-gui</li>
    <li>opcua-client-gui.dist</li>
    <li>python311Packages.binwalk-full</li>
    <li>python311Packages.binwalk-full.dist</li>
    <li>python311Packages.enamlx</li>
    <li>python311Packages.enamlx.dist</li>
    <li>python311Packages.orange-widget-base</li>
    <li>python311Packages.orange-widget-base.dist</li>
    <li>python311Packages.orange3</li>
    <li>python311Packages.orange3.dist</li>
    <li>python311Packages.pyqtgraph</li>
    <li>python311Packages.pyqtgraph.dist</li>
    <li>python312Packages.enamlx</li>
    <li>python312Packages.enamlx.dist</li>
    <li>python312Packages.pyqtgraph</li>
    <li>python312Packages.pyqtgraph.dist</li>
    <li>tribler</li>
  </ul>
</details>

**Comment by doronbehar** [comment]
> Result of `nixpkgs-review pr 323171` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 2 packages marked as broken and skipped:
> 2 packages failed to build:
> 36 packages built:

Thanks! Almost forgot.

**Review by fpletz — APPROVED** [review]

**Pull request merged**
