### PR TITLE
Fix GHC loadArchive clang++ error on macOS

### LINKED ISSUE #149937: GHC unusable on darwin when linking against `-libc++`
### Describe the bug
When a Haskell program that links against `-libc++` is compiled using LLVM & GHC from nixpkgs on macOS (darwin), compilation fails with the following error:

```
ghc: loadArchive: Neither an archive, nor a fat archive: `/nix/store/?-clang-wrapper-5.0.2/bin/clang++'

<no location info>: error:
    loadArchive "/nix/store/?-clang-wrapper-5.0.2/bin/clang++": failed
```

This occurs on `x86_64-darwin` as well as `aarch64-darwin`.

I have verified that it can be alleviated by applying [this patch](https://github.com/input-output-hk/haskell.nix/pull/262/commits/802829772e5edeaf6f43a09fb307f85b4ea4c67d), recompiling GHC, and attempting to rebuild a project that failed previously.

### Steps To Reproduce
Steps to reproduce the behavior **on a macOS system**:
1. Clone [`graphql-engine`](https://github.com/hasura/graphql-engine)
2. Insert the `shell.nix` included below into the repository root directory
3. Enter the `nix-shell`
4. Run `cp cabal.project.dev-sh.local cabal.project.local`
4. **If you are using an `aarch64-darwin` system**
  a. Update the `cabal.project.freeze` `index-state` to `hackage.haskell.org 2021-12-09T17:38:20Z`
5. Run `cabal update && cabal build graphql-engine`

<details>

<summary> shell.nix </summary>

```
{ pkgs ? import <nixpkgs> { }
, unstable ? import <unstable> { }
}:

let
  inherit (pkgs.lib.strings) makeLibraryPath;

  haskellDeps = (with pkgs; [
    haskell.compiler.ghc8107
    cabal-install
  ]);

  # `freetds` needs to be given a `unixODBC` package explicitly when
  # `odbcSupport` is enabled.
  freetdsWithODBC = pkgs.freetds.override {
    odbcSupport = true;
    inherit (pkgs) unixODBC;
  };

  dynamicLibraries = with pkgs; [
    libkrb5
    ncurses
    openssl
    pcre
    zlib

    # Postgres, ODBC, MSSQL, & MySQL deps.
    freetdsWithODBC
    libmysqlclient
    postgresql
    unixODBC
  ];

in
pkgs.mkShell {
  buildInputs =
    haskellDeps
    ++ dynamicLibraries;

  DYLD_FALLBACK_LIBRARY_PATH = makeLibraryPath dynamicLibraries;
}
```

</details>

### Expected behavior
The project should compile successfully, as it does when the patch linked above is applied.

To verify: replace `haskell.compiler.ghc8107` with the following snippet in the `shell.nix` file provided above and rebuild the `nix-shell` environment.

```
    (haskell.compiler.ghc8107.overrideAttrs (oldAttrs: {
      patches = (oldAttrs.patches or [ ]) ++ [
        (pkgs.fetchpatch {
          url = "https://raw.githubusercontent.com/input-output-hk/haskell.nix/613ec38dbd62ab7929178c9c7ffff71df9bb86be/overlays/patches/ghc/ghc-macOS-loadArchive-fix.patch";
          name = "ghc-macos-loadArchive-fix.patch";
          sha256 = "0IUpuzjZb1G+gP3q6RnwQbW4mFzc/OZ/7QqZy+57kx0=";
        })
      ];
    }))
```

**NOTE** Doing this will rebuild GHC from source, which is a very time consuming operation!

### Notify maintainers

@cdepillabout @expipiplus1 @maralorn @sternenseemann 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[jkachmar@manhattan-transfer:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.1.0, macOS 12.0.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4`
 - channels(jkachmar): `"nixpkgs-21.11pre334206.ff17a0fffea"`
 - channels(root): `"nixpkgs-21.11pre334206.ff17a0fffea"`
 - nixpkgs: `/nix/store/i00nm8lvxx4kybwym08ydkxpqf3irgwl-source`
 ```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by jkachmar**
Closes #149937.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jkachmar** [comment]
Note that I haven't tested this patch on GHC 8.8.4, 9.0.1, or 9.2.1. I've only applied it to those expressions following IOHK's guidance (as they apply this patch in their repository to all versions of GHC following 8.6.4).

**Comment by jkachmar** [comment]
@bgamari made the following observation when we discussed this in another channel:

> Oof, that `c++` issue is rather frustrating since it's arguably a workaround for a linker bug which may break currently-working programs
>
> If I understand correctly this patch will break users who specify, e.g.,` extra-libraries: z` in their cabal file
>
> I think a more correct way to work around this bug would be to incorporate a check to ensure that we aren't trying to link against an executable

**Comment by cdepillabout** [comment]
> If I understand correctly this patch will break users who specify, e.g., `extra-libraries: z` in their cabal file

@jkachmar Were you able to figure out if this is the case?

If so, it sounds pretty bad?  My guess is that there are quite a few packages using `extra-libraries` (although I'm not actually that sure).

Also, most of the Haskell maintainers (other than sternenseemann) don't use darwin as far as I know, so we might have to ping @ NixOS/darwin-maintainers in order to get this reviewed.

**Comment by jkachmar** [comment]
I looked into this a bit more again tonight and I still don't really know what the best path forwards is here.

Some related issues:
- https://github.com/tweag/rules_haskell/issues/1601#issuecomment-938450658
- https://github.com/NixOS/nixpkgs/issues/42059
- https://gitlab.haskell.org/ghc/ghc/-/issues/16590

---

@jwiegley I saw that you opened the GHC issue linked above; did you ever find a satisfactory workaround to the issue (or was it resolved for you in an updated GHC release)?

**Comment by mariatsji** [comment]
Thanks, this patch solved the problem I was having with `cabal build` in a nix-shell using GHC 8.10.7 on darwin:

```
ghc: loadArchive: Neither an archive, nor a fat archive: `/nix/store/cvz17hkb0wpbsyx58l4zcaamqs2bhlmz-clang-wrapper-11.1.0/bin/clang++'
ghc: panic! (the 'impossible' happened)
  (GHC version 8.10.7:
        loadArchive "/nix/store/cvz17hkb0wpbsyx58l4zcaamqs2bhlmz-clang-wrapper-11.1.0/bin/clang++": failed
```

**Comment by sternenseemann** [comment]
As stated above, the workaround is not satisfactory, as it may break legitimate use cases that are already working today.

Building cabal-install on darwin is unaffected by this issue:

* https://hydra.nixos.org/job/nixpkgs/nixpkgs-unstable-aarch64-darwin/cabal-install.aarch64-darwin
* https://hydra.nixos.org/job/nixpkgs/trunk/cabal-install.x86_64-darwin

**Comment by jkachmar** [comment]
i agree that this solution is unsatisfactory, however as far as i can tell "something" does need to be done to address this. i'm fine with closing this PR, but i hesitated to do so because it has more activity (and more context) than the discussion at #149937.

if anyone has any ideas for how we should fix this, i'd be more than willing to dedicate some time to exploring them and patching things properly.

**Comment by maksar** [comment]
iohk repo doesn't have a patch for ghc944. Structure of the files has changed in GHC. I used this patch and can confirm issue disappeared:
```
--- a/compiler/GHC/Linker/Loader.hs
+++ b/compiler/GHC/Linker/Loader.hs
@@ -1616,8 +1616,6 @@
        | verbatim = [lib]
        | otherwise = [ "lib" ++ lib ++ lib_tag <.> "a"
                      , lib <.> "a" -- native code has no lib_tag
-                     , "lib" ++ lib
-                     , lib
                      ]
      lib_tag = if is_hs && loading_profiled_hs_libs then "_p" else ""
```

**Comment by sternenseemann** [comment]
@maksar This is equivalent to the patch proposed in this PR and as mentioned above, GHC upstream thinks that the patch breaks legitimate use cases.

**Comment by harryaskham** [comment]
Experiencing the same issue with GHC 9.8.1 on nix-darwin, tried with gcc/clang from each of OSX and nixpkgs in the path. I'll see if patching still works following e.g. https://github.com/NixOS/nixpkgs/pull/149942/commits/e9d090fcd60d3005d2c33db8ac03d8e40ec392b3

**Pull request closed without merging**
