### PR TITLE
pythonPackages.django-raster: Improve django version support

### PR DESCRIPTION
**Pull request by lsix**
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build django-raster

**Comment by xeji** [comment]
oops :smile: 
@GrahamcOfBorg build python36Packages.django-raster

**Review by xeji — COMMENTED** [review]
This assertion fails by default because default django is 1.11.  
I suggest you override `django = django_2_1` in `python-packages.nix`.

**Comment by lsix** [comment]
Sorry for the delay…

I do not think this is a good idea to have that in `python-packages.nix`. If any-one tries to use django-raster with any other django app, then with this kind of approach it will end up with 2 different versions of django in its dependencies, and things will probably go wrong.

The preferred approach, I think, would be to override `pythonPackages` to make use `django_2_1` as `django:

```nix
let python3 = pkgs.python3.override {
      packageOverrides = sef: super: {
        django = super.django_2_1;
      };
    };
in python3.pkgs.buildPythonPackage {
  …
}
```

With such approach, only one version of django it used, but yes, the price is that `django-raster` cannot build without an altered `python` packages set.

**Comment by xeji** [comment]
I understand. The assertion failing with default  settings may confuse people - it confused me for sure. 
Maybe you can add a comment explaining how this is supposed to be used?

**Comment by lsix** [comment]
I’ll add a comment shortly.

My other option was to throw an exception with a message somewhere

```nix
if stdenv.lib.versionOlder django.version "2.0"
then throw "django-raster only supports Django >= 2.0. Consider overriding the pythonPackage set to use django_2_1"
else
buildPythonPackage {
  …
}
```

**Comment by xeji** [comment]
That sounds good as well.

**Comment by lsix** [comment]
@xeji I have updated to throw an exception with a proper error message if django is too old.

**Review by xeji — APPROVED** [review]

**Pull request merged**
