### PR TITLE
git-nomad: migrate to new apple-sdk structure, move to by-name

### PR DESCRIPTION
**Pull request by sarahec**
1. Migrated from old darwin.apple_sdk to the new one. (Explicit references to Apple frameworks aren't needed as build inputs anymore, they're all automatically available during a Darwin build. Magic!)
2.  Moved to pkgs/by-name (and removed from all-packages as no longer needed)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by rraval — APPROVED** [review]

**Comment by sarahec** [comment]
Turns out I need to make another edit or two

**Comment by sarahec** [comment]
So, turns out you don't need to explicitly supply Apple frameworks in BuildInputs anymore as long as you're good with the default SDK. This makes Darwin support so much easier.

**Review by rraval — APPROVED** [review]
Neat. I don't know much about nix on darwin and the existing build was contributed by another user.

The vibes appear right though ¯\\\_(ツ)\_/¯

Thanks for putting this together.

**Review by rraval — APPROVED** [review]

**Review by khaneliman — APPROVED** [review]
LGTM, thanks sarah!

**Comment by sarahec** [comment]
> Would probably be best to separate the commits for the moving and refactor stuff, though.

I'll keep this in mind for future migrations.

**Pull request merged**
