### PR TITLE
libfive-unstable: 2020-02-15 -> 2022-05-19

### PR DESCRIPTION
**Pull request by KoviRobi**
###### Description of changes

Unbreak and update libfive thanks to @lboklin #195327. I've tested it on my older models, a function got renamed `extrude -> extrude-z` but that's a language change in libfive, once I made that things worked nicely.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
@ofborg build libfive-unstable

Fails for me on macos 10.15:

```
FAILED: libfive/src/CMakeFiles/libfive.dir/eval/eval_jacobian.cpp.o 
/nix/store/w20by2g6j2zkckixf1mmj60n3dqm7hc3-clang-wrapper-11.1.0/bin/clang++ -Dlibfive_EXPORTS -I/tmp/nix-build-libfive-unstable-2022-05-19.drv-0/source/libfive/src/../include -isystem /nix/store/2c70basc65vx9c29j1fk49bzgg11frin-eigen-3.4.0/include/eigen3 -Wall -Wextra -g -fPIC -pedantic -Werror=switch -march=native -O3 -DNDEBUG 
In file included from /tmp/nix-build-libfive-unstable-2022-05-19.drv-0/source/libfive/src/eval/eval_jacobian.cpp:10:
In file included from /tmp/nix-build-libfive-unstable-2022-05-19.drv-0/source/libfive/src/../include/libfive/eval/eval_jacobian.hpp:13:
In file included from /tmp/nix-build-libfive-unstable-2022-05-19.drv-0/source/libfive/src/../include/libfive/eval/eval_feature.hpp:13:
In file included from /tmp/nix-build-libfive-unstable-2022-05-19.drv-0/source/libfive/src/../include/libfive/eval/eval_deriv_array.hpp:13:
/tmp/nix-build-libfive-unstable-2022-05-19.drv-0/source/libfive/src/../include/libfive/eval/eval_array.hpp:127:5: error: use of undeclared identifier 'aligned_alloc'
    ALIGNED_OPERATOR_NEW_AND_DELETE(ArrayEvaluator)
    ^
/tmp/nix-build-libfive-unstable-2022-05-19.drv-0/source/libfive/src/../include/libfive/render/brep/default_new_delete.hpp:61:16: note: expanded from macro 'ALIGNED_OPERATOR_NEW_AND_DELETE'
        return aligned_alloc(std::alignment_of_v<T>, size);
```

**Comment by KoviRobi** [comment]
Thanks @risicle, I don't have a Mac so I cannot test it. Looking at the libfive sources it seems like https://github.com/libfive/libfive/issues/470 was meant to fix it, but alas it doesn't seem to work for you sadly. There is also https://github.com/libfive/libfive/issues/462 complaining about similar things that I have to be honest I haven't fully comprehended but seems like 10.15 should work? Maybe Apple is playing games and removing `aligned_alloc` once a release gets old so that people upgrade? I can only remove `darwin` from the list of supported platforms, I cannot think of anything else

**Comment by risicle** [comment]
No I don't think darwin is broken. It probably works on darwin-aarch64 because we use a newer macos sdk on that architecture, and we shouldn't take this package away from darwin-aarch64 users it works for.

There is a mechanism that can be used to force the new sdk on both architectures, but applying it involves using a special `callPackage` in the same way libfive already uses `libsForQt5.callPackage` so I'm not sure they can be used together. Might get some time to look at this tomorrow, but otherwise it's better to have this broken on one darwin platform than not available on either.

**Review by risicle — APPROVED** [review]
Well, this was broken on all platforms before and now it WFM on nixos x86_64.

A darwin x86_64 user who cares enough can come along and fix it if they like or sooner or later we'll switch everything to sdk 11 at which point it will hopefully magically fix itself.

**Pull request merged**
