### PR TITLE
lf: 21 -> 22 and remove myself as maintainer

### PR DESCRIPTION
**Pull request by primeos**
###### Motivation for this change

cc @yoctocell - Maybe you'd be interested to maintain it (ec160da46fce51174b5dc412cbbeaad3f992224e)?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by yoctocell** [comment]
On Wed, Apr 14 2021, Michael Weiss wrote:

> cc @yoctocell - Maybe you’d be interested to maintain it
> (ec160da46fce51174b5dc412cbbeaad3f992224e)?

Thanks for the ping.  I am no longer using lf, so I will leave this to
someone else.  Sorry.

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 119435` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>lf</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
May I ask what you use instead?

**Comment by primeos** [comment]
Nothing, just normal shell commands (plus a few aliases and some specific tools), I never really needed it in the first place tbh.

**Pull request merged**
