### PR TITLE
qt55.qtbase: use more system libraries

### PR DESCRIPTION
**Pull request by abbradar**
###### Things done:
- [x] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
###### More

cc @qknight @ttuegel

### CODE REVIEW

**Comment by abbradar** [comment]
Hm, I'm unsure that this is a "mass" enough rebuild, but this would take whole KDE at least.

**Comment by ttuegel** [comment]
I think this is big enough to deserve the mass-rebuild tag. I have another Qt patch that I was sitting on, so I'll merge them together.

**Comment by edolstra** [comment]
What's the effect on the Qt closure size?

**Comment by abbradar** [comment]
Hm, good question, I haven't evaluated this. How can I (i.e., what's the command for measuring total closure size of an output)?

**Comment by edolstra** [comment]
`du -schl $(nix-store -qR $(nix-build -A pkg))`

**Comment by abbradar** [comment]
Without the patch: 654M
With: 659M

Most size is from `harfbuzz` (`pcre16` is only 500K), but `harfbuzz` is also used in `pango` which is almost ubiquitous.

**Comment by ttuegel** [comment]
I don't understand why the closure size goes up. Without `-system-harfbuzz`, Qt includes its own copy of harfbuzz, which should surely increase the closure size, right?

**Comment by abbradar** [comment]
It links it statically, dropping everything that it doesn't need -- I think this is the reason.

**Comment by abbradar** [comment]
Well, FWIW I think that in practice `harfbuzz` is popular enough and this  to justify less static libraries (i.e. one place where bugs gather) -- and if `harfbuzz` is not in store already, increase is ~0.8%.

**Comment by vcunat** [comment]
The odds may well change after #7701. Until then, when you link dynamically, you also add headers, docs, etc.

**Pull request merged**
