### PR TITLE
tbb: Split into tbb_2020_3 and tbb_2021_8

### PR DESCRIPTION
**Pull request by hesiod**
###### Description of changes
This is based on PR #214762 by @mweinelt.

For the new release 2021.8, see
https://www.intel.com/content/www/us/en/developer/articles/release-notes/intel-oneapi-threading-building-blocks-release-notes.html
https://github.com/oneapi-src/oneTBB/releases/tag/v2021.5.0
https://github.com/oneapi-src/oneTBB/releases/tag/v2021.6.0
https://github.com/oneapi-src/oneTBB/releases/tag/v2021.7.0

Due to the significant breakage due to the update to TBB 2021.8, instead split the tbb package into tbb_2020_3 and tbb_2021_8, with the default tbb aliased to tbb_2020_3 in order to minimize breakage.

The reason I went for this change is that I'd like to package [CCTag](https://github.com/alicevision/CCTag) which depends on TBB 2021. To me this solution seems like a good way to bridge the time until the packages incompatible with TBB 2021.8, but I'm not sure if there are any guidelines regarding splitting packages like this. So please comment if this discouraged for some reason.

I hope I got the split right. In particular, I'm wondering if there's a better solution for sharing `meta`. Also, I'm open to suggestions regarding the versioned package naming scheme.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by davidak** [comment]
For some reason the build fails: https://github.com/NixOS/nixpkgs/pull/216403#issuecomment-1431974295

Also, merge conflict.

**Comment by hesiod** [comment]
I fixed the merge conflict while rebasing, not sure why Github says there's still a conflict...

**Review by chuangzhu — COMMENTED** [review]
GCC 12 isn't supported in v2021.8.0 according to oneapi-src/oneTBB#823, and patches from oneapi-src/oneTBB#866 doesn't seem to be applicable :(

**Comment by davidak** [comment]
@chuangzhu i see. v2021.8.0 supports gcc11

>GNU Compilers (gcc) 4.8.5 - 11.1.1

Source: https://github.com/oneapi-src/oneTBB/blob/v2021.8.0/SYSTEM_REQUIREMENTS.md#supported-compilers

while v2020.3 supports

>GNU Compilers (gcc) 4.8 - 9.1

Source: https://github.com/oneapi-src/oneTBB/blob/v2020.3/doc/Release_Notes.txt#L93

So i think we should use the supported versions.

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 215689` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by davidak** [comment]
This leads to rebuild of about 800 packages including multiple linux kernels, so i think it should go through staging.

**Comment by mweinelt** [comment]
Can you not mention my account name in the commit message? It causes lots of sticky notifications, that I have to manually mark as read on every commit/branch/fork.

Instead, please add me as co-author at the end of the commit message.

```
Co-Authored-By: Martin Weinelt <hexa@darmstadt.ccc.de
```

**Comment by davidak** [comment]
I followed the rebase instructions, but somehow everything is messed up. That is not intentional!

https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging

**Comment by mweinelt** [comment]
I'm locking and closing this pull request, because through the rebase you inadvertently requested many maintainers for review, which subscribed them to update notifications, resulting in unnecessary spam inside everyone's inbox. While we can remove their review requests, we sadly cannot unsubscribe anyone.

Please create a new pull request and for the next time remember to set your PR to draft status before rebasing. In draft status, you can preview the list of maintainers that are about to be requested for review, which allows you to sidestep this issue.

**Pull request closed without merging**
