### PR TITLE
tmux: 3.4 -> 3.5

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Patches were removed, as they seem to be applied:

* https://github.com/tmux/tmux/pull/3840
* https://github.com/tmux/tmux/pull/3933
* https://github.com/tmux/tmux/commit/aa17f0e0c1c8b3f1d6fc8617613c74f07de66fae
* https://github.com/tmux/tmux/commit/3823fa2c577d440649a84af660e4d3b0c095d248

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Result of `nixpkgs-review pr 344844` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>23 packages built:</summary>
  <ul>
    <li>airgeddon</li>
    <li>arsenal</li>
    <li>arsenal.dist</li>
    <li>byobu</li>
    <li>clerk</li>
    <li>fzf-git-sh</li>
    <li>germinal</li>
    <li>hollywood</li>
    <li>hostmux</li>
    <li>overmind</li>
    <li>python311Packages.libtmux</li>
    <li>python311Packages.libtmux.dist</li>
    <li>python312Packages.libtmux</li>
    <li>python312Packages.libtmux.dist</li>
    <li>tmpi</li>
    <li>tmux</li>
    <li>tmux-cssh</li>
    <li>tmux.man</li>
    <li>tmuxPlugins.pass</li>
    <li>tmuxp</li>
    <li>tmuxp.dist</li>
    <li>vimPlugins.cmp-tmux</li>
    <li>wemux</li>
  </ul>
</details>

**Comment by afh** [comment]
Result of `nixpkgs-review pr 344844` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>19 packages built:</summary>
  <ul>
    <li>arsenal</li>
    <li>arsenal.dist</li>
    <li>byobu</li>
    <li>fzf-git-sh</li>
    <li>germinal</li>
    <li>hostmux</li>
    <li>overmind</li>
    <li>python311Packages.libtmux</li>
    <li>python311Packages.libtmux.dist</li>
    <li>python312Packages.libtmux</li>
    <li>python312Packages.libtmux.dist</li>
    <li>tmux</li>
    <li>tmux-cssh</li>
    <li>tmux.man</li>
    <li>tmuxPlugins.pass</li>
    <li>tmuxp</li>
    <li>tmuxp.dist</li>
    <li>vimPlugins.cmp-tmux</li>
    <li>wemux</li>
  </ul>
</details>

**Review by afh — APPROVED** [review]
Thanks for this, @matthiasbeyer, very much looking forward to tmux 3.5 in nixpkgs 🥳

**Comment by WilliamHsieh** [comment]
i saw this in the changelog
> Add --enable-jemalloc to build with jemalloc memory allocator (since glibc
  malloc is so poor).

Would it make sense to add this option in the current PR, or would it be better to create a separate PR for it?

**Comment by matthiasbeyer** [comment]
> Thanks for this, @matthiasbeyer, very much looking forward to tmux 3.5 in nixpkgs 🥳

I just saw the notification for the 3.5 release and checked whether there was a PR, and there wasn't... so I figured I can earn some karma points here :laughing: 

> Would it make sense to add this option in the current PR, or would it be better to create a separate PR for it?

Honestly I would keep this PR as simple as possible and only include the update in it. You're welcome to CC me on a PR for adding options to the package - although I do not use tmux, I am still interested in having nice packages in nixpkgs :laughing:

**Review by alois31 — APPROVED** [review]
Changes look good (in particular, the patches are in fact applied), and tmux still seems to work.

**Comment by Yarny0** [comment]
#### Review per https://github.com/NixOS/nixpkgs/tree/14d4ef8a2e575a25d0a2bfa9ed790a21c6ddc41c/pkgs#package-updates

##### Reviewed points

- [x] package name fits guidelines
- [x] package version fits guidelines
- [x] package builds on x86-64
- [x] executables tested on x86-64
- [ ] all depending packages build

Not applicable:

- [ ] ~~patches have a comment describing either the upstream URL or a reason why the patch wasn't upstreamed~~
- [ ] ~~patches that are remotely available are fetched rather than vendored~~

Works nice on my machine, some things tested:

- [x] changed key bindings
- [x] split windows
- [x] individual status line with variable expansion and colors

##### Comments

Looks really good, I recommend merging.

**Comment by leona-ya** [comment]
@ofborg eval

**Review by leona-ya — APPROVED** [review]

**Comment by afh** [comment]
Thanks for merging, @leona-ya, much appreciated 🎉

**Pull request merged**
