### PR TITLE
nixos.timezone: set TZ to :/etc/localtime

### LINKED ISSUE #23053: Set TZ environment variable?
## Issue description

The TZ environment variable was disabled in #1463, but apparently this has performance implications: 

https://blog.packagecloud.io/eng/2017/02/21/set-environment-variable-save-thousands-of-system-calls/

https://news.ycombinator.com/item?id=13697555

### Steps to reproduce

See the first link above.

## Technical details

* System: 16.09.git.bf4312a (Flounder)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: 16.09.git.bf4312a

### PR DESCRIPTION
**Pull request by wizeman**
###### Motivation for this change

This prevents glibc from calling stat() every time localtime() is called.
This could be a significant performance problem if `/etc` is on an NFS filesystem.

For systemd services, we point TZ to the actual time zone file instead of the /etc/localtime symlink so that systemd services are restarted if the time zone is changed.

Fixes #23053

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by wizeman** [comment]
Please wait just a few minutes as I'm about to push a better version of this PR.

**Comment by wizeman** [comment]
Ok, with this updated version, systemd services are now restarted if the time zone changes.

I don't know if it still makes sense to keep the `TZDIR` variable now that `TZ` is defined. I was hoping that someone who better understands the implications of removing `TZDIR` would comment.

**Comment by wizeman** [comment]
Ah, I believe `TZDIR` still needs to be set, because someone (either in their user environment or in a systemd service) may override `TZ` to be something like `Europe/London`, and in that case glibc must able to locate the time zone data correctly in NixOS, rather than assume the time zone data is in `/usr/share` (the default).

**Review by kevincox — APPROVED** [review]

**Comment by samueldr** [comment]
Anything blocking this from either an in-extremis merge for 18.09 or an early merge for 19.03?

I'm don't have the required knowledge about glibc to confirm the speed assertions, neither the setup to test, but [reading the appropriate manual section](http://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html) confirms this approach seems implemented right

> The third format looks like this:
>
>  * `:characters`
>
> Each operating system interprets this format differently; in the GNU C Library, characters is the name of a file which describes the time zone.
>
>If the `TZ` environment variable does not have a value, the operation chooses a time zone by default. In the GNU C Library, the default time zone is like the specification ‘`TZ=:/etc/localtime`’ (or ‘`TZ=:/usr/local/etc/localtime`’, depending on how the GNU C Library was configured; see Installation). Other C libraries use their own rule for choosing the default time zone, so there is little we can say about them.

**Comment by samueldr** [comment]
[Rebased locally to test](https://github.com/NixOS/nixpkgs/compare/master...samueldr:u/fix-tz-stat).

It breaks the `timezone-imperative` test, which works on the previous commit (current nixpkgs-unstable).

```
error: cannot coerce null to a string, at /.../nixpkgs-PR23078/nixos/modules/config/timezone.nix:12:15
(use '--show-trace' to show detailed location information)
```

This comes from the previous change where timeZone now default to `null` instead of `"UTC"`.

* * *

I have added a WIP commit I'd like reviewed; the tests pass, and it seems semantically correct, but I'm not entirely confident (but pretty sure) it implements the change while not breaking the current assumptions.

cc @wizeman @vcunat @edolstra

**Comment by wizeman** [comment]
@samueldr: Looks good to me!

**Comment by samueldr** [comment]
Pushed on @wizeman's repo after the approval; fixing the merge conflict, now ready to merge.

**Comment by rasendubi** [comment]
(triage) @wizeman @samueldr anyone willing to fix the merge conflict?

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by wizeman** [comment]
I think I must have force-pushed my git branch by mistake and undid @samueldr's merge conflict fixes...

Note that while I was using these changes, I was running into a bug where Go programs couldn't parse the `TZ=:/etc/localtime` environment variable correctly and defaulted to the UTC timezone.

Perhaps golang/go#27570 would fix that (but I'm not sure).

**Comment by flokli** [comment]
I'm don't think we can do this, at least until this isn't supported in major language runtimes (like Go).

**Comment by omasanori** [comment]
The commit https://github.com/golang/go/commit/58fe2cd4022c77946ce4b598cf3e30ccc8367143 was landed, so Go 1.16+ will be ready for this change.

**Comment by flokli** [comment]
Cool! Did someone check if python supports this, too?

**Comment by omasanori** [comment]
@flokli It appearently works with Python 3.7 on NixOS 20.03:

```python
[nix-shell:~]$ ls -l /etc/localtime
lrwxrwxrwx 1 root root 24 Oct 12 06:33 /etc/localtime -> /etc/zoneinfo/Asia/Tokyo

[nix-shell:~]$ TZ=UTC python
Python 3.7.6 (default, Dec 18 2019, 19:23:55)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import time
>>> os.environ['TZ']
'UTC'
>>> time.tzset()
>>> time.tzname
('UTC', 'UTC')
>>> time.strftime('%X %x %Z')
'12:08:22 10/12/20 UTC'
>>> os.environ['TZ'] = ':/etc/localtime'
>>> time.tzset()
>>> time.tzname
('JST', 'JST')
>>> time.strftime('%X %x %Z')
'21:08:45 10/12/20 JST'
>>>
```
(JST: Japan Standard Time; same as Asia/Tokyo and its offset from UTC is +09:00)

**Comment by SuperSandro2000** [comment]
@wizeman Can you rebase this?

**Comment by Ekleog** [comment]
@wizeman Are you still interested in pushing this through the last mile? :)

**Comment by omasanori** [comment]
Here is a good news: [Go 1.16 is released](https://blog.golang.org/go1.16) 🎉
I can take over if @wizeman @samueldr won't have enough time to work on this PR in near future.

**Comment by wizeman** [comment]
@Ekleog I'm interested but I don't have enough time at the moment.

@omasanori Please, feel free to take over. Thanks!

**Comment by omasanori** [comment]
@wizeman I see, Thank you for prompt response!

**Comment by Mic92** [comment]
newer version in https://github.com/NixOS/nixpkgs/pull/113555

**Pull request closed without merging**
