### PR TITLE
platformio: 3.5.3 -> 3.6.1

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

I'll only get the chance to try this out properly on the weekend so not tested yet. It builds and runs but nothing more than ```pio --version``` and ```pio update``` has been attempted.

Cc: @makefu @mogorman 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
The aarch64 error looks weird, and is a regression.

**Comment by makefu** [comment]
for better tracking we could also start the test environment as described in https://github.com/platformio/platformio-core/blob/develop/tox.ini#L62-L64 , or we explicitly disable the tests.

**Comment by peterhoeg** [comment]
@xeji, are you sure this ever worked on aarch64?

**Comment by peterhoeg** [comment]
> for better tracking we could also start the test environment

@makefu, many of the tests require an internet connection. I have changed the PR to disable the tests that cannot pass in our sandbox.

**Comment by peterhoeg** [comment]
Oh, and the pypi package doesn't contain the tests so we need to fetch from GH instead.

**Comment by makefu** [comment]
@peterhoeg wow, fantastic. Thanks for the effort! I think we should just disable aarch64 builds.

**Comment by xeji** [comment]
> xeji, are you sure this ever worked on aarch64?

Not sure it  works, but the current version builds on aarch64.  I think disabling aarch64 is fine for now.

**Pull request merged**
