### PR TITLE
mkvtoolnix: 7.8.0 -> 7.9.0

### PR DESCRIPTION
**Pull request by codyopel**
Added support for the new qt5 gui

@Fuuzetsu @k0ral

### CODE REVIEW

**Comment by Fuuzetsu** [comment]
Cool. Can we make wxWidgets off by default or even gone all together?

**Comment by codyopel** [comment]
The QT5 interface still has some minor bugs that need to be fixed, they will probably be fixed by the next 8.0.0 release(such as can't disable/enable steams individually).  The biggest issue is the Rakefile doesn't install the icons and desktop entries when wxwidgets is disabled(this was probably originally a way to detect if the GUI was enabled).  I would consider this to be a transitional release so I have added support for both and the necessary fixes so that once everything works we can disable or remove wxwidgets.

**Comment by k0ral** [comment]
Could you please add `legacyGUI = false` to the `mkvtoolnix-cli` override (in `all-packages.nix`) ?
I think this is needed so the `assert legacyGUI -> withGUI && wxGTK != null;` works correctly.

**Comment by codyopel** [comment]
It doesn't need to be added to `all-packages.nix`, the assert will work correctly as is, it enforces that for `legacyGUI` to be enabled that `withGUI` must be enabled and `wxGTK` must not be null.  It only matters that `mkvtoolnix-cli` must override/disable `withGUI` in `all-packages.nix`.  If `withGUI` is disabled, then the if statement in `configureFlags` will never pass the `legacyGUI` flag regardless of whether it is enabled or not.

As far as disabling  `legacyGUI` by default, it can't be done cleanly yet, there are upstream fixes needed to the build system that I previously described.

**Comment by k0ral** [comment]
As a matter of fact, the assertion currently fails:

```
> nix-build -A mkvtoolnix-cli
error: assertion failed at "/home/koral/nixpkgs/pkgs/applications/video/mkvtoolnix/default.nix":15:1
```

`legacyGUI` is `true` by default, thus it requires `withGUI` to be `true` as well, which doesn't hold for `mkvtoolnix-cli`.

**Comment by codyopel** [comment]
Yeah, your right, I wasn't paying attention there, I should sleep.

**Comment by codyopel** [comment]
@k0ral 
OK, now it should work.  This way should allow you to enable one or the other or both now too.
@k0ral @Fuuzetsu 
Just to avoid confusion from anyone that uses to package in the meantime, I disabled the newer qt5 GUI until the next release when some issues with it can be resolved.  The current GUI I left titled as legacy so that it is easy to switch back to the QT interface once 8.0.0 is released and hopefully it will be usable at that point.

**Comment by Fuuzetsu** [comment]
What concerns me sligthly is that anyone who had `withGUI = false` now gets wxWidgets GUI. Feels like `legacyGUI` should be set to `false` when `withGUI` is but that's difficult to put in.

What I would do instead is keep `wxWidgets` as `withGUI` so that it remains the default for this release and expose the QT5 GUI under a new option. Then in next release we can just make QT5 the default and deal with wxWidgets separately. This means that only people likely to use the recent package are going to be bitten by change of attributes (easily fixable) rather than suddenly getting `wxWidgets` which with its dependencies is too heavy to just be pulled in randomly. Consider `mkvtoolnix` being used on a server, with this change suddenly we're pulling in `wxWidgets`…

**Comment by codyopel** [comment]
I do agree, but to note that we also already have both `mkvtoolnix`(gui) & `mkvtoolnix-cli` that should handle this for anyone that uses the package.

**Comment by Fuuzetsu** [comment]
Ah, you're correct.

**Pull request merged**
