### PR TITLE
kodi: use LTS jdk11

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change
Build broke with JDK16

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by aanderse — APPROVED** [review]
Thank you!

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 119603` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
14 packages built:
</summary>
<ul>
<li>kodi (kodiPackages.kodi)</li>
<li>kodiPackages.a4ksubtitles</li>
<li>kodiPackages.inputstream-adaptive</li>
<li>kodiPackages.inputstream-ffmpegdirect</li>
<li>kodiPackages.inputstream-rtmp</li>
<li>kodiPackages.joystick</li>
<li>kodiPackages.kodi-platform</li>
<li>kodiPackages.netflix</li>
<li>kodiPackages.pvr-hdhomerun</li>
<li>kodiPackages.pvr-hts</li>
<li>kodiPackages.pvr-iptvsimple</li>
<li>kodiPackages.steam-controller</li>
<li>kodiPackages.vfs-libarchive</li>
<li>kodiPackages.vfs-sftp</li>
</ul>
</details>

**Comment by aanderse** [comment]
Sorry... too early, brain wasn't working. What about `kodi-wayland` and `kodi-gbm`?

**Comment by SuperSandro2000** [comment]
```
Caught: java.lang.reflect.InaccessibleObjectException: Unable to make field protected transient int java.util.AbstractList.modCount accessible: module java.base does not "opens java.util" to unnamed module @c5c7a5a
java.lang.reflect.InaccessibleObjectException: Unable to make field protected transient int java.util.AbstractList.modCount accessible: module java.base does not "opens java.util" to unnamed module @c5c7a5a
        at Generator$_run_closure1.doCall(Generator.groovy:43)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at Generator.run(Generator.groovy:39)
make[2]: *** [build/swig/CMakeFiles/python_binding.dir/build.make:119: build/swig/AddonModuleXbmcwsgi.i.cpp] Error 1
make[1]: *** [CMakeFiles/Makefile2:11159: build/swig/CMakeFiles/python_binding.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by petabyteboy** [comment]
https://github.com/NixOS/nixpkgs/pull/119611

**Comment by aanderse** [comment]
I just built this locally, ran a quick test, everything is fine.

@SuperSandro2000 what is that issue from?

**Comment by SuperSandro2000** [comment]
> I just built this locally, ran a quick test, everything is fine.
> 
> @SuperSandro2000 what is that issue from?

I tried building kodi-wayland and kodi-gbm on master.

**Comment by aanderse** [comment]
Ah yes, thanks.

**Pull request merged**
