### PR TITLE
Bazel 3

### PR DESCRIPTION
**Pull request by avdv**
###### Motivation for this change

Bazel 3 has been released.

edit: I just realized that there already was #85356 which was closed eventually.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Profpatsch** [comment]
cc @uri-canva who wrote the first update PR.

**Comment by uri-canva** [comment]
Note you need to update all the hashes of the fetch derivations that use `buildBazelPackage`, as they depend on the bazel version.

**Comment by uri-canva** [comment]
That's probably why you're getting this failure:
```
error: build of '/nix/store/h4pv5mg2qif45075qc06iaqv5ib07r38-bazel-watcher-0.13.0.drv', '/nix/store/k63r46x8vz7nf58m009im1r1d4mmffa6-bazel-test-shebangs.drv' failed
```

**Comment by avdv** [comment]
> Note you need to update all the hashes of the fetch derivations that use `buildBazelPackage`, as they depend on the bazel version.

Ok, thanks for that hint. I'll look into this...

**Comment by avdv** [comment]
I have updated the hashes of all the packages using `buildBazelPackage`.

And I also added a patch to reverse commit https://github.com/bazelbuild/bazel/commit/15d80dc11b5270ce6cc67fd4e9b502dfb0204e3a because it made it hard to replace the python shebang line (the `nix-build . -A bazel.tests` run failed because of this).

BTW, is there an easy way to update the hashes, short doing it manually?

**Review by uri-canva — APPROVED** [review]

**Comment by kalbasit** [comment]
@avdv we could file a patch upstream to move the whole shebang to a java variable so we could substitute it out on our end, whst do you think? Might be difficult to keep maintaining this revert.

**Comment by avdv** [comment]
Yes, we could do that. But how likely is it that they except such a change?

The plan would be to apply that patch here until after it is merged in an upstream release, right?

**Comment by Profpatsch** [comment]
Do we have any reverse dependencies in nixpkgs which depend on bazel 2? If not, I’d prefer we remove the bazel 2 files.

**Comment by avdv** [comment]
> Do we have any reverse dependencies in nixpkgs which depend on bazel 2? If not, I’d prefer we remove the bazel 2 files.

:+1: It seems every project that used bazel 2 before, can be build with bazel 3 now.

**Comment by avdv** [comment]
> we could file a patch upstream to move the whole shebang to a java variable so we could substitute it out on our end, whst do you think? Might be difficult to keep maintaining this revert.

@kalbasit I tried to implement that idea:
```diff
--- a/src/main/java/com/google/devtools/build/lib/bazel/rules/python/BazelPythonSemantics.java	2020-05-25 14:46:01.608403087 +0200
+++ b/src/main/java/com/google/devtools/build/lib/bazel/rules/python/BazelPythonSemantics.java	2020-05-25 14:50:52.881398320 +0200
@@ -238,14 +238,15 @@
         // TODO(#8685): Remove this special-case handling as part of making the proper shebang a
         // property of the Python toolchain configuration.
         String pythonExecutableName = OS.getCurrent() == OS.OPENBSD ? "python3" : "python";
+        String pythonShebang = "#!/usr/bin/env " + pythonExecutableName;
         ruleContext.registerAction(
             new SpawnAction.Builder()
                 .addInput(zipFile)
                 .addOutput(executable)
                 .setShellCommand(
                     shExecutable,
-                    "echo '#!/usr/bin/env "
-                        + pythonExecutableName
+                    "echo '"
+                        + pythonShebang
                         + "' | cat - "
                         + zipFile.getExecPathString()
                         + " > "

```

and then replacing the `pythonShebang` variable with
```sh
substituteInPlace "$path" \
  --replace '+ pythonShebang' "+ \"${python3}/bin/python\"" \
  ...
```
What do you think?

**Comment by FRidh** [comment]
What is the issue with the shebang? `#!/usr/bin/env python3` seems fine for patch-shebangs.

**Comment by avdv** [comment]
> What is the issue with the shebang? `#!/usr/bin/env python3` seems fine for patch-shebangs.

@FRidh What do you mean? What is a patch-shebang?

The point is to replace the "/usr/bin/env python3" call with the path to the python binary in the resulting bazel derivation. The replacement currently fails because of upstream code changes, which later makes the build error out.

Do you have any better idea to resolve this?

**Comment by FRidh** [comment]
patch-shebangs is a script we run (automatically) as part of our builds to exactly do this, convert such shebangs to absolute paths in the nix store.

**Comment by Profpatsch** [comment]
@FRidh pretty sure there was a stupid reason we need this patch. Either because the file is used at build time or because it’s zipped into a jar at the end.

**Comment by Profpatsch** [comment]
> +1 It seems every project that used bazel 2 before, can be build with bazel 3 now.

cool, then let’s replace the files in `bazel-latest` instead of creating a `bazel_3` directory.

**Comment by avdv** [comment]
> patch-shebangs is a script we run (automatically) as part of our builds to exactly do this, convert such shebangs to absolute paths in the nix store.

Ah, OK. But, this fails here since  the files are compiled to class files (and I suppose the script runs afterwards) and also the code to replace looks like this:
```java
                   "echo '#!/usr/bin/env "
                        + pythonExecutableName
                        + ...
```
So it spans multiple lines with all sorts of quoting and string concatenation going on...

**Comment by FRidh** [comment]
Yes, but after that piece of code is executed we should run patch-shebangs.

**Comment by avdv** [comment]
> Yes, but after that piece of code is executed we should run patch-shebangs.

That piece of code is not executed during the build.

**Comment by kalbasit** [comment]
> > we could file a patch upstream to move the whole shebang to a java variable so we could substitute it out on our end, whst do you think? Might be difficult to keep maintaining this revert.
> 
> @kalbasit I tried to implement that idea:
> ```diff
> --- a/src/main/java/com/google/devtools/build/lib/bazel/rules/python/BazelPythonSemantics.java	2020-05-25 14:46:01.608403087 +0200
> +++ b/src/main/java/com/google/devtools/build/lib/bazel/rules/python/BazelPythonSemantics.java	2020-05-25 14:50:52.881398320 +0200
> @@ -238,14 +238,15 @@
>          // TODO(#8685): Remove this special-case handling as part of making the proper shebang a
>          // property of the Python toolchain configuration.
>          String pythonExecutableName = OS.getCurrent() == OS.OPENBSD ? "python3" : "python";
> +        String pythonShebang = "#!/usr/bin/env " + pythonExecutableName;
>          ruleContext.registerAction(
>              new SpawnAction.Builder()
>                  .addInput(zipFile)
>                  .addOutput(executable)
>                  .setShellCommand(
>                      shExecutable,
> -                    "echo '#!/usr/bin/env "
> -                        + pythonExecutableName
> +                    "echo '"
> +                        + pythonShebang
>                          + "' | cat - "
>                          + zipFile.getExecPathString()
>                          + " > "
> 
> ```
> 
> and then replacing the `pythonShebang` variable with
> ```sh
> substituteInPlace "$path" \
>   --replace '+ pythonShebang' "+ \"${python3}/bin/python\"" \
>   ...
> ```
> What do you think?

Yes that's what I meant! I doubt upstream will kill this patch because it changes nothing on their end but allows us to sed the var on our side :+1:

**Comment by Wulfsta** [comment]
Please consider changing the fetch phase as described [here](https://github.com/NixOS/nixpkgs/issues/87922#issuecomment-632474302).

**Comment by avdv** [comment]
> cool, then let’s replace the files in `bazel-latest` instead of creating a `bazel_3` directory.

@Profpatsch there is no bazel-latest directory, you mean we should introduce that instead of bazel_3, right?

**Comment by avdv** [comment]
> Please consider changing the fetch phase of `build-bazel-package` for this release as described [in this issue](https://github.com/NixOS/nixpkgs/issues/87922#issuecomment-632474302).

@Wulfsta  I would want to keep the two issues separate; since I do not fully understand the implications of changing the build-bazel-package function and this could be done at a later time.

**Comment by Wulfsta** [comment]
@avdv I just thought a major version change would be a good time to introduce that, but if you want to keep it separate that sounds good to me. I might take a crack at it once this is resolved.

**Comment by Profpatsch** [comment]
> @avdv I just thought a major version change would be a good time to introduce that,

`build-bazel-package` should be completely orthogonal to the major bazel version, they are going to release a new one every three months.



> @Profpatsch there is no bazel-latest directory, you mean we should introduce that instead of bazel_3, right?

I was looking at an old branch, I suggest we rename `bazel_2` to `bazel_3` and then just change things in-place.

**Comment by Wulfsta** [comment]
@Profpatsch That patch would require changing all the hashes of the fetch derivations in packages that use `build-bazel-package`, which is required for Bazel version updates as well - this is the only reason I thought it might be worth doing these at the same time.

**Comment by Profpatsch** [comment]
@avdv are you okay with the remaining changes or should I take a look?

**Comment by avdv** [comment]
> @avdv are you okay with the remaining changes or should I take a look?

@Profpatsch I just haven't had the time working on this PR again integrating all the remaining review comments. 

I get to it this evening, probably.

**Comment by avdv** [comment]
@Profpatsch I could spare a few minutes and updated the branch! :-)

**Comment by Profpatsch** [comment]
It looks like the build is failing with a missing executable in a genrule phase:

```
ERROR: /build/bazel_src/src/BUILD:305:2: Executing genrule //src:embedded_tools_nojdk failed (Exit 2): bash failed: error executing command
```
https://logs.nix.ci/?key=nixos/nixpkgs.87726&attempt_id=25543299-77f2-4d2e-b4c1-901c0877dbc0

**Comment by avdv** [comment]
> It looks like the build is failing with a missing executable in a genrule phase:

My interpretation is that the `create_embedded_tools` skript is somehow broken:
```
bazel-out/host/bin/src/create_embedded_tools: line 2: $'PK\003\004': command not found
```
It contains some sort of zip header where it would have expected a command. It also fails locally for me. How can I look at the output / disable the sandbox perhaps?

**Comment by Profpatsch** [comment]
> How can I look at the output / disable the sandbox perhaps?

`nix-build --keep-failed`

**Comment by avdv** [comment]
> nix-build --keep-failed

Already did that, but this does not contain the /build files:
```
$ ls -l /tmp/nix-build-bazel-3.1.0.drv-0/bazel_src
...
lrwxrwxrwx  1 nixbld1 nixbld     43 May 28 16:15 bazel-bazel_src -> /build/bazel_CicdGTsu/out/execroot/io_bazel
lrwxrwxrwx  1 nixbld1 nixbld     64 May 28 16:15 bazel-bin -> /build/bazel_CicdGTsu/out/execroot/io_bazel/bazel-out/k8-opt/bin
lrwxrwxrwx  1 nixbld1 nixbld     53 May 28 16:15 bazel-out -> /build/bazel_CicdGTsu/out/execroot/io_bazel/bazel-out
lrwxrwxrwx  1 nixbld1 nixbld     69 May 28 16:15 bazel-testlogs -> /build/bazel_CicdGTsu/out/execroot/io_bazel/bazel-out/k8-opt/testlogs
```
the symlinks are broken.

**Comment by avdv** [comment]
Although I cannot really see why, I think the shebang patch broke this. :microscope:

**Comment by avdv** [comment]
So, yes the variable was still to be found inside the class file (might be debugging information). Locally, I made this change:
```diff
-          --replace '+ pythonShebang' "+ \"#!${python3}/bin/python\"" \
+          --replace '#!/usr/bin/env " + pythonExecutableName' "#!${python3}/bin/python\"" \
```
So instead of replacing the `pythonShebang` variable where it is used, I am replacing its value when it is initialized. Which kind of makes introducing the variable in the first place a bit useless... What do you think @kalbasit ?

My first attempt actually was to replace the original code spanning multiple lines, but that did not work since I tried to use globbing.

(since the replacement is really only applicable in that one file, I'll probably introduce a single replaceInPlace call instead)

**Comment by avdv** [comment]
I updated the branch again, fixing the shebang-test.

The original branch using the reversed patch of the upstream change is still available here: https://github.com/avdv/nixpkgs/tree/bazel_3_a

**Comment by Profpatsch** [comment]
Looks good, the linux build is passing now. We have a small test of `python_binary`, so I assume it should be fine now. If not, we can always add more tests.

**Comment by Profpatsch** [comment]
All checks have passed, LGTM!

Bazel 3.2 was released two days ago :stuck_out_tongue_closed_eyes:

**Comment by avdv** [comment]
> Bazel 3.2 was released two days ago stuck_out_tongue_closed_eyes

New PR here: #89157 :rocket:

**Comment by avdv** [comment]
> actually replacing the variable definition is what I had in mind because it’s less error prone than the quoted echo part.

But it just looks so cumbersome... And by the specificity of the variable name I thought it was quite safe. Anyway, I am still learning and try to understand what's best practice when doing things.

> BTW did you file a PR upstream?

No, not yet. Thanks for reminding me! 😁

**Comment by avdv** [comment]
@kalbasit the PR on bazel has been merged: https://github.com/bazelbuild/bazel/commit/dfaf06a2d48042a2a74e4140161a1d17f5e0d84d

On the next version bump, we should be able to drop the patch.

**Pull request merged**
