### PR TITLE
libressl: remove weird and old man compression workaround

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 172102` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>acme-sh</li>
    <li>testssl</li>
    <li>twa</li>
  </ul>
</details>
<details>
  <summary>16 packages failed to build:</summary>
  <ul>
    <li>cvsq</li>
    <li>gitolite</li>
    <li>hyprspace</li>
    <li>iodine</li>
    <li>libressl_3_5</li>
    <li>nettools</li>
    <li>openconnect</li>
    <li>openconnect_openssl</li>
    <li>openconnect_unstable</li>
    <li>swtpm</li>
    <li>unixtools.arp</li>
    <li>unixtools.ifconfig</li>
    <li>unixtools.netstat</li>
    <li>unixtools.ping</li>
    <li>unixtools.route</li>
    <li>vpnc-scripts</li>
  </ul>
</details>
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>catgirl</li>
    <li>disnix</li>
    <li>dydisnix</li>
    <li>dysnomia</li>
    <li>libressl</li>
    <li>netcat</li>
    <li>notemap</li>
    <li>openntpd (openntpd_nixos)</li>
    <li>perseus-cli</li>
    <li>restream</li>
    <li>sacc</li>
    <li>telescope</li>
    <li>wasm-pack</li>
  </ul>
</details>

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 172102` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>acme-sh</li>
    <li>testssl</li>
    <li>twa</li>
  </ul>
</details>
<details>
  <summary>16 packages failed to build:</summary>
  <ul>
    <li>cvsq</li>
    <li>gitolite</li>
    <li>hyprspace</li>
    <li>iodine</li>
    <li>libressl_3_5</li>
    <li>nettools</li>
    <li>openconnect</li>
    <li>openconnect_openssl</li>
    <li>openconnect_unstable</li>
    <li>swtpm</li>
    <li>unixtools.arp</li>
    <li>unixtools.ifconfig</li>
    <li>unixtools.netstat</li>
    <li>unixtools.ping</li>
    <li>unixtools.route</li>
    <li>vpnc-scripts</li>
  </ul>
</details>
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>catgirl</li>
    <li>disnix</li>
    <li>dydisnix</li>
    <li>dysnomia</li>
    <li>libressl</li>
    <li>netcat</li>
    <li>notemap</li>
    <li>openntpd (openntpd_nixos)</li>
    <li>perseus-cli</li>
    <li>restream</li>
    <li>sacc</li>
    <li>telescope</li>
    <li>wasm-pack</li>
  </ul>
</details>

**Comment by davidak** [comment]
libressl_3_5 fails. did it also fail before?

**Comment by SuperSandro2000** [comment]
Never build https://hydra.nixos.org/job/nixpkgs/trunk/libressl_3_5.aarch64-darwin

**Pull request merged**
