### PR TITLE
riot-{web,desktop}: 1.0.8 -> 1.1.0

### PR DESCRIPTION
**Pull request by nyanloutre**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by petabyteboy** [comment]
Built and tested riot-desktop, it seems to work fine :+1:

**Comment by BenBals** [comment]
I might be worth running the checks again as riot-desktop depends on yarn, an update of which has just been merged.

**Comment by Ma27** [comment]
Currently testing another PR, but I'm planning to test this after that :)

**Comment by BenBals** [comment]
##### Reviewed points

- [x] package build on Linux nixos-beb 4.19.37 #1-NixOS SMP Sat Apr 27 07:36:41 UTC 2019 x86_64 GNU/Linux
- [x] executables tested on Linux nixos-beb 4.19.37 #1-NixOS SMP Sat Apr 27 07:36:41 UTC 2019 x86_64 GNU/Linux

##### Possible improvements

##### Comments
Run with `nix-review`

**Comment by Ma27** [comment]
Built and tested locally :+1:

**Comment by Ma27** [comment]
@nyanloutre thanks!

**Pull request merged**
