### PR TITLE
neon: 0.29.6 -> 0.30.1

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Test build.

It is my update of a library package, so I'm not sure how to test this properly (as it can not be test started, obviousely).

### CODE REVIEW

**Comment by lethalman** [comment]
Built locally thanks.

**Comment by peti** [comment]
This update broke `davfs2`: http://hydra.cryp.to/build/1319898/log/raw.

**Comment by matthiasbeyer** [comment]
I will re-add the old version of neo and fix this, if not fixed already.

Will propably take 30-60 mins until I can do this.

**Comment by matthiasbeyer** [comment]
PR coming...

**Pull request merged**
