### PR TITLE
disable builds globally for manually downloaded packages

### PR DESCRIPTION
**Pull request by superherointj**
[wip]

* disable builds globally for manually downloaded packages
  (that cannot be built at hydra/nixpkgs-review)
* revert individually disabled builds for manually downloaded packages
  - pixinsight
  - displaylink
  - ndi
  - obs-ndi

Goal is to avoid false positive failures on automated builds of unfree packages.

* Sample list of manually downloaded packages for testing this PR:
    - citrix-workspace
    - ib-tws
    - mathematica
    - wolfram-engine
    - javacard-devkit
    - oraclejdk
    - everspace
    - koboredux
    - sm64ex
    - snapdragon-profiler
    - sqldeveloper
    - worldofgoo

Pending:
* Investigating testing method used to validate this solution.

### CODE REVIEW

**Comment by tpwrules** [comment]
Is this requirement documented anywhere? I had figured in the past this was unnecessary because Hydra already will not build unfree software.

**Comment by superherointj** [comment]
> Is this requirement documented anywhere? I had figured in the past this was unnecessary because Hydra already will not build unfree software.

It still errors in nixpkgs-review.

**Comment by tpwrules** [comment]
Not saying that it's invalid to set, but that documenting the motivation would be good to help it be done consistently in the future.

**Comment by superherointj** [comment]
> Is this requirement documented anywhere?

I don't know. I just want to avoid the long stream of errors when building with `nixpkgs-review`. (I happen to use it very often, and it is annoying.)

**Comment by superherointj** [comment]
> documenting the motivation would be good to help it be done consistently in the future.

I agree. Ideally we should reach some consensus on this.

Also notice, that when using nixpkgs-review, it is common to build unfree packages, like drivers. So, skipping unfree is not the same intended behavior.

**Comment by superherointj** [comment]
> Hydra already will not build unfree software.

Skipping `unfree` is not the same intended behavior.
Is common to nixpkgs-review to build unfree packages, like drivers.

**Comment by SuperSandro2000** [comment]
> It still errors in nixpkgs-review.

Ideally this should be fixed there but I am not sure how to generally fix it. You could skip single packages though.

**Comment by superherointj** [comment]
> Ideally this should be fixed there but I am not sure how to generally fix it. You could skip single packages though.

The problem is, there is still a need to build unfree packages, but just a subset of it shouldn't be built. And the idea is setting hydraPlatforms for this subset. I don't think this problem can be solved at nixpkgs-review because it lacks the information to know which unfree package to avoid building. And hydraPlatforms offers just that.

**Comment by superherointj** [comment]
3 questions to reviewer:
1) Should `manual downloads` have builds disabled for hydra/nixpkgs-review?
2) Shouldn't docs be changed to reflect the need of disabling builds for manual downloads?
3) Is compiled list acceptable?

**Comment by superherointj** [comment]
> > It still errors in nixpkgs-review.
> 
> Ideally this should be fixed there but I am not sure how to generally fix it. You could skip single packages though.

@PedroHLC suggested a general solution at requireFile. And it seems to work fine.

**Pull request closed without merging**
