### PR TITLE
nixos/cfdyndns: dynamic user and loadcredential

### PR DESCRIPTION
**Pull request by happysalada**
## Description of changes

I haven't tested this PR yet, but I'm opening it early for comments.
2 changes are made
- replace a specific user with dynamic user. I don't see any reason here to run this as a specific user.
- use load_credentials for secrets.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jian-lin — APPROVED** [review]
diff LGTM (cannot test it since I am not a cf dns user)

**Comment by happysalada** [comment]
I just tested this on a linux-x86_64 machines and the logs are empty after running this.
I'm guessing it's good news, and will report if any problems arise later.
I don't want to merge this before getting a comment from either @colemickens or @nrdxp though.

**Comment by nrdxp** [comment]
> I just tested this on a linux-x86_64 machines and the logs are empty after running this. I'm guessing it's good news, and will report if any problems arise later. I don't want to merge this before getting a comment from either @colemickens or @nrdxp though.

There should be some logs, either about how your ip has been updated, or if the record is already up to date, it should report that.

**Comment by happysalada** [comment]
I have systemd timers logs
```
Sep 13 19:15:01 bee systemd[1]: Started CloudFlare Dynamic DNS Client.
Sep 13 19:15:05 bee systemd[1]: cfdyndns.service: Deactivated successfully.
Sep 13 19:15:05 bee systemd[1]: cfdyndns.service: Consumed 50ms CPU time, received 24.
```
but no logs coming directly from cfdyndns.

**Comment by colemickens** [comment]
You have to check the service logs, not just the timer.

I don't really know how LoadCredential is supposed to work. So far, installing the apitoken with sops-nix doesn't work with this:

```
Sep 13 12:31:26 raisin systemd[1]: Started CloudFlare Dynamic DNS Client.
Sep 13 12:31:26 raisin cfdyndns-start[3248769]: cat: /run/secrets/cf-apitoken-mickens_us: Permission denied
Sep 13 12:31:26 raisin cfdyndns-start[3248770]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Request not successful: {\"errors\":[{\"code\":6003,\"error_chain\":[{\"code\":6111,\"message\":\"Invalid format for Authorization header\"}],\"message\":\"Invalid request headers\"}],\"messages\":[],\"result\":null,\"success\":false}"', src/main.rs:121:63
Sep 13 12:31:26 raisin cfdyndns-start[3248770]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by colemickens** [comment]
Actually, I just realized that I pulled this PR and didn't actually update my nixpkgs. Ooofta, sorry, I'll update in a few minutes...

**Comment by colemickens** [comment]
There we go:

```
Sep 13 12:37:51 raisin systemd[1]: Started CloudFlare Dynamic DNS Client.
Sep 13 12:37:51 raisin cfdyndns-start[3255909]: raisin.hosts.mickens.us (72.209.157.122 -> 136.34.115.157)...
Sep 13 12:37:51 raisin systemd[1]: cfdyndns.service: Deactivated successfully.
Sep 13 12:37:51 raisin systemd[1]: cfdyndns.service: Consumed 53ms CPU time, received 11.4K IP traffic, sent 2.0K IP traffic.
```

with:

```nix
{
    # ...
    sops.secrets."cf-apitoken-mickens_us" = {
      sopsFile = ../../secrets/encrypted/cf-apitoken-mickens_us;
      format = "binary";
    };
    services.cfdyndns = {
      enable = true;
      apiTokenFile = config.sops.secrets."cf-apitoken-mickens_us".path;
      records = [ "raisin.hosts.mickens.us" ];
    };
    # ...
}
```

Seems like it's probably good to merge.

**Comment by happysalada** [comment]
Using it with agenix with a similar config. Ill wait until tomorrow just in case anyone else wants to have a look.

**Comment by nrdxp** [comment]
@happysalada, as you can see from the code here, the binary should print to standard output in either case (whether the record was updated or skipped):
https://github.com/colemickens/cfdyndns/blob/master/src/main.rs#L160-L164

So if there is no output at all, that is a bit of a concern that something could be amiss.

**Comment by nrdxp** [comment]
@happysalada, I'll amend my previous statement, the binary only prints if it skips a record if `RUST_LOG` is set to info, which apparently is not the default in the version in nixpkgs, so no output is fine after all, assuming your record didn't need updating.

**Pull request merged**
