### PR TITLE
Add VLS (new Vue language server) as a new node package

### PR DESCRIPTION
**Pull request by olimorris**
###### Motivation for this change
Incorporating Nix into my Neovim workflow. I noticed that VLS (which is the new Vue Language Server) wasn't available as a node package.

###### Things done

Followed guide as per https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/node.section.md

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 120498` at c0577e32 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages skipped due to time constraints:</summary>
  <ul>
    <li>iosevka</li>
    <li>lumo</li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
  </ul>
</details>

**Review by midchildan — CHANGES_REQUESTED** [review]
The change itself looks good and basic completion using VLS seems to work. There are a few remaining things left:

* Fix the commit message to conform with [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md) and check off "Fits CONTRIBUTING.md"
* Remove the merge commit and rebase if necessary (See [making patches](https://github.com/NixOS/nixpkgs/blob/master/doc/contributing/submitting-changes.chapter.md#making-patches-submitting-changes-making-patches))
* Run `bin/vls` and check off  "Tested execution of all binary files". This is a good opportunity to catch packaging issues, and it'd be best if people actually using the package can test it.

**Review by midchildan — APPROVED** [review]
LGTM

**Review by midchildan — CHANGES_REQUESTED** [review]
Oops, I missed that there're still 2 commits in this PR. Could you squash them?

**Comment by olimorris** [comment]
I've stuffed up the commit history so gonna delete this and start over

**Pull request closed without merging**
