### PR TITLE
gyp: Fix sandboxed build on stdenvDarwinPure

### LINKED ISSUE #10091: darwin: http-parser doesn't build with sandbox enabled
I'm on master (https://github.com/NixOS/nixpkgs/commit/4a8e06f1f06fa0653793f038f5e2f53498ff7de5) on Darwin (OSX 10.10.5) with stdenvDarwinPure and building with chroot (Darwin sandbox). I seem to have issues with Python multiprocessing module (and probably with the sandbox). This error with building http-parser:

```
these derivations will be built:
  /nix/store/pzadiyj8wjmy9vkdnx8qhg7qp2gzw2y1-http-parser-2.5.0.drv
building path(s) ‘/nix/store/mvdhhjkk6rrvw4j2nml1x5ljv9m5fra7-http-parser-2.5.0’
unpacking sources
unpacking source archive /nix/store/pzrd7hdkhsyn8i0glnkchmp6k0n36gbn-v2.5.0.tar.gz
source root is http-parser-2.5.0
patching sources
applying patch /nix/store/x3rg29m48h5lkn200mysqz3kr8vq7rz8-build-shared.patch
patching file http_parser.gyp
configuring
sh: /usr/sbin/sysctl: Operation not permitted
Traceback (most recent call last):
  File "/nix/store/648d307hm1lm586dj380jdcvfq0cg9cv-python2.7-gyp-2015-06-11/bin/.gyp-wrapped", line 10, in <module>
    load_entry_point('gyp==0.1', 'console_scripts', 'gyp')()
  File "/nix/store/648d307hm1lm586dj380jdcvfq0cg9cv-python2.7-gyp-2015-06-11/lib/python2.7/site-packages/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/nix/store/648d307hm1lm586dj380jdcvfq0cg9cv-python2.7-gyp-2015-06-11/lib/python2.7/site-packages/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/nix/store/648d307hm1lm586dj380jdcvfq0cg9cv-python2.7-gyp-2015-06-11/lib/python2.7/site-packages/gyp/__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "/nix/store/648d307hm1lm586dj380jdcvfq0cg9cv-python2.7-gyp-2015-06-11/lib/python2.7/site-packages/gyp/__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "/nix/store/648d307hm1lm586dj380jdcvfq0cg9cv-python2.7-gyp-2015-06-11/lib/python2.7/site-packages/gyp/input.py", line 2759, in Load
    check, generator_input_info)
  File "/nix/store/648d307hm1lm586dj380jdcvfq0cg9cv-python2.7-gyp-2015-06-11/lib/python2.7/site-packages/gyp/input.py", line 596, in LoadTargetBuildFilesParallel
    parallel_state.pool = multiprocessing.Pool(multiprocessing.cpu_count())
  File "/nix/store/a8hv9fl48qnx4nl8ji78xp2p856zz6pa-python-2.7.10/lib/python2.7/multiprocessing/__init__.py", line 136, in cpu_count
    raise NotImplementedError('cannot determine number of cpus')
NotImplementedError: cannot determine number of cpus
builder for ‘/nix/store/pzadiyj8wjmy9vkdnx8qhg7qp2gzw2y1-http-parser-2.5.0.drv’ failed with exit code 1
error: build of ‘/nix/store/pzadiyj8wjmy9vkdnx8qhg7qp2gzw2y1-http-parser-2.5.0.drv’ failed
```

And, on other occasions, seen seen this

```
  File "/nix/store/a8hv9fl48qnx4nl8ji78xp2p856zz6pa-python-2.7.10/lib/python2.7/multiprocessing/synchronize.py", line 59, in <module>
    " function, see issue 3770.")
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
```

### PR DESCRIPTION
**Pull request by datakurre**
Fixes #10091

### CODE REVIEW

**Comment by copumpkin** [comment]
:heart:

**Comment by domenkozar** [comment]
Let's submit this upstream?

**Comment by datakurre** [comment]
The second patch (no-xcode) probably should, but I just updated an old patch without really learning what it does and why.

**Comment by zeroware** [comment]
I'm trying to build something with `node-gyp` and I get the "Install XCode" popup. 
Is this patch fix it ?

**Comment by datakurre** [comment]
@zeroware No, this already implements replicates nodejs patch for a python package, but have you already tried sandboxed builds?

Either with ``--option build-use-chroot true`` or adding ``build-use-chroot = true`` into ``/etc/nix/nix.conf``.

See https://nixos.org/wiki/Nix_on_OS_X for more information.

**Comment by zeroware** [comment]
@datakurre Thanks for your answer.
Sandboxed builds are broken for the moment on nix 1.10. Will try with HEAD.

**Comment by datakurre** [comment]
@zeroware Building nodePackages.node-gyp with Nix built from master worked for me.

**Comment by zeroware** [comment]
I did some digging and the problem is that node-gyp bundle it's own version of gyp which is not nix-compatible. Anyway this is unrelated to this issue , I will create a new one.

**Comment by Profpatsch** [comment]
(triage) @datakurre what’s the status of this?

**Comment by datakurre** [comment]
@Profpatsch I've been off from darwin for a couple of months for now, so I must just close this :/

**Comment by the-kenny** [comment]
Can we take another look at this? It would solve an issue blocking https://github.com/NixOS/nixpkgs/pull/17316 and deprecate https://github.com/NixOS/nixpkgs/pull/17609.

(The PR applies cleanly on my darwin box, but trying to build `gyp` with sandbox enabled complains that it specifies a sandbox profile)

**Pull request closed without merging**
