### PR TITLE
Vim tridactyl

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by leona-ya** [comment]
@SuperSandro2000 Why do you just merge this when multiple packages fail to build with this PR?

Also tested with nixpkgs-review:

Result of `nixpkgs-review pr 199042` run on x86_64-linux
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.editorconfig-vim</li>
    <li>vimPlugins.flake8-vim</li>
    <li>vimPlugins.python-mode</li>
    <li>vimPlugins.tabnine-vim</li>
  </ul>
</details>
<details>
  <summary>93 packages built:</summary>
  <ul>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.asyncrun-vim</li>
    <li>vimPlugins.auto-save-nvim</li>
    <li>vimPlugins.bufferline-nvim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.cmp-dictionary</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-neosnippet</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.conflict-marker-vim</li>
    <li>vimPlugins.coq-artifacts</li>
    <li>vimPlugins.coq-thirdparty</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.deoplete-lsp</li>
    <li>vimPlugins.dracula-nvim</li>
    <li>vimPlugins.editorconfig-nvim</li>
    <li>vimPlugins.fern-vim</li>
    <li>vimPlugins.flit-nvim</li>
    <li>vimPlugins.fuzzy-nvim</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.haskell-tools-nvim</li>
    <li>vimPlugins.hop-nvim</li>
    <li>vimPlugins.jsonc-vim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.leap-nvim</li>
    <li>vimPlugins.legendary-nvim</li>
    <li>vimPlugins.lf-vim</li>
    <li>vimPlugins.lsp_signature-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.material-nvim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.ncm2-neosnippet</li>
    <li>vimPlugins.neco-vim</li>
    <li>vimPlugins.neodev-nvim</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neosnippet-vim</li>
    <li>vimPlugins.neotest-haskell</li>
    <li>vimPlugins.nord-nvim</li>
    <li>vimPlugins.nvim-base16</li>
    <li>vimPlugins.nvim-bqf</li>
    <li>vimPlugins.nvim-dap-python</li>
    <li>vimPlugins.nvim-gdb</li>
    <li>vimPlugins.nvim-jdtls</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-metals</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.omnisharp-extended-lsp-nvim</li>
    <li>vimPlugins.onenord-nvim</li>
    <li>vimPlugins.project-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.registers-nvim</li>
    <li>vimPlugins.satellite-nvim</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-media-files-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.vim-bazel</li>
    <li>vimPlugins.vim-closer</li>
    <li>vimPlugins.vim-codefmt</li>
    <li>vimPlugins.vim-commentary</li>
    <li>vimPlugins.vim-floaterm</li>
    <li>vimPlugins.vim-fugitive</li>
    <li>vimPlugins.vim-go</li>
    <li>vimPlugins.vim-illuminate</li>
    <li>vimPlugins.vim-maktaba</li>
    <li>vimPlugins.vim-slime</li>
    <li>vimPlugins.vim-startuptime</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.vim-tridactyl</li>
    <li>vimPlugins.vim-vsnip</li>
    <li>vimPlugins.vim-vsnip-integ</li>
    <li>vimPlugins.vim-which-key</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.virtual-types-nvim</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
> * vimPlugins.flake8-vim
> * vimPlugins.python-mode
> * vimPlugins.tabnine-vim

If you take a look at the diff then all of those only changed hashes, not revs, so I assume the hash was unstable already before this.
All of them have in common that they use submodules which can be impure.

**Comment by dotlambda** [comment]
I get
```
error: hash mismatch in fixed-output derivation '/nix/store/smxd29fmkm8bh7xsqcly55421sdpakzg-source.drv':
         specified: sha256-l2GS+7WOzEOYbmTxOiykLhQpY5qYGpqjdkfRif7YSAk=
            got:    sha256-qPax/8RwpgUJ8DMcH0hHkXHzgBw1Hw1iSqsZnGZgQZk=
error: 1 dependencies of derivation '/nix/store/mwaq15lb71p40zl4ngyaqr2zv4ya5ray-vimplugin-editorconfig-vim-2022-10-30.drv' failed to build
```
What could be the source of non-reproducability when using `fetchSubmodules = true`?

**Comment by dotlambda** [comment]
> If you take a look at the diff then all of those only changed hashes, not revs, so I assume the hash was unstable already before this.

That's not a reason to break them.

**Comment by leona-ya** [comment]
`YouCompleteMe` also uses submodules but was stable for me for quite some time. This PR broke it. And submodules should be afaik stable in general because they refer to a specific commit in the other repository.

In general: In my opinion (and I know some other maintainers feel the same way), you should not merge your own PRs directly. I can understand when you merge them after a few days if no one has reviewed them, but that was not the case with this and many other PRs.

**Comment by SuperSandro2000** [comment]
> What could be the source of non-reproducability when using `fetchSubmodules = true`?

I saw this ``fatal: invalid refspec '+refs/tags/v0.8.3^{}'`` in the logs. Could it be that upstream pinned the submodule to a tag that no longer exists and then our fetcher is always downloading HEAD?



> On what kind of machine did you compute these hashes?

NixOS unstable x86_64-linux

---

I wouldn't have merged if I'd known that the update script is flaky. In the past it worked and you could just merge the update PRs which also usually needs to be done fast otherwise you get constant merge conflicts.

**Comment by dotlambda** [comment]
> I saw this `fatal: invalid refspec '+refs/tags/v0.8.3^{}'` in the logs.

In the context of which plugin?

**Comment by SuperSandro2000** [comment]
Oh, sorry. Should have mentioned that. That's in ``vimPlugins.YouCompleteMe.src``. Just noticed that this happens 3 or 4 times.

**Comment by leona-ya** [comment]
I also saw that and it wondered me. I don't know where it comes from. Git submodules only work with specific commits and not tags. But maybe they had some fuckup with the submodules

**Pull request merged**
