### PR TITLE
Dlang update

### PR DESCRIPTION
**Pull request by ThomasMader**
###### Motivation for this change

Update versions for dmd, dtools and dub.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build dmd dtools dub

**Comment by ThomasMader** [comment]
> Failure on x86_64-darwin (full log)

Could you maybe trigger a new run on Mac to see if it is reproducible on this machine?
On my machine it went through.

**Comment by Mic92** [comment]
@GrahamcOfBorg build dmd dtools dub

**Comment by Mic92** [comment]
@ThomasMader you also ask for borg access here: https://github.com/NixOS/ofborg/issues/22

**Comment by Mic92** [comment]
@LnL7 btw. do you have a sandbox on your builder now, right?

**Comment by ThomasMader** [comment]
I just did a rerun but everything went through again.
In /etc/nix/nix.conf I have build-use-sandbox = true and build-cores = 4.
I am running currently on macOS High Sierra 10.13.3 Beta (17D29a)

I will update to 10.13.4 Beta 2 maybe it's related to that.
Any way to get more information about the bot build machine?

**Comment by ThomasMader** [comment]
Did the update and now nix-build is stopping right at the beginning. :-/

> nix-build -A dmd
these derivations will be built:
  /nix/store/5h0d608gm0fn83jjcxdgvsaj9prcrnbb-dmd.drv
  /nix/store/vvy5r7j489my262f7qb3yy55319sg2lb-druntime.drv
  /nix/store/8yjsssadxk7wdb90pwjxqg7hi4095i5s-dmdBuild-2.078.2.drv
  /nix/store/9shv1rc5nc9jsly7msc73dh2arnxjljp-phobosUnittests-2.078.2.drv
  /nix/store/h4ga1vfh2j2fnvpibplhzhl9c3p8bzxi-dmd-2.078.2.drv
these paths will be fetched (128.47 MiB download, 609.35 MiB unpacked):
  /nix/store/24i0p29d4cw0vissa7wvmg16vb66jnsl-apple-lib-xpc
  /nix/store/26ssd6a59dw9lcsh5ycfp7m0jdby2sqb-apple-framework-CoreGraphics
  /nix/store/2fai9mvfi9nak6jxmqnvv9xqlq0qlinb-clang-wrapper-4.0.1
  /nix/store/cryxdda7a4pymfmn9zjkllqbc1cj58qs-dmd-2.067.1
  /nix/store/g8ljrl1hzd90ad58m1vzllxi90rpwgxd-apple-framework-IOSurface
  /nix/store/gk21pv5a8wwrj6frd5m283qjdvd1yvkn-clang-4.0.1
  /nix/store/jk9p05hmny8hlm7ryf6gqb8vv259vn76-llvm-4.0.1
  /nix/store/llppkqdpx0yvgkz38ynm5rkqnzl72zda-apple-framework-ApplicationServices
  /nix/store/np2zl9hr0p0xhhr65ijgjkf2qcskg2vf-dmdBuild-2.067.1
  /nix/store/pa9mggxfc2965vqf15nwjk58x687m0jl-stdenv-darwin
  /nix/store/qpr8ya4qjl1mbnpxrhyzanz6pgvy8yg6-MacOS_SDK-10.10
  /nix/store/z3xwixy8mqlmfxrln3i586wx89lny1is-apple-framework-Foundation
  /nix/store/z5l24i1ph8amj68ypmizl4l639vxb83x-apple-framework-ImageIO
  /nix/store/zmsg0kbyl492za3rcs6g5hjxajw403ly-apple-framework-CoreText
fetching path ‘/nix/store/jk9p05hmny8hlm7ryf6gqb8vv259vn76-llvm-4.0.1’...
building path(s) ‘/nix/store/2ml635qwfk2vfr64b6g7rc0hq5kdnjvz-dmd’
killing process 470
error: cannot kill processes for uid ‘30001’: failed due to signal 9 (Killed: 9)

**Comment by Mic92** [comment]
@ThomasMader I am not sure, if the same would happen on hydra though.

**Comment by grahamc** [comment]
cc @LnL7 can you take a look? :/

**Comment by ThomasMader** [comment]
I am on (Nix) 1.11.16 and I wanted to update to channel 17.09-darwin but nix-channel --update failed with the same problem.
I will try to reinstall nix.

**Comment by LnL7** [comment]
@grahamc Are you sure that's my builder? Works fine for me.

**Comment by LnL7** [comment]
@ThomasMader that looks like https://github.com/NixOS/nix/issues/1823

**Comment by joachifm** [comment]
I take it the failure is unrelated to this PR

**Pull request merged**
