### PR TITLE
nix-output-monitor: 1.0.1.1 -> 1.0.2.0

### PR DESCRIPTION
**Pull request by maralorn**
Package update with bugfixes.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 115042` at 07999ac6 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/94a04b16032e15c5d8174cf478a7ceae">haskellPackages.nix-output-monitor</a></li></li>
    <li><a href="https://gist.github.com/3b887cdac58da34cb9090340e2ae524d">nix-output-monitor</a></li></li>
  </ul>
</details>

**Comment by maralorn** [comment]
@r-rmcgibbo those build errors look completely unrelated to this change.

**Comment by maralorn** [comment]
Simple change, tests have passed.

**Comment by Mic92** [comment]
> @r-rmcgibbo those build errors look completely unrelated to this change.

Looks like @r-rmcgibbo passed the turing test in this instance.

**Comment by SuperSandro2000** [comment]
> @r-rmcgibbo those build errors look completely unrelated to this change.

I think I accidentally pushed a mass rebuild to master and ghc requires a rebuild which does not succeed on all hardware.

**Pull request merged**
