### PR TITLE
atom: 1.48.0 -> 1.53.0

### PR DESCRIPTION
**Pull request by MrMebelMan**
###### Motivation for this change
Update to a newer version.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by danieldk — COMMENTED** [review]
Result of `nixpkgs-review pr 108915` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>atom</li>
    <li>atom-beta</li>
  </ul>
</details>

`atom` runs fine, but `atom-beta` fails with:

```
nohup: failed to run command '/run/user/1000/atom-build/Atom/atom': No such file or directory
```

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 108915` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>atom</li>
    <li>atom-beta</li>
  </ul>
</details>

**Comment by MrMebelMan** [comment]
@danieldk, I don't know how to fix atom-beta 😣

**Comment by taku0** [comment]
The stable is now `1.54.0` and the beta is `1.55.0`.

**Comment by petabyteboy** [comment]
This seems to be done in https://github.com/NixOS/nixpkgs/pull/114277

**Pull request closed without merging**
