### PR TITLE
Revert nixExperimental / nixFlakes changes and deprecate nixFlakes attribute

### PR DESCRIPTION
**Pull request by edolstra**
###### Motivation for this change

This reverts #120141, which adds a `nixExperimental` attribute that enables all experimental features in Nix, and makes `nixFlakes` enable the flakes feature by default.

Usage of the `nixFlakes` attribute obscures the fact that it's an experimental feature. Providing a `nixExperimental` attribute (which people will inevitably start using on their production machines) makes it too easy to enable all experimental features, when you should explicitly opt in to the features that you want to try out.
    
Also, upstream Nix doesn't provide an "enable all experimental features" patch so neither should Nixpkgs.

While I was at it, I made `nixFlakes` into an alias for `nixUnstable`. There no longer is a separate `nixFlakes` package, flake support has been in master for a while.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123898` at 62ee635d run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built successfully:</summary>
  <ul>
    <li>hydra-unstable</li>
    <li>nix-direnv</li>
    <li>nix-update</li>
    <li>nixpkgs-review</li>
  </ul>
</details>

**Review by roberth — APPROVED** [review]
**Regarding the patches**

Even if some users may disagree about some decisions made, this PR reflects the status quo. If you want to improve Nix and speed up its development, contribute to the project.

Making Flakes appear non-experimental is not a decision for downstream to make and it will result in broken expectations.

**Removal of `nixFlakes`**

This is good because it reflects the status quo.

We can have opinions about the approach taken that lead to the status quo, which is only useful for improving the process. This PR is not about process but about the technical reality. Process can be discussed elsewhere.

**Comment by DavHau** [comment]
I'm sorry for the inconvenience this might have caused. My intention was not to undermine upstream, just to improve usability.

Though I have a question for you @roberth.
If a maintainer of chromium requests our `ungoogled-chromium` package to  be removed because it does not reflect the status quo of the upstream project, will we remove `ungoogled-chromium` from our package set?
I guess we would not. It is open source and we're free to create modified packages to fulfill the needs of our community.

I don't want to say we should not remove nixFlakes. I understand that it might cause wrong expectations, as I took an existing attribute and changed its meaning.
But if your general stance is that upstream should be entitled to dictate downstream modifications of their software, I find that questionable.

If some members of the community benefit of a modified package, it should be legitimate to have a discussion about it.

There were concerns about wrong expectation. Those could also have been solved for example by changing the packages description or changing the attribute to something like `unstableNixWithFlakes` to make it very clear that this variation is still unstable.

**Comment by roberth** [comment]
> upstream

Same community,

> `ungoogled-chromium`

other community.

If we can't work with our own, we have a much bigger problem. I don't believe that's the case.

> > Process can be discussed elsewhere.

> it should be legitimate to have a discussion about it.

I did not imply that. You are free to do so, but this thread is not a good platform. Matrix or discourse may be better suited.

> could also have been solved for example by

Let's not repeat the same discussion. The root of the problem is not release management or packaging, but the fact that flakes aren't ready for a non-experimental release. If you want to accelerate the arrival of flakes, you could contribute to the project.

**Comment by gytis-ivaskevicius** [comment]
Can we please have something along the lines of `pkgs.nixExperimentalFlakes`? Just to simplify the life of peeps that do use flakes (which is probably majority of community at this point)

**Comment by balsoft** [comment]
I would love if there was a nixpkgs config option `nixExperimentalOptions` or similar, so that people must still opt-in to using features considered unstable, but don't have to do so with a runtime, and sometimes (on non-NixOS) even stateful Nix config file.

**Pull request merged**
