### PR TITLE
framework-laptop-kmod: 0-unstable-2024-01-02 -> 0-unstable-2024-09-15 

### LINKED ISSUE #342261: Build failure: framework-laptop-kmod with kernel 6.11-rc7 aka testing
### Steps To Reproduce

1. build framework-laptop-kmod with linuxPackages_testing

### Build log

```
error: builder for '/nix/store/i0x14fn2zrbq0c3awcy515n9gi62wgl3-framework-laptop-kmod-0-unstable-2024-01-02.drv' failed with exit code 2;
       last 10 log lines:
       > /build/source/framework_laptop.c:358:19: error: initialization of 'void (*)(struct platform_device *)' from incompatible pointer type 'int (*)(struct platform_device *)' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wincompatible-pointer-types-Werror=incompatible-pointer-types8;;]
       >   358 |         .remove = framework_remove,
       >       |                   ^~~~~~~~~~~~~~~~
       > /build/source/framework_laptop.c:358:19: note: (near initialization for 'framework_driver.<anonymous>.remove')
       > cc1: some warnings being treated as errors
       > make[3]: *** [/nix/store/cbbxx7s9b116h9yrqasmizwn62cl6vz7-linux-6.11-rc7-dev/lib/modules/6.11.0-rc7/source/scripts/Makefile.build:244: /build/source/framework_laptop.o] Error 1
       > make[2]: *** [/nix/store/cbbxx7s9b116h9yrqasmizwn62cl6vz7-linux-6.11-rc7-dev/lib/modules/6.11.0-rc7/source/Makefile:1926: /build/source] Error 2
       > make[1]: *** [/nix/store/cbbxx7s9b116h9yrqasmizwn62cl6vz7-linux-6.11-rc7-dev/lib/modules/6.11.0-rc7/source/Makefile:224: __sub-make] Error 2
       > make[1]: Leaving directory '/nix/store/cbbxx7s9b116h9yrqasmizwn62cl6vz7-linux-6.11-rc7-dev/lib/modules/6.11.0-rc7/build'
       > make: *** [Makefile:12: modules] Error 2
       For full logs, run 'nix log /nix/store/i0x14fn2zrbq0c3awcy515n9gi62wgl3-framework-laptop-kmod-0-unstable-2024-01-02.drv'.
error: 1 dependencies of derivation '/nix/store/0wh4xcbmknsi4nf71wzdls2va8ki39nx-linux-6.11-rc7-modules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fy93qhi4dr2kdyxg7y992ldgkz091y1r-nixos-system-framework-24.05.20240914.8f7492c.drv' failed to build
```

### Additional context

Wanted to try the 6.11 Kernel cause there is a bug fixed in 'cros_ec' module which pings in kde wrong battery state

https://community.frame.work/t/responded-battery-percentage-gets-misreported-as-0-occasionally/38056/9

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.10, NixOS, 24.05 (Uakari), 24.05.20240914.8f7492c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"home-manager-24.05.tar.gz, nixos-24.05, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/store/s8pb2vy9zdjxlc5gr2iwkkm9y5gqr4ph-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by gaykitty**
## Description of changes

https://github.com/DHowett/framework-laptop-kmod/compare/a9e8db9ba2959b75c1fb820ffac8fa189f0f63c3...6164bc3dec24b6bb2806eedd269df6a170bcc930

Closes #342261
Closes #342264

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by pbsds** [comment]
4.19 fails on hydra, the other failures are new

**Comment by aktaboot** [comment]
tested and working on latest,

It seems not to build on _testing kernel

**Comment by SebTM** [comment]
Result of `nixpkgs-review pr 335482` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_19.framework-laptop-kmod</li>
    <li>linuxPackages_4_19_hardened.framework-laptop-kmod (linuxKernel.packages.linux_4_19_hardened.framework-laptop-kmod)</li>
    <li>linuxKernel.packages.linux_5_10.framework-laptop-kmod</li>
    <li>linuxPackages_5_10_hardened.framework-laptop-kmod (linuxKernel.packages.linux_5_10_hardened.framework-laptop-kmod)</li>
    <li>linuxKernel.packages.linux_5_15.framework-laptop-kmod</li>
    <li>linuxPackages_5_15_hardened.framework-laptop-kmod (linuxKernel.packages.linux_5_15_hardened.framework-laptop-kmod)</li>
    <li>linuxKernel.packages.linux_5_4.framework-laptop-kmod</li>
    <li>linuxPackages_5_4_hardened.framework-laptop-kmod (linuxKernel.packages.linux_5_4_hardened.framework-laptop-kmod)</li>
  </ul>
</details>
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_6_1.framework-laptop-kmod</li>
    <li>linuxPackages_latest.framework-laptop-kmod (linuxKernel.packages.linux_6_10.framework-laptop-kmod)</li>
    <li>linuxPackages_6_1_hardened.framework-laptop-kmod (linuxKernel.packages.linux_6_1_hardened.framework-laptop-kmod)</li>
    <li>linuxPackages.framework-laptop-kmod (linuxKernel.packages.linux_6_6.framework-laptop-kmod)</li>
    <li>linuxPackages_hardened.framework-laptop-kmod (linuxPackages_6_6_hardened.framework-laptop-kmod)</li>
    <li>linuxPackages_latest-libre.framework-laptop-kmod (linuxKernel.packages.linux_latest_libre.framework-laptop-kmod)</li>
    <li>linuxPackages-libre.framework-laptop-kmod (linuxKernel.packages.linux_libre.framework-laptop-kmod)</li>
    <li>linuxPackages_lqx.framework-laptop-kmod (linuxKernel.packages.linux_lqx.framework-laptop-kmod)</li>
    <li>linuxPackages_xanmod.framework-laptop-kmod (linuxKernel.packages.linux_xanmod.framework-laptop-kmod)</li>
    <li>linuxPackages_xanmod_latest.framework-laptop-kmod (linuxKernel.packages.linux_xanmod_latest.framework-laptop-kmod ,linuxPackages_xanmod_stable.framework-laptop-kmod)</li>
    <li>linuxPackages_zen.framework-laptop-kmod (linuxKernel.packages.linux_zen.framework-laptop-kmod)</li>
  </ul>
</details>

**Comment by SebTM** [comment]
Not sure about the failures, for only 4.19 or hardened we could have marked it as broken but I guess at least 5.15 needs to be fixed before we can move forward. I'm currently not able to take care of - looking to reply to pings/reviews from time to time if possible.

**Comment by aktaboot** [comment]
hmm, the kmod did build for 5.15 with my configuration, I will look into it

**Comment by aktaboot** [comment]
Okay so https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=b1d288d9c3c5ca28df062214656a59cf7ee370e0
 renames cros_ec_command to cros_ec_cmd that is used by the kmod,

so versions before 6.1 will not build since they use the old function name

**Comment by SebTM** [comment]
> so versions before 6.1 will not build since they use the old function name

I see a few options here:
* Create an issue/MR for the upstream module to handle different kernel-versions differently like sysdig e.g. does (https://github.com/falcosecurity/libs/blob/master/driver/main.c#L1652 - not a C developer not sure if LINUX_VERSION_CODE and KERNEL_VERSION stuff is custom or builtin)
* Create a patch for the latest code that uses the old function and only include the patch based on the kernel-version in nix (should still open an upstream-issue and link it)
* Least favorite option: Create two packages one legacy that stays on the latest v5-kernel compatible version and the main one that gets marked broken for versions below 6.1

**Comment by aktaboot** [comment]
Having looked at it, a lot of changes actually happened to cros_ec in 5.16. it would require some not so minor changes to make the module compatible with 5.15.

but that shouldn't block the update since the module was not compatible with  < 6.1 anw

**Comment by pbsds** [comment]
Then `broken = lib.versionOlder kernel.version "6.1";` sounds like a good addition

**Comment by gaykitty** [comment]
> Then `broken = lib.versionOlder kernel.version "6.1";` sounds like a good addition

I'll add that.

**Review by Scrumplex — APPROVED** [review]
Outputs of framework_privacy

Seems to be working!

**Comment by SebTM** [comment]
Result of `nixpkgs-review pr 335482` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_19.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_4_19_hardened.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_5_10.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_5_10_hardened.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_5_15.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_5_15_hardened.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_5_4.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_5_4_hardened.framework-laptop-kmod</li>
    <li>linuxPackages_4_19_hardened.framework-laptop-kmod</li>
    <li>linuxPackages_5_10_hardened.framework-laptop-kmod</li>
    <li>linuxPackages_5_15_hardened.framework-laptop-kmod</li>
    <li>linuxPackages_5_4_hardened.framework-laptop-kmod</li>
  </ul>
</details>
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_6_1.framework-laptop-kmod</li>
    <li>linuxPackages_latest.framework-laptop-kmod (linuxKernel.packages.linux_6_10.framework-laptop-kmod)</li>
    <li>linuxPackages_6_1_hardened.framework-laptop-kmod (linuxKernel.packages.linux_6_1_hardened.framework-laptop-kmod)</li>
    <li>linuxPackages.framework-laptop-kmod (linuxKernel.packages.linux_6_6.framework-laptop-kmod)</li>
    <li>linuxPackages_hardened.framework-laptop-kmod (linuxPackages_6_6_hardened.framework-laptop-kmod)</li>
    <li>linuxPackages_latest-libre.framework-laptop-kmod (linuxKernel.packages.linux_latest_libre.framework-laptop-kmod)</li>
    <li>linuxPackages-libre.framework-laptop-kmod (linuxKernel.packages.linux_libre.framework-laptop-kmod)</li>
    <li>linuxPackages_lqx.framework-laptop-kmod (linuxKernel.packages.linux_lqx.framework-laptop-kmod)</li>
    <li>linuxPackages_xanmod.framework-laptop-kmod (linuxKernel.packages.linux_xanmod.framework-laptop-kmod)</li>
    <li>linuxPackages_xanmod_latest.framework-laptop-kmod (linuxKernel.packages.linux_xanmod_latest.framework-laptop-kmod ,linuxPackages_xanmod_stable.framework-laptop-kmod)</li>
    <li>linuxPackages_zen.framework-laptop-kmod (linuxKernel.packages.linux_zen.framework-laptop-kmod)</li>
  </ul>
</details>

**Review by SebTM — APPROVED** [review]

**Comment by aktaboot** [comment]
@SebTM 
right, my bad I tested against the wrong version!
incompatibilities were introduced here mostly https://github.com/DHowett/framework-laptop-kmod/commit/6ee08ebb558627863236ff00fab98d25f582ac01

the thing is, it does builld for current kernels but not on 6.11, which soon might get on to our linuxPackages_latest.

I made a small PR upstream to fix that: DHowett/framework-laptop-kmod#24

**Comment by pbsds** [comment]
> I made a small PR upstream to fix that: https://github.com/DHowett/framework-laptop-kmod/pull/24

does this mean that untill that pr is merged, we have a ticking time bomb? This strikes me as a merge-blokker

**Comment by Scrumplex** [comment]
> > I made a small PR upstream to fix that: [DHowett/framework-laptop-kmod#24](https://github.com/DHowett/framework-laptop-kmod/pull/24)
> 
> does this mean that untill that pr is merged, we have a ticking time bomb? This strikes me as a merge-blocker

We could also expedite this patch and apply it for our drv before it gets merged

**Comment by SebTM** [comment]
+1 for adding the up-streamed patch to the derivation to avoid near build failure.

For me it's not clear how we handle the 5.15 breakage - is that fine? Do we need to keep the is state for 5.15-users?

**Comment by pbsds** [comment]
If 5.15 is not supported upstream, we can either do so here as well, or package two versions. I'm leaning towards the former.

**Comment by aktaboot** [comment]
6.11 is very close, I guess we can apply the patch downstream for now to avoid breakage

**Comment by aktaboot** [comment]
actually the patch was merged upstream

**Comment by JohnRTitor** [comment]
Should be backported as kernel upgrades are as well.

**Comment by BeiNacht** [comment]
tested this change with linuxPackages_testing aka 6.11_rc7 on 24.05 and it's working

**Review by Aleksanaa — APPROVED** [review]

**Comment by JohnRTitor** [comment]
Result of `nixpkgs-review pr 335482` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_19.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_4_19_hardened.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_5_10.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_5_10_hardened.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_5_15.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_5_15_hardened.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_5_4.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_5_4_hardened.framework-laptop-kmod</li>
  </ul>
</details>
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_6_1.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_6_10.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_6_11.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_6_1_hardened.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_6_6.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_hardened.framework-laptop-kmod (linuxKernel.packages.linux_6_6_hardened.framework-laptop-kmod)</li>
    <li>linuxKernel.packages.linux_latest_libre.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_libre.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_lqx.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_xanmod.framework-laptop-kmod</li>
    <li>linuxKernel.packages.linux_xanmod_latest.framework-laptop-kmod (linuxKernel.packages.linux_xanmod_stable.framework-laptop-kmod)</li>
    <li>linuxKernel.packages.linux_zen.framework-laptop-kmod</li>
  </ul>
</details>

**Review by JohnRTitor — APPROVED** [review]
Will merge this once eval passes

**Pull request merged**
