### PR TITLE
jetbrains.* 2019.2.3 -> 2019.2.4 (mostly)

### PR DESCRIPTION
**Pull request by kolaente**
###### Motivation for this change

New releases of jetbrains Idea's.

I had an issue with Goland since I upgraded to nixos 19.09, since there is an updated version already, this midght fix it.

I've tested Goland, Clion and Phpstorm, I don't use the others.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @edwtjo @loskutov @miltador @schristo @abaldeau

### CODE REVIEW

**Comment by kolaente** [comment]
I've opened an issue at jetbrains about the Goland issue I was having: https://youtrack.jetbrains.com/issue/GO-8309

**Comment by kolaente** [comment]
Goland was updated to 2019.2.5, I updated.

**Comment by kolaente** [comment]
Looks like we need to wait a bit 
https://twitter.com/GoLandIDE/status/1192558666760826880?s=19

**Comment by c0bw3b** [comment]
Wasn't 2019.2.5 the release that fixed the bug mention on your Twitter link?

**Comment by kolaente** [comment]
@c0bw3b looks like it, yes

**Comment by kolaente** [comment]
@c0bw3b thanks! Should I backport this to 19.09?

**Comment by c0bw3b** [comment]
I'm not sure there is bugfixes "serious" enought to warrant a backport.

Users on stable release can add nixos-unstable as a secondary channel in their user env and install fresher versions of some packages from this channel.

**Pull request merged**
