### PR TITLE
orca-slicer, bambu-studio, prusa-slicer: fix segfault on start

### PR DESCRIPTION
**Pull request by oddlama**
## Description of changes

All of these slicers segfault when started if `__GLX_VENDOR_LIBRARY_NAME` is set. This PR unsets `__GLX_VENDOR_LIBRARY_NAME` in the wrapper to work around the issue. See related comments here:
- #293854
- #328235
- #324086

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by pinpox** [comment]
Result of `nixpkgs-review pr 331624` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>bambu-studio</li>
    <li>bambu-studio.debug</li>
    <li>orca-slicer</li>
    <li>orca-slicer.debug</li>
    <li>prusa-slicer</li>
    <li>prusa-slicer.debug</li>
    <li>super-slicer</li>
    <li>super-slicer-beta</li>
    <li>super-slicer-beta.debug</li>
    <li>super-slicer-latest</li>
    <li>super-slicer-latest.debug</li>
    <li>super-slicer.debug</li>
  </ul>
</details>

**Review by pinpox — APPROVED** [review]

**Comment by oddlama** [comment]
Apparently setting this variable in the first place is not a good idea as @SuperSandro2000 points out here https://github.com/NixOS/nixpkgs/issues/328235#issuecomment-2293105828. Unsetting it for applications that have issues when it (like these three) seems to be a double edged sword; we might prevent a segfault but on the other hand it may be due to a bad system configuration in the first place.

Therefore, I'm not sure whether unsetting it is the right way to go about this. But tracing random segfaults back to that variable is quite hard, especially since this configuration is recommended [by Hyrpland](https://wiki.hyprland.org/Nvidia/#environment-variables) and so I suspect there are many people using it without making the connection that it causes this kind of problem.

Not sure what the best course of action is here, I'd appreciate any input.

**Comment by r-vdp** [comment]
I'll convert this to draft since it seems that you're not sure yet that this is the right solution. Feel free to undraft when you feel that this is ready to be merged.

**Comment by oddlama** [comment]
After thinking about it for a bit I don't think this is the right way forward.

**Pull request closed without merging**
