### PR TITLE
abseil-cpp: use multiple outputs

### PR DESCRIPTION
**Pull request by Luabee**
###### Description of changes
Use multiple outputs for headers and libs on abseil-cpp

Small change with big rebuilds. Sorry about that.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tobim** [comment]
This seems be a worthwhile change:
```fish
> du -d 2 (nix build --print-out-paths .#abseil-cpp) | column -t              
4,411,392  /nix/store/cr5gla9i6bkfpj20na3m2vfaswp5bf2r-abseil-cpp-20230125.3/include/absl
4,411,392  /nix/store/cr5gla9i6bkfpj20na3m2vfaswp5bf2r-abseil-cpp-20230125.3/include
143,360    /nix/store/cr5gla9i6bkfpj20na3m2vfaswp5bf2r-abseil-cpp-20230125.3/lib/cmake
733,184    /nix/store/cr5gla9i6bkfpj20na3m2vfaswp5bf2r-abseil-cpp-20230125.3/lib/pkgconfig
4,321,280  /nix/store/cr5gla9i6bkfpj20na3m2vfaswp5bf2r-abseil-cpp-20230125.3/lib
8,732,672  /nix/store/cr5gla9i6bkfpj20na3m2vfaswp5bf2r-abseil-cpp-20230125.3
```
Can you update it to include `202301` and `202308`?

**Comment by tobim** [comment]
Also, this should target `staging`.

**Comment by Luabee** [comment]
> This seems be a worthwhile change:
> 
> ```fish
> > du -d 2 (nix build --print-out-paths .#abseil-cpp) | column -t              
> 4,411,392  /nix/store/cr5gla9i6bkfpj20na3m2vfaswp5bf2r-abseil-cpp-20230125.3/include/absl
> 4,411,392  /nix/store/cr5gla9i6bkfpj20na3m2vfaswp5bf2r-abseil-cpp-20230125.3/include
> 143,360    /nix/store/cr5gla9i6bkfpj20na3m2vfaswp5bf2r-abseil-cpp-20230125.3/lib/cmake
> 733,184    /nix/store/cr5gla9i6bkfpj20na3m2vfaswp5bf2r-abseil-cpp-20230125.3/lib/pkgconfig
> 4,321,280  /nix/store/cr5gla9i6bkfpj20na3m2vfaswp5bf2r-abseil-cpp-20230125.3/lib
> 8,732,672  /nix/store/cr5gla9i6bkfpj20na3m2vfaswp5bf2r-abseil-cpp-20230125.3
> ```
> 
> Can you update it to include `202301` and `202308`?

Update it to include what now?

**Comment by Luabee** [comment]
> This seems be a worthwhile change:
> 
> ```fish
> > du -d 2 (nix build --print-out-paths .#abseil-cpp) | column -t              
> 4,411,392  /nix/store/cr5gla9i6bkfpj20na3m2vfaswp5bf2r-abseil-cpp-20230125.3/include/absl
> 4,411,392  /nix/store/cr5gla9i6bkfpj20na3m2vfaswp5bf2r-abseil-cpp-20230125.3/include
> 143,360    /nix/store/cr5gla9i6bkfpj20na3m2vfaswp5bf2r-abseil-cpp-20230125.3/lib/cmake
> 733,184    /nix/store/cr5gla9i6bkfpj20na3m2vfaswp5bf2r-abseil-cpp-20230125.3/lib/pkgconfig
> 4,321,280  /nix/store/cr5gla9i6bkfpj20na3m2vfaswp5bf2r-abseil-cpp-20230125.3/lib
> 8,732,672  /nix/store/cr5gla9i6bkfpj20na3m2vfaswp5bf2r-abseil-cpp-20230125.3
> ```
> 
> Can you update it to include `202301` and `202308`?

I only see `202103`, `202111`, and `202206`. Where are the files for those releases?

**Comment by tobim** [comment]
Maybe you need to `git fetch` newer developments from this repo?
I have them:
```
ls pkgs/development/libraries/abseil-cpp/                                                                                                                                                                                      nixpkgs#ansifilter 
202103.nix  202111.nix  202206.nix  202301.nix  202308.nix  cmake-full-dirs.patch
```

**Comment by drupol** [comment]
I'm locking and closing this pull request, because through the rebase you inadvertently requested many maintainers for review, which subscribed them to update notifications, resulting in unnecessary spam inside everyone's inbox. While we can remove their review requests, we sadly cannot unsubscribe anyone.

Please create a new pull request and for the next time remember to set your PR to draft status before rebasing. In draft status, you can preview the list of maintainers that are about to be requested for review, which allows you to sidestep this issue.

**Pull request closed without merging**
