### PR TITLE
nixos/salt: restart on config changes

### PR DESCRIPTION
**Pull request by aneeshusa**
###### Motivation for this change
Restart the Salt minion and master on config changes.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by andir — APPROVED** [review]
It does look reasonable. I am not entirely sure why I am the right person to review. It has been almost 2y since I used salt-stack regulary :/ (cc @Mic92)

**Comment by Mic92** [comment]
@andir Then you have more experience then me. I only read other peoples configuration/documentation.

**Comment by andir** [comment]
@mic92 it looks fine to me thus the +1, I can not test it more then reading it and it reads fine. I guess the only way we could know is if any of us would be using Salt instead of Nix...

@aneeshusa Do you have some very basic configuration on how to test this? Could you write a nixos test so we can verify that it works in the future

**Comment by Mic92** [comment]
Should be fine:

```console
sudo systemctl status salt-minion.service
● salt-minion.service - Salt Minion
   Loaded: loaded (/nix/store/gyibr8na6k3n44wa000c2d0ri6z3482i-unit-salt-minion.service/salt-minion.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-10-30 15:08:12 GMT; 30min ago
 Main PID: 11807 (.salt-minion-wr)
    Tasks: 4 (limit: 4915)
   Memory: 80.3M
   CGroup: /system.slice/salt-minion.service
           ├─11807 /nix/store/2brlr94ahy3a9mvcjy0qbqpv8zrb7b7s-python-2.7.15/bin/python2.7 /nix/store/v9jz3i2jlx72kqz55b5am7a7993bfznq-salt-2018.3.2/bin/.salt-minion-wrapped
           ├─11856 /nix/store/2brlr94ahy3a9mvcjy0qbqpv8zrb7b7s-python-2.7.15/bin/python2.7 /nix/store/v9jz3i2jlx72kqz55b5am7a7993bfznq-salt-2018.3.2/bin/.salt-minion-wrapped
           └─11858 /nix/store/2brlr94ahy3a9mvcjy0qbqpv8zrb7b7s-python-2.7.15/bin/python2.7 /nix/store/v9jz3i2jlx72kqz55b5am7a7993bfznq-salt-2018.3.2/bin/.salt-minion-wrapped

Oct 30 15:36:47 turingmachine salt-minion[11807]: [ERROR   ] DNS lookup or connection check of 'salt' failed.
Oct 30 15:36:47 turingmachine salt-minion[11807]: [ERROR   ] Master hostname: 'salt' not found or not responsive. Retrying in 30 seconds
Oct 30 15:37:17 turingmachine salt-minion[11807]: [ERROR   ] DNS lookup or connection check of 'salt' failed.
Oct 30 15:37:17 turingmachine salt-minion[11807]: [ERROR   ] Master hostname: 'salt' not found or not responsive. Retrying in 30 seconds
Oct 30 15:37:47 turingmachine salt-minion[11807]: [ERROR   ] DNS lookup or connection check of 'salt' failed.
Oct 30 15:37:47 turingmachine salt-minion[11807]: [ERROR   ] Master hostname: 'salt' not found or not responsive. Retrying in 30 seconds
Oct 30 15:38:17 turingmachine salt-minion[11807]: [ERROR   ] DNS lookup or connection check of 'salt' failed.
Oct 30 15:38:17 turingmachine salt-minion[11807]: [ERROR   ] Master hostname: 'salt' not found or not responsive. Retrying in 30 seconds
Oct 30 15:38:47 turingmachine salt-minion[11807]: [ERROR   ] DNS lookup or connection check of 'salt' failed.
Oct 30 15:38:47 turingmachine salt-minion[11807]: [ERROR   ] Master hostname: 'salt' not found or not responsive. Retrying in 30 seconds
```

**Pull request merged**
