### PR TITLE
netdata: Enable cloud support using ACLK-NG

### LINKED ISSUE #91549: netdata: cloud streaming support
**Project description**

Netdata agent plugin 
**Metadata**

* homepage URL: 
* source URL: https://github.com/netdata/netdata
* license: GPL 3.0
* platforms: unix, linux, darwin

We already do have netdata, however it seems to be built without support for the cloud agent that allows it to stream to the cloud or other netdata servers.

### PR DESCRIPTION
**Pull request by leotaku**
###### Motivation for this change

This PR enables Netdata cloud support using ACLK-NG if not on MacOS/Darwin for the Netdata package. This PR is based on #123707, which contains only the update of Netdata to version 1.31.0. 

Would close #91549

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123709` at 717a372c run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>netdata</li>
    <li>tests.trivial</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/tools/system/netdata/default.nix:90:5:
```
   |
90 |     maintainers = [ ];
   |     ^
```
</li>
    <li>warning: unused-argument

Unused argument: `fetchpatch`.
Near pkgs/tools/system/netdata/default.nix:11:3:
```
   |
11 | , fetchpatch
   |   ^
```
</li>
  </ul>
</details>

**Comment by leotaku** [comment]
I have just learned that ACLK-NG, the mechanism we would like to use to enable cloud support is currently broken on MacOS/Darwin. I will edit this PR to conditionally disable the agent-cloud link if we are on Darwin.

**Comment by K900** [comment]
Anything blocking this? I've been running it locally for a bit and it seems to work well.

**Comment by RaghavSood** [comment]
Result of `nixpkgs-review pr 123709` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>netdata</li>
  </ul>
</details>

**Review by RaghavSood — APPROVED** [review]

**Comment by wmertens** [comment]
I'd like to see this backported to 21.05

**Pull request merged**
