### PR TITLE
gnomeExtensions.topicons-plus: enable GNOME 40 compatibility

### PR DESCRIPTION
**Pull request by eduardosm**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123392` at e1b2a44f run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>gnomeExtensions.topicons-plus</li>
    <li>tests.trivial</li>
  </ul>
</details>

**Comment by jonringer** [comment]
cc @NixOS/gnome

**Comment by emanueleperuffo** [comment]
Hi. I'm the maintainer listed in this package, but I haven't been using it since a long time because the author of this extension decided to not support it anymore (source: README in repo).

I can't properly test it or promise to maintain it in the future. Feel free to change the maintainer and put your name there.

The fix looks good to me, but I'm not sure what's the NixOS policy on fetching patches from PRs that haven't been merged to the main repos.

**Comment by eduardosm** [comment]
> I can't properly test it or promise to maintain it in the future. Feel free to change the maintainer and put your name there.

Done, I set myself as maintainer.

**Review by emanueleperuffo — APPROVED** [review]

**Pull request closed without merging**
