### PR TITLE
jetbrains-rust-rover: init at 232.9921.46(EAP)

### PR DESCRIPTION
**Pull request by Followin**
#### Add: [Jetbrains RustRover](https://www.jetbrains.com/rust/)
A new JetBrains IDE for Rust Developers (currently EAP)

Package request: #255001 

##### Note:
Currently requires rust installed via either:
- Rustup (and it doesn't seem to know how to select a default toolchain if one was not present).
- Rust-bin from [rust-overlay](https://github.com/oxalica/rust-overlay) with rust-src extension

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by GenericNerdyUsername — CHANGES_REQUESTED** [review]
A couple of places rust rover needs to be added to:
- `jetbrains/plugins/tests.nix`
- `FRIENDLY_TO_PLUGIN` in `jetbrains/plugins/update_plugins.py` (it maps to `RUST`)

**Comment by GenericNerdyUsername** [comment]
I forgot to mention this in the previous message, but its probably also worth updating the ides

**Comment by Followin** [comment]
> I forgot to mention this in the previous message, but its probably also worth updating the ides

Should I also upgrade the plugins?

**Comment by GenericNerdyUsername** [comment]
The script automatically puts the update in its own commit, and calls the plugin update script

**Comment by Followin** [comment]
Gotcha, thank you.

**Comment by Followin** [comment]
Btw, I'm not sure if we should ship a pinned version of rust with the ide and add it to the PATH so RustRover (probably) finds it.

**Comment by GenericNerdyUsername** [comment]
At least on clion with the rust plugin, getting it to be sensible with the rust toolchain is a bit of a pain. Maybe its possible if we add some config somewhere, but I don't think its worth delaying the merge for that when we can just make a new pr.

**Comment by Followin** [comment]
Yea, they're probably changing the way it interacts with the toolchain soon anyway

**Review by GenericNerdyUsername — APPROVED** [review]

**Comment by GenericNerdyUsername** [comment]
The tests fail with
```
error: output '/nix/store/sc2l88n75cdp5z8z793vqsw5c2pg4jjk-rust-rover-with-plugins-2023.2' is not allowed to refer to the following paths:
         /nix/store/lfi2c75d0pvar3c13jdi5sxy1nl3ycpn-rust-rover-2023.2
```

**Comment by Followin** [comment]
Yup, found the way to run the required tests and changed patching of the whole plugins folder to patching the linker of required rust plugin shipped with the RustRover. It works and tests pass but I'm not sure it's the way to go about it though...

**Review by GenericNerdyUsername — APPROVED** [review]
LGTM

**Comment by GenericNerdyUsername** [comment]
> The tests fail with
> 
> ```
> error: output '/nix/store/sc2l88n75cdp5z8z793vqsw5c2pg4jjk-rust-rover-with-plugins-2023.2' is not allowed to refer to the following paths:
>          /nix/store/lfi2c75d0pvar3c13jdi5sxy1nl3ycpn-rust-rover-2023.2
> ```

turns out this is an error with plugin system/original build system and the ides have had incorrectly linked binaries for a while

**Comment by Followin** [comment]
Is that a different PR kind of issue or should it be addressed here before merging?

**Comment by GenericNerdyUsername** [comment]
I think thats for a new pr, it might require modifying `linux.nix`

**Review by leona-ya — APPROVED** [review]

**Review by tymscar — APPROVED** [review]

**Pull request merged**
