### PR TITLE
python3Packages.scikit-fuzzy: init at unstable-2020-10-03

### PR DESCRIPTION
**Pull request by bcdarwin**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [NA] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [NA] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
I'm not the biggest fan of having many downstream packages of scikit. They usually release subtle breaking changes. The codebase surface is massive. And they've caused me several hours of looking into why certain bumps are breaking builds/tests.

**Comment by bcdarwin** [comment]
I would like to add https://github.com/jcreinhold/intensity-normalization, which needs scikit-fuzzy, to all-packages.nix, but if more scikit packages aren't desirable then I can perhaps add these to an overlay instead ...?  On the other hand, this package is fairly small, has few dependencies, and the tests run in a few seconds.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 100090` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python37Packages.scikit-fuzzy</li>
    <li>python38Packages.scikit-fuzzy</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 100090` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python37Packages.scikit-fuzzy</li>
    <li>python38Packages.scikit-fuzzy</li>
  </ul>
</details>

**Pull request merged**
