### PR TITLE
chrony: 4.5 -> 4.6.1; move to by-name

### PR DESCRIPTION
**Pull request by vifino**
https://chrony-project.org/news.html

Now runs the testsuite sans one broken test.
Enabled it for Darwin and removed OpenBSD, where it never ran.

Moved to by-name and ran nixfmt.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by fpletz — COMMENTED** [review]
Code changes look good but Darwin fails on ofborg.

**Review by GetPsyched — COMMENTED** [review]
These changes should be broken down to multiple commits, in no particular order:
- Version bump
- Running nixfmt
- Refactoring the derivation
- Adding yourself as a maintainer
- Moving the package to by-name

**Comment by vifino** [comment]
> Code changes look good but Darwin fails on ofborg.

It works on aarch64-darwin, but not x86_64-darwin.
`sys/timex.h` is missing, it should be there on after macOS 10.13, guessing the SDKs are too old?

Do you know how to change them to something newer if I'm not explicitly using any framework?

**Review by fpletz — CHANGES_REQUESTED** [review]
@GetPsyched's review is valid. Though all the refactoring that doesn't change any outputs like nixfmt and the by-name move can be done in one commit.

**Comment by vifino** [comment]
So, essentially, I have to do all the work from scratch?
Don't the commits usually get squashed on merge anyway?
What's the point?

**Comment by infinisil** [comment]
@vifino The convention is to not squash, but I think it's good like this and I appreciate the effort to split it into independent commits! This notably aligns with the [commit conventions](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions):

> Create a commit for each logical unit.

There's also this:

> If you have commits `pkg-name: oh, forgot to insert whitespace`: squash commits in this case. Use `git rebase -i`.

But this doesn't apply here, and I'm pretty sure there's no other guidelines that would imply having to squash the commits in this PR more, so I'd like to ask @fpletz to reconsider blocking on this. If there's a good reason to squash more in certain cases, we should discuss it separately and then amend the guidelines so we can refer to it, as suggested in [C4](https://rfc.zeromq.org/spec/42/#24-development-process) (search for "value judgments").

**Comment by infinisil** [comment]
Independently of the above though, we do have a new codeowner validator CI check, which is now detecting a problem with this PR:

```
    [err] line 229: "/pkgs/tools/networking/chrony" does not match any files in repository
```

You'll need to change this line to fix that: https://github.com/NixOS/nixpkgs/blob/bf3905af38e80e6b804ee9f686a98783e621de7c/.github/CODEOWNERS#L229

This would fit well into the first commit (you can do `git rebase -i` to amend a change to the first commit, see [here](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_squashing) for a tutorial if you don't know about it already)

**Comment by vifino** [comment]
Hey @infinisil, thank you for elaborating on this!

Just so we're on the same page:
The initial issue with the PR was that I committed the move, reformat, update and fixup for darwin in a [single commit](https://github.com/NixOS/nixpkgs/commit/10c31c25be8d8e77c5ffaa2641c10836c136373d).
To me, that seemed OK as I believe to have seen it done this way in the past.
My assumption of "logical unit" is a lot more coarse, think split by package/module/tests/docs.
It is not very defined and probably differs a lot, developer to developer.

My annoyance with the request to split it into multiple (fine-detailed) commits was that I essentially needed to redo the work in it's entirety for - to me - questionable benefits, since I had (incorrectly) assumed that it would be squashed - not rebased - just judging from a quick glance at the nixpkgs commit history.

In my personal experience, reviewing the changes requires to look at the entire diff - if not the whole file/derivation - as skipping a "run the formatter" commit in the review process could yield.. *bad* outcomes.
Hence I was a bit upset at the request, since doing that just for the review of (to me) trivial changes seemed a bit pointless, as the resulting file looks very readable.

@fpletz was actually chiming in to tell me that I don't need to as many individual commits as initially requested, trying to save me work, not squashing down fine-grained commits.

However, after I resigned to the fact that the only way I can get this approved is by redoing all the changes, I followed my interpretation of the initial demands as best as I could, yielding the current state (which took me about an hour).

**Comment by vifino** [comment]
> 
> You'll need to change this line to fix that:
> 
> https://github.com/NixOS/nixpkgs/blob/bf3905af38e80e6b804ee9f686a98783e621de7c/.github/CODEOWNERS#L229
> 

I assume I'd only change the path, correct?

**Comment by infinisil** [comment]
@vifino Ah I see, thanks for the clarification, and sorry for the misinterpretation, @fpletz! 

I do think there is a case to be made for granular commits to a degree, not just for the sake reviews, but also history, as it makes reverting, bisecting and blaming nicer (could use [`.git-blame-ignore-revs`](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view)). So I think it's best to get into the habit of committing often, because it's easy to squash multiple commits together. Going the other way is hard, so I wouldn't want to impose that if it's not too beneficial.

Sounds like we need to clarify the guidelines on this to hint at the right balance :)

**Comment by infinisil** [comment]
> > You'll need to change this line to fix that:
> > https://github.com/NixOS/nixpkgs/blob/bf3905af38e80e6b804ee9f686a98783e621de7c/.github/CODEOWNERS#L229
> 
> I assume I'd only change the path, correct?

Yup!

**Comment by vifino** [comment]
Updated the `ci/OWNERS` file now, following #347610!

**Comment by fpletz** [comment]
> @fpletz was actually chiming in to tell me that I don't need to as many individual commits as initially requested, trying to save me work, not squashing down fine-grained commits.

Yup, that was my intention. Some degree of separation in the commits does makes sense but we don't have to be too pedantic about it. Generally, I don't like nitpicking in PRs and tend to just force push my nitpicks rather than put the burden on the PR author to fix minor issues.

My personal interpretation of the rules is that we should make it easy to revert or backport something that later turns out to break something. Changes like formatting or the by-name move most probably won't get reverted so that's fine. The version bump might if we find issues with the release that can't be trivially fixed.

Anyway, thanks everyone for chiming in here and @vifino for separating the commits. :tada:

**Review by fpletz — APPROVED** [review]

**Pull request merged**
