### PR TITLE
OracleJDK: use fetchurl instead of requireFile

### PR DESCRIPTION
**Pull request by ts468**
So far the change only applies to JDK 7 and 8.
Also, 'fetchurl' is adapted slightly.

### CODE REVIEW

**Comment by ts468** [comment]
Please review changes to "pkgs/build-support/fetchurl/builder.sh".

**Comment by vcunat** [comment]
I'm no lawyer, but I think that bypassing the license agreement might not be a legally clean way (it might also depend on jurisdiction, I guess). Maybe with something like the ML-suggested ``allowLicenses = [ pkgs.licenses.oracle-jdk-EULA ];``... but I can't really say either way.

**Comment by edolstra** [comment]
Apart from the legal issue, I don't really like `curlOpts` because it breaks abstraction (it exposes the fact that fetchurl uses curl, which might change one day). It would be better if fetchurl took an argument containing a list/set of cookies, which would be curl-independent.

**Comment by jagajaga** [comment]
I really don't like the idea of automated installing of oraclejdk due to licenses.

**Comment by ts468** [comment]
@edolstra, thanks for the hint on curlOpts, I'll change that.

But before I go ahead and make the changes, I would like to have a decision on the licensing issue and on whether to download OracleJDK automatically, or not.

Of course I would be strongly in favor of it!

In my opinion NixOS would only distribute a build tool, and I don't see a problem in that. At the moment one has to set "allowUnfree=true;", so that the user has to take a conscious decision on whether to use software that requires an EULA.
It might be worth thinking about a general framework where the user can accept individual licenses, like suggested by @nbp on the mailing list.
But for now, I would just want to replace "requireFile" with "fetchurl".

**Comment by edolstra** [comment]
For reference, Gentoo also requires manual downloading: http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/dev-java/oracle-jdk-bin/oracle-jdk-bin-1.7.0.76.ebuild?view=markup

**Comment by copumpkin** [comment]
The question is what our goal is with "manual" activity:

1. Make it more painful for people to use proprietary software, because we don't think they should
2. Make it harder for people to accidentally use proprietary software without being aware of its license terms
3. "Cover our asses", and make sure that nobody could ever claim that nixpkgs is violating or aiding the violation of licenses

With 1, I think we're already pretty good at that ;)
With 2, I think it would be sufficient to have a simple autodownloader with a question-asking mechanism (either interactive or configuration) to ensure that people are aware
For 3, we can either go with 1 (easy but unpleasant), or 2 with additional measures to present actual licenses to users.

**Comment by edolstra** [comment]
In this case it's mostly 3). Oracle put that license page up for a reason - they're likely not happy with people providing automated ways around it.

Also, in the case of Oracle JDK, we don't have to go out of our way to make it easy to install, because there is a fine free alternative for most people (OpenJDK).

**Comment by copumpkin** [comment]
Homebrew does it the shady way! https://github.com/caskroom/homebrew-cask/blob/master/Casks/java.rb

**Comment by ts468** [comment]
So now, as there are distributions with automated downloading and distributions without, what should be policy for NixOS? Who could be asked for legal advice, FSFE?

On the technical side, there is already "config.whitelistedLicenses" in "pkgs/stdenv/generic/default.nix", could that be used to ask the user to accept an EULA? Or, should there be a more explicit option like "config.acceptedEULAs"?
Also, in nixos, there could be a module with descriptions that contain links to the actual EULAs.

For me, it would be very helpful if a general policy for NixOS could be agreed on.
I know of a few more packages that have similar EULAs, and I wanted to integrate those as well.

Concerning OracleJDK in particular, there is just a lot of software, especially enterprise grade software, that require OracleJDK, not OpenJDK. I don't know about the real difference between the two versions, but if possible, I would like to have an automated download for OracleJDK as well.

**Comment by iElectric** [comment]
cc @silverhook

**Comment by ts468** [comment]
What should be done about OracleJDK? Any new thoughts?

**Comment by ts468** [comment]
Concerning licenses and EULAs in general, I just wonder how the licensing issue is handled for, e.g., printer or scanner drivers from HP, Samsung and so on? They seem to contain parts that are under a restrictive license, similar to OracleJDK, but are packed with automatic downloads in nixpkgs.
What do you think? Should those packages be changed? Or, can we change OracleJDK to have an automatic download as well?

**Comment by nathan-gs** [comment]
@ts468 the difference between Oracle JDK vs OpenJDK from version 7 onwards is that Oracle contains a few fonts. 
See: 
https://technfun.wordpress.com/2013/01/18/last-difference-openjdk-oracle-jdk/

Even Oracle announced that OpenJDK is the reference implementation. See https://blogs.oracle.com/henrik/entry/moving_to_openjdk_as_the

**Comment by vcunat** [comment]
I'll close. Bypassing the licenses haven't met with welcome.

**Comment by copumpkin** [comment]
:frowning:

**Comment by ts468** [comment]
@nathan-gs @vcunat thanks for reminding me of that stalled PR!
However, as I have applications, mainly commercial closed source software, that run only with oraclejdk and not with openjdk, I created a follow up PR at #9234.

**Pull request closed without merging**
