### PR TITLE
GNOME updates 2024-12-19

### PR DESCRIPTION
**Pull request by bobby285271**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc @jtojnar

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg build nautilus localsearch gucharmap gnome-terminal gnome-contacts gnome-calculator aisleriot

**Comment by lucasew** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 366551`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 46 packages built:</summary>
  <ul>
    <li>aisleriot</li>
    <li>bluefish</li>
    <li>cinnamon-gsettings-overrides</li>
    <li>collision</li>
    <li>dropbox-cli</li>
    <li>dropbox-cli.nautilusExtension</li>
    <li>eiciel</li>
    <li>eiciel.nautilusExtension</li>
    <li>file-roller</li>
    <li>gnome-applets</li>
    <li>gnome-calculator</li>
    <li>gnome-contacts</li>
    <li>gnome-control-center</li>
    <li>gnome-control-center.debug</li>
    <li>gnome-photos</li>
    <li>gnome-photos.installedTests</li>
    <li>gnome-terminal</li>
    <li>gnomeExtensions.gtk4-desktop-icons-ng-ding</li>
    <li>gucharmap</li>
    <li>gucharmap.dev</li>
    <li>gucharmap.devdoc</li>
    <li>gucharmap.lib</li>
    <li>insync-nautilus</li>
    <li>localsearch</li>
    <li>mate.mate-applets</li>
    <li>mate.mate-panel-with-applets</li>
    <li>mate.mate-tweak</li>
    <li>mate.mate-tweak.dist</li>
    <li>nautilus</li>
    <li>nautilus-open-any-terminal</li>
    <li>nautilus-open-any-terminal.dist</li>
    <li>nautilus-open-in-blackbox</li>
    <li>nautilus-python</li>
    <li>nautilus-python.dev</li>
    <li>nautilus-python.devdoc</li>
    <li>nautilus-python.doc</li>
    <li>nautilus.dev</li>
    <li>nautilus.devdoc</li>
    <li>nemo-fileroller</li>
    <li>nemo-with-extensions</li>
    <li>pantheon.file-roller-contract</li>
    <li>papers</li>
    <li>papers.dev</li>
    <li>papers.devdoc</li>
    <li>phosh</li>
    <li>phosh-mobile-settings</li>
  </ul>
</details>

**Comment by lucasew** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 366551`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 46 packages built:</summary>
  <ul>
    <li>aisleriot</li>
    <li>bluefish</li>
    <li>cinnamon-gsettings-overrides</li>
    <li>collision</li>
    <li>dropbox-cli</li>
    <li>dropbox-cli.nautilusExtension</li>
    <li>eiciel</li>
    <li>eiciel.nautilusExtension</li>
    <li>file-roller</li>
    <li>gnome-applets</li>
    <li>gnome-calculator</li>
    <li>gnome-contacts</li>
    <li>gnome-control-center</li>
    <li>gnome-control-center.debug</li>
    <li>gnome-photos</li>
    <li>gnome-photos.installedTests</li>
    <li>gnome-terminal</li>
    <li>gnomeExtensions.gtk4-desktop-icons-ng-ding</li>
    <li>gucharmap</li>
    <li>gucharmap.dev</li>
    <li>gucharmap.devdoc</li>
    <li>gucharmap.lib</li>
    <li>insync-nautilus</li>
    <li>localsearch</li>
    <li>mate.mate-applets</li>
    <li>mate.mate-panel-with-applets</li>
    <li>mate.mate-tweak</li>
    <li>mate.mate-tweak.dist</li>
    <li>nautilus</li>
    <li>nautilus-open-any-terminal</li>
    <li>nautilus-open-any-terminal.dist</li>
    <li>nautilus-open-in-blackbox</li>
    <li>nautilus-python</li>
    <li>nautilus-python.dev</li>
    <li>nautilus-python.devdoc</li>
    <li>nautilus-python.doc</li>
    <li>nautilus.dev</li>
    <li>nautilus.devdoc</li>
    <li>nemo-fileroller</li>
    <li>nemo-with-extensions</li>
    <li>pantheon.file-roller-contract</li>
    <li>papers</li>
    <li>papers.dev</li>
    <li>papers.devdoc</li>
    <li>phosh</li>
    <li>phosh-mobile-settings</li>
  </ul>
</details>

**Comment by lucasew** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 366551`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 46 packages built:</summary>
  <ul>
    <li>aisleriot</li>
    <li>bluefish</li>
    <li>cinnamon-gsettings-overrides</li>
    <li>collision</li>
    <li>dropbox-cli</li>
    <li>dropbox-cli.nautilusExtension</li>
    <li>eiciel</li>
    <li>eiciel.nautilusExtension</li>
    <li>file-roller</li>
    <li>gnome-applets</li>
    <li>gnome-calculator</li>
    <li>gnome-contacts</li>
    <li>gnome-control-center</li>
    <li>gnome-control-center.debug</li>
    <li>gnome-photos</li>
    <li>gnome-photos.installedTests</li>
    <li>gnome-terminal</li>
    <li>gnomeExtensions.gtk4-desktop-icons-ng-ding</li>
    <li>gucharmap</li>
    <li>gucharmap.dev</li>
    <li>gucharmap.devdoc</li>
    <li>gucharmap.lib</li>
    <li>insync-nautilus</li>
    <li>localsearch</li>
    <li>mate.mate-applets</li>
    <li>mate.mate-panel-with-applets</li>
    <li>mate.mate-tweak</li>
    <li>mate.mate-tweak.dist</li>
    <li>nautilus</li>
    <li>nautilus-open-any-terminal</li>
    <li>nautilus-open-any-terminal.dist</li>
    <li>nautilus-open-in-blackbox</li>
    <li>nautilus-python</li>
    <li>nautilus-python.dev</li>
    <li>nautilus-python.devdoc</li>
    <li>nautilus-python.doc</li>
    <li>nautilus.dev</li>
    <li>nautilus.devdoc</li>
    <li>nemo-fileroller</li>
    <li>nemo-with-extensions</li>
    <li>pantheon.file-roller-contract</li>
    <li>papers</li>
    <li>papers.dev</li>
    <li>papers.devdoc</li>
    <li>phosh</li>
    <li>phosh-mobile-settings</li>
  </ul>
</details>

**Comment by lucasew** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 366551`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 46 packages built:</summary>
  <ul>
    <li>aisleriot</li>
    <li>bluefish</li>
    <li>cinnamon-gsettings-overrides</li>
    <li>collision</li>
    <li>dropbox-cli</li>
    <li>dropbox-cli.nautilusExtension</li>
    <li>eiciel</li>
    <li>eiciel.nautilusExtension</li>
    <li>file-roller</li>
    <li>gnome-applets</li>
    <li>gnome-calculator</li>
    <li>gnome-contacts</li>
    <li>gnome-control-center</li>
    <li>gnome-control-center.debug</li>
    <li>gnome-photos</li>
    <li>gnome-photos.installedTests</li>
    <li>gnome-terminal</li>
    <li>gnomeExtensions.gtk4-desktop-icons-ng-ding</li>
    <li>gucharmap</li>
    <li>gucharmap.dev</li>
    <li>gucharmap.devdoc</li>
    <li>gucharmap.lib</li>
    <li>insync-nautilus</li>
    <li>localsearch</li>
    <li>mate.mate-applets</li>
    <li>mate.mate-panel-with-applets</li>
    <li>mate.mate-tweak</li>
    <li>mate.mate-tweak.dist</li>
    <li>nautilus</li>
    <li>nautilus-open-any-terminal</li>
    <li>nautilus-open-any-terminal.dist</li>
    <li>nautilus-open-in-blackbox</li>
    <li>nautilus-python</li>
    <li>nautilus-python.dev</li>
    <li>nautilus-python.devdoc</li>
    <li>nautilus-python.doc</li>
    <li>nautilus.dev</li>
    <li>nautilus.devdoc</li>
    <li>nemo-fileroller</li>
    <li>nemo-with-extensions</li>
    <li>pantheon.file-roller-contract</li>
    <li>papers</li>
    <li>papers.dev</li>
    <li>papers.devdoc</li>
    <li>phosh</li>
    <li>phosh-mobile-settings</li>
  </ul>
</details>

**Comment by lucasewd** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 366551`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 46 packages built:</summary>
  <ul>
    <li>aisleriot</li>
    <li>bluefish</li>
    <li>cinnamon-gsettings-overrides</li>
    <li>collision</li>
    <li>dropbox-cli</li>
    <li>dropbox-cli.nautilusExtension</li>
    <li>eiciel</li>
    <li>eiciel.nautilusExtension</li>
    <li>file-roller</li>
    <li>gnome-applets</li>
    <li>gnome-calculator</li>
    <li>gnome-contacts</li>
    <li>gnome-control-center</li>
    <li>gnome-control-center.debug</li>
    <li>gnome-photos</li>
    <li>gnome-photos.installedTests</li>
    <li>gnome-terminal</li>
    <li>gnomeExtensions.gtk4-desktop-icons-ng-ding</li>
    <li>gucharmap</li>
    <li>gucharmap.dev</li>
    <li>gucharmap.devdoc</li>
    <li>gucharmap.lib</li>
    <li>insync-nautilus</li>
    <li>localsearch</li>
    <li>mate.mate-applets</li>
    <li>mate.mate-panel-with-applets</li>
    <li>mate.mate-tweak</li>
    <li>mate.mate-tweak.dist</li>
    <li>nautilus</li>
    <li>nautilus-open-any-terminal</li>
    <li>nautilus-open-any-terminal.dist</li>
    <li>nautilus-open-in-blackbox</li>
    <li>nautilus-python</li>
    <li>nautilus-python.dev</li>
    <li>nautilus-python.devdoc</li>
    <li>nautilus-python.doc</li>
    <li>nautilus.dev</li>
    <li>nautilus.devdoc</li>
    <li>nemo-fileroller</li>
    <li>nemo-with-extensions</li>
    <li>pantheon.file-roller-contract</li>
    <li>papers</li>
    <li>papers.dev</li>
    <li>papers.devdoc</li>
    <li>phosh</li>
    <li>phosh-mobile-settings</li>
  </ul>
</details>

**Comment by lucasew** [comment]
Sorry for the nixpkgs-review messages. We are cooking an automation to run nixpkgs-review using GitHub actions. This is a test.

BTW this is the workflow run https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12445968172

image

**Review by jtojnar — APPROVED** [review]
Thanks, upstream changes look okay.

**Pull request merged**
