### PR TITLE
gnutls: Fix failing patch for Aarch32

### PR DESCRIPTION
**Pull request by matthewmazzanti**
###### Motivation for this change

A patch for tests that fail on arm has been upstreamed, and is no longer
needed.

###### Things done

I have gated this behind a lib.versionOlder to allow the build.

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ajs124** [comment]
Why add the versionOlder and not just drop the patch?

**Comment by matthewmazzanti** [comment]
In the same file theres a "versionAtLeast" as well, so I wanted to keep with the flow and maintain the ability to change versions if needed. If it would be more appropriate to just drop the patch, let me know.

**Comment by ajs124** [comment]
We only tend to do that for packages with a common infrastructure that multiple versions are built from. Apparently this used to be the case for gnutls until 33e7d721b6400aefacf1e138380836accc376229/#58611.

IMHO having conditions which only ever evaluate to the same result is an antipattern and should be avoided, but if it is to be expected that a `generic.nix` and multiple different gnutls versions will return, it might make sense to keep them around anyways.

**Comment by matthewmazzanti** [comment]
Well I can remove the patch entirely, thats no problem. Do you want me to remove the other version dependent reference as well, or leave it in?

**Comment by matthewmazzanti** [comment]
Removed the patch.

**Comment by SuperSandro2000** [comment]
Can we target master here?

**Comment by matthewmazzanti** [comment]
Tried to change the base directly and it looked nasty. Let me do a cherry pick and open a new PR.

**Comment by matthewmazzanti** [comment]
New pr here: https://github.com/NixOS/nixpkgs/pull/117279

**Pull request closed without merging**
