### PR TITLE
dovecot_fts_xapian: 1.4.11 -> 1.4.14

### PR DESCRIPTION
**Pull request by mvnetbiz**
###### Motivation for this change
Update Dovecot fts-xapian plugin to make compatible with newest Dovecot. (old version crashes)

###### Things done
Update dovecot_fts_xapian to 1.4.14

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mvnetbiz** [comment]
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>dovecot_fts_xapian</li>
  </ul>
</details>

**Comment by symphorien** [comment]
@SuperSandro2000 please don't merge so fast. Please leave at least a few days for maintainers to test. This bump in particular seems fine, but the next one is not in a subtle way: https://github.com/grosjo/fts-xapian/issues/103

**Comment by SuperSandro2000** [comment]
You only reacted to this PR after 6 days which is already a couple of days. I am not sure how long I am supposed to wait and if maintainers will react at all even after weeks.

**Comment by mvnetbiz** [comment]
Dovecot wouldn't even start prior to this so I don't think it was made worse at least, unless it deleted someone's emails or something.

**Comment by symphorien** [comment]
> You only reacted to this PR after 6 days which is already a couple of days. I am not sure how long I am supposed to wait and if maintainers will react at all even after weeks.

Surely more than a *single hour*, please.

**Comment by lionello** [comment]
Could this be considered for backporting to 21.11? The one in 21.11 has the out-of-memory problems.

**Comment by symphorien** [comment]
Unless I'm mistaken, this commit is included in 21.11.

**Comment by lionello** [comment]
@symphorien You're right! I must have looked in the wrong branch. Awesome.

**Pull request merged**
