### PR TITLE
forgejo: 9.0.2 -> 9.0.3, forgejo-lts: 7.0.11 -> 7.0.12

### PR DESCRIPTION
**Pull request by emilylange**
- `forgejo`
	- https://codeberg.org/forgejo/forgejo/releases/tag/v9.0.3
	- https://codeberg.org/forgejo/forgejo/src/commit/403a81bdb50db190fb1374396d4768d753e0f3cd/release-notes-published/9.0.3.md
	- diff: https://codeberg.org/forgejo/forgejo/compare/v9.0.2...v9.0.3
- `forgejo-lts`
	- https://codeberg.org/forgejo/forgejo/releases/tag/v7.0.12
	- https://codeberg.org/forgejo/forgejo/src/commit/403a81bdb50db190fb1374396d4768d753e0f3cd/release-notes-published/7.0.12.md
	- diff: https://codeberg.org/forgejo/forgejo/compare/v7.0.11...v7.0.12

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by evanrichter — APPROVED** [review]
I upgraded from 7.0.11 to 7.0.12 with these hashes and everything seems to work great still

**Comment by NyCodeGHG** [comment]
tests pass on x86_64-linux
```
# nix-build -A forgejo.tests -A forgejo-lts.tests
/nix/store/3gkbdf52ar6622lfp5d80xsnjy5wv97j-vm-test-run-forgejo-mysql
/nix/store/wrwvmjnmy8n2cbb06ffy6x0ggqi45sy8-vm-test-run-forgejo-postgres
/nix/store/i9fdaxmfk8i190m78rzpnqdf60gqiv4d-vm-test-run-forgejo-sqlite3
/nix/store/2pfjpzmmx4zmjpqai9b9bwwlia2s8fh1-vm-test-run-forgejo-mysql
/nix/store/xczhbr3qx8kn81i9kvlwqry7s7jkd0i2-vm-test-run-forgejo-postgres
/nix/store/wkwmq37k14w5rr33sam1hagprpcadlj0-vm-test-run-forgejo-sqlite3
```

**Review by NyCodeGHG — APPROVED** [review]

**Comment by adamcstephens** [comment]
we'll use the borg while it exists :)

@ofborg build forgejo.passthru.tests forgejo-lts.passthru.tests

**Comment by adamcstephens** [comment]
Since this is a security fix we'll want to update the 7.x on 24.05

**Comment by emilylange** [comment]
> Since this is a security fix we'll want to update the 7.x on 24.05

Manual backport in #364761

**Pull request merged**
