### PR TITLE
erlang_26: init at 26.0

### PR DESCRIPTION
**Pull request by shanesveller**
###### Description of changes

Mechanical duplication of OTP 25, so I'm expecting small changes to be requested during review, i.e. perhaps around carrying over `buildPackages.autoconf269`.

I consciously omitted changing `latestVersion` in `beam-packages.nix` but if it's desirable to include after all, that's no problem.

https://www.erlang.org/blog/otp-26-highlights/
https://www.erlang.org/patches/otp-26.0
https://www.erlang.org/doc/apps/erts/notes.html#erts-14.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by shanesveller** [comment]
The four `beam.interpreters` outputs build successfully for me on M2 Darwin and x86_64 NixOS, but nothing is picked up during `nixpkgs-review` from either platform.

**Comment by DianaOlympos** [comment]
Or maybe not. Ping @NixOS/beam what am i missing?

**Comment by happysalada** [comment]
correct next to line 103, if you don't add the erlang_26 there, it doesn't get picked up as a new package.
By default beam interpreters aren't build IIRC.

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 232278` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by happysalada** [comment]
very weird, let's merge as is since the changes are correct, and when we find out what is missing then we can add this later.

**Pull request merged**
