### PR TITLE
mesa: 22.0.4 -> 22.1.1

### PR DESCRIPTION
**Pull request by primeos**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
Sounds like NixOS 22.05 will stay on mesa 22.0.

**Comment by alapshin** [comment]
This is probably not a right place for this question so my apologies in advance.

In the past one could update mesa drivers without full system rebuild using `driDrivers` attribute like this
https://github.com/NixOS/nixpkgs/issues/165636#issuecomment-1079649286

PR https://github.com/NixOS/nixpkgs/pull/161085 removed this attribute and this approach no longer works. Is there some way to achieve similar result? Or this is something that was never supported/recommended in the first place and was a hack?

**Comment by vcunat** [comment]
AFAIK you can replace mesa the same way.  And I don't see that change as really related... upstream just dropped one kind of drivers.

**Comment by primeos** [comment]
Yes, looking at https://github.com/NixOS/nixpkgs/issues/165636#issuecomment-1079216766 that override was only required to avoid `meson.build:180:2: ERROR: Problem encountered: Mesa's main branch no longer has any "classic" drivers, use the "amber" branch instead.` and this is resolved since https://github.com/NixOS/nixpkgs/pull/161085.
https://nixos.wiki/wiki/OpenGL#Testing_Mesa_updates might also be of interest to you (but the existing approach might be preferable).

**Comment by primeos** [comment]
@ofborg test tinywl sway

**Comment by vcunat** [comment]
The build regressed on aarch64-darwin, most likely due to this update: https://hydra.nixos.org/build/180201006

**Comment by vcunat** [comment]
Same error on x86_64-darwin as well: https://hydra.nixos.org/build/180092035

**Comment by vcunat** [comment]
Upstream: https://gitlab.freedesktop.org/mesa/mesa/-/issues/6519

**Pull request merged**
