### PR TITLE
cargo-spellcheck: fix build on darwin

### PR DESCRIPTION
**Pull request by JohnTitor**
###### Motivation for this change

#144627 (here's the failure log: https://hydra.nixos.org/build/157268985/nixlog/1)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by newAM — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 144692` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>cargo-spellcheck</li>
  </ul>
</details>

**Comment by siraben** [comment]
```
$ nix log /nix/store/0g11hvhr4jfgddwv7pdy3vdy7q999wz8-cargo-spellcheck-0.8.14.drv | ix
http://ix.io/3E49
```

**Comment by JohnTitor** [comment]
@siraben Thanks for checking the build! I'm, however, not sure why `SIGABRT` happened on the `maplit` build, any idea?

**Comment by risicle** [comment]
Built successfully for me on macos 10.15

**Review by thiagokokada — APPROVED** [review]
Result of `nixpkgs-review pr 144692` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>cargo-spellcheck</li>
  </ul>
</details>

**Comment by thiagokokada** [comment]
Considering that many people builds the package succesfully on `x86_64-darwin`, I assume that something is wrong with @siraben system (sandbox enabled, corrupted `/nix/store`, faulty hardware, etc).

I will go and merge it them.

**Comment by siraben** [comment]
Did anyone build it on macOS 12.0.1? I have sandboxing disabled as well

**Comment by thiagokokada** [comment]
> Did anyone build it on macOS 12.0.1? I have sandboxing disabled as well

Huh... This maybe the cause. However, AFAIK, more recent macOS versions (11.0, 12.0) still have some more deep problems in nixpkgs (for example, we use a very old version of Clang and Xcode).

Still, again AFAIK, as long Hydra builds successfully you can use the binaries from the cache even if you're using a newer macOS version. Since Hydra should be using an older version of macOS, I think it is fine.

**Pull request merged**
