### PR TITLE
julia_110: 1.10.2 -> 1.10.3

### PR DESCRIPTION
**Pull request by NickCao**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by getchoo — COMMENTED** [review]
it seems some of the tests may be flaky

Result of `nixpkgs-review pr 308070` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>cantor (libsForQt5.cantor ,plasma5Packages.cantor)</li>
    <li>julia (julia-stable ,julia_110)</li>
    <li>julia-bin (julia-stable-bin ,julia_110-bin)</li>
    <li>labplot</li>
  </ul>
</details>

```
error: builder for '/nix/store/5qkvlkq47lnrg9m18cfmq3yck41jhhp6-julia-bin-1.10.3.drv' failed with exit code 1;
       last 10 log lines:
       > Error in testset file:
       > Test Failed at /nix/store/qmbxymr953hs3yv59claaxxyc9l8m2c8-julia-bin-1.10.3/share/julia/test/file.jl:1696
       >   Expression: !(isnothing(Base.Filesystem.getgroupname(s.gid)))
       >
       > Error in testset file:
       > Test Failed at /nix/store/qmbxymr953hs3yv59claaxxyc9l8m2c8-julia-bin-1.10.3/share/julia/test/file.jl:1717
       >   Expression: !(isnothing(Base.Filesystem.getgroupname(s.gid)))
       >
       > ERROR: LoadError: Test run finished with errors
       > in expression starting at /nix/store/qmbxymr953hs3yv59claaxxyc9l8m2c8-julia-bin-1.10.3/share/julia/test/runtests.jl:95
       For full logs, run 'nix log /nix/store/5qkvlkq47lnrg9m18cfmq3yck41jhhp6-julia-bin-1.10.3.drv'.
error: builder for '/nix/store/v0jkgkkmjvrpcywhz3lf7sbki7yb5g0r-julia-1.10.3.drv' failed with exit code 2;
       last 10 log lines:
       >   Expression: !(isnothing(Base.Filesystem.getgroupname(s.gid)))
       >
       > Error in testset file:
       > Test Failed at /build/julia-1.10.3/test/file.jl:1717
       >   Expression: !(isnothing(Base.Filesystem.getgroupname(s.gid)))
       >
       > ERROR: LoadError: Test run finished with errors
       > in expression starting at /build/julia-1.10.3/test/runtests.jl:95
       > make[1]: *** [Makefile:30: all] Error 1
       > make: *** [Makefile:619: testall] Error 2
       For full logs, run 'nix log /nix/store/v0jkgkkmjvrpcywhz3lf7sbki7yb5g0r-julia-1.10.3.drv'.
error: 1 dependencies of derivation '/nix/store/6lj9fzxslkrccp5nx67h7d6brlql2p6x-cantor-23.08.5.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hs9rcj2dcp2mx9rgi3pw9xz1f9cp13r9-labplot-2.10.1.drv' failed to build
error: 4 dependencies of derivation '/nix/store/lz9phpcmb2xwbzsfcb51021l9jxcmkwc-review-shell.drv' failed to build
```

**Comment by NickCao** [comment]
> it seems some of the tests may be flaky

May you share the full log?

**Comment by getchoo** [comment]
[v0jkgkkmjvrpcywhz3lf7sbki7yb5g0r-julia-1.10.3.drv.log](https://github.com/NixOS/nixpkgs/files/15181803/v0jkgkkmjvrpcywhz3lf7sbki7yb5g0r-julia-1.10.3.drv.log)
[5qkvlkq47lnrg9m18cfmq3yck41jhhp6-julia-bin-1.10.3.drv.log](https://github.com/NixOS/nixpkgs/files/15181804/5qkvlkq47lnrg9m18cfmq3yck41jhhp6-julia-bin-1.10.3.drv.log)

**Comment by NickCao** [comment]
I feel that this might not be flaky, but something related to the filesystem, or even nscd?

> [v0jkgkkmjvrpcywhz3lf7sbki7yb5g0r-julia-1.10.3.drv.log](https://github.com/NixOS/nixpkgs/files/15181803/v0jkgkkmjvrpcywhz3lf7sbki7yb5g0r-julia-1.10.3.drv.log) [5qkvlkq47lnrg9m18cfmq3yck41jhhp6-julia-bin-1.10.3.drv.log](https://github.com/NixOS/nixpkgs/files/15181804/5qkvlkq47lnrg9m18cfmq3yck41jhhp6-julia-bin-1.10.3.drv.log)

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 308070` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>cantor (libsForQt5.cantor ,plasma5Packages.cantor)</li>
    <li>julia (julia-stable ,julia_110)</li>
    <li>julia-bin (julia-stable-bin ,julia_110-bin)</li>
    <li>labplot</li>
  </ul>
</details>

**Comment by NickCao** [comment]
Merging as unable to reproduce the failure and ofborg is happy.

**Pull request merged**
