### PR TITLE
pythonManylinuxPackages: add libz and expat

### PR DESCRIPTION
**Pull request by jneem**
###### Description of changes

Adds two libs to the `pythonManylinuxPackages` collection. These libs aren't mentioned in PEP 513, but auditwheel allows them (https://github.com/pypa/auditwheel/issues/152) and so built wheels may depend on them.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Janik-Haag — APPROVED** [review]
LGTM

**Review by Janik-Haag — COMMENTED** [review]
the diff looks fine but the build throws errors:
```
nix-build -A pythonManylinuxPackages                            
error:
       … while calling the 'foldl'' builtin

         at /home/janik/Projects/nixos/nixpkgs/pkgs/development/interpreters/python/manylinux/default.nix:78:16:

           77|   # Additionally, add `autoPatchelfHook` to `nativeBuildInputs`.
           78|   manylinux1 = lib.unique (lib.attrValues manylinux1Libs);
             |                ^
           79|   manylinux2010 = lib.unique (lib.attrValues manylinux2010Libs);

       … while evaluating a branch condition

         at /home/janik/Projects/nixos/nixpkgs/lib/lists.nix:646:28:

          645|    */
          646|   unique = foldl' (acc: e: if elem e acc then acc else acc ++ [ e ]) [];
             |                            ^
          647|

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: undefined variable 'libz'

       at /home/janik/Projects/nixos/nixpkgs/pkgs/development/interpreters/python/manylinux/default.nix:59:19:

           58|     "libglib-2.0.so.0" = glib;
           59|     "libz.so.1" = libz;
             |                   ^
           60|     "libexpat.so.1" = expat;
``` :/

**Comment by jneem** [comment]
Thanks for checking, and sorry for the mistake. (I could have sworn I ran `nix-build -A pythonManylinuxPackages` already!)

Anyway, it should be better now.

**Comment by Janik-Haag** [comment]
Thanks for your contribution and sorry that It took so long until someone reviewed it /: 
I will merge this since PR runs successfully and the package builts fine locally.

**Pull request merged**
