### PR TITLE
convos: 5.00 -> 5.11

### PR DESCRIPTION
**Pull request by stigtsp**
###### Motivation for this change

https://github.com/Nordaaker/convos/blob/5.11/Changes

dependencies:
perlPackages.HTTPAcceptLanguage: init at 0.02
perlPackages.LinkEmbedder: 1.15 -> 1.16
perlPackages.Mojolicious: 8.67 -> 8.71
perlPackages.MojoliciousPluginWebpack: 0.13 -> 0.14 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>50 packages built:</summary>
  <ul>
    <li>abcde</li>
    <li>convos</li>
    <li>perl530Packages.HTTPAcceptLanguage</li>
    <li>perl530Packages.JSONValidator</li>
    <li>perl530Packages.LinkEmbedder</li>
    <li>perl530Packages.Minion</li>
    <li>perl530Packages.MinionBackendSQLite</li>
    <li>perl530Packages.MinionBackendmysql</li>
    <li>perl530Packages.MojoIOLoopForkCall</li>
    <li>perl530Packages.MojoJWT</li>
    <li>perl530Packages.MojoPg</li>
    <li>perl530Packages.MojoRedis</li>
    <li>perl530Packages.MojoSAML</li>
    <li>perl530Packages.MojoSQLite</li>
    <li>perl530Packages.MojoUserAgentCached</li>
    <li>perl530Packages.Mojolicious</li>
    <li>perl530Packages.MojoliciousPluginAssetPack</li>
    <li>perl530Packages.MojoliciousPluginGravatar</li>
    <li>perl530Packages.MojoliciousPluginMail</li>
    <li>perl530Packages.MojoliciousPluginOpenAPI</li>
    <li>perl530Packages.MojoliciousPluginStatus</li>
    <li>perl530Packages.MojoliciousPluginTextExceptions</li>
    <li>perl530Packages.MojoliciousPluginWebpack</li>
    <li>perl530Packages.Mojomysql</li>
    <li>perl530Packages.MusicBrainz</li>
    <li>perl530Packages.OpenAPIClient</li>
    <li>perl532Packages.HTTPAcceptLanguage</li>
    <li>perl532Packages.JSONValidator</li>
    <li>perl532Packages.LinkEmbedder</li>
    <li>perl532Packages.Minion</li>
    <li>perl532Packages.MinionBackendSQLite</li>
    <li>perl532Packages.MinionBackendmysql</li>
    <li>perl532Packages.MojoIOLoopForkCall</li>
    <li>perl532Packages.MojoJWT</li>
    <li>perl532Packages.MojoPg</li>
    <li>perl532Packages.MojoRedis</li>
    <li>perl532Packages.MojoSAML</li>
    <li>perl532Packages.MojoSQLite</li>
    <li>perl532Packages.MojoUserAgentCached</li>
    <li>perl532Packages.Mojolicious</li>
    <li>perl532Packages.MojoliciousPluginAssetPack</li>
    <li>perl532Packages.MojoliciousPluginGravatar</li>
    <li>perl532Packages.MojoliciousPluginMail</li>
    <li>perl532Packages.MojoliciousPluginOpenAPI</li>
    <li>perl532Packages.MojoliciousPluginStatus</li>
    <li>perl532Packages.MojoliciousPluginTextExceptions</li>
    <li>perl532Packages.MojoliciousPluginWebpack</li>
    <li>perl532Packages.Mojomysql</li>
    <li>perl532Packages.MusicBrainz</li>
    <li>perl532Packages.OpenAPIClient</li>
  </ul>
</details>

Tested OK on linux x64 and darwin x64.

### CODE REVIEW

**Comment by zakame** [comment]
Result of `nixpkgs-review pr 110054` run on Other x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>50 packages built:</summary>
  <ul>
    <li>abcde</li>
    <li>convos</li>
    <li>perl530Packages.HTTPAcceptLanguage</li>
    <li>perl530Packages.JSONValidator</li>
    <li>perl530Packages.LinkEmbedder</li>
    <li>perl530Packages.Minion</li>
    <li>perl530Packages.MinionBackendSQLite</li>
    <li>perl530Packages.MinionBackendmysql</li>
    <li>perl530Packages.MojoIOLoopForkCall</li>
    <li>perl530Packages.MojoJWT</li>
    <li>perl530Packages.MojoPg</li>
    <li>perl530Packages.MojoRedis</li>
    <li>perl530Packages.MojoSAML</li>
    <li>perl530Packages.MojoSQLite</li>
    <li>perl530Packages.MojoUserAgentCached</li>
    <li>perl530Packages.Mojolicious</li>
    <li>perl530Packages.MojoliciousPluginAssetPack</li>
    <li>perl530Packages.MojoliciousPluginGravatar</li>
    <li>perl530Packages.MojoliciousPluginMail</li>
    <li>perl530Packages.MojoliciousPluginOpenAPI</li>
    <li>perl530Packages.MojoliciousPluginStatus</li>
    <li>perl530Packages.MojoliciousPluginTextExceptions</li>
    <li>perl530Packages.MojoliciousPluginWebpack</li>
    <li>perl530Packages.Mojomysql</li>
    <li>perl530Packages.MusicBrainz</li>
    <li>perl530Packages.OpenAPIClient</li>
    <li>perl532Packages.HTTPAcceptLanguage</li>
    <li>perl532Packages.JSONValidator</li>
    <li>perl532Packages.LinkEmbedder</li>
    <li>perl532Packages.Minion</li>
    <li>perl532Packages.MinionBackendSQLite</li>
    <li>perl532Packages.MinionBackendmysql</li>
    <li>perl532Packages.MojoIOLoopForkCall</li>
    <li>perl532Packages.MojoJWT</li>
    <li>perl532Packages.MojoPg</li>
    <li>perl532Packages.MojoRedis</li>
    <li>perl532Packages.MojoSAML</li>
    <li>perl532Packages.MojoSQLite</li>
    <li>perl532Packages.MojoUserAgentCached</li>
    <li>perl532Packages.Mojolicious</li>
    <li>perl532Packages.MojoliciousPluginAssetPack</li>
    <li>perl532Packages.MojoliciousPluginGravatar</li>
    <li>perl532Packages.MojoliciousPluginMail</li>
    <li>perl532Packages.MojoliciousPluginOpenAPI</li>
    <li>perl532Packages.MojoliciousPluginStatus</li>
    <li>perl532Packages.MojoliciousPluginTextExceptions</li>
    <li>perl532Packages.MojoliciousPluginWebpack</li>
    <li>perl532Packages.Mojomysql</li>
    <li>perl532Packages.MusicBrainz</li>
    <li>perl532Packages.OpenAPIClient</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110054` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>47 packages failed to build and are new build failures:</summary>
  <ul>
<li>convos: log was empty</li>
<li>perl530Packages.JSONValidator: log was empty</li>
<li>perl530Packages.LinkEmbedder: log was empty</li>
<li>perl530Packages.Minion: log was empty</li>
<li>perl530Packages.MinionBackendSQLite: log was empty</li>
<li>perl530Packages.MinionBackendmysql: log was empty</li>
<li>perl530Packages.MojoIOLoopForkCall: log was empty</li>
<li>perl530Packages.MojoJWT: log was empty</li>
<li>perl530Packages.MojoPg: log was empty</li>
<li>perl530Packages.MojoRedis: log was empty</li>
<li>perl530Packages.MojoSAML: log was empty</li>
<li>perl530Packages.MojoSQLite: log was empty</li>
<li>perl530Packages.MojoUserAgentCached: log was empty</li>
<li>perl530Packages.Mojolicious: log <a href="https://termbin.com/trov">https://termbin.com/trov</a></li>
<li>perl530Packages.MojoliciousPluginAssetPack: log was empty</li>
<li>perl530Packages.MojoliciousPluginGravatar: log was empty</li>
<li>perl530Packages.MojoliciousPluginMail: log was empty</li>
<li>perl530Packages.MojoliciousPluginOpenAPI: log was empty</li>
<li>perl530Packages.MojoliciousPluginStatus: log was empty</li>
<li>perl530Packages.MojoliciousPluginTextExceptions: log was empty</li>
<li>perl530Packages.MojoliciousPluginWebpack: log was empty</li>
<li>perl530Packages.Mojomysql: log was empty</li>
<li>perl530Packages.MusicBrainz: log was empty</li>
<li>perl530Packages.OpenAPIClient: log was empty</li>
<li>perl532Packages.JSONValidator: log was empty</li>
<li>perl532Packages.LinkEmbedder: log was empty</li>
<li>perl532Packages.Minion: log was empty</li>
<li>perl532Packages.MinionBackendSQLite: log was empty</li>
<li>perl532Packages.MinionBackendmysql: log was empty</li>
<li>perl532Packages.MojoIOLoopForkCall: log was empty</li>
<li>perl532Packages.MojoJWT: log was empty</li>
<li>perl532Packages.MojoPg: log was empty</li>
<li>perl532Packages.MojoRedis: log was empty</li>
<li>perl532Packages.MojoSAML: log was empty</li>
<li>perl532Packages.MojoSQLite: log was empty</li>
<li>perl532Packages.MojoUserAgentCached: log was empty</li>
<li>perl532Packages.Mojolicious: log <a href="https://termbin.com/mf6s">https://termbin.com/mf6s</a></li>
<li>perl532Packages.MojoliciousPluginAssetPack: log was empty</li>
<li>perl532Packages.MojoliciousPluginGravatar: log was empty</li>
<li>perl532Packages.MojoliciousPluginMail: log was empty</li>
<li>perl532Packages.MojoliciousPluginOpenAPI: log was empty</li>
<li>perl532Packages.MojoliciousPluginStatus: log was empty</li>
<li>perl532Packages.MojoliciousPluginTextExceptions: log was empty</li>
<li>perl532Packages.MojoliciousPluginWebpack: log was empty</li>
<li>perl532Packages.Mojomysql: log was empty</li>
<li>perl532Packages.MusicBrainz: log was empty</li>
<li>perl532Packages.OpenAPIClient: log was empty</li>
  </ul>
</details>
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>perl530Packages.HTTPAcceptLanguage</li>
<li>perl532Packages.HTTPAcceptLanguage</li>
</ul>
</details>

**Comment by stigtsp** [comment]
> Result of `nixpkgs-review pr 110054` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
> 47 packages failed to build and are new build failures:

The checkPhase for Mojolicious seems to cause the problem - from https://termbin.com/mf6s:
```
t/mojo/daemon.t ............................ 1/? 
#   Failed test 'No tests run for subtest "Minimal application"'
#   at t/mojo/daemon.t line 35.
Can't create listen socket: Operation not permitted at /private/tmp/nix-build-perl5.30.3-Mojolicious-8.71.drv-0/Mojolicious-8.71/blib/lib/Mojo/IOLoop.pm line 130.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 1.
```

I'm able to reproduce this problem on my darwin x64 running macOS 10.15.7 under `nixpkgs-review`, however `nix-build -A convos` and `nix-build -A perlPackages.Mojolicious` works fine. Some sandboxing on darwin seems to cause problems binding to localhost I think.

**Comment by SuperSandro2000** [comment]
> I'm able to reproduce this problem on my darwin x64 running macOS 10.15.7 under `nixpkgs-review`, however `nix-build -A convos` and `nix-build -A perlPackages.Mojolicious` works fine. Some sandboxing on darwin seems to cause problems binding to localhost I think.

I think this, too.

**Review by zakame — APPROVED** [review]

**Comment by stigtsp** [comment]
Tested OK on linux x64 and darwin x64:
- Basic functionality works, connected to freenode
- New SASL EXTERNAL feature works

Ticks all the boxes, will merge.

**Pull request merged**
