### PR TITLE
uv: build with python builder to include python module

### PR DESCRIPTION
**Pull request by Aleksanaa**
## Description of changes

Requested by @Moraxyc 

I'm not 100% sure this is correct though.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Aleksanaa** [comment]
Before:
```
/nix/store/m1bpll41w8vbx8zk18qcrlrv7y8pqnqy-uv-0.1.44
├── bin
│   └── uv
└── share
    ├── bash-completion
    │   └── completions
    │       └── uv.bash
    ├── fish
    │   └── vendor_completions.d
    │       └── uv.fish
    └── zsh
        └── site-functions
            └── _uv
```
After:
```
./result                                                                                                                                                   
├── bin                                                                                                                                                    
│   └── uv
├── lib
│   └── python3.11
│       └── site-packages
│           ├── uv
│           │   ├── __init__.py
│           │   ├── __main__.py
│           │   ├── __pycache__
│           │   │   ├── __init__.cpython-311.opt-1.pyc
│           │   │   ├── __init__.cpython-311.pyc
│           │   │   ├── __main__.cpython-311.opt-1.pyc
│           │   │   └── __main__.cpython-311.pyc
│           │   └── py.typed
│           └── uv-0.1.45.dist-info
│               ├── license_files
│               │   ├── LICENSE-APACHE
│               │   └── LICENSE-MIT
│               ├── METADATA
│               ├── RECORD
│               └── WHEEL
├── nix-support
│   └── propagated-build-inputs
└── share
    ├── bash-completion
    │   └── completions
    │       └── uv.bash
    ├── fish
    │   └── vendor_completions.d
    │       └── uv.fish
    └── zsh
        └── site-functions
            └── _uv
```

**Comment by Moraxyc** [comment]
Successfully built using this package as a python dependency.

**Comment by GaetanLepage** [comment]
Hey ! Thanks for the patch.

> Requested by @Moraxyc

Could you please provide a more precise context for this change (reference to an issue, documentation...) ?

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 314183` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>uv (python311Packages.uv)</li>
    <li>uv.dist (python311Packages.uv.dist)</li>
    <li>python312Packages.uv</li>
    <li>python312Packages.uv.dist</li>
  </ul>
</details>

**Comment by Aleksanaa** [comment]
> Could you please provide a more precise context for this change (reference to an issue, documentation...) ?

The latest version of `hatch` requires `uv>=0.1.35` as a pyproject dependency: https://github.com/pypa/hatch/blob/abf787d64f1afec7f658343f10188369554bd5a6/pyproject.toml#L54

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 314183` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>uv (python311Packages.uv)</li>
    <li>uv.dist (python311Packages.uv.dist)</li>
    <li>python312Packages.uv</li>
    <li>python312Packages.uv.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 314183` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>uv (python311Packages.uv)</li>
    <li>uv.dist (python311Packages.uv.dist)</li>
    <li>python312Packages.uv</li>
    <li>python312Packages.uv.dist</li>
  </ul>
</details>

**Review by GaetanLepage — APPROVED** [review]
Diff LGTM and the package still builds fine.

**Review by natsukium — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
