### PR TITLE
vault: 1.5.4 -> 1.5.5

### PR DESCRIPTION
**Pull request by marsam**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102402` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>vault</li>
    <li>vault-bin</li>
  </ul>
</details>

**Review by mkaito — APPROVED** [review]
diff looks good to me. ofborg has been building this for 16 hours? Is that normal?

**Comment by marsam** [comment]
>ofborg has been building this for 16 hours? Is that normal?

it's because currently there are no builders for darwin https://monitoring.nix.ci/dashboard/db/ofborg

**Comment by SuperSandro2000** [comment]
> it's because currently there are no builders for darwin [monitoring.nix.ci/dashboard/db/ofborg](https://monitoring.nix.ci/dashboard/db/ofborg)

Can't we run the tests manually? I don't know the command.

**Comment by mkaito** [comment]
That would be `nix-build -A nixosTests.vault`.

I just ran them, and they pass on my machine (`x86_64-linux`).

**Review by mkaito — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
```
nix-build -A nixosTests.vault
error: assertion (stdenv).isLinux failed at /Users/user/nixpkgs2/pkgs/os-specific/linux/kernel/generic.nix:66:1
(use '--show-trace' to show detailed location information)
```

Does not run on darwin.

**Comment by SuperSandro2000** [comment]
```
nix-build -A nixosTests.vault
error: assertion (stdenv).isLinux failed at /Users/user/nixpkgs2/pkgs/os-specific/linux/kernel/generic.nix:66:1
(use '--show-trace' to show detailed location information)
```

Does not run on darwin.

**Pull request merged**
