### PR TITLE
ejabberd: 20.12 -> 21.04

### PR DESCRIPTION
**Pull request by Izorkin**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 122569` at f04448c8 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>ejabberd</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/servers/xmpp/ejabberd/default.nix:115:5:
```
    |
115 |     license = licenses.gpl2;
    |     ^
```
</li>
  </ul>
</details>

**Comment by hrhino** [comment]
It appears that the license for this should be `gpl2Plus` according to the files' license headers; oddly, though, there are a few (such as [src/mod_mqtt_ws.erl](https://github.com/processone/ejabberd/blob/b860a25c82515ba51b044e13ea4e040e3b9bbc41/src/mod_mqtt_ws.erl)) that claim to be apache v2...

**Comment by hrhino** [comment]
```
[nix-shell:~/.cache/nixpkgs-review/pr-122569]$ results/ejabberd/bin/iex
/nix/store/a94napnlmxxvlsvycqf0ynnd6w0igrbq-ejabberd-21.04/bin/elixir: line 126: exec: erl: not found
```

I'm getting this if I try to run `iex` or `mix` binaries... presumably those scripts should have their `ERL_EXEC="erl"` lines patched.

**Review by hrhino — CHANGES_REQUESTED** [review]
see above comments

**Pull request merged**
