### PR TITLE
nixos/steam: support using system fonts in Steam interface

### PR DESCRIPTION
**Pull request by eclairevoyant**
## Description of changes

Without this fix, all Chinese and Japanese text in the Steam interface display as boxes ("tofu").

As we use the existing fonts on the system, this avoids closure impact.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Aleksanaa** [comment]
Is it able to pick up noto-fonts-cjk or source-han-sans (they are the same project but packaged by google and adobe)? Wenquanyi is quite aged imo

**Comment by Aleksanaa** [comment]
> Does wenquanyi lack any code points that I didn't notice?

Not really. I did hear some people complain that it didn't look good, or didn't work well on their high-resolution screens. Not a big problem compared to closure size.

**Comment by Aleksanaa** [comment]
Also it seems that it is not completely impossible to load Chinese fonts. Some Chinese users reported that they were once able to load the system's Chinese fonts correctly, although some games were still missing fonts. But after recent update it's broken again. This problem may be caused by steam incompatible with variable fonts.

The workaround they mentioned earlier is consistent with the changes you made in this PR: adding Chinese fonts to extraPackages.

I don't currently have steam installed on my computer, so I'm sorry I can't help you.

CC @A1ca7raz @ocfox @yilozt @oxalica for reporting font problems in NixOS Chinese group.

**Comment by eclairevoyant** [comment]
I don't think it's a variable font issue necessarily; it did used to pick up my system fonts until a few weeks ago. Now, even adding wqy to the system fonts doesn't help.

Either way I will see if a minimal font package can be made, based on one of the newer projects.

**Comment by jonringer** [comment]
> Is it able to pick up noto-fonts-cjk or source-han-sans (they are the same project but packaged by google and adobe)? Wenquanyi is quite aged imo

32bit support is needed for a lot of this.... age is an awkward thing :)

**Comment by jonringer** [comment]
I wonder if we could have the steam nixos module also pick up system fonts.... that seems like a more scalable and less closure bloat way to go about this.

**Comment by eclairevoyant** [comment]
> I wonder if we could have the steam nixos module also pick up system fonts.... that seems like a more scalable and less closure bloat way to go about this.

Thanks, seems to work as well.

**Review by mkg20001 — APPROVED** [review]

**Review by jonringer — APPROVED** [review]

**Review by jonringer — APPROVED** [review]
Looks right to me, should be minimal closure increase since the fonts are already going to be be installed

**Comment by oxalica** [comment]
It does not eval for me on 0c165dec843e9aa71379c4928df273b5ea8b7df7. Is the steam module tested?

```
error:
       … while calling the 'head' builtin

         at /nix/store/j0dd6cvy5nfv70v5nvsx0glrfc2is0k6-source/lib/attrsets.nix:1541:11:

         1540|         || pred here (elemAt values 1) (head values) then
         1541|           head values
             |           ^
         1542|         else

       … while evaluating the attribute 'value'

         at /nix/store/j0dd6cvy5nfv70v5nvsx0glrfc2is0k6-source/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attempt to call something which is not a function but a list

       at /nix/store/j0dd6cvy5nfv70v5nvsx0glrfc2is0k6-source/pkgs/games/steam/fhsenv.nix:47:8:

           46|     sqlite
           47|   ] ++ extraPkgs pkgs;
             |        ^
           48|

```

**Comment by eclairevoyant** [comment]
You're right, `extraPkgs` should be a function, not a list. I'm not sure why it went through despite cherry-picking the change into the nixpkgs used by my config 😕

**Comment by jonringer** [comment]
That's on me. I should have attempted a system rebuild.

**Pull request merged**
