### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by matthewbauer**
Experiments in improving derivation performance. Trying two things:

- inlining isCross
- don't check hardening flags up front

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
@grahamcofborg eval

**Comment by grahamc** [comment]
Tomorrow I'll generate some flame graphs for comparison, but according to the performance report in the Checks tab, this is very promising. Some highlights:

 - function calls are reduced by ~1 million, 
 - 83 mb cut off the heap
 - 4.5 million fewer lookups

Nicely done!

**Comment by offlinehacker** [comment]
Nice job 🙂 BTW, how do you profile nix and what do you to create flame graphs?

**Comment by grahamc** [comment]
It looks like https://github.com/NixOS/nixpkgs/pull/59369 isn't included in your branch, so it is a bit obscured by the unique function's interesting behavior. At any rate, here we are: 

before: http://gsc.io/log.matthewbauer.pre.folded.svg

after: http://gsc.io/log.matthewbauer.folded.svg

**Comment by grahamc** [comment]
https://github.com/NixOS/nixpkgs/pull/59756/checks?check_run_id=109424120 this report is generated by comparing the results from `NIX_SHOW_STATS=1 nix-instantiate pkgs/top-level/all-packages.nix -A unstable`.

For flame graphs: have like 30gb of ram (swap is ok but slow) and follow https://github.com/NixOS/nix/pull/2782

**Comment by matthewbauer** [comment]
@grahamc A question for you on the performance report:

Is it comparing performance results against the previous commit or the master branch? For instance I am trying to figure out the difference between these two results:

- https://github.com/NixOS/nixpkgs/pull/59756/checks?sha=a06b702
- https://github.com/NixOS/nixpkgs/pull/59756/checks?sha=a1dcb88

**Pull request closed without merging**
