### PR TITLE
matrix-synapse: Allow keys to be generated

### PR DESCRIPTION
**Pull request by eqyiel**
###### Motivation for this change

The matrix-synapse user has `createHome = true;` which runs before this `preStart` script, so the home directory will always exist and this block will never execute.

Also don't include default path to keys in the configuration file, because synapse will choke if it tries to open them before they exist (even with `--generate-keys`).

Any existing keys will not be overwritten: https://github.com/matrix-org/synapse/blob/9bba6ebaa903a81cd94fada114aa71e20b685adb/synapse/config/tls.py#L86-L150
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by rycee** [comment]
To which extent is this change transparent to NixOS users? Having a brief look at it it seems that existing NixOS configurations should continue to function as-is, but maybe you can confirm? If there are any user-visible changes then I think this PR should include a release note.

**Comment by eqyiel** [comment]
@rycee I'm not sure what you mean?  This change should be completely transparent for existing users of `services.matrix-synapse`.  It only makes a difference for new users who are not using an existing cert / key, because the `preStart` script now works as intended.

**Comment by Ralith** [comment]
And even then, the only observable difference should be that it actually works as opposed to failing to start, right?

**Comment by rycee** [comment]
Great, that was what I was hoping for :-)

**Comment by rycee** [comment]
Tried out this change and it started just fine, including generation of certificates on the first run. I would be happy to see this PR applied.

**Comment by rycee** [comment]
Since there were no more issues raised I've rebased this into master in 08d7fbb42d37994ad0a4f736f5585d6b584b4b87. Many thanks for your contribution!

**Pull request closed without merging**
