### PR TITLE
R: Update CRAN and bioconductor packages

### PR DESCRIPTION
**Pull request by jabranham**
###### Motivation for this change
Update R package set

###### Things done

Ran `nix-build test-evaluation.nix --dry-run`

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @peti

### CODE REVIEW

**Comment by peti** [comment]
Test builds of 064aebf2bb5c2dace7128e528e6f8a2211f6a146 are running at https://hydra.nixos.org/jobset/nixpkgs/r-updates.

**Comment by peti** [comment]
There are 2000+ newly broken packages after this update. :-(

I added aedf9aa6ccbdc0ef8efc11c8e1468f36820f4526 to the `r-updates` branch. That should fix some of them. But it's probably a good idea to fix some more pivotal packages before we merge.

**Comment by peti** [comment]
0537d3cdbe96524d53de856d5933bac99a07fd8f should improve matters some more ...

**Comment by jabranham** [comment]
Thanks. Looks like between those two commits we're back up to about the same numbers as before.

**Comment by peti** [comment]
Merged to `master`.

**Pull request closed without merging**
