### PR TITLE
elasticsearch: 1.5.2 -> 1.7.2

### PR DESCRIPTION
**Pull request by itkovian**

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @offlinehacker

**Comment by offlinehacker** [comment]
@itkovian did you check that all relevant plugins  are correct versions and support es 1.7

**Comment by offlinehacker** [comment]
Based on travis, i woukd say it's ok, but will test it,  before merging. @itkovian tnx for update

**Comment by itkovian** [comment]
No, I did not. At the moment, I cannot get anything installed either due to #9809, so I cannot really help at this moment.

**Comment by offlinehacker** [comment]
Will test it on our servers.

**Comment by lethalman** [comment]
This should go to master, not staging.

**Comment by offlinehacker** [comment]
Ok, i agree, i'm merging.

**Comment by offlinehacker** [comment]
Ah, i was too fast, to not notice this is for staging

**Comment by itkovian** [comment]
@lethalman Which is why I wanted it to go to staging, but apparently that was the wrong branch?

**Comment by lethalman** [comment]
@itkovian it's not what staging is for

**Pull request merged**
