### PR TITLE
gettext: 0.19.6 -> 0.19.7

### PR DESCRIPTION
**Pull request by zimbatm**
now using libxml2 instead of expat

Replaces #13072

Needs testing, still compiling on my machine.

### CODE REVIEW

**Comment by zimbatm** [comment]
It compiles fine but I'm not sure what to text with the XML version

**Comment by vcunat** [comment]
gtk3 build uses it. Maybe @lethalman remembers what was the problem in there.

**Comment by zimbatm** [comment]
I made some cleanup which I was at it.

gettext, gettextWithXML and gtk3 compile fine.

After installing gettextWithXML and running `ldd $(which gettext)` I only get:
```
$ readlink $(which gettext)
/nix/store/wbpykariknr1qqdyl29f33gmj6yp1dpg-gettext-0.19.7-with-xml/bin/gettext
$ ldd $(which gettext)
	linux-vdso.so.1 (0x00007ffe517c0000)
	libc.so.6 => /nix/store/3xnbb8hkzv8nmndssknx413sd217bj56-glibc-2.21/lib/libc.so.6 (0x00007f19bb1ab000)
	/nix/store/3xnbb8hkzv8nmndssknx413sd217bj56-glibc-2.21/lib/ld-linux-x86-64.so.2 (0x00007f19bb54a000)
```

**Comment by vcunat** [comment]
Well, it seems not detected, as it's not in closure and log says:
```
checking whether included libxml is requested... no
checking for libxml... no
checking whether to use the included libxml... yes
```

**Comment by vcunat** [comment]
But I think it's OK for now to let it use bundled libxml. I think this gettext+XML stuff is all used only during build-time anyway.

**Comment by zimbatm** [comment]
I bet it needs pkgconfig to find it. I agree, let's use the bundled version for now and make gettextWithExpat a deprecated alias.

**Comment by zimbatm** [comment]
Compiling gtk3 to see if it works. If you have an idea of a gtk3 program that uses locales heavily let me know.

**Comment by zimbatm** [comment]
Compiled sonata which uses gtk3, ran `LANG=de_DE.utf8 LC_CTYPE= sonata` and got proper German in the UI. I'm not 100% sure this exercises gettext+xml or how to find a program that does.

Is this good enough for testing ?

**Comment by vcunat** [comment]
I think so. IIRC expat was only needed during build time.

**Comment by zimbatm** [comment]
Okay. How do you usually merge a mass rebuild, is there anything different to do ?

**Comment by vcunat** [comment]
They get merged to staging to save master from mass rebuilds without binaries.

**Comment by zimbatm** [comment]
Is staging merged back into master later or do I first merge the branch into staging manually, wait for hydra to catch-up and then merge this branch into master ?

**Comment by vcunat** [comment]
Staging is merged to master periodically, after Hydra finishes (most) builds.

**Comment by zimbatm** [comment]
Just merged into staging manually: https://github.com/NixOS/nixpkgs/compare/8bfc5d7e724d...f05bc0444aac

**Comment by vcunat** [comment]
Then we should close this.

**Comment by abbradar** [comment]
It would be nice to have this in master as soon as possible -- we have `git rebase` broken on unstable channel now...

**Comment by zimbatm** [comment]
agreed. Still 26k packages to go: https://hydra.nixos.org/jobset/nixpkgs/staging

**Comment by abbradar** [comment]
As a workaround with less rebuilding needed I've reverted patch c38eb526d59e2fcc985a0459e94a6ad30b1d3706 locally (changing it a bit to make sure when actual fixes hit master `rebase` will yell at me to skip it).

**Comment by zimbatm** [comment]
Yeah it might make sense to bundle these changes

**Comment by abbradar** [comment]
Well, we might just wait for Hydra to finish most builds now -- reverting that patch is a good enough workaround for those who need it. I hope next unstable channel won't be so delayed ~_^.

**Comment by abbradar** [comment]
...wait, I think `git rebase` might actually have worked for me, just spewed error messages and haven't shown other ones. Let me check...

**Comment by zimbatm** [comment]
Yeah next time. Hopefully the hydra+s3 stuff goes out soon as well so we can have faster builds.

**Comment by abbradar** [comment]
Yes, that was a false call. `git pull --rebase` has shown only errors to me so I assumed that it's broken, but I have just been atop the latest master already. Sorry for the noise!

**Pull request closed without merging**
