### PR TITLE
add electron-chromedriver

### PR DESCRIPTION
**Pull request by liam-murphy14**
## Description of changes

Add new package electron-chromedriver which wraps the electron build of chromedriver found in each electron release. See [the electron GitHub page](https://github.com/electron/electron) for more info.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilylange** [comment]
Hi and welcome to nixpkgs :)
You PR looks good to me at first glance.
Thank you for following our maze of contributing guidelines and whatnot :p

One question came to mind (as `chromium` maintainer) before I look any further into this though:

The "original" `chromedriver` (for `chromium`) needs to be kept in sync with each major version (which is why `chromedriver` part of our `chromium` version bumps).

I would assume this is also the case with `electron-chromedriver` and `electron`.
Can you comment on this?
We maintain multiple major versions of `electron` in nixpkgs at each time.
Do we need multiple `electron-chromedriver` version due to this as well? :eyes:

**Comment by liam-murphy14** [comment]
Hi @emilylange, thanks for checking out my PR! 

To answer your question: I intend to keep `electron-chromedriver` up to date with each `chromium` release. To my understanding, the latest `electron` release should be up to date with the latest `chromium` version. This package does not rely on which `electron` version is used apart from deciding which `chromedriver` binary it downloads. To me, the thing that matters most is that it stays compatible with `chromium`. 

Let me know if you need any more info on this, happy to discuss further!

**Comment by yu-re-ka** [comment]
Why download the binary and not build from source? If this is part of the regular electron release tarballs, then the chromedriver is already availabe in the underlying electron derivation.

**Comment by liam-murphy14** [comment]
Hi @yu-re-ka, I downloaded the binary instead of building from source because I used the existing nix `chromedriver` derivation, which does the same, as a template. This binary is included in the regular releases of electron, but I don't see anywhere in the nix `electron` derivation where it is exposed or would be. I am relatively new to nix though, so I might be missing something. If there is a clear/simple way to expose the `chromedriver` binary from the underlying `electron` derivation, please point me in the right direction and I'd be happy to open a PR for that instead of this.

As a side note: I started writing this because I needed a chromedriver binary that runs of `aarch64-linux` without building from source because I don't have very powerful hardware. I realized there exists an [electron-chromedriver npm package](https://www.npmjs.com/package/electron-chromedriver) and wanted to write something similar for nixpkgs. If there is a better way to achieve this, do let me know. Thanks for the review

**Pull request closed without merging**
