### PR TITLE
WIP: qtcreator: fix examples (make them visible)

### PR DESCRIPTION
**Pull request by bjornfor**
This is an attempt to make it possible to run QtCreator and browse (and build) examples directly from the IDE. Currently the examples page is empty, and I'm stuck.

EDIT: DON'T MERGE YET.

### CODE REVIEW

**Comment by akaWolf** [comment]
@bjornfor 
There is qt54.doc package. I think, if you add it to Qt Creator build inputs, QtC should find documentation. Why did you create buildDocs parameter and «qt5-with-docs» package?
Examples should be build and installed with Qt Base submodule.
So «qt5-with-examples» without buildDocs parameter would be more logical, I think.

**Comment by bjornfor** [comment]
@akaWolf: Ok, I'll check the qt54.doc attribute.

About qt5-with-docs, that was just a "desperate attempt". It's not indented to be merged.

**Comment by akaWolf** [comment]
@bjornfor 
Oh... Examples are contained in all submodules. So we need to install them for all submodules (probably in qt-submodule.nix), not only in qtbase.nix.

**Comment by akaWolf** [comment]
@bjornfor 
Looks like we need for every submodule do also «make install_docs».
«make install» already should install examples, but looks like there is something wrong with paths. By default make is trying to install examples to the directory where Qt is installed (I guess, it's determined by «qmake -query» output).

**Comment by bjornfor** [comment]
Note to self: https://wiki.qt.io/Qt_Examples_in_Qt_Creator

**Comment by rasendubi** [comment]
(triage) @bjornfor any update?

**Comment by bjornfor** [comment]
@rasendubi: Nope. This keeps getting deprioritized :-(

**Comment by 7c6f434c** [comment]
I guess can be closed for now…

**Pull request closed without merging**
