### PR TITLE
gtk-mac-integration: 2.0.8 -> 2.1.3

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

Version update

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
I don't have a way to test, unfortunately, so please review this.

**Comment by veprbl** [comment]
@GrahamcOfBorg build gtk-mac-integration-gtk2 gtk-mac-integration-gtk3

**Comment by prusnak** [comment]
@GrahamcOfBorg build gtk-mac-integration-gtk2 gtk-mac-integration-gtk3

**Review by veprbl — APPROVED** [review]
Tested by running dia.

nixpkgs-review on x86_64-darwin
```
3 package marked as broken and skipped:
gimpPlugins.ufraw ufraw zathura

3 package failed to build:
gimp gimpPlugins.gmic haskellPackages.gtk-mac-integration

25 package built:
cherrytree compcert coq_8_5 coq_8_6 coq_8_7 coq_8_8 coq_8_9 darktable dia framac gtk-mac-integration gtk-mac-integration-gtk2 libbap opa prooftree proverif python27Packages.bap python27Packages.gwyddion python27Packages.pygtksourceview python37Packages.bap python38Packages.bap satysfi unison usync why3
```

**Pull request merged**
