### PR TITLE
rustic: rename from rustic-rs

### PR DESCRIPTION
**Pull request by alyssais**
## Description of changes

As far as I can tell, the name of the software is "rustic".  [Every other distro calls it "rustic".][1]  The crate is presumably called "rustic-rs" because "rustic" is already taken on crates.io, which is not a problem in Nixpkgs.

I've added "rustic-rs" as an alias, so the old name will continue working.

[1]: https://repology.org/project/rustic/versions

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by matthiasbeyer — DISMISSED** [review]
You're doing two things at once here: Renaming the package and moving it to the `by-name` hierarchy.

That should be two individual commits. I am also not sure whether the `all-packages.nix` change is actually correct, as by-name packages are imported automatically!

**Comment by alyssais** [comment]
> Renaming the package and moving it to the `by-name` hierarchy.

It's not allowed to rename a package _without_ moving to the by-name hierarchy, so I'm not sure I agree that these are two different things.

> I am also not sure whether the all-packages.nix change is actually correct, as by-name packages are imported automatically!

Yes, but this package needs an argument passed to it, so it has to still be listed in all-packages.nix.  This is what the by-name documentation [says to do](https://github.com/NixOS/nixpkgs/tree/523e0c0310a8e92500818632603fe118fb8b2acd/pkgs/by-name#changing-implicit-attribute-defaults), and also what the countless examples of by-name packages that take callPackage overrides already in Nixpkgs do.

**Review by NobbZ — APPROVED** [review]

**Comment by NobbZ** [comment]
> It's not allowed (per CI) to rename a package without moving to the by-name hierarchy, so I'm not sure I agree that these are two different things.

It should be fine to:

1. rename the attribute in one commit
2. move it to `pkgs/by-name` in the second

If this does indeed not work proof this by a screenshot showing that borgi still complaints about this and re-request a review by matthias.

**Comment by alyssais** [comment]
I still think adding an extra commit to rename a file that then immediately gets renamed again in the next commit makes no sense, but I've done it.

**Review by NobbZ — APPROVED** [review]

**Comment by NobbZ** [comment]
@matthiasbeyer Can you please unblock the PR?

**Comment by matthiasbeyer** [comment]
Sorry, I was traveling and just came back. Here you go...

**Comment by alyssais** [comment]
Ugh, hash mismatch because the name change.  Will fix…

**Review by NobbZ — APPROVED** [review]

**Comment by NobbZ** [comment]
Result of `nixpkgs-review pr 331757` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>rustic</li>
  </ul>
</details>

**Review by matthiasbeyer — APPROVED** [review]

**Comment by NobbZ** [comment]
I will merge if the `nixpkgs-review` for aarch64 succeeds. It is just a matter of days…

image

**Comment by NobbZ** [comment]
Result of `nixpkgs-review pr 331757` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>rustic</li>
  </ul>
</details>

**Pull request merged**
