### PR TITLE
python3Packages.pendulum: fix build

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
pendulum switched over to a poetry build

also needed `poetry-core` to work correctly

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Already fixed in https://github.com/NixOS/nixpkgs/commit/d58b4c9a14b97312defa629187cc8791c8d73c46.

**Comment by jonringer** [comment]
... literally minutes before i made this

**Comment by jonringer** [comment]
@mweinelt there was more packaging work done in my PR to enable the packages on other python versions, I opened a new PR with my additional work

**Comment by mweinelt** [comment]
@jonringer Sorry, I just skimmed the commit messages, I'll take a look.

**Pull request closed without merging**
