### PR TITLE
python3Packages.openhomedevice: init at 1.0.0

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Python module to access Linn Ds and Openhome devices

https://github.com/bazwilliams/openhomedevice

This is a Home Assistant dependency. The Home Assistant's tests don't pass (python-jose issue).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 118453` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.openhomedevice</li>
    <li>python39Packages.openhomedevice</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
> The Home Assistant's tests don't pass (python-jose issue).

Can you post the output?

**Comment by fabaff** [comment]
```bash
warning: ignoring the user-specified setting 'sandbox', because it is a restricted setting and you are not a trusted user
builder for '/nix/store/46wxdrylxzn8dfb2kxhyrl8ja2mb07ls-homeassistant-2021.3.4.drv' failed with exit code 5; last 10 log lines:
  ../../nix/store/pcsjm5rkczklba3j2jm0444ydlgvd2k9-python3.8-python-jose-3.2.0/lib/python3.8/site-packages/jose/backends/cryptography_backend.py:18
  ../../nix/store/pcsjm5rkczklba3j2jm0444ydlgvd2k9-python3.8-python-jose-3.2.0/lib/python3.8/site-packages/jose/backends/cryptography_backend.py:18
  ../../nix/store/pcsjm5rkczklba3j2jm0444ydlgvd2k9-python3.8-python-jose-3.2.0/lib/python3.8/site-packages/jose/backends/cryptography_backend.py:18
  ../../nix/store/pcsjm5rkczklba3j2jm0444ydlgvd2k9-python3.8-python-jose-3.2.0/lib/python3.8/site-packages/jose/backends/cryptography_backend.py:18
  ../../nix/store/pcsjm5rkczklba3j2jm0444ydlgvd2k9-python3.8-python-jose-3.2.0/lib/python3.8/site-packages/jose/backends/cryptography_backend.py:18
    /nix/store/pcsjm5rkczklba3j2jm0444ydlgvd2k9-python3.8-python-jose-3.2.0/lib/python3.8/site-packages/jose/backends/cryptography_backend.py:18: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
      from cryptography.utils import int_from_bytes, int_to_bytes
  
  -- Docs: https://docs.pytest.org/en/stable/warnings.html
  ============================= 5 warnings in 6.20s ==============================
cannot build derivation '/nix/store/5r49dy9npkf7z23rwh68jhzfx0p7b0fd-env.drv': 1 dependencies couldn't be built
```

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 118453` at 8ffa4754 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.openhomedevice</li>
    <li>python39Packages.openhomedevice</li>
  </ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by mweinelt** [comment]
> ```shell
> warning: ignoring the user-specified setting 'sandbox', because it is a restricted setting and you are not a trusted user
> builder for '/nix/store/46wxdrylxzn8dfb2kxhyrl8ja2mb07ls-homeassistant-2021.3.4.drv' failed with exit code 5; last 10 log lines:
>   ../../nix/store/pcsjm5rkczklba3j2jm0444ydlgvd2k9-python3.8-python-jose-3.2.0/lib/python3.8/site-packages/jose/backends/cryptography_backend.py:18
>   ../../nix/store/pcsjm5rkczklba3j2jm0444ydlgvd2k9-python3.8-python-jose-3.2.0/lib/python3.8/site-packages/jose/backends/cryptography_backend.py:18
>   ../../nix/store/pcsjm5rkczklba3j2jm0444ydlgvd2k9-python3.8-python-jose-3.2.0/lib/python3.8/site-packages/jose/backends/cryptography_backend.py:18
>   ../../nix/store/pcsjm5rkczklba3j2jm0444ydlgvd2k9-python3.8-python-jose-3.2.0/lib/python3.8/site-packages/jose/backends/cryptography_backend.py:18
>   ../../nix/store/pcsjm5rkczklba3j2jm0444ydlgvd2k9-python3.8-python-jose-3.2.0/lib/python3.8/site-packages/jose/backends/cryptography_backend.py:18
>     /nix/store/pcsjm5rkczklba3j2jm0444ydlgvd2k9-python3.8-python-jose-3.2.0/lib/python3.8/site-packages/jose/backends/cryptography_backend.py:18: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
>       from cryptography.utils import int_from_bytes, int_to_bytes
>   
>   -- Docs: https://docs.pytest.org/en/stable/warnings.html
>   ============================= 5 warnings in 6.20s ==============================
> cannot build derivation '/nix/store/5r49dy9npkf7z23rwh68jhzfx0p7b0fd-env.drv': 1 dependencies couldn't be built
> ```

That is not the real error. The error is simply that there are no tests for the `openhome` component. So if you disable xdist for a moment the error will become visible.

```
ERROR: file or directory not found: tests/components/openhome
```

What you posted are deprecation warnings, they wouldn't cause a failure.

**Review by mweinelt — APPROVED** [review]

**Comment by mweinelt** [comment]
Approach for a better error response when component tests are enabled and they do not exist over in https://github.com/NixOS/nixpkgs/pull/118703.

**Comment by fabaff** [comment]
Thanks

**Pull request merged**
