### PR TITLE
Node.js (0.12.0 -> 0.12.4)

### PR DESCRIPTION
**Pull request by Havvy**

### CODE REVIEW

**Comment by Havvy** [comment]
Failure occurred due to too many line of output. I tested this locally and it worked.

**Comment by Havvy** [comment]
This is ready to merge in... @shlevy @vcunat

**Comment by vcunat** [comment]
Just curious... why ping me?

**Comment by Havvy** [comment]
Somebody mentioned your name on IRC when I asked about somebody merging this in.

**Pull request closed without merging**
