### PR TITLE
[21.05] gitea: startup script changes

### PR DESCRIPTION
**Pull request by vs49688**
###### Motivation for this change
Backports of https://github.com/NixOS/nixpkgs/pull/129861, https://github.com/NixOS/nixpkgs/pull/132882

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by symphorien** [comment]
Can you elaborate on the need to backport these ? Notably #129861 looks like a performance improvement only, so not obviously worth the risk backporting.

https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#criteria-for-backporting-changes

**Comment by vs49688** [comment]
The performance difference I'm seeing is from hours to seconds. `systemctl start gitea` would routinely timeout when starting gitea before these changes.

Perhaps I've just hit a pathological case, but I'm running this on stable with no issues.

**Comment by happysalada** [comment]
I think the rule for backporting is there to limit the amount of PRs we have to deal with as maintainers.
Given the fact that this helps people, how about we make an exception ?
I don't feel this would set a precedent, and I think that the rule about backporting has been made clear.
@symphorien I am happy to go both ways, if you feel strongly about this.

**Comment by symphorien** [comment]
no strong feelings either way. I you tested it and it works please go ahead!

**Comment by happysalada** [comment]
Amazing. I'm just about to test it on monday. I'll update when I've had a run.

**Comment by happysalada** [comment]
finally had the chance to test. Looks good.

**Pull request merged**
