### PR TITLE
Refactor another ~100 package from python-packages.nix -> python-modules

### PR DESCRIPTION
**Pull request by costrouc**
###### Things done

All have been tested to build and is ready for merge

Strictly moving package to python-modules. Did not attempt to upgrade package unless it added python 3 support or was broken. Also converted fetch... to fetchPypi to make future upgrades easier. All packages have been tested in sandbox mode to build properly.

As of the last edit there are ~332 remaining packages to move.

```
grep "buildPythonPackage" python-packages.nix | wc
    332    1706   13716
```

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lheckemann** [comment]
Sorry, I broke this by splitting slixmpp in #48545

**Comment by FRidh** [comment]
e08ab90  should be squashed

**Comment by costrouc** [comment]
@lheckemann no worries I will rebase it. I appreciate you letting me know. @FRidh my git fu is not quite good enough and I was being lazy when I made those commits. I will learn how to properly split that commit and merge into the appropriate commit.

**Comment by costrouc** [comment]
@FRidh I have learned just how powerful rebasing can be. I have removed all (2) of the commits that "patched" typos I made in the previous commit. Thanks for the feedback and ready to merge.

**Comment by Mic92** [comment]
Good job.

**Comment by costrouc** [comment]
25 more packges -> python-modules. All tested.

**Comment by ryantm** [comment]
@costrouc Thank you for this work! [@FRidh is encouraging](https://github.com/ryantm/nixpkgs-update/issues/83) me to start updating Python packages semi-automatically with r-ryantm/nixpkgs-update and it cannot update the packages in python-modules.nix (because it won't update things in a file with multiple fetchers), so this work you are doing should help keep Python packages more up to date!

**Comment by costrouc** [comment]
You are welcome! I was aware of your bot and someone told me that it could only work with `fetchPypi` and being in `python-modules`. To me it seems like automation is an important step in the growth of `nix`. Otherwise small package updates will consume too much of our time. I have a bit more free time for the next month and my goal is to really cleanup the python packages in `nix`.

**Comment by costrouc** [comment]
The good news is that soon (next few years) python projects will start declaring their dependencies in a static file `pyproject.toml`. This will make life much easier for updating packages.

**Comment by Mic92** [comment]
pyproject.toml will probably still need some time to establish. At the moment I don't see how c-extension can be packed this way.

**Comment by ryantm** [comment]
As far as I know, nixpkgs-update doesn't need the derivation to use `fetchPypi`. In fact, here is one using fetchFromGitHub: https://github.com/NixOS/nixpkgs/pull/49037/files

**Comment by costrouc** [comment]
@ryantm what `fetch...` does it work with? In some cases packages released through `pypi` do not contain tests which make upgrades more dangerous (not knowing if something breaks). Makes me want to favor `fetchFromGitHub`, `fetchFromGitLab`, etc. What are your thoughts?

**Comment by ryantm** [comment]
@costrouc As long as the fetcher is written in some way that it gets modified by changing the version string somewhere in the file, and the hash for it is somewhere in the file, and `nix-prefetch-url` works,  it should work. So, all the main fetchers work, but sometimes expressions are formatted in a way that doesn't works, for example, the `rev` might not be based on the version, or fetchgit is using the commit sha.

As for what to do for python things, I want to defer to @FRidh. I'm not familiar with the Python ecosystem.

**Comment by FRidh** [comment]
> pyproject.toml will probably still need some time to establish. At the moment I don't see how c-extension can be build using this.

`pyproject.toml` will specify that `setuptools` will be used as build system, and from there on everything is the same as it is now. It's a step in the right direction, giving access to dependencies in a easier way. However, we still have to do the hardest part: dependency resolution across the whole package set.

**Pull request merged**
