### PR TITLE
emacs-irony: fix build

### LINKED ISSUE #66556: Emacs irony doesn't build
**To Reproduce**
1. force install the irony emacs package with allowBroken
2. 
```
[...]
no Makefile or custom buildPhase, doing nothing
installing
Parsing tar file...
Parsing tar file...done
Wrong type argument: arrayp, nil
builder for '/nix/store/8mwsvlc8lw10rbpfcqsgb435y0qkdghd-emacs-irony-20190703.1732.drv' failed with exit code 255
```

**Expected behavior**
The package builds and works

**Additional context**
It has been introduced by https://github.com/NixOS/nixpkgs/pull/65874/commits/978b34622bccce24f179ffaf4475544dbe2e61dd#diff-b1864d4e308e56ef358dd33142771718R380

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.65, NixOS, 19.09pre188498.4557b9f1f50 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre188498.4557b9f1f50"`
 - channels(multun): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

@adisbladis 

I tried to debug this but couldn't figure it out :(

### PR DESCRIPTION
**Pull request by matthewbauer**
Fixes #66556

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by mmahut** [comment]
@GrahamcOfBorg build emacs-irony

**Comment by mmahut** [comment]
@GrahamcOfBorg build emacsPackagesNg.melpaPackages.irony

**Comment by alexarice** [comment]
@matthewbauer is irony working for you after this pr, I'm getting 
```
(void-function irony-cdb-autosetup-compile-options)
```
and am trying to work out if I am doing something wrong or if the package has somehow gone weird after the update

**Comment by alexarice** [comment]
ignore this, I have fixed the issue by adding `(require 'irony-cbd)` to my config

**Pull request merged**
