### PR TITLE
devbox: 0.13.0 -> 0.13.3

### PR DESCRIPTION
**Pull request by Lagoja**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by momeemt** [comment]
Result of `nixpkgs-review pr 346260` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>devbox</li>
  </ul>
</details>

**Review by momeemt — APPROVED** [review]
LGTM :)

**Comment by sikmir** [comment]
Result of `nixpkgs-review pr 346260` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>devbox</li>
  </ul>
</details>

**Comment by sikmir** [comment]
Could you please fix cross compilation:
```diff
diff --git i/pkgs/development/tools/devbox/default.nix w/pkgs/development/tools/devbox/default.nix
index b0432c609a8c..cc2e9a61e04a 100644
--- i/pkgs/development/tools/devbox/default.nix
+++ w/pkgs/development/tools/devbox/default.nix
@@ -2,6 +2,7 @@
 , fetchFromGitHub
 , installShellFiles
 , lib
+, stdenv
 }:
 buildGoModule rec {
   pname = "devbox";
@@ -27,7 +28,7 @@ buildGoModule rec {

   nativeBuildInputs = [ installShellFiles ];

-  postInstall = ''
+  postInstall = lib.optionalString (stdenv.buildPlatform.canExecute stdenv.hostPlatform) ''
     installShellCompletion --cmd devbox \
       --bash <($out/bin/devbox completion bash) \
       --fish <($out/bin/devbox completion fish) \

```

**Comment by sikmir** [comment]
```sh
[nix-shell:~/.cache/nixpkgs-review/pr-346260]$ results/devbox/bin/updater
panic: lstat go.jetpack.io/devbox/examples: no such file or directory

goroutine 1 [running]:
main.main()
	go.jetpack.io/devbox/testscripts/testrunner/updater/main.go:19 +0x2b
```

Looks like `subPackages = [ "cmd/devbox" ];` should be added.

**Comment by Lagoja** [comment]
@sikmir Thanks for the suggestions! I've amended the PR to include your feedback

**Pull request merged**
