### PR TITLE
python2Packages.legitfs: init at 0.3

### PR DESCRIPTION
**Pull request by layus**

### CODE REVIEW

**Review by FRidh — CHANGES_REQUESTED** [review]
tests aren't run

**Comment by FRidh** [comment]
Also, will you maintain this package?

**Comment by layus** [comment]
@FRidh I just noticed that version 0.4 was released at the same time as this PR.

This updated version
* Has myself as a maintainer.
* Uses version 0.4.0
* Updates fastimport for py3k support (as legitfs added support for py3k in the meantime).
* Still runs no tests, because legitfs has none

**Comment by globin** [comment]
Could you change the message of the first commit `python2Packages -> pythonPackages`?

**Comment by FRidh** [comment]
> Still runs no tests, because legitfs has none

Then it needs `doCheck = false;` along with a comment stating it doesn't include tests.

**Comment by layus** [comment]
Closing. the updated version does not work properly. I will resubmit later when I get more time to investigate.

@globin, @FRidh : Thanks for the guidelines about formatting & co in pythonPacakges.

**Pull request closed without merging**
