### PR TITLE
vimPlugins.fern-vim: init at 2020-12-22

### PR DESCRIPTION
**Pull request by jmc-figueira**
###### Motivation for this change
Added the [fern.vim](https://github.com/lambdalisue/fern.vim) vim plugin.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Please never merge master into a branch to fix a conflict. I am going to fix that now once because I need to add another commit.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108213` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
27 packages built:
</summary>
<ul>
<li>spacevim</li>
<li>vimPlugins.Spacegray-vim</li>
<li>vimPlugins.YouCompleteMe</li>
<li>vimPlugins.coc-nvim</li>
<li>vimPlugins.completion-nvim</li>
<li>vimPlugins.defx-git</li>
<li>vimPlugins.deol-nvim</li>
<li>vimPlugins.fern-vim</li>
<li>vimPlugins.nvim-highlite</li>
<li>vimPlugins.nvim-lspconfig</li>
<li>vimPlugins.nvim-lsputils</li>
<li>vimPlugins.nvim-treesitter</li>
<li>vimPlugins.nvim-treesitter-context</li>
<li>vimPlugins.nvim-treesitter-textobjects</li>
<li>vimPlugins.telescope-nvim</li>
<li>vimPlugins.vim-airline</li>
<li>vimPlugins.vim-clap</li>
<li>vimPlugins.vim-floaterm</li>
<li>vimPlugins.vim-hexokinase</li>
<li>vimPlugins.vim-lsp</li>
<li>vimPlugins.vim-ocaml</li>
<li>vimPlugins.vim-polyglot</li>
<li>vimPlugins.vim-visual-multi</li>
<li>vimPlugins.vim-vsnip</li>
<li>vimPlugins.vimsence</li>
<li>vimPlugins.vista-vim</li>
<li>vimPlugins.yats-vim</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108213` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
4 packages built:
</summary>
<ul>
<li>spacevim</li>
<li>vimPlugins.YouCompleteMe</li>
<li>vimPlugins.vim-clap</li>
<li>vimPlugins.vim-hexokinase</li>
</ul>
</details>

**Comment by jmc-figueira** [comment]
> Please never merge master into a branch to fix a conflict. I am going to fix that now once because I need to add another commit.

Oh, I'm sorry, I followed [this suggestion](https://nixos.wiki/wiki/Nixpkgs/Contributing) and thought it would be the ideal way of keeping my branch up to date. I initially tried a rebase, which pulled all of master's recent commits into the pull request, which was definitely a bad idea, so I thought a merge was the right thing to do. For future reference, what is the recommended way of doing this?

In any case, thank you for approving my request.

**Pull request merged**
