### PR TITLE
vulkan-utility-libraries: 1.3.270 -> 1.3.268

### LINKED ISSUE #268429: Build failure:  vulkan-validation-layers-1.3.268.0
### Steps To Reproduce

1. build vulkan-validation-layers

### Build log

https://gist.github.com/khaneliman/f00a01e44bd586a274955b875324a890#file-vulkan-validation-layers-1-3-268-0-drv-error

### Notify maintainers
@Ralith 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix-shell -p nix-info --run "nix-info -m"
🔨 Welcome to khanelinix
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.1, NixOS, 23.11 (Tapir), 23.11.20231114.bf744fe`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`

```

### PR DESCRIPTION
**Pull request by khaneliman**
## Description of changes
Utility libraries were updated past the current sdk release and package is broken because of it. Reverting to last released sdk version.

Resolves https://github.com/NixOS/nixpkgs/issues/268429

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by khaneliman** [comment]
Result of `nixpkgs-review pr 268730` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>vulkan-extension-layer</li>
    <li>vulkan-tools-lunarg</li>
    <li>vulkan-utility-libraries</li>
    <li>vulkan-validation-layers</li>
    <li>vulkan-validation-layers.debug</li>
  </ul>
</details>

**Comment by vs49688** [comment]
Result of `nixpkgs-review pr 268730` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>vulkan-extension-layer</li>
    <li>vulkan-tools-lunarg</li>
    <li>vulkan-utility-libraries</li>
    <li>vulkan-validation-layers</li>
    <li>vulkan-validation-layers.debug</li>
  </ul>
</details>

**Review by vs49688 — APPROVED** [review]

**Comment by Ralith** [comment]
Thanks for handling this!

**Comment by 9p4** [comment]
Shouldn't the hash be `sha256-l6PiHCre/JQg8PSs1k/0Zzfwwv55AqVdZtBbjeKLS6E=`?

**Comment by NickCao** [comment]
> Shouldn't the hash be `sha256-l6PiHCre/JQg8PSs1k/0Zzfwwv55AqVdZtBbjeKLS6E=`?

Seems so.

**Comment by khaneliman** [comment]
Is it failing hydra or something? I’m using this hash locally and it passed nixpkgs-review

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by NickCao** [comment]
FODs won't get rebuilt as long as it's already in your store, try replacing the hash with `lib.fakeHash` and build again.

**Pull request merged**
