### PR TITLE
klavaro: 3.08 -> 3.09

### PR DESCRIPTION
**Pull request by davidak**
###### Motivation for this change

Update

Screenshot from 2020-05-28 00 44 18

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc maintainer @mimame

### CODE REVIEW

**Comment by drewrisinger** [comment]
From the linked Sourceforge page, the author mentions releasing 3.10. Would prefer to merge 3.10 vs 3.09. Looks like 3.10 is available on https://sourceforge.net/projects/klavaro/files/
Also, general best practice is to fetch a patch from the web vs including it in the Nix tree, though it looks like this patch will be redundant in v3.10.

**Comment by davidak** [comment]
>Looks like 3.10 is available

yes, i know. but i think it's nice to have all versions in nixpkgs history. will make a new pr for it

i couldn't find the patch in repo, so created it manually

**Comment by davidak** [comment]
superseded by https://github.com/NixOS/nixpkgs/pull/89352

**Comment by drewrisinger** [comment]
FYI, you don't have to close the PR/branch. You can rename & force-push to overwrite this one.

**Pull request closed without merging**
