### PR TITLE
ocamlPackage.ppx_deriving: fix build with ocaml 4.07

### PR DESCRIPTION
**Pull request by symphorien**
###### Motivation for this change

https://github.com/NixOS/nixpkgs/pull/161344#issuecomment-1055616670

cc @vbgl

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by vbgl — CHANGES_REQUESTED** [review]
This wrongly makes recent versions of `ppx_deriving` depend on `ounit`.

**Comment by symphorien** [comment]
as far as I can see, the diff of the PR you bisected to on ppx_deriving is:
```diff
commit a13cdfe520d87db401dd000fbd67cad728162a60
Author: Ulrik Strid <ulrik.strid@outlook.com>
Date:   Tue Feb 22 10:59:04 2022 +0100

    ocamlPackages tree-wide: Move buildInputs that should be nativeBuildInputs
    
    To keep this for the future we also strictDeps where possible, including for janePackages, topkg, oasis and ocamlbuild.
    This makes some closures significantly smaller and makes cross compilation easier

diff --git a/pkgs/development/ocaml-modules/ppx_deriving/default.nix b/pkgs/development/ocaml-modules/ppx_deriving/default.nix
index 5563e611346..090c8113ce4 100644
--- a/pkgs/development/ocaml-modules/ppx_deriving/default.nix
+++ b/pkgs/development/ocaml-modules/ppx_deriving/default.nix
@@ -5,7 +5,7 @@
 , ppxlib
 , ppx_derivers
 , result
-, ounit
+, ounit2
 , ocaml-migrate-parsetree
 , ocaml-migrate-parsetree-2
 }:
@@ -37,7 +37,11 @@ buildDunePackage rec {
     inherit (params) sha256;
   };
 
-  buildInputs = [ ppxlib cppo ];
+  # This currently fails with dune
+  strictDeps = false;
+
+  nativeBuildInputs = [ cppo ];
+  buildInputs = [ ppxlib ];
   propagatedBuildInputs = [
     (if params.useOMP2
     then ocaml-migrate-parsetree-2
@@ -47,7 +51,7 @@ buildDunePackage rec {
   ];
 
   doCheck = true;
-  checkInputs = [ ounit ];
+  checkInputs = [ ounit2 ];
 
   meta = with lib; {
     description = "deriving is a library simplifying type-driven code generation on OCaml >=4.02.";
```
so if depending on ounit was a mistake, it was the case before.

**Comment by vbgl** [comment]
Alright. Your argument is convincing. Can we take the opportunity of this PR to also fix the mistake from the past?

Suggested patch:
~~~
--- a/pkgs/development/ocaml-modules/ppx_deriving/default.nix
+++ b/pkgs/development/ocaml-modules/ppx_deriving/default.nix
@@ -6,6 +6,7 @@
 , ppx_derivers
 , result
 , ounit
+, ounit2
 , ocaml-migrate-parsetree
 , ocaml-migrate-parsetree-2
 }:
@@ -51,7 +52,9 @@ buildDunePackage rec {
   ];
 
   doCheck = true;
-  checkInputs = [ ounit ];
+  checkInputs = [
+    (if lib.versionAtLeast params.version "5.2" then ounit2 else ounit)
+  ];
 
   meta = with lib; {
     description = "deriving is a library simplifying type-driven code generation on OCaml >=4.02.";
~~~

**Comment by ulrikstrid** [comment]
Looking at it there doesn't seem to be a difference between `ounit` and `ounit2` since the first just installs 2 in its place

**Comment by vbgl** [comment]
Yes. `ounit` is a compatibility layer (around `ounit2`) for legacy code not yet updated to `ounit2`.

**Comment by symphorien** [comment]
done

**Comment by vbgl** [comment]
Thanks.

**Pull request merged**
