### PR TITLE
prisma: 3.11.0 -> 3.12.0

### PR DESCRIPTION
**Pull request by pimeys**
###### Description of changes

Changelog: https://github.com/prisma/prisma/releases/tag/3.12.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by tomhoule — APPROVED** [review]

**Comment by superherointj** [comment]
Packages updated are `nodePackages.prisma` and `prisma-engines` and not `prisma` (at top-level) as conveyed on commit message. Ideally we should be more precise on this. Each package on it's own commit. When running `nixpkgs-review pr` only prisma-engines was built. I don't know if this is related. I'm still trying to understand.

**Comment by pimeys** [comment]
The thing why they're bundled is that we cannot update only one of them, they must come in bundle. Why they're not in the same build setup is an unfortunate decision made by Prisma ages ago...

**Comment by pimeys** [comment]
> > The thing why they're bundled is that we cannot update only one of them, they must come in bundle. Why they're not in the same build setup is an unfortunate decision made by Prisma ages ago...
> 
> I was referring to the location of package at nixpkgs. In nixpkgs, at top level, package `prisma` does not exist. Which makes the commit message wrong. And as two packages are being updated, there should be two commit messages. One for `nodePackages.prisma` and another for `prisma-engines`.
> 
> Sorry about the inconvenience here just following the guidelines.

Oh, cool. Fixed that!

**Comment by pimeys** [comment]
I'm just wondering is it really worth it due to somebody just checking [this commit](https://github.com/NixOS/nixpkgs/pull/167353/commits/e9b3ad050595060512bdfa73897989a82cf059e2) and then building nodePackages.prisma would give them a broken tool...

**Comment by superherointj** [comment]
You could add a comment to both packages saying it needs to be updated in lockstep with nodePackages.prisma, prisma-engines.

**Comment by superherointj** [comment]
A note on why such package shouldn't be used standalone could be good as well. We need more documentation on Prisma here. I've struggled a bit with Prisma. And my setup is still far from ideal. (I'm still using a nix-shell that I want to get rid of, eventually.)

**Comment by pimeys** [comment]
You basically need both packages, `nodePackages.prisma` is the command line utility, and the node library `prisma-client` needs to know where to find the engine files, and in general nixpkgs don't hold javascript libraries, so you need to do an environment trick for it to work (as seen in my example).

**Comment by pimeys** [comment]
Added comments about the dependency.

**Comment by pimeys** [comment]
Wait, so docs and version change in the same commit or how do we squash?

**Comment by superherointj** [comment]
> Too bad NixOS is not and probably will not be officially supported by the company. Luckily two Prisma's Rust devs are hardcore NixOS users and here we are. :)

As Nix is gaining in popularity, this might change. I see a lot of growth of Nix happening. Everything at it's due time. Thanks for your contribution to Nix. Happy to use it. :-)

**Comment by superherointj** [comment]
> 

It's just a comment. Not a problem. You don't need to add docs for now. The comment is enough.

**Comment by pimeys** [comment]
Quickly still confirming, do you want me to modify this PR somehow, didn't really catch that.

**Comment by superherointj** [comment]
> Quickly still confirming, do you want me to modify this PR somehow, didn't really catch that.

As you are changing 2 packages, it should be 2 commits and not 4 commits. One commit per package.

**Comment by pimeys** [comment]
Done.

**Review by superherointj — APPROVED** [review]

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
