### PR TITLE
python pyflakes: 0.9.2 -> 1.0.0

### PR DESCRIPTION
**Pull request by FRidh**

### CODE REVIEW

**Comment by domenkozar** [comment]
I've lowered it to `0.8.1` for #10399 because latests flake8 blocks newer versions

**Comment by FRidh** [comment]
How about having a `pyflakes_0_8` specificly for `flake8`?
If I'm correct a higher version of pyflakes is needed for Python 3.5

**Comment by domenkozar** [comment]
Right, OK, let's have `pyflakes_0_8`

**Comment by FRidh** [comment]
Merged in #10255

**Pull request closed without merging**
