### PR TITLE
update zdoom package

### PR DESCRIPTION
**Pull request by Lassulus**
the old one was broken.

### CODE REVIEW

**Comment by jagajaga** [comment]
We prefer releases. And I can see `2.7.1`. So please update to this version.

**Comment by Lassulus** [comment]
sadly i cant build 2.7.1.
```
/tmp/nix-build-zdoom-2.7.1.drv-0/zdoom-2.7.1-src/src/sdl/hardware.cpp:35:17: fatal error: SDL.h: No such file or directory
#include <SDL.h>
                 ^
compilation terminated.
```

**Comment by jagajaga** [comment]
You need `SDL` as I can see.

**Comment by Lassulus** [comment]
this i the full build.log and the updated default.nix. 
https://gist.github.com/Lassulus/55beb80f04b1283e0fbc
I have included SDL and he reports he can find it, the error happens nevertheless.

**Comment by lethalman** [comment]
Try `NIX_CFLAGS_COMPILE = [ "${SDL2}/include/SDL2" ];`

**Comment by Lassulus** [comment]
alright, I managed to build 2.7.1.

**Comment by lethalman** [comment]
Built locally, thanks. @madjar for some reason new packages are not picked by travis.

**Pull request merged**
