### PR TITLE
sonar-scanner-bin: init at 3.3.0.1492

### PR DESCRIPTION
**Pull request by peterromfeldhk**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterromfeldhk** [comment]
i have no idea how to build this from source :(

even for the `bin` version i have some questions:
1. it comes with `jre` shipped, i guess i should instead propagate jre?
2. it has some config, should i make it a service where you can configure it?

**Comment by peterromfeldhk** [comment]
also issue on linux :(
```
[nix-shell:~]$ sonar-scanner -h
/nix/store/xgs83qivcnl370wdypbazj0zw9bls51j-sonar-scanner-bin-3.3.0.1492/bin/sonar-scanner: line 59: /nix/store/xgs83qivcnl370wdypbazj0zw9bls51j-sonar-scanner-bin-3.3.0.1492/jre/bin/java: No such file or directory
```

**Comment by peterromfeldhk** [comment]
just had successful run with it on OSX :) need to try it on linux

**Comment by peterromfeldhk** [comment]
also seems to work fine on nixos

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by wmertens** [comment]
Well this seems ok - too bad it uses a binary install while the source is at https://www.github.com/SonarSource/sonar-scanner-cli

I'm a bit conflicted, on the one hand it's Java so compiling ourselves won't make much of a difference, OTOH we try to be a from-source distro.

@peterromfeldhk what do you think? If you prefer maintaining the binary version I'll just merge it.

**Comment by puffnfresh** [comment]
@wmertens I'd like to see this merged. I agree it would be better to do from-source but I don't want that to block having this be readily available for NixOS users. I agree it won't make much of a difference since it's Java.

**Comment by ryantm** [comment]
Result of `nixpkgs-review pr 55558` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- sonar-scanner-bin
</details>

**Pull request merged**
