### PR TITLE
obsidian: 0.8.2 -> 0.8.12

### PR DESCRIPTION
**Pull request by zaninime**
###### Motivation for this change

Updating Obsidian to 0.8.12, while reducing the final closure size. Since the app is based on Electron (without extra native dependencies), I replaced the AppImage with an Electron wrapper.

~~I still rely on the AppImage for building the derivation as it includes both the `.asar` file and the icon file.~~ I found an icon in their official forum. This will reduce the required bandwith for building too.

I also added an `updateScript`.

cc @conradmearns

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by tomberek — APPROVED** [review]
Builds, runs, and functions as expected on NixOS.

**Comment by ajs124** [comment]
@zimbatm You updated in to 0.8.2 in 873cca6e032dba597804fc46ed133b3e07d40560, what do you think of this approach?

**Comment by zimbatm** [comment]
sounds good to me! The only downside is that it's a bit more work to maintain.

**Comment by zaninime** [comment]
@zimbatm how would you like to continue with this PR? Should I rebase on master and we try to get it merged? Otherwise I will just close it.

**Comment by zimbatm** [comment]
yeah, rebase it on master and pingback when it's working

**Comment by zaninime** [comment]
@zimbatm ping

**Comment by zimbatm** [comment]
thanks!

**Pull request merged**
