### PR TITLE
gamescope: fix build

### PR DESCRIPTION
**Pull request by superherointj**
gamescope: fix build

Fix breakage from #321418

I'd appreciate further testing to confirm application works as expected.

CC @PedroHLC @magneticflux- @nrdxp @Scrumplex @zhaofengli @k900

### CODE REVIEW

**Comment by magneticflux-** [comment]
I'm not sure this is the best fix, given https://github.com/NixOS/nixpkgs/pull/319766
> Packagers have GOT to stop applying random patches/defines where they change the version of submodules to use system packages

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 321616` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
    <li>gamescope</li>
    <li>gamescope-wsi</li>
  </ul>
</details>

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 321616` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
    <li>gamescope</li>
    <li>gamescope-wsi</li>
  </ul>
</details>

**Comment by superherointj** [comment]
Thanks k900.

**Pull request merged**
