### PR TITLE
pywalfox: init at 2.7.4

### PR DESCRIPTION
**Pull request by gekoke**
###### Description of changes
https://github.com/Frewacom/pywalfox-native

Backend service python package for https://github.com/Frewacom/pywalfox.
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mtoohey31** [comment]
If I build this on `x86_64-linux` then run `pywalfox install` as the [upstream installation instructions](https://github.com/Frewacom/pywalfox#-installation) suggest, I get:

```console
Successfully removed manifest at: /home/XXX/.mozilla/native-messaging-hosts/pywalfox.json
Copied manifest to: /home/XXX/.mozilla/native-messaging-hosts/pywalfox.json
Set daemon executable path to: /nix/store/xnlc4xgzm327v1fp4na4a6mmwpiqh929-python3.10-pywalfox-2.7.4/lib/python3.10/site-packages/pywalfox/bin/main.sh
Failed to set executable permissions on: /nix/store/xnlc4xgzm327v1fp4na4a6mmwpiqh929-python3.10-pywalfox-2.7.4/lib/python3.10/site-packages/pywalfox/bin/main.sh
	[Errno 30] Read-only file system: '/nix/store/xnlc4xgzm327v1fp4na4a6mmwpiqh929-python3.10-pywalfox-2.7.4/lib/python3.10/site-packages/pywalfox/bin/main.sh'

Try setting the permissions manually using: chmod +x
```

Is running `pywalfox install` still correct when `pywalfox` itself has been installed through Nix? If so, I think we may want to add a patch that removes the calls to `set_executable_permissions`, because it looks like `main.sh` is already executable.

**Comment by gekoke** [comment]
I noticed this too, but ended up ignoring it since the script was executable. I will patch out the call.

Now that you mention it, it would be nice to declaratively ensure the post-installation state too. Though I'm not sure if this should be something the Python package derivation should handle - probably more suited for a `service.foo.enable = true;` in home-manager. I might look into that later.

**Comment by mtoohey31** [comment]
Home Manager does sound like the right place for that sort of thing.

**Comment by mtoohey31** [comment]
As of e213f8c329429cac1715a86eec617a93783bb99c, all subcommands work for me on `x86_64-linux`.

**Comment by KiaraGrouwstra** [comment]
already merged thru #271023

**Pull request closed without merging**
