### PR TITLE
python3Packages.{xdis,uncompyle6}: bump to latest to support python 3.8.12

### PR DESCRIPTION
**Pull request by r-burns**
* xdis needs a bump to support python 3.8.12 (currently in staging-next https://github.com/NixOS/nixpkgs/pull/141684/)
* uncompyle6 needs bump to support newer xdis

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-burns** [comment]
Result of `nixpkgs-review pr 144059` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python38Packages.uncompyle6</li>
    <li>unrpa (python38Packages.unrpa)</li>
    <li>python38Packages.xdis</li>
    <li>python39Packages.xdis</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
```
/nix/store/x5s5b448m5s9i1hi8n4r24c2f0b0310y-python3.8-xdis-5.0.11/lib/python3.8/site-packages/xdis/op_imports.py:173: in get_opcode_module
    return op_imports[canonic_python_version[vers_str]]
E   KeyError: '3.8.12'
```

Wow, that is something...

**Review by mweinelt — CHANGES_REQUESTED** [review]
Please rebase onto staging-next so wen can fix the issue there.

**Comment by r-burns** [comment]
Sure, done.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 144059` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
4 packages built:
</summary>
<ul>
<li>python38Packages.uncompyle6</li>
<li>unrpa (python38Packages.unrpa)</li>
<li>python38Packages.xdis</li>
<li>python39Packages.xdis</li>
</ul>
</details>

**Pull request merged**
