### PR TITLE
vimPlugins.deoplete-dictionary: init at 2019-04-16

### PR DESCRIPTION
**Pull request by justinlovinger**
###### Motivation for this change

Add deoplete-dictionary vim plugin

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Tested vim plugin
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
This actually does an update as well, but thats alright.

`nix-review` passes on NixOS
diff LGTM

```
[93 built, 34 copied (824.4 MiB), 191.3 MiB DL]
https://github.com/NixOS/nixpkgs/pull/68464
47 package were build:
vimPlugins.ale vimPlugins.coc-git vimPlugins.coc-go vimPlugins.coc-pairs vimPlugins.coc-snippets vimPlugins.coc-tsserver vimPlugins.denite-git vimPlugins.denite-nvim vimPlugins.deol-nvim vimPlugins.deoplete-dictionary vimPlugins.deoplete-fish vimPlugins.deoplete-lsp vimPlugins.deoplete-nvim vimPlugins.falcon vimPlugins.fastfold vimPlugins.ghcid vimPlugins.iosvkem vimPlugins.julia-vim vimPlugins.lh-vim-lib vimPlugins.lightline-vim vimPlugins.neomake vimPlugins.neoterm vimPlugins.nerdtree vimPlugins.nvimdev-nvim vimPlugins.vim-airline vimPlugins.vim-autoformat vimPlugins.vim-elixir vimPlugins.vim-fireplace vimPlugins.vim-fugitive vimPlugins.vim-gitgutter vimPlugins.vim-go vimPlugins.vim-grepper vimPlugins.vim-jsx-pretty vimPlugins.vim-lsc vimPlugins.vim-plug vimPlugins.vim-polyglot vimPlugins.vim-rhubarb vimPlugins.vim-ruby vimPlugins.vim-sensible vimPlugins.vim-snippets vimPlugins.vim-table-mode vimPlugins.vim-test vimPlugins.vim-visual-multi vimPlugins.vimtex vimPlugins.yats-vim vimPlugins.youcompleteme vimPlugins.zig-vim
```

**Comment by teto** [comment]
please split the addition of the plugin and the update into two commits (via git add -p for isntance)

**Comment by JustinLovinger** [comment]
> This actually does an update as well, but thats alright.

I was following [the official instructions](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/vim.section.md#adding-new-plugins-to-nixpkgs), which say to create a commit with an update before adding a new plugin.

> please split the addition of the plugin and the update into two commits (via git add -p for isntance)

The update and the addition are separate commits, with commit messages following [the official instructions](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/vim.section.md#adding-new-plugins-to-nixpkgs).

**Comment by teto** [comment]
you are right sorry :(

**Comment by JustinLovinger** [comment]
@teto No problem :)

**Pull request merged**
