### PR TITLE
bazel_4: 4.1.0 -> 4.2.1

### PR DESCRIPTION
**Pull request by timothyklim**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 136004` at 46f0f0ed run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>bazel_4</li>
  </ul>
</details>
<details>
  <summary>20 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env bash' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/shell/Command.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:178:0:
```
    |
178 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/bin/true' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/shell/Command.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:178:0:
```
    |
178 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/shell/Command.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:178:0:
```
    |
178 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env bash' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxedSpawnRunner.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:178:0:
```
    |
178 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env bash' doesn't match anything in file 'src/main/java/com/google/devtools/build/docgen/templates/be/make-variables.vm'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:178:0:
```
    |
178 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/bin/bash' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/shell/Command.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:178:0:
```
    |
178 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/sandbox/DarwinSandboxedSpawnRunner.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:178:0:
```
    |
178 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env python' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/sandbox/DarwinSandboxedSpawnRunner.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:178:0:
```
    |
178 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxedSpawnRunner.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:178:0:
```
    |
178 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env bash' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/analysis/ShToolchain.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:178:0:
```
    |
178 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env' doesn't match anything in file 'src/main/java/com/google/devtools/build/docgen/templates/be/make-variables.vm'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:178:0:
```
    |
178 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook postInstall`.

Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:588:3:
```
    |
588 |   installPhase = ''
    |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env python' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxedSpawnRunner.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:178:0:
```
    |
178 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/bin/bash' doesn't match anything in file 'src/main/java/com/google/devtools/build/docgen/templates/be/make-variables.vm'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:178:0:
```
    |
178 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/bin/true' doesn't match anything in file 'src/main/java/com/google/devtools/build/docgen/templates/be/make-variables.vm'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:178:0:
```
    |
178 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/bin/bash' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxedSpawnRunner.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:178:0:
```
    |
178 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env python' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/shell/Command.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:178:0:
```
    |
178 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env python' doesn't match anything in file 'src/main/java/com/google/devtools/build/docgen/templates/be/make-variables.vm'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:178:0:
```
    |
178 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/bin/bash' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/sandbox/DarwinSandboxedSpawnRunner.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:178:0:
```
    |
178 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '/usr/bin/env bash' doesn't match anything in file 'src/main/java/com/google/devtools/build/lib/sandbox/DarwinSandboxedSpawnRunner.java'
Near pkgs/development/tools/build-managers/bazel/bazel_4/default.nix:178:0:
```
    |
178 |     description = "Build tool that builds code quickly and reliably";
    | ^
```
</li>
  </ul>
</details>

**Comment by divanorama** [comment]
Nice, checked on Gentoo x86_64 with sandbox=true, it compiles and starts fine

**Comment by uri-canva** [comment]
Tested on:
* `x86_64-darwin` all good
* `aarch64-darwin` `//examples/cpp:hello-success_test` fails, however the built bazel version seems to work fine, it's possible the example just isn't compatible with `aarch64-darwin` to begin with, I think this is ok to ignore if nothing comes to mind, if you know how disable them for `aarch64-darwin`

I also saw a warning during the test:
```
DEBUG: /private/tmp/nix-build-bazel-4.2.1.drv-0/_bazel__nixbld1/be75a0ea28bc829c1f56b23f6947b302/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
```
Maybe the examples haven't been updated to be compatible with bazel 4.2.1 yet?

**Comment by divanorama** [comment]
seeing same debug message for 21.05 4.1.0 in hydra https://hydra.nixos.org/build/151636357#tabs-buildsteps
cpp example - not sure if it was tested on darwin in hydra yet, here are some pending jobs https://hydra.nixos.org/eval/1702415?filter=bazel_4&compare=1702318&full=#tabs-unfinished

**Comment by divanorama** [comment]
4.1.0 fails build on m1 darwin hydra
https://hydra.nixos.org/build/152240577/nixlog/8
```
ERROR: /private/tmp/nix-build-bazel-4.1.0.drv-0/bazel_kwMjBOrB/out/external/com_google_protobuf/BUILD:377:11: Linking external/com_google_protobuf/libprotoc_lib.a failed: (Exit 1): ar failed: error executing command 
  (cd /private/tmp/nix-build-bazel-4.1.0.drv-0/bazel_kwMjBOrB/out/execroot/io_bazel && \
  exec env - \
    PATH=/nix/store/9k3gs858f4q9vj328nkpfhydps34mhmx-zip-3.0/bin:/nix/store/bvsn3pwjpajrdf104zgxbf937wqpzwbr-python3-3.9.6/bin:/nix/store/0lz6q8yk7i151pkdqb9zdr2mrhkda3ql-unzip-6.0/bin:/nix/store/s2v06b2m3w9816zrppwpiddfysc370ii-which-2.21/bin:/nix/store/bwr2q22ybdjl31yi9mza8r9nzl5cl5nb-bash/bin:/nix/store/67ik3kdijgfk32g3438998z7v7z0y022-cctools-port-949.0.1/bin:/nix/store/s3inv443kpy2ghc0y9k9fkhzjillmqx1-clang-wrapper-11.1.0/bin:/nix/store/2n9xp491kavknz6dp0p6rk3czrwb74i9-clang-11.1.0/bin:/nix/store/3z3l1w9bqdd2slzfawcsqx1n3hzdia1i-coreutils-8.32/bin:/nix/store/7m7sqncxxm86qici5sya6wqbxvl8pl7w-cctools-binutils-darwin-wrapper-949.0.1/bin:/nix/store/famk49fc6hy95rb1ig0v67r3qni0f8gg-cctools-binutils-darwin-949.0.1/bin:/nix/store/23v76wa3fh6yl2nhbd350i7xsh0vmk2f-zulu11.48.21-ca-jdk-11.0.11/bin:/nix/store/3z3l1w9bqdd2slzfawcsqx1n3hzdia1i-coreutils-8.32/bin:/nix/store/pfxv6ikyz2fp1g2dlrk2zihckiyf12z7-findutils-4.8.0/bin:/nix/store/yhwc5gpzma8iv31spmn7wvgynaizvxcb-diffutils-3.7/bin:/nix/store/4vidrnjh9750fpfyby8rysb9dgxx1p8j-gnused-4.8/bin:/nix/store/5wjgbkcv93awdg9g7p1brc85ygi463rk-gnugrep-3.6/bin:/nix/store/7lsh119f052zpiidfdcpim5r9fi7h9l1-gawk-5.1.0/bin:/nix/store/mh1rcjgl181jk52id13b9wzm71wlj8h3-gnutar-1.34/bin:/nix/store/jbb0gf03cpp5h3wayqp0f84hb4a3h5q3-gzip-1.10/bin:/nix/store/fm3irf9iiymd7nxn6h9pnjgrgcaf7qjd-bzip2-1.0.6.0.2-bin/bin:/nix/store/5yl01h6vbra4kr24qnz24kl217r8dy42-gnumake-4.3/bin:/nix/store/rz3zq8dw9srfs4kv4plwry50chsxidq0-bash-4.4-p23/bin:/nix/store/chk4f0f5n2cadzdw6prwcpjkk2xda0aq-patch-2.7.6/bin:/nix/store/8mky34c1fnx5wbf6sfzdw2z5rbm8gp3k-xz-5.2.5-bin/bin:/nix/store/rz3zq8dw9srfs4kv4plwry50chsxidq0-bash-4.4-p23/bin:/nix/store/3z3l1w9bqdd2slzfawcsqx1n3hzdia1i-coreutils-8.32/bin:/nix/store/pfxv6ikyz2fp1g2dlrk2zihckiyf12z7-findutils-4.8.0/bin:/nix/store/7lsh119f052zpiidfdcpim5r9fi7h9l1-gawk-5.1.0/bin:/nix/store/5wjgbkcv93awdg9g7p1brc85ygi463rk-gnugrep-3.6/bin:/nix/store/0w23dxjq3ihy13yyv3vf0yq5cdc0qq3d-gnutar-1.34/bin:/nix/store/4vidrnjh9750fpfyby8rysb9dgxx1p8j-gnused-4.8/bin:/nix/store/jbb0gf03cpp5h3wayqp0f84hb4a3h5q3-gzip-1.10/bin:/nix/store/s2v06b2m3w9816zrppwpiddfysc370ii-which-2.21/bin:/nix/store/0lz6q8yk7i151pkdqb9zdr2mrhkda3ql-unzip-6.0/bin:/nix/store/w1jm2iawkxwi301gkp58zm9v6c9b78yk-file-5.40/bin:/nix/store/9k3gs858f4q9vj328nkpfhydps34mhmx-zip-3.0/bin:/nix/store/s66brsrfcajp0m8yhpfrmk2c2q4h8b7p-python-2.7.18/bin:/nix/store/bvsn3pwjpajrdf104zgxbf937wqpzwbr-python3-3.9.6/bin \
    PWD=/proc/self/cwd \
  /nix/store/67ik3kdijgfk32g3438998z7v7z0y022-cctools-port-949.0.1/bin/ar @bazel-out/darwin_arm64-opt-exec-EDC14992/bin/external/com_google_protobuf/libprotoc_lib.a-2.params)
Execution platform: //:default_host_platform
[102 / 169] 7 actions running
    Compiling src/google/protobuf/descriptor.cc; 1s local
    Compiling src/google/protobuf/util/message_differencer.cc; 0s local
    Compiling src/google/protobuf/duration.pb.cc; 0s local
    Compiling src/google/protobuf/util/internal/utility.cc; 0s local
    Compiling src/google/protobuf/util/time_util.cc; 0s local
    @com_google_protobuf//:protobuf; 0s local
    @com_google_protobuf//:protobuf; 0s local
usage:  ar -d [-TLsv] archive file ...
        ar -m [-TLsv] archive file ...
```

**Comment by uri-canva** [comment]
Yeah it's not a regression, `4.1.0` doesn't build at all on m1, so `4.2.1` is better even if the examples don't build, because the main package builds fine at least, and we can skip building the examples on m1.

**Review by uri-canva — APPROVED** [review]

**Comment by uri-canva** [comment]
ping @Profpatsch @mboes

**Comment by bobby285271** [comment]
Result of `nixpkgs-review pr 136004` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>bazel_4</li>
  </ul>
</details>

**Pull request merged**
