### PR TITLE
db-backup: init at 1.0

### PR DESCRIPTION
**Pull request by Br1ght0ne**
###### Motivation for this change
https://github.com/infostreams/db/releases/tag/1.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/75493)

### CODE REVIEW

**Comment by aanderse** [comment]
@filalex77 you'll need to test this first.

**Comment by aanderse** [comment]
@filalex77 ping

**Comment by filalex77** [comment]
@aanderse Seems to work under `nixpkgs-review` with my local MySQL installation. At least the `export/import` bits.

**Comment by aanderse** [comment]
@filalex77 I'm just trying to figure out how this program can work in a pure environment when the package has no reference to `mysql` :man_shrugging:

**Comment by aanderse** [comment]
FYI I also see references to at least `curl`, `php`, and `python` in the source.

**Comment by Br1ght0ne** [comment]
I was not able to make it build, and not interested in trying.

**Pull request closed without merging**
