### PR TITLE
mbpfan: improve description, resolves #32266

### LINKED ISSUE #32266: rename mbpfan to macfan
It does not only work on MacBook Pros, but also on Macbooks and probably other Mac hardware.

So i suggest to rename it to macfan, similar to thinkfan.

cc @cstrahan

### PR DESCRIPTION
**Pull request by lukateras**
###### Motivation for this change

See #32266. /cc @davidak

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

(sorry for the noise, master was broken by a merge)

**Comment by davidak** [comment]
@yegortimoshenko i would also put "on all MacBook/MacBook Pros (probably all Apple computers)" and "using the applesmc module" in the description. That might be keywords people search for.

See https://github.com/dgraziotin/mbpfan

**Comment by yegortimoshenko** [comment]
I don't like copying description from upstream :-)

I've checked `mbpfan` source code and all it relies on is `applesmc` module, which is indeed present in all Macs and MacBooks. I've ended up with "mbpfan, fan controller daemon for Apple Macs and MacBooks".

**Comment by yegortimoshenko** [comment]
I've tried `nixos-rebuild` with this patch and it still evaluates.

**Pull request merged**
