### PR TITLE
luaPackages.middleclass: init at 4.1.1-0

### PR DESCRIPTION
**Pull request by tmillr**
This is my first pr to nixpkgs! Bare with me

## Description of changes

Add Lua package https://luarocks.org/modules/kikito/middleclass

## Some things to note

- This is a basic, "pure lua", lib with no deps that appears to have been around awhile (and seems fairly popular).
- This lua module consists of just a single file named `middleclass.lua` which is located in the root of the repo. Hopefully this doesn't cause issues when used with neovim?
- I didn't implement tests/testing (checks?), not sure if this is necessary? I believe the repo does have tests and [uses busted](https://github.com/kikito/middleclass#specs).
- [x] Still need to run update script to generate the nix expressions? But it keeps failing on me with a different error each time. **(edit: nix expression/drv was added manually, see below)**

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
@OfBorg eval

**Comment by teto** [comment]
The updater is kinda tricky at the moment as you have noticed. You can generate the nix code by running luarocks-nix https://github.com/nix-community/luarocks-nix `luarocks nix middleclass`. It seems to fail though. I have a bunch of fixes in different related areas and I was planning to run an update of the lua package set this week  so if you dont mind I can do it in your stead this week ?

**Comment by tmillr** [comment]
> You can generate the nix code by running luarocks-nix https://github.com/nix-community/luarocks-nix `luarocks nix middleclass`. It seems to fail though.

I can actually get it to generate with that cmd (via `nix shell nixpkgs#luarocks-nix -c luarocks nix middleclass`):

```nix
{ luaOlder, buildLuarocksPackage, fetchurl, lua }:
buildLuarocksPackage {
  pname = "middleclass";
  version = "4.1.1-0";
  knownRockspec = (fetchurl {
    url    = "mirror://luarocks/middleclass-4.1.1-0.rockspec";
    sha256 = "10xzs48lr1dy7cx99581r956gl16px0a9gbdlfar41n19r96mhb1";
  }).outPath;
  src = fetchurl {
    url    = "https://github.com/kikito/middleclass/archive/v4.1.1.tar.gz";
    sha256 = "11ahv0b9wgqfnabv57rb7ilsvn2vcvxb1czq6faqrsqylvr5l7nh";
  };

  disabled = (luaOlder "5.1");
  propagatedBuildInputs = [ lua ];

  meta = {
    homepage = "https://github.com/kikito/middleclass";
    description = "A simple OOP library for Lua";
    license.fullName = "MIT";
  };
}
```

Maybe it's working for me because my local nix installation is on unstable (instead of master)?

Although it seems to have a slightly different structure compared to what the mass-updater outputs? For example, here's the previous commit affecting the Lua pkg list/csv: https://github.com/NixOS/nixpkgs/commit/895d66d915f66d75a610294515b3c7da506c0444

---

> if you dont mind I can do it in your stead this week ?

That's totally fine by me, whatever works.

I'll include what I've got for now. It appears to build just fine and can be `required` in the lua repl.

This lua module consists of just a single file named `middleclass.lua` which is located in the root of the repo. Hopefully this doesn't cause issues when used with neovim?

**Comment by teto** [comment]
great ty. Format will get updated with https://github.com/NixOS/nixpkgs/pull/258819

**Pull request merged**
