### PR TITLE
bazel: use bash with fallback $PATH consisting of basic shell utils

### LINKED ISSUE #265040: bazel cannot be used for remote builds
### Describe the bug

I'm trying to use `bazel_6` from nixpkgs on my laptop and use remote builders (buildbarn).
This fails due to patches that are applied in nixpkgs.

Vanilla Bazel has a hardcoded fallback path for bash (`/bin/bash`) [^1][^2]. This path is used to invoke shell actions (`ctx.actions.run_shell`). On NixOS, this obviously doesn't work (`/bin/bash` doesn't exist). This is why Bazel from nixpkgs [replaces this hardcoded path with a bash from nixpkgs](https://github.com/NixOS/nixpkgs/blob/b8b46961cce1b22e23e804b80be6dc5f29cc1375/pkgs/development/tools/build-managers/bazel/bazel_6/default.nix#L418-L427).

This has the downside of not producing a working fallback for `$PATH` (bash from nixpkgs will default initialize `$PATH` as `/no-such-path`). The workaround for this is to default initialize the path variables somewhere else. Currently, this is done [here](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/tools/build-managers/bazel/bazel_6/actions_path.patch).

This works fine for local execution, since this is where this function is called. However, this function is never called for remote execution (it is a hack to override things for the local execution environment only). So when using Bazel from nixpkgs locally and enabling remote execution, the shell is set to a bash from nixpkgs during the analysis phase but the `$PATH` variable is explicitly left unset by many actions, leading to the PATH in bash being `/no-such-path` and resulting in `no such file or directory` errors when executing tools in a script.

I think there are two possible solutions:

- when using remote execution, do not replace the hardcoded `/bin/bash` (this is probably not a great fix since it only works for FHS executors)
- instead of replacing `/bin/bash` with a regular bash from nixpkgs, add a little helper script that adds shell utils to `$PATH`. This way, any shell rule created by bazel has a minimal set of tools.
- use `--shell_executable=/bin/bash` when turning on remote execution. This has the downside of only working when the remote builder has a shell in that path.

### Steps To Reproduce

See this for a detailed reproducer: https://github.com/tweag/rules_nixpkgs/issues/439

### Expected behavior

Using bazel from nixpkgs should work with remote execution.

### Additional context

Using this version of bazel with remote execution is becoming more viable due to https://github.com/tweag/rules_nixpkgs.

### Notify maintainers

@mboes
@marsam
@uri-canva
@cbley
@olebedev
@groodt
@aherrmann
@ylecornec

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.9, NixOS, 23.05 (Stoat), 23.05.20231027.1a3c95e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - nixpkgs: `/nix/store/lqfbzmwwanrvbvgsvxa5jbmjbhm5aygr-source`
```

[^1]: https://github.com/bazelbuild/bazel/blob/37d95846d3258da81c690d4693f1604f5d28087d/src/main/java/com/google/devtools/build/lib/bazel/rules/BazelRuleClassProvider.java#L168
[^2]: https://github.com/bazelbuild/bazel/blob/37d95846d3258da81c690d4693f1604f5d28087d/src/main/java/com/google/devtools/build/lib/bazel/rules/BazelRuleClassProvider.java#L219-L223

### PR DESCRIPTION
**Pull request by malt3**
## Description of changes

Fixes #265040. Ensure any shell action has a minimal set of tools available (even for remote builds).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by uri-canva — APPROVED** [review]
Sounds ok to me.

**Review by olebedev — APPROVED** [review]
LGTM 👍

**Comment by mweinelt** [comment]
Bisect thinks this change broke `python311.pkgs.jaxlib`.

```
3576806d7edc615b2e89ee4f845d67c5b6c7ecc1 is the first bad commit
commit 3576806d7edc615b2e89ee4f845d67c5b6c7ecc1
Author: Malte Poll <1780588+malt3@users.noreply.github.com>
Date:   Thu Nov 2 13:13:00 2023 +0100

    bazel: use bash with fallback $PATH consisting of basic shell utils

 .../tools/build-managers/bazel/bazel_6/default.nix  | 21 ++++++++++++++++-----
 1 file changed, 16 insertions(+), 5 deletions(-)
bisect found first bad commit
```

```
bazel-build-jaxlib> building '/nix/store/dap85k2hizfk5wyg9qxcr95w06ig3307-bazel-build-jaxlib-0.4.19.drv'
bazel-build-jaxlib> unpacking sources
bazel-build-jaxlib> unpacking source archive /nix/store/j4bkh2nlm62pjxp7is00g2bcp608xb2b-source
bazel-build-jaxlib> source root is source
bazel-build-jaxlib> patching sources
bazel-build-jaxlib> updateAutotoolsGnuConfigScriptsPhase
bazel-build-jaxlib> configuring
bazel-build-jaxlib> no configure script, doing nothing
bazel-build-jaxlib> building
bazel-build-jaxlib> Extracting Bazel installation...
bazel-build-jaxlib> INFO: Options provided by the client:
bazel-build-jaxlib>   Inherited 'common' options: --isatty=1 --terminal_columns=0
bazel-build-jaxlib> INFO: Reading rc options for 'run' from /build/source/.bazelrc:
bazel-build-jaxlib>   Inherited 'common' options: --experimental_repo_remote_exec
bazel-build-jaxlib> INFO: Reading rc options for 'run' from /nix/store/v9x5zmj6ai0c5vjiv4yfjb0nqafiiga2-bazel-rc:
bazel-build-jaxlib>   Inherited 'build' options: --distdir=/nix/store/m8y1s64j25am1b60ihzk11wprr2wmjra-bazel-deps --extra_toolchains=@bazel_tools//tools/jdk:nonprebuilt_toolchain_definition --tool_java_runtime_version=local_jdk_11 --java_runtime_version=local_jdk_11
bazel-build-jaxlib> INFO: Reading rc options for 'run' from /build/source/.bazelrc:
bazel-build-jaxlib>   Inherited 'build' options: --nocheck_visibility --apple_platform_type=macos --macos_minimum_os=10.14 --announce_rc --define open_source_build=true --spawn_strategy=standalone --enable_platform_specific_config --experimental_cc_shared_library --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true --define=tsl_link_protobuf=true -c opt --config=short_logs --copt=-DMLIR_PYTHON_PACKAGE_PREFIX=jaxlib.mlir. --@xla//xla/python:enable_gpu=false
bazel-build-jaxlib> INFO: Reading rc options for 'run' from /build/source/.jax_configure.bazelrc:
bazel-build-jaxlib>   Inherited 'build' options: --strategy=Genrule=standalone --repo_env PYTHON_BIN_PATH=/nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/bin/python --action_env=PYENV_ROOT --python_path=/nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/bin/python --distinct_host_configuration=false --define PROTOBUF_INCLUDE_PATH=/nix/store/5prkzfpsimriksa691j4ip7w90gn4ca7-protobuf-3.24.3/include --config=mkl_open_source_only
bazel-build-jaxlib> INFO: Found applicable config definition build:short_logs in file /build/source/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
bazel-build-jaxlib> INFO: Found applicable config definition build:mkl_open_source_only in file /build/source/.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
bazel-build-jaxlib> INFO: Found applicable config definition build:linux in file /build/source/.bazelrc: --config=posix --copt=-Wno-unknown-warning-option --copt=-Wno-stringop-truncation --copt=-Wno-array-parameter
bazel-build-jaxlib> INFO: Found applicable config definition build:posix in file /build/source/.bazelrc: --copt=-fvisibility=hidden --copt=-Wno-sign-compare --cxxopt=-std=c++17 --host_cxxopt=-std=c++17
bazel-build-jaxlib> Loading: 
bazel-build-jaxlib> DEBUG: /build/output/external/xla/third_party/repo.bzl:132:14: 
bazel-build-jaxlib> Warning: skipping import of repository 'llvm-raw' because it already exists.
bazel-build-jaxlib> Loading: 
bazel-build-jaxlib> Loading: 1 packages loaded
bazel-build-jaxlib> Analyzing: target //jaxlib/tools:build_wheel (2 packages loaded, 0 targets configured)
bazel-build-jaxlib> Analyzing: target //jaxlib/tools:build_wheel (65 packages loaded, 392 targets configured)
bazel-build-jaxlib> Analyzing: target //jaxlib/tools:build_wheel (189 packages loaded, 8992 targets configured)
bazel-build-jaxlib> INFO: Analyzed target //jaxlib/tools:build_wheel (200 packages loaded, 13198 targets configured).
bazel-build-jaxlib> INFO: Found 1 target...
bazel-build-jaxlib> [0 / 20] [Prepa] BazelWorkspaceStatusAction stable-status.txt ... (2 actions, 1 running)
bazel-build-jaxlib> ERROR: /build/output/external/local_config_python/BUILD:78:8: Executing genrule @local_config_python//:python_include failed: (Exit 1): bash failed: error executing command (from target @local_config_python//:python_include) /nix/store/j2l90z41r5c85zpfbj91dsxycm6mm8s9-bash/bin/bash -c ... (remaining 1 argument skipped)
bazel-build-jaxlib> src/main/tools/process-wrapper-legacy.cc:80: "execvp(/nix/store/j2l90z41r5c85zpfbj91dsxycm6mm8s9-bash/bin/bash, ...)": No such file or directory
bazel-build-jaxlib> ERROR: /build/output/external/xla/third_party/py/numpy/BUILD:16:8: Executing genrule @xla//third_party/py/numpy:dummy failed: (Exit 1): bash failed: error executing command (from target @xla//third_party/py/numpy:dummy) /nix/store/j2l90z41r5c85zpfbj91dsxycm6mm8s9-bash/bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; touch bazel-out/k8-opt/bin/external/xla/third_party/py/numpy/tf_numpy_dummy.py'
bazel-build-jaxlib> src/main/tools/process-wrapper-legacy.cc:80: "execvp(/nix/store/j2l90z41r5c85zpfbj91dsxycm6mm8s9-bash/bin/bash, ...)": No such file or directory
bazel-build-jaxlib> Target //jaxlib/tools:build_wheel failed to build
bazel-build-jaxlib> Use --verbose_failures to see the command lines of failed build steps.
bazel-build-jaxlib> INFO: Elapsed time: 4.378s, Critical Path: 0.03s
bazel-build-jaxlib> INFO: 57 processes: 57 internal.
bazel-build-jaxlib> FAILED: Build did NOT complete successfully
bazel-build-jaxlib> ERROR: Build failed. Not running target
bazel-build-jaxlib> 
error: builder for '/nix/store/dap85k2hizfk5wyg9qxcr95w06ig3307-bazel-build-jaxlib-0.4.19.drv' failed with exit code 1;
```

**Comment by bjornfor** [comment]
Revert PR here: https://github.com/NixOS/nixpkgs/pull/266842

**Comment by malt3** [comment]
> bazel-build-jaxlib> src/main/tools/process-wrapper-legacy.cc:80: "execvp(/nix/store/j2l90z41r5c85zpfbj91dsxycm6mm8s9-bash/bin/bash, ...)": No such file or directory

I'm pretty sure this is my `bashWithDefaultShellUtils`. I forgot properly add it as a buildInput of Bazel so it wasn't guaranteed to be available at runtime when `bazel` for other derivations.

**Pull request merged**
