### PR TITLE
fluidsynth: 2.0.6 -> 2.2.0

### PR DESCRIPTION
**Pull request by evenbrenden**
###### Motivation for this change

Package update.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 120560` at 25e217b4 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>26 packages marked as broken and skipped:</summary>
  <ul>
    <li>beret</li>
    <li>frogatto</li>
    <li>gnome3.gnome-books</li>
    <li>gnome3.gnome-documents</li>
    <li>gnunet-gtk</li>
    <li>gtkd</li>
    <li>impressive</li>
    <li>libsForQt512.dragon</li>
    <li>libsForQt512.elisa</li>
    <li>libsForQt512.kamoso</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/9ccffa8ac586fc19b2e78d5fa67b744e">lincity_ng</a></li>
    <li><a href="https://gist.github.com/fef2fdfbf4fb7828a8b9e1ff8b83e1a3">tennix</a></li>
  </ul>
</details>
<details>
  <summary>335 packages skipped due to time constraints:</summary>
  <ul>
    <li>_1oom</li>
    <li>_20kly</li>
    <li>adapta-gtk-theme</li>
    <li>almanah</li>
    <li>apostrophe</li>
    <li>aravis</li>
    <li>asc</li>
    <li>astroid</li>
    <li>audacious (audaciousQt5)</li>
    <li>balsa</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>78 packages built successfully:</summary>
  <ul>
    <li>SDL2_mixer</li>
    <li>SDL_mixer</li>
    <li>abuse</li>
    <li>audio-recorder</li>
    <li>augustus</li>
    <li>ballAndPaddle</li>
    <li>baresip</li>
    <li>brasero</li>
    <li>brasero-original</li>
    <li>byzanz</li>
    <li>cdogs-sdl</li>
    <li>chromium-bsu</li>
    <li>cuyo</li>
    <li>devilutionx</li>
    <li>enlightenment.rage</li>
    <li>evince (gnome3.evince)</li>
    <li>farstream</li>
    <li>fluidsynth</li>
    <li>freedroid</li>
    <li>gav</li>
    <li>gl117</li>
    <li>gmrender-resurrect</li>
    <li>gnome-network-displays</li>
    <li>gnujump</li>
    <li>gscrabble</li>
    <li>gst_all_1.gst-editing-services</li>
    <li>gst_all_1.gst-plugins-bad</li>
    <li>gst_all_1.gst-rtsp-server</li>
    <li>gst_all_1.gst-vaapi</li>
    <li>guile-sdl2</li>
    <li>haskellPackages.SDL-mixer</li>
    <li>haskellPackages.sdl2-mixer</li>
    <li>instead</li>
    <li>jumpnbump</li>
    <li>kmetronome</li>
    <li>lbreakout2</li>
    <li>libsForQt5.drumstick (libsForQt515.drumstick ,plasma5Packages.drumstick)</li>
    <li>libsForQt5.kamoso (libsForQt515.kamoso ,plasma5Packages.kamoso)</li>
    <li>libsForQt5.minuet (libsForQt515.minuet ,plasma5Packages.minuet)</li>
    <li>libsForQt5.phonon-backend-gstreamer (libsForQt515.phonon-backend-gstreamer ,plasma5Packages.phonon-backend-gstreamer)</li>
    <li>libsForQt5.phonon-backend-vlc (libsForQt515.phonon-backend-vlc ,plasma5Packages.phonon-backend-vlc)</li>
    <li>libsForQt512.phonon-backend-gstreamer</li>
    <li>libsForQt512.phonon-backend-vlc</li>
    <li>libsForQt514.kamoso</li>
    <li>libsForQt514.phonon-backend-gstreamer</li>
    <li>libsForQt514.phonon-backend-vlc</li>
    <li>libvlc</li>
    <li>ltris</li>
    <li>mailnag</li>
    <li>mamba</li>
    <li>mar1d</li>
    <li>meritous</li>
    <li>njam</li>
    <li>nxengine-evo</li>
    <li>onscripter-en</li>
    <li>pantheon.elementary-camera</li>
    <li>pantheon.elementary-videos</li>
    <li>parlatype</li>
    <li>pinball</li>
    <li>pithos</li>
    <li>pitivi</li>
    <li>python38Packages.pygame</li>
    <li>python38Packages.pysdl2</li>
    <li>python39Packages.pygame</li>
    <li>python39Packages.pysdl2</li>
    <li>qt-video-wlr</li>
    <li>qutebrowser</li>
    <li>rili</li>
    <li>sfrotz</li>
    <li>sound-juicer</li>
    <li>t4kcommon</li>
    <li>taisei</li>
    <li>teetertorture</li>
    <li>toppler</li>
    <li>trackballs</li>
    <li>tuxtype</li>
    <li>vectoroids</li>
    <li>xfce.parole</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

**Comment by evenbrenden** [comment]
`nixpkgs-review pr 120560` local run:
```
21 packages marked as broken and skipped:
beret frogatto gnome3.gnome-books gnome3.gnome-documents gnunet-gtk impressive libsForQt512.dragon libsForQt512.elisa libsForQt512.kamoso libsForQt512.kdenlive libsForQt512.minuet libsForQt512.soundkonverter libsForQt514.elisa libsForQt514.kdenlive odpdown openmodelica python38Packages.rl-coach python39Packages.rl-coach termplay tribler xmonad_log_applet

31 packages failed to build:
beneath-a-steel-sky broken-sword-25 cataclysm-dda-git citrix_workspace citrix_workspace_20_04_0 citrix_workspace_20_06_0 citrix_workspace_20_09_0 citrix_workspace_20_10_0 citrix_workspace_20_12_0 citrix_workspace_21_01_0 drascula-the-vampire-strikes-back dreamweb empathy flight-of-the-amazon-queen gnucash ib-controller lincity_ng liquidwar luakit lure-of-the-temptress minetime notes-up obs-ndi pantheon.notes-up qtads quodlibet-xine quodlibet-xine-full scummvm simutrans_binaries sladeUnstable worldofgoo

503 packages built:
SDL2_mixer SDL_mixer Sylk _1oom _20kly abbaye-des-morts abuse adapta-gtk-theme almanah anki-bin apostrophe appimage-run appimage-run-tests apple-music-electron aravis areca asc astroid audacious audio-recorder augustus aws-workspaces azureus ballAndPaddle balsa banking baresip betterdiscord-installer birdfont blobwars bookworm bottles brasero brasero-original bubblemail byzanz caerbannog calf calls cantoolz carla cataclysm-dda cawbird cdogs-sdl chocolateDoom chrome-gnome-shell chromium-bsu chrysalis cinnamon.cinnamon-common cinnamon.cinnamon-control-center cinnamon.cinnamon-gsettings-overrides cinnamon.cinnamon-screensaver claws-mail-gtk3 cog commandergenius crack_attack craftos-pc crawlTiles crispyDoom crrcsim crypto-org-wallet cuyo deltachat-electron denemo devdocs-desktop devilutionx dropbox-cli dxx-rebirth easyrpg-player eclipse-mat eclipses.eclipse-committers eclipses.eclipse-cpp eclipses.eclipse-java eclipses.eclipse-modeling eclipses.eclipse-platform eclipses.eclipse-rcp eclipses.eclipse-rust eclipses.eclipse-scala-sdk eclipses.eclipse-sdk eduke32 egoboo electronplayer elementary-planner endgame-singularity enigma enlightenment.rage eolie ephemeral epiphany eternity evince evolution evolution-data-server evolution-ews evolutionWithPlugins farstream fcitx5-gtk fcitx5-with-addons feedreader fish-fillets-ng flare flexoptix-app fluidsynth foliate folks font-manager formiko fractal freeciv freedink freedroid freedroidrpg frescobaldi frozen-bubble gajim gargoyle gav gcompris gemrb gfbgraph giara gjay gl117 glade glom gmrender-resurrect gnome-builder gnome-feeds gnome-keysign gnome-network-displays gnome-online-accounts gnome-passwordsafe gnome-photos gnome-podcasts gnome-recipes gnome-tour gnome-usage gnome3.aisleriot gnome3.bijiben gnome3.cheese gnome3.devhelp gnome3.file-roller gnome3.geary gnome3.gnome-applets gnome3.gnome-boxes gnome3.gnome-calendar gnome3.gnome-clocks gnome3.gnome-contacts gnome3.gnome-control-center gnome3.gnome-flashback gnome3.gnome-initial-setup gnome3.gnome-maps gnome3.gnome-music gnome3.gnome-online-miners gnome3.gnome-panel gnome3.gnome-screenshot gnome3.gnome-session gnome3.gnome-shell gnome3.gnome-software gnome3.gnome-sound-recorder gnome3.gnome-terminal gnome3.gnome-todo gnome3.gnome-tweaks gnome3.gnome-user-share grilo-plugins gnome3.gvfs libgdata libgepub libzapojit gnome3.nautilus gnome3.nautilus-python gnome3.polari gnome3.pomodoro gnome3.rygel gnome3.seahorse shotwell gnome3.sushi gnome3.totem tracker-miners webkitgtk yelp gnomeExtensions.easyScreenCast gnomeExtensions.gsconnect gnomeExtensions.night-theme-switcher gnujump gnvim gnvim-unwrapped gscrabble gst_all_1.gst-editing-services gst_all_1.gst-plugins-bad gst_all_1.gst-rtsp-server gst_all_1.gst-vaapi gthumb gtk4 gtkd guile-sdl guile-sdl2 haskellPackages.Raincat haskellPackages.SDL-mixer haskellPackages.piyo haskellPackages.reflex-dom haskellPackages.sdl2-mixer haskellPackages.webkit2gtk3-javascriptcore hedgewars hyperrogue instead instead-launcher ipscan irccloud ivan joplin-desktop julius jumpnbump keeweb kgx kicad-small kicad-unstable-small kmetronome kooha lbreakout2 lbry ledger-live-desktop lens liberal-crime-squad libhandy libreoffice libreoffice-fresh libreoffice-fresh-unwrapped libreoffice-qt libreoffice-unwrapped libretro.scummvm libsForQt5.dragon libsForQt5.drumstick libsForQt5.elisa libsForQt5.kamoso libsForQt5.kdenlive libsForQt5.minuet libsForQt5.phonon-backend-gstreamer libsForQt5.phonon-backend-vlc soundkonverter libsForQt5.telepathy libsForQt512.drumstick libsForQt512.phonon-backend-gstreamer libsForQt512.phonon-backend-vlc libsForQt512.telepathy libsForQt514.dragon libsForQt514.drumstick libsForQt514.kamoso libsForQt514.minuet libsForQt514.phonon-backend-gstreamer libsForQt514.phonon-backend-vlc libsForQt514.soundkonverter libsForQt514.telepathy libvlc liferea lightspark lispPackages.cl-webkit2 lispPackages.nyxt lollypop losslesscut-bin ltris lunar-client lutris lutris-free lutris-unwrapped mailnag mailnagWithPlugins mamba manaplus mapmap mar1d marker marktext mate.atril mate.mate-user-guide mavproxy megaglest meritous metadata-cleaner meteo midori-unwrapped minitube mmex molotov mopidy-iris mopidy-local mopidy-mopify mopidy-mpd mopidy-mpris mopidy-musicbox-webclient mopidy-scrobbler mopidy-somafm mopidy-soundcloud mopidy-spotify-tunigo mopidy-subidy mopidy-tunein mopidy-youtube mpd muse mycrypto nasc newsflash nheko njam notable np2kai nuclear nxengine-evo nyxt obs-gstreamer obs-move-transition obs-multi-rtmp obs-studio obs-v4l2sink obs-wlrobs octant-desktop odamex onboard onscripter-en opendune openlierox openttd openttd-jgrpp openxcom osmo p3x-onenote pantheon.elementary-calendar pantheon.elementary-camera pantheon.elementary-capnet-assist pantheon.elementary-code pantheon.elementary-greeter pantheon.elementary-gsettings-schemas pantheon.elementary-music pantheon.elementary-onboarding pantheon.elementary-photos pantheon.elementary-session-settings pantheon.elementary-videos pantheon.extra-elementary-contracts pantheon.switchboard-plug-a11y pantheon.switchboard-plug-onlineaccounts pantheon.switchboard-with-plugs pantheon.wingpanel-applications-menu pantheon.wingpanel-indicator-datetime pantheon.wingpanel-with-indicators parlatype pdfpc perl530Packages.SDL perl532Packages.SDL picard pidgin pidgin-carbons pidgin-latex pidgin-mra pidgin-msn-pecan pidgin-opensteamworks pidgin-osd pidgin-otr pidgin-sipe pidgin-skypeweb pidgin-window-merge pidgin-xmpp-receipts pika-backup pinball pingus pipelight pithos pitivi playonlinux plexamp pokerth pokerth-server portfolio portfolio-filemanager pragha prboom printrun pulseeffects-legacy pulseeffects-pw purple-discord purple-facebook purple-hangouts purple-lurch purple-matrix purple-plugin-pack purple-slack purple-vk-plugin purple-xmpp-http-upload pympress pysolfc python38Packages.kicad python38Packages.kivy python38Packages.mido python38Packages.pygame python38Packages.pygame_sdl2 python38Packages.pysdl2 python38Packages.python-vlc python38Packages.pytmx python38Packages.wxPython_4_0 python38Packages.wxPython_4_1 python39Packages.kicad python39Packages.kivy python39Packages.mido python39Packages.pygame python39Packages.pygame_sdl2 python39Packages.pysdl2 python39Packages.python-vlc python39Packages.pytmx python39Packages.wxPython_4_0 python39Packages.wxPython_4_1 pytrainer qgroundcontrol qsynth qt-video-wlr quilter quisk quodlibet quodlibet-full quodlibet-without-gst-plugins qutebrowser radicle-upstream radiotray-ng rambox-pro reaper rednotebook remmina renpy retrofe rili rocksndiamonds rrootage run-scaled sayonara setzer sfrotz shortwave skype4pidgin slade sound-juicer sparkleshare ssb-patchwork standardnotes station steam-run-native strawberry subtitleeditor surf surf-display swt swt_jdk8 t4kcommon taisei tangram teetertorture telegram-purple telepathy-farstream telepathy-haze tennix tilix timeular tootle toppler toxprpl trackballs trezor-suite tunefish tusk tuxguitar tuxpaint tuxtype ulauncher ultrastardx unityhub unoconv vala-language-server vectoroids video2midi vimb-unwrapped vlc vmpk vocal vokoscreen-ng vuze wargus warmux webkit2-sharp wesnoth whatsapp-for-linux wine wine-staging wineWowPackages.full winetricks wootility xfce.parole xiphos xmoto xplayer xpra yaxg zandronum zdoom zettlr zod zulip
```

**Comment by evenbrenden** [comment]
The relevant breakages boils down to `scummvm` and `qtads` because 2.2.0 breaks ABI compatibility:

- https://github.com/scummvm/scummvm/pull/2915
- https://github.com/realnc/qtads/pull/14

These are both recently merged. Maybe just wait for new releases of these two and close this one for now? @cillianderoiste @lovek323

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by peterhoeg** [comment]
Wait, mine is later, sorry.

**Pull request closed without merging**
