### PR TITLE
mint: 0.5.0 -> 0.7.1

### PR DESCRIPTION
**Pull request by infinisil**
###### Motivation for this change
This also fixes the build with the latest crystal version

Don't backport this, 20.03 can be fixed without a version update

###### Things done

- [x] Built it successfully
- [x] Created a project and tested it

### CODE REVIEW

**Review by Br1ght0ne — CHANGES_REQUESTED** [review]
`nixpkgs-review` doesn't pass
```
[0 built (1 failed)]
error: build of '/nix/store/w80af30mcg32a4lrbxykwr3kisb87nyc-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/80391
1 package failed to build:
mint
```
This bug is fixed in #80390 
```
impure path `/homeless-shelter/.cache/crystal/build-source-lib-baked_file_system-src-loader.cr/macro_run' used in link
collect2: error: ld returned 1 exit status
```
So this should work with Crystal 0.33.0

**Comment by Infinisil** [comment]
@filalex77 Huh weird, both me and ofborg seem to be able to build it successfully on Linux. Or are you on Darwin perhaps?

**Comment by filalex77** [comment]
@Infinisil This ran on Ubuntu 18.04 with single-user Nix installed. I'll try to run it in a NixOS VM.

**Review by jonringer — APPROVED** [review]
diff LGTM
fixes broken build
shows usage

```
https://github.com/NixOS/nixpkgs/pull/80391
1 package built:
mint
```

**Pull request merged**
