### PR TITLE
darwin.postFixupSignHook: use absolute path to codesign_allocate

### PR DESCRIPTION
**Pull request by Smaug123**
###### Description of changes

This is https://github.com/NixOS/nixpkgs/pull/148282 but months later. I'm currently building `hello`, we're getting through Clang and Python first. (If it works, I'll squash the merge commit into the previous one.)

This is a massive sledgehammer, I don't know whether it's correct to allowlist these deps.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Smaug123** [comment]
https://github.com/ofborg build pkgsCross.aarch64-darwin.hello hello

**Comment by Smaug123** [comment]
@ofborg build pkgsCross.aarch64-darwin.hello hello

**Comment by Smaug123** [comment]
Phew, finally reproduced the original problem after 44mins of building:
```
error: output '/nix/store/0ybgf3i55fmcdm3m3kk4gbqla1f2ahzl-bootstrap-stage2-stdenv-darwin' is not allowed to refer to the following paths:
         /nix/store/fl3sghzfg8jhyx6zggl4cv15jzy2898w-libtapi-1100.0.11
         /nix/store/p5g5cgpzi74z7zwa0s2qfq0dkq9fwfp8-cctools-port-973.0.1
         /nix/store/vdi592m39p8ckb4b8x00c810r14cr8yy-ncurses-6.3-p20220507
```

**Comment by Smaug123** [comment]
OK, I am extremely out of my depth here, I can see effort being taken to avoid linking ncurses in stage 4 but after this change we want it in stage 2.

**Comment by tjni** [comment]
This should be superceded by https://github.com/NixOS/nixpkgs/pull/238323.

**Pull request closed without merging**
