### PR TITLE
Various fixes for apple frameworks

### PR DESCRIPTION
**Pull request by Mic92**
###### Motivation for this change

Extracted from https://github.com/NixOS/nixpkgs/pull/102306

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
cc @dasJ could you check if this breaks stdenv?

**Comment by dasJ** [comment]
Before I build for days without a usable result: `nix-review pr` without any other args?

**Comment by SuperSandro2000** [comment]
@Mic92 Can you rebase this?

**Comment by veprbl** [comment]
... on staging?

**Comment by jonringer** [comment]
some merge conflicts. Also, this now does 5000+ darwin rebuilds, please target staging

**Comment by Mic92** [comment]
Sorry. Don't have time to solve the merge conflicts.

**Pull request closed without merging**
