### PR TITLE
xserver: check that selected layout exists

### PR DESCRIPTION
**Pull request by lheckemann**
###### Motivation for this change
#5638

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- [x] Built on NixOS
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lheckemann** [comment]
I would have used `builtins.pathExists` rather than `builtins.readDir` + `builtins.hasAttr` but it complained that it (pathExists?) "cannot refer to other paths".

**Comment by abbradar** [comment]
This would force build-at-evaluation-time. You can instead add a `runCommand` to `system.extraDependencies`  that check this and fails.

**Comment by lheckemann** [comment]
Done that, thanks for the input!

**Comment by abbradar** [comment]
It fails on multi-layout setups:

```
Selected X11 keyboard layout (us,ru) does not exist.
```

**Comment by lheckemann** [comment]
Good catch, thanks. I'll fix both of those issues!

**Comment by lheckemann** [comment]
Fixed, hopefully!

**Comment by lheckemann** [comment]
Any more issues with this?

**Comment by 7c6f434c** [comment]
I think I actually use the full power of layout specification as in `layout = "us(altgr-intl),ru(common),gr(basic)";`

**Comment by lheckemann** [comment]
Are this layout specification format and its semantics documented properly anywhere?

**Comment by 7c6f434c** [comment]
Hm, maybe this is actually a legacy format because X.org guide 
recommends using the unreadable version with layouts and variants listed
separately.

**Pull request merged**
