### PR TITLE
zsh-syntax-highlighting: 0.7.1 -> 0.8.0

### PR DESCRIPTION
**Pull request by gepbird**
## Description of changes

diff: https://github.com/zsh-users/zsh-syntax-highlighting/compare/0.7.1...0.8.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

# Motivation
I'm migrating my arch config to nix, and noticed that I get this error with my zsh config:
`zsh-syntax-highlighting: unhandled ZLE widget 'zvm_readkeys_handler'`.
Minimal zsh config for reproducing:
```nix
home-manager.sharedModules = [
  {
    programs.zsh = {
      enable = true;
      syntaxHighlighting.enable = true;
      initExtra = ''
        source ${pkgs.zsh-vi-mode}/share/zsh-vi-mode/zsh-vi-mode.plugins.zsh
        # this binds the <end> key to end-of-line 
        # and causes the error message but only if old syntax highlighting is enabled
        zvm_bindkey viins '^[[4~' end-of-line
      '';
    }
  }
]
```
Using a newer version of zsh-syntax-highlighting (at least https://github.com/zsh-users/zsh-syntax-highlighting/commit/637e1c702e07b9a3cb76063d27e2118ed3ac1503) fixes the issue.

### CODE REVIEW

**Comment by gepbird** [comment]
Result of `nixpkgs-review pr 250009` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zsh-syntax-highlighting</li>
  </ul>
</details>

**Comment by gepbird** [comment]
Result of `nixpkgs-review pr 250009` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zsh-syntax-highlighting</li>
  </ul>
</details>

**Comment by DDoSolitary** [comment]
a stable 0.8.0 is available now: https://github.com/zsh-users/zsh-syntax-highlighting/releases/tag/0.8.0
the old syntax highlighting version is also incompatible with current version of zsh and causes weird issues: https://github.com/zsh-users/zsh-syntax-highlighting/issues/857

**Review by SebTM — APPROVED** [review]
Tested on latest unstable with zsh 5.9 (x86_64-pc-linux-gnu) - works fine ✌🏻 

Result of `nixpkgs-review pr 250009` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zsh-syntax-highlighting</li>
  </ul>
</details>

**Pull request merged**
