### PR TITLE
ocaml modules needed for XAPI (XenServer)

### PR DESCRIPTION
**Pull request by ts468**

### CODE REVIEW

**Comment by vbgl** [comment]
Most of [the comment to PR5529](https://github.com/NixOS/nixpkgs/pull/5529#issuecomment-80113221) still applies: thank you; there are evaluation error; attribute paths are redundant (`ocamlPackage.ocaml_omd`); several packages are already there.

**Comment by ts468** [comment]
@vbgl, thanks, I've renamed the packages, and tried to remove the duplicates.

Just for me, is there a quick way to evaluate and build all new packages of a commit at once?

**Comment by falsifian** [comment]
Maybe nox-review? I think that is what our Travis CI is using. https://github.com/madjar/nox

**Comment by ts468** [comment]
@vbgl, thank your very much for efforts of reviewing the new packages! I went through the list again and removed packages that are already in nixpkgs. I also tried to apply changes according to your comments.

Concerning the change from fetchurl to fetchFromGithub, is there a tool to do the conversion automatically, because there seem to be a lot of packages throughout nixpkgs that are affected?

Also, would you be fine with the changes in #8705 ?

**Comment by vbgl** [comment]
> Concerning the change from fetchurl to fetchFromGithub, is there a
> tool to do the conversion automatically

I’ve got no idea. I’d just do it lazily, when a package breaks or is
updated. Or when adding a new package.

> Also, would you be fine with the changes in #8705 ?

Not at all. It looks like a random and massive breaking of the nixpkgs API.

**Comment by ts468** [comment]
So would it be possible to change to fetchFromGithub lazily in further updates as well, just as there are so many packages involved to get XAPI in? Maybe at the same time the packages could be changed from stdenv.mkDerivation to buildOcaml as well.

About #8705, just for clarification, are you objecting the renaming in general, or just the way I went about doing it? In the first case, are there any naming guidelines that I could follow? In the second case, do you know of a way of introducing deprecation warnings for the old names and leave them as links to the new names?

**Comment by vbgl** [comment]
> So would it be possible to change to fetchFromGithub lazily in
> further updates as well, just as there are so many packages involved
> to get XAPI in?

Are you suggesting that there are too much packages involved in this PR
to go through all of them?

> do you know of a way of introducing deprecation warnings for
> the old names and leave them as links to the new names?

No (but there is a hint at the bottom of all-packages.nix). Maybe you
should ask on the mailing-list.

**Comment by rasendubi** [comment]
(triage) status?

**Comment by joachifm** [comment]
Closing as abandoned.

**Pull request closed without merging**
