### PR TITLE
v4l2loopback: Fix issue with buildEnv using bin output

### PR DESCRIPTION
**Pull request by L-as**
###### Motivation for this change

See https://github.com/NixOS/nixpkgs/pull/134311#issuecomment-901952544

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by L-as** [comment]
I don't get why this is needed. 
I couldn't figure out why this happens by looking at the [source code](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/buildenv/default.nix).

**Comment by frogamic** [comment]
I have tested by adding your change in `overrideAttrs` like so
```nix
extraModulePackages = [ (config.boot.kernelPackages.v4l2loopback.overrideAttrs (old: {
  outputsToInstall = [ "out" ];
}))];
```

And unfortunately I still don't get the kernel driver. I wonder if it would be easier (and more intuitive) to package the utils separately as `v4l2loopback-ctl`?

**Comment by frogamic** [comment]
Sorry, just realised `outputsToInstall` should be in `meta`, can confirm this fixes the missing kernel module.

**Comment by billksun** [comment]
Can we have this merged ASAP? I am using v4l2loopack to use droidcam for video conferencing for my work-from-home setup. And it was kind of caught off-guard this morning when my camera stopped working.

**Comment by vcunat** [comment]
> I don't get why this is needed.

The default `outputsToInstall` value is defined in `pkgs/stdenv/generic/make-derivation.nix`

**Comment by vcunat** [comment]
The first output (`.bin` or `.out` by convention) is mainly relevant when using the package attribute in the nix language itself (without selecting output like `.dev`), but when installing into environments (primarily `nix-env`) you often want a different choice.  And for cases like `buildInputs` there's other default behavior, as you typically want `.dev` (which propagates others).

From the very beginning there's been quite some [documentation](https://nixos.org/manual/nixpkgs/stable/#sec-multiple-outputs-installing-nixos); feel free to suggest improvements for that.

**Comment by vcunat** [comment]
I'd suggest trying to find a different long-term solution than this PR.  `outputsToInstall` was designed for human envs; this way I think you'll be limiting availability of `v4l2loopback-ctl`.  Maybe `boot.extraModulePackages` should select default outputs differently (e.g. `pkgs.aggregateModules` generally).

**Comment by L-as** [comment]
@vcunat Can you explain why 293cd00df6990dfc0d8479724ccc80b10437918a shows different behavior? With this `aggregateModules` seems to use the `out` output for `v4l2loopback`.

**Comment by vcunat** [comment]
No, I'd think it makes that `buildEnv` empty and you get no modules.

**Comment by L-as** [comment]
But I tested it and it works. Perhaps my loca Nix is broken?

**Pull request merged**
