### PR TITLE
Kernel updates for 2023-10-07

### LINKED ISSUE #257159: NVMe Issues on recent kernels.
### Describe the bug

/dev/nvme0 becomes unavailable and causes / to unmount leading to an unresponsive system. 

<details><summary>Smartctl output</summary>

```
sudo smartctl -a /dev/nvme0
smartctl 7.3 2022-02-28 r5338 [x86_64-linux-6.5.5] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       Force MP600
Serial Number:                      [REDACTED]
Firmware Version:                   EGFM11.0
PCI Vendor/Subsystem ID:            0x1987
IEEE OUI Identifier:                0x6479a7
Total NVM Capacity:                 2,000,398,934,016 [2.00 TB]
Unallocated NVM Capacity:           0
Controller ID:                      1
NVMe Version:                       1.3
Number of Namespaces:               1
Namespace 1 Size/Capacity:          2,000,398,934,016 [2.00 TB]
Namespace 1 Formatted LBA Size:     512
Namespace 1 IEEE EUI-64:            6479a7 2161894542
Local Time is:                      Sun Sep 24 17:44:05 2023 CST
Firmware Updates (0x12):            1 Slot, no Reset required
Optional Admin Commands (0x0017):   Security Format Frmw_DL Self_Test
Optional NVM Commands (0x005d):     Comp DS_Mngmt Wr_Zero Sav/Sel_Feat Timestmp
Log Page Attributes (0x08):         Telmtry_Lg
Maximum Data Transfer Size:         512 Pages
Warning  Comp. Temp. Threshold:     70 Celsius
Critical Comp. Temp. Threshold:     90 Celsius

Supported Power States
St Op     Max   Active     Idle   RL RT WL WT  Ent_Lat  Ex_Lat
 0 +    10.73W       -        -    0  0  0  0        0       0
 1 +     7.69W       -        -    1  1  1  1        0       0
 2 +     6.18W       -        -    2  2  2  2        0       0
 3 -   0.0490W       -        -    3  3  3  3     2000    2000
 4 -   0.0018W       -        -    4  4  4  4    25000   25000

Supported LBA Sizes (NSID 0x1)
Id Fmt  Data  Metadt  Rel_Perf
 0 +     512       0         2
 1 -    4096       0         1

=== START OF SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

SMART/Health Information (NVMe Log 0x02)
Critical Warning:                   0x00
Temperature:                        55 Celsius
Available Spare:                    100%
Available Spare Threshold:          5%
Percentage Used:                    16%
Data Units Read:                    339,743,326 [173 TB]
Data Units Written:                 439,068,487 [224 TB]
Host Read Commands:                 11,765,950,011
Host Write Commands:                6,832,718,155
Controller Busy Time:               17,515
Power Cycles:                       2,923
Power On Hours:                     18,937
Unsafe Shutdowns:                   435
Media and Data Integrity Errors:    0
Error Information Log Entries:      2,690
Warning  Comp. Temperature Time:    59
Critical Comp. Temperature Time:    0

Error Information (NVMe Log 0x01, 16 of 63 entries)
Num   ErrCount  SQId   CmdId  Status  PELoc          LBA  NSID    VS
  0       2690     0  0x0008  0x4004  0x028            0     0     -
```
</details>

### Steps To Reproduce

NVMe + 6.5 kernel (either on main branch, staging-next branch, or staging-next + gnome branch)

### Expected behavior
Not like this UnU

### Screenshots

<details><summary>Error messages before rebooting</summary>

IMG20230924173611

IMG20230924173707
</details>

### Additional context

Related to #253418

Related to https://bbs.archlinux.org/viewtopic.php?id=288316
Related to https://discussion.fedoraproject.org/t/laptop-does-not-show-luks-password-prompt-as-nvme-fails-with-kernel-6-4-11-kernel-6-4-12/88622
Related to https://lore.kernel.org/lkml/30b69186-5a6e-4f53-b24c-2221926fc3b4@sapience.com/T/
Related to https://bugzilla.redhat.com/show_bug.cgi?id=2232838

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.5, NixOS, 23.11 (Tapir), 23.11.git.49bb21b4a2e5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos, nixos-small"`
 - channels(fabian): `"home-manager, nixos-19.03-19.03, nixos-19.09-19.09, nixos-20.03-20.03, nixos-20.09-20.09, nixos-21.05-21.05, nixos-21.11-21.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

hw-probe: https://linux-hardware.org/?probe=007bb33fbf

### PR DESCRIPTION
**Pull request by fabianhjr**
## Description of changes

Previous: #256915

Was upstreamed in 6.1 and 6.5 (still present in 6.4): https://github.com/NixOS/nixpkgs/pull/255824

Closes https://github.com/NixOS/nixpkgs/issues/257159

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabianhjr** [comment]
Building 6.5.6

**Comment by Kiskae** [comment]
https://github.com/NixOS/nixpkgs/pull/254723 should be merged together with this PR to combine rebuilds.

**Comment by fabianhjr** [comment]
Built 6.5.6, rebooting in a bit

**Comment by lf-** [comment]
For the record I'm the upstream tester of the final regression patch on 6.1 and it does work on my machine. I can build these and test them soon as well but I don't expect issues.

**Comment by fabianhjr** [comment]
6.4 probably should be removed, there is also a pending RT update for 6.1 and those two would be the only two remaining places were the patch is being applied.

**Comment by RaitoBezarius** [comment]
> For the record I'm the upstream tester of the final regression patch on 6.1 and it does work on my machine. I can build these and test them soon as well but I don't expect issues.
> 
> I believe the patch was not applied to 6.4 due to EOL. Should we remove 6.4?

Drop being worked on in https://github.com/NixOS/nixpkgs/pull/258569.

**Comment by fabianhjr** [comment]
Only reference on the patch should be 6.1-rt now

**Comment by fabianhjr** [comment]
Rebooted int 6.5.6, working good. Attempting to get an nvme crash from https://github.com/NixOS/nixpkgs/issues/257159

**Comment by alyssais** [comment]
Please merge https://github.com/NixOS/nixpkgs/pull/254723 at the same time.

**Comment by K900** [comment]
Are we good to go here?

**Comment by fabianhjr** [comment]
Sure, though I was waiting for a review. UnU

**Comment by fabianhjr** [comment]
Also, haven't gotten an nvme crash so far, so seems the issue I had been experiencing on 6.5 series is fixed. :3

**Comment by Ma27** [comment]
Haven't had the time to do a review today, let alone from the other PRs that are rquested to be merged here. Unless someone's faster, I'll probably be able to do this tomorrow.

**Comment by fabianhjr** [comment]
fixed the hardened update script, pushing hardened updates to this branch as well.

**Comment by alyssais** [comment]
> Haven't had the time to do a review today, let alone from the other PRs that are rquested to be merged here.

When I ask for another PR to be merged, the only reason I haven't just merged it by myself is that I want to group the rebuilds.  I'm happy to take the blame for any consequences.

**Comment by fabianhjr** [comment]
Built and booted into 6.5.6-hardened1

Regarding https://github.com/NixOS/nixpkgs/pull/254723, sure can merge though I don't want to self merge this PR, specially without a review/approve. :C

On the other hand 6.5.6 does seem to fix nvme issues (other that those addressed by the rptx revert / patch in NixOS) so if there isn't any opposition I could merge both by end of day in Americas/Mexico_City timezone.

**Review by lf- — APPROVED** [review]
This message written from hardware that used to require the `dell_xps_regression` patch, running 6.5.6. Kernel seems to work for me.

**Comment by fabianhjr** [comment]
Merged both this and 254723

**Pull request merged**
