### PR TITLE
lib.types: chore use consistent payload form

### PR DESCRIPTION
**Pull request by hsjobeki**
Use `attributeSet` for `functor.payload` consistently. This reduces complexity and allows to move generic logic for payload handling out of the individual types.

`types.separatedString`
`types.enum`

Are the only ones that don't use attribute sets for their payload.

I'd like to introduce this convention. Maybe we should add a CI check.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by infinisil — APPROVED** [review]
Looked at it together with @hsjobeki in a call, LGTM with the release notes!

**Comment by PerchunPak** [comment]
`mergeEnums` is a use-case that this PR broke:

https://github.com/catppuccin/nix/blob/a817009ebfd2cca7f70a77884e5098d0a8c83f8e/modules/lib/default.nix#L133-L137
https://github.com/catppuccin/nix/blob/a817009ebfd2cca7f70a77884e5098d0a8c83f8e/modules/home-manager/cursor.nix#L12

Fix is:

```diff
-mergeEnums = a: b: lib.types.enum (a.functor.binOp a.functor.payload b.functor.payload);
+mergeEnums = a: b: lib.types.enum (a.functor.binOp a.functor.payload b.functor.payload).values;
```

**Comment by infinisil** [comment]
@PerchunPak Thanks for reaching out, we were thinking of that exact piece of code when discussing this PR! Since `.payload` is internal (for now), I don't recommend relying on it. Instead you can use this to merge types:
```
mergeEnums = a: b: a.typeMerge b.functor;
```

While `.typeMerge` and `.functor` are also somewhat internal, they can be expected to stay more stable.

**Comment by roberth** [comment]
Any reason not to add that to `lib`?

```nix
mergeTypes = a: b: a.typeMerge b.functor;
```

**Comment by infinisil** [comment]
Oh yeah, good idea

**Comment by hsjobeki** [comment]
> Any reason not to add that to `lib`?
> 
> ```nix
> mergeTypes = a: b: a.typeMerge b.functor;
> ```

Made a pr for that #364620

**Pull request merged**
