### PR TITLE
yarn: 1.0.1 -> 1.2.0

### PR DESCRIPTION
**Pull request by frontsideair**
###### Motivation for this change
Upstream release

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by zimbatm** [comment]
@frontsideair 1.2.1 just got released 4 hours ago. mind updating the PR?

**Comment by frontsideair** [comment]
Sure.

**Comment by frontsideair** [comment]
@zimbatm guess it's ready.

**Comment by jb55** [comment]
nit: I see two commits. rebase perhaps?

**Comment by frontsideair** [comment]
Done, thanks for feedback!

**Comment by zimbatm** [comment]
thanks!

**Pull request merged**
