### PR TITLE
irods-icommands: fixed version mismatch

### PR DESCRIPTION
**Pull request by bzizou**
###### Motivation for this change
Should fix build (https://hydra.nixos.org/build/59950343/nixlog/9)

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bzizou** [comment]
Should contribute to fix issue #28643

**Comment by joachifm** [comment]
All patches should go to master first, then be cherry-picked as needed.

**Comment by joachifm** [comment]
Hm, that didn't quite work the way I'd hoped ...

**Comment by bzizou** [comment]
Do you want me to create a new PR against the master branch?

**Comment by joachifm** [comment]
You can force push this branch or re-open, whichever is easier.

**Comment by bzizou** [comment]
Well, actually, it seems that this PR is obsolete: https://github.com/NixOS/nixpkgs/commit/5fb93524b3802ccdca7a560c232a1efb0056ba7f

**Comment by joachifm** [comment]
Seems like it. Thank you, anyway.

**Comment by joachifm** [comment]
@bzizou I've picked the commit in question to the release branch so should be fixed there as well.

**Pull request closed without merging**
