### PR TITLE
alterx: init at 0.0.1

### PR DESCRIPTION
**Pull request by fabaff**
###### Description of changes
Fast and customizable subdomain wordlist generator using DSL

https://github.com/projectdiscovery/alterx

Related to https://github.com/NixOS/nixpkgs/issues/81418

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by emilylange — COMMENTED** [review]
Pretty sure the update flags are broken
```
❯ result/bin/alterx -h
[...]

UPDATE:
   -up, -update                 update alterx to latest version
   -duc, -disable-update-check  disable automatic alterx update check
```

https://github.com/projectdiscovery/alterx/blob/29f4ad1576033f183f8e35757d09909a1a6ed57a/internal/runner/runner.go#L59-L62

Played a bit around with the version patched to `v0.0.0`
```diff
diff --git a/internal/runner/banner.go b/internal/runner/banner.go
index fa62427..0e42847 100644
--- a/internal/runner/banner.go
+++ b/internal/runner/banner.go
@@ -12,7 +12,7 @@ var banner = (`
 /_/ |_/_/\__/\__/_/ /_/|_|  				 
 `)
 
-var version = "v0.0.1"
+var version = "v0.0.0"
 
 // showBanner is used to show the banner to the user
 func showBanner() {

```

```
❯ echo "example.com" | result/bin/alterx

   ___   ____          _  __
  / _ | / / /____ ____| |/_/
 / __ |/ / __/ -_) __/>  <  
/_/ |_/_/\__/\__/_/ /_/|_|  				

		projectdiscovery.io

[INF] Current alterx version v0.0.0 (outdated)
```

```
❯ result/bin/alterx -update

   ___   ____          _  __
  / _ | / / /____ ____| |/_/
 / __ |/ / __/ -_) __/>  <  
/_/ |_/_/\__/\__/_/ /_/|_|  				

		projectdiscovery.io

[updater] update of alterx 0.0.0 -> 0.0.1 failed , insufficient permission detected got: open /nix/store/y38yl02j8mqp8lp3qb5l95pwaynxbxkd-alterx-0.0.1/bin/.alterx.check-perm: read-only file system
```

But I guess the same applies to most packages from https://github.com/projectdiscovery/ packaged in nixpkgs /shrug

Not blocking.

**Comment by tarunKoyalwar** [comment]
@IndeedNotJames , update flags in all tools of @projectdiscovery tools . tries to update binary itself . depending on how and where it is installed it needs sudo permissions.

Ex: installed using `go` => no need for sudo since $HOME/.go/bin is writable
      installed using pkg manager ex: apt => sudo is needed since /usr/bin is not writable to normal users
I think this is also case here ^

**Comment by IndeedNotJames** [comment]
@tarunKoyalwar thanks for chiming in!
You seem to be part of the @projectdiscovery org :)

This wasn't really a critique or anything.
Most updaters are just inherently incompatible with nix/nixpkgs.
I personally don't expect software to care how nixpkgs does stuff -- like at all.

But just to clarify: `/nix/store` is read-only, even with `sudo`/as `root`.

Some programs do however provide a compile flag to disable their updater (or replace it with a message like "_Installed via package manager; consult your package manager instead_").

Which is really handy for package managers, as you would usually not want to allow a package installed via a package manager to circumvent the very same package manager.
As it would undermine a lot of the reasons why one prefers to use a package manager in the first place.

And in the nixpkgs world, updaters are essentially guaranteed to be not working/broken anyway.
So that's in no way specific to @projectdiscovery^^

See for example https://github.com/NixOS/nixpkgs/pull/34127

It kinda depends on the pkgs maintainer here in nixpkgs for each package if they decide to manually patch-out updater.
At least that's my impression. I couldn't really find any discussions about this in the past https://github.com/NixOS/nixpkgs/pull/222269#pullrequestreview-1349673423

**Comment by tarunKoyalwar** [comment]
@IndeedNotJames , yeah, no worries It was not a critique from my end too , just wanted to know nixOs better we actually intend to use nixOs for our usecase https://github.com/projectdiscovery/gozero/issues/6 . so its great that pd tools are part of nixpkgs .

yeah it is known that maintainers do patch the update flags as we have seen it done with nuclei in kali , gitlab etc and we are ok with that and our goal is not replacing `package managers` so all good on that front , Thanks for the the compile flag / build tag suggestion . It seems like a great solution . I will raise the issue internally to check if we can do that . 

also @IndeedNotJames , does nixpkgs have some sort of automation to check/pull latest versions of packages . if so does it support a custom endpoint for pulling latest version of a tool

**Comment by IndeedNotJames** [comment]
> also @IndeedNotJames , does nixpkgs have some sort of automation to check/pull latest versions of packages . if so does it support a custom endpoint for pulling latest version of a tool

https://github.com/ryantm/nixpkgs-update (running under the bot account @r-ryantm) updates a lot.
See e.g. https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+projectdiscovery

 nixpkgs-update already supports 3 different update sources (repology, pypi and GitHub releases).
 Considering that @projectdiscovery seems to use GitHub releases, I don't think there's really a need to extend it with a custom endpoint :)
 
E.g. https://github.com/NixOS/nixpkgs/pull/224884 (logs for that run are at https://r.ryantm.com/log/interactsh/2023-04-05.log, in case you are interested) was done via the information provided at https://github.com/projectdiscovery/interactsh/releases

(Unless I misunderstood your question :sweat_smile:)

**Comment by tarunKoyalwar** [comment]
@IndeedNotJames , thanks !!

**Comment by fabaff** [comment]
The automatic update process work quite well in most cases, till it breaks :-)

So far, I haven't spent much thoughts on the update feature. Disabling/patching it would definitely improve the user experience as the feature is not working. At the other hand it doesn't break the installation or a like, simple spit out a error message or says that you are good go (e.g, `[INF] naabu is already updated to latest version`). Also, @r-ryantm and myself make sure that we ship updates in a timely manner, if possible. Thus, users should not be tempted to use `--update` at least on `unstable`. Looks different on stable releases, though.

My expectation is that users know to some extent what's the difference is between installing a tool manually and using a package manager. Especially about the implications that come with mixing package sources.

I'm happy to remove `--update` if the common consent is that every kind of update feature should be patched out.

**Pull request merged**
