### PR TITLE
deltachat-desktop: 1.28.2 -> 1.30.0

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
https://github.com/deltachat/deltachat-desktop/blob/v1.30.0/CHANGELOG.md

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 175488` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>44 packages failed to build:</summary>
  <ul>
    <li>balanceofsatoshis</li>
    <li>code-server</li>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>epgstation</li>
    <li>grafana-image-renderer</li>
    <li>iosevka</li>
    <li>n8n</li>
    <li>python310Packages.batchspawner</li>
    <li>python310Packages.dockerspawner</li>
    <li>python310Packages.jupyterhub</li>
    <li>python310Packages.jupyterhub-ldapauthenticator</li>
    <li>python310Packages.jupyterhub-systemdspawner</li>
    <li>python310Packages.jupyterhub-tmpauthenticator</li>
    <li>python310Packages.oauthenticator</li>
    <li>python39Packages.batchspawner</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.jupyterhub</li>
    <li>python39Packages.jupyterhub-ldapauthenticator</li>
    <li>python39Packages.jupyterhub-systemdspawner</li>
    <li>python39Packages.jupyterhub-tmpauthenticator</li>
    <li>python39Packages.oauthenticator</li>
    <li>slack</li>
    <li>teams</li>
    <li>theLoungePlugins.plugins.giphy</li>
    <li>thelounge</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vscode</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>vscode-fhs</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
    <li>vscodium-fhs</li>
    <li>whalebird</li>
    <li>zx</li>
  </ul>
</details>
<details>
  <summary>40 packages built:</summary>
  <ul>
    <li>antennas</li>
    <li>antora</li>
    <li>bitwarden-cli</li>
    <li>breitbandmessung</li>
    <li>castnow</li>
    <li>commitlint</li>
    <li>create-cycle-app</li>
    <li>deltachat-desktop</li>
    <li>fast-cli</li>
    <li>flexoptix-app</li>
    <li>flood</li>
    <li>google-clasp</li>
    <li>gtop</li>
    <li>hueadm</li>
    <li>hyperspace-cli</li>
    <li>imapnotify</li>
    <li>joplin</li>
    <li>lessc</li>
    <li>mastodon-bot</li>
    <li>morgen</li>
    <li>mx-puppet-discord</li>
    <li>node2nix</li>
    <li>openmoji-black</li>
    <li>openmoji-color</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pscid</li>
    <li>pulp</li>
    <li>pyright</li>
    <li>redoc-cli</li>
    <li>reveal-md</li>
    <li>shepherd</li>
    <li>shout</li>
    <li>sloc</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
    <li>triton</li>
    <li>vimPlugins.coc-go</li>
    <li>wasm-text-gen</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 175488` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>teleprompter</li>
    <li>timedoctor</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vimPlugins.markdown-preview-nvim</li>
  </ul>
</details>
<details>
  <summary>82 packages built:</summary>
  <ul>
    <li>antennas</li>
    <li>antora</li>
    <li>balanceofsatoshis</li>
    <li>bitwarden-cli</li>
    <li>breitbandmessung</li>
    <li>castnow</li>
    <li>code-server</li>
    <li>commitlint</li>
    <li>create-cycle-app</li>
    <li>deltachat-desktop</li>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>epgstation</li>
    <li>fast-cli</li>
    <li>flexoptix-app</li>
    <li>flood</li>
    <li>google-clasp</li>
    <li>grafana-image-renderer</li>
    <li>gtop</li>
    <li>hueadm</li>
    <li>hyperspace-cli</li>
    <li>imapnotify</li>
    <li>joplin</li>
    <li>lessc</li>
    <li>mastodon-bot</li>
    <li>morgen</li>
    <li>mx-puppet-discord</li>
    <li>n8n</li>
    <li>node2nix</li>
    <li>openmoji-black</li>
    <li>openmoji-color</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pscid</li>
    <li>pulp</li>
    <li>pyright</li>
    <li>python310Packages.batchspawner</li>
    <li>python310Packages.dockerspawner</li>
    <li>python310Packages.jupyterhub</li>
    <li>python310Packages.jupyterhub-ldapauthenticator</li>
    <li>python310Packages.jupyterhub-systemdspawner</li>
    <li>python310Packages.jupyterhub-tmpauthenticator</li>
    <li>python310Packages.oauthenticator</li>
    <li>python39Packages.batchspawner</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.jupyterhub</li>
    <li>python39Packages.jupyterhub-ldapauthenticator</li>
    <li>python39Packages.jupyterhub-systemdspawner</li>
    <li>python39Packages.jupyterhub-tmpauthenticator</li>
    <li>python39Packages.oauthenticator</li>
    <li>redoc-cli</li>
    <li>reveal-md</li>
    <li>shepherd</li>
    <li>shout</li>
    <li>slack</li>
    <li>sloc</li>
    <li>teams</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.plugins.giphy</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
    <li>thelounge</li>
    <li>triton</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-go</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vscode</li>
    <li>vscode-extensions.matklad.rust-analyzer (vscode-extensions.rust-lang.rust-analyzer)</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>vscode-fhs</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
    <li>vscodium-fhs</li>
    <li>wasm-text-gen</li>
    <li>whalebird</li>
    <li>zx</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
> <summary>1 package failed to build:</summary>
>  <ul>
>    <li>vimPlugins.markdown-preview-nvim</li>
>  </ul>

cc @Dettorer

**Comment by Dettorer** [comment]
@dotlambda I already fixed that in https://github.com/NixOS/nixpkgs/pull/175324/commits/833d7f8aed3396bb6c56f561a475898558f16113 but it got undone right after, here: https://github.com/NixOS/nixpkgs/commit/e47fff26cc89000efc72fb66aabda84b75218657#diff-804b42cd1947fd3a640c50cae6d373e26d08ac6a00c435e84d3773172aeea3abL110326.

**Comment by Dettorer** [comment]
Do you need me to do something? Re-applying that commit (while accounting for the line number change) should be enough.

**Comment by dotlambda** [comment]
> Re-applying that commit (while accounting for the line number change) should be enough.

It is not since that's not a permanent change. You have to fix it elsewhere, e.g. `pkgs/development/node-packages/overrides.nix`.

**Comment by Dettorer** [comment]
Oh my bad, I didn't realize I edited a generated file (even though it was clearly written on the first line…). I'm on it.

**Pull request merged**
