### PR TITLE
treewide: remove orphaned packages

### PR DESCRIPTION
**Pull request by kampka**
###### Motivation for this change
 Requested by @Mic92 in https://github.com/NixOS/nixpkgs/pull/109813#issuecomment-763541463

### CODE REVIEW

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
You need to add throw aliases for all of them and remove them from top level to make ofborg happy.

**Review by SuperSandro2000 — APPROVED** [review]

**Review by Ekleog — CHANGES_REQUESTED** [review]
@Mic92 I know you asked Kampka to do this, but IMO this is a bad idea as long as we don't have popcon-like information about which packages are used. For instance, I know that `mdadm` was maintainer-less when I noticed it had last been updated since a quite long time ago when looking into a bug, and at that time I “took over” maintainership (though in practice it's not like mdadm is very active a project anyway so I haven't been doing that much).

All that to say, IMO even orphaned packages have some potentially significant value, at least so long as there are no known security vulnerabilities in them — removing them when there's no longer any maintainer listed basically means that we decide that nixpkgs is only a distribution for people who do maintain packages.

**Comment by Mic92** [comment]
> @Mic92 I know you asked Kampka to do this, but IMO this is a bad idea as long as we don't have popcon-like information about which packages are used. For instance, I know that `mdadm` was maintainer-less when I noticed it had last been updated since a quite long time ago when looking into a bug, and at that time I “took over” maintainership (though in practice it's not like mdadm is very active a project anyway so I haven't been doing that much).
> 
> All that to say, IMO even orphaned packages have some potentially significant value, at least so long as there are no known security vulnerabilities in them — removing them when there's no longer any maintainer listed basically means that we decide that nixpkgs is only a distribution for people who do maintain packages.

They also create work if we do treewide refactoring i.e. updating a central library that might break some other packages i.e. https://github.com/NixOS/nixpkgs/pull/109113 I asked on discourse if anyone wants to keep any of these packages.

**Comment by kevincox** [comment]
I agree. I think we should remove them if no one is stepping up. The packages will still live on in Git and are trivial to add back if someone wants to step up at some point in the future.

**Comment by SuperSandro2000** [comment]
> Mic92 I know you asked Kampka to do this, but IMO this is a bad idea as long as we don't have popcon-like information about which packages are used. For instance, I know that `mdadm` was maintainer-less when I noticed it had last been updated since a quite long time ago when looking into a bug, and at that time I “took over” maintainership (though in practice it's not like mdadm is very active a project anyway so I haven't been doing that much).

mdadm is by default installed on other Distros and it is reasonable to assume that it is an important package unlike the ones that are removed here.

> All that to say, IMO even orphaned packages have some potentially significant value, at least so long as there are no known security vulnerabilities in them — removing them when there's no longer any maintainer listed basically means that we decide that nixpkgs is only a distribution for people who do maintain packages.

If you are using a package which lags a maintainer and it is to significant value to you than you should step up as a maintainer otherwise the package will degrade over time. We can't put the maintenance burden of maintainerless packages onto the community and fix time along side when doing major updates of other packages. Maintainers can take away some of the burden and fix packages quickly after they broke in nixpkgs-unstable and it is very important that people actually use those packages in their day to day live to find more indepth bugs which someone just checking if the program starts would have never found.

**Comment by aanderse** [comment]
I always thought an Ubuntu style "multiverse" repo would be a good solution to this problem. See this [discourse](https://discourse.nixos.org/t/contributor-retention/12412/19?u=aanderse) thread for additional discussion on the topic.

**Pull request closed without merging**
