### PR TITLE
rabbitmq-server: set explicit Elixir version to 1_12

### LINKED ISSUE #152576: rabbitmq-sever build error caused by rabbitmqctl does not support Elixir 1.13.1
### Describe the bug
rabbitmq-sever build error caused by rabbitmqctl does not support Elixir 1.13.1

### Steps To Reproduce
1. nix-shell -p rabbitmq-server

```console 
[user@system:~]$ nix-shell -p rabbitmq-server
...
Generated parallel_stream app
==> json
Compiling 13 files (.ex)
Generated json app
==> recon
Compiling 6 files (.erl)
Generated recon app
==> csv
Compiling 10 files (.ex)
Generated csv app
==> observer_cli
Compiling 13 files (.erl)
Generated observer_cli app
==> rabbitmqctl
** (Mix) You're trying to run :rabbitmqctl on Elixir v1.13.1 but it has declared in its mix.exs file it supports only Elixir >= 1.10.4 and < 1.13.0
make[2]: *** [Makefile:106: escript/rabbitmqctl] Error 1
make[2]: Leaving directory '/private/tmp/nix-build-rabbitmq-server-3.9.8.drv-1/rabbitmq-server-3.9.8/deps/rabbitmq_cli'
make[1]: *** [../../erlang.mk:4512: deps] Error 2
make[1]: Leaving directory '/private/tmp/nix-build-rabbitmq-server-3.9.8.drv-1/rabbitmq-server-3.9.8/deps/rabbit'
make: *** [erlang.mk:4512: deps] Error 2
error: builder for '/nix/store/9b3njwkp6vq2s6a6xj3981bm9bbrn20y-rabbitmq-server-3.9.8.drv' failed with exit code 2
```

### Expected behavior
rabbitmq-sever built and installed on the nix shell.

### Additional context
`elixir 1.13.1` was released in [December 14th](https://github.com/elixir-lang/elixir/releases/tag/v1.13.1) and `elixir nixpkg` was updated in [December 17th](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/interpreters/elixir/1.13.nix) but [RabbitMQ's rabbitmq-sever does not yet support Elixir 1.13.1](https://github.com/rabbitmq/rabbitmq-server/blob/4993fefa08fa0785385d23465d1f6de20bd4649c/deps/rabbitmq_cli/mix.exs#L14).
I am very new to NixOS project, so I am not sure how these conflicts are commonly resolved. I tried to build `rabbitmq-sever` with `elixir_1_12` and it built it successfully, just replacing `elixir` with `elixir_1_12` in rabbitmq_server'd [default.nix](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/servers/amqp/rabbitmq-server/default.nix).

### Notify maintainers
@turion 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.1.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(user): `"nixpkgs-22.05pre340506.5c37ad87222"`
 - nixpkgs: `/Users/user/.nix-defexpr/channels/nixpkgs`
```

### PR DESCRIPTION
**Pull request by keoko**
###### Motivation for this change
Fixes #152576

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by turion** [comment]
You can test the build and the integration test like this:

@ofborg build rabbitmq-server
@ofborg test rabbitmq

**Comment by turion** [comment]
Builds & tests pass! Awesome :)

Can you amend your commit so the message fits into the format as described here: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#submitting-changes

For example `rabbitmq-server: pin elixir_1_12`

**Comment by keoko** [comment]
@ofborg build rabbitmq-server
@ofborg test rabbitmq

**Comment by turion** [comment]
Thanks a lot!

**Pull request merged**
