### PR TITLE
Revert "ddclient: remove package and module on upstream maintainer request"

### PR DESCRIPTION
**Pull request by Majiir**
###### Description of changes

Reverts https://github.com/NixOS/nixpkgs/pull/241462. New application maintainers have stepped up (see https://github.com/ddclient/ddclient/issues/528#issuecomment-1642163043). @SuperSandro2000 no longer wishes to maintain the package, so I have added myself as maintainer.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by bjornfor — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Please wait for this until the next release and the broken caching is fixed or cherry-pick the commit for it.

**Comment by bjornfor** [comment]
> Please wait for this until the next release and the broken caching is fixed or cherry-pick the commit for it.

Issue link? (Are you saying ddclient is broken for everybody? I looked in my log, but it doesn't go back far enough to show ddclient actually making an ipaddr change -- it just checks and exits.)

**Comment by SuperSandro2000** [comment]
That should be it https://github.com/ddclient/ddclient/issues/431

I think at least one provider disabled an account because of this

**Comment by Majiir** [comment]
Closing as I'm no longer using `ddclient`.

**Comment by bjornfor** [comment]
Upstream has made a new release, so I picked this up again in https://github.com/NixOS/nixpkgs/pull/261241.

**Pull request closed without merging**
