### PR TITLE
passphrase2pgp: 1.2.1 -> 1.3.0, add check

### PR DESCRIPTION
**Pull request by KAction**

### CODE REVIEW

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 223114` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>passphrase2pgp</li>
  </ul>
</details>

**Comment by lucasew** [comment]
A simple test you can implement in the package definition (checkPhase)
```
passphrase2pgp -a  -u 1000 -i <(echo test) | md5sum
```

equals to ```6a239061fc8bc9d1c4b896d7423b922f```

**Comment by lucasew** [comment]
You can automate future bumps by using `nix-update-script` ([example](https://github.com/NixOS/nixpkgs/blob/master/pkgs/games/cbonsai/default.nix#L20))

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 223114` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>passphrase2pgp</li>
  </ul>
</details>

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 223114` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>passphrase2pgp</li>
  </ul>
</details>

**Review by lucasew — APPROVED** [review]

**Review by lucasew — APPROVED** [review]

**Comment by KAction** [comment]
@SuperSandro2000 Can you please merge this?

**Pull request merged**
