### PR TITLE
Leave the Determinate Systems community

### PR DESCRIPTION
**Pull request by danderson**
## Description of changes

Due to a clerical error on my part, it seems I accidentally joined the wrong community! I'm not quite sure how, but I ended up in the Determinate Systems community when I was looking for Nix. Thanks to https://determinate.systems/posts/on-community-in-nix/ for clearing up my confusion!

This does orphan a small number of packages, but I trust that the Determinate Systems community can work that out.

### CODE REVIEW

**Comment by roberth** [comment]
Just to be clear on this, only one shareholder of Determinate Systems is on the board of the NixOS foundation, and no individual has absolute authority over Nix, Nixpkgs or NixOS.

I will not try to negate any of the other issues here, but everyone deserves to know that at least some things are not as bad as they have been presented.

I am not affiliated with Determinate Systems.

If you're interested, here's [my perspective](https://functional.cafe/@roberth/112332724619849948) on things that were said about the Nix team. (Or CppNix team I guess?)

You are of course free to remove yourself from maintainership; no hard feelings.

**Comment by joepie91** [comment]
> and no individual has absolute authority over Nix, Nixpkgs or NixOS.

I imagine that this comment is more appropriately directed at Eelco, given their apparent attempt in the referenced blogpost to imply that Nix is a Determinate Systems project.

**Comment by danderson** [comment]
I'm confused by your statement. The chair of the foundation board published the link I quoted, and has made it very clear that this github organization, its community, and its future direction are the property of himself alone, and by extension his company Determinate Systems. Not, as I mistakenly thought previously, a collaboration of diverse contributors working to bring about a common ideal. My PR just corrects my mistake, while I go find that collaborative project I'd like to be a small part of.

If that post is not the consensus position, and the foundation chair does not have absolute ownership and authority over the project, why did the foundation chair say otherwise? Why did the foundation chair encourage people to migrate to community spaces that are under the sole control of Determinate Systems?

Looking at Github permissions, the board and its chair seem to hold complete administrative access over the organization. I'm given to understand this is also true of access to infrastructure beyond github. This does seem to indicate that the board has de-facto ultimate authority over the project, and through the chair have clarified how this project operates.

I would certainly be happy to be double-mistaken, as it were! It would save me quite a lot of work. But I don't see how your statement can be reconciled with the empirical ground truth?

**Comment by roberth** [comment]
> their apparent attempt in the referenced blogpost to imply that Nix is a Determinate Systems project.

That was very foolish of him, and certainly counterproductive for what appear to be his goals.

**Review by MostAwesomeDude — APPROVED** [review]

**Comment by roberth** [comment]
I may not be able to answer everything, but I'll try my best as a community member who's been around for a while, but has not been directly involved with the foundation, or moderation team, or infra team.

> The chair of the foundation board published the link I quoted, and has made it very clear that this github organization, its community, and its future direction are the property of himself alone, and by extension his company Determinate Systems.

This is for @edolstra to answer and I really don't want to do his dirty work, but I care about truth, so please bear with me while I share what I know. He's talked about creating these things and leading them, not owning them. Related, but certainly weaker than owning; no absolute power implied.

(skipping ahead and back if you don't mind:)

> Looking at Github permissions, the board and its chair seem to hold complete administrative access over the organization

The GitHub organization has four owners ([source](https://github.com/orgs/NixOS/people?query=role%3Aowner), not sure if accessible to everyone):
- Domen Kozar
- Rok Garbas
- Jonas Chevalier
- Eelco Dolstra

> If that post is not the consensus position, and the foundation chair does not have absolute ownership and authority over the project, why did the foundation chair say otherwise?

I believe he wasn't aware that people would read that into it. I would like him to make a statement refuting this.

> Why did the foundation chair encourage people to migrate to community spaces that are under the sole control of Determinate Systems?

I don't know the details of this. Is DetSys hosting something? I know https://discourse.nixos.org is hosted by Flying Circus, which is a respectable company. I've never heard of any drama involving them.
This seems like a solvable problem.

> I'm given to understand this is also true of access to infrastructure beyond github.

All I know is that we have a team whose work is quite transparent by having a public repo, where we can follow along. I don't know everyone's affiliation, but I recognize plenty non-DetSys handles there.
Example: https://github.com/NixOS/infra/issues/324

------

The community has largely self-organized into various structures such as the various teams, even before DetSys existed. These teams have most of these responsibilities and privileges that you care about. Any attempt to replace or hijack those would be foolish, leading to backlash *from the members of those teams*, which is not what has happened.

I hate to say it, but I can understand that sometimes activism can be more important than truth, to reach the _activation threshold_, but ultimately everyone should know the truth, which is the only reason I'm spending my time apparently trying to convince someone who, frankly speaking after a long week of both work and drama work I really shouldn't care about. Yet I do.

**Comment by 7c6f434c** [comment]
I think you misfiled this PR, given that the post you link clearly says that Nixpkgs community (this one) is not actually «run» by the Foundation or DetSys, and for DetSys communities there are links given (non of them going to https://github.com/NixOS ).

Obviously, everyone has an obvious right to stop maintainership of packages without owing anyone an explanation, but I wanted to inform you that the explanation you give looks inconsistent.

**Comment by danderson** [comment]
I won't reply point by point as this will turn into another forum debate, and goodness knows there's enough places for that already. I do appreciate you trying to defend what I personally feel has become indefensible, and I'm sorry to have caused you pain.

Where I disagree with you, I think, is on the impact of explicit vs. implicit power. The structures and teams you describe are nominal power structures, who _should_ have authority over things. I agree that those exist and have some amount of authority over their domain.

I am leaving because Eelco's publication states, in no uncertain terms, that an implicit power structure exists, one in which he and DetSys own the direction of the project. And that he is not only aware of this, but actively wishes to keep it so. This is not the first instance of stating or demonstrating this implicit power, and while I don't think it's the sole governance problem that exists, it is a chronic impediment to addressing any governance problem. It's the problem of unbalanced authority vs. responsibility, which sits at the core of many organizational collapses.

You are of course welcome to disagree with my reading. But I've been silently observing the growing governance crisis for a couple of years, and seen not just lack of progress, but repeated and deliberate blockading of progress on the simplest of steps. I was willing to assume good intent and allow time for change to happen, but that goodwill ran out for me with the post I linked. I don't think it's possible to avoid a collapse of the ecosystem any more, although I will continue to hope that I'm wrong.

> I don't know the details of this. Is DetSys hosting something?

Quoting from the post I linked:

> I remain committed to creating a community where everyone feels seen, heard, and valued, and I will not let unfounded accusations detract from this important work. I encourage everyone reading this who feels that they have not been heard or feels displaced to join the Determinate Systems community as we continue working to make Nix as easy to use and as impactful as possible. Our code of conduct is available [here](https://flakehub.com/policy/code-of-conduct), and you can join our Discord at https://determinate.systems/discord.

It's possible to read this and assume benign intent. But as the culmination of the last several years, I can't read this any other way than the foundation chair undermining existing community spaces in favor of his company's private space. You are, of course, welcome to read this another way.

---

> I wanted to inform you that the explanation you give looks inconsistent.

I decline to play the game you are proposing to play. Please do not interact with me further, unless it's to merge this PR so that we can all move on.

**Comment by edolstra** [comment]
@joepie91 

> I imagine that this comment is more appropriately directed at Eelco, given their apparent attempt in the referenced blogpost to imply that Nix is a Determinate Systems project.

I really don't see how you arrived at that interpretation, since my post *explicitly says the exact opposite*:

> The assertion that Determinate Systems “owns” Nix or seeks to exert outsized influence over the project, the community, or the foundation is patently false: I am the only member of the Nix team who works for Determinate Systems.

**Comment by nyabinary** [comment]
> @joepie91
> 
> > I imagine that this comment is more appropriately directed at Eelco, given their apparent attempt in the referenced blogpost to imply that Nix is a Determinate Systems project.
> 
> I really don't see how you arrived at that interpretation, since my post _explicitly says the exact opposite_:
> 
> > The assertion that Determinate Systems “owns” Nix or seeks to exert outsized influence over the project, the community, or the foundation is patently false: I am the only member of the Nix team who works for Determinate Systems.
> 
> @roberth
> 
> > Is DetSys hosting something?
> 
> I don't believe we are. You can see where all our infrastructure lives in the https://github.com/NixOS/infra repo.

Resign

**Comment by imincik** [comment]
> Just to be clear on this, only one shareholder of Determinate Systems is on the board of the NixOS foundation, and no individual has absolute authority over Nix, Nixpkgs or NixOS.
> 
> I will not try to negate any of the other issues here, but everyone deserves to know that at least some things are not as bad as they have been presented.
> 
> I am not affiliated with Determinate Systems.
> 
> If you're interested, here's [my perspective](https://functional.cafe/@roberth/112332724619849948) on things that were said about the Nix team. (Or CppNix team I guess?)
> 
> You are of course free to remove yourself from maintainership; no hard feelings.

@roberth , I think you should publish your post (my perspective) on Discourse. It is very well written. Thank you very much for that.

**Pull request merged**
