### PR TITLE
minizip2 -> minizip-ng: 2.10.6 -> 3.0.7

### PR DESCRIPTION
**Pull request by panicgh**
###### Description of changes

The repository has been moved. The old URL
https://github.com/nmoinvaz/minizip redirects to
https://github.com/zlib-ng/minizip-ng.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [X] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>linphone</li>
    <li>minizip2</li>
  </ul>
</details>

- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by panicgh** [comment]
Sorry for the mess. I changed the GitHub owner name, but forgot to rename the project minizip2 -> minizip-ng.

**Comment by panicgh** [comment]
Enable unit tests and set an alternative lib name, as suggested in #208013. I omitted `-DMZ_LIBCOMP=OFF`.

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>linphone</li>
    <li>minizip-ng</li>
  </ul>
</details>

**Comment by risicle** [comment]
On macos 10.15:

```
/tmp/nix-build-minizip-ng-3.0.7.drv-0/source/mz_strm_libcomp.c:16:10: fatal error: 'compression.h' file not found
#include <compression.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```

This is why I set `-DMZ_LIBCOMP=OFF`

**Comment by panicgh** [comment]
> On macos 10.15:

Thanks for testing. `-DMZ_LIBCOMP=OFF` added.

**Comment by risicle** [comment]
`nixpkgs-review` happy, macos 10.15 & nixos x86_64, though `pkgsStatic.minizip2` and `pkgsCross.aarch64-multiplatform.minizip2` look like they used to build and neither seem to for `minizip-ng`.  Partly my fault for adding the test-enablement. Possibly we should omit the test-related cmake flags if the tests are disabled, and disable the tests for static builds?

(can use the `finalAttrs` mechanism to discover the "final" decision as to whether tests are enabled or not, should save repeated logic?)

**Comment by panicgh** [comment]
A few minor improvements:
* Use an upstream commit which sets the default `MZ_SIGNING=OFF` instead of a manual override
* Make `BUILD_SHARED_LIBS` setting dependent on `stdenv.hostPlatform.isStatic`
* Move `MZ_LIBCOMP=OFF` to a conditional list dependent on `stdenv.hostPlatform.isDarwin`
* Switch tests ON/OFF depending on `doCheck`

I am not fully sure my understanding regarding `pkgsStatic` and `pkgsCross` is correct, but these observations may be related:
* `doCheck` is true only if the host platform [can be executed](https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/make-derivation.nix#L162) on the build platform
* Therefore for `pkgsCross`, `gtest` is never added to the `nativeBuildInputs` but the `cmakeFlags` still request to build the unit tests, cmake searches for gtest, and fails
  ```
  nix-repl> map (drv: drv.pname) pkgsCross.aarch64-multiplatform.minizip-ng.nativeBuildInputs
  [ "cmake" "aarch64-unknown-linux-gnu-pkg-config-wrapper" ]
  ```
* `pkgsStatic` can be executed and so `gtest` is added to `nativeBuildInputs`, but it seems to be of the wrong platform (build instead of host platform). This is correct for executables that need to be run on the build platform (e.g. cmake), but for libraries I would expect the host platform version (`"x86_64-unknown-linux-musl-gtest"`). There seems to be no way to specify this with `checkInputs`.
  ```
  nix-repl> map (drv: drv.pname) pkgsStatic.minizip-ng.nativeBuildInputs
  [ "cmake" "x86_64-unknown-linux-musl-pkg-config-wrapper" "gtest" ]
  ```

The tests build and run correctly, if `gtest` is moved from `checkInputs` to `buildInputs`.
In case of `pkgsCross`, `gtest` is correctly detected during the cmake configure phase (so `MZ_BUILD_TESTS` can stay `ON`), but the `checkPhase` is never executed because it is not supported for the host platform. `gtest` is not added to the runtime closure of the resulting pkg.
In case of `pkgsStatic`, the correct host platform's `gtest` is detected and used, tests are run successfully. But `gtest` is added to the closure of the resulting pkg.

```diff
diff --git a/pkgs/development/libraries/minizip-ng/default.nix b/pkgs/development/libraries/minizip-ng/default.nix
index 2d1b06271a0..16d08294a11 100644
--- a/pkgs/development/libraries/minizip-ng/default.nix
+++ b/pkgs/development/libraries/minizip-ng/default.nix
@@ -39,7 +39,7 @@ stdenv.mkDerivation rec {
   ];

   nativeBuildInputs = [ cmake pkg-config ];
-  buildInputs = [ zlib bzip2 xz zstd openssl ];
+  buildInputs = [ zlib bzip2 xz zstd openssl gtest ];

   cmakeFlags = [
     "-DBUILD_SHARED_LIBS=${if stdenv.hostPlatform.isStatic then "OFF" else "ON"}"
@@ -62,7 +62,6 @@ stdenv.mkDerivation rec {
   '';

   doCheck = true;
-  checkInputs = [ gtest ];
   enableParallelChecking = false;

   meta = with lib; {
```

An alternative is to disable unit tests whenever `buildPlatform != hostPlatform`, i.e. even if we could run them as for `pkgsStatic`. This defeats the purpose of the `canExecute` logic in make-derivation.nix, but appears to me to be the cleanest workaround for now.

```diff
diff --git a/pkgs/development/libraries/minizip-ng/default.nix b/pkgs/development/libraries/minizip-ng/default.nix
index 2d1b06271a0..1b85a54c0a2 100644
--- a/pkgs/development/libraries/minizip-ng/default.nix
+++ b/pkgs/development/libraries/minizip-ng/default.nix
@@ -61,7 +61,7 @@ stdenv.mkDerivation rec {
     fi
   '';

-  doCheck = true;
+  doCheck = stdenv.buildPlatform == stdenv.hostPlatform;
   checkInputs = [ gtest ];
   enableParallelChecking = false;
```

**Comment by risicle** [comment]
I think you've basically got it except you can probably make it a bit more robust by doing:

```patch
- stdenv.mkDerivation rec {
+ stdenv.mkDerivation (finalAttrs: rec {
```

and pulling `doCheck` from `finalAttrs`:

```patch
-    "-DMZ_BUILD_TESTS=${if doCheck then "ON" else "OFF"}"
+    "-DMZ_BUILD_TESTS=${if finalAttrs.doCheck then "ON" else "OFF"}"
```

**Review by risicle — APPROVED** [review]
Awesome, `pkgsStatic` & `pkgsCross` WFM now.

Maybe worth adding a clause to the `postInstall` to similarly symlink the `.a` file if it exists.

**Comment by panicgh** [comment]
Improve compat symlinks as suggested. Fix a broken symlink in the `pkgsStatic`-case (`-ng.so` -> `.so` while `.so` does not exist, because there is only `.a`).

**Comment by risicle** [comment]
I'm considering a different route for backports, and I don't think we can reasonably make this change to stable. Too many unknowns.

**Review by risicle — APPROVED** [review]
nixpkgs-review` happy, macos 10.15, nixos x86_64 & aarch64-linux. `pkgsStatic` & `pkgsCross.riscv64` build happily, aarch64-linux

**Pull request merged**
