### PR TITLE
fetchArchive: init

### PR DESCRIPTION
**Pull request by lukateras**
###### Motivation for this change

Even though `fetchzip` uses stdenv's `unpackFile` to unpack `.{tar{,.*},zip}` files, it doesn't expose any convenient way to extend it to handle anything other than that.

Additionally, `fetchzip`'s `stripRoot` goes beyond ignoring archive metadata/algorithm non-determinism and affects actual archive contents.

This is an attempt at a more explicit API that only fetches, then unpacks with one of `inputs`. It uses SRI hashes added in Nix 2.2 to avoid [code churn](https://github.com/NixOS/nixpkgs/blob/f44012ba10537e1a2a94b2be443a86e4dd0ad38f/pkgs/build-support/fetchurl/default.nix#L102-L108) that happens to algorithm-specific arg attrs as hash algorithms change.

`stripRoot` is implemented a la carte as a function that takes a directory and returns its first child.

Short list of changes:

- add `unpackCmd` hook to `dpkg`
- add SRI hash support to `fetchurl`
- add `fetchArchive` + docs
- showcase `fetchArchive` on `typora` derivation
- add `lib.stripRoot` + docs

Fetch examples:

```nix
fetchArchive {
  url = https://github.com/NixOS/nix/archive/2.2.1.tar.gz;
  hash = "sha512-U8y9gVgvjowXZ/lTp7fxqRrWFbxZwrbS4LY95XduiM2plvhQ37rJ5TACo/PHStCILSvhzHG19UBZ1bWP62jEgQ==";
}

fetchArchive {
  url = https://github.com/NixOS/nix/archive/2.2.1.zip;
  hash = "sha512-U8y9gVgvjowXZ/lTp7fxqRrWFbxZwrbS4LY95XduiM2plvhQ37rJ5TACo/PHStCILSvhzHG19UBZ1bWP62jEgQ==";
  inputs = [ unzip ];
}

fetchArchive {
  url = https://deb.debian.org/debian/pool/main/a/apt/apt_1.4.8_arm64.deb;
  hash = "sha512-/6NY2ZhfJIKA6Qzg5vBxVaG9qfR7TqF/kK2ntzwMGXGpg2ycopjUAtxLqqRsM87OZQsYS7hklQhHcvx/NVz3dQ==";
  inputs = [ dpkg ];
}
```

Derivation override example:

```nix
nixUnstable.overrideAttrs (super: {
  src = lib.stripRoot (fetchArchive {
    url = https://github.com/NixOS/nix/archive/2.2.1.tar.gz;
    hash = "sha512-U8y9gVgvjowXZ/lTp7fxqRrWFbxZwrbS4LY95XduiM2plvhQ37rJ5TACo/PHStCILSvhzHG19UBZ1bWP62jEgQ==";
  });
})
```

Maybe this should better be called `fetchThenUnpack`. Also, instead of `lib.stripRoot`, stdenv can be tweaked into supporting non-stripped sources.

cc @grahamc, @LnL7, @oxij, @zimbatm

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by edolstra** [comment]
Using SRI hashes will cause problems with NixOS upgrades, since `nixos-rebuild` uses the old daemon (which might not support SRI hashes) to do the build.

**Comment by vcunat** [comment]
Something like that, yes.  I suppose it depends on the expected amount of benefit from using the feature.  I remember this precedent: https://github.com/NixOS/nixpkgs/pull/37693

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by mmahut** [comment]
Closing due to inactivity.

**Pull request closed without merging**
