### PR TITLE
z3_4_{8_5,8,11,12}: fix clang-19 build

### PR DESCRIPTION
**Pull request by paparodeo**
z3 contains a bunch of typos in never used functions. The update to clang-19 now reports the typos -- wrong member function / variable names.  There is an upstream patch which fixes some of these:

https://github.com/Z3Prover/z3/commit/2ce89e5f491fa817d02d8fdce8c62798beab258b

And the others we patch or remove as the upstream code has since been modified.

https://hydra.nixos.org/build/281894894
https://hydra.nixos.org/build/281915487
https://hydra.nixos.org/build/282836452
https://hydra.nixos.org/build/282910819

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by numinit** [comment]
This will conflict with #327052 though we should still add the patches there.

**Comment by paparodeo** [comment]
> This will conflict with #327052 though we should still add the patches there.

I see -- using nixfmt really makes a mess of things. with that change merged this one doesn't really matter. nothing uses 4_12 and can get dropped. one thing uses 4_11 and it is broken anyway and one thing uses 4_8_5 which is also broken. 4_13 should be updated to the most recent version which came out a couple of weeks ago. you're free to take the patches from this change.

**Comment by numinit** [comment]
Thank you for the work in any case. Apologies you didn't see the PR before doing the work, I wish there was some preflight "this derivation is being touched by that PR" dashboard...

**Comment by paparodeo** [comment]
> Thank you for the work in any case. Apologies you didn't see the PR before doing the work, I wish there was some preflight "this derivation is being touched by that PR" dashboard...

no worries. I was involved in the llvm-19 compiler bump so have just been fixing issues for 2 months... this one was pretty easy as clang-19 is just complaining about dead code.

**Pull request closed without merging**
