### PR TITLE
staging-next 2022-04-15

### LINKED ISSUE #169010: `libcap` fails to cross-compile from `gnu64` to `aarch64-multiplatform` on unstable
### Describe the bug
When attempting to build an aarch64 sdcard image with the below configuration, libcap fails to build with the following error:

```console
error: builder for '/nix/store/wi4g5zqg5y1m29z0g9ryg6jkmb9nsl98-libcap-aarch64-unknown-linux-gnu-2.63.drv' failed with exit code 2;
       last 10 log lines:
       > make libcap.so
       > make[2]: Entering directory '/build/libcap-2.63/libcap'
       > aarch64-unknown-linux-gnu-gcc -O2  -Wall -Wwrite-strings -Wpointer-arith -Wcast-qual -Wcast-align -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Winline -Wshadow -Wunreachable-code -fPIC -Dlinux -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I/build/libcap-2.63/libcap/../libcap/include/uapi -I/build/libcap-2.63/libcap/../libcap/include   empty.c   -o empty
       > objcopy --dump-section .interp=loader.txt empty /dev/null
       > objcopy: Unable to recognise the format of the input file `empty'
       > make[2]: *** [Makefile:112: loader.txt] Error 1
       > make[2]: Leaving directory '/build/libcap-2.63/libcap'
       > make[1]: *** [Makefile:41: all] Error 2
       > make[1]: Leaving directory '/build/libcap-2.63/libcap'
       > make: *** [Makefile:12: all] Error 2
       For full logs, run 'nix log /nix/store/wi4g5zqg5y1m29z0g9ryg6jkmb9nsl98-libcap-aarch64-unknown-linux-gnu-2.63.drv'.
```

### Steps To Reproduce

1. Create flake.nix.
```nix
{
  description = "Base aarch64 system";

  inputs = {
    nixpkgs.url = "nixpkgs/nixos-unstable";
  };

  outputs = { self, nixpkgs }: rec {
    nixosConfigurations.system = nixpkgs.lib.nixosSystem {
      system = "aarch64-linux";
      modules = [
        "${nixpkgs}/nixos/modules/installer/sd-card/sd-image-aarch64.nix"
        {
          nixpkgs = {
            config.allowUnfree = true;
            crossSystem = nixpkgs.lib.systems.examples.aarch64-multiplatform;
            localSystem = nixpkgs.lib.systems.examples.gnu64;
          };
        }
      ];
    };

    images.sdcard = nixosConfigurations.system.config.system.build.sdImage;
  };
}
```
2. Run `nix build '.#images.sdcard'`
3. Build eventually fails with the above error.

### Expected behavior
Working build.

### Screenshots
N/A

### Additional context
I'm not 100% confident that I'm doing this cross compilation correctly. I've been working on this problem all evening and the above flake code is more or less the sum of my knowledge on the subject so far.

### Notify maintainers

Nobody was in meta.maintainers, so I added some folks from git blame. I apologize if I @'d anyone who is not relevant. I would tag someone experienced with cross compilation but I'm not sure how to find one of the owners of such a feature.

@Ericson2314 
@siraben 
@orivej 
@zowoq 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.32, NixOS, 22.05 (Quokka), 22.05.20220406.b6966d9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixos"`
 - channels(eliza): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by mweinelt**
workflow docs: [nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy](https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy)
constitutents: [hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents](https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents)
jobset: [hydra.nixos.org/jobset/nixpkgs/staging-next](https://hydra.nixos.org/jobset/nixpkgs/staging-next)
nix-review reports: https://malob.github.io/nix-review-tools-reports/

Previous staging-next #168140

### CODE REVIEW

**Comment by mweinelt** [comment]
- [ ] python3.pkgs.requests regression in aarch64-darwin https://hydra.nixos.org/build/173685998
- [ ] glib regression on aarch64-darwin https://hydra.nixos.org/build/173722990

**Comment by fabianhjr** [comment]
Several gcc11 fixes: https://github.com/NixOS/nixpkgs/pull/168797

**Comment by fabianhjr** [comment]
@NixOS/qt-kde would appreciate help unbreaking Qt 5.12 and 5.14; there is an issue with gcc11 regarding limits.h not being included. Easiest fix would be to use gcc10 on those 2 versions but when I attempted an override on top-level/all-packages.nix (by removing the `inherit stdenv` and adding a `stdenv = if stdenv.cc.isGNU then gcc10Stdenv else stdenv` the inner modules kept using gcc11 (tried with `libsForQt512.qtbase` and `libsForQt514.qtbase`)

**Comment by SuperSandro2000** [comment]
I think the stdenv is not being passed through here https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/qt-5/5.15/default.nix#L121-L130= and callPackage uses the default top-level stdenv. If we pass it there ot every package I think it could work.

**Comment by fabianhjr** [comment]
Thanks for the pointer @SuperSandro2000, that was it and the override propagated to qtbase.

https://github.com/NixOS/nixpkgs/pull/168869

**Comment by fabianhjr** [comment]
Another round of gcc11 fixes: https://github.com/NixOS/nixpkgs/pull/168877

**Comment by mweinelt** [comment]
- [ ] [python3.pkgs.pandas](https://hydra.nixos.org/build/173731589) regressed on x86_64-darwin
- [ ] [python3.pkgs.scipy](https://hydra.nixos.org/build/173740703) regressed on x86_64-darwin

**Comment by fabianhjr** [comment]
hardened kernels and some kernel modules are broken on staging-next due to gcc11 changes, won't have much time to take a look at them until monday so would appreciate help if someone could attempt to fix them before then.

**Comment by mweinelt** [comment]
cc @emilazy @Ma27 for the hardened kernels ^

**Pull request merged**
