### PR TITLE
minitube: 2.4 -> 2.9

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

Version 2.9 is based on QT5 (with a much better interface) and requires
additionally the dependencies `qtbase`, `qtdeclarative` and `qttools`.

Furthermore the `QT_PLUGIN_PATH` had to be altered, however the
`phonon-backend` contains versioned paths, so we provide the plugin path
that matches the QT version used to build this package.

See #33248

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
When I build and run this locally, it seems to work fine but I get these error messages:
```
$ result/bin/minitube 
[unknown] QIODevice::read (QFile, ":/functions.js"): device not open
[00007f68e0000c28] vdpau_avcodec generic error: Xlib is required for VDPAU
```
The second one is probably unrelated to this package, but the first one might be.

**Comment by xeji** [comment]
The first error seems to be generated [here in the source](https://github.com/flaviotordini/minitube/blob/b9df0006232f86223827dd8a6762807701a924fc/src/jsfunctions.cpp#L43) but I don't know anything else about it.

**Comment by Ma27** [comment]
@xeji did you encounter *any* issues while using this package? I tried playing around with it a bit and besides the probably unrelated `vdpau_avcodec generic error: Xlib is required for VDPAU` error no errors arise and the application works fine.

Interestingly enough the qt4 variant (v2.4) broke for me with the following errors:

```
[0000000002a8b6b8] core input error: Your input can't be opened
[0000000002a8b6b8] core input error: VLC is unable to open the MRL 'https://r2---sn-4g5e6nsk.googlevideo.com/videoplayback?ipbits=0&fexp=23724337&dur=213.623&mime=video%2Fmp4&itag=18&source=youtube&mm=31%2C26&mn=sn-4g5e6nsk%2Csn-25ge7nsl&requiressl=yes&ip=2a00%3Acb0%3A8002%3A1055%3Aca5b%3A76ff%3Afeca%3Ad3c5&gir=yes&ratebypass=yes&fvip=6&mt=1525462356&mv=u&pl=34&id=o-AB_szYNuSyeBAYSWlJmrYpJWbFI7_d6C6zX-mV9oIn1G&ei=xLfsWvbaLNDbgQf03bqQDA&ms=au%2Conr&c=WEB&key=yt6&lmt=1524755502570017&clen=19154330&expire=1525484580&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&signature=undefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefined'. Check the log for details.
Phonon error: "No active input"  Phonon::NormalError  
```

I'm unfortunately unable to estimate how serious the error is you described, so I'm unsure if we should merge for now or try further investigation (in case the application is unusable for you) :-)

**Comment by xeji** [comment]
Seems to work just fine here, and the first error has disappeared too. Looks like it  was caused by a nonexisting file `~/.local/share/Flavio Tordini/Minitube/functions.js` on startup, which the app seems to create later when you actually watch a video. `aarch64` failure is in a dependency, so I think this is good to merge.

**Pull request merged**
