### PR TITLE
python311Packages.logbook: 1.5.3 -> 1.6.0 

### PR DESCRIPTION
**Pull request by fabaff**
Changelog: https://github.com/getlogbook/logbook/blob/1.6.0/CHANGES

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 251354` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>22 packages failed to build:</summary>
  <ul>
    <li>cobang</li>
    <li>cobang.dist</li>
    <li>dbt (python310Packages.dbt-core)</li>
    <li>dbt.dist (python310Packages.dbt-core.dist)</li>
    <li>python310Packages.dbt-bigquery</li>
    <li>python310Packages.dbt-bigquery.dist</li>
    <li>python310Packages.dbt-postgres</li>
    <li>python310Packages.dbt-postgres.dist</li>
    <li>python310Packages.dbt-redshift</li>
    <li>python310Packages.dbt-redshift.dist</li>
    <li>python310Packages.dbt-snowflake</li>
    <li>python310Packages.dbt-snowflake.dist</li>
    <li>python311Packages.dbt-bigquery</li>
    <li>python311Packages.dbt-bigquery.dist</li>
    <li>python311Packages.dbt-core</li>
    <li>python311Packages.dbt-core.dist</li>
    <li>python311Packages.dbt-postgres</li>
    <li>python311Packages.dbt-postgres.dist</li>
    <li>python311Packages.dbt-redshift</li>
    <li>python311Packages.dbt-redshift.dist</li>
    <li>python311Packages.dbt-snowflake</li>
    <li>python311Packages.dbt-snowflake.dist</li>
  </ul>
</details>
<details>
  <summary>22 packages built:</summary>
  <ul>
    <li>matrix-commander</li>
    <li>matrix-commander.dist</li>
    <li>mirage-im</li>
    <li>opsdroid</li>
    <li>opsdroid.dist</li>
    <li>pantalaimon</li>
    <li>pantalaimon-headless</li>
    <li>pantalaimon-headless.dist</li>
    <li>pantalaimon.dist</li>
    <li>python310Packages.elastic-apm</li>
    <li>python310Packages.elastic-apm.dist</li>
    <li>python310Packages.logbook</li>
    <li>python310Packages.logbook.dist</li>
    <li>python310Packages.matrix-nio</li>
    <li>python310Packages.matrix-nio.dist</li>
    <li>python311Packages.elastic-apm</li>
    <li>python311Packages.elastic-apm.dist</li>
    <li>python311Packages.logbook</li>
    <li>python311Packages.logbook.dist</li>
    <li>python311Packages.matrix-nio</li>
    <li>python311Packages.matrix-nio.dist</li>
    <li>weechatScripts.weechat-matrix</li>
  </ul>
</details>

**Comment by tjni** [comment]
We probably need to relax this dependency in `dbt-core`. Maybe in `cobang` too?

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 251354` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>44 packages built:</summary>
  <ul>
    <li>cobang</li>
    <li>cobang.dist</li>
    <li>dbt (python310Packages.dbt-core)</li>
    <li>dbt.dist (python310Packages.dbt-core.dist)</li>
    <li>matrix-commander</li>
    <li>matrix-commander.dist</li>
    <li>mirage-im</li>
    <li>opsdroid</li>
    <li>opsdroid.dist</li>
    <li>pantalaimon</li>
    <li>pantalaimon-headless</li>
    <li>pantalaimon-headless.dist</li>
    <li>pantalaimon.dist</li>
    <li>python310Packages.dbt-bigquery</li>
    <li>python310Packages.dbt-bigquery.dist</li>
    <li>python310Packages.dbt-postgres</li>
    <li>python310Packages.dbt-postgres.dist</li>
    <li>python310Packages.dbt-redshift</li>
    <li>python310Packages.dbt-redshift.dist</li>
    <li>python310Packages.dbt-snowflake</li>
    <li>python310Packages.dbt-snowflake.dist</li>
    <li>python310Packages.elastic-apm</li>
    <li>python310Packages.elastic-apm.dist</li>
    <li>python310Packages.logbook</li>
    <li>python310Packages.logbook.dist</li>
    <li>python310Packages.matrix-nio</li>
    <li>python310Packages.matrix-nio.dist</li>
    <li>python311Packages.dbt-bigquery</li>
    <li>python311Packages.dbt-bigquery.dist</li>
    <li>python311Packages.dbt-core</li>
    <li>python311Packages.dbt-core.dist</li>
    <li>python311Packages.dbt-postgres</li>
    <li>python311Packages.dbt-postgres.dist</li>
    <li>python311Packages.dbt-redshift</li>
    <li>python311Packages.dbt-redshift.dist</li>
    <li>python311Packages.dbt-snowflake</li>
    <li>python311Packages.dbt-snowflake.dist</li>
    <li>python311Packages.elastic-apm</li>
    <li>python311Packages.elastic-apm.dist</li>
    <li>python311Packages.logbook</li>
    <li>python311Packages.logbook.dist</li>
    <li>python311Packages.matrix-nio</li>
    <li>python311Packages.matrix-nio.dist</li>
    <li>weechatScripts.weechat-matrix</li>
  </ul>
</details>

**Comment by fabaff** [comment]
> We probably need to relax this dependency in dbt-core. Maybe in cobang too?

Done.

**Pull request merged**
