### PR TITLE
Upgrade beancount-black and beancount-parser

### PR DESCRIPTION
**Pull request by fangpenlin**
## Description of changes

Author of [beancount-parser](https://github.com/LaunchPlatform/beancount-parser) and [beancount-black](beancount-black) here, we have newer version fixed many bugs, so would like to push an upgrade here.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kirillrdy** [comment]
@fangpenlin greetings !

can you please split update into two commits, one per each attribute, and change commit message to confirm with contribution guidelines https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions

**Comment by pluiedev** [comment]
Result of `nixpkgs-review pr 310502` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>beancount-black (python311Packages.beancount-black)</li>
    <li>beancount-black.dist (python311Packages.beancount-black.dist)</li>
    <li>python311Packages.beancount-parser</li>
    <li>python311Packages.beancount-parser.dist</li>
    <li>python312Packages.beancount-black</li>
    <li>python312Packages.beancount-black.dist</li>
    <li>python312Packages.beancount-parser</li>
    <li>python312Packages.beancount-parser.dist</li>
  </ul>
</details>

**Comment by ambroisie** [comment]
Thanks for taking the time to do this @fangpenlin, I didn't have the time to do it before this week-end.

As pointed out by @kirillrdy, please follow our commit conventions :-).

**Comment by fangpenlin** [comment]
pushed, and tested with preview command. it seems like working as expected

**Review by ambroisie — APPROVED** [review]

**Review by kirillrdy — APPROVED** [review]
Result of `nixpkgs-review pr 310502` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>beancount-black (python311Packages.beancount-black)</li>
    <li>beancount-black.dist (python311Packages.beancount-black.dist)</li>
    <li>python311Packages.beancount-parser</li>
    <li>python311Packages.beancount-parser.dist</li>
    <li>python312Packages.beancount-black</li>
    <li>python312Packages.beancount-black.dist</li>
    <li>python312Packages.beancount-parser</li>
    <li>python312Packages.beancount-parser.dist</li>
  </ul>
</details>

**Pull request merged**
