### PR TITLE
godot: 4.0-rc1 -> 4.0-stable

### PR DESCRIPTION
**Pull request by CyborgPotato**
###### Description of changes

Updates godot to the stable release of godot 4!

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by drupol — APPROVED** [review]

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 219029` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>godot_4</li>
  </ul>
</details>

**Review by superherointj — APPROVED** [review]

**Comment by Garmelon** [comment]
If #215829 is merged before this, the `GODOT_VERSION_STATUS` environment variable must be unset again for the 4.0 release. If this PR is merged before #215829, I'll rebase and fix the latter.

**Comment by superherointj** [comment]
> If #215829 is merged before this, the `GODOT_VERSION_STATUS` environment variable must be unset again for the 4.0 release. If this PR is merged before #215829, I'll rebase and fix the latter.

I will merge this PR first then. When you are ready with other PR, ping me.

**Comment by campbellcole** [comment]
I am trying to use this derivation and it built successfully, but crashes almost every time I run Godot:
```
Godot Engine v4.0.stable.custom_build - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 525.89.02 - Compatibility - Using Device: NVIDIA Corporation - NVIDIA GeForce RTX 3070 Ti

X connection to :0 broken (explicit kill or server shutdown).
ERROR: BUG: Unreferenced static string to 0: GuiToggleOnDisabledMirrored
   at: unref (core/string/string_name.cpp:129)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketLargeE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools12BucketMediumE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketSmallE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
ERROR: BUG: Unreferenced static string to 0: interface_added
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: bus_layout_changed
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: settings_changed
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: menu_changed
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: fallback_changed
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: cell_selected
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: child_entered_tree
   at: unref (core/string/string_name.cpp:131)
```

That is the most common error for me, but several others appear occasionally:
```
Godot Engine v4.0.stable.custom_build - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 525.89.02 - Compatibility - Using Device: NVIDIA Corporation - NVIDIA GeForce RTX 3070 Ti

[xcb] Extra reply data still left in queue
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that.
godot: xcb_io.c:673: _XReply: Assertion `!xcb_xlib_extra_reply_data_left' failed.
[1]    10870 IOT instruction (core dumped)  godot
```
```
Godot Engine v4.0.stable.custom_build - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 525.89.02 - Compatibility - Using Device: NVIDIA Corporation - NVIDIA GeForce RTX 3070 Ti

X connection to :0 broken (explicit kill or server shutdown).
ERROR: BUG: Unreferenced static string to 0: _process_internal
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: _physics_process_internal
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: GuiToggleOnDisabledMirrored
   at: unref (core/string/string_name.cpp:129)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketLargeE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools12BucketMediumE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketSmallE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
ERROR: BUG: Unreferenced static string to 0: interface_added
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: frame_pre_draw
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: frame_post_draw
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: process_frame
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: physics_frame
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: bus_layout_changed
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: settings_changed
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: menu_changed
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: fallback_changed
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: cell_selected
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: child_entered_tree
   at: unref (core/string/string_name.cpp:131)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.stable.custom_build
Dumping the backtrace. Please include this when reporting the bug to the project developer.
ERROR: FATAL: Index p_index = 1 is out of bounds (size() = 0).
   at: get (./core/templates/cowdata.h:155)

================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.0.stable.custom_build
Dumping the backtrace. Please include this when reporting the bug to the project developer.
ERROR: FATAL: Index p_index = 1 is out of bounds (size() = 0).
   at: get (./core/templates/cowdata.h:155)
[1]    14602 illegal hardware instruction (core dumped)  godot
```

This error appeared after it successfully created two windows and was able to keep them interactive for about 5 seconds, then it crashed:
```
Godot Engine v4.0.stable.custom_build - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 525.89.02 - Compatibility - Using Device: NVIDIA Corporation - NVIDIA GeForce RTX 3070 Ti

X connection to :0 broken (explicit kill or server shutdown).
ERROR: BUG: Unreferenced static string to 0: _process_internal
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: _physics_process_internal
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: GuiToggleOnDisabledMirrored
   at: unref (core/string/string_name.cpp:129)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketLargeE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools12BucketMediumE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketSmallE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
ERROR: BUG: Unreferenced static string to 0: tab_clicked
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: tab_hovered
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: canceled
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: interface_added
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: frame_pre_draw
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: frame_post_draw
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: process_frame
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: physics_frame
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: bus_layout_changed
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: settings_changed
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: menu_changed
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: fallback_changed
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: cell_selected
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: button_down
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: button_up
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: child_entered_tree
   at: unref (core/string/string_name.cpp:131)
```

All of these errors point to some X configuration being broken, especially the `[xcb] This is most likely caused by a broken X extension library`. Is there any type of package I may have installed that I should try removing?

System information:
NixOS: `23.05.20230222 (using flake)`
Kernel: `6.1.12`
CPU: `i7-13700KF`
GPU: `RTX 3070 Ti`
RAM: `32GB`

Thanks

**Comment by superherointj** [comment]
> I am trying to use this derivation and it built successfully, but crashes almost every time I run Godot:
> ```
> Godot Engine v4.0.stable.custom_build - https://godotengine.org
> OpenGL API 3.3.0 NVIDIA 525.89.02 - Compatibility - Using Device: NVIDIA Corporation - NVIDIA GeForce RTX 3070 Ti
> 
> X connection to :0 broken (explicit kill or server shutdown).
> ERROR: BUG: Unreferenced static string to 0: GuiToggleOnDisabledMirrored
>    at: unref (core/string/string_name.cpp:129)
> ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketLargeE
>    at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
> ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools12BucketMediumE
>    at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
> ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketSmallE
>    at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
> ERROR: BUG: Unreferenced static string to 0: interface_added
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: bus_layout_changed
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: settings_changed
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: menu_changed
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: fallback_changed
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: cell_selected
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: child_entered_tree
>    at: unref (core/string/string_name.cpp:131)
> ```
> 
> That is the most common error for me, but several others appear occasionally:
> ```
> Godot Engine v4.0.stable.custom_build - https://godotengine.org
> OpenGL API 3.3.0 NVIDIA 525.89.02 - Compatibility - Using Device: NVIDIA Corporation - NVIDIA GeForce RTX 3070 Ti
> 
> [xcb] Extra reply data still left in queue
> [xcb] This is most likely caused by a broken X extension library
> [xcb] Aborting, sorry about that.
> godot: xcb_io.c:673: _XReply: Assertion `!xcb_xlib_extra_reply_data_left' failed.
> [1]    10870 IOT instruction (core dumped)  godot
> ```
> ```
> Godot Engine v4.0.stable.custom_build - https://godotengine.org
> OpenGL API 3.3.0 NVIDIA 525.89.02 - Compatibility - Using Device: NVIDIA Corporation - NVIDIA GeForce RTX 3070 Ti
> 
> X connection to :0 broken (explicit kill or server shutdown).
> ERROR: BUG: Unreferenced static string to 0: _process_internal
>    at: unref (core/string/string_name.cpp:129)
> ERROR: BUG: Unreferenced static string to 0: _physics_process_internal
>    at: unref (core/string/string_name.cpp:129)
> ERROR: BUG: Unreferenced static string to 0: GuiToggleOnDisabledMirrored
>    at: unref (core/string/string_name.cpp:129)
> ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketLargeE
>    at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
> ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools12BucketMediumE
>    at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
> ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketSmallE
>    at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
> ERROR: BUG: Unreferenced static string to 0: interface_added
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: frame_pre_draw
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: frame_post_draw
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: process_frame
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: physics_frame
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: bus_layout_changed
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: settings_changed
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: menu_changed
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: fallback_changed
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: cell_selected
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: child_entered_tree
>    at: unref (core/string/string_name.cpp:131)
> 
> ================================================================
> handle_crash: Program crashed with signal 11
> Engine version: Godot Engine v4.0.stable.custom_build
> Dumping the backtrace. Please include this when reporting the bug to the project developer.
> ERROR: FATAL: Index p_index = 1 is out of bounds (size() = 0).
>    at: get (./core/templates/cowdata.h:155)
> 
> ================================================================
> handle_crash: Program crashed with signal 4
> Engine version: Godot Engine v4.0.stable.custom_build
> Dumping the backtrace. Please include this when reporting the bug to the project developer.
> ERROR: FATAL: Index p_index = 1 is out of bounds (size() = 0).
>    at: get (./core/templates/cowdata.h:155)
> [1]    14602 illegal hardware instruction (core dumped)  godot
> ```
> 
> This error appeared after it successfully created two windows and was able to keep them interactive for about 5 seconds, then it crashed:
> ```
> Godot Engine v4.0.stable.custom_build - https://godotengine.org
> OpenGL API 3.3.0 NVIDIA 525.89.02 - Compatibility - Using Device: NVIDIA Corporation - NVIDIA GeForce RTX 3070 Ti
> 
> X connection to :0 broken (explicit kill or server shutdown).
> ERROR: BUG: Unreferenced static string to 0: _process_internal
>    at: unref (core/string/string_name.cpp:129)
> ERROR: BUG: Unreferenced static string to 0: _physics_process_internal
>    at: unref (core/string/string_name.cpp:129)
> ERROR: BUG: Unreferenced static string to 0: GuiToggleOnDisabledMirrored
>    at: unref (core/string/string_name.cpp:129)
> ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketLargeE
>    at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
> ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools12BucketMediumE
>    at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
> ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketSmallE
>    at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
> ERROR: BUG: Unreferenced static string to 0: tab_clicked
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: tab_hovered
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: canceled
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: interface_added
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: frame_pre_draw
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: frame_post_draw
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: process_frame
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: physics_frame
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: bus_layout_changed
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: settings_changed
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: menu_changed
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: fallback_changed
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: cell_selected
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: button_down
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: button_up
>    at: unref (core/string/string_name.cpp:131)
> ERROR: BUG: Unreferenced static string to 0: child_entered_tree
>    at: unref (core/string/string_name.cpp:131)
> ```
> 
> All of these errors point to some X configuration being broken, especially the `[xcb] This is most likely caused by a broken X extension library`. Is there any type of package I may have installed that I should try removing?
> 
> System information:
> NixOS: `23.05.20230222 (using flake)`
> Kernel: `6.1.12`
> CPU: `i7-13700KF`
> GPU: `RTX 3070 Ti`
> RAM: `32GB`
> 
> Thanks

Open an issue.

**Comment by superherointj** [comment]
@campbellcole Open an issue.

Btw, works for me:

image

This commit is not at unstable:

image

Source: https://nixpk.gs/pr-tracker.html?pr=219029

Have you bisected your problem to this commit?

**Comment by campbellcole** [comment]
Yes I am certain I was using the exact derivation this PR has merged. I copied the derivation locally and called it that way. I also just tried using the `rc.1` version in unstable, and that one also has this problem. I updated my issue to reflect this. However, I tried the `godot` package which is 3.5.1 and that version works with no problems.

**Comment by superherointj** [comment]
> Yes I am certain I was using the exact derivation this PR has merged. I copied the derivation locally and called it that way.
> I also just tried using the `rc.1` version in unstable, and that one also has this problem. 

Again, this commit is not at unstable [yet].
As unstable already has the issue you claim, problem is unrelated to this PR.

Godot is working for me. I cannot reproduce your issue.

Next time, file an issue *first* instead of blaming PRs.

**Pull request merged**
