### PR TITLE
nixos: fix release notes about linux_latest version

### PR DESCRIPTION
**Pull request by bjornfor**
###### Motivation for this change
It's version 5.13, not 5.12.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by davidak — APPROVED** [review]
yes, that is correct

>linuxPackages_latest = linuxPackages_5_13;

**Comment by davidak** [comment]
>It currently is not officially supported for use with the zfs filesystem

is that still the case?

**Comment by vcunat** [comment]
Having `linux_latest` version in release notes seems kind of pointless to me, as it follows the latest version from upstream.  Originally it was 5.11 (when 21.05 was forked off).

**Comment by davidak** [comment]
the item might be just there for the zfs note?

i agree it does not make a lot of sense

**Comment by vcunat** [comment]
Yes, that part is useful.  The ZFS problem still exists; it's typical for nontrivial out-of-tree drivers.  (e.g. nvidia, too)

**Comment by davidak** [comment]
does the issue still exist for 5.12 as well? maybe that should be documented as well

**Comment by vcunat** [comment]
I think generally the support always arrives at *some* point, but it would be too late so it's not worth delaying `linux_latest` because of that.

**Pull request merged**
