### PR TITLE
cdrtools: 3.02a06 -> 3.02a09

### PR DESCRIPTION
**Pull request by c0bw3b**
###### Motivation for this change

* `cdrtools` update
* `dvdplusrwtools` revamp in order to replace local patches with ones we can fetch, + set meta.license

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by c0bw3b** [comment]
I'm adding the WIP label only because ofBorg Darwin builder seems offline and I don't want to add any more jobs to its waiting queue.

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build cdrtools dvdplusrwtools

**Comment by risicle** [comment]
`nix-review` builds happily macos 10.13

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build cdrtools dvdplusrwtools

**Comment by c0bw3b** [comment]
Thanks @risicle 

Locally on nixos:

---
Result of `nix-review pr 71405` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>1 package are marked as broken and were skipped:</summary>

  - k9copy (kdeApplications.k3b)
</details>
<details>
  <summary>12 package were build:</summary>

  - bashburn (kdeApplications.k3b)
  - bombono (kdeApplications.k3b)
  - brasero (kdeApplications.k3b)
  - dvd-slideshow (kdeApplications.k3b)
  - dvdplusrwtools (kdeApplications.k3b)
  - dvdstyler (kdeApplications.k3b)
  - k3b (kdeApplications.k3b)
  - sound-juicer (kdeApplications.k3b)
  - terraform-full (kdeApplications.k3b)
  - terraform-providers.libvirt (kdeApplications.k3b)
  - terraform_0_11-full (kdeApplications.k3b)
  - terragrunt (kdeApplications.k3b)
</details>

---
And I can't reproduce ofborg failure when building `cdrtools`  :confused:

**Comment by c0bw3b** [comment]
One has to eval locally because ofBorg eval ignores packages with `hydraPlatforms = [];` so:

```console
$ nix-review pr 71405 -p cdrtools --eval local
[...]
1 package were build:
cdrtools
[...]

$ ./results/cdrtools/bin/mkisofs --version
mkisofs 3.02a09 (x86_64-unknown-linux-gnu)

$ ./results/cdrtools/bin/cdrecord --version
Cdrecord-ProDVD-ProBD-Clone 3.02a09 (x86_64-unknown-linux-gnu) Copyright (C) 1995-2016 Joerg Schilling
```

**Comment by c0bw3b** [comment]
In a second nixos VM on another machine :

```console
$ nix-review pr 71405 --eval local
[...]
13 package were build:
bashburn bombono brasero cdrtools dvd-slideshow dvdplusrwtools dvdstyler k3b sound-juicer terraform-full terraform-provider-libvirt terraform_0_11-full terragrunt

$ ./results/cdrtools/bin/cdrecord --version
Cdrecord-ProDVD-ProBD-Clone 3.02a09 (x86_64-unknown-linux-gnu) Copyright (C) 1995-2016 Joerg Schilling
```

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build cdrtools dvdplusrwtools

**Comment by c0bw3b** [comment]
Turns out the previous build failures of `cdrtools` were a consequence of parallel building.

**Pull request merged**
