### PR TITLE
go-dnscollector: init package

### PR DESCRIPTION
**Pull request by shift**
Inited the go-dnscollector package. and added myself to the maintainers.

## Things done
 Built and tested on multiple x86_64 machines.

- Built on platform(s)
  - [*] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [*] Tested, as applicable:
- [*] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by m1dugh** [comment]
Can you format your code using `nixfmt-rfc-style`, and run `nixpkgs-review pr 3511194` and give us the output of the tool ? (see https://github.com/Mic92/nixpkgs-review)

**Comment by Scrumplex** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 351194`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>go-dnscollector</li>
  </ul>
</details>

**Review by Scrumplex — APPROVED** [review]
LGTM

**Comment by emilylange** [comment]
This is missing some `ldflags` for embedding version info.

https://github.com/dmachard/go-dnscollector/blob/v1.1.0/Makefile#L21-L24
https://github.com/dmachard/go-dnscollector/blob/v1.1.0/.goreleaser.yml#L12-L15

```bash
# result/bin/go-dnscollector -version

# (empty newline)
```

Is this something you feel confident fixing yourself @shift?
And if you want you can add a version test as well.

**Comment by shift** [comment]
Yeah, I can fix it. Was at NixCon Berlin, had some issues with the WiFi will resolve soon.

**Comment by shift** [comment]
@emilylange So I've a change, including a test. But I'm currently unsure on how to execute the test I've created. Could you provide some assistance/linkage to docs please?

**Comment by Scrumplex** [comment]
You could write a NixOS VM test:
https://nixos.org/manual/nixos/stable/index.html#sec-nixos-tests
https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/all-tests.nix

**Comment by emilylange** [comment]
> @emilylange So I've a change, including a test. But I'm currently unsure on how to execute the test I've created. Could you provide some assistance/linkage to docs please?

I am on mobile right now.
But for the version test you either want to use <https://nixos.org/manual/nixpkgs/unstable/#tester-testVersion> or <https://nixos.org/manual/nixpkgs/unstable/#versioncheckhook>.

If you add `testers.testVersion` to `passthru.tests` just like in the example fron the manual, you can use `nix-build -A go-dnscollector.passthru.tests` or just `nix-build -A go-dnscollector.tests`.

And in case you opt for the `versionCheckHook` it will be part of `nix-build -A go-dnscollector`.

For the `ldflags` you can look at other prometheus exporters. E.g. https://github.com/NixOS/nixpkgs/blob/b320b56ad0f4c2d2c6e100e8c868c7c2bf31eff0/pkgs/servers/monitoring/prometheus/systemd-exporter.nix#L19-L23 or using `let in` https://github.com/NixOS/nixpkgs/blob/7148776f8697fd2591951fa0bda3a7e5d7cc8eff/pkgs/servers/monitoring/prometheus/sql-exporter.nix#L16-L24

Hope that helps^^

**Pull request merged**
