### PR TITLE
azure-cli-extensions: update at 2024-07-29

### PR DESCRIPTION
**Pull request by superherointj**
azure-cli-extensions: update at 2024-07-29

CC @katexochen

### CODE REVIEW

**Comment by superherointj** [comment]
@ofborg build azure-cli

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 330864` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>azure-cli-extensions.aks-preview</li>
    <li>azure-cli-extensions.aks-preview.dist</li>
    <li>azure-cli-extensions.amg</li>
    <li>azure-cli-extensions.amg.dist</li>
    <li>azure-cli-extensions.azure-firewall</li>
    <li>azure-cli-extensions.azure-firewall.dist</li>
    <li>azure-cli-extensions.dataprotection</li>
    <li>azure-cli-extensions.dataprotection.dist</li>
    <li>azure-cli-extensions.oracle-database</li>
    <li>azure-cli-extensions.oracle-database.dist</li>
  </ul>
</details>

**Comment by katexochen** [comment]
Last commit message is wrong, otherwise lgtm. Do we need to update these extensions this often?

**Comment by superherointj** [comment]
> Last commit message is wrong, otherwise lgtm. Do we need to update these extensions this often?

My goal here was to learn the process. Because last time I got it wrong. And now, it seems I also got it wrong again. And then, I was thinking on how this should be automated.

**Comment by superherointj** [comment]
> Last commit message is wrong, otherwise lgtm.

Can you clarify the problem?

**Comment by katexochen** [comment]
> My goal here was to learn the process. Because last time I got it wrong. And now, it seems I also got it wrong again. And then, I was thinking on how this should be automated.

Okay, got it. :)

So when I update these extensions, I will call `git add -p` and commit the hunks that init or remove things, or that are close together manually. The script can then do the rest. I thought a bit about atomizing it further, but I think it would require so much work and not save much time (for me).

> Can you clarify the problem?

Sure, sorry. The last commit is actually a new extension, so the commit message should be `...: init at 1.0.0.b1`

**Review by katexochen — APPROVED** [review]

**Pull request merged**
