### PR TITLE
openjump: 1.3.1 -> 1.15

### LINKED ISSUE #38452: OpenJump should depend on Java
## Issue description

OpenJump, being a Java application, needs a JRE (and more specifically, the `java` command) to run, but doesn't currently pull that in.

### Steps to reproduce

`nix-shell -p openjump --run OpenJump` on a system without Java installed globally results in
```
which: no java in (/nix/store/3szk4257s9400bw97a7fg2fdgsy6f1di-openjump-1.3.1/bin:/nix/store/48rw1wqh28whw8xdnnfsk2153vspjgsf-patchelf-0.9/bin:/nix/store/jh856w2kbmszb3vn0gq2clc2rs197fll-paxctl-0.9/bin:/nix/store/5l6b97jscljkvsq9y9amg71v5jfzddm4-gcc-wrapper-6.4.0/bin:/nix/store/3p1b66av1sflap15jr4b8z6hw28fmjam-gcc-6.4.0/bin:/nix/store/klwxxrlgalq49cjnczvgha3j7l00jixw-binutils-2.28.1/bin:/nix/store/5yls004wxgb5ihhj94kyc82s2f1qlw3z-glibc-2.25-123-bin/bin:/nix/store/4bh7qhnrjk8cgd1bh7nr0glbga0aasdx-coreutils-8.28/bin:/nix/store/4bh7qhnrjk8cgd1bh7nr0glbga0aasdx-coreutils-8.28/bin:/nix/store/y936jxj0dl6rm9v6hrjz945361s73bcx-findutils-4.6.0/bin:/nix/store/d9b634g64hx785ypr6sn721l4sy4i7yn-diffutils-3.6/bin:/nix/store/za5n7hg16pnkvdrnnh7fxy9hsx9pp2i6-gnused-4.4/bin:/nix/store/h6vf6alpgnynlx1w9xwlaqhnjybjvy2x-gnugrep-3.1/bin:/nix/store/xxsx4amblqfnd2544gk5rk2xd935aihr-gawk-4.1.4/bin:/nix/store/0lyn8v4w3cd70hzg5md0xwhykhlbsq9f-gnutar-1.29/bin:/nix/store/93hb9j4n685dr698qq0j7ip0p2mss4lm-gzip-1.8/bin:/nix/store/7hdn84ab02qar14qpy5l4z4diw726rb4-bzip2-1.0.6.0.1-bin/bin:/nix/store/7wdyvzy6f07idfijhxx9xzn5plzji0bx-gnumake-4.2.1/bin:/nix/store/jgw8hxx7wzkyhb2dr9hwsd9h2caaasdc-bash-4.4-p12/bin:/nix/store/32glzc7751ybdy7i93j97iy6nqglmg1b-patch-2.7.5/bin:/nix/store/xjpzzdl3mh8v1wcbxrlgm2p9mnhlys6y-xz-5.2.3-bin/bin:/nix/store/z61y0s2xzngyxy8pndp9hqq23s7z1ywq-unzip-6.0/bin:/nix/store/kgid3ll10cmq52jnq1dgw1nnw6js422z-glib-2.52.3-dev/bin:/home/das-g/bin:/run/wrappers/bin:/etc/per-user-pkgs/das-g/bin:/home/das-g/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin)
openjump.sh: Zeile 69: -cp: Kommando nicht gefunden.
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.86, NixOS, 17.09.3222.21693048d72 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.3222.21693048d72"`
 - channels(das-g): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

### PR DESCRIPTION
**Pull request by syberant**
###### Motivation for this change
I was trying to fix #38452 but ended up updating the version at the same time because it was very old at this point.
@das-g, I don't use this software myself so I can't very well test if everything works. I just know the basics work like drawing the UI. Would you be so friendly as to test whether this solves your problems and doesn't create new ones?

Also for any reviewer: I am very uncertain about how to package shell scripts so some feedback and suggestions when I'm doing it wrong would be much appreciated! It does work though.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by das-g** [comment]
Result of `nixpkgs-review pr 94405` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- openjump
</details>

**Comment by das-g** [comment]
>  @das-g, I don't use this software myself so I can't very well test if everything works. I just know the basics work like drawing the UI.

I've only yet used OpenJump to display data. So if you've drawn in it (i.e. created new data or edited existing one) you've done more with it than I ever have.

> Would you be so friendly as to test whether this solves your problems and doesn't create new ones?

This PR does indeed solve #38452: With this change OpenJump can be launched without the user having to care how to provide a JRE to it. :+1:

**Comment by das-g** [comment]
> @das-g, I don't use this software myself so I can't very well test if everything works.

I've just tested it by downloading the `*.shp.zip` from https://download.geofabrik.de/europe/liechtenstein.html and opening that within OpenJump (even without unpacking the Zip archive first).

:heavy_check_mark: Seems to work fine and displays the content:

Bildschirmfoto von 2020-08-01 10-21-47

**Comment by syberant** [comment]
> Edit: Sorry, I've misread. I see now that you wrote about "drawing the _UI_", so I assume you mean just getting the UI to display.

Yes, I did mean just getting the UI to display.

> I've just tested it by downloading the `*.shp.zip` from https://download.geofabrik.de/europe/liechtenstein.html and opening that within OpenJump (even without unpacking the Zip archive first).
> 
> heavy_check_mark Seems to work fine and displays the content:

Great, thanks very much for testing.

Also, pinging @MarcWeber here as he is the maintainer.

**Pull request merged**
