### PR TITLE
citrix_workspace: 22.07.0 -> 22.12.0

### PR DESCRIPTION
**Pull request by michaeladler**
###### Description of changes

Version update + drop support for some old versions (housekeeping)

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cawilliamson** [comment]
This being merged is fairly important since you can no longer download the exact same version being expected by the previous package it seems. It's no longer present on the page. A slightly older version is but the pkg isn't expecting that.

(Likely not related specifically to this version only):

On another note - this DOES work for me by launching "selfservice" from CLI but fails to load properly running via the .desktop app since it fails with:

```
TLS/SSL support not available; install glib-networking
```

It seems that the .desktop file may need to be patched to use the wrapped version of the selfservice binary.

**Comment by michaeladler** [comment]
Hi @cawilliamson, I just checked `selfservice.desktop` and it points to `bin/selfservice` which is the same what you execute from the CLI. So if it works from the CLI, then it must be due to your `PATH` or other environment variables which aren't set if you launch the desktop file directly. My conclusion is that our wrapper is incomplete and missing something which fixes the glib-networking issue (obviously, this is loaded somehow dynamically).

**Review by RaitoBezarius — APPROVED** [review]
LGTM

**Comment by RaitoBezarius** [comment]
I do not have citrix_workspace therefore cannot test this, @michaeladler can you fix the wrapper to be more comprehensive or would that require another PR?

**Comment by michaeladler** [comment]
I've fixed the 22.07 hashes now. I'd say fixing the wrapper should be addressed in another PR. There's more broken unfortunately, e.g. the usbdaemon has never worked in NixOS (which is needed to forward USB devices, a pretty cool feature!).

**Comment by RaitoBezarius** [comment]
> I've fixed the 22.07 hashes now. I'd say fixing the wrapper should be addressed in another PR. There's more broken unfortunately, e.g. the usbdaemon has never worked in NixOS (which is needed to forward USB devices, a pretty cool feature!).

It seems like the PR do not pass ofborg eval though.

**Comment by michaeladler** [comment]
Yeah I somehow lost the `homepage` attribute while rebasing. This made me realize that today 22.12.0 was released. I haven't tested it yet, but will report back tomorrow morning when I get a chance to try 22.12.0 at work.

**Comment by michaeladler** [comment]
I have just tested 22.12.0 successfully so I'd say this is ready to merge :)

**Review by RaitoBezarius — APPROVED** [review]

**Pull request merged**
