### PR TITLE
maintainers: drop janik

### PR DESCRIPTION
**Pull request by Janik-Haag**
I guess my time has come as well...

With this commit, I'm not just dropping my maintainer entry, but I'm also resigning from my duties as a board observer and NixCon project lead. I also terminated my Summer of Nix contract today. I'll also stop hosting the local NixOS meetup.

The only "project" I'll finish under the NixOS Foundation umbrella is Google Summer of Code because the mentees aren't even remotely responsible for why I'm leaving, and it would be unfair to leave them hanging.

I'm grateful for all the things I was able to learn, for all the experiences I could gather, and for all the friends I made along the way. NixOS is what makes computers bearable for me, so I'll go and work on some fork (*something something* you always meet twice in life).

### CODE REVIEW

**Comment by Janik-Haag** [comment]
https://github.com/NixOS/first-time-contribution-tagger will also be needing a new maintainer. Shouldn't be more than a version bump here and there, as long as GitHub doesn't break their API in any major way.

**Review by yayayayaka — APPROVED** [review]
Thanks for everything :purple_heart:

**Comment by rhendric** [comment]
Oof, this hurts. I've been a big fan of yours.

**Comment by 0x4A6F** [comment]
Thanks for all your work. :heart:

**Comment by drupol** [comment]
Thank you man... count on me on your fork :)

**Pull request merged**
