### PR TITLE
php: php upgrades

### PR DESCRIPTION
**Pull request by etu**
###### Motivation for this change
Upgrade PHP 7.4 and 8.0

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 125513` at a3c966cc run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/c85502d1639c15f8fe6ec599ab800f5a">php74Extensions.pcs</a></li>
    <li><a href="https://gist.github.com/04970991995110f74b48c33f1902e232">php74Extensions.pthreads</a></li>
    <li><a href="https://gist.github.com/a6f214bbc076a09bb42e90070a158e4a">php74Extensions.v8</a></li>
    <li><a href="https://gist.github.com/9bbb3fbbe772d493e7759cd17027452c">php74Extensions.v8js</a></li>
    <li><a href="https://gist.github.com/027f1dfa3cb32731e92e197e343c8c7b">php74Extensions.zmq</a></li>
    <li><a href="https://gist.github.com/a3685b63ef4631a41d46e9c0816e223f">php80Extensions.apcu_bc</a></li>
    <li><a href="https://gist.github.com/7d3a2724ee48341f938e020ef1500ea8">php80Extensions.couchbase</a></li>
    <li><a href="https://gist.github.com/91fe1f6d4a8fc451f85e6154f9da4524">php80Extensions.pcs</a></li>
    <li><a href="https://gist.github.com/27c68e5c6cfca861856ac27d5cccc864">php80Extensions.php_excel</a></li>
    <li><a href="https://gist.github.com/2314a146dd8de759963d53bac8330c3d">php80Extensions.pthreads</a></li>
    <li><a href="https://gist.github.com/f39f6de4a96de6a31c90bceb99e5d397">php80Extensions.v8</a></li>
    <li><a href="https://gist.github.com/6a2bbad21f24ce123984506c5d20ded9">php80Extensions.v8js</a></li>
    <li><a href="https://gist.github.com/97fcf8940bce8068ba2a148a7eae0dfe">php80Extensions.zmq</a></li>
  </ul>
</details>
<details>
  <summary>6 packages skipped due to time constraints:</summary>
  <ul>
    <li>hhvm</li>
    <li>libsForQt512.kcachegrind</li>
    <li>php74Extensions.pdlib</li>
    <li>pulseeffects-legacy</li>
    <li>pulseeffects-pw</li>
    <li>unit</li>
  </ul>
</details>
<details>
  <summary>207 packages built successfully:</summary>
  <ul>
    <li>adminer</li>
    <li>php (apacheHttpdPackages.php ,php74)</li>
    <li>arcanist</li>
    <li>bookstack</li>
    <li>engelsystem</li>
    <li>icingaweb2</li>
    <li>libsForQt5.kcachegrind (libsForQt515.kcachegrind ,plasma5Packages.kcachegrind)</li>
    <li>libsForQt514.kcachegrind</li>
    <li>lsp-plugins</li>
    <li>matomo</li>
    <li>matomo-beta</li>
    <li>nagios</li>
    <li>nextcloud-news-updater</li>
    <li>phoronix-test-suite</li>
    <li>php74Extensions.apcu</li>
    <li>php74Extensions.apcu_bc</li>
    <li>php74Extensions.ast</li>
    <li>php74Extensions.bcmath</li>
    <li>php74Extensions.bz2</li>
    <li>php74Extensions.calendar</li>
    <li>php74Extensions.couchbase</li>
    <li>php74Extensions.ctype</li>
    <li>php74Extensions.curl</li>
    <li>php74Extensions.dba</li>
    <li>php74Extensions.dom</li>
    <li>php74Extensions.enchant</li>
    <li>php74Extensions.event</li>
    <li>php74Extensions.exif</li>
    <li>php74Extensions.ffi</li>
    <li>php74Extensions.fileinfo</li>
    <li>php74Extensions.filter</li>
    <li>php74Extensions.ftp</li>
    <li>php74Extensions.gd</li>
    <li>php74Extensions.gettext</li>
    <li>php74Extensions.gmp</li>
    <li>php74Extensions.iconv</li>
    <li>php74Extensions.igbinary</li>
    <li>php74Extensions.imagick</li>
    <li>php74Extensions.imap</li>
    <li>php74Extensions.intl</li>
    <li>php74Extensions.json</li>
    <li>php74Extensions.ldap</li>
    <li>php74Extensions.mailparse</li>
    <li>php74Extensions.maxminddb</li>
    <li>php74Extensions.mbstring</li>
    <li>php74Extensions.memcached</li>
    <li>php74Extensions.mongodb</li>
    <li>php74Extensions.mysqli</li>
    <li>php74Extensions.mysqlnd</li>
    <li>php74Extensions.oci8</li>
    <li>php74Extensions.opcache</li>
    <li>php74Extensions.openssl</li>
    <li>php74Extensions.pcntl</li>
    <li>php74Extensions.pcov</li>
    <li>php74Extensions.pdo</li>
    <li>php74Extensions.pdo_dblib</li>
    <li>php74Extensions.pdo_mysql</li>
    <li>php74Extensions.pdo_oci</li>
    <li>php74Extensions.pdo_odbc</li>
    <li>php74Extensions.pdo_pgsql</li>
    <li>php74Extensions.pdo_sqlite</li>
    <li>php74Extensions.pdo_sqlsrv</li>
    <li>php74Extensions.pgsql</li>
    <li>php74Extensions.php_excel</li>
    <li>php74Extensions.pinba</li>
    <li>php74Extensions.posix</li>
    <li>php74Extensions.protobuf</li>
    <li>php74Extensions.pspell</li>
    <li>php74Extensions.rdkafka</li>
    <li>php74Extensions.readline</li>
    <li>php74Extensions.redis</li>
    <li>php74Extensions.session</li>
    <li>php74Extensions.shmop</li>
    <li>php74Extensions.simplexml</li>
    <li>php74Extensions.smbclient</li>
    <li>php74Extensions.snmp</li>
    <li>php74Extensions.snuffleupagus</li>
    <li>php74Extensions.soap</li>
    <li>php74Extensions.sockets</li>
    <li>php74Extensions.sodium</li>
    <li>php74Extensions.sqlite3</li>
    <li>php74Extensions.sqlsrv</li>
    <li>php74Extensions.swoole</li>
    <li>php74Extensions.sysvmsg</li>
    <li>php74Extensions.sysvsem</li>
    <li>php74Extensions.sysvshm</li>
    <li>php74Extensions.tidy</li>
    <li>php74Extensions.tokenizer</li>
    <li>php74Extensions.xdebug</li>
    <li>php74Extensions.xml</li>
    <li>php74Extensions.xmlreader</li>
    <li>php74Extensions.xmlrpc</li>
    <li>php74Extensions.xmlwriter</li>
    <li>php74Extensions.xsl</li>
    <li>php74Extensions.yaml</li>
    <li>php74Extensions.zend_test</li>
    <li>php74Extensions.zip</li>
    <li>php74Extensions.zlib</li>
    <li>php74Packages.box</li>
    <li>php74Packages.composer</li>
    <li>php74Packages.composer1</li>
    <li>php74Packages.deployer</li>
    <li>php74Packages.php-cs-fixer</li>
    <li>php74Packages.php-parallel-lint</li>
    <li>php74Packages.phpcbf</li>
    <li>php74Packages.phpcs</li>
    <li>php74Packages.phpmd</li>
    <li>php74Packages.phpstan</li>
    <li>php74Packages.psalm</li>
    <li>php74Packages.psysh</li>
    <li>php80</li>
    <li>php80Extensions.apcu</li>
    <li>php80Extensions.ast</li>
    <li>php80Extensions.bcmath</li>
    <li>php80Extensions.bz2</li>
    <li>php80Extensions.calendar</li>
    <li>php80Extensions.ctype</li>
    <li>php80Extensions.curl</li>
    <li>php80Extensions.dba</li>
    <li>php80Extensions.dom</li>
    <li>php80Extensions.enchant</li>
    <li>php80Extensions.event</li>
    <li>php80Extensions.exif</li>
    <li>php80Extensions.ffi</li>
    <li>php80Extensions.fileinfo</li>
    <li>php80Extensions.filter</li>
    <li>php80Extensions.ftp</li>
    <li>php80Extensions.gd</li>
    <li>php80Extensions.gettext</li>
    <li>php80Extensions.gmp</li>
    <li>php80Extensions.iconv</li>
    <li>php80Extensions.igbinary</li>
    <li>php80Extensions.imagick</li>
    <li>php80Extensions.imap</li>
    <li>php80Extensions.intl</li>
    <li>php80Extensions.ldap</li>
    <li>php80Extensions.mailparse</li>
    <li>php80Extensions.maxminddb</li>
    <li>php80Extensions.mbstring</li>
    <li>php80Extensions.memcached</li>
    <li>php80Extensions.mongodb</li>
    <li>php80Extensions.mysqli</li>
    <li>php80Extensions.mysqlnd</li>
    <li>php80Extensions.oci8</li>
    <li>php80Extensions.opcache</li>
    <li>php80Extensions.openssl</li>
    <li>php80Extensions.pcntl</li>
    <li>php80Extensions.pcov</li>
    <li>php80Extensions.pdlib</li>
    <li>php80Extensions.pdo</li>
    <li>php80Extensions.pdo_dblib</li>
    <li>php80Extensions.pdo_mysql</li>
    <li>php80Extensions.pdo_oci</li>
    <li>php80Extensions.pdo_odbc</li>
    <li>php80Extensions.pdo_pgsql</li>
    <li>php80Extensions.pdo_sqlite</li>
    <li>php80Extensions.pdo_sqlsrv</li>
    <li>php80Extensions.pgsql</li>
    <li>php80Extensions.pinba</li>
    <li>php80Extensions.posix</li>
    <li>php80Extensions.protobuf</li>
    <li>php80Extensions.pspell</li>
    <li>php80Extensions.rdkafka</li>
    <li>php80Extensions.readline</li>
    <li>php80Extensions.redis</li>
    <li>php80Extensions.session</li>
    <li>php80Extensions.shmop</li>
    <li>php80Extensions.simplexml</li>
    <li>php80Extensions.smbclient</li>
    <li>php80Extensions.snmp</li>
    <li>php80Extensions.snuffleupagus</li>
    <li>php80Extensions.soap</li>
    <li>php80Extensions.sockets</li>
    <li>php80Extensions.sodium</li>
    <li>php80Extensions.sqlite3</li>
    <li>php80Extensions.sqlsrv</li>
    <li>php80Extensions.swoole</li>
    <li>php80Extensions.sysvmsg</li>
    <li>php80Extensions.sysvsem</li>
    <li>php80Extensions.sysvshm</li>
    <li>php80Extensions.tidy</li>
    <li>php80Extensions.tokenizer</li>
    <li>php80Extensions.xdebug</li>
    <li>php80Extensions.xml</li>
    <li>php80Extensions.xmlreader</li>
    <li>php80Extensions.xmlwriter</li>
    <li>php80Extensions.xsl</li>
    <li>php80Extensions.yaml</li>
    <li>php80Extensions.zend_test</li>
    <li>php80Extensions.zip</li>
    <li>php80Extensions.zlib</li>
    <li>php80Packages.box</li>
    <li>php80Packages.composer</li>
    <li>php80Packages.composer1</li>
    <li>php80Packages.deployer</li>
    <li>php80Packages.php-cs-fixer</li>
    <li>php80Packages.php-parallel-lint</li>
    <li>php80Packages.phpcbf</li>
    <li>php80Packages.phpcs</li>
    <li>php80Packages.phpmd</li>
    <li>php80Packages.phpstan</li>
    <li>php80Packages.psalm</li>
    <li>php80Packages.psysh</li>
    <li>qcachegrind</li>
    <li>rss-bridge-cli</li>
    <li>wp-cli</li>
    <li>yle-dl</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Review by risicle — APPROVED** [review]
`nixpkgs-review` reveals no (new) breakage, nixos x86_64 & macos 10.15

**Comment by Ma27** [comment]
@aanderse @risicle @etu is there any reason to not backport patch releases?

**Comment by etu** [comment]
@Ma27 Yes, I haven't got around to it until now :wink:

**Pull request merged**
