### PR TITLE
doc: Add staging workflow diagram

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
Add diagram describing the staging workflow to Submitting changes docs. Depends on #105962 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
Rendered:

image

**Comment by Ericson2314** [comment]
The number of technologies that go into the this final quite remarkable :D.

**Comment by jtojnar** [comment]
Rebased onto master and checked that the image displays in epub too (using mupdf).

**Comment by ryantm** [comment]
Result of `nixpkgs-review pr 105986` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pandoc-lua-filters</li>
  </ul>
</details>

**Comment by jtojnar** [comment]
Changed pandoc-lua-filters platform to all.

**Review by ryantm — APPROVED** [review]
Code and rendering look good to me.

**Pull request merged**
