### PR TITLE
buildGoModule: enable strictDeps

### PR DESCRIPTION
**Pull request by Mic92**
This will improve cross compiling in the long run.
See also https://github.com/NixOS/nixpkgs/pull/82786

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by Ericson2314 — APPROVED** [review]

**Comment by Ericson2314** [comment]
@Mic92 teeny nit I feel bad saying, but I think normally `nativeBuildInputs` are before `buildInputs`?

**Comment by Mic92** [comment]
> @Mic92 teeny nit I feel bad saying, but I think normally `nativeBuildInputs` are before `buildInputs`?

swapped.

**Comment by Mic92** [comment]
All packages now build for me.

**Comment by Mic92** [comment]
Looks like staging is not really required for this one.

**Comment by matthewbauer** [comment]
A few macOS things broke from this:

https://hydra.nixos.org/eval/1576403#tabs-now-fail

I'm not actually sure why, but it looks like they are all missing Security framework.

**Comment by Mic92** [comment]
@matthewbauer Oh. Do you have a solution for this or should we disable it on macOS for the time being?

**Comment by Mic92** [comment]
Seems to be fixed by https://github.com/NixOS/nixpkgs/pull/83099/files

**Comment by Mic92** [comment]
Sorry for the breakage.

**Pull request merged**
