### PR TITLE
libretro.citra: fix broken build (ffmpeg -> ffmpeg_6)

### LINKED ISSUE #351162: Build failure: retroarchFull because of libretro citra core
### Steps To Reproduce

1. build *retroarchFull*

### Build log

```
error: builder for '/nix/store/5656wcj8bwi6ziyjjrc94bj3c07x53vp-libretro-citra-unstable-2024-01-24.drv' failed with exit code 2;
       last 10 log lines:
       > ./src/common/assert.h:33:15: note: in definition of macro 'ASSERT'
       >    33 |         if (!(_a_)) {                                                                              \
       >       |               ^~~
       > src/audio_core/hle/ffmpeg_decoder.cpp:215:56: error: 'struct AVFrame' has no member named 'channels'
       >   215 |                 response.num_channels = decoded_frame->channels;
       >       |                                                        ^~~~~~~~
       > src/audio_core/hle/ffmpeg_decoder.cpp:222:75: error: 'struct AVFrame' has no member named 'channels'
       >   222 |                     for (std::size_t channel(0); channel < decoded_frame->channels; channel++) {
       >       |                                                                           ^~~~~~~~
       > make: *** [Makefile:417: src/audio_core/hle/ffmpeg_decoder.o] Error 1
```

### Additional context

When adding retroarchFull to your system packages it will fail to build because of the citra core.
It seems like the citra core is incompatible with the latest ffmpeg module.

### Notify maintainers

@aanderse
@edwtjo
@thiagokokada
@matthewbauer 
@kolbycrouch

### Workaround
Use ffmpeg_6 as build input: https://github.com/NixOS/nixpkgs/blob/9801748d78845bda7f7b9d854edccef173a04c35/pkgs/applications/emulators/retroarch/cores.nix#L321

### Metadata

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Frontear**
Closes https://github.com/NixOS/nixpkgs/issues/351162

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Frontear** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 352220`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>libretro.citra</li>
    <li>retroarchFull</li>
  </ul>
</details>

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 352220`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>libretro.citra</li>
    <li>retroarchFull</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>libretro.citra</li>
    <li>retroarchFull</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:fast_forward: 1 package marked as broken and skipped:</summary>
  <ul>
    <li>libretro.citra</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:fast_forward: 1 package marked as broken and skipped:</summary>
  <ul>
    <li>libretro.citra</li>
  </ul>
</details>

**Review by khaneliman — APPROVED** [review]
LGTM, thanks!

**Review by thiagokokada — APPROVED** [review]

**Comment by thiagokokada** [comment]
CC @emilazy since you're trying to replace the older versions of ffmpeg.

**Comment by emilazy** [comment]
Upstream Citra is a dead project so I worry somewhat that this will never be fixed. Actually, I’m somewhat surprised that we carry this fork that has been [basically untouched all year](https://github.com/libretro/citra/commits/master) and is behind where upstream Citra was when we dropped it in https://github.com/NixOS/nixpkgs/pull/293312.

An active‐until‐yesterday(!) fork of Citra, used by things like the AUR package, merged an FFmpeg 7 compatibility PR:  https://github.com/PabloMK7/citra/pull/248. If we’re keeping this package but not actual Citra – though it seems a little odd to me given that development is more inactive than Citra or its forks – then we should probably apply that PR instead. I would prefer vendoring it in that case, given that the repository is now archived.

**Comment by thiagokokada** [comment]
> Upstream Citra is a dead project so I worry somewhat that this will never be fixed. Actually, I’m somewhat surprised that we carry this fork that has been [basically untouched all year](https://github.com/libretro/citra/commits/master) and is behind where upstream Citra was when we dropped it in https://github.com/NixOS/nixpkgs/pull/293312.
> 
> An active‐until‐yesterday(!) fork of Citra, used by things like the AUR package, merged an FFmpeg 7 compatibility PR:  https://github.com/PabloMK7/citra/pull/248. If we’re keeping this package but not actual Citra – though it seems a little odd to me given that development is more inactive than Citra or its forks – then we should probably apply that PR instead. I would prefer vendoring it in that case, given that the repository is now archived.

I have no strong feelings for us to switch to this fork. The only reason I think we never switch is because nobody bothered to open a PR.

**Comment by emilazy** [comment]
I am not sure we can switch to it, since this is a libretro fork and I don’t know that Citra ever supported libretro itself. We removed Citra proper and this libretro version is behind upstream Citra, so it surprises me that we’re choosing to still carry this, but if we do then we should try to apply the FFmpeg 7 PR from the Citra fork I linked.

**Comment by thiagokokada** [comment]
> I am not sure we can switch to it, since this is a libretro fork and I don’t know that Citra ever supported libretro itself. We removed Citra proper and this libretro version is behind upstream Citra, so it surprises me that we’re choosing to still carry this, but if we do then we should try to apply the FFmpeg 7 PR from the Citra fork I linked.

Oh ok, I thought this fork supported libretro.

In this case, I am fine either using the ffmpeg embedded in libretro/citra itself or backporting the ffmpeg patches if possible.

**Comment by Frontear** [comment]
> but if we do then we should try to apply the FFmpeg 7 PR from the Citra fork I linked.

I'll do a little bit of investigating and see if I an propose a more elegant solution to this derivation, either by updating source or patching!

**Pull request merged**
