### PR TITLE
fetchpatch: quote excludes

### PR DESCRIPTION
**Pull request by timokau**
The excludes argument of fetchpatch is based on the `-x` flag of
filterdiff. That flag takes a "pattern" as an argument, which is similar
to a bash glob. For example 'some/path/*' would be acceptable and
exclude all files in some/path.

Currently those excludes are passed without quoting, leading to
unexpected things (the shell expanding the glob).

This shouldn't break anything, since nobody actually uses anything but plain paths in `excludes` yet. It shouldn't  cause any rebuilds either, since the result of fetchpatch doesn't change and the hashes are fixed.

@vcunat @globin 

There used to also be a `includes` that had the same error, but that patch (by @Ericson2314) was shortly after reverted (by mistake? the commit message doesn't indicate why).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ericson2314** [comment]
@volth Good call. @timokau It was part of https://github.com/NixOS/nixpkgs/pull/41420 which was revert. Feel free to revert the revert, but the newer version of that PR doesn't use it so it will be dead code.

**Comment by timokau** [comment]
@dotlambda Oh I only grepped through master. But the patch fetched in that commit actually ends up to be empty. That has happened to me more often than I'd like and I recognize the hash by now :grin: 

So that shows that we should probably apply this to 18.03 too.

@volth Good point. Changed.

@Ericson2314 I think it makes sense to offer both, so I included that.

**Review by vcunat — APPROVED** [review]
Seems good.  Personally I'd use an assert instead of `meta.broken` for this.

**Comment by vcunat** [comment]
Perhaps we might additionally block empty result of `fetchpatch` somehow, either make the derivation fail or recognize the hash at evaluation time.

**Comment by timokau** [comment]
I have added another commit that checks for empty files. It is a bit verbose because I check at every step, but I think the improved error messages are worth it.

**Comment by timokau** [comment]
While we're at it: I think it would be neat to add an option to reverse a patch. That can already be done with `${args.postFetch or ""}` right now though and could be considered feature creep. What do you think?

**Review by fpletz — APPROVED** [review]

**Comment by vcunat** [comment]
The ability to revert a patch sounds natural, though it seems rarely useful in nixpkgs to me.

**Comment by timokau** [comment]
It would be useful if a bug was introduced by some commit and the commit isn't reversed yet upstream. I've needed that at least once for sage and ended up downloading & reversing the patch. But its not all that common.

**Comment by timokau** [comment]
Since its usually easier to get feedback about something after implementing than it is to get feedback for ideas, I went ahead and implemented it.

**Review by matthewbauer — APPROVED** [review]

**Comment by vcunat** [comment]
Borg reported this changes the `sage*` builds, but I suppose @timokau knows about that.

**Comment by dotlambda** [comment]
> Borg reported this changes the sage* builds

That's because @timokau immediately made use of the new revert feature: https://github.com/NixOS/nixpkgs/pull/43538/files#diff-5bd819821ddc9ac4a654e7ea45752448.

**Pull request merged**
