### PR TITLE
traefik: 2.4.8 -> 2.4.13

### PR DESCRIPTION
**Pull request by amaxine**
###### Motivation for this change
https://github.com/traefik/traefik/blob/v2.4.13/CHANGELOG.md

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
@maxeaubrey it seems as the VM-test is failing (can reproduce this locally). Would you mind looking into this? :)

**Comment by risicle** [comment]
@Ma27 do you mean `nixosTests.traefik`? It's passing for me, nixos x86_64.

**Comment by Ma27** [comment]
Nice, seems to be a flaky test then. I got the same error as in https://logs.nix.ci/?key=nixos/nixpkgs.131867&attempt_id=34bc5151-08f8-4a4d-b812-d5dd9ab5c20d.

**Comment by risicle** [comment]
(FWIW builds happily macos 10.15)

**Comment by risicle** [comment]
I'm doing it on quite an unloaded system - might be a timing thing, not sure if that `curl` request retries at all.

**Comment by maxeaubrey** [comment]
Sorry, I forgot there's a test. Is it the same flakiness as #115418?

**Comment by Ma27** [comment]
Ahh most likely, yes. But to me this doesn't seem as if it's an actual problem with traefik, but with the test itself. So while it'd be good to get this fixed, I don't think that we should block the update here. WDYT @risicle ?

**Comment by maxeaubrey** [comment]
If it's that flakiness it's just racing against traefik being ready to serve traffic. I don't think the test should bock the update in that situation (though fixing it would be nice to address regardless, but a sleep just seemed... lazy and inappropriate, whereas retrying until success seemed potentially misguided - hence why I didn't commit a fix last time.).

**Comment by risicle** [comment]
Yes. A tricky conundrum. Personally I'd probably do a first retry loop to get to the point where we know the service is up, but then perhaps another request that *definitely* has to pass first time?

**Comment by maxeaubrey** [comment]
> Yes. A tricky conundrum. Personally I'd probably do a first retry loop to get to the point where we know the service is up, but then perhaps another request that _definitely_ has to pass first time?

So just adding a `client.wait_until_succeeds` on the first curl, before keeping the current two subtests?

**Comment by risicle** [comment]
Yeah that's what I'd try.

**Comment by maxeaubrey** [comment]
Sorry, didn't really have time lately. That change seems to do the trick (plus I forgot to push the actual bump to 2.4.13 in the last force push, oops!)

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Pull request merged**
