### PR TITLE
linuxPackages.nvidia_x11_beta: 525.89.02 -> 530.30.02

### PR DESCRIPTION
**Pull request by Kiskae**
###### Description of changes

- Release highlights since 525.89.02:
  - Added an application profile to avoid performance problems in Xfce 4 when the OpenGL compositor backend is enabled along with G-SYNC.
  - Added support for suspend and resume when using GSP firmware.
  - Moved the nvidia-settings application icon into the ‘hicolor’ icon theme, which allows it to be customized by other icon themes selected in the desktop environment.
  - Fixed a bug that prevented PRIME render offload from working for Wayland applications when running on a system with an AMD iGPU.
  - Fixed a bug that prevented nvidia-installer from recording kernel log output to the installer log in some module loading failure paths.
  - Changed nvidia-installer to no longer use the $XDG_DATA_DIRS environment variable. XDG data files are now installed to a path specified by the --xdg-data-dir option, or /usr/share if not specified. This fixes a problem when Flatpak is installed that caused the installer to place the nvidia-settings.desktop file in /root/.local/share/flatpak/exports/share/applications.
  - Changed the behavior of glXGetRefreshRateSGI() for non-integer refresh rates to round to the nearest whole number rather than truncating.
  - Changed the compression format of the .run installer package from xz to zstd. This results in a smaller compressed package, and faster decompression performance. A fallback zstd decompressor is embedded into the installer package for systems which do not already have a zstd decompression program installed.
  - Fixed a bug that caused nvidia-installer to mistakenly unload some already loaded non-NVIDIA kernel modules.
  - Added compatibility for Linux kernels with Indirect Branch Tracking (IBT).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kiskae** [comment]
Result of `nixpkgs-review pr 218876` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>62 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11</li>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11_beta</li>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11_production</li>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_beta</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_6_1_hardened.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_6_2.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_xanmod_stable.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_legacy340</li>
    <li>linuxPackages-libre.nvidia_x11_legacy340</li>
    <li>linuxPackages.nvidia_x11_legacy340</li>
    <li>linuxPackages_5_10_hardened.nvidia_x11_legacy340</li>
    <li>linuxPackages_5_15_hardened.nvidia_x11_legacy340</li>
    <li>linuxPackages_5_4_hardened.nvidia_x11</li>
    <li>linuxPackages_5_4_hardened.nvidia_x11_beta</li>
    <li>linuxPackages_5_4_hardened.nvidia_x11_beta_open</li>
    <li>linuxPackages_5_4_hardened.nvidia_x11_legacy340</li>
    <li>linuxPackages_5_4_hardened.nvidia_x11_legacy390</li>
    <li>linuxPackages_5_4_hardened.nvidia_x11_legacy470</li>
    <li>linuxPackages_5_4_hardened.nvidia_x11_production</li>
    <li>linuxPackages_5_4_hardened.nvidia_x11_vulkan_beta</li>
    <li>linuxPackages_6_1_hardened.nvidia_x11_legacy340</li>
    <li>linuxPackages_hardened.nvidia_x11_legacy340</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_beta</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_beta_open</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_legacy340</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_legacy390</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_legacy470</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_production</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_vulkan_beta</li>
    <li>linuxPackages_latest-libre.nvidia_x11_legacy340</li>
    <li>linuxPackages_latest.nvidia_x11_legacy340</li>
    <li>linuxPackages_lqx.nvidia_x11_legacy340</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_legacy340</li>
    <li>linuxPackages_xanmod.nvidia_x11_legacy340</li>
    <li>linuxPackages_xanmod_latest.nvidia_x11_legacy340</li>
    <li>linuxPackages_xanmod_stable.nvidia_x11_legacy340</li>
    <li>linuxPackages_zen.nvidia_x11_legacy340</li>
  </ul>
</details>
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>13 packages failed to build:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_beta</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11_beta (linuxKernel.packages.linux_4_14_hardened.nvidia_x11_beta)</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_beta</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11_beta (linuxKernel.packages.linux_4_19_hardened.nvidia_x11_beta)</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_beta</li>
    <li>linuxPackages_5_10_hardened.nvidia_x11_beta (linuxKernel.packages.linux_5_10_hardened.nvidia_x11_beta)</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_beta</li>
    <li>linuxPackages_latest.nvidia_x11_legacy390 (linuxKernel.packages.linux_6_2.nvidia_x11_legacy390)</li>
    <li>linuxPackages_latest.nvidia_x11_legacy470 (linuxKernel.packages.linux_6_2.nvidia_x11_legacy470)</li>
    <li>linuxPackages_latest-libre.nvidia_x11_legacy390 (linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy390)</li>
    <li>linuxPackages_latest-libre.nvidia_x11_legacy470 (linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy470)</li>
    <li>linuxPackages_zen.nvidia_x11_legacy390 (linuxKernel.packages.linux_zen.nvidia_x11_legacy390)</li>
    <li>linuxPackages_zen.nvidia_x11_legacy470 (linuxKernel.packages.linux_zen.nvidia_x11_legacy470)</li>
  </ul>
</details>
<details>
  <summary>112 packages built:</summary>
  <ul>
    <li>bumblebee</li>
    <li>geekbench (geekbench5)</li>
    <li>geekbench4</li>
    <li>gwe</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11 (linuxKernel.packages.linux_4_14.nvidia_x11_production)</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_vulkan_beta</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11 (linuxKernel.packages.linux_4_14_hardened.nvidia_x11 ,linuxPackages_4_14_hardened.nvidia_x11_production)</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11_beta_open (linuxKernel.packages.linux_4_14_hardened.nvidia_x11_beta_open)</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11_legacy340 (linuxKernel.packages.linux_4_14_hardened.nvidia_x11_legacy340)</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11_legacy390 (linuxKernel.packages.linux_4_14_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_4_14_hardened.nvidia_x11_legacy470)</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_4_14_hardened.nvidia_x11_vulkan_beta)</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11 (linuxKernel.packages.linux_4_19.nvidia_x11_production)</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_vulkan_beta</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11 (linuxKernel.packages.linux_4_19_hardened.nvidia_x11 ,linuxPackages_4_19_hardened.nvidia_x11_production)</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11_beta_open (linuxKernel.packages.linux_4_19_hardened.nvidia_x11_beta_open)</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11_legacy340 (linuxKernel.packages.linux_4_19_hardened.nvidia_x11_legacy340)</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11_legacy390 (linuxKernel.packages.linux_4_19_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_4_19_hardened.nvidia_x11_legacy470)</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_4_19_hardened.nvidia_x11_vulkan_beta)</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11 (linuxKernel.packages.linux_5_10.nvidia_x11_production)</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_vulkan_beta</li>
    <li>linuxPackages_5_10_hardened.nvidia_x11 (linuxKernel.packages.linux_5_10_hardened.nvidia_x11 ,linuxPackages_5_10_hardened.nvidia_x11_production)</li>
    <li>linuxPackages_5_10_hardened.nvidia_x11_beta_open (linuxKernel.packages.linux_5_10_hardened.nvidia_x11_beta_open)</li>
    <li>linuxPackages_5_10_hardened.nvidia_x11_legacy390 (linuxKernel.packages.linux_5_10_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_5_10_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_10_hardened.nvidia_x11_legacy470)</li>
    <li>linuxPackages_5_10_hardened.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_5_10_hardened.nvidia_x11_vulkan_beta)</li>
    <li>linuxPackages.nvidia_x11 (linuxKernel.packages.linux_5_15.nvidia_x11 ,linuxPackages.nvidia_x11_production)</li>
    <li>linuxPackages.nvidia_x11_beta (linuxKernel.packages.linux_5_15.nvidia_x11_beta)</li>
    <li>linuxPackages.nvidia_x11_beta_open (linuxKernel.packages.linux_5_15.nvidia_x11_beta_open)</li>
    <li>linuxPackages.nvidia_x11_legacy390 (linuxKernel.packages.linux_5_15.nvidia_x11_legacy390)</li>
    <li>linuxPackages.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_15.nvidia_x11_legacy470)</li>
    <li>linuxPackages.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_5_15.nvidia_x11_vulkan_beta)</li>
    <li>linuxPackages_hardened.nvidia_x11 (linuxPackages_5_15_hardened.nvidia_x11 ,linuxPackages_hardened.nvidia_x11_production)</li>
    <li>linuxPackages_hardened.nvidia_x11_beta (linuxPackages_5_15_hardened.nvidia_x11_beta)</li>
    <li>linuxPackages_hardened.nvidia_x11_beta_open (linuxPackages_5_15_hardened.nvidia_x11_beta_open)</li>
    <li>linuxPackages_hardened.nvidia_x11_legacy390 (linuxPackages_5_15_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_hardened.nvidia_x11_legacy470 (linuxPackages_5_15_hardened.nvidia_x11_legacy470)</li>
    <li>linuxPackages_hardened.nvidia_x11_vulkan_beta (linuxPackages_5_15_hardened.nvidia_x11_vulkan_beta)</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11 (linuxKernel.packages.linux_5_4.nvidia_x11_production)</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_legacy340</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_vulkan_beta</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11 (linuxKernel.packages.linux_6_1.nvidia_x11_production)</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_beta</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_vulkan_beta</li>
    <li>linuxPackages_6_1_hardened.nvidia_x11 (linuxKernel.packages.linux_6_1_hardened.nvidia_x11 ,linuxPackages_6_1_hardened.nvidia_x11_production)</li>
    <li>linuxPackages_6_1_hardened.nvidia_x11_beta (linuxKernel.packages.linux_6_1_hardened.nvidia_x11_beta)</li>
    <li>linuxPackages_6_1_hardened.nvidia_x11_beta_open (linuxKernel.packages.linux_6_1_hardened.nvidia_x11_beta_open)</li>
    <li>linuxPackages_6_1_hardened.nvidia_x11_legacy390 (linuxKernel.packages.linux_6_1_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_6_1_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_6_1_hardened.nvidia_x11_legacy470)</li>
    <li>linuxPackages_6_1_hardened.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_6_1_hardened.nvidia_x11_vulkan_beta)</li>
    <li>linuxPackages_latest.nvidia_x11 (linuxKernel.packages.linux_6_2.nvidia_x11 ,linuxPackages_latest.nvidia_x11_production)</li>
    <li>linuxPackages_latest.nvidia_x11_beta (linuxKernel.packages.linux_6_2.nvidia_x11_beta)</li>
    <li>linuxPackages_latest.nvidia_x11_beta_open (linuxKernel.packages.linux_6_2.nvidia_x11_beta_open)</li>
    <li>linuxPackages_latest.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_6_2.nvidia_x11_vulkan_beta)</li>
    <li>linuxPackages_latest-libre.nvidia_x11 (linuxKernel.packages.linux_latest_libre.nvidia_x11 ,linuxPackages_latest-libre.nvidia_x11_production)</li>
    <li>linuxPackages_latest-libre.nvidia_x11_beta (linuxKernel.packages.linux_latest_libre.nvidia_x11_beta)</li>
    <li>linuxPackages_latest-libre.nvidia_x11_beta_open (linuxKernel.packages.linux_latest_libre.nvidia_x11_beta_open)</li>
    <li>linuxPackages_latest-libre.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_latest_libre.nvidia_x11_vulkan_beta)</li>
    <li>linuxPackages-libre.nvidia_x11 (linuxKernel.packages.linux_libre.nvidia_x11 ,linuxPackages-libre.nvidia_x11_production)</li>
    <li>linuxPackages-libre.nvidia_x11_beta (linuxKernel.packages.linux_libre.nvidia_x11_beta)</li>
    <li>linuxPackages-libre.nvidia_x11_beta_open (linuxKernel.packages.linux_libre.nvidia_x11_beta_open)</li>
    <li>linuxPackages-libre.nvidia_x11_legacy390 (linuxKernel.packages.linux_libre.nvidia_x11_legacy390)</li>
    <li>linuxPackages-libre.nvidia_x11_legacy470 (linuxKernel.packages.linux_libre.nvidia_x11_legacy470)</li>
    <li>linuxPackages-libre.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_libre.nvidia_x11_vulkan_beta)</li>
    <li>linuxPackages_lqx.nvidia_x11 (linuxKernel.packages.linux_lqx.nvidia_x11 ,linuxPackages_lqx.nvidia_x11_production)</li>
    <li>linuxPackages_lqx.nvidia_x11_beta (linuxKernel.packages.linux_lqx.nvidia_x11_beta)</li>
    <li>linuxPackages_lqx.nvidia_x11_beta_open (linuxKernel.packages.linux_lqx.nvidia_x11_beta_open)</li>
    <li>linuxPackages_lqx.nvidia_x11_legacy390 (linuxKernel.packages.linux_lqx.nvidia_x11_legacy390)</li>
    <li>linuxPackages_lqx.nvidia_x11_legacy470 (linuxKernel.packages.linux_lqx.nvidia_x11_legacy470)</li>
    <li>linuxPackages_lqx.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_lqx.nvidia_x11_vulkan_beta)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11 (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11 ,linuxPackages_testing_bcachefs.nvidia_x11_production)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_beta (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_beta)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_beta_open (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_beta_open)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_legacy390 (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy390)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_legacy470 (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy470)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_vulkan_beta)</li>
    <li>linuxPackages_xanmod.nvidia_x11 (linuxKernel.packages.linux_xanmod.nvidia_x11 ,linuxPackages_xanmod.nvidia_x11_production)</li>
    <li>linuxPackages_xanmod.nvidia_x11_beta (linuxKernel.packages.linux_xanmod.nvidia_x11_beta)</li>
    <li>linuxPackages_xanmod.nvidia_x11_beta_open (linuxKernel.packages.linux_xanmod.nvidia_x11_beta_open)</li>
    <li>linuxPackages_xanmod.nvidia_x11_legacy390 (linuxKernel.packages.linux_xanmod.nvidia_x11_legacy390)</li>
    <li>linuxPackages_xanmod.nvidia_x11_legacy470 (linuxKernel.packages.linux_xanmod.nvidia_x11_legacy470)</li>
    <li>linuxPackages_xanmod.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_xanmod.nvidia_x11_vulkan_beta)</li>
    <li>linuxPackages_xanmod_latest.nvidia_x11 (linuxKernel.packages.linux_xanmod_latest.nvidia_x11 ,linuxPackages_xanmod_latest.nvidia_x11_production ,linuxPackages_xanmod_stable.nvidia_x11 ,linuxPackages_xanmod_stable.nvidia_x11_production)</li>
    <li>linuxPackages_xanmod_latest.nvidia_x11_beta (linuxKernel.packages.linux_xanmod_latest.nvidia_x11_beta ,linuxPackages_xanmod_stable.nvidia_x11_beta)</li>
    <li>linuxPackages_xanmod_latest.nvidia_x11_beta_open (linuxKernel.packages.linux_xanmod_latest.nvidia_x11_beta_open ,linuxPackages_xanmod_stable.nvidia_x11_beta_open)</li>
    <li>linuxPackages_xanmod_latest.nvidia_x11_legacy390 (linuxKernel.packages.linux_xanmod_latest.nvidia_x11_legacy390 ,linuxPackages_xanmod_stable.nvidia_x11_legacy390)</li>
    <li>linuxPackages_xanmod_latest.nvidia_x11_legacy470 (linuxKernel.packages.linux_xanmod_latest.nvidia_x11_legacy470 ,linuxPackages_xanmod_stable.nvidia_x11_legacy470)</li>
    <li>linuxPackages_xanmod_latest.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_xanmod_latest.nvidia_x11_vulkan_beta ,linuxPackages_xanmod_stable.nvidia_x11_vulkan_beta)</li>
    <li>linuxPackages_zen.nvidia_x11 (linuxKernel.packages.linux_zen.nvidia_x11 ,linuxPackages_zen.nvidia_x11_production)</li>
    <li>linuxPackages_zen.nvidia_x11_beta (linuxKernel.packages.linux_zen.nvidia_x11_beta)</li>
    <li>linuxPackages_zen.nvidia_x11_beta_open (linuxKernel.packages.linux_zen.nvidia_x11_beta_open)</li>
    <li>linuxPackages_zen.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_zen.nvidia_x11_vulkan_beta)</li>
    <li>primus</li>
    <li>xpraWithNvenc</li>
  </ul>
</details>

**Comment by Kiskae** [comment]
The `legacy390` branch is no longer getting updates from nvidia

**Comment by Kiskae** [comment]
This release also adds the `nvidia.NVreg_EnableResizableBar=1` kernel parameter to enable resizable BAR

**Comment by astatide** [comment]
I've been running this PR / version for the last day or so; is there anything I could to do help test / report on since I'm using it?

**Comment by ConnorBaker** [comment]
Hi all,

This PR fixes `nixGL` for me (as originally mentioned in https://github.com/guibou/nixGL/issues/126). I personally would like to see it merged sooner than later.

Are there any outstanding blockers or fixes required? More than happy to help test anything required.

**Comment by Kiskae** [comment]
This is probably mostly an update that is only beta because they updated their toolchain and not because of any functional reason. These past 3 weeks I've not noticed any issues that didn't happen with older drivers.

**Comment by Kiskae** [comment]
It appears nvidia released `530.41.03` last friday, but it was never announced and the sources haven't been mirrored to their github repositories.

**Comment by Kiskae** [comment]
This PR will probably be superceded by #222762 when nvidia finishes publishing to their repositories.

**Comment by Kiskae** [comment]
Superseded by #222762, packaging changes were merged into that one as well.

**Pull request closed without merging**
