### PR TITLE
fwupd: wrap programs needed in PATH

### LINKED ISSUE #65658: fwupd: Can't find efibootmgr
**Describe the bug**

As I am trying to upgrade my XPS 13, fwupd can't find `efibootmgr`
```
Failed to execute child process “efibootmgr” (No such file or directory)
```

**To Reproduce**

```
# fwupdmgr update
Downloading 0.1.5.0 for XPS 13 9380 System Firmware...
Decompressing…           [***************************************]
Authenticating…          [***************************************]
Updating XPS 13 9380 System Firmware…                            ]
Scheduling…              [***************************************]
Failed to execute child process “efibootmgr” (No such file or directory)
```

**Expected behavior**
Update completes

**Additional context**
I am using nixos-unstable

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.0, NixOS, 19.09pre185259.362be9608c3 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre186460.c4fec1c6314, nixos-19.03-19.03.173182.96151a48dd6, nixos-unstable-19.09pre186460.c4fec1c6314"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
Should fix #65658. ~I we dislike this approach we could add entries to `PATH` with the wrapper.~

**Edit**: let's do that

cc @baracoder @tadfisher 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by baracoder** [comment]
I've checked out this branch and performed a rebuild switch, unfortunately fwupd does fail with segmentation fault
```
● fwupd.service - Firmware update daemon
   Loaded: loaded (/nix/store/25fnylavzacwnzi4d1p91rf7hgvp6dgd-fwupd-1.2.8/lib/systemd/system/fwupd.service; linked; vendor preset: enabled)
   Active: failed (Result: signal) since Sat 2019-08-03 13:39:11 CEST; 16s ago
     Docs: https://fwupd.org/
  Process: 13705 ExecStart=/nix/store/25fnylavzacwnzi4d1p91rf7hgvp6dgd-fwupd-1.2.8/libexec/fwupd/fwupd (code=killed, signal=SEGV)
 Main PID: 13705 (code=killed, signal=SEGV)

Aug 03 13:39:11 hex systemd[1]: Starting Firmware update daemon...
Aug 03 13:39:11 hex systemd[1]: fwupd.service: Main process exited, code=killed, status=11/SEGV
Aug 03 13:39:11 hex systemd[1]: fwupd.service: Failed with result 'signal'.
Aug 03 13:39:11 hex systemd[1]: Failed to start Firmware update daemon.

```

**Comment by worldofpeace** [comment]
@baracoder How about now?

**Comment by baracoder** [comment]
@worldofpeace sorry for the delay. It works with the new changes. (Writing from a successfully updated laptop)

**Comment by worldofpeace** [comment]
Thank you @baracoder for testing :+1:

**Pull request merged**
