### PR TITLE
redshift, xarchiver: add hicolor-icon-theme to buildInputs

### PR DESCRIPTION
**Pull request by rardiol**
###### Motivation for this change

https://github.com/NixOS/nixpkgs/issues/10370

maintainers @domenkozar @yegortimoshenko 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by jtojnar — CHANGES_REQUESTED** [review]
`hicolor-icon-theme` is now spelt with dashes.

**Review by lukateras — DISMISSED** [review]
`find $(nix-build '<nixpkgs>' -A redshift --no-out-link) -name \*.cache | wc -l` returns 0, so I don't think #10370 applies here.

**Comment by rardiol** [comment]
really? I got a conflict between those two today. And i have this in my nix store:

> /nix/store/mp6331kwvvd2yl6z4ax2vp4y9rpgi60y-redshift-1.11/share/icons/hicolor/icon-theme.cache

Also changed name to using dashes.

**Comment by yegortimoshenko** [comment]
- system: `"x86_64-linux"`
 - host os: `Linux 4.14.21, NixOS, 18.03pre129218.36b0efc12f4 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-hardware, nixos-18.03pre130151.268d99b1fe4, nixos-overlay"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

I have `/nix/store/xxdnjsc6vhqw6wb8zk9v6663grr4n623-redshift-1.11` and `/nix/store/y0j5m8lcrs81870sgmdijjn5ha86h5zm-redshift-1.11` in the store that do not have a cache file, and `/nix/store/y0j5m8lcrs81870sgmdijjn5ha86h5zm-redshift-1.11` that does have a cache file. Perhaps someone has recently made a change elsewhere that affected this elsewhere, but I don't know of any.

I wouldn't mind a preemptive change in `redshift`.

**Comment by rardiol** [comment]
Commit 47f25fa fixes this on redshift. Is adding the hicolor dependency or manually removing the better way to fix the issue?

**Comment by yegortimoshenko** [comment]
I think dependency is better (more declarative) than a manual deletion of the cache file.

**Comment by yegortimoshenko** [comment]
Thanks!

**Pull request merged**
