### PR TITLE
dotnet-sdk: 6.0.201 -> 6.0.202

### PR DESCRIPTION
**Pull request by mdarocha**
###### Description of changes

https://devblogs.microsoft.com/dotnet/april-2022-updates/

This update, among other things, fixes `dotnet format`, which was broken in 6.0.200.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Smaug123** [comment]
On darwin-aarch64, `mono` failed to build under `nix run nixpkgs#nixpkgs-review pr https://github.com/NixOS/nixpkgs/pull/168486`, but I don't yet know whether this is a) consistent and b) true on master. (And I'm going to bed now.)

**Comment by mdarocha** [comment]
> On darwin-aarch64, `mono` twice failed to build under `nix run nixpkgs#nixpkgs-review pr https://github.com/NixOS/nixpkgs/pull/168486`, but I don't yet know whether this is true on master. (And I'm going to bed now.)
> 
> ```
> /nix/store/cmcl1jichs33ynwv5apzs8r8ndx2w2pi-bash-5.1-p16/bin/bash ../mkinstalldirs _tmpinst/bin
> mkdir -p -- _tmpinst/bin
> cp mono-wrapper _tmpinst/bin/mono
> echo '#! /bin/sh' > _tmpinst/bin/ilasm ; \
> r=`pwd`; m=`cd /private/tmp/nix-build-mono-6.12.0.122.drv-1/mono-6.12.0.122/mcs && pwd`; \
> echo 'exec "'"$r/_tmpinst/bin/mono"'" "'"$m/ilasm/ilasm.exe"'" "$@"' >> _tmpinst/bin/ilasm ; \
> chmod +x _tmpinst/bin/ilasm
> echo '#! /bin/sh' > _tmpinst/bin/csc ; \
> r=`pwd`; m=`cd /private/tmp/nix-build-mono-6.12.0.122.drv-1/mono-6.12.0.122/mcs && pwd`; \
> echo 'exec "'"$r/_tmpinst/bin/mono"'" "'"/private/tmp/nix-build-mono-6.12.0.122.drv-1/mono-6.12.0.122/external/roslyn-binaries/Microsoft.Net.Compilers/3.6.0/csc.exe"'" "$@"' >> _tmpinst/bin/csc ; \
> chmod +x _tmpinst/bin/csc
> echo '#! /bin/sh' > _tmpinst/bin/mcs ; \
> r=`pwd`; m=`cd /private/tmp/nix-build-mono-6.12.0.122.drv-1/mono-6.12.0.122/mcs && pwd`; \
> echo 'exec "'"$r/_tmpinst/bin/mono"'" "'"$m/class/lib/net_4_x/mcs.exe"'" "$@"' >> _tmpinst/bin/mcs ; \
> chmod +x _tmpinst/bin/mcs
> echo '#! /bin/sh' > _tmpinst/bin/al ; \
> r=`pwd`; m=`cd /private/tmp/nix-build-mono-6.12.0.122.drv-1/mono-6.12.0.122/mcs && pwd`; \
> echo 'exec "'"$r/_tmpinst/bin/mono"'" "'"$m/class/lib/net_4_x/al.exe"'" "$@"' >> _tmpinst/bin/al ; \
> chmod +x _tmpinst/bin/al
> if test -w /private/tmp/nix-build-mono-6.12.0.122.drv-1/mono-6.12.0.122/mcs; then :; else chmod -R +w /private/tmp/nix-build-mono-6.12.0.122.drv-1/mono-6.12.0.122/mcs; fi
> cd /private/tmp/nix-build-mono-6.12.0.122.drv-1/mono-6.12.0.122/mcs && make --no-print-directory -s NO_DIR_CHECK=1 PROFILES='binary_reference_assemblies net_4_x xbuild_12 xbuild_14              ' CC='clang' all-profiles
> mkdir -p -- build/deps
> /nix/store/cmcl1jichs33ynwv5apzs8r8ndx2w2pi-bash-5.1-p16/bin/bash: line 1: mono: command not found
> make[6]: *** [build/profiles/build.make:134: build/deps/basic-profile-check.exe] Error 127
> *** The runtime 'mono' doesn't appear to be usable.
> *** Trying the 'monolite-macos/1A5E0066-58DC-428A-B21C-0AD6CDAE2789' directory.
> make[8]: *** [build/profiles/build.make:134: build/deps/basic-profile-check.exe] Segmentation fault: 11
> *** The contents of your 'monolite-macos/1A5E0066-58DC-428A-B21C-0AD6CDAE2789' directory may be out-of-date
> *** You may want to try 'make get-monolite-latest'
> make[8]: *** [build/profiles/build.make:117: do-profile-check-monolite] Error 1
> make[7]: *** [build/profiles/build.make:93: do-profile-check] Error 2
> make[6]: *** [build/profiles/build.make:129: do-profile-check-monolite] Error 2
> make[5]: *** [build/profiles/build.make:93: do-profile-check] Error 2
> ```

Hmm, `mono` should not be affected by these changes. I can't test this, since I have no access to Apple hardware, but the CI builds seem to have passed fine. Isn't it some issue with your local configuration?

**Comment by Smaug123** [comment]
Very possibly! Feel free not to consider this blocking.
-------- Original Message --------

**Comment by gador** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 168486` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package blacklisted:
</summary>
<ul>
<li>tests.writers</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>osu-lazer: log was empty</li>
  </ul>
</details>
<details>
<summary>
15 packages built:
</summary>
<ul>
<li>ArchiSteamFarm</li>
<li>btcpayserver</li>
<li>discordchatexporter-cli</li>
<li>dotnet-aspnetcore (dotnetCorePackages.aspnetcore_6_0)</li>
<li>dotnet-runtime (dotnetCorePackages.runtime_6_0)</li>
<li>dotnet-sdk (dotnet-sdk_6 ,dotnetCorePackages.sdk_6_0)</li>
<li>github-runner</li>
<li>inklecate</li>
<li>jackett</li>
<li>nbxplorer</li>
<li>omnisharp-roslyn</li>
<li>opentabletdriver</li>
<li>pinta</li>
<li>pre-commit</li>
<li>ryujinx</li>
</ul>
</details>

**Comment by mdarocha** [comment]
`osu-lazer` should be fixed now

**Comment by gador** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 168486` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package blacklisted:
</summary>
<ul>
<li>tests.writers</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>osu-lazer: log was empty</li>
  </ul>
</details>
<details>
<summary>
15 packages built:
</summary>
<ul>
<li>ArchiSteamFarm</li>
<li>btcpayserver</li>
<li>discordchatexporter-cli</li>
<li>dotnet-aspnetcore (dotnetCorePackages.aspnetcore_6_0)</li>
<li>dotnet-runtime (dotnetCorePackages.runtime_6_0)</li>
<li>dotnet-sdk (dotnet-sdk_6 ,dotnetCorePackages.sdk_6_0)</li>
<li>github-runner</li>
<li>inklecate</li>
<li>jackett</li>
<li>nbxplorer</li>
<li>omnisharp-roslyn</li>
<li>opentabletdriver</li>
<li>pinta</li>
<li>pre-commit</li>
<li>ryujinx</li>
</ul>
</details>

**Comment by gador** [comment]
I am still getting the following error:
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/368w2xwqib74kpn650sm562ad3ifc094-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
Executing dotnetConfigureHook
  Determining projects to restore...
/nix/store/bbr88j9h3dmfg9147r3fha1zjdqj2v48-dotnet-sdk-6.0.202/sdk/6.0.202/NuGet.targets(564,5): error : The process cannot access the file '/build/tmp.QExyqLusF0/.nuget/NuGet/nugetorgadd.trk' because it is being used by another process. [/build/source/osu.Game.Rulesets.Catch/osu.Game.Rulesets.Catch.csproj]
```

**Comment by mdarocha** [comment]
> I am still getting the following error for osu-lazer:
> ```
> @nix { "action": "setPhase", "phase": "unpackPhase" }
> unpacking sources
> unpacking source archive /nix/store/368w2xwqib74kpn650sm562ad3ifc094-source
> source root is source
> @nix { "action": "setPhase", "phase": "patchPhase" }
> patching sources
> @nix { "action": "setPhase", "phase": "configurePhase" }
> configuring
> Executing dotnetConfigureHook
>   Determining projects to restore...
> /nix/store/bbr88j9h3dmfg9147r3fha1zjdqj2v48-dotnet-sdk-6.0.202/sdk/6.0.202/NuGet.targets(564,5): error : The process cannot access the file '/build/tmp.QExyqLusF0/.nuget/NuGet/nugetorgadd.trk' because it is being used by another process. [/build/source/osu.Game.Rulesets.Catch/osu.Game.Rulesets.Catch.csproj]
> ```

Hmm, theres not much I can do about this error. Dotnet on *unixes still has the limitation from Windos that only one process can access each file. This can cause errors like this to crop up randomly. I encountered it while building another package, and retrying the build fixed it for me. You can also check if there aren't any other dotnet processes that may block the file.

**Comment by gador** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 168486` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package blacklisted:
</summary>
<ul>
<li>tests.writers</li>
</ul>
</details>
<details>
<summary>
16 packages built:
</summary>
<ul>
<li>ArchiSteamFarm</li>
<li>btcpayserver</li>
<li>discordchatexporter-cli</li>
<li>dotnet-aspnetcore (dotnetCorePackages.aspnetcore_6_0)</li>
<li>dotnet-runtime (dotnetCorePackages.runtime_6_0)</li>
<li>dotnet-sdk (dotnet-sdk_6 ,dotnetCorePackages.sdk_6_0)</li>
<li>github-runner</li>
<li>inklecate</li>
<li>jackett</li>
<li>nbxplorer</li>
<li>omnisharp-roslyn</li>
<li>opentabletdriver</li>
<li>osu-lazer</li>
<li>pinta</li>
<li>pre-commit</li>
<li>ryujinx</li>
</ul>
</details>

**Review by gador — APPROVED** [review]
yes, seems to be flakey. Anyway, it builds and LGTM!

**Review by IvarWithoutBones — APPROVED** [review]
Looks good to me, thank you :)

Result of `nixpkgs-review pr 168486` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.writers</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>ArchiSteamFarm</li>
    <li>btcpayserver</li>
    <li>discordchatexporter-cli</li>
    <li>dotnet-aspnetcore (dotnetCorePackages.aspnetcore_6_0)</li>
    <li>dotnet-runtime (dotnetCorePackages.runtime_6_0)</li>
    <li>dotnet-sdk (dotnet-sdk_6 ,dotnetCorePackages.sdk_6_0)</li>
    <li>github-runner</li>
    <li>inklecate</li>
    <li>jackett</li>
    <li>nbxplorer</li>
    <li>omnisharp-roslyn</li>
    <li>opentabletdriver</li>
    <li>osu-lazer</li>
    <li>pinta</li>
    <li>pre-commit</li>
    <li>ryujinx</li>
  </ul>
</details>

**Comment by Mindavi** [comment]
This broke Archisteamfarm for aarch64-linux: https://hydra.nixos.org/build/176111899

See also ofborg checks on this PR.

ZHF: https://github.com/NixOS/nixpkgs/issues/172160

**Comment by mdarocha** [comment]
> This broke Archisteamfarm for aarch64-linux: https://hydra.nixos.org/build/176111899
> 
> See also ofborg checks on this PR.
> 
> ZHF: #172160

Fixed in https://github.com/NixOS/nixpkgs/pull/172589

**Pull request merged**
