### PR TITLE
llvm*Packages: fix output selection (lib.get*)

### PR DESCRIPTION
**Pull request by vcunat**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/120058#issuecomment-836459634

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 122554` at 6b3b7940 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>465 packages marked as broken and skipped:</summary>
  <ul>
    <li>agdaPackages.iowa-stdlib</li>
    <li>aldor</li>
    <li>bareos</li>
    <li>belle-sip</li>
    <li>betaflight-configurator</li>
    <li>bless</li>
    <li>cassandra_2_1</li>
    <li>cassandra_2_2</li>
    <li>clang-sierraHack</li>
    <li>clang-sierraHack-stdenv</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>8494 packages skipped due to time constraints:</summary>
  <ul>
    <li>AusweisApp2</li>
    <li>DisnixWebService</li>
    <li>EBTKS</li>
    <li>R</li>
    <li>abcl</li>
    <li>accountsservice</li>
    <li>acsccid</li>
    <li>adapta-gtk-theme</li>
    <li>adoptopenjdk-icedtea-web</li>
    <li>aerc</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>clang (clang_7 ,llvmPackages.clang ,llvmPackages.libstdcxxClang ,llvmPackages_7.clang ,llvmPackages_7.libstdcxxClang)</li>
    <li>haskell.compiler.ghc8102BinaryMinimal</li>
  </ul>
</details>

**Comment by vcunat** [comment]
Hmm, no luck with verifying ruby on OfBorg &ndash; it timed out.  I expect the change also caused rebuild of some of its deeper dependencies.

**Comment by Ericson2314** [comment]
@vcunat well, I defer to you on that as original author of multiple outputs in Nixpkgs :).

**Comment by Ericson2314** [comment]
@vcunat anyways I think more `dev` will be harmless because it will propagate the other inputs.

**Review by Ericson2314 — APPROVED** [review]

**Comment by vcunat** [comment]
... or not 😄   I'm feeling optimistic and Hydra would otherwise be quite idle now.  It's just staging-next, so in the worst case we can change it again.

**Pull request merged**
