### PR TITLE
strace: 5.14 -> 5.15

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change
ChangeLog: https://github.com/strace/strace/releases/tag/v5.15

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
This is a feature update, and 21.11 has been released already.  Are you sure it should be backported?

**Review by alyssais — APPROVED** [review]

**Comment by Ma27** [comment]
@alyssais perhaps I missed something, but do we have a new backporting policy which contradicts `Anything that does not cause user or downstream dependency regressions can be backported`?

Apart from the fact that it doesn't seem breaking, it contains compatibility for Linux 5.15 (which is also on 21.11), so IMHO the `Services which require a client to be up-to-date regardless`-bulletpoint also applies here (in case we see `strace` as "client" to the kernel). Finally, I can't remember `strace` breaking things recently, so it doesn't seem risky to me.

But perhaps I'm missing something, anyway, I'm happy to discuss (and perhaps reconsider) that :)

**Comment by alyssais** [comment]
Sorry, you're right.  I got the rules mixed up.

**Comment by risicle** [comment]
I'm convinced by the linux 5.15 argument :heavy_check_mark: 

I think though we are going to have to introduce some sort of policy that backports _at least_ get `nixpkgs-review`ed on all hydra-built platforms before merge, because I'm sure we introduced stable-branch breakages during 21.05.

**Pull request merged**
