### PR TITLE
kernel: enable pressure stall information on 4.20+

### PR DESCRIPTION
**Pull request by thoughtpolice**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by thoughtpolice** [comment]
@GrahamcOfBorg build linuxPackages_4_20.kernel

**Comment by vcunat** [comment]
Oh, that's a cool feature &ndash; exactly the thing I always wanted to watch and couldn't.  :+1:  [Simple explanation.](https://major.io/2019/01/27/using-the-pressure-stall-information-interface-in-kernel-4.20/)

**Comment by thoughtpolice** [comment]
@vcunat Yep, I'm hoping to get some other tools in for 19.03 too, like `oomd` https://facebookincubator.github.io/oomd/

**Comment by vcunat** [comment]
PSI might be nice for Hydra builder machines: https://status.nixos.org/grafana

**Comment by vcunat** [comment]
BTW, new packages are eligible for picking any time.

**Comment by dtzWill** [comment]
:+1: -- I kinda assumed this was already enabled! Thanks and looking forward to it!

**Pull request closed without merging**
