### PR TITLE
dotnetCorePackages: refactor aliases to microsoft naming scheme

### PR DESCRIPTION
**Pull request by khaneliman**
## Description of changes
Related Issue: https://github.com/NixOS/nixpkgs/issues/260915

Not sure we need any message to user, basically would be seen a stable version bump to anyone referencing the existing name. 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by eclairevoyant** [comment]
This will break dozens of packages... `aliases.nix` is meant for deprecated aliases

**Comment by khaneliman** [comment]
> This will break dozens of packages... `aliases.nix` is meant for deprecated aliases

So it's not an actual alias? I saw numerous references that clang does this with.

**Comment by Artturin** [comment]
Use of aliases from `aliases.nix` isn't allowed in nixpkgs, it's for out of tree uses.

**Comment by khaneliman** [comment]
Result of `nixpkgs-review pr 260946` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>28 packages built:</summary>
  <ul>
    <li>dotnet-aspnetcore</li>
    <li>dotnet-aspnetcore-lts</li>
    <li>dotnet-aspnetcore-preview</li>
    <li>dotnet-runtime</li>
    <li>dotnet-runtime-lts</li>
    <li>dotnet-runtime-preview</li>
    <li>dotnet-sdk</li>
    <li>dotnet-sdk-lts</li>
    <li>dotnet-sdk-preview</li>
    <li>fable</li>
    <li>famistudio</li>
    <li>godot3-mono</li>
    <li>godot3-mono-debug-server</li>
    <li>godot3-mono-export-templates</li>
    <li>godot3-mono-headless</li>
    <li>godot3-mono-headless.dev</li>
    <li>godot3-mono-headless.man</li>
    <li>godot3-mono-server</li>
    <li>godot3-mono.dev</li>
    <li>godot3-mono.man</li>
    <li>lidarr</li>
    <li>nuget-to-nix</li>
    <li>pbm</li>
    <li>pre-commit</li>
    <li>pre-commit.dist</li>
    <li>prowlarr</li>
    <li>radarr</li>
    <li>readarr</li>
  </ul>
</details>

**Comment by khaneliman** [comment]
Result of `nixpkgs-review pr 260946` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>dotnet-aspnetcore</li>
    <li>dotnet-aspnetcore-lts</li>
    <li>dotnet-aspnetcore-preview</li>
    <li>dotnet-runtime</li>
    <li>dotnet-runtime-lts</li>
    <li>dotnet-runtime-preview</li>
    <li>dotnet-sdk</li>
    <li>dotnet-sdk-lts</li>
    <li>dotnet-sdk-preview</li>
    <li>pre-commit</li>
    <li>pre-commit.dist</li>
    <li>prowlarr</li>
    <li>radarr</li>
  </ul>
</details>

**Review by mdarocha — CHANGES_REQUESTED** [review]
Not a fan of this. This is basically a breaking change for no technical reason, only a rename that is not to everybody's preference.

We definitialy don't want to change what the no-postfix packages (`dotnet-sdk`, etc.) point to, it's been pretty established that they point to the latest LTS version. 

You can still add the `-preview` and `-lts` aliases without changing the existing no-postfix ones. If you want an alias for the stable channel, you can use `-sts` (for Standard Term Support)

@NixOS/dotnet

**Comment by khaneliman** [comment]
Lost interest in dealing with this. Thought it seemed like a no brained quick help PR.

**Pull request closed without merging**
