### PR TITLE
commandergenius: 2.3.3 -> 3.5.0

### PR DESCRIPTION
**Pull request by mfrischknecht**
The currently packaged version of `Commander-Genius` stopped building with GCC 13, because GCC stopped transitively pulling in a couple of standard headers in various scenarios. Among these is `cstdint`, which declares a couple of standard integer types like `uint32_t`.

At the same time, the currently packaged version is rather old already, and these build issues have been resolved upstream in newer versions.

This change updates `Commander-Genius` to the most recent upstream release, fixing said build issues in the process as a side effect.

Failing Hydra build: https://hydra.nixos.org/build/246237074
Hydra log: https://hydra.nixos.org/build/246237074/nixlog/1

Relevant log excerpt:
```
[ 27%] Building CXX object src/engine/refkeen/kdreams/CMakeFiles/refkeen_kdreams.dir/id_ca.cpp.o
In file included from /build/source/GsKit/base/utils/FindFile.h:28,
                 from /build/source/src/engine/refkeen/kdreams/id_ca.cpp:21:
/build/source/GsKit/base/utils/Unicode.h:16:9: error: 'uint32_t' does not name a type
   16 | typedef uint32_t UnicodeChar;
      |         ^~~~~~~~
/build/source/GsKit/base/utils/Unicode.h:1:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
  +++ |+#include <cstdint>
    1 | /*
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mfrischknecht** [comment]
@hce FYI: I haven't yet had the opportunity to test whether this version actually runs properly. I started the patch while traveling and currently have only remote access to a headless NixOS system. I should be able to do so in a couple of days.

**Comment by mfrischknecht** [comment]
Also, I'm wondering: Does this update warrant a Release Notes entry? From what I can gather from the [upstream repo page](https://gitlab.com/Dringgstein/Commander-Genius/-/tags), version 3.0.0 was assigned rather arbitrarily, and I can't find any documented breaking changes. Should I still include a new entry simply because the the major version changed, or is that unnecessary?

**Comment by mfrischknecht** [comment]
> @hce FYI: I haven't yet had the opportunity to test whether this version actually runs properly. I started the patch while traveling and currently have only remote access to a headless NixOS system. I should be able to do so in a couple of days.

Update: Tested with Commander Keen 1, builds and runs fine for me.

**Comment by trofi** [comment]
Result of `nixpkgs-review pr 284039` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>commandergenius</li>
  </ul>
</details>

**Review by trofi — APPROVED** [review]

**Pull request merged**
