### PR TITLE
uboot 2023.10, timeout handling, tests

### PR DESCRIPTION
**Pull request by sorki**
## Description of changes

- Bumps uboot to 2023.10
- Adds patch that fixes QEMU extlinux boot
- Separates uboot tests from `boot.nix` into `uboot.nix`
- Fixes timeout handling for extlinux, adds test coverage for it
- Adds `passthru.tests` for uboot package
- Fixes an error message about profiles directory not available when building an image

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

CC maintainers  @bartsch @dezgeg @samueldr @lopsided98

### CODE REVIEW

**Comment by sorki** [comment]
Integrated and merged changes done by @jmbaur in #258701
- Included patch subject change from 6a12107f231b8936dc9c98a741922a3702015029 and fixed it up to the first commit 3682adabec8ca8f465b20cac54e4e50d99708981, added @jmbaur as Co-author
- Switched from `fetchpatch2` used in 6a12107f231b8936dc9c98a741922a3702015029 to `git format-patch` patch generated from the tree and added as file, changed the commit title prefix `ubootRaspberryPi*` -> `uboot` since it affects all builds

Split the `x86 pxeboot initrd` patch size into separate commit to make it clear why it was added.

Re-tested using `nixos/tests/uboot.nix`

---

It looks like the last patch which fixes RPi4 SD/MMC boot breaks USB boot and the ML discussion is still ongoing. See also https://bugzilla.suse.com/show_bug.cgi?id=1216036#c8

**Comment by lopsided98** [comment]
>  Switched from `fetchpatch2` used in [6a12107](https://github.com/NixOS/nixpkgs/commit/6a12107f231b8936dc9c98a741922a3702015029) to `git format-patch` patch generated from the tree and added as file

Why? Also, I think there should be comments linking to the mailing list or patchwork.

**Comment by sorki** [comment]
> > Switched from `fetchpatch2` used in [6a12107](https://github.com/NixOS/nixpkgs/commit/6a12107f231b8936dc9c98a741922a3702015029) to `git format-patch` patch generated from the tree and added as file
> 
> Why? Also, I think there should be comments linking to the mailing list or patchwork.

Hmm, I've automatically added the second patch similar to the first one and then aligned the 3rd with these but I realize now, that we only need to keep downstream one as a file. I find it a bit easier to just work with git but if `fetchpath` is preferred (if only for nixpkgs size reason) I sure can switch both.

**Comment by lopsided98** [comment]
My main reason for using `fetchpatch` would be make it easy to find exactly where the patch came from.

**Comment by sorki** [comment]
> My main reason for using `fetchpatch` would be make it easy to find exactly where the patch came from.

Out of curiosity is there a way to find a corresponding git commit hash from patchwork page? Maybe I'm just missing something but I was looking for it by matching a commit message with git log (also how do I know if it was already commited to the tree or not, I'm new to patchwork with only a bit of mailing list workflows experience). Anyway I'll switch both to fetchpatch and add commit hash into the comment.

**Comment by lopsided98** [comment]
Not that I know of. Normally, I would fetch the patch directly from patchwork.

**Comment by sorki** [comment]
Thanks, updated. The State of the patch is actually visible on the patch details page, I've just missed it. I've proposed https://github.com/getpatchwork/patchwork/issues/569 for linking the patch to git commit ID.

**Pull request closed without merging**
