### PR TITLE
easyroam-connect-desktop: init at 1.3.5

### LINKED ISSUE #228158: Package request: EASYROAM
**Project description**
There is a GUI for the new easyroam connection.easyroam is a European university network with which you can get a WIFI connection at all institutions and access paywalled research papers.
Sadly, it is only available as a .deb file and I haven't been able to package it myself, due to lacking experience.
I would be very gateful, if someone would be willing to package this!

**Metadata**

* homepage URL: https://get.eduroam.de
* source URL: https://www.easyroam.de/debapp/easyroam_connect_desktop-1.3.0+1.3.0-linux.deb
* platforms: linux

### PR DESCRIPTION
**Pull request by manyinsects**
Creates a package for the [easyroam](https://easyroam.de) desktop application, which helps users to connect to German academic WiFi networks. Closes #228158.

This is my first time packaging for NixOS, so any feedback is appreciated!

## Things done

- Built on platform(s)
  - [x] x86_64-linux (the application is only released for x86_64, and I don't have a Darwin host to test those versions)
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by shadows-withal** [comment]
Updated the package to properly provide the `easyroam_connect_desktop` bin file, and to use `wrapGAppsHook`. Also, the version I initially packaged was already out-of-date, so I updated it to the latest upstream one.

**Comment by MarchCraft** [comment]
Hey are you looking for another maintainer? i could help

**Comment by shadows-withal** [comment]
@MarchCraft done!

**Comment by MarchCraft** [comment]
Result of `nixpkgs-review pr 348785` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Review by FliegendeWurst — APPROVED** [review]

**Pull request merged**
