### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
tracker blocks https://hydra.nixos.org/build/132356591
cc @NixOS/gnome

**Comment by jtojnar** [comment]
Possibly just a flaky builder?

**Comment by TredwellGit** [comment]
>Possibly just a flaky builder?

Nope, I can't build it either.

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/blob/ee1a7ec4be04626e2f8a5a192c3f70249756bb2d/pkgs/development/libraries/tracker/default.nix#L85
Set `doCheck = false;`  and it builds.

**Comment by jtojnar** [comment]
Looks like it is incompatibility with sqlite 3.34.0: https://bugs.archlinux.org/task/68903

**Comment by jonringer** [comment]
the error message is a bit odd:
```
Bail out! Tracker-FATAL-CRITICAL: SQLite error: database disk image is malformed (errno: Success)
```
It failed.... successfully?

**Comment by FRidh** [comment]
> Looks like it is incompatibility with sqlite 3.34.0: https://bugs.archlinux.org/task/68903

- sqlite forum post https://www.sqlite.org/forum/forumpost/4f5ce1fa7f
- tracker issue https://gitlab.gnome.org/GNOME/tracker/-/issues/275
- arch issue https://bugs.archlinux.org/task/68903

**Comment by jtojnar** [comment]
Added a patch for the tracker issue.

**Comment by FRidh** [comment]
tracker now seems to have an error during installation phase https://hydra.nixos.org/build/132506698. Wrong target directory?
```
Traceback (most recent call last):
  File "/nix/store/n9vj7i7armczjs1x7qzyqhfhzfidrv62-meson-0.56.0/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 140, in run
    return options.run_func(options)
  File "/nix/store/n9vj7i7armczjs1x7qzyqhfhzfidrv62-meson-0.56.0/lib/python3.8/site-packages/mesonbuild/minstall.py", line 554, in run
    installer.do_install(datafilename)
  File "/nix/store/n9vj7i7armczjs1x7qzyqhfhzfidrv62-meson-0.56.0/lib/python3.8/site-packages/mesonbuild/minstall.py", line 375, in do_install
    self.install_data(d)
  File "/nix/store/n9vj7i7armczjs1x7qzyqhfhzfidrv62-meson-0.56.0/lib/python3.8/site-packages/mesonbuild/minstall.py", line 406, in install_data
    if self.do_copyfile(fullfilename, outfilename, makedirs=(d.dirmaker, outdir)):
  File "/nix/store/n9vj7i7armczjs1x7qzyqhfhzfidrv62-meson-0.56.0/lib/python3.8/site-packages/mesonbuild/minstall.py", line 266, in do_copyfile
    dirmaker.makedirs(outdir, exist_ok=True)
  File "/nix/store/n9vj7i7armczjs1x7qzyqhfhzfidrv62-meson-0.56.0/lib/python3.8/site-packages/mesonbuild/minstall.py", line 63, in makedirs
    os.makedirs(path, exist_ok=exist_ok)
  File "/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr'
FAILED: meson-install 
/nix/store/n9vj7i7armczjs1x7qzyqhfhzfidrv62-meson-0.56.0/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

**Comment by TredwellGit** [comment]
It builds for me on staging.

**Comment by jtojnar** [comment]
Did we merge the systemd pkg-config fix yet?

**Pull request merged**
