### PR TITLE
vimPlugins.scretch-nvim: init at 2024-10-20

### PR DESCRIPTION
**Pull request by abhisheksingh0x558**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by abhisheksingh0x558** [comment]
@GaetanLepage please review

**Comment by abhisheksingh0x558** [comment]
I have a question. All these PRs are being merged to `master` while `nix registry list` on my system shows that packages are pull from `nixpkgs-unstable` and [search.nixos.org/packages with unstable option selected](https://search.nixos.org/packages) refers to `nixos-unstable` branch. At what frequency are these 2 branches synced with `master`

**Comment by GaetanLepage** [comment]
> At what frequency are these 2 branches synced with `master`?

In general between 1 and 4 days.
You can track the syncing here: https://grafana.nixos.org/d/LhIq8iLWk/channel-updates?orgId=1&refresh=10s

**Comment by abhisheksingh0x558** [comment]
> > At what frequency are these 2 branches synced with `master`?
> 
> In general between 1 and 4 days. You can track the syncing here: https://grafana.nixos.org/d/LhIq8iLWk/channel-updates?orgId=1&refresh=10s

Thanks

**Comment by GaetanLepage** [comment]
It looks like this plugin depends on `telescope-nvim`.
Could you try to add a test in `overrides.nix` (`nvimRequireCheck = "scretch";`) and see if it works without telescope.
Otherwise, add `dependencies = with self; [ telescope-nvim ];`.

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 349977`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>vimPlugins.scretch-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>vimPlugins.scretch-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>vimPlugins.scretch-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>vimPlugins.scretch-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Comment by abhisheksingh0x558** [comment]
@GaetanLepage seems it got built successfully, i assume `dependencies = with self; [ telescope-nvim ]` or anything else is not required here.

**Comment by GaetanLepage** [comment]
> @GaetanLepage seems it got built successfully, I assume `dependencies = with self; [ telescope-nvim ]` or anything else is not required here.

Yes, it looks like it is not a required dependency. Let's leave it like this.

**Review by GaetanLepage — APPROVED** [review]
LGTM, let's wait for ofborg.

**Pull request merged**
