### PR TITLE
Additional redwax modules 

### PR DESCRIPTION
**Pull request by dirkx**
Submission of redwax modules to NixOS packages; including comments from review on #75620.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [X] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by aanderse** [comment]
Do you have a working `configuration.nix` snippet you used to test this code with that you could share?

**Comment by dirkx** [comment]
Aanderse - still working on extracting that -- my test is currently tied in with some proprietary HSM code - which I am swapping for OpenSC/pcsclite.

**Comment by dirkx** [comment]
Ok - got a bunch of example files liberated and working in our end to end test.

E.g. for the time stamping: https://pastebin.com/GsSHj3DB

What is the proper way to add an example to a pull request ? Or make it part of the overal body of examples ?

**Comment by aanderse** [comment]
@dirkx looking good :+1: 

I'm playing with your test example and will get back to you in the next couple days... but I think this is good to merge. Thanks for the work on this!

**Comment by aanderse** [comment]
@dirkx I threw together a nixos test. Generally we don't make nixos tests for packages, just modules, unless there is a pressing need. *Personally* I think we should have tests for packages which do cool things like this one... :sunglasses: but I'll leave that decision up to someone else. Take a look and see if my test makes sense based on your pastebin: https://github.com/NixOS/nixpkgs/compare/master...aanderse:redwax

**NOTE:** There have been some [changes](https://github.com/NixOS/nixpkgs/pull/73113) to the `httpd` module since you created your PR so the configuration I have is a little bit off what you had.

**Comment by dirkx** [comment]
That makes perfect sense; I've since simplified the test a fair bit (the `fatal' error is that it reuses the cert for the server -- which tools like MS-Word do not like) - but I guess better to wait for this PR to finish before embarking on sanitising the tests for all modules.

**Comment by dirkx** [comment]
Slightly simplified and more realistic test at https://gist.github.com/dirkx/e4dc43ebcea0b3f372f5d6a3dce302e5.

Is it ok to use things like <(echo foo) in these scripts - or strictly bourne-shell neutral ?

**Comment by aanderse** [comment]
@GrahamcOfBorg build mod_ca mod_crl mod_csr mod_ocsp mod_scep mod_pkcs12 mod_spkac mod_timestamp

**Comment by dirkx** [comment]
@aanderse is there a way to kick off the tests `raw' without firing up the kvm/qemu isolation (as this is 90+ second affair from the docker containers that I use) ?

**Comment by dirkx** [comment]
Did not mean to close this. Slip of the mouse/finger.

**Comment by aanderse** [comment]
@dirkx thanks again for contributing this! I'm excited to see someone using apache `httpd` like this on NixOS.

> @aanderse is there a way to kick off the tests `raw' without firing up the kvm/qemu isolation (as this is 90+ second affair from the docker containers that I use) ?

I think NixOS tests are tied to qemu, but I don't know all the details because I've never looked at the implementation. If you post questions like this on https://discourse.nixos.org/ you will get great answers... better than I can give you :smile:

**Comment by dirkx** [comment]
Ack - will do & will do a PR for the test/example use cases for the other modules too.

**Pull request merged**
