### PR TITLE
 linuxKernel.packages.linux_4_4: drop 

### LINKED ISSUE #156735: Linux 4.4 EOL
Kernel 4.4 goes EOL in 2022/02 and needs to be removed from nixpkgs.

See https://kernel.org/category/releases.html
https://twitter.com/kernellogger/status/1483895032797188099

@alyssais @TredwellGit @Ma27 @NeQuissimus

### PR DESCRIPTION
**Pull request by ajs124**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/158634#issuecomment-1033171631

upstream is EOL

Maybe this should get a release notes entry? @NixOS/nixos-release-managers 

Also unsure if these aliases are correct. Maybe we should just keep those as is and throw in some other place?

Closes #156735

###### Things done
- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
We should probably have an entry for `linuxKernel.kernels.linux_4_4` as well. There's a possibility that people adopted the more structured path.

**Comment by jonringer** [comment]
looks like there's still a reference lingering:
```
attribute 'linux_4_4' missing, at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/ofborg-evaluator-6/pkgs/top-level/linux-kernels.nix:472:47
```

**Comment by ajs124** [comment]
> We should probably have an entry for `linuxKernel.kernels.linux_4_4` as well. There's a possibility that people adopted the more structured path.

I agree, but I'm unsure how. Maybe in `pkgs/top-level/linux-kernels.nix`?
I think when we remove non-LTS kernels we don't add `throw`s, so I can't copy&paste that and we haven't removed an LTS since all of this restructuring happened.

**Comment by jonringer** [comment]
we could probably just do aliases in `aliases.nix`. But then that would be a throw in `pkgs/top-level/linux-kernels.nix`

**Comment by jonringer** [comment]
> I think when we remove non-LTS kernels we don't add `throw`s, so I can't copy&paste that and we haven't removed an LTS since all of this restructuring happened.

I don't think the distinction is necessary. EOL kernels are EOL.

**Comment by ajs124** [comment]
> I don't think the distinction is necessary. EOL kernels are EOL.

Sure, but that hasn't been a thing that people have been doing. Should I add the throw to `pkgs/top-level/linux-kernels.nix`, then?

**Comment by Ma27** [comment]
> Sure, but that hasn't been a thing that people have been doing. Should I add the throw to pkgs/top-level/linux-kernels.nix, then?

Seems reasonable to me.

@jonringer btw, IIRC we backported removals of EOLed kernels to stable. I assume that's OK here as well?

**Comment by jonringer** [comment]
> > Sure, but that hasn't been a thing that people have been doing. Should I add the throw to pkgs/top-level/linux-kernels.nix, then?
> 
> Seems reasonable to me.
> 
> @jonringer btw, IIRC we backported removals of EOLed kernels to stable. I assume that's OK here as well?

That's fine with me. cc @NixOS/nixos-release-managers

**Review by tomberek — APPROVED** [review]
Looks good. Add to release notes?

**Comment by vcunat** [comment]
I don't think this needs to be in release notes.  Many reasons:
 - Rare usage of such old kernels with NixOS, I expect.
 - The deadline has been known for years.
 - People can't miss it (eval error).
 
_Well, certainly you can add it anytime, if you think so._

**Comment by vcunat** [comment]
For reference, 4.4 apparently still will be somewhat maintained within a project in The Linux Foundation: https://wiki.linuxfoundation.org/civilinfrastructureplatform/start
... but I don't expect people here are really missing it.

**Pull request merged**
