### PR TITLE
jackaudio: compile without profiling

### PR DESCRIPTION
**Pull request by magnetophon**

### CODE REVIEW

**Comment by wkennington** [comment]
Lgtm

**Comment by magnetophon** [comment]
Sorry, forgot to mention:
With this flag, jackd creates profiling files in lot's of random dirs.
Also @rgareus recommends to build without.

So please also merge this with 15.09.

PS: the failed travis looks like a fluke, no?

**Comment by cillianderoiste** [comment]
I've tested locally, apart from some unrelated errors, everything builds.

**Comment by magnetophon** [comment]
@cillianderoiste
Thanks again.
Could you also merge this into 15.09?

**Pull request merged**
