### PR TITLE
babashka: 0.4.5 -> 0.5.1

### PR DESCRIPTION
**Pull request by ericdallo**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by thiagokokada — APPROVED** [review]
Code-wise LGTM.

However it is important to remember that `nixpkgs` is still packaging GraalVM [21.0.0](https://github.com/NixOS/nixpkgs/blob/3e712c9a24e7ba3e88539d530a809077741b6ead/pkgs/development/compilers/graalvm/community-edition.nix#L40) while [Babashka itself expects GraalVM 21.1](https://github.com/babashka/babashka/commit/35103f40ef113c5528dd74e3a547a6020ecf449f).

There is even a known bug with [Babashka compiled with GraalVM 21.0](https://github.com/babashka/babashka/issues/884).

**Comment by ericdallo** [comment]
@thiagokokada thanks, I intend to bump graalvm soon on nixpkgs as well

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 132604` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>babashka</li>
    <li>clojure-lsp</li>
    <li>vscode-extensions.betterthantomorrow.calva</li>
  </ul>
</details>

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 132604` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>babashka</li>
    <li>clojure-lsp</li>
    <li>vscode-extensions.betterthantomorrow.calva</li>
  </ul>
</details>

**Pull request merged**
