### PR TITLE
Fix inkscape extensions

### PR DESCRIPTION
**Pull request by arkivm**
## Description of changes

* Fix inkscape manage extensions #197044
* Update hexmap extension

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by raboof** [comment]
Result of `nixpkgs-review pr 258885` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>hackneyed</li>
    <li>spring</li>
    <li>springLobby</li>
  </ul>
</details>
<details>
  <summary>42 packages built:</summary>
  <ul>
    <li>adapta-gtk-theme</li>
    <li>arc-theme</li>
    <li>arx-libertatis</li>
    <li>asciidoc-full</li>
    <li>asciidoc-full-with-plugins</li>
    <li>asciidoc-full-with-plugins.dist</li>
    <li>asciidoc-full.dist</li>
    <li>ayu-theme-gtk</li>
    <li>capitaine-cursors</li>
    <li>cinnamon.cinnamon-screensaver</li>
    <li>cinnamon.iso-flags-png-320x420</li>
    <li>cinnamon.iso-flags-svg</li>
    <li>clevis</li>
    <li>clevis.man</li>
    <li>coreboot-configurator</li>
    <li>dblatexFull</li>
    <li>disorderfs</li>
    <li>emojione</li>
    <li>fim</li>
    <li>hikounomizu</li>
    <li>inkscape</li>
    <li>inkscape-extensions.hexmap</li>
    <li>inkscape-with-extensions</li>
    <li>iso-flags</li>
    <li>k40-whisperer</li>
    <li>kabeljau</li>
    <li>rep (kakounePlugins.rep)</li>
    <li>luksmeta</li>
    <li>mate.mate-utils</li>
    <li>mojave-gtk-theme</li>
    <li>numix-cursor-theme</li>
    <li>numix-solarized-gtk-theme</li>
    <li>plata-theme</li>
    <li>pop-gtk-theme</li>
    <li>python310Packages.diagrams</li>
    <li>python310Packages.diagrams.dist</li>
    <li>python311Packages.diagrams</li>
    <li>python311Packages.diagrams.dist</li>
    <li>tang</li>
    <li>tang.man</li>
    <li>volantes-cursors</li>
    <li>wpa_supplicant_gui</li>
  </ul>
</details>

**Review by raboof — APPROVED** [review]
Can confirm this makes the opening the "extensions -> manage extensions" dialog work again, and is indeed functional (tested by adding and using the 'fill hatch' plugin).

I still prefer the declarative approach I think, but neat anyway :)

**Comment by jtojnar** [comment]
Could you please check if filelock is still needed in 1.3? IIRC I did not see any references in the source code: https://github.com/NixOS/nixpkgs/pull/245431#discussion_r1313824049

**Comment by arkivm** [comment]
Filelock is listed as a dep for the Inkscape [extension manager](https://gitlab.com/inkscape/extras/extension-manager/-/blob/master/pyproject.toml#L15) and introduced [here](https://gitlab.com/inkscape/extras/extension-manager/-/commit/9a4acde6c1c028725187ff5972e29e0dbfa99b06).

**Comment by jtojnar** [comment]
Turns out it is an optional runtime dependency for `cachecontrol`.

**Pull request merged**
