### PR TITLE
replace SRI hashes (20.03)

### PR DESCRIPTION
**Pull request by LnL7**
###### Motivation for this change

These break compatibility with nix 2.0, see #89275. Unless we also want to backport #89476 to the 20.03 release.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by vcunat — APPROVED** [review]
For 20.03 (and older) I really prefer this instead of the requirement bump.

**Review by bhipple — APPROVED** [review]

**Comment by worldofpeace** [comment]
@LnL7 Rebase? This LGTM.

**Comment by bhipple** [comment]
Has merge conflict and 20.03 is no longer maintained, so I'll close. Feel free to re-open if you still want to do this of course.

**Comment by worldofpeace** [comment]
20.03 is still maintained https://github.com/NixOS/nixpkgs/issues/101975 and accepting fixes. I hope people don't close PRs thinking this, though, for this particular one it was good to close regardless.

**Pull request closed without merging**
