### PR TITLE
Fix NetworkManager connection sharing

### PR DESCRIPTION
**Pull request by khumba**
NetworkManager's connection sharing doesn't work for me on the current nixos-14.12 channel (8f11a84), partly because of bug #7593.  Here are the fixes I made to get it working again.  This allows NM to create networks in ad-hoc and access point modes.  I applied these patches on top of 8f11a84, successfully created ad-hoc and AP networks, and connected a Wii U to the AP network.  I haven't tested these patches against master because of the large build required (it's not convenient for me to do that right now).

### CODE REVIEW

**Comment by khumba** [comment]
CC @urkud as maintainer of NM and wpa_supplicant.

**Comment by lethalman** [comment]
What has wpa_supplicant to do with CONFIG_AP? Is it wpa_supplicant actually sharing the connection?

**Comment by lethalman** [comment]
Looks good to me.

**Comment by khumba** [comment]
CC @Phreedom, @wkennington as maintainers of NM and wpa_supplicant respectively.

**Pull request merged**
