### PR TITLE
[nixpkgs-19.09]: neomutt: 20180716 -> 2019-10-25

### PR DESCRIPTION
**Pull request by matthiasbeyer**
I propose to backport this patch to stable, reason see below.

This does not build yet on my machine because two unit-tests fail. I am about to investigate.

---

Backported to stable to fix:

    https://github.com/neomutt/neomutt/issues/1373

which includes the following patch:

    https://github.com/Austin-Ray/neomutt/commit/46eb0a5f275041fc92c2772afd0fd812bae891bd

but the patch itself does not apply cleanly to 20180716, thus we need to
update neomutt.

https://github.com/neomutt/neomutt/releases/tag/2019-10-25
(cherry picked from commit b83908f1ed2ba67edbccb9eba4ba761794a441a3)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@GrahamcOfBorg build neomutt

**Comment by matthiasbeyer** [comment]
I guess this is highly controversial. Thus I wouldn't be offended at all if this gets rejected.

In this case I just take neomutt from unstable. :smile:

**Review by Ma27 — APPROVED** [review]
LGTM. I didn't backport back then since I was too afraid of breaking too much stuff for other neomutt-users, but if this fixes problematic issues, I'm fine with backporting (I'm usually using `neomutt` from `nixpkgs-unstable`).

**Comment by matthiasbeyer** [comment]
Well, I don't know if this breaks other things. As there are no stable releases of neomutt, is think so... Thankfully it is not up to me to decide this.

**Comment by flokli** [comment]
I'm afraid of unexpectedly breaking users of the stable release channel by just bumping the version.

Ran myself into an issue where I didn't see the virtual folders anymore until I had migrated to the `named-mailboxes` syntax.

I didn't bisect if this specific issue is caused somewhere between these releases, but it's a problem as neomutt has no stable releases in general. Users can expect some breakage here when upgrading NixOS, but I don't really want to break during a stable cycle.

I'd be fine with a backport of the specific commit, but given it's nontrivial, and 20.03 is around the corner, I'd propose just using neomutt from unstable/20.03 in the meantime.

**Pull request closed without merging**
