### PR TITLE
python-cffi: fix clang build

### PR DESCRIPTION
**Pull request by LnL7**
###### Motivation for this change

A lot of packages depend on this and broke.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build python3Packages.cffi python2Packages.cffi

**Review by Mic92 — APPROVED** [review]

**Comment by Mic92** [comment]
I guess we should queue this for staging instead?

**Comment by LnL7** [comment]
Dunno, master is already broken anyway.

**Comment by LnL7** [comment]
```
Estimating rebuild amount by counting changed Hydra jobs.
   6494 x86_64-darwin
   6896 x86_64-linux
```

I'll merge master into staging so we don't have unnecessary rebuilds.

**Pull request merged**
