### PR TITLE
heroku: 3.43.16 -> 7.5.7

### PR DESCRIPTION
**Pull request by domenkozar**
```
$ nix-build -A heroku -I ~/dev
these derivations will be built:
  /nix/store/q29iva8k02b1gzkm63p7g131rjj4nrad-heroku-7.5.7-modules-7.5.7.drv
  /nix/store/nyjs1jjlq5a56jrk6q0adwsai9cl1ggq-heroku-7.5.7.drv
building '/nix/store/q29iva8k02b1gzkm63p7g131rjj4nrad-heroku-7.5.7-modules-7.5.7.drv'...
configuring
building
yarn config v1.8.0
success Set "yarn-offline-mirror" to "/nix/store/j0xn98mmavzazn7q0md8jc9jmfkkrmlp-offline".
Done in 0.03s.
yarn install v1.8.0
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "EACCES: permission denied, unlink '/nix/store/j0xn98mmavzazn7q0md8jc9jmfkkrmlp-offline/semver-5.5.0.tgz'".
info If you think this is a bug, please open a bug report with the information provided in "/build/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
builder for '/nix/store/q29iva8k02b1gzkm63p7g131rjj4nrad-heroku-7.5.7-modules-7.5.7.drv' failed with exit code 1
cannot build derivation '/nix/store/nyjs1jjlq5a56jrk6q0adwsai9cl1ggq-heroku-7.5.7.drv': 1 dependencies couldn't be built
error: build of '/nix/store/nyjs1jjlq5a56jrk6q0adwsai9cl1ggq-heroku-7.5.7.drv' failed
```
For some reason, yarn is unlinking the symlink which fails since it has no permission to do so.

Best workaround to use heroku seems to be https://github.com/NixOS/nixpkgs/pull/25983#issuecomment-387913836

### CODE REVIEW

**Comment by srhb** [comment]
@GrahamcOfBorg eval

**Comment by domenkozar** [comment]
@zimbatm this is why I've set `hydraPlatforms = [];` to avoid hydra builds.

**Comment by zimbatm** [comment]
If the package is not built by hydra then how about maintaining the definition outside of nixpkgs? It's not yet popular but https://github.com/nix-community/nur might be a good solution for that.

**Comment by domenkozar** [comment]
That looses the convenience of nixpkgs such as `nix-shell -p heroku`, etc. It makes installing of heroku harder, so I'd like to understand the gain of splitting nix packages into another repo.

I understand that hydra not building is inconvenient already, but why make it even more so? :)

**Comment by matthewbauer** [comment]
Why not use node2nix? It should just take adding heroku to the node-packages.json file & regenerating it.

**Comment by domenkozar** [comment]
Not sure who mentioned it to me (@zimbatm?) but it also doesn't work with node2nix.

**Comment by the-kenny** [comment]
I would like to merge this as it works fine and brings `heroku-cli` back. We can always improve the implementation later. 

Anyone against merging?

**Comment by the-kenny** [comment]
Correction: It doesn't work for me :-)

```
% nix-shell -p heroku                                                                                              :(
these derivations will be built:
  /nix/store/hxg3sh70n762s3jxvp2r2956dfhnxdn7-heroku-7.5.7-modules-7.5.7.drv
  /nix/store/vbmka5djxps0wb5mzkw3w63gs253rca5-heroku-7.5.7.drv
building '/nix/store/hxg3sh70n762s3jxvp2r2956dfhnxdn7-heroku-7.5.7-modules-7.5.7.drv'...
configuring
building
yarn config v1.9.4
success Set "yarn-offline-mirror" to "/nix/store/rvvzns36hs08bkhg2b46p67w2bzqdm4j-offline".
Done in 0.03s.
yarn install v1.9.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "EACCES: permission denied, unlink '/nix/store/rvvzns36hs08bkhg2b46p67w2bzqdm4j-offline/semver-5.5.0.tgz'".
info If you think this is a bug, please open a bug report with the information provided in "/build/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
builder for '/nix/store/hxg3sh70n762s3jxvp2r2956dfhnxdn7-heroku-7.5.7-modules-7.5.7.drv' failed with exit code 1
cannot build derivation '/nix/store/vbmka5djxps0wb5mzkw3w63gs253rca5-heroku-7.5.7.drv': 1 dependencies couldn't be built
error: build of '/nix/store/vbmka5djxps0wb5mzkw3w63gs253rca5-heroku-7.5.7.drv' failed
```

**Comment by jdxcode** [comment]
stumbled across this (I'm the maintainer of the Heroku CLI). I don't know much about nixos, but you guys might be able to do something like we do for our [homebrew formula](https://github.com/heroku/homebrew-brew/blob/master/Formula/heroku.rb#L4).

That tarball is all the node files needed to run heroku. If you either put a `node` bin on the `PATH` or map the shebang to node >=8 like we do in the formula that would be much easier I think. No need to mess with yarn.

**Comment by garbas** [comment]
@jdxcode whlie we have you here. first thank you for the pointers how to package heroku-cli. Is there also the option to disable self-update?

**Comment by jdxcode** [comment]
yes with `HEROKU_DISABLE_AUTOUPDATE=1`

**Comment by bobvanderlinden** [comment]
@jdxcode I've implemented your suggestion as an alternative to this PR here: https://github.com/NixOS/nixpkgs/pull/46804

**Comment by domenkozar** [comment]
Thank you!

**Pull request closed without merging**
