### PR TITLE
cc-wrapper: deunify clang/gcc handling of `-B` flag

### LINKED ISSUE #225779: #209870 broke `llvmPackages_13.compiler-rt-libc`
Another regression: `llvmPackages_13.compiler-rt-libc`. https://github.com/NixOS/nixpkgs/pull/225220 does not fix it.

_Originally posted by @alyssais in https://github.com/NixOS/nixpkgs/issues/209870#issuecomment-1501625884_

### LINKED ISSUE #225780: #209870 broke `llvmPackages_rocm.clang`
> Also same-looking issue in `llvmPackages_rocm` but not in other llvmPackages versions that we build.  (I just confirmed that the PR doesn't fix it and reverting glibc upgrade doesn't fix it.  It sounds possible that this PR triggered them.)  Build links:

> https://hydra.nixos.org/build/214886749
> https://hydra.nixos.org/build/215014044

_Originally posted by @vcunat in https://github.com/NixOS/nixpkgs/issues/209870#issuecomment-1501714553_

### PR DESCRIPTION
**Pull request by ghost**
Closes #225779
Closes #225780 

`NIX_CFLAGS_COMPILE+="v"`-then-`nuke-refs`-then-`diff` gives:

screenshot-20230411-233347

screenshot-20230412-001109

https://github.com/gcc-mirror/gcc/blob/5582ad0afb051a76231b2959487f4ef1746df283/gcc/gcc.cc#L549-L551

Which is implemented as:

screenshot-20230412-001116

https://github.com/gcc-mirror/gcc/blob/5582ad0afb051a76231b2959487f4ef1746df283/gcc/gcc.cc#L6423-L6435

Which comes from:

screenshot-20230412-001121

https://github.com/gcc-mirror/gcc/blob/5582ad0afb051a76231b2959487f4ef1746df283/gcc/gcc.cc#L4505-L4506

So the root problem is the first red-text block in the image above.  Once that `-B` is in there, `gcc` will automatically add the offending `-isystem` flags due to the `specs` file.

So it's just that one extra `-B` that's causing all the trouble.

### CODE REVIEW

**Comment by amjoseph-nixpkgs** [comment]
Running a rebuild with this.

It definitely fixes `llvmPackages_13.compiler-rt-libc` when applied selectively using `wrapCCWith` to `compiler-rt-libc`.  This PR applies it globally.

I think the big lesson from this issue and #225220 is that the `cc-wrapper` codepath for non-self-bootstrapping compilers had a fair bit of `clang`-specific stuff in it.  This PR and that PR carve out those bits and mark them as being strictly `isClang`-isms.

**Comment by trofi** [comment]
Yeah, that's unfortunate. I think `nixpkgs` uses `-Blib/gcc/${target}/${version}` only to redirect the lookup of `crt*.o` files. `include/` change was unexpected. The rest is handled by `-I/-isystem/-idirafter` and `-L` flags.

Longer term we might need to avoid aliasing `*.o / include` by storing them in different directories. Or by tweaking `gcc` not to use `-isystem` injection for this case. Or by changing the order of how `cc-wrapper` injects `-I/-isystem/-idirafter` to play nicer with `-B` option (rare external firmware packages likely use it as well).

**Comment by amjoseph-nixpkgs** [comment]
Fixed merge conflict.

**Comment by amjoseph-nixpkgs** [comment]
Confirmed that this fixes #225779 and #225846.

**Comment by amjoseph-nixpkgs** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/225846

**Comment by amjoseph-nixpkgs** [comment]
> I think `nixpkgs` uses `-Blib/gcc/${target}/${version}` only to redirect the lookup of `crt*.o` files.

At some point (well after the 23.05 release) I would like to try putting `crt*.o` either in their own output, or else in the `libgcc` output.

They are effectively compiler intrinsics just like `libgcc`... the main difference is that they are always statically linked (there is no `.so` version of them).

**Comment by amjoseph-nixpkgs** [comment]
Added a revert of d0bb9ed674a258ef8bd6a787d8d1ad0f2164cfdd.

@vcunat would you please check that this PR reverts all the temporary fixes in `staging-next`?

**Comment by vcunat** [comment]
Yes all of them.  I'm not sure if the `rocm-thunk` one is related to this PR.

**Comment by amjoseph-nixpkgs** [comment]
@ofborg eval

**Comment by amjoseph-nixpkgs** [comment]
> Yes all of them. I'm not sure if the `rocm-thunk` one is related to this PR.

It's kinda hard to figure out what that commit does since it doesn't have a PR... it just got lumped in with a 250-commit merge in #224806

**Comment by vcunat** [comment]
@ofBorg eval

**Comment by vcunat** [comment]
I merged master to staging, which should hopefully fix evaluation, but the very same line also caused a conflict here.

**Comment by amjoseph-nixpkgs** [comment]
@vcunat will this make it into the 23.05 release?

This causes a mass rebuild, so if it doesn't make the release it is unlikely to be backported and we'll be stuck with the `wrapCCWith` kludge until 23.11.

**Comment by matthewpi** [comment]
Reverting https://github.com/NixOS/nixpkgs/commit/d0bb9ed674a258ef8bd6a787d8d1ad0f2164cfdd caused `rocm-thunk` to fail with the same error again.  I'm building my NixOS config using this PR at commit `e2340a5b8595d40b93e4463d24992f34974bdc91` and so far I have the following build errors.

<details>

image

Apologies for the image, I cannot copy text from the output without cancelling the remaining rebuilds.
</details>

**Comment by amjoseph-nixpkgs** [comment]
> Reverting [d0bb9ed](https://github.com/NixOS/nixpkgs/commit/d0bb9ed674a258ef8bd6a787d8d1ad0f2164cfdd) caused `rocm-thunk` to fail with the same error again.

@matthewpi thank you for checking this.  And for spending two days of builder time on it.  This was my mistake, I should not have reverted that commit.

> Yes all of them. I'm not sure if the `rocm-thunk` one is related to this PR.

@vcunat, sorry for not looking at this more closely.

I have dropped the revert from this PR.

**Comment by vcunat** [comment]
@matthewpi: `mangohud` was an earlier unrelated regression: https://github.com/NixOS/nixpkgs/pull/224485#issuecomment-1502728378

**Comment by matthewpi** [comment]
> @matthewpi: `mangohud` was an earlier unrelated regression: https://github.com/NixOS/nixpkgs/pull/224485#issuecomment-1502728378

I wasn't sure, but luckily these are the only two failures I've noticed so far.

---

I'll look into building the new changes "tomorrow", hopefully without anymore issues.

**Review by matthewpi — APPROVED** [review]
Fixes the rocm and LLVM-related build failures I've had on staging.

**Comment by orivej** [comment]
Does this also fix building `androidsdk_9_0`? Recently it fails with:
```
auto-patchelf: 2 dependencies could not be satisfied
error: auto-patchelf could not satisfy dependency libgcc_s.so.1 wanted by emulator-check
error: auto-patchelf could not satisfy dependency libgcc_s.so.1 wanted by emulator
```

**Comment by vcunat** [comment]
No, this PR does not address auto-patchelf errors, though they were introduced by the PR with gcc bootstrapping changes.  Packages not built on Hydra get easily missed.  Individual packages are easy to fix (e.g. see ab1cc58b5cf8), but maybe we should have a generic fix for `autoPatchelfHook` instead.

**Comment by amjoseph-nixpkgs** [comment]
> Does this also fix building `androidsdk_9_0`? Recently it fails with:

@orivej can you please open an issue with a bug report for this build failure (including a specific nixpkgs commit and exact `nix-build` or `nix build` command which failed)?

It's probably my fault.  Please assign the issue to me and I will fix it.

> but maybe we should have a generic fix for `autoPatchelfHook` instead.

I think so too:
- https://github.com/NixOS/nixpkgs/issues/225963

If @orivej's problem turns out to be due to this then that will be the second issue report, and I will start working on a general `autoPatchelfHook` fix.  I'd like to have two test cases in order to do that (already have one).

**Pull request merged**
