### PR TITLE
Update NixOS module files to include WindowMaker

### PR DESCRIPTION
**Pull request by AndersonTorres**
Fixes https://github.com/NixOS/nixpkgs/pull/4066#issuecomment-72017611

### CODE REVIEW

**Comment by lethalman** [comment]
You also added other window managers.

**Comment by AndersonTorres** [comment]
Yep! I did it after editing the title of commit :)

**Comment by lethalman** [comment]
@AndersonTorres I wanted to say, just include windowmaker in this PR, thanks :)

**Comment by AndersonTorres** [comment]
Wel, well...
I just run the procedure I learned in [1]. It is very useful to simple testing as I do in mpv and individual packages, but nothing so big as X11+windowmaker. I never tried to do something more advanced in testing Nixpkgs/NixOS from Github.

I even think to do something like a "Nixpkgs Heavy Testing" boot menu on Gummiboot (can I substitute it by Grub?) using my local copy of Nixpkgs, but I am very confused.

So, I can just rely on logic and intuition, and pray to not commit (pun not intended) any mistake.

1- https://nixos.org/wiki/Create_and_debug_nix_packages.

**Comment by lethalman** [comment]
@AndersonTorres I'd prefer only the windowmaker change, yes.

**Comment by lethalman** [comment]
@AndersonTorres when you commit to the PR we don't get notified.

**Comment by lethalman** [comment]
Looks fine to me, don't know whether windowmaker works or not, but if it does for you... :) Merging thanks.

**Comment by AndersonTorres** [comment]
<@AndersonTorres when you commit to the PR we don't get notified.>

So, I need to open a new pull-request? It is a bit "counterproducent". Or there is another way?

**Comment by lethalman** [comment]
Just comment this same PR asking for review :)

**Pull request merged**
