### PR TITLE
staging: revert the binutils bump

### PR DESCRIPTION
**Pull request by flokli**
###### Motivation for this change

The binutils bump from 2.33.1 to 2.34 made it necessary to set `ac_cv_func_lchmod=no` for various binaries so they keep running (inside the nix sandbox at least).

This had to be done with coreutils in e30f1e3c80dad49893b7921c393583f3a149bceb as part of https://github.com/NixOS/nixpkgs/pull/85951, but it seems more userland needs fixes, like [rsync](https://github.com/NixOS/nixpkgs/pull/85951#issuecomment-621199816). I manually verified setting `ac_cv_func_lchmod=no` rsync would fix that specific problem, but we don't know what other applications also need fixing, so let's revert this for now until we figured out why binutils causes this behaviour now.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
Also reverted the now obsolete bump fixup from @Ma27 in #86260.

**Comment by lovesegfault** [comment]
@flokli I would prefer if instead we just added `ac_cv_func_lchmod=no` to stdenv on Linux with glibc, as I think that's the only place it applies and should apply everywhere.

**Comment by flokli** [comment]
If it's possible, this would still be the "big hammer" approach. I'd prefer to understand the problem better, and sticking with old binutils for now.

**Comment by Ericson2314** [comment]
I gotta ask, what is with the upstream maintainership of binutils? I've never been closely involved, but it seems like every version bump for us is nightmare. We can't be the only distro facing this.

**Comment by flokli** [comment]
I'll revert this for now to unbreak staging. If we can fix it, we can always add it back.

**Pull request merged**
