### PR TITLE
wxwidgets 3.1.0 -> 3.1.2

### PR DESCRIPTION
**Pull request by lasandell**
###### Motivation for this change

Need this dependency for another package I'm working on. :smile: 

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
It might make sense to just get rid of the 3.0 package and put everything in the 3.1 directory. We'd need to verify everything still works though.

**Comment by matthewbauer** [comment]
@grahamcofborg build wxGTK30 wxGTK31 pwsafe

**Comment by lasandell** [comment]
Looks like it's going to break things, unfortunately. I had to work around the fact that there was no `--enable-compat26` flag in 3.1.2. Also looks like there is some error with `--enable-universal-binaries` missing on x86_64-darwin.

**Comment by lasandell** [comment]
Resolved by 63423

**Pull request closed without merging**
