### PR TITLE
Python packages set updates

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
@jonringer let's be pragmatic here and just revert updates to leaf packages that cause trouble.

**Comment by jonringer** [comment]
agreed

**Comment by jonringer** [comment]
@fridh one big issue i've seen so far is :
```
#7122: Expressions given to the -m and -k options are no longer evaluated using Python’s eval(). The format supports or, and, not, parenthesis and general identifiers to match against. Python constants, keywords or other operators are no longer evaluated differently.
```

This means code like:
```
  pytest -k 'not x \
    and not y'
```

will fail, because "\" is no longer an accepted character

**Comment by jonringer** [comment]
pytestCheckHook + disabledTests seems to be unaffected because I believe it just constructs the expression in a single line

**Comment by jonringer** [comment]
I concluded that it will be too much of a pain to pin all failing pytest runs to `pytest5`, so instead I kept the default as pytest5, and just added a `pytest_6` package, and hopefully, we will be able to do the jump later

Only package that I've seen so far requiring pytest>=6 is `pytest-xdist>=2`, which I've done a similar bump/pin where `pytest_xdist` points to the last 1.x release, and a `pytest_xdist_2` points to 2.0.0

**Comment by jonringer** [comment]
had to revert isort as well, as most of the packages consuming it are not ready to make the jump

**Comment by jonringer** [comment]
fix build for nixops

**Comment by FRidh** [comment]
Thanks @jonringer ! There are 100 additional failures at this point, I think that is acceptable. People can fix their own packages on master.

**Pull request merged**
