### PR TITLE
bite: init at 0.2.1

### PR DESCRIPTION
**Pull request by vinnymeller**
## Description of changes

Adds [BiTE](https://github.com/WINSDK/bite), a platform-agnostic executable analysis tool.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Aleksanaa** [comment]
```
=> ./result/bin/bite 
thread 'main' panicked at src/main.rs:19:37:
called `Result::unwrap()` on an `Err` value: os error at /build/cargo-vendor-dir/winit-0.29.10/src/platform_impl/linux/wayland/event_loop/mod.rs:81: The wayland library could not be loaded.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```
Doesn't work on my machine

**Comment by Aleksanaa** [comment]
Also the desktop file and background are not installed.

For desktop entry you can use `desktopItems = [ (makeDesktopItem {...}) ]` with `copyDesktopItems`. For icons you can add a background to white or dark icon (See https://stackoverflow.com/questions/2322750/replace-transparency-in-png-image-with-white-background) and place it in `$out/share/pixmaps`.

**Comment by vinnymeller** [comment]
@Aleksanaa  thank you for your help so far. It should work on wayland now. I made wayland vm to test there from now on.

I'm just trying to understand your other requests so I can do it right next time. 

- `pixmaps` only appears in all of nixpkgs ~300 times. how do I know when I need to add files here / when would I not need to?
- from looking at other derivations it seems that some build processes produce `desktop` files. when that happens, in the derivation we move desktop file to `$out/share/applications`. some builds (this pr) doesn't, so we do it. yes?  -- should basically all gui apps have a desktop file?

**Comment by Aleksanaa** [comment]
> pixmaps only appears in all of nixpkgs ~300 times. how do I know when I need to add files here / when would I not need to?

You can also use `$out/share/icons/hicolor/64x64/apps`. See https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

> should basically all gui apps have a desktop file?

Mostly yes.

**Comment by vinnymeller** [comment]
Result of `nixpkgs-review pr 304829` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>bite</li>
  </ul>
</details>

**Comment by Aleksanaa** [comment]
Works for me, but didn't know `autoPatchelfHook` doesn't work on darwin, so we either need something like https://github.com/NixOS/nixpkgs/blob/68165781ccbe4d2ff1d12b6e96ebe4a9f4a93d51/pkgs/development/misc/msp430/mspdebug.nix#L44, or just wrap the binary like you did before

**Comment by vinnymeller** [comment]
@Aleksanaa is there anything else you'd like done differently?

**Pull request merged**
