### PR TITLE
KDE Applications: 20.12.0, KDE Frameworks: 5.77, dependencies, patches

### PR DESCRIPTION
**Pull request by hamburger1984**
###### Motivation for this change

Upgraded kde-applications and kde-frameworks to their most recent releases.

Some dependencies added & fixed for kde-applications, kde-frameworks and plasma5.

> This branch also includes the fix for fetch-kde-qt.sh from https://github.com/NixOS/nixpkgs/pull/104684. (But this could be omitted, if the "new" approach of downloading and hashing the archives is deemed more suitable)
(removed)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ttuegel** [comment]
> This branch also includes the fix for fetch-kde-qt.sh from #104684. (But this could be omitted, fit the "new" approach of downloading and hashing the archives is deemed more suitable)

What are the advantages of extracting the file hashes from HTML instead of hashing the downloaded files? I want to be sure the additional complexity is justified.

**Comment by hamburger1984** [comment]
> 
> 
> > This branch also includes the fix for fetch-kde-qt.sh from #104684. (But this could be omitted, fit the "new" approach of downloading and hashing the archives is deemed more suitable)
> 
> What are the advantages of extracting the file hashes from HTML instead of hashing the downloaded files? I want to be sure the additional complexity is justified.

Basically it's just reduced load on the servers and not having to fetch the files before they're actually needed. So.. maybe it's not necessary.

**Comment by hamburger1984** [comment]
Before this PR becomes a non-Draft, I'll cherry-pick some changes for kinfocenter (it finally works!) from https://github.com/hamburger1984/nixpkgs/commits/kde-plasma-fixes-unstable.

**Comment by peterhoeg** [comment]
Regd kinfocenter: https://github.com/NixOS/nixpkgs/pull/107781

**Comment by hamburger1984** [comment]
> 
> 
> Regd kinfocenter: #107781

Proposed my fixes in that PR.

**Comment by hamburger1984** [comment]
Regarding the fetch-kde-qt.sh script:
I reverted and tried to fetch srcs.nix for kde-frameworks, kde-applications, qt-5 and plasma5
* it's slow to fetch all source packages (some mirrors are probably doing some ratelimiting..)
* the hashes calculated by the previous script don't match the ones provided on the websites (is that just a different encoding of the same hash?)

for example:
image
image

I'll include the revert and re-generated srcs.nix anyhow as my proposed script doesn't seem to gain too much love here ;-)

**Comment by ttuegel** [comment]
> the hashes calculated by the previous script don't match the ones provided on the websites (is that just a different encoding of the same hash?)

Yes, this is just an encoding issue. The upstream websites undoubtedly list the SHA256 hashes in the conventional hexadecimal (base-16) notation, but all the Nix tools use base-32 (compact, but idiosyncratic).

**Comment by hamburger1984** [comment]
> > the hashes calculated by the previous script don't match the ones provided on the websites (is that just a different encoding of the same hash?)
> 
> Yes, this is just an encoding issue. The upstream websites undoubtedly list the SHA256 hashes in the conventional hexadecimal (base-16) notation, but all the Nix tools use base-32 (compact, but idiosyncratic).

Okay. Then my script really would just improve the speed of generating srcs.nix. This does not justify the complexity, as this is not done that often, I guess.

@tteggel any objections towards rebasing this branch on latest staging?
Also: is this form of PR fine or should I split this into more fine grained PRs?

**Comment by CrystalGamma** [comment]
The upstream fetch-kde-qt.sh was broken for me, so I wrote this: https://gist.github.com/CrystalGamma/c6a7252219b44cf2c6ddaf5e4c49b6da .
If you're interested, feel free to integrate it; first command line argument is the mirror to fetch the hashes from, second is the path on each of the mirrors, which is written to the srcs.nix, third is the path to the srcs.nix to write to.

**Pull request closed without merging**
