### PR TITLE
Vaapi update (libva+intel)

### PR DESCRIPTION
**Pull request by eduarrrd**
Version bump.

### CODE REVIEW

**Comment by vcunat** [comment]
- 1.5.0 versions were released ~3 days ago, so we'd better update both directly to that one.  http://cgit.freedesktop.org/libva/tree/NEWS?h=v1.5-branch http://cgit.freedesktop.org/vaapi/intel-driver/tree/NEWS?h=v1.5-branch

- The news don't suggest to me any other necessity than updating version+hash, so if acceleration through VA still works for you, merging to master is safe. If build problems appear, we can deal with them afterwards (the rebuild factor isn't so high, mostly through ffmpeg).

- I myself don't have intel-capable HW (except for a 10-year-old notebook which I don't use anymore).

**Comment by eduarrrd** [comment]
@vcunat Thanks for the heads-up.

Updated. Works for me on my hardware.

**Comment by eduarrrd** [comment]
@vcunat ping

**Comment by vcunat** [comment]
I wonder how I missed that comment.

**Pull request closed without merging**
