### PR TITLE
git: 2.22.0 -> 2.23.0

### PR DESCRIPTION
**Pull request by Izorkin**
###### Motivation for this change
Update git to version 2.23.0
Changelog - https://lkml.org/lkml/2019/8/16/877

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by Izorkin** [comment]
@GrahamcOfBorg build git
@GrahamcOfBorg test gitolite

**Comment by mmahut** [comment]
This should probably go to staging as a mass rebuild, please.

**Comment by wmertens** [comment]
@Izorkin 	I tried changing the base but it picked up changes in 54 other files ;) LGTM, can you rebase on staging?

**Comment by Izorkin** [comment]
Change to staging.

**Comment by Izorkin** [comment]
@GrahamcOfBorg build git
@GrahamcOfBorg test gitolite

**Pull request merged**
