### PR TITLE
Vala updates 2021-12-02

### PR DESCRIPTION
**Pull request by bobby285271**
###### Motivation for this change

Bump vala 0.48 and 0.52, remove EOL version, revisit packages that are not building with latest vala.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg build vala_0_48 vala_0_52 tootle xfce.xfce4-dockbarx-plugin

**Comment by bobby285271** [comment]
### Vala 0.52.8

b059d729f5f3d504a7808752d388a933bdd9b628: vala_0_52: 0.52.7 → 0.52.8
(https://ftp.gnome.org/pub/GNOME/sources/vala/0.52/vala-0.52.8.news)

Various improvements and bug fixes:

  - codegen:
    + Use CCodeConstant for member access of constant symbol
    + Add and use CCodeConstantIdentifier for accessing constants
    + Check required length of enum type name for GType support
    + Add missing check while overriding virtual async interface methods [<a href="https://gitlab.gnome.org/GNOME/vala/issues/852">#852</a>]
    + Drop inconsistent space for ObjectType parameters
    + Accept CCode.type attribute on parameters [<a href="https://gitlab.gnome.org/GNOME/vala/issues/876">#876</a>]
    + Fix CCodeUnaryExpression.write() for PREFIX_INCREMENT/PREFIX_DECREMENT
  - vala:
    + Improve error message for invalid handler of dynamic signal
    + Using SignalHandler.disconnect() is required for dynamic signals
    + Check for unavailable value-type of variable initializer [<a href="https://gitlab.gnome.org/GNOME/vala/issues/1253">#1253</a>]
    + Add [Profile] as known attribute for methods
    + Report error on missing gio-2.0 package for async constructors
    + Fix signals with generic return
    + parser: Split out Parser.parse_switch_section_statement()
    + parser: Better handling of misplaced switch sections [<a href="https://gitlab.gnome.org/GNOME/vala/issues/1246">#1246</a>]
  - genie:
    + Amend text of indent and dedent for error messages [<a href="https://gitlab.gnome.org/GNOME/vala/issues/497">#497</a>]
    + Accept INTERR token before type arguments when parsing type [<a href="https://gitlab.gnome.org/GNOME/vala/issues/1245">#1245</a>]
    + Properly handle plain "get" or "set" property accessors [<a href="https://gitlab.gnome.org/GNOME/vala/issues/1248">#1248</a>]
    + "exception" is the expected string for TokenType.ERRORDOMAIN
    + Accept accessibility/async modifiers on "construct" creation methods [<a href="https://gitlab.gnome.org/GNOME/vala/issues/1235">#1235</a>]
  - girparser: Accept "sealed" for transformed records and compact classes
  - gtkmodule: Improve error message for invalid signal element in ui-file
  - tests: Rename colliding test cases to avoid conflicts
 - Bindings:
   - alsa: Add more API and fix a few things
   - gnome-desktop-3.0: Some parameter fixes
   - gstreamer: Cherry-pick bindings fixes from 0.56
   - gstreamer-base-1.0: Some parameter fixes [<a href="https://gitlab.gnome.org/GNOME/vala/issues/1255">#1255</a>]
   - pango: Cherry-pick bindings fixes from 0.56

---

### Vala 0.48.20

64899e83e19e3987c77d793d35c070dfa3707e08: vala_0_48: 0.48.19 → 0.48.20
(https://ftp.gnome.org/pub/GNOME/sources/vala/0.48/vala-0.48.20.news)

Various improvements and bug fixes:

  - codegen:
    + Add type declaration for implicit temporary local variable
    + Actually free data when using "remove(_all)"
      on GLib.Queue/(S)List [<a href="https://gitlab.gnome.org/GNOME/vala/issues/1238">#1238</a>]
    + Use CCodeConstant for member access of constant symbol
    + Add and use CCodeConstantIdentifier for accessing constants
    + Check required length of enum type name for GType support
    + Add missing check while overriding virtual async interface methods [<a href="https://gitlab.gnome.org/GNOME/vala/issues/852">#852</a>]
    + Drop inconsistent space for ObjectType parameters
    + Accept CCode.type attribute on parameters [<a href="https://gitlab.gnome.org/GNOME/vala/issues/876">#876</a>]
    + Fix CCodeUnaryExpression.write() for PREFIX_INCREMENT/PREFIX_DECREMENT
  - vala:
    + Warn about unsupported cast to void and drop it [<a href="https://gitlab.gnome.org/GNOME/vala/issues/1070">#1070</a>]
    + Don't restrict element type of GLib.Array [<a href="https://gitlab.gnome.org/GNOME/vala/issues/1227">#1227</a>]
    + Accept NullType as generic type argument
    + Set source references of created DataType instances in OCE
    + Parameter following ellipsis parameter is not allowed [<a href="https://gitlab.gnome.org/GNOME/vala/issues/1237">#1237</a>]
    + More thorough check of ValueType and set CodeNode.error on failure
    + Really check compatiblity of error types for delegate symbol
    + Correctly output signature of callable throwing error
    + Report error for non ErrorType in throws
    + Implement CodeWriter.visit_foreach_statement()/visit_catch_clause()
    + Improve error message for invalid handler of dynamic signal
    + Using SignalHandler.disconnect() is required for dynamic signals
    + Check for unavailable value-type of variable initializer [<a href="https://gitlab.gnome.org/GNOME/vala/issues/1253">#1253</a>]
    + Add [Profile] as known attribute for methods
    + Report error on missing gio-2.0 package for async constructors
    + Fix signals with generic return
    + parser: Make sure ErrorCodes are accessible as needed
    + parser: Split out Parser.parse_switch_section_statement()
    + parser: Better handling of misplaced switch sections [<a href="https://gitlab.gnome.org/GNOME/vala/issues/1246">#1246</a>]
  - genie:
    + Amend text of indent and dedent for error messages [<a href="https://gitlab.gnome.org/GNOME/vala/issues/497">#497</a>]
    + Accept INTERR token before type arguments when parsing type [<a href="https://gitlab.gnome.org/GNOME/vala/issues/1245">#1245</a>]
    + Properly handle plain "get" or "set" property accessors [<a href="https://gitlab.gnome.org/GNOME/vala/issues/1248">#1248</a>]
    + "exception" is the expected string for TokenType.ERRORDOMAIN
    + Accept accessibility/async modifiers on "construct" creation methods [<a href="https://gitlab.gnome.org/GNOME/vala/issues/1235">#1235</a>]
  - girparser: Add support for "ref_/ref_sink_/unref_function"
    metadata for classes [<a href="https://gitlab.gnome.org/GNOME/vala/issues/1233">#1233</a>]
  - girparser: Accept "sealed" for transformed records and compact classes
  - gtkmodule: Improve error message for invalid signal element in ui-file
  - valadoc: Correctly format background of inline @link's [<a href="https://gitlab.gnome.org/GNOME/vala/issues/1226">#1226</a>]
  - tests: Rename colliding test cases to avoid conflicts
 - Bindings:
   - alsa: Add more API and fix a few things
   - gio-2.0: Unhide a few usable symbols which are marked not introspectable [<a href="https://gitlab.gnome.org/GNOME/vala/issues/1222">#1222</a>]
   - gio-2.0: Backport fixes from 0.54.2
   - glib-2.0: Current constants in GLib.Math are part of glib.h [<a href="https://gitlab.gnome.org/GNOME/vala/issues/1220">#1220</a>]
   - glib-2.0: Add RefString since 2.58 [<a href="https://gitlab.gnome.org/GNOME/vala/issues/723">#723</a>]
   - gnome-desktop-3.0: Some parameter fixes
   - gstreamer: Cherry-pick bindings fixes from 0.56
   - gstreamer-base-1.0: Some parameter fixes [<a href="https://gitlab.gnome.org/GNOME/vala/issues/1255">#1255</a>]
   - gtk4: Backport fixes from 0.54.2
   - pango: Cherry-pick bindings fixes from 0.56

**Review by davidak — APPROVED** [review]
Changes look good, not tested

**Comment by bobby285271** [comment]
Result of `nixpkgs-review pr 148372` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>xfce.xfce4_dockbarx_plugin</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>tootle</li>
    <li>vala_0_48</li>
    <li>vala_0_52</li>
    <li>xfce.xfce4-dockbarx-plugin</li>
  </ul>
</details>

**Comment by bobby285271** [comment]
@ofborg build vala_0_48 vala_0_52
@ofborg build tootle
@ofborg build xfce.xfce4-dockbarx-plugin

**Comment by bobby285271** [comment]
https://github.com/pdfpc/pdfpc/issues/594 has been fixed, give me some time to patch that.

**Comment by bobby285271** [comment]
Result of `nixpkgs-review pr 148372` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>cinnamon.cinnamon-common</li>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>cinnamon.cinnamon-screensaver</li>
    <li>cinnamon.cjs</li>
    <li>gnome.caribou</li>
    <li>pdfpc</li>
    <li>tootle</li>
    <li>vala_0_48</li>
    <li>vala_0_52</li>
    <li>xfce.xfce4-dockbarx-plugin</li>
    <li>xfce.xfce4-namebar-plugin</li>
  </ul>
</details>

**Comment by bobby285271** [comment]
@ofborg build cinnamon.cinnamon-common cinnamon.cinnamon-gsettings-overrides cinnamon.cinnamon-screensaver cinnamon.cjs gnome.caribou pdfpc tootle vala_0_48 vala_0_52 xfce.xfce4-dockbarx-plugin xfce.xfce4-namebar-plugin

**Comment by bobby285271** [comment]
Current vala version we have:

- 0.40.25 (old LTS)
- 0.48.20 (latest LTS)
- 0.52.8 (old stable)
- 0.54.2 (latest stable)

Package that builds with vala 0.40 and cannot build with 0.48:

- `ping` - upstream has no more activity since Dec 2020, no fix on latest git version
- `xfce.xfce4-namebar-plugin` - upstream has no more activity since May 2020, and no more commit since 1.0.0

Package that builds with vala 0.48 and cannot build with 0.52:

- `gnome.caribou` - [0.4.21](https://gitlab.gnome.org/GNOME/caribou/-/tree/0.4.21) is a 5-year-old release, but no new release, haven't tested the latest git version yet

Package that builds with vala 0.52 and cannot build with 0.54:

- I am not sure about this, I haven't checked hydra for this yet

**Comment by bobby285271** [comment]
Result of `nixpkgs-review pr 148372` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>xfce.xfce4_dockbarx_plugin</li>
    <li>xfce.xfce4_namebar_plugin</li>
  </ul>
</details>
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>cinnamon.cinnamon-common</li>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>cinnamon.cinnamon-screensaver</li>
    <li>cinnamon.cjs</li>
    <li>gnome.caribou</li>
    <li>pdfpc</li>
    <li>tootle</li>
    <li>vala_0_48</li>
    <li>vala_0_52</li>
    <li>xfce.xfce4-dockbarx-plugin</li>
    <li>xfce.xfce4-namebar-plugin</li>
  </ul>
</details>

**Comment by jtojnar** [comment]
Caribou is no longer used by GNOME. @mkg20001 do you know what Cinnamon’s plans for it are? Maybe they could take over the [upstream repo](https://gitlab.gnome.org/GNOME/caribou) if they still intend to use it.

**Comment by mkg20001** [comment]
No. The upstream repo does not mention that the library is deperacted. Though a lack of updates hints at it. Are you sure it will be/is deperacted?

**Comment by bobby285271** [comment]
Ooooops, actually `gnome.caribou` builds with latest vala with [this patch](https://gitlab.gnome.org/GNOME/caribou/-/commit/c52ce71c49dc8d6109a58d16cc8d491d7bd1d781)...

**Review by jtojnar — APPROVED** [review]
Great job. Personally I would just drop Vala 0.40 and mark the stuff that depends on it as broken but :woman_shrugging:

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 148372` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>cinnamon.cinnamon-common</li>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>cinnamon.cinnamon-screensaver</li>
    <li>cinnamon.cjs</li>
    <li>gnome.caribou</li>
    <li>pdfpc</li>
    <li>tootle</li>
    <li>vala_0_48</li>
    <li>vala_0_52</li>
    <li>xfce.xfce4-dockbarx-plugin (xfce.xfce4_dockbarx_plugin)</li>
    <li>xfce.xfce4-namebar-plugin (xfce.xfce4_namebar_plugin)</li>
  </ul>
</details>

**Review by davidak — APPROVED** [review]
Changes look good, packages build

tootle works
pdfpc starts

@bobby285271 thank you!

**Pull request merged**
