### PR TITLE
Revert "nv-codec-headers: recreate under by-name"

### PR DESCRIPTION
**Pull request by flokli**
This reverts commit 01f7c8a1a317171a5a1b84086e955e0c28900523.

It broke NixOS config evaluation, as in
https://github.com/NixOS/nixpkgs/pull/324199#issuecomment-2212422318.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Aleksanaa** [comment]
Did you have a `pkgs.sources` sitting somewhere in your config? While this does seem like it could cause a problem, we haven't encountered it yet (in Nixpkgs)?

**Comment by flokli** [comment]
> Did you have a `pkgs.sources` sitting somewhere in your config? While this does seem like it could cause a problem, we haven't encountered it yet (in Nixpkgs)?

I have a `sources` in my NixOS config, yes (and use Niv to pin dependencies), I define it in an overlay like this:

```
  sources = import ./sources.nix { inherit (super) system; };
```

… and use `sources.` in various places in my NixOS configuration.

**Comment by Aleksanaa** [comment]
Still don't get it, we even don't have any `nv-codec` matches in nixos modules?

**Comment by Aleksanaa** [comment]
Oh

**Comment by flokli** [comment]
Ah, it's because `[pkgs/by-name/nv/nv-codec-headers/package.nix](https://github.com/NixOS/nixpkgs/pull/325242/files#diff-3f4c9ac87583bb57efcdb1464abe956e24bb764da0a514f1146812074815700e)` does get `callPackage`'ed. Yeah, this is bad.

**Comment by Aleksanaa** [comment]
That should be ideal though, I guess that's where the "default version" comes from

**Comment by flokli** [comment]
I don't think this `sources` defaulting to `./sources.nix`should be an overridable argument.
Same for other bits to produce different variants (like `majorVersion`).

AFAIK, the only inputs should be packages defined in the package set, and if things get too fancy, they should live outside by-name, to avoid these sudden surprises.

**Comment by Aleksanaa** [comment]
So every time [I tell people a joke](https://github.com/NixOS/nixpkgs/issues/310373#issuecomment-2210118825), it becomes something serious (Remember dbus-broker, Huh)

**Comment by Aleksanaa** [comment]
> I don't think this `sources` defaulting to `./sources.nix`should be an overridable argument. Same for other bits to produce different variants (like `majorVersion`).
> 
> AFAIK, the only inputs should be packages defined in the package set, and if things get too fancy, they should live outside by-name, to avoid these sudden surprises.

Agree, this is too non-trivial to put in by-name.

**Review by Aleksanaa — APPROVED** [review]
We have no rebuilds.

**Comment by TomaSajt** [comment]
I don' think the main issue is `pkgs/by-name`. It's just `callPackage` being `callPackage`

You would have encountered the same issue in a package that's not in `by-name`, since you're supposed to call packages with `callPackage` anyways. The fact that the package broke was because they also refactored the code.

The main issue was just having `sources` being present in the override-able argument list.
(Which, IMO, should have just be placed into the `let in` block, since you would probably only  ever have to override the `majorVersion` anyways)

**Comment by AndersonTorres** [comment]
> The main issue was just having `sources` being present in the override-able argument list.

This was intentional: the source list is treated as part of calling interface.

**Pull request merged**
