### PR TITLE
[24.05 backport] nodejs changes

### PR DESCRIPTION
**Pull request by aduh95**
## Description of changes

Generated with 

```sh
for commit in $(git log HEAD...origin/staging --reverse --pretty=format:"%H" -- pkgs/development/web/nodejs/); do
             echo "About to cherry-pick $commit";
             git cherry-pick -x "$commit";
             read -p "Press any key to resume ...";
done
```

I only picked the commits that did not break the builds.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by tie** [comment]
Hm, did the commit that switches the build system to `ninja` fail for some reason?
(note that we’d also need #337360 as a followup fix)

**Review by Ma27 — COMMENTED** [review]
> note that we’d also need #337360 as a followup fix

Given the significant changes to the build-system and the fact that there is in fact fall-out already, I'd like to raise the question whether it's actually a good idea to backport all of that.

Would it be an option to just backport the bumps and bugfixes (if any?)

**Comment by aduh95** [comment]
I agree with Maximilian, not backporting that `ninja` change minimizes the risk of breakage. I don't remember exactly if I dropped it because of a build failure, I think I didn't even try to resolve the conflicts and just skipped it. FWIW I'm not against backporting it ever, but I'd rather not be the one doing it.

> Would it be an option to just backport the bumps and bugfixes (if any?)

Unless I'm missing something, that's currently the case. The changes are either version bump, bug fixes, or "ineffective" changes included just to minimize the amount of conflicts (i.e. all test-related changes don't have any impact on the 24.05 branches because we don't run the tests there, see https://github.com/NixOS/nixpkgs/commit/21e378223cbc13bfff4984486265fd8310d063ee).

**Comment by Ma27** [comment]
> FWIW I'm not against backporting it ever, but I'd rather not be the one doing it.

I don't think this needs to be backported at all: yes, further version bumps and all of that will be more painful, but I'd argue it's less of a risk than backporting all the build-system changes. Also, the situation will resolve itself by the end of the year when 24.05 gets retired.

> Unless I'm missing something, that's currently the case

I thought this wasn't the case before since the build-system changes were included? But on a second glance, this isn't the case anymore (I guess the `NINJA` env change was a red herring and I fell for it :see_no_evil: ).

In that case it's fine I'd say.

**Comment by tie** [comment]
>I guess the NINJA env change was a red herring and I fell for it

Yes, I was a bit confused by this as well and was half-expecting other ninja-related changes.

>Would it be an option to just backport the bumps and bugfixes (if any?)

Perhaps we shouldn’t backport https://github.com/NixOS/nixpkgs/pull/336570/commits/4b90b5edfda9d6efa29539d230f163d10e26a992 since it is a non-trivial change to the Node.js build process (i.e. using an emulator instead of building for multiple platforms)? Otherwise the commits in this PR look good to me.

**Comment by aduh95** [comment]
Marking as draft until https://github.com/NixOS/nixpkgs/pull/339252 can be included (because of https://github.com/NixOS/nixpkgs/pull/336556#issuecomment-2325514159), and https://github.com/NixOS/nixpkgs/commit/4b90b5edfda9d6efa29539d230f163d10e26a992 is removed from this PR.

**Comment by aduh95** [comment]
> 7f3e4cc34082635b3b7831db7598b7062961dae3 not found in any pickable branch

I guess I should wait for `staging-next` to be merged into `master`

**Review by Conni2461 — APPROVED** [review]

**Pull request merged**
