### PR TITLE
mesa: 22.1.7 -> 22.2.0

### PR DESCRIPTION
**Pull request by PedroHLC**
###### Description of changes

- Bumped version;
- Rebased patches;
- Remove upstreamed patches.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by PedroHLC** [comment]
Missing a "Merge staging-next into staging" to fix the eval. But meanwhile I'll tag you guys for reviewing.

**Comment by vcunat** [comment]
Usually we just skip `.0`.  I didn't look now, but upstream were saying that `.0` are "testing" releases.

**Comment by PedroHLC** [comment]
> Usually we just skip `.0`. I didn't look now, but upstream were saying that `.0` are "testing" releases.

I didn't find any reference to support such claim, they had a month freeze between -rc3 and this release. Plus, it's coming even to Debian[[1]](https://tracker.debian.org/news/1364218/accepted-mesa-2220-1-source-into-unstable/) and Fedora 37,38,ELN[[2]](https://bodhi.fedoraproject.org/updates/?packages=mesa).

**Comment by vcunat** [comment]
Here in the first paragraph is the phrase they've been repeating for years: https://docs.mesa3d.org/relnotes/22.1.0.html#mesa-22-1-0-release-notes-2022-05-18

**Comment by PedroHLC** [comment]
We'll see each other again some 22.2.1 day.

**Comment by jtojnar** [comment]
Also the release disables some codecs https://gitlab.freedesktop.org/mesa/mesa/-/commit/7d969fe9e91e39e03041cdfac69bf33337bc2c96. Since we are not Fedora, we should probably enable them https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/M4LTGLHY5JX42IHC45WNWB5FH2JIFMAS/.

**Pull request closed without merging**
