### PR TITLE
[19.09] vimPlugins.vimelette: init at 2019-05-02

### PR DESCRIPTION
**Pull request by gotcha**
Added vim plugin vimelette

### CODE REVIEW

**Comment by jonringer** [comment]
I think you meant to do this against master.... not nixpkgs-19.09-darwin

**Comment by gotcha** [comment]
@jonringer I already did it against master and it got merged.

Then I wondered how to get from master to nixpkgs-19.09-darwin (See https://discourse.nixos.org/t/nixpkgs-flow-from-master-to-channel/4727).
I understood (maybe wrongly) that I also need a PR in nixpkgs-19.09-darwin

**Comment by jonringer** [comment]
do you mind doing a 
```
nix-channel --list
sudo nix-channel --list
```
and posting the output?

**Comment by jonringer** [comment]
cc @NixOS/darwin-maintainers @NixOS/channel-updaters what's the policy on the darwin variant channels?

**Comment by LnL7** [comment]
I'm not sure what the nixpkgs-19.09-darwin branch is but it has nothing to do with the channel.

**Comment by LnL7** [comment]
If you want to backport changes to a release please use `git cherry-pick -x` to have a reference to the original commit and target the release-19.09 branch.

**Comment by gotcha** [comment]
Well, it seems I first need to better understand how nixpkgs branches get turned into channels.
@LnL7 @jonringer Any pointers ?

**Comment by LnL7** [comment]
@gotcha To be honest, I'm not sure I can point to anything specific. I definitively agree this should be described somewhere. Apparently these channel branches are a recent change for technical reasons, but the fact that they exist makes this even more important now to avoid confusion.

**Comment by jonringer** [comment]
agreed, and I'm not sure who's driving the darwin channels, but I would like to know their intent with using the darwin variant channels. Only benefit i could see is that it would clear out a lot of non-darwin noise when looking through hydra jobsets, but I think that should be a feature on hydra to sort by targeted architecture

**Comment by timokau** [comment]
Either way, the vim-plugins update should not go to the stable channel. It might break things. I'm fine with backporting new packages (i.e. just the `vimlette` init, not the update), but I'm not sure what the general policy there is.

**Comment by jonringer** [comment]
@gotcha IIRC, you already landed a PR in master, do you  mind running:
```
nix-channel --list
sudo nix-channel --list
```
this PR might not even be necessary

**Comment by gotcha** [comment]
@jonringer  FTR
    
    $ nix-channel --list
    home-manager https://github.com/rycee/home-manager/archive/release-19.09.tar.gz
    nixpkgs https://nixos.org/channels/nixpkgs-19.09-darwin

Nevertheless, I guess that PR might be closed as I now learned that I should be able to configure the plugin via `overlays` (which I am still trying to implement)

**Comment by jonringer** [comment]
interesting, do darwin installations normally default to the darwin variants? (did you switch it to the channel, or was that selected for you?)

**Comment by jonringer** [comment]
overlays are usually used when you want to extend/change packages that are likely only to apply to you. adding a vimplugin like this should probably be upstreamed here

**Comment by jonringer** [comment]
or since you're sending in PRs, do what most of us do and just switch your channel to unstable and then you get your merged PRs through channels ~4hrs later

**Comment by Enteee** [comment]
> Nevertheless, I guess that this PR might be closed as I now learned that I should be able to configure the plugin via `overlays` (which I am still trying to implement)

@gotcha could you then please go ahead and close this pull request. Thank you.

**Comment by jonringer** [comment]
generally we do not backport new packages to a release channel. 

Closing

**Comment by gotcha** [comment]
@jonringer Thanks for closing
@Enteee You are right, I should have closed.

**Pull request closed without merging**
