### PR TITLE
rdkafka: 2.1.1 -> 2.2.0

### PR DESCRIPTION
**Pull request by sagikazarmark**
###### Description of changes

Update rdkafka to 2.2.0

https://github.com/confluentinc/librdkafka/releases/tag/v2.2.0

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 2xsaiko** [comment]
Result of `nixpkgs-review pr 243630` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages failed to build:</summary>
  <ul>
    <li>python310Packages.bytewax</li>
    <li>python310Packages.bytewax.dist</li>
    <li>python310Packages.confluent-kafka</li>
    <li>python310Packages.confluent-kafka.dist</li>
    <li>python310Packages.streamz</li>
    <li>python310Packages.streamz.dist</li>
    <li>python311Packages.confluent-kafka</li>
    <li>python311Packages.confluent-kafka.dist</li>
    <li>python311Packages.streamz</li>
    <li>python311Packages.streamz.dist</li>
  </ul>
</details>
<details>
  <summary>33 packages built:</summary>
  <ul>
    <li>ceph (ceph-dev)</li>
    <li>ceph-client</li>
    <li>ceph-csi</li>
    <li>ceph.dev (ceph-dev.dev)</li>
    <li>ceph.doc (ceph-dev.doc)</li>
    <li>libceph (ceph.lib ,libceph.dev ,libceph.doc ,libceph.lib ,libceph.man)</li>
    <li>ceph.man (ceph-dev.man)</li>
    <li>collectd</li>
    <li>haskellPackages.haskakafka</li>
    <li>haskellPackages.haskakafka.doc</li>
    <li>haskellPackages.hw-kafka-client</li>
    <li>haskellPackages.hw-kafka-client.doc</li>
    <li>haskellPackages.hw-kafka-conduit</li>
    <li>haskellPackages.hw-kafka-conduit.doc</li>
    <li>haskellPackages.pipes-kafka</li>
    <li>haskellPackages.pipes-kafka.doc</li>
    <li>kafka-delta-ingest</li>
    <li>kcat</li>
    <li>libserdes</li>
    <li>libserdes.dev</li>
    <li>ntopng</li>
    <li>php81Extensions.rdkafka</li>
    <li>php82Extensions.rdkafka</li>
    <li>php83Extensions.rdkafka</li>
    <li>qemu_full</li>
    <li>qemu_full.debug</li>
    <li>qemu_full.ga</li>
    <li>rdkafka</li>
    <li>rsyslog</li>
    <li>sambaFull (samba4Full)</li>
    <li>sambaFull.dev (samba4Full.dev)</li>
    <li>sambaFull.man (samba4Full.man)</li>
    <li>vector</li>
  </ul>
</details>

Result of `nixpkgs-review pr 243630` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages marked as broken and skipped:</summary>
  <ul>
    <li>collectd</li>
    <li>kafka-delta-ingest</li>
    <li>ntopng</li>
    <li>python310Packages.bytewax</li>
    <li>python310Packages.bytewax.dist</li>
    <li>python310Packages.streamz</li>
    <li>python310Packages.streamz.dist</li>
    <li>python311Packages.streamz</li>
    <li>python311Packages.streamz.dist</li>
    <li>qemu_full</li>
  </ul>
</details>
<details>
  <summary>17 packages built:</summary>
  <ul>
    <li>haskellPackages.haskakafka</li>
    <li>haskellPackages.haskakafka.doc</li>
    <li>haskellPackages.hw-kafka-client</li>
    <li>haskellPackages.hw-kafka-client.doc</li>
    <li>haskellPackages.hw-kafka-conduit</li>
    <li>haskellPackages.hw-kafka-conduit.doc</li>
    <li>haskellPackages.pipes-kafka</li>
    <li>haskellPackages.pipes-kafka.doc</li>
    <li>kcat</li>
    <li>libserdes</li>
    <li>libserdes.dev</li>
    <li>python310Packages.confluent-kafka</li>
    <li>python310Packages.confluent-kafka.dist</li>
    <li>python311Packages.confluent-kafka</li>
    <li>python311Packages.confluent-kafka.dist</li>
    <li>rdkafka</li>
    <li>vector</li>
  </ul>
</details>

**Review by milibopp — CHANGES_REQUESTED** [review]
The Kafka client libraries that depend on librdkafka have to be upgraded along with this to avoid breaking them. The Python library (confluent-kafka) is currently broken, see #246744

**Comment by sagikazarmark** [comment]
@milibopp unfortunately, I'm not familiar with the python library. I looked at the referenced issues though and it seems like it hasn't been solved upstream yet, so we may have to hold off on merging that for now.

I'm happy to collaborate on upgrades of other packages.

**Comment by wegank** [comment]
Already on master, closing.

Also, would you like to have a look at #263612?

**Pull request closed without merging**
