### PR TITLE
Update path in udev rule of mdadm

### PR DESCRIPTION
**Pull request by ts468**
Could you please check if that change makes sense? Something like that was required by nixos-rebuild.

### CODE REVIEW

**Comment by lethalman** [comment]
cc @edolstra

**Comment by peti** [comment]
:+1:

**Comment by iElectric** [comment]
Same should be done for `udev-md-raid-arrays.rules`

**Comment by ts468** [comment]
udev-md-raid-arrays.rules does not contain any path that needs replacement, at least as far as I can see

**Comment by iElectric** [comment]
```
$ grep sbin /nix/store/2a1xnmzw1l1clm39r0ql2id02vvnjyp3-mdadm-3.3/lib/udev/rules.d/*
/nix/store/2a1xnmzw1l1clm39r0ql2id02vvnjyp3-mdadm-3.3/lib/udev/rules.d/63-md-raid-arrays.rules:IMPORT{program}="/sbin/mdadm --detail --export $devnode"
/nix/store/2a1xnmzw1l1clm39r0ql2id02vvnjyp3-mdadm-3.3/lib/udev/rules.d/64-md-raid-assembly.rules:ACTION=="add", RUN+="/sbin/mdadm --incremental $devnode --offroot"
/nix/store/2a1xnmzw1l1clm39r0ql2id02vvnjyp3-mdadm-3.3/lib/udev/rules.d/64-md-raid-assembly.rules:ACTION=="remove", ENV{ID_PATH}=="?*", RUN+="/sbin/mdadm -If $name --path $env{ID_PATH}"
/nix/store/2a1xnmzw1l1clm39r0ql2id02vvnjyp3-mdadm-3.3/lib/udev/rules.d/64-md-raid-assembly.rules:ACTION=="remove", ENV{ID_PATH}!="?*", RUN+="/sbin/mdadm -If $name"
```

**Comment by ts468** [comment]
@iElectric, you're right, sorry, I didn't see the IMPORT rule. I've updated the PR.

**Comment by ts468** [comment]
@aszlig, thanks for pointing that out! So what do you suggest?
Without the patch nixos-rebuild fails, at least for me, because it somehow checks whether all udev rules can at least find the referenced binaries. With it, the system may not boot anymore...

**Comment by lethalman** [comment]
@ts468 you can fix the mdadm patching here: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/stage-1.nix#L142

**Pull request merged**
