### PR TITLE
taffybar: unbreak package by default

### PR DESCRIPTION
**Pull request by mdorman**
@peti The gtk library situation seems to have been resolved, so it builds again.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by pSub** [comment]
@GrahamcOfBorg build haskellPackages.taffybar

**Review by pSub — COMMENTED** [review]
Not sure if I'm doing something wrong, but at least ofBorg still refuses to build taffy bar

```
a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.
```

**Comment by Infinisil** [comment]
@pSub This change here will only be applied once hackage-packages.nix gets regenerated. The file changed here is the configuration for that auto-generator.

**Comment by Infinisil** [comment]
For reference, the fix for taffybar was in https://github.com/NixOS/nixpkgs/pull/57095

**Comment by peti** [comment]
Merged in e910657c1135ec9e7d2bccf1caff7a839155671f.

**Comment by pSub** [comment]
> @pSub This change here will only be applied once hackage-packages.nix gets regenerated. The file changed here is the configuration for that auto-generator.

Thank you for the explanation.

**Pull request closed without merging**
