### PR TITLE
linuxPackages.nvidia_x11: 515.86.01, 470.161.03, 390.157

### PR DESCRIPTION
**Pull request by Kiskae**
###### Description of changes

~Currently a draft since NVIDIA hasn't published the `nvidia-settings` and `nvidia-persistenced` updates.~

- Release highlights since 515.76: `nvidia_x11_production`
  - Added support for the following GPUs:
    - GeForce RTX 3050 OEM
    - GeForce RTX 3050
    - GeForce RTX 3070 Ti Laptop GPU
    - GeForce RTX 3080 Ti Laptop GPU
    - GeForce RTX 3090 Ti
    - RTX A500 Laptop GPU
    - RTX A1000 Embedded GPU
    - RTX A2000 Embedded GPU
    - RTX A1000 Laptop GPU
    - RTX A2000 8GB Laptop GPU
    - RTX A3000 12GB Laptop GPU
    - RTX A4500 Embedded GPU
    - RTX A4500 Laptop GPU
    - RTX A5500 Laptop GPU
    - T550 Laptop GPU
    - NVIDIA GeForce MX550
    - NVIDIA GeForce MX570
    - NVIDIA GeForce RTX 2050
    - NVIDIA PG509-210
  - Updated the nvidia-settings control panel to correctly limit the allowed values for GPUTargetFanSpeed to match the existing valid fan speed ranges for supported NVIDIA GPUs. The valid ranges are 30%-100% for Ampere or newer GPUs, and 1%-100% for older GPUs.
  - Fixed a regression in 515.76 that caused blank screens and hangs when starting an X server on RTX 30 series GPUs in some configurations where the boot display is connected via HDMI.
  - Fixed a bug where Marvel’s Spider-Man Remastered would sometimes crash with Xid 13 errors on Turing and later.
- Release highlights since 470.141.03: `nvidia_x11_legacy470`
  - Fixed a bug that caused the Xorg server to crash if an NvFBC capture session is started while video memory is full.
  - Improved performance on GPUs which are experiencing a high number of correctable ECC memory errors.
- `nvidia_x11_legacy390` has no release notes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kiskae** [comment]
This update appears to fix `legacy470` and `legacy390` for newer kernels.

**Comment by Kiskae** [comment]
Managed to determine the settings/persistenced hashes through the tarballs published on https://download.nvidia.com/XFree86/

Until these versions are published on github (and thus actually buildable without manually adding them to the store) I'll leave this as a draft.

**Comment by Kiskae** [comment]
Result of `nixpkgs-review pr 202417` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>bumblebee</li>
  </ul>
</details>
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>bottles</li>
    <li>heroic</li>
    <li>mangohud</li>
  </ul>
</details>
<details>
  <summary>73 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_production_open</li>
    <li>linuxKernel.packages.linux_4_14_hardened.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_4_14_hardened.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_4_14_hardened.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_4_14_hardened.nvidia_x11_production_open</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_production_open</li>
    <li>linuxKernel.packages.linux_4_19_hardened.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_4_19_hardened.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_4_19_hardened.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_4_19_hardened.nvidia_x11_production_open</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_production_open</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_production_open</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_production_open</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_legacy390 (linuxKernel.packages.linux_5_15_hardened.nvidia_x11_legacy390)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_15_hardened.nvidia_x11_legacy470)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_production (linuxKernel.packages.linux_5_15_hardened.nvidia_x11_production)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_production_open (linuxKernel.packages.linux_5_15_hardened.nvidia_x11_production_open)</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_production_open</li>
    <li>linuxKernel.packages.linux_6_0.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_6_0.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_6_0.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_6_0.nvidia_x11_production_open</li>
    <li>linuxKernel.packages.linux_6_0_hardened.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_6_0_hardened.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_6_0_hardened.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_6_0_hardened.nvidia_x11_production_open</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_production_open</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_production_open</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_production_open</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_production_open</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_production_open</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_legacy390 (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_legacy390)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_legacy470 (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_legacy470)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_production (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_production)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_production_open (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_production_open)</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_production_open</li>
    <li>primus</li>
  </ul>
</details>

**Comment by Kiskae** [comment]
Failures are due to the missing open-source utilities, will be fixed once they are published.

This should probably be tagged for `release-22.11` backport, since it fixes the legacy drivers for the kernel releases it ships with.
Ping @jonringer @PedroHLC @superherointj

**Comment by Kiskae** [comment]
Utilities have been published (https://github.com/NVIDIA/nvidia-settings/issues/93)

Although it looks like these repositories are secondary to the tarballs on download.nvidia.com, so using that as the primary source might be a future fix.

**Comment by PedroHLC** [comment]
Can you also bump the vulkan-beta one from .24 -> .25 ?

**Comment by PedroHLC** [comment]
Result of `nixpkgs-review pr 202417` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages marked as broken and skipped:</summary>
  <ul>
    <li>bumblebee</li>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11_production</li>
    <li>linuxKernel.packages.hardkernel_4_14.nvidia_x11_production_open</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_legacy390</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_legacy470</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_production</li>
    <li>linuxPackages_hardkernel_latest.nvidia_x11_production_open</li>
  </ul>
</details>
<details>
  <summary>76 packages built:</summary>
  <ul>
    <li>bottles</li>
    <li>heroic</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_4_14.nvidia_x11_production_open</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11_legacy390 (linuxKernel.packages.linux_4_14_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_4_14_hardened.nvidia_x11_legacy470)</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11_production (linuxKernel.packages.linux_4_14_hardened.nvidia_x11_production)</li>
    <li>linuxPackages_4_14_hardened.nvidia_x11_production_open (linuxKernel.packages.linux_4_14_hardened.nvidia_x11_production_open)</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_4_19.nvidia_x11_production_open</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11_legacy390 (linuxKernel.packages.linux_4_19_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_4_19_hardened.nvidia_x11_legacy470)</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11_production (linuxKernel.packages.linux_4_19_hardened.nvidia_x11_production)</li>
    <li>linuxPackages_4_19_hardened.nvidia_x11_production_open (linuxKernel.packages.linux_4_19_hardened.nvidia_x11_production_open)</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_production_open</li>
    <li>linuxPackages_5_10_hardened.nvidia_x11_legacy390 (linuxKernel.packages.linux_5_10_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_5_10_hardened.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_10_hardened.nvidia_x11_legacy470)</li>
    <li>linuxPackages_5_10_hardened.nvidia_x11_production (linuxKernel.packages.linux_5_10_hardened.nvidia_x11_production)</li>
    <li>linuxPackages_5_10_hardened.nvidia_x11_production_open (linuxKernel.packages.linux_5_10_hardened.nvidia_x11_production_open)</li>
    <li>linuxPackages.nvidia_x11_legacy390 (linuxKernel.packages.linux_5_15.nvidia_x11_legacy390)</li>
    <li>linuxPackages.nvidia_x11_legacy470 (linuxKernel.packages.linux_5_15.nvidia_x11_legacy470)</li>
    <li>linuxPackages.nvidia_x11_production (linuxKernel.packages.linux_5_15.nvidia_x11_production)</li>
    <li>linuxPackages.nvidia_x11_production_open (linuxKernel.packages.linux_5_15.nvidia_x11_production_open)</li>
    <li>linuxPackages_hardened.nvidia_x11_legacy390 (linuxPackages_5_15_hardened.nvidia_x11_legacy390)</li>
    <li>linuxPackages_hardened.nvidia_x11_legacy470 (linuxPackages_5_15_hardened.nvidia_x11_legacy470)</li>
    <li>linuxPackages_hardened.nvidia_x11_production (linuxPackages_5_15_hardened.nvidia_x11_production)</li>
    <li>linuxPackages_hardened.nvidia_x11_production_open (linuxPackages_5_15_hardened.nvidia_x11_production_open)</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_production_open</li>
    <li>linuxPackages_latest.nvidia_x11_legacy390 (linuxKernel.packages.linux_6_0.nvidia_x11_legacy390)</li>
    <li>linuxPackages_latest.nvidia_x11_legacy470 (linuxKernel.packages.linux_6_0.nvidia_x11_legacy470)</li>
    <li>linuxPackages_latest.nvidia_x11_production (linuxKernel.packages.linux_6_0.nvidia_x11_production)</li>
    <li>linuxPackages_latest.nvidia_x11_production_open (linuxKernel.packages.linux_6_0.nvidia_x11_production_open)</li>
    <li>linuxKernel.packages.linux_6_0_hardened.nvidia_x11_legacy390</li>
    <li>linuxKernel.packages.linux_6_0_hardened.nvidia_x11_legacy470</li>
    <li>linuxKernel.packages.linux_6_0_hardened.nvidia_x11_production</li>
    <li>linuxKernel.packages.linux_6_0_hardened.nvidia_x11_production_open</li>
    <li>linuxPackages_latest-libre.nvidia_x11_legacy390 (linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy390)</li>
    <li>linuxPackages_latest-libre.nvidia_x11_legacy470 (linuxKernel.packages.linux_latest_libre.nvidia_x11_legacy470)</li>
    <li>linuxPackages_latest-libre.nvidia_x11_production (linuxKernel.packages.linux_latest_libre.nvidia_x11_production)</li>
    <li>linuxPackages_latest-libre.nvidia_x11_production_open (linuxKernel.packages.linux_latest_libre.nvidia_x11_production_open)</li>
    <li>linuxPackages-libre.nvidia_x11_legacy390 (linuxKernel.packages.linux_libre.nvidia_x11_legacy390)</li>
    <li>linuxPackages-libre.nvidia_x11_legacy470 (linuxKernel.packages.linux_libre.nvidia_x11_legacy470)</li>
    <li>linuxPackages-libre.nvidia_x11_production (linuxKernel.packages.linux_libre.nvidia_x11_production)</li>
    <li>linuxPackages-libre.nvidia_x11_production_open (linuxKernel.packages.linux_libre.nvidia_x11_production_open)</li>
    <li>linuxPackages_lqx.nvidia_x11_legacy390 (linuxKernel.packages.linux_lqx.nvidia_x11_legacy390)</li>
    <li>linuxPackages_lqx.nvidia_x11_legacy470 (linuxKernel.packages.linux_lqx.nvidia_x11_legacy470)</li>
    <li>linuxPackages_lqx.nvidia_x11_production (linuxKernel.packages.linux_lqx.nvidia_x11_production)</li>
    <li>linuxPackages_lqx.nvidia_x11_production_open (linuxKernel.packages.linux_lqx.nvidia_x11_production_open)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_legacy390 (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy390)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_legacy470 (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy470)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_production (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_production)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_production_open (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_production_open)</li>
    <li>linuxPackages_xanmod.nvidia_x11_legacy390 (linuxKernel.packages.linux_xanmod.nvidia_x11_legacy390)</li>
    <li>linuxPackages_xanmod.nvidia_x11_legacy470 (linuxKernel.packages.linux_xanmod.nvidia_x11_legacy470)</li>
    <li>linuxPackages_xanmod.nvidia_x11_production (linuxKernel.packages.linux_xanmod.nvidia_x11_production)</li>
    <li>linuxPackages_xanmod.nvidia_x11_production_open (linuxKernel.packages.linux_xanmod.nvidia_x11_production_open)</li>
    <li>linuxPackages_xanmod_latest.nvidia_x11_legacy390 (linuxKernel.packages.linux_xanmod_latest.nvidia_x11_legacy390 ,linuxPackages_xanmod_stable.nvidia_x11_legacy390)</li>
    <li>linuxPackages_xanmod_latest.nvidia_x11_legacy470 (linuxKernel.packages.linux_xanmod_latest.nvidia_x11_legacy470 ,linuxPackages_xanmod_stable.nvidia_x11_legacy470)</li>
    <li>linuxPackages_xanmod_latest.nvidia_x11_production (linuxKernel.packages.linux_xanmod_latest.nvidia_x11_production ,linuxPackages_xanmod_stable.nvidia_x11_production)</li>
    <li>linuxPackages_xanmod_latest.nvidia_x11_production_open (linuxKernel.packages.linux_xanmod_latest.nvidia_x11_production_open ,linuxPackages_xanmod_stable.nvidia_x11_production_open)</li>
    <li>linuxPackages_zen.nvidia_x11_legacy390 (linuxKernel.packages.linux_zen.nvidia_x11_legacy390)</li>
    <li>linuxPackages_zen.nvidia_x11_legacy470 (linuxKernel.packages.linux_zen.nvidia_x11_legacy470)</li>
    <li>linuxPackages_zen.nvidia_x11_production (linuxKernel.packages.linux_zen.nvidia_x11_production)</li>
    <li>linuxPackages_zen.nvidia_x11_production_open (linuxKernel.packages.linux_zen.nvidia_x11_production_open)</li>
    <li>mangohud</li>
    <li>primus</li>
  </ul>
</details>

**Comment by Kiskae** [comment]
@PedroHLC merged #201790, also tested unbreaking some of the builds and nothing appears to be failing to build anymore.

**Review by PedroHLC — APPROVED** [review]

**Review by NickCao — APPROVED** [review]
Happy to see nvidia updating the long dormant legacy branches.

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
