### PR TITLE
maintainers: remove eclairevoyant

### PR DESCRIPTION
**Pull request by eclairevoyant**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by drupol** [comment]
Oh sad to see this... what's happening?

**Comment by eclairevoyant** [comment]
Consider it a "culture shock". 
I had an extended back-and-forth with other committers about whether we should move to by-name without any other changes, which was resolved with a change to the contribution guidelines to reflect that this is now permissible.

Though I don't necessarily agree with every aspect of the end-result, this would've otherwise been nothing of note, except Atemu made a comment to the effect of ["the guidelines are downstream of whatever the reviewer has in their head that day" and "the only way to enforce anything in nixpkgs is an RFC"](https://github.com/NixOS/nixpkgs/pull/338675#issuecomment-2336477709), which got agreement from other committers.

Of course the guidelines will never cover everything, and they must be fluid enough to change with our needs. However, to have committers actively advocating for _disregarding_ statements in the contribution guidelines is shocking, and demonstrates to me that committers making up their own guidelines during review is a "feature" not a "bug" as I had assumed. I always thought the worst feature of nitpkgs (sic) was lack of support for various review statements, but if that's by design, this is not a project that makes sense to contribute to for me.
(I won't even comment on the RFC process, that's been done to death.)

Cliquey behaviour from moderation seems to only cement this counterproductive design.
Code and docs can be changed, culture can't (certainly not from where I stand).

Nevertheless, the majority of folks I've worked with (yourself included) have been great and I wish you all the best.

**Comment by eclairevoyant** [comment]
PS I could self-merge but I find that quite gauche in any but the most extenuating circumstances, so a merge from someone else would be appreciated.

**Comment by drupol** [comment]
@eclairevoyant Thank you for sharing your thoughts and giving us some context. I'm not here to try to convince you to keep this PR open or to stay in the community if that’s not what you want, but I’d like to share my perspective.

Contributing to an open-source project can indeed be frustrating at times. It's a risk we all take when we get involved. Over time, you learn to manage those frustrations and find ways to emotionally detach from the aspects that weigh you down. I’ve been there myself—more than once, particularly with nixpkgs.

There were moments when I thought about doing the same thing as you're considering now, but in the end, I realized how much I enjoy working with Nix and the technology behind it. I knew I would regret stepping away completely.

Instead of leaving, I decided to adjust how I contributed. I took a break from most of the Matrix channels and gave myself the space to step back. That alone made a huge difference. Afterward, I focused on smaller, easier tasks like quick PR reviews, which kept me engaged without feeling overwhelmed. Eventually, my motivation returned, and I started to take on more again.

What I’ve learned from this is that contributors, especially in open source, need to find a balance. Burnout happens when we get too emotionally attached or overcommitted. Sometimes it helps to slow down, step back, or shift focus rather than leaving entirely.

Whatever you decide, I truly appreciate your contributions and hope you find a way to stay involved in a way that works for you.

**Comment by eclairevoyant** [comment]
Of course, if it was simply frustration, I'd continue, I mean I stuck around for over a year so far :slightly_smiling_face: In this case, though I think writing up all these guidelines which turn out to not matter does a massive disservice to (especially new) contributors who try to follow them, and dissuades said contributions. I mostly stuck around because I had hope that we can actually try to improve the experience for new-to-nixpkgs contributors, not intentionally cause them confusion over the capriciousness of reviewers. So, I think my entire reason to stay doesn't make sense anymore.

**Comment by drupol** [comment]
Fair enough...

**Comment by numinit** [comment]
Thanks for your work @eclairevoyant. The few times I interacted with you were pleasant, safe travels. :-)

**Comment by AndersonTorres** [comment]
I had no time to write an acceptable farewell letter.
I am sad you are going away.

Our bad interactions were by my fault, but our good interactions were fun and light, and I learned a thing or two from them (except about splicing - I am unable to understand that thing!).

Good bye! 
Stay safe, and show up more often!

**Comment by huantianad** [comment]
Hey @eclairevoyant, a bit late to the party, but just wanted to say a real quick farewell, express a hope that I'll still see you around, and thank you for all your help :)

**Pull request merged**
