### PR TITLE
mariadb: wrap mysqld with --basedir

### LINKED ISSUE #1053: Akonadi should include MySQL as BuildInput
Akonadi service won't start even manually. It whines that it cannot connect to MySQL.

### PR DESCRIPTION
**Pull request by pwetzel**
###### Things done
- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This wraps mysqld to always include --basedir set to the nix store location. Without the --basedir argument, mysqld cannot find an error message i18n file, looking in `/not/a/real/dir` instead. This issue specifically affects akonadi from KDE's PIM suite. 

There is what seems to be a more complete solution in #8494 that seeks to take advantage of multiple-outputs, but that more complex solution is having trouble getting finished or merged (I don't understand some of the discussion). This PR solves the immediate problem and closes #1053. The output splitting fix can come when it's ready.

I've tested this on 16.03 with KDE PIM and a normal mysql service. It seems appropriate to me to merge into release since KDE PIM is currently broken on 16.03, but I'll leave that decision to someone wiser.

### CODE REVIEW

**Comment by pwetzel** [comment]
Should have mentioned @thoughtpolice as a maintainer.

**Comment by vcunat** [comment]
Hmm, do I understand it right that `DEFAULT_MYSQL_HOME` is set to `/not/a/real/dir` so that libraries don't depend on the main output? And now it should be overridden in `mysqld` back.

**Comment by vcunat** [comment]
It certainly sounds a step forward. Thanks.

**Comment by pwetzel** [comment]
Thanks. You'd have to ask @wkennington to be sure, but I think the ideal would be `DEFAULT_MYSQL_HOME` set to `$out`, but that causes a cyclic reference in the package definition (or it did when I tried that). The multiple outputs solution seems to work around that somehow just by reading it, though I'm not sure it should be able to (shouldn't `preConfigure` be part of the hash?).

**Comment by vcunat** [comment]
No, that problem is unavoidable; if libs referred to `$out`, there's no point in splitting as both outputs would always have to be present. Note that this is/was a multiple-output derivation already.

**Comment by shlevy** [comment]
@vcunat I haven't been following this whole thing, but FWIW I disagree with the idea that there's no point in splitting outputs that have mutual references. Of course they would both always have to be present, but they wouldn't both have to be, say, included in user environments, processed as buildInputs, etc. Obviously we'd need to extend nix to support the cycle, but I don't think it would be pointless to do so.

**Comment by vcunat** [comment]
Well, yes, there would be some advantages, but I don't think this particular thread was touching this feature that seems not near being implemented in nix. (And I'm personally not convinced the added complexity in nix would be worth it; it seems much easier to e.g. create symlink trees for requested subsets of files.)

**Comment by jerith666** [comment]
This did not fix amarok; I'm running on top of current `nixos-unstable` (453086a) and just reported the `/not/a/real/dir` issue in https://github.com/NixOS/nixpkgs/issues/15264.

**Pull request merged**
