### PR TITLE
Fix derivations setting `createFindlibDestdir` in `nix-shell`

### LINKED ISSUE #121991: `nix-shell -A ocamlPackages.X` doesn't work if `X` contains `createFindlibDestdir = true`
**Describe the bug**

Any package depending on `findlib` and which sets `createFindlibDestdir = true` will trigger the following line of the setup hook:
https://github.com/NixOS/nixpkgs/blob/fc8162a69bafc6d71a53c35c6470ee57ece4c66d/pkgs/development/tools/ocaml/findlib/default.nix#L42

Unfortunately, this setup hook is also called when running `nix-shell -A`. This makes the latter unusable, even though this is one of the essential features of NIx.

If you have already built the derivation for a given package, then the directory will already be there and you won't notice the error.

**To Reproduce**

Take a derivation you have not built locally, which depends on `findlib` and sets `createFindlibDestdir = true` and run `nix-shell -A`. E.g., `nix-shell -A ocamlPackages.process`.

It fails with: `mkdir: cannot create directory ‘/nix/store/wa3qhw038klf5fqnhndgzpchvqj0awn4-ocaml4.10.2-process-0.2.1’: Read-only file system`.

**Additional context**

We initially detected this problem with @CohenCyril when working with the Coq derivation. But we are not the first ones to notice it. For instance, @vbgl mentioned the problem in 2018: https://github.com/coq/coq/pull/8602#discussion_r222996538.

I'm self-assigning because there is an easy "quick fix", which is to allow `mkdir` to fail, and I will open a PR with it.

### PR DESCRIPTION
**Pull request by Zimmi48**
###### Motivation for this change

Fix #121991

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Zimmi48** [comment]
> by appending to the `preCheck` hook maybe?

There is also a `preInstall` hook. Is there any reason you didn't suggest this one?

**Comment by sternenseemann** [comment]
Typo, I would suggest preInstall of course.

**Comment by Zimmi48** [comment]
Here is a new version based on this idea that seems to work as well. I didn't know how to append to the `preInstall` hook, so I just replaced it.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 121992` at d0bcd0ea run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>17 packages marked as broken and skipped:</summary>
  <ul>
    <li>coccinelle</li>
    <li>coq_8_5</li>
    <li>coq_8_6</li>
    <li>cubicle</li>
    <li>haxe_3_2</li>
    <li>haxe_3_4</li>
    <li>libvmi</li>
    <li>monotoneViz</li>
    <li>obliv-c</li>
    <li>opa</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>63 packages skipped due to time constraints:</summary>
  <ul>
    <li>abella</li>
    <li>acgtk</li>
    <li>alt-ergo</li>
    <li>beluga</li>
    <li>coq_8_10</li>
    <li>coq_8_12</li>
    <li>coq_8_13</li>
    <li>coq_8_7</li>
    <li>coq_8_8</li>
    <li>coq_8_9</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>53 packages built successfully:</summary>
  <ul>
    <li>coq (coqPackages.coq ,coq_8_11)</li>
    <li>coqPackages.Cheerios</li>
    <li>coqPackages.CoLoR</li>
    <li>coqPackages.ITree</li>
    <li>coqPackages.InfSeqExt</li>
    <li>coqPackages.QuickChick</li>
    <li>coqPackages.StructTact</li>
    <li>coqPackages.Verdi</li>
    <li>coqPackages.bignums</li>
    <li>coqPackages.contribs.zorns-lemma</li>
    <li>coqPackages.coq-bits</li>
    <li>coqPackages.coq-elpi</li>
    <li>coqPackages.coq-ext-lib</li>
    <li>coqPackages.coqeal</li>
    <li>coqPackages.coqhammer</li>
    <li>coqPackages.coqprime</li>
    <li>coqPackages.coqtail-math</li>
    <li>coqPackages.coquelicot</li>
    <li>coqPackages.corn</li>
    <li>coqPackages.dpdgraph</li>
    <li>coqPackages.equations</li>
    <li>coqPackages.flocq</li>
    <li>coqPackages.fourcolor</li>
    <li>coqPackages.gappalib</li>
    <li>coqPackages.hierarchy-builder</li>
    <li>coqPackages.interval</li>
    <li>coqPackages.iris</li>
    <li>coqPackages.math-classes</li>
    <li>coqPackages.mathcomp</li>
    <li>coqPackages.mathcomp-abel</li>
    <li>coqPackages.mathcomp-algebra</li>
    <li>coqPackages.mathcomp-analysis</li>
    <li>coqPackages.mathcomp-bigenough</li>
    <li>coqPackages.mathcomp-character</li>
    <li>coqPackages.mathcomp-field</li>
    <li>coqPackages.mathcomp-fingroup</li>
    <li>coqPackages.mathcomp-finmap</li>
    <li>coqPackages.mathcomp-real-closed</li>
    <li>coqPackages.mathcomp-solvable</li>
    <li>coqPackages.ssreflect (coqPackages.mathcomp-ssreflect)</li>
    <li>coqPackages.metalib</li>
    <li>coqPackages.multinomials</li>
    <li>coqPackages.odd-order</li>
    <li>coqPackages.paco</li>
    <li>coqPackages.paramcoq</li>
    <li>coqPackages.simple-io</li>
    <li>coqPackages.stdpp</li>
    <li>coqPackages.tlc</li>
    <li>dune_2</li>
    <li>framac</li>
    <li>hevea</li>
    <li>opaline</li>
    <li>why3</li>
  </ul>
</details>

**Comment by Zimmi48** [comment]
@sternenseemann Does the new version look good to you?

**Comment by sternenseemann** [comment]
I've thought about it and I think overriding the `preInstall` hook may gives us trouble. For one I don't really like it because it becomes harder to use `preInstall` and overriding is probably compromised. More importantly though I think a lot of ocaml packages don't run the `preInstall hook due to `installPhases` like this:

```
  installPhase = "ocaml setup.ml -install";
```

I think the easiest could be to remove `createFindlibDestdir` altogether and insert the `mkdir` calls manually everywhere where it is needed. We don't really need to keep this around since the ecosystem seems to be converging on dune anyways. What do you think? I'm somewhat inclined to sacrifice myself and do the chore as well.

**Comment by Zimmi48** [comment]
I didn't really consider this option because I thought it would be a huge task. Checking now with grep, I see that there are still 116 occurrences. That's not that many compared to the 812 occurrences of `buildDunePackage`. So if you are up to the task, I'd be happy with the solution you propose.

**Comment by sternenseemann** [comment]
As @symphorien pointed out, alternatively we could also add a new phase via the setup hook like `autoreconfHook` does:

<https://github.com/NixOS/nixpkgs/blob/1834bc871199fc6583cf270474aacbda9e5127f2/pkgs/build-support/setup-hooks/autoreconf.sh#L1-L7>

**Comment by Zimmi48** [comment]
Given that your PR is ready, and that this feature was becoming less and less useful with the general move toward Dune, I wouldn't bother doing differently now.

**Comment by sternenseemann** [comment]
@vbgl what do you think?

**Comment by vbgl** [comment]
I acknowledge that there is a problem that should be fixed.

This PR has a QnD fix that looks OK but causes a massive rebuild so we have to double-check before merging…

PR 124504 seems much better (a lot of welcome cleaning, a thorough understanding of how to fix the issue) but the change is large thus tedious to review.

**Comment by sternenseemann** [comment]
Something in a similar spirit was incidentally implemented in #133008: a3ab43d3a45338f845a0f8a12ed34e84c8b79dae.

**Pull request closed without merging**
