### PR TITLE
more boost downgrades

### PR DESCRIPTION
**Pull request by vcunat**
###### Motivation for this change
These packages started failing now that the default boost version has
been bumped from 1.69 to 1.77. They are now pinned to the highest boost
version they will build against.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
I guess I should /cc the target PR #148396

**Comment by vcunat** [comment]
From OfBorg I noticed just one larger independent issue which should be fixed by 28e731742c2.

**Comment by oxalica** [comment]
I fetched all logs of still-failing `x86_64-linux` jobs from this recent evaluation https://hydra.nixos.org/eval/1732213, `grep`-ed with  `boost` and here's the result. I think most packages from this list also need pinning the version of `boost`.

<details>
<summary>56 lines</summary>

```
160462262-libpointmatcher.x86_64-linux.log
160468241-masari.x86_64-linux.log
160478816-libtorrent-rasterbar-1_1_x.x86_64-linux.log
160479753-monotone.x86_64-linux.log
160500363-arc_unpacker.x86_64-linux.log
160540402-swiften.x86_64-linux.log
160540480-pivxd.x86_64-linux.log
160564351-cpp-netlib.x86_64-linux.log
160579764-particl-core.x86_64-linux.log
160584032-nova-filters.x86_64-linux.log
160586177-powerdns.x86_64-linux.log
160588878-uhd3_5.x86_64-linux.log
160591233-namecoind.x86_64-linux.log
160596352-libbitcoin.x86_64-linux.log
161302024-ndn-tools.x86_64-linux.log
161303057-nfd.x86_64-linux.log
161446162-rethinkdb.x86_64-linux.log
161457339-litecoind.x86_64-linux.log
161459340-wt3.x86_64-linux.log
161459694-mozart2.x86_64-linux.log
161469148-librecad.x86_64-linux.log
161583675-ycmd.x86_64-linux.log
161639202-namecoin.x86_64-linux.log
161639682-emulationstation.x86_64-linux.log
161644472-python39Packages.graph-tool.x86_64-linux.log
161644527-opendungeons.x86_64-linux.log
161645143-litecoin.x86_64-linux.log
161646842-colobot.x86_64-linux.log
161648316-snapcast.x86_64-linux.log
161648981-foundationdb.x86_64-linux.log
161652078-gnuradio3_8Packages.gnuradio.x86_64-linux.log
161653351-python39Packages.imbalanced-learn.x86_64-linux.log
161654369-sourcetrail.x86_64-linux.log
161655798-dashpay.x86_64-linux.log
161657474-digikam.x86_64-linux.log
161658640-gnuradio3_8Minimal.x86_64-linux.log
161660600-freecad.x86_64-linux.log
161661659-opentoonz.x86_64-linux.log
161662191-sdrangel.x86_64-linux.log
161664993-pokerth-server.x86_64-linux.log
161665236-python39Packages.roboschool.x86_64-linux.log
161668133-python39Packages.scikit-survival.x86_64-linux.log
161669158-python38Packages.imbalanced-learn.x86_64-linux.log
161669524-foundationdb61.x86_64-linux.log
161673596-pokerth.x86_64-linux.log
161674671-python38Packages.graph-tool.x86_64-linux.log
161674815-python38Packages.roboschool.x86_64-linux.log
161675184-bombono.x86_64-linux.log
161679644-musikcube.x86_64-linux.log
161681221-gplates.x86_64-linux.log
161681328-mapnik.x86_64-linux.log
161681376-pivx.x86_64-linux.log
161685604-mirtk.x86_64-linux.log
161688486-slic3r.x86_64-linux.log
161690279-arrayfire.x86_64-linux.log
161693015-ethminer-free.x86_64-linux.log
```

</details>

**Comment by veprbl** [comment]
@oxalica Thanks for providing the list, I've opened an issue.

**Pull request merged**
