### PR TITLE
python3Packages.locust: init at 2.14.1

### PR DESCRIPTION
**Pull request by shyim**
###### Description of changes
 
Packed the open source load test tool [locustio](https://locust.io). It was a while ago packaged but has been removed because it was unmaintained in https://github.com/NixOS/nixpkgs/pull/104351

So this reads the newest version and makes me the maintainer

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tpwrules** [comment]
I can't get this to build due to problems with mypy. I tried the commit as it is and rebased on current master and both failed.

**Comment by shyim** [comment]
What was the error?

**Comment by tpwrules** [comment]
It was Tox complaining that mypy could not be installed. I modified the derivation to install it, then mypy complained that the tests did not pass.

This should be rebased on current master, upgraded to latest locustio, then I will review it again.

**Comment by shyim** [comment]
@tpwrules do you want to try out again?

**Comment by tpwrules** [comment]
This still does not work:
```
error: builder for '/nix/store/ps9wmd9zal6cci106hlg1cgd2qj7lad4-python3.11-locustio-2.14.1.drv' failed with exit code 1;
       last 10 log lines:
       > adding 'locust-0.0.0.dist-info/RECORD'
       > removing build/bdist.linux-x86_64/wheel
       > Finished executing setuptoolsBuildPhase
       > installing
       > Executing pipInstallPhase
       > /build/source/dist /build/source
       > Processing ./locust-0.0.0-py3-none-any.whl
       > ERROR: Could not find a version that satisfies the requirement gevent>=20.12.1 (from locust) (from versions: none)
       > ERROR: No matching distribution found for gevent>=20.12.1
       > 
       For full logs, run 'nix log /nix/store/ps9wmd9zal6cci106hlg1cgd2qj7lad4-python3.11-locustio-2.14.1.drv'.
error: builder for '/nix/store/77pww50w9a9rw462g2mdsckd7s4svv6b-python3.10-locustio-2.14.1.drv' failed with exit code 1;
       last 10 log lines:
       > Rewriting #!/nix/store/abax98471z8fshv4b9p46bkh3lxmpy0z-python3-3.10.9/bin/python3.10 to #!/nix/store/abax98471z8fshv4b9p46bkh3lxmpy0z-python3-3.10.9
       > wrapping `/nix/store/lpskblj1qz49c0373vxqglzl9h8v374j-python3.10-locustio-2.14.1/bin/locust'...
       > Executing pythonRemoveTestsDir
       > Finished executing pythonRemoveTestsDir
       > running install tests
       > mypy: install_deps> python -I -m pip install mypy==0.981
       > mypy: exit 1 (8.69 seconds) /build/source> python -I -m pip install mypy==0.981 pid=337
       >   mypy: FAIL code 1 (9.08 seconds)
       >   evaluation failed :( (9.34 seconds)
       > 
       For full logs, run 'nix log /nix/store/77pww50w9a9rw462g2mdsckd7s4svv6b-python3.10-locustio-2.14.1.drv'.
```

Can you explain how you are testing and confirm it works for you? I used `nixpkgs-review` to check.

**Comment by shyim** [comment]
Just run nix build. Maybe something because I built it on macOS and the sandbox is not so good. I will look later on Linux

**Comment by thornycrackers** [comment]
Can we rename this to `locust` instead of `locustio`? The tool is canonically referred to as `locust` everywhere.

**Comment by adisbladis** [comment]
> Can we rename this to `locust` instead of `locustio`? The tool is canonically referred to as `locust` everywhere.

Good catch. `locust` is the canonical pypi name: https://pypi.org/project/locust/

**Comment by teto** [comment]
main folder contains a pryproject.toml https://github.com/locustio/locust/blob/master/pyproject.toml have you tried packaging it with poetry ? it should make the package easier to maintain.

**Pull request closed without merging**
