### PR TITLE
Revert "python3: splice python within python3Packages.callPackage"

### PR DESCRIPTION
**Pull request by ghost**
Reverts NixOS/nixpkgs#245475

### CODE REVIEW

**Comment by amjoseph-nixpkgs** [comment]
This broke #212795 first, which is more urgent, and has been waiting for a while now.

**Comment by FRidh** [comment]
Please record the motivation in the commit when reverting.

**Comment by amjoseph-nixpkgs** [comment]
> Please record the motivation in the commit when reverting.

Sorry about that.

**Comment by SuperSandro2000** [comment]
fyi @Artturin

**Comment by amjoseph-nixpkgs** [comment]
> fyi @Artturin

https://github.com/NixOS/nixpkgs/pull/245475#issuecomment-1652686302

https://github.com/NixOS/nixpkgs/pull/245475#issuecomment-1652751286

**Comment by Artturin** [comment]
Revert of this revert https://github.com/NixOS/nixpkgs/pull/247245

**Pull request merged**
