### PR TITLE
[Backport staging-22.11] Pipewire 0.3.65

### PR DESCRIPTION
**Pull request by K900**
###### Description of changes

Manual backport of #212972 and everything that came before, 0.3.60 is rather buggy so hopefully this is better.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
Will undraft once I make sure it builds successfully.

**Comment by K900** [comment]
Builds successfully, undrafted.

**Comment by mweinelt** [comment]
Running into the same test failures on both aarch64-linux and x86_64-linux in libuv.

```
libuv-aarch64-linux> not ok 261 - tcp_bind6_error_addrinuse
libuv-aarch64-linux> # exit code 134
libuv-aarch64-linux> # Output from process `tcp_bind6_error_addrinuse`:
libuv-aarch64-linux> # Assertion failed in test/test-tcp-bind6-error.c on line 60: r == UV_EADDRINUSE
[...]
libuv-aarch64-linux> not ok 267 - tcp_bind_error_addrinuse_listen
libuv-aarch64-linux> # exit code 134
libuv-aarch64-linux> # Output from process `tcp_bind_error_addrinuse_listen`:
libuv-aarch64-linux> # Assertion failed in test/test-tcp-bind-error.c on line 99: r == UV_EADDRINUSE
```

**Comment by K900** [comment]
Wait how does this even affect libuv

**Comment by mweinelt** [comment]
I don't think it does, but libuv is on the way to build pipewire.

**Comment by K900** [comment]
Must be a very recent regression then.

**Comment by mweinelt** [comment]
I'm seeing the same failure on release-22.11 … weird. Builds fine on hydra.

**Comment by vcunat** [comment]
Uhhh, how come we backported this and didn't add the necessary fix?
https://github.com/NixOS/nixpkgs/pull/214387

Now we'd need to rebuild again :-(

**Pull request merged**
