### PR TITLE
samba: 4.19.5 -> 4.20.0, ldb: 2.8.0 -> 2.9.0

### PR DESCRIPTION
**Pull request by qubitnano**
## Description of changes

https://www.samba.org/samba/history/samba-4.20.0.html

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by ivan — APPROVED** [review]
I built and tested this PR on my x86_64 NixOS master and didn't observe any issues with my Samba servers.

**Comment by wegank** [comment]
@ofborg build samba

**Review by wegank — APPROVED** [review]

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 300156` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>43 packages marked as broken and skipped:</summary>
  <ul>
    <li>anilibria-winmaclinux</li>
    <li>arcan</li>
    <li>booster</li>
    <li>kaffeine</li>
    <li>kodiPackages.inputstream-adaptive</li>
    <li>kodiPackages.inputstream-ffmpegdirect</li>
    <li>kodiPackages.inputstream-rtmp</li>
    <li>kodiPackages.joystick</li>
    <li>kodiPackages.libretro</li>
    <li>kodiPackages.libretro-2048</li>
    <li>kodiPackages.libretro-fuse</li>
    <li>kodiPackages.libretro-genplus</li>
    <li>kodiPackages.libretro-mgba</li>
    <li>kodiPackages.libretro-nestopia</li>
    <li>kodiPackages.libretro-snes9x</li>
    <li>kodiPackages.pvr-hdhomerun</li>
    <li>kodiPackages.pvr-hts</li>
    <li>kodiPackages.pvr-iptvsimple</li>
    <li>kodiPackages.pvr-vdr-vnsi</li>
    <li>kodiPackages.steam-controller</li>
    <li>kodiPackages.vfs-libarchive</li>
    <li>kodiPackages.vfs-rar</li>
    <li>kodiPackages.vfs-sftp</li>
    <li>kodiPackages.visualization-fishbmc</li>
    <li>kodiPackages.visualization-goom</li>
    <li>kodiPackages.visualization-matrix</li>
    <li>kodiPackages.visualization-pictureit</li>
    <li>kodiPackages.visualization-projectm</li>
    <li>kodiPackages.visualization-shadertoy</li>
    <li>kodiPackages.visualization-spectrum</li>
    <li>kodiPackages.visualization-starburst</li>
    <li>kodiPackages.visualization-waveform</li>
    <li>kphotoalbum</li>
    <li>ldb</li>
    <li>ldb.dev</li>
    <li>python311Packages.python-vlc</li>
    <li>python311Packages.python-vlc.dist</li>
    <li>python312Packages.python-vlc</li>
    <li>python312Packages.python-vlc.dist</li>
    <li>qemu_full</li>
    <li>sanoid</li>
    <li>xarcan</li>
    <li>zpool-auto-expand-partitions</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>legba</li>
  </ul>
</details>
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>enum4linux</li>
    <li>enum4linux-ng</li>
    <li>enum4linux-ng.dist</li>
    <li>python311Packages.pysmbc</li>
    <li>python311Packages.pysmbc.dist</li>
    <li>python312Packages.pysmbc</li>
    <li>python312Packages.pysmbc.dist</li>
    <li>samba (samba4)</li>
    <li>samba.dev (samba4.dev)</li>
    <li>samba.man (samba4.man)</li>
    <li>sambaFull (samba4Full)</li>
    <li>sambaFull.dev (samba4Full.dev)</li>
    <li>sambaFull.man (samba4Full.man)</li>
    <li>termscp</li>
  </ul>
</details>

**Comment by anthonyroussel** [comment]
Hello Samba team!

This PR broke the build of sssd, because it is incompatible with Samba 4.20.
Could someone review my PR to fix the `sssd` build, please? :pray:

**Pull request merged**
