### PR TITLE
Remove python 2.6

### PR DESCRIPTION
**Pull request by falsifian**
Python 2.6 is not receiving security updates [as of October 2013](https://www.python.org/download/releases/2.6.9/). I think it's a bad idea to have insecure software hanging around, so this pull request deletes it.

If people really want to keep it, can we make it impossible to accidentally install, e.g. make it require a iUnderstandPython26IsInsecureButIWantItAnyway config option to be set to true?

Paging @bjornfor as a random person who's touched Python stuff recently. (I'm making this change fairly blindly.)

It looks like cudatoolkit explicitly depends on Python 2.6, but this override has been copied and pasted from version to version. Paging @jb55 as a random person who's modified cudatoolkit stuff.

Paging @geerds who posted on nix-dev about using Python 2.6 last year.

### CODE REVIEW

**Comment by domenkozar** [comment]
I still need to use python 2.6, but that shouldn't be a reason to keep it (I can just use older nixpkgs checkout).

**Comment by rbvermaa** [comment]
I prefer to keep it, as we are using it for some older software.

**Comment by edolstra** [comment]
It could be marked as broken (`meta.broken = true`).

**Comment by rbvermaa** [comment]
But it is not broken right?

**Comment by edolstra** [comment]
If it has unpatched security bugs it's arguably broken (but I don't know if that's the case).

**Comment by edolstra** [comment]
CUDA toolkit 6.5 builds fine with Python 2.7, btw.

**Comment by vcunat** [comment]
Marking as broken (or setting empty platforms) seems the easiest way to disable it while allowing to use it with an explicit opt-in. That would also stop it being built on Hydra.nixos.org, but I guess that's what we want as well (and ``python26Packages`` already aren't built).

**Comment by matthiasbeyer** [comment]
@vcunat While I consider emptying the platforms variable seems like an ugly hack to me, I'm fine with marking it as broken.

Maybe we should introduce another variable `endOfLive` or something exactly for this case.

**Comment by falsifian** [comment]
Thanks for the feedback. I've posted https://github.com/NixOS/nixpkgs/pull/8757 to mark Python 2.6 as broken instead; I'll close this PR.

**Pull request closed without merging**
