### PR TITLE
Kdevelop5 beta 2

### PR DESCRIPTION
**Pull request by ambrop72**
Tested this on 16.03 - starts up all right, sometimes freezes but that seems like an upstream bug. I assume it works all right within Plasma5 but since I'm using it from Xfce, I had to do some system configuration (like in the kde5 desktop-manager service) to get KDE5 apps to run in general, and also [this hack](https://github.com/NixOS/nixpkgs/issues/13715#issuecomment-209089191) to get icons to show up.
###### Things done
- [x] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
Hm
> curl: (9) Server denied you to change to the given directory
error: cannot download kdevplatform-4.90.91.tar.xz from any mirror

**Comment by ambrop72** [comment]
@joachifm URL went wrong while I was refactoring it and I didn't notice because it was already downloaded, fixed it.

**Comment by joachifm** [comment]
Now it fails with
> dev/lib/cmake/Qt5ScriptTools/Qt5ScriptToolsConfig.cmake:15 (message):
  The imported target "Qt5::ScriptTools" references the file
     "/nix/store/1aq378wxq4xilmkzkxnf6iqa54kmsc22-qtscript-5.5.1-dev/lib/libQt5ScriptTools.so.5.5.1"
  but this file does not exist.  Possible reasons include:
  * The file was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and contained
     "/nix/store/1aq378wxq4xilmkzkxnf6iqa54kmsc22-qtscript-5.5.1-dev/lib/cmake/Qt5ScriptTools/Qt5ScriptToolsConfig.cmake"
  but not all the files it references.

**Comment by ttuegel** [comment]
@joachifm This looks like a failure in `fixQtModuleCMakeConfig`; see [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/qt-5/5.5/qtscript/default.nix#L8). The CMake file should be getting the shared library from the `$out` output, rather than the `$dev` output.

**Comment by yochai** [comment]
Without okteta it seems to build fine, opened, compiled and ran in debug a small C99 Makefile project.
It seems that the issue with qtscript, at-lest for this commit, affects okteta only. qtscript is used by other packages in the commit, kdevplatform for example.  
Not sure how to fix the problem with okteta and qtscript.

**Comment by joachifm** [comment]
Is this still being worked on?

**Comment by ambrop72** [comment]
Hey, I think it's still relevant though it doesn't work due to the okteta issue (which is not a problem with this pull request itself, just makes it not work). I may find some time this weekend to look into it.

**Comment by ambrop72** [comment]
Closing in favor of https://github.com/NixOS/nixpkgs/pull/18031

**Pull request closed without merging**
