### PR TITLE
Rework postfix module and package

### PR DESCRIPTION
**Pull request by abbradar**
Changes are as follows:
- Data directory for Postfix is moved from `/var/postfix` to `/var/lib/postfix` -- _this is a breaking change_! I felt that the change is good enough and the module was being reworked anyway, but we may want to discuss this.
- `postfix30` package is now patched to not emit warnings that cannot be effectively fixed on NixOS (access rights in the Nix store)
- `postfix30` package now has support for optional building of various database drivers.
- `postfix` NixOS module is reworked so more options are not emitted when you want it, and users and groups are created only when their names are unchanged.
- Access rights setting script is redone so there are no warnings emitted from `postfix` daemon now. Hooray!
- New options `aliasFiles` and `mapFiles` are added for compiling alias and map files on service start. They are used for some files already.
- Some paths are fixed in the `postfix30` package.

And other ones, less interesting or things that I've forgotten.

### CODE REVIEW

**Comment by globin** [comment]
You might want to move the stuff from /var/postfix to /var/lib/postfix if only the former exists to not break too many setups.

**Comment by abbradar** [comment]
Done, thanks for the idea!

**Comment by peti** [comment]
:+1:

**Comment by hrdinka** [comment]
Please remove this commit:

> nixos/postfix: fix double TLS configuration

The TLS config isn't doubled. There is one for `smtp_*` and one for `smtpd_*` (recognize the trailing `d`).

`smtp_*` is used when postfix acts as client (connects to a remote server)
`smtpd_*` is used when postfix acts as server (clients connect to postfix)

Without this TLS is broken.

**Comment by abbradar** [comment]
Ouch, thanks, I haven't known about this!

**Comment by hrdinka** [comment]
:+1:

**Comment by abbradar** [comment]
I've changed pre-starting script a bit to fix access rights for `sendmail` to work properly.

**Comment by abbradar** [comment]
I'll push this in several days unless we find any new problems.

**Pull request merged**
