### PR TITLE
rPackages.arrow: fix for current CRAN version 14.0.0.2

### PR DESCRIPTION
**Pull request by philipp-baumann**
## Description of changes

Current {arrow} on CRAN is now at 14.0.0.2: https://cran.r-project.org/web/packages/arrow/index.html . `arrow-cpp` (libarrow) in Nixpkgs master is currently at 15.0.0, which means that the versions are not compatible when compiling `rPackages.arrow`. `arrow-cpp` is a compile- and run-time dependency of `rPackages.arrow`. Currently, the release cycle is out-of-sync, more details here: https://github.com/apache/arrow/issues/39698 . On the long term, such a mismatch of library versions is likely, and also it seems more likely that the `arrow-cpp` is more frequently updated on Nixpkgs compared to CRAN updates/adjustments/fixes in `rPackages`. By going for a patch, I think its more likely to avoid unnoticed breakages in Nixpkgs arrow CRAN package (if a patch is not necessary, it would maybe be easy to disable in `default.nix` in `r-modules`. So this would have to be checked, for now manually, but there could be also additional, automated scripts for this after updates with `generate-r-packages.R` for CRAN.

## Things done

Regenerated rPackages using `generate-r-packages.R`. Adjusted `buildInputs` and `nativeBuildInputs` for failing build of `rPackages.arrow`. I could not yet figure out how to apply the patch arrow-cpp as Input for `rPackages.arrow`. 

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by philipp-baumann** [comment]
Result of `nixpkgs-review pr 289274` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python312Packages.nbdev</li>
    <li>python312Packages.nbdev.dist</li>
    <li>python312Packages.rpy2</li>
    <li>python312Packages.rpy2.dist</li>
  </ul>
</details>
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>python311Packages.nbdev</li>
    <li>python311Packages.nbdev.dist</li>
    <li>python311Packages.radian</li>
    <li>python311Packages.radian.dist</li>
    <li>python311Packages.rchitect</li>
    <li>python311Packages.rchitect.dist</li>
    <li>python311Packages.rpy2</li>
    <li>python311Packages.rpy2.dist</li>
    <li>python312Packages.radian</li>
    <li>python312Packages.radian.dist</li>
    <li>python312Packages.rchitect</li>
    <li>python312Packages.rchitect.dist</li>
    <li>quarto</li>
  </ul>
</details>

**Comment by philipp-baumann** [comment]
Result of `nixpkgs-review pr 289274` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python312Packages.nbdev</li>
    <li>python312Packages.nbdev.dist</li>
    <li>python312Packages.rpy2</li>
    <li>python312Packages.rpy2.dist</li>
  </ul>
</details>
<details>
  <summary>15 packages built:</summary>
  <ul>
    <li>python311Packages.nbdev</li>
    <li>python311Packages.nbdev.dist</li>
    <li>python311Packages.radian</li>
    <li>python311Packages.radian.dist</li>
    <li>python311Packages.rchitect</li>
    <li>python311Packages.rchitect.dist</li>
    <li>python311Packages.rpy2</li>
    <li>python311Packages.rpy2.dist</li>
    <li>python312Packages.radian</li>
    <li>python312Packages.radian.dist</li>
    <li>python312Packages.rchitect</li>
    <li>python312Packages.rchitect.dist</li>
    <li>quarto</li>
    <li>rWrapper</li>
    <li>radianWrapper</li>
  </ul>
</details>

**Comment by philipp-baumann** [comment]
Result of `nixpkgs-review pr 289274` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python312Packages.nbdev</li>
    <li>python312Packages.nbdev.dist</li>
    <li>python312Packages.rpy2</li>
    <li>python312Packages.rpy2.dist</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>jasp-desktop</li>
  </ul>
</details>
<details>
  <summary>21 packages built:</summary>
  <ul>
    <li>cantor (libsForQt5.cantor ,plasma5Packages.cantor)</li>
    <li>labplot</li>
    <li>python311Packages.nbdev</li>
    <li>python311Packages.nbdev.dist</li>
    <li>python311Packages.radian</li>
    <li>python311Packages.radian.dist</li>
    <li>python311Packages.rchitect</li>
    <li>python311Packages.rchitect.dist</li>
    <li>python311Packages.rpy2</li>
    <li>python311Packages.rpy2.dist</li>
    <li>python312Packages.radian</li>
    <li>python312Packages.radian.dist</li>
    <li>python312Packages.rchitect</li>
    <li>python312Packages.rchitect.dist</li>
    <li>quarto</li>
    <li>rstudio</li>
    <li>rstudio-server</li>
    <li>rstudioServerWrapper</li>
    <li>rstudioWrapper</li>
    <li>sage</li>
    <li>sageWithDoc</li>
  </ul>
</details>

**Comment by Kupac** [comment]
I could not reproduce the build, it fails for me with a different error. I'm also not sure if patching is the correct way to handle this. I'd first try to override the version and hash of the pkgs.arrow without patching anything.

**Comment by Kupac** [comment]
You can probably also put this PR [back to draft](https://docs.github.com/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests) stage. PR-s should contain a commit for each logical unit (in this case that's just the `rPackages.arrow`, so a single commit)

**Comment by philipp-baumann** [comment]
```sh
nix-build --pure -A rPackages.arrow
```

```sh
* removing '/nix/store/c6azanmwdk0mzx7xh5jsp47lv1mplsvd-r-arrow-14.0.0.2/library/arrow'
error: builder for '/nix/store/rm53v5qzndi2fspvi7i87ah540iq35m1-r-arrow-14.0.0.2.drv' failed with exit code 1;
       last 10 log lines:
       > /nix/store/k687y4hiraslz65qz8pli1wb5wmcabvn-clang-wrapper-16.0.6/bin/c++ -std=gnu++17 -I"/nix/store/1hfs8ylpsyfrrakhyvskr4dgycd0l16c-R-4.3.2/lib/R/include" -DNDEBUG -I/nix/store/a5yby7z43cngyy3m3h9hmrbswmpxqflx-arrow-cpp-14.0.0/include   -DARROW_R_WITH_PARQUET -DARROW_R_WITH_DATASET -DARROW_R_WITH_ACERO -DARROW_R_WITH_SUBSTRAIT -DARROW_R_WITH_JSON -DARROW_R_WITH_S3 -I'/nix/store/icgvzqb9iimya88zh611qzbc91b6zxqk-r-cpp11-0.4.7/library/cpp11/include' -isystem /nix/store/ydfb1m5h1lcghpvs2hmv9686z008paij-libcxx-16.0.6-dev/include/c++/v1    -fPIC  -g -O2  -c symbols.cpp -o symbols.o
       > /nix/store/k687y4hiraslz65qz8pli1wb5wmcabvn-clang-wrapper-16.0.6/bin/c++ -std=gnu++17 -I"/nix/store/1hfs8ylpsyfrrakhyvskr4dgycd0l16c-R-4.3.2/lib/R/include" -DNDEBUG -I/nix/store/a5yby7z43cngyy3m3h9hmrbswmpxqflx-arrow-cpp-14.0.0/include   -DARROW_R_WITH_PARQUET -DARROW_R_WITH_DATASET -DARROW_R_WITH_ACERO -DARROW_R_WITH_SUBSTRAIT -DARROW_R_WITH_JSON -DARROW_R_WITH_S3 -I'/nix/store/icgvzqb9iimya88zh611qzbc91b6zxqk-r-cpp11-0.4.7/library/cpp11/include' -isystem /nix/store/ydfb1m5h1lcghpvs2hmv9686z008paij-libcxx-16.0.6-dev/include/c++/v1    -fPIC  -g -O2  -c table.cpp -o table.o
       > /nix/store/k687y4hiraslz65qz8pli1wb5wmcabvn-clang-wrapper-16.0.6/bin/c++ -std=gnu++17 -I"/nix/store/1hfs8ylpsyfrrakhyvskr4dgycd0l16c-R-4.3.2/lib/R/include" -DNDEBUG -I/nix/store/a5yby7z43cngyy3m3h9hmrbswmpxqflx-arrow-cpp-14.0.0/include   -DARROW_R_WITH_PARQUET -DARROW_R_WITH_DATASET -DARROW_R_WITH_ACERO -DARROW_R_WITH_SUBSTRAIT -DARROW_R_WITH_JSON -DARROW_R_WITH_S3 -I'/nix/store/icgvzqb9iimya88zh611qzbc91b6zxqk-r-cpp11-0.4.7/library/cpp11/include' -isystem /nix/store/ydfb1m5h1lcghpvs2hmv9686z008paij-libcxx-16.0.6-dev/include/c++/v1    -fPIC  -g -O2  -c threadpool.cpp -o threadpool.o
       > /nix/store/k687y4hiraslz65qz8pli1wb5wmcabvn-clang-wrapper-16.0.6/bin/c++ -std=gnu++17 -I"/nix/store/1hfs8ylpsyfrrakhyvskr4dgycd0l16c-R-4.3.2/lib/R/include" -DNDEBUG -I/nix/store/a5yby7z43cngyy3m3h9hmrbswmpxqflx-arrow-cpp-14.0.0/include   -DARROW_R_WITH_PARQUET -DARROW_R_WITH_DATASET -DARROW_R_WITH_ACERO -DARROW_R_WITH_SUBSTRAIT -DARROW_R_WITH_JSON -DARROW_R_WITH_S3 -I'/nix/store/icgvzqb9iimya88zh611qzbc91b6zxqk-r-cpp11-0.4.7/library/cpp11/include' -isystem /nix/store/ydfb1m5h1lcghpvs2hmv9686z008paij-libcxx-16.0.6-dev/include/c++/v1    -fPIC  -g -O2  -c type_infer.cpp -o type_infer.o
       > /nix/store/k687y4hiraslz65qz8pli1wb5wmcabvn-clang-wrapper-16.0.6/bin/c++ -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -L/nix/store/1hfs8ylpsyfrrakhyvskr4dgycd0l16c-R-4.3.2/lib/R/lib -L/nix/store/hi4fialjfb9wd2f5al4vpzlyh8dz38fz-libcxx-16.0.6/lib -o arrow.so RTasks.o altrep.o array.o array_to_vector.o arraydata.o arrowExports.o bridge.o buffer.o chunkedarray.o compression.o compute-exec.o compute.o config.o csv.o dataset.o datatype.o expression.o extension-impl.o feather.o field.o filesystem.o io.o json.o memorypool.o message.o parquet.o r_to_arrow.o recordbatch.o recordbatchreader.o recordbatchwriter.o safe-call-into-r-impl.o scalar.o schema.o symbols.o table.o threadpool.o type_infer.o -L/nix/store/a5yby7z43cngyy3m3h9hmrbswmpxqflx-arrow-cpp-14.0.0/lib -larrow_substrait -larrow_dataset -larrow_acero -lparquet -larrow -L/nix/store/1hfs8ylpsyfrrakhyvskr4dgycd0l16c-R-4.3.2/lib/R/lib -lR -lintl -Wl,-framework -Wl,CoreFoundation
       > ld: library not found for -lintl
       > clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
       > make: *** [/nix/store/1hfs8ylpsyfrrakhyvskr4dgycd0l16c-R-4.3.2/lib/R/share/make/shlib.mk:10: arrow.so] Error 1
       > ERROR: compilation failed for package 'arrow'
       > * removing '/nix/store/c6azanmwdk0mzx7xh5jsp47lv1mplsvd-r-arrow-14.0.0.2/library/arrow'
       For full logs, run 'nix log /nix/store/rm53v5qzndi2fspvi7i87ah540iq35m1-r-arrow-14.0.0.2.drv'.
```

**Comment by philipp-baumann** [comment]
on `x86_64-linux` `nix-build --pure -A rPackages.arrow` compiles successfully.

```sh
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (arrow)
installPhase completed in 2 minutes 29 seconds
Running phase: fixupPhase
shrinking RPATHs of ELF executables and libraries in /nix/store/1zs1933axj5xf3wwi60mfsv64c081ck3-r-arrow-14.0.0.2
shrinking /nix/store/1zs1933axj5xf3wwi60mfsv64c081ck3-r-arrow-14.0.0.2/library/arrow/libs/arrow.so
checking for references to /build/ in /nix/store/1zs1933axj5xf3wwi60mfsv64c081ck3-r-arrow-14.0.0.2...
patching script interpreter paths in /nix/store/1zs1933axj5xf3wwi60mfsv64c081ck3-r-arrow-14.0.0.2
/nix/store/1zs1933axj5xf3wwi60mfsv64c081ck3-r-arrow-14.0.0.2/library/arrow/build_arrow_static.sh: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/5l50g7kzj7v0rdhshld1vx46rf2k5lf9-bash-5.2p26/bin/bash"
rewriting symlink /nix/store/1zs1933axj5xf3wwi60mfsv64c081ck3-r-arrow-14.0.0.2/nix-support/propagated-user-env-packages to be relative to /nix/store/1zs1933axj5xf3wwi60mfsv64c081ck3-r-arrow-14.0.0.2
/nix/store/1zs1933axj5xf3wwi60mfsv64c081ck3-r-arrow-14.0.0.2
```

**Comment by b-rodrigues** [comment]
Tested on linux-aarch64 (rpi5), compiles and runs:

```
> arrow::arrow_info()
Arrow package version: 14.0.0.2

Capabilities:
               
acero      TRUE
dataset    TRUE
substrait  TRUE
parquet    TRUE
json       TRUE
s3         TRUE
gcs        TRUE
utf8proc   TRUE
re2        TRUE
snappy     TRUE
gzip       TRUE
brotli     TRUE
zstd       TRUE
lz4        TRUE
lz4_frame  TRUE
lzo       FALSE
bz2        TRUE
jemalloc   TRUE
mimalloc   TRUE

Memory:
                  
Allocator jemalloc
Current    0 bytes
Max        0 bytes

Runtime:
                        
SIMD Level          none
Detected SIMD Level none

Build:
                           
C++ Library Version  14.0.0
C++ Compiler            GNU
C++ Compiler Version 13.2.0
```

I like the approach you're going for, this way, the package and the cpp lib will never desync again. I was just wondering, do we need to all these changes in the `pkgs/development/r-modules/cran-packages.nix` file? That's really a lot.

**Comment by philipp-baumann** [comment]
> Tested on linux-aarch64 (rpi5), compiles and runs:
> 
> ```
> > arrow::arrow_info()
> Arrow package version: 14.0.0.2
> 
> Capabilities:
>                
> acero      TRUE
> dataset    TRUE
> substrait  TRUE
> parquet    TRUE
> json       TRUE
> s3         TRUE
> gcs        TRUE
> utf8proc   TRUE
> re2        TRUE
> snappy     TRUE
> gzip       TRUE
> brotli     TRUE
> zstd       TRUE
> lz4        TRUE
> lz4_frame  TRUE
> lzo       FALSE
> bz2        TRUE
> jemalloc   TRUE
> mimalloc   TRUE
> 
> Memory:
>                   
> Allocator jemalloc
> Current    0 bytes
> Max        0 bytes
> 
> Runtime:
>                         
> SIMD Level          none
> Detected SIMD Level none
> 
> Build:
>                            
> C++ Library Version  14.0.0
> C++ Compiler            GNU
> C++ Compiler Version 13.2.0
> ```
> 
> I like the approach you're going for, this way, the package and the cpp lib will never desync again. I was just wondering, do we need to all these changes in the `pkgs/development/r-modules/cran-packages.nix` file? That's really a lot.

thanks for testing. actually, valid point it's all the CRAN package updates, which is better handled by an upgrade process. However, since one does already the effort of fixing packages, wouldn't it make sense to allow for single package updates at https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/development/r-modules/generate-r-packages.R as an extension? For this PR, will get back to current master list of CRAN pkgs, and only update arrow.

**Comment by philipp-baumann** [comment]
closing i totally messed up the rebasing.

**Comment by Kupac** [comment]
> closing i totally messed up the rebasing.

I feel you. It brings back memories of my (very recent) first rebase.

**Pull request closed without merging**
