### PR TITLE
qtile: 0.10.4 -> 0.10.7

### PR DESCRIPTION
**Pull request by steveej**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by steveeJ** [comment]
/cc @kamilchm 

I've tried to adapt the patches to the new version, though there are still build errors left:

<details>
 <summary>Build Output</summary>

```
$ nix-build . -A qtile
these derivations will be built:
  /nix/store/xhwsqs95886livj1bx19d0cp6ss8zcd6-qtile-0.10.7.drv
building '/nix/store/xhwsqs95886livj1bx19d0cp6ss8zcd6-qtile-0.10.7.drv'...
unpacking sources
unpacking source archive /nix/store/iaw2gfsab16nba98q9wvv3w9789bb7yi-qtile
source root is qtile
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file qtile/tox.ini
patching sources
configuring
building
warning: no previously-included files found matching 'xcffib/_ffi.py'

Installed /tmp/nix-build-qtile-0.10.7.drv-0/qtile/.eggs/xcffib-0.5.1-py2.7.egg
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 170, in <module>
    **cffi_args
  File "/nix/store/a4zb290zkx8avpand4a58ndci8ppczik-python2.7-bootstrapped-pip-9.0.1/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/nix/store/87l8l9w3x8saxqz9sfcfw2i3jiilmxfi-python-2.7.14/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/nix/store/a4zb290zkx8avpand4a58ndci8ppczik-python2.7-bootstrapped-pip-9.0.1/lib/python2.7/site-packages/setuptools/dist.py", line 333, in __init__
    _Distribution.__init__(self, attrs)
  File "/nix/store/87l8l9w3x8saxqz9sfcfw2i3jiilmxfi-python-2.7.14/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/nix/store/a4zb290zkx8avpand4a58ndci8ppczik-python2.7-bootstrapped-pip-9.0.1/lib/python2.7/site-packages/setuptools/dist.py", line 476, in finalize_options
    ep.load()(self, ep.name, value)
  File "/nix/store/ibgvw4nhlvc0kpd88b789qbynhnjym5z-python2.7-cffi-1.11.4/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 193, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/nix/store/ibgvw4nhlvc0kpd88b789qbynhnjym5z-python2.7-cffi-1.11.4/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
    execfile(build_file_name, mod_vars)
  File "/nix/store/ibgvw4nhlvc0kpd88b789qbynhnjym5z-python2.7-cffi-1.11.4/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 25, in execfile
    exec(code, glob, glob)
  File "libqtile/ffi_build.py", line 25, in <module>
    from xcffib.ffi_build import ffi as xcffib_ffi
  File "/tmp/nix-build-qtile-0.10.7.drv-0/qtile/.eggs/xcffib-0.5.1-py2.7.egg/xcffib/__init__.py", line 34, in <module>
    lib = ffi.dlopen(soname)
OSError: cannot load library 'libxcb.so.1': libxcb.so.1: cannot open shared object file: No such file or directory
builder for '/nix/store/xhwsqs95886livj1bx19d0cp6ss8zcd6-qtile-0.10.7.drv' failed with exit code 1
error: build of '/nix/store/xhwsqs95886livj1bx19d0cp6ss8zcd6-qtile-0.10.7.drv' failed
```

</details>

**Comment by grahamc** [comment]
I introduced a failure in the evaluator today, sorry about that. Testing for a fix:

@GrahamcOfBorg eval

**Comment by steveeJ** [comment]
Thanks, but my build failure likely isn't related. Looks like qtile isn't built on the CI.

**Comment by steveeJ** [comment]
Thanks @adisbladis for jumping in with the xcffib bump. I've been running this successfully for a few hours now without encountering issues. Finally we have the power of the *Columns* layout :-)

**Comment by adisbladis** [comment]
Thanks! 👍

**Pull request merged**
