### PR TITLE
docker: 1.10.3 -> 1.12.1 on release 16.09

### PR DESCRIPTION
**Pull request by vdemeester**
###### Motivation for this change

> Docker we have is very old. This build is also much better as previous, it provides man files, has dependency clean-up and removes uneeded references to go compiler. I've tested this with and without nixos and works without any issues. It would be nice to have this merged in 16.09 @domenkozar 

/cc @offlinehacker 
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

docker: 1.10.3 -> 1.12.1

### CODE REVIEW

**Review by NeQuissimus — APPROVED** [review]
LGTM, considering it works fine on master, it should be good on 16.09

**Comment by FRidh** [comment]
please use `cherry-pick -x xxxx..yyyyy` so we get all the commits, as well as references to the original ones

**Comment by vdemeester** [comment]
@FRidh ah ok, wasn't sure about the best way to do it.. I'll update :wink:

**Comment by FRidh** [comment]
ok, pushed the commits myself

**Comment by FRidh** [comment]
for the next time :)

**Comment by vdemeester** [comment]
@FRidh ok :stuck_out_tongue_closed_eyes:

**Pull request closed without merging**
