### PR TITLE
spectre-meltdown-checker: 0.31 -> 0.32

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dotlambda** [comment]
cc @andir

**Comment by andir** [comment]
@grahamcofborg build spectre-meltdown-checker

**Comment by dotlambda** [comment]
Thanks!

**Comment by dtzWill** [comment]
It's showing vulnerable for variants 1 and 2, running latest unstable, with latest kernel.  Is this expected?

nix-info -m:
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.14, NixOS, 18.03pre125953.5402412b972 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.12dtz5869_f8d9aed`
 - channels(will): `"allvm, unstable-18.03pre125130.3a763b91963"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by dotlambda** [comment]
Yes it is.
According to https://www.phoronix.com/scan.php?page=news_item&px=Linux-4.9-4.14-Retpoline, the fixes should be available for the kernels available in Nixpkgs (>= 4.14.14 or >= 4.9.77)
But they need to be built with gcc >= 7.3, which is not yet available, according to https://www.phoronix.com/scan.php?page=news_item&px=GCC-7-Gets-Retpolines.

**Pull request merged**
