### PR TITLE
eclipses: 4.9 -> 4.10

### PR DESCRIPTION
**Pull request by rycee**
This applies to Eclipse platform, SDK, and the JDT plugin.

### CODE REVIEW

**Comment by samueldr** [comment]
Heads up, [this broke `nixpgks.tarball`](https://hydra.nixos.org/build/87689824) due to the missing i686-linux source, which isn't available upstream.

```
checking Nixpkgs on i686-linux
error: while querying the derivation named 'eclipse-platform-4.10':
while evaluating the attribute 'src' of the derivation 'eclipse-platform-4.10' at /build/source/pkgs/stdenv/generic/make-derivation.nix:185:11:
attribute 'i686-linux' missing, at /build/source/pkgs/applications/editors/eclipse/build-eclipse.nix:5:15
build time elapsed:  0m0.107s 0m0.127s 0m19.143s 0m2.722s
```

I do not know how to fix it properly; it looks like it would need to be fixed in `pkgs/applications/editors/eclipse/build-eclipse.nix` to *somehow* do the right thing when there's no source available.

**Comment by rycee** [comment]
Sorry, reverted in c076bd22338f1c31ee09fb8b4123407ee14337e8.

**Comment by jerith666** [comment]
it looks like eclipse stopped supporting 32-bit in 2018-12.  I'm working on redoing this with that in mind.

**Comment by jerith666** [comment]
See #55575 for my attempt.

**Pull request merged**
