### PR TITLE
openvpn-auth-ldap: 2.0.3+deb6.1 -> 2.0.4

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
ZHF: #122042

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

I didn't test whether this is actually functional.

cc @NixOS/nixos-release-managers

### CODE REVIEW

**Review by benley — APPROVED** [review]
Thank you for the update! I'm no longer using this package myself so I will trust that it actually works, given the successful build.

**Comment by risicle** [comment]
:blink: :blink: probably the last place I expected to see references to gnustep. Guess the author just really likes objc.

FWIW the one patch in the series that doesn't appear to have been included in 2.0.4 looks to be `openvpn_ldap_simpler_add_handler_4` - it's not as though it appears to be something security critical.

`nixpkgs-review` happy for me non-nixos linux x86_64.

**Comment by dotlambda** [comment]
> FWIW the one patch in the series that doesn't appear to have been included in 2.0.4 looks to be `openvpn_ldap_simpler_add_handler_4` - it's not as though it appears to be something security critical.

The patch no longer applies cleanly and I have no interest in maintaining it. So I would just leave it out.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 124698 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>1 package built:</summary>  <ul>    <li>openvpn-auth-ldap</li>  </ul></details>

**Pull request merged**
