### PR TITLE
soundtracker: 1.0.1 -> 1.0.2.1

### PR DESCRIPTION
**Pull request by fgaz**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by OPNA2608** [comment]
Result of `nixpkgs-review pr 127251` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>soundtracker</li>
  </ul>
</details>

---

<details>
  <summary>To fix the build on macOS:</summary>

```patch
@@ -1,7 +1,7 @@
 { lib, stdenv
 , fetchurl
 , pkg-config
-, autoconf
+, autoreconfHook
 , gtk2
 , alsa-lib
 , SDL
@@ -23,9 +23,30 @@ stdenv.mkDerivation rec {
     sha256 = "0nh0dwz8nldc040q6n06vlazhss8ms42r2dffhjcrqj3hbrvfx82";
   };

+  postPatch = lib.optionalString stdenv.hostPlatform.isDarwin ''
+    # Darwin binutils don't support D option for ar
+    # ALSA macros are missing on Darwin, causing error
+    substituteInPlace configure.ac \
+      --replace ARFLAGS=crD ARFLAGS=cru \
+      --replace AM_PATH_ALSA '#AM_PATH_ALSA'
+    # Avoid X11-specific workaround code on more than just Windows
+    substituteInPlace app/keys.c \
+      --replace '!defined(_WIN32)' '!defined(_WIN32) && !defined(__APPLE__)'
+    # "The application with bundle ID (null) is running setugid(), which is not allowed."
+    sed -i -e '/seteuid/d' -e '/setegid/d' app/main.c
+  '';
+
+  configureFlags = [
+    "--with-graphics-backend=gdk"
+  ] ++ lib.optionals stdenv.hostPlatform.isDarwin [
+    "--disable-alsa"
+  ];
+
+  enableParallelBuilding = true;
+
   nativeBuildInputs = [
     pkg-config
-    autoconf
+    autoreconfHook
   ];
   buildInputs = [
     gtk2
@@-49,7 +70,5 @@ stdenv.mkDerivation rec {
     license = licenses.gpl2Plus;
     maintainers = with maintainers; [ fgaz ];
     platforms = platforms.all;
-    # gdk/gdkx.h not found
-    broken = stdenv.isDarwin;
   };
 }
```

Screenshot_macOS_2021-06-17_22:12:35

</details>

**Comment by fgaz** [comment]
@OPNA2608 Thanks! Could you send that diff as a patch (or separate pr) so you can have attribution?

**Comment by OPNA2608** [comment]
Here you go: https://github.com/OPNA2608/nixpkgs/commit/50f14945e6028351638f6e037a5ad6dbfd937c07

**Comment by fgaz** [comment]
@OPNA2608 hmm, ofborg timed out...

**Comment by OPNA2608** [comment]
I can append a nixpkgs-review for Darwin when I'm back home.

Result of `nixpkgs-review pr 127251` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>soundtracker</li>
  </ul>
</details>

**Review by OPNA2608 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
@ofborg build soundtracker

**Comment by fgaz** [comment]
Still timing out... wasn't there an issue with osx sessions that made some builds stall?

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 127251` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>soundtracker</li>
  </ul>
</details>

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 127251` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>soundtracker</li>
  </ul>
</details>

**Comment by siraben** [comment]
Failed to build on macOS because of a failing pycairo test

**Comment by siraben** [comment]
I suggest waiting until the next staging cycle so this works immediately on master.

**Comment by lukegb** [comment]
Result of `nixpkgs-review pr 127251` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>soundtracker</li>
  </ul>
</details>

**Pull request merged**
