### PR TITLE
starsector: 0.96a-RC10 -> 0.97a-RC8

### PR DESCRIPTION
**Pull request by rafaelrc7**
During this update, due to a new version of Java, the software broke.
  On startup it crashed with the error: "Conflicting collector
  combinations in option list". This was due to mixing the default
  `-XX:+UseG1GC` and the `-XX:+UseConcMarkSweepGC -XX:+UseParNewGC` flags.
  I removed the latter flags, leaving the default garbage collector
  
  Furthermore, on succesful launch, the game wound warn about the
  `-XX:PermSize=192m -XX:MaxPermSize=192m` flags, that were removed in
  Java 8. Thus, those flags were also removed.
  
  The `substituteInPlace` deprecated `--replace` argument was also
  replaced by the new alternatives.

## Description of changes

Release notes of 0.97a-RC7: [https://fractalsoftworks.com/2024/02/02/starsector-0-97a-release/](https://fractalsoftworks.com/2024/02/02/starsector-0-97a-release/)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by rafaelrc7** [comment]
cc. @necauqua . 

You were the one that added those extra JVM flags, on PR #181422, of which two caused a conflict with the default enabled GC. I remove those new GC flags in favour of the default one. However, do you agree with this? Are those flags, in general, superior to G1GC? Your opinion would be really appreciated!

**Comment by necauqua** [comment]
I honestly don't remember the specifics, but those flags were more like a recommendation that I was using at the time, so it should be fine

The important bit is disabling bytecode verification :)

**Comment by rafaelrc7** [comment]
> I honestly don't remember the specifics, but those flags were more like a recommendation that I was using at the time, so it should be fine
> 
> The important bit is disabling bytecode verification :)

Ok, thanks for the quick answer! It might be worthed reviewing the remaining flags, to check if they are still relevant and if there are newer recommendations.

**Comment by rafaelrc7** [comment]
@head-gardener , you can review this PR, if you wish :)

**Comment by head-gardener** [comment]
lgtm, game runs fine

**Pull request merged**
