### PR TITLE
jetbrains: replace overrideDerivation with overrideAttr

### PR DESCRIPTION
**Pull request by raboof**
###### Motivation for this change

This fixes error-checking of function arguments (
https://nixos.org/manual/nixpkgs/stable/#sec-pkg-overrideDerivation),
notably checking the license (https://github.com/NixOS/nixpkgs/issues/107250)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by raboof** [comment]
the ofborg problem seems to be some uwsgi thing not related to this PR

**Comment by SuperSandro2000** [comment]
ping @raboof @edwtjo @lovek323

**Comment by raboof** [comment]
(I created this PR, so naturally I'm in favor ;) )

**Review by hugolgst — APPROVED** [review]
Code-wise it looks good to me

**Comment by SuperSandro2000** [comment]
> (I created this PR, so naturally I'm in favor ;) )

I was looking for another maintainer which can confirm that this works and does not break anything.

**Comment by raboof** [comment]
Result of `nixpkgs-review pr 107344` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Review by jonringer — APPROVED** [review]
LGTM

was able to build and launch clion.

**Pull request merged**
