### PR TITLE
python312Packages.lingua: enable tests and Python 3.12 support

### PR DESCRIPTION
**Pull request by fabaff**
## Description of changes
Issue detected in #281528

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by cole-h** [comment]
@ofborg eval

**Comment by fabaff** [comment]
This needs to go to `staging`...

**Comment by fabaff** [comment]
@ofborg build python312Packages.lingua python312Packages.mako python312Packages.holidays python311Packages.lingua python311Packages.mako

**Comment by mweinelt** [comment]
What is the state of this?

**Comment by mweinelt** [comment]
```
holidays> Traceback (most recent call last):
holidays>   File "/build/source/./scripts/l10n/generate_po_files.py", line 125, in <module>
holidays>     POGenerator.run()
holidays>   File "/build/source/./scripts/l10n/generate_po_files.py", line 121, in run
holidays>     POGenerator().process_countries()
holidays>   File "/build/source/./scripts/l10n/generate_po_files.py", line 77, in process_countries
holidays>     create_pot_file(
holidays>   File "/nix/store/b64rfm70j5s8mqbqr8rkwk87rfvyvnc0-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
holidays>     return self.main(*args, **kwargs)
holidays>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
holidays>   File "/nix/store/b64rfm70j5s8mqbqr8rkwk87rfvyvnc0-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1078, in main
holidays>     rv = self.invoke(ctx)
holidays>          ^^^^^^^^^^^^^^^^
holidays>   File "/nix/store/b64rfm70j5s8mqbqr8rkwk87rfvyvnc0-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
holidays>     return ctx.invoke(self.callback, **ctx.params)
holidays>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
holidays>   File "/nix/store/b64rfm70j5s8mqbqr8rkwk87rfvyvnc0-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 783, in invoke
holidays>     return __callback(*args, **kwargs)
holidays>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
holidays>   File "/nix/store/5ndchzq44rr2mb0p6a4mgik1vchcvqvs-python3.11-lingua-4.15.0/lib/python3.11/site-packages/lingua/extract.py", line 388, in main
holidays>     register_extractors()
holidays>   File "/nix/store/5ndchzq44rr2mb0p6a4mgik1vchcvqvs-python3.11-lingua-4.15.0/lib/python3.11/site-packages/lingua/extractors/__init__.py", line 169, in register_extractors
holidays>     for entry_point in entry_points("lingua.extractors"):
holidays>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
holidays> TypeError: entry_points() takes 0 positional arguments but 1 was given
```

**Pull request closed without merging**
