### PR TITLE
kubernetes: fix interpolation error and move services to own target

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

The first commit is a straight up fix for a bug where enabling the cni network
plugin will make evaluation fail.

The second part shifts the kubernetes services into their own slice and makes
the launch happen via a dedicated kubernetes target.

The reason for moving into its own slice and target is that it makes starting
and stopping far easier plus it allows for resource allocations.

Cc: @offlinehacker

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by offlinehacker** [comment]
Thanks!

**Comment by offlinehacker** [comment]
Why did you need toString? imap nethod should always return numbers.

**Comment by peterhoeg** [comment]
> Why did you need toString? imap nethod should always return numbers.

Because ```10+i``` isn't being interpolated automatically inside the string.

**Comment by offlinehacker** [comment]
ah yes, of course, tnx

**Pull request merged**
