### PR TITLE
r-modules: cran and bioc package bump

### PR DESCRIPTION
**Pull request by PhDyellow**
###### Motivation for this change

I was working on a fix for the BIOC package sets anyway (#127790), and wanted to test it. 

###### Things done
Bumping the CRAN and BIOC package sets.

Remove the following packages from `default.nix` that were removed from CRAN or BIOC 
- `BayesXsrc`
- `EasyqpcR
- `OligoSpecificitySystem`
- `dpa`

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 137751` at fc2701c1 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python38Packages.cnvkit</li>
    <li>python39Packages.cnvkit</li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.rpy2</li>
    <li>python39Packages.rpy2</li>
  </ul>
</details>

**Review by jbedo — CHANGES_REQUESTED** [review]
Looks good, just squash everything down to one commit

**Comment by PhDyellow** [comment]
Squashed

**Comment by jbedo** [comment]
So sorry, for some reason I missed the notification of your update. I've now got the broken marking working and a newer package set bump over here: #139609. Would you be ok with closing this in favour of that PR?

On a related note, do you have a particular update frequency you would find most useful?

**Comment by jbedo** [comment]
Merged #139609 in favour of this bump.

**Comment by PhDyellow** [comment]
Sorry, I've been out of internet range for a little while.

No problem about dropping this PR in favour of a newer package set. 

Regarding package bump frequency, monthly is fine for my purposes. I use Nix to pin the package set for projects, rather than get bleeding edge CRAN packages. When the package set was getting to around 3 months old, I was starting to notice new features in packages that I couldn't get in Nix yet, so I made overlays. The overlays were useful for Github packages too, but that's another PR : )  

Updates that are more frequent than monthly won't hurt if they are automated, but I wouldn't want to spend human time fetching them or fixing broken packages. I also don't know how Nixpkgs handles automatic PRs to bump package sets, I get the impression it would be discouraged.

**Pull request closed without merging**
