### PR TITLE
python310Packages.jupytext: 1.14.1 -> 1.15.0

### PR DESCRIPTION
**Pull request by natsukium**
## Description of changes

Diff: https://github.com/mwouts/jupytext/compare/refs/tags/v1.14.1...v1.15.0

Changelog: https://github.com/mwouts/jupytext/releases/tag/refs/tags/v1.15.0

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by natsukium** [comment]
Result of `nixpkgs-review` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>python310Packages.jupytext</li>
    <li>python310Packages.jupytext.dist</li>
    <li>python310Packages.mkdocs-jupyter</li>
    <li>python310Packages.mkdocs-jupyter.dist</li>
    <li>python311Packages.jupytext</li>
    <li>python311Packages.jupytext.dist</li>
    <li>python311Packages.mkdocs-jupyter</li>
    <li>python311Packages.mkdocs-jupyter.dist</li>
  </ul>
</details>

**Comment by timokau** [comment]
Thank you! The aarch64 build is failing. Do you have an idea on how to fix that? Otherwise we might just exclude the platform for now.

Are you interested in taking over maintenance of the package? I have been neglecting it a bit since I do not use it anymore. If you're interested, please replace me in the maintainers list.

**Comment by natsukium** [comment]
Thanks for checking!

The dependent jupyter-server-field seems to fail. I was able to build jupytext itself locally.

> Are you interested in taking over maintenance of the package? I have been neglecting it a bit since I do not use it anymore. If you're interested, please replace me in the maintainers list.

OK, I have recently started a jupyter team, and I'm going to change the maintainer.

**Review by tjni — APPROVED** [review]
I reviewed the change and looked through the changelog. This LGTM.

**Review by timokau — APPROVED** [review]
Thank you!

**Pull request merged**
