### PR TITLE
staging-next 2022-10-13

### PR DESCRIPTION
**Pull request by mweinelt**
- workflow docs: https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/193494

### CODE REVIEW

**Comment by oxalica** [comment]
`systemd` build is fragile because of https://github.com/mesonbuild/meson/issues/10919

**Comment by yu-re-ka** [comment]
> `systemd` build is fragile because of [mesonbuild/meson#10919](https://github.com/mesonbuild/meson/issues/10919)

Oooooh this explains something I ran into

**Comment by vcunat** [comment]
systemd: for now I'd suggest PR https://github.com/NixOS/nixpkgs/pull/195934

**Comment by mweinelt** [comment]
- [ ] [rustc 1.64.0](https://hydra.nixos.org/build/195608754) fails to build on x86_64-darwin @zowoq @alyssais

**Comment by r-burns** [comment]
The cc-wrapper arg deduplication seems to have broken netcat-openbsd on x86_64-linux, bisected failure to 0bea4a194f7103fcedc0226a74e50657875a7c4d

**Comment by r-burns** [comment]
0bea4a194f7103fcedc0226a74e50657875a7c4d also broke iortcw

**Comment by vcunat** [comment]
I'm not aware of anything really blocking this PR. (Perhaps wait a while to finish almost all the builds.)  Comparisons:
- 3 platforms: https://hydra.nixos.org/eval/1783854?compare=1783856
- `aarch64-darwin`: https://hydra.nixos.org/eval/1783854?compare=1783841
We have significantly more newly succeeding than newly failing builds, at least numerically right now.  I hope it's not just because I've done multiple of restart-failed steps due to some transient errors.

**Pull request merged**
