### PR TITLE
vim-utils: include man pages in the output of vim_customizable.customize, add option to include gvim wrapper

### LINKED ISSUE #24691: installing `vim_configurable.customize{...}` doesn't make vim's manpage available
## Issue description

The wrapper only has `.../bin/vim`, so the corresponding `.../share/man/...` where `man` would check for manpages is absent.

### Steps to reproduce

* don't have regular vim installed
* install something like `vim_configurable.customize{name="vim"; vimrcConfig={};}`
* `man vim`

## Technical details

17.09pre104936.b0d07aa894

### PR DESCRIPTION
**Pull request by therealpxc**
###### Motivation for this change
fixes #24691

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by edanaher** [comment]
Looks reasonable to me; my only question is whether there should be a separate flag for giving the gvim wrapper its own name (rather than `g${name}`).  But I can definitely understand wanting to leave that out for now, especially given that previously gvim was completely unavailable, and apparently there weren't any complaints about that...

**Comment by nicknovitski** [comment]
I have no objections, this clearly improves things.

**Comment by therealpxc** [comment]
What if we also want to wrap vimtutor and other `${vim}/bin` outputs? Does anyone have a proposition for a more general solution? Then I could address the configurability issue for gvim's name separately.

**Comment by Mic92** [comment]
Do you want to change other things in this pull request?

**Comment by xeji** [comment]
Superseded by #56277, closing

**Comment by ncfavier** [comment]
> What if we also want to wrap vimtutor and other `${vim}/bin` outputs? Does anyone have a proposition for a more general solution? Then we could address the configurability issue for gvim's name in the same stroke.

Proposed solution to this in https://github.com/NixOS/nixpkgs/pull/164994

**Pull request closed without merging**
