### PR TITLE
Pgadmin 6.11

### PR DESCRIPTION
**Pull request by gador**
###### Description of changes

Update pgadmin4 to 6.11.

[Release Notes](https://www.pgadmin.org/docs/pgadmin4/latest/release_notes_6_11.html)

Noteworthy changes: `Added capability to deploy PostgreSQL servers on Microsoft Azure.`

Also, since the update of postgresql from 14.3 -> 14.4 one of the regression sql test fails for pgadmin. This is unrelated to this update. A bugreport has been filed [upstream](https://redmine.postgresql.org/issues/7527) and meanwhile the test is skipped for now. AFAIK, this should not impact any performance or functionality.

This PR also includes the fix of the hash of `ua-parser` from my PR #179865. `pgadmin4` depends on it and will not build otherwise.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
Please rebase

**Comment by gador** [comment]
@dotlambda rebased :+1:

**Comment by symphorien** [comment]
Maybe I'm holding it wrong but the test fails to evaluate:
```
[nix-shell:~/.cache/nixpkgs-review/pr-179994]$ nix-build nixpkgs/nixos/tests/pgadmin4.nix
error: value is a list while a set was expected

       at /home/symphorien/.cache/nixpkgs-review/pr-179994/nixpkgs/nixos/tests/pgadmin4.nix:49:15:

           48|               # test suite package requirements
           49|               pythonPackages.testscenarios
             |               ^
           50|               pythonPackages.selenium
(use '--show-trace' to show detailed location information)
```

**Comment by gador** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 179994` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>pgadmin4</li>
</ul>
</details>

**Comment by symphorien** [comment]
thank you for your explanation

**Pull request merged**
