### PR TITLE
Just: 1.26.0 -> 1.28.0

### PR DESCRIPTION
**Pull request by vlaci**
## Description of changes

Release notes: https://github.com/casey/just/releases/tag/1.27.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by marcusramberg** [comment]
Result of `nixpkgs-review pr 316156` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>aba</li>
    <li>kabeljau</li>
  </ul>
</details>
<details>
  <summary>92 packages built:</summary>
  <ul>
    <li>catppuccin-cursors</li>
    <li>catppuccin-cursors.frappeBlue</li>
    <li>catppuccin-cursors.frappeDark</li>
    <li>catppuccin-cursors.frappeFlamingo</li>
    <li>catppuccin-cursors.frappeGreen</li>
    <li>catppuccin-cursors.frappeLavender</li>
    <li>catppuccin-cursors.frappeLight</li>
    <li>catppuccin-cursors.frappeMaroon</li>
    <li>catppuccin-cursors.frappeMauve</li>
    <li>catppuccin-cursors.frappePeach</li>
    <li>catppuccin-cursors.frappePink</li>
    <li>catppuccin-cursors.frappeRed</li>
    <li>catppuccin-cursors.frappeRosewater</li>
    <li>catppuccin-cursors.frappeSapphire</li>
    <li>catppuccin-cursors.frappeSky</li>
    <li>catppuccin-cursors.frappeTeal</li>
    <li>catppuccin-cursors.frappeYellow</li>
    <li>catppuccin-cursors.latteBlue</li>
    <li>catppuccin-cursors.latteDark</li>
    <li>catppuccin-cursors.latteFlamingo</li>
    <li>catppuccin-cursors.latteGreen</li>
    <li>catppuccin-cursors.latteLavender</li>
    <li>catppuccin-cursors.latteLight</li>
    <li>catppuccin-cursors.latteMaroon</li>
    <li>catppuccin-cursors.latteMauve</li>
    <li>catppuccin-cursors.lattePeach</li>
    <li>catppuccin-cursors.lattePink</li>
    <li>catppuccin-cursors.latteRed</li>
    <li>catppuccin-cursors.latteRosewater</li>
    <li>catppuccin-cursors.latteSapphire</li>
    <li>catppuccin-cursors.latteSky</li>
    <li>catppuccin-cursors.latteTeal</li>
    <li>catppuccin-cursors.latteYellow</li>
    <li>catppuccin-cursors.macchiatoBlue</li>
    <li>catppuccin-cursors.macchiatoDark</li>
    <li>catppuccin-cursors.macchiatoFlamingo</li>
    <li>catppuccin-cursors.macchiatoGreen</li>
    <li>catppuccin-cursors.macchiatoLavender</li>
    <li>catppuccin-cursors.macchiatoLight</li>
    <li>catppuccin-cursors.macchiatoMaroon</li>
    <li>catppuccin-cursors.macchiatoMauve</li>
    <li>catppuccin-cursors.macchiatoPeach</li>
    <li>catppuccin-cursors.macchiatoPink</li>
    <li>catppuccin-cursors.macchiatoRed</li>
    <li>catppuccin-cursors.macchiatoRosewater</li>
    <li>catppuccin-cursors.macchiatoSapphire</li>
    <li>catppuccin-cursors.macchiatoSky</li>
    <li>catppuccin-cursors.macchiatoTeal</li>
    <li>catppuccin-cursors.macchiatoYellow</li>
    <li>catppuccin-cursors.mochaBlue</li>
    <li>catppuccin-cursors.mochaDark</li>
    <li>catppuccin-cursors.mochaFlamingo</li>
    <li>catppuccin-cursors.mochaGreen</li>
    <li>catppuccin-cursors.mochaLavender</li>
    <li>catppuccin-cursors.mochaLight</li>
    <li>catppuccin-cursors.mochaMaroon</li>
    <li>catppuccin-cursors.mochaMauve</li>
    <li>catppuccin-cursors.mochaPeach</li>
    <li>catppuccin-cursors.mochaPink</li>
    <li>catppuccin-cursors.mochaRed</li>
    <li>catppuccin-cursors.mochaRosewater</li>
    <li>catppuccin-cursors.mochaSapphire</li>
    <li>catppuccin-cursors.mochaSky</li>
    <li>catppuccin-cursors.mochaTeal</li>
    <li>catppuccin-cursors.mochaYellow</li>
    <li>catppuccin-sddm</li>
    <li>celeste</li>
    <li>cosmic-applets</li>
    <li>cosmic-applibrary</li>
    <li>cosmic-bg</li>
    <li>cosmic-design-demo</li>
    <li>cosmic-edit</li>
    <li>cosmic-files</li>
    <li>cosmic-greeter</li>
    <li>cosmic-icons</li>
    <li>cosmic-launcher</li>
    <li>cosmic-notifications</li>
    <li>cosmic-panel</li>
    <li>cosmic-randr</li>
    <li>cosmic-screenshot</li>
    <li>cosmic-session</li>
    <li>cosmic-settings</li>
    <li>cosmic-store</li>
    <li>cosmic-term</li>
    <li>dogdns</li>
    <li>dogdns.man</li>
    <li>find-billy</li>
    <li>just</li>
    <li>just.doc</li>
    <li>just.man</li>
    <li>ssh-openpgp-auth</li>
    <li>sshd-openpgp-auth</li>
  </ul>
</details>

**Comment by marcusramberg** [comment]
The two failures seem related to the just cache, not sure if new or known

```
       > install flags: PREFIX=/nix/store/k5sn9r08zwhfzdglkb6h5k8dawg9lzmk-aba-0.8.0 MANIFEST_OPTS=--frozen\ --locked\ --profile=release INSTALL_OPTS=--no-track install
       > cargo build  --frozen --locked --profile=release
       >     Finished release [optimized] target(s) in 0.15s
       > cargo install --no-track --frozen --locked --profile=release --root "/nix/store/k5sn9r08zwhfzdglkb6h5k8dawg9lzmk-aba-0.8.0" --path .
       >   Installing aba v0.8.0 (/build/source)
       >     Finished release [optimized] target(s) in 0.22s
       >   Installing /nix/store/k5sn9r08zwhfzdglkb6h5k8dawg9lzmk-aba-0.8.0/bin/aba
       >    Installed package `aba v0.8.0 (/build/source)` (executable `aba`)
       > warning: be sure to add `/nix/store/k5sn9r08zwhfzdglkb6h5k8dawg9lzmk-aba-0.8.0/bin` to your PATH to be able to run the installed binaries
       > error: I/O error in cache dir `/homeless-shelter/.cache/just`: Permission denied (os error 13)
       For full logs, run 'nix log /nix/store/bbif83z14sdj4vhs6c4qxpa9p7gpx7yf-aba-0.8.0.drv'.
```

**Comment by vlaci** [comment]
> The two failures seem related to the just cache, not sure if new or known
> 
> ```
>        > install flags: PREFIX=/nix/store/k5sn9r08zwhfzdglkb6h5k8dawg9lzmk-aba-0.8.0 MANIFEST_OPTS=--frozen\ --locked\ --profile=release INSTALL_OPTS=--no-track install
>        > cargo build  --frozen --locked --profile=release
>        >     Finished release [optimized] target(s) in 0.15s
>        > cargo install --no-track --frozen --locked --profile=release --root "/nix/store/k5sn9r08zwhfzdglkb6h5k8dawg9lzmk-aba-0.8.0" --path .
>        >   Installing aba v0.8.0 (/build/source)
>        >     Finished release [optimized] target(s) in 0.22s
>        >   Installing /nix/store/k5sn9r08zwhfzdglkb6h5k8dawg9lzmk-aba-0.8.0/bin/aba
>        >    Installed package `aba v0.8.0 (/build/source)` (executable `aba`)
>        > warning: be sure to add `/nix/store/k5sn9r08zwhfzdglkb6h5k8dawg9lzmk-aba-0.8.0/bin` to your PATH to be able to run the installed binaries
>        > error: I/O error in cache dir `/homeless-shelter/.cache/just`: Permission denied (os error 13)
>        For full logs, run 'nix log /nix/store/bbif83z14sdj4vhs6c4qxpa9p7gpx7yf-aba-0.8.0.drv'.
> ```

Ohh, so the tmpdir to cache dir change is not limited to tests, good to know.

I don't know what's the best action here:
- Add `XDG_CACHE_HOME` variable to affected packages.
- Somhow convince just to fall back to using a regular tmpdir on permission issues. This would be nice if it could be upstreamed, but I am unsure how probable is that `~/.cache` is not writable.
- Revert the patch introducing this change.

**Comment by vlaci** [comment]
Created an issue upstream
https://github.com/casey/just/issues/2123

**Comment by vlaci** [comment]
The new `completions::bash` test fails.
```

**Comment by vlaci** [comment]
Result of nixpkgs-review:

```
94 packages built:
aba catppuccin-cursors catppuccin-cursors.frappeBlue catppuccin-cursors.frappeDark catppuccin-cursors.frappeFlamingo catppuccin-cursors.frappeGreen catppuccin-cursors.frappeLavender catppuccin-cursors.frappeLight catppuccin-cursors.frappeMaroon catppuccin-cursors.frappeMauve catppuccin-cursors.frappePeach catppuccin-cursors.frappePink catppuccin-cursors.frappeRed catppuccin-cursors.frappeRosewater catppuccin-cursors.frappeSapphire catppuccin-cursors.frappeSky catppuccin-cursors.frappeTeal catppuccin-cursors.frappeYellow catppuccin-cursors.latteBlue catppuccin-cursors.latteDark catppuccin-cursors.latteFlamingo catppuccin-cursors.latteGreen catppuccin-cursors.latteLavender catppuccin-cursors.latteLight catppuccin-cursors.latteMaroon catppuccin-cursors.latteMauve catppuccin-cursors.lattePeach catppuccin-cursors.lattePink catppuccin-cursors.latteRed catppuccin-cursors.latteRosewater catppuccin-cursors.latteSapphire catppuccin-cursors.latteSky catppuccin-cursors.latteTeal catppuccin-cursors.latteYellow catppuccin-cursors.macchiatoBlue catppuccin-cursors.macchiatoDark catppuccin-cursors.macchiatoFlamingo catppuccin-cursors.macchiatoGreen catppuccin-cursors.macchiatoLavender catppuccin-cursors.macchiatoLight catppuccin-cursors.macchiatoMaroon catppuccin-cursors.macchiatoMauve catppuccin-cursors.macchiatoPeach catppuccin-cursors.macchiatoPink catppuccin-cursors.macchiatoRed catppuccin-cursors.macchiatoRosewater catppuccin-cursors.macchiatoSapphire catppuccin-cursors.macchiatoSky catppuccin-cursors.macchiatoTeal catppuccin-cursors.macchiatoYellow catppuccin-cursors.mochaBlue catppuccin-cursors.mochaDark catppuccin-cursors.mochaFlamingo catppuccin-cursors.mochaGreen catppuccin-cursors.mochaLavender catppuccin-cursors.mochaLight catppuccin-cursors.mochaMaroon catppuccin-cursors.mochaMauve catppuccin-cursors.mochaPeach catppuccin-cursors.mochaPink catppuccin-cursors.mochaRed catppuccin-cursors.mochaRosewater catppuccin-cursors.mochaSapphire catppuccin-cursors.mochaSky catppuccin-cursors.mochaTeal catppuccin-cursors.mochaYellow catppuccin-sddm celeste cosmic-applets cosmic-applibrary cosmic-bg cosmic-design-demo cosmic-edit cosmic-files cosmic-greeter cosmic-icons cosmic-launcher cosmic-notifications cosmic-panel cosmic-randr cosmic-screenshot cosmic-session cosmic-settings cosmic-store cosmic-term dogdns dogdns.man find-billy just just.doc just.man kabeljau ssh-openpgp-auth sshd-openpgp-auth
```

**Pull request merged**
