### PR TITLE
Update gup and rename gfxmonk -> timbertson

### PR DESCRIPTION
**Pull request by nckx**
I switched from `fetchgit` to `fetchFromGitHub`, since all gup releases seem to be properly (and consistently) tagged and it removes the need to match hashes to version numbers.

@timbertson: what do you think?

### CODE REVIEW

**Comment by zimbatm** [comment]
LGTM

**Comment by nckx** [comment]
Thanks :)

I'd normally not bother with a PR for the bump, but @timbertson is also the gup upstream & might be using some kind of script/workflow that this would break.

If that's the case, I'd prefer to see less such generated code in nixpkgs. If not, there shouldn't be a reason to map releases to git hashes. We'll see...

**Comment by zimbatm** [comment]
I'm not sure of what generated code you're talking about, except the version and sha256 the rest shouldn't change no ?

**Comment by nckx** [comment]
Hence why I prefer a comment from the author.

If they use a raw git revision instead of the release tag/tarball (created by the same person), it might be for good reason... or it might be because they blindly `sed`-script updates every second Tuesday... or they didn't know they could fetch tags. The only way to know is ask.

Anyway, you're right that this shouldn't break anything.

**Comment by timbertson** [comment]
Hi! I mostly use raw git fetching in my nix expressions from force of habit - because sometimes I like to fetch non-release commits or fetch from non-github locations during development. I shouldn't need to do that here though since it's in nixpkgs proper, it should only be dealing with released versions.

@nckx I actually tried to reduce duplication of this package by doing a `callPackage "${source}/nix" { ...}` to use the upstream nix expression directly, but it broke nix's builds when trying to get a list of packages without actually building anything. I'd still like to achieve that, if you have any ideas. It's a bit of a pain that I have to duplicate gup's nix expression in both gup and nixpkgs.

**Pull request merged**
