### PR TITLE
transmission: Configurable download directory permissions

### PR DESCRIPTION
**Pull request by dsg22**
The ExecStartPre script previously ran a 'chmod 770' on all directories,
including complete and incomplete download directories. Change this
so it only ensures user and group rights, but don't touch world
permissions.

###### Motivation for this change
I would like to access my torrent complete folder (stored on NFS) from other sources. I have correct permissions set there, but on every start of the transmission service it resets the permissions to 770.

See also issue #55161

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @astsmtl @vcunat @wizeman

### CODE REVIEW

**Comment by wizeman** [comment]
Hmm, this probably merits some discussion.

I had a similar problem as you. In my case I wanted to make sure that both the `download-dir` and `incomplete-dir` were readable by others over NFS. However, when I was looking into this I have also locally modified the `transmission` service to set the `homeDir` and `settingsDir` permissions to `700` (not readable by the transmission group nor by others), as I didn't see a need for anything more permissive. The latter works perfectly fine for me.

If there's a need for different permissions on different machines, perhaps they should be configurable?
I'd be happy to get rid of my local modifications.

**Comment by dsg22** [comment]
Good points. Indeed, 700 should be enough. I also agree that making the permissions for download-dir and incomplete-dir configurable would be better.

I'll have another go at this and update the PR later.

**Comment by dsg22** [comment]
I've reworked this to add a new option downloadDirPermissions which gets applied to download-dir and incomplete-dir. It defaults to 770 like the old code. I think that's a bad default, but I'd also like to avoid a package update changing people's torrent directory permissions. I'd like to hear others thoughts on this.

This patch also makes homeDir and settingsDir 700 (non-configurable). I don't expect this will affect anyone.

**Review by Lassulus — APPROVED** [review]
LGTM, I have similiar issues currently with my transmission setup

**Comment by chreekat** [comment]
fyi, this change made the transmission service unusable with default settings.

1. The download dir is a subdir of the home dir
1. The home dir is 0700
1. Therefore, nobody except the owner can traverse to the download dir

I have to also echo #55161 - why do the directories get their permissions set *on every load of the service*?

**Comment by Lassulus** [comment]
hmm, this is indeed not very practical, I will have to fix that, thanks for pointing that out.

I guess we could add a check if the directory already exists and chmod it only then or do it in an activationScript.

**Comment by dsg22** [comment]
There are already two pull requests open to fix the issue caused by this PR:
https://github.com/NixOS/nixpkgs/pull/76552
https://github.com/NixOS/nixpkgs/pull/78113

I agree though that setting perms on every start is suboptimal.

**Comment by bb2020** [comment]
Can't we just merge https://github.com/bb2020/nixpkgs/commit/3625af9def7049956ac1a09ecf7b42369dcaedb9 that I've mentioned in https://github.com/NixOS/nixpkgs/pull/76552.
It should fix all transmission related issues.

**Comment by Lassulus** [comment]
@bb2020 ah, this looks good, is there a PR open for that?

**Comment by bb2020** [comment]
Created one just now.

**Pull request merged**
