### PR TITLE
osu-lazer: 2022.205.0 -> 2022.409.0

### PR DESCRIPTION
**Pull request by izik1**
###### Description of changes

There's been a lot of intervening updates, but this one is: https://github.com/ppy/osu/releases/tag/2022.409.0

and a link to the commit range: https://github.com/ppy/osu/compare/2022.205.0...2022.409.0

Had to update to dotnet-sdk-6 and dotnet-runtime-6 (which is why @r-ryantm didn't get it)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

If there's anything I missed please let me know and I'll fix it.

### CODE REVIEW

**Comment by JCapucho** [comment]
Result of `nixpkgs-review pr 167961` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>osu-lazer</li>
  </ul>
</details>

**Comment by JCapucho** [comment]
A new version has been released since https://github.com/ppy/osu/releases/tag/2022.409.0

**Comment by izik1** [comment]
> A new version has been released since https://github.com/ppy/osu/releases/tag/2022.409.0

I could bump to the newer version, (in fact, I just did it locally). I'm not sure what the protocol for "a new version released while you were updating" is. Should add a new commit? Amend my previous one? Should I open a new PR? Update this one's title? Leave the PR alone? My gut says leave the PR alone and just add an additional commit, I'd just like to be sure that is what's expected.

**Comment by ryantm** [comment]
@izik1 Probably you can find evidence of people doing it every way you suggest, but my suggestion would be to do make your updates, squash it down to one commit and force push and update the name of the PR.

**Comment by JCapucho** [comment]
Result of `nixpkgs-review pr 167961` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>osu-lazer</li>
  </ul>
</details>

**Review by oxalica — APPROVED** [review]
Builds and works well.

**Pull request merged**
