### PR TITLE
bcachefs-tools: 1.7.0-unstable-2024-05-09 -> 1.9.2

### LINKED ISSUE #321049: Update request: bcachefs-tools 1.7.0-unstable-2024-05-09 → 1.9.1
- Package name: bcachefs-tools
- Latest released version: 1.9.1

- Current version on the unstable channel: 1.7.0-unstable-2024-05-09
- Current version on the stable/release channel: 1.7.0-unstable-2024-05-09

- [ ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@Madouura @JohnRTitor @davidak 

-----

Note for maintainers: Please tag this issue in your PR.

https://github.com/koverstreet/bcachefs-tools/releases/tag/v1.9.0

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by JohnRTitor**
## Description of changes

- Closes #321049
- Remove patches that are merged upstream

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by tmuehlbacher** [comment]
Thanks, but please pause this for a bit, the v1.9.0 tag is a bit messy. The `nixpkgs#nixosTests.bcachefs` test fails with this.

**Comment by JohnRTitor** [comment]
Indeed the test fails, here's the log for reference

<details>

<code>
(finished: must succeed: echo password | bcachefs unlock -k session /dev/vdb1, in 0.70 seconds)
machine: must succeed: echo password | mount -t bcachefs /dev/vdb1:/dev/vdb2 /tmp/mnt
machine # [    6.710377] dhcpcd[664]: eth0: Router Advertisement from fe80::2
machine # [    6.710950] dhcpcd[664]: eth0: adding address fec0::5054:ff:fe12:3456/64
machine # [    6.712111] dhcpcd[664]: eth0: adding route to fec0::/64
machine # [    6.712579] dhcpcd[664]: eth0: adding default route via fe80::2
machine: output: ERROR - bcachefs::commands::mount: Fatal error: failed to verify passphrase

cleanup
kill machine (pid 9)
qemu-kvm: terminating on signal 15 from pid 6 (/nix/store/6b1fqdwb3g56j5pazv8zkx9qd0mv3wiz-python3-3.11.9/bin/python3.11)
(finished: cleanup, in 0.02 seconds)
Traceback (most recent call last):
  File "/nix/store/s4mmd0j5griaizximy55wdc75gpqiihi-nixos-test-driver-1.1/bin/.nixos-test-driver-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/s4mmd0j5griaizximy55wdc75gpqiihi-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/__init__.py", line 146, in main
    driver.run_tests()
  File "/nix/store/s4mmd0j5griaizximy55wdc75gpqiihi-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/driver.py", line 166, in run_tests
    self.test_script()
  File "/nix/store/s4mmd0j5griaizximy55wdc75gpqiihi-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/driver.py", line 158, in test_script
    exec(self.tests, symbols, None)
  File "<string>", line 5, in <module>
  File "/nix/store/s4mmd0j5griaizximy55wdc75gpqiihi-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 611, in succeed
    raise Exception(f"command `{command}` failed (exit code {status})")
Exception: command `echo password | mount -t bcachefs /dev/vdb1:/dev/vdb2 /tmp/mnt` failed (exit code 1)
kill vlan (pid 7)
error: builder for '/nix/store/r9qfv8c94ca52iyx51v99jwd9kl19lc9-vm-test-run-bcachefs.drv' failed with exit code 1;
       last 25 log lines:
       > machine # [    6.710377] dhcpcd[664]: eth0: Router Advertisement from fe80::2
       > machine # [    6.710950] dhcpcd[664]: eth0: adding address fec0::5054:ff:fe12:3456/64
       > machine # [    6.712111] dhcpcd[664]: eth0: adding route to fec0::/64
       > machine # [    6.712579] dhcpcd[664]: eth0: adding default route via fe80::2
       > machine: output: ERROR - bcachefs::commands::mount: Fatal error: failed to verify passphrase
       >
       > cleanup
       > kill machine (pid 9)
       > qemu-kvm: terminating on signal 15 from pid 6 (/nix/store/6b1fqdwb3g56j5pazv8zkx9qd0mv3wiz-python3-3.11.9/bin/python3.11)
       > (finished: cleanup, in 0.02 seconds)
       > Traceback (most recent call last):
       >   File "/nix/store/s4mmd0j5griaizximy55wdc75gpqiihi-nixos-test-driver-1.1/bin/.nixos-test-driver-wrapped", line 9, in <module>
       >     sys.exit(main())
       >              ^^^^^^
       >   File "/nix/store/s4mmd0j5griaizximy55wdc75gpqiihi-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/__init__.py", line 146, in main
       >     driver.run_tests()
       >   File "/nix/store/s4mmd0j5griaizximy55wdc75gpqiihi-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/driver.py", line 166, in run_tests
       >     self.test_script()
       >   File "/nix/store/s4mmd0j5griaizximy55wdc75gpqiihi-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/driver.py", line 158, in test_script
       >     exec(self.tests, symbols, None)
       >   File "<string>", line 5, in <module>
       >   File "/nix/store/s4mmd0j5griaizximy55wdc75gpqiihi-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 611, in succeed
       >     raise Exception(f"command `{command}` failed (exit code {status})")
       > Exception: command `echo password | mount -t bcachefs /dev/vdb1:/dev/vdb2 /tmp/mnt` failed (exit code 1)
       > kill vlan (pid 7)
       For full logs, run 'nix log /nix/store/r9qfv8c94ca52iyx51v99jwd9kl19lc9-vm-test-run-bcachefs.drv'.
   
</code>

</details>

**Comment by tmuehlbacher** [comment]
There's likely going to be a v1.9.1 shortly :sweat_smile:

**Comment by tmuehlbacher** [comment]
v1.9.1 is tagged now btw. :)

**Comment by JohnRTitor** [comment]
`nom build .#nixosTests.bcachefs` succeeds now.

**Comment by JohnRTitor** [comment]
@ofborg build bcachefs-tools.passthru.tests

**Comment by JohnRTitor** [comment]
Looks like it [fails multi installer test](https://github.com/NixOS/nixpkgs/pull/321055/checks?check_run_id=26488767354), @tmuehlbacher would there be a upstream commit fixing this soon?

I remember Kent said this is harmless, ie. won't eat your data. But since this test fails, I am hesitant to merge this as this might cause other issues.

@onny would love if you could test this with encrypted root!

**Comment by tmuehlbacher** [comment]
simple and multi both fail. Huh, it's stuck at writing the hardware-configuration.nix file? => This is fixed by adding `modprobe bcachefs` in `createPartitions`/`installer.succeed()`.

But then it failed for me locally at a later stage verifying the nix store. Not sure about that yet.

I have been using the flake from upstream as an overlay on my system for a bit and can still boot at least.
btw, I think you can also delete the patch file, since it's no longer used?

**Comment by JohnRTitor** [comment]
Good catch! not sure how I missed it.

**Comment by tmuehlbacher** [comment]
Ok so I have a fix for these test failures now. The tests work if you add this:

```diff
diff --git a/nixos/tests/installer.nix b/nixos/tests/installer.nix
index 3f57a64333dd..d3e870f7922a 100644
--- a/nixos/tests/installer.nix
+++ b/nixos/tests/installer.nix
@@ -1144,6 +1144,7 @@ in {

     createPartitions = ''
       installer.succeed(
+        "modprobe bcachefs",
         "flock /dev/vda parted --script /dev/vda -- mklabel msdos"
         + " mkpart primary ext2 1M 100MB"          # /boot
         + " mkpart primary linux-swap 100M 1024M"  # swap
@@ -1213,6 +1214,7 @@ in {

     createPartitions = ''
       installer.succeed(
+        "modprobe bcachefs",
         "flock /dev/vda parted --script /dev/vda -- mklabel msdos"
         + " mkpart primary ext2 1M 100MB"          # /boot
         + " mkpart primary linux-swap 100M 1024M"  # swap

```

I am not sure why this is needed _now_ and if that's a problem or normal. Without explicitly loading bcachefs, the mount succeeds still but then the fs cannot be used in any way. It appears that nixos-generate-config just blocks forever trying to write to a file inside of the fs.

---

I was also sidetracked by something else: I have `TMPDIR=/var/tmp` set for nix-daemon.service because large builds like the kernel end up exhausting the my tmpfs-backed `/tmp`, which is the default build dir for nix. The problem is that these tests fail if I build them in my bcachefs-backed `/var/tmp` with kernel messages like this:

```
installer # [   65.856006] bcachefs (vda3 inum 1879055323 offset 3871232): data data checksum error, type crc32c: got 00000000 should be ee7e0061
installer # [   65.856683] bcachefs (vda3 inum 1879055323 offset 3871232): no device to read from
installer # [   65.857233] bcachefs (vda3 inum 1879055323 offset 3871232): read error 3 from btree lookup
installer # [   65.858518] bcachefs (vda3 inum 1879055323 offset 3871232): data data checksum error, type crc32c: got 00000000 should be ee7e0061
installer # [   65.859271] bcachefs (vda3 inum 1879055323 offset 3871232): no device to read from
installer # [   65.859642] bcachefs (vda3 inum 1879055323 offset 3871232): read error 3 from btree lookup
```

Here is the full log for `# nix build --rebuild --option build-dir /var/tmp -L .#nixosTests.installer.bcachefsSimple` 
[test-build-log.txt](https://github.com/user-attachments/files/15937804/test-build-log.txt)

**Comment by JohnRTitor** [comment]
`Modeprobe`ing loads the kernel module, which I believe takes over mounting. I am not confident enough to merge this as it is, without comprehensive testing that this won't break like last time.

**Comment by JohnRTitor** [comment]
@ofborg eval

**Comment by JohnRTitor** [comment]
Result of `nixpkgs-review pr 321055` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>bcachefs-tools</li>
  </ul>
</details>

**Comment by JohnRTitor** [comment]
The issue was with `bcachefs` kernel module, and has been fixed in 6.9.7+ releases. 

and Ofborg suggests the installer tests are [succeeding](https://github.com/NixOS/nixpkgs/pull/321055/checks?check_run_id=27135189079) as well. As such I have no reason to hold this further.

**Pull request merged**
