### PR TITLE
[22.05] nixos/proxmox-image: fix broken build

### PR DESCRIPTION
**Pull request by illustris**
(cherry picked from commits 148b6da2a785371127eb52f0c37bd3421ce5db6c and 0c0ea441e7a1fbbbccd1fdfbf998932fa14d75ac)

###### Description of changes

This is a backport of https://github.com/NixOS/nixpkgs/pull/172076
Fixes https://github.com/NixOS/nixpkgs/issues/171989 on 22.05

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by illustris** [comment]
```
[illustris@illustris-thinkpad:~/src/nixpkgs/.worktree/backport-pve]$ nix run github:nix-community/nixos-generators -- -f proxmox -I nixpkgs=$PWD
trace: warning: system.stateVersion is not set, defaulting to 22.05. Read why this matters on https://nixos.org/manual/nixos/stable/options.html#opt-system.stateVersion.
/nix/store/sjx1ivrzh9ffkf787gg0n6998ki3snbr-proxmox-nixos-22.05pre-git/vzdump-qemu-nixos-22.05pre-git.vma.zst
```

**Review by winterqt — APPROVED** [review]
Out of curiosity, is there a reason you didn't add the commit adding Proxmox images to the release? (I don't think there would be an issue, but you might/probably know better than me.)

**Comment by illustris** [comment]
I wasn't sure if anyone would take issue with that. So I went with the most pedantic interpretation of the "backporting changes" section of CONTRIBUTING.md and picked only the commit that fixed the issue, and nothing more. If adding that commit is fine, I'll do it. Would be nice to have proxmox images for 22.05 available on Hydra.

**Comment by winterqt** [comment]
Considering the last change to release was before the branch off to 22.05, I'm not entirely sure. I don't see why it shouldn't be backported, but someone else might.

@dasJ What do you think?

**Comment by dasJ** [comment]
I have no particular opinion

**Comment by winterqt** [comment]
I asked around in #dev, and others agreed that this can be merged.

**Pull request merged**
