### PR TITLE
rstudio: use qt5's mkDerivation

### LINKED ISSUE #74298: RStudio "failed to start because no Qt platform plugin could be initialized"
I have installed RStudio on NixOS via `environment.systemPackages`. When I try to start it, it fails with an error message:
```
$ rstudio
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

[1]    2573 abort (core dumped)  rstudio
$ echo $QT_PLUGIN_PATH
/home/c74d/.nix-profile/lib/qt4/plugins:/home/c74d/.nix-profile/lib/kde4/plugins:/etc/profiles/per-user/c74d/lib/qt4/plugins:/etc/profiles/per-user/c74d/lib/kde4/plugins:/nix/var/nix/profiles/default/lib/qt4/plugins:/nix/var/nix/profiles/default/lib/kde4/plugins:/run/current-system/sw/lib/qt4/plugins:/run/current-system/sw/lib/kde4/plugins
```

RStudio worked fine for me on NixOS in 2018, when it would build at all. Rebooting my computer doesn't fix the problem, so I doubt it's a transient problem with my desktop session.

I note that this is the same error message from #33702, #48826, and #54872, but my issue involves RStudio installed via `environment.systemPackages` rather than run via `nix-shell` as in those issues.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.84-hardened, NixOS, 20.03pre202088.e89b21504f3 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre202088.e89b21504f3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by tomcur**
###### Motivation for this change

This fixes QT5 at runtime. See tracking issue #65399.
Fixes #74298.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @ehmry @changlinli @ciil

### CODE REVIEW

**Comment by ciil** [comment]
Thanks a lot for tackling the qt5 issue. Last time I checked this change wasn't enough to fix it, but hopefully it works now. Unless somebody else does it first, I'll be looking into this more thoroughly tomorrow.

**Review by jonringer — COMMENTED** [review]
it's double wrapped, one of them isn't needed

```
#rstudio
#! /nix/store/b34zjdmq5l8k6rwdykjx55yl9r9isl8k-bash-4.4-p23/bin/bash -e
export PATH=$PATH${PATH:+':'}'/nix/store/64w6bxpi29xm01lnis31pii17q79inaw-gnumake-4.2.1/bin'
exec -a "$0" "/nix/store/c9qkgz4c7aivbhk0bjzgsl4vsh516p02-RStudio-1.2.1335/bin/.rstudio-wrapped"  "$@"
```

EDIT: looking at the expression, this would imply that rstudio shells out to make... is that true?

**Comment by Beskhue** [comment]
@jonringer thanks, I've moved the wrapping into `qtWrapperArgs`: there's only one layer of wrapping now.

RStudio uses Make for build tooling. Building RStudio without `gnumake` in `qtWrapperArgs`, and then trying to use the Make build tools at runtime in RStudio will error.

Oddly enough, when:
1. building RStudio _with_ `qtWrapperArgs`;
1. then copying the resulting wrapper and removing the `PATH` export; and
1. launching that custom wrapper while providing only bash in the path: `PATH=/nix/store/fa4zygrvfq77gccqiyl9kixs05nfihk1-bash-interactive-4.4-p23/bin ./custom-rstudio-wrapper`

RStudio somehow still gets `gnumake` in its path: if you open a terminal inside RStudio and `echo $PATH`, it'll show whathever you set the path to _and_ will have gnumake appended. Something like `/nix/store/fa4zygrvfq77gccqiyl9kixs05nfihk1-bash-interactive-4.4-p23/bin:/nix/store/64w6bxpi29xm01lnis31pii17q79inaw-gnumake-4.2.1/bin`. I'm not sure why that is.

**Review by ciil — APPROVED** [review]
Yeah, if you `echo $PATH` in the originally wrapped version leads to gnumake being appended twice. I don't see any obvious way to resolve this now and would rather (now that I finally got around to testing) see this merged sooner rather than even later.

So, tested and lgtm for what the PR set out to do.

**Review by ghost — APPROVED** [review]

**Comment by jonringer** [comment]
the `rstudio` package launches fine, is there a need for the `rstudioWrapper` package anymore?

**Comment by Beskhue** [comment]
`rstudioWrapper` is a package that is to `rstudio` as `rWrapper` is to `R`: it sets `R_LIBS_SITE`. This appears to be necessary if you want to use R packages installed with Nixpkgs (through `rstudioWrapper.override = { packages = [ ... ]; }`.

`rstudioWrapper` uses `rstudio`.

**Comment by jonringer** [comment]
ah, so it's to help with managing r packages. Sounds good

**Pull request merged**
