### PR TITLE
redo-apenwarr: init at unstable-2019-06-21

### PR DESCRIPTION
**Pull request by andrewchambers**
###### Motivation for this change

New package.

###### Things done

- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by andrewchambers** [comment]
@grahamc  Not quite sure what this failed check means.

**Comment by joachifm** [comment]
@GrahamcOfBorg build redo-apenwarr

**Comment by joachifm** [comment]
ofborg fails with hash mismatch

> hash mismatch in fixed-output derivation '/nix/store/6jqhb18lknd6is01hq399bia5za2i2c7-source':
  wanted: sha256:0nk74dngww3w74zz8c8vsqdbsn9q9pg9xdlrki0hvvcbq68w9l8z
  got:    sha256:0x1bvfyxg4pqd041zsxh9fwc2jv25achc9i57629s9kill18vfjc

**Comment by andrewchambers** [comment]
Ok, I will update.

**Comment by joachifm** [comment]
@GrahamcOfBorg build redo-apenwarr

**Pull request merged**
