### PR TITLE
gnomeExtensions.window-is-ready-remover: remove custom packaging and create alias

### PR DESCRIPTION
**Pull request by rhoriguchi**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 122921` at 47774d4b run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>gnomeExtensions.window-is-ready-remover</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/desktops/gnome/extensions/window-is-ready-remover/default.nix:23:3:
```
   |
23 |   meta = with lib; {
   |   ^
```
</li>
  </ul>
</details>

**Comment by jonringer** [comment]
cc @NixOS/gnome

**Comment by piegamesde** [comment]
nixpkgs master now contains the extension with the desired version, albeit under a different name (due to automatic packaging): `window-is-ready-notification-remover`. I think the best way forward is to replace the whole packaging with a simple alias. But I'd be fine with merging as is too, the cleanup is not urgent.

**Comment by rhoriguchi** [comment]
> nixpkgs master now contains the extension with the desired version, albeit under a different name (due to automatic packaging): `window-is-ready-notification-remover`. I think the best way forward is to replace the whole packaging with a simple alias. But I'd be fine with merging as is too, the cleanup is not urgent.

I agree with removing and adding a alias but that should be fixed with #124315.

**Comment by piegamesde** [comment]
As far as I can tell, this has already been committed as part of #124315. I am sorry for the trouble.

**Pull request closed without merging**
