### PR TITLE
_1password-gui: 8.8.0 -> 8.9.4

### PR DESCRIPTION
**Pull request by SebTM**
###### Description of changes

Updated to latest stable release

###### Things done

Updated hash, checked app locally

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by maxeaubrey** [comment]
Please change the PR name and commit message to match the package name, i.e. `_1password-gui`.

**Comment by SebTM** [comment]
> Please change the PR name and commit message to match the package name, i.e. `_1password-gui`.

Done

**Comment by maxeaubrey** [comment]
Thanks

**Comment by Lyndeno** [comment]
Trying to use the built-in ssh key signing feature for git:
```zsh
$ /nix/store/g2dsfb8viffa6h225y9lkg05am3bihf6-1password-8.9.4/share/1password/op-ssh-sign
zsh: no such file or directory: /nix/store/g2dsfb8viffa6h225y9lkg05am3bihf6-1password-8.9.4/share/1password/op-ssh-sign
```

Using `ls` the executable is indeed there.

**Comment by Lyndeno** [comment]
Please see #193454 for fix. Tested by launching application and it did not through the error. I did not try actually signing anything with it yet.

**Pull request merged**
