### PR TITLE
Use unix chkpwd wrapper

### PR DESCRIPTION
**Pull request by jcumming**
###### Motivation for this change

Non-root applications that use PAM to check auth credentials need a suid helper application to access `/etc/shadow`. 

NixOS creates this wrapper at `/run/wrappers/chkpwd`, this patch the `pam_unix` security module to use the suid wrapper. It provides a function argument to allow overriding the chkpwd to use.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@jcumming please target staging with the mass rebuild.

**Comment by jcumming** [comment]
Created PR in #106285, closing this one.

**Comment by SuperSandro2000** [comment]
Please do not create not necessary PRs if you can reuse an existing one by a simple force push.

**Comment by jcumming** [comment]
> Please do not create not necessary PRs if you can reuse an existing one by a simple force push.

Reviewing PRs is a thankless job, and I understand rigour is required to ensure high quality of the codebase. 

I appreciate you being polite, but you aren't being helpful. Can you throw a couple links down on how to:
 - force push a PR
 - retarget a PR to a different branch

Thanks!

**Pull request closed without merging**
