### PR TITLE
nim: 0.17.2 -> 0.18.0

### PR DESCRIPTION
**Pull request by euantorano**
###### Motivation for this change

Update the version of Nim to the current release, 0.18.0.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I haven't had time to test this at all as I'm new to Nix, but this is a releatively minor change that should hopefully just work.

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build nim

**Comment by Mic92** [comment]
One test at least fails for me. Should be easy to patch by replacing `/bin/sleep` in the file:

```
FAIL: tioselectors.nim C
Test "tests/async/tioselectors.nim" in category "async"
Failure: reExitcodesDiffer
Expected:
exitcode: 0
Gotten:
exitcode: 1
Output:
tioselectors.nim(466)    tioselectors
tioselectors.nim(164)    process_notification_test
osproc.nim(830)          startProcess
osproc.nim(942)          startProcessAuxFork
oserr.nim(110)           raiseOSError
Error: unhandled exception: Operation now in progress
Additional info: Could not find command: '/bin/sleep'. OS error: No such file or directory [OSError]
```

**Comment by euantorano** [comment]
How might I go about doing that @Mic92? This is my first foray into Nix, so any pointers would be appreciated.

**Comment by euantorano** [comment]
It looks like most of the failures are related to missing binaries:

- `/usr/bin/env`
- `/bin/sleep`

There's also an interesting one relating to boehm GC:

```
could not load: libgc.so.1
compile with -d:nimDebugDlOpen for more information
```

I'm going to mention this in the Nim IRC channel and see if anybody has any ideas about the above and some of the other issues (such as `cannot open 'jester'`).

**Comment by euantorano** [comment]
Looks like I also need to add `boehm-gc` as a dependency. I'll push a patch tomorrow after testing this locally and see how may of these issues I can solve.

**Comment by Mic92** [comment]
@euantorano you can use `substituteInPlace` in `postPatch` to fix replace the path in those tests with a binary without `/bin` it: https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/text/a2ps/default.nix#L26

**Comment by pacien** [comment]
Required build and test dependencies are listed in nim's Travis CI configuration file [here](https://github.com/nim-lang/Nim/blob/v0.18.0/.travis.yml).

It seems that some `nimble` packages need to be installed (at least temporarily in the test environment) to properly run the tests.

**Comment by euantorano** [comment]
@pacien Yep, I've been trying that. Been hitting permission denied errors when running `nimble install` inside the script, probably because it's trying to write to somewhere like `$HOME/.nimble`. I also can't find `libgc` which is required for the boehm GC tests.

**Comment by pacien** [comment]
[Here](https://github.com/euantorano/nixpkgs/pull/1) is a pull request for this pull request.
I made some progress, successfully adding Boehm GC and SFML.
Nimble however seems to fail downloading packages from the build sandbox.

**Comment by euantorano** [comment]
Thanks to @pacien, this should now pass tests hopefully.

**Comment by Mic92** [comment]
@GrahamcOfBorg build nim

**Comment by Mic92** [comment]
If access to $HOME is denied a workaround is to set `export HOME=$TMPDIR`. However network access for the package manager is not allowed anyway, so disabling those tests is probably the better choice.

**Comment by pacien** [comment]
Failure is at [lib/pure/stats.nim#L361](https://github.com/nim-lang/Nim/blob/v0.18.0/lib/pure/stats.nim#L361). Floats should not be compared that way since their precision may vary on different architectures ([Nim/issues#6747](https://github.com/nim-lang/Nim/issues/6747)).

@euantorano Maybe should we disable this test?

```
FAIL: stats.nim C
Test "lib/pure/stats.nim" in category "lib"
Failure: reExitcodesDiffer
Expected:
exitcode: 0
Gotten:
exitcode: 1
Output:
stats.nim(361)           stats
system.nim(3771)         raiseAssert
system.nim(2833)         sysFatal
Error: unhandled exception: intercept(rr) == -0.03424657534246611  [AssertionError]
```

**Comment by euantorano** [comment]
Yeah, disabling that test is probably the easiest solution.

**Comment by Mic92** [comment]
It does not really make the build fail so we can keep it. I think this test should be rather fixed upstream.

**Pull request merged**
