### PR TITLE
swhkd: init at 1.2.2

### PR DESCRIPTION
**Pull request by mibmo**
## Description of changes

Add swhkd package

## Things done

Created pkg then tested by running `swhks &` then creating a test config at `/etc/swhkd/swhkdrc` and running `pkexec swhkd`.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mibmo** [comment]
> Tested it out and its working great for me! Would you be planning to add polkit rules and services so that it can be started automatically on boot? 

I've not done any work with Polkit, but I am writing a module for it :) I can't decide whether it should be nixos or home-manager though; afaik swhks has to run as your specific user and that just seems more suitable for HM.

If you need it ASAP, I can push my work somewhere :)

**Comment by alexandru0-dev** [comment]
any update on the pr?

**Comment by mibmo** [comment]
> any update on the pr?

The module PR or this one? as far as i remember, this one is good to go, just needs reviewing.

**Comment by alexandru0-dev** [comment]
@mibmo this one

**Comment by Baitinq** [comment]
@SuperSandro2000 Adding you as a reviewer since you took a look at the [PR](https://github.com/NixOS/nixpkgs/pull/276788) that was based on this. Thank you!🙇

**Review by Baitinq — APPROVED** [review]
lgtm

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by lolbinarycat** [comment]
oppose in favor of #306159 since that PR properly installs manpages.

if people don't like the idea of adding an untested module to nixos, i can split off a pr that just adds the package.

**Pull request closed without merging**
