### PR TITLE
Upgraded MinGW-W64 to stable version 5.0.3

### PR DESCRIPTION
**Pull request by taktoa**
###### Motivation for this change

There is a new version of MinGW-W64, so I updated the package to use that.

I also refactored the package a bit and added the `--enable-idl` and `--enable-secure-api`
flags which I found necessary when hacking on MinGW cross compilation last October.

I tested all the packages in `crossMingwW64` and they all compile except for `coreutils`, `guile_1_8` (because `libsigsegv` fails), and `windows.wxMSW`. See #24984 for more details. Note that all three of those packages were broken before this change.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox][useSandbox] or `build-use-sandbox` in [`nix.conf`][nix.conf])
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all modified pkgs using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

[useSandbox]: http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox
[nix.conf]: http://nixos.org/nix/manual/#sec-conf-file

### CODE REVIEW

**Comment by DavidEGrayson** [comment]
Projects like MSYS2 that rely heavily on mingw-w64 usually just [build](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-headers-git/PKGBUILD) from the latest Git version, and I find that to be convenient too because mingw-w64 can take a long time between releases and most of the commits to it are pretty straightforward bug fixes.  The upstream project is also pretty fast at accepting patches when I send them.  So I would prefer to use git, but I suppose it also works to do it this way and just patch it as needed in nixpkgs.

**Comment by taktoa** [comment]
I'm fine with using the latest git revision, but I've usually found there to be a fairly strong bias in nixpkgs towards using the latest stable release (and having `5.0.2` is still going to be a huge improvement over `4.0.6`), so I'll leave it as-is and someone else can make another PR that upgrades it to the latest git.

**Comment by Mic92** [comment]
It would also acceptable to have a newer `unstable` variant of mingw-w64 as well.

**Comment by 7c6f434c** [comment]
I think having both stable and unstable is OK when there is a reason to have unstable, too.

Maybe adding meta would be a good idea.

**Comment by vcunat** [comment]
This would break 32-bit builds, as `gcc-5.4.0-i686-pc-mingw32-stage-final` fails with:
```
checking for -rdynamic... g++   -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE  -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -DGENERATOR_FILE -static-libstdc++ -static-libgcc  -o build/genmatch \
    build/genmatch.o ../build-x86_64-unknown-linux-gnu/libcpp/libcpp.a build/errors.o build/vec.o build/hash-table.o ../build-x86_64-unknown-linux-gnu/libiberty/libiberty.a
yes
checking for library containing dlopen... genattr: Internal error: abort in copy_rtx, at rtl.c:356
make[2]: *** [Makefile:2130: s-attr] Error 1
make[2]: *** Waiting for unfinished jobs....
```

You can test quickly e.g. by `nix-build pkgs/top-level/release-cross.nix -Q -A crossMingw32.libtool`.

**Comment by Ericson2314** [comment]
@taktoa I last summer split that derivation up kind of like you did, but into separate files. I figured that was good enough, but integrated your extra configure flags, and then cherry-picked @angerman's patch. I'll get hydra to build this to see what happens!

**Comment by Ericson2314** [comment]
Ooop, I had broken the cross jobs quite bad. https://hydra.nixos.org/eval/1442341 has it.

**Comment by Ericson2314** [comment]
OK hydra is slow but I built in manually.

**Pull request merged**
