### PR TITLE
Samba: fix missing dependencies for building sambaFull

### PR DESCRIPTION
**Pull request by ts468**

### CODE REVIEW

**Comment by ts468** [comment]
@edolstra, maybe you could have a look as I'm partly reverting some changes you applied recently

**Comment by edolstra** [comment]
What are those dependencies needed for? AFAIK, stuff like `subunit` and `nss_wrapper` is only used by the test suite that we don't run.

**Comment by ts468** [comment]
Phew! I don't really know what they are needed for. But apparently sambaFull, especially the kerberos related stuff, wouldn't build without it.

**Comment by lethalman** [comment]
sambaFull now builds because I've dropped the heimdal compat patch. Closing.

**Pull request closed without merging**
