### PR TITLE
coursera-dl: init at 0.10.0

### PR DESCRIPTION
**Pull request by alexfmpe**
###### Motivation for this change
New package

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build coursera-dl

**Comment by Mic92** [comment]
The following will enable tests:

```
diff --git a/pkgs/applications/misc/coursera-dl/default.nix b/pkgs/applications/misc/coursera-dl/default.nix
index 419d91c5709..1f5d7107aa4 100644
--- a/pkgs/applications/misc/coursera-dl/default.nix
+++ b/pkgs/applications/misc/coursera-dl/default.nix
@@ -1,7 +1,8 @@
-{ stdenv, fetchFromGitHub, fetchurl, pandoc, python3, glibcLocales }:
+{ stdenv, fetchFromGitHub, fetchurl, pandoc, python2 }:
 let
-  pythonPackages = python3.pkgs;
+  pythonPackages = python2.pkgs;
+
 in pythonPackages.buildPythonApplication rec {
   name = "coursera-dl-${version}";
   version = "0.10.0";
@@ -13,23 +14,10 @@ in pythonPackages.buildPythonApplication rec {
     sha256 = "0m3f6ly8c3mkb8yy2y398afswqgy17rz159s1054wzxpb4f85zlb";
   };
-  nativeBuildInputs = with pythonPackages; [ pandoc ];
-
-  buildInputs = [ glibcLocales ];
+  buildInputs = with pythonPackages; [ beautifulsoup4 ConfigArgParse keyring mock pandoc pytest requests urllib3 ];
   propagatedBuildInputs = with pythonPackages; [ beautifulsoup4 ConfigArgParse keyring pyasn1 requests six urllib3 ];
-  checkInputs = with pythonPackages; [ pytest mock ];
-
-  preConfigure = ''
-    export LC_ALL=en_US.utf-8
-  '';
-
-  checkPhase = ''
-    # requires dbus service
-    py.test -k 'not test_get_credentials_with_keyring' .
-  '';
-
   meta = with stdenv.lib; {
     description = "CLI for downloading Coursera.org videos and naming them";
     homepage = https://github.com/coursera-dl/coursera-dl;
```

**Comment by alexfmpe** [comment]
Thanks. I updated the PR with your feedback.
That fixes the `UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2` under python 3, but I do get a warning in NixOS: 
`/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf-8)`

**Comment by Mic92** [comment]
This is probably related to: https://github.com/NixOS/nixpkgs/issues/38991

**Comment by Mic92** [comment]
@GrahamcOfBorg build coursera-dl

**Pull request merged**
