### PR TITLE
bcachefs/update-7

### PR DESCRIPTION
**Pull request by eadwu**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by Chiiruno** [comment]
I'm having some overheating issues and no compressed air on hand, so I'll have to test this at a later date.
In the meantime...
@GrahamcOfBorg test bcachefs

**Review by ghost — APPROVED** [review]
Got some compressed air!
Tested with `nix-build nixos/tests/bcachefs.nix`, all good!

**Comment by Chiiruno** [comment]
@GrahamcOfBorg build linux_testing_bcachefs

**Comment by Chiiruno** [comment]
Yeah sorry, I don't think I have permissions for that, we'll have to wait until someone with them can build/test/merge with the build bot.

**Review by ghost — APPROVED** [review]
Tested latest with `nix-build nixos/tests/bcachefs.nix`, all good!
I think the checks are due to a hydra failure.

**Review by ghost — APPROVED** [review]
Tested again as above.
Still good.

**Comment by davidak** [comment]
@GrahamcOfBorg test bcachefs

**Review by davidak — APPROVED** [review]
LGTM

not tested tho

**Comment by timokau** [comment]
Thanks all!

**Pull request merged**
