### PR TITLE
[WIP] qgis: update to 2.8.0

### PR DESCRIPTION
**Pull request by michelk**
I'm trying to update qgis. I could successfully compile. But when I try to run `qgis`, I get a 
- python error and 
- libpng incompatibility error.

```
libpng warning: Application was compiled with png.h from libpng-1.6.16
libpng warning: Application  is  running with png.c from libpng-1.2.50
libpng error: Incompatible libpng version in application and library
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 545, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 237, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 582, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 528, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 412, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdata_nd
```

@vbgl was the python error solved in #4898?

### CODE REVIEW

**Comment by vbgl** [comment]
AFAIK these issues (python and libpng) have not been addressed. I could not reproduce the python error.

**Comment by michelk** [comment]
I can confirm: On NixOS I won't get the python error, only on debian/nixpkgs. 

I also just saw that in `qscintilla` we need the python bindings for the processing plugin.

**Comment by vbgl** [comment]
Looks like 2.8.1 is out already.

**Comment by michelk** [comment]
Updated to 2.8.1.

**Comment by michelk** [comment]
Curiously the libpng error has vanished.  So everything's works fine, except of the processing plugin which depends on the python bindings for qscintilla. But I think this could be merged for now.

**Pull request merged**
