### PR TITLE
python3Packages.mautrix: 0.5.8 -> 0.8.3, mautrix-telegram: 0.8.2 -> 0.9.0, python3Packages.telethon: 1.14.0 -> 1.17.5

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Motivation for this change

Closes #103319, Closes #92893

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105336` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>mautrix-telegram</li>
    <li>python37Packages.mautrix</li>
    <li>python37Packages.telethon</li>
    <li>python38Packages.mautrix</li>
    <li>python38Packages.telethon</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105336` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python37Packages.mautrix</li>
    <li>python37Packages.telethon</li>
    <li>python38Packages.mautrix</li>
    <li>python38Packages.telethon</li>
  </ul>
</details>

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 105336 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>5 packages built:</summary>  <ul>    <li>mautrix-telegram</li>    <li>python37Packages.mautrix</li>    <li>python37Packages.telethon</li>    <li>python38Packages.mautrix</li>    <li>python38Packages.telethon</li>  </ul></details>

**Comment by Limvot** [comment]
I think this update makes the service not work for me, as it doesn't install anything in the bin folder:
`/nix/store/6gnd9dl9pbh1fnlx6zgd5n22xx54kzr3-python3.8-mautrix-telegram-0.9.0/bin/mautrix-telegram: No such file or directory`

I'm guessing this is due to https://github.com/tulir/mautrix-telegram/commit/a565853c5e57a5671ebe4da178a5ac3d02a5005c
but I'm not sure.

**Comment by Ma27** [comment]
Was this actually tested before merging?

Will take a look.

**Comment by Ma27** [comment]
@Limvot fixed in 878e80c5962b42b7b10a20a98f98319a72cb5031, 752b6a95db93f03d6901304f760bd452b4b7db41.

**Pull request merged**
