### PR TITLE
nodePackages: Add js-beautify

### PR DESCRIPTION
**Pull request by jbaum98**
###### Motivation for this change

Add [js-beautify](https://github.com/beautify-web/js-beautify) to `nodePackages`

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
Is this still working? If so it would be great integration into the js2mode of spacemacs

**Comment by jbaum98** [comment]
I accidentally closed this when trying to redo this commit to fix the merge conflicts, my bad.

**Comment by jbaum98** [comment]
This one has no merge conflicts and definitely still builds on my machine.

**Comment by tjikini** [comment]
@Mic92 please merge :)

**Pull request closed without merging**
