### PR TITLE
lammps: stable_22Aug2018 -> stable_29Oct2020

### PR DESCRIPTION
**Pull request by markuskowa**
###### Motivation for this change
Update from an old 2018 version. Supersedes and closes https://github.com/NixOS/nixpkgs/pull/80614

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by markuskowa** [comment]
@GrahamcOfBorg build lammps-mpi

**Review by costrouc — APPROVED** [review]
Thank you for updating lammps along with trying to standardize the mpi attribute! Looks great to me.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 110590` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python37Packages.dftfit</li>
    <li>python37Packages.lammps-cython</li>
    <li>python38Packages.dftfit</li>
    <li>python38Packages.lammps-cython</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110590` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>4 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.dftfit: log was empty</li>
<li>python37Packages.lammps-cython: log <a href="https://termbin.com/lehf">https://termbin.com/lehf</a></li>
<li>python38Packages.dftfit: log was empty</li>
<li>python38Packages.lammps-cython: log <a href="https://termbin.com/f3q2">https://termbin.com/f3q2</a></li>
  </ul>
</details>
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>lammps</li>
<li>lammps-mpi</li>
</ul>
</details>

**Comment by markuskowa** [comment]
@costrouc the update breaks `pymatgen-lammps`. It may need a patch?

**Comment by markuskowa** [comment]
Rebased. The python packages that are affected by this update have been marked broken meanwhile.

**Pull request merged**
