### PR TITLE
monero: 0.17.1.0 -> 0.17.1.1

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
Important bugfix

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Can you fix the title and commit messages?

``monero: 0.17.1.1 -> 0.17.1.1`` => ``monero: 0.17.1.0 -> 0.17.1.1``

**Comment by rnhmjoj** [comment]
Done, thank you.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 101985` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>monero</li>
  </ul>
</details>

**Comment by rnhmjoj** [comment]
Backported to 20.09: 47122ce3f9176c8476106b79bf3890bcbe571f83 b3bf6a410a91d3205fd95e4b78b45af57a2e7852

**Pull request merged**
