### PR TITLE
notebook: fix tests on darwin, 6.1.3 -> 6.1.4

### PR DESCRIPTION
**Pull request by tricktron**
###### Motivation for this change

The last commit c379aa9f8e4d1d43b7cd1d549a49b8f09286fe91 removed two excluded tests on darwin. Unfortunately they still fail on darwin:
```bash
File "/nix/store/hzvpbjbpschymag875hjzpsy2vrvrd9l-python3.8-tornado-6.0.4/lib/python3.8/site-packages/tornado/web.py", line 1703, in _execute
    result = await result
  File "/nix/store/hzvpbjbpschymag875hjzpsy2vrvrd9l-python3.8-tornado-6.0.4/lib/python3.8/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/private/tmp/nix-build-python3.8-notebook-6.1.4.drv-0/notebook-6.1.4/notebook/services/contents/handlers.py", line 237, in delete
    yield maybe_future(cm.delete(path))
  File "/private/tmp/nix-build-python3.8-notebook-6.1.4.drv-0/notebook-6.1.4/notebook/services/contents/manager.py", line 279, in delete
    self.delete_file(path)
  File "/private/tmp/nix-build-python3.8-notebook-6.1.4.drv-0/notebook-6.1.4/notebook/services/contents/filemanager.py", line 546, in delete_file
    send2trash(os_path)
  File "/nix/store/jf45dbr7f1z7n01k1snqljlfbqw21sm8-python3.8-Send2Trash-1.5.0/lib/python3.8/site-packages/send2trash/plat_osx.py", line 48, in send2trash
    check_op_result(op_result)
  File "/nix/store/jf45dbr7f1z7n01k1snqljlfbqw21sm8-python3.8-Send2Trash-1.5.0/lib/python3.8/site-packages/send2trash/plat_osx.py", line 37, in check_op_result
    raise OSError(msg)
OSError: Insufficient access privileges for operation
```

I don't know what is causing it. It looks like nix cannot delete a file in `/private/tmp` on darwin due to permission issues. These permission issues seem to pop up since MacOs 10.15 Catalina.

@NixOS/nixos-release-managers For now I just excluded the tests again but if anyone has a better idea I am open for suggestions.

ZHF: #97479 

###### System info

```
- system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(tricktron): `""`
 - channels(root): `"nixpkgs-20.03pre197736.91d5b3f07d2"`
 - nixpkgs: `/Users/tricktron/github/my-forks/nixpkgs`
```

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tricktron** [comment]
@jonringer What is the difference between `pytestCheckHook` and just `pytest`?

**Comment by risicle** [comment]
Fixes the build for me on macos 10.14

**Review by worldofpeace — CHANGES_REQUESTED** [review]
editorconfig test fails, can this be fixed?

**Comment by jonringer** [comment]
> @jonringer What is the difference between `pytestCheckHook` and just `pytest`?

https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#using-pytestcheckhook

**Comment by tricktron** [comment]
@jonringer Thanks for the link.

**Comment by tricktron** [comment]
@worldofpeace I fixed the editorconfig test

**Pull request merged**
