### PR TITLE
nixui: include build files

### PR DESCRIPTION
**Pull request by matejc**
fix issue when nixui is inside systemPackages

### CODE REVIEW

**Comment by wmertens** [comment]
that was fast :) I just removed nixui, let me fix that.

**Comment by wmertens** [comment]
Hmm sorry @matejc looks like the git author info didn't make it over :cry: I guess the only way to fix that is to remove and re-add the files with the author set to you... want me to do that?

**Comment by matejc** [comment]
If you want to do it then do it, from my side it is OK anyway - no worries.
I am sorry for badly packaged package :)

**Comment by wmertens** [comment]
It's still failing :sob: https://travis-ci.org/NixOS/nixpkgs/builds/48059604#L463

    cannot import ‘/nix/store/jk3vxwh0si3a19bkaqya3gi79nzvxcd5-nixpkgs/pkgs/top-level/node-packages.nix’, since path ‘/nix/store/jk3vxwh0si3a19bkaqya3gi79nzvxcd5-nixpkgs’ is not valid, at "/tmp/nix-build-nixpkgs-tarball-15.05pre1234.abcdef.drv-0/nixpkgs/pkgs/tools/package-management/nixui/node-default.nix":5:18

@edolstra thoughts?

**Comment by wmertens** [comment]
Looks like it only gives that error when the nix store doesn't contain the import path, which is weird because it's in the store?

**Comment by matejc** [comment]
hum, I packaged it with npm2nix that is inside nixpkgs and I rebuild it on my computer on fixnixui branch that was master at the time of building.

**Comment by wmertens** [comment]
Yeah, with travis it somehow breaks...

**Comment by matejc** [comment]
I think I know why, let me try it out and make a pull request

**Pull request closed without merging**
