### PR TITLE
llvm6: 6.0.0 -> 6.0.1 (18.03 edition)

### PR DESCRIPTION
**Pull request by dtzWill**
Triggers rebuild on Linux, so suggesting sent to staging-18.03
(and using PR instead of just picking onto the branch directly).

Like other point releases for LLVM lots of bug-fixes of varying importance.

No official summary of changes (other than looking at SVN/git for commits merged) AFAIK.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by LnL7** [comment]
Is the jobset for staging-18.03 still active? The release staging branches are only used when stabilising the release AFAIK. There's generally not much activity on a stable release to require a staging workflow (unlike master 😄 ).

**Comment by dtzWill** [comment]
Oh, I'm not sure.  I should probably read that RFC again -- I mostly wanted a +1 for this change on 18.03 and to avoid blocking things there unnecessarily since AFAIK this isn't a *priority* but should make it there eventually :).

**Comment by dtzWill** [comment]
Oh, haha there's no mesa dep on 18.03 so it's not a mass-rebuild anyway!
Well alright then this seems like an easy win.  Okay to pick these onto release-18.03 directly?

**Comment by LnL7** [comment]
Has the hydra eval finished building stuff with 6.0.1 yet. Maybe take a quick look at that to make sure everything looks sane, but I don't see a problem with backporting this.

**Comment by dtzWill** [comment]
> Has the hydra eval finished building stuff with 6.0.1 yet. Maybe take a quick look at that to make sure everything looks sane, but I don't see a problem with backporting this.

Not sure which job this would be--with cancels and such.  I think this one, assuming things aren't aborted?

https://hydra.nixos.org/eval/1466589

If so, it looks very much still underway.  If that's correct, then perhaps we should give this a day or two to sit first?

**Comment by LnL7** [comment]
Up to you, I'm guessing it's probably fine if you don't want to wait.

**Comment by dtzWill** [comment]
Welp LGTM but not sure what to make of that evaluation.  But as you say it's unlikely to be especially problematic, but regardless please ping me if anything breaks that I've missed!

**Pull request merged**
