### PR TITLE
box2d: multiple changes

### PR DESCRIPTION
**Pull request by peterhoeg**
## Description of changes

- **box2d: 2.3.1 -> 2.4.1**
- **libsForQt5.qmlbox2d: 2018-04-06 -> 2022-08-025**
- **qt6Packages.qmlbox2d: init at unstable-2022-08-25**
  
I haven't tried building libreoffice but everything else is OK.  

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by peterhoeg** [comment]
Seems like it - I don't have a darwin machine on hand to test it out, so the trial-and-error cycle will be a little slow.

**Comment by 7c6f434c** [comment]
I guess we could throw it in and see if ofBorg is happy… Yeah, if anything more interesting arises, we should try getting Darwin maintainers help and mark broken on Darwin if we don't get a fix from them.

**Comment by peterhoeg** [comment]
Well, I've tried adding it in - let's see what happens.

Let's squash the commits when it's all done.

If we mark it broken, that will break libreoffice on darwin despite it *actually* not using box2d but instead building a vendored version.

**Comment by 7c6f434c** [comment]
I think Carbon comes from Darwin frameworks? E.g. see how `scummvm` line works in `all-packages.nix`

As a LibreOffice maintainer (who doesn't have a nice setup to build it, though), I have zero objections to conditioning-out stuff broken on Darwin when a vendored version is used anyway. Yeah, it's better not to do this if there is a cheap fix, but if not, so be it.

**Comment by 7c6f434c** [comment]
Whether `glfw` being vendored is a good thing or a bad thing is a separate question, but more work to figure out…

**Review by 7c6f434c — APPROVED** [review]

**Review by 7c6f434c — APPROVED** [review]

**Pull request merged**
