### PR TITLE
 python3Packages.pytest: 5.3.5 -> 5.4.1 

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
attempt at  #83675 again, this time giving a month for the ecosystem to adjust.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by drewrisinger** [comment]
FYI, looks ``pytest`` was updated to 5.4.2 in the meantime. https://docs.pytest.org/en/latest/changelog.html

**Review by drewrisinger — APPROVED** [review]
Diff LGTM. Didn't build. ``nix-review`` doesn't work because of merge conflicts.

**Comment by jonringer** [comment]
This was cherry-picked into python-unstable, then merged into staging, now in https://github.com/NixOS/nixpkgs/pull/87814

**Comment by jonringer** [comment]
the conflicts were because staging is now at `5.4.2`

**Pull request closed without merging**
