### PR TITLE
tuxedo-keyboard: 3.2.14 -> 4.6.2

### LINKED ISSUE #337072: Build failure: tuxedo-keyboard-6.10.5-3.2.14.drv
### Steps To Reproduce

If I enable `pkgs.linuxPackages_latest` , I get `tuxedo-keyboard-6.10.5-3.2.14.drv' failed with exit code 2`.

Worked fine with ` pkgs.linuxPackages_6_9`.

[tuxedo-keyboard](https://github.com/NixOS/nixpkgs/blob/master/pkgs%2Fos-specific%2Flinux%2Ftuxedo-keyboard%2Fdefault.nix)

### Build log

```
error: builder for '/nix/store/mhglpxhcc7w4j1g2pah4axxd98c65mz7-tuxedo-keyboard-6.10.5-3.2.14.drv' failed with exit code 2;
       last 25 log lines:
       >       |      ^~~~~~~~~~~~~~~~~
       > /build/source/./src/clevo_acpi.c:189:10: error: 'struct acpi_driver' has no member named 'owner'
       >   189 |         .owner = THIS_MODULE,
       >       |          ^~~~~
       > In file included from /nix/store/3250aqigq71xg3jl7j7f9x7w8nfy2vmi-linux-6.10.5-dev/lib/modules/6.10.5/source/include/linux/printk.h:6,
       >                  from /nix/store/3250aqigq71xg3jl7j7f9x7w8nfy2vmi-linux-6.10.5-dev/lib/modules/6.10.5/source/include/linux/kernel.h:31,
       >                  from /build/source/./src/clevo_acpi.c:20:
       > /nix/store/3250aqigq71xg3jl7j7f9x7w8nfy2vmi-linux-6.10.5-dev/lib/modules/6.10.5/source/include/linux/init.h:180:21: error: initialization of 'const struct acpi_device_id *' from incompatible pointer type 'struct module *' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wincompatible-pointer-types-Werror=incompatible-pointer-types8;;]
       >   180 | #define THIS_MODULE (&__this_module)
       >       |                     ^
       > /build/source/./src/clevo_acpi.c:189:18: note: in expansion of macro 'THIS_MODULE'
       >   189 |         .owner = THIS_MODULE,
       >       |                  ^~~~~~~~~~~
       > /nix/store/3250aqigq71xg3jl7j7f9x7w8nfy2vmi-linux-6.10.5-dev/lib/modules/6.10.5/source/include/linux/init.h:180:21: note: (near initialization for 'clevo_acpi_driver.ids')
       >   180 | #define THIS_MODULE (&__this_module)
       >       |                     ^
       > /build/source/./src/clevo_acpi.c:189:18: note: in expansion of macro 'THIS_MODULE'
       >   189 |         .owner = THIS_MODULE,
       >       |                  ^~~~~~~~~~~
       > cc1: some warnings being treated as errors
       > make[3]: *** [/nix/store/3250aqigq71xg3jl7j7f9x7w8nfy2vmi-linux-6.10.5-dev/lib/modules/6.10.5/source/scripts/Makefile.build:244: /build/source/./src/clevo_acpi.o] Error 1
       > make[2]: *** [/nix/store/3250aqigq71xg3jl7j7f9x7w8nfy2vmi-linux-6.10.5-dev/lib/modules/6.10.5/source/Makefile:1934: /build/source] Error 2
       > make[1]: *** [/nix/store/3250aqigq71xg3jl7j7f9x7w8nfy2vmi-linux-6.10.5-dev/lib/modules/6.10.5/source/Makefile:240: __sub-make] Error 2
       > make[1]: Leaving directory '/nix/store/3250aqigq71xg3jl7j7f9x7w8nfy2vmi-linux-6.10.5-dev/lib/modules/6.10.5/build'
       > make: *** [Makefile:29: all] Error 2
       For full logs, run 'nix log /nix/store/mhglpxhcc7w4j1g2pah4axxd98c65mz7-tuxedo-keyboard-6.10.5-3.2.14.drv'.
error: 1 dependencies of derivation '/nix/store/1x1lmr70msyd70cs44sqd2h38hnmfhjl-linux-6.10.5-modules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/q9mxk49fg6x017inmxda1v0m0k28yd1i-nixos-system-clawfinger-24.05.20240822.797f7dc.drv' failed to build
```

### Additional context

I suspect this has to be changed to gitlab, since hithub repo is not maintained anymore: 
`src = fetchFromGitHub {`

Seems gitlab contains a fix already: https://gitlab.com/tuxedocomputers/development/packages/tuxedo-drivers/-/commit/f8ed07d5baef2a0182e1067b8f0528b6a94770ed

### Notify maintainers

@blanky0230

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
these 6 paths will be fetched (0.75 MiB download, 10.20 MiB unpacked):
  /nix/store/j4aja22d2ngbpmi4vdpdd2dvp1hm7dvr-file-5.45
  /nix/store/pqjr4bpaykb34bp13m1gc5sin1gzb1a8-gnu-config-2024-01-01
  /nix/store/3hnf34qxi3h6c62dw95crgxdxvibasml-gnumake-4.4.1
  /nix/store/cy6j2yii4y9jlbqr10k190v0b3jdbwl3-patchelf-0.15.0
  /nix/store/dd7nxjnni7nzm0846fq5xrm89ais5lwz-stdenv-linux
  /nix/store/l4sqcq84ibmissf3427f34mjlzx28h20-update-autotools-gnu-config-scripts-hook
copying path '/nix/store/pqjr4bpaykb34bp13m1gc5sin1gzb1a8-gnu-config-2024-01-01' from 'https://cache.nixos.org'...
copying path '/nix/store/cy6j2yii4y9jlbqr10k190v0b3jdbwl3-patchelf-0.15.0' from 'https://cache.nixos.org'...
copying path '/nix/store/j4aja22d2ngbpmi4vdpdd2dvp1hm7dvr-file-5.45' from 'https://cache.nixos.org'...
copying path '/nix/store/3hnf34qxi3h6c62dw95crgxdxvibasml-gnumake-4.4.1' from 'https://cache.nixos.org'...
copying path '/nix/store/l4sqcq84ibmissf3427f34mjlzx28h20-update-autotools-gnu-config-scripts-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/dd7nxjnni7nzm0846fq5xrm89ais5lwz-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.12, NixOS, 24.05 (Uakari), 24.05.20240801.0540572`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(papanito): `"home-manager-23.05.tar.gz"`
 - channels(root): `"agenix, nixos"`
 - nixpkgs: `/nix/store/0ma1jl6szmcx4pr9vsczrn7vw7f85b08-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by papanito**
## Description of changes

Fixes #337072

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by papanito** [comment]
@blanky0230 may you have a look

**Comment by idlecodinggoats** [comment]
I've just been trying to use this update but I get a `Unknown symbol tuxedo_is_compatible (err -2)` in `journalctl` - do you not have this problem?

**Comment by papanito** [comment]
how exactly do you try it out? My nixos knowledge is still q bit limited

**Comment by idlecodinggoats** [comment]
I downloaded the raw `default.nix` from this pull request and placed it in my configuration directory i.e. `/etc/nixos/tuxedo-keyboard/default.nix` and in my configuration file (`configuration.nix`) added 
```
boot.kernelModules = [ "tuxedo_keyboard" ];
boot.extraModulePackages = [ ( config.boot.kernelPackages.callPackage ./tuxedo-keyboard/default.nix { } ) ];
```
which mimics `hardware.tuxedo-keyboard.enable = true;` but uses your updated tuxedo-keyboard derivation. Then I do a `nixos-rebuild test` (or `switch` etc.). The module is then available via `modprobe` but won't load because of the `Unknown symbol`.

**Comment by papanito** [comment]
Mhh ok I can't build due to a conflict :-(

```
error: builder for '/nix/store/dsnl0nqpvkb0h0dplp694yif6y666hc4-linux-6.6.52-modules.drv' failed with exit code 25;
       last 1 log lines:
       > error: collision between `/nix/store/d4a8d8lk1fi3svqk8sfpfy7yigkckrvq-tuxedo-keyboard-6.6.52-3.2.14/lib/modules/6.6.52/clevo_acpi.ko' and `/nix/store/dr43l4pqlfs21hfshxhzfjjwngnwli62-tuxedo-keyboard-6.6.52-4.6.2/lib/modules/6.6.52/clevo_acpi.ko'
       For full logs, run 'nix log /nix/store/dsnl0nqpvkb0h0dplp694yif6y666hc4-linux-6.6.52-modules.drv'.
error: 1 dependencies of derivation '/nix/store/pd1jz4fqkg3b1xxh4pli4r41pvswxr6q-nixos-system-clawfinger-24.05.20240927.f651414.drv' failed to build
```

**Comment by h7x4** [comment]
Does this conflict with #336633?

**Comment by papanito** [comment]
Not sure, I added this

```
    kernelPackages = pkgs.linuxPackages_6_10;
    extraModulePackages = [ ( config.boot.kernelPackages.callPackage ./../../tuxedo-keyboard/default.nix { } ) ];
 ```
Which then fails with

```
error: builder for '/nix/store/7hgvnwy3pfvwhw4rxp8mhffsxf7gz14i-tuxedo-keyboard-6.10.11-3.2.14.drv' failed with exit code 2;
       last 10 log lines:
       >       |                     ^
       > /build/source/./src/clevo_acpi.c:189:18: note: in expansion of macro 'THIS_MODULE'
       >   189 |         .owner = THIS_MODULE,
       >       |                  ^~~~~~~~~~~
       > cc1: some warnings being treated as errors
       > make[3]: *** [/nix/store/l82lbbbf14fxqsn5wbgnvk7lilbn8bip-linux-6.10.11-dev/lib/modules/6.10.11/source/scripts/Makefile.build:244: /build/source/./src/clevo_acpi.o] Error 1
       > make[2]: *** [/nix/store/l82lbbbf14fxqsn5wbgnvk7lilbn8bip-linux-6.10.11-dev/lib/modules/6.10.11/source/Makefile:1934: /build/source] Error 2
       > make[1]: *** [/nix/store/l82lbbbf14fxqsn5wbgnvk7lilbn8bip-linux-6.10.11-dev/lib/modules/6.10.11/source/Makefile:240: __sub-make] Error 2
       > make[1]: Leaving directory '/nix/store/l82lbbbf14fxqsn5wbgnvk7lilbn8bip-linux-6.10.11-dev/lib/modules/6.10.11/build'
       > make: *** [Makefile:29: all] Error 2
       For full logs, run 'nix log /nix/store/7hgvnwy3pfvwhw4rxp8mhffsxf7gz14i-tuxedo-keyboard-6.10.11-3.2.14.drv'.
error: 1 dependencies of derivation '/nix/store/lc8n2kal64hzgkcrgk0fmlmv6a1hy2df-linux-6.10.11-modules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/x240gksw1v1nsmp58hk98rnhmj8ks1x6-nixos-system-clawfinger-24.05.20240927.f651414.drv' failed to build
```

It takes the wrong driver version (3.2.14), so I guess I am doing something wrong anything

**Comment by idlecodinggoats** [comment]
> Not sure, I added this
> 
> ```
>     kernelPackages = pkgs.linuxPackages_6_10;
>     extraModulePackages = [ ( config.boot.kernelPackages.callPackage ./../../tuxedo-keyboard/default.nix { } ) ];
> ```
> 
> Which then fails with
> 
> ```
> error: builder for '/nix/store/7hgvnwy3pfvwhw4rxp8mhffsxf7gz14i-tuxedo-keyboard-6.10.11-3.2.14.drv' failed with exit code 2;
>        last 10 log lines:
>        >       |                     ^
>        > /build/source/./src/clevo_acpi.c:189:18: note: in expansion of macro 'THIS_MODULE'
>        >   189 |         .owner = THIS_MODULE,
>        >       |                  ^~~~~~~~~~~
>        > cc1: some warnings being treated as errors
>        > make[3]: *** [/nix/store/l82lbbbf14fxqsn5wbgnvk7lilbn8bip-linux-6.10.11-dev/lib/modules/6.10.11/source/scripts/Makefile.build:244: /build/source/./src/clevo_acpi.o] Error 1
>        > make[2]: *** [/nix/store/l82lbbbf14fxqsn5wbgnvk7lilbn8bip-linux-6.10.11-dev/lib/modules/6.10.11/source/Makefile:1934: /build/source] Error 2
>        > make[1]: *** [/nix/store/l82lbbbf14fxqsn5wbgnvk7lilbn8bip-linux-6.10.11-dev/lib/modules/6.10.11/source/Makefile:240: __sub-make] Error 2
>        > make[1]: Leaving directory '/nix/store/l82lbbbf14fxqsn5wbgnvk7lilbn8bip-linux-6.10.11-dev/lib/modules/6.10.11/build'
>        > make: *** [Makefile:29: all] Error 2
>        For full logs, run 'nix log /nix/store/7hgvnwy3pfvwhw4rxp8mhffsxf7gz14i-tuxedo-keyboard-6.10.11-3.2.14.drv'.
> error: 1 dependencies of derivation '/nix/store/lc8n2kal64hzgkcrgk0fmlmv6a1hy2df-linux-6.10.11-modules.drv' failed to build
> error: 1 dependencies of derivation '/nix/store/x240gksw1v1nsmp58hk98rnhmj8ks1x6-nixos-system-clawfinger-24.05.20240927.f651414.drv' failed to build
> ```
> 
> It takes the wrong driver version (3.2.14), so I guess I am doing something wrong anything

If you've got 'hardware.tuxedo-keyboard.enable = true;' or you are using `hardware.tuxedo-rs.enable = true;' or anything then it'll be pulling in the original 'tuxedo-keyboard' derivation. You'll need to add 'hardware.tuxedo-keyboard.enable = lib.mkForce false;' to prevent this original (3.2.14) derivation from being used. 

For what its worth I think that https://github.com/NixOS/nixpkgs/pull/336633 does fix this problem - but it will need 'tuxedo-rs' to implement using 'tuxedo-drivers' rather than 'tuxedo-keyboard' if that's what you are using.

**Comment by papanito** [comment]
Ahh I see, that makes sense - I slowly getting the grasp of it....

**Comment by papanito** [comment]
I will close my PR, it's the same as #293017 (superseeded by #343483) or #329383 (closed)

But looks like #336633 is the one.

**Comment by blanky0230** [comment]
> I will close my PR, it's the same as #293017 (superseeded by #343483) or #329383 (closed)
> 
> But looks like #336633 is the one.

Thanks for supporting though :+1: I'm just catching up with the review requests rn.

**Pull request closed without merging**
