### PR TITLE
texinfo: 6.5 -> 6.7; fix cross compiling

### PR DESCRIPTION
**Pull request by kampka**
###### Motivation for this change

The current derivation does not correctly cross-build when building in non-interactive mode.
Looking at the derivation, I don't see a reason for this distinction at all, hence this PR removes it.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
since this change causes over 500 rebuilds, do you mind targeting the staging branch

```
git rebase --onto=staging HEAD~1
git push .. ... --force
```
then change the base branch in the github PR from `master` -> `staging`

See https://nixos.org/nixpkgs/manual/#submitting-changes-staging-branch for more details on staging branch
```
$ nix-env -f /home/jon/.cache/nixpkgs-review/pr-95910/nixpkgs -qaP --xml --out-path --show-trace --meta
28975 packages updated:
```

**Comment by kampka** [comment]
Is there any way to get move this along? I know it's a bit last minute, but I'd really hate to miss the 20.09 release window with this ...

**Comment by FRidh** [comment]
This broke darwin stdenv and is blocking staging-next (and branch-off thereby) https://nix-cache.s3.amazonaws.com/log/lnkwicmp12bcy9fhdillhkwh2xm9px8b-texinfo-6.7.drv

**Comment by FRidh** [comment]
Proposed revert https://github.com/NixOS/nixpkgs/pull/97218.

**Comment by kampka** [comment]
> Proposed revert #97218.

This PR contains two commits, the cross-compile fixes and the version bump, the later of which seems to [introduce this regression](https://git.savannah.gnu.org/cgit/texinfo.git/commit/?id=2cd1cfc788d207cef7da5053be1b2ea76a301149).
I think it should be fairly easy to patch this forward, but if you want to revert, would it make sense to just revert the version bump (I'm mostly interested in the cross-compile fixes anyways).
Since I cannot test against Darwin, I'm afraid I cannot offer much active help in form of testing.

**Comment by FRidh** [comment]
A fix is preferred, and otherwise its a revert. I was under the impression it was the interactive change, but did not give it much thought.

I can't test it myself either, like most of us...

**Comment by vcunat** [comment]
Or postpone this whole PR after 20.09?  I can't see why it needs to be in there.  (I can't test Darwin either.)

**Pull request merged**
