### PR TITLE
staging-next 2023-06-11

### PR DESCRIPTION
**Pull request by vcunat**
##### Helpful links

- workflow docs: https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/235556
- - - 
##### Mass breakages
(will be edited based on progress)
- [x] debuginfod
  https://github.com/NixOS/nixpkgs/pull/235618#issuecomment-1585872346
- [x] `python311Packages.yarl` [details below](#issuecomment-1592409206)
- [ ]  `python311Packages.exceptiongroup` https://github.com/agronholm/exceptiongroup/issues/64

### CODE REVIEW

**Comment by vcunat** [comment]
- [ ] `python311Packages.yarl` started to fail some tests (reproducibly).  On all four platforms but not with python 3.10.  Report says this blocks a few thousand builds.  /cc maintainer @dotlambda
  https://hydra.nixos.org/build/224065833/nixlog/2/tail

**Comment by vcunat** [comment]
@lilyinstarlight: `gst_all_1.gst-plugins-rs` regressed on `aarch64-*` ([linux link](https://hydra.nixos.org/build/224296657)).  Maybe rustc or llvm update; I don't know.

**Comment by lilyinstarlight** [comment]
> @lilyinstarlight: `gst_all_1.gst-plugins-rs` regressed on `aarch64-*` ([linux link](https://hydra.nixos.org/build/224296657)). Maybe rustc or llvm update; I don't know.

Ugh, more test failures. Probably easiest to just add raptorq to the list to disable on aarch64 for now on it. I'm computer-less until Tuesday so it would be ideal if someone else can do that to at least unblock it for now

I'll investigate further and open an upstream issue when I'm back at my computer

Thanks for the ping!

**Comment by vcunat** [comment]
- [ ] `nixosTests.sway` hangs exactly since merging this PR, on both platforms.  It's blocking `nixos-unstable` channel.
  /cc maintainers: @primeos, @Synthetica9

**Comment by vcunat** [comment]
> Probably easiest to just add raptorq to the list to disable on aarch64 for now on it.

OK, done.

**Pull request merged**
