### PR TITLE
[r19.09] musl: 1.1.2x -> 1.1.24 (security)

### PR DESCRIPTION
**Pull request by d-goldin**
###### Motivation for this change

I think it's worth considering to backport this fix for 19.09 too, as it's rated as critical.
Addresses: https://github.com/NixOS/nixpkgs/issues/73668

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @dtzWill

### CODE REVIEW

**Review by nh2 — APPROVED** [review]
`nix-review` is happy with this:

```
[58 built, 1735 copied (9701.9 MiB), 1176.3 MiB DL]
https://github.com/NixOS/nixpkgs/pull/73758
1 package are marked as broken and were skipped:
nix-exec

50 package were build:
bundix busybox-sandbox-shell cabal2nix cachix common-updater-scripts crystal2nix dep2nix discover disnix disnixos fusionInventory gnome3.gnome-packagekit gnome3.gnome-software simple-scan go2nix haskellPackages.cachix haskellPackages.nix-paths hydra lispPackages.quicklisp-to-nix lispPackages.quicklisp-to-nix-system-info lorri musl nix nix-bundle nix-du nix-index nix-pin nix-plugins nix-prefetch nix-prefetch-bzr nix-prefetch-cvs nix-prefetch-docker nix-prefetch-git nix-prefetch-hg nix-prefetch-scripts nix-prefetch-svn nix-review nix-serve nix-update-source nixFlakes nixUnstable nixos-generators nixui packagekit packagekit-qt pypi2nix python37Packages.nixpkgs python37Packages.pythonix vgo2nix vulnix
```

**Comment by fpletz** [comment]
Cherry-picked with `-x` (see section in the [nixpkgs manual](https://nixos.org/nixpkgs/manual/#submitting-changes-stable-release-branches)) onto recent release-19.09 and force pushed.

**Comment by fpletz** [comment]
Currently checking if some of the `pkgsStatic` package set still works. @dtzWill should have the final say if we can safely backport this.

**Review by thoughtpolice — APPROVED** [review]

**Review by dtzWill — APPROVED** [review]
LGTM, thanks for backporting!

I'm unaware of anything other than fixes and improvements in this set of upgrades, I think it's safe.  And well motivated by the security fix.

**Comment by d-goldin** [comment]
@dtzWill: Well, there was pretty much zero effort of "backporting", just noticed that this could be useful for 19.09 too, that's all. Thanks for taking a look!

**Pull request merged**
