### PR TITLE
python39Packages.sphinx: 4.3.1 -> 4.4.0, add sphinx maintainer team

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Motivation for this change
I hacked a while on sphinx today for #155973 and thought this would be a good idea. If someone is interested feel free to create a PR to add yourself to the team and give me a ping. If someone wants to move some more sphinx things to the team please do the same.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
python-updates pushed sphinx to 4.3.2

please rebase

**Comment by jonringer** [comment]
one more conflict :(

**Comment by SuperSandro2000** [comment]
I will fix the merge conflict and then merge it.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 155976 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>1 package built:</summary>  <ul>    <li>sphinx</li>  </ul></details>

**Comment by FRidh** [comment]
I think using a team for this is very arbitrary. Let's say I want to maintain Sphinx as well, but not those packages. Does it make sense then that I am not part of the Sphinx team? My question is therefore, what is the *scope* of the Sphinx team, because there are a lot of Sphinx related packages.

**Comment by SuperSandro2000** [comment]
The sphinx team contains all the packages which are a direct dependency of sphinx and are part of sphinx org. Basically sphinx plus https://github.com/sphinx-doc/sphinx/blob/4.x/setup.py#L17-L22. Don't ask me why sphinx has those packages extra but it makes no sense for those packages to not be maintained by sphinx. You also could have inherited meta.maintainers from sphinx but that is maybe a infinite recursion, didn't try.

**Pull request merged**
