### PR TITLE
python-packages: falcon 0.2.0 -> 0.3.0

### PR DESCRIPTION
**Pull request by desiderius**
Tested with Python 2.7, 3.2, 3.3, 3.4 (+cython) & PyPy.

### CODE REVIEW

**Comment by jagajaga** [comment]
Please rename commit's name following our guide from `CONTRIBUTING.md`

**Comment by desiderius** [comment]
I renamed the commit. Thank for your comment. I missed the update about the guidelines.

**Comment by jagajaga** [comment]
Better name it as `falcon: 0.2.0 -> 0.3.0`.

**Comment by desiderius** [comment]
I used the prefix *python-packages* because that is what was commonly used until now. By the way, there is already a package named [falcon](https://github.com/NixOS/nixpkgs/blob/release-14.12/pkgs/development/interpreters/falcon/default.nix#L17).  Is that alright to use an ambiguous name in the commit message ?

**Comment by jagajaga** [comment]
You have a good point for a name.

**Pull request merged**
