### PR TITLE
perlnavigator: init at 0.6.0

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
closes #252821 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by WolfangAukang** [comment]
Unfortunately this is not working for me. I can get it built successfully and helix can indeed find the lsp on `hx --health`, but editing a Perl file does not show anything, and when running the generated binary, I get this:

```
[nix-shell:~/.cache/nixpkgs-review/pr-253163]$ ./results/perlnavigator/bin/perlnavigator
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'vscode-languageserver/node'
Require stack:
- /nix/store/1vrb4s23r4yg34sgfqhk7smhjn10y0mh-perlnavigator-0.6.0/lib/node_modules/perlnavigator/server/out/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/nix/store/1vrb4s23r4yg34sgfqhk7smhjn10y0mh-perlnavigator-0.6.0/lib/node_modules/perlnavigator/server/out/server.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/1vrb4s23r4yg34sgfqhk7smhjn10y0mh-perlnavigator-0.6.0/lib/node_modules/perlnavigator/server/out/server.js'
  ]
}

Node.js v18.17.1
```

**Comment by dotlambda** [comment]
@WolfangAukang Feel free to use my code and fix remaining problems yourself.

**Comment by WolfangAukang** [comment]
Result of `nixpkgs-review pr 253163` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>perlnavigator</li>
  </ul>
</details>

**Comment by WolfangAukang** [comment]
FYI, the last changes you did to the PR (the `postInstall` section) did the trick. Thank you very much!

**Review by WolfangAukang — APPROVED** [review]

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 253163` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>perlnavigator</li>
  </ul>
</details>

**Review by lucasew — APPROVED** [review]

**Pull request merged**
