### PR TITLE
unityhub: update dependency openssl_1_1 -> openssl_3

### PR DESCRIPTION
**Pull request by huantianad**
###### Description of changes
Updates OpenSSL dependency to OpenSSL 3 as per #210452. Seems to work without requiring any package updates, perhaps was enabled by a previous update.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
@ofborg eval

**Comment by huantianad** [comment]
Almost forgot, ill need to double check if the editor itself works with OpenSSL 3

**Comment by headblockhead** [comment]
Hello! Just commenting to say that after this commit, When starting up an older version of Unity (such as Unity 2021.2.17f1) I get 'no usable version of libssl was found'. Downgrading the unity-hub package to nixpkgs afb1ed8 works perfectly.

No action is required - just mentioning for the record.

**Comment by huantianad** [comment]
Yeah unfortunately there's not much we can do about older versions of the unity editor, thankfully newer version do support OpenSSL3.

Another workaround is overriding `extraLibs`, adding `openssl_1_1` to it yourself, if you don't want to pin Unity Hub to an older version.

**Pull request merged**
