### PR TITLE
dwarf-fortress: add dfhack

### PR DESCRIPTION
**Pull request by a1russell**
Originally I opened #10082 in order to add dfhack. That pull request uses the DFHack binary rather than the source code, and I received feedback from @robbinch that I should try to build from source.

Since the diffs are quite different, I put this into a new branch and therefore pull request. If this pull request is favorable to #10082, I'll simply close #10082.

So @robbinch and @the-kenny, I know it took me a while, as my spare time is quite limited, but what do you think of this version?

### CODE REVIEW

**Comment by robbinch** [comment]
I think it's great that this PR builds dfhack from source, and I'll remove dfhack package if this gets merged by @the-kenny or @roconnor.

**Comment by the-kenny** [comment]
From a first look it looks very nice. I don't like the "copy stuff to home" approach that much, but I didn't like that with vanilla dwarf fortress either. We should work against that at some point in the future.

Another thing that slightly bugs me is that dfhack is mixed with DwarfFortress. It might be worth to split them.

That said, I'm going to merge this if everything works (testing that now). My opinion is that it's better to have something working and polish it incrementally rather than working a long time without a visible result.

**Comment by the-kenny** [comment]
After building it with ```nix-build . -A dwarf_fortress``` (*without* DFHack) I get the following error on start:

```
% ./result/bin/dwarf-fortress
+ data_dir=/home/moritz/.local/share/df_linux
+ pkg_dir=/nix/store/1sk2pazh3plwrv70758d6g7nd7armmrq-dwarf-fortress-0.40.24/share/df_linux
+ . /nix/store/1sk2pazh3plwrv70758d6g7nd7armmrq-dwarf-fortress-0.40.24/share/df_linux/shell/install-df-data-to-home.sh
+++ readlink /home/moritz/.local/share/df_linux/raw
++ [[ '' != \/\n\i\x\/\s\t\o\r\e\/\1\s\k\2\p\a\z\h\3\p\l\w\r\v\7\0\7\5\8\d\6\g\7\n\d\7\a\r\m\m\r\q\-\d\w\a\r\f\-\f\o\r\t\r\e\s\s\-\0\.\4\0\.\2\4\/\s\h\a\r\e\/\d\f\_\l\i\n\u\x\/\r\a\w ]]
++ rm -f /home/moritz/.local/share/df_linux/raw
++ ln -s /nix/store/1sk2pazh3plwrv70758d6g7nd7armmrq-dwarf-fortress-0.40.24/share/df_linux/raw /home/moritz/.local/share/df_linux/raw
ln: failed to create symbolic link ‘/home/moritz/.local/share/df_linux/raw’: No such file or directory

```

**Comment by a1russell** [comment]
Thanks @the-kenny for catching that. I'll definitely fix it.

As for the "copy stuff to home" approach, I didn't aim to fix it here, but I'd be glad to tackle it in the future once I have the game actually running the way I like.

For dfhack being in a separate package, #9972 added that. @robbinch said he thought this approach might be better, but honestly either way is fine with me as long as it's easy to the end-user. The problem with #9972 is you have to do some manual installation, I think. I don't like that. If you prefer the packages separate, I could focus on improving that separate package, including some of the refactoring I did as a part of this. It will be quite discouraging, though, to go through a third iteration of this package.

**Comment by the-kenny** [comment]
Thanks for fixing that.

I'm aware that don't-copy-to-home isn't the target here, so that's perfectly fine.

As for #9972: Agreed. Manual steps are quite unfavorable. We just need to keep in mind to keep an upgrade path when we implement the don't-copy-to-home stuff. So don't worry about the separation of packages for now, we can split that later.

**Comment by a1russell** [comment]
@the-kenny I was missing a `mkdir` because that directory already existed for me before I started making the package. Should be fixed now.

**Pull request closed without merging**
