### PR TITLE
Closure size WIP

### PR DESCRIPTION
**Pull request by avnik**
Fix qtile, fvwm and subversion

### CODE REVIEW

**Comment by avnik** [comment]
I am and @lethalman decided to postpone this PR before master will be merged to closure-size, and I rebase stuff on it.

**Comment by vcunat** [comment]
Ping. I pushed a tested version of closure-size with new staging in it. (All packages I use do build.)

**Comment by vcunat** [comment]
And, in the meantime subversion started to build again, so it's possible some parts of this PR won't be needed anymore (and/or will conflict).

**Comment by avnik** [comment]
On Wed, Jan 20, 2016 at 10:51:22AM -0800, Vladimír Čunát wrote:

> And, in the meantime subversion started to build again, 
> so it's possible some parts of this PR won't be needed 
> anymore (and/or will conflict).
> 

I am not sure, if it was common problem, or it unbuildable on
my localhost only. Need to check it separately.

**Comment by vcunat** [comment]
No, at the time of filing this PR I *did* experience svn build problems.

**Comment by avnik** [comment]
On Wed, Jan 20, 2016 at 11:54:37AM -0800, Vladimír Čunát wrote:

> No, at the time of filing this PR I *did* experience svn build
> problems.
> 

Can you tell what problems, and how you fix them?

**Comment by vcunat** [comment]
It didn't build, but I don't remember exactly (it was months ago) and I don't know how they got fixed. Maybe I did pushed something to fix it or someone else did, but I just don't remember anymore :-)

**Comment by avnik** [comment]
On Wed, Jan 20, 2016 at 01:14:07PM -0800, Vladimír Čunát wrote:

> It didn't build, but I don't remember exactly (it was months
> ago) and I don't know how they got fixed. Maybe I did pushed
> something to fix it or someone else did, but I just don't
> remember anymore :-)
> 

Or it just come from cache.
I will try to invalidate my local build (by adding space
somewhere) and look if it build or not.

**Comment by dezgeg** [comment]
Probably the subversion problem was caused by GCC 5 (which closure-size had but no longer seems to have) which had some changes in that area.

**Comment by avnik** [comment]
On Mon, Jan 25, 2016 at 03:51:01PM -0800, Tuomas Tynkkynen wrote:
> Probably the subversion problem was caused by GCC 5 (which closure-size had but no longer seems to have) which had some changes in that area.
> 

In my experiments it fixed by adding 
```
CPPFLAGS="-P";
```

But not sure if it correct solution.

**Comment by avnik** [comment]
On Mon, Jan 25, 2016 at 03:51:01PM -0800, Tuomas Tynkkynen wrote:

> Probably the subversion problem was caused by GCC 5 (which closure-size had but no longer seems to have) which had some changes in that area.
> 

Some comment taken from my own unstaged commit:
```
Mysterious error "configure: error: failed to recognize APR_INT64_T_FMT on this platform" appeared,
usually it appears on OSX, not on linux. Openembedded's forum suggest
CPPFLAGS="-P" to fix it.

Short snippet from svn's autocrap illustrating problematic place:
140           if test "x$svn_cv_pycfmt_apr_int64_t" = "x"; then
141             AC_EGREP_CPP([MaTcHtHiS +\"lld\" +EnDeNd],
142                          [#include <apr.h>
143                           MaTcHtHiS APR_INT64_T_FMT EnDeNd],
144                          [svn_cv_pycfmt_apr_int64_t="L"])
145           fi

I think line numbering can smash this magic, so disable it with `-P`

```

**Comment by vcunat** [comment]
The gcc switch back was done and explained in 9d1343414a. It didn't occur to me as a possible reason why it builds again.

**Comment by avnik** [comment]
Updated branch.
(remove svn stuff, fix build deps for `syslog-ng`)

**Comment by avnik** [comment]
@vcunat  This one can be merged ;)

Next broken things:  qtbase (via postgres's libpq and iodbc), and packages which contain only manpages (stdmanpage) -- but haven't any ideas how to fix them.

Any other packages which I can to fix/test to make whole closure-size merged?

**Comment by vcunat** [comment]
`qtbase` linking to libpq should be fixed by 363f667. I don't see a connection between qt and iodbc in the nix expressions.

**Comment by vcunat** [comment]
The `stdman` problem was that developer documentation (such as `man3`) is now stripped from packages by default or moved into `.docdev` if defined. I passed <nixpkgs/pkgs/data/documentation> in c979012.

**Comment by avnik** [comment]
On Thu, Jan 28, 2016 at 04:39:18AM -0800, Vladimír Čunát wrote:

> `qtbase` linking to libpq should be fixed by 363f667. 
> I don't see a connection between qt and iodbc in the nix
> expressions.
> 

I just see iodbc related error upper in log before libpq's one.

**Comment by vcunat** [comment]
I expect it's an optional dependency that is never fulfilled on any of our branches.

**Comment by avnik** [comment]
On Thu, Jan 28, 2016 at 06:16:14AM -0800, Vladimír Čunát wrote:

> I expect it's an optional dependency that is never fulfilled
> on any of our branches.
> 

Good.
@vcunat have we any issue(-s) with pending tasks to merge closure-size into master?

**Comment by vcunat** [comment]
I'm updating merge blockers (in my opinion) at the top of that PR #7701.

**Pull request merged**
