### PR TITLE
imhex-bin: init at 1.35.4

### PR DESCRIPTION
**Pull request by pcasaretto**
## Description of changes

After failing to [build imhex from source](https://github.com/WerWolv/ImHex/issues/1807#event-13632163534) I'm adding a pre-built option for ImHex for darwin users.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
Would you like help getting it to build from source? I’m not sure how much time I can spare for it but the problems you were getting don’t look like they should be too bad to fix.

**Comment by afh** [comment]
Happy to take a look and possibly help out too if helpful.

**Comment by khaneliman** [comment]
> Would you like help getting it to build from source? I’m not sure how much time I can spare for it but the problems you were getting don’t look like they should be too bad to fix.

Yeah, I was reading through that issue and wondering how long it would take to get the build issues sorted with some assistance from more eyes in the nix space.

**Comment by pcasaretto** [comment]
Absolutely! Everything I tried is documented on the PR.

**Comment by afh** [comment]
Having a draft PR with the source build imhex package would be helpful for collaboration, mind creating one?

**Comment by n8henrie** [comment]
Also happy to help out -- imhex was one of the first projects I ever tried to package for nix, but I failed. Have learned a few things since then, interested to see the approach(es) taken here!

**Comment by afh** [comment]
Please find below my take on a source package for ImHex, based on your amazing work, @pcasaretto. While it does not yet succeed, it may provide some help to continue.

Currently building this fails with:

```
       > warning: cannot resolve item '/usr/lib/libSystem.B.dylib'
       >
       >   possible problems:
       >     need more directories?
       >     need to use InstallRequiredSystemLibraries?
       >     run in install tree instead of build tree?
       >
       > CMake Error at /nix/store/wkpac975pr7mad7mnbjf3dhdf4v6ildv-cmake-3.29.6/share/cmake-3.29/Modules/BundleUtilities.cmake:458 (message):
       >   otool -l failed: 1
       >
       >
       >   /nix/store/y627qxz7qhscidi7c0r2lzzcd0pwg71z-cctools-binutils-darwin-973.0.1/bin/otool:
       >   error: '/usr/lib/libSystem.B.dylib': No such file or directory
```


<details><summary> 👉  <code>pkgs/by-name/im/imhex/package.nix</code></summary>

Note that the package is written, so that the `imhex = …` entry in `pkgs/top-level/all-packages.nix` can be deleted.

```nix
{ lib
, stdenv
, cmake
, darwin
, llvmPackages_17
, fetchFromGitHub
, mbedtls
, gtk3
, pkg-config
, capstone
, dbus
, libGLU
, glfw3
, file
, perl
, python3
, jansson
, curl
, fmt_8
, nlohmann_json
, yara
}:

let
  llvmPackages = llvmPackages_17;
  stdenv' = if stdenv.cc.isClang then llvmPackages.stdenv else stdenv;
  version = "1.35.4";
  patterns_version = "1.35.4";

  patterns_src = fetchFromGitHub {
    owner = "WerWolv";
    repo = "ImHex-Patterns";
    rev = "ImHex-v${patterns_version}";
    hash = "sha256-5a6aFT8R8vMzPS+Y+fcDV5+olhioEpLjdMqa7qOyGsw=";
  };

in
stdenv'.mkDerivation (finalAttrs: {
  pname = "imhex";
  inherit version;

  src = fetchFromGitHub {
    fetchSubmodules = true;
    owner = "WerWolv";
    repo = "imhex";
    rev = "v${finalAttrs.version}";
    hash = "sha256-6QpmFkSMQpGlEzo7BHZn20c+q8CTDUB4yO87wMU5JT4=";
  };

  nativeBuildInputs = [ cmake llvmPackages.llvm python3 perl pkg-config ];

  buildInputs = [
    capstone
    curl
    dbus
    file
    fmt_8
    glfw3
    gtk3
    jansson
    libGLU
    mbedtls
    nlohmann_json
    yara
  ] ++ lib.optionals stdenv.isDarwin [
    darwin.apple_sdk_11_0.frameworks.UniformTypeIdentifiers
  ];

  cmakeFlags = [
    (lib.cmakeBool "IMHEX_OFFLINE_BUILD" true)
    (lib.cmakeBool "IMHEX_COMPRESS_DEBUG_INFO" false) # avoids error: cannot compress debug sections (zstd not enabled)
    (lib.cmakeBool "IMHEX_GENERATE_PACKAGE" stdenv.isDarwin or stdenv.isWindows)
    (lib.cmakeBool "USE_SYSTEM_CAPSTONE" true)
    (lib.cmakeBool "USE_SYSTEM_CURL" true)
    (lib.cmakeBool "USE_SYSTEM_FMT" true)
    (lib.cmakeBool "USE_SYSTEM_LLVM" true)
    (lib.cmakeBool "USE_SYSTEM_NLOHMANN_JSON" true)
    (lib.cmakeBool "USE_SYSTEM_YARA" true)
  ];

  postInstall = ''
    mkdir -p $out/share/imhex
    cp -aR ${patterns_src}/{constants,encodings,includes,magic,patterns} $out/share/imhex
    find $out/share/imhex -name '*_schema.json' -exec rm {} \;
  '';

  meta = with lib; {
    description = "Hex Editor for Reverse Engineers, Programmers";
    homepage = "https://github.com/WerWolv/ImHex";
    license = with licenses; [ gpl2Only ];
    maintainers = with maintainers; [ kashw2 cafkafk ];
    platforms = platforms.linux ++ platforms.darwin;
  };
})
```

</details>

**Comment by emilazy** [comment]
This is irrelevant, but a little nit: please use `lib.platforms.unix` or even `lib.platforms.all` rather than `platforms.linux ++ platforms.darwin`. There’s usually no reason to disenfranchise our FreeBSD‐using friends for a source build.

A PR would be much better for collaboration as we’d have access to the review tools.

**Comment by pcasaretto** [comment]
Here it is! https://github.com/NixOS/nixpkgs/pull/330303

**Comment by afh** [comment]
While conversation and work is ongoing on the [collaborative source PR](https://github.com/NixOS/nixpkgs/pull/330303) mind converting this one to a draft, @pcasaretto? We can always come back to this one later.

**Comment by pcasaretto** [comment]
> Note that the package is written, so that the imhex = … entry in pkgs/top-level/all-packages.nix can be deleted .

@adh would you be so kind as to enlighten me on how you achieved this?

**Comment by afh** [comment]
I'm on a mobile device and cannot easily access your previous so I'm going to answer from memory, which may not be entirely accurate.

The imhex package defined an llvm input, which was overwritten in all-packages nix with llvmPackages_17. In the package I proposed in  previous comment I used llvmPackages_17 directly as an input. That did the trick.

It's seems to be a trade-off where I haven't seen clear guidance from nixpkgs yet.
Either standalone packages below pkgs/by-name or flexibility in overwriting input/dependencies from a single place that is all-packages.nix.
Note that there are packages residing under pkgs/by-name that have their inputs overwritten.

Hopefully I've been able to explain well the approach I've taken, if not, please ask me to clarify and I'll gladly answer in greater detail 🙂

**Pull request closed without merging**
