### PR TITLE
Qtile rework

### PR DESCRIPTION
**Pull request by avnik**
@kamilchm @lethalman, please take a look: is a changes which we discuss in #11219

### CODE REVIEW

**Comment by lethalman** [comment]
I don't use qtile but that seems a nice solution. qtile users should judge better than me.

**Comment by kamilchm** [comment]
I'll try to switch to it today and see it in action :)

**Comment by avnik** [comment]
@lethalman I still thinking about generalized way to save $0 and altered variables in wrapProgram, and put restore_os_environment to sitecustomize.py for example (I think tainting environment by python is more common issue)

**Comment by kamilchm** [comment]
Looks good, works good :+1:

**Comment by avnik** [comment]
Cool, then can someone merge this?

**Pull request merged**
