### PR TITLE
Python package set major updates

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

The package set has not been updated in a while, and now contains significantly outdated packages.

https://hydra.nixos.org/jobset/nixpkgs/python-unstable

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bhipple** [comment]
Looks like a `keyring` might need some tender loving care:

```
builder for '/nix/store/0zp5q9zqra8lngiapk1a1abrfi97g991-python3.7-keyring-21.2.1.drv' failed with exit code 1
cannot build derivation '/nix/store/l3rmr6dz94ijvm9iycd4iqhaparywdk5-python3.7-twine-3.1.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/r3bim58y80gq4r9gl1y05m68yd0my6ip-python3.7-python-daemon-2.2.4.drv': 1 dependencies couldn't be built
```

**Comment by jonringer** [comment]
I'll spend some time stabilizing this

**Comment by jonringer** [comment]
got `azure-cli` `aws-sam-cli` and `nixops` building again

**Comment by jonringer** [comment]
> Will the maintainers of the affected packages be notified in any way?

Most likely not, hydra used to have an email feature, but I believe that has been turned off.

**Comment by FRidh** [comment]
~ 700 more failures, we're getting there :stuck_out_tongue:

**Comment by FRidh** [comment]
~ 500 more failures and 60 removed packages. I think a third to a half is now a direct failure, so that means its only leaf packages that are left.

**Comment by meh** [comment]
This seems to have broken `cheroot`, the tests now fail.

**Pull request merged**
