### PR TITLE
buildDartApplication: Generate Dart wrapper with symlinkJoin

### PR DESCRIPTION
**Pull request by hacker1024**
## Description of changes

This wraps Dart for use in fixed-output vendor derivations with `symlinkJoin` instead of `runCommand`. This allows other binaries installed alongside Dart, such as `flutter`, to remain available.

Closes #263723.

@NixOS/flutter

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by linsui** [comment]
LGTM, thanks! :)

**Comment by linsui** [comment]
https://github.com/NixOS/nixpkgs/blob/d6ada5d880ebdd9ff0a752a4ab4f07231f368fd6/pkgs/build-support/flutter/default.nix#L23

Is this line still needed?

**Comment by hacker1024** [comment]
> https://github.com/NixOS/nixpkgs/blob/d6ada5d880ebdd9ff0a752a4ab4f07231f368fd6/pkgs/build-support/flutter/default.nix#L23
> 
> Is this line still needed?

Yep, otherwise Flutter would not be available when the `sdkSetupScript` and `pubGetScript` portions run.

**Comment by linsui** [comment]
It works for me without that. Flutter is available in "dart" which is already overrided.

**Review by 999eagle — APPROVED** [review]
Tested with a new flutter application I'm packaging. LGTM

**Comment by linsui** [comment]
Any update here?

**Review by FlafyDev — APPROVED** [review]

**Comment by Steinhagen** [comment]
Works well for me as well.

**Pull request merged**
