### PR TITLE
python27Packages.pytestpep8: remove due to pytest v6 incompatibility

### PR DESCRIPTION
**Pull request by drewrisinger**
###### Motivation for this change

Remove ``pythonPackages.pytestpep8`` because:
* It has been abandoned upstream: no PyPi release since 2014: https://pypi.org/project/pytest-pep8/#history
* It is no longer compatible with pytest v6+: I get an error pointing to
  https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent
  when I try to use it with ``pytestCheckHook`` (i.e. pytest v6.0+)
* It doesn't have a maintainer

Removing it will make it clear that it is no longer working, instead of chasing down pytest collection errors when the plugin doesn't work.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by drewrisinger** [comment]
Converting to a draft b/c I didn't realize how widespread its usage is in the tree. It looks like ``pythonPackages.pytestpep8`` only produces a pytest error when pytest is called as ``pytest --pep8``, so maybe it's OK to leave in tree?

E.g. ``python3Packages.mwclient`` builds on ``master``, but adding ``--pep8`` to its checkPhase fails the build.

**Comment by jonringer** [comment]
these could be dated references

most check phases are most likely not making use of it

**Comment by drewrisinger** [comment]
@jonringer is it worth removing it then if the check phase isn't making use of it?

Just asking before I put in the time going through ~20 packages.

**Comment by gebner** [comment]
All of the issues seem to have been addressed.  I'm merging this now because the PR unbreaks `cura`.  Please open a new PR for further improvements.

**Comment by drewrisinger** [comment]
I hadn't finished going through & building everything, so I didn't want to unmark it as a draft quite yet. I'll finish this project sometime later today, probably.

**Pull request merged**
