### PR TITLE
texi2html: Fix cross-platform build

### PR DESCRIPTION
**Pull request by kampka**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kampka** [comment]
@GrahamcOfBorg build texi2html
@GrahamcOfBorg build pkgsCross.aarch64-multiplatfrom.texi2html

**Comment by symphorien** [comment]
maybe you can add `strictDeps = true` to make regressions less likely?
This applies to many of your cross-fixing PRs.

**Comment by kampka** [comment]
@GrahamcOfBorg build texi2html
@GrahamcOfBorg build pkgsCross.aarch64-multiplatform.texi2html

**Comment by kampka** [comment]
> maybe you can add `strictDeps = true` to make regressions less likely?
> This applies to many of your cross-fixing PRs.

Done (other will follow).

**Comment by SuperSandro2000** [comment]
Please target master. This is not a mass rebuild.

**Comment by kampka** [comment]
> Please target master. This is not a mass rebuild.

@SuperSandro2000 can you please for future reference clarify what constitutes as a `mass rebuild` and ideally have that documented clearly (as in 'objectively') in the staging branch section of the nixpkgs manual? I have asked that question multiple times and in different spaces and have never gotten a definitive answer. Thanks.

**Comment by SuperSandro2000** [comment]
> > Please target master. This is not a mass rebuild.
> 
> @SuperSandro2000 can you please for future reference clarify what constitutes as a `mass rebuild` and ideally have that documented clearly (as in 'objectively') in the staging branch section of the nixpkgs manual? I have asked that question multiple times and in different spaces and have never gotten a definitive answer. Thanks.

500+ plus is a mass rebuild.

**Comment by fgaz** [comment]
Anyone knows why @GrahamcOfBorg requested my review? Maybe some recent history (the mindustry updates in particular, since there's @petabyteboy too) got briefly included while switching branch and force pushing?

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 97093` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>btrbk</li>
    <li>frescobaldi</li>
    <li>lilypond-unstable</li>
    <li>udiskie</li>
  </ul>
</details>
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>asciidoc-full</li>
    <li>asciidoc-full-with-plugins</li>
    <li>ccache</li>
    <li>ccacheStdenv</li>
    <li>knightos-genkfs</li>
    <li>knightos-kimg</li>
    <li>knightos-mktiupgrade</li>
    <li>lilypond</li>
    <li>lilypond-with-fonts</li>
    <li>rep</li>
    <li>texi2html</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 97093` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>2 packages failed to build and are new build failures:</summary>
  <ul>
<li>spring: log <a href="https://termbin.com/jxy1">https://termbin.com/jxy1</a></li>
<li>springLobby: log was empty</li>
  </ul>
</details>
<details>
<summary>
35 packages built:
</summary>
<ul>
<li>adapta-gtk-theme</li>
<li>asciidoc-full</li>
<li>asciidoc-full-with-plugins</li>
<li>btrbk</li>
<li>ccache</li>
<li>ccacheStdenv</li>
<li>ccacheWrapper</li>
<li>chrome-gnome-shell</li>
<li>clevis</li>
<li>denemo</li>
<li>disorderfs</li>
<li>frescobaldi</li>
<li>gnome3.gnome-session (gnome3.gnome_session)</li>
<li>gnome3.gnome-shell (gnome3.gnome_shell)</li>
<li>gnome3.gnome-terminal (gnome3.gnome_terminal)</li>
<li>gnome3.gnome-tweaks (gnome3.gnome-tweak-tool)</li>
<li>gnome3.pomodoro</li>
<li>gnomeExtensions.easyScreenCast</li>
<li>gnomeExtensions.gsconnect</li>
<li>gnomeExtensions.night-theme-switcher</li>
<li>herbstluftwm</li>
<li>knightos-genkfs</li>
<li>knightos-kimg</li>
<li>knightos-mkrom</li>
<li>knightos-mktiupgrade</li>
<li>lilypond</li>
<li>lilypond-unstable</li>
<li>lilypond-with-fonts</li>
<li>luksmeta</li>
<li>pantheon.elementary-session-settings</li>
<li>rep</li>
<li>solfege</li>
<li>tang</li>
<li>texi2html</li>
<li>udiskie</li>
</ul>
</details>

**Comment by petabyteboy** [comment]
> Anyone knows why @GrahamcOfBorg requested my review? Maybe some recent history (the mindustry updates in particular, since there's @petabyteboy too) got briefly included while switching branch and force pushing?

Yes, one commit that was pushed to the branch, https://github.com/NixOS/nixpkgs/commits/0fd3afc1b2fb053d6b6f67db659b0a236d60cbf8, also contains a mindustry change, but it's not included in the diff anymore.

**Pull request merged**
