### PR TITLE
uriparser: 0.9.0 backport to 18.09

### PR DESCRIPTION
**Pull request by periklis**
###### Motivation for this change
Backport request for #49274 

cc @jtojnar

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by c0bw3b** [comment]
Did you intend to embed the two other commits for `gmock` and `gtest` ?

**Comment by periklis** [comment]
@c0bw3b Yes, because uriparser depends on googletest from 0.9.0 on. See #49310 and #49306

**Comment by samueldr** [comment]
@GrahamcOfBorg build uriparser mumble mxnet

**Review by samueldr — APPROVED** [review]
`uriparser` itself builds fine. AFAICT there's nothing depending on `uriparser`, which makes the security issue much less pressing.

The annoying amount of rebuilds seems to be entirely based on how `gtest` is used much more. Though picking a random sampling (`mumble` and `mxnet`) it seems to work right here.

(Approving before ofborg finishes building, chances are IMHO low it would fail on other platforms.)

**Comment by samueldr** [comment]
And due to the noise from the failure (multiple unverified attributes on aarch64) let's confirm for `uriparser` :/

@GrahamcOfBorg build uriparser

**Comment by samueldr** [comment]
Sorry for the noise!

**Comment by edolstra** [comment]
Commit ff43959e75c24535b34e9dec0b381918b7854819 breaks movit: https://hydra.nixos.org/build/83867621.

**Comment by jtojnar** [comment]
@edolstra https://github.com/NixOS/nixpkgs/commit/6daa1938b69486dfc75600253ee3878702c604ea needs backport as well.

**Comment by edolstra** [comment]
@jtojnar Thanks, done.

**Pull request merged**
