### PR TITLE
notmuch-bower: 0.10 -> 0.11

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

https://github.com/wangp/bower/blob/0.11/NEWS

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @erictapen

### CODE REVIEW

**Comment by mmahut** [comment]
When trying to run ``bower`` it doesn't find notmuch:

```
# ./bower 
/bin/sh: line 0: exec: notmuch: not found
Errors in configuration file:
process returned with exit code 127
could not derive default from_address from .notmuch-config
```

**Comment by erictapen** [comment]
@mmahut It doesn't make sense to use `notmuch-bower` without `notmuch` so I guess that is not a problem.

For me this works, thanks for the bump, @dtzWill!

**Comment by mmahut** [comment]
@erictapen should that be taken as a dependency then?

**Comment by erictapen** [comment]
@mmahut From the `notmuch-bower` [Readme](https://github.com/wangp/bower):

> Bower is designed such that it can be run on the local machine but call out to notmuch on a remote machine (that holds your mail) via ssh. The advantage is that you can start helper programs on the local machine (e.g. a web browser or image viewer), and add or save attachments on the local filesystem, even if your mail archive is stored on a different machine.

So I guess that usecase doesn't need a locally installed `notmuch`. In case you still think `notmuch` should be installed could you open another issue for this? The behaviour you describe has been the case for all former versions of notmuch-bower.

**Comment by mmahut** [comment]
@erictapen I see, thank you for explanation!

**Comment by Ma27** [comment]
Built and tested locally :+1:

**Comment by Ma27** [comment]
@dtzWill thanks!

**Pull request merged**
