### PR TITLE
python310Packages.tensorflow-bin: 2.13.0 -> 2.15.0

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Update `tensorflow-bin` to `2.15.0`.
Changelog: https://github.com/tensorflow/tensorflow/releases/tag/v2.15.0

cc @jyp @abbradar 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Currently, the installation fails:
```
AttributeError: module 'ml_dtypes' has no attribute 'float8_e4m3b11'. Did you mean: 'float8_e4m3fn'?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "/nix/store/pzf6dnxg8gf04xazzjdwarm7s03cbrgz-python3-3.10.12/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/4pcdqpn2asn90qk1r8ckf27bim9g34a4-python3.10-tensorflow-2.14.0/lib/python3.10/site-packages/tensorflow/__init__.py", line 38, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/nix/store/4pcdqpn2asn90qk1r8ckf27bim9g34a4-python3.10-tensorflow-2.14.0/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 42, in <module>
    from tensorflow.python.saved_model import saved_model
  File "/nix/store/4pcdqpn2asn90qk1r8ckf27bim9g34a4-python3.10-tensorflow-2.14.0/lib/python3.10/site-packages/tensorflow/python/saved_model/saved_model.py", line 20, in <module>
    from tensorflow.python.saved_model import builder
  File "/nix/store/4pcdqpn2asn90qk1r8ckf27bim9g34a4-python3.10-tensorflow-2.14.0/lib/python3.10/site-packages/tensorflow/python/saved_model/builder.py", line 23, in <module>
    from tensorflow.python.saved_model.builder_impl import _SavedModelBuilder
  File "/nix/store/4pcdqpn2asn90qk1r8ckf27bim9g34a4-python3.10-tensorflow-2.14.0/lib/python3.10/site-packages/tensorflow/python/saved_model/builder_impl.py", line 26, in <module>
    from tensorflow.python.framework import dtypes
  File "/nix/store/4pcdqpn2asn90qk1r8ckf27bim9g34a4-python3.10-tensorflow-2.14.0/lib/python3.10/site-packages/tensorflow/python/framework/dtypes.py", line 39, in <module>
    _np_float8_e5m2 = pywrap_ml_dtypes.float8_e5m2()
TypeError: Unable to convert function return value to a Python type! The signature was
        () -> handle
```

While I don't exactly see the link between the `AttributeError` and the rest of the traceback, I guess that this is related to a recent deprecation in `ml-dtypes`.
Tensorflow [has pinned `ml-dtypes` to 2.0.0](https://github.com/tensorflow/tensorflow/pull/61943).
This has also been reported in [jax](https://github.com/google/jax/issues/17693) and [tensorflow-onnx](https://github.com/onnx/tensorflow-onnx/issues/2245).

**Comment by alyssais** [comment]
@OfBorg eval

**Review by mihaimaruseac — APPROVED** [review]

**Comment by samuela** [comment]
Thanks for explaining @mihaimaruseac ! Sounds like we can just wait until the next release then

**Comment by GaetanLepage** [comment]
Thanks @mihaimaruseac !
Indeed, we will wait for the next release.

**Comment by GaetanLepage** [comment]
`tensorflow` builds fine for me on x86, with and without CUDA.
If all the versions/flavors build fine, **I would plead to merge this ASAP.**
Indeed, several packages are broken as they depend on TF. Furthermore, this could let us update many packages in the python ecosystem.

**Comment by mihaimaruseac** [comment]
Note that due to some confusion, master branch now also have the pin:

https://github.com/tensorflow/tensorflow/blob/c8b5e2b0d9d91ff199a5eeb30ec2f5d33a5d92c6/tensorflow/tools/pip_package/setup.py#L92

Since 2.15 branch has been cut already, this likely means that TensorFlow 2.15 will suffer from the same problem.

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 258546` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>34 packages built:</summary>
  <ul>
    <li>libretranslate (python311Packages.libretranslate)</li>
    <li>libretranslate.dist (python311Packages.libretranslate.dist)</li>
    <li>python310Packages.argos-translate-files</li>
    <li>python310Packages.argos-translate-files.dist</li>
    <li>python310Packages.argostranslate</li>
    <li>python310Packages.argostranslate.dist</li>
    <li>python310Packages.ctranslate2</li>
    <li>python310Packages.ctranslate2.dist</li>
    <li>python310Packages.faster-whisper</li>
    <li>python310Packages.faster-whisper.dist</li>
    <li>python310Packages.libretranslate</li>
    <li>python310Packages.libretranslate.dist</li>
    <li>python310Packages.tensorflow-bin</li>
    <li>python310Packages.tensorflow-bin.dist</li>
    <li>python310Packages.translatehtml</li>
    <li>python310Packages.translatehtml.dist</li>
    <li>python311Packages.argos-translate-files</li>
    <li>python311Packages.argos-translate-files.dist</li>
    <li>python311Packages.argostranslate</li>
    <li>python311Packages.argostranslate.dist</li>
    <li>python311Packages.ctranslate2</li>
    <li>python311Packages.ctranslate2.dist</li>
    <li>python311Packages.faster-whisper</li>
    <li>python311Packages.faster-whisper.dist</li>
    <li>python311Packages.tensorflow-bin</li>
    <li>python311Packages.tensorflow-bin.dist</li>
    <li>python311Packages.translatehtml</li>
    <li>python311Packages.translatehtml.dist</li>
    <li>tts</li>
    <li>tts.dist</li>
    <li>whisper-ctranslate2</li>
    <li>whisper-ctranslate2.dist</li>
    <li>wyoming-faster-whisper</li>
    <li>wyoming-faster-whisper.dist</li>
  </ul>
</details>

**Review by samuela — APPROVED** [review]
diff LGTM!

**Comment by GaetanLepage** [comment]
Any change request ? I guess that this is ready to be merged :)

**Comment by samuela** [comment]
LGTM, if no one objects I'll merge tomorrow?

**Review by SomeoneSerge — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Looks good to me too, ok with merging

**Comment by samuela** [comment]
Thanks @GaetanLepage !

**Pull request merged**
