### PR TITLE
pythonPackages.django-debug-toolbar: 3.2.4 -> 3.4

### PR DESCRIPTION
**Pull request by yuuyins**
###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yuuyins** [comment]
can someone test the `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`?

**Comment by fabaff** [comment]
```bash
error: builder for '/nix/store/rkziazqqjc9hs6jg14w903c2f91g9fj9-python3.9-django-debug-toolbar-3.4.drv' failed with exit code 1;
       last 10 log lines:
       >     await asyncio.create_task(task())
       >   File "/build/source/tests/panels/test_sql.py", line 109, in task
       >     await sync_to_async(sql_call)()
       > AssertionError: SQLQueryTriggered not raised
       >
       > ----------------------------------------------------------------------
       > Ran 138 tests in 2.778s
       >
       > FAILED (failures=1, skipped=13)
       > Destroying test database for alias 'default'...
       For full logs, run 'nix log /nix/store/rkziazqqjc9hs6jg14w903c2f91g9fj9-python3.9-django-debug-toolbar-3.4.drv'.
```

**Comment by yuuyins** [comment]
@fabaff ah i'm sorry i thought i had built it successfully.

**Comment by yuuyins** [comment]
https://github.com/jazzband/django-debug-toolbar/pull/1615
https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-python/django-debug-toolbar/django-debug-toolbar-3.4.ebuild
https://devmanual.gentoo.org/eclass-reference/python-r1.eclass/index.html

**Comment by yuuyins** [comment]
I'm trying to [pythonPackages.django-debug-toolbar: 3.2.4 -> 3.4](https://github.com/NixOS/nixpkgs/pull/171764). check phase failes with

```sh
python3.9-django-debug-toolbar> shrinking RPATHs of ELF executables and libraries in /nix/store/s3j82nksp55mlwpixriscybsvfz99ws2-python3.9-django-debug-toolbar-3.4
python3.9-django-debug-toolbar> strip is /nix/store/k0np19xv7wjc1grhrb2y6r85qiv1cikd-gcc-wrapper-11.2.0/bin/strip
python3.9-django-debug-toolbar> stripping (with command strip and flags -S) in /nix/store/s3j82nksp55mlwpixriscybsvfz99ws2-python3.9-django-debug-toolbar-3.4/lib
python3.9-django-debug-toolbar> patching script interpreter paths in /nix/store/s3j82nksp55mlwpixriscybsvfz99ws2-python3.9-django-debug-toolbar-3.4
python3.9-django-debug-toolbar> checking for references to /build/ in /nix/store/s3j82nksp55mlwpixriscybsvfz99ws2-python3.9-django-debug-toolbar-3.4...
python3.9-django-debug-toolbar> Executing pythonRemoveTestsDir
python3.9-django-debug-toolbar> Finished executing pythonRemoveTestsDir
python3.9-django-debug-toolbar> running install tests
python3.9-django-debug-toolbar> Creating test database for alias 'default'...
python3.9-django-debug-toolbar> System check identified no issues (0 silenced).
python3.9-django-debug-toolbar> ................................................F...ss....s.....s.s...............................s............................sssssss....
python3.9-django-debug-toolbar> ======================================================================
python3.9-django-debug-toolbar> FAIL: test_cursor_wrapper_asyncio_ctx (tests.panels.test_sql.SQLPanelTestCase)
python3.9-django-debug-toolbar> ----------------------------------------------------------------------
python3.9-django-debug-toolbar> Traceback (most recent call last):
python3.9-django-debug-toolbar>   File "/nix/store/54cz3yrllb9b2bgwkrf3kxrcr0z8yj79-python3.9-asgiref-3.5.0/lib/python3.9/site-packages/asgiref/sync.py", line 204, in __call__
python3.9-django-debug-toolbar>     return call_result.result()
python3.9-django-debug-toolbar>   File "/nix/store/33hlmb4afkk7l2fapfik80m6yknjxq10-python3-3.9.12/lib/python3.9/concurrent/futures/_base.py", line 439, in result
python3.9-django-debug-toolbar>     return self.__get_result()
python3.9-django-debug-toolbar>   File "/nix/store/33hlmb4afkk7l2fapfik80m6yknjxq10-python3-3.9.12/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
python3.9-django-debug-toolbar>     raise self._exception
python3.9-django-debug-toolbar>   File "/nix/store/54cz3yrllb9b2bgwkrf3kxrcr0z8yj79-python3.9-asgiref-3.5.0/lib/python3.9/site-packages/asgiref/sync.py", line 270, in main_wrap
python3.9-django-debug-toolbar>     result = await self.awaitable(*args, **kwargs)
python3.9-django-debug-toolbar>   File "/nix/store/33hlmb4afkk7l2fapfik80m6yknjxq10-python3-3.9.12/lib/python3.9/unittest/mock.py", line 1353, in patched
python3.9-django-debug-toolbar>     return await func(*newargs, **newkeywargs)
python3.9-django-debug-toolbar>   File "/build/source/tests/panels/test_sql.py", line 112, in test_cursor_wrapper_asyncio_ctx
python3.9-django-debug-toolbar>     await asyncio.create_task(task())
python3.9-django-debug-toolbar>   File "/build/source/tests/panels/test_sql.py", line 109, in task
python3.9-django-debug-toolbar>     await sync_to_async(sql_call)()
python3.9-django-debug-toolbar> AssertionError: SQLQueryTriggered not raised
python3.9-django-debug-toolbar> ----------------------------------------------------------------------
python3.9-django-debug-toolbar> Ran 138 tests in 3.773s
python3.9-django-debug-toolbar> FAILED (failures=1, skipped=13)
python3.9-django-debug-toolbar> Destroying test database for alias 'default'...
```

https://github.com/jazzband/django-debug-toolbar/blob/1d6c953b5554058ac563a56dfded6a9124063606/tests/panels/test\_sql.py#L108, added on https://github.com/jazzband/django-debug-toolbar/pull/1615/files

```sh
    async def test_cursor_wrapper_asyncio_ctx(self, mock_wrapper):
        self.assertTrue(sql_tracking.allow_sql.get())
        await sync_to_async(sql_call)()

        async def task():
            sql_tracking.allow_sql.set(False)
            # By disabling sql_tracking.allow_sql, we are indicating that any
            # future SQL queries should be stopped. If SQL query occurs,
            # it raises an exception.
            with self.assertRaises(sql_tracking.SQLQueryTriggered):
                await sync_to_async(sql_call)()
```

so it seems a query is going on here but it shouldn't so the test fails? Upstream didn't provide an explanation, so i'm supposing this is an issue on the nix derivation side.

**Comment by yuuyins** [comment]
https://github.com/NixOS/nixpkgs/pull/178240

**Pull request closed without merging**
