### PR TITLE
portaudio: remove Werror

### PR DESCRIPTION
**Pull request by hexagonal-sun**
###### Motivation for this change

This implements @Mindavi's suggestion mentioned in #131550.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
And why are new compilers bringing new errors a problem? That way it's possible to keep track of problems and explicitly blacklist known stuff.

**Comment by Mindavi** [comment]
Werror is just too strict, it's handy for dev work but it's annoying for downstreams that just want to use the package without having to deal with fallout on every compiler upgrade. Why keep doing extra work that doesn't bring any value (IMO)?

**Comment by r-burns** [comment]
Compiler warnings are always upstream issues. It's not nixpkgs' fault that some package is triggering -Werror=implicit-whatever, and fixing these isn't relevant to our job as packagers IMO.

**Comment by Ma27** [comment]
> Werror is just too strict, it's handy for dev work but it's annoying for downstreams that just want to use the package without having to deal with fallout on every compiler upgrade. Why keep doing extra work that doesn't bring any value (IMO)?

If upstream has an erroneously `-Werror` that doesn't even work, why can't we patch it there?

**Comment by Mindavi** [comment]
I do agree that we could take it upstream and ask for:

1. A flag to disable Werror
2. Them to disable Werror for normal builds

**Comment by Mic92** [comment]
> > Werror is just too strict, it's handy for dev work but it's annoying for downstreams that just want to use the package without having to deal with fallout on every compiler upgrade. Why keep doing extra work that doesn't bring any value (IMO)?
> 
> If upstream has an erroneously `-Werror` that doesn't even work, why can't we patch it there?

They use pesky autotools, which does not have a notion of release vs debug builds.

**Comment by Be-ing** [comment]
> They use pesky autotools

My [CMake rewrite](https://github.com/PortAudio/portaudio/pull/461) was merged just recently. I do not know when it will be released though.

**Pull request merged**
