### PR TITLE
firefox: Prefix $PATH with xdg_utils

### LINKED ISSUE #92751: Setting browsers (Firefox, Chromium) as default have no effect in Sway.
**Describe the bug**
"Set browser as default" functionality doesn't work for Firefox and Chromium in Sway. (bspwm and other x11 wms worked)

**Additional context**
If I have xdg_utils installed globally, it works as expected.

**Notify maintainers**
xdg_utils & firefox:
@edolstra
firefox:
@andir

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/d43v6bx7r6fcaq3fbbfd5mwh1f5s7rmg-bash-interactive-4.4-p23-dev
copying path '/nix/store/d43v6bx7r6fcaq3fbbfd5mwh1f5s7rmg-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.7, NixOS, 20.03.2459.c9d124e39db (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2459.c9d124e39db, nixos-unstable-20.09pre228622.029a5de0839"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by ryneeverett**
###### Motivation for this change

Resolve #92751.

Comparable to #96922.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
> Firefox is currently your default browser

:heart:

**Review by mweinelt — APPROVED** [review]

**Comment by ryneeverett** [comment]
> Edit: testing this messed up my browser profile … wow.

Yikes. I'm guessing this is the result of another firefox patch that landed in master yesterday.

**Comment by ryneeverett** [comment]
https://github.com/NixOS/nixpkgs/pull/91724

**Comment by mweinelt** [comment]
Can you please add a motivation to your commit message, so that we don't need to rely on GitHub history to follow the intent of your commit.

**Comment by symphorien** [comment]
@GrahamcOfBorg firefox

**Comment by symphorien** [comment]
ah oops
@grahamcofborg build firefox

**Review by mweinelt — APPROVED** [review]

**Comment by mweinelt** [comment]
I've run with this for close to a week. Thanks!

**Comment by erictapen** [comment]
Backported this in 1b5f6503521233e98d109b425675d0a2d13e1268.

**Pull request merged**
