### PR TITLE
FreeBSD support

### PR DESCRIPTION
**Pull request by ysangkok**
This adds FreeBSD support by e.g. making bzip2's build-script use `cc` instead of `gcc`. This means that the result may be different for Linux systems that have `cc` linked to `clang` instead of `gcc`.

Not all packages build on FreeBSD yet, but I hope to work on this at NixCon.

### CODE REVIEW

**Comment by AndersonTorres** [comment]
It's good to know! I also want to port NixOS to NetBSD, so I will watch your efforts.

**Comment by ysangkok** [comment]
I don't think I can do anything about these CI failures, looks like it is just timing out cause the build takes too long?

**Comment by ysangkok** [comment]
@AndersonTorres Maybe we could merge the NetBSD and FreeBSD porting efforts, I guess it is mostly just replacing "isFreeBSD" with "isFreeBSD || isNetBSD". You could take the FreeBSD patch for nix and use it with this nixpkgs, and it might work. Then we could merge it together.

**Comment by domenkozar** [comment]
cc @tomster

**Comment by AndersonTorres** [comment]
@ysangkok there is some support for NetBSD or FreeBSD on Nix itself?

**Comment by ysangkok** [comment]
Currently there is incomplete support for FreeBSD in Nix, but I am expecting mjacob's patch to get merged.

Build farm sounds like a good idea, but what exactly needs to be designed? I can sponsor a jail if needed.

**Comment by ysangkok** [comment]
This depends on https://github.com/NixOS/nix/pull/657 so maybe we should wait until that is merged...

**Comment by AndersonTorres** [comment]
A thing: are you testing it using clang and llvm stack? They are the preferred ones on FreeBSD nowadays.

**Comment by ysangkok** [comment]
@AndersonTorres yes, I am using clang/llvm. But, I will push some commits switching to coreutils, since nixpkgs depend on them for patching binary files with patch(1). The manual also mentions coreutils. But on NixCon it seemed that there was consensus for making a pure stdenv for FreeBSD, which would be cross-compiled with a Linux-type compiler (which would also run on FreeBSD if binary emulation was working). That stdenv would then probably use gcc since this is what other pure stdenv's use.

**Comment by vcunat** [comment]
Just for the record, the new darwin (almost pure) stdenv uses clang.

**Comment by ysangkok** [comment]
Ok, I stand corrected. But currently I am not focusing on the pure stdenv anyway, and most issues seem related to the use of clang. For example, this is the issue I am currenly trying to work around: https://mariadb.atlassian.net/browse/MDEV-5944

**Comment by ysangkok** [comment]
@nbp How would you like me to document this?

**Comment by nbp** [comment]
@domenkozar should we add a release note section to the Nixpkgs manual?

**Comment by nbp** [comment]
@ysangkok I was thinking of having a section of supported platforms in the Nixpkgs manual, where Linux, Darwin and Cygwin would already be listed, but I do not see any.  If you want to add such documentation in a separate issue I would be fine too, as there is no existing documentation in place.

**Comment by vcunat** [comment]
That depends what's meant by "supported". On Hydra.nixos.org we have CI only for three platforms currently (two Linux and one Darwin). For the rest the state might tend to rot (or we might not know), I'm afraid, and even the Darwin support level doesn't seem to be first-class yet.

**Comment by ysangkok** [comment]
@vcunat Bitcoin is building and runs now, I am satisfied with this and would like to get it reviewed for merging.

**Comment by vcunat** [comment]
OK, queued in my TODO ;-)

**Comment by eliask** [comment]
I tested building some stuff on FreeBSD 11.0-CURRENT and can attest that the workaround for m4 is also required for it (clang 3.7.0).

In 11.0-CURRENT and m4, make check only fails for test 189 (but not for 084 as with FreeBSD 10).
I tested this with the package from the ports tree too and got the same result, so clearly this is not specific to the Nix package.

**Comment by ysangkok** [comment]
@vcunat I rebased onto current master.

**Comment by vcunat** [comment]
The `stdenvNative` changes (in pkgs/stdenv/native/default.nix) seem useless now that `stdenvFreeBSD` is used instead. It's used by cygwin, for example, and it isn't clear to me if it would be broken by those changes (the alias targets might not be provided).

**Comment by ysangkok** [comment]
@vcunat I undid those changes now, you are right, they were unnecessary.

**Comment by vcunat** [comment]
While testing this, `cyrus_sasl` wouldn't build on x86_64-linux; for now I've made the fetched patch and `autoreconfHook` conditional.

**Comment by vcunat** [comment]
Staged.

**Comment by ysangkok** [comment]
Thanks!

**Comment by FlorianHeigl** [comment]
@vcunat I'm also happy to help build-farm wise, whenever it's time.

**Comment by vcunat** [comment]
@FlorianHeigl: You mean providing binaries for freebsd in some way?

**Pull request closed without merging**
