### PR TITLE
glew110: fix cross compiling

### PR DESCRIPTION
**Pull request by RossComputerGuy**
## Description of changes

Fixes cross compiling of glew110

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by NickCao — COMMENTED** [review]
Instead of patching we can simply do:
```diff
--- a/pkgs/development/libraries/glew/1.10.nix
+++ b/pkgs/development/libraries/glew/1.10.nix
@@ -40,6 +40,8 @@ stdenv.mkDerivation (finalAttrs: {

   makeFlags = [
     "SYSTEM=${if stdenv.hostPlatform.isMinGW then "mingw" else stdenv.hostPlatform.parsed.kernel.name}"
+    "CC:=$(CC)"
+    "LD:=$(CC)"
   ];

   passthru.tests.pkg-config = testers.testMetaPkgConfig finalAttrs.finalPackage;
```

**Comment by RossComputerGuy** [comment]
> Instead of patching we can simply do:
> 
> ```diff
> --- a/pkgs/development/libraries/glew/1.10.nix
> +++ b/pkgs/development/libraries/glew/1.10.nix
> @@ -40,6 +40,8 @@ stdenv.mkDerivation (finalAttrs: {
> 
>    makeFlags = [
>      "SYSTEM=${if stdenv.hostPlatform.isMinGW then "mingw" else stdenv.hostPlatform.parsed.kernel.name}"
> +    "CC:=$(CC)"
> +    "LD:=$(CC)"
>    ];
> 
>    passthru.tests.pkg-config = testers.testMetaPkgConfig finalAttrs.finalPackage;
> ```

Does that work when CC and LD are declared like [this](https://github.com/nigels-com/glew/blob/glew-1.10.0/config/Makefile.linux)?

**Comment by NickCao** [comment]
> Does that work when CC and LD are declared like [this](https://github.com/nigels-com/glew/blob/glew-1.10.0/config/Makefile.linux)?

Yes.

**Comment by NickCao** [comment]
@ofborg build pkgsCross.aarch64-multiplatform.glew110

**Review by NickCao — APPROVED** [review]

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 314452` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>fspy</li>
    <li>golden-cheetah-bin</li>
    <li>itch</li>
  </ul>
</details>
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>appimage-run-tests</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>badlion-client</li>
  </ul>
</details>
<details>
  <summary>125 packages built:</summary>
  <ul>
    <li>Sylk</li>
    <li>altair</li>
    <li>alvr</li>
    <li>anki-bin</li>
    <li>anytype</li>
    <li>appimage-run</li>
    <li>arduino-ide</li>
    <li>bazecor</li>
    <li>beekeeper-studio</li>
    <li>beeper</li>
    <li>betterdiscord-installer</li>
    <li>bino3d</li>
    <li>bloomrpc</li>
    <li>bootstrap-studio</li>
    <li>buttercup-desktop</li>
    <li>caido</li>
    <li>caprine-bin</li>
    <li>chrysalis</li>
    <li>cider</li>
    <li>clockify</li>
    <li>codux</li>
    <li>cozy-drive</li>
    <li>crypto-org-wallet</li>
    <li>davinci-resolve</li>
    <li>davinci-resolve-studio</li>
    <li>deskreen</li>
    <li>devdocs-desktop</li>
    <li>electron-mail</li>
    <li>electronplayer</li>
    <li>fflogs</li>
    <li>firefly-desktop</li>
    <li>flexoptix-app</li>
    <li>fluent-reader</li>
    <li>framesh</li>
    <li>game-rs</li>
    <li>glew110</li>
    <li>glew110.dev</li>
    <li>hamsket</li>
    <li>hifile</li>
    <li>hoppscotch</li>
    <li>httpie-desktop</li>
    <li>immersed-vr</li>
    <li>insomnia</li>
    <li>irccloud</li>
    <li>jan</li>
    <li>jbrowse</li>
    <li>jetbrains-toolbox</li>
    <li>joplin-desktop</li>
    <li>kchat</li>
    <li>keet</li>
    <li>kmeet</li>
    <li>kodiPackages.steam-launcher</li>
    <li>lbry</li>
    <li>ldtk</li>
    <li>ledger-live-desktop</li>
    <li>lens</li>
    <li>listen1</li>
    <li>lmstudio</li>
    <li>losslesscut-bin</li>
    <li>lunar-client</li>
    <li>lunatask</li>
    <li>lutris</li>
    <li>marktext</li>
    <li>mathpix-snipping-tool</li>
    <li>mendeley</li>
    <li>minigalaxy</li>
    <li>minigalaxy.dist</li>
    <li>miru</li>
    <li>mobilecoin-wallet</li>
    <li>mockoon</li>
    <li>molotov</li>
    <li>motrix</li>
    <li>mqttx</li>
    <li>museeks</li>
    <li>mycrypto</li>
    <li>neo4j-desktop</li>
    <li>nosql-workbench</li>
    <li>notable</li>
    <li>notesnook</li>
    <li>notion-app-enhanced</li>
    <li>nuclear</li>
    <li>openlens</li>
    <li>osu-lazer-bin</li>
    <li>p3x-onenote</li>
    <li>parsify</li>
    <li>playonlinux</li>
    <li>plexamp</li>
    <li>polypane</li>
    <li>protontricks</li>
    <li>protontricks.dist</li>
    <li>protonup-qt</li>
    <li>pureref</li>
    <li>rambox</li>
    <li>raven-reader</li>
    <li>remnote</li>
    <li>requestly</li>
    <li>saleae-logic-2</li>
    <li>session-desktop</li>
    <li>simplex-chat-desktop</li>
    <li>sonixd</li>
    <li>spacedrive</li>
    <li>ssb-patchwork</li>
    <li>station</li>
    <li>steam (steamPackages.steam-fhsenv)</li>
    <li>steam-rom-manager</li>
    <li>steam-run</li>
    <li>steam-small (steamPackages.steam-fhsenv-small)</li>
    <li>steam-tui</li>
    <li>steamPackages.steam-fhsenv-without-steam</li>
    <li>steamcmd (steamPackages.steamcmd)</li>
    <li>timeular</li>
    <li>todoist-electron</li>
    <li>trezor-suite</li>
    <li>tusk</li>
    <li>tutanota-desktop</li>
    <li>upscayl</li>
    <li>via</li>
    <li>vial</li>
    <li>wootility</li>
    <li>wowup-cf</li>
    <li>xivlauncher</li>
    <li>xlights</li>
    <li>zecwallet-lite</li>
    <li>zettlr</li>
    <li>zulip</li>
  </ul>
</details>

Only failure is an unrelated hash mismatch.

**Pull request merged**
