### PR TITLE
nixos/pipewire: add pkgs.pulseaudio to pipewire-pulse user unit path

### PR DESCRIPTION
**Pull request by lilyinstarlight**
###### Description of changes

Add `pkgs.pulseaudio` to pipewire-pulse systemd user unit per https://github.com/NixOS/nixpkgs/pull/165125#issuecomment-1100830655

This removes `pactl` errors from logs and ostensibly would fix the fallback null sink Pulseaudio compatibility behavior, if anyone is using that (since that's all it would affect and the error is otherwise harmless - see https://github.com/NixOS/nixpkgs/pull/160482#discussion_r827182135)

Supersedes and closes #165125

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by klemensn — APPROVED** [review]
FWIW, the error in question is
```
Jun 14 17:16:39 <hostname> pipewire-pulse[9091]: pw.conf: execvp error 'pactl': No such file or directory
```
caused by
https://github.com/NixOS/nixpkgs/blob/69443b19b8aa329b7f415e2ed6254c1c916254f3/nixos/modules/services/desktops/pipewire/daemon/pipewire-pulse.conf.json#L37

**Comment by lilyinstarlight** [comment]
I just pushed an update to add a `lib.mkIf cfg.pulse.enable` guard to this change, since not everyone will have pipewire-pulse enabled and may not have the user unit

**Comment by lilyinstarlight** [comment]
> There's more to enable conditionally if yo go that route

I'll let @jansol comment on whether more conditionals should be added elsewhere in the module, but for this PR the systemd unit won't exist unless `services.pipewire.pulse.enable = true` since it's in a separate `pipewire.pulse` package that gets conditionally added

**Comment by jansol** [comment]
AFAIK the pipewire-pulse config file doesn't really need to exist when pulse support is not enabled so I'm okay with only creating it conditionally.

**Review by klemensn — APPROVED** [review]

**Review by jansol — APPROVED** [review]

**Review by SuperSandro2000 — APPROVED** [review]

**Review by jonringer — APPROVED** [review]

**Comment by jonringer** [comment]
much better than trying to solve it at the package level

**Pull request merged**
