### PR TITLE
[20.09] rocksdb: 6.10.2 -> 6.12.7

### PR DESCRIPTION
**Pull request by basvandijk**
###### Motivation for this change

https://github.com/facebook/rocksdb/blob/v6.12.7/HISTORY.md#6127-2020-10-14

###### Things done

Cherry-picked https://github.com/NixOS/nixpkgs/pull/101559 on `release-20.09`.

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by basvandijk** [comment]
Result of `nixpkgs-review pr 102401` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>bareos</li>
  </ul>
</details>
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>blockbook</li>
    <li>ceph (ceph-dev)</li>
    <li>ceph-client</li>
    <li>haskellPackages.rocksdb-haskell</li>
    <li>haskellPackages.rocksdb-haskell-jprupp</li>
    <li>libceph</li>
    <li>rocksdb</li>
    <li>rocksdb_lite</li>
    <li>sambaFull (samba4Full)</li>
    <li>sortmerna</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102401` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>bareos</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>haskellPackages.rocksdb-haskell</li>
    <li>sortmerna</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>blockbook</li>
    <li>haskellPackages.rocksdb-haskell-jprupp</li>
  </ul>
</details>

**Comment by jonringer** [comment]
is
```
Public API Change

    Reworked BackupableDBOptions::share_files_with_checksum_naming (new in 6.12) with some minor improvements and to better support those who were extracting files sizes from backup file names.
```
a backwards compatible change?

**Comment by mweinelt** [comment]
Unfortunately NixOS 20.09 has reached its end-of-life status on 2021-07-01, one
month after the release of NixOS 21.05.

Since we do not accept any changes to its branches anymore, I'm closing this pull
request.

**Pull request closed without merging**
