### PR TITLE
lib/licenses: Business Source License 1.1 is redistributable

### PR DESCRIPTION
**Pull request by RaitoBezarius**
###### Description of changes

Feel free to bikeshed me.
It is written in its text, still unfree though and cannot be used for *production*.

At the request here: #232235.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cab404** [comment]
Heh, we can also parametrize it with a date and a fallback license, so to automatically switch it to fallback license)

**Comment by RaitoBezarius** [comment]
> Heh, we can also parametrize it with a date and a fallback license, so to automatically switch it to fallback license using the date from git)

I don't understand what you mean by that, can you clarify?

**Comment by cab404** [comment]
> I don't understand what you mean by that, can you clarify?

BSL is actually a parametrized license. You can choose "Change" license, which takes force after BSL period (also a parameter) ends.

**Comment by RaitoBezarius** [comment]
oh lord that's much more complicated than the scope of this PR, can you open a follow up for that?

**Comment by cab404** [comment]
> oh lord that's much more complicated than the scope of this PR, can you open a follow up for that?

You've added a request for bikeshedding ;D

**Comment by RaitoBezarius** [comment]
> You've added a request for bikeshedding ;D

true :DDDD — but I didn't expect "implement this whole changing license mechanism" as a bikeshedding to redistribution :P

**Comment by RaitoBezarius** [comment]
> In practice I don't think the change date mechanism is meaningful, and trying to represent it in Nixpkgs is likely to result in more inaccurate license info. The change date tends to be frequently bumped, so unless we don't upgrade in Nixpkgs, or upstream stops releasing (or forgets to update its change date), the version we package in Nixpkgs will never be available under the fallback license. I don't think people are going to remember to check the new change date every time they update a package, so I'd expect change dates recorded in Nixpkgs to quickly become incorrect.

Hmm, I might be misunderstanding this but isn't the Change Date some "target limit date"? If you release a version 1, and something happens where you release version 2, 3, 4, 5, 6, after the 4th anniversary of version 1, all versions gets fallback license?

If it's not the case, I definitely agree with you then.

**Comment by alyssais** [comment]
> Hmm, I might be misunderstanding this but isn't the Change Date some "target limit date"? If you release a version 1, and something happens where you release version 2, 3, 4, 5, 6, after the 4th anniversary of version 1, all versions gets fallback license?

The way it usually works is that upstream will pick some duration, like 3 years, and then each release will have a change date attached that's 3 years from when that release is made.  So if v1 comes out in 2023, and v2 comes out in 2024, you could use v1 under the fallback license from 2026, and v2 from 2027.  So if you're keeping up to date, the fallback license is irrelevant.  It's only useful if upstream dies, or if you want to run an old version.  Does that answer your question?

**Review by alyssais — APPROVED** [review]

**Pull request merged**
