### PR TITLE
mpdris2: fix version & locale directory

### PR DESCRIPTION
**Pull request by codyopel**
@pjones

### CODE REVIEW

**Comment by pjones** [comment]
Can you explain why `nativeBuildInputs` is required here?  I know there's some confusing behavior in python packages related to `buildInputs` and `nativeBuildInputs`, but as far I'm aware `buildInputs` is the correct choice here.

Also, I don't believe setting `DATADIRNAME` in `makeFlags` has any effect.  The generated `Makefile` doesn't allow `DATADIRNAME` to be set from the environment.

**Comment by codyopel** [comment]
`nativeBuildInputs` are for `buildInputs` that are only required at build time, not for linking or runtime. They are typically seperated out for the purpose of not having to compile build dependencies for the target architecture when cross compiling.

Not setting `DATADIRNAME`, the make variable never gets set so it generates garbage output in the form of `$out/@DATADIRNAME@` which is invalid.  Also `makeFlags` are not environment variables.

**Comment by pjones** [comment]
This appears to be a bug in the `po/Makefile.in` file.  The AC variable `@DATADIRNAME@` does not get substituted by the `configure` script.  You should file a bug upstream for this.  I suspect that the variable the author is intending to use is `@DATADIR@`.

As far as using `makeFlags` to fix the problem, I think using something like `postPatch`/`postConfigure` and `substituteInPlace` would more clearly show your intention.

Finally, by "environment" I was referring to make's ability to set make variables from environment variables.  I forgot that setting a variable on the command line overrides the variable assignment in the `Makefile` and the environment.  Sorry about that.

**Comment by pSub** [comment]
Any updates?

**Comment by jagajaga** [comment]
@codyopel ping.

**Comment by jagajaga** [comment]
@codyopel won't you fix it?

**Pull request closed without merging**
