### PR TITLE
vimPlugins.neuron-nvim: init at 2021-03-20

### PR DESCRIPTION
**Pull request by wbadart**
###### Motivation for this change

The other vim/neovim plugins for `neuron-notes` are no longer maintained, so while this one is specific to neovim only (no vim support), it works with the latest versions of neuron.

###### Things done

```sh
cd pkgs/misc/vim-plugins
./update.py
./update.py --add oberblastmeister/neuron.nvim
```

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wbadart** [comment]
Looks like I managed to duplicate the new entry in generated.nix. Will fix when I'm back at my computer.

**Comment by figsoda** [comment]
btw you can just do
```
pkgs/misc/vim-plugins/update.py --add oberblastmeisternueron.nvim
```
for short

**Comment by wbadart** [comment]
Thanks @figsoda! I just ran that command from a clean checkout of `master` and force pushed.

**Comment by figsoda** [comment]
Result of `nixpkgs-review pr 140404` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>24 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>vimPlugins.chadtree</li>
    <li>vimPlugins.cmp_luasnip</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.feline-nvim</li>
    <li>vimPlugins.goto-preview</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neuron-nvim</li>
    <li>vimPlugins.nginx-vim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-code-action-menu</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-ts-rainbow</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.open-browser (vimPlugins.open-browser-vim)</li>
    <li>vimPlugins.quickrun (vimPlugins.vim-quickrun)</li>
    <li>vimPlugins.splitjoin-vim</li>
    <li>vimPlugins.vim-flog</li>
    <li>vimPlugins.vim-go</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.wilder-nvim</li>
  </ul>
</details>

**Review by figsoda — APPROVED** [review]

**Pull request merged**
