### PR TITLE
unbound: 1.6.5 -> 1.6.6

### PR DESCRIPTION
**Pull request by joachifm**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Builds quite a few packages. Staging?

**Comment by joachifm** [comment]
Hm, I seem to recall it had been decoupled from gnutls (or the other way around, really) but maybe I'm misremembering. Or perhaps there's a different rebuild trigger I'm just not aware of. In any case, I'm happy to change the target to staging.

**Comment by Mic92** [comment]
It wants to rebuild 4108 packages on my system.

**Review by fpletz — APPROVED** [review]
This minor update contains bugfixes so we should backport it to 17.09.

I decoupled unbound and gnutls a few months ago but reintroduced it along with some other changes (dns-root-data addition). Libunbound is used in gnutls for DANE support. I think we should support that. It is a big rebuild but not that much. Staging is probably best.

**Review by vcunat — APPROVED** [review]

**Comment by joachifm** [comment]
@vcunat thank you :)

**Pull request merged**
