### PR TITLE
terraform-providers.b2: init at 0.8.0

### PR DESCRIPTION
**Pull request by Hjdskes**
###### Description of changes

This PR adds a new Terraform provider, for [Backblaze B2](https://www.backblaze.com/b2/cloud-storage.html). The Terraform registry page can be found [here](https://registry.terraform.io/providers/Backblaze/b2/latest). The source code for the provider is [here](https://github.com/Backblaze/terraform-provider-b2).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Hjdskes** [comment]
Hey @zowoq! I'm not sure what I'm doing wrong, but trying to use this in my configuration with Nix Flakes I am running into this:

```
╷
│ Error: Failed to load plugin schemas
│ 
│ Error while loading schemas for plugin components: Failed to obtain provider schema: Could not load the schema for provider registry.terraform.io/backblaze/b2: failed to instantiate provider "registry.terraform.io/backblaze/b2" to
│ obtain schema: Unrecognized remote plugin message: 
│ 
│ This usually means that the plugin is either invalid or simply
│ needs to be recompiled to support the latest protocol...
╵
```

I suspect it's a capitalization issue, as per:

```
 λ ls /nix/store/bhzpkwa0s8axr5nzqkmb0y2p6g0c0iih-terraform-1.2.0/libexec/terraform-providers/registry.terraform.io/
Backblaze
```

Notice that it's a capital B, whereas the registry url uses a small b.

**Comment by zowoq** [comment]
> Notice that it's a capital B, whereas the registry url uses a small b.

Registry URL is capital B?

https://registry.terraform.io/namespaces/Backblaze

https://github.com/numtide/nixpkgs-terraform-providers-bin/blob/master/providers/Backblaze/b2/default.nix

**Comment by Hjdskes** [comment]
Yes absolutely. I meant the URL in the error message: `registry.terraform.io/backblaze/b2`. Notice that that's not a capital B.

**Comment by zowoq** [comment]
IIRC terraform output will lowercase the providers so the issue is likely to be something else.

**Comment by Hjdskes** [comment]
Do you have an idea where to start troubleshooting? I'm not familiar with the NixOS way of doing Terraform.

**Pull request merged**
