### PR TITLE
nnn: 2.7 -> 2.8.1

### PR DESCRIPTION
**Pull request by Br1ght0ne**
###### Motivation for this change
https://github.com/jarun/nnn/releases/tag/v2.8

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
```
/nix/store/vm8l0is87p446jrd0wsngmd35jj3q9da-nnn-2.7	  30.6M
/nix/store/491kv7bsd1g0blkhklcm8fc329kqhmbj-nnn-2.8	  30.7M
```
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @jfrankenau

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/74971)

### CODE REVIEW

**Comment by sikmir** [comment]
@filalex77 [2.8.1](https://github.com/jarun/nnn/releases/tag/v2.8.1) is out.

**Comment by filalex77** [comment]
@GrahamcOfBorg build nnn

**Comment by jfrankenau** [comment]
This update has already been merged in #75016. Also this pull request contains some totally unrelated changes.

**Comment by filalex77** [comment]
@jfrankenau Oh, didn't know about that. Thanks for letting me know!

**Pull request closed without merging**
