### PR TITLE
zrythm: 1.0.0-beta.4.9.1 -> 1.0.0-beta.4.12.5

### PR DESCRIPTION
**Pull request by davidak**
## Description of changes

Related https://github.com/NixOS/nixpkgs/issues/252561

can't add @yuuyins as reviewer for some reason

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by davidak** [comment]
Needs some new dependencies.

> Dependency gtk4 found: NO found 4.10.4 but need: '>=4.13'

We don't have that yet.

Please continue this when available.

**Comment by Nyabinary** [comment]
A little bit useful but I need the latest since that is preferable, also it uses GTK 4.12.1 but only because it includes fixes for MacOS

**Comment by davidak** [comment]
Then this update will take some time.

**Comment by bobby285271** [comment]
> updating gtk4 to latest stable

It is in GNOME 45 PR 822896ad311a1f4ea179d2a897d4d532bc31e3ce 1c34cf740131c6f867c1d5de8c6d97da3a5efb9e. I don't have a reason to block this from bumping separately *for now* so probably we can try (I changed my day $job recently and have much fewer time to work on Nixpkgs things so there is no guarantee on this).

**Comment by davidak** [comment]
@bobby285271 it's probably not worth the risk to break a lot of packages. makes sense to update gnome completely

Be careful not to work too much!

**Comment by Nyabinary** [comment]
How would I test it? Bit of a newbie.

**Comment by davidak** [comment]
This command builds the packages affected by this pull request and opens a shell that has them available. Then you can run and test them. You have to run it inside a local checkout of nixpkgs.

`nix-shell -p nixpkgs-review --run "nixpkgs-review pr 253765"`

Optionally, you can setup a github token to post the build result as a comment to the pull request using `--post-result`.

https://github.com/Mic92/nixpkgs-review#github-api-token

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 253765` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zrythm</li>
  </ul>
</details>

**Review by magnetophon — APPROVED** [review]

**Comment by davidak** [comment]
@magnetophon have you tested it and verified that you don't have the crashes i experienced?

**Comment by Nyabinary** [comment]
@davidak The segment fault issue is solved in the new version of Zrythm, 4.13, so should update this PR to 4.13

**Comment by davidak** [comment]
@Nyabinary that still needs an unstable version of GTK we don't have in nixpkgs yet.

4.12 and 4.11 all crash when "save and close". i don't want to update the package to a broken state. the packaged version works. so we have to wait here

until then, you can use the flatpak as a workaround: https://flathub.org/apps/org.zrythm.Zrythm

**Comment by Nyabinary** [comment]
@davidak The flatpak isnt officially supported

**Comment by davidak** [comment]
@Nyabinary it's verified by the developers. and flatpak is supported on nixos. so it should work

**Comment by Nyabinary** [comment]
Any updates on this btw?

**Comment by yuuyins** [comment]
@Nyabinary No. Need to wait until the likely stable release of GTK 4.14 and then addition to Nixpkgs.

**Comment by Nyabinary** [comment]
Any updates on this?

**Comment by m-bdf** [comment]
GTK 4.13 still isn't in nixpkgs, see https://github.com/NixOS/nixpkgs/issues/258634#issuecomment-1744396352.

I'm currently using this to build zrythm 1.0.0-beta.4.13.31 with GTK 4.13.3:

```nix
{ lib, pkgs, ... }:

let
  gtk4 = pkgs.gtk4.overrideAttrs (oldAttrs: rec {
    version = "4.13.3";
  
    src = pkgs.fetchurl {
      url = "mirror://gnome/sources/gtk/${lib.versions.majorMinor version}/gtk-${version}.tar.xz";
      sha256 = "TwSkPnwoc2BHPzT8J7Yp9kh1eV87x+wngd9EnF5y8xI=";
    };
  
    patches = [];
  
    buildInputs = oldAttrs.buildInputs ++ [ pkgs.libdrm ];
  });
in

pkgs.zrythm.overrideAttrs (oldAttrs: rec {
  version = "1.0.0-beta.4.13.31";

  src = pkgs.fetchFromGitLab {
    domain = "gitlab.zrythm.org";
    owner = "zrythm";
    repo = "zrythm";
    rev = "v${version}";
    hash = "sha256-of0osz+Qgqok7VbhLsWlSDPLKi+4IdziKU9h0iTYWzc=";
  };

  buildInputs = [ gtk4 ] ++ oldAttrs.buildInputs ++ [ pkgs.soxr ];
})
```

**Comment by PowerUser64** [comment]
I have updated zrythm on my own branch: https://github.com/PowerUser64/nixpkgs/commit/2aeeeccae670d7f6fe9c88b8e8965b433f25c82b. This brings zrythm to its current version (1.0.0-beta.5.1.1). I used `overrideAttrs` to bring gtk to the required release, and updated carla to the latest commit.

Should I submit a PR with these changes? I don't know whether using `overrideAttrs` inside `buildInputs` is allowed in nixpkgs.

**Comment by nyabinary** [comment]
> I have updated zrythm on my own branch: [PowerUser64@2aeeecc](https://github.com/PowerUser64/nixpkgs/commit/2aeeeccae670d7f6fe9c88b8e8965b433f25c82b). This brings zrythm to its current version (1.0.0-beta.5.1.1). I used `overrideAttrs` to bring gtk to the required release, and updated carla to the latest commit.
> 
> Should I submit a PR with these changes? I don't know whether using `overrideAttrs` inside `buildInputs` is allowed in nixpkgs.

overrideAttrs should be allowed.

**Comment by PowerUser64** [comment]
Made a PR to update to `v1.0.0-beta.6.4.1` using overrideAttrs to fill gaps in package versions where needed https://github.com/NixOS/nixpkgs/pull/290598

**Comment by PowerUser64** [comment]
Superseded by #306959 (Merged)

**Pull request closed without merging**
