### PR TITLE
trust-dns: fix hash

### PR DESCRIPTION
**Pull request by wegank**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by superherointj — APPROVED** [review]

**Comment by aktaboot** [comment]
sorry,  my fault! ... how did I get these wrong :thinking:

**Comment by uninsane** [comment]
image

they overwrote the existing tag (so @aktaboot you probably did get it right). we did take the update before the Github "release" was made, maybe they missed a step in their release process and thought nobody was using the tag yet and that it could be fixed silently. idk.

they've got a Discord channel if anyone with an account wants to dive deeper: <https://github.com/hickory-dns/hickory-dns?tab=readme-ov-file#community>

**Comment by superherointj** [comment]
Can I merge then?

**Comment by uninsane** [comment]
looks like they only fixed the version fields i guess for people who would be using this as a library.

from my own tags: `git diff v0.24.1..e56a18ee241edf9c8a4ee17508cfc727617ffbb9`

```diff
diff --git Cargo.lock Cargo.lock
index cb204564..ea563044 100644
--- Cargo.lock
+++ Cargo.lock
@@ -231,7 +231,7 @@ dependencies = [
 
 [[package]]
 name = "async-std-resolver"
-version = "0.24.0"
+version = "0.24.1"
 dependencies = [
  "async-std",
  "async-trait",
@@ -781,7 +781,7 @@ checksum = "d231dfb89cfffdbc30e7fc41579ed6066ad03abda9e567ccafae602b97ec5024"
 
 [[package]]
 name = "hickory-client"
-version = "0.24.0"
+version = "0.24.1"
 dependencies = [
  "cfg-if",
  "data-encoding",
@@ -803,7 +803,7 @@ dependencies = [
 
 [[package]]
 name = "hickory-compatibility"
-version = "0.24.0"
+version = "0.24.1"
 dependencies = [
  "data-encoding",
  "futures",
@@ -815,7 +815,7 @@ dependencies = [
 
 [[package]]
 name = "hickory-dns"
-version = "0.24.0"
+version = "0.24.1"
 dependencies = [
  "clap",
  "futures-util",
@@ -835,7 +835,7 @@ dependencies = [
 
 [[package]]
 name = "hickory-integration"
-version = "0.24.0"
+version = "0.24.1"
 dependencies = [
  "async-trait",
  "futures",
@@ -857,7 +857,7 @@ dependencies = [
 
 [[package]]
 name = "hickory-proto"
-version = "0.24.0"
+version = "0.24.1"
 dependencies = [
  "async-trait",
  "backtrace",
@@ -902,7 +902,7 @@ dependencies = [
 
 [[package]]
 name = "hickory-recursor"
-version = "0.24.0"
+version = "0.24.1"
 dependencies = [
  "async-recursion",
  "async-trait",
@@ -923,7 +923,7 @@ dependencies = [
 
 [[package]]
 name = "hickory-resolver"
-version = "0.24.0"
+version = "0.24.1"
 dependencies = [
  "cfg-if",
  "futures-executor",
@@ -951,7 +951,7 @@ dependencies = [
 
 [[package]]
 name = "hickory-server"
-version = "0.24.0"
+version = "0.24.1"
 dependencies = [
  "async-trait",
  "basic-toml",
@@ -983,7 +983,7 @@ dependencies = [
 
 [[package]]
 name = "hickory-util"
-version = "0.24.0"
+version = "0.24.1"
 dependencies = [
  "clap",
  "console",
diff --git Cargo.toml Cargo.toml
index e7705c4f..ae700db1 100644
--- Cargo.toml
+++ Cargo.toml
@@ -15,7 +15,7 @@ members = [
 exclude = ["fuzz"]
 
 [workspace.package]
-version = "0.24.0"
+version = "0.24.1"
 authors = ["The contributors to Hickory DNS"]
 edition = "2021"
 rust-version = "1.67.0"
```

**Pull request merged**
