### PR TITLE
polychromatic: 0.7.3 -> 0.8.0

### PR DESCRIPTION
**Pull request by jrgiacone**
###### Description of changes

Updates polychromatic to version 0.8.0 recently released, the some file names and paths changed as well such as common.py to paths.py.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jrgiacone** [comment]
Hi is there anything more I am missing on this one?

**Comment by jrgiacone** [comment]
@SuperSandro2000 @evanjs is there anything I am missing from this PR that is preventing it from going through?

**Comment by drupol** [comment]
I think you need to rebase it properly and have one single commit

**Comment by jrgiacone** [comment]
> I think you need to rebase it properly and have one single commit

I'm sorry trying to figure out how to do that now, I'm new to contributing

**Comment by anoadragon453** [comment]
Assuming you only want the changes in this commit: [d8e9915](https://github.com/NixOS/nixpkgs/pull/206347/commits/d8e991582820b7f324345b8faed49e415eb6d228)

You can simply do the following. Be sure to double-check what your remotes are called first (use `git remote -v` to check):

```
# check out the latest upstream commit of the `master` branch again
# (assuming your remote for NixOS/nixpkgs is called `upstream`)
git fetch && git checkout upstream/master

# delete and re-create your local `master` branch with the same contents of NixOS/nixpkgs master branch.
# don't worry - this won't delete the contents of your commits
git branch -D master && git checkout -b master

# Set the remote branch of your local branch that you'll push to
# to the `master` branch on jrgiacone/nixpkgs.
# (assuming your remote for jrgiacone/nixpkgs is called `origin`)
git branch --set-upstream-to=origin/master master

# Cherry pick the only commit you want on the PR
git cherry-pick d8e991582820b7f324345b8faed49e415eb6d228

# Force-push your changes in order to rewrite the history of your PR to only include that one commit
# (assuming your remote for jrgiacone/nixpkgs is called `origin`)
git push -f -u origin master
```

**Comment by Majiir** [comment]
You should also go through the checklist. Not every single item needs to be addressed, but for this one, you should run `nixpkgs-review` (which should easily pass), test basic functionality of binary files (post a description of what you tested and maybe a screenshot), and read over `CONTRIBUTING.md`. Without those items checked, it looks like a work-in-progress.

**Comment by winterqt** [comment]
In addition to everything discussed above, you should change the commit message to use a lowercase P in the package name (to match the name in top-level), so tests are automatically ran.

**Comment by SuperSandro2000** [comment]
@ofborg build polychromatic

**Pull request merged**
