### PR TITLE
golden-cheetah: inline patch

### PR DESCRIPTION
**Pull request by flokli**
This won't get merged into GoldenCheetah any time soon, at least not
before their 3.6 release.

The PR is periodically rebased, so better ship this in nixpkgs for the
time being.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
What's the advantage? The URL won't 404, will it?

**Comment by flokli** [comment]
> What's the advantage? The URL won't 404, will it?

It might get GC'ed eventually, if the branch containing it is removed (or force-pushed). I think it's safer to inline it.

**Comment by dguibert** [comment]
> > What's the advantage? The URL won't 404, will it?
> 
> It might get GC'ed eventually, if the branch containing it is removed (or force-pushed). I think it's safer to inline it.

What about appending `.patch` to the github PR:
[https://github.com/GoldenCheetah/GoldenCheetah/pull/3590.patch](https://github.com/GoldenCheetah/GoldenCheetah/pull/3590.patch)

**Comment by flokli** [comment]
I'm not sure on how stable that is either.

**Comment by JohnAZoidberg** [comment]
> It might get GC'ed eventually, if the branch containing it is removed (or force-pushed). I think it's safer to inline it.

Yeah I've seen branches from old PRs disappear.

Should we also link your PR that's still open and which will fix the issue upstream?
https://github.com/GoldenCheetah/GoldenCheetah/pull/3628

**Review by JohnAZoidberg — APPROVED** [review]

**Comment by bobby285271** [comment]
> What about appending .patch to the github PR:

Ramdom example here: https://github.com/bobby285271/nixpkgs/pull/10

**Pull request merged**
