### PR TITLE
remctl: init at 3.18

### PR DESCRIPTION
**Pull request by de11n**
## Things done

This is a replacement PR for #110336.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by marcusramberg** [comment]
```
error: builder for '/nix/store/x36lw93kxz7xrpk99gbd8dlnvsfw2dkf-remctl.drv' failed with exit code 1;
       last 10 log lines:
       > and the repository exists.
       > fatal: Could not read from remote repository.
       >
       > Please make sure you have the correct access rights
       > and the repository exists.
       > fatal: Could not read from remote repository.
       >
       > Please make sure you have the correct access rights
       > and the repository exists.
       > Unable to checkout refs/tags/release/3.18 from git://git.eyrie.org/kerberos/remctl.git.
```

**Comment by SuperSandro2000** [comment]
Is this dead software? the last commit is 2 years old.

**Comment by de11n** [comment]
@marcusramberg Oof thanks. I didn't realize that mirror had gone down. I fixed it.

**Review by marcusramberg — APPROVED** [review]

**Comment by zakame** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 350206`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 9 packages built:</summary>
  <ul>
    <li>perl538Packages.NetRemctl</li>
    <li>perl538Packages.NetRemctl.devdoc</li>
    <li>perl540Packages.NetRemctl</li>
    <li>perl540Packages.NetRemctl.devdoc</li>
    <li>python311Packages.remctl</li>
    <li>python311Packages.remctl.dist</li>
    <li>python312Packages.remctl</li>
    <li>python312Packages.remctl.dist</li>
    <li>remctl</li>
  </ul>
</details>

**Review by zakame — APPROVED** [review]
perl-packages LGTM

**Review by stigtsp — APPROVED** [review]
LGTM

**Pull request merged**
