### PR TITLE
Concourse

### PR DESCRIPTION
**Pull request by dingxiangfei2009**
###### Motivation for this change

In this pull request, we provide Nix expression for evaluating concourse and fly, as well as systemd service units for setting up concourse ATC and/or worker.

Concourse: https://concourse-ci.org

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dingxiangfei2009** [comment]
@GrahamcOfBorg build concourse

**Comment by dingxiangfei2009** [comment]
@Infinisil I have question about CI. It appears that CI refused to evaluate a derivation because the derivator was not in the store. How can I fix this problem?

**Comment by Infinisil** [comment]
Not sure what the problem is. In any case you should clean up the commits in this PR. This means:
- One commit for adding yourself as a maintainer
- A single commit for every package added
- A single commit for every NixOS module added
- Get rid of all merges, you should always rebase instead
- Format your commit message according to the [Contribution Guidelines](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes), also linked to from the PR template.

**Comment by dR3b** [comment]
When will concourse be available on the stable channel?

**Comment by dingxiangfei2009** [comment]
@dR3b we are blocked on #60069 and #60071

**Comment by pinpox** [comment]
Any updates on this, is anyone working on adding concourse to nixos?

**Comment by grerrg** [comment]
@pinpox 
I'm looking forward to this one too.
Looks like the way to go is using the [concourse docker container](https://memo.barrucadu.co.uk/concourseci-nixos.html).

Since this issue is a bit older i've decided to go with `buidbot` because there are already nix options for that.

**Comment by AndersonTorres** [comment]
Closing as dead.

**Comment by grerrg** [comment]
> @dR3b we are blocked on #60069 and #60071

Can we somehow revive this since those blockers are resolved?
Could try my luck with those changes already present but haven't done much in this direction. -> could take some time.

**Comment by AndersonTorres** [comment]
Do as you wish.

**Pull request closed without merging**
