### PR TITLE
openbao: Build with native go compiler

### PR DESCRIPTION
**Pull request by djds**

### CODE REVIEW

**Comment by NickCao** [comment]
What's the justification?

**Comment by djds** [comment]
> What's the justification?

That's how upstream builds it and there's no need for any CGO features.

**Comment by NickCao** [comment]
> there's no need for any CGO features.

In fact there is: https://pkg.go.dev/net#hdr-Name_Resolution. With CGO the native, glibc based resolver is used, which do support more features than the go based resolver. While this is not relevant for the majority of the users, disabling CGO doesn't provide much benefit either. Upstream might be inclined to disable CGO to produce a static binary that's easier to redistributed, but that's never a problem with nix.

**Comment by djds** [comment]
> With CGO the native, glibc based resolver is used, which do support more features than the go based resolver.
Ah, TIL.

**Pull request closed without merging**
