### PR TITLE
zabbix: 6.0 -> 7.0

### PR DESCRIPTION
**Pull request by adamprice56**
## Description of changes

Zabbix has released v7.0.0 LTS
https://www.zabbix.com/documentation/7.0/en/manual/introduction/whatsnew700

A few breaking changes to be noted here
https://www.zabbix.com/documentation/7.0/en/manual/installation/upgrade_notes_700#breaking-changes

## Things done

- Added Zabbix v70 definition in versions.nix
- Added zabbix70 definition to all-packages.nix
- Pointed zabbix package to zabbix70

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by DontEatOreo** [comment]
Please reword your commit and PR title to be `zabbix: 6.0 -> 7.0`

**Comment by adamprice56** [comment]
Reworded (Assuming I've done it right) 😄 

I'm running some tests on a spare machine to make sure the Zabbix services run correctly, I'm sure an upgrade from 6.x will need checking too 🤔

**Comment by DontEatOreo** [comment]
Could you please squash 93ca7dc6060712678a20cb9918e257b3e62d58e7 and 762488c856f578399fc7fe85bc47ea7ea1efd63c into 8143bf67fe6a6ea16ba3fa701f2940096be07cc6 ?

**Comment by gador** [comment]
Have you tried deploying the new version?

**Comment by gador** [comment]
@adamprice56 do you still work on this PR?

**Comment by gador** [comment]
@adamprice56 thanks for your contribution. As I have not heard from you, I added a PR to update zabbix myself, which will supersede your PR. If you like, you can have a look (and maybe review) the new PR. I'll go ahead and close your draft here in favor of   #332290

**Pull request closed without merging**
