### PR TITLE
treewide: disable static linking for Go packages

### PR DESCRIPTION
**Pull request by azahi**
###### Description of changes

Disable static linking for buildGoModule and buildGoPackage packages.

Since we can leverage patchelf to change RPATH for dynamically linked executables, I propose removing static linking from Go packages. This will result in executables with smaller size and  will fully utilize their respective closures.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
Have you tested that these are still built statically when using pkgsStatic?

**Comment by azahi** [comment]
> Have you tested that these are still built statically when using pkgsStatic?

Well, I'm not exactly familiar with `pkgsStatic`, and if it utilizes `stdenv`, it probably won't works because for Go static/dynamic linking is defined by `-ldflags`. Could you please link to some documentation or show how can test this out?

**Comment by azahi** [comment]
Result of `nixpkgs-review pr 190034` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>arduino-ci</li>
    <li>arduino-cli</li>
    <li>datree</li>
    <li>gobgp</li>
    <li>gobgpd</li>
    <li>ligolo-ng</li>
    <li>mimir</li>
    <li>rancher</li>
    <li>scaleway-cli</li>
    <li>tanka</li>
    <li>trickster</li>
    <li>vegeta</li>
  </ul>
</details>

**Comment by alyssais** [comment]
> Well, I'm not exactly familiar with `pkgsStatic`, and if it utilizes `stdenv`, it probably won't work because for Go static/dynamic linking is defined by `-ldflags`.

You're right.  I thought it worked for Go programs but I just tested it and it seems like it doesn't.  So never mind. :)

**Comment by zowoq** [comment]
I guess I don't really have an opinion on this. I don't see much benefit from it but I don't object to merging it. These flags may have been added for reason(s) (valid or not) but we can't really stop them from being re-added or added in other packages.

https://github.com/NixOS/nixpkgs/issues/77591 has some detail on what `pkgsStatic` for `go` would look like but I'd doubt that'll be resolved anytime soon, we need to have better handling of ldflags|tags|buildFlags* and so forth first.

@NixOS/golang Any thoughts on this?

**Comment by azahi** [comment]
> These flags may have been added for reason(s) (valid or not) but we can't really stop them from being re-added or added in other packages.

Maybe we can add a suggestion not to use `-extldflags=-static` unless required in some circumstances to the [docs](https://nixos.org/manual/nixpkgs/unstable/#ssec-go-common-attributes)?

**Comment by zowoq** [comment]
Yeah, adding a note to the docs wouldn't be a bad idea. Gives us something to refer to from now on and might discourage some cargo culting.

**Comment by azahi** [comment]
I've researched the topic of static linking for Go for a while and stumbled upon a plethora of articles and comments that suggest to **not** to use dynamic linking/cgo. Notably [this one](https://dave.cheney.net/tag/cgo). 

I'm now kinda conflicted: on the one hand cgo being enabled is the default way of building a Go package, on the other hand using cgo leads to [a bigger virtual memory footprint](https://stackoverflow.com/questions/54456100/why-does-cgo-enable-make-a-such-impact-on-virtual-memory), [slower speed + larger executable size](https://stackoverflow.com/questions/64531437/why-is-cgo-enabled-1-default#comment114120432_64531740), and in a case of the package which I maintain: a [segfault](https://gist.github.com/azahi/99cacfaedb56e8b38413f894e3485bb1).

From that I came to the conclusion that there's virtually no benefit for dynamic linking, and it in fact could even be harmful in some cases, so I'm closing this PR unless some compelling argument arises in favor of doing this.

**Pull request closed without merging**
