### PR TITLE
sage: 8.0 -> 8.1, fix sandbox build

### PR DESCRIPTION
**Pull request by timokau**
This updates sage to 8.1 and, more importantly, makes the build work sandboxed.

###### Motivation for this change

The sandboxed build was failing, because it relied heavily on /usr/bin/env. This is fixed with a lot of shebang patching (both to system packages and to sage-internal packages).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`) (Well, there are too many to test all. But at least ./result/bin/sage)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build sage

**Comment by 7c6f434c** [comment]
After looking at what is needed for a rebuild-everything-locally sandboxed build, I have gone into negative-amount-of-surprise about my failure to build it while reusing maxima-ecl etc. built externally…

**Comment by timokau** [comment]
Yeah, sage is a real pain! Lets just hope they don't change their build too much in the future.

**Comment by 7c6f434c** [comment]
An optimist would hope that they would actually change their build in the future and make it easier to package with system versions of software! Oh well…

On the other hand, Debian does seem to be forcing Sage to reuse at least some of the dependencies from the outer system.

**Comment by 7c6f434c** [comment]
@grahamc timeout means no output for half an hour? Any way to see if there was a sudden load on the builder machine?

**Comment by grahamc** [comment]
The timeout is for overall build time.

**Comment by 7c6f434c** [comment]
There goes my plan to improve builder utilisation…

**Comment by 7c6f434c** [comment]
(actually tested on my sandbox-enabled build brix)

Thanks!

**Comment by timokau** [comment]
Great, thanks!

**Comment by timokau** [comment]
This commit is included in `nixos-unstable` now, but not in the binary cache. Is that because the hydra build failed? I tried to navigate hydra.nixos.org, but I couldn't figure out how that is organized.

**Comment by 7c6f434c** [comment]
`[giac-1.2.3.47.p0] ! LaTeX Error: File `xcolor.sty' not found.`

I… don't understand what has happenned.

https://hydra.nixos.org/job/nixpkgs/trunk/sage.x86_64-linux
https://hydra.nixos.org/build/68286564
https://hydra.nixos.org/build/68286564/nixlog/2/raw

**Comment by timokau** [comment]
Well thats an easy fix, but how did that happen? Can it be that `texlive.combine` somehow breaks sandboxing? I have `xcolor` on my system (but did build with sandbox).

**Comment by 7c6f434c** [comment]
I am not really sure.

**Comment by timokau** [comment]
I opened an issue about it, hopefully somebody more knowledgable about the sandbox and texlive-combined can explain and maybe fix the issue. Its probably better to wait for that before I make a PR for a fix, since there may be more latex packages missing and I don't want to abuse hydra as a test machine.

**Pull request merged**
