### PR TITLE
openmw: enable with glibc fix

### PR DESCRIPTION
**Pull request by nicknovitski**
###### Description of changes

Apply a patch to fix compilation with new glibc versions.

Fixed also some problems with tes3mp.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by marius851000** [comment]
You should probably do a different commit for the openmw fix, and the tes3mp improvement, but otherwise, it looks good for me. I'll try to compile it later.

**Comment by marius851000** [comment]
OpenMW worked correctly,  but tes3mp refuse to connect to any server (tested with server on version 0.8.1, 0.8.0 or 0.7-alpha) when using the server browser (while out of scope of this PR, it should be a good idea to provide all three version of tes3mp, as the server need a matching client version)

**Comment by nicknovitski** [comment]
Good points, I've changed the commit to keep tes3mp disabled.

**Comment by marius851000** [comment]
@nicknovitski Do you plan on making a new PR to fix tes3mp ? Otherwise, I'll try to fix it myself (by adding the three commonly run version of the game as different packages).

**Comment by nicknovitski** [comment]
> @nicknovitski Do you plan on making a new PR to fix tes3mp ?

No, I defer to you on that.

I did make a brief effort to write a nixos test which verified that for a given tes3mp package, a client would be able to connect to a server, but from the openmw documentation it is not possible on v0.47 to run the game completely without morrowind's data files, and even if I could get a server running in the test, I did not know how to script the client so that it connects to that server, or even how to start the browser on a private network without internet access and still be able to see the test server.

**Pull request merged**
