### PR TITLE
ugarit-manifest-maker: init at 0.1

### PR DESCRIPTION
**Pull request by ebzzry**

### CODE REVIEW

**Comment by zimbatm** [comment]
@ebzzry can you rebase on top of master ?

**Comment by ebzzry** [comment]
@zimbatm Did you mean, rebase with ugarit-2.0?

**Comment by zimbatm** [comment]
I mean this repo's master. Right now I can't merge the branch into master because of merge conflict

**Comment by ebzzry** [comment]
Ok, let me do it.

**Comment by ebzzry** [comment]
@zimbatm rebased =)

**Comment by ebzzry** [comment]
@zimbatm Thanks!

**Pull request merged**
