### PR TITLE
mongodb-4_2: 4.2.19 -> 4.2.24

### PR DESCRIPTION
**Pull request by vifino**
###### Description of changes

MongoDB 4.2 is still used by the unifi applications and had security patches.

I've tried bumping 4.4 as well, but the boost 1.79 patch does not apply, so that'll take more work.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Atemu — COMMENTED** [review]
Result of `nixpkgs-review pr 222045` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>mongodb-4_2</li>
  </ul>
</details>


```
Compiling build/nixos/mongo/scripting/mozjs/objectwrapper.o
<built-in>:1:10: fatal error: 'js-config.h' file not found
#include "js-config.h"
         ^~~~~~~~~~~~~
```

This error existed before though. You can probably remove the Darwin patch and make `meta.broken = stdenv.isDarwin;`

**Comment by vifino** [comment]
> This error existed before though. You can probably remove the Darwin patch and make `meta.broken = stdenv.isDarwin;`

It seems this only happens because there is no relevant config generated - I believe it only affects aarch64-darwin.

Then again, in `mongodb.nix:188`, `platforms = subtractLists systems.doubles.i686 systems.doubles.unix;` makes it seem like it only supports i686..

**Comment by vifino** [comment]
According to the [supported platforms list](https://www.mongodb.com/docs/manual/administration/production-notes/#supported-platforms) only 6.0 and up works on M1 machines.

**Comment by GabrielDougherty** [comment]
Result of `nixpkgs-review pr 222045` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mongodb-4_2</li>
  </ul>
</details>

**Comment by vifino** [comment]
I added a small fix to let it compile for aarch64, otherwise I can't get my unifi controller updated.
When I tackle the later mongodb versions, I'll add the same patch, didn't wanna do it here.

**Review by Atemu — APPROVED** [review]
Result of `nixpkgs-review pr 222045` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mongodb-4_2</li>
  </ul>
</details>

**Pull request merged**
