### PR TITLE
Release 14.12 - adding configFile option for the dovecot so that absolute path could be used

### PR DESCRIPTION
**Pull request by ghost**
Config file used for the whole dovecot configuration.
### Example usage

```
$ cat /etc/nixos/dovecot-config.nix
services.dovecot2.enable = true;

# all settings are useless if the configFile is specified like so
services.dovecot2.configFile = "/etc/dovecot/dovecot2.conf";
```
### Reason

Absolute path is required when one has such postfix configuration where he/she needs to specify tha actual (real) path to active dovecot config as below.

Before this patch is applied, the dovecot is running in such way: `/nix/store/hashAAA-dovecot-2.1.17/sbin/dovecot -F -c /nix/store/hashBBB-dovecot2.conf`   ; and postfix can't be aware of the value of "hashBBB" via `services.postfix.extraConfig = '' ... '';`   ;  (only it can be aware of "hashAAA" with `${pkgs.dovecot}` parameter)

```
$ cat /etc/nixos/postfix-config.nix
  services.postfix.extraMasterConf =
''
dovecot   unix  -       n       n       -       -       pipe
  flags=DRhu user=vmail:vmail argv=${pkgs.dovecot}/libexec/dovecot/deliver -c /etc/dovecot/dovecot2.conf
  -f ''${sender} -d ''${recipient}
```
### Patch

```
[root@mail:~]# diff -u nixpkgs/nixos/modules/services/mail/dovecot.nix.orig nixpkgs/nixos/modules/services/mail/dovecot.nix
--- nixpkgs/nixos/modules/services/mail/dovecot.nix.orig    2015-01-17 08:49:24.894834703 +0100
+++ nixpkgs/nixos/modules/services/mail/dovecot.nix 2015-01-17 08:58:09.160141108 +0100
@@ -45,8 +45,6 @@
       pop3_uidl_format = %08Xv%08Xu
     '' + cfg.extraConfig;

-  confFile = pkgs.writeText "dovecot.conf" dovecotConf;
-
 in

 {
@@ -88,6 +86,12 @@
         description = "Additional entries to put verbatim into Dovecot's config file.";
       };

+      configFile = mkOption {
+        default = null;
+        description = "Config file used for the whole dovecot configuration.";
+        apply = v: if v != null then v else pkgs.writeText "dovecot.conf" dovecotConf;
+      };
+
       mailLocation = mkOption {
         default = "maildir:/var/spool/mail/%u"; /* Same as inbox, as postfix */
         example = "maildir:~/mail:INBOX=/var/spool/mail/%u";
@@ -155,7 +159,7 @@
             ${pkgs.coreutils}/bin/chown -R ${cfg.user}:${cfg.group} /var/run/dovecot2
           '';

-        exec = "${pkgs.dovecot}/sbin/dovecot -F -c ${confFile}";
+        exec = "${pkgs.dovecot}/sbin/dovecot -F -c ${cfg.configFile}";
       };

     environment.systemPackages = [ pkgs.dovecot ];

```
#### Credits

Thanks to Lethalman from #nixos IRC :-)

### CODE REVIEW

**Comment by lethalman** [comment]
Omg what a mess this PR, github screwed up :P Can you please rebase your commit on top of master and reopen the PR? Thanks.

**Comment by peti** [comment]
Yeah, 1,590 changed files is a bit much.

**Comment by arno01** [comment]
I'm noob with this :) Let me retry...

**Comment by lethalman** [comment]
@arno01 np it's not straightforward to get a clean PR in github across different branches... you tried the hard path :P

**Comment by arno01** [comment]
@lethalman  not sure if this is right/good approach... but I forked the nixpkgs and committed two patches to myself :-)

Please check it and tell me what's the easiest way to make a pull request to the official repo?

https://github.com/arno01/nixpkgs/commits/release-14.12

https://github.com/arno01/nixpkgs/commit/85fb6ed3628d76d498052ff04f993253db72e4c7
https://github.com/arno01/nixpkgs/commit/bdd2a2d0b5271a8015a9fb5cfe64ca48afd46f55


Just to keep the track (for myself and other git-noobs), I followed:
```
https://help.github.com/articles/set-up-git/
https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/syncing-a-fork/
https://help.github.com/articles/using-pull-requests/
```

Then I cloned release-14.12 to my laptop, added upstream (I guess I didn't even use it...)
```
git clone -b release-14.12 https://github.com/arno01/nixpkgs
cd nixpkgs/
git remote add upstream https://github.com/arno01/nixpkgs.git
git fetch upstream
git checkout release-14.12
```

Then applied patches one-by-one with `patch -p1`  & `git commit .`


#### Result

```
~/nixpkgs $ git log -2
commit 85fb6ed3628d76d498052ff04f993253db72e4c7
Author: Andrey Arapov <arno@nixaid.com>
Date:   Sat Jan 17 14:08:59 2015 +0100

    Absolute path is required when one has such postfix configuration
    where he/she needs to specify tha actual (real) path to active dovecot
    config.
    
    Without this commitapplied, the dovecot is running in such way:
    /nix/store/hashAAA-dovecot-2.1.17/sbin/dovecot -F -c /nix/store/hashBBB-dovecot2.conf
    
    and postfix can't be aware of the value of "hashBBB" via services.postfix.extraConfig = '' ... '';
    (it can only be aware of "hashAAA" with ${pkgs.dovecot} parameter)

commit bdd2a2d0b5271a8015a9fb5cfe64ca48afd46f55
Author: Andrey Arapov <arno@nixaid.com>
Date:   Sat Jan 17 14:07:00 2015 +0100

    libmilter isn't compiled with the IPv6 support,
    because of that OpenDKIM fails to verify and postfix won't accept email:
    
    Jan 17 10:01:39 mail opendkim[5628]: OpenDKIM Filter: connect[140678164576000]: unknown family 54
    
    To remedy this patch has to be applied.
```

And then I pushed local changes to my fork with `git push`

**Comment by arno01** [comment]
Ok I guess I should do it against the master :-)

**Pull request closed without merging**
