### PR TITLE
lib.systems.riscv-multiplatform: linux-kernel config improvements

### PR DESCRIPTION
**Pull request by NickCao**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by onny** [comment]
What does `preferBuiltin = true;` mean? Why dropping
```
extraConfig = ''
  SERIAL_OF_PLATFORM y
'';
```

**Comment by NickCao** [comment]
> What does `preferBuiltin = true;` mean?

Even if a kconfig option defaults to `y`, if `preferBuiltin` is not set and `m` is available as an option, `m` would be set.


> Why dropping
> ```
> extraConfig = ''
>   SERIAL_OF_PLATFORM y
> '';
> ```

It's part of the `defconfig` since 2018.

**Review by onny — APPROVED** [review]
Great, works for me on VisionFive2 board without manually force `        PINCTRL_STARFIVE_JH7110_SYS = yes;`. Kernel is booting fine :+1:

**Comment by NickCao** [comment]
@onny Do you know who else is working on riscv? I'd like to ping more people before merging such a potentially breaking change.

**Comment by onny** [comment]
Unfortunately not. We should create a platform maintainer group :)

**Comment by NickCao** [comment]
> Unfortunately not. We should create a platform maintainer group :)

There is @NixOS/exotic-platform-maintainers

**Comment by 0x4A6F** [comment]
There is also [#riscv:nixos.org](https://matrix.to/#/#riscv:nixos.org) which is scoped to RISC-V topic.

**Comment by onny** [comment]
Are we save merging this or do we need some more tests?

**Comment by NickCao** [comment]
> Are we save merging this or do we need some more tests?

Let's merge this, it should be a net profit for the riscv platform. Except for these really memory constrained devices that can benefit from a smaller kernel, but they should be using a trimmed down kernel config anyway.

**Pull request merged**
