### PR TITLE
Cmake paths patch 1/? (boost, aws-sdk-cpp)

### PR DESCRIPTION
**Pull request by thequux**
###### Motivation for this change

Many packages generate CMake configuration files that try to figure out the paths to include and library directories from the location of the CMake file; this breaks in NixOS derivations with a `dev` output because the CMake package gets installed to `$out/lib/cmake`, but then gets moved into the `dev` output by the `_multioutDevs` fixup hook.

This needs to be fixed on a case-by-case basis, because this usually involves custom logic. So far, I've fixed boost (>= 1.70; before that, it didn't install cmake files as far as I can tell) and aws-sdk-cpp.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"` (I hoped Hydra would do that for me)
- [ ] Tested execution of all binary files (usually in `./result/bin/`) (no binaries, only libraries, and they should be unaffected)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
     (within 10KiB for both)
- [x] Ensured that relevant documentation is up to date (I couldn't find any)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
This looks useful! @thequux, do you think these patches or parts of them can be sent upstream?

**Comment by thequux** [comment]
The aws-cpp-sdk one can be; it's designed to mangle the logic as little as possible. However, the boost patch is very nix-specific; bjam is not exactly my jam, so I didn't try to do a nice job of it, but rather make something that would be robust to upstream changes.

**Comment by veprbl** [comment]
@thequux Could you please do that? The reason for upstreaming patches (especially bigger ones like the one you add to `aws-sdk-cpp`) is so that we don't take extra effort to maintain them in the future, plus we get them looked at by the upstream authors, and one other thing is that we can then use `fetchpatch` to fetch them from an url instead of piling them in git history. For the boost one, it would be preferred to at least file an upstream bug.

**Comment by thequux** [comment]
Sure. I'll send a patch for aws-sdk-cpp first thing tomorrow morning, but for boost, I need to first verify that we're actually giving bjam all of the correct paths at build time, rather than depending on the preFixup hook to move things into the correct output.

**Comment by thequux** [comment]
I submitted a slightly improved version of the patch in awslabs/aws-sdk-cpp#1365 ; the differences between this patch and that one are irrelevant for Nix's purposes (specifically, the upstream patch will generate valid pkg-config files even if the install dirs aren't absolute).

I get the impression that the AWS SDK hasn't been focusing much on pull requests recently, as upstream hasn't touched any PRs since 6 Jan, so it may be best to use an in-tree patch until they get through their backlog.

**Comment by doronbehar** [comment]
Just wanted to say that both this and https://github.com/NixOS/nixpkgs/pull/73940 _work_, as mentioned in #85922 . What I've found out today though, was that with the workaround supplied at: https://github.com/NixOS/nixpkgs/pull/85922#issuecomment-619075044

Makes (e.g) `mtxclient` reference `boost.dev`. With either this or the other patch, it doesn't.

**Comment by bhipple** [comment]
Thanks for doing this!  I had stumbled on the broken aws-sdk-cpp pcfiles a while ago, but hacked it up with a local overlay fix using `sed` since I didn't have the time to stitch together the proper, clean fix.

I've built and verified this fixes the issue; can you send a backport PR to 20.03 as well?

Separately, it'd be nice if we had some kind of automated pkg-config file validation check, like making sure includedirs and libdirs actually exist, which would fail the build if not.

**Pull request merged**
