### PR TITLE
networkmanager{,applet,plugins}, modemmanager: update

### PR DESCRIPTION
**Pull request by groxxda**
###### Motivation for this change

new versions everywhere

**depends on #19304 and #19305**
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Tested with gnome 3.22 only. Plugins not tested for functionality since i dont have any of the required remotes.

### CODE REVIEW

**Comment by grahamc** [comment]
I merged these three PR together and successfully bulit everything. Don't know if it actually works.

**Comment by fpletz** [comment]
LGTM, but you should use the attribute names of the packages in the commit message as they appear in `pkgs/top-level/all-packages.nix`.

**Comment by groxxda** [comment]
nox reported no errors (only webkitgtk214, but that's unrelated)

**Comment by groxxda** [comment]
@fpletz fixed the commit messages

**Pull request merged**
