### PR TITLE
Python Updates 2022-09-15

### PR DESCRIPTION
**Pull request by mweinelt**
This is a major python updates run.

Hydra project: https://hydra.nixos.org/jobset/nixpkgs/python-updates
Regressions: https://malob.github.io/nix-review-tools-reports/

Previos python-updates run https://github.com/NixOS/nixpkgs/pull/181620

### CODE REVIEW

**Comment by FRidh** [comment]
Fixing scipy using https://github.com/NixOS/nixpkgs/pull/180243

**Comment by mweinelt** [comment]
Ah cool, you migrated the build to meson. :+1:

**Comment by mweinelt** [comment]
@kirillrdy Can you take a look at awsebcli?

**Comment by kirillrdy** [comment]
> @kirillrdy Can you take a look at awsebcli?

https://github.com/NixOS/nixpkgs/pull/191844

**Comment by kirillrdy** [comment]
@mweinelt  after last rebase https://github.com/NixOS/nixpkgs/pull/191844 is no longer there

**Comment by mweinelt** [comment]
Oh wow, thanks for noticing. Will pick the commit when I get home.

**Comment by mweinelt** [comment]
Fixed.

**Comment by mweinelt** [comment]
@samuela jax needs an update because we needed to bump protobuf for google-api-core.

**Comment by samuela** [comment]
Hi @mweinelt thanks so much for the heads up! Will that upgrade be done in this PR or will it be necessary once this lands?

**Comment by mweinelt** [comment]
The protobuf update is in this tree. it will be merged into staging-next later today.

**Comment by mweinelt** [comment]
Too tired to do more fixes for now.

**Comment by trofi** [comment]
Did not verify the bisection, but suspect that 246216e599eefe157169d2deaec801206fd735d8 `python3Packages.afdko: 3.9.0 -> 3.9.1` broken the build in `staging` and `staging-next` of `python3Packages.afdko`:

```
$ nix build --no-link -f. python310Packages.afdko -L
...
python3.10-afdko> applying patch /nix/store/00r3wz6naq0nmrg7jnf2bgsppkf1ia6f-use-dynamic-system-antlr4-runtime.patch
python3.10-afdko> patching file CMakeLists.txt
python3.10-afdko> Hunk #1 succeeded at 36 with fuzz 2.
python3.10-afdko> patching file c/makeotf/lib/cffread/CMakeLists.txt
python3.10-afdko> patching file c/makeotf/lib/hotconv/CMakeLists.txt
python3.10-afdko> Hunk #1 succeeded at 69 with fuzz 2.
python3.10-afdko> applying patch /nix/store/sickncxw0s730j6gfrnlsi5ndgysi6la-libxml2-cmake-find-package.patch
python3.10-afdko> patching file CMakeLists.txt
python3.10-afdko> Hunk #1 FAILED at 42.
python3.10-afdko> 1 out of 1 hunk FAILED -- saving rejects to file CMakeLists.txt.rej
```

**Comment by mweinelt** [comment]
`poetry` and `python3Packages.poetry` have no relationship. The former uses `poetry2nix` and that needs to be updated to pass setuptools where appropriate. This is due to 86ab83260fa002c3a0bab81d5965b6edff376759.

**Comment by cpcloud** [comment]
> `poetry` and `python3Packages.poetry` have no relationship.=

I am aware :)

Thanks for the clarification!

**Comment by smaret** [comment]
I've just realized that this update broke one of the package I maintain (which is  fixed in #194642). Would it be possible to notify the maintainers of all the packages that are updated during these mass updates? This would give us a chance to fix things before they land on master.

If it's not possible for technical reasons to ping all maintainers, perhaps it would make sense to have a python-maintainer team on GH?

**Comment by mweinelt** [comment]
> Would it be possible to notify the maintainers of all the packages that are updated during these mass updates?

Sadly not. The python package set has over 5000 packages and GitHub allows us to do 15 review requests.

> If it's not possible for technical reasons to ping all maintainers, perhaps it would make sense to have a python-maintainer team on GH?

That's a good idea. But we'd need some tooling that aggregates maintainers in `python3Packages`, resolves their github username, and updates the team list regularly.

**Comment by mweinelt** [comment]
We have roughly 670 python package maintainers, this is going to be rough and needs some discussion.

**Pull request merged**
