### PR TITLE
[staging] boost: default to boost 1.77 and refactor

### PR DESCRIPTION
**Pull request by hjones2199**
###### Motivation for this change
Most packages that depend on the boost libraries in nixpkgs are pointing at the unversioned "boost" package. Unversioned boost is currently 1.69.0, which was released in 2018. The default should be the newest boost library available (1.77). I expect build-time breakages, but it should be fairly straightforward to pin broken packages to an older boost revision once they are identified.

The level of divergence (particularly the addition of boost-build) since I submitted #120259, and the fact that I wanted to combine the addition of boost 1.77 into the same PR made it easier to start the request from scratch.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hjones2199** [comment]
Do to the addition of patches in boost-build, boost 1.77 currently fails in the patch phase. Solving that without breaking old versions of boost on darwin is needed.

**Comment by oxalica** [comment]
What's blocking this issue now? Is it just `uhd`?

**Comment by trofi** [comment]
`arc_unpacker` now fails it's own tests in `staging-next`. Bisected down to eca50883fc25ecc4b27a9ec3e694f261bba2f21e  `boost: default to boost 1.77`:

```
$ nix build -f. arc_unpacker -L
...
arc_unpacker-unstable> /build/source/tests/dec/cat_system/int_archive_decoder_test.cc:38
arc_unpacker-unstable> ...............................................................................
arc_unpacker-unstable> /build/source/tests/test_support/decoder_support.cc:35: FAILED:
arc_unpacker-unstable>   {Unknown expression after the reported line}
arc_unpacker-unstable> due to unexpected exception with message:
arc_unpacker-unstable>   Premature end of file
```

**Comment by veprbl** [comment]
@trofi Right, that's #151469

**Pull request merged**
