### PR TITLE
maintainers: add artemis

### PR DESCRIPTION
**Pull request by Arteneko**
###### Description of changes

added myself to maintainers

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by JulienMalka — COMMENTED** [review]
You typically add yourself as a maintainer in the same PR as creating a new package or updating a package. Adding yourself to the ``maintainer-list`` without adding yourself in the ``meta.maintainers`` field of a package/module has no effect AFAIK.

**Comment by Arteneko** [comment]
I found [the opposite](https://nixos.org/manual/nixpkgs/stable/#var-meta-maintainers) detailed in the manual, in a few other PRs, and when talking around with some other users/maintainers though

**Comment by Mindavi** [comment]
The maintainer list is mainly there for contact details and to know who the reviewers will be for package updates. For personal repos it doesn't add much value.

I prefer not to have maintainers which don't actually maintain a package, since it just adds noise to the maintainer list.

Hope you understand this.

**Comment by Mindavi** [comment]
The maintainer list is mainly there for contact details and to know who the reviewers will be for package updates. For personal repos it doesn't add much value.

I prefer not to have maintainers which don't actually maintain a package, since it just adds noise to the maintainer list.

Hope you understand this.

**Comment by Arteneko** [comment]
Perfectly understandable, yes
Thanks for the info!

Maybe it would be worthwhile to note this in the nixpkgs manual? Because I really struggled to find whether or not adding a maintainer was in its own PR, so I'm sure someone else may need this info.

I'm gonna see to find a bit of time to propose an edit in the manual

**Comment by Mindavi** [comment]
A mention in the manual might be a good idea, yeah. I do see these PRs more often because people sometimes think you can become a maintainer without maintaining any packages, so having that explicitly mentioned somewhere wouldn't be a bad idea.

**Pull request closed without merging**
