### PR TITLE
ruby: 2.6.7 -> 2.7.3

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change

I tested this a bit and doesn't seem to be any major breakage, so I'd like this be merged for the 21.05 release

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 120058` at 91718290 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>473 packages marked as broken and skipped:</summary>
  <ul>
    <li>agdaPackages.iowa-stdlib</li>
    <li>aldor</li>
    <li>aqemu</li>
    <li>atom-beta</li>
    <li>autotrace</li>
    <li>bareos</li>
    <li>bonfire</li>
    <li>cassandra_2_1</li>
    <li>cassandra_2_2</li>
    <li>dockbarx</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>5367 packages skipped due to time constraints:</summary>
  <ul>
    <li>AusweisApp2</li>
    <li>DisnixWebService</li>
    <li>Fabric (python38Packages.Fabric)</li>
    <li>MIDIVisualizer</li>
    <li>R</li>
    <li>Sylk</li>
    <li>_1password-gui</li>
    <li>_3llo</li>
    <li>abcl</li>
    <li>abiword</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>195 packages built successfully:</summary>
  <ul>
    <li>bcat</li>
    <li>bundler</li>
    <li>bundler-audit</li>
    <li>colorls</li>
    <li>drake</li>
    <li>gist</li>
    <li>git-fame</li>
    <li>h</li>
    <li>homesick</li>
    <li>maphosts</li>
    <li>matter-compiler</li>
    <li>nix-top</li>
    <li>nix-universal-prefetch</li>
    <li>ocl-icd</li>
    <li>one_gadget</li>
    <li>overcommit</li>
    <li>papertrail</li>
    <li>puppet-lint</li>
    <li>rake</li>
    <li>reckon</li>
    <li>redis-dump</li>
    <li>ruby</li>
    <li>ruby-zoom</li>
    <li>rubyPackages.CFPropertyList</li>
    <li>rubyPackages.RubyInline</li>
    <li>rubyPackages.ZenTest</li>
    <li>rubyPackages.actionmailbox</li>
    <li>rubyPackages.actionmailer</li>
    <li>rubyPackages.actionpack</li>
    <li>rubyPackages.actiontext</li>
    <li>rubyPackages.actionview</li>
    <li>rubyPackages.activejob</li>
    <li>rubyPackages.activemodel</li>
    <li>rubyPackages.activerecord</li>
    <li>rubyPackages.activestorage</li>
    <li>rubyPackages.activesupport</li>
    <li>rubyPackages.addressable</li>
    <li>rubyPackages.ast</li>
    <li>rubyPackages.atomos</li>
    <li>rubyPackages.awesome_print</li>
    <li>rubyPackages.bacon</li>
    <li>rubyPackages.builder</li>
    <li>rubyPackages.certified</li>
    <li>rubyPackages.claide</li>
    <li>rubyPackages.clamp</li>
    <li>rubyPackages.cocoapods</li>
    <li>rubyPackages.cocoapods-art</li>
    <li>rubyPackages.cocoapods-clean</li>
    <li>rubyPackages.cocoapods-clean_build_phases_scripts</li>
    <li>rubyPackages.cocoapods-core</li>
    <li>rubyPackages.cocoapods-coverage</li>
    <li>rubyPackages.cocoapods-deintegrate</li>
    <li>rubyPackages.cocoapods-disable-podfile-validations</li>
    <li>rubyPackages.cocoapods-downloader</li>
    <li>rubyPackages.cocoapods-expert-difficulty</li>
    <li>rubyPackages.cocoapods-fix-react-native</li>
    <li>rubyPackages.cocoapods-generate</li>
    <li>rubyPackages.cocoapods-open</li>
    <li>rubyPackages.cocoapods-plugins</li>
    <li>rubyPackages.cocoapods-search</li>
    <li>rubyPackages.cocoapods-stats</li>
    <li>rubyPackages.cocoapods-testing</li>
    <li>rubyPackages.cocoapods-trunk</li>
    <li>rubyPackages.cocoapods-try</li>
    <li>rubyPackages.cocoapods-wholemodule</li>
    <li>rubyPackages.coderay</li>
    <li>rubyPackages.colorator</li>
    <li>rubyPackages.colored</li>
    <li>rubyPackages.colored2</li>
    <li>rubyPackages.concurrent-ruby</li>
    <li>rubyPackages.crass</li>
    <li>rubyPackages.daemons</li>
    <li>rubyPackages.data_objects</li>
    <li>rubyPackages.diff-lcs</li>
    <li>rubyPackages.docile</li>
    <li>rubyPackages.domain_name</li>
    <li>rubyPackages.dotenv</li>
    <li>rubyPackages.erubi</li>
    <li>rubyPackages.escape</li>
    <li>rubyPackages.excon</li>
    <li>rubyPackages.faraday</li>
    <li>rubyPackages.faraday-excon</li>
    <li>rubyPackages.faraday-net_http</li>
    <li>rubyPackages.faraday-net_http_persistent</li>
    <li>rubyPackages.ffi</li>
    <li>rubyPackages.ffi-compiler</li>
    <li>rubyPackages.fog-core</li>
    <li>rubyPackages.fog-json</li>
    <li>rubyPackages.formatador</li>
    <li>rubyPackages.forwardable-extended</li>
    <li>rubyPackages.fourflusher</li>
    <li>rubyPackages.fuzzy_match</li>
    <li>rubyPackages.gitlab-markup</li>
    <li>rubyPackages.globalid</li>
    <li>rubyPackages.hashie</li>
    <li>rubyPackages.highline</li>
    <li>rubyPackages.hike</li>
    <li>rubyPackages.hitimes</li>
    <li>rubyPackages.http-accept</li>
    <li>rubyPackages.http-cookie</li>
    <li>rubyPackages.httpclient</li>
    <li>rubyPackages.i18n</li>
    <li>rubyPackages.jekyll-watch</li>
    <li>rubyPackages.jmespath</li>
    <li>rubyPackages.json</li>
    <li>rubyPackages.json_pure</li>
    <li>rubyPackages.jwt</li>
    <li>rubyPackages.kramdown</li>
    <li>rubyPackages.kramdown-parser-gfm</li>
    <li>rubyPackages.kramdown-rfc2629</li>
    <li>rubyPackages.liquid</li>
    <li>rubyPackages.listen</li>
    <li>rubyPackages.loofah</li>
    <li>rubyPackages.mab</li>
    <li>rubyPackages.magic</li>
    <li>rubyPackages.mail</li>
    <li>rubyPackages.marcel</li>
    <li>rubyPackages.mercenary</li>
    <li>rubyPackages.method_source</li>
    <li>rubyPackages.mime-types</li>
    <li>rubyPackages.mime-types-data</li>
    <li>rubyPackages.mini_mime</li>
    <li>rubyPackages.mini_portile2</li>
    <li>rubyPackages.minitest</li>
    <li>rubyPackages.molinillo</li>
    <li>rubyPackages.multi_json</li>
    <li>rubyPackages.multipart-post</li>
    <li>rubyPackages.mustermann</li>
    <li>rubyPackages.nanaimo</li>
    <li>rubyPackages.nap</li>
    <li>rubyPackages.native-package-installer</li>
    <li>rubyPackages.net-scp</li>
    <li>rubyPackages.net-ssh</li>
    <li>rubyPackages.netrc</li>
    <li>rubyPackages.nokogiri</li>
    <li>rubyPackages.osx_keychain</li>
    <li>rubyPackages.parallel</li>
    <li>rubyPackages.parser</li>
    <li>rubyPackages.pathutil</li>
    <li>rubyPackages.pkg-config</li>
    <li>rubyPackages.polyglot</li>
    <li>rubyPackages.pry</li>
    <li>rubyPackages.public_suffix</li>
    <li>rubyPackages.racc</li>
    <li>rubyPackages.rack</li>
    <li>rubyPackages.rack-protection</li>
    <li>rubyPackages.rack-test</li>
    <li>rubyPackages.rails-dom-testing</li>
    <li>rubyPackages.rails-html-sanitizer</li>
    <li>rubyPackages.rainbow (rubyPackages_2_7.rainbow)</li>
    <li>rubyPackages.rake</li>
    <li>rubyPackages.rb-fsevent</li>
    <li>rubyPackages.rb-inotify</li>
    <li>rubyPackages.rb-readline</li>
    <li>rubyPackages.red-colors</li>
    <li>rubyPackages.redis</li>
    <li>rubyPackages.regexp_parser</li>
    <li>rubyPackages.rexml</li>
    <li>rubyPackages.rouge</li>
    <li>rubyPackages.rspec-core</li>
    <li>rubyPackages.rspec-expectations</li>
    <li>rubyPackages.rspec-mocks</li>
    <li>rubyPackages.rspec-support</li>
    <li>rubyPackages.rubocop-ast</li>
    <li>rubyPackages.ruby-progressbar</li>
    <li>rubyPackages.ruby2_keywords</li>
    <li>rubyPackages.rubyzip</li>
    <li>rubyPackages.safe_yaml</li>
    <li>rubyPackages.simplecov</li>
    <li>rubyPackages.simplecov-html</li>
    <li>rubyPackages.simplecov_json_formatter</li>
    <li>rubyPackages.sinatra</li>
    <li>rubyPackages.slather</li>
    <li>rubyPackages.slop</li>
    <li>rubyPackages.sprockets</li>
    <li>rubyPackages.sprockets-rails</li>
    <li>rubyPackages.terminal-table</li>
    <li>rubyPackages.thor</li>
    <li>rubyPackages.tilt</li>
    <li>rubyPackages.treetop</li>
    <li>rubyPackages.tzinfo</li>
    <li>rubyPackages.unf</li>
    <li>rubyPackages.unf_ext</li>
    <li>rubyPackages.unicode-display_width</li>
    <li>rubyPackages.websocket-driver</li>
    <li>rubyPackages.websocket-extensions</li>
    <li>rubyPackages.xcodeproj</li>
    <li>rubyPackages.xctasks</li>
    <li>rubyPackages.yard</li>
    <li>rubyPackages.zeitwerk</li>
    <li>rubyPackages_2_6.rainbow</li>
    <li>rufo</li>
    <li>terraforming</li>
    <li>tmuxPlugins.jump</li>
    <li>wayback_machine_downloader</li>
  </ul>
</details>

**Comment by shepting** [comment]
@marsam Will this update `bundler` to 2.2.16 as well?

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by marsam** [comment]
>Will this update bundler to 2.2.16 as well?

nop, this just updates the default ruby. I plan to update bundler in another PR

**Review by thefloweringash — APPROVED** [review]

**Comment by vcunat** [comment]
It does not build on x86_64-darwin: https://hydra.nixos.org/build/142630631

Also perhaps note that at merge time, mass-rebuild "breaking changes" for 21.05 [weren't allowed](https://discourse.nixos.org/t/21-05-release-schedule/12528) anymore.  (I can't really judge the risks myself, e.g. level of incompatibility between 2.6 and 2.7.)

**Comment by thefloweringash** [comment]
Looks like something in the cc-wrapper for clang. 

```
configure:8254: checking whether LDFLAGS is valid
configure:8274: clang -o conftest -g -O2    conftest.c  >&5
ld: warning: directory not found for option '-L/nix/store/qi9244lsyk081f00sa2na21qz77xqfnc-clang-7.1.0/lib'
configure:8274: $? = 0
configure: failed program was:
[snipped]
configure:8280: result: no
configure:8282: error: something wrong with LDFLAGS=""
```

Which comes from `cc-ldflags`.

```
$ cd /nix/store/gq4rn1jh66cww2n566znrfmgm182qkvw-clang-wrapper-7.1.0/nix-support
$ grep -e /nix/store/qi9244lsyk081f00sa2na21qz77xqfnc-clang-7.1.0/lib -r .
./cc-cflags:-target x86_64-apple-darwin  -B/nix/store/qi9244lsyk081f00sa2na21qz77xqfnc-clang-7.1.0/lib -arch x86_64 -resource-dir=/nix/store/gq4rn1jh66cww2n566znrfmgm182qkvw-clang-wrapper-7.1.0/resource-root
./cc-ldflags: -L/nix/store/qi9244lsyk081f00sa2na21qz77xqfnc-clang-7.1.0/lib  -L/nix/store/d51irgw2cb1md3yn5xx7snikm8m1zz3f-libc++-7.1.0/lib
```

Which I think comes from https://github.com/nixos/nixpkgs/blob/f4d69ad1f211b18f93d3b39d20d9d3c5a5b5fb71/pkgs/build-support/cc-wrapper/default.nix#L392-L393

Probably related to #111487. cc @Ericson2314

Perhaps something odd with `getLib`?

```
nix-repl> toString stdenv.cc.cc.lib
"/nix/store/qliqicaaqsaqlism5qq4la4wkrbnw3rl-clang-7.1.0-lib"

nix-repl> toString (lib.getLib stdenv.cc.cc)
"/nix/store/qi9244lsyk081f00sa2na21qz77xqfnc-clang-7.1.0"
```

**Comment by vcunat** [comment]
`getLib` and similar behave in the way that if you've specified an output once, it won't change.  For example, `getLib (getBin pkgs.foo)` will prefer `.bin`.  I suspect something like that happened here with `stdenv.cc.cc`.

**Comment by vcunat** [comment]
The getLib discrepancy is solved in PR #122554.  (I could only test eval-time locally.)

**Comment by vcunat** [comment]
Ruby build succeeded again on Hydra: https://hydra.nixos.org/build/142889679

**Pull request merged**
