### PR TITLE
fira: remove Fira Mono

### PR DESCRIPTION
**Pull request by hellerbarde**
(This is my first pull request here and I'm mildly overwhelmed with the things I should do below. If someone wants to help, I'd appreciate it. I'm not even sure how I go about testing the change on my own system. )

###### Description of changes

Change the build commands to only copy FiraSans*.otf. Fira Mono is covered by a different derivation "fira-mono"

I ran into an error when I tried to install "fira" and "fira-mono", so I investigated it and the reason is that the mozilla/Fira repository contains a sneaky 3 extra `FiraMono*.otf` files. They are being packaged by both [fira-mono](https://github.com/NixOS/nixpkgs/blob/nixpkgs-unstable/pkgs/data/fonts/fira-mono/default.nix) and [fira](https://github.com/NixOS/nixpkgs/blob/nixpkgs-unstable/pkgs/data/fonts/fira/default.nix)

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wegank** [comment]
cc @rycee

**Comment by rycee** [comment]
Makes sense, I think. And yeah, the apostrophe package will need to be updated as well. Could you include the apostrophe change as well?

**Comment by Pheoxy** [comment]
Running into this as well.

```
building '/nix/store/g4yip9z58721xxcb196yzvjl1h6l019p-system-fonts.drv'...
warning: different permissions in `/nix/store/z6f505d9gb9228npm1mnykdr3a10j2an-fira-4.202/share/fonts/opentype/FiraMono-Bold.otf' and `/nix/store/l2y2djl6jail954c9rfjl4n6zahmkg5d-fira-mono-4.202/share/fonts/opentype/FiraMono-Bold.otf': 0555 <-> 0444 at /nix/store/by3lmvq7ldg20ivmad96p6kzb9pwb8bs-builder.pl line 103.
error: collision between `/nix/store/l2y2djl6jail954c9rfjl4n6zahmkg5d-fira-mono-4.202/share/fonts/opentype/FiraMono-Bold.otf' and `/nix/store/z6f505d9gb9228npm1mnykdr3a10j2an-fira-4.202/share/fonts/opentype/FiraMono-Bold.otf'
error: builder for '/nix/store/g4yip9z58721xxcb196yzvjl1h6l019p-system-fonts.drv' failed with exit code 2
```

I've disabled fira fonts in my `configuration.nix` file for now.

**Comment by sternenseemann** [comment]
My problem with this change is that it'll break downstream user's systems silently: Fira Mono will just disappear. Consequently this needs at least a changelog entry.

An alternative, non-breaking way of solving the inconsistency would be to drop `fira-mono` and alias it to `fira` (it's not called `fira-sans` anyways).

**Comment by wegank** [comment]
Or we can deprecate `fira` in favour of `fira-sans`.

**Comment by sternenseemann** [comment]
Do the benefits outweigh the costs of downstream users needing to potentially debug their systems and adjust their configuration?

**Comment by wegank** [comment]
Aliasing `fira-mono` to `fira` will result in `fira-mono` bringing `FiraSans*.ttf`, which is unexpected.

The proper fix is to drop one of the two, and human intervention is required in both case. And dropping `fira` is just better.

**Comment by Pheoxy** [comment]
In the context of configurability, I would prefer if I could choose either firaSans or firaMono fonts separately and then an Alias called firaFull that includes both.

**Comment by hellerbarde** [comment]
I'm really sorry I lost track of doing this PR. I can see that a bunch of people got involved. Is there anything you need me to do at the moment? If yes, I will make time over the weekend.

**Comment by abathur** [comment]
@wegank Did you have any specific changes in mind when you set this to draft in April? 

Not trying to force a merge decision... I just read hellerbarde's comment and couldn't figure out myself whether this has hit an impasse, or the ball is in his court, or if there's some other blocker.

**Pull request closed without merging**
