### PR TITLE
quickemu: 4.9.4 -> 4.9.4-unstable-2024-05-28

### LINKED ISSUE #321384: quickemu: bugged release that is resolved on latest revision
### Describe the bug
<https://github.com/quickemu-project/quickemu/issues/1287>. There is a bug in the latest release of quickemu (present in nixpkgs), that sends invalid flags to qemu and thus doesn't work for MacOS (maybe others too).

The fix I was planning to PR was to simply move the src to point to the most current revision. I wasn't 100% sure if that was something that I should do however, given it would set the precedent that we follow revisions for this package instead of the version tag, which may add maintenance burden.

Just wanted opinions before I made a PR, would it be acceptable to bump the revision temporarily to avoid this issue? It's niche but its real and could affect users of this package.

### Steps To Reproduce
1. `nix shell nixpkgs#quickemu`
2. `quickget macos ventura`
3. `quickemu --vm macos-ventura.conf`

### Expected behavior
Pops open a Qemu window with the appropriate screens.

### Additional context
Fails with a strange "macos-ventura/macos-ventura.pid file not found", but it is related to the bugged release.

### Notify maintainers
@FedX-sudo 
@flexiondotorg 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
- host os: `Linux 6.6.33, NixOS, 24.11 (Vicuna), 24.11.20240616.b60ebf5`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.18.2`
- nixpkgs: `/nix/store/5w7nhyvrgsa81h0kyifmbl6j97hvlzh5-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Frontear**
## Description of changes

As per a bug described here (https://github.com/quickemu-project/quickemu/issues/1287), I've bumped quickemu temporarily to a revision.

I've also removed the patch added by @eclairevoyant as its part of the changes in the current revision.

I pushed revision rather than writing a patch because I could not easily determine if the fixes occurred in a single commit or multiple (almost 200 commits since 4.9.4). If patches are preferred to a revision change I can re-check and appropriately rebase.

No regressions or other issues noted, testing with the following VM configurations

- `quickget windows 11`
- `quickget android 9.0 x86_64`
- `quickget macos sonoma`

Closes https://github.com/NixOS/nixpkgs/issues/321384

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by eclairevoyant** [comment]
The version should be updated per guidelines:

https://github.com/NixOS/nixpkgs/blob/44e3ac88c64ddf112af9b46136cc6fad58148d21/pkgs/README.md?plain=1#L352-L354

Then the commit message and PR title as well

**Comment by Frontear** [comment]
> The version should be updated per guidelines:
> 
> https://github.com/NixOS/nixpkgs/blob/44e3ac88c64ddf112af9b46136cc6fad58148d21/pkgs/README.md?plain=1#L352-L354
> 
> Then the commit message and PR title as well

Will do, thank you!

**Comment by Frontear** [comment]
woops forgot to actually commit the version name

**Comment by eclairevoyant** [comment]
lgtm on the surface but I'd want to get the maintainers' opinions if possible

**Review by eclairevoyant — COMMENTED** [review]
one other thing, you'd need to hardcode `version = "4.9.5";` in the `testVersion` call for tests to pass

**Comment by Frontear** [comment]
didnt even think to re-run tests, guess this is a good reminder. would it be preferred to amend the commit to fix both tests and version change in one commit, for git history cleanliness?

**Comment by eclairevoyant** [comment]
yes, it's the same logical change

**Review by flexiondotorg — APPROVED** [review]

**Review by eclairevoyant — APPROVED** [review]

**Pull request merged**
