### PR TITLE
faiss: Fix missing phase hooks, set `make -j` correctly

### PR DESCRIPTION
**Pull request by nh2**
## Description of changes

This package lacks `runHook`s in its phases (), and also has `make` invocation without correct `-j`, making the build take much longer than necessary.

See https://nixos.org/manual/nixpkgs/stable/#sec-stdenv-phases

> When overriding a phase, for example `installPhase`, it is important to start with `runHook preInstall` and end it with `runHook postInstall`

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by paparodeo — COMMENTED** [review]
you can use `buildFlags` to specify the build targets and then eliminate the `buildPhase` and then use `postBuild` to do the python only wheel build. likewise, in `installPhase` remove the call to `make` and move the contents to `postInstall` sans runHook.

<details><summary>suggested changes.diff</summary>

```diff
diff --git a/pkgs/development/libraries/science/math/faiss/default.nix b/pkgs/development/libraries/science/math/faiss/default.nix
index 7aab0ba0f05a..c2a380a2d65b 100644
--- a/pkgs/development/libraries/science/math/faiss/default.nix
+++ b/pkgs/development/libraries/science/math/faiss/default.nix
@@ -97,35 +97,27 @@ stdenv.mkDerivation {
     "-DCUDAToolkit_INCLUDE_DIR=${cudaJoined}/include"
   ];
 
+  buildFlags = [
+    "faiss"
+    "demo_ivfpq_indexing"
+  ] ++ lib.optionals pythonSupport [
+    "swigfaiss"
+  ];
 
   # pip wheel->pip install commands copied over from opencv4
 
-  buildPhase = ''
-    runHook preBuild
-
-    make -j $NIX_BUILD_CORES faiss
-    make -j $NIX_BUILD_CORES demo_ivfpq_indexing
-    ${lib.optionalString pythonSupport ''
-      make -j swigfaiss
-      (cd faiss/python &&
-      python -m pip wheel --verbose --no-index --no-deps --no-clean --no-build-isolation --wheel-dir dist .)
-    ''}
-
-    runHook postBuild
+  postBuild = lib.optionalString pythonSupport ''
+    (cd faiss/python &&
+     python -m pip wheel --verbose --no-index --no-deps --no-clean --no-build-isolation --wheel-dir dist .)
   '';
 
-  installPhase = ''
-    runHook preInstall
-
-    make -j $NIX_BUILD_CORES install
+  postInstall = ''
     mkdir -p $demos/bin
     cp ./demos/demo_ivfpq_indexing $demos/bin/
     ${lib.optionalString pythonSupport ''
       mkdir -p $out/${pythonPackages.python.sitePackages}
       (cd faiss/python && python -m pip install dist/*.whl --no-index --no-warn-script-location --prefix="$out" --no-cache)
     ''}
-
-    runHook postInstall
   '';
 
   fixupPhase = lib.optionalString (pythonSupport && cudaSupport) ''

```
</details>

**Comment by nh2** [comment]
> you can use `buildFlags` to specify the build targets and then eliminate the `buildPhase` and then use `postBuild` to do the python only wheel build. likewise, in `installPhase` remove the call to `make` and move the contents to `postInstall` sans runHook.

@paparodeo I will leave that type of cleanup to somebody else, I'm only fixing what's wrong here due to being out of time for this weekend.

**Comment by paparodeo** [comment]
> > you can use `buildFlags` to specify the build targets and then eliminate the `buildPhase` and then use `postBuild` to do the python only wheel build. likewise, in `installPhase` remove the call to `make` and move the contents to `postInstall` sans runHook.
> 
> @paparodeo I will leave that type of cleanup to somebody else, I'm only fixing what's wrong here due to being out of time for this weekend.

luckily i already did the work and provided a diff -- you just need to apply it.

**Comment by paparodeo** [comment]
> > you can use `buildFlags` to specify the build targets and then eliminate the `buildPhase` and then use `postBuild` to do the python only wheel build. likewise, in `installPhase` remove the call to `make` and move the contents to `postInstall` sans runHook.
> 
> @paparodeo I will leave that type of cleanup to somebody else, I'm only fixing what's wrong here due to being out of time for this weekend.

ok. superseded by https://github.com/NixOS/nixpkgs/pull/320419

**Comment by SomeoneSerge** [comment]
@nh2 thanks; from the looks of it, we can and should merge @paparodeo's version directly, but I do want to comment that I don't think there's anything wrong with incremental improvements and with people only having limited time, and your PR is appreciated

**Comment by nh2** [comment]
@SomeoneSerge Yes all good, I completely agree that doing it as #320419 does it is an even better way.

**Pull request closed without merging**
