### PR TITLE
google-chrome: 57.0.2987.133 -> 58.0.3029.96

### PR DESCRIPTION
**Pull request by benley**
stable: 57.0.2987.133 -> 58.0.3029.96
beta: 58.0.3029.68 -> 59.0.3071.36
dev: 59.0.3067.0 -> 60.0.3088.3

###### Motivation for this change
Upstream release

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ianfarmer** [comment]
It seems like this doesn't build:

https://hydra.nixos.org/build/52547874

**Comment by joachifm** [comment]
@benley any idea why this builds for you but not on hydra?

**Comment by FRidh** [comment]
Note that the name of the commit is wrong: this is chromium, note chrome.

**Comment by jcumming** [comment]
Did builder changes not get committed?

**Comment by benley** [comment]
Agh crap, I failed to realize that this would affect the chromium builds and not just the google-chrome debs.  Is there an obvious fix?  Please feel free to revert this commit if it's going to take a while to find a proper fix, because I won't have time to work on it until tomorrow.

**Comment by benley** [comment]
(for what it's worth, it's not incorrect to describe this as google-chrome, because it actually is the way to update the Chrome derviations.  I guess it's _also_ chromium, though.)

**Pull request merged**
