### PR TITLE
confluent-kafka: init at 0.9.4

### PR DESCRIPTION
**Pull request by mlieberman85**
###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mlieberman85** [comment]
@copumpkin

**Review by copumpkin — APPROVED** [review]
Looks good to me, and I think this is the new preferred style over the giant pile o' python packages, but I'll wait for @FRidh to confirm.

**Review by FRidh — CHANGES_REQUESTED** [review]
Tests fail on at least 3.5.

**Comment by FRidh** [comment]
Likely they passed on Mac because you're running without sandbox and so setuptools was able to download the package that is needed for the tests.

**Comment by mlieberman85** [comment]
Looks like I need to also add 3 python avro packages (avro-python3, avro, fastavro.) Should I put those in separate pull requests?

**Comment by copumpkin** [comment]
I'd just add more commits to this PR, but keep a single PR.

**Comment by mlieberman85** [comment]
Looks like there's actually the right avro package I need already in nixpkgs. Got the tests to find the avro package, but I'm now running into an issue where it can't find verifiable_client.

verifiable_client is a module included in the tests folder of the python source of this package.

**Comment by mlieberman85** [comment]
@FRidh @copumpkin I updated my PR. Turns out the tests were failing because of some missing packages, but even after installing them they still fail because of issues with their tests (for python 3) in that release.

I fixed the imports to get it working with avro support and with python3.

**Pull request merged**
