### PR TITLE
bundler 1.14.6 -> 1.16.1

### PR DESCRIPTION
**Pull request by polynomial**
###### Motivation for this change

I was trying to use `vagrant plugin install vagrant-aws` which was failing with:
```
Installing the 'vagrant-aws' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies bundler (= 1.14.6) and bundler (= 1.16.1)
  Activated bundler-1.16.1
  which does not match conflicting dependency (= 1.14.6)

  Conflicting dependency chains:
    bundler (= 1.16.1), 1.16.1 activated

  versus:
    bundler (= 1.14.6)

  Gems matching bundler (= 1.14.6):
    bundler-1.14.6
```

###### Things done
I used bundix to create a new gemset.nix and then updated the version of bundler to match what I think ruby expects:
```
$ git clone git@github.com:hashicorp/vagrant.git
$ cd vagrant
$ bundix -l
$ cp gemset.nix /path/to/nixpkgs/pkgs/development/tools/vagrant
```

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
duplicate of #30881 , see comments there

**Comment by polynomial** [comment]
Thanks @xeji

**Comment by Mic92** [comment]
For all the pure souls who have to use vagrant, the following workaround for vagrant: #36880 is a short term solution.

**Comment by Mic92** [comment]
I think we can upgrade bundler now, since gitlab was fixed: https://github.com/NixOS/nixpkgs/commit/94f5e5ad14e99700e82576167515ba784dbfe98b

**Comment by Mic92** [comment]
part of https://github.com/NixOS/nixpkgs/pull/39597

**Pull request closed without merging**
