### PR TITLE
bomber-go: 0.3.4 -> 0.4.4

### PR DESCRIPTION
**Pull request by aaronjheng**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by fabaff — COMMENTED** [review]
I see this:

```bash
$ nix build --extra-experimental-features nix-command no-url-literals --no-link --keep-going --no-allow-import-from-derivation --option build-use-sandbox relaxed -f /home/fab/.cache/nixpkgs-review/pr-250730/build.nix
error: builder for '/nix/store/mwgaq755idwj7dsy9y6v0330sq9cis10-bomber-go-0.4.4.drv' failed with exit code 1;
       last 10 log lines:
       > github.com/devops-kung-fu/bomber/lib/enrichment.Enrich({0xc00005d400, 0x4, 0x4})
       >      /build/source/lib/enrichment/epss.go:29 +0x457
       > github.com/devops-kung-fu/bomber/lib/enrichment.TestEnrich(0x0?)
       >       /build/source/lib/enrichment/epss_test.go:26 +0x65
       > testing.tRunner(0xc000138680, 0x761f28)
       >    /nix/store/54qksp8q7lwwhpjyxqbhzvrmn883gkpy-go-1.20.7/share/go/src/testing/testing.go:1576 +0x10b
       > created by testing.(*T).Run
       >         /nix/store/54qksp8q7lwwhpjyxqbhzvrmn883gkpy-go-1.20.7/share/go/src/testing/testing.go:1629 +0x3ea
       > FAIL github.com/devops-kung-fu/bomber/lib/enrichment 0.004s
       > FAIL
       For full logs, run 'nix-store -l /nix/store/mwgaq755idwj7dsy9y6v0330sq9cis10-bomber-go-0.4.4.drv'.
error: 1 dependencies of derivation '/nix/store/k0jxphg53q9qv4h5kk7xmk68mnfkpj6b-review-shell.drv' failed to build
```

**Comment by matthiasbeyer** [comment]
Result of `nixpkgs-review pr 250730` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>bomber-go</li>
  </ul>
</details>

**Comment by aaronjheng** [comment]
All done.

**Review by fabaff — APPROVED** [review]
Change looks good to me.

**Pull request merged**
