### PR TITLE
easyrsa: 3.0.0 -> 3.0.8

### PR DESCRIPTION
**Pull request by numinit**
###### Motivation for this change

Getting latest version of easy-rsa. Slightly different NixOS compatibility patch required.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
Builds & runs, macos 10.14 too.

**Review by risicle — APPROVED** [review]

**Review by tomberek — APPROVED** [review]

**Comment by tomberek** [comment]
builds, runs, functions as expected on NixOS.

**Comment by numinit** [comment]
Revised to update easy-rsa to 3.0.8. No changes to compatibility patch required.

**Comment by markuskowa** [comment]
@GrahamcOfBorg build easyrsa

**Pull request merged**
