### PR TITLE
fdroidserver: 2.2.1 -> unstable-2023-10-23

### PR DESCRIPTION
**Pull request by linsui**
## Description of changes

F-Droid always runs on the master. The stable version is too outdated.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jugendhacker — COMMENTED** [review]
Looks good to me, but I'm not sure what's the general nixpkgs policy about unstable packages, so maybe we could need some help from a more experienced maintainer here?

**Comment by linsui** [comment]
Is there any policy? :)

**Comment by kirillrdy** [comment]
I am not aware of the policy, I've seen it happen for packages that haven't been "released" in more than a year.

may I suggest, if there is a need to run version other than what is latest release, file an issue upstream about making a new release.

**Comment by jugendhacker** [comment]
The only policy I know about is [about the version name](https://nixos.org/manual/nixpkgs/stable/#sec-package-naming) but you did follow it, so I guess this should be okay

**Comment by jugendhacker** [comment]
> I am not aware of the policy, I've seen it happen for packages that haven't been "released" in more than a year.
> 
> may I suggest, if there is a need to run version other than what is latest release, file an issue upstream about making a new release.

@linsui and I are both also involved in upstream and the problem is that upstream is basically moving to fast currently. Never the less it's definitely discussed to release more often. But for the time beeing I think unsing a unstable version is reasonable, as upstream introduced some breaking changes (e.g. changing the metadata formatting) which conflicts with users of the release versions

**Review by jugendhacker — APPROVED** [review]

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
If the stable version isn't working in the normal use case, we can switch to unstable.

**Pull request merged**
