### PR TITLE
thunderbird, thunderbird-bin: 78.1.1 -> 78.2.1, 68.11.0 -> 68.12.0

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

- Various security fixes (68 only)
- Updates and fixes.
- OpenPGP enabled by default (78 only). 

https://www.thunderbird.net/en-US/thunderbird/78.2.0/releasenotes/
https://www.thunderbird.net/en-US/thunderbird/78.2.1/releasenotes/
https://www.thunderbird.net/en-US/thunderbird/68.12.0/releasenotes/
https://www.mozilla.org/en-US/security/known-vulnerabilities/thunderbird/#thunderbird68.12

At this time, users of the Enigmail Add-on should not update to Thunderbird 78.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lourkeur** [comment]
commit description should read `thunderbird: 78.1.1 -> 78.2.0` right?

**Comment by taku0** [comment]
Yes. Fixed. Thank you.

**Comment by doronbehar** [comment]
PR title as well ?

**Review by vcunat — APPROVED** [review]
Seems OK.

I used the compiled `78.2.0` for over three days continuously &ndash; and now each of the four versions for several minutes.

**Pull request merged**
