### PR TITLE
[staging] elfutils: 0.182 -> 0.185, cleanup

### PR DESCRIPTION
**Pull request by r-burns**
Remove obsolete musl patches & musl-specific autoreconfHook
(same as https://git.alpinelinux.org/aports/commit/main/elfutils?id=a8779348058ef0f42d31c814d2792ccdc8062007)

cc @baloo for debuginfod testing against #112455 (still builds, but you might want to check it still works as well)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-burns** [comment]
cc @pjjw

**Comment by r-burns** [comment]
Rebased with no new changes yet.

Need to take a look at some more cleanups @trofi found independently:

* tests + installtests can now be run (requires shebang patching for tests/*.sh)
* zstd support can be enabled

Sound right?

**Review by trofi — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by pjjw** [comment]
thanks for the cleanup here!

**Pull request merged**
