### PR TITLE
hplip: Adds missing depdency `sip`

### PR DESCRIPTION
**Pull request by bkchr**
###### Motivation for this change

Fixes: https://github.com/NixOS/nixpkgs/issues/37857

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by cx405** [comment]
Wow, just noticed this absolutely randomly. Thank you very much, @bkchr!

**Comment by bkchr** [comment]
I just wanted to print for myself and observed that it did not work :D I found your issue while searching for the error message :)

**Comment by bkchr** [comment]
@jgeerds @ttuegel anyone could merge this?

**Comment by bjornfor** [comment]
Applied to master (8152db99d75e690b96e091b1b1a50f7325a30981).

Should it be backported? To 18.03 and 17.09?

**Comment by bkchr** [comment]
I think it needs to be backported to 18.03. I'm unsure about 17.09, because I don't know when it stopped working.

**Comment by bjornfor** [comment]
Cherry-picked to release-18.03 (fbc2cb78b7e9d71f75f32120a2c1fff546338e49).

**Comment by cx405** [comment]
@bjornfor @bkchr the 17.09 had the same situation. The deal is - while its possible to add the printer via CUPS inteface, its done via PPD, so basically the hplip is dead without this. I need yet to test if this actually fixes it or there are additional stuff missing.

Obviously "hp-doctor" will be broken by the very design of NixOS, however if hplip-gui starts and capable to add/detect consequences with printer/scanner/fax we are fine.

I also noted that:
1) printer will refuse to print any "custom paper", which is available through GIMP menu for example.
2) GIMP preview creates HUGE offset fields on some paper formats, however they are not printed
3) Qt-based applications, such as Okular refuse to accept some paper types - which is very similar to this: https://forum.kde.org/viewtopic.php?f=289&t=136325

**Comment by bkchr** [comment]
@cx405 I could add my printer with this this patch.

**Comment by cx405** [comment]
@bkchr Could I ask you how did you import the patched hplip? I am on 18.03 and doing:

```
{ config, pkgs, ... }:
let master = import <nixos-master> {}; in
{
...
services.printing.drivers = with pkgs; [ master.hplip ];
...
}
```
with
```
# nix-channel --list
nixos https://nixos.org/channels/nixos-18.03
nixos-master https://nixos.org/channels/nixos-unstable
```
leads to 1Gb pull of duplicate libraries. Could I ask you about advice for this type of per-package upgrade? I have HP Officejet pro 8600 (n911a).

**Comment by bkchr** [comment]
I'm following the master branch of nixpkgs as my channel. You will probably need to wait for `unstable` or `unstable-small` to contain the fix.

**Pull request closed without merging**
