### PR TITLE
staging-next 2024-04-12

### LINKED ISSUE #301380: Build failure: libpeas2 cannot find lua lgi package
### Steps To Reproduce

- Build `libpeas2` on `nixos-unstable` 

<details>
<summary><sub>NOTE: an earlier version of this report contained misleading info, preserved for posterity within the collapsed content</sub></summary>

~Unclear to me.~

~I have only been able to reproduce this error as a dependency of my (flake-based) NixOS system configuration on `aarch64-linux`.~

~None of these alone result in an error:~

```
# IGNORE THESE! SEE ABOVE UPDATE FOR CORRECT INFO
# nix build nixpkgs#libpeas
# nix build nixpkgs#gnome-builder
```

</details>

### Build log

Full: https://gist.github.com/montchr/bdfd613a3b747a33f32bb669a30ed265

Excerpt of `nixos-rebuild build --verbose` output (removed unrelated lines):

```
building '/nix/store/d9qijlw975ag76bj5vv82j6l94srcg62-libpeas-2.0.1.drv'...
error: builder for '/nix/store/d9qijlw975ag76bj5vv82j6l94srcg62-libpeas-2.0.1.drv' failed with exit code 1;
       last 10 log lines:
       > Compiler for C supports link arguments -Wl,-z,relro: YES
       > Compiler for C supports link arguments -Wl,-z,now: YES
       > Compiler for C supports link arguments -Wl,-Bsymbolic: YES
       > Compiler for C supports link arguments -fno-plt: YES
       > Compiler for C supports arguments -fvisibility=hidden: YES
       > Configuring config.h using configuration
       >
       > meson.build:404:2: ERROR: Problem encountered: Lua51 requested but failed to locate suitable Lua51 and LGI support
       >
       > A full log can be found at /build/libpeas-2.0.1/build/meson-logs/meson-log.txt
       For full logs, run 'nix log /nix/store/d9qijlw975ag76bj5vv82j6l94srcg62-libpeas-2.0.1.drv'.
error: 1 dependencies of derivation '/nix/store/zhishld4zw0dg7wh8zipbzq29ilwyvyi-gnome-builder-45.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/bjidb7n0krz58w16rwavz966g4p55yg9-gnome-builder-45.0_fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kdjyyxmaxni2pk1q2n3z6i3gmkva4abg-man-paths.drv' failed to build
building '/nix/store/vm6dm6wzasgvh7y6mcxgqzd6x51d9h87-nnn-4.9.drv'...
error: 1 dependencies of derivation '/nix/store/5y654pcc4swqsf6sy1wr4g54nc9gcj5b-system-path.drv' failed to build
...
error: 1 dependencies of derivation '/nix/store/4l71d3j310ipbi29nglnlnjp8215hi1r-nixos-system-tuvok-24.05.20240403.08b9151.drv' failed to build
```

### Additional context

Flake-based configuration for Asahi (Apple Silicon) system tracking `nixos-unstable` (08b9151ed40350725eb40b1fe96b0b86304a654b)

[Update]:

After further searching, I found this upstream issue and fix from 4 years ago:

<https://gitlab.gnome.org/GNOME/libpeas/-/issues/33>
<https://gitlab.gnome.org/GNOME/libpeas/-/merge_requests/20>

I am not sure what to do with that, however.

### Notify maintainers

@NixOS/gnome 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.6.0-asahi, NixOS, 24.05 (Uakari), 24.05.20240323.44d0940`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/06b0vfbjzpnn5qdar7yw83c6gzqsz5yd-amxd2p02wx78nyaa4bkb0hjvgwhz1dq7-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by vcunat**
##### Helpful links

- workflow docs: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#staging
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/298548
- - - 
##### Mass breakages
_nothing notable so far_

### CODE REVIEW

**Comment by vcunat** [comment]
Lots of python regressions.  First quick triage of the worst (by job count):

- [ ] `python312Packages.sphinx` (all platforms; 3.11 looks OK; thousands of builds blocked by this)
  https://hydra.nixos.org/build/256095265
- [ ] `python3Packages.traitlets` (all platforms; both pythons; thousands of builds blocked by this)
  https://hydra.nixos.org/build/256120930
- [ ] `python312Packages.exceptiongroup` (all platforms; 3.11 looks OK; hundreds of builds blocked by this)
  https://hydra.nixos.org/build/256125096
- [ ] `python3Packages.toolz` (all platforms; both pythons; hundreds of builds blocked by this)
  https://hydra.nixos.org/build/256084532

**Comment by doronbehar** [comment]
- https://github.com/NixOS/nixpkgs/pull/304226

**Comment by doronbehar** [comment]
Opened upstream issue for `toolz` test failure: https://github.com/pytoolz/toolz/issues/577 We can disable that test with a proper comment if they don't reply quickly.

**Comment by vcunat** [comment]
`.toolz` test skipped in 736d06d6cfef to clean up the list of regressions (and perhaps uncover more of them).

**Comment by vcunat** [comment]
- [ ] `python3Packages.dask` (both pythons, probably all platforms, blocking a few hundred jobs)
  https://hydra.nixos.org/build/256435947/nixlog/2/tail
  I tried updating but that runs into a different error which I couldn't immediately resolve.
  @fridh or @mweinelt might be interested in dask

**Comment by GaetanLepage** [comment]
> Oh, I had searched but skipped this PR based on title.

Yes, updating `coffea` was the original intent. We are quite stuck on this though as there is no clear way of running the tests without running into a circular dependency problem with `dask-expr`.

**Comment by vcunat** [comment]
Overall it's still not great, but we might be getting close to mergeable state
https://hydra.nixos.org/eval/1805777?compare=1805776#tabs-now-fail

**Comment by vcunat** [comment]
I think that the remaining regressions can be brought to wider audience.

**Pull request merged**
