### PR TITLE
llvmPackages: fix wasm with common opts

### PR DESCRIPTION
**Pull request by RossComputerGuy**
## Description of changes

CC @spiage

Fixes things using WASM like Firefox.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by RossComputerGuy** [comment]
@ofborg build firefox

**Comment by spiage** [comment]
@SuperSandro2000 @vcunat Hi! Can this two checks for firefox on darwin be skipped? This fix should fix issue with https://github.com/NixOS/nixpkgs/pull/330316
Both firefox and thunderbird builds fine with [current commit](https://github.com/NixOS/nixpkgs/pull/332170/commits/0b07b7e4b7a0d6d160e8b1a2296105d1e7a8719e) on my machine and by ofborg too

**Comment by vcunat** [comment]
No need to wait for it, if you're confident that it's irrelevant.  I think ofBorg can often get overloaded for darwin, so it takes time.

**Comment by spiage** [comment]
> No need to wait for this one, if you're confident that it's irrelevant. I think ofBorg can often get overloaded for darwin, so it takes time.

Thank you!

@RossComputerGuy can you break it?

**Comment by vcunat** [comment]
Actually, `firefox` isn't even supported in nixpkgs for `*-darwin`.

**Comment by spiage** [comment]
@vcunat could you please help me? How can I stop these two tests? Or can only @RossComputerGuy do this?

**Comment by RossComputerGuy** [comment]
Sorry I just woke up, Firefox on Linux built at least which is all we need to provide the fix. The error which occurred happened during configuration and not at building, I just didn't have enough time to properly test this before I had to go to sleep.

**Comment by gador** [comment]
PR LGTM. I got the config error on current `master` and the build for `firefox` is already way past it. I'm building `firefox` (and run `nixpkgs-review` on the buildserver)  right now for `x86_64-linux` and can merge after they succeed. Or someone else merges before it ;-)

**Comment by spiage** [comment]
Thank you! Every is fine now:
Version 15379 -> 15380:
  firefox-unwrapped: -73.1 KiB
  nixos-system-a7: 24.11.20240804.f099c76 → 24.11.20240804.e16b22c

**Pull request merged**
