### PR TITLE
erofs-utils: fix filesystem corruption issues

### LINKED ISSUE #261394: erofs-utils 1.7 is broken
### Describe the bug

erofs-utils is broken since 1.7.

### Steps To Reproduce

Build an filesystem image with erofs-utils 1.7 and try to access file on from a running VM.

### Expected behavior

Accessing files from a filesystem image created with erofs-utils should work.

### Additional context

This was reported first in https://github.com/NixOS/nixpkgs/pull/256937

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

### PR DESCRIPTION
**Pull request by blitz**
## Description of changes

When packaging a Nix store, erofs hits a bug in version 1.7:

```
 [36640.475349] erofs: (device loop0): erofs_read_inode: bogus i_mode (0) @ nid 0
 cannot access '.../-tzdata-2023c/share/zoneinfo/Brazil/Acre': Structure needs cleaning
```

Backport the fix from erofs master.

Fixes #261394.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nikstur** [comment]
@ofborg build erofs-utils
@ofborg test non-default-filesystems.erofs

**Comment by yu-re-ka** [comment]
Does still not fully work for me with an `nix-store --optimize`'d  store, compared to 1.6.
nixosTests.gitlab fails on aarch64-linux:

https://termbin.com/d4gk

**Comment by blitz** [comment]
@yu-re-ka Can you add a reproducer to #261394?

**Comment by yu-re-ka** [comment]
If only I knew how to reliably reproduce it, or rather, why it happens on my machine. I'm running xfs, ran `nix-store --optimise` at some point, and am building nixosTests.gitlab.

**Comment by blitz** [comment]
@yu-re-ka This seems like a different issue though. In your log the device containing nix-store doesn't pop up and can't be mounted. This PR fixes an issue where erofs-utils generates broken filesystem images.

**Comment by yu-re-ka** [comment]
```
# current nixos-unstable-small
$ git checkout 982b24c40e743793c966b47b3bb3699881489ae0
$ nix build -f . nixosTests.gitlab
=> https://termbin.com/8y0ka # Structure needs cleaning

# erofs-utils: fix filesystem corruption issues (This PR)
$ git checkout 8b157ab1b572ab907644322a2590906da7d5ff21
$ nix build -f . nixosTests.gitlab
=> https://termbin.com/vylj # Timed out waiting for device /dev/disk/by-label/nix-store

# revert to erofs-utils 1.6
$ git checkout 982b24c40e743793c966b47b3bb3699881489ae0
$ git revert --no-g --no-e 943da8b1a78bc1701666d9c6b34e555af4ac04b1
=> https://termbin.com/vki2 # works fine

**Comment by blitz** [comment]
@yu-re-ka In your original log, it looks like the label can't be found. Weird. Maybe @hsiangkao can help?

**Comment by yu-re-ka** [comment]
I bisected the failure to find the label, and now I know what the issue is.
This is indeed a separate issue that is introduced with v1.7, specifically https://github.com/erofs/erofs-utils/commit/8ee2e591dfd6a9ef99de40954c28da65ba9275c4
I am running this on an Apple Silicon MacBook Pro, with `CONFIG_ARM64_16K_PAGES=y` kernel setting, which leads to the erofs built on this system producing images with 16K block size, which can't be read by the VM which has `CONFIG_ARM64_4K_PAGES=y`.

**Pull request merged**
