### PR TITLE
imhex: 1.33.2 -> 1.35.3; fix RUNPATH and formatting

### LINKED ISSUE #309532: Imhex run failure.
### Describe the bug
Imhex failed to start.

### Steps To Reproduce
1. nix-shell -p imhex --run imhex

Shows the following errors:
```
[18:50:54] [INFO]  [main | Main]               Welcome to ImHex 1.33.2!
[18:50:54] [INFO]  [main | Main]               Compiled using commit Unknown@Unknown
[18:50:54] [INFO]  [main | Main]               Running on Linux 6.6.29 #1-NixOS SMP PREEMPT_DYNAMIC Sat Apr 27 15:11:44 UTC 2024 (x86_64)
[18:50:54] [INFO]  [main | Main]               Native scaling set to: 1.0
[18:50:54] [FATAL] [main | Main]               ImHex crashed during initial setup!
Error: Received signal 'SIGSEGV' (11)
[18:50:54] [FATAL] [main | Main]                 imhex(_ZN3hex10stacktrace13getStackTraceEv+0x5a) [0x433dda]
[18:50:54] [FATAL] [main | Main]                 imhex(_ZN3hex5crash11handleCrashERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x2c) [0x42669c]
[18:50:54] [FATAL] [main | Main]                 imhex() [0x426d41]
[18:50:54] [FATAL] [main | Main]                 imhex() [0x426fe4]
[18:50:54] [FATAL] [main | Main]                 /nix/store/35pq4hr29c3sl79lgfwgsvd9nwzyp4am-glibc-2.39-5/lib/libc.so.6(+0x3ff30) [0x7f8e89eb0f30]
[18:50:54] [INFO]  [main | Main]               Exit task 'Saving settings' finished successfully
[18:50:54] [INFO]  [main | Main]               Exit task 'Prepare exit' finished successfully
[18:50:54] [INFO]  [main | Main]               Exit task 'Unloading plugins' finished successfully
[18:50:54] [INFO]  [main | Main]               Exit task 'Deleting old files' finished successfully
```

### Expected behavior
Imhex start up normally.

### Additional Context
Adding -v, --verbose doesn't give more information. I don't know how to either.

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.29, NixOS, 24.05 (Uakari), 24.05.20240502.63c3a29`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/p69bcs7ma6ijj8v9xsrg3nq3nn8ryn95-source`
```

### LINKED ISSUE #330231: imhex crashes
### Describe the bug

Imhex on unstable and nixos-24.05 crashes.

### Steps To Reproduce

`nix run 'nixpkgs#imhex'`

### Additional context

Output from the above command:
```
[18:49:47] [INFO]  [main | Main]               Welcome to ImHex 1.33.2!
[18:49:47] [INFO]  [main | Main]               Compiled using commit Unknown@Unknown
[18:49:47] [INFO]  [main | Main]               Running on Linux 6.6.41 #1-NixOS SMP PREEMPT_DYNAMIC Thu Jul 18 11:21:27 UTC 2024 (x86_64)
[18:49:47] [INFO]  [main | Main]               Native scaling set to: 1.0
[18:49:47] [FATAL] [main | Main]               ImHex crashed during initial setup!
Error: Received signal 'SIGSEGV' (11)
[18:49:47] [FATAL] [main | Main]                 /nix/store/4q9n3x2hwmfd30pm02h57wwqwwr00kf5-imhex-1.33.2/bin/imhex(_ZN3hex10stacktrace13getStackTraceEv+0x5a) [0x43421a]
[18:49:47] [FATAL] [main | Main]                 /nix/store/4q9n3x2hwmfd30pm02h57wwqwwr00kf5-imhex-1.33.2/bin/imhex(_ZN3hex5crash11handleCrashERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x2c) [0x4267cc]
[18:49:47] [FATAL] [main | Main]                 /nix/store/4q9n3x2hwmfd30pm02h57wwqwwr00kf5-imhex-1.33.2/bin/imhex() [0x426e71]
[18:49:47] [FATAL] [main | Main]                 /nix/store/4q9n3x2hwmfd30pm02h57wwqwwr00kf5-imhex-1.33.2/bin/imhex() [0x427114]
[18:49:47] [FATAL] [main | Main]                 /nix/store/m71p7f0nymb19yn1dascklyya2i96jfw-glibc-2.39-52/lib/libc.so.6(+0x405c0) [0x7f89a05bc5c0]
[18:49:47] [INFO]  [main | Main]               Exit task 'Saving settings' finished successfully
[18:49:47] [INFO]  [main | Main]               Exit task 'Prepare exit' finished successfully
[18:49:47] [INFO]  [main | Main]               Exit task 'Unloading plugins' finished successfully
[18:49:47] [INFO]  [main | Main]               Exit task 'Deleting old files' finished successfully
```

### Notify maintainers

@kashw2 @cafkafk

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.41, NixOS, 24.05 (Uakari), 24.05.3164.63d37ccd2d17`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(nix): `""`
 - channels(root): `"home-manager-24.05.tar.gz, nixos-24.05, nixos-hardware, nixos-unstable, nur"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by eclairevoyant**
## Description of changes

- 1.33.2 -> 1.35.3
- fix RUNPATH to find libGL and its own plugins - fixes #309532, fixes #330231
- format with nixfmt-rfc-style

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by someplaceguy** [comment]
I am not sure if this is the correct fix.

On my system, `imhex` is failing to start because `glfw` calls `dlopen("libwayland-client.so.0")` but `dlopen()` fails to open the library. The code in question comes from here:

https://github.com/glfw/glfw/blob/7b6aead9fb88b3623e3b3725ebb42670cbe4c579/src/wl_init.c#L514

This is an strace:
```
 982   │ write(3, "[02:23:40] [INFO]  [main | Main]"..., 104) = 104
 983   │ openat(AT_FDCWD, "/etc/sane-libs/libwayland-client.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
 984   │ openat(AT_FDCWD, "/nix/store/xb59jda2vw545dg9nllldx82w36zrjr3-libXrandr-1.5.4/lib/libwayland-client.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
 985   │ openat(AT_FDCWD, "/nix/store/xkiv94vn38wdw8y1mmjl5xwwskyz0h7n-libXinerama-1.1.5/lib/libwayland-client.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
 986   │ openat(AT_FDCWD, "/nix/store/4wdi47sz9jj6xb3dnnqajrc4y3isqjsg-libXcursor-1.2.2/lib/libwayland-client.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
 987   │ openat(AT_FDCWD, "/nix/store/9z7w5dw20wmsc5bfm3gbmdhlicpwcbv8-libXi-1.8.1/lib/libwayland-client.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
 988   │ openat(AT_FDCWD, "/nix/store/yi2gj7888r7fzc3dnynh8f00wfva69dr-glibc-2.39-52/lib/libwayland-client.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
 989   │ openat(AT_FDCWD, "/nix/store/yi2gj7888r7fzc3dnynh8f00wfva69dr-glibc-2.39-52/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
 990   │ openat(AT_FDCWD, "/nix/store/yi2gj7888r7fzc3dnynh8f00wfva69dr-glibc-2.39-52/lib/libwayland-client.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
 991   │ openat(AT_FDCWD, "/nix/store/c6s854sg2kbnq3nclgw2ygyx29hcf05w-xgcc-13.2.0-libgcc/lib/glibc-hwcaps/x86-64-v3/libwayland-client.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
 992   │ newfstatat(AT_FDCWD, "/nix/store/c6s854sg2kbnq3nclgw2ygyx29hcf05w-xgcc-13.2.0-libgcc/lib/glibc-hwcaps/x86-64-v3/", 0x7ffe62001270, 0) = -1 ENOENT (No such file or directory)
 993   │ openat(AT_FDCWD, "/nix/store/c6s854sg2kbnq3nclgw2ygyx29hcf05w-xgcc-13.2.0-libgcc/lib/glibc-hwcaps/x86-64-v2/libwayland-client.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
 994   │ newfstatat(AT_FDCWD, "/nix/store/c6s854sg2kbnq3nclgw2ygyx29hcf05w-xgcc-13.2.0-libgcc/lib/glibc-hwcaps/x86-64-v2/", 0x7ffe62001270, 0) = -1 ENOENT (No such file or directory)
 995   │ openat(AT_FDCWD, "/nix/store/c6s854sg2kbnq3nclgw2ygyx29hcf05w-xgcc-13.2.0-libgcc/lib/libwayland-client.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
 996   │ newfstatat(AT_FDCWD, "/nix/store/c6s854sg2kbnq3nclgw2ygyx29hcf05w-xgcc-13.2.0-libgcc/lib/", {st_mode=S_IFDIR|0555, st_size=4, ...}, 0) = 0
 997   │ write(3, "[02:23:40] [FATAL] [main | Main]"..., 74) = 74
```

As you can see, `libwayland-client.so.0` cannot be found when `glfw` calls `dlopen()`.

So I think that this issue should not be fixed in `imhex`, but rather in `glfw`, so that it works for all programs that use `glfw`.

One potential fix for `glfw` could be to do something like it is done here:

https://github.com/NixOS/nixpkgs/blob/079457313a259f66e32acc08a52bc54ff88dce43/pkgs/development/python-modules/matplotlib/default.nix#L114-L117

That said, I don't know much about how `dlopen()` is supposed to work on NixOS to be sure about whether this is the correct way to fix this.

cc `glfw` maintainers @MarcWeber @Twey

**Comment by eclairevoyant** [comment]
Can't repro, on sway, on NixOS :shrug: Someone else can dig I guess.

**Comment by someplaceguy** [comment]
> Can't repro, on sway, on NixOS 🤷 Someone else can dig I guess.

I'm sorry, I wasn't very clear. I wasn't saying that I am experiencing the `dlopen` failure after applying your PR.

My point was that your PR contains a fix for #309532 but your fix would only work for `imhex`. However, the underlying root cause for that issue is a problem in `glfw`, which means that the issue should not be fixed in `imhex` but rather in `glfw` so that it is fixed once and for all, for every program that uses `glfw`.

**Comment by someplaceguy** [comment]
In fact, the exact same issue was already fixed in #276228 but for a different version of `glfw`. I will open a new issue for this.

**Comment by someplaceguy** [comment]
I've submitted #323510 to deal with the `glfw` issue but that PR is not enough to fix #309532.

On my system, after applying #323510, `imhex` now crashes in this line of code:

https://github.com/WerWolv/ImHex/blob/dffb7e95e377a31633ca58dc4625a140c201a7df/main/gui/source/init/splash_window.cpp#L524

So it seems that `imhex` is not able to call that opengl function for some reason.

However, with the fix in this PR, `imhex` doesn't crash anymore when calling OpenGL functions. However, I can only see the splash screen and then a blank window. I also see some error messages in the console.

```
(...)
[INFO]  [main | Init Tasks]         Loading plugin 'ui.hexpluglib'
[ERROR] [libimhex | Init Tasks]     Loading library 'ui.hexpluglib' failed: fonts.hexpluglib: cannot open shared object file: No such file or directory!
[INFO]  [main | Init Tasks]         Loading plugin 'fonts.hexpluglib'
[INFO]  [main | Init Tasks]         Loading plugin 'builtin.hexplug'
[ERROR] [libimhex | Init Tasks]     Loading library 'builtin.hexplug' failed: ui.hexpluglib: cannot open shared object file: No such file or directory!
(...)
```

In any case, my suggestion is to reopen this PR, if possible, because it's still an improvement.

Thanks!

**Comment by eclairevoyant** [comment]
I attempted a cursed fix for the plugins, does this address it? I can't repro it on my system, again

**Comment by someplaceguy** [comment]
Your "cursed fix" worked perfectly! Thanks! Finally, `imhex` works fine on my system.

I've tried to revert #323510 to see if this PR alone was enough but it isn't: `imhex` fails to initialize `GLFW` without the glfw fix.

So to be clear, on my system, both this PR (with the plugin fix) and #323510 were needed for `imhex` to work properly.

**Comment by jys1670** [comment]
can we update it to latest v1.35.4 (released 3 weeks ago)? 
it has some bugfixes

**Comment by eclairevoyant** [comment]
Honestly I'd rather just fix the runtime issue rather than bumping indefinitely. If no one's reviewing this then that's just busywork.

**Review by kashw2 — APPROVED** [review]

**Review by cafkafk — APPROVED** [review]
Seems to run fine, let's get this out of the way so  #330303 can proceed

**Pull request merged**
