### PR TITLE
nixos-rebuild: run systemd-run with / as the working directory

### PR DESCRIPTION
**Pull request by r-vdp**
Before we would run systemd-run with the user's home dir as the working directory, but this causes issues when the home dir is on a separate partition and that partition cannot be mounted, as the transient unit created by systemd-run would gain a dependency on the home mount and fail. Since the root partition is guaranteed to be mounted, using that as the working directory avoids this issue and allows doing a remote nixos-rebuild to fix the issue preventing /home from being mounted.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Mic92 — APPROVED** [review]
Seems to work on my machine. The change itself is trivial. Give others a chance to react though, since nixos-rebuild is quite critical.

**Comment by r-vdp** [comment]
@ofborg test nixos-rebuild-install-bootloader nixos-rebuild-specialisations nixos-rebuild-target-host

**Comment by emilazy** [comment]
Per the systemd documentation, this “defaults to the root directory when systemd is running as a system instance and the respective user's home directory if run as user”. Therefore, I don’t think we need to set this at all; we can just remove the line.

**Comment by r-vdp** [comment]
> Per the systemd documentation, this “defaults to the root directory when systemd is running as a system instance and the respective user's home directory if run as user”, and this unit runs on the system instance of systemd. Therefore, I don’t think we need to set this at all; we can just remove the line.

Yeah that also works. I don't mind either way.

I mainly wonder if there was any specific reason that `--same-dir` was chosen originally. I can't really think of any, I don't think we really depend on the working dir here.

**Comment by emilazy** [comment]
Maybe the previous non‐`systemd-run` behaviour didn’t move out of the current directory and so it was picked to maximize compatibility? Though in this case it makes the environment less uniform and introduces issues like you described, so I don’t think that’s a good thing when part of the point of using `systemd-run` is to reduce environmental dependencies like that.

**Comment by emilazy** [comment]
Looking at https://github.com/NixOS/nixpkgs/pull/258571, it let lots of the old environment through originally and that was whittled down through review. I think this is just one more step in that process. cc @thiagokokada for insight though

**Review by thiagokokada — APPROVED** [review]

**Comment by thiagokokada** [comment]
The changes looks fair to me, I don't use home in a separate partition so this was never an issue for me, but I can understand this causing issues when you have one.

**Comment by thiagokokada** [comment]
One thing that I am thinking now is if we even need to change the directory. I don't even remember why I set the `--same-dir`.

**Comment by emilazy** [comment]
I think we should just drop the line and be done with it – it’ll be `/` in practice and there’s no reason for us to have an opinion about it at all, since the default is what we want.

**Comment by r-vdp** [comment]
OK, fine for me, I'll update the PR.

**Comment by thiagokokada** [comment]
@ofborg test nixos-rebuild-install-bootloader nixos-rebuild-specialisations nixos-rebuild-target-host

**Review by thiagokokada — APPROVED** [review]

**Review by emilazy — APPROVED** [review]

**Comment by emilazy** [comment]
It seems like `--same-dir` is back in `nixos-rebuild-ng`, was this intentional?

**Comment by thiagokokada** [comment]
> It seems like `--same-dir` is back in `nixos-rebuild-ng`, was this intentional?

No, I think my PR adding the `systemd-run` support was created before this one.

I will open another PR to remove it.

**Pull request merged**
