### PR TITLE
clojure: 1.10.1.645 -> 1.10.1.727

### PR DESCRIPTION
**Pull request by bennyandresen**
###### Motivation for this change
newest version

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

/marvin opt-in
/status needs_reviewer

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102272` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>clojure</li>
    <li>lumo</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102272` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>lumo</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>clojure</li>
  </ul>
</details>

**Comment by bennyandresen** [comment]
> gyp-mac-tool: /usr/bin/env: bad interpreter: Operation not permitted

Could this be a problem with Mac OS Catalina? I see reports about that by googling for that error.
In any case we need to wait someone with darwin experience to debug this further, as I only have access to x86-64 linux.

**Comment by SuperSandro2000** [comment]
> Could this be a problem with Mac OS Catalina?

Could be. We can also disable it for darwin for now.

**Comment by bennyandresen** [comment]
> Could be. We can also disable it for darwin for now.

Okay. That would have to be a different PR, because the lumo problem is not a clojure problem, AFAICS.

**Review by jlesquembre — APPROVED** [review]

**Comment by jlesquembre** [comment]
> Okay. That would have to be a different PR, because the lumo problem is not a clojure problem, AFAICS.

I agree, lumo issues have nothing to do with this PR.
Also, lumo was abandoned, his creator moved away from the clojure ecosystem, and said he has no intention to maintain it (see https://github.com/anmonteiro/lumo/issues/492#issuecomment-564296959)

 I think we should remove lumo from nixpkgs at some point (it was removed from homebrew, see https://github.com/Homebrew/homebrew-core/commit/f0520924fe2da50ce6657fcdcb8a46ace7475578). In my opinion, graalvm and babashka are better alternatives to lumo, and I don't see a reason - for new projects - to pick lumo over it. I'd like to know @hlolli opinion about it, does make sense to you to continue maintaining lumo?

**Pull request merged**
