### PR TITLE
sage: explicitly use gfortran6

### PR DESCRIPTION
**Pull request by timokau**
###### Motivation for this change

The recent change from gfortran=gfortran6 to gfortran=gfortran7 broke
the build.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build sage

**Comment by timokau** [comment]
The `sage` build is too long for ofBorg, it doesn't complete within the time limit.

**Comment by vcunat** [comment]
Did you try it locally?  IIRC I've tried building with gfortran6 but it didn't help.

**Comment by timokau** [comment]
Yes, I made sure that I can reproduce the failure and that reverting to gfortran6 fixes it.

**Review by vcunat — APPROVED** [review]

**Comment by vcunat** [comment]
Hmm, my machine apparently tends to suffer from transient errors on `sage`.  Tried twice now, succeeded in the second case.

**Comment by timokau** [comment]
This package is just a never ending source of fun (please somebody stop me next time before I take on such a project :grimacing:).

Do you have a build log for the failed one?

**Comment by vcunat** [comment]
Not anymore.  It was probably a compiler segfaulting, as it sometimes happens with my (probably) buggy CPU.

**Comment by 7c6f434c** [comment]
@timokau if https://github.com/NixOS/nixpkgs/pull/23842#issuecomment-286239237 was not enough to stop you (or if you start fixing huge packages without checking their track record), then I am not sure stopping you is feasible…

**Pull request merged**
