### PR TITLE
pybind11: Unify with pythonPackages.pybind11

### PR DESCRIPTION
**Pull request by knedlsepp**
###### Motivation for this change
Instead of one derivation providing a cmake-compatible library and one
providing a setuptools compatible library, we now support both ways of
consuming the library for both pybind11 and python.pkgs.pybind11.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by jonringer — CHANGES_REQUESTED** [review]
python packages aren't able to discover it through pip

```
[4 built (11 failed), 89 copied (1218.4 MiB), 417.4 MiB DL]
error: build of '/nix/store/dsmkqa55zadlzvvssair3k5d9lsahlsf-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/74302
32 package failed to build:
ocrmypdf pybind11 pybitmessage python27Packages.fasttext python27Packages.fipy python27Packages.loo-py python27Packages.pyamg python27Packages.pyfma python27Packages.pyopencl python27Packages.reikna python27Packages.sasmodels python37Packages.accupy python37Packages.fasttext python37Packages.fipy python37Packages.loo-py python37Packages.pikepdf python37Packages.pyamg python37Packages.pyfma python37Packages.pyopencl python37Packages.reikna python37Packages.sasmodels python38Packages.accupy python38Packages.fasttext python38Packages.fipy python38Packages.loo-py python38Packages.pikepdf python38Packages.pyamg python38Packages.pyfma python38Packages.pyopencl python38Packages.reikna python38Packages.sasmodels sasview

2 package were built:
python37Packages.pybind11 python38Packages.pybind11
```

**Comment by jonringer** [comment]
example failure:
```
  distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pybind11>=2.2')
cannot build derivation '/nix/store/pcsz0i6rfngll7bypcbdmbsxxpzinmh0-python3.8-accupy-0.2.0.drv': 1 dependencies couldn't be built
```

**Comment by knedlsepp** [comment]
@GrahamcOfBorg build python2Packages.pybind11 python37Packages.pybind11 python38Packages.pybind11 python3Packages.accupy  python38Packages.pyopencl

**Comment by knedlsepp** [comment]
> example failure:
> 
> ```
>   distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pybind11>=2.2')
> cannot build derivation '/nix/store/pcsz0i6rfngll7bypcbdmbsxxpzinmh0-python3.8-accupy-0.2.0.drv': 1 dependencies couldn't be built
> ```

@jonringer Sorry for opening this PR earlier than it was ready. I think it's now in a state where it should do as advertised. Do you mind taking a look again? :)

**Review by jonringer — APPROVED** [review]
diff LGTM

sasview was broken on master, needs some love. But that can be done outside of this PR
```
[35 built (1 failed), 566 copied (3337.4 MiB), 887.6 MiB DL]
error: build of '/nix/store/di8k6m09y5hka6waw4fg5d1qf1kqbnsj-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/74302
1 package failed to build:
sasview

33 package were built:
ocrmypdf pybind11 pybitmessage python27Packages.fasttext python27Packages.fipy python27Packages.loo-py python27Packages.pyamg python27Packages.pyfma python27Packages.pyopencl python27Packages.reikna python27Packages.sasmodels python37Packages.accupy python37Packages.fasttext python37Packages.fipy python37Packages.loo-py python37Packages.pikepdf python37Packages.pyamg python37Packages.pybind11 python37Packages.pyfma python37Packages.pyopencl python37Packages.reikna python37Packages.sasmodels python38Packages.accupy python38Packages.fasttext python38Packages.fipy python38Packages.loo-py python38Packages.pikepdf python38Packages.pyamg python38Packages.pybind11 python38Packages.pyfma python38Packages.pyopencl python38Packages.reikna python38Packages.sasmodels
```

**Comment by knedlsepp** [comment]
Thx. Gave sasview a glance. Looks like the wxPython installation in general is at fault since it's site-packages directory contains a "build" directory.

**Pull request merged**
