### PR TITLE
Revert "chromium: 45.0.2454.101 -> 46.0.2490.71"

### PR DESCRIPTION
**Pull request by obadz**
This reverts commit 0ad0fbdf8aebeb01b10d71117eab7aaccbe01849.

See https://github.com/NixOS/nixpkgs/issues/10555

### CODE REVIEW

**Comment by obadz** [comment]
cc @wkennington @domenkozar

**Comment by bjornfor** [comment]
IMHO, it's good style to explain why the revert is needed (in the commit message).

**Comment by obadz** [comment]
@bjornfor: fixed, thanks.

**Comment by domenkozar** [comment]
@aszlig

**Comment by domenkozar** [comment]
Merging for now, hangouts are important feature for most of us.

**Comment by wkennington** [comment]
Just note we are now vulnerable to multiple flash vulnerabilities and
potentially others.

**Comment by obadz** [comment]
Didn't Chrome dump flash?

**Comment by wkennington** [comment]
No, they dumped npapi but they bundle pepper flash as part of the chromium
release.

**Comment by domenkozar** [comment]
Sigh. Do we have an upstream issue for hangouts?

**Comment by vcunat** [comment]
@obadz: actually, I only use chromium for some flash stuff, as it's the only real way to get a recent version of flash on Linux. Some things do not work with the older one.

**Comment by bdimcheff** [comment]
@domenkozar I put some upstream info here: https://github.com/NixOS/nixpkgs/issues/10555#issuecomment-152549786

**Pull request merged**
