### PR TITLE
 proxychains{,-ng}: install default config 

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ZenithalHourlyRate** [comment]
See https://github.com/rofl0r/proxychains-ng/pull/442#issuecomment-1126666327 and https://github.com/rofl0r/proxychains-ng/pull/449, waiting for this to be resolved.

**Comment by ZenithalHourlyRate** [comment]
See https://github.com/rofl0r/proxychains-ng/pull/442#issuecomment-1126666327 and https://github.com/rofl0r/proxychains-ng/pull/449, waiting for this to be resolved.

**Comment by ZenithalHourlyRate** [comment]
> See [rofl0r/proxychains-ng#442 (comment)](https://github.com/rofl0r/proxychains-ng/pull/442#issuecomment-1126666327) and [rofl0r/proxychains-ng#449](https://github.com/rofl0r/proxychains-ng/pull/449), waiting for this to be resolved.

Resolved. Please add a new patch https://github.com/rofl0r/proxychains-ng/commit/9b42da71f4df7b783cf07a58ffa095e293c43380

**Comment by SuperSandro2000** [comment]
Fails with
```
proxychains-ng> make: *** No rule to make target '/nix/store/hz9y82pmhjnjpp4kqg5j1mpvmywn7b1n-proxychains-ng-4.16/share/zsh/site_functions/_proxychains4', needed by 'install-zsh-completion'.  Stop.
```

**Comment by ZenithalHourlyRate** [comment]
> Fails with
> 
> ```
> proxychains-ng> make: *** No rule to make target '/nix/store/hz9y82pmhjnjpp4kqg5j1mpvmywn7b1n-proxychains-ng-4.16/share/zsh/site_functions/_proxychains4', needed by 'install-zsh-completion'.  Stop.
> ```

I can reproduce this. It seems that the new patch renamed the file but `make` can not recognize it (strange behavior of make, encountered similar thing before). I tried not to patch it and it worked.

```
  src = fetchFromGitHub {
    owner = "rofl0r";
    repo = pname;
    rev = "9b42da71f4df7b783cf07a58ffa095e293c43380";
    sha256 = "sha256-FIjPQMvTTYAMv9g1+QrOyIYoylr+gyJ/8OuWknnPYd4=";
  };  
```
This can build successfully with 
```
./tools/install.sh -D -m 644 completions/_proxychains4 /nix/store/q3inc51xlfb7dv4d9b1g8hcnn5w7g0ii-proxychains-ng-tmp/share/zsh/site_functions/_proxychains4
```

So I suggest adding only `install-config` this time. When `proxychains-ng` releases `4.17` we could add `install-zsh-completion`

**Review by ZenithalHourlyRate — APPROVED** [review]
Works for me on x86_64-linux
```
nix-build -A proxychains-ng
nix-build -A proxychains
```

**Comment by wrvsrx** [comment]
That change makes proxychains can't find config made by `programs.proxychains.proxies`. Would you consider fix it?

**Comment by chuangzhu** [comment]
> That change makes proxychains can't find config made by `programs.proxychains.proxies`. Would you consider fix it?

This could probably be solved by wrapping the executable in the module.

**Comment by chuangzhu** [comment]
Digged a little bit into the code. Now I think the better way is to patch the code, swapping `priority 4` and `priority 5` in https://github.com/haad/proxychains/blob/1f04b93d350ce51ea3c791ca88e166a4ada85165/src/common.c#L40-L48. This way is better because it respects configurations in `~/.proxychains/proxychains.conf` on multi-user stations.

**Pull request merged**
