### PR TITLE
aws-sdk-cpp: 1.7.90 -> 1.8.113

### PR DESCRIPTION
**Pull request by orivej**
###### Motivation for this change

Regular update.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests)): awscli, nix-ssh-serve
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107623` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>nix-exec</li>
  </ul>
</details>
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
    <li>tests.nixos-functions.nixosTest-test</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python37Packages.nixpkgs</li>
    <li>python39Packages.nixpkgs</li>
  </ul>
</details>
<details>
  <summary>63 packages built:</summary>
  <ul>
    <li>aws-c-cal</li>
    <li>aws-c-common</li>
    <li>aws-c-event-stream</li>
    <li>aws-c-io</li>
    <li>aws-checksums</li>
    <li>aws-sdk-cpp</li>
    <li>bundix</li>
    <li>cabal2nix</li>
    <li>cachix</li>
    <li>common-updater-scripts</li>
    <li>crate2nix</li>
    <li>crystal2nix</li>
    <li>dep2nix</li>
    <li>disnix</li>
    <li>disnixos</li>
    <li>dydisnix</li>
    <li>fusionInventory</li>
    <li>go2nix</li>
    <li>haskellPackages.cachix</li>
    <li>haskellPackages.hercules-ci-agent</li>
    <li>haskellPackages.hocker</li>
    <li>haskellPackages.nix-paths</li>
    <li>haskellPackages.update-nix-fetchgit</li>
    <li>hercules-ci-agent</li>
    <li>hydra-unstable</li>
    <li>libnixxml</li>
    <li>lispPackages.quicklisp-to-nix</li>
    <li>lispPackages.quicklisp-to-nix-system-info</li>
    <li>nix (nixStable)</li>
    <li>nix-bundle</li>
    <li>nix-direnv</li>
    <li>nix-doc</li>
    <li>nix-du</li>
    <li>nix-index</li>
    <li>nix-pin</li>
    <li>nix-plugins</li>
    <li>nix-prefetch</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-cvs</li>
    <li>nix-prefetch-docker</li>
    <li>nix-prefetch-git</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-serve</li>
    <li>nix-update</li>
    <li>nix-update-source</li>
    <li>nixFlakes (nixUnstable)</li>
    <li>nixos-generators</li>
    <li>nixos-shell</li>
    <li>nixpkgs-review</li>
    <li>nixui</li>
    <li>python37Packages.nix-kernel</li>
    <li>python37Packages.pythonix</li>
    <li>python38Packages.nix-kernel</li>
    <li>python38Packages.nixpkgs</li>
    <li>python38Packages.pythonix</li>
    <li>python39Packages.nix-kernel</li>
    <li>python39Packages.pythonix</li>
    <li>s2n</li>
    <li>update-nix-fetchgit</li>
    <li>vgo2nix</li>
    <li>vulnix</li>
  </ul>
</details>

python37Packages.nixpkgs
```
[pbr] Reusing existing SOURCES.txt
running build_ext
nixpkgs (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: nixpkgs (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: nixpkgs
Traceback (most recent call last):
  File "/nix/store/401hv5vy6jm6wyppmlaalakdlsrzchc6-python3-3.7.9/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/nix/store/401hv5vy6jm6wyppmlaalakdlsrzchc6-python3-3.7.9/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/build/nixpkgs-0.2.4/nixpkgs/__init__.py", line 41, in <module>
    import nix
ModuleNotFoundError: No module named 'nix'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
```

**Comment by orivej** [comment]
I have reported the issue about python37Packages.nixpkgs and python39Packages.nixpkgs which happens independently from this PR at https://github.com/Mic92/pythonix/issues/6

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 107623` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package marked as broken and skipped:
</summary>
<ul>
<li>nix-exec</li>
</ul>
</details>
<details>
<summary>
2 packages blacklisted:
</summary>
<ul>
<li>tests.nixos-functions.nixos-test</li>
<li>tests.nixos-functions.nixosTest-test</li>
</ul>
</details>
<details>

  <summary>6 packages failed to build and are new build failures:</summary>
  <ul>
<li>cachix: log was empty</li>
<li>haskellPackages.cachix: log was empty</li>
<li>haskellPackages.hercules-ci-agent: log was empty</li>
<li>hercules-ci-agent: log was empty</li>
<li>python37Packages.nixpkgs: log <a href="https://hastebin.com/raw/ivatahitas">https://hastebin.com/raw/ivatahitas</a></li>
<li>python39Packages.nixpkgs: log <a href="https://hastebin.com/raw/bayatucidi">https://hastebin.com/raw/bayatucidi</a></li>
  </ul>
</details>
<details>
<summary>
59 packages built:
</summary>
<ul>
<li>aws-c-cal</li>
<li>aws-c-common</li>
<li>aws-c-event-stream</li>
<li>aws-c-io</li>
<li>aws-checksums</li>
<li>aws-sdk-cpp</li>
<li>bundix</li>
<li>cabal2nix</li>
<li>common-updater-scripts</li>
<li>crate2nix</li>
<li>crystal2nix</li>
<li>dep2nix</li>
<li>disnix</li>
<li>disnixos</li>
<li>dydisnix</li>
<li>fusionInventory</li>
<li>go2nix</li>
<li>haskellPackages.hocker</li>
<li>haskellPackages.nix-paths</li>
<li>haskellPackages.update-nix-fetchgit</li>
<li>hydra-unstable</li>
<li>libnixxml</li>
<li>lispPackages.quicklisp-to-nix</li>
<li>lispPackages.quicklisp-to-nix-system-info</li>
<li>nix (nixStable)</li>
<li>nix-bundle</li>
<li>nix-direnv</li>
<li>nix-doc</li>
<li>nix-du</li>
<li>nix-index</li>
<li>nix-pin</li>
<li>nix-plugins</li>
<li>nix-prefetch</li>
<li>nix-prefetch-bzr</li>
<li>nix-prefetch-cvs</li>
<li>nix-prefetch-docker</li>
<li>nix-prefetch-git</li>
<li>nix-prefetch-hg</li>
<li>nix-prefetch-scripts</li>
<li>nix-prefetch-svn</li>
<li>nix-serve</li>
<li>nix-update</li>
<li>nix-update-source</li>
<li>nixFlakes (nixUnstable)</li>
<li>nixos-generators</li>
<li>nixos-shell</li>
<li>nixpkgs-review</li>
<li>nixui</li>
<li>python37Packages.nix-kernel</li>
<li>python37Packages.pythonix</li>
<li>python38Packages.nix-kernel</li>
<li>python38Packages.nixpkgs</li>
<li>python38Packages.pythonix</li>
<li>python39Packages.nix-kernel</li>
<li>python39Packages.pythonix</li>
<li>s2n</li>
<li>update-nix-fetchgit</li>
<li>vgo2nix</li>
<li>vulnix</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

python38Packages.nixpkgs:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>

**Comment by SuperSandro2000** [comment]
@orivej Can you fix the merge conflict?

**Comment by flokli** [comment]
This broke `nix` cross compilation: https://github.com/NixOS/nixpkgs/issues/106759#issuecomment-764519504

**Comment by orivej** [comment]
#110307 should fix it.

**Pull request merged**
