### PR TITLE
readline 7.0 -> 7.0.3

### PR DESCRIPTION
**Pull request by vanschelven**
###### Motivation for this change

Full motivation: https://groups.google.com/forum/#!topic/nix-devel/agupzdm352Q

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by danbst** [comment]
Please, reflect the version change by changing name attribute. Maybe 7.0p03 would be good.

**Comment by vanschelven** [comment]
I've reflected the version change as requested by @danbst ; though not using the leading zero.

The general mechanism to do so was inspired by [the expression for bash](https://github.com/NixOS/nixpkgs/blob/7c58d1261609a6b660de917e9010a3d15af8c07b/pkgs/shells/bash/4.4.nix#L30)

**Comment by vanschelven** [comment]
I could squash the commits if this is preferred; is it generally preferred to squash or are commits kept as is?

**Comment by danbst** [comment]
I'd  prefer to see it squashed for such simple change

**Comment by vcunat** [comment]
Nice.  Pushed with a minor meta fixup; also to 17.03.

**Pull request merged**
