### PR TITLE
auto-patchelf: avoid filesets

### PR DESCRIPTION
**Pull request by emilazy**
The use of filesets triggers the same Nix evaluation bug as in e4b8a0a243d917d78935e6c479a5005e7c52063f, which broke the installer tests again.

See [this Matrix message](https://matrix.to/#/!DBFhtjpqmJNENpLDOv:nixos.org/$fHrarncPutb9w-c2KsGPsY4Ok2-eY1KaFJpLUZT7yAY?via=nixos.org&via=matrix.org&via=tchncs.de) for the reproducer last time this happened with `switch-to-configuration-ng`. It’s some interaction between `NIX_PATH` and chroot stores.

I genuinely think we need to ban use of filesets in Nixpkgs until the filesets implementation works around the bug or all affected Nix versions get fixes (we do claim compatibility down to 2.3, after all). It has been fiendishly difficult to track down this issue both times now and it’s blocked the `staging-next` merge for a couple days.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
Thanks to @lilyinstarlight for putting in way too much effort to track this down.

@ofborg test installer.simpleUefiSystemdBoot

**Comment by infinisil** [comment]
I'm 95% sure this cannot be worked around on the fileset library level without compromising correctness :(

**Comment by emilazy** [comment]
If we can’t work around it in Nixpkgs then I think we really do have to just ban the use of filesets in‐tree for now, preferably enforced by CI. Any package that uses filesets and ends up being in the closure of the systems set up by the installer image wreaks havoc and it’s painful to track down the failures. Eval breaking under chroot stores is a pretty big correctness problem too, after all 😅

**Comment by Yarny0** [comment]
Might this be caused by https://github.com/NixOS/nix/issues/11503 ?

**Comment by emilazy** [comment]
That indeed looks eminently plausible.

**Pull request merged**
