### PR TITLE
utsushi: 3.57.0 -> 3.59.2

### PR DESCRIPTION
**Pull request by wucke13**
+ building from gitlab source
+ reorderd dependencies to be in logical/alphabetical order
+ replaced patches with substituteInPlace, as patches broke the installChecks
  and substituteInPlace may be more robust than making new patches for each
  release. Also the compiled source is now closer to upstream than
  before.
+ added installChecks
+ added all supported devices as listed on epson.net

(cherry picked from commit 9eb00acbbee63d20a6ac7c124005089a8bebcfba)

Reference: https://github.com/NixOS/nixpkgs/pull/70160#issuecomment-541270534

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @grahamc 
Please try to build with @GrahamcOfBorg . I did not test this build for a lack of time.

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg build utsushi

**Comment by wucke13** [comment]
@grahamc what's going on with the branches here?

**Comment by grahamc** [comment]
Please cherry-pick to the release-19.09 branch, and then send the PR against release-19.09. staging-19.09 is only for really big changes.

**Comment by wucke13** [comment]
@grahamc done.

**Comment by grahamc** [comment]
@ofborg build utsushi

**Pull request merged**
