### PR TITLE
llvmPackages_19.libclc: fix cross compilation

### PR DESCRIPTION
**Pull request by NickCao**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by NickCao** [comment]
@ofborg build pkgsCross.aarch64-multiplatform.llvmPackages_19.libclc pkgsCross.aarch64-multiplatform.llvmPackages_18.libclc

**Comment by NickCao** [comment]
mesa build still fails, requires:
```diff
diff --git a/pkgs/development/libraries/mesa/default.nix b/pkgs/development/libraries/mesa/default.nix
index 5e2651b764b3..310007311848 100644
--- a/pkgs/development/libraries/mesa/default.nix
+++ b/pkgs/development/libraries/mesa/default.nix
@@ -138,6 +138,7 @@ in stdenv.mkDerivation {

   patches = [
     ./opencl.patch
+    ./mesa-clc-cross.patch
   ];

   postPatch = ''
diff --git a/pkgs/development/libraries/mesa/mesa-clc-cross.patch b/pkgs/development/libraries/mesa/mesa-clc-cross.patch
new file mode 100644
index 000000000000..e94c136ce385
--- /dev/null
+++ b/pkgs/development/libraries/mesa/mesa-clc-cross.patch
@@ -0,0 +1,13 @@
+diff --git a/src/compiler/clc/meson.build b/src/compiler/clc/meson.build
+index 74767d08d..1194e0e0f 100644
+--- a/src/compiler/clc/meson.build
++++ b/src/compiler/clc/meson.build
+@@ -124,8 +124,4 @@ prog_mesa_clc = executable(
+   c_args : [pre_args, no_override_init_args],
+   link_args : [ld_args_build_id],
+   dependencies : [idep_mesaclc, dep_llvm, dep_spirv_tools, idep_getopt],
+-  # If we can run host binaries directly, just build mesa_clc for the host.
+-  # Most commonly this happens when doing a cross compile from an x86_64 build
+-  # machine to an x86 host
+-  native : not meson.can_run_host_binaries(),
+ )
```

**Review by misuzu — APPROVED** [review]
Fixes `pkgsCross.aarch64-multiplatform.llvmPackages_19.libclc`

**Comment by vcunat** [comment]
That didn't build for me:
```
[2903/3039] Generating builtins.opt.clspv--.bc
/nix/store/ypkf4zwhgja2b0sd9mvhwzycn4kx0ldq-llvm-19.1.5/bin/opt: WARNING: failed to create target machine for 'spir-unknown-unknown': unable to get target for 'spir-unknown-unknown', see --version and --triple.
[2904/3039] Generating clspv--.bc
FAILED: clspv--.bc /build/libclc-src-19.1.5/libclc/build/clspv--.bc 
cd /build/libclc-src-19.1.5/libclc/build && prepare_builtins -o clspv--.bc builtins.opt.clspv--.bc
/bin/sh: prepare_builtins: not found
[2905/3039] Generating builtins.opt.clspv64--.bc
/nix/store/ypkf4zwhgja2b0sd9mvhwzycn4kx0ldq-llvm-19.1.5/bin/opt: WARNING: failed to create target machine for 'spir64-unknown-unknown': unable to get target for 'spir64-unknown-unknown', see --version and --triple.
[...]
ninja: build stopped: subcommand failed.
```

**Comment by NickCao** [comment]
The warnings are unrelated

> /bin/sh: prepare_builtins: not found

Ought to be fixed by this. Wrong commit?

**Comment by vcunat** [comment]
That's quite possible.

**Pull request merged**
