### PR TITLE
haskellPackages: update stackage and hackage

### PR DESCRIPTION
**Pull request by maralorn**
### This Merge

This PR is the regular merge of the `haskell-updates` branch into `master`.

This branch is being continually built and tested by hydra at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates. You may be able to find an up-to-date Hydra build report at [cdepillabout/nix-haskell-updates-status](https://github.com/cdepillabout/nix-haskell-updates-status).

We roughly aim to merge these `haskell-updates` PRs at least once every two weeks. See the @NixOS/haskell [team calendar](https://cloud.maralorn.de/apps/calendar/p/H6migHmKX7xHoTFa) for who is currently in charge of this branch.

### haskellPackages Workflow Summary

Our workflow is currently described in [`pkgs/development/haskell-modules/HACKING.md`](https://github.com/NixOS/nixpkgs/blob/haskell-updates/pkgs/development/haskell-modules/HACKING.md).

The short version is this:
* We regularly update the Stackage and Hackage pins on `haskell-updates` (normally at the beginning of a merge window).
* The community fixes builds of Haskell packages on that branch.
* We aim at at least one merge of `haskell-updates` into `master` every two weeks.
* We only do the merge if the [`mergeable`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/mergeable) job is succeeding on hydra.
* If a [`maintained`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/maintained) package is still broken at the time of merge, we will only merge if the maintainer has been pinged 7 days in advance. (If you care about a Haskell package, become a maintainer!)

More information about Haskell packages in nixpkgs can be found [in the nixpkgs manual](https://nixos.org/manual/nixpkgs/unstable/#haskell).

---

This is the follow-up to #226832. Come to [#haskell:nixos.org](https://matrix.to/#/#haskell:nixos.org) if you have any questions.

### CODE REVIEW

**Comment by maralorn** [comment]
@Gabriella439 Currently we pin dhall to 1.41.2 from stackage, but the newest dhall-nix release requires dhall 1.42.
The simplest solution is to manually pin dhall-nix to the previous version, would that be okay with you?

**Comment by maralorn** [comment]
Okay, @thielema, here comes the fallout from the packages we activated.

#### Maintained Linux packages with build failure
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/217010253) [[:penguin::x:]](https://hydra.nixos.org/build/217010206) [haskellPackages.audacity](https://hydra.nixos.org/eval/1793973?filter=haskellPackages.audacity) @thielema
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/217010203) [[:penguin::x:]](https://hydra.nixos.org/build/217010223) [haskellPackages.comfort-fftw](https://hydra.nixos.org/eval/1793973?filter=haskellPackages.comfort-fftw) @thielema
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/217010164) [[:penguin::x:]](https://hydra.nixos.org/build/217010147) [haskellPackages.med-module](https://hydra.nixos.org/eval/1793973?filter=haskellPackages.med-module) @thielema
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/217010146) [[:penguin::x:]](https://hydra.nixos.org/build/217010142) [haskellPackages.spreadsheet](https://hydra.nixos.org/eval/1793973?filter=haskellPackages.spreadsheet) @thielema
#### Maintained Linux packages with failed dependency
- [ ] [[:iphone::heavy_exclamation_mark:]](https://hydra.nixos.org/build/217010191) [[:penguin::heavy_exclamation_mark:]](https://hydra.nixos.org/build/217010175) [haskellPackages.align-audio](https://hydra.nixos.org/eval/1793973?filter=haskellPackages.align-audio) @thielema
- [ ] [[:iphone::heavy_exclamation_mark:]](https://hydra.nixos.org/build/217010165) [[:penguin::heavy_exclamation_mark:]](https://hydra.nixos.org/build/217010154) [haskellPackages.cutter](https://hydra.nixos.org/eval/1793973?filter=haskellPackages.cutter) @thielema
- [ ] [[:iphone::heavy_exclamation_mark:]](https://hydra.nixos.org/build/217010158) [[:penguin::heavy_exclamation_mark:]](https://hydra.nixos.org/build/217010136) [haskellPackages.mbox-utility](https://hydra.nixos.org/eval/1793973?filter=haskellPackages.mbox-utility) @thielema
- [ ] [[:iphone::heavy_exclamation_mark:]](https://hydra.nixos.org/build/217010202) [[:penguin::heavy_exclamation_mark:]](https://hydra.nixos.org/build/217010177) [haskellPackages.sound-collage](https://hydra.nixos.org/eval/1793973?filter=haskellPackages.sound-collage) @thielema

**Comment by maralorn** [comment]
@vcunat fa8367c2 introduced eval errors to our branch: https://hydra.nixos.org/jobset/nixpkgs/haskell-updates#tabs-errors
Anything we can/should do about this?

**Comment by vcunat** [comment]
That should've been fixed in 6c43a3495a11, so e.g. pull master again.

**Comment by thielema** [comment]
On Sat, 22 Apr 2023, maralorn wrote:

> Okay, @thielema, here comes the fallout from the packages we activated.
>
>     Maintained Linux packages with build failure
>
>  *  [📱❌] [🐧❌] haskellPackages.comfort-fftw @thielema

I fixed this one with a new release on Hackage, version 0.0.0.1.

Problem was, that -0.00 was expected, but 0.00 was computed. So it was a 
slight rounding problem.

Will Nix use the version from Hackage automatically or will it stick to 
the Stackage version?

>     Maintained Linux packages with failed dependency
>
>  *  [📱❗] [🐧❗] haskellPackages.align-audio @thielema
>  *  [📱❗] [🐧❗] haskellPackages.sound-collage @thielema

These should be fixed by the comfort-fftw fix.

**Comment by thielema** [comment]
On Sat, 22 Apr 2023, maralorn wrote:

>     Maintained Linux packages with build failure
>
>  *  [📱❌] [🐧❌] haskellPackages.med-module @thielema

Its example "animed" depends on packages hps and hcg-minus. Both are 
deprecated. I can certainly add fixes, but cannot release to Hackage. Can 
and should I prepare custom fixes and how would I contribute them to Nix? 
Alternative would be to disable "animed" and only build "unmed2" example. 
But currently there is only one Cabal flag to build them both or none of 
them. Alternatively I could disable buildExamples flag, again.

**Comment by thielema** [comment]
On Sat, 22 Apr 2023, maralorn wrote:

>     Maintained Linux packages with build failure
>
>  *  [📱❌] [🐧❌] haskellPackages.audacity @thielema

hackage-packages.nix lacks libraryHaskellDepends for optparse-applicative 
and soxlib. These are activated in the Cabal file conditionally, depending 
on the buildExamples flag.

>  *  [📱❌] [🐧❌] haskellPackages.spreadsheet @thielema

Relaxed version bounds on optparse-applicative and shell-utility at 
Hackage.

>  *  [📱❗] [🐧❗] haskellPackages.cutter @thielema
>  *  [📱❗] [🐧❗] haskellPackages.mbox-utility @thielema

They fail because of their dependency on `spreadsheet`.

**Comment by maralorn** [comment]
> I fixed this one with a new release on Hackage, version 0.0.0.1. Problem was, that -0.00 was expected, but 0.00 was computed. So it was a slight rounding problem. Will Nix use the version from Hackage automatically or will it stick to the Stackage version?

By default, it will stick to the stackage version. I guess we have the choice between overriding that or disabling the tests for now.

**Comment by maralorn** [comment]
> On Sat, 22 Apr 2023, maralorn wrote: Maintained Linux packages with build failure * [iphonex] [penguinx] haskellPackages.med-module @thielema
> Its example "animed" depends on packages hps and hcg-minus. Both are deprecated. I can certainly add fixes, but cannot release to Hackage. Can and should I prepare custom fixes and how would I contribute them to Nix? Alternative would be to disable "animed" and only build "unmed2" example. But currently there is only one Cabal flag to build them both or none of them. Alternatively I could disable buildExamples flag, again.

We can apply a patch (e.g. one disabling the deprecated example), especially if we can fetch them from remotes. We are not huge fans of checking in patches into nixpkgs. You can look for examples using `fetchpatch` in `configuration-common.nix`.
I don’t know how much you care about those examples. I would probably suggest just disabling them, but I’ll leave it up to you.

**Comment by thielema** [comment]
On Sat, 22 Apr 2023, maralorn wrote:

> We can apply a patch (e.g. one disabling the deprecated example), 
> especially if we can fetch them from remotes. We are not huge fans of 
> checking in patches into nixpkgs. You can look for examples using 
> fetchpatch in configuration-common.nix.

I don't know whether patches are the right way to go.

I succeeded to build the examples with GHC-9.4.5 using certain Git commits 
of imported packages. In my cabal.project file I have added

~~~~
source-repository-package
     type: git
     location: https://gitlab.com/rd--/hps
     tag: 7cc3d7b981a71967619dfef24e3f525e58530cf9

source-repository-package
     type: git
     location: https://gitlab.com/rd--/hcg-minus
     tag: e5254e43a5e76ebffbb238e4b7e43114a5be695d

source-repository-package
     type: git
     location: https://gitlab.com/rd--/hmt-base
     tag: d8520843ee3de93b4a8b8bb539116d55360b6f58
~~~~

Then I need some patches in my med-module package. I can release them to 
Hackage. However, the author of hps, hcg-minus, hmt-base says, that those 
packages are deprecated and thus he hesitates to release them to Hackage.

Is it possible to define a Nix-Haskell-package with sources pulled from a 
git commit?


> I don’t know how much you care about those examples. I would probably 
> suggest just disabling them, but I’ll leave it up to you.

My idea was to provide the users with prebuilt executables that are hard 
to build by themselves.

**Comment by sternenseemann** [comment]
I think it is less of a nightmare going forward if we not manually try to keep deprecated packages working unless we absolutely have to. Especially if they are only required by example binaries. I'm personally not convinced building examples is necessarily worth it in nixpkgs in the first place, they should at least use separate bin outputs to decrease download sizes for those that only depend on the library — Haskell binaries are quite big due to static linking.

**Comment by maralorn** [comment]
I also think continuing support for three deprecated libraries in nixpkgs is unwise.

**Comment by maralorn** [comment]
@thielema I would like to merge this PR now. I assume the med-module issue is not very urgent. I will, for now, disable the examples so that the package at least builds. Feel free open a PR fixing the examples somehow whenever you feel like it.

**Pull request merged**
