### PR TITLE
terraform-lsp: use buildGoModule

### PR DESCRIPTION
**Pull request by azahi**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Kranzes — CHANGES_REQUESTED** [review]
Please specify a hash for vendorSha256. Do this for all the PRs you've created in the past couple of days.

I am not going to manually go through all of your PRs with a similar change and review them to add a hash. This hash isn't *needed* but highly recommended to avoid having unreproducibile builds.

Tagging @aaronjheng since they seem to be doing a similar thing right now.

**Comment by azahi** [comment]
@Kranzes `vendorSha256` is null here because the source repository already has a `./vendor` directory with vendored dependencies. If I'm understanding Go's build system and `buildGoModule` correctly, these dependencies are already present not being pulled during build, and thus reproducible, given that changes in vendor would reflect in the tarball/git repo's hash.

I can do something like this:
```diff
diff --git i/pkgs/development/tools/misc/terraform-lsp/default.nix w/pkgs/development/tools/misc/terraform-lsp/default.nix
index 1f35f769623..ce8f5c08fcf 100644
--- i/pkgs/development/tools/misc/terraform-lsp/default.nix
+++ w/pkgs/development/tools/misc/terraform-lsp/default.nix
@@ -14,7 +14,8 @@ buildGoModule rec {
     sha256 = "111350jbq0dp0qhk48j12hrlisd1fwzqpcv357igrbqf6ki7r78q";
   };
 
-  vendorSha256 = null;
+  deleteVendor = true;
+  vendorSha256 = "sha256-0CdGQ4wwFyY7GQ1pm6aZ9jGx1D+ST6Hbq9NxJuCPJYE=";
 
   ldflags = [ "-s" "-w" "-X main.Version=${version}" "-X main.GitCommit=${src.rev}" ];
```

Which would delete vendored dependencies and repopulate them checking for hash. But I honestly think that this is a bit excessive and gives nothing of value since we have already checked for hash.

**Comment by Kranzes** [comment]
I still believe `vendorSha256` should be specified so we can fetch the deps ourself snd stop relying on upstream. This is what's recommended and I believe there are more reasons to do it that way. `deleteVendor` doesn't seem to be needed though.

**Comment by azahi** [comment]
That is not possible because of [this snippet](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/go-modules/generic/default.nix#L103-L106).

If I try to explicitly specify `vendorSha256` without enabling `deleteVendor`, I'll just get an error:
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/0psn9dl7sqbl31kfc72rfzi4nfjg58zl-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
@nix { "action": "setPhase", "phase": "buildPhase" }
building
vendor folder exists, please set 'vendorSha256 = null;' in your expression
```

**Comment by Kranzes** [comment]
Oh right, I didn't understand the structure of the src. I still prefer hashing the vendor on the nixpkgs level over relying on upstream.

**Comment by zowoq** [comment]
> [`deleteVendor`](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/go.section.md#deletevendor-var-go-deletevendor)
> This should only be used if the dependencies included in the vendor folder are broken or incomplete.

**Comment by aaronjheng** [comment]
If we want ignore `vendor` in source tree, It's better to do it in `buildGoModule`.

**Pull request merged**
