### PR TITLE
gpsd: unbreak the build for guiSupport=false

### PR DESCRIPTION
**Pull request by ghost**
###### Description of changes

The `rm $out/bin/xgps*` command fails because that file is not there in the first place.  Let's change it to `rm -f $out/bin/xgps*` so we can build with `guiSupport=false`.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by amjoseph-nixpkgs** [comment]
Ping @bjornfor @rasendubi

**Comment by vcunat** [comment]
Do I understand that the file is never there?  (assuming `guiSupport == false`)  Why not delete that line then?

**Comment by amjoseph-nixpkgs** [comment]
> Do I understand that the file is never there? (assuming `guiSupport == false`)

I believe that is correct.

> Why not delete that line then?

An abundance of caution.  But you're right, leaving dead code there is worse.  I've removed it in the latest commit.

**Comment by vcunat** [comment]
It fails the same on 22.05.

**Pull request merged**
