### PR TITLE
generic-builder: Use buildInputs for haskell deps

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

This actually will matter when I (soon) land cross-compilation support,
and native deps are compiled for the build, instead of host, platform.
But even now, it's good style do this, and one less thing to review
later.

Also, no idea whether this is enough of a rebuild that it should go to staging, or master is fine.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peti** [comment]
Pushed to `haskell-updates` as bd5854a23a2fb1480c6113a000c278d277565c5b so that Hydra can build this at http://hydra.nixos.org/jobset/nixpkgs/haskell-updates.

**Comment by Ericson2314** [comment]
Thanks!

**Comment by peti** [comment]
It appears that this change broke ~3500 builds: http://hydra.nixos.org/jobset/nixpkgs/haskell-updates

**Comment by Ericson2314** [comment]
@peti Sorry about that. Very odd, as it looks like the issue is dependencies aren't being propagated, and I ran into that *and* fixed it when applying this diff locally. I'll take another look soon.

**Comment by Ericson2314** [comment]
Ah, OK. The problem was stdenv was still using the `propagated-native-build-inputs` file, for non-cross. Rather than go back to using that file, I skipped the redundant traversal and just used the `nativePks` variable which stdenv defined the first time.

Unfortunately, when I actually merge support for cross, I'll need to conditionally swap out `nativePkgs` for `crossPkgs`. There's no way to write a non-conditional expression now due to the poor design of stdenv's `setup.sh` with these matters, but I plan on fixing these in the future with by introducing `${build,host,target}Pkgs`, which will unconditionally collect the corresponding inputs. For a sneak preview, see https://github.com/obsidiansystems/nixpkgs/commit/stdenv-setup-ng

**Comment by peti** [comment]
Pushed to Hydra in 4e1a62311745c5e09c87fe18557847da06d2014b.

**Comment by Ericson2314** [comment]
@peti looks like this one didn't screw up then? *wipes brow*

**Pull request closed without merging**
