### PR TITLE
nixos: some improvements for dnscrypt-proxy

### PR DESCRIPTION
**Pull request by joachifm**
Enable systemd support and some additional hardening.

### CODE REVIEW

**Comment by joachifm** [comment]
Pushed a squashed series which I hope makes a bit more sense.

**Comment by joachifm** [comment]
Rebased on master to resolve merge conflict.

**Comment by joachifm** [comment]
Rebased & added support for custom upstream resolvers.

**Comment by joachifm** [comment]
I've used these changes for a long time without problems, I believe they should be merged at some point.

**Comment by joachifm** [comment]
Bump.

**Comment by falsifian** [comment]
Thanks for the PR, and sorry for the delay. I think it's a good idea to @ - mention people familiar with the files you're changing, or to ping the nix-dev mailing list. Unfortunately we don't seem to have an effective way to make sure things like this don't fall through the cracks.

(I personally have no idea what dnscrypt-proxy is but these look like careful changes so I merged them.)

**Comment by falsifian** [comment]
(I mean, do that next time you want someone to pay attention to your PR; you don't have to do it now.)

**Pull request merged**
