### PR TITLE
qt6.qtbase: derive plugin load path from PATH

### LINKED ISSUE #270028: Qt 6 is unable to pick up plugins on non-NixOS
### Describe the bug
Doing `nix profile install nixpkgs#qt6ct` doesn't make Qt 6 to use qt6ct despite `QT_QPA_PLATFORMTHEME=qt6ct` is set. Perhaps that's because https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/qt-5/5.15/qtbase.patch.d/0009-qtbase-qtpluginpath.patch is not ported to Qt 6.

### Steps To Reproduce
1. `QT_QPA_PLATFORMTHEME=qt6ct`
2. `nix profile install nixpkgs#qt6ct`
3. Install & run any Qt 6 application

### Expected behavior
Application follows qt6ct settings

### Notify maintainers
@milahu @NIckCao

### Metadata

```console

 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.9-lqx1, NixOS, 23.11 (Tapir), 23.11.19700101.dirty`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.17.1`
 - nixpkgs: `/etc/static/nixpkgs`
```
(I'm reporting this for other person)

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by NickCao**
## Description of changes
Fixes https://github.com/NixOS/nixpkgs/issues/270028

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by NickCao** [comment]
@ofborg build qt6.qtbase qt6.qtdeclarative telegram-desktop

**Comment by NickCao** [comment]
Tested with copyq, works with qt6ct.

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 270036` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>obs-studio-plugins.obs-hyperion</li>
    <li>python310Packages.theanoWithCuda</li>
    <li>python310Packages.theanoWithCuda.dist</li>
    <li>python311Packages.theanoWithCuda</li>
    <li>python311Packages.theanoWithCuda.dist</li>
    <li>truecrack-cuda</li>
  </ul>
</details>
<details>
  <summary>19 packages failed to build:</summary>
  <ul>
    <li>cudaPackages.tensorrt</li>
    <li>cudaPackages.tensorrt.dev</li>
    <li>cudaPackages.tensorrt_8_5_1</li>
    <li>cudaPackages.tensorrt_8_5_1.dev</li>
    <li>cudaPackages.tensorrt_8_5_2</li>
    <li>cudaPackages.tensorrt_8_5_2.dev</li>
    <li>cudaPackages.tensorrt_8_6_0</li>
    <li>cudaPackages.tensorrt_8_6_0.dev</li>
    <li>katagoTensorRT</li>
    <li>obs-studio-plugins.obs-ndi</li>
    <li>obs-studio-plugins.obs-replay-source</li>
    <li>python310Packages.tensorrt</li>
    <li>python310Packages.tensorrt.dist</li>
    <li>python311Packages.tensorrt</li>
    <li>python311Packages.tensorrt.dist</li>
    <li>xpraWithNvenc</li>
    <li>xpraWithNvenc.dist</li>
    <li>yandex-browser</li>
    <li>yandex-browser-beta</li>
  </ul>
</details>
<details>
  <summary>341 packages built:</summary>
  <ul>
    <li>abracadabra</li>
    <li>activitywatch</li>
    <li>adwaita-qt6</li>
    <li>adwaita-qt6.dev</li>
    <li>albert</li>
    <li>alice-tools-qt6</li>
    <li>anki</li>
    <li>anki.dist</li>
    <li>anki.doc</li>
    <li>anki.man</li>
    <li>ao (python311Packages.libfive)</li>
    <li>ausweisapp</li>
    <li>aw-qt</li>
    <li>aw-qt.dist</li>
    <li>bambootracker-qt6</li>
    <li>beamerpresenter</li>
    <li>beamerpresenter-poppler</li>
    <li>bloom</li>
    <li>calcmysky</li>
    <li>calibre</li>
    <li>citra-canary</li>
    <li>citra-nightly</li>
    <li>colmapWithCuda</li>
    <li>comic-mandown</li>
    <li>comic-mandown.dist</li>
    <li>copyq</li>
    <li>cudaPackages.cuda-samples</li>
    <li>cudaPackages.cudatoolkit</li>
    <li>cudaPackages.cudatoolkit.doc</li>
    <li>cudaPackages.cudatoolkit.lib</li>
    <li>cudaPackages.cutensor</li>
    <li>cudaPackages.cutensor.dev</li>
    <li>cudaPackages.nsight_compute (cudaPackages.nsight_compute.bin)</li>
    <li>cutemaze</li>
    <li>discord-screenaudio</li>
    <li>dolphin-emu</li>
    <li>dsview</li>
    <li>duckstation</li>
    <li>fcitx5-chinese-addons</li>
    <li>fcitx5-configtool</li>
    <li>fcitx5-skk-qt</li>
    <li>fcitx5-unikey</li>
    <li>fcitx5-with-addons</li>
    <li>feather</li>
    <li>focuswriter</li>
    <li>forge</li>
    <li>gammaray</li>
    <li>goldendict-ng</li>
    <li>gpu-burn</li>
    <li>gpxsee-qt6</li>
    <li>gqrx</li>
    <li>gqrx-gr-audio</li>
    <li>gqrx-portaudio</li>
    <li>gromacsCudaMpi</li>
    <li>gromacsCudaMpi.dev</li>
    <li>gromacsCudaMpi.man</li>
    <li>gwe</li>
    <li>haka</li>
    <li>hydrus</li>
    <li>hydrus.doc</li>
    <li>in-formant</li>
    <li>ipe</li>
    <li>jami</li>
    <li>katagoWithCuda</li>
    <li>kdsingleapplication</li>
    <li>kemai</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>ladybird</li>
    <li>libre-graph-api-cpp-qt-client</li>
    <li>librealsenseWithCuda</li>
    <li>librealsenseWithCuda.dev</li>
    <li>libremines</li>
    <li>libsForQt5.fcitx5-qt</li>
    <li>maestral-gui</li>
    <li>maestral-gui.dist</li>
    <li>maskromtool</li>
    <li>mediaelch-qt6</li>
    <li>mediawriter</li>
    <li>miniaudicle</li>
    <li>mnemosyne</li>
    <li>mnemosyne.dist</li>
    <li>mozillavpn</li>
    <li>nanovna-saver</li>
    <li>nanovna-saver.dist</li>
    <li>normcap</li>
    <li>normcap.dist</li>
    <li>notes</li>
    <li>nvtop</li>
    <li>nvtop-nvidia</li>
    <li>obs-studio</li>
    <li>obs-studio-plugins.advanced-scene-switcher</li>
    <li>obs-studio-plugins.droidcam-obs</li>
    <li>obs-studio-plugins.input-overlay</li>
    <li>obs-studio-plugins.looking-glass-obs</li>
    <li>obs-studio-plugins.obs-3d-effect</li>
    <li>obs-studio-plugins.obs-backgroundremoval</li>
    <li>obs-studio-plugins.obs-command-source</li>
    <li>obs-studio-plugins.obs-freeze-filter</li>
    <li>obs-studio-plugins.obs-gradient-source</li>
    <li>obs-studio-plugins.obs-gstreamer</li>
    <li>obs-studio-plugins.obs-livesplit-one</li>
    <li>obs-studio-plugins.obs-move-transition</li>
    <li>obs-studio-plugins.obs-multi-rtmp</li>
    <li>obs-studio-plugins.obs-mute-filter</li>
    <li>obs-studio-plugins.obs-nvfbc</li>
    <li>obs-studio-plugins.obs-pipewire-audio-capture</li>
    <li>obs-studio-plugins.obs-rgb-levels-filter</li>
    <li>obs-studio-plugins.obs-scale-to-sound</li>
    <li>obs-studio-plugins.obs-shaderfilter</li>
    <li>obs-studio-plugins.obs-source-clone</li>
    <li>obs-studio-plugins.obs-source-record</li>
    <li>obs-studio-plugins.obs-source-switcher</li>
    <li>obs-studio-plugins.obs-teleport</li>
    <li>obs-studio-plugins.obs-text-pthread</li>
    <li>obs-studio-plugins.obs-transition-table</li>
    <li>obs-studio-plugins.obs-tuna</li>
    <li>obs-studio-plugins.obs-vaapi</li>
    <li>obs-studio-plugins.obs-vertical-canvas</li>
    <li>obs-studio-plugins.obs-vintage-filter</li>
    <li>obs-studio-plugins.obs-vkcapture</li>
    <li>obs-studio-plugins.obs-websocket</li>
    <li>obs-studio-plugins.waveform</li>
    <li>obs-studio-plugins.wlrobs</li>
    <li>olive-editor</li>
    <li>onedrivegui</li>
    <li>onedrivegui.dist</li>
    <li>organicmaps</li>
    <li>ostinato</li>
    <li>owncloud-client</li>
    <li>passes</li>
    <li>path-of-building</li>
    <li>pcsx2</li>
    <li>pgmodeler</li>
    <li>pineapple-pictures</li>
    <li>pokefinder</li>
    <li>prismlauncher</li>
    <li>prismlauncher-unwrapped</li>
    <li>punes-qt6</li>
    <li>python310Packages.cupy</li>
    <li>python310Packages.cupy.dist</li>
    <li>python310Packages.echo</li>
    <li>python310Packages.echo.dist</li>
    <li>python310Packages.glueviz</li>
    <li>python310Packages.glueviz.dist</li>
    <li>python310Packages.jaxlibWithCuda</li>
    <li>python310Packages.jaxlibWithCuda.dist</li>
    <li>python310Packages.libfive</li>
    <li>python310Packages.lightgbm</li>
    <li>python310Packages.lightgbm.dist</li>
    <li>python310Packages.numbaWithCuda</li>
    <li>python310Packages.numbaWithCuda.dist</li>
    <li>python310Packages.pvextractor</li>
    <li>python310Packages.pvextractor.dist</li>
    <li>python310Packages.pycuda</li>
    <li>python310Packages.pycuda.dist</li>
    <li>python310Packages.pynvml</li>
    <li>python310Packages.pynvml.dist</li>
    <li>python310Packages.pyqt6</li>
    <li>python310Packages.pyqt6-charts</li>
    <li>python310Packages.pyqt6-charts.dist</li>
    <li>python310Packages.pyqt6-webengine</li>
    <li>python310Packages.pyqt6-webengine.dev</li>
    <li>python310Packages.pyqt6-webengine.dist</li>
    <li>python310Packages.pyqt6.dev</li>
    <li>python310Packages.pyqt6.dist</li>
    <li>python310Packages.pyrealsense2WithCuda</li>
    <li>python310Packages.pyrealsense2WithCuda.dev</li>
    <li>python310Packages.pyside6</li>
    <li>python310Packages.shap</li>
    <li>python310Packages.shap.dist</li>
    <li>python310Packages.shiboken6</li>
    <li>python310Packages.tensorflowWithCuda</li>
    <li>python310Packages.tensorflowWithCuda.dist</li>
    <li>python311Packages.cupy</li>
    <li>python311Packages.cupy.dist</li>
    <li>python311Packages.echo</li>
    <li>python311Packages.echo.dist</li>
    <li>python311Packages.glueviz</li>
    <li>python311Packages.glueviz.dist</li>
    <li>python311Packages.jaxlibWithCuda</li>
    <li>python311Packages.jaxlibWithCuda.dist</li>
    <li>python311Packages.lightgbm</li>
    <li>python311Packages.lightgbm.dist</li>
    <li>python311Packages.numbaWithCuda</li>
    <li>python311Packages.numbaWithCuda.dist</li>
    <li>python311Packages.pvextractor</li>
    <li>python311Packages.pvextractor.dist</li>
    <li>python311Packages.pycuda</li>
    <li>python311Packages.pycuda.dist</li>
    <li>python311Packages.pynvml</li>
    <li>python311Packages.pynvml.dist</li>
    <li>python311Packages.pyqt6</li>
    <li>python311Packages.pyqt6-charts</li>
    <li>python311Packages.pyqt6-charts.dist</li>
    <li>python311Packages.pyqt6-webengine</li>
    <li>python311Packages.pyqt6-webengine.dev</li>
    <li>python311Packages.pyqt6-webengine.dist</li>
    <li>python311Packages.pyqt6.dev</li>
    <li>python311Packages.pyqt6.dist</li>
    <li>python311Packages.pyrealsense2WithCuda</li>
    <li>python311Packages.pyrealsense2WithCuda.dev</li>
    <li>python311Packages.pyside6</li>
    <li>python311Packages.shap</li>
    <li>python311Packages.shap.dist</li>
    <li>python311Packages.shiboken6</li>
    <li>python311Packages.tensorflowWithCuda</li>
    <li>python311Packages.tensorflowWithCuda.dist</li>
    <li>qalculate-qt</li>
    <li>qbittorrent</li>
    <li>qbittorrent-nox</li>
    <li>qgnomeplatform-qt6</li>
    <li>qlog</li>
    <li>qmmp</li>
    <li>qownnotes</li>
    <li>qpwgraph</li>
    <li>qt6.full</li>
    <li>qt6.qmake</li>
    <li>qt6.qt3d</li>
    <li>qt6.qt3d.dev</li>
    <li>qt6.qt5compat</li>
    <li>qt6.qt5compat.dev</li>
    <li>qt6.qtbase</li>
    <li>qt6.qtbase.dev</li>
    <li>qt6.qtcharts</li>
    <li>qt6.qtcharts.dev</li>
    <li>qt6.qtconnectivity</li>
    <li>qt6.qtconnectivity.dev</li>
    <li>qt6.qtdatavis3d</li>
    <li>qt6.qtdatavis3d.dev</li>
    <li>qt6.qtdeclarative</li>
    <li>qt6.qtdeclarative.dev</li>
    <li>qt6.qtdoc</li>
    <li>qt6.qtgraphs</li>
    <li>qt6.qtgraphs.dev</li>
    <li>qt6.qtgrpc</li>
    <li>qt6.qtgrpc.dev</li>
    <li>qt6.qthttpserver</li>
    <li>qt6.qthttpserver.dev</li>
    <li>qt6.qtimageformats</li>
    <li>qt6.qtimageformats.dev</li>
    <li>qt6.qtlanguageserver</li>
    <li>qt6.qtlanguageserver.dev</li>
    <li>qt6.qtlocation</li>
    <li>qt6.qtlocation.dev</li>
    <li>qt6.qtlottie</li>
    <li>qt6.qtlottie.dev</li>
    <li>qt6.qtmqtt</li>
    <li>qt6.qtmqtt.dev</li>
    <li>qt6.qtmultimedia</li>
    <li>qt6.qtmultimedia.dev</li>
    <li>qt6.qtnetworkauth</li>
    <li>qt6.qtnetworkauth.dev</li>
    <li>qt6.qtpositioning</li>
    <li>qt6.qtpositioning.dev</li>
    <li>qt6.qtquick3d</li>
    <li>qt6.qtquick3d.dev</li>
    <li>qt6.qtquick3dphysics</li>
    <li>qt6.qtquick3dphysics.dev</li>
    <li>qt6.qtquickeffectmaker</li>
    <li>qt6.qtquickeffectmaker.dev</li>
    <li>qt6.qtquicktimeline</li>
    <li>qt6.qtquicktimeline.dev</li>
    <li>qt6.qtremoteobjects</li>
    <li>qt6.qtremoteobjects.dev</li>
    <li>qt6.qtscxml</li>
    <li>qt6.qtscxml.dev</li>
    <li>qt6.qtsensors</li>
    <li>qt6.qtsensors.dev</li>
    <li>qt6.qtserialbus</li>
    <li>qt6.qtserialbus.dev</li>
    <li>qt6.qtserialport</li>
    <li>qt6.qtserialport.dev</li>
    <li>qt6.qtshadertools</li>
    <li>qt6.qtshadertools.dev</li>
    <li>qt6.qtspeech</li>
    <li>qt6.qtspeech.dev</li>
    <li>qt6.qtsvg</li>
    <li>qt6.qtsvg.dev</li>
    <li>qt6.qttools</li>
    <li>qt6.qttools.dev</li>
    <li>qt6.qttranslations</li>
    <li>qt6.qtvirtualkeyboard</li>
    <li>qt6.qtvirtualkeyboard.dev</li>
    <li>qt6.qtwayland</li>
    <li>qt6.qtwayland.dev</li>
    <li>qt6.qtwebchannel</li>
    <li>qt6.qtwebchannel.dev</li>
    <li>qt6.qtwebengine</li>
    <li>qt6.qtwebengine.dev</li>
    <li>qt6.qtwebsockets</li>
    <li>qt6.qtwebsockets.dev</li>
    <li>qt6.qtwebview</li>
    <li>qt6.qtwebview.dev</li>
    <li>qt6Packages.poppler</li>
    <li>qt6Packages.poppler.dev</li>
    <li>qt6Packages.qscintilla</li>
    <li>qt6Packages.qt6ct</li>
    <li>qt6Packages.qt6gtk2</li>
    <li>qt6Packages.qtkeychain</li>
    <li>qt6Packages.qtpbfimageplugin</li>
    <li>qt6Packages.qtstyleplugin-kvantum</li>
    <li>qt6Packages.quazip</li>
    <li>qt6Packages.quazip.dev</li>
    <li>qt6Packages.qxlsx</li>
    <li>qtcreator</li>
    <li>qtwirediff</li>
    <li>qucs-s</li>
    <li>qutebrowser</li>
    <li>qutebrowser.dist</li>
    <li>retext</li>
    <li>retext.dist</li>
    <li>retool</li>
    <li>retool.dist</li>
    <li>rocmPackages.mivisionx (rocmPackages.mivisionx-hip)</li>
    <li>rocmPackages.mivisionx-cpu</li>
    <li>rocmPackages.mivisionx-opencl</li>
    <li>rpcs3</li>
    <li>smb3-foundry</li>
    <li>stellarium</li>
    <li>streamdeck-ui</li>
    <li>streamdeck-ui.dist</li>
    <li>syncplay</li>
    <li>telegram-desktop</li>
    <li>texstudio</li>
    <li>texturepacker</li>
    <li>texworks</li>
    <li>translatelocally</li>
    <li>unbook</li>
    <li>valeronoi</li>
    <li>waycheck</li>
    <li>wireshark</li>
    <li>wireshark.dev</li>
    <li>xdg-desktop-portal-hyprland</li>
    <li>xgboostWithCuda</li>
    <li>yandex-browser-corporate</li>
    <li>yuzu-early-access</li>
    <li>yuzu-mainline</li>
    <li>zeal-qt6</li>
    <li>zint</li>
    <li>zint.dev</li>
  </ul>
</details>

**Comment by LunNova** [comment]
Noticed two different qt6 qtdeclaratives building while giving this a review run. Don't think caused by this PR.
image

**Comment by NickCao** [comment]
> Noticed two different qt6 qtdeclaratives building while giving this a review run. Don't think caused by this PR. ![image]

Might be related to https://github.com/NixOS/nixpkgs/pull/246022

**Comment by NickCao** [comment]
qt 6.6.1 just released, this PR would be merged together with the update.

**Pull request closed without merging**
