### PR TITLE
fuzzel: 1.5.0 -> 1.5.1

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

Bug fix release.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fionera** [comment]
This broke building on on current unstable, atleast for me because it needs wayland >= 1.19

**Comment by sternenseemann** [comment]
I checked out the commit `nixos-unstable` is at currently and fuzzel builds fine and seems to work without any problems it seems to me. What issue are you experiencing?

**Comment by fionera** [comment]
```
  /nix/store/lnr40av67dakzv7gqigw3crqyjv3a40n-wlroots-5e19e0053a5800252a27ce127fd015d641ee2e9e.drv
  /nix/store/5f50na1glsb2bgq66np44q31a5ad1ddb-fuzzel-1.5.1.drv
  /nix/store/0a58whiwdz2lfj31y26lpfk1k0qy50ll-user-environment.drv
  /nix/store/cyqhcdk32wq02igfm6ks02gpp0jbh8sf-etc.drv
```

```
building '/nix/store/lnr40av67dakzv7gqigw3crqyjv3a40n-wlroots-5e19e0053a5800252a27ce127fd015d641ee2e9e.drv'...
```

```
Dependency wayland-server found: NO found 1.18.0 but need: '>=1.19'
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency wayland-server found: NO

meson.build:92:0: ERROR: Invalid version of dependency, need 'wayland-server' ['>=1.19'] found '1.18.0'.

```

**Comment by sternenseemann** [comment]
Seems to me just the wlroots build is broken for some reason. `fuzzel` neither depends on `wayland-server` nor specifies a version constraint for any dependency.

**Comment by fionera** [comment]
Ok I think I found the issue but I dont understand it. It tries to build wlroots from master

**Comment by fionera** [comment]
Ok found it im stupid :D I have https://github.com/colemickens/nixpkgs-wayland/ as overlay and thats broken :)

**Pull request merged**
