### PR TITLE
Move Python modules/packages to python-packages.nix

### PR DESCRIPTION
**Pull request by FRidh**
See #11567.

To do:
- [x] Fix `bsddb3`, `--berkeley-db` flag seems to be ignored when building wheel. Luckily we could set an environment variable instead as well.
- [x] Fix `pyside`, imports fine with both 2.7 and 3.4. Version 3.5 is not supported.
- [x] pygame doesn't seem to work with Python 3 because somewhere `python` is called. Haven't found out where, so disabled for py3k for now.

Optionally:
- [ ] Move more packages ...
- [ ] Add libPrefix: https://github.com/NixOS/nixpkgs/issues/1468

### CODE REVIEW

**Comment by domenkozar** [comment]
@jagajaga opposite what?

**Comment by jagajaga** [comment]
Move expressions from `python-packages.nix` to their own files.

**Comment by domenkozar** [comment]
@jagajaga did you read my commit https://github.com/NixOS/nixpkgs/commit/6cf4e29c4f33d40c6560e25f38071c3c6a876cbb and what troubles it causes?

**Comment by jagajaga** [comment]
@domenkozar will read, thank you!

**Comment by jagajaga** [comment]
@domenkozar and what troubles does it cause? :)

**Comment by FRidh** [comment]
Please discuss this in #11567.

**Comment by domenkozar** [comment]
@FRidh let me know if some of the packages are troublesome and I'll take a peek (`bsddb3` as potential candidate)

**Comment by FRidh** [comment]
@domenkozar 
- bsddb3 works
- pygame would't work with python 3, so disabled it for py3k
- everything else seems to build and work
- nox review needs to be done

**Comment by FRidh** [comment]
Two components of pyside might actually be shared between Python 2 and 3. It only needs sphinx to generate documentation if I am correct. So that could be improved.

**Comment by domenkozar** [comment]
@FRidh let's merge this?

**Comment by FRidh** [comment]
@domenkozar yes, let's merge

**Pull request merged**
