### PR TITLE
libiconv: Correct cross-building

### PR DESCRIPTION
**Pull request by bnikolic**
###### Things done
- [ X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [X] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Select the crossDrv based on the target platform in all-packages.nix,
remove superfluous assert in libiconv

nix-shell -p nox --run "nox-review wip" fails because it tries to build libiconvReal on Linux which fails on master already

### CODE REVIEW

**Comment by vcunat** [comment]
Hmm, yes, I think so. Cross-compilation is still rather hacky, unfortunately.

**Comment by bnikolic** [comment]
I've fixed the failure in CI call into find-tarballs.nix. Remaining is the failure in libiconvReal by the automatic dependency checker -- it should try to build this on a glibc system. How to proceed?

**Comment by DavidEGrayson** [comment]
I did something similar in my pull request here: https://github.com/NixOS/nixpkgs/pull/21388

**Comment by Ericson2314** [comment]
As did I https://github.com/NixOS/nixpkgs/pull/21268. My or @DavidEGrayson's PRs should be closed in lieu of this.

**Comment by joachifm** [comment]
Closing in deference to the above mentioned PRs.

**Pull request closed without merging**
