### PR TITLE
 fractal: 4.0.0 -> 4.2.0 

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Commit Message
Build system changes happening in the following commits:

* https://gitlab.gnome.org/GNOME/fractal/commit/79bf10af6ddecf50b0dc7641658694c196f73403
* https://gitlab.gnome.org/GNOME/fractal/commit/6982765607fb0a0c9e5eae4ad32659b29e5d0fb3
* https://gitlab.gnome.org/GNOME/fractal/commit/4abfa58282e958b2ab6fe44c5e3963d1b5db258a

Submitted MR upstream to update Cargo.lock [0] and to
make scripts executable [1].

[0]: https://gitlab.gnome.org/GNOME/fractal/merge_requests/446
[1]: https://gitlab.gnome.org/GNOME/fractal/merge_requests/447

###### Things done

I've built this without checks because I couldn't tell what was going on with
them. Kept them enabled here to see how it goes with ofborg.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @dtzWill 

ping @Infinisil since I think he was interested in this.

### CODE REVIEW

**Comment by Infinisil** [comment]
I also got a build with this working when I tried to update it yesterday, however it crashed or threw an error when I tried to log in, logs here: https://gist.github.com/Infinisil/85f2d628d96e56fff7a8c6caa1fa12c7

Can you log in successfully?

**Comment by worldofpeace** [comment]
I don't think you have a secret service running. It works for me when using gnome-keyring.

**Comment by worldofpeace** [comment]
Huh, looks the like the tests timed out. Not sure if they're actually doing what they should?
From what I can tell they're running the cargo tests within meson now.

**Comment by Infinisil** [comment]
The tests just took a while to run when I built it.

Oh, well that's kinda shitty, because I could at least log in with version 4.0.0 without having to run any secret service.

**Comment by worldofpeace** [comment]
> Oh, well that's kinda shitty, because I could at least log in with version 4.0.0 without having to run any secret service.

Actually I think that you should be able to at least login, it's just your password won't be remembered.
I recall that's how it worked before. (https://gitlab.gnome.org/GNOME/fractal#password-storage)

**Comment by Infinisil** [comment]
Yeah I just tried again with this PR, it crashes in the same way when I try to log in. I already mentioned it in the fractal matrix channel yesterday, I should open a bug for this.

**Comment by Infinisil** [comment]
Opened an issue: https://gitlab.gnome.org/GNOME/fractal/issues/517

**Comment by worldofpeace** [comment]
Updated to fetch https://gitlab.gnome.org/GNOME/fractal/merge_requests/446 because it's merged.
Couldn't get https://gitlab.gnome.org/GNOME/fractal/merge_requests/447 to do anything.

**Review by dtzWill — APPROVED** [review]
Eep, something just came up sorry!

However i'm running 4.2.0 with the two commits upstream merged that were authored by you, and I'm not 100% (formatting change, this once, makes it hard to spot changes in deps if any).

If it works for you I say ship it, works for me :).  Does your 2nd commit need fetching/applying or do we just do that ourselves directly?

**Comment by worldofpeace** [comment]
> If it works for you I say ship it, works for me :). Does your 2nd commit need fetching/applying or do we just do that ourselves directly?

Didn't seem to work.

> Couldn't get https://gitlab.gnome.org/GNOME/fractal/merge_requests/447 to apply though so we still manually chmod.

Would that be like binary data need to be applied with `git apply` instead of `patch`?
Probably not worth the effort since it's just one file we needed.

**Comment by Infinisil** [comment]
Yeah so I can't use 4.2.0 after all because of above issue with gnome-keyring

**Pull request merged**
