### PR TITLE
swappy: 1.2.1 -> 1.3.0

### PR DESCRIPTION
**Pull request by bbigras**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113546` at 548460f3 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/668e686410d1ffd6437773de66466c73">swappy</a></li></li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/meson-cmake.md">meson-cmake</a>

Meson uses CMake as a fallback dependency resolution method and it likely is not necessary here. The message about cmake not being found is purely informational.

Near pkgs/applications/misc/swappy/default.nix:27:3:
```
   |
27 |   nativeBuildInputs = [ glib meson ninja pkg-config cmake scdoc ];
   |   ^
```
</li>
    <li>warning: unused-argument

Unused argument: `gio-sharp`.
Near pkgs/applications/misc/swappy/default.nix:12:3:
```
   |
12 | , gio-sharp
   |   ^
```
</li>
  </ul>
</details>

**Comment by bbigras** [comment]
I made the suggested changes.

**Comment by bbigras** [comment]
cc @matthiasbeyer

**Review by matthiasbeyer — APPROVED** [review]

**Pull request merged**
