### PR TITLE
ffmpeg: 6.1 -> 6.1.1, 5.1.3 -> 5.1.4

### PR DESCRIPTION
**Pull request by jopejoe1**
## Description of changes

Removed extraPatches that were already included upstream.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jopejoe1** [comment]
@ofgorg eval

**Comment by Atemu** [comment]
@ofBorg build ffmpeg ffmpeg-full ffmpeg_4-full ffmpeg_5-full jellyfin-ffmpeg

**Review by Atemu — APPROVED** [review]
The diff LGTM and this *should* be a minor update. I'd still like to see reports of some direct dependants build successfully.

**Comment by jopejoe1** [comment]
Result of `nixpkgs-review pr 292998` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>26 packages built:</summary>
  <ul>
    <li>dim</li>
    <li>ffmpeg_5-full</li>
    <li>ffmpeg_5-full.bin (ffmpeg_5-full.bin.bin ,ffmpeg_5-full.bin.data ,ffmpeg_5-full.bin.dev ,ffmpeg_5-full.bin.doc ,ffmpeg_5-full.bin.lib ,ffmpeg_5-full.bin.man)</li>
    <li>ffmpeg_5-full.data (ffmpeg_5-full.data.bin ,ffmpeg_5-full.data.data ,ffmpeg_5-full.data.dev ,ffmpeg_5-full.data.doc ,ffmpeg_5-full.data.lib ,ffmpeg_5-full.data.man)</li>
    <li>ffmpeg_5-full.dev (ffmpeg_5-full.dev.bin ,ffmpeg_5-full.dev.data ,ffmpeg_5-full.dev.dev ,ffmpeg_5-full.dev.doc ,ffmpeg_5-full.dev.lib ,ffmpeg_5-full.dev.man)</li>
    <li>ffmpeg_5-full.doc (ffmpeg_5-full.doc.bin ,ffmpeg_5-full.doc.data ,ffmpeg_5-full.doc.dev ,ffmpeg_5-full.doc.doc ,ffmpeg_5-full.doc.lib ,ffmpeg_5-full.doc.man)</li>
    <li>ffmpeg_5-full.lib (ffmpeg_5-full.lib.bin ,ffmpeg_5-full.lib.data ,ffmpeg_5-full.lib.dev ,ffmpeg_5-full.lib.doc ,ffmpeg_5-full.lib.lib ,ffmpeg_5-full.lib.man)</li>
    <li>ffmpeg_5-full.man (ffmpeg_5-full.man.bin ,ffmpeg_5-full.man.data ,ffmpeg_5-full.man.dev ,ffmpeg_5-full.man.doc ,ffmpeg_5-full.man.lib ,ffmpeg_5-full.man.man)</li>
    <li>ffmpeg_6-full</li>
    <li>ffmpeg_6-full.bin (ffmpeg_6-full.bin.bin ,ffmpeg_6-full.bin.data ,ffmpeg_6-full.bin.dev ,ffmpeg_6-full.bin.doc ,ffmpeg_6-full.bin.lib ,ffmpeg_6-full.bin.man)</li>
    <li>ffmpeg_6-full.data (ffmpeg_6-full.data.bin ,ffmpeg_6-full.data.data ,ffmpeg_6-full.data.dev ,ffmpeg_6-full.data.doc ,ffmpeg_6-full.data.lib ,ffmpeg_6-full.data.man)</li>
    <li>ffmpeg_6-full.dev (ffmpeg_6-full.dev.bin ,ffmpeg_6-full.dev.data ,ffmpeg_6-full.dev.dev ,ffmpeg_6-full.dev.doc ,ffmpeg_6-full.dev.lib ,ffmpeg_6-full.dev.man)</li>
    <li>ffmpeg_6-full.doc (ffmpeg_6-full.doc.bin ,ffmpeg_6-full.doc.data ,ffmpeg_6-full.doc.dev ,ffmpeg_6-full.doc.doc ,ffmpeg_6-full.doc.lib ,ffmpeg_6-full.doc.man)</li>
    <li>ffmpeg_6-full.lib (ffmpeg_6-full.lib.bin ,ffmpeg_6-full.lib.data ,ffmpeg_6-full.lib.dev ,ffmpeg_6-full.lib.doc ,ffmpeg_6-full.lib.lib ,ffmpeg_6-full.lib.man)</li>
    <li>ffmpeg_6-full.man (ffmpeg_6-full.man.bin ,ffmpeg_6-full.man.data ,ffmpeg_6-full.man.dev ,ffmpeg_6-full.man.doc ,ffmpeg_6-full.man.lib ,ffmpeg_6-full.man.man)</li>
    <li>ffmpegthumbnailer</li>
    <li>jellyfin-ffmpeg</li>
    <li>jellyfin-ffmpeg.bin (jellyfin-ffmpeg.bin.bin ,jellyfin-ffmpeg.bin.data ,jellyfin-ffmpeg.bin.dev ,jellyfin-ffmpeg.bin.doc ,jellyfin-ffmpeg.bin.lib ,jellyfin-ffmpeg.bin.man)</li>
    <li>jellyfin-ffmpeg.data (jellyfin-ffmpeg.data.bin ,jellyfin-ffmpeg.data.data ,jellyfin-ffmpeg.data.dev ,jellyfin-ffmpeg.data.doc ,jellyfin-ffmpeg.data.lib ,jellyfin-ffmpeg.data.man)</li>
    <li>jellyfin-ffmpeg.dev (jellyfin-ffmpeg.dev.bin ,jellyfin-ffmpeg.dev.data ,jellyfin-ffmpeg.dev.dev ,jellyfin-ffmpeg.dev.doc ,jellyfin-ffmpeg.dev.lib ,jellyfin-ffmpeg.dev.man)</li>
    <li>jellyfin-ffmpeg.doc (jellyfin-ffmpeg.doc.bin ,jellyfin-ffmpeg.doc.data ,jellyfin-ffmpeg.doc.dev ,jellyfin-ffmpeg.doc.doc ,jellyfin-ffmpeg.doc.lib ,jellyfin-ffmpeg.doc.man)</li>
    <li>jellyfin-ffmpeg.lib (jellyfin-ffmpeg.lib.bin ,jellyfin-ffmpeg.lib.data ,jellyfin-ffmpeg.lib.dev ,jellyfin-ffmpeg.lib.doc ,jellyfin-ffmpeg.lib.lib ,jellyfin-ffmpeg.lib.man)</li>
    <li>jellyfin-ffmpeg.man (jellyfin-ffmpeg.man.bin ,jellyfin-ffmpeg.man.data ,jellyfin-ffmpeg.man.dev ,jellyfin-ffmpeg.man.doc ,jellyfin-ffmpeg.man.lib ,jellyfin-ffmpeg.man.man)</li>
    <li>mpv</li>
    <li>openmw</li>
    <li>vlc</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
@jopejoe1 On which base did you run these tests?  On staging the binutils patch does not apply for `ffmpeg_5` anymore.

**Comment by jopejoe1** [comment]
I based it on acdc68ae37415027dd38747b9bee5d10cbf57c0f which was the merge base between master and staging at the point of the PR creation.

**Comment by mweinelt** [comment]
Yeah, that was insufficient, because https://github.com/NixOS/nixpkgs/pull/283732 had been on staging for two weeks by then.

**Comment by jopejoe1** [comment]
Created a fix for it in  #294521

**Pull request merged**
