### PR TITLE
yj: init at 4.0.0

### PR DESCRIPTION
**Pull request by Profpatsch**
Converter between json/yaml/toml (minimal wrapper around go libraries)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Profpatsch** [comment]
@GrahamcOfBorg build yj

**Review by marsam — CHANGES_REQUESTED** [review]
Looks like upstream uses go modules. Can you use [`buildGoModule`](https://nixos.org/nixpkgs/manual/#ssec-go-modules)?

**Comment by Profpatsch** [comment]
> Can you use [`buildGoModule`](https://nixos.org/nixpkgs/manual/#ssec-go-modules)?

I’d rather not, because it uses fixed output derivations.

**Comment by domenkozar** [comment]
I wonder what it does if you have a heterogenous list in JSON and try to convert to TOML.

**Comment by Profpatsch** [comment]
> I wonder what it does if you have a heterogenous list in JSON and try to convert to TOML.

It only uses the golang default libraries, so you’ll have to defer to them. Probably something absurdly questionable.

---

@marsam ping

**Review by marsam — APPROVED** [review]

**Comment by marsam** [comment]
>I’d rather not, because it uses fixed output derivations

No problem. I'm slightly inclined to `buildGoModule` because deps.nix it's a bit of a pain to maintain

**Pull request merged**
