### PR TITLE
perl: 5.34.1 -> 5.36.0, perldevel: 5.35.9 -> 5.37.0, perl-cross: 31dac3e2 -> c8760457

### PR DESCRIPTION
**Pull request by stigtsp**
###### Description of changes

- Update `perl` from 5.34.1 to 5.36.0
  https://metacpan.org/release/RJBS/perl-5.36.0/changes
  - perl536: init at 5.36.0
  - perl: perl534 -> perl536
  - perlPackages: perl534Packages -> perl536Packages
  - perl532: removed

- Updates to `perlPackages`
  - perlPackages.BKeywords: 1.22 -> 1.24 
  - perlPackages.DBIxClass: 0.082842 -> 0.082843

- Update `perldevel` from 5.39.9 to 5.37.0
  https://metacpan.org/release/RJBS/perl-5.37.0/changes

- Update `perl-cross` from https://github.com/arsv/perl-cross/commit/31dac3e2 to https://github.com/arsv/perl-cross/commit/c876045741f5159318085d2737b0090f35a842ca 

- Fixed `unit`: add perl536 as default, remove perl532

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ajs124** [comment]
@GrahamcOfBorg build rt
@GrahamcOfBorg test switchTest

**Comment by ajs124** [comment]
hm. maybe we should build everything with this on hydra and see what the fallout is like? Or do you think we can just go ahead with this, as is?

**Comment by stigtsp** [comment]
@GrahamcOfBorg build perlPackages.DBDmysql perlPackages.IOSocketSSL
@GrahamcOfBorg build hydra-unstable
@GrahamcOfBorg test switchTest

**Comment by stigtsp** [comment]
The latest `perldevel` (perl 5.37.2) doesn't build, but don't think this should hold up the 5.36.0 update for the stable perl.

**Comment by stigtsp** [comment]
@GrahamcOfBorg build pkgsCross.aarch64-multiplatform.perlPackages.NetDBus

**Comment by stigtsp** [comment]
@GrahamcOfBorg build hydra-unstable
@GrahamcOfBorg test switchTest

**Comment by stigtsp** [comment]
Testing some builds after rebasing to staging at a3b3912772e6b80e12e1eb86f14c60776b71b03f:
- [ ] pkgsCross.aarch64-multiplatform.perlPackages.NetDBus
- [ ] hydra-unstable
- [ ] nixosTests.switch-test

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by zakame** [comment]
@GrahamcOfBorg build perl536
@GrahamcOfBorg build perl534
@GrahamcOfBorg build perldevel

**Review by zakame — APPROVED** [review]
`perl536` builds fine on my M1 👍

**Comment by stigtsp** [comment]
> `perl536` builds fine on my M1 +1

Thx for testing. On a sidenote, going to perl536 I'm hoping to be able to shim dependencies for Module::Build and friends for perl-cross builds with the new builtins::

**Comment by trofi** [comment]
(took me a few days to bisect) commit 20868cb2d07dffa645e736d676a1e8df3e082284 `perl: 5.34.1 -> 5.36.0` somehow broke `claws-mail` build on `staging` and `staging-next`:

```
$ nix build -f. -L claws-mail
...
claws-mail> In file included from perl_plugin.c:55:
claws-mail> perl_plugin.c: In function 'XS_ClawsMail_filter_init':
claws-mail> /nix/store/iiy452z89fpj7ky0i8fls6kh41k8qcg8-perl-5.36.0/lib/perl5/5.36.0/x86_64-linux-thread-multi/CORE/perl.h:760:25: error: expected expression before 'do'
claws-mail>   760 | #   define STMT_START   do
claws-mail>       |                         ^~
```

Might be some `#define` collision?

**Comment by stigtsp** [comment]
Found some issues Arch had with their perl-5.36.0 bump: 
- https://archlinux.org/todo/pelr-5360-rebuild/

Relevant for claws-mail:
- https://github.com/archlinux/svntogit-packages/blob/packages/claws-mail/trunk/20cope_with_fix_for_1009149.patch
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1009473

**Comment by trofi** [comment]
Ah, tricky! will give @ajs124 's fix a shot.

**Pull request merged**
