### PR TITLE
Manual: Fixed typo that casued a syntax error

### PR DESCRIPTION
**Pull request by AveryLychee**

### CODE REVIEW

**Comment by AveryGlitch** [comment]
Travis has failed this due to some other issue with a derivation called 'calamares-1.0', which (as far as I can see) has nothing to do with a typo correction for the docs.

**Comment by vcunat** [comment]
That evaluation problem is on master already, discussed on https://github.com/NixOS/nixpkgs/pull/11764#issuecomment-165381821.

**Comment by abbradar** [comment]
LGTM. A small nitpick: please squash commits into one.

**Comment by AveryGlitch** [comment]
The commits have been squashed.

**Comment by abbradar** [comment]
Thanks!

**Pull request merged**
