### PR TITLE
flightgear: 2019.1.1 -> 2020.1.3, simgear: 2020.1.{1 -> 3}

### LINKED ISSUE #91787: flightgear is broken
**Describe the bug**

Trying to build `flightgear` fails

**To Reproduce**

```
nix-repl> :b flightgear
builder for '/nix/store/163jmryxkxch5s9m4s8kgwzyps3wc084-flightgear-2019.1.1.drv' failed with exit code 2; last 10 log lines:
     67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
        |          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     68 |        __bos (__s), __fmt, __va_arg_pack ());
        |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  [ 23%] Built target fgviewer
  [ 25%] Linking CXX executable yasim-proptest
  [ 25%] Built target yasim-proptest
  [ 25%] Linking C static library libfgsqlite3.a
  [ 25%] Built target fgsqlite3
  make: *** [Makefile:183: all] Error 2
[2 built (1 failed), 315 copied (1454.3 MiB), 301.4 MiB DL]
error: build of '/nix/store/163jmryxkxch5s9m4s8kgwzyps3wc084-flightgear-2019.1.1.drv' failed
```

**Additional context**

Apparently it was already broken here: https://github.com/NixOS/nixpkgs/pull/88773

Maybe it makes sense to update to recently released version 2020.1.

**Notify maintainers**

@raskin

### PR DESCRIPTION
**Pull request by turion**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
Does this release support the new `openscenegraph` release?

https://github.com/NixOS/nixpkgs/pull/77799

**Comment by veprbl** [comment]
Flightgear would not build for me with this:
```
CMake Error at CMakeModules/Translations.cmake:38 (translation_dir_list):
  translation_dir_list Function invoked with incorrect arguments for function
  named: translation_dir_list
```

Let's ask ofborg to reproduce (might not work because of empty `meta.hydraPlatforms`):
@GrahamcOfBorg build flightgear

**Comment by turion** [comment]
I reverted the version to 2020.1.2, this seems to build. Best to have something working at all. We can bump the version further later.

**Pull request merged**
