### PR TITLE
libunwind: 1.1 -> 1.2.1

### PR DESCRIPTION
**Pull request by orivej**
###### Motivation for this change

libunwind 1.2.1 includes all patches for libunwind 1.1, except that `libunwind-1.1-lzma.patch` would have been relevant without `autoreconfHook`.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Tested compilation of some packages that depend on `libunwind`: `strace`, `julia`.

### CODE REVIEW

**Comment by vbgl** [comment]
This broke `julia_05`. Updating it to version `0.5.2` does not seem to help. Updating to version `0.6.0` seems non-trivial. Any idea?

**Comment by vcunat** [comment]
In the worst case, one can always bring back an old version privately for julia...

**Comment by vcunat** [comment]
That easy possibility is quite a distinct advantage of nix(pkgs) over standard distros...

**Comment by orivej** [comment]
It seems this is a bug in `libunwind` which is trivial to patch. Its `include/libunwind-common.h` contains
```
#define UNW_VERSION_MAJOR	1
#define UNW_VERSION_MINOR	2.1
#define UNW_VERSION_EXTRA	
```
I'll look into it.

**Pull request merged**
