### PR TITLE
nixos/prometheus: add new configuration options

### PR DESCRIPTION
**Pull request by yrd**
###### Motivation for this change
As mentioned in #141477, the new Prometheus versions has a few new configuration options that are not yet mirrored in the NixOS module. Judging by the [changelog](https://github.com/prometheus/prometheus/blob/main/CHANGELOG.md), at least the following new options are missing:

- Linode SD
- HTTP SD
- Kuma SD

Further, there are a bunch of (admittedly less-used) other options that are also not yet present.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by basvandijk** [comment]
@GrahamcOfBorg test prometheus

**Review by basvandijk — APPROVED** [review]
LGTM. Thank you!

**Comment by basvandijk** [comment]
@yrd can you turn the PR from draft to "ready for review"? Then I'll merge it in.

**Comment by basvandijk** [comment]
@yrd can you turn the PR from draft to "ready for review"? Then I'll merge it in.

**Comment by yrd** [comment]
@basvandijk Jeah, the new Prometheus version is required. There are still a few config options missing, I'll add the remaining ones and then undraft it.

**Comment by basvandijk** [comment]
> ... There are still a few config options missing, I'll add the remaining ones and then undraft it.

Sounds good. At some point we should probably rewrite the prometheus module to use [freeform options](https://nixos.org/manual/nixos/stable/index.html#sec-freeform-modules) rather than explicitly syncing every upstream option. But let's do that in some future PR...

**Comment by basvandijk** [comment]
@yrd just a heads-up that this PR and my https://github.com/NixOS/nixpkgs/pull/143147 will probably raise a minor git conflict which should be easy to resolve.

BTW would you be interested reviewing my PR?

**Comment by yrd** [comment]
> At some point we should probably rewrite the prometheus module to use [freeform options](https://nixos.org/manual/nixos/stable/index.html#sec-freeform-modules) rather than explicitly syncing every upstream option.

Personally, I quite like having a strictly typed set of options and wouldn't strip out the already defined stuff in favor of a generic freeform module. I had thought about somehow parsing the [upstream documentation](https://github.com/prometheus/prometheus/blob/main/docs/configuration/configuration.md) but it isn't all that machine-readable so that's probably not that good of an idea…

**Comment by yrd** [comment]
> will probably raise a minor git conflict

Hm... That might be the case yes^^ Which one should go first?

**Comment by basvandijk** [comment]
>  Which one should go first?

I don't really mind which one goes first but since yours is still blocked on https://github.com/NixOS/nixpkgs/pull/141477 I would suggest I merge mine first. I would be happy to help resolving those conflicts although I think they are minor.

**Comment by yrd** [comment]
Okay, sounds good! Then I'll try to get the other config options in by tomorrow or so, then this PR can follow.

**Comment by basvandijk** [comment]
@yrd https://github.com/NixOS/nixpkgs/pull/143147 is merged so you can go ahead and rebase on master.

**Comment by yrd** [comment]
@basvandijk Thanks! Based on your branch, I finished up the remaining service discovery options. That said, I *think* this should be mergeable now but it'd be nice if you could look through it again before squashing and merging. A few thoughts from myself:

- The descriptions are more or less copypasta from the upstream documentation and don't always follow consitent formatting
- There a bunch of descriptions that contain something like 'Must be one of xyz', which is redundant with the `enum` type
- Sometimes links are written as `<link>` tags, sometimes they are just inlined. Same goes for `<literal>` and backticks.

As already discussed, we are blocked by #141477. Further though, a quick search gives a few PRs that would be invalidated once this is through: #111682 #136672 #124588 #112207

**Review by basvandijk — APPROVED** [review]
Looks great!

I can confirm the manual, including the option documentation, builds using:
`nix-build nixos/release.nix -A manualHTML.x86_64-linux`
and looks OK. 

It would be nice of course to clean up those points you mentioned but it's certainly not a blocker for this PR.

**Comment by basvandijk** [comment]
@GrahamcOfBorg test prometheus

**Comment by basvandijk** [comment]
I've merged https://github.com/NixOS/nixpkgs/pull/141477 so merging this in now...

**Comment by yrd** [comment]
@basvandijk Thanks! There are a few options in now that are 2.31.0 only and won't work under 2.30, but I guess that won't be to big of a deal if the new version gets merged soon as well.

**Pull request merged**
