### PR TITLE
podman: remove wrapper

### PR DESCRIPTION
**Pull request by zowoq**
###### Description of changes

trying to get all of the podman functionality to work with the wrapper is becoming more complicated with each release, it isn't sustainable

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

___
```
bin
└── podman
lib
├── systemd
│   ├── system
│   │   ├── podman-auto-update.service
│   │   ├── podman-auto-update.timer
│   │   ├── podman-clean-transient.service
│   │   ├── podman-kube@.service
│   │   ├── podman-restart.service
│   │   ├── podman.service
│   │   └── podman.socket
│   ├── system-generators
│   │   └── podman-system-generator ⇒ ../../../libexec/podman/quadlet
│   ├── user ⇒ ../../share/systemd/user
│   └── user-generators
│       └── podman-user-generator ⇒ ../../../libexec/podman/quadlet
└── tmpfiles.d
    └── podman.conf
libexec
└── podman
    ├── quadlet
    └── rootlessport
share
├── bash-completion
│   └── completions
│       └── podman
│       └── podman-remote
├── fish
│   └── vendor_completions.d
│       ├── podman-remote.fish
│       └── podman.fish
├── systemd
│   └── user
│       ├── podman-auto-update.service
│       ├── podman-auto-update.timer
│       ├── podman-kube@.service
│       ├── podman-restart.service
│       ├── podman.service
│       └── podman.socket
└── zsh
    └── site-functions
        └── _podman
        └── _podman-remote
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Yay!

**Comment by michaeladler** [comment]
This seems to break podman's port-forwarding, e.g.

```
$ podman run --rm -it -p 1337:1337 alpine:latest /bin/sh 
Error: could not find "rootlessport" in one of [/usr/local/libexec/podman /usr/local/lib/podman /usr/libexec/podman /usr/lib/podman /nix/store/iccl4wdqvlcvgv7dqgszbk428fblw0zr-podman-helper-binary-wrapper/bin].  To resolve this error, set the helper_binaries_dir key in the `[engine]` section of containers.conf to the directory containing your helper binaries.
```

**Comment by zowoq** [comment]
Thought I'd checked that but seems not, I'll look at adding a test for it so doesn't regress again.

Should be easy enough to fix but I don't want to break something else rushing though a fix so I'll revert it for now.

https://github.com/NixOS/nixpkgs/pull/216769

**Comment by zowoq** [comment]
Adding a test for rootlessport in https://github.com/NixOS/nixpkgs/pull/216945.

I have a fix for it but might have a couple of other tweaks to make so I'll leave trying the wrapper for another PR.

**Comment by zowoq** [comment]
Second attempt at removing the wrapper: https://github.com/NixOS/nixpkgs/pull/218355

**Pull request merged**
