### PR TITLE
Add a NixOS module for Prometheus

### PR DESCRIPTION
**Pull request by benley**
It's a start. Is this too elaborate?

### CODE REVIEW

**Comment by lethalman** [comment]
Yes. Just let people write their own yaml. Remove all those options that are "nullOr", if an option is not mandatory, it's not worth making it a nixos option... rather let people write that directly in yaml or whatever else.

Only add mandatory config as nixos option, simplify all that stuff please.

**Comment by joachifm** [comment]
@benley are you still working on this?

**Comment by benley** [comment]
no - in fact I thought someone else had already taken this on and written a simpler prometheus module.  I could still finish this at some point if nobody else has done it.

**Comment by joachifm** [comment]
Closing, seems little value in keeping it open if nobody's working on it.

**Comment by teh** [comment]
Hey, I'd like to re-open this.

@lethalman This isn't actually as elaborate as it seems - it's a nixos-module typing for the yaml format. There's precedent for this style, e.g. jenkins job builder, gitlab, kibana, kubernetes, influx, uswgi, and some others, didn't investigate deeply.

IMO this is good to include after some more testing. @lethalman, @joachifm any objections to me reviving this work?

**Comment by fpletz** [comment]
We've been using this module for months now with only small modifications, mainly fixing the conflicts and an option was renamed in a newer prometheus version. I can open a new pull request if desired.

**Comment by teh** [comment]
@fpletz please do! I just fixed the merge conflicts and was going to tackle the renamed option.

**Comment by teh** [comment]
See https://github.com/NixOS/nixpkgs/pull/18298

Sorry @fpletz - let me know if you have any additional changes on top of this!

**Comment by benley** [comment]
Awesome, I didn't realize people were actually using this code.  If it is working well for you I'm all in favor of merging it, especially if we'll have multiple maintainers.

**Comment by benley** [comment]
Let's close this PR in favor of #18298

**Pull request closed without merging**
