### PR TITLE
gitlab: fix smtp setting

### LINKED ISSUE #50163: gitlab startup errors since eadb998
## Issue description

I believe commit eadb9985819327f6bce7da87730d32e5018ee848 broke gitlab startup.

On [this line](https://github.com/NixOS/nixpkgs/commit/eadb9985819327f6bce7da87730d32e5018ee848#diff-a8187202c46aeec728e5b8818fdce3c8L569), the pre-start script attempts to link an smtp settings file into the 'initializers' subdirectory of '/var/gitlab/state/config/', but at the time the target directory doesn't exist so this errors.

Before eadb9985819327f6bce7da87730d32e5018ee848, [this line](https://github.com/NixOS/nixpkgs/commit/eadb9985819327f6bce7da87730d32e5018ee848#diff-a8187202c46aeec728e5b8818fdce3c8R571) would have created the 'initializers' directory, but it now happens too late.

I can make a PR that simply adds a 'mkdir' to make it work, if that's the right solution.

### Steps to reproduce

Enable the gitlab service in nixos, set `services.gitlab.smtp.enable` to `true`, and try to start gitlab.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.79, NixOS, 18.09.1228.a4c4cbb613c (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(catherine): `"nixpkgs-18.09.810.59fe4c7f17a"`
 - channels(root): `""`
 - nixpkgs: `/home/catherine/.nix-defexpr/channels/nixpkgs`

### PR DESCRIPTION
**Pull request by globin**
fixes #50163

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - N/A macOS
   - N/A other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- N/A Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- N/A Tested execution of all binary files (usually in `./result/bin/`)
- N/A Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @lheckemann @flokli @krav @fpletz

### CODE REVIEW

**Comment by Infinisil** [comment]
@GrahamcOfBorg test gitlab

**Review by flokli — APPROVED** [review]

**Comment by flokli** [comment]
@lheckemann can you backport to 18.09 as well?

**Comment by lheckemann** [comment]
9bf8b0d06b7

**Comment by flokli** [comment]
Thanks!

**Pull request merged**
