### PR TITLE
cataclysm-dda: 0.E-3 -> 0.F, cataclysm-dda-git: 2020-12-09 -> 2021-07-03

### PR DESCRIPTION
**Pull request by DeeUnderscore**
###### Motivation for this change
https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/0.F

Makefile now installs a .desktop file, so we can get rid of the script we had for that. 

Parallel builds seem to work for me locally, now, so I re-enabled them.

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Note that this might break cataclysm-dda-git, but at this point it's behind the stable release, so it could just be aliased to 0.F for now.

### CODE REVIEW

**Comment by DeeUnderscore** [comment]
It looks like x86_64-darwin is failing because it can't figure out `OSX_MIN`, but I'm not quite sure what that would that should be set to, or how else to fix it.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 129150` at 03842a87 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/c11377ac4224c5aada3949d1b9336ba6">cataclysm-dda-git</a></li>
  </ul>
</details>
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>cataclysm-dda</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by DeeUnderscore** [comment]
I've gone ahead and bumped cataclysm-dda-git, too, so it isn't broken (it's master, a bit ahead of 0.F)

**Comment by SuperSandro2000** [comment]
> It looks like x86_64-darwin is failing because it can't figure out `OSX_MIN`, but I'm not quite sure what that would that should be set to, or how else to fix it.

The version of our apple_sdk I think. https://github.com/NixOS/nixpkgs/blob/7eaa130f54d3f90dc287db7063da61afafbb6b24/pkgs/os-specific/darwin/apple-sdk-11.0/default.nix#L7

**Comment by mnacamura** [comment]
Adding `OSX_MIN=10.4` to make flag works fine for me on darwin. Alternatively use `darwin.apple_sdk_11_0` instead?

**Comment by DeeUnderscore** [comment]
I've set `OSX_MIN` to `stdenv.targetPlatform.darwinMinVersion`. Upstream Makefile will default to 10.9 at the highest, and `darwinMinVersion` is higher than that, so I assume it's safe.

**Review by mnacamura — APPROVED** [review]

**Pull request merged**
