### PR TITLE
lmms: Add support for Carla

### PR DESCRIPTION
**Pull request by Rampoina**
Add Carla as an optional dependency and the needed patch.
This adds the Carla rack and Carla instrument LMMS plugins.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by orivej** [comment]
Here is the upstream issue: https://github.com/LMMS/lmms/issues/6395
And here is the corresponding patch: https://github.com/LMMS/lmms/pull/6403
Could you apply it with `fetchfatch`? (https://github.com/LMMS/lmms/commit/3518d307f47c79db06bd0e9430f39b91488673dc.patch)
Fixes the `sed` are difficult to maintain, it is hard to know when they become obsolete.

**Comment by Rampoina** [comment]
@orivej thanks for the suggestion, I'll work on that this friday

**Comment by Rampoina** [comment]
> Here is the upstream issue: [LMMS/lmms#6395](https://github.com/LMMS/lmms/issues/6395) And here is the corresponding patch: [LMMS/lmms#6403](https://github.com/LMMS/lmms/pull/6403) Could you apply it with `fetchfatch`? (https://github.com/LMMS/lmms/commit/3518d307f47c79db06bd0e9430f39b91488673dc.patch) Fixes with `sed` are difficult to maintain, it is hard to know when they become obsolete.

@orivej It looks like the files plugins/carlabase/carla.h were renamed to camelcase at some point so the patch doesn't apply. 

Even if we change the names it still doesn't apply because of this [line](https://github.com/PhysSong/lmms/blob/9c49a7747c38ac0a3dd1c21d30019a830155d500/plugins/CarlaBase/Carla.h#L3) (and others) which comes from [this](https://github.com/LMMS/lmms/pull/5846) feature

[This](https://github.com/archlinux/svntogit-community/blob/packages/lmms/trunk/lmms-carla-export.patch) patch from Arch Linux  would apply or we could also include it ourselves.
How do you suggest to proceed?

**Comment by orivej** [comment]
Good idea! However, the link https://raw.githubusercontent.com/archlinux/svntogit-community/packages/lmms/trunk/lmms-carla-export.patch will expire as soon as ArchLinux deletes that patch (probably when they update lmms). To keep the link working we refer to patches on github by their tags or hashes rather than by their branch names (in this case the branch name is `packages/lmms`). To obtain a stable link you can open https://github.com/archlinux/svntogit-community/blob/packages/lmms/trunk/lmms-carla-export.patch , press `y` on the keyboard (or click … near "Go to file", choose "Copy permalink", and visit the copied link), and then click "Raw" and copy the link from the browser url bar. In this case the result is https://raw.githubusercontent.com/archlinux/svntogit-community/cf64acc45e3264c6923885867e2dbf8b7586a36b/trunk/lmms-carla-export.patch

**Review by orivej — APPROVED** [review]

**Pull request merged**
