### PR TITLE
virtualbox:  fix pulseaudio device access: #24259

### PR DESCRIPTION
**Pull request by deepfire**
###### Motivation for this change
Fix https://github.com/NixOS/nixpkgs/issues/24259

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by deepfire** [comment]
The failure is `no space left on device`:
```

kmk_builtin_append: failed to fclose '/run/user/1000/nix-build-virtualbox-5.1.18.drv-2/VirtualBox-5.1.18/out/linux.amd64/release/obj/VBoxOGLhostcrstate/state_tracker/state_multisample.o.dep'!: No space left on device
kmk: *** [/run/user/1000/nix-build-virtualbox-5.1.18.drv-2/VirtualBox-5.1.18/out/linux.amd64/release/obj/VBoxOGLhostcrstate/state_tracker/state_multisample.o] Error 1
kmk: *** Deleting file `/run/user/1000/nix-build-virtualbox-5.1.18.drv-2/VirtualBox-5.1.18/out/linux.amd64/release/obj/VBoxOGLhostcrstate/state_tracker/state_multisample.o'
kmk: *** Waiting for unfinished jobs....
{standard input}: Assembler messages:
{standard input}: Fatal error: can't write 121 bytes to section .rodata.str1.8 of /run/user/1000/nix-build-virtualbox-5.1.18.drv-1/VirtualBox-5.1.18/out/linux.amd64/release/obj/VBoxOGLhostcrstate/state_tracker/state_lists.o because: 'No space left on device
```

**Comment by deepfire** [comment]
The build succeeds locally, on my machine, and indeed I'm using the resultant VirtualBox.

However, on Travis this build blows the 2G disk space limit: https://travis-ci.org/NixOS/nixpkgs/jobs/215361318#L879
```
878  /nix/store/ya481hkpjrnbwjrz8rrcn6yzd4ihc1bl-virtualbox-modules-5.1.18-3.10.105.drv
879  these paths will be fetched (676.97 MiB download, 1569.67 MiB unpacked):
```
...then, https://travis-ci.org/NixOS/nixpkgs/jobs/215361318#L2283:
```
2283  unpacking source archive /nix/store/0llwyj0qia7xj2k9qhw9n9dh6bbwjiid-linux-4.9.18.tar.xz
2284  source root is linux-4.9.18
2285  tar: linux-4.9.18/drivers/gpu/drm/amd/include/asic_reg/gca/gfx_8_1_sh_mask.h: Wrote only 7680 of 10240 bytes
2286  tar: linux-4.10.6/include/net/regulatory.h: Wrote only 1536 of 7801 bytes
2287  tar: linux-4.10.6/include/net/request_sock.h: Cannot write: No space left on device
```

I have no idea how much the disk limit ought to be raised to fix this.

One question is -- can this disk space limit be raised on a per-PR basis, or not?  Raising this globally would be problematic, since @grahamc rightfully pointed out on IRC that Travis isn't in business to allow huge builds to happen.

**Comment by abbradar** [comment]
Tested locally. Thanks for your work!

**Comment by deepfire** [comment]
@abbradar, thanks!

**Comment by grahamc** [comment]
Kosyrev Serge <notifications@github.com> writes:

> One question is -- can this disk space limit be raised on a per-PR
> basis, or not?

Unfortunately not, they don't offer any flexibility here.

Graham

**Pull request merged**
