### PR TITLE
rfkill: remove

### PR DESCRIPTION
**Pull request by deviant**
###### Motivation for this change

rfkill was subsumed by util-linux in 2017 [[1]], and the upstream has not
been updated in over 5 years [[2]]. This package shadows the rfkill from
util-linux, so it can be completely removed with no breaking changes,
because util-linux is in the base package set in nixos/system-path.

[1]: https://github.com/karelzak/util-linux/commit/d17fb726b562a69e8f174d46fa6cf794abc129cd
[2]: https://git.sipsolutions.net/rfkill.git/log/

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
Eval failed because we require that any in-tree packages can't reference the aliases, they must refer to the actual package (`utillinux`).

**Comment by deviant** [comment]
@veprbl blueberry was added very recently, I've been sitting on this patch for months and the new addition slipped past me. Will fix it later :-)

**Comment by deviant** [comment]
@veprbl Should be fixed now.

**Review by romildo — APPROVED** [review]
LGTM

**Pull request merged**
