### PR TITLE
mesa: 21.1.3 -> 21.1.4

### PR DESCRIPTION
**Pull request by primeos**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by primeos** [comment]
@ofborg test sway

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 128873` at e23145b6 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>16 packages marked as broken and skipped:</summary>
  <ul>
    <li>asymptote</li>
    <li>electron_3</li>
    <li>electron_4</li>
    <li>electron_5</li>
    <li>exodus</li>
    <li>forge</li>
    <li>gtkd</li>
    <li>plover.stable</li>
    <li>qemu_xen</li>
    <li>qemu_xen-light</li>
    <li>qemu_xen_4_10</li>
    <li>qemu_xen_4_10-light</li>
    <li>rocm-opencl-icd</li>
    <li>rocm-opencl-runtime</li>
    <li>spotifywm</li>
    <li>tilix</li>
  </ul>
</details>
<details>
  <summary>705 packages skipped due to time constraints:</summary>
  <ul>
    <li>adapta-gtk-theme</li>
    <li>akira-unstable</li>
    <li>almanah</li>
    <li>alpine-make-vm-image</li>
    <li>alttab</li>
    <li>anbox</li>
    <li>anki</li>
    <li>ankisyncd</li>
    <li>apostrophe</li>
    <li>aqemu</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>89 packages built successfully:</summary>
  <ul>
    <li>amtk</li>
    <li>appgate-sdp</li>
    <li>avocode</li>
    <li>bamf</li>
    <li>blur-effect</li>
    <li>cage</li>
    <li>cardboard</li>
    <li>clutter (gnome.clutter)</li>
    <li>clutter-gst (gnome.clutter-gst)</li>
    <li>clutter-gtk (gnome.clutter-gtk)</li>
    <li>cogl (gnome.cogl)</li>
    <li>dwl</li>
    <li>egl-wayland</li>
    <li>electron (electron_13)</li>
    <li>electron_10</li>
    <li>electron_11</li>
    <li>electron_12</li>
    <li>electron_6</li>
    <li>electron_7</li>
    <li>electron_8</li>
    <li>electron_9</li>
    <li>fbida</li>
    <li>fgallery</li>
    <li>gjs (gnome.gjs)</li>
    <li>gnome.gdm</li>
    <li>gnome.gnome-clocks</li>
    <li>gtksourceview (gnome.gtksourceview ,gtksourceview3 ,xfce.gtksourceview)</li>
    <li>gtksourceview4 (gnome.gtksourceview4)</li>
    <li>libdazzle (gnome.libdazzle)</li>
    <li>i3</li>
    <li>libhandy</li>
    <li>libretro.freeintv</li>
    <li>libretro.o2em</li>
    <li>libretro.prosystem</li>
    <li>libretro.sameboy</li>
    <li>libretro.vecx</li>
    <li>mesa</li>
    <li>nix-tour</li>
    <li>pantheon.elementary-dock</li>
    <li>pantheon.switchboard</li>
    <li>pantheon.switchboard-plug-about</li>
    <li>pantheon.switchboard-plug-applications</li>
    <li>pantheon.switchboard-plug-bluetooth</li>
    <li>pantheon.switchboard-plug-datetime</li>
    <li>pantheon.switchboard-plug-display</li>
    <li>pantheon.switchboard-plug-keyboard</li>
    <li>pantheon.switchboard-plug-mouse-touchpad</li>
    <li>pantheon.switchboard-plug-network</li>
    <li>pantheon.switchboard-plug-notifications</li>
    <li>pantheon.switchboard-plug-power</li>
    <li>pantheon.switchboard-plug-printers</li>
    <li>pantheon.switchboard-plug-security-privacy</li>
    <li>pantheon.switchboard-plug-sharing</li>
    <li>pantheon.switchboard-plug-sound</li>
    <li>python38Packages.ewmh</li>
    <li>python38Packages.i3ipc</li>
    <li>python38Packages.skytemple-ssb-debugger</li>
    <li>python38Packages.xlib</li>
    <li>python38Packages.xvfbwrapper</li>
    <li>python39Packages.i3ipc</li>
    <li>python39Packages.pyside</li>
    <li>python39Packages.pysideTools</li>
    <li>python39Packages.xlib</li>
    <li>python39Packages.xvfbwrapper</li>
    <li>retroarch</li>
    <li>retroarchBare</li>
    <li>selinux-sandbox</li>
    <li>stretchly</li>
    <li>sysprof</li>
    <li>teleprompter</li>
    <li>tinywl</li>
    <li>uivonim</li>
    <li>vieb</li>
    <li>virglrenderer</li>
    <li>vscode</li>
    <li>vscode-with-extensions</li>
    <li>waybox</li>
    <li>wbg</li>
    <li>wio</li>
    <li>wlroots</li>
    <li>xf86_input_wacom</li>
    <li>xorg.xf86inputevdev</li>
    <li>xorg.xf86inputlibinput</li>
    <li>xorg.xf86inputsynaptics</li>
    <li>xorg.xf86videodummy</li>
    <li>xorg.xinit</li>
    <li>xorg.xorgserver</li>
    <li>xvfb-run</li>
    <li>xwayland</li>
  </ul>
</details>

**Comment by primeos** [comment]
Apparently `tests.sway on aarch64-linux` failed during the `glinfo` test. This is a bit strange but hopefully not reproducible or at least not related to this PR. Unfortunately I lack a good AArch64 setup to reproduce it locally but given that the `x86_64` test succeeded it's hopefully fine.

**Comment by vcunat** [comment]
I retried the test a few times on `vcunat@aarch64.nixos.community`, and it is running into problems, but they seem the same on the commit just before this merge as well.

**Comment by vcunat** [comment]
Well, the whole sway tests seems weird to me.  Even on master x86_64 you have a coredump though [the test](https://hydra.nixos.org/build/146827295) "succeeds"
```
machine: must succeed: su - alice -c 'swaymsg exit || true'
machine # [   83.392086] su[1214]: Successful su for alice by root
machine # [   83.398254] su[1214]: pam_unix(su:session): session opened for user alice(uid=1000) by (uid=0)
machine # [   83.621565] show_signal_msg: 97 callbacks suppressed
machine # [   83.621568] sway[938]: segfault at 3f800008 ip 00007f2b572aaf10 sp 00007fffa057f378 error 4 in libwayland-server.so.0.1.0[7f2b572a4000+8000]
machine # [   83.625410] Code: 48 83 c3 08 49 39 dd 77 d1 b8 01 00 00 00 48 83 c4 08 5b 5d 41 5c 41 5d c3 90 48 89 3f 48 89 7f 08 c3 0f 1f 84 00 00 00 00 00 <48> 8b 47 08 48 89 3e 48 89 46 08 48 89 77 08 48 8b 46 08 48 89 30
machine # [   83.527180] systemd[1]: Created slice system-systemd\x2dcoredump.slice.
machine # [   83.532951] systemd[1]: Started Process Core Dump (PID 1219/UID 0).
machine # [   84.019080] systemd-coredump[1220]: Process 938 (sway) of user 1000 dumped core.
machine # 00:00:00.604 [common/ipc-client.c:87] Unable to receive IPC response
```

**Comment by primeos** [comment]
~~@vcunat thanks for looking into that. I forgot to look before `machine: waiting for alice@machine to appear on screen` when I reviewed the CI log for the first time and just noticed that there's also a kernel warning/trace:~~

```
machine # [   26.546909] ------------[ cut here ]------------
machine # [   26.548354] WARNING: CPU: 0 PID: 951 at kernel/dma/mapping.c:188 dma_map_sg_attrs+0x44/0x60
machine # [   26.550186] Modules linked in: crct10dif_ce joydev mousedev virtio_gpu virtio_dma_buf drm_kms_helper ip6table_nat uio_pdrv_genirq uio qemu_fw_cfg iptable_nat nf_nat xt_conntrack nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c ip6t_rpfilter ipt_rpfilter ip6table_raw iptable_raw xt_pkttype nf_log_ipv6 nf_log_ipv4 nf_log_common xt_LOG xt_tcpudp cfg80211 rfkill 8021q garp mrp ip6table_filter ip6_tables sch_fq_codel iptable_filter tap macvlan bridge drm stp llc fuse ip_tables x_tables overlay dm_mod virtio_rng rng_core
machine # [   26.560555] CPU: 0 PID: 951 Comm: sway Not tainted 5.10.45 #1-NixOS
machine # [   26.561887] Hardware name: linux,dummy-virt (DT)
machine # [   26.562888] pstate: 80000005 (Nzcv daif -PAN -UAO -TCO BTYPE=--)
machine # [   26.564238] pc : dma_map_sg_attrs+0x44/0x60
machine # [   26.565190] lr : drm_gem_map_dma_buf+0x60/0xd8 [drm]
machine # [   26.566284] sp : ffff80001047bb70
machine # [   26.567010] x29: ffff80001047bb70 x28: ffff80001047bd78
machine # [   26.568211] x27: 000000000000000c x26: ffff7395c219b200
machine # [   26.569367] x25: ffff7395c9163dd8 x24: 00000000c2369000
machine # [   26.570511] x23: ffff7395c219b328 x22: ffff7395d1e58980
machine # [   26.571682] x21: 0000000000000000 x20: ffff7395d1e58980
machine # [   26.572829] x19: ffff7395d1e58780 x18: 0000000000000000
machine # [   26.573971] x17: 0000000000000000 x16: ffffb0786f3433e8
machine # [   26.575131] x15: ffffffce55e00000 x14: 0000000000176000
machine # [   26.576297] x13: 0000000000000000 x12: 000000000000001a
machine # [   26.577465] x11: 0000000000000189 x10: 000000000000001a
machine # [   26.578637] x9 : ffffb0785a90dd18 x8 : ffff7395cb78eb40
machine # [   26.579826] x7 : 0000000000177000 x6 : 0000000000000000
machine # [   26.580978] x5 : ffffffce57310000 x4 : 0000000000000020
machine # [   26.582156] x3 : 0000000000000000 x2 : 000000000000001a
machine # [   26.583327] x1 : ffff7395cb78e800 x0 : ffff7395c3a44410
machine # [   26.584517] Call trace:
machine # [   26.585067]  dma_map_sg_attrs+0x44/0x60
machine # [   26.585920]  dma_buf_map_attachment+0x9c/0x110
machine # [   26.586941]  drm_gem_prime_import_dev+0xec/0x1b0 [drm]
machine # [   26.588142]  drm_gem_prime_import+0x1c/0x28 [drm]
machine # [   26.589198]  virtgpu_gem_prime_import+0x34/0xa8 [virtio_gpu]
machine # [   26.590463]  drm_gem_prime_fd_to_handle+0xd4/0x228 [drm]
machine # [   26.591665]  drm_prime_fd_to_handle_ioctl+0x30/0x48 [drm]
machine # [   26.592898]  drm_ioctl_kernel+0xc8/0x118 [drm]
machine # [   26.593918]  drm_ioctl+0x224/0x480 [drm]
machine # [   26.594811]  __arm64_sys_ioctl+0xb0/0xf8
machine # [   26.595710]  el0_svc_common.constprop.0+0x80/0x1a8
machine # [   26.596757]  do_el0_svc+0x2c/0x98
machine # [   26.597483]  el0_svc+0x20/0x30
machine # [   26.598159]  el0_sync_handler+0xb0/0xb8
machine # [   26.599009]  el0_sync+0x180/0x1c0
machine # [   26.599753] ---[ end trace d51dfe505360de37 ]---
```

~~I suppose that could be the cause (drm+virtgpu). I'm not sure why `waiting for alice@machine to appear on screen` succeeds but maybe it's some very strange visual glitch or it somehow shows the Linux virtual console again without Sway crashing.~~

Nvm, I just noticed that this already happens on `nixos-unstable` where the test still succeeds: https://hydra.nixos.org/build/146827636

Ideally this only affects the VM test which already has to use `-vga none -device virtio-gpu-pci` for QEMU and `WLR_RENDERER_ALLOW_SOFTWARE=1` for wlroots (and even then it only barely works as you've already noticed with the segfault).

I hope that I can have a closer look at that soon but currently I do unfortunately lack the time for it.

**Pull request merged**
