### PR TITLE
xflux-gui: 2016-09-21 -> 1.1.10

### PR DESCRIPTION
**Pull request by aske**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Do I need a service/desktop environment to use fluxgui?

```console
$ /nix/store/ydagh41zyqadj1idch4vhhn7kqfnyjcm-xflux-gui-1.1.10/bin/fluxgui
Failed to contact configuration server; the most common cause is a missing or misconfigured D-Bus session bus daemon. See http://projects.gnome.org/gconf/ for information. (Details -  1: GetIOR failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.GConf was not provided by any .service files)
Critical error. Exiting.
Traceback (most recent call last):
  File "/nix/store/ydagh41zyqadj1idch4vhhn7kqfnyjcm-xflux-gui-1.1.10/bin/...fluxgui-wrapped-wrapped-wrapped", line 22, in <module>
    main()
  File "/nix/store/ydagh41zyqadj1idch4vhhn7kqfnyjcm-xflux-gui-1.1.10/lib/python2.7/site-packages/fluxgui/fluxapp.py", line 213, in main
    try:
  File "/nix/store/ydagh41zyqadj1idch4vhhn7kqfnyjcm-xflux-gui-1.1.10/lib/python2.7/site-packages/fluxgui/fluxapp.py", line 28, in __init__
    print "Critical error. Exiting."
  File "/nix/store/ydagh41zyqadj1idch4vhhn7kqfnyjcm-xflux-gui-1.1.10/lib/python2.7/site-packages/fluxgui/fluxapp.py", line 43, in exit
    try:
AttributeError: 'FluxGUI' object has no attribute 'xflux_controller'
Exception AttributeError: AttributeError("'FluxGUI' object has no attribute 'xflux_controller'",) in <bound method FluxGUI.__del__ of <fluxgui.fluxapp.FluxGUI object at 0x7fde31009990>> ignored
```

**Comment by joachifm** [comment]
cc maintainer @sheenobu

**Comment by sheenobu** [comment]
I don't think you need a desktop environment for this. The error looks unrelated but I'm checking it out now.

**Comment by sheenobu** [comment]
@Mic92 yes you'll need gconf and *maybe* dbus to run the fluxgui. Not the full gnome environment, though.

This part:
```
Traceback (most recent call last):
  File "/nix/store/ydagh41zyqadj1idch4vhhn7kqfnyjcm-xflux-gui-1.1.10/bin/...fluxgui-wrapped-wrapped-wrapped", line 22, in <module>
    main()
  File "/nix/store/ydagh41zyqadj1idch4vhhn7kqfnyjcm-xflux-gui-1.1.10/lib/python2.7/site-packages/fluxgui/fluxapp.py", line 213, in main
    try:
  File "/nix/store/ydagh41zyqadj1idch4vhhn7kqfnyjcm-xflux-gui-1.1.10/lib/python2.7/site-packages/fluxgui/fluxapp.py", line 28, in __init__
    print "Critical error. Exiting."
  File "/nix/store/ydagh41zyqadj1idch4vhhn7kqfnyjcm-xflux-gui-1.1.10/lib/python2.7/site-packages/fluxgui/fluxapp.py", line 43, in exit
    try:
AttributeError: 'FluxGUI' object has no attribute 'xflux_controller'
Exception AttributeError: AttributeError("'FluxGUI' object has no attribute 'xflux_controller'",) in <bound method FluxGUI.__del__ of <fluxgui.fluxapp.FluxGUI object at 0x7fde31009990>> ignored
```

is just bad cleanup code in the fluxgui code.

**Comment by orivej** [comment]
Thanks! You shouldn't replace `pythonPackages` with `python2Packages` in derivations. If you want to be explicit, set `pythonPackages = python2Packages` in `all-packages.nix`, although there is no need for that.

**Pull request merged**
