### PR TITLE
r-modules: regenerate cran packages

### PR DESCRIPTION
**Pull request by michelk**

### CODE REVIEW

**Comment by michelk** [comment]
See [mailiing list question](http://article.gmane.org/gmane.linux.distributions.nixos/17298) on README.

**Comment by peti** [comment]
The problem I see with the README here is that it duplicates information from the Wiki, which means that the Wiki and the README will almost certainly diverge, eventually. Also, we already have documentation in the `doc/` directory and it feels odd to open up yet another spot for documentation in addition to that.

**Comment by michelk** [comment]
As I said in the email, I'm not really happy with the Wiki: (a) only online available, (b) sparse editor support, (c) mediawiki markup, (d) no git comfort, (e) no github comfort.

I would love to see documentation either in `README.md`s like it's done for example in the contrib area of [spacemacs](https://github.com/syl20bnr/spacemacs/tree/master/contrib) or an approach similar to [haskelldocumentation](https://github.com/commercialhaskell/haskelldocumentation).

**Comment by peti** [comment]
The Wiki is a kludge. This kind of  documentation doesn't belong there, really, it belongs into the Nixpkgs manual found in the doc directory of this very repository.

**Comment by michelk** [comment]
I guess `README.md`s could be easily spliced into the `doc`-xml hierarchy  with `pandoc`.

**Comment by peti** [comment]
I guess they could! If we had that feature implemented, then splitting the information into several README files like this would be feasible.

**Comment by michelk** [comment]
Closing in favor of 29779ae6425e2e6d5f4cbe0671243b6b85e853b4, although the documentation issue is still open. I may create another PR for that.

**Pull request closed without merging**
