### PR TITLE
neovim: Allow passing packages to add to PATH

### PR DESCRIPTION
**Pull request by Jomik**
###### Motivation for this change
I need to add packages to my path that some of my vim plugins use.
The only way to do this is overriding the unwrapped neovim, and then adding them to the path there, but then I have to rebuild neovim, which is not optimal, especially since we have a wrapper.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Maybe we should (also/instead) add a `makeWrappArgs` parameter?

**Comment by Jomik** [comment]
> Maybe we should (also/instead) add a `makeWrapperArgs` parameter?
That seems like a good idea, tbh, since this expression is a _wrapper_, it makes sense that you can add more args to it. 👍

**Comment by teto** [comment]
doing so you wouldn't need `extraPackages` anymore as you could just `--prefix PATH`. Could you update the PR ?

**Comment by Jomik** [comment]
@teto Done :+1:

**Review by teto — APPROVED** [review]

**Comment by teto** [comment]
thanks

**Pull request merged**
