### PR TITLE
xen: patch with XSA-464

### PR DESCRIPTION
**Pull request by hehongbo**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by hehongbo** [comment]
464 is easy to get in without problems but we still have to pull 463 in, as our builder is searching for `https://xenbits.xen.org/xsa/xsa${id}.patch` but `xsa463.patch` does not exist that way.

See https://xenbits.xen.org/xsa/advisory-463.html

**Review by SigmaSquadron — APPROVED** [review]

**Comment by SigmaSquadron** [comment]
i'll deal with 463

**Comment by emilazy** [comment]
Sorry, maybe should have merged this while waiting on 463.

**Comment by emilazy** [comment]
@SigmaSquadron Can we make the XSA fetching stuff more normal? It’s one thing to get bikeshedded into all those bells and whistles when they don’t harm anyone, but in this case the mismatch between the expectations of the fancy stuff and the reality of how the patches were released has actively impeded deploying a security patch. (Though apparently the series might not apply cleanly anyway…)

**Comment by SigmaSquadron** [comment]
I briefly discussed that concern with Alyssa a while back. Personally I'm okay with just a normal, in-line `fetchpatch`. It's not like there are too many XSAs applied at any one time anyway.

**Comment by SigmaSquadron** [comment]
Also, I was meaning to drop Qubes' build reproducibility patches. They don't work as expected.

**Comment by emilazy** [comment]
Even just `fetchurl` should be okay, since they’re released canonically as patch files rather than that being a generated forge thing that could change format. (A point Alyssa has made to me.)

**Pull request merged**
