### PR TITLE
nixos/display-managers: add renamed option missed in #291913

### PR DESCRIPTION
**Pull request by SuperSandro2000**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by philiptaron — APPROVED** [review]
I love to see it. Thanks for the quick turnaround.

I don't believe the ofBorg eval failure is related.

**Review by Shawn8901 — APPROVED** [review]

**Comment by cole-h** [comment]
You'll want to rebase on the latest `master` -- there was an issue that broke ofborg's ability to evaluate Nixpkgs that has since been resolved. Sorry for the inconvenience!

**Review by philiptaron — APPROVED** [review]
Here's the list of options under `services.xserver.displayManager` on `release-23.11`: 
[release-23.11-services.xserver.displayManager.txt](https://github.com/NixOS/nixpkgs/files/14937458/release-23.11-services.xserver.displayManager.txt)

Here's the list on master (prior to this PR): [master-services.xserver.displayManager.txt](https://github.com/NixOS/nixpkgs/files/14937462/master-services.xserver.displayManager.txt)

Diff:

```diff
 defaultSession
 desktopManagerHandlesLidAndPower
 extraSessionFilesPackages
 gdm
-hiddenUsers
 importedVariables
 job
 lightdm
 logToJournal
 sddm
 session
 sessionCommands
-sessionData
-sessionPackages
 setupCommands
 slim
 startx
 sx
```

This suggests that `hiddenUsers` is also needs this same treatment.

**Comment by philiptaron** [comment]
I meant to request changes there, dang it.

**Comment by SuperSandro2000** [comment]
good catch @philiptaron 👍🏼

**Review by philiptaron — APPROVED** [review]
# ✅
Someday, I'll add detection like this to nixpkgs-check-by-name.

**Pull request merged**
