### PR TITLE
unrar: 6.2.12 -> 7.0.7

### LINKED ISSUE #279409: Update request: unrar  6.2.12→  7.00 beta 3
-     Package name: unrar 
-     Latest released version: 7.00 beta 3
-     Current version on the unstable channel: 6.2.12
-     Current version on the stable/release channel: 6.2.12

I receive more and more RAR files which are created with Unrar 7.00 beta versions / require a more recent version tan 6.2.12 
I would appreciated if  the existing unrar package can be updated or a new unrar-beta package be proposed .. 

Changelog : https://www.rarlab.com/rarnew.htm

Notify maintainers
@ehmry 
@wegank

### PR DESCRIPTION
**Pull request by wegank**
## Description of changes

Now official: https://www.rarlab.com/rarnew.htm https://www.rarlab.com/rar_add.htm

At the same time, add an `unrar_6` for `rar2fs`.

Closes #279409.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 292396` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>python311Packages.unrardll</li>
    <li>python311Packages.unrardll.dist</li>
    <li>python312Packages.unrardll</li>
    <li>python312Packages.unrardll.dist</li>
    <li>rarcrack</li>
    <li>sabnzbd</li>
    <li>unrar</li>
    <li>unrar.dev</li>
    <li>unrar_6</li>
    <li>unrar_6.dev</li>
  </ul>
</details>

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 292396` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>python311Packages.unrardll</li>
    <li>python311Packages.unrardll.dist</li>
    <li>python312Packages.unrardll</li>
    <li>python312Packages.unrardll.dist</li>
    <li>rarcrack</li>
    <li>unrar</li>
    <li>unrar.dev</li>
    <li>unrar_6</li>
    <li>unrar_6.dev</li>
  </ul>
</details>

**Comment by lolbinarycat** [comment]
this is a major versioned release of a somewhat common command, are there any breaking changes to the cli or just the library?

maybe this deserves an entry in the release notes?

**Comment by wegank** [comment]
> this is a major versioned release of a somewhat common command, are there any breaking changes to the cli or just the library?

I'm not aware of any breaking changes, except for the source-code integration, which rar2fs does.

> maybe this deserves an entry in the release notes?

Done.

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 292396` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>python311Packages.unrardll</li>
    <li>python311Packages.unrardll.dist</li>
    <li>python312Packages.unrardll</li>
    <li>python312Packages.unrardll.dist</li>
    <li>rarcrack</li>
    <li>unrar</li>
    <li>unrar.dev</li>
    <li>unrar_6</li>
    <li>unrar_6.dev</li>
  </ul>
</details>

**Pull request merged**
