### PR TITLE
python310Packages.aiohttp: 3.8.5 -> 3.8.6

### PR DESCRIPTION
**Pull request by dotlambda**
<details>
<summary>I don't understand why one test is failing.</summary>

```
___________________ test_request_tracing_url_params[pyloop] ____________________

loop = <_UnixSelectorEventLoop running=False closed=False debug=False>
aiohttp_client = <function aiohttp_client.<locals>.go at 0x7ffff4e314e0>

    async def test_request_tracing_url_params(loop: Any, aiohttp_client: Any) -> None:
        async def root_handler(request):
            return web.Response()

        async def redirect_handler(request):
            raise web.HTTPFound("/")

        app = web.Application()
        app.router.add_get("/", root_handler)
        app.router.add_get("/redirect", redirect_handler)

        mocks = [mock.Mock(side_effect=make_mocked_coro(mock.Mock())) for _ in range(7)]
        (
            on_request_start,
            on_request_redirect,
            on_request_end,
            on_request_exception,
            on_request_chunk_sent,
            on_response_chunk_received,
            on_request_headers_sent,
        ) = mocks

        trace_config = aiohttp.TraceConfig(
            trace_config_ctx_factory=mock.Mock(return_value=mock.Mock())
        )
        trace_config.on_request_start.append(on_request_start)
        trace_config.on_request_redirect.append(on_request_redirect)
        trace_config.on_request_end.append(on_request_end)
        trace_config.on_request_exception.append(on_request_exception)
        trace_config.on_request_chunk_sent.append(on_request_chunk_sent)
        trace_config.on_response_chunk_received.append(on_response_chunk_received)
        trace_config.on_request_headers_sent.append(on_request_headers_sent)

        session = await aiohttp_client(app, trace_configs=[trace_config])

        def reset_mocks() -> None:
            for m in mocks:
                m.reset_mock()

        def to_trace_urls(mock_func: mock.Mock) -> List[URL]:
            return [call_args[0][-1].url for call_args in mock_func.call_args_list]

        def to_url(path: str) -> URL:
            return session.make_url(path)

        # Standard
        for req in [
            lambda: session.get("/?x=0"),
            lambda: session.get("/", params=dict(x=0)),
        ]:
            reset_mocks()
            async with req() as resp:
                await resp.text()
>               assert to_trace_urls(on_request_start) == [to_url("/?x=0")]
E               AssertionError: assert [URL('http://....0.1:41893/')] == [URL('http://...:41893/?x=0')]
E                 At index 0 diff: URL('http://127.0.0.1:41893/') != URL('http://127.0.0.1:41893/?x=0')
E                 Full diff:
E                 - [URL('http://127.0.0.1:41893/?x=0')]
E                 ?                              ----
E                 + [URL('http://127.0.0.1:41893/')]

aiohttp_client = <function aiohttp_client.<locals>.go at 0x7ffff4e314e0>
app        = <Application 0x7ffff45d2250>
loop       = <_UnixSelectorEventLoop running=False closed=False debug=False>
mocks      = [<Mock id='140737293134672'>, <Mock id='140737293131728'>, <Mock id='140737298123280'>, <Mock id='140737298131024'>, <Mock id='140737298127440'>, <Mock id='140737298133200'>, ...]
on_request_chunk_sent = <Mock id='140737298127440'>
on_request_end = <Mock id='140737298123280'>
on_request_exception = <Mock id='140737298131024'>
on_request_headers_sent = <Mock id='140737298131792'>
on_request_redirect = <Mock id='140737293131728'>
on_request_start = <Mock id='140737293134672'>
on_response_chunk_received = <Mock id='140737298133200'>
redirect_handler = <function test_request_tracing_url_params.<locals>.redirect_handler at 0x7ffff4e30e00>
req        = <function test_request_tracing_url_params.<locals>.<lambda> at 0x7ffff4e31940>
reset_mocks = <function test_request_tracing_url_params.<locals>.reset_mocks at 0x7ffff4e31800>
resp       = <ClientResponse(http://127.0.0.1:41893/?x=0) [200 OK]>
<CIMultiDictProxy('Content-Length': '0', 'Content-Type': 'application/octet-stream', 'Date': 'Mon, 09 Oct 2023 04:13:13 GMT', 'Server': 'Python/3.11 aiohttp/3.8.6')>

root_handler = <function test_request_tracing_url_params.<locals>.root_handler at 0x7ffff4e316c0>
session    = <aiohttp.test_utils.TestClient object at 0x7ffff4a96b10>
to_trace_urls = <function test_request_tracing_url_params.<locals>.to_trace_urls at 0x7ffff4e313a0>
to_url     = <function test_request_tracing_url_params.<locals>.to_url at 0x7ffff4e318a0>
trace_config = <aiohttp.tracing.TraceConfig object at 0x7ffff4a963d0>

test_client_session.py:669: AssertionError
```
</details>
EDIT: I applied https://github.com/aio-libs/aiohttp/pull/7260 to fix this.

## Description of changes
Changelog: https://github.com/aio-libs/aiohttp/blob/v3.8.6/CHANGES.rst

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
@mweinelt Home Assistant's tests fail with
```
__________________ test_multiple_runs_repeat_choose[action0] ___________________
[gw6] linux -- Python 3.11.4 /nix/store/3k7is7nc2xbav8a48vx7arad522d8czx-python3-3.11.4/bin/python3.11

hass = <HomeAssistant RUNNING>
caplog = <_pytest.logging.LogCaptureFixture object at 0x7fffa475f490>
action = {'repeat': {'count': 1, 'sequence': {'event': 'abc'}}}

    @pytest.mark.parametrize(
        "action",
        [
            {"repeat": {"count": 1, "sequence": {"event": "abc"}}},
            {"choose": {"conditions": [], "sequence": {"event": "abc"}}},
            {"choose": [], "default": {"event": "abc"}},
        ],
    )
    async def test_multiple_runs_repeat_choose(
        hass: HomeAssistant, caplog: pytest.LogCaptureFixture, action
    ) -> None:
        """Test parallel runs with repeat & choose actions & max_runs > default."""
        max_runs = script.DEFAULT_MAX + 1
        script_obj = script.Script(
            hass,
            cv.SCRIPT_SCHEMA(action),
            "Test Name",
            "test_domain",
            script_mode="parallel",
            max_runs=max_runs,
        )

        events = async_capture_events(hass, "abc")
        for _ in range(max_runs):
            hass.async_create_task(script_obj.async_run(context=Context()))
        await hass.async_block_till_done()

>       assert "WARNING" not in caplog.text
E       AssertionError: assert 'WARNING' not in '2023-10-21 ...nt abc[L]>\n'
E         'WARNING' is contained here:
E           15:41.723 WARNING  MainThread asyncio:base_events.py:1917 Executing <Task pending name='Task-3956' coro=<Script.async_run() running at /build/homeassistant-2023.10.4/homeassistant/helpers/script.py:1578> wait_for=<Future pending cb=[shield.<locals>._outer_done_callback() at /nix/store/3k7is7nc2xbav8a48vx7arad522d8czx-python3-3.11.4/lib/python3.11/asyncio/tasks.py:898, Task.task_wakeup()] created at /nix/store/3k7is7nc2xbav8a48vx7arad522d8czx-python3-3.11.4/lib/python3.11/asyncio/base_events.py:427> cb=[set.remove(), _wait.<locals>._on_completion() at /nix/sto...
E
E         ...Full output truncated (35 lines hidden), use '-vv' to show

_          = 10
action     = {'repeat': {'count': 1, 'sequence': {'event': 'abc'}}}
caplog     = <_pytest.logging.LogCaptureFixture object at 0x7fffa475f490>
events     = [<Event abc[L]>, <Event abc[L]>, <Event abc[L]>, <Event abc[L]>, <Event abc[L]>, <Event abc[L]>, ...]
hass       = <HomeAssistant RUNNING>
max_runs   = 11
script_obj = <homeassistant.helpers.script.Script object at 0x7fffa3f46c10>
```

**Comment by mweinelt** [comment]
They downgraded to 3.8.5 after 3.8.6 caused problems.

https://github.com/home-assistant/core/pull/101913

**Comment by dotlambda** [comment]
One of the security issues would also be fixed by https://github.com/NixOS/nixpkgs/pull/244541.

**Comment by mweinelt** [comment]
@ofborg eval

**Comment by mweinelt** [comment]
I'm a bit worried about what happened to home-assistant, so we'll have to keep an eye on other regressions.

**Pull request merged**
