### PR TITLE
llvmPackages_14.openmp: unbreak

### PR DESCRIPTION
**Pull request by dtzWill**
###### Description of changes

Fixup old patches causing OpenMP to be marked broken,
one of which can be removed in favor of pointing the build
at the required tools directly.

Mostly get tests working, but few failures I haven't tracked down
caused me to ultimately disable them for now.

Help testing or pointing to something that should work on Linux with
this is appreciated :).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dtzWill** [comment]
Looks like others need fixing too, see #162423 .  Especially `libunwind` and `libcxxabi`.  `libunwind` is trickier re:patch.
@Ericson2314 IIRC you upstreamed some patches to LLVM re:GNUInstallDirs, what's the status there? And don't suppose you have patches for these already or would be willing to take a look? Thanks!

**Comment by dtzWill** [comment]
(force-push'ing after rebasing onto master, and -rc updates before that)

**Comment by Ericson2314** [comment]
@dtzWill https://github.com/NixOS/nixpkgs/pull/154465 updated the patches somewhat, a tiny bit more was perhaps upstreamed since. I am not sure at what point the branch-offs occured upstream.

**Comment by Ericson2314** [comment]
github.com/Ericson2314/llvm-project has the commits I made by patches from, but I would rebase them so it is unclear whether we have enough to stuff for prior releases from there :(.

**Comment by Ericson2314** [comment]
@dtzWill Did you just remove parts of the patch that already were applied, or what?

**Comment by dtzWill** [comment]
### Patch change question

> @dtzWill Did you just remove parts of the patch that already were applied, or what?

Actually it looks like for this one... yes! Looking at how this compares to the patch before (or in `git/`, thanks for the pointer) that's all it took.  IIRC I applied it to the llvm-project tree and went from there, grep'd for the changed patterns a bit.  And dropped the tools patch in favor of using the cmake vars to control those paths.  Almost got tests working, I'll check but if you don't hear they're still failing on the final release :smile:.

### vs openmp13

Comparing this to `llvmPackages_13.openmp`, this has multiple outputs now (which were already present before this PR)! So that might impact users, but hopefully works as folks expect without much trouble.  Might be good to ensure that users of the `.dev` output's cmake files can properly find the libraries in `.out`.  But since this patch is basically what we had before, modulo what you upstreamed (hooray!), maybe I'm worrying too much about this :smile:.

Comparing the header trees, looks like it's almost entirely the same, small enough I can include the diff:

```diff
diff -r ./openmp13/include/omp.h ./openmp14-dev/include/omp.h
434c434,439
<     extern void *__KAI_KMPC_CONVENTION omp_calloc(size_t nmemb, size_t size, omp_allocator_handle_t a = omp_null_allocator);
---
>     extern void *__KAI_KMPC_CONVENTION omp_aligned_alloc(size_t align, size_t size,
>                                                          omp_allocator_handle_t a = omp_null_allocator);
>     extern void *__KAI_KMPC_CONVENTION omp_calloc(size_t nmemb, size_t size,
>                                                   omp_allocator_handle_t a = omp_null_allocator);
>     extern void *__KAI_KMPC_CONVENTION omp_aligned_calloc(size_t align, size_t nmemb, size_t size,
>                                                           omp_allocator_handle_t a = omp_null_allocator);
440a446,447
>     extern void *__KAI_KMPC_CONVENTION omp_aligned_alloc(size_t align, size_t size,
>                                                          omp_allocator_handle_t a);
441a449,450
>     extern void *__KAI_KMPC_CONVENTION omp_aligned_calloc(size_t align, size_t nmemb, size_t size,
>                                                           omp_allocator_handle_t a);
```

Seems like on that front things are very unlikely to break :).

I re-enabled the bitcode building as it builds and installs it fine AFAICT.

### Testing

If someone is in a position to test this at all, that'd be swell.  I admit I don't remember right now how to use this for ad-hoc testing, and of course checking our in-tree users (or future in-tree users when they move to 14) would be good.

* in-tree users: Darwin, clang-based stdenv's.  Maybe can at least kick the tires a bit by modifying a package to use an appropriate stdenv on Linux for that.  Might take fair bit of compute to test more exhaustively on Linux (via `pkgsLLVM` or something).
* Checking build on Darwin:  Darwin ofborg builders timed out building LLVM, checking this at least /builds/ on that platform is probably a good idea before proudly marking it no longer broken :innocent: .

---

All that said, I think if this looks good to folks we should move ahead (maybe after build-testing on Darwin?).  I think things like `libcxxabi` are likely more important, for example.  Not sure how tricky that'll be yet!

**Comment by dtzWill** [comment]
> @dtzWill Did you just remove parts of the patch that already were applied, or what?

That's what it ended up being, yes, I think.  Not how I went about it but yes, applied and seemed safe to drop bits that were already applied (since seemed you were upstreaming things).  The rest still seem useful, and seem to be needed (and doing what they seem intended to).

Bummer about the patches rebase'd and maybe lost from around the branch-off.  These things happen, but ugh sorry.  How do you want to handle this, then? (don't suppose you have a super high `git reflog` limit and they're still sticking around in there? *hopeful face*)

What we have here (openmp) doesn't seem super broken (bits all end up in expected places, compared to openmp13 -- includes are almost entirely the same, etc.), but I haven't checked the produced cmake bits all work (esp across multiple outputs).  Haven't sorted what a good test might be, since our in-tree users are Darwin or a clangStdenv (so can't just point nixpkgs-review at it or something :)).

The other bits (the other subprojects) I/we might need (or really appreciate at the least) some help with.  Can you take a look?  Or is there a way to check things work as expected?

---

BTW I've done a hopefully-not-too-rough attempt at packaging up MLIR and flang over here: https://github.com/NixOS/nixpkgs/pull/163878 .  I noticed your github has a gnu installdirs for MLIR (5ad96992ef909e6b99d8c693a285f06c9fc645fe), is any of that needed? To fix libraries being installed in the wrong location, I addressed it same as in another patch (but I don't see that in your commit).  Well anyway, this can be discussed over in that PR if you have time/are interested :smile:.  Also, I'm packaging up a few more projects, hopefully that'll be posted soon (maybe as a flake).

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 163868` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>llvmPackages_14.openmp</li>
  </ul>
</details>

**Comment by Ericson2314** [comment]
@dtzWill is the issue that the GNU install dirs LLVM patches only contain too much stuff, or do they sometimes not contain enough stuff? If just tthe former I might have reflog, but honestly I would just start with what's in Nixpkgs as more of a known-good state.

**Comment by Ericson2314** [comment]
Also note I did save the original backports in `split-prefix-*`. I should probably put 13's in there for safe keeping, and 14's once it is fixed it.

**Pull request merged**
