### PR TITLE
llvmPackages_12: 12.0.0-rc5 -> 12.0.0

### PR DESCRIPTION
**Pull request by primeos**
Release notes: https://releases.llvm.org/12.0.0/docs/ReleaseNotes.html

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by primeos** [comment]
@GrahamcOfBorg build llvmPackages_12

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 119541` at 2c2e8662 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>19 packages skipped due to time constraints:</summary>
  <ul>
    <li>chromium</li>
    <li>clang_12 (llvmPackages_12.clang ,llvmPackages_12.libstdcxxClang)</li>
    <li>lld_12 (llvmPackages_12.lld)</li>
    <li>lldb_12 (llvmPackages_12.lldb)</li>
    <li>llvmPackages_12.bintools</li>
    <li>llvmPackages_12.clang-manpages</li>
    <li>llvmPackages_12.clang-unwrapped</li>
    <li>llvmPackages_12.compiler-rt</li>
    <li>llvmPackages_12.libclang</li>
    <li>llvmPackages_12.libcxxClang</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>3 packages built successfully:</summary>
  <ul>
    <li>llvmPackages_12.libcxx</li>
    <li>llvmPackages_12.libcxxabi</li>
    <li>llvmPackages_12.libunwind</li>
  </ul>
</details>
<details>
  <summary>18 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/development/compilers/llvm/12/libunwind/default.nix:20:3:
```
   |
20 |   cmakeFlags = lib.optional (!enableShared) "-DLIBUNWIND_ENABLE_SHARED=OFF";
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/compilers/llvm/12/lldb/default.nix:75:3:
```
   |
75 |   meta = with lib; {
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/compilers/llvm/12/clang/default.nix:98:5:
```
   |
98 |     installPhase = ''
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/development/compilers/llvm/12/clang/default.nix:39:7:
```
   |
39 |       ./purity.patch
   |       ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/compilers/llvm/12/compiler-rt/default.nix:19:3:
```
   |
19 |   NIX_CFLAGS_COMPILE = [
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/compilers/llvm/12/libunwind/default.nix:20:3:
```
   |
20 |   cmakeFlags = lib.optional (!enableShared) "-DLIBUNWIND_ENABLE_SHARED=OFF";
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/compilers/llvm/12/lld/default.nix:33:3:
```
   |
33 |   meta = {
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/development/compilers/llvm/12/compiler-rt/default.nix:52:5:
```
   |
52 |     ./compiler-rt-codesign.patch # Revert compiler-rt commit that makes codesign mandatory
   |     ^
```
</li>
    <li>warning: unused-argument

Unused argument: `fetchpatch`.
Near pkgs/development/compilers/llvm/12/libc++/default.nix:1:23:
```
  |
1 | { lib, stdenv, fetch, fetchpatch, cmake, python3, libcxxabi, llvm, fixDarwinDylibNames, version
  |                       ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/compilers/llvm/12/libc++/default.nix:43:3:
```
   |
43 |   meta = {
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/compilers/llvm/12/libc++abi/default.nix:37:3:
```
   |
37 |   installPhase = if stdenv.isDarwin
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/compilers/llvm/12/clang/default.nix:85:5:
```
   |
85 |     meta = {
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/development/compilers/llvm/12/lldb/default.nix:30:15:
```
   |
30 |   patches = [ ./lldb-procfs.patch ];
   |               ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/development/compilers/llvm/12/compiler-rt/default.nix:19:3:
```
   |
19 |   NIX_CFLAGS_COMPILE = [
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/compilers/llvm/12/openmp.nix:19:3:
```
   |
19 |   meta = {
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/development/compilers/llvm/12/clang/default.nix:94:5:
```
   |
94 |     buildPhase = ''
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/development/compilers/llvm/12/clang/default.nix:108:5:
```
    |
108 |     meta.description = "man page for Clang ${version}";
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/compilers/llvm/12/clang/default.nix:108:5:
```
    |
108 |     meta.description = "man page for Clang ${version}";
    |     ^
```
</li>
  </ul>
</details>

**Comment by vcunat** [comment]
It isn't new but occasionally we get error in one test: https://hydra.nixos.org/build/141548680
```
Failed Tests (1):
  LLVM :: tools/llvm-exegesis/X86/uops-CMOV16rm-noreg.s
```
Not sure what to do about the cases; so far they just got restarted until succeeding.

**Comment by primeos** [comment]
I've just noticed this too because the Chromium build failed. Is it always the same test (and does it happen frequently)? If so it would seem like a good idea to try to disable it.

**Comment by vcunat** [comment]
Always the same test, in the cases I've seen.  Last time in LLVM 11, I think.  I saw some [revert upstream](https://reviews.llvm.org/rG7822b4618853a41aaa5ee3a7f14e0e32b1d29a64) but that seemed already included in the relevant releases.

**Comment by vcunat** [comment]
[Here's one](https://hydra.nixos.org/build/141497033/nixlog/1/tail) with LLVM 9.  Maybe some change in (some of) the build machines triggered these appearances.

**Comment by lukegb** [comment]
I filed #119673 for this. Basically, if it builds on wendy, it'll break :(

**Comment by vcunat** [comment]
@primeos: was it intentional not to bump `llvmPackages_latest`?

**Comment by primeos** [comment]
> @primeos: was it intentional not to bump llvmPackages_latest?

Yes, in the past we often waited a few weeks in case some issues/regressions appear and in case we want to make a few additional changes before it affects a lot of rebuilds. I've currently repurposed https://github.com/NixOS/nixpkgs/pull/116646 for `llvmPackages_latest`. I didn't perform that change in the past so I'm also not sure how best to test it (I guess a Hydra jobset would make sense?).

**Pull request merged**
