### PR TITLE
powerline-go: 1.12.1 -> 1.13.0

### PR DESCRIPTION
**Pull request by sifmelcara**
###### Motivation for this change
New version released by upstream.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xrelkd** [comment]
@GrahamcOfBorg build powerline-go

**Comment by xrelkd** [comment]
LGTM!
I also tested `powerline-go` locally on NixOS.
@marsam Could you merge this PR? Thank you very much!

**Review by marsam — COMMENTED** [review]
Looks like upstream uses go modules, would you mind updating the expression to use [`buildGoModule`](https://nixos.org/nixpkgs/manual/#ssec-go-modules)?

**Comment by sifmelcara** [comment]
Thanks for the suggestion! PR updated and tested again.
(and thanks @xrelkd for reviewing my pending PRs!)

**Comment by marsam** [comment]
Tested locally on NixOS and darwin.
Thanks @sifmelcara, and xrelkd

**Pull request merged**
