### PR TITLE
gitbutler: 0.12.16 -> 0.14.4

### LINKED ISSUE #335875: Update request: gitbutler 0.12.16 → 0.12.20
- Package name: gitbutler
- Latest released version: 0.12.20

- Current version on the unstable channel:0.12.16
- Current version on the stable/release channel: none

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

@getchoo 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #355157: Build failure: gitbutler
### Steps To Reproduce

1. nix build --impure nixpkgs#gitbutler

### Build log

[Gist](https://gist.github.com/matyas-cimbulka/5ad393b33872801d71da31df0808ed79)

### Notify maintainers
@getchoo
@techknowlogick 

### Metadata

---
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.58, NixOS, 24.11 (Vicuna), 24.11.20241109.76612b1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source`

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by getchoo**
Closes #335875
Fixes #355157
Supersedes #347819
Part of #354146

Changelog: https://github.com/gitbutlerapp/gitbutler/releases/tag/release%2F0.14.1
Diff: https://github.com/gitbutlerapp/gitbutler/compare/release/0.12.16...release/0.14.1

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by techknowlogick** [comment]
Thanks for figuring this one out <3

Will run this through `nixpkgs-review` and test it out soon.

**Comment by techknowlogick** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 355366`

---
### `aarch64-darwin`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>gitbutler</li>
  </ul>
</details>

**Comment by getchoo** [comment]
Thanks for catching that. My old MBA takes *ages* to build this 😆

**Comment by sarahec** [comment]
Result of `nixpkgs-review pr 355366` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>gitbutler</li>
  </ul>
</details>

**Comment by sarahec** [comment]
`gitoxide` is failing to build during nixpkgs-review and taking everything else down.

**Comment by sarahec** [comment]
Result of `nixpkgs-review pr 355366` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>gitbutler</li>
  </ul>
</details>

**Comment by sarahec** [comment]
Build error (aarch64-darwin):
```sh
       > Finished cargoCheckHook
       > checkPhase completed in 1 minutes 45 seconds
       > Running phase: glibPreInstallPhase
       > Running phase: glibPreInstallPhase
       > Running phase: installPhase
       > Executing tauriInstallHook
       > mv: cannot stat '/nix/store/4wxc38ls8z07gfrmiqq9zw81zplk740g-gitbutler-0.13.13/Applications/GitButler.app/Contents/MacOS/GitButler': No such file or directory
```

**Comment by getchoo** [comment]
Ah, binary name must have changed there too. Thanks so much :)

**Comment by sarahec** [comment]
Result of `nixpkgs-review pr 355366` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gitbutler</li>
  </ul>
</details>

**Comment by techknowlogick** [comment]
> Thanks for catching that. My old MBA takes _ages_ to build this 😆

No worries, a bit of warmth in these colder months 😆

Sorry for just pasting the build error above without any context; I had to rush off and couldn't provide more details, but I figured what I had would be enough, and if not, then at least it'd be a starting point until I could get back and give more.

Thanks again for figuring out what was going on with the rust stuff. And thank you, @sarahec, for providing additional Darwin build information.

**Review by techknowlogick — APPROVED** [review]

**Comment by getchoo** [comment]
Result of `nixpkgs-review pr 355366` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gitbutler</li>
  </ul>
</details>

**Comment by getchoo** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 355366`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>gitbutler</li>
  </ul>
</details>

**Review by Scrumplex — COMMENTED** [review]
0.13.15 has been released, and I was reminded and offered to update using upstream's updater. Interestingly, it fails with `Invalid cross-device link (os error 18)`

Is your patch supposed to disable the updater too?

**Comment by getchoo** [comment]
> Is your patch supposed to disable the update too?

`.bundle.createUpdaterArtifacts = false` on [this](https://github.com/NixOS/nixpkgs/blob/a42b32c15c57dd6f33f9c6d6be0fec18a744cc54/pkgs/by-name/gi/gitbutler/package.nix#L52) line should. Guess this is another weird thing from Tauri v2 :/

**Comment by getchoo** [comment]
Bumped to the latest version, and the updater should be removed properly now

**Comment by getchoo** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 355366`

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>gitbutler</li>
  </ul>
</details>

**Comment by phsb5321** [comment]
Is there any reason it's not merged yet?

**Comment by getchoo** [comment]
Waiting on reviews now

**Review by Scrumplex — COMMENTED** [review]
changes LGTM. Currently building

**Comment by Scrumplex** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 355366`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>gitbutler</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>gitbutler</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>gitbutler</li>
  </ul>
</details>

**Review by Scrumplex — APPROVED** [review]

**Comment by Scrumplex** [comment]
It seems like after trying to run the main program, it fails with the following error:

```
thread 'main' panicked at crates/gitbutler-tauri/src/main.rs:262:18:
Failed to build tauri app: PluginInitialization("updater", "Error deserializing 'plugins.updater' within your Tauri configuration: invalid type: null, expected struct Config")
```

I guess removing the updater configuration breaks parsing it at runtime :/

**Comment by getchoo** [comment]
The app now launches and doesn't try to update, but instead shows an error about the list of endpoints being empty. Properly patching this out will probably take me a bit, as they have actually rolled their own updater based on Tauri's APIs

Let me know if there is interest in merging this in its current form, though. Might be worth unbreaking the package and bringing it to a supported version with a warning rather than waiting

**Comment by phsb5321** [comment]
Hey, is it possible to use the package derivation before it is merged? Sorry, I am really new in NixOS.

**Comment by getchoo** [comment]
You can checkout this branch of Nixpkgs only for this package with something like the following

```nix
{ pkgs, ... }:

let
  nixpkgs-gitbutler = fetchTarball "https://github.com/NixOS/nixpkgs/archive/6b2bd7588dfb58281f66c8837e5e5ed92d04862f.tar.gz";
  gitbutlerPkgs = import nixpkgs-gitbutler {
    inherit (pkgs.stdenv.hostPlatform) system;
    inherit (pkgs) config overlays;
  };
in

{
  environment.systemPackages = [ gitbutlerPkgs.gitbutler ];
}
```

If you're using Flakes, `nixpkgs-gitbutler` should be an input rather than using `fetchTarball` (though you could still use this in a Flake by passing `--impure`)

**Comment by techknowlogick** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 355366`

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>gitbutler</li>
  </ul>
</details>

**Comment by techknowlogick** [comment]
I'm fine with merging it as-is with the updater warning.

**Comment by phsb5321** [comment]
> You can checkout this branch of Nixpkgs only for this package with something like the following
> 
> ```nix
> { pkgs, ... }:
> 
> let
>   nixpkgs-gitbutler = fetchTarball "https://github.com/NixOS/nixpkgs/archive/6b2bd7588dfb58281f66c8837e5e5ed92d04862f.tar.gz";
>   gitbutlerPkgs = import nixpkgs-gitbutler {
>     inherit (pkgs.stdenv.hostPlatform) system;
>     inherit (pkgs) config overlays;
>   };
> in
> 
> {
>   environment.systemPackages = [ gitbutlerPkgs.gitbutler ];
> }
> ```
> 
> If you're using Flakes, `nixpkgs-gitbutler` should be an input rather than using `fetchTarball` (though you could still use this in a Flake by passing `--impure`)

---

👋 Thank you for helping me with the Gitbutler setup! That was super helpful.

I have a follow-up question - how did you get/generate the Flake URL (github:nixos/nixpkgs/6b2bd7588dfb58281f66c8837e5e5ed92d04862f) from the PR? I'd love to learn how to do this myself for future PRs 🙏

**Comment by Scrumplex** [comment]
IMO the updater can stay for now. Maybe we can ask upstream to add a simple way to disable it.



> I have a follow-up question - how did you get/generate the Flake URL (github:nixos/nixpkgs/6b2bd7588dfb58281f66c8837e5e5ed92d04862f) from the PR? I'd love to learn how to do this myself for future PRs 🙏

@phsb5321 It boils down to `github:NixOS/nixpkgs/<last commit of this PR>`. So just head to the "Commits" tab and copy the full sha1 hash of the last commit (in this case `6b2bd7588dfb58281f66c8837e5e5ed92d04862f`)

**Comment by getchoo** [comment]
If everyone else is good with the warning, then so am I :D

Feel free to merge

**Comment by Scrumplex** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 355366`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>gitbutler</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>gitbutler</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>gitbutler</li>
  </ul>
</details>

**Review by Scrumplex — APPROVED** [review]

**Pull request merged**
