### PR TITLE
teams-for-linux: 1.3.22 -> 1.4.1

### PR DESCRIPTION
**Pull request by chvp**
## Description of changes

https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.3.23  
https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.3.24  
https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.3.25  
https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.3.26  
https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.3.27  
https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.0  
https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.1

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by qjoly — APPROVED** [review]

**Comment by chvp** [comment]
Sorry, converting this to draft, there seems to be an issue with the changes in 1.3.23. Looking into it.

**Comment by chvp** [comment]
My upstream PR fixing the 1.3.23 issue was released, so I've incorporated that release in this PR.

**Comment by rjpcasalino** [comment]
Running `nixpkgs-review` again:

Result of `nixpkgs-review pr 273932` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>teams-for-linux</li>
  </ul>
</details>

```
[nix-shell:~/.cache/nixpkgs-review/pr-273932/results/teams-for-linux/bin]$ ./teams-for-linux --version
unknown
```
but the program runs fine.

**Review by rjpcasalino — APPROVED** [review]

**Comment by lilyinstarlight** [comment]
I trace the version error all the way back through yargs, electron-builder, and electron and I'm 90% sure it is indirectly caused by https://github.com/electron/electron/issues/40501 (since yargs [expects](https://github.com/yargs/yargs/blob/e517318cea0087b813f5de414b3cdec7b70efe33/lib/yargs-factory.ts#L1617) [`require.main.filename`](https://github.com/yargs/yargs/blob/e517318cea0087b813f5de414b3cdec7b70efe33/lib/platform-shims/cjs.ts#L23) when loading via cjs)

As for what to do about it... I guess since I don't think we can make the `cwd` check work, we can either get the teams-for-linux folks to move to ESM for loading or get them to add a `version` arg to the function and a `.version(version)` here:

https://github.com/IsmaelMartinez/teams-for-linux/blob/43ee13e8f3d741e03489de1c0726fe7691915373/app/config/index.js#L20

and propagate the `app.getVersion()` through here:

https://github.com/IsmaelMartinez/teams-for-linux/blob/43ee13e8f3d741e03489de1c0726fe7691915373/app/index.js#L15

and here:

https://github.com/IsmaelMartinez/teams-for-linux/blob/43ee13e8f3d741e03489de1c0726fe7691915373/app/appConfiguration/index.js#L14

Or something equivalent

**Comment by lilyinstarlight** [comment]
I went ahead and opened a PR IsmaelMartinez/teams-for-linux#1058 for the latter because why not. This PR should pass tests with the following diff:

```diff
diff --git a/pkgs/applications/networking/instant-messengers/teams-for-linux/default.nix b/pkgs/applications/networking/instant-messengers/teams-for-linux/default.nix
index 9cb695cc4ad2..6c0a66952650 100644
--- a/pkgs/applications/networking/instant-messengers/teams-for-linux/default.nix
+++ b/pkgs/applications/networking/instant-messengers/teams-for-linux/default.nix
@@ -1,6 +1,7 @@
 { lib
 , stdenv
 , fetchFromGitHub
+, fetchpatch
 , makeWrapper
 , makeDesktopItem
 , copyDesktopItems
@@ -33,6 +34,15 @@ stdenv.mkDerivation (finalAttrs: {
     hash = "sha256-ef+JW5ud9LlRxaCJC2iOT5N7FgZO7IkAABJcMQPvIBA=";
   };
 
+  patches = [
+    # remove when IsmaelMartinez/teams-for-linux#1058 is merged
+    (fetchpatch {
+      name = "teams-for-linux-fix-version.patch";
+      url = "https://github.com/IsmaelMartinez/teams-for-linux/commit/1d14947eef35c6a2e0cbdfcce405820f8dd36c68.diff";
+      hash = "sha256-kj2jEAqgZ0frUw85hY23mFYFcXz95z/WQSDymsheDfg=";
+    })
+  ];
+
   nativeBuildInputs = [ yarn prefetch-yarn-deps nodejs copyDesktopItems makeWrapper ];
 
   configurePhase = ''
```

Thank you @chvp for working on this!

**Comment by chvp** [comment]
> ```diff
> +  patches = [
> +    # remove when IsmaelMartinez/teams-for-linux#1058 is merged
> +    (fetchpatch {
> +      name = "teams-for-linux-fix-version.patch";
> +      url = "https://github.com/IsmaelMartinez/teams-for-linux/commit/1d14947eef35c6a2e0cbdfcce405820f8dd36c68.diff";
> +      hash = "sha256-kj2jEAqgZ0frUw85hY23mFYFcXz95z/WQSDymsheDfg=";
> +    })
> +  ];
> +
> ```

Applied, thanks!

**Review by lilyinstarlight — APPROVED** [review]
Looks good to me, thanks again!

**Pull request merged**
