### PR TITLE
vapoursynth-editor: use qt's mkDerivation

### PR DESCRIPTION
**Pull request by tadeokondrak**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by worldofpeace** [comment]
This needs a backport.

**Review by worldofpeace — CHANGES_REQUESTED** [review]
This program is already wrapped, so `wrapQtAppsHook` will ignore wrapping it. This is because it ignores scripts.

What you can do is use `wrapQtApp` in place of `wrapProgram` and set `dontWrapQtApps = true;` as we're wrapping manually. You should then remove `makeWrapper` from this expression.

**Comment by worldofpeace** [comment]
Note, wrapping should happen in `preFixup`. Not the installPhase.

**Comment by tadeokondrak** [comment]
> This program is already wrapped, so wrapQtAppsHook will ignore wrapping it. This is because it ignores scripts.

It does seem to work anyway, but wrapping a program twice probably isn't great.  
Fixed, if it looks good I'll make a backport PR.

**Comment by worldofpeace** [comment]
> > This program is already wrapped, so wrapQtAppsHook will ignore wrapping it. This is because it ignores scripts.
> 
> It does seem to work anyway, but wrapping a program twice probably isn't great.
> Fixed, if it looks good I'll make a backport PR.

This was the content of the wrapper without using `wrapQtApp`
```
#! /nix/store/zavn4np1jvm79f0rafkv0p1mrag09qkz-bash-4.4-p23/bin/bash -e
export PYTHONPATH='/nix/store/f5fz7wa9nixd7qpzh6a1rp1ij7bxw0xq-vapoursynth-R47.2/lib/python3.7/site-packages'${PYTHONPATH:+':'}$PYTHONPATH
export LD_LIBRARY_PATH='/nix/store/f5fz7wa9nixd7qpzh6a1rp1ij7bxw0xq-vapoursynth-R47.2/lib'${LD_LIBRARY_PATH:+':'}$LD_LIBRARY_PATH
exec -a "$0" "/nix/store/mbbql8hkf5b8kplkji3h469wf5b6avk6-vapoursynth-editor-R19/bin/.vsedit-wrapped"  "$@"
```

so it was actually broken. 

Here's the content of the wrapper in the latest commit
```
#! /nix/store/zavn4np1jvm79f0rafkv0p1mrag09qkz-bash-4.4-p23/bin/bash -e
export QT_PLUGIN_PATH='/nix/store/js39qrk4i5i5my3nl317dniqk4sp5dgi-qtbase-5.12.5-bin/lib/qt-5.12.5/plugins'${QT_PLUGIN_PATH:+':'}$QT_PLUGIN_PATH
export QT_PLUGIN_PATH='/nix/store/x507783mf613yhaksqcj2bpy14mrwa8l-qtsvg-5.12.5-bin/lib/qt-5.12.5/plugins'${QT_PLUGIN_PATH:+':'}$QT_PLUGIN_PATH
export QT_PLUGIN_PATH='/nix/store/phka1gjvm55kmw7jw9nmm7aa62q7anlf-qtdeclarative-5.12.5-bin/lib/qt-5.12.5/plugins'${QT_PLUGIN_PATH:+':'}$QT_PLUGIN_PATH
export QML2_IMPORT_PATH='/nix/store/phka1gjvm55kmw7jw9nmm7aa62q7anlf-qtdeclarative-5.12.5-bin/lib/qt-5.12.5/qml'${QML2_IMPORT_PATH:+':'}$QML2_IMPORT_PATH
export QML2_IMPORT_PATH='/nix/store/cl4r46fmcihpig1slcpmm1s2bx72cv5h-qtquickcontrols-5.12.5/lib/qt-5.12.5/qml'${QML2_IMPORT_PATH:+':'}$QML2_IMPORT_PATH
export QT_PLUGIN_PATH='/nix/store/ays1cry94qjil280jjh9j283f2pkb74j-qtwayland-5.12.5-bin/lib/qt-5.12.5/plugins'${QT_PLUGIN_PATH:+':'}$QT_PLUGIN_PATH
export QML2_IMPORT_PATH='/nix/store/ays1cry94qjil280jjh9j283f2pkb74j-qtwayland-5.12.5-bin/lib/qt-5.12.5/qml'${QML2_IMPORT_PATH:+':'}$QML2_IMPORT_PATH
export QML2_IMPORT_PATH='/nix/store/kq988pbxyp5pwz54k51xdg54ljlva5w2-qtwebsockets-5.12.5-bin/lib/qt-5.12.5/qml'${QML2_IMPORT_PATH:+':'}$QML2_IMPORT_PATH
export PYTHONPATH='/nix/store/f5fz7wa9nixd7qpzh6a1rp1ij7bxw0xq-vapoursynth-R47.2/lib/python3.7/site-packages'${PYTHONPATH:+':'}$PYTHONPATH
export LD_LIBRARY_PATH='/nix/store/f5fz7wa9nixd7qpzh6a1rp1ij7bxw0xq-vapoursynth-R47.2/lib'${LD_LIBRARY_PATH:+':'}$LD_LIBRARY_PATH
exec -a "$0" "/nix/store/819qdp87gc22j989vqyn8kqmwrl2q5nv-vapoursynth-editor-R19/bin/.vsedit-wrapped"  "$@"
```

LGTM :+1: I can perform the backport manually for you as well.

**Comment by tadeokondrak** [comment]
> This was the content of the wrapper without using wrapQtApp

Yeah, `.vsedit-wrapped` actually was another wrapper script that called `..vsedit-wrapped-wrapped`.
> LGTM +1 I can perform the backport manually for you as well.

Thanks!

**Comment by worldofpeace** [comment]
backported in 82b699861c27819b859abe28b17ebcfe4745a197.

> Thanks!

No problem, thank you :sparkles:

**Pull request merged**
