### PR TITLE
Rust and cargo improvements

### PR DESCRIPTION
**Pull request by dvc94ch**
###### Motivation for this change
- Enable cross-compiling std crates
- Prepare for the 1.10.0 release when we can bootstrap from release tarball
- Update cargo and use release tarball
- Add scripts to fetch release tarball hashes for supported platforms

To try out rust on arm (depends on https://github.com/NixOS/nixpkgs/pull/15867):

``` nix
with import <nixpkgs> {};

let
  pkgs = import ../../../nixpkgs;
  pkgsNative = pkgs {};
  pkgsCross = pkgs {
    inherit system;
    inherit crossSystem;
  };
  crossSystem = rec {
    config = "arm-linux-gnueabihf";
    bigEndian = false;
    arch = "arm";
    float = "hard";
    fpu = "vfpv3-d16";
    withTLS = true;
    libc = "glibc";
    platform = platforms.armv7l-hf-multiplatform;
    openssl.system = "linux-generic32";
    inherit (platform) gcc;
  };
  rustc = pkgsNative.rustc.override {
    targets = ["armv7-unknown-linux-gnueabihf"];
    targetToolchains = [pkgsCross.gccCrossStageFinal];
  };
  cargo = pkgsNative.cargo.override {
    inherit rustc;
  };
in
stdenv.mkDerivation rec {
    name = "arm-hello";

    buildInputs = [ cargo pkgsCross.gccCrossStageFinal qemu ];

    shellHook = ''
        PS1="rust-arm> "
        alias build="cargo build --target=${rustc.target}"
        alias run-debug="qemu-arm target/${rustc.target}/debug/${name}"
        alias run-release="qemu-arm target/${rustc.target}/release/${name}"
    '';
}
```
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jagajaga** [comment]
cc @wizeman

**Comment by dvc94ch** [comment]
don't merge this just yet, I want to rework this. rust is moving to using cargo as a build system, so the rustc and cargo packages can share the bootstrapping code. should this be a new package then? or can we put the cargo and rustc code in the same folder so that we can share the bootstrapping code through local imports without polluting all-packages?

**Comment by the-kenny** [comment]
I'm fine with moving `cargo` and `rustc` to the same folder if that simplifies the implementation.

**Comment by dvc94ch** [comment]
So final building and testing is still pending, but I think it should be ok. If someone wants to test it on mac osx to make sure there are no regressions, that would be good...

**Comment by the-kenny** [comment]
Seems like there is an issue with evaluating the package set:

```
% nix-env -f . -qa
error: getting status of ‘/home/moritz/dev/nixpkgs/pkgs/development/tools/build-managers/cargo’: No such file or directory
```

**Comment by the-kenny** [comment]
Also, personally, I'd like an alias for `rustc` in `all-packages.nix` just like for `cargo`.

**Comment by dvc94ch** [comment]
mmh that is right there is no build-managers cargo anymore. have you added any custom patches to nixpkgs? I'm not having that problem... I rebased on master and added a sha256 fix for the exa package, can you try again?

**Comment by the-kenny** [comment]
I didn't at the time. I re-applied everything after your recent rebase and now it's evaluating fine.

**Comment by the-kenny** [comment]
I'll check if everything builds fine with sandbox . Otherwise :+1:

**Comment by the-kenny** [comment]
@dvc94ch 



```
nix-build . -A rustc 
...
output path ‘/nix/store/dx95c8mp9g1gqvy5qin10xzwngw2yr97-rust-e4e8b66’ has r:sha256 hash ‘1pz4qx70mqv78fxm4w1mq7csk5pssq4qmr2vwwb5v8hyx03caff8’ when ‘167rh7hs77grn895h54s7np7f0k7b6i8z4wdfinncg4chy08hxq1’ was expected
```

**Comment by dvc94ch** [comment]
I get these spurious hash changes sometimes too. My rust src is currently cached, so I didn't notice the change. I think fetchgit isn't 100% deterministic.

**Comment by dvc94ch** [comment]
Pushed the hash change

**Comment by the-kenny** [comment]
Ugh, non-determinism in `fetchgit` isn't good. It pulls quite a bunch of submodules (I think), maybe it's related to that?

**Comment by dvc94ch** [comment]
Maybe. If I would make a wild guess I'd say this happens when a submodule
gets a new branch. But I haven't looked into this, since once it's
committed the package is in the binary cache, so it isn't an issue until
you make a change...

**Comment by dvc94ch** [comment]
@the-kenny I know I'm inpatient, but I'll ask anyway. Are we good to go?

**Comment by the-kenny** [comment]
Sorry! I was busy at work yesterday (while my machine built all of Rust in Nix). To me it looks good. I think it's fine to merge it, but we should try to investigate the sha256 issue further.We’ve changed the BLE Scanning behavior starting in DP4. We’ll prevent applications from starting and stopping scans more than 5 times in 30 seconds. For long running scans, we’ll convert them into opportunistic scans.

**Pull request merged**
