### PR TITLE
terraform_0_11: 0.11.5 -> 0.11.6

### PR DESCRIPTION
**Pull request by jbgi**
Fix a particularly annoying regression: https://github.com/hashicorp/terraform/pull/17744

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build terraform_0_11

**Comment by Mic92** [comment]
@GrahamcOfBorg build terraform_0_11

**Comment by Mic92** [comment]
also in 18.03 now.

**Comment by copumpkin** [comment]
Do the plugins/providers need an upgrade or is it okay to only do the base package?

**Pull request merged**
