### PR TITLE
swift: 5.5.3 -> 5.6.2

### PR DESCRIPTION
**Pull request by Trundle**
###### Description of changes

* Several new upstream releases
* Unbreak build
* Add myself as maintainer

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dduan** [comment]
Thanks for taking the time to do this!

I'm testing these changes out locally.

It appears that the SHA for swift-format needs an update.

**Comment by Trundle** [comment]
> Thanks for taking the time to do this!
> It appears that the SHA for swift-format needs an update.

Welcome! This PR took me quite a while and I changed from 5.6.1 to 5.6.2 at some point, so it's possible that some other SHAs need updates as well. Meanwhile, I updated the one for swift-format.

**Comment by dduan** [comment]
+1

Verified build on my Ubuntu setup. All validation tests pass. Simple programs compile and function as expected.

**Comment by dduan** [comment]
Great work! I recommend adding yourself as a maintainer @Trundle!

**Review by dduan — APPROVED** [review]

**Comment by trepetti** [comment]
Result of `nixpkgs-review pr 186476` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>swift</li>
  </ul>
</details>

**Review by trepetti — APPROVED** [review]
LGTM. Thank you for your work. Yes, it is a lot of work updating because of how Apple structures the subrepos and build, which make it basically impossible to automate. There are also some internal inconsistencies in how they invoke Python that don't comply with PEP 394.

**Comment by SuperSandro2000** [comment]
How is x86_64-linux failing but aarch64-linux succeeding?

**Comment by Trundle** [comment]
> How is x86_64-linux failing but aarch64-linux succeeding?

I haven't seen this before and the previous runs were all successful. Possibly a flaky test or some issue with the runner (e.g. out of memory)

**Comment by SuperSandro2000** [comment]
Maybe we should disable the test(s) that are flaky.

**Comment by dduan** [comment]
the failing test is `AutoDiff/compiler_crashers_fixed/sr14290-missing-debug-scopes-in-pullback-trampoline.swift`. Pretty random since this type of regression tests don't regress much. Nevertheless we may want to disable it.

**Comment by Trundle** [comment]
I personally think it's a bit hasty to call a test flaky if it only failed once for not-so-clear reasons, but if that is what is needed to move this PR forward, I'm happy to disable it.

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 186476` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>swift</li>
  </ul>
</details>

**Comment by navinkumarr** [comment]
Hi @Trundle , I am getting following error. Is there any plan to support this in future ?

```
error: Package ‘swift-5.6.2’ in /nix/store/1is4128ymlh2pd0amyq5hw8d1gm6im4h-source/pkgs/development/compilers/swift/default.nix:464 is not supported on ‘x86_64-darwin’, refusing to evaluate.
```

**Comment by dduan** [comment]
We never had Darwin support here. It would be a separate, none trivial support to enable it.

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Review by dduan — APPROVED** [review]

**Comment by stephank** [comment]
Darwin support is tracked in #37473.

**Pull request merged**
