### PR TITLE
[WIP] init: create /dev/root in stage 2 too

### PR DESCRIPTION
**Pull request by teto**
###### Motivation for this change
Solves (same problem)
https://github.com/NixOS/nixpkgs/issues/32406
https://github.com/NixOS/nixops/issues/795

Create the symlink /dev/root in stage2 as in some cases (like when /proc is not available) stage 1 can't create it. I moved the /proc/cmdline parsing after /proc gets mounted.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by teto** [comment]
Is there any reason to create the symlink in stage 1 ? maybe I could remove it from there so that it isn't done twice ?

**Comment by matthewbauer** [comment]
This looks like a good change though I'm not very knowledgeable in the Linux stage stuff.

/cc @domenkozar

**Comment by teto** [comment]
@matthewbauer thanks for the ping, If I deploy with a nixpkgs without this branch then I can't reboot the VM (that run with a host kernel) so that's annoying.

**Comment by teto** [comment]
Would love to have some feedback on this. The only drawback I see is the loss of some logging  if /proc/cmdline was correctly mounted and boot.debugtrace set. It can be solved by duplicating the boot.debutrace but I thought the extra complexity was not worth it.

**Comment by teto** [comment]
This seems too peculiar a problem to justify the change, I'll try to work around it with boot.postCommands or fix it via a nixops patch instead.

**Pull request closed without merging**
