### PR TITLE
[19.03] Linux 5.2

### PR DESCRIPTION
**Pull request by herrwiese**
###### Motivation for this change

Linux 5.1 (current `linuxPackages_latest`) is EOL and has not had stable updates for ~4 releases now, which is unfortunate.

I checked how this was done for the last non-LTS transitions and AFAICS 5.0 → 5.1 also happened after release of 19.03.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @NeQuissimus

### CODE REVIEW

**Review by NeQuissimus — APPROVED** [review]
Seems reasonable to me. Thanks for pinging me, I'll cherry-pick future updates.

**Comment by NeQuissimus** [comment]
@GrahamcOfBorg test kernel-latest

**Comment by fpletz** [comment]
@GrahamcOfBorg test kernel-latest

**Review by fpletz — APPROVED** [review]

**Comment by herrwiese** [comment]
»Build timed out after 1800 seconds.« Yeah, well… what now? :)

**Pull request merged**
