### PR TITLE
k3s_1_24: 1.24.10+k3s1 -> 1.24.12+k3s1

### PR DESCRIPTION
**Pull request by yajo**
###### Description of changes

Update.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yajo** [comment]
I can't build these derivations because my PC goes out of memory. Is there any way to tell bots to build them on CI and download the built binaries to check they work?

**Comment by euank** [comment]
I don't think there's a shared binary cache for ofborg on PRs: https://github.com/NixOS/ofborg/issues/68

I'm able to get it to build locally, but I run into a test failure for this change.

On master, tests pass, but on this PR, I get a failure:

```
$ nix build '.#k3s_1_24.tests.single-node'
error: builder for '/nix/store/zqy2a9c1jf1n28vjsja7vvyx346zmqpf-vm-test-run-k3s-1.24.12+k3s1-single-node.drv' failed with exit code 1;
       last 10 log lines:
       >     driver.run_tests()
       >   File "/nix/store/lm0dq5j8wa6dr8db5y8cpn1kfz0iiwqr-nixos-test-driver-1.1/lib/python3.10/site-packages/test_driver/driver.py", line 142, in run_tests
       >     self.test_script()
       >   File "/nix/store/lm0dq5j8wa6dr8db5y8cpn1kfz0iiwqr-nixos-test-driver-1.1/lib/python3.10/site-packages/test_driver/driver.py", line 138, in test_script
       >     exec(self.tests, symbols, None)
       >   File "<string>", line 14, in <module>
       >   File "/nix/store/lm0dq5j8wa6dr8db5y8cpn1kfz0iiwqr-nixos-test-driver-1.1/lib/python3.10/site-packages/test_driver/machine.py", line 598, in succeed
       >     raise Exception(f"command `{command}` failed (exit code {status})")
       > Exception: command `k3s kubectl wait --for 'condition=Ready' pod/test` failed (exit code 1)
       > kill vlan (pid 7)
       For full logs, run 'nix log /nix/store/zqy2a9c1jf1n28vjsja7vvyx346zmqpf-vm-test-run-k3s-1.24.12+k3s1-single-node.drv'.
```

Looking at the logs, it seems to be waiting for the node to show up. The failure is it waiting on the pod to run with the below being repeated:

```
machine # [   59.570226] k3s[920]: time="2023-04-10T13:10:24Z" level=info msg="Waiting for containerd startup: rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService"
machine # [   59.705364] k3s[920]: time="2023-04-10T13:10:24Z" level=info msg="Waiting for control-plane node machine startup: nodes \"machine\" not found"
machine # error: timed out waiting for the condition on pods/test
```

I can investigate the failure more later this week hopefully

**Comment by yajo** [comment]
I finally managed to build it by following [these instructions](https://stackoverflow.com/a/72935939/1468388).

I get these failure logs too: [error.log](https://github.com/NixOS/nixpkgs/files/11199428/error.log)

The important part seems to be:

    Waiting for containerd startup: rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService

Any clues on what's happening here? 🤔 

BTW why the bot failed the builds, but still left the CI as ✅ ? 👀

**Comment by yajo** [comment]
It might be related to the containerd upgrade. Could this work for us too? https://github.com/containerd/containerd/issues/7799#issuecomment-1453687538

**Comment by euank** [comment]
For older versions of k3s, we had to set `systemd.enableUnifiedCgroupHierarchy = false`.

That could be worth trying. If that fixes it, we can update the test to set that for this k3s version.

We could also try 1.24.13 and see if that fixes it, though the changelog doesn't look like it has anything related.

**Comment by euank** [comment]
Setting that didn't seem to make a difference on my machine :(
I think I won't actually have time to debug this one. I don't use k3s 1.24, and it goes EOL pretty soon regardless....

**Comment by wegank** [comment]
Already dropped in 23.05, closing.

**Pull request closed without merging**
