### PR TITLE
 nixos/transmission: allow prestart to create directories

### LINKED ISSUE #41643: Unable to change transmission service default download directory
## Issue description
I tried to change the default download directory, since it shouldn't be done in settings.json, but in the configuration.nix. Here's the relevant part of the configuration:
```
services.transmission = {
    enable = true;
    settings = {
      download-dir = "/mnt/disk1/Torrents/";
      rpc-whitelist = "127.0.0.1,192.168.*.*";
     };
  };
```

but when I do `sudo nixos-rebuild switch` I get the following:

warning: the following units failed: transmission.service

● transmission.service - Transmission BitTorrent Service
   Loaded: loaded (/nix/store/hg7d316iy1pn1n3nnk6084phl8ljc939-unit-transmission.service/transmission.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2018-06-07 20:31:33 CEST; 21ms ago
  Process: 26534 ExecStartPre=/nix/store/qi4b7qiych7xyhrbprrypf566iqcbdsy-transmission-pre-start (code=exited, status=1/FAILURE)
 Main PID: 765 (code=exited, status=0/SUCCESS)

Jun 07 20:31:33 hp-desktop qi4b7qiych7xyhrbprrypf566iqcbdsy-transmission-pre-start[26534]: + chmod 770 /var/lib/transmission
Jun 07 20:31:33 hp-desktop qi4b7qiych7xyhrbprrypf566iqcbdsy-transmission-pre-start[26534]: + for DIR in '/var/lib/transmission' '/var/lib/transmission/.config/transmission-daemon' '/mnt/disk1/Torrents/' '/var/lib/transmission/.incomplete'
Jun 07 20:31:33 hp-desktop qi4b7qiych7xyhrbprrypf566iqcbdsy-transmission-pre-start[26534]: + mkdir -p /var/lib/transmission/.config/transmission-daemon
Jun 07 20:31:33 hp-desktop qi4b7qiych7xyhrbprrypf566iqcbdsy-transmission-pre-start[26534]: + chmod 770 /var/lib/transmission/.config/transmission-daemon
Jun 07 20:31:33 hp-desktop qi4b7qiych7xyhrbprrypf566iqcbdsy-transmission-pre-start[26534]: + for DIR in '/var/lib/transmission' '/var/lib/transmission/.config/transmission-daemon' '/mnt/disk1/Torrents/' '/var/lib/transmission/.incomplete'
Jun 07 20:31:33 hp-desktop qi4b7qiych7xyhrbprrypf566iqcbdsy-transmission-pre-start[26534]: + mkdir -p /mnt/disk1/Torrents/
Jun 07 20:31:33 hp-desktop qi4b7qiych7xyhrbprrypf566iqcbdsy-transmission-pre-start[26534]: mkdir: cannot create directory ‘/mnt/disk1/Torrents/’: Permission denied
Jun 07 20:31:33 hp-desktop systemd[1]: transmission.service: Control process exited, code=exited status=1
Jun 07 20:31:33 hp-desktop systemd[1]: transmission.service: Failed with result 'exit-code'.
Jun 07 20:31:33 hp-desktop systemd[1]: Failed to start Transmission BitTorrent Service.
warning: error(s) occurred while switching to the new configuration

### Steps to reproduce
Mentioned above. 
Change transmission service's default directory in configuration.nix and try to rebuild.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.39, NixOS, 18.09pre139319.1d9330d63a5 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixos-18.09pre139319.1d9330d63a5"`
 - channels(savo): `"nixos-17.09pre106916.c5badb123a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

### PR DESCRIPTION
**Pull request by emmanuelrosa**
###### Motivation for this change

This change executes the systemd transmission service pre-start script as `root`
so that it's able to create any directories specified in the configuration. In addition,
a smoke-test is added to the existing tests.

###### Pre-start script

* Directories leading to a given directory are created (if missing) in mode 775 and owned by root (this is new).
* If the final directory does not exist:
  * Mode set to 770 (left unchanged)
  * ~~Group is changed to `transmission` (changed).~~
  * Owner and group are changed to `transmission` (changed).
  * ~~Ownership is left unchanged; Hence if the directory had to be created the file it will be owned by root.~~

Note that this does not guarantee that the directories are accessible by
transmission. For example, if the `download-dir` is set to `/home/alice/torrents`
the pre-start script will be able to create the directory, but because
`/home/alice` is owned by user `alice` and the mode is 700, transmission
won't be able to access it (since it runs under the user `transmission`).

###### Smoke-test

This change also updates the transmission NixOS test to attempt downloading a torrent.
The purpose is to ensure the transmission daemon can access its directories. 

For example, by default adding a torrent via `transmission-remote` causes the daemon
to save the .torrent file to /var/lib/transmission/.config/torrents

The download is cancelled right after it's started.

Closes #41643

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - ~[ ] macOS~
   - ~[ ] other Linux distributions~
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

The command `nix path-info -S nixos/tests -f transmission.nix` produced: `error: path '/nix/store/5fzg0xpyhx82slw7i7d5761bkh9k3s8q-vm-test-run-transmission' is not valid` I don't know how to determine the closure size for this change.

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
@GrahamcOfBorg test transmission

**Comment by bb2020** [comment]
I think the service should not create the `fullSettings.download-dir` and `fullSettings.incomplete-dir` directories. These directories may be mounted after system init and if so the service will always crash while starting. Furthermore transmission itself creates them before a file write.

**Comment by bb2020** [comment]
It looks like `chgrp` may not be enough, the ownership should also be changed.

**Comment by emmanuelrosa** [comment]
755/drwxr-xr-x is used because when the directories are created the absolute path is specified along with the "-p" option, causing `mkdir` to create any necessary parent directories. Those parent directories (/home, /var, etc) most likely would be 755. 770 is only used on the final directory in the path since that's the directory transmission should be writing to. Leaving the owner as root was probably an oversight on my part, so thank you for bringing it to my attention.

**Comment by bb2020** [comment]
Oh, you have a `chmod 770` beneath `mkdir`, sorry I did not see it.
`chown transmission:transmission` instead of `chgrp` looks like the way to go then.

**Pull request closed without merging**
