### PR TITLE
Add additional vim plugins

### PR DESCRIPTION
**Pull request by RonanMacF**
- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
markbar is failing, I create https://github.com/Yilin-Yang/vim-markbar/pull/23 to fix it.

```
builder for '/nix/store/1rx1hdsw7mpig83x1ndqkfgr9afmarky-vimplugin-vim-markbar-2020-05-10.drv' failed with exit code 1; last 10 log lines:
  unpacking sources
  unpacking source archive /nix/store/qfl0s4jazv3ar4whrxzqjvvbgy100qfp-source
  source root is source
  patching sources
  configuring
  building
  installing
  Building help tags
  Error detected while processing command line:
  E154: Duplicate tag "g:markbar_foldopen" in file /nix/store/1xvh545n22z6x4amsa1824jiy0girh09-vimplugin-vim-markbar-2020-05-10/share/vim-plugins/vim-markbar/doc/vim-markbar.txtFailed to build help tags!
cannot build derivation '/nix/store/xpgyqpxzyrnvnr7k3001fj1xf8d1v2zw-env.drv': 1 dependencies couldn't be built
[5 built (1 failed), 0.0 MiB DL]
error: build of '/nix/store/xpgyqpxzyrnvnr7k3001fj1xf8d1v2zw-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/96044
1 package failed to build:
vimPlugins.vim-markbar

2 packages built:
vimPlugins.vim-merginal vimPlugins.vim-twiggy
```

**Comment by jonringer** [comment]
there's some merge conficts, do you mind rebasing?

Also, if we don't want to wait for upstream to merge my PR, you can add it as a patch in `overrides.nix`

**Comment by RonanMacF** [comment]
Cheers for looking into that Jon, i'll keep an eye on the PR on markbar and once it merges i'll rebase and push again! Thanks for the follow up

**Comment by jonringer** [comment]
you should be able to update and have it work fine.

**Comment by RonanMacF** [comment]
Should be good to go now!

**Comment by jonringer** [comment]
for git history, do you mind doing `git pull -r` instead of merging :)

or use `git rebase -i`, drop the update and merge commits, then do a new update :)

**Comment by RonanMacF** [comment]
Think that should be good to now.

**Comment by jonringer** [comment]
changes were included in  #96862

**Pull request closed without merging**
