### PR TITLE
Change the preset networking.hostId to use `mkDefault` so it can be easily changed by the user later.

### PR DESCRIPTION
**Pull request by CMCDragonkai**
I'm not sure, but I get the feeling that the `lib` argument can just be added and everything will work?

### CODE REVIEW

**Comment by nbp** [comment]
Yes, the `lib` attribute is given to all modules, as it is needed for creating properties and options.
This patch looks good to me, and I see no references to hostId which might need any additional patching.

Still I think it might be good if you can provide additional documentation to ZFS to mention that the `hostId` should be changed if we want to use multiple instance (as I understand).

**Comment by CMCDragonkai** [comment]
Where would you suggest to add that extra documentation? In the `hostId` comment section in the appendix?

**Comment by nbp** [comment]
I would add it next to the ZFS documentation if we have any.

**Comment by CMCDragonkai** [comment]
There isn't any ZFS specific documentation in the manuals. There's only some in the wikis. But they are not really up-to-date. I'm working on a tutorial to setup ZFS on NixOS actually, will be releasing it once I have it all working.

**Comment by nbp** [comment]
Currently we have a few manual pages which are using the new style of writing documentation, such as postgres [1] and nixos path [2].

The idea would be to add a file named `zfs.xml` [3] next to the module `zfs.nix` and to include this documentation next to luks encryption [4] of the file system.

Feel free to open a new issue for that.

[1] https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/databases/postgresql.xml
[2] https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/misc/nixos.xml (see also https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/misc/nixos.nix#L78-L79)
[3] https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/tasks/filesystems/zfs.nix
[4] https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/configuration/file-systems.xml

**Pull request merged**
