### PR TITLE
racket: 7.9 -> 8.0

### PR DESCRIPTION
**Pull request by iblech**
###### Things done

Note: The wrapped binary `mzscheme` does not work (aborts with a core dump): It tries to read a certain portion of `$0`, but this fails because `$0` points to the much shorter wrapper script instead of the larger true binary (and even if the wrapper script would be longer, the bytes it would read from the wrapper script would probably not be what mzscheme is expecting). **This problem is not a regression, but occurs also with the current nixpkgs version of racket.** A solution is to change `exec -a "$0"` in the wrapper script to `exec "$0"`. Does anyone know how to do this in a non-hacky way? The binaries `racket` and `drracket` work just fine.

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
mzscheme tries to read some bytes from the binary in $0 which in our case does not match the real binary name. If we remove the -a then the binary name is wrong. I think this is an upstream bug which needs some patching. The file is https://github.com/racket/racket/blob/v8.0/racket/src/bc/main.c or some included file but I don't know where it tries to read it. It would be cool if we could replace the read of $0 with a better way or just hardcode the binary instead of removing the exec -a.

**Review by mohe2015 — APPROVED** [review]
Builds and runs a program I wrote for university some time ago.

**Comment by iblech** [comment]
Thank you for the analysis, @SuperSandro2000! I opened an upstream issue: https://github.com/racket/racket/issues/3685

And thank you for the confirmation, @mohe2015 :-)

**Comment by marsam** [comment]
@GrahamcOfBorg build racket-minimal

**Comment by SuperSandro2000** [comment]
My c is terrible but I think we can just patch https://github.com/racket/racket/blob/master/racket/src/cs/c/main.c#L434 from ``  char *exec_file = argv[0], *run_file = NULL;`` to ``  char *exec_file = "mzscheme", *run_file = NULL;``

**Comment by iblech** [comment]
I thought so too, but the problem is that not only `mzscheme`, but also `mzred` is impacted from the problem. So hardcoding `mzscheme` is not going to work...

**Pull request merged**
