### PR TITLE
acme-client: 0.2.5 -> 1.0.1

### PR DESCRIPTION
**Pull request by ruuda**
###### Motivation for this change

[A new version has been released upstream.](https://github.com/graywolf/acme-client-portable/releases/tag/v1.0.0)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Initially this pull request was for version 1.0.0, which needed a small patch for a missing include. This has now been fixed upstream in version 1.0.1, and I have updated this pull request accordingly.

### CODE REVIEW

**Comment by graywolf** [comment]
1.0.1 is out and includes your patch. I would also suggest using tar balls from https://data.wolfsden.cz/sources/, it will allow you to skip the `autoreconf` step in your build process.

**Comment by ruuda** [comment]
> 1.0.1 is out and includes your patch.

Thanks for the quick release! I updated this pull request.

> I would also suggest using tar balls from https://data.wolfsden.cz/sources/, it will allow you to skip the autoreconf step in your build process.

I did not know about these sources, thanks for the suggestion. That is a nice simplification of the package, I added that to this PR.

@pmahoney, could you please take a look?

**Review by pmahoney — APPROVED** [review]
Looks good.

@graywolf is that URL preferable to, e.g. https://git.sr.ht/~graywolf/acme-client-portable/archive/v1.0.1.tar.gz ?  Is it documented somewhere other than your comment above?

**Comment by graywolf** [comment]
In general yes, it is preferable, since it is output of `make dist` with all
the implications. It is *not* documented anywhere, which is a good point. I
should probably put the link somewhere.

**Pull request merged**
