### PR TITLE
akkoma: Backport #300343 to release 23.11

### PR DESCRIPTION
**Pull request by tcmal**
## Description of changes

Manual backport of #300343 to release 23.11.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by illdefined** [comment]
I noticed a number of non‐functional changes to formatting inconsistent with the rest of the files, for example: <https://github.com/NixOS/nixpkgs/pull/303733/files#diff-9a3a1a75457221f8bb90ae13db288c63d6b452bb58e332abc52203504372f70dL112> or <https://github.com/NixOS/nixpkgs/pull/303733/files#diff-9a3a1a75457221f8bb90ae13db288c63d6b452bb58e332abc52203504372f70dL73>. It does not matter to me personally, but I suspect that these may have been introduced unintentionally.

I ran the tests locally and was unable to reproduce the issue with the confined test we experienced on master. The module tests both pass consistently.

I wondered if it makes sense to mention this update in the 23.11 release notes with respect to the security implications of serving media from the same domain. I don’t think it is strictly necessary as this update does not break anything, and I do not have a strong opinion on it.

Thank you for taking care of this update, @tcmal.

**Review by illdefined — APPROVED** [review]

**Review by cafkafk — APPROVED** [review]

**Comment by jrick** [comment]
I'm seeing these errors building release-23.11 which look related to this backport.  I don't use akkoma or pleroma.

```
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/whbaz13z7ag2wz9prrbs3xz34qrnry5r-lazy-options.json.drv^*'
error:
       … while evaluating attribute 'services.akkoma.config.":pleroma".":media_proxy".base_url'

         at /nix/store/qh92r1qsj83hq20a4r07m24v5bjjq26b-nixos/lib/make-options-doc/default.nix:94:63:

           93|
           94|   optionsNix = builtins.listToAttrs (map (o: { name = o.name; value = removeAttrs o ["name" "visible" "internal"]; }) optionsList);
             |                                                               ^
           95|

       … while evaluating attribute 'default'

         at /nix/store/4s6k687zxxfmd1qhwqggkv1vrwp103yq-lib/options.nix:326:11:

          325|         // optionalAttrs (opt ? defaultText || opt ? default) {
          326|           default =
             |           ^
          327|             builtins.addErrorContext "while evaluating the ${if opt?defaultText then "defaultText" else "default value"} of option `${name}`" (

       … while calling the 'addErrorContext' builtin

         at /nix/store/4s6k687zxxfmd1qhwqggkv1vrwp103yq-lib/options.nix:327:13:

          326|           default =
          327|             builtins.addErrorContext "while evaluating the ${if opt?defaultText then "defaultText" else "default value"} of option `${name}`" (
             |             ^
          328|               renderOptionValue (opt.defaultText or opt.default)

       … while evaluating the default value of option `services.akkoma.config.":pleroma".":media_proxy".base_url`

       … from call site

         at /nix/store/4s6k687zxxfmd1qhwqggkv1vrwp103yq-lib/options.nix:328:15:

          327|             builtins.addErrorContext "while evaluating the ${if opt?defaultText then "defaultText" else "default value"} of option `${name}`" (
          328|               renderOptionValue (opt.defaultText or opt.default)
             |               ^
          329|             );

       … while calling 'renderOptionValue'

         at /nix/store/4s6k687zxxfmd1qhwqggkv1vrwp103yq-lib/options.nix:365:23:

          364|   */
          365|   renderOptionValue = v:
             |                       ^
          366|     if v ? _type && v ? text then v

       error: attribute 'services' missing

       at /nix/store/qh92r1qsj83hq20a4r07m24v5bjjq26b-nixos/modules/services/web-apps/akkoma.nix:5:9:

            4| let
            5|   cfg = config.services.akkoma;
             |         ^
            6|   ex = cfg.config;
Cacheable portion of option doc build failed.
Usually this means that an option attribute that ends up in documentation (eg `default` or `description`) depends on the restricted module arguments `config` or `pkgs`.

Rebuild your configuration with `--show-trace` to find the offending location. Remove the references to restricted arguments (eg by escaping their antiquotations or adding a `defaultText`) or disable the sandboxed build for the failing module by setting `meta.buildDocsInSandbox = false`.
```

**Review by cafkafk — COMMENTED** [review]
`"Pleroma.Upload"` and `base_url` might need a `defaultText`, but it's odd that it was not caught by tests, maybe the state version for testing was 24.05, so the null was fine?

**Comment by mweinelt** [comment]
> `"Pleroma.Upload"` and `base_url` might need a `defaultText`, but it's odd that it was not caught by tests, maybe the state version for testing was 24.05, so the null was fine?

Can you send a fix and ping me?

**Comment by vcunat** [comment]
This is blocking 23.11 channels now, e.g.
https://hydra.nixos.org/eval/1805686

**Comment by cafkafk** [comment]
> > `"Pleroma.Upload"` and `base_url` might need a `defaultText`, but it's odd that it was not caught by tests, maybe the state version for testing was 24.05, so the null was fine?
> 
> Can you send a fix and ping me?

something like this might work, couldn't figure out how to reproduce the issue locally so I'm not sure:
```diff
diff --git a/nixos/modules/services/web-apps/akkoma.nix b/nixos/modules/services/web-apps/akkoma.nix
index b2b2c53f2fce..6f16eec9d8ee 100644
--- a/nixos/modules/services/web-apps/akkoma.nix
+++ b/nixos/modules/services/web-apps/akkoma.nix
@@ -777,6 +777,11 @@ in {
                     default = if lib.versionOlder config.system.stateVersion "24.05"
                               then "${httpConf.scheme}://${httpConf.host}:${builtins.toString httpConf.port}/media/"
                               else null;
+                    defaultText = literalExpression ''
+                      if lib.versionOlder config.system.stateVersion "24.05"
+                      then "${httpConf.scheme}://${httpConf.host}:${builtins.toString httpConf.port}/media/"
+                      else null;
+                    '';
                     description = mdDoc ''
                       Base path which uploads will be stored at.
                       Whilst this can just be set to a subdirectory of the main domain, it is now recommended to use a different subdomain.
@@ -818,6 +823,11 @@ in {
                     default = if lib.versionOlder config.system.stateVersion "24.05"
                               then "${httpConf.scheme}://${httpConf.host}:${builtins.toString httpConf.port}/media/"
                               else null;
+                    defaultText = literalExpression ''
+                      if lib.versionOlder config.system.stateVersion "24.05"
+                      then "${httpConf.scheme}://${httpConf.host}:${builtins.toString httpConf.port}/media/"
+                      else null;
+                    '';
                     description = mdDoc ''
                       Base path for the media proxy.
                       Whilst this can just be set to a subdirectory of the main domain, it is now recommended to use a different subdomain.
```

I'll have more time to look after work. This should probably also be added to the original pr if it works.

**Comment by vcunat** [comment]
> couldn't figure out how to reproduce the issue locally

In nixpkgs checkout you simply run e.g.
```bash
nix build -f nixos/release.nix options
```

**Comment by cafkafk** [comment]
> > couldn't figure out how to reproduce the issue locally
> 
> In nixpkgs checkout you simply run e.g.
> 
> ```shell
> nix build -f nixos/release.nix options
> ```
> 
> EDIT: or generally, if I should follow the linked Hydra job more precisely, it would be a bit longer equivalent:
> 
> ```shell
> nix build -f nixos/release-combined.nix nixos.options
> ```

Thanks, did reveal a small issue with my fix, but this seems to work:
```diff
diff --git a/nixos/modules/services/web-apps/akkoma.nix b/nixos/modules/services/web-apps/akkoma.nix
index b2b2c53f2fce..6cc93194961c 100644
--- a/nixos/modules/services/web-apps/akkoma.nix
+++ b/nixos/modules/services/web-apps/akkoma.nix
@@ -777,6 +777,11 @@ in {
                     default = if lib.versionOlder config.system.stateVersion "24.05"
                               then "${httpConf.scheme}://${httpConf.host}:${builtins.toString httpConf.port}/media/"
                               else null;
+                    defaultText = literalExpression ''
+                      if lib.versionOlder config.system.stateVersion "24.05"
+                      then "$\{httpConf.scheme}://$\{httpConf.host}:$\{builtins.toString httpConf.port}/media/"
+                      else null;
+                    '';
                     description = mdDoc ''
                       Base path which uploads will be stored at.
                       Whilst this can just be set to a subdirectory of the main domain, it is now recommended to use a different subdomain.
@@ -809,6 +814,7 @@ in {
                 enabled = mkOption {
                     type = types.bool;
                     default = false;
+                    defaultText = literalExpression "false";
                     description = mdDoc ''
                       Whether to enable proxying of remote media through the instance's proxy.
                     '';
@@ -818,6 +824,11 @@ in {
                     default = if lib.versionOlder config.system.stateVersion "24.05"
                               then "${httpConf.scheme}://${httpConf.host}:${builtins.toString httpConf.port}/media/"
                               else null;
+                    defaultText = literalExpression ''
+                      if lib.versionOlder config.system.stateVersion "24.05"
+                      then "$\{httpConf.scheme}://$\{httpConf.host}:$\{builtins.toString httpConf.port}/media/"
+                      else null;
+                    '';
                     description = mdDoc ''
                       Base path for the media proxy.
                       Whilst this can just be set to a subdirectory of the main domain, it is now recommended to use a different subdomain.
```

**Pull request merged**
