### PR TITLE
perlPackages.PLS: init at 0.897

### PR DESCRIPTION
**Pull request by Artturin**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
Result of `nixpkgs-review pr 150596` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>libsForQt512.kpat</li>
    <li>libsForQt514.kpat</li>
  </ul>
</details>
<details>
  <summary>55 packages built:</summary>
  <ul>
    <li>freecell-solver</li>
    <li>gnome.aisleriot</li>
    <li>libsForQt5.kpat (libsForQt515.kpat ,plasma5Packages.kpat)</li>
    <li>perl532Packages.CLIHelpers</li>
    <li>perl532Packages.DistZillaPluginBundleTestingMania</li>
    <li>perl532Packages.DistZillaPluginTestCompile</li>
    <li>perl532Packages.DistZillaPluginTestMinimumVersion</li>
    <li>perl532Packages.DistZillaPluginTestPerlCritic</li>
    <li>perl532Packages.Future</li>
    <li>perl532Packages.FutureAsyncAwait</li>
    <li>perl532Packages.IOAsync</li>
    <li>perl532Packages.IOAsyncSSL</li>
    <li>perl532Packages.NetAsyncHTTP</li>
    <li>perl532Packages.NetAsyncPing</li>
    <li>perl532Packages.NetAsyncWebSocket</li>
    <li>perl532Packages.PLS</li>
    <li>perl532Packages.PPR</li>
    <li>perl532Packages.PerlCritic</li>
    <li>perl532Packages.PerlCriticCommunity</li>
    <li>perl532Packages.PerlCriticMoose</li>
    <li>perl532Packages.PerlCriticPolicyVariablesProhibitLoopOnHash</li>
    <li>perl532Packages.PerlCriticPulp</li>
    <li>perl532Packages.PerlMinimumVersion</li>
    <li>perl532Packages.PerlTidy</li>
    <li>perl532Packages.TaskFreecellSolverTesting</li>
    <li>perl532Packages.TestMinimumVersion</li>
    <li>perl532Packages.TestPerlCritic</li>
    <li>perl532Packages.TestPerlTidy</li>
    <li>perl534Packages.CLIHelpers</li>
    <li>perl534Packages.DistZillaPluginBundleTestingMania</li>
    <li>perl534Packages.DistZillaPluginTestCompile</li>
    <li>perl534Packages.DistZillaPluginTestMinimumVersion</li>
    <li>perl534Packages.DistZillaPluginTestPerlCritic</li>
    <li>perl534Packages.Future</li>
    <li>perl534Packages.FutureAsyncAwait</li>
    <li>perl534Packages.IOAsync</li>
    <li>perl534Packages.IOAsyncSSL</li>
    <li>perl534Packages.NetAsyncHTTP</li>
    <li>perl534Packages.NetAsyncPing</li>
    <li>perl534Packages.NetAsyncWebSocket</li>
    <li>perl534Packages.PLS</li>
    <li>perl534Packages.PPR</li>
    <li>perlcritic (perl534Packages.PerlCritic)</li>
    <li>perl534Packages.PerlCriticCommunity</li>
    <li>perl534Packages.PerlCriticMoose</li>
    <li>perl534Packages.PerlCriticPolicyVariablesProhibitLoopOnHash</li>
    <li>perl534Packages.PerlCriticPulp</li>
    <li>perl534Packages.PerlMinimumVersion</li>
    <li>perl534Packages.PerlTidy</li>
    <li>perl534Packages.TaskFreecellSolverTesting</li>
    <li>perl534Packages.TestMinimumVersion</li>
    <li>perl534Packages.TestPerlCritic</li>
    <li>perl534Packages.TestPerlTidy</li>
    <li>pysolfc</li>
    <li>tlp</li>
  </ul>
</details>

**Comment by stigtsp** [comment]
@GrahamcOfBorg build perlPackages.PLS

**Comment by Artturin** [comment]
@stigtsp  i used your script to generate the PPR and PLS entries :smile:  https://github.com/stigtsp/nix-update-cpan

**Comment by stigtsp** [comment]
> @stigtsp i used your script to generate the PPR and PLS entries smile https://github.com/stigtsp/nix-update-cpan

Nice! It needs some more work but happy to hear that it was useful.

**Review by stigtsp — APPROVED** [review]
LGTM

**Pull request merged**
