### PR TITLE
urxvt_bidi: init at 2.15

### PR DESCRIPTION
**Pull request by doronbehar**
###### Motivation for this change

Add a very useful plugin to urxvt - https://github.com/mkamensky/Text-Bidi .

###### Things done

All things done below were tested with #70310 merged, hence it's a requirement for this to get merged.

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @rnhmjoj as you are the maintainer of urxvt.

### CODE REVIEW

**Comment by rnhmjoj** [comment]
Thank you, I've just tested and it works. Everything looks good.
I'm not sure about enabling it by default, the closure increase is pretty small (≈1MB), though.

**Comment by doronbehar** [comment]
TBH I wouldn't care much, it's just that it's a little bit nontrivial for this package to be added to the plugin's list because of the `perlDeps` which needs to have `urxvt_bidi` as well. I wanted to show for anyone who may read the definition of `rxvt_unicode-with-plugins` and that may want to specify his own plugins in his config, that this is needed.

Would you be satisfied if I would leave an appropriate comment instead?

**Comment by rnhmjoj** [comment]
> TBH I wouldn't care much, it's just that it's a little bit nontrivial for this package to be added to the plugin's list because of the perlDeps which needs to have urxvt_bidi as well.

Yes, definitely: I intend to rewrite the plugin system to handle dependencies for this reason.

> Would you be satisfied if I would leave an appropriate comment instead?

No, you're right: It's better this way until there is a way for a plugin to export perl dependencies, not many people look at the source code anyway.

**Comment by doronbehar** [comment]
Oh right so I'll leave it as is. Do you have write permissions to the nixpkgs?

**Review by rnhmjoj — APPROVED** [review]

**Comment by rnhmjoj** [comment]
> Oh right so I'll leave it as is. Do you have write permissions to the nixpkgs?

No, sorry. I'll try to get attention.

**Comment by veprbl** [comment]
@GrahamcOfBorg build rxvt_unicode-with-plugins urxvt_bidi

**Pull request merged**
