### PR TITLE
`lib`: Remove unneeded polyfills

### PR DESCRIPTION
**Pull request by infinisil**
## Description of changes

Nix 2.3 (the minimum version needed to evaluate Nixpkgs) supports these, so no need to keep them around.

Ping @roberth 

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by infinisil** [comment]
I'll merge this myself soon if nobody else does before

**Review by roberth — COMMENTED** [review]
- :heavy_check_mark: All builtins exist in the latest 2.3; 2.3.17.
- :question: How about `2.3` proper?
- :heavy_check_mark: `zip-int-bits.nix` does not have other imports in Nixpkgs, and almost all files are not entrypoints, as usual.

**Comment by roberth** [comment]
Sorry, got stuck on a 2.3 build failure when I looked at this originally.

**Comment by infinisil** [comment]
Was able to confirm that the first 2.3 in Nixpkgs also supported all these builtins.

Was easy to find a pre-built version with [this page](https://lazamar.co.uk/nix-versions/?package=nix&version=2.3&fullName=nix-2.3&keyName=nixStable&revision=d93fb7b27207ae63a2e5c5b878f249a5a9fd9dd6&channel=nixpkgs-unstable#instructions) :)

**Pull request merged**
