### PR TITLE
nodejs: 14.21.1 -> 14.21.2, 16.18.1 -> 16.19.0, 18.12.1 -> 18.13.0, 19.2.0 -> 19.4.0

### PR DESCRIPTION
**Pull request by anthonyroussel**
###### Description of changes

* https://nodejs.org/en/blog/release/v19.4.0/
* https://nodejs.org/en/blog/release/v19.3.0/
* https://nodejs.org/en/blog/release/v18.13.0/
* https://nodejs.org/en/blog/release/v16.19.0/
* https://nodejs.org/en/blog/release/v14.21.2/

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by marsam** [comment]
Thank you!  Please target `staging-next`

**Comment by anthonyroussel** [comment]
> Thank you! Please target it to `staging-next`

@marsam Thanks for the review. I retargeted the PR to staging-next.

**Comment by anthonyroussel** [comment]
Fixed the failing build for nodejs-19_x, cause was patches in pkgs/development/web/nodejs/npm-patches.nix are now useless for nodejs-19_x because they are merged upstream.

They are still required for NodeJS 14, 16, 18 however.

**Comment by anthonyroussel** [comment]
Rebased my branch against staging-next.

**Review by marsam — APPROVED** [review]
Thank you!

**Comment by winterqt** [comment]
Hi @marsam, just checking: do you remember why you sent this directly into an active -next? It doesn't seem to be security related. Thanks!

**Comment by marsam** [comment]
Hi, I suggested to send it to `staging-next` because Node v19.3.0 updated npm to 9.2.0, and `staging-next` had `npmPatches` which were backports of npm 9. 
If this PR landed to master first, it would break `nodejs-19_x` when `staging-next` is merged since it merges cleanly, even though `npmPatches` were conflicting.

**Pull request merged**
