### PR TITLE
mpv: fix build on darwin

### LINKED ISSUE #345516: Build failure: mpv
### Steps To Reproduce

1. Fetch latest `master`
1. Run `nix-build -A pkgs.mpv`

### Build log

```
FAILED: osdep/mac/swift.swiftmodule osdep/mac/swift.h osdep/mac/swift.o 
/nix/store/mms5vi0wxy511i9faihkrzalzpfk0gfi-swift-wrapper-5.8/bin/swift -frontend -c -sdk /nix/store/chm77nb9a51ys9hkwybv9gydai8cjz7c-SDKs/MacOSX11.0.sdk -enable-objc-interop -emit-objc-header -parse-as-library -O -D HAVE_MACOS_10_15_4_FEATURES -D HAVE_MACOS_11_FEATURES -D HAVE_MACOS_COCOA_CB -D HAVE_MACOS_TOUCHBAR -D HAVE_MACOS_MEDIA_PLAYER -module-name swift -emit-module-path osdep/mac/swift.swiftmodule -import-objc-header /private/tmp/nix-build-mpv-0.39.0.drv-0/source/osdep/mac/app_bridge_objc.h -emit-objc-header-path osdep/mac/swift.h -o osdep/mac/swift.o ../osdep/mac/application.swift ../osdep/mac/app_hub.swift ../osdep/mac/event_helper.swift ../osdep/mac/input_helper.swift ../osdep/mac/libmpv_helper.swift ../osdep/mac/log_helper.swift ../osdep/mac/menu_bar.swift ../osdep/mac/option_helper.swift ../osdep/mac/precise_timer.swift ../osdep/mac/presentation.swift ../osdep/mac/swift_compat.swift ../osdep/mac/swift_extensions.swift ../osdep/mac/type_helper.swift ../video/out/mac/common.swift ../video/out/mac/title_bar.swift ../video/out/mac/view.swift ../video/out/mac/window.swift ../video/out/cocoa_cb_common.swift ../video/out/mac/gl_layer.swift ../osdep/mac/remote_command_center.swift ../osdep/mac/touch_bar.swift -I. -I/private/tmp/nix-build-mpv-0.39.0.drv-0/source -I/nix/store/409zncmgji52kg643w8b2fymn0zl9hmp-libplacebo-7.349.0/include -I/nix/store/10ylmxvkisc5l75n0m0lmhr2hw3cyn68-ffmpeg-6.1.2-dev/include
../osdep/mac/input_helper.swift:77:14: error: value of type 'NSCondition' has no member 'withLock'
        lock.withLock {
        ~~~~ ^~~~~~~~
```

### Additional context

It was reported originally in https://github.com/mpv-player/mpv/issues/13763, it seems to be an issue with the version of Swift that's being used.

### Notify maintainers

@AndersonTorres
@fpletz
@globin
@ma27

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.0.0, macOS 15.0`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixpkgs"`
 - channels(user): `"home-manager, nixpkgs"`
 - nixpkgs: `~/.nix-defexpr/channels/nixpkgs`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by winterqt**
## Description of changes

Closes #345516.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 345600`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 1 package marked as broken and skipped:</summary>
  <ul>
    <li>ytui-music</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 116 packages built:</summary>
  <ul>
    <li>adl</li>
    <li>ani-cli</li>
    <li>anilibria-winmaclinux</li>
    <li>anime-downloader</li>
    <li>anime-downloader.dist</li>
    <li>anki</li>
    <li>anki.dist</li>
    <li>anki.doc</li>
    <li>anki.man</li>
    <li>castero</li>
    <li>castero.dist</li>
    <li>celluloid</li>
    <li>cplay-ng</li>
    <li>cplay-ng.dist</li>
    <li>curseradio</li>
    <li>curseradio.dist</li>
    <li>deepin.dde-gsettings-schemas</li>
    <li>deepin.deepin-movie-reborn</li>
    <li>deepin.deepin-movie-reborn.dev</li>
    <li>deepin.deepin-voice-note</li>
    <li>delfin</li>
    <li>dmlive</li>
    <li>dra-cla</li>
    <li>ff2mpv</li>
    <li>ff2mpv-go</li>
    <li>finamp</li>
    <li>finamp.debug</li>
    <li>finamp.pubcache</li>
    <li>flet-client-flutter</li>
    <li>flet-client-flutter.debug</li>
    <li>flet-client-flutter.pubcache</li>
    <li>gonic</li>
    <li>gtk-pipe-viewer</li>
    <li>gtk-pipe-viewer.devdoc</li>
    <li>haruna</li>
    <li>hydrus</li>
    <li>hydrus.doc</li>
    <li>hypnotix</li>
    <li>invidtui</li>
    <li>jellyfin-media-player</li>
    <li>jellyfin-mpv-shim</li>
    <li>jellyfin-mpv-shim.dist</li>
    <li>jftui</li>
    <li>kdePackages.mpvqt</li>
    <li>kdePackages.mpvqt.debug</li>
    <li>kdePackages.mpvqt.dev</li>
    <li>kdePackages.mpvqt.devtools</li>
    <li>kdePackages.plasmatube</li>
    <li>kdePackages.plasmatube.debug</li>
    <li>kdePackages.plasmatube.dev</li>
    <li>kdePackages.plasmatube.devtools</li>
    <li>kdePackages.tokodon</li>
    <li>kdePackages.tokodon.debug</li>
    <li>kdePackages.tokodon.dev</li>
    <li>kdePackages.tokodon.devtools</li>
    <li>ki</li>
    <li>ki.dist</li>
    <li>klipperscreen</li>
    <li>libsForQt5.plasmatube (plasma5Packages.plasmatube)</li>
    <li>libsForQt5.tokodon (plasma5Packages.tokodon)</li>
    <li>memento</li>
    <li>minitube</li>
    <li>mnemosyne</li>
    <li>mnemosyne.dist</li>
    <li>mov-cli</li>
    <li>mov-cli.dist</li>
    <li>mpc-qt</li>
    <li>mpv</li>
    <li>mpv-unwrapped</li>
    <li>mpv-unwrapped.dev</li>
    <li>mpv-unwrapped.doc</li>
    <li>mpv-unwrapped.man</li>
    <li>mpvScripts.inhibit-gnome</li>
    <li>mpvScripts.mpris</li>
    <li>mpvpaper</li>
    <li>musicpod</li>
    <li>musicpod.debug</li>
    <li>musicpod.pubcache</li>
    <li>photoqt</li>
    <li>pipe-viewer</li>
    <li>pipe-viewer.devdoc</li>
    <li>plex-media-player</li>
    <li>plex-mpv-shim</li>
    <li>plex-mpv-shim.dist</li>
    <li>previewqt</li>
    <li>python311Packages.flet</li>
    <li>python311Packages.flet-runtime</li>
    <li>python311Packages.flet-runtime.dist</li>
    <li>python311Packages.flet.dist</li>
    <li>python311Packages.mpv</li>
    <li>python311Packages.mpv.dist</li>
    <li>python312Packages.flet</li>
    <li>python312Packages.flet-runtime</li>
    <li>python312Packages.flet-runtime.dist</li>
    <li>python312Packages.flet.dist</li>
    <li>python312Packages.mpv</li>
    <li>python312Packages.mpv.dist</li>
    <li>qimgv</li>
    <li>radio-cli</li>
    <li>radioboat</li>
    <li>somafm-cli</li>
    <li>spotube</li>
    <li>stremio</li>
    <li>sublime-music</li>
    <li>sublime-music.dist</li>
    <li>subtitleedit</li>
    <li>supersonic</li>
    <li>supersonic-wayland</li>
    <li>svp</li>
    <li>termusic</li>
    <li>tomato-c</li>
    <li>tsukimi</li>
    <li>wiliwili</li>
    <li>wtwitch</li>
    <li>youtube-tui</li>
    <li>ytfzf</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:fast_forward: 28 packages marked as broken and skipped:</summary>
  <ul>
    <li>anilibria-winmaclinux</li>
    <li>anki</li>
    <li>anki.dist</li>
    <li>anki.doc</li>
    <li>anki.man</li>
    <li>flet-client-flutter</li>
    <li>flet-client-flutter.debug</li>
    <li>flet-client-flutter.pubcache</li>
    <li>jellyfin-mpv-shim</li>
    <li>jellyfin-mpv-shim.dist</li>
    <li>ki</li>
    <li>ki.dist</li>
    <li>libsForQt5.tokodon</li>
    <li>mnemosyne</li>
    <li>mnemosyne.dist</li>
    <li>mpc-qt</li>
    <li>plasma5Packages.tokodon</li>
    <li>python311Packages.flet</li>
    <li>python311Packages.flet-runtime</li>
    <li>python311Packages.flet-runtime.dist</li>
    <li>python311Packages.flet.dist</li>
    <li>python312Packages.flet</li>
    <li>python312Packages.flet-runtime</li>
    <li>python312Packages.flet-runtime.dist</li>
    <li>python312Packages.flet.dist</li>
    <li>sublime-music</li>
    <li>sublime-music.dist</li>
    <li>ytui-music</li>
  </ul>
</details>
<details>
  <summary>:x: 3 packages failed to build:</summary>
  <ul>
    <li>gonic</li>
    <li>hydrus</li>
    <li>hydrus.doc</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 32 packages built:</summary>
  <ul>
    <li>ani-cli</li>
    <li>cplay-ng</li>
    <li>cplay-ng.dist</li>
    <li>curseradio</li>
    <li>curseradio.dist</li>
    <li>dmlive</li>
    <li>dra-cla</li>
    <li>ff2mpv-go</li>
    <li>gtk-pipe-viewer</li>
    <li>gtk-pipe-viewer.devdoc</li>
    <li>invidtui</li>
    <li>klipperscreen</li>
    <li>mov-cli</li>
    <li>mov-cli.dist</li>
    <li>mpv-unwrapped</li>
    <li>mpv-unwrapped.dev</li>
    <li>mpv-unwrapped.doc</li>
    <li>mpv-unwrapped.man</li>
    <li>pipe-viewer</li>
    <li>pipe-viewer.devdoc</li>
    <li>python311Packages.mpv</li>
    <li>python311Packages.mpv.dist</li>
    <li>python312Packages.mpv</li>
    <li>python312Packages.mpv.dist</li>
    <li>somafm-cli</li>
    <li>subtitleedit</li>
    <li>supersonic</li>
    <li>termusic</li>
    <li>tomato-c</li>
    <li>wtwitch</li>
    <li>youtube-tui</li>
    <li>ytfzf</li>
  </ul>
</details>

**Comment by winterqt** [comment]
gonic failing wasn't my fault, but why not fix it while we're at it (was failing b/c of Darwin sandbox). Hydrus tests also blow up in the sandbox; not a trivial fix, so I'm just leaving it for now.

**Comment by khaneliman** [comment]
> gonic failing wasn't my fault, but why not fix it while we're at it (was failing b/c of Darwin sandbox). Hydrus tests also blow up in the sandbox; not a trivial fix, so I'm just leaving it for now.

Wasn't expecting fixes for those in this PR, so thanks. Was mostly pointing out how many packages get unbroken on darwin from this PR.

**Comment by winterqt** [comment]
@JohnRTitor In the future, it would be nice to give the package maintainers even 24 hours to respond before you merge.

**Comment by winterqt** [comment]
@JohnRTitor Also, we were still waiting on an x86_64-darwin test run. *Please* be more careful before merging next time.

**Comment by autrimpo** [comment]
The gonic changes look good to me, thank you!

**Comment by JohnRTitor** [comment]
> @JohnRTitor In the future, it would be nice to give the package maintainers even 24 hours to respond before you merge.

Thanks I will keep that in my mind, changes looked good and I needed the fix to get merged for darwin, so I merged in haste. Will be more careful in future

(so used to just keeping an eye for linux checks and not looking at darwin checks as they fail often)

**Pull request merged**
