### PR TITLE
nixVersions.nix_2_25: init at 2.25.2

### PR DESCRIPTION
**Pull request by zowoq**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Mic92** [comment]
Things that need to be tested:

- [ ] nixpkgs-review on x86_64-linux
- [ ] nixpkgs-review on x86_64-darwin
- [ ] nixpkgs-review on aarch64-linux
- [ ] nixpkgs-review on aarch64-darwin
- [ ] passthru.tests

- [ ] Furthermore fallback-paths.nix needs to be updated (check update-all.sh or the README for how to do this.

**Comment by zowoq** [comment]
> I would suggest to split the PR into two. First one just adds 2.25 and the second one does the actual switch.

`nixVersions.latest: 2.24 -> 2.25` 

You want the `latest` bump moved to another PR?

**Comment by Mic92** [comment]
> You want the `latest` bump moved to another PR?

Yes I think this would speed up the process a bit.

**Comment by lovesegfault** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 355350`

---
### `aarch64-linux`
<details>
  <summary>:x: 5 packages failed to build:</summary>
  <ul>
    <li>nixVersions.nix_2_25</li>
    <li>nixVersions.nix_2_25.debug</li>
    <li>nixVersions.nix_2_25.dev</li>
    <li>nixVersions.nix_2_25.doc</li>
    <li>nixVersions.nix_2_25.man</li>
  </ul>
</details>

**Comment by lovesegfault** [comment]
It'd be nice if we started leveraging the new meson build system, I think

**Comment by lovesegfault** [comment]
Both failures are due to `tests/functional/ca/repl.sh` failing, and retrying does not seem to help.

**Comment by lovesegfault** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 355350`

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>nixVersions.nix_2_25</li>
    <li>nixVersions.nix_2_25.dev</li>
    <li>nixVersions.nix_2_25.doc</li>
    <li>nixVersions.nix_2_25.man</li>
  </ul>
</details>

**Comment by Mic92** [comment]
> It'd be nice if we started leveraging the new meson build system, I think, but that can happen in another PR as well

That's a bit more involved. @roberth has something for it in the works.

**Comment by Mic92** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 355350`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 5 packages built:</summary>
  <ul>
    <li>nixVersions.nix_2_25</li>
    <li>nixVersions.nix_2_25.debug</li>
    <li>nixVersions.nix_2_25.dev</li>
    <li>nixVersions.nix_2_25.doc</li>
    <li>nixVersions.nix_2_25.man</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 5 packages built:</summary>
  <ul>
    <li>nixVersions.nix_2_25</li>
    <li>nixVersions.nix_2_25.debug</li>
    <li>nixVersions.nix_2_25.dev</li>
    <li>nixVersions.nix_2_25.doc</li>
    <li>nixVersions.nix_2_25.man</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:x: 4 packages failed to build:</summary>
  <ul>
    <li>nixStatic</li>
    <li>nixStatic.dev</li>
    <li>nixStatic.doc</li>
    <li>nixStatic.man</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>nixVersions.nix_2_25</li>
    <li>nixVersions.nix_2_25.dev</li>
    <li>nixVersions.nix_2_25.doc</li>
    <li>nixVersions.nix_2_25.man</li>
  </ul>
</details>

**Comment by Mic92** [comment]
Fixing nixStatic on darwin in the next pr.

**Pull request merged**
