### PR TITLE
steam: fix steamwebhelper

### LINKED ISSUE #137279: Steam: embeddedd browser not working with latest update
### Describe the bug
Steam's in-app web browser no longer works with the latest [Steam update (September 10)](https://steamcommunity.com/games/593110/announcements/detail/2941402621044012222).

### Steps To Reproduce
1. Enable steam using the option `programs.steam.enable = true;`
2. Launch steam

Note: you might have to manually force Steam to check for updates, to get the latest build.

Potentially related issue: https://github.com/ValveSoftware/steam-for-linux/issues/7935

### Expected behavior
To be able to use the in-app web browser.

### Screenshots
https://i.imgur.com/nOXpR21.png

### Notify maintainers
@jagajaga @jonringer

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.62, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - channels(root): `"nixos-21.11pre308541.6fc5211eddd"`
 - channels(owner): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by TredwellGit**
###### Motivation for this change
Fixes https://github.com/NixOS/nixpkgs/issues/137279 and https://github.com/ValveSoftware/steam-runtime/issues/462.

###### Things done
- Built on platform(s)
  - [x] x86_64-linux
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TredwellGit** [comment]
This works when launched from a shell, but not from the XDG Desktop Entry. Any ideas why?

**Comment by jonringer** [comment]
> This works when launched from a shell, but not from the XDG Desktop Entry. Any ideas why?

unless you rebuild your system and reboot, it might be pointing at a different store path

**Comment by TredwellGit** [comment]
Both `nixos-rebuild switch` and `reboot` do not make it work.

**Review by Enzime — APPROVED** [review]
Fixed my Steam issues :+1:

**Comment by anund** [comment]
Alternative is building a valid working set `pango libthai harfbuzz`. Short term is seems safer to add rather than remove dependencies here. Longer term stopping or somehow better supporting the pattern of "fixing" various steam games by adding to `fhsenv.nix` needs to be worked through.

**Comment by anund** [comment]
https://github.com/ValveSoftware/steam-runtime/issues/462#issuecomment-917311581 has a workable fix users can apply without waiting for this PR.

**Comment by TredwellGit** [comment]
Interestingly, the XDG Desktop Entry works when launched by GNOME Shell, but not Rofi.

**Comment by TredwellGit** [comment]
Why do these games need libraries from the system rather than the Steam runtime?

**Comment by TredwellGit** [comment]
@bendlas can you test if Screeps works with this?

**Comment by TredwellGit** [comment]
I say we merge this now and deal with the desktop entry later.

**Comment by anund** [comment]
Screeps Arena (a demo version of the same thing?) is less broken with the additional dependencies.

Just removing pango results in a failure to launch with `<...>/Steam/steamapps/common/Screeps Arena/arena: symbol lookup error: /lib64/libgtk-3.so.0: undefined symbol: pango_attr_foreground_alpha_new` 
Adding all three allows the game to launch and hit some other error along the lines of https://github.com/ValveSoftware/steam-for-linux/issues/5089 so I'm not digging further.

**Comment by anund** [comment]
@TredwellGit I suggest removing pango trades launching steam for various cryptic game failures across more than just Screeps. It's removing a 2 year old implicit dependency.

**Comment by TredwellGit** [comment]
I will update to add the dependencies.

**Comment by bendlas** [comment]
tried the latest version. can confirm that it fixes steam on my desktop. screeps still works

**Review by jonringer — APPROVED** [review]
fixes the issue for now.

Would still like to get off the "make steam an ever-growing runtime closure" track... but that can be when proton is more mature.

**Pull request merged**
