### PR TITLE
lib.types.loeOf: treat <elem> as [<elem>]

### PR DESCRIPTION
**Pull request by groxxda**
###### Motivation for this change

Having to check for null element and empty list is error prone.

I think this has the potential to break stuff, but probably only things that miraculously worked..

I wrote this some time ago when #18172 was merged. Of course this would not have prevented #19610 because that specific code uses `either str (listOf str)`..

There are probably places in nixpkgs that could be removed if this is merged (apply functions that do the same at the moment)
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This makes the usage of loeOf more uniform because it automatically
wraps single elements inside a list so it always returns a list.

The user no longer has to check if a single element or a list with one
element was passed.

This also allows merging multiple definitions when they are not lists:

```
file1: option = "a";
file2: option = [ "b" ];
results in: option = [ "a" "b" ];
```

(previously this was an error)

### CODE REVIEW

**Comment by ericsagnes** [comment]
For the record, there was a proposition to deprecate `loeOf` in #1800.

**Comment by groxxda** [comment]
Well that issue is about loaOf, not loeOf.
While loeOf is also there to support backwards compatibility, this PR addresses the mergability problem.

**Comment by ericsagnes** [comment]
> Well that issue is about loaOf, not loeOf.

Oops, my bad.

> While loeOf is also there to support backwards compatibility, this PR addresses the mergability problem.

Does this PR just turn `loeOf` into a `listOf` where you can set a single value without using `singleton`?

**Comment by groxxda** [comment]
> Does this PR just turn loeOf into a listOf where you can set a single value without using singleton?

Basically yes.

Since the conversion is always done, if one code site defined a single value, a second value can now be merged. Previously this resulted in an exception:
(caller 1 is evaluated before caller 2)
```
caller 1: var = "x";
caller 2: var = "y";
ERROR: option defined multiple times
caller 1: var = "x";
caller 2: var = ["y"];
ERROR: option defined multiple times
caller 1: var = ["x"];
caller 2: var = "y";
ERROR: value is a string while a list was expected
caller 1: var = ["x"];
caller 2: var = ["y"];
RESULT: ["x" "y"]
```
(the error is dependent on evaluation order)

With this change all 4 options are valid and return `["x" "y"]`

**Comment by ericsagnes** [comment]
Then, IMO turning these options in `listOf` and explicitely declare singleton lists would be cleaner.

Having 2 different option types doing almost the same thing can be confusing. (I suppose unmergeable single values in the original code was on purpose)

Let's wait and see what others think.

**Comment by groxxda** [comment]
I agree that having `loeOf` can be confusing. It should be marked as deprecated, so no new uses are introduced.

It's only valid use case is to add support for lists to _existing_ options without breaking existing code.
I think it's better than having `either [ elem (listOf elem) ]` in various places because it's error prone (see initial motivation for this change).

**Comment by nbp** [comment]
I suggest we even remove this type completely instead of making it deprecated.
I see only 4 uses in NixOS.

**Comment by ericsagnes** [comment]
There are a [few projects](https://github.com/search?q=loeOf&type=Code) external to nixpkgs that seem to use it, might be nicer to them to have a deprecation phase.

**Pull request closed without merging**
