### PR TITLE
mupdf: 1.24.8 -> 1.24.9, fixes

### LINKED ISSUE #331934: Build failure: python312Packages.pymupdf
### Steps To Reproduce

1. build *python312Packages.pymupdf*

### Build log

```nix
builder for '/nix/store/0ibrmx5mkr625p2n5972n7426k6fq5yp-mupdf-1.23.6.drv' failed with exit code 1;
       last 20 log lines:
       > (+5.7s): -b: 1: __main__.py:1638:build: [returned e=1]
       > Traceback (most recent call last):
       >     scripts/mupdfwrap.py:6:<module>(): wrap.__main__.main()
       >     scripts/wrap/__main__.py:2902:main(): jlib.exception_info()
       >     ^except raise:
       >     scripts/wrap/__main__.py:2900:main(): main2()
       >     scripts/wrap/__main__.py:2310:main2(): build( build_dirs, swig_command, args, vs_upgrade)
       >     scripts/wrap/__main__.py:1638:build(): jlib.build(
       >     scripts/jlib.py:2213:build(): system( command, out=out, verbose=verbose, executable=executable, caller=2)
       >     scripts/jlib.py:1682:system(): raise Exception( message)
       > Exception: Command failed: c++ \
       >     -o build/shared-release/libmupdfcpp.so \
       >  \
       >     -O2 -DNDEBUG \
       >     -fPIC -shared \
       >     -I /build/mupdf-1.23.6-source/include \
       >     -I /build/mupdf-1.23.6-source/platform/c++/include \
       >      platform/c++/implementation/classes.cpp platform/c++/implementation/classes2.cpp platform/c++/implementation/exceptions.cpp platform/c++/implementation/extra.cpp platform/c++/implementation/functions.cpp platform/c++/implementation/internal.cpp \
       >     -L build/shared-release -l mupdf -Wl,-rpath,'$ORIGIN',-z,origin
       > /nix/store/1r32fki5z5ivgaikgh8pq0r6vz3b0jpj-stdenv-linux/setup: line 193: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/0ibrmx5mkr625p2n5972n7426k6fq5yp-mupdf-1.23.6.drv'.
error: 1 dependencies of derivation '/nix/store/bgrlbv73rkijhw2n03yh98r503l7jrk4-python3.12-pymupdf-1.23.26.drv' failed to build
```

### Additional context

I see few more build failures with other packages. Guess so it is not built in cache as well.

Eg: python312Packages.imbalanced-learn

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.2, NixOS, 24.11 (Vicuna), 24.11.20240728.52ec9ac`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/bcghcr9qwqmanpds017w75mcqda4fgab-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by emilazy**
## Description of changes

All credit goes to @lilyinstarlight. Built `mupdf`, `python3Packages.mupdf`, `mupdf.tests.mupdf-all`.

cc @drupol @GaetanLepage

cc @sarahec I think this should fix the issue you were running into, and you should be able to bump cleanly on top of this.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by sarahec** [comment]
As a double-check, also build `python3Packages.pymupdf` after the bump. I could get `mupdf` to build then encounter compilation issues when pymupdf tried to build the parent.

**Review by sarahec — COMMENTED** [review]
Failure while building `python311Packages.pymupdf` on aarch64-Darwin:

```sh
error: builder for '/nix/store/4l9j0zyl7h7nvkp8ml1kci064p7hm9ah-mupdf-1.24.9.drv' failed with exit code 1;
       last 10 log lines:
       > Traceback (most recent call last):
       >     scripts/mupdfwrap.py:6:<module>(): wrap.__main__.main()
       >     scripts/wrap/__main__.py:3062:main(): jlib.exception_info()
       >     ^except raise:
       >     scripts/wrap/__main__.py:3060:main(): main2()
       >     scripts/wrap/__main__.py:2445:main2(): build( build_dirs, swig_command, args, vs_upgrade, make_command)
       >     scripts/wrap/__main__.py:1637:build(): build_0(
       >     scripts/wrap/__main__.py:1413:build_0(): cpp.cpp_source(
       >     scripts/wrap/cpp.py:5024:cpp_source(): raise Exception(f'libclang does not appear to be installed') from e
       > Exception: libclang does not appear to be installed
       For full logs, run 'nix log /nix/store/4l9j0zyl7h7nvkp8ml1kci064p7hm9ah-mupdf-1.24.9.drv'.
error: 1 dependencies of derivation '/nix/store/k5wqx2jc6z43ixgy5qfz8m066sh33lcd-python3.11-pymupdf-1.24.8.drv' failed to build
```

**Comment by emilazy** [comment]
This still needs some more changes (e.g. `pymupdf` bump, and actually it turns out that the FreeGLUT fork is required). The `libclang` error there looks like what I fixed in 6e0421e551ac153e31014b294f6f03939071135a; odd if it’s still happening.

**Comment by sarahec** [comment]
> The `libclang` error there looks like what I fixed in [6e0421e](https://github.com/NixOS/nixpkgs/commit/6e0421e551ac153e31014b294f6f03939071135a); odd if it’s still happening.

Yes, that made its way into `default.nix` for `mupdf`. Somehow, it still seems to be happening. It's a mystery.

Build log: https://gist.github.com/sarahec/97d280ae7a8e0cdb0f24535f1ef40726

**Comment by sarahec** [comment]
This looks salient (from the gist):

```sh
(+0.0s): parse.py:14:<module>: Warning, could not import clang: No module named 'clang'
(+0.1s): state.py:18:<module>: Warning: failed to import clang.cindex: e=ModuleNotFoundError("No module named 'clang'")
(+0.1s): state.py:18:<module>: We need Clang Python to build MuPDF python.
(+0.1s): state.py:18:<module>: Install with `pip install libclang` (typically inside a Python venv),
(+0.1s): state.py:18:<module>: or (OpenBSD only) `pkg_add py3-llvm.`
```

**Comment by emilazy** [comment]
It should work on everything now (including cross).

**Comment by sarahec** [comment]
What seems to be happening is that `mupdf` builds just fine standalone, but build `python311Packages.pymupdf` and it builds a fresh copy of `mupdf` and signals that missing package error.

**Comment by lilyinstarlight** [comment]
> What seems to be happening is that `mupdf` builds just fine standalone, but build `python311Packages.pymupdf` and it builds a fresh copy of `mupdf` and signals that missing package error.

Can you share how you are testing and details on your host system? (e.g. what macOS version, is sandbox enabled, etc)

**Comment by sarahec** [comment]
> > What seems to be happening is that `mupdf` builds just fine standalone, but build `python311Packages.pymupdf` and it builds a fresh copy of `mupdf` and signals that missing package error.
> 
> Can you share how you are testing and details on your host system? (e.g. what exact command you are running to checkout the commit from this PR, what command to build, what macOS version, is sandbox enabled, etc)

1. Checked out `pr/emilazy/342894:push-truntykvnrrx` from within vscode and use `git pull` before each round of testing to get the latest updates
2. `nix-build -A python311Packages.pymudf` is what I'm running.
3. ```sh
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.6.0, macOS 14.6.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```
4. I get identical results with sandboxing on and off (`nix-build -A python311Packages.pymupdf --option sandbox false` vs. with the option set to `true`).

**Comment by sarahec** [comment]
> It should work on everything now (including cross).

The cross-compilation error is gone, and I think the issue may be that the python interface build is missing `python3Packages.libclang`.

**Comment by lilyinstarlight** [comment]
> The cross-compilation error is gone, and I think the issue may be that the python interface build is missing `python3Packages.libclang`.

`python3Packages.libclang` is present (see [here](https://github.com/NixOS/nixpkgs/pull/342894/files#diff-5a5a41db2d1a1036fc1552ca1f7b47078835e015f7426a57f95bc395e119dbdeR107))

> 2. `nix-build -A python311Packages.pymudf` is what I'm running.

Ah! I'd only tested `python3Packages.pymupdf` (which is `python312Packages.pymupdf`), not the Python 3.11 version. I'll see if I can poke at it tomorrow morning and figure it out (it's late here and I'm about to sleep), thank you :)

**Comment by lilyinstarlight** [comment]
@ofborg build python311Packages.pymupdf

**Comment by lilyinstarlight** [comment]
@sarahec Well I couldn't sleep. So I remember this issue now. Darwin will always fail for any Python package that's not in the `python3Packages` set that also utilizes the `desktopToDarwinBundle` setup hook (like `mupdf.override { python3 = python311 }`), because that hook erroneously propagates default `python3` via `python3Packages.icnsutil` and pollutes the `python311` build with `python312` references (and therefore fails to find the `python311Packages.libclang` since `python3` command is erroneously `${lib.getBin python312}/bin/python3`)

Until we have a more proper fix for Python environment management when needing just bins from a python package, the easiest general fix for every package in this situation would be to do this diff (which has been in my nixpkgs `git stash` for a long time now... also see <https://github.com/NixOS/nixpkgs/pull/266544#pullrequestreview-1733320816>):

```diff
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index 1254d45dda59..ca71039f4293 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -1341,7 +1341,7 @@ with pkgs;
 
   desktopToDarwinBundle = makeSetupHook {
     name = "desktop-to-darwin-bundle-hook";
-    propagatedBuildInputs = [ writeDarwinBundle librsvg imagemagick python3Packages.icnsutil ];
+    propagatedBuildInputs = [ writeDarwinBundle librsvg imagemagick (onlyBin python3Packages.icnsutil) ];
   } ../build-support/setup-hooks/desktop-to-darwin-bundle.sh;
 
   keepBuildTree = makeSetupHook {
```

**Comment by sarahec** [comment]
@lilyinstarlight I hope you managed to get some sleep. Thank you for unpacking the issue for Darwin.

Is there something I should do here?

**Comment by sarahec** [comment]
@lilyinstarlight I tested the dozen or so packages that use `desktopToDarwinBundle` and python, and only this one and possibly `rcu` fail. So perhaps there's a local patch to [py?]mupdf that makes sense?

**Comment by emilazy** [comment]
I think it would be best just to open a PR with the `desktopToDarwinBundle` workaround rather than adding more complicated and less general workarounds here.

**Comment by emilazy** [comment]
Going to merge this so that it gets in for the next `staging` cycle; @sarahec if you open a PR for the `desktopToDarwinBundle` fix feel free to ping me for review/merge.

**Pull request merged**
