### PR TITLE
.github/workflows/basic-eval.yml: try to parallelize

### PR DESCRIPTION
**Pull request by Artturin**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/runs/5772942787?check_suite_focus=true 20m before
 
https://github.com/NixOS/nixpkgs/actions/runs/2072549291 7m 41s after

**Comment by zowoq** [comment]
The limit is 20 concurrent jobs. Running 4 in parallel slows down the jobs queue for other PRs. I don't think it matters how fast `basic-eval` is as long as it is faster than `ofborg`.

I don't see that that is an improvement.

https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits

**Comment by zowoq** [comment]
Even with `max-parallel: 2` I'm a very strong no to this PR.

It is adding a lot of complexity for the sake of saving a few minutes.

**Comment by Artturin** [comment]
@zowoq i set it to only run if manually dispatched https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

i still think it is worth it to have this available in nixpkgs

**Comment by zowoq** [comment]
I'm very, very strongly against the complexity being added for the parallel jobs. If we only running this manually who cares it it takes a few extra minutes. I'd much rather that this remain as simple as possible.

**Pull request closed without merging**
