### PR TITLE
[20.09] lxd: Backport #97550

### PR DESCRIPTION
**Pull request by Patryk27**
This pull request backports https://github.com/NixOS/nixpkgs/pull/97550 for 20.09.

### CODE REVIEW

**Comment by worldofpeace** [comment]
You need to use `cherry-pick -x`.

**Review by jonringer — COMMENTED** [review]
When backporting changes, please follow https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#backporting-changes.

Namely, you should be doing `git cherry-pick -x <rev>` from a commit that has already landed in master. If the branches have diverged, you may alter the commit or add another commit to ensure that the package is able to still evaluate and build

**Comment by Patryk27** [comment]
Reading be hard, sorry :facepalm:
I've adjusted pull request to the requirements :-)

**Comment by worldofpeace** [comment]
@Patryk27 Oh, sorry about that, it appears both me and Jon requested the same review :grimacing: 
All good now, thanks for backporting :sparkles:

**Pull request merged**
