### PR TITLE
yosys-symbiflow: 2023.02.08 -> 1.20230425 (and libraries uhdm 1.45->1.57, surelog 1.45->1.57)

### PR DESCRIPTION
**Pull request by hzeller**
###### Description of changes
uhdm: 1.45 -> 1.57
surelog: 1.45 -> 1.57
yosys-symbiflow: 2023.02.08 -> 1.20230425

These build on top of each other and are in active development, so update them all at in this PR (each of the updates is their separate commit of course).

Most notable from the packaging perspective is, that UHDM and Surelog don't need the vendored dependencies (in their third_party/ submodules), but can use directly the libraries from nix (capnp, flatbuffers, antlr, gtest).
(that means UHDM and Surelog don't need the `fetchSubmodules=true` anymore.

On top of that, the UHDM and Surelog projects themselves now provide proper `pkg-config` files that are picked up by the yosys-symbiflow plugin build.

### Yosys-symbiflow
While at it: fixed tests for yosys-symbiflow: they were not run anymore (`checkTarget` was default `check`, but needs to be `test`). Also adaptions for new locations of plugins in the build-tree and making googletest work again.
The pmgen patch did not apply cleanly anymore as the upstream Makefiles were changed. Simplify that logic and make work again.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - The unit tests of UHDM, Surelog and yosys-symbiflow ran successfully.
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hzeller** [comment]
Successfully compiled on x86_64 linux and aarch64 linux.

**Comment by hzeller** [comment]
Also, ofborg also compiled it in addtion successfully on x86_64-darwin, but seems to be still queued for a chance to compile on aarch64-darwin.

**Comment by hzeller** [comment]
@matthuszagh looks good ?

**Comment by hzeller** [comment]
@ofborg build yosys-symbiflow

**Comment by hzeller** [comment]
@ofborg build yosys-symbiflow

**Review by thoughtpolice — APPROVED** [review]
👍🏻 lgtm

**Pull request merged**
