### PR TITLE
[20.09] nixops: unbreak

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

Backport PR for #112407. Please note that I removed `nixopsUnstable` here on purpose as this would've meant that another PR had to be backported and I didn't manage to get it building without deeper investigation.

cc @madonius

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by adisbladis** [comment]
@Ma27 Instead of outright removing `nixopsUnstable` could you make it an alias for `nixops`?

**Comment by Ma27** [comment]
Good point! Pushed a commit for that! :)

**Comment by Ma27** [comment]
@adisbladis anything else? Otherwise I'd merge :)

**Comment by adisbladis** [comment]
> anything else? Otherwise I'd merge :)

Nothing else :) Been AFK for a couple of hours.

**Pull request merged**
