### PR TITLE
New packages: Prometheus monitoring system

### PR DESCRIPTION
**Pull request by benley**
Various accessory packages to follow: promdash, alertmanager,
haproxy_exporter, etc.

[Review on Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/6408)

### CODE REVIEW

**Comment by benley** [comment]
build breakage is unrelated to this change :-\

**Comment by benley** [comment]
SWEET this actually works now.  Is it okay that I'm not using buildGoPackage here?

**Comment by lethalman** [comment]
It's a problem in that the day people need some of the deps of prometheus, those will be duplicated. Libraries must go in go-packages.nix as much as possible to be reusable.
I can help with the buildGoPackage usage if you find any trouble. The only one I see is that of running protoc, but I guess that would be easily fixed with a postUnpack or such.

**Comment by benley** [comment]
I should be able to get this switched over to using buildGoPackage soon, just haven't had time to get back to it.

**Comment by benley** [comment]
I think this should be good to go now.

One thing I wasn't sure about: with the migration from code.google.com to github.com, there are now two distinct locations for the protobuf library, and various things are probably going to depend on both of them for a while during the transition.  Is there a better way of handling that transition than adding a second instance of the package for the alternate namespace?

**Comment by benley** [comment]
friendly ping, I believe this is ready for review again.

**Comment by lethalman** [comment]
Can't you change the existing goPackages.protobuf to point to the new location?

**Comment by benley** [comment]
Won't that break all the existing packages that rely on the older code.google.com/p/protobuf path for imports?  Apologies if I'm misunderstanding something here - it feels like I might be.

**Comment by benley** [comment]
I'm working on a separate change to try to handle all the code.google.com -> github.com goPackagePath transitions that are going to be needed sooner or later.

**Comment by lethalman** [comment]
@benley ah right, go works by path :( ok then packaging it twice should be fine, and keep the old one.

**Comment by lethalman** [comment]
Does this work now after merging the protobuf PR?

**Comment by benley** [comment]
Rebased this to include #6941, which ought to take care of it. Pity the travis build seems to be broken on something unrelated now.

**Comment by lethalman** [comment]
Just merged #6941 but github doesn't seem to recognize that in this PR.

**Comment by lethalman** [comment]
Built a couple of them locally, thanks.

**Comment by benley** [comment]
Woot!

**Pull request merged**
