### PR TITLE
rocketchat-2.10.5: initial commit

### PR DESCRIPTION
**Pull request by hlolli**
###### Motivation for this change
It's basically an Electron desktop app like Slack. I tested it as nix-overlay. There are some warnings printed about Rocket Chat not being able to auto update via electron-updater, but that's ok as we wouldn't want this feature to work. Otherwise no problem. Need to get myself comfortable with the sandbox, slowly learning nixos, so I decided to PR this derivation.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ x ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ x ] Tested execution of all binary files (usually in `./result/bin/`)
- [ x ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by emmanuelrosa** [comment]
Given that there's also a rocketchat web app, which on NixOS would be implemented as a service, there will need to be a way to distinguish the server side package (which doesn't exist yet) from this desktop app package: Because typically services, say postgres, have packages in the top-level.

As an example, this package can be named rocketchat-desktop while rocketchat could refer to the web app. Or, this package name can stay and the web app package be the one to take the rename.

**Comment by emmanuelrosa** [comment]
The derivation builds just fine (with sandboxing). I did get the following build output:

```
cannot find section .interp
cannot find section .interp
not an ELF executable
not an ELF executable
not an ELF executable
not an ELF executable
not an ELF executable
not an ELF executable
not an ELF executable
not an ELF executable
```

I successfully ran the app from the .desktop file (inside of a vm built with `nixos-rebuild build-vm`) and also from the commandline. I did get this error regarding a missing file:
```
$ rocketchat
Checking for update
Error: Error: ENOENT: no such file or directory, open '/nix/store/ryvzhlz8a2inm26aw2q04ygrj0r5vz6x-rocketchat-2.10.5/lib/rocketchat/resources/app-update.yml'
    at /nix/store/ryvzhlz8a2inm26aw2q04ygrj0r5vz6x-rocketchat-2.10.5/lib/rocketchat/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:370:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/nix/store/ryvzhlz8a2inm26aw2q04ygrj0r5vz6x-rocketchat-2.10.5/lib/rocketchat/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:395:11)
    at Lazy.AppUpdater.configOnDisk.Lazy [as creator] (/nix/store/ryvzhlz8a2inm26aw2q04ygrj0r5vz6x-rocketchat-2.10.5/lib/rocketchat/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:132:43)
    at Lazy.get value [as value] (/nix/store/ryvzhlz8a2inm26aw2q04ygrj0r5vz6x-rocketchat-2.10.5/lib/rocketchat/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /nix/store/ryvzhlz8a2inm26aw2q04ygrj0r5vz6x-rocketchat-2.10.5/lib/rocketchat/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:281:33
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/nix/store/ryvzhlz8a2inm26aw2q04ygrj0r5vz6x-rocketchat-2.10.5/lib/rocketchat/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:353:11)
    at /nix/store/ryvzhlz8a2inm26aw2q04ygrj0r5vz6x-rocketchat-2.10.5/lib/rocketchat/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:264:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/nix/store/ryvzhlz8a2inm26aw2q04ygrj0r5vz6x-rocketchat-2.10.5/lib/rocketchat/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:307:11)
    at AppImageUpdater.checkForUpdates (/nix/store/ryvzhlz8a2inm26aw2q04ygrj0r5vz6x-rocketchat-2.10.5/lib/rocketchat/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:213:35)
    at checkForUpdates (/nix/store/ryvzhlz8a2inm26aw2q04ygrj0r5vz6x-rocketchat-2.10.5/lib/rocketchat/resources/app.asar/app/background.js:391:37)
    at afterMainWindow (/nix/store/ryvzhlz8a2inm26aw2q04ygrj0r5vz6x-rocketchat-2.10.5/lib/rocketchat/resources/app.asar/app/background.js:516:5)
    at App.<anonymous> (/nix/store/ryvzhlz8a2inm26aw2q04ygrj0r5vz6x-rocketchat-2.10.5/lib/rocketchat/resources/app.asar/app/background.js:606:5)
    at emitTwo (events.js:130:20)
    at App.emit (events.js:213:7)
```

**Comment by emmanuelrosa** [comment]
The thought of building an electron app from source on Nix makes my stomach turn.

I think it's perfectly fine to keep the package name. Then whoever creates a server package can just call it something like rocketchat-server, and the service module could simply be called rocketchat.

As for the error, aside from ignoring it, the only thing I can think of that is somewhat reasonable is to replace the `AppUpdater.js` in the asar archive with with a Nix-friendly neutered version.

**Comment by hlolli** [comment]
I'd go for try catch or something. This is typescript, and we may be looking at source map code, could be a stir into a minified spagetti. First I have to unzip/untar the asar archive, will research...

**Comment by hlolli** [comment]
@emmanuelrosa the elecetron-updater is completly supressed in my last commit. The .aspar archive is basically a textfile with header which maps to js files. And the metadata of each file is the file line count and the position of the start of the file in character. So sed-ing on this file works if one does not change the netto character count of the replace.

**Comment by emmanuelrosa** [comment]
@hlolli Nice!

On my system, the _About RocketChat_ dialog shows a blank window, where as in the original commit the dialog displays a button to check for updates, along with a checkbox to enable/disable checking for updates upon start. What about on your system?

**Comment by hlolli** [comment]
Yes I get the same, it shows empty dialog. No warning or error printed... strange. Will look deeper into this (could be after the weekend).

**Comment by matthewbauer** [comment]
So, I think we are going to want to build this from source. Have you tried using yarn2nix?

**Comment by hlolli** [comment]
@matthewbauer no but I'm planing to try yarn2nix for another node based app. I guess I could use it here too, I went this elfpatching path because the slack derivation does the same thing, basically copy paste. But I'm not sure if yarn2nix would solve the electron-updater issue here.

https://github.com/RocketChat/Rocket.Chat.Electron/pull/411

Do you have any suggestions on this. If I'm able to get the "about" dialog back, and maybe remove the "Check for updates" button too. Would it be enough. I'm also happy to do it over with yarn2nix, need to learn it sooner or later :)

**Comment by jbwiv** [comment]
Is this still a work in progress? I'd like to run this on NixOS as well. Thanks.

**Comment by hlolli** [comment]
@jbwiv you could use my nix expression as an overlay and start running Rocketchat. I'm getting there's still 4 weeks until I have time to look into this PR, there's to say if someone doesn't beat me to it.

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by hlolli** [comment]
I'm going to have another go at this, like @matthewbauer mentioned, we are going to want to build this from source. I'm going to start with patching the electron-builder and make a PR for it, after that, it should be easy. Similarly what I did with yakyak https://github.com/NixOS/nixpkgs/pull/69393 (in case someone here is up for code-reviewing it). I close this PR for now.

**Pull request closed without merging**
