### PR TITLE
airwindows-lv2: 20.0 -> 22.0

### PR DESCRIPTION
**Pull request by hannesbraun**
## Description of changes

This pull request updates the package to version 22.0. The changelog is available here: https://git.sr.ht/~hannes/airwindows-lv2/refs/v22.0

As the project moved to Sourcehut, I updated the source location as well.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by magnetophon — APPROVED** [review]
Thanks for the update, and for porting the Airwindows plugins to lv2 in the first place!
Are you using nix and/or planning on using it in the future?
Would you like to become the maintainer, or co-maintainer of this package?

**Comment by magnetophon** [comment]
Result of `nixpkgs-review pr 246985` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>airwindows-lv2</li>
  </ul>
</details>

**Comment by hannesbraun** [comment]
> Thanks for the update, and for porting the Airwindows plugins to lv2 in the first place!

You're welcome :)

> Are you using nix and/or planning on using it in the future?
> Would you like to become the maintainer, or co-maintainer of this package?

As of now, I'm not really using Nix. Occasionally, I try things out with it. Maybe I'll use it more in the future, but I don't really know. So I think it doesn't make a lot of sense for me to become a maintainer of the package right now. But if there are any problems or questions, you can always reach out and I'll try to help you as good as I can.

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 246985` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>airwindows-lv2</li>
  </ul>
</details>

**Review by tomberek — APPROVED** [review]

**Pull request merged**
