### PR TITLE
[staging] perl: 5.36.0 -> 5.38.0

### PR DESCRIPTION
**Pull request by stigtsp**
###### Description of changes

- Update `perl` and `perl538` to v5.38.0
  https://metacpan.org/release/RJBS/perl-5.38.0/changes

- Update `perl536` to v5.36.1
  https://metacpan.org/release/SHAY/perl-5.36.1/changes

- Update `perl-cross` to 1.5

- Remove `perl534` and `perl534Packages`

- Set `perldevel` to 5.38.0

Patches:
- Add patches from #225640 by @ck3d to support Module::Build and friends for cross-compilation, modify them to work with 5.38.0
- Update no-sys-dirs patch for 5.38.0
- Only apply HTTP-Tiny patch for 5.36.1, as it is fixed in 5.38.0
- Set `USE_ZLIB_NG=False` for Compress::Raw::Zlib

Related:
- slimserver: replace `perl534Packages` with `perlPackages` (builds - but untested)
- unit: add `perl538` as default, remove `perl534`
- perlPackages.TestWithoutModule: 0.20 -> 0.21
- perlPackages.TestTrap: 0.3.4 -> 0.3.5
- perlPackages.TestSimple13: 1.302183 -> 1.302195
- perlPackages.MIMECharset: 1.012.2 -> 1.013.1
- perlPackages.BKeywords: 1.24 -> 1.26
- perlPackages.XSParseKeyword: 0.25 -> 0.34

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin

Build Tests:
- `nix-build -A pkgsCross.aarch64-multiplatform.perlPackages.ModuleBuild` OK
- `nix-build -A pkgsCross.aarch64-multiplatform.perl536Packages.ModuleBuild` OK
- `nix-build -A pkgsCross.aarch64-multiplatform.xdg-utils` OK
- `nix-build -A hydra-unstable` OK
- `nix-build -A convos` OK

### CODE REVIEW

**Comment by mweinelt** [comment]
I already prepared the libxcrypt update in #241779.

**Comment by stigtsp** [comment]
> I already prepared the libxcrypt update in #241779.

The patch is not in 4.4.6 though, but looks like they are about to release 4.4.7?

**Comment by mweinelt** [comment]
image

Pretty sure it is.

**Comment by stigtsp** [comment]
> Pretty sure it is.

You are indeed correct! :-)

**Comment by magneticflux-** [comment]
@stigtsp Was there an incompatibility with `enableParallelBuilding` from the other changes? As far as I know, Perl still supports parallel builds with `make -jN` according to [various build instructions](https://github.com/search?q=repo%3APerl%2Fperl5+%22+-j%22+NOT+language%3APerl+NOT+language%3AShell+&type=code).

**Comment by Atemu** [comment]
@stigtsp could you explain the necessity for disabling enableParallelBuilding in non-cross circumstances?

**Comment by stigtsp** [comment]
@Atemu @magneticflux- Sorry for the late response, the specifics for this is a bit lost in time for me. 

I'm not aware of any reason why parallel builds shouldn't work, but vaguely remember having some problems with it when testing builds locally.

**Pull request merged**
