### PR TITLE
Replay Qt 5.12.3 version bump

### PR DESCRIPTION
**Pull request by ttuegel**
###### Motivation for this change

#64598 was reverted for causing segfaults (see #65448). The strict compatibility enforced by #65526 prevents the problem from recurring.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by ttuegel** [comment]
@GrahamcOfBorg test plasma5

**Review by samueldr — APPROVED** [review]
Validated that (1) by reverting #65526 this bump would fail, and that (2) it doesn't fail as it is.

This is good to go.

**Comment by ttuegel** [comment]
@samueldr Thanks for checking this out for me! :smile:

**Comment by peterhoeg** [comment]
This is slightly off-topic but I have a shit-ton of changes (frameworks, plasma, applications) that I wanted to see if it had to go into staging, only to see that various people had already done all the work. Gaaaarrrggghhhhh. Note to future self - check staging before taking on bigger bits.

**Comment by vcunat** [comment]
It won't build on darwin: https://hydra.nixos.org/build/98889958

**Comment by matthewbauer** [comment]
Most likely we need to update the qtbase patch, I think

**Comment by vcunat** [comment]
BTW, I see several Qt apps [now fail to build](https://hydra.nixos.org/eval/1538653?compare=1538611#tabs-now-fail) with "incomplete type" messages.  I assume it's just some header reorganization and adding includes will fix that relatively easily, as this PR was just a patch-number bump.

**Comment by vcunat** [comment]
_It's now in master, including the problems I posted about._

**Comment by vcunat** [comment]
Oh, I didn't realize that we have
```nix
{
 libsForQt5 = if stdenv.isDarwin then libsForQt511 else libsForQt512;
}
```
so the breakage of 5.12 on darwin doesn't seem too significant, though `qt5 = qt512;` isn't consistent with that, so that confused me a bit.  @matthewbauer: the inconsistency was introduced in #63707 &ndash; was that even intentional?

**Comment by vcunat** [comment]
I switched Darwin back to 5.11 for now: 2a7910655 :woman_shrugging:

**Comment by adisbladis** [comment]
I've applied a patch and fixed `qt512.qtbase` in https://github.com/NixOS/nixpkgs/pull/72999.

We have to bump the Qt version on Darwin as Qt 5.11 does not build with latest mesa.

**Pull request merged**
