### PR TITLE
nixos/tests/stalwart-mail: Add test for server version >= 0.7

### LINKED ISSUE #303156: stalwart-mail module needs a rewrite for version 0.7.0
### Describe the bug

 The new version of stalwart mail (0.7.0), has changed a lot and the module needs a rewrite for a while now, for example: I have forked nixpkgs, to remove the standard settings, to allow me to make a more complex setting.

 issues I see.
 - No way to disable the default options, in: `services.stalwart-mail.settings`.
 - WebUI is not currently supported
 - The `stalwart-mail` package imports the entire `cargo.lock`.

### Notify maintainers
@happysalada  

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by onny**
## Description of changes

Going to add test for stalwart-mail 0.8 beside already implemented test for stalwart-mail_0_6

Continuation of https://github.com/NixOS/nixpkgs/pull/304812
Fixes https://github.com/NixOS/nixpkgs/issues/303156

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by onny** [comment]
Somehow tests for both versions succeed but stalwart-mail 0.8 throws some errors about configuration syntax

**Comment by onny** [comment]
stalwart-mail 0.8 throws following errors while the test itself succeeds

```
machine # [    6.527263] stalwart-mail[800]: ERROR: Build error for key "*": Failed to update configuration: Internal Error: Failed to write local configuration file: Read-only file system (os error 30)
machine # [    6.529408] stalwart-mail[800]: ERROR: Failed to parse setting "directory.in-memory.principals.0001.type": Unknown directory type: "individual"
machine # [    6.531331] stalwart-mail[800]: ERROR: Failed to parse setting "directory.in-memory.principals.0000.type": Unknown directory type: "individual"
machine # [    6.533033] stalwart-mail[800]: ERROR: Build error for key "certificate.snakeoil": No certificates found.
```

maybe we can ignore the first error because we'll leave the configuration file read-only

**Comment by onny** [comment]
Okay all errors are fixed now :)

**Review by pacien — APPROVED** [review]
Beside the remark about the new default for the local public suffixes list, looks good to me :+1:

**Comment by onny** [comment]
> I didn't check, but the `passthru.tests` of the corresponding packages might also need to be updated to reference their respective NixOS tests.

The passthru.tests will run always the stalwart-mail test for both packages, hope that's fine :)

**Review by pacien — APPROVED** [review]

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
