### PR TITLE
python311Packages.python-osc: refactor

### PR DESCRIPTION
**Pull request by fabaff**
- use correct build system
- enable tests
- disable on unsupported Python releases

## Description of changes
Fix build (https://hydra.nixos.org/build/241256803)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 272540` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>ledfx</li>
    <li>ledfx.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.python-osc</li>
    <li>python310Packages.python-osc.dist</li>
    <li>python311Packages.python-osc</li>
    <li>python311Packages.python-osc.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 272540` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>ledfx</li>
    <li>ledfx.dist</li>
    <li>python310Packages.python-osc</li>
    <li>python310Packages.python-osc.dist</li>
    <li>python311Packages.python-osc</li>
    <li>python311Packages.python-osc.dist</li>
  </ul>
</details>

**Comment by rbozan** [comment]
Is this the reason that I'm getting the following error if I run LedFX on unstable or 23.11?

```
❯ ledfx
Loading configuration file: /home/rbozan/.ledfx/config.json
Started webinterface at http://localhost:8888
[ERROR   ] ledfx.core                     : Exception in core event loop: Task exception was never retrieved
Traceback (most recent call last):
  File "/nix/store/zlzbmrsilglbrzm2p4cyx8gm9ncwfl06-python3.11-ledfx-2.0.80/lib/python3.11/site-packages/ledfx/core.py", line 233, in async_start
    self.devices = Devices(self)
                   ^^^^^^^^^^^^^
  File "/nix/store/zlzbmrsilglbrzm2p4cyx8gm9ncwfl06-python3.11-ledfx-2.0.80/lib/python3.11/site-packages/ledfx/devices/__init__.py", line 581, in __init__
    super().__init__(ledfx, Device, self.PACKAGE_NAME)
  File "/nix/store/zlzbmrsilglbrzm2p4cyx8gm9ncwfl06-python3.11-ledfx-2.0.80/lib/python3.11/site-packages/ledfx/utils.py", line 809, in __init__
    self.import_registry(package)
  File "/nix/store/zlzbmrsilglbrzm2p4cyx8gm9ncwfl06-python3.11-ledfx-2.0.80/lib/python3.11/site-packages/ledfx/utils.py", line 850, in import_registry
    importlib.import_module(name)
  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/zlzbmrsilglbrzm2p4cyx8gm9ncwfl06-python3.11-ledfx-2.0.80/lib/python3.11/site-packages/ledfx/devices/osc.py", line 5, in <module>
    from pythonosc.osc_message_builder import OscMessageBuilder
ModuleNotFoundError: No module named 'pythonosc'
```

**Comment by SuperSandro2000** [comment]
23.11 is probably missing #271323

**Comment by SuperSandro2000** [comment]
fix in #274295

**Pull request merged**
