### PR TITLE
 scrcpy: init at 1.2

### PR DESCRIPTION
**Pull request by DeltaEvo**
###### Motivation for this change

Add scrcpy https://github.com/Genymobile/scrcpy

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ryantm** [comment]
Did you investigate building the server from src? That would be preferable if possible.

**Comment by DeltaEvo** [comment]
I tried quickly but I think I can build it by creating a subPackage and calling `androidenv.buildGradleApp`, but I don't know what license to choose then because `androidenv.buildGradleApp` make a package with an unfree license

Is there another way to do it ?
If not do I build it from source ?

**Comment by Mic92** [comment]
@GrahamcOfBorg build scrcpy

**Comment by Mic92** [comment]
I get the same error when building the package.

**Review by ryantm — CHANGES_REQUESTED** [review]
Please make it build.

**Comment by xeji** [comment]
@GrahamcOfBorg build scrcpy

**Comment by xeji** [comment]
closing in favor of #44249

**Pull request closed without merging**
