### PR TITLE
Intellij overhaul

### PR DESCRIPTION
**Pull request by GenericNerdyUsername**
## Description of changes

A complete overhaul of the linux side of the jetbrains ides, including building pycharm and intellij community from source

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by GenericNerdyUsername** [comment]
@wegank would you be able to check if this works on aarch64? If you're busy/don't want to, that's cool, just let me know so I can setup stuff with `boot.binfmt` and work on it myself.

**Comment by wegank** [comment]
Building `jetbrains.idea-community` on my machine.

**Comment by GenericNerdyUsername** [comment]
Just realised something, line 236 in source/build.nix is probably going to cause a fail

**Comment by wegank** [comment]
It works.

```
$ nix-build -A jetbrains.idea-community
/nix/store/hrj83zrbsg7lfi26jl82hks7lxcfnpy7-idea-community-2023.2.3
```

**Comment by GenericNerdyUsername** [comment]
Does it run? are any the binaries in there built for x86?

**Comment by wegank** [comment]
> Does it run?

Yes.

>  are any the binaries in there built for x86?

Only for some plugins: 

```
skipping /nix/store/hrj83zrbsg7lfi26jl82hks7lxcfnpy7-idea-community-2023.2.3/idea-community/plugins/android/resources/native/linux/libimage_converter.so because its architecture (x64) differs from target (AArch64)
skipping /nix/store/hrj83zrbsg7lfi26jl82hks7lxcfnpy7-idea-community-2023.2.3/idea-community/plugins/cwm-plugin/quiche-native/linux-x86-64/libquiche.so because its architecture (x64) differs from target (AArch64)
skipping /nix/store/hrj83zrbsg7lfi26jl82hks7lxcfnpy7-idea-community-2023.2.3/idea-community/plugins/webp/lib/libwebp/linux/libwebp_jni64.so because its architecture (x64) differs from target (AArch64)
skipping /nix/store/hrj83zrbsg7lfi26jl82hks7lxcfnpy7-idea-community-2023.2.3/idea-community/plugins/webp/lib/libwebp/linux/libwebp_jni.so because its architecture (x86) differs from target (AArch64)
```

**Comment by GenericNerdyUsername** [comment]
If you could build pycharm from source as well, that'd be great. I think if that goes well, theres nothing I can think of to do before removing draft status

**Comment by wegank** [comment]
```
$ nix-build -A jetbrains.pycharm-community                                                                                     intellij-overhaul
/nix/store/iylba5d5vzqpw7xfmmb13x4qaz2jqhxz-pycharm-community-2023.2.3
```

**Comment by niknetniko** [comment]
Result of `nixpkgs-review`:

```
23 packages built:
jetbrains.clion jetbrains.datagrip jetbrains.dataspell jetbrains.gateway jetbrains.goland jetbrains.idea-community jetbrains.idea-community-bin jetbrains.idea-ultimate jetbrains.jcef jetbrains.jcef.unpacked jetbrains.jdk jetbrains.jdk-no-jcef jetbrains.jdk-no-jcef.debug jetbrains.jdk.debug jetbrains.mps jetbrains.phpstorm jetbrains.pycharm-community jetbrains.pycharm-community-bin jetbrains.pycharm-professional jetbrains.rider jetbrains.ruby-mine jetbrains.rust-rover jetbrains.webstorm
```

I tested Intellij Community, Intellij Ultimate and PyCharm Community: all seem to work.

---- 

Out of curiosity, what is the benefit of having a `ides.json` file? As I understand it, this is mostly static information, so why can't this be a `nix` file? If this is just a nixpkgs convention I am unaware of, my apologies in advance

**Comment by GenericNerdyUsername** [comment]
It takes up a lot of space and obscures the actual build logic

**Comment by sequencer** [comment]
Any change to get this in?

**Review by wegank — APPROVED** [review]

**Review by niknetniko — APPROVED** [review]

**Comment by Janik-Haag** [comment]
Then you want https://github.com/NixOS/aarch64-build-box

**Pull request merged**
