### PR TITLE
obs-studio: 29.1.3 -> 30.0.0

### LINKED ISSUE #226468: `obs-studio` Browser Source - Hardware Acceleration not Enabled
### Describe the bug
`obs-studio` package (both 22.11 (v 28.1.2) and unstable (v 29.0.2)) for some reason does not have hardware acceleration enabled, whereas the flatpak version does by default. Running on a machine with an NVIDIA GPU.

### Steps To Reproduce
1. Install via `nix-shell -p obs-studio`
2. Run obs
3. Add browser source and point to `chrome://gpu`

### Expected behavior
Hardware acceleration should be enabled (if possible) with OpenGL enabled.

### Screenshots

nix installed version
image

flatpak version
image

### Additional context
Without this, WebGL based websites do not work such as `foundryvtt`.

### Notify maintainers
@jb55 @MP2E @V @miangraham

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.106, NixOS, 22.11 (Raccoon), 22.11.3689.fda0d99c2cb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11"`
 - channels(myusername): `"home-manager-22.11.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### LINKED ISSUE #267977: Update request: obs-studio 29.1.3 → 30.0
- Package name: `obs-studio`
- Latest released version: **30.0**

- Current version on the unstable channel: **29.1.3**
- Current version on the stable/release channel: **29.0.2**

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@jb55 @MP2E @V @miangraham 

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by materusPL**
## Description of changes

Update obs-studio to 30.0.0
Will close https://github.com/NixOS/nixpkgs/issues/267977

## Things done
Obs have new dependencies which are not in nixpkgs, I added them only for obs currently not in nixpkgs:
- Added qrcodegencpp, probably should be output to current qrcodegen but not sure about structure @AndersonTorres 
- Added onevpl, I don't have intel GPU so I can't really check if it works. Probably should be added as package in nixpkgs but as I don't own Intel card I'm not willing to maintain it for more than obs build needs. Alternative to onevpl is disabling QSV in obs

Change to libcef: added output for ANGLE libEGL and libGLESv2 to fix https://github.com/NixOS/nixpkgs/issues/226468#issuecomment-1751793235 @puffnfresh 

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by materusPL** [comment]
Result of `nixpkgs-review pr 269008` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>obs-studio-plugins.obs-hyperion</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>obs-studio-plugins.obs-ndi</li>
    <li>obs-studio-plugins.obs-pipewire-audio-capture</li>
    <li>obs-studio-plugins.obs-replay-source</li>
    <li>obs-studio-plugins.obs-tuna</li>
    <li>obs-studio-plugins.obs-vertical-canvas</li>
  </ul>
</details>
<details>
  <summary>32 packages built:</summary>
  <ul>
    <li>libcef</li>
    <li>obs-studio</li>
    <li>obs-studio-plugins.advanced-scene-switcher</li>
    <li>obs-studio-plugins.droidcam-obs</li>
    <li>obs-studio-plugins.input-overlay</li>
    <li>obs-studio-plugins.looking-glass-obs</li>
    <li>obs-studio-plugins.obs-3d-effect</li>
    <li>obs-studio-plugins.obs-backgroundremoval</li>
    <li>obs-studio-plugins.obs-command-source</li>
    <li>obs-studio-plugins.obs-freeze-filter</li>
    <li>obs-studio-plugins.obs-gradient-source</li>
    <li>obs-studio-plugins.obs-gstreamer</li>
    <li>obs-studio-plugins.obs-livesplit-one</li>
    <li>obs-studio-plugins.obs-move-transition</li>
    <li>obs-studio-plugins.obs-multi-rtmp</li>
    <li>obs-studio-plugins.obs-mute-filter</li>
    <li>obs-studio-plugins.obs-nvfbc</li>
    <li>obs-studio-plugins.obs-rgb-levels-filter</li>
    <li>obs-studio-plugins.obs-scale-to-sound</li>
    <li>obs-studio-plugins.obs-shaderfilter</li>
    <li>obs-studio-plugins.obs-source-clone</li>
    <li>obs-studio-plugins.obs-source-record</li>
    <li>obs-studio-plugins.obs-source-switcher</li>
    <li>obs-studio-plugins.obs-teleport</li>
    <li>obs-studio-plugins.obs-text-pthread</li>
    <li>obs-studio-plugins.obs-transition-table</li>
    <li>obs-studio-plugins.obs-vaapi</li>
    <li>obs-studio-plugins.obs-vintage-filter</li>
    <li>obs-studio-plugins.obs-vkcapture</li>
    <li>obs-studio-plugins.obs-websocket</li>
    <li>obs-studio-plugins.waveform</li>
    <li>obs-studio-plugins.wlrobs</li>
  </ul>
</details>

**Comment by muni-corn** [comment]
hiya! thank you for working on this! is there anything i can do to help move this along?

**Comment by materusPL** [comment]
If you have intel gpu it would be great to test if onevpl works okay.

Other than that, I would like to get details about what to do with onevpl and qrcodegencpp. 
OneVPL probably should be made package in nixos but as I don't own intel gpu I don't really have a way to test it, just made it to get obs to build without disabling QSV.
qrcodegencpp not sure if it should be output of qrcodegen or another package.

Obs  works fine for me  with current changes.

**Comment by AndersonTorres** [comment]
Fix the failure.

**Comment by eclairevoyant** [comment]
30.0.2 is out

**Comment by CobaltCause** [comment]
I just opened https://github.com/NixOS/nixpkgs/pull/275544 which builds on this PR and includes commits for 30.0.0, 30.0.1, and 30.0.2. I have no preference on which PR gets merged/closed, I just wanted to help out by making available the handful of changes I just made, especially since this PR hasn't gotten any commits for about a month.

**Comment by fpletz** [comment]
Didn't notice anybody was working on this. We'll continue in #275544. Thanks for the work @materusPL!

**Pull request closed without merging**
