### PR TITLE
asciiidoctor-web-pdf: init at 1.0.0-alpha.14

### PR DESCRIPTION
**Pull request by Flakebi**
###### Motivation for this change
Also add kroki plugin for diagrams and mathjax plugin for latex math in pdfs.

To add it with plugins:
```nix
environment.systemPackages = with pkgs; [
  (asciidoctor-web-pdf.override {
    plugins = with asciidoctor-web-pdf-plugins; [ kroki mathjax ];
  })
];
```

To generate pdf slides, run e.g. with `asciidoctor-web-pdf -r asciidoctor-kroki -r @djencks/asciidoctor-mathjax --template-require /path/to/slides-template.js slides.adoc` where `slides-template.js` is from `/nix/store/<hash>-asciidoctor-pdf-unstable-2021-10-23/libexec/asciidoctor-pdf/deps/asciidoctor-pdf/examples/slides/`.

Latex math can be rendered with
```adoc
[latexmath]
++++
\int_a^b 1 = b - a
++++
```

I tried out asciidoc inspired by https://discourse.nixos.org/t/markdown-vs-asciidoctor/15583 and it looks quite useful to make presentations with latex-like capabilities but a lot easier to use, so I decided to package it.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Flakebi** [comment]
Rebased and fix IFD by including `package.json` in nixpkgs.

**Comment by Flakebi** [comment]
Rebased and updated to 1.0.0-alpha.14.

**Comment by Flakebi** [comment]
Rebased and updated asciidoctor-kroki to [0.15.4](https://github.com/Mogztter/asciidoctor-kroki/releases/tag/v0.15.4).

**Comment by Flakebi** [comment]
Seems like it’s not going to be merged and I don’t plan to use asciidoctor anymore, so I’ll close this.

**Comment by ZainKergaye** [comment]
Hey how can we get this merged? I can't seem to find a way to clone @Flakebi 's branch to bump it two versions either.

**Comment by matklad** [comment]
@ZainKergaye FWIW, while I used to be a _huge_ fan of asciidoctor-web-pdf, these days I solve the problem by:

- compiling whatever document I have to HTML
- proving a "PDF" stylesheet using `@media print`
- and manually clicking my browser's print button.

In other words, using browsers layout engine to get a PDF output is still a smart thing to do, but you don't really need complicated tools to do that, DYI is feasible and is actually simpler, at least for me.

**Comment by Flakebi** [comment]
[Typst](https://typst.app/) (LaTeX but usable) + [Touying](https://github.com/touying-typ/touying) (slide framework for typst) is working quite well for me nowadays 🙂

**Pull request closed without merging**
