### PR TITLE
nixVersions.nix_2_24: 2.24.8 -> 2.24.9

### PR DESCRIPTION
**Pull request by trofi**
Changes: https://github.com/NixOS/nix/compare/2.24.8...2.24.9

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by trofi** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 348038`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 12 packages built:</summary>
  <ul>
    <li>colmena</li>
    <li>harmonia</li>
    <li>nil</li>
    <li>nix-eval-jobs</li>
    <li>nix-fast-build</li>
    <li>nix-fast-build.dist</li>
    <li>nix-serve</li>
    <li>nixVersions.latest</li>
    <li>nixVersions.latest.debug</li>
    <li>nixVersions.latest.dev</li>
    <li>nixVersions.latest.doc</li>
    <li>nixVersions.latest.man</li>
  </ul>
</details>

**Review by tomberek — APPROVED** [review]

**Review by drupol — APPROVED** [review]

**Comment by drupol** [comment]
Diff LGTM but the CI is failing to build...

**Comment by trofi** [comment]
> Diff LGTM but the CI is failing to build...

I think the test failure is pre-existing. Not sure why hydra does not run it by default. `nix build --no-link github:NixOS/nixpkgs#nixVersions.nix_2_24.passthru.tests.upgrade` fails here as:

```
$ nix build --no-link github:NixOS/nixpkgs#nixVersions.nix_2_24.passthru.tests.upgrade -L
...
vm-test-run-nix-upgrade> machine # Failed to stop nix-store.mount
vm-test-run-nix-upgrade> machine # the following new units were started: run-credentials-systemd\x2dtmpfiles\x2dresetup.service.mount, sysinit-reactivation.target, systemd-tmpfiles-resetup.service
vm-test-run-nix-upgrade> machine # [   21.495105] nixos[1020]: switching to system configuration /nix/store/jvkq0w49jqy390i39g7lyzramsz1gnjg-nixos-system-nixos-24.11pre-git failed (status 4)
```

It looks like a race between running a test and shutting down a VM.

**Comment by zowoq** [comment]
Updating the fallback paths in https://github.com/NixOS/nixpkgs/pull/348411.

**Comment by Mic92** [comment]
@trofi the upgrade test is broken because of switch-ng. There is an issue for this.

**Comment by Mic92** [comment]
https://github.com/NixOS/nixpkgs/issues/343975

**Comment by Mic92** [comment]
Just merged a workaround though.

**Pull request merged**
