### PR TITLE
monero-{cli,gui}: 0.18.1.2 -> 0.18.2.0

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Description of changes

Version bump

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change (`monero-cli`, `monero-gui`)
- [x] Tested basic functionality of all binary files (just `--help` and missing `.so`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

As usual, I tested connecting monero-gui to a remote node, creating a wallet and syncing the blockchain.

cc: [dani0854](https://github.com/dani0854)

### CODE REVIEW

**Comment by prusnak** [comment]
Did you check whether the Trezor support still works?

**Comment by rnhmjoj** [comment]
> Did you check whether the Trezor support still works?

I never did: I don't own one so don't think I can test it.

**Comment by prusnak** [comment]
In that case, please drop the 1eb471e8726949f0dc9e15c395cacc2adbe130d7 commit from the PR. According to the build log, the Trezor support is not built.

**Comment by rnhmjoj** [comment]
Oh,  you're right: I forgot a submodule. It should be fine now, the log says trezor support is enabled.

**Comment by prusnak** [comment]
How much time we are saving by not fetching the submodules of miniupnp, randomx, rapidjson?

Can you time how long does it take to fetch the repo with and without c47379d5e1d4ecb3123db1452d68d1da372132fb?

I'd prefer not to complicate the update process if we save only couple of seconds.

**Comment by rnhmjoj** [comment]
> I'd prefer not to complicate the update process if we save only couple of seconds.

It cuts by about a half the sources: 62M to 34M.

**Pull request merged**
