### PR TITLE
php.extensions.swoole: init at 4.6.4

### PR DESCRIPTION
**Pull request by etu**
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by etu** [comment]
@ofborg build php80.extensions.swoole php74.extensions.swoole php73.extensions.swoole

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 115965` at 7b446956 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built successfully:</summary>
  <ul>
    <li><a href="https://gist.github.com/31e27469a26ff9df95b05794ec0f04e2">php73Extensions.swoole</a></li></li>
    <li><a href="https://gist.github.com/7cbf6f8c0a7dbcd2f3f0fad3816de68b">php74Extensions.swoole</a></li></li>
    <li><a href="https://gist.github.com/0e208672f336e5deb889546434274ee5">php80Extensions.swoole</a></li></li>
  </ul>
</details>

**Comment by etu** [comment]
@ofborg build php80.extensions.swoole php74.extensions.swoole php73.extensions.swoole

**Comment by aanderse** [comment]
Thanks @etu!

**Pull request merged**
