### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by jonringer**
https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents  (soon)

- - -

Should be the final staging-next for ZHF

Major areas of focus: llvm packages, aarch64-darwin support.

Previous Staging-next: #122068

### CODE REVIEW

**Comment by andir** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/123297 to fix the libgcc issue on linux.

**Comment by andir** [comment]
This seems to be the same error was the one I fixed previously: https://hydra.nixos.org/build/143059644

Maybe we are up for more of these? We might want to consider reverting / rewriting 77e97ac4cac8af9578fa328c5cac5eaa4597da56 instead?

**Comment by jonringer** [comment]
> This seems to be the same error was the one I fixed previously: https://hydra.nixos.org/build/143059644
> 
> Maybe we are up for more of these? We might want to consider reverting / rewriting [77e97ac](https://github.com/NixOS/nixpkgs/commit/77e97ac4cac8af9578fa328c5cac5eaa4597da56) instead?

I would probably just pass the version as a passthru. `passthru = { major = ...; majorMinor = ...; }`. I think the use of `pname` and `version` is the more correct route, so I would prefer not to revert those changes.

**Comment by jonringer** [comment]
actually, it probably worked originally because version was being passed on `passthru`, and thus down stream packages were getting the `version` without the patch suffix.

**Comment by andir** [comment]
> > This seems to be the same error was the one I fixed previously: https://hydra.nixos.org/build/143059644
> > Maybe we are up for more of these? We might want to consider reverting / rewriting [77e97ac](https://github.com/NixOS/nixpkgs/commit/77e97ac4cac8af9578fa328c5cac5eaa4597da56) instead?
> 
> I would probably just pass the version as a passthru. `passthru = { major = ...; majorMinor = ...; }`. I think the use of `pname` and `version` is the more correct route, so I would prefer not to revert those changes.

Sounds good. Do you want to open a PR for that?

**Comment by bobrik** [comment]
#123706 fixes `python3Packages.cryptography` on darwin (or at least aarch64-darwin, since x86_64-darwin has broken deps).

**Comment by bobrik** [comment]
#123626 fixes `libidn2` for darwin.

**Comment by bobrik** [comment]
Some more PRs for aarch64-darwin:

* #123726 `gtk2` blocks 115 packages
* #123729 `gsl` blocks 38 packages
* #123728 `python3Packages.dbus-python` blocks 37 packages

**Comment by FRidh** [comment]
Build failures:
- poppler on darwin https://hydra.nixos.org/build/143419153 @jtojnar 
- rustc 1.45 for firefox on linux https://hydra.nixos.org/build/143387622 @madjar @cstrahan @globin @havvy

**Comment by vcunat** [comment]
And the rustc builds has
```
No space left on device
```
Unfortunately the `wendy` machine is now doing that occasionally, e.g. both webkit flavors on master recently.

**Comment by vcunat** [comment]
at a glance:
- [ ] firefox: its attempts to override llvm's bintools don't work anymore (can't find `llvm-ar`)
- [ ] php: broken tests, most likely after libxml2 update

**Comment by sternenseemann** [comment]
> firefox: its attempts to override llvm's bintools don't work anymore (can't find llvm-ar)

Should be fixed by #123886.

Note that there could be similar regression for virtually everything that uses clang and LTO in nixpkgs, but I guess it is not that many derivations?

**Comment by jtojnar** [comment]
For libxml2, maybe #123890

**Comment by stephank** [comment]
> For libxml2, maybe #123890

Having some difficulty verifying if that fixes `phpExtensions.dom`. On Darwin, it is a stdenv rebuild. On Linux, I have to go through gnutls which fails for some reason. 😕

**Comment by vcunat** [comment]
> On Linux, I have to go through gnutls which fails for some reason.

I'm not getting that failure.  (x86_64 NixOS, sandboxed)

**Comment by vcunat** [comment]
Nevertheless, the php issue doesn't seem affected by the change.  I'm not even sure it was meant to.

**Comment by stephank** [comment]
Okay, good to know. I was trying to opposite direction next, cherry-pick libxml2 2.9.12 into `master`. That's these two commits:

 - d01a4e3fe99cdc9f4015e741edfd3c77a5d90a37
 - 76c58493d78d5f06ed62e0b8309f223232dfc309

Unfortunately, I'm again blocked by gnutls. 😕 I think it's actually an issue with my local qemu VM, that mysteriously hangs at various idle points, because the failures are random timeouts in tests.

**Comment by jonringer** [comment]
I think the immediate course of action will be:

- get #123886 merged to fix firefox build on staging-next
- get #123890 into staging, eventually cherry-pick
- branch-off hopefully tomorrow, when remaining darwin rebuilds aren't severe.
- cherry-pick relevant fixes into `21.05-staging`

Release is scheduled to be done by next week.

@grahamc for next release, we should really increase the x86_64-darwin compute going into ZHF, if they are going to be included in jobsets which will determine merge-ability :)

**Comment by stephank** [comment]
I managed to resolve my VM issue and do some further testing. (Apparently, I have to run qemu with `-display none` on macOS to get consistent scheduling or something. Probably the difference between a GUI application and background task.)

Curiously, I got two different results:
 - On `master`, cherry-picking d01a4e3 and 76c5849 makes a build of `phpExtensions.dom` fail with the same error we're seeing on Hydra.
 - On `master`, just overriding the libxml2 input of `phpExtensions.dom` with the changes from d01a4e3 does **not** fail.

**Comment by stephank** [comment]
Hmm, the subtlety for the second case, of just overriding the libxml2 build input, is whether it is also overridden for PHP itself. Overriding libxml2 for both PHP and the dom extension results in the same failure as on Hydra.

So looks to me like it's definitely the libxml2 upgrade.

**Comment by stephank** [comment]
I made an attempt to fix the PHP issue upstream in https://github.com/php/php-src/pull/7030. With that patch, the full `php` with extensions builds again. But not sure if my patch is correct, so hoping for an upstream response.

**Comment by mweinelt** [comment]
https://shells.darmstadt.ccc.de/~hexa/1672060.html

**Comment by jonringer** [comment]
> https://shells.darmstadt.ccc.de/~hexa/1672060.html

I did the review report myself, and was able to build many of the "failed builds". I think this is fine to merge

**Comment by jonringer** [comment]
waiting on eval to finish

**Comment by jonringer** [comment]
eval finished

**Pull request merged**
