### PR TITLE
lib/options: mkPackageOption: document better, add pkgsText and usePname options, refactor

### PR DESCRIPTION
**Pull request by schuelermine**
## Description of changes

I have noticed that changes to `mkPackageOption` have left the documentation behind. I have updated the documentation.

I also noticed the documentation encourages users to pass alternative package sets to the function,
but as it is implemented, this would lead to end-user confusion. I have added a parameter that alleviates this.

I added another parameter that could be useful in niche cases, which has necessitated a refactor,
but I think the refactor leaves the function easier to read anyways. However, for this change in particular I request feedback.

I have only done rudimentary tests by inspecting the output of the function in `nix repl`.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by infinisil — CHANGES_REQUESTED** [review]
This is really hard to review like this, separate commits would help. But also I'm not sure about the new parameters, could that be a separate PR from the doc fixes?

Furthermore there are already some tests for this function in https://github.com/NixOS/nixpkgs/blob/e3948974208d4f1f4d77b1a710ff05f2597d451e/lib/tests/modules.sh#L228-L231, please run and extend them as necessary.

**Comment by schuelermine** [comment]
I have split the PR into seven commits, and added tests for each change.
I believe the `pkgsText` parameter is necessary if the function is to work as originally advertised. I have removed mentions of the functionality that would require it from the commits before the parameter is added, though.
About `usePname`, feel free to reject if you don’t see it being useful. It was just an idea.

**Comment by infinisil** [comment]
Nice thanks! `pkgsText` sounds good. `usePname` seems a bit odd, I think it's better to remove it from this PR. Otherwise everything looks good.

**Comment by schuelermine** [comment]
Do you want to include the refactor? I originally made it to make adding `usePname` easier but it might actually be easier to read this way anyway.

**Comment by schuelermine** [comment]
I have removed `usePname`

**Comment by schuelermine** [comment]
Last-minute change! I’ve added a test that `mkPackageOption` does in fact use the package set passed to it

**Review by infinisil — APPROVED** [review]
Nice thanks!

**Pull request merged**
