### PR TITLE
why3: 1.3.3 -> 1.4.0

### PR DESCRIPTION
**Pull request by yrashk**
###### Motivation for this change

New release with a lot of updates

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 121231` at 4b8814f3 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/9c214d58b80e15a6a575dae2f24cc238">framac</a></li>
  </ul>
</details>
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>why3</li>
  </ul>
</details>
<details>
  <summary>3 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern 'js_of_ocaml.ppx' doesn't match anything in file 'Makefile.in'
Near pkgs/applications/science/logic/why3/default.nix:43:0:
```
   |
43 |     description = "A platform for deductive program verification";
   | ^
```
</li>
    <li>warning: unused-argument

Unused argument: `fetchpatch`.
Near pkgs/applications/science/logic/why3/default.nix:1:26:
```
  |
1 | { callPackage, fetchurl, fetchpatch, lib, stdenv
  |                          ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`lgpl21` is a deprecated license, please check if project uses `lgpl21Plus` or `lgpl21Only` and change `meta.license` accordingly.

Near pkgs/applications/science/logic/why3/default.nix:45:5:
```
   |
45 |     license     = licenses.lgpl21;
   |     ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

**Review by vbgl — CHANGES_REQUESTED** [review]
This breaks Frama-C.

**Comment by vbgl** [comment]
Frama-C Vanadium is out (rc1). I guess it can be updated in `nixpkgs` as part of this PR.

**Comment by vbgl** [comment]
Also, the `postPatch` hook should be removed.

**Comment by vbgl** [comment]
Subsumed by #128073

**Pull request closed without merging**
