### PR TITLE
gn: 20180423 -> 20180830

### PR DESCRIPTION
**Pull request by YorikSar**
gn sources have been moved into separate repository which greatly
simplify build process.

###### Motivation for this change

We need to update gn to build latest Chromium.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

On macOS I can't build this with sandbox as it links with system frameworks, so built w/o sandbox.

---

CC @stesie @matthewbauer

### CODE REVIEW

**Comment by YorikSar** [comment]
@bendlas @7c6f434c @vcunat As this is related to Chromium and you usually help with review there, could you please help out here as well?

**Comment by volth** [comment]
is there a way to tell ofborg to do ```nix-build --check``` forcing re-building of FOD instead of fetch it from cache ?

**Comment by volth** [comment]
https://github.com/NixOS/nixpkgs/pull/46718

**Comment by volth** [comment]
Unstable hash of ```fetchgit``` with fully specified ```rev``` (not branch/tag name) is weird :(

**Pull request merged**
