### PR TITLE
vscode, vscodium: 1.48.1 -> 1.48.2

### PR DESCRIPTION
**Pull request by JesusMtnez**
###### Motivation for this change

Bump `vscode` and `vscodium` to 1.48.2

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Synthetica9** [comment]
Please use a more descriptive name for the commits, similar to the title of
this pull request

**Comment by JesusMtnez** [comment]
@Synthetica9 I have amended those commits to fit contribution recommendations. Thank you!!

**Review by danieldk — APPROVED** [review]

**Comment by danieldk** [comment]
@JesusMtnez Thank you for your first contribution :+1: .

**Comment by JesusMtnez** [comment]
Thank you! Really easy to do, really nice organization. :smile: :sunglasses:

**Pull request merged**
