### PR TITLE
Remove lots of pygtk using software

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
A lot of these programs that use pygtk, which is using python2, are just completely abandoned and nixpkgs doesn't need to hold onto them.

Additionally, there's certain packages that in their latest released version don't use deprecated bindings. I will try to handle some of these updates.

---

~This is a draft. I'm not finished so review isn't needed just yet.~

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by worldofpeace** [comment]
@romildo connman-notify is marked as broken here. In later versions it has been ported to python3.
Are you still interested in maintaining this?

**Comment by romildo** [comment]
I am still using phwmon to monitor cpu, memory, etc. with light window managers like openbox, fluxbox and awesome. It is working well for me.

**Comment by romildo** [comment]
> @romildo connman-notify is marked as broken here. In later versions it has been ported to python3.
> Are you still interested in maintaining this?

Yes, I am. I will take a look at the python3 based version.

I am waiting for a release of connman with good integration with iwd to make connman my network manager of choice.

**Comment by worldofpeace** [comment]
> I am still using phwmon to monitor cpu, memory, etc. with light window managers like openbox, fluxbox and awesome. It is working well for me.

Thanks. That was one of the entries I had a strong feeling was going to become a dropped commit :+1:

**Comment by worldofpeace** [comment]
Though it's actually a pretty small script, it could be easily ported to python3 and gobject bindings
* https://gitlab.com/o9000/phwmon/blob/master/phwmon.py

**Comment by veprbl** [comment]
cc @dgonyeo

**Comment by worldofpeace** [comment]
@veprbl As stated, this PR isn't ready for review because  I'm not certain all removed packages are appropriate. So I don't really want to attract to much attention like people's packages are in danger of removal.

**Comment by 7c6f434c** [comment]
>@veprbl requested your review on: NixOS/nixpkgs#74295 Remove lots of pygtk using software.

Yeah, Uzbl stopped doing any releases around moving to WebKit2, and then just withered away, fine to drop

(by that time I was not closely following, as after Opera becoming Chromium clone I minimised my use of WebKit/Blink)

**Comment by romildo** [comment]
> > @romildo connman-notify is marked as broken here. In later versions it has been ported to python3.
> > Are you still interested in maintaining this?
> 
> Yes, I am. I will take a look at the python3 based version.
> 
> I am waiting for a release of connman with good integration with iwd to make connman my network manager of choice.

Updated connman-notify: https://github.com/NixOS/nixpkgs/pull/74321

**Comment by romildo** [comment]
> Though it's actually a pretty small script, it could be easily ported to python3 and gobject bindings
> 
>     * https://gitlab.com/o9000/phwmon/blob/master/phwmon.py

Issue entry in upstream: https://gitlab.com/o9000/phwmon/issues/4

**Comment by veprbl** [comment]
@worldofpeace Sorry, I didn't mean to cause any trouble here.

**Comment by worldofpeace** [comment]
Going to leave some of my research on the remaining packages here:
* ocropus has a fork kraken that supports python3
there's also a wip PR:
https://github.com/tmbdev/ocropy/pull/319

* pmenu has no activity of a python3 port
https://gitlab.com/o9000/pmenu cc @romildo 

* xdgmenumaker supports python3
https://github.com/gapan/xdgmenumaker#about cc @romildo 

* problematic claws mail python2 plugins
For the foreseeable future, python3 gtk won't be supported unless claws is ported to gtk3.
https://www.thewildbeast.co.uk/claws-mail/bugzilla/show_bug.cgi?id=4271
Taking no action as it's optional off by default.

* is nicotine-plus abandoned?
there's an issue upstream. https://github.com/Nicotine-Plus/nicotine-plus/issues/99.
Package was added 10 months ago.

* screenkey is missing python3 support
no issue upstream https://gitlab.com/wavexx/screenkey.

* keybinder is likely obsolete to keybinder3?
[Keybinder doesn't appear to touch python anymore](https://github.com/kupferlauncher/keybinder/blob/04ae06724d914c7d4fec6a2723edf9c6320ec502/NEWS)

* libappindicator :frowning: 
Remove python completely
https://src.fedoraproject.org/rpms/libappindicator/blob/master/f/nopython.patch

* mpdris2 has python3 support
cc @pjones 

* gpsd has python3 support https://gitlab.com/gpsd/gpsd needs update.
cc  @bjornfor @rasendubi

* solfege has python3 support https://sourceforge.net/projects/solfege/ (it's in the description)
cc @bjornfor

**Comment by jtojnar** [comment]
Screenkey is irreplaceable when I want to record a bug triggered by keyboard shortcuts, issue here: https://gitlab.com/wavexx/screenkey/issues/3

Regarding gpsd https://github.com/NixOS/nixpkgs/issues/35604

**Comment by worldofpeace** [comment]
> Regarding gpsd #35604

Cool, diff looks usable.

**Comment by worldofpeace** [comment]
Going to try to leave this PR at what it is currently.

Please ignore the missing `# added` in aliases.nix. I'll fix that up later.

**Comment by Fuuzetsu** [comment]
>A lot of these programs that use pygtk, which is using python2, are just completely abandoned and nixpkgs doesn't need to hold onto them.

I don't understand. Presumably a lot of these packages actually still work as-is? Part of the beauty of nix is that we can have these live along new packages without worrying about version mismatches.

w.r.t. mcomix, it hasn't had a release for a while [but it's not completely dead](https://sourceforge.net/p/mcomix/git/ci/486f02eef164df451a72598ce5989a1b37b49c60/log/?path=) and [there's even MR for gtk3 support](https://sourceforge.net/p/mcomix/git/merge-requests/7/). 

Unless the packages are broken, why remove them?

**Comment by worldofpeace** [comment]
> > A lot of these programs that use pygtk, which is using python2, are just completely abandoned and nixpkgs doesn't need to hold onto them.
> 
> I don't understand. Presumably a lot of these packages actually still work as-is? Part of the beauty of nix is that we can have these live along new packages without worrying about version mismatches.
> 
> w.r.t. mcomix, it hasn't had a release for a while [but it's not completely dead](https://sourceforge.net/p/mcomix/git/ci/486f02eef164df451a72598ce5989a1b37b49c60/log/?path=) and [there's even MR for gtk3 support](https://sourceforge.net/p/mcomix/git/merge-requests/7/).
> 
> Unless the packages are broken, why remove them?

These are slight assumptions. I've mostly opened this so we can track what can be dropped that will never be ported, and what may have ports in process. Requesting review of the respective maintainers is part of this, so thank you for sharing this.

The premise of this PR is basically https://github.com/NixOS/nixpkgs/pull/74282#issuecomment-559125236. pygtk and python2 are deprecated. The underlying libraries don't have maintainers, so it doesn't matter if they're broken yet. There's nothing there to ensure their continued function.
I started at the most critical severity, removal, because nixpkgs already has a large problem of packages with no maintainers and scattered abandonware.

**Comment by worldofpeace** [comment]
Actually @Fuuzetsu, after some more research there's a fork of mcomix, mcomix3, that supports gtk3
* https://github.com/multiSnow/mcomix3

I think we should follow fedora and package that to supersede the previous package
* https://src.fedoraproject.org/rpms/mcomix/c/d1de9b3e59de4e236a6c7f751c091eb436a11c8c?branch=master

**Comment by jtojnar** [comment]
> Presumably a lot of these packages actually still work as-is?

They do not. pygtk no longer builds with current pango.

We have these options:

1. Staying at pango 1.43 and having to backport all the CVE fixes. (That is what we are doing now: https://github.com/NixOS/nixpkgs/pull/71660)
2. Duplicating pango fixed at the old version and all its reverse dependencies and having pygtk apps use that. (That is what https://github.com/NixOS/nixpkgs/pull/74282 attempted before realizing that reverse dependencies need to be duplicated as well.)
3. Reviving pygtk ourselves, fixing all the incompatibilities. (It looks like this is the direction we are going: https://github.com/NixOS/nixpkgs/pull/74282#issuecomment-559125236)
4. Mark pygtk as broken or drop it completely. (This would be the most pleasant variant for us.)

**Comment by worldofpeace** [comment]
And I'd say we've agreed on going the #3 route because we won't be removing every single package that depends on pygtk. However, it's only temporary, eventually pygtk will have to be removed. But that's not going to happen right away. It's slightly more demanding on the maintainers to do this for now, but it will cause less a disruption to users.

**Comment by Fuuzetsu** [comment]
> > > A lot of these programs that use pygtk, which is using python2, are just completely abandoned and nixpkgs doesn't need to hold onto them.
> > 
> > 
> > I don't understand. Presumably a lot of these packages actually still work as-is? Part of the beauty of nix is that we can have these live along new packages without worrying about version mismatches.
> > w.r.t. mcomix, it hasn't had a release for a while [but it's not completely dead](https://sourceforge.net/p/mcomix/git/ci/486f02eef164df451a72598ce5989a1b37b49c60/log/?path=) and [there's even MR for gtk3 support](https://sourceforge.net/p/mcomix/git/merge-requests/7/).
> > Unless the packages are broken, why remove them?
> 
> These are slight assumptions. I've mostly opened this so we can track what can be dropped that will never be ported, and what may have ports in process. Requesting review of the respective maintainers is part of this, so thank you for sharing this.
> 
> The premise of this PR is basically [#74282 (comment)](https://github.com/NixOS/nixpkgs/pull/74282#issuecomment-559125236). pygtk and python2 are deprecated. The underlying libraries don't have maintainers, so it doesn't matter if they're broken yet. There's nothing there to ensure their continued function.
> I started at the most critical severity, removal, because nixpkgs already has a large problem of packages with no maintainers and scattered abandonware.

I think technically (sadly) Python 2.7 is still not deprecated (https://pythonclock.org/).

>I think we should follow fedora and package that to supersede the previous package

Sounds good to me.

>They do not. pygtk no longer builds with current pango.

I see.

**Comment by 7c6f434c** [comment]
> pygtk and python2 are deprecated. The underlying libraries don't have maintainers, so it doesn't matter if they're broken yet.

I think it is a pretty strong claim (there are some upstream-unmaintained packages that caused no trouble in ten years), but it is not needed to make the point anyway: all versions of pango are slightly broken, and they are also incompatible with each other, so I agree that pygtk does actively create a pain.

**Comment by worldofpeace** [comment]
Details for planner https://github.com/NixOS/nixpkgs/issues/74949.

**Comment by romildo** [comment]
>     * pmenu has no activity of a python3 port
>       https://gitlab.com/o9000/pmenu cc @romildo

I consider [jgmenu](https://jgmenu.github.io/) to be a successor of pmenu, and it is more complete. It has a module based on pmenu. Therefore pmenu can be removed.

**Comment by worldofpeace** [comment]
> > ```
> > * pmenu has no activity of a python3 port
> >   https://gitlab.com/o9000/pmenu cc @romildo
> > ```
> 
> I consider [jgmenu](https://jgmenu.github.io/) to be a successor of pmenu, and it is more complete. It has a module based on pmenu. Therefore pmenu can be removed.

Thanks, I've removed it here. I'll assume you'd package that when it's ready.
It would be nice if there was someway to poll cache.nixos.org for a popularity contest on the packages.

**Comment by romildo** [comment]
> > I consider [jgmenu](https://jgmenu.github.io/) to be a successor of pmenu, and it is more complete. It has a module based on pmenu. Therefore pmenu can be removed.
> 
> Thanks, I've removed it here. I'll assume you'd package that when it's ready.

@worldofpeace Do you mean packaging [jgmenu](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/jgmenu/default.nix)? It is already packaged.

**Comment by worldofpeace** [comment]
> > > I consider [jgmenu](https://jgmenu.github.io/) to be a successor of pmenu, and it is more complete. It has a module based on pmenu. Therefore pmenu can be removed.
> > 
> > 
> > Thanks, I've removed it here. I'll assume you'd package that when it's ready.
> 
> @worldofpeace Do you mean packaging [jgmenu](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/jgmenu/default.nix)? It is already packaged.

Ah :rofl:  Minor dyslexia on my side with the g's and q's.
(fuzzy search of jqmenu obviously didn't work)

**Comment by romildo** [comment]
> * 
> 
> * xdgmenumaker supports python3
>   https://github.com/gapan/xdgmenumaker#about cc @romildo

Migrated to python3 in https://github.com/NixOS/nixpkgs/pull/75015.

**Comment by worldofpeace** [comment]
Here's info about mcomix3 https://github.com/NixOS/nixpkgs/issues/75028.

**Comment by worldofpeace** [comment]
`uzbl` and `pywebkitgtk` got moved into #75040.

**Pull request merged**
