### PR TITLE
fsv: 0.9-1 -> 3.0

### PR DESCRIPTION
**Pull request by SFrijters**
###### Description of changes

The original 0.9-1 fork is unmaintained:
https://github.com/mcuelenaere/fsv/commit/4ef9040fcf14cddd52d79dad87a80355fc885602

The new 3.0 version uses a new fork https://github.com/jabl/fsv

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SFrijters** [comment]
Result of `nixpkgs-review pr 193491` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>fsv</li>
  </ul>
</details>

**Comment by rnhmjoj** [comment]
It seems to be somewhat broken: the context menus in the sidebar are empty (at least they're also in the main view, so it's probably ok). Also it crashes right away if you switch to tree view in a relatively large directory (not that the previous fsv would be usable in this situation).

**Comment by SFrijters** [comment]
Hm, indeed I can reproduce the tree view crash...

```
fsv:ERROR:../src/geometry.c:1415:geometry_treev_platform_theta: assertion failed: (!geometry_treev_is_leaf( dnode ) || NODE_IS_METANODE(dnode))
Bail out! fsv:ERROR:../src/geometry.c:1415:geometry_treev_platform_theta: assertion failed: (!geometry_treev_is_leaf( dnode ) || NODE_IS_METANODE(dnode))
```

I'm not sure what you mean by the context menus in the sidebar though; the side bars are populated for me and I can click on items to have the main view move to them, but what are the context menus supposed to be/do?

The existing 0.9 version also didn't work well for me (but I didn't spend a lot of time with it), so I tried to do this upgrade. But if you think the new fork is not good enough (yet), feel free to close this PR.

**Comment by rnhmjoj** [comment]
> what are the context menus supposed to be/do?

If you right click on an entry it would previously show options to expand, look at etc. Now I only get a small empty menu flashing for a second.

> But if you think the new fork is not good enough (yet), feel free to close this PR.

I'm not sure: getting rid of some of the gtk/autoconf cruft is by itself tempting.
What didn't work before that this version fixed?

**Comment by SFrijters** [comment]
The 0.9 version was very unresponsive and I had (one time) a hard crash, when I was running it from a nixpkgs clone as the root directory (which is quite hefty of course). But I tried again just now and it seems better (still stuttery animation, but no freezes); I don't know what's different from before. I now definitely see your point on the missing menus etc. though.
The upstream transition to GTK3 is quite recent, so maybe quality will improve further still; I might file an issue or two if I find the time.

**Comment by rnhmjoj** [comment]
Considering this is not exactly a critical piece of software, it's probably ok for now. Let's merge this.

**Pull request merged**
