### PR TITLE
tandoor-recipes: 1.4.4 -> 1.4.9

### PR DESCRIPTION
**Pull request by ambroisie**
###### Description of changes

Updates the package that wasn't auto-updated by @r-ryantm, and address #229894 breaking the build.

Changelog: [1.4.4...1.4.9](https://github.com/TandoorRecipes/recipes/compare/1.4.4...1.4.9)

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Please include the relevant changelogs in your commit messages.

**Comment by ambroisie** [comment]
@mweinelt done :-)

**Comment by mweinelt** [comment]
https://github.com/hhursev/recipe-scrapers/releases/tag/14.36.1
https://github.com/hhursev/recipe-scrapers/releases/tag/14.36.0
https://github.com/hhursev/recipe-scrapers/releases/tag/14.35.1
https://github.com/hhursev/recipe-scrapers/releases/tag/14.35.0
https://github.com/hhursev/recipe-scrapers/releases/tag/14.34.0
https://github.com/hhursev/recipe-scrapers/releases/tag/14.33.0

https://github.com/BITSOLVER/django-js-reverse/releases/tag/0.10.1-b0

And the django-js-reverse commit should mention, that we are moving towards a fork, because the upstream project is unmaintained.

**Comment by ambroisie** [comment]
Alright, will change the format!

**Comment by ambroisie** [comment]
Sorry about the churn :upside_down_face:.

**Comment by Stunkymonkey** [comment]
@ambroisie is it a good idea to backport this to 22.11?
I am getting the error you fixed here: https://github.com/TandoorRecipes/recipes/pull/2458

**Comment by ambroisie** [comment]
@Stunkymonkey I do not run the release branches and don't test on there, if this fixes your issue I'll backport it.

**Pull request merged**
