### PR TITLE
crashplan: 4.6.0-r3 -> 4.7.0

### PR DESCRIPTION
**Pull request by jerith666**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by domenkozar** [comment]
@jerith666 did you run this and test it works?

**Comment by jerith666** [comment]
Yeah, it's working fine for me.  I don't understand the Travis CI failure ... ?

**Comment by joachifm** [comment]
The linux run is fine, the osx one fails due to `nox`.

**Comment by domenkozar** [comment]
travis-ci is a bit broken atm, will resolve in a few days.

**Pull request merged**
