### PR TITLE
k3s: 1.30.1+k3s1 -> 1.30.2+k3s2

### PR DESCRIPTION
**Pull request by wrmilling**
## Description of changes

Updating k3s (k3s_1_30) to 1.30.2+k3s2

Changelog: https://github.com/k3s-io/k3s/releases/tag/v1.30.2%2Bk3s2

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>k3s</li>
  </ul>
</details>

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by superherointj** [comment]
Is update script not working?

**Comment by wrmilling** [comment]
> Is update script not working?

I used the update script for this PR, but build was failing on master until go 1.22.4 got merged from staging. I am sure the bot would have caught it eventually, but I figured I would create it since I was checking.

**Comment by superherointj** [comment]
> > Is update script not working?
> 
> I used the update script for this PR, but build was failing on master until go 1.22.4 got merged from staging. I am sure the bot would have caught it eventually, but I figured I would create it since I was checking.

Whenever the bot is not proposing PRs, we have to check update script logs, like:
> https://r.ryantm.com/log/k3s/2024-07-06.log

The [commit message](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions) is missing from release:

> Release: https://github.com/k3s-io/k3s/releases/tag/v1.30.2%2Bk3s1

I'll just run tests and we can have this merged shortly.

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 325894` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Review by superherointj — APPROVED** [review]

**Comment by wrmilling** [comment]
@NixOS/nixpkgs-merge-bot merge

**Pull request merged**
