### PR TITLE
lkl: 2017-10-18 -> 2017-11-10, make-disk-image: do not fake time for cptofs 

### LINKED ISSUE #393: Preserving file times when copying with cptofs
I need all my files inside my image to have a UNIX timestamp of 1. If I just use `cptofs` normally, it uses the current time. I can use `libfaketime` to fool `cptofs` into thinking that the current time is 1, but oddly enough all the timestamps in the image come out as 2 instead of 1.

So now I'm confused what's going on. Can `cptofs` get an option to preserve file times, or if not, does anyone know why all my timestamps are getting incremented by 1 before making it into the image?

If I tell `cptofs` that the time is 0, all my timestamps in the image are 1, so I'm not stuck, but it would be nice if this behaved more intuitively.

cc @dezgeg

### PR DESCRIPTION
**Pull request by orivej**
###### Motivation for this change

New LKL has fixed https://github.com/lkl/linux/issues/393, so we can partially revert f5b3f2c5a7f2b51e80ac32fb47fd1d7d3e475ad1. I've confirmed that `/nix/store` paths in the resulting image are dated `1970-01-01 00:00:01`.

@copumpkin Should we remove `faketime` for `mkfs`? What purpose does it serve?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - nixos/tests/ec2.nix
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dezgeg** [comment]
I presume `faketime` on mkfs affects the timestamp of `/lost+found`. But IIRC it's impossible to make binary-reproducible ext4 images no matter flags you pass to mkfs (unless the situation has changed).

**Comment by orivej** [comment]
Good guess! Note that without faketime before cptofs the files other than those in the `/nix/store` have recent times:
```
   Date      Time    Attr         Size   Compressed  Name                                                                                                                                                                           
------------------- ----- ------------ ------------  ------------------------                                                                                                                                                       
1970-01-01 00:00:01 D....                            lost+found                                                                                                                                                                     
2017-11-11 20:30:10 D....                            bin                                                                                                                                                                            
2017-11-11 20:29:45 D....                            dev                                                                                                                                                                            
2017-11-11 20:30:26 D....                            etc                                                                                                                                                                            
2017-11-11 20:29:45 D....                            home                                                                                                                                                                           
2017-11-11 20:29:45 D....                            nix                                                                                                                                                                            
2017-11-11 20:29:45 D....                            proc                                                                                                                                                                           
2017-11-11 20:30:10 D....                            root                                                                                                                                                                           
2017-11-11 20:30:26 D....                            run                                                                                                                                                                            
2017-11-11 20:29:45 D....                            sys
2017-11-11 20:30:27 D....                            tmp
2017-11-11 20:29:45 D....                            var
2017-11-11 20:30:26 D....                            boot
2017-11-11 20:30:10 .....           65         4096  bin/sh
2017-11-11 20:30:10 .....            0            0  etc/NIXOS
2017-11-11 20:30:26 D....                            etc/nixos
2017-11-11 20:30:02 D....                            nix/store
2017-11-11 20:29:45 D....                            nix/var
1970-01-01 00:00:01 D....                            nix/store/p7i8r2icyrdd21gpy7ljbxqdxaz7mv03-unit-serial-getty-.service
1970-01-01 00:00:01 D....                            nix/store/bx6nz9yxm99gli10280l7apy5dkc3vh1-bzip2-1.0.6.0.1-man
1970-01-01 00:00:01 D....                            nix/store/i9xmmmsxhk4rpmc3flvk00jdwyjf9fyf-nixos-system-unnamed-18.03.git.b888ee7
```
I'm going to remove `faketime` them.

**Comment by orivej** [comment]
Done.

**Comment by orivej** [comment]
After a part of ec2 tests (`nix-build nixos/tests/ec2.nix`) pass, I'm seeing this failure both with the current master and with this PR: https://gist.github.com/orivej/64a9ad44da2140f10f8ef303b26e035a . It seems related to this comment: https://github.com/NixOS/nixpkgs/blob/1503409aac75ebae42ede986ff0ed964174f1236/nixos/tests/ec2.nix#L31-L34 Could you reproduce it and help with the fix?

**Comment by dezgeg** [comment]
I cherry-picked this to 17.09 because the faketime was apparently breaking the OVA build. Really strange.

**Comment by copumpkin** [comment]
I've been meaning to look into the EC2 test for a while, but I don't really have a machine that can virtualize linux nicely, so it's hard for me to experiment for now. I'm guessing we just need to make sure some of its dependencies are in the store, but it's hard to tell what it wants from the log.

**Pull request merged**
