### PR TITLE
nix-ld-rs: init at 2024-03-23

### PR DESCRIPTION
**Pull request by Mic92**
## Description of changes

This pull requests add nix-ld-rs as an alternative implementation for nix-ld.
After a testing phase the plan is to merge nix-ld-rs into nix-ld.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Maybe this would be a good point to also rework baseLibraries, so that any addition to it does not overwrite all default entries. https://github.com/NixOS/nixpkgs/blob/nixos-23.11/nixos/modules/programs/nix-ld.nix#L19C3-L19C17

**Review by SuperSandro2000 — APPROVED** [review]
VSCode continues to work like before on WSL

**Comment by Mic92** [comment]
> Maybe this would be a good point to also rework baseLibraries, so that any addition to it does not overwrite all default entries. https://github.com/NixOS/nixpkgs/blob/nixos-23.11/nixos/modules/programs/nix-ld.nix#L19C3-L19C17

Maybe they could be exposed as a readable option? Because there are cases where you want to override the default list. Anyway I find this is an orthogonal problem.

**Comment by SuperSandro2000** [comment]
If we set them in config, they could be overwritten completely with mkForce

**Comment by Mic92** [comment]
> If we set them in config, they could be overwritten completely with mkForce

Feel free to make a pull request, but please also drop a release not item because nix-ld is widely used and this may be a surprising change.

**Comment by SuperSandro2000** [comment]
please see #299576

**Pull request merged**
