### PR TITLE
malcontent: 0.6.0 → 0.7.0

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
Changes: https://gitlab.freedesktop.org/pwithnall/malcontent/-/commit/2e8a07d58c047f757e36a5fcf1d5b76faae08e75

Allows us to split the UI package.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
On staging gnome-initial-setup depends on `malcontent-ui` so we will need to disable it first. See  #83403.

**Review by worldofpeace — APPROVED** [review]
I made two minor changes, and I read over https://gitlab.freedesktop.org/pwithnall/malcontent/-/merge_requests/38 and the patches. It sucks we can't get perfect separation.
Installed tests work for me also (though I got a weird unreproducible failure when I first built them).

**Comment by worldofpeace** [comment]
Forgot to mention motivation for enabling accounts-service in the module. It does require it so we should just do it there anyways.

**Comment by jtojnar** [comment]
@GrahamcOfBorg eval

**Comment by jtojnar** [comment]
@GrahamcOfBorg eval

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

**Comment by grahamc** [comment]
(note I'm actively debugging this)

**Pull request merged**
