### PR TITLE
nexus: 3.12.1 -> 3.14.0-04

### PR DESCRIPTION
**Pull request by zaninime**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by zaninime** [comment]
// cc @aespinosa @ironpinguin @ma27

**Comment by Ma27** [comment]
@GrahamcOfBorg build nexus
@GrahamcOfBorg test nexus

**Comment by aespinosa** [comment]
Lgtm

**Comment by Ma27** [comment]
The test fails locally as it's lacking disk space (it seems as they've increased the minimum diskspace to 4096MB). If I manage to fix that, I'll push a fix :)

**Review by Ma27 — APPROVED** [review]

**Comment by Ma27** [comment]
As ofborg evaluates successfully and the test passes again, let's merge this :+1:

**Comment by Ma27** [comment]
@zaninime thanks!

**Comment by zaninime** [comment]
:+1 does it make sense that we backport this to 18.09?

**Comment by Ma27** [comment]
Are there any important patches like security fixes in 3.14 or 3.13? Unless I'm not sure if we want to backport the change, but feel free to open a PR with the patches against `release-18.09` and discuss this with some more maintainers :)

**Pull request merged**
