### PR TITLE
nodePackages.cbmp: init at 1.1.1

### PR DESCRIPTION
**Pull request by mrtnvgr**
## Description of changes

This PR adds cbmp node package to nixpkgs.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by diniamo** [comment]
Any update on this? I failed to package it myself so it would be nice to merge this.

**Comment by mrtnvgr** [comment]
I'm generating the files now.

**Comment by diniamo** [comment]
The version in the title should be changed to 1.1.1

**Comment by diniamo** [comment]
And also, the package fails to build, you're missing
```nix
nativeBuildInputs = [pkgs.makeWrapper];
```
from the override, which if I add, I arrive at the same error I got while trying to package this in my own repo:
<details>

```js
node:internal/modules/cjs/loader:1143
  const err = new Error(message);
              ^

Error: Cannot find module '@resvg/resvg-js-linux-x64-gnu'
Require stack:
- /nix/store/03bhxalgkribmyb96wrh2vssvqqzpqi3-cbmp-1.1.1/lib/node_modules/cbmp/node_modules/@resvg/resvg-js/js-binding.js
- /nix/store/03bhxalgkribmyb96wrh2vssvqqzpqi3-cbmp-1.1.1/lib/node_modules/cbmp/node_modules/@resvg/resvg-js/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/nix/store/03bhxalgkribmyb96wrh2vssvqqzpqi3-cbmp-1.1.1/lib/node_modules/cbmp/node_modules/@resvg/resvg-js/js-binding.js:1:3488)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/03bhxalgkribmyb96wrh2vssvqqzpqi3-cbmp-1.1.1/lib/node_modules/cbmp/node_modules/@resvg/resvg-js/js-binding.js',
    '/nix/store/03bhxalgkribmyb96wrh2vssvqqzpqi3-cbmp-1.1.1/lib/node_modules/cbmp/node_modules/@resvg/resvg-js/index.js'
  ]
}

Node.js v20.12.2
```
</details>

**Comment by mrtnvgr** [comment]
This package should work https://github.com/mrtnvgr/nurpkgs/blob/master/pkgs/misc/cbmp/default.nix

**Comment by diniamo** [comment]
Okay so, from what I can tell, this doesn't work because of #36981

**Comment by Luflosi** [comment]
Could this be done using [buildNpmPackage](https://nixos.org/manual/nixpkgs/stable/#javascript-buildNpmPackage)?

**Comment by mrtnvgr** [comment]
> This package should work https://github.com/mrtnvgr/nurpkgs/blob/master/pkgs/misc/cbmp/default.nix

I have this package made with `buildNpmPackage`. Is it okay if I commit it here?

**Comment by pyrox0** [comment]
> > This package should work [mrtnvgr/nurpkgs@`master`/pkgs/misc/cbmp/default.nix](https://github.com/mrtnvgr/nurpkgs/blob/master/pkgs/misc/cbmp/default.nix?rgh-link-date=2024-06-14T03%3A06%3A44Z)
> 
> I have this package made with `buildNpmPackage`. Is it okay if I commit it here?

Yes, please do so. As it's a new package, it should go under pkgs/by-name!

**Pull request closed without merging**
