### PR TITLE
maestral-gui: fix build by using compatible maestral library

### PR DESCRIPTION
**Pull request by SFrijters**
###### Description of changes

Latest (automatic?) Python update (a3f1b8c2ad99ceccb1f1f995ea4f9e72704423fd) broke maestral-qt, which is being held back  at version 1.5.3 by the PyQt6 requirement of its latest versions.
Solution: use the old matching maestral version for now. 
I did this rather inelegantly; if someone could tell me the magic incantation to override version/hash inside a Python package in the Python package set that may be a cleaner option.

Added myself as a maintainer since this is not the first time surprise updates related to these packages broke my system and I've done many updates to these packages in the past.

@peterhoeg @mweinelt 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SFrijters** [comment]
Result of `nixpkgs-review pr 184177` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>maestral-gui</li>
    <li>python310Packages.maestral_1_5_3</li>
    <li>python39Packages.maestral_1_5_3</li>
  </ul>
</details>

**Comment by peterhoeg** [comment]
I'd just use `overridePackages` together with `overridePythonAttrs` instead of duplicating everything.

**Comment by peterhoeg** [comment]
I will also suggest having a look at https://github.com/NixOS/nixpkgs/pull/183963 to see how the pythonpath bit can be made *much* shorter.

**Comment by SFrijters** [comment]
Result of `nixpkgs-review pr 184177` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>maestral-gui</li>
  </ul>
</details>

**Comment by SFrijters** [comment]
Redid the PR using `overridePythonAttrs`.
@peterhoeg I'm not sure what else I can do to shrink the `PYTHONPATH` code, I already copied your changes to maestral in maestral-qt.

**Comment by peterhoeg** [comment]
The override isn't "allowed" to be in `all-packages.nix`. So you just do the python3 override inside `maestral-qt/default.nix` instead.

Since we have multiple calls to `makePythonPath` I would do `inherit (python3.pkgs) makePythonPath` at the very top (where you will be override python3 as well).

**Comment by peterhoeg** [comment]
I pushed to your branch as it's easier to show what I mean this way.

**Comment by SFrijters** [comment]
@peterhoeg Thanks, I absorbed your changes to keep a clean history.

**Pull request merged**
