### PR TITLE
androidenv: autogenerated build-tools and addons repositories

### PR DESCRIPTION
**Pull request by yorickvP**
###### Motivation for this change

This PR adds two features to the androidenv packages: multiple versions of the android build-tools, and
the google addon repository.

Android apps commonly depend on multiple and/or specific versions of the android build tools. Add support for the buildToolsVersions argument to androidenv, just like platformVersions, in order to support this.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by yorickvP** [comment]
@taku0 @svanderburg @primeos @rasendubi please look into this if you have time :)

**Comment by rasendubi** [comment]
Oh, that's nice!

@GrahamcOfBorg build androidenv.buildTools_all androidenv

**Comment by rasendubi** [comment]
Can we add build-tools-26.0.2, so I can close #36911?

**Comment by taku0** [comment]
Maybe, `fetch.sh` also should be updated.

**Review by matthewbauer — CHANGES_REQUESTED** [review]
Resolve merge conflict

**Comment by tadfisher** [comment]
@yorickvP Can you rebase please?

**Comment by mmahut** [comment]
What is the status of this pull request?

**Comment by yorickvP** [comment]
I think this is outdated now. If there is still an interest in these features I can take a look at it again.

**Pull request closed without merging**
