### PR TITLE
vscode-extensions.vadimcn.vscode-lldb: 1.6.1 -> 1.6.4

### PR DESCRIPTION
**Pull request by oxalica**
###### Motivation for this change

Version bump. Also fix the error `unable to locate lldb-server`.
Tested via debugging simple rust code in vscode.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
  911.6M -> 781.9M
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 119945` at 0976b4e6 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
  </ul>
</details>
<details>
  <summary>3 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/fixup-phase.md">fixup-phase</a>

`fixupPhase` should not be overridden, use `postFixup` instead.

Near pkgs/misc/vscode-extensions/vscode-lldb/default.nix:83:3:
```
   |
83 |   fixupPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/misc/vscode-extensions/vscode-lldb/default.nix:53:15:
```
   |
53 |   patches = [ ./cmake-build-extension-only.patch ];
   |               ^
```
</li>
    <li>warning: unused-argument

Unused argument: `jq`.
Near pkgs/misc/vscode-extensions/vscode-lldb/default.nix:1:60:
```
  |
1 | { lib, stdenv, fetchFromGitHub, rustPlatform, makeWrapper, jq, callPackage
  |                                                            ^
```
</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Please remove jq from inputs and use postFixup like the bot discovered.

**Comment by oxalica** [comment]
ping @SuperSandro2000

**Comment by oxalica** [comment]
Seems the extension on master is broken due to splitting output of lldb. This update fixes that issue. Now ready to be reviewed.

**Pull request merged**
