### PR TITLE
emacs: integrate macport into generic drv 

### PR DESCRIPTION
**Pull request by Atemu**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Atemu** [comment]
I have no idea why the release checks fail. The attribute evals just fine when building.

**Comment by Atemu** [comment]
Result of `nixpkgs-review` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>cedille</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>agda</li>
    <li>macvim</li>
    <li>python310Packages.notmuch</li>
    <li>python310Packages.pycflow2dot</li>
    <li>vimacs</li>
  </ul>
</details>
<details>
  <summary>22 packages built:</summary>
  <ul>
    <li>aerc</li>
    <li>afew</li>
    <li>auctex</li>
    <li>cask</li>
    <li>cflow</li>
    <li>cscope</li>
    <li>emacs</li>
    <li>emacs-nox</li>
    <li>emacsMacport</li>
    <li>framac</li>
    <li>lieer</li>
    <li>mozart2</li>
    <li>mu</li>
    <li>muchsync</li>
    <li>neomutt</li>
    <li>notmuch</li>
    <li>notmuch-addrlookup</li>
    <li>pycflow2dot (python39Packages.pycflow2dot)</li>
    <li>pydb</li>
    <li>python39Packages.notmuch</li>
    <li>rtags</li>
    <li>why3</li>
  </ul>
</details>

The Agda build was killed manually because it takes so long. The other failures were already broken.

**Comment by doronbehar** [comment]
Quoting ofborg:

```
access to URI 'ftp://ftp.math.s.chiba-u.ac.jp/emacs/emacs-27.2-mac-8.3.tar.gz' is forbidden in restricted mode
```

You should probably switch to an HTTP URL, preferably with a European or US domain. 

There's also merge conflicts now.

**Comment by Atemu** [comment]
I don't think the tarball is available through any other means.

We could build from source instead of the patches but I wanted to preserve the previous status-quo as much as possible.

Is that what causes the [basic eval checks](https://github.com/NixOS/nixpkgs/runs/4846317134?check_suite_focus=true)? Because the URL is unchanged, it was like this before too. The only thing I did change was go from `fetchurl` to `fetchTarball` since it's actually a tarball, not just a file.

**Comment by Atemu** [comment]
Alright, I just tried using the exact same `fetchurl` string again but I still get eval errors. How the hell did it work before and why doesn't it work anymore?

The same ftp server is also used with fetchTarball inside the drv and the eval checks don't complain about that when I comment out the problematic patches fetcher.

What gives?

**Comment by Atemu** [comment]
Should I just give up and build from source instead?

**Comment by AndersonTorres** [comment]
> Should I just give up and build from source instead?

YES

**Comment by AndersonTorres** [comment]
In my not so humble opinion, looking at the huge size of this patch, I think the macport should stay separated.
A whole source input, a set of patches, a set of MacOS-only libraries... All of It makes difficult to read and understand the expression.

**Comment by Atemu** [comment]
> huge size of this patch

It's not very big IMO. In fact, it removes more code than it adds.

> A whole source input, a set of patches

It's one or the other.

> a set of MacOS-only libraries

Many were already present for the upstream NS port of emacs which is different from the macport.

> All of It makes difficult to read and understand the expression.

I disagree. It's trivial to ignore everything guarded behind things like `withMacport` and it isn't really all that much here. The emacs drv is simply a pretty complex thing all-together because emacs itself is a complex piece of software. Nothing wrong with that.

***

The problem with keeping the macport separated is that most of the drv is the same as regular emacs. The only difference would be that you wouldn't have to cater towards Linux toolkits in the macport drv and vice versa.

As macport is being developed with a 28.1 base now, integrating native-comp would mean maintaining even more duplicate code.

**Comment by AndersonTorres** [comment]
Okay then.
Nonetheless your current code is conflicting the repo.

**Comment by Atemu** [comment]
I'll get to that tomorrow hopefully.

**Comment by junyi-hou** [comment]
this is a great patch! it is sad that it hasn't been merged yet. Have you consider publishing it as an overlay?

**Comment by isker** [comment]
> it is sad that it hasn't been merged yet

It can’t be merged because it has merge conflicts.  The conflicts need to be resolved.

**Comment by Atemu** [comment]
It also can't be merged because there's an odd eval error that I need to get rid of first or rip out the tarball build.

If anyone wants to pick this up, feel free because I'm going to have exams for the next few weeks.

**Comment by AndersonTorres** [comment]
Drafting.

**Comment by Atemu** [comment]
Rebased and now building from source. I'll squash some of these together but the end-result will be the same.

**Comment by Atemu** [comment]
The high number of rebuilds are the emacsPackages, no need for staging.

**Comment by dhess** [comment]
Thank you all!

**Pull request merged**
