### PR TITLE
reverse_proxy module: helper to run nginx as reverse proxy

### PR DESCRIPTION
**Pull request by ts468**

### CODE REVIEW

**Comment by ts468** [comment]
What do you think?

**Comment by tomberek** [comment]
Something like this would help cut down the size of a lot of my configuration - until I needed to modify or adjust something (extraConfig needed). Also, how does this interact with the normal nginx configuration? It doesn't seem to add to it, but replace it.

**Comment by ts468** [comment]
@tomberek thanks for your interest! I've updated the module, could you maybe have a look if you can spot anything that should be fixed? Especially, should the default values be changed? Many thanks!

**Comment by ts468** [comment]
@domenkozar Is there a way to re-activate the original PR?

**Comment by domenkozar** [comment]
I don't think so :/

**Pull request merged**
