### PR TITLE
[20.09] bitcoin: 0.20.1 -> 0.21.0

### PR DESCRIPTION
**Pull request by AndersonTorres**
###### Motivation for this change

Repology treats it as outdated and dangerous/vulnerable.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
Why is nomad part of this PR?

**Comment by AndersonTorres** [comment]
No reason at all. I just cherry-picked all related commits to this modification.

**Comment by AndersonTorres** [comment]
No reason at all. I just cherry-picked all related commits to this modification.

**Comment by AndersonTorres** [comment]
No reason at all. I just cherry-picked all related commits to this modification.

**Comment by prusnak** [comment]
> Repology treats it as outdated and dangerous/vulnerable.

Repology is wrong in that regard - 0.20.1 is perfectly fine. I suggest leaving it as it is. And maybe later update it to 0.20.2 if some serious bug fix needs to be backported.

**Comment by AndersonTorres** [comment]
Good to know!

**Pull request closed without merging**
