### PR TITLE
pipenv: patch pipenv to point to python that has virtualenv

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @kaali

### CODE REVIEW

**Comment by FRidh** [comment]
This could also be fixed by creating a `python.withPackages` with all runtimeDeps, and then patching the shebangs to point to that Python version.

**Comment by Kaali** [comment]
Fixes #71771 and #71178 with `pipenv`

**Comment by FRidh** [comment]
So it's OK now?

**Review by jonringer — APPROVED** [review]
I was able to use it before fine. Still works

**Pull request merged**
