### PR TITLE
linux-rt: Fix incorrect ordering of kernel version numbers when determining latest version

### PR DESCRIPTION
**Pull request by duxovni**
###### Motivation for this change

The `update-rt.sh` script incorrectly downgraded linux-rt_5_10 in #159261, since it assumed that https://mirrors.edge.kernel.org/pub/linux/kernel/projects/rt/5.10/sha256sums.asc would be sorted in version order when it was actually sorted lexicographically. This breaks the build of linux-rt_5_10 in combination with #154994, which requires all 5.10 kernels to be 5.10.90 or later. This PR fixes the script to sort kernel versions correctly, and re-runs the fixed script to update linux-rt_5_10 to the correct latest version.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by TredwellGit — APPROVED** [review]

**Comment by Artturin** [comment]
@TredwellGit feel free to ping me in kernel issues which you approve

**Comment by Artturin** [comment]
I assume there's a existing backport pr for a kernel update, ping me in that and readd the label in this pr once the backport pr is merged

**Comment by TredwellGit** [comment]
@Artturin https://github.com/NixOS/nixpkgs/pull/161592

**Comment by TredwellGit** [comment]
Only https://github.com/NixOS/nixpkgs/pull/161287/commits/a716a45b198d57f456a016acc418bc0e41cd7559 needs to be backported.

**Pull request merged**
