### PR TITLE
php: Upgrade from PHP 8.1 to 8.2 as default PHP

### PR DESCRIPTION
**Pull request by etu**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [X] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by drupol** [comment]
Shouldn't we postpone this a little bit ? PHP 8.1 is still supported until November 2023 (https://www.php.net/supported-versions.php)

**Comment by etu** [comment]
Why not upgrade? It's not like we're dropping 8.1 and people can still use it if they like. Other distros (even debian, https://www.debian.org/News/2023/20230610) is shipping PHP 8.2 by default.

**Comment by etu** [comment]
I created the PR to let the CI run and such, however I would like to sign the commit with GPG before merge... and my GPG key expired earlier today. I'll have time to extend it tomorrow... so hold off merges until then :slightly_smiling_face:

**Comment by drupol** [comment]
> Why not upgrade? It's not like we're dropping 8.1 and people can still use it if they like. Other distros (even debian, https://www.debian.org/News/2023/20230610) is shipping PHP 8.2 by default.

Regarding the question "What is the best moment to switch the default PHP version?" I don't have a strong opinion on this either and I don't know what would be the best approach with this. I guess we definitely should do that before the end of the active support.

**Review by drupol — APPROVED** [review]

**Pull request merged**
