### PR TITLE
vimPlugins.nvim-spectre: fix vendored spectre_oxi hash

### LINKED ISSUE #324458: Build failure: vimPlugins.nvim-spectre
### Steps To Reproduce

```
$ nix build nixpkgs/master#vimPlugins.nvim-spectre

```

### Build log

```
these 3 derivations will be built:
  /nix/store/jpjvdsmyw6dwqaf35v8b07x3rp0gdf42-spectre_oxi-2024-06-25-vendor.tar.gz.drv
  /nix/store/0hzc3dwwj0di70vvdl2sszk49n8s0qg1-spectre_oxi-2024-06-25.drv
  /nix/store/zn2f31s02rml97cziz6z1daj6wfyizyk-vimplugin-nvim-spectre-2024-06-25.drv
building '/nix/store/jpjvdsmyw6dwqaf35v8b07x3rp0gdf42-spectre_oxi-2024-06-25-vendor.tar.gz.drv'...
spectre_oxi> Running phase: unpackPhase
spectre_oxi> unpacking source archive /nix/store/7yxks2v1q2d14mb5d9d41p9w6sg348l6-source
spectre_oxi> source root is source/spectre_oxi
spectre_oxi> Running phase: patchPhase
spectre_oxi> Running phase: updateAutotoolsGnuConfigScriptsPhase
spectre_oxi> Running phase: configurePhase
spectre_oxi> no configure script, doing nothing
spectre_oxi> Running phase: buildPhase
spectre_oxi>     Updating crates.io index
spectre_oxi>  Downloading crates ...
spectre_oxi>   Downloaded bit-set v0.5.3
spectre_oxi>   Downloaded serde_derive v1.0.192
spectre_oxi>   Downloaded oxi-types v0.3.0
spectre_oxi>   Downloaded oxi-macros v0.3.0
spectre_oxi>   Downloaded oxi-luajit v0.3.0
spectre_oxi>   Downloaded bit-vec v0.6.3
spectre_oxi>   Downloaded serde_repr v0.1.17
spectre_oxi>   Downloaded nvim-oxi v0.3.0
spectre_oxi>   Downloaded quote v1.0.33
spectre_oxi>   Downloaded thiserror-impl v1.0.50
spectre_oxi>   Downloaded proc-macro2 v1.0.69
spectre_oxi>   Downloaded unicode-ident v1.0.12
spectre_oxi>   Downloaded oxi-api v0.3.0
spectre_oxi>   Downloaded thiserror v1.0.50
spectre_oxi>   Downloaded serde v1.0.192
spectre_oxi>   Downloaded fancy-regex v0.13.0
spectre_oxi>   Downloaded memchr v2.6.4
spectre_oxi>   Downloaded once_cell v1.18.0
spectre_oxi>   Downloaded lazy_static v1.4.0
spectre_oxi>   Downloaded syn v2.0.39
spectre_oxi>   Downloaded aho-corasick v1.1.2
spectre_oxi>   Downloaded regex-syntax v0.8.2
spectre_oxi>   Downloaded regex-automata v0.4.3
spectre_oxi>   Downloaded libc v0.2.150
spectre_oxi>    Vendoring aho-corasick v1.1.2 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/aho-corasick-1.1.2) to spectre_oxi-2024-06-25-vendor.tar.gz/aho-corasick
spectre_oxi>    Vendoring bit-set v0.5.3 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/bit-set-0.5.3) to spectre_oxi-2024-06-25-vendor.tar.gz/bit-set
spectre_oxi>    Vendoring bit-vec v0.6.3 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/bit-vec-0.6.3) to spectre_oxi-2024-06-25-vendor.tar.gz/bit-vec
spectre_oxi>    Vendoring fancy-regex v0.13.0 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/fancy-regex-0.13.0) to spectre_oxi-2024-06-25-vendor.tar.gz/fancy-regex
spectre_oxi>    Vendoring lazy_static v1.4.0 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/lazy_static-1.4.0) to spectre_oxi-2024-06-25-vendor.tar.gz/lazy_static
spectre_oxi>    Vendoring libc v0.2.150 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.150) to spectre_oxi-2024-06-25-vendor.tar.gz/libc
spectre_oxi>    Vendoring memchr v2.6.4 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/memchr-2.6.4) to spectre_oxi-2024-06-25-vendor.tar.gz/memchr
spectre_oxi>    Vendoring nvim-oxi v0.3.0 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/nvim-oxi-0.3.0) to spectre_oxi-2024-06-25-vendor.tar.gz/nvim-oxi
spectre_oxi>    Vendoring once_cell v1.18.0 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.18.0) to spectre_oxi-2024-06-25-vendor.tar.gz/once_cell
spectre_oxi>    Vendoring oxi-api v0.3.0 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/oxi-api-0.3.0) to spectre_oxi-2024-06-25-vendor.tar.gz/oxi-api
spectre_oxi>    Vendoring oxi-luajit v0.3.0 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/oxi-luajit-0.3.0) to spectre_oxi-2024-06-25-vendor.tar.gz/oxi-luajit
spectre_oxi>    Vendoring oxi-macros v0.3.0 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/oxi-macros-0.3.0) to spectre_oxi-2024-06-25-vendor.tar.gz/oxi-macros
spectre_oxi>    Vendoring oxi-types v0.3.0 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/oxi-types-0.3.0) to spectre_oxi-2024-06-25-vendor.tar.gz/oxi-types
spectre_oxi>    Vendoring proc-macro2 v1.0.69 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.69) to spectre_oxi-2024-06-25-vendor.tar.gz/proc-macro2
spectre_oxi>    Vendoring quote v1.0.33 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/quote-1.0.33) to spectre_oxi-2024-06-25-vendor.tar.gz/quote
spectre_oxi>    Vendoring regex-automata v0.4.3 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/regex-automata-0.4.3) to spectre_oxi-2024-06-25-vendor.tar.gz/regex-automata
spectre_oxi>    Vendoring regex-syntax v0.8.2 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/regex-syntax-0.8.2) to spectre_oxi-2024-06-25-vendor.tar.gz/regex-syntax
spectre_oxi>    Vendoring serde v1.0.192 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.192) to spectre_oxi-2024-06-25-vendor.tar.gz/serde
spectre_oxi>    Vendoring serde_derive v1.0.192 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/serde_derive-1.0.192) to spectre_oxi-2024-06-25-vendor.tar.gz/serde_derive
spectre_oxi>    Vendoring serde_repr v0.1.17 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/serde_repr-0.1.17) to spectre_oxi-2024-06-25-vendor.tar.gz/serde_repr
spectre_oxi>    Vendoring syn v2.0.39 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/syn-2.0.39) to spectre_oxi-2024-06-25-vendor.tar.gz/syn
spectre_oxi>    Vendoring thiserror v1.0.50 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/thiserror-1.0.50) to spectre_oxi-2024-06-25-vendor.tar.gz/thiserror
spectre_oxi>    Vendoring thiserror-impl v1.0.50 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/thiserror-impl-1.0.50) to spectre_oxi-2024-06-25-vendor.tar.gz/thiserror-impl
spectre_oxi>    Vendoring unicode-ident v1.0.12 (/build/source/spectre_oxi/cargo-home.vaA/registry/src/index.crates.io-6f17d22bba15001f/unicode-ident-1.0.12) to spectre_oxi-2024-06-25-vendor.tar.gz/unicode-ident
spectre_oxi> To use vendored sources, add this to your .cargo/config.toml for this project:
spectre_oxi> Running phase: installPhase
spectre_oxi> Running phase: fixupPhase
spectre_oxi> shrinking RPATHs of ELF executables and libraries in /nix/store/6l9554nkssybgxnla6ydarf2fbvy5d23-spectre_oxi-2024-06-25-vendor.tar.gz
spectre_oxi> checking for references to /build/ in /nix/store/6l9554nkssybgxnla6ydarf2fbvy5d23-spectre_oxi-2024-06-25-vendor.tar.gz...
spectre_oxi> patching script interpreter paths in /nix/store/6l9554nkssybgxnla6ydarf2fbvy5d23-spectre_oxi-2024-06-25-vendor.tar.gz
error: hash mismatch in fixed-output derivation '/nix/store/jpjvdsmyw6dwqaf35v8b07x3rp0gdf42-spectre_oxi-2024-06-25-vendor.tar.gz.drv':
         specified: sha256-ZBlxJjkHb2buvXK6VGP6FMnSFk8RUX7IgHjNofnGDAs=
            got:    sha256-SqbU9YwZ5pvdFUr7XBAkkfoqiLHI0JwJRwH7Wj1JDNg=
error: 1 dependencies of derivation '/nix/store/0hzc3dwwj0di70vvdl2sszk49n8s0qg1-spectre_oxi-2024-06-25.drv' failed to build
error: 1 dependencies of derivation '/nix/store/zn2f31s02rml97cziz6z1daj6wfyizyk-vimplugin-nvim-spectre-2024-06-25.drv' failed to build
```

### Notify maintainers

@matthewcoudron
@oxalica

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.11 (Vicuna), 24.11.20240702.0aeab74`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.23.1`
 - channels(mightyiam): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/ad7m39h49x2c4i9lzqhx4iy8kka8wchd-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by khaneliman**
## Description of changes
Resolves https://github.com/NixOS/nixpkgs/issues/324458

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by NotAShelf — APPROVED** [review]

**Comment by aymanbagabas** [comment]
1 package built:
vimPlugins.nvim-spectre

Result of `nixpkgs-review pr 324952` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vimPlugins.nvim-spectre</li>
  </ul>
</details>

**Review by aymanbagabas — APPROVED** [review]

**Comment by aymanbagabas** [comment]
Result of `nixpkgs-review pr 324952` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vimPlugins.nvim-spectre</li>
  </ul>
</details>

**Review by aymanbagabas — APPROVED** [review]

**Comment by NotAShelf** [comment]
Result of `nixpkgs-review pr 324952` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vimPlugins.nvim-spectre</li>
  </ul>
</details>

**Comment by khaneliman** [comment]
> Result of `nixpkgs-review pr 324952` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 
> 1 package failed to build:

Is it showing different hashes on different platforms? I’m not home to test on Linux.

**Comment by NotAShelf** [comment]
Result of `nixpkgs-review pr 324952` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vimPlugins.nvim-spectre</li>
  </ul>
</details>

**Comment by NotAShelf** [comment]
I just had to rebase around master, lgtm now.

**Review by NotAShelf — APPROVED** [review]

**Comment by khaneliman** [comment]
@GrahamcOfBorg build vimPlugins.nvim-spectre

**Comment by mightyiam** [comment]
Thank you!

**Pull request merged**
