### PR TITLE
obsidian: electron_18 -> electron_21

### PR DESCRIPTION
**Pull request by 1sixth**
###### Description of changes

- Electron 18 has reached EOL: <https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline>
- The upstream builds have been using Electron 21 since v1.1.9: <https://forum.obsidian.md/t/obsidian-release-v1-1-9/50426>

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by qbit** [comment]
Result of `nixpkgs-review pr 213593` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>obsidian</li>
  </ul>
</details>

**Review by qbit — APPROVED** [review]

**Review by LunNova — APPROVED** [review]
Fixes ```error: Package ‘electron-18.1.0’ in /nix/store/c913y6lyhkaw6z5cr61rp7kj9s43h473-nixpkgs-patched/pkgs/development/tools/electron/generic.nix:27 is marked as insecure, refusing to evaluate.```

**Comment by IzumiRaine** [comment]
Any chance this could be backported to 22.11? Evaluation there currently fails with the same error that @LunNova mentioned.

**Comment by ius** [comment]
This seems to be a recurring theme. I've opened 2 PRs to improve the status quo: https://github.com/NixOS/nixpkgs/pull/214366 (master) https://github.com/NixOS/nixpkgs/pull/214368 (22.11)

**Pull request merged**
