### PR TITLE
python3Packages.tensorflow-bin: 2.7.0 -> 2.8.0

### LINKED ISSUE #169129: `python39Packages.tensorflow-bin` build failure on x86_64-linux as of `891d0226`
## Issue description
Build of `python39Packages.tensorflow` failed on x86_64-linux as of 891d0226de6e281422a8d0d99814925fd7aed8d0. This is currently breaking python3Packages.tensorflow-bin.

```
error: builder for '/nix/store/ra0brrxhlk461ig6imw2b0il7lyjbxli-python3.9-tensorflow-2.7.0.drv' failed with exit code 1;
       last 10 log lines:
       > Requirement already satisfied: protobuf>=3.9.2 in /nix/store/azllrykpck52hhismhn7vdfjqv8slh83-python3.9-protobuf-3.19.3/lib/python3.9/site-packages (from tensorflow-cpu==2.7.0) (3.19.3)
       > Requirement already satisfied: numpy>=1.14.5 in /nix/store/lwk6w9022x0rn7v9jf4lraxyykb3yqzf-python3.9-numpy-1.21.5/lib/python3.9/site-packages (from tensorflow-cpu==2.7.0) (1.21.5)
       > Requirement already satisfied: google-pasta>=0.1.1 in /nix/store/f5r90mvr7fhzbzf9b1qcxjx3v407dpin-python3.9-google-pasta-0.2.0/lib/python3.9/site-packages (from tensorflow-cpu==2.7.0) (0.2.0)
       > Requirement already satisfied: tensorboard~=2.6 in /nix/store/h4qszvv52j0hq2pmiy5gadqpaqnyzah5-python3.9-tensorboard-2.8.0/lib/python3.9/site-packages (from tensorflow-cpu==2.7.0) (2.8.0)
       > Requirement already satisfied: wrapt>=1.11.0 in /nix/store/yxgwr65bfpzb9py2q0rf7a1ididm9nph-python3.9-wrapt-1.13.3/lib/python3.9/site-packages (from tensorflow-cpu==2.7.0) (1.13.3)
       > Requirement already satisfied: absl-py>=0.4.0 in /nix/store/kkwdp67afj2qk2h380zq4giiwi7y8wwl-python3.9-absl-py-1.0.0/lib/python3.9/site-packages (from tensorflow-cpu==2.7.0) (1.0.0)
       > Requirement already satisfied: h5py>=2.9.0 in /nix/store/xshnrg2zmvc3chs9bm84s68zmmdrccj4-python3.9-h5py-3.6.0/lib/python3.9/site-packages (from tensorflow-cpu==2.7.0) (3.6.0)
       > ERROR: Could not find a version that satisfies the requirement tensorflow-estimator<2.8,~=2.7.0rc0 (from tensorflow-cpu) (from versions: none)
       > ERROR: No matching distribution found for tensorflow-estimator<2.8,~=2.7.0rc0
       > 
       For full logs, run 'nix log /nix/store/ra0brrxhlk461ig6imw2b0il7lyjbxli-python3.9-tensorflow-2.7.0.drv'.
```

[full build log](https://github.com/samuela/nixpkgs-upkeep/actions/runs/2181534947)

python3Packages.tensorflow-bin maintainers cc: @jyp @abbradar @cdepillabout
python39Packages.tensorflow maintainers cc: @jyp @abbradar
Other cc: n/a

### Steps to reproduce
1. Checkout nixpkgs at commit 891d0226de6e281422a8d0d99814925fd7aed8d0
2. Run `nix-build -A python39Packages.tensorflow`

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.0-1021-azure, Ubuntu, 20.04.4 LTS (Focal Fossa), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - nixpkgs: `/nix/store/r902mrj2iwsjhy8gs6y0rbr9nada0z4z-source`
```

## Misc.
This issue was automatically generated by [nixpkgs-upkeep](https://github.com/samuela/nixpkgs-upkeep).
- [CI workflow](https://github.com/samuela/nixpkgs-upkeep/actions/runs/2181534947) that created this issue.
- Internal tag: 7571569481954458355

### PR DESCRIPTION
**Pull request by samuela**
###### Description of changes

Fix https://github.com/NixOS/nixpkgs/issues/169129. Note that the x86_64-linux CPU-only build is currently disabled because upstream has not built/published a wheel for it yet. See https://github.com/tensorflow/tensorflow/issues/55581 for more info.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by samuela** [comment]
Result of `nixpkgs-review pr 169249` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by samuela** [comment]
would someone from @NixOS/darwin-maintainers be able to try a quick `nixpkgs-review pr --post-result 169249` on an x86_64-darwin machine?

**Comment by uri-canva** [comment]
Result of `nixpkgs-review pr 169249` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>python39Packages.tensorflow-bin</li>
  </ul>
</details>

**Comment by samuela** [comment]
Thanks @uri-canva!

Ok, if no one objects I'll go ahead and merge tomorrow

**Pull request merged**
