### PR TITLE
Add option to display git revision to nixos-version

### PR DESCRIPTION
**Pull request by eduarrrd**
Example use case: git checkout `nixos-version --hash`

Problem: How do I test this safely?

### CODE REVIEW

**Comment by iElectric** [comment]
`nixos-rebuild switch -I /path/to/folder/with/nixpkgs`

**Comment by eduarrrd** [comment]
@iElectric that doesn't actually work. The change isn't picked up. I have a feeling that this should not be happening. Even if there is no hash to `nixos-version.sh`, the arguments to `makeProg` are modified ...

**Comment by bjornfor** [comment]
Try "nixos-rebuild switch -I nixpkgs=/path/to/nixpkgs"

**Comment by eduarrrd** [comment]
@bjornfor OK, that worked! Thanks!

My change looks good IMO. If nobody objects I would be great if it could be merged.

**Comment by peti** [comment]
What bothers me about this PR is that the new options seem to be entirely undocumented. Am I missing something?

**Comment by eduarrrd** [comment]
No, that's fair criticism. You're right. That got lost between trying to
test it and (a month later) testing it seeing it work. I will patch it in
to this PR today or tomorrow. Thanks for picking up on this!

**Comment by edolstra** [comment]
Looks like `nixos-version` is entirely undocumented at the moment...

**Comment by peti** [comment]
Good point ...

**Comment by iElectric** [comment]
So lets open an issue to fix that?

**Pull request merged**
