### PR TITLE
tauri-mobile: init at unstable-2023-04-25

### PR DESCRIPTION
**Pull request by happysalada**
###### Description of changes

I'm using unstable here since the cargo lock was fixed after the release was made.
The install process populates the home directory, I've open an issue asking them to be able to define the directory with an env var. Not sure before then how we can really get access to that. I've put that directory in share in the meanwhile it contains the commit info and some templates.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
I'm going to merge this for now, but would be very happy to collect feedback later.

**Comment by bburdette** [comment]
Is this the place for feedback on this?  I had problems with `cargo mobile init`.

I worked around the missing ~/.tauri-mobile by copying the folder out of the store into my home, then chmodding it until it stopped giving me errors (mainly readonly README.md).

Next issue, missing CodeLLDB extension:

```
[bburdette@HOSS:~/code/zknotes/zknotes/meh2]$ cargo mobile init
Project name (meh2):
Stylized name (Meh2):
Domain (example.com):
Detected template packs:
  [0] bevy
  [1] bevy-demo
  [2] wgpu
  [3] winit
  [4] wry
  Enter an index for a template pack above.
Template pack (0):
Generating base project...
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /home/bburdette/code/zknotes/zknotes/meh2/.git/
error: Failed to install CodeLLDB extension
    No such file or directory (os error 2)
```

I thought adding lldb to my flake deps might help, but it didn't fix it.   

Despite this error, the template project apparently installed itself enough to compile successfully, although the `.first-init` file indicates that the init process never officially finished.  

I also needed to add alsa-lib to my devShell in order for compile to work.

**Comment by happysalada** [comment]
@bburdette thanks for coming by!
the templates thing should be fixed in the next version. I opened an issue upstream and they changed the reference to those.
I've got a PR in draft with the fix https://github.com/NixOS/nixpkgs/pull/231887
The problem is that with their latest release, their lockfile is not up to date. I could make another unstable upgrade, but I was waiting for them to release the next stable.
Could the codelldb thing be this ? https://github.com/vadimcn/codelldb
I'm happy to add any dependencies to the buildInputs that you think are needed.

**Comment by bburdette** [comment]
I honestly don't know if that's the right codelldb.  Seems likely?  Maybe its just a nice-to-have and not an essential component.

**Comment by happysalada** [comment]
Its packaged in nixpkgs under vscode-lldb (under vscode extensions) if you ever want to test it out. Ill tag you when i make the next update of tauri mobile and you can verify it works for you.

**Comment by bburdette** [comment]
I added that to my flake.nix but still got the same error on `cargo mobile init`.  For me its probably no big deal as I'm going with the [Integrate into Existing Project](https://next--tauri.netlify.app/next/mobile/development/integrate) route rather than using one of the  templates, and I don't use vscode.

**Comment by bburdette** [comment]
I was able to build an apk, finally!  But I ended up copying this and the tauri nix file out of nixpkgs into my own project and editing the versions to the newest.  Turns out the directions I was following for build didn't match the tauri-mobile I got from here. That project is moving pretty fast.

**Comment by happysalada** [comment]
Thank you for the update, the latest release again had a wrong lock file, so i didnt update.

**Comment by happysalada** [comment]
I've made the update to latest in this PR in case you want to test https://github.com/NixOS/nixpkgs/pull/231887

**Pull request merged**
