### PR TITLE
ripgrep-all: 0.9.6 -> 1.0.0-alpha.5

### LINKED ISSUE #250306: Build failure: ripgrep-all
### Steps To Reproduce

1. build `ripgrep-all`

### Build log

```
error: builder for '/nix/store/md5x85n2jdc3rxxi8i8nbb63g3qvp866-ripgrep-all-0.9.6.drv' failed with exit code 1;
       last 10 log lines:
       > adapter: poppler
       > adapter: poppler
       > adapter: zip
       > adapter: poppler
       > adapter: pandoc
       > Unknown option --atx-headers.
       > Try pandoc --help for more information.
       > Error: Broken pipe (os error 32)
       > -------------------------------------------------------------------------------
       > ERROR: test1 failed! Could not find the word 'hello' 26 times in the sample data.
       For full logs, run 'nix log /nix/store/md5x85n2jdc3rxxi8i8nbb63g3qvp866-ripgrep-all-0.9.6.drv'.

```

### Additional context

https://discourse.nixos.org/t/ripgrep-all-build-error-on-latest-unstable/31907

> It looks like ripgrep-all is trying to use a the pandoc flag --atx-headers, which no longer exists.
Upstream issue: [Failure on searching epub with pandoc deprecation warning · Issue #115 · phiresky/ripgrep-all · GitHub](https://github.com/phiresky/ripgrep-all/issues/115)
> 
> It looks like it was already fixed: [fixes to postprocessing · phiresky/ripgrep-all@020000c · GitHub](https://github.com/phiresky/ripgrep-all/commit/020000cc77d0d63c5a7b2871e6f22550b4dbc1a0#diff-2ed052dd4f13ac4841c1e3377b4c100faa9330c26d7ccbc30f971f3f87d9e30cR92).
> 
> Updating ripgrep-all to the latest version should fix this, the release in nixpkgs is from 2020-05-19.

### Notify maintainers

@Ma27 @zaninime 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.10-200.fc38.x86_64, Fedora Linux, 38.20230817.0 (Kinoite), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/home/fenglengshun/.nix-defexpr/channels/nixpkgs`
```

### PR DESCRIPTION
**Pull request by pinpox**
Fixes #250306

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Benjamin-L** [comment]
Result of `nixpkgs-review pr 264362` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ripgrep-all</li>
  </ul>
</details>

Tested the resulted binary against the files in `nixpkgs-review/exampledir/demo`, and it seems to work. Confirmed that the tests that were removed from `installCheckPhase` are part of the `cargo test` tests that run during the build now.

**Review by olivia-fl — APPROVED** [review]

**Review by magnetophon — APPROVED** [review]
Result of `nixpkgs-review pr 264362` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ripgrep-all</li>
  </ul>
</details>

``rga`` and ``rga-fzf`` work as expected, but there are also two binaries in  ``/bin`` dir that I didn't recognize and seem to be "internal" tools:
``rga-fzf-open`` and ``rga-preproc``.
Not sure if they should be in ``/bin``.

**Comment by phiresky** [comment]
Yes, they are used internally. Afaik rga expects them to be in the same location the rga binary is

**Review by zaninime — APPROVED** [review]
Result of `nixpkgs-review pr 264362` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ripgrep-all</li>
  </ul>
</details>

**Comment by Ma27** [comment]
I can take a look later today and merge if everything seems OK :)

**Review by Ma27 — APPROVED** [review]
Tested for a while, also with larger directories and it seems fine so far. The only issue I encountered was that poppler complained about a locked database which could be solved by deleting my old cache (https://github.com/phiresky/ripgrep-all/issues/188), but given that clearing the cache as workaround is sufficient (and there seem to be quite a lot of changes), I'm fine with that.

The author claims that it's working fine for them and should generally be releasable, but they'd like to see if more problems come up. To me the current state seems good enough and the implementation in this PR is IMHO highly preferable over applying all the patches between 0.9.6 and now that fix known issues with adapters without the more complex changes that were the reason for a new major (which is the only other option left short of marking this as broken).

**Pull request merged**
