### PR TITLE
Upgrade ansible and ansible-core

### PR DESCRIPTION
**Pull request by mkg20001**
- **ansible-core: 2.16.5 -> 2.17.1**
- **ansible: 9.6.0 -> 10.1.0**

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by natsukium — COMMENTED** [review]
Could you add ansible_2_17 to all-packages.nix?
You can refer to the [PR I previously updated to 2.16](https://github.com/NixOS/nixpkgs/pull/277719).

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 324076` at e315597f run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/natsukium/cc71925aa3494ff3805ade6a69d03bde">ansible-later</a></li>
    <li>ansible-navigator (python312Packages.ansible-navigator)</li>
    <li>python311Packages.ansible-kernel</li>
    <li><a href="https://gist.github.com/natsukium/c31b08d72dcac09fd87f2597749ad6a1">python311Packages.ansible-runner</a></li>
    <li><a href="https://gist.github.com/natsukium/0823912fcfb64b64a6f71d71c26940ac">python311Packages.pytest-ansible</a></li>
    <li>python312Packages.ansible-kernel</li>
    <li><a href="https://gist.github.com/natsukium/d775034b041937dba9195ce4940b892d">python312Packages.ansible-runner</a></li>
    <li><a href="https://gist.github.com/natsukium/d4110b2069b6cc6862ae8ada52375245">python312Packages.pytest-ansible</a></li>
  </ul>
</details>
<details>
  <summary>12 packages built successfully:</summary>
  <ul>
    <li>ansible (ansible_2_17 ,python312Packages.ansible-core)</li>
    <li>ansible-lint</li>
    <li>ansible_2_16</li>
    <li>molecule (python312Packages.molecule)</li>
    <li>python311Packages.ansible-compat</li>
    <li>python311Packages.ansible-core</li>
    <li>python311Packages.ansible-vault-rw</li>
    <li>python311Packages.molecule</li>
    <li>python311Packages.pytest-testinfra</li>
    <li>python312Packages.ansible-compat</li>
    <li>python312Packages.ansible-vault-rw</li>
    <li>python312Packages.pytest-testinfra</li>
  </ul>
</details>

**Comment by mkg20001** [comment]
Most of the failures are from this PR, looks like the packages need to be updated

**Comment by mkg20001** [comment]
Rebased, upgraded. Failures actually not from this PR. Tested latest unstable. Merging after CI.

ansible-later: already broken
ansible-navigator: test failure, already broken before
kargo: already broken
ansible-runner: test failure, already broken before
ansible-kernel: depends on ansible-runner, broken

**Pull request merged**
