### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by zimbatm**
Use the new issue template format and add a "packaging request" template.

The best thing is that labels are pre-applied so they are then easily queryable.

### CODE REVIEW

**Comment by FRidh** [comment]
I like to have a couple templates. Important is, though, that there is a general one in case others don't apply, and that it is obvious which one that is and that it is OK to take that one when not sure. I think the general issue should be the default one.

Suggested templates:
- General issue
- Bug
- Security (of course with the mention of https://nixos.org/nixos/security.html)
- Question
- Packaging request

**Comment by zimbatm** [comment]
In that case I need to make some more tests. The UI only has 3 entries with pre-defined names: https://github.com/NixOS/nixpkgs/issues/templates/edit
Maybe the filenames matter, maybe not so I need to test this.

**Comment by FRidh** [comment]
Note the motivation for these is because its not something ofborg can handle (unless we add some more advanced NLP to it).

**Comment by zimbatm** [comment]
:boom: this is a nice opportunity to add an "attrset" selector to the issue template. This would allow ofborg to map an issue to a maintainer for us.

**Comment by zimbatm** [comment]
After doing a bit of experimentation on my own repo, there is a limit of 3 templates available. + a generic one in small.

image

**Comment by gloaming** [comment]
Cool! How about "regular" -> "miscellaneous"

Also, upgrade requests seem to be reasonably common. Should they be a separate template, or go under "package requests"?

**Comment by zimbatm** [comment]
We can only have 3 templates so we have to choose carefully. The "open a regular issue" text is not something we control.

**Comment by zimbatm** [comment]
The "Open a regular issues." link uses the old `.github/ISSUE_TEMPLATE.md` file as a template.

**Comment by zimbatm** [comment]
I'm going to make another pass at the templates to add a front-matter for the structured data

**Comment by zimbatm** [comment]
Okay this is ready for review.

You can play with the new issue templates over here to see how it will look like: https://github.com/zimbatm/nixpkgs/issues/new/choose

**Comment by zimbatm** [comment]
TODO from @ghuntley: add a untriaged label

**Comment by FRidh** [comment]
Not applicable for these files, but for the other .github/ ones it may be worth it to put them all in one repo:
https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization

**Comment by zimbatm** [comment]
@ghuntley showed us a repo with more than 3 templates during the office hours. So maybe we can add many more.

**Comment by grahamc** [comment]
I would be interested in an issue template (and label) for https://github.com/grahamc/r13y.com/issues/3

The idea being I could have a link to a search page, like "autogen-5.18.12. is unreproducible label:reproducibility"

**Comment by zimbatm** [comment]
I'll merge this for now to expose the changes to a wider public so we can iterate on the templates.

**Pull request merged**
