### PR TITLE
Keybase 2.13.1

### PR DESCRIPTION
**Pull request by emmanuelrosa**
###### Motivation for this change

This change updates the keybase clients to version 2.13.1

This update introduces a Stellar (XLM) wallet built-in to the GUI client.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
~- [] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))~
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
  - /nix/store/crmrla0ldzwq9xxi7sk95mpyq20n3xc2-keybase-gui-2.13.0    514194056
  - /nix/store/agy45qxjhd1599rvw04j0lf068y9cbqw-keybase-gui-2.13.1    602877480
  - /nix/store/7f052pbid2v2sr0wkpi1x8fpjxyiavmk-keybase-2.11.0-bin     83144176
  - /nix/store/95kli1cw668417w6ff4mck35jgr6dx23-keybase-2.13.1-bin     84715536

~- [ ] Assured whether relevant documentation is up to date~
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
cc @rvolosatovs @kalbasit

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build keybase keybase-gui

**Comment by hedning** [comment]
The darwin build complains about [wrong hash](https://github.com/NixOS/nixpkgs/pull/54277/checks?check_run_id=52310394).

**Comment by emmanuelrosa** [comment]
Hmm... there is the hash for the Darwin build supposed to go? I only see one hash in the package.

**Comment by kalbasit** [comment]
It's interesting that the build hash failed on Mac for the same archive. Let's try again.

@GrahamcOfBorg build keybase keybase-gui

**Comment by kalbasit** [comment]
@GrahamcOfBorg build keybase keybase-gui

**Review by kalbasit — APPROVED** [review]

**Pull request merged**
