### PR TITLE
[WIP] python3Packages.pulumi-* init

### PR DESCRIPTION
**Pull request by costrouc**
###### Motivation for this change

Initializing basic pulumi python resources for devops.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by costrouc** [comment]
Result of `nixpkgs-review pr 84258` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>46 package marked as broken and skipped:</summary>

  - digitalbitbox
  - iterm2
  - linuxPackages_4_4.evdi
  - linuxPackages_hardkernel_4_14.bcc
  - linuxPackages_hardkernel_4_14.bpftrace
  - linuxPackages_hardkernel_4_14.can-isotp
  - linuxPackages_hardkernel_4_14.chipsec
  - linuxPackages_hardkernel_4_14.digimend
  - linuxPackages_hardkernel_4_14.evdi
  - linuxPackages_hardkernel_4_14.mba6x_bl
  - linuxPackages_hardkernel_4_14.nvidia_x11
  - linuxPackages_hardkernel_4_14.nvidia_x11_legacy390
  - linuxPackages_hardkernel_4_14.nvidiabl
  - linuxPackages_hardkernel_4_14.prl-tools
  - linuxPackages_hardkernel_4_14.rtl8814au
  - linuxPackages_hardkernel_4_14.rtl8821au
  - linuxPackages_hardkernel_4_14.rtl8821ce
  - linuxPackages_hardkernel_4_14.rtlwifi_new
  - linuxPackages_hardkernel_4_14.v4l2loopback
  - newlibCross
  - nix-linter
  - octave-jit
  - php72Packages-unit.php_excel
  - php72Packages-unit.v8
  - php72Packages-unit.v8js
  - php72Packages.php_excel
  - php72Packages.v8
  - php72Packages.v8js
  - php73Packages-unit.php_excel
  - php73Packages-unit.v8
  - php73Packages.php_excel
  - php73Packages.v8
  - php74Packages-unit.couchbase
  - php74Packages-unit.pcs
  - php74Packages-unit.php_excel
  - php74Packages-unit.v8
  - php74Packages.couchbase
  - php74Packages.php_excel
  - php74Packages.v8
  - python27Packages.caffe
  - python27Packages.flitBuildHook
  - python37Packages.notify
  - python37Packages.pyblock
  - python38Packages.nixpart
  - python38Packages.notify
  - python38Packages.pyblock
</details>
<details>
  <summary>14 package built:</summary>

  - python37Packages.pulumi
  - python37Packages.pulumi-aws
  - python37Packages.pulumi-azure
  - python37Packages.pulumi-digitalocean
  - python37Packages.pulumi-gcp
  - python37Packages.pulumi-kubernetes
  - python37Packages.pulumi-random
  - python38Packages.pulumi
  - python38Packages.pulumi-aws
  - python38Packages.pulumi-azure
  - python38Packages.pulumi-digitalocean
  - python38Packages.pulumi-gcp
  - python38Packages.pulumi-kubernetes
  - python38Packages.pulumi-random
</details>

**Comment by costrouc** [comment]
Not sure why checks are failing?

**Review by cole-h — CHANGES_REQUESTED** [review]
It looks to me like checks are failing because none of the packages have `meta.platforms` set and are then trying to evaluate on `aarch64`, which pulumi doesn't appear to support. See: https://github.com/NixOS/nixpkgs/blob/c4f5f95d8d2d2d5864c7d11548d6ac659ca9fbda/pkgs/tools/admin/pulumi/default.nix#L29

**Comment by mudrii** [comment]
@costrouc is any update on this package?
I would be happy to co-maintain the packages

**Comment by teto** [comment]
@costrouc @mudrii any chance either of you resume this ? I am interested in this as well. I can either review or eventually complete if that's not too much work.

**Comment by teto** [comment]
sry I pushed to your branch that was not my intention. I opened an update for the packages I am interested in at https://github.com/NixOS/nixpkgs/pull/163062

**Pull request closed without merging**
