### PR TITLE
vimPlugins.arrow-nvim: init at 2024-04-19

### PR DESCRIPTION
**Pull request by hmajid2301**
## Description of changes

Add new vim plugin [arrow-nvim](https://github.com/otavioschwanck/arrow.nvim)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Aleksanaa** [comment]
Seems wrong commits are pushed to this branch?

**Comment by hmajid2301** [comment]
I updated the pkgs/applications/editors/vim/plugins/vim-plugin-names then ran nix-shell -p vimPluginsUpdater --run vim-plugins-updater and these are the commits that were generated. Did I do something wrong ?


Thanks

**Comment by Aleksanaa** [comment]
Yes. They are out of scope for this PR.

**Comment by vinnymeller** [comment]
@Aleksanaa for some reason this seems fairly common(?) with `vimPlugins` additions. A couple recent examples:

https://github.com/NixOS/nixpkgs/pull/301342
https://github.com/NixOS/nixpkgs/pull/291299

**Comment by Aleksanaa** [comment]
> @Aleksanaa for some reason this seems fairly common(?) with `vimPlugins` additions.

Okay, let someone else handle it.

**Comment by hmajid2301** [comment]
So, just to clarify, what should this PR contain, just the new package? No updates to other packages? Or packages without any grammar updates?

Thanks

**Comment by vinnymeller** [comment]
@hmajid2301 sorry missed this one. it'll probably be easier to get your PR merged if the changes only include the new plugin

id remove the 2nd and 3rd commit, rebase your 1st commit to current master, and then copy _only_ the part of `generated.nix` that adds your new plugin

not sure if there's a better way that I'm missing, but that's essentially what I do. main difference is I follow the instructions here:

my current flow for adding a new plugin is basically following the instructions here: https://github.com/NixOS/nixpkgs/blob/f679db404cbf52dc264f018e1e21c2b73633aa59/doc/languages-frameworks/vim.section.md?plain=1#L250-L264

to only created the `generated.nix` for my single plugin, and copy/paste my added content into `vim-plugin-names` and `generated.nix` in the right spots

**Comment by hmajid2301** [comment]
Thanks @vinnymeller, no worries buddy it happens init we are all busy. Let me do tha then!

**Comment by hmajid2301** [comment]
should be done now hopefully!

**Comment by vinnymeller** [comment]
> should be done now hopefully!

:+1:, only other I'd add is linking back to the plugin in the description. not sure how much people check, but its useful to quickly verify that e.g. there are no other dependencies the plugin needs that this pr might be missing

**Review by vinnymeller — APPROVED** [review]

**Comment by hmajid2301** [comment]
done!

**Pull request merged**
