### PR TITLE
rdedup: 3.0.1 -> 3.1.1

### PR DESCRIPTION
**Pull request by steveej**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dywedir** [comment]
@GrahamcOfBorg build rdedup

**Comment by Mic92** [comment]
@GrahamcOfBorg build rdedup

**Comment by steveeJ** [comment]
Thanks for jumping in @dywedir. The last build error is beyond the build system and needs fixing upstream. That is, if the author has an interest of making this work on Darwin.

**Comment by Mic92** [comment]
We should mark it at least as broken in this case.

**Comment by steveeJ** [comment]
@Mic92 

> We should mark it at least as broken for macOS in this case.

Done.

**Review by dywedir — APPROVED** [review]

**Comment by dywedir** [comment]
Thanks!

**Pull request merged**
