### PR TITLE
Vulkan 1.3.275

### PR DESCRIPTION
**Pull request by K900**
## Description of changes

New SDK release.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by K900** [comment]
Overall pretty painless update this time. `vulkan-volk` because `volk` is taken.

**Review by Ralith — APPROVED** [review]

**Comment by trofi** [comment]
Bisect says that b52d8522e53dd887e438f4d11bab610b0fbbc597 `spirv-headers: 1.3.268.0 -> 1.3.275.0` broke `spirv-llvm-translator` in `staging` and `staging-next` as: 

```
$ nix build --no-link -f. spirv-llvm-translator -L
...
SPIRV-LLVM-Translator> [ 48%] Building CXX object lib/SPIRV/CMakeFiles/LLVMSPIRVLib.dir/SPIRVToLLVMDbgTran.cpp.o
SPIRV-LLVM-Translator> In file included from /build/source/lib/SPIRV/SPIRVInternal.h:45,
SPIRV-LLVM-Translator>                  from /build/source/lib/SPIRV/VectorComputeUtil.h:43,
SPIRV-LLVM-Translator>                  from /build/source/lib/SPIRV/VectorComputeUtil.cpp:39:
SPIRV-LLVM-Translator> /build/source/lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h: In member function 'void SPIRV::SPIRVMap<Ty1, Ty2, Identifier>::init() [with Ty1 = spv::Capability; Ty2 = std::__cxx11::basic_string<char>; Identifier = void]':
SPIRV-LLVM-Translator> /build/source/lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h:607:7: error: 'CapabilityLongConstantCompositeINTEL' was not declared in this scope
SPIRV-LLVM-Translator>   607 |   add(CapabilityLongConstantCompositeINTEL, "LongConstantCompositeINTEL");
SPIRV-LLVM-Translator>       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Ralith** [comment]
Looks like that was renamed to `LongCompositesINTEL` in https://github.com/KhronosGroup/SPIRV-Headers/commit/d5acd42cb7cdaa5d0f2c5f739208eeeed395f491.

**Comment by K900** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/282006

**Comment by zeuner** [comment]
Not sure why this was merged as-is since it breaks subsequent CI due to disregarding the `pkgs/by-name` policy: https://github.com/NixOS/nixpkgs/actions/runs/7600068348/job/20697863923?pr=282473

**Comment by K900** [comment]
This was merged into staging before the pkgs/by-name enforcement, which was merged into master.

**Comment by vcunat** [comment]
BTW, 1.3.277 adds `VK_KHR_video_decode_av1`.  Sounds interesting, over longer term at least.

**Pull request merged**
