### PR TITLE
Updated pulumi all plugins

### LINKED ISSUE #111679: Pulumi AWS plugin out of date
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: pulumi-bin

current version: 2.19.0 (aws plugin 3.25.1)
desired version: 2.19.0 (aws plugin 3.26.1)

###### Notify maintainers

maintainers: @cpcloud @ghuntley @peterromfeldhk @jlesquembre

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by chrisportela**
###### Motivation for this change
Warnings when using the latest pulumi packages and fixes #111679 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 111680` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>pulumi-bin</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
Can you please update the commit message to fit the contributing guide?

**Comment by chrisportela** [comment]
@SuperSandro2000 Updated commit message, is this good? Wasn't sure what to put since I wasn't updating pulumi itself and I updated like 10 plugins.

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 Updated commit message, is this good? Wasn't sure what to put since I wasn't updating pulumi itself and I updated like 10 plugins.

It would be better if each update would be its own commit but not that important tbh. The important part is that it starts with pulumi:.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 111680` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>pulumi-bin</li>
</ul>
</details>

**Pull request closed without merging**
