### PR TITLE
flightgear: 2020.1.3 -> 2020.3.4

### PR DESCRIPTION
**Pull request by wucke13**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Might tick of the requirements for https://github.com/NixOS/nixpkgs/pull/77799

### CODE REVIEW

**Comment by samb96** [comment]
@GrahamcOfBorg eval

**Comment by veprbl** [comment]
@GrahamcOfBorg build flightgear

**Comment by aanderse** [comment]
It won't build. Blacklisted because of size. Have to build locally to confirm.

**Review by veprbl — APPROVED** [review]
LGTM

**Pull request merged**
