### PR TITLE
krohnkite: 0.8.2 -> 0.9.7

### LINKED ISSUE #324406: Update request: krohnkite 0.8.1 → 0.9.7
- Package name: krohnkite
- Latest released version: 0.9.7
- Current version on the unstable channel: 0.8.2
- Current version on the stable/release channel: 0.8.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@seqizz 

**Notes**

The project was recently [forked](https://github.com/anametologin/krohnkite/) (from the [original](https://github.com/esjeon/krohnkite)) and ported to Plasma 6. It would be better I think to package the fork.

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by seqizz**
## Description of changes

Routine update with source change, looks like it is forked

Fixes #324406

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by K900** [comment]
That's really not routine. Are we sure this fork is good?

**Comment by seqizz** [comment]
Can't really vouch for it tbh, not using plasma for a long time now.

Original repo actually seems stale, and people on issues mentioned the new one, which has [visible differences](https://github.com/esjeon/krohnkite/compare/master...anametologin:krohnkite:master) over the original. Looked good enough.

**Comment by JohnAZoidberg** [comment]
Have other distributions switched over to this fork?

**Comment by aanderse** [comment]
yes this has become the version of the script that became dominant on the kde get new stuff store and it is reasonable to switch to it

what about plasma 6? i am not up to date with packaging addons since the change from 5 to 6 but given the `libsForQt5` bit i will assume this also needs packaging for plasma 6? the addon itself is compatible with both 5 and 6, btw

**Comment by seqizz** [comment]
Makes sense, but I couldn't see plasma-6 in the tree, nor libsforqt6. If there is such distinction please send me an example so I can try to adjust.

**Comment by aanderse** [comment]
i haven't done any packaging for plasma 6 so i am out of the loop...

i did notice [this](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/data/themes/kwin-decorations/kde-rounded-corners/default.nix#L29) package which works for plasma 6... so maybe nothing special needed? 

sorry, i wish i knew more but haven't looked into it yet

**Comment by jiriks74** [comment]
Hello,
I didn't learn nix properly yet, so I can't help with technicalities about packaging, etc. But I'm using Plasma 6 so I can be your test dummy. So far I see that packages changed from `libsForQt5` to `kdePackages` for Plasma 6.

Also from what I saw on the internet it's the best tiling kwin script available as of now. I've personally used Polonium but it has issues which can be quite annoying at times. Krohnkite could be the one that gets me to use tiling 24/7 again.

I'll be testing it soon enough (if it works from the store) and I'll see how it goes. I'll update you once I get everything setup.

**Review by aanderse — APPROVED** [review]
oh... i forgot about this PR, sorry

anyone opposed to merge? i intend to merge this in the next few days

thanks all

**Comment by jiriks74** [comment]
I see that the package is still under plasma-5. Shouldn't it be moved, or copied, to plasma-6?

**Comment by jiriks74** [comment]
I've just pulled Krohnkite from Nixpkgs instead of building it myself. It's at `0.9.7`, upstream is at `0.9.8.2` as of 4 days ago, and everything seems to work just fine.

**Comment by Iorvethe** [comment]
I think we can close this MR, as another package for `krohnkite` was created for Plasma 6 (#340606) and the version here is not backwards compatible. This would allow the Plasma 5 version (0.8.2) to still be installable along the Plasma 6 one (0.9.8.3). I will close the linked issue as completed

**Comment by seqizz** [comment]
Nice to hear, closing

**Pull request closed without merging**
