### PR TITLE
gitlab: 12.1.6 -> 12.3.0

### PR DESCRIPTION
**Pull request by bgamari**
###### Motivation for this change

This is an updated version of #68777 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by bgamari** [comment]
@test gitlab

**Comment by worldofpeace** [comment]
@GrahamcOfBorg test gitlab

**Comment by bgamari** [comment]
This appears to be broken due to https://gitlab.com/gitlab-org/gitlab-shell/issues/211.

**Comment by bgamari** [comment]
@flokli I honestly have no idea. The GitLab folks seem to think that there is no bug but my very limited knowledge of Go's packaging system makes it very hard for me to tell. Do we perhaps have someone with a deeper knowledge of Go who could have a look?

**Comment by flokli** [comment]
let's poke @arianvp ;-)

**Comment by petabyteboy** [comment]
Any news? It is currently impossible to set up a gitlab-ee instance, because the old gitlab-ee version was removed from the repository.

**Comment by petabyteboy** [comment]
@bgamari did you forget to commit some things? I can not build gitlab-shell for multiple reasons. The patch could not be applied, and then it complained about missing "rubocop".

**Comment by bgamari** [comment]
Milan <notifications@github.com> writes:

> @bgamari did you forget to commit some things? I can not build gitlab-shell for multiple reasons. The patch could not be applied, and then it complained about missing "rubocop".
>
I just pushed the current state of my branch.

**Comment by bgamari** [comment]
Unfortunately I suspect that `gitlab-ee` fails with,
```
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: rake aborted!
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: NoMethodError: undefined method `mysql?' for Gitlab::Database:Module
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/ph31hylpcjdziv17iif1qjgnwy97hw8b-gitlab-ee-12.3.2/share/gitlab/config/initializers/active_record_mysql_timestamp.rb:7:in `<top (required)>'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/acrnaqnibcqfr9n4x5zdfpvbiyc9g4nd-ruby2.5.5-activesupport-5.2.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/acrnaqnibcqfr9n4x5zdfpvbiyc9g4nd-ruby2.5.5-activesupport-5.2.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/acrnaqnibcqfr9n4x5zdfpvbiyc9g4nd-ruby2.5.5-activesupport-5.2.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/acrnaqnibcqfr9n4x5zdfpvbiyc9g4nd-ruby2.5.5-activesupport-5.2.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/ihx2vzc5qnzlq31m4wm2x4drpr8v88jn-ruby2.5.5-railties-5.2.3/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:657:in `block in load_config_initializer'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/acrnaqnibcqfr9n4x5zdfpvbiyc9g4nd-ruby2.5.5-activesupport-5.2.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/ihx2vzc5qnzlq31m4wm2x4drpr8v88jn-ruby2.5.5-railties-5.2.3/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:656:in `load_config_initializer'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/ihx2vzc5qnzlq31m4wm2x4drpr8v88jn-ruby2.5.5-railties-5.2.3/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/ihx2vzc5qnzlq31m4wm2x4drpr8v88jn-ruby2.5.5-railties-5.2.3/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:613:in `each'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/ihx2vzc5qnzlq31m4wm2x4drpr8v88jn-ruby2.5.5-railties-5.2.3/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:613:in `block in <class:Engine>'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/ihx2vzc5qnzlq31m4wm2x4drpr8v88jn-ruby2.5.5-railties-5.2.3/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/ihx2vzc5qnzlq31m4wm2x4drpr8v88jn-ruby2.5.5-railties-5.2.3/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/ihx2vzc5qnzlq31m4wm2x4drpr8v88jn-ruby2.5.5-railties-5.2.3/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/ihx2vzc5qnzlq31m4wm2x4drpr8v88jn-ruby2.5.5-railties-5.2.3/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `each'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/ihx2vzc5qnzlq31m4wm2x4drpr8v88jn-ruby2.5.5-railties-5.2.3/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `tsort_each_child'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/ihx2vzc5qnzlq31m4wm2x4drpr8v88jn-ruby2.5.5-railties-5.2.3/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/ihx2vzc5qnzlq31m4wm2x4drpr8v88jn-ruby2.5.5-railties-5.2.3/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/ph31hylpcjdziv17iif1qjgnwy97hw8b-gitlab-ee-12.3.2/share/gitlab/config/environment.rb:6:in `<top (required)>'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/acrnaqnibcqfr9n4x5zdfpvbiyc9g4nd-ruby2.5.5-activesupport-5.2.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/acrnaqnibcqfr9n4x5zdfpvbiyc9g4nd-ruby2.5.5-activesupport-5.2.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/acrnaqnibcqfr9n4x5zdfpvbiyc9g4nd-ruby2.5.5-activesupport-5.2.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/acrnaqnibcqfr9n4x5zdfpvbiyc9g4nd-ruby2.5.5-activesupport-5.2.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/ihx2vzc5qnzlq31m4wm2x4drpr8v88jn-ruby2.5.5-railties-5.2.3/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:337:in `require_environment!'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/ihx2vzc5qnzlq31m4wm2x4drpr8v88jn-ruby2.5.5-railties-5.2.3/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: /nix/store/488nkhl1ys627sch7mjmi0kf30jhng83-gitlab-env-12.3.2/lib/ruby/gems/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: Tasks: TOP => db:migrate => db:load_config => environment
Oct 02 14:01:45 gitlab.haskell.org z0x511y6dv9fzi5an58l7j7n5xyandvn-unit-script-gitlab-pre-start[18032]: (See full trace by running task with --trace)
```

**Comment by globin** [comment]
MySQL support has been removed with 12.3, as far as I remember.

**Comment by bgamari** [comment]
Indeed, it looks like the problem was stale initializers in `/run/gitlab/config/initializers`. Perhaps these should be wiped during startup?

**Comment by bgamari** [comment]
I don't know if this is related but I am seeing [migration issues](https://gitlab.com/gitlab-org/gitlab/issues/33262) with `gitlab-ee`.

**Comment by bgamari** [comment]
Closing in favor of #70216.

**Pull request closed without merging**
