### PR TITLE
treewide: update 21.03 to 21.05

### PR DESCRIPTION
**Pull request by lukegb**
The NixOS 21.03 release has been delayed to 21.05. See NixOS/rfcs#80.

There are two instances of 21.03 which have been left as is, since they
are in stateVersion comparisons. This will ensure that existing user
configurations which refer to 21.03 will continue to work.

cc @jonringer @FRidh

### CODE REVIEW

**Comment by lukegb** [comment]
Note: this will break inflight PRs which add things to the release notes for 21.05, since this renames the release notes file to match the new version.

**Comment by jonringer** [comment]
partial overlap with #107565

**Comment by lukegb** [comment]
> partial overlap with #107565

Hrm, should I just drop this PR entirely in favour of that one?

**Comment by lukegb** [comment]
In any case, I realised I forgot the EOL date update on the 21.05 release notes, so updated that now too.

**Comment by lukegb** [comment]
@ofborg eval

**Comment by cole-h** [comment]
Not that this can be done in a PR, but we should rename the 21.03 milestone to 21.05 as well.

**Comment by vcunat** [comment]
OK, I did that immediately in this repo, so that we don't forget.

**Comment by cole-h** [comment]
I also went ahead and did the same for the org project (https://github.com/orgs/NixOS/projects/6).

**Comment by lukegb** [comment]
Rebased again to remove merge conflict.

**Review by cole-h — COMMENTED** [review]
2 more occurrences of 21.03 I found:

* https://github.com/lukegb/nixpkgs/blob/6340c4bf8ca5033b0723f14b52be0c5b69ecbd63/nixos/modules/services/web-apps/nextcloud.nix#L366
* https://github.com/lukegb/nixpkgs/blob/6340c4bf8ca5033b0723f14b52be0c5b69ecbd63/nixos/modules/services/web-apps/hedgedoc.nix#L8

**Comment by lukegb** [comment]
> 2 more occurrences of 21.03 I found:
> 
> * https://github.com/lukegb/nixpkgs/blob/6340c4bf8ca5033b0723f14b52be0c5b69ecbd63/nixos/modules/services/web-apps/nextcloud.nix#L366
> * https://github.com/lukegb/nixpkgs/blob/6340c4bf8ca5033b0723f14b52be0c5b69ecbd63/nixos/modules/services/web-apps/hedgedoc.nix#L8

Those are intentionally as is: they're comparing stateVersion, so to avoid breaking existing configs (generated with stateVersion = "21.03") they should remain as is, I think.

**Comment by FRidh** [comment]
We need to add 21.05 there *additionally*, considering 21.03 as a past release.

**Comment by lukegb** [comment]
> We need to add 21.05 there _additionally_, considering 21.03 as a past release, but I don't much about stateVersion though.

These two are both relative comparisons rather than exact comparisons.

For the Nextcloud one: there's no nextcloud21 release yet, so nextcloud20 should be the shipped release with stateVersion==21.03 and stateVersion==21.05.
For the Hedgehog one it was a one-off rename, so 21.03+ should call it hedgehog.

**Comment by jonringer** [comment]
https://gitlab.com/libosinfo/osinfo-db/-/merge_requests/263 has been merged, I think we are good to merge this now

**Review by jonringer — APPROVED** [review]

**Comment by jonringer** [comment]
> We need to add 21.05 there _additionally_, considering 21.03 as a past release, but I don't much about stateVersion though.

Agreed

**Comment by lukegb** [comment]
> > We need to add 21.05 there _additionally_, considering 21.03 as a past release, but I don't much about stateVersion though.
> 
> Agreed

I'm still unconvinced in those two specific cases:

* People who installed with nixos-unstable will have generated configuration.nix with 21.03 (which will never exist)
* The contract of configuration.nix is such that we shouldn't change things which will have material impact on system state
* nixos/modules/services/web-apps/nextcloud.nix:
  * If we replace 21.03 with 21.05, we'll downgrade people from nextcloud20 to nextcloud19, which is a breaking change.
  * If we do nothing, it'll "work" fine for people with either 21.03 or 21.05 in their stateVersion.
  * Doing `versionOlder stateVersion "21.03" && versionOlder stateVersion "21.05"` would be redundant and more than a little confusing. Anything older than 21.03 is obviously also going to be older than 21.05.
  * -> I've compromised and added a comment instead.
* nixos/modules/services/web-apps/hedgedoc.nix:
  * If we replace 21.03 with 21.05, we'll rename the user from "hedgedoc" back to "codimd", which is a breaking change.
  * If we do nothing, it'll work fine for people with either 21.03 or 21.05 in their stateVersion.
  * Doing `versionAtLeast config.system.stateVersion "21.03" || versionAtLeast config.system.stateVersion "21.05"` is redundant again and again super confusing. 21.05 is obviously >= 21.03.
  * -> I've compromised and added a comment instead.

**Review by jonringer — APPROVED** [review]
LGTM

**Review by cole-h — APPROVED** [review]
Diff LGTM as well.

**Comment by jonringer** [comment]
if you rebase the conflicts, I will merge. Sorry for neglecting this

**Review by jonringer — APPROVED** [review]
diff LGTM

**Comment by jonringer** [comment]
thank you @lukegb, sorry this got postponed longer than it needed to :)

**Pull request merged**
