### PR TITLE
pulp: fix build

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by calbrecht — APPROVED** [review]

**Review by prusnak — APPROVED** [review]

**Comment by calbrecht** [comment]
Tested it locally, they build now. I guess `pulp` needs the `pkgs.purescript` within `propagatedNativeBuildInputs`, because without:
```
[nix-shell:~/ws/nixpkgs]$ pulp test
* ERROR: `purs` executable not found.
```

**Comment by Mic92** [comment]
> Tested it locally, they build now. I guess `pulp` needs the `pkgs.purescript` within `propagatedNativeBuildInputs`, because without:
> 
> ```
> [nix-shell:~/ws/nixpkgs]$ pulp test
> * ERROR: `purs` executable not found.
> ```

I am not sure we should do this. We also do not bundle make with a C compiler. What is the common expectation here?

**Comment by calbrecht** [comment]
> I am not sure we should do this. We also do not bundle make with a C compiler. What is the common expectation here? An alternative would be to suffix $PATH to include purescript.

That is a good point. I did not look at it this way :) Also it is very easy to overcome. I just haven't thought much about it.

**Comment by Mic92** [comment]
It is the upstream expectation though to bundle it. Hence they made purescript installed with pulp. That's why I added it in the end.

**Pull request merged**
