### PR TITLE
breitbandmessung: init at 3.1.0

### PR DESCRIPTION
**Pull request by B4dM4n**
###### Motivation for this change

Add a new package for the German Breitbandmessung app. Sadly it is only available as a binary download.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by legendofmiracles** [comment]
Running this prints "your operating system is not supported"

**Comment by legendofmiracles** [comment]
Result of `nixpkgs-review pr 156855` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>breitbandmessung</li>
  </ul>
</details>

**Comment by B4dM4n** [comment]
I noticed this error when running the test, but I blamed it on a the test desktop environment not being sufficient. The main motivation for the test was checking if all dependencies can be loaded and that it does not crash immediately :sweat_smile:

@legendofmiracles can you please post the console output when running the program from a terminal?

**Comment by B4dM4n** [comment]
I found the problem. At first start, it checks whether it runs on a supported operating system, namely Ubuntu/Debian and when successful writes this information to it's config folder.

During testing I added a `fake-lsb-release` script, which emulates Debian.
But I removed the script after checking that the program still starts fine, which it does because of the stored information on my user account.

Now that the script is in place again, the program also starts fine during the test.

**Review by FliegendeWurst — APPROVED** [review]
Works fine, measures connection speeds correctly.

**Review by mweinelt — APPROVED** [review]
Tested and worked for me.

**Pull request merged**
