### PR TITLE
openrazer: 2.7.0 -> 2.8.0

### PR DESCRIPTION
**Pull request by evanjs**
###### Motivation for this change
[v2.8.0 Changelog](https://github.com/openrazer/openrazer/releases/tag/v2.8.0)
Support for several new devices added

Unsure if related to #92959 but figured it can/should be updated, anyway.

###### Things done
Bumped from 2.7.0 -> 2.8.0

cc @algram

### CODE REVIEW

**Review by roelvandijk — APPROVED** [review]

**Comment by Algram** [comment]
I would like to check if this changes fixes my problem. How would I best test this locally before the merge?

Thanks!

**Comment by evanjs** [comment]
> I would like to check if this changes fixes my problem. How would I best test this locally before the merge?
> 
> Thanks!

I'm lazy and typically use `gh` for checking out PRs
e.g. `nix run nixos.gitAndTools.gh --command gh pr checkout 93275` from a local `nixpkgs` repo
That aside, from the root of a local `nixpkgs` repository (with the PR checked out), one way is to run `nixos-rebuild switch -I nixpkgs=.`

This should rebuild your system with the main channel referencing the local `nixpkgs` repo instead.

There are probably better ways to do it, but this is how I currently test module updates.

**Comment by Algram** [comment]
Thanks! I tested it and it works on my end. The mouse gets recognized and I can communicate with it via DBUS.

**Review by endocrimes — APPROVED** [review]
Works for me (I have the same diff I was about to PR, that I'm currently running on my workstation)

**Comment by evanjs** [comment]
Curious, any other Razer users with merge/write permissions?

Not sure what else I can do (or who would be best to ping) aside from e.g. 
@GrahamcOfBorg build openrazer-daemon
or etc

**Pull request merged**
