### PR TITLE
Add opt-in BitcoinXT support

### PR DESCRIPTION
**Pull request by jefdaj**
I want to make this as uncontroversial as possible, so let me know if anything should be different!

### CODE REVIEW

**Comment by jefdaj** [comment]
Hmm ran out of memory. What now?

**Comment by offlinehacker** [comment]
Don't worry about travis, it happens a lot. Other question is why you don't make a separate file? This way it might be simpler, but technically it's a different package.

**Comment by offlinehacker** [comment]
Some reason why making a separate file might be better solution is that in case bitcoin-xt does not become popular somehow, and it supposedly becomes deprecated, the history of git changes will be cleaner.

**Comment by jefdaj** [comment]
Here's the branch with separate files. Think I should use it instead?

https://github.com/NixOS/nixpkgs/compare/master...jefdaj:bitcoinxt-twopackages

I originally went with the single file so it would be easy to keep them in sync, but it's not a big deal either way.

**Comment by jefdaj** [comment]
OK went ahead and added that as [9384](https://github.com/NixOS/nixpkgs/pull/9384).

**Comment by jefdaj** [comment]
OK went ahead and added that as [9384](https://github.com/NixOS/nixpkgs/pull/9384).

**Comment by ttuegel** [comment]
This appears to be superseded by #9384.

**Pull request closed without merging**
