### PR TITLE
protege-distribution: init at 5.5.0

### PR DESCRIPTION
**Pull request by nessdoor**
###### Motivation for this change
Stanford's Protege is the major open source OWL2 ontology editor for the Semantic Web. Although a web version is available and ready to run on any platform, the desktop version offers some more advanced functionalities (e.g. pluggable reasoner support) and, of course, offline operation.

The packaged application is the "distribution" version, that comes into a zip archive bundled with a collection of third-party plugins. All licenses for such plugins have been included in the meta-attributes.

For now, this is the only packaged version I can provide. In the future, as soon as I manage to get Maven builds work under Nix, I hope to be able to include the "bare" version compiled from the upstream repository, with no included plugins and better patches.

This application is supposedly platform-independent but, since I don't have a Darwin system available, I cannot guarantee functionality of this package on such OS. Help is welcome.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nessdoor** [comment]
I just noticed that I totally missed https://github.com/NixOS/nixpkgs/pull/97365 but, since the produced artifacts are different and this package is already working, maybe it is still valuable.

Waiting for feedback.

Sorry for not double-checking, I worked only from memory.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 127396` at 39a4c607 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>protege-distribution</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`lgpl3` is a deprecated license, please check if project uses `lgpl3Plus` or `lgpl3Only` and change `meta.license` accordingly.

Near pkgs/development/web/protege-distribution/default.nix:70:5:
```
   |
70 |     license = with licenses; [ asl20 bsd2 epl10 lgpl3 ];
   |     ^
```
</li>
  </ul>
</details>

**Comment by mucaho** [comment]
I think the previously proposed PR https://github.com/NixOS/nixpkgs/pull/97365 contained a cleaner and more future proof derivation to the unnecessary, hard-coded patching introduced by this PR

**Comment by nessdoor** [comment]
@mucaho Whether it was unnecessary I think is up for debate, but surely the patching process would need to be modified to a greater extent if a new launcher script was to be released.
Considering the very long release cycle of the tool and the fact that I _will_ maintain it and be sure to update it accordingly as (hopefully) new versions come out, I don't think it will be a big problem.

Anyway, I was also surprised by the merge and definitely would have been willing to discuss with you.

**Comment by mucaho** [comment]
> Anyway, I was also surprised by the merge and definitely would have been willing to discuss with you.

My comment was intended for the reviewer, in this case @SuperSandro2000 .
In the effort to get the huge numbers of PRs reviewed and merged, he may have missed comparing the old and new PR.
In the end, it doesn't matter, I just propose a few more changes to the current master version.

----

> @mucaho Whether it was unnecessary I think is up for debate [...]

These hard-coded replacements give in my opinion little value compared to the additional complexity of maintaining them.
I have been using protege using the previous PR's definition for over a year now with no observed issues in regards to the changes made by these replacements - these replacements affect non-issues in my opinion.

**_Suggestion 1_:** As you can see, I feel strongly in favor of removing these hard-coded sed replacement statements, but would like to hear your motivation behind those still.

> [...] surely the patching process would need to be modified to a greater extent if a new launcher script was to be released.
> Considering the very long release cycle of the tool and the fact that I _will_ maintain it and be sure to update it accordingly as (hopefully) new versions come out, I don't think it will be a big problem.

This is a noble goal, however in reality different people commit updates and changes to the package, which is evident by some package maintainers not being involved any more.
I think the package definition should be as simple and stupid as possible for other people to understand and adapt it, while still addressing any noteworthy issues.

**_Suggestion 2_:** The second thing I would like to see addressed is how the desktop icons get created. In the current version only a 128x128 ico file is put in to the share folder, whereas in the previously proposed version the code used the built-in icoToHiColorTheme converter tool which created multiple icons of different sizes.

The rest looks good to me, and even fixes some licensing attributes and the placement of the package in the top-level definition.

------

Pinging the people previously involved with this package if they would like to add something to this discussion: @doronbehar , @mgttlinger , @JonathanReeve .

**Comment by nessdoor** [comment]
@mucaho 

> These hard-coded replacements give in my opinion little value compared to the additional complexity of maintaining them.

So, the thing is that those seven lines of not particularly cristal-clear Bash implement a lot of logic in order to understand where the "installation" directory is. We know the correct path statically, so why keep them?
By evicting them all, we are left with a simple launcher that changes directory and launches a Java application with the recommended/mandated flags. Of course the Java command is still horrible and I would really like to have the patience and temper to knock on upstream's door and fix that (together with all those undocumented properties and configuration files full of relative paths and hard-coded strings that make the `cd` necessary in the first place). I think I wanted to have a cleaner launcher script and not have to result to double shellscript wrapping.

I can totally understand your point and I see the choice is debatable, but I really lean towards removing upstream cruft instead of wrapping around it. I just thought this would have been more of a no-brainer to maintain, since that path detection logic is probably not going to change much, and however it changes it will still be useless for us (I suppose).
That script has been touched for the last time more than 2 years ago. The specific annoying piece of logic has been introduced 5 years ago. I think the added maintenance complexity is amortized more than enough.

> The second thing I would like to see addressed is how the desktop icons get created.

Yes, absolutely, I discovered `icoFileToHiColorTheme` from _your_ PR. I didn't modify mine accordingly because I didn't know if i would have been out-merged, plus I thought it could have been perceived as blatant plagiarism to just make mine more appealing to the maintainers.
Please, PR it. I'll be sure to remember it for the next package.

P.S. A shameful thing of mine was outright deleting those console logging configuration lines. Yes, those are bad, I've been lazy there, but I was tired and wanted to conclude the thing, I suppose. I still think we should dispose of them, but instead do it through an orthodox patch.
If you want, PR it. If not, I will as soon as I manage to get the upstream, non-distribution Protege to build. Don't want to also dump fixup PRs into this already overflowing barrel.

**Comment by nessdoor** [comment]
Right, now that I think about it, maybe all those `sed`s should at least be `patch`es.
Sorry, I have been too much of a minimalist and disregarded the inherently self-documenting nature of diffs.

**Comment by mucaho** [comment]
> So, the thing is that those seven lines of not particularly cristal-clear Bash implement a lot of logic in order to understand where the "installation" directory is. We know the correct path statically, so why keep them?
By evicting them all, we are left with a simple launcher that changes directory and launches a Java application with the recommended/mandated flags. 
> [...]
> I think I wanted to have a cleaner launcher script and not have to result to double shellscript wrapping. 
> [...]
> Right, now that I think about it, maybe all those `sed`s should at least be `patch`es.
> Sorry, I have been too much of a minimalist and disregarded the inherently self-documenting nature of diffs.

Your motivation for the removal of these lines makes sense and that's an excellent idea to use patches, they are also commonly used in other packages and as you said, are self-documenting. Much better than current approach 👍 

---

If it's not too much of an ask, I would kindly suggest to submit a PR with the patch-based solution, as you know best which lines to remove.
If you see a good reason to remove console logging then do so as well in that patch (I currently don't understand the motivation behind this).

For the sake of simplicity I suggest to include the `icoFileToHiColorTheme` method in your PR as well.
Thanks for the consideration though, I care only about having the feasibly "best" solution in the repo 👍

**Comment by nessdoor** [comment]
Alright, before this week ends I will try to include all these modifications in a new PR, then.
Thank you very much for the feedback.

**Pull request merged**
