### PR TITLE
tor: 0.4.6.10 -> 0.4.7.7

### PR DESCRIPTION
**Pull request by prusnak**
###### Description of changes

- new stable release: https://forum.torproject.net/t/stable-release-0-4-7-7/3108

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by delroth** [comment]
Can repro the aarch64 test failures seen on onborg:

```
sandbox/open_filename: [forking]
  FAIL src/test/test_sandbox.c:158: open: Operation not permitted [1]
  [open_filename FAILED]
sandbox/opendir_dirname: [forking]
  FAIL src/test/test_sandbox.c:264: opendir: Operation not permitted [1]
  [opendir_dirname FAILED]
sandbox/openat_filename: [forking]
  FAIL src/test/test_sandbox.c:242: openat: Operation not permitted [1]
  [openat_filename FAILED]
sandbox/chmod_filename: [forking]
  FAIL src/test/test_sandbox.c:184: chmod: Operation not permitted [1]
  [chmod_filename FAILED]
sandbox/chown_filename: [forking]
  FAIL src/test/test_sandbox.c:202: chown: Operation not permitted [1]
  [chown_filename FAILED]
sandbox/rename_filename: [forking]
  FAIL src/test/test_sandbox.c:222: rename: Operation not permitted [1]
  [rename_filename FAILED]
```

**Comment by prusnak** [comment]
> Can repro the aarch64 test failures seen on ofborg:

Wondering what's the difference in sandboxing between x86_64-linux and aarch64-linux ...

**Comment by delroth** [comment]
Reported upstream: https://gitlab.torproject.org/tpo/core/tor/-/issues/40599

**Comment by delroth** [comment]
It doesn't seem like this is NixOS specific -- I noticed someone on the Tor side is working on adding arm64 CI, and the test fails similarly in their runs: https://gitlab.torproject.org/eighthave/tor/-/jobs/128518

Maybe we should build Tor on aarch64 with the sandbox disabled? (I think it can be optionally disabled, at least by not providing a libseccomp input?)

**Comment by prusnak** [comment]
> I think it can be optionally disabled, at least by not providing a libseccomp input?)

Disabled seccomp in 113ca3c (via a configure flag, removing libseccomp from inputs does not thing, because libseccomp is already present in the system as a dependency of something else).

**Comment by prusnak** [comment]
@GrahamcOfBorg build tor

**Review by delroth — APPROVED** [review]

**Pull request merged**
