### PR TITLE
vimPlugins.pum-vim: init at 2024-01-18

### PR DESCRIPTION
**Pull request by euank**
## Description of changes

This adds the [`pum.vim` plugin](https://github.com/Shougo/pum.vim).

This is mostly useful in conjunction with [ddc-ui-pum](https://github.com/Shougo/ddc-ui-pum), which I'll have a PR for shortly.

It's a vim plugin I use, and after a while of occasionally rebasing my own branch for this, I figured I'd see if I can put it upstream.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by PerchunPak** [comment]
Result of `nixpkgs-review pr 293288` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vimPlugins.pum-vim</li>
  </ul>
</details>

**Review by PerchunPak — APPROVED** [review]
LGTM!

[CC](https://github.com/NixOS/nixpkgs/pull/333817#issuecomment-2294798601) @GaetanLepage

**Comment by euank** [comment]
I went ahead and rebased + updated to the latest upstream git commit; I'll report back shortly after testing it in my vim configuration (with ddc-ui-pum)

**Comment by euank** [comment]
Reporting back, pulling this branch into my vim config (along with #293289) gives me a working setup, so this PR, after rebasing, still seems to work fine for me!

**Comment by PerchunPak** [comment]
But why updating the plugin in a second commit, why not squash those?

**Comment by euank** [comment]
No reason, squashed it down to one commit, thanks for the nudge to do so

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 293288` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>vimPlugins.pum-vim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Review by GaetanLepage — APPROVED** [review]
LGTM

**Pull request merged**
