### PR TITLE
nixos/tests/prosody: update prosody tests

### PR DESCRIPTION
**Pull request by Izorkin**
###### Motivation for this change
Moved ejabberd and prosody tests to xmpp folder.
Update prosody test to check work in local network.
Add test prosody test with mysql database.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Izorkin** [comment]
@GrahamcOfBorg test prosody prosodyMysql

**Review by teto — APPROVED** [review]
it tests more in-depth the xmpp prosody server.

**Comment by Izorkin** [comment]
@GrahamcOfBorg test prosody prosodyMysql

**Comment by aanderse** [comment]
@ajs124 can we get your approval please?

**Comment by teto** [comment]
@ajs124 are you fine with me merging this first ? you can update your PR later on

**Comment by ajs124** [comment]
@aanderse: Sure! In general this looks fine, although I cannot really speak to the prosody part of it. The one thing which should be fixed before merging is that the ejabberd wasn't actually moved, but copied. So if I'm not mistaken, we would end up with two ejabberd test.

@teto: Fine by me.

**Comment by ajs124** [comment]
ping

**Comment by aanderse** [comment]
@Izorkin can you please address the comment about two `ejabberd` tests by @ajs124?

**Comment by Izorkin** [comment]
Fixed error - not full moved ejabberd.nix to folder nixos/tests/xmpp

**Comment by Izorkin** [comment]
@GrahamcOfBorg test prosody prosodyMysql
@GrahamcOfBorg test ejabberd

**Pull request merged**
