### PR TITLE
element-{web,desktop}: hack to make ofborg maintainer pings work again

### PR DESCRIPTION
**Pull request by Ma27**
###### Description of changes

Until now we had the problem that the matrix team wasn't pinged on
element changes because the version data is in a JSON and the position
of the `version`-attribute wrongly pointed to
`element-{web,desktop}.nix`:

    nix-instantiate -E 'with import ./. {}; builtins.unsafeGetAttrPos "version" element-web' --eval
    { column = 22; file = "/home/ma27/Projects/nixpkgs/pkgs/applications/networking/instant-messengers/element/element-web.nix"; line = 24; }

This is a problem because ofborg checks if modified file is part of a
derivation that got changed in a PR. I.e. only pings for element's
maintainers would be added to an element update PR if `pin.json` (which
gets modified in that case) would be recognized as file being a part of
the changed derivations (element-web/element-desktop)[1]

However, JSON imports don't propagate attribute positions (I don't know
how one would that sanely implement btw), so I decided to change
`pin.json` to a `pin.nix` and merge the relevant contents into
element-web/element-desktop.

This is kinda hacky, but as a maintainer I'd like to get modified if
somebody touches element so I can review & merge that.

With this change the position detection works fine now:

    { column = 3; file = "/home/ma27/Projects/nixpkgs/pkgs/applications/networking/instant-messengers/element/pin.nix"; line = 2; }

[1] https://github.com/NixOS/ofborg/blob/released/ofborg/src/maintainers.nix

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
Since it doesn't change the way this is built, I'd like to backport it. I don't want to do manual element backports for several months again.

**Comment by Ma27** [comment]
OK, just tested this against ofborg locally (with the following change):

``` diff
diff --git a/ofborg/src/maintainers.nix b/ofborg/src/maintainers.nix
index c519725..dbc861e 100644
--- a/ofborg/src/maintainers.nix
+++ b/ofborg/src/maintainers.nix
@@ -1,6 +1,6 @@
 { changedattrsjson, changedpathsjson }:
 let
-  pkgs = import ./. {};
+  pkgs = import ../../../nixpkgs {};
 
   changedattrs = builtins.fromJSON (builtins.readFile changedattrsjson);
   changedpaths = builtins.fromJSON (builtins.readFile changedpathsjson);
```

```
$ echo '[["element-web"]]' > changedattrs.json
$ echo '["pkgs/applications/networking/instant-messengers/element/pin.nix"]' > changedpaths.json
```

`~/Projects/nixpkgs` points to `master`:
```
$ nix-instantiate ofborg/src/maintainers.nix --arg changedattrsjson ./changedattrs.json --arg changedpathsjson ./changedpaths.json --eval
{ }
```

`~/Projects/nixpkgs` points to this branch:

```
$ nix-instantiate ofborg/src/maintainers.nix --arg changedattrsjson ./changedattrs.json --arg changedpathsjson 
./changedpaths.json --eval
{ dali99 = <CODE>; ekleog = <CODE>; fadenb = <CODE>; ma27 = <CODE>; mguentner = <CODE>; ralith = <CODE>; sumnerevans = <CODE>; }
```

**Comment by IndeedNotJames** [comment]
I played a bit around with this, as it seemed fairly interesting.
Plus, the same issue also applies to essentially every other derivation in nixpkgs, that offloads certain things to an external file.

Considering the current variable names and structure of `pin.nix` (specifically `version` and no name collisions with other stuff in the original attrset), there seems to be another, smaller, but probably even more hacky way to archive the same:

```diff
diff --git a/pkgs/applications/networking/instant-messengers/element/element-web.nix b/pkgs/applications/networking/instant-messengers/element/element-web.nix
index b73fda72174..0535ada3dc9 100644
--- a/pkgs/applications/networking/instant-messengers/element/element-web.nix
+++ b/pkgs/applications/networking/instant-messengers/element/element-web.nix
@@ -12,12 +12,12 @@
 }:
 
 let
-  pinData = lib.importJSON ./pin.json;
+  pinData = import ./pin.nix;
   noPhoningHome = {
     disable_guests = true; # disable automatic guest account registration at matrix.org
   };
 in
-stdenv.mkDerivation rec {
+(stdenv.mkDerivation rec {
   pname = "element-web";
   inherit (pinData) version;
 
@@ -84,4 +84,4 @@ stdenv.mkDerivation rec {
     license = lib.licenses.asl20;
     platforms = lib.platforms.all;
   };
-}
+} // pinData)
```

I have no idea what horrible side effects that introduces^^

**Comment by Ma27** [comment]
>  Plus, the same issue also applies to essentially every other derivation in nixpkgs, that offloads certain things to an external file.

That's correct. I fixed it here because I'd like to get pinged when somebody updates a package I maintain, so it was rather selfish ;-)

But thanks for reminding me, I guess I'll bring this issue up to the Nixpkgs architecture team since that's a general problem (and I'm not sure how to globally fix that in a reasonable manner).

> I have no idea what horrible side effects that introduces^^

I just realized that `finalAttrs` is actually a pretty cool pattern because it ensures that you can override e.g. `version` and it gets properly applied everywhere. See for instance:

```nix
with import <nixpkgs> { };

(stdenv.mkDerivation rec {
  pname = "foo";
  version = "23";
  buildCommand = ''
    echo ${version} >$out
  '';
  preferLocalBuild = true;
}).overrideAttrs (_: { version = "24"; })
```

When you `nix-build` that, `$out` will be a file with `23` as content.

However when using `finalAttrs` like

```nix
with import <nixpkgs> { };

(stdenv.mkDerivation (final: {
  pname = "foo";
  version = "23";
  buildCommand = ''
    echo ${final.version} >$out
  '';
  preferLocalBuild = true;
})).overrideAttrs (_: { version = "24"; })
```

`$out` will be `24`. This was unintended by me, but it has the benefit that you can trivially override `version` in `overrideAttrs` now and the overriden version will be used everywhere.

Because of that I'd prefer the solution I implemented because of unintended, yet nice side-effects %)

**Pull request merged**
