### PR TITLE
kubectx: 0.5.1 -> 0.6.1

### PR DESCRIPTION
**Pull request by periklis**
Also provides shell completions for zsh, bash and fish

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by periklis** [comment]
cc @srhb

**Comment by srhb** [comment]
@GrahamcOfBorg build kubectx

**Comment by srhb** [comment]
Do you know how I can test zsh completions? Tab-completing after installing it seems to do nothing, but perhaps I need to do something else.

**Comment by periklis** [comment]
@srhb I am used to configure that on macos with nix-darwin, but afaik this is what you need to do:
https://github.com/LnL7/nix-darwin/blob/master/modules/programs/zsh/default.nix#L183

**Comment by srhb** [comment]
Right, I have zsh completions working normally, I mean that they don't appear to do anything for kubectx. I'm just wondering if I need to change something with kubectl in order to get them to work. Did you test them yourself? If it works for you, that's fine too.

**Comment by periklis** [comment]
i've tested myself, but i have already a `~/.kube/config` with some clusters listed.

**Comment by srhb** [comment]
OK, great!

**Pull request merged**
