### PR TITLE
tailscale: 1.22.2 -> 1.24.0

### PR DESCRIPTION
**Pull request by twitchyliquid64**
###### Description of changes

Update to new release: https://github.com/tailscale/tailscale/releases/tag/v1.24.0

Also adding myself as a maintainer since I joined Tailscale :)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by twitchyliquid64** [comment]
`nix-shell -p nixpkgs-review --run "nixpkgs-review pr 169896"`:

```shell
[xxx@xxx:~/projects/nixpkgs]$ NIX_PATH="nixpkgs=./" nix-shell -p nixpkgs-review --run "nixpkgs-review pr 169896"
<snip>
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/169896/head:refs/nixpkgs-review/1
From https://github.com/NixOS/nixpkgs
   9dc12546ab3..79d81ff4a80  master                -> refs/nixpkgs-review/0
   df6d1ee32ac..c7b93bcdd18  refs/pull/169896/head -> refs/nixpkgs-review/1
$ git worktree add /home/xxx/.cache/nixpkgs-review/pr-169896/nixpkgs 79d81ff4a80deddca317e46faab31d9d6df88cd4
Preparing worktree (detached HEAD 79d81ff4a80)
Updating files: 100% (30254/30254), done.
HEAD is now at 79d81ff4a80 Merge pull request #169261 from r-ryantm/auto-update/python3.10-vispy
$ nix-env --option system x86_64-linux -f /home/xxx/.cache/nixpkgs-review/pr-169896/nixpkgs -qaP --xml --out-path --show-trace
$ git merge --no-commit --no-ff c7b93bcdd1899399f92f9e5eb1f1fbf8b38e62c0
Automatic merge went well; stopped before committing as requested
$ nix-env --option system x86_64-linux -f /home/xxx/.cache/nixpkgs-review/pr-169896/nixpkgs -qaP --xml --out-path --show-trace --meta
1 package updated:
tailscale (1.22.2 → 1.24.0)

warning: ignoring the user-specified setting 'system', because it is a restricted setting and you are not a trusted user
$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/xxx/.cache/nixpkgs-review/pr-169896/build.nix
warning: ignoring the user-specified setting 'sandbox', because it is a restricted setting and you are not a trusted user
building '/nix/store/xjahmkv7n3g1c8qpj4ijx4sykw8my6p3-review-shell.drv'...

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/169896

1 package built:
tailscale

$ nix-shell /home/xxx/.cache/nixpkgs-review/pr-169896/shell.nix
[nix-shell:~/.cache/nixpkgs-review/pr-169896]$
```

**Review by danderson — APPROVED** [review]

**Comment by epk** [comment]
@danderson @twitchyliquid64 Can we backport to 21.11 and other releases? TIA

**Comment by twitchyliquid64** [comment]
@epk to do that we would need to backport all the Go 1.18 machinery or bring in tailscale-go - not sure if either of those would be palatable to upstream.

**Comment by danderson** [comment]
Yeah, Tailscale adopts new Go toolchains right away, so unless the Go toolchain team's willing to backport 1.18, I think this'd be a case of waiting for 22.xx, or blending the unstable tailscale package into your 21.11 install (which is what I do, fwiw).

**Comment by epk** [comment]
Sorry I wasn't aware of the dependency between Go versions and  NixOS releases. 


I copied Dave's older flake-less unstable override for tailscale and it works.

**Pull request merged**
