### PR TITLE
home-assistant: 2021.1.3 -> 2021.1.4 (+zigpy)

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://github.com/home-assistant/core/releases/tag/2021.1.4

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 109605` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>22 packages built:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python37Packages.bellows</li>
    <li>python37Packages.zha-quirks</li>
    <li>python37Packages.zigpy</li>
    <li>python37Packages.zigpy-deconz</li>
    <li>python37Packages.zigpy-znp</li>
    <li>python38Packages.bellows</li>
    <li>python38Packages.zha-quirks</li>
    <li>python38Packages.zigpy</li>
    <li>python38Packages.zigpy-cc</li>
    <li>python38Packages.zigpy-deconz</li>
    <li>python38Packages.zigpy-xbee</li>
    <li>python38Packages.zigpy-zigate</li>
    <li>python38Packages.zigpy-znp</li>
    <li>python39Packages.bellows</li>
    <li>python39Packages.zha-quirks</li>
    <li>python39Packages.zigpy</li>
    <li>python39Packages.zigpy-cc</li>
    <li>python39Packages.zigpy-deconz</li>
    <li>python39Packages.zigpy-xbee</li>
    <li>python39Packages.zigpy-zigate</li>
    <li>python39Packages.zigpy-znp</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
Looks good to me

**Comment by mweinelt** [comment]
aarch64 seems to run into a spurious test failure:

```
==================================== ERRORS ====================================
_______________ ERROR at setup of test_remove_older_logs[pyloop] _______________
[gw6] linux -- Python 3.8.6 /nix/store/yi9a1fafijn0nf5m8qkmnl955vi2mncm-python3-3.8.6/bin/python3.8
loop_factory = <class 'asyncio.unix_events._UnixDefaultEventLoopPolicy'>
fast = False, loop_debug = False
    @pytest.fixture
    def loop(loop_factory, fast, loop_debug):  # type: ignore
        """Return an instance of the event loop."""
        policy = loop_factory()
        asyncio.set_event_loop_policy(policy)
>       with loop_context(fast=fast) as _loop:
/nix/store/6ij587xhxfxngkx8d0brwgbhxv2ai1pj-python3.8-aiohttp-3.7.3/lib/python3.8/site-packages/aiohttp/pytest_plugin.py:228:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/nix/store/yi9a1fafijn0nf5m8qkmnl955vi2mncm-python3-3.8.6/lib/python3.8/contextlib.py:113: in __enter__
    return next(self.gen)
/nix/store/6ij587xhxfxngkx8d0brwgbhxv2ai1pj-python3.8-aiohttp-3.7.3/lib/python3.8/site-packages/aiohttp/test_utils.py:493: in loop_context
    loop = setup_test_loop(loop_factory)
/nix/store/6ij587xhxfxngkx8d0brwgbhxv2ai1pj-python3.8-aiohttp-3.7.3/lib/python3.8/site-packages/aiohttp/test_utils.py:514: in setup_test_loop
    asyncio.set_event_loop(loop)
/nix/store/yi9a1fafijn0nf5m8qkmnl955vi2mncm-python3-3.8.6/lib/python3.8/asyncio/events.py:753: in set_event_loop
    get_event_loop_policy().set_event_loop(loop)
/nix/store/yi9a1fafijn0nf5m8qkmnl955vi2mncm-python3-3.8.6/lib/python3.8/asyncio/unix_events.py:1365: in set_event_loop
    self._watcher.attach_loop(loop)
/nix/store/yi9a1fafijn0nf5m8qkmnl955vi2mncm-python3-3.8.6/lib/python3.8/asyncio/unix_events.py:931: in attach_loop
    self._do_waitpid_all()
/nix/store/yi9a1fafijn0nf5m8qkmnl955vi2mncm-python3-3.8.6/lib/python3.8/asyncio/unix_events.py:985: in _do_waitpid_all
    self._do_waitpid(pid)
/nix/store/yi9a1fafijn0nf5m8qkmnl955vi2mncm-python3-3.8.6/lib/python3.8/asyncio/unix_events.py:1019: in _do_waitpid
    callback(pid, returncode, *args)
/nix/store/yi9a1fafijn0nf5m8qkmnl955vi2mncm-python3-3.8.6/lib/python3.8/asyncio/unix_events.py:216: in _child_watcher_callback
    self.call_soon_threadsafe(transp._process_exited, returncode)
/nix/store/yi9a1fafijn0nf5m8qkmnl955vi2mncm-python3-3.8.6/lib/python3.8/asyncio/base_events.py:764: in call_soon_threadsafe
    self._check_closed()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <_UnixSelectorEventLoop running=False closed=True debug=False>
    def _check_closed(self):
        if self._closed:
>           raise RuntimeError('Event loop is closed')
E           RuntimeError: Event loop is closed
/nix/store/yi9a1fafijn0nf5m8qkmnl955vi2mncm-python3-3.8.6/lib/python3.8/asyncio/base_events.py:508: RuntimeError
```

**Comment by mweinelt** [comment]
Yep, flaky. Cannot repro on my local aarch64 host.

**Comment by mweinelt** [comment]
Sadly unable to reproduce locally.

**Comment by mweinelt** [comment]
Disabled the test case, as it just seems to be racy.

**Review by etu — COMMENTED** [review]
Works fine, just built it on my local setup with both Z-Wave and Zigbee devices.

**Pull request merged**
