### PR TITLE
selenium: 4.12.0 -> 4.14.0

### LINKED ISSUE #181035: pythonPackages.selenium: FileNotFoundError: [Errno 2] No such file or directory, 'getAttribute.js'
### Describe the bug
The selenium python bindings includes additional build artifacts(i.e javascript file) in its build process which are depended on for certain functionality. However, these files are not included when building with setuptools as they are built by bazel and copied into the source. This result in errors at runtime when certain functions are called which requires loading the javascript files. For instance, `get_attribute` and `is_displayed`.

This seems to be caused by the version bump 3.141.0 -> 4.2.0  in https://github.com/NixOS/nixpkgs/commit/8466ac2820966da53ff0d8aafbb01380cab195e4 as prior versions are built using the sdist tarball on PyPi which include the necessary build artifacts. Version 4.0.0 do not have corresponding sdist tarball available as reported in https://github.com/SeleniumHQ/selenium/issues/9917 and subsequent version also do not seem to have them.

Relevant files: https://github.com/SeleniumHQ/selenium/blob/7b1c6461f618fefcb8fec4a972bc7ec1abb47c34/py/BUILD.bazel#L84-L107

### Steps To Reproduce
Rough reproducible example:
```py
  #!/usr/bin/env nix-shell
  #!nix-shell -i python3 -p "python39.withPackages(ps: [ ps.selenium ])"
  #!nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/87e7965bbcdbac3d103e3ed14ff04f719a4f7a58.tar.gz
  from selenium import webdriver
  from selenium.webdriver.firefox.options import Options
  from selenium.webdriver.common.by import By
  
  options = Options()
  options.headless = True
  
  driver = webdriver.Firefox(options=options)
  driver.get("https://quotes.toscrape.com/")
  element = driver.find_element(By.XPATH, "//div[@class='quote']")
  print(element.get_attribute("innerHTML"))
  driver.quit()
```

<details>
  <summary>Error log</summary>
  
  ```
    Traceback (most recent call last):
      File "/home/user/test.py", line 11, in <module>
        print(element.get_attribute("innerHTML"))
      File "/nix/store/nlcjwyijydldr02ynhsa9kv5wvxs44b3-python3-3.9.13-env/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 172, in get_attribute
        _load_js()
      File "/nix/store/nlcjwyijydldr02ynhsa9kv5wvxs44b3-python3-3.9.13-env/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 45, in _load_js
        getAttribute_js = pkgutil.get_data(_pkg, 'getAttribute.js').decode('utf8')
      File "/nix/store/r8hi2lpzycparplcq0y663c43866f9bz-python3-3.9.13/lib/python3.9/pkgutil.py", line 639, in get_data
        return loader.get_data(resource_name)
      File "<frozen importlib._bootstrap_external>", line 1039, in get_data
    FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/nlcjwyijydldr02ynhsa9kv5wvxs44b3-python3-3.9.13-env/lib/python3.9/site-packages/selenium/webdriver/remote/getAttribute.js'
  ```
</details>

### Expected behavior
The javascript build artifacts are present in the python environment and the `get_attribute` function call completes successfully.

### Additional context
According to https://github.com/SeleniumHQ/selenium/issues/10083#issuecomment-982068916, the recommended way to build from source is invoking `bazel build //py:selenium-wheel` on the source repository. I am not familiar with bazel and the python packaging framework in Nixpkgs but would it be possible to utilize bazel in the selenium build process? 

### Notify maintainers

@jraygauthier @SuperSandro2000 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.9, NixOS, 22.11 (Raccoon), 22.11.20220708.b39924f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by arkivm**
## Description of changes

Fixes #181035, #230232

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sdht0** [comment]
Doesn't look like the changes are working. With 4.8 atleast chrome starts successfully.
```
File /nix/store/vz7incjb6l9234l2mr7ajbhysw1mvjdg-python3.10-selenium-4.13.0/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:229, in ErrorHandler.check_response(self, response)
    227         alert_text = value["alert"].get("text")
    228     raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
--> 229 raise exception_class(message, screen, stacktrace)

SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/sdh/.cache/selenium/chrome/linux64/117.0.5938.92/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

**Comment by arkivm** [comment]
> These changes leads to a chrome crash for me. With 4.8 atleast chrome was starting successfully, but hitting the linked bug.

Care to post a MWE that triggers this bug? Also post on which arch you encounter this crash. On `aarch64-darwin` the following example works.
```python
#!/usr/bin/env python3

from selenium import webdriver

driver = webdriver.Chrome()
driver.get("https://nixos.org")
print(driver.title)
driver.close()
```

**Comment by sdht0** [comment]
Right, this is on x86_64-linux. These same commands work with selenium 4.8. 
```
with import ~/nixpkgs {};

mkShell {
  name = "python-devel";
  venvDir = "venv";

  nativeBuildInputs = [ chromedriver ];
 
  buildInputs = with python3Packages; [ selenium ];
}
```
```bash
$ nix-shell
$ python
>>> from selenium import webdriver
>>> from selenium.webdriver.chrome.service import Service
>>> browser = webdriver.Chrome()                                                                                                                                                                                                                                                                                      
Traceback (most recent call last):                                                                                                                                                                                                                                                                                        
  File "<stdin>", line 1, in <module>                                                                                                                                                                                                                                                                                         
  File "/nix/store/vz7incjb6l9234l2mr7ajbhysw1mvjdg-python3.10-selenium-4.13.0/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__                                                                                                                                                     
    super().__init__(                                                                                                                                                                                                                                                                                                         
  File "/nix/store/vz7incjb6l9234l2mr7ajbhysw1mvjdg-python3.10-selenium-4.13.0/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__                                                                                                                                                   
    super().__init__(                                                                                                                                                                                                                                                                                                         
  File "/nix/store/vz7incjb6l9234l2mr7ajbhysw1mvjdg-python3.10-selenium-4.13.0/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 205, in __init__                                                                                                                                                    
    self.start_session(capabilities)                                                                                                                                                                                                                                                                                          
  File "/nix/store/vz7incjb6l9234l2mr7ajbhysw1mvjdg-python3.10-selenium-4.13.0/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 289, in start_session                                                                                                                                               
    response = self.execute(Command.NEW_SESSION, caps)["value"]                                                                                                                                                                                                                                                               
  File "/nix/store/vz7incjb6l9234l2mr7ajbhysw1mvjdg-python3.10-selenium-4.13.0/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute                                                                                                                                                     
    self.error_handler.check_response(response)                                                                                                                                                                                                                                                                               
  File "/nix/store/vz7incjb6l9234l2mr7ajbhysw1mvjdg-python3.10-selenium-4.13.0/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response                                                                                                                                           
    raise exception_class(message, screen, stacktrace)                                                                                                                                                                                                                                                                        
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.                                                                                                                                                                                                 
  (session not created: DevToolsActivePort file doesn't exist)                                                                                                                                                                                                                                                                
  (The process started from chrome location /home/sdh/.cache/selenium/chrome/linux64/117.0.5938.92/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:                                                                                                                                                                                                                                                                                                                   
#0 0x55af144ce6b3 <unknown>                                                    
#1 0x55af141a41e7 <unknown>                                                    
#2 0x55af141d7526 <unknown>                                                    
#3 0x55af141d369c <unknown>                                                    
#4 0x55af1421623a <unknown>                                                    
#5 0x55af1420ce93 <unknown>                                                    
#6 0x55af141df934 <unknown>                                                    
#7 0x55af141e071e <unknown>                                                    
#8 0x55af14493cb8 <unknown>                                                    
#9 0x55af14497bf0 <unknown>                                                    
#10 0x55af144a219c <unknown>                                                   
#11 0x55af14498808 <unknown>                                                   
#12 0x55af1446527f <unknown>                                                   
#13 0x55af144bce88 <unknown>                                                   
#14 0x55af144bd059 <unknown>                                                   
#15 0x55af144cd843 <unknown>                                                   
#16 0x7fcd1beecdd4 start_thread 
```

**Comment by sdht0** [comment]
So it looks like a change in selenium behavior. I got it working by explicitly setting path to `chromium` (and not `chrome`). 
```
>>> from selenium.webdriver.chrome.options import Options
>>> opts = Options()
>>> opts.binary_location = "/run/current-system/sw/bin/chromium"
>>> d = webdriver.Chrome(opts)
>>> d.get("https://nixos.org")
```
So yeah it was an issue on my end. The PR is good to go.

**Comment by arkivm** [comment]
Thanks for testing @sdht0. I managed to test it on x86_64_linux with google chrome and it works there too.

**Comment by AleXoundOS** [comment]
The current python3Packages.selenium version in master is 4.12.0. But it introduced problems using it, which also affect running [some NixOS tests](https://github.com/NixOS/nixpkgs/pull/260518#issuecomment-1785410436). @mweinelt, as for now, I would kindly suggest to revert python3Packages.selenium package back to the working version 4.8.0. While solving the remaining problems (e.g. selenium-manager related) through this issue.

**Comment by AleXoundOS** [comment]
Hotfix for python3Packages.selenium: #264386.

**Review by AleXoundOS — COMMENTED** [review]
I tested the current changes with `geckodriver` and it works. However, the current test uses only `geckodriver` and maybe we should add test(s) for other driver(s) too?

**Comment by arkivm** [comment]
@sdht0 tested it on chrome. I have tested it on ff (geckodriver) and chrome as well. @AleXoundOS Let me know if you'd prefer this patch instead of the hotfix. I will rebase this patch on top of the current master.

**Comment by AleXoundOS** [comment]
@arkivm, I'm quite new to the selenium ecosystem. I was just writing NixOS tests and they broke after a recent rebase on master. First hotfix solution was provided by @mweinelt and I was fine with it. Later I realized that the patch from this issue already provides a fix. But I'm not experienced enough here to say whether it's ready to be merged or not.

It looks this patch provides a more general solution (somehow getting the selenium-manager to work with Nix).

**Comment by mweinelt** [comment]
Unfortunately I'm not a selenium expert either, and I don't currently have the capacity to review what happens in `postInstall`. I propose we got with my workaround now, as this PR needs a rebase anyway.

**Comment by arkivm** [comment]
Your hotfix https://github.com/NixOS/nixpkgs/pull/264386 works only on firefox and doesn't fix other long-standing issues (https://github.com/NixOS/nixpkgs/issues/181035, https://github.com/NixOS/nixpkgs/issues/230232). The need for rebasing shouldn't stop us. Updated selenium to v4.14.0. `postInstall` essentially does what bazel does [here](https://github.com/SeleniumHQ/selenium/blob/selenium-4.14.0/py/BUILD.bazel#L52-L99) in their official repo.

**Comment by mweinelt** [comment]
Too big for master, needs to be rebased on top of staging-next.

**Comment by mweinelt** [comment]
Not quite there yet. That's 42 commits too much.

**Comment by mweinelt** [comment]
Since you are touching the python package, the attribute name in the commit message should read `python311Packages.selenium`.

Additionally the release notes for the all intermediate releases should be attached to the commit message.

**Comment by arkivm** [comment]
> Additionally the release notes for the all intermediate releases should be attached to the commit message.

Would be even more nice if every commit had it. https://github.com/NixOS/nixpkgs/commit/612f8e91417ec1985cc865b7c2b42819f7a0ece9

**Comment by mweinelt** [comment]
That commit was part of a bulk update series, and the script used to do that unfortunately does not support that yet.

Feel free to improve it. It is at `pkgs/development/interpreters/python/update-python-libraries/update-python-libraries.py`.

**Comment by AleXoundOS** [comment]
2 weeks have passed since https://github.com/NixOS/nixpkgs/pull/257728/commits/b222b771cdf67cbcd0bfa62f742bbbc1a3342168 has landed in staging-next, but it's still missing in master branch. @mweinelt, is it expected to take so long or did something go wrong with the merge or testing?

cc: @arkivm

**Comment by mweinelt** [comment]
The staging cycle has unfortunately encountered delays.

**Pull request merged**
