### PR TITLE
youtube-dl: 2016.07.16 -> 2016.09.19

### PR DESCRIPTION
**Pull request by goetzst**
###### Motivation for this change

youtube-dl couldn't play twitch streams (server response 400 Bad Request). Newest version fixes this.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lsix** [comment]
Apparently, there is a `2016.09.19` release available. Maybe bump up to that version?

**Comment by goetzst** [comment]
wasn't available yesterday. I'll update.

**Comment by Profpatsch** [comment]
If they release one version each day you don’t have to update daily of course (maybe monthly?).

**Comment by goetzst** [comment]
I could go with monthly yes

**Pull request merged**
