### PR TITLE
authelia: fix update script

### PR DESCRIPTION
**Pull request by 06kellyjac**
## Description of changes
Prepare for future release
Don't use a patch that is prone to needing updating
Visibly fail

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by IreneKnapp** [comment]
I tested this (manually tweaking NEW_VERSION to "4.38.0-beta3", as we discussed on Matrix), and it works great!

Kudos also on the change to substituteInPlace instead of a patch file, I wouldn't have thought of that.

**Comment by 06kellyjac** [comment]
Ah I didn't see `v4.38.0-beta3` but I guess it was a branch rather than pre-release tag?

glad it works now

**Comment by IreneKnapp** [comment]
correct, it's a branch, hence easy to miss. of course nixpkgs shouldn't actually update authelia until there's a non-beta release, but it's good for the script to work :)

**Comment by IreneKnapp** [comment]
@06kellyjac just so you know, there's discussion over on https://github.com/wxWidgets/wxWidgets/pull/23309 of making sure to announce this kind of thing in advance going forward, so it can be tested. since you're the maintainer for the nix wxGTK package I thought you might want to be involved.

**Pull request merged**
