### PR TITLE
pythonPackages.Mako: cleanup & enable PyPy tests

### PR DESCRIPTION
**Pull request by drewrisinger**
###### Motivation for this change
While fixing #98391, found some out of date things in ``pythonPackages.Mako``.

* Cleaned up meta
* Enabled more tests
* Updated issue links to new non-BitBucket location.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Fails on pypy2.7, maybe disable?

```
=================================== FAILURES ===================================
____________________ EncodingTest.test_bytestring_passthru _____________________
Traceback (most recent call last):
  File "/build/Mako-1.1.3/test/test_template.py", line 603, in test_bytestring_passthru
    self.assertRaises(UnicodeDecodeError, template.render)
  File "/nix/store/idb40rk8awki0mjjsd2amdj3q1biiwm6-pypy-7.3.1/pypy-c/lib-python/2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/nix/store/idb40rk8awki0mjjsd2amdj3q1biiwm6-pypy-7.3.1/pypy-c/lib-python/2.7/unittest/case.py", line 116, in __exit__
    "{0} not raised".format(exc_name))
AssertionError: UnicodeDecodeError not raised
=========================== short test summary info ============================
FAILED test/test_template.py::EncodingTest::test_bytestring_passthru - Assert...
======= 1 failed, 406 passed, 59 skipped, 3 deselected in 11.77 seconds ========
builder for '/nix/store/3hvxvax9kf8i24bjs1f8hg1mbzg86760-pypy2.7-Mako-1.1.3.drv' failed with exit code 1
```

**Comment by jonringer** [comment]
@GrahamcOfBorg build azure-cli
@GrahamcOfBorg build python2Packages.Mako
@GrahamcOfBorg build python3Packages.Mako
@GrahamcOfBorg build python37Packages.Mako

**Comment by drewrisinger** [comment]
Thanks @mweinelt, didn't find that in my spot check. Fixed & pushed.

**Comment by jonringer** [comment]
@GrahamcOfBorg build azure-cli
@GrahamcOfBorg build python2Packages.Mako
@GrahamcOfBorg build python3Packages.Mako
@GrahamcOfBorg build python37Packages.Mako

**Review by jonringer — APPROVED** [review]
LGTM

```
[09:05:44] jon@nixos ~/projects/nixpkgs (dr-pr-mako-cleanup)
$ nbfkg azure-cli python3Packages.Mako python37Packages.Mako python2Packages.Mako
[1 built, 0.0 MiB DL]
```

**Pull request merged**
