### PR TITLE
[21.11] remote-touchpad: 1.0.5 -> 1.1.0

### PR DESCRIPTION
**Pull request by schnusch**
###### Motivation for this change

This depends on #157274.
(cherry picked from commit 1ac72e43ac6f8d815e399d98947222fcba670cbd)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by AtilaSaraiva — APPROVED** [review]
I've tested your commit and it indeed built normally. I can't test for functionality since I use wayland, but I assume it is working since it reported it as an incompatible env.

**Comment by vcunat** [comment]
I can't see why this should be backported.  See https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-stable-release-branches

**Comment by schnusch** [comment]
Mainly why not.

    However, many changes are able to be backported, including:
      * [...]
      * Version updates which include new functionality (but no breaking changes)
      * [...]

As this does not seem to introduce any breaking changes, per the [changelog](https://github.com/Unrud/remote-touchpad/blob/v1.1.0/CHANGELOG.md), I see not reason why it could not be backported.

**Comment by vcunat** [comment]
Looks OK(-ish) in this case.  You're nixpkgs-side maintainer of it and apparently consider it sufficiently low-risk (breakages due to new bugs, etc.) and I see nothing contrary to that.

I don't perfectly like the formulation of that line, as in my eyes it could be interpreted too broadly, but that's another thing.  I raised it in the relatively recent PR introducing this text.

**Comment by vcunat** [comment]
I work for one such project myself, but I'm still not putting _every_ update into NixPkgs stable branches.  Of course, it's subjective where you cut the tradeoff between old bugs and new bugs.

**Pull request merged**
