### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Automake fails
```
stripping (with command strip and flags -S) in /nix/store/67rfgwqzas6lrsymv0vinacbkmv57xzv-automake-1.15/bin 
checking for references to /build/ in /nix/store/67rfgwqzas6lrsymv0vinacbkmv57xzv-automake-1.15...
invalid ownership on file '/nix/store/67rfgwqzas6lrsymv0vinacbkmv57xzv-automake-1.15/bin/aclocal'
```
https://hydra.nixos.org/build/95671911

**Comment by FRidh** [comment]
I have not been able to reproduce this issue locally.

**Comment by vcunat** [comment]
Darwin stdenv won't build, at least on Hydra: https://hydra.nixos.org/build/95653283  I don't know if that's also some impurity from the builders.

**Comment by FRidh** [comment]
cc @NixOS/darwin-maintainers

**Comment by LnL7** [comment]
Bootstrapping problem, cmake was updated. That should fix it.

**Pull request merged**
