### PR TITLE
mates: init at 0.1.0

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by wizeman** [comment]
I fixed a bug in `fetch-cargo-deps` which was causing your failure.
However, now it's causing a different failure: a hash mismatch.

I believe the reason for the hash mismatch is because there is a git dependency in `Cargo.toml`, which is very hard to make deterministic. It is essentially the same problem as #8567, but it's harder to fix because `cargo` doesn't call into `git`. Instead, it uses git as a library, so we cannot easily fake its output...

For now I'm going to merge your PR, but keep in mind that it's likely that this program will likely continue to experience build failures because of this git dependency in `Cargo.toml`...

**Comment by DamienCassou** [comment]
What can I do when build fails?

**Comment by wizeman** [comment]
When the build fails you can fix the hash and try building it again.
However, that is not a long-term solution. As a more long-term solution I would recommend contacting the upstream developers to try and see if they could upload the git dependency into crates.io, so that there aren't any git dependencies in `Cargo.toml`.
Also, if time allows, I will try and further debug this issue to see what's causing the non-deterministic git repositories, so as to try and avoid these type of problems in the future.

**Pull request merged**
