### PR TITLE
python.pkgs.python-language-server: init at 0.18.0

### PR DESCRIPTION
**Pull request by Mic92**
###### Motivation for this change

I use the following snippet for the plugins (put it into `environment.systemPackages` for example).

```nix
(python3.withPackages(ps: [ps.pyls-mypy ps.pyls-isort ])) 
```

and the following snippets in neovim:

```vim
let g:LanguageClient_serverCommands = {
     \ 'python': ['pyls']
     \ }
```

which is provided by the LanguageClient-neovim as shown in my dotfiles: https://github.com/Mic92/dotfiles/blob/master/nixpkgs-config/config.nix#L26

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build python.pkgs.python-language-server

**Comment by teto** [comment]
Looks good. Closing this then https://github.com/NixOS/nixpkgs/pull/31180

**Comment by Mic92** [comment]
Ah, I did not check, what we got before.

**Comment by Mic92** [comment]
Turns out both packages are empty at the moment.

**Comment by Mic92** [comment]
Fixed.

**Comment by Mic92** [comment]
@GrahamcOfBorg build python.pkgs.python-language-server python3.pkgs.python-language-server
python3.pkgs.pyls-mypy python3.pkgs.pyls-isort

**Comment by Mic92** [comment]
Also added in the wiki: https://nixos.wiki/wiki/Vim#Vim_as_a_Python_IDE

**Pull request merged**
