### PR TITLE
rabbitmq-server: 3.10.8 -> 3.11.2

### PR DESCRIPTION
**Pull request by ajs124**
###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by turion** [comment]
Why does the test segfault on x86_64-darwin?

**Comment by ajs124** [comment]
Apparently `erlangR25` does not build on `x86_64-darwin`? cc @NixOS/beam

**Comment by happysalada** [comment]
Ok good to know, i havent had a chance to test or debug, will put it in the todo list

**Comment by ajs124** [comment]
> Why does the test segfault on x86_64-darwin?

Considering #169956, we should just ignore that failure.

Also the test stopped evaluating due to a combination of #169644 and #201859

**Comment by happysalada** [comment]
@GrahamcOfBorg eval

**Comment by happysalada** [comment]
I agree here.
I took forthcoming steps and merged since i didnt expect a rush of opinions on this one. Happy to reconsider if anyone feels strongly against this

**Comment by DianaOlympos** [comment]
Work for me. Erlang cross-compilation in nixpkgs has been broken for quite some time (i would like to have it for graviton2 instances in AWS) but I have never been able to figure out how to fix it. I spent a week on it, and I feel like I understand even less now than before the experiment. Cross-compilation in nixpkgs feels like there is no-one able to help us with that anymore. And it is not helped by the erlang bootstrap process being _fairly invovled_

I would love to take another stab at it, but I feel I need help from an expert in nixpkgs cross-compilation for that.

**Comment by yorickvP** [comment]
RabbitMQ 3.11 is not backwards compatible with earlier versions. Steps should be taken before upgrading. https://blog.rabbitmq.com/posts/2022/07/required-feature-flags-in-rabbitmq-3.11/

Please write a release note.

**Pull request merged**
