### PR TITLE
Gnome 3.22

### PR DESCRIPTION
**Pull request by DamienCassou**
Start packaging Gnome 3.22 (even though it's not yet released).

### CODE REVIEW

**Comment by lethalman** [comment]
Thanks a lot. I'm not going to merge however, it's quite a lot of effort to change the version from 3.21 to 3.22 afterwards, and we most likely lose changes from 3.20 during that time. Also, everytime we upgraded to a new major version we had troubles that had been fixed afterwards by minor versions.

**Comment by groxxda** [comment]
@DamienCassou  did you make progress?  3.22 is out since a few days.

I have a branch with most versions updated (some are not picked up by the maintainers script)
and started filing PRs for the base libraries.
#18850 #18849 #18848 maybe others :sleeping: 

`gdm` is probably still causing the most headache, since the last versions already didn't make it into nixpkgs.

I'm still not a member of the organization, but it would be easiest to have a gnome322 branch and a hydra jobset like we had for 3.20 to collaborate on this.


Another thing I was thinking of:
fedora switched to wayland as a default and uses xwayland for the incompatible stuff. Imho it's about time to do the same in nixos (__rootless graphical.target__). If others are interested as well we should try to coordinate our effort to get a first working version asap (since 16.09 is brand new now seems to be a good time). Of course we will have to find someone taking care of kde, I have no idea whats the state of kde and wayland :wink: 
cc @lethalman @jgeerds

**Comment by lethalman** [comment]
@groxxda it would be better to do the wayland transition in a second step in my opionion, otherwise it would delay GNOME 3.22.

**Comment by cmfwyp** [comment]
Wayland isn't even an option at login right now. The first thing to do would be to add it and make it the default (but keep the option to use X.Org).

Also, I believe `services.xserver.desktopManager.gnome3.enable` should follow [the upstream modulesets](https://blogs.gnome.org/mcatanzaro/2016/09/21/gnome-3-22-core-apps/).

These two things don't need to be done at the same time as upgrading GNOME 3.22 if that would delay it.

**Comment by groxxda** [comment]
Okay, then let's focus on gnome in general first :)

**Comment by DamienCassou** [comment]
I didn't do anything more. Please go on, I don't have time right now. Thank you.

**Comment by vcunat** [comment]
I assume this work is all obsolete. Otherwise, rebase against the version of gnome-3.22 that's got to staging recently.

**Comment by thomastjeffery** [comment]
If I set my configuration.nix to have the lines
`services.xserver.desktopManager.gnome3.enable = true;`
`environment.gnome3.packageSet = pkgs.gnome3_22;`

I still end up with GNOME `3.0` installed.

How do I install a reasonably up-to-date version of GNOME?

**Comment by jgeerds** [comment]
@thomastjeffery how did you verify this? Did you look in "Settings → Detail" ? The version number isn't the right one . I guess we're missing some env var during compiling or something like that.

Open a terminal and check it like this:
```
$ readlink $(type -P gnome-shell)
/nix/store/d8ai7shdgigd3rcfaxldrfrzvw2q0pzf-gnome-shell-3.22.0/bin/gnome-shell
```

**Comment by thomastjeffery** [comment]
Looks like you are correct.

I assumed that version number was correct because of some issues I was having: I cannot add an input method (and the `setxkbmap` line in my `~/.xprofile` gets overridden), and there is no way to log out (end the X session) instead of shutting down (probably due to a very minimal default configuration, but I would still consider this a bug).

I'll probably stick with Plasma5 anyway, but I would be happy to test any changes in the GNOME 3 package.

**Pull request closed without merging**
