### PR TITLE
python3Packages.clvm-rs: 0.1.19 -> 0.3.0

### PR DESCRIPTION
**Pull request by otavio**
ZHF: #265948
https://hydra.nixos.org/build/241412268

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by natsukium** [comment]
@ofborg build python311Packages.clvm-rs

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 268608` at 00111365 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>chia</li>
    <li>chia-dev-tools</li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python310Packages.clvm-rs</li>
    <li>python311Packages.clvm-rs</li>
  </ul>
</details>

**Comment by natsukium** [comment]
clvm-rs seems to be able to build now, can you fix chia?
I'm not interested in blockchain, but I think it is nice to be able to use chia.

**Comment by otavio** [comment]
I am unsure if I will be able to look at this soon. I will be traveling during the weekend.

**Comment by natsukium** [comment]
Let's merge this now and get someone interested in chia to fix it.

**Review by natsukium — APPROVED** [review]
LGTM, thanks.

**Comment by lourkeur** [comment]
The mutt promising way to fix chia would be to properly update it imho: #252913

It's also not good to be 3 major versions behind so I will probably make a PR to flag it as problematic if the other PR doesn't make it

**Pull request merged**
