### PR TITLE
[pulumi-language-python] Add libstdc++.so.6

### PR DESCRIPTION
**Pull request by glennpratt**
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/code/bootstrap/venv/lib/python3.11/site-packages/pulumi/__init__.py", line 33, in <module>
    from .config import (
  File "/code/bootstrap/venv/lib/python3.11/site-packages/pulumi/config.py", line 22, in <module>
    from . import log
  File "/code/bootstrap/venv/lib/python3.11/site-packages/pulumi/log.py", line 22, in <module>
    from .runtime.settings import get_engine
  File "/code/bootstrap/venv/lib/python3.11/site-packages/pulumi/runtime/__init__.py", line 29, in <module>
    from .mocks import (
  File "/code/bootstrap/venv/lib/python3.11/site-packages/pulumi/runtime/mocks.py", line 23, in <module>
    from . import rpc, rpc_manager
  File "/code/bootstrap/venv/lib/python3.11/site-packages/pulumi/runtime/rpc.py", line 41, in <module>
    from . import known_types, settings
  File "/code/bootstrap/venv/lib/python3.11/site-packages/pulumi/runtime/settings.py", line 25, in <module>
    import grpc
  File "/code/bootstrap/venv/lib/python3.11/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/code/bootstrap/venv/lib/python3.11/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory
```

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by natsukium** [comment]
@ofborg eval

**Comment by glennpratt** [comment]
Converted to a draft as I wasn't able to test this locally yet.

**Comment by Trundle** [comment]
This happens because the `pulumi` package is coming from PyPI and not from nixpkgs . You get the same error when you pip-install `grpcio` and try to use it, without Pulumi being involved.

I think when using a Python from nixpkgs, it's best to also use Python packages coming from nixpkgs. You can use `pkgs.python3.withPackages (ps: [ps.pulumi])` to get a Python which can use the `pulumi` package.

**Comment by glennpratt** [comment]
Thanks @Trundle!

**Pull request closed without merging**
