### PR TITLE
anki: 2.1.61 -> 2.1.65

### PR DESCRIPTION
**Pull request by euank**
###### Description of changes

Upstream changelog: https://github.com/ankitects/anki/releases/tag/2.1.65

The item that seems like it might matter to us:

> If you are on Linux and don't have ANKI_WAYLAND set, you may need to install
> libxcb-cursor or Anki will fail to start. Eg on Debian/Ubuntu:

... I dunno, it starts on my machine using X, so I think it's okay?

The update was pretty straightforward, other than ~needing to patch the Cargo.lock file to have only one "percent-encoding" dependency.~ no longer true, that was for 2.1.62, but we've reached 2.1.65 now where the patch is unneeded.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by euank** [comment]
Updated to 2.1.65, since upstream has had more releases, and it was just bumping hashes pretty much.

**Comment by oxij** [comment]
@GrahamcOfBorg build anki

**Review by oxij — APPROVED** [review]
LGTM.

**Comment by mohe2015** [comment]
For checking the checkboxes at e.g. Tools -> Preferences -> Review didn't work which seems to work for the anki-bin version. Unfortunately I can't investigate and I also don't know if this PR causes that. It may run on wayland and maybe thats related to the issue you mentioned.

**Comment by euank** [comment]
Thanks for the heads up @mohe2015! I appreciate the info.

It's broken for me, both on main (X + Anki 2.1.61) and with this PR.

I think that means it's not related to this PR specifically, but rather the broader package.
As such, I'll look into it separately.

I filed an issue for that: https://github.com/NixOS/nixpkgs/issues/248357

**Comment by tjni** [comment]
@euank Thank you for initiating this update. I don't use `anki` and wanted to gauge your confidence in this update.

We merged https://github.com/NixOS/nixpkgs/pull/248866 into staging, which among other things updated `wheel` to 0.41.1. I think `anki` will be broken until https://github.com/ankitects/anki/commit/e20e7f7af12303d70be98cd0f9b36cd2ce9cde87 is picked up, which was only added in version 2.1.62. I could try to cherry-pick that change onto the current version, but I only want to take that route if we cannot update it.

**Comment by mohe2015** [comment]
As the issue I found seems unrelated to this PR I think we can still merge it.

**Comment by euank** [comment]
Thanks for the heads up, @tjni, appreciated.

I'm not sure if we'll need to cherry pick that or not.
Since it's related to wheel packaging, I think it's likely that if the package still builds, there's a decent chance it's fine.

It looks like there's not yet a hydra build for those changes on staging, so checking properly would also require recompiling pretty much the entire world, not just anki.
I think I'll wait on hydra to get something built, see if hydra hits an evaluation error for the current 2.1.61 anki package, and then also see if I can check this update with the staging changes.

**Comment by tjni** [comment]
It took awhile for staging-next to build, and at the time of this writing it's only [finished for aarch64-linux](https://hydra.nixos.org/build/232788270), but there does seem to be an error related to `wheel`:

```
FAILED: /build/source/out/wheels/aqt-2.1.61-py3-none-any.whl 
/build/source/out/rust/debug/runner run /build/source/out/pyenv/bin/python python/write_wheel.py qt/aqt /build/source/out/qt/_aqt /build/source/out/wheels/aqt-2.1.61-py3-none-any.whl
Command failed: 

Traceback (most recent call last):
  File "/build/source/python/write_wheel.py", line 189, in <module>
    write_wheel(
  File "/build/source/python/write_wheel.py", line 80, in write_wheel
    return write_wheel_file(
  File "/build/source/python/write_wheel.py", line 46, in write_wheel_file
    with ReproducibleWheelFile(filename, "w") as wheel:
  File "/nix/store/hzpbm0zkg61smdwpj42jmp2k5bansrdw-python3-3.10.12/lib/python3.10/zipfile.py", line 1312, in __exit__
    self.close()
  File "/nix/store/h8mzz6lkk0v83ck53541fpq7n7ngl1s1-python3.10-wheel-0.41.1/lib/python3.10/site-packages/wheel/wheelfile.py", line 195, in close
    self.writestr(self.record_path, data.getvalue())
  File "/build/source/python/write_wheel.py", line 18, in writestr
    raise ValueError("ZipInfo required")
ValueError: ZipInfo required
Exception ignored in: <function ZipFile.__del__ at 0xfffff7114e50>
Traceback (most recent call last):
  File "/nix/store/hzpbm0zkg61smdwpj42jmp2k5bansrdw-python3-3.10.12/lib/python3.10/zipfile.py", line 1821, in __del__
    self.close()
  File "/nix/store/h8mzz6lkk0v83ck53541fpq7n7ngl1s1-python3.10-wheel-0.41.1/lib/python3.10/site-packages/wheel/wheelfile.py", line 195, in close
    self.writestr(self.record_path, data.getvalue())
  File "/build/source/python/write_wheel.py", line 18, in writestr
    raise ValueError("ZipInfo required")
ValueError: ZipInfo required
```

**Comment by mohe2015** [comment]
Then we should probably merge this sooner than later as this update seems to include that fix and seems to work otherwise too.

**Review by mohe2015 — APPROVED** [review]
LGTM!

**Review by Atemu — APPROVED** [review]
Result of `nixpkgs-review pr 229480` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>anki</li>
    <li>anki.dist</li>
    <li>anki.doc</li>
    <li>anki.man</li>
    <li>mnemosyne</li>
    <li>mnemosyne.dist</li>
  </ul>
</details>

**Comment by euank** [comment]
In addition to the nixpkgs-review above, I've verified that this PR, when merged into current master, gives a working anki binary.

Since the python update broke the older anki that's on master now, I think that lends more importance to merging this as soon as possible.

**Comment by Atemu** [comment]
> In addition to the nixpkgs-review above, I've verified that this PR, when merged into current master, gives a working anki binary.

Note that nixpkgs-review also builds against master by default.

**Comment by euank** [comment]
Yup, I was just trying to say that I also ran the binary too, since nixpkgs-review only verifies the build, not running the application.

**Comment by Atemu** [comment]
Anki builds on Darwin but crashes on startup. Could you set `meta.broken = stdenv.isDarwin`?

**Comment by euank** [comment]
I've marked it as broken on darwin, thanks for testing that!

**Comment by Atemu** [comment]
Btw, 2.1.66 is out but I didn't want to hold this PR off on that.

**Pull request merged**
