### PR TITLE
deepin.deepin-anything: init at 0.0.7

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

Add [deepin-anything](https://github.com/linuxdeepin/deepin-anything), the Deepin file search tool.

> It is dedicated to providing Linux users with a lightning-fast file name search function and offline search.

About packaging deepin for NixOS: https://github.com/NixOS/nixpkgs/issues/59023

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by romildo** [comment]
**TODO:**

- It has a kernel module that has to be correctly installed.
- It has a group/user that has to be setup.
- It installs a dbus service and a systemd unit. A NixOS module may be a good idea.
- It seems to have a plugin system that may need further investigation.

Help is welcome.

**Comment by romildo** [comment]
It is a dependency for `deepin-file-manager`.

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

**Comment by romildo** [comment]
The dbus service, systemd service, desktop module, group and user will be added to the nixos module in a forthcoming PR. It will depend on https://github.com/NixOS/nixpkgs/pull/59943.

**Pull request merged**
