### PR TITLE
moc: always use newest ffmpeg

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/issues/120705

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123486` at 2148b9ef run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>moc</li>
    <li>tests.trivial</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/audio/moc/default.nix:100:5:
```
    |
100 |     license = licenses.gpl2;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

libtool is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/applications/audio/moc/default.nix:48:3:
```
   |
48 |   buildInputs = [ ncurses db popt libtool ]
   |   ^
```
</li>
  </ul>
</details>

**Comment by peterhoeg** [comment]
Instead of pinning it to `ffmpeg_4`, shouldn't we take this opportunity and make it `ffmpeg` so we (possibly) don't have to touch it again?

**Comment by dotlambda** [comment]
> Instead of pinning it to `ffmpeg_4`, shouldn't we take this opportunity and make it `ffmpeg` so we (possibly) don't have to touch it again?

Sure, but then we'd have to remove the `withffmpeg4` argument completely.

**Comment by peterhoeg** [comment]
> Sure, but then we'd have to remove the withffmpeg4 argument completely.

The only reference in nixpkgs to withffmpeg4 is in that file, so I guess it's safe to drop it completely.

**Comment by teto** [comment]
tested, this fixed my build, binary ran fine and patch looks ok. Ty.

**Comment by dotlambda** [comment]
@teto Please consider becoming a maintainer for moc.

**Comment by teto** [comment]
There are already 3 maintainers so I dont see the need ? (apologies to them if I shouldn't have merged).

**Comment by dotlambda** [comment]
They don't seem very avtive.

**Pull request merged**
