### PR TITLE
grpc: 1.62.1 -> 1.66.1

### PR DESCRIPTION
**Pull request by rorosen**
## Description of changes

I messed up in the initial [PR](https://github.com/NixOS/nixpkgs/pull/337898) and caused a mass ping. This is a new try.

This updates grpc and related python packages.

grpc: 1.62.1 -> 1.66.1

Diff: https://github.com/grpc/grpc/compare/v1.62.1...v1.66.1

Changelog: https://github.com/grpc/grpc/releases/tag/v1.66.1

python3Packages.grpcio-status: 1.64.1 -> 1.66.1

python3Packages.grpcio-tools: 1.64.1 -> 1.66.1

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by rorosen** [comment]
ping @risicle @nikstur

**Review by drupol — APPROVED** [review]
Diff LGTM

**Review by drupol — COMMENTED** [review]
Please update the PR title accordingly.

**Comment by risicle** [comment]
I can confirm the two lines mentioned in https://github.com/grpc/grpc/issues/36654#issuecomment-2228569158 added to the toplevel `CMakeLists.txt` fix build on macos 12 x86_64.

Whether it's preferred to use a patch to add them, append them using `cat` or whatever is up you and/or the maintainers.

**Comment by rorosen** [comment]
> I can confirm the two lines mentioned in [grpc/grpc#36654 (comment)](https://github.com/grpc/grpc/issues/36654#issuecomment-2228569158) added to the toplevel `CMakeLists.txt` fix build on macos 12 x86_64.

Build on `x86_64-darwin` fails now due to timeout. Not sure what to do about it...

**Comment by risicle** [comment]
Not because of `grpc` though, because some change to llvm. I generally don't expect ofborg builds to be successful on the staging branch.

**Comment by matdibu** [comment]
you forgot `python312Packages.grpcio`, it's sitting at 1.64.1
this, unfortunately, makes it incompatible with grpcio-tools
so files generated with grpcio-tools 1.66 _cannot_ be used by grpcio 1.64

**Comment by rorosen** [comment]
I'm very sorry to hear that. I'm not aware of what python packages needs to be updated with grpc. I see that there is already a PR (https://github.com/NixOS/nixpkgs/pull/346850) that updates `python312Packages.grpcio`, however, I will open a PR that extends the [comment](https://github.com/NixOS/nixpkgs/blob/6b1ffdb0976ac367aeea173b8e69de62828a4ca7/pkgs/development/libraries/grpc/default.nix#L26) of packages that should always be updated with grpc.

**Comment by matdibu** [comment]
fair enough, it wasn't mentioned there and there aren't any tests that would've caught that

**Pull request merged**
