### PR TITLE
TDE, again!

### LINKED ISSUE #108967: Package request: Trinity Desktop Environment
**Project description**
The Trinity Desktop Environment (TDE) project is a computer desktop environment for Unix-like operating systems with a primary goal of retaining the function and form of traditional desktop computers.
KDE3.5 Fork that still continues to develop.
Very light on resources.
TDE is a complete software desktop environment designed for Unix-like operating systems, intended for computer users preferring a traditional desktop model, and is free/libre software. Born as a fork of KDE 3.5 back in 2010, TDE is now a fully independent project with its own personality and development team, available for various Linux distros, BSD and DilOS.

**Metadata**

* homepage URL: https://trinitydesktop.org/
* source URL: http://mirror.git.trinitydesktop.org/cgit/
* license: "GPL and other licenses" (artwork, I think LGPL)
* platforms: linux, freebsd (,other unix-like)

This will be probably pretty tough to package, but I hope you do it. It is very hard to install on any unsupported distribution, especially for newbies. Nixpkg should probably help a lot by installing it using nix on any distro.

### PR DESCRIPTION
**Pull request by AndersonTorres**
###### Description of changes

My personal  reminder of https://github.com/NixOS/nixpkgs/pull/18715
Will close https://github.com/NixOS/nixpkgs/issues/108967 (or I'll die trying)

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
Logging the progress.

# Then

As I said before, I'm restarting and restudying my previous work.

# 2023-08-07

Some compilation errors were catched.
I silenced them by setting `hardeningDisable`.
I should report this to upstream.

**Comment by AndersonTorres** [comment]
@ofborg build tde.arts

**Comment by AndersonTorres** [comment]
@ofborg build tde.arts

**Comment by AndersonTorres** [comment]
# Then

tqtinterface is the current gatekeeper.

# 2023-11-30

A questionable patch was introduced, and now arts can be built!

**Comment by AndersonTorres** [comment]
I will restart this in Museoa.

**Comment by danwdart** [comment]
The hype is real.

**Pull request closed without merging**
