### PR TITLE
treewide: remove trailing space in description

### PR DESCRIPTION
**Pull request by Sigmanificient**
## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by donovanglover — APPROVED** [review]
LGTM

**Review by infinisil — APPROVED** [review]
Nice!

**Review by tomodachi94 — CHANGES_REQUESTED** [review]
Could you post the code that you used to generate this, and amend your commit description to include the code?

**Comment by Sigmanificient** [comment]
> Could you post the code that you used to generate this, and amend your commit description to include the code?

Hum I used `grep -rP 'description\s+=\s+"[^"]+[ ]";' | cut -d ':' -f 1 | xargs -i nvim {}` which opens a `nvim` instance for each match of the previous regex, then sorted them by hand, avoiding generated packages list

**Comment by tomodachi94** [comment]
> > Could you post the code that you used to generate this, and amend your commit description to include the code?
> 
> Hum I used `grep -rP 'description\s+=\s+"[^"]+[ ]";' | cut -d ':' -f 1 | xargs -i nvim {}` which opens a `nvim` instance for each match of the previous regex, then sorted them by hand, avoiding generated packages list
> 
> Should I amend with that command?

Definitely. I was under the impression that this was a fully automatic change, but I was mistaken :sweat_smile:

**Comment by Sigmanificient** [comment]
Would love to give same treatment with periods, but there is about 3800 of them :sweat_smile:

Should I do a tracking pr and do them block by block just like https://github.com/NixOS/nixpkgs/issues/313981?

**Review by Mindavi — APPROVED** [review]

**Review by jopejoe1 — APPROVED** [review]

**Comment by jopejoe1** [comment]
Thanks!

**Review by afh — CHANGES_REQUESTED** [review]
Please also remove the ending punctuation as recommended in https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#meta-attributes

**Review by tomodachi94 — APPROVED** [review]
Lgtm. I think this can be merged as-is, as you've mentioned cleaning up the punctuation in another PR.

**Review by Aleksanaa — APPROVED** [review]

**Pull request merged**
