### PR TITLE
fetchPypi: move to top level

### PR DESCRIPTION
**Pull request by figsoda**
###### Description of changes

`fetchPypi` does not use python under the hood, and it doesn't make sense to me to have to associate it with a specific version of python whenever it is used, so I moved it to top level similar to `fetchCrate` and `fetchHex`

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
What problem does this solve? And why an `inherit` instead of just moving the import altogether?

**Comment by figsoda** [comment]
> What problem does this solve?

I was struggling to find a good user interface when trying to implement `fetchPypi` support for [nurl](https://github.com/nix-community/nurl), this makes it easier that all the fetchers are top level

> And why an inherit instead of just moving the import altogether?

I didn't want to break anything by accident, I can do that instead if you think that's better

**Comment by jonringer** [comment]
I think for consistency, `pkgs/development/interpreters/python/fetchpypi.nix` should be moved to `pkgs/build-support/fetchpypi/default.nix`. `fetchPypi` should exist at the top-level, then be inherited by `python.pkgs`.

**Comment by figsoda** [comment]
is this good to merge?

**Comment by FRidh** [comment]
Commit message lacks a motivation.

**Comment by figsoda** [comment]
added motivation to the commit message

**Pull request merged**
