### PR TITLE
python3Packages.pydmd: init at 0.3.3

### PR DESCRIPTION
**Pull request by yl3dy**
###### Motivation for this change

PyDMD is a library for Dynamic Mode Decomposition, linear interpolation/extrapolation method useful for multivariate Time Series Analysis.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yl3dy** [comment]
Result of `nixpkgs-review pr 135055` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.pydmd</li>
    <li>python39Packages.pydmd</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 135055` at 3dbd616b run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/e75399a9ffdc8b853628c0fd741cf0ab">python38Packages.pydmd</a></li>
    <li><a href="https://gist.github.com/b33a91d7d24374f00e38590bd3b40cad">python39Packages.pydmd</a></li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by SuperSandro2000** [comment]
@yl3dy please mark it broken on aarch64 and ideally create an upstream issue.

**Comment by yl3dy** [comment]
> @yl3dy please mark it broken on aarch64 and ideally create an upstream issue.

Done. Is there a way to extract logs from @r-rmcgibbo builds? I don't have access to aarch64 hardware, but any error messages would be helpful.

**Comment by SuperSandro2000** [comment]
> > @yl3dy please mark it broken on aarch64 and ideally create an upstream issue.
> 
> Done. Is there a way to extract logs from @r-rmcgibbo builds? I don't have access to aarch64 hardware, but any error messages would be helpful.

You click on the link in the expanded details.

**Comment by yl3dy** [comment]
How could I missed these links? :) Thank you, will try to report it to the upstream, although the error (SVD non-convergence) doesn't look encouraging.

**Pull request merged**
