### PR TITLE
Fix nvidia vulkan steam

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
fix nvidia icd. This is a much less opinionated version of #157907

fixes regressions from: https://github.com/NixOS/nixpkgs/pull/158276

Tests:
- [x] Launched Dota 2 using native vulkan pipeline.

To test:
```
# close existing steam session
NIXPKGS_ALLOW_UNFREE=1 nix run github:jonringer/nixpkgs/fix-nvidia-vulkan-steam#steam
```

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
Most of the rebuilds are from the nvidia driver changes. But people will have to rebuild it anyway.

**Comment by jonringer** [comment]
@tejing1 can you test for any AMD regressions. Otherwise this seems to be an improvement for nvidia users.

**Comment by tejing1** [comment]
> @tejing1 can you test for any AMD regressions. Otherwise this seems to be an improvement for nvidia users.

I'm on nvidia, not amd. Probably got me confused with someone else.

**Comment by jonringer** [comment]
> > @tejing1 can you test for any AMD regressions. Otherwise this seems to be an improvement for nvidia users.
> 
> I'm on nvidia, not amd. Probably got me confused with someone else.

Yea, probably.

**Review by lovesegfault — APPROVED** [review]

**Comment by Artturin** [comment]
I have a amd vega64, I'll test when I'm home

**Review by Artturin — APPROVED** [review]
i don't think i have any vulkan games installed so i just tried launching enter the gungeon and it worked


EDIT currently downloading superliminal which is a vulkan game

EDIT: superliminal launches

**Review by jansol — APPROVED** [review]
Talos Principle (native Linux, Vulkan) works on AMD. DotA 2 segfaults in libtier0.so which seems unrelated to this change.

**Comment by Flakebi** [comment]
Nice! I like that this does not set `VK_ICD_FILENAMES` anymore (and thus allows to overwrite it when starting steam) :)

**Pull request merged**
