### PR TITLE
wxGTK*: Remove abandoned dependencies

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
The many-years abandoned GStreamer 0.10 branch no longer builds so let's remove it. Hopefully nothing used it these days.

GConf has been abandoned for years too and would not work without user running the daemon.

cc https://github.com/NixOS/nixpkgs/issues/39975 https://github.com/NixOS/nixpkgs/pull/93540

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 7c6f434c** [comment]
Erm, this flat-out breaks the build, though? Are there some flags to pass?

**Comment by jtojnar** [comment]
From the error message, it sounds like it revealed an underspecified dependency that was previously masked by propagation:

```
./vidxanm.cpp:23:10: fatal error: X11/Intrinsic.h: No such file or directory
   23 | #include <X11/Intrinsic.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

Did not have time to look into it yet, though.

**Comment by 7c6f434c** [comment]
One of the builds seems to complain explicitly about gstreamer not found, though.

**Comment by jtojnar** [comment]
Seems to build now, after removing a configure flag.

**Comment by jtojnar** [comment]
Let's see what it breaks.

**Pull request merged**
