### PR TITLE
nixos/cinnamon: Unbreak sessionPath option

### PR DESCRIPTION
**Pull request by bobby285271**
It looks like `XDG_CURRENT_DESKTOP` is not set when we run these lines, (and `XDG_CURRENT_DESKTOP` is `X-Cinnamon` not `Cinnamon`)...

Helps https://github.com/NixOS/nixpkgs/issues/276028

~~*Actually I have the impression that `XDG_SESSION_DESKTOP` [is not standardized by freedesktop.org](https://gitlab.gnome.org/GNOME/gtk/-/issues/1224#note_270915), but I am not sure if we actually have better solution here, or probably we just don't check desktops like the GNOME module*~~ We are now actually copy pasting from the GNOME module so this is no longer an issue :clown_face: 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg test cinnamon cinnamon-wayland

**Comment by mkg20001** [comment]
I've created a VM with this patch and gpaste in sessionPath (with cinnamon-wayland) but I don't see anything in "env | grep gpaste"

**Comment by mkg20001** [comment]
Bildschirmfoto vom 2023-12-22 18-35-30
Bildschirmfoto vom 2023-12-22 18-36-43
Bildschirmfoto vom 2023-12-22 18-37-14

**Comment by mkg20001** [comment]
is /etc/gdm/Xsession being ran when using wayland?

**Comment by bobby285271** [comment]
I assume I fixed the GDM + Cinnamon Wayland case this time, please try again.

**Comment by mkg20001** [comment]
Bildschirmfoto vom 2023-12-23 12-14-16

gpaste is now in the environment, but gpaste-reloaded is still not working

I think as this pr only concerns sessionPath it's good for merge, need to debug gpaste a bit further

**Review by mkg20001 — APPROVED** [review]

**Comment by mkg20001** [comment]
Bildschirmfoto vom 2023-12-23 12-20-39

The error in gpaste-reloaded is still the same

**Comment by bobby285271** [comment]
Okay, I don't have ideas this time,

probably we should check if the applet knows these variables, try edit `~/.local/share/cinnamon/applets/gpaste-reloaded@feuerfuchs.eu/applet.js`, and apply the following patch

https://github.com/bobby285271/cinnamon-spices-applets/commit/d0482e11b7d536344aaa0e5e8e924071093df9a0

and restart cinnamon / re-add the applet and see what journal says?

**Comment by mkg20001** [comment]
It is missing

````Dez 23 14:18:52 mkg-framework .cinnamon-wrapp[2112]: JS LOG: [LookingGlass/info] get_search_path: 37
Dez 23 14:18:52 mkg-framework .cinnamon-wrapp[2112]: JS LOG: [LookingGlass/info] [
                                                         '/nix/store/7n2i3wcfavjhc6zdh6n80bqx4sm30ybj-cjs-6.0.0/lib/cjs/girepository-1.0',
                                                         '/nix/store/5k6v8850m7mdpgy4afnbdv4jwnaz934i-muffin-6.0.0/lib/muffin',
                                                         '/nix/store/znvzplxw1w9yq6i9z4vsyxyb146hcgcv-cinnamon-common-6.0.2/lib',
                                                         '/nix/store/lq2ancrkpg1v4bjq4g1q6zqp81iwxpdj-gobject-introspection-wrapped-1.78.1/lib/girepository-1.0',
                                                         '/nix/store/nvxripmvr79xy3qxy9m88nv0jsgp8m58-at-spi2-core-2.50.0/lib/girepository-1.0',
                                                         '/nix/store/r1jah6fzcscqpwlvv6rj5zr2dzf961iy-gdk-pixbuf-2.42.10/lib/girepository-1.0',
                                                         '/nix/store/nkkdfnrkwrfgs3rpm1ln0pc96ff4n4gk-gsettings-desktop-schemas-45.0/lib/girepository-1.0',
                                                         '/nix/store/xsyfa26fpspw4jr2h5l0fsxl811djbdc-harfbuzz-7.3.0/lib/girepository-1.0',
                                                         '/nix/store/xrr20s0ivpdwybs9532b3hckn2j9ls7k-pango-1.51.0/lib/girepository-1.0',
                                                         '/nix/store/b58rkvfpkhw66jj6njc5d5xw6hyywfly-gtk+3-3.24.38/lib/girepository-1.0',
                                                         '/nix/store/z2bfc9frkn6izdps38v0kmsyfxvkmm25-librsvg-2.57.0/lib/girepository-1.0',
                                                         '/nix/store/k624agha4kqgfmzba47aad7i3j48k1vl-gobject-introspection-1.78.1/lib/girepository-1.0',
                                                         '/nix/store/y8l5pn1pgkxs6fncw85b93365k8q0bbb-cinnamon-desktop-6.0.0/lib/girepository-1.0',
                                                         '/nix/store/29ml7jdm0324zkfl04vfvn20zqiiw12l-cinnamon-menus-6.0.0/lib/girepository-1.0',
                                                         '/nix/store/nbni0j1k2f7794182wy3drj4qzdd15y7-libical-3.0.17/lib/girepository-1.0',
                                                         '/nix/store/g4pqgla9r9m25naimxvmw9kvgl9y8jhz-libsoup-3.4.4/lib/girepository-1.0',
                                                         '/nix/store/4z62j430bf29x98pp4r81bld988w1y4q-json-glib-1.8.0/lib/girepository-1.0',
                                                         '/nix/store/xwkrqs5s2y8dq208a7181jc0rxwzrqc8-evolution-data-server-3.50.2/lib/girepository-1.0',
                                                         '/nix/store/pd7013npwaxvm1y87p6pdpm1c6n9rljz-gsound-1.0.3/lib/girepository-1.0',
                                                         '/nix/store/nx91gkbdyrs263v2k1gr0zqbm73fs3kz-graphene-1.10.8/lib/girepository-1.0',
                                                         '/nix/store/y9ns0k3rs1zm16nqxp9n93hs8z8m6bx1-networkmanager-1.44.2/lib/girepository-1.0',
                                                         '/nix/store/xjdgbspp576w02sfdbdy3y19pp64kjin-polkit-123/lib/girepository-1.0',
                                                         '/nix/store/lx47yv9wiqi44l2skm2qnf4dnc7cwlhh-libxklavier-5.4/lib/girepository-1.0',
                                                         '/nix/store/w4y17hjnf6vy15spc7d33pr3w7gicdyv-libgnomekbd-3.28.1/lib/girepository-1.0',
                                                         '/nix/store/m8dqp16r4h8dbllks9dqq7wf2xs0aac5-gstreamer-1.22.7/lib/girepository-1.0',
                                                         '/nix/store/9d5rrl0dysfnhf5xjb4ny7mxai2smah3-caribou-0.4.21/lib/girepository-1.0',
                                                         '/nix/store/43syrh9gs5i154q312dcnndzfzhhyy2d-libgee-0.20.6/lib/girepository-1.0',
                                                         '/nix/store/8jajf6ckmry1a14f14xiyz9a06z1p2rp-keybinder3-0.3.2/lib/girepository-1.0',
                                                         '/nix/store/wqgd6f8nza0a84hrzv03mickgk611qhf-upower-1.90.2/lib/girepository-1.0',
                                                         '/nix/store/v2sm0cax2jnhvlhi1jspx93y4fs6ws9s-xapp-2.8.1/lib/girepository-1.0',
                                                         '/nix/store/w0acrvy2qh7yj7gm907ii83s5hf3gpgk-timezonemap-0.4.5.1/lib/girepository-1.0',
                                                         '/nix/store/wlxn8iqajc0qipf6fp8g7ciwp6fmiy9g-nemo-6.0.1/lib/girepository-1.0',
                                                         '/nix/store/6s28p6ws3s4s0yyzn0n44c1fy5jnrvwl-libnotify-0.8.3/lib/girepository-1.0',
                                                         '/nix/store/cbhx5q20qli7jqk5jdmzaf3hj4v3d8fn-accountsservice-23.13.9/lib/girepository-1.0',
                                                         '/nix/store/v5ffglf02146s6w0fiq0pp60m4q3yp2a-libnma-1.10.6/lib/girepository-1.0',
                                                         '/nix/store/8f98nzyryhy537syyxkqgjcl4libh0aa-gnome-online-accounts-3.48.0/lib/girepository-1.0',
                                                         '/nix/store/k624agha4kqgfmzba47aad7i3j48k1vl-gobject-introspection-1.78.1/lib/girepository-1.0',
                                                     ]
Dez 23 14:18:52 mkg-framework .cinnamon-wrapp[2112]: JS LOG: [LookingGlass/info] LD_LIBRARY_PATH: 1
Dez 23 14:18:52 mkg-framework .cinnamon-wrapp[2112]: JS LOG: [LookingGlass/info] [
                                                         '/etc/sane-libs',
                                                     ]
Dez 23 14:18:52 mkg-framework .cinnamon-wrapp[2112]: JS LOG: [LookingGlass/info] GI_TYPELIB_PATH: 33
Dez 23 14:18:52 mkg-framework .cinnamon-wrapp[2112]: JS LOG: [LookingGlass/info] [
                                                         '/nix/store/lq2ancrkpg1v4bjq4g1q6zqp81iwxpdj-gobject-introspection-wrapped-1.78.1/lib/girepository-1.0',
                                                         '/nix/store/nvxripmvr79xy3qxy9m88nv0jsgp8m58-at-spi2-core-2.50.0/lib/girepository-1.0',
                                                         '/nix/store/r1jah6fzcscqpwlvv6rj5zr2dzf961iy-gdk-pixbuf-2.42.10/lib/girepository-1.0',
                                                         '/nix/store/nkkdfnrkwrfgs3rpm1ln0pc96ff4n4gk-gsettings-desktop-schemas-45.0/lib/girepository-1.0',
                                                         '/nix/store/xsyfa26fpspw4jr2h5l0fsxl811djbdc-harfbuzz-7.3.0/lib/girepository-1.0',
                                                         '/nix/store/xrr20s0ivpdwybs9532b3hckn2j9ls7k-pango-1.51.0/lib/girepository-1.0',
                                                         '/nix/store/b58rkvfpkhw66jj6njc5d5xw6hyywfly-gtk+3-3.24.38/lib/girepository-1.0',
                                                         '/nix/store/z2bfc9frkn6izdps38v0kmsyfxvkmm25-librsvg-2.57.0/lib/girepository-1.0',
                                                         '/nix/store/k624agha4kqgfmzba47aad7i3j48k1vl-gobject-introspection-1.78.1/lib/girepository-1.0',
                                                         '/nix/store/y8l5pn1pgkxs6fncw85b93365k8q0bbb-cinnamon-desktop-6.0.0/lib/girepository-1.0',
                                                         '/nix/store/29ml7jdm0324zkfl04vfvn20zqiiw12l-cinnamon-menus-6.0.0/lib/girepository-1.0',
                                                         '/nix/store/nbni0j1k2f7794182wy3drj4qzdd15y7-libical-3.0.17/lib/girepository-1.0',
                                                         '/nix/store/g4pqgla9r9m25naimxvmw9kvgl9y8jhz-libsoup-3.4.4/lib/girepository-1.0',
                                                         '/nix/store/4z62j430bf29x98pp4r81bld988w1y4q-json-glib-1.8.0/lib/girepository-1.0',
                                                         '/nix/store/xwkrqs5s2y8dq208a7181jc0rxwzrqc8-evolution-data-server-3.50.2/lib/girepository-1.0',
                                                         '/nix/store/pd7013npwaxvm1y87p6pdpm1c6n9rljz-gsound-1.0.3/lib/girepository-1.0',
                                                         '/nix/store/nx91gkbdyrs263v2k1gr0zqbm73fs3kz-graphene-1.10.8/lib/girepository-1.0',
                                                         '/nix/store/y9ns0k3rs1zm16nqxp9n93hs8z8m6bx1-networkmanager-1.44.2/lib/girepository-1.0',
                                                         '/nix/store/xjdgbspp576w02sfdbdy3y19pp64kjin-polkit-123/lib/girepository-1.0',
                                                         '/nix/store/lx47yv9wiqi44l2skm2qnf4dnc7cwlhh-libxklavier-5.4/lib/girepository-1.0',
                                                         '/nix/store/w4y17hjnf6vy15spc7d33pr3w7gicdyv-libgnomekbd-3.28.1/lib/girepository-1.0',
                                                         '/nix/store/m8dqp16r4h8dbllks9dqq7wf2xs0aac5-gstreamer-1.22.7/lib/girepository-1.0',
                                                         '/nix/store/9d5rrl0dysfnhf5xjb4ny7mxai2smah3-caribou-0.4.21/lib/girepository-1.0',
                                                         '/nix/store/43syrh9gs5i154q312dcnndzfzhhyy2d-libgee-0.20.6/lib/girepository-1.0',
                                                         '/nix/store/8jajf6ckmry1a14f14xiyz9a06z1p2rp-keybinder3-0.3.2/lib/girepository-1.0',
                                                         '/nix/store/wqgd6f8nza0a84hrzv03mickgk611qhf-upower-1.90.2/lib/girepository-1.0',
                                                         '/nix/store/v2sm0cax2jnhvlhi1jspx93y4fs6ws9s-xapp-2.8.1/lib/girepository-1.0',
                                                         '/nix/store/w0acrvy2qh7yj7gm907ii83s5hf3gpgk-timezonemap-0.4.5.1/lib/girepository-1.0',
                                                         '/nix/store/wlxn8iqajc0qipf6fp8g7ciwp6fmiy9g-nemo-6.0.1/lib/girepository-1.0',
                                                         '/nix/store/6s28p6ws3s4s0yyzn0n44c1fy5jnrvwl-libnotify-0.8.3/lib/girepository-1.0',
                                                         '/nix/store/cbhx5q20qli7jqk5jdmzaf3hj4v3d8fn-accountsservice-23.13.9/lib/girepository-1.0',
                                                         '/nix/store/v5ffglf02146s6w0fiq0pp60m4q3yp2a-libnma-1.10.6/lib/girepository-1.0',
                                                         '/nix/store/8f98nzyryhy537syyxkqgjcl4libh0aa-gnome-online-accounts-3.48.0/lib/girepository-1.0',
                                                     ]
Dez 23 14:18:52 mkg-framework .cinnamon-wrapp[2112]: JS LOG: [LookingGlass/info] SHELL
Dez 23 14:18:52 mkg-framework .cinnamon-wrapp[2112]: JS LOG: [LookingGlass/info] /run/current-system/sw/bin/bash
Dez 23 14:18:52 mkg-framework .cinnamon-wrapp[2112]: JS LOG: [LookingGlass/info] Loaded applet gpaste-reloaded@feuerfuchs.eu in 96 ms
```

**Comment by bobby285271** [comment]
Okay, I can again reproduce this :upside_down_face: , looks like this is still GDM + Cinnamon Wayland issue 

So https://gitlab.gnome.org/GNOME/gdm/-/issues/770 suggests that probably cinnamon-session needs fix

**Comment by bobby285271** [comment]
Please try this cinnamon-session patch (when applying on nixpkgs, you need to rebase the existing `0001-Use-dbus_glib-instead-of-elogind.patch`)

```diff
From 536f4dd96a444b20c7cf3fa75e7d48b3fb4e1986 Mon Sep 17 00:00:00 2001
From: Bobby Rong <rjl931189261@126.com>
Date: Sat, 23 Dec 2023 23:24:59 +0800
Subject: [PATCH] cinnamon-session: make sure wayland sessions get a login
 shell

Users expect their shell profiles to get sourced at startup, which
doesn't happen with wayland sessions.

This commit brings back that feature, by making the cinnamon-session
wrapper script run a login shell.

ref: https://gitlab.gnome.org/GNOME/gnome-session/-/commit/7e307f8ddb91db5d4051c4c792519a660ba67f35
---
 cinnamon-session/cinnamon-session.in | 16 ++++++++++++++++
 cinnamon-session/meson.build         | 14 +++++++++++++-
 2 files changed, 29 insertions(+), 1 deletion(-)
 create mode 100755 cinnamon-session/cinnamon-session.in

diff --git a/cinnamon-session/cinnamon-session.in b/cinnamon-session/cinnamon-session.in
new file mode 100755
index 0000000..d9d7cb2
--- /dev/null
+++ b/cinnamon-session/cinnamon-session.in
@@ -0,0 +1,16 @@
+#!/bin/sh
+
+if [ "x$XDG_SESSION_TYPE" = "xwayland" ] &&
+   [ "x$XDG_SESSION_CLASS" != "xgreeter" ] &&
+   [  -n "$SHELL" ] &&
+   grep -q "$SHELL" /etc/shells &&
+   ! (echo "$SHELL" | grep -q "false") &&
+   ! (echo "$SHELL" | grep -q "nologin"); then
+  if [ "$1" != '-l' ]; then
+    exec bash -c "exec -l '$SHELL' -c '$0 -l $*'"
+  else
+    shift
+  fi
+fi
+
+exec @libexecdir@/cinnamon-session-binary "$@"
diff --git a/cinnamon-session/meson.build b/cinnamon-session/meson.build
index a244069..b5e8273 100644
--- a/cinnamon-session/meson.build
+++ b/cinnamon-session/meson.build
@@ -53,7 +53,7 @@ cinnamon_session_sources = [
   gdbus_sources,
 ]
 
-executable('cinnamon-session',
+executable('cinnamon-session-binary',
   cinnamon_session_sources,
   dependencies: [
     cinnamon_desktop,
@@ -75,6 +75,18 @@ executable('cinnamon-session',
   ],
   include_directories: [ rootInclude ],
   install: true,
+  install_dir: get_option('libexecdir'),
+)
+
+script_conf = configuration_data()
+script_conf.set('libexecdir', get_option('prefix') / get_option('libexecdir'))
+
+configure_file(
+  input: 'cinnamon-session.in',
+  output: 'cinnamon-session',
+  install: true,
+  install_dir: get_option('bindir'),
+  configuration: script_conf
 )
 
 units = [
-- 
2.42.0
```

**Comment by bobby285271** [comment]
Also sent to https://github.com/linuxmint/cinnamon-session/pull/161 hoping upstream can help

**Comment by mkg20001** [comment]
That did the trick, will PR the patch

**Pull request merged**
