### PR TITLE
Create config builder to handle default config values

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change
This is spun off from #39580. This just adds a config.nix file to handle common config values already in Nixpkgs. We can reuse the mkOption function from NixOS module system.

### CODE REVIEW

**Comment by grahamc** [comment]
Conceptually I like this a lot.

1) I think I'd prefer envVar not be added to mkOption, to make it harder to use in NixOS. what do you and others think?
2) will this break if I add arbitrary other stuff to my configuration?

**Comment by matthewbauer** [comment]
> I think I'd prefer envVar not be added to mkOption, to make it harder to use in NixOS. what do you and others think?

Yeah that is probably a good idea. But where else could we put it? I guess we could make the environment variable the ```default``` value.

**Comment by dtzWill** [comment]
!!! Great, ty!

**Comment by matthewbauer** [comment]
Closing for now. If someone wants to take this up, feel free...

**Pull request closed without merging**
