### PR TITLE
pythonPackages.hypothesis_4: drop

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
This should be safe (numbers-wise) to go into master.

**Review by mweinelt — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 127835` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
20 packages marked as broken and skipped:
</summary>
<ul>
<li>pypi2nix</li>
<li>python38Packages.ansible-collections</li>
<li>python38Packages.dftfit</li>
<li>python38Packages.flower</li>
<li>python38Packages.lammps-cython</li>
<li>python38Packages.optuna</li>
<li>python38Packages.pymatgen-lammps</li>
<li>python38Packages.pymc3</li>
<li>python38Packages.pywick</li>
<li>python38Packages.shap</li>
<li>python38Packages.skein</li>
<li>python38Packages.skorch</li>
<li>python39Packages.ansible-collections</li>
<li>python39Packages.flower</li>
<li>python39Packages.lammps-cython</li>
<li>python39Packages.optuna</li>
<li>python39Packages.pymatgen-lammps</li>
<li>python39Packages.pywick</li>
<li>python39Packages.skein</li>
<li>python39Packages.skorch</li>
</ul>
</details>
<details>

  <summary>41 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>apache-airflow: log was empty</li>
<li>buildbot: log was empty</li>
<li>buildbot-full: log was empty</li>
<li>buildbot-ui: log was empty</li>
<li>home-assistant: log was empty</li>
<li>python38Packages.ansible-kernel: log was empty</li>
<li>python38Packages.ansible-runner: log was empty</li>
<li>python38Packages.baselines: log was empty</li>
<li>python38Packages.flask-appbuilder: log was empty</li>
<li>python38Packages.jupyterlab-git: log was empty</li>
<li>python38Packages.nbdime: log was empty</li>
<li>python38Packages.pyro-ppl: log was empty</li>
<li>python38Packages.pytorch-lightning: log was empty</li>
<li>python38Packages.pytorch-metric-learning: log was empty</li>
<li>python38Packages.rising: log was empty</li>
<li>python38Packages.robotframework-selenium2library: log was empty</li>
<li>python38Packages.robotframework-seleniumlibrary: log was empty</li>
<li>python38Packages.robotframework-tools: log was empty</li>
<li>python38Packages.scikit-tda: log was empty</li>
<li>python38Packages.sopel: log was empty</li>
<li>python38Packages.spacy-transformers: log was empty</li>
<li>python38Packages.tensorboardx: log was empty</li>
<li>python39Packages.ansible-kernel: log was empty</li>
<li>python39Packages.ansible-runner: log was empty</li>
<li>python39Packages.baselines: log was empty</li>
<li>python39Packages.buildbot: log was empty</li>
<li>python39Packages.buildbot-full: log was empty</li>
<li>python39Packages.buildbot-ui: log was empty</li>
<li>python39Packages.flask-appbuilder: log was empty</li>
<li>python39Packages.jupyterlab-git: log was empty</li>
<li>python39Packages.nbdime: log was empty</li>
<li>python39Packages.pyro-ppl: log was empty</li>
<li>python39Packages.pytorch-lightning: log was empty</li>
<li>python39Packages.pytorch-metric-learning: log was empty</li>
<li>python39Packages.rising: log was empty</li>
<li>python39Packages.robotframework-selenium2library: log was empty</li>
<li>python39Packages.robotframework-seleniumlibrary: log was empty</li>
<li>python39Packages.robotframework-tools: log was empty</li>
<li>python39Packages.sopel: log was empty</li>
<li>python39Packages.tensorboardx: log was empty</li>
<li>tts: log was empty</li>
  </ul>
</details>
<details>

  <summary>247 packages failed to build and are new build failures:</summary>
  <ul>
<li>ansible: log was empty</li>
<li>(ansible_2_11: log was empty</li>
<li>,python38Packages.ansible-core): log was empty</li>
<li>ansible-lint: log was empty</li>
<li>(python38Packages.ansible-lint): log was empty</li>
<li>ansible_2_10: log was empty</li>
<li>(python38Packages.ansible-base): log was empty</li>
<li>awscli2: log was empty</li>
<li>backblaze-b2: log was empty</li>
<li>(python38Packages.buildbot): log was empty</li>
<li>(python38Packages.buildbot-full): log was empty</li>
<li>(python38Packages.buildbot-ui): log was empty</li>
<li>checkov: log was empty</li>
<li>conan: log was empty</li>
<li>cq-editor: log was empty</li>
<li>deja-dup: log was empty</li>
<li>duplicity: log was empty</li>
<li>duply: log was empty</li>
<li>evillimiter: log was empty</li>
<li>ffmpeg-normalize: log was empty</li>
<li>gnome-keysign: log was empty</li>
<li>ihaskell: log was empty</li>
<li>jellyfin-mpv-shim: log was empty</li>
<li>keepkey_agent: log was empty</li>
<li>(python38Packages.keepkey_agent): log was empty</li>
<li>ledger_agent: log was empty</li>
<li>(python38Packages.ledger_agent): log was empty</li>
<li>luigi: log was empty</li>
<li>magic-wormhole: log was empty</li>
<li>(python38Packages.magic-wormhole): log was empty</li>
<li>matrix-commander: log was empty</li>
<li>matrix-synapse: log was empty</li>
<li>matrix-synapse-plugins.matrix-synapse-mjolnir-antispam: log was empty</li>
<li>mnemosyne: log was empty</li>
<li>noto-fonts-emoji: log was empty</li>
<li>papis: log was empty</li>
<li>(python38Packages.papis): log was empty</li>
<li>piston-cli: log was empty</li>
<li>plex-mpv-shim: log was empty</li>
<li>powerdns-admin: log was empty</li>
<li>python38Packages.afdko: log was empty</li>
<li>python38Packages.aiosmb: log was empty</li>
<li>python38Packages.angrop: log was empty</li>
<li>python38Packages.b2sdk: log was empty</li>
<li>python38Packages.batchspawner: log was empty</li>
<li>python38Packages.castepxbin: log was empty</li>
<li>python38Packages.catboost: log was empty</li>
<li>python38Packages.celery: log was empty</li>
<li>python38Packages.cirq: log was empty</li>
<li>python38Packages.cirq-core: log was empty</li>
<li>python38Packages.cirq-google: log was empty</li>
<li>python38Packages.datashader: log was empty</li>
<li>python38Packages.dipy: log was empty</li>
<li>python38Packages.django-raster: log was empty</li>
<li>python38Packages.djmail: log was empty</li>
<li>python38Packages.dnachisel: log was empty</li>
<li>python38Packages.dockerspawner: log was empty</li>
<li>python38Packages.ffmpeg-progress-yield: log was empty</li>
<li>python38Packages.genome-collector: log was empty</li>
<li>python38Packages.gradient: log was empty</li>
<li>python38Packages.graphtage: log was empty</li>
<li>python38Packages.gtts: log was empty</li>
<li>python38Packages.holoviews: log was empty</li>
<li>python38Packages.hvplot: log was empty</li>
<li>python38Packages.ignite: log was empty</li>
<li>python38Packages.intake: log was empty</li>
<li>python38Packages.ipyvuetify: log was empty</li>
<li>python38Packages.jupyterhub-ldapauthenticator: log was empty</li>
<li>python38Packages.libagent: log was empty</li>
<li>python38Packages.lsassy: log was empty</li>
<li>python38Packages.mesa: log was empty</li>
<li>python38Packages.modeled: log was empty</li>
<li>python38Packages.moretools: log was empty</li>
<li>python38Packages.moto: log was empty</li>
<li>python38Packages.moviepy: log was empty</li>
<li>python38Packages.nbclient: log was empty</li>
<li>python38Packages.nbsmoke: log was empty</li>
<li>python38Packages.ndjson: log was empty</li>
<li>python38Packages.nltk: log was empty</li>
<li>python38Packages.nototools: log was empty</li>
<li>python38Packages.panel: log was empty</li>
<li>python38Packages.papermill: log was empty</li>
<li>python38Packages.parfive: log was empty</li>
<li>python38Packages.perfplot: log was empty</li>
<li>python38Packages.proglog: log was empty</li>
<li>python38Packages.pymatgen: log was empty</li>
<li>python38Packages.pypiserver: log was empty</li>
<li>python38Packages.pyppeteer: log was empty</li>
<li>python38Packages.pypykatz: log was empty</li>
<li>python38Packages.python-miio: log was empty</li>
<li>python38Packages.python-mpv-jsonipc: log was empty</li>
<li>python38Packages.qiskit: log was empty</li>
<li>python38Packages.qiskit-aer: log was empty</li>
<li>python38Packages.qiskit-aqua: log was empty</li>
<li>python38Packages.qiskit-ibmq-provider: log was empty</li>
<li>python38Packages.qiskit-ignis: log was empty</li>
<li>python38Packages.qiskit-terra: log was empty</li>
<li>python38Packages.sacremoses: log was empty</li>
<li>python38Packages.salmon-mail: log was empty</li>
<li>python38Packages.scancode-toolkit: log was empty</li>
<li>python38Packages.spacy: log was empty</li>
<li>spyder: log was empty</li>
<li>(python38Packages.spyder): log was empty</li>
<li>python38Packages.stytra: log was empty</li>
<li>python38Packages.sumo: log was empty</li>
<li>python38Packages.sunpy: log was empty</li>
<li>python38Packages.textacy: log was empty</li>
<li>python38Packages.thinc: log was empty</li>
<li>python38Packages.toggl-cli: log was empty</li>
<li>python38Packages.tokenizers: log was empty</li>
<li>python38Packages.transformers: log was empty</li>
<li>trezor_agent: log was empty</li>
<li>(python38Packages.trezor_agent): log was empty</li>
<li>python38Packages.tubeup: log was empty</li>
<li>python38Packages.vega: log was empty</li>
<li>python39Packages.afdko: log was empty</li>
<li>python39Packages.aiosmb: log was empty</li>
<li>python39Packages.angrop: log was empty</li>
<li>python39Packages.ansible-base: log was empty</li>
<li>python39Packages.ansible-core: log was empty</li>
<li>python39Packages.ansible-lint: log was empty</li>
<li>python39Packages.b2sdk: log was empty</li>
<li>python39Packages.batchspawner: log was empty</li>
<li>python39Packages.castepxbin: log was empty</li>
<li>python39Packages.catboost: log was empty</li>
<li>python39Packages.celery: log was empty</li>
<li>python39Packages.cirq: log was empty</li>
<li>python39Packages.cirq-core: log was empty</li>
<li>python39Packages.cirq-google: log was empty</li>
<li>python39Packages.cufflinks: log was empty</li>
<li>python39Packages.cve-bin-tool: log was empty</li>
<li>python39Packages.datasets: log was empty</li>
<li>python39Packages.dipy: log was empty</li>
<li>python39Packages.django-raster: log was empty</li>
<li>python39Packages.djmail: log was empty</li>
<li>python39Packages.dnachisel: log was empty</li>
<li>python39Packages.dockerspawner: log was empty</li>
<li>python39Packages.enrich: log was empty</li>
<li>python39Packages.ffmpeg-progress-yield: log was empty</li>
<li>python39Packages.gdown: log was empty</li>
<li>python39Packages.genome-collector: log was empty</li>
<li>python39Packages.gradient: log was empty</li>
<li>python39Packages.gradient-utils: log was empty</li>
<li>python39Packages.graphtage: log was empty</li>
<li>python39Packages.gtts: log was empty</li>
<li>python39Packages.habanero: log was empty</li>
<li>python39Packages.holoviews: log was empty</li>
<li>python39Packages.huggingface-hub: log was empty</li>
<li>python39Packages.hvplot: log was empty</li>
<li>python39Packages.hyperopt: log was empty</li>
<li>python39Packages.ignite: log was empty</li>
<li>python39Packages.intake: log was empty</li>
<li>python39Packages.internetarchive: log was empty</li>
<li>python39Packages.ipydatawidgets: log was empty</li>
<li>python39Packages.ipympl: log was empty</li>
<li>python39Packages.ipyvue: log was empty</li>
<li>python39Packages.ipyvuetify: log was empty</li>
<li>python39Packages.ipywidgets: log was empty</li>
<li>python39Packages.jupyter: log was empty</li>
<li>python39Packages.jupyter-sphinx: log was empty</li>
<li>python39Packages.jupyterhub: log was empty</li>
<li>python39Packages.jupyterhub-ldapauthenticator: log was empty</li>
<li>python39Packages.jupyterhub-systemdspawner: log was empty</li>
<li>python39Packages.jupyterhub-tmpauthenticator: log was empty</li>
<li>python39Packages.kaggle: log was empty</li>
<li>python39Packages.keepkey_agent: log was empty</li>
<li>python39Packages.kmapper: log was empty</li>
<li>python39Packages.ledger_agent: log was empty</li>
<li>python39Packages.libagent: log was empty</li>
<li>python39Packages.lightparam: log was empty</li>
<li>python39Packages.lsassy: log was empty</li>
<li>python39Packages.magic-wormhole: log was empty</li>
<li>python39Packages.mathlibtools: log was empty</li>
<li>python39Packages.mesa: log was empty</li>
<li>python39Packages.modeled: log was empty</li>
<li>python39Packages.monty: log was empty</li>
<li>python39Packages.moretools: log was empty</li>
<li>python39Packages.moto: log was empty</li>
<li>python39Packages.moviepy: log was empty</li>
<li>python39Packages.msldap: log was empty</li>
<li>python39Packages.myfitnesspal: log was empty</li>
<li>python39Packages.nagiosplugin: log was empty</li>
<li>python39Packages.nbclient: log was empty</li>
<li>python39Packages.nbsmoke: log was empty</li>
<li>python39Packages.ndjson: log was empty</li>
<li>python39Packages.nltk: log was empty</li>
<li>python39Packages.nototools: log was empty</li>
<li>python39Packages.oauthenticator: log was empty</li>
<li>python39Packages.panel: log was empty</li>
<li>python39Packages.papermill: log was empty</li>
<li>python39Packages.papis: log was empty</li>
<li>python39Packages.parfive: log was empty</li>
<li>python39Packages.perfplot: log was empty</li>
<li>python39Packages.plexapi: log was empty</li>
<li>python39Packages.proglog: log was empty</li>
<li>python39Packages.pymatgen: log was empty</li>
<li>python39Packages.pypiserver: log was empty</li>
<li>python39Packages.pyppeteer: log was empty</li>
<li>python39Packages.pypykatz: log was empty</li>
<li>python39Packages.python-daemon: log was empty</li>
<li>python39Packages.python-miio: log was empty</li>
<li>python39Packages.python-mpv-jsonipc: log was empty</li>
<li>python39Packages.qiskit: log was empty</li>
<li>python39Packages.qiskit-aer: log was empty</li>
<li>python39Packages.qiskit-aqua: log was empty</li>
<li>python39Packages.qiskit-ibmq-provider: log was empty</li>
<li>python39Packages.qiskit-ignis: log was empty</li>
<li>python39Packages.qiskit-terra: log was empty</li>
<li>python39Packages.rbtools: log was empty</li>
<li>python39Packages.rich: log was empty</li>
<li>python39Packages.sacremoses: log was empty</li>
<li>python39Packages.salmon-mail: log was empty</li>
<li>python39Packages.scancode-toolkit: log was empty</li>
<li>python39Packages.sumo: log was empty</li>
<li>python39Packages.sunpy: log was empty</li>
<li>python39Packages.surepy: log was empty</li>
<li>python39Packages.thinc: log was empty</li>
<li>python39Packages.tokenizers: log was empty</li>
<li>python39Packages.tqdm: log was empty</li>
<li>python39Packages.transformers: log was empty</li>
<li>python39Packages.trezor_agent: log was empty</li>
<li>python39Packages.tubeup: log was empty</li>
<li>python39Packages.twine: log was empty</li>
<li>python39Packages.vega: log was empty</li>
<li>r128gain: log was empty</li>
<li>sacad: log was empty</li>
<li>sage: log was empty</li>
<li>sageWithDoc: log was empty</li>
<li>sourcehut.buildsrht: log was empty</li>
<li>sourcehut.coresrht: log was empty</li>
<li>sourcehut.dispatchsrht: log was empty</li>
<li>sourcehut.gitsrht: log was empty</li>
<li>sourcehut.hgsrht: log was empty</li>
<li>sourcehut.hubsrht: log was empty</li>
<li>sourcehut.listssrht: log was empty</li>
<li>sourcehut.mansrht: log was empty</li>
<li>sourcehut.metasrht: log was empty</li>
<li>sourcehut.pastesrht: log was empty</li>
<li>sourcehut.todosrht: log was empty</li>
<li>spotdl: log was empty</li>
<li>tartube: log was empty</li>
<li>theharvester: log was empty</li>
<li>tinyprog: log was empty</li>
<li>twitter-color-emoji: log was empty</li>
<li>urlwatch: log was empty</li>
<li>weechatScripts.weechat-matrix: log was empty</li>
<li>wlc: log was empty</li>
  </ul>
</details>
<details>
<summary>
190 packages built:
</summary>
<ul>
<li>aiodnsbrute</li>
<li>anki</li>
<li>ankisyncd</li>
<li>arion</li>
<li>aws-sam-cli</li>
<li>check_systemd</li>
<li>cloud-custodian</li>
<li>cloud-init</li>
<li>cyclonedx-python</li>
<li>deeptools</li>
<li>docker-compose</li>
<li>dpt-rp1-py</li>
<li>dt-schema</li>
<li>eliot-tree</li>
<li>evdevremapkeys</li>
<li>flexget</li>
<li>gdown (python38Packages.gdown)</li>
<li>gns3-gui</li>
<li>gns3-server</li>
<li>jupyter</li>
<li>kaggle (python38Packages.kaggle)</li>
<li>ldeep</li>
<li>lieer</li>
<li>manim</li>
<li>mathlibtools (python38Packages.mathlibtools)</li>
<li>mirage-im</li>
<li>nbstripout</li>
<li>nrfutil</li>
<li>ocrmypdf</li>
<li>opsdroid</li>
<li>pantalaimon</li>
<li>past-time</li>
<li>pferd</li>
<li>python38Packages.Nikola</li>
<li>python38Packages.Pweave</li>
<li>python38Packages.altair</li>
<li>python38Packages.apispec</li>
<li>python38Packages.asdf</li>
<li>python38Packages.aws-sam-translator</li>
<li>python38Packages.bravado-core</li>
<li>python38Packages.cfn-lint</li>
<li>python38Packages.chart-studio</li>
<li>python38Packages.connexion</li>
<li>python38Packages.cufflinks</li>
<li>python38Packages.cve-bin-tool</li>
<li>python38Packages.dash</li>
<li>python38Packages.datasets</li>
<li>python38Packages.eliot</li>
<li>python38Packages.enrich</li>
<li>python38Packages.flask-restplus</li>
<li>python38Packages.flask-restx</li>
<li>python38Packages.geoip2</li>
<li>python38Packages.gradient-utils</li>
<li>python38Packages.habanero</li>
<li>python38Packages.huggingface-hub</li>
<li>python38Packages.hyperopt</li>
<li>python38Packages.internetarchive</li>
<li>python38Packages.ipydatawidgets</li>
<li>python38Packages.ipympl</li>
<li>python38Packages.ipyvue</li>
<li>python38Packages.ipywidgets</li>
<li>python38Packages.jsonmerge</li>
<li>python38Packages.jsonschema</li>
<li>python38Packages.jupyter</li>
<li>python38Packages.jupyter-sphinx</li>
<li>python38Packages.jupyter-telemetry</li>
<li>python38Packages.jupyter_server</li>
<li>python38Packages.jupyterhub</li>
<li>python38Packages.jupyterhub-systemdspawner</li>
<li>python38Packages.jupyterhub-tmpauthenticator</li>
<li>python38Packages.jupyterlab</li>
<li>python38Packages.jupyterlab_launcher</li>
<li>python38Packages.jupyterlab_server</li>
<li>python38Packages.jupytext</li>
<li>python38Packages.kmapper</li>
<li>python38Packages.lightparam</li>
<li>python38Packages.livelossplot</li>
<li>python38Packages.matrix-nio</li>
<li>python38Packages.mocket</li>
<li>python38Packages.monty</li>
<li>python38Packages.msldap</li>
<li>python38Packages.myfitnesspal</li>
<li>python38Packages.nagiosplugin</li>
<li>python38Packages.nbclassic</li>
<li>python38Packages.nbconflux</li>
<li>python38Packages.nbconvert</li>
<li>python38Packages.nbformat</li>
<li>python38Packages.nbmerge</li>
<li>python38Packages.nbsphinx</li>
<li>python38Packages.nbval</li>
<li>python38Packages.nix-kernel</li>
<li>python38Packages.notebook</li>
<li>python38Packages.notedown</li>
<li>python38Packages.oauthenticator</li>
<li>python38Packages.onnx</li>
<li>python38Packages.openapi-schema-validator</li>
<li>python38Packages.openapi-spec-validator</li>
<li>python38Packages.phik</li>
<li>python38Packages.plexapi</li>
<li>python38Packages.plotly</li>
<li>python38Packages.pook</li>
<li>python38Packages.prance</li>
<li>python38Packages.pyrsistent</li>
<li>python38Packages.python-daemon</li>
<li>python38Packages.rachiopy</li>
<li>python38Packages.rbtools</li>
<li>python38Packages.rich</li>
<li>python38Packages.robomachine</li>
<li>python38Packages.robotframework</li>
<li>python38Packages.robotframework-databaselibrary</li>
<li>python38Packages.robotframework-requests</li>
<li>python38Packages.robotframework-sshlibrary</li>
<li>python38Packages.robotstatuschecker</li>
<li>python38Packages.robotsuite</li>
<li>python38Packages.sphinxcontrib-openapi</li>
<li>python38Packages.spyder_3</li>
<li>python38Packages.surepy</li>
<li>python38Packages.swagger-spec-validator</li>
<li>python38Packages.tqdm</li>
<li>ttp (python38Packages.ttp)</li>
<li>twine (python38Packages.twine)</li>
<li>python38Packages.warlock</li>
<li>python38Packages.webthing</li>
<li>python38Packages.widgetsnbextension</li>
<li>python38Packages.zetup</li>
<li>python38Packages.zigpy-znp</li>
<li>python39Packages.Nikola</li>
<li>python39Packages.Pweave</li>
<li>python39Packages.altair</li>
<li>python39Packages.apispec</li>
<li>python39Packages.asdf</li>
<li>python39Packages.aws-sam-translator</li>
<li>python39Packages.bravado-core</li>
<li>python39Packages.cfn-lint</li>
<li>python39Packages.chart-studio</li>
<li>python39Packages.connexion</li>
<li>python39Packages.dash</li>
<li>python39Packages.eliot</li>
<li>python39Packages.flask-restplus</li>
<li>python39Packages.flask-restx</li>
<li>python39Packages.geoip2</li>
<li>python39Packages.jsonmerge</li>
<li>python39Packages.jsonschema</li>
<li>python39Packages.jupyter-telemetry</li>
<li>python39Packages.jupyter_server</li>
<li>python39Packages.jupyterlab</li>
<li>python39Packages.jupyterlab_launcher</li>
<li>python39Packages.jupyterlab_server</li>
<li>python39Packages.jupytext</li>
<li>python39Packages.livelossplot</li>
<li>python39Packages.matrix-nio</li>
<li>python39Packages.mocket</li>
<li>python39Packages.nbclassic</li>
<li>python39Packages.nbconflux</li>
<li>python39Packages.nbconvert</li>
<li>python39Packages.nbformat</li>
<li>python39Packages.nbmerge</li>
<li>python39Packages.nbsphinx</li>
<li>python39Packages.nbval</li>
<li>python39Packages.nix-kernel</li>
<li>python39Packages.notebook</li>
<li>python39Packages.notedown</li>
<li>python39Packages.onnx</li>
<li>python39Packages.openapi-schema-validator</li>
<li>python39Packages.openapi-spec-validator</li>
<li>python39Packages.plotly</li>
<li>python39Packages.pook</li>
<li>python39Packages.prance</li>
<li>python39Packages.pyrsistent</li>
<li>python39Packages.rachiopy</li>
<li>python39Packages.robomachine</li>
<li>python39Packages.robotframework</li>
<li>python39Packages.robotframework-databaselibrary</li>
<li>python39Packages.robotframework-requests</li>
<li>python39Packages.robotframework-sshlibrary</li>
<li>python39Packages.robotstatuschecker</li>
<li>python39Packages.robotsuite</li>
<li>python39Packages.sphinxcontrib-openapi</li>
<li>python39Packages.spyder_3</li>
<li>python39Packages.swagger-spec-validator</li>
<li>python39Packages.ttp</li>
<li>python39Packages.warlock</li>
<li>python39Packages.webthing</li>
<li>python39Packages.widgetsnbextension</li>
<li>python39Packages.zetup</li>
<li>python39Packages.zigpy-znp</li>
<li>snakemake</li>
<li>streamlit</li>
<li>tockloader</li>
<li>ytmdl</li>
</ul>
</details>

**Comment by mweinelt** [comment]
> 247 packages failed to build and are new build failures:

I smoke tested like 10 of these and they all built. :disappointed:

**Comment by dotlambda** [comment]
> I smoke tested like 10 of these and they all built.

Same.

**Comment by SuperSandro2000** [comment]
> > 247 packages failed to build and are new build failures:
> 
> I smoke tested like 10 of these and they all built. 😞

Probably network connection issues. There is no easy way right now to only retry those.

**Pull request merged**
