### PR TITLE
oraclejdk7: mark as broken since it is end of life (16.09)

### PR DESCRIPTION
**Pull request by grahamc**
###### Motivation for this change

RE: https://github.com/NixOS/nixpkgs/issues/18856
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
Note that maintenance of the public versions has ended more than a year ago: http://www.oracle.com/technetwork/java/javase/downloads/eol-135779.html

**Comment by grahamc** [comment]
Thanks, @vcunat. Do you know if I did this complete / thoroughly / correctly? That's the only thing I'm unsure of, or I'd have put it straight in.

**Comment by vcunat** [comment]
Therefore, on master we should *remove* it instead of marking it broken, I believe.

**Comment by grahamc** [comment]
Here is the PR to remove it from master: https://github.com/NixOS/nixpkgs/pull/19057

**Comment by vcunat** [comment]
Aha :-) I missed that one somehow.

**Comment by grahamc** [comment]
(PS: I have the same question about if I did it completely / thoroughly  / correctly)

**Comment by vcunat** [comment]
@grahamc: both PRs seem complete and correct to me.

**Pull request merged**
