### PR TITLE
linuxPackages_latest: 5.12.12 -> 5.13

### PR DESCRIPTION
**Pull request by alyssais**
###### Motivation for this change

This was overlooked in #128502.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ymatsiuk — APPROVED** [review]
I was not sure as now we have testing and latest pointing to the same kernel 😉 I haven't found any instructions/policies on how/when to update.
Thanks for the heads up!

**Comment by alyssais** [comment]
The instruction is right below the line you added in all-packages.nix ;)

> ```nix
> # When adding to the list above:
> # - Update linuxPackages_latest to the latest version
> ```

**Comment by Atemu** [comment]
We've established in past discussions that we just update _latest whenever the kernel is stable without regard for OOT module users.

**Comment by jonringer** [comment]
Hmm, was going to to use the _latest bump to also mark related modules as failing.

**Comment by ymatsiuk** [comment]
Got it! Thanks @alyssais and @Atemu for clarifications.

**Comment by andrevmatos** [comment]
This broke `nvidiaPackages.stable` on `latest`. It seems `nvidia 460.67` doesn't build against `linux 5.13` without [these patches](https://forums.developer.nvidia.com/t/460-67-incompatible-with-kernel-5-13-at-the-moment/177543). `nvidiaBeta` does, but is not usable for prime users at the moment because [X crashes when a second screen is attached](https://forums.developer.nvidia.com/t/470-42-01-and-earlier-geforce-940m-optimus-xorg-crash-in-nvidia-drv-so-nvidiaunlock-0x40b654-gnome-session-with-3d-fullscreen-application/181876)

**Comment by Atemu** [comment]
That's Nvidia's problem, not ours. Sorry but that's 100% expected with OOT modules, especially illegal proprietary ones.

Use regular linuxPackages or linuxPackages_5_12 instead.

**Comment by jonringer** [comment]
> This broke `nvidiaPackages.stable` on `latest`. It seems `nvidia 460.67` doesn't build against `linux 5.13` without [these patches](https://forums.developer.nvidia.com/t/460-67-incompatible-with-kernel-5-13-at-the-moment/177543). `nvidiaBeta` does, but is not usable for prime users at the moment because [X crashes when a second screen is attached](https://forums.developer.nvidia.com/t/470-42-01-and-earlier-geforce-940m-optimus-xorg-crash-in-nvidia-drv-so-nvidiaunlock-0x40b654-gnome-session-with-3d-fullscreen-application/181876)

We should probably probably emit a warning around `_latest` stating that you will likely be broken every kernel release, dependening on module usage.

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/issues/122606

**Comment by Atemu** [comment]
It would probably also have helped if the broken kernel modules like the Nvidia one were marked as such as part of this bump.

How are we going to warn about that though? Eval warnings for everybody using _latest and an OOT module?

**Comment by alyssais** [comment]
Warnings should be for definite issues that users can resolve.  A warning that users can't do anything about -- "this _might_ be a problem" -- will teach users to ignore warnings and lead to [alert fatigue](https://en.wikipedia.org/wiki/Alarm_fatigue).

`linux_latest`, by longstanding convention as well as common sense, refers to the latest version of the Linux kernel.  It should be updated as soon as a new kernel is available in Linux.  It is a mechanism that allows users to opt into a bleeding edge kernel version, where they presumably have some compelling need for it.  Obviously, downstreams might not be up to date with it yet, but we shouldn't hold up linux_latest for that.  Similarly, holding it up because we need to do the work of checking every out of tree module, including morally ambiguous ones like NVidea, dilutes the meaning of "latest" and creates a very reasonable justification for a future linux_latest_latest, for people who don't want the actual latest kernel, not whatever version we've arbitrarily decided is good enough for Nixpkgs to pretend is the latest.

**Pull request merged**
