### PR TITLE
krr: 1.7.1 -> 1.11.0

### LINKED ISSUE #327629: Build failure: krr
### Steps To Reproduce

1. build *krr*

### Build log

```
error:
           … while calling the 'derivationStrict' builtin
    
             at /builtin/derivation.nix:9:12: (source not available)
    
           … while evaluating derivation 'home-manager-generation'
             whose name attribute is located at /nix/store/kr5gpvypsqk6h2ahjk7lj40293fyzjbx-source/pkgs/stdenv/generic/make-derivation.nix:334:7
    
           … while evaluating attribute 'buildCommand' of derivation 'home-manager-generation'
    
             at /nix/store/kr5gpvypsqk6h2ahjk7lj40293fyzjbx-source/pkgs/build-support/trivial-builders/default.nix:68:16:
    
               67|         enableParallelBuilding = true;
               68|         inherit buildCommand name;
                 |                ^
               69|         passAsFile = [ "buildCommand" ]
    
           (stack trace truncated; use '--show-trace' to show the full trace)
    
           error: Package ‘python3.12-prometrix-0.1.18-unstable-2024-04-30’ in /nix/store/kr5gpvypsqk6h2ahjk7lj40293fyzjbx-source/pkgs/development/python-modules/prometrix/default.nix:57 is marked as broken, refusing to evaluate.
    
           a) To temporarily allow broken packages, you can use an environment variable
              for a single invocation of the nix tools.
    
                $ export NIXPKGS_ALLOW_BROKEN=1
    
              Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
                    then pass `--impure` in order to allow use of environment variables.
    
           b) For `nixos-rebuild` you can set
             { nixpkgs.config.allowBroken = true; }
           in configuration.nix to override this.
    
           c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
             { allowBroken = true; }
           to ~/.config/nixpkgs/config.nix.
```

### Notify maintainers

@azahi 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-darwin"`
 - host os: `Darwin 23.5.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by azahi**
## Description of changes

- **python3.prometrix: 0.1.18-unstable-2024-04-30 -> 0.1.18**
- **krr: 1.7.1 -> 1.11.0**

Fixes: #327629

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by azahi** [comment]
I can't really test this out right now. @dminca do you have a cluster to test this on?

**Comment by dminca** [comment]
> I can't really test this out right now. @dminca do you have a cluster to test this on?

hmm good question, I don't have a cluster unfortunately

**Comment by azahi** [comment]
Sigh, execution and tests are broken because krr's `typer` dependency is waaay too old to simply ignore and use with what Nixpkgs provides. I tried to override it, but there was way too much stuff to override (a commit to the latest relevant version is 4+ years old). Upstream needs to update their stuff... 

I'm closing this PR since it doesn't resolve the problem. Python packaging in Nixpkgs is PITA.

**Comment by dminca** [comment]
I'm sorry Azat 🫂

**Pull request closed without merging**
