### PR TITLE
cloud-init module: adopt the settings format

### PR DESCRIPTION
**Pull request by zimbatm**
This makes it easier to for example set `datasource_list = [ "Vultr" ];`
so that cloud-init doesn't scan trough all of the datasources when you
know on which target the system is going to be deployed.

Previously, one had to copy-paste the default config and adapt it.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kevinmehall** [comment]
@zimbatm It seems like the default settings are not being applied with this. `/etc/cloud/cloud.cfg` just contains `{}`.

If I explicitly set options under `services.cloud-init.settings` those do make it into the file, but the defaults that you converted into settings format here are not being included:
https://github.com/NixOS/nixpkgs/blob/a3fe093364f627e621deb52e71071e59b14763a4/nixos/modules/services/system/cloud-init.nix#L94-L145

This is causing a boot delay and the message `Failed to start Wait for Network to be Configured.` with `services.cloud-init.network.enable` because it's not using `networkd` to configure networking.

**Comment by kevinmehall** [comment]
Adding these to my configuration with the new settings mechanism is a workaround for the network issue:
```
services.cloud-init.settings = {
    system_info.network.renderers = ["networkd"];
    system_info.network.activators = ["networkd"];
};
```

Note that the (currently-ignored) defaults only include `renderers` not `activators` -- the latter should maybe be added as a default to make it use `networkd` for DHCP, which might also make https://github.com/NixOS/nixpkgs/pull/226216 unnecessary.

**Comment by zimbatm** [comment]
Thanks, https://github.com/NixOS/nixpkgs/pull/231867 fixes this.

**Comment by jfroche** [comment]
> Note that the (currently-ignored) defaults only include `renderers` not `activators` -- the latter should maybe be added as a default to make it use `networkd` for DHCP, which might also make #226216 unnecessary.

I don't think #226216 is unnecessary as cloud-init (on the first boot) is attempting to configure an ephemeral ipv4 address on the first interface before trying to fetch the provider network configuration. The dhcp request made by udhcp (and previously dhclient) will still be required to setup that ephemeral/bootstrap networking (see [EphemeralDHCPv4](https://github.com/canonical/cloud-init/blob/main/cloudinit/net/ephemeral.py#L313) used by many datasource to bootstrap the networking).

**Pull request merged**
