### PR TITLE
Python packages set: major updates

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by FRidh** [comment]
@jonringer up for another big PR? Some changes likely need to be reverted.

**Comment by jonringer** [comment]
sure.... I just want to say you're a mad man

**Comment by jonringer** [comment]
I'll spend some time after i get home from work

**Comment by FRidh** [comment]
Haha yes these types of upgrades are crazy. To be honest, I think the next
time for such an update will be like 1 month before branchoff, so it's not
that often.

**Comment by jonringer** [comment]
Do you mind if I force push to the branch, if i rebase on top of master?

**Comment by FRidh** [comment]
Force push is ok, but don't rebase on top of master. We need to merge
master into staging-next and staging-next into staging and then rebase.

**Comment by jonringer** [comment]
I guess that makes sense, my major use-case was to revert one of the bumps which applied itself to a frozen version

**Comment by jonringer** [comment]
I'm just going to start disabling failing python2 packages, don't see much of a reason to continually freeze

**Comment by jonringer** [comment]
rebased on top of staging, fixed some packages

**Comment by jonringer** [comment]
oh lol, i was about to push some.. oh well, it was like 3 packages... I'll just make a PR

**Comment by FRidh** [comment]
Ahh, yeah, it seemed more than good enough to me. Thanks for the fixes! The changes are now in staging next, so you can  open a PR against that branch if they are fixes.

**Comment by FRidh** [comment]
@flokli a best effort is made, but I am not going to check 400+ updates.

**Comment by jonringer** [comment]
I did revert 3-4 commits which bumped frozen versions, but it takes a while to investigate, and very time consuming.

Plus each commit drop was a force push which is awkward when 2 people are using a single branch.

**Comment by ahiaao** [comment]
@FRidh This PR incorrectly upgraded cerberus11 to version 1.3.1 instead of remaining at 1.1 like the package name suggests.

**Comment by FRidh** [comment]
@ahiaao fixed with 9c52da0e0c7bec320931af4e704a62e2d7c9215f and 34715da5dc3fcbfe031bc7b5a8480b55ee60c588

**Comment by veprbl** [comment]
This broke ipykernel: #76197

**Pull request merged**
