### PR TITLE
Update Monero for upcoming hard fork (backports #48301)

### PR DESCRIPTION
**Pull request by samueldr**
Things done:

 * Built using sandbox
 * Cherry-picked using `-x`.

Backports #48301
This also cherry-picks #48634 since there apparently was an (upstream) issue with the 0.13.0.2 releases :/.
And finally, backports the previous updates, as there was a change (see comments).

cc @rnhmjoj

### CODE REVIEW

**Comment by samueldr** [comment]
@rnhmjoj ??!? I'm thinking I'm missing something obvious or something weird is going on.

(Disregard the current eval failure of ofborg. It's unrelated.)

`monero` not `monero-gui` this time seems to fail; but it did build **on master** locally *and* on ofborg!

```
 $ exec env -i NIXPKGS_ALLOW_UNFREE=1 nix-build -A monero
these derivations will be built:
  /nix/store/r4ssxh5p7zmv6ld1n8jm5q1f62zmvday-source.drv
  /nix/store/znrxg5lkgvfbnj39hyfpxc2iblc2j864-monero-0.13.0.3.drv
building '/nix/store/r4ssxh5p7zmv6ld1n8jm5q1f62zmvday-source.drv'...

trying https://github.com/monero-project/monero/archive/v0.13.0.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   132    0   132    0     0    578      0 --:--:-- --:--:-- --:--:--   578
100 8412k    0 8412k    0     0  3195k      0 --:--:--  0:00:02 --:--:-- 3518k
unpacking source archive /build/v0.13.0.3.tar.gz
fixed-output derivation produced path '/nix/store/bwacxn0dswn1xqy1pkqnynfrlwlqjas2-source' with sha256 hash '18hlnq5hp3m91r7w7kx2bpqmr18nj8cshba6psrpxrvklgaxjzs0' instead of the expected hash '03qx8y74zxnmabdi5r3a274pp8zvm3xhkdwi1xf5sb40vf4sfmwb'
cannot build derivation '/nix/store/znrxg5lkgvfbnj39hyfpxc2iblc2j864-monero-0.13.0.3.drv': 1 dependencies couldn't be built
error: build of '/nix/store/znrxg5lkgvfbnj39hyfpxc2iblc2j864-monero-0.13.0.3.drv' failed
Command exited with non-zero status 1
```

Any idea of anything I could have overlooked?

Should we now add both the friggin' commit IDs AND the tag names on `fetchFromGitHub` to reduce doubts? Did `fetchFromGitHub` change on master (or on stable)?

(Again, not directed at anyone in particular, I just don't know what I'm looking at here.)

**Comment by rnhmjoj** [comment]
monero need fetchgit because some dep is in a submodule IIRC. here it's using fetchFromGithub.

**Comment by samueldr** [comment]
Ah right, if I had looked and backported *all* commits instead of resolving the merge conflict I would have seen `fetchgit`. Thanks, I'll do that later.

**Comment by samueldr** [comment]
As ofborg might have issues right now with release-18.09 I'm attaching my own logs

 * https://gist.github.com/samueldr/db4b79b7952080341e1421fffbb90c0e

@GrahamcOfBorg build monero-gui xmr-stak

**Comment by samueldr** [comment]
@GrahamcOfBorg eval

**Review by rnhmjoj — APPROVED** [review]
I tried it and seems to work.

**Pull request merged**
