### PR TITLE
Kubernetes: fix kubelet service unit configuration

### PR DESCRIPTION
**Pull request by azazel75**
Refactored systemd unit to better handle optional attrs and their
interaction with "\"

###### Motivation for this change

I've got a startup failure of the kubelet when trying master code

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
---

### CODE REVIEW

**Comment by azazel75** [comment]
cc @srhb @johanot @calbrecht

**Comment by azazel75** [comment]
Done the same for apiserver

**Comment by srhb** [comment]
I've filed https://github.com/systemd/systemd/issues/12883 since this is global breakage for us.

**Comment by azazel75** [comment]
Thanks, @srhb I didn't realize it was a global issue... also, it's good to know that someone reads things like this ;-)

**Comment by globin** [comment]
Can we close this as it seems to be included in our systemd version?

**Comment by azazel75** [comment]
Is it included? I don't think so, but it seems that the issue has been resolved at the systemd level

**Comment by srhb** [comment]
@azazel75 It is: https://github.com/NixOS/systemd/commit/bcbaa8da9c6350cec98d888b0af8b0f6ec1ef2e1

**Pull request closed without merging**
