### PR TITLE
sudo: add darwin support

### PR DESCRIPTION
**Pull request by wegank**
###### Description of changes

This should allow pmbootstrap to build on x86_64-darwin.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by delroth** [comment]
I'm not particularly opposed to this change, but in general having a direct dependency on sudo is likely a packaging bug more than anything. The `sudo` binary installed in the Nix store is not SUID and thus not really useful, it only becomes useful via NixOS suid wrappers.

So I'd be in favor of dropping the problematic dependency instead (or additionally). What do you think?

**Comment by delroth** [comment]
cc @onny pmbootstrap maintainer

**Comment by wegank** [comment]
It looks like pmbootstrap tests really require sudo, otherwise:

```
RuntimeError: Can't find sudo or doas required to run pmbootstrap. Please install sudo, doas, or specify your own sudo with the PMB_SUDO environmental variable.
```

I actually doubt pmbootstrap is functional on Darwin, as it relies heavily on chroot IMHO. If it does work well, maybe it would be okay to add something like that about Darwin?

```
preCheck = lib.optionalString stdenv.isDarwin ''
  export PMB_SUDO=/usr/bin/sudo
''
```

**Comment by wegank** [comment]
Closing in favor of #204182.

**Pull request closed without merging**
