### PR TITLE
gnome.mutter: 40.1 -> 40.4

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change

New version released.
Changelog:
https://gitlab.gnome.org/GNOME/mutter/-/blob/2bfef7dbdc6f432a5433c93c1fcdbf00099367c8/NEWS#L1-48

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by dasj19 — APPROVED** [review]
LGTM

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 135393` at f6b87124 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>17 packages built successfully:</summary>
  <ul>
    <li>adapta-gtk-theme</li>
    <li>chrome-gnome-shell</li>
    <li>gnome.gnome-control-center (gnome.gnome_control_center)</li>
    <li>gnome.gnome-session (gnome.gnome_session)</li>
    <li>gnome.gnome-shell (gnome.gnome_shell)</li>
    <li>gnome.gnome-terminal (gnome.gnome_terminal)</li>
    <li>gnome.gnome-tweaks (gnome.gnome-tweak-tool)</li>
    <li>gnome.gpaste</li>
    <li>gnome.mutter</li>
    <li>gnome.pomodoro</li>
    <li>gnomeExtensions.easyScreenCast</li>
    <li>gnomeExtensions.gsconnect</li>
    <li>pantheon.elementary-session-settings</li>
    <li>phoc</li>
    <li>phosh</li>
    <li>vimix-gtk-themes</li>
    <li>whitesur-gtk-theme</li>
  </ul>
</details>

**Review by jtojnar — COMMENTED** [review]
[Changes](https://ftp.gnome.org/pub/GNOME/sources/mutter/40/mutter-40.2.news) look okay:

> 40.2
> ====
> * Fix mouse position in remote desktop with fractional scaling [Pascal; <a href="https://gitlab.gnome.org/GNOME/mutter/merge_requests/1867">!1867</a>]
> * Fix fd leak [Carlos; <a href="https://gitlab.gnome.org/GNOME/mutter/merge_requests/1875">!1875</a>]
> * Disable KMS modifiers on radeon driver [Carlos; <a href="https://gitlab.gnome.org/GNOME/mutter/merge_requests/1872">!1872</a>]
> * Fix adding virtual monitor to physical session [Jonas; <a href="https://gitlab.gnome.org/GNOME/mutter/merge_requests/1891">!1891</a>]
> * Unbreak press-drag-release to pop up and select right click menus
>   [Carlos; <a href="https://gitlab.gnome.org/GNOME/mutter/merge_requests/1885">!1885</a>]
> * Fix VKMS detection [Jonas; <a href="https://gitlab.gnome.org/GNOME/mutter/merge_requests/1892">!1892</a>]
> * Misc. bug fixes [Jonas, Daniel, Florian; <a href="https://gitlab.gnome.org/GNOME/mutter/merge_requests/1876">!1876</a>, <a href="https://gitlab.gnome.org/GNOME/mutter/merge_requests/1873">!1873</a>, <a href="https://gitlab.gnome.org/GNOME/mutter/merge_requests/1890">!1890</a>, <a href="https://gitlab.gnome.org/GNOME/mutter/merge_requests/1884">!1884</a>]
> 
> Contributors:
>   Jonas Ådahl, Carlos Garnacho, Florian Müllner, Pascal Nowack, Daniel van Vugt
> 
> Translators:
>   Pawan Chitrakar [ne], Charles Monzat [fr]
> 

[Changes](https://ftp.gnome.org/pub/GNOME/sources/mutter/40/mutter-40.2.1.news) look okay:

> 40.2.1
> ======
> * Fixed crash [Jonas; <a href="https://gitlab.gnome.org/GNOME/mutter/merge_requests/1895">!1895</a>]
> 
> Contributors:
>   Jonas Ådahl
> 

[Changes](https://ftp.gnome.org/pub/GNOME/sources/mutter/40/mutter-40.3.news) look okay:

> 40.3
> ====
> * Fix area screencasts when window is unredirected [Michel; <a href="https://gitlab.gnome.org/GNOME/mutter/issues/1707">#1707</a>]
> * Fix mapping tablet to monitor [Christoph; <a href="https://gitlab.gnome.org/GNOME/mutter/issues/1712">#1712</a>]
> * Fixed crash [Jonas; <a href="https://gitlab.gnome.org/GNOME/mutter/merge_requests/1910">!1910</a>]
> * Misc. bug fixes [Jonas, Carlos; <a href="https://gitlab.gnome.org/GNOME/mutter/merge_requests/1911">!1911</a>, <a href="https://gitlab.gnome.org/GNOME/mutter/merge_requests/1920">!1920</a>]
> 
> Contributors:
>   Jonas Ådahl, Michel Dänzer, Carlos Garnacho, Christoph Trassl
> 
> Translators:
>   Dušan Kazik [sk], Chao-Hsiung Liao [zh_TW]
> 

[Changes](https://ftp.gnome.org/pub/GNOME/sources/mutter/40/mutter-40.4.news) look okay:

> 40.4
> ====
> * Don't require a newly attached buffer to apply state [Christian, Jonas; <a href="https://gitlab.gnome.org/GNOME/mutter/merge_requests/1795">!1795</a>]
> * Fix upside-down Xshape surface with EGLstream [Robert; <a href="https://gitlab.gnome.org/GNOME/mutter/merge_requests/1937">!1937</a>]
> * Misc. bug fixes and cleanups [Jonas; <a href="https://gitlab.gnome.org/GNOME/mutter/merge_requests/1942">!1942</a>, <a href="https://gitlab.gnome.org/GNOME/mutter/merge_requests/1912">!1912</a>]
> 
> Contributors:
>   Robert Mader, Christian Rauch, Jonas Ådahl
> 
> Translators:
>   Marek Černocký [cs]

**Comment by jtojnar** [comment]
Thanks.

**Pull request merged**
