### PR TITLE
treewide: automatically md-convert option descriptions

### PR DESCRIPTION
**Pull request by pennae**
###### Description of changes

alternative to #183105, this time the conversion was done automatically with a rather small program.

the conversion procedure is simple:

 - find all things that look like options, ie calls to either `mkOption` or `lib.mkOption` that take an attrset. remember the attrset as the option
 -  for all options, find a `description` attribute who's value is not a call to `mdDoc` or `lib.mdDoc`
 -  textually convert the entire value of the attribute to MD with a few simple regexes (the set from mdize-module.sh)
 - if the change produced a change in the manual output, discard
 - if the change kept the manual unchanged, add some text to the description to make sure we've actually found an option. if the manual changes this time, keep the converted description
    
this procedure converts 80% of nixos options to markdown. around 2000 options remain to be inspected, but most of those fail the "does not change the manual output check": currently the MD conversion process does not faithfully convert docbook tags like \<code\> and \<package\>, so any option using such tags will not be converted at all.

conversion were done using https://github.com/pennae/nix-doc-munge, which has much the same interface as `mdize-module.sh`: pass it a bunch of module paths as arguments, and it'll convert stuff. it probably makes most sense to review the tool instead of the patch, because the patch is gigantic (10k lines in 1052 files changed!)

### files dropped due to conflicts

- nixos/modules/services/continuous-integration/gitlab-runner.nix
- nixos/modules/services/x11/window-managers/fvwm.nix

### CODE REVIEW

**Review by jtojnar — APPROVED** [review]
Quickly paged through the whole diff and did not notice anything amiss. The other two commits look okay too.

**Comment by pennae** [comment]
considering that ths is a mechanical change that verifiably doesn't break anything we're inclined to merge this in a few days. would also stop merge conflicts appearing.

**Review by Mindavi — APPROVED** [review]
Took a quick (non-comprehensive) look at the tool, looks ok to me.

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 183491` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>

**Comment by ncfavier** [comment]
https://github.com/NixOS/nixpkgs/commit/52b0ad17e3727fe0c3ca028787128ede5fb86352 causes some duplicated prefixes in option declaration locations, see https://github.com/NixOS/nixos-search/issues/513

**Comment by ncfavier** [comment]
I'm going to hazard a guess that this is because we now call `mergeJSON.py` twice on some options, and that script prepends `nixos/modules/`.

**Comment by ncfavier** [comment]
```
# fix up declaration paths in lazy options, since we don't eval them from a full nixpkgs dir
```
Can we avoid this ugliness, by evaluating the lazy options from the full nixpkgs dir? (not even sure what that means)

**Comment by pennae** [comment]
> I'm going to hazard a guess that this is because we now call mergeJSON.py twice on some options, and that script prepends nixos/modules/.

ugh, didn't think to check that. this pr calls mergeJSON twice because it was so slow, after https://github.com/NixOS/nixpkgs/pull/185056 we can do away with that check again. we'll amend that PR soonish.

> Can we avoid this ugliness, by evaluating the lazy options from the full nixpkgs dir? (not even sure what that means)

only at great cost, the full nixpkgs dir is ten times the sizes of the nixos subdir. we really don't want to copy all that stuff if we don't have to.

**Comment by ncfavier** [comment]
Why do we have to copy anything again?

**Comment by pennae** [comment]
we somehow have to get the modules into a derivation to avoid evaluating the entire options tree for each system build, and that requires them being in the store. there was an attempt to at least reuse a flake store path, but that caused dependent packages to have different hashes depending on how they were built (https://github.com/NixOS/nixpkgs/pull/153594#issuecomment-1020530593).

**Pull request merged**
