### PR TITLE
arrayfire: add

### PR DESCRIPTION
**Pull request by chessai**
###### Motivation for this change
Add the missing arrayfire library to nixpkgs.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

### CODE REVIEW

**Comment by chessai** [comment]
Not tested on MacOS or other linux distributions.

No nixos tests available for this package.

No packages in nixpkgs depend on the previously-unavailable arrayfire nixpkg, so no packages should be affected.

There are no binary files, but @dmjio has confirmed that he can link against this in his haskell bindings and run the code.

There can be no change to the closure size of a new package.

All documentation is new.

**Comment by chessai** [comment]
not sure why the first CI failure occurred. i just ran

`nix-build -A arrayfire --arg config '{ allowUnfree = true; }' --arg overlays '[]'` and it found pkgs.mesa_noglu just fine.

**Comment by chessai** [comment]
ok, disabled the alias. wasn't aware of that.

**Comment by chessai** [comment]
added support for darwin. @dmjio has confirmed that this works for him, with the caveat that you cant get cudatoolkit so arrayfire will offload to cpu.

**Review by cleverca22 — APPROVED** [review]

**Comment by chessai** [comment]
thanks!

**Comment by dmjio** [comment]
Thanks @cleverca22 @chessai

**Pull request merged**
