### PR TITLE
vscode-extensions.mikestead.dotenv: Init at 1.0.1

### PR DESCRIPTION
**Pull request by andyrichardson**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by andyrichardson** [comment]
@SuperSandro2000 no pressure/rush! 

Wanted to ping you as these changes are based off of your suggestions in previous PRs 🙏

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 no pressure/rush!
> 
> Wanted to ping you as these changes are based off of your suggestions in previous PRs 🙏

If a PR sleeps through feel free to ping me as long as you don't do it on an hourly basis I have no problem with that.

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by andyrichardson** [comment]
> If a PR slips through feel free to ping me as long as you don't do it on an hourly basis I have no problem with that

Really appreciate it - you rock 🙏

**Pull request merged**
