### PR TITLE
ndi: 5.6.0 -> 5.6.1

### PR DESCRIPTION
**Pull request by LostAttractor**
## Description of changes
bump version

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by JohnRTitor — APPROVED** [review]
Result of `nixpkgs-review pr 305112` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>ndi</li>
    <li>obs-studio-plugins.obs-ndi</li>
  </ul>
</details>

EDIT: **approved** by mistake. 
Looks like these packages are failing to build.

**Comment by pSub** [comment]
@LostAttractor there are build failures, see the comment above.

**Comment by JohnRTitor** [comment]
@ofborg build ndi
@ofborg build obs-studio-plugins.obs-ndi

**Comment by LostAttractor** [comment]
> Result of `nixpkgs-review pr 305112` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 2 packages failed to build:
> 
>     * ndi
> 
>     * obs-studio-plugins.obs-ndi
> 
> 
> EDIT: **approved** by mistake. Looks like these packages are failing to build.

image
NDI is not an open source software, you need to get source tarball manually.
You can get download link from [here](https://ndi.video/ndi-sdk/) and add the tarball to nix by:
```bash
nix-prefetch-url https://link.to/Install_NDI_SDK_v5_Linux.tar.gz
```
Then the `nixpkgs-review` can build NDI successful as well as packages depend on it.

**Comment by JohnRTitor** [comment]
Can we not get it via `fetchzip` or `fetchurl`?

I am still a bit confused as to how Nix builds it in the CI. There doesn't seem to a fetching mechanism in default.nix.

**Comment by LostAttractor** [comment]
> Can we not get it via `fetchzip` or `fetchurl`?

No. Its copyright requirements do not permit redistribution. Providing a binary cache is also an act of redistribution.
There are quite a few similar packages, such as `wechat-uos`.

**Comment by JohnRTitor** [comment]
So basically this is *an installer* for NDI package provided we give it the tarball.

**Comment by jshcmpbll** [comment]
> > Can we not get it via `fetchzip` or `fetchurl`?
> 
> No. Its copyright requirements do not permit redistribution. Providing a binary cache is also an act of redistribution. There are quite a few similar nix packages, such as `wechat-uos`.
> 
> > I am still a bit confused as to how Nix builds it in the CI. There doesn't seem to a fetching mechanism in default.nix.
> 
> Nix's CI can't build it.

Ah, thanks for the context. I had opened [this](https://github.com/NixOS/nixpkgs/pull/298259) a little while ago but that unfortunate we can't redistribute it.

Also did you have issues with that library not linking to anything?

**Comment by jshcmpbll** [comment]
Based on the information winter on discourse provided it sounds like due to the license set in the derivation, `unfree`, it isn't actually cached and redistributed anyways. Hopefully that means we can move forward on [#298259](https://github.com/NixOS/nixpkgs/pull/298259)

**Comment by JohnRTitor** [comment]
Ok closing this, since superseded by #298259

**Pull request closed without merging**
