### PR TITLE
playwright.browsers: fix build

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bbigras** [comment]
I got:

```
error: undefined variable 'browsers'

       at /nix/store/jsib33haz5j61lr0z7sf9d0jzby8j36r-source/pkgs/development/python-modules/playwright/default.nix:214:14:

          213|
          214|     tests = {
             |              ^
          215|       inherit driver browsers;
(use '--show-trace' to show detailed location information)
```

**Comment by DGollings** [comment]
In case you missed it:
https://github.com/SuperSandro2000/nixpkgs/commit/db5d6bc4d6f16d1ed98e6e8f14e8ea8de9c5d66a#r87527876

**Comment by bbigras** [comment]
hehe, I was wondering :)

**Comment by DGollings** [comment]
it appears to be compiling Firefox right now (your new commit), so I'm hopeful. Will update in a moment

**Comment by DGollings** [comment]
Did I accidentally install Gentoo? I'm starting to appreciate the cache more, still waiting

**Comment by DGollings** [comment]
41 minutes, on a 16 core CPU. Anyway, it compiled/built successfully @SuperSandro2000

**Comment by bbigras** [comment]
```nix
mkShell {
  buildInputs = [
    playwright
  ];

  PLAYWRIGHT_BROWSERS_PATH="${playwright.browsers}";
}
```

It works with chromium :tada: .

But with firefox I get:

```
❯ playwright open https://google.ca -b ff
[: Executable doesn't exist at /nix/store/rrpjbmgnklcfma57yv7iwjccrl4sxsgi-playwright-browsers/firefox-1357/firefox/firefox
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
```

```
❯ exa -T /nix/store/rrpjbmgnklcfma57yv7iwjccrl4sxsgi-playwright-browsers/firefox-1357
/nix/store/rrpjbmgnklcfma57yv7iwjccrl4sxsgi-playwright-browsers/firefox-1357
└── firefox -> /nix/store/4m99m1z9zmw7l9cmh17i3b7vj0q3yxnp-firefox-106.0.1/bin/firefox
```

**Comment by SuperSandro2000** [comment]
Can you try #197291

**Pull request merged**
