### PR TITLE
python3Packages.python-gitlab: 1.15.0 -> 2.2.0

### PR DESCRIPTION
**Pull request by das-g**
###### Motivation for this change

upstream releases (see [PyPI](https://pypi.org/project/python-gitlab/2.2.0/#history) for SHA256 hashes & [GitHub](https://github.com/python-gitlab/python-gitlab/releases) for release notes)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
----
Result of `nixpkgs-review pr 86269` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
<br>- python37Packages.python-gitlab
<br>- python38Packages.python-gitlab
</details>

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
Please follow [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md) and [manual#submitting-changes-making-patches ](https://nixos.org/nixpkgs/manual/#submitting-changes-making-patches) and squash the commits.

This is a lot of small bumps, I would just compile into one
```
python3Packages.python-gitlab: 1.15.0 -> 2.2.0
```

**Comment by das-g** [comment]
> Please follow [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md) [...]

What part of [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md) did I not follow? (Honest question. I just read it again and can't determine where I went afoul of it.)

>[...] and [manual#submitting-changes-making-patches ](https://nixos.org/nixpkgs/manual/#submitting-changes-making-patches) and squash the commits.
> 
> This is a lot of small bumps, I would just compile into one
> 
> ```
> python3Packages.python-gitlab: 1.15.0 -> 2.2.0
> ```

Does that manual section mandate squashing of all commits? The only rule towards that direction seems to be
> * If you have commits `pkg-name: oh, forgot to insert whitespace`: squash commits in this case. Use git rebase -i.

None of my commits here are of "oh, forgot to insert whitespace" nature, as far as I can tell.

That manual section also says:

> * Make commits of logical units.

That's what I tried to do here. Note that I _didn't_ make separate commits for _all_ versions since 1.15.0. My reasons for the commits are as follows:

- be60e99ffb13462284a40db179065c06cd847e28 `re-format with nixfmt`: Unrelated to the version bumps. Would result in confusing / misleading change reasons being shown by `git blame` if it'd be included in a version bump commit.
- a27308cf473a2d078abf41c16ea225a366815fb9 `1.15.0 -> 2.0.0`: Major release, this bump is the reason for dropping `six` and for disabling on Python < 3.6
- 7cceb71ed740831ed7f0a5190969a4f5e2d3b9f1 `2.0.0 -> 2.0.1`: Latest patch release of 2.0 minor release group
- 548bb89f8e78c188f0eb9981087c8fb98b4b470f  `2.0.1 -> 2.1.2`: Latest patch release of 2.1 minor release group (Note that I skipped over 2.1.0 and 2.1.1)
- a7706508276dbb85f0e562a729c18ce755b6d4f9 `2.1.2 -> 2.2.0`: (Current) latest patch release of 2.2 minor release group

Yes, these are many bumps, but I think having them in the history is worthwhile. If you maintain that they are _too_ many, I'd like to at least preserve be60e99ffb13462284a40db179065c06cd847e28 & a27308cf473a2d078abf41c16ea225a366815fb9 (and squash 7cceb71ed740831ed7f0a5190969a4f5e2d3b9f1, 548bb89f8e78c188f0eb9981087c8fb98b4b470f and a7706508276dbb85f0e562a729c18ce755b6d4f9 to one), unless you insist they be squashed into only one commit.

**Comment by das-g** [comment]
Does 3 commits sound good to you?

Either
- `re-format with nixfmt` be60e99ffb13462284a40db179065c06cd847e28
- `1.15.0 -> 2.0.0` a27308cf473a2d078abf41c16ea225a366815fb9
- `2.0.0 -> 2.2.0` 7cceb71ed740831ed7f0a5190969a4f5e2d3b9f1 + 548bb89f8e78c188f0eb9981087c8fb98b4b470f + a7706508276dbb85f0e562a729c18ce755b6d4f9 squashed

or
- `re-format with nixfmt` be60e99ffb13462284a40db179065c06cd847e28
- `1.15.0 -> 2.0.1` a27308cf473a2d078abf41c16ea225a366815fb9 + 7cceb71ed740831ed7f0a5190969a4f5e2d3b9f1 squashed
- `2.0.1 -> 2.2.0` 548bb89f8e78c188f0eb9981087c8fb98b4b470f + a7706508276dbb85f0e562a729c18ce755b6d4f9 squashed

make most sense, if not all 5 commits shall be preserved.

**Comment by jonringer** [comment]
From the perspective of the master branch, I think it makes more sense to just do all the bumps in one go, because the individual package bumps never existed. But that's just me

**Comment by das-g** [comment]
>From the perspective of the master branch, I think it makes more sense to just do all the bumps in one go, because the individual package bumps never existed.

Alright, I've squashed the four version bump commits into one, but left the re-format commit as-is.

> But that's just me

Not quite sure what to make of that. If you require changes for an approving review, please give actionable feedback. If however the PR just isn't to your best liking, but you find it objectively acceptable, please state that clearly.

**Comment by jonringer** [comment]
> Not quite sure what to make of that. If you require changes for an approving review, please give actionable feedback. If however the PR just isn't to your best liking, but you find it objectively acceptable, please state that clearly.

To me, you're doing a version bump, if you have a series of 4 version bumps, why not collapse it into a single version bump? If there was a regression in this package, then having the many version bumps doesn't really help, because you are trying to triage regressions from master. So having an intermediate commit, which never had a release on that package, seems to add noise when doing a `git bisect`.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 86269 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>2 packages built:</summary><br>- python37Packages.python-gitlab<br>- python38Packages.python-gitlab</details>

**Pull request merged**
