### PR TITLE
dune_3: 3.16.1 -> 3.17.0

### PR DESCRIPTION
**Pull request by smorimoto**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by vbgl** [comment]
@GrahamcOfBorg build ocamlPackages.hxd

**Review by vbgl — CHANGES_REQUESTED** [review]
This breaks `hxd` tests (possible workaround: disable them).

**Comment by smorimoto** [comment]
For some reason, the dune cache is enabled, and there seems to be an error that cannot create a directory for it. I don't usually use Nix and don't know how to work around this. Can you help me?

**Comment by smorimoto** [comment]
Related PRs:
- https://github.com/ocaml/dune/pull/10710
- https://github.com/ocaml/dune/pull/10944

**Comment by vbgl** [comment]
Here is an other suggestion:

~~~
--- a/pkgs/development/ocaml-modules/hxd/default.nix
+++ b/pkgs/development/ocaml-modules/hxd/default.nix
@@ -23,6 +23,10 @@ buildDunePackage rec {
 
   doCheck = true;
 
+  preCheck = ''
+    export DUNE_CACHE=disabled
+  '';
+
   meta = with lib; {
     description = "Hexdump in OCaml";
     homepage = "https://github.com/dinosaure/hxd";
~~~

**Comment by smorimoto** [comment]
@vbgl Isn't this possible for all packages using dune?

**Comment by smorimoto** [comment]
@GrahamcOfBorg build ocamlPackages.hxd

**Comment by smorimoto** [comment]
@GrahamcOfBorg build ocamlPackages.hxd

**Comment by smorimoto** [comment]
@GrahamcOfBorg build ocamlPackages.ligo

**Comment by vbgl** [comment]
Other newly failing OCaml libraries: `ocplib-simplex`, `melange`.

**Comment by smorimoto** [comment]
@GrahamcOfBorg ocamlPackages.melange

**Comment by vbgl** [comment]
`ocplib-index` can be fixed using the following patch:

~~~
diff --git a/tests/dune b/tests/dune
index 4fcdd22..b0e0fff 100644
--- a/tests/dune
+++ b/tests/dune
@@ -11,41 +11,3 @@
    standalone_minimal
    standalone_test_strict_bounds)
  (libraries ocplib-simplex zarith))
-
-(rule
- (alias runtest)
- (action
-  (diff solveEmpty.expected solveEmpty.output)
- )
-)
-
-(rule
- (alias runtest)
- (action
-  (diff
-    standalone_minimal_maximization.expected
-    standalone_minimal_maximization.output
-  )
- )
-)
-
-(rule
- (alias runtest)
- (action
-  (diff
-    standalone_minimal.expected
-    standalone_minimal.output
-  )
- )
-)
-
-(rule
- (alias runtest)
- (action
-  (diff
-    standalone_test_strict_bounds.expected
-    standalone_test_strict_bounds.output
-  )
- )
-)
-
~~~

**Comment by smorimoto** [comment]
@vbgl Can you add commits to this PR? I'm completely new to the Nix ecosystem and still don't understand which packages are broken and how.

**Comment by vbgl** [comment]
I’ve just done it and included in this branch commits from other PRs (#362572 & #363369).

**Comment by smorimoto** [comment]
Thanks a lot!

**Review by vbgl — APPROVED** [review]

**Comment by smorimoto** [comment]
Thanks a lot!

**Pull request merged**
