### PR TITLE
ipcalc: add patch to disable tests failing in Darwin sandbox

### PR DESCRIPTION
**Pull request by siriobalmelli**
Signed-off-by: Sirio Balmelli <sirio@b-ad.ch>

### CODE REVIEW

**Comment by peterhoeg** [comment]
Thank you for this but we need some comments to go in with the `patches` part so explain why we are doing this. Is there an upstream issue we can track?

**Comment by siriobalmelli** [comment]
> Thank you for this but we need some comments to go in with the `patches` part so explain why we are doing this. Is there an upstream issue we can track?

Thank you for the review, I appreciate it.

AFAICT these tests fail in sandbox only, simply because they access the network (which, as I understand, is not allowed in sandbox.

Quick reproduction on Darwin:

```
# fails to build
nix shell github:NixOS/nixpkgs#ipcalc --sandbox --command ipcalc --version

# runs ok
nix shell github:siriobalmelli-foss/nixpkgs/fix/ipcalc#ipcalc --sandbox --command ipcalc -6 -o localhost

# runs ok
nix shell github:NixOS/nixpkgs#ipcalc --no-sandbox --command ipcalc --version
```

**Comment by peterhoeg** [comment]
Sorry if I wasn't clear. You don't need to comment out the tests (removing them is fine). It's comments in pkgs/tools/networking/ipcalc/default.nix I was referring to.

**Comment by siriobalmelli** [comment]
> Sorry if I wasn't clear. You don't need to comment out the tests (removing them is fine). It's comments in pkgs/tools/networking/ipcalc/default.nix I was referring to.

Tracking, thank you.

Respun to:

- remove comments from the patchfile
- add an explainer comment in pkgs/tools/networking/ipcalc/default.nix

**Pull request merged**
