### PR TITLE
snappy: build both static and shared libs

### PR DESCRIPTION
**Pull request by volth**
build lib/libsnappy.so as it was before 1.1.7

### CODE REVIEW

**Comment by volth** [comment]
oops, now it builds only .so, it stopped producing .a :(

**Comment by orivej** [comment]
There was no `.a` before f689a6d1c6796c4a4f116ffec6c4624379e04bc9.

**Comment by volth** [comment]
> There was no .a before f689a6d

Yes, @dezgeg introduced .a in f689a6d and I assumed he needs .a (as it was the only output file) and kept producing .a in order not to break his things

**Comment by dezgeg** [comment]
Actually I just tried to upgrade the package to make it work on ARMv7 at all (it was failing the testsuite before), but upstream had switched the build system to CMake, and I just assumed it had the same semantics as before.

**Pull request closed without merging**
