### PR TITLE
bottles: 51.15 -> 51.17

### PR DESCRIPTION
**Pull request by Gliczy**
51.16: https://github.com/bottlesdevs/Bottles/releases/tag/51.16
51.17: https://github.com/bottlesdevs/Bottles/releases/tag/51.17
Full diff: https://github.com/bottlesdevs/Bottles/compare/51.15...51.17

A check has been added in `51.16` that will make `bottles` exit if it is not running as a sandboxed flatpak, I added a patch to remove this check.

I added another patch to remove the "Core" tab that was in the preferences.
This tab is not used for quite some time in the official Flatpak and is not functioning anyway.
I opted to patch it out since it will only cause confusion and may lead to unwanted bug report to upstream.

I re-ordered the python3 packages in `propagatedBuildInputs` so they are in the same order as the official flatpak (to make it easier to review if we are missing dependencies) and added `pycairo` and `charset-normalizer` since they are included in the official package.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Gliczy** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 365397`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
  </ul>
</details>

**Comment by Gliczy** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 365397`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
  </ul>
</details>

**Comment by keenanweaver** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 365397`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
  </ul>
</details>

**Review by keenanweaver — APPROVED** [review]

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 365397`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
  </ul>
</details>

**Comment by Gliczy** [comment]
It runs without errors on my system, but I'm using an AMD GPU.

Does this also happen on the current version of `bottles` (51.15)?

**Comment by khaneliman** [comment]
> It runs without errors on my system, but I'm using an AMD GPU.
> 
> 
> 
> Does this also happen on the current version of `bottles` (51.15)?

I have AMD, as well. But the error is the 'orjson' call

**Comment by Gliczy** [comment]
I've rebuilt `bottles` with `nix build` and `nixpkgs-review` to double check. I also use this PR's version of `bottles` with my flake for a few days.
I got no `orjson` error showing up and `bottles` launch properly.

I'm a bit confused.

**Comment by Brisingr05** [comment]
I'm not getting that error either. I have an Intel iGPU.

**Comment by Brisingr05** [comment]
Unrelated to the error, but since we're removing the sandbox check, could we add a warning [similar to Fedora](https://src.fedoraproject.org/rpms/bottles/blob/rawhide/f/1003-Display-warning-regarding-issue-tracker.patch) that this package is unsupported by upstream and to report bugs here?

**Review by khaneliman — APPROVED** [review]

**Comment by LordGrimmauld** [comment]
I had a chat with @theevilskeleton (the author of the sandbox check) and how to do repackaging well.
As outlined in [this fedi thread](https://social.treehouse.systems/@TheEvilSkeleton/113676105047314912) the sandbox detection patch has caused some waves, which as far as i can tell was indeed the intention.

Their communication to me was nix being fine, because users mostly know to file packaging bugs with the nixpkgs issue tracker, as well as the nix package being well tested in comparison to some other distribution methods. We briefly also discussed a nix-specific detection (like checking `argv0` against `/nix/store` or checking `etc/os-release`, but concluded none of those options are as simple as just a revert patch.

This does not mean we should sit on our laurels and just entirely disregard the problem here. Patching the issue report URL is definitely a good idea. But the patch did not deliberately target nix specifically. So we are still "blessed" in a sense.

Skeli is not a maintainer in nixpkgs, but i do keep contact to them and they definitely know about nix and how our packages work, enough to respect it. But they felt uncomfortable writing a statement in here unprompted, so here i am writing that "by proxy". If i twisted anything, do let me know @theevilskeleton!

**Comment by khaneliman** [comment]
Reading some of the linked discussions, it honestly wouldn't be a bad idea to at least add the console warning and reroute the issue link to prevent upstream from getting reports directly from users from the software we are manipulating. We can triage in our tracker and determine if its truly an upstream bug.

**Comment by Gliczy** [comment]
Thanks @Brisingr05 for your suggestion and @LordGrimmauld for reaching out to TheEvilSkeleton to get a clearer view about how us packaging `bottles` stand with upstream!

To ensure our users are aware of the unofficial nature of this package and to avoid burdening upstream with issues caused by our packaging, I have done the following:
- Restored the popup warning informing that the package is unsupported and to report issues to nixpkgs.
- Added a warning when run in a terminal.
- Redirected "Report an Issue" to `nixpkgs` issue tracker.
- Added `removeWarningPopup`, which default to false. This provides an opt-in option for removing the popup warning.

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 365397`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
  </ul>
</details>

**Comment by LordGrimmauld** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 365397`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
  </ul>
</details>

**Review by LordGrimmauld — APPROVED** [review]
Tested, the override works (and this is, imo, more intuitive).
Both packages start and behave like bottles should behave, with the only difference being the popup. Issue report link also points to nixpkgs.  Thanks for your work :)

**Pull request merged**
