### PR TITLE
mimalloc: 2.0.2 -> 2.0.5

### PR DESCRIPTION
**Pull request by kamadorueda**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
On macos 10.15:

```
[1/40] Building C object CMakeFiles/mimalloc.dir/src/random.c.o
FAILED: CMakeFiles/mimalloc.dir/src/random.c.o 
/nix/store/18i795dcmzx2jlc7560nf65qybp0y41p-clang-wrapper-11.1.0/bin/clang -DMI_MALLOC_OVERRIDE -DMI_OSX_INTERPOSE=1 -DMI_OSX_ZONE=1 -DMI_SHARED_LIB -DMI_SHARED_LIB_EXPORT -Dmimalloc_EXPORTS -I/tmp/nix-build-mimalloc-2.0.5.drv-0/source/include -O3 -DNDEBUG -fPIC -Wall -Wextra -Wno-unknown-pragmas -fvisibility=hidden -Wstrict-prototypes -Wpedantic -Wno-static-in-inline -ftls-model=initial-exec -fno-builtin-malloc -std=gnu11 -MD -MT CMakeFiles/mimalloc.dir/src/random.c.o -MF CMakeFiles/mimalloc.dir/src/random.c.o.d -o CMakeFiles/mimalloc.dir/src/random.c.o -c /tmp/nix-build-mimalloc-2.0.5.drv-0/source/src/random.c
In file included from /tmp/nix-build-mimalloc-2.0.5.drv-0/source/src/random.c:198:
/nix/store/c5jrszdq2hy3hj9rpyx3hk9gba60wd1d-Libsystem-1238.60.2/include/CommonCrypto/CommonRandom.h:35:9: error: unknown type name 'CCCryptorStatus'
typedef CCCryptorStatus CCRNGStatus;
        ^
1 error generated.

```

**Comment by risicle** [comment]
The above problem is resolved by 

```postPatch = ''
    substituteInPlace src/random.c \
      --replace '#include <CommonCrypto/CommonRandom.h>' \
        $'#include <CommonCrypto/CommonCryptor.h>\n#include <CommonCrypto/CommonRandom.h>'
  '';
```

But then we get

```
/nix/store/18i795dcmzx2jlc7560nf65qybp0y41p-clang-wrapper-11.1.0/bin/clang -DMI_MALLOC_OVERRIDE -DMI_OSX_INTERPOSE=1 -DMI_OSX_ZONE=1 -DMI_SHARED_LIB -DMI_SHARED_LIB_EXPORT -Dmimalloc_EXPORTS -I/tmp/nix-build-mimalloc-2.0.5.drv-2/source/include -std=c11 -O3 -DNDEBUG -fPIC -Wall -Wextra -Wno-unknown-pragmas -fvisibility=hidden -Wstrict-prototypes -Wpedantic -Wno-static-in-inline -ftls-model=initial-exec -fno-builtin-malloc -std=gnu11 -MD -MT CMakeFiles/mimalloc.dir/src/alloc.c.o -MF CMakeFiles/mimalloc.dir/src/alloc.c.o.d -o CMakeFiles/mimalloc.dir/src/alloc.c.o -c /tmp/nix-build-mimalloc-2.0.5.drv-2/source/src/alloc.c
In file included from /tmp/nix-build-mimalloc-2.0.5.drv-2/source/src/alloc.c:19:
/tmp/nix-build-mimalloc-2.0.5.drv-2/source/src/alloc-override.c:80:21: error: use of undeclared identifier 'aligned_alloc'; did you mean 'mi_aligned_alloc'?
    MI_INTERPOSE_MI(aligned_alloc),
                    ^~~~~~~~~~~~~
                    mi_aligned_alloc
```

**Comment by risicle** [comment]
Aha https://github.com/microsoft/mimalloc/pull/550

**Comment by risicle** [comment]
```
  patches = [
    (fetchpatch {
      name = "older-macos-fixes.patch";
      url = "https://github.com/microsoft/mimalloc/commit/40e0507a5959ee218f308d33aec212c3ebeef3bb.patch";
      sha256 = "15qx2a3axhhwbfzxdis98b8j14y9cfgca0i484aj2pjpqnm0pb8c";
    })
  ];
```

fixes it for me, macos 10.15.

**Comment by kamadorueda** [comment]
Thank you @risicle 

Just updated the PR with your suggestion, really good review btw, thank you

**Comment by risicle** [comment]
It's possible to enable the tests too with

```
  doCheck = true;
  preCheck = let
    ldLibraryPathEnv = if stdenv.isDarwin then "DYLD_LIBRARY_PATH" else "LD_LIBRARY_PATH";
  in ''
    export ${ldLibraryPathEnv}="$(pwd)/build:''${${ldLibraryPathEnv}}"
  '';
```

**Comment by kamadorueda** [comment]
Thank you @risicle 

Just updated the PR, works like a charm on *-linux

**Review by risicle — APPROVED** [review]
`nixpkgs-review` happy, macos 10.15, nixos x86_64 & aarch64

**Pull request merged**
