### PR TITLE
duckdb: 0.4.0 -> 0.5.0

### PR DESCRIPTION
**Pull request by cpcloud**
###### Description of changes

* Bump `duckdb` to 0.5.0
* Bump `duckdb-engine` to 0.6.4
* Bump `ibis-framework` to 3.2.0
* Add `sqlglot` @ 6.0.7

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
@ofborg build python3Packages.duckdb-engine

Fails for me with this

**Comment by cpcloud** [comment]
@risicle I believe I've fixed that issue by updating `duckdb-engine` to the latest version (0.6.3).

**Comment by risicle** [comment]
That's better, now it's

@ofborg build python310Packages.ibis

**Comment by risicle** [comment]
Oops I mean

@ofborg build python310Packages.ibis-framework

**Comment by cpcloud** [comment]
Ah ok. We're going to release ibis-framework soon, with duckdb 0.5.0 support so maybe I'll just wrap this up then.

**Comment by cpcloud** [comment]
@risicle I've bumped added everything necessary for this PR, can you give it a whirl? I'm running `nixpkgs-review` in the meantime.

**Comment by cpcloud** [comment]
Result of `nixpkgs-review pr 189993` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>duckdb</li>
    <li>python310Packages.duckdb</li>
    <li>python310Packages.duckdb-engine</li>
    <li>python310Packages.ibis-framework</li>
    <li>python310Packages.sqlglot</li>
    <li>python39Packages.duckdb</li>
    <li>python39Packages.duckdb-engine</li>
    <li>python39Packages.ibis-framework</li>
    <li>python39Packages.sqlglot</li>
  </ul>
</details>

**Comment by risicle** [comment]
@ofborg build python310Packages.duckdb

For some reason `python39Packages.duckdb` is fine for me on macos 10.15 but this always fails on `duckdb_engine/tests/test_basic.py::test_simple_string` :confused:

**Review by risicle — APPROVED** [review]
LGTM

`nixpkgs-review` happy, macos 10.15 & nixos x86_64. `pkgsMusl.duckdb` & `pkgsCross.aarch64-multiplatform.duckdb` build.

**Comment by risicle** [comment]
`python310Packages.duckdb-engine` built fine for me once my machine had less load.

**Pull request merged**
