### PR TITLE
qmidinet: 0.2.1 -> 0.4.1

### PR DESCRIPTION
**Pull request by magnetophon**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by fpletz** [comment]
The Travis errors seems to be related:
```
checking for qmake-qt5... no
checking for qmake... /usr/bin/qmake
configure: error: qmake-qt5 not found in current PATH. Maybe QT development environment isn't available. (qt5-devel)
builder for ‘/nix/store/c6i6ph103j5hscshnhha82xj2j0w93wk-qmidinet-0.4.0.drv’ failed with exit code 1
error: build of ‘/nix/store/c6i6ph103j5hscshnhha82xj2j0w93wk-qmidinet-0.4.0.drv’ failed
The invocation of "nix-build -A QmidiNet /home/travis/.nox/nixpkgs" failed
```

**Comment by bjornfor** [comment]
I got a bit further (rebased this PR onto master), but it still failed:

```
$ nix-build -A QmidiNet
[...]
config.status: creating src/qmidinet.desktop
config.status: creating src/config.h

  QmidiNet 0.4.0

  Build target . . . . . . . . . . . . . . . . . . .: release

  ALSA MIDI support  . . . . . . . . . . . . . . . .: yes
  JACK MIDI support  . . . . . . . . . . . . . . . .: yes

  Install prefix . . . . . . . . . . . . . . . . . .: /nix/store/kipl6cp2zm7yp8cjzy1iya9vywd35h6p-qmidinet-0.4.0

Now type 'make', followed by 'make install' as root.

building
make flags: SHELL=/nix/store/4has5pbalamhkgx3qgjxm2cgbdi2h871-bash-4.3-p42/bin/bash    
Could not find qmake configuration file linux-g++.
Error processing project file: qmidinet.pro
Makefile:48: recipe for target 'qmidinet.mak' failed
make: *** [qmidinet.mak] Error 3
builder for ‘/nix/store/ddnk4nfcm5203jj06dry7390lxz384m2-qmidinet-0.4.0.drv’ failed with exit code 2
error: build of ‘/nix/store/ddnk4nfcm5203jj06dry7390lxz384m2-qmidinet-0.4.0.drv’ failed
```

@fpletz: Was that build without chroot? Just wondering since configure found qmake in /usr/bin/qmake.

**Comment by magnetophon** [comment]
Sorry to be missing in this conversation.
I'm a bit swamped right now!

**Comment by magnetophon** [comment]
I pushed a new version.
It builds and runs now.

**Pull request merged**
