### PR TITLE
wrapNeovimUnstable: add appName option

### PR DESCRIPTION
**Pull request by mrcjkb**
## Description of changes

CC: @teto 

This adds an optional `appName` option, which - if set - adds [`NVIM_APPNAME`](https://neovim.io/doc/user/starting.html#%24NVIM_APPNAME) to the wrapper and creates a symlink.
This can be useful for having multiple Neovim derivations that don't use the same `$XDG_CONFIG_HOME/nvim` directory (instead, they use `$XDG_CONFIG_HOME/<appName>`.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mrcjkb** [comment]
Result of `nixpkgs-review pr 268412` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by teto** [comment]
This is doable without patching nixpkgs so I would be of the opinion to keep the wrapper minimal and not special case this scenario. 
I do want to make it easier for users to build hermetic vs impure nvims since this is a recurring problem as seen here https://github.com/NixOS/nixpkgs/issues/177375 . So I think here the best would be to add a section in the documentation showing how to do that (your PR basically, maybe renaming pname too). Waht do you think ?

**Comment by mrcjkb** [comment]
> This is doable without patching nixpkgs so I would be of the opinion to keep the wrapper minimal and not special case this scenario. I do want to make it easier for users to build hermetic vs impure nvims since this is a recurring problem as seen here #177375 . So I think here the best would be to add a section in the documentation showing how to do that (your PR basically, maybe renaming pname too). Waht do you think ?

Adding a wrapper that sets `NVIM_APPNAME` is easy without patching nixpkgs, but adding an alias isn't so straightforward (afaik, you would have to create a shell alias or a new derivation). Or do you know of an easier way?

**Comment by teto** [comment]
by "an alias" do you refer to `ln -s $out/bin/nvim $out/bin/${appName}` ? I would put it in a fixupPhase. `mv bin/nvim bin/${appName}` for instance

**Comment by mrcjkb** [comment]
> by "an alias" do you refer to `ln -s $out/bin/nvim $out/bin/${appName}` ? I would put it in a fixupPhase. `mv bin/nvim bin/${appName}` for instance. The `nvim` executable must disappear if you create an appname version of it else you will get "nvim" collisions (you might have some for the providers too, I had not put #190812 in case someone relied on those but we might be able to remove them).

Makes sense. I'll close this and add a section to the docs in a separate PR.

**Pull request closed without merging**
