### PR TITLE
 nixos/systemd: apply .link even when networkd is disabled (without the lib refactor this time)

### PR DESCRIPTION
**Pull request by flokli**
###### Motivation for this change
This is https://github.com/NixOS/nixpkgs/pull/82310 re-applied, but without https://github.com/NixOS/nixpkgs/pull/82310/commits/1115959a8d4d73ad73341563dc8bbf52230a281e which seems to have caused problems with hydra evaluations.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NinjaTrappeur** [comment]
:+1:

**Comment by flokli** [comment]
@vcunat can we schedule a jobset for this on hydra? Or what's your plan on checking this?

**Comment by grahamc** [comment]
Pretty cheap to revert if there is an issue. I'll merge kick off an eval. @flokli you'll watch?

**Comment by flokli** [comment]
Yes, thanks a lot!

**Comment by vcunat** [comment]
Evaluation [succeeded](https://hydra.nixos.org/eval/1576564).

**Comment by flokli** [comment]
Backported to 20.03 in c4611d8f20b and e26bc8445a2.

**Pull request merged**
