### PR TITLE
podman: 1.6.2 -> 1.6.3

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

The slirp4netns change is needed for proper rootless containers to work. 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
do you mind changing the outputs of podman to:
```
outputs = [ "out" "man" ];
```
nothing actually gets written to the outPath but:
```
$ tree ./result
./result
└── nix-support
    └── propagated-build-inputs

1 directory, 1 file
[00:34:06] jon@jon-desktop /home/jon/projects/nixpkgs (fix-isort)
$ realpath ./result
/nix/store/dp6gv8r80rycxx4ryzf8w1v6v093jygx-podman-1.6.3
```

**Comment by peterhoeg** [comment]
>   do you mind changing the outputs of podman to:
>
> outputs = [ "out" "man" ];

That breaks the build (also after changing $bin to $out). I'll take a look at that later.

**Comment by jonringer** [comment]
I think there's debug symbols pointing back to the compiler, if you grep the binary, you will find a store path to go

**Review by saschagrunert — COMMENTED** [review]
I think there is a man page missing from this release. The commit https://github.com/containers/libpod/commit/079164c39193ee35641e2f4b680d8e69fe553625 is not part of v1.6.3. Does this hurt us?

**Comment by peterhoeg** [comment]
1.7.0 is already in master.

**Pull request closed without merging**
