### PR TITLE
[release-24.05] github-runner: 2.317.0 -> 2.319.1

### PR DESCRIPTION
**Pull request by newAM**
## Description of changes

Closes #333288.

This is the same as #333288, but with `sha256` instead of `hash` for `deps.nix`.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by sysvinit** [comment]
I've attempted to build github-runner from the commit in this PR, and there's a small search-and-replace error in the deps update -- it's accidentally matched the name of the `System.IO.Hashing` module, which has been mangled into `System.IO.sha256ing`, which causes a build failure.

**Comment by newAM** [comment]
> I've attempted to build github-runner from the commit in this PR, and there's a small search-and-replace error in the deps update -- it's accidentally matched the name of the `System.IO.Hashing` module, which has been mangled into `System.IO.sha256ing`, which causes a build failure.

Gah!  I fixed that locally but forgot to push :(

Thanks for the catch!

**Comment by newAM** [comment]
For anyone reviewing, note the failed job is not a hard fail:

> Note this should not necessarily be treated as a hard fail, but a reviewer's attention should be drawn to it and github actions have no way of doing that but to raise a 'failure'

I think it is because I used the words "[Adapted from] cherry picked" in my commit message.

**Comment by arianvp** [comment]
Hmm it's annoying this was changed. This means backports will never be working automatically from now on. Can we move unstable back to using `sha256`?  I'm a bit worried as Github Actions runners will just blackout after a while if they're not updated soon enough.   If we have to manually update the patches for every backport that is really frustrating

**Comment by arianvp** [comment]
Result of `nixpkgs-review pr 333767` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>github-runner</li>
  </ul>
</details>

**Comment by arianvp** [comment]
Result of `nixpkgs-review pr 333767` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>github-runner</li>
  </ul>
</details>

**Comment by arianvp** [comment]
<details>
<summary>
Double checked that non of the hashes changed and just the word `sha256` changed to `hash`:
</summary>

```
{ fetchNuGet }: [
  (fetchNuGet { pname = "Azure.Core"; version = "1.36.0"; [-sha256-]{+hash+} = "sha256-lokfjW2wvgFu6bALLzNmDhXIz3HXoPuGX0WfGb9hmpI="; })
  (fetchNuGet { pname = "Azure.Storage.Blobs"; version = "12.19.1"; [-sha256-]{+hash+} = "sha256-E7QHJrhQjQjGhFq4GoQpyVGR6uKfA91NGcyziRf
dr2U="; })
  (fetchNuGet { pname = "Azure.Storage.Common"; version = "12.18.1"; [-sha256-]{+hash+} = "sha256-M10Ov1bBV1/U8R3Sp05apS3qFHONQRmAQakQsd
17X8I="; })
  (fetchNuGet { pname = "Castle.Core"; version = "4.4.0"; [-sha256-]{+hash+} = "sha256-7hLBAHnB+drr2yU4w3o05eMX2ADy/rXN3XRPBn1d7GY="; })
  (fetchNuGet { pname = "Microsoft.AspNet.WebApi.Client"; version = "5.2.9"; [-sha256-]{+hash+} = "sha256-CCytWp0v8C6NZa+o4cRXvA2u/ZOEA3
TiG9+luszAwes="; })
  (fetchNuGet { pname = "Microsoft.Bcl.AsyncInterfaces"; version = "1.1.1"; [-sha256-]{+hash+} = "sha256-fAcX4sxE0veWM1CZBtXR/Unky+6sE33
yrV7ohrWGKig="; })
  (fetchNuGet { pname = "Microsoft.CodeCoverage"; version = "17.2.0"; [-sha256-]{+hash+} = "sha256-ckbeFz5ArvZUE7w3EYiciBIGlmbmjwpxqWeAO
EKgHgU="; })
  (fetchNuGet { pname = "Microsoft.CSharp"; version = "4.0.1"; [-sha256-]{+hash+} = "sha256-0huoqR2CJ3Z9Q2peaKD09TV3E6saYSqDGZ290K8CrH8=
"; })
  (fetchNuGet { pname = "Microsoft.IdentityModel.Logging"; version = "5.2.1"; [-sha256-]{+hash+} = "sha256-b1wK8yssiKQxsFO7FFNQAffEu9r8c
3YPcIY+UWVS874="; })
  (fetchNuGet { pname = "Microsoft.IdentityModel.Tokens"; version = "5.2.1"; [-sha256-]{+hash+} = "sha256-APBQ+v+2RvfE98sHXzEIjujGYvMzut
4RtpGHvAsJZg8="; })
  (fetchNuGet { pname = "Microsoft.NET.Test.Sdk"; version = "17.2.0"; [-sha256-]{+hash+} = "sha256-IXyc+oc7EwalDaq+UkkWx3bhZC/H+SZ8rTHMi
87Allk="; })
  (fetchNuGet { pname = "Microsoft.NETCore.Platforms"; version = "1.0.1"; [-sha256-]{+hash+} = "sha256-mZotlGZqtrqDSoBrZhsxFe6fuOv5/BIo0
w2Z2x0zVAU="; })
  (fetchNuGet { pname = "Microsoft.NETCore.Platforms"; version = "1.0.1-rc2-24027"; [-sha256-]{+hash+} = "sha256-qNPzjQvYz+X3OGuN/cn3vHG
VFkUH1lEPJtlRjbYrHKg="; })
  (fetchNuGet { pname = "Microsoft.NETCore.Platforms"; version = "1.1.0"; [-sha256-]{+hash+} = "sha256-FeM40ktcObQJk4nMYShB61H/E8B7tIKfl
9ObJ0IOcCM="; })
  (fetchNuGet { pname = "Microsoft.NETCore.Platforms"; version = "1.1.1"; [-sha256-]{+hash+} = "sha256-8hLiUKvy/YirCWlFwzdejD2Db3DaXhHxT
7GSZx/znJg="; })
  (fetchNuGet { pname = "Microsoft.NETCore.Platforms"; version = "2.0.0"; [-sha256-]{+hash+} = "sha256-IEvBk6wUXSdyCnkj6tHahOJv290tVVT8t
yemYcR0Yro="; })
  (fetchNuGet { pname = "Microsoft.NETCore.Runtime"; version = "1.0.2-rc2-24027"; [-sha256-]{+hash+} = "sha256-EO7lnnodbx7XgVWRtqQbYFwwb
SFxGB9FRDSgYYJt90Y="; })
  (fetchNuGet { pname = "Microsoft.NETCore.Runtime.CoreCLR"; version = "1.0.2-rc2-24027"; [-sha256-]{+hash+} = "sha256-vZCfpwHH4vrzj9WPV
Jt4FeTjsjJf81op0D9Rt82XwBc="; })
  (fetchNuGet { pname = "Microsoft.NETCore.Runtime.Native"; version = "1.0.2-rc2-24027"; [-sha256-]{+hash+} = "sha256-VOuY8bICze650uP6Bz
rUc5j/saFidG304VMvaetaF4Y="; })
  (fetchNuGet { pname = "Microsoft.NETCore.Targets"; version = "1.0.1"; [-sha256-]{+hash+} = "sha256-lxxw/Gy32xHi0fLgFWNj4YTFBSBkjx5l6uc
mbTyf7V4="; })
  (fetchNuGet { pname = "Microsoft.NETCore.Targets"; version = "1.0.1-rc2-24027"; [-sha256-]{+hash+} = "sha256-sv12e7PuIV06abQV2ms4fotpQ
CyuufMsIOWoqSUqJMg="; })
  (fetchNuGet { pname = "Microsoft.NETCore.Targets"; version = "1.1.0"; [-sha256-]{+hash+} = "sha256-0AqQ2gMS8iNlYkrD+BxtIg7cXMnr9xZHtKA
uN4bjfaQ="; })
  (fetchNuGet { pname = "Microsoft.NETCore.Targets"; version = "1.1.3"; [-sha256-]{+hash+} = "sha256-WLsf1NuUfRWyr7C7Rl9jiua9jximnVvzy6n
k2D2bVRc="; })
  (fetchNuGet { pname = "Microsoft.NETCore.Windows.ApiSets"; version = "1.0.1-rc2-24027"; [-sha256-]{+hash+} = "sha256-HezmYiv8wL03Ok3FF
BtAULe2yOUjjXfj9wPHE8hNlQw="; })
...skipping...
  (fetchNuGet { pname = "System.Threading.Tasks"; version = "4.0.11-rc2-24027"; [-sha256-]{+hash+} = "sha256-ADtupyd4h9YLTqIE9t/30CrUka0+CFI9C9KP2ttvTzs="; })
  (fetchNuGet { pname = "System.Threading.Tasks"; version = "4.3.0"; [-sha256-]{+hash+} = "sha256-Z5rXfJ1EXp3G32IKZGiZ6koMjRu0n8C1NGrwpdIen4w="; })
  (fetchNuGet { pname = "System.Threading.Tasks.Extensions"; version = "4.0.0"; [-sha256-]{+hash+} = "sha256-+YdcPkMhZhRbMZHnfsDwpNbUkr31X7pQFGxXYcAPZbE="; })
  (fetchNuGet { pname = "System.Threading.Tasks.Extensions"; version = "4.0.0-rc2-24027"; [-sha256-]{+hash+} = "sha256-z9+gWBZBjNoG7P5F0RHMVA4VxAw8Farnf0a94S9uGoE="; })
  (fetchNuGet { pname = "System.Threading.Tasks.Extensions"; version = "4.3.0"; [-sha256-]{+hash+} = "sha256-X2hQ5j+fxcmnm88Le/kSavjiGOmkcumBGTZKBLvorPc="; })
  (fetchNuGet { pname = "System.Threading.Tasks.Extensions"; version = "4.5.1"; [-sha256-]{+hash+} = "sha256-3NeBC+r7eTVz3f+cEm1NkVhxSr7LrYGX/NdUwje9ecY="; })
  (fetchNuGet { pname = "System.Threading.Tasks.Extensions"; version = "4.5.4"; [-sha256-]{+hash+} = "sha256-owSpY8wHlsUXn5xrfYAiu847L6fAKethlvYx97Ri1ng="; })
  (fetchNuGet { pname = "System.Threading.ThreadPool"; version = "4.3.0"; [-sha256-]{+hash+} = "sha256-wW0QdvssRoaOfQLazTGSnwYTurE4R8FxDx70pYkL+gg="; })
  (fetchNuGet { pname = "System.Threading.Timer"; version = "4.0.1-rc2-24027"; [-sha256-]{+hash+} = "sha256-B3qiX7GvZ6wU9lyg4BEQhspVq0LGcF/W4H+4RwWJfBo="; })
  (fetchNuGet { pname = "System.Threading.Timer"; version = "4.3.0"; [-sha256-]{+hash+} = "sha256-pmhslmhQhP32TWbBzoITLZ4BoORBqYk25OWbru04p9s="; })
  (fetchNuGet { pname = "System.Xml.ReaderWriter"; version = "4.0.11"; [-sha256-]{+hash+} = "sha256-haZAFFQ9Sl2DhfvEbdx2YRqKEoxNMU5STaqpMmXw0zA="; })
  (fetchNuGet { pname = "System.Xml.ReaderWriter"; version = "4.0.11-rc2-24027"; [-sha256-]{+hash+} = "sha256-jYxZjqyHIpC4g3QngWbA3joMg0DQBRWeyWviauJ73G8="; })
  (fetchNuGet { pname = "System.Xml.ReaderWriter"; version = "4.3.0"; [-sha256-]{+hash+} = "sha256-QQ8KgU0lu4F5Unh+TbechO//zaAGZ4MfgvW72Cn1hzA="; })
  (fetchNuGet { pname = "System.Xml.XDocument"; version = "4.0.11"; [-sha256-]{+hash+} = "sha256-KPz1kxe0RUBM+aoktJ/f9p51GudMERU8Pmwm//HdlFg="; })
  (fetchNuGet { pname = "System.Xml.XDocument"; version = "4.0.11-rc2-24027"; [-sha256-]{+hash+} = "sha256-P9yCIlkbOAhF03mTF/T+iLKEXSIcncoVDbgbplykb+c="; })
  (fetchNuGet { pname = "System.Xml.XDocument"; version = "4.3.0"; [-sha256-]{+hash+} = "sha256-rWtdcmcuElNOSzCehflyKwHkDRpiOhJJs8CeQ0l1CCI="; })
  (fetchNuGet { pname = "System.Xml.XmlDocument"; version = "4.3.0"; [-sha256-]{+hash+} = "sha256-kbuV4Y7rVJkfMp2Kgoi8Zvdatm9CZNmlKB3GZgANvy4="; })
  (fetchNuGet { pname = "System.Xml.XmlSerializer"; version = "4.3.0"; [-sha256-]{+hash+} = "sha256-IqTGPENWYoI06x2NHFPVtHlLEq9tazbom32bFLom6h4="; })
  (fetchNuGet { pname = "xunit"; version = "2.7.1"; [-sha256-]{+hash+} = "sha256-cf9vLYPIOvBGiUoUept+1NJfuhpSSdCFQSr6+XFde6E="; })
  (fetchNuGet { pname = "xunit.abstractions"; version = "2.0.3"; [-sha256-]{+hash+} = "sha256-0D1y/C34iARI96gb3bAOG8tcGPMjx+fMabTPpydGlAM="; })
  (fetchNuGet { pname = "xunit.analyzers"; version = "1.12.0"; [-sha256-]{+hash+} = "sha256-ZqbNShkNckXsZTght1ZlzkJyfd/e8oPtjSMDsJwqGuo="; })
  (fetchNuGet { pname = "xunit.assert"; version = "2.7.1"; [-sha256-]{+hash+} = "sha256-RisnpE0ov99xyrxFywIctzzVnxwXb/HEp9E0dOAq4Ns="; })
  (fetchNuGet { pname = "xunit.core"; version = "2.7.1"; [-sha256-]{+hash+} = "sha256-3+w1MZ/USIUqQbnyQT4ocgYfghpSoxawZN3E5EhtJ9M="; })
  (fetchNuGet { pname = "xunit.extensibility.core"; version = "2.7.1"; [-sha256-]{+hash+} = "sha256-6AUG4c+cKswwoR2RMz+rrBjhdkIlGiRNxfLPkqKY8gI="; })
  (fetchNuGet { pname = "xunit.extensibility.execution"; version = "2.7.1"; [-sha256-]{+hash+} = "sha256-3LEbfaJ2Uu/PWQW4NGONPr5SxZwy3Sj5yCWO6gy7IOk="; })
  (fetchNuGet { pname = "xunit.runner.visualstudio"; version = "2.4.1"; [-sha256-]{+hash+} = "sha256-Fm5DjFXZJzTJuApib0thPGUD0w0eavfBfSh9FOYtljo="; })
  (fetchNuGet { pname = "YamlDotNet.Signed"; version = "5.3.0"; [-sha256-]{+hash+} = "sha256-K/aWN3NDNkfIxBvxcr8+4AJ/bVBZ2LWC2ef9L5Qq174="; })
]
```
</details>

**Review by arianvp — APPROVED** [review]

**Comment by arianvp** [comment]
Thanks!

**Pull request merged**
