### PR TITLE
chromium: fix GCC 7 related build issues

### PR DESCRIPTION
**Pull request by YorikSar**
###### Motivation for this change

Chromium build has been failing.

Most of the issues were related to GCC update, all of them have been fixed upstream. I've added several commits that need to be applied to stable and dev. Beta is currently older that stable, so I didn't look at it.

Also removed `fix_network_api_crash.patch` and replaced it with proper commit from upstream.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @bendlas

### CODE REVIEW

**Comment by YorikSar** [comment]
Oops, it still seems to fail. Adding another patch.

**Comment by YorikSar** [comment]
@7c6f434c thanks! Can you please also cherrypick this commit to stable branches?

**Comment by bendlas** [comment]
OK, wow, there were a lot of missing pieces in this release. Thanks for taking care of this, @YorikSar

**Comment by YorikSar** [comment]
@bendlas It seems only next release will be ready for GCC 7.3, but we are already there.

**Comment by 7c6f434c** [comment]
As you say, oh Chromium guru.

**Comment by YorikSar** [comment]
@7c6f434c thanks!

**Pull request merged**
