### PR TITLE
matrix-conduit: 0.7.0 -> 0.8.0

### PR DESCRIPTION
**Pull request by mweinelt**
https://conduit.rs/changelog/#v0-8-0-2024-06-12
https://gitlab.com/famedly/conduit/-/compare/v0.7.0...v0.8.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ulrikstrid** [comment]
Noteably this is a CRITICAL vulnerability, I'm going to look try this immediately, if it boots I would suggest we merge it

**Comment by mweinelt** [comment]
> Noteably this is a CRITICAL vulnerability, I'm going to look try this immediately, if it boots I would suggest we merge it

Only if you share the homeserver with untrusted users, but yes, not great.

**Comment by pstn** [comment]
Oh, this is conduit, not nheko, sorry for the last message.

I'm not sure how much has changed here between the releases.

**Comment by niklaskorz** [comment]
NixOS 24.05 is still on 0.6.0. There is one breaking change from 0.6.0 to 0.7.0 that affects the Nix version as well, which is the new requirement of specifying the database backend, but that is already fulfilled by the NixOS module for conduit in 24.05 and I guess the vulnerability merits a backport, assuming 0.6.0 is affected too?

**Comment by mweinelt** [comment]
It was backported to 24.05, precisely because the breaking change is not breaking for us.

**Pull request merged**
