### PR TITLE
vimPlugins.sniprun: 1.3.8 -> 1.3.9

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Update vim-plugins but more specifically `sniprun` and `sg-nvim`.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 274470` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>78 packages built:</summary>
  <ul>
    <li>vimPlugins.ChatGPT-nvim</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.barbecue-nvim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.cmp-clippy</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-dictionary</li>
    <li>vimPlugins.cmp-digraphs</li>
    <li>vimPlugins.cmp-fish</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-git</li>
    <li>vimPlugins.cmp-greek</li>
    <li>vimPlugins.cmp-look</li>
    <li>vimPlugins.cmp-neosnippet</li>
    <li>vimPlugins.cmp-npm</li>
    <li>vimPlugins.cmp-nvim-lsp-signature-help</li>
    <li>vimPlugins.cmp-nvim-tags</li>
    <li>vimPlugins.cmp-pandoc-nvim</li>
    <li>vimPlugins.cmp-rg</li>
    <li>vimPlugins.cmp-snippy</li>
    <li>vimPlugins.cmp-tmux</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.cmp-vimwiki-tags</li>
    <li>vimPlugins.cmp-zsh</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.dropbar-nvim</li>
    <li>vimPlugins.go-nvim</li>
    <li>vimPlugins.hardtime-nvim</li>
    <li>vimPlugins.harpoon2</li>
    <li>vimPlugins.haskell-tools-nvim</li>
    <li>vimPlugins.image-nvim</li>
    <li>vimPlugins.julia-vim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lazygit-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.mason-lspconfig-nvim</li>
    <li>vimPlugins.material-nvim</li>
    <li>vimPlugins.mkdnflow-nvim</li>
    <li>vimPlugins.molten-nvim</li>
    <li>vimPlugins.multicursors-nvim</li>
    <li>vimPlugins.neodev-nvim</li>
    <li>vimPlugins.neoformat</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.nfnl</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.no-neck-pain-nvim</li>
    <li>vimPlugins.none-ls-nvim</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-python</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-metals</li>
    <li>vimPlugins.nvim-navbuddy</li>
    <li>vimPlugins.nvim-navic</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-parsers.erlang</li>
    <li>vimPlugins.nvim-treesitter-parsers.haskell</li>
    <li>vimPlugins.nvim-treesitter-parsers.nim</li>
    <li>vimPlugins.nvim-treesitter-parsers.v</li>
    <li>vimPlugins.nvim-treesitter-parsers.wing</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.playground</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.rustaceanvim</li>
    <li>vimPlugins.sg-nvim</li>
    <li>vimPlugins.sniprun</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.text-case-nvim</li>
    <li>vimPlugins.typescript-tools-nvim</li>
    <li>vimPlugins.unison</li>
    <li>vimPlugins.vim-lsp-settings</li>
    <li>vimPlugins.vim-test</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 274470` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>78 packages built:</summary>
  <ul>
    <li>vimPlugins.ChatGPT-nvim</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.barbecue-nvim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.cmp-clippy</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-dictionary</li>
    <li>vimPlugins.cmp-digraphs</li>
    <li>vimPlugins.cmp-fish</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-git</li>
    <li>vimPlugins.cmp-greek</li>
    <li>vimPlugins.cmp-look</li>
    <li>vimPlugins.cmp-neosnippet</li>
    <li>vimPlugins.cmp-npm</li>
    <li>vimPlugins.cmp-nvim-lsp-signature-help</li>
    <li>vimPlugins.cmp-nvim-tags</li>
    <li>vimPlugins.cmp-pandoc-nvim</li>
    <li>vimPlugins.cmp-rg</li>
    <li>vimPlugins.cmp-snippy</li>
    <li>vimPlugins.cmp-tmux</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.cmp-vimwiki-tags</li>
    <li>vimPlugins.cmp-zsh</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.dropbar-nvim</li>
    <li>vimPlugins.go-nvim</li>
    <li>vimPlugins.hardtime-nvim</li>
    <li>vimPlugins.harpoon2</li>
    <li>vimPlugins.haskell-tools-nvim</li>
    <li>vimPlugins.image-nvim</li>
    <li>vimPlugins.julia-vim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lazygit-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.mason-lspconfig-nvim</li>
    <li>vimPlugins.material-nvim</li>
    <li>vimPlugins.mkdnflow-nvim</li>
    <li>vimPlugins.molten-nvim</li>
    <li>vimPlugins.multicursors-nvim</li>
    <li>vimPlugins.neodev-nvim</li>
    <li>vimPlugins.neoformat</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.nfnl</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.no-neck-pain-nvim</li>
    <li>vimPlugins.none-ls-nvim</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-python</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-metals</li>
    <li>vimPlugins.nvim-navbuddy</li>
    <li>vimPlugins.nvim-navic</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-parsers.erlang</li>
    <li>vimPlugins.nvim-treesitter-parsers.haskell</li>
    <li>vimPlugins.nvim-treesitter-parsers.nim</li>
    <li>vimPlugins.nvim-treesitter-parsers.v</li>
    <li>vimPlugins.nvim-treesitter-parsers.wing</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.playground</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.rustaceanvim</li>
    <li>vimPlugins.sg-nvim</li>
    <li>vimPlugins.sniprun</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.text-case-nvim</li>
    <li>vimPlugins.typescript-tools-nvim</li>
    <li>vimPlugins.unison</li>
    <li>vimPlugins.vim-lsp-settings</li>
    <li>vimPlugins.vim-test</li>
  </ul>
</details>

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 274470 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>78 packages built:</summary>  <ul>    <li>vimPlugins.ChatGPT-nvim</li>    <li>vimPlugins.SchemaStore-nvim</li>    <li>vimPlugins.barbecue-nvim</li>    <li>vimPlugins.catppuccin-nvim</li>    <li>vimPlugins.cmp-clippy</li>    <li>vimPlugins.cmp-copilot</li>    <li>vimPlugins.cmp-dap</li>    <li>vimPlugins.cmp-dictionary</li>    <li>vimPlugins.cmp-digraphs</li>    <li>vimPlugins.cmp-fish</li>    <li>vimPlugins.cmp-fuzzy-buffer</li>    <li>vimPlugins.cmp-fuzzy-path</li>    <li>vimPlugins.cmp-git</li>    <li>vimPlugins.cmp-greek</li>    <li>vimPlugins.cmp-look</li>    <li>vimPlugins.cmp-neosnippet</li>    <li>vimPlugins.cmp-npm</li>    <li>vimPlugins.cmp-nvim-lsp-signature-help</li>    <li>vimPlugins.cmp-nvim-tags</li>    <li>vimPlugins.cmp-pandoc-nvim</li>    <li>vimPlugins.cmp-rg</li>    <li>vimPlugins.cmp-snippy</li>    <li>vimPlugins.cmp-tmux</li>    <li>vimPlugins.cmp-vim-lsp</li>    <li>vimPlugins.cmp-vimwiki-tags</li>    <li>vimPlugins.cmp-zsh</li>    <li>vimPlugins.completion-treesitter</li>    <li>vimPlugins.dropbar-nvim</li>    <li>vimPlugins.go-nvim</li>    <li>vimPlugins.hardtime-nvim</li>    <li>vimPlugins.harpoon2</li>    <li>vimPlugins.haskell-tools-nvim</li>    <li>vimPlugins.image-nvim</li>    <li>vimPlugins.julia-vim</li>    <li>vimPlugins.lazy-lsp-nvim</li>    <li>vimPlugins.lazygit-nvim</li>    <li>vimPlugins.lean-nvim</li>    <li>vimPlugins.leap-ast-nvim</li>    <li>vimPlugins.luasnip</li>    <li>vimPlugins.mason-lspconfig-nvim</li>    <li>vimPlugins.material-nvim</li>    <li>vimPlugins.mkdnflow-nvim</li>    <li>vimPlugins.molten-nvim</li>    <li>vimPlugins.multicursors-nvim</li>    <li>vimPlugins.neodev-nvim</li>    <li>vimPlugins.neoformat</li>    <li>vimPlugins.neogit</li>    <li>vimPlugins.nfnl</li>    <li>vimPlugins.nightfox-nvim</li>    <li>vimPlugins.no-neck-pain-nvim</li>    <li>vimPlugins.none-ls-nvim</li>    <li>vimPlugins.nvim-cmp</li>    <li>vimPlugins.nvim-dap</li>    <li>vimPlugins.nvim-dap-python</li>    <li>vimPlugins.nvim-lint</li>    <li>vimPlugins.nvim-lspconfig</li>    <li>vimPlugins.nvim-metals</li>    <li>vimPlugins.nvim-navbuddy</li>    <li>vimPlugins.nvim-navic</li>    <li>vimPlugins.nvim-treesitter</li>    <li>vimPlugins.nvim-treesitter-parsers.erlang</li>    <li>vimPlugins.nvim-treesitter-parsers.haskell</li>    <li>vimPlugins.nvim-treesitter-parsers.nim</li>    <li>vimPlugins.nvim-treesitter-parsers.v</li>    <li>vimPlugins.nvim-treesitter-parsers.wing</li>    <li>vimPlugins.orgmode</li>    <li>vimPlugins.playground</li>    <li>vimPlugins.refactoring-nvim</li>    <li>vimPlugins.rest-nvim</li>    <li>vimPlugins.rustaceanvim</li>    <li>vimPlugins.sg-nvim</li>    <li>vimPlugins.sniprun</li>    <li>vimPlugins.ssr</li>    <li>vimPlugins.text-case-nvim</li>    <li>vimPlugins.typescript-tools-nvim</li>    <li>vimPlugins.unison</li>    <li>vimPlugins.vim-lsp-settings</li>    <li>vimPlugins.vim-test</li>  </ul></details>

**Comment by teto** [comment]
I was not able to find the tests for sg.nvim but sniprun has some. For the next update, could you try to run its tests plz ? 
These plugins tend not to have releases (sniprun being the exception) and people use them with arbitrary nvims so it's nice to be able to run the tests for them.

I am trying to run the tests for plugins that use nvim as lua interpreter too for instance.

**Pull request merged**
