### PR TITLE
nixos/resilio: set rslsync gid

### PR DESCRIPTION
**Pull request by JakeHillion**
Resilio has a fixed ID in `ids.nix` but this isn't set by the NixOS module. Set this ID so it's consistent if `/var/lib/nixos` is discarded between boots.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [X] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by JakeHillion** [comment]
There are no maintainers listed for the nixos module, I am willing to add myself but not sure what the etiquette is there. Will tag the maintainers for the Nix package in a week or so if this doesn't get approval as it's a tiny bug fix.

**Comment by FliegendeWurst** [comment]
> There are no maintainers listed for the nixos module, I am willing to add myself but not sure what the etiquette is there.

You can add yourself as maintainer anywhere you want really. It is of course a good idea to also ask the maintainers of the package if they want to be maintainers too.

**Review by FliegendeWurst — COMMENTED** [review]
Does this change impact backward compatibility with existing installations? (e.g. if the service creates any permanent files where the group owner matters)

**Comment by JakeHillion** [comment]
> > There are no maintainers listed for the nixos module, I am willing to add myself but not sure what the etiquette is there.
> 
> You can add yourself as maintainer anywhere you want really. It is of course a good idea to also ask the maintainers of the package if they want to be maintainers too.

Thanks! I'll throw up a separate PR to do that, I do use this package quite extensively so I'd rather it had a maintainer attached.

> Does this change impact backward compatibility with existing installations? (e.g. if the service creates any permanent files where the group owner matters)

No, with one caveat. On a normal NixOS install you hit:

https://github.com/NixOS/nixpkgs/blob/b50cd02c4e76f111c38fe9ac11ff8ba326de416a/nixos/modules/config/update-users-groups.pl#L158 

I don't have an example for the GID line and don't want to break a host to get it, but for the UID version it shows up as:

`warning: not applying UID change of user ‘jake’ (1001 -> 1000) in /etc/passwd`

When you switch. The machine has picked a number the first time and it's stored in `/var/lib/nixos`, if you later set an explicit one in the NixOS config it's ignored to not mess up file ownership.

The caveat is running with impermanence, where you instead get warnings like:

```
trace: warning: environment.persistence:
    Neither /var/lib/nixos nor any of its parents are
    persisted. This means all users/groups without
    specified uids/gids will have them reassigned on
    reboot.
    The following users are missing a uid:
      dhcpcd
      heisenbridge
      nscd
      sshd
      systemd-oom

    The following groups are missing a gid:
      dhcpcd
      heisenbridge
      nscd
      podman
      rslsync
      sshd
      systemd-coredump
      systemd-oom
```

Impermenance with not-fixed IDs means the IDs are selected as if it is the first time every boot, deterministically for a given NixOS config. Any changes to the users or groups on a system have a chance of changing this ordering which can mess things up. There's no way of knowing which last ID was picked, so pinning here does have a chance of breaking users running impermanence who choose to not persist `/var/lib/nixos`. I still think this change is net-positive for those impermenance users (of which I am one).

Thanks for your review!

**Comment by FliegendeWurst** [comment]
Thanks for the detailed explanation!

**Review by FliegendeWurst — APPROVED** [review]

**Pull request merged**
