### PR TITLE
Update Haskell package set to Stackage Nightly 2021-01-02 (plus other fixes)

### PR DESCRIPTION
**Pull request by peti**
This PR is test-built by Hydra at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates. I'll fix up the remaining errors and merge it on Friday, 2021-01-08 20:00 +01:00. You can watch this live on Twitch at https://www.twitch.tv/peti343. In addition to the chat features offered by Twitch, there is also a voice conference at https://discord.gg/YTEa3XR that viewers can use to chat with me and with each other.

### CODE REVIEW

**Comment by cdepillabout** [comment]
I've rebased the `haskell-updates` branch on top of `master` in order to make sure that `haskell-updates` includes https://github.com/NixOS/nixpkgs/pull/108362.

That PR changes `configuration-common.nix`, so I wanted to make sure that someone doesn't change `configuration-common.nix` here in `haskell-updates`, and then there is a merge conflict when @peti goes to merge it in.

---------------------------------------------

This `haskell-updates` branch was originally at commit 32bfa8300d1 before I rebased, and is now at commit 97c61d6ddd4.

@peti If you don't want me to do this in the future, please let me know.

**Comment by peti** [comment]
@maralorn, it appears that `hls-explicit-imports-plugin` won't compile:

~~~
Preprocessing library for hls-explicit-imports-plugin-0.1.0.0..
Building library for hls-explicit-imports-plugin-0.1.0.0..
[1 of 1] Compiling Ide.Plugin.ExplicitImports ( src/Ide/Plugin/ExplicitImports.hs, dist/build/Ide/Plugin/ExplicitImports.o, dist/build/Ide/Plugin/ExplicitImports.dyn_o )

src/Ide/Plugin/ExplicitImports.hs:32:1: error:
    Could not find module ‘Ide.Plugin’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
32 | import Ide.Plugin
   | ^^^^^^^^^^^^^^^^^
~~~

If you have the chance to take a look, then that would be very much appreciated. If all else fails, I'll try to fix the error later tonight during the livestream.

**Comment by peti** [comment]
> @peti If you don't want me to do this in the future, please let me know.

Don't worry, just rebase as you see fit.

My approach is to do a normal merge of `master` into `haskell-updates` during the week because that typically won't cause merge conflicts for existing PRs (while re-basing sometimes does), but then I oftentimes do a final re-base on Friday, too, to straighten up and polish the commit history. Either way is fine, though.

**Comment by peti** [comment]
We'll merge https://github.com/NixOS/nixpkgs/pull/109011 next week.

**Pull request merged**
