### PR TITLE
oracle-instantclient: add instantclient-tools

### PR DESCRIPTION
**Pull request by cjab**
###### Motivation for this change

This adds the instantclient-tools package which includes tools for importing and exporting databases.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

@flokli

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 129706` at e3b72807 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/8c93bf0434a1352e0eea712af5f44888">perl530Packages.DBDOracle</a></li>
    <li><a href="https://gist.github.com/b4d3aed9cb021a45f354dbd5e1a77553">perl532Packages.DBDOracle</a></li>
    <li><a href="https://gist.github.com/8f2be68742047436f2f1d7ba7da24438">php74Extensions.oci8</a></li>
    <li><a href="https://gist.github.com/14e779b7a120072527de4ec8a6bd2bea">php74Extensions.pdo_oci</a></li>
    <li><a href="https://gist.github.com/6cbb368822b1f3fa0f8b29092719d4e1">php80Extensions.oci8</a></li>
    <li><a href="https://gist.github.com/e5fe912c2b0d2ff83db55ab9343cbd7a">php80Extensions.pdo_oci</a></li>
    <li><a href="https://gist.github.com/a9849f8190a4f289769c7e0557cb99fd">python38Packages.cx_oracle</a></li>
    <li><a href="https://gist.github.com/b52a4a1a2a45d933f567363d48ba8af7">python38Packages.patator</a></li>
    <li><a href="https://gist.github.com/530c7a02aaf7d415ef866b57cf2320cb">python39Packages.cx_oracle</a></li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by cjab** [comment]
> Result of `nixpkgs-review pr 129706` at [e3b7280](https://github.com/NixOS/nixpkgs/commit/e3b728074c0dca9c9ca5cc7bb36bb216dfe6b534) run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 
> 9 packages failed to build:
> * [perl530Packages.DBDOracle](https://gist.github.com/8c93bf0434a1352e0eea712af5f44888)
> * [perl532Packages.DBDOracle](https://gist.github.com/b4d3aed9cb021a45f354dbd5e1a77553)
> * [php74Extensions.oci8](https://gist.github.com/8f2be68742047436f2f1d7ba7da24438)
> * [php74Extensions.pdo_oci](https://gist.github.com/14e779b7a120072527de4ec8a6bd2bea)
> * [php80Extensions.oci8](https://gist.github.com/6cbb368822b1f3fa0f8b29092719d4e1)
> * [php80Extensions.pdo_oci](https://gist.github.com/e5fe912c2b0d2ff83db55ab9343cbd7a)
> * [python38Packages.cx_oracle](https://gist.github.com/a9849f8190a4f289769c7e0557cb99fd)
> * [python38Packages.patator](https://gist.github.com/b52a4a1a2a45d933f567363d48ba8af7)
> * [python39Packages.cx_oracle](https://gist.github.com/530c7a02aaf7d415ef866b57cf2320cb)
> 
> Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
> Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

Updated with the correct hashes for instantclient-tools-linux.x64-19.3.0.0.0dbru.zip.drv and instantclient-tools-macos.x64-19.3.0.0.0dbru.zip.drv

The other packages are fixed by this but `python39Packages.cx_oracle` is still failing. However, it appears to be broken before these changes.

**Comment by flokli** [comment]
I successfully built that and confirmed the tools where in `$out/bin`, and I could execute them.

**Comment by flokli** [comment]
Thanks for the contribution!

**Pull request merged**
