### PR TITLE
idrisPackages.sdl2: 2018-01-19 -> 0.1.1

### PR DESCRIPTION
**Pull request by steshaw**
Update to the latest release which unbreaks the package.

I'm happy to help maintain this package as I wrote the upstream package.

The previous version was broken but the current closure size is:

```sh-session
$ nix path-info -S -f . idrisPackages.sdl2
/nix/store/qwb0d8qh5mxfgrspjp0knlahfpkpy0kd-idris-sdl2-0.1.1        7096224
```

###### Motivation for this change

The package was set to `broken = true`. This change unbreaks it.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @brainrape

### CODE REVIEW

**Comment by Infinisil** [comment]
Nice! Can you add yourself as a maintainer in a separate first commit?

**Comment by steshaw** [comment]
> Nice! Can you add yourself as a maintainer in a separate first commit?

Done!

Oughtn't this convention be mentioned in some of:

- https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md
- https://github.com/NixOS/nixpkgs/blob/master/.github/PULL_REQUEST_TEMPLATE.md
- https://github.com/NixOS/nixpkgs/blob/master/doc/meta.xml

Probably CONTRIBUTING and the manual? PULL_REQUEST_TEMPLATE seems a little late.

I did a `git log maintainers/maintainer-list.nix` to see what the convention was. I'd be happy to put together another pull request to update the documentation—or raise an issue for discussion, if that's the process.

**Comment by Infinisil** [comment]
Oh, that would be great if that was mentioned somewhere. I think [this section](https://nixos.org/nixpkgs/manual/#chap-submitting-changes) in the nixpkgs manual would be a good fit, and the meta section could cross-link to it.

**Comment by steshaw** [comment]
Yes indeed, I just came back to mention:

- doc/submitting-changes.xml

There's a little bit of duplication with the manual, and .github files but sometimes it's a good idea. I'll see if I can find the time to submit a PR.

**Review by infinisil — APPROVED** [review]
PR looks good, thanks for the update :)

**Pull request merged**
