### PR TITLE
grpc-tools: init at 1.10.0

### LINKED ISSUE #93173: Packaging grpc-tools from grpc-node
**Project description**

The https://github.com/grpc/grpc-node repository has a number of GRPC related packages usable in the Node ecosystem.

In particular the https://github.com/grpc/grpc-node/tree/master/packages/grpc-tools tries to bring `grpc_tools_node_protoc` and `grpc_tools_node_protoc_plugin` for generating JS code from protobuf spec.

However it's using C++ code inside, and it's not really built by the `node-pre-gyp`. It only uses that `node-pre-gyp` to download a precompiled binary hosted on node-precompiled-binaries.grpc.io.

So this package doesn't work just be overriding from `node2nix` output.

```
{ pkgs ? import <nixpkgs> {} }:

let p = import ./nix/default.nix { pkgs = pkgs; };
in p.package.override (oldAttrs: {
  buildInputs = oldAttrs.buildInputs ++ [ pkgs.nodePackages.node-pre-gyp ];
})
```

The above does not work, with `nix-build`, and just produces:

```
> node-pre-gyp install

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: getaddrinfo ENOTFOUND node-precompiled-binaries.grpc.io
node-pre-gyp ERR! stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
node-pre-gyp ERR! System Linux 4.19.128
node-pre-gyp ERR! command "/nix/store/rcxlrj41836ps5iqv3jikqn6h7msbjpw-nodejs-12.15.0/bin/node" "/nix/store/hzw29a3cf0ync2mn4jbwd1x5sfpqdiwi-node_grpc-tools-1.9.0/lib/node_modules/grpc-tools/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /nix/store/hzw29a3cf0ync2mn4jbwd1x5sfpqdiwi-node_grpc-tools-1.9.0/lib/node_modules/grpc-tools
node-pre-gyp ERR! node -v v12.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.15.0
node-pre-gyp ERR! not ok
getaddrinfo ENOTFOUND node-precompiled-binaries.grpc.io
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc-tools@1.9.0 install: `node-pre-gyp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc-tools@1.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2020-07-15T11_46_32_675Z-debug.log

builder for '/nix/store/avrmmjcpa2yybrdv77n5w95q86dvsvjz-node_grpc-tools-1.9.0.drv' failed with exit code 1
error: build of '/nix/store/avrmmjcpa2yybrdv77n5w95q86dvsvjz-node_grpc-tools-1.9.0.drv' failed
```

So we need some help packaging the C++ in Nix.

**Metadata**

* homepage URL: https://github.com/grpc/grpc-node/tree/master/packages/grpc-tools
* source URL: https://github.com/grpc/grpc-node/tree/master/packages/grpc-tools
* license: APL2
* platforms: unix, linux, darwin, ...

### PR DESCRIPTION
**Pull request by nzhang-zh**
###### Motivation for this change

Fixes #93173

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
The cool thing about this package is that this scales with all the other possible GRPC tools that may come out that uses the same repository of `grpc-node`.

Note that we cannot compile with the protobuf that's already inside nixpkgs, it has to use the protobuf that's pinned in the repository due to version compatibility constraints.

**Comment by marsam** [comment]
I think you could write the expression as
```nix
{ lib
, stdenv
, cmake
, fetchFromGitHub
}:

stdenv.mkDerivation rec {
  pname = "grpc-tools";
  version = "1.10.0";

  src = fetchFromGitHub {
    owner = "grpc";
    repo = "grpc-node";
    rev = "3a094f01711942f79abd8a536c45a91b574d626f"; # version 1.10.0 was not tagged
    sha256 = "1a7l91kxc3g7mqfqvhc3nb7zy0n21ifs5ck0qqg09qh3f44q04xm";
    fetchSubmodules = true;
  };

  sourceRoot = "source/packages/grpc-tools";

  nativeBuildInputs = [ cmake ];

  installPhase = ''
    install -Dm755 -t $out/bin grpc_node_plugin
    install -Dm755 -t $out/bin deps/protobuf/protoc
  '';

  meta = with lib; {
    description = "Distribution of protoc and the gRPC Node protoc plugin for ease of installation with npm";
    longDescription = ''
      This package distributes the Protocol Buffers compiler protoc along with
      the plugin for generating client and service objects for use with the Node
      gRPC libraries.
    '';
    homepage = "https://github.com/grpc/grpc-node/tree/master/packages/grpc-tools";
    license = licenses.asl20;
    platforms = platforms.all;
    maintainers = [ maintainers.nzhang-zh ];
  };
}

```

**Comment by nzhang-zh** [comment]
@marsam Updated `default.nix` as suggested

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110659` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>grpc-tools</li>
</ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM, linked correctly

**Review by marsam — APPROVED** [review]

**Comment by tobiasBora** [comment]
Thanks for this, I need it to package robotframework-browser since I also get an error when automatically building grpc-tools from node (it tries to access internet), but it's not clear to me how I should use it? For reference here is the derivation I wrote so far https://discourse.nixos.org/t/grpc-tools-in-node-programs-tries-to-access-internet-while-building/66118

**Pull request merged**
