### PR TITLE
nbench: supply stdenv.glibc.static since Makefile uses -static

### PR DESCRIPTION
**Pull request by ghost**
ZHF: #172160

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

nbench's Makefile always compiles with -static, so we need it to be
able to see libc.a.  Let's add stdenv.glibc.static to the buildInputs.

### CODE REVIEW

**Comment by davidak** [comment]
Please squash the commits.

**Comment by Mindavi** [comment]
I squashed them in the github UI.

**Comment by davidak** [comment]
We usually create merge commits which are missing with this, that's why i haven't used it.

**Comment by a-m-joseph** [comment]
> We usually create merge commits which are missing with this, that's why i haven't used it.

I massively prefer squashing, it keeps the history readable and cherry-pickable (you can't `git cherry-pick` a merge commit).

Git merges were never meant to be used the way the github web UI uses them -- for applying patchsets.  Git merges were always meant for long-lived branches that get merged more than once, like our `staging` and `staging-next`.

Github pushes excessive use of merge commits because they don't like the fact that rebasing/cherrypicking a commit changes its hash.  This costs them more storage (less deduplication), but the real problem is that it breaks all their big data analytics.

**Comment by davidak** [comment]
I agree, but this is not the place to change the rules.

**Comment by a-m-joseph** [comment]
> I agree, but this is not the place to change the rules.

Oh, I didn't know there was a formal policy about this.  I've seen people merge my PRs using both styles.

**Comment by davidak** [comment]
It's even worse. There is an informal policy.
We should document a sane policy, so it's done consistently.
But not in this issue...

**Pull request merged**
