### PR TITLE
calibre: wrap manually

### PR DESCRIPTION
**Pull request by worldofpeace**
Also move wrapGAppsHook to nativeBuildInputs

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM (although not super familiar with Qt application packaging)
binaries seem to work
leaf package

I did notice that some of the applications don't get passed the right executable name (but the wrapped name), although this doesn't affect how they work:
```
[nix-shell:/home/jon/.cache/nix-review/pr-66483]$ ./results/calibre/bin/web2disk
Usage: .web2disk-wrapped URL

Where URL is for example https://google.com

Whenever you pass arguments to .web2disk-wrapped that have spaces in them, enclose the arguments in quotation marks. For example: "/some path/with spaces"

Options:
  --version             show program's version number and exit
...
```

**Comment by worldofpeace** [comment]
Yeah that's an unfortunate side-effect of how wrappers work.

**Comment by lilyball** [comment]
The executable name is because `wrapProgram` renames the original program from `foo` to `.foo-wrapped`. I wonder if it's worth changing `wrapProgram` to instead change it to something like `.wrapped/foo`, so the basename doesn't change. Conflicts would still have to be handled, right now they append extra `_`s to the name, so we could still end up with `.wrapped/foo_`, though I suppose `.wrapped_/foo` is also a possibility (though it might be weird to see).

**Comment by jonringer** [comment]
In a lot of wrapped programs, it displays correctly. I just wonder if the mechanism is something like __file__ in python where it doesn't reference $0

**Comment by lilyball** [comment]
`wrapProgram` will pass the original name as argv 0 to the program, but programs that use the platform-specific mechanism of reading the running executable name end up displaying the wrong name.

**Pull request merged**
