### PR TITLE
Fix asterisk & asterisk: 13.6.0 -> 14.1.2

### PR DESCRIPTION
**Pull request by DerTim1**
###### Motivation for this change
Bring back Asterisk Telephony Server to NixOS. #18856 

- Fix bug in skel creation
- Update to newest version
- Compile with modules lua, pjsip and format_mp3 (e.g. for musiconhold)
- Use /etc/asterisk instead of direct linkt to etc in nixstore (otherwise you have to restart asterisk to reload config changes)
- Add NixOS-Option to use some of the default config files.

Example Configuration to use Asterisk on NixOS could be something like this:
```
{ config, pkgs, lib, ... }:

{
  services.asterisk = {
    enable = true;
    # asterisk.conf here:
    extraConfig = ''
      [options]
      documentation_language = en_US

      [compat]
      pbx_realtime=1.6
      res_agi=1.6
      app_set=1.6

    '';
    confFiles = { # Put not asterisk.conf here
      "agents.conf" = builtins.readFile asterisk/conf/agents.conf;
      "dundi.conf" = builtins.readFile asterisk/conf/dundi.conf;
      "extensions.lua" = builtins.readFile asterisk/conf/extensions.lua;
      "manager.conf" = builtins.readFile asterisk/conf/manager.conf;
      "musiconhold.conf" = builtins.readFile asterisk/conf/musiconhold.conf;
      "sip.conf" = builtins.readFile asterisk/conf/sip.conf + builtins.readFile asterisk/conf/my-sip.conf;
      "voicemail.conf" = builtins.readFile asterisk/conf/voicemail.conf;
      "myconfig.conf" = ''
          ;;Some Asterisk options
      '';
    };
    # useTheseDefaultConfFiles = [
    #   "phone.conf"
    #   "unistim.conf"
    # ];
  };

  networking.firewall.allowedTCPPorts = [ 5060 5600 ];
  networking.firewall.allowedUDPPorts = [ 5060 5600 2048 2051 2727 4569 5036 53357 ];
  networking.firewall.allowedUDPPortRanges = [ { from = 10000; to = 20000; } ];
}
```

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
Woohoo! Thank you for bringing Asterisk back to life! I'll check this PR out, thank you :)

**Comment by joachifm** [comment]
@grahamc ping :)

**Review by fpletz — APPROVED** [review]

**Comment by makefu** [comment]
i'd love to see this module back in nixOS

**Comment by qknight** [comment]
thanks!

**Pull request merged**
