### PR TITLE
amoeba: xlibs -> xorg, fix borg

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change

what https://github.com/NixOS/nixpkgs/pull/104686 was supposed to be

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
I will let the ofborg CI finish this time

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 104697` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by jonringer** [comment]
now I remember why I would just run ofborg locally.. could wait up to 6+ hrs

**Comment by jonringer** [comment]
I'm going to merge this because I have to attend to other things, and I don't want ofborg permanently broken.

The diff looks right.

**Comment by SuperSandro2000** [comment]
> I'm going to merge this because I have to attend to other things (been almost 2 hours), and I don't want ofborg permanently broken.

Me neither. I try to keep an eye on it and try to hotfix if anything bubbles up.

**Comment by jonringer** [comment]
@SuperSandro2000 thanks

**Pull request merged**
