### PR TITLE
glibc: fix cross-build

### PR DESCRIPTION
**Pull request by Mic92**
glibc's buildsystem uses its own executables to generate locales.
This does not work for cross-compilation so instead we use localedef
from buildPackages.

cc @vcunat 

I only tested the build so far. Please verify that the cross-compiled archive also works. i.e. python

```
LOCALE_ARCHIVE= python -c 'import locale; locale.setlocale(locale.LC_ALL, "C.UTF-8")'
```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
Nitpick: as written, this shouldn't cause any rebuild for non-cross, so I'd expect to merge to master directly.

**Comment by Mic92** [comment]
@vcunat sure, you can cherry-pick it, if you tested the cross-compiled binaries.

**Comment by vcunat** [comment]
I did some very basic tests of running cross-compiled binaries with this, but not even any locale so far.

**Comment by lopsided98** [comment]
It seems like this should definitely go into master, since cross is completely broken right now, and we shouldn't have to wait for a staging merge to fix it.

**Comment by Mic92** [comment]
master: ff1b945851f778cb0c8f42faf5d5f4d931912e13

**Comment by Ericson2314** [comment]
Awesome!!

**Pull request merged**
