### PR TITLE
Some trivial enhancements to startkde

### PR DESCRIPTION
**Pull request by kirelagin**
@ttuegel

To be honest, I didn’t test any of this as I'm not currently using KDE, just thinking about getting back to it.

### CODE REVIEW

**Comment by kirelagin** [comment]
I just added one more commit and actually tested everything.
Well, it still doesn’t work for me (I’m trying to start a kde session on Gentoo, installing `startkde` into my user profile), but it totally looks like my commits didn’t break anything, at least I don’t see anything wrong in `startkde`’s debug output.

**Comment by ttuegel** [comment]
I agree we need to fix the `kdostartupconfig5` path. I don't want to make the shell changes because this is just a modified version of the script provided by upstream. Yes, "quotes should always be there," but if upstream *wants* weird stuff to happen, I want weird stuff to happen. I think the `GenericConfigLocation` change is OK, though.

**Comment by edolstra** [comment]
As an aside, why do we have our own startkde script? In KDE 4, this was part of the kde-workspace package...

**Comment by ttuegel** [comment]
@edolstra KDE provides startkde in plasma-workspace now. The script they provide must be heavily modified to work on NixOS. Rather than maintaining a big diff, I thought it would be easier just to package the modified script separately.

**Comment by kirelagin** [comment]
> I don't want to make the shell changes because this is just a modified version of the script provided by upstream. Yes, "quotes should always be there," but if upstream wants weird stuff to happen, I want weird stuff to happen.

Right, I initially read the comment and thought that the script is completely different from the upstream one. When I later started digging the upstream code I realised that this was almost the same but it was too late already =).

I’ll send my changes upstream then. Feel free to cherry-pick the other two commits for now.

**Comment by ttuegel** [comment]
I cherry-picked these into master yesterday, but I guess I forgot to close this pull request!

**Pull request closed without merging**
