### PR TITLE
wine: unstable 1.7.43 -> 1.7.45

### PR DESCRIPTION
**Pull request by bendlas**
cc @abbradar @7c6f434c

### CODE REVIEW

**Comment by jagajaga** [comment]
Rebase against current master, please.
And have you tested it yet?

**Comment by abbradar** [comment]
FWIW I've compiled it successfully some time ago but had a very hectic schedule then and forgot to test and merge, sorry.

**Comment by bendlas** [comment]
It seems wine-unstable has been bumped to `1.7.46` in the meantime. Yesterday, I've started a rebuild involving the current `1.7.47`. I suggest closing this PR and I'll later open one for `1.7.47` + the latest `winetricks`.

**Comment by vcunat** [comment]
Yeah, outdated and we have #8913 already.

**Pull request closed without merging**
