### PR TITLE
python3Packages.uvloop: 0.15.0 -> 0.15.1

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://github.com/MagicStack/uvloop/releases/tag/v0.15.1

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113219` at 06b323d4 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>32 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/80cd6785c000f89a74157278caeaf211">aiodnsbrute</a></li></li>
    <li><a href="https://gist.github.com/d2756962fa6a4031af986871ee0f8f4b">datasette</a></li> (python38Packages.datasette)</li>
    <li><a href="https://gist.github.com/24f500ba61b53ee9d48745e0f35fba7d">google-music-scripts</a></li></li>
    <li><a href="https://gist.github.com/f363d247c13f2fa5ea5c26fa076d092c">home-assistant</a></li></li>
    <li><a href="https://gist.github.com/8db30f176e59aa1badca7d5efa69c4cb">mtprotoproxy</a></li></li>
    <li><a href="https://gist.github.com/39ee8b275e8b1abe1d378b2ab2c10b89">python38Packages.PyRMVtransport</a></li></li>
    <li><a href="https://gist.github.com/5fe3460fff3125bfc6dfe3f46ab924c2">python38Packages.aioextensions</a></li></li>
    <li><a href="https://gist.github.com/7644c327393ae489a447d445d93565bf">python38Packages.aiorun</a></li></li>
    <li><a href="https://gist.github.com/00b1a81804745d33f6c34e60d23cb4d7">python38Packages.anyio</a></li></li>
    <li><a href="https://gist.github.com/345cfb01f42080bc9f616a67683c015f">python38Packages.asyncpg</a></li></li>
    <li><a href="https://gist.github.com/fc44bd780c0b5d91786280cb2279349f">python38Packages.axis</a></li></li>
    <li><a href="https://gist.github.com/a7a9c4c7cd314c1a2796c824786009fe">python38Packages.databases</a></li></li>
    <li><a href="https://gist.github.com/3f4455181b3ad6a1e80e359f15c427eb">python38Packages.entrance</a></li></li>
    <li><a href="https://gist.github.com/edb4ab1f985c9c9f8aa57864485fda98">python38Packages.entrance-with-router-features</a></li></li>
    <li><a href="https://gist.github.com/6ff56a9a845b56661704c7a6f2fc2ed6">python38Packages.fastapi</a></li></li>
    <li><a href="https://gist.github.com/d8f8110c7f9647a5f2725ed68c0cf93b">python38Packages.google-music</a></li></li>
    <li><a href="https://gist.github.com/a982d345811f808ced2d9b91c6160e8d">python38Packages.httpcore</a></li></li>
    <li><a href="https://gist.github.com/ededa21b6f349d2b0a977c549382f27a">python38Packages.httpx</a></li></li>
    <li><a href="https://gist.github.com/917f1bb8bdcd782a42589ed953319630">python38Packages.ircrobots</a></li></li>
    <li><a href="https://gist.github.com/9158bbd9553b9ab9ed1fa402ca276b5d">python38Packages.orm</a></li></li>
    <li><a href="https://gist.github.com/49da000641b04e1087d51fc0b5c1b9bf">python38Packages.pproxy</a></li></li>
    <li><a href="https://gist.github.com/eb7cfa848560d12d5be065b2edf172ef">python38Packages.qiskit</a></li></li>
    <li><a href="https://gist.github.com/b12d5130bbf037a7e65d7b9e1a8c4edb">python38Packages.qiskit-ibmq-provider</a></li></li>
    <li><a href="https://gist.github.com/d30cecc8af546e5048e3392406f8a75d">python38Packages.respx</a></li></li>
    <li><a href="https://gist.github.com/5bd4df912100297e47aaf376896be6d1">python38Packages.sanic</a></li></li>
    <li><a href="https://gist.github.com/96aaf9b584faf8333851505e5568b472">python38Packages.sanic-auth</a></li></li>
    <li><a href="https://gist.github.com/fb5978d81771aed22b119edf324e089f">python38Packages.slack-sdk</a></li></li>
    <li><a href="https://gist.github.com/e6b3659a216074afd979bbec01bf198f">python38Packages.starlette</a></li></li>
    <li><a href="https://gist.github.com/7f1934facbbcca2eb8e94a3f939b3b0d">python38Packages.uvicorn</a></li></li>
    <li><a href="https://gist.github.com/3714e8a66d41329399e41118608703e5">python38Packages.uvloop</a></li></li>
    <li><a href="https://gist.github.com/57f81bc97348e552826ed8514e58cacb">sourcehut.listssrht</a></li></li>
    <li><a href="https://gist.github.com/b707e4710ac7f28c2c062b478d59eb3c">theharvester</a></li></li>
  </ul>
</details>
<details>
  <summary>37 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/9c0adf751ad54e2c9cc2e98c6be4cc0c">python37Packages.PyRMVtransport</a></li></li>
    <li><a href="https://gist.github.com/9ee1276063e91cb2b981a73c28357414">python37Packages.aioextensions</a></li></li>
    <li><a href="https://gist.github.com/7e54f6b02efb8164603f4ba74ff7f72a">python37Packages.aiorun</a></li></li>
    <li><a href="https://gist.github.com/1d76ecd1c3670da0b9378c53be3119df">python37Packages.anyio</a></li></li>
    <li><a href="https://gist.github.com/877170c469fb6eafa7cae93084299755">python37Packages.asyncpg</a></li></li>
    <li><a href="https://gist.github.com/2b8ce527507ef65f997303618e8636c1">python37Packages.axis</a></li></li>
    <li><a href="https://gist.github.com/f8111d4eb5460b4fe4a016aea4e0df6d">python37Packages.databases</a></li></li>
    <li><a href="https://gist.github.com/dffcd0d6ae4684034b25a5bebbe57e5c">python37Packages.datasette</a></li></li>
    <li><a href="https://gist.github.com/d74325733a3a31e83f8451cc8e693237">python37Packages.entrance</a></li></li>
    <li><a href="https://gist.github.com/5db58af062262dc22642bdb329aa1f42">python37Packages.entrance-with-router-features</a></li></li>
    <li><a href="https://gist.github.com/941c38170b72c43bd277f26218b6f248">python37Packages.fastapi</a></li></li>
    <li><a href="https://gist.github.com/16c32179afaf6d7a8d9839d07dac0a29">python37Packages.google-music</a></li></li>
    <li><a href="https://gist.github.com/d283b166ceed560c02ee094adf69d83a">python37Packages.httpcore</a></li></li>
    <li><a href="https://gist.github.com/34f417345608417355f7f1eb73f31fd5">python37Packages.httpx</a></li></li>
    <li><a href="https://gist.github.com/4a55de76d0be28af2d71569c140a461e">python37Packages.ircrobots</a></li></li>
    <li><a href="https://gist.github.com/47119dc1fb3c7e16e3aa3f0fc854bfb6">python37Packages.orm</a></li></li>
    <li><a href="https://gist.github.com/bf55ab0059ae0cf04782469391fb6d1b">python37Packages.pproxy</a></li></li>
    <li><a href="https://gist.github.com/64916e1a9ebb6579fdd258d288beb70c">python37Packages.qiskit</a></li></li>
    <li><a href="https://gist.github.com/2864c6b20df963a9dab3838a1eaa73d5">python37Packages.qiskit-ibmq-provider</a></li></li>
    <li><a href="https://gist.github.com/3f09c439c5a38e61b4b5d4e1e140eac2">python37Packages.respx</a></li></li>
    <li><a href="https://gist.github.com/9318755b62a3337cbaa4131dac8335a6">python37Packages.sanic</a></li></li>
    <li><a href="https://gist.github.com/d6b5d5d925195a3666b021a5307ac267">python37Packages.sanic-auth</a></li></li>
    <li><a href="https://gist.github.com/a688c27d798f489c60adef9935faac96">python37Packages.slack-sdk</a></li></li>
    <li><a href="https://gist.github.com/b21933843931cbad4e535a9cd5dc71a1">python37Packages.starlette</a></li></li>
    <li><a href="https://gist.github.com/931be705620c1f93a6dedbdabbf1d33f">python37Packages.uvicorn</a></li></li>
    <li><a href="https://gist.github.com/54c1bfac753150d5c2ae9fc2ef15c43d">python37Packages.uvloop</a></li></li>
    <li><a href="https://gist.github.com/5d3dc976cf32b2f257054b0a03d7db25">python39Packages.aioextensions</a></li></li>
    <li><a href="https://gist.github.com/96ad7a682175fd692e8d25c21192d1f1">python39Packages.aiorun</a></li></li>
    <li><a href="https://gist.github.com/60ae56e9b20e09420e55a84edbb2e67f">python39Packages.asyncpg</a></li></li>
    <li><a href="https://gist.github.com/13b994175a6455992eb8887ecc1e657b">python39Packages.databases</a></li></li>
    <li><a href="https://gist.github.com/654725d0d8f2dcbbd3462af2096df873">python39Packages.httpcore</a></li></li>
    <li><a href="https://gist.github.com/52cd24b0aa271459fc3847832c7f27d1">python39Packages.orm</a></li></li>
    <li><a href="https://gist.github.com/c4a75530f64df9543d655995b63e4408">python39Packages.pproxy</a></li></li>
    <li><a href="https://gist.github.com/52ae6864ad107f8f70f52dd4cee43b4e">python39Packages.slack-sdk</a></li></li>
    <li><a href="https://gist.github.com/0f411884f33301a9f61cab93af726dcc">python39Packages.starlette</a></li></li>
    <li><a href="https://gist.github.com/6f55b1f8ca1ec354e1d08849b295f1f4">python39Packages.uvicorn</a></li></li>
    <li><a href="https://gist.github.com/1a764e72a0df108b20a07bb27922a8f3">python39Packages.uvloop</a></li></li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 113219` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>python37Packages.entrance</li>
    <li>python37Packages.entrance-with-router-features</li>
    <li>python37Packages.qiskit</li>
    <li>python37Packages.sanic</li>
    <li>python37Packages.sanic-auth</li>
    <li>python38Packages.qiskit</li>
    <li>python38Packages.slack-sdk</li>
  </ul>
</details>
<details>
  <summary>62 packages built:</summary>
  <ul>
    <li>aiodnsbrute</li>
    <li>datasette (python38Packages.datasette)</li>
    <li>google-music-scripts</li>
    <li>home-assistant</li>
    <li>mtprotoproxy</li>
    <li>python37Packages.PyRMVtransport</li>
    <li>python37Packages.aioextensions</li>
    <li>python37Packages.aiorun</li>
    <li>python37Packages.anyio</li>
    <li>python37Packages.asyncpg</li>
    <li>python37Packages.axis</li>
    <li>python37Packages.databases</li>
    <li>python37Packages.datasette</li>
    <li>python37Packages.fastapi</li>
    <li>python37Packages.google-music</li>
    <li>python37Packages.httpcore</li>
    <li>python37Packages.httpx</li>
    <li>python37Packages.ircrobots</li>
    <li>python37Packages.orm</li>
    <li>python37Packages.pproxy</li>
    <li>python37Packages.qiskit-ibmq-provider</li>
    <li>python37Packages.respx</li>
    <li>python37Packages.slack-sdk</li>
    <li>python37Packages.starlette</li>
    <li>python37Packages.uvicorn</li>
    <li>python37Packages.uvloop</li>
    <li>python38Packages.PyRMVtransport</li>
    <li>python38Packages.aioextensions</li>
    <li>python38Packages.aiorun</li>
    <li>python38Packages.anyio</li>
    <li>python38Packages.asyncpg</li>
    <li>python38Packages.axis</li>
    <li>python38Packages.databases</li>
    <li>python38Packages.entrance</li>
    <li>python38Packages.entrance-with-router-features</li>
    <li>python38Packages.fastapi</li>
    <li>python38Packages.google-music</li>
    <li>python38Packages.httpcore</li>
    <li>python38Packages.httpx</li>
    <li>python38Packages.ircrobots</li>
    <li>python38Packages.orm</li>
    <li>python38Packages.pproxy</li>
    <li>python38Packages.qiskit-ibmq-provider</li>
    <li>python38Packages.respx</li>
    <li>python38Packages.sanic</li>
    <li>python38Packages.sanic-auth</li>
    <li>python38Packages.starlette</li>
    <li>python38Packages.uvicorn</li>
    <li>python38Packages.uvloop</li>
    <li>python39Packages.aioextensions</li>
    <li>python39Packages.aiorun</li>
    <li>python39Packages.asyncpg</li>
    <li>python39Packages.databases</li>
    <li>python39Packages.httpcore</li>
    <li>python39Packages.orm</li>
    <li>python39Packages.pproxy</li>
    <li>python39Packages.slack-sdk</li>
    <li>python39Packages.starlette</li>
    <li>python39Packages.uvicorn</li>
    <li>python39Packages.uvloop</li>
    <li>sourcehut.listssrht</li>
    <li>theharvester</li>
  </ul>
</details>

**Comment by fabaff** [comment]
The qiskit failures will be fixed with #112625.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 113219` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
7 packages marked as broken and skipped:
</summary>
<ul>
<li>python37Packages.fastapi</li>
<li>python37Packages.starlette</li>
<li>python38Packages.fastapi</li>
<li>python38Packages.starlette</li>
<li>python39Packages.fastapi</li>
<li>python39Packages.google-music</li>
<li>python39Packages.starlette</li>
</ul>
</details>
<details>

  <summary>8 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.aioextensions: log <a href="https://termbin.com/kys0c">https://termbin.com/kys0c</a></li>
<li>python37Packages.qiskit: log was empty</li>
<li>python37Packages.slack-sdk: log <a href="https://termbin.com/j6x8">https://termbin.com/j6x8</a></li>
<li>python38Packages.aioextensions: log <a href="https://termbin.com/1gu8">https://termbin.com/1gu8</a></li>
<li>python38Packages.qiskit: log was empty</li>
<li>python38Packages.slack-sdk: log <a href="https://termbin.com/icny1">https://termbin.com/icny1</a></li>
<li>python39Packages.aioextensions: log <a href="https://termbin.com/7pr0">https://termbin.com/7pr0</a></li>
<li>python39Packages.slack-sdk: log <a href="https://termbin.com/sg3v">https://termbin.com/sg3v</a></li>
  </ul>
</details>
<details>
<summary>
67 packages built:
</summary>
<ul>
<li>aiodnsbrute</li>
<li>datasette (python38Packages.datasette)</li>
<li>google-music-scripts</li>
<li>home-assistant</li>
<li>mtprotoproxy</li>
<li>python37Packages.PyRMVtransport</li>
<li>python37Packages.aiorun</li>
<li>python37Packages.anyio</li>
<li>python37Packages.asyncpg</li>
<li>python37Packages.axis</li>
<li>python37Packages.databases</li>
<li>python37Packages.datasette</li>
<li>python37Packages.entrance</li>
<li>python37Packages.entrance-with-router-features</li>
<li>python37Packages.google-music</li>
<li>python37Packages.httpcore</li>
<li>python37Packages.httpx</li>
<li>python37Packages.ircrobots</li>
<li>python37Packages.orm</li>
<li>python37Packages.pproxy</li>
<li>python37Packages.qiskit-ibmq-provider</li>
<li>python37Packages.respx</li>
<li>python37Packages.sanic</li>
<li>python37Packages.sanic-auth</li>
<li>python37Packages.uvicorn</li>
<li>python37Packages.uvloop</li>
<li>python38Packages.PyRMVtransport</li>
<li>python38Packages.aiorun</li>
<li>python38Packages.anyio</li>
<li>python38Packages.asyncpg</li>
<li>python38Packages.axis</li>
<li>python38Packages.databases</li>
<li>python38Packages.entrance</li>
<li>python38Packages.entrance-with-router-features</li>
<li>python38Packages.google-music</li>
<li>python38Packages.httpcore</li>
<li>python38Packages.httpx</li>
<li>python38Packages.ircrobots</li>
<li>python38Packages.orm</li>
<li>python38Packages.pproxy</li>
<li>python38Packages.qiskit-ibmq-provider</li>
<li>python38Packages.respx</li>
<li>python38Packages.sanic</li>
<li>python38Packages.sanic-auth</li>
<li>python38Packages.uvicorn</li>
<li>python38Packages.uvloop</li>
<li>python39Packages.PyRMVtransport</li>
<li>python39Packages.aiorun</li>
<li>python39Packages.anyio</li>
<li>python39Packages.asyncpg</li>
<li>python39Packages.axis</li>
<li>python39Packages.databases</li>
<li>python39Packages.datasette</li>
<li>python39Packages.entrance</li>
<li>python39Packages.entrance-with-router-features</li>
<li>python39Packages.httpcore</li>
<li>python39Packages.httpx</li>
<li>python39Packages.ircrobots</li>
<li>python39Packages.orm</li>
<li>python39Packages.pproxy</li>
<li>python39Packages.respx</li>
<li>python39Packages.sanic</li>
<li>python39Packages.sanic-auth</li>
<li>python39Packages.uvicorn</li>
<li>python39Packages.uvloop</li>
<li>sourcehut.listssrht</li>
<li>theharvester</li>
</ul>
</details>

probably darwin sandbox issues

**Comment by mweinelt** [comment]
> 8 packages failed to build and are new build failures:

Still not true. https://hydra.nixos.org/eval/1649098?filter=qiskit&compare=1649077&full=#tabs-still-fail

**Comment by rmcgibbo** [comment]
Looks like this is not building on hydra for aarch64-linux: https://hydra.nixos.org/job/nixpkgs/trunk/python38Packages.uvloop.aarch64-linux. Is that a known issue?

**Comment by mweinelt** [comment]
Even before this upgrade, since the first broken build was 0.15.0.

**Pull request merged**
