### PR TITLE
podman-desktop: 0.12.0 -> 1.13.2

### LINKED ISSUE #343328: Build failure: podman-desktop @0.12.0 on Darwin
### Steps To Reproduce

1. `nix-build -A podman-desktop` on Darwin

### Build log

https://gist.github.com/sarahec/9dbccc59ecce22cb7994390a6d8d8938

### Notify maintainers

@panda2134 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.0.0, macOS 15.0`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by booxter**
This also fixes a build failure on darwin due to read-only permissions on some Electron.app files, which apparently breaks electron-builder.

Closes: #343328

## Description of changes

- Bump the version to the latest release.
- Sign the macos app with a hook.
- Don't use desktopToDarwinBundle for Darwin.
- Switched from yarn to pnpm.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [X] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by panda2134** [comment]
Looks good to me.

**Review by panda2134 — APPROVED** [review]
Looks good.

**Comment by booxter** [comment]
The `passthru` tests for linux fail with permission denied when building the Electron bundle too:

```
  ⨯ EACCES: permission denied, open '/build/source-patched/dist/linux-unpacked/podman-desktop'  failedTask=build stackTrace=Error: EACCES: permission denied, open '/build/source-patched/dist/linux-unpacked/podman-desktop'
```

I wonder if perhaps the "ugly hack" to fix it with `chmod` will have to be applied for all platforms.

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 343648`

---
### `x86_64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>podman-desktop</li>
  </ul>
</details>

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 343648`

**Comment by khaneliman** [comment]
For some reason, it's also not detecting a darwin rebuild.

**Comment by khaneliman** [comment]
> mv: missing destination file operand after '/nix/store/mg2p3sanr09glbkc8r5l4yin3m810g77-podman-desktop-1.12.0/Applications'

x86-darwin ofborg error

**Comment by booxter** [comment]
Fixed mac x86 build (the directory is just `dist/mac` in this case). Applying chmod hack for linux, since it looks like the error is otherwise identical to darwin.

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 343648`

---
### `x86_64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>podman-desktop</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>podman-desktop</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>podman-desktop</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>podman-desktop</li>
  </ul>
</details>

**Comment by booxter** [comment]
Both linux builds fail with:

```
Error: getaddrinfo EAI_AGAIN registry.npmjs.org
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
Emitted 'error' event on ClientRequest instance at:
    at emitErrorEvent (node:_http_client:108:11)
    at TLSSocket.socketErrorListener (node:_http_client:511:5)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'registry.npmjs.org'
}
```

which I think is a sign that networking is sandboxed for these builders (but not for macos); so they probably fail to fetch something from npmjs registry to build the offline deps bundle. I am not sure how this is supposed to be tackled on packaging side. Any advice is welcome.

**Comment by booxter** [comment]
I don't understand how any package relying on `prefetch-yarn-deps` could ever build without DNS / fetching from NPM. Isn't it the whole point of the derivation - to fetch packages from registry (and then make sure that SHA is as expected)?

**Comment by booxter** [comment]
It's currently failing locally with

```
cp: cannot stat '/nix/store/8kfqm2hacl3s6zydjayw3lhk6p9gcx7v-electron-unwrapped-32.1.2/libexec/electron/Electron.app': No such file or directory
```

 I will need to attend to this, though I still don't understand why DNS fails in ofborg. When I have a linux fix, we'll see if ofborg is any happier then.

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 343648`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>podman-desktop</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>podman-desktop</li>
  </ul>
</details>

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 343648`

**Comment by khaneliman** [comment]
Detecting no rebuild for darwin, for some reason. Going to manually build.

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 343648`

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>podman-desktop</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>podman-desktop</li>
  </ul>
</details>

**Review by khaneliman — APPROVED** [review]
LGTM 
image

**Pull request merged**
