### PR TITLE
write-qt-apps-hook.sh: use make-binary-wrapper for significant speedups

### LINKED ISSUE #225871: wrap-qt-apps-hooks leads to very slow wrapper scripts
### Describe the bug

Wrapper scripts for plasma apps such as `krunner` or `plasma-emojier` are slow. For example, executing just the wrapper for `plasma-emojier` takes 100ms on my fast machine. 

The reason for slowness is that the wrapper itself repeatedly adds various paths:

```console
$ rg -F "QT_PLUGIN_PATH='" $(which plasma-emojier) | wc -l
44
```

This leads to quadratic behavior. Profiling with perf shows that the bulk of the time is spend in string manipulation routines.

The relevant logic is here:

https://github.com/NixOS/nixpkgs/blob/07ab967e1c3e1e8a4f2fb08fcff1fecf585ebe69/pkgs/development/libraries/qt-6/hooks/wrap-qt-apps-hook.sh#L43

Essentially, we are calling 

```bash
wrapProgram program \
  --prefix QT_PLUGIN_PATH ...
  --prefix QT_PLUGIN_PATH ...
  --prefix QT_PLUGIN_PATH ...
```

and `makeWrapper` then faithfully translates each `--prefix`, instead of pre-computing thee concatenation. 

### Steps To Reproduce

```console
# Strip the `exec` line
$ <$(which plasma-emojier) head -n -1 > wrapper.sh && chmod a+x ./wrapper.sh

# Time the execution of the wrapper itself
$ time ./wrapper.sh
real	0m0.117s  😱
user	0m0.115s
sys	0m0.002s
```

### Expected behavior

Wrapper itself shouldn't take more than a handful of milliseconds. It seems achievable if I manually replace incremental quadratic addition to environmental variables with setting them once.

Not sure what's the best fix here, some options I see are:

* fix `wrap-qt-apps-hook` to pre-concatenate variables and pass just a single `--prefix` argument per variable to `wrapProgram`
* make `wrapProgram` itself smarter and teach it to collate identical prefixes
* fix `wrap-qt-apps-hook` to use `--set` rather then `--prefix`

As I don't know bash, I don't plan on working on the fix myself

### Notify maintainers

cc @ttuegel 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[matklad@Ishmael:~/tmp]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.10, NixOS, 23.05 (Stoat), 23.05.20230411.3fb8eed`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(matklad): `""`
 - nixpkgs: `/nix/store/k9vs66va04886gl91m6lpcwaymqiihqx-9lkm36ac7hfl7f9h2z9dj00mdh30mjhi-source`
```

### PR DESCRIPTION
**Pull request by matklad**
###### Description of changes

QT apps tend to call makeWrapper with a lot of arguments, which causes noticable slowdowns (+100ms for app startup). The slow down boils down to two reasons:

- the required string processing is O(N^2)
- bash is slow at doing the processing

By using the binary wrapper, we fix the second point, brining the overhead down from 100ms to just 4ms or thereabouts.

I tested this change by rebuilding my whole system with it (I use plasma). It booted and it works (that's where I type this commit message), but I am not 100% sure if this won't break anything else.

Closes: #225871

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]
Should be none breaking if all arguments are supported. Probably needs to go to staging.

**Comment by matklad** [comment]
Can I change the base branch to `staging` in GitHub UI? Or is it better to close this PR and open the new one? This indeed should target staging, as it rebuilds every QT app

**Comment by SuperSandro2000** [comment]
This PR rebuilds a lot of packages which means we must target staging. Please follow the [contributing guide](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging) to not potentially ping a lot of people.

**Comment by SuperSandro2000** [comment]
> Should be fine, but I'd probably keep this for after 23.05 as it's the kind of change that has spooky implications.

If all things build, this should just work but it could be that some things use flags not supported by the binary wrapper which would trigger a build failure. binary wrapper is already used by wrapGAppsHook and more things on darwin due to that the shebang must be a binary.

**Comment by K900** [comment]
I'm expecting it to be fine, but will it be "last staging cycle before release" fine? I'm less confident.

**Review by RaitoBezarius — APPROVED** [review]
Let's try, but we should revert in case of large issues.

**Comment by oxalica** [comment]
Is there any plan to simplify the wrapper logic? Is it possible? It is not only slow but also as big as ~40KB for one bash wrapper (`stat -L $(which dolphin)`).

**Comment by SuperSandro2000** [comment]
Do you mean the binary or the shell wrapper? The binary wrapper should already be a lot more optimized. The shell wrapper could probably be greatly optimized if we didn't check for every entry if the first and final : are there but since we want to deduplicate the entries it will probably stay longish. Maybe we could try to reduce the amount of entries added or symlinkJoin beforehand.

**Comment by K900** [comment]
I think tdesktop is broken now?

```
❄ ❯ objdump -x =telegram-desktop
objdump: warning: /run/current-system/sw/bin/telegram-desktop has a section extending past end of file
objdump: /run/current-system/sw/bin/telegram-desktop: file format not recognized
```

**Comment by SuperSandro2000** [comment]
I encountered the same

```
 ➜ strace telegram-desktop
execve("/etc/profiles/per-user/user/bin/telegram-desktop", ["telegram-desktop"], 0x7fff4612eaf0 /* 175 vars */) = 0
brk(NULL)             = 0x2143000
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffe7105f100) = -1 EINVAL (Invalid argument)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x8} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

**Comment by K900** [comment]
Never mind, tdesktop shoots itself in the foot: #228410

**Comment by wentasah** [comment]
Fix for `gnuplot_qt` is in #229479. Can someone review it?

**Comment by K900** [comment]
A better fix is already in staging: https://github.com/NixOS/nixpkgs/pull/229154

**Pull request merged**
