### PR TITLE
Regenerate R modules and update mirrors

### PR DESCRIPTION
**Pull request by abbradar**
Travis check.

### CODE REVIEW

**Comment by abbradar** [comment]
Oh the second thought, this is not a "trivial change" -- would someone who is involved with R-on-Nix care to comment on whether these kinds of updates are good to just push?

**Comment by abbradar** [comment]
cc @peti @taku0 (sorry if I cc'd a wrong person). Any comments/hidden issues with bumping R packages?

**Comment by peti** [comment]
@abbradar, I can run test builds of the updated package set at http://hydra.cryp.to/jobset/nixpkgs/r-packages, but before I do it's important to make sure that the updated code actually evaluates. A simple way to test that is to run:

    $ nix-env -qaP -A rPackages

Sometimes obsolete packages disappear from the set, but the `default.nix` still contains code that refers to the (now non-existent) attribute.

**Comment by abbradar** [comment]
@peti, I've run this on my own Hydra (mainly to be able to force-eval for faster development cycle). A day later, all errors fixed!
https://abbradar.net/hydra/jobset/nixpkgs/r-packages#tabs-evaluations

**Comment by abbradar** [comment]
Done! Please, review.

**Comment by peti** [comment]
@abbradar, great job, thank you very much!

**Pull request merged**
