### PR TITLE
pythonPackages.django-simple-captcha: init at 0.5.12

### PR DESCRIPTION
**Pull request by schmittlauch**
###### Motivation for this change

This PR succeeds #64523 which has somehow stalled and is based on @MrMebelMan's work.
After approval it probably needs to be squashed into 1 commit, but I wanted to keep the history intact so far.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by jonringer — CHANGES_REQUESTED** [review]
each package addition should include the additional entry to python-packages. I would also squash the other "enhance" commit into the first simple-captcha bump. Your commit history should be:
```
pythonPackages.django-simple-captcha: init at 0.5.6
pythonPackages.django-ranged-response: init at 0.2.0
```

**Comment by schmittlauch** [comment]
@jonringer Done, commit history adjusted to your requests.

**Review by jonringer — COMMENTED** [review]
otherwise LGTM

NIT: the ordering of the packages should probably go in a separate commit, as that's much more likely to cause merge conflicts if these packages needed to be cherry-picked

**Comment by schmittlauch** [comment]
@jonringer all done.
I also formatted both expressions with `nixpkgs-nixfmt`.

**Comment by jonringer** [comment]
do you mind resolving conflicts and rebasing?

**Comment by schmittlauch** [comment]
@jonringer done

**Review by jonringer — APPROVED** [review]
diff LGTM
commits LGTM

failure unrelated to PR (python38Packages.aiohttp is broken)
```
[9 built, 9 copied (134.2 MiB), 24.3 MiB DL]
https://github.com/NixOS/nixpkgs/pull/76515
6 package built:
python27Packages.django-ranged-response python27Packages.django-simple-captcha python37Packages.django-ranged-response python37Packages.django-simple-captcha python38Packages.django-ranged-response python38Packages.django-simple-captcha
```

**Comment by jonringer** [comment]
@GrahamcOfBorg build python27Packages.django-ranged-response python27Packages.django-simple-captcha python37Packages.django-ranged-response python37Packages.django-simple-captcha python38Packages.django-ranged-response python38Packages.django-simple-captcha

**Comment by schmittlauch** [comment]
@jonringer FYI: All builds went through

**Comment by jonringer** [comment]
sorry about that, don't have as much free time as i used to

**Comment by schmittlauch** [comment]
@jonringer Don't worry, that's why I pinged you. Glad that was okay.

**Pull request merged**
