### PR TITLE
nixopsUnstable: 1.7pre2764_932bf4 -> 2.0.0-pre

### PR DESCRIPTION
**Pull request by adisbladis**
###### Motivation for this change
This is a an early draft of what NixOps 2.0 plugin management could look like based on https://github.com/NixOS/nixops/pull/1256.

This adds a new top-level attribute `nixops2Unstable` that has a function called `withPlugins`.

To build NixOps with the AWS plugin enabled (the only one packaged so far) you'd use this expression:
``` nix
nixops2Unstable.withPlugins (
  ps: [
    ps.nixopsaws
  ]
)
```
Where `ps` is the pythonPackages set created for `nixops2Unstable`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @grahamc @AmineChikhaoui

### CODE REVIEW

**Comment by tewfik-ghariani** [comment]
Can this PR be reviewed please?

**Comment by tewfik-ghariani** [comment]
@adisbladis  I was wondering what would be required to build nixops 2.0 in Hydra? Would we need to bring back the 'release.nix'?

**Comment by roberth** [comment]
I'd expect these files to go in `pkgs/applications/networking/cluster/`, alongside `terraform` and `docker-machine`.
A clustered networking application isn't super accurate, but at least consistent with similar apps. NixOps certainly isn't a package management tool.

Perhaps it needs a lockfile update because it's been six months

Other than these two things it looks good to me.

**Comment by adisbladis** [comment]
> I'd expect these files to go in pkgs/applications/networking/cluster/, alongside terraform and docker-machine.

Indeed that makes more sense. I'll keep the old (nixops1) around where it is, but I'll move this new attribute elsewhere.

**Comment by aanderse** [comment]
Thank you @adisbladis :heart:

**Pull request merged**
