### PR TITLE
python3Packages.nexia: 0.9.10 -> 0.9.11

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 0.9.11

- Related Home Assistant change: https://github.com/home-assistant/core/pull/53534
- Target Home Assistant release: current (only dependency update, no code changes)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 131614` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.nexia</li>
    <li>python39Packages.nexia</li>
  </ul>
</details>

**Comment by siraben** [comment]
```
Successfully installed homeassistant-2021.7.4
/tmp/nix-build-homeassistant-2021.7.4.drv-0/source
Finished executing pipInstallPhase
@nix { "action": "setPhase", "phase": "fixupPhase" }
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/j0xhm8x1nw07d7dz75jvchcjg7ff72z4-homeassistant-2021.7.4
patching script interpreter paths in /nix/store/j0xhm8x1nw07d7dz75jvchcjg7ff72z4-homeassistant-2021.7.4
checking for references to /tmp/nix-build-homeassistant-2021.7.4.drv-0/ in /nix/store/j0xhm8x1nw07d7dz75jvchcjg7ff72z4-homeassistant-2021.7.4...
Rewriting #!/nix/store/yqjhkdarf7p74wcha7aypzsb751n7wl2-python3-3.9.5/bin/python3.9 to #!/nix/store/yqjhkdarf7p74wcha7aypzsb751n7wl2-python3-3.9.5
wrapping `/nix/store/j0xhm8x1nw07d7dz75jvchcjg7ff72z4-homeassistant-2021.7.4/bin/hass'...
Executing pythonRemoveTestsDir
Finished executing pythonRemoveTestsDir
@nix { "action": "setPhase", "phase": "installCheckPhase" }
running install tests
no Makefile or custom installCheckPhase, doing nothing
@nix { "action": "setPhase", "phase": "pythonCatchConflictsPhase" }
pythonCatchConflictsPhase
@nix { "action": "setPhase", "phase": "pythonRemoveBinBytecodePhase" }
pythonRemoveBinBytecodePhase
@nix { "action": "setPhase", "phase": "pythonImportsCheckPhase" }
pythonImportsCheckPhase
Executing pythonImportsCheckPhase
@nix { "action": "setPhase", "phase": "pytestCheckPhase" }
pytestCheckPhase
Executing pytestCheckPhase
mkdir: cannot create directory ‘/build/media’: No such file or directory
```

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 131614 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>1 package failed to build:</summary>  <ul>    <li>home-assistant</li>  </ul></details><details>  <summary>2 packages built:</summary>  <ul>    <li>python38Packages.nexia</li>    <li>python39Packages.nexia</li>  </ul></details>

**Comment by siraben** [comment]
Is home assistant broken for the time being?

**Pull request merged**
