### PR TITLE
klayout: 0.28.12 -> 0.29.6

### PR DESCRIPTION
**Pull request by HelgeGehring**
## Description of changes

https://www.klayout.de/development.html#0.29.5

## Things done

Updated, added libgit2 as dependency

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by HelgeGehring** [comment]
@knedlsepp Is there something we'd need to maunally do for the cicd to complete? It's my first PR to nixpkgs :)

**Comment by HelgeGehring** [comment]
@wegank @c0bw3b as you previously mentioned a PR regarding klayout, could you have a look? :)

**Comment by simbilod** [comment]
+1 would love to see this merged!

**Comment by HelgeGehring** [comment]
@knedlsepp @wegank @c0bw3b
Is there something we need to do before this can be reviewed?
Thanks :)

**Review by knedlsepp — APPROVED** [review]
Looks good. 👍 Congrats on your first nixpkgs PR and welcome.
(Sorry for the delay, I'm not very active here these days and should probably remove myself from the maintainers list)

**Comment by HelgeGehring** [comment]
Thanks a lot! @knedlsepp 
I saw that there's a minor update of klayout in the meantime (just updating the version/hash which fixes a bug) - should I update this PR or sent a second one?)

**Comment by knedlsepp** [comment]
I think it's fine to just update this PR

**Comment by HelgeGehring** [comment]
@knedlsepp updated!

**Review by knedlsepp — APPROVED** [review]
:+1:

**Pull request merged**
