### PR TITLE
rpcs3: 0.0.8-9300-341fdf7eb -> 0.0.10-10310-7df825855

### PR DESCRIPTION
**Pull request by ghost**
**Requires #84232**

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kolbycrouch** [comment]
Doesn't this depend on qt 5.14?

**Review by ghost — CHANGES_REQUESTED** [review]
I just tried compiling the package, but it throws an error about the 'RPCS3_GIT_FULL_BRANCH' variable not being set.
This can be fixed by adding it to preConfigure, like this:

```
   preConfigure = ''
     cat > ./rpcs3/git-version.h <<EOF
     #define RPCS3_GIT_VERSION "${gitVersion}"
     #define RPCS3_GIT_BRANCH "HEAD"
+    #define RPCS3_GIT_FULL_BRANCH "RPCS3/rpcs3/master"
     #define RPCS3_GIT_VERSION_NO_UPDATE 1
     EOF
   '';
```
Setting any other value for RPCS3_GIT_FULL_BRANCH makes it compile just fine, but it throws a warning about it being an unofficial build everytime it is started.

**Comment by Mic92** [comment]
Mark as draft until we have https://github.com/NixOS/nixpkgs/pull/84232

**Comment by petabyteboy** [comment]
close in favor of https://github.com/NixOS/nixpkgs/pull/100773

**Pull request closed without merging**
