### PR TITLE
linux-firmware: 20230809 -> unstable-2023-09-16

### PR DESCRIPTION
**Pull request by bendlas**
20230809 is also unstable and breaks amdgpu for at least Navi 21

fix https://github.com/NixOS/nixpkgs/commit/c99e492f004c56c4cb6415964d502468e573a40b

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
I have no issues with a 6800XT here. Can you be more specific?

**Comment by bendlas** [comment]
Oh, so you're saying that it works on your machine? :upside_down_face: 

I had issues with my 6700XT not starting into desktop any more ...

```
(EE) AMDGPU(0): [drm] Failed to open DRM device for pci:0000:08:00.0: No such file or directory
vesa: Refusing to run, Framebuffer or dri device present
(WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
(EE) Screen 0 deleted because of no matching config section.
(II) UnloadModule: "amdgpu"
(EE) Device(s) detected, but none match those in the config file.
(EE)
Fatal server error:
(EE) no screens found(EE)
(EE) Server terminated with error (1). Closing log file.
Unable to run X server
```

... not sure why, but maybe these commits, that came right after the **unreleased version** you committed, have something to do with it?

- https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=fd44bdae459a2df0b1dc434af06590c4a3cc914f
- https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=ae80f1f10609ee6b81f96b98b97aecdb52b5ff5f

But to be honest, I don't really care about diagnosing issues with binary blobs from a pre-release. All I can tell you that with this version, my desktop started working again.

So since we already got into the game of shipping unreleased versions, I'd suggest that until we get to the next **released version** of linux-firmware, we bump with extreme prejudice, at even the slightest hint of an issue, instead of only now demanding a full paper trail of accountability.

**Comment by K900** [comment]
We are on a released version though?

**Comment by bendlas** [comment]
I don't see `20230809` in the list https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/refs/

Which are you looking at?

**Comment by K900** [comment]
Also, 6700XT is Navi22, and the GFX11 changes only affect Navi3x. Also, while I understand your frustration, that's not a good reason to resort to bold font personal attacks.

**Comment by K900** [comment]
OK, I see now that this is not in fact an upsteam tag, and I removed the "unstable-" prefix intentionally to avoid breaking nixos-hardware. We should probably keep that part, at least.

**Comment by bendlas** [comment]
> It was coordinated on Matrix, as it included a security hotfix for then-just-announced [AMD "Inception" vulnerability](https://www.tomshardware.com/news/amd-inception-vulnerability-affects-zen-3-and-4), which is also why we can't go back to the latest tag easily.

OK, fair enough. Good that you mention that, I was just about to go prepare a revert to latest tag. But in this case, presumably, the only way on this is forward.

> Given you're the first person to report this in over a month of this version being in nixpkgs, I'm generally inclined to think that this is not a widespread issue, which is also why I asked you for additional details - it's very possible we're dealing with a kernel regression of some sort and not a firmware problem if it only manifested now.

Hoping you're right. It did manifest for me on `linux 6.5.2` with the very common AsRock Challenger 6700XT. On my other machine with a slightly lagging bcachfs kernel and an XFX 319 6700XT, it did not manifest, but I don't remember if I actually tried it with this firmware.

> The offending change has been removed from nixos-hardware, so it's no longer an immediate issue. Other things that may be checking the linux-firmware version may still be affected though. I will not insist on the change.

OK, then I'd rather ship like this, because if we're shipping an unstable version for security reasons, it should be designated as such. If a downstream tool made for introspecting an implementation detail can't handle an unstable version, the downstream tool should change, since the format of version strings has never been promised by nixpkgs. Shipping an unstable version has always been in the cards with linux-firmware, and I remember multiple occasions over the last few years where we did so.

**Comment by K900** [comment]
I'm fine with shipping like this, though I'd rather get some more testing on this because it does also update other firmware which may cause other breakage.

**Comment by bendlas** [comment]
OK, I'll leave this till tomorrow ...

**Comment by K900** [comment]
There's a stable tag now, can you update to that?

**Comment by K900** [comment]
Ended up doing it myself: https://github.com/NixOS/nixpkgs/pull/256121

**Pull request closed without merging**
