### PR TITLE
[20.09] chromium, llvm_11: Backport additional patches

### PR DESCRIPTION
**Pull request by primeos**
###### Motivation for this change

I'm trying to keep the differences between 20.09 and nixos-unstable minimal. I didn't backport these patches right away as the last two Chromium updates needed to be merged more quickly for security reasons. A few (two?) Chromium patches are still missing for now.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by primeos** [comment]
This also contains #103294 and should be ready to test now (CI was fine until the timeout).

@Frostman could you test Chromium as usual?

**Comment by primeos** [comment]
I'll merge this right away due to #103595. CI was fine anyway (up to the timeout at least).

**Comment by Frostman** [comment]
@primeos I have some problems with my setup - wasn't able to get it to finish state, will try to debug this weekend and hopefully will work fine for the next time.

**Comment by primeos** [comment]
@Frostman ok, no problem, thanks for the update :)

**Pull request merged**
