### PR TITLE
kanata: fix hash mismatch on case-insensitive filesystems

### PR DESCRIPTION
**Pull request by jian-lin**
## Description of changes

related https://github.com/NixOS/nixpkgs/issues/308089

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jian-lin** [comment]
CC @toonn for review since this is [suggested][1] by you.
CC @thefloweringash for review since the duplicated files are found by you.  BTW, could you share the way you use to find that?

[1]: https://github.com/NixOS/nixpkgs/pull/306546#discussion_r1584797778
[2]: https://github.com/NixOS/nixpkgs/pull/306546#discussion_r1584771680

**Comment by SuperSandro2000** [comment]
Could you also send an upstream PR to resolve this?

**Comment by jian-lin** [comment]
Which upstream do you mean?

Presumably, the issue is in `cargo`.  I just linked two `cargo` issues in https://github.com/NixOS/nixpkgs/issues/308089#issue-2272419543.  `cargo` maintainers [think][1] they have not come to a conclusion on if it should be fixed and what the right constraints are.  So I will not fix this in `cargo`.  Fixing this in Nixpkgs eases the burden of bumping to new version a lot.

[1]: https://github.com/rust-lang/cargo/pull/13885#issuecomment-2100608385

**Review by toonn — APPROVED** [review]
LGTM

Does upstream really intend for there to be two differently capitalized READMEs though, seems quirky?

**Comment by jian-lin** [comment]
> Does upstream really intend for there to be two differently capitalized READMEs though

Looks like so.

---

Merge conflicts are resolved.  I have verified that the hash is the same on both linux and darwin.  Let's merge this.

**Comment by toonn** [comment]
Where is `README.md` coming from actually? The native-windows-gui repo seems to only have `readme.md`s, though 1.0.13, the version on crates.io, is not a tag in the repo.

I also checked `Cargo.toml`s, one of the issues mentioned problems when those contained a different case for README files but none of them seem to mention any.

**Comment by jian-lin** [comment]
> Does upstream really intend for there to be two differently capitalized READMEs
> Where is `README.md` coming from actually? The native-windows-gui repo seems to only have `readme.md`s, though 1.0.13, the version on crates.io, is not a tag in the repo.

Oh, so by "upstream" you mean `native-windows-gui`?  I thought you meat `cargo` by "upstream" because the real issue is in `cargo`.

My understanding is that native-windows-gui's readme file is named `readme.md`, but `cargo` wants a `README.md`, so `cargo` generates a `README.md` from `readme.md` when publishing a crate.  That is exactly https://github.com/rust-lang/cargo/issues/14020.  You can verify this following [this command](https://github.com/NixOS/nixpkgs/pull/306546#discussion_r1584771680) on a case-sensitive FS.

**Comment by jian-lin** [comment]
The subtle thing about reproducing steps in https://github.com/rust-lang/cargo/issues/14020 is that **you have to run `cargo package` on a case-insensitive FS**!

**Pull request merged**
