### PR TITLE
octoprint: 1.8.1 -> 1.8.2

### PR DESCRIPTION
**Pull request by gador**
###### Description of changes

Update of octoprint.
[Changelog](https://octoprint.org/blog/2022/08/09/new-release-1.8.2/?utm_source=octoprint&utm_medium=announcements&utm_content=1.8.1)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by viraptor** [comment]
Result of `nixpkgs-review pr 185826` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>octoprint</li>
  </ul>
</details>

**Comment by symphorien** [comment]
fails to build for me:
```
error: hash mismatch in fixed-output derivation '/nix/store/hs2wkfqr6gv7czglwjnkqfqr24zfz82d-source.drv':
         specified: sha256-8MUKUayVFbUv5JYpssneaEmK7Q2RlleHJgQsLZQnHa8=
            got:    sha256-uJuGeDS4TnGH1r+6oHtcJDZVGM7hDmkJpB35B1JtqQ0=
error: 1 dependencies of derivation '/nix/store/my28d57aahc78jh243c8hlg3853y9zq0-python3.10-OctoPrint-1.8.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/x55lj8356chhwli02n9jmm275p0inkxf-review-shell.drv' failed to build
```
did they force-push a tag?

**Comment by gador** [comment]
good question. Can't really tell from github. The commit is from 6 days ago for `1.8.2` which is older than this PR. So theoretically, it shouldn't have changed. But with force-pushing, you can't really tell (right?). 

I verified the commit ID from their official github page and it matches `nix-prefetch-github` so I added a commit with the changed `sha256`

**Comment by gador** [comment]
Result of `nixpkgs-review pr 185826` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>octoprint</li>
  </ul>
</details>

**Pull request merged**
