### PR TITLE
parted: switch to python3

### PR DESCRIPTION
**Pull request by lukegb**
###### Motivation for this change

Trying to remove things from the minimal ISO that still rely on Python 2. #105392

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lukegb** [comment]
Result of `nixpkgs-review pr 105407` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>gnome3.gnome-books</li>
    <li>gnome3.gnome-documents</li>
    <li>libsForQt512.kpmcore</li>
    <li>nixops</li>
    <li>nixopsUnstable</li>
    <li>nixops_1_6_1</li>
    <li>rabbitvcs</li>
    <li>xmonad_log_applet</li>
  </ul>
</details>
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
    <li>tests.nixos-functions.nixosTest-test</li>
  </ul>
</details>
<details>
  <summary>135 packages built:</summary>
  <ul>
    <li>adapta-gtk-theme</li>
    <li>almanah</li>
    <li>atom</li>
    <li>atom-beta</li>
    <li>bubblemail</li>
    <li>calamares</li>
    <li>calls</li>
    <li>cantata</li>
    <li>chrome-gnome-shell</li>
    <li>cinnamon.cinnamon-common</li>
    <li>cinnamon.cinnamon-control-center</li>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>cinnamon.cinnamon-screensaver</li>
    <li>clementine</li>
    <li>clementineUnfree</li>
    <li>collectd</li>
    <li>collectd-data</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>dropbox-cli</li>
    <li>elementary-planner</li>
    <li>empathy (gnome3.empathy)</li>
    <li>enlightenment.enlightenment</li>
    <li>evolution-data-server (gnome3.evolution-data-server ,gnome3.evolution_data_server)</li>
    <li>evolution-ews</li>
    <li>f3</li>
    <li>far2l</li>
    <li>fatresize</li>
    <li>feedreader</li>
    <li>folks (gnome3.folks)</li>
    <li>gfbgraph (gnome3.gfbgraph)</li>
    <li>gnome-multi-writer</li>
    <li>gnome-online-accounts (gnome3.gnome-online-accounts ,gnome3.gnome_online_accounts)</li>
    <li>gnome-photos (gnome3.gnome-photos)</li>
    <li>gnome-recipes</li>
    <li>gvfs (gnome2.gvfs)</li>
    <li>gnome3.bijiben (gnome3.gnome-notes)</li>
    <li>gnome3.cheese</li>
    <li>gnome3.evolution</li>
    <li>gnome3.file-roller</li>
    <li>gnome3.geary</li>
    <li>gnome3.gnome-applets</li>
    <li>gnome3.gnome-boxes</li>
    <li>gnome3.gnome-calendar</li>
    <li>gnome3.gnome-contacts</li>
    <li>gnome3.gnome-control-center (gnome3.gnome_control_center)</li>
    <li>gnome3.gnome-disk-utility</li>
    <li>gnome3.gnome-flashback</li>
    <li>gnome3.gnome-initial-setup</li>
    <li>gnome3.gnome-maps</li>
    <li>gnome3.gnome-music</li>
    <li>gnome3.gnome-online-miners</li>
    <li>gnome3.gnome-panel</li>
    <li>gnome3.gnome-session (gnome3.gnome_session)</li>
    <li>gnome3.gnome-shell (gnome3.gnome_shell)</li>
    <li>gnome3.gnome-software</li>
    <li>gnome3.gnome-terminal (gnome3.gnome_terminal)</li>
    <li>gnome3.gnome-todo</li>
    <li>gnome3.gnome-tweaks (gnome3.gnome-tweak-tool)</li>
    <li>gnome3.gnome-user-share</li>
    <li>grilo-plugins (gnome3.grilo-plugins)</li>
    <li>gnome3.gvfs</li>
    <li>libgdata (gnome3.libgdata)</li>
    <li>libzapojit (gnome3.libzapojit)</li>
    <li>gnome3.nautilus</li>
    <li>gnome3.nautilus-python</li>
    <li>gnome3.pomodoro</li>
    <li>shotwell (gnome3.shotwell)</li>
    <li>gnome3.totem</li>
    <li>tracker-miners (gnome3.tracker-miners)</li>
    <li>gnomeExtensions.gsconnect</li>
    <li>gnomeExtensions.night-theme-switcher</li>
    <li>gnufdisk</li>
    <li>gparted</li>
    <li>hal-flash</li>
    <li>haskellPackages.libvirt-hs</li>
    <li>libblockdev</li>
    <li>libguestfs</li>
    <li>libsForQt5.kpmcore (libsForQt515.kpmcore)</li>
    <li>libsForQt514.kpmcore</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>libvirt_5_9_0</li>
    <li>libvmi</li>
    <li>mailnagWithPlugins</li>
    <li>mate.mate-utils</li>
    <li>minikube</li>
    <li>minishift</li>
    <li>multibootusb</li>
    <li>nwipe</li>
    <li>pantheon.elementary-calendar</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-session-settings</li>
    <li>pantheon.extra-elementary-contracts</li>
    <li>pantheon.wingpanel-indicator-datetime</li>
    <li>pantheon.wingpanel-with-indicators</li>
    <li>parted</li>
    <li>partition-manager</li>
    <li>perl530Packages.SysVirt</li>
    <li>perl532Packages.SysVirt</li>
    <li>psensor</li>
    <li>python27Packages.guestfs</li>
    <li>python27Packages.libvirt</li>
    <li>python27Packages.pyparted</li>
    <li>python37Packages.guestfs</li>
    <li>python37Packages.libvirt</li>
    <li>python37Packages.pyparted</li>
    <li>python38Packages.guestfs</li>
    <li>python38Packages.libvirt</li>
    <li>python38Packages.pyparted</li>
    <li>rapid-photo-downloader</li>
    <li>rubyPackages.ruby-libvirt (rubyPackages_2_6.ruby-libvirt)</li>
    <li>rubyPackages_2_5.ruby-libvirt</li>
    <li>rubyPackages_2_7.ruby-libvirt</li>
    <li>spaceFM</li>
    <li>terraform-full</li>
    <li>terraform-providers.libvirt</li>
    <li>terraform_0_11-full</li>
    <li>udiskie</li>
    <li>udisks (udisks2)</li>
    <li>usermount</li>
    <li>vagrant</li>
    <li>vifm-full</li>
    <li>virt-manager</li>
    <li>virt-manager-qt</li>
    <li>virt-top</li>
    <li>virt-viewer</li>
    <li>virtlyst</li>
    <li>woeusb</li>
    <li>xfce.gigolo</li>
    <li>xfce.gvfs</li>
    <li>xfce.thunar (xfce.thunar-bare ,xfce.thunar-build ,xfce.thunarx-2-dev)</li>
    <li>xfce.thunar-archive-plugin</li>
    <li>xfce.thunar-dropbox-plugin</li>
    <li>xfce.xfdesktop</li>
  </ul>
</details>

**Comment by lukegb** [comment]
@raboof

**Comment by lukegb** [comment]
@ajs124 I'm assuming there's probably a PR for this too. I probably should've checked first, heh

**Comment by raboof** [comment]
I see you found my PR at https://github.com/NixOS/nixpkgs/pull/104703 - you could still add yourself as maintainer though :)

**Pull request closed without merging**
