### PR TITLE
nixos.cjdns: allow multiple cjdns networks and multiple UDP/ETH interfaces per network

### LINKED ISSUE #21813: cjdns module doesnt support multiple networks
## Issue description

At the moment, there can be one cjdns network only.  It would be nice, if one could configure many independent cjdns networks.

Now:
```
services.cjdns = {
   enable = true;
   ...
}
```
Multiple networks:
```
services.cjdns.networks = {
   home = {
      enable = true;
      ...
   };
   hyperboria = {
      enable = true;
      ...
   };
   test = {
      enable = true;
      ...
   };
}
````

### PR DESCRIPTION
**Pull request by wizeman**
###### Motivation for this change

There are two big changes to the `cjdns` module:
1. Allow the definition of multiple UDP and ETH interfaces.
2. Allow the definition of multiple cjdns networks.

Both are breaking changes to existing `cjdns` configurations, and that's why I'm grouping both changes in the same PR (so that, if we go ahead with breaking configurations, we don't break them more often than necessary).

If you prefer, I can separate them into 2 separate PRs, instead of 2 separate commits in the same PR.

Both commit messages follow:

##### Accept multiple UDP and ETH interfaces

This can be useful for UDP interfaces if you want to listen on multiple
UDP ports, for example, if you want to have redundant paths to a node,
e.g. so that you are more likely to be able to bypass firewalls.

It is also useful for ethernet interfaces because if you have set
`bind = "all"` and `beacon = 0` in your ETHInterface, then (presumably
due to a bug) cjdns won't try to connect to any nodes.

In this case, you may want to define two separate ETHInterfaces, for
example, one binding to your actual ethernet device, and another one
binding to your wifi device.

**WARNING:** This is a breaking change for anyone who uses cjdns, since
UDPInterface is renamed to UDPInterfaces and it is now a list (same for
ETHInterface).

##### Allow multiple cjdns networks to coexist

This is useful in case you wish to be connected to one or more private
cjdns networks, and/or also be connected to a public network (e.g.
Hyperboria).

Each network will have a name assigned to it, and the TUN network
interface will be set to the name of the cjdns network (instead of being
named `tun0` or whatever number is available). This allows the interface
names to be predictable and easy to tell which one belongs to which
network, which facilitates firewall configuration.

The cjdns files that were automatically created with the secret keys
and the public parameters (`/etc/cjdns.keys` and `/etc/cjdns.public`) will
now be called `/etc/cjdns-<name>.keys` and `/etc/cjdns-<name>.public`.

**WARNING:** This is a breaking change for anyone who uses cjdns, since
cjdns networks now must be under an attribute name (which defines the
cjdns network name). For example, whereas before you had a cjdns network
defined liked this:

```
services.cjdns = {
  enable = true;
  UDPInterface = { ... };
};
```

... you must now define it like this:

```
services.cjdns.networks = {
  mynet = {
    enable = true;
    UDPInterfaces = [ {
      ...
    } ];
  };
};
```

... where `mynet` is some name you must assign to your cjdns network
(note that the name will also be used to name the network interface,
replacing the generic name `tun0`).

Also, you must copy your existing `/etc/cjdns.keys` and
`/etc/cjdns.public` files to `/etc/cjdns-mynet.keys` and
`/etc/cjdns-mynet.public`, respectively (replace `mynet` by your network
name), so that you can keep the same IPv6 address and private/public keys
you were using before.

Fixes #21813

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by wizeman** [comment]
BTW, since we're already breaking things, a good follow-up PR would probably be to move `/etc/cjdns-*.{keys,public}` files to `/var/lib/cjdns/` instead.

**Comment by ehmry** [comment]
Breaking changes make me nervous, but I'm not satisfied with how this is configured either.

An alternative solution would be to ignore the current implementation and come up with a new NixOS friendly format for cjdns, then create a new configurator tool. Cjdns is actually only configured using the admin RPC socket, and a helper process is translating the JSON configuration to RPC calls.

There is a Go library that could do this with some updates https://github.com/fc00/go-cjdns, otherwise there is JS, but I hate to encourage that sort of thing.

**Comment by wizeman** [comment]
@ehmry: what is it exactly that you are not satisfied with, regarding how this is configured? This is quite similar to how `cjdroute.conf` is actually configured in upstream `cjdns`.

If the problem is that `UDPInterfaces`/`ETHInterfaces` is now a list of attribute sets (which, admittedly, could be confusing for some people), perhaps I could change this PR to maintain the old `UPDInterface`/`ETHInterface` config options, and instead add 2 new options: `extraUDPInterfaces` and `extraETHInterfaces`, which would be (empty be default) lists, and which almost nobody would need to set (unless more than one interface of the same type is needed).

I guess this could simplify the configuration a bit, be a bit more similar to how other NixOS services are configured, while still allowing more complex configs. I think the main downside would be that `man configuration.nix` would have some duplicate documentation (identical for `UDPInterface` and `extraUDPInterfaces`, for instance).

**Comment by tohl** [comment]
> Breaking changes make me nervous

That is a valid concern.  However:

> There is a Go library that could do this with some updates
> https://github.com/fc00/go-cjdns, otherwise there is JS, but I hate to
> encourage that sort of thing.

the first thing the suggested library says is:

   IMPORTANT: go-cjdns was recently restructured and has probably broken
   any programs that were using it. Sorry about that, but it's for the
   best, I promise. The code is much better organized now and will
   continue to be improved.

Is it not a concern with this additional external dependency?

> An alternative solution would be to ignore the current implementation
> and come up with a new NixOS friendly format for cjdns, then create a
> new configurator tool.  Cjdns is actually only configured using the
> admin RPC socket, and a helper process is translating the JSON
> configuration to RPC calls.

This seems out of scope for nixpkgs.  cjdns is configurable via a config
file, which can be easily created by nixpkgs module and no external
dependencies are needed in this case.

> and come up with a new NixOS friendly format for cjdns

In what way is the current implementation insufficient, except lacking
more options?

**Comment by tohl** [comment]
@wizeman Thanks for working on this!

> This is useful in case you wish to be connected to one or more private
> cjdns networks, and/or also be connected to a public network (e.g.
> Hyperboria).

Another use case is simply to gain more IP addresses on the same
machine.

On the whole I like the change as is, even though it breaks existing
installations.  I think that it is a step in the right direction.

**Comment by tohl** [comment]
> config = mkIf (cfgs != [])

@wizeman you deleted the "enable" option, that option is important and
should work like for other modules, i.e that mkIf should look if any cfg
is enable = true.

**Comment by tohl** [comment]
@wizeman nixos/tests/cjdns.nix also needs to change

**Comment by wizeman** [comment]
@tohl: I've done the changes you mentioned, let me know if anything else is needed.

Thanks!

**Comment by mguentner** [comment]
@wizeman, have you seen #18881? It would be awesome to have the passwords removed from the store. This could also be done in a follow-up PR, maybe a good idea since this PR introduces enough change as it is.

**Comment by wizeman** [comment]
@mguentner: yes, but like you suggested, I think that should be done in another PR.

**Comment by tohl** [comment]
@wizeman I have been using your changes for a week and it works for me.
Thanks!

Here are more thoughts.

Most programs don't offer an option to choose, which network interface
to use (e.g. ping can select an interface, ssh cannot).  Those that
cannot, rely on kernel to choose the right one.  Kernel does it based on
the network, but this does not work for cjdns because all cjdns
addresses are always "on the same network" fc00::/8 from the kernels
point of view.  This means that configuring more than one cjdns network
attribute on a machine will make connections from this machine to any
cjdns network "unreliable", because the kernel will use "random" or "the
first activated" cjdns network, and if that is the wrong one, cjdns will
"hang", trying to find nonexisting route.

There are two use-cases:

1) So the case with multiple cjdns networks does not work for "leaf" or
   "outbound" nodes, or for nodes where somebody want to connect to the
   cjdns network and relying on the kernel choosing the right interface.

   So far people usually use cjdns to connect to the cjdns network from
   the local computer where the kernel routes does the first part of
   routing (towards the cjdns process).  This works when one cjdns
   network is configured only.

2) However, if it is used for the other use-cases mentioned (e.g. to
   gain cjdns IP addresses on the same machine), it works fine with
   multiple cjdns networks configured, because it is a cjdns router
   which routes the connections, not the local kernel.

I hope it makes sense, I am not sure how to describe the difference in
better words atm.  but if you try it, you'll understand.

So the question is, would it make sense to preserve backward
compatibility for the two different use-cases?  It seems that it
actually makes sense and would make everybody happy.

What do you think?

**Comment by ehmry** [comment]
I neither use cjdns or NixOS currently, so I'm not the one to take care of this issue.

**Comment by wizeman** [comment]
@tohl For your first use case, I was thinking that, for example, if you have two cjdns networks configured in your machine: one like Hyperboria (e.g. called `hyper`), and another one being a private network where you know the IPv6 addresses of all the nodes in them (e.g. called `cjvpn`), then you could manually add routes for your networks with a bash script like this:

```bash
# First, delete any routes cjdns could have added automatically:
ip -6 route del fc00::/8 dev hyper || true
ip -6 route del fc00::/8 dev cjvpn || true

# Add routes to hosts in your private cjdns network:
ip -6 route add $IPV6_ADDRESS_HOST1 dev cjvpn
ip -6 route add $IPV6_ADDRESS_HOST2 dev cjvpn
(...)

# Add route for remaining cjdns IPv6 addresses over the public cjdns network:
ip -6 route add fc00::/8 dev hyper
```
(Note, I haven't tried this yet, so it's possible it may not actually work).

> So the question is, would it make sense to preserve backward
compatibility for the two different use-cases?

What do you mean by preserving backwards compatibility?

**Comment by vcunat** [comment]
People interested in cjdns: the current version in master [is incompatible](http://hydra.nixos.org/build/49069698) with [glibc-2.25](https://github.com/NixOS/nixpkgs/issues/22874) due to defining a symbol that glibc now started exporting.  I would like to have glibc-2.25 in 17.03 when it gets branched (in a week).

**Comment by wizeman** [comment]
@vcunat: I believe this patch should fix the issue: https://github.com/cjdelisle/cjdns/pull/1017/files

**Comment by vcunat** [comment]
Right, that does seem correct, and it does fix the build: 3d04d470cd.

**Comment by tohl** [comment]
@wizeman thanks for the routing suggestions, I'll try it when I get
time.

>  So the question is, would it make sense to preserve backward
>  compatibility for the two different use-cases?
>
> What do you mean by preserving backwards compatibility?

By that I mean "not to force people to change their configuration.nix".
E.g. @ehmry did not like that but he is not using it anyway.  Other
people might complain though when their config breaks.  I am personally
fine with it.

**Comment by joachifm** [comment]
@GrahamcOfBorg test cjdns

**Comment by joachifm** [comment]
@GrahamcOfBorg eval

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by tohl** [comment]
i think that there are some unresolved issues with this pull request
and it is not likely to move forward

nixos has a good support for containers these days so one could install
multiple instances of the cjdns module in separate containers with
appropriate networking configuration

**Comment by ehmry** [comment]
I'm closing this PR because it is stale and the branch cannot be merged, please reopen if these changes are still desired.

**Pull request closed without merging**
