### PR TITLE
josm: 19207 → 19230

### PR DESCRIPTION
**Pull request by sikmir**
[Changelog](https://josm.openstreetmap.de/wiki/Changelog#a2024-10-02:Stablerelease1923024.09)

## Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by rycee** [comment]
I'm having troubles building this at the moment:

``` console
$ nix log /nix/store/h2jzwg7ahg3yl4jf90h31hh0ad9ndh7g-tested-r19230.drv
exporting https://josm.openstreetmap.de/svn/trunk/native/linux/tested (r19230) into /nix/store/4v6h8ycrvpdsgdky80k70rp3cx3v6mk4-tested-r19230
svn: E170013: Unable to connect to a repository at URL 'https://josm.openstreetmap.de/svn/trunk/native/linux/tested'
svn: E230001: Server SSL certificate verification failed: certificate has expired, issuer is not trusted
```

Curiously I am able to open <https://josm.openstreetmap.de/> in Firefox and the CI seemes to have passed so I'm not certain what the issue is.

**Comment by rycee** [comment]
@GrahamcOfBorg build josm

**Comment by rycee** [comment]
Seems like it's not just me the [GrahamOfBorg build](https://github.com/NixOS/nixpkgs/pull/346511/checks?check_run_id=31135097779) failed with the same error.

**Comment by sikmir** [comment]
Now I have the same issue.

**Comment by enockseth** [comment]
I have the same issue too.

**Comment by sikmir** [comment]
@ofborg build josm

**Comment by sikmir** [comment]
Well, let's switch to https://github.com/JOSM/josm mirror.

**Comment by rycee** [comment]
Thanks @sikmir, that seems to have helped!

**Comment by AndrewKvalheim** [comment]
Possible solution for the SSL error: #356829

**Pull request merged**
