### PR TITLE
basedpyright: 1.19.0 -> 1.21.0

### PR DESCRIPTION
**Pull request by kiike**
Diff:
https://github.com/detachhead/basedpyright/compare/refs/tags/v1.19.0...v1.21.0

Changelog:
https://github.com/detachhead/basedpyright/releases/tag/1.21.0

- The package is a lot simpler as basedpyright changed from lerna to npm workspaces.
- nix-update can now update the package automatically, so the custom shell script is no longer needed
- as the project uses the root `package-lock.json`, patching the lockfiles is no longer needed
- a couple of dependencies were added, apparently pkg-config and libsecret are needed, I guess to store credentials into the password manager
- tweaked the test script a bit to add a couple more errors

Let me know if you find anything missing!

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 354204`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>basedpyright</li>
    <li>emacsPackages.lsp-bridge</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>basedpyright</li>
    <li>emacsPackages.lsp-bridge</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>basedpyright</li>
    <li>emacsPackages.lsp-bridge</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>basedpyright</li>
    <li>emacsPackages.lsp-bridge</li>
  </ul>
</details>

**Review by GaetanLepage — CHANGES_REQUESTED** [review]
Thank you for this detailed report and the PR too.
This is much simpler indeed !

A few things:
- Do `version` and `src` still need to be in a `let` `in` block ? Couldn't we go back to a more standard `finalAttrs` implem ?
- Could you add `versionCheckHook` (and then maybe remove `passthru.tests.version`). See [here](https://github.com/NixOS/nixpkgs/blob/10ff7c5e10cbef2c21433c560abcea04e805c1fe/pkgs/by-name/ty/typst/package.nix#L69-L73) for an example.
- You commented `sourceRoot` but didn't remove it completely.

**Comment by kiike** [comment]
> Thank you for this detailed report and the PR too. This is much simpler indeed !
> 
> A few things:
> 
>     * Do `version` and `src` still need to be in a `let` `in` block ? Couldn't we go back to a more standard `finalAttrs` implem ?

I think they still need to be there, yes. `docstubs` needs to be in the `let [...] in` block, and that needs access to `src`, which needs access to `version`.
 
>     * Could you add `versionCheckHook` (and then maybe remove `passthru.tests.version`). See [here](https://github.com/NixOS/nixpkgs/blob/10ff7c5e10cbef2c21433c560abcea04e805c1fe/pkgs/by-name/ty/typst/package.nix#L69-L73) for an example.

Done!
 
>     * You commented `sourceRoot` but didn't remove it completely.

Good catch! A couple more comments needed updating too. Thanks for the tip!

**Comment by GaetanLepage** [comment]
> I think they still need to be there, yes. `docstubs` needs to be in the `let [...] in` block, and that needs access to `src`, which needs access to `version`.

Ins't this achievable with `finalAttrs` or `rec` ? (I could be wrong).

**Comment by kiike** [comment]
> > I think they still need to be there, yes. `docstubs` needs to be in the `let [...] in` block, and that needs access to `src`, which needs access to `version`.
> 
> Ins't this achievable with `finalAttrs` or `rec` ? (I could be wrong).

I moved the docstubs block so that we can achieve the same effect inside the `rec`. After this change, the docstubs are not in a separate derivation so the result can't be reused in case of incremental building. Not a drama, though.

As for the rec, I can't seem to find examples of the `finalAttrs` pattern with `buildNpmPackage` so it might be not compatible. For now it looks like `rec` might be the only way.

**Comment by GaetanLepage** [comment]
> I moved the docstubs block so that we can achieve the same effect inside the `rec`. After this change, the docstubs are not in a separate derivation so the result can't be reused in case of incremental building. Not a drama, though.

Ok it is a bit more streamlined now at least.
Thanks for taking the time to conduct the change.

> As for the `rec`, I can't seem to find examples of the `finalAttrs` pattern with `buildNpmPackage` so it might be not compatible. For now it looks like `rec` might be the only way.

Indeed, my bad. The `finalAttrs` is only possible with the original `mkDerivation` builder.

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 354204`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>basedpyright</li>
    <li>emacsPackages.lsp-bridge</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>basedpyright</li>
    <li>emacsPackages.lsp-bridge</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>basedpyright</li>
    <li>emacsPackages.lsp-bridge</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>basedpyright</li>
    <li>emacsPackages.lsp-bridge</li>
  </ul>
</details>

**Comment by kiike** [comment]
Thanks for the review!

**Review by GaetanLepage — APPROVED** [review]

**Pull request merged**
