### PR TITLE
naproche: fix build with GHC 9

### PR DESCRIPTION
**Pull request by jvanbruegge**
###### Description of changes

Currently this prevents users from installing isabelle

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by rnhmjoj — APPROVED** [review]
I tested this fixes naproche and Isabelle builds.

**Review by rnhmjoj — CHANGES_REQUESTED** [review]
Ah, given there is no release tag, the version [should be](https://nixos.org/manual/nixpkgs/stable/#sec-package-naming) changed to YYYY-MM-DD.

**Comment by jvanbruegge** [comment]
Done

**Comment by cdepillabout** [comment]
A couple points:

- In general, Haskell packages (even packages with only an exectuable) should be uploaded to Hackage.  That way, Haskellers can get them through their normal channels (like `cabal`, `stack`, Nixpkgs, haskell.nix, other Linux distros, etc).  Uploading your Haskell programs to Hackage means that you mostly don't have to do any work to keep it up-to-date in Nixpkgs.  It gets automatically updated to the latest release on Hackage.  If you're not the maintainer, I'd highly recommend creating an issue upstream urging the maintainer to release to Hackage.  (Although it appears that it wouldn't have helped in this case, since you're using an un-released version.  But in general it still holds true.)

- > Is there somewhere I need to register naproche so it will get caught here in the next round of updates

    You can add `naproche` to the list in https://github.com/NixOS/nixpkgs/blob/0bbb65673c0ba31047c9ba6c4cd211556b534a4e/pkgs/top-level/release-haskell.nix#L140.  This makes sure that `naproche` will appear in the build reports for the `haskell-updates` PRs.  Here's an example build report:

    https://github.com/NixOS/nixpkgs/pull/168049#issuecomment-1102643457

- It is generally easier for us to have Haskell-related PRs targetting the `haskell-updates` branch instead of `master`.  In the future, you can also feel free to ping @-NixOS/haskell to get your Haskell-related PRs reviewed/merged.

**Comment by jvanbruegge** [comment]
Thanks.
- Yeah, I am not the maintainer, and I don't think they will upload it to hackage any time soon. I just need it for isabelle
- Thanks, added it now there
- ok, i will target `haskell-updates` in the future

**Comment by cdepillabout** [comment]
Thanks for the quick response!

**Comment by jvanbruegge** [comment]
Thanks for the quick reply :)

**Pull request merged**
