### PR TITLE
docker-compose-language-service: init at 0.1.3

### PR DESCRIPTION
**Pull request by natsukium**
###### Description of changes

Language service for Docker Compose documents
https://github.com/microsoft/compose-language-service

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by qverkk** [comment]
I was about to add this one too. Although wouldn't it be better to define this in `node-packages.nix`? It's already available in npm. For example u probably could add:

`
 "@microsoft/compose-language-service-1.3.0" = {
      name = "_at_microsoft_slash_compose-language-service";
      packageName = "@microsoft/compose-language-service";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@microsoft/compose-language-service/-/compose-language-service-1.3.0.tgz";
        sha512 = "2ejg8I/7P8Mb4uGsLKZ+bJkQsq95wMyF/mino3TqpB6+hoi5OaeL1ozCfm4GQhKDkC/TGrhljGxXtgwA5G2+7g==";
      };
    };
`

**Comment by natsukium** [comment]
Yes, there is a way to do it, but @winter, one of the member of nixpkgs node team, said that `buildNpmPackage` is preferable to codegen with `node2nix`, so I use it.
see, https://github.com/NixOS/nixpkgs/pull/213590#issuecomment-1419018577

**Comment by qverkk** [comment]
> 

Ah kk, sounds good then tyvm for the explanation

**Comment by SuperSandro2000** [comment]
> I was about to add this one too. Although wouldn't it be better to define this in `node-packages.nix`?

nodePackages is an unmaintainable pile of code and we should not add to much more onto it.

**Pull request merged**
