### PR TITLE
Vimplugin update to fix coc

### PR DESCRIPTION
**Pull request by Dettorer**
###### Description of changes
This updates all vim plugins. What waranted the update is a change in the coc-nvim API that home-manager now uses, see https://github.com/nix-community/home-manager/issues/2966

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Dettorer** [comment]
Result of `nixpkgs-review pr 175324` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.lush-nvim</li>
  </ul>
</details>
<details>
  <summary>173 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>vimPlugins.Coqtail</li>
    <li>vimPlugins.FTerm-nvim</li>
    <li>vimPlugins.LeaderF</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.aniseed</li>
    <li>vimPlugins.barbar-nvim</li>
    <li>vimPlugins.bufdelete-nvim</li>
    <li>vimPlugins.bufferline-nvim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.circles-nvim</li>
    <li>vimPlugins.cmp-nvim-lsp</li>
    <li>vimPlugins.cmp-tabnine</li>
    <li>vimPlugins.coc-lua</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.codi-vim</li>
    <li>vimPlugins.command-t</li>
    <li>vimPlugins.comment-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.conjure</li>
    <li>vimPlugins.copilot-vim</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.dart-vim-plugin</li>
    <li>vimPlugins.defx-nvim</li>
    <li>vimPlugins.deoplete-fish</li>
    <li>vimPlugins.deoplete-khard</li>
    <li>vimPlugins.deoplete-nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.dressing-nvim</li>
    <li>vimPlugins.edge</li>
    <li>vimPlugins.everforest</li>
    <li>vimPlugins.feline-nvim</li>
    <li>vimPlugins.fern-vim</li>
    <li>vimPlugins.fidget-nvim</li>
    <li>vimPlugins.formatter-nvim</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.fzf-lsp-nvim</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.git-blame-nvim</li>
    <li>vimPlugins.gitlinker-nvim</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.gruvbox-material</li>
    <li>vimPlugins.impatient-nvim</li>
    <li>vimPlugins.indent-blankline-nvim</li>
    <li>vimPlugins.julia-vim</li>
    <li>vimPlugins.kanagawa-nvim</li>
    <li>vimPlugins.kommentary</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.lf-vim</li>
    <li>vimPlugins.lir-nvim</li>
    <li>vimPlugins.litee-calltree-nvim</li>
    <li>vimPlugins.litee-filetree-nvim</li>
    <li>vimPlugins.litee-nvim</li>
    <li>vimPlugins.litee-symboltree-nvim</li>
    <li>vimPlugins.lsp_signature-nvim</li>
    <li>vimPlugins.lspsaga-nvim</li>
    <li>vimPlugins.lualine-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vimPlugins.marks-nvim</li>
    <li>vimPlugins.material-nvim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.mru</li>
    <li>vimPlugins.ncm2</li>
    <li>vimPlugins.ncm2-jedi</li>
    <li>vimPlugins.neco-vim</li>
    <li>vimPlugins.neoformat</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neoterm</li>
    <li>vimPlugins.nerdcommenter</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.nord-nvim</li>
    <li>vimPlugins.nord-vim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-base16</li>
    <li>vimPlugins.nvim-biscuits</li>
    <li>vimPlugins.nvim-bqf</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-code-action-menu</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-fzf</li>
    <li>vimPlugins.nvim-gps</li>
    <li>vimPlugins.nvim-lightbulb</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-metals</li>
    <li>vimPlugins.nvim-notify</li>
    <li>vimPlugins.nvim-scrollview</li>
    <li>vimPlugins.nvim-spectre</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-refactor</li>
    <li>vimPlugins.nvim-treesitter-textobjects</li>
    <li>vimPlugins.nvim-ts-rainbow</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.nvim-yarp</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.onedark-nvim</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.plenary-nvim</li>
    <li>vimPlugins.project-nvim</li>
    <li>vimPlugins.quick-scope</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.registers-nvim</li>
    <li>vimPlugins.renamer-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.rnvimr</li>
    <li>vimPlugins.rose-pine</li>
    <li>vimPlugins.rust-tools-nvim</li>
    <li>vimPlugins.seoul256-vim</li>
    <li>vimPlugins.sonokai</li>
    <li>vimPlugins.space-vim</li>
    <li>vimPlugins.splitjoin-vim</li>
    <li>vimPlugins.srcery-vim</li>
    <li>vimPlugins.tagalong-vim</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-file-browser-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.toggleterm-nvim</li>
    <li>vimPlugins.verilog_systemverilog-vim</li>
    <li>vimPlugins.vifm-vim</li>
    <li>vimPlugins.vim-airline</li>
    <li>vimPlugins.vim-android</li>
    <li>vimPlugins.vim-autoformat</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-closetag</li>
    <li>vimPlugins.vim-code-dark</li>
    <li>vimPlugins.vim-endwise</li>
    <li>vimPlugins.vim-floaterm</li>
    <li>vimPlugins.vim-fugitive</li>
    <li>vimPlugins.vim-git</li>
    <li>vimPlugins.vim-gitgutter</li>
    <li>vimPlugins.vim-gnupg</li>
    <li>vimPlugins.vim-go</li>
    <li>vimPlugins.vim-ledger</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-markbar</li>
    <li>vimPlugins.vim-matchup</li>
    <li>vimPlugins.vim-mucomplete</li>
    <li>vimPlugins.vim-oscyank</li>
    <li>vimPlugins.vim-pandoc</li>
    <li>vimPlugins.vim-prosession</li>
    <li>vimPlugins.vim-puppet</li>
    <li>vimPlugins.vim-ruby</li>
    <li>vimPlugins.vim-sandwich</li>
    <li>vimPlugins.vim-scriptease</li>
    <li>vimPlugins.vim-smoothie</li>
    <li>vimPlugins.vim-snippets</li>
    <li>vimPlugins.vim-table-mode</li>
    <li>vimPlugins.vim-test</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.vim-unimpaired</li>
    <li>vimPlugins.vimagit</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.wilder-nvim</li>
    <li>vimPlugins.yats-vim</li>
    <li>vimPlugins.zephyr-nvim</li>
  </ul>
</details>

**Comment by Dettorer** [comment]
Packages fail to build because of https://github.com/rktjmp/lush.nvim/issues/89, I'll wait a bit for upstream to push a fix and may add my proposed patch (https://github.com/rktjmp/lush.nvim/pull/90) to nixpkgs if it takes too much time.

I also understand that the `cargoSha256` references may be an issue when updating plugin (I get that from https://github.com/NixOS/nixpkgs/pull/162815), but I'm not sure what to check myself to make sure I'm not breaking plugins that depend on rust.

**Comment by Dettorer** [comment]
As to the coc-nvim problem with home manager, I just confirmed that building my nixos configuration against this PR works, while building it against nixpkg's master fails on home-manager's neovim with `E117: Unknown function: coc#float#create_notification`. So this indeed fixes my particular problem.

**Comment by ronanharris09** [comment]
I also run into that error and went straight to patch `coc-nvim` locally as a temporary solution. The patches related to the issue is
1. https://github.com/neoclide/coc.nvim/commit/45828e407de419f73cee3e5f8d59a4cbbc2274e6.patch

**Comment by teto** [comment]
thanks for taking care of the lush issue, I just hit it (and fixing the nord-vim branch, it's now using "main"). Is this ready ?

**Comment by Dettorer** [comment]
Result of `nixpkgs-review pr 175324` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>176 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>vimPlugins.Coqtail</li>
    <li>vimPlugins.FTerm-nvim</li>
    <li>vimPlugins.LeaderF</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.aniseed</li>
    <li>vimPlugins.barbar-nvim</li>
    <li>vimPlugins.bufdelete-nvim</li>
    <li>vimPlugins.bufferline-nvim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.circles-nvim</li>
    <li>vimPlugins.cmp-nvim-lsp</li>
    <li>vimPlugins.cmp-tabnine</li>
    <li>vimPlugins.coc-lua</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.codi-vim</li>
    <li>vimPlugins.command-t</li>
    <li>vimPlugins.comment-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.conjure</li>
    <li>vimPlugins.copilot-vim</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.dart-vim-plugin</li>
    <li>vimPlugins.defx-nvim</li>
    <li>vimPlugins.deoplete-fish</li>
    <li>vimPlugins.deoplete-khard</li>
    <li>vimPlugins.deoplete-nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.dressing-nvim</li>
    <li>vimPlugins.edge</li>
    <li>vimPlugins.everforest</li>
    <li>vimPlugins.feline-nvim</li>
    <li>vimPlugins.fern-vim</li>
    <li>vimPlugins.fidget-nvim</li>
    <li>vimPlugins.formatter-nvim</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.fzf-lsp-nvim</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.git-blame-nvim</li>
    <li>vimPlugins.gitlinker-nvim</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.gruvbox-material</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.impatient-nvim</li>
    <li>vimPlugins.indent-blankline-nvim</li>
    <li>vimPlugins.julia-vim</li>
    <li>vimPlugins.kanagawa-nvim</li>
    <li>vimPlugins.kommentary</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.lf-vim</li>
    <li>vimPlugins.lir-nvim</li>
    <li>vimPlugins.litee-calltree-nvim</li>
    <li>vimPlugins.litee-filetree-nvim</li>
    <li>vimPlugins.litee-nvim</li>
    <li>vimPlugins.litee-symboltree-nvim</li>
    <li>vimPlugins.lsp_signature-nvim</li>
    <li>vimPlugins.lspsaga-nvim</li>
    <li>vimPlugins.lualine-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.lush-nvim</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vimPlugins.marks-nvim</li>
    <li>vimPlugins.material-nvim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.mru</li>
    <li>vimPlugins.ncm2</li>
    <li>vimPlugins.ncm2-jedi</li>
    <li>vimPlugins.neco-vim</li>
    <li>vimPlugins.neoformat</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neoterm</li>
    <li>vimPlugins.nerdcommenter</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.nord-nvim</li>
    <li>vimPlugins.nord-vim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-base16</li>
    <li>vimPlugins.nvim-biscuits</li>
    <li>vimPlugins.nvim-bqf</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-code-action-menu</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-fzf</li>
    <li>vimPlugins.nvim-gps</li>
    <li>vimPlugins.nvim-lightbulb</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-metals</li>
    <li>vimPlugins.nvim-notify</li>
    <li>vimPlugins.nvim-scrollview</li>
    <li>vimPlugins.nvim-spectre</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-refactor</li>
    <li>vimPlugins.nvim-treesitter-textobjects</li>
    <li>vimPlugins.nvim-ts-rainbow</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.nvim-yarp</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.onedark-nvim</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.plenary-nvim</li>
    <li>vimPlugins.project-nvim</li>
    <li>vimPlugins.quick-scope</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.registers-nvim</li>
    <li>vimPlugins.renamer-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.rnvimr</li>
    <li>vimPlugins.rose-pine</li>
    <li>vimPlugins.rust-tools-nvim</li>
    <li>vimPlugins.seoul256-vim</li>
    <li>vimPlugins.sonokai</li>
    <li>vimPlugins.space-vim</li>
    <li>vimPlugins.splitjoin-vim</li>
    <li>vimPlugins.srcery-vim</li>
    <li>vimPlugins.tagalong-vim</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-file-browser-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.toggleterm-nvim</li>
    <li>vimPlugins.verilog_systemverilog-vim</li>
    <li>vimPlugins.vifm-vim</li>
    <li>vimPlugins.vim-airline</li>
    <li>vimPlugins.vim-android</li>
    <li>vimPlugins.vim-autoformat</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-closetag</li>
    <li>vimPlugins.vim-code-dark</li>
    <li>vimPlugins.vim-endwise</li>
    <li>vimPlugins.vim-floaterm</li>
    <li>vimPlugins.vim-fugitive</li>
    <li>vimPlugins.vim-git</li>
    <li>vimPlugins.vim-gitgutter</li>
    <li>vimPlugins.vim-gnupg</li>
    <li>vimPlugins.vim-go</li>
    <li>vimPlugins.vim-ledger</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-markbar</li>
    <li>vimPlugins.vim-matchup</li>
    <li>vimPlugins.vim-mucomplete</li>
    <li>vimPlugins.vim-oscyank</li>
    <li>vimPlugins.vim-pandoc</li>
    <li>vimPlugins.vim-prosession</li>
    <li>vimPlugins.vim-puppet</li>
    <li>vimPlugins.vim-ruby</li>
    <li>vimPlugins.vim-sandwich</li>
    <li>vimPlugins.vim-scriptease</li>
    <li>vimPlugins.vim-smoothie</li>
    <li>vimPlugins.vim-snippets</li>
    <li>vimPlugins.vim-table-mode</li>
    <li>vimPlugins.vim-test</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.vim-unimpaired</li>
    <li>vimPlugins.vim-wakatime</li>
    <li>vimPlugins.vimagit</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.wilder-nvim</li>
    <li>vimPlugins.yats-vim</li>
    <li>vimPlugins.zephyr-nvim</li>
  </ul>
</details>

**Comment by Dettorer** [comment]
Lush.nvim merged my fix so I just ran the update script again, everything seems to build correctly.

I'm still not sure what to check regarding the possible cargoSha256 issues, but other than that the PR is ready.

**Comment by Dettorer** [comment]
Ok so #162815 just seems to rebuild plugins for which we have an override that mentions cargo somewhere. There are currently four of them: `LanguageClient-neovim`, `sniprun`, `vim-clap`, and `vim-markdown-composer`, I just built theme successfully so I guess everything's alright regarding rust based plugins.

This PR is ready.

**Comment by teto** [comment]
Result of `nixpkgs-review pr 175324` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>177 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>tests.vim.test_vim_with_vim_nix</li>
    <li>vimPlugins.Coqtail</li>
    <li>vimPlugins.FTerm-nvim</li>
    <li>vimPlugins.LeaderF</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.aniseed</li>
    <li>vimPlugins.barbar-nvim</li>
    <li>vimPlugins.bufdelete-nvim</li>
    <li>vimPlugins.bufferline-nvim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.circles-nvim</li>
    <li>vimPlugins.cmp-nvim-lsp</li>
    <li>vimPlugins.cmp-tabnine</li>
    <li>vimPlugins.coc-lua</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.codi-vim</li>
    <li>vimPlugins.command-t</li>
    <li>vimPlugins.comment-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.conjure</li>
    <li>vimPlugins.copilot-vim</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.dart-vim-plugin</li>
    <li>vimPlugins.defx-nvim</li>
    <li>vimPlugins.deoplete-fish</li>
    <li>vimPlugins.deoplete-khard</li>
    <li>vimPlugins.deoplete-nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.dressing-nvim</li>
    <li>vimPlugins.edge</li>
    <li>vimPlugins.everforest</li>
    <li>vimPlugins.feline-nvim</li>
    <li>vimPlugins.fern-vim</li>
    <li>vimPlugins.fidget-nvim</li>
    <li>vimPlugins.formatter-nvim</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.fzf-lsp-nvim</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.git-blame-nvim</li>
    <li>vimPlugins.gitlinker-nvim</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.gruvbox-material</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.impatient-nvim</li>
    <li>vimPlugins.indent-blankline-nvim</li>
    <li>vimPlugins.julia-vim</li>
    <li>vimPlugins.kanagawa-nvim</li>
    <li>vimPlugins.kommentary</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.lf-vim</li>
    <li>vimPlugins.lir-nvim</li>
    <li>vimPlugins.litee-calltree-nvim</li>
    <li>vimPlugins.litee-filetree-nvim</li>
    <li>vimPlugins.litee-nvim</li>
    <li>vimPlugins.litee-symboltree-nvim</li>
    <li>vimPlugins.lsp_signature-nvim</li>
    <li>vimPlugins.lspsaga-nvim</li>
    <li>vimPlugins.lualine-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.lush-nvim</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vimPlugins.marks-nvim</li>
    <li>vimPlugins.material-nvim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.mru</li>
    <li>vimPlugins.ncm2</li>
    <li>vimPlugins.ncm2-jedi</li>
    <li>vimPlugins.neco-vim</li>
    <li>vimPlugins.neoformat</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neoterm</li>
    <li>vimPlugins.nerdcommenter</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.nord-nvim</li>
    <li>vimPlugins.nord-vim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-base16</li>
    <li>vimPlugins.nvim-biscuits</li>
    <li>vimPlugins.nvim-bqf</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-code-action-menu</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-fzf</li>
    <li>vimPlugins.nvim-gps</li>
    <li>vimPlugins.nvim-lightbulb</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-metals</li>
    <li>vimPlugins.nvim-notify</li>
    <li>vimPlugins.nvim-scrollview</li>
    <li>vimPlugins.nvim-spectre</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-refactor</li>
    <li>vimPlugins.nvim-treesitter-textobjects</li>
    <li>vimPlugins.nvim-ts-rainbow</li>
    <li>vimPlugins.nvim-web-devicons</li>
    <li>vimPlugins.nvim-yarp</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.onedark-nvim</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.plenary-nvim</li>
    <li>vimPlugins.project-nvim</li>
    <li>vimPlugins.quick-scope</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.registers-nvim</li>
    <li>vimPlugins.renamer-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.rnvimr</li>
    <li>vimPlugins.rose-pine</li>
    <li>vimPlugins.rust-tools-nvim</li>
    <li>vimPlugins.seoul256-vim</li>
    <li>vimPlugins.sonokai</li>
    <li>vimPlugins.space-vim</li>
    <li>vimPlugins.splitjoin-vim</li>
    <li>vimPlugins.srcery-vim</li>
    <li>vimPlugins.tagalong-vim</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-file-browser-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.toggleterm-nvim</li>
    <li>vimPlugins.verilog_systemverilog-vim</li>
    <li>vimPlugins.vifm-vim</li>
    <li>vimPlugins.vim-airline</li>
    <li>vimPlugins.vim-android</li>
    <li>vimPlugins.vim-autoformat</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-closetag</li>
    <li>vimPlugins.vim-code-dark</li>
    <li>vimPlugins.vim-endwise</li>
    <li>vimPlugins.vim-floaterm</li>
    <li>vimPlugins.vim-fugitive</li>
    <li>vimPlugins.vim-git</li>
    <li>vimPlugins.vim-gitgutter</li>
    <li>vimPlugins.vim-gnupg</li>
    <li>vimPlugins.vim-go</li>
    <li>vimPlugins.vim-ledger</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-markbar</li>
    <li>vimPlugins.vim-matchup</li>
    <li>vimPlugins.vim-mucomplete</li>
    <li>vimPlugins.vim-oscyank</li>
    <li>vimPlugins.vim-pandoc</li>
    <li>vimPlugins.vim-prosession</li>
    <li>vimPlugins.vim-puppet</li>
    <li>vimPlugins.vim-ruby</li>
    <li>vimPlugins.vim-sandwich</li>
    <li>vimPlugins.vim-scriptease</li>
    <li>vimPlugins.vim-smoothie</li>
    <li>vimPlugins.vim-snippets</li>
    <li>vimPlugins.vim-table-mode</li>
    <li>vimPlugins.vim-test</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.vim-unimpaired</li>
    <li>vimPlugins.vim-wakatime</li>
    <li>vimPlugins.vimagit</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.wilder-nvim</li>
    <li>vimPlugins.yats-vim</li>
    <li>vimPlugins.zephyr-nvim</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
From `pkgs/development/node-packages/node-packages.nix`:

> This file has been generated by node2nix 1.11.1. Do not edit!

**Comment by seanparsons** [comment]
@Dettorer Is this going to be merged into 22.05 as well?

**Comment by seanparsons** [comment]
@Dettorer I only ask because this is breaking in 22.05 as well right now.

**Comment by Lyndeno** [comment]
Is this backportable?

**Comment by Dettorer** [comment]
I think it shouldn't be backported as-is alone anyway since it broke markdown-preview-nvim, it should come with #175708, which fixed that.

**Comment by RossComputerGuy** [comment]
It was merged and I think this should be backported now.

**Comment by vpfeiffer** [comment]
I'm not sure if it was backported since I just updated to nixos 22.05 and experienced the issue.

**Pull request merged**
