### PR TITLE
btop: 1.2.13 -> 1.3.0

### LINKED ISSUE #281107: Build failure: btop on x86_64-darwin x86_64 darwin
### Steps To Reproduce

1. build `btop` on x86_64-darwin

### Build log

[gist link](https://gist.github.com/arichtman/5d9f00b0a6b61ac2d490b0f6beb0ba77)

### Additional context

Nope, thanks for looking!

### Notify maintainers

@rmcgibbo 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-info -m
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"darwin"`
 - nixpkgs: `not found`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by adamcstephens**
## Description of changes

Diff: https://github.com/aristocratos/btop/compare/v1.2.13...v1.3.0

Changelog: https://github.com/aristocratos/btop/blob/v1.3.0/CHANGELOG.md

Closes: https://github.com/NixOS/nixpkgs/issues/281107

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by liff** [comment]
Runs fine on x86_64-linux and aarch64-linux.

**Review by rmcgibbo — APPROVED** [review]

**Comment by reckenrode** [comment]
btop 1.3 supports building with clang, but previous versions didn’t, which is probably why 1.2.13 started failing after https://github.com/NixOS/nixpkgs/commit/c8cadde6999b25e0fd1aac2a7abf450c97fbe277.

I was going to request changing it to build with clang on Darwin, but it seems that’s already the case now. If 1.3 does work, that’s great!

**Comment by marcomayer** [comment]
I get this on MacOS since today (linux works fine):

```
error: builder for '/nix/store/8fcjdyiv29a2k4zbc0kn2w7brgvp7xdq-btop-1.2.13.drv' failed with exit code 2;
       last 10 log lines:
       > LDCXXFLAGS :| -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-clash-protection  -F/nix/store/bz6521203ia6vasgwkc8y8r7y57bllnh-apple-framework-IOKit-11.0.0/Library/Frameworks/ -framework IOKit -framework CoreFoundation -Wno-format-truncation
       > CXXFLAGS   +| $(REQFLAGS) $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)
       > LDFLAGS    +| $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)
       >
       > Building btop++ (v1.2.13) macos arm64
       > Compiling src/btop.cpp
       > clang-16: error: unknown argument: '-ftree-loop-vectorize'
       > clang-16: warning: -framework IOKit: 'linker' input unused [-Wunused-command-line-argument]
       > clang-16: warning: -framework CoreFoundation: 'linker' input unused [-Wunused-command-line-argument]
       > make: *** [Makefile:274: obj/btop.o] Error 1
       For full logs, run 'nix log /nix/store/8fcjdyiv29a2k4zbc0kn2w7brgvp7xdq-btop-1.2.13.drv'.

```

```
nix log /nix/store/8fcjdyiv29a2k4zbc0kn2w7brgvp7xdq-btop-1.2.13.drv
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/8fcjdyiv29a2k4zbc0kn2w7brgvp7xdq-btop-1.2.13.drv^*'
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/7068n74nm3nr7mvx9rszh9c02na2y0n4-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
build flags: SHELL=/nix/store/lv74m20f3z7pa60mxm3zsvxldq031qph-bash-5.2-p21/bin/bash
/nix/store/lv74m20f3z7pa60mxm3zsvxldq031qph-bash-5.2-p21/bin/bash: line 1: sysctl: command not found

 ██████╗ ████████╗ ██████╗ ██████╗
 ██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗   ██╗    ██╗
 ██████╔╝   ██║   ██║   ██║██████╔╝ ██████╗██████╗
 ██╔══██╗   ██║   ██║   ██║██╔═══╝  ╚═██╔═╝╚═██╔═╝
 ██████╔╝   ██║   ╚██████╔╝██║        ╚═╝    ╚═╝
 ╚═════╝    ╚═╝    ╚═════╝ ╚═╝      Makefile v1.5
PLATFORM   ?| macos
ARCH       ?| arm64
CXX        ?| clang++ (16.0.6)
THREADS    :| auto
REQFLAGS   !| -std=c++20
WARNFLAGS  :| -Wall -Wextra -pedantic
OPTFLAGS   :| -O2 -ftree-loop-vectorize -flto=auto
LDCXXFLAGS :| -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-clash-protection  -F/nix/store/bz6521203ia6vasgwkc8y8r7y57bllnh-apple-framework-IOKit-11.0.0/Library/Frameworks/ -framework IOKit -framework CoreFoundation -Wno-format-t>
CXXFLAGS   +| $(REQFLAGS) $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)
LDFLAGS    +| $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)

Building btop++ (v1.2.13) macos arm64
Compiling src/btop.cpp
clang-16: error: unknown argument: '-ftree-loop-vectorize'
clang-16: warning: -framework IOKit: 'linker' input unused [-Wunused-command-line-argument]
clang-16: warning: -framework CoreFoundation: 'linker' input unused [-Wunused-command-line-argument]
make: *** [Makefile:274: obj/btop.o] Error 1
```

Could this be related to the PR?

**Comment by adamcstephens** [comment]
> Building btop++ (v1.2.13) macos arm64

No, you're building the version prior to this PR.

**Comment by marcomayer** [comment]
> > Building btop++ (v1.2.13) macos arm64
> 
> No, you're building the version prior to this PR.

Ok cool, thanks! Will try again once it's in unstable.

**Pull request merged**
