### PR TITLE
pinocchio: 2.7.1 -> 3.0.0

### PR DESCRIPTION
**Pull request by nim65s**
## Description of changes

Pinocchio 2.7.1 -> 3.0.0: https://github.com/stack-of-tasks/pinocchio/releases/tag/v3.0.0
Crocoddyl 2.0.2 -> 2.1.0: https://github.com/loco-3d/crocoddyl/releases/tag/v2.1.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by nim65s** [comment]
Result of `nixpkgs-review pr 315303` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>22 packages built:</summary>
  <ul>
    <li>crocoddyl</li>
    <li>example-robot-data</li>
    <li>jrl-cmakemodules</li>
    <li>pinocchio</li>
    <li>python311Packages.crocoddyl</li>
    <li>python311Packages.eigenpy</li>
    <li>python311Packages.eigenpy.dev</li>
    <li>python311Packages.eigenpy.doc</li>
    <li>python311Packages.example-robot-data</li>
    <li>python311Packages.hpp-fcl</li>
    <li>python311Packages.hpp-fcl.dev</li>
    <li>python311Packages.hpp-fcl.doc</li>
    <li>python311Packages.pinocchio</li>
    <li>python312Packages.crocoddyl</li>
    <li>python312Packages.eigenpy</li>
    <li>python312Packages.eigenpy.dev</li>
    <li>python312Packages.eigenpy.doc</li>
    <li>python312Packages.example-robot-data</li>
    <li>python312Packages.hpp-fcl</li>
    <li>python312Packages.hpp-fcl.dev</li>
    <li>python312Packages.hpp-fcl.doc</li>
    <li>python312Packages.pinocchio</li>
  </ul>
</details>

**Comment by wegank** [comment]
Builds well on my aarch64-darwin machine. I'll check if this is also the case on Hydra tomorrow.

**Comment by wegank** [comment]
Build passes on both Darwin on Hydra, but not on aarch64-linux. Should we disable `test-cpp-algorithm-utils-force` for now since it's flaky enough? https://hydra.nixos.org/job/nixpkgs/trunk/pinocchio.aarch64-linux

**Comment by nim65s** [comment]
Yes, I think we can deactivate it. I'll report that to upstream with low priority (at least untill someone complains about it), so that we can get some time to work on it.

**Pull request merged**
