### PR TITLE
glfw3: general improvements

### LINKED ISSUE #356975: `imhex`: EGL: Library not found
## Describe the bug

ImHex wont launch because of missing egl library

## Steps To Reproduce

N/A (Launch ImHex)

## Expected behavior

N/A

## Screenshots

image

## Additional context

N/A

## Metadata

fetching path input 'path:/nix/store/hfz1qqd0z8amlgn8qwich1dvkmldik36-source'
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.5-zen1, NixOS, 25.05 (Warbler), 25.05.20241115.5e4fbfb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.1
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/user/.config/nix/nix.conf:/nix/store/1c1x2ki3lz5k5nw5z0bl0glizgb0k0rb-plasma-workspace-6.2.3/etc/xdg/nix/nix.conf:/nix/store/ya7vhc1j80aq3vn643k2sq4i7c2vsqr1-kglobalacceld-6.2.3/etc/xdg/nix/nix.conf:/nix/store/pdgsrs8i0crldkl8n2cp9jx3h06rcnzc-baloo-6.8.0/etc/xdg/nix/nix.conf:/home/user/.config/kdedefaults/nix/nix.conf:/nix/store/1c1x2ki3lz5k5nw5z0bl0glizgb0k0rb-plasma-workspace-6.2.3/etc/xdg/nix/nix.conf:/nix/store/ya7vhc1j80aq3vn643k2sq4i7c2vsqr1-kglobalacceld-6.2.3/etc/xdg/nix/nix.conf:/nix/store/pdgsrs8i0crldkl8n2cp9jx3h06rcnzc-baloo-6.8.0/etc/xdg/nix/nix.conf:/nix/store/1c1x2ki3lz5k5nw5z0bl0glizgb0k0rb-plasma-workspace-6.2.3/etc/xdg/nix/nix.conf:/nix/store/ya7vhc1j80aq3vn643k2sq4i7c2vsqr1-kglobalacceld-6.2.3/etc/xdg/nix/nix.conf:/nix/store/pdgsrs8i0crldkl8n2cp9jx3h06rcnzc-baloo-6.8.0/etc/xdg/nix/nix.conf:/home/user/.config/kdedefaults/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/user/.local/share/flatpak/exports/etc/xdg/nix/nix.conf:/var/lib/flatpak/exports/etc/xdg/nix/nix.conf:/home/user/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/user/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/user/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/kqpjnkkpv1drbnvrqbhnyd2ixy9dymzb-lix-2.91.1/share`
 - nixpkgs: `/nix/store/hfz1qqd0z8amlgn8qwich1dvkmldik36-source`
 
## Notify maintainers

@kashw2
@cafkafk 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #357732: glfw: EGL library not found
## Describe the bug

GLFW tries to load libEGL but can't.
```
WARNING: GLFW: Error: 65542 Description: EGL: Library not found
WARNING: GLFW: Failed to initialize Window
```

## Steps To Reproduce

1. Run a GLFW application, for example I'm trying to use Raylib

## Expected behavior

GLFW manages to load libEGL, and the application starts properly.

## Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.8, NixOS, 25.05 (Warbler), 25.05.20241117.2b45d4a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.92.0-devpre20241109_d0e0969
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/diniamo/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/diniamo/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/diniamo/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/diniamo/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/yrgvc5r60s08ykwrfls47jk1xmqqqrvb-lix-patched-2.92.0-devpre20241109_d0e0969/share`
 - nixpkgs: `/nix/store/r5kb5jhbzr07ybvkfqx42z63lqnxbq57-source`
```

Do note though, that this issue isn't present on my system nixpkgs.

## Notify maintainers

@MarcWeber @Scrumplex @Twey 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Scrumplex**
Closes #357732
Closes #356975

Each commit has a description describing its primary change.

The formatting commit is last, to make reviewing easier. The evaluation should not change between `HEAD` and `HEAD^`

One fairly simple package to test these changes with is `raylib-games`. I was able to build and run asteroids both on XWayland and Wayland.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Scrumplex** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 358007`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 2 packages marked as broken and skipped:</summary>
  <ul>
    <li>chickenPackages_5.chickenEggs.hypergiant</li>
    <li>libsForQt5.mapbox-gl-native</li>
  </ul>
</details>
<details>
  <summary>:x: 4 packages failed to build:</summary>
  <ul>
    <li>icesl</li>
    <li>meshlab</li>
    <li>orca-slicer</li>
    <li>orca-slicer.debug</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 110 packages built:</summary>
  <ul>
    <li>_2ship2harkinian</li>
    <li>bambu-studio</li>
    <li>bambu-studio.debug</li>
    <li>blackshades</li>
    <li>blender</li>
    <li>blender-hip</li>
    <li>blendfarm</li>
    <li>bottles</li>
    <li>bottles-unwrapped</li>
    <li>cemu</li>
    <li>chickenPackages_5.chickenEggs.glfw3</li>
    <li>cpu-x</li>
    <li>djv</li>
    <li>dxvk_2</li>
    <li>eepers</li>
    <li>embree</li>
    <li>embree2</li>
    <li>envision</li>
    <li>esshader</li>
    <li>famistudio</li>
    <li>glfw</li>
    <li>glfw3-minecraft</li>
    <li>gnuradioPackages.fosphor</li>
    <li>goxel</li>
    <li>gr-framework</li>
    <li>heroic</li>
    <li>hmcl</li>
    <li>imgui</li>
    <li>imgui.lib</li>
    <li>imhex</li>
    <li>imnodes</li>
    <li>imnodes.dev</li>
    <li>implot</li>
    <li>io</li>
    <li>librealsense-gui</li>
    <li>librealsense-gui.dev</li>
    <li>libsForQt5.maplibre-gl-native</li>
    <li>linux-wallpaperengine</li>
    <li>mangl</li>
    <li>mangohud</li>
    <li>mangohud.doc</li>
    <li>mangohud.man</li>
    <li>midivisualizer</li>
    <li>mlx42</li>
    <li>mmlgui</li>
    <li>monado</li>
    <li>mujoco</li>
    <li>openmvs</li>
    <li>openusd</li>
    <li>picocrypt</li>
    <li>pixelnuke</li>
    <li>portablemc</li>
    <li>portablemc.dist</li>
    <li>prismlauncher</li>
    <li>python311Packages.ale-py</li>
    <li>python311Packages.ale-py.dist</li>
    <li>python311Packages.dm-control</li>
    <li>python311Packages.dm-control.dist</li>
    <li>python311Packages.glfw</li>
    <li>python311Packages.glfw.dist</li>
    <li>python311Packages.gymnasium</li>
    <li>python311Packages.gymnasium.dist</li>
    <li>python311Packages.minari</li>
    <li>python311Packages.minari.dist</li>
    <li>python311Packages.mujoco</li>
    <li>python311Packages.mujoco.dist</li>
    <li>python311Packages.openusd</li>
    <li>python311Packages.pettingzoo</li>
    <li>python311Packages.pettingzoo.dist</li>
    <li>python311Packages.pymeshlab (python312Packages.pymeshlab)</li>
    <li>python311Packages.raylib-python-cffi</li>
    <li>python311Packages.raylib-python-cffi.dist</li>
    <li>python311Packages.shimmy</li>
    <li>python311Packages.shimmy.dist</li>
    <li>python311Packages.skrl</li>
    <li>python311Packages.skrl.dist</li>
    <li>python311Packages.torchrl</li>
    <li>python311Packages.torchrl.dist</li>
    <li>python312Packages.dm-control</li>
    <li>python312Packages.dm-control.dist</li>
    <li>python312Packages.glfw</li>
    <li>python312Packages.glfw.dist</li>
    <li>python312Packages.mujoco</li>
    <li>python312Packages.mujoco.dist</li>
    <li>python312Packages.openusd</li>
    <li>python312Packages.raylib-python-cffi</li>
    <li>python312Packages.raylib-python-cffi.dist</li>
    <li>raylib</li>
    <li>raylib-games</li>
    <li>sbclPackages.cl-glfw</li>
    <li>sbclPackages.cl-glfw3</li>
    <li>sbclPackages.cl-glfw3-examples</li>
    <li>sbclPackages.kons-9</li>
    <li>scopehal-apps</li>
    <li>sdrpp</li>
    <li>silice</li>
    <li>snekim</li>
    <li>sony-headphones-client</li>
    <li>space-station-14-launcher</li>
    <li>taisei</li>
    <li>tev</li>
    <li>tracy</li>
    <li>tracy-x11</li>
    <li>vcv-rack</li>
    <li>vk-bootstrap</li>
    <li>vk-bootstrap.dev</li>
    <li>vkdt</li>
    <li>vlang</li>
    <li>wlay</li>
    <li>woomer</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:fast_forward: 21 packages marked as broken and skipped:</summary>
  <ul>
    <li>blender</li>
    <li>chickenPackages_5.chickenEggs.hypergiant</li>
    <li>esshader</li>
    <li>mujoco</li>
    <li>python311Packages.dm-control</li>
    <li>python311Packages.dm-control.dist</li>
    <li>python311Packages.mujoco</li>
    <li>python311Packages.mujoco.dist</li>
    <li>python311Packages.shimmy</li>
    <li>python311Packages.shimmy.dist</li>
    <li>python311Packages.torchrl</li>
    <li>python311Packages.torchrl.dist</li>
    <li>python312Packages.dm-control</li>
    <li>python312Packages.dm-control.dist</li>
    <li>python312Packages.mujoco</li>
    <li>python312Packages.mujoco.dist</li>
    <li>python312Packages.shimmy</li>
    <li>python312Packages.shimmy.dist</li>
    <li>python312Packages.torchrl</li>
    <li>python312Packages.torchrl.dist</li>
    <li>tev</li>
  </ul>
</details>
<details>
  <summary>:x: 5 packages failed to build:</summary>
  <ul>
    <li>gr-framework</li>
    <li>openusd</li>
    <li>python311Packages.openusd</li>
    <li>python312Packages.openusd</li>
    <li>wlay</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 37 packages built:</summary>
  <ul>
    <li>chickenPackages_5.chickenEggs.glfw3</li>
    <li>embree</li>
    <li>famistudio</li>
    <li>glfw</li>
    <li>glfw3-minecraft</li>
    <li>hmcl</li>
    <li>imhex</li>
    <li>librealsense-gui</li>
    <li>librealsense-gui.dev</li>
    <li>midivisualizer</li>
    <li>mlx42</li>
    <li>mmlgui</li>
    <li>openmvs</li>
    <li>picocrypt</li>
    <li>python311Packages.glfw</li>
    <li>python311Packages.glfw.dist</li>
    <li>python311Packages.raylib-python-cffi</li>
    <li>python311Packages.raylib-python-cffi.dist</li>
    <li>python312Packages.glfw</li>
    <li>python312Packages.glfw.dist</li>
    <li>python312Packages.raylib-python-cffi</li>
    <li>python312Packages.raylib-python-cffi.dist</li>
    <li>raylib</li>
    <li>raylib-games</li>
    <li>sbclPackages.cl-glfw</li>
    <li>sbclPackages.cl-glfw3</li>
    <li>sbclPackages.cl-glfw3-examples</li>
    <li>sbclPackages.kons-9</li>
    <li>scopehal-apps</li>
    <li>sdrpp</li>
    <li>silice</li>
    <li>snekim</li>
    <li>taisei</li>
    <li>tracy (tracy-x11)</li>
    <li>vk-bootstrap</li>
    <li>vk-bootstrap.dev</li>
    <li>vlang</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:fast_forward: 21 packages marked as broken and skipped:</summary>
  <ul>
    <li>blender</li>
    <li>chickenPackages_5.chickenEggs.hypergiant</li>
    <li>esshader</li>
    <li>mujoco</li>
    <li>python311Packages.dm-control</li>
    <li>python311Packages.dm-control.dist</li>
    <li>python311Packages.mujoco</li>
    <li>python311Packages.mujoco.dist</li>
    <li>python311Packages.shimmy</li>
    <li>python311Packages.shimmy.dist</li>
    <li>python311Packages.torchrl</li>
    <li>python311Packages.torchrl.dist</li>
    <li>python312Packages.dm-control</li>
    <li>python312Packages.dm-control.dist</li>
    <li>python312Packages.mujoco</li>
    <li>python312Packages.mujoco.dist</li>
    <li>python312Packages.shimmy</li>
    <li>python312Packages.shimmy.dist</li>
    <li>python312Packages.torchrl</li>
    <li>python312Packages.torchrl.dist</li>
    <li>tev</li>
  </ul>
</details>
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>gr-framework</li>
    <li>wlay</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 40 packages built:</summary>
  <ul>
    <li>chickenPackages_5.chickenEggs.glfw3</li>
    <li>embree</li>
    <li>famistudio</li>
    <li>glfw</li>
    <li>glfw3-minecraft</li>
    <li>hmcl</li>
    <li>imhex</li>
    <li>librealsense-gui</li>
    <li>librealsense-gui.dev</li>
    <li>midivisualizer</li>
    <li>mlx42</li>
    <li>mmlgui</li>
    <li>openmvs</li>
    <li>openusd</li>
    <li>picocrypt</li>
    <li>python311Packages.glfw</li>
    <li>python311Packages.glfw.dist</li>
    <li>python311Packages.openusd</li>
    <li>python311Packages.raylib-python-cffi</li>
    <li>python311Packages.raylib-python-cffi.dist</li>
    <li>python312Packages.glfw</li>
    <li>python312Packages.glfw.dist</li>
    <li>python312Packages.openusd</li>
    <li>python312Packages.raylib-python-cffi</li>
    <li>python312Packages.raylib-python-cffi.dist</li>
    <li>raylib</li>
    <li>raylib-games</li>
    <li>sbclPackages.cl-glfw</li>
    <li>sbclPackages.cl-glfw3</li>
    <li>sbclPackages.cl-glfw3-examples</li>
    <li>sbclPackages.kons-9</li>
    <li>scopehal-apps</li>
    <li>sdrpp</li>
    <li>silice</li>
    <li>snekim</li>
    <li>taisei</li>
    <li>tracy (tracy-x11)</li>
    <li>vk-bootstrap</li>
    <li>vk-bootstrap.dev</li>
    <li>vlang</li>
  </ul>
</details>

**Comment by diniamo** [comment]
Nice, thanks. Not sure how this stuff works exactly, but as a reminder, this should be backported, right?

Also, on the note of raylib-games, it would be be great to get #357729 merged as well, which updates raylib, and pretty much rewrites the entire definition, since it was mostly wrong.

**Comment by Scrumplex** [comment]
The issue(s) fixed by this PR shouldn't be present in 24.11, as #354761 was not backported. I will backport both that and this PR once this is merged.

**Comment by Scrumplex** [comment]
Regarding my nixpkgs-review result above:

**`x86_64-linux`**
- icesl: wrong src hash, same failure on master
- meshlab: unrelated failure on my builder. I was able to build it successfully
- orca-slicer: actually builds :thinking: 

both darwins:
- gr-framework: fails on master
- openusd: fails on master
- wlay: fails on master

**Pull request merged**
