### PR TITLE
Cython 0.28.5, hypothesis 3.69.2

### PR DESCRIPTION
**Pull request by urkud**
###### Motivation for this change
Update 2 packages to their latest versions, fix cython build with python 3.7.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS: python 2.7, 3.6, 3.7
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Please change or re-open this pull request to the staging branch instead of master.

**Comment by FRidh** [comment]
This is on hold until after release of 18.09. At that point we'll do more major updates such as matplotlib.

**Comment by FRidh** [comment]
Cython we may actually want to get in 18.09 though.

**Comment by urkud** [comment]
@FRidh @Mic92 So, should I change the target branch? If yes, which one: staging, or staging-18.09, or something else?

**Comment by dotlambda** [comment]
> We should get Cython in.

It seems it didn't get in. Any reason to still backport?

**Comment by FRidh** [comment]
More recent versions available on master.

**Pull request closed without merging**
