### PR TITLE
nixos/heartbeat: Bring heartbeat in-line with other ELK stack modules

### PR DESCRIPTION
**Pull request by JJJollyjim**
###### Motivation for this change

I want to run heartbeat7 rather than 6.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by JJJollyjim** [comment]
The first commit is my stylistic preference and doesn't matter much, happy to remove it.

**Comment by JJJollyjim** [comment]
Embarrassingly I forgot to actually *use* the package option... force-pushed a fix.

**Comment by JJJollyjim** [comment]
Still relevant afaik, but I moved to prometheus/grafana/loki so ¯\_(ツ)_/¯

**Comment by h7x4** [comment]
I believe this was partly fixed by #180231. But the test changes still seem relevant? Could I ask whether these changes were just more tests, or whether they were related to the new version?

**Pull request closed without merging**
