### PR TITLE
plasma-applet-virtual-desktop-bar: init at unstable-2021-02-20

### LINKED ISSUE #107151: plasma-applet-virtual-desktop-bar
**Project description**
An applet for KDE Plasma panel (or Latte Dock) that lets you switch between virtual desktops and also invoke some actions to dynamically manage them in a convenient way.

**Metadata**

* homepage URL: https://github.com/wsdfhjxc/virtual-desktop-bar
* source URL: https://github.com/wsdfhjxc/virtual-desktop-bar
* license: gpl3
* platforms: linux

### PR DESCRIPTION
**Pull request by lasers**
###### Motivation for this change

Closes https://github.com/NixOS/nixpkgs/issues/107151. 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SCOTT-HAMILTON** [comment]
https://github.com/wsdfhjxc/virtual-desktop-bar/search?q=or+later Seems to give nothing apart from the LICENSE file, so according to https://discourse.nixos.org/t/lib-licenses-gpl3-co-are-now-deprecated/8206, you should use gpl3Only licence.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113786` at 905c777d run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/fa4a3dc80e08b015a16eaa0962c78744">libsForQt512.plasma-applet-virtual-desktop-bar</a></li></li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/cf23cc3293f343292343802969954904">libsForQt5.plasma-applet-virtual-desktop-bar</a></li> (libsForQt515.plasma-applet-virtual-desktop-bar ,plasma5Packages.plasma-applet-virtual-desktop-bar)</li>
    <li><a href="https://gist.github.com/d4daa994d721d16c602c140f6007bcc7">libsForQt514.plasma-applet-virtual-desktop-bar</a></li></li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/desktops/plasma-5/3rdparty/addons/virtual-desktop-bar.nix:32:5:
```
   |
32 |     maintainers = with maintainers; [ ];
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl3` is a deprecated license, check if project uses `gpl3Plus` or `gpl3Only` and change `meta.license` accordingly.

Near pkgs/desktops/plasma-5/3rdparty/addons/virtual-desktop-bar.nix:30:5:
```
   |
30 |     license = licenses.gpl3;
   |     ^
```
</li>
  </ul>
</details>

**Comment by lasers** [comment]
* I fixed the license. It's now `gpl3Only`. 
* Looking for somebody to accept maintainership of this package.
* Awaiting more feedback before I pushed the required changes.

**Comment by peterhoeg** [comment]
Minor thing: version should be `unstable-2021-02-20`. Otherwise all good!

As for maintainership, how about yourself? If so, please add another commit that adds your details to the maintainer file and then tag yourself here.

**Comment by lasers** [comment]
@peterhoeg Fixed. As for maintainership, I'm new and am not there yet with NixOS. Maybe in the future. This is just a copy and paste template from other plasma-applet that worked okay for me. Thank you.

**Comment by peterhoeg** [comment]
New packages need a maintainer to be accepted. Feel free to add me for now.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 113786` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package marked as broken and skipped:
</summary>
<ul>
<li>libsForQt512.plasma-applet-virtual-desktop-bar</li>
</ul>
</details>
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>libsForQt5.plasma-applet-virtual-desktop-bar (libsForQt515.plasma-applet-virtual-desktop-bar ,plasma5Packages.plasma-applet-virtual-desktop-bar)</li>
<li>libsForQt514.plasma-applet-virtual-desktop-bar</li>
</ul>
</details>

**Pull request merged**
