### PR TITLE
foot: 1.5.1 -> 1.6.2

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

[Changelog](https://codeberg.org/dnkl/foot/releases/tag/1.6.0)

* fix build with `clangStdenv`
* support foot's PGO build
  * enable by default if gcc is used (there are some unresolved warnings
    with clang which need to investigated if they are detrimental, but
    it works all in all)
  * build *should* be deterministic with PGO as we use an input file which
    is generated with the same seed everytime.
* apply nixpkgs-fmt

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Supersedes #106529.

### CODE REVIEW

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build foot

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build foot

**Comment by sternenseemann** [comment]
Seems like using a fixed seed for input generation does the trick in terms of deterministic build outputs: I was able to get the exact same build result for gcc PGO build on two different x86_64 machines.

**Comment by sternenseemann** [comment]
Fixed the PGO build for clang as well, now enabled by default for all compilers.

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build foot

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build foot

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build foot

**Comment by WolfangAukang** [comment]
Result of `nixpkgs-review pr 107265` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>foot</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107265` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>foot</li>
  </ul>
</details>

**Pull request merged**
