### PR TITLE
python310Packages.google-*: mass update

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
```
Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/187800

10 packages marked as broken and skipped:
python310Packages.optuna python310Packages.pywick python310Packages.rl-coach python310Packages.shap python310Packages.skorch python39Packages.optuna python39Packages.pywick python39Packages.rl-coach python39Packages.shap python39Packages.skorch

47 packages failed to build:
baserow goobook lbdb privacyidea python310Packages.apache-beam python310Packages.arviz python310Packages.dalle-mini python310Packages.distrax python310Packages.dm-sonnet python310Packages.elegy python310Packages.flax python310Packages.functorch python310Packages.google-cloud-datastore python310Packages.google-cloud-error-reporting python310Packages.google-cloud-logging python310Packages.monai python310Packages.pymc python310Packages.qiskit python310Packages.rlax python310Packages.spacy python310Packages.spacy-transformers python310Packages.stanza python310Packages.textacy python310Packages.treex python310Packages.vqgan-jax python39Packages.arviz python39Packages.dalle-mini python39Packages.deepwave python39Packages.distrax python39Packages.dm-sonnet python39Packages.elegy python39Packages.flax python39Packages.functorch python39Packages.goobook python39Packages.google-cloud-datastore python39Packages.google-cloud-error-reporting python39Packages.google-cloud-logging python39Packages.monai python39Packages.pymc python39Packages.qiskit python39Packages.rlax python39Packages.spacy python39Packages.spacy-transformers python39Packages.stanza python39Packages.textacy python39Packages.treex python39Packages.vqgan-jax

234 packages built:
barman beancount deja-dup duplicity duply dvc-with-remotes fava gam gcalcli git-annex-remote-googledrive gphotos-sync home-assistant-component-tests.google_pubsub home-assistant-component-tests.nest kmymoney kube-hunter ledger2beancount lieer openai parsedmarc python310Packages.baselines python310Packages.beancount_docverif python310Packages.boxx python310Packages.bpycv python310Packages.certbot-dns-google python310Packages.chirpstack-api python310Packages.cirq python310Packages.cirq-google python310Packages.coqui-trainer python310Packages.deepwave python310Packages.django-storages python310Packages.drivelib python310Packages.duckdb python310Packages.duckdb-engine python310Packages.edward python310Packages.ezyrb python310Packages.ffcv python310Packages.gcsfs python310Packages.gensim python310Packages.google-api-core python310Packages.google-api-python-client python310Packages.google-auth python310Packages.google-auth-httplib2 python310Packages.google-auth-oauthlib python310Packages.google-cloud-access-context-manager python310Packages.google-cloud-appengine-logging python310Packages.google-cloud-asset python310Packages.google-cloud-automl python310Packages.google-cloud-bigquery python310Packages.google-cloud-bigquery-datatransfer python310Packages.google-cloud-bigquery-logging python310Packages.google-cloud-bigquery-storage python310Packages.google-cloud-bigtable python310Packages.google-cloud-container python310Packages.google-cloud-core python310Packages.google-cloud-datacatalog python310Packages.google-cloud-dataproc python310Packages.google-cloud-dlp python310Packages.google-cloud-dns python310Packages.google-cloud-firestore python310Packages.google-cloud-iam python310Packages.google-cloud-iam-logging python310Packages.google-cloud-iot python310Packages.google-cloud-kms python310Packages.google-cloud-language python310Packages.google-cloud-monitoring python310Packages.google-cloud-org-policy python310Packages.google-cloud-os-config python310Packages.google-cloud-pubsub python310Packages.google-cloud-redis python310Packages.google-cloud-resource-manager python310Packages.google-cloud-runtimeconfig python310Packages.google-cloud-secret-manager python310Packages.google-cloud-securitycenter python310Packages.google-cloud-spanner python310Packages.google-cloud-speech python310Packages.google-cloud-storage python310Packages.google-cloud-tasks python310Packages.google-cloud-testutils python310Packages.google-cloud-texttospeech python310Packages.google-cloud-trace python310Packages.google-cloud-translate python310Packages.google-cloud-videointelligence python310Packages.google-cloud-vision python310Packages.google-cloud-websecurityscanner python310Packages.google-nest-sdm python310Packages.google-resumable-media python310Packages.gpt-2-simple python310Packages.gspread python310Packages.ibis-framework python310Packages.ignite python310Packages.keyrings-google-artifactregistry-auth python310Packages.kubernetes python310Packages.mask-rcnn python310Packages.oauthenticator python310Packages.objax python310Packages.openshift python310Packages.pathy python310Packages.pot python310Packages.proto-plus python310Packages.pydmd python310Packages.pydrive2 python310Packages.pymanopt python310Packages.pyro-ppl python310Packages.qiskit-machine-learning python310Packages.rising python310Packages.scikit-tda python310Packages.slicer python310Packages.smart-open python310Packages.spacy-loggers python310Packages.tensorboard python310Packages.tensorboardx python310Packages.test-tube python310Packages.tflearn python310Packages.torch-tb-profiler python310Packages.torchgpipe python310Packages.torchinfo python310Packages.torchmetrics python310Packages.torchvision python310Packages.trfl python310Packages.umap-learn python310Packages.wandb python310Packages.weboob python310Packages.woob python310Packages.zcs python39Packages.apache-beam python39Packages.baselines python39Packages.beancount python39Packages.beancount_docverif python39Packages.boxx python39Packages.bpycv python39Packages.certbot-dns-google python39Packages.chirpstack-api python39Packages.cirq python39Packages.cirq-google python39Packages.coqui-trainer python39Packages.django-storages python39Packages.drivelib python39Packages.duckdb python39Packages.duckdb-engine python39Packages.edward python39Packages.ezyrb python39Packages.ffcv python39Packages.gcsfs python39Packages.gensim python39Packages.google-api-core python39Packages.google-api-python-client python39Packages.google-auth python39Packages.google-auth-httplib2 python39Packages.google-auth-oauthlib python39Packages.google-cloud-access-context-manager python39Packages.google-cloud-appengine-logging python39Packages.google-cloud-asset python39Packages.google-cloud-automl python39Packages.google-cloud-bigquery python39Packages.google-cloud-bigquery-datatransfer python39Packages.google-cloud-bigquery-logging python39Packages.google-cloud-bigquery-storage python39Packages.google-cloud-bigtable python39Packages.google-cloud-container python39Packages.google-cloud-core python39Packages.google-cloud-datacatalog python39Packages.google-cloud-dataproc python39Packages.google-cloud-dlp python39Packages.google-cloud-dns python39Packages.google-cloud-firestore python39Packages.google-cloud-iam python39Packages.google-cloud-iam-logging python39Packages.google-cloud-iot python39Packages.google-cloud-kms python39Packages.google-cloud-language python39Packages.google-cloud-monitoring python39Packages.google-cloud-org-policy python39Packages.google-cloud-os-config python39Packages.google-cloud-pubsub python39Packages.google-cloud-redis python39Packages.google-cloud-resource-manager python39Packages.google-cloud-runtimeconfig python39Packages.google-cloud-secret-manager python39Packages.google-cloud-securitycenter python39Packages.google-cloud-spanner python39Packages.google-cloud-speech python39Packages.google-cloud-storage python39Packages.google-cloud-tasks python39Packages.google-cloud-testutils python39Packages.google-cloud-texttospeech python39Packages.google-cloud-trace python39Packages.google-cloud-translate python39Packages.google-cloud-videointelligence python39Packages.google-cloud-vision python39Packages.google-cloud-websecurityscanner python39Packages.google-nest-sdm python39Packages.google-resumable-media python39Packages.gpt-2-simple python39Packages.gspread python39Packages.ibis-framework python39Packages.ignite python39Packages.keyrings-google-artifactregistry-auth python39Packages.kubernetes python39Packages.mask-rcnn python39Packages.oauthenticator python39Packages.objax python39Packages.openai python39Packages.openshift python39Packages.parsedmarc python39Packages.pathy python39Packages.pot python39Packages.proto-plus python39Packages.pydmd python39Packages.pydrive2 python39Packages.pymanopt python39Packages.pyro-ppl python39Packages.qiskit-machine-learning python39Packages.rising python39Packages.scikit-tda python39Packages.slicer python39Packages.smart-open python39Packages.spacy-loggers python39Packages.tensorboard python39Packages.tensorboardx python39Packages.test-tube python39Packages.tflearn python39Packages.torch-tb-profiler python39Packages.torchgpipe python39Packages.torchinfo python39Packages.torchmetrics python39Packages.torchvision python39Packages.trfl python39Packages.umap-learn python39Packages.wandb python39Packages.weboob python39Packages.woob python39Packages.zcs s3ql snakemake

```

**Comment by SuperSandro2000** [comment]
Manually verified the broken builds and most are broken on target branch.

**Review by ruuda — APPROVED** [review]
I haven’t tried to build it or checked any changelogs, but the diff looks good to me, just version bumps and a few small changes to make the tests work.

**Comment by SuperSandro2000** [comment]
@samuela Do you have time to check for regressions in the AI/ML packages that where not there before?

**Comment by samuela** [comment]
@SuperSandro2000 Thanks so much for the heads up! I'll dig into this tonight...

**Comment by samuela** [comment]
Result of `nixpkgs-review pr 187800` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>14 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.optuna</li>
    <li>python310Packages.pytorchWithCuda</li>
    <li>python310Packages.pywick</li>
    <li>python310Packages.rl-coach</li>
    <li>python310Packages.shap</li>
    <li>python310Packages.skorch</li>
    <li>python310Packages.tensorflowWithCuda</li>
    <li>python39Packages.optuna</li>
    <li>python39Packages.pytorchWithCuda</li>
    <li>python39Packages.pywick</li>
    <li>python39Packages.rl-coach</li>
    <li>python39Packages.shap</li>
    <li>python39Packages.skorch</li>
    <li>python39Packages.tensorflowWithCuda</li>
  </ul>
</details>
<details>
  <summary>47 packages failed to build:</summary>
  <ul>
    <li>baserow</li>
    <li>goobook (python310Packages.goobook)</li>
    <li>lbdb</li>
    <li>privacyidea</li>
    <li>python310Packages.apache-beam</li>
    <li>python310Packages.arviz</li>
    <li>python310Packages.dalle-mini</li>
    <li>python310Packages.distrax</li>
    <li>python310Packages.dm-sonnet</li>
    <li>python310Packages.elegy</li>
    <li>python310Packages.flax</li>
    <li>python310Packages.functorch</li>
    <li>python310Packages.monai</li>
    <li>python310Packages.pymanopt</li>
    <li>python310Packages.pymc</li>
    <li>python310Packages.qiskit</li>
    <li>python310Packages.rlax</li>
    <li>python310Packages.spacy</li>
    <li>python310Packages.spacy-transformers</li>
    <li>python310Packages.stanza</li>
    <li>python310Packages.tensorflow-datasets</li>
    <li>python310Packages.textacy</li>
    <li>python310Packages.treex</li>
    <li>python310Packages.vqgan-jax</li>
    <li>python39Packages.apache-beam</li>
    <li>python39Packages.arviz</li>
    <li>python39Packages.dalle-mini</li>
    <li>python39Packages.distrax</li>
    <li>python39Packages.dm-sonnet</li>
    <li>python39Packages.elegy</li>
    <li>python39Packages.flax</li>
    <li>python39Packages.functorch</li>
    <li>python39Packages.goobook</li>
    <li>python39Packages.monai</li>
    <li>python39Packages.oauthenticator</li>
    <li>python39Packages.pot</li>
    <li>python39Packages.pymanopt</li>
    <li>python39Packages.pymc</li>
    <li>python39Packages.qiskit</li>
    <li>python39Packages.rlax</li>
    <li>python39Packages.spacy</li>
    <li>python39Packages.spacy-transformers</li>
    <li>python39Packages.stanza</li>
    <li>python39Packages.tensorflow-datasets</li>
    <li>python39Packages.textacy</li>
    <li>python39Packages.treex</li>
    <li>python39Packages.vqgan-jax</li>
  </ul>
</details>
<details>
  <summary>253 packages built:</summary>
  <ul>
    <li>barman</li>
    <li>beancount (python310Packages.beancount)</li>
    <li>deja-dup</li>
    <li>duplicity</li>
    <li>duply</li>
    <li>dvc-with-remotes</li>
    <li>fava</li>
    <li>gam</li>
    <li>gcalcli</li>
    <li>git-annex-remote-googledrive</li>
    <li>gphotos-sync</li>
    <li>gpt2tc</li>
    <li>home-assistant-component-tests.google_pubsub</li>
    <li>home-assistant-component-tests.nest</li>
    <li>kmymoney</li>
    <li>kube-hunter</li>
    <li>ledger2beancount</li>
    <li>libtensorflow</li>
    <li>lieer</li>
    <li>openai (python310Packages.openai)</li>
    <li>parsedmarc (python310Packages.parsedmarc)</li>
    <li>python310Packages.baselines</li>
    <li>python310Packages.beancount_docverif</li>
    <li>python310Packages.boxx</li>
    <li>python310Packages.bpycv</li>
    <li>python310Packages.certbot-dns-google</li>
    <li>python310Packages.chirpstack-api</li>
    <li>python310Packages.cirq</li>
    <li>python310Packages.cirq-google</li>
    <li>python310Packages.coqui-trainer</li>
    <li>python310Packages.deepwave</li>
    <li>python310Packages.django-storages</li>
    <li>python310Packages.drivelib</li>
    <li>python310Packages.duckdb</li>
    <li>python310Packages.duckdb-engine</li>
    <li>python310Packages.edward</li>
    <li>python310Packages.ezyrb</li>
    <li>python310Packages.ffcv</li>
    <li>python310Packages.gcsfs</li>
    <li>python310Packages.gensim</li>
    <li>python310Packages.google-api-core</li>
    <li>python310Packages.google-api-python-client</li>
    <li>python310Packages.google-auth</li>
    <li>python310Packages.google-auth-httplib2</li>
    <li>python310Packages.google-auth-oauthlib</li>
    <li>python310Packages.google-cloud-access-context-manager</li>
    <li>python310Packages.google-cloud-appengine-logging</li>
    <li>python310Packages.google-cloud-asset</li>
    <li>python310Packages.google-cloud-automl</li>
    <li>python310Packages.google-cloud-bigquery</li>
    <li>python310Packages.google-cloud-bigquery-datatransfer</li>
    <li>python310Packages.google-cloud-bigquery-logging</li>
    <li>python310Packages.google-cloud-bigquery-storage</li>
    <li>python310Packages.google-cloud-bigtable</li>
    <li>python310Packages.google-cloud-container</li>
    <li>python310Packages.google-cloud-core</li>
    <li>python310Packages.google-cloud-datacatalog</li>
    <li>python310Packages.google-cloud-dataproc</li>
    <li>python310Packages.google-cloud-datastore</li>
    <li>python310Packages.google-cloud-dlp</li>
    <li>python310Packages.google-cloud-dns</li>
    <li>python310Packages.google-cloud-error-reporting</li>
    <li>python310Packages.google-cloud-firestore</li>
    <li>python310Packages.google-cloud-iam</li>
    <li>python310Packages.google-cloud-iam-logging</li>
    <li>python310Packages.google-cloud-iot</li>
    <li>python310Packages.google-cloud-kms</li>
    <li>python310Packages.google-cloud-language</li>
    <li>python310Packages.google-cloud-logging</li>
    <li>python310Packages.google-cloud-monitoring</li>
    <li>python310Packages.google-cloud-org-policy</li>
    <li>python310Packages.google-cloud-os-config</li>
    <li>python310Packages.google-cloud-pubsub</li>
    <li>python310Packages.google-cloud-redis</li>
    <li>python310Packages.google-cloud-resource-manager</li>
    <li>python310Packages.google-cloud-runtimeconfig</li>
    <li>python310Packages.google-cloud-secret-manager</li>
    <li>python310Packages.google-cloud-securitycenter</li>
    <li>python310Packages.google-cloud-spanner</li>
    <li>python310Packages.google-cloud-speech</li>
    <li>python310Packages.google-cloud-storage</li>
    <li>python310Packages.google-cloud-tasks</li>
    <li>python310Packages.google-cloud-testutils</li>
    <li>python310Packages.google-cloud-texttospeech</li>
    <li>python310Packages.google-cloud-trace</li>
    <li>python310Packages.google-cloud-translate</li>
    <li>python310Packages.google-cloud-videointelligence</li>
    <li>python310Packages.google-cloud-vision</li>
    <li>python310Packages.google-cloud-websecurityscanner</li>
    <li>python310Packages.google-nest-sdm</li>
    <li>python310Packages.google-resumable-media</li>
    <li>python310Packages.gpt-2-simple</li>
    <li>python310Packages.gspread</li>
    <li>python310Packages.ibis-framework</li>
    <li>python310Packages.ignite</li>
    <li>python310Packages.keyrings-google-artifactregistry-auth</li>
    <li>python310Packages.kubernetes</li>
    <li>python310Packages.mask-rcnn</li>
    <li>python310Packages.oauthenticator</li>
    <li>python310Packages.objax</li>
    <li>python310Packages.openshift</li>
    <li>python310Packages.pathy</li>
    <li>python310Packages.pot</li>
    <li>python310Packages.proto-plus</li>
    <li>python310Packages.pydmd</li>
    <li>python310Packages.pydrive2</li>
    <li>python310Packages.pyro-ppl</li>
    <li>python310Packages.pytorch (python310Packages.pytorchWithoutCuda)</li>
    <li>python310Packages.pytorch-lightning</li>
    <li>python310Packages.pytorch-metric-learning</li>
    <li>python310Packages.pytorch-pfn-extras</li>
    <li>python310Packages.qiskit-machine-learning</li>
    <li>python310Packages.rising</li>
    <li>python310Packages.scikit-tda</li>
    <li>python310Packages.slicer</li>
    <li>python310Packages.smart-open</li>
    <li>python310Packages.spacy-loggers</li>
    <li>python310Packages.tensorboard</li>
    <li>python310Packages.tensorboardx</li>
    <li>python310Packages.tensorflow (python310Packages.tensorflow-build ,python310Packages.tensorflowWithoutCuda)</li>
    <li>python310Packages.tensorflow-bin</li>
    <li>python310Packages.tensorflow-probability</li>
    <li>python310Packages.test-tube</li>
    <li>python310Packages.tflearn</li>
    <li>python310Packages.torch-tb-profiler</li>
    <li>python310Packages.torchgpipe</li>
    <li>python310Packages.torchinfo</li>
    <li>python310Packages.torchmetrics</li>
    <li>python310Packages.torchvision</li>
    <li>python310Packages.trfl</li>
    <li>python310Packages.umap-learn</li>
    <li>python310Packages.wandb</li>
    <li>python310Packages.weboob</li>
    <li>python310Packages.woob</li>
    <li>python310Packages.zcs</li>
    <li>python39Packages.baselines</li>
    <li>python39Packages.beancount</li>
    <li>python39Packages.beancount_docverif</li>
    <li>python39Packages.boxx</li>
    <li>python39Packages.bpycv</li>
    <li>python39Packages.certbot-dns-google</li>
    <li>python39Packages.chirpstack-api</li>
    <li>python39Packages.cirq</li>
    <li>python39Packages.cirq-google</li>
    <li>python39Packages.coqui-trainer</li>
    <li>python39Packages.deepwave</li>
    <li>python39Packages.django-storages</li>
    <li>python39Packages.drivelib</li>
    <li>python39Packages.duckdb</li>
    <li>python39Packages.duckdb-engine</li>
    <li>python39Packages.edward</li>
    <li>python39Packages.ezyrb</li>
    <li>python39Packages.ffcv</li>
    <li>python39Packages.gcsfs</li>
    <li>python39Packages.gensim</li>
    <li>python39Packages.google-api-core</li>
    <li>python39Packages.google-api-python-client</li>
    <li>python39Packages.google-auth</li>
    <li>python39Packages.google-auth-httplib2</li>
    <li>python39Packages.google-auth-oauthlib</li>
    <li>python39Packages.google-cloud-access-context-manager</li>
    <li>python39Packages.google-cloud-appengine-logging</li>
    <li>python39Packages.google-cloud-asset</li>
    <li>python39Packages.google-cloud-automl</li>
    <li>python39Packages.google-cloud-bigquery</li>
    <li>python39Packages.google-cloud-bigquery-datatransfer</li>
    <li>python39Packages.google-cloud-bigquery-logging</li>
    <li>python39Packages.google-cloud-bigquery-storage</li>
    <li>python39Packages.google-cloud-bigtable</li>
    <li>python39Packages.google-cloud-container</li>
    <li>python39Packages.google-cloud-core</li>
    <li>python39Packages.google-cloud-datacatalog</li>
    <li>python39Packages.google-cloud-dataproc</li>
    <li>python39Packages.google-cloud-datastore</li>
    <li>python39Packages.google-cloud-dlp</li>
    <li>python39Packages.google-cloud-dns</li>
    <li>python39Packages.google-cloud-error-reporting</li>
    <li>python39Packages.google-cloud-firestore</li>
    <li>python39Packages.google-cloud-iam</li>
    <li>python39Packages.google-cloud-iam-logging</li>
    <li>python39Packages.google-cloud-iot</li>
    <li>python39Packages.google-cloud-kms</li>
    <li>python39Packages.google-cloud-language</li>
    <li>python39Packages.google-cloud-logging</li>
    <li>python39Packages.google-cloud-monitoring</li>
    <li>python39Packages.google-cloud-org-policy</li>
    <li>python39Packages.google-cloud-os-config</li>
    <li>python39Packages.google-cloud-pubsub</li>
    <li>python39Packages.google-cloud-redis</li>
    <li>python39Packages.google-cloud-resource-manager</li>
    <li>python39Packages.google-cloud-runtimeconfig</li>
    <li>python39Packages.google-cloud-secret-manager</li>
    <li>python39Packages.google-cloud-securitycenter</li>
    <li>python39Packages.google-cloud-spanner</li>
    <li>python39Packages.google-cloud-speech</li>
    <li>python39Packages.google-cloud-storage</li>
    <li>python39Packages.google-cloud-tasks</li>
    <li>python39Packages.google-cloud-testutils</li>
    <li>python39Packages.google-cloud-texttospeech</li>
    <li>python39Packages.google-cloud-trace</li>
    <li>python39Packages.google-cloud-translate</li>
    <li>python39Packages.google-cloud-videointelligence</li>
    <li>python39Packages.google-cloud-vision</li>
    <li>python39Packages.google-cloud-websecurityscanner</li>
    <li>python39Packages.google-nest-sdm</li>
    <li>python39Packages.google-resumable-media</li>
    <li>python39Packages.gpt-2-simple</li>
    <li>python39Packages.gspread</li>
    <li>python39Packages.ibis-framework</li>
    <li>python39Packages.ignite</li>
    <li>python39Packages.keyrings-google-artifactregistry-auth</li>
    <li>python39Packages.kubernetes</li>
    <li>python39Packages.mask-rcnn</li>
    <li>python39Packages.objax</li>
    <li>python39Packages.openai</li>
    <li>python39Packages.openshift</li>
    <li>python39Packages.parsedmarc</li>
    <li>python39Packages.pathy</li>
    <li>python39Packages.proto-plus</li>
    <li>python39Packages.pydmd</li>
    <li>python39Packages.pydrive2</li>
    <li>python39Packages.pyro-ppl</li>
    <li>python39Packages.pytorch (python39Packages.pytorchWithoutCuda)</li>
    <li>python39Packages.pytorch-lightning</li>
    <li>python39Packages.pytorch-metric-learning</li>
    <li>python39Packages.pytorch-pfn-extras</li>
    <li>python39Packages.qiskit-machine-learning</li>
    <li>python39Packages.rising</li>
    <li>python39Packages.scikit-tda</li>
    <li>python39Packages.slicer</li>
    <li>python39Packages.smart-open</li>
    <li>python39Packages.spacy-loggers</li>
    <li>python39Packages.tensorboard</li>
    <li>python39Packages.tensorboardx</li>
    <li>python39Packages.tensorflow (python39Packages.tensorflow-build ,python39Packages.tensorflowWithoutCuda)</li>
    <li>python39Packages.tensorflow-bin</li>
    <li>python39Packages.tensorflow-probability</li>
    <li>python39Packages.test-tube</li>
    <li>python39Packages.tflearn</li>
    <li>python39Packages.torch-tb-profiler</li>
    <li>python39Packages.torchgpipe</li>
    <li>python39Packages.torchinfo</li>
    <li>python39Packages.torchmetrics</li>
    <li>python39Packages.torchvision</li>
    <li>python39Packages.trfl</li>
    <li>python39Packages.umap-learn</li>
    <li>python39Packages.wandb</li>
    <li>python39Packages.weboob</li>
    <li>python39Packages.woob</li>
    <li>python39Packages.zcs</li>
    <li>s3ql</li>
    <li>snakemake</li>
    <li>tts</li>
  </ul>
</details>

**Comment by samuela** [comment]
The biggest new failure AFAICT is python310Packages.apache-beam, which is [building fine on master](https://hydra.nixos.org/build/188038838). Here's the [full log](https://gist.github.com/samuela/9d194364ebe5a318380306eb9aac8887) of build errors from nixpkgs-review. Lots of things depend on apache-beam, so I think that's where a bunch of the other failures are originating from...

**Comment by SuperSandro2000** [comment]
I fixed goobook but now scikit-learn tests are failing crashing which I leave up to you since they seem to be unrelated to google-* bumps.

**Comment by samuela** [comment]
> I fixed goobook but now 6 scikit-learn tests are crashing which I leave up to you since they seem to be unrelated to google-* bumps.

Yeah, those seem entirely unrelated so I'm not worried about those.

The apache-beam failure breaks a lot of stuff though. Would that be a difficult fix?

**Comment by SuperSandro2000** [comment]
> The apache-beam failure breaks a lot of stuff though. Would that be a difficult fix?

It relies on scikit-learn. How about moving apache-beam out of pythonPackages?

**Comment by samuela** [comment]
> How about moving apache-beam out of pythonPackages?

apache-beam is a widely relied upon python package. It's inclusion in pythonPackages is essential. One can't just kick someone else's package out of pythonPackages any time it mildly inconveniences one of their PRs.

> It relies on scikit-learn.

I'm looking at [the derivation](https://github.com/NixOS/nixpkgs/blob/nixos-22.05/pkgs/development/python-modules/apache-beam/default.nix), but I'm not seeing that... How does it rely on scikit-learn?

**Comment by SuperSandro2000** [comment]
> I'm looking at [the derivation](https://github.com/NixOS/nixpkgs/blob/nixos-22.05/pkgs/development/python-modules/apache-beam/default.nix?rgh-link-date=2022-08-28T13%3A44%3A11Z), but I'm not seeing that... How does it rely on scikit-learn?

You where looking at stable, so it probably only got introduced recently https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/apache-beam/default.nix#L41

**Comment by SuperSandro2000** [comment]
> apache-beam is a widely relied upon python package. It's inclusion in pythonPackages is essential. One can't just kick someone else's package out of pythonPackages any time it mildly inconveniences one of their PRs.

That was only an idea floating around but when it is a requirement of other packages we ofcourse can't do that so easily.

**Pull request merged**
