### PR TITLE
nixos/tests/misc: support old and new path-info output structure

### PR DESCRIPTION
**Pull request by mweinelt**
## Description of changes

https://github.com/NixOS/nixpkgs/pull/315262#issuecomment-2139134458

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by fricklerhandwerk** [comment]
@nixos/nix-team Why in the world is Nixpkgs even testing against Nix experimental commands? Looking at [commit history](https://github.com/NixOS/nixpkgs/blame/a047bae9f3f9a0f3a00964f1b6bbfef61485880d/nixos/tests/misc.nix), this has been added before experimental features were a thing. I suggest removing that test and only adding it back when the command is stabilized.

**Comment by K900** [comment]
Going to untag as channel-blocker as the Nix bump was reverted.

**Comment by Mic92** [comment]
> @NixOS/nix-team Why in the world is Nixpkgs even testing against Nix experimental commands? That's exactly how you make them unchangeable or annoy everyone with breakages.
> 
> Looking at [commit history](https://github.com/NixOS/nixpkgs/blame/a047bae9f3f9a0f3a00964f1b6bbfef61485880d/nixos/tests/misc.nix), this has been added before experimental features were a thing. I suggest removing that test and only adding it back when the command is stabilized.

I think we are beyond a point where we can reasonable treat these commands as experimental. Even if it doesn't break in nixpkgs, it will still break other users, since these commands have been cooking for too long in an "experimental" state.

**Comment by mweinelt** [comment]
If it broke, then yes, `passthru.tests` seems appropriate.  Naming the test `misc` :shrug:

**Comment by Mic92** [comment]
Yeah. Terrible name. I will come up with something else.

**Comment by lilyinstarlight** [comment]
> I think we are beyond a point where we can no longer reasonable treat these commands as experimental. Even if it doesn't break in nixpkgs, it will still break other users, since these commands have been cooking for too long in an "experimental" state.

This command has been present since Nix 2.0 and was added to the NixOS misc tests during the Nix 2.0 bump PR (<https://github.com/NixOS/nixpkgs/pull/34636/files#diff-5eb2258233433ba8710976a266f30f16a70d92c633d36706072a095f91dc50a9R38>)

I'm just providing context, though, so I won't make any comment either way about whether it's appropriate the command was later made "experimental" when that ability was added (like the `nix repl` command) or whether it should be removed from the test until the command is "stabilized"

**Comment by Mic92** [comment]
Tested that this, fixes the nix upgrade.

**Comment by Ericson2314** [comment]
> I currently don't see a good replacement for this command in the old cli interface.

There is a mishmash of `nix-store` commands to query individual fields of the path info JSON. Agreed that is much less nice to use! 

> If we make sure that we run this NixOS test on every nix version bump, than we can also fix it.

That's true. If we the tests make clear they are not locking down features users should rely on, but just sanity checking Nixpkgs' own internal usage of experimental stuff, it is less bad.

**Pull request merged**
