### PR TITLE
kratos: 0.6.0-alpha.1 -> 0.6.0-alpha.2

### PR DESCRIPTION
**Pull request by MrMebelMan**
###### Motivation for this change

Update ORY Kratos to a newer version.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date (mostly)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 122499` at 40d02e73 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>kratos</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>error: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-flags-spaces.md">no-flags-spaces</a>

`buildFlags` cannot contain spaces, please use `buildFlagsArray` in Bash.

Near pkgs/applications/misc/kratos/default.nix:18:3:
```
   |
18 |   buildFlags = [ "-tags sqlite" ];
   |   ^
```
</li>
  </ul>
</details>

**Comment by CMCDragonkai** [comment]
@MrMebelMan I've been testing out the Kratos on NixOS.

Everything seems to work except for SMTP.

Did you test this out as well?

I posted my problem up here: https://github.com/ory/kratos/issues/781#issuecomment-851766787

Just basic smtp isn't working with MailHog, even though MailHog works with other client sending emails.

**Comment by MrMebelMan** [comment]
I've tried using mailslurper and Gmail and had no problems with SMTP whatsoever :thinking: 
Maybe try using smtps instead of smtp in config?

**Comment by MrMebelMan** [comment]
@CMCDragonkai I've tried using mailslurper and Gmail and had no problems with SMTP whatsoever :thinking: 
Does it work if you use `smtps` instead of `smtp` in your connection string?

**Comment by CMCDragonkai** [comment]
Apologies, it was a configuration mistake!

On 3 June 2021 2:31:13 am AEST, Vladyslav Burzakovskyy ***@***.***> wrote:
>I've tried using mailslurper and Gmail and had no problems with SMTP
>whatsoever :thinking: 
>Maybe try using smtps instead of smtp in config?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/NixOS/nixpkgs/pull/122499#issuecomment-853174308

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by CMCDragonkai** [comment]
Did you ever package Ory Hydra as well?

**Pull request merged**
