### PR TITLE
Added Asterisk telephony server

### PR DESCRIPTION
**Pull request by auntieNeo**
I packaged the Asterisk telephony server. The derivation has a few hacks to the paths to make it behave better at runtime.

A NixOS module is forthcoming; I just need to iron out the config options and documentation. If the pull takes more than a few days, I will probably just push the module to this same branch.

The derivation itself works fine standalone without the module, given the runtime path hacks.

### CODE REVIEW

**Comment by jagajaga** [comment]
work in progress?

**Comment by auntieNeo** [comment]
Maybe I submitted the pull request a bit early to force myself to write the module documentation... that psychology seems to have worked, because I just pushed it.

I'm pretty happy with this module. The hello world example in the module documentation is the shortest real example I could come up with, and it works with my smartphone. I have been using this module to do rudimentary conferencing for about two weeks now.

I hope those options cover 99% of asterisk use cases. Asterisk is pretty flexible with regards to configuration, and it's all done by those .conf files.

I'm not so sure about /var, so I don't touch it after creating the /var directories. In the future an upgrade mechanism might be needed.

There's a "FIXME" in there for the additional arguments. I don't know enough bash-fu to account for whitespace there, but I could find several other modules that don't account for it either.

**Comment by jagajaga** [comment]
Nice. But please resolve conflicts with master.

**Comment by jagajaga** [comment]
Squash last commit into previous one, please :)

**Comment by auntieNeo** [comment]
Sorry about that. It should be good now.

**Pull request merged**
