### PR TITLE
macdylibbundler: init

### PR DESCRIPTION
**Pull request by nomeata**
###### Motivation for this change

which I found useful to make self-contained releases of binaries built
on osx.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nomeata** [comment]
It builds on non-osx systems, but is less useful there because it wants `otool` in the PATH. Not sure if `otool` can be packaged, or if this package should be restricted to OSX then.

**Comment by matthewbauer** [comment]
darwin.cctools contains otool. I think it makes sense to wrap it. We can definitely get it to work on linux.

**Comment by nomeata** [comment]
BTW, I have no `version` fields; is that ok for a package installed from GitHub where upstream does not define versions?

**Comment by matthewbauer** [comment]
I think you should use the date the commit was made. So ```version = "20180825"```

**Pull request merged**
