### PR TITLE
bisq-desktop:  Add UI scale option

### PR DESCRIPTION
**Pull request by ekimber**
Add option to scale the Bisq UI so that it is readable on hidpi screens.

###### Description of changes

Added the option `ui-scale` to the bisq launcher script so that it can be configured to be readable on 4k, 8k monitors etc.

###### Things done
- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ekimber** [comment]
@emmanuelrosa Does this change make sense? I find that I can't really use the app without scaling

**Review by emmanuelrosa — CHANGES_REQUESTED** [review]
There could be a number of JAVA_TOOL_OPTIONS that a user may wish to set.

Instead of the "ui-scale" attribute, you can have a "javaToolOptsFunc" attribute which is a function that gets called with the attribute set:

`{ "-XX:+UseG1GC" = null;  "-XX:MaxHeapFreeRatio" = 10; "-XX:MinHeapFreeRatio" = 5;  "-XX:+UseStringDeduplication" = null; }`

... and returns a new attribute set to represent the JAVA_TOOL_OPTIONS. By default, said function would simply return its input. But users can use the function to make changes to JAVA_TOOL_OPTIONS.

`(bisq-desktop.override { javaToolOptsFunc = defaults: defaults // { "-Dglass.gtk.uiScale" = "1.0";}; })`

That attribute set can then be converted into the JAVA_TOOL_OPTIONS string.

**Comment by ekimber** [comment]
@emmanuelrosa

I've modified it along the lines you suggested, except that it is just a list of string options, e.g.
`bisq-desktop.override {
    javaToolOptsFunc = defaults: defaults ++ [ "-Dglass.gtk.uiScale=2.0" ]; };`

**Review by emmanuelrosa — APPROVED** [review]
I didn't test the UI scale option because I don't have the appropriate hardware. But I confirm that by default the original functionality remains intact.

For anyone who may wish to modify the default JAVA_TOOL_OPTIONS, you can use `builtins.filter` to remove an option and list concatenation to add one:

```
(bisq-desktop.override {
  javaToolOptsFunc = orig: (builtins.filter (opt: opt != "-XX:MinHeapFreeRatio=5") orig) ++ [ "-XX:MinHeapFreeRatio=10" ];
})
```

However, keep in mind that when changing an existing option there's the potential for breakage in the event that a default option changes. That's because the filter would no longer match and therefore the original value would be silently left intact. It's possible to mitigate this some what by matching with a regular expression or a substring.

**Comment by emmanuelrosa** [comment]
This PR is replaced by #229319

**Pull request closed without merging**
