### PR TITLE
Fix string misuse

### PR DESCRIPTION
**Pull request by Lucus16**
###### Motivation for this change

In some cases, simple strings are used where indented strings should be used. This looks silly, has unexpected semantics, and hinders automatic formatters. I cleaned up the formatting surrounding the changes a little bit because I didn't want to introduce inconsistent formatting.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
Nice, sounds good to me, I didn't even realize this problem was so prevalent in nixpkgs

**Comment by yorickvP** [comment]
@GrahamcOfBorg build i810switch

**Review by yorickvP — APPROVED** [review]
This all still parses and quick manual review seems to check out.

**Comment by Infinisil** [comment]
Where do all the rebuilds come from?

**Comment by yorickvP** [comment]
@Infinisil this is a semantic change in that "" includes indentation and '''' does not

**Comment by Infinisil** [comment]
Yes, but even still you only changed about 70 files, but the @GrahamcOfBorg evaluation identified over 2500 packages as needing a rebuild (see https://gist.github.com/GrahamcOfBorg/dee66ed5bcce589dd91d376878215a89). I'm wondering which parts of your changes caused this many. Probably some dependency that's used by many packages

**Comment by ajs124** [comment]
Why were some of the enable options changed to a multi-line string with only one line of content, whereas others were changed to a simple string? (e.g. memcached vs yandex-disk or bind)

**Comment by Lucus16** [comment]
I based that decision mostly on what the surrounding code did, but I admit
I didn't give it too much thought.

**Comment by FRidh** [comment]
The rebuilds is caused because the '' string type removes indentation, and thus the derivation is different. See e.g. https://github.com/NixOS/nixpkgs/pull/65367/files#diff-a7c4646d4130686ce08465f99cc70c97

**Comment by Infinisil** [comment]
Yes I got that @FRidh, but I'm asking for why there are *so many* rebuilds, not *why* there are at all.

**Comment by Lucus16** [comment]
Among others, `git` changed because it depends on `docbook_xml_dtd_412`, which had its indentation changed.

**Comment by FRidh** [comment]
@grahamcofborg eval

**Comment by Lucus16** [comment]
What's the best way forward? Should we wait for a `git` update? Do the changes look acceptable other than the large number of rebuilds?

**Comment by yorickvP** [comment]
Git updates aren't mass rebuilds, since they are used in fixed output
derivations. It must be something else.

**Comment by FRidh** [comment]
I guess wxwidgets.

**Comment by doronbehar** [comment]
There are merged conflicts now.

**Comment by yorickvP** [comment]
This is going to break again pretty soon after updating. Is it scriptable?

**Comment by Lucus16** [comment]
Not really, there's too much variation in how strings are misused.

**Comment by SuperSandro2000** [comment]
@Lucus16 please solve the many merge conflicts and I'll merge it.

**Pull request closed without merging**
