### PR TITLE
pythonPackages.django: 1.11 -> 2.2

### PR DESCRIPTION
**Pull request by lsix**
###### Motivation for this change

Django-1.11 will end its support before in march 2020, so I try to get rid of it before the 20.03 release.

This PR tries to fix most breakages.

This is still a WIP, but I’d like to have it integreated before 20.03 feature freeze, even if I still have some fixing to do after.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lsix** [comment]
This PR tends to break multiple packages (among them `mailan-web`), which is unfortunate.

I would prefer to have then broken “now” and make sure that what we ship can be supported for the lifetime of `release-20.03`, but that is a personal opinion.

@jonringer @FRidh  any thought on that ?

**Comment by FRidh** [comment]
I indeed think this should ship in 20.03 as well. We do need to ensure `mailman-web` functions, at least in the NixOS module.

**Comment by lsix** [comment]
I have updated the definition of `mailman-web` (in `all-packages.nix`) to use use django-1.11 (the one used in the module). Hopefully it will be updated to support django-2.2 before django-1.11 reaches EOL (or I’ll do it if I have some time)

**Comment by FRidh** [comment]
cc @alyssais regarding mailman-web

**Comment by lsix** [comment]
I have fixed all django related errors or disabled packages that does not support django-2.2 (yet).

Few errors remain, but only for packages already broken on master.

**Comment by lsix** [comment]
For the record, still broken packages are:

```
$ nix-review pr 78711
[…]
6 package failed to build:
python37Packages.google_cloud_error_reporting python37Packages.google_cloud_logging python37Packages.pelican python38Packages.google_cloud_error_reporting python38Packages.google_cloud_logging python38Packages.pelican

139 package built:
[…]
```

**Comment by FRidh** [comment]
Thank you! I've fixed the evaluation error and pushed the commits to https://github.com/NixOS/nixpkgs/pull/79375.

**Pull request closed without merging**
