### PR TITLE
vimPlugins.telescope-media-files-nvim: init at 2021-10-21

### LINKED ISSUE #182734: vimPlugins: telescope-media-files-nvim
**Project description**
Telescope extension to preview media files using Ueberzug.

**Metadata**

* homepage URL: https://github.com/nvim-telescope/telescope-media-files.nvim
* source URL: https://github.com/nvim-telescope/telescope-media-files.nvim
* license: mit
* platforms: linux

### PR DESCRIPTION
**Pull request by pyrox0**
###### Description of changes
Adds telescope-media-files.nvim with its overrides, and closes #182734.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
the global update breaks vim-clap (try nixpkgs-review) 
```
1 package failed to build:
vimPlugins.vim-clap
```
so either you discard that commit or you fix vim-clap (updating rust hashes I believe).

**Comment by theHedgehog0** [comment]
> 

Should be fixed now!

**Comment by teto** [comment]
could you post the results for nixpkgs-review please ? I can't run it at the moment

**Comment by theHedgehog0** [comment]
Result of `nixpkgs-review pr 183091` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>205 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>tests.vim.test_vim_with_vim_nix</li>
    <li>vimPlugins.Coqtail</li>
    <li>vimPlugins.FTerm-nvim</li>
    <li>vimPlugins.FixCursorHold-nvim</li>
    <li>vimPlugins.LeaderF</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.SpaceCamp</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.alpha-nvim</li>
    <li>vimPlugins.aurora</li>
    <li>vimPlugins.auto-session</li>
    <li>vimPlugins.barbar-nvim</li>
    <li>vimPlugins.bufferline-nvim</li>
    <li>vimPlugins.calendar-vim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.catppuccin-vim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.clangd_extensions-nvim</li>
    <li>vimPlugins.cmp-clippy</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-dictionary</li>
    <li>vimPlugins.cmp-digraphs</li>
    <li>vimPlugins.cmp-fish</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-git</li>
    <li>vimPlugins.cmp-greek</li>
    <li>vimPlugins.cmp-look</li>
    <li>vimPlugins.cmp-neosnippet</li>
    <li>vimPlugins.cmp-npm</li>
    <li>vimPlugins.cmp-nvim-lsp-signature-help</li>
    <li>vimPlugins.cmp-nvim-tags</li>
    <li>vimPlugins.cmp-pandoc-nvim</li>
    <li>vimPlugins.cmp-path</li>
    <li>vimPlugins.cmp-rg</li>
    <li>vimPlugins.cmp-snippy</li>
    <li>vimPlugins.cmp-tabnine</li>
    <li>vimPlugins.cmp-tmux</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.cmp-vimwiki-tags</li>
    <li>vimPlugins.cmp-zsh</li>
    <li>vimPlugins.coc-lua</li>
    <li>vimPlugins.comment-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.conjure</li>
    <li>vimPlugins.coq-artifacts</li>
    <li>vimPlugins.coq-thirdparty</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.csharpls-extended-lsp-nvim</li>
    <li>vimPlugins.dashboard-nvim</li>
    <li>vimPlugins.deol-nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.doki-theme-vim</li>
    <li>vimPlugins.dressing-nvim</li>
    <li>vimPlugins.edge</li>
    <li>vimPlugins.editorconfig-nvim</li>
    <li>vimPlugins.embark-vim</li>
    <li>vimPlugins.everforest</li>
    <li>vimPlugins.feline-nvim</li>
    <li>vimPlugins.fern-vim</li>
    <li>vimPlugins.fidget-nvim</li>
    <li>vimPlugins.flutter-tools-nvim</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.fuzzy-nvim</li>
    <li>vimPlugins.fzf-lsp-nvim</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.gentoo-syntax</li>
    <li>vimPlugins.glow-nvim</li>
    <li>vimPlugins.gotests-vim</li>
    <li>vimPlugins.goto-preview</li>
    <li>vimPlugins.gruvbox-community</li>
    <li>vimPlugins.gruvbox-material</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.hologram-nvim</li>
    <li>vimPlugins.hop-nvim</li>
    <li>vimPlugins.hotpot-nvim</li>
    <li>vimPlugins.indent-blankline-nvim</li>
    <li>vimPlugins.kanagawa-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.lexima-vim</li>
    <li>vimPlugins.litee-calltree-nvim</li>
    <li>vimPlugins.litee-filetree-nvim</li>
    <li>vimPlugins.litee-nvim</li>
    <li>vimPlugins.litee-symboltree-nvim</li>
    <li>vimPlugins.lsp_lines-nvim</li>
    <li>vimPlugins.lsp_signature-nvim</li>
    <li>vimPlugins.lualine-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.lush-nvim</li>
    <li>vimPlugins.marks-nvim</li>
    <li>vimPlugins.material-nvim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.minimap-vim</li>
    <li>vimPlugins.mkdir-nvim</li>
    <li>vimPlugins.neoformat</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neoscroll-nvim</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.nord-nvim</li>
    <li>vimPlugins.nordic-nvim</li>
    <li>vimPlugins.nui-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-bqf</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-ui</li>
    <li>vimPlugins.nvim-dap-virtual-text</li>
    <li>vimPlugins.nvim-fzf</li>
    <li>vimPlugins.nvim-gdb</li>
    <li>vimPlugins.nvim-highlite</li>
    <li>vimPlugins.nvim-jdtls</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lsp-ts-utils</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-luapad</li>
    <li>vimPlugins.nvim-metals</li>
    <li>vimPlugins.nvim-neoclip-lua</li>
    <li>vimPlugins.nvim-notify</li>
    <li>vimPlugins.nvim-snippy</li>
    <li>vimPlugins.nvim-spectre</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-treesitter-textobjects</li>
    <li>vimPlugins.nvim-ts-rainbow</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.onedark-nvim</li>
    <li>vimPlugins.onedark-vim</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.packer-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rose-pine</li>
    <li>vimPlugins.sonokai</li>
    <li>vimPlugins.spellsitter-nvim</li>
    <li>vimPlugins.splitjoin-vim</li>
    <li>vimPlugins.sqlite-lua</li>
    <li>vimPlugins.stabilize-nvim</li>
    <li>vimPlugins.swayconfig-vim</li>
    <li>vimPlugins.syntastic</li>
    <li>vimPlugins.tcomment_vim</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-coc-nvim</li>
    <li>vimPlugins.telescope-file-browser-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-media-files-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-vim-bookmarks-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.tlib_vim</li>
    <li>vimPlugins.toggleterm-nvim</li>
    <li>vimPlugins.vifm-vim</li>
    <li>vimPlugins.vim-addon-actions</li>
    <li>vimPlugins.vim-addon-completion</li>
    <li>vimPlugins.vim-addon-goto-thing-at-cursor</li>
    <li>vimPlugins.vim-addon-nix</li>
    <li>vimPlugins.vim-addon-sql</li>
    <li>vimPlugins.vim-addon-syntax-checker</li>
    <li>vimPlugins.vim-addon-toggle-buffer</li>
    <li>vimPlugins.vim-airline</li>
    <li>vimPlugins.vim-airline-themes</li>
    <li>vimPlugins.vim-argwrap</li>
    <li>vimPlugins.vim-auto-save</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-code-dark</li>
    <li>vimPlugins.vim-dirvish</li>
    <li>vimPlugins.vim-endwise</li>
    <li>vimPlugins.vim-eunuch</li>
    <li>vimPlugins.vim-fugitive</li>
    <li>vimPlugins.vim-go</li>
    <li>vimPlugins.vim-illuminate</li>
    <li>vimPlugins.vim-kitty-navigator</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-manpager</li>
    <li>vimPlugins.vim-markbar</li>
    <li>vimPlugins.vim-matchup</li>
    <li>vimPlugins.vim-merginal</li>
    <li>vimPlugins.vim-mundo</li>
    <li>vimPlugins.vim-ocaml</li>
    <li>vimPlugins.vim-pandoc-syntax</li>
    <li>vimPlugins.vim-quickrun</li>
    <li>vimPlugins.vim-rsi</li>
    <li>vimPlugins.vim-sandwich</li>
    <li>vimPlugins.vim-slime</li>
    <li>vimPlugins.vim-snipmate</li>
    <li>vimPlugins.vim-snippets</li>
    <li>vimPlugins.vim-startuptime</li>
    <li>vimPlugins.vim-test</li>
    <li>vimPlugins.vim-textobj-variable-segment</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.vim-xkbswitch</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.zk-nvim</li>
  </ul>
</details>

**Comment by theHedgehog0** [comment]
> could you post the results for nixpkgs-review please ? I can't run it at the moment

Done!

**Comment by WhyNotHugo** [comment]
I guess this supercedes https://github.com/NixOS/nixpkgs/pull/182598

**Pull request merged**
