### PR TITLE
Update to ROCm 3.8.0

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

Update to ROCm 3.8.0.

cc: @acowley @Flakebi 

It would be nice if someone could test if this works, I had to replace my RX380.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Flakebi** [comment]
Thanks, seems to build and work fine. `clinfo` works, other OpenCL samples hang my (unsupported) GPU, so same as 3.7 for me.

```
$ nixpkgs-review pr 98230
9 packages built:
rocclr rocm-cmake rocm-comgr rocm-device-libs rocm-opencl-icd rocm-opencl-runtime rocm-runtime rocm-smi rocm-thunk
```

**Comment by danieldk** [comment]
Thanks for testing. Hopefully there will soon be progress on Navi.

**Comment by acowley** [comment]
Sorry for the delay, I started building 3.8 things this morning, but it's not done yet. The changes all look innocuous, but I'll report back in any case.

**Comment by acowley** [comment]
OpenCL and HIP are working for me with these updates, thank you @danieldk!

**Comment by danieldk** [comment]
Awesome, thanks for testing!

**Pull request merged**
