### PR TITLE
jackaudio: 1.9.11-RC1 -> 1.9.12

### PR DESCRIPTION
**Pull request by magnetophon**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg build jackaudio

**Comment by magnetophon** [comment]
@GrahamcOfBorg build jack2Full

**Comment by magnetophon** [comment]
@grahamc am I doing it wrong? ^^

**Comment by orivej** [comment]
@magnetophon The builds need pre-approval: https://github.com/grahamc/ofborg/issues/22

@GrahamcOfBorg build jack2Full

**Comment by vbgl** [comment]
This breaks the build of `libjack2` on darwin because some patch no longer applies:

```
> nix-build -A libjack2
these derivations will be built:
  /nix/store/377r3ixjq46ns9ygrvj0aj20l6hwg5p9-libjack2-1.9.12.drv
building path(s) ‘/nix/store/9a7b77hf6dlx2phg3zffhn0knxkxclb9-libjack2-1.9.12’
unpacking sources
unpacking source archive /nix/store/y3lrh1djz5v6ib548fjxx64gcbdhc4fj-source
source root is source
patching sources
applying patch /nix/store/r6sjxxbg9rpsm58rji4xq474rfidp0mg-clang.patch
patching file tests/test.cpp
Hunk #1 FAILED at 479.
1 out of 2 hunks FAILED -- saving rejects to file tests/test.cpp.rej
builder for ‘/nix/store/377r3ixjq46ns9ygrvj0aj20l6hwg5p9-libjack2-1.9.12.drv’ failed with exit code 1
```

**Pull request merged**
