### PR TITLE
nixos/top-level: add specialisation.<name>.configuration type

### PR DESCRIPTION
**Pull request by Scriptkiddi**
###### Motivation for this change
#76184

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by cole-h — APPROVED** [review]
Diff LGTM, thanks!

**Comment by ajs124** [comment]
I'm not sure why or how, but with this, the `nginx` test in `nixos/tests` fails to evaluate with:
```
error: The option `services.nginx.virtualHosts.localhost.root' has conflicting definition values:
- In `<unknown-file>': <derivation /nix/store/pbfyh5b86m14f3vkqz7gb8anfiyz2bmc-testdir.drv>
- In `<unknown-file>': <derivation /nix/store/jz45f8nkvqb82iim1s192349c28lbm4b-testdir2.drv>
(use '--show-trace' to show detailed location information)
```

cc @Infinisil as you're the `specialisation.` guy AFAIR

**Comment by ajs124** [comment]
Yeah, the acme and specialisation test are also broken with this.

**Comment by cole-h** [comment]
Sorry, I guess I didn't run the related test this time...

I don't actually know how to type this. `types.anything` works, but I don't know if we want to be more specific.

Ping our resident type-master @infinisil.

**Pull request merged**
