### PR TITLE
auth0-cli: 1.1.2 -> 1.4.0

### PR DESCRIPTION
**Pull request by sjbodzo**
## Description of changes

Release notes: https://github.com/auth0/auth0-cli/releases/tag/v1.4.0

Upgrades the auth0 command line utility package to the latest release.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by MatthewCroughan — APPROVED** [review]

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 301875` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>auth0-cli</li>
  </ul>
</details>

**Comment by sjbodzo** [comment]
> Result of `nixpkgs-review pr 301875` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 
> 1 package failed to build:
> Build fails due to failure in the test suite.
> 
> ```shell
> error: builder for '/nix/store/4nfarslfq9irxjzl4ahsxw1sxdsw4k16-auth0-cli-1.4.0.drv' failed with exit code 1;
>        last 10 log lines:
>        >                                -     (string) (len=19) "usernamePlaceholder": (string) (len=25) "Username or email address",
>        >                                  -     (string) (len=17) "wrong-credentials": (string) (len=26) "Wrong username or password",
>        >                                   -     (string) (len=23) "wrong-email-credentials": (string) (len=23) "Wrong email or password"
>        >                                 +    (string) (len=5) "login": (map[string]interface {}) (len=1) {
>        >                                     +     (string) (len=5) "title": (string) (len=33) "Welcome friend, glad to have you!"
>        >                                       }
>        >                 Test:           TestFetchUniversalLoginBrandingData/it_uses_a_default_branding_theme_if_it_fails_to_fetch_it
>        > FAIL
>        > FAIL        github.com/auth0/auth0-cli/internal/cli 8.333s
> ```

As someone new to Nix, what would you suggest (if anything) that I do for this to be upstreamed? 

I have: 
- reviewed the Go module builder [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/go/module.nix) to see if anything stood out to explain discrepancy locally on my box versus via Nix invocation 
- downloaded the referenced repo onto my host (outside of my flake environment) and ran the full unit test suite [and the single test that reports failure]
   - my host is Darwin ARM64 (M2 Max) running MacOS on Sonoma 14.4.1 with Go version 1.22.2
   - the test passes (both in the full suite run and in isolation)

I intend to rebuild my primary Linux machine in the next 2-3 weeks (time permitting), and should have a reliable Nix environment running on ARM64. Anything else I can do to troubleshoot / help here?

**Comment by fabaff** [comment]
The `nix-review` output only shows the last part of the issue. It starts:

```bash
[...]
Running phase: checkPhase
ok      github.com/auth0/auth0-cli/internal/analytics   0.005s
ok      github.com/auth0/auth0-cli/internal/ansi        0.005s
ok      github.com/auth0/auth0-cli/internal/auth        20.044s
ok      github.com/auth0/auth0-cli/internal/auth/authutil       3.057s
ok      github.com/auth0/auth0-cli/internal/buildinfo   0.003s
Error: failed to deploy action with ID "1221c74c-cfd6-40db-af13-7bc9bb1c38db": 400 Bad Request
Usage:
  deploy [flags]

Examples:
  auth0 actions deploy
[...]
Flags:
  -h, --help              help for show
  -l, --language string   Language of the custom text. (default "en")

--- FAIL: TestFetchUniversalLoginBrandingData (0.01s)
    --- FAIL: TestFetchUniversalLoginBrandingData/it_can_correctly_fetch_universal_login_branding_data (0.00s)
        universal_login_customize_test.go:958: 
[...]
```

At first glance I would says that the test want to perform a "real" web requests. As the tests are passing locally according to your analysis, I guess that this test is not mocked.

The quick solution would be to skip the failing test. The sandbox has no network access.

```nix
  preCheck = ''
    [...]
    # Tests requires network access
    substituteInPlace internal/cli/universal_login_customize_test.go \
      --replace-fail "TestFetchUniversalLoginBrandingData" "SkipFetchUniversalLoginBrandingData"
  '';
```

**Comment by sjbodzo** [comment]
Rebased off upstream origin with `preCheck` bypassing the errant tests.

**Comment by fabaff** [comment]
Could you please update the commit message of [b36963e](https://github.com/NixOS/nixpkgs/pull/301875/commits/b36963e93cffa25e405c086efc756cd1fcd46adc), e. g., `auth0-cli: disable failing tests`?

**Comment by sjbodzo** [comment]
> Could you please update the commit message of [b36963e](https://github.com/NixOS/nixpkgs/pull/301875/commits/b36963e93cffa25e405c086efc756cd1fcd46adc), e. g., `auth0-cli: disable failing tests`?

Done! Thanks again for all the help. Let me know if you need anything else to merge.

**Review by fabaff — APPROVED** [review]
Change looks good to me.

**Pull request merged**
