### PR TITLE
go: 1.9.3 -> 1.10

### PR DESCRIPTION
**Pull request by velovix**
###### Motivation for this change

Go 1.10 has been released.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I had to keep Kubernetes using Go 1.9 because the latest stable release doesn't seem to support 1.10.

cloudfoundry-cli seems to refer to Go 1.9 even when using 1.10 for some reason, so I've bumped it down to 1.9 for now. Perhaps someone more versed in the Nix expression language could help me debug this. The error I get is the following:

```
output ‘/nix/store/a20l7zj2qxr21drd64xhi7xyb8q2apvm-cloudfoundry-cli-6.32.0’ is not allowed to refer to path ‘/nix/store/bwznrnxvnky47w44sd7l3y9ssyxfpgyd-go-1.9.4’
```

### CODE REVIEW

**Comment by velovix** [comment]
Looks like master is broken right now.

**Comment by adisbladis** [comment]
@GrahamcOfBorg eval

**Comment by adisbladis** [comment]
@GrahamcOfBorg build go_1_10

**Comment by velovix** [comment]
Unfortunately I don't have a Darwin platform to test on, so I have to take Darwin off the supported platform list for now.

**Comment by adisbladis** [comment]
> Unfortunately I don't have a Darwin platform to test on, so I have to take Darwin off the supported platform list for now.

I'll have a look of that later today.

**Comment by Mic92** [comment]
Looks like a race condition. I have made a pull request here as well: https://github.com/NixOS/nixpkgs/pull/35330
I think (correct me if I am wrong) I have incorporate all changes, you have applied + darwin support.

**Comment by velovix** [comment]
I guess I would have preferred if there was a way to preserve the correct Git blame, maybe by forking against my fork, then having me merge your changes in. That's a lot of process overhead though and I don't blame you for not doing it.

**Comment by velovix** [comment]
Closing in favor of https://github.com/NixOS/nixpkgs/pull/35330

**Pull request closed without merging**
