### PR TITLE
unbound: 1.8.0 -> 1.8.1

### PR DESCRIPTION
**Pull request by fadenb**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by disassembler** [comment]
@GrahamcOfBorg build unbound

**Review by vcunat — APPROVED** [review]
- Darwin build atop master [succeeded](https://github.com/NixOS/nixpkgs/pull/49304#issuecomment-433658296).
- [NEWS](https://nlnetlabs.nl/pipermail/unbound-users/2018-October/010992.html) seem relatively safe.

**Comment by vcunat** [comment]
I'd wait a while to give maintainers a chance to react: @fpletz, @fadenb.

**Comment by vcunat** [comment]
Oh, @ehmry is the second one.

**Comment by vcunat** [comment]
BTW, "you" might be interested in switching unbound's openssl to 1.1.x, e.g. because of [TLS forwarding](https://www.nlnetlabs.nl/bugs-script/show_bug.cgi?id=658#c16).  Well, unless we [switch the default](https://github.com/NixOS/nixpkgs/pull/22357) soon.

**Pull request merged**
