### PR TITLE
Some cc-wrapper changes to better support darwin and clang

### PR DESCRIPTION
**Pull request by copumpkin**
- Add a conditional flag for the c++ std lib (not used in this branch yet, but my next PR will use it)
- Build binaries that get linked by our own dyld (someday)
- Automatically add framework directories in the setup hook

### CODE REVIEW

**Comment by copumpkin** [comment]
cc @shlevy @gridaphobe @joelteon @edolstra and anyone else who has feedback

**Comment by shlevy** [comment]
Why is this against staging?

**Comment by copumpkin** [comment]
Because it's a mass rebuild. Am I wrong?

**Comment by shlevy** [comment]
We can just open up a jobset for it and merge it in when it's done.

**Comment by copumpkin** [comment]
You might be able to :smile:! Such powers are outside of my reach. I can point this against master and let you set up a jobset though, if that's better.

**Comment by gridaphobe** [comment]
@shlevy I think one benefit of staging is that it can accumulate stdenv changes wheres the individual PRs each correspond to one change. E.g. my libiconv PR and this one will both force a mass-rebuild so staging could be building the results of applying both. Starting individual jobsets doesn't help here unless we base one PR off of the other.

**Comment by shlevy** [comment]
@copumpkin Sure, I'd like for more people to be able to, IMO until hydra can automatically create jobsets from PRs at least all contributors should get access if they want to ( @rbvermaa @edolstra ?)

**Comment by shlevy** [comment]
@gridaphobe Sure, but that's not how it's actually used. Instead we just dump a bunch of stuff in staging and then merge at some vague point in the future. I don't think it's very common that a lot of stdenv-changing things pile up at once, and I think it's fine to do things like base one PR off of another in those limited cases.

**Comment by copumpkin** [comment]
Yeah! Ideal for me is:
- Hydra auto-builds PRs
- Hydra can tell if it's a mass rebuild, if the rebuild is above some threshold, it requires permission (in the form of a thumbs up in a comment, perhaps) to test the build
- Hydra auto tags things as mass rebuilds
- ???
- Profit

**Comment by gridaphobe** [comment]
@shlevy Oh I don't have a problem with basing stdenv-changing PRs off of each other, just pointing out that it's an extra step we need to remember :smile:

**Comment by copumpkin** [comment]
Anyway, it doesn't look like I can repoint this, so I'll open another PR against master with the same changes

**Comment by gridaphobe** [comment]
@copumpkin can you base it off of my #6166 instead?

**Pull request closed without merging**
