### PR TITLE
firefox-bin: 45.0.2 -> 46.0

### PR DESCRIPTION
**Pull request by taku0**
###### Things done
- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
- Improved security of the JavaScript Just In Time (JIT) Compiler
- Use Content Decryption Module as a fallback to decode unencrypted H.264 and AAC media where available
- GTK3 integration (GNU/Linux only)
- WebRTC fixes to improve performance and stability

https://www.mozilla.org/en-US/firefox/46.0/releasenotes/

I will use SHA512 from the next release.

### CODE REVIEW

**Comment by joachifm** [comment]
When both gtk2 and gtk3 are available, what does it do? Does that mean that firefox-bin now closes over both gtk2 and 3?

**Comment by taku0** [comment]
It has `gtk2/libmozgtk.so` linking to GTK+2 and `libmozgtk.so` linking to GTK+3. GTK+3 is used by default. I don't know how to use GTK+2 version.

**Comment by joachifm** [comment]
Okay, I'm mostly concerned about the potential size increase. Also, I *think* gtk2 is supposed to be the default/preferred version in nixpkgs (not sure why).

**Comment by edolstra** [comment]
It's not desirable to have Firefox depend on *both* GTK 2 and 3. And yes, GTK 2 is our default, but we could change that for 16.09 (but only if stuff like consistent theming in KDE works).

**Comment by taku0** [comment]
It seems that `gtk2/libmozgtk.so` is used for plugins while `libmozgtk.so` is used for the browser. So we need both GTK+2 and GTK+3. We could compile Firefox from source with only GTK+2 (maybe with `--enable-default-toolkit=cairo-gtk2` or other), but we cannot use firefox-bin without GTK+3.

https://bugzilla.mozilla.org/show_bug.cgi?id=624422
http://hg.mozilla.org/mozilla-central/rev/c838e1e4de5d

**Comment by taku0** [comment]
Fixed crash on file dialog. See https://github.com/NixOS/nixpkgs/commit/ddeb2f5cceef9d5cc146972850e6990cec1e7981.

**Comment by taku0** [comment]
Scroll bar and radio buttons are not rendered properly (they are still there and clickable). Is this a problem of my desktop setting, Firefox, or GTK+3?
firefox-gtk3

**Comment by taku0** [comment]
The source package version 45.0.2 with GTK+3 enabled (`pkgs.wrapFirefox (pkgs.firefox-unwrapped.override { enableGTK3 = true; }) {}`) renders widgets correctly.

**Comment by joachifm** [comment]
If gtk3 is now required to run, I guess we have no choice, if we are to continue supporting firefox-bin in any meaningful way?

**Comment by taku0** [comment]
The source package version 46.0 with GTK+3 enabled also suffers from the problem.

Here is the `configuration.nix` I used to build a VM (nixos-rebuild build-vm).
https://gist.github.com/taku0/c7083962db2972017a243eb67c5d7928

**Comment by taku0** [comment]
The widget rendering problem is a bug of Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=1230955). Should we merge this PR for now or wait for the upstream fix?

**Comment by taku0** [comment]
46.0.1 is released. Closes in favor of #15208.

**Pull request closed without merging**
