### PR TITLE
steam: add openssl to fhsenv

### PR DESCRIPTION
**Pull request by SuperSamus**
###### Description of changes

#231533 broke some applications launched via `steam-run` by removing `openssl_1_1`.
For example, the [Ryujinx binary](https://ryujinx.org/download) stopped working after that PR, and works again with this.

EDIT: The reason why `openssl_1_1` was there in the first place was Loop Hero, which is *not* fixed by this PR.

cc @mweinelt

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by xfix** [comment]
Replacing `openssl_1_1` with `openssl` was tested for the previous pull request, it didn't work, which is why the dependency was removed entirely.

**Comment by SuperSamus** [comment]
So, Loop Hero is made with GameMaker.
I tested another GameMaker game (Undertale), but it needs none of these dependencies to work.

**Comment by xfix** [comment]
It depends on OpenSSL 1.0.0, which was removed long time ago from steam-run, and is provided by Steam runtime, unlike OpenSSL 1.1.

**Review by sugar700 — APPROVED** [review]

**Review by Atemu — APPROVED** [review]
If this fixes something like Ryujinx, this LGTM. Closure size shouldn't be an issue since openssl would be in almost everyone's closure anyways.

**Pull request merged**
