### PR TITLE
sqlint: 0.2.1 -> 0.3.0

### PR DESCRIPTION
**Pull request by purcell**
## Description of changes

Replacement for #266597, whereby I have properly fixed and released the dependencies upstream.

~First necessary to resolve the google-protobuf build error.~

This PR also adds an override for the `google-protobuf` gem, the latest version of which fails unless the compiler hardening settings are relaxed somewhat.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by robert-manchester** [comment]
same error on x64 linux. however, if i use the previous protobuf release, 3.24.4, the build is fine.

**Comment by maixnor** [comment]
can confirm build error on x64 linux

**Comment by robert-manchester** [comment]
> same error on x64 linux. however, if i use the previous protobuf release, 3.24.4, the build is fine.

disabling the warning as error in the compiler would work too but not sure how to pass compile flags into the gem stuff. what the compiler wants is.
```
rb_raise(rb_eRuntimeError, "%s", upb_Status_ErrorMessage(&status));
```
rather than
```
rb_raise(rb_eRuntimeError, upb_Status_ErrorMessage(&status));
```
so if there are format strings in the string returned by upb_Status_ErrorMessage it will not cause problems.

**Comment by purcell** [comment]
I think I've found where to fix it, bear with me.

**Comment by purcell** [comment]
I think I did it. 🤞

**Review by ghost — APPROVED** [review]
LGTM
basic test worked.
```sh
result/bin/sqlint <<SQL
select
a,
b,
c
from "table";
SQL
```
Result of `nixpkgs-review pr 266835` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)                                                                                                                                                                                           <details>                                                                                                                                                                                                                                                                                         <summary>1 package built:</summary>                                                                                                                                                                                                                                                             <ul>                                                                                                                                                                                                                                                                                              <li>sqlint</li>                                                                                                                                                                                                                                                                               </ul>                                                                                                                                                                                                                                                                                         </details>

**Review by marsam — APPROVED** [review]

**Comment by purcell** [comment]
Thanks all! 🙏

**Pull request merged**
