### PR TITLE
nextcloud: 15.0.7 -> 15.0.8

### PR DESCRIPTION
**Pull request by flokli**
###### Motivation for this change
https://nextcloud.com/changelog/#15-0-8

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by mmahut — APPROVED** [review]
- [X] reviewed the diff and commit messages
- [X] made sure ofBorg build succeeded for all applicable platforms
- [X] run nix-review without any failures

LGTM

**Comment by c0bw3b** [comment]
@GrahamcOfBorg test nextcloud.basic

**Comment by Lassulus** [comment]
tested inside a VM

**Comment by Lassulus** [comment]
backported in https://github.com/NixOS/nixpkgs/compare/cdec6217d98b...642b36a6bcb3

**Comment by flokli** [comment]
Thanks!

**Pull request merged**
