### PR TITLE
Pantheon updates 2021-09-23

### PR DESCRIPTION
**Pull request by bobby285271**
###### Motivation for this change

Part of Pantheon 6.0.2 updates (previous one at https://github.com/NixOS/nixpkgs/pull/139057).

We pinned vala to 0.52 for 2 packages as they don't build with vala 0.54, see:

- https://github.com/elementary/wingpanel-indicator-sound/issues/219
- https://github.com/elementary/photos/issues/638

###### Things done

- [x] Rebuilt NixOS to test the change.
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
#### pantheon.gala

https://github.com/elementary/gala/releases/tag/6.2.0
https://github.com/elementary/gala/compare/6.0.1...6.2.0

> New features:
> - Stash the picture-in-picture window by pushing it off screen
> 
> Improvements:
> - Fix a potential crash while changing wallpapers
> - Updated translations

#### pantheon.elementary-photos

https://github.com/elementary/photos/releases/tag/2.7.2
https://github.com/elementary/photos/compare/2.7.1...2.7.2

> - Draw selection rectangle when dragging to select
> - Show image titles in preview mode
> - Translation updates

**Comment by bobby285271** [comment]
Result of `nixpkgs-review pr 139163` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>24 packages built:</summary>
  <ul>
    <li>monitor</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-gsettings-schemas</li>
    <li>pantheon.elementary-photos</li>
    <li>pantheon.elementary-session-settings</li>
    <li>pantheon.gala</li>
    <li>pantheon.switchboard-plug-a11y</li>
    <li>pantheon.switchboard-plug-mouse-touchpad</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-plug-security-privacy</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-a11y</li>
    <li>pantheon.wingpanel-indicator-bluetooth</li>
    <li>pantheon.wingpanel-indicator-datetime</li>
    <li>pantheon.wingpanel-indicator-keyboard</li>
    <li>pantheon.wingpanel-indicator-network</li>
    <li>pantheon.wingpanel-indicator-nightlight</li>
    <li>pantheon.wingpanel-indicator-notifications</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-indicator-session</li>
    <li>pantheon.wingpanel-indicator-sound</li>
    <li>pantheon.wingpanel-with-indicators</li>
  </ul>
</details>

**Comment by bobby285271** [comment]
@ofborg test pantheon

**Comment by davidak** [comment]
I have built my system from this PR and it works.

**Pull request merged**
