### PR TITLE
nixos/dendrite: use umask and chmod to protect configuration

### PR DESCRIPTION
**Pull request by dotlambda**
Also, we can use envsubst even if no environmentFile is defined.

###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/109561#discussion_r625889153

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

I couldn't test this because the module is lacking tests and I don't use it personally. The tests need to be added!!

### CODE REVIEW

**Comment by mjlbach** [comment]
umask isn't available on path in ExecStartPre

```
May 04 19:27:05 nixos systemd[1]: Starting Dendrite Matrix homeserver...
May 04 19:27:05 nixos systemd[607]: matrix-dendrite.service: Failed to locate executable umask: No such file or directory
May 04 19:27:05 nixos systemd[607]: matrix-dendrite.service: Failed at step EXEC spawning umask: No such file or directory
```

If you want to test (for this PR), you first need to generate a private key:
`nix-shell -p matrix-dendrite --command "generate-keys --private-key matrix_key.pem"`

You can use nixos-shell with the following vm.nix
``
{ pkgs, ... }: {
  boot.kernelPackages = pkgs.linuxPackages_latest;
  virtualisation.qemu.networkingOptions = [
    # We need to re-define our usermode network driver
    # since we are overriding the default value.
    "-net nic,netdev=user.0,model=virtio"
    # Than we can use qemu's hostfwd option to forward ports.
    "-netdev user,id=user.0,hostfwd=tcp::8008-:8008"
  ];
  nixos-shell.mounts = {
    mountHome = false;
    mountNixProfile = false;
    cache = "none"; # default is "loose"
  };
  services.matrix-dendrite.enable = true;
  services.matrix-dendrite.settings.global.server_name = "example.com";
  services.matrix-dendrite.settings.client_api.registration_disabled = false;
  services.matrix-dendrite.settings.global.private_key = ./private.key;
}
```

The other change is fine, I don't know why I had issues with envsubst not copying the file before.

**Comment by mjlbach** [comment]
I'll trust your usage of chmod given you were the one who filed https://github.com/NixOS/nixpkgs/issues/121293 :P

**Comment by dotlambda** [comment]
@mjlbach The only thing I'm not sure about is whether `Umask` also applies to `ExecStartPre`. Can you paste the file permissions before and after this change?
The use of `chmod` is fine since it only write-protects the configuration. `Umask` is responsible for preventing other users from reading the configuration.

There is one more problem I have: This change doesn't actually help because the `environmentFile` has to be world-readable due to the use of `DynamicUser`. Any idea how to fix that?

Also, would it make sense to use envsubst's `-no-unset` and `-no-empty`?

**Comment by dotlambda** [comment]
To be honest, I feel like reverting ff43bbe53e370fa1072e952b89d0a32fb1dfda3a until we figured this out is a good option. We don't want to ship a module in 21.05 just to make breaking changes shortly after.

**Comment by mjlbach** [comment]
as of ff43bbe 
```
drwxr-xr-x 19 root            root            520 May  4 21:33 ..
drwx------  2 matrix-dendrite matrix-dendrite  60 May  4 21:33 .
-r--r--r--  1 matrix-dendrite matrix-dendrite 279 May  4 21:33 dendrite.yaml
```

as of this PR
```
drwx------  2 matrix-dendrite matrix-dendrite  60 May  4 21:33 .
-rw-r--r--  1 matrix-dendrite matrix-dendrite 279 May  4 21:30 dendrite.yaml
```

I'm opposed to reverting it, I don't believe any of the sandboxing/permission issues are user-facing. Other modules leak secrets via the nix store, and having this secret is not a necessity for using the module (it only lets you restrict registrations, which you can also achieve via a reverse proxy with login requirements). I'm not in any position to challenge you on this. I'm happy to gradually add tests/improve the security of the module.

I'm not familiar enough with how dynamicuser works to know an immediate solution for environmentfile, I didn't think it was persistent.

**Comment by mjlbach** [comment]
Re: -no-unset/-no-empty I don't know what the advantage would be, just to fail early if environmentfile was malformed?

**Comment by dotlambda** [comment]
> as of this PR
> 
> ```
> drwx------  2 matrix-dendrite matrix-dendrite  60 May  4 21:33 .
> -rw-r--r--  1 matrix-dendrite matrix-dendrite 279 May  4 21:30 dendrite.yaml
> ```

I think you got the order messed up.
Anyway, seems like `Umask` doesn't apply to `ExecStartPre` :-(
However, the permissions on the directory prevent access anyway, so I guess we can just go without it.

> I'm not familiar enough with how dynamicuser works to know an immediate solution for environmentfile, I didn't think it was persistent.

The problem is not persistence, it's that the file `environmentFile` has to be readable by anywone because otherwise the dynamic user wouldn't be allowed to read it.
I suggest we prefix the command in `ExecStartPre` with `!` (documented [here](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStart=)) or, even better, use `preStart`. In the latter case, we could use the `umask` command but the semantics of `environmentFile` would change to a shell script and the option should be renamed. In both cases, `envsubst` would run as root and we could thus make the file readable to root only.

> Re: -no-unset/-no-empty I don't know what the advantage would be, just to fail early if environmentfile was malformed?

It would prevent the usage of an insecure secret if you accidentally misspell the variable name in one of the two places, in which case it wouldn't get substituted.

**Comment by mjlbach** [comment]
> I think you got the order messed up.

I was confused by this too, but I did not mess up the order. You can verify with the nixos-shell from above.

> I suggest we prefix the command in ExecStartPre with ! (documented here) or, even better, use systemd.services.matrix-dendrite.preStart. In the latter case, we could use the umask command but the semantics of environmentFile would change to a shell script (we'd use source to read it) and the option should be renamed. In both cases, envsubst would run as root and we could thus make the file readable to root only.

I had thought about using preStart in this way, but the implementation/interface of providing an environment file directly seemed cleaner. If you think this is necessary then I guess we have to.

> It would prevent the usage of an insecure secret if you accidentally misspell the variable name in one of the two places, in which case it wouldn't get substituted.

This seems fine to me then.

**Comment by dotlambda** [comment]
> the implementation/interface of providing an environment file directly seemed cleaner

I feel the same way. Running a shell script is always scary.

**Comment by dotlambda** [comment]
I figured out why `chmod` was not executed: multiple commands need multiple `ExecStartPre`.


> The problem is not persistence, it's that the file `environmentFile` has to be readable by anywone because otherwise the dynamic user wouldn't be allowed to read it.

I was wrong there I think: It suffices if systemd can read that file.

Now, what is an issue though is that `tlsCert` and `tlsKey` have to be readable by the dynamic user, i.e. by everyone. I guess we need to copy these using root.

**Comment by dotlambda** [comment]
> Now, what is an issue though is that `tlsCert` and `tlsKey` have to be readable by the dynamic user, i.e. by everyone. I guess we need to copy these using root.

unless we require that they are placed in `/var/lib/matrix-dendrite`

**Comment by mjlbach** [comment]
> unless we require that they are placed in /var/lib/matrix-dendrite

That's what I had done in a previous iteration of my PR where I had a systemd service generate the TLS keys

**Comment by dotlambda** [comment]
Since the same is true for `private_key`, I guess it makes sense to require them being placed there. But then there's no point in making them configurable.

**Comment by dotlambda** [comment]
I still feel this is broken somewhat fundamentally due to the interplay between `DynamicUser` and those files. We really need to make sure to fix this before 21.05 or revert.

**Comment by dotlambda** [comment]
Why don't we generate the `private_key` automatically, e.g. using
```
${pkgs.matrix-dendrite}/bin/generate-keys --private-key matrix_key.pem.tmp ;
${pkgs.coreutils}/bin/cp -n matrix_key.pem.tmp matrix_key.pem
```
in `ExecStartPre`?

**Comment by dotlambda** [comment]
I don't have time to work on this. Please ping me in the PR fixing this though.

**Comment by dotlambda** [comment]
Btw, I don't think umask is necessary given we have `RuntimeDirectoryMode`.

**Comment by mjlbach** [comment]
I did originally have private key, tls key, tls cert generated automatically by the systemd service, but during review this was pointed out to be adding additional complexity, so I removed it. I can look into the issues you've raised.

**Pull request closed without merging**
