### PR TITLE
lib.concatMapAttrs: Simplify stack trace

### PR DESCRIPTION
**Pull request by roberth**
###### Description of changes

By removing the unnecessary `pipe` and `flip`, we get a simpler, shorter stack trace.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by infinisil** [comment]
@piegamesde might be interested in this as the author of NixOS/rfcs#148

**Comment by piegamesde** [comment]
@infinisil Thanks, this is an interesting example.

--------

On another note, I'd like to see less pull requests of the kind "self-merged after 3 hours", even for simple and straightforward changes

**Comment by infinisil** [comment]
> On another note, I'd like to see less pull requests of the kind "self-merged after 3 hours", even for simple and straightforward changes

Agreed! I would've merged this PR @roberth :slightly_smiling_face:

**Comment by roberth** [comment]
> On another note, I'd like to see less pull requests of the kind "self-merged after 3 hours", even for simple and straightforward changes

Ok. Feels unnecessary, but I can think of some arguments. I'll do my part and see how it goes.

> rfc 148

Actually I just pulled this commit from #202517 with the intent of removing the trivial stuff to make review easier. I didn't want to bother anyone with review because I thought it was uninteresting and not worth their time. So I got that wrong then.

**Comment by piegamesde** [comment]
I understand your motivation and don't think merging this PR quickly was inherently bad. It's just that not all Nixpkgs contributors hold themselves up to the same standards, so this kind of thing tends to occasionally go wrong and break things. And it's of course difficult to differentiate here, so the next best thing is to normalize some generous safety margins, even though they might feel (and be) unnecessary in some situations.

**Pull request merged**
