### PR TITLE
[23.05] nixVersions: 2.15.0 -> 2.15.1, nixVersions: add 2.16.1, nixVersions.minver: init

### PR DESCRIPTION
**Pull request by lorenzleutgeb**
Backports:

 - #236268
 - ~~#233439~~ (Edit: Removed, as this would change `nixVersions.stable`, sorry!)
 - #234070
 - #235221 (Edit: 95b82210876197d231f81c6be34320c56c04be31, which was part of this PR was dropped, since it would change `nixVersions.unstable`.)
 - #235012

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
Why does this comply for backport criteria?

**Comment by Kranzes** [comment]
Yeah, I believe we decided to stick with 2.13.3 on stable for now.

**Comment by lorenzleutgeb** [comment]
Sorry, I missed that this would change `nixVersions.stable`. I removed #233439.

**Comment by lorenzleutgeb** [comment]
OK, I dropped 95b82210876197d231f81c6be34320c56c04be31

**Comment by lorenzleutgeb** [comment]
The last [check](https://github.com/NixOS/nixpkgs/pull/236430/checks?check_run_id=14075663989) has been running for >7h. Is that to be expected? If not, is there a way to retry?

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 236430` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>nix-init</li>
    <li>nixVersions.minimum</li>
    <li>nixVersions.minimum.dev</li>
    <li>nixVersions.minimum.doc</li>
    <li>nixVersions.minimum.man</li>
    <li>nixVersions.nix_2_15 (nixVersions.unstable)</li>
    <li>nixVersions.nix_2_15.dev (nixVersions.unstable.dev)</li>
    <li>nixVersions.nix_2_15.doc (nixVersions.unstable.doc)</li>
    <li>nixVersions.nix_2_15.man (nixVersions.unstable.man)</li>
    <li>nixVersions.nix_2_16</li>
    <li>nixVersions.nix_2_16.dev</li>
    <li>nixVersions.nix_2_16.doc</li>
    <li>nixVersions.nix_2_16.man</li>
    <li>nurl</li>
  </ul>
</details>

**Comment by PetarKirov** [comment]
Is this PR ready to be merged?

**Pull request merged**
