### PR TITLE
zoneminder: 1.34.9 -> 1.34.16

### PR DESCRIPTION
**Pull request by adisbladis**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by peterhoeg** [comment]
While at it, can I trouble you to remove me as a maintainer? I haven't used ZM in ages.

**Comment by adisbladis** [comment]
@peterhoeg Removed as requested.

Out of curiousity: Did you switch CCTV software to something else? I haven't started using zoneminder yet but I will do a CCTV setup in the next couple of days.

**Comment by peterhoeg** [comment]
I did switch, yes. motioneye is perfectly fine for my needs. ZM is just a mess IMHO.

**Comment by bachp** [comment]
@peterhoeg Do you have motioneye working on NixOS?

**Comment by peterhoeg** [comment]
@bachp, I do yes, but not upstream and not modularized either so tied pretty heavily to my setup here. I have created a gist with the package as well as the config here: https://gist.github.com/peterhoeg/01fe3ccb54cea4d9a437b9e8ffb3c55c

There are some hardcoded ids/passwords in there but everything is on a separate VLAN without any internet access, so that should be fine (besides, those are just default passwords anyway).

**Comment by peterhoeg** [comment]
One external password was *not* blanked out but it's been changed now and shouldn't have been in there in the first place.

**Pull request merged**
