### PR TITLE
build-pecl: fix strictDeps

### PR DESCRIPTION
**Pull request by ofalvai**
phpize from the php package itself is needed in autoreconfPhase

Ref: https://github.com/NixOS/nixpkgs/issues/178468

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by drupol — APPROVED** [review]

**Comment by drupol** [comment]
@Ma27 or @jtojnar can you check this PR too?

**Comment by jtojnar** [comment]
The addition of PHP for `phpize` in `autoreconfPhase` sounds reasonable. Maybe it would be possible to use unwrapped PHP (to reduce the number of packages needed for cross builds) but that can always be done later.

The addition of `strictDeps` is a BC break that can affect any `buildPecl`-dependent package but it should probably be fine. Would be still nice to try nixpkgs-review or some other way to build all reverse dependencies.

**Comment by ofalvai** [comment]
I ran `nixpkgs-review` with the same change on top of `master`, I think it's mostly okay. I'm not familiar with the state of PHP packages + macOS, but I randomly looked up a few of the broken packages in Hydra, and they are already broken.


## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review`

---
### `aarch64-darwin`
<details>
  <summary>:fast_forward: 10 packages marked as broken and skipped:</summary>
  <ul>
    <li>php81Extensions.parallel</li>
    <li>php82Extensions.parallel</li>
    <li>php83Extensions.couchbase</li>
    <li>php83Extensions.parallel</li>
    <li>php84Extensions.couchbase</li>
    <li>php84Extensions.openswoole</li>
    <li>php84Extensions.parallel</li>
    <li>php84Extensions.phalcon</li>
    <li>php84Extensions.swoole</li>
    <li>qcachegrind</li>
  </ul>
</details>
<details>
  <summary>:x: 15 packages failed to build:</summary>
  <ul>
    <li>php81Extensions.pinba</li>
    <li>php81Extensions.rrd</li>
    <li>php81Extensions.vld</li>
    <li>php81Extensions.yaml</li>
    <li>php82Extensions.pinba</li>
    <li>php82Extensions.rrd</li>
    <li>php82Extensions.yaml</li>
    <li>php83Extensions.pinba</li>
    <li>php83Extensions.rrd</li>
    <li>php83Extensions.yaml</li>
    <li>php84Extensions.datadog_trace</li>
    <li>php84Extensions.mailparse</li>
    <li>php84Extensions.pinba</li>
    <li>php84Extensions.rrd</li>
    <li>php84Extensions.yaml</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 217 packages built:</summary>
  <ul>
    <li>adminer</li>
    <li>adminer-pematon</li>
    <li>adminerevo</li>
    <li>agorakit</li>
    <li>php (apacheHttpdPackages.php)</li>
    <li>composer-require-checker</li>
    <li>davis</li>
    <li>engelsystem</li>
    <li>firefly-iii</li>
    <li>firefly-iii-data-importer</li>
    <li>flarum</li>
    <li>frankenphp</li>
    <li>freshrss</li>
    <li>grocy</li>
    <li>icingaweb2</li>
    <li>ifm-web</li>
    <li>kimai</li>
    <li>laravel</li>
    <li>matomo</li>
    <li>matomo-beta</li>
    <li>matomo_5</li>
    <li>movim</li>
    <li>n98-magerun2</li>
    <li>nagios</li>
    <li>nextcloud-news-updater</li>
    <li>nextcloud-news-updater.dist</li>
    <li>nominatim</li>
    <li>paratest</li>
    <li>pdepend</li>
    <li>pest</li>
    <li>phel</li>
    <li>phoronix-test-suite</li>
    <li>php81Extensions.amqp</li>
    <li>php81Extensions.apcu</li>
    <li>php81Extensions.apcu.dev</li>
    <li>php81Extensions.ast</li>
    <li>php81Extensions.couchbase</li>
    <li>php81Extensions.datadog_trace</li>
    <li>php81Extensions.ds</li>
    <li>php81Extensions.event</li>
    <li>php81Extensions.gnupg</li>
    <li>php81Extensions.grpc</li>
    <li>php81Extensions.igbinary</li>
    <li>php81Extensions.igbinary.dev</li>
    <li>php81Extensions.imagick</li>
    <li>php81Extensions.mailparse</li>
    <li>php81Extensions.maxminddb</li>
    <li>php81Extensions.memcache</li>
    <li>php81Extensions.memcached</li>
    <li>php81Extensions.meminfo</li>
    <li>php81Extensions.memprof</li>
    <li>php81Extensions.mongodb</li>
    <li>php81Extensions.msgpack</li>
    <li>php81Extensions.openswoole</li>
    <li>php81Extensions.opentelemetry</li>
    <li>php81Extensions.pcov</li>
    <li>php81Extensions.pdlib</li>
    <li>php81Extensions.pdo_sqlsrv</li>
    <li>php81Extensions.phalcon</li>
    <li>php81Extensions.protobuf</li>
    <li>php81Extensions.pspell</li>
    <li>php81Extensions.rdkafka</li>
    <li>php81Extensions.redis</li>
    <li>php81Extensions.smbclient</li>
    <li>php81Extensions.snuffleupagus</li>
    <li>php81Extensions.spx</li>
    <li>php81Extensions.sqlsrv</li>
    <li>php81Extensions.ssh2</li>
    <li>php81Extensions.swoole</li>
    <li>php81Extensions.xdebug</li>
    <li>php81Extensions.zstd</li>
    <li>php81Packages.phan</li>
    <li>php82Extensions.amqp</li>
    <li>php82Extensions.apcu</li>
    <li>php82Extensions.apcu.dev</li>
    <li>php82Extensions.ast</li>
    <li>php82Extensions.couchbase</li>
    <li>php82Extensions.datadog_trace</li>
    <li>php82Extensions.ds</li>
    <li>php82Extensions.event</li>
    <li>php82Extensions.gnupg</li>
    <li>php82Extensions.grpc</li>
    <li>php82Extensions.igbinary</li>
    <li>php82Extensions.igbinary.dev</li>
    <li>php82Extensions.imagick</li>
    <li>php82Extensions.mailparse</li>
    <li>php82Extensions.maxminddb</li>
    <li>php82Extensions.memcache</li>
    <li>php82Extensions.memcached</li>
    <li>php82Extensions.meminfo</li>
    <li>php82Extensions.memprof</li>
    <li>php82Extensions.mongodb</li>
    <li>php82Extensions.msgpack</li>
    <li>php82Extensions.openswoole</li>
    <li>php82Extensions.opentelemetry</li>
    <li>php82Extensions.pcov</li>
    <li>php82Extensions.pdlib</li>
    <li>php82Extensions.pdo_sqlsrv</li>
    <li>php82Extensions.phalcon</li>
    <li>php82Extensions.protobuf</li>
    <li>php82Extensions.pspell</li>
    <li>php82Extensions.rdkafka</li>
    <li>php82Extensions.redis</li>
    <li>php82Extensions.smbclient</li>
    <li>php82Extensions.snuffleupagus</li>
    <li>php82Extensions.spx</li>
    <li>php82Extensions.sqlsrv</li>
    <li>php82Extensions.ssh2</li>
    <li>php82Extensions.swoole</li>
    <li>php82Extensions.vld</li>
    <li>php82Extensions.xdebug</li>
    <li>php82Extensions.zstd</li>
    <li>php82Packages.phan</li>
    <li>php83Extensions.amqp</li>
    <li>php83Extensions.apcu</li>
    <li>php83Extensions.apcu.dev</li>
    <li>php83Extensions.ast</li>
    <li>php83Extensions.datadog_trace</li>
    <li>php83Extensions.ds</li>
    <li>php83Extensions.event</li>
    <li>php83Extensions.gnupg</li>
    <li>php83Extensions.grpc</li>
    <li>php83Extensions.igbinary</li>
    <li>php83Extensions.igbinary.dev</li>
    <li>php83Extensions.imagick</li>
    <li>php83Extensions.imap</li>
    <li>php83Extensions.mailparse</li>
    <li>php83Extensions.maxminddb</li>
    <li>php83Extensions.memcache</li>
    <li>php83Extensions.memcached</li>
    <li>php83Extensions.meminfo</li>
    <li>php83Extensions.memprof</li>
    <li>php83Extensions.mongodb</li>
    <li>php83Extensions.msgpack</li>
    <li>php83Extensions.openswoole</li>
    <li>php83Extensions.opentelemetry</li>
    <li>php83Extensions.pcov</li>
    <li>php83Extensions.pdlib</li>
    <li>php83Extensions.pdo_sqlsrv</li>
    <li>php83Extensions.phalcon</li>
    <li>php83Extensions.protobuf</li>
    <li>php83Extensions.pspell</li>
    <li>php83Extensions.rdkafka</li>
    <li>php83Extensions.redis</li>
    <li>php83Extensions.smbclient</li>
    <li>php83Extensions.snuffleupagus</li>
    <li>php83Extensions.spx</li>
    <li>php83Extensions.sqlsrv</li>
    <li>php83Extensions.ssh2</li>
    <li>php83Extensions.swoole</li>
    <li>php83Extensions.vld</li>
    <li>php83Extensions.xdebug</li>
    <li>php83Extensions.zstd</li>
    <li>php83Packages.castor</li>
    <li>php83Packages.composer</li>
    <li>php83Packages.composer-local-repo-plugin</li>
    <li>php83Packages.cyclonedx-php-composer</li>
    <li>php83Packages.deployer</li>
    <li>php83Packages.grumphp</li>
    <li>php83Packages.phan</li>
    <li>php83Packages.phing</li>
    <li>php83Packages.phive</li>
    <li>php83Packages.php-codesniffer</li>
    <li>php83Packages.php-cs-fixer</li>
    <li>php83Packages.php-parallel-lint</li>
    <li>php83Packages.phpinsights</li>
    <li>php83Packages.phpmd</li>
    <li>php83Packages.phpstan</li>
    <li>php83Packages.psalm</li>
    <li>php83Packages.psysh</li>
    <li>php84Extensions.amqp</li>
    <li>php84Extensions.apcu</li>
    <li>php84Extensions.apcu.dev</li>
    <li>php84Extensions.ast</li>
    <li>php84Extensions.ds</li>
    <li>php84Extensions.event</li>
    <li>php84Extensions.gnupg</li>
    <li>php84Extensions.grpc</li>
    <li>php84Extensions.igbinary</li>
    <li>php84Extensions.igbinary.dev</li>
    <li>php84Extensions.imagick</li>
    <li>php84Extensions.imap</li>
    <li>php84Extensions.maxminddb</li>
    <li>php84Extensions.memcache</li>
    <li>php84Extensions.memcached</li>
    <li>php84Extensions.meminfo</li>
    <li>php84Extensions.memprof</li>
    <li>php84Extensions.mongodb</li>
    <li>php84Extensions.msgpack</li>
    <li>php84Extensions.opentelemetry</li>
    <li>php84Extensions.pcov</li>
    <li>php84Extensions.pdlib</li>
    <li>php84Extensions.pdo_sqlsrv</li>
    <li>php84Extensions.protobuf</li>
    <li>php84Extensions.pspell</li>
    <li>php84Extensions.rdkafka</li>
    <li>php84Extensions.redis</li>
    <li>php84Extensions.smbclient</li>
    <li>php84Extensions.snuffleupagus</li>
    <li>php84Extensions.spx</li>
    <li>php84Extensions.sqlsrv</li>
    <li>php84Extensions.ssh2</li>
    <li>php84Extensions.vld</li>
    <li>php84Extensions.xdebug</li>
    <li>php84Extensions.zstd</li>
    <li>php84Packages.phan</li>
    <li>phpactor</li>
    <li>phpdocumentor</li>
    <li>phpunit</li>
    <li>pixelfed</li>
    <li>roave-backward-compatibility-check</li>
    <li>signaturepdf</li>
    <li>simplesamlphp</li>
    <li>vimPlugins.phpactor</li>
    <li>wp-cli</li>
    <li>yle-dl</li>
    <li>yle-dl.dist</li>
  </ul>
</details>

**Comment by ofalvai** [comment]
Actually, `rrd` was a fallout from my change. I pushed a fix. The others are compilation errors, probably because of Clang.

**Comment by drupol** [comment]
@ofborg build php84Extensions.rrd

**Comment by ofalvai** [comment]
@ofborg build php84Extensions.rrd

**Comment by drupol** [comment]
I don't think this is ready to merge yet...

**Comment by ofalvai** [comment]
@drupol apologies, I forgot to post my comment about testing `php84Extensions.rrd` on both macOS and Linux, it builds for me, so I'm not sure what is going on with ofborg. And I ran a GC since I built a staging stdenv, I can't test it again right now.
Can you help me what else is needed before we can merge this?

**Comment by drupol** [comment]
Can you try to rebate your branch against the latest commit ?

**Comment by drupol** [comment]
I guess we can target the master branch, WDYT ?

**Comment by ofalvai** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 361855`

---
### `aarch64-linux`
<details>
  <summary>:fast_forward: 9 packages marked as broken and skipped:</summary>
  <ul>
    <li>php81Extensions.parallel</li>
    <li>php82Extensions.parallel</li>
    <li>php83Extensions.couchbase</li>
    <li>php83Extensions.parallel</li>
    <li>php84Extensions.couchbase</li>
    <li>php84Extensions.openswoole</li>
    <li>php84Extensions.parallel</li>
    <li>php84Extensions.phalcon</li>
    <li>php84Extensions.swoole</li>
  </ul>
</details>
<details>
  <summary>:fast_forward: 2 packages blacklisted:</summary>
  <ul>
    <li>tests.php.overrideAttrs-preserves-enabled-extensions</li>
    <li>tests.php.withExtensions-enables-previously-disabled-extensions</li>
  </ul>
</details>
<details>
  <summary>:x: 7 packages failed to build:</summary>
  <ul>
    <li>php81Extensions.vld</li>
    <li>php81Extensions.yaml</li>
    <li>php82Extensions.yaml</li>
    <li>php83Extensions.yaml</li>
    <li>php84Extensions.datadog_trace</li>
    <li>php84Extensions.pdo_oci</li>
    <li>php84Extensions.yaml</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 249 packages built:</summary>
  <ul>
    <li>adminer</li>
    <li>adminer-pematon</li>
    <li>adminerevo</li>
    <li>agorakit</li>
    <li>php (apacheHttpdPackages.php ,php83)</li>
    <li>bookstack</li>
    <li>composer-require-checker</li>
    <li>davis</li>
    <li>engelsystem</li>
    <li>firefly-iii</li>
    <li>firefly-iii-data-importer</li>
    <li>flarum</li>
    <li>frankenphp</li>
    <li>freshrss</li>
    <li>grocy</li>
    <li>icingaweb2</li>
    <li>ifm-web</li>
    <li>kimai</li>
    <li>laravel</li>
    <li>librenms</li>
    <li>libsForQt5.kcachegrind (plasma5Packages.kcachegrind)</li>
    <li>matomo</li>
    <li>matomo-beta</li>
    <li>matomo_5</li>
    <li>movim</li>
    <li>n98-magerun2</li>
    <li>nagios</li>
    <li>nextcloud-news-updater</li>
    <li>nextcloud-news-updater.dist</li>
    <li>nominatim</li>
    <li>paratest</li>
    <li>pdepend</li>
    <li>pest</li>
    <li>phel</li>
    <li>phoronix-test-suite</li>
    <li>php81Extensions.amqp</li>
    <li>php81Extensions.apcu</li>
    <li>php81Extensions.apcu.dev</li>
    <li>php81Extensions.ast</li>
    <li>php81Extensions.couchbase</li>
    <li>php81Extensions.datadog_trace</li>
    <li>php81Extensions.ds</li>
    <li>php81Extensions.event</li>
    <li>php81Extensions.gnupg</li>
    <li>php81Extensions.grpc</li>
    <li>php81Extensions.igbinary</li>
    <li>php81Extensions.igbinary.dev</li>
    <li>php81Extensions.imagick</li>
    <li>php81Extensions.inotify</li>
    <li>php81Extensions.mailparse</li>
    <li>php81Extensions.maxminddb</li>
    <li>php81Extensions.memcache</li>
    <li>php81Extensions.memcached</li>
    <li>php81Extensions.meminfo</li>
    <li>php81Extensions.memprof</li>
    <li>php81Extensions.mongodb</li>
    <li>php81Extensions.msgpack</li>
    <li>php81Extensions.oci8</li>
    <li>php81Extensions.openswoole</li>
    <li>php81Extensions.opentelemetry</li>
    <li>php81Extensions.pcov</li>
    <li>php81Extensions.pdlib</li>
    <li>php81Extensions.pdo_oci</li>
    <li>php81Extensions.pdo_sqlsrv</li>
    <li>php81Extensions.phalcon</li>
    <li>php81Extensions.pinba</li>
    <li>php81Extensions.protobuf</li>
    <li>php81Extensions.pspell</li>
    <li>php81Extensions.rdkafka</li>
    <li>php81Extensions.redis</li>
    <li>php81Extensions.rrd</li>
    <li>php81Extensions.smbclient</li>
    <li>php81Extensions.snuffleupagus</li>
    <li>php81Extensions.spx</li>
    <li>php81Extensions.sqlsrv</li>
    <li>php81Extensions.ssh2</li>
    <li>php81Extensions.swoole</li>
    <li>php81Extensions.uuid</li>
    <li>php81Extensions.uv</li>
    <li>php81Extensions.xdebug</li>
    <li>php81Extensions.zstd</li>
    <li>php81Packages.phan</li>
    <li>php82Extensions.amqp</li>
    <li>php82Extensions.apcu</li>
    <li>php82Extensions.apcu.dev</li>
    <li>php82Extensions.ast</li>
    <li>php82Extensions.couchbase</li>
    <li>php82Extensions.datadog_trace</li>
    <li>php82Extensions.ds</li>
    <li>php82Extensions.event</li>
    <li>php82Extensions.gnupg</li>
    <li>php82Extensions.grpc</li>
    <li>php82Extensions.igbinary</li>
    <li>php82Extensions.igbinary.dev</li>
    <li>php82Extensions.imagick</li>
    <li>php82Extensions.inotify</li>
    <li>php82Extensions.mailparse</li>
    <li>php82Extensions.maxminddb</li>
    <li>php82Extensions.memcache</li>
    <li>php82Extensions.memcached</li>
    <li>php82Extensions.meminfo</li>
    <li>php82Extensions.memprof</li>
    <li>php82Extensions.mongodb</li>
    <li>php82Extensions.msgpack</li>
    <li>php82Extensions.oci8</li>
    <li>php82Extensions.openswoole</li>
    <li>php82Extensions.opentelemetry</li>
    <li>php82Extensions.pcov</li>
    <li>php82Extensions.pdlib</li>
    <li>php82Extensions.pdo_oci</li>
    <li>php82Extensions.pdo_sqlsrv</li>
    <li>php82Extensions.phalcon</li>
    <li>php82Extensions.pinba</li>
    <li>php82Extensions.protobuf</li>
    <li>php82Extensions.pspell</li>
    <li>php82Extensions.rdkafka</li>
    <li>php82Extensions.redis</li>
    <li>php82Extensions.rrd</li>
    <li>php82Extensions.smbclient</li>
    <li>php82Extensions.snuffleupagus</li>
    <li>php82Extensions.spx</li>
    <li>php82Extensions.sqlsrv</li>
    <li>php82Extensions.ssh2</li>
    <li>php82Extensions.swoole</li>
    <li>php82Extensions.uuid</li>
    <li>php82Extensions.uv</li>
    <li>php82Extensions.vld</li>
    <li>php82Extensions.xdebug</li>
    <li>php82Extensions.zstd</li>
    <li>php82Packages.phan</li>
    <li>php83Extensions.amqp</li>
    <li>php83Extensions.apcu</li>
    <li>php83Extensions.apcu.dev</li>
    <li>php83Extensions.ast</li>
    <li>php83Extensions.datadog_trace</li>
    <li>php83Extensions.ds</li>
    <li>php83Extensions.event</li>
    <li>php83Extensions.gnupg</li>
    <li>php83Extensions.grpc</li>
    <li>php83Extensions.igbinary</li>
    <li>php83Extensions.igbinary.dev</li>
    <li>php83Extensions.imagick</li>
    <li>php83Extensions.imap</li>
    <li>php83Extensions.inotify</li>
    <li>php83Extensions.mailparse</li>
    <li>php83Extensions.maxminddb</li>
    <li>php83Extensions.memcache</li>
    <li>php83Extensions.memcached</li>
    <li>php83Extensions.meminfo</li>
    <li>php83Extensions.memprof</li>
    <li>php83Extensions.mongodb</li>
    <li>php83Extensions.msgpack</li>
    <li>php83Extensions.oci8</li>
    <li>php83Extensions.openswoole</li>
    <li>php83Extensions.opentelemetry</li>
    <li>php83Extensions.pcov</li>
    <li>php83Extensions.pdlib</li>
    <li>php83Extensions.pdo_oci</li>
    <li>php83Extensions.pdo_sqlsrv</li>
    <li>php83Extensions.phalcon</li>
    <li>php83Extensions.pinba</li>
    <li>php83Extensions.protobuf</li>
    <li>php83Extensions.pspell</li>
    <li>php83Extensions.rdkafka</li>
    <li>php83Extensions.redis</li>
    <li>php83Extensions.rrd</li>
    <li>php83Extensions.smbclient</li>
    <li>php83Extensions.snuffleupagus</li>
    <li>php83Extensions.spx</li>
    <li>php83Extensions.sqlsrv</li>
    <li>php83Extensions.ssh2</li>
    <li>php83Extensions.swoole</li>
    <li>php83Extensions.uuid</li>
    <li>php83Extensions.uv</li>
    <li>php83Extensions.vld</li>
    <li>php83Extensions.xdebug</li>
    <li>php83Extensions.zstd</li>
    <li>php83Packages.castor</li>
    <li>php83Packages.composer</li>
    <li>php83Packages.composer-local-repo-plugin</li>
    <li>php83Packages.cyclonedx-php-composer</li>
    <li>php83Packages.deployer</li>
    <li>php83Packages.grumphp</li>
    <li>php83Packages.phan</li>
    <li>php83Packages.phing</li>
    <li>php83Packages.phive</li>
    <li>php83Packages.php-codesniffer</li>
    <li>php83Packages.php-cs-fixer</li>
    <li>php83Packages.php-parallel-lint</li>
    <li>php83Packages.phpinsights</li>
    <li>php83Packages.phpmd</li>
    <li>php83Packages.phpstan</li>
    <li>php83Packages.psalm</li>
    <li>php83Packages.psysh</li>
    <li>php84Extensions.amqp</li>
    <li>php84Extensions.apcu</li>
    <li>php84Extensions.apcu.dev</li>
    <li>php84Extensions.ast</li>
    <li>php84Extensions.ds</li>
    <li>php84Extensions.event</li>
    <li>php84Extensions.gnupg</li>
    <li>php84Extensions.grpc</li>
    <li>php84Extensions.igbinary</li>
    <li>php84Extensions.igbinary.dev</li>
    <li>php84Extensions.imagick</li>
    <li>php84Extensions.imap</li>
    <li>php84Extensions.inotify</li>
    <li>php84Extensions.mailparse</li>
    <li>php84Extensions.maxminddb</li>
    <li>php84Extensions.memcache</li>
    <li>php84Extensions.memcached</li>
    <li>php84Extensions.meminfo</li>
    <li>php84Extensions.memprof</li>
    <li>php84Extensions.mongodb</li>
    <li>php84Extensions.msgpack</li>
    <li>php84Extensions.oci8</li>
    <li>php84Extensions.opentelemetry</li>
    <li>php84Extensions.pcov</li>
    <li>php84Extensions.pdlib</li>
    <li>php84Extensions.pdo_sqlsrv</li>
    <li>php84Extensions.pinba</li>
    <li>php84Extensions.protobuf</li>
    <li>php84Extensions.pspell</li>
    <li>php84Extensions.rdkafka</li>
    <li>php84Extensions.redis</li>
    <li>php84Extensions.rrd</li>
    <li>php84Extensions.smbclient</li>
    <li>php84Extensions.snuffleupagus</li>
    <li>php84Extensions.spx</li>
    <li>php84Extensions.sqlsrv</li>
    <li>php84Extensions.ssh2</li>
    <li>php84Extensions.uuid</li>
    <li>php84Extensions.uv</li>
    <li>php84Extensions.vld</li>
    <li>php84Extensions.xdebug</li>
    <li>php84Extensions.zstd</li>
    <li>php84Packages.phan</li>
    <li>phpactor</li>
    <li>phpdocumentor</li>
    <li>phpunit</li>
    <li>pixelfed</li>
    <li>qcachegrind</li>
    <li>roave-backward-compatibility-check</li>
    <li>signaturepdf</li>
    <li>simplesamlphp</li>
    <li>vimPlugins.phpactor</li>
    <li>wp-cli</li>
    <li>yle-dl</li>
    <li>yle-dl.dist</li>
  </ul>
</details>

**Comment by ofalvai** [comment]
Thank you for the base change @SuperSandro2000. I ran nixpkgs-review and fixed one remaining regression, the rest of the build failures are also present on master.

**Comment by drupol** [comment]
Thank you all.

**Pull request merged**
