### PR TITLE
libjack2Unstable: 2015-09-03 -> 2016-08-18

### PR DESCRIPTION
**Pull request by magnetophon**
###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] OS X
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Could you update the name here to follow with the package naming guidelines. 
The attribute in `all-packages.nix` would become `libjack2Unstable` and the name attribute `${prefix}jack2-unstable-2016-08-18`.

**Comment by magnetophon** [comment]
@FRidh like this?

**Comment by FRidh** [comment]
Exactly. Note that `pkgs/development/libraries/libsoundio/default.nix`  depends on the old `libjack2-git`.

**Comment by magnetophon** [comment]
@FRidh No, it doesn't.  ;)

**Pull request merged**
