### PR TITLE
teyjus: 2.0b2 -> 2.1

### PR DESCRIPTION
**Pull request by ryantm**
Semi-automatic update. These checks were done:

- built on NixOS
- ran `/nix/store/s3a893figs9wwy07swfzxbf2ai7g6f1d-teyjus-2.1/bin/tjcc --help` got 0 exit code
- ran `/nix/store/s3a893figs9wwy07swfzxbf2ai7g6f1d-teyjus-2.1/bin/tjdepend --help` got 0 exit code
- ran `/nix/store/s3a893figs9wwy07swfzxbf2ai7g6f1d-teyjus-2.1/bin/tjdis --help` got 0 exit code
- ran `/nix/store/s3a893figs9wwy07swfzxbf2ai7g6f1d-teyjus-2.1/bin/tjlink --help` got 0 exit code
- ran `/nix/store/s3a893figs9wwy07swfzxbf2ai7g6f1d-teyjus-2.1/bin/tjsim --help` got 0 exit code
- found 2.1 with grep in /nix/store/s3a893figs9wwy07swfzxbf2ai7g6f1d-teyjus-2.1
- found 2.1 in filename of file in /nix/store/s3a893figs9wwy07swfzxbf2ai7g6f1d-teyjus-2.1

cc @bcdarwin

### CODE REVIEW

**Comment by vbgl** [comment]
This change does not do what the commit message claims (it probably fixes the hash but does not perform any update). @ryantm did you look at this patch before opening this PR?

**Comment by ryantm** [comment]
@vbgl no. I think it might just be changing the hash format even. I will try to look into how I can prevent this mistake and fix this.

**Comment by joachifm** [comment]
Ah, I missed that, too, sorry

**Comment by ryantm** [comment]
It would have been hard to notice the version update anyway: https://github.com/teyjus/teyjus/issues/117

**Pull request merged**
