### PR TITLE
dpdk: refactor to allow building extapps

### PR DESCRIPTION
**Pull request by abuibrahim**
###### Motivation for this change

These patches enable building external DPDK apps like pktgen. The primary output can now be used as RTE_SDK root.

Kernel modules are split into "kmod".

All apps and examples are bundled together and copied to bin thus ending up on PATH.

After adding the missing dependencies vm_power_mgr is now built into "examples" output.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by abuibrahim** [comment]
I had to massage my previous release-16.03 patches a bit to apply them cleanly on top of master.

**Comment by zimbatm** [comment]
Looking good. Can you just rename the last commit to `pktgen: init at 3.0.00` to follow the CONTRIBUTING guideline ?

**Comment by abuibrahim** [comment]
Sure. Will send another PR shortly.

**Comment by zimbatm** [comment]
No need to make a new PR, you can just amend the last commit and force-push

**Comment by abuibrahim** [comment]
Oops, too late, already sent a new PR. I also rebased on top of master for a smooth fast-forward (in case I beat other 278 PRs in the queue ;)

**Pull request closed without merging**
