### PR TITLE
R: Update R, CRAN, & Bioconductor

### PR DESCRIPTION
**Pull request by jabranham**
###### Motivation for this change
Update R packages @peti

###### Things done
Checked the expression evaluates using `nix-build test-evaluation.nix --dry-run`

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jabranham** [comment]
Added a commit to update R along with its packages @peti

**Comment by jabranham** [comment]
@peti or @timokau Can we merge this?

**Comment by timokau** [comment]
I have never touched those package sets, so I'll defer to @peti.

**Review by peti — COMMENTED** [review]
Test builds are running at https://hydra.nixos.org/jobset/nixpkgs/r-updates. Assuming that all goes well, I'll merge ASAP.

**Comment by jabranham** [comment]
Hydra build finished, looks OK to me.

**Comment by peti** [comment]
The update introduces lots of evaluation errors: https://hydra.nixos.org/jobset/nixpkgs/r-updates#tabs-errors. We can't merge it in that state.

**Comment by peti** [comment]
@jabranham, will you do anything about those evaluation errors?

**Comment by jabranham** [comment]
@peti Sorry, missed that notification somehow. I updated the package sets to today and fixed the evaluation errors, hopefully.

**Comment by peti** [comment]
I re-started Hydra ...

**Pull request merged**
