### PR TITLE
pufferpanel: 2.2.0 -> 2.6.6

### PR DESCRIPTION
**Pull request by tie**
###### Description of changes

Reopening #220407 since changing the target branch accidentally added a lot of folks as reviewers 😅 cc @ckiee

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tie** [comment]
Hm, I see that PufferPanel is marked as broken on Darwin, let me try to build it there before merging 🧐
I wouldn’t be surprised if the new version builds just fine or with some minor addition to build flags. Although I’m on AArch64 so can’t test x86_64 unfortunately.

**Comment by tie** [comment]
Builds and runs on `aarch64-darwin` 🎉
<details>

puffer-aarch64-darwin
</details>

Is to OK to remove the “broken” attribute? I’d assume it works on `x86_64-darwin` too, does the CI check that?

**Comment by ckiee** [comment]
Ofborg should check that once the attribute is removed so yeah, go ahead.

**Comment by tie** [comment]
@ckiee, [done](https://github.com/NixOS/nixpkgs/compare/a8aaf1d04f0e0b9cd23a0f02510b1b091155e74e..c1c44d3ccc3a2d987138ab992ee4ee468676f23c).

**Review by ckiee — APPROVED** [review]

**Comment by ckiee** [comment]
Squash-merging to fix commit message: `pufferpanel: 2.2.0 -> 2.6.6` instead of `v2.6.6`. Thank you!

(CONTRIBUTING.md: There are no GPG signatures and it's a single commit, so nothing is lost here)

**Pull request merged**
