### PR TITLE
nlohmann_json: apply patch for pkg-config path

### PR DESCRIPTION
**Pull request by doronbehar**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 117986` at b2e4ab5d run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>giada</li>
    <li>nix-exec</li>
    <li>nixui</li>
    <li>poedit</li>
  </ul>
</details>
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/333c81b9df68050367f726758c5c56ff">dydisnix</a></li>
    <li><a href="https://gist.github.com/b4a778016a326e021ef75c69386a3d3d">libnixxml</a></li>
    <li><a href="https://gist.github.com/1b41d86a828583093dcd537046789a3f">python39Packages.qiskit</a></li>
    <li><a href="https://gist.github.com/98bdb1431935cef9a606080cbc49f230">python39Packages.qiskit-aer</a></li>
    <li><a href="https://gist.github.com/b8c3358b8ce79979a722a98571a81dfb">python39Packages.qiskit-aqua</a></li>
    <li><a href="https://gist.github.com/7cbf8b784e8f67047df4f0b0d45464e0">python39Packages.qiskit-ibmq-provider</a></li>
    <li><a href="https://gist.github.com/620bf88fceeb3ea8a0917811c1628215">python39Packages.qiskit-ignis</a></li>
  </ul>
</details>
<details>
  <summary>20 packages skipped due to time constraints:</summary>
  <ul>
    <li>cachix</li>
    <li>crate2nix</li>
    <li>haskellPackages.cachix</li>
    <li>haskellPackages.hercules-ci-agent</li>
    <li>haskellPackages.update-nix-fetchgit</li>
    <li>hercules-ci-agent</li>
    <li>hydra-unstable</li>
    <li>nheko</li>
    <li>nix-index</li>
    <li>openrct2</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>45 packages built successfully:</summary>
  <ul>
    <li>bear</li>
    <li>bundix</li>
    <li>cabal2nix</li>
    <li>cpp-ipfs-api</li>
    <li>dep2nix</li>
    <li>disnix</li>
    <li>disnixos</li>
    <li>fusionInventory</li>
    <li>go2nix</li>
    <li>haskellPackages.hercules-ci-cnix-expr</li>
    <li>haskellPackages.hercules-ci-cnix-store</li>
    <li>haskellPackages.nix-paths</li>
    <li>mtxclient</li>
    <li>nix (nixStable)</li>
    <li>nix-bundle</li>
    <li>nix-direnv</li>
    <li>nix-doc</li>
    <li>nix-du</li>
    <li>nix-pin</li>
    <li>nix-plugins</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-cvs</li>
    <li>nix-prefetch-docker</li>
    <li>nix-prefetch-git</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-serve</li>
    <li>nix-update</li>
    <li>nix-update-source</li>
    <li>nixFlakes (nixUnstable)</li>
    <li>nixos-generators</li>
    <li>nixos-shell</li>
    <li>nixpkgs-review</li>
    <li>nlohmann_json</li>
    <li>nwg-launchers</li>
    <li>python38Packages.nix-kernel</li>
    <li>python38Packages.nixpkgs</li>
    <li>python38Packages.pythonix</li>
    <li>python39Packages.nix-kernel</li>
    <li>python39Packages.nixpkgs</li>
    <li>python39Packages.pythonix</li>
    <li>sycl-info</li>
    <li>toxvpn</li>
    <li>vgo2nix</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/libraries/nlohmann_json/default.nix:36:3:
```
   |
36 |   meta = with lib; {
   |   ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

**Comment by doronbehar** [comment]
Similarly to what happened with [spdlog's update](https://github.com/NixOS/nixpkgs/pull/117987), the build failures noted above are false as it seems.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 117986` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package marked as broken and skipped:
</summary>
<ul>
<li>nix-exec</li>
</ul>
</details>
<details>
<summary>
2 packages blacklisted:
</summary>
<ul>
<li>tests.nixos-functions.nixos-test</li>
<li>tests.nixos-functions.nixosTest-test</li>
</ul>
</details>
<details>

  <summary>2 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>dydisnix: log was empty</li>
<li>libnixxml: log was empty</li>
  </ul>
</details>
<details>

  <summary>2 packages failed to build and are new build failures:</summary>
  <ul>
<li>yuzu-ea: log was empty</li>
<li>yuzu-mainline: log was empty</li>
  </ul>
</details>
<details>
<summary>
77 packages built:
</summary>
<ul>
<li>bear</li>
<li>bundix</li>
<li>cabal2nix</li>
<li>cachix</li>
<li>common-updater-scripts</li>
<li>cpp-ipfs-api</li>
<li>crate2nix</li>
<li>crystal2nix</li>
<li>dep2nix</li>
<li>disnix</li>
<li>disnixos</li>
<li>fusionInventory</li>
<li>giada</li>
<li>go2nix</li>
<li>haskellPackages.cachix</li>
<li>haskellPackages.hercules-ci-agent</li>
<li>haskellPackages.hercules-ci-cnix-expr</li>
<li>haskellPackages.hercules-ci-cnix-store</li>
<li>haskellPackages.nix-paths</li>
<li>haskellPackages.update-nix-fetchgit</li>
<li>hercules-ci-agent</li>
<li>hydra-unstable</li>
<li>lispPackages.quicklisp-to-nix</li>
<li>lispPackages.quicklisp-to-nix-system-info</li>
<li>mtxclient</li>
<li>nheko</li>
<li>nix (nixStable)</li>
<li>nix-bundle</li>
<li>nix-direnv</li>
<li>nix-doc</li>
<li>nix-du</li>
<li>nix-index</li>
<li>nix-pin</li>
<li>nix-plugins</li>
<li>nix-prefetch</li>
<li>nix-prefetch-bzr</li>
<li>nix-prefetch-cvs</li>
<li>nix-prefetch-docker</li>
<li>nix-prefetch-git</li>
<li>nix-prefetch-hg</li>
<li>nix-prefetch-scripts</li>
<li>nix-prefetch-svn</li>
<li>nix-serve</li>
<li>nix-update</li>
<li>nix-update-source</li>
<li>nixFlakes (nixUnstable)</li>
<li>nixos-generators</li>
<li>nixos-rebuild</li>
<li>nixos-shell</li>
<li>nixpkgs-review</li>
<li>nixui</li>
<li>nlohmann_json</li>
<li>nwg-launchers</li>
<li>openrct2</li>
<li>poedit</li>
<li>pothos</li>
<li>python38Packages.nix-kernel</li>
<li>python38Packages.nixpkgs</li>
<li>python38Packages.pythonix</li>
<li>python38Packages.qiskit</li>
<li>python38Packages.qiskit-aer</li>
<li>python38Packages.qiskit-aqua</li>
<li>python38Packages.qiskit-ibmq-provider</li>
<li>python38Packages.qiskit-ignis</li>
<li>python39Packages.nix-kernel</li>
<li>python39Packages.nixpkgs</li>
<li>python39Packages.pythonix</li>
<li>python39Packages.qiskit</li>
<li>python39Packages.qiskit-aer</li>
<li>python39Packages.qiskit-aqua</li>
<li>python39Packages.qiskit-ibmq-provider</li>
<li>python39Packages.qiskit-ignis</li>
<li>sycl-info</li>
<li>toxvpn</li>
<li>update-nix-fetchgit</li>
<li>vgo2nix</li>
<li>vulnix</li>
</ul>
</details>

**Comment by rmcgibbo** [comment]
> Similarly to what happened with spdlog's update, the build failures noted above are false as it seems.

Are they false, or just specific to aarch64?

**Comment by doronbehar** [comment]
> > Similarly to what happened with spdlog's update, the build failures noted above are false as it seems.
> 
> Are they false, or just specific to aarch64?

Aish :grimacing: didn't notice that. I'll pay more attention next time. From some reason I can't find the job for these packages on Hydra, both on the website and with hydra-check:

```
$ hydra-check --arch=aarch64-linux python38Packages.qiskit
Build Status for nixpkgs.python38Packages.qiskit.aarch64-linux on unstable
⚠ This job is not a member of the latest evaluation of its jobset. This means it was removed or had an evaluation error.
```

**Comment by doronbehar** [comment]
I did find these hydra jobs now:

```
$ hydra-check --arch=aarch64-linux --channel=master python38Packages.qiskit
Build Status for python38Packages.qiskit.aarch64-linux on master
✖ (Dependency failed) python3.8-qiskit-0.24.1 from 2021-03-30 - https://hydra.nixos.org/build/140418441

Last Builds:
✖ (Dependency failed) python3.8-qiskit-0.24.1 from 2021-03-26 - https://hydra.nixos.org/build/140299143
✖ (Dependency failed) python3.8-qiskit-0.24.0 from 2021-03-26 - https://hydra.nixos.org/build/140238877
✖ (Cancelled) python3.8-qiskit-0.24.0 from 2021-03-25 - https://hydra.nixos.org/build/139956441
✖ (Dependency failed) python3.8-qiskit-0.24.0 from 2021-03-20 - https://hydra.nixos.org/build/139535622
✖ (Dependency failed) python3.8-qiskit-0.24.0 from 2021-03-19 - https://hydra.nixos.org/build/139339204
✖ (Dependency failed) python3.8-qiskit-0.24.0 from 2021-03-13 - https://hydra.nixos.org/build/138956506
✖ (Dependency failed) python3.8-qiskit-0.24.0 from 2021-03-10 - https://hydra.nixos.org/build/138816214
✖ (Dependency failed) python3.8-qiskit-0.24.0 from 2021-03-08 - https://hydra.nixos.org/build/138487900
✖ (Dependency failed) python3.8-qiskit-0.24.0 from 2021-03-08 - https://hydra.nixos.org/build/138460968
```

**Pull request merged**
