### PR TITLE
Firefox: 122.0.1 -> 123.0; 115.7.0esr -> 115.8.0esr

### PR DESCRIPTION
**Pull request by mweinelt**
https://www.mozilla.org/en-US/firefox/123.0/releasenotes/
https://www.mozilla.org/en-US/firefox/115.8.0/releasenotes/

Status: testing

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mweinelt** [comment]
Tested 123.0 on x86_64-linux wlroots/pipewire with working WebGL, Camera, Microphone, Screensharing. Video-Playback (incl. hwdec).

Built all versions on both x86_64-linux and aarch64-linux.

**Comment by sdht0** [comment]
Is firefox beta/dev-edition not as well supported as stable in nixpkgs? #287063 has been open for couple of weeks now. I have been using the dev-edition for early access to features, but was quite surprised to see it still on v121.

Since a browser is a security critical software, I was expecting special attention to the version updates, and for now, it seems I should be on stable firefox to get that.

**Comment by sdht0** [comment]
Thanks for the explanation and the merge! Was just asking to understand the support levels. 

Automating the updates should help I think? ryan-tm's automatic updates doesn't work right now and something like #289404 is probably what is needed to make it work.
  
https://r.ryantm.com/log/firefox-devedition-unwrapped/2024-02-18.log
https://r.ryantm.com/log/firefox-beta-bin-unwrapped/2024-02-19.log

**Comment by mweinelt** [comment]
Possibly. We'll revisit that PR shortly before branching off for NixOS 24.05, to minimize the need for manual backports.

**Comment by sdht0** [comment]
Alright, thanks again.

**Comment by vcunat** [comment]
Release notes are up.

**Comment by benaryorg** [comment]
Are there any known issues related to X11 mouse-cursor things in this Firefox release that I *somehow* managed to not find when searching the internet?

I ended up bisecting nixpkgs and this merge seems to be the one causing the issue of me not having the proper "hand" kind of X11 cursor when hovering over links and such in Firefox when running on NixOS 23.11.
Well, technically the backport to 23.11 was the merge that came up, but this here seems like the proper place to ask if anyone knows anything about this before I did deeper.
It may be specific to my setup, I have barely checked anything yet, but I also haven't heard a big outcry from my bubble yet so I would assume this only hits a fairly small portion of users anyway, and finding something in a software as big as Firefox that causes this kind of behaviour.… uhh.… I'm not getting my hopes up just yet.

Since I've been bisecting (and for good measure rebooting my entire device for proper testing) for like the past half hour which means I won't debug this for a few hours, but if anyone else has a similar issue or knows of something related please ping me, otherwise I'll pick this up after I got some sleep and create a proper issue if this is something that I can't isolate to my setup specifically.
Any help is appreciated of course.

**Comment by vcunat** [comment]
@benaryorg: one person mentioned exactly that in the chat (except I don't know which NixOS version)
https://matrix.to/#/!PbcQeaWcgMyjVfeGQN:nixos.org/$gudRfRLHuIPbnZvKtnXJOWVWuBvkuXw_JdUJ0DptUlg?via=nixos.org&via=matrix.org&via=mozilla.org

**Comment by ajs124** [comment]
I feel like we've had something similar before. Is your cursor theme in the nix store or somewhere outside it?

**Comment by benaryorg** [comment]
> I feel like we've had something similar before. Is your cursor theme in the nix store or somewhere outside it?

I am using the default X cursor theme, the one that AFAIK is baked into X.

---

I wrote [a little flake to reproduce this](https://gist.github.com/benaryorg/b44dc8a6d9b15ae2ddc54667629f25ec):

```bash
nixos-rebuild build-vm --flake git+https://gist.github.com/benaryorg/b44dc8a6d9b15ae2ddc54667629f25ec#test --no-write-lock-file && ./result/bin/run-nixos-vm && rm nixos.qcow2
```

1. when running this you should be automatically logged into a user account on the XFCE X11 install
1. open up a terminal using the bottom bar
1. run `firefox-good`, and observe how hovering over the language-link of Wikipedia works fine, close firefox and wait until the command exits in the prompt
1. run `firefox-bad`, and observe how hovering over the language-link of Wikipedia doesn't change the cursor, close firefox and wait until the command exits in the prompt
1. shut down the VM using the top-right XFCE menu (labelled "user" here)

If you want to debug some more the flake has the serial console as well as the gettys configured to autologin as root.

---

Since this looks more like an upstream issue to me, considering that none of the dependencies or anything else about NixOS has changed here I think I should direct this towards the upstream Bugzilla since this is a rather.… uhh.… in-depth tech stack that I haven't got the first idea about how to debug it.
Unless anyone else here has some input on this I would go ahead with the upstream report in like 24h or so.

---

While editing this comment I just noticed this also applies to the special cursor symbol for resizing the GitHub comment textbox too, so it's not just the "click this thing" kind of cursor, however it does *not* affect the text cursor.

**Comment by benaryorg** [comment]
It seems that upstream has a bug for this actually: https://bugzilla.mozilla.org/show_bug.cgi?id=1876366
Please don't ask me how I missed that one when I was looking for something.

**Comment by brprice** [comment]
I'm also affected by the "Firefox 123 cursor broken / not changing when hovering over links" issue. From that upstream bug report it seems like it is an issue with old-fashioned X11 cursors which I guess will only affect people not running a DE and who haven't customized cursor/icon theme.

I see the issue running uncustomized openbox, and have found one workaround is customizing my cursor, e.g. `nix build nixpkgs#vanilla-dmz && XCURSOR_PATH=$(readlink ./result)/share/icons/ XCURSOR_THEME=Vanilla-DMZ firefox`. (I'm sure there is a better method of doing this customization permanently, but not sure what it is.)

Some possibly helpful links:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1876366 (the upstream bug already linked above)
- https://wiki.archlinux.org/title/Cursor_themes#Configuration
- https://github.com/NixOS/nixpkgs/issues/22652
- https://nixos.wiki/wiki/Cursor_Themes (only talks about home-manager)

**Pull request merged**
